### PR TITLE
Improve preprocessing text docs

### PR DESCRIPTION
**Pull request by jaketae**
Added docstrings from the original keras_preprocessing repo to provide better readability of docs. Also included examples to help demonstrate how each function can be used.

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by gbaned** [comment]
@jaketae Can you please check build failures. Thanks!

**Comment by mihaimaruseac** [comment]
In particular, the error that needs fixing looks like

```
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/keras/distribute/keras_dnn_correctness_test.runfiles/org_tensorflow/tensorflow/python/keras/distribute/keras_dnn_correctness_test.py", line 27, in <module>
    from tensorflow.python.keras.distribute import keras_correctness_test_base
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/keras/distribute/keras_dnn_correctness_test.runfiles/org_tensorflow/tensorflow/python/keras/distribute/keras_correctness_test_base.py", line 36, in <module>
    from tensorflow.python.keras.preprocessing import sequence
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/keras/distribute/keras_dnn_correctness_test.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 28, in <module>
    from tensorflow.python.keras.preprocessing import text
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/keras/distribute/keras_dnn_correctness_test.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/text.py", line 58, in <module>
    @keras_export('tf.keras.preprocessing.text.one_hot')
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/keras/distribute/keras_dnn_correctness_test.runfiles/org_tensorflow/tensorflow/python/util/tf_export.py", line 281, in __init__
    self._validate_symbol_names()
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/keras/distribute/keras_dnn_correctness_test.runfiles/org_tensorflow/tensorflow/python/util/tf_export.py", line 308, in _validate_symbol_names
    'Can only export symbols under package name of component. '
tensorflow.python.util.tf_export.InvalidSymbolNameError: Can only export symbols under package name of component. e.g. tensorflow_estimator must export all symbols under tf.estimator
```

**Comment by mihaimaruseac** [comment]
Let's try replacing `keras_export` with `tf_export`

**Comment by jaketae** [comment]
@mihaimaruseac Thank you for the heads up. I reviewed my previous commit and realized that this line might be the cause of the problem: 
```python
@keras_export('tf.keras.preprocessing.text.one_hot')
```
I've fixed this line to be `@keras_export('keras...')` and got rid of the `tf` part. If this doesn't fix the issue, then I will try applying `@tf_export` instead. Thanks again!

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
That seems to have solved the first issue but now there is another one

```
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest tensorflow.python.keras.preprocessing.text.one_hot[1]>", line 1, in <module>
        tf.keras.preprocessing.text.one_hot(text, 20)
      File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/text.py", line 86, in one_hot
        return text.one_hot(
    AttributeError: 'str' object has no attribute 'one_hot'
```

**Comment by jaketae** [comment]
@mihaimaruseac I see. Do you think this is caused by the fact that `text` is both a parameter of the function as well as the name of the module we are importing from (`from keras_preprocessing import text`)?

**Comment by mihaimaruseac** [comment]
It's likely

**Comment by jaketae** [comment]
@mihaimaruseac I am considering two possibilities:

- Changing the function parameter to something like `input_text` instead of `input` to resolve build error
- Closing this issue and opening a new PR migrating `keras_preprocessing` to the TF repo entirely

The first option seems more reasonable, but if the long-term goal is to reduce dependency on Keras exports, maybe we can consider the latter as well. At any rate, the two options are not mutually exclusive, so I guess we could first come up with an alternate name for the parameter (is `input_text` permissible?).

**Comment by mihaimaruseac** [comment]
Let's go with the first approach for now as keras tries to separate from TF.

Also, I just realized this might also need an API review from the API owners. But let's get the test green first and then I'll add the proper labels

**Comment by jaketae** [comment]
@mihaimaruseac I've replaced `text` with `input_text`; hopefully this will resolve the conflict with Keras imports. Thank you.

**Review by mihaimaruseac — DISMISSED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Review by Dynmi — APPROVED** [review]

**Comment by zjzh** [comment]
Hello,  @jaketae @mihaimaruseac , therefore, is the problem because that ”text“ is conflict with module name?

**Comment by jaketae** [comment]
> Hello, @jaketae @mihaimaruseac , therefore, is the problem because that ”text“ is conflict with module name?

Hi @zjzh, yes, I believe that was the problem if I recall correctly.

**Pull request merged**
