### PR TITLE
Update soft NMS factor as per research paper

### LINKED ISSUE #40253: Difference of 0.5 factor compared to Research Paper in Soft NMS implementation
Hi,

I believe the below lines are for Gaussian implementation of Soft-NMS, since the variable 'scale' is used in:
https://github.com/tensorflow/tensorflow/blob/7474d3c8345d663cea3f9132c47cd1bd342b0cec/tensorflow/core/kernels/non_max_suppression_op.cc#L189
https://github.com/tensorflow/tensorflow/blob/7474d3c8345d663cea3f9132c47cd1bd342b0cec/tensorflow/core/kernels/non_max_suppression_op.cc#L194

But in the research paper, no multiplier of 0.5 is mentioned. Please refer page number 4 of [https://arxiv.org/pdf/1704.04503.pdf](https://arxiv.org/pdf/1704.04503.pdf).

So if paper suggests ideal sigma value of 0.5, should I configure value of 0.25 instead?

### PR DESCRIPTION
**Pull request by sachinprasadhs**
Updated soft NMS factor as per research paper https://arxiv.org/pdf/1704.04503.pdf (page 4)
Fixes: https://github.com/tensorflow/tensorflow/issues/40253

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @cantonios Can you please review this PR ? Thank you!

**Review by mihaimaruseac — APPROVED** [review]
Approving, but note that changing these values could break tests so we might just revert.

**Comment by cantonios** [comment]
There are test failures:
-  `tensorflow/core/kernels/image:non_max_suppression_op_test`
-  `tensorflow/python:image_ops_test`

Can you fix those?

**Comment by gbaned** [comment]
Hi @sachinprasadhs Can you please check @cantonios's comments and keep us posted ? Thank you!

**Review by cantonios — CHANGES_REQUESTED** [review]
See comment about failing tests.

**Comment by gbaned** [comment]
Hi @sachinprasadhs Can you please check @cantonios's [comments](https://github.com/tensorflow/tensorflow/pull/58754#pullrequestreview-1327269242). Thank you!

**Pull request closed without merging**
