### PR TITLE
Add float64 to _valid_dtypes in Optimizer

### PR DESCRIPTION
**Pull request by siddharth-agrawal**
Added float64 to _valid_dtypes in class Optimizer(). Tested locally.

This solves #1061 as well as #761. For #1061, the change was tested with the clip_by_value operator as mentioned in [this comment](https://github.com/tensorflow/tensorflow/issues/1061#issuecomment-219238294).

### CODE REVIEW

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
some other tests failed, please take a look

**Comment by siddharth-agrawal** [comment]
@vrv Fixed the errors. This time I ran all the tests.

**Comment by vrv** [comment]
Thanks, seems reasonable -- I guess we were testing that float64 wasn't supported explicitly...

@tensorflow-jenkins test this please

**Pull request merged**
