### PR TITLE
[INTEL MKL] Fixing a build error in a test

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**

### CODE REVIEW

**Comment by penpornk** [comment]
I think @ezhulenev is a better reviewer for this.

**Comment by ezhulenev** [comment]
What is the build error? This test should not be fully disabled, it tests not only custom contraction kernels, but Eigen spatial convolution in general.

**Comment by mahmoud-abuzaina** [comment]
@ezhulenev this the build error message:
error: 'QInt8' in namespace 'Eigen' does not name a type
At this line: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/eigen_spatial_convolutions_test.cc#L1758

**Comment by ezhulenev** [comment]
Can you try to add few extra headers:

```
#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
// Disable clang-format to prevent 'FixedPoint' header from being included
// before 'Tensor' header on which it depends.
// clang-format off
#include "third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint"
// clang-format on
```

**Comment by mahmoud-abuzaina** [comment]
If I add the above headers, I get another build error:
`./tensorflow/core/kernels/eigen_spatial_convolutions-inl.h:1479:3: error: static assertion failed: YOU_MADE_A_PROGRAMMING_MISTAKE
   EIGEN_STATIC_ASSERT((nr == 4), YOU_MADE_A_PROGRAMMING_MISTAKE)
   ^`

**Comment by ezhulenev** [comment]
I think putting just https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/eigen_spatial_convolutions_test.cc#L1837-L1845 inside #ifdef should fix the issue

**Comment by mahmoud-abuzaina** [comment]
Thank you. I updated the PR with your last suggestion.

**Review by ezhulenev — APPROVED** [review]

**Comment by ezhulenev** [comment]
Thanks!

**Pull request merged**
