### PR TITLE
Only run test that requires int64 support when the driver supports int64

### PR DESCRIPTION
**Pull request by DavidNorman**
Making a test that requires int64 support conditional on support from int64 in the device under test.

### CODE REVIEW

**Review by hawkinsp — APPROVED** [review]
The parentheses around the if condition aren't necessary. But the change looks good to me.

**Comment by DavidNorman** [comment]
thanks for that.  agreed about the ().  I guess I've been switching languages too quickly

**Comment by DavidNorman** [comment]
hi guys.  is there a long waiting list for the sanity checks?  strange that it has not gone through, if it is an automated system.

**Comment by hawkinsp** [comment]
Jenkins, test this please.

**Comment by hawkinsp** [comment]
The tests have to be manually triggered, either by the reviewer or by the person triaging pull requests. Apologies for not triggering them myself last week --- I was out of office.

**Comment by DavidNorman** [comment]
cheers.  nice one.

**Pull request merged**
