### PR TITLE
[INTEL MKL] Updating QuantizeV2 and Dequantize Ops with API changes in MKLDNN 1.0

### PR DESCRIPTION
**Pull request by mdfaijul**
This PR updates QuantizeV2 and Dequantize Ops for API changes in MKLDNN 1.0.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Comment by mdfaijul** [comment]
@penpornk Is there any issue with  

> import/copybara — An error happened while migrating the change

**Comment by penpornk** [comment]
@mdfaijul Yeah, something seems wrong. Let me rerun the tests again to re-trigger import/copybara.

**Comment by mdfaijul** [comment]
@penpornk Thanks for rerunning. Let me know if there is any issue from our side.

**Pull request merged**
