### PR TITLE
Speedup ResizeNearestNeighborGrad.

### PR DESCRIPTION
**Pull request by WindQAQ**
Speedup `ResizeNearestNeighborGrad` on CPU. Thread over batch and vectorization over channel. Because there is a non-negligible overhead for non-vectorized sizes within `Eigen::Map<Eigen::Vector>`, vectorization is only enabled when `channels > kPacketSize`. See the benchmark on  `(1, 250, 250, 1) | (499, 499)` and `(1, 250, 250, 3) | (499, 499)`.

On **Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz**

| Input shape `(N, IH, IW, C)` | Output shape `(OW, OH)` | Original | Thread | Vectorization | Thread + Vectorization | This PR (Mixin vectorization) |
| --------------------------------| ---------------------------- | ---   | -------| --------------- | --------------------------|  ----|
| (1, 125, 125, 1)                       | (250, 250)                          | 138        |  148         |  142                      |      122                                 | 148 |
| (1, 125, 125, 3)                       | (250, 250)                          | 318        |  339         |   344                     |       278                                | 318 |
| (1, 125, 125, 16)                       | (250, 250)                          | 456        | 445          |  574                      |     505                                  | 509 |
| (1, 125, 125, 21)                       | (250, 250)                          | 403        |  431         |  494                      |     457                                  | 497 |
| (10, 125, 125, 1)                       | (250, 250)                          | 288        |   438        |  226                      |     415                                  | 468 |
| (10, 125, 125, 3)                       | (250, 250)                          | 279        |   405        |  397                      |     406                                  | 356 |
| (10, 125, 125, 16)                       | (250, 250)                          | 355        |   488        | 466                       |   460                                    | 462 |
| (10, 125, 125, 21)                       | (250, 250)                          | 387        |   491        |  480                      |   474                                    | 451 |
| (1, 499, 499, 1)                       | (250, 250)                          | 310        |  344         |    299                    |       254                                | 346 |
| (1, 499, 499, 3)                       | (250, 250)                          | 669        |  738         |   797                     |       578                                | 739 |
| (1, 499, 499, 16)                       | (250, 250)                          | 1006        |  1083         |  2424                     |   1914                                    | 1870 |
| (1, 499, 499, 21)                       | (250, 250)                          |  962       |   1168        |   2014                     |    1520                                   | 1509 |
| (10, 499, 499, 1)                       | (250, 250)                          |  495       |   1475        |  329                      |      1136                                 | 1586 |
| (10, 499, 499, 3)                       | (250, 250)                          |  885       |  2321         |   802                     |      2139                                 | 2557 |
| (10, 499, 499, 16)                       | (250, 250)                          |  954       |  2202         |  2004                      |    2532                                   | 2603 |
| (10, 499, 499, 21)                       | (250, 250)                          | 993        |   2119        |  1814                      |      2607                                 | 2262 |

The number is computed as `time / (iterations * N * IH * IW * C)`, the higher the better.

### CODE REVIEW

**Comment by gbaned** [comment]
@WindQAQ  Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@WindQAQ Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
