### PR TITLE
Add C++ SegmentSum gradient operation.

### PR DESCRIPTION
**Pull request by theflofly**
This pull request adds the C++ counter part of the gradient of the SegmentSum python operation.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @suharshs: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by theflofly** [comment]
It's been more than a month now...

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @suharshs: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by suharshs** [comment]
Truly sorry for the delay. This slipped under my radar :( . Looks great!

**Review by suharshs — APPROVED** [review]

**Comment by theflofly** [comment]
What is the next step?
Can someone do a "please test"?

**Pull request merged**
