### PR TITLE
hash with a new seed when hash collision is found

### PR DESCRIPTION
**Pull request by yann-yy**

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by gbaned** [comment]
@yann-yy can you please check build failures? Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by yann-yy** [comment]
I have checked the failure of Ubuntu Python2 CI. And I don't think my commit will cause errors like this. And I doubt whether these 3 failed cases of py3 is necessary in py2 CI?
?

**Comment by mihaimaruseac** [comment]
Ignore the py3 changes, they're going to be fixed soon

**Comment by yann-yy** [comment]
So I'm suppose to wait the fix on master, and merge the changes into my branch then continue the PR?

**Comment by mihaimaruseac** [comment]
We'll take care of it, you won't have to do anything except if there are conflicts

**Comment by yann-yy** [comment]
Thank you @mihaimaruseac

**Pull request merged**
