### PR TITLE
Added a resource

### PR DESCRIPTION
**Pull request by alifelham**

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @MarkDaoust Can you please review this PR ? Thank you!

**Review by MarkDaoust — APPROVED** [review]
Seems reasonable to me.

**Comment by alifelham** [comment]
Hi, could you please add me as an author to the commit? It doesn't show that I have made a contribution to this approved pull request.

**Comment by mihaimaruseac** [comment]
https://github.com/tensorflow/tensorflow/commit/e84884379ab15ed41e6060dcf189ef47a6694157 has you as author

**Review by alifelham — COMMENTED** [review]
Perfect

**Pull request merged**
