### PR TITLE
[INTEL MKL] Adding CentOS 8 oneDNN partials and dockerfiles

### PR DESCRIPTION
**Pull request by ashahba**
This PR introduces [oneDNN](https://github.com/oneapi-src/oneDNN) Partials and Dockerfiles for TensorFlow.

In order to regenerate the files simply run:

```
$ cd tensorflow/tools/dockerfiles
$ alias asm_dockerfiles="docker run --rm -u $(id -u):$(id -g) -v $(pwd):/tf tf-tools python3 assembler.py "
$ alias asm_images="docker run --rm -v $(pwd):/tf -v /var/run/docker.sock:/var/run/docker.sock tf-tools python3 assembler.py "

$ asm_dockerfiles --release dockerfiles --construct_dockerfiles
$ sed -i '' -e 's/Copyright 2019 The TensorFlow Authors/Copyright 2020 The TensorFlow Authors/g' dockerfiles/onednn/*
$ TF_VERSION=2.2.0 && asm_images --release centos-onednn --repository intel/intel-optimized-tensorflow --arg BAZEL_VERSION=2.0.0 --arg TF_BRANCH=v${TF_VERSION} --arg TF_PACKAGE_VERSION=${TF_VERSION} --arg _TAG_PREFIX=${TF_VERSION}-centos --build_images --only_tags_matching '.*centos-.*'
 ```
Once the images are built you should have the following:
```
intel/intel-optimized-tensorflow:2.2.0-centos-8
intel/intel-optimized-tensorflow:2.2.0-centos-8-devel
intel/intel-optimized-tensorflow:2.2.0-centos-8-jupyter
intel/intel-optimized-tensorflow:2.2.0-centos-8-devel-jupyter
intel/intel-optimized-tensorflow:2.2.0-centos-8-mpi-horovod
intel/intel-optimized-tensorflow:2.2.0-centos-8-devel-mpi-horovod
intel/intel-optimized-tensorflow:2.2.0-centos-8-mpi-horovod-jupyter
intel/intel-optimized-tensorflow:2.2.0-centos-8-devel-mpi-horovod-jupyter
intel/intel-optimized-tensorflow:2.2.0-centos-8-mpich-horovod
intel/intel-optimized-tensorflow:2.2.0-centos-8-devel-mpich-horovod
intel/intel-optimized-tensorflow:2.2.0-centos-8-mpich-horovod-jupyter
intel/intel-optimized-tensorflow:2.2.0-centos-8-devel-mpich-horovod-jupyter
```

### CODE REVIEW

**Comment by ashahba** [comment]
Hi @angerson 
Please feel free to review and let me know if you have any questions.

Thanks.

**Comment by ashahba** [comment]
Hi @angerson 
Any feedback on this?

**Comment by angerson** [comment]
Thanks for the ping. Sorry I'm late on this.

I may be missing something, but is there something in the way of combining the many new sections? They look repetitive, so it seems like they could get expanded.

**Comment by ashahba** [comment]
You mean for `spec.yaml` file? I can look into that.

**Comment by angerson** [comment]
Yeah, in spec.yaml. Thanks!

**Comment by ashahba** [comment]
Cool. I'll take a stab at simplifying it.

**Comment by gbaned** [comment]
@ashahba Any update on this PR? Please. Thanks!

**Comment by ashahba** [comment]
@gbaned I got it bit busy last week, I'll make sure to get this updated again in the next few days.

**Comment by ashahba** [comment]
Sorry @angerson I've been a bit busy to update this PR. But I'll get to it soon.

**Comment by ashahba** [comment]
Hi @angerson 
The file a bit more organized now and some duplicates have been removed. Users should be able to generate images this way now:

```bash
TF_VERSION=2.3.0 && \
asm_images \
    --release onednn \
    --repository intel/intel-optimized-tensorflow \
    --arg BAZEL_VERSION=3.1.0 \
    --arg TF_BRANCH=v${TF_VERSION} \
    --arg TF_PACKAGE_VERSION=${TF_VERSION} \
    --arg _TAG_PREFIX=${TF_VERSION}-centos \
    --build_images \
    --only_tags_matching '.*centos-8-.*$'
```

and that'll generate the following images:
```
intel/intel-optimized-tensorflow:2.3.0-centos-8
intel/intel-optimized-tensorflow:2.3.0-centos-8-devel
intel/intel-optimized-tensorflow:2.3.0-centos-8-devel-jupyter
intel/intel-optimized-tensorflow:2.3.0-centos-8-devel-mpich-horovod
intel/intel-optimized-tensorflow:2.3.0-centos-8-devel-mpich-horovod-jupyter
intel/intel-optimized-tensorflow:2.3.0-centos-8-devel-mpi-horovod
intel/intel-optimized-tensorflow:2.3.0-centos-8-devel-mpi-horovod-jupyter
intel/intel-optimized-tensorflow:2.3.0-centos-8-jupyter
intel/intel-optimized-tensorflow:2.3.0-centos-8-mpich-horovod
intel/intel-optimized-tensorflow:2.3.0-centos-8-mpich-horovod-jupyter
intel/intel-optimized-tensorflow:2.3.0-centos-8-mpi-horovod
intel/intel-optimized-tensorflow:2.3.0-centos-8-mpi-horovod-jupyter
```

**Comment by gbaned** [comment]
@angerson  Can you please take a look on above comments from @ashahba. Thanks!

**Comment by ashahba** [comment]
Hi @angerson would you please review?

Thanks.

**Comment by angerson** [comment]
Thanks for the ping. I just got back from a long vacation.

**Review by angerson — APPROVED** [review]
Looks good to me. I'm starting to wonder how we can make sure these don't get confusing for future maintainers, as the unofficial configurations now vastly outnumber the official ones. Not an issue for this PR, though; I'll just keep it in mind for the docker-and-related-tools inventory I'm working on through the rest of this quarter.

Thanks for your work!

**Comment by ashahba** [comment]
Sounds great @angerson 
If there is any area that I can contribute to, or a design document that you like to review please feel free to tag me.

Thanks.

**Pull request merged**
