### PR TITLE
add not equal op to tf_op_files.txt

### PR DESCRIPTION
**Pull request by resec**
Adding the kernel op `NotEqual` to tf_ops_list.txt

### CODE REVIEW

**Comment by martinwicke** [comment]
@petewarden, ping?

**Comment by drpngx** [comment]
@petewarden any luck with this?

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by petewarden — APPROVED** [review]
Sorry for the extremely late review, approved.

**Pull request merged**
