### PR TITLE
[INTEL MKL] Comparison and cast op fusion

### PR DESCRIPTION
**Pull request by Solaryee**
In this PR, comparison op(bf16/fp32->bool) and cast op(bool->bf16/fp32) is fused into one(bf16/fp32->bf16/fp32). The reason to do this fusion is that comparison functors do not support vectorization, but new added scalar_cmp_with_cast_op functor supports vectorization. This can help greatly improve the performance of comparison op, especially for bf16.

This pr was submitted in https://github.com/tensorflow/tensorflow/pull/41047 but got reverted in https://github.com/tensorflow/tensorflow/commit/3f49de584cb7a9de005457006132f5720cc14dd6.

### CODE REVIEW

**Comment by gbaned** [comment]
@ShengYang1  Can you please resolve conflicts? Thanks!

**Comment by ShengYang1** [comment]
> @ShengYang1 Can you please resolve conflicts? Thanks!

Done.

**Review by ezhulenev — APPROVED** [review]

**Comment by yimeisun123** [comment]
@ezhulenev - after this PR is merged, the changes got reverted by a follow-on commit (pasted below). Could you please share the reason of this revert?
(FYI - @ShengYang1, @agramesh1  )
`commit 7085dc4947b8237dac752e1c1cb32ff8e1f1e279
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Tue Aug 3 06:29:08 2021 -0700
    Internal change
    PiperOrigin-RevId: 388440280
    Change-Id: Ib18d245a11fbee823c755881b29b91f394778cd2
`

**Comment by ashiqimranintel** [comment]
Any update on this?

**Pull request merged**
