### PR TITLE
Print/return the result with the highest accuracy

### PR DESCRIPTION
**Pull request by urmilshroff**
Small hotfix to print the most accurate prediction instead of the least accurate prediction, like it was doing before!

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 17 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 32 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 47 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jsimsa: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by jsimsa** [comment]
Hi @urmilshroff, when you say "like it was doing before" what are you referring to? As far as I can tell the code that you are changing was introduced by https://github.com/tensorflow/tensorflow/pull/9261/files and never changed since.

**Comment by urmilshroff** [comment]
@jsimsa I don't remember exactly, but when I had used the `label_image.py` file earlier in my project (sometime around January 2019), it was working fine. Then I messed it up and re-downloaded the file from the TF repo, and realized it wasn't returning the proper values. I'm on vacation and will clarify further once I get my laptop, if the need be.

**Comment by jsimsa** [comment]
OK. The last change to that file happened in 02/2018 so chances are something else have changed in your setup and I am hesitant to accept your "fix".

**Pull request closed without merging**
