### PR TITLE
Expose `assign_moving_average` via public API

### LINKED ISSUE #35118: Expose assign_moving_average via public API
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): `master`
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
`assign_moving_average` does not have a public API (`tf.assign_moving_average`). 

**Will this change the current api? How?**
`tf.assign_moving_average` instead of `tensorflow.python.training.moving_averages.assign_moving_average`

**Who will benefit with this feature?**

We're using it in https://github.com/tensorflow/addons/pull/760, and having a public API would be super useful. 

**Any Other info.**

### PR DESCRIPTION
**Pull request by Squadrick**
Closes #35118

### CODE REVIEW

**Comment by jaingaurav** [comment]
@robieta: Does it make sense to export this API?

**Comment by robieta** [comment]
My inclination is not to, as it would extend the API surface and it's not clear that it justifies the maintenance cost. (We have lots of symbols already.) However we can ask api-owners. I definitely don't think it should be a top-level symbol; `tf.train.assign_moving_average` might be fine since `tf.train.ExponentialMovingAverage` already exists.

By the way, it's already (mostly) exported via `tf.keras.backend.moving_average_update`, so if you just need a public symbol will that suffice?

**Comment by Squadrick** [comment]
@robieta `tf.keras.backend.moving_average_update` would be perfect, if `zero_debias` was a parameter. But it is currently set to `zero_debias = not tf2.enabled()`.

**Comment by Squadrick** [comment]
@robieta Any update on this?

**Comment by robieta** [comment]
I think you'll have to bring it to TF API Owners.

**Pull request closed without merging**
