### PR TITLE
String Tensor fix for s390x arch

### PR DESCRIPTION
**Pull request by rposts**
`String Tensors` defined [here](https://github.com/tensorflow/tensorflow/blob/a17b9ec79c4400e8e4e9b1022da9452beca54d3c/tensorflow/lite/string_util.h#L17) are used by `Tensorflow Lite` extensively. Furthermore, TensorFlow Lite uses `tflite::DynamicBufer` to encode vector of strings. The first integers in the raw buffer is the number of strings.

While this works for natively generated `tflite` models, problem occurs when `tflite` models are moved across endian sensitive architectures. This problem is most evident in `Tensorflow Serving` where few testcases use little-endian generated `tflite` models and serve it on big-endian systems (`s390x` arch in this case).

This PR attempts to do the following:

1. `tensorflow/lite/string_util.cc` code is modified to always store `num_strings` and string `offset` values in litte-endian format and adjust the `GetStringCount` and `StringRef` functions to read the values as little-endian.
2. `parse_example` TF lite kernal is modified to store `num_strings` and string `offset` values in little-endian format.

Corresponding changes are required on the `Tensorflow Serving` code base which will be triggered by a separate PR.

Thanks!

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Please resolve conflicts

**Comment by rposts** [comment]
> Please resolve conflicts

@mihaimaruseac conflicts have been resolved - tx!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by rposts** [comment]
@mihaimaruseac seems like Windows build was failing due to conversion error - have pushed another change to `string_util.cc` - tx!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by rposts** [comment]
@mihaimaruseac - it appears that "Code check" step is failing but I don't have access to internal CIs to address this issue - is this something you can help me with? Thx!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by rposts** [comment]
@mihaimaruseac @gbaned - is there something I can do to assist with moving this forward? Tx.

**Comment by mihaimaruseac** [comment]
Just like the other lite issues, someone from TFLite needs to shepherd this forward.

**Comment by rposts** [comment]
@terryheo is this something you can help with?

**Comment by rposts** [comment]
@gbaned trying to understand if I need to do anything at my end. I presume this PR is in some "queue" waiting to be integrated. Tx.

**Comment by gbaned** [comment]
> @gbaned trying to understand if I need to do anything at my end. I presume this PR is in some "queue" waiting to be integrated. Tx.

Hi @rposts Sorry for the delay, no action pending from your end. This is processing internally. Thank you!

**Comment by rposts** [comment]
There are few regressions spotted on `s390x` due to this commit - I am pulling back PR until a solution is found. Thx.

**Pull request closed without merging**
