### PR TITLE
fix pooling1D dimension bug

### PR DESCRIPTION
**Pull request by stegben**
When `data_format` is `channels_last`, input is `NWC`, so we have to `expand_dim(1)` to make it become `NHWC`. Then we apply pooling on `W` which is the 3rd dimention.

When `data_format` is `channels_first`, input is `NCW`, so we have to `expand_dim(2)` to make it become `NCHW`. Then we apply pooling on `W`, which is the 4th dimention.

RELNOTES: Fixed wrong handling of 1D pooling (pooling was not happening on the correct dimension).

### CODE REVIEW

**Comment by stegben** [comment]
Any comment from the admins?

**Comment by stegben** [comment]
Am I wrong with the implementation detail about 1D pooling?

**Comment by stegben** [comment]
May I ask about the review progress?

**Comment by stegben** [comment]
@martinwicke

**Comment by martinwicke** [comment]
Sorry. Busy times.

This looks fine to me on the face of it, but I'm worried about the fact that there were no tests. Could you add tests that check that the 1D case works as expected?

Thanks!

**Review by martinwicke — CHANGES_REQUESTED** [review]
Please add tests that (and ideally, some of those should have failed before your patch).

**Comment by stegben** [comment]
Thank you for your review, I'll add some test to `python/layers/pooling_test.py`

**Comment by stegben** [comment]
There are 4 test cases in `pooling_test.py` but I believe the cases for `channels_first` are wrong. I fix it in 211e5a4 . 

BTW, how to trigger CI to re-run the test?

**Comment by stegben** [comment]
@martinwicke  There are 4 test cases in `pooling_test.py` but I think the cases for `channels_first` are wrong. I fix it in 211e5a4 . 

BTW, how to trigger CI to re-run the test? I would like to see the test failing status

**Comment by stegben** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
We're killing Jenkins. I've triggered the tests.

**Comment by stegben** [comment]
@martinwicke done, plz trigger CI again

**Comment by rmlarsen** [comment]
@martinwicke could you approve this, please?

**Review by martinwicke — APPROVED** [review]

**Comment by stegben** [comment]
Thanks the review from @martinwicke !

**Pull request merged**
