### PR TITLE
RGB to YUV: Conflicting information between example and description

### PR DESCRIPTION
**Pull request by yil532**
https://www.tensorflow.org/api_docs/python/tf/image/rgb_to_yuv 

Fix the documentation explainations. [0, 1] input range was misleading.

Issue is tracked here https://github.com/tensorflow/tensorflow/issues/41496 and https://github.com/tensorflow/tensorflow/issues/41300

### CODE REVIEW

**Comment by yil532** [comment]
I do have CLA signed. My email is yiwen.li@ibm.com or yil532@ucsd.edu

**Comment by gbaned** [comment]
@yil532 Thank you for your contribution. Can you please sign CLA? Thanks!

**Comment by aigagror** [comment]
I’m sorry but this change doesn’t really do anything. The documentation still says it must be between 0 and 1 and the example defies that.

**Comment by yil532** [comment]
> @yil532 Thank you for your contribution. Can you please sign CLA? Thanks!

I did sign CLA, for example, on this PR, it shows that I have CLA signed https://github.com/tensorflow/tensorflow/pull/41567

**Comment by yil532** [comment]
> I’m sorry but this change doesn’t really do anything. The documentation still says it must be between 0 and 1 and the example defies that.

Yes, the input define range was not wrong, it was just not very clear. Users need to convert from [0, 255] to [0, 1] float range. Should I change the sample input values then?

**Comment by yil532** [comment]
Could someone check my CLA please? This is a previous PR got merged https://github.com/tensorflow/tensorflow/pull/41348
Not sure why it says no CLA here. @gbaned

**Comment by gbaned** [comment]
> Could someone check my CLA please? This is a previous PR got merged #41348
> Not sure why it says no CLA here. @gbaned

@yil532 Can you use please make sure to use same GitHub username and email-id associated with it.

**Comment by yil532** [comment]
Yes, I checked, the username is yil532 and email is yiwen.li@ibm.com Everything seems fine.
@gbaned

**Comment by rthadur** [comment]
@yil532 can you please try to sign the cla with both username and email( yiwen.li@ibm.com) together , we see CLA with only email( yiwen.li@ibm.com)

**Comment by yil532** [comment]
Sure, asking my team about this @rthadur

**Comment by yil532** [comment]
@rthadur Hi, I did sign my CLA with both yil532 and yiwen.li@ibm.com
Should I refresh this PR?

**Comment by rthadur** [comment]
@yil532 for some reason it is not showing the same, can you please try to submit a new PR ?

**Comment by yil532** [comment]
Sure, doing it now @rthadur

**Pull request closed without merging**
