### PR TITLE
Add pre-load CPU feature guard check

### PR DESCRIPTION
**Pull request by hakos**
Follow-up from #48024: building the library and Python code loading it.

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by hakos** [comment]
Thanks for the review. The MacOS failures look unrelated?

**Comment by hakos** [comment]
Any input @penpornk?

**Comment by penpornk** [comment]
@hakos Thank you for checking! Yes, the `MacOS CPU Python` build is unrelated. The PR has already been pulled inside and is just stuck with internal test failures. I'll try to get to it soon.

**Review by duynguyen0209 — APPROVED** [review]

**Comment by hakos** [comment]
@penpornk Thanks, should I try rebasing to see if it can get rid of the `MacOS CPU Python` build failure?

**Comment by penpornk** [comment]
@hakos You don't need to. They are unrelated. :)

**Comment by penpornk** [comment]
@hakos The PR is merged! Thank you very much for your patience! :)
What changed: I ended up moving the `.so` to `//tensorflow/core/platform` to fix the segfaults.

**Comment by hakos** [comment]
Thanks @penpornk!

**Pull request merged**
