### PR TITLE
Boring ssl update.

### PR DESCRIPTION
**Pull request by tjingrant**
As per https://github.com/tensorflow/tensorflow/issues/13587.
Ping @gunan .
Also what's the standard way of getting the checksum? I used sha256sum on the file I downloaded.
The patch to the BUILD file is no longer applicable, I'm not sure if we still need that patch.. Any comments?

### CODE REVIEW

**Comment by caisq** [comment]
@tjingrant please take a look at the sanity build failure:

ERROR: /workspace/tensorflow/tools/pip_package/BUILD:101:1: no such package '@boringssl//': Traceback (most recent call last):
	File "/workspace/tensorflow/workspace.bzl", line 123
		_apply_patch(repo_ctx, repo_ctx.attr.patch_file)
	File "/workspace/tensorflow/workspace.bzl", line 107, in _apply_patch
		repo_ctx.path(patch_file)
path() can only take a string or a label. and referenced by '//tensorflow/tools/pip_package:licenses'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:licenses' failed; build aborted.

https://ci.tensorflow.org/job/tensorflow-pull-requests-sanity/8948/console

**Comment by tjingrant** [comment]
@caisq It seems to be the fault of Github. Github was experiencing issues when I submitted the changes; I did a force-update and things make sense now.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Review by gunan — APPROVED** [review]
sorry for the delay.
The mirror is now available.

**Comment by tjingrant** [comment]
Hi @gunan, here at IBM Research we have to constantly experiment with the master branch and it has been a slight nuisance that we have to debug the master branch every time. Although I do not speak for IBM Research officially, my manager has been telling me that he's interested in taking a more active approach to this issue. For instance, we can commit one of our [minsky](https://www.ibm.com/developerworks/community/blogs/aixpert/entry/OpenPOWER_IBM_S822LC_for_HPC_Minsky_First_Look?lang=en) machine to be a build bot. This can help prevent some mishaps (for us) that can easily be identified and corrected (i.e., https://github.com/tensorflow/tensorflow/commit/fa8c1a1f30eed9ea35e1339eb94515cefc97582f). 

On the other hand, we understand there is no official support for PPC, but some of us are already constantly maintaining the specific build instructions for PPC internally and therefore we can be of some help to address some of the build failures on PPC.

Again, although I do not speak for IBM Research officially, we would like to actively explore all possible options and get the conversation started.

**Comment by gunan** [comment]
@thirupalanisamy @martinwicke FYI.
We used to have an s390x build setup by @nayana-ibm with a setup similar to what you are suggesting. However, that machine seems to be offline at the moment. There are also some upcoming changes in our CI infrastructure, so we may need to come up with a longer term plan for such use cases.

Thiru, can we open a separate communication channel to @tjingrant 's team to discuss how we can make life easier for IBM Research?

**Comment by Nayana-ibm** [comment]
@gunan The vms used for s390x Tensorflow CI are up and running however disconnected by av8ramit. This is probably due to builds are continuously failing for s390x. I could see the two reasons for build failure: first one is it needs Bazel upgrade to 0.6.1 and other one is google/nsync module. 
I have upgraded Bazel to 0.6.1 on these vms. For google/nsync failure I  have raised an issue [here](https://github.com/tensorflow/tensorflow/issues/13777).

**Comment by gunan** [comment]
Looks like only one of the VMs was connected but disabled. I reenabled this
VM. Sorry for missing this earlier.
for VM-0, I see "Ping response time is too long or timed out." So that one
is actually not connected.

We can continue the discussion in the issue you filed, if you like.

**Comment by tjingrant** [comment]
@thirupalanisamy do you have any recommendations regarding how we can move forward with this? We searched around and cannot find any information regarding how to add a new build bot.

**Comment by gunan** [comment]
@thirupalanisamy is right now travelling, but Let us discuss this separately.
Right now, we have a s390x build:
http://ci.tensorflow.org/view/contrib/job/tensorflow-contrib-s390x/

We can setup something similar.
TF team cannot commit to keeping it green, but the failures can be easier to track with a continuous build. Please feel free to reach out to me via email using <my github username>[at]google.com

**Comment by Nayana-ibm** [comment]
Hi Gunan,
Continuing discussion on CI vms on this thread : https://github.com/tensorflow/tensorflow/issues/13914

**Pull request merged**
