### PR TITLE
Make the output for model summary wrap

### PR DESCRIPTION
**Pull request by Llamrei**
This is just a small alteration to the printing logic of the model summary to allow the cells to wrap, this is useful for model with long outputs/inputs (such as BERT, which is what motivated me to do this). Useful for rigorous storage of model summaries.

[x] Read contributing guidelines.
[x] Read Code of Conduct.
[x] Ensure you have signed the Contributor License Agreement (CLA).
[x] Check if my changes are consistent with the guidelines. (I think they are)
[x] Changes are consistent with the Coding Style. (File's pylint score unchanged from 8.56)
[ ] Run Unit Tests.

I am really struggling to be able to run these tests, been trying for a good 4/5 hours, I am on Ubuntu 20.04, I have:
1. Tried running `tensorflow/tools/ci_build/ci_build.sh CPU bazel test //tensorflow/...` from repo root, this consistently errors due to `tensorflow/tools/ci_build/install/install_pip_packages.sh` not seeing the correct python version (which weirdly is trying to use python3.6 even though the git blame for the changes to line 26 suggest the purpose was to migrate to python 3.7)
2. Tried changing the docker file to some other one, I have tried the `tensorflow/tools/ci_build/Dockerfile.pi-python38` (which i now realise is for raspberry pi's - derp!) and `tensorflow/tools/ci_build/Dockerfile.local-toolchain-ubuntu18.04-manylinux2010`. Neither worked.
3. Ultimately, I have pulled `tensorflow/tensorflow   latest-devel   a4c4b6decc02` and exec'd into the container and tried to run `bazel test //tensorflow/python/keras` but that has errored due to:
```
ERROR: /tensorflow_src/tensorflow/core/kernels/BUILD:2736:18: C++ compilation of rule '//tensorflow/core/kernels:resource_variable_ops' failed (Exit 4): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 240 argument(s) skipped)
gcc: internal compiler error: Killed (program cc1plus)
```

I am really keen to try and get these tests running to verify my changes haven't affected anything (although searching the repo for tests using `model.summary()` suggests everything should still pass.

### CODE REVIEW

**Comment by Llamrei** [comment]
would be happy to write tests for this if I could get the tests working on my machine 🙈

**Comment by deeb02** [comment]
@Llamrei Thank you for your contribution. This could be useful but requires some testing. Could you please supply some screenshots that illustrate the old and new behavior and how it's supposed to work?

**Comment by Llamrei** [comment]
Hey sorry for the late reply - please see attached examples of changes proposed. As i said in post above I would be pretty keen to write some tests but I cannot for the life of me get them working locally so it would be pretty darn painful making them without any feedback and just waiting for comments from you guys



Before:
Screenshot from 2021-03-15 11-48-13
After:
Screenshot from 2021-03-15 11-45-43

**Comment by deeb02** [comment]
@Llamrei, thanks for the screenshot and the contribution. I see from your screenshot that the "Connected to" column is affected and has several new lines in the middle and is only continued after the whole wrapped cell is done. Could you please address that?

**Review by deeb02 — COMMENTED** [review]
@Llamrei, thanks for the screenshot and the contribution. I see from your screenshot that the "Connected to" column is affected and has several new lines in the middle and is only continued after the whole wrapped cell is done. Could you please address that?

**Comment by gbaned** [comment]
@Llamrei  Can you please check @deeb02's comments and keep us posted ? Thanks!

**Comment by Llamrei** [comment]
Hadn't checked in on this in a while my bad - I know what's causing this and will push a fix up in the next couple of days

**Comment by Llamrei** [comment]
I have implemented a simple fix for the issue as requested, see the new output attached - I admit this lowers the quality of `connected to` column a little.

However, I think it still adds a benefit as now layers with long names that are connected to are no longer truncated and thus the original purpose of this proposal - to make sure the summary presents all the information it has access to - is fulfilled. 

I could add logic for handling lists/dictionaries whilst being aware of key/entry string lengths for an optimal presentation but I wonder how much value it would add relative to added complexity in the code?

connected_to_not_generating_extra_lines

**Comment by gbaned** [comment]
@deeb02  Can you please assist on above comments from @Llamrei. Thanks!

**Review by deeb02 — APPROVED** [review]
Looks good to me, subject to tests passing.

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by Llamrei** [comment]
Hey so I can see some of the tests are failing - as I said in the original post after like a day of messing around with everything under the sun I couldn't get tests to work locally so i guess this is to be expected. 

Looking at the [output of the failed tests](https://source.cloud.google.com/results/invocations/faa0f8f0-345d-4252-95ae-12cd9e05c2fb/targets/%2F%2Ftensorflow%2Fpython%2Fkeras%2Ftests:model_subclassing_test;shard=3;run=1;attempt=1/tests;group=__main__.ModelSubclassingTest;test=test_summary_v2_eager;row=2) I think it is because I was a little lazy with spacing of the final column. That should be fixed now.

More generally I can envisage a reality where someone could write a test that fails due to the output being broken out over multiple lines but that should not be any of the current test suite and I think writing tooling to introspect the output more carefully (column by column) is overkill pre-emptive action.

**Comment by Llamrei** [comment]
Just realised condition checking in above fix was the wrong way round - silly me. 

Should be all ok now - still not sure what's up with the ROCm build.

**Comment by Llamrei** [comment]
Is there anything else I ought to do? As in both the failed tests it looks like the tool died not the code failing?

**Comment by Llamrei** [comment]
Bump ^^

**Comment by gbaned** [comment]
@deeb02 Can you please assist on above comments from @Llamrei. Thanks!

**Comment by deeb02** [comment]
@Llamrei, we are moving active development of Keras to https://github.com/keras-team/keras and streamlining the process(including testing). Could you please move this PR to that repository?

**Comment by Llamrei** [comment]
Sure thing!

**Comment by gbaned** [comment]
Closing this PR, since it is moved to keras-team/kears repo (https://github.com/keras-team/keras/pull/14865). Thank you.

**Pull request closed without merging**
