### PR TITLE
Refactoring comparisons invoke calls

### PR DESCRIPTION
**Pull request by joyalbin**
Refactoring the duplicated source code comparison Eval functions

### CODE REVIEW

**Review by renjie-liu — COMMENTED** [review]
Hi, I think we're trying to migrate away from using macro as it will generate less friendly compilation error, if possible, can you use template?

**Comment by joyalbin** [comment]
@renjie-liu The changes have modified to remove the macro dependency. Couldnt further refactor because the `comparisonFn` expect the type also when its getting passed. 
Could you please review the PR further.

**Comment by joyalbin** [comment]
@shashishekhar Could you please review and approve this PR?

**Comment by shashishekhar** [comment]
Adding @jianlijianli who will be a better reviewer.

**Comment by gbaned** [comment]
@jianlijianli Could you PTAL and approve.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @renjie-liu, @jianlijianli: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Review by renjie-liu — APPROVED** [review]

**Pull request merged**
