### PR TITLE
tflite/micro/README: fix binary paths

### PR DESCRIPTION
**Pull request by proppy**
/cc @dansitu

### CODE REVIEW

**Comment by gbaned** [comment]
@petewarden Could you PTAL and approve.

**Comment by gbaned** [comment]
@petewarden, @MarkDaoust can you please review this PR ?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @MarkDaoust: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Review by wangtz — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
