### PR TITLE
Fix: Can't set None on TextVectorization layer's split parameter problem

### LINKED ISSUE #36071: Can't set None on TextVectorization layer's split parameter.
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `no`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Ubuntu 18.04`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: `no`
- TensorFlow installed from (source or binary): `no`
- TensorFlow version (use command below): `2.0.0`
- Python version: `3.7.3`
- Bazel version (if compiling from source): `-`
- GCC/Compiler version (if compiling from source): `-`
- CUDA/cuDNN version: `-`
- GPU model and memory: `-`

**Describe the current behavior**
The TextVectorization layer `split` parameter expects `None` as a possible value but can't handle it.

**Describe the expected behavior**
The layer should work properly when `None` is passed as a `split` parameter, or documentation should be updated.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
from pprint import pprint
assert tf.__version__ == '2.1.0-rc1'

dummy_data = ["Foo", "bar", "foo foo", "foo bar", "foobar."]
predict_data = ["foo", "bar", "foobar", "foo foo", "OOV"]
inputs = tf.keras.layers.Input(shape=(1, ), dtype=tf.string, name="text")
vectorize_layer = TextVectorization(output_mode="binary", max_tokens=5, split=None)
vectorize_layer.adapt(np.asarray(dummy_data))
print(f"Vocabulary:\t\t{vectorize_layer.get_vocabulary()}")
outputs = vectorize_layer(inputs)
model = tf.keras.Model(inputs, outputs)
print(f"Prediction data:\t{predict_data}")
predictions = model.predict(predict_data)
print(f"Predictions:")
pprint(predictions)

AttributeError                            Traceback (most recent call last)
<ipython-input-3-f1a03cb1e414> in <module>()
      9 inputs = tf.keras.layers.Input(shape=(1, ), dtype=tf.string, name="text")
     10 vectorize_layer = TextVectorization(output_mode="binary", max_tokens=5, split=None)
---> 11 vectorize_layer.adapt(np.asarray(dummy_data))
     12 print(f"Vocabulary:\t\t{vectorize_layer.get_vocabulary()}")
     13 outputs = vectorize_layer(inputs)

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/layers/preprocessing/text_vectorization.py in _to_numpy(self, preprocessed_data)
    334     if isinstance(preprocessed_data, np.ndarray):
    335       return preprocessed_data
    336     return np.array(preprocessed_data.to_list())
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'to_list'
```

### PR DESCRIPTION
**Pull request by rushabh-v**
resolves: #36071

### CODE REVIEW

**Comment by rushabh-v** [comment]
@googlebot I signed it!

**Comment by rushabh-v** [comment]
@tanzhenyu I have added a test for this. Can you please review the changes?

**Comment by rushabh-v** [comment]
Can someone review this PR, please?

**Review by tanzhenyu — DISMISSED** [review]

**Comment by rushabh-v** [comment]
@tanzhenyu I forgot to put `self` argument in the test. I have pushed one more commit. Can you review it again, please?

**Review by tanzhenyu — DISMISSED** [review]

**Comment by rthadur** [comment]
@rushabh-v can you please fix build failures ?

**Comment by rushabh-v** [comment]
I'm sorry for those silly mistakes. I have fixed it

**Comment by rushabh-v** [comment]
@tanzhenyu sorry that keeps coming. Can you please review it once again. I think it's the last time.

**Comment by rushabh-v** [comment]
Can you review it once again, please? @tanzhenyu

**Review by tanzhenyu — DISMISSED** [review]

**Comment by rthadur** [comment]
@rushabh-v can you please fix build failures ?

**Comment by rushabh-v** [comment]
>@rushabh-v can you please fix build failures ?

Fixed it. used dtype wrongly before.

**Comment by rushabh-v** [comment]
Can you review it, please? @tanzhenyu

**Comment by tanzhenyu** [comment]
> Can you review it, please? @tanzhenyu

Let me know after all runs are passed then I will approve it.

**Comment by rushabh-v** [comment]
I didn't know that I can run the checks before it's reviewed. Can you please tell me how to run the checks. Or you mean I should check locally?

**Review by tanzhenyu — DISMISSED** [review]

**Comment by rushabh-v** [comment]
@rthadur the added test is passing and other tests are also passing. But three CI checks are failing. I looked at the logs but couldn't figure out why they are failing. Can you take a look, please?

**Comment by rthadur** [comment]
@tanzhenyu gentle ping to assist with build failures. Thank you

**Comment by mihaimaruseac** [comment]
```
2. do_pylint: Python 3 pylint
  FAIL
```

Downloading the log and looking at the start gives the pylint issues

```
FAIL: Found 1 non-whitelisted pylint errors:
tensorflow/python/keras/layers/preprocessing/text_vectorization_test.py:1121: [C0326(bad-whitespace), ] No space allowed before bracket
```

**Comment by rushabh-v** [comment]
Okay, I have removed that extra blank space before the bracket, it should be fine now..

**Review by rthadur — APPROVED** [review]

**Review by rthadur — APPROVED** [review]

**Review by tensorflowbutler — DISMISSED** [review]

**Review by mihaimaruseac — DISMISSED** [review]

**Review by rthadur — DISMISSED** [review]

**Comment by rthadur** [comment]
`"google3/runfiles/google3/third_party/tensorflow/python/keras/layers/preprocessing/text_vectorization_test.py", line 1124, in test_split_equals_zero_on_adapt
    predictions = model.predict(predict_data)
  File "/google3/runfiles/google3/third_party/tensorflow/python/keras/engine/training_v1.py", line 969, in predict
    use_multiprocessing=use_multiprocessing)
  File "/google3/runfiles/google3/third_party/tensorflow/python/keras/engine/training_arrays.py", line 707, in predict
    x, check_steps=True, steps_name='steps', steps=steps)
  File "/google3/runfiles/google3/third_party/tensorflow/python/keras/engine/training_v1.py", line 2311, in _standardize_user_data
    batch_size=batch_size)
  File "google3/runfiles/google3/third_party/tensorflow/python/keras/engine/training_v1.py", line 2338, in _standardize_tensors
    exception_prefix='input')
  File "google3/runfiles/google3/third_party/tensorflow/python/keras/engine/training_utils.py", line 527, in standardize_input_data
    standardize_single_array(x, shape) for (x, shape) in zip(data, shapes)
  File "google3/runfiles/google3/third_party/tensorflow/python/keras/engine/training_utils.py", line 527, in <listcomp>
    standardize_single_array(x, shape) for (x, shape) in zip(data, shapes)
  File "google3/runfiles/google3/third_party/tensorflow/python/keras/engine/training_utils.py", line 452, in standardize_single_array
    if (x.shape is not None and len(x.shape) == 1 and
AttributeError: 'str' object has no attribute 'shape'`

@rushabh-v can you please check above error ?

**Comment by gbaned** [comment]
@rushabh-v Can you please check @rthadur comments and resolve conflicts?. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@rushabh-v Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@rushabh-v Any update on this PR? and please resolve conflicts Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by rthadur** [comment]
@rushabh-v can you please check below errors

`File "/testing/parameterized.py", line 284, in bound_param_test
   return test_method(self, *testcase_params)
 File "/tensorflow/python/keras/keras_parameterized.py", line 388, in decorated
   _v1_session_test(f, self, config, *args, **kwargs)
 File "/tensorflow/python/keras/keras_parameterized.py", line 405, in _v1_session_test
   f(test_or_class, *args, **kwargs)
 File "/tensorflow/python/keras/layers/preprocessing/text_vectorization_test.py", line 1214, in test_split_equals_zero_on_adapt
   predictions = model.predict(predict_data)
 File "/tensorflow/python/keras/engine/training_v1.py", line 988, in predict
   use_multiprocessing=use_multiprocessing)
 File "/tensorflow/python/keras/engine/training_arrays.py", line 707, in predict
   x, check_steps=True, steps_name='steps', steps=steps)
 File "/tensorflow/python/keras/engine/training_v1.py", line 2330, in _standardize_user_data
   batch_size=batch_size)
 File "/tensorflow/python/keras/engine/training_v1.py", line 2357, in _standardize_tensors
   exception_prefix='input')
 File "/tensorflow/python/keras/engine/training_utils.py", line 527, in standardize_input_data
   standardize_single_array(x, shape) for (x, shape) in zip(data, shapes)
 File "/tensorflow/python/keras/engine/training_utils.py", line 527, in <listcomp>
   standardize_single_array(x, shape) for (x, shape) in zip(data, shapes)
 File "/tensorflow/python/keras/engine/training_utils.py", line 452, in standardize_single_array
   if (x.shape is not None and len(x.shape) == 1 and
AttributeError: 'str' object has no attribute 'shape'
`

**Comment by rushabh-v** [comment]
hey @rthadur ! 

I apologize to you and @mihaimaruseac  for not replying to your comments. Actually I mistakenly unsubscribed from the notification of this PR. And just saw those comments today.

But I see that the errors are solved with the last commit of @mihaimaruseac

**Comment by rthadur** [comment]
@rushabh-v we still see same error , can you please check again.

**Comment by mihaimaruseac** [comment]
It seems it's an internal error only, so probably will need manual import. Don't know if I can do this this week, but I'll add it on my plate.

**Comment by gbaned** [comment]
@mihaimaruseac  Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by mattdangerw** [comment]
This looks pretty stale--this fix would no longer apply at head. And the underlying issue this fixes looks already closed.

I think we can probably just close this @gbaned

**Comment by gbaned** [comment]
@mattdangerw  Thanks for the confirmation. Closing this PR. Thanks!

**Pull request closed without merging**
