### PR TITLE
Add support for complex SVD.

### PR DESCRIPTION
**Pull request by AidanGG**
In response to my issue https://github.com/tensorflow/tensorflow/issues/3874, I decided to get it working. I might still need to write some tests, but preliminary testing seems good.

### CODE REVIEW

**Comment by rmlarsen** [comment]
Please update the tests in tensorflow/python/kernel_tests/svd_op_test.py accordingly.

**Comment by rmlarsen** [comment]
@AidanGG Please update the tests in tensorflow/python/kernel_tests/svd_op_test.py accordingly.

**Comment by AidanGG** [comment]
I modified the tests and they do pass, but I still have to clean up the file. Are the tolerance values appropriate?

**Comment by rmlarsen** [comment]
@AidanGG Looks good to me! Thanks!

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@AidanGG Could you please sync your repo with the master and resolve the merge conflicts? The second template argument was removed from all the linear algebra ops to avoid duplicating the code. This reduces compile time and binary size.

**Comment by AidanGG** [comment]
I think this is ready now.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by AidanGG** [comment]
I don't know what's going on with the failed check.

**Comment by rmlarsen** [comment]
The test failure is in a flaky test. Unrelated to your PR, which I'm merging now. Thanks for your contribution.

**Comment by caisq** [comment]
Let's give the testing another go. @tensorflow-jenkins test this please.

**Comment by caisq** [comment]
@rmlarsen Tests look good. Ready to merge.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
