### PR TITLE
fixed the equation of the sequence increase

### PR DESCRIPTION
**Pull request by XuesongYang**

### CODE REVIEW

**Review by caisq — APPROVED** [review]

**Comment by caisq** [comment]
@tensorflow-jenkins test this please.

**Comment by caisq** [comment]
@XuesongYang, can you please sign the CLA? Thanks.

**Comment by XuesongYang** [comment]
Hi guys,

I just signed it. Thanks.

Best

Xuesong

**Comment by caisq** [comment]
PR merged. Thank you, @XuesongYang !

**Pull request merged**
