### PR TITLE
[oneDNN] Enable fusion for Add/AddV2 which has BiasAdd semantics

### PR DESCRIPTION
**Pull request by yimeisun123**
If an Add/AddV2 op has one input of Conv2D/DepthwiseConv2D/MatMul in NHWC format,
and the other input is 1-dimension, treat this add node as BiasAdd.

 Co-authored-by: Guangyong Shi <guangyong.shi@intel.com>

### CODE REVIEW

**Comment by yimeisun123** [comment]
@googlebot I fixed it.

**Comment by yimeisun123** [comment]
@googlebot I fixed it.

**Comment by gbaned** [comment]
@yimeisun123 Can you please sign CLA. Thanks!

**Comment by yimeisun123** [comment]
@gbaned - I am working for Intel and should have already signed the CLA, and have submitted PR before. I am not quite sure why I run into this CLA issue.

**Comment by yimeisun123** [comment]
Since this has co-author, it might need some action from @gyshi . I will ping him. Thanks.

**Comment by gyshi** [comment]
@googlebot I fixed it.

**Comment by yimeisun123** [comment]
@googlebot I consent

**Comment by yimeisun123** [comment]
Not sure what else needs to be done to pass the CLA issue. Both contributors to this PR have CLA signed via Intel, and both commented with consent. Any suggestion? Thanks

**Comment by yimeisun123** [comment]
Since this PR keeps failing CLA check, close this one and create a new PR to submit the changes for review.
https://github.com/tensorflow/tensorflow/pull/52358

**Pull request closed without merging**
