### PR TITLE
Update readme of CRF

### PR DESCRIPTION
**Pull request by jinze1994**
PR [12056](https://github.com/tensorflow/tensorflow/pull/12056) implemented CRF decoding in tensor way, but the README hasn't been updated. This PR got this done.

### CODE REVIEW

**Comment by jinze1994** [comment]
I signed it!

**Review by drpngx — APPROVED** [review]
Nice, thanks!

**Comment by drpngx** [comment]
Jenkins, test this please

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Can you pull rebase? That should fix the error. Thanks.

**Comment by drpngx** [comment]
Also, can you check the CLA status? For some reason the googlebot believes it's not clean.

**Pull request merged**
