### PR TITLE
Support for Python 3.8

### PR DESCRIPTION
**Pull request by steffanjensen**

### CODE REVIEW

**Comment by gbaned** [comment]
@reliefs Could you please sign cla ? Thank you.

**Comment by gbaned** [comment]
@reliefs  Gentle ping to sign CLA. Thanks!

**Comment by mihaimaruseac** [comment]
In any case, just adding that line won't bring support for python 3.8. Hence, closing PR.

**Comment by reliefs** [comment]
yes that was a mistake a truely a lack of understanding from my part.. Still using tensorflow i love it.. 

I now just never use it for other people to install :P

**Pull request closed without merging**
