### PR TITLE
Add filesystem ops

### PR DESCRIPTION
**Pull request by vnghia**
@mihaimaruseac 
This PR adds filesystem ops. Regarding the problems with directory, I copy the current approach. But as far as I know, the curent approach can not guarantee the same behavior with `posix filesystem`. I think it maybe the good time to change the `gcs filesystem` design and drop all the `fake directory` support. In particular, CreateDir, DeleteDir, ... will always return ok. What do you think ? I do not have access to the internal code so could you check it for me. Thank you

### CODE REVIEW

**Comment by vnvo2409** [comment]
So I have done some testing. Turn out the current implementation is more complex than I thought and it has the same behavior with local filesystem. But it has one trade-off, it sometimes shows the wrong information compared to the server.

I have an object `'test/foo'` on the server.
`tensorflow 2.2.0` returns true if I call `tf.io.gfile.exists("test")` or `tf.io.gfile.exists("test/")` but `google-cloud-cpp` and `google-cloud-storage` (python) return not found.

I would like to ask if there is any particular reason that we have to keep this behavior ? ( I think the reason is that we want to have the same behavior between filesystems )

**Comment by mihaimaruseac** [comment]
`tf.io.gfile.exists(path)` should return `true` whenever `path` exists.

I think the other 3 only return `true` if the `path` exists and is a file.

Note that the plugin interface checks for a path, not a file https://github.com/tensorflow/tensorflow/blob/e25d3e084b330de37284f54853295ce28ea93d12/tensorflow/c/experimental/filesystem/filesystem_interface.h#L506-L517

**Comment by vnvo2409** [comment]
If we do like this, we will check that if there is a object whose key contains that path ( like object `test/foo` contains `test`). I think it is not so useful in general ?

**Comment by mihaimaruseac** [comment]
Users might ask if a path exists (file/directory) to determine what operations to run in the future. This is much better than the alternative where if they wanted to see if a file exists they can also use `IsDirectory` and look at the return value (the `Status` tells them if the path exists but it is a file).

**Comment by vnvo2409** [comment]
Ok I got it. So first I will copy the current implementation and we could return to this topic after everything is done

**Comment by mihaimaruseac** [comment]
I would still like to split this PR into components:

1. will just create/delete files/directories
1. will just add support for moving/renaming
1. will add support for checking if paths exists, if they are directories, for the stats, etc.
1. will finally allow matching glob patterns and getting all children of a path

**Comment by vnvo2409** [comment]
Close for smaller PRs

**Pull request closed without merging**
