### PR TITLE
Add decode_wav api endpoint

### PR DESCRIPTION
**Pull request by VikramTiwari**
As discussed here: https://groups.google.com/a/tensorflow.org/forum/#!topic/testing/_9AfKgzldf8

### CODE REVIEW

**Comment by martinwicke** [comment]
Regarding your question: there are tests in tensorflow/core/kernels/decode_wav_op_test.cc.

**Review by nfelt — APPROVED** [review]
Looks good to me, assuming it's API-review approved as well @martinwicke?  (Not sure how that works on github.)

**Comment by martinwicke** [comment]
I added the API review label. Let's wait for that to disappear then we're
good.

**Review by alextp — APPROVED** [review]
(For tf-api-owners)

**Pull request merged**
