### PR TITLE
Fix setting out_mtypes in MemoryTypesForNode

### PR DESCRIPTION
**Pull request by lahead**
Clear hostmem_attr vector before populating it with indices from "_output_hostmem" attribute so that it doesn't contain indices from "_input_hostmem" attribute.

### CODE REVIEW

**Comment by lahead** [comment]
@googlebot I signed it!

**Comment by allenlavoie** [comment]
Is the claim that `TryGetNodeAttr` mutates `hostmem_attr` but still returns a bad status?

I don't see why it would do that. Is there a bug this was causing / can we write a unit test for this?

**Comment by lahead** [comment]
The problematic case is when both `_input_hostmem` and `_output_hostmem` attributes are specified. In such case first `TryGetNodeAttr` is called and `hostmem_attr` is populated with host memory input indices, then `TryGetNodeAttr` is called again and host memory output indices are added to the `hostmem_attr` vector, because `TryGetNodeAttr` doesn't clear the vector, but rather simply appends values to it. And so we end up with `out_mtypes` being set based on the indices from both the `_input_hostmem` and `_output_hostmem` attributes.
Sure, I will try to prepare a unit test for this bug.

**Comment by allenlavoie** [comment]
Ah, that makes sense, thanks. Not sure why I was mentally inserting a return.

With a unit test this looks like a good change to me then.

**Comment by gbaned** [comment]
@lahead Can you please check @allenlavoie's comments and keep us posted ? Thanks!

**Comment by lahead** [comment]
I'm working on a unit test, please hold on.

**Comment by lahead** [comment]
Unit test extended to cover this case, please review.

**Review by allenlavoie — APPROVED** [review]
Thank you for fixing this!

**Comment by lahead** [comment]
No problem!
I see some CI build failures, but the failures don't seem to be related to my change. May this be some environment issue?

**Comment by lahead** [comment]
No problem!
I see some CI build failures, but the failures don't seem to be related to my change. May this be some environment issue?

**Comment by lahead** [comment]
No problem!
I see some CI build failures, but the failures don't seem to be related to my change. May this be some environment issue?

**Pull request merged**
