### PR TITLE
Portability improvements for CMake build.

### PR DESCRIPTION
**Pull request by mrry**
- Adds WIN32 overrides for many of the external projects.
- Makes building boringssl optional, to speed up the build.
- Cleans up various comments in the build files.

### CODE REVIEW

**Comment by mrry** [comment]
@gunan @caisq Looks like the CMake presubmit is trying (and failing) to run `bazel`?! Did something change recently to make this the case?

(On the other hand, this builds locally for me without using Docker, so if you want to ignore the check and merge it anyway, that'd be splendid....)

**Comment by caisq** [comment]
@mrry The build has always called bazel, unnecessarily. But it has been working fine until recently, when some environment changes may have made bazel unavailable. I'll look into it soon.

**Comment by caisq** [comment]
This is caused by https://github.com/tensorflow/tensorflow/commit/4316aeb4cb3f7867cf40f74020bd5d12f72d9f0f.

**Comment by caisq** [comment]
See https://github.com/tensorflow/tensorflow/pull/4541, @mrry

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by mrry** [comment]
Rebased to get the CI fix (thanks @caisq!) and fixed an incorrect path. PTAL.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Wait, the tests already pass, I was looking at the wrong thing.

**Comment by mrry** [comment]
Ach if they passed once they'll pass again :).

**Review by gunan — APPROVED** [review]

**Comment by martinwicke** [comment]
Using old passing tests as an excuse to merge.

**Pull request merged**
