### PR TITLE
Go bindings

### PR DESCRIPTION
**Pull request by alonsovidales**

### CODE REVIEW

**Comment by martinwicke** [comment]
I merged this without CLA. We checked with all authors, and all are both ok with merging their commits and have CLAs in place.

**Comment by jmhodges** [comment]
This was merged into the `go` branch. I'm guessing that was intentional. Is there another PR to merge the `go` branch into `master`?

**Comment by alonsovidales** [comment]
Hi @jmhodges , yes, this PR comes from this other one: https://github.com/tensorflow/tensorflow/pull/1771
I think that is because the code still has to be integrated on Jenkins and reviewed a bit more. By the moment, I think that there is no other PR to `master`.

**Comment by martinwicke** [comment]
There is no PR to merge it into master right now. More infrastructure work
has to happen before we can merge it to master (from where it would
automatically be sucked into a lot of systems that are not ready for it).

**Comment by tmc** [comment]
@martinwicke it looks like this got merged with 1429abd -- did that lose commit history? I was looking for how much of this still was made up of my initial contribution but it looks like that history may have been lost.

**Comment by martinwicke** [comment]
Yes. I am sorry, I did squash those commits. I should not have. You can
still look at #2479 for the history.

**Pull request merged**
