### PR TITLE
Update Bazel NDK revision compatibility

### LINKED ISSUE #18000: Android NDK r16 support
While building TensorFlow with Android NDK r16, it failed finding system headers, such as `stdlib.h`

Full error log:

```
                                                             ^
In file included from /wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/cstdlib:72:0,
                 from /wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algo.h:59,
                 from /wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/algorithm:62,
                 from ./google/protobuf/stubs/common.h:38,
                 from ./google/protobuf/stubs/atomicops.h:59,
                 from google/protobuf/stubs/atomicops_internals_x86_msvc.cc:37:
/wd/android-ndk-r16//sources/android/support/include/stdlib.h:32:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
In file included from /wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:44:0,
                 from /wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/bits/postypes.h:40,
                 from /wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/bits/char_traits.h:40,
                 from /wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/string:40,
                 from ./google/protobuf/stubs/bytestream.h:54,
                 from google/protobuf/stubs/bytestream.cc:31:
/wd/android-ndk-r16//sources/android/support/include/wchar.h:32:24: fatal error: wchar.h: No such file or directory
 #include_next <wchar.h>
                        ^
compilation terminated.
In file included from /wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/cstdlib:72:0,
                 from /wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algo.h:59,
                 from /wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/algorithm:62,
                 from ./google/protobuf/stubs/common.h:38,
                 from ./google/protobuf/message_lite.h:43,
                 from google/protobuf/stubs/common.cc:33:
/wd/android-ndk-r16//sources/android/support/include/stdlib.h:32:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:34:0:
/wd/android-ndk-r16//sources/cxx-stl/gnu-libstdc++/4.9/include/cstring:42:20: fatal error: string.h: No such file or directory
 #include <string.h>
                    ^
make[3]: *** [google/protobuf/stubs/common.lo] Error 1
compilation terminated.
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [google/protobuf/stubs/atomicops_internals_x86_gcc.lo] Error 1
make[3]: *** [google/protobuf/stubs/atomicops_internals_x86_msvc.lo] Error 1
make[3]: *** [google/protobuf/stubs/bytestream.lo] Error 1
make[3]: Leaving directory `/wd/tensorflow_0314/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/wd/tensorflow_0314/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/wd/tensorflow_0314/tensorflow/tensorflow/contrib/makefile/downloads/protobuf'
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by seanpmorgan**
Updated Bazel compatible Android NDK version. I also tried to re-word the docs to require less revision in the future. 
Demo app on Bazel 0.16.1 + NDK16 compiled without issue as a sanity check. 

This should close https://github.com/tensorflow/tensorflow/issues/18000
Announcement of Bazel NDK16 compatibility: https://github.com/bazelbuild/bazel/issues/4068#issuecomment-370068345

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by seanpmorgan** [comment]
@zh794390558 Sorry, I do not. My suggestion would be to start with NDK 16 or 17 and work your way down in empirical tests.

**Comment by zh794390558** [comment]
@seanpmorgan Thanks for your opinion.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by seanpmorgan** [comment]
This PR is stale (for example configure.py supports NDK up to 18, though the READMEs are still behind. Closing PR

**Pull request closed without merging**
