### PR TITLE
Replace all COMPILER_MSVC to _MSC_VER and _WIN32 accordingly

### PR DESCRIPTION
**Pull request by rongjiecomputer**
`-D` compile flag should be avoided as much as possible. Many Google projects like Chromium follow  (which uses CMake or GN) only define macro in header file like below and always include the header file to get the macro (IWYU).

```cpp
#ifdef _MSC_VER
#define COMPILER_MSVC
#endif
```

However, such rule is not easy to implement for Tensorflow as Bazel require strict header dependency. It is easier to just use `_MSC_VER` and `_WIN32` directly.

Other stuff:

- Remove `ARRAYSIZE` macro in `tensorflow/stream_executor/platform/port.h` (only used in `tensorflow/stream_executor/cuda/cuda_driver.cc`, which is now replaced with `TF_ARRAYSIZE` from `tensorflow/stream_executor/platform/macros.h`).

### CODE REVIEW

**Review by mrry — APPROVED** [review]

**Comment by rongjiecomputer** [comment]
@mrry I fixed one more ARRAYSIZE -> TF_ARRAYSIZE. PTAL and re-trigger CI test.

**Comment by meteorcloudy** [comment]
@tensorflow-jenkins test this please

**Comment by rongjiecomputer** [comment]
@meteorcloudy For some reason, I got the email notification that you pinged @tensorflow-jenkins for CI test, but your comment is missing in Github web and the CI test is not triggered.

**Comment by meteorcloudy** [comment]
That's right.. I deleted the comment because I just realized TF is not using Jenkins to do presubmit anymore, I don't know how to trigger a retest. @mrry Can you do that?

**Review by meteorcloudy — APPROVED** [review]

**Comment by mrry** [comment]
@meteorcloudy Sure: for future reference, you now have to apply the "kokoro:force-run" label to the PR to kick off the tests.

**Comment by meteorcloudy** [comment]
@mrry Got it, thanks!

**Comment by rongjiecomputer** [comment]
Last commit fixes the remaining failing CI tests ("GPU CC", "GPU Python3" and "XLA"), caused by including non-existing header file. Sorry for the spam.

**Pull request merged**
