### PR TITLE
Half pixel centers

### PR DESCRIPTION
**Pull request by lisphacker**
This PR adds half-pixel-center support for nearest neighbour and bilinear interpolation for XLA backends. This would enable the use of tf.keras.layers.UpSampling2D() over an XLA backend.

### CODE REVIEW

**Review by fsx950223 — APPROVED** [review]

**Comment by gbaned** [comment]
@smit-hinsu  Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@lisphacker  Can you please resolve conflicts? Thanks!

**Comment by lisphacker** [comment]
@gbaned Sorry for delay, I've rebased the diff.

**Comment by lisphacker** [comment]
Hmm, just noticed the number of files showing as changed? Maybe I need to rebase this again?

**Comment by gbaned** [comment]
@mikedelorimier  Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@mikedelorimier Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@mikedelorimier Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@lisphacker Can you please resolve conflicts? Thanks!

**Comment by lisphacker** [comment]
Hello, can this PR be re-opened?

**Pull request closed without merging**
