### PR TITLE
Update convolutional.py

### PR DESCRIPTION
**Pull request by gautam1858**
Adding tf_export decorators/calls to TensorFlow functions and constants.

### CODE REVIEW

**Comment by carlthome** [comment]
What is this used for?

**Comment by martinwicke** [comment]
Is it useful to publish this as a hidden class?

**Comment by gautam1858** [comment]
yup

**Comment by martinwicke** [comment]
I'm not sure we would want to allow this. We make the API specifically to call out what you can rely on and what is stable. Anything that it hidden is by definition not part of the API. You can of course always access it directly, but I don't think it's a good idea to expose it into the TensorFlow module.

**Comment by gautam1858** [comment]
Hmm but it was not hidden right and why do you think it shouldn't be exposed to API ?

**Comment by martinwicke** [comment]
It is a private class, if you use it you should be very aware that you are relying on an internal implementation detail. 

You can always use this (this is Python, after all), you just have to explicitly import it from the file it's defined in.

**Comment by gautam1858** [comment]
hmmm ok

**Pull request closed without merging**
