### PR TITLE
Set grpc_state timeout when options is nullptr

### PR DESCRIPTION
**Pull request by lzr-official**
Set default timeout for grpc_state when options is nullptr.

Currently, the timeout would be 0 when `call_opts` is nullptr. `operation_timeout_in_ms` in `ConfigProto` would not work in some cases: For example in [grpc_remote_worker.cc](https://github.com/tensorflow/tensorflow/blob/c528f878ca31bcb970cb67688938f9e2f3daedf4/tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.cc) many invocations of `IssueRequest` has `call_opts = nullptr` as default argument.

This change allows setting a default timeout for all operations via environment variable `RPC_STATE_DEFAULT_OPERATION_TIMEOUT_IN_MS`.

### CODE REVIEW

**Comment by haoyuz** [comment]
Hmm IMO operation timeout and RPC timeout are different concepts, and I'm not convinced that we should have a global default timeout for all RPCs. Could you elaborate your use case? If you just want a specific RPC to have a timeout, you can change its `CallOptions`?

**Comment by lzr-official** [comment]
There are many methods defined in [grpc_remote_worker.cc](https://github.com/tensorflow/tensorflow/blob/c528f878ca31bcb970cb67688938f9e2f3daedf4/tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.cc) that doesn't have a `CallOptions` in the function call context.

For example in this call to `IssueRequest`,
https://github.com/tensorflow/tensorflow/blob/c528f878ca31bcb970cb67688938f9e2f3daedf4/tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.cc#L104 The caller `DeregisterGraphAsync` doesn't have `CallOptions` in its parameters or in the request message.

In these cases, timeout will be 0 by default. We need a way to configure the default value in that case.

**Comment by haoyuz** [comment]
> The caller `DeregisterGraphAsync` doesn't have `CallOptions` in its parameters or in the request message.

Yes, but how could a deregister graph RPC fail with timeout? There is no blocking logic in handling `DeregisterGraph` RPCs, so I guess it's timing out because the remote worker is down? Should it set `GRPC_FAIL_FAST` in that case?

**Comment by lzr-official** [comment]
It's not only the `DeregisterGraph`, there are also other methods without `CallOptions`.

`GRPC_FAIL_FAST` has also been tried, but it doesn't always work for unknown reason.

**Comment by gbaned** [comment]
@haoyuz Can you please assist on above comments from @lzr-official. Thank you!

**Comment by gbaned** [comment]
Hi @lzr-official Can you please resolve the conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @lzr-official Can you please resolve the conflicts? Thank you!

**Pull request closed without merging**
