### PR TITLE
tf.Dimension raises TypeError for tf.DType

### LINKED ISSUE #17079: tf.zeros should raise an error when passed a DType as shape
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NA
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab, colab.research.google.com
- **TensorFlow installed from (source or binary)**:  unsure
- **TensorFlow version (use command below)**: 1.6.0-rc1
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**:
```python
import tensorflow as tf
tf.InteractiveSession()
tf.zeros(tf.string).eval()
```

### Describe the problem

This returns a NumPy array with seven elements?!?
```python
array([0., 0., 0., 0., 0., 0., 0.], dtype=float32)
```

Of course, I mixed up the shape and dtype arguments to tf.zeros, The proper usage is `tf.zeros((), tf.string))`. So this should really raise TypeError (or maybe ValueError).

### PR DESCRIPTION
**Pull request by facaiy**
fix #17079.

### CODE REVIEW

**Review by skye — APPROVED** [review]
Thanks for fixing this!

**Comment by skye** [comment]
jenkins test this please

**Comment by facaiy** [comment]
I have resolved the conflict, and could anyone help restart all tests?

**Comment by facaiy** [comment]
@skye @drpngx Excuse me, could you help restart all tests? Thanks.

**Comment by drpngx** [comment]
Thanks for pinging, sorry I missed the first email.

**Comment by facaiy** [comment]
@drpngx All tests pass. Thanks for your consistent help :)

**Comment by drpngx** [comment]
Woohoo!

**Pull request merged**
