### PR TITLE
Update version number in pip package setup.py

### PR DESCRIPTION
**Pull request by Robin-des-Bois**
Updated version number. 
Minor change. But I was confused for a short time about the old version number in the newly generated .whl file...

### CODE REVIEW

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by vrv** [comment]
this is incomplete -- there are a bunch of other places to make this change.

@martinwicke @caisq should we merge the version change from the r0.9 back into master?  Should this have been done first before branching?

**Comment by martinwicke** [comment]
In the past we have merged back after the actual release. There's no reason
not to merge back more often. I'd like the actual version number change to
be a commit on the release branch but that's really only an aesthetic
preference.

**Comment by martinwicke** [comment]
We'll revert this, it breaks a bunch of stuff.

**Comment by Robin-des-Bois** [comment]
I did not realize that the version number should also get updated in all these other places. I should have checked that. I was also not sure about where to base the pull request. 

I am sorry for your inconvenience.

**Comment by martinwicke** [comment]
Don't worry. We shouldn't have merged it.

**Pull request merged**
