### PR TITLE
Add zero point check for kTfLiteInt16 and scale check for multiple operators

### PR DESCRIPTION
**Pull request by smpurkis**
Hello, have added zero point checks and scale checks to the following operators

arg_min_max.cc
gather.cc
gather_nd.cc
mul.cc
pack.cc
pad.cc
pooling.cc
resize_bilinear.cc
resize_nearest_neighbor.cc
select.cc
slice.cc
transpose.cc
unpack.cc

### CODE REVIEW

**Comment by abattery** [comment]
@smpurkis could you share the motivation of this change? Why are these runtime check necessary?

**Comment by smpurkis** [comment]
Of course, there are two checks that have been added, a zero point check, such as in
`tensorflow/lite/kernels/mul.cc`
```
  if (output->type == kTfLiteInt16) {
    TF_LITE_ENSURE_EQ(context, input1->params.zero_point, 0);
    TF_LITE_ENSURE_EQ(context, input2->params.zero_point, 0);
    TF_LITE_ENSURE_EQ(context, output->params.zero_point, 0);
  }
```
this ensures that for `int16` the constraint that the zero point is 0 is met.

The second check (less commonly added) is a scale check that is applied to `uint8`, `int8`, `int16`, such as in 
`tensorflow/lite/kernels/resize_bilinear.cc`
```
  if (input->type == kTfLiteUInt8 || input->type == kTfLiteInt8 ||
      input->type == kTfLiteInt16) {
    TF_LITE_ENSURE_EQ(context, input->params.scale, output->params.scale);
```
this ensures that the scaling between input and output is the same.

These checks already exist in the majority of operators. The ones I've added, seem to be missing from the operators I've added them to.
For example, `tensorflow/lite/kernels/add.cc` has the zero point check [here](https://github.com/tensorflow/tensorflow/blob/5bde0752f9a4f7fd1991463aa15dd388cc3c4644/tensorflow/lite/kernels/add.cc#L139). While `tensorflow/lite/kernels/mul.cc` doesn't.

Furthermore, I found that a couple of the pooling tests, that test `int16` had the zero point being non-zero. Thus failing once I had added the zero point checks to `tensorflow/lite/kernels/pooling.cc`.

**Comment by gbaned** [comment]
@abattery  Can you please assist on above comments from @smpurkis. Thank you!

**Comment by gbaned** [comment]
Hi @abattery Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @abattery Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @smpurkis Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @smpurkis Can you please resolve conflicts? Thank you!

**Pull request closed without merging**
