### PR TITLE
Branch 180304271

### PR DESCRIPTION
**Pull request by drpngx**

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Windows CMake seems stuck... Trying again.

Jenkins, test this please.

**Comment by drpngx** [comment]
Still stuck.

Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Yep, @yifeif @gunan it looks like all jenkins builds are frozen for some reason.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
There was a problem with ssl certificates. it should be working now.

**Comment by drpngx** [comment]
Thanks!

**Comment by drpngx** [comment]
Woohoo!

**Pull request merged**
