### PR TITLE
[ROCm] rocBLAS BLAS algorithms integration logic in ROCm StreamExecutor

### PR DESCRIPTION
**Pull request by whchung**
Please focus on the content in commit https://github.com/tensorflow/tensorflow/pull/20715/commits/c12b7df5a9321582e785d13edf81c32fc9df379b

The pull request contains rocBLAS integration logic for ROCm platform.

There are additional changes included in this pull request which are covered
in other pull requests for ROCm. In order to ensure each pull request is
self-contained and builds / runs on both CUDA & ROCm platform they are still
included here.

- #20277 : bazel changes and continuous integration logic
- #20675 : StreamExecutor interface change
- #20709 : barebone ROCm StreamExecutor implementation

Authors:

- Jack Chung: jack.chung@amd.com
- Deven Desai: deven.desai@amd.com
- Johannes M Dieterich: Johannes.Dieterich@amd.com

### CODE REVIEW

**Comment by whchung** [comment]
@jlebar This is the subsequent PR after #20709 to cover integration logic for rocBLAS BLAS algorithms on ROCm StreamExecutor implementation

**Comment by jlebar** [comment]
cc @chsigg

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jlebar, @chsigg: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by whchung** [comment]
@qlzh727 all of my PRs are still alive. it's just literally they all hinge on #20277 where I have to fix issues met on Mac / Windows and certain Ubuntu build targets. I'll rebase and revise the PR once #20277 lands

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
