### PR TITLE
Replace all gate_gradients=1 with gate_gradients=GATE_OP in documenta…

### PR DESCRIPTION
**Pull request by slacy**
Replace all "gate_gradients=1" in documentation with "gate_gradients=GATE_OP" to make 
it very clear that GATE_OP is the default value. This matches what exists in the source code as well.

### CODE REVIEW

**Comment by slacy** [comment]
I signed it!

**Comment by slacy** [comment]
Is there something that I need to do to run the required checks above, or will they eventually run automatically?

**Review by rmlarsen — APPROVED** [review]

**Review by rmlarsen — CHANGES_REQUESTED** [review]
The .md files are auto-generated from the docstring in the Python code, so this change would be quickly overwritten.

**Comment by rmlarsen** [comment]
@slacy I'm not sure there is a way to preserve "GATE_OP" when auto-generating the docs. Assigning @xmbrst for advice.

**Comment by vrv** [comment]
All the docs changed in the 1.0 release -- going to close this -- it's possible this got fixed with the new doc generators.  In any case, editing the .md files wouldn't be the right thing to do anyway :(

**Pull request closed without merging**
