### PR TITLE
TFLite: add cmake support

### PR DESCRIPTION
**Pull request by jsee23**
Motivation:
Raspberry Pi4 is gaining OpenGL ES3.1 support with Mesa 19.3. Additionally, many SoC's in the embedded space also supporting 3.1 or OpenCL 2.0. Also, there are desktop GPUs which support OpenCL 2.0. Make it possible to compile the GL & CL delegates easily and separatly (e.g. if just OpenGL ES3.1 is available).

This PR adds support for compiling TF Lite with CMake. CMake was choosen, because it's a settled build system, used very often in embedded area and also support by abseil & flatbuffers (which are requirements for GL & CL delegates). It mainly adds a lot of #ifdefs to the code... The PR isn't complete yet, but I quickly want to discuss, if CMake support is desired and if yes, we should deprecate Makefile support.

To use it:
1. run download_dependencies.sh in tools/make
2. run build.sh in tools/cmake (this will run cmake twice, first compiling flatc for the host, then TFLite for the target; additional parameters of build.sh are passed to the "target"-cmake run)

Missing stuff: documentation/README.md, don't compile flatc when no delegate is built, etc.

### CODE REVIEW

**Comment by jsee23** [comment]
@googlebot I signed it!

**Comment by rthadur** [comment]
@jsee23 can you please resolve conflicts ?

**Comment by jsee23** [comment]
@rthadur done

**Review by impjdi — COMMENTED** [review]
I'm generally in favor of "add cmake support".  But the amount of #ifdefs inserted in this PR makes the code really hard to read and thus I'm against the change.

Do you need TFLITE_CONFIG_GPU_CL & TFLITE_CONFIG_GPU_GL?  if you remove that, it might be much cleaner?

**Comment by srjoglekar246** [comment]
Looks like want wouldn't to add CMake-specific code to our codebase. Our (limited) Makefile support is already a bit tricky to maintain, so I would unfortunately say no to "adding CMake support".

**Comment by jsee23** [comment]
Sorry, this ended up like no PR should look like: I mixed different things in one PR.
1) adding CMake support: IMO, cmake is a better fit than Makefiles, as it's also cleanly supported on Windows hosts. We could deprecate the Makefiles and offer CMake support instead. @srjoglekar246  would you prefer this? Next steps could be e.g. support for a TFLite conan package (would simplify the start with TF Lite for some users...). IMO, we need a good 2nd build system in addition to bazel, as bazel perfectly fit for building Tensorflow, but it isn't widely adopted and people aren't used to it...
2) de-couple the OpenCL & OpenGLES backends with #ifdefs: I saw a lot of embedded SoC's that either just support OpenCL 2.x **OR** OpenGL ES 3.1. With the #ifdef-ing, one could just compile in the GLES shaders (e.g. on a RPi4 with the latest mesa), just the OpenCL shaders (e.g. on a desktop system) or both.

If there is a common understanding for point 1, I will create a new PR and separate point 1 & 2. Please also comment if it make sense to follow up point 2.

**Comment by jdduke** [comment]
@impjdi to comment on selective building of GL/CL. Something like this makes sense to me, and I'm generally supportive, however, I think we might want to take a step back and see if we can restructure the code to more seamlessly allow this, without needing to sprinkle in #ifdefs in many different places.

As for CMake support, I'm sympathetic, but I think we'd need a proper engineering discussion before we move ahead with something like that. The only reason we have the Makefiles, currently, is that cross-compilation w/ Bazel can be difficult for certain systems. Ideally, we'd remove the parallel Makefile build system entirely, and rely on Bazel. Is there a reason Bazel doesn't work for your needs?

**Comment by jdduke** [comment]
Friendly ping on why bazel is insufficient for your needs. Maintaining two separate build systems is often a losing battle, and the TFLite Makefile exists only for legacy reasons.

**Comment by jsee23** [comment]
@jdduke Sorry, this took way too long :) Build systems are a very emotional thing for many people, I will try to stay on a technical path ;)
I see two major requirements that people are trying out/integrate TFLite: (1) easy (cross) compilation for a embedded target & (2) integration with a package manager.
1) IMO, documentation for cross-compilation in Bazel is limited or the whole process is too complicated? Didn't found any documentation/tutorial e.g. for cross-compilation for RPI. This is easier with just specifying CC, CXX and some flags with make, cmake, etc. Maybe it makes sense to take here the tool which is used the most? (don't have any numbers for CMake...)
2) people start to use package managers even with C/C++ :) I think bazel isn't yet natively supported by Conan, vckpg, etc.
Maybe you can cross-check with your colleagues from Abseil about their experiences? (see https://abseil.io/blog/20190402-cmake-support)

**Comment by jdduke** [comment]
OK, so leaving the CMake discussion aside, did you want to proceed with the ability to selectively build GL vs CL in the GPU delegate?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@jsee23 Can you please check jdduke's comments and resolve conflicts?. Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Comment by BenjaminWegener** [comment]
got a tflite runtime with gpu to work in python under debian
https://github.com/BenjaminWegener/tensorflow_lite_gpu_python/commit/b1fcd1b51c039fca0408eccf49cea77d3bbee2c5
https://github.com/BenjaminWegener/tensorflow_lite_gpu_python/commit/9721986c8289c3fce9642526ef7bb799ade5466e

**Pull request closed without merging**
