### PR TITLE
Allow providing custom hash to snapshot

### LINKED ISSUE #47994: tf.data.experimental.snapshot should allow providing custom hash
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): Ues

**Describe the feature and the current behavior/state.**
Users may want to specify a custom hash_code to control the behavior of when snapshot enters read vs. write mode.
As an example: If snapshot is generated outside of training, and the dataset call-chain/graph is guaranteed to be unchanged,
then a simple hash function can checksum all the input files and generate a hash_code.

As long as the input dataset remains the same during training, the hash function can generate the same hash_code, and the
generated snapshots would be read. If the input dataset is different, the hash function would generate a new hash_code,
and therefore the SnapshotDataset op would generate new snapshots.
**Will this change the current api? How?**
It will expose a new optional parameter `hash_code` in the current `tf.data.experimental.snapshot` api.
**Who will benefit with this feature?**
All users of `tf.data.experimental.snapshot` who
**Any Other info.**
This extends the capability exposed in the C++ API: https://github.com/tensorflow/tensorflow/commit/cbc7f31b7d6aac81158be084201d3b3e8e346907

### PR DESCRIPTION
**Pull request by ashahab**
This exposes a new parameter `hash_code` to `tf.data.experimental.snapshot`.

Users may want to specify this parameter to control the behavior of when snapshot enters read vs. write mode.
As an example: If snapshot is generated outside of training, and the dataset call-chain/graph is guaranteed to be unchanged,
then a simple hash function can checksum all the input files and generate a hash_code.

As long as the input dataset remains the same during training, the hash function can generate the same hash_code, and the
generated snapshots would be read. If the input dataset is different, the hash function would generate a new hash_code,
and therefore the SnapshotDataset op would generate new snapshots.

This fixes #47994

This extends the custom hash param exposed in the C++ API: https://github.com/tensorflow/tensorflow/commit/cbc7f31b7d6aac81158be084201d3b3e8e346907

### CODE REVIEW

**Comment by jsimsa** [comment]
Being able to override the hashing function does not seem like a good idea. The intended use for `snapshot` is not to be able to read "snapshot" generated by different input pipeline graphs and relying on users to correctly determine whether their input pipeline graph have changed and it is therefore safe to read the snapshot is prone to error.

To decouple the graph used for reading and writing the materialized data, users should use [save](https://www.tensorflow.org/api_docs/python/tf/data/experimental/save?version=nightly) and [load](https://www.tensorflow.org/api_docs/python/tf/data/experimental/load?version=nightly) instead.

**Comment by ashahab** [comment]
Hi @jsimsa, Thank you for your comment. The capability for adding a custom hash was added by this PR: https://github.com/tensorflow/tensorflow/commit/cbc7f31b7d6aac81158be084201d3b3e8e346907#diff-ddd28df5aaf5fafc521b4012e0fca1801ec50c56dc41a3e2196c98223404b3b4R81

Our use-case is this: Our Deep-learning jobs always have an infra-portion of the dataset graph, and a user-customizable part of the dataset graph. We would like to always pre-generate snapshots for the infra portion so that all users can benefit from different pre-generated snapshots. However, this strategy does not work well with Estimators as the Estimator expects an entire input_fn. 
It is easier for us if we can pre-generate the snapshots, and then use the same hash for all training jobs that use the same data, regardless of the model training framework(keras vs estimator).

Would it be ok to add additional warnings for users to only use this when they are certain that the dataset chain and input set have not changed?

The issue with using save and load is that the sharding and reading is not as well implemented as `snapshot`, and also checkpoint versioning complicates saving and loading.

**Comment by jsimsa** [comment]
> Hi @jsimsa, Thank you for your comment. The capability for adding a custom hash was added by this PR: [cbc7f31#diff-ddd28df5aaf5fafc521b4012e0fca1801ec50c56dc41a3e2196c98223404b3b4R81](https://github.com/tensorflow/tensorflow/commit/cbc7f31b7d6aac81158be084201d3b3e8e346907#diff-ddd28df5aaf5fafc521b4012e0fca1801ec50c56dc41a3e2196c98223404b3b4R81)
This change introduced the hash as an attribute of the op to avoid the need to recompute the hash repeatedly for efficiency sake. The intended use is not for the hash to be exposed in the user-facing API for the reasons I mentioned in my previous response.

> Our use-case is this: Our Deep-learning jobs always have an infra-portion of the dataset graph, and a user-customizable part of the dataset graph. We would like to always pre-generate snapshots for the infra portion so that all users can benefit from different pre-generated snapshots. However, this strategy does not work well with Estimators as the Estimator expects an entire input_fn.
> It is easier for us if we can pre-generate the snapshots, and then use the same hash for all training jobs that use the same data, regardless of the model training framework(keras vs estimator).
>
> Would it be ok to add additional warnings for users to only use this when they are certain that the dataset chain and input set have not changed?
> 
> The issue with using save and load is that the sharding and reading is not as well implemented as `snapshot`, and also checkpoint versioning complicates saving and loading.

The arguments of `save` and `load` mirror the read and write path of `snapshot` and are implemented using the same building blocks as snapshot, so it is not clear what part of `save` and `load` is not as well implemented. For your use case, you could use `save` to pre-generate "snapshots" and your user input pipelines would use `load` to read from one of the pre-generated snapshots.

**Comment by ashahab** [comment]
@jsimsa thank you for your clear explanation. Are you referring to this save and load implementation: https://github.com/tensorflow/tensorflow/blob/827d029baabdcedac973f47076dd2ec9932d6938/tensorflow/core/kernels/data/experimental/io_ops.cc#L190

The inconvenience with the load api is that it requires an output tensor shape, whereas the snapshot API does not.

**Comment by jsimsa** [comment]
I am referring to the Python [API](https://www.tensorflow.org/api_docs/python/tf/data/experimental/load?version=nightly) that I also linked in my earlier [response](https://github.com/tensorflow/tensorflow/pull/47995#issuecomment-804527253). The need for providing `element_spec` has been removed recently. TF nightly does not need it and neither will TF 2.5.

**Comment by ashahab** [comment]
@jsimsa  Thank you for being so responsive! We are on TF 2.4.0. Is this the only backport we need to use the load api without tensor_spec: https://github.com/tensorflow/tensorflow/commit/9132f00c2071753b3da43b81913b7c35d402c610

**Comment by jsimsa** [comment]
yes, it should be

**Comment by gbaned** [comment]
@ashahab Any update on this PR? Please. Thanks!

**Comment by ashahab** [comment]
@gbaned I'm working on testing save and load as a viable alternative this. I can get back to this in 1-2 weeks.

**Comment by ashahab** [comment]
@gbaned @jsimsa  We were able to test `tf.data.experimental.save` and `tf.data.experimental.load` as alternatives to `tf.data.experimental.snapshot`. The issue is that unlike `tf.data.experimental.snapshot`, `tf.data.experimental.save` is not a dataset operation. Therefore, we can't iterate through it to incrementally save the dataset. Our datasets are large and can easily take upwards of 2-4 hours to save. When we were using `tf.data.experimental.snapshot`, we were able to expose the progress of snapshot writes to tensorboard. With `tf.data.experimental.save` there's no such opportunity, unless there's a hook to publish something from the iteration: https://github.com/tensorflow/tensorflow/blob/d96b20aa303b9a90d407cd80b94288626bd8e22e/tensorflow/core/kernels/data/experimental/io_ops.cc#L104

How can we solve this issue? If we cannot, we have to revert to using snapshot (with the custom hash id).

**Comment by jsimsa** [comment]
When you talk about incrementally saving a dataset are you referring to checkpointing progress in the presence of pre-emptions?

How did monitor progress of `snapshot` through TensorBoard?

I would rather improve implementation of `save` and `load`, instead of exposing implementation details of `snapshot` that should not be exposed.

**Comment by ashahab** [comment]
Hi @jsimsa What I mean is the tf.data.experimental.snapshot's Writer is a DatasetIterator, which saves the dataset element when GetNextInternal is called. 
We exposed it to tensorboard by emitting a counter to after each call to next(dataset).

It is different when tf.data.experimental.save is called, it will iterate through the entire dataset, and therefore we cannot do the same.

**Comment by jsimsa** [comment]
> It is different when tf.data.experimental.save is called, it will iterate through the entire dataset, and therefore we cannot do the same.

You can do the following:

```
import tensorflow as tf

writer = tf.summary.create_file_writer("/tmp/example")
counter = tf.Variable(0, dtype=tf.int64)

def log_progress(x):  
  counter.assign_add(1)
  with writer.as_default():
    tf.summary.scalar("elements_saved", counter, counter)  
  return x

ds = ... # your dataset
ds = ds.map(log_progress)
tf.data.experimental.save(ds)
```

**Comment by ashahab** [comment]
Thank you @jsimsa . However, what is the reason for not implementing `tf.data.experimental.save` as a DatasetBase operation? Is there a plan to convert it to DatasetBase later?

**Comment by jsimsa** [comment]
What would be the use case for `save` behaving as [tee](https://linuxize.com/post/linux-tee-command/)? There are no plans for this at the moment.

**Comment by ashahab** [comment]
@jsimsa Thank you for your response.
The use-case for save behaving like a dataset operation would allow users to iterate through it while saving, and inject stateful functions. Your above example only works for stateless functions, whereas we want to keep state such as "time when the first operation was done, and time when the current operation is being done".
The other reason is that it would make `tf.data.experimental.save` similar to `tf.data.experimental.load` which does require dataset iteration.

**Comment by jsimsa** [comment]
Why does my example only work for stateless functions? 

The asymmetry between `save` and `load` is intentional and commonplace. Calling `save` on an object saves the contents of an object instance . Calling `load` on an object, creates a new instance of the object by loading its contents.

**Comment by ashahab** [comment]
@jsimsa 
This is our code that calculates write throughput. I am not sure how we keep track of last_record_time and last_batch_count in your example:
```python
last_record_time = time.time()
last_batch_count = 0
batch_count = 0
for _ in dataset:
    batch_count += 1
    if batch_count % SNAPSHOT_THROUGHPUT_MEASUREMENT_GRANULARITY == 0:
        current_example_count=batch_count * batch_size,
        last_example_count=last_batch_count * batch_size
        throughput = (current_example_count - last_example_count) / (time.time() - last_record_time)
        with snapshot_summary_writer.as_default():
            tf.summary.scalar(name=SNAPSHOT_THROUGHPUT_SUMMARY_NAME, data=throughput,
                              step=current_example_count, description=SNAPSHOT_THROUGHPUT_SUMMARY_DESCRIPTION)
        last_batch_count = batch_count
        last_record_time = time.time()
```

**Comment by jsimsa** [comment]
Executing the following program:

```
import time

import numpy as np
import tensorflow as tf

LOG_EVERY_N_BATCHES=2
BATCH_SIZE=10

last_record_time = time.time()
last_batch_count = 0.0

batch_count = tf.Variable(0)

dataset = tf.data.Dataset.range(200)
dataset = dataset.batch(BATCH_SIZE)

def helper(batch_count):
  global last_record_time
  global last_batch_count
  current_example_count=np.float32(batch_count * BATCH_SIZE)
  last_example_count=np.float32(last_batch_count * BATCH_SIZE)
  throughput = (current_example_count - last_example_count) / (time.time() - last_record_time)
  last_batch_count = batch_count
  last_record_time = time.time()
  print(throughput, current_example_count)  # debug print statement
  return throughput, current_example_count

def track_progress(x):
  batch_count.assign_add(1)
  if batch_count % LOG_EVERY_N_BATCHES == 0:
    throughput, current_example_count = tf.py_function(func=helper, inp=[batch_count], Tout=(tf.float32, tf.float32))
    # ... your summary writer logic here    
  return x

dataset = dataset.map(track_progress)

for _ in dataset:
  pass
```

produces the following example output:

```
181.52955917136075 20.0
22863.47233578632 40.0
20580.490677134447 60.0
27539.750492449115 80.0
36519.84327383544 100.0
32909.40761082777 120.0
32400.957898802626 140.0
31242.487895716946 160.0
36615.48668703623 180.0
19481.207617278218 200.0
```

**Comment by ashahab** [comment]
Thank you @jsimsa , this is helpful.
If we wanted to modify the batch size, do we reset BATCH_SIZE to something else before calling dataset = dataset.map, or is there a cleaner and more tensorflow-friendly way?
i.e:
```python
BATCH_SIZE=10
...
def track_progress(x):
...
BATCH_SIZE=64
dataset = dataset.map(track_progress)
```

**Comment by ashahab** [comment]
@jsimsa  we have discovered a bug with snapshots: https://github.com/tensorflow/tensorflow/issues/48903

**Comment by gbaned** [comment]
@jsimsa Can you please assist on above comments from @ashahab. Thanks!

**Comment by gbaned** [comment]
@jsimsa Any update on this PR? Please. Thanks!

**Comment by jsimsa** [comment]
As per my earlier [comment](https://github.com/tensorflow/tensorflow/pull/47995#issuecomment-804527253), I do not think this PR makes sense.

**Comment by ashahab** [comment]
Sorry I was out this morning. Yes it is fine to close this one. I have a
patch pending in 2.5 though for save and load, would like to see that
reviewed.

**Pull request closed without merging**
