### PR TITLE
[ROCm] Fix unit test for ROCm.

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
/cc @cheshire

### CODE REVIEW

**Review by cheshire — COMMENTED** [review]
Would that pass on NVIDIA ? Wouldn't you need to use variable names?

**Comment by rsanthanam-amd** [comment]
> Would that pass on NVIDIA ? Wouldn't you need to use variable names?

An is_built_with_rocm_ predicate is used and the change in this PR affects only the ROCm part of that.

**Comment by rsanthanam-amd** [comment]
This has always passed on Nvidia.  The enablement of this test on ROCm was done several weeks ago but needed the modification in this PR because of some other change.  The same modification was done for Nvidia recently and that change needs to be replicated for CUDA.

**Comment by rsanthanam-amd** [comment]
@cheshire gentle ping

**Review by cheshire — APPROVED** [review]

**Pull request merged**
