### PR TITLE
Added iOS example

### PR DESCRIPTION
**Pull request by petewarden**
This change adds in an example of using the static library generated by the makefile in an iOS app, and allows optimization flags to be passed to the makefile on the command line.

### CODE REVIEW

**Comment by mtngld** [comment]
Good to see tensorflow finally supported on iOS (#16), I wonder what does this PR mean for #1631?

**Comment by fpolacov** [comment]
I'm receiving this error running tensorflow/contrib/makefile/compile_ios_tensorflow.sh.

~/Developer/libs/tensorflow/tensorflow/contrib/makefile/gen/lib/libtensorflow-core-armv7.a -arch armv7 -miphoneos-version-min=9.2 -Xlinker -S -Xlinker -x -Xlinker -dead_strip -all_load -L~/Developer/libs/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib -lz -lstdc++ -lprotobuf -lm
ld: internal error: atom not found in symbolIndex(__ZN10tensorflow10RunOptions15set_trace_levelENS_21RunOptions_TraceLevelE) for architecture armv7

Any idea of what's wrong?

**Comment by petewarden** [comment]
What version of Xcode are you running? I've seen that with versions before 7.3.

**Comment by fpolacov** [comment]
XCode Version 7.2 (7C68). I'll try updating. Thanks!

**Pull request merged**
