### PR TITLE
[XLA] utility functions and more/better logging

### PR DESCRIPTION
**Pull request by nouiz**
Add a few utility functions and some update to the logging system.
This will be needed for the following PR.

@sanjoy @thomasjoerg

### CODE REVIEW

**Review by sanjoy — APPROVED** [review]
lgtm, although I'd have preferred putting `FillWithZY` in the PR that used it.

**Comment by nouiz** [comment]
Ok. But what difference you see between the 2 utilities functions here that make you have different preference between them?

**Comment by sanjoy** [comment]
> Ok. But what difference you see between the 2 utilities functions here that make you have different preference between them?

One of them is exercised (albeit only via a unit test) while the other one isn't.

In this specific case this isn't a big deal at all, the added methods are very simple.  But for more complicated helpers it is nice to introduce both the helpers and some code using the helpers so that if the helper is buggy then the CL won't pass unit tests.

**Comment by nouiz** [comment]
ok. thanks.

**Pull request merged**
