### PR TITLE
[INTEL MKL] Fused quantized Ops for Intel CPU [PR for comment only].

### PR DESCRIPTION
**Pull request by mdfaijul**
This PR is intended for comments on eight bit precision inference on Intel CPU. Please do not merge this PR. Here is summary:

1. Introduce quantized Conv2D and its fused operators. (i) Conv2D (ii) Conv2D + BiasAdd (iii) Conv2D + BiasAdd + ReLU (iv) Conv2D + Relu.
2. Adds algorithms for graph quantization [tensorflow/tools/quantization/quantize_graph.py]. The resulting graph is partially quantized, more quantized operators will be added as more implementations are done. We set round_mode to "HALF_TO_EVEN" in QuantizeOp since Intel CPU supports only that rounding mode. Future PR will include an implementation of MklQuantizeOp.
3. QuantizedConv2D and its fusion works with unsigned input and signed filter on Intel CPU.

**Example of fp32 graph:**
fp_graph

**Example of partially quantized graph:** 
quant_graph

### CODE REVIEW

**Comment by tatianashp** [comment]
@raghuraman-k , @suharshs, @rmlarsen, @andydavis1   - Do you have any thoughts on this PR?

**Comment by mdfaijul** [comment]
@tatianashp @agramesh1 @raghuraman-k @suharshs @rmlarsen @andydavis1 
Any update on this PR?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request closed without merging**
