### PR TITLE
Branch 155393864

### PR DESCRIPTION
**Pull request by andrewharp**
Pushing internal commits

### CODE REVIEW

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this, please.

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this, please.

**Comment by andrewharp** [comment]
@tfboyd @gunan Any idea why user "unknown" keeps aborting the tests?

```
Build was aborted
Aborted by unknown
[Set GitHub commit status (universal)] PENDING on repos [] (sha:8a095d9) with context:tensorflow-pull-requests-cpu-python3
Unable to get pull request builder trigger!!
Setting status of b0f739da665b0491920667a7d1e2bcc2fd721f0d to FAILURE with url https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/4716/ and message: 'FAILURE
 '
Using context: Linux CPU Tests (Python 3)
Finished: ABORTED
```

And from the ci.tensorflow.org test:
```
First time build. Skipping changelog.
    >> Job status: [tensorflow-pull-requests-sanity] the 'build only if scm changes' feature is disabled.
```

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this, please.

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this, please.

**Comment by andrewharp** [comment]
@gunan Ok to ignore the //tensorflow/python/kernel_tests:stage_op_test  timeout?

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this, please.

**Comment by gunan** [comment]
Yes, I will take care of that timeout separately.

**Review by gunan — APPROVED** [review]

**Pull request merged**
