### PR TITLE
Update Dockerfile to be based on 9.2-base-ubuntu18.04

### PR DESCRIPTION
**Pull request by cancan101**

### CODE REVIEW

**Comment by gunan** [comment]
While this has a great potential to work, we are not continuously testing TF on cuda 9.2
I would like to see what @zheng-xq and @tfboyd think about this change before I merge it.

**Comment by cancan101** [comment]
referencing this ticket: https://github.com/tensorflow/tensorflow/issues/18906

**Comment by cancan101** [comment]
@tfboyd ?

**Comment by tfboyd** [comment]
I feel the device driver is too new for most people as it is not easy to get via the official debian repository or even the ubuntu repoistory (I just checked again) which is updated faster.  NVIDIA does not support officially support the driver on their DGX-1.  It is not hard to install but I find it odd how any people cannot install these tools.  I posted some basic [performance numbers ](https://github.com/tensorflow/tensorflow/issues/18906) and you get most of the CUDA 9.2 gains with CUDA 9.0/cuDNN 7.1.4.  I would like us to support two versions of CUDA like the other ML tools but that is not something the infrastructure is supporting right now.  That will have to change with the CUDA 10 launch.  There is some mid and long-term hope.  NVIDIA has suggested they will make CUDA 10 through 10.x backwards compatible with the initial device driver, and as soon as CUDA is early access I want to publish builds.    

Per the issue below, I am open to suggestions and other ways to look at it.  One perspective is people that cannot update their device driver should get an older version of TensorFlow.  I kind of dig that idea, but I wonder how painful that is for people to then find out they need a much newer device driver.  On the plus side NVIDIA is publishing better CUDA install packages.

https://github.com/tensorflow/tensorflow/issues/18906

Let me know what you think and if you have time what you are using that is specifically in CUDA 9.2/7.1.4 that is not in CUDA 9.0/7.1.4.  I am curious and that might help tip the scales in the short-term.

**Comment by cancan101** [comment]
I believe that in order to use Ubuntu 18.04 you need to be using CUDA 9.2 (see https://github.com/NVIDIA/nvidia-docker/issues/666#issuecomment-389118126). I would like to upgrade to 18.04 for a number of reasons, the primary being native support for Python 3.6.

**Comment by tfboyd** [comment]
@cancan101  Ahh so CUDA 9.2 is not the goal the goal is Ubuntu 18.04.  CUDA 9.2 is a means to an end.  I did not consider that.

**Comment by tfboyd** [comment]
18.04 seems fresh and as an indication are not offering an upgrade from 16.04 LTS until maybe later July.  I do not know how popular the Docker is but moving it to Python 3.6 as the default seems like a big deal if people were expecting it to be 2.x.  NVIDIA dropped 14.04 and we should move to 18.04 I do not think it should happen right now, that is an even bigger move in my opinion than CUDA 9.2.  

Thank you for the info.  I really had not considered the Ubuntu angle.

**If we moved to building tensorflow with CUDA 9.2 would that reduce your pain.**  You could have a custom docker file with a pip install tf-nightly or whatever and get Ubuntu 18.04.  Just asking.

**Comment by cancan101** [comment]
no no no. I am not suggesting moving from python 2 to python 3.6. There is already a python 3 image which I am suggesting moving to python 3.6 (from 3.6).

**Comment by cancan101** [comment]
see: https://github.com/tensorflow/tensorflow/blob/444d3a7b382cd2a0f3759eb9f7791054f6319843/tensorflow/tools/docker/parameterized_docker_build.sh#L282-L316

**Comment by tfboyd** [comment]
Let me try and get some base truth (to keep it straight for me, I can be slow and I do not know if what I was reading is correct.)

- Ubuntu 18.04 is default Python 3.6, meaning if we move to that as the base we would need to switch the default as part of the DockerFile to Python 2.x for the python 2.x build
- Ubuntu 18.04 needs CUDA 9.2
- CUDA 9.2 needs device driver 396.26

My current concerns (and I want to upgrade):

1. Device driver is really new.
2. Ubuntu 18.04 was just released.

If I made up a random rule or idea.  I would jump to Ubuntu 18.04 with CUDA 10.  That way people just have to upgrade once and off we go.  I still would like to have a second CUDA build but that is not up to me.

**Comment by cancan101** [comment]
>Ubuntu 18.04 is default Python 3.6, meaning if we move to that as the base we would need to switch the default as part of the DockerFile to Python 2.x for the python 2.x build

What I should have said above is that the default python3 version in 18.04 went from 3.5 to 3.6.

**Comment by tfboyd** [comment]
I think what you are suggesting is the following, just to get the ask 100% correct.

- Upgrade both Python 2 and 3 Dockers to Ubuntu 18.04 (which then means CUDA 9.2)
- For the Python 2.x Docker we would include command to swap in Python 2.x as the default.

I know this does not help you now, but I am inclined to push for 18.04 for the CUDA 10 release.  Thoughts? dirty looks?

**Comment by cancan101** [comment]
Yes that sounds about right. 

What is the timeline for Cuda 10 + support in tf + docker images for Cuda 10? If it's soon, than might be no problem. If could be a while, I'd love to get onto 18.04 without having to wait for that.

**Comment by tfboyd** [comment]
My guess is CUDA 10 will be later Q3 or early Q4.  I can see moving to CUDA 9.2 near the end of the cycle in early Q3.  That makes the move to Ubuntu 18.04 not really relevant, and I still think it may be a good time to move to 18.04 as that keeps us in the middle of the cycles  16.04 end of life's April 2021.  

How many systems to you manage and are you upgrading them all to Ubuntu 18.04?  That seems aggressive for a production system.  I am going to mark this closed as we will not be accepting the change in the near-term.

**Comment by cancan101** [comment]
We use Docker so upgrading the "system" involves bumping the base Docker image. All we need to do is update the Nvidia driver version on the host. That involves pre-baking an AMI.

**Comment by cancan101** [comment]
Last question, if I install tf from pypi, should it work with Cuda 9.2?

**Comment by gunan** [comment]
No, the pypi versions are  built against CUDA 9.0.

**Comment by mirekphd** [comment]
> No, the pypi versions are built against CUDA 9.0.

A few versions later and it is no longer true. TF 1.13.1 uses CUDA 10.0. What if our servers don't have NVIDIA drivers new enough for CUDA 10? What is the newest TF wheel I can still use under CUDA 9.0? 

(And a suggestion: why not include CUDA / cuDNN versions in wheel names?)

**Comment by tfboyd** [comment]
https://www.tensorflow.org/install/source#linux   

tensorflow_gpu-1.12.0

You have no idea how long it took me to find this closed issue and add that link .

I try to keep us on the same CUDA until a major release happens do to driver issues.  NVIDIA keeps getting closer to backward compatibility but it is not there just yet.  Really close and likely kind of working, but I also like to keep it simple even when I get flamed by a minority of people or maybe majority secretly I have no idea.  :-)

**Comment by tfboyd** [comment]
@mirekphd 
https://www.tensorflow.org/install/source#linux
1.12 was the last on CUDA 9.0

I try to keep us on the same CUDA until a major release comes out.  This results in me getting a decent amount of flames from the interwebs.  NVIDIA is close and kind of has some backwards compatibility working and keepings making it better every quarter.  I have hopes the situation gets better.

I cannot believe I am commenting on an issue closed almost 1 year ago. It took me 30 minutes just to find this issue after seeing it on my phone and then finding the link to the versions on the website.  Time to go home.

**Comment by mirekphd** [comment]
@tfboyd : thank you, much appreciated. I ended up installing [1.12.2 from PyPi](https://pypi.org/project/tensorflow-gpu/1.12.2/) and it works in the GPU under CUDA 9.0 (9.0.176.3-1). 

Well, Google is the best search engine for closed Github issues, as the closed issues tend to contain more solutions than the open ones, so the closed ones should rank higher:)

**Comment by tfboyd** [comment]
I need to get some internet points for commenting on old issues.  I really
am glad you found what you needed.  I read more closed bugs when looking
for answers as well.

*From: *mirekphd <notifications@github.com>
*Date: *Tue, May 14, 2019, 4:42 AM
*To: *tensorflow/tensorflow
*Cc: *Toby Boyd, Mention

@tfboyd <https://github.com/tfboyd> : thank you, much appreciated. I ended

**Pull request closed without merging**
