### PR TITLE
[ROCm] Adding/Removing no_rocm tag to/from tests

### PR DESCRIPTION
**Pull request by deven-amd**
Adding/Removing no_rocm tag to/from tests/subtests that are currently
failing/passing on the ROCm platform

Separating this commit out as a separate PR from PR #35764

/cc @cheshire @whchung

### CODE REVIEW

**Review by cheshire — DISMISSED** [review]

**Comment by gbaned** [comment]
@deven-amd Can you please check failed build errors? Thanks!

**Comment by deven-amd** [comment]
@gbaned,    pushed out a commit to fix the buildier errors. 

please re-approve and re-run the CI tests. thanks

**Review by cheshire — APPROVED** [review]

**Review by cheshire — DISMISSED** [review]

**Comment by gbaned** [comment]
@deven-amd Can you please resolve conflicts? Thanks!

**Comment by deven-amd** [comment]
@gbaned I have rebased the PR to resolve the merge-conflcts

**Comment by gbaned** [comment]
> @gbaned I have rebased the PR to resolve the merge-conflcts

@deven-amd  Still, conflicts appearing. Could you please resolve those? Thanks!

**Comment by deven-amd** [comment]
@gbaned , rebased PR again to resolve the new merge conflicts

**Review by cheshire — DISMISSED** [review]

**Comment by deven-amd** [comment]
@gbaned, rebased yet again to resolve another merge conflict that showed up today

**Review by cheshire — APPROVED** [review]

**Pull request merged**
