### PR TITLE
Reintegrate tensorflow/toolchains

### PR DESCRIPTION
**Pull request by angerson**
Removing the tensorflow/toolchains repository has these benefits:

- Speed up toolchain and RBE changes: with the repo, every toolchains adjustment requires a PR, a Release, a mirror upload, and another PR = ~hours of busywork. Without the repo, it's one PR. We wouldn't have to automate anything.
- Reduce confusion about toolchains: the toolchains repository, except for the toolchains subdirectory which has been migrated here, is mostly unused junk that attempts to replicate TensorFlow's WORKSPACE setup to make the toolchains functional without TF. That isn't true; tensorflow/toolchains does not actually work if you try to bazel build anything because the WORKSPACE is broken.
- Remove the maintenance burden of the toolchains repo: one less repository for us to worry about.
- Remove coupling: tensorflow/toolchains and tensorflow/tensorflow are heavily coupled, i.e. they depend on each other.

And these downsides:

- Obligation to notify / fix downstream users: I haven't found any direct users for @tf_toolchains, but a few projects do use our toolchains. They usually use a WORKSPACE that pulls the entirety of TensorFlow. It's our responsibility to notify anyone who indirectly uses our toolchains to tell them that they may need to adjust their workflows.
- Loss of toolchain history: we can't retain history across repositories, so all previous changes to the directory would be lost. I don't think we have a choice, and this isn't enough of a reason to keep it as a separate repo.
- Loss of any benefits of the separate repository: the original goal of a _separate repository_ to "enable reuse of all of [TF's toolchains] across TFRT, custom ops, and main TensorFlow." Considering that TFRT does not use these toolchains and that the custom op repository is unsupported, this goal has failed and there is no loss in re-integrating.

This PR is a demonstration of what little work is required to re-integrate the tensorflow/toolchains repository back under TensorFlow. The only changes I've made have been:

- Move tensorflow/toolchains://toolchains back into //tensorflow/tools/toolchains
- Update `@tf_toolchains` paths to match new locations
- Remove the external WORKSPACE dependency and other unused files 

I was able to build TensorFlow successfully this way. Have I missed anything?

@mihaimaruseac @learning-to-play

### CODE REVIEW

**Comment by angerson** [comment]
Trying to clean up those extra commits...

**Comment by angerson** [comment]
Ubuntu Sanity has correctly noticed some formatting / broken-BUILD problems that I'll get around to fixing after discussing this more.

**Comment by chsigg** [comment]
Maybe add an item under 'downsides' that explains the motivation for splitting out the toolchains into a separate repository? Unfortunately, I don't remember what we tried to achieve. Maybe we wanted tensorflow/runtime to depend on it as well?

**Review by mihaimaruseac — APPROVED** [review]

**Review by perfinion — APPROVED** [review]
This change looks good to me. The only minor change i'd want is regarding this one:

"Loss of toolchain history: we can't retain history across repositories, so all previous changes to the directory would be lost. I don't think we have a choice, and this isn't enough of a reason to keep it as a separate repo."

Include the exact commit hash from the tf_toolchains repo that you took the files from into the commit message of the first commit in this stack (in the message itself so that git log/blame will have it).

The tf_toolchain repo is not going anywhere (at most we'd mark it read-only on github) so that is all the information anyone would need to be able to trace history themselves albeit a little manually.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
