### PR TITLE
Cherry Pick: Automatically build SWIG from source

### PR DESCRIPTION
**Pull request by jart**
Reviewer: @gunan 

This PR cherry-picks 1dba78b997dc49df9df663a838e0bacd6602f5b8 and cl/137268906 onto r0.11.

### CODE REVIEW

**Comment by gunan** [comment]
@yifeif looks like we have a few more fixes. This one is needed to fix docker build at head.
The tests look bad. Could you look into what is wrong with them?

**Comment by jart** [comment]
Yeah whatever those errors are, they look pretty bad.

**Comment by caisq** [comment]
If we cherry-pick this, please cherry-pick the upgrade CL/137268906 as well.

**Comment by gunan** [comment]
The latest builds on this branch have been healthy, so the test failures are either infra issues or caused by this PR.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Comment by jart** [comment]
Done. Please don't squash when merging.

**Comment by yifeif** [comment]
All three builds failed with '/tensorflow/python/BUILD:1749:1: C++ compilation of rule '//tensorflow/python:_pywrap_tensorflow.so' failed'

**Comment by yifeif** [comment]
Is there anything else that's needed from master to go with this PR?

**Comment by jart** [comment]
I don't even know where to begin with that error. I can't reproduce it locally.

**Comment by gunan** [comment]
We cannot merge the PR with the test failures.
To unblock the release, can we add the swig dependency to the master Dockerfile to unblock the release, and with 0.12, we can remove that dependency?

**Comment by gunan** [comment]
Just to make sure, Jenkins, test this please.

**Comment by gunan** [comment]
These do not look like flakes. I am closing this PR, let's fix the issue in master by adding the deb package back.

**Pull request closed without merging**
