### PR TITLE
[INTEL MKL] Enable reorder cache in MklTranspose.

### PR DESCRIPTION
**Pull request by pandaoxin**
Enable reorder primitive reuse in MklTranspose, please review.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zhangyaobit: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by pandaoxin** [comment]
@zhangyaobit Any updates?

**Review by zhangyaobit — DISMISSED** [review]

**Comment by zhangyaobit** [comment]
@caisq looks like I don't have write access any more. Could you add another reviewer? Thanks.

**Comment by pandaoxin** [comment]
@caisq @zhangyaobit Any updates?

**Comment by pandaoxin** [comment]
@caisq @zhangyaobit Any updates?

**Comment by pandaoxin** [comment]
@caisq @zhangyaobit Any updates?

**Comment by pandaoxin** [comment]
@caisq @zhangyaobit Any updates?

**Comment by caisq** [comment]
@pandaoxin Starting the pulling process now. Sorry for the delay.

**Comment by caisq** [comment]
@pandaoxin the pulling process is affected by the recent (ongoing?) GitHub outage. Still trying. Thank you for your patience.

**Comment by caisq** [comment]
@pandaoxin Can you take a look at the clang-format error at https://source.cloud.google.com/results/invocations/46bdfb6c-809a-4948-a6eb-6c9953449e68/targets/%2F%2Ftensorflow%2Ftools%2Fci_build:gen_ci_clang_format_out/log?

**Comment by pandaoxin** [comment]
@caisq Have fixed. Thanks!

**Pull request merged**
