### PR TITLE
[XLA] Fix OS/X compile error with std::transform and  std::addressof

### PR DESCRIPTION
**Pull request by DavidNorman**
I don't know if this has been flagged up elsewhere...

on my platform (OS/X, XLA), I receive the following error when trying to compile tensorflow/compiler/xla/service/llvm_ir/kernel_support_library.cc:

```
tensorflow/compiler/xla/service/llvm_ir/kernel_support_library.cc:101:5: error: no matching function for call to 'transform'
    std::transform(function->arg_begin(), function->arg_end(),
    ^~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:1922:1: note: candidate template ignored: couldn't infer template argument '_UnaryOperation'
transform(_InputIterator __first, _InputIterator __last, _OutputIterator __result, _UnaryOperation __op)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:1932:1: note: candidate function template not viable: requires 5 arguments, but 4 were provided
transform(_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2,
^
```

It is possible that std::addressof cannot be matched with the unary function template.

This code change replaces addressof with an function, which does match std::function<> ok.

### CODE REVIEW

**Comment by yifeif** [comment]
Thanks @DavidNorman. Do you mind resolving the conflicts?

**Comment by DavidNorman** [comment]
no problem.

**Comment by DavidNorman** [comment]
done

**Comment by sanjoy** [comment]
I thought this was already resolved by #15229?  I'm not familiar with github's workflow so I may be missing something.

**Comment by DavidNorman** [comment]
It's probable, I have not pulled the master for a week due to vacation.....

**Comment by DavidNorman** [comment]
yes - it has been fixed.  although I prefer my anonymous inline function to the multi-line expansion :)

**Pull request closed without merging**
