### PR TITLE
Fix segfault when recording raw allocation returns nullptr

### PR DESCRIPTION
**Pull request by byronyi**
See [here](https://github.com/tensorflow/tensorflow/commit/ec1403e7dc2b919531e527d36d28659f60621c9e#commitcomment-23432313) for discussion.

### CODE REVIEW

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by byronyi** [comment]
@michaelisard @reedwm Could you take a look here? Thanks!

**Comment by rmlarsen** [comment]
Thank you for the fix!

**Comment by byronyi** [comment]
I am sorry, but could you revert this? Seems this is only a partial fix that does for allocation but not de-allocation. I will try to address it in 9bb2c8eda.

**Pull request merged**
