### PR TITLE
 [CMake] Extract more file lists

### PR DESCRIPTION
**Pull request by Androbin**
like #14877
@mrry /cc

### CODE REVIEW

**Comment by mrry** [comment]
Can you explain the benefit of this change? As far as I can tell, all it does is add an indirection, and the file lists aren't shared with other parts of the build. (This is unlike the list of Python modules, which is useful to extract so that it can be used in a consistency-checking test.)

**Comment by Androbin** [comment]
I will submit consistency-checks as a follow-up as soon as #15166 is done.
Also, it keeps things clean and prevents merge conflicts due to indentation and the like.

**Comment by Androbin** [comment]
@mrry I [discussed this](https://github.com/tensorflow/tensorflow/issues/10296#issuecomment-353749235) with @gunan
Both `tf_python.cmake` and `tf_tests.cmake` will benefit, other won't.
I reverted all non-beneficial changes.
Tests on this will follow.

**Comment by drpngx** [comment]
Feel free to bounce.

**Comment by Androbin** [comment]
I have the corresponding tests ready. Waiting for #15670 to get merged.

**Comment by Androbin** [comment]
Added tests (like #15670)

**Comment by Androbin** [comment]
@martinwicke Any objections?

**Comment by gunan** [comment]
My comments on the issue were just comparative values for extracting lists from the cmakefiles. Not a comment on the absolute value of extracting the file lists. So, as @mrry asked, if we can explain the added value we get from extracting the lists to txt files, we can review this. Otherwise, I usually like erring on the side of lesser code complexity.

**Comment by martinwicke** [comment]
I guess what @gunan is rightfully asking: what does this buy us? Does it lead to
- less/easier modification of CMAKE files in cases of changes to the code
- better tests/errors in case of changes that would break the CMAKE build
or some other advantage?

**Comment by Androbin** [comment]
* separates concerns of declaration and use (less need to care about the other)
* changes don't affect each other (data format (`"${tensorflow_source_dir}/`), line indentation)
* provides clean access to other code (e.g. sharing with other build scripts)
* enables testing (in this case, helps cleaning up outdated references)

**Comment by Androbin** [comment]
Well, maybe points 1 and 3 don't quite hold for the `exclude` lists.

**Comment by Androbin** [comment]
The point is, as @gunan stated, issues with Python files go unnoticed.
For example, [this line](https://github.com/tensorflow/tensorflow/pull/15590/files#diff-154d7a6e7930f8e143fbd4b8329c67d0L247) should ideally have broken the build.
And as the last commit on this PR shows, there were invalid entries in 3 of 4 file lists.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rmlarsen** [comment]
@gunan are you convinced by the arguments & changes that we should proceed with this?

**Comment by Androbin** [comment]
Spotted two more invalid exclude paths:
tensorflow/contrib/tfprof/python/tools/tfprof/pprof_profiler_test.py
tensorflow/contrib/data/python/kernel_tests/iterator_ops_test.py
(unnoticed since removal last week)

**Comment by gunan** [comment]
After @mrry and @martinwicke's comments, I think it may be better to drop this PR. These lists do not need to be shared across different things, so removing them from the cmake files are just added complexity.

**Pull request closed without merging**
