### PR TITLE
Fixes to `Wrapper.get_config` and `Wrapper.from_config`.

### PR DESCRIPTION
**Pull request by pandrey-fr**
This PR aims at solving two light issues I identified with the `tf.keras.layers.Wrapper` class.

This has been tested on both TensorFlow 2.1.0 and 2.2.0-rc0 for Python 3.6.9, both installed using `pip` on a Linux 64-bits system.

#### 1. Serialization through `get_config`.

**Issue**: The dict output by `Wrapper.get_config()` is designed to contain the config of the wrapped layer, in a format similar to that output by keras serialization utilities. However, the identifier of that layer (its `class_name`) is currently manually gathered within the `get_config`, which results in bugs such as  custom layers set for registration (using `tf.keras.utils.register_keras_serializable`) not being given their proper identifier.

**Fix**: I propose to replace the manual creation of the `layer` entry within the returned configuration by a direct call to `serialize_keras_object`.

**Minimal example**:
```python
import tensorflow as tf

@tf.keras.utils.register_keras_serializable(package='test')
class CustomLayer(tf.keras.layers.Layer):
    def call(self, inputs):
        return inputs

wrapper = tf.keras.layers.Wrapper(CustomLayer())
config = wrapper.get_config()
tf.keras.layers.Wrapper.from_config(config)
```
When run before the fix, this fails on the last line, raising `ValueError: Unknown layer: CustomLayer`.
When run after the fix, this runs successfully.

#### 2. Instantiation through `from_config`.

**Issue**: Contrary to what the source code suggests, `Wrapper.from_config` has side effects on the provided config dictionary; in short, it pops out its `layer` sub-dict.

**Fix**: Instead of calling `config.copy()`, I suggest using `copy.deepcopy(config)` before popping out the `layer` sub-dict of the (deep copy of the) input config dictionary.

**Minimal example**:
```python
import tensorflow as tf

dense = tf.keras.layers.Dense(32)
wrapper = tf.keras.layers.Wrapper(dense)
config = wrapper.get_config()
assert 'layer' in config, 'before wrapper instantiation'
tf.keras.layers.Wrapper.from_config(config)
assert 'layer' in config, 'after wrapper instantiation'
```
When run before the fix, the second assertion fails due to the side effect.
When run after the fix, this runs successfully.

### CODE REVIEW

**Review by qlzh727 — DISMISSED** [review]
Thanks for the change, and sorry for the late review.

**Comment by qlzh727** [comment]
It seems that the test is failing wrt deepcopy:

https://source.cloud.google.com/results/invocations/2e5f1424-87f0-4826-93b2-d3936a6caa51/targets/%2F%2Ftensorflow%2Fpython%2Fkeras%2Flayers:wrappers_test/tests

**Comment by pandrey-fr** [comment]
@qlzh727 Thank you for the review.

I see what went wrong; in the `Bidirectional` wrapper, the (optional) `backward_layer` is being de-serialized within the overridden part of `from_config`, thus the `config` passed to the super method contains an instantiated layer, which `deepcopy` does not know how to handle.

I see two ways to handle this:

0. Replace the `super().from_config` call in `Bidirectional.from_config` with direct re-instantiation of the forward layer and constructor call. This way there is no secondary deepcopy call and the bug does not arise - but not calling the super method and duplicating some of its lines of code may feel improper.

1. Add a `parse_config` method to `Wrapper` that takes care of everything save for the deepcopy, and have `from_config` run the latter before delegating to the former. But this feels like a painful hack to avoid one bug...

I will push a commit implementing solution zero, but let me know if you would rather adopt another way of handling this.

**Comment by pandrey-fr** [comment]
I tested locally that all tests from `wrapper_test.py` pass with the last commit.

On the side, I realized custom layers used as backward layer were not properly serialized either; I thus also made a minor modification to `Bidirectional.get_config`.

**Review by qlzh727 — APPROVED** [review]

**Pull request merged**
