### PR TITLE
Add batch_size and ValidationMonitor

### PR DESCRIPTION
**Pull request by GuohongLi**
Add batch_size and ValidationMonitor

### CODE REVIEW

**Comment by GuohongLi** [comment]
I signed it!

**Comment by rmlarsen** [comment]
@ispirmustafa Can you review this or delegate?

**Comment by GuohongLi** [comment]
@rmlarsen Can anybody review this? I had successfully run it myself, and some questions on stackoverflow  are about this example. it will be helpful.

**Review by ispirmustafa — CHANGES_REQUESTED** [review]
Hi Guohong,
Thank you for your contributions.
Adding batch_size make sense. could you please take a look to 'tf.estimator.pandas_input_fn'? if it can be used, that would simplify the code.

ValidationMonitor is deprecated. We'll not add new examples of it. Could you please remove it?

I couldn't understand the value of n_classes? since label column is binary. if n_classes doesn't make sense to parameterize, can you please remove it?

**Comment by drpngx** [comment]
@GuohongLi ping?

**Comment by vrv** [comment]
Closing due to lack of response for 4 weeks, please re-open a new PR with the addressed changes if you can!  Thank you for your contribution.

**Pull request closed without merging**
