### PR TITLE
Fix tf.contrib.framework.init_from_checkpoint

### PR DESCRIPTION
**Pull request by vladfi1**
Loading to variables in the root scope (`/`) was not supported.

### CODE REVIEW

**Comment by vladfi1** [comment]
@googlebot I signed it!

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by concretevitamin** [comment]
@vihanjain @ispirmustafa can you take a look?

**Review by ispirmustafa — APPROVED** [review]
Thanks for catching the corner case!

**Pull request merged**
