### PR TITLE
Fix analogy response of word2vec interactive when the response is unicode.

### PR DESCRIPTION
**Pull request by muik**
I run word2vec.py with interactive mode.

```
$ python word2vec.py --interactive --train_data=t --eval_data=q --save_path=save
...
In [3]: model.analogy(b'남자', b'여자', b'아빠')
Out[3]: '\xec\x97\x84\xeb\xa7\x88'
```

The response of analogy couldn't be readable.

So I fix the response and then rerun the code.

```
In [3]: model.analogy(b'남자', b'여자', b'아빠')
엄마
```

Now I can see the response.

### CODE REVIEW

**Comment by danmane** [comment]
This doesn't seem quite right to me. Why should the analogy function sometimes return a string, but sometimes print a string and then return nothing? That is a strange contract for a function, and will confuse users of this code who are depending on the return value (i.e. not in interactive mode).

Instead of changing the type signature of the function, can you instead make it handle unicode correctly?

**Comment by muik** [comment]
@danmane  I agree a strange contract for the analogy function. But IPython always prints an unreadable unicode output which is decoded or not.

IPython examples:
```
In [1]: '한글'
'\xed\x95\x9c\xea\xb8\x80'

In [2]: '한글'.decode('UTF-8')
u'\ud55c\uae00'
```

So I fixed the function to be printing a result like the nearby function which is also a function for an interactive mode.

**Comment by rmlarsen** [comment]
@danmane please give this another look.

**Comment by danmane** [comment]
Ok, @zffchen78 (who has a bit more context on this code) gave it LGTM.
@tensorflow-jenkins, test this please.

**Pull request merged**
