### PR TITLE
Fix trivial typos in source codes / comments

### PR DESCRIPTION
**Pull request by inureyes**
- Fix trivial typos in source codes / comments

### CODE REVIEW

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by gunan** [comment]
Can one of the admins verify this patch?

**Comment by martinwicke** [comment]
I'm killing the test jobs for now to make space for release tests (sorry!).

**Comment by martinwicke** [comment]
I'll restart them later.

**Comment by vrv** [comment]
Linux GPU PIP passed, and this was just doc changes, so I'll merge.

**Pull request merged**
