### PR TITLE
[WIP] Add a cache layer to record_reader

### PR DESCRIPTION
**Pull request by snnn**
#8715

### CODE REVIEW

**Comment by snnn** [comment]
test code:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import logging
import argparse
import os.path
import sys
import math
import time
import tensorflow as tf
from tensorflow.python.ops import data_flow_ops
from tensorflow.python.ops import control_flow_ops


def train_fn(sess,label):
  train_fn.counter += 1
  train_start_time = time.time()
  result = sess.run(label)
  duration = time.time() - train_start_time
  print("step %d: count = %g, dur = %g" % (train_fn.counter,len(result),duration))

def main(_):
    logger = logging.getLogger('tensorflow')  
    logger.setLevel(logging.INFO)
    global_step = tf.train.get_or_create_global_step()
    reader = data_flow_ops.RecordInput("D:\\testdata2\\tf\\*.tfrecord",parallelism=1,buffer_size=1024,name="record_input",batch_size=40960)
    y = reader.get_yield_op()
    features = tf.parse_example(
        y,
        # Defaults are not specified since both keys are required.
        features={
            'l': tf.FixedLenFeature([], tf.float32),
            'v': tf.VarLenFeature(tf.int64)
        })
    label = features['l']
    features = features['v']
    # Ensure the train_tensor computes grad_updates.
    train_op = control_flow_ops.with_dependencies([global_step], label)  
    train_fn.counter = 0

    sv = tf.train.Supervisor(logdir="t3",save_summaries_secs=1,global_step = global_step)
    tf.train.basic_train_loop(sv,train_fn,[train_op])
  

if __name__ == '__main__':
  tf.app.run()
```

before:
INFO:tensorflow:global_step/sec: 0
step 1: count = 40960, dur = 0.215178
step 2: count = 40960, dur = 0.206151
step 3: count = 40960, dur = 0.206683
step 4: count = 40960, dur = 0.214185
INFO:tensorflow:global_step/sec: 0
step 5: count = 40960, dur = 0.208147
step 6: count = 40960, dur = 0.205167
step 7: count = 40960, dur = 0.206236
step 8: count = 40960, dur = 0.204632
step 9: count = 40960, dur = 0.203644
INFO:tensorflow:global_step/sec: 0
step 10: count = 40960, dur = 0.205663
step 11: count = 40960, dur = 0.203331
step 12: count = 40960, dur = 0.208636
step 13: count = 40960, dur = 0.207647

After:
step 1: count = 40960, dur = 0.0535386
step 2: count = 40960, dur = 0.0370266
step 3: count = 40960, dur = 0.0395277
step 4: count = 40960, dur = 0.038027
step 5: count = 40960, dur = 0.038027
step 6: count = 40960, dur = 0.0395284
step 7: count = 40960, dur = 0.0350249
step 8: count = 40960, dur = 0.0355251
step 9: count = 40960, dur = 0.0350249
step 10: count = 40960, dur = 0.0355251
step 11: count = 40960, dur = 0.0370266
step 12: count = 40960, dur = 0.0385275
step 13: count = 40960, dur = 0.0370264
step 14: count = 40960, dur = 0.0370262
step 15: count = 40960, dur = 0.0375264

**Comment by yifeif** [comment]
@saxenasaurabh could you take a look at this change? Thanks!

**Comment by drpngx** [comment]
@saxenasaurabh feel free to comment directly here or LMK if you don't have cycles for this.

**Comment by snnn** [comment]
Two unitests failed due to this new implementation doesn't support seek operation. I'm thinking how to resolve it.

**Comment by saxenasaurabh** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
@snnn any progress?

**Comment by snnn** [comment]
Sorry, I'm in vacation. Let me close it first.

**Pull request closed without merging**
