### PR TITLE
read_up() for slim parallel reader #11164

### PR DESCRIPTION
**Pull request by akindyakov**

### CODE REVIEW

**Comment by vrv** [comment]
@sguada looks to be OOO at a conference this week, so this will have to wait until he gets back, I think.

**Review by sguada — APPROVED** [review]
Looks good, thanks.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
The failing TF Eager mode test is unrelated. Merging.

**Pull request merged**
