### PR TITLE
Enable Use of Cudnn APIs for Backward Input Grouped Convolutions

### PR DESCRIPTION
**Pull request by AyanmoI**
As per @akuegel 's comment https://github.com/tensorflow/tensorflow/pull/30370#discussion_r301941616
in https://github.com/tensorflow/tensorflow/pull/30370 , creating a new PR to enable use of cudnn for backward input grouped conv

### CODE REVIEW

**Comment by gbaned** [comment]
@akuegel Hi, Could you please review this PR ?

**Comment by AyanmoI** [comment]
Hi @akuegel ... I need to make changes to this PR to make it complete. I am working on the depthwise backward filter conv pass like we discuss in https://github.com/tensorflow/tensorflow/pull/30370 and it is almost done. All tests pass and seems to improve mobilnet performance. I will put up a public PR soon. If you want that I enable cudnn for backward input after that PR is merged, I can do that and close this for now. Or I can make changes to this PR now. Please let me know what you think will be appropriate.

**Comment by AyanmoI** [comment]
@akuegel Sorry for the delay in pushing this commit. This was sitting on my machine for a while now. In my experiments, even I found that thunking grouped backward input conv to cudnn backwar APIs doesn't do much (unlike grouped backward filter). So till we can make cudnn better for this, I reverted `MatchBackwardInput` back to state where it thunks to cudnn fwd for group_count > 1. However, the existing code that was supposed to map grouped backward input to cudnn, IMO, was incorrect. I change that piece of code to do the right thing. Incase we decide to use cudnn backward for grouped backward inputs, this change in conjunction with the algebraic simplification pipeline I introduced in #31597, will clean up the final graph and eventually do the right thing.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Review by akuegel — APPROVED** [review]

**Pull request merged**
