### PR TITLE
Fixes to the getting started documentation

### PR DESCRIPTION
**Pull request by alanyee**
Removed some unneeded code, streamlined the code, fixed a broken example, corrected output for example code, minor grammar fix

### CODE REVIEW

**Comment by alanyee** [comment]
I noticed this file referred to `tf.estimator` instead of `tf.contrib.learn`, but the current version of TensorFlow (1.2.0) seems not to `tf.estimator.LinearRegressor` yet. I am unsure how to approach this discrepancy from https://www.tensorflow.org/get_started/get_started.

**Comment by drpngx** [comment]
@alanyee about the `DNNRegressor`, the current documentation is correct. This is causing some confusion right now until 1.2.0 is released.

@MarkDaoust Could you take a look at this PR? It looks like some numbers changed.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by alanyee** [comment]
@drpngx `DNNRegressor`? I think I was talking about `LinearRegressor`.

Also I updated another part of the webpage again. Could you run the Jenkins again?

**Comment by drpngx** [comment]
Jenkins, test this please.

The core version is what we want people to use moving forward, except that it's not here yet.

**Comment by drpngx** [comment]
@gunan before I investigate, just making sure that nothing changed on the Mac side that would cause these failures right?

**Comment by gunan** [comment]
Looks like another one of the xcode issues we keep seeing on mac1
https://ci.tensorflow.org/job/tensorflow-pull-requests-mac/5552/console
@caisq, could you take a look?

The build failure is definitely unrelated, PR ok to merge.

**Comment by caisq** [comment]
Hmmm. Let me try removing the old version of xcode tomorrow.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Thank you @gunan and @caisq ! It passed.

@MarkDaoust what do you think of the changes?

**Review by MarkDaoust — APPROVED** [review]
I suggest we keep the dtypes on the variables (to stay in sync with the upper part of the file).

I've attached the commit.

Other than that, this all seems good.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Pull request merged**
