### PR TITLE
Added mode to input_fn argument

### PR DESCRIPTION
**Pull request by k-w-w**
And modified existing tests to include the mode argument. 

(deleted previous PR because I accidentally pulled a bunch of other commits into the branch)

### CODE REVIEW

**Review by ispirmustafa — APPROVED** [review]
Thank you!

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Seems like an unrelated failure.
```
[ RUN      ] NaryGradTest.Select
tensorflow/cc/gradients/math_grad_test.cc:699: Failure
Expected: (max_error) < (1e-3), actual: 0.170095 vs 0.001
[  FAILED  ] NaryGradTest.Select (7 ms)
```

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by drpngx** [comment]
Not sure what happened to the Linux XLA log.

Jenkins, test this please.

**Comment by drpngx** [comment]
@gunan any idea what happened to the Linux XLA test? I ran kokoro and Jenkins again and it's still 404.

**Comment by drpngx** [comment]
Ignoring Jenkins build Linux XLA that is now in kokoro.

**Pull request merged**
