### PR TITLE
Minor Python code health improvements

### PR DESCRIPTION
**Pull request by frankfqchen**
Minor Python code health improvements

### CODE REVIEW

**Comment by frankfqchen** [comment]
I signed it!

**Comment by drpngx** [comment]
Please sync & rebase. The CLA doesn't seem to have passed properly. Could you go back to the web site and make sure it's done? Then "I signed it!" again.

**Comment by vrv** [comment]
I think you are okay with the CLA so:

1) Make sure your github commits use the email address you signed the CLA with
2) Make sure you add this email to your github account.
3) Respond to this PR and it should trigger the CLA check again.

**Comment by vrv** [comment]
Closing -- feel free to ping this thread when you can sign the CLA.

**Pull request closed without merging**
