### PR TITLE
Branch 178185697

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by caisq** [comment]
cc @ankurtaly

**Comment by caisq** [comment]
test failure in "Ubuntu Contrib" is a known flake.

**Review by gunan — APPROVED** [review]

**Comment by ppwwyyxx** [comment]
Similar here:
```
ERROR: /home/xxx/tensorflow/tensorflow/contrib/boosted_trees/lib/BUILD:31:1: C++ compilation of rule '//tensorflow/contrib/boosted_trees/lib
:utils' failed (Exit 1).
In file included from ./tensorflow/core/framework/allocator.h:23:0,
                 from ./tensorflow/core/framework/tensor.h:20,
                 from ./tensorflow/contrib/boosted_trees/lib/utils/sparse_column_iterable.h:19,
                 from tensorflow/contrib/boosted_trees/lib/utils/sparse_column_iterable.cc:16:
./tensorflow/core/framework/numeric_types.h: In constructor 'tensorflow::bfloat16::bfloat16(float)':
./tensorflow/core/framework/numeric_types.h:49:16: error: 'isnan' was not declared in this scope
     if (isnan(v)) {
```

**Comment by castleguarders** [comment]
Issue still alive, with nvcc

**Comment by gunan** [comment]
Issue is known, and we will try to fix them as a part of https://github.com/tensorflow/tensorflow/pull/14773
There is nothing we can do as a part of this PR, as this is just a part of our sync processs, and it is already merged.

**Pull request merged**
