### PR TITLE
Rint Operator

### PR DESCRIPTION
**Pull request by chemelnucfin**
round to nearest operator #709

### CODE REVIEW

**Comment by chemelnucfin** [comment]
Had to force push the branch and lost the comments.  I removed the google/protobuf commit, and @girving was mentioning about @martinwicke 's CL.  Also about the using directives being moved elsewhere.

**Comment by martinwicke** [comment]
Yeah, can you remove the change to stream_executor? If it still works after that change (which I expect it would -- my change was almost identical except for that), I'll merge it.

**Comment by chemelnucfin** [comment]
@martinwicke Removed from stream_executor.  Thanks.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Ah. backwards_compatibility_test. Check the build log -- it's a simple thing to fix, the console log contains instructions. Add the changed files to this PR.

**Comment by chemelnucfin** [comment]
@martinwicke I added manually to the ops.pbtxt (which I'm guessing is autogenerated).  However, I don't have the tensorflow/core/ops/compat/ops_history.v0.pbtxt file from this commit:
commit c1a40c7b9085719cb120ae92f991f86d0757af7e 

I don't have the entire tensorflow/core/ops/compat directory or the associated test with it (which is why my tests passed, I guess)

**Comment by vrv** [comment]
You should be able to run 

bazel-bin/tensorflow/core/ops/compat/update_ops tensorflow/core/ops

and things will work

**Comment by chemelnucfin** [comment]
@vrv I don't have that directory either.  I have searched for update_ops.  Is that an option in configuration or maybe just an internal directory?

**Comment by chemelnucfin** [comment]
@vrv @girving @martinwicke looks like the compat directory was put in.  I checked in the op history files and this should be ready to go!

**Comment by martinwicke** [comment]
Can you rebase? Sorry I sat on this.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by chemelnucfin** [comment]
@martinwicke Do you want me to update the branch still?  I don't want you to have to run another test.

**Comment by martinwicke** [comment]
yes, please update, I can't merge without (we discontinued our merge script and now we're stuck with github's button)

**Comment by chemelnucfin** [comment]
ok.  Let me see if I can update from github and merge it or if I need to
rebase and push from my end.

**Comment by martinwicke** [comment]
if you update from github it'll make an ugly merge commit. It's really bad
actually. and they don't allow merges any more if the PR is not rebased to
head. Silly.

**Comment by chemelnucfin** [comment]
Should be fine now.  Thanks for putting up with the hassle!

**Comment by vrv** [comment]
@martinwicke: we can still merge when the branch is out of date, as long as there is no conflict.  It's just that they recently changed the icon to match the same one that indicates conflict, so it's hard to tell :)

**Comment by martinwicke** [comment]
I guess the reasoning is that if you merge, you never know whether the merge is any good.

**Comment by martinwicke** [comment]
@vrv You rolled this back, right? It's not at head -- do you remember what the problem was?

**Pull request merged**
