### PR TITLE
Cherrypicks

### PR DESCRIPTION
**Pull request by av8ramit**

### CODE REVIEW

**Review by jhseu — APPROVED** [review]

**Review by MarkDaoust — APPROVED** [review]
LGTM for my commit.

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Review by rryan — APPROVED** [review]
LGTM for tf.contrib.spectral (thanks!) but I think it may need 2 more fixes for test timeouts and error bounds. I commented on the bug you filed.

**Comment by av8ramit** [comment]
GPU tests can be ignored since the tag has changed.

**Pull request merged**
