### PR TITLE
add a simple tensorflow model safety-check tool

### PR DESCRIPTION
**Pull request by zhangbo5891001**
Check whether a TensorFlow model contains security sensitive ops, Output related info.

This script is designed to take a checkpoint or SavedModel model file,
and detect whether it contains security ops, and output the check result.

Traditionally, a TensorFlow model is considered as data files, this
leads people to ignore the fact that the TensorFlow model/graph
is actual program/code which contains kinds of ops and runs under the
TensorFlow runtime. Therefore, it is possibile to use legitimate ops
to do some malicious things in a model file. This script just checks
some predefined sensitive ops, do not rely on its result completely.

For security risks of TensorFlow model, your can refer to this: 
https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md

### CODE REVIEW

**Comment by martinwicke** [comment]
Can you check that the email on your commits matches the email you use in your github account? Otherwise out CLA checker gets confused.

**Comment by zhangbo5891001** [comment]
Yes, the email is  zhangbo5891001@gmail.com in my github account,  and I have signed CLA.
I don't know why CLA check failed...
Any suggestions? Thanks!

**Comment by martinwicke** [comment]
Looks like CLABot caught up. Thank you!

@zhangbo5891001, we were internally discussion whether this would make most sense as a `--security-scan` option to `saved_model_cli`. What do you think? Then all the tools are in one place.

@yifeif was looking into this.

**Comment by yifeif** [comment]
I have a pending change internally on saved_model_cli that does something similar. I can convert it into a PR if that makes it easier.

**Comment by martinwicke** [comment]
Yeah, then we can compare. @zhangbo5891001 I think the big question is whether a separate command is preferable for some reason. We were leaning towards something integrated into saved_model_cli to be able to share a bunch of code.

**Comment by zhangbo5891001** [comment]
@martinwicke It seems that the saved_model_cli is a tool for only 'SavedModel' file. Therefore I make a seperate tool both for checkpoint and SavedModel and mainly for security.
We can add more security checks to this tool if any other security risks found  in the subsequent tensorflow versions.

**Comment by yifeif** [comment]
I added the saved_model_cli version at #17529. It doesn't check for checkpoint though as @zhangbo5891001 pointed out, and I would prefer to not add checkpoint check to saved_model_cli to keep it clean. @martinwicke what do you think is the best way to proceed here?

**Comment by martinwicke** [comment]
@yifeif I agree we should keep raw checkpoints out of saved_model_cli. We are actively encouraging saving models as SavedModels. 

@zhangbo5891001 users would have to write their own code to interpret a checkpoint + metagraph. There isn't enough information in the metagraph to simply run it. What is the threat model here? I can see a situation where someone writes a graph execution tool and then runs untrusted graphs which happen to conform to an interface that make them work with this custom tool. 

The way to formally specify the interface (and therefore make this something you can actually share) would be to produce a SavedModel. I would be in favor of adding functionality to saved_model_cli to allows converting a graph + (optionally) a checkpoint + (optionally) inputs and outputs to a SavedModel. Checking that for vulnerabilities (see #17529) makes a lot of sense.

**Comment by zhangbo5891001** [comment]
@martinwicke @yifeif Yes, I agree that keep saved_model_cli clean. That's why I make a separate tool.

The real threat of TensorFlow model is the ops in GraphDef of metagraph or SavedModel. Given a metagraph + checkpoint, one can run the graph(load metagraph then run session). Although TensorFlow encourages using SavedModel, many users still use checkpoint + metagraph as the serialization of models.

If we want to keep saved_model_cli clean and consider the threat of checkpoint + metagrap, maybe the way @martinwicke mentioned is a good choice.

> adding functionality to saved_model_cli to allows converting a graph + (optionally) a checkpoint + (optionally) inputs and outputs to a SavedModel. Checking that for vulnerabilities

**Comment by frankchn** [comment]
@martinwicke Do we still need this open?

**Comment by martinwicke** [comment]
No, I think we should add the ability to assemble a `SavedModel` from a checkpoint to `saved_model_cli` instead.

**Pull request closed without merging**
