### PR TITLE
Update 1_notmnist.ipynb

### PR DESCRIPTION
**Pull request by fire717**
I'm learning Tensorflow on the Udacity,and while I flow the course to test code,I found that the url in Update 1_notmnist.ipynb is wrong,it can't be open.After a while,I found the url in the video is different from the one in the file,so I pause the vedio and remenber the url.This url is ok and it pass the test perfectly. Thx for ur attention.

### CODE REVIEW

**Comment by gengqx** [comment]
@fire717  Maybe this is because of you are in China.So you have a little problem connect to the google server. I'm in China too,I could use this url by this way :
'url = 'https://commondatastorage.googleapis.com/books1000/''
This works well for me maybe I used VPN.

**Comment by fire717** [comment]
I tried VPN,too.I can open FACEBOOK, but this page shown like this(U can see it more clear on the picture):


This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous users does not have storage.objects.list access to bucket books1000.</Details></Error>






在2016年11月08 09时31分, "gengqx"<notifications@github.com>写道:



@fire717  Maybe this is because of you are in China.So you have a little problem connect to the google server. I'm in China too,I could use this url by this way :
'url = 'https://commondatastorage.googleapis.com/books1000/''
This works well for me maybe I used VPN.

**Comment by fire717** [comment]
I signed it!






在2016年11月09 14时15分, "googlebot"<notifications@github.com>写道:



Thanks for your pull request.  It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝Please visit https://cla.developers.google.com/ to sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify.  Thanks.

If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your email is set on your git commits.
If you signed the CLA as a corporation, please let us know the company's name.

**Comment by gengqx** [comment]
@fire717  Have a try: Change ‘http’ into ‘https’.

**Comment by vincentvanhoucke** [comment]
FYI, we won't be moving back to the yaroslavvb.com address, as it's someone's private server. Let me know if there is anything we can do to make the Google address work better for you, but I'm afraid it's out of my hands.

**Pull request closed without merging**
