### PR TITLE
change to ANSI C style for loop

### PR DESCRIPTION
**Pull request by luxupu**

### CODE REVIEW

**Comment by harshini-gadige** [comment]
@luxupu  Request you to sign the CLA in order to proceed further steps in merging this PR. Thanks !

**Comment by luxupu** [comment]
I signed it!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by hgadig** [comment]
Sorry to say but we cannot proceed until CLA reflects YES. Could you please open a new PR(which may resolve the CLA issue) and try. Closing this.

**Pull request closed without merging**
