### PR TITLE
R1.12

### PR DESCRIPTION
**Pull request by huaxiaozhong1**
When I was interested in running TfLite on Rapeberry Pi for embedded system or IoT, I was hungry for finding guide to build apps, after which I could exert my energy. With googling, I noticed that many developers met the same bottleneck. Now, I created the "pull request" in order to contribute community 2 TfLite apps that are able to run at Raspberry Pi 3. Here are the steps to build/run the apps.

    1, Follow https://www.raspberrypi.org/learning/software-guide/quickstart/, to install Raspbian onto a Raspberry Pi 3 board. 
    #sudo apt install build-essential
    Follow https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/pi_examples to install camera. 
    Verify if the camera works or not:
    #raspistill -v

    2, git clone -b r1.12 https://github.com/huaxiaozhong1/tensorflow.git. (The best, this is done within the latest docker container of Ubuntu 18.04).
    It will clone 6 static libraries into /tensorflow/tensorflow/contrib/lite/examples/camera/libs:
    libjpeg.a librt.a libv4l1.a libv4l2.a libv4l2rds.a libv4lconvert.a.
    Actually they are from Pi environment prepared at step 1:

    3, In the container of host: 
    #apt update
    #apt upgrade
    #apt install crossbuild-essential-armhf
    #cd /tensorflow
    #./tensorflow/contrib/lite/tools/make/download_dependencies.sh
    #apt install -y libjpeg-dev
    #apt install libv4l-dev
    #./tensorflow/contrib/lite/tools/make/build_rpi_lib.sh
    Now, you could find ./tensorflow/contrib/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a, /tensorflow/tensorflow/contrib/lite/tools/make/gen/rpi_armv7l/bin/label_image and /tensorflow/tensorflow/contrib/lite/tools/make/gen/rpi_armv7l/bin/camera. 

    4, Copy label_image and camera, the Linux executables, to Raspeberry board. 
    Copy grace_hopper.bmp from /tensorflow/tensorflow/contrib/lite/examples/label_image/testdata of host’s container to the board.
    Copy labels.txt from /tensorflow/tensorflow/contrib/lite/java/ovic/src/testdata of host’s container to the board.
    Download Mobilenet_v2_1.0_224_quant.tflite from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models.md to the board.
    The 3 data files and 2 Linux executables should be inside the same folder.

    5, Run the 2 apps one by one. 

    Note: the base branch that I added the 2 apps into is r1.12. Now TfLite has been announced to move out of contrib. But when I ran build_rpi_lib.sh in the latest tensorflow/tensorflow:nightly-devel, it didn’t get success. So, may I submit the pull-request based at r1.12 right now? I could add the same feature on r1.13+ as soon as it succeeds in building libtensorflow-lite.a.

    Thank you so much, and looking forward to hearing from you,

                                                     Xiaozhong(Jim) Hua

### CODE REVIEW

**Comment by huaxiaozhong1** [comment]
Having updated to v0.16 with files changed:
./tensorflow/contrib/lite/tools/make/Makefile,
./tensorflow/contrib/lite/tools/make/build_rpi_lib.sh.
With the update, a new environment variable, TfLite_RPI_APPS, is added. It could be set in build_rpi_lib.sh. If it is not set as true, the 2 apps won't be generated. The building process won't be blocked on that case. 
Please don't hesitate to let me know if more tests are needed, or more consideration needs to be taken into.
Thanks,
--Jim

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 26 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 41 days with no activity and the `awaiting review` label has been applied.

**Comment by petewarden** [comment]
Unfortunately we can't take binary files (like .a libs) into the repository. I'd be happy to add documentation links to point to your example if you wanted to host it as a standalone github project though? Thanks for this, and sorry for the delay in responding.

**Pull request closed without merging**
