### PR TITLE
Add a unit test for training and validation callbacks

### LINKED ISSUE #32819: Shared and mutated state between training and validation callbacks
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Datalab
- Mobile device: NA
- TensorFlow installed from: Binary
- TensorFlow version: 1.15.0rc1
- Python version: 3.5.6
- Bazel version: NA
- GCC/Compiler version: NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**

When invoking `keras.Model.fit` with two `data.Dataset`s, one is for training, and one is validation, so that the training one is infinite with `epochs` and `steps_per_epoch` provided to `fit`, and the validation one is finite without any additional parameters to `fit`, the progress bar shows incorrect number of steps after the first validation. In particular, the number of steps per epoch gets set to the number of steps in the validation set.

**Describe the expected behavior**

The prescribed `steps_per_epoch` remains the same in the progress bar for all epochs.

**Code to reproduce the issue**

See below.

**Other info / logs**

I believe the problem is due to this modification when the input is exhausted:

https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/python/keras/engine/training_v2.py#L136

The number of steps gets overwritten. However, `self.params` is shared across both the training and validation callbacks, which essentially misleads the progress bar for training. The state share is potentially due to the following line:

https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/python/keras/engine/training_v2.py#L347

In other words, `validation_callbacks` is based on `training_callbacks`. `configure_callbacks` should probably take `callbacks` instead.

### PR DESCRIPTION
**Pull request by IvanUkhov**
The test is to check that the progress bar shown by Keras during the training process is working properly when training and validating with inputs of unknown sizes.

### CODE REVIEW

**Comment by pavithrasv** [comment]
Can you verify that progress bar logger looks good and works as expected? i remember trying this and something was failing, don't recall what now.

**Comment by IvanUkhov** [comment]
Well, I tried with the same code as the one I wrote in #32819, and it worked as expected. However, I don’t I’m in the position to guarantee that it doesn’t break anything. I assumed the test suite would catch if there would be any problems.

**Comment by pavithrasv** [comment]
Sounds good, can you add a test case for the two Dataset use case you tested in callbacks_test? There are existing unit tests that check Progbar, may be we can add something similar for this case?

**Comment by IvanUkhov** [comment]
The current status is that all tests in `keras` pass with the proposed change:

```
bazel test //tensorflow/python/keras/...
...
Executed 151 out of 152 tests: 152 tests pass.
INFO: Build completed successfully, 771 total actions
```

(There was apparently one skipped, but I suspect it was due to a previous run.)

I will then add a test, as it was suggested.

**Comment by pavithrasv** [comment]
Thank you for adding the test, can you confirm that the test you added fails without the change?

**Comment by IvanUkhov** [comment]
I did the following on master (earlier I reported results with respect to what comes with `tensorflow/tensorflow:devel-py3` without pulling).

Without any changes and any new tests, the following one was failing under `keras`:

```
bazel test //tensorflow/python/keras/...
...
//tensorflow/python/keras/distribute:multi_worker_fault_tolerance_test   FAILED in 14 out of 14 in 9.2s
...
Executed 152 out of 152 tests: 151 tests pass and 1 fails locally.
INFO: Build completed, 1 test FAILED, 16920 total actions
```

I assumed it was irrelevant.

Then I focused on `keras:callbacks_test`, added the test there, and got a failure:

```
bazel test //tensorflow/python/keras:callbacks_test
...
//tensorflow/python/keras:callbacks_test                                 FAILED in 3 out of 4 in 38.8s
...
INFO: Build completed, 1 test FAILED, 5 total actions
```

However, it was due to a different reason (not what the test was asserting):

```
  File "…/tensorflow/python/keras/callbacks_test.py", line 352, in test_progbar_logging_training_validation
    steps_per_epoch=20)
...
ValueError: When using data tensors as input to a model, you should specify the `steps_per_epoch` argument.
```

It complained that `steps_per_epoch` was not given, but it was. I thought it was due to a bug in what is version 1, since it was coming from `training.py`, not `training_v2.py` (the latter is what this pull request makes an adjustment to). I forced the test to exclusion version 1:

```python
@keras_parameterized.run_all_keras_modes(always_skip_v1=True)
```

Still without any changes outside the tests, the new test succeeded. I confirmed that the test was properly executed by changing the expected output and seeing it fail.

I thought it was fixed on master and checked out `v1.15.0-rc1`. Without any changes and any new tests, there was already one failure:

```python
bazel test //tensorflow/python/keras/...
...
//tensorflow/python/keras:callbacks_test                                 FAILED in 4 out of 4 in 61.1s
...
Executed 153 out of 153 tests: 152 tests pass and 1 fails locally.
INFO: Build completed, 1 test FAILED, 10644 total actions
```

And it was `test_progbar_logging_validation_split`, which the new test was actually based on. The new test with `always_skip_v1=True` gave the following:

```
[ RUN      ] KerasCallbacksTest.test_progbar_logging_training_validation_v2_eager_sequential
[  FAILED  ] KerasCallbacksTest.test_progbar_logging_training_validation_v2_eager_sequential
[ RUN      ] KerasCallbacksTest.test_progbar_logging_training_validation_v2_funcgraph_subclass
[       OK ] KerasCallbacksTest.test_progbar_logging_training_validation_v2_funcgraph_subclass
```

And it was, as expected, due to `AssertionError: Regex didn't match…`. Then I changed the calculation of `validation_callbacks`, as shown in the patch, and got the following:

```
[ RUN      ] KerasCallbacksTest.test_progbar_logging_training_validation_v2_eager_sequential
[       OK ] KerasCallbacksTest.test_progbar_logging_training_validation_v2_eager_sequential
[ RUN      ] KerasCallbacksTest.test_progbar_logging_training_validation_v2_funcgraph_subclass
[       OK ] KerasCallbacksTest.test_progbar_logging_training_validation_v2_funcgraph_subclass
```

(`test_progbar_logging_validation_split` was failing as before.)

So what do we do with all this?

**Comment by pavithrasv** [comment]
Thank you for the detailed notes, i agree about adding the test case since it will be useful and we can call the issue done.

**Comment by IvanUkhov** [comment]
I’ve rebased and remove the first commit.

**Review by pavithrasv — CHANGES_REQUESTED** [review]
Thank you! Could you update the title/desc to reflect the changes

**Comment by IvanUkhov** [comment]
Done!

**Review by pavithrasv — DISMISSED** [review]
Thank you!

**Comment by IvanUkhov** [comment]
I’ve looked through the failed builds, and one was them was due to the new code. There was incorrect indentation on two lines. Fixed.

**Comment by rthadur** [comment]
Seems auto-merge is not happening but the changes are now committed so we can close this. Thank you for the PR.

**Pull request closed without merging**
