### PR TITLE
Update NCCL and Eigen sources for CUDA9

### PR DESCRIPTION
**Pull request by nluehr**
Also fix presumably outdated manifest_proto_py_pb2 and pandas dependencies.

### CODE REVIEW

**Comment by drpngx** [comment]
That seems to update eigen.

@lukeiwanski @benoitsteiner @rmlarsen what do you think?

**Comment by lukeiwanski** [comment]
I am pretty sure that this PR will hit the same issue as we did in https://github.com/tensorflow/tensorflow/pull/12010#issuecomment-320093539 .

In order to avoid that Eigen needs to get bumped to at least: https://bitbucket.org/eigen/eigen/commits/da11a2b1da3f93a3f1e5328368731f0ee8cdbab2?at=default

**Comment by nluehr** [comment]
Updated eigen changeset to top of default branch.

Also, what action is required for the bazel mirror 'http://mirror.bazel.build/bitbucket.org/eigen/eigen/get/f3a22f35b044.tar.gz' to get created?

**Comment by zheng-xq** [comment]
For the Eigen changes, assign the reviewer to Benoit

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Review by benoitsteiner — APPROVED** [review]

**Pull request merged**
