### PR TITLE
State variable seperated from others.

### PR DESCRIPTION
**Pull request by arnavmehta7**
Resolved the todo i.e., to separate the state variable from the other variables.

### CODE REVIEW

**Comment by arnavmehta7** [comment]
Oh how do I solve this?

**Comment by arnavmehta7** [comment]
@sirakiin Hey, I'm quite new to this, can you tell me what is AMD ROCm and how can I solve this?

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
This is not what the comment wanted. The code mixes state and options and needs a larger refactor to separate them.

As it is, this is a no-op, just moves a line around without any actual semantic change

**Comment by gbaned** [comment]
Hi @arnavmehta7 Can you please check @mihaimaruseac's [comments](https://github.com/tensorflow/tensorflow/pull/57695#pullrequestreview-1232178713) and keep us posted ? Thank you!

**Pull request closed without merging**
