### PR TITLE
New Updated curl to 7.65.1 #30650 

### PR DESCRIPTION
**Pull request by shubham769**
Updated curl to latest version

### CODE REVIEW

**Review by d0k — CHANGES_REQUESTED** [review]
The curl change looks good, but there are quite a bunch of unrelated changes in this file. Mind rebasing to master?

**Comment by shubham769** [comment]
> The curl change looks good, but there are quite a bunch of unrelated changes in this file. Mind rebasing to master?

@d0k Done with the rebasing , kindly check it again please.

**Review by d0k — DISMISSED** [review]
I'm seeing unrelated changes again. I guess this is really just that workspace.bzl is changing all the time? I'll approve this now, let's see how merging goes.

**Comment by shubham769** [comment]
> I consent

**Pull request closed without merging**
