### PR TITLE
Add links to new tensorflow Udacity courses #852

### PR DESCRIPTION
**Pull request by PatrickChrist**
Hey TF-Team,

I added two links to the new tensorflow Udacity course in the Main Readme.md and the Udacity Courses examples Readme.md

Cheers,
Patrick

### CODE REVIEW

**Comment by vincentvanhoucke** [comment]
@tensorflow-jenkins ok to test

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
(I would prefer squashing these two commits, since they are small)

**Comment by PatrickChrist** [comment]
Is there anything I can do for you guys?

**Comment by vrv** [comment]
(yeah, squash the commits into one.  See [here](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit))

**Comment by vincentvanhoucke** [comment]
Merged, thanks!

**Pull request closed without merging**
