### PR TITLE
Stream image build logs in dockerfile assembler system

### PR DESCRIPTION
**Pull request by xiamaz**
This change enables streaming image build logs when using `assembler.py` by using the lower level docker APIClient and manually handling the returned log stream.

This change is useful for modifications on dockerfiles, since behavior can be inspected before a build is finished.

### CODE REVIEW

**Comment by angersson** [comment]
This looks pretty cool. Thanks!

**Review by angerson — DISMISSED** [review]

**Comment by angersson** [comment]
@xiamaz I got an error with `asm_images --release nightly --build_images`:

```
After this operation, 905 kB of additional disk space will be used.
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 wget amd64 1.17.1-1ubuntu1.4                                                                                     
  404  Not Found [IP: 91.189.88.162 80]
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 wget amd64 1.17.1-1ubuntu1.4                                                                                     
  404  Not Found [IP: 91.189.88.162 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/wget/wget_1.17.1-1ubuntu1.4_amd64.deb  404  Not Found [IP: 91.189.88.162 80]                                       

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Docker image build complete.
Traceback (most recent call last):
  File "assembler.py", line 719, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "assembler.py", line 619, in main
    if image_id:
UnboundLocalError: local variable 'image_id' referenced before assignment
```

It seems like this can fail improperly when a build failure happens. Can you take a look?

**Comment by angersson** [comment]
@rthadur can you revert the state of this PR to "awaiting review"?

**Comment by xiamaz** [comment]
@angersson Thanks. Failed image builds should be correctly handled now.

**Review by angerson — APPROVED** [review]
Seems good to me now, thanks!

**Comment by angersson** [comment]
This has been merged (see above), but I guess GitHub got confused. Closing. Thanks for your contribution!

**Pull request closed without merging**
