### PR TITLE
Fix to the build override input-shape issue

### PR DESCRIPTION
**Pull request by bono1567**
https://github.com/tensorflow/tensorflow/issues/34141

Was passing input_shape (which was null). Please review and comment.

### CODE REVIEW

**Comment by bono1567** [comment]
@rthadur I have made a minor change. The test cases are already present.

**Comment by mihaimaruseac** [comment]
Please give a better title and description. Please add tests.

**Comment by bono1567** [comment]
@mihaimaruseac Please review and comment

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by bono1567** [comment]
@mihaimaruseac Is there anything that is blocking the merge? 
I am new to the community hence I don't know much.

**Comment by mihaimaruseac** [comment]
You have the check statuses below the PR. For example, Ubuntu Sanity failed (ignore the Android one)

```
5. do_buildifier: buildifier check
  FAIL
```

```
=== Sanity check step 5 of 15: do_buildifier (buildifier check) ===

Running do_buildifier on 373 files

tensorflow/compiler/jit/BUILD # reformat
tensorflow/compiler/xla/BUILD # reformat

buildifier took 1 s

FAIL: buildifier found errors and/or warnings in above BUILD files.
buildifier suggested the following changes:
tensorflow/compiler/jit/BUILD:
1c1
< load("//tensorflow:tensorflow.bzl", "if_mlir", "tf_cc_test", "cc_header_only_library")
---
> load("//tensorflow:tensorflow.bzl", "cc_header_only_library", "if_mlir", "tf_cc_test")
tensorflow/compiler/xla/BUILD:
1c1
< load("//tensorflow:tensorflow.bzl", "tf_cc_test", "cc_header_only_library")
---
> load("//tensorflow:tensorflow.bzl", "cc_header_only_library", "tf_cc_test")
Please fix manually or run buildifier <file> to auto-fix.
```

As you didn't touch C++/build rules, you can ignore that.

However, Ubuntu CPU/Linux GPU fail with Python errors on the files you touched

```
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/tpu/feature_column_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1245, in decorated
    return f(self, *args, **kwargs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/tpu/feature_column_test.runfiles/org_tensorflow/tensorflow/python/tpu/feature_column_test.py", line 156, in test_get_dense_tensor
    'aaa': sparse_input
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/tpu/feature_column_test.runfiles/org_tensorflow/tensorflow/python/tpu/feature_column.py", line 428, in _get_dense_tensor
    self, inputs, weight_collections, trainable)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/tpu/feature_column_test.runfiles/org_tensorflow/tensorflow/python/feature_column/feature_column.py", line 2516, in _get_dense_tensor
    trainable=trainable)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/tpu/feature_column_test.runfiles/org_tensorflow/tensorflow/python/feature_column/feature_column.py", line 2482, in _get_dense_tensor_internal
    scope=variable_scope.get_variable_scope())
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/tpu/feature_column_test.runfiles/org_tensorflow/tensorflow/python/tpu/feature_column.py", line 128, in _creator
    return embedding_column_layer(None, scope=scope)  # pylint: disable=not-callable
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/tpu/feature_column_test.runfiles/org_tensorflow/tensorflow/python/layers/base.py", line 547, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/tpu/feature_column_test.runfiles/org_tensorflow/tensorflow/python/keras/engine/base_layer.py", line 818, in __call__
    self._maybe_build(inputs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/tpu/feature_column_test.runfiles/org_tensorflow/tensorflow/python/keras/engine/base_layer.py", line 2119, in _maybe_build
    self.build(tuple(input_shapes))
TypeError: 'NoneType' object is not iterable
```

**Comment by bono1567** [comment]
@mihaimaruseac 
Is Docker the only way of conducting the sanity checks?

**Comment by bono1567** [comment]
@rthadur Do I need to create a new PR or will it take time for the reviewers to review the change?

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
Sorry about this. The PR slipped through the cracks.

Usually we try to respond to the PRs fast. If there's no review after fixing the previous review comments, feel free to ping reviewers.

**Comment by bono1567** [comment]
@mihaimaruseac Hi, there were a few build failures in the previous PR. I have made the changes again, please review and approve. And how can I conduct the tests (Dense Test to be precise) which are failing during the build, locally on my PC?
Thank you

**Comment by bono1567** [comment]
bot:mlx:test

**Comment by bono1567** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 28-Nov-2019

Artefact file | Status
-- | --
[build_tf.log](https://gist.githubusercontent.com/mellanox-github/844a65c4b7e3512eb43e92f39b13cd20/raw/3d9ee8ab00ca7bf985aeefebdb2117e6da189bc4/build_tf.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/844a65c4b7e3512eb43e92f39b13cd20/raw/139685e783e1a92183d626417e1fbd49b96afeb7/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_tf_cnn_benchmarks.log](https://gist.githubusercontent.com/mellanox-github/844a65c4b7e3512eb43e92f39b13cd20/raw/e5b8e501f31726509861e3e98e4f48f4ad38074e/run_tf_cnn_benchmarks.log) | :heavy_check_mark: PASS
[run_tf_models_imagenet_host1.log](https://gist.githubusercontent.com/mellanox-github/844a65c4b7e3512eb43e92f39b13cd20/raw/c57e8c7a8067d50149946d407a2338e5a81425ae/run_tf_models_imagenet_host1.log) | :question: UNKNOWN
[run_tf_models_imagenet_host2.log](https://gist.githubusercontent.com/mellanox-github/844a65c4b7e3512eb43e92f39b13cd20/raw/2eff4ac8045d09a2523a637dc4a37be5fdbb733a/run_tf_models_imagenet_host2.log) | :question: UNKNOWN
[run_tf_models_imagenet_launcher.log](https://gist.githubusercontent.com/mellanox-github/844a65c4b7e3512eb43e92f39b13cd20/raw/9af7fa08d92f402502dc0d0cd29c8b571c059069/run_tf_models_imagenet_launcher.log) | :question: UNKNOWN
[run_tf_tests.log](https://gist.githubusercontent.com/mellanox-github/844a65c4b7e3512eb43e92f39b13cd20/raw/7bd981773f1bcc0cc046b96aa3514dcf31a9df87/run_tf_tests.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by bono1567** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 28-Nov-2019

Artefact file | Status
-- | --
[build_tf.log](https://gist.githubusercontent.com/mellanox-github/33be6b2a6d6ff16e5d87f2090f1fc293/raw/83ade73bde98320014c1b9665ce95ab025b38c0e/build_tf.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by rthadur** [comment]
@bono1567 can you please check the build failures ?

**Comment by bono1567** [comment]
> @bono1567 can you please check the build failures ?

@rthadur I wanted to know how can I run these build tests prior to pushing the next change. Can I do it locally?

**Comment by rthadur** [comment]
@bono1567 please follow the steps here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/README.md

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by bono1567** [comment]
I am encountering build issues. 
I am not working on it anymore

**Pull request closed without merging**
