### PR TITLE
Fix PCRE link in get started docs

### PR DESCRIPTION
**Pull request by mpeteuil**
This is just a simple typo correction. Does this still require the [Contributor License Agreements](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#contributor-license-agreements) mentioned in the contributing guidelines?

### CODE REVIEW

**Comment by mpeteuil** [comment]
Looks like the answer is yes :smile: 

I signed it!

**Comment by vrv** [comment]
Thanks, can you update to master?

**Comment by mpeteuil** [comment]
Sure thing, it should be up to date now. Let me know if there's anything else I need to do.

**Comment by vrv** [comment]
Apparently github changed their icons for when the changes are out of date, and they chose a color that matched the indication for 'this has a merge conflict'.  Sorry for the noise.

**Comment by vrv** [comment]
Merged

**Pull request closed without merging**
