### PR TITLE
Pulic API for name_scope & convert_to_tensor

### PR DESCRIPTION
**Pull request by autoih**
Replace ops.name_scope by tf.name_scope

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by gbaned** [comment]
@I-Hong  Could you please check failed build errors? Thanks!

**Comment by I-Hong** [comment]
Thanks @gbaned. I replaced it back, but there is an import/copybara error, could you please retrigger the test?

**Comment by mihaimaruseac** [comment]
I think this should get a review from the API owners if it is replacing public API

**Comment by alextp** [comment]
This does not work. You cannot `import tensorflow as tf` from a python file inside tensorflow itself.

**Comment by I-Hong** [comment]
> This does not work. You cannot `import tensorflow as tf` from a python file inside tensorflow itself.

Thanks @alextp, I got it.

**Pull request closed without merging**
