### PR TITLE
Register half in some ops which support all floating point types

### PR DESCRIPTION
**Pull request by DavidNorman**
Add 'half' to the acceptable data types for the depthwise convolution gradients, and some pooling ops.

I've just added 'half', although it seems that these ops should be able to operate on any real value.  in general there isn't a lot of consistency in the op constraints...

Conv2D doesn't accept double, but DepthwiseConv2D does. BiadAdd works on any numbertype, but would typically follow a Convolution. Conv3D supports bfloat16, but its back prop versions do not.

Perhaps there is a bigger job to be done in the future, to replace all of the explicit types with classes of types (real, int, etc).

### CODE REVIEW

**Comment by DavidNorman** [comment]
hi - all checks passed - wonder if we could consider this for merging?

**Review by hawkinsp — APPROVED** [review]
Sorry, this PR got lost in my inbox. Looks fine.

**Comment by DavidNorman** [comment]
thanks :)

**Comment by DavidNorman** [comment]
hi - could we get this merged before merge conflicts cause a problem?  cheers.

**Pull request merged**
