### PR TITLE
[oneDNN] Dynamic generate oneDNN version

### PR DESCRIPTION
**Pull request by Zantares**
Added a python script to get oneDNN version from cmake and dynamic set it to bazel, instead of changing the oneDNN version manually.

### CODE REVIEW

**Comment by Zantares** [comment]
This PR is built based on an old commit and got failure in the newest master, I will check and address it.

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @Zantares Can you please rebase your branch and resolve conflicts? Thank you!

**Review by cantonios — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @Zantares Can you please rebase your branch and resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @Zantares Can you please rebase your branch and resolve conflicts? Thank you!

**Comment by Zantares** [comment]
It seems this method only works on bare metal and failed in docker. I will have a check.

**Comment by gbaned** [comment]
Hi @Zantares Can you please rebase your branch and resolve conflicts? Thank you!

**Comment by Zantares** [comment]
I'm sorry for that I didn't get time to debug the docker issue. I plan to close this PR first and resubmit it in the future once the docker issue is solved, thanks!

**Pull request closed without merging**
