### PR TITLE
Terminology changes in bazel scripts

### PR DESCRIPTION
**Pull request by whchung**
Quite a few functions in TF bazel scripts can be used on both CUDA and ROCm
platform. In this commit rename them to more generic term:

- tf_cuda_* -> tf_gpu_*
- cuda_py_* -> gpu_py_*

### CODE REVIEW

**Comment by rmlarsen** [comment]
@yifei, @gunan I think this requires some copybara changes as well?

**Comment by yifeif** [comment]
Thanks @whchung and @rmlarsen. Agree that the naming is confusing now. We also have a bunch of internal targets of those two types as well though. WDYT is the best thing we should do here @gunan?

**Comment by gunan** [comment]
I do not think this is as straightforward as just renaming. There are some non-opensource google projects which started using these. As soon as this gets submitted, hundreds of internal targets will be broken.
I think this either needs to be done internally, or we need separate targets for rocm and cuda.
It may be tied to the discussion in #20277, so I would like @jlebar to weigh in here as well.

**Comment by jlebar** [comment]
What I did last time I had a renaming change that also affected internal targets was, do the review externally, approve it, import it, and then continue the renaming internally before committing the change.

So it should be *possible*.  That's separate from the question of whether it's desirable.

@Artem-B might have more concrete thoughts.  To me it seems like you may want a level of indirection between how you spell things in BUILD files and the actual BUILD targets.  Just like we have `xla_test(foo)` which expands into foo_gpu and foo_cpu (and you could imagine changing this so it expands into `:foo_nvgpu`, `:foo_amdgpu`, `:foo_cpu`), maybe you want tf_gpu_lib that expands into cuda and rocm variants.  Then if you have a `tf_rocm` mega-library, it can glob together all of the rocm build targets (you can glob based on build tags, not just on name).

So in that sense this CL sort of seems to me like it's going in the right direction.  But again I'd want to know what @Artem-B thinks.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by parallelo** [comment]
Hi @rmlarsen - Just wanted to re-engage on this PR and to discuss the next steps we should take.  In summary, it sounds like there's support for the PR, but there are some non-open source projects that may be affected.  

Any thoughts on @jlebar's previously used approach?  
> do the review externally, approve it, import it, and then continue the renaming internally before committing the change

**Comment by parallelo** [comment]
Hi @thirupalanisamy - Just wanted to check if there are any updates from your side regarding @gunan's comment last week.  Let us know if there's anything we can do to help move this forward.

**Comment by thirupalanisamy** [comment]
Thanks fro the ping.

Update: We are started an internal discussion re the scope of work, will
keep you posted.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by parallelo** [comment]
Just wanted to ping this PR with an acknowledgement.  We'll be working on this PR with Gunan's offline suggestions: 
- rename from tf_cuda* to tf_gpu*
- tf_cuda* must remain operational
- create new tf_cuda* rules that simply call tf_gpu* rules

**Comment by rmlarsen** [comment]
@whchung can we close this PR?

**Comment by parallelo** [comment]
The plan is to simplify this PR with the details provided above.

**Comment by rmlarsen** [comment]
@parallelo OK, I see.
@whchung can you rebase this PR, if you intend to continue working on it?a

**Comment by parallelo** [comment]
FYI - To simplify the process, I just created a replacement PR.  (#22747)

**Pull request closed without merging**
