### PR TITLE
Add float16 support for tf.sparse.softmax

### LINKED ISSUE #53657: tf.sparse.softmax lack support for float16
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
logits = tf.random.uniform([16, 1, 10], dtype=tf.float16)
r1 = tf.nn.softmax(logits,axis=-1) # pass
logits_sp = tf.sparse.from_dense(logits)
r2 = tf.sparse.softmax(logits_sp) # InvalidArgumentError
```

**Describe the current behavior**
`tf.sparse.softmax` cannot accept a tensor of type `float16`. However, `tf.nn.softmax` do support `half`. 
For the above code snippet, the error message is:
```
InvalidArgumentError: Value for attr 'T' of half is not in the list of allowed values: float, double
	; NodeDef: {{node SparseSoftmax}}; Op<name=SparseSoftmax; signature=sp_indices:int64, sp_values:T, sp_shape:int64 -> output:T; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE]> [Op:SparseSoftmax]
```

**Describe the expected behavior**
According to the document for `tf.sparse.softmax`, it is equivalent to `tf.nn.softmax` (but for sparse tensors), so `tf.sparse.softmax` should also support `float16` inputs.

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to address the issue raised in #53657 where float16 was not supported for tf.sparse.softmax, while the counterpart of tf.nn.softmax has the float16 support.
This PR adds float16 support.

This PR fixes #53657.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by cantonios** [comment]
Looks like the error bounds are too tight for float16 in XLA:
```
Traceback (most recent call last):
  File "/build/work/e39599bf06332784ad310db57a9e48f4b607/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", [line 1623](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/python/framework/test_util.py?l=1623&ws=tap-prod-presubmit/189138231&snapshot=2), in decorated
    return f(self, *args, **kwargs)
  File "/build/work/e39599bf06332784ad310db57a9e48f4b607/google3/runfiles/google3/third_party/tensorflow/python/kernel_tests/sparse_ops/sparse_ops_test.py", [line 1003](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/python/kernel_tests/sparse_ops/sparse_ops_test.py?l=1003&ws=tap-prod-presubmit/189138231&snapshot=2), in testEquivalentToDensified
    self.assertAllClose(dense_result, sp_result)
  File "/build/work/e39599bf06332784ad310db57a9e48f4b607/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", [line 1532](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/python/framework/test_util.py?l=1532&ws=tap-prod-presubmit/189138231&snapshot=2), in decorated
    return f(*args, **kwds)
  File "/build/work/e39599bf06332784ad310db57a9e48f4b607/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", [line 3105](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/python/framework/test_util.py?l=3105&ws=tap-prod-presubmit/189138231&snapshot=2), in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/build/work/e39599bf06332784ad310db57a9e48f4b607/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", [line 3061](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/python/framework/test_util.py?l=3061&ws=tap-prod-presubmit/189138231&snapshot=2), in _assertAllCloseRecursive
    self._assertArrayLikeAllClose(
  File "/build/work/e39599bf06332784ad310db57a9e48f4b607/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", [line 2998](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/python/framework/test_util.py?l=2998&ws=tap-prod-presubmit/189138231&snapshot=2), in _assertArrayLikeAllClose
    np.testing.assert_allclose(
  File "/build/work/e39599bf06332784ad310db57a9e48f4b607/google3/runfiles/google3/third_party/py/numpy/testing/_private/utils.py", [line 1530](https://cs.corp.google.com/piper///depot/google3/third_party/py/numpy/testing/_private/utils.py?l=1530&ws=tap-prod-presubmit/189138231&snapshot=2), in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/build/work/e39599bf06332784ad310db57a9e48f4b607/google3/runfiles/google3/third_party/py/numpy/testing/_private/utils.py", [line 844](https://cs.corp.google.com/piper///depot/google3/third_party/py/numpy/testing/_private/utils.py?l=844&ws=tap-prod-presubmit/189138231&snapshot=2), in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=1e-06
Mismatched value: a is different from b. 
not close where = (array([1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 4, 5]), array([ 0,  1,  5,  6,  7,  8, 10, 11,  0,  2,  3,  5,  6,  7,  8, 10, 11,
        0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11,  7, 10]))
not close lhs = [0.05228 0.0559  0.1272  0.0774  0.05246 0.128   0.0913  0.10187 0.0594
 0.0709  0.05728 0.06168 0.1255  0.07355 0.0956  0.0641  0.0946  0.0946
 0.089   0.09796 0.05252 0.084   0.05176 0.1101  0.0649  0.06003 0.0861
 0.131   0.1083  0.1186 ]
not close rhs = [0.05225 0.05588 0.1271  0.07733 0.05243 0.1279  0.09125 0.1018  0.05936
 0.07086 0.05725 0.06165 0.1254  0.0735  0.0955  0.064   0.09454 0.09467
 0.08905 0.098   0.05255 0.08405 0.0518  0.11017 0.06494 0.0601  0.0862
 0.1311  0.10834 0.1185 ]
not close dif = [3.052e-05 3.052e-05 1.221e-04 6.104e-05 3.052e-05 1.221e-04 6.104e-05
 6.104e-05 3.052e-05 6.104e-05 3.052e-05 3.052e-05 1.221e-04 6.104e-05
 6.104e-05 6.104e-05 6.104e-05 6.104e-05 6.104e-05 6.104e-05 3.052e-05
 6.104e-05 3.052e-05 6.104e-05 6.104e-05 6.104e-05 6.104e-05 1.221e-04
 6.104e-05 6.104e-05]
not close tol = [1.07e-06 1.07e-06 1.13e-06 1.07e-06 1.07e-06 1.13e-06 1.13e-06 1.13e-06
 1.07e-06 1.07e-06 1.07e-06 1.07e-06 1.13e-06 1.07e-06 1.13e-06 1.07e-06
 1.13e-06 1.13e-06 1.13e-06 1.13e-06 1.07e-06 1.07e-06 1.07e-06 1.13e-06
 1.07e-06 1.07e-06 1.07e-06 1.13e-06 1.13e-06 1.13e-06]
dtype = float16, shape = (6, 12)
Mismatched elements: 30 / 72 (41.7%)
Max absolute difference: 0.0001221
Max relative difference: 0.001016
 x: array([[0.0741 , 0.06683, 0.11426, 0.0867 , 0.05603, 0.086  , 0.1095 ,
        0.064  , 0.1203 , 0.06015, 0.0952 , 0.0666 ],
       [0.05228, 0.0559 , 0.07654, 0.0924 , 0.0734 , 0.1272 , 0.0774 ,...
 y: array([[0.0741 , 0.06683, 0.11426, 0.0867 , 0.05603, 0.086  , 0.1095 ,
        0.064  , 0.1203 , 0.06015, 0.0952 , 0.0666 ],
       [0.05225, 0.05588, 0.07654, 0.0924 , 0.0734 , 0.1271 , 0.07733,...
```
I'm not sure how far off the non-XLA implementation is.  You can try modifying the test to use `assertAllCloseAccordingToType(...)`.  Otherwise, we may need to dig into the XLA implementation.

**Comment by gbaned** [comment]
@yongtang Can you please check @cantonios's comments and keep us posted ? Thank you!

**Comment by gbaned** [comment]
@yongtang Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
@yongtang Any update on this PR? Please. Thank you!

**Comment by yongtang** [comment]
@mihaimaruseac  @cantonios @gbaned  Thanks a lot for the help and I am really sorry for the late reply. I have rebased the PR and used assertAllCloseAccordingToType now. Can you take a look and see if the issue will be resolved?

**Review by cantonios — APPROVED** [review]

**Pull request merged**
