### PR TITLE
Use asarray to avoid copy - ~2x speedup for feed_dict

### PR DESCRIPTION
**Pull request by nanddalal**
This starts to address #2919

### CODE REVIEW

**Comment by ebrevdo** [comment]
Jenkins, test this please.

**Comment by ebrevdo** [comment]
@nanddalal can you sign the CLA?

**Comment by nanddalal** [comment]
Hi, sorry for the delay - I am still working on signing the CLA so I can contribute later on, but if you were already able to incorporate this change in a different PR, that would be great.

**Comment by mrry** [comment]
It turns out I fixed this independently in another commit (which is will appear in the next push from internal) - thanks for noticing the issue though!

**Pull request closed without merging**
