### PR TITLE
 change validation_metrics to MetricSpec

### PR DESCRIPTION
**Pull request by BoyuanJiang**
tensorflow:Please specify metrics using MetricSpec. Using bare functions or (key, fn) tuples is deprecated and support for it will be removed on Oct 1, 2016.
so run the previous code will get a mistake!

### CODE REVIEW

**Review by ispirmustafa — APPROVED** [review]
Thanks

**Comment by BoyuanJiang** [comment]
@ispirmustafa  @tensorflow-jenkins  hey,it's my first time to use github PR,so what should I do next to complete those six checks bellow and merge the changes?

**Comment by terrytangyuan** [comment]
@BoyuanJiang When tests pass it's good to merge. @tensorflow-jenkins Test this please

**Comment by BoyuanJiang** [comment]
I test the changes on my local machine using Python3.5 correctly,so I'm not sure why it failed in Linux CPU Tests (Python 3)  T_T

**Comment by ilblackdragon** [comment]
@BoyuanJiang it seems like it's failed independently of your change.
Let's retest and merge.
@tensorflow-jenkins Test this please

**Comment by danmane** [comment]
Pretty confident the failure is unrelated (looks like a platform-specific timing issue). Merging, thanks!

**Pull request merged**
