### PR TITLE
[wip] 4d image ops

### PR DESCRIPTION
**Pull request by ppries**
Continuation of #3566 - I decided to change to master branch, since I needed some stuff that wasn't in r0.9.

I've extended hue, saturation, and the flip ops now. Comments or suggestions are welcome.

I'll continue working on the other ops here and there, when I have the time, and after that I'll write some tests.

The latest commit might look a bit strange, because of a merge with the latest upstream master.

### CODE REVIEW

**Comment by danmane** [comment]
@ppries I think we should hold off on review until you add the tests, does that seem reasonable to you?

**Comment by ppries** [comment]
Yes, of course. I'll slowly chip away at it as I have time.

**Comment by martinwicke** [comment]
@ppries Let us know when you're ready for a review.

**Comment by drpngx** [comment]
Closing due to inactivity. Let us know when it's ready.

**Pull request closed without merging**
