### PR TITLE
shrink pip package content

### PR DESCRIPTION
**Pull request by jendap**
@martinwicke @caisq we need this and the questions is if we want to keep the "external" there.

### CODE REVIEW

**Comment by jendap** [comment]
The external contains a lot of things - all the javascript files for tensorboard (we probably want those), but also all the eigen header files (we don't need those), and perhaps many other things. I'm going to look at those directories and probably remove a few of them now. But that's hacky, not long term solution.

**Comment by jendap** [comment]
It is updated to remove the eigen headers. All javascript stay.

**Comment by martinwicke** [comment]
@benoitsteiner @danmane This is in, but I'd like your opinions on what can/should stay and what can be removed.

**Comment by danmane** [comment]
We can absolutely shrink the pip package further. Right now we don't minify TensorBoard's HTML and JS, and I'm not sure whether we are taking the minified js or full js (or both) into the pip package. So there are some very low hanging fruit here.

**Pull request merged**
