### PR TITLE
Add error message fix in qr grad and test coverage

### PR DESCRIPTION
**Pull request by D-Roberts**
Add a fix for the bug in the error message in the qr grad check for matrix shapes. Add a test for it.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Is there a bug report? Or an example where the error is wrong? Can we add a test so that future change reversing the order in the comparison gets blocked if wrong?

**Comment by D-Roberts** [comment]
@mihaimaruseac So the check works correctly, all the test cases are covered correctly - the only thing wrong is the text of the message: it should say 'nrows > ncols' vs 'ncols > nrows' . (My bad, I wrote the initial code).

Note the correct test cases in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/qr_op_test.py

**Comment by D-Roberts** [comment]
Eg where the incorrect message would show up:
```
import numpy as np
import tensorflow as tf
np.random.seed(42)

# nrows > ncols
nrows, ncols = 3, 2
a = np.random.uniform(-1, 1, (3, 2)).astype(np.float32)
atf = tf.convert_to_tensor(a)

with tf.GradientTape() as g:
  g.watch(atf)
  ret = tf.linalg.qr(atf, True) # full_matrices=True

g.gradient(ret, atf)
```
with output:
```
Traceback (most recent call last):
  File "/Users/denisaroberts/Desktop/eg.py", line 12, in <module>
    g.gradient(ret, atf)
  File "/Users/denisaroberts/tf/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 1083, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/Users/denisaroberts/tf/lib/python3.7/site-packages/tensorflow/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/Users/denisaroberts/tf/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 162, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/Users/denisaroberts/tf/lib/python3.7/site-packages/tensorflow/python/ops/linalg_grad.py", line 498, in _QrGrad
    raise NotImplementedError("QrGrad not implemented when ncols > nrows "
NotImplementedError: QrGrad not implemented when ncols > nrows and full_matrices is true.
```

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
If it is possible to transform this example into a test that would be great.

Thank you for the PR and the context

**Comment by D-Roberts** [comment]
@mihaimaruseac Will do. To be crystal clear - you mean a test that asserts that the correct message for the check is issued when "nrows > ncols and full_matrices=True" ?

**Comment by mihaimaruseac** [comment]
Yes, a test that checks that the error message contains `not implemented when ncols > nrows and full_matrices is true`

**Comment by D-Roberts** [comment]
@mihaimaruseac Added test.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
