### PR TITLE
add LU operation and return factorized matrices, related to issue #6992

### PR DESCRIPTION
**Pull request by zhuangh**
related to #6992 and
reopen for pull request https://github.com/tensorflow/tensorflow/pull/16185

### CODE REVIEW

**Comment by zhuangh** [comment]
The differences between this pull request and previous https://github.com/tensorflow/tensorflow/pull/16185
- change FullPivLU to PartialPivLU
- change full matrix of permutation to an index array.
- use tf.gather instead of p^-1 lu
- Ops derived from OpKernel, instead of LinearAlgebraOp

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rmlarsen** [comment]
An LU op was contributed by Google, and should be available on github. Thanks for working on this.

**Pull request closed without merging**
