### PR TITLE
Building TensorFlow Lite - macos_arm64 support using cmake

### PR DESCRIPTION
**Pull request by simonmaurer**
with respect to this [issue](https://github.com/google/XNNPACK/issues/1302) in the XNNPACK repository:  `bazel` builds for macos_arm64 platform are not yet supported.
however building with cmake works successfully.

this change allows to build the `TensorFlow Lite library` and the `benchmark_model` on a macos_arm64 host platform when using `-DTFLITE_ENABLE_XNNPACK=ON` (default). see [instructions](https://www.tensorflow.org/lite/guide/build_cmake).

### CODE REVIEW

**Comment by abattery** [comment]
@terryheo could you review this PR?

**Comment by simonmaurer** [comment]
@googlebot I signed it!

**Comment by simonmaurer** [comment]
oneDNN unit test failed?

**Comment by simonmaurer** [comment]
once this [PR](https://github.com/google/XNNPACK/pull/1327) is accepted in XNNPACK repo, we can then also proceed with a new PR so `TensorFlow Lite`and `benchmark_model`can be built using:

> bazel build -c opt --config=macos_arm64 //tensorflow/lite/tools/benchmark:benchmark_model

**Review by terryheo — APPROVED** [review]
Thanks for your contribution.

LGTM

**Comment by terryheo** [comment]
Oh, are you going to send another PR when https://github.com/google/XNNPACK/pull/1327 is merged?
Otherwise, it might be better to wait?

**Comment by simonmaurer** [comment]
> Oh, are you going to send another PR when [google/XNNPACK#1327](https://github.com/google/XNNPACK/pull/1327) is merged?
> Otherwise, it might be better to wait?

thank you. mainly this PR was for updating the cmake build files for `macos_arm64`, but you're right.. it might indeed be better to wait for the `XNNPACK` PR to be accepted. so we can pull in all changes at once. if you're ok with the PR naming I will wait and add the remaining commits of `XNNPACK` and `pthreadpool` too here. would be nice if you could review again to be safe.
there also needs to be a change for cpuinfo. did some testing and pulled the latest master branch in , but the [cpuinfo.patch](https://github.com/tensorflow/tensorflow/blob/master/third_party/cpuinfo/cpuinfo.patch) is not compatible so I deactivated applying this patch [WORKSPACE](https://github.com/tensorflow/tensorflow/blob/master/third_party/cpuinfo/WORKSPACE) in for verification. this went fine for `macos_arm64` and host builds on `macos_x86-64` but I'm not sure if this is the right way to go.
what do you think?

**Comment by terryheo** [comment]
I see. It might take time to wait for all the XNNPack related changes are merged.
I'm fine with having the second PR so we have can more time to verify all XNNPack related patches.

**Comment by terryheo** [comment]
This PR is merged and the [XNNPack PR](https://github.com/google/XNNPACK/pull/1327) got LGTM.

@simonmaurer I have one question. Does the "--config=macos_arm64" option only works on M1 machine?
I can't use it on my Ubuntu desktop and x86 Mac machine.

**Comment by simonmaurer** [comment]
@terryheo thanks. if you're talking about the TensorFlow repo: this accepted PR here only allows the host build for `macos_arm64` using cmake as described [here](https://www.tensorflow.org/lite/guide/build_cmake).
I'll make the additional PR here to pull in the latest `pthreadpool` (PR accepted & merged), `XNNPACK` (PR accepted) and `cpuinfo` once they are both merged.

however if you're talking about the XNNPACK repo (the PR is indeed accepted, but not yet merged):

> bazel build --config=macos_arm64 -c opt :end2end_bench

will work on a host M1 machine. on different platforms (like Linux or even macos x86-64) that does not work yet because of missing toolchains

**Comment by simonmaurer** [comment]
@terryheo another note:
ideally we would want bazel to work on M1 host machine like this:

M1 host machine compilation (without specifying the platform):
> bazel build -c opt :end2end_bench (XNNPACK)
> bazel build -c opt //tensorflow/lite/tools/benchmark:benchmark_model (TF)

Cross compilation on a different platform (e.g. Linux x86):
> bazel build -c opt --config=macos_arm64 :end2end_bench (XNNPACK)
> bazel build -c opt --config=macos_arm64 //tensorflow/lite/tools/benchmark:benchmark_model (TF)

**Comment by simonmaurer** [comment]
> the `pip_package` should work already according to this [PR](https://github.com/tensorflow/tensorflow/commit/bab0d14036efd0adcd4e48303d045cee3c342cb0), which builds fine on a M1 host but I got errors about missing symbols when importing the tensorflow package in python3

with this [PR](https://github.com/tensorflow/tensorflow/pull/47594) the pip package can be built using a native build on M1 host machine

**Comment by simonmaurer** [comment]
@terryheo also thanks for reviewing [#47639](https://github.com/tensorflow/tensorflow/pull/47639).  this includes the changes on the follow-up PR we discussed:
> once this [PR](https://github.com/google/XNNPACK/pull/1327) is accepted in [XNNPACK](https://github.com/google/XNNPACK) repo, we can then also proceed with a new PR so `TensorFlow Lite`and `benchmark_model`can be built for `macos_arm64`using:
> 
> > bazel build --config=macos_arm64 -c opt //tensorflow/lite:libtensorflowlite.so
> > bazel build --config=macos_arm64 -c opt //tensorflow/lite/tools/benchmark:benchmark_model

that being said, with [#47639](https://github.com/tensorflow/tensorflow/pull/47639) we can now also build using bazel for `macos_arm64` platform:

**Cross compilation** on a M1 host or a different platform (e.g. Linux x86):
> bazel build -c opt --config=macos_arm64 //tensorflow/lite:libtensorflowlite.so
> bazel build -c opt --config=macos_arm64 //tensorflow/lite/tools/benchmark:benchmark_model

and due to the additional changes by @freedomtan when using a more recent version of bazel ([bazel #4928295](https://github.com/bazelbuild/bazel/commit/4928295b236ec8f590a7e9d863502bc2f50a77d9))

**M1 host machine compilation** (without specifying the platform):
> bazel build -c opt //tensorflow/lite:libtensorflowlite.so
> bazel build -c opt //tensorflow/lite/tools/benchmark:benchmark_model

**Pull request merged**
