### PR TITLE
Remove llvm unavailable mirror in Bazel

### PR DESCRIPTION
**Pull request by bhack**

### CODE REVIEW

**Comment by bhack** [comment]
Ok It seems that the mirror is mandatory. Probably the mirror has just lags.

**Comment by mihaimaruseac** [comment]
Yes, the mirror is lagging recently. I'm trying to debug why Bazel stops pulling instead of trying the upstream.

**Comment by bhack** [comment]
> Yes, the mirror is lagging recently. I'm trying to debug why Bazel stops pulling instead of trying the upstream.

Cause:
https://github.com/tensorflow/tensorflow/blob/b9387225565226e5c8a497fc8b5e28ac832529c1/third_party/repo.bzl#L76-L84

**Comment by bhack** [comment]
I meant this was for the mandatory of the tensorflow mirror for llvm cause it is not in the `SINGLE_URL_WHITELIST`

**Pull request closed without merging**
