### PR TITLE
Add handling of TensorRT's new enumeration value `nvinfer1::DataType::kFP8`

### PR DESCRIPTION
**Pull request by linuxmetel**
`nvinfer1::DataType::kFP8` added between 8.5.3 and 8.6.0 of TensorRT. (API Reference: [8.5.3](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-853/api/c_api/namespacenvinfer1.html#a83aed11a1c160f30dcd13809678bdd29), [8.6.0](
https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-860-ea/api/c_api/namespacenvinfer1.html#a83aed11a1c160f30dcd13809678bdd29)) And compiling will be failed with TensorRT 8.6.0 because of this change like #60031.

It happens because the new enumeration value hasn't be handled in some switch blocks yet. I added some cases for `kFP8` in switch block of `nvinfer1::DataType` if the switch block has the all of or almost all of cases of the `nvinfer1::Dat
aType`'s enumerate types.

I think this change doesn't have problem, but I can't compile it because of another problem (which maybe is the same as https://github.com/tensorflow/tensorflow/issues/58881). So I made it a Draft PR for now.

<details>

  <summary>Click to expand!</summary>

```
ERROR: /home/linuxmetel/tensorflow/tensorflow/BUILD:1263:21: Linking tensorflow/libtensorflow_cc.so.2.13.0 failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-opt/bin/tensorflow/libtensorflow_cc.so.2.13.0-2.params
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/libkernels.pic.lo(sparse_mat_mul_op.pic.o): in function `tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, float>::Compute(tensorflow::OpKernelContext*)':
sparse_mat_mul_op.cc:(.text._ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEfE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEfE7ComputeEPNS_15OpKernelContextE]+0x473): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, float>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: sparse_mat_mul_op.cc:(.text._ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEfE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEfE7ComputeEPNS_15OpKernelContextE]+0x501): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, float>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/libkernels.pic.lo(sparse_mat_mul_op.pic.o): in function `tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, double>::Compute(tensorflow::OpKernelContext*)':
sparse_mat_mul_op.cc:(.text._ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEdE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEdE7ComputeEPNS_15OpKernelContextE]+0x473): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, double>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: sparse_mat_mul_op.cc:(.text._ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEdE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEdE7ComputeEPNS_15OpKernelContextE]+0x501): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, double>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/libkernels.pic.lo(sparse_mat_mul_op.pic.o): in function `tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, std::complex<float> >::Compute(tensorflow::OpKernelContext*)':
sparse_mat_mul_op.cc:(.text._ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceESt7complexIfEE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceESt7complexIfEE7ComputeEPNS_15OpKernelContextE]+0x473): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<float> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: sparse_mat_mul_op.cc:(.text._ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceESt7complexIfEE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceESt7complexIfEE7ComputeEPNS_15OpKernelContextE]+0x501): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<float> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/libkernels.pic.lo(sparse_mat_mul_op.pic.o): in function `tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, std::complex<double> >::Compute(tensorflow::OpKernelContext*)':
sparse_mat_mul_op.cc:(.text._ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceESt7complexIdEE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceESt7complexIdEE7ComputeEPNS_15OpKernelContextE]+0x473): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<double> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: sparse_mat_mul_op.cc:(.text._ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceESt7complexIdEE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceESt7complexIdEE7ComputeEPNS_15OpKernelContextE]+0x501): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<double> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/libkernels.pic.lo(mat_mul_op.pic.o): in function `tensorflow::CSRMatMulGPUOp<std::complex<double> >::Compute(tensorflow::OpKernelContext*)':
mat_mul_op.cc:(.text._ZN10tensorflow14CSRMatMulGPUOpISt7complexIdEE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow14CSRMatMulGPUOpISt7complexIdEE7ComputeEPNS_15OpKernelContextE]+0x3ce): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<double> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/libkernels.pic.lo(mat_mul_op.pic.o): in function `tensorflow::CSRMatMulGPUOp<std::complex<float> >::Compute(tensorflow::OpKernelContext*)':
mat_mul_op.cc:(.text._ZN10tensorflow14CSRMatMulGPUOpISt7complexIfEE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow14CSRMatMulGPUOpISt7complexIfEE7ComputeEPNS_15OpKernelContextE]+0x3ce): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<float> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/libkernels.pic.lo(mat_mul_op.pic.o): in function `tensorflow::CSRMatMulGPUOp<double>::Compute(tensorflow::OpKernelContext*)':
mat_mul_op.cc:(.text._ZN10tensorflow14CSRMatMulGPUOpIdE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow14CSRMatMulGPUOpIdE7ComputeEPNS_15OpKernelContextE]+0x3cd): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, double>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/libkernels.pic.lo(mat_mul_op.pic.o): in function `tensorflow::CSRMatMulGPUOp<float>::Compute(tensorflow::OpKernelContext*)':
mat_mul_op.cc:(.text._ZN10tensorflow14CSRMatMulGPUOpIfE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow14CSRMatMulGPUOpIfE7ComputeEPNS_15OpKernelContextE]+0x3ce): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, float>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 698.990s, Critical Path: 312.83s
INFO: 1626 processes: 98 internal, 1528 local.
FAILED: Build did NOT complete successfully
```

</details>

I read the guideline, but I don't think unit tests should be added because it's not a change which adds features or fixes bug. And I signed CLA but maybe it hasn't be approved yet. If submitting PR before it's approval is not good, I'll ap
ologize for that.

For your information:

The list of the functions which have the switch blocks of `nvinfer1::DataType` that I added that case in:

- `std::ostream& operator<<()` in tensorflow/compiler/tf2tensorrt/common/utils.cc
- `size_t TRT_ShapedWeights::size_bytes()` in tensorflow/compiler/tf2tensorrt/convert/weights.cc
- `Status SetupBindings()` in tensorflow/compiler/tf2tensorrt/utils/trt_engine_utils.cc
- `string DebugString()` in tensorflow/compiler/tf2tensorrt/convert/utils.cc
- `Status TrtTypeToTfType()` in tensorflow/compiler/tf2tensorrt/convert/utils.cc (I don't know why it doesn't have `kINT8`'s case)

The list of the functions which have the switch blocks of `nvinfer1::DataType` that I didn't add that case in:

- `Status SetValues()` in tensorflow/compiler/tf2tensorrt/convert/weights.h
- `Status Validate()` in tensorflow/compiler/tf2tensorrt/convert/ops/fill_ops.cc
- `void ReorderCKtoKC()`, `void ReorderRSCKToKCRS()`, `void ReorderDRSCKToKCDRS()` and `void ReorderDRSCKToKCDRS()` in tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc

I'm sorry for my bad English.

### CODE REVIEW

**Comment by pjannaty** [comment]
@DEKHTIARJonathan

**Review by nluehr — APPROVED** [review]
LGTM. Note that this will likely conflict with the previously merged https://github.com/tensorflow/tensorflow/pull/60143.

**Comment by linuxmetel** [comment]
Thank you.

I merged master branch few minutes ago. There hasn't be any conflict yet.

**Comment by nluehr** [comment]
There is a silent conflict in the latest merge commit. [These lines](https://github.com/tensorflow/tensorflow/blob/10cbe6ef7ad60cdeef873e6a99be86b0ad80693c/tensorflow/compiler/tf2tensorrt/common/utils.cc#L216-L220) are repeated [here](https://github.com/tensorflow/tensorflow/blob/10cbe6ef7ad60cdeef873e6a99be86b0ad80693c/tensorflow/compiler/tf2tensorrt/common/utils.cc#L235-L239).

**Comment by linuxmetel** [comment]
OK, I fixed.

**Review by nluehr — APPROVED** [review]

**Pull request merged**
