### PR TITLE
Switch cmsis-nn and ethos-u to using OPTIMIZED_KERNEL_DIR.

### PR DESCRIPTION
**Pull request by advaitjain**
This change started as a switch cmsis-nn and ethos-u to using OPTIMIZED_KERNEL_DIR. However, supporting both OPTIMIZED_KERNEL_DIR=cmsis-nn and TAGS=cmsis-nn required a lot of workarounds.

As a result, it was decided to also remove the deprecated TAGS functionality.

This change also adds a new CO_PROCESSOR command line parameter to the TFLM makefile.

Specifying `CO_PROCESSOR=<c>` and `OPTIMIZED_KERNEL_DIR=<o>` will result in the following:
 * `tools/make/ext_libs/<o>.inc` and `tools/make/ext_libs/<c>.inc` will be included from the Makefile
 * kernel sources will be specialized from both `kernels/<o>.inc` and `kernels/<c>.inc` (in that order).
 * the specialization order is important because it means that if the same kernel in implemented in both optimized_kernel_dir and the co_processor, then the co_processor implementation will be used.

Tested the following commands locally:

Build for cortex-m55 + reference kernels + ethos-u kernel:
```
make -f tensorflow/lite/micro/tools/make/Makefile -j8 TARGET=cortex_m_generic TARGET_ARCH=cortex-m55 CO_PROCESSOR=ethos-u microlite
```

Build for cortex-m55 + cmsis-nn kernels (as available) + ethos-u kernel:
```
make -f tensorflow/lite/micro/tools/make/Makefile -j8 TARGET=cortex_m_generic TARGET_ARCH=cortex-m55 OPTIMIZED_KERNEL_DIR=cmsis-nn CO_PROCESSOR=ethos-u microlite
```

See the discussion on https://github.com/tensorflow/tensorflow/pull/46352 for some more context.

### CODE REVIEW

**Review by mansnils — APPROVED** [review]

**Review by njeffrie — APPROVED** [review]

**Comment by advaitjain** [comment]
@mansnils @njeffrie: I wasn't planning on merging this PR yet but because it had all the approvals it did get merged.

We can roll back or fix forward as needed.

I will make a PR that changes the directory names to underscores first thing tomorrow.

And I certainly wanted to chat with @njeffrie about my last change where I decided that removing support for TAGS was the way to go.

Note that I rebased and amended do that there was only a single commit from this PR to make it easier for anyone to locally roll back if needed since I am breaking backwards compatibility.

**Comment by mansnils** [comment]
@advaitjain Ok, let's get the last PR merged tomorrow.

**Comment by advaitjain** [comment]
rename complete with https://github.com/tensorflow/tensorflow/pull/46584

**Comment by advaitjain** [comment]
> This change started as a switch cmsis-nn and ethos-u to using OPTIMIZED_KERNEL_DIR. However, supporting both OPTIMIZED_KERNEL_DIR=cmsis-nn and TAGS=cmsis-nn required a lot of workarounds.
> 
> As a result, it was decided to also remove the deprecated TAGS functionality.
> 

@dzakhar @JaccovG: With this PR we are no longer supporting the use of TAGS as part of the top-level TFLM Makefile. The optimized kernel implementation can be selected with OPTIMIZED_KERNEL_DIR=<your dir> and for anything else the specific target / optimized kernel makefile can add additional command line options.

The diff for the Makefile in this PR will give you some more info on what has changed: https://github.com/tensorflow/tensorflow/pull/46473/files?file-filters%5B%5D=No+extension#diff-84c8d7e242143d674d6e26ab56443970ed8e1f3db0fcb1d0e8e127eaebbe1a1a

I'd be happy to help you figure out a path forward to getting the ARC platform support up and running.

**Pull request merged**
