### PR TITLE
Fix the issue #32041: Fix riscv32_mcu link failure in build period.

### PR DESCRIPTION
**Pull request by zhoupeng**
Fix the issue https://github.com/tensorflow/tensorflow/issues/32041/

1) tflite:riscv:Fix riscv32_mcu build failed with undefined references 
    Fix the ld error: undefined references to __wrap_puts for build commands like `make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=riscv32_mcu hello_world_bin` 
    The Makefile variables XXX_TEST_SRCS/XXX_SRCS in targets/mcu_riscv_makefile.inc are overridden by the the examples's respective makefile.inc (eg. hello_world/Makefile.inc), which leads to the architecture specified __wrap__funs are not included correctly.
2) tflite:riscv:Fix hidden symbol `__dso_handle' isn't defined.    
    For arduino sketch in of riscv_mcu examples, this patch fix this bug by declare the following global variable    `void* __dso_handle;`
3) how to test:
`make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=riscv32_mcu hello_world_test_bin`

`make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=riscv32_mcu hello_world_bin`

### CODE REVIEW

**Review by nkreeger — CHANGES_REQUESTED** [review]
Hi @zhoupeng - is this related to https://github.com/tensorflow/tensorflow/pull/33680?

Some comments in that one apply here. Again sorry for any lag with TensorFlow World last week.

**Comment by zhoupeng** [comment]
@nkreeger
Patch updated as you suggest, pls review again.

**Comment by gbaned** [comment]
@zhoupeng Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@zhoupeng gentle ping to resolve conflicts. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 29 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
