### PR TITLE
[ROCM] Adding support for rocblas, rocfft, and rocrand

### PR DESCRIPTION
**Pull request by deven-amd**
@timshen91, @whchung 

This PR is to add the support for rocblas, rocfft, and rocrand plugins. These libraries will be dynamically loaded (similar to their CUDA counterparts).

Note that even though the "--config=rocm" compile will (continue to) build successfully after this PR merged, we will still upstream a few more PRs before the tensorflow functionality can be tested with "--config=rocm" builds in the upstream repo.

Tim, 

Once you have reviewed the changes (which are broken down into 5 commits for ease of review), I can squash them into one if need be. Please let me know if that is required.

Thanks

deven

### CODE REVIEW

**Comment by whchung** [comment]
@deven-amd could you cherry-pick commits in https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/305 into this PR? it makes the initialization logic a bit more robust.

**Comment by deven-amd** [comment]
Where can I get the "buildifier" tool? 

The "Ubuntu Sanity" failure seems to due to incorrectly formatted `BUILD` file, and the recommended solution is to run it through the "buildifier" tool.

thanks

**Comment by whchung** [comment]
@deven-amd `tensorflow/tools/ci_build/ci_sanity.sh`

**Comment by timshen91** [comment]
Unfortunately I don't have cycles for the following reviews. I'll leave them to othe reviewers.

I'll juggle this back to @jlebar.

**Comment by jlebar** [comment]
@chsigg are you willing and able to take this review?

**Comment by whchung** [comment]
@chsigg another gentle ping. the test results show no impact to existing test targets. the single failure on "Ubuntu Python3 PIP" doesn't seem to be related to this PR.

**Comment by chsigg** [comment]
Generally this looks good. I am going to generate an internal CL from this to continue my review. I will have to mark this PR as 'ready to pull' for that. It doesn't mean it's really ready to be merged, it just allows me to view the difference in our source tree. Thanks for you patience.

**Comment by deven-amd** [comment]
@chsigg 

gentle ping. Also I just rebased to remove the merge conflicts.

**Comment by chsigg** [comment]
Thanks for your help! I'm working on getting this PR submitted.

**Review by chsigg — APPROVED** [review]

**Pull request merged**
