### PR TITLE
build: Support Bazel 1.0

### PR DESCRIPTION
**Pull request by byronyi**
Ping @gunan @seanpmorgan @dslomov; is there any known blockers?

### CODE REVIEW

**Comment by laszlocsomor** [comment]
@meteorcloudy , how can I help?

**Comment by meteorcloudy** [comment]
@laszlocsomor I'll finish the work to upgrading Bazel to 0.29.1. Can you help making TensorFlow build with Bazel 1.0. Currently the build is red after we released 1.0 and TensorFlow is temporarily disabled at Bazel's Downstream pipeline. I believe the main blocker is https://github.com/tensorflow/tensorflow/issues/32835.

**Comment by gbaned** [comment]
@laszlocsomor Any update on this PR, please.

**Comment by byronyi** [comment]
@gbaned This is staled as TF builds with Bazel >= 1.1.0.

Closing for now.

**Pull request closed without merging**
