### PR TITLE
[XLA] Wrap LCB::GetOrCreateLocalClient with StatusOr<T>

### PR DESCRIPTION
**Pull request by ajweiss**
Prevents crashes when GPUs present, but below minimum capability level

Fixes [google/jax issue #39](https://github.com/google/jax/issues/39)

### CODE REVIEW

**Review by froystig — DISMISSED** [review]
Looks good to me. Thanks for the PR!

**Comment by hgadig** [comment]
@ajweiss Can you please run clang-format on your code.

**Comment by ajweiss** [comment]
Formatted, squashed and force-pushed!

**Comment by hgadig** [comment]
@froystig  Could you also approve this PR if it looks good. Approving would help to proceed with the next steps for merging. Thank you !

**Review by froystig — CHANGES_REQUESTED** [review]
Did you run `clang-format -style=Google`? Pointer declarations were reformatted in a way that seems unusual for this project. Otherwise, it still looks good.

**Comment by ajweiss** [comment]
Strange, it seems to center the asterisk for pointers even when in Google mode.  I also see it elsewhere in the codebase:

[scatter_expander.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/scatter_expander.cc#L59)

I'm not sure what the story is, maybe the macro is confusing clang-format somehow?  The official style guide says they should be left or right justified.

I can manually fix it up, but I could also see that causing problems with automated tools that use clang-format down the line and it would be inconsistent with the other places in the codebase.  It does however, appear to format correctly when the `const` keyword is used when defining the pointer in the macro.

**Comment by froystig** [comment]
Understood and agreed. Thanks for clarifying!

**Review by froystig — APPROVED** [review]

**Comment by ajweiss** [comment]
I see the CI checks are failing.  Let me know if I should rebase this on HEAD or if that's expected.  (I ask as it will probably trigger another review)

**Comment by hgadig** [comment]
> I see the CI checks are failing. Let me know if I should rebase this on HEAD or if that's expected. (I ask as it will probably trigger another review)

I'm taking care of this PR and helping to get it merged. I'll keep you posted if anything is required from your end. Thanks !

**Pull request merged**
