### PR TITLE
integer overflow possibility fix v.2

### PR DESCRIPTION
**Pull request by iurii-kvasniuk**
The current code for static int64 GetDirectConvCost f-n can lead to integer overflow and weird results
Created issue: #32045

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Should we error on overflow or just clamp? At least a warning should be given

Also, please run linters and formatters over the code

**Comment by iurii-kvasniuk** [comment]
Thanks for your reply. I will make the corrections just after weekend.

**Comment by iurii-kvasniuk** [comment]
@mihaimaruseac,
I have to comply corporate rules and it turns out that I can not use my personal accounts/mails for contributing, especially from resources others than my company’s resources.
My company even ready to provide me with legal corporate email, but it takes additional money, I am not sure it worths it.
I think the best way here is to close the PR.
The only thing that I am not sure that PR from shubham769 (https://github.com/tensorflow/tensorflow/pull/32083) is worthy to be accepted.
He copy-pasted all my commits even with my bugs. He could mention my PR at least. I think that such things should not be allowed.

**Comment by rthadur** [comment]
Thank you @iurii-kvasniuk for your contribution, closing this PR based on latest comments.

**Pull request closed without merging**
