### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hey there. I've just optimized all of your images. They are the same dimensions and quality as before, only they take up less space now.

\tensorflow\examples\android\res\drawable-xxhdpi\ic_launcher.png (16.04%))
\tensorflow\contrib\factorization\g3doc\gmm.png (61.79%))
\tensorflow\core\profiler\g3doc\profiler_ui.jpg (12.02%))
\tensorflow\contrib\pi_examples\label_image\data\grace_hopper.jpg (4.83%))
\tensorflow\contrib\factorization\g3doc\kmeans.png (61.21%))
\tensorflow\contrib\factorization\g3doc\wals.png (3.51%))
\tensorflow\core\profiler\g3doc\code_timeline.png (39.87%))
\tensorflow\contrib\kernel_methods\g3doc\acc_vs_outdim.png (13.7%))
\tensorflow\core\lib\png\testdata\lena_rgba.png (5.21%))
\tensorflow\contrib\kernel_methods\g3doc\acc-vs-trn_time.png (14.03%))
\tensorflow\contrib\kernel_methods\g3doc\kernel_mapping.png (2.08%))
\tensorflow\contrib\linear_optimizer\kernels\g3doc\newton.png (38.51%))
\tensorflow\core\lib\jpeg\testdata\medium.jpg (7.52%))
\tensorflow\core\profiler\g3doc\graph_timeline.png (0.3%))
\tensorflow\contrib\learn\python\learn\estimators\g3doc\svm.png (57.3%))
\tensorflow\core\lib\jpeg\testdata\small.jpg (26.06%))
\tensorflow\core\profiler\g3doc\scope_timeline.png (45.94%))
\tensorflow\examples\android\res\drawable-hdpi\ic_action_info.png (23.61%))
\tensorflow\examples\ios\benchmark\data\grace_hopper.jpg (11.77%))
\tensorflow\examples\label_image\data\grace_hopper.jpg (4.83%))
\tensorflow\contrib\linear_optimizer\kernels\g3doc\mod_newton.png (34.1%))
\tensorflow\examples\android\res\drawable-mdpi\ic_launcher.png (8.74%))
\tensorflow\examples\android\res\drawable-hdpi\ic_launcher.png (10.83%))
\tensorflow\examples\ios\camera\data\grace_hopper.jpg (11.77%))
\tensorflow\examples\android\res\drawable-xhdpi\ic_action_info.png (23.69%))
\tensorflow\examples\multibox_detector\data\surfers.jpg (8.2%))
\tensorflow\examples\android\res\drawable-hdpi\tile.9.png (30.1%))
\tensorflow\examples\android\res\drawable-xhdpi\ic_launcher.png (12.39%))
\tensorflow\contrib\linear_optimizer\kernels\g3doc\newton_compare_experiment.png (35.35%))
\tensorflow\examples\android\res\drawable-mdpi\ic_action_info.png (23.61%))
\tensorflow\examples\tutorials\deepdream\pilatus800.jpg (35.75%))
\tensorflow\contrib\verbs\design_diagram.png (44.22%))
\tensorflow\examples\ios\simple\data\grace_hopper.jpg (11.77%))
\tensorflow\examples\android\res\drawable-xxhdpi\ic_action_info.png (25.65%))
\tensorflow\core\lib\png\testdata\lena_gray.png (24.95%))

### CODE REVIEW

**Comment by drpngx** [comment]
Thanks! Since these are binaries, for security reasons we'll probably want to run the optimizer ourselves. How did compress them?

**Comment by dabutvin** [comment]
ImgBot uses Imagemagick - https://github.com/dlemstra/Magick.NET - utilizing the `LosslessCompress` routine

see
https://github.com/dabutvin/ImgBot/blob/78efe1179df81acb9990bbba52cee072e6ac42d9/ImgBot.Function/CompressImages.cs#L64-L89

This bot is designed as a GitHub app that you can install into a GitHub repo.

https://github.com/apps/ImgBot

**Comment by sb2nov** [comment]
@drpngx what should be the next steps here?

**Comment by drpngx** [comment]
Thank you @dabutvin sorry it dropped off my list.

@MarkDaoust @mhyttsten Any suggestions here?

**Comment by MarkDaoust** [comment]
I can recompress the images, but I'm not sure about the value of doing this, on github.

Git stores the history, so while looking at an image will be more efficient, doesn't this just add bloat for anyone doing a git clone (without using the --depth flag)? 

Isn't the right solution to move these to tensorflow.org and compress them there?

**Comment by martinwicke** [comment]
Technically, no images >20k should be in the repo. We once had a presubmit for that, but not sure it's doing its job. Especially the images in various g3doc subfolders seem very suspect.

Those should probably be deleted (the folders) -- they don't belong on github at all, docs_srcs should be it.

**Comment by martinwicke** [comment]
I will close this PR -- I do like the bot though, it's very cool!

**Pull request closed without merging**
