### PR TITLE
Fix issue of `name` used in `build_default_serving_input_fn`

### LINKED ISSUE #12755: build_default_serving_input_fn() uses a name that is not a valid variable scope.
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04 LTS 
- **TensorFlow installed from (source or binary)**: SOURCE (pip install tensorflow) 
- **TensorFlow version (use command below)**: ('v1.3.0-rc2-20-g0787eee', '1.3.0')
- **Python version**: Python 2.7.6
- **Bazel version (if compiling from source)**: N/A 
- **CUDA/cuDNN version**: N/A 
- **GPU model and memory**: N/A 
- **Exact command to reproduce**:

### Describe the problem

See this short example:

$ python -c "import tensorflow as tf 
f = {'feature': tf.placeholder(name='feature', shape=[32], dtype=tf.float32) } 
serving_input = tf.contrib.learn.utils.input_fn_utils.build_default_serving_input_fn(f)
serving_input()"

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/utils/input_fn_utils.py", line 112, in input_fn
    name=t.name)
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1548, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2094, in _placeholder
    name=name)
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 374, in apply_op
    with g.as_default(), ops.name_scope(name) as scope:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4522, in name_scope
    with g.as_default(), g.name_scope(n) as scope:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3172, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'feature:0' is not a valid scope name

The issue is that in input_fn_utils.py here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/utils/input_fn_utils.py#L112

The attribute "t.name" is passed to array_ops.placeholder(), and t.name will always have a ":N" suffix, and ":" is not a valid variable scope name, so this function fals. 

### Source code / logs

See above.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #12755 where the name used in `build_default_serving_input_fn` is not a valid variable scope:
```
$ python -c "import tensorflow as tf
f = {'feature': tf.placeholder(name='feature', shape=[32], dtype=tf.float32) }
serving_input = tf.contrib.learn.utils.input_fn_utils.build_default_serving_input_fn(f)
serving_input()"
...
ValueError: 'feature:0' is not a valid scope name
```

In `build_default_serving_input_fn`, the name of the tensor is used directly which consists of the op name and the value index:
```
class Tensor(_TensorLike):
....
  @property
  def name(self):
    """The string name of this tensor."""
    if not self._op.name:
      raise ValueError("Operation was not named: %s" % self._op)
    return "%s:%d" % (self._op.name, self._value_index)
```

This fix fixes this issue by using the name of the tensor's op (not tensor): `t.op.name` instead, to avoid the ":0" (value index) at the end.

This fix fixes #12755.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by slacy** [comment]
Probably should add a simple unit test for build_default_serving_input_fn that mimics what I did to repro this?

**Comment by martinwicke** [comment]
Yes, such a test would be great.

**Comment by yongtang** [comment]
Thanks @slacy @martinwicke . The PR has been updated with test cases added. Please take a look.

**Comment by yongtang** [comment]
Updated the PR to cover `tf.estimator.export.build_raw_serving_input_receiver_fn` as well.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by yifeif** [comment]
@davidsoergel, @martinwicke does the change look good to you?

**Comment by drpngx** [comment]
Jenkins, test this please. (master got stuck)

@davidsoergel @martinwicke any luck with this?

**Comment by sb2nov** [comment]
@martinwicke ping

**Review by martinwicke — APPROVED** [review]

**Comment by sathyamoorthyrr** [comment]
In one of my legacy project using google **seq2seq**, I use **Tensorflow 1.3**
In [train.py](https://github.com/google/seq2seq/blob/master/bin/train.py), could see that `Experiment` based structure is used. To existing code, I additionally added `export_strategies` parameters and tried to export. Faced the same error as in [Issue 12775](https://github.com/tensorflow/tensorflow/issues/12755). Referring to this merge request, I manually changed the respective files and exported successfully.

But, I cannot even load the exported graph with these simple lines,
```
with tf.Session(graph=tf.Graph()) as sess:
  tf.saved_model.loader.load(sess, ["serve"], export_dir)
```
The error says,
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-a5f6a641c0c9> in <module>()
      4 
      5 with tf.Session(graph=tf.Graph()) as sess:
----> 6   tf.saved_model.loader.load(sess, ["serve"], export_dir)

/pyenv/local/lib/python2.7/site-packages/tensorflow/python/saved_model/loader_impl.pyc in load(sess, tags, export_dir, **saver_kwargs)
    214 
    215     # Build a saver by importing the meta graph def to load.
--> 216     saver = tf_saver.import_meta_graph(meta_graph_def_to_load, **saver_kwargs)
    217 
    218     if saver:

/pyenv/local/lib/python2.7/site-packages/tensorflow/python/training/saver.pyc in import_meta_graph(meta_graph_or_file, clear_devices, import_scope, **kwargs)
   1696                                       clear_devices=clear_devices,
   1697                                       import_scope=import_scope,
-> 1698                                       **kwargs)
   1699   if meta_graph_def.HasField("saver_def"):
   1700     return Saver(saver_def=meta_graph_def.saver_def, name=import_scope)

/pyenv/local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.pyc in import_scoped_meta_graph(meta_graph_or_file, clear_devices, graph, import_scope, input_map, unbound_inputs_col_name, restore_collections_predicate)
    690           for value in field.value:
    691             col_op = graph.as_graph_element(
--> 692                 ops.prepend_name_scope(value, scope_to_prepend_to_names))
    693             graph.add_to_collection(key, col_op)
    694         elif kind == "int64_list":

/pyenv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in as_graph_element(self, obj, allow_tensor, allow_operation)
   2706 
   2707     with self._lock:
-> 2708       return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
   2709 
   2710   def _as_graph_element_locked(self, obj, allow_tensor, allow_operation):

/pyenv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in _as_graph_element_locked(self, obj, allow_tensor, allow_operation)
   2766         if name not in self._nodes_by_name:
   2767           raise KeyError("The name %s refers to an Operation not in the "
-> 2768                          "graph." % repr(name))
   2769         return self._nodes_by_name[name]
   2770 

KeyError: "The name 'hash_table' refers to an Operation not in the graph."
```
Does this occur because of my manual changes that may not be compatible with other part? Possibly, should I change any other part of code? or that change has nothing to do and is a different error?

**Comment by martinwicke** [comment]
I don't think the issue you cited is related, but it's impossible to tell
without knowing what you exactly did to the graph when you edited the
files. If you modified some the Graph it is quite likely you created an
inconsistent state.

**Comment by sathyamoorthyrr** [comment]
@martinwicke 
I tried to export the model (**SavedModel** format) using the following code in [existing file](https://github.com/google/seq2seq/blob/master/bin/train.py),

```
  source_tokens_ph = tf.placeholder(dtype=tf.string, shape=(1, None))
  source_len_ph = tf.placeholder(dtype=tf.int32, shape=(1,))

  features_serve = {
    "source_tokens": source_tokens_ph,
    "source_len": source_len_ph
  }

  experiment = PatchedExperiment(
  ...

  export_strategies = [saved_model_export_utils.make_export_strategy(serving_input_fn = build_default_serving_input_fn(features_serve))]
  )
```
I faced an error as in this [issue](https://github.com/tensorflow/tensorflow/issues/12755).
Upon referring to this [merge request](https://github.com/tensorflow/tensorflow/pull/12759/files), I edited the following files in my local tensorflow library,

1. tensorflow/contrib/learn/python/learn/utils/input_fn_utils.py
2. tensorflow/python/estimator/export/export.py

It helped me to successfully export the model.

However, the simple code to load that exported model fails with the previously mentioned error,
```
with tf.Session(graph=tf.Graph()) as sess:
  tf.saved_model.loader.load(sess, ["serve"], export_dir)
```
Also, leaving out the exported graph, I tried this with the model files directory,

```
with tf.Session() as sess:
    saver = tf.train.import_meta_graph(checkpoint + '.meta')
```
This also fails with the similar error,

> KeyError: "The name 'hash_table' refers to an Operation not in the graph."

Could not find what's messed up!

To further say, the code in this [file](https://github.com/google/seq2seq/blob/master/bin/train.py) uses **MonitoredTrainingSession**

Also, if you can help, I used the exported model for Tensorflow Serving and facing [this problem](https://stackoverflow.com/questions/54899188/error-model-att-seq2seq-minimum0-is-both-fed-and-fetched)(may be not related to this)

**Comment by sathyamoorthyrr** [comment]
Upon analyzing further,
I tried to print `self._nodes_by_name` from [here](https://github.com/tensorflow/tensorflow/blob/31f770fa9fa8e32606fca7333349ce5c722fc199/tensorflow/python/framework/ops.py#L3709)

**Part of Output:**
```
u'model/att_seq2seq/hash_table': <tf.Operation 'model/att_seq2seq/hash_table' type=HashTableV2>
u'model/att_seq2seq/hash_table_1': <tf.Operation 'model/att_seq2seq/hash_table_1' type=HashTableV2>, 
u'model/att_seq2seq/hash_table_3': <tf.Operation 'model/att_seq2seq/hash_table_3' type=HashTableV2>, 
u'model/att_seq2seq/hash_table_2': <tf.Operation 'model/att_seq2seq/hash_table_2' type=HashTableV2>,
u'model/att_seq2seq/hash_table_5': <tf.Operation 'model/att_seq2seq/hash_table_5' type=HashTableV2>,
u'model/att_seq2seq/hash_table_4': <tf.Operation 'model/att_seq2seq/hash_table_4' type=HashTableV2>
```
And, I tried to print `meta_graph_def.collection_def.items()` from [here](https://github.com/tensorflow/tensorflow/blob/31f770fa9fa8e32606fca7333349ce5c722fc199/tensorflow/python/framework/meta_graph.py#L859)

**Part of Output:**
```
(u'vocab_tables_values', node_list {
  value: "hash_table"
  value: "hash_table_5"
  value: "hash_table_1"
  value: "hash_table_2"
  value: "hash_table_4"
  value: "hash_table_3"
})
```
The node_list's(**2nd Output**) values are validated against **1st Output** by seeing [here](https://github.com/tensorflow/tensorflow/blob/31f770fa9fa8e32606fca7333349ce5c722fc199/tensorflow/python/framework/ops.py#L3709)

That seems to raise an error.

Searching the seq2seq library for **vocab_tables** gives some hint to reach [here](https://github.com/google/seq2seq/blob/7f485894d412e8d81ce0e07977831865e44309ce/seq2seq/models/seq2seq_model.py#L214)

Hope this could help towards the possible solution.
Kindly ping if more details are needed.

Again, to stress, it uses **Tensorflow 1.3**

Any help is appreciated. Thanks in advance

**Pull request merged**
