### PR TITLE
The gradient op of bias_add supports 3/4/5D NCHW format

### PR DESCRIPTION
**Pull request by facaiy**
Ref: #22127, #23004

### CODE REVIEW

**Review by frankchn — DISMISSED** [review]

**Comment by frankchn** [comment]
Probably not related to your changes, but

//tensorflow/python/kernel_tests/distributions:student_t_test
//tensorflow/contrib/constrained_optimization:candidates_test

are failing. Can you rebase to master and try again?

**Comment by facaiy** [comment]
Thank you, Frank.
Yes, unrelated failures. Because [MacOs Build](https://storage.googleapis.com/tensorflow-kokoro-build-badges/macos-py2-cc.html) of master branch also fails, I doubt whether it works (rebase).

**Comment by facaiy** [comment]
@frankchn Still fails. But I think they are unrelated.

**Comment by frankchn** [comment]
:( -- can you rebase to head and try again?

**Comment by facaiy** [comment]
Sure :-)

**Review by frankchn — APPROVED** [review]

**Pull request merged**
