### PR TITLE
Using count for Set Membership Check

### PR DESCRIPTION
**Pull request by gautam1858**
Instead of find and comparing to end(), using count to check for membership in the std::unordered_set. which is more efficient.

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Can you provide a benchmark? In general find can terminate early, as soon as an element is found, whereas count needs to go to the end of the array, so this looks like a pessimization, not an optimization.

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
https://quick-bench.com/q/IsFeSai4ZF6jt2WeJuMxpLwD7gA shows that count is slower

**Comment by gautam1858** [comment]
Checkout this benchmark where count is faster than find - https://quick-bench.com/q/F_JiLDSu-7tQVgb-pHqPSoDxQsc

**Comment by mihaimaruseac** [comment]
That's for a container of a smaller size, I don't think that is that relevant here.

If you have a user-level macro benchmark that proves this is an optimization I'll reopen, but just fudging with a micro benchmark to change numbers doesn't work

**Comment by mihaimaruseac** [comment]
Also, your benchmark seems influenced by noise, rerunning gives https://quick-bench.com/q/F_JiLDSu-7tQVgb-pHqPSoDxQsc

**Comment by mihaimaruseac** [comment]
That is, clearing the cache and rerunning generates new results. Your link now proves the contrary of what you've said.

**Pull request closed without merging**
