### PR TITLE
Update head.py

### PR DESCRIPTION
**Pull request by alanyee**
Use tf.losses instead of deprecated contrib

### CODE REVIEW

**Review by frankchn — APPROVED** [review]

**Comment by frankchn** [comment]
Jenkins, test this please.

**Comment by frankchn** [comment]
Trying this again.

@tensorflow-jenkins, test this please.

**Comment by alanyee** [comment]
@tensorflow-jenkins, test this please.

**Comment by terrytangyuan** [comment]
@tensorflow-jenkins Test this please

**Comment by frankchn** [comment]
Here is the error: 

```======================================================================
ERROR: testBinarySVMWith1DWeights (__main__.BinarySvmHeadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head_test.py", line 1581, in testBinarySVMWith1DWeights
    logits=self._predictions)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head.py", line 1258, in create_model_fn_ops
    enable_centered_bias=self._enable_centered_bias)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head.py", line 638, in _create_model_fn_ops
    loss, weighted_average_loss = loss_fn(labels, logits, weight_tensor)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head.py", line 1216, in _loss_fn
    return _compute_weighted_loss(loss, weights)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head.py", line 1796, in _compute_weighted_loss
    weight = weights_broadcast_ops.broadcast_weights(weight, loss_unweighted)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/python/ops/weights_broadcast_ops.py", line 167, in broadcast_weights
    with ops.control_dependencies((assert_broadcastable(weights, values),)):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/python/ops/weights_broadcast_ops.py", line 103, in assert_broadcastable
    weights_rank_static, values.shape, weights.shape))
ValueError: weights can not be broadcast to values. values.rank=0. weights.rank=2. values.shape=(). weights.shape=(2, 1).```

**Comment by frankchn** [comment]
@tensorflow-jenkins, test this please.

**Comment by frankchn** [comment]
@tensorflow-jenkins, test this please.

**Comment by frankchn** [comment]
@tensorflow-jenkins, test this please.

**Comment by printdhruv** [comment]
Great! @alanyee Would using debugger might have helped me ?

**Comment by alanyee** [comment]
@printdhruv I just read the code and documentation really closely. My initial confusion came from the lack of static types, so luckily my PL theory and compiler classes help me get pass the confusion.

**Comment by printdhruv** [comment]
@alanyee Nice to hear that one.How you are planning to fix tf.summary ?

**Comment by alanyee** [comment]
I will eventually read the code closely, but right now, I am too sleepy to focus and I need to watch the latest episode of Games of Thrones.

**Comment by printdhruv** [comment]
No problem :) I think it will work with what I tried in my version . Finger crossed;)

**Pull request merged**
