### PR TITLE
System libs: unbundle more and add variables for PREFIX support

### PR DESCRIPTION
**Pull request by perfinion**
This adds a few variables so some common variables like $PREFIX, $LIBDIR, $INCLUDEDIR are supported and unbundle double-conversion and boringssl deps.

### CODE REVIEW

**Comment by perfinion** [comment]
I added some more commits to unbundle absl_py as well.
@angersson can you in particular review the third_party/repo.bzl bits? I added a system_link_files attr just like the link_files from your third_party_http_archive. If syslibs is enabled and both link_files and system_link_files specify the same file then it should us the system_ one. or should it instead require the system_ one to fully specify all of the files again instead of sharing between link_files and system_link_files?

**Comment by perfinion** [comment]
oh and someone will need to mirror, i moved it from native.http_archive to tf_http_archive so i could use system_build_file
"https://mirror.bazel.build/github.com/google/double-conversion/archive/3992066a95b823efc8ccc1baf82a1cfc73f6e9b8.zip",

**Comment by angersson** [comment]
Sorry in advance -- I'll have slow responses on this. I'm the release owner for 1.11, and will be pretty busy for the next couple of weeks.

**Comment by martinwicke** [comment]
@perfinion there are a few bazel failures that I think may be related to this PR, can you look?

**Comment by perfinion** [comment]
I think 7461ff7837bb9c57f0020d8adf46a73596dfb77d fixed it, i rebased on top, lets see how the tests go now

**Comment by perfinion** [comment]
@martinwicke it looks good now, the only failure is //tensorflow/compiler/xla/tests:exhaustive_f32_elementwise_op_test_cpu which has been failing for a few weeks so is unrelated. :)

Also I've included this patchset (+protobuf unbundling which isnt part of this PR) in the Gentoo package for tensorflow-1.11.0_rc{0,1,2} and its working well so far.

**Comment by noahstier** [comment]
> (+protobuf unbundling which isnt part of this PR)

@perfinion would you mind pointing me to your changes for protobuf unbundling? I see in the build script for the gentoo package that you added protobuf to TF_SYSTEM_LIBS, but I can't find the changes to Tensorflow to observe that option.

**Comment by perfinion** [comment]
@noahstier 
The discussion on sig-build is here: https://groups.google.com/a/tensorflow.org/forum/#!topic/build/sSOdm79w-DI
and the rebased patch is here: https://github.com/perfinion/tensorflow/tree/protobuf

**Pull request merged**
