### PR TITLE
Multiple fixes in KMeans clustering estimator

### PR DESCRIPTION
**Pull request by terrytangyuan**
- Fixed inconsistent usage of `batch_size` and `steps` in kmeans estimator
- Removed unused `continue_training` and `verbose`
- Reused the same `RunConfig` in tests

### CODE REVIEW

**Comment by vrv** [comment]
(i'm waiting for green tests :)

**Comment by terrytangyuan** [comment]
@vrv Thanks. Done!  :-)

**Comment by vrv** [comment]
(not sure who the best reviewer is for this, so assigning to two people)

**Comment by terrytangyuan** [comment]
Perhaps @martinwicke can take a look. This is similar to #3244.

**Comment by martinwicke** [comment]
the self.batch_size line puzzled me -- is it ever executed? I feel like it shouldn't have worked in tests.

**Comment by terrytangyuan** [comment]
@martinwicke Yeah the author was using `num_points` for `bacth_size` like this in the test class:
```
   @property
    def batch_size(self):	
      return self.num_points
```

**Comment by terrytangyuan** [comment]
@martinwicke so `self.batch_size` is a property defined in `KMeansTest` so it can be reused.

**Comment by martinwicke** [comment]
Thanks!

**Pull request merged**
