### PR TITLE
Upgrade grpc to 1.41.1 and protobuf to 3.19.0

### PR DESCRIPTION
**Pull request by meteorcloudy**
This is a retry of https://github.com/tensorflow/tensorflow/pull/51923

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by meteorcloudy** [comment]
With protobuf 3.19.1, many Linux tests are failing with Segmentation fault:
 https://source.cloud.google.com/results/invocations/23e260dc-55b8-446a-92c2-a57b7423a56f/targets

I did a bisect on protobuf in the TensorFlow build, can identify the breakage on Linux comes from this commit:
https://github.com/protocolbuffers/protobuf/commit/a00125024e9231d76746bd394fef8876f5cc15e2

Unfortunately, this is a sync commit with internal code base, it's still very hard to figure what's the exact breakage.

/cc @learning-to-play  @yongtang 
/cc protobuf experts @acozzette @TeBoring

**Comment by acozzette** [comment]
@meteorcloudy I looked at a couple of the failures but the logs didn't seem to include a stack trace or anything. Do you know if there is any way to get access to a more detailed error message?

**Comment by meteorcloudy** [comment]
@acozzette Thanks for looking into it, I managed to get a stack trace with gdb:
```
Reading symbols from bazel-bin/tensorflow/c/experimental/ops/gen/cpp/cpp_generator_test...done.

warning: core file may not match specified executable file.
[New LWP 5773]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `bazel-bin/tensorflow/c/experimental/ops/gen/cpp/cpp_generator_test'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4fddc1657d in tensorflow::OpDef::OpDef(tensorflow::OpDef const&) ()
   from /home/kbuilder/.cache/bazel/_bazel_kbuilder/b35e56146bb385d966771bab3ed3e8cb/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/c/experimental/ops/gen/cpp/../../../../../../_solib_local/_U_S_Stensorflow_Sc_Sexperimental_Sops_Sgen_Scpp_Ccpp_Ugenerator_Utest___Utensorflow/libtensorflow_framework.so.2
#0  0x00007f4fddc1657d in tensorflow::OpDef::OpDef(tensorflow::OpDef const&) ()
   from /home/kbuilder/.cache/bazel/_bazel_kbuilder/b35e56146bb385d966771bab3ed3e8cb/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/c/experimental/ops/gen/cpp/../../../../../../_solib_local/_U_S_Stensorflow_Sc_Sexperimental_Sops_Sgen_Scpp_Ccpp_Ugenerator_Utest___Utensorflow/libtensorflow_framework.so.2
#1  0x00007f4fdd12f573 in std::_Function_base::_Base_manager<tensorflow::register_op::OpDefBuilderWrapper::operator()()::{lambda(tensorflow::OpRegistrationData*)#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<tensorflow::register_op::OpDefBuilderWrapper::operator()()::{lambda(tensorflow::OpRegistrationData*)#1}> const&, std::_Manager_operation) ()
   from /home/kbuilder/.cache/bazel/_bazel_kbuilder/b35e56146bb385d966771bab3ed3e8cb/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/c/experimental/ops/gen/cpp/../../../../../../_solib_local/_U_S_Stensorflow_Sc_Sexperimental_Sops_Sgen_Scpp_Ccpp_Ugenerator_Utest___Utensorflow/libtensorflow_framework.so.2
#2  0x00007f4fdd12a785 in std::function<tensorflow::Status (tensorflow::OpRegistrationData*)>::function(std::function<tensorflow::Status (tensorflow::OpRegistrationData*)> const&) ()
   from /home/kbuilder/.cache/bazel/_bazel_kbuilder/b35e56146bb385d966771bab3ed3e8cb/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/c/experimental/ops/gen/cpp/../../../../../../_solib_local/_U_S_Stensorflow_Sc_Sexperimental_Sops_Sgen_Scpp_Ccpp_Ugenerator_Utest___Utensorflow/libtensorflow_framework.so.2
#3  0x00007f4fdd12a84d in void std::vector<std::function<tensorflow::Status (tensorflow::OpRegistrationData*)>, std::allocator<std::function<tensorflow::Status (tensorflow::OpRegistrationData*)> > >::_M_realloc_insert<std::function<tensorflow::Status (tensorflow::OpRegistrationData*)> const&>(__gnu_cxx::__normal_iterator<std::function<tensorflow::Status (tensorflow::OpRegistrationData*)>*, std::vector<std::function<tensorflow::Status (tensorflow::OpRegistrationData*)>, std::allocator<std::function<tensorflow::Status (tensorflow::OpRegistrationData*)> > > >, std::function<tensorflow::Status (tensorflow::OpRegistrationData*)> const&) ()
   from /home/kbuilder/.cache/bazel/_bazel_kbuilder/b35e56146bb385d966771bab3ed3e8cb/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/c/experimental/ops/gen/cpp/../../../../../../_solib_local/_U_S_Stensorflow_Sc_Sexperimental_Sops_Sgen_Scpp_Ccpp_Ugenerator_Utest___Utensorflow/libtensorflow_framework.so.2
#4  0x00007f4fdd1301ba in tensorflow::OpRegistry::Register(std::function<tensorflow::Status (tensorflow::OpRegistrationData*)> const&) ()
   from /home/kbuilder/.cache/bazel/_bazel_kbuilder/b35e56146bb385d966771bab3ed3e8cb/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/c/experimental/ops/gen/cpp/../../../../../../_solib_local/_U_S_Stensorflow_Sc_Sexperimental_Sops_Sgen_Scpp_Ccpp_Ugenerator_Utest___Utensorflow/libtensorflow_framework.so.2
#5  0x00007f4fdd130980 in tensorflow::register_op::OpDefBuilderWrapper::operator()() ()
   from /home/kbuilder/.cache/bazel/_bazel_kbuilder/b35e56146bb385d966771bab3ed3e8cb/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/c/experimental/ops/gen/cpp/../../../../../../_solib_local/_U_S_Stensorflow_Sc_Sexperimental_Sops_Sgen_Scpp_Ccpp_Ugenerator_Utest___Utensorflow/libtensorflow_framework.so.2
#6  0x00007f4fce8a8712 in __static_initialization_and_destruction_0(int, int) [clone .constprop.17] ()
   from /home/kbuilder/.cache/bazel/_bazel_kbuilder/b35e56146bb385d966771bab3ed3e8cb/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/c/experimental/ops/gen/cpp/../../../../../../_solib_local/libtensorflow_Scompiler_Smlir_Stensorflow_Slibmlir_Upassthrough_Uop.so
#7  0x00007f4fde5828d3 in call_init (env=0x7fff2e73b0b8, argv=0x7fff2e73b0a8, argc=1, l=<optimized out>) at dl-init.c:72
#8  _dl_init (main_map=0x7f4fde79d170, argc=1, argv=0x7fff2e73b0a8, env=0x7fff2e73b0b8) at dl-init.c:119
#9  0x00007f4fde5730ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#10 0x0000000000000001 in ?? ()
#11 0x00007fff2e73cb44 in ?? ()
#12 0x0000000000000000 in ?? ()
```

Another interesting observation is that this only happens with test binary with **remote execution,** I cannot reproduce if build and test locally (test passes normally).

**Comment by meteorcloudy** [comment]
This has something to do with the RBE cc toolchain, I can reproduce the issue with 
`bazel test --config=rbe_cpu_linux_base //tensorflow/c/experimental/ops/gen/cpp:cpp_generator_test` locally.

**Comment by acozzette** [comment]
I bet this is related to the global protobuf default instances being constant-initialized, since that is one of the major C++ changes in the protobuf commit from the bisect.

Here is my guess for what is happening: for some reason the RBE toolchain is not constant-initializing the protobuf default instances and is instead trying to initialize them at runtime. Then Tensorflow registration is not working properly because it uses the `OpDef` proto which isn't fully functional without the default instances initialized. This could be a variation of the C++ static initialization order [fiasco](https://en.cppreference.com/w/cpp/language/siof).

**Comment by bhack** [comment]
> the RBE toolchain is not constant-initializing...

Are we not matching in the macro on RBE the extra case for:
```
 #define PROTOBUF_CONSTINIT [[clang::require_constant_initialization]]
```

**Comment by acozzette** [comment]
> > the RBE toolchain is not constant-initializing...
> 
> Are we not matching in the macro on RBE the extra case for:
> 
> ```
>  #define PROTOBUF_CONSTINIT [[clang::require_constant_initialization]]
> ```

That could be. My understanding is that the constant initialization is supposed to work regardless of how `PROTOBUF_CONSTINIT` is defined, but we define it when possible anyway because that will force the compiler to return an error if it's unable to do the constant initialization.

@sbenzaquen Do you have any ideas on whether something could be going wrong with the const initialization?

**Comment by meteorcloudy** [comment]
@acozzette Thanks! Sounds like this one https://stackoverflow.com/questions/11911662/c-static-member-initialization-confuses-with-compiler-linking-how-to-solve? 
Is there a way to prevent this problem from protobuf side?

**Comment by sbenzaquen** [comment]
> > > the RBE toolchain is not constant-initializing...
> > 
> > 
> > Are we not matching in the macro on RBE the extra case for:
> > ```
> >  #define PROTOBUF_CONSTINIT [[clang::require_constant_initialization]]
> > ```
> 
> That could be. My understanding is that the constant initialization is supposed to work regardless of how `PROTOBUF_CONSTINIT` is defined, but we define it when possible anyway because that will force the compiler to return an error if it's unable to do the constant initialization.
> 
> @sbenzaquen Do you have any ideas on whether something could be going wrong with the const initialization?

Constant initialization is mainly there to save on resources. It reduces binary size and runtime costs.
In MSVC, for example, we are not constant initializing the globals and they will just be runtime initialized during static initialization time.

I see that the stack trace above is happening during static initialization time.
Using protobuf during static initialization time is not supported, since the protobuf library itself is being initialized at this time.
If this platform is not constant initializing the objects, then it might be likely using it before it is initialized. Note that even on platforms that support constant initialization you are still at risk of using parts of protobuf before they are initialized.

**Comment by acozzette** [comment]
@meteorcloudy Do you have a way to make an edit to force `PROTOBUF_CONSTINIT` to be `[[clang::require_constant_initialization]]` and rerun the tests on RBE that way? It would be good to confirm for sure that we know what the problem is.

**Comment by meteorcloudy** [comment]
@acozzette Sure, can you send me a patch? I can help verify it.

**Comment by acozzette** [comment]
I was thinking you could just replace lines 577-587 [here](https://github.com/protocolbuffers/protobuf/blob/7ccf4d8f67878a6ceb2184df279478cb3314372b/src/google/protobuf/port_def.inc#L577) with this one line:
```
#define PROTOBUF_CONSTINIT [[clang::require_constant_initialization]]
```

**Comment by meteorcloudy** [comment]
@acozzette I still failed with the same error with the following patch on protocolbuffers/protobuf@a001250:
```
--- a/src/google/protobuf/port_def.inc
+++ b/src/google/protobuf/port_def.inc
@@ -562,27 +562,29 @@
 // by this flag is supposed to be removed after this experiment.
 // #define PROTOBUF_MESSAGE_OWNED_ARENA_EXPERIMENT

-#if defined(__cpp_constinit)
-#define PROTOBUF_CONSTINIT constinit
-#elif defined(__has_cpp_attribute)
-#if __has_cpp_attribute(clang::require_constant_initialization)
 #define PROTOBUF_CONSTINIT [[clang::require_constant_initialization]]
-#endif
-#endif
-#ifndef PROTOBUF_CONSTINIT
-#define PROTOBUF_CONSTINIT
-#endif

-#if defined(__cpp_constinit)
-#define PROTOBUF_CONSTINIT constinit
-#elif defined(__has_cpp_attribute)
-#if __has_cpp_attribute(clang::require_constant_initialization)
-#define PROTOBUF_CONSTINIT [[clang::require_constant_initialization]]
-#endif
-#endif
-#ifndef PROTOBUF_CONSTINIT
-#define PROTOBUF_CONSTINIT
-#endif
```

**Comment by meteorcloudy** [comment]
I found an easy way to reproduce this inside a RBE docker container used on TF kokoro (but no need to enable RBE).
```
# Inside gcr.io/tensorflow-testing/nosla-cuda11.2-cudnn8.1-ubuntu18.04-manylinux2010-multipython
 
git clone https://github.com/meteorcloudy/tensorflow.git
git fetch origin upgrade_protobuf_grpc
git checkout upgrade_protobuf_grpc
 
./configure # Set Python to /usr/local/bin/python3.9
 
bazel test --config=rbe_cpu_linux_base //tensorflow/c/experimental/ops/gen/cpp:cpp_generator_test
```
Feel free to try it out

**Comment by bhack** [comment]
> bazel test --config=rbe_cpu_linux_base //tensorflow/c/experimental/ops/gen/cpp:cpp_generator_test

I've runned this in the image but the test log is empty:

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tensorflow/c/experimental/ops/gen/cpp:cpp_generator_test
-----------------------------------------------------------------------------
```

**Comment by meteorcloudy** [comment]
> I've runned this in the image but the test log is empty:

Yes, that's because the test binary failed at startup time due to the Segmentation fault. You'll need gdb to debug it, something like https://serverfault.com/questions/61659/can-you-get-any-program-in-linux-to-print-a-stack-trace-if-it-segfaults.

Unfortunately I don't have enough C++ knowledge for this..

**Comment by bhack** [comment]
Oh it was a segmentation fault.. so we can just use this bazel workaround in the meantime:

https://github.com/bazelbuild/bazel/issues/11371#issuecomment-884455884

**Comment by bhack** [comment]
> I was thinking you could just replace lines 577-587 [here](https://github.com/protocolbuffers/protobuf/blob/7ccf4d8f67878a6ceb2184df279478cb3314372b/src/google/protobuf/port_def.inc#L577) with this one line:
> 
> ```
> #define PROTOBUF_CONSTINIT [[clang::require_constant_initialization]]
> ```

I think this will not have any effect on the RBE image as we are using `gcc (GCC) 7.3.1 20180303`

Also `__constinit` for our c++14 mode I think was introduce only in GCC 10:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91360

**Comment by acozzette** [comment]
@bhack Could you try defining `PROTOBUF_CONSTINIT` as something like `__attribute__((init_priority((102))))`? We use this in `PROTOBUF_ATTRIBUTE_INIT_PRIORITY` in a few other places to guarantee that our initialization happens earlier than other initializations. This could be one potential solution. I'm not 100% sure if we would want to do this, but it would at least be useful to know if it fixes the problem.

**Comment by bhack** [comment]
@acozzette No, it is not working.

**Comment by meteorcloudy** [comment]
With the RBE cc toolchain, we are using `/dt7/usr/bin/gcc` instead of `/usr/bin/gcc` to do cross compiling which targets manylinux. There are some suspect that it's caused due to mismatch of libc/libc++ versions in the docker.

**Comment by bhack** [comment]
> With the RBE cc toolchain, we are using `/dt7/usr/bin/gcc` instead of `/usr/bin/gcc` to do cross compiling which targets manylinux. There are some suspect that it's caused due to mismatch of libc/libc++ versions in the docker.

Using bazel ` --subcommands` I see we are comping with 

`external/ubuntu18.04-gcc7_manylinux2010-cuda11.2-cudnn8.1-tensorrt7.2_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc`

That with `--version` is:

`gcc (GCC) 7.3.1 20180303
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by bhack** [comment]
I suppose it is coming from:
https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl

**Comment by meteorcloudy** [comment]
@bhack You are right, if you looking into `external/ubuntu18.04-gcc7_manylinux2010-cuda11.2-cudnn8.1-tensorrt7.2_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc`, the underlying cpp compiler would be `/dt7/usr/bin/gcc`

**Comment by bhack** [comment]
> @bhack You are right, if you looking into `external/ubuntu18.04-gcc7_manylinux2010-cuda11.2-cudnn8.1-tensorrt7.2_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc`, the underlying cpp compiler would be `/dt7/usr/bin/gcc`

So what is the incompatibility that you suppose we have between gcc `7.3.1 20180303`  and `libc++` (what version?) in the RBE docker?

**Comment by meteorcloudy** [comment]
I don't know the exact reason, but here is the dockerfile for the RBE docker:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.rbe.cuda11.2-cudnn8.1-ubuntu18.04-manylinux2010-multipython#L32

**Comment by meteorcloudy** [comment]
@d0k @jyknight might know more.

**Comment by bhack** [comment]
@meteorcloudy But just to be sure that it is related to the RBE image  have you tried if your branch and this selected test run regularly in the `tensorflow/tensorflow-devel` official image?

**Comment by meteorcloudy** [comment]
> But just to be sure that it is related to the RBE image have you tried if your branch and this selected test run regularly in the tensorflow/tensorflow-devel official image?

Yes, the tests pass correctly in my local build. It's only failing with the RBE docker contains with the RBE toolchain, which uses different compiler and toolchain. Normally it should be fine and it's how we always run TF tests on CI.

**Comment by r4nt** [comment]
So, tests fail with the devtoolset gcc, which uses the pre-C++11-string ABI.
It looks to me like  fixed_address_empty_string is not initialized because InitProtobufDefaultsImpl is not called.
I'm still trying to reproduce this.

**Comment by bhack** [comment]
> So, tests fail with the devtoolset gcc, which uses the pre-C++11-string ABI.

https://discuss.python.org/t/how-to-set-glibcxx-use-cxx11-abi-for-manylinux2014-and-manylinux2010-wheels/10551/4

That it is also  the problem we have experimenting with https://github.com/tensorflow/build/pull/41

**Comment by r4nt** [comment]
Problem found:
protobuf doesn't support constructing protos from static initalizers.
Here, specificially, the global empty string instance protobuf relies on is not constructed.
Putting OpDef::descriptor() into OpDefBuilderWrapper::operator()() "fixes" the issue.
We need some way for protobuf to support being used from initializers from user code.

**Comment by bhack** [comment]
@r4nt Why It was working in the non RBE env like https://github.com/tensorflow/tensorflow/pull/52853#issuecomment-961860165?

**Comment by meteorcloudy** [comment]
For anyone who's interested in debugging the Windows failure, to reproduce, simply:
```
git clone https://github.com/meteorcloudy/tensorflow.git
cd tensorflow
git fetch origin upgrade_protobuf_grpc
configure
bazel test --announce_rc --config=opt tensorflow/python/grappler:memory_optimizer_test --test_arg=MemoryOptimizerSwapTest.testNoSwapping
```

**Comment by bhack** [comment]
Can you post the error we have in:
`grappler/memory_optimizer_test/test.log` ?

**Comment by meteorcloudy** [comment]
Here is the log, but it doesn't provide much useful information:
```
==================== Test output for //tensorflow/python/grappler:memory_optimizer_test:
Running tests under Python 3.9.7: C:\Python39\python.exe
[ RUN      ] MemoryOptimizerSwapTest.testNoSwapping
2021-11-12 13:58:41.522874: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2021-11-12 13:58:41.525970: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2021-11-12 13:58:41.529455: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Hello world
Windows fatal exception: code 0xc0000374

Current thread 0x00028698 (most recent call first):
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\org_tensorflow\tensorflow\python\grappler\tf_optimizer.py", line 67 in OptimizeGraph
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\org_tensorflow\tensorflow\python\grappler\memory_optimizer_test.py", line 57 in testNoSwapping
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\org_tensorflow\tensorflow\python\framework\test_util.py", line 1532 in decorated
  File "C:\Python39\lib\unittest\case.py", line 550 in _callTestMethod
  File "C:\Python39\lib\unittest\case.py", line 592 in run
  File "C:\Python39\lib\unittest\case.py", line 651 in __call__
  File "C:\Python39\lib\unittest\suite.py", line 122 in run
  File "C:\Python39\lib\unittest\suite.py", line 84 in __call__
  File "C:\Python39\lib\unittest\suite.py", line 122 in run
  File "C:\Python39\lib\unittest\suite.py", line 84 in __call__
  File "C:\Python39\lib\unittest\runner.py", line 176 in run
  File "C:\Python39\lib\unittest\main.py", line 271 in runTests
  File "C:\Python39\lib\unittest\main.py", line 101 in __init__
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\absl_py\absl\testing\absltest.py", line 2553 in _run_and_get_tests_result
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\absl_py\absl\testing\absltest.py", line 2584 in run_tests
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\absl_py\absl\testing\absltest.py", line 2172 in _run_in_app
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\absl_py\absl\testing\absltest.py", line 2065 in main
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\org_tensorflow\tensorflow\python\platform\googletest.py", line 51 in g_main
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\absl_py\absl\app.py", line 258 in _run_main
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\absl_py\absl\app.py", line 312 in run
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\org_tensorflow\tensorflow\python\platform\googletest.py", line 60 in main_wrapper
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\org_tensorflow\tensorflow\python\platform\benchmark.py", line 514 in benchmarks_main
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\org_tensorflow\tensorflow\python\platform\googletest.py", line 62 in main
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\org_tensorflow\tensorflow\python\platform\test.py", line 56 in main
  File "\\?\C:\src\temp\Bazel.runfiles__yzpk26z\runfiles\org_tensorflow\tensorflow\python\grappler\memory_optimizer_test.py", line 325 in <module>
```

I managed to locate the "Windows fatal exception" was triggered at:
https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/python/grappler/tf_optimizer_wrapper.cc;l=98 when calling the constructor of `tensorflow::grappler::MetaOptimizer`

Maybe this problem is related to https://github.com/protocolbuffers/protobuf/issues/7691

**Comment by bhack** [comment]
Mhh, currently I don't have enough resources to compile that target on Qemu.

Is the `dbg`config working for the Windows build?

https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#debug-builds

**Comment by meteorcloudy** [comment]
@bhack Yes, the `--config=dbg` build should work on Windows as well.

**Comment by bhack** [comment]
So can you debug a break point on the suspected section with this `dbg` config and  your fixes?

**Comment by meteorcloudy** [comment]
Figured out an easy way to reproduce this issue, checkout this commit: https://github.com/meteorcloudy/tensorflow/commit/ffb1b5c85a676502146a5dacf107517036f8b84b and run 
```
bazel run --announce_rc --config=opt tensorflow/python/grappler:_pywrap_tf_optimizer.so
```
This way, the python extension thingy isn't involved, and should be easier to debug, but I still have to figure out how to use windbg..

**Comment by bhack** [comment]
> still have to figure out how to use windbg..

If you find a way a reproducible way It could be very useful to add few documenting lines in the `Contributing.md` debug section other then a PR with your branch changes for the Windows debug build configuration fix.

**Comment by meteorcloudy** [comment]
> other then a PR with your branch changes for the Windows debug build configuration fix.

The fix didn't actually work, because it failed at linking _pywrap_tensorflow_internal.so. If it works, I will definitely better document it.

**Comment by bhack** [comment]
I don't know if @reedwm has some feedback on this as he documented that `dbg` build config at:

https://github.com/tensorflow/tensorflow/issues/48919#issuecomment-866438774

**Comment by reedwm** [comment]
I am very unfamiliar with Windows so unfortunately I cannot help much here. Make sure you are using `--config=dbg` and not `-c dbg`. What is the error message you got when linking _pywrap_tensorflow_internal.so?

**Comment by meteorcloudy** [comment]
OK, I found an easy way to reproduce and debug this. In https://github.com/meteorcloudy/tensorflow/commit/61d7c3a4b19903d4fa0f9ff8d7f7e9a1c254eac4, I added a few targets to imitate how the how _pywrap_tf_optimizer link to _pywrap_ternsorflow_internal.pyd (but without actually depending on the actual giant shared library). 
Luckily, the issue can be reproduced, and we can easily build a debuggable binary:
```
bazel run --announce_rc --config=dbg tensorflow/python/grappler:tf_optimizer_wrapper_bin
```

I'm able to get a stack trace in VS:
image

However, my C++ and protobuf knowledge is limited, and this place is likely the victim of some other code that actually corrupted the heap.

@acozzette Do you have any good guess on what's happening here? I suspect it's related to that protobuf is statically linked in both the cc binary and the DLL it depends on. Any suggestion where I should debug into? Context: https://github.com/tensorflow/tensorflow/pull/52853#issuecomment-967138677

**Comment by meteorcloudy** [comment]
@acozzette Maybe something related to https://github.com/protocolbuffers/protobuf/tree/master/cmake#dlls-vs-static-linking? In TF, dynamic link isn't avoidable, and protobuf could be statically linked for each DLL, any suggestion on making them work correctly?

**Comment by acozzette** [comment]
I think you are probably right that this crash has something to do with DLLs. Protobuf has a default string object and decides whether to delete a string or not by comparing a given string pointer with the address of the default string, so if the protobuf runtime is linked in more than one place then there can be more than one default string. This would be consistent with the crash in the stack trace.

It seems to me that there are two possible ways to fix this problem:
- Make sure the protobuf runtime is only linked in one place (so if it's in the DLL then don't link it in the main cc_binary).
- If the runtime has to be linked in more than one place, then try to keep them completely separate (e.g. hide symbols as much as possible and don't pass protos across the DLL boundary).

**Comment by gbaned** [comment]
@meteorcloudy Can you please resolve conflicts? Thanks!

**Comment by mihaimaruseac** [comment]
I think this should now wait for #53234 

@gbaned let's not ping this PR anymore until linked issue above gets resolved, to reduce noise

**Comment by gbaned** [comment]
@meteorcloudy Can you please resolve conflicts? Thanks!

**Comment by bhack** [comment]
Still waiting for https://github.com/tensorflow/tensorflow/issues/53234

**Comment by mihaimaruseac** [comment]
Closing due to https://github.com/tensorflow/tensorflow/commit/84f40925e929d05e72ab9234e53c729224e3af38

**Pull request closed without merging**
