### PR TITLE
Fixed failed building of /pi_examples/label_image.

### PR DESCRIPTION
**Pull request by ghost**
Included <stdio.h> before including <jpeglib.h> because jpeglib.h implicitly requires it.
Cast 'usage' variable to 'const char*' because tensorflow::port::InitMain() function requires C-style string instead of std::string.

### CODE REVIEW

**Comment by drag0** [comment]
@googlebot I signed it!

**Review by vrv — APPROVED** [review]
Looks good, although there are no tests for this so who knows?

@petewarden  :)

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
One more try.  @tensorflow-jenkins test this please

**Comment by vrv** [comment]
Seems like unrelated failures.

**Pull request merged**
