### PR TITLE
[tensorflow/compiler/jit/increase_dynamism_for_auto_jit_pass.cc] Use correct size type for `NumElements` iterator

### PR DESCRIPTION
**Pull request by SamuelMarks**
https://github.com/tensorflow/tensorflow/pull/51739#issuecomment-940389562 told me to split the larger PR into one PR per file; thus this (thanks `bash`, `git` and `gh`!)

### CODE REVIEW

**Comment by SamuelMarks** [comment]
@gbaned @jpienaar Any issue with this PR?

**Comment by gbaned** [comment]
@jpienaar Can you please review this PR ? Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Closing stale PR. Please reopen if still needed and wanting to work on it.

**Comment by SamuelMarks** [comment]
@mihaimaruseac It's not stale, looking at master your latest commit to that file still has the wrong type: https://github.com/tensorflow/tensorflow/blob/dd79e90/tensorflow/compiler/jit/increase_dynamism_for_auto_jit_pass.cc#L80

**Pull request closed without merging**
