### PR TITLE
build: install TensorRT directly in dockerfiles

### PR DESCRIPTION
**Pull request by byronyi**
@angersson I see TRT available in [https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64/](https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64/) so there is no need to install a local repo.

Unfortunately, the case is not true for ppc64le. Ping @tjakob to double-check.

### CODE REVIEW

**Comment by tjakob** [comment]
It is my understanding that NVIDIA has no current plans to upload TensorRT packages for ppc64le.
So the ppc64le check will need to stay.

**Review by angerson — CHANGES_REQUESTED** [review]
Good catch, thank you for this. Can you please regenerate the dockerfiles as well? There are instructions in the README in the `tensorflow/tools/dockerfiles` directory.

**Comment by pooyadavoodi** [comment]
> It is my understanding that NVIDIA has no current plans to upload TensorRT packages for ppc64le.
> So the ppc64le check will need to stay.

@tjakob TRT5.1 GA has ppc64 packages: https://developer.nvidia.com/tensorrt-5136ubuntu-18042ppc64le-gnucuda-101cudnn75.tar.gz

**Comment by byronyi** [comment]
Ping @aaroey; I see 220e8e059a2514567b33cc2614fea0935bd3f631 and I presume this PR is obsolete.

**Comment by tjakob** [comment]
@pooyadavoodi They only have .tar.gz packages for ppc64le (no rpms or debs). So additional work would need to be done for TensorRT and ppc64le (pulling that tar file, and extracting it to the correct location).

**Comment by aaroey** [comment]
@byronyi that commit was rolled back and I'll redo that later.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
