### PR TITLE
Fix exception causes in session.py

### PR DESCRIPTION
**Pull request by cool-RR**
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706) and [Pandas](https://github.com/pandas-dev/pandas/pull/32322), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now.

The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.

Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a more accurate message between the tracebacks. Instead of this:

```
During handling of the above exception, another exception occurred:
```

You'll get this:

```
The above exception was the direct cause of the following exception:
```

The first is inaccurate, because it signifies a bug in the exception-handling code itself, which is a separate situation than wrapping an exception.

Let me know what you think!

### CODE REVIEW

**Comment by mrry** [comment]
@cool-RR Thanks for this change! Am I right in thinking that this chaining syntax is only available in Python 3? Would `six.raise_from()` work in this case?

@martinwicke Do we have a timeline for accepting changes that use Python 3 features?

**Comment by cool-RR** [comment]
@mrry You're welcome, yes and yes.

**Comment by mrry** [comment]
Great! Would you mind switching the PR to use `six.raise_from()` and then I'd be happy to approve the change?

**Comment by cool-RR** [comment]
Yep, done. Just curious though, [looking here](https://www.tensorflow.org/install/pip) it says that Python 3.5+ is required. What reason is there to avoid native Python 3 syntax like `raise foo from bar`?

**Review by mrry — DISMISSED** [review]

**Comment by mrry** [comment]
Thanks! Yes, I was hoping @martinwicke could clarify our policy on that. Even though we are no longer building PIP packages for Python 2.7, I believe we still have a few non-PIP users that are stuck on that version of Python, which prevents us from adopting new syntax (just yet).

**Comment by cool-RR** [comment]
@mrry: I understand. I'll wait with fixing this problem in the entire project until after you've moved to Python 3 completely, so we could switch straight to `raise foo from bar`. (Assuming I won't be too busy then.) Once you've left Python 2 completely, feel free to send me a message here.

**Comment by gbaned** [comment]
@cool-RR Any update on this PR, please. Thanks!

**Comment by cool-RR** [comment]
@gbaned See my last message.

**Comment by gbaned** [comment]
@mrry  Any update on this PR, please. Thanks!

**Comment by mrry** [comment]
@gbaned: See @cool-RR's last message. This PR is on hold until we get confirmation that TensorFlow can use Python 3–specific features.

**Comment by gbaned** [comment]
@mrry, @cool-RR  This PR is in draft, any update on this? Please. Thanks!

**Comment by cool-RR** [comment]
@gbaned I moved this PR to ready state now. As far as I'm concerned we can move forward, just need confirmation that Python 2 support is dropped in TensorFlow.

Here's a blog post I made where I explained my effort to push this Python 3 syntax in many open-source packages: https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with

There's now a PyLint rule that checks for this syntax.

**Comment by gbaned** [comment]
@mrry Can you please take a look on the above comment from @cool-RR. Thanks!

**Comment by martinwicke** [comment]
@cool-RR We are soooo close to being able to actually using Python3-only syntax. I'm re-running the tests and I will merge this if I can using the six as is. 

@ematejska FYI this would make a good test case whether we can really break Py2.

**Review by martinwicke — DISMISSED** [review]

**Comment by gbaned** [comment]
@cool-RR Can you please check build failures. Thank you!

**Comment by cool-RR** [comment]
@gbaned I rebased and pushed. It's been 4 hours and the CI hasn't started running yet. Is this normal?

**Comment by martinwicke** [comment]
triggered it now

**Comment by gbaned** [comment]
@cool-RR Still, build failures are appearing, can you please fix those?. Thank you!

**Comment by cool-RR** [comment]
Looks like you have a test `test_propagates_exception_trace` that checks things I don't understand about the exception traceback. Looks like @yifeif wrote it. Yifey, if you have a solution here, let me know. Otherwise this is getting too hairy for me.

**Comment by yifeif** [comment]
Took a brief look, and seems like six changed the exception string, and you might need to update the test to reflect that. Here is the current error from CI
```
AssertionError: '<string>' not found in ['session.py', 'monitored_session.py'] : The exception was raised from an unrecognized file. This unit test probably needs to be updated. Traceback:
[<FrameSummary file /b/f/w/bazel-out/k8-opt/bin/tensorflow/python/monitored_session_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session_test.py, line 750 in test_propagates_exception_trace>, <FrameSummary file /b/f/w/bazel-out/k8-opt/bin/tensorflow/python/monitored_session_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py, line 1384 in run>, <FrameSummary file /b/f/w/bazel-out/k8-opt/bin/tensorflow/python/monitored_session_test.runfiles/six_archive/six.py, line 703 in reraise>, <FrameSummary file /b/f/w/bazel-out/k8-opt/bin/tensorflow/python/monitored_session_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py, line 1369 in run>, <FrameSummary file /b/f/w/bazel-out/k8-opt/bin/tensorflow/python/monitored_session_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py, line 1689 in run>, <FrameSummary file /b/f/w/bazel-out/k8-opt/bin/tensorflow/python/monitored_session_test.runfiles/org_tensorflow/tensorflow/python/client/session.py, line 976 in run>, <FrameSummary file /b/f/w/bazel-out/k8-opt/bin/tensorflow/python/monitored_session_test.runfiles/org_tensorflow/tensorflow/python/client/session.py, line 1202 in _run>, <FrameSummary file /b/f/w/bazel-out/k8-opt/bin/tensorflow/python/monitored_session_test.runfiles/org_tensorflow/tensorflow/python/client/session.py, line 1380 in _do_run>, <FrameSummary file /b/f/w/bazel-out/k8-opt/bin/tensorflow/python/monitored_session_test.runfiles/org_tensorflow/tensorflow/python/client/session.py, line 1407 in _do_call>, <FrameSummary file <string>, line 3 in raise_from>]
```
Here is where the test was getting the name of the file exception was raised from (where the change needs to be made),
https://github.com/tensorflow/tensorflow/blob/f618ab49554dba03c104ef27cea5d893063fd373/tensorflow/python/training/monitored_session_test.py#L756

**Comment by cool-RR** [comment]
I'm gonna bow out, this is getting too complicated for me.

**Pull request closed without merging**
