### PR TITLE
11055: test to reproduce Keras load model raises ValueError when loading optimizer weights

### PR DESCRIPTION
**Pull request by kevinjos**

### CODE REVIEW

**Comment by kevinjos** [comment]
I signed it!

**Comment by drpngx** [comment]
@fchollet this is a repro case for #11055, not a merge request.

**Comment by fchollet** [comment]
Thanks for the report. I have identified the cause and will fix it. It's a bit of an edge case. As a temporary workaround, you can skip the optimizer loading step when loading your model, by passing `compile=False` to `load_model`.

**Comment by kevinjos** [comment]
Thank you for looking into it! I look forward to reading the patch.

**Comment by fchollet** [comment]
This has been fixed in upstream Keras. We will backport the fix to TensorFlow in a few days.

**Comment by kevinjos** [comment]
@fchollet, shall I apply the fix to this PR? I saw in the Keras repo that simply removing the sort of the trainable weights by name fixes the serialization bug.

Also, I have noticed that if I load the model with compile=False or delete the optimizer weights before loading the model that the Exception is not raised. However, the loaded model predictions preform as if the model was not trained at all. I don't understand how this could be.. I am retraining the model with this bug fix applied now to see if it's related or not.

**Comment by vrv** [comment]
Closing since this is probably better as an issue filed in Keras at this point.  Thanks for the help @kevinjos !!

**Pull request closed without merging**
