### PR TITLE
Sync Branch 175311543

### PR DESCRIPTION
**Pull request by aselle**
@tensorflow-jenkins test this please

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
@gunan do you know where these tensorflow-jenkins "SUCCESS" messages come from? They're new, and confusing, because wrong.

**Comment by aselle** [comment]
@tensorflow-jenkins test this please

**Comment by gunan** [comment]
I am investigating, not sure what changed in our jenkins config.

**Comment by gunan** [comment]
I made some changes on Jenkins config,
Let me know if it helps or not with Jenkins spamming review threads.

**Comment by martinwicke** [comment]
I'll close this, we have to fix a merge accident first. I'll let you know.

**Pull request closed without merging**
