### PR TITLE
Solved for MNIST file downloading problem

### PR DESCRIPTION
**Pull request by tibrewalpratik17**
A lot of folks (#6742, #8126, #8134,#8116) were having trouble regarding this issue. Even I faced it today while writing the MNIST code as the mnist.py was unable to connect with the source url. I downloaded the files and pasted it in the folder containing the code and made some changes in the code which solves the need for connecting it to the website. Hope so this works out.

### CODE REVIEW

**Comment by tibrewalpratik17** [comment]
I signed it!

**Review by caisq — COMMENTED** [review]
Sorry, but I don't think this will work. The point of this module is so that data files can be downloaded automatically if they don't exist on local file system. If the files exist, the download won't happen.

But the change you made here disables the downloading, requiring all users to download the files manually. This is both cumbersome and backward incompatible.

We don't want to include the data files in the git repo either, because of file size issue and licensing issues.

So I'll close this PR. If you have questions or other comments, please let me know. Thanks.

**Comment by tibrewalpratik17** [comment]
Hello @caisq , the website is not allowing us to connect what is the solution now?

**Comment by caisq** [comment]
Sorry - I'm confused what you mean by the website not allowing you to connect. I just tried

```
wget --spider https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz
wget --spider https://storage.googleapis.com/cvdf-datasets/mnist/train-labels-idx1-ubyte.gz
wget --spider https://storage.googleapis.com/cvdf-datasets/mnist/t10k-images-idx3-ubyte.gz
wget --spider https://storage.googleapis.com/cvdf-datasets/mnist/t10k-labels-idx1-ubyte.gz
```

The commands all work, indicating remote files exist.

**Comment by tibrewalpratik17** [comment]
I am getting the following output

`Traceback (most recent call last):
  File "mnist_softmax.py", line 79, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/pratik/tensorflow/venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "mnist_softmax.py", line 37, in main
    mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)
  File "/home/pratik/tensorflow/venv/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 240, in read_data_sets
    source_url + TRAIN_IMAGES)
  File "/home/pratik/tensorflow/venv/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 208, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "/home/pratik/tensorflow/venv/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 165, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/pratik/tensorflow/venv/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 190, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol`

**Comment by caisq** [comment]
This seems to be a network connectivity problem specific to you.

**Comment by tibrewalpratik17** [comment]
Well at first I thought it was due to some proxy configuration settings but now turning off all proxies and switching my connection to another network..it shows
 `IOError: [Errno socket error] [Errno 111] Connection refused`

**Pull request closed without merging**
