### PR TITLE
Removed .combat.v1. method in the example.

### PR DESCRIPTION
**Pull request by nagellette**
As a resolution to #24524 , old code is removed to get the correct results as show in the tensorflow [tutorial](https://www.tensorflow.org/tutorials/estimators/cnn#load_training_and_test_data)

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @xiejw: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by xiejw** [comment]
@karmel do you know who owns the tutorial update? I had little knowledge about the new API in v2 module.

**Comment by karmel** [comment]
This particular tutorial has been auto-updated to 2.0-compatible code, so the compat.v1 is correct; you can try running with the 2.0 preview to fix the error linked above (`pip install --upgrade tf-nightly-2.0-preview`). That said, I believe this particular example will eventually be removed, as it is no longer current. Consider taking a look at the [official MNIST](https://github.com/tensorflow/models/tree/master/official/mnist#mnist-in-tensorflow).

**Pull request closed without merging**
