### PR TITLE
Add uint8 support for Pad with GPU

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address some of the issue raised in #17823,
where Pad with GPU does not support uint8. This fix adds the uint8 support.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by wujingyue — APPROVED** [review]
Thanks!

**Comment by ymodak** [comment]
@yongtang Can you please approve this PR? Thanks!

**Comment by yongtang** [comment]
@yongtang I think the PR has been approved by @wujingyue?

**Comment by yongtang** [comment]
@ymodak I think the PR has been approved by @wujingyue.

**Comment by yongtang** [comment]
@ymodak Any update to this PR, or is there anything else I need to do?

**Comment by patricksnape** [comment]
@yongtang Given how simple this implementation looks - do you think it would be the same to extend uint8 functionality to strided slice to close off #17823?

**Pull request merged**
