### PR TITLE
Branch 162658391

### PR DESCRIPTION
**Pull request by jhseu**

### CODE REVIEW

**Comment by jhseu** [comment]
Jenkins, test this please

**Review by frankchn — APPROVED** [review]

**Comment by ebrevdo** [comment]
Flakiness in spectral ops test:

```
FAIL: //tensorflow/contrib/signal:spectral_ops_test (see /private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/testlogs/tensorflow/contrib/signal/spectral_ops_test/test.log).
INFO: From Testing //tensorflow/contrib/signal:spectral_ops_test:
==================== Test output for //tensorflow/contrib/signal:spectral_ops_test:
2017-07-20 21:05:37.224871: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 21:05:37.224894: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
.F....
======================================================================
FAIL: test_gradients_numerical (__main__.SpectralOpsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/bin/tensorflow/contrib/signal/spectral_ops_test.runfiles/org_tensorflow/tensorflow/contrib/signal/python/kernel_tests/spectral_ops_test.py", line 245, in test_gradients_numerical
    self.assertLess(stft_error, stft_bound)
AssertionError: 0.00093367695808410645 not less than 0.0008

----------------------------------------------------------------------
Ran 6 tests in 46.787s

FAILED (failures=1)**
```

@rryan

**Comment by ebrevdo** [comment]
Flakiness in custom_grad_test in bayesflow:

```
FAIL: //tensorflow/contrib/bayesflow:custom_grad_test (see /private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/testlogs/tensorflow/contrib/bayesflow/custom_grad_test/test.log).
INFO: From Testing //tensorflow/contrib/bayesflow:custom_grad_test:
==================== Test output for //tensorflow/contrib/bayesflow:custom_grad_test:
.2017-07-20 21:06:37.116599: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 21:06:37.116621: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
FF...
======================================================================
FAIL: test_works_correctly (__main__.CustomGradientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/bin/tensorflow/contrib/bayesflow/custom_grad_test.runfiles/org_tensorflow/tensorflow/contrib/bayesflow/python/kernel_tests/custom_grad_test.py", line 51, in test_works_correctly
    self.assertAllEqual(f(x_), fx_)
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/bin/tensorflow/contrib/bayesflow/custom_grad_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 752, in assertAllEqual
    np.testing.assert_array_equal(b, a)
  File "/usr/local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-macosx-10.11-x86_64.egg/numpy/testing/utils.py", line 813, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-macosx-10.11-x86_64.egg/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 0.26%)
 x: array([ 5000.    ,  4998.    ,  4996.0004, ...,  4996.0004,  4998.    ,
        5000.    ])
 y: array([ 5000.    ,  4998.    ,  4996.0004, ...,  4996.0004,  4998.    ,
        5000.    ])

======================================================================
FAIL: test_works_correctly_both_f_g_zero (__main__.CustomGradientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/bin/tensorflow/contrib/bayesflow/custom_grad_test.runfiles/org_tensorflow/tensorflow/contrib/bayesflow/python/kernel_tests/custom_grad_test.py", line 65, in test_works_correctly_both_f_g_zero
    self.assertAllEqual(f(x_), fx_)
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/bin/tensorflow/contrib/bayesflow/custom_grad_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 752, in assertAllEqual
    np.testing.assert_array_equal(b, a)
  File "/usr/local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-macosx-10.11-x86_64.egg/numpy/testing/utils.py", line 813, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-macosx-10.11-x86_64.egg/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 0.26%)
 x: array([ 5000.    ,  4998.    ,  4996.0004, ...,  4996.0004,  4998.    ,
        5000.    ])
 y: array([ 5000.    ,  4998.    ,  4996.0004, ...,  4996.0004,  4998.    ,
        5000.    ])

----------------------------------------------------------------------
Ran 6 tests in 0.376s

FAILED (failures=2)
not equal where =  (array([ 560,  753,  896,  958, 1117, 1796, 2137, 2229, 2397, 2801, 2977,
       3334, 4569, 4667, 4902, 5430, 5788, 6575, 7602, 7862, 8203, 8783,
       8882, 9041, 9246, 9457]),)
not equal lhs =  [  3.94262053e+03   3.60727387e+03   3.36841610e+03   3.26739790e+03
   3.01536429e+03   2.05289301e+03   1.63910906e+03   1.53544112e+03
   1.35487221e+03   9.66873815e+02   8.18264895e+02   5.54889022e+02
   3.70734643e+01   2.21156729e+01   1.90163031e+00   3.70734643e+01
   1.24371323e+02   4.96539353e+02   1.35487221e+03   1.63910906e+03
   2.05289301e+03   2.86354713e+03   3.01536429e+03   3.26739790e+03
   3.60727387e+03   3.97465614e+03]
not equal rhs =  [  3.94262053e+03   3.60727387e+03   3.36841610e+03   3.26739790e+03
   3.01536429e+03   2.05289301e+03   1.63910906e+03   1.53544112e+03
   1.35487221e+03   9.66873815e+02   8.18264895e+02   5.54889022e+02
   3.70734643e+01   2.21156729e+01   1.90163031e+00   3.70734643e+01
   1.24371323e+02   4.96539353e+02   1.35487221e+03   1.63910906e+03
   2.05289301e+03   2.86354713e+03   3.01536429e+03   3.26739790e+03
   3.60727387e+03   3.97465614e+03]
not equal where =  (array([ 560,  753,  896,  958, 1117, 1796, 2137, 2229, 2397, 2801, 2977,
       3334, 4569, 4667, 4902, 5430, 5788, 6575, 7602, 7862, 8203, 8783,
       8882, 9041, 9246, 9457]),)
not equal lhs =  [  3.94262053e+03   3.60727387e+03   3.36841610e+03   3.26739790e+03
   3.01536429e+03   2.05289301e+03   1.63910906e+03   1.53544112e+03
   1.35487221e+03   9.66873815e+02   8.18264895e+02   5.54889022e+02
   3.70734643e+01   2.21156729e+01   1.90163031e+00   3.70734643e+01
   1.24371323e+02   4.96539353e+02   1.35487221e+03   1.63910906e+03
   2.05289301e+03   2.86354713e+03   3.01536429e+03   3.26739790e+03
   3.60727387e+03   3.97465614e+03]
not equal rhs =  [  3.94262053e+03   3.60727387e+03   3.36841610e+03   3.26739790e+03
   3.01536429e+03   2.05289301e+03   1.63910906e+03   1.53544112e+03
   1.35487221e+03   9.66873815e+02   8.18264895e+02   5.54889022e+02
   3.70734643e+01   2.21156729e+01   1.90163031e+00   3.70734643e+01
   1.24371323e+02   4.96539353e+02   1.35487221e+03   1.63910906e+03
   2.05289301e+03   2.86354713e+03   3.01536429e+03   3.26739790e+03
   3.60727387e+03   3.97465614e+03]
================================================================================
```

@jvdillon

**Review by agarwal-ashish — APPROVED** [review]
Looks good for contrib/timeseries changes.

**Comment by jvdillon** [comment]
On Thu, Jul 20, 2017 at 2:56 PM, ebrevdo <notifications@github.com> wrote:

> Flakiness in custom_grad_test in bayesflow:
>
> FAIL: //tensorflow/contrib/bayesflow:custom_grad_test (see /private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/testlogs/tensorflow/contrib/bayesflow/custom_grad_test/test.log).
> INFO: From Testing //tensorflow/contrib/bayesflow:custom_grad_test:
> ==================== Test output for //tensorflow/contrib/bayesflow:custom_grad_test:
> .2017-07-20 21:06:37.116599: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-07-20 21:06:37.116621: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
> FF...
> ======================================================================
> FAIL: test_works_correctly (__main__.CustomGradientTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/bin/tensorflow/contrib/bayesflow/custom_grad_test.runfiles/org_tensorflow/tensorflow/contrib/bayesflow/python/kernel_tests/custom_grad_test.py", line 51, in test_works_correctly
>     self.assertAllEqual(f(x_), fx_)
>   File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/bin/tensorflow/contrib/bayesflow/custom_grad_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 752, in assertAllEqual
>     np.testing.assert_array_equal(b, a)
>   File "/usr/local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-macosx-10.11-x86_64.egg/numpy/testing/utils.py", line 813, in assert_array_equal
>     verbose=verbose, header='Arrays are not equal')
>   File "/usr/local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-macosx-10.11-x86_64.egg/numpy/testing/utils.py", line 739, in assert_array_compare
>     raise AssertionError(msg)
> AssertionError:
> Arrays are not equal
>
> (mismatch 0.26%)
>  x: array([ 5000.    ,  4998.    ,  4996.0004, ...,  4996.0004,  4998.    ,
>         5000.    ])
>  y: array([ 5000.    ,  4998.    ,  4996.0004, ...,  4996.0004,  4998.    ,
>         5000.    ])
>
> ======================================================================
> FAIL: test_works_correctly_both_f_g_zero (__main__.CustomGradientTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/bin/tensorflow/contrib/bayesflow/custom_grad_test.runfiles/org_tensorflow/tensorflow/contrib/bayesflow/python/kernel_tests/custom_grad_test.py", line 65, in test_works_correctly_both_f_g_zero
>     self.assertAllEqual(f(x_), fx_)
>   File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/darwin_x86_64-opt/bin/tensorflow/contrib/bayesflow/custom_grad_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 752, in assertAllEqual
>     np.testing.assert_array_equal(b, a)
>   File "/usr/local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-macosx-10.11-x86_64.egg/numpy/testing/utils.py", line 813, in assert_array_equal
>     verbose=verbose, header='Arrays are not equal')
>   File "/usr/local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-macosx-10.11-x86_64.egg/numpy/testing/utils.py", line 739, in assert_array_compare
>     raise AssertionError(msg)
> AssertionError:
> Arrays are not equal
>
> (mismatch 0.26%)
>  x: array([ 5000.    ,  4998.    ,  4996.0004, ...,  4996.0004,  4998.    ,
>         5000.    ])
>  y: array([ 5000.    ,  4998.    ,  4996.0004, ...,  4996.0004,  4998.    ,
>         5000.    ])
>
> ----------------------------------------------------------------------
> Ran 6 tests in 0.376s
>
> FAILED (failures=2)
> not equal where =  (array([ 560,  753,  896,  958, 1117, 1796, 2137, 2229, 2397, 2801, 2977,
>        3334, 4569, 4667, 4902, 5430, 5788, 6575, 7602, 7862, 8203, 8783,
>        8882, 9041, 9246, 9457]),)
> not equal lhs =  [  3.94262053e+03   3.60727387e+03   3.36841610e+03   3.26739790e+03
>    3.01536429e+03   2.05289301e+03   1.63910906e+03   1.53544112e+03
>    1.35487221e+03   9.66873815e+02   8.18264895e+02   5.54889022e+02
>    3.70734643e+01   2.21156729e+01   1.90163031e+00   3.70734643e+01
>    1.24371323e+02   4.96539353e+02   1.35487221e+03   1.63910906e+03
>    2.05289301e+03   2.86354713e+03   3.01536429e+03   3.26739790e+03
>    3.60727387e+03   3.97465614e+03]
> not equal rhs =  [  3.94262053e+03   3.60727387e+03   3.36841610e+03   3.26739790e+03
>    3.01536429e+03   2.05289301e+03   1.63910906e+03   1.53544112e+03
>    1.35487221e+03   9.66873815e+02   8.18264895e+02   5.54889022e+02
>    3.70734643e+01   2.21156729e+01   1.90163031e+00   3.70734643e+01
>    1.24371323e+02   4.96539353e+02   1.35487221e+03   1.63910906e+03
>    2.05289301e+03   2.86354713e+03   3.01536429e+03   3.26739790e+03
>    3.60727387e+03   3.97465614e+03]
> not equal where =  (array([ 560,  753,  896,  958, 1117, 1796, 2137, 2229, 2397, 2801, 2977,
>        3334, 4569, 4667, 4902, 5430, 5788, 6575, 7602, 7862, 8203, 8783,
>        8882, 9041, 9246, 9457]),)
> not equal lhs =  [  3.94262053e+03   3.60727387e+03   3.36841610e+03   3.26739790e+03
>    3.01536429e+03   2.05289301e+03   1.63910906e+03   1.53544112e+03
>    1.35487221e+03   9.66873815e+02   8.18264895e+02   5.54889022e+02
>    3.70734643e+01   2.21156729e+01   1.90163031e+00   3.70734643e+01
>    1.24371323e+02   4.96539353e+02   1.35487221e+03   1.63910906e+03
>    2.05289301e+03   2.86354713e+03   3.01536429e+03   3.26739790e+03
>    3.60727387e+03   3.97465614e+03]
> not equal rhs =  [  3.94262053e+03   3.60727387e+03   3.36841610e+03   3.26739790e+03
>    3.01536429e+03   2.05289301e+03   1.63910906e+03   1.53544112e+03
>    1.35487221e+03   9.66873815e+02   8.18264895e+02   5.54889022e+02
>    3.70734643e+01   2.21156729e+01   1.90163031e+00   3.70734643e+01
>    1.24371323e+02   4.96539353e+02   1.35487221e+03   1.63910906e+03
>    2.05289301e+03   2.86354713e+03   3.01536429e+03   3.26739790e+03
>    3.60727387e+03   3.97465614e+03]
> ================================================================================
>
> @jvdillon <https://github.com/jvdillon>
>

Grr. Looks like some compiler is not IEEE754 compliant. Ill need to change
assertAllEqual to assertAllClose. Sending out cl shortly.

**Pull request closed without merging**
