### PR TITLE
Make verbosity of fit generator available for validation

### PR DESCRIPTION
**Pull request by lukasfolle**
Fixing #31074.
Creating another variable as an option to control the verbosity of the validation in `fit_generator` would probably be confusing -> `verbose` now would controll both

### CODE REVIEW

**Comment by lufol** [comment]
@gbaned  Could you possibly assign a new reviewer as the last update is past almost a week?

**Review by tanzhenyu — DISMISSED** [review]
You might want to change that for training_arrays as well.

**Review by lukasfolle — COMMENTED** [review]
5d32478 inlcudes the fix for `training_arrays` as well.

**Comment by lufol** [comment]
@tanzhenyu could you please review again?

**Review by tanzhenyu — APPROVED** [review]

**Comment by lufol** [comment]
The "feedback/copybara" check seems to fail. Can I do something about it?

**Pull request merged**
