### PR TITLE
Fix multiple values for keyword argument error in ModelAverageOptimizer and ElasticAverageOptimizer

### PR DESCRIPTION
**Pull request by jinxin0924**
Fix multiple values for keyword argument error in ModelAverageOptimizer and ElasticAverageOptimz. 
For detailed error, please look at [here](https://github.com/tensorflow/tensorflow/issues/19617)

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by martinwicke — DISMISSED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by alextp — APPROVED** [review]

**Pull request merged**
