### PR TITLE
[ROCm] Gelu op

### PR DESCRIPTION
**Pull request by ekuznetsov139**
This PR creates a kernel-based Gelu activation op (which offers a substantial speedup over a basic Python implementation).

### CODE REVIEW

**Review by alextp — CHANGES_REQUESTED** [review]
Why do we need this in core TF? Can this live in tf addons?

**Comment by alextp** [comment]
And can we replace this kernel implementation with a tf.function(experimental_compile=True) so we use XLA to generate the kernel implementation?

**Comment by ekuznetsov139** [comment]
There are already numerous other activations in TF core, what's one more? 
And Gelu is arguably more important than some of the existing activations (like e.g. Selu) because it's used by BERT.

It is part of the standard API in PyTorch: https://pytorch.org/docs/stable/nn.html#torch.nn.GELU

I am not familiar with experimental_compile, it's worth testing, but we can merge this now and replace the kernel with Python+XLA later when it is confirmed to work correctly and match performance.

**Comment by bhack** [comment]
See also https://github.com/tensorflow/tensorflow/pull/33945 /cc @WindQAQ
@alextp Why with `tf.function` the backward seems so slow? See https://github.com/tensorflow/addons/issues/1722#issuecomment-619447106?

**Comment by alextp** [comment]
To merge this we need the kernels for higher order derivatives. Without running a profiler though I can't tell why the backward step is slow. Can you tun the TPU profiler and post screenshots of a trace here?

**Comment by bhack** [comment]
> There are already numerous other activations in TF core, what's one more?

@ekuznetsov139  we had already this activation available in Tensorflow Addons and we was trying to upstream to core at https://github.com/tensorflow/tensorflow/pull/33945. We have a specific process for this [upstreaming activity documented](https://github.com/tensorflow/addons/blob/master/MIGRATION_TO_CORE.md).
In the meantime we are discussing about GELU (and other activations) custom kernel implementation removal for a python only composite ops at https://github.com/tensorflow/addons/issues/1752

**Comment by rthadur** [comment]
Closing this as there is already PR opened [here](https://github.com/tensorflow/tensorflow/pull/33945) , thank you for your contribution.

**Pull request closed without merging**
