### PR TITLE
[hlo] instruction_fusion: optimization of DFS traversal, visited node…

### PR DESCRIPTION
**Pull request by lipracer**
…s end in advance

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @r4nt Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @r4nt Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @cheshire Can you please review this PR ? Thank you!

**Comment by cheshire** [comment]
Could you describe the behavior change in this CL? Why does it make the traversal faster?

**Comment by lipracer** [comment]
If the ```user``` is already in the```visits```,the follow statement 
```
    if (operands.count(user->unique_id()) != 0) {
      return true;
    }
```
is redundant.

**Comment by lipracer** [comment]
> Could you describe the behavior change in this CL? Why does it make the traversal faster?

If the ```user``` is already in the```visits```,the follow statement 
```
    if (operands.count(user->unique_id()) != 0) {
      return true;
    }
```
is redundant.

**Comment by gbaned** [comment]
Hi @cheshire Can you please review this PR ? Thank you!

**Pull request closed without merging**
