### PR TITLE
add/update comments for word2vec_basic.py

### PR DESCRIPTION
**Pull request by Albert-Z-Guo**
refine comments and provide further references for curious reader

### CODE REVIEW

**Comment by gbaned** [comment]
@Albert-Z-Guo  please sign CLA

**Comment by Albert-Z-Guo** [comment]
OK. I have signed the CLA.

**Comment by gbaned** [comment]
@aselle, @drpngx  Could you PTAL and approve.

**Comment by tensorflowbutler** [comment]
Nagging Reviewers @aselle, @ebrevdo: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Review by frankchn — APPROVED** [review]

**Pull request merged**
