### PR TITLE
[TF C API] Added TF_GetMutableOutput C API

### PR DESCRIPTION
**Pull request by cramasam**
C API to get the mutable output tensor is missing. This API is required by the TF Plugin for forwarding the input to output.

Signed-off-by: Chandra Kumar Ramasamy <ChandraKumar.Ramasamy@amd.com>
Reviewed-by: Aakar Dwivedi <Aakar.Dwivedi@amd.com>

### CODE REVIEW

**Comment by gbaned** [comment]
@cramasam Can you please resolve conflicts? Thank you!

**Comment by cramasam** [comment]
> @cramasam Can you please resolve conflicts? Thank you!

I have resolved the conflicts. Thank you.

**Review by sagunb — APPROVED** [review]
Thanks for the PR! No issues.

**Pull request merged**
