### PR TITLE
Add support for ppc64le_dockerfiles

### PR DESCRIPTION
**Pull request by tjakob**
Add support for ppc64le dockerfiles with newest assembler changes.

The `LIB_DIR_PREFIX` arg could be removed by adding a couple `if` to `nvidia-devel.partial`
Moved the tools.Dockerfile to ubuntu:16.04 because all of the architectures in get.docker.com support ubuntu:xenial, but not all of them support debian:stretch.

### CODE REVIEW

**Comment by tjakob** [comment]
@jayfurmanek @wdirons @angersson

**Review by angerson — CHANGES_REQUESTED** [review]
Thanks for working on this (especially for the typo fixes). I have some changes to request, though.

* Can you move the ppc64le slices to their own `slice_set`s and `release`? That'll help us with encapsulation, especially since I don't know if we'd be pushing these yet (+@gunan)

@tfboyd Do these `${CUDA}` variable expansions look good to you? I don't know how versions change, so I don't know if we'd need a bunch of manual updates or not. Also, should our regular Dockerfiles use 9.2 or does it not matter (since 10.0 is coming soon)?

**Comment by jayfurmanek** [comment]
Nvidia's cuda packages historically have used the naming:

```
[package]-[cuda version major]-[cuda version minor]
```
And then the version of the package has the full version number.
For example:
```
cuda-toolkit-10-0-10.0.130-1.ppc64le
```

So the cuda expansion vars look ok to me. 
I'd also say we just move these to cuda10 since, as just discussed in the build SIG mtg, it sounds like cuda10 is the target for 1.13.

**Comment by angersson** [comment]
Some other notes from discussing with @gunan:

- I'm going to make some quick changes to support output directories, so that the ppc dockerfiles all go in a subdirectory.
- Are you planning to use the builder-assembler features to build these images? We're not planning to host them on tensorflow/tensorflow (which is what `nightly` and `release` are for), so if you're planning to build the resulting Dockerfiles yourself, you can mark them as dockerfiles-only. Otherwise, you can make your own release for easier filtering (I'll update the docs, too).

**Comment by tjakob** [comment]
Once I see an update for output directories, I'll update my patch.
Updated patch will use cuda 10.0 for both x86 and ppc64le docker files, create an "ubuntu-ppc64le" slice_set, and "ubuntu-ppc64le-dockerfiles" release.

We don't plan on using the assembler to build/publish the images (yet).

**Comment by angersson** [comment]
I made https://github.com/tensorflow/tensorflow/pull/24206 to support subdirectories.

**Comment by tjakob** [comment]
I added a new ARG (CACHE_STOP) before we pull down tensorflow (either in .whl or git clone).
Without this, docker will cache the RUN command, and you will get the same version of tensorflow for each build.
@angersson How are you planning on getting around this issue when you pip install tensorflow (and other packages)?

**Comment by angersson** [comment]
@tjakob our CI does everything from scratch and doesn't have a cache from previous builds, so I don't think it's an issue on our end.

**Comment by tjakob** [comment]
@angersson Was there anything else that you and/or @gunan wanted changed?

**Comment by angersson** [comment]
@tjakob Sorry for making you wait; our build infra has been finicky. I'm working on verifying that our new CI for Docker works before accepting new Docker-related PRs; it'll take a bit longer before I can get back to this.

**Comment by angersson** [comment]
This looks better now, thanks. Can you pull in the latest changes and rebuild?

**Comment by tjakob** [comment]
@angersson Is there any update on when you'll be ready to merge this PR?

**Comment by angersson** [comment]
Sorry for the wait. This looks good, but I'd like to wait until the 1.13 release is complete to make sure there's only one thing going on with the Dockerfiles at once.

**Review by angerson — DISMISSED** [review]

**Comment by angersson** [comment]
Finally merged. Thanks for your patience, @tjakob!

**Pull request merged**
