### PR TITLE
Fixing Broken Link

### PR DESCRIPTION
**Pull request by johcarvajal**
Fixed broked links

### CODE REVIEW

**Comment by johcarvajal** [comment]
I fixed C++ documentation links

**Comment by girving** [comment]
@martinwicke: Are these files autogenerated?

**Comment by chemelnucfin** [comment]
@girving @martinwicke I think those files are autogenerated and we both made changes which should have fixed the links.  Do you need to run something internally and push to production?  This also references the comment @girving made on #1303

**Comment by martinwicke** [comment]
I need to redeploy the website. Otherwise this should be fixed.

**Pull request closed without merging**
