### PR TITLE
Fix MPI build failure caused by StringPiece -> absl::string_view

### LINKED ISSUE #22376: Failed to build TF from source with MPI support
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04 LTS
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.11.0-rc0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.17.1
- **GCC/Compiler version (if compiling from source)**: 7.3.0
- **CUDA/cuDNN version**: 9.2/7.2
- **GPU model and memory**: Asus GTX 1080Ti
- **Exact command to reproduce**: See below

### Describe the problem
I canno't seem to compile tensorflow from source when I try to enable MPI support. The build always fails.
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/stefan/.cache/bazel/_bazel_stefan/install/28c1d2ace0add449e21862ae9f2d2289/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.17.1 installed.
Please specify the location of python. [Default is /home/stefan/.tmp/venv3/bin/python]: 


Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'
Found possible Python library paths:
  /home/stefan/.tmp/venv3/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/stefan/.tmp/venv3/lib/python3.6/site-packages]

Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: 
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: 
Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: 
Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Amazon AWS Platform support? [Y/n]: 
Amazon AWS Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Apache Kafka Platform support? [Y/n]: 
Apache Kafka Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: 
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: 
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: 
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with nGraph support? [y/N]: 
No nGraph support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]: 9.2


Please specify the location where CUDA 9.2 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7.0]: 7.2


Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 


Do you wish to build TensorFlow with TensorRT support? [y/N]: 
No TensorRT support will be enabled for TensorFlow.

Please specify the NCCL version you want to use. If NCCL 2.2 is not installed, then you can use version 1.3 that can be fetched automatically but it may have worse performance with multiple GPUs. [Default is 2.2]: 


Please specify the location where NCCL 2 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:/usr/local/cuda/nccl


Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 6.1]: 


Do you want to use clang as CUDA compiler? [y/N]: 
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 


Do you wish to build TensorFlow with MPI support? [y/N]: y
MPI support will be enabled for TensorFlow.

Please specify the MPI toolkit folder. [Default is /usr/local]: 


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: 
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
Configuration finished
```
This is my configuration. Note that the build succeeds with MPI set to no.
Error message when build fails:
```
ERROR: /home/stefan/.tmp/tensorflow/tensorflow/contrib/mpi/BUILD:60:1: C++ compilation of rule '//tensorflow/contrib/mpi:mpi_rendezvous_mgr' failed (Exit 1)
In file included from ./tensorflow/core/framework/common_shape_fns.h:22:0,
                 from ./tensorflow/core/framework/resource_mgr.h:24,
                 from ./tensorflow/core/common_runtime/device.h:43,
                 from ./tensorflow/core/common_runtime/device_mgr.h:24,
                 from ./tensorflow/core/distributed_runtime/worker_session.h:21,
                 from ./tensorflow/core/distributed_runtime/base_rendezvous_mgr.h:24,
                 from ./tensorflow/contrib/mpi/mpi_rendezvous_mgr.h:35,
                 from tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc:18:
./tensorflow/core/util/tensor_format.h: In function 'tensorflow::TensorShape tensorflow::ShapeFromFormat(tensorflow::TensorFormat, tensorflow::int64, tensorflow::gtl::ArraySlice<long long int>, tensorflow::int64)':
./tensorflow/core/util/tensor_format.h:501:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (format == FORMAT_NHWC_VECT_W && dim == spatial.size() - 1) {
                                         ~~~~^~~~~~~~~~~~~~~~~~~~~
In file included from tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc:18:0:
./tensorflow/contrib/mpi/mpi_rendezvous_mgr.h: In member function 'void tensorflow::MPISendTensorCall::Init(const tensorflow::Rendezvous::ParsedKey&, tensorflow::int64, bool)':
./tensorflow/contrib/mpi/mpi_rendezvous_mgr.h:74:36: error: 'using StringPiece = class absl::string_view {aka class absl::string_view}' has no member named 'ToString'
     mRes_.set_key(parsed.FullKey().ToString());
                                    ^~~~~~~~
tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc: In member function 'virtual void tensorflow::MPIRemoteRendezvous::RecvFromRemoteAsync(const tensorflow::Rendezvous::ParsedKey&, const tensorflow::Rendezvous::Args&, tensorflow::Rendezvous::DoneCallback)':
tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc:139:38: error: 'using StringPiece = class absl::string_view {aka class absl::string_view}' has no member named 'ToString'
   mgr->QueueRequest(parsed.FullKey().ToString(), step_id_,
                                      ^~~~~~~~
tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc: In lambda function:
tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc:261:45: error: 'using StringPiece = class absl::string_view {aka class absl::string_view}' has no member named 'ToString'
         SendQueueEntry req(parsed.FullKey().ToString().c_str(), std::move(res));
                                             ^~~~~~~~
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/contrib/mpi/mpi_utils.h:25,
                 from ./tensorflow/contrib/mpi/mpi_rendezvous_mgr.h:34,
                 from tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc:18:
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetTensorDim(tensorflow::gtl::ArraySlice<T>, tensorflow::TensorFormat, char) [with T = long long int; tensorflow::gtl::ArraySlice<T> = absl::Span<const long long int>]':
./tensorflow/core/util/tensor_format.h:452:47:   required from here
./tensorflow/core/util/tensor_format.h:420:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attributes.size())
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:420:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attributes.size())
   ^
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetFilterDim(tensorflow::gtl::ArraySlice<T>, tensorflow::FilterTensorFormat, char) [with T = long long int; tensorflow::gtl::ArraySlice<T> = absl::Span<const long long int>]':
./tensorflow/core/util/tensor_format.h:461:54:   required from here
./tensorflow/core/util/tensor_format.h:435:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attribute.size())
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:435:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attribute.size())
   ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 863.199s, Critical Path: 65.99s
INFO: 3852 processes: 3852 local.
FAILED: Build did NOT complete successfully
```
It says that StringPiece has no member ToString.
I installed MPI with:
```
wget https://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.1.2.tar.gz
tar -xvf openmpi-3.1.2.tar.gz
cd openmpi-3.1.2
./configure --disable-mpi-fortran --with-cuda=/usr/local/cuda/ --prefix /usr/local/
make
make install
```

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to fix the MPI build failure caused by `StringPiece` -> `absl::string_view`.

This fix fixes #22376.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by martinwicke** [comment]
@jlebar have we caught these already?

**Comment by jlebar** [comment]
> @jlebar have we caught these already?

Looks to me like we have not.

**Comment by yongtang** [comment]
Updated the description to include `This fix fixes #22376.`, as issue #22376 is related.

/cc @jlebar @martinwicke

**Comment by jlebar** [comment]
Looks like you clang-formatted the whole file.  That's not the right thing to do: clang-format is not a stable format, so if you clang-format the entirety of every file you touch, we're going to introduce a lot of irrelevant whitespace changes.

The correct thing is to apply the diff that the clang-format test was saying to apply, or to use the `git-clang-format` tool that you can find in the LLVM repository, e.g. https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/git-clang-format.

Whitespace, I know...

@yifeif IIRC we're now clang-formatting patches when we import them to be submitted.  Does that allow us to turn off the external clang-format check, so we don't have to go through this with folks anymore?

**Comment by yongtang** [comment]
Thanks @jlebar. I have updated the PR and now only applied the clang-format change as is shown in `Experimental clang-format Check`. Please take a look and let me know if there are any issues.

**Comment by phalexo** [comment]
So was MPI related ToString issue addressed? I still see it with the latest master pull.

**Comment by jlebar** [comment]
> So was MPI related ToString issue addressed? I still see it with the latest master pull.

Isn't the fix you're looking for in this PR, which is still unsubmitted?

**Review by jlebar — APPROVED** [review]

**Comment by phalexo** [comment]
> > So was MPI related ToString issue addressed? I still see it with the latest master pull.
> 
> Isn't the fix you're looking for in this PR, which is still unsubmitted?

I don't know. I guess I was hoping that my question might prod someone to submit it. Wishful thinking?

**Comment by yongtang** [comment]
@phalexo This PR addresses the issue you encounter. The PR is not merged into the master yet, but it will go into master soon.

**Comment by jlebar** [comment]
This is ready for @martinwicke to submit.

**Comment by martinwicke** [comment]
@jlebar, in that case, just add the "ready to pull" label.

**Comment by martinwicke** [comment]
(just did for this one)

**Comment by EFanZh** [comment]
What about r1.11 branch? Is it going to get the patch?

**Pull request merged**
