### PR TITLE
MKL: Updating Performance Guide Documentations 

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**

### CODE REVIEW

**Comment by tfboyd** [comment]
I will start looking through this for the summit.  I need to verify the linking works as expected with the markdown style used by the site.  Target to have some comments by the end of this week.

**Comment by MarkDaoust** [comment]
> I need to verify the linking works as expected with the markdown style used by the site.

I've confirmed that this works as intended.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @tfboyd: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tfboyd** [comment]
This is going to take more time.  I agree with the content but there are too many changes here for me to easily approve.  Our markdown parser for TensorFlow.org is picky and just because it renders in MD in github does not mean it will render on tensorflow.org.  That is being fixed in the next 2-4 weeks.  I will try to come back to this.  I also feel there is some rewriting needed as some sections feel more like marketing now and it feel out of place.  Especially the top where I was summarizing the CPU and GPU perf sections.  A little flowering language is fine but it looks silly to me at this point and I would need to have the tech writers review it.  This is me being overly honest as I do not like not just accepting this and moving on.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 43 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 58 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 73 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 88 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 103 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 118 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 133 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 148 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 163 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 178 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 193 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 208 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 223 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request closed without merging**
