### PR TITLE
Expose CreateLoopInvariantCopy

### PR DESCRIPTION
**Pull request by Sam-Hornby**
Summary:
In order to use this function in other passes that act on while loops
make this function public.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @r4nt Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @r4nt Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @r4nt Can you please review this PR ? Thank you!

**Comment by cheshire** [comment]
Hi Samuel,

Do you need this change for other pending PRs? Could you specify which ones?

**Pull request closed without merging**
