### PR TITLE
[ROCm] Update script install_pip_packages.sh for Python 2.7

### PR DESCRIPTION
**Pull request by deven-amd**
Currently ROCm TF cotnainers use the `install_pip_packages.sh` script to install the Python pip package-manager.
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.rocm#L102
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_pip_packages.sh#L20-L23

Starting 01/23/2021, we started getting the following error while building TF containers for ROCM CI (when calling `get-pip.py` for Python2)

```
Traceback (most recent call last):
  File "get-pip.py", line 24226, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpWkL0gn/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
```

The cause seems to be an update to the `get-pip.py` script, which now picks the version `pip-21.0` (previously it was `pip-20.3.4`).
`pip-21.0` drops support for Python2.7 (as indicated by the following warning message)
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020.
Please upgrade your Python as Python 2.7 is no longer maintained.
pip 21.0 will drop support for Python 2.7 in January 2021.
More details about Python 2 support in pip can be found at
https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pip 21.0 will remove support for this functionality.
```

It seems that there is now a Python 2.7 specific version of the `get-pip.py` script that we need to use, and that is what this commit does

Note: Although I am filing this PR as a ROCm specific PR, this issue + fix is probably applicable to all users of the `install_pip_packages.sh` script.

---------------------------------------------------------------------------

/cc @cheshire @chsigg @nvining-work

### CODE REVIEW

**Comment by deven-amd** [comment]
@chsigg gentle ping....ROCm CSB is blocked by this PR.

**Comment by deven-amd** [comment]
@chsigg gentle ping

**Comment by deven-amd** [comment]
@chsigg gentle ping

**Comment by chsigg** [comment]
If Python 2.7 has reached end of life, shouldn't we just drop support for it? Admittedly, I didn't check who and how it's still being used.

**Comment by deven-amd** [comment]
> If Python 2.7 has reached end of life, shouldn't we just drop support for it? Admittedly, I didn't check who and how it's still being used.

that would be ideal, but as you said we do not know who/what it will impact. Can we take this PR for now, and have the correct person in G look at making the bigger change to drop Python 2.x support + references in this and other scripts?

**Comment by chsigg** [comment]
@mihaimaruseac, do I understand correctly that we do not build TF for Python 2.7 anymore and this change is only needed for ROCm's CI?

**Comment by mihaimaruseac** [comment]
We dropped support for py2 last year.

We should no longer take PRs that only affect py2 support.

**Comment by deven-amd** [comment]
@mihaimaruseac 

can I then go ahead and modify this PR to instead, drop all `pip2` commands from the `install_pip_packages.sh` script?

**Comment by mihaimaruseac** [comment]
Sure, that is a better fix.

**Comment by deven-amd** [comment]
> Sure, that is a better fix.

@mihaimaruseac , done...please review

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
