### PR TITLE
[WIP] Fixing Minor Issues

### PR DESCRIPTION
**Pull request by miladsade96**

### CODE REVIEW

**Comment by gbaned** [comment]
@EverLookNeverSee  Can you please address PyLint errors? Thanks!

**Comment by EverLookNeverSee** [comment]
> @EverLookNeverSee Can you please address PyLint errors? Thanks!

It is written in tensorflow code style that the indentation size should be multiply four, but pylint says the indentation should be 6 instead of 12 in some lines.

**Review by miladsade96 — COMMENTED** [review]
LGTM!

**Comment by EverLookNeverSee** [comment]
I am going to ignore fixing the line indentations.

**Comment by EverLookNeverSee** [comment]
I decided to close this PR and create a new one without manipulating the line indentations.

**Pull request closed without merging**
