### PR TITLE
Fix compilation failure that prevents JAX from building on ROCm.

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
/cc @cheshire @chsigg

### CODE REVIEW

**Comment by cheshire** [comment]
Could you be more specific on what is not working? We do use implicit conversion to optional almost ~everywhere, why this specific file?

**Comment by cheshire** [comment]
@hawkinsp looks fine to you?

**Comment by rsanthanam-amd** [comment]
I removed the temporary but kept the move.  Apparently the copy ops for PjRtChunk are deleted which is probably why the compiler complained.

It worked with this latest change.

**Review by cheshire — APPROVED** [review]

**Review by hawkinsp — APPROVED** [review]

**Review by wozhendeshuai — COMMENTED** [review]
good choice

**Pull request merged**
