### PR TITLE
xla cache .

### PR DESCRIPTION
**Pull request by zhaozheng09**

### CODE REVIEW

**Comment by zhaozheng09** [comment]
https://github.com/tensorflow/tensorflow/issues/52645

**Comment by zhaozheng09** [comment]
I am a novice, and I don't know whether this pr is useful. so I simple change my code. If you think this pr is useful, I will detailly add this function and test .

**Comment by gbaned** [comment]
@thomasjoerg Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@thomasjoerg Can you please review this PR ? Thanks!

**Comment by Marek-Arnold** [comment]
I hope this fixes an OOM problem I am facing right now, when using XLA functions on CPU, thx @all who are involved in fixing this :)

**Comment by gbaned** [comment]
Hi @r4nt Can you please review this PR ? Thank you!

**Comment by cheshire** [comment]
Hi, a lot more comments would be required to check in similar changes. From the code itself it's hard to tell how the cache behavior would change and whether it would help.

**Pull request closed without merging**
