### PR TITLE
Move tensorflow/c/tf_status... to TSL

### PR DESCRIPTION
**Pull request by joker-eph**
This is done by forwarding as many function calls as possible. This will allow to cut some more dependencies from XLA to TensorFlow.

### CODE REVIEW

**Comment by joker-eph** [comment]
@bani-intelaipg ; apparently you can help here?

I have a Windows-only issue that I don't know how to solve. I'm just moving code around, and just a single test fails the windows build:
```
Executed 1511 out of 1741 tests: 1740 tests pass and 1 fails to build.
```

Here is the test log:
```
LINK : warning LNK4044: unrecognized option '/lm'; ignored


   Creating library bazel-out\x64_windows-opt\bin\tensorflow\c\kernels\tensor_shape_utils_test.lib and object bazel-out\x64_windows-opt\bin\tensorflow\c\kernels\tensor_shape_utils_test.exp


LINK : warning LNK4217: symbol '?g_trace_level@internal@profiler@tensorflow@@3U?$atomic@H@std@@A (struct std::atomic<int> tensorflow::profiler::internal::g_trace_level)' defined in 'traceme_recorder_impl.lo.lib(traceme_recorder.obj)' is imported by 'allocator_registry_impl.lo.lib(cpu_allocator_impl.obj)' in function '"public: static void __cdecl tensorflow::profiler::TraceMe::InstantActivity<class <lambda_81a9a529402ba0173c27e781358b0282>,1>(class <lambda_81a9a529402ba0173c27e781358b0282> &&,int)" (??$InstantActivity@V<lambda_81a9a529402ba0173c27e781358b0282>@@$00@TraceMe@profiler@tensorflow@@SAX$$QEAV<lambda_81a9a529402ba0173c27e781358b0282>@@H@Z)'


LINK : warning LNK4217: symbol 'TF_NumDims' defined in 'tf_tensor.lib(tf_tensor.obj)' is imported by 'tensor_shape_utils.lib(tensor_shape_utils.obj)' in function '"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl tensorflow::ShapeDebugString(struct TF_Tensor *)" (?ShapeDebugString@tensorflow@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAUTF_Tensor@@@Z)'


LINK : warning LNK4217: symbol 'TF_Dim' defined in 'tf_tensor.lib(tf_tensor.obj)' is imported by 'tensor_shape_utils.lib(tensor_shape_utils.obj)' in function '"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl tensorflow::ShapeDebugString(struct TF_Tensor *)" (?ShapeDebugString@tensorflow@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAUTF_Tensor@@@Z)'


LINK : warning LNK4217: symbol 'TF_DataTypeSize' defined in 'tf_datatype.lo.lib(tf_datatype.obj)' is imported by 'tf_tensor.lib(tf_tensor.obj)' in function '"struct TF_Tensor * __cdecl `anonymous namespace'::CreateTensor(class TF_ManagedBuffer *,enum TF_DataType,__int64 const *,int,unsigned __int64)" (?CreateTensor@?A0x1c9e8144@@YAPEAUTF_Tensor@@PEAVTF_ManagedBuffer@@W4TF_DataType@@PEB_JH_K@Z)'


tf_tensor.lib(tf_tensor.obj) : error LNK2019: unresolved external symbol __imp_TF_SetStatus referenced in function TF_TensorBitcastFrom


bazel-out\x64_windows-opt\bin\tensorflow\c\kernels\tensor_shape_utils_test.exe : fatal error LNK1120: 1 unresolved externals


ERROR: C:/[workspace/tensorflow/c/kernels/BUILD:167](https://cs.corp.google.com/piper///depot/google3/workspace/tensorflow/c/kernels/BUILD?l=167&cl=476650608):11: Linking tensorflow/c/kernels/tensor_shape_utils_test.exe failed: (Exit 1120): link.exe failed: error executing command 

  cd /d C:/tmp/hgi62d3r/execroot/org_tensorflow

  SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\um\x64

    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\Windows\system32

    SET PWD=/proc/self/cwd

    SET TEMP=C:\Users\ContainerAdministrator\AppData\Local\Temp

    SET TF2_BEHAVIOR=1

    SET TMP=C:\Users\ContainerAdministrator\AppData\Local\Temp

  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe @bazel-out/x64_windows-opt/bin/tensorflow/c/kernels/tensor_shape_utils_test.exe-2.params

# Configuration: d22592f8f6550f303aa159dc327417c1006f1735f4c74f98dea0300b8bbc527f

# Execution platform: //tensorflow/tools/toolchains/win:rbe_windows_ltsc2019
```

Basically 
```
tf_tensor.lib(tf_tensor.obj) : error LNK2019: unresolved external symbol __imp_TF_SetStatus referenced in function TF_TensorBitcastFrom
```

Seems like the error. However the TF_SetStatus is still present and I don't think I changed the dependency structure in a way that would make it not present anymore? 
More importantly I would expect much more other failures involving other symbols, which leaves me puzzled.

**Comment by jerry-adams-franklin-intel** [comment]
@joker-eph joker-eph

We manually reproduced your build. We are observing the following error :-

ERROR: C:/users/sdp/_bazel_sdp/lhb4i5gx/external/com_google_absl/absl/base/BUILD.bazel:203:11: Linking external/com_google_absl/absl/base/base_2dd4b70e6d.dll failed: (Exit 1120): link.exe failed: error executing command
  cd /d C:/users/sdp/_bazel_sdp/lhb4i5gx/execroot/org_tensorflow
  SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Python310/python.exe
    SET PYTHON_LIB_PATH=C:/Python310/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\sdp\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TMP=C:\Users\sdp\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe @bazel-out/x64_windows-opt/bin/external/com_google_absl/absl/base/base_2dd4b70e6d.dll-2.params
# Configuration: f7b0e5afa37b2860fb1baa0e5bbdaa95806a39ea5d02b492d0e82c9bbbdbbd70
# Execution platform: @local_execution_config_platform//:platform
   Creating library bazel-out/x64_windows-opt/bin/external/com_google_absl/absl/base/base.if.lib and object bazel-out/x64_windows-opt/bin/external/com_google_absl/absl/base/base.if.exp
spinlock.obj : error LNK2019: unresolved external symbol "unsigned int __cdecl absl::lts_20220623::base_internal::SpinLockWait(struct std::atomic<unsigned int> *,int,struct absl::lts_20220623::base_internal::SpinLockWaitTransition const * const,enum absl::lts_20220623::base_internal::SchedulingMode)" (?SpinLockWait@base_internal@lts_20220623@absl@@YAIPEAU?$atomic@I@std@@HQEBUSpinLockWaitTransition@123@W4SchedulingMode@123@@Z) referenced in function "void __cdecl absl::lts_20220623::base_internal::CallOnceImpl<class <lambda_5e0106fcf58677adb5f4f60c9fdf882e> >(struct std::atomic<unsigned int> *,enum absl::lts_20220623::base_internal::SchedulingMode,class <lambda_5e0106fcf58677adb5f4f60c9fdf882e> &&)" (??$CallOnceImpl@V<lambda_5e0106fcf58677adb5f4f60c9fdf882e>@@$$V@base_internal@lts_20220623@absl@@YAXPEAU?$atomic@I@std@@W4SchedulingMode@012@$$QEAV<lambda_5e0106fcf58677adb5f4f60c9fdf882e>@@@Z)
sysinfo.obj : error LNK2001: unresolved external symbol "unsigned int __cdecl absl::lts_20220623::base_internal::SpinLockWait(struct std::atomic<unsigned int> *,int,struct absl::lts_20220623::base_internal::SpinLockWaitTransition const * const,enum absl::lts_20220623::base_internal::SchedulingMode)" (?SpinLockWait@base_internal@lts_20220623@absl@@YAIPEAU?$atomic@I@std@@HQEBUSpinLockWaitTransition@123@W4SchedulingMode@123@@Z)
spinlock.obj : error LNK2019: unresolved external symbol AbslInternalSpinLockWake_lts_20220623 referenced in function "void __cdecl absl::lts_20220623::base_internal::CallOnceImpl<class <lambda_5e0106fcf58677adb5f4f60c9fdf882e> >(struct std::atomic<unsigned int> *,enum absl::lts_20220623::base_internal::SchedulingMode,class <lambda_5e0106fcf58677adb5f4f60c9fdf882e> &&)" (??$CallOnceImpl@V<lambda_5e0106fcf58677adb5f4f60c9fdf882e>@@$$V@base_internal@lts_20220623@absl@@YAXPEAU?$atomic@I@std@@W4SchedulingMode@012@$$QEAV<lambda_5e0106fcf58677adb5f4f60c9fdf882e>@@@Z)
sysinfo.obj : error LNK2001: unresolved external symbol AbslInternalSpinLockWake_lts_20220623
spinlock.obj : error LNK2019: unresolved external symbol AbslInternalSpinLockDelay_lts_20220623 referenced in function "private: void __cdecl absl::lts_20220623::base_internal::SpinLock::SlowLock(void)" (?SlowLock@SpinLock@base_internal@lts_20220623@absl@@AEAAXXZ)
bazel-out\x64_windows-opt\bin\external\com_google_absl\absl\base\base_2dd4b70e6d.dll : fatal error LNK1120: 3 unresolved externals
Target //tensorflow/c/kernels:tensor_shape_utils_test failed to build

**Comment by jerry-adams-franklin-intel** [comment]
@joker-eph 

We tried to manually reproduce the build and we are observing the following error :-

ERROR: C:/users/sdp/_bazel_sdp/lhb4i5gx/external/com_google_absl/absl/base/BUILD.bazel:203:11: Linking external/com_google_absl/absl/base/base_2dd4b70e6d.dll failed: (Exit 1120): link.exe failed: error executing command
  cd /d C:/users/sdp/_bazel_sdp/lhb4i5gx/execroot/org_tensorflow
  SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Python310/python.exe
    SET PYTHON_LIB_PATH=C:/Python310/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\sdp\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TMP=C:\Users\sdp\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe @bazel-out/x64_windows-opt/bin/external/com_google_absl/absl/base/base_2dd4b70e6d.dll-2.params
# Configuration: f7b0e5afa37b2860fb1baa0e5bbdaa95806a39ea5d02b492d0e82c9bbbdbbd70
# Execution platform: @local_execution_config_platform//:platform
   Creating library bazel-out/x64_windows-opt/bin/external/com_google_absl/absl/base/base.if.lib and object bazel-out/x64_windows-opt/bin/external/com_google_absl/absl/base/base.if.exp
spinlock.obj : error LNK2019: unresolved external symbol "unsigned int __cdecl absl::lts_20220623::base_internal::SpinLockWait(struct std::atomic<unsigned int> *,int,struct absl::lts_20220623::base_internal::SpinLockWaitTransition const * const,enum absl::lts_20220623::base_internal::SchedulingMode)" (?SpinLockWait@base_internal@lts_20220623@absl@@YAIPEAU?$atomic@I@std@@HQEBUSpinLockWaitTransition@123@W4SchedulingMode@123@@Z) referenced in function "void __cdecl absl::lts_20220623::base_internal::CallOnceImpl<class <lambda_5e0106fcf58677adb5f4f60c9fdf882e> >(struct std::atomic<unsigned int> *,enum absl::lts_20220623::base_internal::SchedulingMode,class <lambda_5e0106fcf58677adb5f4f60c9fdf882e> &&)" (??$CallOnceImpl@V<lambda_5e0106fcf58677adb5f4f60c9fdf882e>@@$$V@base_internal@lts_20220623@absl@@YAXPEAU?$atomic@I@std@@W4SchedulingMode@012@$$QEAV<lambda_5e0106fcf58677adb5f4f60c9fdf882e>@@@Z)
sysinfo.obj : error LNK2001: unresolved external symbol "unsigned int __cdecl absl::lts_20220623::base_internal::SpinLockWait(struct std::atomic<unsigned int> *,int,struct absl::lts_20220623::base_internal::SpinLockWaitTransition const * const,enum absl::lts_20220623::base_internal::SchedulingMode)" (?SpinLockWait@base_internal@lts_20220623@absl@@YAIPEAU?$atomic@I@std@@HQEBUSpinLockWaitTransition@123@W4SchedulingMode@123@@Z)
spinlock.obj : error LNK2019: unresolved external symbol AbslInternalSpinLockWake_lts_20220623 referenced in function "void __cdecl absl::lts_20220623::base_internal::CallOnceImpl<class <lambda_5e0106fcf58677adb5f4f60c9fdf882e> >(struct std::atomic<unsigned int> *,enum absl::lts_20220623::base_internal::SchedulingMode,class <lambda_5e0106fcf58677adb5f4f60c9fdf882e> &&)" (??$CallOnceImpl@V<lambda_5e0106fcf58677adb5f4f60c9fdf882e>@@$$V@base_internal@lts_20220623@absl@@YAXPEAU?$atomic@I@std@@W4SchedulingMode@012@$$QEAV<lambda_5e0106fcf58677adb5f4f60c9fdf882e>@@@Z)
sysinfo.obj : error LNK2001: unresolved external symbol AbslInternalSpinLockWake_lts_20220623
spinlock.obj : error LNK2019: unresolved external symbol AbslInternalSpinLockDelay_lts_20220623 referenced in function "private: void __cdecl absl::lts_20220623::base_internal::SpinLock::SlowLock(void)" (?SlowLock@SpinLock@base_internal@lts_20220623@absl@@AEAAXXZ)
bazel-out\x64_windows-opt\bin\external\com_google_absl\absl\base\base_2dd4b70e6d.dll : fatal error LNK1120: 3 unresolved externals
Target //tensorflow/c/kernels:tensor_shape_utils_test failed to build

**Comment by joker-eph** [comment]
`--dynamic=off` was missing I think. It is not longer needed at HEAD, I rebased the change

**Comment by gbaned** [comment]
Hi @joker-eph Can you please resolve conflicts? Thank you!

**Pull request closed without merging**
