### PR TITLE
Add tensorflow io support

### PR DESCRIPTION
**Pull request by dilverse**
Add tensorflow-io package to the pip-packages that gets picked in tensorflow docker images, to provide object storage support for tensorflow images out of the box as seen in [this](https://github.com/tensorflow/tensorflow/issues/58710) issue

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
I think the plan is for users to manually install the TF IO wheel. We don't want `pip install tensorflow` to install all and every package that exists in TF ecosystem.

**Comment by dilverse** [comment]
@mihaimaruseac The idea was for the docker images to pick the tensorflow-io support, since applications like tensorboard with object storage or other file system support is purely dependent on that package. this add complexity to the deployment as described in the issue [#58710](https://github.com/tensorflow/tensorflow/issues/58710), what would be your recommended approach?

**Comment by dvaldivia** [comment]
Why is there an exception for `tensorflow-io-gcs-filesystem` if that's also part of `tensorflow-io` @mihaimaruseac? S3 support was standard up to TF 2.4.0 until the code got split into tensorflow-io and broke support for it but support for GCS made it as an exception for some reason.

We tracked this problem all the way from kubeflow which uses a lot of TensorFlow components, and they all make the assumption that s3 is present, but it was removed so using a newer tensorflow breaks the components (tensorboard, tf serving, for example)

The idea of this PR is to make sure the standard TensorFlow image includes this dependency, if this used to be part of the core code and it got split to alleviate the load of the main repository, I don't see a problem in adding the dependency into the final package/container.

**Comment by mihaimaruseac** [comment]
> @mihaimaruseac The idea was for the docker images to pick the tensorflow-io support, since applications like tensorboard with object storage or other file system support is purely dependent on that package. This adds complexity to the deployment as described in the issue [#58710](https://github.com/tensorflow/tensorflow/issues/58710), what would be your recommended approach?

Then it should be added to the dockerfile installs, not to the `setup.py` package

> Why is there an exception for `tensorflow-io-gcs-filesystem` if that's also part of `tensorflow-io` @mihaimaruseac? S3 support was standard up to TF 2.4.0 until the code got split into tensorflow-io and broke support for it but support for GCS made it as an exception for some reason.
> 
> We tracked this problem all the way from kubeflow which uses a lot of TensorFlow components, and they all make the assumption that s3 is present, but it was removed so using a newer tensorflow breaks the components (tensorboard, tf serving, for example)
> 
> The idea of this PR is to make sure the standard TensorFlow image includes this dependency, if this used to be part of the core code and it got split to alleviate the load of the main repository, I don't see a problem in adding the dependency into the final package/container.

The GCS filesystem is needed for most of the tutorials on TF.org, has a larger level of maintenance and replicates the support for internal TF. The S3 filesystem does not match that. Users should do `pip install tensorflow-io` to bring in the additional filesystems, as needed.

**Pull request closed without merging**
