### PR TITLE
improve API doc page: tf.data.Dataset

### PR DESCRIPTION
**Pull request by dothinking**
-  show list style for `tf.data.Dataset.list_files` example 
-  change `NOTE:` to `Note:` to keep a consistent style in API doc

### CODE REVIEW

**Comment by fuhailin** [comment]
Thanks for your PR, I think this improvement is not necessary, the `NOTE` word style existed in https://github.com/tensorflow/tensorflow/blob/5ad917782a5bc3895aa92292fd4447e57eda2560/tensorflow/python/data/ops/iterator_ops.py#L42
and 
https://github.com/tensorflow/tensorflow/blob/5ad917782a5bc3895aa92292fd4447e57eda2560/tensorflow/python/data/ops/optional_ops.py#L111
are already in a consistent style

**Comment by jsimsa** [comment]
@dothinking thank you for attempting to improve tf.data API documentation. Having said that, I agree with @fuhailin that this change is not necessary.

I quickly searched through all of tensorflow/python/data and found 9 occurrences of "Note" and 16 occurrences of "NOTE". So there does not seem to be a precedent and I am also not aware of official style guide for TensorFlow that would state to use "Note". If we wanted to be consistent, I'd prefer "NOTE".

**Comment by yashk2810** [comment]
> TensorFlow that would state to use "Note"

Devsite highlights `Note:` with a special format. Sadly it does not recognize `NOTE:`.  See https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly for example and the highlighting that `Note:` causes.

**Comment by jsimsa** [comment]
Thanks @yashk2810, if that's the case I agree that this PR makes sense.

**Review by jsimsa — APPROVED** [review]

**Comment by dothinking** [comment]
Thank @fuhailin, @jsimsa  for the comments, it's OK to use `NOTE` through the doc string. But as explained by @yashk2810 , the `NOTE` style could not be rendered properly in the API documentation page.

Of course, it'll be better if both `Note` and `NOTE` are able to be accommodated.

**Comment by dothinking** [comment]
Thank @yashk2810 for your explanation, that's exactly what I meant.

**Pull request merged**
