### PR TITLE
Cleanup, Warning Removal and TC added for the file

### PR DESCRIPTION
**Pull request by amitsrivastava78**
Fixed warning, cleanup the code and added TC to the file.

### CODE REVIEW

**Comment by gbaned** [comment]
@alanchiao Could you PTAL and approve.

**Comment by gbaned** [comment]
@alanchiao can you please review this PR ?

**Comment by amitsrivastava78** [comment]
@gbaned i have rebased the PR.
@alanchiao can you pls review the PR.

Regards
Amit

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by terryheo** [comment]
Thanks for the contribution.
Unfortunately, new converter is default now. So we'd better not accept further changes for old converter.
https://groups.google.com/a/tensorflow.org/d/msg/tflite/Z_h7706dt8Q/sNrjPj4yGgAJ

**Pull request closed without merging**
