### PR TITLE
fix for issue #22347

### PR DESCRIPTION
**Pull request by jrbtaylor**
fix for #22347 in contrib/graph_editor/transform: clear the colocation attribute when copying the node_def such that the new subgraph can be exported separate from the original copied subgraph

### CODE REVIEW

**Review by purpledog — CHANGES_REQUESTED** [review]
Would you mind also writing a test for this. It should fail before this CL and passes after.

Also, I am not very familiar with node_def proto but it seems strange that "_class" refers to "colocation". what does the node_def look like? (I think you deleted the output from the issue).

**Comment by jrbtaylor** [comment]
I can't find any documentation on the node_def so I'm only going off what I saw in my examples, which I agree is not rigorous. I'll have to find out if the "_class" attribute can hold things other than colocation. I'll try to dig into this more next week.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @purpledog: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by ebrevdo** [comment]
Please resubmit a clean pr

**Comment by jrbtaylor** [comment]
I'm going to close this as my application might be a special case and it's easier for me to just maintain my own version of transform.graph_replace

**Pull request closed without merging**
