### PR TITLE
Update docs for using Docker with GPU, with nvidia-docker2

### PR DESCRIPTION
**Pull request by tiangolo**
Update docs to reflect the current version of `nvidia-docker` (version 2).

For reference: https://github.com/NVIDIA/nvidia-docker/wiki/About-version-2.0

### CODE REVIEW

**Comment by gunan** [comment]
On my installation, `nvidia-docker` still works. I think to reduce confusion, we should stick with `nvidia-docker`, and think of this switch later down the line where we have a higher adoption rate for nvidia-docker2

**Comment by gunan** [comment]
No, I verified that after i purged the old nvidia-docker and installed the new version.
@flx42 for verification if `nvidia-docker` should still work.

**Comment by gunan** [comment]
Here is what the nvidia-docker2 package installs:
```
$ dpkg -L nvidia-docker2
/.
/etc
/etc/docker
/etc/docker/daemon.json
/usr
/usr/bin
/usr/bin/nvidia-docker
/usr/share
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/nvidia-docker2
/usr/share/doc
/usr/share/doc/nvidia-docker2
/usr/share/doc/nvidia-docker2/copyright
/usr/share/doc/nvidia-docker2/changelog.Debian.gz
```
Please see `/usr/bin/nvidia-docker` above. When I check its contents it is identical to this file: https://github.com/NVIDIA/nvidia-docker/blob/master/nvidia-docker

Also querying further:
```
$ sudo nvidia-docker version
NVIDIA Docker: 2.0.0
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

please check your installation of nvidia-docker. I will close this PR as it complicates our instructions.

**Comment by flx42** [comment]
Yes, V1 will still work.
And V2 provides a wrapper script for backward compatibility, so your instructions should still work.

**Pull request closed without merging**
