### PR TITLE
[TF 2.0 API Docs] tf.group

### PR DESCRIPTION
**Pull request by imransalam**
https://github.com/tensorflow/tensorflow/issues/29262
The file changes are according to this issue raised. Added more in the description and made a simple usage example.

### CODE REVIEW

**Comment by imransalam** [comment]
@googlebot I've signed it!

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@yashk2810 Can you please take a look on this PR? Thanks!

**Comment by gbaned** [comment]
@imransalam Can you please address Ubuntu Sanity errors? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
