### PR TITLE
[ROCm] Updating find_rocm_config.py to …

### PR DESCRIPTION
**Pull request by deven-amd**
Updating find_rocm_config.py to pickup the commit that was missed when merging PR #44471 ( https://github.com/tensorflow/tensorflow/pull/44471 )

See the following comments (in PR # 44471 for further details)
https://github.com/tensorflow/tensorflow/pull/44471#issuecomment-724678159
https://github.com/tensorflow/tensorflow/pull/44471#issuecomment-724729560

--------------------------------------------------------------------------------

/cc @akuegel @cheshire @chsigg @nvining-work

### CODE REVIEW

**Review by akuegel — APPROVED** [review]

**Comment by akuegel** [comment]
I think the compressed version of the find_rocm_config.py script had an older version where the last few lines were still commented out. I was going to fix this, but then someone else already approved the merge. So this fix will go in separately.

**Comment by deven-amd** [comment]
sorry about that, my fault. Fortunately those lines being commented do not affect any functionality (for now).

will fix this in the next PR (related to rocm config) I file. thanks

**Comment by akuegel** [comment]
Actually I noticed that we get failures if those lines are not commented out. So in my change I kept them commented out, just improved some other things slightly.

**Comment by deven-amd** [comment]
@akuegel 

Think @jerryyin figured out (during out weekly sync of this repo --> ROCm fork) why you possibly maybe getting failures with those lines not commented out.

When uncommented, the `_find_rocblas_config` function is invoked, and this commit introduces a bug in that routine
https://github.com/tensorflow/tensorflow/commit/3ec134727f7cb07b62c99407298c782ce6effed3#diff-5601f1b9a25269295e766e91038a92cfc2372d411fdfe75fcfd86f98124dcf6dR267

The value of `path` gets over-written in the loop, and will not work as expected in the second iteration, leading to failure.

**Comment by akuegel** [comment]
Good catch :)
Those changes were suggested to me in an internal review, and I didn't spot this bug.
The intent of the change was to avoid doing another call to os.path.exists after the for loop.
I guess we should just use another variable in the for loop to assign os.path.join(path, f) to.

**Comment by akuegel** [comment]
I have a change for this under review and will try to get it landed tomorrow.

**Comment by akuegel** [comment]
The fix has landed now: https://github.com/tensorflow/tensorflow/commit/3a52a5462c609c37a3b6048ee17465b1a3d6ba22

**Pull request merged**
