### PR TITLE
Update CROSSTOOL with Toolchain for ARM

### PR DESCRIPTION
**Pull request by jmtatsch**
Update CROSSTOOL that it uses the local_linux toolchain for arm as some people managed to build tensor flow on raspberrypi2 and jetson. Otherwise it would fail with:

```
ERROR: No toolchain found for cpu 'arm'. Valid cpus are: [
  k8,
  piii,
  darwin,
].
```

### CODE REVIEW

**Comment by vrv** [comment]
Thanks for the contribution!  I'm a bit confused though -- you've made the change to the crosstool when compiling with GPUs.  Did you intend to want it to work without --config=cuda too?

**Comment by jmtatsch** [comment]
Hmm, I never tried to compile without --config=cuda. Probably its a non issue for systems without cuda...

**Comment by vrv** [comment]
Assigning to @andrewharp, who has more experience with arm builds :)

**Comment by andrewharp** [comment]
Seems sensible, but it looks like you need to merge master into your branch.

**Comment by jmtatsch** [comment]
Unfortunately, this doesn't only affect gpu builds on arm platforms. For whatever reason the CROSSTOOL file is also parsed when gpu support is disabled and fails with the same error.  My proposed fix with disabled gpu support errors out with:

```
INFO: Found 1 target...
ERROR: /opt/tensorflow/third_party/gpus/cuda/BUILD:159:1: declared output 'third_party/gpus/cuda/cuda.config' is a dangling symbolic link.
ERROR: /opt/tensorflow/third_party/gpus/cuda/BUILD:159:1: not all outputs were created.
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 6.667s, Critical Path: 0.27s
```

**Comment by jmtatsch** [comment]
By the way, building without cuda on aarch64 works perfectly.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

(sorry for the huge delay)

**Comment by vrv** [comment]
every time you merge, it invalidates the tests, so it would be good to avoid merging after i've kicked off tests :)

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by alephman** [comment]
Hi @jmtatsch 
I was trying to build it on my arm64 boards with aarch64:



ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/farmhash_archive/BUILD:5:1: Executing genrule @farmhash_archive//:configure failed: bash failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; pushd external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260; workdir=$(mktemp -d -t tmp.XXXXXXXXXX); cp -a * $workdir; pushd $workdir; ./configure; popd; popd; cp $workdir/config.h bazel-out/local_linux-opt/genfiles/external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260; rm -rf $workdir;'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/tensorflow/external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/tensorflow
/tmp/tmp.5EXVBY1p2Z /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/tensorflow/external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/tensorflow
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... /tmp/tmp.5EXVBY1p2Z/missing: Unknown `--is-lightweight' option
Try `/tmp/tmp.5EXVBY1p2Z/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
./config.guess: unable to guess system type

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2010-08-21

uname -m = aarch64
uname -r = 3.10.52-linaro-bubblegum
uname -s = Linux
uname -v = #22 SMP PREEMPT Fri Apr 15 11:21:43 CST 2016

/usr/bin/uname -p = 
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = 
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = aarch64
UNAME_RELEASE = 3.10.52-linaro-bubblegum
UNAME_SYSTEM  = Linux
UNAME_VERSION = #22 SMP PREEMPT Fri Apr 15 11:21:43 CST 2016
configure: error: cannot guess build type; you must specify one
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 29.680s, Critical Path: 27.59s

**Pull request merged**
