### PR TITLE
[ROCm] Fixes to enable the cholesky unit test for BEF thunk on ROCm.

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
This captures the TF repo changes needed to enable the cholesky unit test on ROCm.

/cc @chsigg @hanbinyoon

### CODE REVIEW

**Comment by rsanthanam-amd** [comment]
Actually, I need to make the TFRT fixes myself.

I am going to leave the PR up here but please don't review it yet since it is incomplete.

**Comment by rsanthanam-amd** [comment]
Some of the constants used in this PR are defined in a separate commit as part of: https://github.com/tensorflow/tensorflow/pull/54926

**Comment by chsigg** [comment]
Hi Rohit, would you mind rebasing the change? Thanks!

**Comment by rsanthanam-amd** [comment]
> Hi Rohit, would you mind rebasing the change? Thanks!

Done.

**Comment by rsanthanam-amd** [comment]
I used git rebase instead of git merge - I hope that was the right thing to do.

**Comment by chsigg** [comment]
No, this PR now touches 484 files.

**Comment by rsanthanam-amd** [comment]
Closing this and opening a new PR due to git rebase error.

**Pull request closed without merging**
