### PR TITLE
Remove name_scope from convolutional calls.

### PR DESCRIPTION
**Pull request by case540**
Cherry-picking conv layer fix to 1.4 branch.

### CODE REVIEW

**Comment by case540** [comment]
Is this all we need for the conv layer issue to fix it in 1.4?

**Review by agarwal-ashish — APPROVED** [review]

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by benoitsteiner** [comment]
reassigned to @gunan who has permission to merge code into the 1.4 branch.

**Comment by gunan** [comment]
Jenkins, test this please

**Comment by case540** [comment]
Jenkins, test this please

**Comment by case540** [comment]
Errors on the test runs are...

===== ci.tensorflow.org bot =====
ERROR: Error fetching remote repo 'origin'
ERROR: [GitHub Commit Status Setter] - Cannot retrieve Git metadata for the build, setting build result to FAILURE
Unable to get pull request builder trigger!!

and..

===== Unbuntu Makefile Bot =====
ERROR: Skipping '//tensorflow/contrib/makefile:build_all_linux': no such package 'tensorflow/contrib/makefile': BUILD file not found on package path

Both of these seems unrelated to this PR. Not sure how to get them to pass.

**Comment by case540** [comment]
I think the problem is that the CI build scripts are not in TensorFlow so they didnt branch. The build script is trying to run something added after the branch point. So I think we are going to have to force-submit these.

**Pull request merged**
