### PR TITLE
Cast size() to int to avoid implementation-defined conversion

### LINKED ISSUE #19578: Latest NonMaxSuppression breaks backward compatiblity
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Python version**:  N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

The latest changes https://github.com/tensorflow/tensorflow/commit/1a300437cecfae36f7584694dac523851f1cd931 to the NonMaxSuppression op have two issues:

1. It breaks backward compatibility. It removes all boxes whose scores are below a threshold, and the threshold is default to 0. However, the old API does not require that the scores have to be >= 0. Boxes with negative scores will be removed by default after this change.
On [my implementation of Mask RCNN](https://github.com/ppwwyyxx/tensorpack/tree/master/examples/FasterRCNN) this decreases mAP by 0.2.

2. It has a potential bug. This loop:
https://github.com/tensorflow/tensorflow/blob/1a300437cecfae36f7584694dac523851f1cd931/tensorflow/core/kernels/non_max_suppression_op.cc#L137-L142

triggers an integer underflow when `selected` is empty, because `size()` is unsigned. It happens to cause no bugs in this case, but should better be fixed. If the loop order is reversed like `for (int j = 0; j <= selected.size() - 1; ++j)`, this would become a bug immediately.

EDIT: From https://en.cppreference.com/w/cpp/language/implicit_conversion:

> If the destination type is signed, the value does not change if the source integer can be represented in the destination type. Otherwise the result is implementation-defined. (Note that this is different from signed integer arithmetic overflow, which is undefined).

So the above code relies on implementation-defined behavior.

### PR DESCRIPTION
**Pull request by ppwwyyxx**
`selected.size()` is unsigned and originally 0.
The conversion from `(size_t)0 - 1` to int is implementation defined: 

From https://en.cppreference.com/w/cpp/language/implicit_conversion:

> If the destination type is signed, the value does not change if the source integer can be represented in the destination type. Otherwise the result is implementation-defined. (Note that this is different from signed integer arithmetic overflow, which is undefined).

This fixes #19578

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
@caisq Seems like a CI issue again.

**Comment by ppwwyyxx** [comment]
@caisq a gentle ping

**Comment by caisq** [comment]
@cy89 Can you help review this PR or recommend someone to review it? Thanks.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @cy89, @rmlarsen: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Review by rmlarsen — DISMISSED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ppwwyyxx** [comment]
Any updates? 
Resolving the merge conflicts has unfortunately invalidated the review and tests..

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 50 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ppwwyyxx** [comment]
ping @rmlarsen @caisq

**Pull request merged**
