### PR TITLE
enable mkl in eigen for qr_op

### PR DESCRIPTION
**Pull request by suiyuan2009**
#7128

### CODE REVIEW

**Comment by suiyuan2009** [comment]
`--define=using_mkl=true` must be added when using bazel to build, sometimes you need to clean `/path/to/tensorflow/third_party/mkl` first(remove `.so` file),  I added `/path/to/tensorflow/third_party/mkl` to `LD_LIBRARY_PATH` in `~/.bash_profile`.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
I'm a bit wary of having special instructions out. Could you add them in the documentation?

@benoitsteiner WDYT?

**Comment by suiyuan2009** [comment]
it seems mkl is not enabled even if I configure to use mkl when I build from source, so maybe it's still under developing?

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
We made a recent change about how we build with MKL.
I removed the configure option for MKL, but now you can just add `--config=mkl` to your build command to build with MKL support.

**Pull request merged**
