### PR TITLE
fix cmake windows py27 import fail

### PR DESCRIPTION
**Pull request by fo40225**
fix cmake windows py27 import fail

### CODE REVIEW

**Review by protoget — COMMENTED** [review]
I'll start a kokoro run to see if it works.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by fo40225** [comment]
update to 1.9.0, please review.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by annarev — APPROVED** [review]

**Pull request merged**
