### PR TITLE
Fix typo in Problem 1

### PR DESCRIPTION
**Pull request by seanpavlov**
Simple typo in the description.

### CODE REVIEW

**Comment by vincentvanhoucke** [comment]
LGTM, awaiting CLA. Thanks!

**Comment by seanpavlov** [comment]
I signed it!

**Comment by vincentvanhoucke** [comment]
@seanpavlov looks like you need to rebase, I'm getting conflicts.

**Comment by vincentvanhoucke** [comment]
Fix a-coming from upstream.

**Pull request closed without merging**
