### PR TITLE
Various build fixes for FreeBSD

### LINKED ISSUE #28113: TF 2.0.0-alpha0 doesn't build on FreeBSD: error in hwloc
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): FreeBSD 12.0
- Bazel version (if compiling from source): 0.23.0
- GCC/Compiler version (if compiling from source): Clang 8.0.0

I'n trying to build TensorFlow from source on FreeBSD 12. During build the following problem shows up:

```
ERROR: /usr/home/arr/.cache/bazel/_bazel_arr/5d34786d346adb404a81c63780107a71/external/hwloc/BUILD.bazel:212:1: C++ compilation of rule '@hwloc//:hwloc' failed (Exit 1)
external/hwloc/hwloc/topology-linux.c:39:10: fatal error: 'mntent.h' file not found
#include <mntent.h>
         ^~~~~~~~~~
1 error generated.
```

This is because `topology-linux.c` is being compiled instead of `topology-freebsd.c`. I have zero knowledge in Bazel, so I wasn't able to include on of these files based on the condition.

This should be easy to fix for anyone experienced with Bazel.

### PR DESCRIPTION
**Pull request by arrowd**
This PR incorporates changes from https://github.com/freedomtan/tensorflow/commit/ffd86f605bfdbe6f209c1fa707089d6010f0b719, https://github.com/tensorflow/tensorflow/pull/25471 and my own.

This is not ready to be merged yet, as there is a problematic change in last commit. In third_party/hwloc/BUILD.bazel file we only need to have `_INCLUDE_PRIVATE_HWLOC_AUTOIGEN_CONFIG_H_LINUX_SUBS` items in `_INCLUDE_PRIVATE_HWLOC_AUTOIGEN_CONFIG_H_COMMON_SUBS` when we are building on Linux. I wasn't able to express that in Bazel, though. Nested `select`s, as well as `if`s in `BUILD` files are prohibited. How do I go about this change?

Fixes https://github.com/tensorflow/tensorflow/issues/28113
Obsoletes https://github.com/tensorflow/tensorflow/pull/25471

### CODE REVIEW

**Comment by arrowd** [comment]
Signed CLA.

**Review by gunan — DISMISSED** [review]

**Comment by rthadur** [comment]
@arrowd please let us know if this is still WIP ?

**Comment by arrowd** [comment]
> 
> 
> @arrowd please let us know if this is still WIP ?

Yes, I still need help with including `_INCLUDE_PRIVATE_HWLOC_AUTOIGEN_CONFIG_H_LINUX_SUBS` into

```
template_rule(
name = "include_private_hwloc_autogen__config_h",
...
```

in `third_party/hwloc/BUILD.bazel`

**Comment by arrowd** [comment]
Let's just omit that `hwloc` change from the PR for now and get this merged?

**Comment by rthadur** [comment]
> Let's just omit that `hwloc` change from the PR for now and get this merged?

can you please push changes again after removing '`hwloc`'

**Review by gunan — APPROVED** [review]

**Comment by arrowd** [comment]
Ping. Can we get this in?

**Comment by arrowd** [comment]
Another bump.

**Comment by arrowd** [comment]
I take it, this didn't make it into `beta1` release?

**Comment by gunan** [comment]
Unfortunately did not. But it will be definitely in 2.0 release candidates, and any other release we do.

**Pull request merged**
