### PR TITLE
[XLA] Use EmitWriteArrayElement that add LLVM annotation. 

### PR DESCRIPTION
**Pull request by nouiz**
This could help LLVM to vectorize.

See one commit in https://github.com/tensorflow/tensorflow/pull/38136

@cheshire 
I looked at all "Store(" and "CreateStore(" under xla/service/gpu to fix all missed annotation cases.

### CODE REVIEW

**Review by cheshire — DISMISSED** [review]

**Comment by nouiz** [comment]
Some tests are failing. But most of them also fail upstream... So I can't do any debuging.

Is the Linux build passing upstream?

**Comment by nouiz** [comment]
As I can't debut normally, I remove one of the change. The CI should be able to test it.

**Review by cheshire — APPROVED** [review]

**Comment by akuegel** [comment]
Sorry for the delay. It seems our tooling pulled the changes into the previous changelist, but we had already removed ourselves as reviewer from that changelist because that one was not ready to land. Therefore we did not get another notification that this change is ready to be approved.

**Comment by gbaned** [comment]
Changes have been merged into master by commit 79504b1. So closing the PR.

**Pull request closed without merging**
