### PR TITLE
Close FileWriterCache before moving training directory in estimator_test

### LINKED ISSUE #9185: Windows: //tensorflow/python/estimator:estimator_test failing in Bazel build
http://ci.tensorflow.org/job/tf-master-win-bzl/751/consoleFull

It has been failing on ci for a while with:
```
22:36:33 ======================================================================
22:36:33 ERROR: test_train_save_copy_reload (__main__.EstimatorTrainTest)
22:36:33 ----------------------------------------------------------------------
22:36:33 Traceback (most recent call last):
22:36:33   File "\\?\c:\tmp\Bazel.runfiles_r2z2r52c\runfiles\org_tensorflow\py_test_dir\tensorflow\python\estimator\estimator_test.py", line 267, in test_train_save_copy_reload
22:36:33     os.renames(model_dir1, model_dir2)
22:36:33   File "C:\Program Files\Anaconda3\lib\os.py", line 288, in renames
22:36:33     rename(old, new)
22:36:33 PermissionError: [WinError 5] Access is denied: 'c:\\tmp\\tmp8f7qnomv\\model_dir1' -> 'c:\\tmp\\tmp8f7qnomv\\model_dir2'
```
@gunan Can we fix this test case on Windows? Otherwise we'd better disable this test on Windows.

### PR DESCRIPTION
**Pull request by martinwicke**
Hopefully this fixes #9185 by releasing some stray file handle.

### CODE REVIEW

**Comment by martinwicke** [comment]
I triggered http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/3/console

I hope the setup is the same as tf-master-win-bzl.

@meteorcloudy FYI.

**Comment by meteorcloudy** [comment]
@martinwicke I tested on my local machine as well, it doesn't seem to fix the problem.

But I found `shutil.copytree(model_dir1, model_dir2)` works, can we use this instead of `os.rename`?

**Comment by martinwicke** [comment]
The problem with that would be that this does not delete the old tree. This test is to ensure that no absolute paths creep in anywhere, so this would defang the test.

I cannot see what hangs on to a file handle.

**Comment by mrry** [comment]
Perhaps the easiest approach would be to install the current nightly on one of our Windows test VMs, run a modified version of `estimator_test.py` that blocks before the rename, and apply https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx to the Python interpreter to see what handles are open?

**Comment by meteorcloudy** [comment]
@mrry It shows this file is in use by python
`c:/tmp/tmp3y2vhvzi/model_dir1/events.out.tfevents.1492671112.TENSORFLOW-JENK`


image

**Comment by mrry** [comment]
Thanks for tracking that down, Yun! Then I think we have a smoking gun: the `tf.summary.FileWriter` is holding open a file handle after `est1.train()` returns.

It looks like this happens deep in the `MonitoredTrainingSession`... and there seems to be a cache(!!) involved:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/summary/writer/writer_cache.py#L27

As a hack, you might try invoking `FileWriterCache.clear()` before the rename, but I'm not sure that that's sufficient because deleting a `FileWriter` doesn't appear to `close()` it, so you might need to add a `writer.close()` call somewhere (or maybe add it to the destructor?).

**Comment by meteorcloudy** [comment]
@mrry Thanks for the hint, Derek! 
I tested adding `writer_cache.FileWriterCache._cache[model_dir1].close()` before rename also solves the problem. Does this sounds good to you?

**Comment by martinwicke** [comment]
That'll fix the test, but I'm wondering whether we can get put that line (or some equivalent) somewhere were it will be called automatically when the Estimator owning the model_dir is deleted?

**Comment by martinwicke** [comment]
I'm even wondering whether we should even keep the cache live when any of train(), eval(), predict() exit. They're all meant to be long running and ideally shouldn't leave open file handles hanging around.

**Comment by meteorcloudy** [comment]
@martinwicke Yes, I totally agree! But I am lack of knowledge how these function works. Can someone with more experience look into this?

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Triggered another Windows build: http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/4/

**Comment by martinwicke** [comment]
I edited FileWriterCache to `close()` all caches it has, and call that in the test. Cleaner than closing the cache directly.

**Review by mrry — APPROVED** [review]
LGTM (assuming the test passes)!

**Comment by martinwicke** [comment]
I'll merge to fix build.

**Pull request merged**
