### PR TITLE
Tfl-to-TOSA lowering for 'tfl.range' and 'tfl.shape' ops

### PR DESCRIPTION
**Pull request by rafaelubalmw**

### CODE REVIEW

**Comment by eric-k256** [comment]
A couple of broad comments. It's not clear these belong in a TFL to TOSA pass, as neither of them are generating TOSA, rather shape/arith/tensor/etc. They could be separated out into a separate pass doing TFL to tensor (or similar).

In addition, I'm working to propose DIM/tosa.dim as a new operator inside TOSA. Then the tfl.shape could be legalized with pure TOSA ops using tosa.dim instead of going through the shape dialect. Some additional work would go into TOSA so ops such as RESHAPE could take the calculated shape.

**Comment by rafaelubalmw** [comment]
@jpienaar @eric-k256 Just pinging on this PR. Thanks!

**Comment by gbaned** [comment]
Hi @rafaelubalmw Can you please resolve conflicts? Thank you!

**Comment by rafaelubalmw** [comment]
We seem to be clearer now about what to do with ops that produce dialects other than TOSA. I'll wait until this PR (https://github.com/tensorflow/tensorflow/pull/61660) is merged and will rearrange this according to the new file structure.

**Comment by gbaned** [comment]
Hi @rafaelubalmw Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @rafaelubalmw Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @rafaelubalmw  I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for your contribution!

**Pull request closed without merging**
