### PR TITLE
Branch 171199546

### PR DESCRIPTION
**Pull request by av8ramit**

### CODE REVIEW

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by yaroslavvb** [comment]
@akshayka what about also allowing graph_callable on functions that have no arguments?

**Comment by akshayka** [comment]
@yaroslavvb Great question; that's actually already supported. Just pass an empty list to graph_callable.

```
@graph_callable([])
def my function():
   ...
```

**Pull request closed without merging**
