### PR TITLE
LoggingTensorHook to read from runconfig in Estimator

### PR DESCRIPTION
**Pull request by ankitvgupta**
Fixes https://github.com/tensorflow/tensorflow/issues/17115
Based on the suggestion made in this pull request: https://github.com/tensorflow/tensorflow/pull/17117

### CODE REVIEW

**Comment by xiejw** [comment]
Thanks for the contribution. Do you mind also updating the RunConfig pydoc for the log_step_count_steps? I think currently, it says:


     log_step_count_steps: The frequency, in number of global steps, that the
          global step/sec will be logged during training

 which does not mention the effect this PR adds.

**Comment by ankitvgupta** [comment]
@xiejw Sure, done! Let me know if you think there is a better wording.

**Review by xiejw — APPROVED** [review]
Thanks!

**Comment by ankitvgupta** [comment]
@xiejw Great thanks! Is there anything I need to do to run the CI tests?

**Comment by xiejw** [comment]
To my best knowledge, one of the admin will handle the rest for you. If you do not see that in one week, feel free to ping the thread and I will help. 

Thank you again.

**Comment by ankitvgupta** [comment]
@xiejw Looks like it hasn't run yet. Is it because there is still an "awaiting review" label?

**Comment by xiejw** [comment]
I reached the yifeif and hope now the labels are correct.

**Comment by ankitvgupta** [comment]
@xiejw Looks like there was an infrastructure error. Does that mean the code was broken or things just need to be re-run?

**Comment by xiejw** [comment]
I kicked multiple runs over the weekend. I believe all errors were transient. Tests look great now.

**Pull request merged**
