### PR TITLE
[Intel MKL] Adding support for perchannel requantization

### PR DESCRIPTION
**Pull request by nammbash**
### 1. Adding two new hidden operators to support requantization to be performed perchannel and provided the mkl implementations for the same.

        1. requantize_per_channel_op
        2. requantization_range_per_channel_op

### 2. Provided Unit test to test the implementation logic of both these above mentioned ops.

### CODE REVIEW

**Comment by nammbash** [comment]
Can you review and approve this PR please

**Comment by nammbash** [comment]
@rthadur . I see that this PR has not been assigned to anybody. Can someone please assign this to someone?

**Comment by ebrevdo** [comment]
there seems to be an issue in merging.  see if you can create a clean fork of tensorflow HEAD, apply your small diff to it, and then submit that.

**Comment by nammbash** [comment]
thank you @ebrevdo I opened a new one without the git rebasing problems here in a new PR https://github.com/tensorflow/tensorflow/pull/25203

**Pull request closed without merging**
