### PR TITLE
Adding progress bar also while evaluating the model

### PR DESCRIPTION
**Pull request by ashutosh1919**
fixes tensorflow/addons issue [#1620](https://github.com/tensorflow/addons/issues/1620).  

@gabrieldemarmiesse, rather than changing methods like `on_test_batch_begin()`, I have changed the `configure_callback()` method which is used to add `ProgBar` in train, now with this change, it will add in test too. Also, there is not requirement of model history logs while test progress bar. So, I have not added that one.  

@gabrieldemarmiesse and @mihaimaruseac - Please review.

### CODE REVIEW

**Comment by zaccharieramzi** [comment]
Hi @ashutosh1919 this is not what I meant to say in https://github.com/tensorflow/addons/issues/1620. I really wanted to have the `tqdm` progress bar which is very specific, as a callback (note that there is already a progress bar when using `evaluate`). 
Also here, you added the progress bar in any case, no matter if verbose or not, which is probably not something we want.

I think the best way to solve this issue is as @gabrieldemarmiesse pointed out to implement the `on_test_batch_(begin|end)` methods.

**Comment by gabrieldemarmiesse** [comment]
I believe the pull request should be made to tensorflow/addons, not tensorflow/tensorflow indeed, specificly for the tqdm callback.

**Comment by ashutosh1919** [comment]
@zaccharieramzi and @gabrieldemarmiesse, working on it. Please give me sometime. Let me understand the problem. I will soon raise PR there.

**Comment by ashutosh1919** [comment]
Closing this one.

**Pull request closed without merging**
