### PR TITLE
extend tf.select to broadcast a scalar condition #3945

### PR DESCRIPTION
**Pull request by Mistobaan**
continuation of pull request GH-3995

### CODE REVIEW

**Comment by Mistobaan** [comment]
@drpngx re-posted

**Comment by drpngx** [comment]
@benoitsteiner Continued discussion here...

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by benoitsteiner — APPROVED** [review]

**Comment by benoitsteiner** [comment]
@Mistobaan thanks for your new PR. I looked at the code, and it looked great, so I merged it.

**Comment by Mistobaan** [comment]
🎉  wohoo 🎉

**Pull request merged**
