### PR TITLE
Update layers.py

### PR DESCRIPTION
**Pull request by shreyneil**
I have added a check on beta with reference to the following issue raised.
https://github.com/tensorflow/tensorflow/issues/11673

Please verify and get back.
Thank you.

### CODE REVIEW

**Comment by caisq** [comment]
@shreyneil Do you mind adding a unit test for this fix?

**Comment by shreyneil** [comment]
Sir the following test cases take cover exhaustive cases for the combination of center with zero_debias_moving_mean parameter.
Please verify.
Test Case 1:
import tensorflow as tf
a = tf.placeholder(tf.float32, shape=(10, 10, 10, 10))
b = tf.contrib.layers.batch_norm(a, center=False, data_format='NCHW',
                                 zero_debias_moving_mean=True)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

Test Case 2:
import tensorflow as tf
a = tf.placeholder(tf.float32, shape=(10, 10, 10, 10))
b = tf.contrib.layers.batch_norm(a, center=False, data_format='NCHW',
                                 zero_debias_moving_mean=False)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

Test Case 3:
import tensorflow as tf
a = tf.placeholder(tf.float32, shape=(10, 10, 10, 10))
b = tf.contrib.layers.batch_norm(a, center=True, data_format='NCHW',
                                 zero_debias_moving_mean=True)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

Test Case 4:
import tensorflow as tf
a = tf.placeholder(tf.float32, shape=(10, 10, 10, 10))
b = tf.contrib.layers.batch_norm(a, center=True, data_format='NCHW',
                                 zero_debias_moving_mean=False)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

**Comment by vrv** [comment]
Would it be worth adding a test to layers_test to validate this fix?

**Comment by rmlarsen** [comment]
@shreyneil Please update the unit tests to validate the fix.

**Comment by jhseu** [comment]
Closing out for now due to being stalled. Feel free to reopen or send a new pull request with the test added. Thanks!

**Pull request closed without merging**
