### PR TITLE
[ROCm] Introduce TENSORFLOW_USE_ROCM macro to support operators on ROCm

### PR DESCRIPTION
**Pull request by whchung**
Enable supported TensorFlow operators on ROCm. Use TENSORFLOW_USE_ROCM macro
which was introduced in PR#20277.

Only trivial ones which doesn't inlcude custom CUDA / HIP GPU kernels are
included this commit. Subsequent ones would cover other operators.

### CODE REVIEW

**Comment by jlebar** [comment]
@ymodak, I work primarily on XLA, I'm not familiar with TF core, so I'm not comfortable reviewing this.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @benbarsdell, @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @benbarsdell, @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @benbarsdell, @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by whchung** [comment]
Will break this PR into smaller ones.

**Pull request closed without merging**
