### PR TITLE
Update bazel toolchains dependency.

### PR DESCRIPTION
**Pull request by av8ramit**
PiperOrigin-RevId: 186650360

### CODE REVIEW

**Review by case540 — APPROVED** [review]
lgtm

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
The failure looks legitimate, have we seen this before?

**Comment by av8ramit** [comment]
@gunan I cannot tell since tests didn't even build prior to this. Can I still merge and debug that test after?

**Comment by gunan** [comment]
I was thinking when we were doing the release.
But sure, let's first merge and then debug. I think this test was passing when we did 1.6, so I would like to avoid disabling the test for 1.6 release.

**Pull request merged**
