### PR TITLE
examples change to sklearn dataset load method

### PR DESCRIPTION
**Pull request by hevensun**
The same to #7310 but change the commit account.

change tf.contrib.learn.datasets.load_dataset('boston') to sklearn.datasets.load_boston()
change tf.contrib.learn.datasets.load_dataset('iris') to sklearn.datasets.load_iris()
because when run examples/learn/iris.py and examples/learn/boston.py with python35, errors like followings occurs:
UnicodeEncodeError: 'utf-16-le' codec can't encode character '\udcds' in position 166: surrogates not allowed
so it's better to change sklearn's method.

### CODE REVIEW

**Comment by vrv** [comment]
Great, CLA looks good, thanks.  We're quite busy through tomorrow, but we'll look at this soon.

**Comment by dandelionmane** [comment]
Based on the discussion at https://github.com/tensorflow/tensorflow/pull/7310, it sounds like we should fix the unicode compat bug in tf.contrib.learn.datasets.load_dataset rather than adding more dependencies on SKLearn. @hevensun can you take that on?

**Comment by hevensun** [comment]
@dandelionmane  first I want to fix this unicode error using sklearn's datasets load  method for other users to use, then I will deep into the unicode compat bug in tf.contrib.learn.datasets.load_dataset to if I can fix it.

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Pull request merged**
