### PR TITLE
Change tensorflow GPU docker file to be compatible with Kubernetes GPU doc

### PR DESCRIPTION
**Pull request by a6802739**
@angersson, reference to #26393.

I'm not sure if I was in the right direction, I change some package version from CUDA9.0 to CUDA10.0,
I'll check if it's  compatible Kubernetes GPU settings.

Hope could get some advice from you.

Thanks.

### CODE REVIEW

**Comment by angersson** [comment]
@a6802739 Our Docker images are all built from the `dockerfiles` directory, rather than the `docker` directory (I'm trying to remove the old directory in https://github.com/tensorflow/tensorflow/pull/26113, because it's confusing). Can you take a look there, instead?

**Comment by a6802739** [comment]
@angersson Thanks for your response, so I should wait for #26113 done, and then merge the change after?

**Comment by angersson** [comment]
If you like, you can start looking at the dockerfiles/ directory now. No need to wait on that change -- all it does is delete the old directory.

**Comment by a6802739** [comment]
@angersson, Thanks! Just done that as you say. Please take a loot at it.

**Comment by angersson** [comment]
@a6802739, please take a look at the README in the dockerfiles directory. You'll have to update the partial files and recreate the images from there.

**Comment by rthadur** [comment]
@a6802739 can you please check latest review comments.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
