### PR TITLE
Switch back to Ubuntu 14.04 for our releases.

### PR DESCRIPTION
**Pull request by jhseu**
Haven't tested this yet. Letting Jenkins do the work.

@caisq fyi. Note that we should keep our Docker Hub images on Ubuntu 16.04 because that fixes the bugs users encounter.

Note for others looking at this change: we're downgrading to Ubuntu 14.04 for official releases so that it links against the older version of glibc and allows for wider compatibility.

### CODE REVIEW

**Comment by jhseu** [comment]
@gunan this is mostly a revert plus some minor version changes and edits.

**Comment by yaroslavvb** [comment]
I'm expecting you'll see some jemalloc caused SEGFAULTS on process shutdown, since that happens in 14.04 but not 16.04

**Comment by jhseu** [comment]
We're using the other fix here: reinstalling numpy without OpenBLAS support.

**Comment by caisq** [comment]
@jhseu Thanks for cc'ing me. +1 for keeping the Docker Hub and gcr.io images at 16.04.

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
Thank you very much for the change!

**Pull request merged**
