### PR TITLE
fix incorrect example code

### PR DESCRIPTION
**Pull request by dotm**
based on https://stackoverflow.com/questions/40904979/the-print-of-string-constant-is-always-attached-with-b-intensorflow

### CODE REVIEW

**Comment by dotm** [comment]
I signed it!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 62 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 77 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request closed without merging**
