### PR TITLE
Add empty linker_bin_path

### PR DESCRIPTION
**Pull request by Flamefire**
Fixes regression introduced in #34202

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by Flamefire** [comment]
Possibly unrelated failure:

> WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/aws/aws-sdk-cpp/archive/1.5.8.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

followed by
> gcc: error: unrecognized command line option '-std=c++14'

**Comment by rthadur** [comment]
@Flamefire can you please resolve conflicts ?

**Comment by Flamefire** [comment]
Someone already reverted the commit that introduced the bug fixed here. I updated the commit message to the original one now: See #34202

**Review by mihaimaruseac — APPROVED** [review]

**Comment by rthadur** [comment]
@Flamefire can you please fix the build failures ?

**Comment by Flamefire** [comment]
This seems to be (again) the error that it can't download  https://storage.googleapis.com/mirror.tensorflow.org/github.com/aws/aws-sdk-cpp/archive/1.5.8.tar.gz. I don't know where this is coming from but certainly not from this PR. I suspect something in the CI setup of TensorFlow has changed? Any ideas?

**Comment by mihaimaruseac** [comment]
These should be fixed soon, sorry for the delay

**Pull request merged**
