### PR TITLE
Portability fix for StrAppend

### PR DESCRIPTION
**Pull request by snnn**
#15557

### CODE REVIEW

**Comment by drpngx** [comment]
I am not sure this is correct. If the initial string is empty, not append?

**Comment by snnn** [comment]
Here the size of the "result" string is after expending? empty() is a shortcut for size()==0 ?

**Comment by drpngx** [comment]
If you do `string x; StrAppend(&x, 1, 2)` then you're supposed to get `"12"`.  I think your check will not result in the correct string.

**Comment by snnn** [comment]
Ok... Let me check it. Sorry, I'm in vacation right now. I'll do it in this weekend.

**Comment by snnn** [comment]
Close it as you will migrate these GTL containers to ABSL.

**Pull request closed without merging**
