### PR TITLE
[tflite] fix missing labels.txt in model maker tutorial

### PR DESCRIPTION
**Pull request by freedomtan**
fix the problem of missing `labels.txt` in #43463 and #41470

### CODE REVIEW

**Review by teijeong — APPROVED** [review]

**Comment by ziyeqinghan** [comment]
Please hold on this PR. We hope to make with_metadata=True in the colab. Will update the colab description instead.

**Comment by gbaned** [comment]
@ziyeqinghan  Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@ziyeqinghan Any update on this PR? Please. Thanks!

**Comment by ziyeqinghan** [comment]
We have updated the colab to describe with_metadata more clear.

**Pull request closed without merging**
