### PR TITLE
Updates so that Demo app can build in current Android Studio.

### PR DESCRIPTION
**Pull request by qu1j0t3**
This has been tested on OS X Android Studio 3.2.1.

### CODE REVIEW

**Comment by qu1j0t3** [comment]
Corrected committer email.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by hgadig** [comment]
@qu1j0t3  Could you please rebase to resolve the branch conflicts. Thanks !

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
