### PR TITLE
remove SRU num_units == x.shape[-1] restriction

### PR DESCRIPTION
**Pull request by stegben**
Based on the [author's response](https://github.com/taolei87/sru/issues/12), the restriction is unnecessary. Simply add a linear transform to the input will solve the issue

#13094

### CODE REVIEW

**Comment by rmlarsen** [comment]
@stegben can you add a unit test that exercises the new behavior?

**Review by ebrevdo — APPROVED** [review]

**Review by ebrevdo — CHANGES_REQUESTED** [review]
Oops; forgot, can you add a unit test?

**Comment by stegben** [comment]
sure!

**Comment by stegben** [comment]
@rmlarsen plz help me trigger CI, thank you!

**Comment by stegben** [comment]
@rmlarsen I fixed the test again. I've test it on my laptop so it should be OK this time

**Comment by rmlarsen** [comment]
@stegben Thanks!

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@ebrevdo this is good to go, right? Could you hit approve to confirm?

**Review by ebrevdo — APPROVED** [review]

**Comment by stegben** [comment]
@ebrevdo @rmlarsen Thanks a lot!

**Pull request merged**
