### PR TITLE
[TFLite] Add int16x8 support for DEPTH_TO_SPACE and SPACE_TO_DEPTH operators

### PR DESCRIPTION
**Pull request by johan-gras**
Hello,

This PR adds int16x8 support for DEPTH_TO_SPACE and SPACE_TO_DEPTH operators.

Thanks,
Johan.

### CODE REVIEW

**Comment by gbaned** [comment]
@miaout17 Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
Hi @johan-gras Can you please resolve conflicts? Thank you!

**Comment by psunn** [comment]
Hi @gbaned, can we re-open this ticket?
We have some new updates on the PR, and we're still eager to merge it into upstream.

**Comment by gbaned** [comment]
> Hi @gbaned, can we re-open this ticket? We have some new updates on the PR, and we're still eager to merge it into upstream.

Hi @psunn Sure thing, reopened the PR. Thank you!

**Comment by gbaned** [comment]
Hi @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @zichuan-wei Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @zichuan-wei Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @johan-gras , Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @johan-gras , Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @johan-gras , Can you please resolve the conflicts? Thank you!

**Pull request closed without merging**
