### PR TITLE
 [ROCm] Fix for ROCM CSB breakage - 210322 

### PR DESCRIPTION
**Pull request by deven-amd**
## 1
The following commit adds GPU support for int32/int64 support for the Unique/UniqueWithCounts ops, but breaks ROCm build in the process

02585ac

```
tensorflow/core/kernels/unique_op_gpu.cu.cc:292:9: error: no matching constructor for initialization of 'gpuprim::TransformInputIterator<int, SegmentIndicatorFunctor<unsigned long, int>, gpuprim::CountingInputIterator<int>>' (aka 'transform_iterator<rocprim::counting_iterator<int, long>, tensorflow::(anonymous namespace)::SegmentIndicatorFunctor<unsigned long, int>, int>')
        segment_indicator_iter(0, {sorted_input_ptr});
        ^                      ~~~~~~~~~~~~~~~~~~~~~
tensorflow/core/kernels/unique_op_gpu.cu.cc:176:12: note: in instantiation of member function 'tensorflow::UniqueOpGPU<unsigned long, int>::ComputeAsync' requested here
  explicit UniqueOpGPU(OpKernelConstruction* context)
           ^
tensorflow/core/kernels/unique_op_gpu.cu.cc:461:27: note: in instantiation of member function 'tensorflow::UniqueOpGPU<unsigned long, int>::UniqueOpGPU' requested here
TF_CALL_REAL_NUMBER_TYPES(REGISTER_UNIQUE_GPU);
```

This PR/commit disables ROCm support for newly added ops to get the CSB passing again. We are looking into resolving the build errors, and will file a separate PR to re-enable ROCm functionality for the same. This PR commit also adds the `no_rocm` tag to a couple of unit tests that start failing as a consequence of lack of ROCm support for these ops.

```
//tensorflow/python/keras/optimizer_v2:adamax_test_gpu                   FAILED in 3 out of 3 in 7.0s
//tensorflow/python/training:adam_test_gpu                               FAILED in 3 out of 3 in 6.3s
```

## 2 

 The following commit adds a new unit-test which is failing on the ROCm platform

50f8897

```
//tensorflow/python/keras/distribute:dataset_creator_model_fit_test_gpu  FAILED in 3 out of 3 in 112.5s
```

This commit adds a `no_rocm` tag to temporarily disable that unit-test on ROCm.

---------------------------------------------------------

/cc @cheshire @chsigg

### CODE REVIEW

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping.  Need this PR to get ROCm builds passing again.

**Review by cheshire — APPROVED** [review]

**Comment by gbaned** [comment]
@deven-amd  Can you please check build failures. Thanks!

**Comment by deven-amd** [comment]
@gbaned all the build error point to 

```
ERROR: /tmpfs/bazel_output/_bazel_kbuilder/f2d52ca1f092ccbe254cc98c3dc90790/external/llvm-project/llvm/BUILD
```

don't think they are related to the change in this PR.

can you trigger the tests again...maybe whatever was causing them, has been fixed.

**Comment by deven-amd** [comment]
@gbaned , rebased my branch to resolve the merge conflict

**Comment by deven-amd** [comment]
@gbaned , rebased (again) my branch to resolve the merge conflict

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
rebased PR to resolve merge conflict

@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
rebased PR again to resolve merge conflict

@cheshire @chsigg gentle ping

**Review by chsigg — APPROVED** [review]

**Comment by rthadur** [comment]
@deven-amd can you please resolve conflicts

**Comment by deven-amd** [comment]
@rthadur rebased the PR again to resolve the merge conflict.

@chsigg will need your approval again

**Review by rthadur — APPROVED** [review]

**Pull request merged**
