### PR TITLE
GPU version for OSX also available

### PR DESCRIPTION
**Pull request by bquast**
as per: #664

### CODE REVIEW

**Comment by benoitsteiner** [comment]
Can you sign the CLA? Thanks.

**Comment by bquast** [comment]
sorry, signed the CLA but forgot to reply to the email, just did that.

**Comment by bquast** [comment]
I signed it!

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by benoitsteiner** [comment]
Thanks, I'll merge it as soon as the test results come back.

**Comment by danmane** [comment]
There was a test failure, but given that this pull request only touches markdown I'm concluding the test failure was a flake. Merging, thanks for the fix!

**Pull request merged**
