### PR TITLE
Clarified the correct way of passing the inputs and assigning the datatypes

### PR DESCRIPTION
**Pull request by kavilivishnu**
Hello @Venkat6871 , @eggie5 

Fixed the #69284 issue.

I believe we just have to make sure to pass the inputs and the be consistent with the datatypes that we are using. 

The vital observation that I was able to make is the indices list and the relationship between var and accum parameters, and the relationship between grad and indices.

I mentioned the obseravations clearly in the file where I believe we could include that in the website - [https://www.tensorflow.org/api_docs/python/tf/raw_ops/ResourceSparseApplyAdagrad](url), so that user's will have a better understanding of the usage of ResourceSparseApplyAdagrad

```

#Considered some example values for testing

var = tf.Variable([1.0, 2.2, 0.3, 6.3, 5.2], dtype=tf.complex64)
accum = tf.Variable([0.1, 0.2, 0.3, 1.1, 9.1], dtype=tf.complex64)
accum2 = tf.Variable([0, 1.2, -3.3], dtype=tf.complex64)
lr = tf.Variable(0.01, dtype=tf.complex64)
grad = tf.constant([1.1, 5.2, 7.3, 9.2], dtype=tf.complex64)
momentum = 0.9


#Actual values to be used
var = tf.Variable([1.0, 2.0, 3.0, 4.0, 5.0], dtype=tf.complex64)
accum = tf.Variable([0.1, 0.2, 0.3, 0.4, 0.5], dtype=tf.complex64) 
accum2 = tf.Variable([0, 1.2, -3.3], dtype=tf.complex64) 
lr = tf.Variable(0.01, dtype=tf.complex64)
grad = tf.constant([0.1, 0.2, 0.3, 0.4], dtype=tf.complex64)

#Executed Successfully
tf.raw_ops.ResourceSparseApplyAdagrad(
    var=var.handle,
    accum=accum.handle,
    lr=lr,
    grad=grad,
    # indices=tf.constant([1, 2, 3, 4]),
    indices=tf.constant([0, 1, 2, 3]),
    # use_locking=False,
)
```

I believe the same rules apply to ResourceSparseApplyAdagradDA and ResourceSparseApplyAdagradV2.

Please correct me if I am wrong.

Thanks!

### CODE REVIEW

**Comment by kavilivishnu** [comment]
@gbaned , The AMD ROCm -- Community CI Build keeps failing. Can you please let me know if I am authorized to look into this? If yes, I will proceed and will try to fix it. If not, could you please help me?

Thanks!

**Comment by keerthanakadiri** [comment]
Hi @penpornk Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @kavilivishnu Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @kavilivishnu, Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @kavilivishnu, Can you please resolve the conflicts? Thank you!

**Pull request closed without merging**
