### PR TITLE
DeepDream tutorial notebook for TensorFlow

### PR DESCRIPTION
**Pull request by znah**

### CODE REVIEW

**Comment by znah** [comment]
CLA update

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
This should be put into the models repo: https://github.com/tensorflow/models

**Comment by znah** [comment]
https://github.com/tensorflow/models/pull/22

**Comment by znah** [comment]
Should me move it to 'examples' instead?

**Pull request merged**
