### PR TITLE
Fixing quotes in documentation. See https://github.com/tensorflow/ten…

### PR DESCRIPTION
**Pull request by aodhan-domhnaill**
Fixes https://github.com/tensorflow/tensorflow/issues/8207

### CODE REVIEW

**Comment by aidan-plenert-macdonald** [comment]
I signed it!

It is under my company Knuedge

**Comment by dandelionmane** [comment]
Looks like CLABot isn't satisfied. Can you verify that the commit email address matches an email that you've signed a CLA under? (see the links at the bottom of CLABot's last message)

**Comment by aidan-plenert-macdonald** [comment]
They are having the same problem here. I don't know how to check which email is my  CLA one, but if I remember correctly, it was the amacdonald@knuedge.com one.

**Comment by aidan-plenert-macdonald** [comment]
They are having the same problem here. I don't know how to check which email is my  CLA one, but if I remember correctly, it was the amacdonald@knuedge.com one.

**Comment by martinwicke** [comment]
@willnorris Is there a way I can check whether someone else has a proper CLA? It would be useful and I wouldn't have to bother you.

**Comment by aidan-plenert-macdonald** [comment]
I was told by @acozzette in https://github.com/google/protobuf/pull/2807#issuecomment-286154817 that it was because I might not be in the Google Group for my company. I am working it out now

**Comment by willnorris** [comment]
> @willnorris Is there a way I can check whether someone else has a proper CLA? It would be useful and I wouldn't have to bother you.

go/cla-signers

**Comment by martinwicke** [comment]
@willnorris Thanks!

**Comment by gunan** [comment]
Is it also possible that your commit email is not your company email (I did not check it, but this is a common cause).
You can git commit --amend to edit the commit author

**Comment by aidan-plenert-macdonald** [comment]
I signed it!

**Comment by martinwicke** [comment]
Is the commit email the right one?

**Comment by aidan-plenert-macdonald** [comment]
I think I fixed the CLA. I had to amend a couple commits to get the emails right

**Comment by martinwicke** [comment]
@Staberinde are you ok with your commit ending up in TensorFlow?

**Comment by martinwicke** [comment]
a83cc3f should not be part of this PR -- can you rebase to head?

**Comment by aidan-plenert-macdonald** [comment]
@martinwicke  I think its gone.

**Comment by martinwicke** [comment]
Thanks! Just waiting for @Staberinde for CLA consent.

Jenkins, test this please?

**Comment by aidan-plenert-macdonald** [comment]
Jenkins, test this please?

**Comment by aidan-plenert-macdonald** [comment]
I signed it!

**Comment by drpngx** [comment]
So... the CLA is still not registered as signed. We definitely need this.

**Comment by aidan-plenert-macdonald** [comment]
I signed it!

**Comment by martinwicke** [comment]
@staberinde, are you ok with this commit ending up in TensorFlow?

**Comment by martinwicke** [comment]
Ok, sorry @aidan-plenert-macdonald. This is very annoying, but since we don't have explicit consent from @Staberinde I cannot merge this PR. Can you make a new one that has only your commits?

I will close this one.

**Pull request closed without merging**
