### PR TITLE
Remove redundant arguments of ImageResizerState's API

### LINKED ISSUE #47789: ImageResizerState's public function contains redundant arguments
`ImageResizerState::ValidateAndCreateOutput` needs a tensor as the second argument. Actually it is unnecessary. Because `input` can be retrieved through `context->input(0)`. `ImageResizerGradientState` has a similar issue.

### PR DESCRIPTION
**Pull request by CyangXu**
Fix #47789 

Currently `ImageResizerState::ValidateAndCreateOutput()` needs a tensor as the second argument. Actually its value can be retrieved through `context->input(0)`. Hence, it is unnecessary to provide the second argument. `ImageResizerGradientState::ValidateAndCreateOutput()` has the similar issue.

This code change removes the redundant arguments of the two functions mentioned above.

### CODE REVIEW

**Comment by CyangXu** [comment]
One test seems to have been impending for a long time. How should I deal with it?

**Review by mihaimaruseac — APPROVED** [review]

**Review by hyeygit — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by CyangXu** [comment]
I notice that one test failed. How should I re-run the test? Just want to rule out the possibility that the failing test is flaky.

**Review by rohan100jain — APPROVED** [review]

**Comment by CyangXu** [comment]
Is there anyone to tell me how I should fix the broken test of MacOS CPU Python3?  I am able to run a test through the command like `bazel test //tensorflow/lite/python:lite_test`. But how should I verify the test for MacOS?

**Comment by gbaned** [comment]
@rohan100jain Can you please take a look on the above comment from @CyangXu. Thanks!

**Comment by hyeygit** [comment]
@CyangXu I apologize for the delay. I brought in the PR and ran the tests. It should be merged in shortly.

**Comment by CyangXu** [comment]
@hyeygit No worry! Thank you for your reply! By the way, I have a question: if my CL really breaks a MacOS test, how should I reproduce it on my side? Do I have to own a MacOS machine to reproduce the failure?

**Comment by hyeygit** [comment]
@CyangXu MacOS would be necessary; however, even with a mac, it's not easy to replicate the environment the CI test is run in, unfortunately. The best path forward is to remind us in the comments that windows/macos tests are failing and someone from tensorflow should help you test them further.

**Pull request merged**
