### PR TITLE
Generalize MinMax monotonic optimizer

### PR DESCRIPTION
**Pull request by lgeiger**
This PR generalizes the MinMax monotonic optimizer to support `SegmentMax`, `UnsortedSegmentMax` and `ArgMax` operations.

This will improve performance of such operations after monotonic function.

### CODE REVIEW

**Review by ezhulenev — APPROVED** [review]

**Comment by lgeiger** [comment]
Thanks for the fast merge! You might want to check out #25332 too, which adds support for more monotonic ops.

**Comment by lgeiger** [comment]
@ezhulenev Can you tell me the reason why this PR was reverted in 0507dba17e223053f7d7f19e8e546ca6a97b1d8b?

It would be great to get feedback so I can fix it.

**Comment by ezhulenev** [comment]
@lgeiger it failed in https://gist.github.com/ezhulenev/0b8ab39e1533933197a61f23675e719b

```AssertionError: 0.5 != 0.90499997 within 2 places```

Sorry didn't have time to dig into it myself, had to rollback to unblock other teams. Probably something simple.

**Comment by lgeiger** [comment]
No worries, thanks for the link. I'll take a look.

**Comment by lgeiger** [comment]
It seems like my changes are fine but surfaced a bug in the existing algorithmic optimizer.
I made a PR to fix this: #25535

I'll reopen this PR after #25535 and #25438 are merged or rejected.

**Pull request merged**
