### PR TITLE
Fix typo in GL converter error log

### PR DESCRIPTION
**Pull request by anotheruserofgithub**

### CODE REVIEW

**Comment by anotheruserofgithub** [comment]
Please @nutsiepully would you mind validating this PR? This is just a small fix for a typo in a log message. Thank you!

**Comment by anotheruserofgithub** [comment]
@nutsiepully

**Comment by gbaned** [comment]
@nutsiepully Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
@nutsiepully Can you please review this PR ? Thank you!

**Comment by anotheruserofgithub** [comment]
@nutsiepully @gbaned Could you merge this now, please? It has been a very long time since this PR has been opened.
If you really need more explanations about this PR, I can certainly provide you with a detailed manuscript.

**Comment by gbaned** [comment]
@nutsiepully Can you please review this PR ? Thank you!

**Review by haozha111 — APPROVED** [review]

**Comment by anotheruserofgithub** [comment]
Thanks @haozha111! I can't see the details of the failing checks, what should I do to make it work?

**Comment by gbaned** [comment]
> Thanks @haozha111! I can't see the details of the failing checks, what should I do to make it work?

Hi @anotheruserofgithub No action pending from end at this moment. We will let you know if anything needs to do from your side. Thank you!

**Pull request merged**
