### PR TITLE
Fix audio bugs in the Arduino micro_speech example

### PR DESCRIPTION
**Pull request by hollance**
In the Arduino audio_provider, the LatestAudioTimestamp increments twice as fast as real-time because the audio code confuses bytes and samples (one sample is two bytes).

Related to this, the feature_provider sometimes attempts to read too far ahead from the audio capture buffer.

### CODE REVIEW

**Review by petewarden — APPROVED** [review]
Thanks for catching this, hopefully it will improve the recognition quality a lot!

**Review by petewarden — CHANGES_REQUESTED** [review]
Sorry for the change, but I took a deeper look at the feature provider changes and I'm not as certain they're correct, especially since the feature provider test is now failing.

The Arduino CaptureSamples() change is definitely a bug fix though (and quite a nasty one, thanks for the catch). Could you break up this PR so we can accept part that while we look at the feature provider modifications more closely?

**Comment by hollance** [comment]
I spent quite a bit of time verifying that the feature provider gives the exact same spectrograms as the TF training script. With my changes to the feature provider, the spectrograms computed by the Arduino code are exactly the same as the ones computed by the TF op, when given the same WAV input. (Except for occasional rounding errors, most likely because of the quantization that happens on the Arduino.)

If the test case fails now, it's probably because there is a bug in the test case. ;-)

**Comment by hollance** [comment]
I'm not entirely sure what I need to do to change this PR to only include the audio capture changes. Undo the feature provider changes in my local copy and commit?

**Comment by hollance** [comment]
OK I guess that worked. :-)

Another thing I should mention that is related to the audio capture is the following definition:

```
// The size of the input time series data we pass to the FFT to produce the
// frequency information. This has to be a power of two, and since we're dealing
// with 30ms of 16KHz inputs, which means 480 samples, this is the next value.
constexpr int kMaxAudioSampleSize = 512;
```

This comment is misleading. It's OK to define `kMaxAudioSampleSize = 480` because the FFT will copy this data into its own buffer and pad it out to the nearest power of two.

In `GetAudioSamples` in arduino/audio_provider.cc, I would personally change the line,

```
*audio_samples_size = kMaxAudioSampleSize;
```

to:

```
*audio_samples_size = duration_sample_count;
```

and possibly include an assertion that makes sure `duration_sample_count <= kMaxAudioSampleSize`. The code will work either way, but now the `audio_samples_size` is correct whenever the requested duration is less than 30ms.

**Comment by hollance** [comment]
I opened a new issue for the feature_provider changes: https://github.com/tensorflow/tensorflow/issues/46365

**Comment by mateusz-holenko** [comment]
I encountered the same problem when preparing/testing a simulation in [Renode](renode.io).

Testing on the looped [mock data](https://github.com/tensorflow/tensorflow/blob/4c63c27f015d09c35e11506651f0642245d522ef/tensorflow/lite/micro/examples/micro_speech/yes_1000ms_sample_data.cc#L21), original code gives me the following results:
```
4 bytes lost due to alignment. To avoid this loss, please make sure the tensor_arena is 16 bytes aligned.
Heard yes (210) @2016ms
Heard yes (201) @4512ms
Heard yes (204) @6240ms
Heard yes (203) @8512ms
Heard yes (211) @10272ms
Heard yes (201) @12480ms
Heard yes (203) @14240ms
Heard yes (207) @16512ms
Heard yes (225) @18272ms
Heard yes (206) @20544ms
Heard yes (205) @22304ms
Heard yes (209) @26272ms
Heard yes (206) @28544ms
```

wheres with the proposed changes I get:
```
4 bytes lost due to alignment. To avoid this loss, please make sure the tensor_arena is 16 bytes aligned.
Heard yes (205) @1488ms
Heard yes (251) @2992ms
Heard yes (246) @4496ms
Heard yes (250) @6000ms
Heard yes (246) @7520ms
Heard yes (246) @9024ms
Heard yes (246) @10528ms
Heard yes (250) @12032ms
Heard yes (245) @13552ms
Heard yes (245) @15056ms
Heard yes (245) @16560ms
Heard yes (251) @18080ms
Heard yes (245) @19584ms
Heard yes (244) @21088ms
Heard yes (245) @22592ms
Heard yes (252) @24112ms
Heard yes (245) @25616ms
```

I can also confirm that I noticed problems with reading "outside the buffer" as reported in #46365 - in my case I changed the frequency of PDM interrupts (it's easy to simulate in Renode, probably not that easy to test on the actual HW) and noticed that TF tried to access samples "from the future" - not yet read from the device.

**Comment by advaitjain** [comment]
With TFLM moving to its own GitHub repository, we are not going to be merging any TFLM specific pull requests in the TensorFlow repository starting today.

I am closing the current PR but please feel free to open a new PR in https://github.com/tensorflow/tflite-micro/.

https://groups.google.com/a/tensorflow.org/g/micro/c/W4DACgjPmOE

**Pull request closed without merging**
