### PR TITLE
Changed non-public ops to public ones in tutorials

### LINKED ISSUE #811: relu_layer doesn't appear in tensorflow.org/versions/master/api_docs
relu_layer has a docstring in the code, but it doesn’t appear in the tensorflow online documentation for some reason.

In case it is not public yet, it should be removed from the cifar example.

### PR DESCRIPTION
**Pull request by cesarsalgado**
Replace non-public `tf.nn.relu_layer` and `tf.nn.xw_plus_b` by a combination of `tf.nn.relu`, `tf.matmul` and `tf.add`.

This PR fixes #811.

### CODE REVIEW

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Our CI is currently broken, will pick this back up when we fix it. Looks good to me though. Can you squash the commits?

**Comment by cesarsalgado** [comment]
My PR has only one commit. What do you mean by squash the commits?

**Comment by vrv** [comment]
@martinwicke: the merge commits are dropped when we rebase, so this is actually fine as is.

**Comment by cesarsalgado** [comment]
Maybe I shouldn't press the button `Update branch` in the Github UI next time? Or it doesn't matter?

**Comment by vrv** [comment]
@tensorflow-jenkins, test this please

@cesarsalgado: shouldn't matter as long as there are no conflicts with the base branch :)

**Comment by vrv** [comment]
Merged.

**Pull request closed without merging**
