### PR TITLE
MKL: Making MKL-DNN default

### PR DESCRIPTION
**Pull request by agramesh1**
Make Tensroflow use MKL DNN by default if --config=mkl is used when building

### CODE REVIEW

**Comment by rmlarsen** [comment]
@agramesh1 Thanks for the PR. Please sign the CLA.

**Comment by rmlarsen** [comment]
@agramesh1 Please rebase.

**Comment by agramesh1** [comment]
@rmlarsen ok will rebase.

**Comment by agramesh1** [comment]
@rmlarsen rebase completed.

**Comment by rmlarsen** [comment]
@agramesh1 Thanks!

**Review by andydavis1 — APPROVED** [review]

**Comment by andydavis1** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@andydavis1 Thanks, for reviewing. I can sheperd this PR along from here.

**Comment by agramesh1** [comment]
@rmlarsen thanks.

**Pull request merged**
