### PR TITLE
Remove executable mode from `tensorflow/c/eager/c_api.h`.

### PR DESCRIPTION
**Pull request by dan-zheng**
This fixes a codesigning issue for [Swift for TensorFlow](https://github.com/apple/swift/tree/tensorflow) on macOS:
```console
# After this patch: https://github.com/apple/swift/pull/26595.
$ ./swift/utils/build-toolchain-tensorflow --pkg
...
error: cannot parse the debug map for './/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2019-08-09-a.xctoolchain/usr/Library/Frameworks/LLDB.framework/Versions/A/Resources/Swift/macosx/x86_64/modulemaps/CTensorFlow/c_api_eager.h-e': The file was not recognized as a valid object file
error: cannot parse the debug map for './/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2019-08-09-a.xctoolchain/usr/Library/Frameworks/LLDB.framework/Versions/A/Resources/Swift/macosx/x86_64/modulemaps/CTensorFlow/c_api_eager.h': The file was not recognized as a valid object file
```

### CODE REVIEW

**Review by saeta — APPROVED** [review]

**Comment by alextp** [comment]
I'm confused, github says "no changes"?

**Comment by alextp** [comment]
Oh I see nvm

**Review by alextp — APPROVED** [review]

**Comment by dan-zheng** [comment]
> I'm confused, github says "no changes"?

There are no content changes - the change is actually `chmod -x tensorflow/c/eager/c_api.h`.

Prior to this patch, `tensorflow/c/eager/c_api.h` had executable mode for some reason. Other headers in the same directory do not:

```
$ ls -alh tensorflow/c/eager
total 600
drwxr-xr-x  15 danielzheng  primarygroup   480B Jul 31 14:26 .
drwxr-xr-x  51 danielzheng  primarygroup   1.6K Jul 31 14:26 ..
-rw-r--r--   1 danielzheng  primarygroup   9.9K Jul 31 14:26 BUILD
-rw-r--r--   1 danielzheng  primarygroup    40K Jul 31 14:26 c_api.cc
-rwxr-xr-x   1 danielzheng  primarygroup    23K Jul 31 14:26 c_api.h
-rw-r--r--   1 danielzheng  primarygroup   5.6K Jul 31 14:26 c_api_debug.cc
-rw-r--r--   1 danielzheng  primarygroup   1.8K Jul 31 14:26 c_api_debug_test.cc
-rw-r--r--   1 danielzheng  primarygroup    21K Jul 31 14:26 c_api_experimental.cc
-rw-r--r--   1 danielzheng  primarygroup    18K Jul 31 14:26 c_api_experimental.h
-rw-r--r--   1 danielzheng  primarygroup    20K Jul 31 14:26 c_api_experimental_test.cc
-rw-r--r--   1 danielzheng  primarygroup    10K Jul 31 14:26 c_api_internal.h
-rw-r--r--   1 danielzheng  primarygroup    69K Jul 31 14:26 c_api_test.cc
-rw-r--r--   1 danielzheng  primarygroup   8.1K Jul 31 14:26 c_api_test_util.cc
-rw-r--r--   1 danielzheng  primarygroup   2.5K Jul 31 14:26 c_api_test_util.h
-rw-r--r--   1 danielzheng  primarygroup    43K Jul 31 14:26 tape.h
```

The fact that `c_api.h` has executable mode causes a codesigning issue for Swift for TensorFlow, as mentioned in the PR description.

**Comment by rthadur** [comment]
@yifeif @mihaany idea how we merge this ?

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Oh, it needs to be fixed from the inside. Let me give it a try

**Comment by mihaimaruseac** [comment]
Actually, seems copybara migration worked this time. It will get merged, thanks for the PR

**Comment by rthadur** [comment]
@mihaimaruseac thank you

**Pull request merged**
