### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by NianzuMa**
You may refer to this page, right? The original link is not accessible.

### CODE REVIEW

**Comment by gunan** [comment]
Thanks for the contribution.
It looks like the when I go to the link you provided, I get a https error. is that expected?

Also, could you sign the CLA and then comment on the PR as instructed by the google cla bot?

**Comment by JacobIsrael123** [comment]
I signed the CLA, thanks.

**Comment by JacobIsrael123** [comment]
The original link shows me on the page:
Not Found
The requested URL /~treebank/ was not found on this server.
Do not know how it looks like on your computer?

So I think updated it to some other pages. 
the link I provided
previous link

**Comment by jhseu** [comment]
Our system doesn't show the CLA as being signed yet. Mind trying again?

**Review by jhseu — APPROVED** [review]

**Comment by gunan** [comment]
@JacobIsrael123 you will need to type exactly `I signed it!` to your comment, as it is a bot checking this.
I was not able to manually verify your CLA.

**Comment by JacobIsrael123** [comment]
I signed it!

**Comment by gunan** [comment]
We still cannot verify your CLA, neother manually, nor automated.
Is it possible your commit email is hidden in github, or is it maybe different than the one you used to sign the Google CLA?

**Comment by JacobIsrael123** [comment]
Sorry for the inconvenience. My first time to contribute. What do you mean it is hidden in github? I changed the setting-> profile-> public email to my email signed email just now. Could you double check?

**Comment by JacobIsrael123** [comment]
Maybe that matters. Google bot auto-replied just now.

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by JacobIsrael123** [comment]
Why the link is still not updated in the website after this issue already been merged?
[https://www.tensorflow.org/tutorials/recurrent/](https://www.tensorflow.org/tutorials/recurrent/)

**Comment by jhseu** [comment]
There's a separate process to push updates to the website.

**Pull request merged**
