### PR TITLE
Fix wrong instruction of TFLite iOS profiling tool

### PR DESCRIPTION
**Pull request by hajuho**
Change to "Product > Profile" from "Product > Scheme"

### CODE REVIEW

**Comment by hajuho** [comment]
@googlebot I signed it!

**Comment by abattery** [comment]
@yyoon could you review this PR?

**Review by yyoon — APPROVED** [review]

**Comment by yyoon** [comment]
Thanks, @hajuho :)

**Comment by hajuho** [comment]
@abattery @yyoon nice to see you again :)

**Pull request merged**
