### PR TITLE
[CMake] Extract list of python modules

### PR DESCRIPTION
**Pull request by Androbin**
Progressing #10296
@drpngx FYI

### CODE REVIEW

**Review by mrry — APPROVED** [review]
This is super useful, thanks! Once this is submitted, we should be able to add a Bazel test that compares the set of modules in the Bazel-generated PIP package to this list, and points developers to this file if something is missing. This should save a lot of headaches when keeping the CMake build in sync :).

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by Androbin** [comment]
@mrry Exactly my point.
Changes in `contrib` are often not reflected properly.
E.g. `stateless` and `stat_summarizer` have the `python` directory missing.
Couldn't they be just implied if present?

**Comment by mrry** [comment]
@Androbin That would be nice! If there's a reliable automatic way to get CMake to infer the set of Python modules that matches the Bazel behavior (and doesn't introduce a dependency on Bazel), I'd be in favor of that. In the meantime, once this change is submitted, adding a Bazel presubmit test that keeps the two in sync still seems like an improvement.

**Comment by Androbin** [comment]
I did some diffing for the `python` directories and found the following:

Exists in filetree but not in list:
`batching/python`
`fused_conv/python`
`hooks/python`
`lite/python`
`lite/toco/python`
`receptive_field/python`
`stat_summarizer/python`
`stateless/python`

Exists in list but not in filetree:
`keras/python`

**Comment by mrry** [comment]
Expanding it out to the union of modules in the filetree and the current list seems fine. I assume there are some modules in the filetree that aren't explicitly imported by one of their parents or tested by the tests in `tf_tests.cmake`, and so we've been getting away with having fewer modules in the CMake files.

**Comment by Androbin** [comment]
@mrry I added the proto files that I listed above.
For the python modules, we probably wanna list all sub-directories with a `__init__.py` file?

**Comment by mrry** [comment]
It's more than that, because Bazel will add an empty `__init__.py` file to any directories containing a `py_library` when it builds the PIP package.

**Comment by Androbin** [comment]
@mrry I did some more diffing. Shall I patch these discrepancies?

Exists in filetree but not in list:
`batching/kernels`
`batching/python`
`batching/python/ops`
`boosted_trees/kernels`
`data/kernels`
`fused_conv/kernels`
`fused_conv/python`
`fused_conv/python/ops`
`hooks/python`
`image/kernels`
`image/python/kernel_tests`
`input_pipeline/kernels`
`kfac/python/kernel_tests`
`legacy_seq2seq/python/kernel_tests`
`lite/kernels`
`lite/python`
`lite/toco/python`
`receptive_field/python`
`signal/python/kernel_tests`
`solvers/python/kernel_tests`
`sparsemax/python/kernel_tests`
`stat_summarizer/python`
`stateless/python`
`stateless/python/kernel_tests`
`tensor_forest/kernels`

Exists in list but not in filetree:
`keras/python`
`metrics/kernels`

**Comment by Androbin** [comment]
I'll try to extract the `.proto` files as well.

**Comment by mrry** [comment]
@Androbin I don't think we need to include the `kernel_tests` directories, since those should be purely test code that doesn't need to be included in the PIP package. (Indeed, we probably include too much test code in the current wildcards, and it would be nice to prune it if possible.)

**Comment by Androbin** [comment]
@mrry What about these?
`tensorflow/python/kernel_tests/...`
`tensorflow/contrib/testing/...`

**Comment by mrry** [comment]
I think `tensorflow/contrib/testing` is needed because it gets loaded when you use `tf.contrib`, but `tensorflow/python/kernel_tests` can be omitted.

**Comment by mrry** [comment]
Thanks for the updates! Still LGTM. 

@tensorflow-jenkins test this please.

**Comment by Androbin** [comment]
@mrry `//bazel_pip/tensorflow/contrib/data/python/kernel_tests:prefetch_dataset_op_test FAILED`

**Comment by mrry** [comment]
Hmm, looks like the PIP tests can depend on code in `tensorflow/python/kernel_tests` :(. Yes, the easiest move would be to add `tensorflow/python/kernel_tests` back to the list of modules.

However, AFAICT that was a Bazel test that failed, and you didn't change the Bazel rules, so I'm confused as to why that test did not pass.

**Comment by Androbin** [comment]
AFAICT, the test is initiated via `//tensorflow/python/kernel_tests/BUILD` which depends on the PIP package and the `contrib` part is delegated to `CMake`.

**Comment by Androbin** [comment]
Anyway, I'll rebase to the latest stable commit on `master`.

**Comment by Androbin** [comment]
@mrry Failing test `//tensorflow/contrib/data/python/kernel_tests:prefetch_dataset_op_test` was introduced in commit d73e8b36d1332723f5819d07f8c44e88c49c7cec

**Comment by mrry** [comment]
Thanks for digging into it. I'm guessing it's broken for all PRs, and perhaps not part of our internal presubmit matrix?

@saxenasaurabh Can you take a look? I think the problem is that libraries in `tensorflow/python/kernel_tests/...` (in particular, `dataset_serialization_test_base.py` don't get included in the PIP package, so PIP tests that depend on them don't work. However, I'm not sure why some tests pass and some don't.

**Comment by Androbin** [comment]
@mrry Now with `tensorflow/python/kernel_tests` back in, could you make Jenkins retest please?

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by Androbin** [comment]
@mrry I had to do another rebase to resolve a merge conflict with bf001790e84e6dc433ac39e7eaba7896b70fa9ef.

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by Androbin** [comment]
Kernel Tests still failing @saxenasaurabh Any updates yet?

**Comment by Androbin** [comment]
@mrry I think the CI server broke.

**Comment by Androbin** [comment]
@mrry There was a flawky commit from the last rebase. Also, I had to resolve another merge conflict.
@saxenasaurabh Any updates concerning the PIP package?
@sb2nov Any updates concerning the CI infrastructure?

**Comment by sb2nov** [comment]
I fixed most of the broken tests on head last night so kicking off a new building. Let's see how that goes.

**Comment by sb2nov** [comment]
I'm going to merge this for now as the pip issue is known and can be addressed in another PR

**Comment by Androbin** [comment]
@mrry Which of the other `cmake` scripts you think would benefit the most from extraction?

**Pull request merged**
