### PR TITLE
Pylint: Revert W + TODO

### PR DESCRIPTION
**Pull request by bhack**
https://github.com/tensorflow/tensorflow/issues/55442

### CODE REVIEW

**Review by mdanatg — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Oh, this accidentally renames the file :(

**Comment by bhack** [comment]
How it was changed?

**Comment by mihaimaruseac** [comment]
63dzVBiycCn8mzC

**Comment by bhack** [comment]
I've just edited this file on github directly. Who have renamed the file? copybara?

**Comment by bhack** [comment]
Ok yes sorry.. it was just a bad copy paste in the Github form.

**Comment by mihaimaruseac** [comment]
It's all good, just an accidental rename. Fixed now.

**Pull request merged**
