### PR TITLE
[XLA] Make postorder stack adds a channel once for all predecessors

### PR DESCRIPTION
**Pull request by zhuzilin**
This is a PR from JIZHI, the AI platform in Tencent.

This pr slightly changes `ComputeInstructionPostOrder` and make the stack for post order traversal not add the whole channel for every predecessor. And example is the `InstructionPostOrderWithAllReduce` test case in `hlo_computation_test.cc`:
```
HloModule Module

add {
  lhs = f32[] parameter(0)
  rhs = f32[] parameter(1)
  ROOT add = f32[] add(lhs, rhs)
}

ENTRY entry {
  param = f32[128] parameter(0), sharding={maximal device=0}
  crs0 = f32[128] all-reduce(param),
    replica_groups={{0}}, channel_id=1, to_apply=add,
    sharding={maximal device=0}
  crs1 = f32[128] all-reduce(param),
    replica_groups={{0}}, channel_id=1, to_apply=add,
    sharding={maximal device=1}
  add = f32[128] add(crs0, crs0), sharding={maximal device=0}
  ROOT t = (f32[128], f32[128]) tuple(add, crs1)
})
```
The `add` instruction would add `crs0` and `crs1` twice in the old implementation. And this pr avoids that.

Thank you for your time on reviewing this pr.

### CODE REVIEW

**Comment by zhuzilin** [comment]
@gbaned 
It seems that @joker-eph seldom reviews pr unrelated to mlir. Shall we add another reviewer for this? Thank you!

**Review by jpienaar — COMMENTED** [review]
@hyouklee might be the most appropriate person/know who would be to review this. I don't know the invariants expected from post order wrt all reduce here, so would prefer someone who knows this code better.

Would there be any way to surface the behavior? E.g., could a test a be written which would serve to document behavior.

**Comment by cheshire** [comment]
@yunxing @majnemer could you take a look?

**Review by dimvar — COMMENTED** [review]
Thanks for the PR @zhuzilin. I think it's probably better to leave the method as is though. There is already a CHECK_EQ in HloComputation::MakeInstructionPostOrder which ensures that we put each instruction in post_order only once. So, the PR tries to optimize the number of times a channel instruction goes in the worklist (dfs_stack), but it makes the code a little longer and less clear, so I don't think there is a clear win here.

**Comment by zhuzilin** [comment]
@dimvar 
Sure :).

**Pull request closed without merging**
