### PR TITLE
optimize_for_inference script removes dropouts

### PR DESCRIPTION
**Pull request by kbalka**
This PR is addressing feature request: 

https://github.com/tensorflow/tensorflow/issues/5867

It enhances optimize_for_inference script with function of removing dropouts. 
Since dropouts are only valuable during training, it makes sense to remove them for inference.

### CODE REVIEW

**Comment by kbalka** [comment]
@concretevitamin Thanks for pointing this out, just pushed an update, let me know whether it works for you

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by kbalka** [comment]
@petewarden Is there anything I can do to help with review process ?

**Comment by slanab** [comment]
@kbalka Does not seem to work if dropout layer is in a namespace (ex. cnn_conv_A2e/dropout/dropout/mul)

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by kbalka** [comment]
@slanab I've pushed an update, it should work for dropouts in namespaced

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 23 days with no activity and the `awaiting review` label has been applied.

**Comment by slanab** [comment]
Is this code expected to work on a model written using Estimator API?

**Comment by damiles** [comment]
Hi all, i test this PR and works fine, i optimize a Model created with estimator API (@slanab) with this code. Removing this nodes are important for inference if you want to use in third party libraries like OpenCV DNN modules that not support dropout nodes for inference.
 
Good job @kbalka , waiting for the @petewarden review and commit to master branch.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 30 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 45 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 60 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 75 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Review by petewarden — COMMENTED** [review]
Sorry for the very slow review on this one. We have deprecated optimize_for_inference in favor of the graph transform tool's newer functionality, but these changes seem reasonable, thanks.

**Comment by nanshihui** [comment]
sorry. In my graph ,    use the way above. could not removes dropouts. anyone know it ?
`
0 inputs Placeholder
1 keep Placeholder
2 conv1d/kernel Const
3 conv1d/bias Const
4 conv1d/conv1d/ExpandDims/dim Const
5 conv1d/conv1d/ExpandDims ExpandDims
└─── 0 ─ inputs
└─── 1 ─ conv1d/conv1d/ExpandDims/dim
6 conv1d/conv1d/ExpandDims_1/dim Const
7 conv1d/conv1d/ExpandDims_1 ExpandDims
└─── 0 ─ conv1d/kernel
└─── 1 ─ conv1d/conv1d/ExpandDims_1/dim
8 conv1d/conv1d/Conv2D Conv2D
└─── 0 ─ conv1d/conv1d/ExpandDims
└─── 1 ─ conv1d/conv1d/ExpandDims_1
9 conv1d/conv1d/Squeeze Squeeze
└─── 0 ─ conv1d/conv1d/Conv2D
10 conv1d/BiasAdd BiasAdd
└─── 0 ─ conv1d/conv1d/Squeeze
└─── 1 ─ conv1d/bias
11 conv1d/Relu Relu
└─── 0 ─ conv1d/BiasAdd
12 max_pooling1d/ExpandDims/dim Const
13 max_pooling1d/ExpandDims ExpandDims
└─── 0 ─ conv1d/Relu
└─── 1 ─ max_pooling1d/ExpandDims/dim
14 max_pooling1d/MaxPool MaxPool
└─── 0 ─ max_pooling1d/ExpandDims
15 max_pooling1d/Squeeze Squeeze
└─── 0 ─ max_pooling1d/MaxPool
16 conv1d_1/kernel Const
17 conv1d_1/bias Const
18 conv1d_1/conv1d/ExpandDims/dim Const
19 conv1d_1/conv1d/ExpandDims ExpandDims
└─── 0 ─ max_pooling1d/Squeeze
└─── 1 ─ conv1d_1/conv1d/ExpandDims/dim
20 conv1d_1/conv1d/ExpandDims_1/dim Const
21 conv1d_1/conv1d/ExpandDims_1 ExpandDims
└─── 0 ─ conv1d_1/kernel
└─── 1 ─ conv1d_1/conv1d/ExpandDims_1/dim
22 conv1d_1/conv1d/Conv2D Conv2D
└─── 0 ─ conv1d_1/conv1d/ExpandDims
└─── 1 ─ conv1d_1/conv1d/ExpandDims_1
23 conv1d_1/conv1d/Squeeze Squeeze
└─── 0 ─ conv1d_1/conv1d/Conv2D
24 conv1d_1/BiasAdd BiasAdd
└─── 0 ─ conv1d_1/conv1d/Squeeze
└─── 1 ─ conv1d_1/bias
25 conv1d_1/Relu Relu
└─── 0 ─ conv1d_1/BiasAdd
26 max_pooling1d_1/ExpandDims/dim Const
27 max_pooling1d_1/ExpandDims ExpandDims
└─── 0 ─ conv1d_1/Relu
└─── 1 ─ max_pooling1d_1/ExpandDims/dim
28 max_pooling1d_1/MaxPool MaxPool
└─── 0 ─ max_pooling1d_1/ExpandDims
29 max_pooling1d_1/Squeeze Squeeze
└─── 0 ─ max_pooling1d_1/MaxPool
30 conv1d_2/kernel Const
31 conv1d_2/bias Const
32 conv1d_2/conv1d/ExpandDims/dim Const
33 conv1d_2/conv1d/ExpandDims ExpandDims
└─── 0 ─ max_pooling1d_1/Squeeze
└─── 1 ─ conv1d_2/conv1d/ExpandDims/dim
34 conv1d_2/conv1d/ExpandDims_1/dim Const
35 conv1d_2/conv1d/ExpandDims_1 ExpandDims
└─── 0 ─ conv1d_2/kernel
└─── 1 ─ conv1d_2/conv1d/ExpandDims_1/dim
36 conv1d_2/conv1d/Conv2D Conv2D
└─── 0 ─ conv1d_2/conv1d/ExpandDims
└─── 1 ─ conv1d_2/conv1d/ExpandDims_1
37 conv1d_2/conv1d/Squeeze Squeeze
└─── 0 ─ conv1d_2/conv1d/Conv2D
38 conv1d_2/BiasAdd BiasAdd
└─── 0 ─ conv1d_2/conv1d/Squeeze
└─── 1 ─ conv1d_2/bias
39 conv1d_2/Relu Relu
└─── 0 ─ conv1d_2/BiasAdd
40 max_pooling1d_2/ExpandDims/dim Const
41 max_pooling1d_2/ExpandDims ExpandDims
└─── 0 ─ conv1d_2/Relu
└─── 1 ─ max_pooling1d_2/ExpandDims/dim
42 max_pooling1d_2/MaxPool MaxPool
└─── 0 ─ max_pooling1d_2/ExpandDims
43 max_pooling1d_2/Squeeze Squeeze
└─── 0 ─ max_pooling1d_2/MaxPool
44 conv1d_3/kernel Const
45 conv1d_3/bias Const
46 conv1d_3/conv1d/ExpandDims/dim Const
47 conv1d_3/conv1d/ExpandDims ExpandDims
└─── 0 ─ max_pooling1d_2/Squeeze
└─── 1 ─ conv1d_3/conv1d/ExpandDims/dim
48 conv1d_3/conv1d/ExpandDims_1/dim Const
49 conv1d_3/conv1d/ExpandDims_1 ExpandDims
└─── 0 ─ conv1d_3/kernel
└─── 1 ─ conv1d_3/conv1d/ExpandDims_1/dim
50 conv1d_3/conv1d/Conv2D Conv2D
└─── 0 ─ conv1d_3/conv1d/ExpandDims
└─── 1 ─ conv1d_3/conv1d/ExpandDims_1
51 conv1d_3/conv1d/Squeeze Squeeze
└─── 0 ─ conv1d_3/conv1d/Conv2D
52 conv1d_3/BiasAdd BiasAdd
└─── 0 ─ conv1d_3/conv1d/Squeeze
└─── 1 ─ conv1d_3/bias
53 conv1d_3/Relu Relu
└─── 0 ─ conv1d_3/BiasAdd
54 max_pooling1d_3/ExpandDims/dim Const
55 max_pooling1d_3/ExpandDims ExpandDims
└─── 0 ─ conv1d_3/Relu
└─── 1 ─ max_pooling1d_3/ExpandDims/dim
56 max_pooling1d_3/MaxPool MaxPool
└─── 0 ─ max_pooling1d_3/ExpandDims
57 max_pooling1d_3/Squeeze Squeeze
└─── 0 ─ max_pooling1d_3/MaxPool
58 Reshape/shape Const
59 Reshape Reshape
└─── 0 ─ max_pooling1d_3/Squeeze
└─── 1 ─ Reshape/shape
60 dropout/Shape Shape
└─── 0 ─ Reshape
61 dropout/random_uniform/min Const
62 dropout/random_uniform/max Const
63 dropout/random_uniform/RandomUniform RandomUniform
└─── 0 ─ dropout/Shape
64 dropout/random_uniform/sub Sub
└─── 0 ─ dropout/random_uniform/max
└─── 1 ─ dropout/random_uniform/min
65 dropout/random_uniform/mul Mul
└─── 0 ─ dropout/random_uniform/RandomUniform
└─── 1 ─ dropout/random_uniform/sub
66 dropout/random_uniform Add
└─── 0 ─ dropout/random_uniform/mul
└─── 1 ─ dropout/random_uniform/min
67 dropout/add Add
└─── 0 ─ keep
└─── 1 ─ dropout/random_uniform
68 dropout/Floor Floor
└─── 0 ─ dropout/add
69 dropout/div RealDiv
└─── 0 ─ Reshape
└─── 1 ─ keep
70 dropout/mul Mul
└─── 0 ─ dropout/div
└─── 1 ─ dropout/Floor
71 dense/kernel Const
72 dense/bias Const
73 dense/MatMul MatMul
└─── 0 ─ dropout/mul
└─── 1 ─ dense/kernel
74 dense/BiasAdd BiasAdd
└─── 0 ─ dense/MatMul
└─── 1 ─ dense/bias
75 softmax_tensor_output Softmax
└─── 0 ─ dense/BiasAdd

Process finished with exit code 0

`

**Comment by kbalka** [comment]
> sorry. In my graph , use the way above. could not removes dropouts. anyone know it ?
> `
> 0 inputs Placeholder
> 1 keep Placeholder
> 2 conv1d/kernel Const
> 3 conv1d/bias Const
> 4 conv1d/conv1d/ExpandDims/dim Const
> 5 conv1d/conv1d/ExpandDims ExpandDims
> └─── 0 ─ inputs
> └─── 1 ─ conv1d/conv1d/ExpandDims/dim
> 6 conv1d/conv1d/ExpandDims_1/dim Const
> 7 conv1d/conv1d/ExpandDims_1 ExpandDims
> └─── 0 ─ conv1d/kernel
> └─── 1 ─ conv1d/conv1d/ExpandDims_1/dim
> 8 conv1d/conv1d/Conv2D Conv2D
> └─── 0 ─ conv1d/conv1d/ExpandDims
> └─── 1 ─ conv1d/conv1d/ExpandDims_1
> 9 conv1d/conv1d/Squeeze Squeeze
> └─── 0 ─ conv1d/conv1d/Conv2D
> 10 conv1d/BiasAdd BiasAdd
> └─── 0 ─ conv1d/conv1d/Squeeze
> └─── 1 ─ conv1d/bias
> 11 conv1d/Relu Relu
> └─── 0 ─ conv1d/BiasAdd
> 12 max_pooling1d/ExpandDims/dim Const
> 13 max_pooling1d/ExpandDims ExpandDims
> └─── 0 ─ conv1d/Relu
> └─── 1 ─ max_pooling1d/ExpandDims/dim
> 14 max_pooling1d/MaxPool MaxPool
> └─── 0 ─ max_pooling1d/ExpandDims
> 15 max_pooling1d/Squeeze Squeeze
> └─── 0 ─ max_pooling1d/MaxPool
> 16 conv1d_1/kernel Const
> 17 conv1d_1/bias Const
> 18 conv1d_1/conv1d/ExpandDims/dim Const
> 19 conv1d_1/conv1d/ExpandDims ExpandDims
> └─── 0 ─ max_pooling1d/Squeeze
> └─── 1 ─ conv1d_1/conv1d/ExpandDims/dim
> 20 conv1d_1/conv1d/ExpandDims_1/dim Const
> 21 conv1d_1/conv1d/ExpandDims_1 ExpandDims
> └─── 0 ─ conv1d_1/kernel
> └─── 1 ─ conv1d_1/conv1d/ExpandDims_1/dim
> 22 conv1d_1/conv1d/Conv2D Conv2D
> └─── 0 ─ conv1d_1/conv1d/ExpandDims
> └─── 1 ─ conv1d_1/conv1d/ExpandDims_1
> 23 conv1d_1/conv1d/Squeeze Squeeze
> └─── 0 ─ conv1d_1/conv1d/Conv2D
> 24 conv1d_1/BiasAdd BiasAdd
> └─── 0 ─ conv1d_1/conv1d/Squeeze
> └─── 1 ─ conv1d_1/bias
> 25 conv1d_1/Relu Relu
> └─── 0 ─ conv1d_1/BiasAdd
> 26 max_pooling1d_1/ExpandDims/dim Const
> 27 max_pooling1d_1/ExpandDims ExpandDims
> └─── 0 ─ conv1d_1/Relu
> └─── 1 ─ max_pooling1d_1/ExpandDims/dim
> 28 max_pooling1d_1/MaxPool MaxPool
> └─── 0 ─ max_pooling1d_1/ExpandDims
> 29 max_pooling1d_1/Squeeze Squeeze
> └─── 0 ─ max_pooling1d_1/MaxPool
> 30 conv1d_2/kernel Const
> 31 conv1d_2/bias Const
> 32 conv1d_2/conv1d/ExpandDims/dim Const
> 33 conv1d_2/conv1d/ExpandDims ExpandDims
> └─── 0 ─ max_pooling1d_1/Squeeze
> └─── 1 ─ conv1d_2/conv1d/ExpandDims/dim
> 34 conv1d_2/conv1d/ExpandDims_1/dim Const
> 35 conv1d_2/conv1d/ExpandDims_1 ExpandDims
> └─── 0 ─ conv1d_2/kernel
> └─── 1 ─ conv1d_2/conv1d/ExpandDims_1/dim
> 36 conv1d_2/conv1d/Conv2D Conv2D
> └─── 0 ─ conv1d_2/conv1d/ExpandDims
> └─── 1 ─ conv1d_2/conv1d/ExpandDims_1
> 37 conv1d_2/conv1d/Squeeze Squeeze
> └─── 0 ─ conv1d_2/conv1d/Conv2D
> 38 conv1d_2/BiasAdd BiasAdd
> └─── 0 ─ conv1d_2/conv1d/Squeeze
> └─── 1 ─ conv1d_2/bias
> 39 conv1d_2/Relu Relu
> └─── 0 ─ conv1d_2/BiasAdd
> 40 max_pooling1d_2/ExpandDims/dim Const
> 41 max_pooling1d_2/ExpandDims ExpandDims
> └─── 0 ─ conv1d_2/Relu
> └─── 1 ─ max_pooling1d_2/ExpandDims/dim
> 42 max_pooling1d_2/MaxPool MaxPool
> └─── 0 ─ max_pooling1d_2/ExpandDims
> 43 max_pooling1d_2/Squeeze Squeeze
> └─── 0 ─ max_pooling1d_2/MaxPool
> 44 conv1d_3/kernel Const
> 45 conv1d_3/bias Const
> 46 conv1d_3/conv1d/ExpandDims/dim Const
> 47 conv1d_3/conv1d/ExpandDims ExpandDims
> └─── 0 ─ max_pooling1d_2/Squeeze
> └─── 1 ─ conv1d_3/conv1d/ExpandDims/dim
> 48 conv1d_3/conv1d/ExpandDims_1/dim Const
> 49 conv1d_3/conv1d/ExpandDims_1 ExpandDims
> └─── 0 ─ conv1d_3/kernel
> └─── 1 ─ conv1d_3/conv1d/ExpandDims_1/dim
> 50 conv1d_3/conv1d/Conv2D Conv2D
> └─── 0 ─ conv1d_3/conv1d/ExpandDims
> └─── 1 ─ conv1d_3/conv1d/ExpandDims_1
> 51 conv1d_3/conv1d/Squeeze Squeeze
> └─── 0 ─ conv1d_3/conv1d/Conv2D
> 52 conv1d_3/BiasAdd BiasAdd
> └─── 0 ─ conv1d_3/conv1d/Squeeze
> └─── 1 ─ conv1d_3/bias
> 53 conv1d_3/Relu Relu
> └─── 0 ─ conv1d_3/BiasAdd
> 54 max_pooling1d_3/ExpandDims/dim Const
> 55 max_pooling1d_3/ExpandDims ExpandDims
> └─── 0 ─ conv1d_3/Relu
> └─── 1 ─ max_pooling1d_3/ExpandDims/dim
> 56 max_pooling1d_3/MaxPool MaxPool
> └─── 0 ─ max_pooling1d_3/ExpandDims
> 57 max_pooling1d_3/Squeeze Squeeze
> └─── 0 ─ max_pooling1d_3/MaxPool
> 58 Reshape/shape Const
> 59 Reshape Reshape
> └─── 0 ─ max_pooling1d_3/Squeeze
> └─── 1 ─ Reshape/shape
> 60 dropout/Shape Shape
> └─── 0 ─ Reshape
> 61 dropout/random_uniform/min Const
> 62 dropout/random_uniform/max Const
> 63 dropout/random_uniform/RandomUniform RandomUniform
> └─── 0 ─ dropout/Shape
> 64 dropout/random_uniform/sub Sub
> └─── 0 ─ dropout/random_uniform/max
> └─── 1 ─ dropout/random_uniform/min
> 65 dropout/random_uniform/mul Mul
> └─── 0 ─ dropout/random_uniform/RandomUniform
> └─── 1 ─ dropout/random_uniform/sub
> 66 dropout/random_uniform Add
> └─── 0 ─ dropout/random_uniform/mul
> └─── 1 ─ dropout/random_uniform/min
> 67 dropout/add Add
> └─── 0 ─ keep
> └─── 1 ─ dropout/random_uniform
> 68 dropout/Floor Floor
> └─── 0 ─ dropout/add
> 69 dropout/div RealDiv
> └─── 0 ─ Reshape
> └─── 1 ─ keep
> 70 dropout/mul Mul
> └─── 0 ─ dropout/div
> └─── 1 ─ dropout/Floor
> 71 dense/kernel Const
> 72 dense/bias Const
> 73 dense/MatMul MatMul
> └─── 0 ─ dropout/mul
> └─── 1 ─ dense/kernel
> 74 dense/BiasAdd BiasAdd
> └─── 0 ─ dense/MatMul
> └─── 1 ─ dense/bias
> 75 softmax_tensor_output Softmax
> └─── 0 ─ dense/BiasAdd
> 
> Process finished with exit code 0
> 
> `
Hi, there are few ways the dropout can be implemented in the graph - looks like you have an use case which is currently not supported by script. I'd love to add support for it, but this PR will not be merged anyway. I think you should use new graph transform tool functionality instead.

**Pull request closed without merging**
