### PR TITLE
add visibility to  //tensorflow/contrib/tensor_forest/proto:fertile_stats_proto

### PR DESCRIPTION
**Pull request by yupbank**
Since the proto is a public-visible and TreePath depending on the proto 

Let's make it public...

### CODE REVIEW

**Comment by jhseu** [comment]
This doesn't seem right. That rule doesn't directly depend on the proto file.

**Comment by yupbank** [comment]
what?!?

`TreePath` is being save in protobuf, while there is no python package to deserialized it!

So that there is no way to a user to read from the prediction.

**Comment by yupbank** [comment]
https://github.com/tensorflow/tensorflow/blob/ced7455a9c3d2ff1570f9752c9ca432af1913167/tensorflow/contrib/tensor_forest/python/tensor_forest.py#L108  
user can specify `inference_tree_paths` and if so, it would https://github.com/tensorflow/tensorflow/blob/ced7455a9c3d2ff1570f9752c9ca432af1913167/tensorflow/contrib/tensor_forest/kernels/model_ops.cc#L237  SerializeAsString and output

but if there is no `fertile_stats_proto_pb2.py`, user from python side can never have a chance to really use it.

**Comment by jhseu** [comment]
Ah, thanks for the explanation.

**Review by jhseu — APPROVED** [review]

**Pull request merged**
