### PR TITLE
Fix minor typo and math rendering format in linear operator related apis

### PR DESCRIPTION
**Pull request by imsheridan**
This PR is to fix some minor typo and mathe rendering format in linear operator related doc strings.
- Fix a minor typo format for below line in [tensor_rank](https://www.tensorflow.org/api_docs/python/tf/linalg/LinearOperator#tensor_rank);
image

- Fix some math equation rendering format in linear operator related api doc strings, like the one example [LinearOperatorLowRankUpdate](https://www.tensorflow.org/api_docs/python/tf/linalg/LinearOperatorLowRankUpdate#base_operator) as below;
image

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 21 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by av8ramit** [comment]
@imsheridan please resolve conflicts. @andrewharp is this okay with you to merge?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
