### PR TITLE
add Erlang distribution

### PR DESCRIPTION
**Pull request by Mistobaan**
This is in the family of the Gamma distributions but with a=2.0.

### CODE REVIEW

**Comment by drpngx** [comment]
This looks like the exponential distribution? It's really a special case of Erlang.

**Comment by Mistobaan** [comment]
Yes, is another special case of the Gamma distribution, but instead of alpha=1 is alpha=2.0. I am referencing the Machine Learning through a Probabilistic Perspective book.

**Comment by drpngx** [comment]
What's the difference with [exp](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distributions/python/ops/exponential.py#L37) then?

**Comment by Mistobaan** [comment]
On a second thought, the Gamma is a generalization of the Erlang, where instead of using the factorial it uses the Gamma function. The only advantage of adding the Erlang is to constrain the scale parameter to just integers and optimize the kernel to just compute the factorial instead of the gamma function.

**Pull request closed without merging**
