### PR TITLE
Add scalar test for neg op

### PR DESCRIPTION
**Pull request by siju-samuel**
Add scalar test for neg op

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @karimnosseir: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @karimnosseir: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Review by karimnosseir — DISMISSED** [review]

**Comment by rthadur** [comment]
@siju-samuel can you please re-base your branch to resolve conflicts.

**Comment by siju-samuel** [comment]
@karimnosseir @rthadur I have rebased, please check and approve again. Thanks

**Review by karimnosseir — APPROVED** [review]

**Comment by rthadur** [comment]
Changes are merged by this commit ` 0ec5db4` this is a duplicate [PR](https://github.com/tensorflow/tensorflow/pull/27018) , thank you

**Pull request closed without merging**
