### PR TITLE
Tests for minimum/maximum quantization quantization

### PR DESCRIPTION
**Pull request by wwwind**
Problem description:
MINIMUM and MAXIMUM operations were not quantized properly. Specifically, the problem was that only one of the inputs was quantized while another one was left in the original data type. Because of this reason, TFLite interpreter was failing to prepare since quantization params of ops did not match.

Problem cause:
MINIMUM and MAXIMUM operators were created in the way that they only had one input, not two. Hence when looping through inputs while quantizing them, only one of two inputs was quantized.

Problem fix:
Change the definition of the aforementioned properties.

This patch contains fixes for the problem described above.

- Properties of MINIMUM and MAXIMUM operators were altered to have
two inputs rather than one. This is safe since both 1.* and 2.* branches
have only two inputs for these ops
- Test suite for testing Minimum and Maximum ops quantization is added
- Two small binaries have been added for testing purposes

This is an updated version of the [PR](https://github.com/tensorflow/tensorflow/pull/32582). The old PR was raised by KonstantinARM, who has left ARM.

### CODE REVIEW

**Comment by gbaned** [comment]
@wwwind Can you please resolve conflicts? Thanks!

**Comment by suharshs** [comment]
Comment from Anton: 
"Hi @suharshs. Thanks for checking this PR. Can you please review the PR #34484 we raised to replace this one? - It extends your fix to cover for the case of inputs with different quantization parameters, and includes the C++ tests to cover both aspects of the problem."


Reply:
I think the current code should apply rescales on the inputs correctly as it does for Concat operations. The combination of arbitrary_inputs and restrict_same_input_output_scale should be sufficient AFAICT. Does that make sense, or am I missing something?

**Comment by suharshs** [comment]
The c++ tests would still be welcome additions though. Thanks!

**Comment by wwwind** [comment]
Hi Suharsh, 

In our original fix we kept the fixed number of inputs to 2, but, yes, arbitrary_inputs variable solves the issue. I removed traces of the original fix and left only C++ tests.
Could you please review them ?

Thanks!

**Review by suharshs — DISMISSED** [review]

**Comment by gbaned** [comment]
@wwwind Could you please address Ubuntu Sanity errors? Thanks!

**Comment by wwwind** [comment]
Hi @suharshs, could you please take a look again ? I had to push a fix for the sanity check - there was a small complaint from the buildifier.
Thanks!

**Review by suharshs — APPROVED** [review]

**Pull request merged**
