### PR TITLE
[INTEL MKL] Clean up of remapper code

### PR DESCRIPTION
**Pull request by Zantares**
Removed static macro `INTEL_MKL` and changed them to `IsMKLEnabled`, now it's fully supported runtime switch.

Signed-off-by: Lu Teng teng.lu@intel.com

### CODE REVIEW

**Review by ezhulenev — APPROVED** [review]

**Comment by rthadur** [comment]
@Zantares sorry there are some conflicts to resolve, can you please check.Thank you

**Comment by Zantares** [comment]
@rthadur @ezhulenev conflict has been resolved, please take a new look, thanks!

**Comment by gbaned** [comment]
@Zantares  Can you please resolve conflicts? Thanks!

**Comment by Zantares** [comment]
> @Zantares Can you please resolve conflicts? Thanks!

Done, please help to review, thanks!

**Comment by Zantares** [comment]
@ezhulenev can you help to review again since the conflict is resolved? We have some internal issues which are  blocked by this PR, thanks!

**Review by ezhulenev — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Pull request merged**
