### PR TITLE
Compute test accuracy in batches to avoid OOM on GPUs

### PR DESCRIPTION
**Pull request by thisisrandy**
Reported here: https://github.com/tensorflow/tensorflow/issues/136
Alternative to this for mnist_deep.py: https://github.com/tensorflow/tensorflow/pull/157

Note that some reports in https://github.com/tensorflow/tensorflow/issues/136 claim that BFC solves the problem and that it would be included in the next binary release, but as this writing is two years after those comments, it stands to reason that the example still doesn't work out of the box for "low" memory GPUs.

Also noting for completeness that I am running on a GeForce GTX 670 (2GB) and that avg(avg(x_i)) = avg(x_i) when |x_i| for all i is equal.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by martinwicke** [comment]
@MarkDaoust Not sure we even want to keep this example at all? Is this going to be rewritten?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @MarkDaoust: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @MarkDaoust: It has been 38 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @MarkDaoust: It has been 52 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @MarkDaoust: It has been 67 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Review by MarkDaoust — DISMISSED** [review]
The plan for normalizing the tutorials is taking longer than expected. 

There's no harm in accepting this as is. I've confirmed that it works as expected.

**Review by MarkDaoust — APPROVED** [review]

**Pull request merged**
