### PR TITLE
[NextPluggableDevice]add pjrt compile on demand control flag 

### PR DESCRIPTION
**Pull request by jzhoulon**
let eager op compiled by xla or execute on custom kernel control to plugin

### CODE REVIEW

**Comment by jzhoulon** [comment]
@jyingl3  can you have a review? thanks

**Review by jyingl3 — APPROVED** [review]
Thanks Zhoulong!

**Comment by jyingl3** [comment]
Hi Zhoulong, sorry just realize one issue - could you update the build target of tensorflow/core/common_runtime/pluggable_device/pluggable_device_plugin_init.cc to include pjrt_compile_on_demand_op? Thank you!

**Comment by jzhoulon** [comment]
> Hi Zhoulong, sorry just realize one issue - could you update the build target of tensorflow/core/common_runtime/pluggable_device/pluggable_device_plugin_init.cc to include pjrt_compile_on_demand_op? Thank you!

@jyingl3 done. thanks

**Review by Neilblaze — APPROVED** [review]

**Review by jyingl3 — APPROVED** [review]

**Pull request merged**
