### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by KukretiShubham**
Corrected Grammar

### CODE REVIEW

**Comment by gbaned** [comment]
@KukretiShubham  Can you please sign CLA. Thanks!

**Comment by KukretiShubham** [comment]
> @KukretiShubham Can you please sign CLA. Thanks!

Hey, @gbaned I did that already. 
Here I signed : https://cla.developers.google.com/clas
Correct me if I am wrong.
Thank you

**Comment by PINTO0309** [comment]
@KukretiShubham 

>Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.

**Comment by KukretiShubham** [comment]
@googlebot  I signed it!

**Comment by PINTO0309** [comment]
I'm sorry. It seems that the label has already been OK'd in response to my comment.

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
None of the fixes are correct.

**Comment by KukretiShubham** [comment]
@mihaimaruseac I will look for more issues. I am beginner to tensorflow. Is there any community forum or channel where I can learn or get more insights on how i can contribute to TensorFlow. 
Thanks

**Comment by mihaimaruseac** [comment]
https://discuss.tensorflow.org/ is the best forum.

If you want to fix typos, please fix typos in an entire directory, instead of just 1-2

**Pull request closed without merging**
