### PR TITLE
Add usage example for tf.image.transpose

### PR DESCRIPTION
**Pull request by rickwierenga**

### CODE REVIEW

**Review by Mbah-Javis — COMMENTED** [review]
Nice work mate :) I think it will be appropriate to change _Example usage_ to <strong>Usage Example</strong> and also instead of using a random image, will u try using something of this format `image = [[[1, 2], [3, 4]],
               [[5, 6], [7, 8]],
               [[9, 10], [11, 12]]]`

**Comment by rickwierenga** [comment]
Thanks for the quick review! I copied that text from another method, and fixed those too.

**Comment by Mbah-Javis** [comment]
@rickwierenga looks good. There wasn't any need of thanking me anyway u are welcome  :)

**Comment by rickwierenga** [comment]
@Mbah-Javis, could you please approve the changes via code review so GitHub knows it's been reviewed? Thanks.

**Comment by Mbah-Javis** [comment]
> @Mbah-Javis, could you please approve the changes via code review so GitHub knows it's been reviewed? Thanks.

I would have love too but lets wait for the admins to take a look at it first hope u understand 👍

**Comment by mihaimaruseac** [comment]
Please open against `master` branch, not against a release branch

**Comment by rickwierenga** [comment]
Hadn't seen that, I'm sorry. `master` already has a usage example for `transpose`, so I'm adding a usage example for `pad_to_bounding_box` instead. See https://github.com/tensorflow/tensorflow/pull/36056.

**Pull request closed without merging**
