### PR TITLE
Optimizing and improving accuracy of fp16 conv2d for new powervr gpu …

### PR DESCRIPTION
**Pull request by cycheng**
…generation.

The patch:
- Adds powervr gpu_info
- On the new powervr gpu generation, uses the fp16 matmul builtin for conv2d
- Uses better workgroup size and block size

We see 1.3 ~ 1.55 times speedup of inference time on IMG BXM-8-256 using our internal NN models.

benchmark_model option: --use_gpu=true --gpu_backend=cl --gpu_precision_loss_allowed=true

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @cycheng Can you please resolve conflicts? Thank you!

**Comment by cycheng** [comment]
>

**Comment by gbaned** [comment]
@cycheng Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
@cycheng Any update on this PR? Please. Thank you!

**Comment by cycheng** [comment]
> @cycheng Any update on this PR? Please. Thank you!

Hi gbaned, I am sorry for the delay! Have been sync with latest tflite repo.
Thanks :)

**Comment by gbaned** [comment]
Hi @terryheo Can you please review this PR ? Thank you!

**Comment by roserg** [comment]
Hi,
Thank you for this extensive investigation and suggested improvements.
We definitely will be glad to submit powervrinfo(ideally as separate request), but no need to add driver info unless you really need it.
But we cannot submit this __builtin_IMG_dotF16_m2k4n4_accF32_bt. It looks like illegal, we haven't seen this in any public documentation. You can try to use usual dot() functions and hope that compiler will use internally this builtin functions. But we cannot accept the code that use them directly due to legal reason.
We know that our code on powervr has mediocre  performance in f32-f16 mode.

**Comment by roserg** [comment]
What is the device that you are using for testing?

**Comment by roserg** [comment]
If this possible you can try f32 precision. It can be strange, but f32 precision much faster than f32-f16 on powervr ge8320 and has similar performance to f16 in many cases.

**Comment by impjdi** [comment]
@roserg did the review on my behalf, and looks like we can't use __builtin_IMG_dotF16_m2k4n4_accF32_bt as it's not part of the public API.  Thank you very much for the attempted contribution, but looks like this can't be pursued further.  Closing this PR.

**Pull request closed without merging**
