### PR TITLE
Replace Deprecated logging_ops

### PR DESCRIPTION
**Pull request by thesuperzapper**
Replace: (In the tf.contrib.learn estimators)
- logging_ops.scalar_summary() with summary.scalar()
- logging_ops.histogram_summary() with summary.histogram()

### CODE REVIEW

**Comment by dandelionmane** [comment]
I have a feeling this should block on me until I add a bit of extra functionality to tf.summary.scalar (and friends) that re-delegates control over display name in TB to the api caller.

**Comment by martinwicke** [comment]
@dandelionmane what's the word on this?

**Comment by drpngx** [comment]
@dandelionmane ping?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by dandelionmane** [comment]
Jenkins, test this please.

**Review by teamdandelion — APPROVED** [review]

**Pull request merged**
