### PR TITLE
Fix the issue where distributions.percentile does not support eager mode

### LINKED ISSUE #23619: tf.contrib.distributions.percentile didn't support eager execution
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):tensorflow-py2-cpu API r1.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
When I using the eager execution. I try this:

```
import tensorflow as tf

tf.enable_eager_execution()

x = tf.constant([1,2,3,4],dtype='float64')
y = tf.contrib.distributions.percentile(x,q=30)
```

will report an error:

> TypeErrorTraceback
> 
>  (most recent call last)
> <ipython-input-1-b7b170c83880> in <module>()
>       4 
>       5 x = tf.constant([1,2,3,4],dtype='float64')
> ----> 6 y = tf.contrib.distributions.percentile(x,q=30)
> 
> /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distributions/python/ops/sample_stats.pyc in percentile(x, q, axis, interpolation, keep_dims, validate_args, name)
>     301                        (allowed_interpolations, interpolation))
>     302 
> --> 303   with ops.name_scope(name, [x, q]):
>     304     x = ops.convert_to_tensor(x, name="x")
>     305     # Double is needed here and below, else we get the wrong index if the array
> 
> /usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in __enter__(self)
>    5743       else:
>    5744         cache_key = self._name, self._old_name, self._default_name
> -> 5745         if cache_key in name_scope_cache:
>    5746           self._ctx.scope_name = name_scope_cache[cache_key]
>    5747           return self._ctx.scope_name
> 
> TypeError: unhashable type: 'list'

but when I use tf.Session() to run the same code block:

```
import tensorflow as tf
x = tf.constant([1,2,3,4],dtype='float64')
y = tf.contrib.distributions.percentile(x,q=30)
with tf.Session() as sess:
    print sess.run(y)

```
It worked and report that I wanted:
`2.0`

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

I'm using tensorflow to make some calculate. Eager is very help but this problem stop me to use it.

Thanks for anyone will fix it.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue in #23619 where distributions.percentile in eager mode throws:
```
TypeError: unhashable type: 'list'
```
The issue is that ` [x, q]` should be passed as `values`, not name default. This fix fixed the issue.

This fix fixes #23619

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment]
Ping @jvdillon to take a look, I think the change is quite small ☺️

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jvdillon, @rsepassi: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by SiegeLordEx** [comment]
At some point this got independently fixed in both TensorFlow contrib and TensorFlow probability:

https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/stats/quantiles.py#L136 and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distributions/python/ops/sample_stats.py#L303

Sorry for dropping the ball on this PR, but at least the issue is fixed now.

**Comment by yongtang** [comment]
@SiegeLordEx Thanks for the help. I will close the PR now.

**Pull request closed without merging**
