### PR TITLE
trivial typo in ci_build README

### PR DESCRIPTION
**Pull request by chemelnucfin**
bellow -> below

### CODE REVIEW

**Comment by dave-andersen** [comment]
LGTM

**Comment by dave-andersen** [comment]
@tensorflow-jenkins test this please.
(for auto-merge happiness even though it's just a doc change)

**Comment by martinwicke** [comment]
Jenkins, this this PLEASE!

**Comment by martinwicke** [comment]
Jenkins? test this please?

**Comment by martinwicke** [comment]
Man, sometimes he's really stuck up.

**Comment by dave-andersen** [comment]
It's a Friday - he probably left early to go to Yosemite.  In fairness, the falls are absolutely gorgeous this time of year.

**Comment by chemelnucfin** [comment]
@martinwicke, you mistyped the first "test this".  Maybe Jenkins needs some
NLP autocorrect.  :P

**Pull request merged**
