### PR TITLE
Update BAZEL_VERSION to 0.17.1

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to update BAZEL_VERSION from previous 0.15.0 to 0.17.1. The reason for the update was that PR #19461 depends on a Bazel issue https://github.com/bazelbuild/bazel/issues/5932 which has only been fixed in 0.17.1.

This fix updates the BAZEL_VERSION so that test builds could succeed for #19461.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
@yifeif @gunan The PR #19461 needs a fix in Bazel (https://github.com/bazelbuild/bazel/issues/5932) to pass the test. The Bazel fix is only available in 0.17.1.

I am trying to update the Bazel to 0.17.1 for CI tests. I think some other changes might be needed. Please let me know if there are other places I need to modify.

**Comment by gunan** [comment]
Hi @yongtang Yes, bazel upgrade needs more changes internally.

However, for us to be able to use a feature only in 0.17.1, we have to bump our requirement of bazel version to 0.17.1
I would like to wait one full bazel release cycle before I do that, as pushing dependencies to bleeding edge has caused problems before.
Does this sound reasonable?

**Comment by yongtang** [comment]
Thanks @gunan, lets wait until the next version of Bazel is released. Much appreciate the help 👍 !

**Comment by yongtang** [comment]
Let me close this PR. Will update the Bazel status when next version is released.

**Pull request closed without merging**
