### PR TITLE
Avoid const char-related warning internally

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by caisq** [comment]
https://github.com/tensorflow/tensorflow/commit/c84d0b1c2abef256aba64a99b9c2fec03b3989a5 caused warnings that were treated as errors internally, hence blocking pull. This CL addresses that. Corresponding change has been tested internally. @mrry @gunan

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Review by mrry — APPROVED** [review]
LGTM... perhaps this should more properly be `#if defined(COMPILER_MSVC)`, but not a big deal.

**Comment by caisq** [comment]
@mrry Changed to COMPILE_MSVC.

**Review by mrry — COMMENTED** [review]
Awesome, thanks!

**Pull request merged**
