### PR TITLE
Make windows gpu build project name tensorflow_gpu.

### PR DESCRIPTION
**Pull request by yifeif**

### CODE REVIEW

**Review by mrry — APPROVED** [review]
LGTM!

**Comment by gunan** [comment]
Could you also change the script for windows gpu build?
we only uninstall (pip uninstall) tensorflow at the moment. To avoid weird behaviour, we should uninstall both tensorflow and tensorflow_gpu

**Comment by gunan** [comment]
Also, we need to modify windows GPU installation instructions.

**Comment by yifeif** [comment]
ok, let me do that

**Pull request merged**
