### PR TITLE
Fix Tensor constructor with DataType

### PR DESCRIPTION
**Pull request by luliyucoordinate**
#57142

### CODE REVIEW

**Review by gprakarsh — APPROVED** [review]
Looks good!

**Review by sagunb — APPROVED** [review]
Good catch! Thanks for the fix!

**Comment by rthadur** [comment]
Can you please rebase the branch to head , thank you!

**Comment by luliyucoordinate** [comment]
> Can you please rebase the branch to head , thank you!

got it

**Review by rthadur — APPROVED** [review]

**Pull request merged**
