### PR TITLE
TfLite Fill quantization support added

### PR DESCRIPTION
**Pull request by Dayananda-V**
Quantization support added for #28438

### CODE REVIEW

**Comment by gbaned** [comment]
@achowdhery Can you please review this PR? Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @achowdhery: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by gbaned** [comment]
@Dayananda-V Can you please resolve conflicts? Thanks!

**Comment by Dayananda-V** [comment]
@gbaned 

conflicts resolved.

**Comment by gbaned** [comment]
@Dayananda-V Could you please resolve conflicts? Thanks!

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
