### PR TITLE
Support Python 2 and 3 in notebooks

### PR DESCRIPTION
**Pull request by gsemet**
Support Python 2 and 3 in notebooks

### CODE REVIEW

**Comment by Stibbons** [comment]
I signed it!

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this please.

**Comment by andrewharp** [comment]
Looks like the GPU failure here is preexisting and unrelated.

**Comment by Stibbons** [comment]
Look like a network error, the boost tarball failed downloading.

**Review by martinwicke — APPROVED** [review]
jupyter and git just don't like each other.

**Comment by martinwicke** [comment]
Overriding test failure, infrastructure failure.

**Pull request merged**
