### PR TITLE
Fix stddev computation in TensorBoard examples. (#4054)

### PR DESCRIPTION
**Pull request by shohad25**

### CODE REVIEW

**Comment by martinwicke** [comment]
I believe this has been fixed at head.

**Comment by martinwicke** [comment]
(and in r0.10)

**Comment by vrv** [comment]
(If it was in r0.10, wouldn't this PR diff to nothing?)

**Comment by martinwicke** [comment]
Who knows what that diff is doing, but it's not a diff against r0.10: 
[retrain.py](https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/examples/image_retraining/retrain.py) has no mention of `_sum(` in it.

**Comment by martinwicke** [comment]
I did that on the weekend. Should be fixed.

**Pull request closed without merging**
