### PR TITLE
Try to switch to h5py 3.1.0

### PR DESCRIPTION
**Pull request by bhack**

### CODE REVIEW

**Comment by bhack** [comment]
This is the new strings r/w behavior for 3.x series: https://docs.h5py.org/en/latest/strings.html

**Comment by bhack** [comment]
Just to reference the original ticket https://github.com/tensorflow/tensorflow/issues/44467

**Comment by bhack** [comment]
In the CI logs I see different unicode issues related to https://docs.h5py.org/en/latest/strings.html#what-about-numpy-s-u-type
> TypeError: No conversion path for dtype: dtype

But CPU tests don't fail locally inside the official TF devel image `tensorflow/tensorflow:devel`.

It is hard to work locally where official devel images are not aligned with the CI. 
I think an user can expect to collect the same test result of the CI `Ubuntu CPU` as locally with `tensorflow/tensorflow:devel` if not it will be hard to develop in a local reproducible system.

I think that probably this is caused unaligned `tensorflow/tensorflow:devel` with `LANG_CTYPE=C.UTF-8` and other image used from the CI that are `LC_CTYPE="POSIX"`

**Comment by bhack** [comment]
I've tried to use  `POSIX` locally in `tensorflow/tensorflow:devel` but tests are passing. I cannot reproduce CI fails..

So I've just reverted on one of the first commit to let you see that Linux is passing but not Win/Mac

**Review by mihaimaruseac — APPROVED** [review]

**Comment by bhack** [comment]
@mihaimaruseac What was the Win and OSX issue?

**Comment by mihaimaruseac** [comment]
Windows seems to be broken at HEAD due to an MLIR integrate from 12 hours ago.

MacOS seemed to pass. Probably the environment is different? Hopefully there is no rollback.

**Comment by bhack** [comment]
@mihaimaruseac Can you reopen this? Do you have Shell access on a win/MacOS machine?

**Comment by mihaimaruseac** [comment]
I cannot reopen, GitHub does not let me :(

I can get access to a windows machine, but it will take a while as I have a few P0 items to finish this week/early next week.

**Comment by bhack** [comment]
Yes I know it is merged but I meant something like https://github.com/tensorflow/tensorflow/pull/45487

**Pull request merged**
