### PR TITLE
[PluggableDevice] Add DEVICE_DEFAULT int32 registration for strided slice ops

### PR DESCRIPTION
**Pull request by PatriceVignola**

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Review by penpornk — CHANGES_REQUESTED** [review]
I just remembered that this is a resubmission of #53561 which was rolled back because it broke some internal GPU target. So I'll hold this one off until I have time to investigate why. This will probably miss TF 2.9 deadline (branch cut on next Monday 3/28).

**Comment by PatriceVignola** [comment]
@penpornk That makes sense. That change is not critical so I'm not too worried about it. On the other hand, does that mean that there's absolutely no chances that the other PR for `TF_AssignVariable` (https://github.com/tensorflow/tensorflow/pull/55379) can make it through for 2.9? This other PR is much more important for us because one of the main benchmarks that people use to evaluate GPU providers still uses ref variables. Unfortunately we didn't find that it was an issue until very recently, but since it is in the experimental header, is there a chance that it could make it through?

**Comment by penpornk** [comment]
@PatriceVignola I don't think `TF_AssignRefVariable` will make it. It's too short notice and it touches C API (but at least it's in experimental). Branch cut is this coming Monday (3/28) or Tuesday (3/29) if Monday's nightly isn't clean. I can check with @wangpengmit though.

**Comment by PatriceVignola** [comment]
@penpornk Since it doesn't look like the `TF_AssignRefVariable` PR will be able to make it in TF 2.9, is there a possibility to prioritize the review of this PR for early 2.10 nightly builds, maybe by the end of the week? We want to at least be able to point users to nightly builds if they want to run the benchmarks that still use those ops.

**Comment by PatriceVignola** [comment]
@penpork Do we know which test was failing?

**Pull request closed without merging**
