### PR TITLE
Keras' load_model() fix

### PR DESCRIPTION
**Pull request by smyskoff**
Hi.

I just faced a problem that I cannot load checkpoints of my Keras model. There was an `ValueError` exception with a following backtrace:

```
ValueError                                Traceback (most recent call last)
<ipython-input-3-8b604ef2029d> in <module>
----> 1 model = tf.keras.models.load_model(model_file)

~/Projects/__mangled__/__mangled__/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py in load_model(filepath, custom_objects, compile)
    245           weighted_metrics=weighted_metrics,
    246           loss_weights=loss_weights,
--> 247           sample_weight_mode=sample_weight_mode)
    248 
    249       # Set optimizer weights.

~/Projects/__mangled__/__mangled__/venv/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    454     self._setattr_tracking = False  # pylint: disable=protected-access
    455     try:
--> 456       result = method(self, *args, **kwargs)
    457     finally:
    458       self._setattr_tracking = previous_value  # pylint: disable=protected-access

~/Projects/__mangled__/__mangled__/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, distribute, **kwargs)
    302     # Prepare list of loss functions, same size of model outputs.
    303     self.loss_functions = training_utils.prepare_loss_functions(
--> 304         loss, self.output_names)
    305 
    306     self._feed_outputs = []

~/Projects/__mangled__/__mangled__/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_utils.py in prepare_loss_functions(loss, output_names)
   1143       if name not in output_names:
   1144         raise ValueError('Unknown entry in loss dictionary: {}. Only expected '
-> 1145                          'following keys: {}'.format(name, output_names))
   1146     loss_functions = []
   1147     for name in output_names:

ValueError: Unknown entry in loss dictionary: class_name. Only expected following keys: ['output']
```

I use 2.0.0-alpha0, but the same story with 1.12.0.

I figured out, that loss is not being deserialized before passing it to `model.compile()` call.

My quick fix seems work for me. Could you please check and approve, if all things done in the right way.

### CODE REVIEW

**Comment by smyskoff** [comment]
I signed it!

**Comment by gbaned** [comment]
@k-w-w Could you PTAL and approve.

**Comment by k-w-w** [comment]
Thanks for adding this change! Can you add a test to make sure this doesn't happen again?

**Comment by smyskoff** [comment]
Found what was the deal with the issue and why there's no noise in the internet: it happened only in case if `tf.keras.losses.BinaryCrossentropy` or the other _built-in loss class instance_ was used while the model was compiled. In this case the loss is not a string (like in case if I just used `'binary_crossentropy'` string while compiling the model, but a dictionary, which was not de-serialized.

**Comment by gbaned** [comment]
@k-w-w Can you have a look on smyskoff's comments? Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @k-w-w: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by gbaned** [comment]
@smyskoff Can you please resolve conflicts? Thanks!

**Comment by smyskoff** [comment]
@gbaned, ready

**Comment by k-w-w** [comment]
Hi @smyskoff, does the test pass with as currently implemented? The code has changed a bit, and it should now handle custom object correctly. (The code that deserializes the loss object is here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/saving/saving_utils.py#L210)

**Comment by gbaned** [comment]
@smyskoff Could you please address the reviewer comments. Thanks!

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@smyskoff Gentle ping to check the reviewer comments. Thanks!

**Comment by smyskoff** [comment]
Checked out the updated code. Seems like the problem has gone with changes, so my changes are not needed to make it work in the described flow.

**Comment by gbaned** [comment]
Thank you @smyskoff . Closing this PR as per your confirmation.

**Pull request closed without merging**
