### PR TITLE
Updated the links in docs to match the markdown sytnax.

### PR DESCRIPTION
**Pull request by haosdent**
Refer to [markdown syntax](https://daringfireball.net/projects/markdown/syntax#link),
the `[` should come after `)` without spaces or new line character. This fixs
the broken links when generate PDF/EPUB books by Gitbook.

### CODE REVIEW

**Comment by haosdent** [comment]
@terrytangyuan Sorry for the delay, may you help review this patch? Thank you in advance.

**Comment by terrytangyuan** [comment]
Thanks! @tensorflow-jenkins Test this please.

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Review by yifeif — APPROVED** [review]

**Comment by rohan100jain** [comment]
For the changes in the python API, I believe it would make sense to update the actual py code instead of the docs since the docs are automatically generated.

**Comment by haosdent** [comment]
Hi, @rohan100jain Thanks a lot for review! I change both shard documents in python API and python source code. e.g., For `Candidate Sampling Algorithms Reference`, I change `tensorflow/python/ops/nn.py` and `tensorflow/g3doc/api_docs/python/functions_and_classes/shard1/tf.nn.sampled_softmax_loss.md`

Should I need to revert anything?

**Comment by rohan100jain** [comment]
Thats great! But I think you might have missed out some such as https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L2128
etc. 

Don't think you need to revert anything but what I'm saying is that if the .py files for all the ops are not changed this problem with re-occur because someone will regenerate and we'll get the broken links back again. So I guess it would be great if you can look through all the python API docs that were changed in this PR and see if there are corresponding .py documentation that might need to be changed as well.

**Comment by haosdent** [comment]
@rohan100jain Thanks a lot! My bad use `\]\s\([#h]` to search it, I should use `\]\s+\([#h]` Would you like to help review my patch to fix this issue?

**Pull request merged**
