### PR TITLE
Load op library fix

### PR DESCRIPTION
**Pull request by eaplatanios**
This fixes the issue with external bindings to TensorFlow loading custom op libraries. It does so by exporting all the relevant symbols in `libtensorflow.so`. Note that these symbols were there but they were hidden and we could not link to them previously. Currently, with this fix, developers of custom op libraries can link at compile time using `libtensorflow.so`, thus avoiding the need for `-undefined -dynamic_lookup` on Macs (which also currently doesn't work as a solution on its own) and the need for loading with `RTLD_GLOBAL` (which also does not work on its own, given that `pywrap_tensorflow.so` needs to be loaded with that flag, given it's the own exporting the necessary symbols). I've tested this on my mac and it resolves the issue.

@asimshankar I know this is not really a good solution given that you probably don't want to export everything in `libtensorflow.so`, but I think it offers a good temporary workaround to the issue, until  the fix @allenlavoie is working on, is published.

P.S. This issue has been discussed a bit in #12895.

### CODE REVIEW

**Comment by asimshankar** [comment]
Thanks @eaplatanios : but I'd really like to avoid this for now.  This restriction was introduced in https://github.com/tensorflow/tensorflow/pull/9059/commits/b0989a0280971034bd838fa176ae3f92b210e8dc for two reasons: (1) binary size and (2) clearly defining the API.

There is a reasonable chance that @allenlavoie 's more principled fix will make it to release 1.5 (if not earlier in 1.4). So paying this temporary technical debt doesn't seem worth it. (The workaround won't be helpful to any users of the release till the next release anyway, and those building from source can do this in their build)

(Though, I'll sync with Allen - if I'm wrong about his fix being enough, then will revisit)

**Comment by eaplatanios** [comment]
@asimshankar That sounds reasonable! I agree that it's better to have a clearly defined API. In general, modularization of TensorFlow and it's binaries would probably be a good idea.

As for a temporary workaround, I only need this for my Scala API for defining an op equivalent to `py_func`. One way to go about this would be to make `pywrap_tensorflow.so` accessible through the nightly CI builds. Is that something that's easy to do? Then, I can simply also package it with `libtensorflow.so` for my current purposes, until a more elegant alternative is available.

P.S. I refer to the CI builds because my packaging/release script right now, pulls the `libtensorflow.so` binaries from there.

**Comment by asimshankar** [comment]
Great, thanks for your understanding (I'll go ahead and close this PR).

You could pull `pywrap_tensorflow.so` from the nightly builds by downloading the `whl` file and extracting it :)

**Comment by eaplatanios** [comment]
No problem! :)

I checked out [http://ci.tensorflow.org/view/Nightly/](http://ci.tensorflow.org/view/Nightly/) for the nightly whl files but I can't find them. I only see one build for linux-python3 but that doesn't seem to include the pywrap shared object. Could you point me to a download link for one of those whl files?

**Comment by asimshankar** [comment]
See: https://github.com/tensorflow/tensorflow#installation

**Comment by allenlavoie** [comment]
And the .so itself should be at something like tensorflow-1.3.0.data/purelib/tensorflow/python/_pywrap_tensorflow_internal.so once you unzip the .whl.

**Comment by eaplatanios** [comment]
Great! Thanks a lot! :)

**Pull request closed without merging**
