### PR TITLE
Update .gitignore files for Android Studio

### PR DESCRIPTION
**Pull request by daj**
Without these, Git shows lots of noisy build/IDE config files.

These files are based on these two sources (plus the list of added files that Git shows when I build in Android Studio):
https://github.com/github/gitignore/blob/master/Android.gitignore
https://github.com/github/gitignore/pull/2103/files

Tested in Android Studio 3.0 Beta 2.

### CODE REVIEW

**Comment by drpngx** [comment]
@aselle is this necessary?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 41 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by case540** [comment]
aselle@ do you think these changes are necessary or should we close this PR?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 29 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 45 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Review by gunan — APPROVED** [review]

**Pull request merged**
