### PR TITLE
[TF:TRT] Add ability to persist timing cache to disk

### PR DESCRIPTION
**Pull request by christopherbate**
Drops compile time of models significantly (e.g. 240 sec -> 40 sec on object detection with TRT 8.2)

### CODE REVIEW

**Comment by christopherbate** [comment]
Marked as draft as we require some discussion. Is there a better way to persist the cache than just persisting to disk at an environment variable location? Can we embed it as a resource in the model (with some information about the GPU)?

**Comment by bixia1** [comment]
The approach looks fine to me. Thanks for working on this!

**Comment by gbaned** [comment]
@christopherbate This PR is in draft, any update on this? Please. Thank you!

**Comment by gbaned** [comment]
@christopherbate This PR is in draft, any update on this? Please. Thank you!

**Pull request closed without merging**
