### PR TITLE
register gpu kernel for div_no_nan

### PR DESCRIPTION
**Pull request by facaiy**
This is a follow up PR for #21621.

### CODE REVIEW

**Review by drpngx — APPROVED** [review]

**Comment by drpngx** [comment]
```
ValueError: The use_gpu value used to get the cached session is different than the one that was used to create the session. Maybe create a new session with self.session()
```

**Comment by facaiy** [comment]
Thank you, @drpngx . So will cache_session raise ValueError if use_gpu?

**Comment by drpngx** [comment]
I initial thought it was due to this PR change in `_test.py`, but it was in some other test  in keras, so I think it was unrelated.

**Comment by facaiy** [comment]
Oh, I see :-)

**Pull request merged**
