### PR TITLE
Push changes from internal: 122460440

### PR DESCRIPTION
**Pull request by mrry**

### CODE REVIEW

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please.

**Comment by caisq** [comment]
common_runtime_gpu_gpu_debug_allocator_test failed. Testing this again to see if it is a flaky test.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
The common_runtime_gpu_gpu_debug_allocator_test failure seems to be reproducible:

==================== Test output for //tensorflow/core:common_runtime_gpu_gpu_debug_allocator_test:
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Running main() from test_main.cc
[==========] Running 7 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 7 tests from GPUDebugAllocatorTest
[ RUN      ] GPUDebugAllocatorTest.OverwriteDetection_None
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GRID K520
major: 3 minor: 0 memoryClockRate (GHz) 0.797
pciBusID 0000:00:03.0
Total memory: 4.00GiB
Free memory: 3.95GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
[       OK ] GPUDebugAllocatorTest.OverwriteDetection_None (275 ms)
[ RUN      ] GPUDebugAllocatorTest.OverwriteDetection_Header

[WARNING] external/gmock_archive/gmock-1.7.0/gtest/src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.
================================================================================

**Comment by mrry** [comment]
@caisq: That warning looks ominous, but it doesn't appear to be new in gmock, nor is the death test in that target new. Is there a good way to run that test in isolation on the test machine?

@keveman is trying to reproduce this locally. If he doesn't succeed, I propose we continue the push and disable the test for now.

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
@caisq: @keveman figured out the breakage (due to a subtle change in the behavior of our CUDA code across `fork()`). Can you please try running the tests again, in case @tensorflow-jenkins doesn't listen to me? :)

**Comment by ebrevdo** [comment]
Jenkins, test this please.

**Pull request merged**
