### PR TITLE
During makefile CI build, adjust ownership of the files docker writes…

### PR DESCRIPTION
**Pull request by gunan**
… to host filesystem.

### CODE REVIEW

**Comment by gunan** [comment]
Jenkins, test this please.

**Review by petewarden — APPROVED** [review]

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

(one more try)

**Comment by gunan** [comment]
Ubuntu repos not found?
I do not know what is going on with the makefile failure.

**Comment by vrv** [comment]
So what should we do?

**Comment by gunan** [comment]
I am hoping this is a transient issue with ubuntu servers. I will try to debug locally to see if there is something I am doing that is causing this problem.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by gunan** [comment]
Ill close this until I figure out what the problem with ubuntu repositories are.

**Pull request closed without merging**
