### PR TITLE
[XLA] Define LANG_CXX11 for >= VS 2015

### PR DESCRIPTION
**Pull request by rongjiecomputer**
In MSVC, __cplusplus == 199711 even when /std:c++latest is set because MSVC is still not "fully" C++11 compliant.

Split from #15310.

#15213

### CODE REVIEW

**Comment by snnn** [comment]
It's not needed. It's already in cl.exe's command line arg.

**Comment by rongjiecomputer** [comment]
@snnn I ran into a lot of compile errors due to `LANG_CXX11` not defined in several XLA `cc_library` (that was before I noticed your old PR #14531). Now that all `cc_library` will be replaced with `tf_cc_library` (#15466), this should be less of a problem.

I know `LANG_CXX11` is already defined in [`get_win_copts`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L155), but since there is a way to just detect MSVC and define `LANG_CXX11` in header file, this should be better than command line flag. I was hoping to remove `LANG_CXX11` from `get_win_copts` and just rely on it being defined in header file.

What do you think?

**Comment by snnn** [comment]
Either is ok to me, but, keep consistent. I don't want to see  macro redefined warnings

**Review by tatatodd — APPROVED** [review]

**Comment by tatatodd** [comment]
Jenkins, test this please.

**Pull request merged**
