### PR TITLE
Fix duplicate symbol CreateGPUTracerEv

### LINKED ISSUE #12699: libtensorflow-core.a contains duplicate symbol CreateGPUTracerEv
Running `build_all_ios.sh` produces a `libtensorflow-core.a` that contains a symbol twice. When linking on iOS the error is

```
duplicate symbol __ZN10tensorflow15CreateGPUTracerEv in:
    <PROJDIR>/.../libtensorflow-core.a(gpu_tracer.o)
ld: 1 duplicate symbol for architecture x86_64
```

I checked with `nm` just to be sure

```
$ nm libtensorflow-core.a | grep CreateGPUTracerEv
---------------- T __ZN10tensorflow15CreateGPUTracerEv
---------------- T __ZN10tensorflow15CreateGPUTracerEv
```

Branch `master`
MacOS Sierra 10.12.6 (16G29)
Xcode Version 8.3.3 (8E3004b)

### PR DESCRIPTION
**Pull request by eaigner**
Closes #12699

### CODE REVIEW

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
@petewarden does that sound right?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by sb2nov** [comment]
@petewarden ping

**Review by petewarden — APPROVED** [review]
Looks good, thanks for this, and sorry for the slow response.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by eaigner** [comment]
Unfortunately you took so long that this seems to be fixed on master already.

**Comment by martinwicke** [comment]
Sorry about that. :( At least it is fixed.

**Pull request closed without merging**
