### PR TITLE
Fix broken links to docs_src/get_started/get_started.md

### PR DESCRIPTION
**Pull request by kswapd**
Fix broken links to tensorflow/tensorflow/docs_src/get_started/get_started.md

### CODE REVIEW

**Comment by kswapd** [comment]
I signed it!

**Comment by dandelionmane** [comment]
Can you repro that the links are broken? They seem to be working on tensorflow.org. If there is a bug, we would want to fix our custom link generator rather than short-circuiting it and using raw markdown.

**Comment by kswapd** [comment]
I don't know why I cannot access tensorflow.org, so I can only learn TensorFlow from github, Is there anyway that the links work well in both link generator and markdown environment?

**Comment by dandelionmane** [comment]
It sounds like the root issue to debug is that you can't access tensorflow.org. I don't think we're aiming to maintain the doc links in pure-markdown, but I'll let @josh11b comment on that.

**Comment by josh11b** [comment]
I agree with @dandelionmane , our strategy is described in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/g3doc

Maybe @martinwicke can offer suggestions for accessing these docs without tensorflow.org (a case we would like to support, for e.g. people who know they will be offline).

**Comment by josh11b** [comment]
Actually, you can follow the instructions in that README, to generate an offline copy of the docs with the links fixed.

**Comment by dandelionmane** [comment]
Closing this PR since the site is working as intended.

**Comment by kswapd** [comment]
I got it, thank you.

**Pull request closed without merging**
