### PR TITLE
Support CMake options to use external package providers like zlib, GRPC, Eigen

### PR DESCRIPTION
**Pull request by imsheridan**
This PR is to add the ability to use external package providers like GRPC, zlib, Eigen .etc. It is not possible to compile project using two different versions of protobuf right now.

This is a continuous work of PR #16210. As discussed [there](https://github.com/tensorflow/tensorflow/pull/13867#issuecomment-339789050), it did something similar to GRPC package whether you specify tensorflow__PROVIDER variable. It will determine if tensorflow needs to download dependency and use it as a module or use find_package() to find package.
> Add ability to use external GRPC, zlib, Eigen and mb some other packages. Because right now it is impossible to compile your project with tensorflow if you're using different version of GRPC. I did something similar to GRPC package whether you specify tensorflow__PROVIDER variable. It will determine if tensorflow needs to download dependency and use it as a module or use find_package() to find package.

### CODE REVIEW

**Review by mrry — APPROVED** [review]

**Comment by perfinion** [comment]
Thanks for rebasing this! It probably makes more sense to name the options systemlib_FOO to match with
https://github.com/tensorflow/tensorflow/pull/15382
also they should be put under systemlib_ALL.
alternatively doing this could be a second PR after this is merged

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
Sorry for the delay.
Could you rebase, and resolve the conflicts?

**Comment by drpngx** [comment]
@imsheridan could you pull rebase and push again?

**Comment by caisq** [comment]
Gentle ping @imsheridan

**Comment by imsheridan** [comment]
Sure, I'll try to rebase tomorrow. Sorry for the delay.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
Closing due to inactivity.
Let me know and I will reopen if the conflicts are resolved.

**Pull request closed without merging**
