### PR TITLE
differentiate package description and license

### PR DESCRIPTION
**Pull request by zjj2wry**
differentiate license and package desription. use /* */ make code more clear.

### CODE REVIEW

**Comment by zjj2wry** [comment]
I signed it!

**Review by yifeif — APPROVED** [review]
Thanks @zjj2wry .

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Comment by yifeif** [comment]
jenkins plug-in issue, trying again. @tensorflow-jenkins test this please.

**Pull request merged**
