### PR TITLE
[TF-TRT] Refactoring Step 2 - `trt_convert.py` splitted into common, v1 and v2 parts

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
TF-TRT Refactoring Step 2
- This PR prepares the ground for https://github.com/tensorflow/tensorflow/pull/58346
- Split `trt_convert.py` into 3 files: common, v1 and v2

**To be noted:**
Some changes are justified by the upcoming changes. They will make more sense when the complete scope of the refactoring see #58346 is being considered.

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
@bixia1 for review

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @DEKHTIARJonathan Can you please resolve conflicts? Thank you!

**Pull request closed without merging**
