### PR TITLE
fixed the bug in tf.graph_util.remove_training_nodes when applying to LSTM networks

### PR DESCRIPTION
**Pull request by yongchao-liu**
This bug damages LSTM network structure and make the model unusable.

### CODE REVIEW

**Comment by yongchao-liu** [comment]
I signed it!

**Comment by frankchn** [comment]
@yongchao-liu You may have to sign it again with the email you used to create the commits and/or your Github email.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
