### PR TITLE
Optimize FusedBatchNorm with DepthwiseConv2dNative for inference.

### PR DESCRIPTION
**Pull request by vv1133**

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 28 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 43 days with no activity and the `awaiting review` label has been applied.

**Comment by petewarden** [comment]
Sorry for the slow response. Can you add a test for this path to optimize_for_inference_test.py? Thanks!

**Comment by vv1133** [comment]
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and have the pull request author add another comment and the bot will run again. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Ftensorflow%2Ftensorflow%2Fpull%2F24662) for more info**.

solved

**Comment by vv1133** [comment]
> Sorry for the slow response. Can you add a test for this path to optimize_for_inference_test.py? Thanks!

Done.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by vv1133** [comment]
Please review @petewarden

**Comment by gbaned** [comment]
@petewarden Hi, Could you PTAL and approve.

**Comment by gbaned** [comment]
@petewarden can you please review this? Thanks!

**Review by jhseu — DISMISSED** [review]
I'll do a review since it's been so long, even though I don't know this code that well. Looks right to me, though.

**Comment by gbaned** [comment]
@vv1133 Can you please check build failures? Thanks!

**Comment by vv1133** [comment]
Hi @jhseu ,  I have corrected pylint issue, can you please review it again? thanks!

**Review by jhseu — DISMISSED** [review]

**Comment by gbaned** [comment]
@vv1133 Can you please address build failures? Thanks!

**Review by jhseu — DISMISSED** [review]

**Comment by vv1133** [comment]
@jhseu There 2 failed tests in Ubuntu Sanity. From the logs, it seems it is irrelevant to this PR. Could you please help check? Thanks!

**Comment by jhseu** [comment]
It's just pylint errors. You can look at the sanity invocation log here:
https://source.cloud.google.com/results/invocations/c2c2e4a2-e57d-4c9a-8f6a-098fa32b6f79/log

**Comment by jhseu** [comment]
Copying here for convenience:
```
tensorflow/python/tools/optimize_for_inference_test.py:178: [C0330(bad-continuation), ] Wrong hanging indentation (remove 4 spaces).
tensorflow/python/tools/optimize_for_inference_test.py:179: [C0330(bad-continuation), ] Wrong hanging indentation (remove 4 spaces).
tensorflow/python/tools/optimize_for_inference_test.py:180: [C0330(bad-continuation), ] Wrong hanging indentation (remove 4 spaces).
tensorflow/python/tools/optimize_for_inference_test.py:181: [C0330(bad-continuation), ] Wrong hanging indentation (remove 4 spaces).
tensorflow/python/tools/optimize_for_inference_test.py:182: [C0330(bad-continuation), ] Wrong hanging indentation.
```

**Comment by vv1133** [comment]
> It's just pylint errors. You can look at the sanity invocation log here:
> https://source.cloud.google.com/results/invocations/c2c2e4a2-e57d-4c9a-8f6a-098fa32b6f79/log

@jhseu Thanks! Could you please review it again?

**Review by jhseu — APPROVED** [review]

**Comment by gbaned** [comment]
@vv1133 Can you please check build failures? Thanks you!

**Comment by vv1133** [comment]
> @vv1133 Can you please check build failures? Thanks you!

@gbaned @jhseu From the logs, it seems it is irrelevant to this PR. Could you please help check? Thanks!

**Comment by jhseu** [comment]
Yeah, the failures look unrelated to me.

**Pull request merged**
