### PR TITLE
Allow custom image size for NASNet models

### PR DESCRIPTION
**Pull request by m-romanenko**
Running `model = NASNetMobile(input_shape=(400, 400, 3), include_top=False, weights="imagenet")` results in a ValueError: When setting `include_top=True` and loading `imagenet` weights, `input_shape` should be (224, 224, 3). This PR aims to fix the above error.

### CODE REVIEW

**Comment by m-romanenko** [comment]
@googlebot I signed it!

**Comment by fchollet** [comment]
Thanks for the PR. I suspect there was a reason why `require_flatten` was set to True. Please add a unit test to test this change.

**Review by fchollet — APPROVED** [review]
Thanks for adding the test. LGTM.

**Comment by fchollet** [comment]
Unfortunately we had to revert this change because it was breaking internal tests. It's looking like there was indeed a reason why `require_flatten` was set to True. I still think this would be a useful change, but making it would require further testing to make sure we don't break backwards compatibility.

**Pull request merged**
