### PR TITLE
added an example for tf.image.rot90

### PR DESCRIPTION
**Pull request by jvishnuvardhan**
Example was requested in https://github.com/tensorflow/tensorflow/issues/29243

### CODE REVIEW

**Review by alextp — CHANGES_REQUESTED** [review]
This example is somewhat unsatisfying.

Can't you show a 1-channel image which then it's easy to rotate?

**Comment by jvishnuvardhan** [comment]
@alextp Made changesto use single channel. Please let me know what you think. Thanks!

**Review by alextp — COMMENTED** [review]
I wanted to literally show the array. So for a 2-by-2 image with 1 channel, a right rotation can go from [[1 2] [3 4]] to [[4 1] [3 2]] (I think?)

**Comment by jvishnuvardhan** [comment]
@alextp In order to be easy for the reader, I thought of adding images and show them on the TF website. I got your point. I have updated. As we need `ndims`=>3, I added third dimension. Thanks!

**Review by alextp — APPROVED** [review]

**Pull request merged**
