### PR TITLE
Add clustering to TF Model Optimization overview

### PR DESCRIPTION
**Pull request by TamasArm**
Small change to the overview document to reflect clustering as an option for model optimization.

### CODE REVIEW

**Comment by MeghnaNatraj** [comment]
@suharshs Could you review this doc update?

**Comment by alanchiao** [comment]
Contents look good. I'll wait until Monday when the launch occurs prior to LGTM'ing this.

**Review by alanchiao — APPROVED** [review]

**Comment by alanchiao** [comment]
LGTMd. @MeghnaNatraj could you review as someone from the TFLite side?

**Comment by MeghnaNatraj** [comment]
LGTM as well. @gbaned you can go ahead and approve these changes.

**Review by rthadur — APPROVED** [review]

**Pull request merged**
