### PR TITLE
Delete

### PR DESCRIPTION
**Pull request by jjwang01**

### CODE REVIEW

**Comment by akshaym** [comment]
Hi @jjwang01, did you mean to delete this file? If so, why?

**Comment by jjwang01** [comment]
Hi,

I’m not too sure how github works, but I just wanted to open an ipython notebook for an udacity course. For some reason it just opened in GitHub. Do you where to go from there?

Thanks,
Justin
________________________________

**Comment by akshaym** [comment]
Hi @jjwang01,

There are some instructions on how to access these notebooks within a docker container here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/udacity

I'm going to close this pull request since it seems it was opened unintentionally.

Thanks!
Akshay

**Comment by jjwang01** [comment]
Hi Akshay,


I actually have a question about this page you've linked. How would I be able to use Docker on a Windows machine for this course, and if I don't have GCP instances? These instructions seem to be geared towards Linux and Mac machines.


Thanks,

Justin

________________________________

**Comment by akshaym** [comment]
Hi @jjwang01,

It should be possible to install docker on windows: https://docs.docker.com/docker-for-windows/install/
Once installed, you should be able to follow the commands on that page. If the commands don't work, please open an issue here: https://github.com/tensorflow/tensorflow/issues/new

You might also be able to get help getting up and running on the course's forums. 

Apologies I couldn't be more help!

Thanks,
Akshay

**Pull request closed without merging**
