### PR TITLE
Remove unused TensorBoard._epoch

### PR DESCRIPTION
**Pull request by lgeiger**
Since 7b43b3ce08035b6c502b1aa4caa23ba59e4710f2 `TensorBoard._epoch` isn't used anymore in the callback, so it can be safely removed.

### CODE REVIEW

**Review by Sahith02 — APPROVED** [review]

**Review by Rishit-dagli — APPROVED** [review]
This indeed seems to not be used.

**Review by fchollet — APPROVED** [review]
LGTM, thank you for the PR

**Comment by gbaned** [comment]
@lgeiger  Can you please resolve conflicts? Thanks!

**Comment by lgeiger** [comment]
> Can you please resolve conflicts?

@gbaned Done

**Review by fchollet — APPROVED** [review]

**Comment by lgeiger** [comment]
@gbaned This PR seems to be stuck in the pipeline, can you check what's going on?

**Comment by gbaned** [comment]
> @gbaned This PR seems to be stuck in the pipeline, can you check what's going on?

@lgeiger Sorry for the delay. Internal test failures are appearing, @fchollet is working on this. Thank you!

**Comment by lgeiger** [comment]
No worries (it's a trivial PR anyway), just pinged you since I thought it might be stuck due to a technical problem :)

**Review by fchollet — APPROVED** [review]
IMO this should just be mergeable.

**Comment by fchollet** [comment]
Unfortunately this appears to be blocked due to technical glitches. We're going to have to fix it separately. Nevertheless, thanks for the PR!

**Pull request closed without merging**
