### PR TITLE
Use CudnnRNNV3 for the GRU and LSTM

### PR DESCRIPTION
**Pull request by kaixih**
This PR replaces the use of CudnnRNN with CudnnRNNV3, which supports inputs with different layouts (time/batch major) and variable sequence lengths. With this PR, we can avoid unnecessary layout permutation and the code will be clearer.

fyi. @nluehr

### CODE REVIEW

**Review by qlzh727 — APPROVED** [review]
Thanks for the change. The original concern for not using cudnnRNNv3 in all case is that it need to create sequence_length even when mask is None, which could introduce some overhead for this default case.

Would it possible for cudnn v3 kernel to make sequence length an optional input (take care of the default sequence length logic)?

**Comment by kaixih** [comment]
> Would it possible for cudnn v3 kernel to make sequence length an optional input (take care of the default sequence length logic)?

Do you mean to let the cudnnrnnv3 takes care of calling the cudnnRNNforwardTraining if no sequence lengths is given or calling the cudnnRNNforwardTrainingEx if seq lengths is given?

**Comment by qlzh727** [comment]
> > Would it possible for cudnn v3 kernel to make sequence length an optional input (take care of the default sequence length logic)?
> 
> Do you mean to let the cudnnrnnv3 takes care of calling the cudnnRNNforwardTraining if no sequence lengths is given or calling the cudnnRNNforwardTrainingEx if seq lengths is given?

Something like that. My main concern is about the performance, and it will be nice if sequence length is just an optional input tensor for cudnnRNNforwardTrainingEx (save the cost of creating sequence length from input shapes).

**Comment by kaixih** [comment]
> Something like that. My main concern is about the performance, and it will be nice if sequence length is just an optional input tensor for cudnnRNNforwardTrainingEx (save the cost of creating sequence length from input shapes).

Yes, I understand. In fact, this PR is to pave the way for another following PR to replace the backend of CudnnRNNV3 with the new cudnnRNNForward and cudnnRNNBackwardxxx_v8, both of which require the sequence lengths array (though I think we could request CUDNN to treat it as optional if we do see performance issue for fixed seq length cases). And all the backends of CudnnRNN and CudnnRNNV2 (cudnnRNNForwardxxx(Ex) and cudnnRNNBackwardxxx(Ex)) will be deprecated.

**Comment by qlzh727** [comment]
> > Something like that. My main concern is about the performance, and it will be nice if sequence length is just an optional input tensor for cudnnRNNforwardTrainingEx (save the cost of creating sequence length from input shapes).
> 
> Yes, I understand. In fact, this PR is to pave the way for another following PR to replace the backend of CudnnRNNV3 with the new cudnnRNNForward and cudnnRNNBackwardxxx_v8, both of which require the sequence lengths array (though I think we could request CUDNN to treat it as optional if we do see performance issue for fixed seq length cases). And all the backends of CudnnRNN and CudnnRNNV2 (cudnnRNNForwardxxx(Ex) and cudnnRNNBackwardxxx(Ex)) will be deprecated.

Ack. Good to know. Approved.

**Comment by qlzh727** [comment]
We have detected a performance regression caused by this PR, will rollback soon.

**Comment by qlzh727** [comment]
The regression is detected via our internal platform, and unfortunately the information is not publicly visible at the moment. @zongweiz and @sanjoy will help you troubleshoot and provide guidance for rolling forward this PR.

**Comment by kaixih** [comment]
Sure. Please share more info about the regression if possible. Is it caused by the creation of seq_lengths array? Or did you see slower kernels are used in the new API?

At the same time, I've sent a request to our CUDNN team to allow the v8 RNN API takes the seq_length as nullptr and fallback to the old execution path.

**Comment by qlzh727** [comment]
We ran 2 benchmarks internally, one on GCP and one on another internal platform. The number from GCP is stable before and after the change, but the other platform was experiencing 30% regression based on steps per second when training the model. 
 
It might related to cuda version/env difference between GCP and the other platform, but we are not sure. @sanjoy and @zongweiz might be able to provide more insights.

**Pull request merged**
