### PR TITLE
[INTEL MKL] Fix to the unit test "print_selective_registration_header_test"

### PR DESCRIPTION
**Pull request by LakshayT**
Removed the check and code to append prefix 'Mkl' if mkl is enabled in the print_selective_registration_header_test unit test, as it was causing a failure with new changes wherein all operators get re-written into MKL versions including matmul. The 'if' check is no longer needed in the test.

### CODE REVIEW

**Review by penpornk — DISMISSED** [review]
Thank you for the PR!

**Comment by gbaned** [comment]
@LakshayT Can you please check Ubuntu Sanity errors? Thanks!

**Comment by LakshayT** [comment]
@gbaned  I have made a change to fix the ubuntu sanity check issue.

**Review by penpornk — APPROVED** [review]
Thank you for your fix!

**Pull request merged**
