### PR TITLE
[XLA:CPU][oneDNN] : Add OneDNN softmax rewriter

### PR DESCRIPTION
**Pull request by sachinmuradi**
This PR rewrites the below mentioned HLO pattern, into softmax pattern and executes it through custom call to oneDNN softmax library function.
This pattern is mainly seen in flax/jax [softmax ](https://github.com/google/jax/blob/a259df0d76e50e0e54fa5a69a7c6b78975cde10a/jax/_src/random.py#L1025)operation, with Float32 datatype. The rewrite uses 'divide' operation as root node to match the pattern and is currently called before any layout assignment / float normalization passes to avoid more convert ops or layout normalization ops during pattern matching.

**HLO Pattern :**
image

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @sachinmuradi Can you please rebase your branch and resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @sachinmuradi Can you please rebase your branch and resolve conflicts? Thank you!

**Review by d0k — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @sachinmuradi Any update on this PR? Please. Thank you!

**Comment by penpornk** [comment]
Closing this PR since its replacement PR https://github.com/openxla/xla/pull/7540 has been merged. Thank you again for the changes!

**Pull request closed without merging**
