### PR TITLE
Changing minor tolerance to pass linalg_grad_test on ppc64le

### PR DESCRIPTION
**Pull request by sandipmgiri**
Fixes: https://github.com/tensorflow/tensorflow/issues/19935

Thanks!

### CODE REVIEW

**Comment by sandipmgiri** [comment]
@martinwicke  Could you please review this PR.

**Review by rmlarsen — CHANGES_REQUESTED** [review]

**Comment by sandipmgiri** [comment]
@rmlarsen As per your suggestion I have updated the PR , please review. Thanks !

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wdirons** [comment]
@rmlarsen, Can you please review the updated pull request ?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sandipmgiri** [comment]
Fixed in https://github.com/tensorflow/tensorflow/commit/422158776bcd9ffbde485610fdd3af498a2d5669, hence closing.

**Pull request closed without merging**
