### PR TITLE
Update nn.py

### PR DESCRIPTION
**Pull request by arasharchor**
adding missing quantized_relu which was missing before.

### CODE REVIEW

**Comment by smajida** [comment]
I signed it!

**Comment by alextp** [comment]
Adding @asimshankar as a reviewer as it's an API change

**Comment by asimshankar** [comment]
Good for API addition (though you might have to update the golden files, the failing tests will tell you how).

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by asimshankar — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by alextp** [comment]
Can you fix the test failures? We'd like to merge this

**Pull request merged**
