### PR TITLE
Added iOS example using the camera

### PR DESCRIPTION
**Pull request by petewarden**

### CODE REVIEW

**Comment by petewarden** [comment]
Jenkins, please test this.

**Comment by petewarden** [comment]
Jenkins, test this please.

**Comment by petewarden** [comment]
Jenkins, test this please.

**Comment by vrv** [comment]
Sadly, we can't merge anything until jenkins is fixed.

@caisq @martinwicke  I assume you guys are looking at this :)

**Comment by petewarden** [comment]
I've been in touch with @martinwicke and they're working on it, so hopefully we can get this in soon.

**Comment by petewarden** [comment]
Jenkins, test this please.

**Comment by jendap** [comment]
I have just downgraded jenkins. That should fix it.

@tensorflow-jenkins test this please

**Comment by petewarden** [comment]
@jendap unfortunately it looks like it's still hitting the same error.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins seems to be fixed now. I have triggered this test, and it seems to be running better now.
Please let me know if the problem persists.

**Comment by petewarden** [comment]
Looking on Jenkins, it seems like the builds all succeeded but the checks here haven't updated.

**Comment by jendap** [comment]
yeah, working on it - b/29081939

**Comment by jendap** [comment]
@tensorflow-jenkins test this please

**Comment by jendap** [comment]
@tensorflow-jenkins test this please

(this time for real, we have workaround the issue)

**Pull request merged**
