### PR TITLE
Update nn_impl.py

### PR DESCRIPTION
**Pull request by 372046933**
fix package name

### CODE REVIEW

**Review by pavithrasv — APPROVED** [review]
Thank you for the PR!

**Comment by gbaned** [comment]
@372046933 Could you please fix build errors? Thanks!

**Comment by 372046933** [comment]
@gbaned I didn't change any other code beyond this file. Can the CI process be retested?

**Comment by gbaned** [comment]
@372046933 Can you please address Ubuntu Sanity errors? Thanks!

**Comment by 372046933** [comment]
@gbaned I have run `./tensorflow/tools/ci_build/ci_sanity.sh`. And step 1 `configure.py` looks for CUDA. Step 1 failed to pass. Why CUDA is a must?

**Pull request merged**
