### PR TITLE
Add a bit more descriptions on adding an op?

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Hi,

I'm trying to add my custom op and feeling that the document doesn't give enough information on how it works. I struggled a lot and finally I'm able to figure things out by reading the code of some header files.

Can anyone take a look if the changes to the document in this PR will make it better for new people?

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
I signed it!

**Comment by yaroslavvb** [comment]
Added a bit of grammar fixes/reworded, looks good otherwise

**Comment by yaroslavvb** [comment]
That's weird, CLA bot didn't recognize my email (I made edit directly from to PR from the github window), github commit page still shows me as author, any ideas @martinwicke ?

**Comment by martinwicke** [comment]
See the fine print in the CLAbot message: It's giving up and it's up to us to make sure you're ok with us merging your commit. Since you clearly are, we will proceed to ignore CLAbot.

**Comment by vrv** [comment]
This is nice, thanks for these clarifications.  Apparently our documentation is in the middle of a reorganization and will be done in a week or two, and we've been told to hold off on changes to documentation this week and next, otherwise these changes will get lost in the changeover.

We can re-ping this PR once the new documentation files are up, and you can make changes to those files once they are ready.  Thank you for the contribution and your patience!

**Comment by zasdfgbnm** [comment]
OK, no problem. It's a great news that there will be a better docs in 1-2 weeks!

**Comment by vrv** [comment]
In this case, I don't think there are going to be new docs for adding an op, just a restructuring (there some edits, but not the ones you made, which are great).

**Comment by josh11b** [comment]
Could you please update your PR to reflect our move from g3doc/ to doc_src/?
https://github.com/tensorflow/tensorflow/commit/1c707ac780313f48a6733dc3beedf4b8a2b3df77

In particular, there are some new instructions here:
https://github.com/tensorflow/tensorflow/blob/1c707ac780313f48a6733dc3beedf4b8a2b3df77/tensorflow/g3doc/README.txt

Thanks!

**Comment by zasdfgbnm** [comment]
I think this is just a merge

**Review by teamdandelion — APPROVED** [review]

**Comment by dandelionmane** [comment]
@tensorflow-jenkins Test this please

**Pull request merged**
