### PR TITLE
UK collection

### PR DESCRIPTION
**Pull request by kiranchhetri1**
To update or to get new version

### CODE REVIEW

**Comment by gbaned** [comment]
@kiranchhetri1 thank you for your contribution, please sign CLA.

**Comment by mihaimaruseac** [comment]
What is this supposed to solve?

**Comment by gbaned** [comment]
@kiranchhetri1 Can you please check @mihaimaruseac's comments and keep us posted. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Pull request closed without merging**
