### PR TITLE
Add float16 support for CTCLoss

### LINKED ISSUE #22096: CTCLoss does not support half precision (float16/fp16)
I was trying to use `CTCLoss` with float16, and encountered a type exception in `python.framework.op_def_library._apply_op_helper `. In the [op definition](https://github.com/tensorflow/tensorflow/blob/294442996b2aeff00b1bfdc7e7169f7cb35bbf3d/tensorflow/core/ops/ops.pbtxt#L3568), it only lists `DT_FLOAT`.  Is there a particular reason that this op wasn't updated to support half precision in #1300?

```
  File "/nix/store/rnfj7g778synyrkr7qa8nx67sdmsr4xg-python3.6-tensorflow-1.7.0/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'inputs' of 'CTCLoss' Op has type float16 that does not match expected type of float32.
```

Have I written custom code: No
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: pip
TensorFlow version: 1.7
Bazel version: 0.10.1
CUDA/cuDNN version: 9.1
GPU model and memory: Tesla V100
Exact command to reproduce: N/A
Mobile device: N/A

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #22096 where there was no float16 support for CTCLoss.

This fix added template to CTCLoss, and registered the op in tensorflow/core/ops/ctc_ops.cc.

This fix fixes #22096.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by npow** [comment]
Wow, this was fast. Thanks @yongtang !

**Comment by npow** [comment]
Do you not need to update the [ops.pbtxt](https://github.com/tensorflow/tensorflow/blob/294442996b2aeff00b1bfdc7e7169f7cb35bbf3d/tensorflow/core/ops/ops.pbtxt#L3568) file?

**Comment by ebrevdo** [comment]
See my comments in that issue.

**Comment by ebrevdo** [comment]
Reopen if there's a good argument for float16 CTC loss on CPU.

**Pull request closed without merging**
