### PR TITLE
Expose TString related C API #46803

### PR DESCRIPTION
**Pull request by Oceania2018**

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
@Oceania2018  Can you please address Ubuntu Sanity errors? Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by Oceania2018** [comment]
Hi @mihaimaruseac, when whill this PR be merged?

**Comment by mihaimaruseac** [comment]
This fails to build internally and needs manual import and fixing.

Sadly, I cannot do this at this time, busy with other things. Will likely be able to next week

**Review by mihaimaruseac — APPROVED** [review]

**Comment by Oceania2018** [comment]
@mihaimaruseac Do you have a change to merge it?

**Comment by Oceania2018** [comment]
@mihaimaruseac Sorry to bother you again, May I know when this PR will be merged? This is changes will fix the TString API for other languages binding like TensorFlow .NET since tensorflow v2.4 made a breaking change for string api.

**Comment by mihaimaruseac** [comment]
Hi.

Apologies for the delay. Been quite busy with the upcoming release and didn't get a chance to look into this.

Should be merged tomorrow.

**Review by wxinix — COMMENTED** [review]
tf_tstring.cc won't need this line:  #include "tensorflow/c/tf_tensor.h"?

**Pull request merged**
