### PR TITLE
Python : simplify computecpp.tpl

### PR DESCRIPTION
**Pull request by JoanThibault**

### CODE REVIEW

**Comment by JoanThibault** [comment]
I signed it!

**Comment by benoitsteiner** [comment]
@JoanThibault Can you check that you used the same email address to sign the CLA and author the change ? Our bot can't seem to find a CLA for you.

**Comment by lukeiwanski** [comment]
:+1:  Looks good to me! Thanks!

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Review by benoitsteiner — APPROVED** [review]

**Pull request merged**
