### PR TITLE
- added missing momentum in ApplyCenteredRMSProp and ResourceApplyCenteredRMSProp doc

### PR DESCRIPTION
**Pull request by ashwin-phadke**
Deals with #42502 for changes.

### CODE REVIEW

**Comment by ashwin-phadke** [comment]
[Updated discussion ](https://github.com/tensorflow/tensorflow/issues/42502#issuecomment-679229073)

**Review by mihaimaruseac — COMMENTED** [review]
This files are autogenerated, we should instead fix the bug in the generation code.

**Comment by ashwin-phadke** [comment]
> This files are autogenerated, we should instead fix the bug in the generation code.

Sure, could you please elaborate on how I can make changes to the generation code? Do you mean I need to change the source file for the implementation of the said code?

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Apologies, seems I was wrong, these files are manually written, not autogenerated. Sorry for the confusion

**Comment by ashwin-phadke** [comment]
Thank you.

**Pull request merged**
