### PR TITLE
Bugfix to test/run_and_gather_logs.

### PR DESCRIPTION
**Pull request by ebrevdo**
- Now soft exit if cpuinfo/psutils not found.
- Uncomment test again.

### CODE REVIEW

**Comment by ebrevdo** [comment]
Should I resubmit from my corporate email address?

**Comment by ebrevdo** [comment]
I signed it!

**Comment by ebrevdo** [comment]
Jenkins, test this please.

**Comment by ebrevdo** [comment]
Jenkins, test this please.

**Comment by ebrevdo** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Jenkins, test this please?

**Comment by jendap** [comment]
@ebrevdo can you please resolve the conflicts? Ideally rebase to new master?

**Comment by ebrevdo** [comment]
Bug fixed internally.  Closed.

**Pull request closed without merging**
