### PR TITLE
tf.nn.conv2d_transpose doc fix

### PR DESCRIPTION
**Pull request by danielwaterworth**

### CODE REVIEW

**Comment by danielwaterworth** [comment]
I signed it

**Comment by danielwaterworth** [comment]
@googlebot, your ability to express gratitude is philosophically disputable.

**Comment by vincentvanhoucke** [comment]
@tensorflow-jenkins test this please

**Comment by danielwaterworth** [comment]
Looks like this was reverted by https://github.com/tensorflow/tensorflow/commit/0d700eff9860757469b65c3b49b9829803d2a9b2. What happened?

**Comment by vincentvanhoucke** [comment]
I think the .md files are automatically generated from:
https://github.com/tensorflow/tensorflow/blob/9171cbec195f2f41c55f83d251f5e532a1910580/tensorflow/python/ops/nn_ops.py#L1022

**Pull request merged**
