### PR TITLE
Update tensorflow.keras.metrics.pbtxt

### PR DESCRIPTION
**Pull request by adriangb**
See https://github.com/tensorflow/tensorflow/pull/42097#issuecomment-675149062

ccing @pavithrasv : is this the right place to make this edit?

### CODE REVIEW

**Comment by pavithrasv** [comment]
Thank you for the PR @adriangb. You need not update the pbtxt files afaik. It's enough to add those strings in losses.py file against the function. https://github.com/tensorflow/tensorflow/blob/442c7015fce8889fac11f415f20d43e0576520a3/tensorflow/python/keras/losses.py#L1455

**Comment by adriangb** [comment]
Ah makes sense, will do!

**Comment by adriangb** [comment]
Just pushed the change @pavithrasv, please take a look when you have a chance. Thanks.

**Review by pavithrasv — DISMISSED** [review]
Thank you for the PR!

**Comment by adriangb** [comment]
I assume the test failures due to API change are expected and just require manual approval/override?

**Comment by gbaned** [comment]
@adriangb  Can you please address Ubuntu Sanity errors? Thanks!

**Comment by adriangb** [comment]
I think I see what happened. Can you re-approve @gbaned ?

**Comment by gbaned** [comment]
@adriangb  Still, Ubuntu Sanity errors appearing, Can you fix those?. Thanks!

**Comment by adriangb** [comment]
I see that I left duplicate parenthesis. I rebased to the last commit in master and re-applied the decorator (a single time). For some reason `ci_sanity.sh` is building the container but not running for me so... do you mind approving again @gbaned ? Thanks

**Review by pavithrasv — DISMISSED** [review]

**Comment by adriangb** [comment]
Sanity checks are now passing. It looks like the failures are from API change, which is correct since this technically does change the API.

**Comment by rthadur** [comment]
@adriangb this test is failing https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/api/tests/api_compatibility_test.py
```
If this test fails, it means a change has been made to the public API. Backwards
incompatible changes are not allowed. You can run the test with
"--update_goldens" flag set to "True" to update goldens when making changes to
the public TF python API.
```

**Comment by adriangb** [comment]
Well this is adding an API, but only because that API was accidentally omitted. This API change should be approved.

**Comment by rthadur** [comment]
cc @pavithrasv

**Comment by pavithrasv** [comment]
That's right, this is not changing any API, it is adding couple of new APIs.

**Comment by rthadur** [comment]
Thank you , @pavithrasv can you please help with internal failures ?

**Comment by pavithrasv** [comment]
Sure, I have replied on it already!

**Comment by gbaned** [comment]
@adriangb  Any update on this PR? Please. Thanks!

**Comment by adriangb** [comment]
> @adriangb Any update on this PR? Please. Thanks!

What updates do you need from me? This is waiting on internal Google approval AFAIK.

**Comment by gbaned** [comment]
> > @adriangb Any update on this PR? Please. Thanks!
> 
> What updates do you need from me? This is waiting on internal Google approval AFAIK.

@adriangb  Sorry, I thought it is waiting for update from you.  Thanks!

**Comment by gbaned** [comment]
@pavithrasv  Any update on this PR? Please. Thanks!

**Review by rthadur — DISMISSED** [review]

**Comment by rthadur** [comment]
@adriangb this test is still failing , please generate goldens https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/api/tests/api_compatibility_test.py
```
If this test fails, it means a change has been made to the public API. Backwards
incompatible changes are not allowed. You can run the test with
"--update_goldens" flag set to "True" to update goldens when making changes to
the public TF python API.
```

**Comment by rthadur** [comment]
please use the command 
```

 blaze run third_party/tensorflow/tools/api/tests:api_compatibility_test \
          -- --update_goldens True
```

cc @pavithrasv

**Comment by adriangb** [comment]
Isn't this something you can do internally? I have no idea what `blaze` is.

**Comment by rthadur** [comment]
@adriangb we usually ask users to generate goldens when there is a change in Apis so that you can credit for changes , you can install bazel and run above command 
check for a similar [PR](https://github.com/tensorflow/tensorflow/pull/42539#issuecomment-686816117) where goldens were generated by users.

**Comment by rthadur** [comment]
cc @mihaimaruseac

**Comment by adriangb** [comment]
Oh ok, you meant _bazel_. https://github.com/tensorflow/tensorflow/pull/42442#issuecomment-702374343 says `blaze run` which confused me a bit.

**Comment by annarev** [comment]
The change adds a symbol to the API and therefore needs to be reviewed by API owners. More details: https://github.com/tensorflow/community/blob/master/governance/api-reviews.md

**Comment by adriangb** [comment]
> The change adds a symbol to the API and therefore needs to be reviewed by API owners. More details: https://github.com/tensorflow/community/blob/master/governance/api-reviews.md

Could you at least tag the API owners? The link in the doc you linked is currently broken (https://github.com/orgs/tensorflow/teams/api-owners). @pavithrasv already okayed this PR.

**Comment by annarev** [comment]
> > The change adds a symbol to the API and therefore needs to be reviewed by API owners. More details: https://github.com/tensorflow/community/blob/master/governance/api-reviews.md
> 
> Could you at least tag the API owners? The link in the doc you linked is currently broken (https://github.com/orgs/tensorflow/teams/api-owners). @pavithrasv already okayed this PR.

I did add "API review" tag, but forgot to mention it in the message above.

**Comment by adriangb** [comment]
Btw, I'm running bazel to update the goldens but even with `--jobs=1` and inside a fresh `tensorflow/tensorflow:devel` I'm getting unrelated compilation errors and it takes ages. I wish there was a way to make changes in TF that didn't require compiling a bunch of unrelated C++ APIs. If there is, please do share!

**Comment by mihaimaruseac** [comment]
Let me import this locally and try doing the goldens internally.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by adriangb** [comment]
> Let me import this locally and try doing the goldens internally.

Thank you!

**Comment by mihaimaruseac** [comment]
> > Let me import this locally and try doing the goldens internally.
> 
> Thank you! I gave you access to my fork in case you want to just push there.

Thanks for giving access to the fork. I'll work on the imported change since that is slightly faster, but if the changed failed to import I would have used the fork

**Pull request merged**
