### PR TITLE
TF utils_test additional test cases covers

### PR DESCRIPTION
**Pull request by Dayananda-V**
1- constant_value api test case
2- get_reachable_from_inputs api test case

### CODE REVIEW

**Comment by Dayananda-V** [comment]
@fchollet 

Please help to review the test case

**Review by fchollet — APPROVED** [review]
Thanks for the PR

**Comment by rthadur** [comment]
@Dayananda-V could you please fix build errors

**Comment by Dayananda-V** [comment]
@rthadur 

those build eeror is not induced from my code and those test are not required on my changes. Please check and update me if require any support.

**Review by alextp — CHANGES_REQUESTED** [review]
The test is now failing if you run it with the environment flag TF2_BEHAVIOR=1, with the error:

======================================================================
FAIL: test_constant_value (__main__.ConstantValueTest)
test_constant_value (__main__.ConstantValueTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/work/4cd5bd788fce7509048c396a420bd3c79455/google3/runfiles/google3/third_party/tensorflow/python/layers/utils_test.py", line 110, in test_constant_value
    self.assertIsNone(utils.constant_value(utils.smart_cond(pred, f1, f2)))
AssertionError: 5 is not None

**Comment by Dayananda-V** [comment]
Compilation error fix changes is commit using new PR #27735, closing the old one.

**Pull request closed without merging**
