### PR TITLE
DO NOT MERGE: Change GPU test to use cuda8. Update docker ubuntu to 16.04.

### PR DESCRIPTION
**Pull request by yifeif**

### CODE REVIEW

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this please.

**Comment by rohan100jain** [comment]
Just wanted to understand the status of this PR... are you waiting for someone to review this?

**Comment by yifeif** [comment]
Thanks for the ping Rohan. We were waiting for cuda 8.0 to come out of RC, but it looks like a bunch of  things changed in the nvidia docker image, and some of changes in this PR no longer applies. I will close this PR.

**Pull request closed without merging**
