### PR TITLE
Updated citation formatting for endpoints

### PR DESCRIPTION
**Pull request by tugceoz**

### CODE REVIEW

**Comment by tugceoz** [comment]
I signed the CLA!

**Review by dynamicwebpaige — APPROVED** [review]
LGTM! Thanks so much for making this fix, and for clarifying the link to the arxiv paper.

**Comment by rthadur** [comment]
@yifeif can you please help merge this PR

**Comment by rthadur** [comment]
Closing this PR as this not against `master`, please open a new PR against `master` 
CC @mihaimaruseac

**Pull request closed without merging**
