### PR TITLE
Fix pip package API generation

### LINKED ISSUE #31973: [TF 2.0.0-rc0] Cannot find any 2.0.0 RC0 API references.
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 and macOS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0-rc0 (both GPU and CPU versions)
- Python version: 3.6.8

**Describe the current behavior**
Not a single reference to members of tensorflow can be found in IDE(PyCharm). 
However, programs run as expected.

**Describe the expected behavior**
References to members of tensorflow can be found.

Screen Shot 2019-08-26 at 17 13 30

### PR DESCRIPTION
**Pull request by lgeiger**
This PR fixes the API generation of the pip package and removes the need for workarounds like `keras = _sys.modules["tensorflow.keras"]` which break IDE autocompletion (see #31973).

@mihaimaruseac added workarounds to the [`root.__init__`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/virtual_root_template_v2.__init__.py) templates to properly export lazily loaded modules in 18c2cf989a2263ee212fbd5ac0b3085d9450b80a and b7db3f4ae43f5228952f3a1bb480a3e52a2006ed. Unfortunately this breaks autocompletion in many IDEs and therfore can make using TensorFlow tricky.

The core issue is that generated [`tensorflow_core.__init__.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/api_template.__init__.py) looks something like this:
```python
# many lines of top level imports

_names_with_underscore = ['__version__', '__git_version__', '__compiler_version__', '__cxx11_abi_flag__', '__monolithic_build__']
__all__ = [_s for _s in dir() if not _s.startswith('_')]
__all__.extend([_s for _s in _names_with_underscore])

# lazy loading of keras, estimator, losses, metrics, initializers and optimizers
```

`__all__` was added by @yifeif in 584a64fa377d3070a05753344a410a5c96685ffd to fix underscore symbol imports.

Since lazily loaded modules like `keras` are imported after computing `__all__` (which relies on `dir()`), they won't be visible in the root template which imports them via:
https://github.com/tensorflow/tensorflow/blob/222f2431b113f2b4726dcf321f3b79688da68e03/tensorflow/virtual_root_template_v2.__init__.py#L101

This PR fixes the issue by moving `__all__` to the bottom of the file.

Note: Please review with care since I wasn't able to build TF from source and thus couldn't properly test the changes in `create_python_api.py`.

Fixes #31973

### CODE REVIEW

**Comment by annarev** [comment]
@lgeiger  Thank you for the change!
You can verify if this helps without building TensorFlow but instead copying the changes into pip package files.
For e.g.
```
python3 -m venv venv
source venv/bin/activate
pip install tensorflow
~$ python
>>> import tensorflow as tf
>>> tf
<module 'tensorflow' from '/path/to/python3.7/site-packages/tensorflow/__init__.py'>
```
Open /path/to/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py
Move `__all__` to the end of the file.
Now you can check if this installation of TensorFlow fixes the issue you see.
(I can also help out with building TensorFlow if you have specific questions).

That being said, I am actually looking right now at fixing the autocomplete issues by removing the virtual package and changing tensorflow_core/ to tensorflow/. Specifically, there are other issues as well, not just `__all__` location.

**Comment by lgeiger** [comment]
@annarev Thanks for the fast reply.

I did indeed manually test my changes and they don't break imports and fix the autocomplete. I just wasn't able to test the pip package generation via `tensorflow/python/tools/api/generator/create_python_api.py`.

> (I can also help out with building TensorFlow if you have specific questions).

Thanks for the offer, the main issue is just that it takes too long to be feasible on my machine without a remote build cache. I'll build it overnight just to make sure.

**Comment by lgeiger** [comment]
> That being said, I am actually looking right now at fixing the autocomplete issues by removing the virtual package and changing tensorflow_core/ to tensorflow/. Specifically, there are other issues as well, not just `__all__` location.

That's great to hear! Do you have an ETA for this?
It would be really cool from a user perspective to get this into the upcoming 2.1 release, even if it is only my solution that doesn't fully solve the problem.

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
This looks good to me. Thank you

**Comment by lgeiger** [comment]
b98db48be1b8238e213d1d6b9ab607ea96088224 will hopefully fix the CI failure. Sorry about that

**Review by mihaimaruseac — APPROVED** [review]

**Review by annarev — APPROVED** [review]

**Comment by annarev** [comment]
> That's great to hear! Do you have an ETA for this?

I put up a proposal here:
https://github.com/tensorflow/community/pull/182/files?short_path=5c4ad87#diff-5c4ad8728e4355930b6444d235b602d0
The change itself should be relatively quick. However, I need to get some feedback first to see if this is the right way to proceed.

**Pull request merged**
