### PR TITLE
Add Dataset_Ops C++ API for building dataflow graph

### PR DESCRIPTION
**Pull request by feihugis**
This PR provides a flexible way to build dataflow graphs by using Dataset_Ops C++ API. With this, the predefined `map_graph_def.pbtxt` file will not be needed.

cc: @aaudiber @jsimsa

### CODE REVIEW

**Comment by aaudiber** [comment]
@feihugis Here are the pros/cons I see for using a GraphDef dynamically generated using the C++ API vs using a static GraphDef generated using the Python API:

Pros for C++ API:
- Dynamically generated GraphDefs are always at the latest version. Static graphdefs could become outdated in a new major version.
- It's easier to make small changes to a dynamically generated GraphDef.

Cons for C++ API:
- Internal C++ API is not guaranteed to stay the same, so the test could break due to C++ API changes.
- Writing tests with C++ API requires understanding many internal details of tf.data, such as the presence of the "RetVal" node, how to build the function library, how to set the right attrs for each node.
- Readers of the test are more familiar with Python API than C++ API.

Tensorflow [guarantees](https://www.tensorflow.org/guide/versions#compatibility_of_savedmodels_graphs_and_checkpoints) that GraphDefs generated using non-experimental APIs in TF 2.x can be executed through all of TF 2.x as well as 3.x. This mitigates the concern that a static file will become outdated. Given this, I would prefer to stick to the public Python API for generating test GraphDefs, so that we don't need to update the test when the less-stable C++ API changes.

**Comment by feihugis** [comment]
Thanks very much for the detailed explanation, @aaudiber! I agreed with you. At the beginning, I just considered the flexibility with using C++ API here, but did not realize the cons you mentioned.  Maybe we can close this PR at this moment.

BTW, do you know what's the plan for the C++ API? I did not see people work on that part. Also, `visibility` in the dataset api defs is set to `HIDDEN` as [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_RangeDataset.pbtxt#L3). Do you know what's the purpose?

**Comment by aaudiber** [comment]
@feihugis I don't know of any plans to make the C++ API compatible across versions - right now only the C API is covered (https://www.tensorflow.org/guide/versions#what_is_covered). 

I believe the reason for setting Dataset API op defs to HIDDEN is that we don't want users to depend on the op def API, and instead stick to the Python API. In general the quality of our Python API documentation is higher than op documentation, since there is very little interest in the op-level documentation.

**Comment by aaudiber** [comment]
I appreciate the idea of switching to C++ API since it definitely gives some nice benefits, but since there are also significant downsides I agree we should close this PR.

**Comment by feihugis** [comment]
@aaudiber Gotcha. I will close this PR.

**Pull request closed without merging**
