### PR TITLE
Branch 135971493

### PR DESCRIPTION
**Pull request by rohan100jain**

### CODE REVIEW

**Comment by rohan100jain** [comment]
@tensorflow-jenkins test this please

**Comment by terrytangyuan** [comment]
@martinwicke Any reason why we are removing `DNNSampledSoftmaxClassifier` from open-source version? https://github.com/tensorflow/tensorflow/pull/4927/commits/b309148f5e9a6766bfc6f68972138a52d095cd5f

**Comment by martinwicke** [comment]
We found out that to actually work properly we would have had to use some tooling that we haven't done the work to opensource yet. We will still do that.

**Comment by terrytangyuan** [comment]
I see. Thanks!

**Pull request closed without merging**
