### PR TITLE
Reuse DeviceNameUtils::LocalName

### PR DESCRIPTION
**Pull request by jiakai0419**
for this
```
// TODO(zhifengc): We need to consolidate (full/partial) device name
// parsing into one place.
//
// Parses and returns the local device part (e.g., cpu:0, gpu:4).
string GetLocalDeviceName(StringPiece fullname) {
  auto pos = fullname.rfind('/');
  CHECK_NE(pos, StringPiece::npos);
  fullname.remove_prefix(pos + 1);
  return string(fullname);
}
```

### CODE REVIEW

**Comment by jiakai0419** [comment]
@rthadur Would you mind adding another reviewer?

**Comment by jiakai0419** [comment]
@rthadur It's been 27 days. @saeta may be busy and have no time to deal with it.

**Comment by rthadur** [comment]
@jiakai0419 thank you for your patience @guptapriya can you review this ?

**Comment by guptapriya** [comment]
I think @jaingaurav is a better person to review runtime related changes.

**Review by jaingaurav — DISMISSED** [review]
LGTM

**Comment by jaingaurav** [comment]
@jiakai0419: Thank you for the PR. Unfortunately, it is not building internally could you please add `//tensorflow/core:framework` as dep for the `remote_device` target here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/BUILD#L288

**Comment by jiakai0419** [comment]
> @jiakai0419: Thank you for the PR. Unfortunately, it is not building internally could you please add `//tensorflow/core:framework` as dep for the `remote_device` target here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/BUILD#L288

@jaingaurav  done

**Review by jaingaurav — APPROVED** [review]

**Pull request merged**
