### PR TITLE
Update cpuinfo and ruy to the latest revision

### PR DESCRIPTION
**Pull request by petrhosek**
This includes recent improvements to the CMake build.

### CODE REVIEW

**Review by terryheo — APPROVED** [review]
LGTM

**Comment by petrhosek** [comment]
Would it be possible to trigger the presubmit builders again?

**Review by mihaimaruseac — APPROVED** [review]

**Review by terryheo — APPROVED** [review]
LGTM

**Comment by petrhosek** [comment]
The change is still failing on the ARM CI builder, but there are no details about the failure other than:
```
FAIL: //bazel_pip/tensorflow/python/kernel_tests/array_ops:concat_op_test_cpu (see /tmpfs/bazel_output/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/testlogs/bazel_pip/tensorflow/python/kernel_tests/array_ops/concat_op_test_cpu/test_attempts/attempt_1.log)
FAIL: //bazel_pip/tensorflow/python/kernel_tests/array_ops:pad_op_test_cpu (see /tmpfs/bazel_output/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/testlogs/bazel_pip/tensorflow/python/kernel_tests/array_ops/pad_op_test_cpu/test_attempts/attempt_1.log)
FAIL: //bazel_pip/tensorflow/python/kernel_tests/array_ops:concat_op_test_cpu (see /tmpfs/bazel_output/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/testlogs/bazel_pip/tensorflow/python/kernel_tests/array_ops/concat_op_test_cpu/test_attempts/attempt_2.log)
FAIL: //bazel_pip/tensorflow/python/kernel_tests/array_ops:pad_op_test_cpu (see /tmpfs/bazel_output/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/testlogs/bazel_pip/tensorflow/python/kernel_tests/array_ops/pad_op_test_cpu/test_attempts/attempt_2.log)
FAIL: //bazel_pip/tensorflow/python/kernel_tests/array_ops:pad_op_test_cpu (see /tmpfs/bazel_output/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/testlogs/bazel_pip/tensorflow/python/kernel_tests/array_ops/pad_op_test_cpu/test.log)
```
I'll try to get access to an ARM64 machine and reproduce it locally.

**Comment by petrhosek** [comment]
I managed to reproduce the issue locally and I don't think it was introduced by this PR, I see errors like:
```
======================================================================
ERROR: testConcatLargeNumberOfTensors (__main__.ConcatOpTest)
ConcatOpTest.testConcatLargeNumberOfTensors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pip_test/venv_clean/lib/python3.10/site-packages/tensorflow/python/framework/test_util.py", line 1625, in decorated
    return f(self, *args, **kwargs)
  File "/tmpfs/bazel_output/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/bazel_pip/tensorflow/python/kernel_tests/array_ops/concat_op_test_cpu.runfiles/org_tensorflow/bazel_pip/tensorflow/python/kernel_tests/array_ops/concat_op_test.py", line 557, in testConcatLargeNumberOfTensors
    self.assertAllEqual(result[index], params[p[i]])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: testRandom (__main__.ConcatOpTest)
ConcatOpTest.testRandom
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pip_test/venv_clean/lib/python3.10/site-packages/tensorflow/python/framework/test_util.py", line 1625, in decorated
    return f(self, *args, **kwargs)
  File "/tmpfs/bazel_output/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/bazel_pip/tensorflow/python/kernel_tests/array_ops/concat_op_test_cpu.runfiles/org_tensorflow/bazel_pip/tensorflow/python/kernel_tests/array_ops/concat_op_test.py", line 159, in testRandom
    self._testRandom(dtypes.bool)
  File "/tmpfs/bazel_output/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/bazel_pip/tensorflow/python/kernel_tests/array_ops/concat_op_test_cpu.runfiles/org_tensorflow/bazel_pip/tensorflow/python/kernel_tests/array_ops/concat_op_test.py", line 153, in _testRandom
    self.assertAllEqual(result[ind], params[p[i]])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

----------------------------------------------------------------------
```
This builder seems to have been consistently failing for other changes as well, see https://github.com/tensorflow/tensorflow/actions/workflows/arm-ci.yml

**Review by terryheo — APPROVED** [review]

**Review by terryheo — APPROVED** [review]

**Pull request merged**
