### PR TITLE
Bump TF version to 1.13.1

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Review by aselle — APPROVED** [review]
LGTM!

**Comment by wookayin** [comment]
Sorry for disturbing you guys, but just out of curiosity, what happened to 1.13.0?

**Comment by gunan** [comment]
Yes, I created the tag on the master branch by mistake.
Previously, when we overwrote tags, there were issues, so we decided to skip 1.13.0 and release 1.13.1

**Comment by stonebig** [comment]
will there be a  Tensorflow-1.13.1 on pypi ?

**Pull request merged**
