### PR TITLE
[Bazel/MSVC] Make Kafka builds on Windows

### PR DESCRIPTION
**Pull request by rongjiecomputer**
Working towards enabling `//tensorflow/contrib/kafka` for Bazel on Windows.

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@rongjiecomputer Is this PR ready to be reviewed?

**Comment by rongjiecomputer** [comment]
Yes. The actual change to enable `//tensorflow/contrib/kafka` will be another PR.

**Review by meteorcloudy — DISMISSED** [review]
Thanks!

**Comment by rongjiecomputer** [comment]
Windows Bazel builds all failed at link step: `LINK : fatal error LNK1000: unknown error at ...`. Probably just flake.

MacOS Contrib also failed with mysterious "Internal CI infrastructure error".

Rebased against master, please trigger CI test again.

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
