### PR TITLE
Update farmhash

### PR DESCRIPTION
**Pull request by mattn**
https://github.com/google/farmhash/commit/6193375f121f1e2288f0d9282c4d9be1547e2c0f include fix for farmhash on Windows.

### CODE REVIEW

**Comment by mattn** [comment]
Oops. Can not download archive. Will fix soon.

**Comment by mattn** [comment]
Ah, it is served from mirror.tensorflow.org. Could you please update cache on mirror?

**Comment by mattn** [comment]
Build error with latest commit of farmhash.

```
g++ -O3 -DNDEBUG -fPIC  --std=c++11 -fext-numeric-literals -D__LITTLE_ENDIAN__ -I. -IC:/dev/tensorflow/tensorflow/lite/tools/make/../../../../../ -IC:/dev/tensorflow/tensorflow/lite/tools/make/../../../../../../ -IC:/dev/tensorflow/tensorflow/lite/tools/make/downloads/ -IC:/dev/tensorflow/tensorflow/lite/tools/make/downloads/eigen -IC:/dev/tensorflow/tensorflow/lite/tools/make/downloads/absl -IC:/dev/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -IC:/dev/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -IC:/dev/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -IC:/dev/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I -I/usr/local/include \

-o C:/dev/tensorflow/tensorflow/lite/tools/make/gen/windows_x86_64/bin/minimal C:/dev/tensorflow/tensorflow/lite/tools/make/gen/windows_x86_64/obj/tensorflow/lite/examples/minimal/minimal.o \

 C:/dev/tensorflow/tensorflow/lite/tools/make/gen/windows_x86_64/lib/libtensorflow-lite.a  -lstdc++ -lpthread -lm -lz

C:/dev/tensorflow/tensorflow/lite/tools/make/gen/windows_x86_64/lib/libtensorflow-lite.a(conv.o):conv.cc:(.text$_ZN3ruy11DispatchMulILNS_4PathE3EaaaNS_9BasicSpecIiaEEEEvRKNS_6MatrixIT0_EERKNS4_IT1_EERKT3_PNS_7ContextEPNS4_IT2_EE[_ZN3ruy11DispatchMulILNS_4PathE3EaaaNS_9BasicSpecIiaEEEEvRKNS_6MatrixIT0_EERKNS4_IT1_EERKT3_PNS_7ContextEPNS4_IT2_EE]+0x1d6): undefined reference to `ruy::TrMul(ruy::TrMulParams*, ruy::Context*)'

collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [tensorflow\lite\tools\make\Makefile:266: C:/dev/tensorflow/tensorflow/lite/tools/make/gen/windows_x86_64/bin/minimal] Error 1
```

**Review by imrrahul — CHANGES_REQUESTED** [review]
make changes as it not redirecting

**Comment by gbaned** [comment]
@mattn  Did you get a chance to look on reviewer comments? Please let us know on the update. Thanks!

**Comment by mattn** [comment]
What should I do?

**Comment by jdduke** [comment]
Please update all of the associated dependencies as shown here: https://github.com/tensorflow/tensorflow/search?q=816a4ae622e964763ca0862d9dbd19324a1eaf45&unscoped_q=816a4ae622e964763ca0862d9dbd19324a1eaf45

**Comment by mattn** [comment]
Sorry, my delay. Updated dependencies.

**Review by mrry — DISMISSED** [review]

**Comment by gbaned** [comment]
@mattn Could you please address the build failures? Thanks!

**Comment by mattn** [comment]
@gbaned it is failing since mirror server does not work.

http://mirror.tensorflow.org/github.com/google/farmhash/archive/0d859a811870d10f53a594927d0d0b97573ad06d.tar.gz

**Comment by gbaned** [comment]
@mattn Could you please resolve the conflicts? Thanks!

**Comment by mattn** [comment]
As I mentioned in above, I need https://github.com/google/farmhash/commit/6193375f121f1e2288f0d9282c4d9be1547e2c0f

But mirror repository does not have the archive contains the commit.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by rthadur** [comment]
closing this PR as contrib folder will be depricated in 2.0, thank you.
CC @mihaimaruseac

**Pull request closed without merging**
