### PR TITLE
Use augmented assignment statements and fix typos in mnist/word2vec python code

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by vrv** [comment]
@tensorflow-jenkins, test this please.

**Comment by dongjoon-hyun** [comment]
I guess the failure of `MacOS CPU Tests` is irrelevant to this PR since the master branch doesn't pass the same test. I'm wondering if the failure of `default` is meaningful.

**Comment by vrv** [comment]
Yeah it's fine. I'll merge tomorrow

**Comment by dongjoon-hyun** [comment]
I see. Thank you, @vrv .

**Comment by vrv** [comment]
Merged

**Pull request closed without merging**
