### PR TITLE
Merge in some performance changes to r1.0

### PR DESCRIPTION
**Pull request by cwhipkey**
git cherry-pick f49cca9b7f7ecac8b4f2c031d489e99594068645
git cherry-pick 66b5684133bda0a3050e1573f747d86c645dfd67
git cherry-pick f0a1af4a8bcbe456a0d8a748f9805494cc4ab786
git cherry-pick 2b589dc79b16c2d104a71f809af5505fe9476687
git cherry-pick f49721aaf82b44dc420b5898536b5dce3254975b
git cherry-pick 9b7c47c1d48dfbe69e2ab62aae6146823ba7e664
git cherry-pick 44642329df6bc1627c54f92c5f6850e5882da991
git cherry-pick 5be95cbb389bc112161232c8514155947063ea72
git cherry-pick 27ffb49afc9030a5070a860f4fca491d4f8c29e7
git cherry-pick e9602d275295feaeee900147147957aad2594fb4
git cherry-pick bf67d0a1c52c303f9018c00cbc030dc35438ed2c
git cherry-pick 7725c874499991464d5fd0a4fd57216885726a60
git cherry-pick e2127701a5695f393c42a270ab30814703feb64b

### CODE REVIEW

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by cwhipkey** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
py3 failure known issue.
Merging.

**Review by gunan — APPROVED** [review]

**Pull request merged**
