### PR TITLE
Make tf.pow work for integer inputs.

### PR DESCRIPTION
**Pull request by codrut3**
Currently tf.pow freezes if both inputs are integer tensors and y contains negative values. For example
the call
`tf.pow(5, -2).eval()`
never finishes.

The cause is the implementation of pow in Eigen. To get around this issue I've changed the
underlying C++ functor to treat differently integer inputs. However, tf.pow now returns float tensors on
input integer tensors.

In order to pass the backwards compatibility test, I had to create a new op IntegralPow for the case of
integer inputs. This mirrors the implementation of abs using Abs and ComplexAbs. I've made this
op hidden.

I've also added tests for the pow function in python.

This should fix issue #9560.

### CODE REVIEW

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by sb2nov** [comment]
@codrut3 can you look at the test failures.

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by codrut3** [comment]
I did, and there were two types of failures:
1. I was handling dtype incorrectly in math_ops.pow (I fixed this)
2. There are use cases where it's natural to expect tf.pow to return an int32 tensor.
    For example, one of the tests did x ** 2, for x a tf.int32 tensor.
    Another computed tf.pow(2, layer), with layer a tf.constant.

These are reasonable use cases, and I don't see a way around them. I don't see how to fix the issue
without returning float for all integer inputs.

So I was thinking of closing the pull request. I apologize for this.

**Comment by sb2nov** [comment]
Thanks for the contribution, if you can come up with a work-around please re-open.

**Pull request closed without merging**
