### PR TITLE
[ROCm] MIOpen DNN algorithms integration logic in ROCm StreamExecutor

### PR DESCRIPTION
**Pull request by whchung**
Please focus on the content in commit https://github.com/tensorflow/tensorflow/pull/20713/commits/7c87476fe25e48039d59ab5058480bdfa91c9e3b

The pull request contains MIOpen integration logic for ROCm platform.

There are additional changes included in this pull request which are covered
in other pull requests for ROCm. In order to ensure each pull request is
self-contained and builds / runs on both CUDA & ROCm platform they are still
included here.

- #20277 : bazel changes and continuous integration logic
- #20675 : StreamExecutor interface change
- #20706 : StreamExecutor interface change
- #20708 : StreamExecutor interface change
- #20709 : barebone ROCm StreamExecutor implementation

Authors:

- Jack Chung: jack.chung@amd.com
- Peng Sun: Peng.Sun@amd.com

### CODE REVIEW

**Comment by whchung** [comment]
@jlebar This is the subsequent PR after #20709 to cover integration logic for MIOpen DNN algorithms on ROCm StreamExecutor implementation

**Comment by jlebar** [comment]
@chsigg volunteered to help with this.  Christian, you can see the full set of patches at https://github.com/tensorflow/tensorflow/pulls/whchung.

**Comment by chsigg** [comment]
Thanks Wen-Heng, this looks very good at first glance. There have been some changes to cuda_dnn.cc that I think would be worth integrating to mroc_dnn.cc. Do you think that would be feasible?

I think it might make sense to integrate the mroc_dnn files from the cuda_dnn files (at least the header, and potentiall the cc file as well to make it simpler to port changes going forward).

**Comment by whchung** [comment]
@chsigg Thanks for the feedback. The philosophy behind the current implementation was to keep existing interface and CUDA implementation as is so we can come up with a working implementation with least intrusive changes.

Moving forward indeed DNN interface and implementation deserve to be refactored between both paths to share common logic as much as possible.

I'm working on addressing requests by @jlebar in #20708 and will follow-up with you on this PR after that's done.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jlebar, @chsigg: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by qlzh727** [comment]
Seems that the #20708 has been merge. Please resolve the merge conflict here and we can proceed again.

**Comment by whchung** [comment]
will revise the PR after #20277 is fixed and lands. this PR depends on it.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
