### PR TITLE
Fix Error using tf.image.random._ : 'numpy.ndarray' object has no attribute 'get_shape' #1399

### LINKED ISSUE #1399: Error using tf.image.random._ : 'numpy.ndarray' object has no attribute 'get_shape'
**Intro**

I am using a modified version of the Tensorflow tutorial "Deep MNIST for experts" with the Python API for a medical images classification project using convolutionnal networks.

I want to artificially increase the size of my training set by applying random modifications on the images of my training set.

**Problem**

When I run the line : 
    
`flipped_images = tf.image.random_flip_left_right(images)`

I get de following error :

> AttributeError: 'numpy.ndarray' object has no attribute 'get_shape'

My Tensor "images" is an ndarray (shape=[batch, im_size, im_size, channels]) of "batch" ndarrays (shape=[im_size, im_size, channels]).

Just to check if my input data was packed in the right shape and type, I have tried to apply this simple function in the (not modified) tutorial "Tensorflow Mechanics 101" and I get the same error.

Finally, I still get the same error trying to use the following functions :

 - tf.image.random_flip_up_down() 
 - tf.image.random_brightness()
 - tf.image.random_contrast()

**Questions**

As input data is usually carried in Tensorflow as ndarrays, I would like to know :   

 1. Is it a bug of Tensorflow Python API or is it my "fault" because
    of the type/shape of my input data?
 2. How could I get it to work and be able to apply    "tf.image.random_flip_left_right" to my training set?

### PR DESCRIPTION
**Pull request by fayeshine**
Fix Error using tf.image.random._ : 'numpy.ndarray' object has no attribute 'get_shape' #1399 by fix flip_left_to_right to call convert_to_tensor
Fixes #1399

### CODE REVIEW

**Comment by fayeshine** [comment]
I signed it!

**Comment by girving** [comment]
Looks good!  @martinwicke: Can you launch the tests?

**Comment by martinwicke** [comment]
You can, too!

Jenkins, test this please.

**Comment by girving** [comment]
@martinwicke: How does one look at the test output?  http://ci.tensorflow.org/job/tensorflow-pull-requests-mac-python3/99/console shows which tests fail, but I don't know how to see how they fail.

**Comment by martinwicke** [comment]
http://ci.tensorflow.org/job/tensorflow-pull-requests-mac-python3/99/consoleFull shows the full log. Also, theres's a little button on top of the log to show the full output.

This looks fine, these three python3 tests are unrelated.

**Comment by girving** [comment]
If I have the power to run tests, does that also mean I have the power to merge?  What's the process for that these days?

**Comment by fayeshine** [comment]
@girving @martinwicke So does this mean it is OK to merge this? :smiley:

**Comment by girving** [comment]
Merged!

**Comment by girving** [comment]
https://github.com/tensorflow/tensorflow/commit/b4b2575ec4bf7e6da2686505f61b5f16cb9273ab

**Pull request closed without merging**
