### PR TITLE
_decayed_lr do not cast self.iterations when scheduler is used

### PR DESCRIPTION
**Pull request by SimplifyAll**
PiecewiseConstantDecay do not accept float step, other schedulers are casting step by themselves

### CODE REVIEW

**Comment by SimplifyAll** [comment]
I signed it!

**Review by tanzhenyu — APPROVED** [review]

**Comment by gbaned** [comment]
@tanzhenyu can you please check build failures

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@SimplifyAll Did you get a chance to look on build failures? Please let us know on the update. Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
