### PR TITLE
Added Variable shape and lookup errors TCs.

### PR DESCRIPTION
**Pull request by amitsrivastava78**
This is one of the TODO in the file.

### CODE REVIEW

**Comment by gbaned** [comment]
@miaout17 Could you PTAL and approve.

**Review by miaout17 — APPROVED** [review]

**Comment by amitsrivastava78** [comment]
@miaout17 , thanks for approving the PR, could you please help to get this merged.


Regards
Amit

**Comment by miaout17** [comment]
Yes this should be merged soon

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by rthadur** [comment]
@amitsrivastava78 can you please fix build failures ?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
