### PR TITLE
Beam Search Wrapper

### PR DESCRIPTION
**Pull request by anair13**
I've been working with the beam search implementation @nikitakit wrote to fix issue #654 , and found the outputs aren't exactly what they should be (unless I'm misunderstanding something). It seems the top output is correct but the rest of the beams are not reordered correctly in the computation. This is my fixed version with a more detailed test case to prove correctness, as well as an attention wrapper to be able to use beam search with attention without much effort. I think it would be great to nail down some official solution.

### CODE REVIEW

**Comment by therne** [comment]
`cand_symbols` and `cand_probs` are not updated? unwrap functions use these states as output but I can't see any updating code...

**Comment by vrv** [comment]
@ebrevdo can you take a look at this?  Does this make sense for TensorFlow core, or does this maybe belong in a separate, more focused repo?

**Comment by ebrevdo** [comment]
@lukaszkaiser let's discuss this one on Monday.

**Comment by lukaszkaiser** [comment]
Ok, maybe around 3pm?

Lukasz

**Comment by ebrevdo** [comment]
Unfortunately, without the original author of the beam search code having provided a clear license in their original gist/github, we cannot accept code except from that author.

That said, the attention wrapper looks like it's original (is it?  if not, do you have details about the original license?)  So if you want, you can submit that on its own with corresponding unit tests for review.  Please look at some other code and unit tests to ensure you conform to code and documentation guidelines.

Thanks!

**Comment by nikitakit** [comment]
I want to chime in here and say that I'm happy to have my code included in contrib, just like I said in the original issue.

I've been away on vacation until recently, which is why you've only been hearing from @anair13 so far.

@ebrevdo I can resubmit my parts under my name if you'd like. (Though I wouldn't be comfortable doing so without first fixing the bugs and getting the tests into shape.) That said, I would find it extremely useful to hear some comments on the high-level approach (i.e. cell wrapping, as opposed to dynamic loops or custom ops) and API design before writing any more code.

**Comment by anair13** [comment]
Thanks for looking at this everyone. As @nikitakit said, I think it would be good to discuss the approach here (personally, I think this way of implementing both attention and beam search as wrappers is simpler to understand and easier to modify) and make changes as we go.

I can fix the issue mentioned by @therne as I had commented out parts I had not tested, and also contribute some new tests and a sequence to sequence model with attention and beam search.

**Comment by ebrevdo** [comment]
Have you seen the `AttentionCellWrapper` we have in [contrib.rnn](https://github.com/tensorflow/tensorflow/blob/ad9e5b29aeee6638476cb47522bc880876eaab86/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L670)?

`tf.nn.raw_rnn` is now safe to use; so any decoding algorithms should probably use it.

**Comment by ebrevdo** [comment]
@nikitakit if you could take a look at AttentionCellWrapper and `raw_rnn` and let us know whether you would like to add onto these or build on top of these, we can decide whether your work should go into core, contrib, or is better suited for its own, higly focused, "model" repo.

**Comment by nikitakit** [comment]
@ebrevdo All attention code here is by @anair13. To be honest I'd prefer to keep the beam search and attention discussions separate, because their implementations should be orthogonal. (The beam search code can work with any attention implementation, including the built-in AttentionCellWrapper).

I would love to build on top of `raw_rnn`, but unfortunately its API is still not expressive enough to support beam search. Beam search needs to have access to intermediate cell states (not just inputs/outputs), because items that fall off the beam need to have their cell state removed and replaced with that of another item. 

Now if `raw_rnn` could be modified to receive `cell_state` into the loop function and output a `new_cell_state` from it, then it's a different story.

**Comment by anair13** [comment]
Thanks for the reply @ebrevdo. I hadn't seen the AttentionCellWrapper before, and thats exactly what the one included here does so I'll take it out.

**Comment by ebrevdo** [comment]
Nikita I'll consider adding control of state in raw_rnn.  The interface is
still flexible

**Comment by nikitakit** [comment]
@ebrevdo If you could add state control to raw_rnn, that would be much appreciated. Using that API should also provide performance improvements for beam search, because it will allow early termination using dynamic_rnn primitives.

**Pull request closed without merging**
