### PR TITLE
Added a "note" in tf.where documentation suggesting a workaround for issue #38349

### PR DESCRIPTION
**Pull request by codeadmin-peritiae**
Added a note in nt.where documentation...

### CODE REVIEW

**Comment by iamharshit13** [comment]
can anyone please explain this to me

**Comment by codeadmin-peritiae** [comment]
> can anyone please explain this to me

Can I help you?

**Comment by iamharshit13** [comment]
> > can anyone please explain this to me
> 
> How can I help you?

Actually I am new to this issue and request stuff, where can i find proper documentation on dealing with this.

**Comment by mihaimaruseac** [comment]
This does not look like a valid PR. Closing.

For contributing, see https://www.tensorflow.org/community/contribute

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Nothing to review

**Comment by codeadmin-peritiae** [comment]
> Nothing to review

Dear @mihaimaruseac 
I'm a regular contributor... and I tried to follow contribution guidelines...
According to @mdanatg suggestion, (please see issue #38349 ) this contribution is just a workaround note meanwhile me and any other is interested  are working on a complete solution (not so easy to find)...
This is the reason why there is no code to review.
Where am I wrong?
Thank you.

**Comment by codeadmin-peritiae** [comment]
> > > can anyone please explain this to me
> > 
> > 
> > How can I help you?
> 
> Actually I am new to this issue and request stuff, where can i find proper documentation on dealing with this.

I'm not sure to get a correct understanding of your question...

All information were into the issue #38349 description.
I just followed Dan Moldovan's suggestion to split the work in two: (a) to patch the documentation and (2) to address the issue (because it looks like very hard...)
Firs part was trivial and I submitted a Pull Request wit a few comment line...
If you wish, we can work together on the second part. I'll be proud of it.

By the way, I don't understand why mr. Mirai Marusac closed the PR and I asked him a clarification...

**Comment by mdanatg** [comment]
@codeadmin-peritiae The PR appears to be completely empty - it should at least contain the documentation updates.

**Comment by mihaimaruseac** [comment]
Apologies @codeadmin-peritiae. The PR looked empty, no code changes were present

**Comment by codeadmin-peritiae** [comment]
> Apologies @codeadmin-peritiae. The PR looked empty, no code changes were present

It's me I have to apologise for...
My Sourcetree GitHub client had went in trouble with a SSH certificate...
I re-submitted my contribution as PR #41775 
Thanks a lot for your support.
G.

**Comment by codeadmin-peritiae** [comment]
> @codeadmin-peritiae The PR appears to be completely empty - it should at least contain the documentation updates.

I'm sorry, please see my comment above. Thanks. G.

**Pull request closed without merging**
