### PR TITLE
[TFLM] TANH kernel refactoring

### PR DESCRIPTION
**Pull request by yair-ehrenwald**
In preparation for adding support for  an optimized version of TANH for CEVA-DSP cores, refactoring and separation of tanh into tanh.cc and tanh_common.cc to allow for reference fallback from the optimized kernel.

@advaitjain I haven't removed uint8 support yet since that's pretty much all the tests are for, so I'm assuming its in use here? Let me know what you think.

### CODE REVIEW

**Review by advaitjain — CHANGES_REQUESTED** [review]
Looks like a lot of wires got crossed while porting TANH from TfLite to TFLM.

The TfLite implementation does have int8 tests: https://github.com/tensorflow/tensorflow/commit/9b542ce7ef0cb6870da4622c1c8951ee83cdb4d5

The Tflite Tanh is part of activations.cc:
https://github.com/tensorflow/tensorflow/blob/409e0a78a1bd5b56fb7247dca683ee7a1b52e036/tensorflow/lite/kernels/activations.cc#L1531-L1537

Tanh in TFLM was originally ported into elementwise.cc: https://github.com/tensorflow/tensorflow/pull/39181

and then moved into its own tanh.cc: https://github.com/tensorflow/tensorflow/commit/f0f84935e31bc7957d7311ceba53ba02271ad9f4

PR https://github.com/tensorflow/tensorflow/pull/35000 also attempted to port TANH from lite to micro (in activations.cc) but ignored the int8 tests. And the PR itself was not merged. Instead https://github.com/tensorflow/tensorflow/commit/71a74e6882e89221de9dba99a1a4378a47034ff0 had many of the same changes but not all.

Given this convoluted history of Tanh, I think we should treat Tanh as an OP that we need to port again from TfLite. Here's what I think we should do:

1. Delete the existing Tanh implementation in TFLM (let's do this in its own PR)
1. Port Tanh from TFL to TFLM in micro/kernels/activations.cc to be consistent with the TfLite structure.
   * Remove uint8 support and tests from TFLM).
   * If you'd like, you can have this be refactored into activations.h and activations_common.cc since you will need that for the CEVA optimized PR.
1. add in CEVA optimizations for Tanh

Let me know what you think.

**Comment by gbaned** [comment]
@yair-ehrenwald  Can you please check @advaitjain's comments and keep us posted ? Thanks!

**Comment by gbaned** [comment]
@yair-ehrenwald Any update on this PR? Please. Thanks!

**Comment by advaitjain** [comment]
With TFLM moving to its own GitHub repository, we are not going to be merging any TFLM specific pull requests in the TensorFlow repository starting today.

I am closing the current PR but please feel free to open a new PR in https://github.com/tensorflow/tflite-micro/.

https://groups.google.com/a/tensorflow.org/g/micro/c/W4DACgjPmOE

**Pull request closed without merging**
