### PR TITLE
tflite-runtime wheels for Python 3.11

### LINKED ISSUE #60115: Publish Python 3.11 Wheels for `tflite-runtime`
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux x86 & ARM
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: N/A
-   **TensorFlow installed from (source or binary)**: Binary
-   **TensorFlow version (use command below)**: N/A
-   **Python version**: N/A
-   **Bazel version (if compiling from source)**: N/A
-   **GCC/Compiler version (if compiling from source)**: N/A
-   **CUDA/cuDNN version**: N/A
-   **GPU model and memory**: N/A
-   **Exact command to reproduce**: N/A

### Describe the problem

[`tensorflow 2.12.0` has published Python 3.11 wheels to PyPI](https://pypi.org/project/tensorflow/2.12.0/#files). The [latest `tflite-runtime-nightly`](https://pypi.org/project/tflite-runtime-nightly/2.13.0.dev20230324/#files) do not have 3.11 wheels.

I request that 3.11 wheels be built and published to PyPI for `tflite-runtime`.

CC @terryheo 

### Related Issues

- #58032
- #56137

### PR DESCRIPTION
**Pull request by samypr100**
Closes #60115

This is a follow on PR to #59423 adding support for Python 3.11 wheel while still retaining a minimum of glibc 2.31 runtime.

* The minimum Numpy versions was increased to `1.23.2` as it's the first version with Python 3.11 support.
* **Python 3.7 support was dropped** due to the Numpy upgrade.
* Fixed a typo in the include paths in download_toolchains.sh `aaarch64` --> `aarch64`

### Related Issues
* #58032

### CODE REVIEW

**Review by haozha111 — APPROVED** [review]

**Comment by samypr100** [comment]
Is there anything else to adjust/todo on this one? Seems like the internal CI builds are working at a glance. Thanks!

**Review by terryheo — APPROVED** [review]
LGTM. Thanks for your contribution!

**Comment by johnthagen** [comment]
@terryheo Just checking if this can be merged. Thanks!

**Comment by gbaned** [comment]
> @terryheo Just checking if this can be merged. Thanks!

Hi @samypr100 Sorry for the delay. This PR is processing internally, Thank you!

**Comment by johnthagen** [comment]
@gbaned Just checking in if you found any issues during internal testing that the community can help address.

Do you think that this MR will make it into the 2.13.0 release?

Thanks!

**Comment by samypr100** [comment]
Good question, I'm curious too. Open to make any other changes needed 💯  to get this 🚢

**Comment by gbaned** [comment]
Hi @terryheo Can you please assist on above comments from @johnthagen, @samypr100. Thank you!

**Comment by ShamoX** [comment]
Hello all,
And thank you for all your work.
Any news on this, or should we stay in python 3.10 for tflite-runtime?

**Review by terryheo — APPROVED** [review]
LGTM

**Comment by terryheo** [comment]
Once this PR is merged, the next TF release (2.14?) will have Python 3.11 releases.

**Comment by samypr100** [comment]
Thanks @terryheo I've just re-updated the branch w/ master to make sure it's clean

**Comment by ShamoX** [comment]
One of the tests seems to fail in 3.10 and is not failing in master (From what I checked, this is another that is failing).

```
//bazel_pip/tensorflow/python/data/experimental/kernel_tests/service:local_workers_test TIMEOUT in 1 out of 24 in 900.1s
  Stats over 24 runs: max = 900.1s, min = 6.1s, avg = 50.8s, dev = 177.1s
```

**Comment by samypr100** [comment]
@ShamoX Seems like the [arm-ci.yml](https://github.com/tensorflow/tensorflow/actions/workflows/arm-ci.yml?query=branch%3Amaster) workflow has been failing in master from what I'm seeing at least these past few days

**Pull request merged**
