### PR TITLE
quick python3 fix

### PR DESCRIPTION
**Pull request by chemelnucfin**
use as instead of comma for python3 compatibility

### CODE REVIEW

**Comment by chemelnucfin** [comment]
apparently only python 2.6 and above though.
http://stackoverflow.com/questions/12682558/how-to-write-an-exception-catching-code-works-in-python2-4-to-python3

**Comment by martinwicke** [comment]
Thanks! Just did the same without seeing yours. I'll merge yours (tests are in #1508). We'll need more fixed though.

**Comment by chemelnucfin** [comment]
@martinwicke ya, I fixed one other simple one with the b missing in front of the string.  A lot of the others require diving into the C++ part and/or server/clients and haven't gone deep into them yet.
Thanks for merging mine and hopefully you don't mind I stepped on your path again.  :)

**Comment by martinwicke** [comment]
No problem. Always nice to have backup. :)

**Pull request merged**
