### PR TITLE
Fix freeze_graph command line argument error.

### PR DESCRIPTION
**Pull request by aaronzs**
Fix TypeError: main() missing 1 required positional argument: 'unused_args' when using freeze_graph command line tool (pip console script entry point)

### CODE REVIEW

**Comment by aaronzs** [comment]
@googlebot I signed it!

**Comment by yesmung** [comment]
Dear 

 

I appreciate your guide. 

I have already signed a CLA. So, I have changed my primary e-mail address from this to yesmung@gmail.com <mailto:yesmung@gmail.com>  

Do I have any more to do?

 

Thank you

Best regards

**Comment by vrv** [comment]
I don't fully understand the fix.

https://github.com/tensorflow/tensorflow/blob/28c3c5dd38e3b397c2cf0acdaa6388dcbf0349f7/tensorflow/python/platform/app.py#L124

This should be calling main() with some form of argv.

I believe all of TF scripts are written this way, so I don't think it makes sense to modify this one in isolation.  Can you provide more information for what's going wrong? Maybe some sample command line and code?

**Comment by aaronzs** [comment]
@vrv 
The code works fine when using `python -m tensorflow.python.tools.freeze_graph`, but with the 
 new command line tool added in r1.5, it will return `TypeError: main() missing 1 required positional argument: 'unused_args'`

I just find that this PR is duplicate with PR #15906, so close it.

**Pull request closed without merging**
