### PR TITLE
Specify python versio via build arg PYTHON_VERSION

### PR DESCRIPTION
**Pull request by ysgit**
Allow python version to be specified as requested in #25939

### CODE REVIEW

**Comment by cipri-tom** [comment]
This is so cool ! Thank you! Hoping it will get merged soon ^^

**Comment by gbaned** [comment]
@ysgit Could you please resolve the conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
similar changes are merged , so closing this PR, thank you for your contribution.

**Pull request closed without merging**
