### PR TITLE
Merge r1.9.0 branch back into master

### PR DESCRIPTION
**Pull request by case540**
Doing this to basically pick up version string changes, make tf.__git_version__ show 1.9.0 tag
when building on master branch, and to make sure to pick up any fixes committed directly
to the release branch.

### CODE REVIEW

**Comment by case540** [comment]
No idea why this is complaining about CLA stuff?

**Comment by av8ramit** [comment]
That's happened quite a few times recently

**Review by av8ramit — DISMISSED** [review]

**Comment by case540** [comment]
Done

**Comment by case540** [comment]
pinging this. I think it needs to be re-approved

**Review by av8ramit — APPROVED** [review]

**Comment by av8ramit** [comment]
Done.

**Pull request merged**
