### PR TITLE
Cherry-pick in additional bug fixes to r1.4 branch.

### PR DESCRIPTION
**Pull request by case540**
Fixes to Datasets, S3 file system, and a change to no longer set random seed in Estimator run_config.

### CODE REVIEW

**Review by mrry — APPROVED** [review]
`Dataset.from_generator()` changes LGTM. Thanks!!

**Review by av8ramit — APPROVED** [review]

**Comment by av8ramit** [comment]
kernel_tests:dataset_from_generator_op_test is timing out

**Comment by case540** [comment]
Hmmm, locally dataset_from_generator_op_test runs and passes just fine. mrry, do you know what could be causing this?

**Comment by vrv** [comment]
@tensorflow-jenkins

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

(I assume I'm supposed to test again?)

**Pull request merged**
