### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by ManHyuk**
memory_intialized -> memory_initialized
set_memory_intialized -> set_memory_initialized

instrucion -> instruction

elment -> element

tensroflow -> tensorflow

interpretted -> interpreted

### CODE REVIEW

**Comment by sb2nov** [comment]
In general we avoid renaming fields in a proto so it might not be a safe change.

**Comment by mrry** [comment]
+1 all the changes apart from the proto field name change look good.

AFAICT, the `ExecProfile.memory_intialized` (sic) field isn't used anywhere else in the codebase, but @panyx0718 might be able to comment on whether that proto is part of any public APIs that might be broken by the change.

**Comment by panyx0718** [comment]
The change passed api_compatibility_test. So it's not part of public API.

**Comment by drpngx** [comment]
OK, then I take that to be an approval then.

**Review by drpngx — APPROVED** [review]
Per @panyx0718 comment.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins, test this please.

**Pull request merged**
