### PR TITLE
The following upstream commits caused a 15% performance degradation o…

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
…n the resnet50 model for ROCm:

4193058f98378f6f67db0cc67fb68332f8396d41: increase row tiling to 64
37ddd35d129280e80a847f09264118c7a0cbd894: enable tree reduction by default

The changes were "undone" for ROCm by guarding the previous implementation details with the TENSORFLOW_USE_ROCM macro.

The commit which increased row tiling to 64 made substantial changes to the reduce_unnested.hlo unit test to accomodate the change so the test fails on ROCm with this commit.

Therefore, the reduce_unnested.hlo unit test has been disabled.

### CODE REVIEW

**Review by cheshire — CHANGES_REQUESTED** [review]
We can't really do this: let's investigate why does the regression occur.

**Comment by rsanthanam-amd** [comment]
@cheshire I am not familiar with how to measure an XLA kernel such as fusion_235 with and without tree reduction.  Please let me know how I can make similar measurements on ROCm.  Also, I am not familiar with what is meant by "67% of roofline".

**Comment by cheshire** [comment]
- "roofline" is the best-possible performance. This is determined by
bandwidth of the GPU (e.g. 650GB/s for Titan V), and the size of the
input/output buffers.
As an example, if we are reducing an array of size 650GB on Titan V, and
the operation took one second, we can't possibly do better (100% roofline).
If it takes 2 seconds, that's 50% roofline, etc.

> I am not familiar with how to measure an XLA kernel such as fusion_235
with and without tree reduction
You can set env XLA_FLAG=--xla_gpu_deterministic_reductions=false ...

**Comment by rsanthanam-amd** [comment]
@cheshire Sorry, I have should been more specific.  I am not sure how to measure the XLA kernel performance as you did (471ms vs. 476ms etc.).

**Comment by cheshire** [comment]
Hi,

You could use https://www.tensorflow.org/tensorboard, where the trace view
should tell you how much time each kernel takes (the kernel name will
correspond to the fusion name).

Alternatively, given that you work for AMD, I'm sure that AMD has profilers
and tools to give you the trace view which would show you each kernel on
the timeline, and that you can get access to that expertise better than I
can.

**Comment by rsanthanam-amd** [comment]
@cheshire I measured a large difference in execution time for fusion_235 on ROCm:

| Configuration | fusion_235 execution time |
| tree reduction disabled and row tiling size = 16 | 4.3 ms |
| tree reduction enabled and row tiling size = 64 | 17.6 ms |

**Comment by cheshire** [comment]
OK but could you debug on what is actually going on? Why is it slow? Is it spilling registers? How far are these numbers from theoretical roofline?

**Comment by rsanthanam-amd** [comment]
@cheshire I am currently in debugging mode.

By inspecting the HLO, I noticed that on CUDA, XLA uses NHWC for fp16 but on ROCm, it uses NCHW for fp16.

I'm wondering if at a high level, that could explain the performance difference on ROCm and the lack of a performance difference on CUDA.

**Comment by cheshire** [comment]
What %% of the overall benchmark runtime is spent in convolutions?

**Comment by rsanthanam-amd** [comment]
@cheshire 

Here is the % of time spent in convolution kernels on ROCm with this resnet50 model:

No Tree Reductions/Row tiling size = 16: 23.6%
Tree Reductions/Row tiling size = 64: 19.3%

**Comment by rsanthanam-amd** [comment]
@cheshire 

Tree reduction cracks a single reduction op into 2 reduction ops to avoid the need for atomics.

How does this guarantee deterministic output?

**Comment by cheshire** [comment]
Because at most one block writes to one output location.

**Comment by gbaned** [comment]
@rsanthanam-amd Can you please resolve conflicts? Thanks!

**Comment by rsanthanam-amd** [comment]
@gbaned Done.

**Comment by cheshire** [comment]
@gbaned This is not awaiting response.

@rsanthanam-amd Sorry for the confusion. Deterministic output is a requirement, we can't conditionally disable it for AMD. Do you think you could try to figure out where exactly the slowdown is coming from?

**Comment by rsanthanam-amd** [comment]
@cheshire I am still working on that.

**Review by cheshire — CHANGES_REQUESTED** [review]

**Review by cheshire — APPROVED** [review]

**Pull request merged**
