### PR TITLE
Update mnist.py

### PR DESCRIPTION
**Pull request by 15751064254**
Comment modification

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by yifeif** [comment]
Thanks @15751064254! Could you fix cla?

**Comment by snnn** [comment]
Pardon? [0,NUM_CLASSES] has NUM_CLASSES+1 numbers!

**Comment by yifeif** [comment]
ah thanks @snnn! Totally missed that. @15751064254 I will close this PR for now.

**Comment by 15751064254** [comment]
Thanks @tensorflow-jenkins I CLA has been submitted.

**Pull request closed without merging**
