### PR TITLE
Branch 134001275

### PR DESCRIPTION
**Pull request by martinwicke**

### CODE REVIEW

**Comment by martinwicke** [comment]
There was a conflict in the gif.BUILD. I basically took @jart's version which is much cleaner, but since there was a fix, I'm not sure it strictly supercedes it, and I'm also not sure whether our CI would catch a problem if there was one with my attempt at a merge. Please let me know if I did it wrong.

**Review by mrry — APPROVED** [review]
`gif.BUILD` change looks good to me.

**Comment by mrry** [comment]
@meteorcloudy: FYI about the `gif.BUILD` change.

**Comment by martinwicke** [comment]
Jenkins, test this please

**Comment by jart** [comment]
The MacOS CPU tests appear to have failed because the GitHub server timed out on the download. Maybe I should really prioritize figuring out that mirror situation.

The cmake CI might be configured incorrectly, since it's saying the bazel command was not found.

**Comment by martinwicke** [comment]
I'm retesting, but cmake may not work still. Derek?

**Comment by mrry** [comment]
According to @caisq on #4537, the CI is misconfigured to run `bazel` even when it's not necessary. He said he'd take a look soon.

**Comment by caisq** [comment]
See https://github.com/tensorflow/tensorflow/pull/4541 regarding the cmake-bazel issue.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by meteorcloudy** [comment]
@mrry I also reviewed the `gif.BUILD` change internally, Looks good. :)

**Comment by martinwicke** [comment]
There's still an issue with the CMAKE tests -- something about SHA and ALGO. @caisq, @mrry any idea?

**Comment by mrry** [comment]
Looks like https://github.com/tensorflow/tensorflow/commit/c5983f87f0402f2cb8c627807917ebdf8e4d4bb6 introduced a dependency between `eigen.cmake` and `workspace.bzl`, and the following code was deleted somewhere in this PR:

```
  # These lines need to be changed when updating Eigen. They are parsed from
  # this file by the cmake and make builds to determine the eigen version and hash.
  eigen_version = "6bcd74d2fa40"
  eigen_sha256 = "df3ca8a395fb615003762b8748c03e3aa7a8932b5674dbb5a6bd3343cc3f408d"

  native.new_http_archive(
    name = "eigen_archive",
    url = "https://bitbucket.org/eigen/eigen/get/" + eigen_version + ".tar.gz",
    sha256 = eigen_sha256,
    strip_prefix = "eigen-eigen-" + eigen_version,
    build_file = str(Label("//:eigen.BUILD")),
  )
```

**Comment by vrv** [comment]
I think it was the 'simplify bazel' commit. look at what the makefile did in that PR and maybe the same thing can be done in cmake?

**Comment by martinwicke** [comment]
Ok. Killing this and making a new one.

**Comment by martinwicke** [comment]
I've reinstated the dependent lines. We can sort it out later, but I want this push out.

**Pull request closed without merging**
