### PR TITLE
[*] Rename "Arguments:" to "Args:"

### PR DESCRIPTION
**Pull request by SamuelMarks**
I've written custom parsers and emitters for everything from docstrings to classes and functions. However, I recently came across an issue with the TensorFlow codebase: inconsistent use of `Args:` and `Arguments:` in its docstrings:

```sh
(tensorflow#d393534)$ for name in 'Args:' 'Arguments:'; do
    printf '%-10s %04d\n' "$name" "$(rg -IFtpy --count-matches "$name" | paste -s -d+ -- | bc)"; done
Args:      5333
Arguments: 0820
```

It is easy enough to extend my parsers to support both variants, howevever it looks like `Arguments:` is wrong anyway, as per:

  - https://google.github.io/styleguide/pyguide.html#doc-function-args @ [`ddccc0f`](https://github.com/google/styleguide/blob/ddccc0f/pyguide.md)
  - https://chromium.googlesource.com/chromiumos/docs/+/master/styleguide/python.md#describing-arguments-in-docstrings @ [`9fc0fc0`](https://chromium.googlesource.com/chromiumos/docs/+/9fc0fc0/styleguide/python.md)
  - https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html @ [`c0ae8e3`](https://github.com/sphinx-contrib/napoleon/blob/c0ae8e3/docs/source/example_google.rst)

Therefore, only `Args:` is valid. This PR replaces them throughout the TensorFlow codebase.

PS: The trackbacks automatically appearing below are sending the same changes to other repositories in the [TensorFlow](https://github.com/tensorflow/tensorflow) and [keras-team](https://github.com/keras-team) organisations.

### CODE REVIEW

**Comment by bhack** [comment]
I think that without having this in day-by-day linting/sanity CI we will go to diverge again.
Do you think that you can solve this with [`pylint.extensions.docparams`](http://pylint.pycqa.org/en/latest/technical_reference/extensions.html) in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/pylintrc?

**Comment by SamuelMarks** [comment]
@bhack Hmm, I made those changes in the linter, but it picked up a whole bunch of other changes. Might be worth separating into a separate PR, called "linting", and merging this one? - Your call.

**Comment by bhack** [comment]
I think that you can open a parallel linter PR without fixes in then meantime so that we could see from the CI what Is failing.

**Review by kkimdev — APPROVED** [review]

**Comment by gbaned** [comment]
@SamuelMarks  Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@SamuelMarks  Any update on this PR? Please. Thanks!

**Comment by SamuelMarks** [comment]
🤔
```
$ pylint --rcfile='tensorflow/tools/ci_build/pylintrc' 'tensorflow/compiler/xla/python/xla_client.py'
************* Module python.xla_client
tensorflow/compiler/xla/python/xla_client.py:66:0: W9015: "distributed_client, node_id" missing in parameter documentation (missing-param-doc)
tensorflow/compiler/xla/python/xla_client.py:66:0: W9016: "distributed_client, node_id" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:125:6: R1720: Unnecessary "else" after "raise" (no-else-raise)
tensorflow/compiler/xla/python/xla_client.py:137:0: W9016: "name" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:137:0: W9012: Missing return type documentation (missing-return-type-doc)
tensorflow/compiler/xla/python/xla_client.py:137:0: W9006: "RuntimeError" not documented as being raised (missing-raises-doc)
tensorflow/compiler/xla/python/xla_client.py:153:6: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
tensorflow/compiler/xla/python/xla_client.py:137:0: W9012: Missing return type documentation (missing-return-type-doc)
tensorflow/compiler/xla/python/xla_client.py:159:0: R0205: Class 'OpMetadata' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
tensorflow/compiler/xla/python/xla_client.py:159:0: W9015: "op_name, op_type, source_file, source_line" missing in parameter documentation (missing-param-doc)
tensorflow/compiler/xla/python/xla_client.py:159:0: W9016: "op_name, op_type, source_file, source_line" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:170:0: W9015: "op_name, op_type, skip_frames" missing in parameter documentation (missing-param-doc)
tensorflow/compiler/xla/python/xla_client.py:170:0: W9016: "op_name, op_type, skip_frames" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:213:0: W9015: "dtype" missing in parameter documentation (missing-param-doc)
tensorflow/compiler/xla/python/xla_client.py:213:0: W9016: "dtype" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:279:0: W9015: "pyval" missing in parameter documentation (missing-param-doc)
tensorflow/compiler/xla/python/xla_client.py:279:0: W9016: "pyval" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:283:4: R1705: Unnecessary "else" after "return" (no-else-return)
tensorflow/compiler/xla/python/xla_client.py:341:0: W9015: "arguments, backend, executable" missing in parameter documentation (missing-param-doc)
tensorflow/compiler/xla/python/xla_client.py:341:0: W9016: "arguments, backend, executable" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:352:0: W9016: "arguments, backend, executable" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:352:0: W9012: Missing return type documentation (missing-return-type-doc)
tensorflow/compiler/xla/python/xla_client.py:386:0: W9015: "lhs_dims, padding_type, rhs_dims, window_strides" missing in parameter documentation (missing-param-doc)
tensorflow/compiler/xla/python/xla_client.py:386:0: W9016: "lhs_dims, padding_type, rhs_dims, window_strides" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:402:2: R1705: Unnecessary "elif" after "return" (no-else-return)
tensorflow/compiler/xla/python/xla_client.py:426:0: W9016: "fn, name, platform" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:441:0: R0205: Class 'PaddingConfigDimension' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
tensorflow/compiler/xla/python/xla_client.py:451:0: R0205: Class 'PaddingConfig' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
tensorflow/compiler/xla/python/xla_client.py:472:5: R1701: Consider merging these isinstance calls to isinstance(padding_config, (list, tuple)) (consider-merging-isinstance)
tensorflow/compiler/xla/python/xla_client.py:484:0: R0205: Class 'DotDimensionNumbers' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
tensorflow/compiler/xla/python/xla_client.py:512:2: R1705: Unnecessary "else" after "return" (no-else-return)
tensorflow/compiler/xla/python/xla_client.py:524:0: R0205: Class 'ConvolutionDimensionNumbers' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
tensorflow/compiler/xla/python/xla_client.py:608:0: R0205: Class 'OpSharding' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
tensorflow/compiler/xla/python/xla_client.py:623:0: R0205: Class 'PrecisionConfig' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
tensorflow/compiler/xla/python/xla_client.py:633:0: R0205: Class 'GatherDimensionNumbers' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
tensorflow/compiler/xla/python/xla_client.py:645:0: R0205: Class 'ScatterDimensionNumbers' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
tensorflow/compiler/xla/python/xla_client.py:657:0: R0205: Class 'ReplicaGroup' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
tensorflow/compiler/xla/python/xla_client.py:686:0: W9015: "enabled" missing in parameter documentation (missing-param-doc)
tensorflow/compiler/xla/python/xla_client.py:686:0: W9016: "enabled" missing in parameter type documentation (missing-type-doc)
tensorflow/compiler/xla/python/xla_client.py:696:0: W9015: "client" missing in parameter documentation (missing-param-doc)
tensorflow/compiler/xla/python/xla_client.py:33:0: C0411: third party import "from absl import logging" should be placed before "from . import xla_extension as _xla" (wrong-import-order)
tensorflow/compiler/xla/python/xla_client.py:34:0: C0411: third party import "import numpy as np" should be placed before "from . import xla_extension as _xla" (wrong-import-order)

------------------------------------------------------------------
Your code has been rated at 8.47/10 (previous run: 8.47/10, +0.00)
```

**Review by kkimdev — APPROVED** [review]

**Comment by SamuelMarks** [comment]
The CI builds were failing, so I merged in master and did it again. We've got to be faster with this process, otherwise master will diverge too much.

**Comment by SamuelMarks** [comment]
The CI builds were failing, so I merged in master and did it again. We've got to be faster with this process, otherwise master will diverge too much.

@kkimdev @gbaned

**Review by kkimdev — APPROVED** [review]

**Comment by kkimdev** [comment]
This PR touches a lot of files, so I won't be surprised if it's difficult to land (passing Github CI is not the end, TF engineers have to approve and land internally.).  Let's give it a shot, but if fails, I think it could be better to split this PR.

**Pull request merged**
