### PR TITLE
Add summary, args and exceptions raised for zeros_initializer docstring

### PR DESCRIPTION
**Pull request by mandroid6**
Closing multiple issues listed in #26532 one by one in this pull request.

Added summary, args and exceptions to the ``tf.zeros_initializer``  #26538 docs.

Tasks to be done:
 - tf.unstack #26534
 - tf.unique #26535
 - tf.zeros #26537

### CODE REVIEW

**Comment by mandroid6** [comment]
Could anyone help me as to where to make changes for code generated docs. I read the ``api_def_Unique.pbtxt`` in ``api_def_Unique.pbtxt``, but couldn't find the complete docstring visible on the ``tf.unique`` API page

**Comment by gunan** [comment]
I am not a good reviewer for this change. Please redirect.

**Review by tamaranorman — CHANGES_REQUESTED** [review]
Please note that on the docs site this method does have generated docs on the API page as it inherits them from the base class but I am aware it doesn't when you look at docs within an editor

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
