### PR TITLE
Add a function for generating random values with predefined seed

### PR DESCRIPTION
**Pull request by DimanNe**
I added a seeded random function, as it was requested in [this PR](https://github.com/tensorflow/tensorflow/pull/11530#issuecomment-315590857):

> Please use seeded rands to make the tests deterministic and easier to debug.

### CODE REVIEW

**Comment by DimanNe** [comment]
@drpngx , any suggestions?

**Comment by vrv** [comment]
@drpngx is out this week, unfortunately; can this wait until he gets back?

**Review by drpngx — APPROVED** [review]

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
OK, i just did this one.

**Comment by vrv** [comment]
Do these need API review the same way the python API does?

**Comment by drpngx** [comment]
There is no requirement enforced by the build system. I think the equivalent would be `tensorflow/cc` for API. I think of this more as an internal lib change.

**Comment by vrv** [comment]
Oh it's also only in lib_internal, not a public library, so yeah this is probably fine.

**Comment by vrv** [comment]
(Though a test would have been nice :)

**Pull request merged**
