### PR TITLE
[TF_Java] adding  whileLoop method for the Java API

### PR DESCRIPTION
**Pull request by melissadutz**
Co-authored-by: Irene Dea <irenedea@fb.com>
Co-authored-by: Samantha Andow <samdow@fb.com>

### CODE REVIEW

**Comment by melissagrueter** [comment]
This commit adds an all-in-one while loop method for the Java API, per discussion [here](https://github.com/tensorflow/tensorflow/pull/24842#discussion_r250655928)

cc @skye @asimshankar @karllessard

**Comment by gunan** [comment]
I have no experience with this code. Please redirect.

**Comment by skye** [comment]
@sjamesr are you able to review this?

**Comment by sjamesr** [comment]
Yes, thank you. I just got added to the tensorflow org but forgot to assign this to me.

**Review by sjamesr — APPROVED** [review]

**Pull request merged**
