### PR TITLE
Branch 172965466

### PR DESCRIPTION
**Pull request by vrv**

### CODE REVIEW

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
@gunan any ideas what's going on with some of these failures?

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by gunan** [comment]
the jenkins failures mostly seem to be due to some issues with APT during the setup phase of our dockerfiles, maybe something in ubuntu repositories changed?  I am puzzled.
It looks like ubuntu 14.10 is still not in EOL status, either.
So I am not sure what is going on with the breakages.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
I just tested https://github.com/tensorflow/tensorflow/pull/13893 and it came back clean, so if this fails once more, it's something in this push that is causing the failures, which means i probably can't push until we figure it out

**Pull request closed without merging**
