### PR TITLE
Add handle_ties arg to in_top_k Op to deal with ties.(#10767)

### PR DESCRIPTION
**Pull request by nolanliou**
[#10767](https://github.com/tensorflow/tensorflow/issues/10767)
Add handle_ties argument to in_top_k Op to make the Op more clear.

### CODE REVIEW

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@nolanliou FYI: Removing the stable sort from top_k was a mistake. We are in the process of restoring it. Perhaps this change becomes unnecessary then?

**Comment by nolanliou** [comment]
The change is about `in_top_k`, Is there a connection between `top_k` and `in_top_k`?

**Comment by rmlarsen** [comment]
@nolanliou Ah, nevermind :-)  Can you please rebase?

**Comment by nolanliou** [comment]
Sorry, I screw it up, I'll close this and reopen a PR.

**Pull request closed without merging**
