### PR TITLE
Add pre-compilation of Pascal binaries (CC 6.0/6.1)

### PR DESCRIPTION
**Pull request by mkolod**
See issue #6914.

Mentioning @vrv since he gave the go-ahead for this.

### CODE REVIEW

**Review by vrv — APPROVED** [review]
LGTM!

**Comment by vrv** [comment]
@gunan let us know if this is okay, shouldn't need to run a bunch of tests...

**Comment by mkolod** [comment]
@vrv @gunan This should be fine as long as you have CUDA 8.0 (or an equivalent version of Google-CUDA) available on the CI and Docker build server. Since we're not changing sass-based codes here (same CUBLAS and CUDNN versions), this should be fine, IMHO.

**Comment by vrv** [comment]
@mkolod agreed, just want to make sure there aren't any unexpected configs we have to update first :)

**Comment by mkolod** [comment]
@vrv @gunan Also, since this is a PR to master (rather than 0.12.1 that gcr.io/tensorflow/tensorflow:latest-devel-gpu is currently based on), I assume this won't affect containers until at least 1.0, unless an update is made to 0.12.1, which I assume is probably not advised at this point, but of course it's your decision :)

**Comment by caisq** [comment]
There is another placs where capability versions are specified in the codebase:
third_party/tensorflow/contrib/cmake/CMakeLists.txt
Line 166

Is it necessary to change that as well?

**Comment by vrv** [comment]
not in this change: the goal is to only fix the development gpu docker images.  expanding the releases to do more will involve changing a lot of other things.

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
Change looks good to me, @caisq, any objections?

**Comment by caisq** [comment]
LGTM

**Comment by mkolod** [comment]
@vrv @caisq @gunan I was also wondering if this change to master could be cherry-picked for the final 1.0 release, or maybe even now. From what I understand, the concern is not the Pascal cubins in the Docker containers, but the pip package limitations. So, maybe it would be OK to add this change to r1.0 as well? I know of several public users who would appreciate that.

**Comment by vrv** [comment]
It doesn't change the binary, just the docker at the branch, so it seems okay to me.  @martinwicke  wdyt?

**Comment by mkolod** [comment]
@vrv Ah yes, you're right, [the GPU devel Dockerfile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu) does already point to r1.0 for Git checkout, so the only issue is to ship with r1.0, rather than merging the Dockerfile into r1.0. Of course I understand that r1.0 isn't yet shippable and so "latest" means r0.12.1.

**Comment by mkolod** [comment]
@vrv @martinwicke For the r0.12 users though, would it be possible to also update the shippable compute capabilities so that users get the Pascal cubins in the nightlies even now?

**Comment by vrv** [comment]
we're probably going to release 1.0 imminently, and then the default pip install / nightlies will use 1.0, so I'd rather just wait for that.

**Comment by mkolod** [comment]
Sounds good.

**Comment by mkolod** [comment]
@vrv Also, I think I have a solution to the pip package limitation problem. There is an nvcc flag (not sure about Google's CUDA compiler) `-Xfatbin -compress-all` which compresses the cubins for storage, but uncompresses at runtime. This would enable pip packages to ship with Pascal too, while using less storage. Unfortunately, while I know how to tweak gcc flags in Bazel, I'm not sure how to tweak the nvcc ones - otherwise I would have issued a PR for that as well.

**Comment by mkolod** [comment]
@vrv @martinwicke @gunan @zheng-xq The nightly is still shipping without Pascal support, so this change hasn't been cherry-picked into the 1.0 branch, and hence the 1.0 gpu-devel Docker image. The way I tested it was via cuobjdump, but it's clear from the 1.0 branch as well (see [here](https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/tools/docker/Dockerfile.devel-gpu#L92)).

```
$ nvidia-docker run --rm -it gcr.io/tensorflow/tensorflow:latest-devel-gpu /bin/bash
root@ee4171f66f39:~# cuobjdump /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so | grep sm_ | sort | uniq
arch = sm_30
arch = sm_35
arch = sm_52

```

**Pull request merged**
