### PR TITLE
[INTEL MKL] Fix the error 'install_pip_packages.sh: line 20: pip2: command not found

### PR DESCRIPTION
**Pull request by ashahba**
This PR is to fix the `cpu` image build job here: https://tensorflow-ci.intel.com/job/tensorflow-mkl-linux-cpu/1190/console

### CODE REVIEW

**Comment by ashahba** [comment]
@agramesh1

**Comment by ashahba** [comment]
Looks like none of `install_bootstrap_deb_packages.sh`, `install_deb_packages.sh` installs `pip/pip3` prior to running `install_pip_packages.sh` and that's why the `Jenkins` job is failing.
So we have a couple of options either installing it during `install_deb_packages.sh` or using the `toolchain` scripts, but it looks like this is cleaner and all those other scripts need `python-pip` or `python3-pip` packages one way or another.

**Comment by wei-v-wang** [comment]
https://github.com/tensorflow/tensorflow/commit/e545a51504503a86c94b9a17c8e0081444d359d7 @ashahba Hi Ebi, master has the fix now it seems.

**Comment by ashahba** [comment]
Closing this since the changes to remove calls to `easy_install` has been reverted.

**Pull request closed without merging**
