### PR TITLE
Layout grappler optimization for NDHWC Conv3D

### PR DESCRIPTION
**Pull request by kaixih**
This PR is to allow the layout grappler optimizer to support Conv3D/Conv3DBackpropFilterV2/Conv3DBackpropInputV2. Specifically, the grappler pass will convert the conv3d nodes to NDHWC/NCDHW when the target format is NHWC/NCHW respectively.

This PR is corresponding to the recent CUDNN v8 support for NDHWC 3D ( https://github.com/tensorflow/tensorflow/pull/40399).

fyi: @nluehr

### CODE REVIEW

**Comment by gbaned** [comment]
@rmlarsen Can you please review this PR ? Thanks!

**Comment by kaixih** [comment]
Any update on this PR? Thanks.

**Comment by kaixih** [comment]
Just added one change to add the support for counting the conv3d nodes in deciding whether to use NHWC or NCHW for the grappler pass.

**Comment by gbaned** [comment]
@kaixih Can you please resolve conflicts? Thanks!

**Review by ezhulenev — DISMISSED** [review]

**Comment by kaixih** [comment]
The conflicts have been solved.

**Review by ezhulenev — DISMISSED** [review]

**Comment by kaixih** [comment]
Just push one more commit to fix a narrow-conversion issue for list initialization.

Now, it seems all the tests pass. @ezhulenev PTAL. Thanks.

**Review by ezhulenev — APPROVED** [review]

**Pull request merged**
