### PR TITLE
Fix TF Lite Windows build.

### LINKED ISSUE #55745: TF Lite (CMake): Does not compile on Windows
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.0

### Custom Code

No

### OS Platform and Distribution

Windows (MSVC 2019)

### Mobile device

N/A

### Python version

N/A

### Bazel version

N/A

### GCC/Compiler version

N/A

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

```shell
TF Lite fails to compile on Windows with MSVC 2019 due to `M_PI` being used by `tensorflow/core/lib/random/random_distributions_utils.h` without defining `_USE_MATH_DEFINES` (see https://docs.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=msvc-160).
```

### Standalone code to reproduce the issue

```shell
Attempt to compile TF Lite on Windows with CMake and it will fail to build with the following error:

random_ops.cc
build\tensorflow\tensorflow/core/lib/random/random_distributions_utils.h(78,27): error C2065: 'M_PI': undeclared identifier
 [build\_deps\tensorflow-build\tensorflow-lite.vcxproj]
\build\tensorflow\tensorflow/core/lib/random
/random_distributions_utils.h(78,15): error C2737: 'v1': const object must be initialized [build\_deps\tensorflow-build\tensorflow-lite.vcxproj]
```
```


### Relevant log output

_No response_</details>

### PR DESCRIPTION
**Pull request by stewartmiles**
Fix TF Lite Windows build.

* TF Lite was failing to compile on Windows as math constants like
  `_M_PI` were used but `_USE_MATH_DEFINES` was not defined. This
  adds the definition `_USE_MATH_DEFINES` to the `tensorflow-lite`
  target on Windows.
* Also, fixed use of C99 / C++20 in
  `lite/delegates/external/external_delegate.cc`.

Fixes #55745

### CODE REVIEW

**Comment by stewartmiles** [comment]
Hi, it has been a couple of weeks any progress on reviewing this?

**Comment by gbaned** [comment]
Hi @JunyoungLim Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @stewartmiles Can you please resolve conflicts? Thank you!

**Comment by stewartmiles** [comment]
Happy to as long as I get a quick review :) I'll do this now.

**Comment by stewartmiles** [comment]
@gbaned or @JunyoungLim any chance someone could take a look at this? It's a tiny PR.

**Comment by stewartmiles** [comment]
Hi, just checking in again. This pull was opened in April, I'm a Xoogler so I can be trusted (kinda), it's tiny .. can someone take a look?

**Comment by gbaned** [comment]
Hi @stewartmiles, Sorry for the delay. Can you please resolve conflicts? Thank you!

**Comment by stewartmiles** [comment]
@gbaned conflicts resolved.

**Comment by stewartmiles** [comment]
At a glance the AMD ROCm build looks nothing to do with this patch, looks like an issue with the bazel / blaze config:

```
ERROR: An error occurred during the fetch of repository 'local_config_rocm':

   Traceback (most recent call last):

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 869, column 38, in _rocm_autoconf_impl

		_create_local_rocm_repository(repository_ctx)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 547, column 35, in _create_local_rocm_repository

		rocm_config = _get_rocm_config(repository_ctx, bash_bin, find_rocm_config_script)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 395, column 30, in _get_rocm_config

		config = find_rocm_config(repository_ctx, find_rocm_config_script)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 373, column 41, in find_rocm_config

		exec_result = _exec_find_rocm_config(repository_ctx, script_path)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 369, column 19, in _exec_find_rocm_config

		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])

	File "/workspace/third_party/remote_config/common.bzl", line 230, column 13, in execute

		fail(
```

**Comment by stewartmiles** [comment]
Still waiting for a review ... 😒

**Review by JunyoungLim — APPROVED** [review]
Hi Stewart, thank you for the fix, and sorry for a long delay in review.. The code change looks good to me.

Please merge when all the checks pass.

**Comment by stewartmiles** [comment]
@JunyoungLim as I mentioned before the failing presubmits are not related to this commit.

AMD ROCm is failing due to a missing TensorFlow runtime archive:
```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/d08733f7ecc1e3ed5d75655fe47671b392f5b3a4.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

Loading: 0 packages loaded

Loading: 0 packages loaded

Loading: 0 packages loaded

Loading: 0 packages loaded

Loading: 0 packages loaded

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/2c3ca3b684bb2b188d977d47548e79dc559fb8ad.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

Loading: 0 packages loaded

INFO: Repository local_config_rocm instantiated at:

  /workspace/WORKSPACE:15:14: in <toplevel>

  /workspace/tensorflow/workspace2.bzl:878:19: in workspace

  /workspace/tensorflow/workspace2.bzl:97:19: in _tf_toolchains

Repository rule rocm_configure defined at:

  /workspace/third_party/gpus/rocm_configure.bzl:888:33: in <toplevel>

ERROR: An error occurred during the fetch of repository 'local_config_rocm':

   Traceback (most recent call last):

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 869, column 38, in _rocm_autoconf_impl

		_create_local_rocm_repository(repository_ctx)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 547, column 35, in _create_local_rocm_repository

		rocm_config = _get_rocm_config(repository_ctx, bash_bin, find_rocm_config_script)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 395, column 30, in _get_rocm_config

		config = find_rocm_config(repository_ctx, find_rocm_config_script)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 373, column 41, in find_rocm_config

		exec_result = _exec_find_rocm_config(repository_ctx, script_path)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 369, column 19, in _exec_find_rocm_config

		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])

	File "/workspace/third_party/remote_config/common.bzl", line 230, column 13, in execute

		fail(

Error in fail: Repository command failed

ERROR: Specified ROCM_PATH "/opt/rocm-5.2.0" does not exist

ERROR: /workspace/WORKSPACE:15:14: fetching rocm_configure rule //external:local_config_rocm: Traceback (most recent call last):

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 869, column 38, in _rocm_autoconf_impl

		_create_local_rocm_repository(repository_ctx)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 547, column 35, in _create_local_rocm_repository

		rocm_config = _get_rocm_config(repository_ctx, bash_bin, find_rocm_config_script)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 395, column 30, in _get_rocm_config

		config = find_rocm_config(repository_ctx, find_rocm_config_script)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 373, column 41, in find_rocm_config

		exec_result = _exec_find_rocm_config(repository_ctx, script_path)

	File "/workspace/third_party/gpus/rocm_configure.bzl", line 369, column 19, in _exec_find_rocm_config

		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])

	File "/workspace/third_party/remote_config/common.bzl", line 230, column 13, in execute

		fail(

Error in fail: Repository command failed

ERROR: Specified ROCM_PATH "/opt/rocm-5.2.0" does not exist

ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_rocm//rocm': Repository command failed

ERROR: Specified ROCM_PATH "/opt/rocm-5.2.0" does not exist

WARNING: Target pattern parsing failed.

ERROR: no such package '@local_config_rocm//rocm': Repository command failed

ERROR: Specified ROCM_PATH "/opt/rocm-5.2.0" does not exist
```

**Comment by JunyoungLim** [comment]
Seems like ROCm version error. I will get back to this once the issue is resolved.

**Comment by JunyoungLim** [comment]
Sent an internal patch to upgrade the ROCm version. Hopefully this will fix the issue. Once it gets approved, I will LYK.

**Comment by stewartmiles** [comment]
Thanks @JunyoungLim ! BTW it looks like "Code Check - Changed Files" and "Py+CPP Test Suite - Ubuntu CPU, Python 3.9" have been stuck in a queue for hours.

**Comment by JunyoungLim** [comment]
Hi Stewart, I just checked that AMD ROCm error has been happening in other PRs as well. Although we might need to fix this eventually, for now the ROCm check failure is not blocking the PR to be submitted.

To unblock this PR, can you try pushing an empty commit to this PR so that we can re-trigger the builds in CI?

https://stackoverflow.com/a/58190576/6096472

**Comment by stewartmiles** [comment]
Just rebased and pushed an empty commit as requested.

**Comment by stewartmiles** [comment]
@JunyoungLim I'm now back to waiting on "Code Check - Changed Files" and "Py+CPP Test Suite - Ubuntu CPU, Python 3.9" to run but they look like they're hung. Is it possible those other two workflows depend upon AMD ROCm completing successfully?

**Comment by stewartmiles** [comment]
@gbaned @JunyoungLim any update on getting these workflows working or perhaps pushing on my behalf without the presubmit?

**Comment by JunyoungLim** [comment]
This AMD ROCm build failure and "Waiting for status to be reported" blockers seem to be ubiquitous across all the PRs at the moment. I will try it internally if it works.

**Comment by JunyoungLim** [comment]
I submitted this change internally to bypass all the GitHub CI checks. There doesn't seem to be any issue.
Once the internal change gets synced with the GitHub repo, could you try pulling it?
We can close this PR and issue after confirming that it works.

**Comment by stewartmiles** [comment]
@JunyoungLim sounds great, what's the internal change message so that I can poll the repo to see when it appears?

**Comment by stewartmiles** [comment]
Oh cool, you merged it for me in https://github.com/tensorflow/tensorflow/commit/b00661ef3be7aeae01b524b17ecedbc9efbd46b5 much appreciated!

**Comment by JunyoungLim** [comment]
Hi Stewart, the post submit check has some failures in MacOS, so the change got reverted. I will take a look at what's causing this issue.

**Comment by JunyoungLim** [comment]
The breakage is fixed, and the change is re-submitted. Hope it works now :)

**Comment by stewartmiles** [comment]
@JunyoungLim cool thanks again!

**Pull request closed without merging**
