### PR TITLE
Cherry-pick updated TensorRT instructions.

### PR DESCRIPTION
**Pull request by MarkDaoust**
```
git cherry-pick  786668c
```

* updated installation instructions for Tensowflow-TensorRT integration

* Minor format changes to clean it up.

* Adding the python symlink command for devel packages too.

* Forcing the symlink creation.

* Updating the sed command for docker parameterized build.

### CODE REVIEW

**Comment by MarkDaoust** [comment]
The cherry-pick kept the original author. The bot wants a response from @jjsjann123.

**Comment by jjsjann123** [comment]
Looks like there's an issue with CLA here.
@cliffwooley Do we want the same doc update to go into r1.8?

**Comment by cliffwoolley** [comment]
It should be the same for 1.8, yes.  Thanks!

**Comment by jjsjann123** [comment]
My comment does not seem to work :(
I do have CLA under my jiej@nvidia.com (associated with this account). Feel free to instruct on how to proceed.

**Comment by MarkDaoust** [comment]
Looks like I can fix it manually.
@tfboyd can you review?

**Comment by tfboyd** [comment]
I will hit it up tonight just to be sure.  Need to run but wanted let let everyone know we are still moving forward :-)

**Review by tfboyd — APPROVED** [review]

**Comment by MarkDaoust** [comment]
Hey Amit, Can you help us get this cherry-pick merged?

**Comment by av8ramit** [comment]
cmake build is unrelated to .md changes.

**Pull request merged**
