### PR TITLE
Branch 164739939

### PR DESCRIPTION
**Pull request by rmlarsen**

### CODE REVIEW

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Review by av8ramit — APPROVED** [review]

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
This passed earlier with only known flakes failing. I'll merge this to fix flaky macOS test.

**Pull request merged**
