### PR TITLE
[WIP] Load CUDA libraries dynamically

### LINKED ISSUE #16184: Tensorflow and libcuda.so.1
Tensorflow 1.4.1
OS:  CentOS 6/7  (we use customized gcc 4.9.2 build for CentOS 6)

We have a number of computational servers.  Some are with GPU but some are not.  For the ease of maintenance, we build tensorflow from source code (bazel build) and install the modules under
/usr/local/... that all computational servers mount to the same /usr/local by means of NFS.

In the past (Tensorflow 1.0.0), the module could be built without linking with libcuda.so.1.  When a computational server without GPU runs tensorflow, it could run as CPU mode without problems.  When the computational server with GPU runs tensorflow, it could detect the GPU and load up libcuda.so.1 (and libcudart.so and libcudnn.so) by using dso_loader.  This works great for supporting both GPU and non-GPU servers while sharing the same module.

But I think that since 1.2.1 (at least, still 1.4.1), it seems that linking libcuda.so.1 is mandatory.  This is bad when non-GPU server would fail loading the module (missing libcuda.so.1), unless we explicitly putting libcuda.so.1 under /usr/lib64 (but this is a non-GPU server...!).  

Wonder if it is possible to make use of the old method of dso_loader instead of linking libcuda.so.1 for bazel building.  Thanks.

### PR DESCRIPTION
**Pull request by superbobry**
Prior to this commit, TensorFlow was built in two flavours: CPU-only and CPU/GPU. The latter version was dynamically linked with CUDA and therefore required CUDA libraries to be installed in the host system. This change replaces dynamic linking with dynamic loading for all of the CUDA libraries but cudart. This would allow to ship a single TensorFlow build which works for both cases.

Note that TensorFlow already used dynamic loading for CUDA libraries prior to version 1.1.0. In 1.1.0 however, dynamic loading has been changed to dynamic linking, see commit 191658d54f90ac03c15b339326129cd52d1f56a3.

Closes #16184

### CODE REVIEW

**Comment by superbobry** [comment]
@gunan a few questions to drop the [WIP] status:

* Are you OK with having the same copy-pasted shim in both cuda_driver.cc and gpu_cudamalloc_allocator.cc? As an alternative, I can make gpu_cudamalloc_allocator use  cuda_driver, or extract the wrappers into a separate file.
* What would be the best way to eliminate the remaining dependency on cudart? The usages are scattered through multiple subsystems, so the local shim trick does not apply. I could create a wrapper in a separate file, e.g. (common_runtime/gpu/gpu_cudart.*) and change the usages to call the wrapped functions.
* Ideally, I'd like to ensure that if CUDA is not available, one cannot register a GPU device. Could you point me to the part of the code responsible for that?

**Comment by jlebar** [comment]
cc @Artem-B

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by superbobry** [comment]
@caisq it is, since it does not remove CUDA libraries entirely (see questions in the comment above). I got some of the answers from @Artem-B over email a couple of weeks ago, but did not have time to revisit the PR since.

**Comment by yifeif** [comment]
I tried up-streaming this change to head, but now I'm getting errors `libtensorflow_framework.so: undefined reference to `cuOccupancyMaxPotentialBlockSize'`. Any idea what else might have changed at head?

**Comment by yifeif** [comment]
Looks like #21958 added the usage of symbol cuOccupancyMaxPotentialBlockSize, thanks to @gunan's detective work.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by pkit** [comment]
@gunan @yifeif fixed all your grievances here #24860, let's do it

**Comment by jlebar** [comment]
This needs a StreamExecutor owner to review -- probably @timshen91.  It also needs @Artem-B's sign-off.

**Comment by yifeif** [comment]
Closing this as the corresponding changes have been submitted. Thanks @superbobry!

**Pull request closed without merging**
