### PR TITLE
change from deprecated version to a new version

### PR DESCRIPTION
**Pull request by Jekyll-SONG**

### CODE REVIEW

**Comment by Jekyll-SONG** [comment]
Singed

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by MarkDaoust — APPROVED** [review]
LGTM

**Comment by rmlarsen** [comment]
@MarkDaoust Thanks for the review!

**Comment by martinwicke** [comment]
Failing test is unrelated.

**Pull request merged**
