### PR TITLE
Speeds up the bidirectional RNN by providing the sequence length to e…

### PR DESCRIPTION
**Pull request by kentonl**
…ach RNN. Also fixes shape inference when using the sequence length.

Change-Id: Ib2843c620bc4bd348aafb2d676b61fa35f1223af

### CODE REVIEW

**Comment by ebrevdo** [comment]
Thank you for the contribution!  What are your sequence length
distributions like and how much speedup to you get from this change?

**Comment by kentonl** [comment]
These are Penn Treebank sentences. With batches of 32 sentences, I'm seeing about 30% improvement in throughput during training.

**Comment by ebrevdo** [comment]
Great to hear!  I was afraid of pushing this exact change because I wasn't
confident the conditional flow control would improve performance
everywhere.  Is this on CPU or GPU?

**Comment by ebrevdo** [comment]
LGTM.

**Comment by vrv** [comment]
@tensorflow-jenkins, test this please.

**Comment by kentonl** [comment]
I was reporting speedups on CPUs. On GPUs, the speedup is less significant (about 5%).

**Comment by vrv** [comment]
Looks like a CPU test failed:

INFO: From Testing //tensorflow/python:rnn_test:
==================== Test output for //tensorflow/python:rnn_test:
F................
======================================================================
FAIL: testBidirectionalRNN (__main__.BidirectionalRNNTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/rnn_test.runfiles/tensorflow/python/kernel_tests/rnn_test.py", line 579, in testBidirectionalRNN
    self._testBidirectionalRNN(use_gpu=False)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/rnn_test.runfiles/tensorflow/python/kernel_tests/rnn_test.py", line 539, in _testBidirectionalRNN
    self.assertEqual(out.get_shape().as_list(), [batch_size, 2 * num_units])
AssertionError: Lists differ: [None, 6] != [2, 6]

First differing element 0:
None
2

- [None, 6]
+ [2, 6]

----------------------------------------------------------------------
Ran 17 tests in 23.687s

FAILED (failures=1)

@kentonl: can you take a look and fix?

**Comment by ebrevdo** [comment]
Actually, could you also add a version of the bidirectional RNN test when
sequence_length is not passed in (thus all sequences are considered full
length)?

**Comment by ebrevdo** [comment]
(btw you can infer the batch size by calling inputs.shape, checking if not
None, and getting the first dimension from the input)

**Comment by kentonl** [comment]
Thanks for the pointers. The bug fix and additional test are in the latest revision.

**Comment by vrv** [comment]
Thanks, can you squash the commits?

**Comment by ebrevdo** [comment]
These lines can fail because get_shape() will sometimes return None (e.g.
if using a Placeholder with no shape!)

output.set_shape([input_.get_shape()[0], self.output_size])

**Comment by ebrevdo** [comment]
Sorry - not none, but a TensorShape with no dimensions.  the __getitem__
will fail.

**Comment by kentonl** [comment]
It looks like TensorShape's `__getitem__` is ok to call with no dimensions (see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/tensor_shape.py#L507). I added a test that uses a shapeless placeholder to be sure.

Note that the extra logic here: https://github.com/kentonl/tensorflow/commit/04036d7e443da373cc151305ba81ffacafe85d13#diff-9d717423e6d3f4359151c45dfaa554b6R234 is required for shapeless placeholders to work correctly for bidirectional RNNs.

**Comment by ebrevdo** [comment]
A cleaner way would be to move the shape check to the top (before anything
happens) and do:

for input in inputs:
  input.set_shape(input.shape.with_rank(2))

But it does indeed seem that this is not necessary.

**Comment by kentonl** [comment]
I switched to `with_rank` for the shape checking. Looking cleaner now, thanks!

This is necessary because of this shape check in the `reverse_sequence` op: https://github.com/tensorflow/tensorflow/blob/d1b8333effdcb031e6e34a2835a2f1c877fdd79b/tensorflow/python/ops/array_ops.py#L1014. We can't promote the input to rank 2 there, because `tf.reverse_sequence` does not make assumptions about the exact rank of the input.

**Comment by kentonl** [comment]
It looks like setting the shape in the RNN is actually not the right fix. When the gradients are computed, the shape inference still fails due to the conservative logic in the `merge` op here:  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/control_flow_ops.py#L1533. Would it be acceptable to relax it so that merging tensors with shapes, for example, `[None, 10]` and `[None, 10]` would produce a `[None, 10]` tensor?

**Comment by ebrevdo** [comment]
I'd be OK with this.

**Comment by kentonl** [comment]
The latest version fixes the above issues with stronger shape inference for the merge op.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please.

**Comment by kentonl** [comment]
The merge op shape inference is now more conservative and fixes problems mentioned before.

**Comment by vrv** [comment]
@tensorflow-jenkins, test this please

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Pull request closed without merging**
