### PR TITLE
Create pylint-presubmit.yml

### PR DESCRIPTION
**Pull request by angerson**
This is a non-blocking check that runs `pylint` if a PR changes Python files. It's based on the [TensorFlow code style guide](https://www.tensorflow.org/community/contribute/code_style) instructions for running Pylint.

This should be a more useful result than the `ci_sanity` Pylint job, since it's consistent. I don't think we can really know if it aligns exactly with the internal pylint, since the configuration is different: while we look into that, this should be a useful check for users.

### CODE REVIEW

**Comment by angerson** [comment]
I'm having trouble getting this to run so that:

- If there are no changed Python files, succeed.
- If there are changed Python files, run pylint.

Just getting stuck on bash.

**Comment by bhack** [comment]
This is nice, I have just an extra idea.
As we have already `pylint` and `clang-format` pre-commit hooks in https://github.com/tensorflow/tensorflow/pull/48371 can we use the docker image that we publish for contributors and developers in this Action?

So we are quite sure to be aligned between the git action we run here and the local linting that the developer run locally in the environment that we distribute.

**Comment by angerson** [comment]
> As we have already pylint and clang-format pre-commit hooks in #48371 can we use the docker image that we publish for contributors and developers in this Action?

I think it'll be good to synchronize the environment when the newer Docker images are available.

**Comment by angerson** [comment]
I mean the upstream ones, yes. I don't want to integrate the `devel` containers while working on those other new containers.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by bhack** [comment]
> I mean the upstream ones, yes. I don't want to integrate the `devel` containers while working on those other new containers.

If we have enought resource for the new containers ok we could cherry pick the pre-commit hooks in my PR and push in your images instead of the official devel.

**Comment by bhack** [comment]
Just for the record:
We already have a Github Action for pylint in model garden https://github.com/tensorflow/models/blob/master/.github/workflows/ci.yml

**Pull request merged**
