### PR TITLE
[T.F 2.0 API Docs] Adding to the documentation of tf.math.acos and tf.math.add functions

### PR DESCRIPTION
**Pull request by Harsh188**
PR for issue #25802. 

This PR is similar to #26017 and #25802. However, neither of them were merged.

I have attempted to add improvements to the documentation for `tf.math.acos` as well as `tf.math.add`. 
This is my first contribution so please do help me identify and fix any errors I might have made.

Thank you

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
The `base_api` documentation is available cross language bindings. Python examples should be inserted in Python documentation only, using testable docstrings to ensure that the examples stay in line with code changes.

https://www.tensorflow.org/community/contribute/docs_ref

**Comment by mihaimaruseac** [comment]
See 8582a58 for how to expose to Python and add documentation there, as an example

**Comment by Harsh188** [comment]
> The `base_api` documentation is available cross language bindings. Python examples should be inserted in Python documentation only, using testable docstrings to ensure that the examples stay in line with code changes.
> 
> https://www.tensorflow.org/community/contribute/docs_ref

Whoops, I saw your comment on #25802 however I didn't quite understand the significance of the issue. Thank you for clarifying once again.
I will be removing the python examples from the `base_api` documentation and resubmit for review. I will then open another PR to add documentation to `python/ops/math_ops.py`.

**Comment by Harsh188** [comment]
Pinging @mihaimaruseac for review. 
I'm assuming that along with adding examples to `python/ops/math_ops.py`, I will similarly have to do the same to `core/ops/math_ops.cc`.

**Comment by Harsh188** [comment]
Created a PR #42619 to address changes to the python documentation.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
