### PR TITLE
BatchMatrixInverse deprecation notice

### PR DESCRIPTION
**Pull request by Pey-crypto**
- BatchMatrixInverse has been depreciated in Tensorflow 2.16 but, the documentation for it is still live on the online documentation.
- This PR aims to push changes to the online documentation.

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
It doesn't look like the operation has been deprecated

**Comment by Pey-crypto** [comment]
`FAILED install/tests/layer_tests/tensorflow_tests/test_tf_BatchMatrixInverse.py::TestBatchMatrixInverse::test_batch_matrix_inverse_basic[ ie_device:CPU - precision:FP16 - adjoint:False - input_type:<class 'numpy.float32'> - input_shape:[2, 3, 3] ] - NotImplementedError: Op BatchMatrixInverse is not available in GraphDef version 1645. It has been removed in version 13. Use MatrixInverse instead.. `

**Comment by mihaimaruseac** [comment]
Thanks. I only checked the release notes.

I still see https://github.com/tensorflow/tensorflow/blob/614104555a559753ddd0f3d9beaffc3d3cdc6fc3/tensorflow/core/kernels/linalg/matrix_inverse_op.cc#L333-L336

This file has not changed in a year. And there is also https://github.com/tensorflow/tensorflow/blob/614104555a559753ddd0f3d9beaffc3d3cdc6fc3/tensorflow/core/ops/linalg_ops.cc#L595-L601

That deprecation notice there for version 13 is several years old, so not from TF 2.16

**Comment by Pey-crypto** [comment]
But since this function cannot be invoked presently, is it possible to update the online documentation to show that the function cannot be used in the current version, would be really helpful for everyone. [https://www.tensorflow.org/api_docs/python/tf/raw_ops/BatchMatrixInverse](https://www.tensorflow.org/api_docs/python/tf/raw_ops/BatchMatrixInverse)

**Comment by mihaimaruseac** [comment]
Sure, I'll open this PR so we can test it, but I'm not 100% sure this is the way forward.

The raw ops are supposed to work for any language binding of TF, adding the deprecation note here might break something.

But, if this works, we should then do the same for the other similarly deprecated ops.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by Pey-crypto** [comment]
From my brief understanding, the changes to this files will affect the internal API definition. I think the team has to then manually generate the documentation based on the internal API definition.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Oh, the fact that the proto doesn't have a deprecation field is maybe why this has not be done at this level.

**Comment by Pey-crypto** [comment]
i figured maybe they might use the api_defs during doc generation, might make its way into the online documentation

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
