### PR TITLE
Improve ROCm's sqrt and rsqrt for std::complex.

### PR DESCRIPTION
**Pull request by chsigg**
Follow up from here: https://github.com/tensorflow/tensorflow/pull/41259/files#r452825851

### CODE REVIEW

**Comment by deven-amd** [comment]
m running this change on ROCm CI ... see following PR
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1043

will update this PR once the run is complete

**Comment by ekuznetsov139** [comment]
In what way is this an improvement? It is likely slower than before (more branches in impl_sqrt, more calls to sqrt and impl_sqrt). Can't tell if the accuracy is better. It may break unit tests if there is any loss of accuracy. Let's wait for CI results.
As a general note, no need to use impl_ prefixes when calling on float and double,
impl_rsqrt(norm(x))
should just be
rsqrt(norm(x))

**Comment by deven-amd** [comment]
all regressions passed

**Comment by chsigg** [comment]
Sorry, my description should have been clearer.

This change adds handling of catastrophic cancellations to impl_sqrt.

And the handling of catastrophic cancellations should be faster and work for half's as well.

Does that make sense?

**Comment by ekuznetsov139** [comment]
According to my tests, "old" impl_sqrt produces NaNs with inputs below the magnitude of ~10^-20. Your "new" impl_sqrt only starts to fail at 10^-23. Outside the extreme range, the two solutions have comparable accuracy levels, the new impl_sqrt is somewhat better and has a lower maximum relative error, the new impl_rsqrt is slightly worse.

Do we care about half? There's no support for complex<half> anywhere in the code that I can see.

This approximation
return T(0.5) * fabs(b) * impl_rsqrt(r);

seems to be a bit off. To the lowest order in |v/r|, the correct value is 

0.5 |b|/sqrt(|v|) (1 - 1/8 |v/r|^2)

and the formula above reduces to 

0.5 |b|/sqrt(|v|) (1 - 1/4 |v/r|^2)

Which does not matter for float, where, as long as |v/r| is less than 1e-5, the quantity in the brackets is exactly 1 either way, but it matters for double. (And even for float, the correct formula would allow one to raise the threshold and result in lower errors.)

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg  This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@chsigg This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
Hi @chsigg This PR is in draft, any update on this? Please. Thank you!

**Comment by gbaned** [comment]
Hi @chsigg This PR is in draft, any update on this? Please. Thank you!

**Comment by gbaned** [comment]
Hi @chsigg This PR is in draft, any update on this? Please. Thank you!

**Comment by gbaned** [comment]
Hi @chsigg This PR is in draft, any update on this? Please. Thank you!

**Comment by mihaimaruseac** [comment]
Closing stale PR

**Pull request closed without merging**
