### PR TITLE
Add complex128 dtype

### LINKED ISSUE #1420: Support for double precision complex numbers
I'd like to use TensorFlow to write an application that would need `complex128` as a dtype.
But TensorFlow currently only supports `complex64`.
Are there any plans for supporting `complex128` as well in the future?

Seems that there is a TODO for this in  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/types.proto#L36.

### PR DESCRIPTION
**Pull request by ibab**
I've started implementing support for `complex128` in order to fix #1420.
This commit contains all changes necessary to create and run `complex128` variables.

If this is okay so far, I'll add tests, change the documentation and enable `complex128` for all ops that are already using `complex64` (and add the corresponding tests).

The only change I wasn't sure about is whether it was okay to rename the `TF_COMPLEX` enum entry to `TF_COMPLEX64` at https://github.com/tensorflow/tensorflow/blob/97f585d506cccc57dc98f234f4d5fcd824dd3c03/tensorflow/core/public/tensor_c_api.h#L81, as this is not backwards-compatible with external source code that uses the C API.
Should I change the entry back to `TF_COMPLEX`?

### CODE REVIEW

**Comment by girving** [comment]
@ibab: Taking a look now.  As for `TF_COMPLEX`, let's have both `TF_COMPLEX` and `TF_COMPLEX64` with the same enum value (https://stackoverflow.com/questions/11412516/enum-why-can-two-different-enumeration-constants-have-the-same-integer-value).

**Comment by girving** [comment]
Looks great, thank you for the contribution!  Just those couple style comments on the Python code.  This is by far the least number of comments I've wanted to make on a TensorFlow PR so far. :)

It's good to keep the commits separate while you're working on it, and once everything is in place we can squash them into a single test-passing commit.

**Comment by ibab** [comment]
Okay, thanks for the comments!
I'll implement them and proceed with converting the existing kernels.

**Comment by girving** [comment]
@ibab: Actually, let's hold the kernel updates to a separate PR.  Adding just the dtype and associated framework support is a nice standalone step.

**Comment by ibab** [comment]
Okay, I've added the style changes.
I've fixed the problem with `scomplex` and `dcomplex` earlier today in https://github.com/tensorflow/tensorflow/commit/03422935b98145f5b1060198e1f7274b665ddd87

**Comment by girving** [comment]
Awesome, looks good to me.  @martinwicke: Can we run this through the tests?  Is it better to smash into a single commit before or after testing?

**Comment by girving** [comment]
Jenkins, test this please.

**Comment by girving** [comment]
@josh11b: Looks like this PR requires the backwards compatibility test to run to make it work (unsurprising since there's a new numeric type).  Is the update script in open source yet?

**Comment by ibab** [comment]
@girving: I can run `./bazel-out/local_linux-py3-opt/bin/tensorflow/core/ops/compat/update_ops`.
I thought that I didn't need to do it, as I hadn't changed any ops (But some of them seem to automatically use all available types).
It didn't show up in my tests, as I had used it after I modified some kernels. Sorry for that. I'll push the remaining files in a second.

**Comment by ibab** [comment]
Can someone ask travis to re-run the tests, to see if they now pass? Thanks!

**Comment by yaroslavvb** [comment]
Jenkins, test this please.

**Comment by josh11b** [comment]
The backwards compatibility test has recently been moved to open-source, along with the update_ops script.

**Comment by ibab** [comment]
@josh11b: Thanks! If the script hasn't changed, then my updated `ops.pbtxt` should be fine, though, right?

It seems that @yaroslavvb is not a `tensorflow member` and Jenkins won't listen to him :disappointed:

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please.

**Comment by ibab** [comment]
The Python 3 test failures seem to be pre-existing ones not caused by this PR.
Maybe @girving would be interested in merging this now?

**Comment by girving** [comment]
Excellent!  I'll take another quick look and then merge.

**Comment by girving** [comment]
@ibab: Unfortunately the backwards compatibility test files have been changed since your update, so the test fails again for me when I try to merge.  Can you merge, regenerate those files, and then squash into one commit?  There's a bit of an unfortunate race condition here.

Incidentally, in a future commit we should add a note to `RELEASE.md` saying TensorFlow has complex64 support now. :)

**Comment by girving** [comment]
I'll relaunch tests ASAP when you do that and try to get it in as quickly as I can.  Large refactoring changes can be tricky to sneak into an atomic system.

**Comment by ibab** [comment]
Okay, I'll remove the updated ops history file, rebase on master, rebuild the ops file and squash all commits.

**Comment by ibab** [comment]
Okay, I've updated the PR. Tests are passing on my side.

**Comment by girving** [comment]
Trying merge now...

**Comment by girving** [comment]
Jenkins, test this please.

**Comment by girving** [comment]
Jenkins, test this please.  (The first time failed for some infrastructure reason)

**Comment by girving** [comment]
@martinwicke: The infrastructure failure persists.  Ideas?

@ibab: Do you mind if I pull this in and commit it myself (crediting you explicitly of course)?  Looks like our Jenkins setup is experiencing some issues, and I'd like to get this before the compatibility test bit rots again.

**Comment by ibab** [comment]
Yeah, that's fine with me. It would be nice if you could keep the author field of the original commit.

**Comment by girving** [comment]
Excellent, looks like the infrastructure failure has passed.  Back to the normal merging process.

**Comment by ibab** [comment]
Cheers :tada:

**Comment by girving** [comment]
Thank for the contribution!

**Pull request merged**
