### PR TITLE
Update CocoaPods specs: added swift_version(5.0)

### PR DESCRIPTION
**Pull request by ryan-cha**
Hello, I'd like to submit a PR. 

* What's changed: Added a configuration, `swift_version`,  to the Cocoapod **podspec** [file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/swift/TensorFlowLiteSwift.podspec)

  - The version, `5.0`, came from the xcode project settings within the [docsgen](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/swift/docsgen/TensorFlowLiteSwift/TensorFlowLiteSwift.xcodeproj) folder.

* Purpose: To fix issues in integrating this pod.
Especially when using `pod package mylib.podspec` where `mylib` has a dependency on [TensorFlowLiteSwift(2.9.1)](https://cocoapods.org/pods/TensorFlowLiteSwift).

```sh
$ pod package mylib.podspec 

Installing TensorFlowLiteC (2.9.1)
Installing TensorFlowLiteSwift (2.9.1)
[!] Unable to determine Swift version for the following pods:

- `TensorFlowLiteSwift` does not specify a Swift version and none of the targets (`packager`) 
integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or 
set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

Below is the podspec file used with the command above.
```podspec
Pod::Spec.new do |s|
  s.name             = 'mylib'
  s.version          = '0.1.0'
  s.summary          = 'A short description of mylib.'
  s.description      = <<-DESC
TODO: Add long description of the pod here.
                       DESC
  s.homepage         = 'https://github.com/myhomepage'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'myname' => 'myemail' }
  s.source           = { :http => 'myurl' }
  s.ios.deployment_target = '12.0'
  s.static_framework = true
  s.source_files = 'mylib/Classes/**/*'
  s.dependency 'TensorFlowLiteSwift', '~> 2.9.1'
  s.dependency 'TensorFlowLiteSwift/CoreML', '~> 2.9.1'
  s.dependency 'TensorFlowLiteSwift/Metal', '~> 2.9.1'
  s.script_phases = [
          {
              :name => 'Download Tflite models',
              :execution_position => :before_compile,
              :shell_path => '/bin/sh',
              :script => '/bin/sh "$SRCROOT/../../RunScripts/download_models.sh"'
          }
      ]
end                    

```

### CODE REVIEW

**Comment by KulykVolodymyr** [comment]
@ryan-cha how does it going with merge?

**Comment by ryan-cha** [comment]
> how does it going with merge?

@vol-kulyk Not quite sure about the unsuccessful checks, but I'm still waiting for the review. 🤷‍♂️

**Comment by gbaned** [comment]
Hi @terryheo Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @terryheo Can you please review this PR ? Thank you!

**Pull request closed without merging**
