### PR TITLE
Fix concat optimization infinite loop

### PR DESCRIPTION
**Pull request by drasmuss**
This is a fix for the issue identified in https://github.com/tensorflow/tensorflow/issues/23383

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by harshini-gadige** [comment]
@skye  -  PTAL

**Comment by skye** [comment]
@ezhulenev are you the right person to review this?

**Comment by ezhulenev** [comment]
Yes, I'll take a look later today or tomorrow

**Comment by harshini-gadige** [comment]
> Yes, I'll take a look later today or tomorrow

Thank you !

**Review by ezhulenev — DISMISSED** [review]

**Comment by harshini-gadige** [comment]
@drasmuss  Please address the failures. Thanks !

**Comment by drasmuss** [comment]
I fixed the one formatting error that I could see.  The other failures don't give any indication as to the cause (e.g., I can't see the build log), but I rebased this branch onto the latest `master` as well, in case that helps.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ezhulenev: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by hgadig** [comment]
@ezhulenev  Request you to take a look and approve this PR. Thanks !

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ezhulenev, @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ezhulenev, @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ezhulenev, @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ezhulenev, @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ezhulenev, @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

**Comment by gbaned** [comment]
@ezhulenev Could you please review and approve this PR? Thanks !

**Review by ezhulenev — APPROVED** [review]

**Pull request merged**
