### PR TITLE
Fix incorrect values in recorded_allocation on BE machines

### PR DESCRIPTION
**Pull request by kun-lu20**
This PR addresses incorrect `count` and `requested_bytes` values in `recorded_allocation` when testing model allocations.

Test case `//tensorflow/lite/micro:recording_micro_allocator_test` fails on Big-Endian systems because `RecordingSimpleMemoryAllocator::AllocateFromTail()` would be called one more time and the `alloc_count_` and `requested_tail_bytes_` fields would be added repeatedly.

`FlatBufferVectorToTfLiteTypeArray()` function in `micro_allocated.cc` has been modified to fix this by invoking the base class version of `AllocateFromTail()` function (`allocator->SimpleMemoryAllocator::AllocateFromTail()`) on BE machines, rather than the derived class version (`allocator->AllocateFromTail()`) which might update the value of `alloc_count_` and `requested_tail_bytes_ fields` besides allocating the space. 

This PR will solve the issue #45455.

### CODE REVIEW

**Comment by kun-lu20** [comment]
Hi @advaitjain , could you please take a look at this PR? Thank you very much!

**Comment by gbaned** [comment]
@kun-lu20 Can you please resolve conflicts? Thanks!

**Comment by kun-lu20** [comment]
Hi @gbaned , I think the reason of conflicts is that the TF Lite Micro codebase has been moved out of TensorFlow repo. Should I move the code changes to the new TFLM repo? Thanks!

**Comment by advaitjain** [comment]
The change from this PR looks reasonable to me. Please create a PR in the [tflite-micro](https://www.github.com/tensorflow/tflite-micro) repo.

**Comment by kun-lu20** [comment]
@advaitjain Thanks! will do.

**Pull request closed without merging**
