### PR TITLE
fix a bug in AddSymbolicGradients

### LINKED ISSUE #37593: bug in C++ API "AddSymbolicGradients"
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes 
- OS Platform and Distribution: CentOS Linux 7.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: Unknown
- TensorFlow installed from (source or binary):source 
- TensorFlow version (use command below): TF 2.0
- Python version:3.7 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 8.3
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**
I build a graph, then call `AddSymbolicGradients` to generate gradients, but I found the order of generated gradients does not match inputs. My inputs are `[a,b]`, but the generated gradients are `[b_grad, a_grad]`
**Describe the expected behavior**
gradients order match inputs. Gradients of inputs `[a,b]` should be `[a_grad, b_grad]`

**My work to solve the problem** 
I checked the code in tensorflow/cc/framework/gradients.cc [L532](https://github.com/tensorflow/tensorflow/blob/07112a5c7e233989652ecac3184f0dd640e1462b/tensorflow/cc/framework/gradients.cc#L532) 
```c++
    size_t dx_index = 0;
    for (const Edge* e : n->in_edges()) {
      if (e->IsControlEdge()) continue;
      if (dx_index == dx.size()) {
        return errors::Internal(
            "Invalid gradient output index: ", dx_index, " size: ", dx.size());
      }
      TF_RETURN_IF_ERROR(
          BackpropAlongEdge(dx[dx_index++], {e->src(), e->src_output()}));
    }
```
I think `dx_index` in code should be `e->dst_input()`, because `in_edges() `returns a `unordered_set` which order is not match `dx`, the input index of edge is `dst_input()`.The right code may be:
```c++
for (const Edge* e : n->in_edges()) {
      if (e->IsControlEdge()) continue;
      int dx_index = e->dst_input();
      if (dx_index >= dx.size()) {
        return errors::Internal("Invalid gradient output index: ", dx_index, " size: ", dx.size());
      }
      TF_RETURN_IF_ERROR(BackpropAlongEdge(dx[dx_index], {e->src(), e->src_output()}));
    }
```

After I modified the code, my program seems works fine.

### PR DESCRIPTION
**Pull request by buaasun**
Fixes #37593

### CODE REVIEW

**Comment by gbaned** [comment]
@buaasun thank you for the contribution. Please sign CLA.

**Comment by buaasun** [comment]
@googlebot I signed it!

**Review by alextp — CHANGES_REQUESTED** [review]
This needs a unit test which fails without this change but passes with this change.

**Comment by buaasun** [comment]
@alextp updated.

**Review by alextp — APPROVED** [review]

**Pull request merged**
