### PR TITLE
Improve docs for `parallel_stack`

### LINKED ISSUE #10036: Document functional differences between tf.stack and tf.parallel_stack
What if `tf.stack` had the API:

```
tf.stack(
    values,
    axis=0,
    name='stack',
    algorithm='sequential'
)
```

Options for algorithm could be `sequential`, `parallel` to start. This could apply broadly to many ops and ops like `parallel_stack` could be deprecated. 

Any ideas for a better parameter name than `algorithm`?

### PR DESCRIPTION
**Pull request by Androbin**
For #10036

### CODE REVIEW

**Comment by ahundt** [comment]
Make the last sentence this:
> Unlike `stack`, `parallel_stack` does NOT support backpropagation.

**Comment by ahundt** [comment]
LGTM

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Review by girving — APPROVED** [review]

**Comment by martinwicke** [comment]
Just noticing -- is it intentional you made this change to the 1.2 branch? Could you put it on master?

That will mean that 1.2 docs won't contain the fix, but I'd rather not mess with the release this late.

**Comment by Androbin** [comment]
No, that was by mistake @martinwicke

**Comment by Androbin** [comment]
I'm sorry, I don't practice rebase that often...

**Pull request closed without merging**
