### PR TITLE
TFLu - refactor apollo3 magic wand

### PR DESCRIPTION
**Pull request by oclyke**
pertaining to #44737

testing status (manually verified by inspection):
board | magic_wand
------|-----------
sparkfun_edge | ✅
apollo3evb | 🤔

### CODE REVIEW

**Comment by gbaned** [comment]
@oclyke  Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@oclyke Any update on this PR? Please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
