### PR TITLE
Disable clang_format check.

### PR DESCRIPTION
**Pull request by yifeif**
Different clang_format version can cause different formats with the same style option. This check might be too strict. Disable for now.

### CODE REVIEW

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Review by gunan — APPROVED** [review]

**Comment by yifeif** [comment]
Thanks @gunan!

**Comment by yongtang** [comment]
@yifeif @gunan Thanks for the fix.

I didn't realize that different version's of clang-format renders different outputs. I will do some investigation and see if there are more reliable solutions for C++ style check.

Again,  thanks for the fix and sorry for the inconvenience caused by `clang_format`.

**Comment by yifeif** [comment]
No worries, and thanks for contributing @yongtang!

**Pull request merged**
