### PR TITLE
Added arg: name to tf.nn.swish

### LINKED ISSUE #40592: `tf.nn.swish` documentation refers `name` as an argument
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/nn/swish

### Clear description

In the "Args" section, there is an input ` name`, but it is not in the signature, and the function doesn't accept the argument.

Running code:

~~~python
tf.nn.swish(1, name=None)
~~~

got exception:

~~~python
TypeError: swish() got an unexpected keyword argument 'name'
~~~

### Parameters defined

Yes

### Returns defined

Yes

### Raises listed and defined

No

## System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.2.0-rc3
- **Python version**: 3.8.2

### PR DESCRIPTION
**Pull request by Patryk999**
Resolves #40592
Added name argument for tf.nn.swish and ops.name_scope, also updated docs to cover those changes.

### CODE REVIEW

**Comment by Patryk999** [comment]
@googlebot I fixed it

**Comment by Patryk999** [comment]
@googlebot I fixed it.

**Comment by Patryk999** [comment]
@googlebot I fixed it.

**Comment by Patryk999** [comment]
@googlebot I fixed it.

**Comment by Patryk999** [comment]
@googlebot I fixed it.

**Comment by Patryk999** [comment]
@googlebot I fixed it.

**Comment by Patryk999** [comment]
@googlebot I fixed it.

**Review by fchollet — COMMENTED** [review]
Thanks for the PR. However, Keras activations don't take a `name` argument.

**Pull request closed without merging**
