### PR TITLE
Fixed a typo error in subgraph.cc (First Pull Request)

### PR DESCRIPTION
**Pull request by captainhaddock18**
Fixed a typo error. Changed the spelling from "GetDelegateKernalName" to "GetDelegateKernelName"

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
You will need to also change all callers of this.

Also, in general we don't accept 1-letter PR fixes. The amount of CI that needs to run is a cost that does not justify it

**Comment by captainhaddock18** [comment]
> You will need to also change all callers of this.
> 
> Also, in general we don't accept 1-letter PR fixes. The amount of CI that needs to run is a cost that does not justify it

can you please tell me how to change all callers of this? how to locate the files where it has been called.

**Comment by mihaimaruseac** [comment]
grep, use IDE, use codesearch tools (github also has a search).

**Comment by gbaned** [comment]
Hi @captainhaddock18 Can you please sign CLA. Thank you!

**Pull request closed without merging**
