### PR TITLE
Unbundle LLVM

### PR DESCRIPTION
**Pull request by isuruf**
cc @perfinion, @timokau

### CODE REVIEW

**Comment by gunan** [comment]
@sanjoy could you take a look?
this PR tries to use system LLVM for TF.
One potential issue I see is, TF always uses cutting edge version for LLVM, so you can almost never use TF at head if you use system LLVM.

**Comment by isuruf** [comment]
> One potential issue I see is, TF always uses cutting edge version for LLVM, so you can almost never use TF at head if you use system LLVM.

This is not a huge issue for me as LLVM releases are fairly frequent (major release every 6 months), that I can wait a few months for a LLVM release to use it.

**Comment by gunan** [comment]
While I understand that this is not a problem for your use case, when it is checked in, everyone can use it for their own use case. And once it does not work, TF team will be receiving issues and support requests.
Therefore, I want XLA team's review on this.

**Comment by sanjoy** [comment]
XLA uses the C++ LLVM API which has **no** compatibility guarantees.  This plus the fact that internally google uses a monorepo means we have to live very close to LLVM head.

So this change is okay if it is clearly documented that the TF and XLA teams will not take (or create!) any PRs solely to make a non HEAD version of LLVM work with XLA.  I.e. I'm okay with this PR if it saves someone a fork, but we can't commit to keeping it working.

> This is not a huge issue for me as LLVM releases are fairly frequent (major release every 6 months), that I can wait a few months for a LLVM release to use it.

Can you elaborate a little bit on this?  Let's say XLA in TF head today gets adapted to an LLVM API change that made on 14 August.  Do you have a plan to deal with that?  That API change may have been reverted before the next release so we may not have *any* LLVM release that works with TF.

**Comment by isuruf** [comment]
> Do you have a plan to deal with that? That API change may have been reverted before the next release so we may not have any LLVM release that works with TF.

If that happens, then yes, we can't use system LLVM. Let me know what you decide.

**Comment by whchung** [comment]
Sorry for my interruption. I'm wondering could this PR be improved so it be enabled conditionally perhaps via a bazel configure-time option?

Working on XLA it's pretty important to closely follow LLVM tip, but I do see some good use cases where going back to system LLVM be beneficial to check interop with IRs coming from other frontends.

**Comment by isuruf** [comment]
> I'm wondering could this PR be improved so it be enabled conditionally perhaps via a bazel configure-time option?

It is there. `TF_SYSTEM_LIBS=llvm` for just `llvm` or `TF_SYSTEM_LIBS=llvm,png,and,other,libs`

**Comment by sanjoy** [comment]
> If that happens, then yes, we can't use system LLVM. Let me know what you decide.

Given that:

 - Using a system LLVM won't reliably work.
 - Gunan says (rightly I think) that even if we document this as "unsupported", in practice we will get bugs / PRs.

I think we should drop this PR.

**Comment by isuruf** [comment]
Thanks for the review.

**Pull request closed without merging**
