### PR TITLE
Add libtensorflow_cc.so to pip_package BUILD

### PR DESCRIPTION
**Pull request by efernandez**
This allows to run inference from C++ code if we link against the `libtensorflow_cc.so` library that will get installed under `/usr/local/lib/python2.7/dist-packages/tensorflow` by default. Otherwise, this library doesn't get installed there and there's no other way to run inference from C++ using Tensorflow AFAIK.

I've seen some issues related with this topic, but it's not clear to me what are the drawbacks of doing this, other than increasing the compile time for the additional target.

Sorry if I missed something and there's actually another way.

### CODE REVIEW

**Comment by perfinion** [comment]
I dont think this works just yet. the size of libtensorflow_cc.so would push the pip package even bigger (_cc.so is huge) and the pip package is already really big. But more importantly, last I heard the C++ API/ABI was not stable yet so I don't think shipping it is necesarily a good idea.

That said, I do ship _cc.so in the Gentoo TF package but I do it in /usr/lib64/ not under the python package.

Also, this is related: https://github.com/tensorflow/tensorflow/issues/18360

**Comment by efernandez** [comment]
Thanks for your comment @perfinion .

You're right, `libtensorflow_cc.so` is quite large.

> the C++ API/ABI was not stable yet
Do you know if that's also true for just running inference?

Although it'd require more work, with the appropriate guidance I might be able to look into a cleaner solution. Maybe an additional artifact (e.g. deb packge in Debian/Ubuntu) that gets generated for the C++ interface only, and also installing it in the standard path.
Do you know how to roughly do that, and where? (some additional bazel rules, ...)

**Comment by perfinion** [comment]
@efernandez yeah, making a .deb would probably be the best solution. I have packaged TensorFlow on Gentoo, you can refer to the ebuild for guidance. I'm not that familiar with debian but i'll definitely help however I can.
Here is the gentoo package, its quite involved but you can hopefully make sense of it:
https://github.com/gentoo/gentoo/blob/master/sci-libs/tensorflow/tensorflow-1.10.0_rc1.ebuild

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request closed without merging**
