### PR TITLE
Unnecessary character in logging.h

### PR DESCRIPTION
**Pull request by ervaibhavkumar**
Unnecessary new line character at line 229 .

### CODE REVIEW

**Comment by ervaibhavkumar** [comment]
I signed it!

**Comment by ervaibhavkumar** [comment]
Please assign this to me

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ervaibhavkumar** [comment]
@tensorflowbutler Assign this to me instead

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by olicht — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ervaibhavkumar** [comment]
@protoget Please approve the changes and update the label if the changes are fine according to you.

**Review by protoget — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ervaibhavkumar** [comment]
@protoget Please update the label as suggested by @tensorflowbutler

**Comment by pragyaak** [comment]
@ervaibhavkumar Can you help understand the difference in code change in this PR versus a previous commit (details at https://github.com/tensorflow/tensorflow/pull/21639/commits/7475e4abaa6d7fb926c73feab8b90c3b7160248c). Should this PR be closed as this PR has no new changes?

**Comment by ervaibhavkumar** [comment]
@pragyaak this PR is in the reference of the commit you are referencing

**Comment by yifeif** [comment]
The the new line was there because it's exceeding the 80 char per line limit linter checker. Our auto-formating tool is adding the new line back when we import this change. Will close this PR then. Thanks again @ervaibhavkumar!

**Pull request closed without merging**
