### PR TITLE
Fixed MobilenetV3 from keras/application

### LINKED ISSUE #48066: Evaluate mobilenet v3 keras model performance on ImageNet
Hi, I've tested the keras mobilenetv3_large_1.0 model accuracy, the model is created by calling the official API and using the official h5 model:
`model = tf.keras.applications.MobileNetV3Large(alpha=1.0, minimalistic=False, weights='imagenet')`

I do the following preprocess on ImageNet:
```
1. cropp the image of size [0.875*original height, 0.875*original width] from the center of original image, 
2. resize the image to 224x224
3. each channel subtract 127.5, multiply 2 (as the .h5 model has a rescaling layer, *1/255)
4. convert BGR to RGB format
```
Finally, I call model.evaluate() to do evaluation. But I can only get the accuracy:
>  sparse_categorical_accuracy: 0.7208 - sparse_top_k_categorical_accuracy: 0.9122

which is 3% less than reported 75%. Could you help me some advice on how the get the right accuracy?

### LINKED ISSUE #48226: Mobilenet v3 keras model lack a 7x7 avgpool and cannot get reported performance
Mobilenetv3 keras model is reported as converted from its ckpt model. As I observed its structure, they are inconsistent, as keras model **lacks a 'Avgpool' layer before conv_2 layer**. As a consequence, the released mobilenetv3_large_1.0 model can only achieve top1: 72.7%, 3% lower than ckpt model.

### LINKED ISSUE #48504: MobileNetV3 keras models have bug with GlobalAveragePooling2D
**System information**
TensorFlow version:
```python
print(tf.version.GIT_VERSION, tf.version.VERSION)
v2.4.0-rc4-71-g582c8d236cb 2.4.0
```

**Describe the current behavior**
According to [MobileNetV3Small documentation](https://www.tensorflow.org/api_docs/python/tf/keras/applications/MobileNetV3Small)

> The weights for all 6 models are obtained and translated from the Tensorflow checkpoints from TensorFlow checkpoints found here.

But keras models cannot reproduce performance on ImageNet #48066.

Tensorflow pb model contains GlobalAvgPool **before** Conv2D with filter <1x1x576x1024>:
image

But MobileNetV3Small from keras.application contains GlobalAvgPool **after** Conv2D with filter <1x1x576x1024>:
image

https://github.com/tensorflow/tensorflow/blob/6a278b9cf2fbed781661079b13d88b4106622a09/tensorflow/python/keras/applications/mobilenet_v3.py#L295-L308

Such version of MobileNetV3Small achieves top1: 56.79% instead of 68.1%.

**Describe the expected behavior**
To achieve reported accuracy, change [model code](https://github.com/tensorflow/tensorflow/blob/6a278b9cf2fbed781661079b13d88b4106622a09/tensorflow/python/keras/applications/mobilenet_v3.py#L295-L315) to:

```python
  x = activation(x)

  x = layers.GlobalAveragePooling2D()(x)
  if channel_axis == 1:
    x = layers.Reshape((last_conv_ch, 1, 1))(x)
  else:
    x = layers.Reshape((1, 1, last_conv_ch))(x)

  x = layers.Conv2D(
      last_point_ch,
      kernel_size=1,
      padding='same',
      use_bias=True,
      name='Conv_2')(x)
  x = activation(x)

  if include_top:
    if dropout_rate > 0:
      x = layers.Dropout(dropout_rate)(x)
    x = layers.Conv2D(classes, kernel_size=1, padding='same', name='Logits')(x)
    x = layers.Flatten()(x)
    imagenet_utils.validate_activation(classifier_activation, weights)
    x = layers.Activation(activation=classifier_activation,
                          name='Predictions')(x)
```

### PR DESCRIPTION
**Pull request by l-bat**
relates to #48504

### CODE REVIEW

**Review by bhack — APPROVED** [review]

**Comment by bhack** [comment]
@l-bat Nice to see you also here

**Comment by bhack** [comment]
We have a shape mismatch in tests now E.g. `AssertionError: Shapes differ: (None, 1, 1, 1024) vs (None, None, None, 1024)`.
Check Ubuntu CPU logs.

**Review by bhack — APPROVED** [review]
For Kokoro run

**Comment by bhack** [comment]
Can you run the test locally with `bazel test //tensorflow/python/keras/applications:applications_test`? I think iterating over the CI is quite slow

**Comment by bhack** [comment]
@nikitamaia We need to connect this PR  to the related issues, eventually assign these to @l-bat,  and put them in progress: 
https://github.com/tensorflow/tensorflow/issues/48504
https://github.com/tensorflow/tensorflow/issues/48226
https://github.com/tensorflow/tensorflow/issues/48066

**Comment by l-bat** [comment]
Can I modify tests to fix them? Because after my changes for MobilenetV3 without top shapes are `(None, 1, 1, 1024)` instead of `(None, None, None, 1024)`. I checked the original TF model from slim. The first GlobalAveragePooling2D  is included in the base part of the mobilenet.

**Comment by bhack** [comment]
I think you can change the test and we can run the CI but @fchollet  or @qlzh727 will need to evaluate the impact on the existing users code base.

**Comment by qlzh727** [comment]
Thanks for sending the fix, let me take a closer look for the issue.

**Comment by qlzh727** [comment]
Thanks for the fix. I think your fix is correct.

To provide more context here, I made the original implementation in https://github.com/tensorflow/tensorflow/commit/ef88a7aad44756a99aa57deddc59dc756ac2b469. One of the delta it stated is that:
"4. [Major] Changed the include_top implementation. The Conv2D layer with name "Conv_2" and its activation is moved to be base model structure, which means they are in the model even the include_top is False. This is based on comparing the implementation detail in original slim implementation in https://github.com/tensorflow/models/blob/a811a3b7e640722318ad868c99feddf3f3063e36/research/slim/nets/mobilenet/mobilenet_v3.py. If we can confirm this change is correct, then we should also fix it on the OSS keras_application as well."

I think I was overlook the conv layer between conv_2 and last conv layer for logits, and the change above is probably NOT correct.

To this PR, the correctness is justified in following points:
1. In the original slim implementation, the global pooling layer is between conv_1 and conv_2. https://github.com/tensorflow/models/blob/a811a3b7e640722318ad868c99feddf3f3063e36/research/slim/nets/mobilenet/mobilenet_v3.py#L132
2. In original paper (page 5 table 1), there is a "pool, 7x7 " between two conv layers.

**Review by qlzh727 — APPROVED** [review]

**Comment by bhack** [comment]
@qlzh727 Thanks can you connect these tickets: https://github.com/tensorflow/tensorflow/pull/48542#issuecomment-821171546

**Pull request merged**
