### PR TITLE
TFLM: Adding TANH op optimized for CEVA-BX1

### PR DESCRIPTION
**Pull request by yair-ehrenwald**
See github issue:  https://github.com/tensorflow/tensorflow/issues/45607

### CODE REVIEW

**Comment by gbaned** [comment]
@yair-ehrenwald Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@yair-ehrenwald Any update on this PR? Please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by yair-ehrenwald** [comment]
I will open a new PR for this later on.

**Pull request closed without merging**
