### PR TITLE
Bug Fix for verbs

### PR DESCRIPTION
**Pull request by jcf94**
This is to fix the bug of "invalid use of member in static member function bug" while building & "local protection error when doing rdma send bug" while using RDMA verbs as communication lib.

Related issues: #22455  #23220  #23618  #24135

### CODE REVIEW

**Comment by jcf94** [comment]
The recent bug was caused by commit 33170cc661f3838aa7d0d7fc19bb0c6ba4812a3c.

The new design of Allocator/SubAllocator is good but not working correctly with this part.
Waiting to migrate all the "cpu_allocator()" to "ProcessState::singleton()", and this patch will nolonger be needed.

**Comment by byronyi** [comment]
Preliminary tests have passed on my side. ``REGISTER_MEM_ALLOCATOR`` seems suspicious though. What do you think @poxvoculi? With this fix verbs wouldn't break in r1.13 at least.

**Comment by poxvoculi** [comment]
The use of GetCPUAllocator() inside REGISTER_MEM_ALLOCATOR is slightly surprising, but if it works, fine.  I'll wait for @yanivbl6 to comment before approving.  I hope to clean up the rest of the cpu_allocator() uses within a month.

**Comment by jcf94** [comment]
Thanks for your reviews. Yeah, the ultimate solution is to move out all the "cpu_allocator()" calls. But for now, though it is not very good to use "REGISTER_MEM_ALLOCATOR" here, I just did not find any better way... :)

**Comment by CheukNgai** [comment]
@jcf94 I tried to run BERT with ParamaterServerStrategy but found the PS process hung up in GetCPUAllocator(int) and could not start up a server. Then i tried another simper model with only 1 layer and the PS process could start up server successfully. Here's the backtrace from gdb:

(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f59044ccb41 in __cxa_guard_acquire ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f590df4d9cc in tensorflow::cpu_allocator() ()
   from /usr/local/lib/python2.7/dist-packages/tensorflow/python/../libtensorflow_framework.so
#3  0x00007f590e26fc95 in tensorflow::ProcessState::GetCPUAllocator(int) ()
   from /usr/local/lib/python2.7/dist-packages/tensorflow/python/../libtensorflow_framework.so
#4  0x00007f590df4f4b9 in tensorflow::AllocatorFactoryRegistry::GetAllocator()
    ()
   from /usr/local/lib/python2.7/dist-packages/tensor-flow/python/../libtensorflow_framework.so
#5  0x00007f590df4d9dd in tensorflow::cpu_allocator() ()
   from /usr/local/lib/python2.7/dist-packages/tensorflow/python/../libtensorflow_framework.so

**Comment by yanivbl6** [comment]
I believe the problem occurs when [use_bfc_allocator ](https://github.com/tensorflow/tensorflow/blob/7b1e7138f1fc36dd83e0cb1e8ea9b49d2b576802/tensorflow/core/common_runtime/process_state.cc#L67) is false.

when specifying TF_CPU_ALLOCATOR_USE_BFC=1, the 2 ps+ 2 workers finished successfully on my setup.

I am not sure if enforcing use_bfc_allocator when compiling with verbs is legal- for the very least, we need to throw an error [here](https://github.com/tensorflow/tensorflow/blob/7b1e7138f1fc36dd83e0cb1e8ea9b49d2b576802/tensorflow/core/common_runtime/process_state.cc#L105), so it wouldn't hang.

As mentioned, this error will occur when BFC is turned off even when distributed tensorflow is not used.

**Comment by byronyi** [comment]
I used force_gpu_compatible session opts so I may not noticed. @CheukNgai could you try specify TF_CPU_ALLOCATOR_USE_BFC=1 environment variable and check again?

**Comment by jeffdaily** [comment]
In our AMD fork, I can confirm that I needed `TF_CPU_ALLOCATOR_USE_BFC=1` to get non-distributed benchmarks to run with this patch.  Unfortunately, I won't be able to evaluate the grpc+verbs path for another week or so due to scheduled maintenance on the systems I've been using.  In any case, I do appreciate the progress made in getting verbs functioning again and understanding what the problem is.

**Comment by yanivbl6** [comment]
@CheukNgai, are you running the tensorflow/benchmark?
note that there was an [issue](https://github.com/tensorflow/benchmarks/issues/257) in the benchmark, that caused this error, and was since fixed.
This problem would persist if the initial session is not started with distributed parameters.
Or this could be a logical error where grpc init could be started before verbs init. I would have expected to encounter it if it was the case, unless there is some race condition.

**Comment by CheukNgai** [comment]
@yanivbl6 My testing model is a distribute version BERT, this model runs normally in grpc or grpc+gdr. However, when i run a 1-layer model, i can see that verbs will init and search for RDMA_DEVICE. I'm convinced that the verb doesn't init in the BERT situation. Thanks for reply.

**Comment by byronyi** [comment]
@ewilderj May I know when will r1.13 be branched? Hope we did not miss it with this PR :(

**Comment by jcf94** [comment]
Hi @CheukNgai , I tried several models using tensorflow/benchmarks (more than 1-layer, like VGG, ResNet, etc) and did not encounter your bugs.
I guess maybe it's related to Estimator & ParameterServerStrategy ? If you're hurried to train your BERT, maybe try not to use Estimator and see whether bug still exist.
I'll write a simple case in Estimator to check if bug can be reproduced here & try to figure out what happend.

**Comment by jcf94** [comment]
I just moved the REGISTER_MEM_ALLOCATOR to VerbsServer constructor, so at least this patch will never affect the other part when not using VERBs implementation.

**Comment by ewilderj** [comment]
> @ewilderj May I know when will r1.13 be branched? Hope we did not miss it with this PR :(

Alas, it was December 13. I emailed the developers@tensorflow.org list with this news. Sorry!

**Comment by yanivbl6** [comment]
@xiejw, I tested the latest commit and it's working well from my side, so I approve of the patch.

I also couldn't replicate the GetCPUAllocator error. @CheukNgai, can you provide a code for replication?

**Review by poxvoculi — DISMISSED** [review]

**Comment by CheukNgai** [comment]
@jcf94 You're right, i am using Estimator & ParameterServerStrategy. I am trying to switch to other API, but it was showed other model runs normally tough using Estimator & ParameterServerStrategy. The problem is not caused by the API. I will show the code later.

**Comment by byronyi** [comment]
@harshini-gadige Ready to pull?

**Comment by CheukNgai** [comment]
@yanivbl6  @byronyi Sorry, guys, i just found this error still exists when running the distribute BERT(this code runs normally in grpc and gdr). FYI, the simple model runs normally with grpc+verbs and it's hard for me to provide a minimal test code right now. I have attached the code in https://github.com/CheukNgai/verbs_test and guys can follow the README.md for replication.

**Comment by poxvoculi** [comment]
Today I submitted an internal change that makes cpu_allocator() map to ProcessState::GetCPUAllocator in real runtime instances.  It should be in tonight's build, and it should allow removal of the strange REGISTER_MEM_ALLOCTOR in this PR.  You may want to resync.

**Pull request merged**
