### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by baseer23**

### CODE REVIEW

**Comment by AbdulBaseerMohammedKhan** [comment]
@googlebot I signed it!

**Comment by AbdulBaseerMohammedKhan** [comment]
corrected a grammatical error

**Comment by mihaimaruseac** [comment]
Can you add a few more spelling fixes to this PR? We should not run multiple hours of CI for just a single word change

**Comment by AbdulBaseerMohammedKhan** [comment]
That was it 
there aren't any more

**Comment by kyscg** [comment]
From [`CONTRIBUTING.md`](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#general-guidelines-and-philosophy-for-contribution),
> As every PR requires several CPU/GPU hours of CI testing, we discourage submitting PRs to fix one typo, one warning,etc. We recommend fixing the same issue at the file level at least (e.g.: fix all typos in a file, fix all compiler warning in a file, etc.)

**Comment by mihaimaruseac** [comment]
Please look in other files too, in that case

**Review by mihaimaruseac — APPROVED** [review]

**Comment by kyscg** [comment]
Good catches!! Thanks for your contribution

**Review by rthadur — APPROVED** [review]

**Pull request merged**
