### PR TITLE
[TF:TRT] Support GatherV2 op when indices is constant

### PR DESCRIPTION
**Pull request by meena-at-work**
Convert the 'indices' input to a GatherV2 op into a constant layer when 'indices' is a constant.

Modify the unit tests to generate constant indices.

Signed-off-by: Meenakshi Venkataraman <meenakshiv@nvidia.com>

Tagging @bixia1 for review
CC: @tfeher @DEKHTIARJonathan

### CODE REVIEW

**Comment by meena-at-work** [comment]
Please review: @bixia1 
CC: @tfeher @DEKHTIARJonathan

**Comment by meena-at-work** [comment]
@googlebot I signed it!

**Comment by meena-at-work** [comment]
@bixia1 , regarding your comment:

> we actually require batch size 1 when (1) both input and indices are tensors, or (2) both input and indices are constants.
> But why do we add the case for (2), as we apply constant folding? In TF-TRT bridge, we report a problem when we see constant operations like this.

Thanks for pointing this out.
1)  is already covered in the converter -- and we flag it.
2) I added support for with this patch. Previously we weren't supporting  indices as constant at all, now we do.

I could remove my note on the PR, as it sounds redundant.

**Review by bixia1 — COMMENTED** [review]
Looks good to me. Thanks for your work!

**Review by bixia1 — APPROVED** [review]

**Pull request merged**
