### PR TITLE
Fix TestApp compile errors

### PR DESCRIPTION
**Pull request by ken0nek**
## Problem
We cannot build `TestApp` now because of compile errors.

## Screenshots

Screen Shot 2019-08-29 at 22 50 41

Screen Shot 2019-08-29 at 22 50 55

### CODE REVIEW

**Comment by ken0nek** [comment]
@googlebot I signed it!

**Comment by ken0nek** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
@miaout17 Can you please take a look on this PR? Thanks!

**Comment by jdduke** [comment]
@yyoon can you review?

**Comment by yyoon** [comment]
In fact, I just tried building the `TestApp` from master branch, and it's actually building fine for me.
@ken0nek Can you explain more about the exact steps you took, and what compile errors you saw?

I used the typical CocoaPods flow, by running `pod install` and then opening the `TestApp.xcworkspace` (NOTE: not the `.xcodeproj` file), and building the `TestApp` scheme from Xcode.

**Comment by gbaned** [comment]
@ken0nek Can you please check @yyoon comments and keep us posted. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@ken0nek Any update on this PR? Please. Thanks!

**Comment by ken0nek** [comment]
@gbaned Sorry for the late response. I checked this issue on master and there was no error any more. I will close this issue. Thank you for the review!

**Pull request closed without merging**
