### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by andrewharp**

### CODE REVIEW

**Comment by rmlarsen** [comment]
@petewarden could you take a look, please?

**Comment by tensorflowbutler** [comment]
Nagging Reviewers @petewarden, @aselle: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @aselle: It has been 29 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @aselle: It has been 44 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @aselle: It has been 59 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Review by shashishekhar — COMMENTED** [review]
Looks like this file has changed since, Andrew is this patch still relevant?

**Pull request closed without merging**
