### PR TITLE
Remove old Docker directory

### PR DESCRIPTION
**Pull request by angerson**
As of a couple weeks ago, the Dockerfile infrastructure in
tools/dockerfiles has supplanted the old set of Dockerfiles in
tools/docker. I don't know of any uses of the files remaining here.

If you think any of the files in this directory are important, please
add a comment. Otherwise, they'll be recoverable via Git's history.

### CODE REVIEW

**Comment by gunan** [comment]
@jayfurmanek @wdirons @claynerobison FYI, please make sure all your dockerfiles have moved to the new directories.

**Comment by wdirons** [comment]
My team supporting ppc64le has no concerns with removing the files listed in this PR. We publish docker images using the new process and we use the docker images in tensorflow/tools/ci_build for regression testing.

**Comment by claynerobison** [comment]
@gunan WIP

**Comment by fabboe** [comment]
This would be great. Many tutorials for example still assume pandas to be part of official tensorflow dockers but it seems to be gone during the move from `docker` to `dockerfiles` as the official source. Please correct me if I'm wrong.

```docker run -it --rm tensorflow/tensorflow:latest-jupyter python -c "import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pandas```

**Comment by angersson** [comment]
@claynerobison I'd like to get this in -- are you planning on making any changes?

@fabboe That's correct; we removed Pandas from the default images for size reasons. Pandas should be available in all of the `-jupyter`-tagged images, however.

**Review by av8ramit — DISMISSED** [review]

**Comment by rthadur** [comment]
@angersson can you please resolve conflicts

**Comment by claynerobison** [comment]
@angersson We have PRs in progress to move the horovod and data science Dockerfiles to the partial infrastructure. Once  https://github.com/tensorflow/tensorflow/pull/27169 is merged, you can merge this.

**Comment by fabboe** [comment]
> @fabboe That's correct; we removed Pandas from the default images for size reasons. Pandas should be available in all of the `-jupyter`-tagged images, however.

Thanks for the response @angersson. I can't find pandas in those images. Find below the steps to reproduce indication that pandas isn't part of most recent `-jupyter`  images (e.g. those from dockerhub).

```
$ docker pull tensorflow/tensorflow:latest-py3-jupyter
[..]

$ docker images -a
REPOSITORY              TAG                   IMAGE ID            CREATED             SIZE
tensorflow/tensorflow   latest-jupyter        81fed7ff566d        5 weeks ago         1.19GB
tensorflow/tensorflow   latest-py3-jupyter    631103b2f156        6 weeks ago         1.26GB

$ docker run -it --rm tensorflow/tensorflow:latest-py3-jupyter python -c "import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'pandas'

$ docker run -it --rm tensorflow/tensorflow:latest-jupyter python -c "import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pandas

```

I'm new to these dockerfiles scripts but indeed I **can't** find pandas package mentioned in [dockerfiles/dockerfiles/cpu-jupyter.Dockerfile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/cpu-jupyter.Dockerfile) nor [dockerfiles/partials/jupyter.partial.Dockerfile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/partials/jupyter.partial.Dockerfile)

I **can** find pandas in [dockerfiles/devel-cpu-jupyter.Dockerfile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/devel-cpu-jupyter.Dockerfile#L92) **but** either that image isn't published or I'm unable to guess the right tag name.

```
% docker pull tensorflow/tensorflow:devel-jupyter
Error response from daemon: manifest for tensorflow/tensorflow:devel-jupyter not found
% docker pull tensorflow/tensorflow:devel-cpu-jupyter
Error response from daemon: manifest for tensorflow/tensorflow:devel-cpu-jupyter not found
% docker pull tensorflow/tensorflow:devel-py3-jupyter
Error response from daemon: manifest for tensorflow
/tensorflow:devel-py3-jupyter not found
```

What am I missing? Or is pandas just only part of the unpublished devel images?

**Comment by angersson** [comment]
@fabboe Sorry about that, I forgot about how minimized the `jupyter` images are. `pandas` is in `tensorflow:devel`, as it's a build dependency, but isn't in any others.

If the tutorials are official TF tutorials, we should probably keep `pandas`. You're welcome to make a PR to add it.

**Comment by angersson** [comment]
I've rebased on master, fixed a typo, and updated the version_updater script.

@av8ramit @gunan @yifeif Can you take another look?

**Review by gunan — APPROVED** [review]

**Pull request merged**
