### PR TITLE
Removed six dependency in tools/git since it breaks hermetic builds

### PR DESCRIPTION
**Pull request by dmadisetti**
[git_configure.bzl](https://github.com/tensorflow/tensorflow/blob/master/third_party/git/git_configure.bzl) uses the host python to run [tools/git/gen_git_source.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/git/gen_git_source.py)

It looks like in a cross compatibility migration (https://github.com/tensorflow/tensorflow/commit/c396546ca3d9424f7d902f4c5c604c209f9c0f0c) a `six` dependency was added. If building on a completely vanilla system, this will break if `six` is not installed on the host. Ideally, this should be done with python provided by bazel, but these rules are called during `tf_workspace`, `bind`, etc... So I think this approach is acceptable.

Small change, but also adds consistency! See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/git/gen_git_source.py#L171

### CODE REVIEW

**Comment by dmadisetti** [comment]
I found evidence I'm not the only person facing this issue: https://github.com/google/mediapipe/issues/276

Everytime I blow away my bazel cache I have to apply this patch

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by gbaned** [comment]
@dmadisetti Can you please address Ubuntu Sanity errors? Thanks!

**Comment by dmadisetti** [comment]
Oh wow. I thought the tests were just due to flake, my bad. Surprised this removed six as a dependency all together in the other apis. Sanity checks passed locally

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Not completely sure this won't break internal py2 old workflows, but let's test

**Comment by dmadisetti** [comment]
:tada:

@mihaimaruseac @gbaned  Looks to be good. Anything needed on my end?

**Comment by mihaimaruseac** [comment]
Nothing left to do here at the moment. It is pending internal integration, review and testing. If all goes well, it will be automerged, otherwise we'll report back.

**Pull request merged**
