### PR TITLE
Recommend the user site, no sudo

### PR DESCRIPTION
**Pull request by wimglenn**
Using sudo to upgrade a pip which was installed by apt-get messes up the system environment and causes [issues](https://stackoverflow.com/q/51404984/674039).  Recommend to use the user site for installing tensor flow.

### CODE REVIEW

**Comment by rmlarsen** [comment]
@wimglenn thanks! Please sign the CLA.

**Comment by wimglenn** [comment]
I signed it!

**Review by MarkDaoust — APPROVED** [review]
Thanks for the fix.

It's hard to test this. But everything suggests that this is correct.

**Comment by wimglenn** [comment]
Hi @rmlarsen / @MarkDaoust , I thought this merge would update the guide [here](https://www.tensorflow.org/install/install_linux#InstallingNativePip), but it hasn't.  Is there a separate release process for that?

**Pull request merged**
