### PR TITLE
Fix for #26294

### PR DESCRIPTION
**Pull request by kyscg**

### CODE REVIEW

**Comment by kyscg** [comment]
Will this work @dynamicwebpaige

**Comment by kyscg** [comment]
It's been quite a while, I'd love to know if I should improve anything @rthadur @dynamicwebpaige

**Comment by jhseu** [comment]
Looks like a duplicate of https://github.com/tensorflow/tensorflow/pull/26332. Since that came first, I'll close this one out.

**Comment by SunflowerPKU** [comment]
Hi @jhseu @kyscg , I am doing a research about "how the labels such as 'good first issue' help newcomers to contribute" , but I found many PR were rejected because of duplication, especially for popular projects. How do you think of this problem? I wonder whether mechanisms to avoid this problem are needed, for example, in addition to "open" and "closed", add a new status of issue: ongoing.

**Pull request closed without merging**
