### PR TITLE
Added early stopping and CheckpointSaverListeners to train and evaluate

### PR DESCRIPTION
**Pull request by ankitvgupta**
Addresses the issue at https://github.com/tensorflow/tensorflow/issues/16203

### CODE REVIEW

**Comment by ankitvgupta** [comment]
Just wanted to ping @ispirmustafa for a review. This is my first time submitting a PR here, so wasn't sure if I was supposed to tag someone or not.

**Comment by rmlarsen** [comment]
@ispirmustafa please take a look at this.

**Comment by ankitvgupta** [comment]
Pinging @xiejw

**Comment by rmlarsen** [comment]
@xiejw could you please take a look?

**Comment by xiejw** [comment]
Sorry, I cannot approve this PR. 

SavingListener part looks good. But ValidationMonitor is known not working well in distributed model. So, we cannot support that. 

The workaround for user, who needs this feature, is to define the monitors.ValidationMonitor in user code and pass to Experiment constructor (train_monitors arg).

**Comment by ankitvgupta** [comment]
I'm a little confused - I don't believe I added ValidationMonitor anywhere. I just added two parameters to its current usage.

**Comment by xiejw** [comment]
Hi,

Experiment class is designed to support not only local (single-machine single-process, depending on definition) but also distributed training and evaluation. So, any constructor argument should fit both scenarios. Otherwise, it will confuse users and/or increase maintenance cost. 

ValidationMonitor was in the code already as the original code only uses it to serve the purpose to do evaluation during training. This is an implementation detail, so ValidationMonitor can be replaced by SessionRunHook or SavingListener without affecting API and users. 

However, the parameters, such as early_stopping_metric, added in this PR is only supported in local case. This is a known fact.  It cannot work with distributed case -- which is a known hard problem. This is a major reason.

If early_stopping_metric, and other early stopping parameters can be added to support both local and distributed case, that will be great! The change could be huge as it needs to adjust all the code in train_and_evaluate(), train(), continuer_evaluate() and other places, as one proper definition of early stopping is, once the condition is met, all the nodes in the cluster should stop at more or less the same time. (It may have other definition also). 

If user only needs this for local case, launching a python script to perform train and evaluate in one process, a workaround was mentioned. 

Hope this helps.

**Comment by ankitvgupta** [comment]
Got it, that makes more sense. Thank you!

How would someone do early stopping in the distributed version of the code right now?

**Pull request closed without merging**
