### PR TITLE
Support --config=monolithic in tf.sysconfig.get_link_flags()

### PR DESCRIPTION
**Pull request by alsrgv**
Currently, `tf.sysconfig.get_link_flags()` always adds `-ltensorflow_framework`.  With this change, it would check whether TensorFlow was built with `--config=monolithic`.

### CODE REVIEW

**Comment by alsrgv** [comment]
@jhseu, would be very nice if this could get in before you cut over to 1.5 branch.

**Review by drpngx — CHANGES_REQUESTED** [review]
Maybe `monolithic_build`?

**Comment by alsrgv** [comment]
@drpngx, sounds good, updated.

**Comment by alsrgv** [comment]
@drpngx, gentle ping.

**Review by drpngx — APPROVED** [review]

**Comment by drpngx** [comment]
Sorry, forgot about this.

(We should get rid of `gen_git_source.sh`, which AFAIK is only used in the Makefile version.)

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by ekelsen** [comment]
Just an FYI, this PR has mostly been reverted after pulling - it breaks forward compatibility.  I left the C objects in - after 3 weeks have passed you can resubmit the rest of the change and forward compatibility will then pass.

**Comment by alsrgv** [comment]
@ekelsen, I just checked `master` and it seems that all the changes are still there. Can you point me to revert diff and share more context about breaking forward compatibility?

**Comment by drpngx** [comment]
I think it's the golden for the API compatibility in `tools/api_tests`. It's strange that it passed the tests in the first place.

**Comment by alsrgv** [comment]
@drpngx, the golden change was part of the PR.  I'm hoping this change can be included as part of next official release (1.5.0 or 1.4.x), so there's no need to have special checks in plugin build scripts for monolithic TF builds.

**Comment by ekelsen** [comment]
I think the push hadn't finished when you last checked - it is now.

Unfortunately, given that 3 weeks need to pass, I think it is unlikely that this can make it into 1.5.0.

**Comment by ekelsen** [comment]
Forward compatibility means that models created at HEAD need to run on binaries that are up to 3 weeks old.  This change broke this guarantee.  The solution is to add the symbols to the C code, then wait three weeks and add your python changes.

**Comment by alsrgv** [comment]
@ekelsen, I just checked now, and the code is still in `master`.

I'm not sure how would it break forward compatibility though since `tf.sysconfig.get_link_flags()` would remain internally-consistent - as long as you use Python bits and binaries from the same TF git ref.

Is there a situation when folks use TF binaries from 3 weeks older than accompanying TF Python code?

**Pull request merged**
