### PR TITLE
Update input parameter validation for advanced activation layers.

### PR DESCRIPTION
**Pull request by amogh7joshi**
Added alpha/theta value validation on the ThresholdedReLU and PReLU layers, and updated the error messages raised on ThresholdedReLU, PReLU, and ELU. Also added test cases for these changes, and added stride validation in convolutional layers.

### CODE REVIEW

**Review by mattdangerw — APPROVED** [review]
Thanks for the PR!

**Comment by rthadur** [comment]
@amogh7joshi can you please check sanity build failures ?

**Comment by amogh7joshi** [comment]
The LeakyReLU `alpha` value isn't supposed to be less than 0 but one of the primary test cases for it (see line 34 of https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/advanced_activations_test.py) uses a value of -1.

Not sure if I should remove that test case or remove the error that looks for alpha <= 0. Let me know.

**Comment by gbaned** [comment]
@mattdangerw  Can you please check build failures. Thanks!

**Comment by mattdangerw** [comment]
@amogh7joshi is correct that we should not have alpha < 0. We can just remove the `-1` from this list of alpha values to test on line 34. Shouldn't have been testing that anyway.

Thanks!

**Comment by amogh7joshi** [comment]
@mattdangerw @gbaned, I will remove the test case then and we should be good to go from there. Thanks!

**Review by mattdangerw — APPROVED** [review]

**Comment by amogh7joshi** [comment]
@mattdangerw The build has broken again, but for a different reason unrelated to this pull request (it is in the bazel build files that the error is located). Is there any way to fix this?

**Comment by mattdangerw** [comment]
Can you try just syncing to the latest master? We may have had some build breakages earlier this week.

**Comment by amogh7joshi** [comment]
It doesn't allow me to resync to any other branches, I think the checks will re-run if you re-approve the pull request though. I've re-requested a review. We can try that to see if it works.

**Review by mattdangerw — APPROVED** [review]

**Comment by gbaned** [comment]
@amogh7joshi Can you please address Ubuntu Sanity errors? Thanks!

**Comment by amogh7joshi** [comment]
The issue was with the line lengths on one of the tests, from what I gathered. That is fixed now, and hopefully that should resolve all build conflicts.

**Review by rthadur — APPROVED** [review]

**Pull request merged**
