### PR TITLE
TF compilation warning removed

### PR DESCRIPTION
**Pull request by PariksheetPinjari909**
Variables are initialised and warnings in the compilation of tensorflow are removed.

### CODE REVIEW

**Review by saeta — DISMISSED** [review]
LGTM, thanks!

**Comment by rthadur** [comment]
@PariksheetPinjari909 can you please resolve conflicts.

**Comment by PariksheetPinjari909** [comment]
@rthadur resolved the conflict
@saeta Can you please approve again. TIA

**Review by saeta — APPROVED** [review]
LGTM.

**Pull request merged**
