### PR TITLE
Rename directories to have underscores instead of dashes (cmsis-nn -> cmsis_nn and ethos-u -> ethos_u)

### PR DESCRIPTION
**Pull request by advaitjain**
Fixes http://b/168824958
- Rename ethos-u to ethos_u.
- cmsis-nn -> cmsis_nn

@mansnils @freddan80 : There is one more cleanup that might be worth addressing as part of this cleanup, and that is the use of OPTIMIZED_KERNEL_DIR instead of TAGS:

The issue at hand is that we are moving towards explicitly including the specific target and optimized_kernel dirs that are needed (as opposed to including all the *.inc and then filtering based on tags):
https://github.com/tensorflow/tensorflow/blob/161fcca9a7767a63a304a875ff26d22026d5e1b5/tensorflow/lite/micro/tools/make/Makefile#L560-L583

What this means is that we would like to change the make command to be:
```
make TARGET=cortex_m_generic OPTIMIZED_KERNEL_DIR=cmsis_nn
```

The catch is what to do about ethos_u since with this new approach we won't be including ext_libs/ethos_u.inc or specializing kernels/ethos_u/ethosu.cc unless we did something special.

An option would be to have cortex_m_generic_makefile.inc include ext_libs/ethos_u.inc (depending on a command line option). And have ethos_u.inc explicitly specialize kernels/ethos_u/ethos.cc (using this same command line option).

I can think of other more involved approaches too, but wanted to type this up to get initial thoughts. Happy to prototype this so that you have a more concrete idea of what I'm suggesting.

The google-way of doing this would be to have separate PRs for each of these changes. I can line up the PRs and plan to merge them in the space of a day or two once they are all approved so that you can pull in all the changes in one go.

However, if you guys would prefer, I can do this all in a single PR too. Let me know.

### CODE REVIEW

**Comment by mansnils** [comment]
@advaitjain If we update Ethos-U in same was as CMSIS-NN, would this not work?
make TARGET=cortex_m_generic OPTIMIZED_KERNEL_DIR=ethos_u
The same way as this (or what is the catch?)
make TARGET=cortex_m_generic OPTIMIZED_KERNEL_DIR=cmsis_nn

Another thing is that we actually use TAGS="cmsis-nn ethos-u". I realize that it will not be possible with OPTIMIZED_KERNEL_DIR.
Potentially a CMSIS-NN operator might not be supported by Ethos-U, then we may want to fall back on CMSIS-NN instead of Reference kernel. So I am thinking how we could support this, perhaps as a special case for Ethos-U, where this logic is moved to ext_libs/ethos_u.inc..?

**Comment by advaitjain** [comment]
Yes, the `TAGS="cmsis-nn ethos-u"` was the case that I was referring to as the catch. We want to disallow multiple directories of optimized kernels because for the most part the optimized kernel implementations are incompatible.

Do you imagine having more ethos-u kernels or will the current one be the only ethos-u specific kernel?

If you always use cmsis_nn with ethos_u then we could consolidate ethos-u and cmsis_nn into one optimized kernel directory and have an ifdef in there. This would be the approach that we are taking for xtensa.

So we would move ethosu.cc to cmsis_nn and have something like:

```
if defined(ETHOSU)
// current contents of ethosu.
#else
// fallback no-op ethosu kernel.
#endif
```

and ext_libs/cmsis_nn.inc can include ext_libs/ethosu.inc (or move that logic into cmsis_nn.inc, if it doesn't clutter things up).


If you do need a way to have all reference kernels with ethos-u then your idea of adding a specialize call for cmsis_nn from  ethos_u.inc would be the way to go.

Let me know what you guys need and we can dive deeper in that direction.

**Comment by mansnils** [comment]
There might be some other Ethos-X. I think we would like to support both TAGS=ethos-u and TAGS="ethos-u cmsis-nn". Another potential use case might be that there is for example a Cortex-M4+DSP, with specific conv optimizations for the DSP. Then one would want to run conv with the DSP but still benefit from the rest of the CMSIS-NN optimizations (so TAGS="some-co-processor cmsis-nn").

**Comment by advaitjain** [comment]
Thanks for the additional context.

Some background on where I am coming at this from:
 * We would like to have fewer specialized kernel directories and group things under a common directory, as much as possible.
 * We are going through a similar exercise with engineers at Cadence where we are consolidating different variations into a common xtensa directory and using -D{TARGET_ARCH} as a way to have ifdefs in the code.
 * The trade-off here is reduced maintenance overhead over time at the cost of more work up-front when implementing the kernels or refactoring of the existing implementations that follow the older pattern.

The co-processor use-case is not something we thought through. I'd still like for this to be a deliberate choice on the command line instead of relying on `TAGS`.

How about something like:
 * `TAGS="ethos-u cmsis-nn"` is replaced with `OPTIMIZED_KERNEL_DIR=cmsis_nn CO_PROCESSOR=ethos_u`
 * `TAGS="ethos-u"` is replaced with `OPTIMIZED_KERNEL_DIR=none CO_PROCESSOR=ethos_u`
    *  we need `OPTIMIZED_KERNEL_DIR=none` for backwards compatibility.

And the makefile explicitly includes and specializes, giving preference to `CO_PROCESSOR` and then `OPTIMIZED_KERNEL_DIR` when specializing kernel implementations.

And is it worth having the co-processor directory be called `ethos` instead of `ethos_u` so that any variants can go in there in the future?

**Comment by mansnils** [comment]
Having OPTIMIZED_KERNEL_DIR and CO_PROCESSOR seem good, although naming could be confusing in the case of OPTIMIZED_KERNEL_DIR=cmsis_nn and CO_PROCESSOR=main_processor, anyway that is a minor detail a long as it works.
Perhaps this could then work with the general example I mentioned, for example OPTIMIZED_KERNEL_DIR=cmsis_nn and CO_PROCESSOR=DSP.
So we would prefer the more general case where CO_PROCESSOR is just that and is not named after Ethos-U or Ethos.

**Comment by advaitjain** [comment]
ok, I think we're converging on a solution. I have created #46473

The steps that I am thinking of is to have you guide #46473 to where it does what you need as a stand-alone change. If you can check it out and test it locally, that would be great.

And then I make a follow-up PR that renames the dash to underscore. Once both are approved we merge them as separate PRs (in quick succession).

Let me know what you think.

**Comment by advaitjain** [comment]
Closing this PR in favor of a new one https://github.com/tensorflow/tensorflow/pull/46584 for the dreictory renaming.

**Pull request closed without merging**
