### PR TITLE
Fix SparseDenseCwiseMulOrDivGrad scalar case

### LINKED ISSUE #46008: SparseTensor mul. broadcasting gradient fails
## System information
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: v1.12.1-47912-gec43aacb56f 2.5.0-dev20201219
- Python version: 3.7

## Current behavior

Computing gradients of scaled `tf.SparseTensor`s fails. This is resolved be adding dimensions to scalar.

## Expected behavior

Gradient computation compatible with automatic dimension adding when broadcasting leading dimensions.

## Standalone code to reproduce the issue

[Notebook](https://colab.research.google.com/drive/1R-HV0570iNzbY3yUGXSuqnikPWZd6aDO?usp=sharing)

Code copied below for convenience

```python
import tensorflow as tf

n = 5
values = tf.Variable(tf.random.uniform((n,)))
indices = tf.sparse.eye(n).indices
with tf.GradientTape() as tape:
    tape.watch(values)
    st = tf.SparseTensor(indices, values, (n, n))
    st = st * 2.                        # doesn't work
    # st = st * tf.reshape(2., (1, 1))  # works
    loss = tf.sparse.reduce_sum(st)

grad = tape.gradient(loss, values)
print(grad)
```

## Stack Trace

```txt
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    grad = tape.gradient(loss, values)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 1073, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 162, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/ops/sparse_grad.py", line 247, in _SparseDenseCwiseMulGrad
    return _SparseDenseCwiseMulOrDivGrad(op, grad, True)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/ops/sparse_grad.py", line 227, in _SparseDenseCwiseMulOrDivGrad
    dense_vals = array_ops.gather_nd(y, scaled_indices)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 5348, in gather_nd
    return gen_array_ops.gather_nd(params, indices, name=name)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3695, in gather_nd
    _ops.raise_from_not_ok_status(e, name)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6870, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: params must be at least a vector [Op:GatherNd]
```

### PR DESCRIPTION
**Pull request by WindQAQ**
Fixes #46008.

### CODE REVIEW

**Review by allenlavoie — COMMENTED** [review]
Should we relax the constraints on gather_nd instead? i.e. accept an [N, 0] indices array as indexing into a scalar `params`. It seems like quite a bit of complexity here otherwise (tf.cond etc.), and we may run into a similar issue elsewhere.

**Comment by WindQAQ** [comment]
Thanks for suggestion! [N, 0] indices array looks weird to me because number of elements inside it is zero, which means that we are gathering nothing. In that case, what should we expect the output shape of gather_nd? Shape of (N,) or a scalar.

**Comment by allenlavoie** [comment]
I agree that size-zero arrays are always a bit weird, but they're often a useful special case. I'd return shape (N,) if the requested indices were shape (N, 0); requested indices with shape (0,) would return a scalar (if that's supported). That matches the general case of (..., N) -> (...) for a full index, right?

We do something similar with slices in Python, and so does NumPy:
https://numpy.org/doc/stable/reference/arrays.indexing.html#detailed-notes
> An empty (tuple) index is a full scalar index into a zero dimensional array. x[()] returns a scalar if x is zero dimensional and a view otherwise. On the other hand x[...] always returns a view.

It's just adding some leading dimensions, but seems like the same principle.

**Comment by gbaned** [comment]
@WindQAQ  Can you please check @allenlavoie's comments and keep us posted ? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@WindQAQ  Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
