### PR TITLE
Removes `SetIsStateful` from op StatelessRandomGetKeyCounterAlg

### PR DESCRIPTION
**Pull request by wangpengmit**
PiperOrigin-RevId: 339147256
Change-Id: I4444b47e9d974bd5bb643b80ae55fcbc347653df

### CODE REVIEW

**Comment by wangpengmit** [comment]
Otherwise tf.random.stateless_XXX functions can be broken when used in tf.data pipelines.

**Review by allenlavoie — APPROVED** [review]
I do think this will cause issues / require more special-casing in optimizations without the stateful bit. DTensor has already run into it for the non-stateful ops with the device selector fused in.

Maybe rather than omitting the stateful bit for this op we could check if there's a statically-known device assignment and if so not include it at all? Presumably tf.data pipelines would be on the CPU.

But if something's broken now feel free to check this in. We should IMO add tf.data tests and put back the stateful bit later, though.

**Comment by wangpengmit** [comment]
> I do think this will cause issues / require more special-casing in optimizations without the stateful bit. DTensor has already run into it for the non-stateful ops with the device selector fused in.
> 
> Maybe rather than omitting the stateful bit for this op we could check if there's a statically-known device assignment and if so not include it at all? Presumably tf.data pipelines would be on the CPU.
> 
> But if something's broken now feel free to check this in. We should IMO add tf.data tests and put back the stateful bit later, though.

My goal for StatelessRandomGetKeyCounterAlg is to be a computability shim to reproduce all tf.random.stateless_XXX's behaviors, without attempt to fix any of them. Hopefully in the future all those problematic behaviors along with StatelessRandomGetKeyCounterAlg will be deprecated, leaving StatelessRandomNormalV2 etc as the sole ideal op.

Conditionally trimming StatelessRandomGetKeyCounterAlg sounds interesting, but it'll take some time. The SetIsStateful bit is already breaking one internal project, so I fear it'll break more OSS code.

**Comment by wangpengmit** [comment]
This cherrypick is not needed because the V2 stateless RNG ops are not activated in branch 2.4 (`_FORWARD_COMPATIBILITY_HORIZON` is [frozen](https://github.com/tensorflow/tensorflow/blob/d2dcde5017c5e16541c3d2fdb487ad124cd96be7/tensorflow/python/compat/compat.py#L36) to be the branch cut date, which is before the V2 ops' kick-in [date](https://github.com/tensorflow/tensorflow/blob/d2dcde5017c5e16541c3d2fdb487ad124cd96be7/tensorflow/python/ops/stateless_random_ops.py#L209)).

**Pull request closed without merging**
