### PR TITLE
correcting index_to_string_table_from_tensor doc

### PR DESCRIPTION
**Pull request by ChihChengLiang**

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
I signed it!

**Comment by caisq** [comment]
cc @ysuematsu

**Comment by ysuematsu** [comment]
Jenkins, test this please.

**Comment by caisq** [comment]
Oops. Sorry for the delay. @tensorflow-jenkins test this please

**Review by drpngx — APPROVED** [review]
Thanks for the fix!

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
`http_util` errors are unrelated.

**Pull request merged**
