### PR TITLE
min_quantize lib and command line

### PR DESCRIPTION
**Pull request by ghost**
a quantize/obfuscate lib
1. without Quantize/DeQuantize ops
2. could obfuscate node names
3. use KMeans instead of simple average slice

### CODE REVIEW

**Comment by eigen2017** [comment]
u need pass cla ~ i was there, now i passed , just follow me:
https://github.com/tensorflow/tensorflow/pull/14867

**Comment by lyskika** [comment]
I signed it!

**Comment by lyskika** [comment]
I signed it!

**Comment by lyskika** [comment]
change repository

**Pull request closed without merging**
