### PR TITLE
[PluggableDevice] Add `TF_OpKernelConstruction_GetNodeDef`

### PR DESCRIPTION
**Pull request by PatriceVignola**
Although the API has functions like `TF_OpKernelConstruction_GetAttrInt32`, it lacks an abstract to iterate through all the attributes and get their names as well as their value. Since some device backends have relatively slow kernel creation times, being able to access the `NodeDef` allows them to uniquely identify kernels for caching purposes.

### CODE REVIEW

**Comment by gbaned** [comment]
@jpienaar Can you please review this PR ? Thanks!

**Comment by jpienaar** [comment]
We already have taken some steps to get rid of most iteration over attributes towards enabling the backing to not be NodeDef.

Additionally exposing the NodeDef results in exposing unregistered attributes which are in the UB part of the world. But I don't know what the policy is PluggableDevice side.

**Comment by PatriceVignola** [comment]
@jpienaar I can certainly change this PR provide ways to iterate through attributes instead of exposing the NodeDef itself. The ultimate goal here is to be able to cache kernels that have identical attributes to avoid creating kernels that have a long initialization cost multiple times. Can you point me towards the steps taken so far to decouple attributes from the NodeDef?

**Comment by gbaned** [comment]
@jpienaar  Can you please assist on above comments from @PatriceVignola. Thanks!

**Comment by gbaned** [comment]
@jpienaar Can you please assist on above comments from @PatriceVignola. Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by PatriceVignola** [comment]
@gbaned Done!

**Comment by gbaned** [comment]
@PatriceVignola Can you please resolve conflicts? Thank you!

**Comment by PatriceVignola** [comment]
@gbaned Done!

**Review by gbaned — APPROVED** [review]

**Pull request merged**
