### PR TITLE
Fix mixed use of bytes and unicode string in gc.py

### PR DESCRIPTION
**Pull request by raviqqe**

### CODE REVIEW

**Comment by vrv** [comment]
Perhaps you could write a test for this so it doesn't regress?

See https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#general-guidelines-and-philosophy-for-contribution

**Comment by raviqqe** [comment]
I wrote a test. Could you run it?

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by raviqqe** [comment]
I cannot access to ci.tensorflow.org to see what is wrong with my code. My Chrome shows NET::ERR_CERT_REVOKED. What is going on?

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by raviqqe** [comment]
Fixed an error.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@raviqqe The test seems to be failing, can you check?

**Comment by raviqqe** [comment]
Yes, I did.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@raviqqe it appears there are some linter errors in your change, please fix:

https://ci.tensorflow.org/job/tensorflow-pull-requests-sanity/4357/consoleFull

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@raviqqe looks like you haave a few more bugs to squash...

**Comment by rmlarsen** [comment]
@raviqqe Nope, unit test failing.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by raviqqe** [comment]
Is the error related to this change? Should I rebase this branch to master or do something?

**Comment by rmlarsen** [comment]
@raviqqe nevermind, the failures in the latest tests are unrelated to your change. This is ready to merge. Thanks for the contribution.

**Comment by raviqqe** [comment]
Finally! Thank you for your assistance!

**Pull request merged**
