### PR TITLE
LayernormSimpleRNN added

### PR DESCRIPTION
**Pull request by ulf1**
tf.keras.experimental.LayernormSimpleRNN is based on tf.keras.layers.SimpleRNN and can apply tf.keras.layers.LayerNormalization instead of bias before the activation function of the recurrent kernel. 

LayernormSimpleRNN is a proposal how to extend SimpleRNN (and other RNN layers) with layer normalization.

### CODE REVIEW

**Comment by ulf1** [comment]
if `LayernormSimpleRNN(..., use_bias=True, use_layernorm=False,...)` then it behaves like `SimpleRNN(..., use_bias=True, ...)`

```
a_t = input_t * W_xh + hidden_{t-1} * W_hh
hidden_t = activation(a_t + bias)
```

if `LayernormSimpleRNN(..., use_bias=True, use_layernorm=True,...)` then bias will be disabled (`use_bias=False`) and `LayerNormalization` applied

```
a_t = input_t * W_xh + hidden_{t-1} * W_hh
normalized_t = gamma / std_t * (a_t - mu_t) + beta
hidden_t = activation(normalized_t)
```

Please refer to page 3, formula 4 in Ba et al (2016), https://arxiv.org/abs/1607.06450

**Comment by qlzh727** [comment]
Thanks for opening this PR and sorry for the late reply.

The current code has a lot of duplication with the SimpleRNN/Cell, and only a small portion is the layer norm related. Since layer norm is quite orthogonal with RNN, can we take the python mixin class approach to the new class? eg SimpleRNNLayerNorm is a mixin of (SimpleRNN, layerNorm), where layernorm will just add some logic to the call() and get_config().

Also, I would like to add Francois as reviewer, since I am not quite sure to accept this as a core keras API. Maybe this is more suitable for tensorflow/addons.

**Comment by ulf1** [comment]
sure, mixin makes a lot of sense. I did not want use mixin from the start as it might obfuscate things. Do you want to make the changes?

**Comment by qlzh727** [comment]
Please make the change in this PR. In case that we move it to tensorflow/addons, you can just copy the content and move it to the addons repository.

**Comment by ulf1** [comment]
Should I also rename `LayernormSimpleRNN` to `SimpleRNNLayerNorm`? You mentionend it above. It makes sense for autocompletion

**Comment by ulf1** [comment]
Inheriting or mixin does not work, e.g. `class LayernormSimpleRNNCell(SimpleRNNCell):` or `class LayernormSimpleRNNCell(SimpleRNNCell, LayerNormalization):`. When calling the parent constructor it throws `TypeError: ('Keyword argument not understood:', 'activation')`

**Comment by qlzh727** [comment]
The error is usually caused when you pass all the param from SimpleRNNCell to LayerNormalization. In LayernormSimpleRNNCell, what you can do is selectively passing params to __init__ SimpleRNNCell and LayerNormalization respectively.

You can google python MRO init for more details.

**Comment by ulf1** [comment]
Thanks about the inheritance issue. The code is refactored using the mixin approch 

- `class LayernormSimpleRNNCell(SimpleRNNCell, LayerNormalization):` and
- `class LayernormSimpleRNN(SimpleRNN):`

**Comment by qlzh727** [comment]
Yea, since we already had one in Addon, it makes more sense to have this one in addon.

Also, thinking about about the MRO here, maybe it makes more sense to change the LayernormSimpleRNNcell to HAVE a layernorm layer, rather than BE a layernorm layer, which is more aligned with the existing code in LayernormLSTMcell.

**Comment by ulf1** [comment]
Hello @qlzh727 I tried `class LayernormSimpleRNNCell(SimpleRNNCell):` before

https://gist.github.com/ulf1/d36051d0a91073f974c9e8b082865657#file-script4-py

The difference to `class LayernormSimpleRNNCell(SimpleRNNCell, LayerNormalization):` are not much. 

in `__init__`

- `self.layernorm = LayerNormalization(...)` versus
- `LayerNormalization.__init__(...)`

in `build` an extra call is required

```
if self.use_layernorm:
      LayerNormalization.build(self, (None, self.units))
```

in `call`

- `output = self.layernorm(output)`, versus
- `output = LayerNormalization.call(self, output)`

in `config`

- `ln_config = self.layernorm.get_config()`, versus
- `ln_config = LayerNormalization.get_config(self)`

We could also try a `LayernormMixin` for the adjustments in `get_config` (see `ln_config`) then use `class LayernormSimpleRNNCell(SimpleRNNCell, LayernormMixin):`

**Comment by ulf1** [comment]
I moved the code to addons https://github.com/tensorflow/addons/pull/841
You can close this PR now

**Comment by qlzh727** [comment]
Ack, closing this PR now.

**Pull request closed without merging**
