### PR TITLE
Add bullet points so Reduction values are clearer

### PR DESCRIPTION
**Pull request by terrytangyuan**
Currently it's these items are all in one line in https://www.tensorflow.org/api_docs/python/tf/losses/Reduction, which is hard to visualize.

### CODE REVIEW

**Review by case540 — DISMISSED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by terrytangyuan** [comment]
@ymodak Could you or anyone else merge this? This has been here for a month and I have to resolve conflicts every now and then.

**Comment by terrytangyuan** [comment]
@case540 Could you re-approve this? I had to rebase and resolve conflicts. Thank you!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request merged**
