### PR TITLE
Removing deprecated array_ops.where() in Keras backend

### PR DESCRIPTION
**Pull request by habernal**
`array_ops.where()` is deprecated in TF2; updating to get rid of warnings

### CODE REVIEW

**Review by qlzh727 — DISMISSED** [review]

**Comment by gbaned** [comment]
@habernal Could you please address Ubuntu Sanity errors? Thanks!

**Comment by habernal** [comment]
@gbaned From what I see in the logs, there are these two failures:

```
...
2. do_pylint PYTHON2: Python 2 pylint
  FAIL
3. do_pylint PYTHON3: Python 3 pylint
  FAIL
...
2 failed; 12 passed.
Sanity checks FAILED
```

To be honest, I don't know how to address that (do I have to install the whole CI locally and run it?).

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Review by qlzh727 — APPROVED** [review]

**Comment by qlzh727** [comment]
Sorry for the late reply, I was on holiday for a few weeks.

**Pull request merged**
