### PR TITLE
Swap indices in detect_objects, reflecting reordered output tensors

### PR DESCRIPTION
**Pull request by jawj**
Fixes issue https://github.com/tensorflow/tensorflow/issues/51591

### CODE REVIEW

**Comment by jawj** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
@ziyeqinghan Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@jawj Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@jawj Can you please resolve conflicts? Thanks!

**Comment by jawj** [comment]
All I did was change some index numbers in a way that fixed things for me at the time. I don't fully understand the changes that conflict here, so I'm not the right person to fix the conflict.

**Comment by gbaned** [comment]
Hi @jawj  Please click on the resolve conflicts button and check the lines of the code.  Thank you.

**Comment by jawj** [comment]
Sorry, again, I don't think I'm the right person to decide which of those is now the right approach. If this problem has been fixed elsewhere in the codebase — and I'm not sure if it has — then perhaps this PR can be closed.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!  Thank you!

**Pull request closed without merging**
