### PR TITLE
Upgrade nanopb to latest release.

### PR DESCRIPTION
**Pull request by mihaimaruseac**
Fixes security vulnerability reported in #37011

PiperOrigin-RevId: 297248686
Change-Id: Ib24b109c8a36b8673842b2f2ebb771406e5fa022

### CODE REVIEW

**Comment by npanpaliya** [comment]
@mihaimaruseac - 
grpc used in TF doesn't work with nanopb 0.4.1. I also tried updating grpc to 1.27.0 but it fails at bazel fetch step. 
I'd tried updating nanopb to 0.3.9.5 tag which also has the security fix and also works with TF 2.1 and TF 1.15.2.

**Comment by mihaimaruseac** [comment]
@npanpaliya is this for master, for 2.1 branch or in general?

**Comment by mihaimaruseac** [comment]
Guess I'll have to actually build and test each of the versions. Do you have a test case?

**Comment by npanpaliya** [comment]
No, I don't know any tests yet. I'm trying to find out.

BTW, if we update grpc in TF to 1.24 or above, we don't even need to update nanopb as nanopb has been removed from 1.24 version of grpc. https://github.com/grpc/grpc/commit/7ec6e8a4de6eba4eb3a8298ceb5aa82c0209b3a1. 
If there is no specific reason for using grpc 1.19.x in TF and we can safely update that to higher version, the issue itself gets resolved.

**Comment by npanpaliya** [comment]
> @npanpaliya is this for master, for 2.1 branch or in general?

I checked 1.15.2 and 2.1. Both fails with nanopb 0.4.1.

**Comment by mihaimaruseac** [comment]
Thank you for the updates. I'll hold off on merging these for now. Is master ok? I haven't seen an issue there (where nanopb update was merged)

**Comment by npanpaliya** [comment]
TF's master branch is working fine because it has grpc updated too. grpc used in master branch is 1.27.0-pre1 which doesn't use nanopb at all. 
In TF, is there any other external package other than grpc which uses nanopb? If not, then I think we can remove nanopb from workspace.bzl file. And that means the security issue reported originally gets invalidated.

**Comment by mihaimaruseac** [comment]
Thanks. I'll take a look on nanopb usages and update accordingly.

**Comment by npanpaliya** [comment]
@mihaimaruseac - Did you get a chance to look at this?

**Comment by mihaimaruseac** [comment]
This is not on master and won't be merged except when we need to do a patch release for 2.1

As such, looking at thisis down-prioritized to up until we need to release the patch. We won't merge this until then

**Comment by mihaimaruseac** [comment]
It fails to build, indeed. I will try removing it from master too.

**Pull request closed without merging**
