### PR TITLE
Remove the files that are moved to be http_util*.

### PR DESCRIPTION
**Pull request by gunan**
During my push, the files were not correctly deleted. removing them now to fix windows cmake and pip tests.

### CODE REVIEW

**Review by caisq — APPROVED** [review]

**Comment by gunan** [comment]
@drpngx this should fix the test failures.

**Comment by gunan** [comment]
Makefile build had an infra flake.
Here is a rerun:
http://ci.tensorflow.org/job/tensorflow-pull-requests-makefile/7196

**Comment by gunan** [comment]
2nd android test passed.
Merging.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (103/100 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:37045 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWmhs-0032Hx-9p
	for greg@biomassiv.es; Thu, 26 Jan 2017 10:15:28 -0600
Date: Tue, 24 Jan 2017 15:18:24 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485299904;
	bh=5KqpkhvT0Jowyy04cRYHmhNyRwy2PibpYfjLgluSJAo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=xRnVNCFawKBZcqQha/2zvjw5Ko0z0suKLCB/lnuelCxw+SY1veUlVijTjc/97nSdU
	 nFBYCU9ufmCLHgMoeADxZmKudd5ivjYH58MVNrJ41p5VikoObbK/05hfZV3qFrwUTM
	 qDFfJ72XSBO2EqnBhtJB40DXqLG+Dv7FWaZ94LcU=

**Pull request merged**
