### PR TITLE
Added Oxford comma in README.md

### PR DESCRIPTION
**Pull request by AlexanderTheGreat**
Added an Oxford comma to line 28, to be consistent with the rest of the file.

### CODE REVIEW

**Comment by Yoshimitsu** [comment]
I signed it!

**Comment by xinye-ohio** [comment]
test

**Comment by rthadur** [comment]
@Yoshimitsu thank you for your contribution , i don't think we need this change.

**Comment by lamberta** [comment]
Hi Alex, thanks for the PR and improving the docs!
I think this is a good change and is in line with the Google Developer Docs style guide: https://developers.google.com/style/commas

**Review by lamberta — APPROVED** [review]
Thanks!

**Pull request merged**
