### PR TITLE
Fix crash in GPU SparseToDense when validate_indices is false.

### PR DESCRIPTION
**Pull request by nluehr**
This essentially extends the fix from commit 23c6926c4e4 to the
validate_indices=false code path.

CC: @reedwm

### CODE REVIEW

**Comment by reedwm** [comment]
I don't think the fix is necessary on the validate_indices=false path. The reason it was necessary on the validate_indices=true path is because we passed a lambda to `event_mgr->ThenExecute` and had to ensure the tensor was still in scope when the lambda was eventually used. But the validate_indices=false path currently does not use a lambda, and does not need to use the tensor after the function returns, so I don't think the issue can occur on that path.

**Comment by nluehr** [comment]
Prior to this fix we observed intermittent CUDA segfaults during training when validate_indices was false. (this was in a TF1 model with identical SparseToDense GPU implementation)

**Comment by reedwm** [comment]
Calling `event_mgr->ThenExecute` effectively causes a GPU synchronization to occur before the op after SparseToDense can execute, which perhaps is causing some race condition to not occur, fixng the segfault. I don't think SparseToDense is the cause though.

If you give us an example to reproduce, we might be able to find where the segfault is coming from. But if the example is too large, there's a good chance we won't have time to debug it, unfortunately.

**Comment by gbaned** [comment]
Hi @nluehr Can you please check @reedwm's comments and keep us posted ? Thank you!

**Pull request closed without merging**
