### PR TITLE
[Windows/CMake] Add more error checking to the CI script.

### PR DESCRIPTION
**Pull request by mrry**

### CODE REVIEW

**Comment by mrry** [comment]
Not sure if this works just yet, but I wanted to run it through the CI....

**Comment by mrry** [comment]
Hmm, this didn't seem to help... I got a passing build by rerunning manually (http://ci.tensorflow.org/job/tensorflow-pr-win-cmake-py/139/) but it looks like it didn't run `ctest` :(.

**Comment by gunan** [comment]
Maybe it will work after #5656

**Comment by gunan** [comment]
Derek, could you rebase and merge the latest changes for version independence?

**Comment by mrry** [comment]
@gunan Looks like it's still not working the way I expected... I'll table this one for now (because hopefully your other fix will make the tests green).

**Review by gunan — APPROVED** [review]

**Comment by mrry** [comment]
@gunan This seems to fix the Windows CMake tests, by applying one of the known workarounds for the `easy-install.pth` bug. All the other failures seem to be caused by some unrelated bug in `tf.learn`.

**Comment by gunan** [comment]
thank you!!!!!

**Comment by gunan** [comment]
only dnn_test failure on the way.
merging right away!

**Review by gunan — APPROVED** [review]

**Pull request merged**
