### PR TITLE
Checks for integer overflow in function tf.convert_to_tensor() ---->

### PR DESCRIPTION
**Pull request by Sarvesh-Kesharwani**
i added a conditional check if input value to "tf.convert_to_tensor(a, tf.int32)" is not exceeding int32 limit, if dtype is int32.

closes issue https://github.com/tensorflow/tensorflow/issues/58994

### CODE REVIEW

**Comment by Sarvesh-Kesharwani** [comment]
guys please guide me further as this is my first PR.
i'll be grateful for your support. thankyou

**Review by mihaimaruseac — COMMENTED** [review]
I think the overflow fixes have to be in C++, not in Python

**Comment by Sarvesh-Kesharwani** [comment]
hi, mihaimaruseac 
thanx for replying, i was stuck findivg what i am doing wrong.
i guess i will be able to make some progress now.
thanx

**Comment by edwardyehuang** [comment]
> I think the overflow fixes have to be in C++, not in Python

Agree. The example below is also dangerous.

'''
import tensorflow as tf

a = 2147483647
a = tf.convert_to_tensor(a, tf.int32)

print(a) # tf.Tensor(2147483647, shape=(), dtype=int32)

b = a + tf.constant(1, tf.int32)

print(b) # tf.Tensor(-2147483648, shape=(), dtype=int32)
'''

**Comment by gbaned** [comment]
@Sarvesh-Kesharwani Can you please resolve conflicts? Thank you!

**Comment by Sarvesh-Kesharwani** [comment]
> @Sarvesh-Kesharwani Can you please resolve conflicts? Thank you!

sure

**Comment by Sarvesh-Kesharwani** [comment]
> This PR is now just adding a single empty line

I regret to inform you that I am currently unable to dedicate enough time to familiarize myself with the required code base for this PR. As a result, I will have to close this PR.

**Pull request closed without merging**
