### PR TITLE
Optimised Images

### PR DESCRIPTION
**Pull request by agarwalutkarsh554**

### CODE REVIEW

**Comment by agarwalutkarsh554** [comment]
@googlebot I signed it!

**Comment by agarwalutkarsh554** [comment]
@googlebot I consent.

**Comment by agarwalutkarsh554** [comment]
@googlebot I consent

**Comment by gbaned** [comment]
@agarwalutkarsh554  Can you please sign CLA. Thanks!

**Comment by agarwalutkarsh554** [comment]
I have already signed it please check

**Comment by gbaned** [comment]
@agarwalutkarsh554 Can you please make sure to use same GitHub username and email-id associated with it.

**Comment by mihaimaruseac** [comment]
What is the purpose of this PR?

**Comment by gbaned** [comment]
@agarwalutkarsh554 Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Pull request closed without merging**
