### PR TITLE
enable double precision for SparseTensorDenseMatMul on GPU

### PR DESCRIPTION
**Pull request by bendavid**
Trivial changes (just adding some extra macro calls)

### CODE REVIEW

**Comment by bendavid** [comment]
I signed it!

**Review by drpngx — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
@bendavid it looks like there are build errors. Could you take a look?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
