### PR TITLE
added //tensorflow/cc:cc_ops to //tensorflow:libtensorflow.so

### PR DESCRIPTION
**Pull request by memoakten**
Hey, I've wrapped tensorflow into openframeworks (http://openframeworks.cc/ ) was a massive PITA but more on that later :)

I needed the c++ ops so I added that to the libtensorflow.so target. I believe this is the right way to do it?
(I can confirm that it does work, I can create graphs in openframeworks. I'll make it all public once i've ironed out a few other things)

### CODE REVIEW

**Comment by memo** [comment]
I signed it!

**Comment by vrv** [comment]
@keveman @josh11b for more thoughts.

At a first glance, it might be better to create a separate target for this.  libtensorflow.so is, I think, meant to hold the core TF library.  cc_ops are just an API for defining the graph, which isn't really part of the core, so I'd be worried about conflating the two.

**Comment by memo** [comment]
ah ok, fair enough. initially I did have it separate, but wasn't sure what to call it. I thought libtensorflow would be the lib of all of tensorflow, and the core would perhaps be libtensorflowcore? alternatively libtensorflow could stay as just core, and libtensorflowcc could be core+cc? either way works for me.

**Comment by keveman** [comment]
The library for the graph building C++ API should be distinct and separate from libtensorflow.so, IMO. Perhaps make a separate libtensorflow_cc.so target for it?

**Comment by memo** [comment]
ok i've separated into a new target. libtensorflow.so is as it was before, libtensorflow_cc.so is core+cc. (i've also merged from upstream so it's up to date)

**Comment by vrv** [comment]
ping for @keveman

**Comment by keveman** [comment]
I was recommending separate library for building C++ ops, i.e., libtensorflow_cc.so containing only cc (not core + cc). But that's my opinion. Perhaps @josh11b can chime in?

**Comment by memo** [comment]
Hi @keveman I actually tried that but was getting errors when running. I can't remember the error exactly but something like "could not start DEFAULT_SESSION". Not sure if that's a bug of an error on my side?

**Comment by josh11b** [comment]
My recollection is that the library for building C++ ops depends on things like core/graph/graph_def_builder, which has other dependencies in core.  Were you thinking that libtensorflow_cc.so would have a dependency on the core so?

**Comment by keveman** [comment]
Yes, libtensorflow_cc.so will have a dependency on libtensorflow.so.

**Comment by vrv** [comment]
Hi @memo: is this still being worked on / ready to look at?

**Comment by memo** [comment]
it's just a tiny change to the build file to add a lib with core+cc. I last used this build target 4 days ago to build 0.7 libs for linux and osx. ( https://github.com/memo/ofxMSATensorFlow ) . Just now updated my branch.

**Comment by vrv** [comment]
Okay, sorry for the delay (our test machines were down).  can you re-merge one more time and squash the commits for one last look?

**Comment by memo** [comment]
ok up to date and commits cleaned up

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
Merged

**Pull request closed without merging**
