### PR TITLE
Add return statement to the micro-test framework.

### PR DESCRIPTION
**Pull request by jenselofsson**
Return kTfLiteOk/kTfLiteError depending on if the test succeeded or not.

### CODE REVIEW

**Comment by jenselofsson** [comment]
@petewarden Ping for review!

**Review by njeffrie — APPROVED** [review]
Interesting, was this causing compilation issues? I can imagine some toolchains will complain about no return value from main.

**Comment by rthadur** [comment]
@jenselofsson can you please check below error 

`tensorflow/lite/micro/examples/magic_wand/gesture_predictor_test.cc:66:1: error: use of undeclared identifier 'kTfLiteOk'
TF_LITE_MICRO_TESTS_END
^
.//tensorflow/lite/micro/testing/micro_test.h:88:12: note: expanded from macro 'TF_LITE_MICRO_TESTS_END'
    return kTfLiteOk;                                          \
           ^/tensorflow/lite/micro/examples/magic_wand/gesture_predictor_test.cc:66:1: error: use of undeclared identifier 'kTfLiteError'
.//tensorflow/lite/micro/testing/micro_test.h:91:12: note: expanded from macro 'TF_LITE_MICRO_TESTS_END'
    return kTfLiteError;                                       \
           ^
2 errors generated.`

**Comment by jenselofsson** [comment]
@njeffrie If I recall correctly, it have more to do with the fact that we want to use the return value to see if the test failed or not, although what you mention is a bonus.

**Pull request merged**
