### PR TITLE
Branch 173194115

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by caisq** [comment]
The Android build failure is preexisting and the Linux XLA build failure is unrelated tool failure. Should be okay to merge, @benoitsteiner

**Comment by caisq** [comment]
Ping @benoitsteiner 
@tensorflow-jenkins test this please

**Comment by benoitsteiner** [comment]
@caisq: My apologies, I didn't notice your PR earlier. #13976 is a superset of your PR, isn't it ?

**Comment by caisq** [comment]
@benoitsteiner OK. Thanks for the update. I'll close this PR, then.

**Pull request closed without merging**
