### PR TITLE
Add stream selection support for `tf.contrib.ffmpeg.decode_audio`

### LINKED ISSUE #16073: Feature request: (optionally) return all audio streams in tf.contrib.ffmpeg.decode_audio
I'm trying to read [musdb18](https://sigsep.github.io/musdb.html) with `tf.data` and it comes in the form of mp4 files with multiple audio streams so `ffmpeg -map` is needed.

`tf.contrib.ffmpeg.decode_audio` cannot be configured to choose the audio stream. I wonder if we could have a `tf.contrib.ffmpeg.decode_audios` that returns every audio stream in the file, or if we could have a new argument in `tf.contrib.ffmpeg.decode_audio` for choosing streams.

Being able to choose the audio stream is also important for getting the right language in a movie file's audio, and similarly `tf.contrib.ffmpeg.decode_video` could need the same extension (though multiple video streams is not as common AFAIK).

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #16073 where it was not possible to selectively decode a perticular stream with `tf.contrib.ffmpeg.decode_audio`.
This fix adds an additional attribute `stream` which could be used to specify the stream to decode (e.g., `stream="1"`). By default `stream=""` which leaves the decision to ffmpeg.

This fix fixes #16073.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by carlthome** [comment]
LGTM!

**Comment by carlthome** [comment]
Do you think it would be good for API symmetry to have the same extension for `tf.contrib.ffmpeg.decode_video` or is that excessive? I can't think of many video files with multiple streams but what do I know?

**Comment by yongtang** [comment]
@carlthome I think it makes sense to have stream selection support for `decode_video` as well. Let me  take a look.

**Comment by yongtang** [comment]
Actually there is a bug in `decode_video` that causes it to not run correctly. I have created a separate PR #16105 to fix it, as it is a bug (not a feature request).

I will work on follow up PR for stream selection support for `decode_video` once #16105 is merged.

**Comment by faroit** [comment]
@yongtang maybe I am missing this, but is there a way to get the number of available substreams so that users can iterate over all substreams?

**Comment by carlthome** [comment]
Similarly, being able to set a time offset and duration would be nice (i.e. ffmpeg `-ss 00:03:00` and `-t 60` for being able to only decode parts of longer movies and audio files, so you can work through a folder of files in reasonable segments, but maybe that is best to think about in a separate issue.

**Comment by yongtang** [comment]
@carlthome @faroit I think it might be possible to have another op (e.g., `video_info`) so that any video related information (e.g., number of streams, length, etc.) is accessible. I can work on creating another PR if this PR is merged.

**Comment by fredbertsch** [comment]
This looks great! Thanks for doing this. Unfortunately, merging this will break our internal build. I'm going to create an internal change that we can synchronize with this one.

**Review by fredbertsch — APPROVED** [review]
LGTM. I've got a parallel change that will happen internally, so I'll merge this PR once that's in flight.

Thank you very much for the added capability! :)

**Comment by yongtang** [comment]
@fredbertsch Thanks for the help! 👍 🎉

**Comment by rmlarsen** [comment]
Please have a look at the test failures, e.g.

https://source.cloud.google.com/results/invocations/87ffa93c-e04d-463d-8b1d-5bd68486b076/targets/%2F%2Ftensorflow%2Fcontrib%2Flayers:layers_test/log

```
  File "/tmp/botexec/bazel-out/k8-py3-opt/bin/tensorflow/contrib/layers/layers_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 1617, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): output_shape has incorrect number of elements: 23 should be: 3
	 [[Node: SparseToDense = SparseToDense[T=DT_INT64, Tindices=DT_INT64, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dense_to_sparse/Where, dense_to_sparse/GatherNd, dense_to_sparse/Shape, SparseToDense/default_value)]]
```

**Comment by yongtang** [comment]
@rmlarsen I run though the test of `//tensorflow/contrib/layers:layers_test` but it passed. Is the failure related to another PR?

**Comment by yongtang** [comment]
The PR #16696 adds the stream selection support for `tf.contrib.ffmpeg.decode_video`.

**Pull request merged**
