### PR TITLE
Add Pillow installation into Docker build file.

### PR DESCRIPTION
**Pull request by foreverfaint**
@caisq this is a new PR related to [PR #5693 install Pillow in Dockerfile](https://github.com/tensorflow/tensorflow/pull/5693). 2 commits are incorprated:
1. add Pillow installation into tensorflow/tools/docker/Dockerfile
2. add Pillow installation into tensorflow/tools/docker/Dockerfile.gpu

the following information for image size comparison:

**gpu version image size drops, i guess latest-gpu tagged image is too old.**

> REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
> gcr.io/tensorflow/tensorflow   gpu                 8ca00ec56643        8 minutes ago       2.658 GB
> gcr.io/tensorflow/tensorflow   latest-gpu          dd645f420f1d        10 days ago         2.713 GB

**cpu version image size increases about 22MB < 2.5% up**

> REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
> gcr.io/tensorflow/tensorflow   Pillow              dff6ac3189bd        17 hours ago        981.6 MB
> gcr.io/tensorflow/tensorflow   latest              5547120ff897        10 days ago         959.6 MB

Hao

### CODE REVIEW

**Comment by foreverfaint** [comment]
@googlebot try again, hope it works now.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@foreverfaint , can you look into the CLA issue again. I'll merge the PR as soon as the CLA is good. Thanks.

**Comment by foreverfaint** [comment]
@caisq, is it still not working for CLA? previously i typo a wrong name in my local git config for email part " foreverfailt@gmail.com". For resolving this issue, i did create a gmail for foreverfailt@gmail.com, and signed CLA by that email too. so for now i have the signed CLA for both author names:
* foreverfaint@gmail.com
* foreverfailt@gmail.com
so what is a further step i should follow?

**Comment by caisq** [comment]
I guess the reason why CLA doesn't work is the second commit:

install Pillow in Dockerfile
root committed ....

You used user root to do the commit, which the CLA bot doesn't recognize. Maybe open another PR to include one commit with the correct user name?

**Comment by foreverfaint** [comment]
sure. let me do it again. close this one

**Pull request closed without merging**
