### PR TITLE
Added CMSIS-NN specialization for fully connected op.

### PR DESCRIPTION
**Pull request by freddan80**
The optimized implementation requires temporary buffer space,
therefore a buffer was defined. The buffer is however a
temporary solution until there's a way to add this buffer to
the memory planner in the prepare phase of the op.

Change-Id: I4faf9010b723e3ced6ef1a1af94f2a524df64c61

### CODE REVIEW

**Comment by freddan80** [comment]
@wangtz , let me know what you think

**Review by petewarden — APPROVED** [review]
I think it makes sense to get this in as-is, since we don't yet have the scratch buffer API.

**Review by njeffrie — COMMENTED** [review]
I mistakenly thought this was for conv in my previous comment.  Looks good to me.

**Comment by freddan80** [comment]
Can someone please re-run this tests. They should not be affected by this change.

**Comment by freddan80** [comment]
Hi! The "Ubuntu CC" seems broke. For all PR's, it seem to be in "Expected — Waiting for status to be reported" state.

**Pull request merged**
