### PR TITLE
Fix bug 17175

### PR DESCRIPTION
**Pull request by ipeirotis**
Fix bug reported at https://github.com/tensorflow/tensorflow/issues/17175

### CODE REVIEW

**Comment by ipeirotis** [comment]
I signed it!

**Comment by ipeirotis** [comment]
Used incorrect email in earlier commit. Fixed it.

**Comment by ipeirotis** [comment]
Any idea why the "Ubuntu CC" check takes so long?

**Review by ebrevdo — APPROVED** [review]

**Comment by ipeirotis** [comment]
@ebrevdo Any idea why the tests take so long? 

For the first commit (https://github.com/tensorflow/tensorflow/pull/17283/commits/0a4bad1a79e60718dc8620e1213adaa4bcc9d0fe) it finished in a few hours with all the 15 tests. Now it seems stuck with the Ubuntu CC test

**Comment by ebrevdo** [comment]
Should improve by tomorrow.

**Comment by ipeirotis** [comment]
@ebrevdo Can we get a forced run of the tests?

**Comment by protoget** [comment]
Re @ipeirotis running tests.

**Pull request merged**
