### PR TITLE
Adding reading op for hadoop sequence file format (very basic version though).

### PR DESCRIPTION
**Pull request by rosun82**
This CL allows tensorflow to be able to read tf.Example stored in Hadoop sequence file, which is the one of the well supported output format in the Hadoop eco system (comparing to recordio or sstable).

This enables one to write Hadoop mapreduce in the familiar way, producing tf.Example, storing them into standard output format (on S3 for example), and invoke tensorflow, avoiding the expensive, and sometimes confusing step of converting from Hadoop format into recordio.

To keep things simple, there are some limitations in this implementation:

1. no compressed sequence file (not a big issue if the records are already serialized protos)

2. SEQ5 or SEQ6 format.

3. The value in the sequence file must be encoded using org.apache.hadoop.io.BytesWritable, no text or other format, as the primary goal is to read tf.Example protos stored therein.

Please help me to get this into tensorflow. Thank you.

### CODE REVIEW

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by rosun82** [comment]
Could someone please help me getting the Windows test right? Seems the failure has nothing to do with my change.

**Comment by caisq** [comment]
@rosun82 The windows failure doesn't have anything to do with your change.

Gentle ping @jhseu

**Comment by jhseu** [comment]
Can we add this as a Dataset instead? https://www.tensorflow.org/programmers_guide/datasets

**Comment by martinwicke** [comment]
(from API review)

+1 to @jhseu's comment. Let's make this available for DataSets. No concerns adding this type of reader there.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 45 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
