### PR TITLE
Update tensorflow to use new version of protobuf library

### PR DESCRIPTION
**Pull request by andrewharp**
This is necessary to remove the need for libpthread workarounds when building binaries for Android (as seen in tensorflow/examples/android/BUILD).

### CODE REVIEW

**Comment by andrewharp** [comment]
@googlebot I signed it!

**Comment by andrewharp** [comment]
@tensorflow-jenkins: test this please

**Comment by andrewharp** [comment]
@martinwicke @vrv Is there a way to view the failing test.log files for this PR? I'm also getting 233 test failures when I try to test a clean copy of master locally:

```
File "/usr/local/google/home/andrewharp/.cache/bazel/_bazel_andrewharp/111e4735042cad380f0b87cff4bce3f6/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/user_ops/ackermann_test.runfiles/google/protobuf/symbol_database.py", line 180, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: 'module' object has no attribute 'Default'
```

And 233 test failures locally with this branch, but with a different error:

```
File "/usr/local/google/home/andrewharp/.cache/bazel/_bazel_andrewharp/7d6b411acf30faa7da8a8cd3f21cf053/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/user_ops/ackermann_test.runfiles/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name descriptor


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

**Comment by andrewharp** [comment]
Also, just switching branches gives me issues where it thinks I have a pending commit to google/protobuf. 

If I'm on my local master branch and do "git checkout update_pb_lib" and it tells me I have a pending commit to google/protobuf (it wants to make it go back to using the old version).

Then I do "git checkout update_pb_lib -- google/protobuf" because I want to revert this unwanted commit and use the version I selected in "update_pb_lib", but it just ignores it and the pending commit remains active. I assume git is treating it differently from a regular file because it's actually a submodule, but I'm not sure how I'm supposed to switch local branches cleanly with this behavior.

**Comment by andrewharp** [comment]
It seems like `git submodule update --init --recursive` does the trick to wipe the pending commit.

**Comment by andrewharp** [comment]
@tensorflow-jenkins: test this please

**Comment by andrewharp** [comment]
@davidzchen 
I've updated my to get past the initial build errors related to https://github.com/google/protobuf/commit/985c968443e5124327fb600a91856192df4476ac, but now I get this:

> ImportError: Traceback (most recent call last):
>   File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-fastbuild/bin/tensorflow/python/string_to_number_op_test.runfiles/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.core.framework.graph_pb2 import *
>   File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-fastbuild/bin/tensorflow/python/string_to_number_op_test.runfiles/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
>     from google.protobuf import descriptor as _descriptor
> ImportError: cannot import name descriptor

Does anything stand out to you that I might be missing here? I'm not sure how it's finding google.protobuf and not descriptor google.protobuf.descriptor, given that your PR didn't do anything to descriptor specifically.

**Comment by davidzchen** [comment]
That's odd. I'll try to reproduce and debug this. I also saw your comment on my PR. Are you still having that issue as well?

By the way, would it be possible to merge #1289 first? That way, we can update the protobuf dependency more easy since all we would need to do is update the WORKSPACE file rather than having to update the submodule reference. The failures in the last CI run on #1289 don't seem to be related to that PR.

**Comment by andrewharp** [comment]
Thanks! Adding the extra parameters to our skylark macro calls to point it to protoc and protobuf_library fixed the original errors I mentioned in your PR. Though I suppose it's possible I did that incorrectly, leading to the current descriptor error.

@vrv What do you think about getting #1289 in?

**Comment by vrv** [comment]
Sure, making protobuf a workspace dep looks good.  Enough bazel improvements have occurred to force users to upgrade at this point (and we can now detect the version)

**Pull request closed without merging**
