### PR TITLE
Fixed 32-bit build error in tensor_forest.

### PR DESCRIPTION
**Pull request by alistair-low**
This patch fixes the build error described in #11229.

### CODE REVIEW

**Comment by alistairlow** [comment]
I signed it!

**Comment by alistairlow** [comment]
Fixed the CLA to include my work email in addition to my personal one. I signed it!

**Comment by gilberthendry** [comment]
Thanks for finding this!  The change actually isn't the best solution, so I'll fix this internally.  Should be committed in a day or so.

**Comment by aloisklink** [comment]
Hi @gilberthendry,

I'm not sure if you've fixed this yet, but it seems to me that 
``` c++
typedef Eigen::TensorMap<
    Eigen::Tensor<const float, 1, 1, long>, 0>  // NOLINT(runtime/int)
    SingleDimStorageType;
```
at `tensorflow/contrib/tensor_forest/kernels/v4/input_target.h:23`
should be replaced with:
``` c++
typedef Eigen::TensorMap<
    Eigen::Tensor<const float, 1, 1, Eigen::DenseIndex>, 0>  // NOLINT(runtime/int)
    SingleDimStorageType;
```
to match
``` c++
template <typename T, int NDIMS = 1, typename IndexType = Eigen::DenseIndex>
struct TTypes {
// Rank-<NDIMS> tensor of scalar type T.
typedef Eigen::TensorMap<Eigen::Tensor<T, NDIMS, Eigen::RowMajor, IndexType>,
Eigen::Aligned> Tensor;
```
at `tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor_types.h:24`

Be aware `Eigen::DenseIndex` has been depreciated as of [Eigen 3.3.0](http://eigen.tuxfamily.org/index.php?title=3.3) and should be replaced by `Eigen::Index`, so it might be worth sticking `Eigen::Index` in there instead.

**Comment by gilberthendry** [comment]
Actually I replaced it with tensorflow::TTypes<float, 1>::ConstTensor, which is more portable I think.

**Comment by aloisklink** [comment]
4de7361c43adc65c442359104a17c449a02eee7a and 14101a8ba173b44179b2a9317781f140eb61b0a1 seems to have fixed this issue for me, I managed to successfully compile and run Tensorflow on a 32-bit Raspberry Pi 3. Cheers @gilberthendry for fixing this bug!

**Comment by alistairlow** [comment]
Yes, thanks @gilberthendry! I'm closing my pull request now

**Pull request closed without merging**
