### PR TITLE
add assert_element_shape method for tf.contrib.data

### LINKED ISSUE #16052: Feature Request: Setting the shape of a tf.data.Dataset if it cannot be inferred
Hello, I have really liked the new `tf.data.Dataset` api, and had a feature request. 
I need to often make data transformations that require third-party libraries, and use `Dataset.map` along with a `tf.py_func` command as shown in the Importing Data tutorial. In the process of doing this, Tensorflow is not able to infer the shape of the numpy arrays that are returned by the py_func-based functions, and so the output_shapes attribute of the dataset returns something like `(TensorShape(None), TensorShape(None), TensorShape(None), TensorShape(None), TensorShape(None))`

To address this, I have been adding a new map function after that calls set_shape on each tensor to enforce the shape requirement. For example, I have code that looks something like this:

```
dataset = dataset.map(lambda strings, labels: tuple(tf.py_func(_featurize, [strs, labels], [tf.int32, tf.float64, tf.int32, tf.int32, labels.dtype])))
dataset = dataset.map(_set_shapes)
```
where 
```
def _set_shapes(af, pf, split, atp, labels):
    af.set_shape([None, 75])
    pf.set_shape([None, 14])
    split.set_shape([None, ])
    atp.set_shape([None, 2])
    labels.set_shape([None, ])
    return af, pf, split, atp, labels
```

Could this be simplified by adding a new `tf.data.Dataset` member function called "set_dataset_shape" which essentially just implements the above _set_shapes method?

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: AWS Deep Learning AMI
- **TensorFlow version (use command below)**: 1.4
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: AWS Deep Learning AMI-based
- **GPU model and memory**: NVIDIA K80
- **Exact command to reproduce**: N/A

### PR DESCRIPTION
**Pull request by facaiy**
fix #16052. 

```python
shapes = [tf.TensorShape([16, 256]), tf.TensorShape(None)]
result = dataset.apply(tf.contrib.data.assert_element_shape(shapes))
print(result.output_shapes)  # ==> "((16, 256), <unknown>)"
```

### CODE REVIEW

**Comment by facaiy** [comment]
@frankchn Thanks, I have fixed the code style. Could you help restart all tests?

**Review by mrry — CHANGES_REQUESTED** [review]
This seems like a useful addition, but I would expect a method called `assert_element_shape` to raise an error if the assertion did not hold. Can you implement this with a `Dataset.map()` that uses `tensor_util.with_shape()` to add ops that check the shape at runtime if necessary?

**Comment by facaiy** [comment]
Sure, I'd like to work on it later.

**Comment by facaiy** [comment]
@mrry Hi, the behavior required has been added, and now `assert_element_shape` will raise an error if the assertion didn't not hold. Could you take a look again?

**Review by mrry — APPROVED** [review]
Thanks looks great! Thanks for the contribution, and for making the requested changes!

**Comment by facaiy** [comment]
@mrry Thanks for your approval. My bad, I have fixed the code style, and could you help restart all tests?

**Comment by facaiy** [comment]
Thanks. All tests pass.

**Comment by mrry** [comment]
Thanks again!

**Comment by dhdaines** [comment]
Is there any equivalent to this in TensorFlow 2? Even the 1.15 docs seem to indicate that we are not supposed to use it.  It is actually useful.

**Comment by facaiy** [comment]
@dhdaines Hi, David, would you please file a new issue for it? Thanks :-)

**Pull request merged**
