### PR TITLE
Added support for new fused Winograd algorithms in cudnn 5.1

### PR DESCRIPTION
**Pull request by benbarsdell**

### CODE REVIEW

**Comment by zheng-xq** [comment]
LGTM. 

@tensorflow-jenkins, test this please.

**Comment by zheng-xq** [comment]
@benbarsdell, conv_ops_test is failing on jenkins with this CL. Could you confirm that it runs well for you locally with Cuda 7.5 + Cudnn 5? Thanks. 

The log is here: 
https://ci.tensorflow.org/job/tensorflow-pull-requests-gpu/2119/consoleFull

If you cannot see it, this is the relevant portion: 
FAIL: testInceptionBackFilter_4 (__main__.Conv2DTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/conv_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/conv_ops_test.py", line 1272, in Test
    strides, padding)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/conv_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/conv_ops_test.py", line 569, in _CompareBackFilter
    self.assertAllClose(values[0], values[i], rtol=1e-4, atol=1e-4)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/conv_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 449, in assertAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001

(mismatch 5.26315789474%)
 x: array([[[[ 46.046501,  45.859997,  56.073101, ...,  45.907337,  51.214821,
           44.84082 ],
         [ 47.817616,  42.558422,  52.609974, ...,  45.89362 ,  46.778015,...
 y: array([[[[ 33.582195,  36.529572,  56.073128, ...,  45.90733 ,  51.214813,
           44.840816],
         [ 35.047573,  32.791656,  52.609985, ...,  45.893631,  46.778004,...

**Comment by benbarsdell** [comment]
Sorry for the delay, I'm in the process of looking into this failure.

**Comment by drpngx** [comment]
SG, if you're interested in merging this at some point, please make sure you follow the instructions to sign the CLA.

**Comment by vrv** [comment]
@benbarsdell: if you have signed the CLA under your nvidia address, maybe git amend your commits to that?  It's currently set to your gmail account.

**Comment by vrv** [comment]
(clearing this out of our open PRs -- ping me or this thread when you want me to reopen after the CLA issues are resolved)

**Pull request closed without merging**
