### PR TITLE
Expose TFOptimizer in tf.keras.optimizers

### LINKED ISSUE #22466: Unable to use TFOptimizer from keras in tensorflow
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: NA
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: Running in colab, chrome
- **TensorFlow version (use command below)**: 1.10.1
- **Python version**: 2
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

### Describe the problem
Using TFOptimizer from keras inside tensorflow gives error - 
```
---> 22 opt = keras.optimizers.TFOptimizer(tf_opt)
     23 opt.lr = lr
     24 

AttributeError: 'module' object has no attribute 'TFOptimizer'
```

I manually imported it to make the code work-
```
from tensorflow.python.keras.optimizers import TFOptimizer
```

Could TFOptimizer class be exported from tensorflow in the following file-
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizers.py#L691

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue in #22466 where
TFOptimizer was not exposed in tf.keras.optimizers
like other optimizers.

This fix fixes #22466.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by qlzh727** [comment]
Please fix the API compatibility test by generate the pbtxt for the new API.

**Comment by yongtang** [comment]
Thanks @qlzh727. The PR has been updated with api compatibility tests passed. Please take a look.

**Comment by qlzh727** [comment]
@fchollet, please take a look.

**Comment by fchollet** [comment]
This class is not meant to be public. The issue linked is unrelated. That issue will be fixed separately with API changes at the level of TF optimizers (in progress).

**Pull request closed without merging**
