### PR TITLE
GPU DynamicPartition support int32&int64

### PR DESCRIPTION
**Pull request by xutianming**
Currently, DynamicPartitionOp on GPU doesn't support int32&int64. They were implemented but not registered. I tested them in my project and they worked fine.

### CODE REVIEW

**Comment by gbaned** [comment]
@sanjoy Any update on this PR? Please. Thanks!

**Comment by xutianming** [comment]
> @sanjoy Any update on this PR? Please. Thanks!

Anything I can do for this, such as adding some tests ?

**Review by sanjoy — APPROVED** [review]
I suspect DynamicPartition is not used in shape computations, so let's land this for now.  Should be simple to roll back in case we see perf regressions.

**Review by reedwm — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by xutianming** [comment]
@googlebot I fixed it.

**Comment by xutianming** [comment]
@gbaned @sanjoy @reedwm I fixed some failing tests. Please help merge this PR.

**Review by reedwm — APPROVED** [review]

**Comment by xutianming** [comment]
@kokoro-team test

**Pull request merged**
