### PR TITLE
Add AMD/ROCm build dependency for grapper/optimizer

### PR DESCRIPTION
**Pull request by rahulbatra85**
ROCm have some grappler/optmizer code that uses code from rocm_dnn.c. This commit updates the BUILD file to include that dependency

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Review by ezhulenev — APPROVED** [review]

**Comment by rthadur** [comment]
@rahulbatra85 could you please resolve conflicts!

**Review by rthadur — APPROVED** [review]

**Review by rthadur — APPROVED** [review]

**Comment by rahulbatra85** [comment]
Can this be merged?

**Comment by SandSnip3r** [comment]
I'm seeing a failure in our internal open source build.
[tensorflow/tsl/platform/default/rocm_rocdl_path.cc:23] fatal error: rocm/rocm_config.h: No such file or directory
   23 | #include "rocm/rocm_config.h"
      |          ^~~~~~~~~~~~~~~~~~~~
      
By the way, there's no description on this PR. What's the point? What is this solving and how?

**Comment by SandSnip3r** [comment]
Ping @rahulbatra85

**Comment by rahulbatra85** [comment]
> Ping @rahulbatra85

Hi sorry for the delay in responding. ROCm have some grappler/optmizer code that uses code from rocm_dnn.c. rocm_dnn.c is part of stream_executor which was recently moved to compiler/xla. That's why the dependency is broken again

Actually, we have the fix the in our ROCm fork. I will update this PR soon with that

**Comment by rahulbatra85** [comment]
@SandSnip3r  Can you review this?
Also, the ARM CI is failing for other PRs as well. I think that failure is unrelated.

**Review by SandSnip3r — APPROVED** [review]

**Comment by rahulbatra85** [comment]
@SandSnip3r 
Is this still failing like this
[tensorflow/tsl/platform/default/rocm_rocdl_path.cc:23] fatal error: rocm/rocm_config.h: No such file or directory
23 | #include "rocm/rocm_config.h"
| ^~~~~~~~~~~~~~~~~~~~

?

**Comment by akuegel** [comment]
It seems this PR needs to be synced again.

**Comment by rahulbatra85** [comment]
> It seems this PR needs to be synced again.

Done!

**Review by akuegel — APPROVED** [review]

**Pull request merged**
