### PR TITLE
Put working links for  Android build instructions

### PR DESCRIPTION
**Pull request by mohantym**
Put working link for "configuring your project for android builds" hyper link with "g3doc/android/lite_build.md"

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @JunyoungLim Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @JunyoungLim Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @JunyoungLim Can you please review this PR ? Thank you!

**Comment by mohantym** [comment]
Hi @JunyoungLim ! @gbaned 
Gentle bump on this PR. Can you point me towards the correct link then.
Thank you!

**Review by JunyoungLim — APPROVED** [review]

**Comment by JunyoungLim** [comment]
It's approved, so please submit it when all the checks pass!

**Comment by JunyoungLim** [comment]
There were some internal error while auto-submitting this PR; instead we submitted this change manually. The change is merged to the main branch, so I will close this PR.

**Pull request closed without merging**
