### PR TITLE
native Cuda kernel for tf.dynamic_stitch op

### PR DESCRIPTION
**Pull request by MycChiu**
Correspond to issue #7251 
Here is the comparison between 
my implementation:
dynamic_stitch_gpu
and current implementation:
dynamic_stitch_cpu
generated by Nvidia visual profiler with [this code](https://gist.github.com/MycChiu/c353fd3c98c47dceae866ed30f40a5a8). *Since the kernel uses `CudaDeviceArrayStruct`, which depends on code from `//tensorflow/core:lib`, I can't generate custom_op library and use the custom_op for performance comparison. I ended up manually switch the tensorflow directory python uses between runs*
Currently, I still have two problems:
1. For some reason, tensorflow won't use the GPU kernel automatically, I had to force it with `tf.device`. What's even worse, tensorflow seems to refuse loading the GPU kernel in `test_session()` even if I tried to force it with `tf.device`, so this code is currently not tested with `dynamic_stitch_test.py`.
~~2. As @yaroslavvb suggested, Cuda kernels need to be real-valued, so I ended up calling `TF_CALL_GPU_NUMBER_TYPES_NO_HALF(REGISTER_DYNAMIC_STITCH_GPU);` to register the kernel. However, I feel like this will break some people's current code if their input data is from the unsupported data type.~~ *fixed in the latest commit.*

Finally, this implementation is really under-optimized for cases where the size of each input data slice is small, because the indices are still processed by the CPU (plus CUDA reads data in warps of 32 threads). However, I still don't think it will be worse than processing everything on CPU then copy them back to GPU though.

### CODE REVIEW

**Comment by dandelionmane** [comment]
Not sure who the best reviewers are - added @girving and @yuanbyu, feel free to hot potato away if you're not the right reviewer. But we've let this sit for 14 days without any attention so we really should take a look promptly.

**Comment by girving** [comment]
I can review this.  Can you squash into a single CL before I start, since it looks like you undid some mistakes?

**Comment by MycChiu** [comment]
@girving Yes, I redirected inputs with datatypes not supported by current CUDA kernel implementation to CPU in the latest commit, but I think the latest commit reflects all the changes I made though? Or perhaps you and I are talking about different things?

**Comment by girving** [comment]
Squashing won't change the final diff, but it makes it easier to read all the changes together as I review them.  So please squash as I requested.

**Comment by MycChiu** [comment]
@girving Welp... Sorry, I think I F'ed up the rebasing part...I think it will be easier if I close this pull request and start a new one. I will tag you when I am done.

**Comment by yaroslavvb** [comment]
@MycChiu I believe you did `git pull` into your PR branch. Never do a `git pull`, only rebase :)

**Comment by MycChiu** [comment]
@yaroslavvb Haha, yes, that's indeed what I did. I will definitely keep this in mind next time, thank you!

**Pull request closed without merging**
