### PR TITLE
Cherrypicks for 1.5

### PR DESCRIPTION
**Pull request by av8ramit**
182804819 not found in github

### CODE REVIEW

**Review by gunan — DISMISSED** [review]

**Comment by av8ramit** [comment]
@gunan any idea of the fix for presubmits?

**Comment by gunan** [comment]
Could you also cherrypick 725d049caea2b75eae373760127ed9b55138f7dc

**Comment by av8ramit** [comment]
@yifeif can I merge this PR, or is a fix coming soon?

**Comment by yifeif** [comment]
Re-triggering

**Comment by gunan** [comment]
Looks like a flaky test?
```
[ RUN      ] FileBlockCacheTest.CoalesceConcurrentReads
tensorflow/core/platform/cloud/file_block_cache_test.cc:464: Failure
Value of: WaitForNotificationWithTimeout(&notification, 10000)
  Actual: false
Expected: true
Timeout waiting for concurrent thread to start.
[  FAILED  ] FileBlockCacheTest.CoalesceConcurrentReads (110 ms)
```

**Review by gunan — APPROVED** [review]

**Pull request merged**
