### PR TITLE
Fixes Issue #26197

### PR DESCRIPTION
**Pull request by drakegens**
Updated link to better documentation.

Happy Hacktoberfest :)

https://hacktoberfest.digitalocean.com/

https://github.com/tensorflow/tensorflow/issues/26197

### CODE REVIEW

**Review by adisakshya — DISMISSED** [review]

**Comment by drakegens** [comment]
Can this be merged in?

**Comment by gbaned** [comment]
@drakegens  Could you please address Ubuntu Sanity errors? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by drakegens** [comment]
Yes. Sorry i've been on vacation. I will look into resolving the Sanity errors

**Comment by drakegens** [comment]
Is this good to be merged?

**Review by tanzhenyu — APPROVED** [review]

**Pull request merged**
