### PR TITLE
Update RealDiv arguments

### LINKED ISSUE #59181: [Documentation] `raw_ops.RealDiv`: Input Tensors cannot be of integer dtype
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux WSL2 Ubuntu 20.04 LTS

### Mobile device

_No response_

### Python version

3.8.10

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current Behaviour?

```shell
The documentation for `tf.raw_ops.RealDiv` states that the input argument `x` must be a Tensor of types `bfloat16, half, float32, float64, uint8, int8, uint16, int16, int32, uint32, uint64, int64, complex64, complex128.` Upon usage, however, this op throws an exception when run with an input of any integer dtype when run on a CPU. The op only works for `float` and `complex` dtypes.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

dtype = "int64"
x = np.array([[1,2,4],[2,3,5]], dtype=dtype)
y = np.array([[1,2,4],[2,3,5]], dtype=dtype)
x = tf.constant(x, dtype=dtype)
y = tf.constant(y, dtype=dtype)
tf.raw_ops.RealDiv(
    x=x, y=y, name=None
)
```

### Relevant log output

```shell
---------------------------------------------------------------------------

NotFoundError                             Traceback (most recent call last)

<ipython-input-3-553c77700511> in <module>
      4 x = tf.constant(x, dtype=dtype)
      5 y = tf.constant(y, dtype=dtype)
----> 6 tf.raw_ops.RealDiv(
      7     x=x, y=y, name=None
      8 )

/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   7162 def raise_from_not_ok_status(e, name):
   7163   e.message += (" name: " + name if name is not None else "")
-> 7164   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   7165 
   7166 

NotFoundError: Could not find device for node: {{node RealDiv}} = RealDiv[T=DT_INT64]
All kernels registered for op RealDiv:
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
 [Op:RealDiv]
```
</details>

### PR DESCRIPTION
**Pull request by sachinprasadhs**
Update realDiv argument details to display only registered dtypes.
Fixes #59181

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @jpienaar / @rdzhabarov Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar / @rdzhabarov Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar / @rdzhabarov Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar / @rdzhabarov Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar / @rdzhabarov Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar / @rdzhabarov Can you please review this PR ? Thank you!

**Comment by jpienaar** [comment]
Same caveat as the other one, @changm may be able to help coordinate

**Comment by changm** [comment]
I think this may be a weird case where it's ok to update the generated file as I can't find how else it's done. Still looping in @rohan100jain for API changes.

**Comment by changm** [comment]
Actually I think you'd have to update [math_ops.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/math_ops.cc#L525) and run the instructions at the top of tf_generated.td to do the right thing.

**Comment by gbaned** [comment]
Hi @sachinprasadhs Can you please take a look on the above comment from @changm. Thank you!

**Comment by gbaned** [comment]
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

**Pull request closed without merging**
