### PR TITLE
Fixed the Windows build for TF Scala.

### PR DESCRIPTION
**Pull request by eaplatanios**
This PR introduces some changes that I found necessary when trying to support a windows build for TF Scala. Specifically, I added a build target for building `tensorflow_framework.lib` and made some changes to export some missing symbols that are used in the TF Scala checkpoint reader.

I also had a question: is there currently a single bazel build target that can be used for building `tensorflow.dll`, `tensorflow.lib`, `tensorflow_framework.dll`, and `tensorflow_framework.lib`, all at once? Thanks!

cc @alextp

### CODE REVIEW

**Review by alextp — DISMISSED** [review]

**Review by alextp — DISMISSED** [review]

**Comment by eaplatanios** [comment]
Also, there is one remaining linking error that I'm not sure how to fix:

```
error LNK2019: unresolved external symbol "class tensorflow::TensorShapeProtoDefaultTypeInternal tensorflow::_TensorShapeProto_default_instance_" (?_TensorShapeProto_default_instance_@tensorflow@@3VTensorShapeProtoDefaultTypeInternal@1@A) referenced in function "private: struct std::pair<class std::unique_ptr<class std::unordered_map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class tensorflow::TensorShape,struct std::hash<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct std::equal_to<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class tensorflow::TensorShape> > >,struct std::default_delete<class std::unordered_map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class tensorflow::TensorShape,struct std::hash<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct std::equal_to<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class tensorflow::TensorShape> > > > >,class std::unique_ptr<class std::unordered_map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,enum tensorflow::DataType,struct std::hash<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct std::equal_to<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,enum tensorflow::DataType> > >,struct std::defau
lt_delete<class std::unordered_map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,enum tensorflow::DataType,struct std::hash<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct std::equal_to<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,enum tensorflow::DataType> > > > > > __cdecl tensorflow::checkpoint::CheckpointReader::BuildV2VarMaps(void)" (?BuildV2VarMaps@CheckpointReader@checkpoint@tensorflow@@AEAA?AU?$pair@V?$unique_ptr@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VTensorShape@tensorflow@@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VTensorShape@tensorflow@@@std@@@2@@std@@U?$default_delete@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VTensorShape@tensorflow@@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VTensorShape@tensorflow@@@std@@@2@@std@@@2@@std@@V?$unique_ptr@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4DataType@tensorflow@@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4DataType@tensorflow@@@std@@@2@@std@@U?$default_delete@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4DataType@tensorflow@@U?$has
h@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4DataType@tensorflow@@@std@@@2@@std@@@2@@2@@std@@XZ) [C:\Users\antho\Development\Repositories\tensorflow_scala\modules\jni\target\native\windows-x86_64\build\tensorflow_jni.vcxproj]

```

**Comment by eaplatanios** [comment]
@alextp sorry I think I dismissed your reviews somehow when I accidentally added and removed some other changes while trying to fix that last linking error.

**Comment by alextp** [comment]
Oof protobuf default instances are nasty things. This is some integration with the proto library I don't fully understand.

**Review by alextp — DISMISSED** [review]

**Review by alextp — DISMISSED** [review]

**Review by alextp — APPROVED** [review]

**Comment by eaplatanios** [comment]
Thanks Alex! I got it working by refactoring a bit how I use the bundle reader. :)

**Comment by alextp** [comment]
We had to roll this back because it broke tests on windows. Can you look at the failures? They are in the rollback message: https://github.com/tensorflow/tensorflow/commit/04d770b603809a9c89974e77576af238d422fde5

**Pull request merged**
