### PR TITLE
Upgrade cuda to 9 and cudnn version to 7.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by yifeif** [comment]
@gunan looks like the jenkins GPU failures are new and might be related to the upgrade?

**Comment by gunan** [comment]
Looks like there was an eigen bug, we will need #14770 merged, then this change should be good to go.

**Comment by gunan** [comment]
@zheng-xq looks like another build issue with cuda 9 crept in. Have you seen this one before?
https://ci.tensorflow.org/job/tensorflow-pull-requests-gpu/7826/consoleFull

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
@zheng-xq now the transpose_op_test is timing out. Do you think it could be caused by the cuda9 upgrade?

**Comment by gunan** [comment]
Jenkins , test this please.

**Comment by zheng-xq** [comment]
Feel free to disable some big ones. @yzhwang can take a look afterwards. Thanks!

**Comment by gunan** [comment]
Merging, since python3 tests passed on kokoro despite the failure on jenkins.

**Comment by flx42** [comment]
Should we remove https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu-cuda9-cudnn7?

**Comment by gunan** [comment]
good idea! I can send a followup PR for that.

**Comment by snnn** [comment]
Hi @gunan 

After this commit, we'll use Ubuntu 16 for GPU build but Ubuntu 14 for CPU build. This will cause a lot confusions. Can you unify that?

**Comment by gunan** [comment]
We still need to continue testing for ubuntu 14, however nvidia docker does not have 14.04 support anymore. So the version skew is partially intentional right now.

**Comment by flx42** [comment]
Wait, does it matter for building a Docker image anyway?
You can still use nvidia-docker 1.0 on trusty, or you can try to use the xenial packages for 2.0, but you will have to setup the new runtime manually.

**Comment by gunan** [comment]
All our CI machines are on ubuntu 16.04. But I think the concern is the CPU docker images are still based off of ubuntu 14.04, while the base image for CUDA enabled packages are ubuntu 16.04

**Comment by alanpurple** [comment]
any plan for cuda 9.1

**Pull request merged**
