### PR TITLE
[TFLite] Avoid passing negative quantized multipliers to MultiplyByQuantizedMultiplier

### PR DESCRIPTION
**Pull request by Tessil**
Hello,

This PR updates the SUB and DIV kernels to avoid passing negative quantized multipliers to the `MultiplyByQuantizedMultiplier` method.

It allows us to later on add a restriction on the quantized multiplier of the int32 `MultiplyByQuantizedMultiplier` similar to the one already present in the int64 version. 

Thibaut

### CODE REVIEW

**Comment by terryheo** [comment]
@daverim could you review this?

**Review by daverim — COMMENTED** [review]
This code seems fine to me, but there doesn't seem like there is a bug that is being fixed -- isn't the multiplier already positive-only? If there is a bug, could you add a failing test that this PR fixes?

I realize these are reference kernels, but is there an impact on latency / memory / binary size ?

**Comment by Tessil** [comment]
This PR doesn't solve a bug per se and should be reviewed with #50290 as context as the current changes were initially part of this PR. The single-rounding PR adds a new requirement to the `quantized_multiplier` parameter of the int32 version of `MultiplyByQuantizedMultiplier`, it must now be a positive integer similar to the requirement for the int64 version.

The PR fixes the negative quantize multipliers by forcing `input2_inv` to be positive for the div kernel and `input2_multiplier` for the sub kernel.

**Review by daverim — APPROVED** [review]
LGTM

**Comment by Tessil** [comment]
@daverim @renjie-liu  It seems the change was merged but then reverted by https://github.com/tensorflow/tensorflow/commit/befc25bd0916f927505ba35b52c0b20249fc3e4d Was there an internal problem that caused the revert?

**Comment by terryheo** [comment]
The CL was reverted since it broke TFMicro test
`tflite_micro/tensorflow/lite/micro/kernels:sub_test`
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/sub_test.cc

**Comment by Tessil** [comment]
Thank you for the information. With TFLite Micro being now in a stand-alone repository our CI missed that.

The problem was that I renamed `BroadcastSubSlow` to `BroadcastQuantSubSlow` to avoid a name clash now that the function is templated. I would need to modify https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/sub.cc and change `BroadcastSubSlow` for (u)int8 to  `BroadcastQuantSubSlow`. We also need to modify the int16 version of the operator to also avoid using the add kernel.

What is the best way to proceed? As the change I need to do in tflite-micro depends on the change in tflite I am not sure if I can raise a PR in tflite-micro that changes https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/kernels/internal/reference/sub.h as the code is part of tflite.

**Comment by daverim** [comment]
Sorry, fell off my radar -- could you submit a PR to micro and link it here? I'll try to merge both in a single patch on our side.

**Comment by Tessil** [comment]
@daverim Thank you, I created the necessary PR in tfllite-micro (linked above). Let me know if there is any problem.

**Comment by advaitjain** [comment]
Google-Internal change that can be merged as one atomic commit : http://cl/405510094

This includes changes from the current PR as well as the corresponding PR in tflite-micro (https://github.com/tensorflow/tflite-micro/pull/665).

Once the internal change is in, the TFLM infra will sync the code to TFLM and then https://github.com/tensorflow/tflite-micro/pull/665 can also be merged.

**Comment by advaitjain** [comment]
The changes from this PR are now merged. I will get the TFLM repo up to date with this change as well.

**Pull request merged**
