### PR TITLE
Revert "Add vmodule support to TF OSS logging."

### LINKED ISSUE #12117: Bazel Windows Build: '//tensorflow/tools/proto_text:gen_proto_text_functions' failed to link
This was first caught by Bazel CI: http://ci.bazel.io/blue/organizations/jenkins/TensorFlow/detail/TensorFlow/1030/pipeline
Reported at https://github.com/bazelbuild/bazel/issues/3524
```
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /OUT:bazel-out/msvc_x64-py3-opt/bin/tensorflow/tools/proto_text/gen_proto_text_functions.exe /MACHINE:X64 /SUBSYSTEM:CONSOLE @bazel-out/msvc_x64-py3-opt/bin/tensorflow/tools/proto_text/gen_proto_text_functions.exe-2.params /DEFAULTLIB:libcmt.lib.
liblib_proto_parsing.a(logging.o) : error LNK2019: unresolved external symbol "public: unsigned __int64 __cdecl tensorflow::StringPiece::Hasher::operator()(class tensorflow::StringPiece)const " (??RHasher@StringPiece@tensorflow@@QEBA_KV12@@Z) referenced in function "protected: struct std::pair<class std::_List_iterator<class std::_List_val<struct std::_List_simple_types<struct std::pair<class tensorflow::StringPiece const ,int> > > >,bool> __cdecl std::_Hash<class std::_Umap_traits<class tensorflow::StringPiece,int,class std::_Uhash_compare<class tensorflow::StringPiece,struct tensorflow::StringPiece::Hasher,struct std::equal_to<class tensorflow::StringPiece> >,class std::allocator<struct std::pair<class tensorflow::StringPiece const ,int> >,0> >::_Insert<struct std::pair<class tensorflow::StringPiece const ,int> &,class std::_List_unchecked_iterator<class std::_List_val<struct std::_List_simple_types<struct std::pair<class tensorflow::StringPiece const ,int> > > > >(struct std::pair<class tensorflow::StringPiece const ,int> &,class std::_List_unchecked_iterator<class std::_List_val<struct std::_List_simple_types<struct std::pair<class tensorflow::StringPiece const ,int> > > >)" (??$_Insert@AEAU?$pair@$$CBVStringPiece@tensorflow@@H@std@@V?$_List_unchecked_iterator@V?$_List_val@U?$_List_simple_types@U?$pair@$$CBVStringPiece@tensorflow@@H@std@@@std@@@std@@@2@@?$_Hash@V?$_Umap_traits@VStringPiece@tensorflow@@HV?$_Uhash_compare@VStringPiece@tensorflow@@UHasher@12@U?$equal_to@VStringPiece@tensorflow@@@std@@@std@@V?$allocator@U?$pair@$$CBVStringPiece@tensorflow@@H@std@@@4@$0A@@std@@@std@@IEAA?AU?$pair@V?$_List_iterator@V?$_List_val@U?$_List_simple_types@U?$pair@$$CBVStringPiece@tensorflow@@H@std@@@std@@@std@@@std@@_N@1@AEAU?$pair@$$CBVStringPiece@tensorflow@@H@1@V?$_List_unchecked_iterator@V?$_List_val@U?$_List_simple_types@U?$pair@$$CBVStringPiece@tensorflow@@H@std@@@std@@@std@@@1@@Z)
bazel-out/msvc_x64-py3-opt/bin/tensorflow/tools/proto_text/gen_proto_text_functions.exe : fatal error LNK1120: 1 unresolved externals
Target //tensorflow/tools/proto_text:gen_proto_text_functions failed to build
```

Culprit is found by bisecting: tensorflow/tensorflow@072b0c9.
The unresolved symbol `tensorflow::StringPiece::Hasher::operator()` is implemented in `stringpiece.cc`. This change should have introduced a dependency on stringpieces.cc from logging.cc.

However, `//tensorflow/tools/proto_text:gen_proto_text_functions` doesn't contain `stringpiece.cc`
```
$ bazel query 'somepath(//tensorflow/tools/proto_text:gen_proto_text_functions, tensorflow/core/lib/core/stringpiece.h)'
//tensorflow/tools/proto_text:gen_proto_text_functions
//tensorflow/core:lib_proto_parsing
//tensorflow/core:lib/core/stringpiece.h

$ bazel query 'somepath(//tensorflow/tools/proto_text:gen_proto_text_functions, tensorflow/core/lib/core/stringpiece.cc)'
INFO: Empty results
```

The strange thing is this didn't break the Linux build, one possible explanation is that there is an implementation of stringpiece.cc in protobuf, which is a dependency of `//tensorflow/tools/proto_text:gen_proto_text_functions`
```
$ bazel query 'deps(//tensorflow/tools/proto_text:gen_proto_text_functions)' | grep stringpiece.cc
@protobuf_archive//:src/google/protobuf/stubs/stringpiece.cc
```
@learyg @gunan

### PR DESCRIPTION
**Pull request by meteorcloudy**
This reverts commit 072b0c9c552837a97c967963628b3c30951388f9.

http://ci.tensorflow.org/job/tf-master-win-bzl/1508/console
This is to fix https://github.com/tensorflow/tensorflow/issues/12117 again, because https://github.com/tensorflow/tensorflow/pull/12151 got rollbacked.

@learyg Sorry, I have to roll back this to fix the Windows build.

@gunan

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]
Sad, but we do want the windows build to work.

**Comment by learyg** [comment]
Sounds good, today was a vacation day in the US so I was AFK. Will look at rolling forward a proper fix sometime this week. @gunan do we believe we have some target that'll fail if I introduce a dependency like this again? Didn't seem at submit time like anything was exploding in the CMake build, but I totally may have missed something. Happy to take any advice on making sure I do a properly tested fix, will try my darndest. :-)

**Comment by meteorcloudy** [comment]
@gunan I remember you tried to set up a Kokoro presubmit job for just building TensorFlow on Windows, is it already working now?

**Comment by gunan** [comment]
not yet, I have been sidetracked by other issues.
I will try to make some time tomorrow.

**Comment by apark263** [comment]
@learyg, would it be as simple as changing all `StringPiece` to `std::string` and then using

```c++
#include <string>
#include <functional>

  struct Hasher {
    std::hash<std::string> hash_fn_;
    size_t operator()(std::string arg) const {
      return hash_fn_(arg);
    }
  };
  using VmoduleMap = std::unordered_map<std::string, int, Hasher>;    
```

As far as i can tell, the key constructors used for `StringPiece` and `std::string` are compatible (`const char*` with `size_t`)

**Comment by learyg** [comment]
@apark263 There was some concern about the allocations that might be created by the std::strings, since VLOGging is so prevalent. Probably we could just define a custom hasher for the const char*s as keys, VLOG macro should always result in a stable const char* pointer to hash via the __FILE__ preprocessing token. +@hawkinsp who originally voiced the concern.

**Comment by reedwm** [comment]
@learyg @hawkinsp any plans to add vmodule support back? It greatly helps when debugging TensorFlow.

**Pull request merged**
