### PR TITLE
Fix floating point issue on RequantizeManyInNewRange

### PR DESCRIPTION
**Pull request by everton1984**
Hi,
while comparing tests `requantize_op_test` and `quantize_down_and_shrink_range_op_test` I noticed that both tests are quite similar, like so
```
TEST_F(QuantizeDownAndShrinkRangeTest, HandCrafted) {
  TF_ASSERT_OK(NodeDefBuilder("quantize_down_and_shrink_range_op",
                              "QuantizeDownAndShrinkRange")
                   .Input(FakeInput(DT_QINT32))
                   .Input(FakeInput(DT_FLOAT))
                   .Input(FakeInput(DT_FLOAT))
                   .Attr("Tinput", DataTypeToEnum<qint32>::v())
                   .Attr("out_type", DataTypeToEnum<quint8>::v())
                   .Finalize(node_def()));
  TF_ASSERT_OK(InitOp());

  // For this test we have an input that has the theoretical range of -256.0f to
  // +256.0f, but the actual values present only span -1.0f to 1.0f. We expect
  // the operator to take advantage of this, and rescale the output to fill up
  // the available range in the lower bit depth, and update to the true min and
  // max ranges.
  const int value_count = 3;
  AddInputFromArray<qint32>(TensorShape({value_count}),
                            {-(1 << 23), 0, (1 << 23)});
  AddInputFromArray<float>(TensorShape({1}), {-256.0f});
  AddInputFromArray<float>(TensorShape({1}), {256.0f});
  TF_ASSERT_OK(RunOpKernel());
  Tensor expected(allocator(), DT_QUINT8, TensorShape({value_count}));
  test::FillValues<quint8>(&expected, {0, 127, 255});
  test::ExpectTensorEqual<quint8>(expected, *GetOutput(0));
  Tensor expected_min(allocator(), DT_FLOAT, TensorShape({}));
  test::FillValues<float>(&expected_min, {-1.0f});
  test::ExpectTensorEqual<float>(expected_min, *GetOutput(1));
  Tensor expected_max(allocator(), DT_FLOAT, TensorShape({}));
  test::FillValues<float>(&expected_max, {1.0f});
  test::ExpectTensorEqual<float>(expected_max, *GetOutput(2));
}
```
and 
```
// Runs a manually generated array through the operator, and makes sure that the
// results match the expected hand-calculated values.
TEST_F(RequantizeTest, HandCraftedRequantize) {
  ConfigureRequantize();
  const int value_count = 3;

  // Requantize to -1 to 1.
  AddInputFromArray<qint32>(TensorShape({value_count}),
                            {-(1 << 23), 0, (1 << 23)});
  AddInputFromArray<float>(TensorShape({1}), {-256.0f});
  AddInputFromArray<float>(TensorShape({1}), {256.0f});
  AddInputFromArray<float>(TensorShape({1}), {-1.0f});
  AddInputFromArray<float>(TensorShape({1}), {1.0f});
  TF_ASSERT_OK(RunOpKernel());
  Tensor expected(allocator(), DT_QUINT8, TensorShape({value_count}));
  test::FillValues<quint8>(&expected, {0, 128, 255});
  test::ExpectTensorEqual<quint8>(expected, *GetOutput(0));
  test::ExpectTensorEqual<float>(test::AsScalar<float>(-1.0f), *GetOutput(1));
  test::ExpectTensorEqual<float>(test::AsScalar<float>(1.0f), *GetOutput(2));
}
```
however one expects the result to be 127 and the other 128. 

If you try to pinpoint the problem `RequantizeManyInNewRange` receives on both tests `min_float` as -1 but on one the bit representation is `10111111100000000000000000000000` and the other one `10111111011111111111111111111111` since `static_cast` just truncates the result differs in both executions. This can be seen on both x86 as well as on Arm. 

The patch fixes this using a default rounding strategy as well as the expected value on `quantize_down_and_shrink_range_op_test` to match.

### CODE REVIEW

**Comment by everton1984** [comment]
I should already be on the CLA list if it's possible, please rerun the check.

**Comment by gbaned** [comment]
> I should already be on the CLA list if it's possible, please rerun the check.

@everton1984 I have checked and still it shows you are not signed CLA.  Can you please make sure to use same GitHub username and email-id associated with it.  Thank you!.

**Comment by mihaimaruseac** [comment]
Hi.

Can you make sure this email address is used to sign the CLA?



GitHub Login | Email | State
-- | -- | --
everton1984 | everton.constantino@linaro.org | Need CLA

**Comment by everton1984** [comment]
> Hi.
> 
> Can you make sure this email address is used to sign the CLA?
> GitHub Login 	Email 	State
> everton1984 	[everton.constantino@linaro.org](mailto:everton.constantino@linaro.org) 	Need CLA

I self-signed just now. Hope it works. Thanks

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Seems to have worked.

**Pull request merged**
