### PR TITLE
Just fix little issue that is model_file_type variable but not using it in iOS DEMO.

### PR DESCRIPTION
**Pull request by tucan9389**

### CODE REVIEW

**Comment by tucan9389** [comment]
I signed it!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 16 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tucan9389** [comment]
Why is this awaited a long time?.. Am I missing something for my process?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 15 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 30 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Review by rmlarsen — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request merged**
