### PR TITLE
Replace `variables.get_global_step()` use `training_util.get_global_step()`

### PR DESCRIPTION
**Pull request by izhangzhihao**

### CODE REVIEW

**Comment by izhangzhihao** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this pleas

**Review by ispirmustafa — APPROVED** [review]
Thank you!

**Comment by caisq** [comment]
@tensorflow-jeknins test this please

**Comment by caisq** [comment]
@izhangzhihao There are test errors: https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/7544/consoleFull

Can you please fix them?

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by izhangzhihao** [comment]
@caisq All tests passed.

**Pull request merged**
