### PR TITLE
Added space to make bullet point visible

### PR DESCRIPTION
**Pull request by devendra-rgb**

### CODE REVIEW

**Comment by devendra-rgb** [comment]
In preview of release.me the bullet point is only visible the sentence is not visible to get rid of bug I added a white space

**Comment by devendra-rgb** [comment]
> This is just a snippet. The space doesn't bring anything.
> 
> When making typo fixes PRs please fix through the entire file/directory.

Thanks! for responding did you see the preview of the edited one

**Comment by mihaimaruseac** [comment]
Yes, but these are just placeholders, they don't mean anything in the rich view

**Comment by devendra-rgb** [comment]
> Yes, but these are just placeholders, they don't mean anything in the rich view

Thankyou! mihaimaruseac got the point 😁

**Pull request closed without merging**
