### PR TITLE
[oneDNN] Convert necessary PlaceholderWithDefault or Placeholder to Constant f…

### PR DESCRIPTION
**Pull request by gaurides**
Convert necessary PlaceholderWithDefault or Placeholder to Constant for Inference. 

Some old models have Placeholder / PlaceholderWithDefault for keras_learning_phase  which decide training / inference phase, can be easily converted to Constant when running Inference.
Changes in this PR will help enable further optimizations like ConstantFolding and RemoveDeadBranches() of Merge in loop_optimization grappler pass. 
This change along with further enabled fusions will provide performance improvements projected to be around 25-30% improvements.

### CODE REVIEW

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gaurides** [comment]
@penpornk Can you please review this PR ?

@gbaned - is there someone else who can review?

**Comment by gbaned** [comment]
@penpornk  Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk / @sun51 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk / @sun51 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk / @sun51 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk / @sun51 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk / @sun51 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk / @sun51 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk / @sun51 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @gaurides Can you please rebase your branch and resolve conflicts? Thank you!

**Comment by gaurides** [comment]
> This PR is stale because it has been open for 14 days with no activity. It will be closed if no further activity occurs. Thank you.

@gbaned - i have resolved conflicts. 1 test failing in Py+CPP Test Suite is not related to changes in this PR.
Can you please review this PR?

**Comment by gbaned** [comment]
> > This PR is stale because it has been open for 14 days with no activity. It will be closed if no further activity occurs. Thank you.
> 
> @gbaned - i have resolved conflicts. 1 test failing in Py+CPP Test Suite is not related to changes in this PR. Can you please review this PR?

Hi @gaurides Thank you for the update.

**Review by cantonios — APPROVED** [review]

**Review by cantonios — APPROVED** [review]

**Pull request merged**
