### PR TITLE
TFLite Micro adding simple api for easier integration with c libraries

### PR DESCRIPTION
**Pull request by ghost**
- Goal of this commit is to be able to create a simpler interface to the code that can be generated as part of a libtfmicrolib.a so that the only header file that is needed by other code is the tf_micro_simple.h

- Adds fPIC to the makefile which was causing problems with creating a shared library if not included

### CODE REVIEW

**Comment by cdknorow** [comment]
I'm not expecting this to be approved, just sharing my perspective working on a majority c code base. A simple api like this would make it easier to incorporate  tf_micro as a library. The thought process would be to 

-> build libtfmicro.a for your specific platform 
-> the user specific code then only needs to include tf_micro_simple.h and the two api's to be able to setup and invoke the model. There won't be a need to include other headers from. If you look at the main_function.cc changes in hello world the idea would be to separate out the tf_micro code as much as possible (at least for the most common scenarios)

**Comment by cdknorow** [comment]
@googlebot I signed it!

**Comment by advaitjain** [comment]
Thanks for this PR @cdknorow. This is useful feedback for us.

**Comment by gbaned** [comment]
@sensiml  thank you for your contribution, please sign CLA.

**Comment by sensiml** [comment]
@googlebot  I signed it!

**Comment by gbaned** [comment]
@sensiml Please sign CLA and resolve the conflicts? Thanks!

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Comment by sensiml** [comment]
@rthadur @advaitjain  Hey, thanks I wasn't able to work on it for a while. Also I wasn't sure if the tflite team was interested in the sort of change to decouple the tflite library from the example applications so I wasn't going to put too much effort into it without that feedback.

**Comment by sensiml** [comment]
We did sign the CLA aggreements thought, but it never seemed to register with the system

**Comment by rthadur** [comment]
@petewarden any thoughts on above comments from @sensiml ?

**Pull request closed without merging**
