### PR TITLE
test for partial_run_setup with no feeds passed

### PR DESCRIPTION
**Pull request by JKurland**

### CODE REVIEW

**Comment by frankchn** [comment]
Jenkins, test this please

**Review by frankchn — APPROVED** [review]

**Comment by frankchn** [comment]
Getting the following error:

```Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/python/session_partial_run_test.runfiles/org_tensorflow/tensorflow/python/client/session_partial_run_test.py", line 203, in testPartialRunSetupNoFeedsPassed
    h = sess.partial_run_setup([r1])
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/python/session_partial_run_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1011, in partial_run_setup
    raise e
TypeError: Cannot interpret feed_list key as Tensor: Can not convert a NoneType into a Tensor.

======================================================================
ERROR: testPartialRunSetupNoFeedsPassed (__main__.PartialRunWithCApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/python/session_partial_run_test.runfiles/org_tensorflow/tensorflow/python/client/session_partial_run_test.py", line 203, in testPartialRunSetupNoFeedsPassed
    h = sess.partial_run_setup([r1])
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/python/session_partial_run_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1011, in partial_run_setup
    raise e
TypeError: Cannot interpret feed_list key as Tensor: Can not convert a NoneType into a Tensor.```

**Review by frankchn — DISMISSED** [review]
Blocking until tests are fixed.

**Comment by rmlarsen** [comment]
@JKurland could you please take a look at the failing tests?

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
The test fails with:

======================================================================
ERROR: testPartialRunSetupNoFeedsPassed (__main__.PartialRunTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/python/session_partial_run_test.runfiles/org_tensorflow/tensorflow/python/client/session_partial_run_test.py", line 203, in testPartialRunSetupNoFeedsPassed
    h = sess.partial_run_setup([r1])
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/python/session_partial_run_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1005, in partial_run_setup
    raise e
TypeError: Cannot interpret feed_list key as Tensor: Can not convert a NoneType into a Tensor.

======================================================================
ERROR: testPartialRunSetupNoFeedsPassed (__main__.PartialRunWithCApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/python/session_partial_run_test.runfiles/org_tensorflow/tensorflow/python/client/session_partial_run_test.py", line 203, in testPartialRunSetupNoFeedsPassed
    h = sess.partial_run_setup([r1])
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/python/session_partial_run_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1005, in partial_run_setup
    raise e
TypeError: Cannot interpret feed_list key as Tensor: Can not convert a NoneType into a Tensor.

----------------------------------------------------------------------
Ran 50 tests in 6.631s

FAILED (errors=2)

**Comment by JKurland** [comment]
Hi,
Sorry about the delay. Yeah this is the error the patch is meant to fix.
Josh

**Comment by rmlarsen** [comment]
@JKurland OK, can you ping this thread when you have a fix?

**Comment by JKurland** [comment]
The solution is here
https://github.com/tensorflow/tensorflow/pull/11353
Can you combine the two pull requests now, I'm afraid I don't really have time

**Comment by rmlarsen** [comment]
@JKurland Can't you just move the test to #11353 and close this PR? Doesn't seem like it would take more than 10 minutes.

**Comment by JKurland** [comment]
ok added the patch

**Review by jhseu — APPROVED** [review]

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by drpngx** [comment]
```
tensorflow/compiler/tf2xla/xla_cpu_backend.cc: In function 'bool tensorflow::CpuOpFilter(tensorflow::KernelDef*)':
tensorflow/compiler/tf2xla/xla_cpu_backend.cc:23:11: error: invalid use of incomplete type 'class tensorflow::KernelDef'
   if (kdef->op() == "RandomStandardNormal") {
           ^
In file included from ./tensorflow/core/framework/op_kernel.h:27:0,
                 from ./tensorflow/core/common_runtime/device.h:41,
                 from ./tensorflow/core/common_runtime/local_device.h:19,
                 from ./tensorflow/compiler/tf2xla/xla_op_registry.h:25,
                 from tensorflow/compiler/tf2xla/xla_cpu_backend.cc:16:
./tensorflow/core/framework/kernel_def_builder.h:27:7: error: forward declaration of 'class tensorflow::KernelDef'
 class KernelDef;
```

Seems to be unrelated.

Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Pull request merged**
