### PR TITLE
[Docker] Upgraded images to Ubuntu 18.04 LTS.

### PR DESCRIPTION
**Pull request by jpds**
Upgraded all Docker base images to `18.04`.

I haven't upgraded the GPU ones as those are still marked experimental: https://hub.docker.com/r/nvidia/cuda/

### CODE REVIEW

**Comment by jpds** [comment]
CLA signed.

**Comment by angersson** [comment]
Looks good to me, but @gunan, is this safe to do? I don't know if there are any problems keeping us at 16.04.

**Comment by gunan** [comment]
I think ubuntu 18.04 has python 3.7?
If yes, i think this will break all our python 3 docker images.

**Comment by bhack** [comment]
Yes it has python 3.7 default but what are the python 3 docker images that are you talking about?

**Comment by bhack** [comment]
Check also https://github.com/tensorflow/tensorflow/issues/17022

**Comment by gunan** [comment]
All the images that have "py3" suffix here:
https://hub.docker.com/r/tensorflow/tensorflow/tags/

**Comment by gunan** [comment]
I will close this PR for now.

**Comment by jpds** [comment]
@gunan Actually, 18.04 LTS has Python 3.6.6:

```
$ apt-get install python3
$ python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19)
```

**Comment by bhack** [comment]
Seems different https://packages.ubuntu.com/bionic/python
https://packages.ubuntu.com/bionic-updates/python3

**Comment by bhack** [comment]
https://packages.ubuntu.com/bionic-updates/python3.7

**Comment by jpds** [comment]
@bhack `python3` ultimately installs `python3.6` which pulls in 3.6.6: https://packages.ubuntu.com/bionic-updates/python3.6

**Comment by bhack** [comment]
So can we reopen this?

**Comment by ymodak** [comment]
@gunan Friendly ping. Can you please take a look at this PR? Thanks!

**Review by gunan — APPROVED** [review]

**Comment by NegatioN** [comment]
I probably just come of as nagging now, but how long do you guys estimate that it would take before this is released under the `:latest` tag?
I'm really excited to use this image, but if we're looking at another 2-3 weeks I would probably deploy a local version I've made.

**Review by angerson — APPROVED** [review]

**Comment by angersson** [comment]
Our Docker images are updated nightly (for the `nightly-` images) and per-release (for `latest-` and `XX.XX-`), so if your deployment is time-critical and you only want to use stable releases, I'd recommend using your own image for now.

**Comment by angersson** [comment]
Note that the GPU development images were not changed in this PR. nvidia/cuda doesn't provide Ubuntu 18 / cuda 9.0 base images.

**Comment by bhack** [comment]
@angersson Is TF still default on 9.0? Any plan for 9.2? There was a bug in [cuda 9.0 series](https://devtalk.nvidia.com/default/topic/1028112/cuda-setup-and-installation/nvcc-bug-related-to-gcc-6-lt-tuple-gt-header-/) with "modern" version of GCC>=6. Some [Asan flags for cuda](https://github.com/google/sanitizers/issues/629) like `protect_shadow_gap=0` are not avaialbe on gcc 5.x.

**Comment by angersson** [comment]
@bhack As far as I know, the TF team is working on upgrading directly to CUDA 10. @tfboyd, can you weigh in?

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/issues/22706

**Pull request merged**
