### PR TITLE
Fixed typos in post_training_quant.ipynb

### PR DESCRIPTION
**Pull request by LakshmiKalaKadali**
This PR fixes some typos in  post_training_quant.ipynb

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @vamsimanchala Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @vamsimanchala Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @vamsimanchala Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @vamsimanchala Can you please review this PR ? Thank you!

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
