### PR TITLE
_ConstantValue can now see through tf.identity ops

### PR DESCRIPTION
**Pull request by ngc92**
Fix for #37716

`_ConstantValue` (and thus `get_static_value`) now know that the static value of the result of `tf.identity` is the same as the static value of the original.

### CODE REVIEW

**Review by alextp — DISMISSED** [review]

**Comment by ngc92** [comment]
It seems the test failures are caused by tensorflow now being able to raise `InvalidArgumentError` in some more situations, which means that the confusion matrix tests that expect the op to assert fail with this exception. How should I proceed?

**Comment by gbaned** [comment]
> It seems the test failures are caused by tensorflow now being able to raise `InvalidArgumentError` in some more situations, which means that the confusion matrix tests that expect the op to assert fail with this exception. How should I proceed?

@alextp Can you please assist on above comments from @ngc92 . Thanks!

**Comment by alextp** [comment]
You can make changes to the tests to make them pass.

**Comment by gbaned** [comment]
@ngc92 Can you please check @alextp comments and resolve conflicts?. Thanks!

**Review by alextp — DISMISSED** [review]

**Comment by gbaned** [comment]
@ngc92 Still, conflicts are appearing. Can you please resolve those? Thanks!

**Review by alextp — APPROVED** [review]

**Pull request merged**
