### PR TITLE
Add RCCL package and ops.

### PR DESCRIPTION
**Pull request by jeffdaily**
These contributed RCCL ops are based on the NCCL ops. Due to the intentional similarities of the RCCL API to the NCCL1 API, in most cases, these can be used as a drop-in replacement for NCCL when compiling with ROCm.

### CODE REVIEW

**Comment by gunan** [comment]
I am not familiar with nccl myself, adding @azaks2 for review.

**Comment by whchung** [comment]
@jeffdaily could you address `clang-format` checks? failures in other test targets don't seem to be that relevant to this PR on the other hand.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yifeif, @chsigg, @gunan, @azaks2, @aaroey: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yifeif, @chsigg, @gunan, @azaks2, @aaroey: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yifeif, @chsigg, @gunan, @azaks2, @aaroey: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by chsigg** [comment]
Hi Jeff. Sorry for the long delay. 

The RCCL ops should move from contrib to core. Contrib is going away in TF 2.0.

I will make sure this gets reviewed/approved promptly afterwards. Thanks for your patience.

**Comment by jeffdaily** [comment]
> Hi Jeff. Sorry for the long delay.
> 
> The RCCL ops should move from contrib to core. Contrib is going away in TF 2.0.
> 
> I will make sure this gets reviewed/approved promptly afterwards. Thanks for your patience.

@chsigg would you like me to close this PR and create a new one against core?

**Comment by whchung** [comment]
@jeffdaily I think it’s up to you. You can create a new one or git push —force and rewrite commit history here.

**Comment by chsigg** [comment]
Yes, whatever works best for you.

**Pull request closed without merging**
