### PR TITLE
Leonard951 patch 1

### PR DESCRIPTION
**Pull request by leonard951**
Fixed the code for aarch64

### CODE REVIEW

**Comment by freedomtan** [comment]
duplicated https://github.com/tensorflow/tensorflow/pull/16175 and  https://github.com/tensorflow/tensorflow/pull/22856

**Review by petewarden — DISMISSED** [review]

**Comment by rthadur** [comment]
@leonard951 gentle ping to resolve conflicts

**Review by petewarden — APPROVED** [review]

**Comment by leonard951** [comment]
It says "Some checks were not successful. 11 failing, 3 pending, and 1 successful checks". What can be done to pass these checks?

**Comment by leonard951** [comment]
I noticed that most of my proposed changes have already shown at the tip of the master branch except for the new one at https://github.com/tensorflow/tensorflow/pull/28911. So, I am closing this pull request. Please review #28911 and upstream it if it gets an approval after code review.

**Pull request closed without merging**
