### PR TITLE
Update SignatureRunner support information for C API

### PR DESCRIPTION
**Pull request by pjpratik**
The TFLite `SignatureRunner` is supported in C API with commit https://github.com/tensorflow/tensorflow/commit/3a6a6465c45797bd573c118a535405da43ab03fa.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @LukeBoyer Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @LukeBoyer Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @LukeBoyer Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @LukeBoyer Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @LukeBoyer Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @LukeBoyer Can you please review this PR ? Thank you!

**Review by LukeBoyer — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
