### PR TITLE
[INTEL MKL] Add MKL-DNN quantized Matmul op with some fusions - Part2.

### PR DESCRIPTION
**Pull request by mdfaijul**
This PR is to replace an older PR #26271 by splitting into three. Current PR is part2. It enables MKL-DNN quantized Matmul ops through graph optimization.

### CODE REVIEW

**Review by penpornk — COMMENTED** [review]
Does this PR depend on https://github.com/tensorflow/tensorflow/pull/26909 (Part 1)?

**Comment by mdfaijul** [comment]
@penpornk Yes, it depends on #26909 (Part 1)?

**Review by penpornk — COMMENTED** [review]
I think the PR is good to go. Once https://github.com/tensorflow/tensorflow/pull/26909 is merged, please rebase the PR and I'll approve it. Thank you again!

**Review by penpornk — APPROVED** [review]
Part 1 (https://github.com/tensorflow/tensorflow/pull/26909) has been merged. (Hasn't shown on Github yet, but it will soon.) And I realized that all three PRs are guarded with `INTEL_MKL` anyway, so we probably won't have problems with the tests on Github. Will approve part 3 too.

**Comment by penpornk** [comment]
There are four failed tests. `MacOS Python2 and CC`, `Ubuntu Makefile`, `Ubuntu Python 2` seem unrelated to this PR. I can't view the log for `Windows Bazel` but it's likely to be unrelated too. 

@rthadur Could you please help pull this PR in? Thank you very much! :)

**Pull request merged**
