### PR TITLE
Added Adaptive pooling layers to tf.keras

### PR DESCRIPTION
**Pull request by Susmit-A**
Added the following layers in the file tensorflow/python/keras/layers/adaptive_pooling.py:
AdaptiveAveragePooling1D
AdaptiveAveragePooling2D
AdaptiveAveragePooling3D
AdaptiveMaxPooling1D
AdaptiveMaxPooling2D
AdaptiveMaxPooling3D

### CODE REVIEW

**Comment by tanzhenyu** [comment]
Can you move this to tf_addons?

**Comment by Susmit-A** [comment]
I've submitted the PR to tensorflow_addons. Thank you.

**Comment by Susmit-A** [comment]
Shall I close this PR?

**Comment by tanzhenyu** [comment]
> Shall I close this PR?

That's great. Thanks! Closing it.

**Pull request closed without merging**
