### PR TITLE
NVCC bug demonstration

### PR DESCRIPTION
**Pull request by brianwa84**
Would like to submit this, but it crashes GPU.

### CODE REVIEW

**Comment by gbaned** [comment]
@chsigg Can you please review this PR ? Thanks!

**Comment by brianwa84** [comment]
Just checked, it still crashes. `Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure`

**Comment by gbaned** [comment]
@sanjoy Can you please take a look on the above comment from @brianwa84. Thanks!

**Comment by brianwa84** [comment]
fwiw, internally this is cl/330040611. I filed this issue to ensure nvidia visibility.

**Comment by gbaned** [comment]
@brianwa84 Any update on this PR? Please. Thanks!

**Comment by sanjoy** [comment]
Closing pull request to avoid confusion.  As Brian stated above, this is just a placeholder to make some source code public.

**Pull request closed without merging**
