### PR TITLE
Use the last char instead of the first in prediction

### PR DESCRIPTION
**Pull request by leondgarse**
1. As it's mentioned the `start_string` could be a string here, in my understanding, the correctly predicted next character should be the last one in `predictions`.
2. As `tf.multinomial` is not used any more here, `temperature` has no effect either.

- i.e.
  - With `start_string = 'QUEEN'`, the model prediction string is `UEEN:`, so the next char should be `:`
  - In the loop run `for i in range(num_generate):`
    - With `predicted_id = tf.argmax(predictions[0]).numpy()`, output is `QUEENUS:\nI think so ...`
    - With `predicted_id = tf.argmax(predictions[-1]).numpy()`, output is `QUEEN:\nThe grand the ...`

### CODE REVIEW

**Comment by alextp** [comment]
@yashk2810 does this make sense to you?

I'm a little confused about what this change entails.

**Comment by yashk2810** [comment]
So, I tried out the change and it for a single character start_string, the predictions shape is (1, 65). But if the start_string is a word like 'Queen', the shape of the first prediction is (5, 65). Hence we need to use the last character from the prediction to predict the next character, hence `predictions[-1]` makes sense there. 

This doesn't matter if the input is a single character. So changing to `predictions[-1]` will make the predictions right if the start_string is a word and it won't change anything if the start_string is a character.

As far as temperature goes, it makes sense to remove it since tf.multinomial is not being used.

@leondgarse Can you also remove the comment above the predicted_id line which mentions tf.multinomial and change the text in the markdown above?

**Comment by leondgarse** [comment]
Sorry for the delay, I just replaced the sentence `a multinomial distribution` by `argmax` in comment and the above text.

**Review by alextp — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request merged**
