### PR TITLE
TFLite library fix for r2.1 branch

### PR DESCRIPTION
**Pull request by terryheo**
This PR contains the following cherry-picks to fix a link failure with TFLite library.

5b1fbe0268 TFLite: tools: make: add fftsg2d.c file in the build resources for libtensorflow-lite.a
7f190ecb9f TFLite: tools: make: remove hash and flags files from the build sources for libtensorflow-lite.a
dcb6a33c40 Update Makefile of TFLite not to include main() function

### CODE REVIEW

**Comment by gbaned** [comment]
@terryheo Can you please sign CLA? Thanks!

**Comment by terryheo** [comment]
@googlebot I consent.

**Comment by terryheo** [comment]
@vinceab could you consent cherry-picking your changes into r2.1 branch?

**Comment by vinceab** [comment]
@googlebot I consent.

**Review by abattery — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Note though that we can only merge this when we do a new patch release.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
