### PR TITLE
typos in tensorflow/core fixed

### PR DESCRIPTION
**Pull request by siju-samuel**

### CODE REVIEW

**Review by Harshini-Gadige — DISMISSED** [review]

**Comment by rthadur** [comment]
@siju-samuel gentle ping to resolve conflicts

**Comment by siju-samuel** [comment]
@rthadur thank you for notifying, conflicts are resolved. @hgadig gentle ping to approve again.

**Review by Harshini-Gadige — APPROVED** [review]

**Comment by siju-samuel** [comment]
@rthadur could you please help to merge this pr. thank you.

**Comment by siju-samuel** [comment]
@rthadur i could see the changes are there in master, but the PR is still open. This PR should go to merged state, right?

**Comment by rthadur** [comment]
@siju-samuel as the changes are merged , can i close this PR

**Pull request closed without merging**
