### PR TITLE
Basic Elementwise OP Reciprocal for TFLITE

### PR DESCRIPTION
**Pull request by siju-samuel**
Implemented basic elementwise op reciprocal.

### CODE REVIEW

**Review by karimnosseir — CHANGES_REQUESTED** [review]
Please add test coverage in
tensorflow/lite/testing/generate_examples_lib.py

Thanks

**Comment by jdduke** [comment]
I don't think this is related to issue #22384. For issue #26869, can you tell if reciprocal is used in conjunction with the gradient ops or that portion of the training graph.

**Comment by gbaned** [comment]
@siju-samuel could you please resolve the conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@siju-samuel could you please resolve the conflicts and keep us posted? Thanks!

**Comment by gbaned** [comment]
@siju-samuel Did you get a chance to look on reviewer(jdduke's) comments? Please let us know on the update. Thanks!

**Comment by jdduke** [comment]
Before adding this, I'd rather we explore expanding this op into fill(1) -> div(x) in the converter. That way we can take advantage of existing accelerators without requiring a new op.

**Comment by gbaned** [comment]
@siju-samuel  Could you please address the jdduke's comments. Thanks!

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
