### PR TITLE
updated TensorFlow official example: cifar10

### PR DESCRIPTION
**Pull request by wqj97**
I found a problem in the official example: cifar10

It not working in the newest TensorFlow because of API change.

But it's an excellent tutorials for newcomer.

So i updated it and hope more people could see it.

Except API changes,I didn't do any other change.

I hope this tutorials can add to official example again.

### CODE REVIEW

**Comment by wqj97** [comment]
I signed it!

**Comment by wqj97** [comment]
Please check this~

**Comment by vincentvanhoucke** [comment]
The files are all in a cfair10/ directory, instead of cifar10/, can you check?

**Comment by wqj97** [comment]
Sorry~
now moved

**Comment by jhseu** [comment]
Can you update it in the models repo instead?
https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10

**Pull request closed without merging**
