### PR TITLE
[Pluggable Device] Add custom device mem allocator for Pluggable device.

### PR DESCRIPTION
**Pull request by kulinseth**
The commit provides a simple alternative to BFCAllocator for Pluggable devices
to do their own device memory management.

@penpornk , @annarev , @jzhoulon

### CODE REVIEW

**Review by penpornk — CHANGES_REQUESTED** [review]
Thank you very much for the PR! I think you forgot to add `pluggable_device_simple_allocator.cc` and `pluggable_device_simple_allocator.h`?

**Comment by kulinseth** [comment]
> Thank you very much for the PR! I think you forgot to add `pluggable_device_simple_allocator.cc` and `pluggable_device_simple_allocator.h`?

Ah, thanks!. Added it.

**Review by penpornk — APPROVED** [review]
Thank you for the changes!

**Comment by rthadur** [comment]
@kulinseth can you please check sanity build failures ?

**Comment by penpornk** [comment]
@rthadur They are minor formatting errors. In the interest of time (since the branch cut is next week), I'll just manually import the PR and fix them. :) I'm just waiting for the `oneDNN` and `Windows Bazel GPU` CI builds to finish.

**Comment by kulinseth** [comment]
Thanks a lot @penpornk. Please let me know if there is needed form my side.

**Pull request merged**
