### PR TITLE
Enhance cuda kernel helper.

### PR DESCRIPTION
**Pull request by yangyanli**
Changes on functionality:
1. Use native atomicAdd for double if `__CUDA_ARCH__ >= 600`.
2. Add max wrappers for float, double and Eigen::half.
3. Add `SetConstant` and `ReplaceValue` kernels. They are useful for example, when doing element-wise max: `SetConstant` to MIN, do max(), then `ReplaceValue` MIN with some friendly values, like zeros.

Changes on readability:
1. `SetZero(const int nthreads, T* bottom_diff)` to `SetZero(const int nthreads, T* data)`, `bottom_diff` maybe is from Caffe ;-), and is irrelevant here.
2. Reorder Add and Max wrappers, to make them better grouped together.

### CODE REVIEW

**Comment by yangyanli** [comment]
I signed it!

**Comment by drpngx** [comment]
Could we add a test for this?

**Comment by yangyanli** [comment]
Sure! I know how to write a test for an op in python, but what's the best practice for writing a test for these kind of lower level functions? Any code I can follow?

**Comment by jlebar** [comment]
It looks like there are a number of independent changes in this patch.  Can you please split them up into separate commits?  (You can leave it as one PR if you like, or split it up into multiple PRs.)

Splitting up the patch makes our lives as reviewers much easier, since the difficulty of reviewing a patch is roughly quadratic in the size of the patch.  It also makes it easier for us to verify that each change is appropriately tested.

Feel free to ask if you need help with the git commands for splitting up the change.  There are lots of tutorials on the web, but in general, `git add -p`, `git commit --amend` and `git rebase -i` are your friends.

**Comment by rmlarsen** [comment]
@yangyanli could you address @jlebar's comments, please?

**Comment by yangyanli** [comment]
I've done the commit splits @jlebar @rmlarsen . Will add the tests as suggested by @drpngx soon, as it's during my Chinese New Year ;-)

**Comment by yangyanli** [comment]
Hi @drpngx I've added a bit test for it, in commit 28fd861, however, I cannot get it compile. Could you help on it?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
What error are you getting?

**Comment by drpngx** [comment]
You are including `thrust/host_vector.h`. It's not part of our dependencies. Can you do without it?

**Comment by vrv** [comment]
Any updates @yangyanli  ?

**Comment by vrv** [comment]
Closing for now to keep our open PR list smaller, but please feel free to open another PR once you have time to contribute this -- it's very much appreciated!

**Pull request closed without merging**
