### PR TITLE
[GPU][ROCm][CUDA] StreamExecutor logic for ROCm / CUDA platform (PR 20709 / 22669 / 24156 continued)

### PR DESCRIPTION
**Pull request by whchung**
New PR to continue the efforts started by @deven-amd in #20709 / #22669 / #24156.

This PR aims to refactor StreamExecutor GPU interfaces so it can be shared among CUDA and ROCm. The PR would be the first part of a series of PRs.

Based on @timshen91 's inputs, I've refactored logic in #214156 so :

- only contains changes in stream_executor/....
- does not remove any stream_executor/cuda/*.h, so that things outside of stream_executor don't break. All the types and functions in the namespace cuda now alias to namespace gpu counterparts. For example, namespace cuda { using CUDADriver = gpu::GpuDriver; }.
- all stream_executor/gpu/BUILD targets should be only visible to //third_party/tensorflow/stream_executor:__subpackages__.
- target stream_executor/gpu:X should be only used by stream_executor/cuda:cuda_X or stream_executor/rocm:rocm_X, not cuda_Y. For example, cuda:cuda_platform should depend on cuda:cuda_driver, not gpu:gpu_driver.

### CODE REVIEW

**Comment by whchung** [comment]
@timshen91 I've finished addressing your comments in #24156 and revise the PR here. The most noticeable change is that no operators/XLA logic are changed, plus all CUDA SE headers are retained. All known good tests are now passing. Logs in those 4 failing test targets suggest those failures are irrelevant to this PR. Would you mind take another look at this PR? Thanks.

**Comment by whchung** [comment]
@timshen91 a gentle ping

**Comment by whchung** [comment]
@timshen91 Could you help advise how to move this PR forward? Just a heads up I'm working on getting ROCm components dynamically loaded like their CUDA counterparts and will likely come up with another PR later this week or early next week. But without getting this PR landed it's hard for us to submit new ones for StreamExecutor on ROCm.

**Comment by timshen91** [comment]
Sorry for the delay. I'm looking at this PR today.

**Review by timshen91 — DISMISSED** [review]

**Comment by timshen91** [comment]
@whchung, I'm trying to integrate. In the mean time, can you fix the commit by adding back cuda_helpers.h and the build target "cuda_helpers"?

**Comment by whchung** [comment]
ok let me restore the target

**Comment by whchung** [comment]
@timshen91 Just restored `cuda_helpers.h` along with all its usages.

**Comment by timshen91** [comment]
About:
  target stream_executor/gpu:X should be only used by stream_executor/cuda:cuda_X or stream_executor/rocm:rocm_X, not cuda_Y. For example, cuda:cuda_platform should depend on cuda:cuda_driver, not gpu:gpu_driver.

Can you also grep cuda/ for `#include.*gpu/gpu_`, and replace the ones with `cuda/cuda_*`? I'm doing the same thing locally so that I don't have to wait on your changes.

**Comment by timshen91** [comment]
One more thing: can you apply the same kind of changes I did in commit bc4a279?

**Comment by whchung** [comment]
@timshen91 I believe changes in https://github.com/tensorflow/tensorflow/commit/bc4a279ca963a901576a9a7a35b189dfae7f5c85 had been incorporated in this PR already.

**Comment by whchung** [comment]
@timshen91 Just to clarify, do you wish to have `if_rocm_is_configured` be guarded against build targets in `tensorflow/stream_executor/rocm/BUILD`?

**Comment by whchung** [comment]
@timshen91 I reviewed my latest commit and found some anomalies. Working on resolving them.

**Comment by whchung** [comment]
@timshen91 a gentle ping again. I've resolved the conflicts with master.

**Comment by whchung** [comment]
@timshen91 ping?

**Comment by whchung** [comment]
+ @deven-amd @dagamayank

**Comment by whchung** [comment]
@timshen91 It seems the PR was merged by you after some changes on your side. I'll close the PR. Thanks!

**Comment by whchung** [comment]
@timshen91 Thanks. Let me digest the commit you just made first. Also I'd like to understand a bit on the recent changes in StreamExecutor and the general direction we are moving to:

- StreamExecutor now loads CUDA libraries dynamically, instead of dynamically linked with CUDA libraries: I think this part is rather clear to me and I've been working on getting a PR for that now.
- On the other hand, other parts of TensorFlow (`grappler`, `core/common_runtime`, implementations of certain TensorFlow operators) still have static dependency to CUDA/HIP runtime APIs. Would they also migrate toward dynamically loaded scheme?

**Comment by whchung** [comment]
@timshen91 also I'd like to understand better about what do you mean by:

- keep `gpu/*` private `cuda/*` / `rocm/*` private to `//tensorflow/stream_executor/...`

In TensorFlow we can see logic using `stream_executor::cuda` right now, they are not completely abstracted by interfaces within `stream_executor_pimpl.h`. Moving forward, do you anticipate everything be hidden by StreamExecutor interfaces defined in `stream_executor_pimpl.h`? Or would we expose some details via `stream_executor::gpu` namespace?

**Comment by timshen91** [comment]
> @timshen91 Thanks. Let me digest the commit you just made first. Also I'd like to understand a bit on the recent changes in StreamExecutor and the general direction we are moving to:
> 
> * StreamExecutor now loads CUDA libraries dynamically, instead of dynamically linked with CUDA libraries: I think this part is rather clear to me and I've been working on getting a PR for that now.

Yes. The goal is to be able to build "core tensorflow" + "CPU and GPU stream_executor" without depending on cuda libraries like cudnn at build time. The built binary should also work on a non-GPU machine.

> * On the other hand, other parts of TensorFlow (`grappler`, `core/common_runtime`, implementations of certain TensorFlow operators) still have static dependency to CUDA/HIP runtime APIs. Would they also migrate toward dynamically loaded scheme?

My understanding is that either the build-time dependencies will be removed, or excluded from "core tensorflow". For example, TF ops won't be part of of "core tensorflow", so it's fine to have build-time CUDA dependencies in them.

**Comment by timshen91** [comment]
> @timshen91 also I'd like to understand better about what do you mean by:
> 
> * keep `gpu/*` private `cuda/*` / `rocm/*` private to `//tensorflow/stream_executor/...`

My bad, I meant "keep ... private as much as possible", and of course excluding the dnn/blas libraries.

> 
> In TensorFlow we can see logic using `stream_executor::cuda` right now, they are not completely abstracted by interfaces within `stream_executor_pimpl.h`. Moving forward, do you anticipate everything be hidden by StreamExecutor interfaces defined in `stream_executor_pimpl.h`? Or would we expose some details via `stream_executor::gpu` namespace?

Let me take a step back. It's actually an open topic and I'd like your opinions. The constraints we have are:
* For portable code, we already have a portable layer `stream_executor_pimpl.h`, so we don't want to have a second portable layer. That will be a source of confusion and inconsistency.
* For non-portable code, by definition it is insufficient to solely use `gpu/...`. In that case, the user should seek one of the backends `cuda/...` or `rocm/...`.
* In general we try to minimize the non-portable code.

Thus I tentativelly draw the conclusion that targets in `gpu/...` shouldn't be public outside of `stream_executor`. This has nothing to do with `namespace gpu`. The uses of `namespace gpu` probably should go as originally planned.

**Pull request closed without merging**
