### PR TITLE
Add dict(features) instead of features in beginners guide

### PR DESCRIPTION
**Pull request by kamilogerto2**

### CODE REVIEW

**Comment by kamilogerto2** [comment]
cla agreement

**Comment by ifulmirwanda** [comment]
Stop send Gmail for me anjeng

Pada tanggal 22 Feb 2018 5.22 PM, "Iful Mirwanda" <kursiwayang@gmail.com>
menulis:

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
