### PR TITLE
Updated arena_planner.cc

### PR DESCRIPTION
**Pull request by amitsrivastava78**
Fixed the warning (comparison between signed and unsigned integer)

### CODE REVIEW

**Comment by rthadur** [comment]
@amitsrivastava78 thank you so much for your contribution , instead of multiple PR's , is it possible to combine these PR's : [26186](https://github.com/tensorflow/tensorflow/pull/26186) , [26185](https://github.com/tensorflow/tensorflow/pull/26185) , [26184](https://github.com/tensorflow/tensorflow/pull/26184)

**Review by shahzadlone — DISMISSED** [review]

**Comment by amitsrivastava78** [comment]
@rthadur , thanks for your comments, Since these PRs are approved i will try to group the similar PRs together in future.

**Comment by shahzadlone** [comment]
@rthadur I think you should group these ones together as well.

**Comment by shahzadlone** [comment]
@amitsrivastava78  I think you should group these ones together as well.

**Comment by amitsrivastava78** [comment]
@shahzadlone and @rthadur, I will merge the PRs tomorrow

**Comment by amitsrivastava78** [comment]
@shahzadlone & @rthadur , i have merged all the requested PR, kindly review and approve.

Regards
Amit

**Comment by rthadur** [comment]
Thank you Amit ,we appreciate your contribution , going forward please submit related PR's in one request, so that it is easy get in to the system.

**Review by shahzadlone — DISMISSED** [review]

**Comment by amitsrivastava78** [comment]
@shahzadlone , i have rebased and merged the code again, can you kindly approve again.

**Review by shahzadlone — APPROVED** [review]

**Comment by amitsrivastava78** [comment]
@rthadur, this PR is approved, can you please change the label to Ready to pull.

**Comment by amitsrivastava78** [comment]
Closing the PR as similar PR is merged.

**Pull request closed without merging**
