### PR TITLE
Add fp32 accumulation for depthwise convolutions

### PR DESCRIPTION
**Pull request by MattConley**
-Also remove check for pre-Maxwell architectures, since all fp16 kernels will have fp32 accumulation

### CODE REVIEW

**Comment by chsigg** [comment]
Hi Matt. Thank you very much for this PR. I will review and merge it, hopefully early next week.

**Comment by MattConley** [comment]
Sounds good, thanks.

**Review by chsigg — COMMENTED** [review]
S is now always equal to PseudoHalfType<T>, correct? Shouldn't we remove the template parameter?

Also, do you want to do a similar change for filter backprop?

**Comment by MattConley** [comment]
Good points, thanks for the suggestions!

I've removed the template parameter and restructured the accumulation type definition.

As for the filter backprop, the one kernel which didn't have fp32 accumulation looks to be written in a way that adding it would be non-trivial.  As soon as each partial sum is calculated, it is immediately atomically added to the output address.  Aside from rewriting the kernel, I'm not sure if there's a good way to add this feature.

I've added a TODO for now, what do you think would be best?

**Review by chsigg — APPROVED** [review]

**Pull request merged**
