### PR TITLE
Remove duplicated NanLossDuringTrainingError in graph_action

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Test this please

**Comment by terrytangyuan** [comment]
Sanity checks and TF.org failed. Testing again. 
@tensorflow-jenkins Test this please

**Comment by terrytangyuan** [comment]
I don't think the test failures are related with my changes. Could someone else take a look?

**Comment by vrv** [comment]
@tensorflow-jenkins test this please  
(looks like the lint errors were pre-existing, maybe they've been updated, trying again)

**Pull request merged**
