### PR TITLE
Update saturate_cast args

### LINKED ISSUE #58053: tf.saturate_cast errors for tf.complex type tensor
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.5 LTS

### Mobile device

_No response_

### Python version

 3.8.10

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current Behaviour?

```shell
From code below, the tf.saturate_cast need to check dtype's min
https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/ops/math_ops.py#L713-L743

However, from code below, min is not support for complex64 or complex128
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/compat/tensorflow_stub/dtypes.py#L188-L194

The documentation for tf.saturate_cast said it support any tensor or dtype desired. Therefore, either code or documentation need to be changed
https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/ops/math_ops.py#L716-L729
```

### Standalone code to reproduce the issue

```shell
Code like: 

import tensorflow as tf
arg_0_tensor = tf.complex(tf.random.uniform([2, 1], dtype=tf.float32),tf.random.uniform([2, 1], dtype=tf.float32))
arg_0_tensor = tf.saturate_cast(arg_0_tensor,dtype=tf.float32)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/dtypes.py", line 110, in min
    raise TypeError(f"Cannot find minimum value of {self} with "
TypeError: Cannot find minimum value of <dtype: 'complex64'> with type <dtype: 'complex64'>.
```
</details>

### PR DESCRIPTION
**Pull request by sachinprasadhs**
Updated saturate_cast args to list the supported dtypes.
Fixes: https://github.com/tensorflow/tensorflow/issues/58053

### CODE REVIEW

**Comment by cantonios** [comment]
We don't usually list dtypes like this in the documentation unless there is a good reason to restrict the set of types.  Otherwise, if we ever register a kernel for a new type, we would have to go through and update all the documentation.  In most cases, calling an op on an unsupported type will automatically list the ones that _are_ supported.

**Comment by sachinprasadhs** [comment]
Understood, In this case it is throwing an error due to one of the internal checks. Do we keep it as it is and close this bug?

**Comment by mihaimaruseac** [comment]
Please write better commit messages and PR titles. https://cbea.ms/git-commit/

**Comment by bhack** [comment]
>  Otherwise, if we ever register a kernel for a new type, we would have to go through and update all the documentation.

We cannot solve the problem with this PR.
The only real solution here is to create a template in the docstrings that could be filled using the kernel registration factory to regenerate the documentation. But considering how many ops we have accumulated it will be hard to allocate resources on this activity and probably it will be also complicated by the devices divergences (I don't have a stat on these).

**Comment by cantonios** [comment]
We've got a documentation fixit coming up next week, so I'll fix this then on our end.  Might be better to support the same types between `cast` and `saturate_cast`, where the latter will saturate by real/imag components separately for complex inputs.  That's probably what one would expect when converting from complex128 to complex64.

**Pull request closed without merging**
