### PR TITLE
[XLA] Allow for disabling these tests via manifest

### PR DESCRIPTION
**Pull request by DavidNorman**
Allow this test to be disabled via the manifest file.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by DavidNorman** [comment]
@vrv @hawkinsp  

Hi guys.  Sorry to pester you,  but I think that this minor change has been overlooked.

**Review by hawkinsp — APPROVED** [review]

**Comment by DavidNorman** [comment]
Is there a need to add a tag to make the test happen?

**Comment by DavidNorman** [comment]
cheers :)

**Comment by hawkinsp** [comment]
Sorry this took a while to commit. I don't review a lot of Github PRs so I didn't press the right buttons. I'll get it right next time :-)

**Pull request merged**
