### PR TITLE
op not register

### PR DESCRIPTION
**Pull request by formath**
1. add op to `tensorflow/contrib/makefile/tf_op_files.txt` to fix problem of `op not registered`
2. fix header and source not found problems when using `build_all_linux.sh`

### CODE REVIEW

**Comment by formath** [comment]
@vrv

**Comment by formath** [comment]
@ekelsen checks blocked?

**Comment by formath** [comment]
@petewarden Please give a review.

**Comment by formath** [comment]
@petewarden Review needed. Thanks

**Comment by formath** [comment]
@ekelsen @petewarden

**Comment by formath** [comment]
@martinwicke @petewarden Please give a review.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 29 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 45 days with no activity and the `awaiting review` label has been applied.

**Comment by formath** [comment]
@petewarden Please add a review or reassign. Thanks.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Pull request closed without merging**
