### PR TITLE
[ROCm] Adding new CI scripts for ROCm platform

### PR DESCRIPTION
**Pull request by deven-amd**
This PR adds new scripts for running CI jobs on the ROCm platform
 * `tensorflow/tools/ci_build/linux/rocm/run_cpu.sh` - this mirrors the functionality of upstream CI job - `Ubuntu CPU`
 * `tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh` - this mirrors the functionality of upstream CI job - `Linux GPU`  (but for ROCm instead of CUDA)
 * `tensorflow/tools/ci_build/linux/rocm/run_gpu_multi.sh` - Variant of `Linux GPU` for tests with the `multi_gpu` tag

These new CI scripts will replace the existing ones
 * `tensorflow/tools/ci_build/linux/rocm/run_cc_core.sh`
 * `tensorflow/tools/ci_build/linux/rocm/run_csb_core.sh`
 * `tensorflow/tools/ci_build/linux/rocm/run_py3_core.sh`
 * `tensorflow/tools/ci_build/xla/linux/rocm/run_py3.sh`

The old CI scripts will removed in a separate PR, once the transition to the new CI scripts is completed.

-------------------------------------------

/cc @rsanthanam-amd @cheshire @chsigg @nvining-work

### CODE REVIEW

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
