### PR TITLE
[TFLite] Add int16x8 support for ARG_MIN and ARG_MAX operators

### PR DESCRIPTION
**Pull request by johan-gras**
Hello,

This PR adds int16x8 support for ARG_MIN and ARG_MAX operators.

Thanks,
Johan.

### CODE REVIEW

**Comment by gbaned** [comment]
@miaout17 Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@miaout17 Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
Hi @johan-gras Can you please resolve conflicts? Thank you!

**Comment by Tessil** [comment]
@gbaned Would it be possible to reopen this PR? Thanks!

**Pull request closed without merging**
