### PR TITLE
Update docstrings in upgrade_schema.py

### PR DESCRIPTION
**Pull request by siju-samuel**
Update the missed RuntimeError and ValueError in upgrade_schema.py

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle, @jianlijianli: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle, @jianlijianli: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by jianlijianli** [comment]
Adding gargn@ for review.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by siju-samuel** [comment]
@jianlijianli @gargn please help to review this changes

**Review by gargn — APPROVED** [review]

**Pull request merged**
