### PR TITLE
2.1-RC0 cherry-pick request: [tf.data] Improvements to cancellation logic.

### PR DESCRIPTION
**Pull request by jsimsa**
This CL:
    - makes sure that a previously cancelled input pipeline won't hang in ParallelMapDataset kernel
    - excludes errors::Cancelled() from being ignored by the IgnoreErrorsDataset kernel to avoid infinitely looping after a cancellation
    
    PiperOrigin-RevId: 280425330
    Change-Id: If210c94c59e3b33b170e77aea6c87308241364e6

### CODE REVIEW

**Review by goldiegadde — APPROVED** [review]

**Comment by goldiegadde** [comment]
@jsimsa 
Jiri, https://github.com/tensorflow/tensorflow/pull/34241 has been merged, do you want to remove that from this commit or is it a noop.

**Comment by jsimsa** [comment]
I resolved the merge conflict.

**Comment by jsimsa** [comment]
Alternatively, I can create a new cherrypick with just one commit if you would prefer that.

**Review by alextp — APPROVED** [review]

**Comment by goldiegadde** [comment]
@jsimsa awesome thanks, once the tests complete. I will merge it in

**Pull request merged**
