### PR TITLE
fix small typo in contrib.metrics.confusion_matrix docs, and use less…

### PR DESCRIPTION
**Pull request by ichuang**
… confusing variable

### CODE REVIEW

**Comment by ichuang** [comment]
CLA signed

**Comment by rmlarsen** [comment]
What do you have against the letter l?

**Comment by ichuang** [comment]
When rendered by github, in this context, the letter I looks like a vertical bar:

image

and this makes it appear unfortunately like incomplete [density matrix notation](https://en.wikipedia.org/wiki/Density_matrix).

**Comment by rmlarsen** [comment]
OK, I don't object to k either.

**Pull request merged**
