### PR TITLE
[XLA/tfcompile] Implement mkstemps for MSVC

### PR DESCRIPTION
**Pull request by rongjiecomputer**
`mkstemps` used in `SaveGraph` is not available on Windows.

Implementation adapted from https://github.com/git-for-windows/git/blob/master/wrapper.c#L470.

### CODE REVIEW

**Comment by snnn** [comment]
Hi,

Is it possible to reuse one of the functions like _mktemp_s?

**Comment by rongjiecomputer** [comment]
@snnn I afraid not. MSVC only has `mkstemp` which can transform `prefixXXXXXX` to `prefix123456`. However, [`SaveGraph`](https://github.com/rongjiecomputer/tensorflow/blob/25713bf9e1e955f176452c1e1962ae19e79c2670/tensorflow/compiler/xla/service/hlo_graph_dumper.cc#L1427) needs `mkstemps` which can transform `prefixXXXXXXsuffix` to `prefix123456suffix`.

**Comment by jlebar** [comment]
It looks like this function is GPL2 (and copyrighted).

I think someone will need to do a cleanroom implementation of this function, or find a more permissive version to copy.  You probably can't do a cleanroom implementation yourself, because you've already written this patch.

Sorry.  :(

**Review by jlebar — CHANGES_REQUESTED** [review]
Adapted from GPLv2 code, cannot merge.

**Comment by rongjiecomputer** [comment]
@jlebar The implementation is licensed under LGPL actually, but still incompatible with Apache 2.0. All implementation of mkstemp[s] I can find (including [StackOverflow](https://stackoverflow.com/questions/6036227/mkstemp-implementation-for-win32)) are licensed under LGPL.

Can you check what is the license used in https://github.com/Alexpux/mingw-w64/blob/b028d1b994ab601843a518a2e4ad0d74a05e9569/mingw-w64-crt/misc/mkstemp.c ? It seems to be licensed under ZPL (see https://github.com/Alexpux/mingw-w64/blob/b028d1b994ab601843a518a2e4ad0d74a05e9569/COPYING)

**Comment by jlebar** [comment]
> https://github.com/Alexpux/mingw-w64/blob/b028d1b994ab601843a518a2e4ad0d74a05e9569/mingw-w64-crt/misc/mkstemp.c seems to be licensed under ZPL

Looks like it to me as well, but we'd have to have a lawyer verify that this is the case and that it's compatible with Apache 2.

Finding someone to reimplement from scratch seems easier to me personally.

Alternatively, perhaps we could rework the hlo graph dumper not to rely on mkstemps?

**Comment by rongjiecomputer** [comment]
> Alternatively, perhaps we could rework the hlo graph dumper not to rely on mkstemps?

Seems reasonable. I can reuse some bits of Env::LocalTempFilename from [1]. I will preserve the ability to specify prefix and suffix, but the random part in the middle of file name will not be the same as mkstemps. Hope the original author of SaveGraph does not mind about this.

[1]: https://github.com/tensorflow/tensorflow/blob/3f0bb2d81da930a6070412bea412677edd79005c/tensorflow/core/platform/env.cc#L284

**Comment by rongjiecomputer** [comment]
Obsolete.

**Pull request closed without merging**
