### PR TITLE
[TFLite] Minor improvement of static build

### PR DESCRIPTION
**Pull request by FloopCZ**
- Include the experimental API in the static library. It is already included when building via Bazel.
- Build static library with position independent code to allow its integration into dynamic libraries.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Review by petewarden — APPROVED** [review]
Looks good, thanks for this!

**Pull request merged**
