### PR TITLE
2.0.0-rc1 cherry-pick request: Import submodules using relative imports.

### PR DESCRIPTION
**Pull request by annarev**
Import submodules using relative imports. This fixed a lot of the autocomplete (although not everything).

### CODE REVIEW

**Comment by annarev** [comment]
Seems like MacOS build failed. I will take a look.

**Comment by annarev** [comment]
I think MacOS build might be failing because tensorboard it picks up doesn't have this change: https://github.com/tensorflow/tensorboard/pull/2593

I will verify it though.

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by annarev** [comment]
So, the issue here is that tensorboard pip package is not installed. This change adds a test that tf.summary.image is available. This symbol is available in V1 without installing tensorboard, but would fail for r2.0 branch without the pip.

Now, I got the package installed for the MacOS build but Ubuntu CPU still doesn't have it.

**Comment by annarev** [comment]
TensorBoard is harder to install for Linux CPU build. So, for now I just disabled the test (added by this change) if `tensorboard` pip is not available.

**Review by goldiegadde — APPROVED** [review]

**Pull request merged**
