### PR TITLE
Fix in resource var AssignVariableOp Compute

### PR DESCRIPTION
**Pull request by AyanmoI**
Add check in AssignVariableOp in resource_var_ops.cc similar to XlaAssignVariableOp::Compute in xla_device_ops.cc

### CODE REVIEW

**Comment by allenlavoie** [comment]
What is this fixing? I assume XLA only has this check because it uses DT_INVALID for uninitialized variables. I don't think we want to allow variables to be initialized with different dtypes than they were declared with.

**Comment by AyanmoI** [comment]
This change does not allow variables to be initialized with different dtypes than they were declared with. This only allows for the update to happen first by the AssignVariableOp, in which case it's still uninitialized. 
It is possible that this scenario never occurs in Tensorflow. However, when using TF-XLA, this scenario is possible when the execution uses the 'fallback' path (which essentially invokes Tensorflow ops via partitioned_call).

**Comment by allenlavoie** [comment]
Can you add a test? I'd also suggest checking explicitly for DT_INVALID, to avoid making this check more lax for non-XLA (in which case the correct dtype should come from the original VarHandleOp).

**Comment by bas-aarts** [comment]
Explicitly checking for DT_INVALID means that an uninitialized variable can have a type other than DT_INVALID. That sounds incorrect (adding the check might lead developers to believe the check is required)
Regretfully we cannot reproduce the issue against an OOTB TF. We've made a change in the XLA compilation strategy such that the fallback path is always executed before the compiled path. This is what causes the AssignVariableOp to be executed before the XlaAssignVariableOp.

**Comment by allenlavoie** [comment]
Do you know which part of TF-XLA is creating the resource (with a `Var` and the wrong dtype) but not initializing it?

**Comment by bas-aarts** [comment]
> Do you know which part of TF-XLA is creating the resource (with a `Var` and the wrong dtype) but not initializing it?

There is no wrong type, unless you deem DT_INVALID a wrong type.

**Comment by allenlavoie** [comment]
So it is DT_INVALID? And do you know where that's set?

The code as-is does include uninitialized variables with real dtypes set (on uninitialized `variable->tensor()`s). If you have two `AssignVariableOp`s racing to initialize the same handle, one will create the resource and one will grab `variable->mu()` first, but it's not necessarily the same one, and if it isn't then the other will see the resource creator's "real dtype but not initialized" Var. I guess you could argue that this is bad and DT_INVALID is nicer, but they just seem like slightly different conventions to me, and setting the dtype carries a bit more information. So I don't understand the pushback on limiting this to ((DT_INVALID && uninitialized) || same_dtype) with a comment that this is XLA's convention.

If we don't want to accept that both conventions are OK, it seems like we should change one of them. So either set the variable's real dtype in XLA or always use DT_INVALID when creating the resource. Those sound OK but are probably larger changes.

**Comment by bas-aarts** [comment]
"So it is DT_INVALID? And do you know where that's set?"
it's set in GetVariableInfosFromInputs:
          // This var is uninitialized for now.
          *ptr = new Var(DT_INVALID);

"The code as-is does include uninitialized variables with real dtypes set"
Yes it does, but so does the code in XlaAssignVariableOp::Compute, which doesn't check for uninitialized variables with a type either. We choose for symmetry with existing code here, and rely on uninitialized variables to have DT_INVALID type.

**Comment by allenlavoie** [comment]
Let's only loosen the check here to the extent we need. It's OK if it's slightly different than XlaAssignVariableOp::Compute.

**Comment by AyanmoI** [comment]
@allenlavoie Incorporated your comment. Please take a look.

**Review by allenlavoie — APPROVED** [review]
Awesome, thank you for your patience.

**Pull request merged**
