### PR TITLE
Fixed contrib warning, removing duplicate 'WARNING'

### PR DESCRIPTION
**Pull request by jchia**
Remove duplicate "WARNING" from the contrib warning message.

### CODE REVIEW

**Comment by jchia** [comment]
This should fix #27045.

**Review by dynamicwebpaige — DISMISSED** [review]
LGTM! Thanks for the fix, and for noticing that the issue you referenced was not resolved. We appreciate it! 🙂

**Comment by jchia** [comment]
I couldn't see the details of the build failures and only got "Oops, page not found."

I doubt I broke the build though. Is there anything for me to do now to get the PR merged?

**Comment by mihaimaruseac** [comment]
The only new releases to 1.13 are security fixes and patches. Would be better to rebase this to work on master (that's why builds failed).

**Comment by jchia** [comment]
I'm uncertain about the release implications of the master branch. Is the
code in the master branch destined for v1, v2 or both? I was under the
impression that there won't be a v1.14.

**Comment by mihaimaruseac** [comment]
There will be a 1.14.

I'll review again once conflicts are resolved.

**Comment by jchia** [comment]
It appears that in the master branch, 64e362bb already mostly fixes the problem, but 'WARNING' is repeated.

**Comment by martinwicke** [comment]
Can you make this against master? We are not taking PRs directly against the release branches that are not on master first. I don't think we'd want to make a patch for the aestetics, but thank you for the fix!

**Comment by martinwicke** [comment]
oh. you just did. Never mind me.

**Review by martinwicke — APPROVED** [review]

**Comment by jchia** [comment]
I think the PR is already destined for matter, although the branch name in
my GitHub fork is still r1.13. Sorry for the confusion of not initially
using master. I didn't know the branch policy.

**Comment by mihaimaruseac** [comment]
It got merged, I think this PR can be closed

**Pull request closed without merging**
