### PR TITLE
Apply check for avoiding printout broken of Fit method

### PR DESCRIPTION
**Pull request by shubham769**
The out-prints of in the fit method in version 2.1 as per mentioned in issue  #36332.
This PR applied a check for the same case.

### CODE REVIEW

**Comment by shubham769** [comment]
@rchao please review this change

**Review by rchao — CHANGES_REQUESTED** [review]
Thanks for the PR! Can you add a test covering the change and correct the syntax error?

**Comment by gbaned** [comment]
"We are closing this PR as it has been copied from somebody else. This behavior is unethical and runs contrary to our TensorFlow Code of Conduct. Please do not do this. If you continue to plagiarize work, we will ban you from the project."

**Comment by mihaimaruseac** [comment]
Hei @shubham769 we see that you are again trying to plagiarize PRs from other persons. Please stop.

**Pull request closed without merging**
