### PR TITLE
[CMake] Optionally support building TF as a shared lib

### PR DESCRIPTION
**Pull request by vit-stepanovs**
Currently, TF is already built as a shared library that is included in the Python package. However, that library:

1. Is implicitly linked against Python libs, and thus expects Python to be present on the machine wherever it is used. It is undesirable for scenarios not requiring Python (e.g. native application that need TensorFlow).
2.  Does not include the TF C++ API.

This PR allows optionally building TF as a stand-alone DLL that does not have the above issues. I am also working on allowing CMake to link all C++ tests against that DLL, and will submit such changes in a separate PR.

As a bonus, this PR also fixes a build break for tf_tools.cmake when GPU is enabled.

### CODE REVIEW

**Comment by mrlzla** [comment]
It seems like you save my life ;) Thank you!

**Comment by tomjaguarpaw** [comment]
@vit-stepanovs I should run cmake with `-DBUILD_SHARED_LIB=ON` but then what build target do I run?

**Comment by vit-stepanovs** [comment]
@tomjaguarpw, the actual option name is tensorflow_BUILD_SHARED_LIB, not BUILD_SHARED_LIB. If you use that, cmake generates a project tensorflow.vcxproj (not tensorflow.sln!) which you can use to build the DLL.

**Comment by drpngx** [comment]
Nice!

LGTM, @mrry what do you think?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by mrry — APPROVED** [review]
Looks good to me too!

**Comment by drpngx** [comment]
Thanks!

**Comment by ivan-aksamentov** [comment]
It works great on both Linux and Windows for me. Why is this PR removed from release 1.1.0? (it was there in 1.1.0-rc2)

**Comment by drpngx** [comment]
It's probably because it didn't make it before the cutoff point when we forked the branch.

/CC: @av8ramit

**Comment by av8ramit** [comment]
I don't believe this was in 1.1.0-rc2, but yes we decided to push it back to 1.2 since it was merged too late for 1.1 to test properly.

**Comment by mrlzla** [comment]
Is there some way to build tensorflow as static lib?

**Comment by adennie** [comment]
I tried this in conjunction with https://github.com/tensorflow/tensorflow/pull/9666 to try to build a debug DLL,, but the generated .def file had over 120K symbols, so it exceeded the 65535 limit.  Any way to filter more aggressively?

**Comment by drpngx** [comment]
@girving another reason to restrict symbols #9525

On May 12, 2017 1:24 PM, "Andy Dennie" <notifications@github.com> wrote:

I tried this in conjunction with #9666
<https://github.com/tensorflow/tensorflow/pull/9666> to try to build a
debug DLL,, but the generated .def file had over 120K symbols, so it
exceeded the 65535 limit. Any way to filter more aggressively?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/pull/9124#issuecomment-301176827>,
or mute the thread

**Comment by girving** [comment]
Nice.  Is there a thread I should notify once we make progress here?  This one seems merged.

**Pull request merged**
