### PR TITLE
Update download_and_extract script for faster CMSIS patching

### LINKED ISSUE #44013: Patching CMSIS source file takes a lot of time
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): 261bc3aba4e5c1611a417cf9d916c916996afad2
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Any 

**Describe the problem**
The download and extract script patches CMSIS source files to use qualified paths in order to be compatible with Arduino IDE build system. Currently it takes a significant amount of time, since there are many include files that need to be patched.

Ideally, there would be no need for patching CMSIS at all, but that would require to change the entire CMSIS repo to using qualified paths. Another solution could be to do the patching only when generating Arduino projects. However, that would most likely require us to patch the TFLu optimized op code (kernels/cmsis-nn/*) instead. 

A short term solution is to optimize the patching algorithm.

**Please provide the exact sequence of commands/steps when you ran into the problem**
Any command running using TAGS="cmsis-nn". For example:
`make -f tensorflow/lite/micro/tools/make/Makefile TAGS=cmsis-nn TARGET=sparkfun_edge person_detection_int8_bin`

### PR DESCRIPTION
**Pull request by freddan80**
This is a short term solution to make the CMSIS patching execute faster. Instead of doing a 'find' for each header file, one find is executed per folder DSP/ and NN/ and sed is expanded to replace multiple include paths on those two find's. 

Partly fixes #44013

### CODE REVIEW

**Review by advaitjain — APPROVED** [review]

**Comment by ml-0** [comment]
@freddan80 your changes work for me under MSYS64/Win10. It look like the cmsis_compiler.h is missing in the list of files. Please add
`
  corefiles="cmsis_compiler.h"
  find tensorflow/lite/micro/tools/make/downloads/cmsis \
    \( -name *.c -or -name *.h -or -name *.cpp \) -exec \
    sed -i "s@#include \"\($corefiles\)\"@#include \"cmsis/CMSIS/Core/Include/\1\"@g" {} \;
`

**Comment by freddan80** [comment]
@ml-0 thanks for the heads up! I will add that. What make command reproduces this issue? I know these files are added as a consequence of

**Comment by ml-0** [comment]
I added the CMSIS include paths to tensorflow/lite/micro/tools/make/ext_libs/cmsis.inc
in the context of #41860, assuming they are necessary. Later, I realized that I was using an incompletely patched CMSIS due to #44001. So, after your changes to download_and_extract.sh, the CMSIS include path is not necessary in cmsis.inc (and this is what I understood from @advaitjain and @mansnils). 

If you comment out lines 122...129 in cmsis.inc and then issue the command
`make -j -f tensorflow/lite/micro/tools/make/Makefile TAGS="cmsis-nn" TARGET=cortex_m_gcc_generic CORTEX_M_CORE=M4F microlite`
you will get
`tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include/arm_math_types.h:76:10: fatal error: cmsis_compiler.h: No such file or directory`
because
`#include cmsis_compiler.h`
is not patched.

**Comment by freddan80** [comment]
Got it, me and @mansnils synced up. I'll upload a new patch soon.

**Comment by freddan80** [comment]
@ml-0 let me know that if works for you as well

**Comment by ml-0** [comment]
Tried again: works perfectly on MSYS64/Win10. Thx.

**Review by advaitjain — APPROVED** [review]

**Comment by advaitjain** [comment]
This PR is failing on the Arduino builds with the following error:
```
In file included from /root/Arduino/libraries/tensorflow_lite/src/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include/arm_math.h:199:0,
                 from /root/Arduino/libraries/tensorflow_lite/src/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:33,
                 from /root/Arduino/libraries/tensorflow_lite/src/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnfunctions.h:164,
                 from /root/Arduino/libraries/tensorflow_lite/src/tensorflow/lite/micro/kernels/cmsis-nn/add.cpp:18:
/root/Arduino/libraries/tensorflow_lite/src/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include/arm_math_types.h:76:10: fatal error: cmsis/CMSIS/Core/Include/cmsis_compiler.h: No such file or directory
 #include "cmsis/CMSIS/Core/Include/cmsis_compiler.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

It is reproducible locally with (note that this will affect your local Arduino install):
```
tensorflow/lite/micro/tools/ci_build/test_arduino.sh
```

SInce the Arduino project generation is hairy, I have manually pushed a fix.

**Review by advaitjain — APPROVED** [review]

**Pull request merged**
