### PR TITLE
Update broken bazel test command.

### PR DESCRIPTION
**Pull request by hjm-aws**
Update broken bazel test command. Inspired by https://github.com/tensorflow/tensorflow/issues/23613#issuecomment-440757155. Locally tested.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
These should be equivalent?

**Comment by gbaned** [comment]
@hjm-aws Can you please sign CLA and check @mihaimaruseac's comments? Thank you!

**Comment by bhack** [comment]
> These should be equivalent?

In formulation I think that this currently will not work for https://github.com/bazelbuild/bazel/issues/14848. Right?

**Comment by hjm-aws** [comment]
> @hjm-aws Can you please sign CLA and check @mihaimaruseac's comments? Thank you!
Signed the CLA but somehow the check is still failing.
> These should be equivalent?
In my case it is not.

**Comment by gbaned** [comment]
@hjm-aws It still shows CLA is pending , can you please sign CLA. Thank you!

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Cannot accept this without CLA

**Comment by gbaned** [comment]
Hi @hjm-aws Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @hjm-aws Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @hjm-aws Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @hjm-aws Any update on this PR? Please. Thank you!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Closing since it was stale so long without a CLA

**Pull request closed without merging**
