### PR TITLE
Allows IndexedSlices to be fed and fetched.

### PR DESCRIPTION
**Pull request by kentonl**
Addresses issue #518.

Both `ops.IndexedSlicesValue` and `ops.IndexedSlicesWithoutDenseShapeValue` are needed because `None` can't fed as a subfeed value (see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/session.py#L357)

### CODE REVIEW

**Comment by mrry** [comment]
Hi Kenton,

Thanks for resubmitting this as a pull request, and for adding the tests. I'd like to push a bit harder against `IndexedSlicesWithoutDenseShapeValue`. I've added some comments to `ops.py` that suggest where the problem with returning `None` could be addressed, and I'd prefer to address those internally. (Ideally all `IndexedSlices` would have dense shapes, but for the meantime we could address this with a helpful error message in the case that the fed value doesn't match the object being fed.)

Derek.

**Comment by kentonl** [comment]
Thanks for reviewing this. If I understand your proposed solution correctly, fetching would fail if we use
```
lambda fetched_vals:
  ops.IndexedSlicesValue(fetched_vals[0], fetched_values[1], fetched_values[2] if len(fetched_vals) == 3 else None)
```
since this call: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/session.py#L321 would result in a TypeError due to `subfetch` being None. Or am I misinterpreting something?

**Comment by mrry** [comment]
Not quite: I was suggesting that, in the event `IndexedSlices` doesn't have a `dense_shape`, the fetch function would return a list of two "subfetch" tensors (the indices and values), instead of returning `None` for the `dense_shape`.

**Comment by kentonl** [comment]
The latest version implements your suggestions along with relevant changes to the tests.

**Comment by mrry** [comment]
Thanks for indulging me! :)

This LGTM, so I'll go ahead and merge it.

**Pull request merged**
