### PR TITLE
Branch 160346151

### PR DESCRIPTION
**Pull request by yifeif**

### CODE REVIEW

**Comment by yifeif** [comment]
cc @ebrevdo @craffel

**Review by drpngx — APPROVED** [review]
Thanks!!

**Comment by yifeif** [comment]
PLEASE DO NOT MERGE YET. THANKS.

**Comment by yifeif** [comment]
This is ready to be merged once the builds pass.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Comment by drpngx** [comment]
Strange it reports a Mac error at that commit, but the Mac looks green.

```
ERROR: /private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/external/local_config_python/BUILD:138:1: declared output 'external/local_config_python/numpy_include/numpy/__multiarray_api.h' is a dangling symbolic link.
```

**Comment by drpngx** [comment]
ok, it was a stale result.

**Pull request merged**
