### PR TITLE
[r2.1 cherry-pick] Fix pip package API generation

### PR DESCRIPTION
**Pull request by lgeiger**
This cherry picks #34629 onto the `r2.1` release branch.

This doesn't completely solve https://github.com/tensorflow/community/pull/182 but should get autocomplete working.

/cc @annarev @mihaimaruseac

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Unfortunately having this in in a pip package causes segfaults on `python -c "import scipy; import tensorflow"`. We will rollback for now, to investigate and then rollforward with a fix or provide more instructions.

**Comment by lgeiger** [comment]
> Unfortunately having this in in a pip package causes segfaults on `python -c "import scipy; import tensorflow"`

That is very strange, I don't see why this change could cause a segfault.
I cannot reproduce the segfault with macOS, Python 3.7.5, Tensorflow 2.1.0rc1, SciPy 1.4.0 and NumPy 1.17.4.

**Comment by mihaimaruseac** [comment]
That is indeed strange, we were able to reproduce it on Ubuntu, Python3.5, TF 2.1.0rc1, scipy 1.4.0.

We'll build a pip package with this rolledback and try it to see if the culprit finder was right. If not, we'll roll it forward again

**Comment by lgeiger** [comment]
I can reproduce the failure on [Colab with `scipy==1.4.0`](https://colab.research.google.com/drive/1Dbi1LXzAhYbgWkrm_Km72GSY80CMCotU), but everything works fine on [Colab with `scipy==1.3.3`](https://colab.research.google.com/drive/1ok6NOHdx41xodpGN8DtkNFNwrNMGmkba).

It might be related to https://github.com/scipy/scipy/issues/11237, which now surfaces due to possible changes in import ordering.

**Comment by mihaimaruseac** [comment]
Rolling back the roll back in #35270. Indeed, the culprit was the scipy bug, not this PR. Apologies for the mistaken rollback

**Comment by lgeiger** [comment]
Thanks for investigating.

**Pull request merged**
