### PR TITLE
Added New Google Activation function Swish

### PR DESCRIPTION
**Pull request by amitsrivastava78**
New activation function performance better than ReLU

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@tanzhenyu & @rthadur , can you pls review the PR

**Comment by amitsrivastava78** [comment]
@pavithrasv & @rthadur , can you pls review the PR

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @pavithrasv: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @pavithrasv: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @pavithrasv: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 46 days with no activity and the `awaiting review` label has been applied.

**Comment by pavithrasv** [comment]
I think we should add this to add-ons for now and and merge into core based on how widely it is used. https://github.com/tensorflow/addons/tree/master/tensorflow_addons

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, If you're still interested in pursing this (and responding to above comments), please feel free to reopen!

**Pull request closed without merging**
