### PR TITLE
Replacing generator activation from relu to leaky_relu to avoid sparse gradients

### PR DESCRIPTION
**Pull request by gowtham1997**
- Replaced generator activation from relu to leaky_relu to avoid sparse gradients. Even though the markdown in notebook mentions - _"We use leaky relu activation except for the last layer which uses tanh activation"_, the code uses relu activation. (The generated outputs are also much better when leaky_relu is used. See image below)

- The input noise (input to the generator) is sampled from the normal distribution
`noise = tf.random_normal([BATCH_SIZE, noise_dim])` but the comment above this line mentions -  _"generating noise from a uniform distribution"_. Also changed this to avoid confusion.

### CODE REVIEW

**Comment by gowtham1997** [comment]
I signed it

**Comment by gowtham1997** [comment]
@alextp @asimshankar Can you please take a look?

**Comment by alextp** [comment]
Can you base this off of https://github.com/tensorflow/tensorflow/pull/23035 ? That has a lot of other changes we want to make and should be merged soon.

**Comment by margaretmz** [comment]
Thanks for your pull request @gowtham1997. FYI I already fixed the activation issue of the generator (it should have been LeakyReLU). It might be easier if I just fix the text regarding the input noise input distribution in my PR #23035. As @alextp mentioned there are lots of changes in PR #23035.

**Comment by gowtham1997** [comment]
Sure @alextp 
@margaretmz  Your PR seems to take care of both my changes, so I don't think I can add anything for sending a PR against your branch.

**Pull request closed without merging**
