### PR TITLE
Add ability to specify which gcc to use

### PR DESCRIPTION
**Pull request by gaohuazuo**
Some versions of gcc is incompatible with cuda (e.g. gcc 5.X.X and cuda 7.5). In such situation a compatible gcc version can be specified when running `./configure`.

### CODE REVIEW

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
I think this looks good, someone with more bash-fu want to double check before merging?

**Comment by vrv** [comment]
Assigning to @girving since he is also touching ./configure :)

**Comment by vrv** [comment]
Can you squash your commits?  We'll then test and merge

**Comment by girving** [comment]
Apologies for the delay, @vrv.  I can do the rest.

**Comment by girving** [comment]
The rest not including squashing, that is.

**Comment by girving** [comment]
Still waiting for the squash.

**Comment by vrv** [comment]
Merged

**Pull request closed without merging**
