### PR TITLE
Rearranging statements

### PR DESCRIPTION
**Pull request by printdhruv**
https://github.com/tensorflow/tensorflow/issues/12857

Highlights:-
It generates informative error.

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by printdhruv** [comment]
@yifeif Any suggestions for `tensorflow/contrib/layers/python/layers/optimizers_test.py`? My local machine is passing all test cases for that.

**Comment by yifeif** [comment]
@honkentuber could you help taking a look? Thanks!

**Comment by honkentuber** [comment]
+wicke,ispir

I'm not on ML any more.

**Comment by martinwicke** [comment]
It appears that you changed the behavior, probably by changing the order of ops. @aselle do you see why that might be? It may be a question if simply updating the tests. The second failure looks a little dangerous though.

**Comment by printdhruv** [comment]
@martinwicke Yes.I am changing the flow.

**Comment by aselle** [comment]
Essentially, the order the graph is constructed will change the random number seeding, even if the number of ops and connectivity is the same. That test should be uneatable in the baseline.

**Comment by printdhruv** [comment]
@aselle what should be your guidelines to achieve tf.int32 error message as expected ?
By default, mean is invoked hence I changed the order.
Should I check it in truncated_normal() function itself and raise error for invalid dtype?

**Comment by ispirmustafa** [comment]
Why does this change generates informative error?

**Comment by gunan** [comment]
Should we close this PR?

**Comment by printdhruv** [comment]
@gunan As,it goes against the random number seeding pointed out by aselle , this fix won't work. The simplest thing would be to brute force checking for this function or to change error message which will be affect all connected components.

**Comment by martinwicke** [comment]
Ok, so close it? Fix the tests? @aselle? @yifeif?

**Comment by gunan** [comment]
I am closing this PR, as now it is clear that this is not the way we would like to fix this.
We can explore the other approach in another PR.

**Pull request closed without merging**
