### PR TITLE
Expose param_regularizers in python batch_norm layer

### LINKED ISSUE #7367: TF Slim batch_norm does not expose beta_regularizer or gamma_regularizer
[`batch_normalization`](https://github.com/tensorflow/tensorflow/blob/b00fc538638f87ac45be9105057b9865f0f9418b/tensorflow/python/layers/normalization.py#L255-L256) takes in a `beta_regularizer` and `gamma_regularizer` but the [TF slim `batch_norm` layer does not expose this](https://github.com/tensorflow/tensorflow/blob/bd4a1c58d28734c77ecb17d719e72c45c6c33077/tensorflow/contrib/layers/python/layers/layers.py#L362-L380).

Compare this to other TF slim layers, such as `convolution` which do expose the regularizers: https://github.com/tensorflow/tensorflow/blob/bd4a1c58d28734c77ecb17d719e72c45c6c33077/tensorflow/contrib/layers/python/layers/layers.py#L789-L791

### PR DESCRIPTION
**Pull request by cancan101**
Closes #7367

### CODE REVIEW

**Review by sguada — CHANGES_REQUESTED** [review]
Could you add test for the changes?

**Comment by cancan101** [comment]
@sguada tests added

**Comment by cancan101** [comment]
ping?

**Review by sguada — APPROVED** [review]

**Comment by dandelionmane** [comment]
@tensorflow-jenkins Test this please

**Comment by dandelionmane** [comment]
Thanks cancan!

**Pull request merged**
