### PR TITLE
change bazel-mirror to mirror.bazel

### PR DESCRIPTION
**Pull request by jakiechris**
grep -v bazel-mirror:
do you mean to not use mirror to download ?

mirror links in workspace.bzl is marked as mirror.bazel , not bazel-mirror.
after this change , the download speed enhanced.

i already signed as contributor

### CODE REVIEW

**Review by jart — APPROVED** [review]

**Comment by jart** [comment]
Thanks for this fix! Jenkins: test this please. All yours @yifeif.

**Comment by yifeif** [comment]
@jakiechris could you fix the cla as well? Thank you!

**Comment by jakiechris** [comment]
sorry it's my first trying pull req.
i did some other changes, and git config user.email "liuzhenjluccst@163.com"  on my pc,    
and pushed it to my fork of tensor.
don't know this time cla's judge result

**Comment by jart** [comment]
`liuzhenjluccst@163.com` is not on record as having signed the CLA. Please visit https://cla.developers.google.com/ to sign.

**Comment by jakiechris** [comment]
Contributor License Agreements
Google Individual Contributor License Agreement

Below is the contact information we have for your Google Individual CLA. The information you provide below will be maintained in accordance with Google's privacy policy.

* required fields
Date Signed
Nov 21, 2017 00:37 PST
Email(s)
Learn more about managing email addresses for your account.
wobushiliu2@gmail.com
Name *

ZhenLiu
Address *

ShenZhen city , nanshan district. langshan road TongFang information harbor C 8
Country *

China
Phone Number *

86 13728881140
GitHub Account Name

liuzhenjluccst@163.com

**Comment by jakiechris** [comment]
@jart thnks for this support.
          and should i do git config user.email "wobushiliu2@gmail.com" on my pc, and push some modifications ?

**Comment by jart** [comment]
Run these commands might work:

```sh
git reset HEAD~1
git add .
git commit --amend --no-edit --author 'Your Name <wobushiliu2@gmail.com>'
```

Then `git push` with the `--force` flag.

**Comment by jakiechris** [comment]
➜  tensorflow git:(master) git reset HEAD~1
Unstaged changes after reset:
M	tensorflow/contrib/makefile/Makefile
➜  tensorflow git:(master) ✗ git add *
➜  tensorflow git:(master) ✗ git config user.email "wobushiliu2@gmail.com"
➜  tensorflow git:(master) ✗ git config user.email                        
wobushiliu2@gmail.com
➜  tensorflow git:(master) ✗ git commit --amend --no-edit --author 'jakiechris <wobushiliu2@gmail.com>'
[master c1b6c75] change bazel-mirror to mirror.bazel
 Author: jakiechris <wobushiliu2@gmail.com>
 2 files changed, 3 insertions(+), 2 deletions(-)
➜  tensorflow git:(master) git push --force origin master
Username for 'https://github.com': jakiechris
Password for 'https://jakiechris@github.com': 
Counting objects: 13, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 625 bytes | 0 bytes/s, done.
Total 7 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
To https://github.com/jakiechris/tensorflow
 + b3d4708...c1b6c75 master -> master (forced update)

**Comment by jakiechris** [comment]
@jart  i followed,  could cla rerun ?

**Comment by jart** [comment]
> Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by jakiechris** [comment]
I signed it!

**Comment by jart** [comment]
Thank you for taking the time to cut through the red tape!

I've confirmed `wobushiliu2@gmail.com` is on record with signcla/ and that it is the email used when I `git log` on the CLI.

The problem now is likely that this email isn't associated with your GitHub account, so the bot has no way of knowing you are you.

image

I'd recommend going into your settings and make it look something like this:

image

**Comment by jakiechris** [comment]
thank you for ur quit detailed guiding. now i added the gmail addr to github.




Emails
liuzhenjluccst@163.com Primary  Public Notifications 
wobushiliu2@gmail.com 
Add email address

  Add
Primary email address
liuzhenjluccst@163.com will be used for account-related notifications and for web-based GitHub operations (e.g. edits and merges).

  Save
Backup email address
Your backup GitHub email address can be used to reset your password if you no longer have access to your primary email address.

  Save
 Keep my email address private
We'll remove your public profile email and use 12059735+jakiechris@users.noreply.github.com when performing web-based Git operations and sending email on your behalf. If you want command line Git operations to use your private email you must set your email in Git.

**Comment by jakiechris** [comment]
need i set "wobushiliu2@gmail.com" to be my primary email address ?

**Comment by jakiechris** [comment]
@jart 
thanks to jart again, it seems worked~
is the next step reviewing my pull req by tensor administrators ?

**Comment by jart** [comment]
> thank you for ur quit detailed guiding. now i added the gmail addr to github.

Don't mention it :) I believe in taking care of the folks who put aside the time to send us bug fixes.

> need i set "wobushiliu2@gmail.com" to be my primary email address ?

I'm not sure if it matters. Whatever you did looks great though.

@yifeif This one should be ready to go. Jenkins: test this please.

**Comment by yifeif** [comment]
Thanks for getting the cla working @jakiechris  and @jart!
Is the change in tensorflow/contrib/makefile/Makefile intentional?

**Comment by jart** [comment]
Yes if that Makefile change is worth keeping, it might be better to send that in a separate pull request.

**Comment by jakiechris** [comment]
sorry for not testing all ndk versions, yes there are 2 commits : 
1. Makefile file added a NDK path include for NDK r16 (which may cause failure in ci.tensorflow.org, i will test it soon )
2. download_dependencies.sh file changed the mirror config.

i should split these 2 commits

**Comment by jart** [comment]
Can you send an entirely separate pull request for that ndk_root thing?

**Comment by jakiechris** [comment]
ok, i 'll send a new pull request only for ndk r16 ,  which modified the only file of Mafile 
i am now testing the compilation myself and make sure it's can pass, sorry for pulling without a test

**Comment by jakiechris** [comment]
i found it's not the easy thing to solve ndk r16 issue ,  so i will close this pull , and new a pull req to change only the download part . 

android NDK r16 killed GNU , so tensor of android platform need be prepared for llvm-clang.
it'll be a huge change in Makefile , so i think leave it to tensor developers.

**Pull request closed without merging**
