### PR TITLE
Add complex support for `tf.sparse.segment_sum`

### LINKED ISSUE #53655: tf.sparse.segment_sum doesn't support complex dtypes
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
data = tf.complex(tf.random.uniform([3, 4], dtype=tf.float64),tf.random.uniform([3, 4], dtype=tf.float64))
segment_ids = [0,0,1]
res = tf.math.segment_sum(data=data,segment_ids=segment_ids) # pass
res_sp = tf.sparse.segment_sum(data=data,indices=tf.constant([0, 1, 2]),segment_ids=segment_ids) # InvalidArgumentError
```

**Describe the current behavior**
`tf.sparse.segment_sum` cannot accept a tensor of type `complex128`. However, `tf.math.segment_sum` do support it. 
For the above code snippet, the error message is:
```
InvalidArgumentError: Value for attr 'T' of complex128 is not in the list of allowed values: float, double, int32, uint8, int16, int8, int64, bfloat16, uint16, half, uint32, uint64
	; NodeDef: {{node SparseSegmentSum}}; Op<name=SparseSegmentSum; signature=data:T, indices:Tidx, segment_ids:Tsegmentids -> output:T; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, DT_INT8, DT_INT64, DT_BFLOAT16, DT_UINT16, DT_HALF, DT_UINT32, DT_UINT64]; attr=Tidx:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]; attr=Tsegmentids:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]> [Op:SparseSegmentSum]
```

**Describe the expected behavior**
`tf.sparse.segment_sum` should also support complex dtypes. Actually I would expect the valid types of `data` of `tf.sparse.segment_sum`  to be the same as `tf.math.segment_sum`, since the document of `tf.sparse.segment_sum` does not have this information.

### PR DESCRIPTION
**Pull request by yongtang**
This PR address the issue raised in #53655 where tf.sparse.segment_sum does not have complex support (while tf.math.segment_sum has). This PR adds complex support for tf.sparse.segment_sum.

This PR fixes #53655.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
```
Traceback (most recent call last):
  ...
  File "/build/work/37e6a7f09dff3d343036fefe6e68527c6156/runfiles/tensorflow/python/client/session.py", [line 1400], in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.UnknownError: <unknown>:0: error: loc(fused["SparseSegmentSum:", "SparseSegmentSum_16"]): 'tf.SparseSegmentSum' op operand #0 must be tensor of integer or floating-point values, but got 'tensor<400x1xcomplex<f32>>'
<unknown>:0: note: loc(fused["SparseSegmentSum:", "SparseSegmentSum_16"]): see current operation: %108 = "tf.SparseSegmentSum"(%89#0, %90#0, %32#0) {device = ""} : (tensor<400x1xcomplex<f32>>, tensor<210xi32>, tensor<210xi32>) -> tensor<?x1xcomplex<f32>>
```

```
//tensorflow/python/kernel_tests/math_ops:segment_reduction_ops_test_cpu	FAILED
```

Broken config is called `mlir.tf.roundtrip`. Probably needs some MLIR update to support complex

Compilation flags: `--compilation_mode=opt --define=with_mlir_support=true`

**Comment by gbaned** [comment]
@yongtang  Any update on this PR? Please. Thank you!

**Review by cantonios — APPROVED** [review]

**Comment by cantonios** [comment]
> Can you give the internal test a try? If everything pass then the `tf_generated_ops.td` is automatically generated and this PR does not needs additional changes anymore.

We can update that on our end.  Can you rebase?

**Comment by gbaned** [comment]
Hi @yongtang Can you please check @cantonios's [comments](https://github.com/tensorflow/tensorflow/pull/54357#issuecomment-1462644578) and keep us posted ? Thank you!

**Pull request closed without merging**
