### PR TITLE
Removed Extra lines and Rearranged the triple ( """   """ ) comment

### PR DESCRIPTION
**Pull request by Rohitw3code**

### CODE REVIEW

**Comment by gbaned** [comment]
@Rohitw3code  Can you please sign CLA. Thanks!

**Comment by Rohitw3code** [comment]
@gbaned  can you help me i want to contribute in tf , don't know where to start

**Comment by Rohitw3code** [comment]
I have signed in CLA

**Comment by qlzh727** [comment]
This PR doesn't provide any value for the code base, so I would like to just leave the existing code as is. 

On a side note, you would like to contribute to TF and provide some actually value, please check the contribution welcome list and pick any task from there. 

https://github.com/tensorflow/tensorflow/issues?q=is%3Aissue+is%3Aopen+contribution+welcome+label%3A%22stat%3Acontributions+welcome%22

**Comment by Rohitw3code** [comment]
@qlzh727 thanks for your suggestion

**Pull request closed without merging**
