### PR TITLE
Add an is_external arg to tf_copts

### PR DESCRIPTION
**Pull request by snnn**
It's for support build custom ops on Windows
@meteorcloudy This is what we talked last week.

### CODE REVIEW

**Comment by snnn** [comment]
Please re-run the tests

**Comment by meteorcloudy** [comment]
@tensorflow-jenkins Test this please

**Comment by snnn** [comment]
CI machine's disk is full.

**Review by meteorcloudy — APPROVED** [review]
Thanks for doing the refactors!

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by yifeif** [comment]
python3 rerun at http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/7629/

**Pull request merged**
