### PR TITLE
Construct scalar constants directly instead of calling zeros([]) or ones([])

### PR DESCRIPTION
**Pull request by lgeiger**
This PR changes the code to construct scalar constants directly instead of calling `zeros([])` or `ones([])`.
For scalars in eager mode calling `tf.constant` directly is about 9x faster than calls to `zeros([])` or `ones([])`. In practice this will only matter in edge cases, but since it doesn't reduce readability I think it is good to do in any case.

### CODE REVIEW

**Review by tomerk — APPROVED** [review]

**Comment by lgeiger** [comment]
Looks like these changes didn't work for bool and string types, I updated the PR to fix the CI failures.

**Review by tomerk — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by gbaned** [comment]
@lgeiger Please submit this PR to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. Thankyou.
@qlzh727

**Comment by lgeiger** [comment]
> Please submit this PR to the github.com/keras-team/keras repository instead. Thankyou.

This code also touches code outside of `tensorflow/python/keras` which is not part of keras-team/keras (the PR even predates the move to keras-team/keras). I won't resubmit, feel free to close if it's not possible to merge.

**Comment by tomerk** [comment]
Acknowledged, sorry about that! As per above, closing because this is unmergable as of the recent Keras repo split.

**Pull request closed without merging**
