### PR TITLE
Portable optimized versions of key tflite_u op kernels

### PR DESCRIPTION
**Pull request by andrewstevens-infineon**
Adds portable optimized versions of key layer ops to improve usefulness of tflite(u) on
platforms where dedicated kernel libraries are not available / applicable.

https://github.com/tensorflow/tensorflow/issues/47644

The kernels are  standard C++11 (no intrinsics, inline asm etc) but take advantage
of prepare-phase precomputations, and coding tweaks reduce runtime and memory overhead.

Some useful additional kernel unit tests are included.

Kernels contributed by Infineon Technologies.  Kudos to our Intern Jakob Kruse who did the real coding with just a code-review and tips on my part.

### CODE REVIEW

**Comment by advaitjain** [comment]
Thanks for the PR.

Some high-level discussion topics:

 * We have currently made an explicit decision that any optimizations (above the reference kernels) should go in target specific kernel directories (instead of having what we previously called `portable_optimized` and what this PR is calling `generic_optimized`):
 https://github.com/tensorflow/tensorflow/blob/aa3bd9f6de5a76c4c226548a48e448d211978e92/tensorflow/lite/micro/docs/optimized_kernel_implementations.md#L72-L89

 * If this is still something that you would like to contribute for your specific target, then we would encourage making a target-specific folder and following the steps outlined in our [Optimized Kernel Implementation guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/docs/optimized_kernel_implementations.md).
    * Note that we recommend having the majority of the optimized implementation available as a downloadable NN library and checking in only the kernel wrappers into the TFLM codebase.
    * And the changes would need to be reviewed as one kernel per PR and (as much as possible) have documented improvements on benchmarks of interest.

Happy to chat more at the next SIG-micro meeting if you would like to discuss this topic in more detail.

Tagging @tensorflow/micro

**Comment by andrewstevens-infineon** [comment]
Hmmm.. so  if we'd called it (say) "stock_rv32i"  (primary in-house use) and sort-of pretended it would not be useful on (say) an ARC core  ("if the need arises" in-house use-case) it would be more welcome.

Of course renaming the directory would be no problem at all.  Its just a bit odd to pretend the content non-portable when that is not actually the case.    

I suspected we are not alone in finding a "base" of not-painfully-inefficient implementations valuable when bringing up support for in-house/not-yet-public platforms with limited/application-specific acceleration capabilities.

Let's discuss!

**Comment by gbaned** [comment]
@andrewstevens-infineon Can you please resolve conflicts? Thanks!

**Comment by advaitjain** [comment]
Closing the current PR. Based on the discussion at the SIG-micro meeting this work may be merged in the form of a optimized kernels for risc-v which then call into the portable library that is hosted separate from the TFLM codebase.

**Pull request closed without merging**
