### PR TITLE
Line104 should be "ZerosLike" in gradients.cc

### PR DESCRIPTION
**Pull request by Dynmi**
This is from issue #41912 .

Line 104 should be 
```
 absl::StrCat("ZerosLike", ToId(handle_)).c_str()); 
```

### CODE REVIEW

**Review by alextp — APPROVED** [review]

**Comment by rthadur** [comment]
@Dynmi can you please update your branch , we see some conflicts.

**Comment by Dynmi** [comment]
> @Dynmi can you please update your branch , we see some conflicts.

No problem. But how should I update it? Could you guide me?

**Comment by rthadur** [comment]
you can try this 

````
git clone ${your_fork_url}
$ cd tensorflow
$ git remote add upstream ${main_tensorflow_repo_url}
$ # do work, git add, git commit, everything on a branch for your repo
$ git push # -u optionally
$ # now syncing from upstream
$ git checkout master
$ git pull --rebase upstream
$ git push  # now master on your fork is synced with master upstream
$ git checkout -  # switch back to the branch
$ git rebase master  # rebase on master without any merge commits
$ git push  # now the changes on your repo and rebased on master upstream
````

**Comment by Dynmi** [comment]
> you can try this
> 
> ```
> git clone ${your_fork_url}
> $ cd tensorflow
> $ git remote add upstream ${main_tensorflow_repo_url}
> $ # do work, git add, git commit, everything on a branch for your repo
> $ git push # -u optionally
> $ # now syncing from upstream
> $ git checkout master
> $ git pull --rebase upstream
> $ git push  # now master on your fork is synced with master upstream
> $ git checkout -  # switch back to the branch
> $ git rebase master  # rebase on master without any merge commits
> $ git push  # now the changes on your repo and rebased on master upstream
> ```

Ok, I will do it later!

**Comment by ymodak** [comment]
@Dynmi Just want to check if are you still interested in fixing this?

**Comment by Dynmi** [comment]
> @Dynmi Just want to check if are you still interested in fixing this?

Well. It seems this problem has been fixed in another PR, which was just a litte earlier than my PR.

**Pull request closed without merging**
