### PR TITLE
Use canonical cuda include directory path in CROSSTOOL.

### LINKED ISSUE #3985: Refactored GPU installation from source issue (Ubuntu 16.04)
It looks like the GPU installation from source got refactored and is failing to compile on my Ubuntu 16.04, CUDA 8.0, cuDNN 5.0, with GTX 1080 GPU.

I had the GTX 1080 working with the build from a few days ago, but just pulled from the head and now cannot compile so I am not sure if this is the auto_configure for the GPU or not I saw going though.

$ git rev-parse HEAD
6d04d601e9e8758ec4642fa9d548b7321d804d63

$ bazel version
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392

$ ./configure

GPU configured

INFO: All external dependencies fetch successfully.
Configuration finished

$ bazel build -c opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package  1>~/initial_output.txt 2>&1 
[initial_output.txt](https://github.com/tensorflow/tensorflow/files/432724/initial_output.txt)

GPU CUDA includes were not found so I added line to new file: CROSSTOOL.tpl @ line 66

  cxx_builtin_include_directory: "/usr/local/cuda-8.0/include"

$ bazel build -c opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package  1>~/second_output.txt 2>&1 
[second_output.txt](https://github.com/tensorflow/tensorflow/files/432726/second_output.txt)

I think it is complaining about not finding "crosstool_wrapper_driver_is_not_gcc".

I did a "locate" and my version seems to be at the following:
$ locate crosstool_wrapper_driver_is_not_gcc
/home/greg/serving/tensorflow/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc
/home/greg/serving/tf_models/syntaxnet/tensorflow/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc
/home/greg/tensorflow/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl

Let me know where the file is that has the path to the crosstool_wrapper.... and I can update the path to test that as a fix unless you know the root cause...

EDIT: BTW, the build works fine without the GPU configuration

### PR DESCRIPTION
**Pull request by davidzchen**
Fixes #3985

### CODE REVIEW

**Comment by martinwicke** [comment]
Is it known yet which bazel release will contain that change?

**Comment by davidzchen** [comment]
The next Bazel release should contain bazelbuild/bazel#1685.

+@damienmg to confirm.

**Comment by damienmg** [comment]
Definitely it will

**Comment by rohan100jain** [comment]
Any updates on this? has the bazel release gone out?

**Comment by damienmg** [comment]
Yes the release was done last Friday.

**Comment by rohan100jain** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
Our CI needs to upgrade bazel, and then we need to bump the version of the check_version required bazel before we can accept this.  It would be nice if the check_version went in with this PR.

**Comment by gunan** [comment]
A lot of the bazel upgrades can be incorporated into this change.
David, could you update all our Dockerfiles that install bazel?
We will then also need to upgrade out MAC executors manually before we merge this.
Also this file:
tensorflow/tools/ci_build/install/install_bazel.sh

**Comment by davidzchen** [comment]
Thanks for the pointers. Will do.

**Comment by gunan** [comment]
DO NOT MERGE
the update change to bazel 0.3.2 has been reverted due to failures in CI.

**Comment by davidzchen** [comment]
The change to upgrade to Bazel 0.3.2 has been rolled-forward. I have rebased this PR on master, and all of the tests are now passing.

PTAL.

**Review by vrv — APPROVED** [review]

**Pull request merged**
