### PR TITLE
Update beginners.md

### PR DESCRIPTION
**Pull request by DanCard**
Add wikipedia link for one-hot encoding, which does a better job of explanation then the following text.

### CODE REVIEW

**Comment by DanCard** [comment]
I signed it!  I'm a googler, ldap: danielcar

**Comment by DanCard** [comment]
I signed it! I'm a googler, ldap: danielcar

**Comment by vrv** [comment]
You need to set your git commit email to your google.com email @DanCard .  See git commit --amend for instructions on how to do so.

**Comment by vrv** [comment]
(Talked offline, going to send another PR since this was done via web interface).

**Pull request closed without merging**
