### PR TITLE
Added tests for tensors, inputs, outputs, opcodes

### PR DESCRIPTION
**Pull request by amitsrivastava78**
This was one of the TODO, just complete the same

### CODE REVIEW

**Review by shashishekhar — DISMISSED** [review]
Thanks , @amitsrivastava78

**Comment by amitsrivastava78** [comment]
@rthadur , can you pls help to get this merged, as this is approved for long and i am afraid that if it stays longer again some merge conflicts might come.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@rthadur, can you please help to get this merged, this is approved for long.

Regards 
Amit

**Comment by rthadur** [comment]
> @rthadur, can you please help to get this merged, this is approved for long.
> 
> Regards
> Amit

Sure

**Comment by amitsrivastava78** [comment]
> > @rthadur, can you please help to get this merged, this is approved for long.
> > Regards
> > Amit
> 
> Sure

@rthadur , thanks for the reply, can you pls help to get this merged.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@shashishekhar , thanks for approving the PR can you please help me to merge this PR, this is approved for long time.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@rthadur , this is a long pending approved PR, can you please help to get this merged.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@rthadur , this is a long pending approved PR, with all necessary checks passed,
 can you please help to get this merged.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@rthadur , can you please help to merge this PR.

Regards
Amit

**Comment by rthadur** [comment]
> @rthadur , can you please help to merge this PR.
> 
> Regards
> Amit

initially failed internal tests , will try to merge this again

**Comment by rthadur** [comment]
@amitsrivastava78 here is the internal error 

`ERROR: /tmpfs/tensor_flow/tensorflow/lite/toco/tflite/BUILD:104:1: Couldn't build file tensorflow/lite/toco/tflite/_objs/export_test/export_test.o: C++ compilation of rule '//tensorflow/lite/toco/tflite:export_test' failed (Exit 1): clang failed: error executing command 
  (cd /tmpfs/tmp/bazel/execroot/org_tensorflow && \
  exec env - \
    BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \
    PATH=/bin:/usr/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python2 \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
    TF_PYTHON_CONFIG_REPO=@org_tensorflow//third_party/toolchains/cpus/py \`
can you please check.

**Comment by amitsrivastava78** [comment]
@rthadur , thanks for the update the PR is quite old and the member of struct ExportParams got little change, i have resolved the issue now.

@shashishekhar , I know it is old PR, but can you please re-approve the same.

Regards
Amit

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@shashishekhar Can you please take a look on this PR? Thanks!

**Comment by jdduke** [comment]
@karimnosseir can you review?

**Review by karimnosseir — APPROVED** [review]

**Comment by rthadur** [comment]
@amitsrivastava78 can you please below errors 

`tensorflow/lite/toco/tflite/export_test.cc:879:3: error: ignoring return value of function declared with 'warn_unused_result' attribute
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/tensorflow/lite/toco/tflite/export_test.cc:901:3: error: ignoring return value of function declared with 'warn_unused_result' attribute 
  Export(input_model_, &result, params);
  ^~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow/lite/toco/tflite/export_test.cc:922:3: error: ignoring return value of function declared with 'warn_unused_result' attribute 
  Export(input_model_, &result, params);
  ^~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/tensorflow/lite/toco/tflite/export_test.cc:946:3: error: ignoring return value of function declared with 'warn_unused_result' attribute 
  Export(input_model_, &result, params);
  ^~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.`

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
