### PR TITLE
[XLA] Add a unary ops cosine test to the standard tests

### PR DESCRIPTION
**Pull request by DavidNorman**
Add an XLA cosine python test.

### CODE REVIEW

**Comment by yifeif** [comment]
Thanks @DavidNorman. @tensorflow-jenkins test this please.

**Comment by DavidNorman** [comment]
hmm.  it's possible that the GPU doesn't support cosine for f64.

i'll doctor up the test to avoid that for GPU.

**Comment by DavidNorman** [comment]
the 'linux CPU tests (python 3)' must be someone else's error.

**Comment by DavidNorman** [comment]
Ok:  this error

```
LLVM ERROR: Cannot select: 0x7f9838182938: f64 = fcos 0x7f98381828d0
  0x7f98381828d0: f64,ch = load<LD8[%2(addrspace=1)](tbaa=<0x7f9838183580>)(noalias=<0x7f983814be50>)(invariant)> 0x7f983824c518, 0x7f9838182868, undef:i64
    0x7f9838182868: i64 = add 0x7f9838182528, 0x7f9838182c10
      0x7f9838182528: i64 = addrspacecast[0 -> 1] 0x7f9838182a08
        0x7f9838182a08: i64,ch = load<LD8[null(addrspace=101)](dereferenceable)(invariant)> 0x7f983824c518, TargetExternalSymbol:i64'_cosine_param_0', undef:i64
          0x7f9838182180: i64 = TargetExternalSymbol'_cosine_param_0'
          0x7f9838182250: i64 = undef
      0x7f9838182c10: i64 = NVPTXISD::MUL_WIDE_UNSIGNED 0x7f98381826c8, Constant:i32<8>
        0x7f98381826c8: i32 = AssertZext 0x7f98381825f8, ValueType:ch:i2
          0x7f98381825f8: i32 = llvm.nvvm.read.ptx.sreg.tid.x TargetConstant:i64<3350>
            0x7f9838182590: i64 = TargetConstant<3350>
        0x7f9838182ba8: i32 = Constant<8>
    0x7f9838182250: i64 = undef
In function: _cosine
================================================================================
```

this indicates that LLVM cannot find a cosine function for f64 that targets the GPU.  Out LLVM person suggests that a possible solution is to add the following to the NVPTXInstrInfo.tf file:

```
def SINF64:  NVPTXInst<(outs Float64Regs:$dst), (ins Float64Regs:$src),
                      "sin.approx.f64 \t$dst, $src;",
                      [(set Float64Regs:$dst, (fsin Float64Regs:$src))]>,
                      Requires<[allowUnsafeFPMath]>;
def COSF64:  NVPTXInst<(outs Float64Regs:$dst), (ins Float64Regs:$src),
                      "cos.approx.f64 \t$dst, $src;",
                      [(set Float64Regs:$dst, (fcos Float64Regs:$src))]>,
                      Requires<[allowUnsafeFPMath]>;
```

but that is a quick guess about the right thing.  we have not tested it or anything.   

I'm not going to try to fix this.  I will leave the pull request open for a while, in case you want to use it as a test for making the NVIDIA support in LLVM work.

**Comment by drpngx** [comment]
@tatatodd FYI, this is more like a bug report. I'm going to close this, assuming that we're acting on this.

@DavidNorman Thanks!

**Comment by DavidNorman** [comment]
No problem.  Do you want me to file a bug report?

**Comment by DavidNorman** [comment]
@drpngx see last comment :)

**Comment by tatatodd** [comment]
@DavidNorman thanks for trying to add the test, and the subsequent sleuthing!

@sanjoy @hpucha @andydavis1 @skye all might be interested in this.

**Pull request closed without merging**
