### PR TITLE
Revert "Add batch support for various image_ops (#14854)"

### PR DESCRIPTION
**Pull request by jhseu**
This reverts commit 20aa9e0a9f129ed929cea1fb45ec12b7be3ac68e.

@martinwicke fyi

### CODE REVIEW

**Comment by jhseu** [comment]
@JoshVarty fyi

**Comment by martinwicke** [comment]
@JoshVarty The issue is that the code changes make the 3D versions of these slower, and sadly, even the 4D versions are slower. @jhseu added benchmarks, let's try again with something with improved performance.

**Review by saeta — APPROVED** [review]

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Pull request merged**
