### PR TITLE
[Windows/CMake] Enable SVD op and test.

### PR DESCRIPTION
**Pull request by mrry**

### CODE REVIEW

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by isaacgerg** [comment]
I am using windows 7 with keras and python 3.4. I would like to help with the tensorflow port.  I have models that currently train and test in theano, would be happy to help get tensorflow working and can validate it against theano for correctness.

How can I get started?

**Comment by rmlarsen** [comment]
Woohoo! Looks like only failure was a flaky test on mac. Merging.

**Comment by rmlarsen** [comment]
@mrry, @isaacgerg  do you have any specific instructions for Isaac about contributing on Windows, other thanthe generic instructions here: https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md

**Comment by guschmue** [comment]
@isaacgerg instructions how to get a windows build are here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md
Keras should work ok, I ran the Keras example directory with a tensorflow backend under windows+gpu some time ago and it was happy.

**Comment by mrry** [comment]
@isaacgerg +1 to what @guschmue said. Currently we're working to get the Windows build at parity with what the Linux version supports. Our number-one priority is to get all of the kernels building, and you can see a list of the ones we're currently unable to build [here](https://github.com/tensorflow/tensorflow/blob/35f7c5c3fd4fe96b588ba578bbdbc95f47e9ac36/tensorflow/contrib/cmake/tf_core_kernels.cmake#L88). You can also see a list of tests that don't currently pass [here](https://github.com/tensorflow/tensorflow/blob/35f7c5c3fd4fe96b588ba578bbdbc95f47e9ac36/tensorflow/contrib/cmake/tf_tests.cmake#L129). Any contributions to make these work would be most valuable!

Please feel free to open an issue if you run into any problems.

**Pull request merged**
