### PR TITLE
Branch 195749522

### PR DESCRIPTION
**Pull request by yifeif**

### CODE REVIEW

**Comment by rmlarsen** [comment]
@yifeif: It looks like the Java bindings are broken:

tensorflow/java/src/gen/cc/op_specs.cc:386:20: error: no member named 'deprecation_version' in 'tensorflow::ApiDef_Endpoint'
      endpoint_def.deprecation_version() > 0);
      ~~~~~~~~~~~~ ^
1 error generated.

Perhaps roll back the CL which caused this?

**Comment by yifeif** [comment]
Looks like it's related to https://github.com/tensorflow/tensorflow/pull/19137/commits/92acc302beefd2b596b505d9278f8b0b46239cea. cc: @annarev.

**Comment by annarev** [comment]
Looks like there was a conflict with my change and a change to op_specs.cc.
The reference to deprecation_version can be removed in that file.

**Comment by yifeif** [comment]
Thanks @annarev! I updated the EndpointSpec class based on your suggestion. PTAL.

**Review by annarev — DISMISSED** [review]

**Comment by yifeif** [comment]
Looks like the only xla failure now is due to cl/195748721, which as been rolled back internally. I'm going to try push another one.

**Comment by yifeif** [comment]
merged #19164 instead. Closing this one.

**Pull request closed without merging**
