### PR TITLE
Add the eager coverage for some experimental dataset kernels

### PR DESCRIPTION
**Pull request by feihugis**
This PR add the eager coverage for `MakeTFRecordDatasetTest` and `MapAndBatchTest`.

### CODE REVIEW

**Comment by jsimsa** [comment]
@shivaniag could you please take a look ... I believe this PR might be duplicate of some of your recent changes

**Comment by feihugis** [comment]
@shivaniag (cc'ed @jsimsa ) I just saw your comments [here](https://github.com/tensorflow/tensorflow/pull/24207#issuecomment-447129506). Feel free to close it if it is duplicated with your merging PR. 

There is another related PR here: https://github.com/tensorflow/tensorflow/pull/24330.

**Comment by jsimsa** [comment]
@feihugis thank you for the contribution ... to avoid duplicating efforts in the future, could you please keep me in the loop on what tf.data TODOs are you working on? if you are interested, we might also be able to suggest some things for you to work on

**Comment by feihugis** [comment]
Thank you very much, @jsimsa! It will be perfect if you could suggest some things for me to work on. In the future, I will also create an issue to check if there is any duplicated work before I start to work on a PR.

**Comment by jsimsa** [comment]
Here is a suggestion for a larger project. Let me know if you are interested:

The goal would be to develop C++ infrastructure for testing tf.data kernel implementations in C++. Currently, the C++ tf.data kernels are only tested through Python bindings which are not fine-grained enough and some public C++ APIs are not always tested.

The flow of testing the C++ API would be:
- create an instance of the dataset op
- invoke the `Compute` method which takes input arguments and produces `DatasetBase` object wrapped in a variant
- test the public API of the `DatasetBase` object, including the `MakeIterator` method which produces `IteratorBase` object
- test the public API of the `IteratorBase` object

**Comment by feihugis** [comment]
@jsimsa Yeah, I am very interested in this project! Do you have any suggestion about how to start the work? May I can submit a PR once I finish an initial version? Then we can discuss more details based on the PR. Or, you already have something that I can continue to work on?

**Comment by jsimsa** [comment]
There is currently no code for this. I suggest you create a fork of the tensorflow repo and start building a prototype for which can create a PRs targeting your fork. That way we can iterate on your code through code reviews more often.

**Comment by feihugis** [comment]
@jsimsa Sounds good! Will do it and keep you updated.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jsimsa, @shivaniag: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by shivaniag** [comment]
Stale PR, closing this.

**Pull request closed without merging**
