### PR TITLE
Replace 0.12.0 deprecated functions in python, contrib, and models directories

### PR DESCRIPTION
**Pull request by samjabrahams**
Used [this script](https://github.com/samjabrahams/tensorcrack/blob/master/scripts/migrate_0.12/migrate.sh) to get initial changes, and then cleaned up using the diff.

### CODE REVIEW

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by samjabrahams** [comment]
Whoops- misspelled `global_variables_initializer` as `global_variable_initializer`. Will fix when I get back to my rig.

**Comment by samjabrahams** [comment]
Ok, I fixed the `global_variables_initializer` typo. Additionally, I took out the changes to `python/kernel_tests/scalar_strict_test.py`, as the tests in it don't work with the new op. Finally, I noticed there were a few typos elsewhere with `global_variables_initializers` (extra 's' at the end), so I fixed those as well.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by samjabrahams** [comment]
Let me know if I should rebase. I don't _think_ the GPU failures were from these changes, but there may be lingering bugs from elsewhere.

**Comment by gunan** [comment]
I don't think they are, but I will run them again once to make sure they are flakes.
Jenkins, test this please.

**Review by gunan — APPROVED** [review]

**Pull request merged**
