### PR TITLE
added const

### PR DESCRIPTION
**Pull request by luizhenriquesoares**
The const statement creates a variable whose value is fixed, that is, a read-only constant

### CODE REVIEW

**Review by dsmilkov — APPROVED** [review]

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@luizhenriquesoares , can you please sign the CLA before we merge this PR? Thanks.

**Comment by luizhenriquesoares** [comment]
@caisq, I already signed the CLA, thanks

**Comment by caisq** [comment]
PR merged. Thanks, @luizhenriquesoares !

**Pull request merged**
