### PR TITLE
TFLu: Add support for unknown output dimensions

### PR DESCRIPTION
**Pull request by mansnils**
Some models (e.g. Convnet) with broadcasting have unspecified output
dimensions for some operators, where the dimensions can be deduced from
the input dimensions.

### CODE REVIEW

**Comment by gbaned** [comment]
@mansnils Can you please resolve conflicts? Thanks!

**Comment by mansnils** [comment]
@gbaned Conflicts are resolved.

**Review by njeffrie — DISMISSED** [review]
Looks good overall.  I'm guessing the reason you are only doing this for add and mul is the specifc model you are using?

**Comment by mansnils** [comment]
@njeffrie Yes, that is correct.

**Comment by rthadur** [comment]
@mansnils can you please check below errors 

`/tensorflow/lite/micro/kernels/add.cc:26:10: fatal error: '/tensorflow/lite/micro/memory_helpers.h' file not found
#include "/tensorflow/lite/micro/memory_helpers.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
/tensorflow/lite/micro/kernels/mul.cc:24:10: fatal error: '/tensorflow/lite/micro/memory_helpers.h' file not found
#include "/tensorflow/lite/micro/memory_helpers.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.`

**Comment by mansnils** [comment]
@rthadur Sorry, I forgot to update the bazel files. I added unit tests as well.

**Comment by rthadur** [comment]
Seems auto-merge is not happening but the changes are now committed so we can close this. Thank you for the PR.

**Pull request closed without merging**
