### PR TITLE
fixed function call of incompatible API

### PR DESCRIPTION
**Pull request by ziyin-dl**
The old function call will throw an error.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 32 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 46 days with no activity and the `awaiting review` label has been applied.

**Comment by gbaned** [comment]
@isaprykin  Hi, Could you PTAL and approve.

**Comment by isaprykin** [comment]
@ziyin-dl what error does it throw?

**Comment by ziyin-dl** [comment]
@isaprykin It would throw an `AttributeError` complaining the function does not exist. Apparently it has been moved from `tf.compat.v1.estimator` to `tf.estimator`.

**Comment by isaprykin** [comment]
> @isaprykin It would throw an `AttributeError` complaining the function does not exist. Apparently it has been moved from `tf.compat.v1.estimator` to `tf.estimator`.

What version are you using?  I don't think I see that, because I can find that symbol.  It shouldn't be a problem with the nightly, say.
>> import tensorflow as tf
>> tf.compat.v1.estimator.inputs.numpy_input_fn
<function [redacted...].tensorflow_estimator.python.estimator.inputs.numpy_io.numpy_input_fn>

**Comment by bananabowl** [comment]
It seems like the rename to compat.v1 did not make it into 1.13 while the reference to it in examples/tutorials/layers/cnn_mnist.py did: 
https://www.tensorflow.org/api_docs/python/tf/estimator/inputs/numpy_input_fn
https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/examples/tutorials/layers/cnn_mnist.py#L137

Sorry for the confusion - this example should work out of the box in 1.14.

**Pull request closed without merging**
