### PR TITLE
Make fuzztest fuzzer ready for OSS-Fuzz

### PR DESCRIPTION
**Pull request by DavidKorczynski**
The goal here is to make the fuzztest fuzzers run in the OSS-Fuzz infrastructure. I'm starting with a single fuzzer to confirm it all works.

I also updated the googletest dependency, will this have any negative impact?

Cross-referencing https://github.com/google/oss-fuzz/pull/8992 in the OSS-Fuzz repo.

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Seems right to me. Might need to also change internal copybara rules, etc. but can take care of it.

**Comment by DavidKorczynski** [comment]
@mihaimaruseac I fixed the lint issues

**Review by mihaimaruseac — APPROVED** [review]
The problem is that someone internal has to shepherd this change as it needs internal changes to Copybara.

CC @fcoUnda

**Comment by DavidKorczynski** [comment]
> The problem is that someone internal has to shepherd this change as it needs internal changes to Copybara.
> 
> CC @fcoUnda

Ah okay, thanks for letting me know. I'll await directions then

**Comment by DavidKorczynski** [comment]
It looks like FuzzTest has some compilation issues:
```
external/com_google_fuzztest/./fuzztest/internal/runtime.h:197:15:   required from here
external/com_google_fuzztest/./fuzztest/internal/runtime.h:179:7: error: ‘kNumArgs’ is not a member of ‘int’
  179 |       Switch<ArgWithDomain::kNumArgs>(index, [&](auto I) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_fuzztest/./fuzztest/internal/runtime.h:180:46: error: request for member ‘domain’ in ‘arg’, which is of non-class type ‘const int’
  180 |         PrintValue(ExtractInnerDomain<I>(arg.domain),
      |                                          ~~~~^~~~~~
external/com_google_fuzztest/./fuzztest/internal/runtime.h:181:36: error: request for member ‘corpus_value’ in ‘arg’, which is of non-class type ‘const int’
  181 |                    std::get<I>(arg.corpus_value), out, mode);
      |                                ~~~~^~~~~~~~~~~~
  ```
 @lszekeres are you familiar with this?

**Comment by gbaned** [comment]
@DavidKorczynski Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
@DavidKorczynski Can you please resolve conflicts? Thank you!

**Comment by DavidKorczynski** [comment]
Hi -- sorry for the delay here @gbaned !! This has been resolved elsewhere now so I will close this PR as it's no longer needed.

**Pull request closed without merging**
