### PR TITLE
Remove deprecated operations in the datasets

### PR DESCRIPTION
**Pull request by luisleee**
In reuters.py and imdb.py, there are ndarray creations with ragged
array, but it's deprecated now. So I added parameter "dtype" to them.

### CODE REVIEW

**Comment by deeb02** [comment]
@luisleee , could you please clarify what was deprecated exactly?

**Comment by luisleee** [comment]
@deeb02 ok, please see here: https://numpy.org/doc/stable/release/1.19.0-notes.html#deprecate-automatic-dtype-object-for-ragged-input.

**Comment by deeb02** [comment]
@luisleee thank you! That makes sense.

**Review by deeb02 — APPROVED** [review]
Looks good to me.
Handles deprecation of implicit type inference for ragged arrays in numpy:
https://numpy.org/neps/nep-0034-infer-dtype-is-object.html

Thank you for the fix.

**Comment by gbaned** [comment]
@luisleee  Can you please address Ubuntu Sanity errors? Thanks!

**Comment by luisleee** [comment]
@gbaned Finished.

**Review by deeb02 — APPROVED** [review]
Looks good to me.
Thank you for the fix.

**Pull request merged**
