### PR TITLE
Fix Invalid description FileWriter

### PR DESCRIPTION
**Pull request by ryujaehun**
After Tensorflow 2.0,eager is used by default.

So, FileWriter class generates a runtime error because of eager context.
tf.compat.v1.Session() 

Even though you use tf.compat.v1.Session (), the session works as an eager, so you can see the following error code.

`RuntimeError: tf.summary.FileWriter is not compatible with eager execution. Use tf.contrib.summary instead.`

But as we all know, `tf.contrib` no longer exists in tensorflow 2.0 world.

So I added the following guide:  Use `tf.compat.v1.disable_eager_execution()` before the code.

And I touched the document a bit to suit him.

Thanks for your working.

### CODE REVIEW

**Comment by ryujaehun** [comment]
> @googlebot I signed it!

**Comment by MarkDaoust** [comment]
Thanks @ryujaehun,

I'll try merging this.

**Review by MarkDaoust — DISMISSED** [review]

**Review by MarkDaoust — DISMISSED** [review]

**Comment by gbaned** [comment]
@ryujaehun Can you please address Ubuntu Sanity errors? Thanks!

**Comment by ryujaehun** [comment]
> @ryujaehun Can you please address Ubuntu Sanity errors? Thanks!

I fixed it, thanks!

**Comment by gbaned** [comment]
@ryujaehun Still, Ubuntu Sanity checks failing. Could you please check again?  Thanks!

**Comment by gbaned** [comment]
@ryujaehun Still, Ubuntu Sanity checks failing. Could you please check again? Thanks!

**Comment by gbaned** [comment]
@ryujaehun Still, Ubuntu Sanity checks failing. Could you please check again? Thanks!

**Review by MarkDaoust — APPROVED** [review]
I think this fixes it.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
Here are the internal errors, @ryujaehun can you please verify ?

`RuntimeError: v1.summary.FileWriter is not compatible with eager execution. Use `tf.summary.create_file_writer`,or a `with v1.Graph().as_default():` context

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<embedded stdlib>/unittest/case.py", line 59, in testPartExecutor
    yield
  File "<embedded stdlib>/unittest/case.py", line 605, in run
    testMethod()
  File "google3/third_party/tensorflow/contrib/eager/python/tfe_test.py", line 137, in testClassicSummaryFileWriterErrorsOut
    writer.FileWriter(tempfile.mkdtemp())
  File "<embedded stdlib>/unittest/case.py", line 217, in __exit__
    expected_regex.pattern, str(exc_value)))
  File "<embedded stdlib>/unittest/case.py", line 135, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: "tf\.summary\.FileWriter is not compatible with eager execution" does not match "v1.summary.FileWriter is not compatible with eager execution. Use `tf.summary.create_file_writer`,or a `with v1.Graph().as_default():` context" `

**Comment by MarkDaoust** [comment]
Yeah, it got stuck on an internal test. I've fixed it (cl/299164574).

**Comment by MarkDaoust** [comment]
This is only waiting for an internal approval, it will be merged soon.

**Pull request merged**
