### PR TITLE
add log_softmax c++ gradient

### PR DESCRIPTION
**Pull request by DeNeutoy**

### CODE REVIEW

**Comment by DeNeutoy** [comment]
I signed it!

**Comment by yifeif** [comment]
@andydavis1 mind taking a look? Thanks!

**Review by andydavis1 — APPROVED** [review]

**Comment by andydavis1** [comment]
Thanks for the contribution!

**Comment by andydavis1** [comment]
@tensorflow-jenkins test this please

**Comment by DeNeutoy** [comment]
@andydavis1 Sorry, this is failing - I am not exactly sure why, as the gradient computation looks correct (comparing to the python [version](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn_grad.py#L217)). I am fairly new to c++ so it's very possible there is something I haven't considered in how these ops are applied. If you have any ideas, happy to poke around!

**Comment by andydavis1** [comment]
It looks like tensorflow/cc:gradients_nn_grad_test is failing. Can you run that locally and see what the error is?

**Comment by DeNeutoy** [comment]
```
[       OK ] NNGradTest.SoftmaxGrad (98 ms) 
[ RUN      ] NNGradTest.LogSoftmaxGrad 
tensorflow/cc/gradients/nn_grad_test.cc:39: Failure 
Expected: (max_error) < (1e-4), actual: 0.000244878 vs 0.0001 
[  FAILED  ] NNGradTest.LogSoftmaxGrad (90 ms) 
[ RUN      ] NNGradTest.ReluGrad 
[       OK ] NNGradTest.ReluGrad (8 ms) 
[ RUN      ] NNGradTest.Relu6Grad 
[       OK ] NNGradTest.Relu6Grad (7 ms) 
[ RUN      ] NNGradTest.EluGrad 
[       OK ] NNGradTest.EluGrad (8 ms) 
[----------] 5 tests from NNGradTest (211 ms total)
```
Hmm, looks like just a finite differences error.

**Comment by andydavis1** [comment]
Maybe try reducing the size of the dimension that gets reduced for your unit test case.  Also, some gradients can be sensitive to initial value when the gradient check is used, so you play with 'x_init_value' (see ReluGrad for an example).

**Comment by DeNeutoy** [comment]
@andydavis1 Thanks, that fixed it, tests passing locally.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Pull request merged**
