### PR TITLE
Fix incorrect documentation in _SliceHelper #10494

### LINKED ISSUE #10494: incorrect documentation in _SliceHelper
The outputs shown for several of the examples in the `_SliceHelper` docstring are incorrect (based on some previous examples?).

See, for example, this line: https://github.com/tensorflow/tensorflow/blob/359d6f9716c0bb9bd8201ce600da98b0481a8049/tensorflow/python/ops/array_ops.py#L412

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #10494.

### CODE REVIEW

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by Androbin** [comment]
@martinwicke Why do documentation updates even need a full CI test?

**Comment by martinwicke** [comment]
They don't, a partial one would do, but we haven't set it up with two separate builds. We can do that, it's just that more interesting things keep happening. But the documentation is built as well, and doc changes can break for a variety of reasons, some of them subtle. 

That said, I do at times merge without testing. Don't tell anyone.

**Review by aselle — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
