### PR TITLE
Disable batch_ops_test on pip

### PR DESCRIPTION
**Pull request by alextp**

### CODE REVIEW

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@alextp weird buildifier error. <tab> instead of space?

**Comment by alextp** [comment]
Jenkins, test this please.

**Comment by rmlarsen** [comment]
@yifeif @wicke I don't have permission to merge this. Can you?

**Comment by yifeif** [comment]
Let's bring this back to master after release. cc @av8ramit

**Pull request merged**
