### PR TITLE
Fixed typo in TFlite export exception.

### PR DESCRIPTION
**Pull request by fanconic**
Changed the exception statement in tensorflow/lite/toco/tflite/export.cc:
"Placeholder ", input_array, " should be specied by input_arrays."
to:
"Placeholder ", input_array, " should be specified by input_arrays."

### CODE REVIEW

**Comment by fanconic** [comment]
@googlebot I signed it!

**Comment by fanconic** [comment]
@googlebot I fixed it.

**Comment by fanconic** [comment]
@googlebot I fixed it.

**Comment by fanconic** [comment]
@googlebot I fixed it.

**Comment by fanconic** [comment]
@googlebot I signed it!

**Comment by fanconic** [comment]
@googlebot I fixed it.

**Comment by rthadur** [comment]
We will not be encouraging one liner grammatical changes as this is expensive process, thank you for your interest.If possible include more such changes and include in this PR.
CC @mihaimaruseac @chanshah

**Comment by fanconic** [comment]
I completely understand, excuse me being a douchebag. It was my first ever pull  request, and I shall  from now on try commit relevant content.
Thank you for your commitment so far :)

**Pull request closed without merging**
