### PR TITLE
Update to use python 2-3 compatible function tf_inspect.getfullargspec.

### PR DESCRIPTION
**Pull request by IMBurbank**
RE: Issue #22413 

The `tf_inspect` module is configured to shim python 2 for use with the `tf_inspect.getfullargspec` wrapper, making the function python 2-3 compatible.

The older `tf_inspect.getargspec` is used locally for _getfullargspec with python 2, and called for unit tests in tf_inspect_test.py, but it's also exposed for potential misuse without much documentation. 

Several modules fall into the trap of calling the exposed `tf_inspect.getargspec` directly. Python 3 calls to any of these modules will call the deprecated python 2 function.

This PR changes the following:

- Adds a warning to the `tf_inspect.getargspec` docstring recommending use of `tf_inspect.getfullargspec` instead.

- Updates `tf_inspect.getargspec` calls in other modules to use `tf_inspect.getfullargspec`

- Adds unit tests for `tf_inspect.getfullargspec` and `tf_inspect.FullArgSpec`

### CODE REVIEW

**Comment by IMBurbank** [comment]
I signed it!

**Review by alextp — DISMISSED** [review]
Thank you for the changes!

**Comment by alextp** [comment]
Hey; there seems to be a small issue with tf_inspect_test. Can you take a look?

**Comment by IMBurbank** [comment]
@alextp I'm looking at the tests now. The changes passed local build tests, but I think I know what's going on after reading through the build check logs.

I'll get this updated today.

**Comment by IMBurbank** [comment]
@alextp I believe I addressed the issues from the logs.

**Review by alextp — DISMISSED** [review]

**Comment by IMBurbank** [comment]
@alextp the backwards compatibility checks are flagging that the name of the ** parameter changed from `keywords` to `varkw` with the change from `inspect.getargspec` to `inspect.getfullargspec`. According to [the docs:](https://docs.python.org/3/library/inspect.html)

From `inspect.getargspec`
> Deprecated since version 3.0: Use `getfullargspec()` for an updated API that is usually a drop-in replacement, but also correctly handles function annotations and keyword-only parameters.

From `inspect.getfullargspec`
> Changed in version 3.6: This method was previously documented as deprecated in favour of signature() in Python 3.5, but that decision has been reversed in order to restore a clearly supported standard interface for single-source Python 2/3 code migrating away from the legacy getargspec() API.

> Changed in version 3.7: Python only explicitly guaranteed that it preserved the declaration order of keyword-only parameters as of version 3.7, although in practice this order had always been preserved in Python 3.

Depending on the importance of this ** parameter's naming, two initial options come to mind:

1. Route (some or all of) the functions back to explicitly calling the deprecated `inspect.getargspec` through `tf_inspect.getargspec` 

This will make the  API compatibility check issue go away, but will also cause python 3 calls to use the deprecated `getargspec` and bypass the (otherwise) cross-compatible `tf_inspect.getfullargspec` wrapper.
 
2. Address any upstream issues that would come from the function signature change.

It seems prudent to make the cross-compatible wrapper work over counting on a deprecated function, but I can't picture what issues the update could create.

I will say that I'm happy to help however I can with this and future issues. Please advise.

**Comment by alextp** [comment]
Maybe tf_inspect.getargspec can call getfullargspec and repackage the return values into the old struct?

**Comment by IMBurbank** [comment]
`tf_inspect` could certainly name the ** parameter based on the call - the module already has two checks to differentiate between python 2/3 and create the current `tf_inspect.getfullargspec` wrapper. 

We could modify the python 3 struct for this call in `tf_inspect` to match the `getargspec` call from python 2 but, analogous to the current situation, it would likely by flagged by python 3 API compatibility checks for the `FullArgSpec` parameter name change from `varkw` to `keywords`.

We could also modify just the python 2 `FullArgSpec` struct to use the `keywords` parameter name; however, the parameter would come back as `keywords` when using python 2 and `varkw` when using python 3. This would keep python 2 environments consistent, but any code used by python 2 and 3 would have to avoid testing for only one instance of this parameter name.

------

Something that just came to mind (maybe this was the intent of your last post) - since both the python 2 and 3 versions of this function are exposed in the `tf_inspect` module, and since there's already a shim to make `tf_inspect.getfullargspec` python 2 compatible - we could add a similar shim such that when `tf_inspect.getargspec` is called from python 3, it made a call to its current `inspect.getfullargspec` and had the `varkw` parameter name changed to `keywords`

`tf_inspect` would contain two shims: one that made python 2 compatible with `getfullargspec` calls, and a new one that made python 3 compatible with non-deprecated `getargspec` calls. When `tf_inspect.getfullargspec` was called, both would have a ** parameter name of `varkw`; when `tf_inspect.getargspec` was called it would be `keywords`. Under the hood python 2 would always be calling `inspect.getargspec` and python 3 would be calling `inspect.getfullargspec`. 

To pass the python 2 API compatibility check, I would also have to change the function calls in other modules back to `tf_inspect.getargspec`, but python 3 would no longer call the deprecated `inspect.getargspec`. 

In this scenario, I would recommend maintaining the docstring recommendation to use `tf_inspect.getfullargspec` moving forward, but neither this function nor `getargspec` should break anything under the hood.

**Comment by IMBurbank** [comment]
Shorter answer: I think so. 

I'll update the PR.

**Comment by alextp** [comment]
Yes this is what I was suggesting

**Comment by IMBurbank** [comment]
That should do it.

**Review by alextp — APPROVED** [review]

**Comment by IMBurbank** [comment]
I don't see any errors in the logs associated with these PR changes.

**Comment by IMBurbank** [comment]
I looked that the Ubuntu CC test logs of a couple other PRs recently marked `Ready to Pull` and they have the same build errors. I think there's a separate internal issue with the testing pipeline.

**Comment by IMBurbank** [comment]
The main thing that stood out in the GPU Python3 invocation log was

```
ERROR: /tmpfs/src/github/tensorflow/tensorflow/python/BUILD:5651:1: Couldn't build file tensorflow/python/_objs/framework/fast_tensor_util.so/tensorflow/python/framework/fast_tensor_util.pic.o: undeclared inclusion(s) in rule '//tensorflow/python:framework/fast_tensor_util.so':
this rule is missing dependency declarations for the following files included by 'tensorflow/python/framework/fast_tensor_util.cpp':
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/arrayobject.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarrayobject.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarraytypes.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_common.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/numpyconfig.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/_numpyconfig.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_endian.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_cpu.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/utils.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/_neighborhood_iterator_imp.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/old_defines.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/__multiarray_api.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_interrupt.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ufuncobject.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_math.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_common.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/arrayobject.h'
  '/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/__ufunc_api.h'
In file included from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from bazel-out/host/genfiles/tensorflow/python/framework/fast_tensor_util.cpp:581:
...
```

**Pull request merged**
