### PR TITLE
fix tf.Saver save and restore bug under distributed setting(with ps, master and worker)

### PR DESCRIPTION
**Pull request by chengmengli06**
This pull request allow using more than one PS in distributed training, saving and restore models without using any shared file stream. The following issues will be fixed, although it is closed:
   https://github.com/tensorflow/tensor2tensor/issues/394
   https://github.com/tensorflow/tensorflow/issues/6374

@tobyyouup @mrry  @ericyue

### CODE REVIEW

**Comment by chengmengli06** [comment]
I signed it.

**Comment by chengmengli06** [comment]
I signed it.

**Comment by mrry** [comment]
Transferring my review request to @allenlavoie, since this is related to saving checkpoints.

**Comment by allenlavoie** [comment]
One high-level question is how this relates to `Saver(sharded=False)`.

Another question is what this does to users of shared filesystems who are using the current sharded behavior. Doesn't this create a bunch of extra communication and a bottleneck?

**Comment by chengmengli06** [comment]
@allenlavoie
This modification does not affect tf.Saver(sharded=False), the sharded controls whether the model are saved in one file or multiple files. I test with both sharded = True and sharded = False, both settings work with the current modification. As for extra communication, shared file system also involves lots of communication. Moreover, pull parameters from sever is necessary for every iteration. 
I experiment with two PS, the saving time does not increase significantly.
Two PS after modification(13s vs 12s): 
[INFO] 2018-11-18 16:32:52,305 tf_logging.py:115 : Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into pascal_resnet50_rfcn_model_dis_more/model.ckpt.
[INFO] 2018-11-18 16:33:05,211 tf_logging.py:115 : Saving checkpoints for 0 into pascal_resnet50_rfcn_model_dis_more/model.ckpt.
One PS before modification:
[INFO] 2018-10-23 11:57:29,569 tf_logging.py:115 : Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into pascal_resnet50_rfcn_model_dis/model.ckpt.
[INFO] 2018-10-23 11:57:41,622 tf_logging.py:115 : Saving checkpoints for 0 into pascal_resnet50_rfcn_model_dis/model.ckpt.

**Comment by chengmengli06** [comment]
@allenlavoie I look into the details of tf.train.Saver, the non sharded case are not affected, because no tf.device is set on the call path, so it is default to job:master. I log out the device placement, and it shows that both restore and save operation are placed on job:master. 

tensorflow/core/common_runtime/placer.cc:935] save/SaveV2: (SaveV2)/job:master/replica:0/task:0/device:CPU:0
tensorflow/core/common_runtime/placer.cc:935] save/RestoreV2: (RestoreV2)/job:master/replica:0/task:0/device:CPU:0

**Comment by allenlavoie** [comment]
I meant more that this seems like it's re-implementing non-sharded save in the `sharded=True` path. Why doesn't `sharded=False` fix issues caused by not having a shared filesystem?

**Comment by allenlavoie** [comment]
My impression is that `sharded=True` is mainly useful if you can't fit all of your variables in memory on a single machine.

So you shard the variables among a bunch of parameter servers. But now if you go to save without sharding, you copy all of the variables to a single machine and run out of memory. Theoretically this could be serialized so each shard gets saved before the next gets copied to the machine doing the saving, but that seems very complicated and pretty slow.

So instead the assumption is that a distributed filesystem handles the shards, and each parameter server can just dump whatever they have to it. This assumption is annoying if there is no distributed filesystem, but I don't think copying all the shards to a single machine helps. Maybe the discussion should be around whether `sharded=True` is a good default, or whether it needs to be clearer in the documentation that a shared filesystem is an assumption for distributed `Estimator`?

FWIW `tf.train.Saver` will probably not be in TensorFlow 2.x. We haven't yet settled on an API to expose this kind of sharding behavior.

**Pull request closed without merging**
