### PR TITLE
tf.tile gradient supports IndexedSlice

### LINKED ISSUE #16930: Gradient function of tile operator failed with sparse Tensor
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4/1.5
- **Python version**: 3.5.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
I found an issue when I use a _tile_ operator followed by a _gather_ operator. It seems that there is a `isinstance(grad, ops.Tensor)` assert in the gradient function of _tile_ operator, while _gather_ operator will result in a sparse gradient with the type of IndexedSlices.

Please see below example for details.

### Source code / logs
Here is a small example to re-produce this issue:
```python
x = tf.Variable([[0.0], [1.0], [2.0], [3.0], [4.0]], name='x')
x = tf.tile(x, [1, 2])
i = tf.Variable(list(range(0, 5)), name='i')
x = tf.gather(x, i)
s = tf.reduce_sum(x)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(s)
```

You will get below errors:
```
ValueError: No attr named '_XlaCompile' in name: "Tile"
op: "Tile"
input: "x/read"
input: "Tile/multiples"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "Tmultiples"
  value {
    type: DT_INT32
  }
}

During handling of the above exception, another exception occurred:
Traceback
 (most recent call last):
  File "D:/test/test_gather.py", line 12, in <module>
    train_op = optimizer.minimize(s)
  File "D:\PyEnv\tf1.5\lib\site-packages\tensorflow\python\training\optimizer.py", line 355, in minimize
    grad_loss=grad_loss)
  File "D:\PyEnv\tf1.5\lib\site-packages\tensorflow\python\training\optimizer.py", line 456, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "D:\PyEnv\tf1.5\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 609, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "D:\PyEnv\tf1.5\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 375, in _MaybeCompile
    return grad_fn()  # Exit early
  File "D:\PyEnv\tf1.5\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 609, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "D:\PyEnv\tf1.5\lib\site-packages\tensorflow\python\ops\array_grad.py", line 552, in _TileGrad
    assert isinstance(grad, ops.Tensor)
AssertionError
```

I think this is caused by the assertion in gradient function of _tile_ operator:
```python
@ops.RegisterGradient("Tile")
def _TileGrad(op, grad):
  """Sum reduces grad along the tiled dimensions."""
  assert isinstance(grad, ops.Tensor)
  input_shape = array_ops.shape(op.inputs[0])
```

Could we remove this assert or change the type to ops._TensorLike?

### PR DESCRIPTION
**Pull request by facaiy**
Fix #16930

### CODE REVIEW

**Comment by facaiy** [comment]
@mrry @cy89 Hi, could you take a look, or assign the PR to the corresponding reviewer? Thanks very much.

**Comment by facaiy** [comment]
@martinwicke Excuse me, do you know who could help review the PR? Thanks.

**Comment by facaiy** [comment]
@suharshs Could you take a look?

**Comment by talkhaldi** [comment]
I apply this fix manually every time I upgrade my tensorflow, it'd be helpful if it gets merged!

**Comment by facaiy** [comment]
@mrry Could you help assign it to a reviewer? Thanks.

**Comment by facaiy** [comment]
@drpngx Hi, could you give a hand? Thanks very much.

**Comment by mrry** [comment]
I'm not familiar with this code, and so decline the review.

**Comment by case540** [comment]
Are you familiar enough to review this annarev@?

**Comment by annarev** [comment]
Adding Zhifeng since I never actually worked on the _TileGrad function. He would know more about it.

**Review by zffchen — DISMISSED** [review]
https://github.com/tensorflow/tensorflow/blob/294fdb0c5452715ec46d0555245e3b130308ebb4/tensorflow/python/kernel_tests/shape_ops_test.py#L411

Please move the test case to the test file above.

**Comment by facaiy** [comment]
@zffchen78 Hi, the test case has been moved. Could you take a look again?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by facaiy** [comment]
@annarev Hi, I think the PR is small, however it has been pending for a long time. Could you take a hand? Thanks :-)

**Comment by martinwicke** [comment]
Hey @skye can you lend a hand? I saw gradient and thought of you.

**Review by annarev — DISMISSED** [review]
Sorry for delay, I was thinking Zhifeng will review it since he knows more about this code.
However, I read through it now, seems good.
Can you add a test with rank 1 input? Otherwise approving.

**Comment by facaiy** [comment]
many thanks, @martinwicke .

@annarev sure, I have added a new test with rank 1 input.

**Review by annarev — APPROVED** [review]

**Pull request merged**
