### PR TITLE
[Intel MKL] Fixing a bug in Elu Op

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR fixes a bug in Elu op when fused with Convolution. It also updates the unit test by using different random generator to generate input with both negative and positive values. Previously the random input was only positive. So the bug was never caught.

### CODE REVIEW

**Review by penpornk — COMMENTED** [review]
Thank you for the PR! I'll approve this after https://github.com/tensorflow/tensorflow/pull/33451 is merged. (There will be a merged conflict.)

**Review by penpornk — CHANGES_REQUESTED** [review]
https://github.com/tensorflow/tensorflow/pull/33451 has been merged. Could you please help resolve the conflicts? Thank you!

**Comment by mahmoud-abuzaina** [comment]
Thank you @penpornk. I have fixed the merge conflicts.

**Review by penpornk — APPROVED** [review]
Thank you, @mahmoud-abuzaina!

**Pull request merged**
