### PR TITLE
[XLA] Add F16 as type for the literal conversion functions

### PR DESCRIPTION
**Pull request by DavidNorman**
The F16 (synonym for eigen half) type was not included in the literal conversion functions.  float/double is supported as a type conversion by the eigen half, so adding identical lines as the native types.

### CODE REVIEW

**Review by hawkinsp — APPROVED** [review]

**Comment by hawkinsp** [comment]
Jenkins, test this please.

**Comment by DavidNorman** [comment]
mm.  that's odd.  i think our buildbot runs that test.  I'll double check.

**Comment by DavidNorman** [comment]
i see.  we run tensorflow/compiler/xla/tests..., and not tensorflow/compiler/xla:...

will fix asap.

**Comment by DavidNorman** [comment]
fixed.

**Review by hawkinsp — APPROVED** [review]

**Comment by hawkinsp** [comment]
Jenkins, test this please.

**Pull request merged**
