### PR TITLE
Enable GPU for MatMul float64

### PR DESCRIPTION
**Pull request by siddharth-agrawal**
Enabled GPU registration for MatMul operations of type double. This partially addresses #1140.

I realize that this is a very small change, I wanted to become familiar with the pull request process before making moderately big changes.

### CODE REVIEW

**Comment by vrv** [comment]
Did you test this out locally, by any chance?

**Comment by siddharth-agrawal** [comment]
Yes, tested it using the following:

`bazel test -c opt --test_verbose_timeout_warnings --config=cuda //tensorflow/python:matmul_op_test`

**Comment by vrv** [comment]
Cool, thanks!  This used to not work because we compiled an Eigen version of contraction which didn't support double, but cublas supports it, so we're all good.

@tensorflow-jenkins test this please

**Comment by siddharth-agrawal** [comment]
I'm going to work on making float64 work on the GPU for other ops as well. Would you prefer pull requests for each op separately, or multiple ops at once?

I'm sorry if this is the not the right forum for me to be asking this. In case it isn't, is there some place someone new like me could ask questions?

**Comment by vrv** [comment]
Keeping it manageable is always good!  Doing classes of ops at a time is fine -- you can probably do a bunch of related ops at once so they're easy to test and verify together.    This is a fine forum to ask about this, since it's about development / new code features.

**Comment by siddharth-agrawal** [comment]
This is weird. The test passes on my machine, don't know what's wrong. I tested it again.

**Comment by vrv** [comment]
Going to try one more time, the test that failed wasn't the 'double' one...

test this please, @tensorflow-jenkins

**Comment by vrv** [comment]
Sorry, I was on vacation, can you rebase?

**Comment by siddharth-agrawal** [comment]
@vrv I think I messed up the rebase, it is giving me all the commits that weren't there in my branch. How do I fix it?

**Comment by vrv** [comment]
I'm not sure, I generally do (on the dev branch);

    git fetch upstream
    git rebase upstream/master
    git push -u origin $branch


You might want to start again in a new PR if it's too messy to undo for you

**Comment by siddharth-agrawal** [comment]
Right, I'm closing this. Will send out a new PR.

**Pull request closed without merging**
