### PR TITLE
Adding Instruction to install tf using Conda

### PR DESCRIPTION
**Pull request by shubham15gupta09**
It's a well know fact that the Installation of tf-gpu might become a difficult process . 

To solve this issue we can use the method of installation through conda .

Conda provide a single line solution to install all the files required like cuda , cdunn etc.

I hope adding this step as a Installation process will help many user to 
 quickly start with tensorflow-gpu.

### CODE REVIEW

**Comment by shubham15gupta09** [comment]
@googlebot I signed it!

**Comment by shubham15gupta09** [comment]
Hi 
I am waiting for a reply 
Please review it . 
If you want to reject you can do that also 

Thanks

**Comment by MarkDaoust** [comment]
We don't own/test/support TensorFlow with conda, so it's hard for us to include this in the official docs.

Right @lamberta?

**Comment by shubham15gupta09** [comment]
Hey Mark 

I know you don't support the conda .

But still conda is one of the way  to use tensorflow .

There are lot of problem which the user face in installing the tensorflow-gpu .As you also have to install Cuda , Cudnn  etc .

Its better to use a single line command using conda . This will automatically install the most appropriate version of cuda , Cudnn etc .

It would be great if you include this installing process also in your official docs.

Thanks

**Comment by lamberta** [comment]
We mention/link to Conda [here in the pip install guide](https://www.tensorflow.org/install/pip?hl=en&lang=python3#2.-create-a-virtual-environment-recommended), but Conda is not officially supported (and often lags behind). I think the TensorFlow Docker images would be a better recommendation.

I'm open to a brief comment and link to the Conda section in the TF install guide, but including commands here seems out-of-scope.

cc: @gunan

**Comment by shubham15gupta09** [comment]
Okay should I move on to the  "  TensorFlow Docker images " installation . If you are okay including that .

**Comment by gunan** [comment]
I agree, if we document conda here, then we open ourselves to questions about why conda packages are available much later than pip packages, bugs in conda due to conda using different build options.
TF builds with manylinux 2010 standard, and builds a whole ecosystem around using the same toolchains. Conda releases use a different toolchain, that can cause incompatibilities with pip packages, or custom ops, or other packages under tensorflow umbrella, like addons.

So, I am definitely against having full instructions in TF website.
If Anaconda has a page with TF instructions, we can point to there.
So, we definitely cannot accept this change.

**Comment by lamberta** [comment]
> Okay should I move on to the " TensorFlow Docker images " installation .

@shubham15gupta09 Yes, we should link to this section: https://www.tensorflow.org/install/docker#gpu_support

**Comment by shubham15gupta09** [comment]
Hi @lamberta  @MarkDaoust @MarkDaoust 
We can include these links to the tf installation instructions as Anaconda has instructions to install tensorflow .
I think it would be better to give these as a link .

https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/
https://www.anaconda.com/blog/tensorflow-in-anaconda
https://anaconda.org/conda-forge/tensorflow

**Pull request closed without merging**
