### PR TITLE
Add doc of conv3d_transpose

### PR DESCRIPTION
**Pull request by yenchenlin**
This PR add the API doc of `conv3d_transpose`.

### CODE REVIEW

**Comment by yenchenlin** [comment]
I signed it!

**Comment by vrv** [comment]
The way to add documentation is to call it out here: https://github.com/tensorflow/tensorflow/blob/f974e8d0c2420c6f7e2a2791febb4781a266823f/tensorflow/python/ops/nn.py#L111

Just add @conv3d_transpose there and our doc generator will update afterwards

**Comment by yenchenlin** [comment]
@vrv thanks, PR updated.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
