### PR TITLE
cherry-pick vulnerability fixes from r1.13 into r1.12

### PR DESCRIPTION
**Pull request by ashahba**

### CODE REVIEW

**Comment by ashahba** [comment]
@mrry is there any plans to patch `r1.12`? These address vulnerability issues and it'll be a good idea to resolve them 🙂

**Comment by mihaimaruseac** [comment]
We recommend using the soon to be released 1.13.2 patch version.

If upgrading is not possible, please let me know and I'll add on my roadmap making a new release for 1.12 and then merge these.

**Comment by ashahba** [comment]
Thanks @mihaimaruseac 
We certainly plan to release `1.13.2` once that patch release is out, but we also need the same patch for `1.12` release i.e `1.12.3`.
Is there no plans to do so.

**Comment by mihaimaruseac** [comment]
There weren't until now, but I think we'll have to do them

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
