### PR TITLE
[TFLite] Fix potential overflow in 64-bit MultiplyByQuantizedMultiplier function

### PR DESCRIPTION
**Pull request by Tessil**
Hi,

This PR fixes potential overflows than can happen in the 64-bit version of `MultiplyByQuantizedMultiplier`.

Overflow example:
```c++
int32_t quantized_multiplier;
int shift;
double scale = 0.00097656;
QuantizeMultiplier(scale, &quantized_multiplier, &shift);

const int64_t x = 10000;
std::cout << x*scale << std::endl;
std::cout << MultiplyByQuantizedMultiplier(x, quantized_multiplier, shift) << std::endl;
```
Output:
```
9.7656
-10 // Should be 10
```

Thanks,
Thibaut

### CODE REVIEW

**Comment by Tessil** [comment]
Hi @suharshs, could you take a look to the PR? Thanks.

**Comment by advaitjain** [comment]
Apologies for the delay. If @suharshs can take a look, that would be great.

I would usually ask for a test that currently fails but passes with the change but I don't see any existing tests for MultiplyByQuantizedMultipler so I'll defer to @suharshs on this as well.

**Comment by gbaned** [comment]
@jianlijianli, @daverim  Can you please take a look on this PR ? Thanks!

**Review by talumbau — CHANGES_REQUESTED** [review]
Thanks for this change! Looks good. I looked around for the right spot for a test. It looks like it the test should go in tensorflow/lite/kernels/internal/quantization_util_test.cc (it already includes this common.h). We should have more tests for this function, so it would be good to start with at least one. Thanks!

**Comment by Tessil** [comment]
Thank you, I hesitated as there was no existing tests for any of the `MultiplyByQuantizedMultiplier` versions. I will check to add some tests as they are quite central functions.

**Comment by Tessil** [comment]
@talumbau I added some tests for the int32 and int64 versions of the `MultiplyByQuantizedMultiplier` function.

I had to modify a bit the BUILD file to link `libm` as I had some `undefined reference to symbol 'round@@GLIBC_2.2.5` error when compiling the `quantization_util_test`.

**Comment by gbaned** [comment]
@talumbau  Can you please take a look on the above comment from @Tessil. Thanks!

**Review by talumbau — APPROVED** [review]
LGTM. Thanks!

**Comment by Tessil** [comment]
@talumbau I realized I used `int32` and `int64` instead of `int32_t` and `int64_t` in two places which created a compilation error in the MacOS CPU test. The PR will need re-approval, sorry.

**Review by talumbau — APPROVED** [review]

**Comment by talumbau** [comment]
Hi,

I am seeing test failures in `quantization_util_test`. Can you confirm you get errors like this:

```
bazel build --compilation_mode=opt //third_party/tensorflow/lite/kernels/internal:quantization_util_test
```

```
third_party/tensorflow/lite/kernels/internal/quantization_util_test.cc:434:32: error: implicit conversion from 'double' to 'int32_t' (aka 'int') changes value from 0.1 to 0 [-Werror,-Wliteral-conversion]
  EXPECT_EQ(quant_and_multiply(0.1, 0), 0);
            ~~~~~~~~~~~~~~~~~~ ^~~
```


Thanks!

**Comment by Tessil** [comment]
Effectively a `double` was used instead of an `int` but surprisingly I didn't have any warning or error using `bazel test` and it slipped by. I fixed the test.

**Review by talumbau — APPROVED** [review]

**Comment by talumbau** [comment]
thanks very much. Just approved again.

**Review by rthadur — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by talumbau** [comment]
Hi Thibaut,

I looked at the Windows Bazel GPU CI build failure, as well as the Intel oneDNN build failure. They look spurious to me and not related to this change. Can you attempt to rebase and invoke the submit process again? I believe that change in 0cead48 should be good.

**Comment by Tessil** [comment]
I merged the latest changes, thanks.

**Review by talumbau — APPROVED** [review]

**Comment by talumbau** [comment]
Looks like there are some builds with additional warnings

```
third_party/tensorflow/lite/kernels/internal/quantization_util_test.cc:453:49: error: operator '<<' has lower precedence than '-'; '-' will be evaluated first [-Werror,-Wshift-op-parentheses]
                  static_cast<double>(1ll << 31 - (-3)));
                                          ~~ ~~~^~~~~~
third_party/tensorflow/lite/kernels/internal/quantization_util_test.cc:453:49: note: place parentheses around the '-' expression to silence this warning
                  static_cast<double>(1ll << 31 - (-3)));
                                                ^
```

Can you fix please?

**Comment by Tessil** [comment]
Thank you, I fixed the warning. 

Is there a reason to not enable these warnings and `-Werror` in the GitHub CI build? I have to see if we can modify a bit our internal CI to more closely match the warnings you use.

**Review by talumbau — APPROVED** [review]

**Comment by talumbau** [comment]
That's a good idea. I have filed this issue internally. Thanks for your patience.

**Comment by talumbau** [comment]
Looks like the Github CI needs significant improvement. I see a failure with this command:

```
bazel --blazerc=/dev/null test --compilation_mode=opt --copt=-UNDEBUG tensorflow/lite/kernels/internal:quantization_util_test
```

it fails on the assert here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/common.h#L179

Can you reproduce?

**Comment by Tessil** [comment]
Thank you, the 64-bit `MultiplyByQuantizedMultiplier` effectively doesn't support negative multipliers. From what I gather it's an intentional behaviour and some HW implementations rely on the fact that the multiplier is >= 0. The TOSA spec also has an `assert(multiplier >= 0);`  in `apply_scale_32`.

I removed the tests with negative multipliers for the 64-bit version but left them for the 32-bit version as some kernels use negative multipliers (notably the SUB operator to reuse the ADD kernel).

**Review by talumbau — APPROVED** [review]

**Pull request merged**
