### PR TITLE
[Intel MKL] Update Eigen to get new optimization contributed by Intel

### PR DESCRIPTION
**Pull request by Zantares**
Update Eigen to get these feature:
1. broadcasting optimization for channel first shape
2. fix a crush when build Tensorflow with Eigen

modified:
- tensorflow/workspace.bzl

Signed-off-by: Lu Teng teng.lu@intel.com

### CODE REVIEW

**Comment by Zantares** [comment]
Update Eigen to get broadcasting optimization for 'channel first' shape, detail is here: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1567

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yifeif: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by harshini-gadige** [comment]
@yifeif  PTAL

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by Zantares** [comment]
Eigen has been updated to the newest version, close this PR.

**Pull request closed without merging**
