### PR TITLE
Add Tan, Asin, Acos, Atan trigonometric functions

### PR DESCRIPTION
**Pull request by Mistobaan**
See  Issue #1108 .

### CODE REVIEW

**Comment by martinwicke** [comment]
Cool! Jenkins, test this please.

**Comment by Mistobaan** [comment]
This PR and others like #1099  are failing on:

```
//tensorflow/user_ops:ackermann_test: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
```

**Comment by vrv** [comment]
I don't think that's correct.  The failure here is legitimate:

//tensorflow/python:cwise_ops_test                                       FAILED in 2 out of 2 in 243.8s
  Stats over 2 runs: max = 243.8s, min = 133.8s, avg = 188.8s, dev = 55.0s
  /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-fastbuild/testlogs/tensorflow/python/cwise_ops_test/test_shard_2_of_2.log
  /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-fastbuild/testlogs/tensorflow/python/cwise_ops_test/test_shard_1_of_2.log

Executed 275 out of 317 tests: 316 tests pass and 1 fails locally.

**Comment by Mistobaan** [comment]
Oh I see, I missed the extra line. How do you see the contents of the log file ? 

`/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-fastbuild/testlogs/tensorflow/python/cwise_ops_test/test_shard_2_of_2.log`

**Comment by vrv** [comment]
I click on the 'details' link and go to "Console output" in Jenkins :)

**Comment by Mistobaan** [comment]
That shows just the line `/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-fastbuild/testlogs/tensorflow/python/cwise_ops_test/test_shard_1_of_2.log`. I meant what is inside that file with the actual info of the error / failed test ?

**Comment by vrv** [comment]
If you go to the full log, the test failure output is embedded somewhere in the log file

**Comment by Mistobaan** [comment]
Rebased patch and fixed failing tests.

**Comment by Mistobaan** [comment]
@martinwicke rebased and fixed the tests cases.

**Comment by vrv** [comment]
@tensorflow-jenkins : test this please

**Comment by vrv** [comment]
@Mistobaan I think we are missing the GPU files like https://github.com/tensorflow/tensorflow/blob/f2bd0fc399606d14b55f3f7d732d013f32b33dd5/tensorflow/core/kernels/cwise_op_gpu_cos.cu.cc for these new ops.

**Comment by Mistobaan** [comment]
@vrv finally got a machine with a GPU, I added the missing files and tested using `ci_build.sh GPU pip.sh GPU` on my local dev box.

**Comment by vrv** [comment]
Sorry, conflicts again.  Can you rebase/squash one more time?  Sorry about this :( -- we just have such a huge backlog of issues and PRs. 

Please respond to the thread when you've done this, since GitHub doesn't notify me when you've done this.  Thanks!

**Comment by Mistobaan** [comment]
oops miss click I did not meant to close the PR. I updated the code in my branch.

**Comment by vrv** [comment]
Can you reopen?  GitHub for some reason doesn't let me re-open this. asofjdsfsdfaldsfds

**Pull request closed without merging**
