### PR TITLE
[ROCm] fix triangular solve

### PR DESCRIPTION
**Pull request by jayfurmanek**
The following tests recently began failing for ROCm:

//tensorflow/compiler/tests:matrix_inverse_op_test_gpu
//tensorflow/compiler/tests:matrix_inverse_op_test_gpu_mlir_bridge_test
//tensorflow/compiler/tests:matrix_solve_op_test_gpu
//tensorflow/compiler/tests:matrix_solve_op_test_gpu_mlir_bridge_test
//tensorflow/compiler/tests:matrix_triangular_solve_op_test_gpu
//tensorflow/compiler/tests:matrix_triangular_solve_op_test_gpu_mlir_bridge_test
//tensorflow/compiler/xla/service/gpu/tests:bef_executable_test_gpu
//tensorflow/compiler/xla/tests:triangular_solve_test_gpu

This was due to the introduction of the batched version of the triangular solve operation in cublas in: https://github.com/tensorflow/tensorflow/commit/d797b6d5f09ebde355a58a48b1d8fb8f61f657e2

This PR adds the same thing for ROCm and rocblas.

One interesting difference is the MakeBatchPointers call, which is implemented in PTX in the CUDA implementation. For ROCm, we add a new helper file with the code for this kernel. This kernel will be usable for other batched operations as well (ex: cholesky).

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@cheshire @chsigg @deven-amd

**Review by cheshire — APPROVED** [review]

**Comment by jayfurmanek** [comment]
@cheshire Can you re-approve, please? Thanks! (only change was buildifier/sanity stuff)

**Comment by jayfurmanek** [comment]
@cheshire  Gentle ping on this one. Thx!

**Comment by jayfurmanek** [comment]
I pushed one more fix here (for BEF/TFRT) since this is still open.

**Comment by jayfurmanek** [comment]
@chsigg FYI

**Review by cheshire — APPROVED** [review]

**Comment by gbaned** [comment]
@jayfurmanek Can you please address Ubuntu Sanity errors? Thank you!

**Comment by jayfurmanek** [comment]
ah, I though I fixed that already. Sorry! Should be fixed now.

**Review by cheshire — APPROVED** [review]

**Comment by jayfurmanek** [comment]
Ugh, note to self - just use buildifier even on small little format things that are easy to fix manually.
Sanity *should* pass now.
Sorry for the churn.

**Review by cheshire — APPROVED** [review]

**Pull request merged**
