### PR TITLE
added audio_ops.cc to tf_op_files.txt to fix the Op type not registered DecodeWav error …

### PR DESCRIPTION
**Pull request by jeffxtang**
…- https://github.com/tensorflow/tensorflow/issues/15921

### CODE REVIEW

**Comment by jeffxtang** [comment]
I signed it!

**Review by petewarden — APPROVED** [review]

**Comment by andrewharp** [comment]
Is there a reason this was closed and not merged? I'm seeing the same issue with the makefile build.

**Comment by jeffxtang** [comment]
@andrewharp sorry I closed it too fast.. please merge it first. 

Btw, I noticed there're other .cc files in the tensorflow/core/ops directory that are not included in the tf_op_files.txt file. Should all the ops/*.cc be included in tf_op_files.txt, as suggested by https://www.tensorflow.org/mobile/prepare_models: "Operations are broken into two parts. The first is the op definition, which declares the signature of the operation, which inputs, outputs, and attributes it has. These take up very little space, and so all are included by default. "

**Comment by naktinis** [comment]
@andrewharp I also had the same question as @jeffxtang about operations that are not included in `tf_op_files.txt` (or even in [core/kernels/BUILD](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/BUILD) for that matter), such as `cwise_op_cos.cc`. Is there any particular reason why some operations are not included there?

If I'm understanding the building process correctly, as a result at the moment `android_extended_ops` group includes complex operations such as `decode_wav_op.cc`, but not something as basic as cosine operation `cwise_op_cos.cc`.

**Pull request merged**
