### PR TITLE
r1.0 python 3.5 fixes

### PR DESCRIPTION
**Pull request by jhseu**

### CODE REVIEW

**Comment by gunan** [comment]
Aww man, I just triggered release builds.
I'll kill them to quickly run these PR builds instead.

**Review by gunan — APPROVED** [review]

**Comment by liaoshen439** [comment]
How to set up GPU driver on Ubuntu ?

**Comment by gunan** [comment]
This is definitely not the correct location for any questions.
GPU driver setup i manufacturer for its driver installation instructions.

**Comment by jhseu** [comment]
Jenkins, test this please

**Pull request merged**
