### PR TITLE
Add deprecation notes

### PR DESCRIPTION
**Pull request by alanyee**
-Add or update deprecation notes to metrics_op.py and tensor_util.py
-Minor comment fix in lookup_ops.py

### CODE REVIEW

**Comment by drpngx** [comment]
@ispirmustafa what do you think?

**Comment by sb2nov** [comment]
@ispirmustafa ping

**Review by ispirmustafa — APPROVED** [review]
Thank you Alan

**Comment by alanyee** [comment]
@sb2nov @drpngx do either of you want to run the test suite on my PR?

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by alanyee** [comment]
@drpngx could you test this again? i had to update it due to merge conflict?

**Comment by drpngx** [comment]
Jenkins, test this please

**Comment by alanyee** [comment]
@drpngx the Ubuntu CC test does not seem to have triggered?

**Comment by drpngx** [comment]
Can you look into the failures?

**Comment by alanyee** [comment]
Hmm I not sure why the tests would be failing since I am just adding deprecation notes. One test `failed to create symbolic link` and other has a docker build failing: `The command '/bin/sh -c /install/install_deb_packages.sh' returned a non-zero code: 100`

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Ignoring unrelated failure:
```
ln: failed to create symbolic link '/workspace/tensorflow/contrib/makefile/gen/protobuf-host/protobuf': File exists
```

**Pull request merged**
