### PR TITLE
Add a donate button to README.md

### PR DESCRIPTION
**Pull request by jingyuan-c92**
The **donate** button is a link to [`https://boost-lab.app/tensorflow/tensorflow`](https://boost-lab.app/tensorflow/tensorflow), which provides potential donors the freedom to financially support the developers of `tensorflow`.

At Boost Lab, our mission is to give developers the ability to receive continuous income for their open source work with minimal impact to their workflow.

For a more detailed explanation of how our platform works, we would love it if you check out our [web app](https://boost-lab.app/about).

### CODE REVIEW

**Comment by qlzh727** [comment]
Assigning to @wicke for more input.

**Comment by ewilderj** [comment]
While appreciating the spirit of the idea, I don't think it's appropriate to do something like this: the majority of our developers are employed by Google or some other corporation. Please see https://opensource.google.com/community/ for some of the ways in which Google supports open source and its developers.

**Comment by jing-c** [comment]
🙏 @ewilderj thank you for your reply. And you are absolutely right. Just by looking at the repo statistics alone, I saw that around 90 - 95% of the contributions are made by Google employees (my estimations are probably off haha). Therefore, financial support is most likely not an issue for those developers.

However, the **donate** button could be a way for other parties to show appreciation & support. For example, one of the many companies that use `tensorflow`, or even a YouTuber that teaches a course on this technology. Those parties could want to support `tensorflow`'s development in ways other than just engineering hours.

But, I can see where you are coming from. Because `tensorflow` is backed by Google, external financial support is not a requirement.

Anyways, we appreciate your feedback. And perhaps Boost Lab is only tailored towards projects that does not have the backing of a tech giant.

BTW, we tried out `tensorflow.js` and we love what Google is doing with the technology 👍.

**Comment by ewilderj** [comment]
Thanks @jing-c! Looks like Boost Lab is a new initiative, so if you want any further conversation on this feel free to email me, and I can go into more detail. ewj at google.

**Pull request closed without merging**
