### PR TITLE
Register Not differentiable RandomShuffle

### PR DESCRIPTION
**Pull request by bhack**
https://github.com/tensorflow/tensorflow/issues/6269#issuecomment-267615674

### CODE REVIEW

**Comment by wangpengmit** [comment]
I can review this.

**Review by wangpengmit — APPROVED** [review]

**Review by wangpengmit — APPROVED** [review]

**Review by wangpengmit — APPROVED** [review]

**Comment by bhack** [comment]
As `Py+CPP Test Suite - Ubuntu CPU, Python 3.9` job is required is it failing cause this change or is it broken for something else?

**Comment by wangpengmit** [comment]
Are you able to see the log? The error message I saw is
```
tensorflow/python/eager/pywrap_gradient_exclusions.cc: In function ‘absl::lts_20211102::optional<tensorflow::gtl::FlatSet<int> > OpGradientUnusedOutputIndices(const string&)’:
tensorflow/python/eager/pywrap_gradient_exclusions.cc:914:4: error: too many initializers for ‘std::__array_traits<{anonymous}::OpIndexInfo, 482>::_Type’ {aka ‘{anonymous}::OpIndexInfo [482]’}
  914 |   }};
      |    ^
```
Looks like somehow 482 is not enough. Strange.

**Comment by bhack** [comment]
But I've not changed line 914 in `pywrap_gradient_exclusions.cc:914`

**Comment by bhack** [comment]
It seems that master is now already at 482

**Comment by wangpengmit** [comment]
> But I've not changed line 914

914 is the end of the "logical line". The error is in the middle of the logical line.

> It seems that master is now already at 482

Then it's just a merging conflict. Changing 482 to 483 should fix it.

**Review by wangpengmit — APPROVED** [review]

**Comment by gbaned** [comment]
Seems auto-merge is not happening but the changes are merged into master now, so we can close this. Thank you for the PR.

**Pull request closed without merging**
