### PR TITLE
Numerous improvements made to the tensorflow_issue_template

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Can you rewrite history of this PR so the rename is an actual `git mv` operation instead of remove and add a new file? It makes for easier to review diffs.

**Comment by rylan-justice** [comment]
Sorry for the inconvenience! Did the recent commits fix the issue?

**Comment by mihaimaruseac** [comment]
Not really, it still shows as the file being deleted and recreated.

I think it also gets confused by the fact that there are so many merge commits. You don't need to merge main branch if there is no conflict.

Are you creating the PR from the GitHub UI? From Visual Studio Code? From command line?

**Comment by mihaimaruseac** [comment]
Press `.` on the repository page and you'll get a Visual Code interface where you can move files around, etc.

Alternatively, please make 2 PRs, one with the file moving and one with the edits.

**Comment by rylan-justice** [comment]
Okay, I'll do so. Thank you!

**Pull request closed without merging**
