### PR TITLE
improve GPU device info output

### PR DESCRIPTION
**Pull request by fo40225**
`memoryClockRate(GHz)` is core clock rate actually.

This problem has existed for several years.

### CODE REVIEW

**Comment by Samsomyajit** [comment]
@fo40225  Its true
Core clock refers to the speed of the cores on the Graphics processor. Cores on a GPU are very similar to cores on a CPU. That is because GPUs are structured like your CPU, the difference being that CPU’s are built to be “Jack of all Trades” in terms of what they can do. And GPUs are made to do one thing, very well. Which is why you aren’t using your RX 480 to run Windows. Cores on a GPU render graphics and assets, just like how cores on a CPU handles tasks. Memory Clock, however, is the frequency of the VRAM on the GPU. VRAM is the ram utilized by the GPU. Different to DRAM (The ram sticks that you put on your motherboard), VRAM is used to hold memory for assets that the GPU needs to render such as “hold the shading textures for these trees.” Similar to DRAM, VRAM clocks in frequencies, faster frequencies means the faster the ram can take, hold, and replace short term information. Because unlike your hard drive or SSD, the information is moving back and forth, deleted and replaced, all of the time. So memory needs much higher frequencies than your typical storage device.

**Review by Samsomyajit — DISMISSED** [review]
Core clock refers to the speed of the cores on the Graphics processor. Cores on a GPU are very similar to cores on a CPU. That is because GPUs are structured like your CPU, the difference being that CPU’s are built to be “Jack of all Trades” in terms of what they can do. And GPUs are made to do one thing, very well. Which is why you aren’t using your RX 480 to run Windows. Cores on a GPU render graphics and assets, just like how cores on a CPU handles tasks.

Memory Clock, however, is the frequency of the VRAM on the GPU. VRAM is the ram utilized by the GPU. Different to DRAM (The ram sticks that you put on your motherboard), VRAM is used to hold memory for assets that the GPU needs to render such as “hold the shading textures for these trees.” Similar to DRAM, VRAM clocks in frequencies, faster frequencies means the faster the ram can take, hold, and replace short term information. Because unlike your hard drive or SSD, the information is moving back and forth, deleted and replaced, all of the time. So memory needs much higher frequencies than your typical storage device.

**Review by chsigg — CHANGES_REQUESTED** [review]
There are a number of unrelated formatting changes. Could you please revert them?

**Review by chsigg — APPROVED** [review]
Thanks!

**Pull request merged**
