### PR TITLE
 Recover the lost output channel number of atrous convolution for NC format

### LINKED ISSUE #13861: Channel number of convolution output is unspecified when atrous rate > 1
Python 2.7
Tensorflow v1.2.0-rc2-21-g12f033d and v1.3.0-rc1-2361-gd1286ab

Easily reproduced by the following code:
``` Python
x = tf.placeholder(tf.float32, [1, 10, None, None])
w = tf.zeros([3, 3, 10, 20])
y = tf.nn.convolution(x, w, 'VALID', [1]*2, [2]*2, data_format='NCHW')
print(y)
```
The input has known channel number but unknown width and height, in NCHW format. The convolution has rate >= 2. The channel number of the output `y` is obviously known, `(1, 20, None, None)` in this example, depending on the shape of `w`. However the execution result gives 
```
Tensor("convolution/BatchToSpaceND:0", shape=(1, ?, ?, ?), dtype=float32)
```
I believe this is related to the reshaping operation in the atrous convolution. The issue happens only when the spatial shape is unknown and with NCHW format. Not sure if this happens to the latest version.

### PR DESCRIPTION
**Pull request by facaiy**
Fix #13861.

### How to test

+ [x] add new test case
+ [ ] pass all tests.

### CODE REVIEW

**Comment by facaiy** [comment]
Hi, @ebrevdo , @drpngx .  May you take a look?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by facaiy** [comment]
I checked the failed log on python 3:  Timed out  //tensorflow/python/keras:data_utils_test. seems unrelated?

**Comment by facaiy** [comment]
Now the master branch of tensorflow/tensorflow failed on both Linux CPU and mac CPU, perhaps it blocks the PR. I'll merge the upstream and test the PR again when its latest master branch passes all tests.

**Comment by facaiy** [comment]
Hi, might we retest the PR? Thanks very much.

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by facaiy** [comment]
Thanks, @jhseu. Could restart the test?

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by facaiy** [comment]
Hi, I test the failed case on my linux machine (python 3), however it works.

```bash
(py36) [facai@h1077922 tensorflow]$ bazel test -c opt //tensorflow/contrib/learn:dnn_linear_com
bined_test
INFO: Elapsed time: 1038.011s, Critical Path: 377.41s
//tensorflow/contrib/learn:dnn_linear_combined_test                      PASSED in 223.9s
  Stats over 4 runs: max = 223.9s, min = 135.5s, avg = 167.4s, dev = 34.1s

Executed 1 out of 1 test: 1 test passes.
```

The failure seems introduced by the master branch itself, right?

**Comment by yifeif** [comment]
Jenkins, test this please.

**Comment by facaiy** [comment]
Thank you, @yifeif. Do I need rebase the latest commit to make CLA check pass?

**Comment by drpngx** [comment]
Framework failure.

Jenkins, test this please.

**Comment by drpngx** [comment]
No, but @martinwicke can override and merge.

**Comment by drpngx** [comment]
So can @gunan I think.

**Comment by facaiy** [comment]
Thank you, @drpngx !

**Comment by drpngx** [comment]
Thank you @gunan !

**Pull request merged**
