### PR TITLE
Added custom loss logging frequency to estimator train

### PR DESCRIPTION
**Pull request by ankitvgupta**
Fixes https://github.com/tensorflow/tensorflow/issues/17115

Added an optional parameter to log losses to tf.estimator

### CODE REVIEW

**Comment by ankitvgupta** [comment]
I signed it!

**Comment by martinwicke** [comment]
If we take this change, we should take it for train_and_evaluate, not necessarily contrib.learn.

**Comment by xiejw** [comment]
RunConfig has log_step_count_steps already. For consistency, probably we should define it there and let Estimator respect this configuration. wdyt?

**Comment by ankitvgupta** [comment]
Oh that's great - I would definitely support having that config parameter getting passed to the appropriate functions.

**Comment by ankitvgupta** [comment]
I figured it'd be simpler to just make a new PR with that change - here it is: https://github.com/tensorflow/tensorflow/pull/17157

**Comment by ispirmustafa** [comment]
based on new PR, closing this one.

**Pull request closed without merging**
