### PR TITLE
[WIP] Clean shell scripts

### PR DESCRIPTION
**Pull request by redianthus**
Hi,

I started to fix various things spotted by ShellCheck.

I used the following command: `find -O3 . -type f -name '*.sh' -exec shellcheck -x {} \;`.

There are quite a lot of things remaining:

```sh
find -O3 . -type f -name '*.sh' -exec shellcheck -x {} \; | wc -l
3731
```

I'll fix all of them in a few days. But to ease the process of reviewing, I open the PR now, and will add a new commit each time. At the end, I'll merge all of them in a single commit.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by zapashcanon** [comment]
@aselle, @protoget, in some cases where shellcheck raises false positives, I can silence them by [adding a comment](https://github.com/koalaman/shellcheck/wiki/Directive). It would makes things easier for me here as there are a lot of warnings... but I'd like to know if that would be a problem to add such comments to the source code ?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 59 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 74 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 89 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 104 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 119 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 134 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 149 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 169 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 185 days with no activity and the `awaiting review` label has been applied.

**Comment by aselle** [comment]
These changes look generally good. Could you rebase as some conflicts have appeared

**Comment by aselle** [comment]
not sure how bad 
```
# shellcheck disable=SC2059
```

**Comment by martinwicke** [comment]
I'd feel better without the comments (just take them out, I guess), since we're not using shellcheck. The changes the tool suggested/made all look good though.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rthadur** [comment]
@zapashcanon  can you please re base your branch

**Pull request closed without merging**
