### PR TITLE
Moving code using new to absl::make_unique. This should make cleaning…

### PR DESCRIPTION
**Pull request by ibebrett**
… this up when std::make_unique is available easier with automatic tooling easier, and remove references to new.

### CODE REVIEW

**Review by gunan — APPROVED** [review]

**Comment by ibebrett** [comment]
Can't check at the moment, but did my changes cause the above CI build failures?

**Comment by gunan** [comment]
There seems to be some new build failures, so I think yes. You may need to download the full log to see the errors though.

**Comment by ibebrett** [comment]
Ok I fixed a build file error (trailing comma). Now I am just getting license check errors in the sanity checker:
```
=== Summary of sanity check results ====
1. do_pylint PYTHON2: Python 2 pylint
  PASS
2. do_pylint PYTHON3: Python 3 pylint
  PASS
3. do_check_futures_test: Check that python files have certain __future__ imports
  PASS
4. do_buildifier: buildifier check
  PASS
5. do_bazel_nobuild: bazel nobuild
  PASS
6. do_pip_package_licenses_check: pip: license check for external dependencies
  FAIL
7. do_lib_package_licenses_check: C library: license check for external dependencies
  FAIL
8. do_java_package_licenses_check: Java Native Library: license check for external dependencies
  FAIL
9. do_pip_smoke_test: Pip Smoke Test: Checking py_test dependencies exist in pip package
  PASS
10. do_check_load_py_test: Check load py_test: Check that BUILD files with py_test target properly load py_test
  PASS
11. do_code_link_check: Code Link Check: Check there are no broken links
  PASS
12. do_cmake_python_sanity: Test entries in /tensorflow/contrib/cmake/python_{modules|protos|protos_cc}.txt for validity and consistency
  PASS
13. do_check_file_name_test: Check file names for cases
  PASS
```
It looks like there is a white list and blacklist containing absl here:
https://github.com/tensorflow/tensorflow/blob/1752d9c8fac5f6cf85a41e77d92e2743adbfc446/tensorflow/tools/ci_build/ci_sanity.sh#L312
but maybe not specifically absl memory?

Should I change it to link the entire thing, or maybe we should change the blacklist white list mechanism?

Note: This is the specific error in the log
```
FAIL: mismatch in packaged licenses and external dependencies
Please remove the licenses for the following external dependencies:
@bazel_tools//src
```

**Comment by ibebrett** [comment]
Now according to ubuntu cc:
https://source.cloud.google.com/results/invocations/7df7e734-4077-4a68-a497-410680df8b6b/targets

arrow_drop_down  Broken target (1)
//tensorflow/core:lib_gtl_inlined_vector_test

Yet this passes locally for me:

Target //tensorflow/core:lib_gtl_inlined_vector_test up-to-date:
  bazel-bin/tensorflow/core/lib_gtl_inlined_vector_test
INFO: Elapsed time: 3.290s, Critical Path: 2.70s
INFO: Build completed successfully, 8 total actions
//tensorflow/core:lib_gtl_inlined_vector_test                            PASSED in 0.0s

Executed 1 out of 1 test: 1 test passes.

Is the CC Build influenced by something other than my changes?

**Comment by gunan** [comment]
It is curious.
Could you rebase your change on top of current master? Thats all I can think of.

**Comment by ibebrett** [comment]
Rebased and pushed. The test still passes locally even after rebase on master.

**Comment by ibebrett** [comment]
I just pulled and ran:

```
bazel test //tensorflow/contrib/bayesflow:hmc_test --test_output=errors
```
I am getting an error, but I checked and its also broken on master for me...

**Comment by ibebrett** [comment]
OK rebased once again, I can't test at the moment, but if the build isn't breaking maybe it will work?

**Comment by ibebrett** [comment]
OK, the test that previously broke seems to work after rebase.

**Comment by ibebrett** [comment]
Should be good now that we rebased?

**Comment by jhseu** [comment]
Mind checking the test failures?

**Comment by ibebrett** [comment]
Will rebuild and push soon, but going but in the error logs reported by gpu cc, I see things like this showing up:

```

: /tmpfs/src/github/tensorflow/tensorflow/core/kernels/BUILD:2503:1: Couldn't build file tensorflow/core/kernels/_objs/svd_op_gpu/tensorflow/core/kernels/svd_op_gpu.cu.o: error while parsing .d ERRORfile: /tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/core/kernels/_objs/svd_op_gpu/tensorflow/core/kernels/svd_op_gpu.cu.d (No such file or directory)
In file included from /usr/local/cuda-9.0/bin/..//include/common_functions.h:50:0,
                 from /usr/local/cuda-9.0/bin/..//include/cuda_runtime.h:115,
                 from <command-line>:0:
/usr/local/cuda-9.0/bin/..//include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
external/com_google_absl/absl/base/config.h:196:5: note: in expansion of macro '__CUDACC_VER__'
     __CUDACC_VER__ >= 7000
     ^
ERROR: /tmpfs/src/github/tensorflow/tensorflow/core/kernels/BUILD:2503:1: Couldn't build file tensorflow/core/kernels/_objs/svd_op_gpu/tensorflow/core/kernels/svd_op_gpu.cu.pic.o: error while parsing .d file: /tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/core/kernels/_objs/svd_op_gpu/tensorflow/core/kernels/svd_op_gpu.cu.pic.d (No such file or directory)
In file included from /usr/local/cuda-9.0/bin/..//include/common_functions.h:50:0,
                 from /usr/local/cuda-9.0/bin/..//include/cuda_runtime.h:115,
                 from <command-line>:0:
/usr/local/cuda-9.0/bin/..//include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
```
I am going to rebase and push soon, I'll try to run the above tests.. is there any particular trick to making sure I am running them with the same configuration as the CI setup?

**Comment by ibebrett** [comment]
So after the rebase, on my local machine:
```bazel test //tensorflow/c:c_api_function_test```
works, however, I am assuming the gpu cc CI is setup to run linking to cuda or something like this. That being said, I am not sure my code is causing the above problem?

**Comment by ibebrett** [comment]
Just pushed the rebase, and I'm trying to test via docker gpu with:
```
tensorflow/tools/ci_build/ci_build.sh GPU bazel test //tensorflow/c:c_api_function_test
```

**Comment by martinwicke** [comment]
@gunan -- we apparently already depend on ABSL C++, which I think we decided is fine. But we need to be careful about any such symbol not making it into any API.

**Comment by martinwicke** [comment]
I will rerun the tests here, it's possible that this does not work for nvcc?

**Comment by martinwicke** [comment]
@ibebrett there are a number of build errors in the GPU builds. Not sure what the cause is, but could you take a look?

**Comment by ibebrett** [comment]
I will try to look later tonight.

**Comment by gunan** [comment]
Looks like the problem may be caused by `CUDA_CC_VER` used in `absl/base/config.h`
This is already fixed in the head of absl.
@ibebrett Your build will be fixed if you also update this block to use a newer commit:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L110

Could you make that change in this PR too?

**Comment by ibebrett** [comment]
Thanks! Sorry, got busy with the day job. I'll make this fix tonight. Thanks for figuring this out!

**Comment by ibebrett** [comment]
Ok I think i updated the build file correctly?

**Comment by gunan** [comment]
Thank you very much for patiently working through the issues.
I just triggered the tests, let's see if this solves the problems.

**Comment by ibebrett** [comment]
Ok, looks like this is now only breaking the cmake build

I think we can probably follow the directions for abseil here:
https://github.com/abseil/abseil-cpp/tree/master/CMake

and add a dependency to tensorflow/contrib/cmake/external/ ? (The other cmake dependencies live here it seems).

According to https://bazel.build/, bazel runs on windows.. Is it necessary to maintain an entirely separate build system? Seems like it will mean extra maintenance work.

If the above steps seem reasonable I can take a look tonight after work and try to build out the cmake dep for absiel.

**Comment by gunan** [comment]
Our bazel build on windows still has some problems we need to fix. Until then, we have to maintain the cmake build.

For adding the cmake dependency, your steps look good to me.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
Ping!
Any updates?

**Comment by jhseu** [comment]
Closing due to lack of activity, but feel free to reopen when the issue is addressed. Thanks!

**Pull request closed without merging**
