### PR TITLE
[INTEL MKL] Replace dead Switch nodes with Identity

### PR DESCRIPTION
**Pull request by gaurides**
If the "pred" input of a Switch node is constant, and it is determined to be a dead switch, we can replace it with Identity. In other pass, Identity gets removed and it enables more fusions resulting in performance improvements.

### CODE REVIEW

**Review by ezhulenev — APPROVED** [review]

**Review by ezhulenev — APPROVED** [review]

**Comment by gaurides** [comment]
@ezhulenev - Hi Eugene, can you please provide me details for this 1 check failed "
feedback/copybara — Google internal checks FAILED for runs with create time 2020-12-29T13:31:47.826852083Z."
I am unable to see the details

**Comment by ezhulenev** [comment]
Some of the tests are failing with this PR:

```
//third_party/tensorflow/python/kernel_tests:control_flow_ops_py_test_xla_gpu	FAILED
//third_party/tensorflow/python/kernel_tests:control_flow_ops_py_test	FAILED
//third_party/tensorflow/python/kernel_tests:control_flow_ops_py_test	FAILED
```

Example:

```
[ RUN      ] ControlFlowContextCheckTest.testInvalidContextInCond
I1229 05:37:04.054435    2628 control_flow_util.py:363] Cannot use 'while/Const_1' as input to 'cond/Add' because 'while/Const_1' is in a while loop.

cond/Add while context: None
while/Const_1 while context: while/while_context
```

**Comment by gbaned** [comment]
@gaurides  Can you please check @ezhulenev's comments and keep us posted ? Thanks!

**Comment by gaurides** [comment]
Hi @gbaned  @ezhulenev - ControlFlowTest.testWhileCondWithControl_1 is the failing test case. I have a work around, but working on the right fix. will keep you updated.

**Comment by gaurides** [comment]
@gbaned @ezhulenev  - i updated the PR with changes to fix the failing test

**Comment by gaurides** [comment]
Hi @ezhulenev , did you get a chance to review the changes? Please let me know if looks ok or needs more changes. Thanks.

**Review by ezhulenev — APPROVED** [review]

**Comment by gaurides** [comment]
@ezhulenev  @gbaned  : Can you please share what tests failed if you need me to fix them. How can I reproduce these issues on my end? Thanks!

**Comment by ezhulenev** [comment]
Seems to be a transient build infra failure, not sure to to force pull one more time, @gbaned can you please take a look.

**Comment by gbaned** [comment]
> Seems to be a transient build infra failure, not sure to to force pull one more time, @gbaned can you please take a look.

@ezhulenev  Sure. It is completed successfully now. Thank you!

**Comment by gaurides** [comment]
Hi @gbaned : I wanted to check on this Ubuntu CPU build, if there's something I need to fix. Thanks.
"Ubuntu CPU — Internal CI infrastructure error. Please apply label 'kokoro:force-run' to rerun the build."

**Comment by gaurides** [comment]
Hi @gbaned : can you please provide me inputs on what failed in this build "feedback/copybara — Google internal checks FAILED "? and if possible how to reproduce?
Also, the 2 Windows builds failure don't seem to be related to my changes here. 
Thanks!

**Comment by gbaned** [comment]
@ezhulenev  Can you please take a look on above comments from @gaurides. Thanks!

**Comment by gbaned** [comment]
@ezhulenev Any update on this PR? Please. Thanks!

**Review by ezhulenev — APPROVED** [review]

**Pull request merged**
