### PR TITLE
Correct resnet.py and hdf5_classification.py

### PR DESCRIPTION
**Pull request by sun9700**
**1. Update tensorflow/examples/skflow/resnet.py**
move "upscale to the next block size" to the outer loops
**2. Update tensorflow/examples/skflow/hdf5_classification.py**
classifier.fit and metrics.accuracy_score takes ndarray as input.
Direct input of HDF5 dataset will cause TypeError: PointSelection **getitem** only works with bool use HDF5 dataset's value or convert to numpy array

### CODE REVIEW

**Comment by sun9700** [comment]
I have signed it！
Google account: sunyu.buaa@gmail.com
GitHub account: sun9700@foxmail.com

Best wishes！

**Comment by terrytangyuan** [comment]
@sun9700 Could you provide a failing example that's reproducible? Thanks.

**Comment by sun9700** [comment]
@terrytangyuan 
**The resnet.py 's error is obvious**
Traceback (most recent call last):
  File "/home/sun/tensorflow/tensorflow/examples/skflow/resnet.py", line 158, in <module>
    mnist.train.images, mnist.train.labels, logdir='models/resnet/')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 241, in fit
    self._setup_training()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 156, in _setup_training
    self._out)
  File "/home/sun/tensorflow/tensorflow/examples/skflow/resnet.py", line 119, in res_net
    net = conv + net
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 520, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 44, in add
    return _op_def_lib.apply_op("Add", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 694, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2155, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1611, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1367, in _BroadcastShape
    % (shape_x, shape_y))
**ValueError: Incompatible shapes for broadcasting: (?, 14, 14, 128) and (?, 14, 14, 256)**

**Comment by terrytangyuan** [comment]
Sorry I meant hdf5 example. BTW, you need to use the primary email of your Github to sign CLA.

**Comment by sun9700** [comment]
@terrytangyuan The error of hdf5_classification.py only occurs in the latest (20160530) nightly binaries. It works in my previous tensorflow.

Traceback (most recent call last):
  File "/home/sun/tensorflow/tensorflow/examples/skflow/hdf5_classification.py", line 46, in <module>
    classifier.fit(X_train, y_train)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 172, in fit
    monitors=monitors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 433, in _train_model
    monitors=monitors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 346, in train
    reraise(*excinfo)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 272, in train
    feed_dict = feed_fn() if feed_fn is not None else None
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/data_feeder.py", line 333, in _feed_dict_fn
    if len(self.X.shape) == 1 else self.X[batch_indices])
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 419, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/selections.py", line 71, in select
    sel[arg]
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/selections.py", line 209, in __getitem__
    raise TypeError("PointSelection __getitem__ only works with bool arrays")
**TypeError: PointSelection __getitem__ only works with bool arrays**

**Comment by terrytangyuan** [comment]
@sun9700 Thanks for reporting. However, it should be fixed in data_feeder. Some recent changes broke the example and [this test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/tests/test_data_feeder.py#L137) is not checked on Jenkins since we don't have it installed there. @ilblackdragon @martinwicke Moving forward, are we planning to test those on Jenkins? What's the status on data_feeder refactoring?

**Comment by sun9700** [comment]
@terrytangyuan Yes, thanks for your efforts.

**Comment by martinwicke** [comment]
Yes, we should be running those tests. You can add the h5py package to install_pip_packages.sh (and possibly the 3.5 version of that), then the tests should start running. @caisq FYI in case I forgot something important that would make that a bad idea.

**Comment by ilblackdragon** [comment]
@tensorflow-jenkins test this please!

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
Needs to be rebased.

**Comment by vrv** [comment]
(Sorry for the delay).

**Comment by danmane** [comment]
Hi @sun9700. It's been a month since the last ping, so I'm going to close this PR as stale for now. Please feel free to re-open it when you have time to update it, we would be glad to have it.

**Pull request closed without merging**
