### PR TITLE
Added Gitbook support for the documents.

### LINKED ISSUE #3810: How can I download TF API document?
How can i download TF API document?
Search in webpage is not so convenient.

### PR DESCRIPTION
**Pull request by haosdent**
This fixed #3810. This patch added a script to generate `SUMMARY.md`
for Gitbook and then we could use Gitbook to generate the documents in
pdf or epub format.

### CODE REVIEW

**Comment by haosdent** [comment]
The online preview address is https://haosdent.gitbooks.io/tensorflow-document/content/api_docs/

**Comment by aselle** [comment]
@xmbrst, it looks reasonable to me, but you are the expert on tensorflow docs, so could you have a look?

**Comment by terrytangyuan** [comment]
@haosdent Seems like this only works with relative path instead of full urls? For example, I see the links don't look right in [this page](https://haosdent.gitbooks.io/tensorflow-document/content/tutorials/tflearn/).

**Comment by haosdent** [comment]
hi, @terrytangyuan Thanks for your review, it's because the tensorflow document not follow the markdown syntax. For example,

```
tf.contrib.learn offers a variety of predefined models, called [`Estimator`s]
(../../api_docs/python/contrib.learn.md#estimators), which you can use "out of
```

should be

```
tf.contrib.learn offers a variety of predefined models, called
[`Estimator`s](../../api_docs/python/contrib.learn.md#estimators), which you can
```

We should not insert a new line between `]` and `(`. How about let me fix these errors in documents?

**Comment by terrytangyuan** [comment]
@haosdent Of course. Thanks!

**Comment by yifeif** [comment]
The links are fixed by @haosdent in #4800. @haosdent, would you like to regenerate the preview?

**Comment by haosdent** [comment]
@yifeif Thanks a lot for your ping! I found there are some links `[] ()` (There is a space between `]` and `(`) make the document not perfect after regenerate document. Do you think I should fix those  links first? Or we could continue to add Gitbook support and continue to fix these links later?

**Comment by yifeif** [comment]
@haosdent thanks for your reply. How much work is involved to fix the links? I would say let's fix the links first.

**Comment by haosdent** [comment]
No problem, would post a patch tomorrow. Let me change this to `[WIP]`

**Comment by haosdent** [comment]
hi, @yifeif @terrytangyuan I create the pull request to fix remain links in https://github.com/tensorflow/tensorflow/pull/4850 Sorry for didn't check it carefully before.

**Comment by haosdent** [comment]
WoW Thanks a lot for your quick response. I have regenerated https://haosdent.gitbooks.io/tensorflow-document/content/tutorials/tflearn/ just now after the broken links fixed.

**Comment by terrytangyuan** [comment]
@tensorflow-jenkins Test this please

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Comment by haosdent** [comment]
Have added
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
```

**Comment by haosdent** [comment]
@tensorflow-jenkins Test this please

**Comment by yifeif** [comment]
@tensorflow-jenkins Test this please

**Comment by haosdent** [comment]
Hi, @rohan100jain @yifeif Would you help to review this again? Thank you very much.

**Comment by drpngx** [comment]
Hey, thanks for looking into this!  We had a discussion about what the right thing is internally. We're publishing our docs on Github so people can contribute.  Whatever gets checked in here will be published soon after on tensorflow.org.  Alternate publishing routes are absolutely allowed, but we aren't going to accept them in our core docs repository.

I'm going to close this. Feel free to reopen if you have further comments.

**Pull request closed without merging**
