### PR TITLE
Add `cudnn_rnn_ops` to the Windows build

### LINKED ISSUE #13696: Problem with CuDNN RNNs on Windows
OS: Windows10
Keras version: master (as of today: 2.08+)
Tensorflow backend version: master (as of today ~1.4rc0)

GPU: Geforce GTX 1080Ti (11GB)
Cuda version: v8.0
cuDNN version: cudnn-8.0-windows10-x64-v6.0

First opened as a Keras GitHub issue here (includes full code and error output):
https://github.com/fchollet/keras/issues/8135

Francois Chollet suggested that this may be a Windows TF problem.

Hi, I tried keras.layers.CuDNNLSTM after seeing fchollet's tweet the other day. I have the latest Keras and Tensorflow, but there is a tensorflow problem with the Op 'CudnnRNN' not being registered.

Have I missed something?

Thanks

### PR DESCRIPTION
**Pull request by mrry**
Fixes #13696.

### CODE REVIEW

**Review by av8ramit — APPROVED** [review]

**Comment by av8ramit** [comment]
@mrry do we need this in rc1? + @case540

**Comment by mrry** [comment]
I'd call it a nice to have, but not enough merit creating rc1 if you're not already doing so. (It's fixing an omission that's more than one year old, and today is the first issue I've seen about it.)

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
