### PR TITLE
ci_build: support tensorflow as submodule

### PR DESCRIPTION
**Pull request by jendap**
this enable tensorflow/serving reuse our ci_build

### CODE REVIEW

**Comment by martinwicke** [comment]
@jendap, is this ready to go? You aborted the tests because they were after the critical point?

**Comment by jendap** [comment]
The tests were aborted for unrelated restart of a gpu node. It should be ready. But just for sure...

@tensorflow-jenkins test this please

**Comment by jendap** [comment]
@martinwicke if the test is successful (which it should) it sill be ready.

Note: There is one important thing here - it is upgrading bazel to 0.1.5 for all our ci builds. The 0.1.5 is needed for submodules (serving has tensorflow as a submodule).

**Comment by martinwicke** [comment]
test seems to not have been successful.

**Comment by jendap** [comment]
It did because at that time the mac-python3 was failing on master. It was fixed since. But now master is broken again - the current build will fail again :( I'll start another one once master is fixed.

BTW: Since we have to upgrade bazel to 0.1.5+ I'm going to upgrade it here to the latest - 0.2.0

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

(I just pushed a flaky test fix to public that should help)

**Comment by jendap** [comment]
It did help. Last build was successful on linux. And mac is not touched by this PR.

I have just rebased to master.

**Comment by jendap** [comment]
@vrv @martinwicke can I merge this? The upgrade of bazel can make some noise. But serving team would be happy.

**Comment by jendap** [comment]
Actually as long as nobody use feature in bazel 0.2.0 we are fine. And mac is still on 0.1.4.

**Pull request merged**
