### PR TITLE
Update the get_started_for_beginners.md file

### PR DESCRIPTION
**Pull request by ctiijima**
Matched and added variable names to match the same ones used in the script iris_data.py that it references from models/samples/core/get_started/.

### CODE REVIEW

**Comment by ctiijima** [comment]
I am part of the IBM CLA, and it shows up under my corporate agreements.  I do not know why it did not pass that check...

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 120 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by karmel** [comment]
This doc no longer exists, so I will close this PR. But CC @MarkDaoust and @lamberta in case these changes are still relevant?

**Comment by MarkDaoust** [comment]
These docs got moved to docs_src/guide

`get_started_for_beginners` doesn't exist anymore. `guide/premade_estimators.md` is the closest thing. 
Any fixes would be welcome, especially if the fix is to convert them to a `.ipynb` notebook.

**Pull request closed without merging**
