### PR TITLE
Rename the TFLite library convert_type to tfl_convert_type as it conf…

### PR DESCRIPTION
**Pull request by aardeb**
Rename the TFLite library convert_type to tfl_convert_type as it conflicts with the similarly named library in Tensorflow

### CODE REVIEW

**Comment by aardeb** [comment]
Hi, 
Wanted to ask if I need to do anything else to get this patch reviewed ? 
Thanks
Aaron

**Comment by jpienaar** [comment]
Could you perhaps expand the description to say what issues you ran into? E.g., there are many libraries with the same name, but they are inside different projects/folders, textually name spacing them does not seem very appealing. I'll also add someone from tflite team for review.

**Comment by aardeb** [comment]
I am trying to re-use the TFlite Flatbuffer to MLIR Dialect function using tflite::FlatBufferToMlir() in an external project by linking to the tensorflow libraries. My external project is using a Cmake build system. 

In doing so I end up adding a number of libraries to my build system. It seems I end up with dependencies from both convert_type (tflite) and convert_type (tensorflow) which I cannot link to easily since they have the same name. 

Renaming to tfl_convert_type for the tflite version allows me to end up with a solution where I can link them, in the simplest way possible.

**Comment by aardeb** [comment]
Hi @karimnosseir is there a chance for a review of this pull request please ?

**Comment by karimnosseir** [comment]
It looks the way you are adding the files doesn't take full path in consideration. I am afraid this change is not future proof for other similar scenarios, and we can't guarantee that the files doesn't get renamed again - which might cause collision on your end again.

May be you should perhaps update your build/script to take full path so you avoid any collisions.

Thanks

**Comment by aardeb** [comment]
I understand but in my cmake file when I tried yur suggestion, and I give the full paths then I get cyclic errors in the linker for some reason, and the solution fails to link:

e.g.
Cannot generate a safe runtime search path for target unit_tests because
  there is a cycle in the constraint graph:

I am assuming because the libraries ae coming from the same package but not sure, but there may be some trick I am missing. 

The alternative may be for me to rename the library as part of the build system, but that seems a bit fragile.

**Pull request closed without merging**
