### PR TITLE
[XLA] Bring XLA Transpose021Tiled up-to-date with reference CUDA implementation.

### PR DESCRIPTION
**Pull request by tjingrant**
The Transpose021Tiled is no longer up-to-date with the reference Cuda implementation and this PR updates the XLA to generate codes that resemble the latest reference Cuda implementation. The main improvement is that a two dimensional logical thread block is launched instead of a one dimensional one. Having more threads in a block increases throughput of transpose.

### CODE REVIEW

**Comment by jhseu** [comment]
(Reassigning to balance pull request review load)

**Comment by jhseu** [comment]
Can you merge this into the master branch instead?

**Review by jpienaar — APPROVED** [review]
Looks good. OOC what was the performance impact?

**Comment by jhseu** [comment]
@tjingrant Please copy the changes and send the pull request against the master branch. We're not making anymore changes to the 1.3 branch.

**Comment by jhseu** [comment]
@tjingrant Please copy the changes and send the pull request against the master branch. We're not making anymore changes to the 1.3 branch.

**Pull request closed without merging**
