### PR TITLE
Get path from environment CUDA_PATH 

### PR DESCRIPTION
**Pull request by Victrid**
**Problem**:
When I tried to compile TensorFlow on Arch Linux which CUDA is installed at `/opt/cuda`, `ldconfig` can only locate to its sub-folders. I referred to the official packaging script by Arch Linux and it exports `TF_CUDA_PATH` to bypass this issue, which should not be a permanent solution.
**About this PR**:
Previously only Windows loads path from environment variable `CUDA_PATH`, but this is also a common variable that most CUDA packages on *nix distributions will export. 
The code will append `CUDA_PATH` value to the search path list, so users who can configure it well originally should not be affected, and will provide convenience to newcomers who's trying to install TensorFlow on their machine.

### CODE REVIEW

**Comment by Suraj-Upadhyay** [comment]
I am relatively a new contributor here but I think the `nvcc_version` should be retained despite the pylint warning as it ensures easy readability as to what actually is expected of the function to return.

What do you think ?

**Comment by Victrid** [comment]
> I am relatively a new contributor here but I think the `nvcc_version` should be retained despite the pylint warning as it ensures easy readability as to what actually is expected of the function to return.
> 
> What do you think ?

I think it is distracting to introduce unneeded variables inside functions, which in turn complicates readability of the code.

**Comment by chsigg** [comment]
Hi Jiang, thanks for your suggestion. 

Could you use `CUDA_TOOLKIT_PATH` instead?

I know, `CUDA_PATH` is the standard env variable, but this whole business of finding the local CUDA installation is already complicated enough. We would like to simplify it by requiring a single CUDA toolkit directory, similar to how it's done for TFRT. I just never get to it.

Thanks, and sorry for causing you trouble.

**Comment by Victrid** [comment]
Thanks, I would try your suggestion, and close this PR.

**Pull request closed without merging**
