### PR TITLE
Make callbacks serializable

### PR DESCRIPTION
**Pull request by ivanlen**
Following the suggestion of @fchollet I follow up an old PR of the [keras](https://github.com/keras-team/keras/pull/13001) repository.

### Summary

Add get_config method to callback classes:

Callbacks as well as layers and optimizers have lots of arguments. The get_config method in the callbacks returns a dictionary with the configuration of the callback allowing us to inspect the parameters of the instance. This allow us to understand better the callbacks and even change them if it is necessary easily.

### Objectives 

- This method allows to easily obtain the configuration of a callback without knowing the arguments of the callback. 
- For the sake of completeness classes such as the `layers`, and `optimizers` have the `get_config` method, thus I think that it will be useful to add this method to callback objects.
Additionally:
- It is known that keras object are not pickleable, adding a get_config method to optimizers may enable to share different optimizers configuration without the need of sharing the object themselves.

### CODE REVIEW

**Comment by adriangb** [comment]
I recently tried to make sklearn wrappers serializable. I ended up inspecting the constructors instead of hardcoding the parameter names. I'm wondering if a similar approach would work here. This is as much a suggestion as it is input on the robustness of the approach, I wonder if I am missing any edge cases:

```python3
import inspect


ARGS_KWARGS_IDENTIFIERS = (
    inspect.Parameter.VAR_KEYWORD,
    inspect.Parameter.VAR_POSITIONAL,
)

class Callback(object):

    renamed_params = {
        'chief_worker_only': '_chief_worker_only',
    }
    
    def get_config(self):
        config = dict()
        for init in reversed(self.__class__.__mro__):  # invert order so that child class __init__ superseeds parent's
            for p in inspect.signature(init).parameters.values():
                if p.kind not in ARGS_KWARGS_IDENTIFIERS:
                    config[p.name] = getattr(self, p.name, None)

        # manual hardcode
        for param_name, attribute_name in self.renamed_params.items():
            config[param_name] = getattr(self, attribute_name)

        # a quick check
        assert None not in config.values()

        return config
```

In theory, base classes just need to edit `renamed_params`.

**Comment by ivanlen** [comment]
I don't see any edge cases at first glance, and actually my first attempt of the the PR was implementing something like this.

However after looking how the `get_config` method was implemented in other classes in layers or losses.py I decided to implemented in this way. I don't think that because in the other classes it is implemented like this I must implemented in the same way, but I was sure that after the refactor the functionality was the desired one and I am not missing any edge cases.

I think that your approach together with a bunch of tests could definitely work in this and the other classes, but it sounds to me more a global refactor and I was looking for a simple (and maybe more robust) implementation to have the functionality.

**Comment by adriangb** [comment]
That makes sense. Maybe it could be used as a mixin with just the `get_config` and `set_config` methods. Would you mind pointing me in the direction of some of the other implementations of `get_config` you are referencing so I can take a look and see if something like this would work more broadly?

**Comment by ivanlen** [comment]
> That makes sense. Maybe it could be used as a mixin with just the `get_config` and `set_config` methods. Would you mind pointing me in the direction of some of the other implementations of `get_config` you are referencing so I can take a look and see if something like this would work more broadly?

Absolutely, regarding the Layers checkout the `Conv` class in `/tensorflow/python/keras/layers/convolutional.py` or any of the classes in `/tensorflow/python/keras/layers/core.py` .
And regarding the losses checkout `/tensorflow/python/keras/losses.py`. In this second case it is not that hardcoded.

**Comment by gbaned** [comment]
@ivanlen Can you please resolve conflicts? Thanks!

**Comment by ivanlen** [comment]
> @ivanlen Can you please resolve conflicts? Thanks!

@gbaned 
done!

**Comment by gbaned** [comment]
@ivanlen Can you please resolve conflicts? Thanks!

**Comment by ivanlen** [comment]
@gbaned done!

**Comment by ivanlen** [comment]
By the way, I am receiving this message, but I don't know that it is causing it

`Error: Failed to update ref: HttpError: Reference does not exist` when running:
https://github.com/ivanlen/tensorflow/runs/1550590136?check_suite_focus=true

**Comment by gbaned** [comment]
@ivanlen  Can you please resolve conflicts? Thanks!

**Comment by ivanlen** [comment]
@gbaned, the conflicts are solved.

**Comment by gbaned** [comment]
@ivanlen Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by ivanlen** [comment]
@gbaned , conflicts solved.

**Comment by gbaned** [comment]
@ivanlen Can you please resolve conflicts? Thanks!

**Comment by ivanlen** [comment]
@gbaned, done
;)

**Comment by mihaimaruseac** [comment]
This should be moved to keras repo.

CC @qlzh727

**Comment by qlzh727** [comment]
Thanks for the PR. Keras code has been moved to keras-team/keras repository, and the old code in tensorflow/python/keras will be removed soon. Please send your PR to the new repo and we will take it from there. Thanks.

**Comment by adriangb** [comment]
It's quite unfortunate that this PR sat without review for 1.5 years, and now it is not viable anymore because of changes in repo structures.

**Comment by ivanlen** [comment]
@adriangb it's funny that it is a super simple PR, but it seems that maintainers have other priorities. My original PR was made more than two years ago on [keras repo](https://github.com/keras-team/keras/pull/13001), LOL.
I guess that I will have to make the PR again... and again, and again.

**Comment by qlzh727** [comment]
Very sorry for the bad experience you have had so far. Clearly we need to better to track and review our PR. I can mirror the content from this PR to the keras-team/keras if you don't have any free cycle to do this. Let me know if you are ok with that, or you still would like to contribute.

**Comment by ivanlen** [comment]
Thank you for the reply @qlzh727, I will try to upload a new PR to the new repo. If I do not have that time I'll let you know.
Cheers.

**Pull request closed without merging**
