### PR TITLE
lite: Add C API for variable tensors

### PR DESCRIPTION
**Pull request by idstein**
Added new experimental C API to access variable tensors. This enables to capture and restore stateful models.

### CODE REVIEW

**Comment by gbaned** [comment]
@idstein  Can you please resolve conflicts? Thank you!

**Comment by idstein** [comment]
> @idstein Can you please resolve conflicts? Thank you!

Done.

**Comment by gbaned** [comment]
Hi @miaout17 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @miaout17 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @miaout17 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @miaout17 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rascani Can you please review this PR ? Thank you!

**Review by rascani — APPROVED** [review]

**Comment by LukeBoyer** [comment]
@sirakiin this look ok to you?

**Pull request merged**
