### PR TITLE
Clean bazel `all_files` targets

### PR DESCRIPTION
**Pull request by Androbin**
Broken out of #15166

### CODE REVIEW

**Comment by Androbin** [comment]
@jart Friendly ping.

**Comment by Androbin** [comment]
- `tensorflow/python/platform/default` -> removed in 2b74220466957e7fbc86ebe3da5ead9a0e4f5169
- `tensorflow/contrib/bayesflow/examples/**` -> removed in 2ccf3aba424405d82e69f03021435e48f54656fb
- `tensorflow/contrib/ios_examples/**` -> moved to `tensorflow/examples/ios` in fdb8e29354ce93afa8c2335a6287a59eb37d42fc
- `tensorflow/contrib/learn/python/learn/dataframe` -> removed in 27ad708b90cdb62e6aeb7c1378a23ff8cc9c1790
- `tensorflow/contrib/metrics/ops` -> moved to `tensorflow/core/ops` in 1af94c269874440373c1d18d823110b1f5eabc19
- `tensorflow/contrib/periodic_resample/python/kernels` -> never existed
- `tensorflow/contrib/tensor_forest/core/ops` -> moved to `tensorflow/contrib/tensor_forest/kernels` in 877aff8a028c495ea7d2d509fb7f8bc78bf0da2d
- `tensorflow/contrib/tensor_forest/data` -> moved to `tensorflow/contrib/tensor_forest/python/ops` 70b6a5d7605d28a3df93295d1b89d9eee4965ea7

**Review by jart — CHANGES_REQUESTED** [review]
I don't understand this change. `//tensorflow:all_opensource_files` is a remnant of our old sync process, which we haven't had time to delete. There appears to be a couple small uses of it remaining, which can easily be removed.

**Comment by Androbin** [comment]
@jart The tests of PR #15166 match the entries of some text files against the total directory hierarchy to spot invalid entries as well as alert about non-existent but expected entries.

To do so, I have included `//tensorflow:all_opensource_files` as bazel `data` dependency which works just fine in principle. Although I had to work around Python resolving all imports (even generated) to the `runfiles` directory.

If you have a way at hand to require only a summary of the directory hierarchy but not the file contents, I am open ears.

**Comment by Androbin** [comment]
@gunan What you say?

**Comment by Androbin** [comment]
@gunan If you don't mind.

**Review by gunan — APPROVED** [review]

**Comment by Androbin** [comment]
@jart Have you figured another way or are you okay with this, too?

**Comment by Androbin** [comment]
@yifeif Could you run the CI tests, please?

**Comment by Androbin** [comment]
@martinwicke Since [you first added the `all_opensource_files` target](https://github.com/tensorflow/tensorflow/commit/75d7b02b01d35285a15cd5c3ff8cf4be66abdb78):
Do you [agree with @jart](https://github.com/tensorflow/tensorflow/pull/15368#pullrequestreview-83662303) that this should be removed?
And if so, how would we resolve the [existing use cases](https://github.com/tensorflow/tensorflow/pull/15166#issuecomment-352110138)?

**Review by jart — APPROVED** [review]
I agree with @gunan. Thank you for the contribution.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by martinwicke** [comment]
@jart I don't believe :all_opensource_files can be removed, or at least I don't know how. I thought that there are still rules that require data access to all files. Maybe this has changed?

**Comment by jart** [comment]
The way I'd go about removing it, is by changing `data = [":all_opensource_files"]` to list legitimate top-level build targets instead, which is what [`:build_pip_package`](https://github.com/tensorflow/tensorflow/blob/3571514ec20d3da04b82abd239a4e5817dbfd5d8/tensorflow/tools/pip_package/BUILD#L141) does. Then Bazel figures out all the transitive stuff.

This would bring some small benefits aside from cleanup. For example, [`:check_futures_test`](https://github.com/tensorflow/tensorflow/blob/3571514ec20d3da04b82abd239a4e5817dbfd5d8/tensorflow/tools/test/BUILD#L108) would be able to test generated sources too.

The `:all_opensource_files` pattern is mostly useful with tools like [MOE](https://github.com/google/moe) when Bazel is building your tarball and you're willing to put up with the extra pain to avoid doing things like leaking the assembly code for some space age algorithm that got schlepped in from part of the monolithic codebase you've never seen.

So if we're 100% on board with Copybara, removing should be doable with some toil.

**Comment by martinwicke** [comment]
The point of the check_futures_test is that it can check files that you have not thought about. So unless we have a global target which is guaranteed to include all python files, I don't see how we can replace all_opensource_files for it.

And since bazel hides anything inside a directory with a BUILD file, all BUILD files must have their own target.

**Comment by jart** [comment]
I now understand what you meant. As far as the `:all_opensource_files` pattern goes, we implement it in pretty much the best way possible (with the presubmit and all.) I'm just talking about alternatives with different tradeoffs.

For example, on the TensorBoard team, we went along with the Copybara vision of just running these sorts of tests and tools independently of Bazel. For example, we run pylint from our [.travis.yml](https://github.com/tensorflow/tensorboard/blob/master/.travis.yml#L89) file.

**Comment by martinwicke** [comment]
That would be great solution -- we can add these tests to sanity, where we already run a bunch of unrelated test outside of bazel.

**Comment by Androbin** [comment]
> That would be great solution -- we can add these tests to sanity, where we already run a bunch of unrelated test outside of bazel.

Can we still import `tensorflow.python.platform.test` from there?
And if not, shall I rewrite #15166 in Bash or something?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by Androbin** [comment]
Test failure `check_futures_test` due to files that were not found by the test before this cleanup.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by Androbin** [comment]
@martinwicke We should make e.g. `check_futures_test` a Sanity Check, not depending on things like `all_opensource_files`. Else we end up with silent errors like the ones I unexpectedly had to fix here.

**Comment by martinwicke** [comment]
I agree. We can probably make anything currently relying on all_opensource_files into a check run in [sanity](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/ci_sanity.sh). 

That already contains a function to get all changed python files, so running a regex over those to check for the future imports should be super-easy. I'd love a PR for that.

**Comment by gunan** [comment]
I disagree.
We should exclusively keep only quick running things on sanity build. Currently, makefile builds depends on all_opensource_files.

If @yifeif can move makefile to not use all_opensource_files, I am ok with what @martinwicke suggests.

**Comment by martinwicke** [comment]
The futures check should be very fast (much faster than, say, pylint: it only check for the existence of from future import lines in all changed python files).

I hadn't considered makefile -- why does that rely on all_opensource_files?

**Comment by gunan** [comment]
It is due to the new infra. All makefile build is wrapped in a bazel target.

**Comment by yifeif** [comment]
Are we talking about wrapping makefile build output with bazel? The bazel part doesn't use all_opensource_files.

**Comment by drpngx** [comment]
I am removing the dep to `third_party/{fft2d,flatbuffers,eigen3}` which we don't control fully and doesn't work well internally for now. Also, for some reason the `contrib/mpi:all_files` and `mpi_collectives:all_files` are missing. We should figure that out internally.

**Comment by Androbin** [comment]
@drpngx `contrib/mpi{_collectives}:all_files` seems to be a visibility issue.

**Pull request merged**
