### PR TITLE
Try RecursivelyCreateDir Except os.makedirs solution to Create Missing Path

### PR DESCRIPTION
**Pull request by tanfiona**
Previous version hits a bug when trying to run tensorflow wrapped in other scripts. 
E.g. while replicating [UberAI Plato](https://github.com/uber-research/plato-research-dialogue-system#running-plato) project, will hit the following error:

`tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: models/camrest_nlu/sys\experiment_run_0\model\log\train; No such file or directory`

With os method, it quickly resolves the issue.

### CODE REVIEW

**Comment by pillowtann** [comment]
@googlebot I signed it!

**Comment by mihaimaruseac** [comment]
What operating system do you get the failure on? The API is supposed to match the python one, it seems there is an issue with `/` and `\` confusion.

**Comment by pillowtann** [comment]
Hi @mihaimaruseac , I'm using Windows 10. I see similar problems faced by others on [this thread](https://github.com/ibab/tensorflow-wavenet/issues/255).

**Comment by mihaimaruseac** [comment]
I assigned a bug internally for me to fix this. Unfortunately, I won't be able to send a fix in the next 2 weeks due to overworking :(

**Comment by pillowtann** [comment]
Yep no worries! Thanks for looking into it. Let me know if I can help with anything.

**Comment by gbaned** [comment]
@mihaimaruseac  Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
Hi @mihaimaruseac Any update on this PR? Please. Thank you!

**Comment by mihaimaruseac** [comment]
I no longer work in TF, except drive-by contributions or emergency.

**Comment by gbaned** [comment]
Hi @superbobry Can you please review this PR ? Thank you!

**Comment by mihaimaruseac** [comment]
Same as https://github.com/tensorflow/tensorflow/pull/42138#issuecomment-1351961713

**Comment by mihaimaruseac** [comment]
Closing stale PR. Should be reopened when modular filesystem is fully implemented.

**Pull request closed without merging**
