### PR TITLE
TF Framework ops_eager_test missing test case add

### PR DESCRIPTION
**Pull request by Dayananda-V**
1-disable_eager_execution api test case

### CODE REVIEW

**Comment by Dayananda-V** [comment]
@qlzh727 

Help to review the changes. Thanks....

**Review by tomhennigan — APPROVED** [review]

**Comment by hgadig** [comment]
@pragyaak  Please help proceeding with the next steps as I've some access issues(I'm trying to resolve).

**Comment by rthadur** [comment]
@Dayananda-V seems one of the file has been moved or deleted `
        tensorflow/tensorflow/python/framework/ops_eager_test.py
      `  can you please check

**Comment by Dayananda-V** [comment]
@rthadur 

This change is closing and update PR #26379 can be find here.

**Pull request closed without merging**
