### PR TITLE
Fix test breakage on Mac Python3 due to assert_called()

### PR DESCRIPTION
**Pull request by caisq**
Replace assert_called() with self.assertTrue and called.

### CODE REVIEW

**Comment by caisq** [comment]
Testing mac python3 build with experimental build at: http://ci.tensorflow.org/view/Experimental/job/experimental-cais-master-mac/12/console

**Comment by caisq** [comment]
Fixes ongoing nightly build breakages such as http://ci.tensorflow.org/view/Tensorflow%20Jenkins%20Monitored%20builds/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=NO_PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=mac-slave/635/console

**Review by drpngx — APPROVED** [review]
Thank you!

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by xiejw** [comment]
Thanks for the fix. But two questions here
1) Why assert_called is not allowed on Mac Python3?
2) The change passed all internal tests. Do we have a better way to find this broken issue earlier?
Thanks

**Pull request merged**
