### PR TITLE
[TF-TRT] Refactoring Step 1 - Allowing `_pywrap_py_utils` to be lazy loaded properly

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
TF-TRT Refactoring Step 1
- This PR prepares the ground for https://github.com/tensorflow/tensorflow/pull/58346
- Allows the C++ libs to be lazy loaded.

**To be noted:**
Some changes are justified by the upcoming changes (like the creation of `types.py` & `lazy_utils.py`). They will make more sense when the complete scope of the refactoring see #58346 is being considered.

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
@bixia1 for review

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @pjannaty Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @pjannaty Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @pjannaty Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @pjannaty Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @DEKHTIARJonathan Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @DEKHTIARJonathan, @pjannaty  I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for your contribution!

**Pull request closed without merging**
