### PR TITLE
Add output_shape parameter to transposed2d_convolution layer

### PR DESCRIPTION
**Pull request by marcociccone**
I just added this parameter that was missing in the `conv2d_transpose layer`.
If `output_shape is None`, then the layer acts as usual returning the smallest shape possible

### CODE REVIEW

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
@sguada is that something you could take a look at?

**Comment by sguada** [comment]
What is the purpose of this extra argument? In theory the output_shape is computed based on the parameters to the layer.

**Comment by marcociccone** [comment]
The main reason is the following: https://github.com/tensorflow/tensorflow/issues/2118#issuecomment-214903814
Also the next comment, `if stride > 1` the output shape is ambigous.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Same coordinator timeout.

Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by sguada — CHANGES_REQUESTED** [review]
Can you add some test for the new code, showing exactly the case of stride > 1

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by marcociccone** [comment]
I will add some test asap.

**Comment by vrv** [comment]
@marcociccone any updates?  Thanks!

**Comment by vrv** [comment]
one more ping for @marcociccone !

**Comment by marcociccone** [comment]
Sorry for the delay! I'll write the test in the weekend!

Il giorno 05 mag 2017, alle ore 07:37, Vijay Vasudevan <notifications@github.com<mailto:notifications@github.com>> ha scritto:


one more ping for @marcociccone<https://github.com/marcociccone> !

**Comment by rmlarsen** [comment]
@marcociccone any progress?

**Comment by martinwicke** [comment]
I will close this PR for now. Please reopen if you have time to add a test.

**Pull request closed without merging**
