### PR TITLE
[r2.1:Cherrypick][Intel MKL] Klocwork fix

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**

### CODE REVIEW

**Comment by rthadur** [comment]
Closing this PR as this not against `master`, please open a new PR against `master`

**Comment by mahmoud-abuzaina** [comment]
@rthadur There is already one against master branch #35390, but I created this because eventually we need to cherry-pick it to r2.1.

**Comment by rthadur** [comment]
No worries this will be cherry picked , we only accept security fixes.

**Comment by mihaimaruseac** [comment]
Reopening as the 2.1 final release is not done yet, so we can get cherry-picks until then.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Actually closing for now, let's wait for #35390 to land on master. Then make a PR against r2.1 with `git cherry-pick ${hash_of_commit_on_master}`. This way we ensure that both branches are in sync w.r.t. this patch.

**Comment by mahmoud-abuzaina** [comment]
Thank you @mihaimaruseac

**Pull request closed without merging**
