### PR TITLE
Add name scope to tf.image

### LINKED ISSUE #1560: Add name scopes (op_scopes) to tf.image ops so they look nice in TensorBoard
For instance, this:

```
image = tf.image.decode_png(tf.read_file("image.png"))
whitened_image = tf.image.per_image_whitening(image)
```

produces this:
screenshot from 2016-03-19 19 33 06
instead of something like this:
screenshot from 2016-03-19 19 37 56

I know we can create the name scopes (that's how I generated the image) but it should probably be default behaviour.

### PR DESCRIPTION
**Pull request by qmick**
This PR fixes #1560 
I searched through the tf.image API list and found the following APIs need to add name scope

> crop_to_bounding_box
> pad_to_bounding_box
> flip_left_right
> random_flip_left_right
> flip_up_down
> random_flip_up_down
> per_image_standardization
> central_crop
> resize_images
> resize_image_with_crop_or_pad
> transpose_image

@martinwicke Thanks for quick reply before and could you please take a look?

- [x] Add name scope to above functions
- [x] Add test case(s)

RELNOTES: Add name scopes to tf.image functions.

### CODE REVIEW

**Comment by qmick** [comment]
For the following ops:
> crop_to_bounding_box
> pad_to_bounding_box
> central_crop
> resize_images
> resize_image_with_crop_or_pad

Because of their structure, if we want to make them like [tf.name_scope](https://www.tensorflow.org/versions/master/api_docs/python/tf/name_scope) suggests, we need to add  `tf.identity` to rename the last ops (Is there another better way?). I am not sure if it is what we want.

**Comment by martinwicke** [comment]
Sorry, I don't quite understand why you need to add an identity there -- these ops have some early exit paths, so sometimes, you will not create a new name scope at all and return the original. Is that what you meant? You are suggesting to add an identity in that case? Since in those cases, the function doesn't create graphs, I think it is sensible to not add a name scope either. I like this as is.

**Review by martinwicke — APPROVED** [review]

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Flaky test starting local grpc server.

Jenkins, test this please.

**Comment by qmick** [comment]
Yes, that is what I mean, sorry for my unclear expression. You are right, adding identity is not necessary.

**Pull request merged**
