### PR TITLE
Make unused variable warning an error during TF builds.

### PR DESCRIPTION
**Pull request by gunan**
We will need to eyeball build logs and see if this is really working as intended

### CODE REVIEW

**Comment by drpngx** [comment]
Thank you! I did some fixes during merge, so maybe I need to push first.

**Comment by caisq** [comment]
@gunan @drpngx It looks like that the change has caused many broken builds.

**Comment by drpngx** [comment]
Yes, now I have pushed from internal, let's see if there are more errors in OSS.

Jenkins, test this please.

**Comment by caisq** [comment]
ping @gunan, any progress or updates on this?

@tensorflow-jenkins test this please

**Comment by gunan** [comment]
The tests have a problem I am not sure how to tackle.
```
FAILED: Build did NOT complete successfully
bazel-out/k8-py3-opt/bin/tensorflow/python/pywrap_tensorflow_internal.cc:4634:9: error: unused variable 'i' [-Werror,-Wunused-variable]
    int i = 0;
        ^
```

`pywrap_tensorflow_internal.cc` is a file generated by swig. I do not know why it adds an unused variable, but unfortunately it does. @drpngx WDYT?

**Comment by drpngx** [comment]
Can we just set a flag for that file like `-Wno-unused-variable`?

**Comment by gunan** [comment]
I remember something like this, but we may need to set these in bzl files, or in crosstools?
I think we already had a similar situation and @mhlopko @lberki already provided us a solution.
Is there a way to globally set a compiler flag, but disable it for certain files? Note that we are still using the built-in c++ toolchain for our CPU C++ builds.

**Comment by drpngx** [comment]
It possible that the flags set at a file level are put at the end and override the global behavior?

**Comment by rmlarsen** [comment]
@gunan do you still want to merge this?

**Comment by gunan** [comment]
This will take some time to resolve, so let's close it for now. I can locally test and verify and reopen the PR>

**Pull request closed without merging**
