### PR TITLE
[TFL] Remove unnecessary Reshape before FullyConnected.

### PR DESCRIPTION
**Pull request by WindQAQ**
Remove unnecessary Reshape before FullyConnected. TFLite support N-D input of shape [batch_size, ..., channels] for FullyConnected. When keep_num_dims is false, all dimensions except the last one are collapsed into a single dimension. Therefore, it's safe to remove Reshape when it does not alter the last dimension.

The pattern is found in the official [mobilebert](https://www.tensorflow.org/lite/models/bert_qa/overview). Reshape op is not expensive but will block the folding of two consecutive FullyConnected Op (unimplemented yet).

I benchmark with simple model here, which is similar to the one found in provided tflite mobilebert model `bert/encoder/layer_0/bottleneck/attention/FakeLayerNorm/add`.

```python
model = tf.keras.Sequential([
  tf.keras.layers.Dense(128, batch_input_shape=(1, 384, 128), use_bias=True),
])
```

It contains a pattern of Reshape-FullyConnected-Reshape. This PR remove the first Reshape so it becomes FullyConnected-Reshape. The performance on Pixel3a is in the following

-----
Before
```
count=1035 first=987 curr=923 min=913 max=1070 avg=939.102 std=27
```
-----
After
```
count=1049 first=991 curr=910 min=894 max=1069 avg=923.888 std=31
```
-----

For end2end testing, I download the savedmodel from [google-research/mobilebert](https://github.com/google-research/google-research/tree/master/mobilebert) (floating point) and convert to tflite.

-----
Before
```
count=94 first=1612190 curr=1611814 min=1601869 max=1623227 avg=1.61185e+06 std=4439
```
-----
After
```
count=94 first=1601583 curr=1600427 min=1590411 max=1614870 avg=1.60146e+06 std=5378
```
-----

There is no significant performance regression or improvement as FullyConnected ops dominate the running time.

I have to reword that the Reshape that will block the folding of two consecutive FullyConnected disappears if I convert the model  manually with tf-nightly, but the pattern still happens very often in mobilebert as well as using `tf.keras.layers.Dense` with 3D or higher input. Also, I cannot really find the pattern stated in my previous response https://github.com/tensorflow/tensorflow/pull/47258#issuecomment-782819838 if I convert the model manually with tf-nightly.

Moreover, even with the simple two consecutive dense layers with 3D input, for example,

```python
model = tf.keras.Sequential([
  tf.keras.layers.Dense(2, batch_input_shape=(1, 384, 512)),
  tf.keras.layers.Dense(3)
])
```

the Reshape ops between two dense layers are optimized out.

### CODE REVIEW

**Comment by WindQAQ** [comment]
I think we can even remove reshape without the constraint of last dimension. In TFLite runtime, units (number of rows) are determined by weights instead of input

https://github.com/tensorflow/tensorflow/blob/0e6b3a307f6363a9ee9dc9e03a8a0350c7668799/tensorflow/lite/kernels/fully_connected.cc#L225-L227

Given reshape op does not modify the order of data, it should be safe enough to be removed.

Some examples in mobilebert (`bert/encoder/layer_16/attention/self/MatMul_1`)

image

**Comment by abattery** [comment]
Generally, it looks good to me. However, I wonder that the new pattern performs really better or not since the fully connected op may be sensitive with the dimension information. Could you simply verify the performance in order not to make a performance regression on it?

**Comment by WindQAQ** [comment]
I benchmark with simple model here, which is similar to the one found in provided tflite mobilebert model `bert/encoder/layer_0/bottleneck/attention/FakeLayerNorm/add`.

```python
model = tf.keras.Sequential([
  tf.keras.layers.Dense(128, batch_input_shape=(1, 384, 128), use_bias=True),
])
```

It contains a pattern of Reshape-FullyConnected-Reshape. This PR remove the first Reshape so it becomes FullyConnected-Reshape. The performance on Pixel3a is in the following

-----
Before
```
count=1029 first=958 curr=921 min=914 max=1791 avg=942.927 std=36
```
-----
After
```
count=1049 first=991 curr=910 min=894 max=1069 avg=923.888 std=31
```
-----

For end2end testing, I download the savedmodel from [google-research/mobilebert](https://github.com/google-research/google-research/tree/master/mobilebert) (floating point) and convert to tflite.

-----
Before
```
count=94 first=1612190 curr=1611814 min=1601869 max=1623227 avg=1.61185e+06 std=4439
```
-----
After
```
count=94 first=1601583 curr=1600427 min=1590411 max=1614870 avg=1.60146e+06 std=5378
```
-----

There is no performance regression or improvement as FullyConnected ops dominate the running time.

I have to reword that the Reshape that will block the folding of two consecutive FullyConnected disappears if I convert the model  manually with tf-nightly, but the pattern still happens very often in mobilebert as well as using `tf.keras.layers.Dense` with 3D or higher input. Also, I cannot really find the pattern stated in my previous response https://github.com/tensorflow/tensorflow/pull/47258#issuecomment-782819838 if I convert the model manually with tf-nightly.

Given that I cannot find a pattern that Reshape will block any fusing opportunities in nightly version and there is only limited improvement, do you think it still worth it? Thank you!

**Comment by abattery** [comment]
I can see that there is a small improvement in both simple case and mobilebert case. Thank you @WindQAQ for conducting these tests! Could you also leave these information in the PR's description?

**Review by abattery — APPROVED** [review]

**Comment by WindQAQ** [comment]
Updated the descriptions 😃 BTW, it would be great if one can update the provided mobilebert tflite model on the official example. I see that it is from tfhub, and it seems to be converted with v1 converter. It should be okay to convert it with mlir converter given that google-research also provides saved model as well. Thank you!

**Comment by abattery** [comment]
Thanks for the suggestion! To be clear, could you share the TOCO-generated mobilebert link to me? I will make a request to update the model file.

**Comment by WindQAQ** [comment]
Here is the model
- TF hub: https://tfhub.dev/tensorflow/lite-model/mobilebert/1/metadata/1
- From official website (same model with TF hub): https://www.tensorflow.org/lite/models/bert_qa/overview
- Pretrained ckpt from google-research: https://github.com/google-research/google-research/tree/master/mobilebert#pre-trained-checkpoints

**Pull request merged**
