### PR TITLE
Fix arguments in docstrings.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR fixes the mismatched argument names in docstring according to the function signatures and detail descriptions.

### CODE REVIEW

**Comment by ilblackdragon** [comment]
Jenkins, please test this!

**Comment by ilblackdragon** [comment]
@dongjoon-hyun Thanks for your commit, can you rebase master and I'll merge?

Thanks!

**Comment by vrv** [comment]
@ilblackdragon: I can merge if you'd like (no testing needed it seems)

**Comment by dongjoon-hyun** [comment]
Oh, thank you @ilblackdragon and @vrv .
And, sorry for a little bit late response. :)

**Pull request merged**
