### PR TITLE
Cherry pick updated TensorBoard binary and python3 bug

### PR DESCRIPTION
**Pull request by dsmilkov**
Pull request of commit 43b29aa1763541a2255f876ac228bdfa5310ac34 into the r0.12 branch

### CODE REVIEW

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Comment by yifeif** [comment]
Failed mac test shouldn't be related. Retest to make sure.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Comment by dsmilkov** [comment]
@yifeif any idea why the tests failed?

@tensorflow-jenkins test this please.

**Comment by yifeif** [comment]
let's try again... @tensorflow-jenkins test this please.

**Review by gunan — APPROVED** [review]

**Pull request merged**
