### PR TITLE
Add gradient for `placeholder_with_default`

### PR DESCRIPTION
**Pull request by gaohuazuo**
Patch for #6906

### CODE REVIEW

**Comment by gaohuazuo** [comment]
Gradient registered in python api only. I found no existing python test for the gradient of `identity`, so I didn't create one for `placeholder_with_default` (manual test seems ok).

I also tried to register the gradient in c api, but I'm not sure how to do it. My attempt:

```
diff --git a/tensorflow/cc/gradients/array_grad_test.cc b/tensorflow/cc/gradients/array_grad_test.cc
index 2d6fabd..c91166f 100644
--- a/tensorflow/cc/gradients/array_grad_test.cc
+++ b/tensorflow/cc/gradients/array_grad_test.cc
@@ -96,6 +96,13 @@ TEST_F(ArrayGradTest, IdentityGrad) {
   RunTest(x, shape, y, shape);
 }
 
+TEST_F(ArrayGradTest, PlaceholderWithDefaultGrad) {
+  TensorShape shape({5, 2});
+  auto x = Placeholder(scope_, DT_FLOAT, Placeholder::Shape(shape));
+  auto y = PlaceholderWithDefault(scope_, x, TensorShape());
+  RunTest(x, shape, y, shape);
+}
+
 TEST_F(ArrayGradTest, SplitGrad) {
   TensorShape x_shape({5, 2});
   auto x = Placeholder(scope_, DT_FLOAT, Placeholder::Shape(x_shape));

diff --git a/tensorflow/core/ops/array_grad.cc b/tensorflow/core/ops/array_grad.cc
index 2894e3c..844585b 100644
--- a/tensorflow/core/ops/array_grad.cc
+++ b/tensorflow/core/ops/array_grad.cc
@@ -87,6 +87,7 @@ Status IdentityGrad(const AttrSlice& attrs, FunctionDef* g) {
   return Status::OK();
 }
 REGISTER_OP_GRADIENT("Identity", IdentityGrad);
+REGISTER_OP_GRADIENT("PlaceholderWithDefault", IdentityGrad);
 
 Status PackGrad(const AttrSlice& attrs, FunctionDef* g) {
   // clang-format off
```

`//tensorflow/cc:gradients_array_grad_test` reports the following error:

```
tensorflow/cc/gradients/array_grad_test.cc:38: Failure
Value of: (ComputeGradientError(scope_, {x}, {x_shape}, {y}, {y_shape}, &max_error))
  Actual: Not found: No gradient defined for op: PlaceholderWithDefault
Expected: ::tensorflow::Status::OK()
```

**Comment by drpngx** [comment]
I think I saw a changelist fly by that fixed something like that. Could you sync without this and see if it's still required?

**Comment by gaohuazuo** [comment]
Looks like `placeholder_with_default` still doesn't have a gradient as of https://github.com/tensorflow/tensorflow/commit/a12c7dc3d83049e10c1dca8903d73cc71d3cb7b2.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by girving** [comment]
Please add a gradient test to `python/kernel_tests/constant_op_test.py`, specifically in `PlaceholderWithDefaultTest`.

**Comment by rmlarsen** [comment]
@gaohuazuo could you please add the unit test requestd by @girving?

**Comment by gaohuazuo** [comment]
It is Chinese New Year now. I can add the test next week.

**Comment by rmlarsen** [comment]
@gaohuazuo OK, sounds great.

**Comment by vrv** [comment]
@gaohuazuo happy new year!  Do you have time to add the tests?

**Comment by gaohuazuo** [comment]
I have added a simple gradient test (the last commit). Other commits all come from the tf main repo, but github seems to recognize them as part of the pr. I guess I should open another pr to replace this one?

**Comment by girving** [comment]
I think you added a commit, then merged, then added another commit.  Github then freaked out in the process.  Rebasing on top of HEAD should fix the problem, no need to make a new PR.

**Comment by vrv** [comment]
It is possible to fix this (rebase your commits to current HEAD) in this PR, but you might as well send a new PR instead, it might be easier.

**Pull request closed without merging**
