### PR TITLE
Make fast builds work with MSVC

### PR DESCRIPTION
**Pull request by tomaszstrejczek**
Allows for successful MSVC GPU enabled build with --compilation_mode fastbuild. The resulting DLL files are linked with /DEBUG:fastlink switch which is reasonably fast and generates usable .pdb files.

### CODE REVIEW

**Review by mihaimaruseac — COMMENTED** [review]
Will this still allow people to compile in debug mode if they want/need to?

**Comment by tomaszstrejczek** [comment]
Yes.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by iperov** [comment]
@tomaszstrejczek can you please tell me success configs to build in windows with MSVC ?

**Comment by iperov** [comment]
@tomaszstrejczek also I cannot build tf-master after your commit https://github.com/tensorflow/tensorflow/issues/43767

but before your commit, compiling kernels:concat_lib pass fine.

**Comment by mihaimaruseac** [comment]
You are right, @iperov Unfortunately, our post-submit CI failed to automatically revert this, so I'll do the revert now.

**Comment by tomaszstrejczek** [comment]
@iperov The command line:
`bazel build -c fastbuild  //tensorflow/tools/pip_package:build_pip_package`
.tf_configure.bazelrc:
`build --action_env PYTHON_BIN_PATH="C:/work/tensorflow/venv/Scripts/python.exe"
build --action_env PYTHON_LIB_PATH="C:/work/tensorflow/venv/lib/site-packages"
build --python_path="C:/work/tensorflow/venv/Scripts/python.exe"
build --config=xla
build --action_env TF_CUDA_VERSION="10.1"
build --action_env TF_CUDNN_VERSION="7"
build --action_env TF_CUDA_PATHS="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1"
build --action_env CUDA_TOOLKIT_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="7.5"
build --config=cuda
build:opt --copt=/arch:AVX --copt=/FS
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"
build --define=override_eigen_strong_inline=true`

**Comment by tomaszstrejczek** [comment]
@iperov Both
` bazel build -c fastbuild  //tensorflow/core/kernels:concat_lib`
and
`bazel build -c opt  //tensorflow/core/kernels:concat_lib`
build for me.
Could you provide me with your .tf_configure.bazelrc, command line and the version of Visual C++ so I could try to reproduce your problem?

**Comment by mihaimaruseac** [comment]
After reverting this internally, all of our Windows builds started passing again.

**Pull request merged**
