### PR TITLE
Add back "PR #49173: [Crash fix] Fix cudaMallocAsync crashes."

### LINKED ISSUE #50669: Internal Error with TF_GPU_ALLOCATOR=cuda_malloc_async
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Pop-OS 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.9.5
- CUDA/cuDNN version: CUDA 11.4 / cuDNN 8.2.2
- GPU model and memory: RTX 3080

**Describe the current behavior**
When using the TF_GPU_ALLOCATOR=cuda_malloc_async, TF throws an internal error after allocation of GPU: 
```
2021-07-08` 12:44:26.553800: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-08 12:44:27.009583: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-08 12:44:27.034925: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-08 12:44:27.035193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:2d:00.0 name: NVIDIA GeForce RTX 3080 computeCapability: 8.6
coreClock: 1.71GHz coreCount: 68 deviceMemorySize: 9.76GiB deviceMemoryBandwidth: 707.88GiB/s
2021-07-08 12:44:27.035207: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-08 12:44:27.036831: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-08 12:44:27.036855: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-07-08 12:44:27.037745: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-07-08 12:44:27.037863: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-07-08 12:44:27.038095: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-07-08 12:44:27.038451: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-07-08 12:44:27.038515: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-07-08 12:44:27.038573: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-08 12:44:27.038841: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-08 12:44:27.039405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-08 12:44:27.039873: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-08 12:44:27.040284: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-08 12:44:27.040520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:2d:00.0 name: NVIDIA GeForce RTX 3080 computeCapability: 8.6
coreClock: 1.71GHz coreCount: 68 deviceMemorySize: 9.76GiB deviceMemoryBandwidth: 707.88GiB/s
2021-07-08 12:44:27.040556: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-08 12:44:27.040800: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-08 12:44:27.041145: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-08 12:44:27.041164: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-08 12:44:27.296173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-08 12:44:27.296199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-07-08 12:44:27.296206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-07-08 12:44:27.296339: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-08 12:44:27.296598: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-08 12:44:27.296835: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-08 12:44:27.297045: I tensorflow/core/common_runtime/gpu/gpu_process_state.cc:210] Using CUDA malloc Async allocator for GPU.
2021-07-08 12:44:27.297081: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
Traceback (most recent call last):
  File "/home/sebltm/OneDrive/KCL/Individual_Project/FaceCapsNet/./training.py", line 424, in <module>
    log_writer = tf.summary.create_file_writer(logdir) if log else None
  File "/home/sebltm/OneDrive/KCL/Individual_Project/FaceCapsNet/facecapsnet/lib/python3.9/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 479, in create_file_writer_v2
    with ops.name_scope(name, "create_file_writer") as scope, ops.device("cpu:0"):
  File "/home/sebltm/OneDrive/KCL/Individual_Project/FaceCapsNet/facecapsnet/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 5255, in device
    return context.device(device_name_or_function)
  File "/home/sebltm/OneDrive/KCL/Individual_Project/FaceCapsNet/facecapsnet/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 2072, in device
    ensure_initialized()
  File "/home/sebltm/OneDrive/KCL/Individual_Project/FaceCapsNet/facecapsnet/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 1867, in ensure_initialized
    context().ensure_initialized()
  File "/home/sebltm/OneDrive/KCL/Individual_Project/FaceCapsNet/facecapsnet/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 525, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: No allocator statistics
```

### PR DESCRIPTION
**Pull request by nouiz**
This reverts commit a4553f8ad74f5ad486057da400fb8e101f12e09f that was reverting #49173.

When I run it now, //tensorflow/core/common_runtime/gpu:gpu_device_test in asan give me the same output as before. It was already crashing before this PR with my command line:

```bazel test --distinct_host_configuration=false --javabase=@bazel_tools//tools/jdk:remote_jdk11 --config=asan -c opt --config=cuda //tensorflow/core/common_runtime/gpu:gpu_device_test```

@penpornk 

fixes #50669

### CODE REVIEW

**Comment by nouiz** [comment]
I just pushed a fix that fix a test error in NDEBUG mode.

**Comment by penpornk** [comment]
@nouiz Thank you so much for taking care of this. And sorry again about the revert. :(
The PR looks good to me. I applied your additional changes and it seems the `cuda_asan` test is still failing internally and might need further fixing, so I'm reassigning this PR to @cheshire. (I don't usually work on GPU PRs unless it's related to sparse kernels.)

**Comment by nouiz** [comment]
Any update on this? It is 3 mount since I started to get this fix in the first time.

**Review by cheshire — APPROVED** [review]

**Comment by nouiz** [comment]
@cheshire Note, the problem is the internal `cuda_asan` test fail. I do not have any information about it. So I can't fix it. I'm also not able to reproduce it.

**Comment by akuegel** [comment]
> @cheshire Note, the problem is the internal `cuda_asan` test fail. I do not have any information about it. So I can't fix it. I'm also not able to reproduce it.

The error is actually another one:
F0817 14:52:42.569874    7691 gpu_cudamallocasync_allocator.cc:133] Failed to get device attribute: CUDA error: invalid argument (CUDA_ERROR_INVALID_VALUE)

This happens without cuda_asan. I guess that in the meantime, the surrounding code has changed, and you will have to adapt your change to that.
I couldn't reproduce the cuda_asan error, so I guess that is fixed now.

**Comment by nouiz** [comment]
I tried the commit in this PR and the gpu_device_test passed. I rebased it and pushed the rebased version and it still pass. The Github Linux CI passed too. So I'm not able to reproduce any error here.

What idea what would be different in your system that would make it fail?

**Review by akuegel — APPROVED** [review]

**Comment by akuegel** [comment]
> I tried the commit in this PR and the gpu_device_test passed. I rebased it and pushed the rebased version and it still pass. The Github Linux CI passed too. So I'm not able to reproduce any error here.
> 
> What idea what would be different in your system that would make it fail?

Internally we are running with cuda 11.3, in open source it is cuda 11.2 (as far as I can see). Otherwise I think there is no difference. The line I quoted as failing is triggered in the test that you are adding in this PR. It did not fail at the time when your PR was first merged, but I think at that time we were not using cuda 11.3 yet. So this could indeed be the reason.

**Comment by nouiz** [comment]
I tried with our CUDA 11.2 and 11.3 container and the test pass.
Hopefully it was an not-related error that won't happen with the new approval.

**Comment by akuegel** [comment]
> I tried with our CUDA 11.2 and 11.3 container and the test pass.
> Hopefully it was an not-related error that won't happen with the new approval.

It did happen with the new approval, same error, and only when executing your newly added test. Unfortunately it looks definitely related. I believe this error would have been triggered before in the first merge as well had we been running with a cuda version >= 11.2, but first time essentially your new code was disabled and therefore couldn't trigger this error. I don't know of any other difference (except the newer cuda version). Can you make sense of the cuda error that is returned? This is line 133 of gpu_cudamallocasync_allocator.cc. In which cases would such an error be returned? Maybe we can narrow it down through that.

@cheshire any idea what else could be different why it fails internally and not externally?

**Comment by nouiz** [comment]
@akuegel Can you check in the log if there is any mention that the GPU is enabled and working in that job?

I updated this PR with extra information in that error message. Mostly, the error is that some argument to the function aren't valid. So I print them. The only argument that I think could fail is the device id. Can you run the test with that extra error message?

**Review by akuegel — APPROVED** [review]

**Comment by akuegel** [comment]
> @akuegel Can you check in the log if there is any mention that the GPU is enabled and working in that job?
> 
> I updated this PR with extra information in that error message. Mostly, the error is that some argument to the function aren't valid. So I print them. The only argument that I think could fail is the device id. Can you run the test with that extra error message?

With this additional debug statement, I can see: "On device: 0". Failed to get device attribute : CUDA error: invalid argument (CUDA_ERROR_INVALID_VALUE)
Is it possible that a certain minimum driver version is needed to run this test successfully?

@Artem-B Do you know which driver version are we currently running internally?

**Comment by Artem-B** [comment]
> @Artem-B Do you know which driver version are we currently running internally?

We're using [cuda_compat](https://docs.nvidia.com/deploy/cuda-compatibility/) 470.57.02 on top of the drivers 450.80.02.

**Comment by nouiz** [comment]
cudaMallocAsync only care about the USER driver. So 470.* should be good.

But I added explicit test that the driver is recent enough. So if there is a strange problem and that this test run with an older USER driver, the error will be explicit.
Can you trigger the test again?

**Review by akuegel — APPROVED** [review]

**Comment by nouiz** [comment]
@akuegel Did the internal test fail? If so, what is the new error message?

**Review by akuegel — APPROVED** [review]
Thanks, I think that should unblock the change :)

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
