### PR TITLE
Delete Dockerfile.devel-gpu-cuda9-cudnn7

### PR DESCRIPTION
**Pull request by gunan**
our default dockerfiles now use cuda9-cudnn7.
No need for this file anymore.

CC @flx42

### CODE REVIEW

**Comment by flx42** [comment]
Great!
Quick question: to build a new CUDA 9.0+cuDNN v7 container image with the new Dockerfiles, what magic value of `TF_DOCKER_BUILD_CENTRAL_PIP` do I need to pass to `parameterized_docker_build.sh`?

**Comment by gunan** [comment]
Right now, there is not a correct value for that.
However, by tomorrow morning we should have our nightlies built, and ready to use.
We should be able to pass our nightly pip package URLs to the script.

As a note, I have a bug open, and the first chance I get I will rewrite all our dockerfiles and get rid of parameterized_docker_build script.

**Review by caisq — APPROVED** [review]

**Comment by flx42** [comment]
thanks @gunan, I'm not seeing the new pip packages at https://pypi.python.org/pypi/tf-nightly-gpu yet.

Also, looks like there hasn't been any nightly GPU docker image for a while:
https://hub.docker.com/r/tensorflow/tensorflow/tags/

Is your CI system currently **on fire**? :) Let me know if I can help.

**Comment by gunan** [comment]
We are also working on the 1.4.1 release, so the CI was backed up last night. I will see what I can do to push these out today.

**Pull request merged**
