### PR TITLE
Enhanced Operator overriding Eager testcase

### PR DESCRIPTION
**Pull request by joyalbin**
Modified the testcase to verify operator overriding
with negative inputs.

### CODE REVIEW

**Review by alextp — DISMISSED** [review]
Thanks!

**Comment by joyalbin** [comment]
I could see the "Ubuntu Sanity"  test on CI  is failed with below error. Could somebody please help me on this error ?
I am not able to relate this error with the code change.

```
ERROR: error loading package 'tensorflow/lite/experimental/swift': Extension file not found. Unable to load file '@bazel_skylib//lib:partial.bzl': file doesn't exist or isn't a file
INFO: Elapsed time: 5.578s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (92 packages loaded)
FAILED: Build did NOT complete successfully (92 packages loaded)
FAIL: bazel build --nobuild  -- //tensorflow/... -//tensorflow/lite/java/demo/app/... -//tensorflow/lite/examples/android/... -//tensorflow/lite/schema/...
  This is due to invalid BUILD files. See lines above for details.
```

**Comment by joyalbin** [comment]
Could you please consider to merge this PR?

**Comment by rthadur** [comment]
> Could you please consider to merge this PR?

There is an error while merging , can you please correct naming of 

> "_testOperations(v1, v2):"

 in to snake_case.

**Comment by joyalbin** [comment]
@rthadur modified the function name as per the review comment, could you please have a look?

**Review by alextp — DISMISSED** [review]

**Comment by rthadur** [comment]
@joyalbin thank you , can you please check failed build errors.

**Review by alextp — APPROVED** [review]

**Pull request merged**
