### PR TITLE
Support GIF image decode ops by FreeImage library

### PR DESCRIPTION
**Pull request by buaaliyi**
Use FreeImage library to decode GIF images. This is the initial commit with simple implementation first, will add more features and optimize later. Thanks.

### CODE REVIEW

**Comment by buaaliyi** [comment]
@tensorflow-jenkins test this please.

**Comment by martinwicke** [comment]
We're not comfortable with the FreeImage dependency. Is there a gif reader library we can use instead?

**Comment by buaaliyi** [comment]
@martinwicke  
For pure gif decoder C++ library, there are:

giflib  http://giflib.sourceforge.net/
libnsgif  http://www.netsurf-browser.org/projects/libnsgif/

to be selected from.

**Comment by martinwicke** [comment]
giflib it is. Can you use that instead? Thanks!

**Comment by buaaliyi** [comment]
OK, I'll use giflib to refactor this code, and submit another PR after future several days. Decoding gif image files is really important in my tensorflow use case.

At the same time, thank you for your advise.

**Comment by martinwicke** [comment]
Closing this in favor of #3020.

**Pull request closed without merging**
