### PR TITLE
Make get_placeholders() accessible and add example

### PR DESCRIPTION
**Pull request by qmick**
This is an improvement of PR #14541.
This PR makes get_placeholders() visible in the document as `tf.contrib.framework.get_placeholders` and add example to the docstring.

- [x] Make get_placeholders() accessible
- [x] Add example

### CODE REVIEW

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Review by drpngx — DISMISSED** [review]
Can we add a test for that?

**Comment by qmick** [comment]
Tests for python package import and placeholder's name added.

**Comment by drpngx** [comment]
Oh, I didn't realize there was already a test, sorry. You can undo that commit.

**Review by ispirmustafa — APPROVED** [review]
Thank you

**Pull request merged**
