### PR TITLE
Added support for `TensorStridedSliceUpdate`

### PR DESCRIPTION
**Pull request by eaplatanios**
This adds support for using the `StridedSliceAssign` op on tensors, similar to `TensorScatterUpdate`. To remain consistent, the new op is named `TensorStridedSliceUpdate`. We need this to add support for efficient tensor strided slice setters in Swift for TensorFlow. The relevant PR and comments can be found [here](https://github.com/apple/swift/pull/23684).

@alextp does this look ok? I cannot currently compile and test on my machine, but I hope I'll be able to do so tomorrow.

### CODE REVIEW

**Review by alextp — CHANGES_REQUESTED** [review]
You'll also need to add an apidef file for this op (search in tf/core/api/ for StridedSlice and copy what's there) or it'll end up in TF's public python API.

If you do want it in the public python API, though, you'll need to run tf/tools/api/tests/api_compatibility_test --update_goldens=True to regenerate the golden files to make all tests pass

**Comment by eaplatanios** [comment]
Thanks Alex! I made some fixes and added support for the op in the public python API (through the strided slice assignment operator).

**Review by alextp — DISMISSED** [review]

**Comment by eaplatanios** [comment]
@alextp there was a typo and a test that does not apply anymore that should be fixed now.

**Review by alextp — DISMISSED** [review]

**Comment by karmel** [comment]
(for tf-api-owners) This should not be visible in the Python API except as a raw_op. Can you remove the exposure via Python and re-run the API compatibility test to regenerate the goldens?

**Comment by eaplatanios** [comment]
@karmel Do I need to do something about this or is it just the tf-api-owners?

**Comment by alextp** [comment]
@eaplatanios I think you need to rerun the api_compatibility_test with --update_goldens=True

**Comment by eaplatanios** [comment]
@alextp @karmel I rerun the API compatibility test and committed the updated files.

**Comment by eaplatanios** [comment]
Can we run the tests again to verify there are no remaining issues?

**Comment by alextp** [comment]
```
=== Sanity check step 4 of 13: do_buildifier (buildifier check) ===
Running do_buildifier on 440 files
tensorflow/core/kernels/BUILD # listsort unsafesort sort:tf_kernel_library.deps
buildifier took 0 s
FAIL: buildifier found errors and/or warnings in above BUILD files.
buildifier suggested the following changes:
151a152
>         ":inplace_ops",
154d154
<         ":inplace_ops",
Please fix manually or run buildifier <file> to auto-fix.

```

**Comment by eaplatanios** [comment]
@alextp If this was due to the alphabetical ordering, it should have been fixed now. :)

**Review by alextp — APPROVED** [review]

**Comment by eaplatanios** [comment]
All tests seem to pass now. Not sure what's wrong with the "android" and the "feedback" checks.

**Comment by eaplatanios** [comment]
@alextp Is this ready to be merged now or should I do something further for the failing checks?

**Comment by alextp** [comment]
@eaplatanios it should be good to go, I'll retry internally

**Comment by eaplatanios** [comment]
@alextp Sounds good, thanks! :)

**Review by alextp — APPROVED** [review]

**Comment by eaplatanios** [comment]
This should be ready to merge now I guess.

**Comment by eaplatanios** [comment]
When is this expected to be merged? I'm asking because it's currently blocking some features I'm working on for Swift for TensorFlow.

**Comment by rthadur** [comment]
> When is this expected to be merged? I'm asking because it's currently blocking some features I'm working on for Swift for TensorFlow.

Thanks for your contribution, this should be merged on Monday.

**Comment by eaplatanios** [comment]
Thanks @rthadur! :)

**Pull request merged**
