### PR TITLE
[oneDNN] UT failure fix: //tensorflow/python/kernel_tests/nn_ops:pooling_ops_3d_test_cpu

### PR DESCRIPTION
**Pull request by ashiqimranintel**
With oneDNN enabled //tensorflow/python/kernel_tests/nn_ops:pooling_ops_3d_test_cpu got triggered, a sanity check of empty tensor on avgpool3d_grad is needed. This PR will resolve //tensorflow/python/kernel_tests/nn_ops:pooling_ops_3d_test_cpu test failure

### CODE REVIEW

**Comment by ashiqimranintel** [comment]
This PR will resolve this issue. https://github.com/tensorflow/tensorflow/issues/58446

**Review by cantonios — APPROVED** [review]
Thanks!

**Review by penpornk — CHANGES_REQUESTED** [review]
Thank you for the fix! Could you please help re-enable the test (by removing the skip-test here) in this PR?
https://github.com/tensorflow/tensorflow/blob/f31ff09c9c47bcd25c934773faac6dd1cbc3229e/tensorflow/tools/ci_build/build_scripts/ARM_SKIP_TESTS.sh#L23

This way the Arm CI will actually run the failed test.

**Comment by ashiqimranintel** [comment]
@penpornk, I have modified the requested change.

**Comment by ashiqimranintel** [comment]
@penpornk , do you have any update on this PR?

**Review by cantonios — APPROVED** [review]

**Comment by ashiqimranintel** [comment]
@cantonios , it's been pending for some time, any update on merging this PR?

**Pull request merged**
