### PR TITLE
 [ROCm] Update to use ROCm 4.1 (when building TF with --config=rocm) 

### PR DESCRIPTION
**Pull request by deven-amd**
/cc @cheshire @chsigg @sanjoy

### CODE REVIEW

**Comment by deven-amd** [comment]
@cheshire @chsigg @sanjoy gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg @sanjoy gentle ping

**Review by cheshire — APPROVED** [review]

**Comment by deven-amd** [comment]
@gbaned this PR seems to have failed the internal review/check....anything I can do to move this PR forward?

thanks

**Comment by akuegel** [comment]
> @gbaned this PR seems to have failed the internal review/check....anything I can do to move this PR forward?
> 
> thanks

I did the fixes, it is merged now.

**Comment by deven-amd** [comment]
Thank you @akuegel , really appreciate your help.

**Pull request merged**
