### PR TITLE
Branch 142576906

### PR DESCRIPTION
**Pull request by jhseu**

### CODE REVIEW

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
@mrry fyi, I had to move saved_model deps from `tf_cc_ops.cmake` to `tf_core_cpu.cmake` to fix the windows cmake build. I added saved_model support to the C API in this set of changes, and it's closer to core anyway despite being under `cc/`.

**Comment by yaroslavvb** [comment]
Maybe `tf.norm` should use `tf.norm(m, ord='fro')` instead of `tf.norm(m, order='fro')` for consistency with numpy? @martinwicke

**Comment by jhseu** [comment]
@aselle See the `tf.norm` comment above ^

**Comment by aselle** [comment]
I am ok with order instead of ord, because frankly, numpy's name there is worse. Incompatibility with keyword arguments is less pressing, since those basically will not cause as much confusion as positional argument mismatches (we do match them in some cases, like our change on axis).

**Comment by jhseu** [comment]
@yaroslavvb fyi, it's being renamed to `ord` and should show up during the next sync.

**Pull request merged**
