### PR TITLE
[INTEL MKL]  RequantizeOp to support int8 data type

### PR DESCRIPTION
**Pull request by gzmkl**
Add registration for RequantizeOp for to support "int8" date type.

Currently RequantizeOp only supports "qint8". MklQuantizedConvOp etc ops already support both.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for your PR and I'm so sorry for my delay!

**Comment by gzmkl** [comment]
Penpornk, 
Thank you so much for the review. 
GZ

**Comment by penpornk** [comment]
@rthadur Gentle ping for pulling. Thank you!

**Comment by gzmkl** [comment]
Penporn: thank you very much!   -GZ

**Pull request merged**
