### PR TITLE
add compatibility check badges to README

### PR DESCRIPTION
**Pull request by ylil93**
Hello google package maintainer,
The badges being added to the README in this PR will indicate your compatibility with other google packages. This addresses a set of user bugs which have happened when a user depends on two Cloud libraries (or runtimes that bundle libraries), say A and B, which both depend on library C. If the two libraries require different versions of C, the users can run into issues both when they pip install the libraries, and when they deploy their code. Our compatibility server checks that all libraries we make including this one are self and pairwise compatible as well as not having any deprecated dependencies. The two badges will mark the build for your project green when the latest version available on PyPI and github HEAD respectively meet all compatibility checks with itself and all other libraries. The badge target will link to a details page that elaborates on the current status. This should help you fix issues pre-release, to avoid user surprises. For more information, please take a look at our project charter at go/python-cloud-dependencies-project-charter and the badging PRD https://docs.google.com/document/d/1GYRFrfUou2ssY71AtnLkc8Sg1SD4dxqN4GzlatGHHyI/edit?ts=5c6f031d

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@ylil93  Can you please resolve conflicts? Thanks!

**Comment by gunan** [comment]
I do not think this is the right place to add that badge. I would recommend having this near the documentation badges at the top.

@ewilderj are we aware of this? Do you think we should add this badge?

**Comment by gbaned** [comment]
@ewilderj Any update on this PR, please. Thanks!

**Comment by gbaned** [comment]
@ylil93 Can you please resolve conflicts? Thanks!

**Review by ewilderj — COMMENTED** [review]
Sorry for the delay on this. Putting these badges without any context could lead to user confusion. I think they might be better placed elsewhere in the README where they can have accompanying explanatory text. Right now to the casual observer they look a little alarming.

@lamberta wdyt?

**Comment by lamberta** [comment]
I would worry about about the badge proliferation after these.

> This should help you fix issues pre-release, to avoid user surprises.

Is the expectation that the TF team will use these badges as a tool before cutting a release?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gunan** [comment]
Looks like we do now wish to add this badge. Closing the PR.

**Pull request closed without merging**
