### PR TITLE
Upgrading the AWS SDK version

### PR DESCRIPTION
**Pull request by rahul003**
Also added some dependencies that the newer version requires

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by rahul003** [comment]
This PR builds fine locally, but fails to find dependencies in CI. Is there something I need to do to get it working?

**Comment by rahul003** [comment]
Actually @MihailSalnikov , I just requested review again, but please hold on before review. I'll comment when done.

Going to go through my bazel definitions once again. As although it builds fine on my local machine, it seems to fail on CI.

**Comment by rahul003** [comment]
@mihaimaruseac I just wanted to say thanks a lot for your help with my multiple PRs. 
I think I've resolved the build issue here. Could you help give CI another shot at this PR?

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by gbaned** [comment]
@rahul003 Can you please address Ubuntu Sanity errors? Thanks!

**Comment by rahul003** [comment]
@gbaned Just pushed a commit to fix the license check issue. Please restart build

**Review by mihaimaruseac — APPROVED** [review]

**Comment by rahul003** [comment]
The build failure doesn't seem related to my changes. Am I missing something

```
ERROR: T:/tmp/bigvaudl/external/llvm-project/llvm/BUILD:3716:1: C++ compilation of rule '@llvm-project//llvm:support' failed (Exit 2)
external/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp(218): error C2712: Cannot use __try in functions that require object unwinding
```

**Comment by mihaimaruseac** [comment]
> The build failure doesn't seem related to my changes. Am I missing something
> 
> ```
> ERROR: T:/tmp/bigvaudl/external/llvm-project/llvm/BUILD:3716:1: C++ compilation of rule '@llvm-project//llvm:support' failed (Exit 2)
> external/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp(218): error C2712: Cannot use __try in functions that require object unwinding
> ```

We're broken by a LLVM integration as part of MLIR. It will have to wait until build turns back green (hopefully tomorrow)

**Comment by rahul003** [comment]
Can we retry now if the build has passed?

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
