### PR TITLE
Adding Python 3 support to Tensorboard

### PR DESCRIPTION
**Pull request by jfsantos**
This PR implements Python 3 support into Tensorboard in a portable way, by importing packages from six when possible and converting strings into the correct encoding whenever necessary.

### CODE REVIEW

**Comment by vrv** [comment]
1) have you verified that this works on python2, or just python3?
2) If it works for both, can you squash the commits?

**Comment by jfsantos** [comment]
I tested it on Python 2.7 (on Linux only) and it works. I could not generate a wheel to test it on OS X due to an unrelated compilation error.

**Comment by jfsantos** [comment]
Commits are squashed now, thanks!

**Comment by martinwicke** [comment]
Assigning to @danmane for final checking. Thanks!

**Comment by jfsantos** [comment]
Sorry, by mistake I submitted the PR from my master instead of a branch and ended up adding other stuff on top of it. I'll rollback now.

**Comment by vrv** [comment]
@girving: want to take a quick look?  Seems fine to merge but just want your extra eye.

**Comment by girving** [comment]
Looks good, except for a couple of places where `compat.as_bytes` could be used.  I added two comments to that effect.

**Comment by jfsantos** [comment]
@girving I amended the commit and used `compat.as_bytes` instead of `.encode('utf-8')`.

**Comment by girving** [comment]
Looks good, assuming that's the right way to import `compat`.  @vrv: Did the tests automatically rerun when the PR was changed?

**Comment by vrv** [comment]
Nope, you have to invoke it.  Like so:

@tensorflow-jenkins: test this please.

**Comment by vrv** [comment]
Merged

**Comment by girishramnani** [comment]
there isnt a 6.1 or 6.0.1 release version of tensorflow with this feature.

**Comment by jfsantos** [comment]
No, but backporting it is straightforward. You basically have to make the
same edits in the same functions. I did that in my local `tensorboard.py`
and `tensorboard_handler.py`, and I could share them if there's any
interest.

**Comment by girishramnani** [comment]
Yeah , i also finally ended up using the 2to3 with some encodes at places and it was working.

**Pull request closed without merging**
