### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mortenjust**
Add instructions on where to run the inception download commands

### CODE REVIEW

**Comment by mortenjust** [comment]
I signed it!

**Comment by gunan** [comment]
Looks like there is still a problem with the CLA.
Could you verify your email you used to sign the CLA is the same one as the email that is in your commit?

**Review by arnwas — APPROVED** [review]

**Comment by gunan** [comment]
@mortenjust the CLA still seems to be an issue.
Could you make sure your commit email and the email you used to sign the CLA are the same?

**Comment by mortenjust** [comment]
hey @gunan - thanks, should be good now. Thought it was enough to add my other CTA-signed emails to github. Anyway, signed the @genstart.dk email just now.

**Pull request merged**
