### PR TITLE
Fix tf.keras.dataset.mnist/reuters np v1.16.3

### PR DESCRIPTION
**Pull request by yongtang**
This fix add `allow_pickle=True` to fix the numpy issue in 1.16.3.

See keras-team/keras@3423197
and keras-team/keras#12714

for related changes in keras-team/keras.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by gbaned** [comment]
@yongtang Could you please resolve the conflicts? Thanks!

**Comment by yongtang** [comment]
@gbaned Thanks, the PR has been updated.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Review by pavithrasv — APPROVED** [review]
Thank you for the PR!

**Pull request merged**
