### PR TITLE
[CMake] Remove invalid python modules

### PR DESCRIPTION
**Pull request by Androbin**
Split from #15368
@mrry Friendly ping.

### CODE REVIEW

**Comment by Androbin** [comment]
@drpngx Friendly ping.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by Androbin** [comment]
The last CI build failed due to newly included `tensorflow/contrib/lite/python` importing `tensorflow/contrib/lite/toco/python`. @drpngx Please re-run the tests.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by mrry — APPROVED** [review]

**Comment by Androbin** [comment]
How is this import supposed to be resolved?
`ImportError: No module named 'tensorflow.contrib.lite.toco.python.tensorflow_wrap_toco'`

**Comment by drpngx** [comment]
You need a dependency to `//tensorflow/contrib/lite/toco/python:tensorflow_wrap_toco`. I suggest not adding them just yet, and adding them in a separate PR.

**Comment by drpngx** [comment]
(The `_wrap` library, as its name implies, is a SWIG wrapped library. It links against protobuf, which gets statically linked, so adding it is probably unsafe to add it.)

**Comment by Androbin** [comment]
Aren't these two lines supposed to include `python:tensorflow_wrap_toco`?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/BUILD#L60
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/python/BUILD#L18

**Comment by drpngx** [comment]
Yes, but loading that library runtime is inherently unsafe, particularly on MacOS. I'd do that in another PR.

**Comment by Androbin** [comment]
Do you want to merge these two lines now or in another PR?
```
tensorflow/contrib/lite/python
tensorflow/contrib/lite/toco/python
```

**Comment by Androbin** [comment]
Okay, I have commented them out and left a TODO.

**Comment by drpngx** [comment]
Jenkins, test this please.

Thanks!

**Comment by drpngx** [comment]
The dreaded `ERROR: Error fetching remote repo 'origin'` again.

Jenkins, test this please.

**Pull request merged**
