### PR TITLE
[LITE]Changed notebooks kernel to python3

### PR DESCRIPTION
**Pull request by siju-samuel**
All other in lite folder is python3 based kernel

### CODE REVIEW

**Comment by gbaned** [comment]
@siju-samuel Could you please resolve the conflicts? Thanks!

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
