### PR TITLE
Make orthogonal initializer use qr factorization (instead of svd)

### PR DESCRIPTION
**Pull request by GBLin5566**
Use QR factorization in orthogonal initializer to get better efficiency when computing orthogonal matrix.

### CODE REVIEW

**Comment by yaroslavvb** [comment]
BTW, that doesn't give uniform distribution over orthogonal matrices. Search for "wrong distribution" in https://arxiv.org/pdf/math-ph/0609050.pdf

To do uniformly at random, need to divide by diagonal entries of the qr term. IE, something like this in numpy
```
from scipy import linalg
import numpy as np
def orthogonal_measure(n):
    z = np.random.randn(n,n)
    q, r = linalg.qr(z)
    d = np.diagonal(r)
    ph = d/np.absolute(d)
    return q*ph

```

before normalization
screenshot 2017-04-25 13 09 13

after normalization
screenshot 2017-04-25 13 09 27

[Notebook with sanity checks](https://wolfr.am/lbWEtaFF)

**Comment by GBLin5566** [comment]
@yaroslavvb thanks for pointing it out !
Gonna fix it soon.

**Comment by keveman** [comment]
Not super familiar with this code. Lobbing over to @rmlarsen

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
Thanks for the change!

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by martinwicke** [comment]
There is an issue with the tests in a ominous location -- @GBLin5566 can you look into this?

**Comment by GBLin5566** [comment]
I checked the error message and found that it was caused due to the mean of Q was bigger than 0. over the threshold. (In this case, mean of Q is  0.04, bigger than +- 0.03).
However, if I change the shape of array or change the seed (123 to 124 for example), the test will be fine.
So I guess the error is from minor instability and it's permissible ?

**Comment by martinwicke** [comment]
It is probably ok, but it does cast some doubt on the quality of this test. Increasing the threshold (or changing the seed) are acceptable, assuming we have made extra certain that our new scheme does not introduce some bias.

**Comment by martinwicke** [comment]
Oops.

**Comment by GBLin5566** [comment]
@martinwicke Thanks for the feedback !

**Pull request merged**
