### PR TITLE
Reuse add_loss function and removed skflow folder

### PR DESCRIPTION
**Pull request by terrytangyuan**
I don't think people are still importing from skflow, instead of importing from learn. 

BTW, @martinwicke @ilblackdragon Are you in the process of removing `learn.ops` to avoid the duplication? What's the best way to handle (`is_training` in `contrib.layers`) and (`IS_TRAINING` in `learn.ops.dropout_ops` and `learn.ops.batch_norm_ops`)?

### CODE REVIEW

**Comment by ilblackdragon** [comment]
May be separate PRs for remove vs adding losses? feel a bit ... dirty ... to have it one :)

**Comment by ilblackdragon** [comment]
About is_training - if you look at layers.batch_norm or dropout they take is_training bool or tensor. so it should be straightforward to convert.

**Comment by ilblackdragon** [comment]
We don't have anything in flight for removal just yet - so if you want to start, feel free.

**Comment by terrytangyuan** [comment]
@ilblackdragon Sorry for this combined PR ;-) Will do next time. Sure, I'll take a look when I get another chance. It's good for me to get some exposure to modules other than tf.learn.

**Comment by terrytangyuan** [comment]
@ilblackdragon Green!

**Pull request merged**
