### PR TITLE
Exploring a baseline Action build

### PR DESCRIPTION
**Pull request by bhack**
With this I want to explore a new testing baseline with Github Action and our official CPU `tensorflow/tensorflow:devel` image.

The idea is to test in the CI the (more or less) Episodic contributor journey to contribute code to Tensorflow at least on CPU.

This is the proposed list of steps:

*  `tensorflow/tensorflow:devel` image rebuid build (or Dockerhub pull?)
* Code checkout
* `ci_sanity.sh` selected steps (--pylint, --<whatever you want> see https://github.com/tensorflow/tensorflow/pull/48294)
* TF bazel `./configure`
* `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`
* `bazel test //tensorflow/`

As the average user it is already experiencing, this will probably require a bazel cache (on [GCS like for TF/IO](https://github.com/tensorflow/io/pull/1294)?) to achieve reasonable compilation times.

I think that reproducibility and the timing of these build steps will let us to monitor the experience of a Tensorflow episodic contribution.

/cc @angerson @mihaimaruseac  @theadactyl @joanafilipa

### CODE REVIEW

**Comment by bhack** [comment]
As expected we had an Github Action timeout on the TensorFlow build step after `5h 56m 42s` with only `11,286` compiled target on an estimate of `33563 targets configured`.

Github Actions are currently running on a [Standard_DS2_v2](https://docs.microsoft.com/it-it/azure/virtual-machines/dv2-dsv2-series#dsv2-series) machine. 

As we  already know this is really a bottleneck for an average TF external (Episodic or not) contributor as we ask to reproduce these steps on its own local machine just for preparing an occasional code PR.

I think that it is important to continuously monitor this Action over time to expect that we could execute it in the expected time that seems to us reasonable for an Episodic/Average TF contributor.

Some proposed solutions to enable this action in order of preference:

- Use a Google hosted [Action runner](https://docs.github.com/en/actions/hosting-your-own-runners) and produce a GCS cache that could be re-used by the action itself and (read-only) by every contributor on his own local-machine when he is working with the official `tensorflow/tensorflow:devel`. A sort of an improvement over https://github.com/tensorflow/tensorflow/pull/48294
- Still use Github hosted Action consuming an usable GCS cache produced elsewhere (Where?)
- Let use a bazel python only build and test commands in this Action using all the c/c++ component from a system `pip install ft-nightly`. **This is risky** cause as we build nightly once a day we could have misalignment against current master c/c++ features.

**Comment by bhack** [comment]
Just in the case we want to explore the first option with the self hosted `Github Action runner` on GKE:
https://github.com/summerwind/actions-runner-controller
https://github.com/evryfs/github-actions-runner-operator/

**Comment by bhack** [comment]
There is also a Terraform Github Self Hosted Runners on GKE repo maintained by Google Cloud members (/cc @bharathkkb) at https://github.com/terraform-google-modules/terraform-google-github-actions-runners

**Comment by bhack** [comment]
Update: We discussed a pilot plan with @perfinion yesterday on SIG-Build Gitter.

**Comment by vnvo2409** [comment]
I would add one more difficulty: Even with local cache, it seems to be invalidated each time I pull the commits from upstream. ( I think LLVM-related commits like https://github.com/tensorflow/tensorflow/commit/17e6dc2492e7556dd6c2107f14b1e2ba76a8ed34 are the culprits ).

**Comment by bhack** [comment]
> I would add one more difficulty: Even with local cache, it seems to be invalidated each time I pull the commits from upstream. ( I think LLVM-related commits like [17e6dc2](https://github.com/tensorflow/tensorflow/commit/17e6dc2492e7556dd6c2107f14b1e2ba76a8ed34) are the culprits ).

What cache command are you using?

**Comment by vnvo2409** [comment]
I am using [`--disk_cache`](https://docs.bazel.build/versions/master/remote-caching.html#disk-cache). I noice that I have much longer build ( around 8~10 hours ) everytime there is one LLVM-related commit ( which is pretty much daily but I don't pull upstream that much often ).

**Comment by vnvo2409** [comment]
I found that in https://github.com/tensorflow/tensorflow/issues/40505#issuecomment-644841643, @mihaimaruseac said the same thing. Do you have any problem regarding this issue @bhack ?

**Comment by bhack** [comment]
> I found that in [#40505 (comment)](https://github.com/tensorflow/tensorflow/issues/40505#issuecomment-644841643), @mihaimaruseac said the same thing. Do you have any problem regarding this issue @bhack ?

We are waiting to have a bootstrapped GCS cache for this action produced with a fresh master build in `tensorflow/tensorflow:devel`

**Comment by bhack** [comment]
If the llvm sync will totally invalidate the remote bazel cache we cannot use Github Action but we need to use self hosted github Actions as suggested in https://github.com/tensorflow/tensorflow/pull/48421#issuecomment-818335926.

**Comment by gbaned** [comment]
@bhack  This PR is in draft, any update on this? Please. Thanks!

**Comment by bhack** [comment]
@gbaned It is a draft cause as you can see the introduced action go in Timeout on Github. 
I am waiting on an agreement on how I could use a GCS readonly cache with the infra/build team /cc @mihaimaruseac @angerson

**Comment by bhack** [comment]
Closing this for https://github.com/tensorflow/tensorflow/pull/57630

**Pull request closed without merging**
