### PR TITLE
Cherry-picks to bring tensorflow/compiler up-to-date with master in r1.0 branch.

### PR DESCRIPTION
**Pull request by tatatodd**
This contains cherry-picks to bring all files under tensorflow/compiler in the r1.0 branch up-to-date with master.

This was accomplished by determining a a sequence of commits in oldest-to-newest order that could cleanly be cherry-picked.  This is represented by everything except the last 2 commits.

The second-to-last commit was manually merged, reverting unrelated tensorboard files.

The last commit was manually created, reverting files in directories other than tensorflow/compiler.

### CODE REVIEW

**Review by gunan — COMMENTED** [review]
I think we can live without reverting the non-compiler folder changes. They do not seem to be too bad.
Could you revert that commit?

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
The failing test is just flaky. After we revert the last commit, I can retest and merge this right away.

**Comment by tatatodd** [comment]
OK, I've reverted the "last commit", so the innocuous files outside of tensorflow/compiler are also part of this PR.  My next message will either be idiotic or brilliant...

**Comment by tatatodd** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
http://ci.tensorflow.org/job/tensorflow-pull-requests-xla/1/
Running XLA tests on the PR to make sure its alive.

**Comment by gunan** [comment]
Mac tests flaked.
Jenkins, test this please.

**Review by gunan — APPROVED** [review]

**Pull request merged**
