### PR TITLE
[INTEL MKL] DNN 0.x code cleanup - Fused Matmul op

### PR DESCRIPTION
**Pull request by gzmkl**
This PR replaces the old one https://github.com/tensorflow/tensorflow/pull/45564 (which is not approved/merged), 

DNN 0.x cleanup of Fused Matmul op:

(1) Remove all DNN 0.x related code;

(2) Replace all DNN 1.x macro usages

And minor change in quantized op (macro replacement in a couple of places)

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for cleaning up and I'm so sorry for the delay!

**Comment by gbaned** [comment]
@gzmkl Can you please resolve conflicts? Thanks!

**Comment by gzmkl** [comment]
@gbaned  I have addressed the merge conflict issues. thank you!

**Review by penpornk — APPROVED** [review]
Thank you again for the PR!

**Pull request merged**
