### PR TITLE
Update activations.py

### PR DESCRIPTION
**Pull request by tanujdhiman**
Add Activation named `Softclip`

### CODE REVIEW

**Comment by gbaned** [comment]
@tanujdhiman  Can you please sign CLA. Thanks!

**Comment by tanujdhiman** [comment]
Hi @gbaned 
I was thinking of this activation function to be added in this repository. I've tried this in my local system too. This works !!!

Also can you please tell how I can sign for CLA (Contributor License Agreement) ?

Thanks

**Comment by tanujdhiman** [comment]
> @tanujdhiman Can you please sign CLA. Thanks!

Yes, I have !!!

**Comment by tanujdhiman** [comment]
@googlebot I signed it!

**Comment by haifeng-jin** [comment]
We are trying to minimize the Keras API to the most widely used functions.
Please refer to https://github.com/keras-team/governance/blob/master/keras_api_design_guidelines.md#carefully-weigh-whether-a-new-feature-should-be-included
We do not believe this met the guidelines for creating a new Keras API.

**Pull request closed without merging**
