### PR TITLE
Update get_started.md

### PR DESCRIPTION
**Pull request by 4F2E4A2E**
Correcting output.

### CODE REVIEW

**Comment by 4F2E4A2E** [comment]
✔️ Please visit https://cla.developers.google.com/ to sign.

**Review by rohan100jain — APPROVED** [review]

**Comment by rohan100jain** [comment]
@tensorflow-jenkins test this please

**Comment by 4F2E4A2E** [comment]
@rohan100jain thank you for merging. Can you tell me how the process of building and deploying the documentation is beeing handle by you guys? I see many differences between the source documentation and the one published.

**Comment by gunan** [comment]
The root of the website will always be from the latest stable version, which is currently 1.0.
Your changes in master will be deployed under `https://www.tensorflow.org/versions/master/get_started/get_started`.
Your changes will also be in the next release cut which will be 1.2 (1.1 is already cut, and nearing the final release.)

**Comment by 4F2E4A2E** [comment]
Thanks for the info. 👍

**Pull request merged**
