### PR TITLE
Add example to import_meta_graph docstring

### PR DESCRIPTION
**Pull request by vidakDK**
Same change as the PR: https://github.com/tensorflow/tensorflow/pull/23742
Created new PR due to merging into a different branch. 

Details: Based on the super insightful example by @mrry on Stackoverflow (https://stackoverflow.com/a/38834095/1063607), which many users suggested should be in the official documentation.

### CODE REVIEW

**Comment by vidakDK** [comment]
CLA test

**Comment by vidakDK** [comment]
CLA test

**Comment by ymodak** [comment]
@vidakDK Can you please sign the CLA to move ahead with this PR? Thanks!

**Comment by angersson** [comment]
@vidakDK Thanks for updating your change to master!

I think the CLA bot is confused because one of the commits doesn't use your GitHub username, but is still your name. It should be safe to override.

**Comment by vidakDK** [comment]
If it’s possible to override please do so, I don’t know how to sign CLA
with that account, it’s just my local host name :) I tried to commit with
my GitHub username afterward, but the bot still isn’t happy. :D

**Review by angerson — APPROVED** [review]

**Pull request merged**
