### PR TITLE
[INTEL MKL] Updated the DNNL version from v2.1 to v2.2 release candidate

### PR DESCRIPTION
**Pull request by cuixiaom**

### CODE REVIEW

**Comment by cuixiaom** [comment]
@penpornk , this is the TensorFlow 2.5 targeted DNNL version. please review. Thanks a lot!

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Comment by penpornk** [comment]
The oneDNN CI Build [failed](https://tensorflow-ci.intel.com/job/tensorflow-mkl-linux-cpu-pr/8624/). Is this expected?

**Comment by agramesh1** [comment]
> The oneDNN CI Build [failed](https://tensorflow-ci.intel.com/job/tensorflow-mkl-linux-cpu-pr/8624/). Is this expected?

@penpornk It is failing a bf16 remapper test that I don't see in our internal tests.  We will try to reproduce. 
I would recommend you go ahead and merge, we will submit a patch if we can reproduce.  Thanks.

**Comment by penpornk** [comment]
@agramesh1 Got it. I'll merge this if other tests pass. Thank you for the quick reply!

**Comment by cuixiaom** [comment]
@penpornk , regard to the build error found in the Ubuntu CPU CI test, we couldn't reproduce it in our local machine or our internal testing machine. This could be another similar issues we had before. probably we only need to add the following lines in the third_party/mkl_dnn/mkldnn_v1.BUILD to fix it?
a/third_party/mkl_dnn/mkldnn_v1.BUILD
+++ b/third_party/mkl_dnn/mkldnn_v1.BUILD
@@ -93,6 +93,7 @@ _TEXTUAL_HDRS_LIST = glob([
"include/**/*",
"src/common/*.hpp",
"src/common/ittnotify/*.h",
+ "src/common/ittnotify/legacy/*.h",
"src/cpu/*.hpp",
"src/cpu/**/*.hpp",

**Comment by penpornk** [comment]
@cuixiaom Thank you for the suggestion! I've already fixed it internally with a similar fix (changing `"src/common/ittnotify/*.h",` to `"src/common/ittnotify/**/*.h",`).

**Comment by alenik01** [comment]
Dear @penpornk and @vpirogov, may you please comment: there is another update planned to add oneDNN v2.2 release, correct? Currently the sources for `mkl_dnn_v1` have been updated to https://github.com/oneapi-src/oneDNN/archive/3d1e248f293cb962eb73bfc1298a0c66a3ad3298.tar.gz, but it seems to be not the final v2.2 release, right?

**Comment by penpornk** [comment]
Hi @alenik01, TF 2.5 will likely use this commit (unless there are some patches needed). For the master branch, I think we will update to the final v2.2 release once they are out. Cc'ing @agramesh1 for more info.

**Comment by agramesh1** [comment]
@penpornk @alenik01 there was a fix made after this commit, and expect that that it will tagged v2.2.  So looks like we will have a patch for upgrading to the tagged branch.

**Comment by alenik01** [comment]
@agramesh1 @penpornk, many thanks for the clarification.

**Comment by penpornk** [comment]
@alenik01 The update to v2.2 went into master yesterday (#48248). We are cherry-picking the update into TF 2.5 (#48345).

**Comment by alenik01** [comment]
@penpornk, thanks for pointing this out, I will update `mkl_dnn_acl_compatible` accordingly.

**Comment by penpornk** [comment]
@alenik01 Thank you! Do you think we can go back to using the same repository now that the branch cut is done?

**Comment by alenik01** [comment]
@penpornk, we, unfortunately, have some problems with compiling JIT'ed sources (currently they are excluded in Bazel for our repository build).

**Comment by penpornk** [comment]
@alenik01 Using the [mkl_dnn_v1](https://github.com/tensorflow/tensorflow/blob/74f6ab85bcec784e58d81998cdc420466a472f71/tensorflow/workspace2.bzl#L182-L183) repository will only force you to use the same [BUILD file](https://github.com/tensorflow/tensorflow/blob/master/third_party/mkl_dnn/mkldnn_v1.BUILD). You can still use a different build rule (like [how it was before the ACL PR](https://github.com/tensorflow/tensorflow/blob/1bcd2dadc6627be30c83022d30343c8251b9f2d2/third_party/mkl_dnn/mkldnn_v1.BUILD#L139-L170)) and exclude the x64 sources.

**Comment by alenik01** [comment]
@penpornk, having the same BUILD file with different targets is indeed possible. May you please comment, will `mkl_dnn_v1` repository be updated in terms of oneDNN version from time to time? E.g., v2.3 release is scheduled for the end of June.

**Comment by penpornk** [comment]
@alenik01 Yes, the [mkl_dnn_v1](https://github.com/tensorflow/tensorflow/blob/74f6ab85bcec784e58d81998cdc420466a472f71/tensorflow/workspace2.bzl#L182-L183) repository is updated from time to time by the @TensorFlow-MKL team. (But not necessarily every minor release, for example, from v1.6.4, we skipped v1.7-v1.8 and upgraded to v2.1.) cc: @agramesh1

If in the future you need to use a different oneDNN version from `mkl_dnn_v1` or need a different update schedule, we can create a separate repo again. :)

**Comment by agramesh1** [comment]
@alenik01 @penpornk we don't have any specific schedule for updating oneDNN, we do skip revs if there is no need to upgrade.

**Comment by alenik01** [comment]
@penpornk @agramesh1 Many thanks for the explanation. The point is that if a new functionality will be added to oneDNN v2.3 we would like to update the repository, thus I suggest to keep separate BUILD files and repositories for some time.

**Comment by penpornk** [comment]
@alenik01 Sounds good to me. Thank you for the clarification!

**Pull request merged**
