### PR TITLE
[tflite] Enable CoreML/GPU delegate on m1

### PR DESCRIPTION
**Pull request by freedomtan**
To run TFLite models on M1 devices, we need CoreML delegate to offload computation to Apple's Neural Engine.

```
bazel build //tensorflow/lite/tools/benchmark:benchmark_model \
  --macos_cpus arm64
```
    
```
./bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model \
  --use_coreml=1 \
  --graph=/tmp/mobilenet_edgetpu_224_1.0_float.tflite
```
works as expected

### CODE REVIEW

**Comment by abattery** [comment]
@teijeong @yyoon could you review this change?

**Comment by freedomtan** [comment]
Testing classifiers with `label_image` + CoreML delegate also shows expected results. E.g., the following is running MobileNet EdgeTPU

```
% bazel-bin/tensorflow/lite/examples/label_image/label_image --use_coreml=1 -m /tmp/tflite-models-new/float/mobilenet_edgetpu_224_1.0_float.tflite -i /tmp/grace_hopper.bmp -l /tmp/labels.txt -c 50     
INFO: Loaded model /tmp/tflite-models-new/float/mobilenet_edgetpu_224_1.0_float.tflite
INFO: resolved reporter
2021-03-07 10:44:37.676 label_image[18419:1846370] coreml_version must be 2 or 3. Setting to 3.
INFO: COREML delegate created.
INFO: CoreML delegate: 75 nodes delegated out of 77 nodes, with 2 partitions.

INFO: Applied Delegate_Provider_COREML delegate.
INFO: invoked
INFO: average time: 0.96858 ms
INFO: 0.78034: 653 military uniform
INFO: 0.0309746: 458 bow tie
INFO: 0.0292118: 835 suit
INFO: 0.0196119: 440 bearskin
INFO: 0.0135848: 716 pickelhaube
```

The `label_image` was built with
```
bazel build --config opt //tensorflow/lite/examples/label_image:label_image --macos_cpus arm64
```

**Review by yyoon — CHANGES_REQUESTED** [review]
Overall looks good to me.

I don't have an M1 mac with me, so could you please paste benchmark results of one of our hosted models to show the latency difference among 1) default (CPU) configuration, 2) `--use_gpu=1`, 3) `--use_coreml=1`?

Also, could you include "GPU delegate" in the PR title as well?

**Comment by freedomtan** [comment]
Floating point MobileNet V1 1.0 224 from [TFLite hosted models](https://www.tensorflow.org/lite/guide/hosted_models)

Summary: unit: ms
| how | average latency|
|-----|------:|
|CPU 1xthread| 18.847 |
|CPU 4xthreads| 9.087|
|GPU delegate| 2.699|
|CoreML delegate| 1.051|

```
freedom@myway-m1 tf-hacks % ./bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model --graph=/tmp/mobilenet_v1_1.0_224.tflite       
STARTING!
Log parameter values verbosely: [0]
Graph: [/tmp/mobilenet_v1_1.0_224.tflite]
Loaded model /tmp/mobilenet_v1_1.0_224.tflite
The input model file size (MB): 16.9011
Initialized session in 0.464ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=26 first=37888 curr=18859 min=18796 max=37888 avg=19709.4 std=3689

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=54 first=18877 curr=18818 min=18817 max=19111 avg=18847.4 std=41

Inference timings in us: Init: 464, First inference: 37888, Warmup (avg): 19709.4, Inference (avg): 18847.4
freedom@myway-m1 tf-hacks % ./bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model --graph=/tmp/mobilenet_v1_1.0_224.tflite --num_threads=4
STARTING!
Log parameter values verbosely: [0]
Num threads: [4]
Graph: [/tmp/mobilenet_v1_1.0_224.tflite]
#threads used for CPU inference: [4]
Loaded model /tmp/mobilenet_v1_1.0_224.tflite
The input model file size (MB): 16.9011
Initialized session in 0.455ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=53 first=35946 curr=9255 min=8685 max=35946 avg=9579.11 std=3664

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=110 first=8954 curr=9034 min=8832 max=9810 avg=9087.25 std=143

Inference timings in us: Init: 455, First inference: 35946, Warmup (avg): 9579.11, Inference (avg): 9087.25
freedom@myway-m1 tf-hacks % ./bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model --graph=/tmp/mobilenet_v1_1.0_224.tflite --use_gpu=1
STARTING!
Log parameter values verbosely: [0]
Graph: [/tmp/mobilenet_v1_1.0_224.tflite]
Use gpu: [1]
Loaded model /tmp/mobilenet_v1_1.0_224.tflite
INFO: Created TensorFlow Lite delegate for Metal.
Explicitly applied GPU delegate, and the model graph will be completely executed by the delegate.
The input model file size (MB): 16.9011
Initialized session in 208.191ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=275 first=4297 curr=2087 min=1429 max=4297 avg=1780.88 std=263

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=362 first=2225 curr=2711 min=1978 max=2827 avg=2698.69 std=84

Inference timings in us: Init: 208191, First inference: 4297, Warmup (avg): 1780.88, Inference (avg): 2698.69
freedom@myway-m1 tf-hacks % ./bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model --graph=/tmp/mobilenet_v1_1.0_224.tflite --use_coreml=1
STARTING!
Log parameter values verbosely: [0]
Graph: [/tmp/mobilenet_v1_1.0_224.tflite]
Use CoreML: [1]
Loaded model /tmp/mobilenet_v1_1.0_224.tflite
2021-03-07 11:03:42.453 benchmark_model[24456:1865700] coreml_version must be 2 or 3. Setting to 3.
INFO: CoreML delegate: 29 nodes delegated out of 31 nodes, with 2 partitions.

Explicitly applied COREML delegate, and the model graph will be partially executed by the delegate w/ 1 delegate kernels.
The input model file size (MB): 16.9011
Initialized session in 341.744ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=472 first=1660 curr=1050 min=1017 max=1660 avg=1049.53 std=31

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=942 first=1039 curr=1084 min=1022 max=1154 avg=1051.01 std=15

Inference timings in us: Init: 341744, First inference: 1660, Warmup (avg): 1049.53, Inference (avg): 1051.01
```

**Review by yyoon — APPROVED** [review]
Thanks for the benchmark results! Looking very nice.

**Comment by freedomtan** [comment]
@yyoon Thanks. I added additional checks to fix dependency problem reported by CI.

**Review by yyoon — APPROVED** [review]

**Review by yyoon — APPROVED** [review]

**Review by teijeong — APPROVED** [review]

**Comment by terryheo** [comment]
@freedomtan what is required to use "--macos_cpus arm64" ?
I used the following command on my x86 mac but the compiled binary is x86_64.
```
$ bazel build //tensorflow/lite/tools/benchmark:benchmark_model --macos_cpus arm64
  ...
$ file bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model
bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model: Mach-O 64-bit executable x86_64
```

Also TF is using "--config=darwin_arm64", why can't we use it?

**Comment by freedomtan** [comment]
@terryheo Arrgh, yes, that's a bit tricky. I should put it down somewhere. No, `--macos_cpus arm64` is not for building arm64 binary on intel machine. I didn't try to build arm64 binary or fat binary on x86 machines.

On M1 machines, with arm64 bazel (built from its master branch), I can build "right" `benchmark_model` (w/o coreml and gpu delegate) without problem. But building either coreml or gpu delegate is enabled, we need update XNNPACK and some related packages. I'll send another PR to update those information. And I'll check if I can build either arm64 or fat one on x86_64 machines.

**Pull request merged**
