### PR TITLE
Fix for build issue #2742;

### PR DESCRIPTION
**Pull request by kingtaurus**
(1) grabs build info from eigen.BUILD (rather than using a specified hash);

### CODE REVIEW

**Comment by kingtaurus** [comment]
I signed it!

**Comment by petewarden** [comment]
Awesome, thanks for putting this together! One minor request - could you add a one-line comment in both places explaining why we're grabbing the hash from the file, something like "Pull the current Eigen version name from the Bazel build file"? Thanks again for doing this!

**Comment by kingtaurus** [comment]
@petewarden Done;

**Comment by vrv** [comment]
unfortunately there are some conflicts :(

**Comment by kingtaurus** [comment]
I'm going to create a new pull request;

**Comment by petewarden** [comment]
Thanks Gregory, and apologies, I'm guessing my manual PR updating the Eigen hash caused the conflicts.

**Pull request closed without merging**
