### PR TITLE
[XLA] Allow the iota test to be disabled with a manifest file

### PR DESCRIPTION
**Pull request by DavidNorman**
This adds the option to disable the iota test using a manifest file.

### CODE REVIEW

**Comment by DavidNorman** [comment]
Polite inquiry: are you awaiting a response from me, or @nickdesaulniers ?

**Comment by nickdesaulniers** [comment]
@martinwicke , I believe I LGTM'd the internal review.  Can you or @caisq see this through?

**Review by nickdesaulniers — APPROVED** [review]

**Comment by DavidNorman** [comment]
Does someone need to add a 'do a test build' flag to get the tests to run?

**Comment by DavidNorman** [comment]
Hi.

Is this now ready to pull, since that 'import/copybara' seems to never report its status for any PR?

**Pull request merged**
