### PR TITLE
Support full [b]float16 in embedding_lookup_sparse

### PR DESCRIPTION
**Pull request by benbarsdell**
- Adds float16 support for SparseSegment* ops.
- Removes a forced cast to float32 in `embedding_lookup_sparse` and instead outputs the same type as the input. The inner computations are still done in float32 to avoid numerical issues.
- This improves performance and makes the operation consistent with all other operations that output the same type as the input.

cc @nluehr @reedwm

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Review by gbaned — APPROVED** [review]

**Comment by benbarsdell** [comment]
@penpornk I noticed that `SparseSegmentSumGrad` was added since I submitted this PR, so we should add float16 for that op too.
I can rebase and force push to this PR, or I can submit a separate PR. Let me know which you'd prefer.

**Comment by benbarsdell** [comment]
Gentle ping

**Comment by penpornk** [comment]
@benbarsdell Sorry for the late reply! Please submit another PR.

**Pull request merged**
