### PR TITLE
Update to bazel-0.18.0 and use try-import

### PR DESCRIPTION
**Pull request by perfinion**
Bazel-0.18.0 adds a try-import option that will non-fatally try and
import a file. Use this for the configure options so that .bazelrc does
not need to change. ./configure rewriting .bazelrc makes using the git
repo annoying because the file is changed.

Also optionally import a /.bazelrc.user file that is gitignored so
user-specific options can go in there.

Fixes: https://github.com/tensorflow/tensorflow/issues/22762
Fixes: https://github.com/tensorflow/tensorflow/pull/22906
Signed-off-by: Jason Zaman <jason@perfinion.com>

### CODE REVIEW

**Comment by perfinion** [comment]
Bazel-0.18.0 is due out on monday. Lets merge this in as soon as we can. Having ./configure edit the .bazelrc is causing a lot of annoyance.

**Comment by gunan** [comment]
Bumping the minimum required version to the cutting edge version has caused many issues before.
Due to this, I am against this change in minimum requirement until at least bazel 0.19 is out.

**Comment by perfinion** [comment]
@gunan okay fair enough. In that case bazel-0.18.0 has temporarily added back reading tools/bazel.rc so I'll make a separate PR to move things back there then when 0.19.0 is out we do this change.

**Comment by yongtang** [comment]
The issue #22449 might be related (needs bazel `update > 0.17.1`).

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment]
@gunan @perfinion It looks like bazel 0.19.0 has been released:
https://github.com/bazelbuild/bazel/issues/6116

**Comment by meteorcloudy** [comment]
Since Bazel 0.19.0 has come out, can we try again to merge this change?
Currently,  TensorFlow has been disabled from Bazel downstream projects due to the bazelrc file change, I wound like to bring it back before we cut 0.20.0.

**Comment by meteorcloudy** [comment]
@perfinion Is this PR going to fix TF build with Bazel 0.19.0? If so, can you try to resolve the conflicts? Thanks!

**Comment by meteorcloudy** [comment]
We need to upgrade Bazel to 0.18.1 on all CI machines before merging this.

**Comment by angersson** [comment]
@meteorcloudy Is that upgrade only required on TensorFlow's CI machines?
@amitpatankar What do we need to do to upgrade Bazel on the CI machines?

**Comment by meteorcloudy** [comment]
@angersson Yes, in order not to break anything, we should upgrade Bazel on all TF CI machines.
But, of course, after merging this change, anyone wants to build TensorFlow from HEAD needs at least 0.18.X.

**Comment by gunan** [comment]
@meteorcloudy, then this change needs to be done internally, to be able to make all the test infra changes atomicly.
Would you like to import this change and make those upgrades? @yifeif can provide the instructions to start by importing this change internally.

**Comment by meteorcloudy** [comment]
Sounds good, I can help import this change and make those upgrades!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by perfinion** [comment]
I updated this. min version is 0.18.0, max is 0.20.0. I added an env variable to skip the max bazel version check to make testing new versions easier.
User-specific changes should go in .bazelrc.user which is gitignored. Nothing should edit .bazelrc anymore since it is no longer gitignored.

Looks like the the CI builds are all failing, do they need to be upgraded?

**Comment by meteorcloudy** [comment]
Yes, looks like Bazel is still 0.16.1 on Ubuntu. Can we upgrade to the latest Bazel on all CI machines?
@gunan @yifeif

**Comment by yifeif** [comment]
@meteorcloudy I'll send you a change to upgrade ubuntu to the same bazel version internally. Ping me if you need help with pulling this PR in.

**Review by gunan — APPROVED** [review]
While minimum is 0.18, I still  want our dockerfiles to have 0.20 because 0.18 and 19 have some bugs

**Review by angerson — APPROVED** [review]

**Pull request merged**
