### PR TITLE
fixed possiblity of integer flow

### PR DESCRIPTION
**Pull request by shubham769**
The current code can lead to integer overflow and weird results
As also discussed in below issue on some points it is giving some unexpected results.
This PR is to fix this problem
#32045 :issue number

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
The code can produce overflows even with the change you proposed.

`filter_rows = filter_cols = in_depth = out_depth = out_row = out_cols = MAX_INT - 1`

**Comment by shubham769** [comment]
@mihaimaruseac i think we can check overflow and give revelant warning , please have an review

**Review by mihaimaruseac — COMMENTED** [review]
The changes look good but I'm not eager to approve a 100% copy-pasted PR (#32120, #32071).

**Comment by mihaimaruseac** [comment]
All of these values are signed integers with a well defined behavior on overflow. As such, caller code should check and handle it, instead of here.

Closing PR due to all mentioned issues.

**Pull request closed without merging**
