### PR TITLE
Update maxout.py

### PR DESCRIPTION
**Pull request by erikchwang**
Specify the final number of features in the maxout axis

### CODE REVIEW

**Comment by carltonwang** [comment]
I signed it!

**Review by drpngx — APPROVED** [review]
Please pull rebase and push again. Thanks!

**Comment by rmlarsen** [comment]
@carltonwang please rebase and push again.

**Comment by carltonwang** [comment]
sorry, i do not know what is rebase

**Comment by drpngx** [comment]
Rebase means to put your changes on top of the current tip of the branch.

Probably something like that:
```
git remote add origin git@github.com:cartonwang/tensorflow.git
git remote add tfhead https://github.com/tensorflow/tensorflow.git
git fetch tfhead && git rebase tfhead/master
git push -u origin master
```

**Pull request closed without merging**
