### PR TITLE
[tflite] Add ruy header for profile in gather

### PR DESCRIPTION
**Pull request by seanshpark**
This will include missing ruy instrumentation header for ruy profile.

### CODE REVIEW

**Comment by seanshpark** [comment]
There seems some network problem... I'll just wait till someone restarts the CI...

**Comment by seanshpark** [comment]
@gbaned PTAL

**Comment by gbaned** [comment]
@miaout17 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @seanshpark Can you please resolve conflicts? Thank you!

**Comment by seanshpark** [comment]
> Can you please resolve conflicts? Thank you!

done :)

**Comment by seanshpark** [comment]
@gbaned , how can I resolve CI failures? or rebase later when it's fixed?

**Comment by seanshpark** [comment]
@alankelly , can you please take a look? @miaout17 seems too busy.

**Review by alankelly — APPROVED** [review]

**Pull request merged**
