### PR TITLE
code annotation fix

### PR DESCRIPTION
**Pull request by MaoXianXin**
change input_tensor: A [1, height, width, 3] ----> input_tensor: A [height, width, 3]

### CODE REVIEW

**Comment by MaoXianXin** [comment]
the input_tensor shape should be [height, width, 3]

**Comment by MaoXianXin** [comment]
Fix Note display problem

**Comment by MaoXianXin** [comment]
change all keypoint_with_scores ---> keypoints_with_scores
Uniform variable representation

**Comment by khanhlvg** [comment]
@gbaned The changes LGTM. Can you approve the PR?

**Review by gbaned — APPROVED** [review]

**Review by khanhlvg — APPROVED** [review]

**Pull request merged**
