### PR TITLE
TFLu: Fix Ethos-U build errors

### PR DESCRIPTION
**Pull request by mansnils**
-Fix variable length array error in conv_test.
-As for now, suppress -Wdouble-promotion in Ethos-U operator until it is
 resolved in Flatbuffers.

### CODE REVIEW

**Comment by mansnils** [comment]
This is the flexbuffer error:
18:25:16  tensorflow/lite/micro/tools/make/downloads/flatbuffers/include/flatbuffers/flexbuffers.h:1420:25: error: implicit conversion increases floating-point precision: 'float' to 'double' [-Werror,-Wdouble-promotion]
18:25:16      Value(float f) : f_(f), type_(FBT_FLOAT), min_bit_width_(BIT_WIDTH_32) {}
18:25:16                         ~^
18:25:16  1 error generated.

**Review by freddan80 — COMMENTED** [review]
Look good to me

**Comment by mansnils** [comment]
The flexbuffers error has been fixed by this PR: https://github.com/google/flatbuffers/commit/dca12522a9f9e37f126ab925fd385c807ab4f84e So I will undo the change in tensorflow/lite/micro/kernels/ethos-u/ethosu.cc

**Review by freddan80 — APPROVED** [review]

**Comment by advaitjain** [comment]
The existing code doesn't really follow the style guide and is worth fixing, IMO.

My hope is that the following two PRs will fix your issue:
 * I have created #43858 to get the code to conform to the style guide and hopefully also fix the issue with VLA.
 * And @njeffrie has separated out the flatbuffer upgrade to its own PR #43856

**Comment by mansnils** [comment]
OK, good. Let's close this PR then.

**Pull request closed without merging**
