### PR TITLE
Fix go build errors

### PR DESCRIPTION
**Pull request by damienstanton**
Two minor changes:
- enum declaration should use C++ syntax
- swig can't port `int64_t` to Go's type system. `long long` used instead.

### CODE REVIEW

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by damienstanton** [comment]
@tensorflow-jenkins test this, pelase

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by zheng-xq** [comment]
Adding @josh11b to review. 

The files had all been moved to tensorflow/c

**Comment by josh11b** [comment]
- We really want a 64-bit int type, not whatever long long happens to be
- The whole point of this file is to use C not C++ so the enum change is counter productive.

**Comment by damienstanton** [comment]
@josh11b fair point, but I was not able to use the Go API bindings until I made these changes. I should probably take a different approach and try to modify the swig helpers rather than the C API itself.

**Comment by danmane** [comment]
@damienstanton should we keep this PR open for you to try a different approach, or close and wait for a fresh PR?

**Comment by damienstanton** [comment]
@danmane since I don't want my branch to get too stale, let's close this and I will open a new PR down the line. Thanks!

**Comment by danmane** [comment]
OK, look forward to the new one :)

**Pull request closed without merging**
