### PR TITLE
Reset mem allocation type after TensorDataFree

### PR DESCRIPTION
**Pull request by siju-samuel**
Reset mem allocation type after TfLiteTensorDataFree

### CODE REVIEW

**Comment by siju-samuel** [comment]
@karimnosseir @aselle please help to review this PR. TIA

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@siju-samuel  Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 44 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
