### PR TITLE
[INTEL MKL]  Setting default value for KMP_BLOCKTIME

### PR DESCRIPTION
**Pull request by vishakha-nervana**
To improve overall user experience and performance, this PR sets KMP_BLOCKTIME to 1, if not set already by user.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Comment by penpornk** [comment]
@alenik01 This PR has changes that could affect `--config=mkl_aarch64` build. Could you please help check if things are okay on your end? (I plan to cherry-pick this into TF 2.5.)

**Comment by alenik01** [comment]
Good morning, @penpornk Many thanks for the heads up. Mmain problem which I encounter with this commit is that it doesn't build even with `--config=mkl`, because Bazel for some reason fails to find `external/llvm_openmp/include/omp.h`. The similar situation is also for `--config=mkl_aarch64`. Did you manage to build the master after merging this commit?

>Execution platform: @local_execution_config_platform//:platform
>tensorflow/core/common_runtime/threadpool_device.cc:19:10: fatal error: external/llvm_openmp/include/omp.h: No such file or directory
>   19 | #include "external/llvm_openmp/include/omp.h"
>     |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>compilation terminated.
>Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by penpornk** [comment]
Good morning, @alenik01! We decided not to cherry-pick this PR into 2.5 for now. 

> Did you manage to build the master after merging this commit?

I didn't try building it manually, but the [oneDNN CI test for this PR was fine](https://tensorflow-ci.intel.com/job/tensorflow-mkl-linux-cpu-pr/8858/).

**Comment by alenik01** [comment]
Good afternoon, @penpornk 

>Could you please help check if things are okay on your end?

I have checked `--config=mkl_aarch64` with the current TF `master` and it works correctly on AArch64 server. The only disadvantage for us is that additional `--cxxopt="-DDNNL_AARCH64_USE_ACL=1"` has to be added now in the build command, _i.e._ defined globally for all the build instead of the necessary files only, I will try to find a more elegant solution.

**Comment by haitong** [comment]
we should not merge this PR as tensorflow build failed with `--config=mkl`. it is surprising that no one complained about it except @alenik01 [alenik01](https://github.com/alenik01)

**Comment by haitong** [comment]
For example, tfserving build is failing due to this https://github.com/tensorflow/serving/issues/1958#issue-1092136168

**Comment by penpornk** [comment]
cc: @TensorFlow-MKL @agramesh1

**Comment by agramesh1** [comment]
HI @penpornk we can revert this PR, it does not work the way it was intended. We will submit a PR to revert. Thanks.

**Pull request merged**
