### PR TITLE
Fixing documentation issue on ctc_loss, this relates to the issue:

### PR DESCRIPTION
**Pull request by leonardoaraujosantos**
https://github.com/tensorflow/tensorflow/issues/34586

### CODE REVIEW

**Comment by leonardoaraujosantos** [comment]
@googlebot I signed it!

**Comment by leonardoaraujosantos** [comment]
@googlebot I fixed

**Comment by leonardoaraujosantos** [comment]
@googlebot I fixed

**Comment by mihaimaruseac** [comment]
Hi. Please make PR against master branch. We are only making PRs against release branches when we are preparing a release or a patch release. In either case, these PRs are only cherry-picks from master.

**Pull request closed without merging**
