### PR TITLE
Fixing comment, wrong data type in argument description.

### PR DESCRIPTION
**Pull request by dcastro9**
Usage can be seen in lines 445->446, the file is read in and passed directly in, it is not a Numpy array, but rather just a string of raw JPEG data passed into the DecodeJpeg layer of an arbitrary network (by default Inception v3).

### CODE REVIEW

**Comment by shlens** [comment]
LGTM

**Comment by danmane** [comment]
@tensorflow-jenkins PTAL

**Comment by petewarden** [comment]
I believe this correction is right, LGTM, thanks!

**Comment by danmane** [comment]
Since this only changes a docstring, I am going to live dangerously and merge it now.

**Pull request merged**
