### PR TITLE
enable avgpooling for windows gpu builds

### PR DESCRIPTION
**Pull request by guschmue**

### CODE REVIEW

**Comment by guschmue** [comment]
this enables #5532 for gpu

**Review by mrry — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
@gunan: It looks like the PIP installation is failing: https://ci.tensorflow.org/job/tensorflow-pr-win-cmake-py/63/console

```
07:49:25 c:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\cmake_build>SET PIP_EXE="C:\Program Files\Anaconda3\Scripts\pip.exe" 
07:49:25 
07:49:25 c:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\cmake_build>"C:\Program Files\Anaconda3\Scripts\pip.exe" uninstall -y tensorflow 
07:49:26 Cannot uninstall requirement tensorflow, not installed
07:49:26 You are using pip version 8.1.2, however version 9.0.1 is available.
07:49:26 You should consider upgrading via the 'python -m pip install --upgrade pip' command.
07:49:26 
07:49:26 c:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\cmake_build>"C:\Program Files\Anaconda3\Scripts\pip.exe" install --upgrade c:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\cmake_build\tf_python\dist\tensorflow-0.11.0rc2_cmake_experimental-py3-none-any.whl 
07:49:26 Processing .\tf_python\dist\tensorflow-0.11.0rc2_cmake_experimental-py3-none-any.whl
07:49:28 Requirement already up-to-date: wheel>=0.26 in c:\program files\anaconda3\lib\site-packages (from tensorflow==0.11.0rc2-cmake-experimental)
07:49:28 Collecting protobuf==3.0.0 (from tensorflow==0.11.0rc2-cmake-experimental)
07:49:28   Using cached protobuf-3.0.0-py2.py3-none-any.whl
07:49:28 Requirement already up-to-date: six>=1.10.0 in c:\program files\anaconda3\lib\site-packages (from tensorflow==0.11.0rc2-cmake-experimental)
07:49:28 Requirement already up-to-date: numpy>=1.11.0 in c:\program files\anaconda3\lib\site-packages (from tensorflow==0.11.0rc2-cmake-experimental)
07:49:29 Collecting setuptools (from protobuf==3.0.0->tensorflow==0.11.0rc2-cmake-experimental)
07:49:29   Using cached setuptools-28.8.0-py2.py3-none-any.whl
07:49:29 Installing collected packages: setuptools, protobuf, tensorflow
07:49:29   Found existing installation: setuptools 23.0.0
07:49:29 Cannot remove entries from nonexistent file c:\program files\anaconda3\lib\site-packages\easy-install.pth
07:49:29 You are using pip version 8.1.2, however version 9.0.1 is available.
07:49:29 You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

The build *seems to be* succeeding (if I'm reading the logs correctly), but is there any way to tell why PIP is failing to install the `tensorflow` module?

**Comment by gunan** [comment]
I think you are right.
pip install seems to be failing with:
`Cannot remove entries from nonexistent file c:\program files\anaconda3\lib\site-packages\easy-install.pth`

Let's rerun to see if it is a flake:
Jenkins, test this please

**Comment by mrry** [comment]
Could it be a bad Anaconda interaction? Issue #3324 seemed to hit the same problem on Linux with Anaconda.

**Comment by mrry** [comment]
...and this seems to affect not just TF:

https://github.com/ContinuumIO/anaconda-issues/issues/542

**Comment by gunan** [comment]
It was some kind of flake in windows, we are back to only reader ops test failing.
Merging.

**Pull request merged**
