### PR TITLE
Update MNIST source url, original url is dead

### PR DESCRIPTION
**Pull request by MostafaGazar**
http://yann.lecun.com/exdb/mnist/ is not accessible

### CODE REVIEW

**Comment by gunan** [comment]
@ilblackdragon @martinwicke 
I don't think I can accept this PR.
I am not sure we would like to have a reference to a personal repository. We can think about alternate storage options for this dataset. Ilia, Martin, should we host this file instead? Are there any license implications we need to consider?

**Comment by MostafaGazar** [comment]
@gunan That would be the ideal solution. I think you should also consider hosting the files in https://github.com/tensorflow/tensorflow/commit/d2a5b7c8f9bd789423566c56c01d1f92cc94d74d in some place you can manage if license allows

**Comment by martinwicke** [comment]
Yeah, apparently there's been a change and it now requires a signup?

Anyway, we have asked before and we've always been turned down for re-hosting. Possibly we'll have to remove mnist altogether. Let me ask again.

**Comment by MostafaGazar** [comment]
Looks like this http://yann.lecun.com/exdb/mnist/ is working fine now!

**Pull request closed without merging**
