### PR TITLE
Fixed bug with DEBUG_MODE bug when performing from_tensor_slices on a ragged tensor

### PR DESCRIPTION
**Pull request by jsparson1**
Fixed bug with DEBUG_MODE bug when performing from_tensor_slices on a ragged tensor related to issue #60239

Thank you, if there are any suggestions feel free to comment.

### CODE REVIEW

**Comment by foxik** [comment]
Note that the proposed fix is not really a fix -- it just switches off eager mode for ragged tensor results, which is not what should happen.

Instead, the problem is really the `ops.convert_to_tensor` on the following line:
https://github.com/tensorflow/tensorflow/blob/06390d9be42502bb14c055be3978e5cd52a0f376/tensorflow/python/data/ops/structured_function.py#L240

The dataset elements can be ragged or sparse tensors, so this conversion must instead honor the type specs in `self._output_structure`. Maybe it is even the case that for ragged/sparse tensors, these must have been constructed explicitly in the mapping function and no further conversion is necessary (while for a usual tensor, the mapping function might return a Python list that needs to be converted to a tensor)?

Last but not least, such a change requires tests to verify that the fix works and that the problem will never appear again (and apart the ragged tensors mentioned in #60239, it should also include support for sparse tensors).

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
This doesn't look like the real fix. See comment above

**Comment by gbaned** [comment]
Hi @jsparson1 Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!

**Comment by jsparson1** [comment]
> Hi @jsparson1 Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!
Yes I can and I plan on it right now I'm in the middle of exams, I will be able to work on improving my fix in the coming days, thank you all for your feedback.

**Comment by jsparson1** [comment]
> Note that the proposed fix is not really a fix -- it just switches off eager mode for ragged tensor results, which is not what should happen.
> 
> Instead, the problem is really the `ops.convert_to_tensor` on the following line:
> 
> https://github.com/tensorflow/tensorflow/blob/06390d9be42502bb14c055be3978e5cd52a0f376/tensorflow/python/data/ops/structured_function.py#L240
> 
> The dataset elements can be ragged or sparse tensors, so this conversion must instead honor the type specs in `self._output_structure`. Maybe it is even the case that for ragged/sparse tensors, these must have been constructed explicitly in the mapping function and no further conversion is necessary (while for a usual tensor, the mapping function might return a Python list that needs to be converted to a tensor)?
> 
> Last but not least, such a change requires tests to verify that the fix works and that the problem will never appear again (and apart the ragged tensors mentioned in #60239, it should also include support for sparse tensors).

I just got an opportunity to look at it again and I actually think its the previous line
`print("TestStart")
  ret = structure.to_tensor_list(self._output_structure, ret)
  print("TestEnd")`

TestStart
2023-05-10 22:16:10.385226: W tensorflow/core/framework/op_kernel.cc:1817] INVALID_ARGUMENT: ValueError: Value [1 2] is not convertible to a tensor with dtype <dtype: 'variant'> and shape ().
Traceback (most recent call last):

**Comment by foxik** [comment]
You are right that the crash already happens in `to_tensor_list`.

Problem is that the ragged tensor has already been converted using the https://www.tensorflow.org/api_docs/python/tf/raw_ops/RaggedTensorToVariant, so the `_output_structure` contains just "this is a Tensor of dtype variant" instead of "this is a ragged tensor". But maybe we could modify the `TensorSpec._to_components` to be able to handle such situation -- i.e., if it gets a ragged tensor and should convert it to `variant` dtype, it could use the above mentioned method to do it, instead of `ops.convert_to_tensor`? I just tried, but I could not make it work easily; maybe we should investigate more how exactly the processing works without the debug mode and handle the conversions ragged<->dense as it is done there.

**Comment by gbaned** [comment]
Hi @jsparson1 Any update on this PR? Please. Thank you!

**Pull request closed without merging**
