### PR TITLE
Fix the progress bar of keras.Model.evaluate()

### LINKED ISSUE #32320: keras model.evaluate() progress bar WAY too long by default
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): just testing this https://www.tensorflow.org/tutorials/keras/basic_classification
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 fully updated
- TensorFlow installed from (source or binary): `pip3 install --user tensorflow-gpu==2.0.0-rc0`
- TensorFlow version (use command below): `v2.0.0-beta1-5101-gc75bb66a99 2.0.0-rc0`
- Python version: 3.7.4
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce GTX 1660 Ti, 6 GB

**Describe the current behavior**
Just running a basic image classifier with Keras. Import data, create model, train, evaluate.
I run `python script-name.py` in the Command Prompt.
`model.evaluate()` prints out an insanely long progress bar at the end. It's many, MANY pages long, with Command Prompt already maximized (so one page is already a lot of characters). I have to scroll WAAAY UP to see the previous output.

**Describe the expected behavior**
I know I could turn off verbosity, but I would expect sane defaults for the progress bars printed by TF/Keras. And with `verbose=1` that thing is so huge, it's useless.

**Code to reproduce the issue**
```python
from __future__ import absolute_import, division, print_function, unicode_literals

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt
from pprint import pprint

# CUDA vs CPU
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

print(tf.__version__)

# load train/test data
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# print shape/size for train/test data
print(train_images.shape, len(train_labels), test_images.shape, len(test_labels))

# show first image
plt.figure()
plt.imshow(train_images[0])
plt.colorbar()
plt.grid(False)
#plt.show()

# normalize pixel values (0...1)
train_images = train_images / 255.0
test_images = test_images / 255.0

# show first 25 images, sanity check
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[i], cmap=plt.cm.binary)
    plt.xlabel(class_names[train_labels[i]])
#plt.show()

# build the model
# flat 1D layer
# dense 128-node layer
# dense softmax output layer
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])

# compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# train the model
model.fit(train_images, train_labels, epochs=5)

# evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('Test accuracy:', test_acc)
```

### PR DESCRIPTION
**Pull request by djshen**
Fix #32320 and #32286

I also wrote a simple test case to check the value of `params.['samples']` after `model.evaluate()`.
```python
import numpy as np
from tensorflow.python import keras
from tensorflow.python.keras import keras_parameterized
from tensorflow.python.keras import testing_utils
from tensorflow.python.keras.callbacks import Callback
from tensorflow.python.platform import test


class TestCase(keras_parameterized.TestCase):
  def test_callback_params_samples(self):
    x, y = np.ones((64, 3)), np.ones((64, 2))
    model = testing_utils.get_small_sequential_mlp(
        num_hidden=10, num_classes=2, input_dim=3)
    model.compile('sgd', 'mse')
    callback = Callback()
    model.evaluate(x, y, callbacks=[callback])
    self.assertEqual(callback.params['samples'], 64)


if __name__ == '__main__':
  test.main()
```
Where should I put this test case?

The test output before this PR:
```
64/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================] - 0s 845us/sample - loss: 0.3011
[  FAILED  ] TestCase.test_callback_params_samples
[ RUN      ] TestCase.test_session
[  SKIPPED ] TestCase.test_session
======================================================================
FAIL: test_callback_params_samples (__main__.TestCase)
test_callback_params_samples (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d.py", line 17, in test_callback_params_samples
    self.assertEqual(callback.params['samples'], 64)
AssertionError: True != 64

----------------------------------------------------------------------
Ran 2 tests in 0.240s

FAILED (failures=1, skipped=1)
```
The test output after this PR:
```
64/64 [==============================] - 0s 1ms/sample - loss: 0.3011
[       OK ] TestCase.test_callback_params_samples
[ RUN      ] TestCase.test_session
[  SKIPPED ] TestCase.test_session
----------------------------------------------------------------------
Ran 2 tests in 0.261s

OK (skipped=1)
```

### CODE REVIEW

**Comment by djshen** [comment]
@googlebot I signed it!

**Comment by rthadur** [comment]
@mihaimaruseac do you want to take this change ?

**Review by omalleyt12 — CHANGES_REQUESTED** [review]
Thank you for the PR!

Can you please add the test method you created to one of the test classes in `tensorflow/python/keras/callbacks_test.py`? The test looks good and this will help us prevent regressions like this in the future

**Review by omalleyt12 — APPROVED** [review]
Thanks for the PR, LGTM!

**Pull request merged**
