### PR TITLE
New environment capture script features

### PR DESCRIPTION
**Pull request by scouvreur**
On issue #25461, added:
* **CUDA/cuDNN** version
* **GPU model** and memory
* **Bazel** version

refactored to functions:
* **OS Platform and Distribution**
* **GCC/Compiler** version

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle, @jianlijianli: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 18 days with no activity and the `awaiting review` label has been applied.

**Comment by scouvreur** [comment]
Hi there @rthadur @aselle @jianlijianli - would you like me to better document the changes I made to facilitate the review process ?
Would a stacked PR be better perhaps ?

**Comment by jdduke** [comment]
I'm not a good reviewer for this.

**Comment by vrv** [comment]
(I'm also unfamiliar with this script, I think @aselle would know the best person to redirect this to)

**Comment by jianlijianli** [comment]
Sorry but I'm not a good reviewer for this change.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by rthadur** [comment]
#25833 has been merged to address the same issue so closing this PR , thanks for your contribution.

**Pull request closed without merging**
