### PR TITLE
[TF-TRT] Add engine device to `converter.summary()`

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
This PR adds the TRTEngineOP device to the `converter.summary()` report.

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
This goes in the direction to be able to debug and assess:
```
with tf.device("/gpu:1"):
    converter.convert()
```

**Comment by DEKHTIARJonathan** [comment]
@bixia1 any feedback ?

**Comment by bixia1** [comment]
Can you provide a PR description on the first block?

**Comment by DEKHTIARJonathan** [comment]
@bixia1 done. Can you approve

**Review by bixia1 — APPROVED** [review]

**Pull request merged**
