### PR TITLE
Shrink README.md logo

### PR DESCRIPTION
**Pull request by angerson**
This got really big all of a sudden.

### CODE REVIEW

**Review by drpngx — APPROVED** [review]
So... It's the new logo, which is good, but if I click on rich diff here, it seems even larger?

**Comment by angersson** [comment]
@drpngx Unless I'm making a big mistake, this change shrinks the enormous logo (which is live at https://github.com/tensorflow/tensorflow) to a more manageable small-ish logo with text underneath.

**Comment by drpngx** [comment]
OK, let's try it out

**Comment by angersson** [comment]
Much better, thanks!

**Pull request merged**
