### PR TITLE
Added implementation of an absolute_name_scope and a unit test.

### PR DESCRIPTION
**Pull request by sleighsoft**
This PR adds a new `name_scope` called `absolute_name_scope` which builds on `name_scope` but allows reusing `name_scope`s without creating a new `name_scope` which is normally uniquified by adding a `_N`.
Based on the discussion in https://github.com/tensorflow/tensorflow/issues/9545

### CODE REVIEW

**Comment by skye** [comment]
I believe this behavior is already implemented if you append "/" to the argument of `name_scope`: https://www.tensorflow.org/api_docs/python/tf/Graph#name_scope

Unfortunately this isn't documented in `tf.name_scope`: https://www.tensorflow.org/api_docs/python/tf/name_scope
PRs welcome for this :)

Can you check if adding "/" works for your use case?

**Comment by sleighsoft** [comment]
No, this does not work right now without doing the same approach that is build into this PR.

Running the following code for example asserts the following:
#1 will actually be created as `abs_inner/FloatOutput`
#2 will actually be crated as `abs_inner/FloatOutput_1`

```python
g = ops.Graph()
    with g.as_default():
      with g.name_scope('abs_outer/'):
        with g.name_scope('abs_inner/'):
          print(g.create_op("FloatOutput", [], [dtypes.float32]).name) #1
      with g.name_scope('abs_outer/'):
        with g.name_scope('abs_inner/'):
          print(g.create_op("FloatOutput", [], [dtypes.float32]).name) #2
```

**Comment by skye** [comment]
Ah I see. I think it's intended to be used more like this:
```python
with tf.name_scope("outer"):
    with tf.name_scope("inner") as inner_scope:
        print(tf.constant(1))
with tf.name_scope(inner_scope):
    print(tf.constant(1))
```
This prints:
outer/inner/Const:0
outer/inner/Const_1:0

I'm hesitant to expose a new API endpoint for doing the same thing, especially since you might get unintended behavior with `absolute_name_scope` if there's a regular `name_scope` somewhere in the stack. Could you save the scope and re-use it as shown above?

**Comment by sleighsoft** [comment]
I know the intentions, but this forces you to carry around the `name_scope` object, which is not necessary when using `variable_scopes`.

**Comment by sleighsoft** [comment]
Alternativ, add a parameter to `name_scope` which makes it behave like the suggestion I made.

**Comment by skye** [comment]
Regarding the inconsistency with `variable_scope`, we're deprecating `variable_scope` in TF 2.0 in favor of a more object-oriented approach (see [this RFC](https://github.com/tensorflow/community/blob/master/rfcs/20180817-variables-20.md)). So I'm still not convinced we should add this API -- it would be more convenient in some situations, but also could lead to confusion and is one more API endpoint.

@alextp @asimshankar do you have an opinion?

**Comment by sleighsoft** [comment]
If the trend is more towards being object-oriented, then I agree that this might not be relevant.

**Comment by alextp** [comment]
variable_scopes are not a part of tf2, yes. Name scopes are still mostly as a way of making your tensorboard prettier.

**Comment by sleighsoft** [comment]
As such I intended this and referenced the issue. I just want to know if I should put more effort into this or if it will be trashed. I find it useful to have a cleaner tensorboard and am happy to share.

**Comment by skye** [comment]
Hi @sleighsoft, sorry for the delay. My opinion is that we should keep the API small and encourage the object-oriented technique, so I'm not gonna sign off on this. The "API review" means that someone else tasked specifically with reviewing API changes should take a look though, so we can get a second opinion. Everyone's busy with the 2.0 effort right now, so that's why it's taking a while. Thanks for your patience.

**Comment by josh11b** [comment]
For tf-api review:

I added a comment on the associated issue, which I've copied here:

The normal TensorFlow way to handle using the same scope in two places is:

```
    with tf.name_scope('outer'):
      with tf.name_scope('inner') as scope:
        print(tf.constant(1)) # Will print outer/inner/Const:0
    with tf.name_scope(scope):
      print(tf.constant(1)) # Will print outer/inner/Const_1:0
```

**Comment by sleighsoft** [comment]
Hey @josh11b,
@skye mentioned that very same thing above. The whole point of my pull request is to allow you to open up that very same `name_scope` without having to carry around the `name_scope` object.
I myself find this useful because it allows me to group operations logically in tensorboard without blowing up my code by passing around `name_scope` objects.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @skye: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @skye: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by karmel** [comment]
The paradigm we are moving towards in 2.0 is carrying around the Python objects, as per @josh11b 's comment above. In this case, as a workaround, you should be able to create a name scope function in your own code that tracks global namescopes. Closing given that workaround.

**Pull request closed without merging**
