### PR TITLE
 Fixes for Python3 Raspberry Pi CI Build

### PR DESCRIPTION
**Pull request by petewarden**
Passes a needed environment variable through to the build script.

### CODE REVIEW

**Comment by petewarden** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by petewarden** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Retrying, as we had a breakage.
Jenkins, test this please.

**Comment by petewarden** [comment]
Jenkins, test this please (Mac OS failure seems unrelated)

**Comment by petewarden** [comment]
Jenkins, test this please.
Linux CPU Tests (Python 3) fails on //bazel_pip/tensorflow/contrib/estimator:replicate_model_fn_test, which seems unrelated to this change.
MacOS CPU Tests times out on //tensorflow/python/kernel_tests:slice_op_test, which also seems unrelated.

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
I think all the above are existing failures. none of them should be related to your change.

**Comment by petewarden** [comment]
Jenkins, test this please. (It's the same tests failing again)

**Pull request merged**
