### PR TITLE
Update TOSA MLIR legalization documentation for current code

### PR DESCRIPTION
**Pull request by armkevincheng**
Signed-off-by: Kevin Cheng <kevin.cheng@arm.com>

### CODE REVIEW

**Comment by armkevincheng** [comment]
Sorry that I should but I forgot to add @stellaraccident and @rsuderman as reviewers when I create the pull request.

**Comment by sjarus** [comment]
A quick note - these are just cleanups of the legalization document matching current code. There are new legalizations and supporting documentation updates to follow in further PRs.

**Review by stellaraccident — APPROVED** [review]
Thank you for the doc updates. LGTM

**Comment by armkevincheng** [comment]
Windows Bazel check seems failing. But I don't think there's any possibility that this change would affect that and causes the error. Is this a outrage on the CI system?

**Pull request merged**
