### PR TITLE
[Intel MKL] unit test for bfloat16 on addN, relu, gelu etc

### PR DESCRIPTION
**Pull request by noim210**

### CODE REVIEW

**Comment by gbaned** [comment]
@noim210  Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@noim210  Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
