### PR TITLE
Branch 179953488

### PR DESCRIPTION
**Pull request by ekelsen**
push

### CODE REVIEW

**Comment by ekelsen** [comment]
@tensorflow-jenkins test this please

**Review by yifeif — APPROVED** [review]

**Comment by yifeif** [comment]
@martinwicke looks like the PR we pulled in failed the cla check even though the original PR passed. Do you know if there is any way around this?

**Comment by martinwicke** [comment]
Hmm... I fear this will be a persistent problem. Let's talk to CLABot team about how to fix this. Until then, the way around this is admin privileges.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
