### PR TITLE
Remove autoencoder estimator

### PR DESCRIPTION
**Pull request by terrytangyuan**
Reasons for removal:
- I created this one long time ago but it's not working anymore since the API has been evolved quite a bit. It causes confusion for users. 
- Better and more flexible API needed to be figured out in order to support different types of autoencoders, e.g. RNN/LSTM, etc. Or perhaps users can just create their own custom models.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@tensorflow-jenkins Test this please

**Comment by pwaller** [comment]
@terrytangyuan Ha! I had just started using `TensorFlowDNNAutoencoder` successfully. Can you point me at a good alternative?

**Comment by terrytangyuan** [comment]
You can provide your own `model_fn` and pass it to `Estimator`. You can take a look at what I have removed. Feel free to submit a PR for more flexible APIs in your mind.

**Comment by pwaller** [comment]
@terrytangyuan I'm struggling in particular to figure out how to get the [`generator()`](https://github.com/tensorflow/tensorflow/blob/37256f4857cdadefa09e0505f4acc91ffbf626e2/tensorflow/contrib/learn/python/learn/estimators/autoencoder.py#L92-L100) method to work, since the estimator now lacks a `._session`.

Where do I find an appropriate session? I guess I want to use `Estimator._infer_model` or `Estimator.evaluate`, but I'm a bit tangled here. I can't figure it out what I need to pass from the tf.learn docs.

**Comment by terrytangyuan** [comment]
Perhaps my blog post could help you understand a bit more: http://terrytangyuan.github.io/2016/07/08/understand-and-build-tensorflow-estimator/

We switched to use [SessionRunHook](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/session_run_hook.py) in Estimator which is why you cannot find the `._session`. 
This does require some reading of the source code instead of just reading from the docs. Hope this helps.

**Comment by pwaller** [comment]
The blog post doesn't mention SessionRunHook, can you point me at an example which uses it?

In particular, it's not clear how (before it was removed) TensorFlowDNNAutoencoder maintained state between `fit` and `transform`, and how to hook this up with SessionRunHook.

**Comment by terrytangyuan** [comment]
You can find some usages in tests. The blog post is pretty old to the speed
of development of TF.

**Pull request merged**
