### PR TITLE
Export `local_conv1d`/`local_conv2d` in `tf.keras.backend`

### LINKED ISSUE #25546: local_conv1d and local_conv2d are missing from the tensorflow.keras.backend namespace.
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Keras-team/keras provides `local_conv1d` and `local_conv2d` in `keras.backend`. tf.keras doesn't expose them. It's a compatibility issue between keras and tensorflow.keras. See https://keras.io/backend/ .

**Will this change the current api? How?**

It will add two functions to `tensorflow.keras.backend`

**Who will benefit with this feature?**

In keras-contrib, we expect keras and tf.keras to have the same public API. If the two are not compatibles, there are things that we can't do. 

**Any Other info.**

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #25546 where
there is a mismatch between `tf.keras.backend` and `keras.backend`
for `local_conv1d`/`local_conv2d`.

This fix exports `local_conv1d`/`local_conv2d` in `tf.keras.backend`,
so that `tf.keras.backend` is compatible with `keras.backend`
(https://keras.io/backend/).

This fix fixes #25546.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by fchollet — DISMISSED** [review]
Thanks for the PR. LGTM

**Comment by yongtang** [comment]
Ping @rthadur Any update on this one? Really would like to see the api consistency between `keras` and `tf.keras`.

**Comment by rthadur** [comment]
> Ping @rthadur Any update on this one? Really would like to see the api consistency between `keras` and `tf.keras`.

Thank you @yongtang ,working on it , waiting for status to be reported

**Comment by rthadur** [comment]
@yongtang could you please fix build errors

**Comment by yongtang** [comment]
Thanks @rthadur for the help. The PR has been updated and all tests passed now.

**Pull request merged**
