### PR TITLE
make toco build for android

### PR DESCRIPTION
**Pull request by freedomtan**
for ARMv8
`
bazel build --config android_arm64 --cxxopt=-std=c++11 --linkopt="-llog" --linkopt=-pie //tensorflow/contrib/lite/toco:toco   --config monolithic
`
for ARMv7a
`
bazel build --config android_arm --cxxopt=-std=c++11 --linkopt="-llog" --linkopt=-pie //tensorflow/contrib/lite/toco:toco   --config monolithic
`

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by freedomtan** [comment]
@andrehentz To provide on-device model conversion, so that it would be possible to download non-tflite models and do some device-specific conversion in the future :-)

**Review by andrehentz — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 15 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by petewarden** [comment]
This breaks the Raspberry Pi build, since `#ifdef __ARM_ARCH_7A__` isn't sufficient to identify a platform that does or doesn't have double() already defined. Requesting a rollback, this could be re-done with an extra guard for Android-only.

**Pull request merged**
