### PR TITLE
Update feature_column.py

### PR DESCRIPTION
**Pull request by yunjiangster**
Allow multiple calls of input_layer to have the same root variable scope.

### CODE REVIEW

**Comment by ymodak** [comment]
@yunjiangster Can you please sign the CLA tp procedd with PR? Please let me know if you are facing any issues. Thanks!

**Comment by ymodak** [comment]
@yunjiangster Gentle reminder to sign CLA. We would like to see progress with this PR. Please let me know if you are facing any issues. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
