### PR TITLE
Add OpKernel of QuantizedReluX

### LINKED ISSUE #20514: No OpKernel was registered to support Op 'QuantizedReluX' with these attrs
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary using conda
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 3.5.2
- **CUDA/cuDNN version**: 8.0/7.0
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **GPU model and memory**: Quadro M2000M/ 4GB
- **Exact command to reproduce**:
Tried to use quantized_relu_x and it doesn't work
I have already used quantized_conv2d and quantized_max_pool, both of them works fine, but have only problem when I use quantized_relu_x

### Describe the problem
Other two quantized kernels QuantizedRelu and QuantizedRelu6 seem to have defined but QuantizedReluX appears to be missing, although three of them are registered together in core/ops/nn_ops.cc file

### Source code / logs
Error message that I am getting is as follows:
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'QuantizedReluX' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  >no registered kernels

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #20514 where no OpKernel was registered to support Op `QuantizedReluX`.

This fix add the OpKernel for `QuantizedReluX`.

This fix fixes #20514.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by qlzh727** [comment]
Ping Peter again for review.

**Comment by qlzh727** [comment]
Also adding Josh for review.

**Comment by qlzh727** [comment]
Ping @petewarden for review.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 89 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 104 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 119 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by petewarden** [comment]
Sorry for the delayed response. We're no longer actively working on the Quantized* ops within mainline TensorFlow, so closing this one.

**Pull request closed without merging**
