### PR TITLE
Rename Tensor "summary_op" to "summary" in the 101 tutorial

### PR DESCRIPTION
**Pull request by tijmentieleman**
"summary_op" is a Tensor, so it's incorrectly labeled as an op. This change renames it to "summary", and makes the corresponding changes in the explanation.

### CODE REVIEW

**Comment by josh11b** [comment]
Looks good to me.

**Comment by danmane** [comment]
LGTM too :)

**Comment by josh11b** [comment]
@tensorflow-jenkins test this please

**Comment by tijmentieleman** [comment]
One of the test errors is "No space left on device". I don't feel that I understand the testing system well enough to comment intelligently, though I'm speculating that the error is not in the code change because it's just a variable rename. Who could take a look and diagnose the problem?

**Comment by vrv** [comment]
known infra issues, merged since all other tests passed

**Pull request merged**
