### PR TITLE
Add concat_v2 to array_ops.py. Also, add gradient support for concat_…

### PR DESCRIPTION
**Pull request by gunan**
…v2 op.

Change: 139839646

We just need this for final r0.12, too late for rc1.

### CODE REVIEW

**Comment by gunan** [comment]
DONOTMERGE until r0.12 is released.

**Comment by gunan** [comment]
I mean, rc1

**Comment by gunan** [comment]
This change is good to go. Please approve and merge whenever you have time.
Jenkins, test this please.

**Comment by martinwicke** [comment]
rc1 is out, should this be merged now?

**Comment by gunan** [comment]
yes please. we can go ahead as all the rc1 branch is merged back into master

**Review by martinwicke — APPROVED** [review]
We have to make sure to undo all this for final.

**Comment by gunan** [comment]
Do we have a tracker to follow up undoing these?
I am 90% sure that we will forget undoing these without a tracker.

**Comment by martinwicke** [comment]
@aselle Do you? We have a list, but I wouldn't call it a tracker.

**Comment by aselle** [comment]
What aspect do we want to undo? You mean remove the _v2 names?

**Pull request merged**
