### PR TITLE
[Intel MKL] set build 2.0 as default in Dockerfile.devel-mkl

### PR DESCRIPTION
**Pull request by guizili0**
We use three file to build the TF docker images in the derectory tensorflow/tools/ci_build/linux/mkl/.
We set build 2.0 as default in both set-build-env.py and build-dev-container.sh.
But set disable 2.0 as default in Dockerfile.devel-mkl.
In this situation, we always disable 2.0 build.

This PR fix this bug that we can build the right TF 2.0 image.

### CODE REVIEW

**Comment by guizili0** [comment]
@angersson Can you help to take time to review this? thanks you.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Review by penpornk — COMMENTED** [review]
Thank you for your PR!
Do you have to change the default value of `BUILD_TF_V2_CONTAINERS` in `build-dev-container.sh` from `no` to `yes` as well?

**Comment by guizili0** [comment]
@penpornk thanks for for comments, I have update it, please help to check.
thanks.

**Review by penpornk — APPROVED** [review]
Thank you for the changes!

**Pull request merged**
