### PR TITLE
Fix Bazel CI / TensorFlow project

### PR DESCRIPTION
**Pull request by laszlocsomor**
See https://github.com/bazelbuild/bazel/issues/2892

### CODE REVIEW

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by vrv** [comment]
Unfortunately there is a merge conflict, can you try resolving the conflict?

**Comment by laszlocsomor** [comment]
@vrv : Done, PTAL

@martinwicke : FYi @meteorcloudy is on vacation, that's why I worked on this bug in the first place

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
