### PR TITLE
make benchmark_model for TFLite build

### PR DESCRIPTION
**Pull request by freedomtan**
It doesn't build for Android and Ubutu box. Make it build.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 15 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by WenguoLi** [comment]
build failed!

ERROR: /home/apuser/deeplearning/tensorflow/tensorflow-master/tensorflow/core/BUILD:1243:1: C++ compilation of rule '//tensorflow/core:android_tensorflow_lib_lite' failed (Exit 1)
tensorflow/core/util/port.cc:19:10: fatal error: 'cuda/include/cuda.h' file not found
         ^
1 error generated.
Target //tensorflow/contrib/lite/tools:benchmark_model failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 97.980s, Critical Path: 6.79s
FAILED: Build did NOT complete successfully

**Comment by WenguoLi** [comment]
hi, @freedomtan ,
Thanks!
How to be disable CUDA ?

**Comment by freedomtan** [comment]
re-run ./configure or edit .tf_configure.bazelrc

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 22 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by freedomtan** [comment]
benchmark_model was updated and fixed. close this.

**Pull request closed without merging**
