### PR TITLE
Branch 160538962

### PR DESCRIPTION
**Pull request by drpngx**

### CODE REVIEW

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by yifeif — COMMENTED** [review]
bad merge?

**Comment by drpngx** [comment]
Jenkins, test this please.

Yeah, somehow that BUILD rule was duplicated.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Yay! All passed.

**Review by yifeif — APPROVED** [review]
Thanks for fixing all the conflicts/errors!

**Pull request merged**
