### PR TITLE
[CMake] Test existence of python entries

### PR DESCRIPTION
**Pull request by Androbin**
Split from #15166
@mrry Friendly ping,

### CODE REVIEW

**Comment by Androbin** [comment]
@mrry Friendly ping.

**Review by mrry — APPROVED** [review]

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
@Androbin could you pull rebase and push again?

**Comment by Androbin** [comment]
Nearly forgot about the other change set. Should be fine now.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
`file_block_cache_test` is flaky, ignoring.

**Comment by Androbin** [comment]
@drpngx Seems like the "Sanity Checks" and the "Windows CMake Tests" are stuck.

**Comment by drpngx** [comment]
Jenkins, test this please.

Yeah, it looks like there is some problem with Windows cmake. @yifeif might
know something about it

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
All tests pass (including sanity), ignoring `ci.tensorflow.org` status.

**Pull request merged**
