### PR TITLE
Backport rel/ build layout to r2.1

### PR DESCRIPTION
**Pull request by angerson**
Files copied from their current state on the 2.1 branch.

### CODE REVIEW

**Review by Dynmi — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
@Dynmi unfortunately, your approval has no merging power

**Review by mihaimaruseac — APPROVED** [review]

**Comment by Dynmi** [comment]
> @Dynmi unfortunately, your approval has no merging power

Oh, I want to work with tensorflow, how can I join you?

**Comment by mihaimaruseac** [comment]
@Dynmi: For contributing, see https://www.tensorflow.org/community/contribute

**Comment by Dynmi** [comment]
> @Dynmi: For contributing, see https://www.tensorflow.org/community/contribute

I see. Thanks. But my intention is to be one of members of tensorflow repository😬. How should I join you?

**Comment by mihaimaruseac** [comment]
Keep contributing and at one point you will be given approval powers.

Or join the team at Google :)

**Comment by Dynmi** [comment]
> Keep contributing and at one point you will be given approval powers.
> 
> Or join the team at Google :)

Thanks for your reply.
I will keep contributing at my best. Of course, if I have the opportunity, I will definitely apply to join the team at Google!  :)

**Pull request merged**
