### PR TITLE
Mention fix for building on 16.04 in Troubleshooting

### PR DESCRIPTION
**Pull request by yaroslavvb**
I ended up using @fayeshine fix from https://github.com/tensorflow/tensorflow/pull/2073 to get tensorflow building on Ubuntu 16.04, add a mention to this work-around under "Linux Issues"

### CODE REVIEW

**Comment by jendap** [comment]
@yaroslavvb do you have a problem with it? I have just build on 16.04 without issues. CI build is coming.

**Comment by yaroslavvb** [comment]
Yes, I couldn't build after upgrading my Ubuntu last week. The upgrade changed gcc to version 
gcc version 4.9.3 (Ubuntu 4.9.3-13ubuntu2)

**Comment by girving** [comment]
@jendap: Assigning you since you commented; feel free to change.

**Comment by vrv** [comment]
As mentioned on the issue, we should probably recommend upgrading to cuda 8.0 instead.

**Pull request closed without merging**
