### PR TITLE
Added missing files to BUILD.

### LINKED ISSUE #50145: Building current master fails due to missing files
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: git/master
- Python version: 3.9
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 4.1.0
- GCC/Compiler version (if compiling from source): 11
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

Building TF from the current source on GH fails due to missing files (all from `llvm-openmp`):
`tools.pm`
`kmp.h`
`kmp_platform.h`
`kmp_os.h`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
My build command was as follows:
```bash
bazel build  --config=mkl -config=nogcp --config=nonccl  -c opt --copt=-march=native --copt=-O3 -s //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### PR DESCRIPTION
**Pull request by eli-osherovich**
Fixes #50145

### CODE REVIEW

**Comment by yimeisun123** [comment]
FYI- when "--spawn_strategy=sandboxed" is specified in the ".bazelrc" file (commit 259399ee, previous commit 9171e39a2), build with "config=mkl" fails in llvm_openmp. The changes in this PR fix this build issue.

**Comment by eli-osherovich** [comment]
@mihaimaruseac  friendly ping. 
Can you please review this PR. 

Thank.

**Comment by eli-osherovich** [comment]
@gbaned 
Is there any chance this PR get reviewed?

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Apologies for the delay. OOO and hiring took most of my time these past days.

**Comment by eli-osherovich** [comment]
Thanks a lot @mihaimaruseac 
There are some failures on MacOS, but I do not think these are related to the PR. It looks like some global flags defined twice....

```
FAIL: MLIR tf_saved_model :: basic_v1_no_variable_lifting.py (1 of 1)
******************** TEST 'MLIR tf_saved_model :: basic_v1_no_variable_lifting.py' FAILED ********************
Script:
--
: 'RUN: at line 16';   /Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/org_tensorflow/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting | /Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/llvm-project/llvm/FileCheck /Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/org_tensorflow/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py
--
Exit Code: 2

Command Output (stderr):
--
2021-06-15 13:43:12.632076: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/count
2021-06-15 13:43:12.632150: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/count
2021-06-15 13:43:12.632169: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/api
2021-06-15 13:43:12.632187: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/api
Traceback (most recent call last):
  File "/Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/org_tensorflow/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py", line 24, in <module>
    from tensorflow.compiler.mlir.tensorflow.tests.tf_saved_model import common_v1
  File "/Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/org_tensorflow/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/common_v1.py", line 34, in <module>
    flags.DEFINE_string('save_model_path', '', 'Path to save the model to.')
  File "/Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/absl_py/absl/flags/_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/absl_py/absl/flags/_defines.py", line 82, in DEFINE
    flag_values, module_name)
  File "/Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/absl_py/absl/flags/_defines.py", line 104, in DEFINE_flag
    fv[flag.name] = flag
  File "/Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/absl_py/absl/flags/_flagvalues.py", line 430, in __setitem__
    raise _exceptions.DuplicateFlagError.from_flag(name, self)
absl.flags._exceptions.DuplicateFlagError: The flag 'save_model_path' is defined twice. First from tensorflow.compiler.mlir.tensorflow.tests.tf_saved_model.common, Second from tensorflow.compiler.mlir.tensorflow.tests.tf_saved_model.common_v1.  Description from first occurrence: Path to save the model to.
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/llvm-project/llvm/FileCheck /Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py.test.runfiles/org_tensorflow/tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/basic_v1_no_variable_lifting.py
```

**Comment by eli-osherovich** [comment]
@mihaimaruseac 
Now it worked!

P. S.
On a side note -- it might be my bad luck, but pretty much every commit has some unrelated failures.... It seems that the internal TF checks are not that strict. Namely, some CLs that cause build errors somehow made their way into the code...

**Comment by mihaimaruseac** [comment]
We don't run Windows and MacOS presubmits internally as they take too much time. We have buildcop rotations where people should watch postsubmit builds and quickly turn them back to green but sometimes this process gets ignored/delayed

**Pull request merged**
