### PR TITLE
Fix flaky test: Add small absolute tolerance so test with expected zero outputs do not fail.

### PR DESCRIPTION
**Pull request by rmlarsen**

### CODE REVIEW

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by gunan** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
FYI, the status of the mac PR test is not shown below but can be seen at: http://ci.tensorflow.org/job/tensorflow-pull-requests-multijob/1662/

**Comment by sguada** [comment]
Thanks for the fix

**Pull request merged**
