### PR TITLE
Rename libtensorflowlite.a to libtensorflow-lite.a

### PR DESCRIPTION
**Pull request by mattn**
LIB_NAME is defined as libtensorflow-lite.a in tensorflow/lite/tools/make/Makefile.

### CODE REVIEW

**Comment by thaink** [comment]
What is the main purpose of this renaming?

**Comment by mattn** [comment]
https://github.com/search?q=%22libtensorflow-lite%22&type=Code

The library name is already assigned as libtensorflow-lite.a. And libtensorflow-lite.a is already used for many projects.

**Comment by mattn** [comment]
This is fixing not a proposal.

**Comment by thaink** [comment]
@terryheo Do we have any specific reasion to name it as tensorflowlite?

**Review by terryheo — APPROVED** [review]
LGTM

**Pull request merged**
