### PR TITLE
[TF-numpy] Add docstring in `np.random`

### PR DESCRIPTION
**Pull request by archsyscall**
Thank you

### CODE REVIEW

**Review by wangpengmit — COMMENTED** [review]
We rely on the `@np_utils.np_doc` decorator to auto-attach numpy docstrings to tfnp functions. Writing these docstrings manually is tedious and may diverge from numpy.

**Comment by gbaned** [comment]
@marload  Can you please check @wangpengmit's comments and keep us posted ? Thanks!

**Comment by gbaned** [comment]
@marload  Any update on this PR? Please. Thanks!

**Comment by wangpengmit** [comment]
This PR is probably safe to close, if @marload you don't object.

**Comment by gbaned** [comment]
@marload Can you please check @wangpengmit's comments and keep us posted ? Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
