### PR TITLE
 optimize method fold_batch_norms, speed up this method  

### PR DESCRIPTION
**Pull request by shubham769**
init method
the code of removing will cost so much time

use a new piece of code to replace the init code
it will speed up.

### CODE REVIEW

**Comment by rthadur** [comment]
@shubham769 thank you , is it possible to add a test cases around new changes.

**Comment by shubham769** [comment]
> @shubham769 thank you , is it possible to add a test cases around new changes.

Not actually, but these changes will not affect previous functionality

**Comment by SmokerX** [comment]
https://github.com/tensorflow/tensorflow/pull/29421

are you kidding me?

**Comment by SmokerX** [comment]
How dare you to steal my code?
https://github.com/tensorflow/tensorflow/pull/29382/files
How stupid you are to steal my original code which I said there is something wrong.
@google-admin

**Comment by SmokerX** [comment]
@rthadur 
You can pay attention to the time you ask him to test case, and then after you ask him, he actually ran to my pr and asked me. I have never seen such a brazen man.

**Pull request closed without merging**
