### PR TITLE
Make summarize_graph recognize VariableV2

### PR DESCRIPTION
**Pull request by snnn**
#8054

### CODE REVIEW

**Comment by dandelionmane** [comment]
Can you add a test please?

**Review by petewarden — APPROVED** [review]
It would be nice to have a test, but since it's my fault I didn't provide one originally it shouldn't be a blocker I think. Thanks for this update!

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Pull request merged**
