### PR TITLE
little_modify

### PR DESCRIPTION
**Pull request by lizuoyue**
Modify the list '[' ']' to the tuple '(' ')'

### CODE REVIEW

**Comment by jhseu** [comment]
Please handle the CLA before we can code review. Thanks!

**Comment by eigen2017** [comment]
u need to pass cla ~ i was there, now i passed , just follow me:
#14867

**Comment by drpngx** [comment]
@lizuoyue if you signed the CLA, please reply "I signed it!" to this thread. Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
Closing for now. Let us know if you have updates.

**Pull request closed without merging**
