### PR TITLE
Fix issues caused by the library update

### PR DESCRIPTION
**Pull request by yesanton**
Fixes were made to eliminate deprecated references in the file caused by library update. Now the file compiles as expected.

### CODE REVIEW

**Comment by yesanton** [comment]
I signed it!

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
The tutorial test on ptb_world_lm still errored out:

```
Traceback (most recent call last):
  File "ptb_word_lm.py", line 369, in <module>
    tf.app.run()
  File "/workspace/pip_test/venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 331, in main
    m = PTBModel(is_training=True, config=config, input_=train_input)
  File "ptb_word_lm.py", line 141, in __init__
    (cell_output, state) = cell(inputs[:, time_step, :], state)
  File "/workspace/pip_test/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 767, in __call__
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/workspace/pip_test/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 292, in __call__
    concat = _linear([inputs, h], 4 * self._num_units, True, scope=scope)
  File "/workspace/pip_test/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 846, in _linear
    raise ValueError("linear is expecting 2D arguments: %s" % shapes)
ValueError: linear is expecting 2D arguments: [TensorShape(None), TensorShape([Dimension(20), Dimension(2)])]
```

https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/2931/console

**Comment by gunan** [comment]
@yesanton looks like the fix did not work.
Could you take another look?

**Comment by yesanton** [comment]
@gunan yes, I will check again.

**Comment by gunan** [comment]
#6200 fixes the ptb_word_lm issue. Closing this pr.

**Pull request closed without merging**
