### PR TITLE
[XLA] add a postpone fusion mechanism

### PR DESCRIPTION
**Pull request by nouiz**
[XLA] add a postpone fusion mechanism to fuse downcast convert into producer instead of consumer.

@thomasjoerg

### CODE REVIEW

**Review by thomasjoerg — DISMISSED** [review]
Approving this for import. I'll report back with benchmark and testing results.

**Review by thomasjoerg — DISMISSED** [review]

**Comment by nouiz** [comment]
I rebased this PR to fix a new conflict.

**Review by d0k — APPROVED** [review]
I'll re-run our internal benchmark suite

**Comment by sanjoy** [comment]
Update so that this does not look stale: the internal benchmark suite detected a regression and NVIDIA now has the HLO IR needed to reproduce this problem.

**Comment by sanjoy** [comment]
Marking as "needing changes" to get this off my queue.

**Review by sanjoy — CHANGES_REQUESTED** [review]
We're working to address some perf regressions.

**Comment by rthadur** [comment]
@sanjoy gentle ping if you have any update on this ?

**Comment by sanjoy** [comment]
@thomasjoerg @nouiz What is the current status here?  I know we discussed this PR over email, did we decide to go ahead with this design?

**Comment by nouiz** [comment]
The conclusion of the email discussion was to try to fuse manually. Tried that, but got other problems. Now working on something else. Thomas started some works that could make this approaches working again, but it causes a regression that prevent him from merging this now. So nothing is sure of what will happen except that it probably won't be done rapidly.

We can close this PR and reopen/open a new PR if we decide to continue this.

**Comment by nouiz** [comment]
I do not plan to work on this shortly. So I'll close this PR.

**Pull request closed without merging**
