### PR TITLE
Add compression support for TextLineReader

### LINKED ISSUE #14593: TextLineReader is missing compression option (see TFRecordReader)
`tf.TextLineReader` does not currently provide a way to read GZIP encoded files

This option exists in `TFRecordReader`:
```
options = tf_record.TFRecordOptions(TFRecordCompressionType.GZIP)
reader = io_ops.TFRecordReader(name="test_reader", options=options)
```

It would be great to be able to ingest gzipped files into the TextLineReader as well:
```
reader = tf.TextLineReader(compression_type="gzip")
```

This `compression_type` argument could pass down to

```
rr = gen_io_ops._text_line_reader_v2(skip_header_lines=skip_header_lines, name=name, compression_type=compression_type)
```
 in the same way the TFRecordReader passes down to `_tf_record_reader_v2`: 
```rr = gen_io_ops._tf_record_reader_v2(name=name, compression_type=compression_type)```

Which would seem to require implementing compression here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/text_line_reader_op.cc

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #14593 where it was not possible to process compressed TextLineReader.

This fix add compression support for TextLineReader, similar to TFRecordReader.

Additional tests have been added.

This fix fixes #14593.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by martinwicke** [comment]
@rohan100jain can you take a look?

**Comment by asimshankar** [comment]
(From API review)

Is this still required after https://github.com/tensorflow/tensorflow/pull/15132 ? Once that PR is merged, then it seems like the behavior of this PR will be the same as connecting the existing `TextLineReader` op to the output of a `DecodeCompressed` op?

Are we missing something?

**Comment by yongtang** [comment]
@asimshankar Yes I think with `decode_compressed` then most of the compression processing could be considered as apply the op to the input/output.

This PR was trying to address the issue raised #14593 which was early. 

Later on #14887 was opened, so PR #15132 was created.

At the moment there are several ops that support option of compression:
```
TextLineDataset
TFRecordDataset
TFRecordReader
TFRecordReaderV2
FixedLengthRecordReaderV2
```

So there might be some overlap/inconsistency on which method/option to use when dealing with compressions.

Maybe there could be some consolidation for that, or just leave old method alone if the API could not change any more?

I am open either way. Or we could just close this PR for now.

**Comment by yifeif** [comment]
@yongtang do we still plan to proceed with this PR now that #15132 is in?

**Comment by yongtang** [comment]
I think I can close this PR. If there is a compelling need to add the option I can reopen, though don't see a big need for now. Thanks all for the help! 👍

**Pull request closed without merging**
