### PR TITLE
Remove unused header

### PR DESCRIPTION
**Pull request by 372046933**
`tensorflow/core/lib/core/errors.h` already included

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
I think the two headers are different.

We have a clang format based tool that reorders imports, so the only way these two are duplicated is if one is forwarding the other (pending deprecation) or they are exactly the same file.

**Comment by 372046933** [comment]
Does it mean that `tensorflow/core/lib/core/errors.h` is forwarding  `tensorflow/core/platform/errors.h`, but these two are not considered as duplicate?

**Comment by mihaimaruseac** [comment]
Looking at the last commit that [touched `core/errors.h`](https://cs.opensource.google/tensorflow/tensorflow/+/22141f949e4ce29bf64b8885f17d27af7e470f86) (22141f949e4ce29bf64b8885f17d27af7e470f86) it seems we should instead remove `core/errors.h`.

Partial migration

**Comment by 372046933** [comment]
Yes, 22141f9 seems just deals with `errors.h`, yet there are many other components that got moved from `tensorflow/core/lib/` to `tensorflow/core/platform`

**Comment by 372046933** [comment]
@mihaimaruseac Could you have a look at the PR? IMHO,  header files in  `tensorflow/core/lib/core` will be moved th `tensorflow/core/platform` in the long run. This PR deals with `tensor_shape.h` and `tensor_shape.cc`

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Was OOO in the past 10 days, sorry for the delay

**Pull request merged**
