### PR TITLE
Bidirectional rnn now returns forward and backward output states, upd…

### PR DESCRIPTION
**Pull request by lucaswiser**
…ated tests, tests pass. Updated my email with the right email this time!

### CODE REVIEW

**Comment by vrv** [comment]
@lukaszkaiser, @ludimagister can you take a look (once this is updated to master)?

**Comment by lukaszkaiser** [comment]
This change looks good, just needs a merge.

**Comment by lucaswiser** [comment]
great! One thing I forgot to do was update the docstring. How do we want to do that?

**Comment by Mistobaan** [comment]
@lucaswiser just change the text in the output docstring https://github.com/lucaswiser/tensorflow/blob/bidirectional-rnn-state/tensorflow/python/ops/rnn.py#L295

**Comment by lucaswiser** [comment]
OK the docstring has been updated

**Comment by lukaszkaiser** [comment]
Let's get it in, what's missing?

**Comment by lucaswiser** [comment]
I think it's all set to go.

**Comment by lukaszkaiser** [comment]
I still see "This branch is out-of-date with the base branch. Merge the latest changes from master into this branch." just above this comment. Are you sure it's all merged?

**Comment by vrv** [comment]
Thanks for doing this -- just a few comments from my side, and then if everything looks good, please squash the commits and we'll test and merge.

**Comment by vrv** [comment]
Don't worry about that, it just means we pushed a commit since the last
update.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by lucaswiser** [comment]
Ok commits are squashed. Should I merge master into the branch to update it or should someone else do that?

**Comment by vrv** [comment]
No need, as long as there are no conflicts we rebase for you.

@tensorflow-jenkins: test this please.  PLEASE.

**Comment by vrv** [comment]
Merged

**Pull request closed without merging**
