### PR TITLE
Add cpp version info/flag

### PR DESCRIPTION
**Pull request by bhack**
https://github.com/tensorflow/tensorflow/commit/8ea5ed0c392b329a3e0481a3f1f7b0ca86821b84#commitcomment-82094699 /cc @mihaimaruseac 

- [x] Expose in the wrapper/python

### CODE REVIEW

**Comment by bhack** [comment]
See also:
https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#how-to-i-set-the-c-dialect-used-to-build-abseil

https://github.com/tensorflow/serving/issues/1935

https://github.com/abseil/abseil-cpp/issues/606#issuecomment-576039324

**Review by mihaimaruseac — APPROVED** [review]

**Comment by bhack** [comment]
Do I have to run `bazel run tensorflow/tools/api/tests:api_compatibility_test  -- --update_goldens True` on my side or you will run it after the API change approval.

**Comment by bhack** [comment]
> Do I have to run `bazel run tensorflow/tools/api/tests:api_compatibility_test -- --update_goldens True` on my side or you will run it after the API change approval?

Done on  my side.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Has to be on your side, or the Pr imported manually.

**Comment by bhack** [comment]
@mihaimaruseac Do you know what was gone wrong in the `feedbacks/copybara` job?

**Comment by mihaimaruseac** [comment]
```
[tensorflow/python/client/tf_session_wrapper.cc:1188](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/python/client/tf_session_wrapper.cc?l=1188&ws=tap-prod-presubmit/210468660&snapshot=2):42: error: use of undeclared identifier 'TF_CXX_VERSION'
  m.def("get_cxx_version", []() { return TF_CXX_VERSION; });
```

**Comment by bhack** [comment]
> ```
> tensorflow/python/client/tf_session_wrapper.cc:1188:42: error: use of undeclared identifier 'TF_CXX_VERSION'
>   m.def("get_cxx_version", []() { return TF_CXX_VERSION; });
> ```

I cannot reproduce this locally/OSS. 
Do we need to run something specific when we change this file https://github.com/tensorflow/tensorflow/pull/57468/files#diff-b9e4766c0f0124421c09e4c012e29af59d4c218ee9163f0baa63bfd100a2720f ?

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
