### PR TITLE
standardize BUILD files format using buildifier

### PR DESCRIPTION
**Pull request by Mistobaan**
I just run `buildifier -mode=fix`find . -iname BUILD -type f`. 

`go get github.com/bazelbuild/buildifier` to install the tool.

I like to have one format for the build files. 
What is the general feeling about this ?

### CODE REVIEW

**Comment by martinwicke** [comment]
This is awesome. @gunan @caisq can we make this part of the ci-sanity? It causes all kinds of conflicts.

**Comment by gunan** [comment]
Maybe without the autofix option, but I agree that we should have this.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Actually, I was thinking about adding a test to cl-sanity that simply runs
buildifier and fails if any changes are suggested. The submitter can then
run it themselves to make sure it passes.

**Comment by Mistobaan** [comment]
I think a CI check would be sufficient, you can run the command with `-mode=check` to only check if the files are well formatted. 

buildifier -mode=check `find . -iname BUILD -type f`

**Pull request merged**
