### PR TITLE
Add SavedModel support to tfcompile

### PR DESCRIPTION
**Pull request by elibixby**
This might be a little bit of a hacky way to add support but it appears to work. Long term it would be better to make SavedModel a first class citizen.

### CODE REVIEW

**Comment by jhseu** [comment]
@tatatodd Friendly ping for review

**Comment by tatatodd** [comment]
Sorry for the delay.  FYI I'll be out of the office until after Labor Day 9/5.  I hope that you're not in a rush to get this in.

I'd taken a look previously, and as you say, the approach isn't super-clean.  So it'll take some time on the review.

**Comment by drpngx** [comment]
@tatatodd feel free to outline a better approach

**Comment by sb2nov** [comment]
@elibixby there seems to be some merge conflicts. Can you address those so this is ready for review again.

**Comment by elibixby** [comment]
@sb2nov Committed a merge resolving conflicts

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by tatatodd** [comment]
Sorry for the delay.  I fear the approach in this PR will be an overall maintenance burden.

@suharshs and I have discussed making SavedModel more of a first-class citizen in general, for all of our tools.  He plans to add a C++ library call to perform freeze_graph functionality.  Once that support is in, I'll update tfcompile to take SavedModel as input, and hook up a call to his C++ library to the rest of the compilation pipeline.  The advantage of this approach is that we won't need a pre-processing python script, and we won't need a separate tf_saved_model_library skylark rule.

@elibixby what do you think?

**Comment by carlthome** [comment]
> I'll update tfcompile to take SavedModel as input, and hook up a call to his C++ library to the rest of the compilation pipeline. The advantage of this approach is that we won't need a pre-processing python script, and we won't need a separate tf_saved_model_library skylark rule.

Yes, please.

**Comment by elibixby** [comment]
SGTM. This was just meant to be a stopgap to show people how to do it if support was a long way off. If this is on the horizon I'm happy closing this.

**Pull request closed without merging**
