### PR TITLE
Fix typos in python/training module.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by vincentvanhoucke** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
@tensorflow-jenkins, test this please.

**Comment by vrv** [comment]
(apparently our CI is down -- we'll look at this again when it's back up, sorry).

**Comment by vrv** [comment]
@tensorflow-jenkins, test this please

**Comment by martinwicke** [comment]
Thanks, this is great!

**Comment by dongjoon-hyun** [comment]
Thank you, @vincentvanhoucke , @vrv , and @martinwicke .

**Pull request merged**
