### PR TITLE
[Intel MKL] Upgrading to MKLDNN v0.20.1

### PR DESCRIPTION
**Pull request by nhasabni**

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for you PR!

**Comment by penpornk** [comment]
@nhasabni Seems like there's a merge conflict. Could you please help resolve it? Thank you!

**Comment by nhasabni** [comment]
@penpornk I've merged master into my branch without any conflicts. Pls take a look.

**Review by penpornk — APPROVED** [review]
Thank you!

**Pull request merged**
