### PR TITLE
Minor change in word2vec_basic tutorial

### PR DESCRIPTION
**Pull request by CastielWong**
Initial `count` with tuple instead of list for consistency, add `global data` in method `generate_batch()` to avoid misunderstanding.

### CODE REVIEW

**Comment by CastielWong** [comment]
I signed it.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @MarkDaoust: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by MarkDaoust** [comment]
Hi @CastielWong.

I removed the `global data` in python you can always read variables without a global declaration.
`data_index` only needs the `global` because it's being written to. So I reverted that line.

Thanks for taking the time to make a PR.

**Review by MarkDaoust — APPROVED** [review]

**Comment by CastielWong** [comment]
Ah~ Got it, thanks! @MarkDaoust :)

**Pull request merged**
