### PR TITLE
Deleted the TF copy of the tensor code

### PR DESCRIPTION
**Pull request by benoitsteiner**
Since  we're now pulling the tensor code directly from the eigen repository we don't need to keep a local copy anymore.

### CODE REVIEW

**Comment by martinwicke** [comment]
Jenkins, please test this.

**Comment by benoitsteiner** [comment]
I signed it

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Jenkins, test this please

**Comment by martinwicke** [comment]
Jenkins, test this please

**Comment by vrv** [comment]
martin: you need a period after "please" :)

@tensorflow-jenkins: test this please.

**Comment by martinwicke** [comment]
I need to change that regex, please.

**Comment by martinwicke** [comment]
Jenkins, retest this please

**Comment by martinwicke** [comment]
test this please.

**Comment by martinwicke** [comment]
retest this please.

**Pull request merged**
