### PR TITLE
Issue tensorflow#33840 in tf.image.ssim_multiscale

### PR DESCRIPTION
**Pull request by aakash30jan**
Fix for issue [tensorflow#33840](https://github.com/tensorflow/tensorflow/issues/33840) on tf.image.ssim_multiscale. #33840

### CODE REVIEW

**Comment by aakash30jan** [comment]
@googlebot I signed it!

**Comment by jsmeredith** [comment]
The issue (https://github.com/tensorflow/tensorflow/issues/33840) was reportedly fixed in the 2.5 release.  

I think we can abandon this pull request then -- but just let us know otherwise. Thanks!

**Comment by gbaned** [comment]
@aakash30jan Can you please check @jsmeredith's comments and keep us posted ? Thanks!

**Comment by aakash30jan** [comment]
@gbaned @jsmeredith, I just checked the gist mentioned by @sachinprasadhs in the issue ([#33840](https://github.com/tensorflow/tensorflow/issues/33840#issuecomment-845018896)) . The issue was reported to be closed based on this wrong gist. The issue still persists in Tensorflow 2.5,  [here](https://colab.research.google.com/gist/aakash30jan/7add0e61ea973844360cf569bf8dcffc/issue_33840.ipynb) is a proper gist to replicate the issue from what OP @AravindGanesh had mentioned.

**Comment by gbaned** [comment]
@jsmeredith  Can you please take a look on above comments from @aakash30jan. Thanks!

**Comment by aakash30jan** [comment]
@jsmeredith @gbaned The issue persists with TF v2.5 as confirmed by a [recent ](https://github.com/tensorflow/tensorflow/issues/33840#issuecomment-887361360) comment on the issue.

**Comment by jsmeredith** [comment]
Acknowledged -- looks like I have some notifications yet to set up.  Thanks so much for pinging again, I'll take a look!

**Comment by jsmeredith** [comment]
Hi!  I see some tests failing with this change, would you be able to fix those and update the CL?   (And double-check things like formatting, if it's possible to add a test which targets this fix, etc.)  Thanks!

**Comment by gbaned** [comment]
@aakash30jan Any update on this PR? Please. Thanks!

**Pull request closed without merging**
