### PR TITLE
differentiaing layer and it's test code is implemented.

### PR DESCRIPTION
**Pull request by shmoon-kr**
A keras layer which differentiate 1D temporal data with respect to step.

### CODE REVIEW

**Comment by qlzh727** [comment]
Adding @fchollet here as the API owner.

@shmoon-kr, thanks for sending the PR. Since this is extension to the current Keras layer API, we want to make sure it is adding value and align with other existing layers. For the current PR you sent, its unclear that my whether it is a good fit for a new layer, it more just like a ops that does the diff, and doesn't necessary to be a layer.

**Comment by qlzh727** [comment]
Also the weights of the layer are just constants, which probably isn't a good usage of variable as they never gets updated.

**Comment by shmoon-kr** [comment]
Thanks for a quick and detailed review. In my recent research, I found that sometimes it's better to use a differentiated vector instead. (https://www.mdpi.com/2077-0383/8/9/1419/htm) I thought the idea could be leveraged in other applications (especially for time series data) so I prepared for a contribution to the project.
I implemented differentiating by multiplying a constant matrix to a tensor as you said. The reason why I wrote a new layer (instead of just defining a constant matrix and multiplying it) is that the size of the constant matrix varies with the shape of an input tensor. Without a layer I should calculate the shape of an input tensor, define an appropriate constant matrix, permute an input tensor and multiply it by the constant matrix for each layer to differentiate. In the beginning I did so but the code is very complicated so I used a custom layer later. With the new layer I proposed, all of the above is done in just a line. It's the value I want to add to the project.

**Comment by qlzh727** [comment]
> Thanks for a quick and detailed review. In my recent research, I found that sometimes it's better to use a differentiated vector instead. (https://www.mdpi.com/2077-0383/8/9/1419/htm) I thought the idea could be leveraged in other applications (especially for time series data) so I prepared for a contribution to the project.
> I implemented differentiating by multiplying a constant matrix to a tensor as you said. The reason why I wrote a new layer (instead of just defining a constant matrix and multiplying it) is that the size of the constant matrix varies with the shape of an input tensor. Without a layer I should calculate the shape of an input tensor, define an appropriate constant matrix, permute an input tensor and multiply it by the constant matrix for each layer to differentiate. In the beginning I did so but the code is very complicated so I used a custom layer later. With the new layer I proposed, all of the above is done in just a line. It's the value I want to add to the project.

If we step back, I think the same functionality can also be done without being a layer. If you defined a function with the input tensor as input param, the body of the function will just be all the actions u described above. I don't see any value being added as layer, comparing to a just a normal python function.

**Comment by shmoon-kr** [comment]
> > Thanks for a quick and detailed review. In my recent research, I found that sometimes it's better to use a differentiated vector instead. (https://www.mdpi.com/2077-0383/8/9/1419/htm) I thought the idea could be leveraged in other applications (especially for time series data) so I prepared for a contribution to the project.
> > I implemented differentiating by multiplying a constant matrix to a tensor as you said. The reason why I wrote a new layer (instead of just defining a constant matrix and multiplying it) is that the size of the constant matrix varies with the shape of an input tensor. Without a layer I should calculate the shape of an input tensor, define an appropriate constant matrix, permute an input tensor and multiply it by the constant matrix for each layer to differentiate. In the beginning I did so but the code is very complicated so I used a custom layer later. With the new layer I proposed, all of the above is done in just a line. It's the value I want to add to the project.
> 
> If we step back, I think the same functionality can also be done without being a layer. If you defined a function with the input tensor as input param, the body of the function will just be all the actions u described above. I don't see any value being added as layer, comparing to a just a normal python function.

OK. If you're asking "Is a new layer the only way to do it?" The answer is no and I agree with you. But last year when I tried to find a way to differentiate a tensor, there was no such an example. So it took a few days to implement it. If there was a Keras layer I proposed by that time, I could have done it in a few minutes. If there's somebody else who takes a similar approach, we can save his/her time a lot by adding the new layer to Keras APIs. And if it is listed in Keras APIs, more people will see it and try in their problems and it's a good contribution to our society. Now it seems totally up to you. I understand your point but I think it still have a value though it's not essential.

**Comment by qlzh727** [comment]
I think the functionality proposed in this PR is a not common use case that is widely used, and Keras layers are designed to be common building blocks for DL model, and this PR is not fit for the core Keras API.

You could try propose this to tensorflow/addons, which is a place for extended functionality for tensorflow and Keras. See contribution guild line at https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md.

I am closing this PR for now since we can't accept at the moment.

**Pull request closed without merging**
