### PR TITLE
Update 1_notmnist.ipynb

### PR DESCRIPTION
**Pull request by luckluca**
If download fails, force delete on file by default

### CODE REVIEW

**Comment by luckluca** [comment]
I signed it!

**Comment by luckluca** [comment]
Hi @tensorflow-jenkins . The problem is that wrong downloaded file persist on memory disk.

**Comment by luckluca** [comment]
tested and it works

**Comment by vrv** [comment]
You have to sign the CLA (see the instructions above to make sure our bot knows about it) before we can look at this.  Closing for now but we'll reopen once the CLA is sorted out.

**Pull request closed without merging**
