### PR TITLE
Change the author of PR #37400 to original contributor

### PR DESCRIPTION
**Pull request by lithuak**

### CODE REVIEW

**Review by jsimsa — APPROVED** [review]

**Comment by jsimsa** [comment]
@gbaned how do I create an internal copy of this CL for review? thanks.

**Comment by mihaimaruseac** [comment]
```
INFO: Effect: NOOP -  Cannot migrate revisions [d82a2ba2018499a014a13a4213ecaf34e021f25f, 6fd74c7ea03005ed35a158393a8a5e8a4e88f91f]: Import of '6fc5f09a36c4f9b1d13c37c1671a16bb21070577' revision resulted in an empty change. Is the change already migrated?. Affected origin_refs: 2
```

**Comment by mihaimaruseac** [comment]
Screenshot from 2020-03-23 16-33-13

**Comment by mihaimaruseac** [comment]
Based on #37400, can we close this / reuse this to fix broken test and resubmit?

**Comment by lithuak** [comment]
@mihaimaruseac This PR was opened by me completely because of misunderstanding about the merging process and further changes. I guess it can be closed. For further fixes I could either open another proper PR or use the original PR.

**Comment by mihaimaruseac** [comment]
Let's use original PR. Closing this one

**Pull request closed without merging**
