### PR TITLE
Moved deepdream to tutorials.

### PR DESCRIPTION
**Pull request by znah**

### CODE REVIEW

**Comment by vrv** [comment]
Is it possible to delete the image entirely from the repo, and just have it be downloaded by the tutorial?  large images in git are bad :(

**Comment by znah** [comment]
@vrv Image size is ~100kb, while notebook size (due to embedded images and graphs) is already ~1mb. Is really a big deal? The files are already in the repository anyway, so removing them will require force-pushing. I'm just moving them to a more appropriate directory.

**Comment by vrv** [comment]
Yikes, we shouldn't have had the notebook in here in the first place either :(.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Pull request merged**
