### PR TITLE
[TFLite] Add int16x8 support for RELU_N1_TO_1 and PRELU operators

### PR DESCRIPTION
**Pull request by johan-gras**
Hello,

This PR adds int16x8 support for RELU_N1_TO_1 and PRELU operators.

Thanks,
Johan.

### CODE REVIEW

**Comment by gbaned** [comment]
@miaout17 Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@miaout17 Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@johan-gras  Can you please sign CLA. Thank you!

**Comment by gbaned** [comment]
Hi @joker-eph Can you please review this PR ? Thank you!

**Comment by joker-eph** [comment]
This isn't directly in my scope, maybe @karimnosseir can help?

**Comment by gbaned** [comment]
@johan-gras Can you please sign CLA and resolve conflicts?

**Comment by johan-gras** [comment]
@gbaned unfortunately I am not working at Arm anymore, so I am unable to modify this PR. Someone from Arm would have to take a look at it. Maybe @Tessil?

**Comment by gbaned** [comment]
Hi @Tessil Can you please resolve conflicts? Thank you!

**Comment by abattery** [comment]
@alankelly could you take a look at this pull request?

In quantized kernel implementation wise, it looks okay to me.

**Comment by gbaned** [comment]
Hi @Tessil Can you please resolve conflicts? Thank you!

**Review by alankelly — COMMENTED** [review]
Kernel changes LGTM. Adding @arfaian for converter changes

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Review by alankelly — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @johan-gras Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @johan-gras Can you please resolve conflicts? Thank you!

**Comment by SaoirseARM** [comment]
> Hi @johan-gras Can you please resolve conflicts? Thank you!

Thanks! Resolved conflicts. 

Best regards,
Saoirse

**Comment by gbaned** [comment]
Hi @alankelly  Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by alankelly** [comment]
@gbaned I no longer work on TFLite, can you please re-assign this PR? Thanks

**Comment by gbaned** [comment]
> @gbaned I no longer work on TFLite, can you please re-assign this PR? Thanks

Hi @alankelly Sure thing, thank you for the update.

**Comment by gbaned** [comment]
Hi @hheydary Can you please review this PR? Thank you!

**Comment by hheydary** [comment]
@gbaned Alan has already reviewed this. If you need a second review, @haozha111 would be a good candidate.

**Comment by gbaned** [comment]
Hi @johan-gras Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @johan-gras Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @johan-gras Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @johan-gras Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @johan-gras Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @johan-gras Can you please resolve the conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @johan-gras, @Tessil  I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!  Thank you for your contribution.

**Pull request closed without merging**
