### PR TITLE
Update 1_notmnist.ipynb

### PR DESCRIPTION
**Pull request by peeyush18**
The url in the file will not redirect to https. i faced this problem so changing it for someone who will see it in future. 
i think port 80 is blocked on that server but 443 is going is going through.

### CODE REVIEW

**Comment by peeyush18** [comment]
The url in the file will not redirect to https. i faced this problem so changing it for someone who will see it in future.
i think port 80 is blocked on that server but 443 is going is going through.
I changed and it working after it.

**Comment by peeyush18** [comment]
I signed it!

**Comment by peeyush18** [comment]
I signed it!

**Comment by peeyush18** [comment]
I signed it!

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
