### PR TITLE
Adding instructions on how to run CMSIS-NN opt kernels using mbed

### PR DESCRIPTION
**Pull request by freddan80**
Change-Id: I31812627f95de1f8dea5704d5880cc1ffcd132cc

### CODE REVIEW

**Review by njeffrie — DISMISSED** [review]
Content looks good.  Please format based on https://github.com/google/styleguide/blob/gh-pages/docguide/style.md, especially around line length suggestions.

**Comment by gbaned** [comment]
@freddan80 Did you get a chance to look on reviewer comments? Please let us know on the update. Thanks!

**Comment by freddan80** [comment]
Hi Nat! 

Thanks for the comments, and sorry for the late reply. I've been ooo for a few weeks.

Regarding the line length I was trying to follow the existing style in the readme file. Some existing examples:

`make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_micro_speech_mbed_project`

and

`make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=arduino TAGS="" generate_micro_speech_mock_arduino_library_zip`

where command line instructions don't break line. Was this what you were referring to?

Regards
Fredrik

**Comment by freddan80** [comment]
@njeffrie , did you have a chance to look at my comment?

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by njeffrie** [comment]
When I run our markdown linter, it breaks those commands into multiple lines.  The style guide indicates to follow line limits "when possible" and it's possible here.  Not a huge deal either way - I understand that we break that rule in other places, but unless there's a reason to exceed the line limit I slightly prefer to follow the style guide.

**Review by njeffrie — APPROVED** [review]
Leaving the decision whether to keep commands on a single line up to the author.  It's something we do elsewhere.  I slightly prefer splitting lines, but it's not a big deal either way.

**Comment by freddan80** [comment]
Thanks @njeffrie! I will leave it like it is for now to be consistent with the other command line commands in that readme file. Is the markdown linter you refer to publicly accessible?

**Comment by njeffrie** [comment]
I don't know of a publicly available version, unfortunately.

**Comment by freddan80** [comment]
Is it possible to get the test restarted. This PR has only textual changes.

**Pull request merged**
