### PR TITLE
Patch @com_google_absl to always export //absl/time:time symbols

### LINKED ISSUE #663: Missing symbol for Abseil ParseTime Op
**Describe the bug**
Since the 20101030 nightly, our library fails when opening the `_parse_time_op.so` because of an undefined symbol error. Typically this occurs when there is an ABI incompatibility between core TensorFlow and our custom-ops. 

```
tensorflow.python.framework.errors_impl.NotFoundError: .../custom_ops/text/_parse_time_op.so: undefined symbol: _ZN4absl9ParseTimeERKSsS1_PNS_4TimeEPSs
```

This particular [custom-op utilizes absl](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/text/cc/kernels/parse_time_kernel.cc#L75) and the mangled symbol name does not match what our compiled operation thinks it should be. I'm not really sure how this would happen since the rest of the TensorFlow library was compiled with a compatible gcc version.

CC'ing some people who may have insight into how this can happen:
@yifeif @r4nt @perfinion @gunan 

I suppose we could make absl a dependency in our TFA build and compile it ourselves but this seems to be going down a bad path.

Failing Log:
https://source.cloud.google.com/results/invocations/a71d103a-ecac-421c-bc53-ef06648fdc9f/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy3%2Fpresubmit/log

### PR DESCRIPTION
**Pull request by scentini**
This should fix tensorflow/addons#663, caused by changing logic in Bazel on which symbols we export (see https://github.com/bazelbuild/bazel/issues/7362).

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Looks good to me. However, there is only one `patch_file` but two mentioned in the comment. Can you instead edit the comment to specify something like "Remove everything but the patch to `absl/time/BUILD.bazel` until ABSL issue is resolved. Remove the patch to `absl/time/BUILD.bazel` when.."

Speaking of which, let's add some more detail about the export symbols issues. A link to another issue should be enough

**Comment by scentini** [comment]
Rephrased the comment, PTAL.

**Review by mihaimaruseac — APPROVED** [review]
Thank you

**Comment by seanpmorgan** [comment]
Hmmm seems there was a copybara error? Gentle bump to see if this can get through as it's breaking our  pin to nightly.

**Comment by mihaimaruseac** [comment]
This is breaking internal builds

```
undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
```

**Pull request merged**
