### PR TITLE
lite: add tensors and nodes size in SignatureRunner

### PR DESCRIPTION
**Pull request by aflaischer**
number of tensors and nodes is already available in Subgraph class, map these sizes in SignatureRunner.

It avoids to use GetSubgraphIndexFromSignature() and subgraph() from Interpreter class to retrieve these sizes for a given signature.

### CODE REVIEW

**Review by yishuangP — APPROVED** [review]

**Comment by gbaned** [comment]
> Hi @gbaned Is there something I should check to make the merge progress?

Hi @aflaischer Can you please take a look on below error. Thank you!

clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)

**Comment by aflaischer** [comment]
Hi @gbaned 

From which job is it coming? it seems I don't have access to feedback/copybara
what is the command to run?

In any case it seems like an environment issue no? if the clang command is segfaulting 

Should I rebase my changes perhaps?

**Comment by gbaned** [comment]
Hi @yishuangP Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @aflaischer Can you please resolve conflicts? Thank you!

**Pull request closed without merging**
