### PR TITLE
Add appropriate value check for `tf.clip_by_norm`

### LINKED ISSUE #54414: `tf.clip_by_norm` gives WRONG results when given negative `norm`
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf

x = tf.constant([[1, 2, 3, 4, 5]], dtype=tf.float32)
clip_norm = -6.0
x_clipped = tf.clip_by_norm(x, clip_norm, )
print(x)
print(x_clipped)

```
Outputs:
```
tf.Tensor([[1. 2. 3. 4. 5.]], shape=(1, 5), dtype=float32)
tf.Tensor([[-0.80903983 -1.6180797  -2.4271195  -3.2361593  -4.0451994 ]], shape=(1, 5), dtype=float32)
```

**Describe the current behavior**
`tf.clip_by_norm` has an argument `clip_norm` which should be a **positive** floating point. However, it does not perform any validity checking and can accept a negative value like `-6.0`.  When applied to a tensor, it produces wrong output silently.

**Describe the expected behavior**
`tf.clip_by_norm` should check the value of `clip_norm`.

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to address the issue raised in #54414 where
there is no check for clip_norm for tf.clip_by_norm.
As a result an invalid result was silently returned.

This PR fixes #54414.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Can you fix Ubuntu CPU?

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Needs fixing for Ubuntu CPU external

**Comment by gbaned** [comment]
Hi @yongtang Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!

**Comment by gbaned** [comment]
@yongtang  Any update on this PR? Please. Thank you!

**Pull request closed without merging**
