### PR TITLE
Removed unused lambda capture

### PR DESCRIPTION
**Pull request by naurril**

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by qlzh727** [comment]
Alex, can u take a look? Thanks.

**Comment by qlzh727** [comment]
@naurril, please fix the clang issue, please see https://source.cloud.google.com/results/invocations/d539047c-ef74-4305-a5df-e9f14342df46/targets/%2F%2Ftensorflow%2Ftools%2Fci_build:gen_ci_clang_format_out/log

**Review by alextp — COMMENTED** [review]
I do not understand the relationship between the c++ changes and the test changes.

Why are these test changes required given the C++ changes?

(I'm fine with the C++ changes as they are as they seem to not change the semantics of the program)

**Review by alextp — DISMISSED** [review]

**Comment by naurril** [comment]
Hi, @alextp @qlzh727, thanks for your review,  I checked the code carefully and found that `parallel_concat_optimizer.cc` does have difference from the master branch, although github didn't show them in the commit. Hope this could fix the clang format issue.

**Comment by naurril** [comment]
Hi, @qlzh727 @alextp, I changed the code format which should be the cause of the clang issue, hope this could solve it.  thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request merged**
