### PR TITLE
remove some signed/unsigned integer comparison warnings

### PR DESCRIPTION
**Pull request by chemelnucfin**
Jenkins, test this please.

I saw some areas where -1 was used as marker, so I didn't try to change those.  A lot of the dimensions specified the dimensions had to be positive.  I wanted to try running tests locally, but I get the following error message:

bazel test ... 
/_clipped_/
ERROR: /usr/local/lib/bazel/base_workspace/tools/BUILD:7:1: no such package 'tools/android': BUILD file not found on package path and referenced by '//tools:srcs'.
ERROR: Loading failed; build aborted.
____Elapsed time: 5.022s
ERROR: Couldn't start the build. Unable to run tests.

This is as much as asking for how to run the test locally as the pull request itself.  Reference #128

### CODE REVIEW

**Comment by vrv** [comment]
What version of bazel are you running?  We'd like to help you test locally, since only admins can trigger tests.

**Comment by vrv** [comment]
You might be better off specifically testing "tensorflow/..." instead of "..."

**Comment by chemelnucfin** [comment]
Great.  Thanks.  Seems to be working so far.  
I guess I was in the wrong directory for the previous command.

I'll get back to you if I find problems.
Thanks.

**Comment by chemelnucfin** [comment]
Seems like there're a lot of tests I need to work on with this patch.  

Are these the expected results currently?  I'm getting this on the tensorflow/master branch.
Executed 176 out of 315 tests: 106 tests pass, 62 fail to build and 147 fail locally.

I will close this pull request, please do not merge.
Thanks.

**Comment by vrv** [comment]
(I think our Mac build is broken, let us fix it first)

**Comment by vrv** [comment]
Okay I pushed a change to fix, you can try again now

**Comment by chemelnucfin** [comment]
I simplified this pull request to minimal (similar to the previous pull request #1050) and should be fine to check in.  However, I'm still getting python test failures.  Maybe a python2/3 issue or a protobuf issue?  The last error message is shown below, 
TypeError: __init__() got an unexpected keyword argument 'syntax'

with the pastebin showing the full error
http://pastebin.com/H59N4k36

**Comment by martinwicke** [comment]
That error is usually due to an older protobuf version installed somewhere on your system.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
Merged

**Pull request closed without merging**
