### PR TITLE
typo 'unit8' instead of 'uint8'

### PR DESCRIPTION
**Pull request by velaia**

### CODE REVIEW

**Comment by vrv** [comment]
Thanks for the fix, but we need the CLA to be signed.  Please let us know if you can sign it and we'll reopen.

**Comment by velaia** [comment]
I signed it! Hope to contribute more substantially in the future. THanks

**Comment by vrv** [comment]
Can you double check the cla info?

**Comment by vrv** [comment]
(you probably have to redo the git commit email)

**Comment by velaia** [comment]
image

I don't understand 'redo the git commit email'. I've only used the github.com web interface for making the patch. Do I have to open a new issue and we close this?

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Review by caisq — APPROVED** [review]

**Comment by caisq** [comment]
PR merged. Thank you, @velaia !

**Pull request merged**
