### PR TITLE
Added release notes for 1.13 release

### PR DESCRIPTION
**Pull request by aselle**

### CODE REVIEW

**Comment by bemeurer** [comment]
@aselle, are the changes in #24666 getting into this release? If so, shouldn't the fix and compatibility with OpenSSL 1.1 be added to the release notes?

**Comment by dmitrievanthony** [comment]
Folks, could you please mention that we've added support of Apache Ignite File System in this release (see https://github.com/tensorflow/tensorflow/pull/22194 PR and [this documentation](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ignite#distributed-file-system)).

I think we could use language like "_Ignite File System plugin added to contrib/ignite that allows to work with IGFS file system_".

**Comment by aselle** [comment]
@dmitrievanthony, this seems to already be in the 1.12 release notes.
```
 * Ignite Dataset added to contrib/ignite that allows to work with Apache
    Ignite.
```

**Comment by bemeurer** [comment]
@aselle Is there any chance / process for that to be changed, and for the OpenSSL fixes to go into this version? The lack of it makes tensorflow unbuildable on environments with OpenSSL 1.1

**Review by gunan — DISMISSED** [review]

**Comment by dmitrievanthony** [comment]
@aselle, I'm talking about another functionality. In 1.2 we have released Ignite **Dataset** (see https://github.com/tensorflow/tensorflow/pull/22210) that allows to read training data from Ignite Cache (like from tables in database). In 1.3 we are about to release Ignite **File System** (see https://github.com/tensorflow/tensorflow/pull/22194) that allows to use IGFS (file system on top of Apache Ignite) as a TensorFlow file system to make checkpoints and logging.

I think we need to reflect that in release notes.

**Review by rajatmonga — DISMISSED** [review]

**Comment by aselle** [comment]
@dmitrievanthony, I added a note under tf.contrib section

**Comment by dmitrievanthony** [comment]
Thanks, @aselle! I forgot to mention that in this release we also added ability to start/stop TensorFlow server from Java API (see https://github.com/tensorflow/tensorflow/pull/23022). Perhaps it's too small fix to mention it in release notes, so just to remind.

**Comment by aselle** [comment]
If you want this mentioned please add it as a PR to the 1.13 branch in
github. I'll put it into the final release notes.

**Pull request merged**
