### PR TITLE
[Windows/CMake] Support compute capability 3.0 by default

### LINKED ISSUE #6083: Cuda Compute Capability 3.0 not supported on Windows?
Running on Windows 8.1, Python 3.5.2, Cuda 8.0

name: GeForce GTX 660M
major: 3 minor: 0 memoryClockRate (GHz) 0.95
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.64GiB

I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:948] Ignoring visible gpu device (device: 0, name: GeForce GTX 660M, pci bus id: 0000:01:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.

### PR DESCRIPTION
**Pull request by mrry**
Fixes #6083.

### CODE REVIEW

**Comment by mrry** [comment]
Running an additional Windows/GPU/CMake presubmit here: http://ci.tensorflow.org/job/tf-pr-win-cmake-gpu/4/console

@gunan Since this is causing issues (#6001, #6083), can we cherry-pick this one into r0.12 if it passes?

**Review by gunan — APPROVED** [review]

**Comment by DollarAkshay** [comment]
Thank you so much 😄

**Comment by DollarAkshay** [comment]
I have no clue how to build using CMake where can I download the .whl file that has this fix ?

**Comment by gunan** [comment]
This change will be built into tonights nightly wheel file build.
Or this week we will have another release candidate ready which will have this fix.

**Pull request merged**
