### PR TITLE
Exported eager API TFE_* symbols in the dynamic library

### PR DESCRIPTION
**Pull request by eaplatanios**
Dicussed in #12784.

### CODE REVIEW

**Review by asimshankar — APPROVED** [review]
This is fine, though note that for Windows we probably need to add `TF_CAPI_EXPORT` in front of all the method declarations as well.

**Comment by asimshankar** [comment]
Jenkins, test this please

**Comment by eaplatanios** [comment]
@asimshankar Thank a lot! I was actually wondering why I couldn't link in Windows but I thought it was a problem with the cross-compilation docker container I was setting up. I made the changes for Windows too now. :)

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by eaplatanios** [comment]
I'm not really sure what's wrong here. Shouldn't this change have no impact on existing code?

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
I believe some of the tests were cancelled. I don't know why. I resolved the conflicts and triggered again.

**Comment by eaplatanios** [comment]
Sounds good. Thanks! :)

**Comment by caisq** [comment]
@eaplatanios There seem to be honest build errors. E.g., 

> ERROR: /workspace/tensorflow/python/BUILD:2884:1: SWIGing tensorflow/python/tensorflow.i failed: swig failed: error executing command 
>   (cd /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace && \
>   exec env - \
>   bazel-out/local-opt/bin/external/swig/swig -c++ -python -module pywrap_tensorflow_internal -o bazel-out/local-opt/bin/tensorflow/python/pywrap_tensorflow_internal.cc -outdir bazel-out/local-opt/bin/tensorflow/python -ltensorflow/python/client/device_lib.i -ltensorflow/python/client/events_writer.i -ltensorflow/python/client/tf_session.i -ltensorflow/python/client/tf_sessionrun_wrapper.i -ltensorflow/python/framework/cpp_shape_inference.i -ltensorflow/python/framework/python_op_gen.i -ltensorflow/python/grappler/cost_analyzer.i -ltensorflow/python/grappler/model_analyzer.i -ltensorflow/python/grappler/tf_optimizer.i -ltensorflow/python/lib/core/py_func.i -ltensorflow/python/lib/core/strings.i -ltensorflow/python/lib/io/file_io.i -ltensorflow/python/lib/io/py_record_reader.i -ltensorflow/python/lib/io/py_record_writer.i -ltensorflow/python/platform/base.i -ltensorflow/python/pywrap_tfe.i -ltensorflow/python/training/quantize_training.i -ltensorflow/python/training/server_lib.i -ltensorflow/python/util/kernel_registry.i -ltensorflow/python/util/port.i -ltensorflow/python/util/py_checkpoint_reader.i -ltensorflow/python/util/stat_summarizer.i -ltensorflow/python/util/tfprof.i -ltensorflow/python/util/transform_graph.i -Ibazel-out/local-opt/genfiles -Iexternal/eigen_archive -Iexternal/grpc -Iexternal/protobuf_archive -Iexternal/swig -Iexternal/boringssl -Iexternal/curl -Ibazel-out/local-opt/genfiles/external/local_config_python -Iexternal/nsync -Iexternal/gemmlowp -Iexternal/jemalloc -Iexternal/jpeg -Iexternal/com_googlesource_code_re2 -Iexternal/jsoncpp_git -Iexternal/zlib_archive -Ibazel-out/local-opt/genfiles/external/jemalloc -Iexternal/snappy -Iexternal/highwayhash -Iexternal/gif_archive -Ibazel-out/local-opt/genfiles/external/jpeg -Iexternal/lmdb -Iexternal/png_archive -Ibazel-out/local-opt/genfiles/external/curl -Ibazel-out/local-opt/genfiles/external/snappy -Iexternal/farmhash_archive -Iexternal/local_config_cuda -Iexternal/sqlite_archive -Iexternal/swig/Lib -Iexternal/swig/Lib/cffi -Iexternal/swig/Lib/python -Iexternal/swig/Lib/std -Iexternal/swig/Lib/typemaps tensorflow/python/tensorflow.i): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
> tensorflow/c/eager/c_api.h:33: Error: Syntax error in input(1).

**Comment by eaplatanios** [comment]
@caisq Thanks for pointing that out! I made a small edit that would probably fix them. Could you please run the tests again? Thanks!

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by eaplatanios** [comment]
I think the tests are simply timing out now and that there should be no bugs.

**Comment by caisq** [comment]
@eaplatanios Yes, the tests look good. But your CLA isn't signed yet. Can you take care of that?

**Comment by eaplatanios** [comment]
I've already done that long time ago. It only started showing at not signed after @martinwicke merged master into this PR. Not sure what to do to make it show it as signed again.

**Comment by martinwicke** [comment]
You can ignore issuebot on this one. It gets confused by multiple authors.

**Pull request merged**
