### PR TITLE
[INTEL MKL] Remove nGraph build support

### PR DESCRIPTION
**Pull request by adk9**
This PR removes now-deprecated direct integration of nGraph in TensorFlow. nGraph integration is still available via the external ngraph-bridge at:
https://github.com/tensorflow/ngraph-bridge/

or via `pip install ngraph-tensorflow-bridge`.

Signed-off-by: Abhishek Kulkarni <abhishek.kulkarni@intel.com>

### CODE REVIEW

**Comment by gbaned** [comment]
@adk9  Can you please resolve conflicts? Thanks!

**Review by penpornk — COMMENTED** [review]
Thank you for the PR! I'm double-checking with other TF folks whether they are okay with removing this. Some of them are out-of-office right now. I'll get back to you soon.

**Review by penpornk — DISMISSED** [review]
Thank you for the clean-up!

**Comment by penpornk** [comment]
Just for future reference, would you mind posting the error log that says `nlohmann_json_lib dep` is  needed by `google-cloud-cpp` (in d2a19ace23da5732796886b3f9020eae199cfb1)? Thank you very much!

**Comment by rthadur** [comment]
@adk9 can you please check ubuntu sanity failures ?

**Comment by adk9** [comment]
> @adk9 can you please check ubuntu sanity failures ?

Sorry about that! I pushed a fix to address the CI sanity failures.

> Just for future reference, would you mind posting the error log that says nlohmann_json_lib dep is needed by google-cloud-cpp (in d2a19ac)? Thank you very much!

I noticed that google-cloud-cpp was bumped to 1.17.1 (0a5e847646) after I opened this PR, and it seems to have a dependency now on `nlohmann_json_lib` which was originally an nGraph dependency. I hoisted it out preemptively but didn't actually run into any errors or have an error log handy.

**Review by penpornk — APPROVED** [review]
Thank you for the fix and the explanation!

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by rthadur — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by gbaned** [comment]
@adk9  Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@adk9 Can you please resolve conflicts? Thanks!

**Review by penpornk — APPROVED** [review]
Thank you for your patience!

**Review by rthadur — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by gbaned** [comment]
@adk9 Can you please resolve conflicts? Thanks!

**Comment by penpornk** [comment]
@adk9 So sorry for the inconvenience. We have had problems with our automatic code import for this PR. After the merge conflicts are resolved, I'll try to pull this PR in manually this time.

**Comment by adk9** [comment]
> @adk9 So sorry for the inconvenience. We have had problems with our automatic code import for this PR. After the merge conflicts are resolved, I'll try to pull this PR in manually this time.

No worries, I've fixed the conflicts. 👍

**Review by penpornk — APPROVED** [review]
Thank you very much!

**Pull request merged**
