### PR TITLE
[ROCm] Change to pick up rocprim and hipcub libraries from ROCm install

### PR DESCRIPTION
**Pull request by deven-amd**
In newer ROCm releases, rocprim and hipcub libraries will be installed on ROCm stack by default. Therefore it will no longer be necessary to pull them from source (as a third party package). This PR contains the changes requried to pick up rocprim and hipcub from ROCM install

This is essentially a cherry-pick this PR ROCmSoftwarePlatform/tensorflow-upstream#620  (authored by @whchung)

----------------------------------------------------------------

@whchung @parallelo @sunway513 @chsigg

### CODE REVIEW

**Comment by whchung** [comment]
@deven-amd would you help resolve the conflicts? thanks.

**Comment by deven-amd** [comment]
> @deven-amd would you help resolve the conflicts? thanks.

done

**Review by chsigg — APPROVED** [review]
Looks good to me. Might need some manual merging on our side though.

**Comment by chsigg** [comment]
FYI, I'm working on getting this merged...

**Pull request merged**
