### PR TITLE
Branch 179628764

### PR DESCRIPTION
**Pull request by ekelsen**
Push

### CODE REVIEW

**Comment by ekelsen** [comment]
@tensorflow-jenkins test this please

**Review by yifeif — APPROVED** [review]

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by yifeif** [comment]
@caisq could you take a look at the failure in `tensorflow/python/debug/wrappers/grpc_wrapper.py`? Looks like python3 does not have `sys.maxint`. Thanks!

**Comment by caisq** [comment]
@yifeif will do, it's interesting that the Kokoro tests didn't catch it. Might be a mac+python3 specific thing.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@yifeif, thanks for the attempt to fix the sys.maxint related failures. I think you need to remove the `import sys` lines from both files as well. Otherwise there will be linter errors.

**Comment by caisq** [comment]
@yifeif Ah - never mind about `import sys`: they were already there for other purposes.

**Pull request merged**
