### PR TITLE
libtensorfow-lite.a linking issue

### PR DESCRIPTION
**Pull request by vinceab**
This pull request fix issues encounter while linking the generated libtensorflow-lite.a into a C/C++ application.
Multiple symbols where not defined such as:
- type_erased.cc:(.text+0x36c): undefined reference to 'absl::Mutex::Lock()
- rfft2d.cc:(.text+0x594): undefined reference to 'rdft2d'

absl/hash and absl/flags that where referencing absl/synchronization have been removed from the build and fft2d/fftsg2d.c has been added to the build.

This has been successfully tested against the STM32MP1 OpenSTLinux distribution.

BR
Vincent

### CODE REVIEW

**Review by terryheo — COMMENTED** [review]
Thanks for the PR.
Could you also remove tensorflow/lite/tools/make/downloads/absl/absl/hash/internal/print_hash_of.cc from CORE_CC_EXCLUDE_SRCS? You can find it on master.

**Comment by vinceab** [comment]
Patches updated.
tensorflow/lite/tools/make/downloads/absl/absl/hash/internal/print_hash_of.cc has been removed from CORE_CC_EXCLUDE_SRCS.

**Review by terryheo — APPROVED** [review]
LGTM

**Comment by apivovarov** [comment]
@terryheo  Can it be backported to r1.15 ?

**Comment by terryheo** [comment]
@apivovarov could you share which script is failing on r1.15?

**Comment by apivovarov** [comment]
If you app uses whole `libtensorflow-lite.a` then the linking will fail with the following error
```
ip-172-19-29-73 % g++ -I /opt/tensorflow-1.15 \
run-lite.cc \
-Wl,--whole-archive \
/opt/tensorflow-1.15/tensorflow/lite/tools/make/gen/linux_x86_64/lib/libtensorflow-lite.a \
-Wl,--no-whole-archive \
-lpthread
/opt/tensorflow-1.15/tensorflow/lite/tools/make/gen/linux_x86_64/lib/libtensorflow-lite.a(rfft2d.o): In function `tflite::ops::custom::rfft2d::Rfft2dImpl(int, int, double**, int*, double*)':
rfft2d.cc:(.text+0x730): undefined reference to `rdft2d'
collect2: error: ld returned 1 exit status
```
We need whole archive because app fails at runtime if we do no use the whole archive.

**Comment by terryheo** [comment]
confirmed. I'll work no it.

**Comment by apivovarov** [comment]
`libtensorflow-lite.a` which is built from r2.1 contains `.o` files with `main()` function.
```
print_hash_of.o
tune_tool.o
```
As a result linking user's program with tflite archive results in "multiple definition of main" 

```
tensorflow/lite/tools/make/downloads/absl/absl/hash/internal/print_hash_of.cc
tensorflow/lite/experimental/ruy/tune_tool.cc
```

**Comment by terryheo** [comment]
I've created PR https://github.com/tensorflow/tensorflow/pull/39773 for r2.1 branch

**Pull request merged**
