### PR TITLE
[PluggableDevice] Add DEVICE_DEFAULT registration to dataset ops

### PR DESCRIPTION
**Pull request by PatriceVignola**

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
See https://github.com/tensorflow/tensorflow/pull/50605#issuecomment-919453092

It seems `tf.data` kernels should not use `DEVICE_DEFAULT`

**Comment by PatriceVignola** [comment]
@mihaimaruseac What should pluggable devices do to support those? As far as I know there's no way from the pluggable device API to handle `tf.data` kernels. Are new APIs similar to what was done for resource tensors required?

**Comment by penpornk** [comment]
Cc'ing @jsimsa for the answer. IIUC, `tf.data` is meant to be run only on TF native devices be design.

**Comment by PatriceVignola** [comment]
@penpornk Thank you for the reply. I guess what I'm trying to understand here is what advantages registering those ops for the GPU devices gives them in terms of performance or memory usage. In our TensorFlow 1.15 fork, we registered those ops for our custom device with the same priority as the GPU devices. Since it's not possible with the TF2 pluggable devices, what would be the impact of performance or memory usage of not having a registration for those operators, compared to the native GPU device?

**Pull request closed without merging**
