### PR TITLE
Fix code typo in eager programmers guide

### PR DESCRIPTION
**Pull request by maitbayev**

### CODE REVIEW

**Comment by maitbayev** [comment]
I signed it!

**Review by asimshankar — APPROVED** [review]
Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by asimshankar** [comment]
Ooops, sorry, I think I mistakenly approved this PR. This isn't a typo, it is intentional that we're re-using the variables in the `dense2` layer. With the changed code, the comment is incorrect (it is not re-using any variables)

Will roll this back.

**Pull request merged**
