### PR TITLE
Remove AWS files as s3 support is now in modular file system

### PR DESCRIPTION
**Pull request by yongtang**
This PR remove AWS files, as s3 support is now in modular file system.

This PR will help reduce build time of tensorflow core.

/cc @kvignesh1420  @vnvo2409 @burgerkingeater FYI

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by kvignesh1420 — COMMENTED** [review]
@yongtang @mihaimaruseac I think we should mention this activity in the RELEASE.md.

**Comment by yongtang** [comment]
@kvignesh1420  Thanks for the reminder. PR #51036 has been created to update the RELEASE.md

**Comment by gbaned** [comment]
@yongtang  Can you please resolve conflicts? Thanks!

**Comment by yongtang** [comment]
Thanks @gbaned . The PR has been updated with conflict resolved.

**Comment by gbaned** [comment]
@mihaimaruseac Can you please review this PR ? Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by gbaned** [comment]
@yongtang  Can you please resolve conflicts? Thanks!

**Comment by yongtang** [comment]
@mihaimaruseac @gbaned  The PR has been rebased to resolve the merge conflict. Can you take a look and see if the PR can be imported now (I noticed last time the internal import may have a failure)?

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
@yongtang  Can you please address Ubuntu Sanity errors? Thanks!

**Comment by yongtang** [comment]
@mihaimaruseac @gbaned The PR has been updated with the lint issue resolved. Please take a look and see if this fixes everything.

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Seems this needs manual import

**Comment by pkanwar23** [comment]
would you mind re-basing?

**Comment by yongtang** [comment]
Thanks @pkanwar23 @mihaimaruseac for the help. The PR has been rebased and updated. Please give it a try on import and see if the issue still persists.

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Most likely copybara won't merge this as it needed manual work, but it is now merged as of 7add88f2982331be6ba65ddc66f1c88053028fff

Sorry for the delay and thanks for sending all these PRs to TF

**Pull request closed without merging**
