### PR TITLE
ResizeNearestNeighbor support bfloat16

### LINKED ISSUE #32801: UpSampling2D doesn't support bfloat16
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): nightly
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TypeError: Value passed to parameter 'images' has DataType bfloat16 not in list of allowed values: int8, uint8, int16, uint16, int32, int64, float16, float32, float64
**Describe the expected behavior**
support bfloat16
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
``` python
import tensorflow as tf
input = tf.keras.Input(shape=(28, 28, 1), name='img',dtype=tf.bfloat16)
x = tf.keras.layers.UpSampling2D(3)(input)
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### PR DESCRIPTION
**Pull request by fsx950223**
Fix #32801

### CODE REVIEW

**Review by alextp — CHANGES_REQUESTED** [review]
I don't think this is enough to support bfloat16, because this change doesn't add kernels that support bfloat16 for any backends.

**Comment by gbaned** [comment]
@fsx950223 Could you please check reviewer comments and keep us posted. Thanks!

**Comment by fsx950223** [comment]
Yes, I'm still looking for the commit which implemented bfloat16 alone.

**Comment by fsx950223** [comment]
I may reopen it when I find the solution

**Pull request closed without merging**
