### PR TITLE
Add reduction parameter to mean_pairwise_squared_error loss

### PR DESCRIPTION
**Pull request by chrisyeh96**
Also increased clarify of the documentation for the function

### CODE REVIEW

**Review by ispirmustafa — CHANGES_REQUESTED** [review]
Thank you!
Please add unit tests

**Comment by chrisyeh96** [comment]
Could you please let me know where I can add unit tests? Thanks.

**Comment by asimshankar** [comment]
(Fine for API change)

**Comment by chrisyeh96** [comment]
@ispirmustafa Could you please let me know where I can add unit tests? Thank you.

**Comment by ispirmustafa** [comment]
You can add tests here: python/kernel_tests/losses_test.py

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by martinwicke** [comment]
I'll close this for now, please reopen if you find time to add tests.

**Pull request closed without merging**
