### PR TITLE
Update Keras 2D convolution docs

### PR DESCRIPTION
**Pull request by marcospgp**

### CODE REVIEW

**Comment by marcospgp** [comment]
@googlebot I signed it!

**Review by tanzhenyu — COMMENTED** [review]
What does "variable size" mean in this case? I think by setting to `None` it means it will get the default format from Keras backend.

**Comment by gbaned** [comment]
@marcospgp  Can you please check @tanzhenyu's comments and keep us posted ? Thanks!

**Comment by marcospgp** [comment]
@tanzhenyu @gbaned

> If any dimension of your input can vary, you can specify it as None

https://keras.io/getting_started/intro_to_keras_for_engineers/

**Comment by gbaned** [comment]
@tanzhenyu Can you please check @marcospgp's comments and keep us posted ? Thanks!

**Review by tanzhenyu — APPROVED** [review]

**Pull request merged**
