### PR TITLE
Port mul from Tensorflow Lite to Tensorflow Lite Micro

### PR DESCRIPTION
**Pull request by jenselofsson**
This PR port the mul kernel to Tensorflow Lite Micro. Supported data types are float, int8 and uint8.

### CODE REVIEW

**Comment by jenselofsson** [comment]
@petewarden Do you have the time to look at this? Thanks!

**Review by petewarden — DISMISSED** [review]
Looks great, thanks, approved!

**Comment by jenselofsson** [comment]
There seems to be some build errors related to multiple definitions of Mul(). I'll have a look at them.

**Comment by jenselofsson** [comment]
It seems that there is some problem with the "Ubuntu CC". It has been waiting for status for a few days now, and I've seen the same things for other PRs.

**Review by freddan80 — APPROVED** [review]

**Review by petewarden — APPROVED** [review]

**Review by freddan80 — DISMISSED** [review]

**Review by petewarden — DISMISSED** [review]

**Comment by jenselofsson** [comment]
Ready to merge.

**Comment by jenselofsson** [comment]
Ready to merge.

**Comment by jenselofsson** [comment]
There's a compile error related to the Register_* functions being moved to micro_ops.h. I'll fix it ASAP.

**Review by freddan80 — APPROVED** [review]

**Review by petewarden — APPROVED** [review]

**Review by neuralsorcerer — APPROVED** [review]

**Comment by jenselofsson** [comment]
Ready to merge.

**Comment by jenselofsson** [comment]
Ready to merge.

**Comment by jenselofsson** [comment]
Ready to merge.

**Comment by petewarden** [comment]
Sorry for the delay on this one, I am chasing it up internally!

**Comment by jenselofsson** [comment]
@petewarden Thanks!

**Comment by rthadur** [comment]
`ERROR: /tmpfs/tensor_flow/tensorflow/lite/experimental/micro/kernels/BUILD:181:1: Couldn't build file tensorflow/lite/experimental/micro/kernels/portable_optimized_depthwise_conv_test_binary: Linking of rule '//tensorflow/lite/experimental/micro/kernels:portable_optimized_depthwise_conv_test_binary' failed (Exit 1)
bazel-out/k8-opt/bin/tensorflow/lite/experimental/micro/kernels/_objs/portable_optimized_ops_resolver/all_ops_resolver.o:all_ops_resolver.cc:function tflite::ops::micro::AllOpsResolver::AllOpsResolver(): error: undefined reference to 'tflite::ops::micro::Register_MUL()'
collect2: error: ld returned 1 exit status`

@jenselofsson can you please check this error ?
cc @petewarden

**Comment by petewarden** [comment]
This is surprising, since the .cc should automatically be included in the library sources here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/tools/make/Makefile#L93

I'll investigate on our end what's going wrong.

**Comment by petewarden** [comment]
This is an issue with one of our Bazel build rules. I have a one-line fix (adding mul.cc to :portable_optimized_micro_ops in the kernel BUILD file), but longer-term we'll fix this so that we don't have to repeat this file.
We will make this change on our side, no action is needed from you Jens!

**Comment by rthadur** [comment]
Changes have been merged , auto merge did not happen so closing this PR , thank you

**Comment by freddan80** [comment]
Thanks for looking into this @petewarden !

**Pull request closed without merging**
