### PR TITLE
[TFMicro][RFC] Create a utility that takes model and generates model-data and ops-re…

### PR DESCRIPTION
**Pull request by kedars**
Saves the developer from knowing the model architecture or the operations used in the model. 

- Currently the model data to CC conversion happens through the xxd
  utility. But the other piece that is dependent on the model is the
  ops-resolver. Having to understand a model to generate the
  ops-resolver is additional overhead
- This utility does both of the above processing in a single go

Would something like this be of interest?

I also have some thoughts about including additional annotations in the model, being converted, so it can be used for placing specific components in the model in faster/slower memory. But that's in the future.

TODOs:
- This is done as an example for Request For Comments for micro-speech, can be extended to other applications
- Relies on `flatc` utility (as other utilities within the repo rely on this). Open to suggestions for using any native Python library for parsing the model

### CODE REVIEW

**Comment by kedars** [comment]
@petewarden would like your inputs here

**Comment by gbaned** [comment]
@kedars Can you please resolve conflicts? Thanks!

**Comment by kedars** [comment]
> @kedars Can you please resolve conflicts? Thanks!

Done

**Comment by gbaned** [comment]
@petewarden Can you please take a look on this PR? Thanks!

**Comment by gbaned** [comment]
@kedars Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by kedars** [comment]
CC @AdityaHPatwardhan

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by AdityaHPatwardhan** [comment]
Sorry for the delayed update, This MR is still worked on, will update today itself.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@AdityaHPatwardhan, @kedars  Any update on this PR, Please. Thanks!

**Comment by AdityaHPatwardhan** [comment]
Yes, I have started working on this, I will update the MR this week.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@AdityaHPatwardhan, @kedars Any update on this PR, Please. Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
