### PR TITLE
Remove python defines which clash with logging

### PR DESCRIPTION
**Pull request by DavidNorman**
I have the following clang on OS/X (High Sierra 10.13.4):

```
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
```

I receive a set of errors while compiling the `contrib/lite` directory which comes down to python defining some of the standard `isXXX` type functions with pre-processor macros.

This change removes those errors by undefining them

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by DavidNorman** [comment]
@aselle @miaout17 hi guys.  i wonder if someone could look at this one. it is an OS/X build failure due to Python.h defining a load of symbols which clash with the standard C RTL

**Comment by DavidNorman** [comment]
I'm abandoning this.

**Pull request closed without merging**
