### PR TITLE
add default decay value for RMSPropOptimizer

### PR DESCRIPTION
**Pull request by aymericdamien**
Set RMSPropOptimizer decay parameter default value to 0.9, for simplicity.

### CODE REVIEW

**Comment by vrv** [comment]
Hm, looks like we're pretty inconsistent about default args for our optimizers.  In Adam we set default values for all parameters (including learning rate), for others, everything but learning rate has a default, and here everything but learning rate and decay has a default.  

I'd be okay with this, since 0.9 seems to be a pretty common default from what I can tell, but @vincentvanhoucke for validation.

(You should add documentation specifying the default in the docstring, at least).

**Comment by aymericdamien** [comment]
ok, I added default value to docstring

**Comment by vincentvanhoucke** [comment]
Looks reasonable. @vrv what's the protocol for this? Looks like I have the right permissions to merge the pull request, is that something I can just go ahead with and all the merging takes care of itself?

**Comment by vrv** [comment]
For simple changes like this, yeah.  But I would recommend that @aymericdamien sqaushes the commits into one first before merging.

**Comment by aymericdamien** [comment]
ok, I just squashed the 2 commits together.

**Pull request merged**
