### PR TITLE
Restore deprecation warnings on {histogram,scalar}_summary in logging_ops

### PR DESCRIPTION
**Pull request by wookayin**
They were originally added in 1cb96893, but temporarily removed at 6d400d474 due to test timeouts.

### CODE REVIEW

**Comment by wookayin** [comment]
I believe that they might need to be restored before the 1.0 release. BTW, this patch also looks applicable to master branch :)

**Review by annarev — APPROVED** [review]

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
Timeout failure is unrelated. Merging.

**Pull request merged**
