### PR TITLE
Provide a Maven POM

### LINKED ISSUE #6527: [Java] provide a Maven POM
It would be handy to have a POM file for the Java library.

In the short-term, having a POM facilitates local development of Java applications (potentially using other build frameworks).  For example, it makes it possible to install the built library into Maven's local repository:
```
mvn install:install-file \
  -Dfile=bazel-bin/tensorflow/java/libtensorflow.jar \
  -DpomFile=tensorflow/java/pom.xml
```

The POM file should also be useful for eventual publishing of the library.

### PR DESCRIPTION
**Pull request by EronWright**
Closes #6527 

- POM file for installing libtensorflow into a Maven repository.

### CODE REVIEW

**Comment by EronWright** [comment]
@asimshankar please review.

**Comment by jhseu** [comment]
Mind adding instructions to the README?

**Review by jhseu — APPROVED** [review]

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by asimshankar** [comment]
@EronWright @jhseu : Quick question: How does `libtensorflow-jni.so` get included and linked in for  projects that add the maven dependency?

**Comment by EronWright** [comment]
Unfortunately Maven doesn't offer much help there.  The native lib is typically assumed to be preinstalled.  

I have seen instances where libraries tuck away their jni libs (for all supported platforms) into the jar, then extract them at runtime.  Similar to:

https://github.com/nathanmarz/jzmq/commit/e6c3c0b8966180a379b2a4aec64d7fd5fac5db38#

https://github.com/os72/protoc-jar/blob/master/README.md

**Pull request merged**
