### PR TITLE
[Docs] Update two Wikipedia links

### PR DESCRIPTION
**Pull request by Androbin**

### CODE REVIEW

**Review by rmlarsen — DISMISSED** [review]

**Comment by rmlarsen** [comment]
Can you update this on the master branch as well/instead?

**Comment by Androbin** [comment]
Yeah, my mistake...

**Comment by Androbin** [comment]
Sorry, now the branch is clean.

**Comment by Androbin** [comment]
My bad. I had to get rid of some cherry-picked commits from 1.8 and rebase.
We're good to go now.

**Comment by Androbin** [comment]
@rmlarsen We're good to go now.

**Review by av8ramit — APPROVED** [review]

**Comment by Androbin** [comment]
Failure unrelated: `tensorflow/contrib/data/python/kernel_tests/batch_dataset_op_test`

**Pull request merged**
