### PR TITLE
Remove duplicate variable assignment.

### PR DESCRIPTION
**Pull request by larrytin**

### CODE REVIEW

**Review by drpngx — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
@larrytin sorry could you pull rebase and push again?

**Comment by rmlarsen** [comment]
@larrytin could you please resolve the conflict?

**Comment by rthadur** [comment]
@larrytin  gentle ping to rebase the branch.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
closing this PR due to lack of activity.

**Pull request closed without merging**
