### PR TITLE
TF Keras io_utils_test missing test cases add

### PR DESCRIPTION
**Pull request by Dayananda-V**
1-test case added for ask_to_proceed_with_overwrite

### CODE REVIEW

**Review by fchollet — DISMISSED** [review]
Thanks for the PR, LGTM

**Comment by rthadur** [comment]
@Dayananda-V can you please check the test failures

**Comment by Dayananda-V** [comment]
@rthadur 

still build error exist from this change?

**Comment by rthadur** [comment]
@Dayananda-V please sign CLA and re base your branch

**Comment by Dayananda-V** [comment]
Corrupted PR is replaced with #27368.

**Pull request closed without merging**
