### PR TITLE
Fix Wrong Rendering of Code Example

### PR DESCRIPTION
**Pull request by suvojit-0x55aa**
Code example was being rendered as plain text. This commit fixes it.

### CODE REVIEW

**Comment by suvojit-0x55aa** [comment]
I signed it!

**Review by sb2nov — APPROVED** [review]

**Comment by suvojit-0x55aa** [comment]
The builds are failing. Do I need to change anything ??

**Comment by sb2nov** [comment]
Seems like it couldn't start the build. Let's try one more time. 

Saving the link for this run for future reference https://source.cloud.google.com/results/invocation/93164fdd-a76a-45c8-a156-4b9c62e39096/log

**Comment by suvojit-0x55aa** [comment]
I don't think the builds are running.
`ERROR: no such package '@bazel_toolchains//configs/debian8_clang/0.2.0/bazel_0.7.0': BUILD file not found on package path`

**Pull request merged**
