### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Molkree**
Mostly just repeating words.
If needed I can split it into more PRs as it probably covers too many files (but on the other hand no code changes so shouldn't be too bad maybe?).

### CODE REVIEW

**Review by mdanatg — APPROVED** [review]

**Review by annarev — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
I think it's better to split this by directory.

**Comment by Molkree** [comment]
Sure, @mihaimaruseac, will do.

**Comment by Molkree** [comment]
@mihaimaruseac, would this be alright or should I split even further?
| Dirs                                   | # of files  |
|:----------------------------:|:----------:|
| This PR                              | 145         |
|                                           |                |
| c & cc & compiler & core | 62            |
| go & python                      | 43            |
| lite & rest                           | 40            |

**Comment by mihaimaruseac** [comment]
I think that might still have too many files. Splitting by directory is better as that would mean a change will need fewer approvals to merge. So, one PR for `c/`, one for `cc/`, one for `compiler/`, etc. It might be likely that even those PRs will need to be split due to the internal approval hierarchy but we'll cross that bridge when we get to it.

**Pull request closed without merging**
