### PR TITLE
Release branch commits

### PR DESCRIPTION
**Pull request by nealwu**
Merges the changes from https://github.com/tensorflow/tensorflow/pull/9954 and https://github.com/tensorflow/tensorflow/pull/9975 into master, since they were only merged into r1.1.

### CODE REVIEW

**Comment by nealwu** [comment]
Both commit authors have already had their work merged into r1.1 in the pull requests linked above, so that should be fine.

**Review by yifeif — APPROVED** [review]
Thanks for merging these changes back Neal!

**Comment by nealwu** [comment]
@andrewharp can we get this merged in?

**Comment by gunan** [comment]
Failure is a known flaky test (should be disabled now).
Since this is a merge PR, CLA is also OK, since all CLAs are signed.
Merging.

**Pull request merged**
