### PR TITLE
Merge branch 'master' into r1.9

### PR DESCRIPTION
**Pull request by Hendis**
add TF_MINOR_VERSION 9

### CODE REVIEW

**Comment by Hendis** [comment]
add TF_MINOR_V 9

**Comment by yifeif** [comment]
Thanks for the PR @Hendis. I believe the merge changes have been made by #19842.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @av8ramit: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by av8ramit** [comment]
Another PR has already done this.

**Pull request closed without merging**
