### PR TITLE
Add distributed aggregation for embedding lookup sparse

### PR DESCRIPTION
**Pull request by suiyuan2009**
#5928 
the function `embedding_lookup` becomes too complex...but hard to split.

### CODE REVIEW

**Comment by tgy** [comment]
I find the `embedding_lookup` too complex too. Maybe it would be a good idea to refactor it into something easier to apprehend for newcomers.

**Comment by suiyuan2009** [comment]
@tgy I tried to add a new function for aggregation, but it was a mess. I need to modify the function `embedding_lookup` or I need to copy a lot of code from `embedding_lookup`.

**Comment by alextp** [comment]
I think I prefer a function in contrib with sadly duplicated code from embedding lookup over changing its API at this point.

I am just worried that maybe use_aggregation=True is not how we'd like this to look like forever. I'd rather let this sit in contrib for a bit (even with the pain of duplication) and see how it's used.

Thoughts?

**Comment by suiyuan2009** [comment]
@alextp it's better to add new functions, the current modification is too ugly...

**Review by alextp — CHANGES_REQUESTED** [review]
Please add a new function to contrib with this functionality, until we are sure we know what this API should look like.

**Comment by alextp** [comment]
Jenkins, test this please.

**Comment by suiyuan2009** [comment]
@alextp I can't see the details of the failed test case.

**Comment by alextp** [comment]
The embedding_ops_test fails in python3 because the code uses xrange instead of range:

FAIL: //tensorflow/contrib/layers:embedding_ops_test (see /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/testlogs/tensorflow/contrib/layers/embedding_ops_test/test.log).
INFO: From Testing //tensorflow/contrib/layers:embedding_ops_test:
==================== Test output for //tensorflow/contrib/layers:embedding_ops_test:
2017-03-29 22:09:06.648837: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-29 22:09:06.648870: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-29 22:09:06.648874: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-03-29 22:09:06.648876: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-29 22:09:06.648879: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
EE../var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/python/ops/partitioned_variables.py:280: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "create_partitioned_variables is deprecated.  Use "
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py:96: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logging.warn("The default value of combiner will change from \"mean\" "
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
........WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:From /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py:344: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
../var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/python/ops/embedding_ops.py:95: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  if params is None or params == []:  # pylint: disable=g-explicit-bool-comparison
./var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/python/ops/embedding_ops.py:95: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  if params is None or params == []:  # pylint: disable=g-explicit-bool-comparison
./var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/python/ops/partitioned_variables.py:280: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "create_partitioned_variables is deprecated.  Use "
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:From /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py:344: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:From /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py:344: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:From /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py:344: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:From /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py:344: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
.WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:From /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py:344: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
..
======================================================================
ERROR: testEmbeddingLookupSparse (__main__.EmbeddingLookupSparseWithDistributedAggregationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops_test.py", line 722, in testEmbeddingLookupSparse
    combiner=combiner)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py", line 640, in embedding_lookup_sparse_with_distributed_aggregation
    weights=weights, idx=idx, segment_ids=segment_ids)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py", line 784, in _embedding_lookup_with_distributed_aggregation
    for p in xrange(np):
NameError: name 'xrange' is not defined

======================================================================
ERROR: testGradientsEmbeddingLookupSparse (__main__.EmbeddingLookupSparseWithDistributedAggregationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops_test.py", line 761, in testGradientsEmbeddingLookupSparse
    combiner=combiner)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py", line 640, in embedding_lookup_sparse_with_distributed_aggregation
    weights=weights, idx=idx, segment_ids=segment_ids)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/contrib/layers/embedding_ops_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py", line 784, in _embedding_lookup_with_distributed_aggregation
    for p in xrange(np):
NameError: name 'xrange' is not defined

----------------------------------------------------------------------
Ran 32 tests in 6.352s

FAILED (errors=2)
================================================================================

**Comment by alextp** [comment]
Jenkins, test this please.

**Review by alextp — APPROVED** [review]

**Pull request merged**
