### PR TITLE
[Intel MKL] Adding Quantized Convolution (Int8) - Part 4

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR is part 4 of four PRs that add quantized version of convolution using MKL-DNN. This part adds the registration of MKL quantized and fused operations. 

Please note that the below PRs replace this one #19425 
Part 1: #21483 
Part 2: #21456 
Part 3: #21465 
Part 4: #21466

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @tatianashp, @raghuraman-k: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 21 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @tatianashp, @raghuraman-k: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 36 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @tatianashp, @raghuraman-k: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 51 days with no activity and the `awaiting review` label has been applied.

**Review by raghuraman-k — DISMISSED** [review]

**Comment by drpngx** [comment]
@mahmoud-abuzaina could you look into the failures?

**Comment by drpngx** [comment]
Can you see the invocation log [here](https://source.cloud.google.com/results/invocations/2fb64cb0-c711-4f79-9fd6-e859d68752f5/targets)? It says "broken", which means that the `C++` failed to build.

**Comment by mdfaijul** [comment]
@drpngx There is no "--config=mkl" in this test invocation command

bazel test --config=cuda --test_tag_filters=-no_oss,-oss_serial,-no_gpu,-benchmark-test --test_lang_filters=py --local_test_jobs=32 --remote_accept_cached=true --spawn_strategy=standalone --remote_local_fallback=false --remote_timeout=600 --strategy=Javac=standalone --strategy=Closure=standalone --genrule_strategy=standalone --copt=-DPOISON_CACHE=TRUE --run_under=//tensorflow/tools/ci_build/gpu_build:parallel_gpu_execute --auth_enabled=true --auth_credentials=/tmpfs/src/keystore/71384_tensorflow-testing-service-account --auth_scope=https://www.googleapis.com/auth/cloud-source-tools --tls_enabled=true --bes_backend=buildeventservice.googleapis.com --bes_best_effort=false --bes_timeout=600s --project_id=tensorflow-testing --remote_cache=remotebuildexecution.googleapis.com --remote_instance_name=projects/tensorflow-testing/instances/default_instance --remote_timeout=3600 -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/...
--

**Comment by drpngx** [comment]
OK, maybe it's unrelated. Trying again.

**Comment by mdfaijul** [comment]
@drpngx I think this failure (MacOS Contrib) too is not related to our contribution.

**Comment by mdfaijul** [comment]
@drpngx @tatianashp I don't think failures related to our contribution. Could you please let us know.

**Comment by drpngx** [comment]
Could you run clang-format? I think we use `3.6.0`. Thanks.

**Comment by mdfaijul** [comment]
@drpngx Ran clang-format 3.6.0

**Review by tatianashp — DISMISSED** [review]

**Comment by agramesh1** [comment]
@drpngx It looks like the tests are passing, can you initiate the merging?

**Comment by mdfaijul** [comment]
@drpngx We don't have access to ```feedback/copybara``` issue

**Comment by mdfaijul** [comment]
@drpngx Any update on this PR?

**Comment by drpngx** [comment]
Waiting for internal approval...

**Comment by agramesh1** [comment]
@drpngx  Sorry to keep bugging you. Any updates on the results of the internal testing?

**Comment by drpngx** [comment]
@tatianashp could you approve internally?

**Comment by mdfaijul** [comment]
@tatianashp @drpngx Any update.

**Pull request merged**
