### PR TITLE
Use TF_CALL_GPU_ALL_TYPES for variable ops

### LINKED ISSUE #35994: Expand registered kernels for variable ops on GPU
**System information**
- TensorFlow version (you are using):1.14/1.15
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**

The current variable op on GPU is restricted to float, double, and int64.  Through the TF_CALL_GPU_NUMBER_TYPES and
TF_CALL_int64 macros.

The notes say to restrict the dtype to those supported by the assignment op.  The assignment op has a broader range of dtypes registered through the
TF_CALL_GPU_ALL_TYPES and 
TF_CALL_int64 macros.

This disallows users to store boolian data with small memory footprints and forces unnecessary casts.  For that matter int32's and half precision could probably also be added.

Its a very easy change to make.  However, I am not sure if there is further rational for the restricted types.

**Will this change the current api? How?**
Nothing other than allowing more dtypes to be passed into variable constuctors

**Who will benefit with this feature?**
Anyone who wants to lower variable memory footprint 

**Any Other info.**

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to expand variable ops, as was discussed in TF_CALL_GPU_ALL_TYPES

This PR fixes #35994

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by alextp — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
This fails internal GPU tests with error similar to 

```
I0504 14:50:24.853820    1577 gpu_device.cc:1230] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14149 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:bb:00.0, compute capability: 7.0)
E0504 14:50:24.889745    1577 test_util.py:1657] 2 root error(s) found.
  (0) Invalid argument: assertion failed: [Input error: exclusive=True: more than 1 conditions (Equal:0, Equal_1:0, Equal_2:0) evaluated as True:] [0 1 1]
	 [[node case/Assert/AssertGuard/Assert (defined at tensorflow/python/ops/control_flow_ops_test.py:1235) ]]
  (1) Invalid argument: assertion failed: [Input error: exclusive=True: more than 1 conditions (Equal:0, Equal_1:0, Equal_2:0) evaluated as True:] [0 1 1]
	 [[node case/Assert/AssertGuard/Assert (defined at tensorflow/python/ops/control_flow_ops_test.py:1235) ]]
	 [[case/cond/Merge/_21]]
0 successful operations.
0 derived errors ignored.
```

**Comment by yongtang** [comment]
@mihaimaruseac  I don't see the code of the internal test setup, though I searched through the current repo. Is the error line corresponds to the following check in `tensorflow/python/ops/control_flow_ops_test.py` (master branch) ?:
```python

  @test_util.run_deprecated_v1
  def testCase_multiple_matches_exclusive(self):
    x = array_ops.placeholder(dtype=dtypes.int32, shape=[])
    conditions = [(math_ops.equal(x, 1), lambda: constant_op.constant(2)),
                  (math_ops.equal(x, 2), lambda: constant_op.constant(4)),
                  (math_ops.equal(x, 2), lambda: constant_op.constant(6))]
    default = lambda: constant_op.constant(8)
    output = control_flow_ops.case(conditions, default, exclusive=True)
    with self.cached_session() as sess:
      self.assertEqual(sess.run(output, feed_dict={x: 1}), 2) # <= failure?
      self.assertEqual(sess.run(output, feed_dict={x: 3}), 8) # <= failure?
      with self.assertRaisesRegexp(errors.InvalidArgumentError, "Input error:"):
        sess.run(output, feed_dict={x: 2})

```

**Comment by mihaimaruseac** [comment]
Hi. Yes, that is the test that fails on GPU. Looks like the ref variable changes are not ok?

**Comment by yongtang** [comment]
@mihaimaruseac The changes is `TF_CALL_GPU_ALL_TYPES` and `TF_CALL_GPU_NUMBER_TYPES` which impacts `bool`, `complex64`, and `complex128`

```c++
#define TF_CALL_GPU_ALL_TYPES(m) \
  TF_CALL_GPU_NUMBER_TYPES(m)    \
  TF_CALL_bool(m) TF_CALL_complex64(m) TF_CALL_complex128(m)
```

I will be surprised if  `complex64` or `complex128` will cause an issue. So it might be related to `bool`.

I think I can either create a PR to remove `bool`, or I can create a PR to revert then resubmit `complex64` and `complex128` only.

**Comment by yongtang** [comment]
@mihaimaruseac @alextp Created a PR #39172 to remove `bool`. But let me know if you prefer to revert first, I can update the PR to revert if needed.

**Pull request merged**
