### PR TITLE
ValueError raised when weights is a None object

### PR DESCRIPTION
**Pull request by moselhy**
Previously: raise ValueError when weights list is empty.
Now: raise ValueError when weights list does not exist or is empty.

### CODE REVIEW

**Comment by moselhy** [comment]
@googlebot I signed it!

**Review by fchollet — APPROVED** [review]
LGTM, thank you for the PR, and sorry for the long delay in reviewing.

**Comment by rthadur** [comment]
@moselhy can you please check Ubuntu sanity failures ?

**Review by rthadur — APPROVED** [review]

**Comment by rthadur** [comment]
@moselhy can you please check below error ?
```
"/tensorflow/python/keras/layers/preprocessing/category_encoding_test.py", line 608, in test_end_to_end_bagged_modeling
    layer.set_weights(weights)
  File "/tensorflow/python/keras/engine/base_layer.py", line 1851, in set_weights
    expected_num_weights, str(weights)[:50]))
ValueError: You called `set_weights(weights)` on layer "category_encoding" with a weight list of length 0, but the layer was expecting 0 weights. Provided weights: []...
```

**Comment by moselhy** [comment]
@rthadur that's fixed now

**Review by rthadur — APPROVED** [review]

**Pull request merged**
