### PR TITLE
Update runtime version to 2.5.0 for newly added kernels' versions

### PR DESCRIPTION
**Pull request by thaink**
This is necessary to correctly reflect the minimum runtime version for these newly added features

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Should this be a cherrypick from master? We don't want to have to change the same lines again on 2.6, right?

**Comment by thaink** [comment]
This is cl is the same as cherry-picking from master.
Actually, I made this pr then cherry-pick to the master.

**Review by terryheo — DISMISSED** [review]
LGTM but not sure if you followed "How to Request a TF Release Cherry-Pick" doc. Maybe we need to use different commit title of "Merging"?

**Comment by thaink** [comment]
I changed the commit message to "Merging" but I am also not sure if it must be fixed that way.

**Comment by mihaimaruseac** [comment]
The cherrypick process requires the change to be in master first so that we have time to fully test it against nightly builds before taking into the release branch, as release testing is very expensive (18 hours or more).

Then, the commits on release branch have to have a reference to the original changelist as there are teams that use this in the automation for their release.

As such, let's close this PR and follow the proper procedure for cherrypicking.

**Pull request closed without merging**
