### PR TITLE
Fully disable all test/build targets that execute tensorflow during build.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by martinwicke** [comment]
Jenkins, test this please?

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
CPU test failure known issue.

**Comment by kirilg** [comment]
Why do the genrule targets need to be commented out? Shouldn't it be sufficient to just mark the tests manual as was done before? If that's not sufficient, adding `tags = [
        "local",
        "manual",
    ],` will definitely have Jenkins skip them for now until a fix is ready. As is, this breaks TensorFlow Serving and we can't sync to head. Can we revert this change or uncomment the genrules?

**Comment by gunan** [comment]
That makes jenkins skip "test execution", but in this case problem is actually building them.
You can see that prior to this change I tried exactly what you suggested. But jenkins still built them. And the problem in our case is the tensorflow library usage during build of these targets.

**Comment by kirilg** [comment]
The problems mentioned shouldn't be an issue if we just have the genrules though. If no test is linking it in (i.e. keep tests commented out for now), it shouldn't be built. If it's somehow being linked, it will be compiled at most once per run so there should be no path collisions. Do you think that would work?

**Comment by gunan** [comment]
we can try it out, if you have a PR I can try to see if it works.
Another way I see it working is, you can create these genrules within tensorflow serving repository and reference those genrules.
Any reason these specificly have to live within tensorflow repo?

**Comment by kirilg** [comment]
I don't have a PR. We don't do much development in git, I'm more comfortable making this change internally, but I see this is purely in Github. Could someone from the TF team undo the genrule comment change and test? (the usual tests we always run pass so I'm not sure where it failed)

We needed it in the TF repo because the other tests there were commented out here depended on it.

**Comment by gunan** [comment]
It causes a flake, which is much harder to track, and thats why it triggered our response.

What do you mean other tests commented out here, they are commented out, so they should not run. You mean tests not under third_party/tensorflow?

Again, if you have any tests in your repo, you can easily create the same genrule, and modify your tests to depend on those. This genrule is definitely going away from tensorflow, I can guarantee that, so the sooner your tests can avoid depending on them, the better.

**Pull request merged**
