### PR TITLE
Add converter for SparseSoftmaxCrossEntropyWithLogits

### PR DESCRIPTION
**Pull request by rrkarim**
Adds converter for `sparse_softmax_cross_entropy_with_logits`. There is a chance that I'm missing something here.
tensorflow/probability#749

### CODE REVIEW

**Review by alextp — DISMISSED** [review]

**Comment by rrkarim** [comment]
@alextp was a tiny issue with the test.

**Comment by rrkarim** [comment]
@alextp can you please approve this?

**Review by alextp — DISMISSED** [review]

**Comment by rrkarim** [comment]
@alextp It's pylint now, fixed that too. Sorry, can you approve again please?

**Review by alextp — DISMISSED** [review]

**Comment by gbaned** [comment]
@rrkarim Can you please check build failures? Thanks!

**Comment by rrkarim** [comment]
@gbaned I'm not sure what is the issue here. It know that the problem is with mlir but what is the cause of it, I'm missing.

**Comment by rthadur** [comment]
@rrkarim can you please resolve conflicts ? so that we can try to pull this in

**Comment by rrkarim** [comment]
@rthadur I can not reproduce that. Can you please look at the logs, there are some issues with mlir tests.

**Comment by rthadur** [comment]
@mihaimaruseac any suggestions on @rrkarim comments.

@rrkarim can you please resolve conflicts.

**Comment by mihaimaruseac** [comment]
Once conflicts are removed we should review and approve again. I think MLIR failures are fixed for now.

**Comment by rrkarim** [comment]
@mihaimaruseac seems like they are not, at least for this PR. I really can't find the cause of the issue here.

**Comment by mihaimaruseac** [comment]
Rebase again on master?

**Comment by rrkarim** [comment]
> Rebase again on master?

done.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Internally the MLIR build succeeds. If this PR still fails then we'll have to dig deeper

**Pull request merged**
