### PR TITLE
[oneDNN] Enabled {Conv2D, DepthwiseConv2D}+BiasAdd+FusedHardSwish for FP32/BF16

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR fuses the Conv2D/DWConv2D + BiasAdd + HardSwish activation function pattern into  _Fused(DW)Conv2D. This fusion improves the performance of Mobilenet-V3 model by 33%.

HardSwishPattern

### CODE REVIEW

**Review by ezhulenev — APPROVED** [review]

**Comment by gbaned** [comment]
@mahmoud-abuzaina Can you please resolve conflicts? Thank you!

**Comment by mahmoud-abuzaina** [comment]
@gbaned I have resolved the merge conflicts. Thanks!

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Review by ezhulenev — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @mahmoud-abuzaina Can you please rebase and resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @mahmoud-abuzaina Can you please rebase and resolve conflicts? Thank you!

**Comment by mahmoud-abuzaina** [comment]
Hi @gbaned I have resolved the merge conflicts.

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Review by ezhulenev — APPROVED** [review]

**Pull request merged**
