### PR TITLE
Make libtensorflow_jni target compatible with Tensorflow Text

### LINKED ISSUE #47431: Failed to run models with libtensorflow_jni and tensorflow text together
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.1
- Python version:  n/a
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): gcc7
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
When using [libtensorflow_jni.so](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/BUILD#L437) with [tensorflow text](https://github.com/tensorflow/text), it crashes.

Same issue: https://github.com/tensorflow/java/issues/82

**Any other info / logs**
```
2021-02-17 19:20:45.283001: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at wordpiece_kernel.cc:204 : Invalid argument: Trying to access resource using the wrong type. Expected N10tensorflow6lookup15LookupInterfaceE got N10tensorflow6lookup15LookupInterfaceE
```

### PR DESCRIPTION
**Pull request by liyinhgqw**
Export tensorflow symbols to solve global static variable lookup issue.

Fix #47431

### CODE REVIEW

**Comment by liyinhgqw** [comment]
@googlebot I consent.

**Comment by liyinhgqw** [comment]
@googlebot I consent.

**Review by frankchn — DISMISSED** [review]

**Comment by gbaned** [comment]
@jhseu Can you please take a look on this PR ? Thanks!

**Comment by gbaned** [comment]
@jhseu Can you please take a look on this PR ? Thanks!

**Comment by gbaned** [comment]
@gharibian  Can you please take a look on this PR ? Thanks!

**Comment by allenlavoie** [comment]
libtensorflow_jni.so links against libtensorflow_framework.so, which exports all TF symbols. Does linking to libtensorflow_framework.so work for you?

**Comment by gbaned** [comment]
@liyinhgqw  Can you please check @allenlavoie's comments and keep us posted ? Thanks!

**Comment by liyinhgqw** [comment]
This will not work if one uses `libtensorflow_jni`. The symbol does exist in both libtensorflow_framework.so and libtensorflow_text.so.
```
Symbol in TF
$ readelf -sW org/tensorflow/native/linux-x86_64/libtensorflow_framework.so.2 | grep hash_bit | grep LookupInterface

 42807: 0000000001cbcb6c     1 OBJECT  UNIQUE DEFAULT   30 _ZZN10tensorflow9TypeIndex4MakeINS_6lookup15LookupInterfaceEEES0_vE8hash_bit
 62977: 0000000001cbcb6c     1 OBJECT  UNIQUE DEFAULT   30 _ZZN10tensorflow9TypeIndex4MakeINS_6lookup15LookupInterfaceEEES0_vE8hash_bit
```
```
Symbol in TF Text
$ readelf -sW tfplugins/linux/libtftextops.so | grep hash_bit  | grep LookupInterface
  6015: 000000000049790a     1 OBJECT  UNIQUE DEFAULT   30 _ZZN10tensorflow9TypeIndex4MakeINS_6lookup15LookupInterfaceEEES0_vE8hash_bit
  8799: 000000000049790a     1 OBJECT  UNIQUE DEFAULT   30 _ZZN10tensorflow9TypeIndex4MakeINS_6lookup15LookupInterfaceEEES0_vE8hash_bit
```

However, if it is not exposed by `libtensorflow_jni.so`, when TF JNI tries to use this variable, the variable will not be the same as the one TF Text refers to as TF Text does not know the symbol is already stored in `libtensorflow_jni.so`. They can only share the same variable of the same address if both expose the symbol.

**Comment by allenlavoie** [comment]
Ah, it's not a missing symbol issue but an issue of a duplicated definition of LookupInterface. I don't see why libtensorflow_jni.so exposing the symbol is a good solution; typically we'd try to remove the second copy of the type, having it rely on a header instead.

In this case it seems like the duplication is from the wordpiece kernel including a second copy of LookupInterface. And I'm guessing libtensorflow_jni.so exporting the symbol puts it into the global symbol table, which would certainly override it in any plugins. But generally just linking against libtensorflow_framework.so should have it use that symbol anyway; is libtftextops.so linked against libtensorflow_framework.so? (ldd should tell you)

**Comment by liyinhgqw** [comment]
Not sure about it, but is it related to the dlopen flag (not `RTLD_GLOBAL`?) that java `loadLibrary` method uses?

**Comment by allenlavoie** [comment]
Maybe what's happening in Python is that _pywrap_tensorflow_internal.so is doing the loading, so even though its symbols aren't in the global symbol table (Python does not use RTLD_GLOBAL either) it still overrides this symbol for kernels it loads. And again in Java since libtensorflow_jni.so is doing the loading the thing being loaded prefers its symbols even if they aren't in the global table.

Can you check if that's really what's happening, e.g. with `LD_DEBUG=bindings`? i.e. that after your change the kernel .so picks up the symbol from libtensorflow_jni.so even though its symbols aren't in the global table.

If so I'd leave a comment explaining why these symbols are exposed. I'd also file a bug explaining that we have three different copies of LookupInterface floating around causing resource ID lookup errors (custom op/kernel .so, language bindings like libtensorflow_jni.so and _pywrap_tensorflow_internal.so, and libtensorflow_framework.so) and then reference that bug in a TODO to remove the symbols from libtensorflow_jni.so. The way this is "working" right now seems extremely fragile.

And do you know why https://github.com/tensorflow/java/issues/82 was fixed for some folks but you're still having issues?

**Pull request closed without merging**
