### PR TITLE
NCCL 2.x document updates and removal of license file

### PR DESCRIPTION
**Pull request by tfboyd**

### CODE REVIEW

**Comment by case540** [comment]
Possibly rename the PR if you can. Unsure what "y8 d0 b" means

**Review by av8ramit — APPROVED** [review]

**Comment by stewbasic** [comment]
Just wondering if the removal of 3.0 from TF_CUDA_COMPUTE_CAPABILITIES in Dockerfile.devel-gpu was deliberate? IIUC this was explicitly added for #4002 and #4301.

**Comment by av8ramit** [comment]
The removal was deliberate. @tfboyd may have some more comments.

**Comment by tfboyd** [comment]
Those issues are almost 2 years old, but if we want the devel to have 3.0 we can add it back but if you are building from source, which is the purpose of that docker, you would set TF_CUDA_COMPUTE_CAPABILITIES to the GPU types you are using.  My motivation was to update it to match the binary release which starts at 3.5.

**Pull request merged**
