### PR TITLE
Fixed sign-compare build error for interpreter.h

### PR DESCRIPTION
**Pull request by Jibanprakash**
Fixed sign-compare build error for  interpreter.h.

### CODE REVIEW

**Comment by Jibanprakash** [comment]
I have signed the cla

**Comment by drpngx** [comment]
@aselle this is a one-liner.

**Comment by aselle** [comment]
What is the breakage caused by this? Is this a compiler warning you are trying to fix. One issue with this change is it creates a backward incompatible change to the c++ api. So I am inclined to suggets a cast in the interior of the function.

**Comment by Jibanprakash** [comment]
Yes, its a fix for compiler warning.
We are trying to use the same header and it causes build break for our code .

> 

> [   71s] /usr/include/tensorflow/tensorflow/contrib/lite/interpreter.h: In member function 'const std::pair<TfLiteNode, _TfLiteRegistration>* tflite::Interpreter::node_and_registration(int) const':
[   71s] /usr/include/tensorflow/tensorflow/contrib/lite/interpreter.h:212:20: **error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]**
[   71s]      if (node_index >= nodes_and_registration_.size() || node_index < 0)
[   71s]

cast in the interior function is an option.
but there are other places in the same file where the datatype is changed instead of a cast . Please check the below patch.

> FYI:   **Convert int -> size_t so that implicit conversion doesn't lose integer precision**

https://github.com/tensorflow/tensorflow/commit/f0d5d2047833c7221ce3be1690689ca1c6658add#diff-188a1b7e9814e7c3f77a5b4ec998b631

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment]
For backward compatibility the signature of the functions cannot change. So adding casts is really the only option.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment]
Closing due to lack of recent activity.

**Pull request closed without merging**
