### PR TITLE
Fix ./configure on Windows

### PR DESCRIPTION
**Pull request by meteorcloudy**
Make `configure` and `configure.py` work on Windows.
Fix http://ci.tensorflow.org/job/tf-master-win-bzl/1300/console
@yifeif @gunan

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Testing at http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/32/console

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by bladeolson** [comment]
UNSUBSCRIBE

**Comment by meteorcloudy** [comment]
Jenkins, test this please.

**Pull request merged**
