### PR TITLE
fixed the output description of bucketized column to one-hot encoded value

### PR DESCRIPTION
**Pull request by takumiohym**
Bucketized Column returns one-hot encoded value.
Should align to this page.
https://www.tensorflow.org/tutorials/structured_data/feature_columns#bucketized_columns

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Please convert docstring example to doctest and then we can check if the output changed

**Comment by gbaned** [comment]
@takumiohym  Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Comment by gbaned** [comment]
@takumiohym Any update on this PR? Please. Thanks!

**Comment by mihaimaruseac** [comment]
Closing as there has not been any update after feedback.

**Pull request closed without merging**
