### PR TITLE
add virtual START&END symbol to CRF and implement viterbi decoding

### PR DESCRIPTION
**Pull request by oohoops**
Two major changes.

    1. add virtual START and END symbol to CRF implementation
    2. reimplement viterbi decoding using tensorflow

The reason of the above modifications:

    1. The original implementation of CRF use no virtual START and END symbol. 
        However crf can use the transition weights that starting from the virtual START 
        symbol to labels of the first step.
    2. The original implementation of viterbi decoding uses numpy, which makes it 
        difficult to infer sequence labels in tensorflow computation graphs.

### CODE REVIEW

**Comment by drpngx** [comment]
Thanks! Could we add some unit tests here?

**Comment by jungle-cat** [comment]
@drpngx I've updated with several unit test

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by jungle-cat** [comment]
@drpngx previously, the code haven't been validated by pylint using Google code style. Now I've fixed most of them. 

And I'm wondering if these checks can be automatically enabled with I checked in new commits. It's my first time to contribute to tensorflow. Thanks so much.

**Comment by drpngx** [comment]
Yes that's part of the sanity check on Jenkins

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
you need to use stack

```
FAIL: //tensorflow/contrib/crf:crf_test (see /private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/local-opt/testlogs/tensorflow/contrib/crf/crf_test/test.log).
INFO: From Testing //tensorflow/contrib/crf:crf_test:
==================== Test output for //tensorflow/contrib/crf:crf_test:
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
.E...
======================================================================
ERROR: testCrfLogNorm (__main__.CrfTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/local-opt/bin/tensorflow/contrib/crf/crf_test.runfiles/org_tensorflow/tensorflow/contrib/crf/python/kernel_tests/crf_test.py", line 123, in testCrfLogNorm
    transition_params=constant_op.constant(transition_params))
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/local-opt/bin/tensorflow/contrib/crf/crf_test.runfiles/org_tensorflow/tensorflow/contrib/crf/python/ops/crf.py", line 105, in crf_log_norm
    inputs = array_ops.unpack(inputs, axis=1)
AttributeError: 'module' object has no attribute 'unpack'

----------------------------------------------------------------------
Ran 5 tests in 9.069s
```

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by jungle-cat** [comment]
previously, pack/unpack is used in the commitments. Now I use stack/unstack instead, and passed the unit tests in my local environment

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
@yuanbyu is that something you might want to look at? LMK or I can find someone else.

**Comment by jungle-cat** [comment]
The failure test seems to be mvn test, should I fix this or some one can help me with this? I've modified nothing on mvn test.

**Comment by drpngx** [comment]
Yes, it's an unrelated time out.

**Comment by rmlarsen** [comment]
@drpngx did you review this?

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
It looks like @alextp review the original version of this code. Would you mind taking a look?

**Comment by drpngx** [comment]
Sounds good. I didn't review. I could check the math but I'm not as confident with the API changes.

**Review by alextp — CHANGES_REQUESTED** [review]
Overall I'd like to minimize the API-breaking changes here. Also the diff is hard to read because lots of things got moved around.

I'm happy to point individual places where I think we're needlessly breaking the API here, let me know if you want me to do that.

Things like renaming parameters improve consistency but can break existing users.

**Comment by jungle-cat** [comment]
@alextp should I rename back input parameters, and make both api and parameters compatible with the original api ?

**Comment by alextp** [comment]
That would be great, thanks!

On Feb 6, 2017 23:40, "Feng Weiguo" <notifications@github.com> wrote:

@alextp <https://github.com/alextp> should I rename back input parameters,
and make both api and parameters compatible with the original api ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/pull/6819#issuecomment-277923410>,
or mute the thread

**Comment by vrv** [comment]
@jungle-cat any updates here?

**Comment by vrv** [comment]
ping for @jungle-cat -- I'll close by end of day if I don't hear back but feel free to send a new PR once you get time to look at this again. We'll try to keep the review cycle short.

**Comment by dandelionmane** [comment]
Closing as stalled per vrv@'s last comment.

**Pull request closed without merging**
