### PR TITLE
Branch 146316196

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by caisq** [comment]
Three tests failed in Python 3
//tensorflow/tools/docs:doc_generator_visitor_test                       FAILED in 1.5s
//tensorflow/tools/docs:generate_test                                    FAILED in 12.2s
//tensorflow/tools/docs:parser_test

The root causes seem to be the same: 
cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/parser_test.runfiles/org_tensorflow/tensorflow/tools/docs/parser.py", line 619, in generate_global_index
    for full_name, py_object in index.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by terrytangyuan** [comment]
Use `dict.items()` instead. `dict.iteritems()` was removed in python3

**Comment by caisq** [comment]
Will submit fixes internally before submitting again.

**Comment by martinwicke** [comment]
I should have fixed this already, let me just push again.

**Comment by burness** [comment]
@caisq  It seems that in the commit 47f4b3c, the markdown images of your links disappear! I'm reading your tfproc docs. PLS help to fix this, Thanks

**Comment by caisq** [comment]
@burness, the images have always been missing in this GitHub repo. To view the doc with working image links, please visit. https://www.tensorflow.org/versions/master/how_tos/debugger/

**Pull request closed without merging**
