### PR TITLE
Close (and reopen new) summary files at regular intervals

### PR DESCRIPTION
**Pull request by rahul003**
This helps prevent the summary file from growing too large, allowing easier management of summaries users are interested in. When uploading summaries to S3, it allows the user to clear up local disk space by uploading the files. S3 File system only uploads the file when the file closes, since it doesn't support append. 

From Tensorboard's point of view, it doesn't make a difference if it's a single file or multiple files. I'm open to feedback especially on the default values/behavior.

### CODE REVIEW

**Comment by nfelt** [comment]
Hi @rahul003 - thanks for the contribution and sorry for the long delay in response.  I understand the utility of being able to rotate event files used by the summary writer, and in fact we're looking into how we can add that into the base summary writing functionality.  Until we have that design fleshed out further I'd like to hold off on merging this, since I would want to make sure that any parameters exposed here aren't contradicting the lower-level API (e.g. we may not expose the ability to control the rotation period at first, or we might want it to be based on size rather than time, for example).

Thanks for your patience.

**Comment by gbaned** [comment]
@nfelt  Any update on this PR? Please. Thanks!

**Comment by nfelt** [comment]
No updates. I understand the use case, but the previous comment still applies - it would be better if we integrate functionality like this into the base summary writer so it's consistent everywhere, rather than specific to Estimator / SummarySaverHook, and we haven't really had a chance to explore that design sufficiently.

**Comment by gbaned** [comment]
@rahul003 Can you please check @nfelt's comments and keep us posted ? Thanks!

**Comment by rahul003** [comment]
Doesn't look like there's anything expected from me here. 

In any case, since I'm not working with TF much these days, it doesn't personally affect me. I am closing the PR.

**Pull request closed without merging**
