### PR TITLE
Improve ETA estimate for model.fit

### PR DESCRIPTION
**Pull request by ngc92**
This PR improves the keras.Progbar by allwoing it to skip the first step when determining the average duration of a step for ETA estimation. Since the first step can be significantly slower due to setup procedures, this helps to generate a better estimate for the remaining time.

### CODE REVIEW

**Review by qlzh727 — DISMISSED** [review]
Thanks for the PR. The change looks good.

**Comment by gbaned** [comment]
@ngc92 Can you please fix build failures ? Thanks!

**Review by qlzh727 — DISMISSED** [review]

**Review by qlzh727 — DISMISSED** [review]

**Review by rthadur — DISMISSED** [review]

**Comment by alextp** [comment]
cc @fchollet 

It's fine to do this by default and not add an argument. The argument doesn't really make sense here.

current == 0: time_per_step = 0
current == 1: time_per_step = now - self._start
current > 1: time_per_step = (now - self._time_after_first_step) / (steps - 1)
current == 2: set self._time_after_first_step

**Comment by gbaned** [comment]
@ngc92 Can you please check @alextp's comments and keep us posted. Thanks!

**Comment by gbaned** [comment]
@ngc92 Any update on this PR? Please. Thanks!

**Comment by ngc92** [comment]
@gbaned sorry, I currently only have my laptop, where running any bazel command either takes half a day or results in an OOM. Will look at this (and the other PR) next week with another computer

**Comment by ngc92** [comment]
@alextp I've removed the argument. I think there is a slight mistake in your comment, `current == 2: set self._time_after_first_step` should be `current == 1: set self._time_after_first_step`, right? The function is called after a step has been completed, so at `current==1` we get the time after the first step.

**Comment by alextp** [comment]
@ngc92 I think you're right.

**Review by qlzh727 — APPROVED** [review]
Sorry for the long wait. Approving.

**Review by rthadur — APPROVED** [review]

**Pull request merged**
