### PR TITLE
Replace legacy Java client instructions by deprecation notice

### PR DESCRIPTION
**Pull request by karllessard**
Deprecating this old version of the Java client.

Please see issue https://github.com/tensorflow/tensorflow/issues/58424 for more details.

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by bhack** [comment]
@karllessard @mihaimaruseac Let's see what happens with import/copybara job.

**Comment by mihaimaruseac** [comment]
Seems to be succeeding

**Comment by bhack** [comment]
Good!

**Comment by bhack** [comment]
Generally it could still happen a rollback after the merge (https://github.com/tensorflow/community/issues/425)

**Comment by mihaimaruseac** [comment]
The internal change needs to be approved and then copybara will (should?) automatically merge this.

**Pull request merged**
