### PR TITLE
Fix warmstart

### PR DESCRIPTION
**Pull request by yunjiangster**
Follow up on https://github.com/tensorflow/tensorflow/pull/31503

### CODE REVIEW

**Review by alextp — APPROVED** [review]

**Comment by rthadur** [comment]
@yunjiangster can you please check build failures ?

**Comment by yunjiangster** [comment]
@rthadur I incorrectly submitted the fix for r1.14. It's actually meant for r1.12. Will submit a new request. Sorry for the inconvenience.

**Comment by yunjiangster** [comment]
This is the new one, with two unit tests added: https://github.com/tensorflow/tensorflow/pull/31718

**Comment by rthadur** [comment]
@yunjiangster np, closing this PR, thank you

**Pull request closed without merging**
