### PR TITLE
Specify endianness in expected_result array to fix #15767.

### LINKED ISSUE #15767: Decode_raw_op_test failure on s390x
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: s390x Ubuntu 16.04 
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.4.1
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**: gcc 5.4.0
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: bazel test -c opt //tensorflow/python/kernel_tests:decode_raw_op_test

### Describe the problem
Observing a failure in [testToFloat16](https://github.com/tensorflow/tensorflow/blob/v1.4.1/tensorflow/python/kernel_tests/decode_raw_op_test.py#L77) sub test, while running `decode_raw_op_test`. It seems that the [byte-reversal logic](https://github.com/tensorflow/tensorflow/blob/v1.4.1/tensorflow/core/kernels/decode_raw_op.cc#L80) for big endian is not needed for **float16 input**(and float16 output). While the other sub tests like int16/uint16 which have byte array input need byte-swapping for consistent results. What would be the best way to correct this?
@rmlarsen, @jiefangxuanyan , Could you please share your thoughts on this?
 
### Source code / logs
```
FAIL: testToFloat16 (__main__.DecodeRawOpTest)
----------------------------------------------------------------------
.
AssertionError:
Arrays are not equal
(mismatch 100.0%)
 x: [repr failed for <matrix>: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()]
 y: array([[  3.576279e-06,   1.144409e-05,   1.156330e-05,   4.053116e-06]], dtype=float16)
----------------------------------------------------------------------
Ran 7 tests in 0.089s

FAILED (failures=1)
not equal where =  (array([0, 0, 0, 0]), array([0, 1, 2, 3]))
not equal lhs =  [[ 1. -2. -3.  4.]]
not equal rhs =  [  3.57627869e-06   1.14440918e-05   1.15633011e-05   4.05311584e-06]
```

### PR DESCRIPTION
**Pull request by jiefangxuanyan**

### CODE REVIEW

**Comment by caisq** [comment]
Gentle ping? @rmlarsen @benoitsteiner

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @rmlarsen, @benoitsteiner: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @rmlarsen, @benoitsteiner: It has been 29 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Review by rmlarsen — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request merged**
