### PR TITLE
Update monitors.py

### PR DESCRIPTION
**Pull request by alanyee**
Renaming PrintTensor to Logging Tensor

### CODE REVIEW

**Comment by jhseu** [comment]
Up to Jianwei, but I'm assuming we're not taking renames here and will do any necessary renames during the move to core.

**Comment by alanyee** [comment]
Ah, I just saw a TODO on renaming

**Comment by jhseu** [comment]
Yeah, I think the blocker is doing the mass rename internally.

**Comment by terrytangyuan** [comment]
@jhseu Only renaming the ones in contrib, right?

**Comment by jhseu** [comment]
@terrytangyuan I meant also updating internal Google code that might refer to it.

Given that there's a TF core equivalent called LoggingTensorHook, I'll close this out.

**Pull request closed without merging**
