### PR TITLE
Branch 145839627

### PR DESCRIPTION
**Pull request by zheng-xq**
Merging internal changes.

### CODE REVIEW

**Comment by zheng-xq** [comment]
@tensorflow-jenkins, test this please.

**Comment by gunan** [comment]
Need change 145852218 to fix python 3 build, maybe even more.

**Comment by rmlarsen** [comment]
Perhaps we can discard this?

**Comment by zheng-xq** [comment]
Sure. Thanks

**Comment by zheng-xq** [comment]
Discarding this CL

**Pull request closed without merging**
