### PR TITLE
nsync dep updates

### PR DESCRIPTION
**Pull request by perfinion**
A new version of nsync is released, this updates the workspace.bzl and adds nsync to the libs that can be unbundled. I've packaged nsync on Gentoo Linux and tested the full unbundled build.

The CMake build is also updated to the latest version, the patch is no longer required and is removed. I have tested the cmake build on my machine but the CI needs to test windows since I can't.

The last commits update ./configure to handle adding TF_SYSTEM_LIBS and an option to disable stripping.

@m3bm3b, can you review too?

### CODE REVIEW

**Comment by perfinion** [comment]
The mirroring will need to be updated by whoever has the perms for that, I already added the URL:
"https://mirror.bazel.build/github.com/google/nsync/archive/1.20.1.tar.gz"
should point to: "https://github.com/google/nsync/archive/1.20.1.tar.gz",

@gunan can you trigger the tests so the windows CMake build runs, thats the most important bit :)

**Comment by perfinion** [comment]
Looks like the windows compile and install succeed in https://source.cloud.google.com/results/invocations/85798d52-c506-4199-b58a-b95d5e54b2cc/log Line 3787. After that the tests fail horribly but that looks like a PYTHON_PATH issue maybe and unrelated to this.

**Comment by m3bm3b** [comment]
I managed to build (thought didn't run tests of) tensorflow using 
cmake on Linux, MacOS, and Windows using this pull request.

**Review by gunan — DISMISSED** [review]

**Comment by gunan** [comment]
Great, thanks for testing.
Then I will proceed with the merge.

**Comment by drpngx** [comment]
@samikama has some reservations about this on #20003.

**Comment by perfinion** [comment]
@drpngx I dropped the BAZEL_STRIP commit and rebased everything. @samikama can remove it completely in #20003 instead.

**Comment by perfinion** [comment]
@gunan no worries, rebased :)

**Pull request closed without merging**
