### PR TITLE
Respect inference type in DefaultQuantParamsPass 

### PR DESCRIPTION
**Pull request by lgeiger**
The `DefaultQuantParamsPass` allows to use fallback to a default quantization range when a tensor doesn't have quantization parameters. This can be useful for latency tests when fake_quant ops might not be correctly placed.
However, the pass currently doesn't respect the inferece type and thus will always add `uint8` quantize/dequantize pairs. This PR changes the pass to correctly set the `dtype` depending on `quant_specs.inference_type`.

### CODE REVIEW

**Comment by jpienaar** [comment]
This looks good to me, but assigning to Feng who knows this pass much better than me.

**Review by liufengdb — APPROVED** [review]
LGTM! thanks!

**Comment by lgeiger** [comment]
Looks like the Windows CI errors are unrelated (`Internal CI infrastructure error.`). Should I rebase onto master or can the failures be ignored?

**Comment by jpienaar** [comment]
Lets try and prod it to see if makes it through Window CI side.

**Review by jpienaar — APPROVED** [review]

**Comment by lgeiger** [comment]
Looks like the windows tests are still failing due to an unreleated build error in `tensorflow/core/kernels:adjust_contrast_op_gpu`.

**Pull request merged**
