### PR TITLE
(DO NOT MERGE) Branch 153227038

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by drpngx** [comment]
Thanks! Do you need this now? I am still doing the merge from github.

**Comment by caisq** [comment]
@drpngx no rush. I can wait for your pull to go through first.

**Comment by drpngx** [comment]
OK, thanks! Feel free to merge if you need to and I can resolve later, but otherwise it would be easier to wait.

**Comment by caisq** [comment]
OK. I'll just leave the PR open for testing purposes. I'll open a new one once your pull is done.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Pull request closed without merging**
