### PR TITLE
De-Bazel pip_smoke_test sanity check

### PR DESCRIPTION
**Pull request by Androbin**
See https://github.com/tensorflow/tensorflow/pull/15368#issuecomment-354156560 for reference.
@gunan @martinwicke /cc

### CODE REVIEW

**Comment by Androbin** [comment]
@gunan Same thing as with #15677?

**Comment by Androbin** [comment]
@gunan Same thing as with #15677?

**Comment by Androbin** [comment]
@gunan Friendly ping.

**Comment by Androbin** [comment]
@martinwicke Friendly ping.

**Review by martinwicke — APPROVED** [review]
Let's make sure it runs, but looks good otherwise.

**Pull request merged**
