### PR TITLE
Fix sample code of embedding_viz

### PR DESCRIPTION
**Pull request by sugyan**
According to [projector_config.proto](https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/contrib/tensorboard/plugins/projector/projector_config.proto), `single_image_dim` is also `SpriteMetadata` field.

### CODE REVIEW

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by sugyan** [comment]
This is same as #6321. Should I close this?

**Review by dsmilkov — APPROVED** [review]

**Comment by dsmilkov** [comment]
Yes, it is the same as #6321 except that you are merging directly into the r0.12 release. @caisq, up to you if you want to cherry pick this into the r0.12 branch.

Thanks @sugyan for the contribution!

**Comment by martinwicke** [comment]
@dsmilkov's added merge commit is fine for CLA.

**Pull request merged**
