### PR TITLE
Added support for missing dtypes in tf.truncated_div 

### LINKED ISSUE #58019: tf.raw_ops.TruncateDiv documentation is not consistent
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

_No response_

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current Behaviour?

```shell
`tf.raw_ops.TruncateDiv` is only supporting integer values, while it is written in the first line in the documentation. The parameters section is saying that all numeric dtypes are allowed.
```

### Standalone code to reproduce the issue

```shell
tf.raw_ops.TruncateDiv(x=np.array(1.), y=np.array(1.))
```

### Relevant log output

```shell
>>> tf.raw_ops.TruncateDiv(x=np.array(1.), y=np.array(1.))
2022-10-07 22:46:30.214942: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-10-07 22:46:30.214981: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-10-07 22:46:30.214999: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (653368f87bf1): /proc/driver/nvidia/version does not exist
2022-10-07 22:46:30.215221: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/tf_export.py", line 400, in wrapper
    return f(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 11558, in truncate_div
    return truncate_div_eager_fallback(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 11603, in truncate_div_eager_fallback
    _result = _execute.execute(b"TruncateDiv", 1, inputs=_inputs_flat,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node TruncateDiv}} = TruncateDiv[T=DT_DOUBLE]
All kernels registered for op TruncateDiv:
  device='GPU'; T in [DT_UINT64]
  device='GPU'; T in [DT_UINT32]
  device='GPU'; T in [DT_INT8]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_INT16]
  device='GPU'; T in [DT_UINT16]
  device='GPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT64]
  device='CPU'; T in [DT_UINT32]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_UINT8]
 [Op:TruncateDiv]
```
</details>

### PR DESCRIPTION
**Pull request by mohantym**
Added support for missing dtypes in tf.truncated_div . Fixes #58019

### CODE REVIEW

**Comment by cantonios** [comment]
Commented on the bug, but I think we should instead disable the op definition for non-integer types in [math_ops.cc](https://github.com/tensorflow/tensorflow/blob/c676c85dd4d48956729857fe98981e50bd80e0a5/tensorflow/core/ops/math_ops.cc#L520).

Instead of `.BINARY_MORE()`, that should probably read
```
.Input("x: T").Input("y: T").Output("z: T").Attr(
      "T: {uint8, int8, uint16, int16, int32, uint32, uint64, int64}")
```

**Comment by JW1992** [comment]
I agree with Antonio.

**Comment by mohantym** [comment]
Closing  this PR considering feasibility from this [comment](https://github.com/tensorflow/tensorflow/issues/58019#issuecomment-1302289540).

**Comment by cantonios** [comment]
Well, I was suggesting the PR should be what I put above that changes the op definition.  And @bhack suggested to align the CPU/GPU types.

**Pull request closed without merging**
