### PR TITLE
update to 3.6.x for fixes with Visual Studio 2017

### PR DESCRIPTION
**Pull request by kingofthebongo2008**
Update for fixes for visual studio std::call_once

### CODE REVIEW

**Comment by gunan** [comment]
Unfortunately, we have to stick to using tags as they are more stable. Would you like to change to using a tag?

**Comment by kingofthebongo2008** [comment]
can you speak with protobuffer people to make 3.6.1 tag?
they have promised to do this 2 months ago
still not there
https://github.com/google/protobuf

**Comment by gunan** [comment]
Adding @xfxyjwf and @acozzette to comment.

**Comment by xfxyjwf** [comment]
Isn't a v3.6.1 release already there?
https://github.com/google/protobuf/releases/tag/v3.6.1

**Comment by kingofthebongo2008** [comment]
i have noticed this, will change the request

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
Closing the PR as there has not been activity for a while.
Please reopen once you push the recommended changes.

**Pull request closed without merging**
