### PR TITLE
r1.12-rc1 cherry-pick request: Update to new RBE toolchain with Clang 8.0.0 r340178.

### PR DESCRIPTION
**Pull request by yifeif**
PiperOrigin-RevId: 216590129

Fix lstm_test&layer_norm_lstm_test w/ Clang 8.0.0
PiperOrigin-RevId: 216475683

Fix lite/kernels:add_test for Clang 8.0.0
PiperOrigin-RevId: 216455772

Fix mul_test with Clang 8.0.0
PiperOrigin-RevId: 216570443

This is to bump the CI image so that Kokoro builds pass on release branch.
Also cherry-pick three tflite test fixes that failed in clang 8.0.0.

### CODE REVIEW

**Review by tatatodd — DISMISSED** [review]

**Comment by yifeif** [comment]
@MarkDaoust Hi Mark, do you know what might be causing the build_docs_test to fail here:
======================================================================
ERROR: testBuildDocs (__main__.BuildDocsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/f/w/run/bazel-out/k8-opt/bin/tensorflow/tools/docs/build_docs_test.runfiles/org_tensorflow/tensorflow/tools/docs/build_docs_test.py", line 64, in testBuildDocs
    raise RuntimeError(msg)
RuntimeError:           Modules nested too deep:
tf.contrib.estimator.python.estimator.head.array_ops.common_shapes.errors.c_api.ctypes.util


Thanks!

**Comment by MarkDaoust** [comment]
Wow. It doesn't make any sense that this PR would cause this. This is a pure-python test.

This looks just like a bug @case540 and I hit with that estimator migration he's working on.

Last time, we saw that a python module importing implementation details from estimator could cause this.

something like:

```
from tensorflow.contrib.estimator.python import estimator 
```

Injects the "python" module back into the `tf.contrib.estimator` namespace.
But I really don't understand why this would be happening now.

Try adding "tf.contrib.estimator":["python"] to [this dict](https://github.com/yifeif/tensorflow/blob/cherrypicks_IJGFA/tensorflow/tools/docs/generate_lib.py#L228).

**Comment by yifeif** [comment]
Thanks for taking a look @MarkDaoust!
It is a bit odd. There is no python version change with the image update in this PR either.

**Review by annarev — APPROVED** [review]

**Review by tatatodd — APPROVED** [review]

**Comment by tatatodd** [comment]
FYI I just merged the recent changes to the branch (shown earlier in this comment thread), and now all presubmits have passed.  None of the changes that were merged should have affected the build_docs_test, but then again, this PR shouldn't have affected build_docs_test in the first place.  ;)

I'm merging this in, since it fixes TF 1.12 presubmits.  Or at least it enables them to pass at least some of the time; we can investigate the weird build_docs_test separately.

**Pull request merged**
