### PR TITLE
[TF:TRT] Cleanup TRTOptimizer and convert_graph

### PR DESCRIPTION
**Pull request by christopherbate**
This change refactors `convert_graph` and `trt_optimization_pass`. 
De-duplicates the amount of data structures holding "conversion parameters". Each conversion parameter was duplicated inside of TRTOptimizationPass class because the `ConversionParams` struct contained const references to state variables. State variables were moved out of the struct and instead passed as function arguments. The `ConversionParams` struct was then moved into the `TRTOptimizationPass` class to make it clear what object owns the struct as an API dependency.
The function `ConvertAfterShapes` is renamed to `ConvertGraph`.
Various debugging output code was removed as it appears to be unused and an artifact of the original implementation.

### CODE REVIEW

**Comment by christopherbate** [comment]
This PR is a dependency of #53659

**Review by bixia1 — APPROVED** [review]

**Comment by bixia1** [comment]
Can you please fix this error:
[third_party/tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op_test.cc:92](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op_test.cc?l=92&ws=tap-prod-presubmit/172369347&snapshot=2):7: error: no type named 'ConversionParams' in namespace 'tensorflow::tensorrt::convert'; did you mean 'convert::TRTOptimizationPass::ConversionParams'?
      convert::ConversionParams params;
      ^~~~~~~~~~~~~~~~~~~~~~~~~
      convert::TRTOptimizationPass::ConversionParams
[./third_party/tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.h:43](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.h?l=43&ws=tap-prod-presubmit/172369347&snapshot=2):10: note: 'convert::TRTOptimizationPass::ConversionParams' declared here
  struct ConversionParams {
         ^
[third_party/tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op_test.cc:115](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op_test.cc?l=115&ws=tap-prod-presubmit/172369347&snapshot=2):19: error: reference to type 'const tensorflow::tensorrt::convert::EngineInfo' could not bind to an rvalue of type 'std::nullptr_t'
          params, nullptr, info, 1, shape_vec, &profile, &segment_string));

**Comment by gbaned** [comment]
@christopherbate Can you please check @bixia1's comments and keep us posted ? Thanks!

**Comment by christopherbate** [comment]
I rebased, squashed update to fix the mentioned errors.

**Review by bixia1 — APPROVED** [review]

**Comment by bixia1** [comment]
I got this test failur
[casttest.log](https://github.com/tensorflow/tensorflow/files/8155552/casttest.log)
e

**Comment by christopherbate** [comment]
Sorry was an error when I split this PR off from the one for the conditioning pass. Am updating this now.

**Comment by christopherbate** [comment]
rebased, squashed fixes for the failing  test fix. Issue was the graph_def being modified by the MaybeRewriteCast() function was a copy of the input graph def, when really it needed to be a reference.

**Review by bixia1 — APPROVED** [review]

**Review by bixia1 — APPROVED** [review]

**Pull request merged**
