### PR TITLE
Remove dependency on TF constant folding pass in mlir/lite

### PR DESCRIPTION
**Pull request by lgeiger**
`mlir/lite` currently depends on the `mlir/tensorflow:tf_dialect_passes` and `mlir/tensorflow:tf_dialect_lib` bazel targets which pull in the `mlir/tensorflow` constant folding pass which adds a huge amount of dependencies.
As far as I can tell it is not required anywhere in `mlir/lite`, so this PR splits out the decode constant pass into its own very small build target which can be used by `mlir/tflite` directly.

This should greatly reduce the build time required to build the `mlir/lite` components. @jpienaar could you take a look?

### CODE REVIEW

**Review by jpienaar — DISMISSED** [review]
Indeed the dialect fallback constant folding adds quite a lot of dependencies. We've even been meaning to have a target which doesn't have it (well and also one to enable TFL dialect constant folding fallback :-)).

**Comment by lgeiger** [comment]
@jpienaar Thanks for the fast review. Do you think this could be cherry-picked onto the r2.2 branch as well?

I am trying to reproduce the build failure locally, but the build takes hours without a remote cache. In the meantime e0a9485c54664a273146eca7fc4601eef2d75f99 might fix the failure.

**Comment by lgeiger** [comment]
e0a9485c54664a273146eca7fc4601eef2d75f99  fixed the `//tensorflow/compiler/mlir/tensorflow/tests:decode_constant.mlir.test` test, though for some reason `tensorflow/compiler/mlir/lite/tests/end2end:ophint_lstm.pbtxt.test` and `tensorflow/compiler/mlir/lite/tests/end2end:fake_quant_per_channel.pbtxt.test` are still failing. @jpienaar Any idea what's going on there?

**Comment by jpienaar** [comment]
I don't see any breakages if I patch this one in locally ...

**Review by jpienaar — DISMISSED** [review]

**Comment by jpienaar** [comment]
Was in wrong terminal when I ran the test, too many open terminals, checking again.

**Comment by lgeiger** [comment]
I added the full `tf_dialect_passes` back to the `tf_to_tfl_flatbuffer` target in 1e29d6b65bc7f4b3819d8d17cbd9a9a946252415 which fixes the test failures.

**Comment by jpienaar** [comment]
Seems to be missing a few dependencies still, but I can do a quick update and send it out.

**Pull request merged**
