### PR TITLE
Give Grappler hints about function XLA compilation so it can selectively apply compatible optimizations

### PR DESCRIPTION
**Pull request by sillly-milly**
Some Grappler optimizations can cause problems for XLA. This was first discovered by the MemoryOptimizer pass creating TemporaryVariable ops without knowing if the later compiling XLA device implemented the TemporaryVariable OpKernel [[issue](https://github.com/tensorflow/tensorflow/issues/30580)].

The first fix for this was to disable Grappler for any functions called from an XlaLaunch node [[commit 1](https://github.com/tensorflow/tensorflow/commit/471b73c238709fb796929eb412f1dab763b3f8cc)].
It was found that this isn't sufficient, as some functions can be encapsulated out of the main XlaLaunch cluster function e.g. While ops, so a later fix was added to also disable Grappler for any functions transitively called by an XlaLaunch function [[commit 2](https://github.com/tensorflow/tensorflow/commit/e0bb74087f440394f6df00c5c7ff36e50d23132a)].

However, a more general approach may be to introduce hints which Grappler can use to avoid making certain XLA-incompatible optimizations, allowing them to work together.
This PR introduces a GrapplerXlaHints struct which is populated by a GenerateXlaHints function, which allows individual Grappler optimizers to switch themselves off depending on the GrapplerItem's XLA hints.
Currently the PR disables the constant_folding, arithmetic_optimizer and the SchedulingPass of the MemoryOptimizer based on these hints.

Note that this will cause a change in behaviour where the immediate XlaLaunch functions will now go through Grappler where they otherwise weren't before commit 1 (with appropriate passes selectively disabling themselves).

I have added a test which passes locally that checks the hints are generated properly for an example call tree.
I have also linted all files according to [this guide](https://www.tensorflow.org/community/contribute/code_style).

### CODE REVIEW

**Comment by sanjoy** [comment]
Is this when using the `jit_compile` (used to be `experimental_compile`) API?

**Comment by markf-gc** [comment]
I believe so, or really anything that could result in XlaLaunch nodes being in the graph.

**Comment by cheshire** [comment]
Sorry I have a hard trouble following why do we need a whole struct with "hints"? Why is simple boolean "are we inside a compiled cluster" not sufficient?

**Comment by markf-gc** [comment]
> Sorry I have a hard trouble following why do we need a whole struct with "hints"? Why is simple boolean "are we inside a compiled cluster" not sufficient?

My vision for this closer XLA<->Grappler integration is that we try to allow them to work together as much as is possible, and try to avoid unconditionally disabling entire grappler passes for rare XLA<->Grappler interactions.
For example, in this diff, I found the arithmetic optimizer pass only needs disabling when the XLA graph contains a subgraph that will be extracted out of it later:
```
// Do not rearrange arithmetic if the item will be compiled by XLA and
// contains an extracted subgraph, since the rearrangement can interleave the
// subgraphs in such a way as to cause a host<->device communication deadlock.
```
I think this is quite a rare situation, so disabling the arithmetic optimizer pass unconditionally for all XLA graphs just for this situation seems overkill.

**Comment by cheshire** [comment]
> My vision for this closer XLA<->Grappler integration is that we try to allow them to work together as much as is possible, and try to avoid unconditionally disabling entire grappler passes for rare XLA<->Grappler interactions

But why? Is there any purpose in doing the optimizations in grappler which can be done later in XLA?

**Comment by gbaned** [comment]
@markf-gc Can you please check @cheshire's comments and keep us posted ? Thanks!

**Comment by gbaned** [comment]
@markf-gc Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@markf-gc Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@markf-gc Any update on this PR? Please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 19 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
