### PR TITLE
Tflite windows

### PR DESCRIPTION
**Pull request by shaurya0**
Hi,

I've ported tensorflow lite to compile with msvc for my own development purposes. It was relatively easy to get it to compile with Visual Studio 2017. The main differences/issues were:

I chose to use cmake since I'm not so familiar with bazel. I'm hoping the CMakeLists.txt file can be used for other purposes than just compiling for msvc.
needed latest version of gemmlowp which is not dependent on POSIX functionality
compiler errors due to narrowing conversions double -> float due to lack of "f" suffix on float numbers in unit tests
Convolution generic optimized takes prohibitively long to compile with msvc
added an operating systems abstraction layer on top of some of the OS functions which are used such as mmap files and loading of dynamic libraries
All unit tests pass except for the ones with have the "EXPECT_DEATH" macro. The testdata filepaths in model_test.cc also need to be made cross platform.

the cmake command i used to compile with visual studio 2017 on my windows machine:
`
cmake -G"Visual Studio 15 2017 Win64" -DMSVC_RUNTIME=static -DGTEST_LIB_DIR="C:/SDKS/googletest/lib" -DGMOCK_LIB_DIR="C:/SDKS/googletest/lib" ..\tensorflow\contrib\lite`

### CODE REVIEW

**Comment by apollo-time** [comment]
It's very good to build msvc.
How can I built tf lite with visual studio on windows 32bit?

**Comment by petewarden** [comment]
Thanks for this change, it was clearly a lot of work and it would be great to get TF Lite on Windows!

I've asked @mrry for some advice on the float narrowing changes, since he would have had to deal with this for mainline TensorFlow, and without good tests it's likely that doubles will creep back into the code.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 123 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 138 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 153 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 168 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment]
We now support in the latest nightly bazel windows builds for tflite and toco. Hope this helps.

**Comment by tworuler** [comment]
@aselle , what's the command of building tflite on windows? I tried `bazel build -c opt tensorflow/contrib/lite/toco:toco`, but got below errors.
```
ERROR: D:/src/tensorflow/tensorflow/tensorflow/contrib/lite/kernels/BUILD:57:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels:eigen_support' failed (Exit 2): cl.exe failed: error executing command
  cd C:/users/administrator/_bazel_administrator/7sou473m/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/Administrator/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/Users/Administrator/Anaconda3/lib/site-packages
    SET TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
    SET TF_DOWNLOAD_CLANG=0
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL_SYCL=0
    SET TMP=C:\Users\ADMINI~1\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/genfiles /Ibazel-out/x64_windows-opt/bin /Iexternal/bazel_tools /Ibazel-out/x64_windows-opt/genfiles/external/bazel_tools /Ibazel-out/x64_windows-opt/bin/external/bazel_tools /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/genfiles/external/local_config_sycl /Ibazel-out/x64_windows-opt/bin/external/local_config_sycl /Iexternal/gemmlowp /Ibazel-out/x64_windows-opt/genfiles/external/gemmlowp /Ibazel-out/x64_windows-opt/bin/external/gemmlowp /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /showIncludes /MD /O2 /DNDEBUG -w -DFARMHASH_NO_CXX_STRING /DTF_COMPILE_LIBRARY -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK /DEIGEN_HAS_C99_MATH /DEIGEN_AVOID_STL_ARRAY /Fobazel-out/x64_windows-opt/bin/tensorflow/contrib/lite/kernels/_objs/eigen_support/eigen_support.obj /c tensorflow/contrib/lite/kernels/eigen_support.cc
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(195): error C2059: syntax error: '('
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(196): error C2065: 'N': undeclared identifier
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(196): error C2975: 'n': invalid template argument for 'EigenForTFLite::array', expected compile-time constant expression
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(21): note: see declaration of 'n'
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(196): error C2143: syntax error: missing ';' before '{'
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(196): error C2447: '{': missing function header (old-style formal list?)
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(199): error C2059: syntax error: '('
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(200): error C2065: 'N': undeclared identifier
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(200): error C2975: 'n': invalid template argument for 'EigenForTFLite::array', expected compile-time constant expression
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(21): note: see declaration of 'n'
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(200): error C2143: syntax error: missing ';' before '{'
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\EmulateArray.h(200): error C2447: '{': missing function header (old-style formal list?)
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\CXX11Workarounds.h(50): error C2059: syntax error: '('
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\CXX11Workarounds.h(50): error C2143: syntax error: missing ';' before '{'
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\CXX11Workarounds.h(50): error C2447: '{': missing function header (old-style formal list?)
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\CXX11Workarounds.h(51): error C2059: syntax error: '('
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\CXX11Workarounds.h(51): error C2143: syntax error: missing ';' before '{'
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\CXX11Workarounds.h(51): error C2447: '{': missing function header (old-style formal list?)
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\CXX11Workarounds.h(52): error C2059: syntax error: '('
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\CXX11Workarounds.h(52): error C2143: syntax error: missing ';' before '{'
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src\util\CXX11Workarounds.h(52): error C2447: '{': missing function header (old-style formal list?)
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/util/CXX11Meta.h(297): error C2246: 'EigenForTFLite::internal::sum_op::Identity': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/util/CXX11Meta.h(301): error C2246: 'EigenForTFLite::internal::product_op::Identity': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/EventCount.h(190): error C2246: 'EigenForTFLite::EventCount::kStackBits': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/EventCount.h(191): error C2246: 'EigenForTFLite::EventCount::kStackMask': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/EventCount.h(192): error C2246: 'EigenForTFLite::EventCount::kWaiterBits': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/EventCount.h(193): error C2246: 'EigenForTFLite::EventCount::kWaiterShift': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/EventCount.h(195): error C2246: 'EigenForTFLite::EventCount::kWaiterMask': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/EventCount.h(196): error C2246: 'EigenForTFLite::EventCount::kWaiterInc': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/EventCount.h(197): error C2246: 'EigenForTFLite::EventCount::kEpochBits': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/EventCount.h(198): error C2246: 'EigenForTFLite::EventCount::kEpochShift': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/EventCount.h(199): error C2246: 'EigenForTFLite::EventCount::kEpochMask': illegal static data member in locally defined class
c:\users\administrator\_bazel_administrator\7sou473m\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/EventCount.h(200): error C2246: 'EigenForTFLite::EventCount::kEpochInc': illegal static data member in locally defined class
Target //tensorflow/contrib/lite/toco:toco failed to build
INFO: Elapsed time: 53.367s, Critical Path: 10.87s
INFO: 116 processes: 116 local.
FAILED: Build did NOT complete successfully
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment]
@tworuler, that problem should be fixed in head

**Comment by jnorwood** [comment]
I'm looking at the cmake windows build again.  A couple of changes were necessary in the download_dependencies.sh to get that tflite-windows branch to work. I update GEMMLOWP_URL to the current one used in tensorflow/workspace.bzl.  It was necessary to get rid of the pthread references.  I also backed up the FLATBUFFERS_URL to 1.8.0, since tflite apparently is not compatible with the latest flatbuffer.

GEMMLOWP_URL="https://mirror.bazel.build/github.com/google/gemmlowp/archive/38ebac7b059e84692f53e5938f97a9943c120d98.zip"

FLATBUFFERS_URL="https://github.com/google/flatbuffers/archive/v1.8.0.zip"

Also, just as a note, you have to run this download_dependencies.sh from the tensorflow root.  I don't think I saw that mentioned anywhere.

Also  you need to build googletest somewhere with options compatible.  With these changes, it that tflite-windows branch, from below link,  passed 40 of 41 tests executing in msvc environment.  The skip_gram_test fails ... haven't looked at that yet.

https://github.com/shaurya0/tensorflow/tree/tflite-windows

**Comment by MaxPalmer-UH** [comment]
> We now support in the latest nightly bazel windows builds for tflite and toco. Hope this helps.

Is this true? So if I download the nightly for Windows x64, it contains the binaries to run TFLite models on Windows?

**Pull request closed without merging**
