### PR TITLE
[ROCm] Enabling/Disabling some unit tests (via no_rocm tag) on the ROCm platform

### PR DESCRIPTION
**Pull request by deven-amd**
all commits either add or remove the `no_rocm` tag from unit-tests to disable / enable them...nothing else.

-----------------------------------------------

/cc @cheshire @chsigg @nvining-work

### CODE REVIEW

**Review by cheshire — APPROVED** [review]

**Comment by deven-amd** [comment]
The failure in `Linux GPU` CI job does not seem to be related to this PR. 

There is only 1 failure in that CI job in the unit test `//tensorflow/compiler/tests:image_ops_test_gpu`, and this PR does not touch that test.

**Comment by deven-amd** [comment]
re-based PR on tip in hopes of getting rid of the error in `Linux GPU` Ci job

**Comment by deven-amd** [comment]
still getting the error in `Linux GPU` CI job, and this time I am unable to access the log file.

@gbaned, can you help? thanks

**Comment by deven-amd** [comment]
able to access the log file (for the failed CI job) now....it seems that the same unit test is failing again `
//tensorflow/compiler/tests:image_ops_test_gpu`.  Fairly certain that the failure is not related to the changes in this PR.  

What to do next?

**Comment by chsigg** [comment]
> able to access the log file (for the failed CI job) now....it seems that the same unit test is failing again ` //tensorflow/compiler/tests:image_ops_test_gpu`. Fairly certain that the failure is not related to the changes in this PR.
> 
> What to do next?

Indeed, this failure is unrelated to this change. I will get it merged.

**Pull request merged**
