### PR TITLE
Create toolchain for AARCH64 builds in Docker container

### PR DESCRIPTION
**Pull request by elfringham**
A new docker container was needed to provide a toolchain with DUAL_ABI enabled for manylinux2014_aarch64

### CODE REVIEW

**Comment by elfringham** [comment]
Found some unexpected unit test failures so will convert to draft for the moment.

**Comment by angerson** [comment]
Thanks for working on this. Having AARCH64 build configs available for the community seems like a nice improvement.

For the dockerfiles directory: this directory in tensorflow/tensorflow is explicitly for the official build environment only, so the aarch64 variants will have to go somewhere else. I'd actually recommend putting your work into [the SIG Build repository](https://github.com/tensorflow/build/blob/master/CONTRIBUTING.md), which would make ownership obvious and would remove coupling. That way you'll also be able to make the containers work only for aarc64 instead of trying to make them work for both. You'll have to sync up with the source directory manually though (if there are features you want to keep in sync, anyway; we wouldn't enforce anything).

For the toolchains directory: I don't think is this the ideal place for these either. I'd like to make sure that aarch-related files and logic are completely separate from the rest of the logic, or at least very cleanly demarcated (e.g. by being in their own repository or directory). Our team isn't supporting the new stuff, but if the aarch64 files live right next to the official config, it's not clear who owns what or how everything works. Ideally, I'd like to see this as a separate repository, but I don't think that's going to work if we want users to be able to build with AARCH64 without modifying the source code, unless you start a new TF fork just for the toolchain changes... nothing I can think of seems ideal. Do you have any suggestions here?

**Comment by elfringham** [comment]
I have removed the code for the Docker container from this PR so we can concentrate solely on the toolchain. I have reworked this to remove the association with the tf_sigbuild toolchains. The load in workspace2.bzl is clearly in the section that loads third party code.
It is my firm expectation that the AARCH64 builds that are triggered from the github actions ARM_CI/ARM_CD will move to make use of this toolchain in order to meet the request to build with Dual ABI enabled and bring them into line with the x86 builds. As such I believe that it needs to be part of the TensorFlow tree.

**Comment by gbaned** [comment]
Hi @angerson Can you please review this PR ? Thank you!

**Comment by learning-to-play** [comment]
@jam14j @BrianWieder Could you please share your instructions for using your Clang images for CPU builds with @elfringham?

**Comment by angerson** [comment]
> It is my firm expectation that the AARCH64 builds that are triggered from the github actions ARM_CI/ARM_CD will move to make use of this toolchain in order to meet the request to build with Dual ABI enabled and bring them into line with the x86 builds. As such I believe that it needs to be part of the TensorFlow tree.

Okay, that makes sense. Please add a README.md file to the cpus/aarch64 directory that explicitly explains this same reasoning, shows that this is a community-owned directory, and notes that you are the code owner for questions / issues.

**Comment by elfringham** [comment]
@angerson  README.md added as requested

**Review by angerson — APPROVED** [review]
Thanks for adding the README. Looks good to me.

**Comment by elfringham** [comment]
About failing the 'Code Check - Changed Files'. The failure is on some code that I copied from third_party/gpus/crosstool/BUILD.tpl and if I run buildifier on that file, then it also fails with the same error.
`
tf-docker /tf/tensorflow > buildifier -v -mode=check third_party/gpus/crosstool/BUILD.tpl
third_party/gpus/crosstool/BUILD.tpl:62:37: syntax error near %
third_party/gpus/crosstool/BUILD.tpl # reformat
`
What is supposed to happen in this case? Is this a real bug that somehow got in despite the buildifier check, or is it a bug in buildifier itself? I suspect the latter as it is in a BUILD template.

**Pull request merged**
