### PR TITLE
Alternative fix for tf.contrib.ffmpeg.decode_video error

### LINKED ISSUE #20348: tf.contrib.ffmpeg.decode_video error
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: ('v1.8.0-4015-g44a1f241bc', '1.9.0-rc0')
- **Python version**: 2.7.15rc1
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: 6.4.0
- **CUDA/cuDNN version**: 9.0.176/7.0.5
- **GPU model and memory**: GeForce GTX 1080 Ti (11GB)
- **Exact command to reproduce**:
```python
import tensorflow as tf
with tf.Session() as sess:
    movie_bin = tf.read_file('5205acf1-3d30b48d.mov')
    movie = tf.contrib.ffmpeg.decode_video(movie_bin)
    movie_ev = movie.eval()
    print("****", len(movie_ev))
```
### Describe the problem

The `tf.contrib.ffmpeg.decode_video` op throws an error and causes a core dump.

My ffmpeg version (`apt get install ffmpeg` on ubuntu 18.04):
```shell
ffmpeg version 3.4.2-2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu2)
  configuration: --prefix=/usr --extra-version=2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
```
### Source code / logs
```shell
2018-06-27 09:15:22.489692: F tensorflow/contrib/ffmpeg/default/ffmpeg_lib.cc:405] Non-OK-status: ReadInfoFile(stderr_filename, width, height, frames) status: Unknown: Not enough video info returned by FFmpeg [0, 720, 1280, 3]Could not read FFmpeg stderr file: /tmp/tmp_file_tensorflow_3_ILW8Ht.err
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by rongou**
An alternative fix to #20366 that might be slightly simpler. Basically only parse the `width x height` information from the `ffmpeg` output, and rely on the `rawvideo` size to calculate the number of frames. This might be a little more robust to `ffmpeg` output changes.

Also added the `-vsync 0` flag so that `ffmpeg` doesn't duplicate or drop frames.

Fixes #20348.

@yongtang

### CODE REVIEW

**Comment by rongou** [comment]
ping @yongtang @yifeif

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yifeif** [comment]
@fredbertsch let me know if you can take a look at this PR. Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 30 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 45 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 60 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 75 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 90 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 105 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 120 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 135 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fredbertsch, @yongtang: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by wookayin** [comment]
Is it going to be merged soon or superceded by tensorflow-io?

**Comment by yongtang** [comment]
@wookayin The `tf.contrib.ffmpeg` directory will be removed in the future tensorflow 2.0

It is preferable to use tensorflow-io for video input now forward looking. Also, tensorflow-io does not use command line to spawn a process. It calls ffmpeg api directly so it should be much more reliable and performs better: https://github.com/tensorflow/io

**Comment by wookayin** [comment]
@yongtang Thanks for your comment. I see, and I like the direction of migrating video ops to `tensorflow-io`, but it is pretty hard to make it work with TF 1.13.0 because of many API changes. So I was wondering if it is still worthwhile to include this changes in TF 1.x series until `tensorflow_io.video` gets easly usable.

**Comment by yongtang** [comment]
Thanks @wookayin for trying out `tensorflow-io`.


The tensorflow-io is actually compatible with tf 1.13 and our nightly build: 
```
pip install tensorflow-io-nightly
```
requires `tensorflow==1.13.0rc2`.

The reason the released version of tensorflow-io still matches 1.12, is that we could not release a version that is based on release candidate (rc2). We are just waiting for 1.13 release and then a version of tensorflow-io will be released immediately.

Also, `tensorflow-io` has a 2.0 preview version as well:

```
pip install tensorflow-io-2.0-preview
```
which is based on TF 2.0 (tf-nightly-2.0-preview). You could also give it a try if you are more interested in TF 2.0.

We have a google discussion group:
https://groups.google.com/a/tensorflow.org/forum/#!forum/io

You may consider joining this group to get more information if you are interested.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
