### PR TITLE
Branch 162842890

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by caisq** [comment]
Investigating GPU build failure: https://ci.tensorflow.org/job/tensorflow-pull-requests-gpu/5878/

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Review by vrv — APPROVED** [review]

**Pull request merged**
