### PR TITLE
Fix Issue  #2225 InvalidArgumentError: No OpKernel T=DT_INT32 for log, exp, etc.

### LINKED ISSUE #2225: InvalidArgumentError: No OpKernel T=DT_INT32 for log, exp, etc.
### Environment info
Operating System: Mac/Ubuntu
Installed version of CUDA and cuDNN: None
commit b8883a237b71e877759327fb4b9077847d4cb16c

### Steps to reproduce
Thanks to http://stackoverflow.com/questions/37027762:
```
import tensorflow as tf
import numpy as np
x = np.array([1], dtype=np.int32)
sess = tf.Session()
print(sess.run(tf.log(x)))
```

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

https://www.tensorflow.org/versions/r0.8/api_docs/python/math_ops.html#log says "x: A Tensor. Must be one of the following types: float32, float64, int32, complex64, int64", but int32 and in64 throws InvalidArgumentError:

InvalidArgumentError: No OpKernel was registered to support Op 'Log' with these attrs
	 [[Node: Log_4 = Log[T=DT_INT32](Log_4/x)]].

I haven't checked all, but `exp`, `cos` and `sin` have the same issue.

I added a simple test:

```
--- a/tensorflow/python/ops/math_ops_test.py
+++ b/tensorflow/python/ops/math_ops_test.py
@@ -28,6 +28,21 @@ from tensorflow.python.platform import googletest
 exp = np.exp
 log = np.log

+class LogTest(test_util.TensorFlowTestCase):
+
+  def testLog(self):
+    x = np.array([1], dtype=np.int32)
+    with self.test_session():
+      y_tf = math_ops.log(x).eval()
+      self.assertEqual(y_tf, 0)

```
which clearly reveals this issue:

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
..E..........
======================================================================
ERROR: testLog (__main__.LogTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/ops/math_ops_test.py", line 44, in testLog
    y_tf = math_ops.log(x).eval()
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/framework/ops.py", line 502, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/framework/ops.py", line 3352, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/client/session.py", line 343, in run
    run_metadata_ptr)
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/client/session.py", line 578, in _run
    feed_dict_string, options, run_metadata)
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/client/session.py", line 651, in _do_run
    target_list, options, run_metadata)
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/client/session.py", line 673, in _do_call
    e.code)
InvalidArgumentError: No OpKernel was registered to support Op 'Log' with these attrs
	 [[Node: Log = Log[T=DT_INT32, _device="/device:CPU:0"](Log/x)]]
Caused by op u'Log', defined at:
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/ops/math_ops_test.py", line 110, in <module>
    googletest.main()
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/platform/googletest.py", line 84, in main
    benchmark.benchmarks_main(true_main=g_main)
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/platform/benchmark.py", line 301, in benchmarks_main
    true_main()
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/platform/googletest.py", line 58, in g_main
    return unittest_main(*args, **kwargs)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 395, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/ops/math_ops_test.py", line 44, in testLog
    y_tf = math_ops.log(x).eval()
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/ops/gen_math_ops.py", line 843, in log
    return _op_def_lib.apply_op("Log", x=x, name=name)
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/ops/op_def_library.py", line 694, in apply_op
    op_def=op_def)
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/framework/ops.py", line 2153, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/bin/tensorflow/python/math_ops_test.runfiles/tensorflow/python/framework/ops.py", line 1153, in __init__
    self._traceback = _extract_stack()


----------------------------------------------------------------------
Ran 13 tests in 0.144s

FAILED (errors=1)
```

### PR DESCRIPTION
**Pull request by hunkim**
This PR fixes  #2225,  InvalidArgumentError: No OpKernel T=DT_INT32 for log, exp, etc.
## Issue

https://www.tensorflow.org/versions/r0.8/api_docs/python/math_ops.html says, "A Tensor. Must be one of the following types: float32, float64, int32, complex64, int64", but code does not:

`REGISTER4(UnaryOp, CPU, "Cos", functor::cos, float, Eigen::half, double, complex64);`

They don't support int32 and int64. So this simple code fails:

```
x = np.array([1], dtype=np.int32)
sess = tf.Session()
print(sess.run(tf.log(x)))
```
## Solution

Thanks to a hint from @yaroslavvb, the patch is rather simple:

```
-REGISTER4(UnaryOp, CPU, "Log", functor::log, float, Eigen::half, double,        
-          complex64);       
+REGISTER6(UnaryOp, CPU, "Log", functor::log, float, Eigen::half, double, int32,
+         int64, complex64);
```
## Tests

I also added several tests to verify the patch. They all pass in my cpu-only machine:

```
...
//tensorflow/python:math_grad_test                                       PASSED in 2.8s
//tensorflow/python:math_ops_test                                        PASSED in 1.5s
//tensorflow/python:matmul_op_test                                       PASSED in 3.1s
...
//tensorflow/python:xent_op_test                                         PASSED in 1.4s

Executed 186 out of 187 tests: 187 tests pass.
```

If I just run math_ops_test without this patch, it fails with InvalidArgumentError: 

```
//tensorflow/python:math_ops_test                                        FAILED in 1.4s
  /home/hunkim/.cache/bazel/_bazel_hunkim/6785122ce03f8c29e79889062219c7d3/tensorflow/bazel-out/local-fastbuild/testlogs/tensorflow/python/math_ops_test/test.log

Executed 186 out of 187 tests: 186 tests pass and 1 fails locally.
```

### CODE REVIEW

**Comment by yaroslavvb** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by yaroslavvb** [comment]
Thanks! Looks good generally, waiting for tests to pass....could you squash the commits?

**Comment by yaroslavvb** [comment]
OK, so apparently this was enabled before and it generated nvcc warnings, because the macro creates a kernel that can automatically downgrade floating point inputs to integers. Also it's a weird kernel to enable because trig functions use floating point math internally anyway, so you don't gain anything (as opposed to, say, defining integer valued matrix multiplication). To deal with user-side crash, the more principled way might be automatic promotion of input arguments (int->float). Sorry this was a bad suggestion on my part :/

**Comment by hunkim** [comment]
@yaroslavvb Thanks for the comments. I'll squash the commits.

I am not sure I understand this correctly:

> To deal with user-side crash, the more principled way might be automatic promotion of input arguments (int->float).

Can you elaborate more? Do you have another fix suggestion?  I am not sure promoting int->float is a good idea. Their max values and precisions are different. 

BTW, this fix was inspired by other ops like pow:
```
REGISTER6(BinaryOp, CPU, "Pow", functor::pow, float, Eigen::half, double, int32,
          int64, complex64);
```
Please let me know.

**Comment by hunkim** [comment]
I see @zheng-xq's comment suggesting updating doc. So it's better not to support int32 and int64?

**Comment by yaroslavvb** [comment]
I think promoting int32->float or double will have the same effect as in the current implementation. IE, int32 may have different precision than float, but it doesn't matter if internal implementation converts it to float anyway since output is floating point even if input is integer. The difference with `Pow` function is in that case integer inputs also produce integer outputs

**Comment by hunkim** [comment]
@yaroslavvb I see the point now. Thanks for the explanation. @zheng-xq suggested API doc update. I guess it would be a simple solution and let users promote their int values to float.

**Comment by hunkim** [comment]
Interestingly, I've got another question in my (Korean) community:

```
InvalidArgumentError: No OpKernel was registered to support Op 'Conv2D' with these attrs
[[Node: Conv2D_19 = Conv2D[T=DT_DOUBLE, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](Conv2D_19/input, Conv2D_19/filter)]]
Caused by op u'Conv2D_19', defined at: 
```
I guess it's not in the basic math ops, but somewhat related: "Conv2D[T=DT_DOUBLE..." I think we need to address this issue, since many espacially, beginners are confused by this error. The error message is also hard to understand. :-)

**Comment by yaroslavvb** [comment]
I think that's a slightly different issue -- someone has data of type `DT_DOUBLE`, but only op of `DT_FLOAT` is supported, so it fails. The idea is that it's better to fail and request explicit conversion, than silently lose precision.

Another example of original problem is that the following fails. Automatic type promotion would help with the problem but it needs someone familiar with the internals to implement and I don't think anyone is working/planning to work on it at the moment.

`tf.constant(1)+tf.constant(np.array(1))`

**Comment by hunkim** [comment]
@yaroslavvb I see. Then, just API doc update at this point?

"A Tensor. Must be one of the following types: float32, float64, ~~int32~~, complex64, ~~int64~~"

**Comment by yaroslavvb** [comment]
Yes

**Comment by hunkim** [comment]
@yaroslavvb Thanks. Working on it.

**Pull request closed without merging**
