### PR TITLE
Upgrade all TF base images to ubuntu 16.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by angersson** [comment]
There are some failures again, but I don't understand why they might be occurring (cpu-python could be a change in the Ubuntu 14-16 change) -- copying some below in case Jenkins doesn't cache them long enough:

```
(sanity)
FAIL: Found 1 non-whitelited pylint errors:
python3: can't open file '/usr/local/lib/python3.4/dist-packages/pylint/lint.py': [Errno 2] No such file or directory
```

```
(cpu-python3)
ERROR: /workspace/tensorflow/core/BUILD:1504:1: undeclared inclusion(s) in rule '//tensorflow/core:lib_hash_crc32c_accelerate_internal':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/lib/hash/crc32c_accelerate.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/nmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/mmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/mm_malloc.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/popcntintrin.h'.
INFO: Building complete.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /workspace/tensorflow/tools/pip_package/BUILD:141:1 undeclared inclusion(s) in rule '//tensorflow/core:lib_hash_crc32c_accelerate_internal':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/lib/hash/crc32c_accelerate.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/nmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/mmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/mm_malloc.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/popcntintrin.h'.
INFO: Elapsed time: 6.483s, Critical Path: 0.22s
Build failed.
```

**Comment by yifeif** [comment]
Looks like Ubuntu16.04 python3 defaults to be python3.5 and our pylint script is looking for /usr/local/lib/python3.4/dist-packages/pylint/lint.py.

**Comment by gunan** [comment]
@mhlopko I think we are running into a bazel bug. Please see the following failure:
```
ERROR: /workspace/tensorflow/tools/pip_package/BUILD:141:1 undeclared inclusion(s) in rule '//tensorflow/core:lib_hash_crc32c_accelerate_internal':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/lib/hash/crc32c_accelerate.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/nmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/mmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/mm_malloc.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/popcntintrin.h'.
```

I think we should be using built-in crosstool for our CPU builds. Maybe the default crosstools missing cxx include directories?

**Comment by gunan** [comment]
I have sent cls for failing tests internally. When those are submitted and pushed we can merge this (finally!)

**Comment by drpngx** [comment]
@gunan I did a push yesterday but didn't notice your CLs. Please ping on this thread when they're submitted.

**Comment by gunan** [comment]
CCd you in the cls. Will ping this thread as you requested once the cls are in so we can retrigger tests.

**Comment by drpngx** [comment]
Thank you!

**Comment by gunan** [comment]
The cls are submitted, and should be pushed wednesday or thursday.
Jenkins, test this please.

**Pull request merged**
