### PR TITLE
Refactor network tester code and Readme

### PR DESCRIPTION
**Pull request by ninja18**

### CODE REVIEW

**Comment by gbaned** [comment]
@ninja18  Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@ninja18 Still, conflicts appearing. Could you please resolve those? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@ninja18 gentle ping to resolve conflicts? Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
