### PR TITLE
Added initial arm64v8 support for dockerfiles

### PR DESCRIPTION
**Pull request by settle**
Pretty straight forward addition of aarch64 support for dockerfiles, with the exception of installing several python3 packages using apt instead of pip because there is some dependency issue that pip could not satisfy but apt could.  On a positive note, it is much faster to install the pre-built python3 packages than building them.  At the moment this is just the devel-cpu-aarch64.Dockerfile (and jupyter variant), but my intention is to add the cpu-aarch64.Dockerfile as soon as possible.

### CODE REVIEW

**Comment by settle** [comment]
@googlebot I signed it!

**Comment by settle** [comment]
Btw, in case someone is interested in what failed using the normal pip install method, here's the tail end of the log: 
[docker_build_failure.log](https://github.com/tensorflow/tensorflow/files/4654492/docker_build_failure.log)

Doing some digging, the apt install method installed the following package, which includes some blas and lapack libraries:
[apt_get_install.log](https://github.com/tensorflow/tensorflow/files/4654496/apt_get_install.log)

However, if I first installed using the apt flow and then tried to upgrade those python3 packages via pip (see below) the same error was thrown so maybe to compile the scipy really needs mkl, openblas, or atlas.  Note that enum34 needed to be installed last or it would introduce an error before the aforementioned error.  At this point I stopped trying to install these python3 packages via the pip flow and just went with the apt way.

```
RUN apt-get update && apt-get install -y \
    python3-pil \
    python3-h5py \
    python3-keras-preprocessing \
    python3-matplotlib \
    python3-mock \
    python3-numpy \
    python3-scipy \
    python3-sklearn \
    python3-pandas \
    python3-portpicker

RUN python3 -m pip --no-cache-dir install --upgrade \
    Pillow \
    h5py \
    keras_preprocessing \
    matplotlib \
    mock \
    numpy \
    scipy \
    sklearn \
    pandas \
    portpicker

RUN python3 -m pip --no-cache-dir install \
    enum34
```

**Comment by angerson** [comment]
Thanks for the PR!

- apt packages are going to be much older to the pip installations, aren't they? Can you fork bazelbuild.partial.Dockerfile into an aarch64-specific partial and use that in your image instead? 
- Once you make the change, please follow the instructions in the README to regenerate the dockerfiles.

**Comment by settle** [comment]
@angerson You're right, nearly all the apt python packages are much older those available from pip (comparison included below).  I created a specific bazelbuild arm variant partial Dockerfile as you suggested and then re-generated the full Dockerfiles.

|Package|Pip|Apt (Ubuntu 18.04)|Apt (Ubuntu 20.04)|
|-|-|-|-|
|Pillow|7.1.2|5.1.0-1ubuntu0.2|7.0.0-4build1|
|h5py|2.10.0|2.7.1-2|2.10.0-2build2|
|Keras_Preprocessing|1.1.2|N/A|1.0.5-1|
|matplotlib|3.2.1|2.1.1-2ubuntu3|3.1.2-1ubuntu4|
|mock|4.0.2|2.0.0-3|3.0.5-1build1|
|numpy|1.18.4|1:1.13.3-2ubuntu1|1:1.17.4-5ubuntu3|
|scipy|1.4.1|0.19.1-2ubuntu1|1.3.3-3build1|
|sklearn|0.0|0.19.1-3|0.22.2.post1+dfsg-5|
|pandas|1.0.3|0.22.0-4ubuntu1|0.25.3+dfsg-7|
|portpicker|1.3.1|1.2.0-1|1.3.1-3|

**Comment by settle** [comment]
@angerson After a little digging I found the missing dependencies for scipy if installing via pip.  It appears that this python package is available as a prebuilt wheel file for amd64, but only as source on arm64v8 which requires the three additional packages below.  However, I'm not sure if these are the preferred blas and lapack library implementations, or alternatively from atlas or openblas for example.  How would you like to proceed?

```
RUN apt-get update && apt-get install -y \
    gfortran \
    libblas-dev \
    liblapack-dev

RUN python3 -m pip --no-cache-dir install \
    Pillow \
    h5py \
    keras_preprocessing \
    matplotlib \
    mock \
    numpy \
    scipy \
    sklearn \
    pandas \
    portpicker \
    enum34
```

**Comment by gbaned** [comment]
@settle Can you please resolve conflicts? Thanks!

**Comment by settle** [comment]
@gbaned Conflicts should be resolved now, thanks!

**Review by angerson — APPROVED** [review]
Cool, thanks!

**Pull request merged**
