### PR TITLE
gradient of diag operator

### PR DESCRIPTION
**Pull request by chemelnucfin**
@girving Hopefully I learned your lessons.  I used auto in a loop, but initialized it to the unsigned version as I found out why it was comparing signed and unsigned.  Otherwise, hopefully this is good to go.

@vrv I noticed that you changed some additional files for the diag_part operator, I must have missed them.  Thanks.

@cameronphchen Just wanted to let you know about this commit.

### CODE REVIEW

**Comment by girving** [comment]
It'd be better to use a pure Python test for this, since then you can use tf.test.compute_gradient_error.

**Comment by girving** [comment]
Also, can you implement and test the gradient of diag_part in the same commit (which is diag)?  Should just be a few more lines, and it's always delightful to add gradients of transpose operators in pairs. :)

**Comment by chemelnucfin** [comment]
@girving Added the gradients for both tf.diag and tf.diag_part and the tests for them.  In the separate commit, also fixed a bug when gradient on int type is called.  I'll be looking for why the saver test is failing in python3.

**Comment by chemelnucfin** [comment]
Referecing Issue #1293 before I forget.

**Comment by girving** [comment]
Looks good once the C++ changes are removed!

**Comment by chemelnucfin** [comment]
@girving Wait, isn't the c++ code necessary?

**Comment by girving** [comment]
No, normally we just register gradients in Python.

**Comment by chemelnucfin** [comment]
@girving removed.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Pull request merged**
