### PR TITLE
[PluggableDevice] Add DEVICE_DEFAULT int32 registration for Pack

### PR DESCRIPTION
**Pull request by PatriceVignola**

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Review by penpornk — COMMENTED** [review]
Pack was registered in #51777 which was rolled back because it broke internal tests. I suspect it was just because StridedSlice op (and not Pack). Will do a thorough test internally before merging this one.

**Comment by penpornk** [comment]
This PR got reverted because it broke internal tests. Will add this to the list of `DEVICE_DEFAULT` ops to revisit / investigate later.

**Comment by PatriceVignola** [comment]
@penpornk Where can we track that list?

**Pull request merged**
