### PR TITLE
Fix transpose op legalization patterns

### PR DESCRIPTION
**Pull request by ahmedsabie**
The second transpose legalization pattern originally handled both types but the first one handled 64 bit, so with this change the second one will only handle 32 bit so they operate disjointly.

### CODE REVIEW

**Comment by ahmedsabie** [comment]
@smit-hinsu

**Review by smit-hinsu — COMMENTED** [review]
Could you add a test for this which would have failed before this change?

Also, add a TODO note to combine these two patterns as we had discussed.

**Comment by ahmedsabie** [comment]
> Could you add a test for this which would have failed before this change?
> 
> Also, add a TODO note to combine these two patterns as we had discussed.

Would the test be a transpose with a 64 bit non constant second argument?

**Comment by smit-hinsu** [comment]
> > Could you add a test for this which would have failed before this change?
> > Also, add a TODO note to combine these two patterns as we had discussed.
> 
> Would the test be a transpose with a 64 bit non constant second argument?

Yes, that's correct. That should give an illegal IR before this change.

**Review by smit-hinsu — APPROVED** [review]

**Review by smit-hinsu — APPROVED** [review]

**Pull request merged**
