### PR TITLE
Cherrypicks

### PR DESCRIPTION
**Pull request by av8ramit**
Tensorboard cherrypicks while reverting tensorboard to previous hash. Please review properly. Doc and release file updates.

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]
The added protos are intentional, yes?

**Comment by av8ramit** [comment]
Yes, cc @dandelionmane .

**Review by petrosmol — APPROVED** [review]
Approving fro RELEASE.md

**Comment by gunan** [comment]
Jenkins, test this please.

**Pull request merged**
