### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by vitor-alves**

### CODE REVIEW

**Comment by vitor-alves** [comment]
I signed it!

**Review by MarkDaoust — DISMISSED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yifeif** [comment]
Thanks @vitor-alves. Could you resolve the conflict?

**Comment by vitor-alves** [comment]
Hi
I will update!

**Comment by vitor-alves** [comment]
Updated.

**Pull request merged**
