### PR TITLE
Update unit tests for xla cpu changes

### PR DESCRIPTION
**Pull request by snadampal**
Update unit tests to fix the build break from the xla cpu changes.
fixes this issue#
https://github.com/tensorflow/tensorflow/issues/56673

### CODE REVIEW

**Review by Berkobey — APPROVED** [review]

**Comment by snadampal** [comment]
I have resolved the merge conflicts.

**Review by penpornk — APPROVED** [review]
Thank you for the fix!

**Comment by penpornk** [comment]
@snadampal We are having trouble importing this PR. Could you please help rebase it? Sorry for the inconvenience. :(

**Comment by snadampal** [comment]
sure, no problem.

**Comment by penpornk** [comment]
@snadampal We can pull it in now. Thank you! :)

**Comment by gbaned** [comment]
Hi @snadampal Can you please resolve conflicts? Thank you!

**Pull request closed without merging**
