### PR TITLE
Update rmsprop.py API docs for TF 2.x

### PR DESCRIPTION
**Pull request by 8bitmp3**
Hello and TGIF. This PR updates the RMSProp API docs for TF 2.x:

- Added a new description: sourced from Alex Graves's 2013 [paper](https://arxiv.org/abs/1308.0850) and Hinton's 2012 [lecture](http://www.cs.toronto.edu/~tijmen/csc321/slides/lecture_slides_lec6.pdf). The latter is said to be the first public mention of the optimizer. The description is pretty much word for word, hope that's ok. Feel free to modify it.
- Modified the reference using Alex Graves' reference style from the 2013 [paper](https://arxiv.org/pdf/1308.0850.pdf) that followed the first "unpublished" introduction of RMSProp (a.k.a. _rmsprop_) (`T. Tieleman and G. Hinton. Lecture 6.5 - rmsprop:...`).
- Other minor fixes (indentation, colon, etc).

Let me know if that looks good @lamberta and team. I'm combing through another platform's optimizer API docs, so will be sending you more PRs if I spot anything here—hope that's ok.

### CODE REVIEW

**Comment by gbaned** [comment]
@8bitmp3 Can you please resolve conflicts? Thanks!

**Review by tanzhenyu — APPROVED** [review]

**Review by rthadur — APPROVED** [review]

**Comment by rthadur** [comment]
@8bitmp3 can you please check build failures and resolve conflicts ?

**Comment by 8bitmp3** [comment]
@rthadur @tanzhenyu @gbaned The changes to the docs were made on Feb 14th and they didn't touch the Python code. So, the the internal build failures may be caused by the fact when you started reviewing the PR in April, the original file already went through some distinct changes, as @fchollet already introduced new improvements to the docstring  - see https://github.com/tensorflow/tensorflow/commit/f6302e4ec726225036b3419af7d218e93aa06783 (especially, the new detailed args section). If Francois doesn't mind, I can submit new a PR with a small addition of references at the end and close this PR.

**Comment by rthadur** [comment]
@8bitmp3 we can close this PR, if there are new doc changes please open a new PR.

**Pull request closed without merging**
