### PR TITLE
Branch 141241224

### PR DESCRIPTION
**Pull request by andrewharp**
Pushing internal commits.

### CODE REVIEW

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this, please.

**Comment by gunan** [comment]
@mrry could you look at the below cmake issue?

```
Error evaluating generator expression:

    $<TARGET_OBJECTS:tf_contrib_metrics_set_ops>

  Objects of target "tf_contrib_metrics_set_ops" referenced but no such
  target exists.
Call Stack (most recent call first):
  tf_python.cmake:497 (GENERATE_PYTHON_OP_LIB)
  CMakeLists.txt:214 (include)
```

**Comment by andrewharp** [comment]
For posterity, the following changes were squashed into 6de612e7767c4114d65cb06fc6606436e3081dc3 due to a temporary export problem:

141201358	Force fix documentation causing open source blocks.
141198275	Avoid making horrible docstrings when KeywordRequired() is used
141196439	TensorFlow: Update generated OSS Python Op docs.
141195963	Moved cuda_libdevice_path.cc to make the functionality available accross all platforms
141194861	Change head_test size from small to medium.
141189800	TensorFlow: Update generated OSS Python Op docs.
141188581	Part 2c of renaming SparseTensor.shape -> SparseTensor.dense_shape
141188238	[XLA:CPU] Mac portability fixes.
141187979	Part 2d of renaming SparseTensor.shape -> SparseTensor.dense_shape
141187865	add name arguments to tf.split and standardize names between tf.split and
141187490	Part 2d of renaming SparseTensor.shape -> SparseTensor.dense_shape
141186655	Fixed name collision in saver test.
141186135	Part 2b of renaming SparseTensor.shape -> SparseTensor.dense_shape
141185169	TensorFlow: Update generated OSS Python Op docs.
141180811	TensorFlow: Update generated OSS Python Op docs.
141176394	TensorFlow: Update generated OSS Python Op docs.
141174390	Remove resources from the public API for now.
141172667	TensorFlow: Update generated OSS Python Op docs.
141170685	Part 2c of renaming SparseTensor.shape -> SparseTensor.dense_shape
141169934	TensorFlow: Update generated OSS Python Op docs.
141167099	TensorFlow: Update generated OSS Python Op docs.
141163858	TensorFlow: Update generated OSS Python Op docs.
141161010	TensorFlow: Update generated OSS Python Op docs.
141158743	TensorFlow: Update generated OSS Python Op docs.
141155653	TensorFlow: Update generated OSS Python Op docs.
141152716	TensorFlow: Update generated OSS Python Op docs.
141152197	Clarify wording in RNN tutorial.
141149578	TensorFlow: Update generated OSS Python Op docs.
141147227	TensorFlow: Update generated OSS Python Op docs.
141145195	TensorFlow: Update generated OSS Python Op docs.
141142798	TensorFlow: Update generated OSS Python Op docs.
141140181	TensorFlow: Update generated OSS Python Op docs.
141139340	Part 2c of renaming SparseTensor.shape -> SparseTensor.dense_shape
141137926	TensorFlow: Update generated OSS Python Op docs.
141135381	TensorFlow: Update generated OSS Python Op docs.
141132823	TensorFlow: Update generated OSS Python Op docs.
141129991	TensorFlow: Update generated OSS Python Op docs.
141127103	TensorFlow: Update generated OSS Python Op docs.

**Comment by andrewharp** [comment]
Merging to unblock pulls, test failures will need to be dealt with in followups.

**Pull request merged**
