### PR TITLE
Remove RewriterConfig from the Python API

### PR DESCRIPTION
**Pull request by allenlavoie**
RewriterConfig has not made it into a release, and so is not subject to semantic versioning. The API needs a bit of work, so it's not going into 1.2.

In order to minimize disruption to non-Google users (some using tf.RewriterConfig from master) and hold up the 1.2 release as little as possible, the plan is to *only* remove RewriterConfig from the 1.2 release, but leave it in master. We will then develop a more permanent way to configure Grappler graph rewriting.

### CODE REVIEW

**Review by benoitsteiner — APPROVED** [review]

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Review by martinwicke — APPROVED** [review]
Looks good to me.

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins, test this please.

**Review by av8ramit — CHANGES_REQUESTED** [review]
Accidentally tested on master, retrying now with r1.2

**Comment by gunan** [comment]
Jenkins, test this please

**Review by av8ramit — APPROVED** [review]

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Pull request merged**
