### PR TITLE
Branch 155393864

### PR DESCRIPTION
**Pull request by andrewharp**
Pushing internal commits.

### CODE REVIEW

**Comment by yifeif** [comment]
The run with --expunge is messing with other runs,
'external/local_config_cuda/cuda/lib/libcudnn.so.6' is a dangling symbolic link.
@gunan, should we merge https://github.com/tensorflow/tensorflow/pull/10307? Or should we only add --expunge first?

**Comment by gunan** [comment]
Ugh, this is bad.
Will chat offline about the issue.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this, please.

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this, please.

**Pull request closed without merging**
