### PR TITLE
hash table more types

### PR DESCRIPTION
**Pull request by formath**

### CODE REVIEW

**Review by qlzh727 — COMMENTED** [review]
One quick note before  ysuematsu@ review this change is that can you sort the kernel registers based on the key and value in a consistent order? eg order by key alphabetically first and then value alphabetically.

**Comment by formath** [comment]
@qlzh727 Fixed. In order now.

**Comment by qlzh727** [comment]
Ping @ysuematsu for review.

**Comment by qlzh727** [comment]
Nudge @ebrevdo for review/approval.

**Comment by ebrevdo** [comment]
Registrations like this balloon the size of the tensorflow binary quite a bit, because they create many new template instantiations.  Can you restrict this PR to just the registrations that you need?

**Comment by formath** [comment]
@ebrevdo Yes. Have been done.

**Comment by qlzh727** [comment]
Please resolve the merge conflict. Thanks.

**Comment by formath** [comment]
@qlzh727 ok

**Comment by qlzh727** [comment]
Ping @ebrevdo for final approval.

**Comment by ebrevdo** [comment]
Looks like you removed some existing registrations, like all the string
value ones

**Comment by formath** [comment]
@ebrevdo Re-add

**Comment by formath** [comment]
@qlzh727 @ebrevdo Please give a review.

**Review by ebrevdo — CHANGES_REQUESTED** [review]
You removed an int64, string registration.

**Comment by formath** [comment]
@ebrevdo add int64_2_string back.

**Review by ebrevdo — APPROVED** [review]

**Pull request merged**
