### PR TITLE
Update config.py to fix ##55218

### PR DESCRIPTION
**Pull request by Gelesh**
Update config.py to fix ##55218

### CODE REVIEW

**Comment by gbaned** [comment]
@Gelesh  Can you please sign CLA. Thanks!

**Comment by mihaimaruseac** [comment]
Please use a better PR title. See https://cbea.ms/git-commit/

**Comment by gbaned** [comment]
@Gelesh Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Comment by Gelesh** [comment]
another pull request submitted

**Pull request closed without merging**
