### PR TITLE
lite: Update CMakeLists.txt

### LINKED ISSUE #59631: `tflite-runtime-nightly` on ARM64 has minimum GLIBC requirement 2.33, which prevents installation in official `python` container images
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `python:3.10-slim-bullseye` container image on **ARM64**
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: N/A
-   **TensorFlow installed from (source or binary)**: Binary
-   **TensorFlow version (use command below)**:  `tflite-runtime-nightly` `2.13.0.dev20230207`
-   **Python version**: 3.10.10
-   **Bazel version (if compiling from source)**: N/A
-   **GCC/Compiler version (if compiling from source)**: N/A
-   **CUDA/cuDNN version**: N/A
-   **GPU model and memory**: N/A
-   **Exact command to reproduce**:

### Describe the problem

1. Create a new `python:3.10-slim-bullseye` container
2. Install [`tflite-runtime-nightly` `2.13.0.dev20230207`](https://pypi.org/project/tflite-runtime-nightly/2.13.0.dev20230207/)
3. Build and run the container on **ARM64** (such as from an ARM Macbook using Docker Desktop)
4. Run

```
>>> import tflite_runtime.interpreter as tflite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 33, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/venv/lib/python3.10/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.so)
```

There are not yet any Debian bookworm-based [`python` official images](https://hub.docker.com/_/python) yet, so it's not possible to bump up to a newer Debian version with a newer GLIBC.

### Other background

This worked fine in a `python:3.10-slim-bullseye` **x86** container, so perhaps the GLIBC version requirements are different due to how the ARM64 wheels were built?

Here are the GLIBC versions of various Linux platforms:

```
Debian Buster:   2.28
       Bullseye: 2.31
       Bookworm: 2.36

Ubuntu 20.04:    2.31
       22.04:    2.35

RHEL   8:        2.28
       9:        2.34
```

Related to:

- #59423

CC @samypr100 @terryheo

### PR DESCRIPTION
**Pull request by terryheo**
To fix undefined symbol: _ZN6tflite9telemetry20TelemetryReportEventEP13TfLiteContextPKc12TfLiteStatus This PR resolves #59631

PiperOrigin-RevId: 510050310

### CODE REVIEW

**Comment by sheepmaster** [comment]
Is https://github.com/tensorflow/tensorflow/issues/59631 the right issue?

**Review by fergushenderson — APPROVED** [review]

**Review by miaout17 — APPROVED** [review]
Looks good -- Fixing CMake build for r2.12 branch. I think the author validated in main branch already.

**Comment by zehuiw** [comment]
Thanks for fixing it @terryheo ! Is it possible to merge this commit to the master branch?

**Comment by terryheo** [comment]
> Thanks for fixing it @terryheo ! Is it possible to merge this commit to the master branch?

It's a cherry-pick from the master change https://github.com/tensorflow/tensorflow/commit/5115fa96d7c5b41451674892317be43e30b7c389

**Review by learning-to-play — APPROVED** [review]

**Pull request merged**
