### PR TITLE
Please, approve iOS DeepLab Tensorflow Lite GPU example.

### PR DESCRIPTION
**Pull request by VolodymyrPavliukevych**
Add TensorFlow Lite GPU example for iOS with DeepLab 257x257 model.

### CODE REVIEW

**Comment by VolodymyrPavliukevych** [comment]
Dear @Takuro-Ito, sorry for that mistake, main .gitignore file removed that file from commit. 
Please, review that pull request.    
Don't forget:
1) Use latest Xcode 10.1;
2) Set your dev team in project settings; 
3) Download model to Resource folder (see README).

**Comment by Takuro-Ito** [comment]
@VolodymyrPavliukevych Thank you for dealing with it. Unfortunately I'm not authorized to review and merge pull request. 
But your example was very helpful to get started with DeepLab model on iOS platform. I appreciate it.

**Comment by VolodymyrPavliukevych** [comment]
@Takuro-Ito, you are welcome!

**Comment by VolodymyrPavliukevych** [comment]
Dear @aselle, please review DeepLab model example  for Tensorflow Lite GPU.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 30 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 45 days with no activity and the `awaiting review` label has been applied.

**Comment by multiverse-tf** [comment]
Sorry for the late response. I've escalated it to @jdduke for review.

**Comment by jdduke** [comment]
This is really great!

We're still trying to determine our general policy for hosting examples. Note that we're also in the process of migrating all the TensorFlow Lite examples to the [new examples repo](https://github.com/tensorflow/examples/tree/master/lite).

One thing we're considering is a gallery page where we link to community examples/demos. If you want to put the example in your own repo for now, we can link to that, and get back to you after we've determined our general example hosting policy. Again, very nice work! Do you by chance have a screenshot?

**Comment by jdduke** [comment]
Tentatively closing this, but we'll reopen when we have a path forward. In the meantime, we're working on a mechanism for linking to community examples if you want to go ahead and host this on your own repo.

**Comment by essalahsouad** [comment]
@VolodymyrPavliukevych 
the project tensorflow/tensorflow/lite/examples/ios/DeepLabApp/DeepLabApp.xcodeproj   doesn't exist.

**Pull request closed without merging**
