### PR TITLE
[OpenCL] Cleans StridedSlice Op

### PR DESCRIPTION
**Pull request by lukeiwanski**
Small PR's that clean OpenCL related code.

### CODE REVIEW

**Review by benoitsteiner — APPROVED** [review]

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by lukeiwanski** [comment]
Linux XLA fail seems to be unrelated

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by gunan** [comment]
Test failure is a known issue, PR safe to merge.

**Pull request merged**
