### PR TITLE
upgrade curl 8.1.2 -> 8.2.1 which has CVE fixes

### PR DESCRIPTION
**Pull request by justkw**
upgrade curl from 8.1.2 to 8.2.1 which has a few vulnerability fixes

### CODE REVIEW

**Review by learning-to-play — APPROVED** [review]

**Comment by nitins17** [comment]
Thanks for the PR, @justkw! The Windows presubmits are failing with:
```
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt-exec-A82A024B/bin/external/curl/_objs/curl/schannel_verify.obj.params
# Configuration: 952e1b9eadc76b69a54e3392b667aac8bc8f29e7deb6150a9a8d85df99154be6
# Execution platform: //tensorflow/tools/toolchains/win:rbe_windows_ltsc2019
external/curl/lib/vtls/schannel_verify.c(40): fatal error C1083: Cannot open include file: 'schannel_int.h': No such file or directory
```

Can you take a look?

**Comment by justkw** [comment]
@mraunak Can you please help to take a look?

**Comment by justkw** [comment]
Updated the PR, added the missing file.

**Review by MichaelHudgins — APPROVED** [review]
Re approve

**Pull request merged**
