### PR TITLE
update linear to mel documentation

### PR DESCRIPTION
**Pull request by keunwoochoi**

### CODE REVIEW

**Comment by keunwoochoi** [comment]
cc'ing @rryan again :) I added one more sentence about its normalization behavior.

**Comment by keunwoochoi** [comment]
(pinging @tomhennigan :)

**Review by tomhennigan — DISMISSED** [review]

**Comment by gbaned** [comment]
@keunwoochoi Could you please address Ubuntu Sanity errors? Thanks!

**Comment by keunwoochoi** [comment]
@rryan do you know if the equation symbols `$$` or something would've caused the error above? that error doesn't show any details so i'm making a guess now. d

**Comment by rryan** [comment]
> @rryan do you know if the equation symbols `$$` or something would've caused the error above? that error doesn't show any details so i'm making a guess now. d

tbh I have no idea :) 

Looking at something that works:
https://www.tensorflow.org/api_docs/python/tf/linalg/lstsq
https://github.com/tensorflow/tensorflow/blob/35a015349bab8f2e3276d843427a4501e56d18b6/tensorflow/python/ops/linalg_ops.py#L193-L204

It looks like you need to use `\\(` and `\\)` to wrap expressions.

**Comment by rryan** [comment]
Er, actually scratch that. `$$` works fine for standalone lines. 

I actually looked at the log this time :). The linter is unhappy:
```
FAIL: Found 1 non-whitelisted pylint errors:
tensorflow/python/ops/signal/mel_ops.py:113: [C0301(line-too-long), ] Line too long (83/80)
```

**Comment by keunwoochoi** [comment]
@rryan Thanks! Fixed now.

**Review by rryan — APPROVED** [review]
thanks!

**Pull request merged**
