### PR TITLE
Applying MKL Eager Rewriter to CPU Ops

### PR DESCRIPTION
**Pull request by philipphack**
Registers the MKL eager rewriter for the POST_PLACEMENT phase, allowing its selective application to ops assigned to a CPU.

### CODE REVIEW

**Review by kkimdev — APPROVED** [review]

**Comment by mahmoud-abuzaina** [comment]
@philipphack This is causing the test mkl_eager_op_rewrite_test to fail. Can you take a look? Command to reproduce:
bazel --config=mkl -c opt //tensorflow/core/common_runtime/eager:mkl_eager_op_rewrite_test
The change seems to be fine but you may need to add POST_PLACEMENT [here](https://github.com/tensorflow/tensorflow/blob/3e182f12fe6be0e30b18d48b68b5aa478b169f37/tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite_test.cc#L64) and [here](https://github.com/tensorflow/tensorflow/blob/3e182f12fe6be0e30b18d48b68b5aa478b169f37/tensorflow/core/common_runtime/eager/execute.cc#L1495).

**Comment by philipphack** [comment]
@mahmoud-abuzaina: Thanks for the note. After modifying the test to run the rewriters for the POST_PLACEMENT phase, the float part passes, but I still see failures for the bfloat16 portion. Possibly something you might want to investigate.

**Review by kkimdev — APPROVED** [review]

**Comment by mahmoud-abuzaina** [comment]
@philipphack Thanks for making the change. Bfloat16 is probably coming because CPU was used does not support that data type. That is expected. The PR looks ok to me now.

**Review by gbaned — APPROVED** [review]

**Comment by agramesh1** [comment]
CC @penpornk

**Pull request merged**
