### PR TITLE
Additional arguments (vmin, vmax, and clip) for summary.image

### PR DESCRIPTION
**Pull request by feihugis**
This PR adds the additional arguments (`vmin`, `vmax`, and `clip`) to `summary.image` for the request by [the issue-12883](https://github.com/tensorflow/tensorflow/issues/12883).

### CODE REVIEW

**Comment by feihugis** [comment]
@alextp Could you please help review this PR when you have time?

**Comment by alextp** [comment]
@nfelt can you review this?

**Comment by feihugis** [comment]
@nfelt Could you help review this PR when you have time?

**Comment by feihugis** [comment]
@nfelt Thanks for your reply! Good to know these plans. It makes sense to reduce the normalization provided by the op.

**Comment by nfelt** [comment]
@feihugis thanks for understanding!  I will close this and comment with an explanation on the original issue.

**Pull request closed without merging**
