### PR TITLE
Mirror link is broken and issue is difficult to debug.

### PR DESCRIPTION
**Pull request by KapoorHitesh**

### CODE REVIEW

**Comment by KapoorHitesh** [comment]
I signed it.

**Comment by npanpaliya** [comment]
I also want to know if the google's site for mnist dataset will be back again or we should use the one from this PR.

**Comment by martinwicke** [comment]
Since all this is deprecated, I don't mind changing the link. 

@wolffg I recall some more link gymnastics here, but I don't remember the outcome. Do we have our own copy?

**Comment by martinwicke** [comment]
This was a problem with the mirror, which has now been fixed. Sorry about the disruption. We prefer to keep the mirror as to avoid DDOSing Yann Lecun's page.

**Pull request closed without merging**
