### PR TITLE
Add text reader fuzzer

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
@fcoUnda

**Review by fcoUnda — APPROVED** [review]
Looks good

**Comment by akuegel** [comment]
Sorry, it seems there is a problem with landing this inside the XLA directory. We are not allowed to accept dependencies into tensorflow. If it is something that should be shared between XLA and Tensorflow, it needs to go into the TSL repository.

**Comment by DavidKorczynski** [comment]
> Sorry, it seems there is a problem with landing this inside the XLA directory. We are not allowed to accept dependencies into tensorflow. If it is something that should be shared between XLA and Tensorflow, it needs to go into the TSL repository.

No problem! I relocated it to the security folder

**Review by akuegel — APPROVED** [review]

**Pull request merged**
