### PR TITLE
TfLite Compare kernel code refactor to remove duplication

### PR DESCRIPTION
**Pull request by Dayananda-V**
One of ToDo activity

### CODE REVIEW

**Comment by gbaned** [comment]
@alanchiao Could you PTAL and approve.

**Comment by gbaned** [comment]
@alanchiao can you please review this PR ?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alanchiao: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alanchiao: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 30 days with no activity and the `awaiting review` label has been applied.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by terryheo** [comment]
Thanks for the contribution, Dayananda-V.
Your change is based on old code. Could you rebase your change for master?

**Comment by tensorflowbutler** [comment]
It has been 16 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
