### PR TITLE
Branch 126195202

### PR DESCRIPTION
**Pull request by rmlarsen**
Push of internal Google changes to TensorFlow.

### CODE REVIEW

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@vrv @martinwicke the two test failures are known and tracked by TF bulid cops. This should be OK to merge.

**Comment by vrv** [comment]
still waiting for GPU builds.

**Comment by rmlarsen** [comment]
right

**Comment by rmlarsen** [comment]
Adandoning this PR.

**Pull request closed without merging**
