### PR TITLE
Allow `~/` in path for transform_graph

### LINKED ISSUE #13211: transform_graph does not allow ~/ in path
when using ~/ in path, transform_graph returns file not found

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #13211 where it was not possible to specify `~` (e.g., `~/`, `~user/`, etc) for the path used in transform_graph. This fix adds the support of `~` transform_graph on Linux.

This fix fixes #13211.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by rmlarsen** [comment]
@andrehentz could you please take a look at this?

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by andrehentz — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment]
The PR has been rebased to resolve merge conflicts.

**Pull request merged**
