### PR TITLE
[ROCm] Adding / removing no_rocm tag from some unit tests

### PR DESCRIPTION
**Pull request by deven-amd**
This PR has two commits
* one to remove the `no_rocm` tag from unit-tests that are now passing on the ROCm platform
* another to add the `no_rocm` tag to unit-tests that are now failing on the ROCm platform

---------------------------------------

/cc @cheshire @chsigg @nvining-work

### CODE REVIEW

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by chsigg** [comment]
Looks good, thanks. I'm merging this change manually.

**Pull request merged**
