### PR TITLE
(Reopened PR) Add handle_ties arg to in_top_k Op to deal with ties.(#10767)

### PR DESCRIPTION
**Pull request by nolanliou**
Reopened PR for [10767](https://github.com/tensorflow/tensorflow/issues/10767)
Add handle_ties argument to in_top_k Op to make the Op more clear.

### CODE REVIEW

**Comment by nolanliou** [comment]
@martinwicke please review it if you have time. thanks.

**Comment by martinwicke** [comment]
Few questions: Is the shape function using the new information? Was the shape function wrong before?

The new default changes behavior (although it has strictly stronger guarantees, so I think it's fine). But we should call this out very explcitly in relnotes. Can you add relnotes for this change?

Should we make a similar change for topk so the two are aligned again?

**Comment by nolanliou** [comment]
@martinwicke 
1. The shape function is right before and this change don't affect the input and output shape.
2. where is the relnotes?  sorry, I cannot find it.
3.  `If two elements are equal, the lower-index element appears first.`, The topk strategy is different from InTopK, Is align necessary?

**Comment by cwhipkey** [comment]
I had a couple questions about the SAMPLE method and the intended use:

1. would it be useful to have a mode that matches top_k exactly, so that any class returning true here would be included in the equivalent top_k call?

2. what is SAMPLE used for?  My understanding of the code is that it doesn't guarantee exactly k classes return true.  Is that right?

**Comment by nolanliou** [comment]
@cwhipkey 
1. So it is necessary to align with topk. 
2. SAMPLE means we choose some elements from the ties for guarantee exactly k classes. the result k classes may contain the object or not.

Actually, there is not a perfect way to deal with the tie situation. you could have a look at the [issue](https://github.com/tensorflow/tensorflow/issues/10767).

**Comment by martinwicke** [comment]
I think aligning with top_k would be good. How hard would that be?

**Pull request closed without merging**
