### PR TITLE
change efficientdet-lite0 --> efficientdet_lite0

### PR DESCRIPTION
**Pull request by MaoXianXin**

### CODE REVIEW

**Review by terryheo — APPROVED** [review]
LGTM

**Comment by MaoXianXin** [comment]
Hi, When will this branch be merged. @gbaned

**Comment by gbaned** [comment]
> Hi, When will this branch be merged. @gbaned

Hi @MaoXianXin Sorry for the late replay. It is showing internal checks failures, we are working on it. Thank you.

**Pull request merged**
