### PR TITLE
FastGFile deprecated warning fixed

### PR DESCRIPTION
**Pull request by tomguluson92**
fix `FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.` problem.

### CODE REVIEW

**Comment by tomguluson92** [comment]
@ymodak please have it reviewed, thx.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by ymodak** [comment]
Ping @petewarden can you please take a look? Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Review by petewarden — APPROVED** [review]
Sorry for the delay in reviewing. Looks good, thanks!

**Comment by rthadur** [comment]
code is already merged in master , thank you

**Pull request closed without merging**
