### PR TITLE
Added missing condition in the Test case

### PR DESCRIPTION
**Pull request by amitsrivastava78**
Added the missing condition in the existing testcase

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@aselle can you pls review the PR and let me know your comments

**Review by aselle — DISMISSED** [review]
Thanks! for the change.

**Comment by amitsrivastava78** [comment]
@pragyaak & @aselle , this PR is approved but cannot see the label ready to pull, can you please replace the label.

**Comment by amitsrivastava78** [comment]
@rthadur, i have checked the failures, it has nothing to do with this changes, can you pls check and merge this PR.

**Comment by amitsrivastava78** [comment]
@rthadur , i have checked the failure is because of some other reason and not because of the PR, kindly check and merge.

**Comment by amitsrivastava78** [comment]
@rthadur , this PR is approved quiet some time , but not still merge, i have checked the error and these are not related to this PR, can you please help.

**Comment by amitsrivastava78** [comment]
@rthadur , all checks have passed for this PR, kindly help to merge this one.

**Comment by amitsrivastava78** [comment]
@rthadur , can you pls help to get this merged, as this is approved for long with all checks passed and i am afraid that if it stays longer again some merge conflicts might come.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@aselle and @rthadur , can you pls help to merge this PR.

Regards
Amit

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by mihaimaruseac** [comment]
Can you please describe why the test got changed? Is there a bug to link against?

**Comment by gbaned** [comment]
@amitsrivastava78 Can you please check reviewer comments and keep us posted. Thanks!

**Comment by mihaimaruseac** [comment]
Closing as it stalled. Please reopen if there is still a need for the PR

**Pull request closed without merging**
