### PR TITLE
Fixes tensorflow/skflow#148 - off by one error

### PR DESCRIPTION
**Pull request by ilblackdragon**
Fixes tensorflow/skflow#148 - error in neural translation example for sampling validation examples.

### CODE REVIEW

**Comment by mrry** [comment]
Jenkins, test this please.

**Comment by ilblackdragon** [comment]
@mrry, targets that fails are all not in skflow code:
//tensorflow/contrib/linear_optimizer:sdca_ops_test                      FAILED in 2.7s
  /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-py3-opt/testlogs/tensorflow/contrib/linear_optimizer/sdca_ops_test/test.log
//tensorflow/python:server_lib_test                                      FAILED in 1.5s
  /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-py3-opt/testlogs/tensorflow/python/server_lib_test/test.log
//tensorflow/python:session_test                                         FAILED in 2.6s
  /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-py3-opt/testlogs/tensorflow/python/session_test/test.log
//tensorflow/python:supervisor_test                                      FAILED in 12.4s
  /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-py3-opt/testlogs/tensorflow/python/supervisor_test/test.log
//tensorflow/tensorboard/backend:server_test                             FAILED in 7.8s
  /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-py3-opt/testlogs/tensorflow/tensorboard/backend/server_test/test.log

**Comment by mrry** [comment]
Ah, looks like the various fixes haven't made it out yet. Can you rebase against HEAD and we'll merge it then?

**Comment by ilblackdragon** [comment]
Done.

**Comment by ilblackdragon** [comment]
Jenkins, test this please.

**Pull request merged**
