### PR TITLE
fix incorrect usage of num_gpus & num_workers (#7312)

### PR DESCRIPTION
**Pull request by skaarthik**
Removed unnecessarily restrictive check as discussed in in #7312 and validated the change using 2 single GPU VMs.

### CODE REVIEW

**Comment by skaarthik** [comment]
I have signed CLA

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Somehow the CLA signing did not trigger. Could you check again?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
@skaarthik you have to exactly type `I signed it!` to retrigger cla bot.

**Review by caisq — APPROVED** [review]

**Comment by skaarthik** [comment]
I signed it!

**Comment by skaarthik** [comment]
Thanks @gunan for letting me know. I have added a new comment that says `I signed it!`.
Thansk @caisq for approving the PR

**Pull request merged**
