### PR TITLE
[TF-TRT] Fix repeated layer name bug

### PR DESCRIPTION
**Pull request by aboubezari**
## Issue
When there are multiple invocations of `SqueezeTensor` in a layer, the converter will complain: 
```
Repeated layer name: TRTEngineOp_000_000/PartitionedCall/model/tf.detection_output/DetectionOutput-shuffle:SHUFFLE (layers must have distinct names))
```
This happens despite passing `op_instance` to `SqueezeTensor`. The root cause is `op_instance` not being propagated to `PrepareTensorForShape`. 

## Fix
Propagate the `op_instance` argument to the internal `PrepareTensorForShape` call. Tested that a >1000 node graph completed with no issues. Add unit test coverage to prevent this issue from happening again.

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
@aboubezari thanks for the PR! Good catch.

Would you mind adding one tiny unittest that shows without your fix it fails and with your fix it works?
That way I can merge it and make sure it doesn't happen again

**Comment by aboubezari** [comment]
@DEKHTIARJonathan I tried reproducing the issue on `convert_nodes_test.cc`, but I'm realizing that this is not a conversion-time error, but this is something that happens when we attempt to execute the engine at inference time, so the UT is not useful at the moment. 

Since this is a low-risk change, what do you think about merging it as is?

**Comment by aboubezari** [comment]
Actually, I do this conversion warning: 
```
TF-TRT Warning: Engine creation for TRTEngineOp_000_000 failed. The native segment will be used instead. Reason: INTERNAL: Failed to build TensorRT engine
```
Let me keep trying to resurface this :)

**Comment by aboubezari** [comment]
Ok, I realized what I was missing: I was not calling `BuildAndRun` in the unittest to actually build & test the network. 

I've added the unittest and confirmed that it fails without my change and passes with it. 

@nluehr @pjannaty @poulsbo @DEKHTIARJonathan can we take one more look? It should be ready 👍

**Comment by aboubezari** [comment]
Unittest results (command: `bazel build -c opt --copt="-Wno-error=switch" tensorflow/compiler/tf2tensorrt:convert_nodes_test && bazel-bin/tensorflow/compiler/tf2tensorrt/convert_nodes_test_gpu --gtest_filter="OpConverterTest.DuplicateSqueeze"`)

**With my change:**
```
Note: Google Test filter = OpConverterTest.DuplicateSqueeze
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from OpConverterTest
[ RUN      ] OpConverterTest.DuplicateSqueeze
2023-04-10 16:09:25.417162: I tensorflow/compiler/tf2tensorrt/common/utils.cc:104] Linked TensorRT version: 8.6.0
2023-04-10 16:09:25.417259: I tensorflow/compiler/tf2tensorrt/common/utils.cc:106] Loaded TensorRT version: 8.6.0
2023-04-10 16:09:25.463796: W tensorflow/compiler/tf2tensorrt/convert/op_converter_registry.cc:55] Overwriting TF->TRT Abs op converter with priority 1 using another converter with priority 2
2023-04-10 16:09:25.468067: I tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:1330] [TF-TRT] Sparse compute capability: enabled.
[       OK ] OpConverterTest.DuplicateSqueeze (323 ms)
[----------] 1 test from OpConverterTest (323 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (323 ms total)
[  PASSED  ] 1 test.
```
Without my change: 
```
``

**Comment by aboubezari** [comment]
@DEKHTIARJonathan quick ping, let me know if there's anything else, I think we're close here :)

**Comment by aboubezari** [comment]
@nluehr @pjannaty @poulsbo @DEKHTIARJonathan another friendly ping :)
Could we take a look please? We should be all good now with unittest coverage.

**Comment by aboubezari** [comment]
@nluehr @pjannaty @poulsbo @DEKHTIARJonathan one last ping for a while. I'm going on vacation for 2-3 weeks after today so would be great to take a look in that time, thanks!

**Comment by DEKHTIARJonathan** [comment]
LGTM approved

**Review by DEKHTIARJonathan — APPROVED** [review]

**Pull request merged**
