### PR TITLE
Fix typo in `trt_engine_op_shape_test.py`

### PR DESCRIPTION
**Pull request by Kh4L**
This PR fixes a small typo introduced in #53327 that prevented the test from being run.

@DEKHTIARJonathan

### CODE REVIEW

**Review by bixia1 — APPROVED** [review]

**Comment by bixia1** [comment]
Are you sure the change is correct?
I got this error:

Traceback (most recent call last):
  File "/build/work/f597b7130c23d9a7ed113a86d697d5f754ae/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", line 1645, in decorated
    return f(self, *args, **kwargs)
  File "/build/work/f597b7130c23d9a7ed113a86d697d5f754ae/google3/runfiles/google3/third_party/tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py", line 1101, in _Test
    self.RunTest(run_params)
  File "/build/work/f597b7130c23d9a7ed113a86d697d5f754ae/google3/runfiles/google3/third_party/tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py", line 1018, in RunTest
    infer_saved_model_dir = self._GetInferGraph(run_params, saved_model_dir)
  File "/build/work/f597b7130c23d9a7ed113a86d697d5f754ae/google3/runfiles/google3/third_party/tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py", line 61, in _GetInferGraph
    func, _ = get_func_from_saved_model(trt_saved_model_dir)
  File "/build/work/f597b7130c23d9a7ed113a86d697d5f754ae/google3/runfiles/google3/third_party/tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py", line 56, in get_func_from_saved_model
    saved_model_dir, tags=[tag_constants.SERVING])
TypeError: 'module' object is not callable

**Comment by gbaned** [comment]
@Kh4L Can you please check @bixia1's comments and keep us posted ? Thanks!

**Comment by gbaned** [comment]
@Kh4L Any update on this PR? Please. Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by bixia1** [comment]
> Are you sure the change is correct? I got this error:
> 
> Traceback (most recent call last): File "/build/work/f597b7130c23d9a7ed113a86d697d5f754ae/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", line 1645, in decorated return f(self, *args, **kwargs) File "/build/work/f597b7130c23d9a7ed113a86d697d5f754ae/google3/runfiles/google3/third_party/tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py", line 1101, in _Test self.RunTest(run_params) File "/build/work/f597b7130c23d9a7ed113a86d697d5f754ae/google3/runfiles/google3/third_party/tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py", line 1018, in RunTest infer_saved_model_dir = self._GetInferGraph(run_params, saved_model_dir) File "/build/work/f597b7130c23d9a7ed113a86d697d5f754ae/google3/runfiles/google3/third_party/tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py", line 61, in _GetInferGraph func, _ = get_func_from_saved_model(trt_saved_model_dir) File "/build/work/f597b7130c23d9a7ed113a86d697d5f754ae/google3/runfiles/google3/third_party/tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py", line 56, in get_func_from_saved_model saved_model_dir, tags=[tag_constants.SERVING]) TypeError: 'module' object is not callable

this PR doesn't seem to make the right change, as I pointed out before.

**Comment by gbaned** [comment]
@Kh4L Can you please check @bixia1's comments and keep us posted ? Thanks!

**Comment by Kh4L** [comment]
@bixia1 I think this change is not relevant here, it was an internal fix, closing now

**Pull request closed without merging**
