### PR TITLE
pip_package: reorganize includes for tf.sysconfig.get_compile_flags()

### PR DESCRIPTION
**Pull request by perfinion**
When tensorflow was moved to tensorflow_core the includes were renamed
as well and no longer worked. This renames them back and cleans up the
includes.

The previous fix for this moved the files around without the wheel
manifest being updated. This changes the file path in the header install
so they are correct in the manifest.

Signed-off-by: Jason Zaman <jason@perfinion.com>

@angersson @mihaimaruseac @byronyi This fixes it on my machine but can you verify it too?

### CODE REVIEW

**Comment by perfinion** [comment]
I'm not completely sure the bit for --nolegacy_external_runfiles is right. Can you guys verify that too?

**Review by mihaimaruseac — DISMISSED** [review]
Thank you

**Comment by byronyi** [comment]
It works in the sense of get_compile_flags. Thanks, @perfinion!

**Comment by perfinion** [comment]
Fixed the pylint error (line too long) in ubuntu-sanity

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Thanks. I fixed some merge conflict internally, that's why Copybara didn't autoclose

**Pull request closed without merging**
