### PR TITLE
support freeze graph where there are control ops between ReadVariableOp and VarHandleOp

### PR DESCRIPTION
**Pull request by yangw1234**

### CODE REVIEW

**Comment by yangw1234** [comment]
@gargn would you help review this?

**Comment by yangw1234** [comment]
@drpngx @annarev Hi guys, it's been 10 days since I created this pr, is there any progress on the reviewing process?

**Comment by miaout17** [comment]
As far as I know, this module is mostly only used by TensorFlow Lite conversion now. 
TensorFlow Lite is going to support control flow V2 (e.g. If, While) but not V1 (e.g. Enter, Exit). 
Could you help us to better understand your use cases?

**Comment by yangw1234** [comment]
@miaout17 I see what you are saying. In my, we want to freeze a tensorflow model and load it on java side for inference. But it has problems with some tf.keras layers as described in  https://github.com/tensorflow/tensorflow/issues/25721

**Comment by wysohn** [comment]
Any update on this one? I'm having the same problem as yangw1234, trying to freeze the graph consisting the tf.keras.layers.LSTM layer throws "Cannot find the variable that is an input to the ReadVariableOp." exception.

**Comment by bhorkar** [comment]
Any progress on this issue?

**Comment by gargn** [comment]
Closing this PR. This functionality was added with slightly more streamlined logic recently.

**Pull request closed without merging**
