### PR TITLE
De-Bazel check_load_py_test sanity check

### PR DESCRIPTION
**Pull request by Androbin**
See https://github.com/tensorflow/tensorflow/pull/15368#issuecomment-354156560 for reference.
@gunan @martinwicke Friendly ping.

### CODE REVIEW

**Comment by martinwicke** [comment]
@gunan do you see a reason why this would not work? This should be completely independent of the makefile build, right?

**Comment by gunan** [comment]
This one is independent from the makefile build. This just makes sure we use our own py_test rule rather than the native py_test rule.

**Comment by Androbin** [comment]
Is there anything left to do for this PR?

**Comment by gunan** [comment]
@martinwicke is currently on vacation due to the holidays, I would like to leave the final call to him on these changes.
He should be back next week.

**Comment by Androbin** [comment]
@gunan Do we yet know if this will work?

**Comment by gunan** [comment]
Redirecting this to @yifeif who wrote the check.

**Review by yifeif — APPROVED** [review]
Thanks @Androbin!

**Comment by Androbin** [comment]
Resolved merge conflicts.

**Comment by martinwicke** [comment]
Thank you!

**Pull request merged**
