### PR TITLE
1.12-rc1 cherry-pick request: Support Keras TPU model to load saved weights and predict.

### PR DESCRIPTION
**Pull request by rachellj218**
PiperOrigin-RevId: 215920993

### CODE REVIEW

**Comment by tatatodd** [comment]
Can you file a bug in buganizer, assign to me, and describe the urgency of this PR?

**Review by tatatodd — APPROVED** [review]

**Comment by rachellj218** [comment]
Thank you, Todd! Do I need to do anything about the Internal CI build failure?

**Comment by tatatodd** [comment]
The failures are due to internal issues.  I'm going to merge now.

**Comment by rachellj218** [comment]
Great. Thanks a lot, Todd.

**Pull request merged**
