### PR TITLE
Branch 150542283

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by caisq** [comment]
cc @ispirmustafa @xiejw @martinwicke for insights into the failures in python/estimator tests.

See log at:
https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/4123/consoleFull

Could this have to do with the content of https://github.com/caisq/tensorflow/blob/branch_150542283/tensorflow/python/estimator/inputs/__init__.py ?

For example:
```
FAIL: //bazel_pip/tensorflow/python/estimator:estimator_test (see /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/testlogs/bazel_pip/tensorflow/python/estimator/estimator_test/test.log).
INFO: From Testing //bazel_pip/tensorflow/python/estimator:estimator_test:
==================== Test output for //bazel_pip/tensorflow/python/estimator:estimator_test:
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/bazel_pip/tensorflow/python/estimator/estimator_test.runfiles/org_tensorflow/bazel_pip/tensorflow/python/estimator/estimator_test.py", line 31, in <module>
    from tensorflow.python.estimator.inputs import numpy_io
ImportError: cannot import name numpy_io
```

**Comment by terrytangyuan** [comment]
@caisq `numpy_io` needs to be imported in the init file and added to the allowed symbols. Or you can import `numpy_input_fn` instead of importing `numpy_io` in that test.

**Comment by terrytangyuan** [comment]
BTW @martinwicke I haven't dived into how `allowed_symbol` works yet but is there a way for external users to use some internal methods/classes that are not included in `allowed_symbols`?

**Comment by caisq** [comment]
@terrytangyuan Thanks for the input. Yes, adding numpy_io, pandas_io and export to allowed_symbols will fix the tests. But I want to check with the tf-learn estimator team that this is the okay, because those symbols might be meant to be hidden from the public API.

**Comment by caisq** [comment]
@terrytangyuan Didn't see the second part of your suggestion. Yes you are right - importing numpy_input_fn instead of numpy_io and so on should solve the problem. Will try the fix.

**Comment by caisq** [comment]
There is a fix coming from internal. Closing the PR.

**Pull request closed without merging**
