### PR TITLE
Create a script for building tensorflow pip package on windows using bazel.

### PR DESCRIPTION
**Pull request by gunan**
Scripts created by @meteorcloudy

### CODE REVIEW

**Comment by gunan** [comment]
Manually killed all tests, jenkins is overloaded and I needed the PR to start testing windows bazel build.

**Comment by meteorcloudy** [comment]
This change looks good to me!

**Comment by gunan** [comment]
http://ci.tensorflow.org/job/tensorflow-pull-requests-windows-bazel/4/console

@meteorcloudy How about the failure above.
Is it caused by this change, or something missing here?
Or is it simply a breakage existing in the repo and we address it separately.

**Comment by meteorcloudy** [comment]
Ah.. Looks like we are hitting the [Windows long path issue](http://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows).
Basically, Windows doesn't support file path longer than 260 characters. Unfortunately, AFAIK, there's no workaround for cl.exe. 

This error is because `tensorflow-pull-requests-windows-bazel` is long enough to make the file path exceed that limitation.

We'll have to work around this by setting `export TMPDIR=c:/temp`, so compare to `C:\\tools\\msys64\\var\\tmp` we can save some characters...

**Comment by meteorcloudy** [comment]
I just noticed there's no need to use double back slash `\\`, this could save us a lot of characters, I'll fix it in the next Bazel release.

**Comment by meteorcloudy** [comment]
```
15:18:35 ERROR: C:/tmp/Bazel/3SovMC5L/external/protobuf/BUILD:579:1: Linking of rule '@protobuf//:internal/_api_implementation.so' failed: msvc_link.bat failed: error executing command 
15:18:35   cd C:/tmp/Bazel/3SovMC5L/execroot/tensorflow-pull-requests-windows-bazel
15:18:35   SET PATH=external/local_config_cc/wrapper/bin
15:18:35   external/local_config_cc/wrapper/bin/msvc_link.bat /DLL /WHOLEARCHIVE -m64 -Xcompilation-mode=opt -Wl,@bazel-out/vc_14_0_x64-py3-opt/bin/external/protobuf/internal/_api_implementation.so-2.params: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1120
15:18:35 LINK : warning LNK4001: no object files specified; libraries used
15:18:35 LINK : error LNK2001: unresolved external symbol _DllMainCRTStartup
15:18:35 bazel-out/vc_14_0_x64-py3-opt/bin/external/protobuf/internal/_api_implementation.so : fatal error LNK1120: 1 unresolved externals
15:18:35 ERROR: C:/tmp/Bazel/3SovMC5L/external/zlib_archive/BUILD:5:1: output 'external/zlib_archive/libzlib.a' was not created
15:18:35 ERROR: C:/tmp/Bazel/3SovMC5L/external/grpc/BUILD:69:1: output 'external/grpc/libgpr.a' was not created
15:18:35 ERROR: C:/tf_jenkins/home/workspace/tensorflow-pull-requests-windows-bazel/tensorflow/core/BUILD:1112:1: declared output 'tensorflow/core/util/version_info.cc' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
```
I saw the new error message on ci, I can reproduce the same error when using "tensorflow-pull-requests-windows-bazel" as the workspace folder name.
Although the error message is not obvious, the underlying problem is still caused by long path. Is it ok to rename the job name to something like `tf-pr-win-bazel`?
So sorry for the trouble, I will fix this soon. (actually, we can only ease this by not using `\\` to save some characters)

**Comment by gunan** [comment]
A-ha, now it is running:
http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/1/console

**Comment by gunan** [comment]
Hehe, I don't think I can approve this PR :)
@meteorcloudy with the new job name, do we need the TMPDIR environment variable?
Also, should I "set -e" in the script?
Not sure how msys bash works.

**Comment by meteorcloudy** [comment]
@gunan Probably yes, it's better we still have it for now.
I can only confirm we don't need it when job name is as short as `tensorflow`
Setting `set -e` sounds good to me, just add it in the beginning of the script, it should be the same as linux.

Why can't you approve this? What else need to be done?

**Comment by gunan** [comment]
Since I am the author of the PR, it wont let me approve.
I will add set -x and set -e to the bash piece.

**Comment by meteorcloudy** [comment]
Haha, I see~  :)

**Comment by gunan** [comment]
@meteorcloudy Final question:
http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/2/consoleFull

We see this error, it does not seem to affect the outcome, but all bazel builds have it:

00:00:36.893 ERROR: CreateFile(C:\tmp\Bazel\hzVGLx29\install): The system cannot find the file specified.

Any idea what it is?

**Comment by meteorcloudy** [comment]
@gunan It happens when running Bazel in a new workspace for the first time, Bazel tries to unzip itself to a install directory. But yes, we should get rid of this error message since it's not actually causing any problem.
We have an issue here: https://github.com/bazelbuild/bazel/issues/1744

Vijay just invited me to join TensorFlow organization, does that mean I can approve this? :)

**Review by mrry — APPROVED** [review]
LGTM.

**Pull request merged**
