### PR TITLE
Allow for different input signatures for different modes and additionally updating zlib fix

### PR DESCRIPTION
**Pull request by abhitopia**
Reopening #5546 on request of @martinwicke 

Changes were reverted back for `estimator.py` which allows different input signatures under different operating modes (`EVAL`, `INFER`, `TRAIN`). 

Additionally, I had to also fix weird zlib error which happened due to the updation of version.

### CODE REVIEW

**Comment by abhitopia** [comment]
@martinwicke - here is the PR again. It's very small change.

**Comment by drpngx** [comment]
@abhitopia please sync and push.

**Comment by drpngx** [comment]
Note that there is zlib 11:

"Due to the bug fixes, any installations of 1.2.9 or 1.2.10 should be immediately replaced with 1.2.11."

**Comment by abhitopia** [comment]
@drpngx - Reopened PR merged with master in #6887

**Pull request closed without merging**
