### PR TITLE
Improved a virtualenv option

### PR DESCRIPTION
**Pull request by ghost**
Replaced the "--system-site-packages" option of virualenv with "--no-site-packages" option, so that the packages required by tensorflow are installed separately with the system packages.
 Otherwise, there could be multiple versions of an installed package (e.g. numpy-1.8.2 installed by apt and numpy-1.12.0 installed by pip), and an error may occur when executing "import tensorflow".

### CODE REVIEW

**Review by caisq — APPROVED** [review]

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@xioryu The change looks good to me. Thank you for your sending the pull request. However, it looks like that you haven't signed the CLA yet. Could you please do that? Thanks.

**Comment by xioryu** [comment]
I signed the CLA.

**Comment by caisq** [comment]
PR merged. Thanks, @xioryu !

**Pull request merged**
