### PR TITLE
Branch 170594836

### PR DESCRIPTION
**Pull request by sb2nov**

### CODE REVIEW

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Review by drpngx — APPROVED** [review]

**Comment by sb2nov** [comment]
@drpngx the CLA bot hasn't commented on the PR for some reason. Is there a way to force trigger it?

**Comment by drpngx** [comment]
Usually it comes after a while. Not sure why it got stock. Maybe it's a large CL.

**Comment by drpngx** [comment]
Is that a flaky test (`monitored_session_test`)?

```
INFO: From Testing //tensorflow/python:monitored_session_test:
==================== Test output for //tensorflow/python:monitored_session_test:
2017-10-01 22:47:36.584234: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
...................WARNING:tensorflow:From /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/monitored_session_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session_test.py:1207: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
..........F................................................
======================================================================
FAIL: test_recover_and_retry_on_aborted_error (__main__.MonitoredSessionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/monitored_session_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session_test.py", line 1198, in test_recover_and_retry_on_aborted_error
    self.assertEqual(3, session.run(do_step))
AssertionError: 3 != 2
```

**Comment by sb2nov** [comment]
I think so as it didn't happen in the previous run of the tests.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by caisq** [comment]
@sb2nov @drpngx Is this PR ready to merge?

**Comment by drpngx** [comment]
We're investigating why the CLA doesn't trigger.

**Comment by sb2nov** [comment]
The CLA was manually approved on the PR. All changes are coming from internal code so have been committed by Googlers so it should be safe to merge this.

**Comment by gunan** [comment]
@willnorris looks like we ran into a bug with the CLA bot.
We will merge the change now, but any idea why CLA bot did not respond on this change?
I checked and bot is working fine on all other PRs. Maybe too many commits in this PR?

**Comment by sb2nov** [comment]
b/67294573 mentions that the PR was timing out due to large number of commits.

**Comment by cflewis** [comment]
Please don't manually pull @willnorris into threads: he's on paternity leave and it means no-one else can help.

You can/should contact us internally.

**Pull request merged**
