### PR TITLE
Additional portable_optimized kernels plus associated test-suite improvements

### PR DESCRIPTION
**Pull request by andrewstevens-infineon**
Adds portable_optimized implementations of fully_connected, conv, and depthwise_conv ops to tflite(u)

Associated tflite(u) fixes/improvements:

-  Test suite updated to run correctly on (at least x86) 32-bit targets
-  Minor coverage/robustness improvements in test suite.
-  MinGW target support "windows_x86_makefile.inc"

### CODE REVIEW

**Comment by gbaned** [comment]
@andrewstevens-infineon  Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@andrewstevens-infineon,  Any update on this PR? Please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by andrewstevens-infineon** [comment]
Returned from Vacation.   Resolving confilicts w.r.t. current master.

**Comment by gbaned** [comment]
@andrewstevens-infineon Can you please resolve conflicts? Thanks!

**Comment by advaitjain** [comment]
Actually, before we ask @andrewstevens-infineon to do more work on this PR, I think it might be worth a conversation on the higher level goals of this work.

Tagging @petewarden to get his thoughts.

**Comment by gbaned** [comment]
@petewarden Any update on this PR? Please. Thanks!

**Comment by andrewstevens-infineon** [comment]
Hi Pete,

I'd assume the PR was on Ice due to the Freeze - thus hadn't follow-up on it.The overall objective was to provide better support for lowest-end HW lacking any acceleration featurtes/intrinsics library.   In our case small RISC-V uC. 

The same code-base was the starting point for  so-far uncontributed/local features (packed sub 8-bit quantized weights, the pre-interpreter to reduce RAM/ROM footprint, custom HW support) .  This is actually our primary focus right now. However, if you feel the PR is worth pursuing I'll see if I can peek to resolve the conflicts with current master and update with back-ported/stripped "portable_optimized" versions of some of the more recent stuff.

-Andrew

**Comment by advaitjain** [comment]
Let's close the current PR.

I think its probably worth having a conversation around what you guys are working on and how that can be merged upstream (if that is of interest to you). Maybe start with a discussion at the next SIG-micro meeting and go from there?

**Comment by andrewstevens-infineon** [comment]
Ok.

Let's  put an item on the Agenda for next SIG.   

- portable_optimized kernels (better support for uC missing dedicated kernels, especially low-end)
- Progress on offline pre-interpreter/static code generator.

**Pull request closed without merging**
