### PR TITLE
Update 2_fullyconnected.ipynb

### PR DESCRIPTION
**Pull request by richardsun-voyager**

### CODE REVIEW

**Comment by gunan** [comment]
Can one of the admins verify this patch?

**Comment by jendap** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
we need the CLA to be signed before we can accept.  are you able to sign?

**Comment by vrv** [comment]
(leave a comment if you're able to sign and we'll reopen, thanks!)

**Pull request closed without merging**
