### PR TITLE
Fix typos in compiler directory

### PR DESCRIPTION
**Pull request by Molkree**
Splitting #43857 by top-level directories.

### CODE REVIEW

**Comment by joker-eph** [comment]
Nice, Thanks! 
LGTM, assuming it passes the tests.

**Review by joker-eph — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by rthadur** [comment]
@Molkree can you please resolve conflicts

**Comment by Molkree** [comment]
@rthadur, resolved

**Review by mihaimaruseac — APPROVED** [review]

**Comment by akuegel** [comment]
Can you please rebase your PR? It seems some files have changed by now. Also, possibly exclude the changes to tf2tensorrt directory, because those seem to trigger additional checks which our workflow to pull in PRs cannot handle (we would have to do it manually).

**Comment by Molkree** [comment]
@akuegel, rebase or merge? I don't see any conflicts in GitHub interface but sure, if you request it.
And fine, I'll remove that directory now.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by Molkree** [comment]
@mihaimaruseac, I see that this was merged, should I close PR?

**Comment by gbaned** [comment]
@Molkree Thank you for the confirmation.
Seems auto-merge is not happening but the changes are merged into master now, so we can close this PR.

**Pull request closed without merging**
