### PR TITLE
grpc+seastar: add grpc+seastar protocol

### PR DESCRIPTION
**Pull request by byronyi**
Re-submission of #27454 as the previous PR is messed up.

This PR serves as a placeholder for contribution from @liutongxuan and his colleagues in Alibaba.

Since TF is going to have yet another (hopefully last) release before 2.0 (r1.14 to be cut on April 15), I am not sure if we have enough time (or incentive) to push this feature into the main repo.

tensorflow/networking should serve as the final target after 2.0. As we are still transitioning and @annarev is working on the networking C API, I would still like to submit this PR against the main repo, mainly for the convenience of reviewing. When we feel like ready, we shall have another PR in https://github.com/tensorflow/networking for refactoring it as a standalone plugin.

Ping @jbedorf @poxvoculi @liutongxuan @lilbedwin @shanshanpt @YongCHN @swpnlptl.

I believe there are a few review comments not fully addressed:

- [ ] https://github.com/tensorflow/tensorflow/pull/27454#discussion_r296912350
- [x] https://github.com/tensorflow/tensorflow/pull/27454#discussion_r296911797
- [ ] https://github.com/tensorflow/tensorflow/pull/27454#issuecomment-504677772 (Optional)

Boost is now not a direct dependency for this patchset, but still a transitive one for seastar.

### CODE REVIEW

**Comment by liutongxuan** [comment]
CLA Agree

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@liutongxuan Could you please sign cla ? Thank you.

**Comment by liutongxuan** [comment]
Agree

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
