### PR TITLE
Fix tensorrt bazel configuration file typo

### PR DESCRIPTION
**Pull request by jerryyin**
incude -> include

This is breaking our CI

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by rthadur** [comment]
@jerryyin can you please check build failures

**Comment by mihaimaruseac** [comment]
There's a fix pending for these failures, they're internal. Will ping here once the fix is landed to retry the tests.

**Comment by mihaimaruseac** [comment]
See also #27901

**Comment by mihaimaruseac** [comment]
Closing because duplicate got merged

**Pull request closed without merging**
