### PR TITLE
Fix beam term incorrect usage in BeamSearchDecoder

### LINKED ISSUE #17839: Beam search terminology
(This issue is with terminology used in documentation and code. System information not applicable.)

The documentation and code in tf.contrib.seq2seq.BeamSearchDecoder and friends seems to use "beam" to mean "search state", whereas beam conventionally means "a collection of search states". This non-standard usage makes for confusing documentation!

Examples in documentation at https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/BeamSearchDecoder:

"The BeamSearchDecoder shuffles its beams" 
"beam_width: Python integer, the number of beams" 

Or in code:

https://github.com/tensorflow/tensorflow/blob/838a8f54f92452a15e3bb62a23ad5cd67e86933f/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py#L144

The conventional search algorithm terminology as I understand it, and attested by wikipedia (https://en.wikipedia.org/wiki/Beam_search) and recent academic usage (http://www.ijcai.org/Proceedings/05/Papers/0596.pdf), is that beam search is called beam search because it keeps a beam of search states in memory. The beam refers to the collection of search states, not the individual search states (I presume by the analogy that a beam of light illuminates certain objects but not others that fall outside the beam).

### PR DESCRIPTION
**Pull request by imsheridan**
This PR is to fix #17839.

As raised in the above issue, from the [Beam_search wikipedia definition](https://en.wikipedia.org/wiki/Beam_search) and [Recent academic usage] (http://www.ijcai.org/Proceedings/05/Papers/0596.pdf), beam search is called beam search because it keeps a beam of search states in memory. 

The beam refers to the collection of search states, not the individual search state.
This PR is to fix the incorrect usage of "beam" term in [BeamSearchDecoderExamples](https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/BeamSearchDecoder), like example below:
"The BeamSearchDecoder shuffles its **beams**"
"beam_width: Python integer, the number of **beams**"

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 52 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 67 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 82 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 97 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 112 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 126 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by annarev** [comment]
@ebrevdo Eugene, can you please take a look at this doc change?

**Comment by ebrevdo** [comment]
Thanks!

**Review by ebrevdo — APPROVED** [review]

**Comment by ebrevdo** [comment]
Done thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 19 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by MattShannon** [comment]
This PR is just a straight-up replace of "beam" for "search state" which leaves the documentation ungrammatical or nonsensical in many places. (I'm afraid I don't have bandwidth at the moment to make the docs better though.)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
@imsheridan could you pull rebase and push again?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rthadur** [comment]
@imsheridan gentle ping to re base

**Comment by rthadur** [comment]
closing this due to rebase pending for long time.

**Pull request closed without merging**
