### PR TITLE
[Intel MKL]: Fixing a build issue in mkl_cpu_allocator

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR fixes a build regression happened in mkl_cpu_allocator because of other commit:
https://github.com/tensorflow/tensorflow/commit/505b11b8c230e644cc4ff71f98a0b22e84514e7e#diff-b34307576896d87b6abd5a4c273d3fa6

### CODE REVIEW

**Comment by mahmoud-abuzaina** [comment]
Hi @penpornk, this is blocking us from building TF with MKL. Can you have a look at this fix?

**Review by penpornk — APPROVED** [review]
Looks good to me. Thank you for your prompt fix! And I'm sorry we broke your build again. :(

@rthadur, would you mind being the assignee for this PR, or could you please help suggest someone else? Thank you very much!

**Comment by penpornk** [comment]
@rthadur Thank you! :)

**Comment by mahmoud-abuzaina** [comment]
@penpornk @rthadur thank you so much for the quick response.

**Pull request merged**
