### PR TITLE
[Intel MKL] Adding Quantized Convolution (Int8) - Part 3

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR is part 3 of four PRs that add quantized version of convolution using MKL-DNN. This part adds changes that are required to quantize a graph and it enables fusions of MKL quantized convolution. 

Please note that the below PRs replace this one #19425 
Part 1: #21483 
Part 2: #21456 
Part 3: #21465 
Part 4: #21466

### CODE REVIEW

**Comment by dspinxd** [comment]
在 2018年8月8日，08:28，Mahmoud Abuzaina <notifications@github.com<mailto:notifications@github.com>> 写道：


This PR is part 3 of four PRs that add quantized version of convolution using MKL-DNN. This part adds changes that are required to quantize a graph and it enables fusions of MKL quantized convolution.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/tensorflow/tensorflow/pull/21465

Commit Summary

  *   Adding int8 conv part3

File Changes

  *   M tensorflow/tools/graph_transforms/BUILD<https://github.com/tensorflow/tensorflow/pull/21465/files#diff-0> (1)
  *   A tensorflow/tools/graph_transforms/fuse_quantized_convolution.cc<https://github.com/tensorflow/tensorflow/pull/21465/files#diff-1> (220)
  *   M tensorflow/tools/quantization/quantize_graph.py<https://github.com/tensorflow/tensorflow/pull/21465/files#diff-2> (348)

Patch Links:

  *   https://github.com/tensorflow/tensorflow/pull/21465.patch
  *   https://github.com/tensorflow/tensorflow/pull/21465.diff

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @tatianashp, @raghuraman-k: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 20 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @tatianashp, @raghuraman-k: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 35 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @tatianashp, @raghuraman-k: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 50 days with no activity and the `awaiting review` label has been applied.

**Review by raghuraman-k — COMMENTED** [review]
Please remove quantize_graph from this PR. It will be best to host it separately.

**Comment by mdfaijul** [comment]
@raghuraman-k @drpngx removed quantize_graph.py

**Comment by mdfaijul** [comment]
@drpngx Tests looks fine. Ready to go?

**Comment by tatianashp** [comment]
@suharshs Can you take a look? Is this PR still relevant?

**Review by suharshs — DISMISSED** [review]

**Comment by drpngx** [comment]
@mahmoud-abuzaina please return an error (invalid argument) for when the tensor parsing fails and not implemented if the dtype is wrong:
```
CHECK(float_tensor.FromProto(float_tensor_proto));
CHECK_EQ(float_tensor.dtype(), DT_FLOAT);
```
We do not allow `CHECK` in new code.

**Pull request merged**
