### PR TITLE
Update r0.12 branch

### PR DESCRIPTION
**Pull request by gunan**
Merge important updates into the release branch.

### CODE REVIEW

**Comment by jhseu** [comment]
LGTM. Feel free to merge if you don't want to wait for Jenkins.

**Comment by jhseu** [comment]
Looks like mac0-slave needs portpicker installed.

**Comment by gokceneraslan** [comment]
Please include https://github.com/tensorflow/tensorflow/pull/5645 as well, fully-connected layer in contrib.layers is not Python 3 compatible in 0.12 branch right now.

**Comment by jhseu** [comment]
#5645 is in the r0.12 branch, so it'll appear in the release.

Merging:
- CLAs are covered by the master branch
- Mac failures happen only on that machine because it's missing portpicker, so I'm ignoring them

**Comment by gunan** [comment]
mac0 is now taken care of.
Thanks for merging, Jonathan.

Now 0.12 branch is locked. :)

**Pull request merged**
