### PR TITLE
feat : update return value

### PR DESCRIPTION
**Pull request by IllidanSR**

### CODE REVIEW

**Comment by IllidanSR** [comment]
@googlebot I signed it!

**Comment by IllidanSR** [comment]
@googlebot I fixed it.

**Comment by IllidanSR** [comment]
@googlebot I fixed it.

**Comment by gbaned** [comment]
@IllidanSR  Can you please sign CLA. Thanks!

**Comment by gbaned** [comment]
@IllidanSR Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
