### PR TITLE
Hadoop filesystem helper

### PR DESCRIPTION
**Pull request by vnghia**
@mihaimaruseac 
This PR adds some helper functions and class port from `core/platform/hadoop`.

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
There might be an issue with the `functional` header but let's try to import while I look if that is allowed

**Comment by vnvo2409** [comment]
I don't change anything at all ( just `status` to `TF_Status` ) so I hope it will be fine

**Comment by mihaimaruseac** [comment]
Oh, then it should be easy to go around potential restrictions.

**Comment by mihaimaruseac** [comment]
I had to do a few minor changes internally after import, but nothing major. It should land in a few hours (currently running tests)

**Comment by vnvo2409** [comment]
Actually, in the next PR, I will remove `libhdfs()` because it causes a memory leak. So if there is a problem with `libhdfs()`, please let me know and I will push a commit to address that problem.

**Comment by mihaimaruseac** [comment]
Hmm, I think the issue was not there. I didn't keep a list of the manual changes I did, unfortunately

**Pull request merged**
