### PR TITLE
Add uint8_t -> int8_t requant method

### PR DESCRIPTION
**Pull request by vikramdattu**
This is required when input to the model is in uint8_t format.
We need this quant op as a first layer.
One of such example is image data.

Related MR: https://github.com/tensorflow/tensorflow/pull/44580

### CODE REVIEW

**Comment by vikramdattu** [comment]
@advaitjain PTAL

**Comment by EliZucker** [comment]
Ran into this issue today..

It looks like converting to .tflite networks that support uint8 input, as seen in the person-detector example, is not possible anymore. In other words, with the current TFLite converter, it is impossible to create a network that the ESP32 can natively use with its uint8 camera frames.

**Review by EliZucker — CHANGES_REQUESTED** [review]
I tested this change and pretty sure this check needs to be updated to allow kTfLiteUInt8 inputs. 

Edit: not sure I commented on the line correctly. I'm talking about the check on line 65 of quantize.cc:
```
TF_LITE_ENSURE(context, input->type == kTfLiteFloat32 ...
```

**Comment by vikramdattu** [comment]
Hi @EliZucker right. UInt8 input case needs to be enabled.

The code/checks around these lines(`Prepare` from `quantize.cc`) will look like this:
```
  if (input->type == kTfLiteFloat32) {
    // Quantize use case.
    TF_LITE_ENSURE(context, output->type == kTfLiteInt8 ||
                                output->type == kTfLiteInt16);
  } else {
    // Requantize use case.
    // We allow Int16, UInt8 and Int8 inputs.
    TF_LITE_ENSURE(context, input->type == kTfLiteInt16 ||
                                input->type == kTfLiteUInt8 ||
                                input->type == kTfLiteInt8);

    // Output is restricted to Int8.
    TF_LITE_ENSURE(context, output->type == kTfLiteInt8);

    double effective_scale = static_cast<double>(input->params.scale) /
                             static_cast<double>(output->params.scale);

    QuantizeMultiplier(effective_scale, &data->output_multiplier,
                       &data->output_shift);
  }

```

Some of the checks are inspired from classic tflite's quantize.cc above.
Kept Float32 in above change. Shall I remove Float32 support completely?

Also, this line from my code:
```
    // Output is restricted to Int8.
    TF_LITE_ENSURE(context, output->type == kTfLiteInt8);
```

restricts output to `Int8`. Since we want to deprecate all other OPS to just keep Int8 OPS.

cc @advaitjain

**Review by advaitjain — CHANGES_REQUESTED** [review]
The scope of change looks good to me. Can you also add a test case to quantize_test.cc?

**Comment by advaitjain** [comment]
Adding to the discussion between @EliZucker and @vikramdattu:

These lines should also be updated (I would hope that a unit test would catch this case):
https://github.com/tensorflow/tensorflow/blob/107b96da1ca5f0db752a11c4fae85ef1272ee175/tensorflow/lite/micro/kernels/quantize.cc#L73-L76

Additionally, since the TF_LITE_ENSURE checks that @EliZucker pointed out in the Prepare function are basically a repeat of the checks in Eval, I would be fine with removing this code block completely:
https://github.com/tensorflow/tensorflow/blob/107b96da1ca5f0db752a11c4fae85ef1272ee175/tensorflow/lite/micro/kernels/quantize.cc#L65-L71

**Comment by EliZucker** [comment]
Just want to say that I recommend trying a manual E2E before merging. I ran these changes myself and behavior did not match a Tf lite interpreter on my computer. 

I didn't have time to debug so just manually converted the esp32 camera values to int8 range and it worked fine. Can post more details if you're curious; it could also be an error from my side as I'm new to this project.

**Comment by vikramdattu** [comment]
@advaitjain 

I get error when I run test for x86 (OS: MacOS Catalina 10.15.07)

```
tensorflow/lite/micro/examples/person_detection/person_detection_test.cc:30:24: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and section separated by a comma
__attribute__((section(".bss.NoInit"), aligned(16)))
                       ^
1 error generated.
make: *** [tensorflow/lite/micro/tools/make/Makefile:488: tensorflow/lite/micro/tools/make/gen/osx_x86_64/obj/tensorflow/lite/micro/examples/person_detection/person_detection_test.o] Error 1
make: *** Waiting for unfinished jobs....
```

Can you please help get pass the issue?

**Comment by EliZucker** [comment]
@vikramdattu I fixed some errors by using ESP-IDF Toolchain v4.0 for that example project. Might be the issue.

**Comment by vikramdattu** [comment]
@EliZucker thanks for quick reply.

I got past this error by simply commenting out that attribute.

I now get one test fail even without UInt8 quant addition.

```
tensorflow/lite/micro/tools/make/gen/osx_x86_64/bin/person_detection_test_int8: FAIL - '~~~ALL TESTS PASSED~~~' not found in logs.
Testing TestInvoke
person data.  person score: -4, no person score: 4

person_score > no_person_score failed at tensorflow/lite/micro/examples/person_detection_experimental/person_detection_test.cc:103
no person data.  person score: -72, no person score: 72
```

**Comment by vikramdattu** [comment]
@advaitjain @EliZucker 
One more question:

I have added few more tests: `QuantizeOpTestUInt8toInt8` and `QuantizeOpTestUInt8toInt8NoZeroPoint`.
How do I know if these are getting called? Is running x86 tests does this already?

**Comment by vikramdattu** [comment]
@advaitjain @EliZucker manually tested this with a custom example I have created here: https://github.com/vikramdattu/tensorflow/commits/master 

Please refer [this](https://github.com/vikramdattu/tensorflow/blob/master/tensorflow/lite/micro/examples/cats_and_dogs/esp/README_ESP.md#generate-the-examples) README to build and run example on ESP32. [Please do ignore some of the unclean code]

**Comment by gbaned** [comment]
@vikramdattu Can you please resolve conflicts? Thanks!

**Comment by vikramdattu** [comment]
> @vikramdattu Can you please resolve conflicts? Thanks!

@gbaned done! Please take a look again.

**Comment by vikramdattu** [comment]
@advaitjain please take a look. Tests are added.

Please take a look at choice of values:
```
const float values[] = {64, 66, 68, 70, 72, 182, 184, 186, 188, 190};
```

These are values used for int8 test+128
```
const float values[] = {-64, -62, -60, -58, -56, 54, 56, 58, 60, 62};
```

**Comment by gbaned** [comment]
@vikramdattu Can you please resolve conflicts? Thanks!

**Comment by vikramdattu** [comment]
@gbaned conflicts are resolved. PTAL.

**Comment by gbaned** [comment]
@vikramdattu Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@vikramdattu  Any update on this PR? Please. Thanks!

**Comment by vikramdattu** [comment]
Hi @gbaned the PR raised is 4-5 months old and I have done multiple merges to update it.

Do you mind if I reconsider it for new PR?

**Comment by gbaned** [comment]
@advaitjain Can you please assist on above comments from @vikramdattu. Thanks!

**Comment by gbaned** [comment]
@advaitjain Any update on this PR? Please. Thanks!

**Comment by advaitjain** [comment]
With TFLM moving to its own GitHub repository, we are not going to be merging any TFLM specific pull requests in the TensorFlow repository starting today.

I am closing the current PR but please feel free to open a new PR in https://github.com/tensorflow/tflite-micro/.

https://groups.google.com/a/tensorflow.org/g/micro/c/W4DACgjPmOE

**Pull request closed without merging**
