### PR TITLE
Rename WorkerCacheInterface::CreateWorker to GetOrCreateWorker().

### PR DESCRIPTION
**Pull request by jiakai0419**
for this
```
  // TODO(mrry): rename this to GetOrCreateWorker() or something that
  // makes it more obvious that this method returns a potentially
  // shared object.
  virtual WorkerInterface* CreateWorker(const string& target) = 0;
```

### CODE REVIEW

**Comment by jiakai0419** [comment]
@gbaned Would you mind adding another reviewer?

**Comment by jiakai0419** [comment]
@gbaned 
> hawkinsp removed their request for review just now
  
Would you mind adding another reviewer?

**Comment by mrry** [comment]
Reassigning this to @swpnlptl to take a look.

**Review by swpnlptl — APPROVED** [review]
Thanks for addressing the TODO.

**Comment by jiakai0419** [comment]
@swpnlptl 
Here are five Internal CI build failed. I don't think it's caused by my changes. What else do I need to do?

**Pull request merged**
