### PR TITLE
Modifying get_optimizer_experimental_options

### PR DESCRIPTION
**Pull request by Harsh188**
PR related to #42450

This pull request should fix the [issue](https://github.com/tensorflow/tensorflow/pull/43105#issuecomment-694910626) I brought up in #43105.

Modifications made to:
- `context.py`

### CODE REVIEW

**Comment by Harsh188** [comment]
@jaingaurav could you review this?

**Comment by jaingaurav** [comment]
@Harsh188: This doesn't seem right, I'm not sure what you're trying to achieve here, but what I talked about in #43105 referred to extracting the default values from C++ and exposing them up to the python layer somehow. I'm not sure how this achieves that.

**Comment by Harsh188** [comment]
@jaingaurav I thought about making an API to bring up the values from C++ but when I was reviewing [`context.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/context.py) I noticed something strange.

The `get_optimizer_experimental_options` function was not utilizing the global variable `_optimizer_experimental_options` dictionary.

If you take a look at [`set_optimizer_experimental_options`](https://github.com/tensorflow/tensorflow/blob/40c3e9fc618a7a1d4a466a877205cfa5a89f2132/tensorflow/python/eager/context.py#L1575) the global dictionary gets updated whenever a user wants to modify the options. There are also two functions on line [965](https://github.com/tensorflow/tensorflow/blob/40c3e9fc618a7a1d4a466a877205cfa5a89f2132/tensorflow/python/eager/context.py#L965) `rewriter_toggle` and `rewriter_bool` which initialize the `_optimizer_experimental_options` dictionary with default values.

However, [`get_optimizer`](https://github.com/tensorflow/tensorflow/blob/40c3e9fc618a7a1d4a466a877205cfa5a89f2132/tensorflow/python/eager/context.py#L1537) was the only function to not utilize the global dictionary. It instead, does the `rewriter_toggle` process, performed in the initial initialization of the dictionary, all over again.

This rose a few red flags for me. After taking a closer look at the [`rewriter_toggle`](https://github.com/tensorflow/tensorflow/blob/40c3e9fc618a7a1d4a466a877205cfa5a89f2132/tensorflow/python/eager/context.py#L1546) function defined in `get_optimizer_experimental_options` I noticed the following piece of code:
```python
attr = getattr(rewrite_options, option)
      if attr != 0:
        options[option] = (attr == rewriter_config_pb2.RewriterConfig.ON)
```
You can see here that if attr is not 1, then the option will not be updated to the dictionary. This is why only two values were being displayed in the [comment](https://github.com/tensorflow/tensorflow/pull/43105#issuecomment-692166581) I left in the original PR.

Essentially this entire method seemed redundant to me since all it had to do was return the global dictionary which already had the options initialized to their default values. That's why I opened up this PR.

_Sorry for the delayed response, I've been piled up with college work :'(_

**Comment by gbaned** [comment]
@jaingaurav Can you please take a look on above comments from @Harsh188. Thanks!

**Comment by Harsh188** [comment]
@jaingaurav Friendly ping :)

**Comment by kkimdev** [comment]
@Harsh188 Sorry for the late response.  Have you confined that `self._optimizer_experimental_options` is correctly initialized with default optimizer options? It wasn't clear to me when I read, and it seemed the dictionary is only updated here https://github.com/tensorflow/tensorflow/blob/9f813ea/tensorflow/python/eager/context.py#L1572 , not at initialization.  Also, in any case, let's add a test in `context_test.py` in the same directory.

**Comment by Harsh188** [comment]
Thanks for the reply @kkimdev!

You are correct. I don't think that `self._optimizer_experimental_options` is initialized correctly. It doesn't look like `_optimizer_experimental_options` is ever updated during the initialization process. Do you have any suggestions on how to fix it?

I would also love to get advice on how I can add a test in `context_test.py`. I'm not sure how to expose the default options set in C++ to test the validity of the optimizer options in the python layer.

**Comment by gbaned** [comment]
@kkimdev Can you please take a look on the above comment from @Harsh188. Thanks!

**Comment by kkimdev** [comment]
@Harsh188 Default values are implicitly hard-coded here https://github.com/tensorflow/tensorflow/blob/66b124e/tensorflow/core/grappler/optimizers/meta_optimizer.cc#L224 , so we need some refactoring.  I think `MetaOptimizer` should have an API returning default values so that we can initialize `self._optimizer_experimental_options` correctly.

**Comment by gbaned** [comment]
@Harsh188 Can you please check @kkimdev's comments and keep us posted ? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@Harsh188  Any update on this PR? Please. Thanks!

**Comment by Harsh188** [comment]
Hi, sorry to inform you that I won't be able to continue this any further. Unfortunately, I haven't had much luck in putting together the solution and I don't feel like I'm experienced enough with C++ to debug my issues. I hope someone can pick up where we left off.

**Pull request closed without merging**
