### PR TITLE
Fix uninitialized local variable

### PR DESCRIPTION
**Pull request by dominic-rossi**
Error is: 
`FailedPreconditionError (see above for traceback): Attempting to use uninitialized value input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs`

There exists a discussion about the problem and resolution [here](https://github.com/tensorflow/tensorflow/issues/3168).

### CODE REVIEW

**Comment by drpngx** [comment]
Please make sure you signed the CLA and reply to this thread as instructed by googlebot. Thanks!

**Comment by dominic-rossi** [comment]
The CLA for this PR is related to [this one](https://github.com/tensorflow/tensorflow/pull/8758).

**Comment by drpngx** [comment]
Sounds good, we might have to wait a little bit then. Thanks for your patience.

**Comment by dominic-rossi** [comment]
I signed it!

**Comment by drpngx** [comment]
Woohoo! 
Jenkins, test this please.

**Review by drpngx — APPROVED** [review]

**Comment by drpngx** [comment]
Checking if that's a transient failure on mac with syncreplicas.

Jenkins, test this please.

**Comment by drpngx** [comment]
Ignoring unrelated failure.

**Pull request merged**
