### PR TITLE
Better ARRAYSIZE macro for tensorflow/stream_executor/platform/port.h

### PR DESCRIPTION
**Pull request by j123123**
taken from https://chromium.googlesource.com/chromium/chromium/+/master/base/basictypes.h#104

### CODE REVIEW

**Comment by j123123** [comment]
I signed it!

**Comment by j123123** [comment]
I think I don't need to sign anything to contribute such small fix. Consider to do something like this https://github.com/dotnet/llilc/pull/1066#issuecomment-253989879 with your googlebot (to not sign anything if contribution is small enough)

**Comment by zheng-xq** [comment]
j123123@, I don't think we can merge any PR without CLA. 

martinwicke@, could you confirm that a CLA is absolutely necessary?

**Comment by j123123** [comment]
If you can't merge, close this PR and create a new same PR. This macro is in google chromium source, so I don't see any legal issue with it

**Comment by martinwicke** [comment]
Yup, we can't merge without CLA. Sorry.

**Pull request closed without merging**
