### PR TITLE
Update license year

### PR DESCRIPTION
**Pull request by m1guelpf**
TO DO:

- [x] Wait to the next year (100% done, depends on timezone)
- [x] Merge!

:octocat:

### CODE REVIEW

**Comment by m1guelpf** [comment]
Signed!

**Review by drpngx — APPROVED** [review]

**Comment by drpngx** [comment]
Let's wait until tomorrow.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
I guess it is technically Jan 1 on GMT. Happy New Year!

**Pull request merged**
