### PR TITLE
TFLu: Port SetCancellationFunction() from TFL and add test cases.

### PR DESCRIPTION
**Pull request by suphoff**
@petewarden : First draft of porting the SetCancellationFunction() from TFL.
Functionality should be fine - but need to check style in unit test.

### CODE REVIEW

**Comment by gbaned** [comment]
@suphoff Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@suphoff  Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@suphoff  Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@suphoff Gentle ping to resolve conflicts? Thanks!

**Comment by suphoff** [comment]
@gbaned : Sorry - I don't have the bandwidth to keep resolving conflicts right now.

**Pull request closed without merging**
