### PR TITLE
Add fuzzer for running static graph computations

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Review by fcoUnda — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Anything more for me to do here?

**Comment by gbaned** [comment]
> Anything more for me to do here?

Hi @DavidKorczynski No action pending at this moment. We will let you know if anything needed from you. Thank you!

**Comment by gbaned** [comment]
Hi @DavidKorczynski Can you please resolve conflicts? Thank you!

**Comment by DavidKorczynski** [comment]
I think was added by way of https://github.com/tensorflow/tensorflow/commit/71912f6e38c484a41b9417b25794a3f7b7a3d39c -- so no need to merge now and we can close this.

**Pull request closed without merging**
