### PR TITLE
Updated the clarity of specific comments in function.py 11212018

### PR DESCRIPTION
**Pull request by fullarray**
I reworked and updated the clarity of specific comments in function.py 11212018

### CODE REVIEW

**Review by alextp — APPROVED** [review]
Indeed functions are experimental; the tf.function API is not experimental but it uses a substantially different backend.

**Comment by alextp** [comment]
Can you fix the linter errors? Thanks!

**Comment by rthadur** [comment]
> Can you fix the linter errors? Thanks!

@fullarray gentle ping

**Comment by fullarray** [comment]
@rthadur yes indeed. I was reviewing the code for a different project back then and thought I add a little contribution.

**Pull request merged**
