### PR TITLE
Fix anchor tag in adding_an_op.md

### PR DESCRIPTION
**Pull request by Lewuathe**
Default anchor tag id is generated by the target text of the title. And it uses an underscore instead of hyphen.

### CODE REVIEW

**Comment by drpngx** [comment]
@MarkDaoust any opinion on this?

**Comment by MarkDaoust** [comment]
I pushed a couple of minor fixes.
I tested it with both g3doc and tensorflow.org.

LGTM

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by drpngx — APPROVED** [review]
As per Mark's comment.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by Scutua — APPROVED** [review]

**Pull request merged**
