### PR TITLE
apply gpu memory fraction option to static memory analysis during identifying memory swap candidates

### PR DESCRIPTION
**Pull request by pengwa**
run  tests (with GPU support), no reported errors. 
$ bazel test -c opt --config=cuda //tensorflow/...
$ bazel test -c opt --config=cuda //tensorflow/python/...

### CODE REVIEW

**Comment by allenlavoie** [comment]
Seems reasonable to me, but the swapping bit of the memory optimizer is much more Benoit's field.

**Comment by qlzh727** [comment]
Nudge for review.

**Comment by pengwa** [comment]
hi, is there anything I need do for the failed internal ci build?

**Comment by qlzh727** [comment]
let me kick off the new test and make sure its not flaky.

**Comment by pengwa** [comment]
@qlzh727 can you help trigger a new build validation? I got some update in the memory_optimizer_test.cc. thanks !!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @allenlavoie, @benoitsteiner: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by pengwa** [comment]
kokoro:run please.

**Comment by qlzh727** [comment]
Ping @benoitsteiner for review.

**Comment by allenlavoie** [comment]
Sorry for the delay.

Taking another look, is this not covered by https://github.com/tensorflow/tensorflow/blob/fe12159e60258d0b6cae9b580e248b22e80f3f7b/tensorflow/core/grappler/clusters/single_machine.cc#L108 ?

It seems like we should be setting memory_size to account for this fraction centrally (even though swapping is the major consumer) if it doesn't account for this fraction already. Is there some way we can unit test the effect of GPU memory limiting on Grappler's device information?

(CC @rmlarsen who has reviewed some of that code)

**Comment by pengwa** [comment]
@allenlavoie I confirmed the memory_optimizer.cc is using virtual_cluster instead of singplemachine.cc. So I believe I need to add some similar logic for virtual_cluster.cc?

**Comment by allenlavoie** [comment]
Sounds reasonable to me. Yao, does accounting for the per-process memory fraction in virtual_cluster make sense to you?

**Comment by pengwa** [comment]
@allenlavoie @zhangyaobit Let me recap a bit about the issues, and possible solutions. 

Issues: in https://github.com/tensorflow/tensorflow/blob/575db18083d5437fd7a87ccf3414303498911bb1/tensorflow/core/grappler/optimizers/memory_optimizer.cc#L969, 

- VirtualCluster is used in memoryoptimizer which is called by metaoptimizer (https://github.com/tensorflow/tensorflow/blob/575db18083d5437fd7a87ccf3414303498911bb1/tensorflow/core/grappler/optimizers/meta_optimizer.cc#L305).  
- VirtualCluster->GeDevices() return the "std::unordered_map<string, DeviceProperties> devices_" defined in VirtualCLuster's base class Cluster.h. 
- devices_ is initialized during VirtualCluster constructors (https://github.com/tensorflow/tensorflow/blob/575db18083d5437fd7a87ccf3414303498911bb1/tensorflow/core/grappler/clusters/virtual_cluster.cc). 
 in this usage of memory_optimizer, the consturctor used is the 3rd one: https://github.com/tensorflow/tensorflow/blob/575db18083d5437fd7a87ccf3414303498911bb1/tensorflow/core/grappler/clusters/virtual_cluster.cc#L42. 

- Once devices_ is set, calling prop.memory_size() in https://github.com/tensorflow/tensorflow/blob/575db18083d5437fd7a87ccf3414303498911bb1/tensorflow/core/grappler/optimizers/memory_optimizer.cc#L969 return the total gpu memory (because of https://github.com/tensorflow/tensorflow/blob/575db18083d5437fd7a87ccf3414303498911bb1/tensorflow/core/grappler/clusters/utils.cc#L101). It does not care about setting like per_process_gpu_memory_fraction.  
   On the other hand, @allenlavoie suggests that actually another cluster single_machine.cc is overriding the device property's memory_size (https://github.com/tensorflow/tensorflow/blob/fe12159e60258d0b6cae9b580e248b22e80f3f7b/tensorflow/core/grappler/clusters/single_machine.cc#L108) considering about user defined per_process_gpu_memory_fraction. (Though single_machine.cc is initlizing its devices_ in Provision, which is different with VirtualCluster, but I think it's not a big deal.)

So there seems to be 2 solutions:

- Override the memory_size in VirtualCluster's constructor ( I think only the 3rd constructor should be modified, since the first 2 constructor accept DeviceProperties as input, which should be controlled by caller). 
- My current fixing. 

I prefer the 1st one, while still appreciate your comments about this. Thanks a lot!!

**Comment by pengwa** [comment]
@zhangyaobit  I think all GPU will be overwritten, because once per_process_gpu_memory_fraction is set, it  should impact all GPU, right? And single machine is doing this way. https://github.com/tensorflow/tensorflow/blob/fe12159e60258d0b6cae9b580e248b22e80f3f7b/tensorflow/core/grappler/clusters/single_machine.cc#L108 

What do you think? :)

**Comment by zhangyaobit** [comment]
@pengwa This sounds good to me. Thanks.

**Comment by pengwa** [comment]
@zhangyaobit  I reverted previous changes, and merged with latest master. please take a look. :)

**Review by zhangyaobit — APPROVED** [review]
Looks good to me. Thanks.

**Review by allenlavoie — APPROVED** [review]
Awesome!

**Comment by pengwa** [comment]
great!! thanks @allenlavoie  @zhangyaobit !!

**Pull request merged**
