### PR TITLE
add model restore support for tree and forest variables

### PR DESCRIPTION
**Pull request by yupbank**
Right now both tree variables and forest variables only support training.

This pr makes it possible for supporting  restore a tensor forest model from a serialized string

### CODE REVIEW

**Review by nataliaponomareva — COMMENTED** [review]
I have no idea how it relates to inference. What are you trying to do? From what i can see you just rename the variables and add defaults
Adding test might help understand the intended usage

**Comment by yupbank** [comment]
Ah... hey, yeah... Thanks!  Let me add some test cases 
And the intention was to use tensor_forest without train with it. I was using it here https://github.com/yupbank/tree_to_tensorflow

but let me add some test cases for sure

**Comment by yupbank** [comment]
@nataliaponomareva hey, i have added one test case, is that helping ?

**Review by nataliaponomareva — DISMISSED** [review]

**Comment by yupbank** [comment]
@martinwicke  hey do you know what's the status of this?

**Comment by martinwicke** [comment]
There were test failures, but they do look unrelated (clicking through, you'd eventually get to e.g., https://source.cloud.google.com/results/invocations/c80640b0-9ec3-475c-b001-03b96833a3ca/targets/%2F%2Ftensorflow%2Fpython%2Fkernel_tests:init_ops_test/log)

In such a case, you can simply trigger the tests again, or if you're very sure, you can request it be merged anyway (probably not an issue in this case). 

I triggered the tests again, assuming they pass, assign me and I'll merge this.

**Review by nataliaponomareva — APPROVED** [review]

**Comment by yupbank** [comment]
@martinwicke  i think the final failure has nothing to do with this pr...

**Pull request merged**
