### PR TITLE
Support max pooling ops in algorithmic optimizer

### PR DESCRIPTION
**Pull request by lgeiger**
This PR adds support for max pooling operations to the algorithmic optimizer for monotonic functions.

This follows up on #25330
/cc @ezhulenev

### CODE REVIEW

**Review by ezhulenev — DISMISSED** [review]

**Comment by ezhulenev** [comment]
Thanks for the changes!

**Comment by rthadur** [comment]
@lgeiger please rebase your branch.

**Comment by lgeiger** [comment]
> @lgeiger please rebase your branch.

This branch is based on #25330 which was recently reverted. I'm happy to rebase it, though it would be great to get feedback on why #25330 was reverted first.

**Comment by lgeiger** [comment]
Rebased it 🚀

**Pull request merged**
