### PR TITLE
Added return descriptions

### PR DESCRIPTION
**Pull request by kyscg**
Added return descriptions to functions in initializers.py

### CODE REVIEW

**Comment by kyscg** [comment]
Review @rthadur ???

**Review by penpornk — CHANGES_REQUESTED** [review]
Thank you for your PR! The indentation level is a bit off.

**Comment by kyscg** [comment]
Thanks a lot, I should have seen that, I fixed it though. Is it good or should i change anything else? @penpornk

**Review by penpornk — APPROVED** [review]
Looks good now. Thank you for contributing! :)

**Comment by kyscg** [comment]
It's been a while, is anything lacking here @penpornk @rthadur ??

**Comment by penpornk** [comment]
@kyscg I don't think you need to do anything more. The PR just needs to be pulled in.
@rthadur Gentle ping for pulling. Thank you!

**Pull request merged**
