### PR TITLE
[BUG FIX]fix mkl relu6 backward bug.

### PR DESCRIPTION
**Pull request by gyshi**
fix mkl relu6 backward bug and use eltwise_clip_v2 to substitute eltwise_bounded_relu

### CODE REVIEW

**Comment by gbaned** [comment]
@penpornk  Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by ashiqimranintel** [comment]
Any update on this PR?

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Review by penpornk — CHANGES_REQUESTED** [review]
Thank you for the PR and I'm so sorry for the delay! Could you please explain the bug and how the PR fixes it?

**Comment by gzmkl** [comment]
@penpornk  Please help to close this PR which is not valid any more.

**Comment by penpornk** [comment]
Got it. Thank you!

**Pull request closed without merging**
