### PR TITLE
Use external repository for protobuf dependency.

### LINKED ISSUE #1069: Use external repository rather than git submodule for protobuf dependency
Currently, TensorFlow vendors its protobuf dependency using a Git submodule due to the [hack](https://github.com/google/protobuf/blob/master/BUILD#L487) that is required for protobuf Python support.

I have made a change (bazelbuild/bazel#702) to add an [`imports` attribute](http://bazel.io/docs/be/python.html#py_library.imports) to Bazel's Python rules, which allows us to add directories to the `PYTHONPATH` and thus allows us to remove the hack in protobuf.

I have a patch to remove the hack for protobuf Python support (see google/protobuf#1230). I am testing this change using a corresponding change to TensorFlow which removes the git submodule and includes the protobuf dependency using a Bazel external repository instead. Once my patch for google/protobuf#1230 has been submitted, I will send out my corresponding patch to TensorFlow for review.

### PR DESCRIPTION
**Pull request by davidzchen**
Currently, TensorFlow uses a Git submodule for its dependency on
protobuf. This was due to the hack used in protobuf for building Python
support with Bazel, which was required since Bazel's Python rules did
not support adding directories to `PYTHONPATH`. Now that the new
`imports` attribute has been added to the Python rules in Bazel 0.2 and
the hack for Python support in protobuf has been removed, this change
removes the `google/protobuf` Git submodule and adds an external
repository for including protobuf.

Fixes #1069

### CODE REVIEW

**Comment by vrv** [comment]
So this require the entire world to upgrade to bazel 0.2, right?

@tensorflow-jenkins: test this please, but note that this probably will fail if the answer to the above question is "yes", since we haven't updated Jenkins to bazel 0.2 yet.

**Comment by davidzchen** [comment]
FYI The `git_repository` rule I added for including the protobuf repo references the current protobuf HEAD since my patch for removing the Python hack was just merged (see google/protobuf#1233). Is this fine or should we wait until the next protobuf release?

**Comment by davidzchen** [comment]
I see that the Jenkins jobs are failing since the CI machines are running an older version of Bazel, which does not yet contain the `imports` property for Python rules.

**Comment by jendap** [comment]
We are going to upgrade bazel to 0.2 today anyway in https://github.com/tensorflow/tensorflow/pull/1206. We will update mac as well and this will work :)

**Comment by davidzchen** [comment]
I have rebased this patch on HEAD, resolved merge conflicts and made some additional changes since there are now additional targets that use protobuf.

**Comment by vrv** [comment]
@tensorflow-jenkins : test this please

**Comment by vrv** [comment]
Can you bump the version of required bazel https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE#L21 here and then we can re-test?

**Comment by davidzchen** [comment]
Done.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by martinwicke** [comment]
Some target in protobuf is missing a `srcs_version = "PY2AND3"` annotation. See 
http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/262/consoleFull

**Comment by vrv** [comment]
Also looks like build_pip_package needs to be updated.

**Comment by davidzchen** [comment]
@martinwicke There seems to be a few. I'll submit a PR to protobuf to add the missing `srcs_versions`.

@vrv Will do.

**Comment by davidzchen** [comment]
Opened google/protobuf#1402. 

What is the Bazel command run for http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/262/consoleFull? I tried `bazel test //...` but I got an error about the BUILD file for gmock not being found:

```
❯❯❯ bazel test //...
ERROR: /usr/local/google/home/dzc/Projects/tensorflow/tensorflow/tensorflow/workspace.bzl:21:3: no such package '@gmock_archive//': In new_http_archive rule //external:gmock_archive the 'build_file' attribute does not specify an existing file (/usr/local/google/home/dzc/Projects/tensorflow/tensorflow/google/protobuf/gmock.BUILD does not exist) and referenced by '//external:gtest'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.190s
ERROR: Couldn't start the build. Unable to run tests.
```

**Comment by martinwicke** [comment]
The exact command is in the log, but the main point is bazel test
//tensorflow/...

**Comment by martinwicke** [comment]
Can you update the commit hash for protobuf?

@vrv, @keveman: Just to make sure -- this shouldn't interact with our binary protobuf distribution, right?

**Comment by davidzchen** [comment]
I have updated the commit hash in `tensorflow/workspace.bzl`. I'm still debugging some build and test failures that I found when running `bazel test //tensorflow/...` on my Goobuntu machine (see below), but let's also run the CI to see if there is anything else that needs to be fixed.

```
❯❯❯ bazel test //tensorflow/...
WARNING: /usr/local/google/home/dzc/Projects/tensorflow/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future
INFO: Found 709 targets and 418 test targets...
INFO: From Compiling external/protobuf/src/google/protobuf/compiler/js/js_generator.cc [for host]:
external/protobuf/src/google/protobuf/compiler/js/js_generator.cc: In function 'std::string google::protobuf::compiler::js::{anonymous}::JSByteGetterSuffix(google::protobuf::compiler::js::{anonymous}::BytesMode)':
external/protobuf/src/google/protobuf/compiler/js/js_generator.cc:492:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^

ERROR: /usr/local/google/home/dzc/.cache/bazel/_bazel_dzc/97010c3bd7554ebe07410261582c4d5e/external/protobuf/BUILD:581:1: C++ compilation of rule '@protobuf//:pyext/_message.so' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,no
w -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote ... (remaining 48 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
In file included from external/protobuf/python/google/protobuf/pyext/extension_dict.cc:34:0:
external/protobuf/python/google/protobuf/pyext/extension_dict.h:51:7: error: expected nested-name-specifier before 'shared_ptr'
 using shared_ptr;
       ^
external/protobuf/python/google/protobuf/pyext/extension_dict.h:51:7: error: 'shared_ptr' has not been declared
external/protobuf/python/google/protobuf/pyext/extension_dict.h:67:3: error: 'shared_ptr' does not name a type
   shared_ptr<Message> owner;
   ^
In file included from external/protobuf/python/google/protobuf/pyext/extension_dict.cc:43:0:
external/protobuf/python/google/protobuf/pyext/message.h:56:7: error: expected nested-name-specifier before 'shared_ptr'
 using shared_ptr;
       ^
external/protobuf/python/google/protobuf/pyext/message.h:56:7: error: 'shared_ptr' not declared
external/protobuf/python/google/protobuf/pyext/message.h:57:12: error: 'std::std' has not been declared
 using std::std::string;
            ^
In file included from external/protobuf/python/google/protobuf/pyext/extension_dict.cc:44:0:
external/protobuf/python/google/protobuf/pyext/repeated_composite_container.h:53:7: error: expected nested-name-specifier before 'shared_ptr'
 using shared_ptr;
       ^
external/protobuf/python/google/protobuf/pyext/repeated_composite_container.h:53:7: error: 'shared_ptr' not declared
In file included from external/protobuf/python/google/protobuf/pyext/extension_dict.cc:45:0:
external/protobuf/python/google/protobuf/pyext/repeated_scalar_container.h:52:7: error: expected nested-name-specifier before 'shared_ptr'
 using shared_ptr;
       ^
external/protobuf/python/google/protobuf/pyext/repeated_scalar_container.h:52:7: error: 'shared_ptr' not declared
external/protobuf/python/google/protobuf/pyext/extension_dict.cc: In function 'google::protobuf::python::ExtensionDict* google::protobuf::python::extension_dict::NewExtensionDict(google::protobuf::python::CMessage*)':
external/protobuf/python/google/protobuf/pyext/extension_dict.cc:251:9: error: 'google::protobuf::python::ExtensionDict' has no member named 'owner'
   self->owner = parent->owner;
         ^
external/protobuf/python/google/protobuf/pyext/extension_dict.cc: In function 'void google::protobuf::python::extension_dict::dealloc(google::protobuf::python::ExtensionDict*)':
external/protobuf/python/google/protobuf/pyext/extension_dict.cc:258:9: error: 'google::protobuf::python::ExtensionDict' has no member named 'owner'
   self->owner.reset();
         ^

INFO: Elapsed time: 44.875s, Critical Path: 33.67s
FAIL: //tensorflow/contrib/ctc:ctc_decoder_ops_test
FAIL: //tensorflow/contrib/ctc:ctc_loss_op_test
FAIL: //tensorflow/contrib/distributions:gaussian_conjugate_posteriors_test

~~~ snipped ~~~
```

**Comment by vrv** [comment]
@tensorflow-jenkins test this please  (to see what's broken)

**Comment by martinwicke** [comment]
master tests are failing right now, so don't expect a clean build.

**Comment by martinwicke** [comment]
or not. Never mind.

**Comment by petewarden** [comment]
Jenkins, test this please.

**Comment by vincentvanhoucke** [comment]
@tensorflow-jenkins test this please

**Comment by davidzchen** [comment]
FYI google/protobuf#1586 should be merged soon. Once that PR is merged, I'll update this PR to point the git commit to the new protobuf HEAD and rebase again.

**Comment by vrv** [comment]
ready to test?

**Comment by davidzchen** [comment]
Yes just rebased, updated, and pushed.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
that failed quickly: ERROR: /workspace/tensorflow/workspace.bzl:84:3: no such package '@gmock_archive//': In new_http_archive rule //external:gmock_archive the 'build_file' attribute does not specify an existing file (/workspace/@protobuf/:gmock.BUILD does not exist) and referenced by '//external:gtest'.

**Comment by davidzchen** [comment]
Odd. Looking

**Comment by davidzchen** [comment]
Seems that this is caused by a bug in this version of Bazel that is fixed in a later version. In any case, it is probably better to have `gmock.BUILD` live in the tensorflow repo for now, similar to those for other dependencies, until we eventually upgrade to a version of gmock/gtest that has its own BUILD file.

Can you start the tests again?

**Comment by vrv** [comment]
test this please

**Comment by vrv** [comment]
Almost, looks like the pip install doesn't work

Python binary path to be used in PIP install: /usr/bin/python (Major.Minor version: 2.7)
Thu May 26 05:26:43 UTC 2016 : === Using tmpdir: /tmp/tmp.PJlk9Vtu7r
rsync: link_stat "/workspace/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/google" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
build_pip_package FAILED

**Comment by davidzchen** [comment]
I'll take a look. Is the command that the script used to invoke `build_pip_package` something along the lines of `bazel run //tensorflow/tools/pip_package:build_pip_package -- /path/to/destination_dir`?

**Comment by vrv** [comment]
Yeah see the section called Create the pip package and install on https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html

**Comment by davidzchen** [comment]
Should be fixed now.

@tensorflow-jenkins test this please

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by davidzchen** [comment]
Looks like all the tests passed this time, though on the GitHub UI, the MacOS CPU Tests is still marked as BUILDING even though it has succeeded on Jenkins. Could it be related to this message?

```
Executed 492 out of 492 tests: 492 tests pass.

Parameterized build ends with SUCCESS at: Thu May 26 16:40:30 UTC 2016 (Elapsed time: 1249 s)
Unable to get pull request builder trigger!!    <~~~~~
Setting status of 278cc4698b757c63edb8248aa051218435cf6415 to SUCCESS with url http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/552/ and message: 'SUCCESS
 '
Using context: Linux CPU Tests (Python 3)
Finished: SUCCESS
```

**Comment by vrv** [comment]
Sweet, this is awesome.  @martinwicke @caisq okay to merge?  (I'll have to do some work internally to bring this change in, but I'll sign up for that this week).

**Comment by davidzchen** [comment]
\o/

**Comment by martinwicke** [comment]
Woot

**Comment by petewarden** [comment]
Yay!

**Comment by StephenOman** [comment]
I understand that Bazel is the preferred build tool for TensorFlow. However, it's worth noting that this change has some consequences for developers woking with alternative build tools:

1. Since the git --recursive option is no longer going to clone Protobuf too, it will have to be cloned manually to get access to the required header files. The documentation needs to be updated to reflect that.

2. The exact commit version of Protobuf to clone is buried in tensorflow/workspace.bzl rather than in the handy google/protobuf link. This is a pity as having it the original way means letting git worry about checking out the right version. The way it is configured now, future changes to the Protobuf version will need to be updated in several different build instruction files.

3. As the google/protobuf path no longer exists, any Include Path directives will have to be modified to point to the new local Protobuf clone location. This is also a shame as having a standard folder google/protobuf in the workspace meant configuring the Include Path once in the build file and then forgetting about it. Now there'll be an extra step for each new developer to change it to point to his/her own Protobuf location.

I'd also add a more general request. This kind of change to the repo structure should have a minor release number with some release notes. It took me a good while to figure out why all the Protobuf headers had disappeared from my build environment after I merged in the latest tensorflow:master changes. I thought I had deleted them somehow and went around in circles before finding this PR.

**Comment by jendap** [comment]
We are sorry for the inconvenience @StephenOman!

It is much better to download git repos using bazel. Also for all the builds there is a lot of them, not just protobuf.

What build tool are you using? We have also have (incomplete):
1) [contrib/cmake](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake) - it may not work today but could be made work with some effort
2) [contrib/makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile) - this one is super new. It is there to build the ios example. We will create CI build for it next week.

Please take a look at those two. Please contribute if one of them would suite you. Once we get them into reasonable state we can enable builds for them in ci.tensorflow.org. That way we make sure no change break that. No more breakage for you :)

**Comment by StephenOman** [comment]
Thanks for the note @jendap.

I'm wrapping the current C++ API with an Objective C++ interface in order to build a Swift-based iOS app. Complicated, I know! To do this, I'd created a set of Xcode projects to build both Protobuf and TensorFlow libs and am managing the build from there.

**Comment by jendap** [comment]
Take a look at [contrib/makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile). We have added it exactly for this reason. It will be recommended way of working in xcode. We will soon have automated build this so it should work in future. But it is very new (may be even broken right now).

**Comment by StephenOman** [comment]
Right, I see where you are going with this. Thanks.

**Pull request merged**
