### PR TITLE
update Android libs

### PR DESCRIPTION
**Pull request by hannesa2**
For android sample:
- improve .gitignore
- upgrade build tools to current most recent stable 3.0.1
- add corresponding gradle

### CODE REVIEW

**Comment by apik420** [comment]
15055

**Review by andrewharp — APPROVED** [review]

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Some kind of infra failure.

Jenkins, test this please.

**Comment by drpngx** [comment]
Failed to git pull :(

Jenkins, test this please.

**Comment by hannesa2** [comment]
Jenkins, test this please.

**Comment by hannesa2** [comment]
Can I do here something ?

**Comment by drpngx** [comment]
No, sorry, we're working on another breakage, we'll get back to regular issues soon.

Jenkins, test this please.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
