### PR TITLE
Branch 136382518

### PR DESCRIPTION
**Pull request by drpngx**

### CODE REVIEW

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by caisq** [comment]
So all jobs except the Windows cmake one passed. The timeout seen in the previous GPU run looks like a flaky timeout. @gunan , any idea about the Windows cmake failure? It appears that the compilation passes, and the network dropped (deterministically?) in the last step.

**Comment by drpngx** [comment]
http://ci.tensorflow.org/job/tensorflow-pull-requests-multijob/2203/ appears to have also passed and reported successfully. I'm waiting for the queue to clear up a little bit to start another build.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Sync'd and rebased, now at #5028.

**Pull request closed without merging**
