### PR TITLE
Fix #27994: compat.as_bytes should support bytearray

### LINKED ISSUE #27994: compat.as_bytes should support bytearray
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently, `tensorflow.python.util.compat.as_bytes` accepts `bytes` but not `bytearray`. This causes issues when trying to write a `bytearray` to `GFile`, which internally calls `compat.as_bytes`.

`compat.as_bytes` should support `bytearray` to improve usability.

**Will this change the current api? How?** This change is backward-compatible.

**Who will benefit with this feature?** Supporting `bytearray` in `compat.as_bytes` helps in use cases where a `GFile` file handle is wrapped in some other class, such as a fastavro `Writer` which writes out `bytearray` to the file handle.

**Any Other info.**

### PR DESCRIPTION
**Pull request by erwa**
I made these changes manually in a local venv and was then able to write to a GFile handle from a fastavro Writer, which writes out `bytearray`s.

### CODE REVIEW

**Comment by rthadur** [comment]
@erwa please sign CLA

**Comment by erwa** [comment]
I'm speaking with my legal team and just need to figure out a few details before signing the CLA. Hope to get back to you later this week.

**Comment by erwa** [comment]
@googlebot I signed it!

**Comment by erwa** [comment]
@rthadur , I've signed the CLA. Could you help review the patch?

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by erwa** [comment]
Thanks for the review, @mihaimaruseac. I took a look at some of the failed CI builds and the failures look unrelated. Can you merge this PR?

**Comment by mihaimaruseac** [comment]
There's some infrastructure changes going on at the moment. Will merge when resolved.

**Comment by erwa** [comment]
Thanks, Mihai.

**Comment by mihaimaruseac** [comment]
Can you solve conflict?

**Comment by erwa** [comment]
Rebased on `master` and resolved conflicts.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
