### PR TITLE
fixing go get and var name

### PR DESCRIPTION
**Pull request by barnjamin**
go get complained about the github.com path, splitting them out fixes it

### CODE REVIEW

**Comment by barnjamin** [comment]
I've signed the CLA

**Review by asimshankar — APPROVED** [review]
Thanks for making this fix, much appreciated.

I see the missing $ as a clear mistake.
Regarding separating out the "go get' into two lines, out of curiosity - which OS/shell were you using? (This syntax seems to work in some. Your fix is better regardless, just curious)

**Comment by asimshankar** [comment]
Mr Jenkins, test this please

**Comment by barnjamin** [comment]
Just using Bash on Ubuntu 16.04
``` 
ben@thor:~/go/src/github.com/tensorflow/tensorflow/tensorflow/go$ echo $0
bash
ben@thor:~/go/src/github.com/tensorflow/tensorflow/tensorflow/go$ go generate github.com/tensorflow/tensorflow/tensorflow/go/op
package github.com/golang/protobuf/{proto,protoc-gen-go}: invalid github.com/ import path "github.com/golang/protobuf/{proto,protoc-gen-go}"
../genop/main.go:15: running "sh": exit status 1
op/generate.go:15: running "go": exit status 1
ben@thor:~/go/src/github.com/tensorflow/tensorflow/tensorflow/go$ go version
go version go1.7.1 linux/amd64
````

**Pull request merged**
