### PR TITLE
Use fast IDCT for JPEG decoding by default

### PR DESCRIPTION
**Pull request by mkolod**
Please refer to issue #4833 for details.

### CODE REVIEW

**Comment by TimZaman** [comment]
Weird potential reviewers given by the bot. A human (#4833) suggested @prb12 and @poxvoculi..

**Comment by mkolod** [comment]
BTW I'm from Nvidia (the org membership is part of my profile) and Nvidia has a corporate CLA. If you need me to do anything else (e.g. file a personal CLA as well) to keep the bots happy, please let me know. :)

**Comment by drpngx** [comment]
@keveman Not sure what the implications are. It looks like we disabled this intentionally.

**Comment by mkolod** [comment]
@drpngx @keveman For the record, Caffe and other frameworks use the default (i.e. fast) IDCT. With compressed JPEGs, the slow IDCT is very unlikely to give any accuracy gains, and slows down processing dramatically, especially when the CPU is the bottleneck for another component in the system that has much higher throughput, e.g. a GPU.

**Comment by mkolod** [comment]
Here's a screenshot for ResNet-50, batch size 64, of convergence with default optimizer, learning rate, etc. I'm not sure if I can get full determinism even with the fixed seed, but in any case, the convergence seems similar after a bunch of iterations even if there's some early noisiness. Again, since the other frameworks use the fast IDCT, I'd think that it's rather innocuous. 
fast_vs_slow

**Comment by mkolod** [comment]
I tried convergence on ResNet-50 and I don't see whether one is markedly better than the other. This was with the data loading queue and preprocessing queue all set to 1 thread, and using fixed initialization seeds, so this is as much determinism as I could imagine having control over. I'd imagine the Inception results would be very similar, and if anything, smaller nets like AlexNet would be even less sensitive to decoding issues.

fast_vs_slow

**Comment by mkolod** [comment]
@drpngx @keveman Note that for e.g. AlexNet, the speed-up due to this small change is about 30% on a GTX 1080 and a Core i7-5930K, running off of a 500 MB/s SSD. That's a pretty significant speed-up. For multi-GPU cases, this will be even more important since then the bottleneck will be the CPU component even more so than in the single-GPU case. Also, it may matter even more on say ARM than on x86, including for the JPEG-based inference speeds.

**Comment by drpngx** [comment]
I don't know about the implications of making that modification in all of users. My intuition would usually be to provide a flag, and consider flipping the default to new behavior.

@keveman any comment on the analysis provided?

**Comment by mkolod** [comment]
Also, see [here](https://github.com/tensorflow/tensorflow/issues/4807#issuecomment-256718844) for perf impact. The importance of fast IDCT varies by image size, and of course its impact on training depends on how compute-heavy the model is (less impact for Inception, more for AlexNet).

**Comment by keveman** [comment]
@tensorflow-jenkins test this please.

**Review by keveman — COMMENTED** [review]
Seems good. Will merge after testing.

**Comment by TimZaman** [comment]
Fails due to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_test.py#L1806
Which error `AssertionError: 0.64828776041666669 not less than 0.6`
Barely overshoots the threshold - bearing in mind the range is [0:255]. I bet the magical thershold value of 0.6 is set because the non-IDCT gets something just below 0.6.

**Comment by mkolod** [comment]
@TimZaman Updated to 0.7. I agree that the assertion's tolerance was based on what the slow IDCT would typically get. The fast IDCT's result is barely different, and that is to be expected due to algo difference, but isn't different for practical purposes.

**Comment by keveman** [comment]
@tensorflow-jenkins test this please

**Comment by keveman** [comment]
@mkolod Can you please take a look at the failures?

**Comment by drpngx** [comment]
It looks like they all fail on jpeg unit test, and mac additionally fails on env test

@gunan @caisq not sure if we bazel rc with test output on failure on macs

**Comment by mkolod** [comment]
@keveman @drpngx I looked at the test and my findings are as follows. There isn't any bug in libjpeg, but, I would argue, the tolerance on the JPEG fixed point test (encode/decode/encode several times and see if there is stability in that the diffs go to zero) is pretty tight. For the first encode-decode, the diff is about 0.55 out of 255, but with the slow IDCT, the diff goes to 0.02 or so on the second encode/decode pass. The fast IDCT does generate more error, this is a known thing. The error is actually basically the same on the first pass in fast and slow IDCT, but the difference is that slow IDCT is more stable on the second decode and re-encode. I'd argue that since TensorFlow is not an image editing platform but a machine learning platform, it would be a real corner case if someone ended up decoding and re-encoding the same image dozens of times over (also in that case, why not use a lossless format?). If there is say one decoding and re-encoding (e.g. due to the need to preprocess an existing dataset offline for more optimized use later, e.g. pre-resizing ImageNet), that would be a single such pass, not counting the final decoding at learning time. So, while the fixed point test would matter a lot for image editing, I don't think it's that important for machine learning applications. If so, I can update the test case and re-submit. However, whether that is OK is of course up to you. Please let me what you think.

**Comment by drpngx** [comment]
Sorry, I had lost context. Yes, we should bump up the epsilons in the tests to make them all pass.

**Comment by mkolod** [comment]
@drpngx Will do, thanks!

**Comment by mkolod** [comment]
@drpngx @keveman Should be fine for re-running tests now, I ran 
bazel test //tensorflow/python/...
locally on Linux and everything seemed fine.

**Comment by mkolod** [comment]
@drpngx @keveman Should be fine for re-running tests now, I ran 
bazel test //tensorflow/python/...
locally on Linux and everything seemed fine. Could you re-run the CI pipeline?

**Comment by keveman** [comment]
@tensorflow-jenkins test this please.

**Comment by mkolod** [comment]
@keveman Apologies, looks like the Python tests pass but the C++ tests still fail. I thought all the testing of the transforms was in Python, hence I ran only the Python test suite. Will re-run all the tests including C++ ones.

**Comment by mkolod** [comment]
@keveman I re-ran all the tests now (Python and C++) using 
```bazel test //tensorflow/...```
and I don't see anything failing in the mainline code on my Linux box.

**Comment by vrv** [comment]
Okay let's kick off another test to find out!

@tensorflow-jenkins test this please

**Review by vrv — APPROVED** [review]
I heartily approve of this PR.

**Comment by vrv** [comment]
Okay, sadly I have to roll this change back -- it looks like some of our groups internally might rely on having higher quality decoding.  Let's re-make this change possibly via an option to DecodeJpegOp, rather than flipping the default everywhere.

**Comment by vrv** [comment]
@mkolod: are you still working on getting this change back in again via the configurable option?  If not, would you like us to do it instead?

**Comment by prb12** [comment]
> Let's re-make this change possibly via an option to DecodeJpegOp, rather than flipping the default everywhere.

+1   This should obviously be the default, but retaining the option for slow high quality is a good thing.
BTW, this op contributes significantly to multi-GPU inception training being bottlenecked on host CPU.

**Comment by vrv** [comment]
Yes, we'll first add the option, then we can try to quickly find those that depend on the slow path for accuracy (not many, but there are some), and then we can switch the default after converting them to explicitly depend on the slow option.

**Pull request merged**
