### PR TITLE
Fix ProfileContext location in README

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Comment by panyx0718** [comment]
Are you sure you can call it like: tf.python.profiler.profile_context.ProfileContext?
I only expose it via contrib on purpose.

**Comment by bryant1410** [comment]
> Are you sure you can call it like: tf.python.profiler.profile_context.ProfileContext?
> I only expose it via contrib on purpose.

Yeah, after 2b51e0ba27af69c914a7523d9aae232de09e3206 it's accessible that way, I have tested it. Furthermore, the README way like it is now doesn't work.

By looking at af23ae65db2585f4a18d0bc5f21f15e94805aa4f, it seems to be migrated to core.

**Comment by panyx0718** [comment]
@bryant1410 
I just build from source and install the latest package

Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.contrib.tfprof.ProfileContext
<class 'tensorflow.python.profiler.profile_context.ProfileContext'>
>>> tf.python.profiler.profile_context.ProfileContext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'python'

**Comment by drpngx** [comment]
@bryant1410 please fix, pull rebase and push again. Thanks!

**Comment by sb2nov** [comment]
@bryant1410 ping

**Comment by gunan** [comment]
I have just confirmed that the original readme is correct.
Maybe we had a bad release which you saw the issue?
Or is it possible maybe on windows our API is messed up somehow?
```
>>> tf.python.profiler.profile_context.ProfileContext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'python'
>>> tf.contrib.tfprof.ProfileContext
<class 'tensorflow.python.profiler.profile_context.ProfileContext'>
>>> tf.__version__
'1.4.0'
```

Therefore, I will close this PR. Thank you very much for the proposed fix, and if you can find the root cause of the issue, I am happy to work with you to fix the issue on our end.

**Pull request closed without merging**
