### PR TITLE
Merge pull request #43269 from rhdong:Mutablehashtable lookup support…

### PR DESCRIPTION
**Pull request by rhdong**
This PR has been merged to master: https://github.com/tensorflow/tensorflow/pull/43269
This PR is one part of [RFC#313](https://github.com/tensorflow/community/pull/313), [RFC#237](https://github.com/tensorflow/community/pull/237)

### CODE REVIEW

**Comment by rhdong** [comment]
@yuefengz Please help review, thank you~

**Comment by byronyi** [comment]
In general I don't think the TF team accept feature cherry-picks into release branches, but it might worth to check again.

**Comment by rhdong** [comment]
> In general I don't think the TF team accept feature cherry-picks into release branches, but it might worth to check again.

Thank you for your prompt, maybe I miss the best time, if I had to wait for the r2.5 release?  I think it will take too long time...

**Comment by mihaimaruseac** [comment]
Unfortunately 2.4 has been released already.

**Pull request merged**
