### PR TITLE
rnn_cell.py: Allow user to explicitly set forget bias in LSTMCell

### PR DESCRIPTION
**Pull request by Mistobaan**

### CODE REVIEW

**Comment by ebrevdo** [comment]
LGTM

**Comment by vrv** [comment]
I think it would be good to have a test for this -- right now if we removed it, no tests would fail.

**Comment by Mistobaan** [comment]
@vrv Added the option to the existing test, seemed useless to add a complete new test just for that option

**Comment by ebrevdo** [comment]
Would this test fail if the dtype of the cell is float64?

**Comment by vrv** [comment]
Closing due to lack of activity.

**Comment by Mistobaan** [comment]
@vrv I think it just need to be tested by Jenkins and then is good to go. what is missing ?

**Comment by vrv** [comment]
An answer to https://github.com/tensorflow/tensorflow/pull/767#issuecomment-172597373 :)

**Comment by Mistobaan** [comment]
@ebrevdo I don't think it would fail. I guess you are referring to the 1.0. I think it will be casted to the right type in the `f + self._forget_bias`. How would you create a test with a cell with dtype=float64 ?

**Comment by lukaszkaiser** [comment]
This change looks good to me, I think it will work as said. Can we test it and get it in?

**Comment by vrv** [comment]
Ok, well then let's address the conflict / squash, then we'll test and merge.

**Comment by Mistobaan** [comment]
rebased

**Comment by TimelyToga** [comment]
Hmm, so not saying this change isn't helpful, but doesn't [Jozefowicz 2016](http://jmlr.org/proceedings/papers/v37/jozefowicz15.pdf) suggest that you would never really want to have a forget bias initialized to anything other than 1.0 as it outperforms all other LSTMs? Would there ever be a foreseeable instance where you would not want to have that be the case?

**Comment by vrv** [comment]
@rafaljozefowicz

**Comment by lukaszkaiser** [comment]
> Would there ever be a foreseeable instance where you would not want to have that be the case?

I think 1.0 is the best default value for a variety of tasks. But it's hard to be sure that there is no better starting bias on some particular task. And some people want to faithfully replicate previous work that used bias=0. So it's definitely good to have this option!

**Comment by vrv** [comment]
Okay, rebase / address the conflict and we'll test / merge.

**Comment by TimelyToga** [comment]
:cool: Thanks!

**Comment by Mistobaan** [comment]
@vrv rebased.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Pull request merged**
