### PR TITLE
Issue #25802 Updating API docs of tf.math.acos

### PR DESCRIPTION
**Pull request by HarshSulakhe**
#25802

### CODE REVIEW

**Comment by HarshSulakhe** [comment]
Okay, will keep that in mind next time. Thanks

**Comment by gbaned** [comment]
ping @mihaimaruseac for review ? Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
@HarshSulakhe  Could you please check failed build errors? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
