### PR TITLE
Adam: Fix latex text (docs).

### PR DESCRIPTION
**Pull request by sbrodehl**
Escape special character and add text section for comments.

### CODE REVIEW

**Comment by sbrodehl** [comment]
Looks like #18168 messed up the formula a bit.

**Comment by sbrodehl** [comment]
Fixed sqrt in lr formula, and updated various files with adam docs.

**Comment by sbrodehl** [comment]
Should the variable names correspond to the ones used in the API?
E.g. `beta_1`should be `beta1`?

**Review by ctrlaltvikas — APPROVED** [review]

**Comment by sbrodehl** [comment]
@MarkDaoust , @martinwicke care to review/merge?

**Comment by sbrodehl** [comment]
Thanks @MarkDaoust !

**Pull request merged**
