### PR TITLE
Added uint8 registration for addition operation (Fixes #10447)

### LINKED ISSUE #10447: Tensorflow Errors with uint8 addition
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
8.0
- **GPU model and memory**:
Nvidia Titan X Pascal 
- **Exact command to reproduce**:
```
import tensorflow as tf
a=tf.constant([1],dtype=tf.uint8)
b=tf.constant([2],dtype=tf.uint8)
c=a+b
session=tf.Session()
with session.as_default():
    session.run(c)
```
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

It appears as thought uint8 addition is not supported.  This is odd.  When running the above code I get the error:

```
InvalidArgumentError: No OpKernel was registered to support Op 'Add' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='CPU'; T in [DT_STRING]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]

	 [[Node: add = Add[T=DT_UINT8](Const, Const_1)]]

```

### PR DESCRIPTION
**Pull request by lakshayg**

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by lakshayg** [comment]
The failures in tests/build seem unrelated to the changes made by this pull request

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by lakshayg** [comment]
I suspect that there is a bug in `tensorflow/python/kernel_tests/sparse_reshape_op_test.py`. This test seems to fail almost always even when the changes are completely unrelated.

**Comment by martinwicke** [comment]
I agree. It's unrelated.

**Pull request merged**
