### PR TITLE
Added missing case for osx

### PR DESCRIPTION
**Pull request by fwinnen**
Small patch for #10060

### CODE REVIEW

**Comment by fwinnen** [comment]
I signed it!

**Comment by fwinnen** [comment]
Email was missing in github, added it. Does it need to be the primary email?

**Comment by maciekcc** [comment]
Jenkins test this please.

**Review by maciekcc — APPROVED** [review]

**Comment by maciekcc** [comment]
Jenkins test this please.

**Comment by maciekcc** [comment]
Jenkins test this please.

**Pull request merged**
