### PR TITLE
Separate constant file for global variables

### PR DESCRIPTION
**Pull request by rajendraarora16**
Created a separate common `constants.py` which can be used globally under `ops.`

**P.S:** I created the same pull request [#16401](https://github.com/tensorflow/tensorflow/pull/16401) as after pushing my latest changes I was facing CLA issues.

### CODE REVIEW

**Comment by rajendraarora16** [comment]
I am facing CLA issues with this pull request since closing it.

**Comment by rajendraarora16** [comment]
@rmlarsen I am struggling with CLA issues, please help me. My CI build was failing since pushed new changes after figuring out issues.

**Comment by rmlarsen** [comment]
As the message says, some of the commits had a different author than the email you used to sign the CLA. Can you perhaps prepare a fresh PR where this is not the case?

**Comment by rajendraarora16** [comment]
Closing this PR, I am facing CLA issues.

**Pull request closed without merging**
