### PR TITLE
Add default settings for cloud tpu client to support AI Platform

### PR DESCRIPTION
**Pull request by pshiko**
- Changed to refer to the value of `TPU_CONFIG` when no argument is passed to TPU Client.
- Add unit tests in the above case.

---
When using `TPU` with `AI Platform`, it is necessary to get the TPU information from the environment variable `TPU_CONFIG`.

Ref: https://cloud.google.com/ai-platform/training/docs/using-tpus#wait-for-tpu-provisioning

These settings aren't interesting and should work with the default settings, just like any other environment like `kubernetes` or `colabolatory`.

NOTE:
I understand that Google recommends `Vertex AI` and `CloudTPU VM` over `AI Platform`, but it seems that the use of `AI Platform` will continue for a while due to insufficient support for scheduled jobs that specify `TPU`.

### CODE REVIEW

**Comment by pshiko** [comment]
If you have any additional information you need, please contact me! 👍 
@michaelbanfield

**Comment by pshiko** [comment]
@michaelbanfield CC: @gbaned Any update?

**Comment by pshiko** [comment]
@allenwang28 @michaelbanfield ping😿

**Comment by gbaned** [comment]
@allenwang28, @michaelbanfield Can you please review this PR ? Thanks!

**Review by allenwang28 — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by pshiko** [comment]
When I merged the latest master again and pushed it, it is error with lint.
The parts pointed out in this lint are different from my changes, should I fix them?

**Comment by pshiko** [comment]
What is said in this PR seems to be relevant.
https://github.com/tensorflow/tensorflow/pull/55453
https://github.com/tensorflow/tensorflow/issues/55442

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
@pshiko Can you please fix build failures ? Thanks!

**Comment by pshiko** [comment]
@gbaned 
Could you do `force run`?
Perhaps [this PR](https://github.com/tensorflow/tensorflow/pull/55464) solved the pylint error.

**Comment by gbaned** [comment]
@pshiko Still, PyLint errors are appearing, any update on this, please. Thank you!

**Comment by pshiko** [comment]
sorry! I merged the master branch and passed the `pylint` step.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
