### PR TITLE
fix scaler transform in boston skflow example

### PR DESCRIPTION
**Pull request by mheilman**
fit_transform was being used instead of transform for the test set in the boston example

### CODE REVIEW

**Comment by mheilman** [comment]
My company (Civis Analytics) signed the CLA a while back.

**Comment by poxvoculi** [comment]
@ilblackdragon Should transform or fit_transform be preferred here?

**Comment by vrv** [comment]
@willnorris if users sign the corp CLA, is there any way to get the label to be set to yes?

**Comment by willnorris** [comment]
The commit in this PR shows `mheilman@users.noreply.github.com` as the commit author.  You would need to use the email address that is associated with the corporate CLA in order to be recognized (presumably an `@civisanalytics.com` email?)

**Comment by ilblackdragon** [comment]
@poxvoculi transform should be used usually - as in serving you don't actually know what would be mean / std.dev of the distribution.

**Comment by ilblackdragon** [comment]
@tensorflow-jenkins test this please.

**Comment by mheilman** [comment]
Gah, sorry, I forgot that GH would use that generated email address since I just made a simple fix in the in-browser interface.  The email is correct now.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
