### PR TITLE
fix the bug that InMemoryEvaluatorHook prints in every iter

### PR DESCRIPTION
**Pull request by matthew-z**
For issue #20622

### CODE REVIEW

**Review by ispirmustafa — CHANGES_REQUESTED** [review]
Thanks for contribution!
I don't think this one is fixes the issue. 
could you please write a unit test to verify?

**Comment by matthew-z** [comment]
Sure, I will try to write a unit test. 

Currently, I can confirm that the logger can print evaluation result with a correct freq with my code after changing the code. The problem is that the original code cannot reach`self._timer.update_last_triggered_step(self._iter_count)` as it is after `return`

**Review by ispirmustafa — APPROVED** [review]
Right! what was I thinking?
no need for more changes

**Comment by jperl** [comment]
I didn't see this before I made the PR. But here is a fix w/ test. https://github.com/tensorflow/tensorflow/pull/20822

**Comment by martinwicke** [comment]
Can this be closed given #20822 is merged?

**Pull request closed without merging**
