### PR TITLE
Minor bugfix in DynamicAttentionWrapper; improve docs

### PR DESCRIPTION
**Pull request by critiqjo**

### CODE REVIEW

**Comment by lukaszkaiser** [comment]
Sorry, I'm not too familiar with this new code, un-assigning myself. Maybe Thang?

**Comment by ebrevdo** [comment]
LGTM thank you for the fix!

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Review by martinwicke — APPROVED** [review]
@ebrevdo says it's good, so it's good.

**Pull request merged**
