### PR TITLE
Update our version of protocol buffers. Use a new numpy and pandas in Jenkins.

### PR DESCRIPTION
**Pull request by jhseu**

### CODE REVIEW

**Comment by gunan** [comment]
Looks like at least the android breakage above is related.
Could you take a look?

**Comment by jhseu** [comment]
(Hold off on reviewing/merging. Failures look genuine. Will investigate a bit later.)

**Comment by jhseu** [comment]
@gunan PTAL. Turns out the pypi numpy causes subtle bugs with Ubuntu 14.04. pip install compiles from source.

**Comment by jhseu** [comment]
Was testing upgrading numpy and pandas as part of this. Left them upgraded because they fix several unrelated issues.

**Comment by jhseu** [comment]
Also upgraded to a protocol buffer version past 3.2.0 to support https://github.com/tensorflow/tensorflow/pull/7165. Only needed in bazel rules and not as a runtime dep.

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
All test are happy, so I am happy.
Should we document which bugs numpy and pandas upgrades resolve?

**Pull request merged**
