### PR TITLE
Dynamic ksize and strides with MaxPool

### LINKED ISSUE #4746: ksize in max_pool
I am trying to build a convolution (followed by max_pool) for variable length input size. Since the length of the input in a batch should be the same, I set the batch size to 1. However, for some reason ksize in tf.nn.max_pool is a list attribute required at run-time. This would prevent any neural network that uses variable input size to apply max pool. Is there a workaround for this? Should ksize be an input tensor otherwise?

### PR DESCRIPTION
**Pull request by yongtang**
This fix is the renewed effort to fix #4746 with Jenkins failures fixed. (the previous PR was #9514).

This fix tries to fix the issue raised in #4746 where ksize and strides is static (attr) with max_pool (and avg_pool).

This fix changes ksize and strides to input tensor with MaxPoolV2 so that it is dynamic now. 

This fix add MaxPoolV2 but hasn't points `nn_ops.max_pool` to `gen_nn_ops.max_pool_v2` yet. It tries to following the same api workflow as PR #10840 (3 weeks before API changes).

This fix fixes #4746.

### CODE REVIEW

**Review by rmlarsen — CHANGES_REQUESTED** [review]
One nit:

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by yongtang** [comment]
Thanks @rmlarsen for the review. The PR has been updated. Please take a look.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@yongtang It looks like you still have to squash a bug for the GPU test:

======================================================================
ERROR: testKernelSmallerThanStrideSame (__main__.PoolingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/pooling_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/pooling_ops_test.py", line 626, in testKernelSmallerThanStrideSame
    v2=v2)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/pooling_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/pooling_ops_test.py", line 172, in _VerifyValues
    data_format, expected, use_gpu, v2)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/pooling_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/pooling_ops_test.py", line 149, in _VerifyOneTest
    data_format, dtypes.float32, expected, use_gpu, v2)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/pooling_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/pooling_ops_test.py", line 124, in _VerifyOneType
    t = test_util.NCHWToNHWC(t)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/pooling_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 224, in NCHWToNHWC
    return array_ops.transpose(input_tensor, new_axes[ndims])
KeyError: None

**Comment by yongtang** [comment]
Thanks @rmlarsen. I forgot to enable `MaxPoolV2` in GPU. The PR has been updated now.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@martinwicke does this require API review? Should we follow the same route as non_max_suppression and hide the kernels and add a Python wrapper?

**Comment by martinwicke** [comment]
Yes, MaxPoolV2 should be hidden. 

The automatically generated python doesn't seem to be exposed to the API, so it appears everything is in order. I suspect that in order to expose it it needs to be added to _allowed_symbols somewhere.

Once three weeks have passed, we need to add the wrapper which runs MaxPoolV2 whenever tf.max_pool is called.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@yongtang please add MaxPoolV2 to hidden_ops.txt.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (27/25 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:20928)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-e6d9-mazecreator=mazecreator.com@sgmail.github.com>)
	id 1demvV-0005ix-Lz
	for mazecreator@mazecreator.com; Mon, 07 Aug 2017 13:39:23 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=pvZCicpUPTlciaIxigIUQDHrZ7o=; b=AnGbocy65u52o7Bd
	I3JYafC/25XSdqXWn9iEydR+8mFaXiP5wRI/yevi1WXWaDK9ExDPtuHrjs57BrxL
	KFLiThhV71YDTx7CMaLK6ULBHLwt8iY2fMUJiw4D9sIAwns05AGduh6KMi2mb8H1
	gOQULf1JTVOnChGlu7uFF/j+Tew=
Received: by filter0966p1mdw1.sendgrid.net with SMTP id filter0966p1mdw1-25672-5988B64A-23
        2017-08-07 18:49:46.615311371 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id SOaTTrD3TwCKH9kms9r5pg
	for <mazecreator@mazecreator.com>; Mon, 07 Aug 2017 18:49:46.594 +0000 (UTC)
Date: Mon, 07 Aug 2017 18:49:46 +0000 (UTC)

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Review by rmlarsen — APPROVED** [review]

**Review by rmlarsen — CHANGES_REQUESTED** [review]
@yongtang  Actually, you still need to add the new op to hidden_ops.txt

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by yongtang** [comment]
The PR has been updated.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
Thank for the contribution!

**Comment by sleighsoft** [comment]
Is there already a way to use that in python?

**Comment by MichaelScaria** [comment]
When will we be able to use this in python?

**Comment by sleighsoft** [comment]
You can do the following for now:
```python
from tensorflow.python.ops import gen_nn_ops
        pool = gen_nn_ops._max_pool_v2(
            conv,
            ksize=[1, tf.shape(conv)[1], tf.shape(conv)[2], 1],
            strides=[1, 1, 1, 1],
            padding='VALID',
            name="pool")
```

Where `conv` is the output of a `tf.layers.conv2d` for example.

**Comment by yongtang** [comment]
@MichaelScaria @sleighsoft A PR  #14983 is created for the v2 in python fix.

**Comment by hlzz** [comment]
@sleighsoft gen_nn_ops._max_pool_v2 is no longer available in version 1.7. So your workaround doesn't work anymore.
@yongtang what's worse is that your PR #14983 is reverted. 
So what should we do to use this dynamic ksize?

**Comment by yongtang** [comment]
@hlzz I believe `_` in generated ops like (`get_nn_ops`) is not needed anymore so I think it is worth to give `gen_nn_ops.max_pool_v2` a try (caution: I haven't tried it myself yet).

PR #14983 was reverted because it caused some issues with MKL. I don't have a lot of experience with MKL, but will give it a try if I had a chance.

**Comment by hlzz** [comment]
@yongtang I've tried, gen_nn_ops.max_pool_v2 is also not there. Don't know what's going on with nn_ops, but it was still there when you made this PR, which is quite recent.

**Comment by sleighsoft** [comment]
gen_nn_ops is machine "generated" locally. I am using v2 for a while now and it works well.

**Comment by xdsilly** [comment]
@yongtang excuse me, i am working on dynamic k-max pooling also, so i need to use _max_pool_v2 in my program. But it has been reverted as you say few months ago, so i wonder if there is any older version of tensorflow we can use _max_pool_v2. Thanks very much!

**Comment by xdsilly** [comment]
@sleighsoft excuse me, which version of tensorflow you can use _max_pool_v2, or any modifies you make in your tensorflow,

**Comment by sleighsoft** [comment]
No, I did not modify anything. I am currently on some 1.8 nightly

**Comment by yongtang** [comment]
@xdsilly As was mentioned in https://github.com/tensorflow/tensorflow/pull/11875#issuecomment-348149489 (@sleighsoft 👍 ), you could use:

```
from tensorflow.python.ops import gen_nn_ops
pool = gen_nn_ops.max_pool_v2(....)
```

Make sure there is no `_` before `max_pool_v2` (`gen_nn_ops.max_pool_v2` not `gen_nn_ops._max_pool_v2`)

**Comment by sleighsoft** [comment]
Oh sorry, forgot to mention that the `_` got dropped

**Comment by olgafour1** [comment]
Is the same modification applied on also for the average pooling layer?

**Pull request merged**
