### PR TITLE
Make fixed format ACL convolution able to handle NCHW input

### PR DESCRIPTION
**Pull request by annop-w**
Also removes //tensorflow/python/kernel_tests/nn_ops:conv_ops_test_cpu , which is fixed by this PR, from skip list.

### CODE REVIEW

**Comment by nSircombe** [comment]
@penpornk 
@elfringham

**Review by penpornk — APPROVED** [review]
Thank you for the PR!
It looks like we forgot to update onednn_acl_depthwise_convolution.patch when we updated oneDNN to v2.7.3. Glad we got it now.

**Comment by penpornk** [comment]
[Py+CPP Test Suite](https://source.cloud.google.com/results/invocations/e83222fa-cd74-40c8-9b45-77cc9fa4bec4/targets) failure seems unrelated. 
```
==================== Test output for //tensorflow/python/client:session_partial_run_test:
...
======================================================================
ERROR: testPartialRunMissingPlaceholderFeedExceptionDist (__main__.PartialRunTest)
PartialRunTest.testPartialRunMissingPlaceholderFeedExceptionDist
----------------------------------------------------------------------
...
tensorflow.python.framework.errors_impl.InternalError: From /job:localhost/replica:0/task:0:
ValidateDevices called before initialization.
```

But it's a required test, so I'm rerunning it.


The rest seems okay:
* [Arm CI](https://github.com/tensorflow/tensorflow/actions/runs/4831759860) seems fine.
* [AMD ROCm](http://ml-ci.amd.com:21096/blue/organizations/jenkins/tensorflow%2Fgithub-prs-upstream-master%2FAMD-ROCm-Community-CI-Build/detail/PR-60432/2/pipeline) failure seems unrelated.

**Comment by elfringham** [comment]
> [Py+CPP Test Suite](https://source.cloud.google.com/results/invocations/e83222fa-cd74-40c8-9b45-77cc9fa4bec4/targets) failure seems unrelated.
> 
> ```
> ==================== Test output for //tensorflow/python/client:session_partial_run_test:
> ...
> ======================================================================
> ERROR: testPartialRunMissingPlaceholderFeedExceptionDist (__main__.PartialRunTest)
> PartialRunTest.testPartialRunMissingPlaceholderFeedExceptionDist
> ----------------------------------------------------------------------
> ...
> tensorflow.python.framework.errors_impl.InternalError: From /job:localhost/replica:0/task:0:
> ValidateDevices called before initialization.
> ```
> 
> But it's a required test, so I'm rerunning it.
> 
> The rest seems okay:
> 
>     * [Arm CI](https://github.com/tensorflow/tensorflow/actions/runs/4831759860) seems fine.
> 
>     * [AMD ROCm](http://ml-ci.amd.com:21096/blue/organizations/jenkins/tensorflow%2Fgithub-prs-upstream-master%2FAMD-ROCm-Community-CI-Build/detail/PR-60432/2/pipeline) failure seems unrelated.

Yes, it is unrelated and known to be flaky. https://github.com/tensorflow/tensorflow/issues/60351

**Pull request merged**
