### PR TITLE
Minor improvement to documentation

### PR DESCRIPTION
**Pull request by freddan80**
* Added offline planner documentation to memory management markdown, since it was missing.
* Minor updates to CMSIS-NN and Ethos-U documentation to reflect current functionality.

### CODE REVIEW

**Comment by freddan80** [comment]
A question/comment. Should I create an RFC folder inside the docs folder? Right now there's a mix between RFC's (e.g. pre-allocated tensor) and 'general documentation' in the docs root folder. @advaitjain let me know what you think.

**Comment by freddan80** [comment]
Solving #48183

**Review by mansnils — APPROVED** [review]

**Review by advaitjain — APPROVED** [review]

**Comment by advaitjain** [comment]
> A question/comment. Should I create an RFC folder inside the docs folder? Right now there's a mix between RFC's (e.g. pre-allocated tensor) and 'general documentation' in the docs root folder. @advaitjain let me know what you think.

Yes, that's a good idea. An RFC sub-folder would be very nice.

**Comment by freddan80** [comment]
@advaitjain done, pushed to this PR

**Review by advaitjain — APPROVED** [review]

**Pull request merged**
