### PR TITLE
Format usage examples in docstring for Python.

### PR DESCRIPTION
**Pull request by dynamicwebpaige**

### CODE REVIEW

**Comment by rthadur** [comment]
@dynamicwebpaige  please resolve merge conflicts

**Review by tomhennigan — APPROVED** [review]
Assuming this is so the generated docs look good? I think otherwise these already follow the recommended style for doctest https://docs.python.org/2/library/doctest.html.

**Comment by rthadur** [comment]
@dynamicwebpaige gentle ping to resolve the conflicts

**Comment by rthadur** [comment]
> @dynamicwebpaige gentle ping to resolve the conflicts

gentle ping

**Review by shahzadlone — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
It has been 25 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
