### PR TITLE
fix_typo of map_structure doc

### PR DESCRIPTION
**Pull request by davidpham87**

### CODE REVIEW

**Comment by davidpham87** [comment]
I signed it!

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Review by caisq — APPROVED** [review]

**Comment by davidpham87** [comment]
Yes! My first contribution to Tensorflow. I should do this more often.

**Comment by drpngx** [comment]
Congrats! By all means, contributions are welcome :)

**Pull request merged**
