### PR TITLE
[ROCm] Fix for the ROCm CSB breakage - 200113 - 1

### PR DESCRIPTION
**Pull request by deven-amd**
The ROCm CSB was broken by the following commit :

https://github.com/tensorflow/tensorflow/commit/880cad85987e8948774f9bae24b1420074534f00

The commit leads to linker errors like below :

```
bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/serialize_sparse_op/serialize_sparse_op.o:
serialize_sparse_op.cc:function tensorflow::(anonymous namespace)::SerializeManySparseOp<tensorflow::tstring, tensorflow::Variant>::Compute(tensorflow::OpKernelContext*): error:
undefined reference to 'tensorflow::DataTypeToEnum<tensorflow::tstring>::value'  
```

The breakage seems to be something that should affect all platforms (not just ROCm)

The cause of the error is that the static member varibale `DataTypeToEnum<T>::value` is declared,
but not defined in the file `tensorflow/core/framework/types.h` file.  Since it si a `constexpr` value, most of it's uses are optimized by the time we get to the linker.

However any use of it that survives to the linking stage, for e.g. use as a "reference",  will lead to linker errors. The commit above seems to introduce two such uses.

The first commit in this PR works around the linker error, by creating a local variable, to avoid the use of `DataTypeToEnum<T>::value` as a reference.

The second commit adds the explicit definition of `DataTypeToEnum<T>::value` in  `types.cc` file

Both commits are independent of each other and will fix the breakage. You can choose to pick either or both, and I can rebase the PR accordingly.

thanks

-----------------------------------

/cc @chsigg @cheshire @whchung

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by mrry — APPROVED** [review]
Thanks for the fix!

**Comment by ebrevdo** [comment]
I prefer just the change to `types.cc` file, but am OK with the fix in both places.

**Comment by procule** [comment]
Thanks a lot for that fix. I've been trying for two days to understand the problem. Compiling TF with Bazel every time you do a small change isn't very optimal to find a problem at the linking stage.

CPU: AMD Ryzen Threadripper 2950X 16-Core Processor
GPUs: 
        1. GeForce RTX 2080
        2. GeForce GTX 960

CUDA: 10.2
Nvidia Linux drivers: 440.44

**Pull request merged**
