### PR TITLE
Fix BUILD_WITH_MMAP error in TFLite Makefile

### PR DESCRIPTION
**Pull request by zhuyie**

### CODE REVIEW

**Comment by zhuyie** [comment]
@miaout17 Can you please take a look at this?

**Comment by miaout17** [comment]
Thanks for sending the Pull Request. 

However it doesn't look right to disable mmap_allocation when `BUILD_WITH_MMAP` is true. 
Could you describe what issue are you running into?

**Comment by miaout17** [comment]
I'm closing this PR since it's incorrect to simply flipping the logic. 
Please create a bug report if you're hitting some issues, with reproduce steps. 
Thanks a lot!

**Comment by zhuyie** [comment]
@miaout17 I think we should *INCLUDE* mmap_allocation.cc when BUILD_WITH_MMAP is true, not *EXCLUDE* it.

**Pull request closed without merging**
