### PR TITLE
fix cmake build error for tflite c library

### PR DESCRIPTION
**Pull request by jiajunstanley**
Fix cmake error when building tflite C library:

```
CMake Error at CMakeLists.txt:63 (add_library):
  Cannot find source file:

    common.c

```

### CODE REVIEW

**Comment by gbaned** [comment]
@miaout17 Can you please review this PR ? Thank you!

**Comment by feliwir** [comment]
This caused issue #56125 inside the TensorFlow 2.9 release - i'm suprised there is an open PR for a known issue that does not get merged....

**Comment by gbaned** [comment]
Hi @miaout17 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @miaout17 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @miaout17 Can you please review this PR ? Thank you!

**Comment by jasonw247** [comment]
Is there an update on this? I just encountered the issue outlined in https://github.com/tensorflow/tensorflow/issues/56125 (which this should solve) on r2.10.

**Comment by mpromonet** [comment]
This seems fixed by https://github.com/tensorflow/tensorflow/pull/57134, hope a release will include this soon ?

**Comment by sachinprasadhs** [comment]
As mentioned in the comment here, the changes are reflecting in master branch now. Could you please close the PR. Thanks!
> This seems fixed by #57134, hope a release will include this soon ?

**Pull request closed without merging**
