### PR TITLE
[r2.2:Cherryppick] Split unroll_batch_matmul pass into own build target

### PR DESCRIPTION
**Pull request by lgeiger**
This is a cherry-pick of #37356

@jpienaar Since this doesn't include functional changes it would be amazing if it could be cherry-picked onto the 2.2 release branch.

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
I think you are missing https://github.com/tensorflow/tensorflow/blob/b720399a6efd37259b2dc51912e217f49b4efa60/tensorflow/compiler/mlir/tensorflow/transforms/unroll_batch_matmul.cc#L28-L29 

It was in #37356 but it is not here. Is it possible the cherrypick was wrong?

**Comment by lgeiger** [comment]
@mihaimaruseac If I compare 0e86d517ea2956be302282f0845c79ca641fb01f and this PR side by side the only difference are the changes in [`tensorflow/compiler/mlir/tensorflow/transforms/batchmatmul_to_einsum.cc`](https://github.com/tensorflow/tensorflow/commit/0e86d517ea2956be302282f0845c79ca641fb01f#diff-cc764124765cbb5a4340353f6371f496) which are not relevant on the `r2.2` branch since the file doesn't exist, or am I missing something?

**Comment by mihaimaruseac** [comment]
Oh, sorry, I was looking at the wrong file.


However, there are still differences between the PR on master and the PR on this branch: On master https://github.com/tensorflow/tensorflow/pull/37356/files#diff-f20d136d02b72175cd9891df563f8d62R267-R280. On this branch https://github.com/tensorflow/tensorflow/pull/37362/files#diff-f20d136d02b72175cd9891df563f8d62R267-R287 There are more deps added on this branch than on master.

**Comment by lgeiger** [comment]
> However, there are still differences between the PR on master and the PR on this branch

This is intentional since during the merge of #37356 those dependencies where added to resolve internal build errors mentioned in https://github.com/tensorflow/tensorflow/pull/37356#issuecomment-595965631

See 0e86d517ea2956be302282f0845c79ca641fb01f for the diff of the merged PR into master.

**Comment by mihaimaruseac** [comment]
Makes sense. Thank you

**Pull request merged**
