### PR TITLE
[Lite] Added 8-bit Quantization Support- FloorDiv.

### PR DESCRIPTION
**Pull request by amitsrivastava78**

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@jdduke , i have resolved the merge conflict, kindly have a look.

Regards
Amit

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@amitsrivastava78 Could you please resolve the conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Pull request closed without merging**
