### PR TITLE
[TF-TRT] Additional TRT 8.5 Fixups

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
@bixia1 for review

### CODE REVIEW

**Comment by bixia1** [comment]
@DEKHTIARJonathan something is wrong with this PR, it modifies > 350 files.

**Comment by DEKHTIARJonathan** [comment]
Oh wow ... You're right... Mis-manipulation incorrect outdated base branch. It's fixed

**Comment by DEKHTIARJonathan** [comment]
@bixia1 we really need this PR merged

**Review by bixia1 — APPROVED** [review]

**Comment by bixia1** [comment]
Build failed:
third_party/tensorflow/compiler/tf2tensorrt/convert/weights.cc:61:11: error: enumeration value 'kBOOL' not handled in switch [-Werror,-Wswitch]
  switch (type_) {
          ^~~~~
1 error generated.

third_party/tensorflow/compiler/tf2tensorrt/convert/weights.cc:61:11: error: enumeration value 'kBOOL' not handled in switch [-Werror,-Wswitch]
  switch (type_) {
          ^~~~~
1 error generated.

**Comment by gbaned** [comment]
@DEKHTIARJonathan Can you please check @bixia1's comments and keep us posted ? Thank you!

**Comment by DEKHTIARJonathan** [comment]
@bixia1 problems fixed. Please re-review

**Review by bixia1 — APPROVED** [review]

**Pull request merged**
