### PR TITLE
Relax type of tf.constant.value to sequence

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**

### CODE REVIEW

**Comment by martinwicke** [comment]
I'd have to look closer, but what happens to strings?

**Comment by mrry** [comment]
Indeed, this seems like it would break `tf.convert_to_tensor(“foo”)` because `isinstance(“foo”, collections.Sequence)` is true.

**Comment by nathanielmanistaatgoogle** [comment]
> @nathanielmanistaatgoogle do you want to try to fix this?

Short answer: yes.

Long answer: in the next three or four weeks maybe; definitely not this week or next.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nathanielmanistaatgoogle** [comment]
@tensorflowbutler: this should probably be assigned to me? It's certainly blocked waiting for a response from me...

**Comment by martinwicke** [comment]
Yup. Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nathanielmanistaatgoogle** [comment]
@tensorflowbutler: this is still worth fixing, and I do intend to turn it around... at some point. Thank you for your continued patience.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 121 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nathanielmanistaatgoogle: It has been 136 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mrry** [comment]
I'm cleaning the decks of my assigned reviews, and since this PR seems to have stalled, I'm going to remove myself as reviewer.

**Review by alextp — CHANGES_REQUESTED** [review]
Can you add a test of the particular Sequences you care about?

**Comment by alextp** [comment]
Do you plan on addressing my review asking for a test?

**Comment by nathanielmanistaatgoogle** [comment]
Yes, I plan on coming back to this as soon as I find time. It's been... wow, almost a year. Wow. Didn't think I'd stay that busy... :slightly_smiling_face:

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
