### PR TITLE
Simplify reset_uids()

### PR DESCRIPTION
**Pull request by autoih**
Remove unnecessary dict clearance code

### CODE REVIEW

**Comment by gbaned** [comment]
@I-Hong Could you please resolve the conflicts? Thanks!

**Review by tanzhenyu — DISMISSED** [review]

**Comment by I-Hong** [comment]
Thanks @gbaned. Updated.

**Comment by gbaned** [comment]
@I-Hong Could you please look at the failing checks? Thanks!

**Comment by I-Hong** [comment]
Updated!

**Review by tanzhenyu — APPROVED** [review]

**Pull request merged**
