### PR TITLE
Use `tf` libaries instead of `array_ops` to provide compatibility with the Tensorflow API

### PR DESCRIPTION
**Pull request by Eben-Success**
…ity with Tensorflow API

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @rainwoodman Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rainwoodman Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rainwoodman Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jsmeredith  Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jsmeredith Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jsmeredith Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jsmeredith Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jsmeredith Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @jsmeredith Can you please review this PR ? Thank you!

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Can you remove changes that are not related (e.g., renaming the test)?

To be honest, I don't think using `tf.` here would work, as this is supposed to be testing the _internal_ API, not the public one.

**Comment by keerthanakadiri** [comment]
Hi @Eben-Success, Any update on this PR ? Please. Thank you !

**Comment by mihaimaruseac** [comment]
Let's just close this, it does not seem to work.

**Pull request closed without merging**
