### PR TITLE
[ROCM] Add ROCM option to tensorflow-build

### PR DESCRIPTION
**Pull request by jayfurmanek**
This PR adds ROCM support to the tensorflow-build container framework.
The idea is to slot ROCM along side the CUDA container in an unobtrusive way. 
The only change on the CUDA side will be needing to explicitly set the --config=cuda for the bazel build command, which is probably more proper anyway and matches the main .bazelrc.

Setting this as draft so I can to do more testing on the CUDA side to make sure I didn't break anything

FYI @angerson 
I'm interested in your thoughts here. thx!

### CODE REVIEW

**Comment by angerson** [comment]
Thanks for working on this!

Can you fork a new directory, like tf_sig_build_dockerfiles_rocm, instead of changing this directory? Afterwards, add ownership details to the top of the README, similar to how subdirectories in the SIG Build repo work.

I know that will introduce more work for you because changes to the originals won't carry over to ROCm unless you use symlinks or something similar. However, I want to encapsulate each variant of the containers (official, ROCm, ARM64, etc.) so that our maintainers don't need to worry about colliding with the other variants.

**Comment by jayfurmanek** [comment]
That makes sense. For common files, are symlinks ok, or should we have a common directory or something as well? Sometimes dependencies change we'll have no idea when or why.

**Comment by angerson** [comment]
Symlinks are good for now, I think. We can look at adding a common directory again later, if it doesn't work out.

**Comment by gbaned** [comment]
Hi @jayfurmanek Can you please check @angerson's [comments](https://github.com/tensorflow/tensorflow/pull/59829#issuecomment-1456994681) and keep us posted ? Thank you!

**Comment by gbaned** [comment]
Hi @jayfurmanek Any update on this PR? Please. Thank you!

**Comment by jayfurmanek** [comment]
I'm going to re-factor this according to Austin's comments. I'll open a separate PR for that.

**Pull request closed without merging**
