### PR TITLE
Change the inherited classes of some dataset ops

### PR DESCRIPTION
**Pull request by feihugis**
This PR fixes the issue #22681

### CODE REVIEW

**Comment by feihugis** [comment]
@jsimsa Could you help review this PR when you have time?

**Comment by jsimsa** [comment]
The API compatibility test is failing, please following the instructions in the test output to fix the issue.

**Comment by feihugis** [comment]
@jsimsa I merged two commits into one, but did not see you are running the test. Could you help re-run the test?

Another thing is that when I run the test locally (`$ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test`), I saw some issues as below:
```
ERROR:tensorflow:36 differences found between API and golden.
Issue 1	: Object tensorflow.estimator.Estimator expected but not found (removed).
Issue 2	: Object tensorflow.estimator.BaselineClassifier expected but not found (removed).
Issue 3	: Object tensorflow.estimator.export.ExportOutput expected but not found (removed).
Issue 4	: Object tensorflow.estimator.inputs expected but not found (removed).
Issue 5	: Object tensorflow.estimator.export.RegressionOutput.__metaclass__ expected but not found (removed).
Issue 6	: Object tensorflow.estimator.export.PredictOutput.__metaclass__ expected but not found (removed).
Issue 7	: Object tensorflow.estimator.EvalSpec expected but not found (removed).
Issue 8	: Object tensorflow.estimator.BaselineRegressor expected but not found (removed).
Issue 9	: Object tensorflow.estimator expected but not found (removed).
Issue 10	: Object tensorflow.estimator.FinalExporter expected but not found (removed).
Issue 11	: Object tensorflow.estimator.export.PredictOutput expected but not found (removed).
Issue 12	: Object tensorflow.estimator.WarmStartSettings expected but not found (removed).
Issue 13	: Object tensorflow.estimator.export.ClassificationOutput expected but not found (removed).
Issue 14	: Object tensorflow.estimator.export.RegressionOutput expected but not found (removed).
Issue 15	: Object tensorflow.estimator.BoostedTreesRegressor expected but not found (removed).
Issue 16	: Object tensorflow.estimator.export expected but not found (removed).
Issue 17	: Object tensorflow.estimator.LatestExporter expected but not found (removed).
Issue 18	: Object tensorflow.estimator.EstimatorSpec expected but not found (removed).
Issue 19	: Object tensorflow.estimator.export.ClassificationOutput.__metaclass__ expected but not found (removed).
Issue 20	: Object tensorflow.estimator.RunConfig expected but not found (removed).
Issue 21	: Object tensorflow.estimator.LinearClassifier expected but not found (removed).
Issue 22	: Object tensorflow.estimator.DNNLinearCombinedClassifier expected but not found (removed).
Issue 23	: Object tensorflow.estimator.BoostedTreesClassifier expected but not found (removed).
Issue 24	: Object tensorflow.estimator.DNNClassifier expected but not found (removed).
Issue 25	: Object tensorflow.estimator.export.ExportOutput.__metaclass__ expected but not found (removed).
Issue 26	: Object tensorflow.estimator.ModeKeys expected but not found (removed).
Issue 27	: Object tensorflow.estimator.BestExporter expected but not found (removed).
Issue 28	: Object tensorflow.estimator.Exporter expected but not found (removed).
Issue 29	: Object tensorflow.estimator.VocabInfo expected but not found (removed).
Issue 30	: Object tensorflow.estimator.DNNLinearCombinedRegressor expected but not found (removed).
Issue 31	: Object tensorflow.estimator.DNNRegressor expected but not found (removed).
Issue 32	: Object tensorflow.estimator.export.ServingInputReceiver expected but not found (removed).
Issue 33	: Object tensorflow.estimator.WarmStartSettings expected but not found (removed).
Issue 34	: Object tensorflow.estimator.TrainSpec expected but not found (removed).
Issue 35	: Object tensorflow.estimator.export.TensorServingInputReceiver expected but not found (removed).
Issue 36	: Object tensorflow.estimator.LinearRegressor expected but not found (removed).
```

**Review by jsimsa — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by feihugis** [comment]
@jsimsa @rmlarsen This PR has been `ready to pull` for 22 days. Is there anything I need to do?

**Comment by jsimsa** [comment]
Thank you for the reminder. I will work on getting this merged today.

**Pull request merged**
