### PR TITLE
Tests that BasicLSTMCell with layer_norm=False.

### PR DESCRIPTION
**Pull request by chris-chris**
I think BasicLSTMCell should be tested when layer_norm is False.

### CODE REVIEW

**Comment by ebrevdo** [comment]
Pretty sure the basiclstmcell is so basic we don't want to add layer norm
to it.

On May 11, 2017 9:24 PM, "Benoit Steiner" <notifications@github.com> wrote:

@benoitsteiner <https://github.com/benoitsteiner> requested your review on:
tensorflow/tensorflow#9817
<https://github.com/tensorflow/tensorflow/pull/9817> Tests that
BasicLSTMCell with layer_norm=False..

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/pull/9817#event-1079368087>, or mute
the thread

**Comment by rmlarsen** [comment]
@ebrevdo this just adds additional test coverage. Are you opposed to that?

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by ebrevdo** [comment]
No, I'm opposed to BasicLSTMCell having layer norm in the first place.
Let's fix that in the other PR and then we don't need this one.

**Comment by ebrevdo** [comment]
Ah I see - you were comparing BasicLSTMCell to LayerNormLSTMCell.  

LGTM assuming tests pass

**Review by ebrevdo — APPROVED** [review]

**Comment by maciekcc** [comment]
Jenkins test this please.

**Pull request merged**
