### PR TITLE
Cherrypicks

### PR DESCRIPTION
**Pull request by av8ramit**
Docs updates Mark requested.

### CODE REVIEW

**Comment by wolffg** [comment]
Just to be sure, @MarkDaoust -- in this commit, I don't see the supervisor.md contents actually moved; it looks like it's just deleted, which might contrast to the commit description.  Secondly, leftnav_files seems to still contain supervisor.md.

**Comment by MarkDaoust** [comment]
For supervisor.md I forgot to update the commit description after @ispir asked that I make it a deletion. It's the commit message that's wrong, not the files.

**Review by MarkDaoust — APPROVED** [review]
I've staged this internally (in the root version) if anyone wants to see the result.

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Pull request merged**
