### PR TITLE
Try to convert to readable latex

### PR DESCRIPTION
**Pull request by ptarjan**
I'm sure what processor you use for http://www.tensorflow.org/tutorials/mnist/beginners/index.md but this is my guess at how to make those symbols translate to something better than it is now

image

### CODE REVIEW

**Comment by vrv** [comment]
Hi @ptarjan, as mentioned in our [Contribution doc](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md), we don't accept pull requests through github yet, and our contribution flow through googlesource.com isn't that easy yet -- for a change like this, would you mind if we fix internally and push the change out for you?

**Comment by ptarjan** [comment]
Feel free to do the change however you want. When I was at Facebook I wrote a syncing system for pull requests to our pharbricator instance, and vice-versa. Maybe something like that would work for you?

See all the PRs on https://github.com/facebook/hhvm for examples of this.

**Comment by vrv** [comment]
Nice :).  Yeah, we'll look into automatically converting the pull requests, and in the meantime we'll address this internally first.  Thanks for the feedback!

**Comment by bhack** [comment]
@vrv There is [Gerrithub](http://gerrithub.io) but it was not opensourced

**Comment by bhack** [comment]
Or take a look at the status of [this gerrit plugin](https://gerrit.googlesource.com/plugins/github/+/master/README.md)

**Comment by BenMorganIO** [comment]
:+1:

**Comment by mrdrozdov** [comment]
Creating an account on Gerrit was not too difficult. I followed the instructions here: https://tensorflow-review.googlesource.com/#/c/1061/2/CONTRIBUTING.md

If that is the only requirement for going through the contribution flow, then I'd recommend giving it a shot.

**Comment by vrv** [comment]
Thanks @mrdrozdov.  Closing for now -- feel free to send through gerrit in the mean-time.

**Pull request closed without merging**
