### PR TITLE
fix spelling

### PR DESCRIPTION
**Pull request by Bantena**
Fix dnn_with_layer_annotations.py 251 line.
Use 'an' instead of 'a' if following word starts with a vowel sound.
so I change 'a estimator' to 'an estimator'

### CODE REVIEW

**Comment by Bantena** [comment]
I fix spelling problem

**Comment by Bantena** [comment]
cla/google

**Comment by Bantena** [comment]
cls: yew

**Comment by Bantena** [comment]
cla: yew

**Comment by Bantena** [comment]
cla: yes

**Comment by Bantena** [comment]
cla  : yes

**Comment by whismile** [comment]
.

**Review by ghost — COMMENTED** [review]
ok

**Review by ghost — APPROVED** [review]
Ok It's ok

**Review by ghost — CHANGES_REQUESTED** [review]
It's ok

**Review by Bantena — COMMENTED** [review]
asd

**Review by ghost — APPROVED** [review]
Yes

**Comment by rmlarsen** [comment]
@Bantena could you please sign the CLA?

**Comment by rmlarsen** [comment]
@Bantena Ah, I see you sent a separate PR with the CLA signed. Thanks!

**Pull request closed without merging**
