### PR TITLE
Revert "TF Checkpoint V2: add "write_version" arg to tf.train.Saver."

### PR DESCRIPTION
**Pull request by yifeif**
This reverts commit a1d0c8e59bec28643688852271859fb750fab1fc.

### CODE REVIEW

**Comment by concretevitamin** [comment]
I saw
Windows Cmake Tests — FAILURE

**Comment by gunan** [comment]
No windows support on 0.11, so expected failure.

**Comment by yifeif** [comment]
That's expected. 0.11 does not have windows support yet, but the test was added universally for PRs on any branch.

**Comment by concretevitamin** [comment]
I see.  LGTM (I don't see an "approve" button).  Thanks for helping on this Yifei!

**Review by gunan — APPROVED** [review]

**Review by concretevitamin — APPROVED** [review]

**Pull request merged**
