### PR TITLE
Branch 147434408

### PR DESCRIPTION
**Pull request by yifeif**

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]
So scary.

**Comment by martinwicke** [comment]
This is not only for docs? e.g. 76906ff?

**Comment by vrv** [comment]
tfdbg will still fail, but if that's the only failure, feel free to merge

**Comment by martinwicke** [comment]
Yes, @caisq's commit is still outstanding, but this will be useful anyway.

**Comment by yifeif** [comment]
Yea, just push, cherrypick to follow once merged.

**Comment by martinwicke** [comment]
Hmm... that commit 76906ff doesn't work. @petewarden?

**Comment by vrv** [comment]
that and the flatmap changes totally died.  ugh

**Comment by yifeif** [comment]
rolling back flatmap change and push again. Closing this one.

**Pull request closed without merging**
