### PR TITLE
Fix CMake config if used as a subproject

### PR DESCRIPTION
**Pull request by NewProggie**
With this fix we don't assume that the tensorflow project is the build
root. Instead `CMAKE_CURRENT_SOURCE_DIR`/`CMAKE_CURRENT_BINARY_DIR` is used
instead of just `CMAKE_SOURCE_DIR`/`CMAKE_BINARY_DIR`, which now builds
successfully, if it is built inside another, larger project.

### CODE REVIEW

**Review by mrry — APPROVED** [review]
Thanks for the fix! LGTM.

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by NewProggie** [comment]
Seems that the one failing test has nothing to do with my PR?

**Comment by mrry** [comment]
Yes, the test failure looks unrelated. I'll merge the PR now.

**Pull request merged**
