### PR TITLE
Fix syntax error in single_image_random_dot_stereograms caused by locale

### LINKED ISSUE #21164: Default floating point values in single_image_random_dot_stereograms_ops.cc cause syntax error
Have I written custom code: yes
OS Platform and Distribution: Ubuntu 18.04
TensorFlow installed from: origin master
TensorFlow version: 1.9
Bazel version 0.15.2
CUDA/cuDNN version: 9.1/7.1
GPU model and memory:  NVIDIA-SMI 390.48
Exact command to reproduce: use code below in python3 script 
Mobile device: N/A
     
     import tensorflow as tf
      vol = tf.contrib.util.make_tensor_proto([256, 256])

Import of /localhome/local/projects/lme_custom_ops/tensorflow/contrib/image/__init__.py causes syntax error on my system (see issue https://github.com/tensorflow/serving/issues/421).

    Traceback (most recent call last):
    File "main.py", line 6, in <module>
        import geometry as geometry
    File "/localhome/local/projects/deep-iterative-reco/geometry.py", line 20, in <module>
        volume_origin = tf.contrib.util.make_tensor_proto([-((_volume_xy-1)/2 * _volume_spacing),-((_volume_xy-1)/2 * _volume_spacing)], tf.float32 )
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
        module = self._load()
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
        module = importlib.import_module(self.__name__)
    File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/__init__.py", line 48, in <module>
        from tensorflow.contrib import image
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/image/__init__.py", line 70, in <module>
        from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 27, in <module>
        "_single_image_random_dot_stereograms.so"))
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
        ret = load_library.load_op_library(path)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 73, in load_op_library
        exec(wrappers, module.__dict__)
    File "<string>", line 28
        def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=3, mu=0,333299994, normalize=True, normalize_max=-100, normalize_min=100, border_level=0, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                                                    ^
    SyntaxError: invalid syntax

Works again if I change the default kwargs float arguments to integer values. Reason maybe localization option (I am from Germany which uses , to indicate decimal point. E.g. 1.2 == 1,2 in Germany). Though I think I am using the US standard.

Using this code in /tensorflow/contrib/image/ops/single_image_random_dot_stereograms_ops.cc solves the problem (not using floating values).

    REGISTER_OP( "SingleImageRandomDotStereograms" )
        .Attr( "T: {double,float,int64,int32}" )
        .Input( "depth_values: T" )
        .Output( "image: uint8" )
        .Attr( "hidden_surface_removal: bool = true" )
        .Attr( "convergence_dots_size: int = 8" )
        .Attr( "dots_per_inch: int = 72" )
        .Attr( "eye_separation: float = 3" )
        .Attr( "mu: float = 3333" )
        .Attr( "normalize: bool = true" )
        .Attr( "normalize_max: float = -100.0" )
        .Attr( "normalize_min: float = 100.0" )
        .Attr( "border_level: float = 0.0" )
        .Attr( "number_colors: int = 256" )

On python2 executing the following...  

      Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
      [GCC 7.3.0] on linux2
      Type "help", "copyright", "credits" or "license" for more information.
      >>> import locale
      >>> locale.setlocale(locale.LC_ALL, '')
            'LC_CTYPE=en_US.UTF-8;LC_NUMERIC=de_DE.UTF-8;LC_TIME=de_DE.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=de_DE.UTF-8;LC_NAME=de_DE.UTF-8;LC_ADDRESS=de_DE.UTF-8;LC_TELEPHONE=de_DE.UTF-8;LC_MEASUREMENT=de_DE.UTF-8;LC_IDENTIFICATION=de_DE.UTF-8'

Though I compiled for python3:

    Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
    Type "copyright", "credits" or "license" for more information.

    IPython 5.5.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: 
    ...: 
    ...: import locale

    In [2]: locale.localeconv()
    Out[2]: 
    {'currency_symbol': '',
    'decimal_point': '.',
    'frac_digits': 127,
    'grouping': [],
    'int_curr_symbol': '',
    'int_frac_digits': 127,
    'mon_decimal_point': '',
    'mon_grouping': [],
    'mon_thousands_sep': '',
    'n_cs_precedes': 127,
    'n_sep_by_space': 127,
    'n_sign_posn': 127,
    'negative_sign': '',
    'p_cs_precedes': 127,
    'p_sep_by_space': 127,
    'p_sign_posn': 127,
    'positive_sign': '',
    'thousands_sep': ''}

I am using tensorflow revision 6d71d3fc659b317a38586f71ae94410ad3261f55 on Ubuntu 18.08. cuDNN 7.1, CUDA 9.1

This seems to be related: https://github.com/tensorflow/tensorflow/issues/2974

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #21164 where the single_image_random_dot_stereograms in different locale (like de_DE) caused syntax error in python like:
```
File "<string>", line 28
    def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=2,5, mu=0,333299994, normalize=True, normalize_max=-100, normalize_min=100, border_level=0, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                      ^
SyntaxError: invalid syntax
```

The issue was that the float to string conversion in `python_op_gen_internal.cc` triggered snprintf (in `FloatToBuffer`) which is local dependent and generates something like `eye_separatiion=2,5` in DE locale.

This fix replaced the float to string conversion with locale-independent
```
      std::ostringstream s;
      s.imbue(std::locale::classic());
```

This fix fixes #21164.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by martinwicke — DISMISSED** [review]

**Comment by martinwicke** [comment]
Nice.

**Comment by martinwicke** [comment]
Can you fix the import order (see linter log: https://source.cloud.google.com/results/invocations/ff5695b9-ca62-4de2-8c9a-b3b8d2f7a69c/targets/%2F%2Ftensorflow%2Ftools%2Fci_build:gen_ci_clang_format_out/log)

**Comment by martinwicke** [comment]
Wait, your last commit already ran clang-format? Is that stale?

**Comment by martinwicke** [comment]
Is this a difference between clang-format versions? I'm afraid of those...

**Comment by yongtang** [comment]
Thanks @martinwicke for the review. The PR has been updated to address the issue in `Experimental clang-format Check` failure.

The clang-format might be different over versions.  I am wondering if there is some information about platform, clang-format version, and the command line in `Experimental clang-format Check`? That probably helps so that developer could run the `Experimental clang-format Check` before submit the PR.

**Comment by yongtang** [comment]
Tried several different versions of clang-format, it looks like clang-format installed through `Ubuntu 16.04` almost matches the behavior of `Experimental clang-format Check`. except that the following line
```
#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
```
will be moved and sorted in `clang-format -i --style=Google`, while `Experimental clang-format Check` will keep the above line at the beginning of the included headers.

I remember placing `unsupported/Eigen/CXX11/Tensor` was intentional and had a discussion before (with vrv?). Did a search but couldn't find the discussion and related PR though.

**Comment by martinwicke** [comment]
@yongtang I'll pull this in and hope for the best.

@yifeif This is the dreaded lint problem. Which version of clang-format are we using exactly?

**Comment by yifeif** [comment]
We are using 3.9 with -style=google in `Experimental clang-format Check`. We can add this information to the failure log in addition to the diff. @martinwicke pulling should be okay.

**Pull request merged**
