### PR TITLE
Documentation - Fixing 'if' spelling

### PR DESCRIPTION
**Pull request by rajendraarora16**
Fixing 'if' spelling

### CODE REVIEW

**Comment by rajendraarora16** [comment]
I signed it!

**Comment by rajendraarora16** [comment]
@googlebot please recheck!

**Comment by rajendraarora16** [comment]
@googlebot Please check CLA

**Comment by MikulasZelinka** [comment]
"Iff" is a shortcut for "if and only if", meaning the original spelling is likely intended.

https://en.wikipedia.org/wiki/If_and_only_if

**Pull request closed without merging**
