### PR TITLE
Add qint8 and qint16 support for FillOp

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to address the issue raised in https://github.com/tensorflow/tensorflow/issues/26069#issuecomment-658767837 where
qint8 and qint16 were not supported for FillOp.

This PR add qint8 and qint16 support for FillOp.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
Can you make the test also test in eager mode?

Also, we are seeing the following error, both in graph mode and in eager mode (removing the session related parts of the test):

```
Traceback (most recent call last):
  File ".../tensorflow/python/framework/tensor_util.py", line 331, in _AssertCompatible
    fn(values)
  File ".../tensorflow/python/framework/tensor_util.py", line 257, in _check_quantized
    _check_failed(values)
  File ".../tensorflow/python/framework/tensor_util.py", line 251, in _check_failed
    raise ValueError(v)
ValueError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<embedded stdlib>/unittest/case.py", line 59, in testPartExecutor
    yield
  File "<embedded stdlib>/unittest/case.py", line 605, in run
    testMethod()
  File ".../tensorflow/python/kernel_tests/constant_op_test.py", line 463, in testQintDtype
    z = array_ops.zeros([2, 3], dtype=dtype)
  File ".../tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File ".../tensorflow/python/ops/array_ops.py", line 2769, in wrapped
    tensor = fun(*args, **kwargs)
  File ".../tensorflow/python/ops/array_ops.py", line 2828, in zeros
    output = fill(shape, constant(zero, dtype=dtype), name=name)
  File ".../tensorflow/python/framework/constant_op.py", line 266, in constant
    allow_broadcast=True)
  File ".../tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File ".../tensorflow/python/framework/tensor_util.py", line 458, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File ".../tensorflow/python/framework/tensor_util.py", line 338, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected qint8, got 0 of type 'int' instead.
```

**Comment by yongtang** [comment]
Thanks @mihaimaruseac , the PR has been updated with session part removed. Also, I casts the qint types to int32 type before comparing it with numpy. Think this will resolve the error raised. Please take a look and let me know if the issue still persists.

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
This still fails internally

```
Traceback (most recent call last):
  File ".../tensorflow/python/framework/tensor_util.py", line 331, in _AssertCompatible
    fn(values)
  File ".../tensorflow/python/framework/tensor_util.py", line 257, in _check_quantized
    _check_failed(values)
  File ".../tensorflow/python/framework/tensor_util.py", line 251, in _check_failed
    raise ValueError(v)
ValueError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<embedded stdlib>/unittest/case.py", line 59, in testPartExecutor
    yield
  File "<embedded stdlib>/unittest/case.py", line 605, in run
    testMethod()
  File ".../tensorflow/python/kernel_tests/constant_op_test.py", line 463, in testQintDtype
    z = array_ops.zeros([2, 3], dtype=dtype)
  File ".../tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File ".../tensorflow/python/ops/array_ops.py", line 2769, in wrapped
    tensor = fun(*args, **kwargs)
  File ".../tensorflow/python/ops/array_ops.py", line 2828, in zeros
    output = fill(shape, constant(zero, dtype=dtype), name=name)
  File ".../tensorflow/python/framework/constant_op.py", line 266, in constant
    allow_broadcast=True)
  File ".../tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File ".../tensorflow/python/framework/tensor_util.py", line 458, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File ".../tensorflow/python/framework/tensor_util.py", line 338, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected qint8, got 0 of type 'int' instead.
```

**Comment by gbaned** [comment]
@yongtang Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Comment by yongtang** [comment]
@mihaimaruseac @gbaned I think I finally figured out the error thrown out during the internal test. The message is caused by `tf.qint8`'s `zero` could not use `0` directly as `0` is incompatible with tf.qint8. Instead I used the np.zeros and casted to tf.qint8 ()changed the following line:
```
+    elif dtype.is_quantized:
+      zero = np.zeros([]).astype(dtype.as_numpy_dtype)
```

The different is that qint8 is actually an `i1` object not an int in np:
```
>>> np.zeros([]).astype(tf.qint8.as_numpy_dtype)
array((0,), dtype=[('qint8', 'i1')])
```

I have updated the PR and believe the issue should have been resolved. 

Please give it another try and let me know if there are still any issues.

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by yongtang** [comment]
@mihaimaruseac Another issue that is different, but similar to the internal test failure above is the `tf.ones` with quantized dtype. As they are not essential to this PR, I have created a separate PR #41603 with different test cases.

**Comment by mihaimaruseac** [comment]
Different failure now

```
  File ".../tensorflow/python/framework/fast_tensor_util.pyx", line 97, in fast_tensor_util.AppendInt8ArrayToTensorProto
ValueError: Buffer dtype mismatch, expected 'int8_t' but got 'short'
```

**Comment by yongtang** [comment]
Thanks @mihaimaruseac for the help. I think this is likely caused by dtype being reused (or graph being reused) in the internal test. I have split the tests into two to avoid this. The PR has been updated, I assume it will fix the error.

Please give another try and sorry for taking that long.

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
Thank you for the prompt response and sorry that the mismatch between internal and open source tests makes this harder to merge.

**Comment by mihaimaruseac** [comment]
`//tensorflow/python/kernel_tests:constant_op_test` still fails :(

```
Traceback (most recent call last):
  File "<embedded stdlib>/unittest/case.py", line 59, in testPartExecutor
    yield
  File "<embedded stdlib>/unittest/case.py", line 605, in run
    testMethod()
  File ".../tensorflow/python/kernel_tests/constant_op_test.py", line 471, in testQint16Dtype
    z = array_ops.zeros([2, 3], dtype=dtype)
  File ".../tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File ".../tensorflow/python/ops/array_ops.py", line 2769, in wrapped
    tensor = fun(*args, **kwargs)
  File ".../tensorflow/python/ops/array_ops.py", line 2830, in zeros
    output = fill(shape, constant(zero, dtype=dtype), name=name)
  File ".../tensorflow/python/framework/constant_op.py", line 266, in constant
    allow_broadcast=True)
  File ".../tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File ".../tensorflow/python/framework/tensor_util.py", line 565, in make_tensor_proto
    append_fn(tensor_proto, proto_values)
  File ".../tensorflow/python/framework/fast_tensor_util.pyx", line 97, in fast_tensor_util.AppendInt8ArrayToTensorProto
ValueError: Buffer dtype mismatch, expected 'int8_t' but got 'short'
```

**Comment by yongtang** [comment]
Thanks @mihaimaruseac. I think the error is caused by the incorrect mapping of fast tensor <=> np which appear to be a bug unrelated. I have created a PR #41677 to address it.

**Comment by yongtang** [comment]
@mihaimaruseac With PR #41677 merged in, I have rebased and updated this PR. I think the internal test issue likely have been solved. Can you give it a try? Thanks a lot for the help in the process.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
