### PR TITLE
Closes #8165 -- Removing traces of os_setup.md

### LINKED ISSUE #8165: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md 404
rt, 404 error of link from readme, Download and Setup

### PR DESCRIPTION
**Pull request by MicaelCarvalho**

### CODE REVIEW

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Review by caisq — APPROVED** [review]

**Comment by caisq** [comment]
@josh11b, i'm not entirely sure whether it makes more sense to link to the website or files under docs_src. Adding you as a reviewer.

**Comment by dandelionmane** [comment]
I don't think the link should point to tensorflow.org directly - I think it should use a relative path. @josh11b can you comment?

**Comment by MicaelCarvalho** [comment]
I agree it should have relative links. Hold on, I'm updating files and will let you know as soon as it's OK (the last commit has a broken link).

**Comment by josh11b** [comment]
@dandelionmane We don't want links to docs_src -- they are source files and are not necessarily readable.  tensorflow.org is the source of truth for docs and should be the target of links.  The main exception is if you are modifying something in docs_src or in a comment that will end up in the API docs, then you should use the new @{...} syntax (described in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/g3doc ) for links when possible.

**Comment by MicaelCarvalho** [comment]
@josh11b I believe anyone seeing the README file would have a Markdown interpreter, no? Unless they're reading in plain text, then it's safe to assume they will be able to follow links by themselves.

Relative links will alow users who have an offline copy to continue working, reading their copies of the docs, instead of going online to find the same resource.

**Comment by josh11b** [comment]
The files in docs_src/ will have lots of problems being rendered by a Markdown interpreter, since we have our own syntax (@{...}) for internal links that requires a preprocessing step to be made useful.

**Comment by MicaelCarvalho** [comment]
I see... On a side note, even after this PR there are still 38 references in 16 files to g3doc, they should eventually be fixed as well.

Should I retreat the last commit with relative links?

**Comment by josh11b** [comment]
Yes please, retreat the last commit

**Comment by MicaelCarvalho** [comment]
@josh11b done. ;)

**Comment by dandelionmane** [comment]
Cool, merging it then. Thanks for the fix.

**Pull request merged**
