### PR TITLE
ReduceMax/ReduceMin, int8 quantization.

### PR DESCRIPTION
**Pull request by wwwind**
Added int8 quantization for ReduceMax/ReduceMin.

This PR addressed this issue: https://github.com/tensorflow/tensorflow/issues/39601

### CODE REVIEW

**Review by talumbau — COMMENTED** [review]
Thanks for this change! This looks correct AFAICT but it would be great to have an example of a fully model that benefits from this change. Do you have such an example model?

**Comment by wwwind** [comment]
Hi @talumbau Yes, this change has been used to quantize the real model, but, unfortunately, I can't share it due to IP. I run op_tests for reduce op and they were green.
Is there any other places where I can add some tests for quantization ?
I see tests in quantize_model_test.cc, but it looks they are for the different purpose.

**Comment by talumbau** [comment]
Consulted with another team member and the op_test addition is sufficient. Thanks!

**Review by talumbau — APPROVED** [review]

**Comment by talumbau** [comment]
Looks like this PR fails a number of tests. For example:

`bazel  test --compilation_mode=opt //third_party/tensorflow/lite/testing:zip_test_reduce_max`

as well as the `zip_test_reduce_min` in the same directory. The equivalent tests over the in `lite/experimental/mlir/testing` also fail, e.g. `tensorflow/lite/experimental/mlir/testing:zip_test_reduce_max`. If you can dig in to why these fail and resolve, we can move forward with merging.

**Comment by wwwind** [comment]
@talumbau Thanks! I will take a look

**Comment by karimnosseir** [comment]
This should be no longer needed. A fix has been sent. Please reopen if there is still a need

**Pull request closed without merging**
