### PR TITLE
Add TensorFlow MicroLite Support for the OpenMV Cam

### PR DESCRIPTION
**Pull request by kwagyeman**
Really simple.

### CODE REVIEW

**Comment by gbaned** [comment]
@kwagyeman thank you for your contribution, please sign CLA.

**Comment by kwagyeman** [comment]
I did. It's signed.

**Comment by kwagyeman** [comment]
@googlebot I signed it!

**Review by petewarden — DISMISSED** [review]

**Comment by gbaned** [comment]
@kwagyeman Can you please resolve conflicts? Thanks!

**Review by petewarden — DISMISSED** [review]
Thanks for your changes, and your patience with the long review time!

**Comment by kwagyeman** [comment]
Can this get merged anytime soon?

**Comment by gbaned** [comment]
@petewarden  Can you please take a look at this? Thanks!

**Comment by gbaned** [comment]
@kwagyeman Can you please resolve conflicts? Thanks!

**Comment by kwagyeman** [comment]
Fixed! Can you guys merge this please. When you sit on it the build just breaks randomly.

**Comment by kwagyeman** [comment]
Can you guys merge this? You've sat on it for so long.

**Comment by kwagyeman** [comment]
It's literally 1 file being added now. No changes...

**Review by petewarden — APPROVED** [review]

**Review by petewarden — APPROVED** [review]

**Pull request merged**
