### PR TITLE
Fix expand_dims of dim argument has been deprecated with axis

### PR DESCRIPTION
**Pull request by imsheridan**
This PR is to fix tf.expand_dims of dim argument has been deprecated with axis.

As we can see from [array_ops.expand_dims#L147](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py#L147), the dim argument of array_ops.expand_dims has been deprecated and in favor of axis.

Besides, we can see from [tf.expand_dims](https://www.tensorflow.org/api_docs/python/tf/expand_dims) as below: axis/ dim should be scalar type instead of list/ tuple.
image

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 36 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 51 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 81 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 96 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 111 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 126 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 141 days with no activity and the `awaiting review` label has been applied.

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
thank you!

**Comment by martinwicke** [comment]
A conflict has crept in (sorry this took so long!), could you rebase/fix?

**Review by ispirmustafa — APPROVED** [review]
Thank you!

**Pull request merged**
