### PR TITLE
Add Tan, Asin, Acos, Atan trigonometric functions. See #1108

### PR DESCRIPTION
**Pull request by Mistobaan**
This branch was previously in https://github.com/tensorflow/tensorflow/pull/1124 but for some reason (most likely a bad force push on my repo) was permanently closed.

### CODE REVIEW

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
Looks like one small test failure for tan -- can you fix and verify?  Otherwise looking good!

**Comment by yaroslavvb** [comment]
@Mistobaan -- I see other people requesting it, this would be a useful addition

**Comment by gunan** [comment]
Can one of the admins verify this patch?

**Comment by ebrevdo** [comment]
Can you fix cwise_op_test failures?

```
INFO: From Testing //tensorflow/python:cwise_ops_test (shard 2 of 2):
==================== Test output for //tensorflow/python:cwise_ops_test (shard 2 of 2):
.............................................................F...
======================================================================
FAIL: testComplex64Basic (__main__.UnaryOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-fastbuild/bin/tensorflow/python/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 250, in testComplex64Basic
    self._compareCpu(x, np.tan, tf.tan)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-fastbuild/bin/tensorflow/python/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 75, in _compareCpu
    self.assertAllClose(jacob_t, jacob_n, rtol=1e-3, atol=1e-3)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-fastbuild/bin/tensorflow/python/cwise_ops_test.runfiles/tensorflow/python/framework/test_util.py", line 431, in assertAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=0.001

(mismatch 100.0%)
 x: array([[ 0.00947874,  0.00274417,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],...
 y: array([[ 0.00947807, -0.00274181,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],...

----------------------------------------------------------------------
Ran 65 tests in 197.312s
```

**Comment by ebrevdo** [comment]
It's a strange failure, let's retry the test.

@tensorflow-jenkins can you test this please?

**Comment by Mistobaan** [comment]
@vrv @ebrevdo 

I spent quite a bit of time but I couldn't figure out why the complex64 atan function was failing. As you see from the output  seems that the problem is a sign in the second element. 
To move this patch forward and prevent from falling behind master I removed the complex64 support from atan for now. What do you think ?

**Comment by Mistobaan** [comment]
ping

**Comment by vrv** [comment]
the branch currently has conflicts, and yes, removing complex64 support for now is fine -- just leave a comment saying something was broken when you tried it, so others can pick up from where you left off.

**Comment by Mistobaan** [comment]
@vrv rebased

**Comment by Mistobaan** [comment]
@ebrevdo @yaroslavvb can one of you run the tests on this patch and see if we can merge it ?

**Comment by mrry** [comment]
@tensorflow-jenkins, test this please.

**Comment by Mistobaan** [comment]
@mrry  did the test run ?

**Comment by mrry** [comment]
@Mistobaan: ...apparently not. @caisq, @ebrevdo, @martinwicke: can one of you please kick off the tests?

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by ebrevdo** [comment]
Still seeing errors for complex64, and also for float16.

**Comment by ebrevdo** [comment]
Search the [console log](http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/890/console) for the string `ERROR:`

**Comment by vrv** [comment]
If you can, please fix the tests and make sure you verify they are fixed via bazel test tensorflow/python:cwise_ops_test

**Comment by Mistobaan** [comment]
Yes I am trying to test on my local machine, but something has changed that is failing with different errors like: `undefined symbol: _ZN10tensorflow7functor12UnaryFunctorIN5Eigen9GpuDeviceENS0_4asinIdEEEclERKS3_NS2_9TensorMapINS2_6TensorIdLi1ELi1ElEELi16EEENS9_INSA_IKdLi1ELi1ElEELi16EEE`

**Comment by vrv** [comment]
Probably becaues you aren't compiling any GPU code.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_gpu_abs.cu.cc -- no equivalent file exists

**Comment by Mistobaan** [comment]
The updated patch is compiling and passing all the tests with cuda on my local machine.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
