### PR TITLE
Disable flaky cwise_ops_test due to broken acosh on windows.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Review by drpngx — APPROVED** [review]

**Comment by guschmue** [comment]
I think this started  6/28 and I see a few other tests failing on windows around the same time. 
Can take a look if we can fix the root cause.

**Comment by drpngx** [comment]
Thanks! The cosh was introduced this week. I can find the pointer tomorrow

On Jul 2, 2017 10:37 PM, "Guenther Schmuelling" <notifications@github.com>
wrote:

I think this started 6/28 and I see a few other tests failing on windows
around the same time.
Can take a look if we can fix the root cause.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/pull/11213#issuecomment-312553315>,
or mute the thread

**Comment by gunan** [comment]
I have root caused the problem to https://github.com/tensorflow/tensorflow/pull/10598
However, as this was blocking most submissions, I have elected to disable the test.
I am happy to quickly reenable it once we have a fix for acosh.
Also, @guschmue any input on the discussion about what maybe wrong with acosh is welcome!

**Comment by guschmue** [comment]
Ah, makes perfect sense.

**Pull request merged**
