### PR TITLE
accelerate crf_log_norm

### PR DESCRIPTION
**Pull request by wanguanglu**
the base `crf_log_norm` function looks very cool, but it runs very slow.
I run the experiment on cpu
```
model name  : Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
```

I use the configure
```python
batch_size=128
max_seq_len=200
```
it runs `0.5s` per batch

when I optimize the realization way
it  runs `0.25s` per batch

### CODE REVIEW

**Comment by wanguanglu** [comment]
I don't know why, when I sign the cla, it occurs.
A server error occurred, please try your request again.
* required fields

**Comment by wanguanglu** [comment]
I don't know why, I can't sign in the google cla. I think there is some mistake with the google cla server.

**Comment by vrv** [comment]
Check the email on your git commits matches the email you signed the CLA with.

**Comment by wanguanglu** [comment]
I meet problem when sign in google cla.
it always

A server error occurred, please try your request again.

and when i try again, the error again.
I don't know who can fix it.

**Comment by Mistobaan** [comment]
are you behind some sort of proxy ?

**Comment by wanguanglu** [comment]
I signed it

**Comment by wanguanglu** [comment]
yes, Because I am in China, I must use proxy to visit Google.
I fix it by change another net envirenment

**Comment by wanguanglu** [comment]
I signed it!

**Pull request closed without merging**
