### PR TITLE
Fix a bug of model_to_dot()

### LINKED ISSUE #14542: 'Model' object has no attribute 'container_nodes'
## Problem
```python
model = tf.keras.models.Model()
model.add(...)
tf.keras.utils.plot_model(model, to_file="model.png")
```
Output:
```
Traceback (most recent call last):
  File "model.py", line 36, in <module>
    K.utils.plot_model(model, to_file="model.png")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/utils/vis_utils.py", line 148, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/utils/vis_utils.py", line 123, in model_to_dot
    if node_key in model.container_nodes:
AttributeError: 'Model' object has no attribute 'container_nodes'
```

## Environment
-System: Ubuntu 16.04
-Tensorflow-gpu bin v1.4.0-rc1-11-g130a514 1.4.0

### PR DESCRIPTION
**Pull request by qmick**
This patch fixes #14542

### CODE REVIEW

**Review by inc0 — APPROVED** [review]

**Review by fchollet — APPROVED** [review]
LGTM

**Comment by garrettargenna** [comment]
It appears this issue was re-introduced in [commit](https://github.com/tensorflow/tensorflow/commit/0bd0bf02aa15a3238b77053a2f0ad6fe373c7d1c#diff-2391fd575f61ea7e3cf589012305ad36)

**Comment by garrettargenna** [comment]
I unfortunately am not allowed to push/pull to github from where I'm located. But the fix is simply to redo the one line replacement in this pull request. 
Replace line 122:
if node_key in model.container_nodes: 
with:
if node_key in model._network_nodes:  # pylint: disable=protected-access

**Comment by qmick** [comment]
@garrettargenna Thanks for the information, seems @sibyjackgrove will work on it.

**Pull request merged**
