### PR TITLE
Fix inline if/else statement in CMAKE_CACHE_ARGS

### PR DESCRIPTION
**Pull request by kaspermarstal**
An if/else statement was given inline as an argument to CMAKE_CACHE_ARGS for some CMake external projects as discussed in #15209. This resulted in the following init cache entries on some systems:

```
set(CMAKE_POSITION_INDEPENDENT_CODE "ON;if(;tensorflow_ENABLE_POSITION_INDEPENDENT_CODE;);else;(;)"CACHE BOOL "Initial cache" FORCE)
set(CMAKE_POSITION_INDEPENDENT_CODE "OFF;endif;(;)" CACHEBOOL "Initial cache" FORCE)
```
This commit changes the inline if/else arguments to -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=${tensorflow_ENABLE_POSITION_INDEPENDENT_CODE} which is functionality equivalent.

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by godrxz** [comment]
I will try this thanks @kaspermarstal

**Comment by godrxz** [comment]
Tested, thanks @kaspermarstal  you are right, worked for me !

**Comment by caisq** [comment]
Test failures are unrelated. Merging PR. Thanks @kaspermarstal

**Pull request merged**
