### PR TITLE
AddSign and PowerSign optimizers for contrib.opt

### PR DESCRIPTION
**Pull request by kdubovikov**
Added optimizers with update rules from https://arxiv.org/pdf/1709.07417.pdf

### CODE REVIEW

**Comment by kdubovikov** [comment]
I signed it!

**Comment by vrv** [comment]
Thanks @kdubovikov for this PR, and for your interest in the paper!

It's worth noting that Irwan (the paper author) is already mostly done with a change to add these optimizers to GitHub.  I would be happy to take this change, but it is complicated due to the fact that most of our supported optimizers require C++ fused implementations for speed and distributed training reasons.

Given that this work is almost done, would you be okay if we closed this PR in favor of the C++ version that is coming soon?

**Comment by kdubovikov** [comment]
Hi! Great news! I thought to develop C++ code later, but it’s clear that the author of the paper will manage this perfectly. Hope I’ll implement something more useful further along

**Comment by vrv** [comment]
Great, I'll close it for now, but if we can't get the C++ changes in by the end of the month, I'll reopen.

**Pull request closed without merging**
