### PR TITLE
Delete Dockerfile.custom_op

### PR DESCRIPTION
**Pull request by bhack**
/cc @yifeif

### CODE REVIEW

**Review by yifeif — APPROVED** [review]
Thank you!

**Comment by bhack** [comment]
@rthadur  Can you invoke kokoro?

**Comment by rthadur** [comment]
@bhack changes have been merged internally , waiting for auto-merge to happen.

**Comment by bhack** [comment]
@rthadur Is  `MacOS Python2 and CC`  broken?

**Pull request merged**
