### PR TITLE
Changed subgraph_test_util to control_flow_test_util

### PR DESCRIPTION
**Pull request by joyalbin**

### CODE REVIEW

**Comment by joyalbin** [comment]
@yenchenlin I have done this modification based on " TODO(ycling): This file should be renamed as `control_flow_test_util` to avoid confusion.", could you please review this PR

**Comment by joyalbin** [comment]
miaout17 Could you please review and approve this PR?

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@joyalbin  Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 44 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
