### PR TITLE
Add tf.contrib.data.LMDBDataset support

### LINKED ISSUE #21129: Feature request: Add a `LMDBDataset` class, that inherits from `tf.data.Dataset`.
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
N/A
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
N/A
- **TensorFlow installed from (source or binary)**:
N/A
- **TensorFlow version (use command below)**:
1.9
- **Python version**:
3.6
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
N/A

### Describe the problem

**Feature request: Add a `LMDBDataset` class, that inherits from `tf.data.Dataset`.**
Currently TF only supports LMDB datasets with the method [`LMDBReader`](https://www.tensorflow.org/api_docs/python/tf/LMDBReader). Implementing a `LMDBDataset` class that inherits from `tf.data.Dataset` will allow users to load LMDB data with the friendly tf.data API, and also use [`tf.contrib.data.make_batched_features_dataset`](https://www.tensorflow.org/api_docs/python/tf/contrib/data/make_batched_features_dataset), which applies the most up-to-data performance optimization for loading data.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #21129 where
there was no LMDBDataset support (only LMDBReader).

This fix fixes #21129.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by caisq** [comment]
tentatively assigning this to @jhseu

**Comment by jhseu** [comment]
Derek, thoughts on tf.contrib.data or tf.data for this? We already have LMDBReader in TensorFlow because it's a common format used with Caffe.

**Review by mrry — CHANGES_REQUESTED** [review]
Note on binary file "tensorflow/contrib/lmdb/python/kernel_tests/testdata/data.mdb": There is already a test LMDB file in "tensorflow/core/lib/lmdb/testdata/data.mdb", so please use that file instead of adding a new blob to the repository.

**Comment by yongtang** [comment]
Thanks @mrry for the review. The PR has been reworked and now LMDBDataset is exposed through `tf.contrib.data`. The binary file `data.mdb` has also been removed. I take a look at the mdb library but couldn't find an easy way to pass different stream than filename. Please take a look.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by mrry — DISMISSED** [review]

**Pull request merged**
