### PR TITLE
Turn check_futures_test into a sanity check

### PR DESCRIPTION
**Pull request by Androbin**
See https://github.com/tensorflow/tensorflow/pull/15368#issuecomment-354156560 for reference.
@gunan @martinwicke /cc

### CODE REVIEW

**Comment by drpngx** [comment]
Could you check your script?

```
=== Sanity check step 3 of 11: do_check_futures_test (Check that python files have certain __future__ imports) ===

Traceback (most recent call last):
  File "check_futures_test.py", line 107, in <module>
    main()
  File "check_futures_test.py", line 90, in main
    BASE_DIR)
AssertionError: BASE_DIR = '../..' doesn't end with tensorflow
```

**Comment by Androbin** [comment]
Good catch, `os.path.normpath` depends on the working directory.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by Androbin** [comment]
@drpngx Seems like the Ubuntu CC test didn't finish but the Sanity Checks succeeded.
Since the latter should be the only ones expected to fail, this should be safe to merge.

**Comment by drpngx** [comment]
Yes, the build is stuck today. We'll have to wait a bit.

**Comment by Androbin** [comment]
@drpngx Could you try restarting the build for this one?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Oh, I think it's good. Ubuntu CC moved to kokoro, I think, so the build is good. Waiting for review.

**Comment by Androbin** [comment]
@gunan Same thing as with #15677?

**Comment by Androbin** [comment]
@martinwicke Friendly ping.

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Looks good to me. @gunan unless you object violently and soon.

**Comment by rmlarsen** [comment]
@Androbin Please resolve conflicts.

**Comment by Androbin** [comment]
@rmlarsen Conflicts resolved.

**Comment by martinwicke** [comment]
Almost there! Thanks!

**Pull request merged**
