### PR TITLE
Gradient doc changed to accurately show the returned params

### PR DESCRIPTION
**Pull request by ashutosh1919**
This PR resolves the issue #35628. The two places where there were descriptions about returned params were inconsistent. I have made them consistent w.r.t. code.

### CODE REVIEW

**Comment by sharvil** [comment]
Thanks for taking this on, @ashutosh1919. The documentation still isn't quite clear to me. The summation notation is ambiguous since it doesn't specify which axis is being reduced. Personally, I think the whole phrasing of "...where each tensor is the `sum(ys/xs)`..." needs to be replaced with something more clear.

A snippet of code or a concrete example would also help.

**Comment by ashutosh1919** [comment]
> Thanks for taking this on, @ashutosh1919. The documentation still isn't quite clear to me. The summation notation is ambiguous since it doesn't specify which axis is being reduced. Personally, I think the whole phrasing of "...where each tensor is the `sum(ys/xs)`..." needs to be replaced with something more clear.
> 
> A snippet of code or a concrete example would also help.

@sharvil , I have added an example for illustration. I think that example illustrates everything with which you can understand the function easily.

**Comment by sharvil** [comment]
Thanks, this looks reasonable to me. I'll leave it to the TF team to get it merged in. Thanks again, @ashutosh1919.

**Comment by ashutosh1919** [comment]
> Thanks, this looks reasonable to me. I'll leave it to the TF team to get it merged in. Thanks again, @ashutosh1919.

@sharvil now has a clear understanding on the gradient doc. So, I request @alextp to review this PR.

**Review by alextp — DISMISSED** [review]

**Review by alextp — APPROVED** [review]

**Pull request merged**
