### PR TITLE
Multi-Stream: add options in protobuf

### PR DESCRIPTION
**Pull request by buptzyb**
This PR works as a part of the whole Multi-Stream feature in TF, which is proposed in #61185.

Two fields (stream_merge_options & multi_stream_options) are added to "config.proto" to provide the entrance for related features.

@changhuilin

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @chuanhaozhuge Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @chuanhaozhuge Can you please review this PR ? Thank you!

**Comment by chuanhaozhuge** [comment]
> Hi @chuanhaozhuge Can you please review this PR ? Thank you!

removed myself from reviewer list since I no longer work with the team.

**Comment by gbaned** [comment]
Hi @sagunb Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sagunb Can you please review this PR ? Thank you!

**Pull request closed without merging**
