### PR TITLE
replaced inception file with v3

### PR DESCRIPTION
**Pull request by ghego**
This is to fix issue #5007

### CODE REVIEW

**Comment by petewarden** [comment]
Can you verify that the process documented in the codelab at codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html still works with this change? I'm a bit surprised we don't need to change any of the layer names for example, but it may be that the naming is the same.

**Comment by ghego** [comment]
Ok, will verify that

**Comment by ghego** [comment]
@petewarden This week I won't have time to check that https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html#0 still works. If anyone wants to step up and do it sooner please feel free, otw I'll do it after Nov 1st

**Comment by vrv** [comment]
friendly ping

**Comment by rmlarsen** [comment]
friendly ping

**Comment by ghego** [comment]
@petewarden finally found some time to work on this. I rebased my branch to be updated with current master, checked out docker, pulled my branch (i.e. most recent commit on upstream + my commit of v3 inception) and followed the instructions at https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html#4.
Unfortunately this breaks because `tf.app.run` in v0.12 has `argv` param, and the docker file still has tensorflow binaries for v0.11, which doesn't have `argv`.

```bash
root@f313c94f7236:/tensorflow# python tensorflow/examples/image_retraining/retrain.py \
> --bottleneck_dir=/tf_files/bottlenecks \
> --how_many_training_steps 500 \
> --model_dir=/tf_files/inception \
> --output_graph=/tf_files/retrained_graph.pb \
> --output_labels=/tf_files/retrained_labels.txt \
> --image_dir /tf_files/flower_photos

Traceback (most recent call last):
  File "tensorflow/examples/image_retraining/retrain.py", line 1012, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
TypeError: run() got an unexpected keyword argument 'argv'
```

how do you suggest to proceed?

**Comment by ghego** [comment]
Tested it on `r0.12rc0`. It fails because the content of the zip file is different from the previous one. Here's the error:

```
>> Downloading inception-v3-2016-03-01.tar.gz 100.0%
Successfully downloaded inception-v3-2016-03-01.tar.gz 399307177 bytes.
Traceback (most recent call last):
  File "tensorflow/examples/image_retraining/retrain.py", line 1012, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/image_retraining/retrain.py", line 753, in main
    create_inception_graph())
  File "tensorflow/examples/image_retraining/retrain.py", line 260, in create_inception_graph
    graph_def.ParseFromString(f.read())
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 106, in read
    self._preread_check()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 73, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /tf_files/inception/classify_image_graph_def.pb
```

Here's the content of `inception-2015-12-05`:
```
classify_image_graph_def.pb
cropped_panda.jpg
imagenet_2012_challenge_label_map_proto.pbtxt
imagenet_synset_to_human_label_map.txt
LICENSE
```

while here's the content of  `inception-v3-2016-03-01`:

```
checkpoint
model.ckpt-157585
README.txt
```

I think the solution is to change the how the function `create_inception_graph` reloads the model, not sure how to fix it yet.

**Comment by martinwicke** [comment]
The new zip file doesn't contain the graph. I think the graph you need is the one in https://github.com/tensorflow/models/inception. 

As soon as feasible, we should migrate all these examples to use SavedModel, which would contain both the graph, the checkpoint, and also annotations to say which tensors to feed and fetch.

**Comment by drpngx** [comment]
@ghego could you merge conflicts and push again?

**Comment by drpngx** [comment]
Close due to inactivity. Please read Martin's comment for requested updates. Thanks.

**Pull request closed without merging**
