### PR TITLE
Add missing "metrics_*.py" modules to tflite_runtime bazel build script

### PR DESCRIPTION
**Pull request by avroshk**
Fix for #49198 

## Steps to reproduce 
* https://github.com/avroshk/build-tflite-runtime 

## Test fix 
* https://github.com/avroshk/build-tflite-runtime/tree/fix

### CODE REVIEW

**Comment by avroshk** [comment]
@googlebot I signed it!

**Review by bhack — APPROVED** [review]
To run kokoro

**Comment by abattery** [comment]
@yyoon coud you review this PR?

**Comment by yyoon** [comment]
Thanks for creating this fix!

I appreciate that this would probably fix the mentioned issue, but I suspect that this is caused by some missing dependency path within bazel BUILD files, and thus the metrics Python source files shouldn't need to be added like this directly in the shell script side.

I'll dig deeper and let you know where we should be fixing this. Thanks again!

**Comment by avroshk** [comment]
@yyoon Thanks for reviewing this. I did have a suspicion that my fix was too naive, :) please let me know if I can help with anything.

**Comment by yyoon** [comment]
@thaink Thai, could you take a look at this PR? As I investigate more about this, the fix in this PR might be the simplest solution. Otherwise, we'd need to re-implement the metrics portable / non-portable implementation in C++ and provide a python wrapper for them. But then, we already have `metrics_wrapper` package already which is used for a different purpose (exporting metrics) so it could be pretty cumbersome to workaround.

What do you think?

**Comment by thaink** [comment]
I am also supportive with this PR since it is consistent with existing build_pip_package.sh and build_pip_package_with_cmake.sh.

**Review by thaink — APPROVED** [review]

**Pull request merged**
