### PR TITLE
inception tutorial: added png to allowed extensions, made print statements clearer

### PR DESCRIPTION
**Pull request by pot0to**
something very minor. it'll probably save a couple people some headaches

### CODE REVIEW

**Comment by xxiane** [comment]
I signed it!

**Review by protoget — COMMENTED** [review]
In the graph we only call add_jpeg_decoding() for jpeg decoding. I'm not sure pngs are supported.

**Comment by xxiane** [comment]
Can we at least leave the print statement in there? It'd be an easier way to let people know that only jpegs are supported.

**Comment by protoget** [comment]
Sure, please make the change and I'll approve.

**Comment by xxiane** [comment]
Actually under `tensorflow/python/ops/gen_image_ops.py` in the version installed by pip3 I see a method with this signature:

```@tf_export('image.decode_png')
def decode_png(contents, channels=0, dtype=_dtypes.uint8, name=None):```

However, I'm not seeing that file in this repo. Do you know why that might be?

**Pull request closed without merging**
