### PR TITLE
Little change in tf.contrib.learn Quickstart tutorial

### PR DESCRIPTION
**Pull request by boing102**

### CODE REVIEW

**Comment by drpngx** [comment]
Can you elaborate why this is needed?

**Comment by boing102** [comment]
Because the tf.contrib.learn.datasets.base.load_csv_with_header function takes 3 arguments not only 2. I dont think the examples in those files work.

**Comment by drpngx** [comment]
Ah, thanks!
@jart is this still needed?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by vrv — APPROVED** [review]
This looks needed, since the third dtype is not optional.  APproving.

**Comment by vrv** [comment]
Can you rebase to deal with the conflict?

**Comment by boing102** [comment]
I used your guys' version as in tensorflow/master to resolve the conflict.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
