### PR TITLE
Added initial support to ROCm

### PR DESCRIPTION
**Pull request by aditya4d**
1. Changed configure to ask for enabling ROCm if XLA is enabled
2. Changed bazel.rc so that bazel config can take rocm as a value

### CODE REVIEW

**Comment by adityaatluri** [comment]
This pull request is for review only. Please don't merge.

**Comment by drpngx** [comment]
@adityaatluri Do we need to keep this PR around?

**Comment by adityaatluri** [comment]
Give me couple of days. Will let you know.

**Comment by drpngx** [comment]
Sounds good. Also, please make sure the CLA is in order. Thanks!

**Comment by adityaatluri** [comment]
The CLA is going to take a while. I'll create a new PR once I sign it.

**Pull request closed without merging**
