### PR TITLE
[TF_MICRO]  Adding cwrapper and compiler option example for building library

### PR DESCRIPTION
**Pull request by cdknorow**
- adding example cwrapper which generates the projects with simple api
- adding make library option to the makefile template
- make project have the compiler path defined setting
- adds a parser to pull out only the used ops from a tflite model

### CODE REVIEW

**Comment by cdknorow** [comment]
@googlebot I consent.

**Comment by petewarden** [comment]
Thanks @cdknorow! This is tackling an important issue for us, I've emailed you offline to discuss more about these changes.

**Comment by rthadur** [comment]
@petewarden gentle ping for any update ?

**Comment by gbaned** [comment]
@cdknorow  Can you please resolve conflicts? Thanks!

**Comment by petewarden** [comment]
Sorry for the long delay on this one @cdknorow - we've been taking a look at how to fit this in, and I'm not sure we're ready to take it yet. It does look useful, but would it be okay to keep this in your fork for now? I'm happy to do a quick followup call to chat more about our thinking on this, if that would be helpful, and thanks again for your patience.

**Pull request closed without merging**
