### PR TITLE
TfLite file close after usage generic fix

### PR DESCRIPTION
**Pull request by Dayananda-V**

### CODE REVIEW

**Comment by gbaned** [comment]
@achowdhery Can you please review this PR? Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @achowdhery: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@Dayananda-V  Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
