### PR TITLE
[Go] package go-gettable, update wrappers, fix tests

### PR DESCRIPTION
**Pull request by galeone**
Hi,

from several months, as documented by these issues:

- https://github.com/tensorflow/tensorflow/issues/39307
- https://github.com/tensorflow/tensorflow/issues/41808
- https://github.com/tensorflow/tensorflow/issues/35133

The simple process of `go get github.com/tensorflow/tensorflow/tensorflow/go` was not possible without errors.

This pull request solves this issue by committing the compiled .proto files to the expected location `tensorflow/go/core/framework/for_core_protos_go_proto/` in order to make the repo go-gettable again.

Moreover, I added a simple `.gitignore` in the `go` folder that ignores some common output/debugging files/folder.

I also fixed a failing test ` TestOperationAttrs` because the type assertion to `*tf.Tensor` was not always possible, and thus I had to move the `reflect.DeepEqual(out, want)` control.

**note** because of this bug of the Go compiler (https://github.com/golang/go/issues/42032) it's highly recommended to set the requirement for the Go language to be != 1.15.3 - otherwise the `(*Graph).Operations()` method fails, as I documented here: https://twitter.com/paolo_galeone/status/1324087418086215683

Moreover, I also committed the update generated wrappers (file op/wrappers.go) that contains the updated wrappers, in this way the package is ready to be go-gettable

### CODE REVIEW

**Review by frankchn — CHANGES_REQUESTED** [review]
Unfortunately, in general we don't allow generated protobuf files to be checked-in to the repository as the protos can change and this would be a maintenance issue. Do you know if there is an alternative to this?

**Comment by galeone** [comment]
> Unfortunately, in general we don't allow generated protobuf files to be checked-in to the repository as the protos can change and this would be a maintenance issue. Do you know if there is an alternative to this?

I guess it's not possible - or better, there is the option to clone the TensorFlow repository and do the protoc invocation manually - but this is not handy and more importantly, it doesn't solve the problem of go-getting the tensorflow package without errors.


However, the TensorFlow/Go package already suffers from this maintenance issue. For example, the op/wrappers.go file, is a generated file that must be manually updated and committed in order to have the correct (updated) wrappers for the C API.

So I guess since the Go package already works in this way, having the generated proto files committed in the repo doesn't change the maintenance issues, but at least gives to the users the possibility of go-getting the package

**Comment by frankchn** [comment]
Hey @jhseu would like your thoughts on this.

**Comment by jhseu** [comment]
Hmm, maybe in another repository. Definitely not in this repo. The main concern from the Go team was the conflicts between the bazel version and the go get version, but we don't expose the bazel version anyway.

I wonder if we should make tensorflow/go and make it the long-term home of the go bindings, and move the generated protos there?

Also, since this kind of change is difficult to review because of the generated code, I'd also rather we generate them here.

**Comment by galeone** [comment]
> Hmm, maybe in another repository. Definitely not in this repo. The main concern from the Go team was the conflict between the bazel version and the go get version, but we don't expose the bazel version anyway.
> 
> I wonder if we should make tensorflow/go and make it the long-term home of the go bindings, and move the generated protos there?
> 
> Also, since this kind of change is difficult to review because of the generated code, I'd also rather we generate them here.

I really like the idea of creating tensorflow/go and make it the home for the Go bindings :+1: 

Separating the go stuff from all the other TensorFlow stuff (the whole huge main repo, and so on) will make the Go part easier to maintain (and finally we could go-get the package without downloading several GB of repo :S) - but I do understand the concerns about the review of the generated code (or better, the possibility of misalignments between the tensorflow/go and tensorflow/tensorflow).

P.S: I don't know if you know my project tfgo (https://github.com/galeone/tfgo) but my project, and other projects that depend on the Go bindings, will benefit from having all the proto generated Go files in the same location together with the Go wrappers [if you look at the prerequisite section of the README.md of tfgo you'll understand why - I have to depend on a fork I have to maintain of TensorFlow, that has all the proto files compiled and available in the go folder)

**Comment by gbaned** [comment]
@jhseu Can you please take a look on the above comment from @galeone. Thanks!

**Comment by davorink** [comment]
Hey @gbaned and @jhseu, I was wondering if there was any progress in planning/thinking about moving generated go files to tensorflow/go; or some other officially-supported ways to make it go gettable without errors? Thanks!

**Comment by galeone** [comment]
> Hey @gbaned and @jhseu, I was wondering if there was any progress in planning/thinking about moving generated go files to tensorflow/go; or some other officially-supported ways to make it go gettable without errors? Thanks!

I maintain a fork: https://github.com/galeone/tensorflow

```
go get github.com/galeone/tensorflow/tensorflow/go@r2.4-go
```

You can also use `tfgo` that depends on the fork and it allows a simplified usage of the Go bindings:

```
go get github.com/galeone/tfgo
```

**Comment by gbaned** [comment]
@jhseu Any update on this PR? Please. Thanks!

**Comment by galeone** [comment]
> @jhseu Any update on this PR? Please. Thanks!

You can refer to my last comment to use a working solution :) https://github.com/tensorflow/tensorflow/pull/44655#issuecomment-779763454

**Comment by domino14** [comment]
@galeone you're awesome for doing this and I trust you, but it would still be ideal if the `go get` command that was specified in the README of this repo _actually worked_

**Comment by galeone** [comment]
> @galeone you're awesome for doing this and I trust you, but it would still be ideal if the `go get` command that was specified in the README of this repo _actually worked_.
> 
> Speaking of which, do you have 2.4.1 available?

Hi, and thank you for the kind words :smile: 

The go get command in the README of [galeone/tfgo](https://github.com/galeone/tfgo) works if you run it inside a new module (e.g. `go mod init`), followed by `go get github.com/galeone/tensorflow/tensorflow/go@r2.4-go`.

Otherwise, if you want it installed in your system, you have to go get the package (without the `@r2.4-go` since it's not possible to specify the version if you're not in a module) - it will fail, then you can move inside the repository, do a `git checkout r2.4-go` and it will work :)

The currently supported version *is* 2.4.0 - the only one you can download from the [Install TensoFlow for C](https://www.tensorflow.org/install/lang_c) page.

**Comment by wzzhu** [comment]
> > @galeone you're awesome for doing this and I trust you, but it would still be ideal if the `go get` command that was specified in the README of this repo _actually worked_.
> > Speaking of which, do you have 2.4.1 available?
> 
> Hi, and thank you for the kind words 😄
> 
> The go get command in the README of [galeone/tfgo](https://github.com/galeone/tfgo) works if you run it inside a new module (e.g. `go mod init`), followed by `go get github.com/galeone/tensorflow/tensorflow/go@r2.4-go`.
> 
> Otherwise, if you want it installed in your system, you have to go get the package (without the `@r2.4-go` since it's not possible to specify the version if you're not in a module) - it will fail, then you can move inside the repository, do a `git checkout r2.4-go` and it will work :)
> 
> The currently supported version _is_ 2.4.0 - the only one you can download from the [Install TensoFlow for C](https://www.tensorflow.org/install/lang_c) page.

The version is rather old. It doesn't contain some fixes from TensorFlow go team. e.g., https://github.com/tensorflow/tensorflow/commit/b6d5fa8ab6735880cbd1f501720450680345be98
As GitHub doesn't support a fork on fork, therefore it will only depends on the owner of the repo to import the updates to this repo.

A workaround is to git clone the whole tensorflow in local dir.
Run tensorflow/tensorflow/go/genop/generate.sh and then copy the pb files to their dir.
Then use the replace rule in go.mod to point own dir for gitHub.com/tensorflow/tensorflow
replace github.com/tensorflow/tensorflow/tensorflow/go => ../tensorflow/tensorflow/go
After this, you can build and run other code using tensorflow go package as usual.

**Comment by galeone** [comment]
> > > @galeone you're awesome for doing this and I trust you, but it would still be ideal if the `go get` command that was specified in the README of this repo _actually worked_.
> > > Speaking of which, do you have 2.4.1 available?
> > 
> > 
> > Hi, and thank you for the kind words smile
> > The go get command in the README of [galeone/tfgo](https://github.com/galeone/tfgo) works if you run it inside a new module (e.g. `go mod init`), followed by `go get github.com/galeone/tensorflow/tensorflow/go@r2.4-go`.
> > Otherwise, if you want it installed in your system, you have to go get the package (without the `@r2.4-go` since it's not possible to specify the version if you're not in a module) - it will fail, then you can move inside the repository, do a `git checkout r2.4-go` and it will work :)
> > The currently supported version _is_ 2.4.0 - the only one you can download from the [Install TensoFlow for C](https://www.tensorflow.org/install/lang_c) page.
> 
> The version is rather old. It doesn't contain some fixes from TensorFlow go team. e.g., [b6d5fa8](https://github.com/tensorflow/tensorflow/commit/b6d5fa8ab6735880cbd1f501720450680345be98)
> As GitHub doesn't support a fork on fork, it only depends on the owner of the repo to import the updates to this repo.
> 
> A workaround is to git clone the whole tensorflow in local dir.
> Run tensorflow/tensorflow/go/genop/generate.sh and then copy the pb files to their dir.
> Then use the replace rule in go.mod to point own dir for gitHub.com/tensorflow/tensorflow
> replace github.com/tensorflow/tensorflow/tensorflow/go => ../tensorflow/tensorflow/go
> After this, you can build and run other code using tensorflow go package as usual.

I'm going to update in the next few days the fork and the library - with the support for TensorFlow 2.5 since it's now been released

**Comment by gbaned** [comment]
@galeone  Any update on this PR? Please. Thanks!

**Comment by galeone** [comment]
> @galeone Any update on this PR? Please. Thanks!

I guess I can close this pull request, it makes no sense now.

I maintain a fork (galeone/tensorflow) that works with a simple `go get` and it's automatically downloaded when you use [tfgo](https://github.com/galeone/tfgo).
I recommend you to use this approach for using TensorFlow in Go - it's way easier.

**Comment by msama** [comment]
I would love to see any update on this one.
Pretty please :)

**Comment by galeone** [comment]
> I would love to see any update on this one. Pretty please :)

The pull request is closed, I have a fork of TensorFlow that is go-gettable and I recommend to use it instead of the official one. Moreover, you can also use tfgo that's a wrapper I built on top of it to simplify the usage of the Tensorflow's Go bindings: [tfgo](https://github.com/galeone/tfgo)

**Pull request closed without merging**
