### PR TITLE
Fix raising wrong exception.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by martinwicke** [comment]
Good catch. Clearly, this wasn't properly tested (that line never executed), could you add a unit test for the failure behavior?

**Comment by dongjoon-hyun** [comment]
Oh, in this case, I'm afraid that it might be too much work(lines) for this tiny error. :-)

By the way, is `Tensorflow` tested by any coverage test tool like `Coverity` now?

**Comment by martinwicke** [comment]
Not coverity, but we do measure coverage. It was around 96% or so last time I checked.

I'll merge this.

**Comment by dongjoon-hyun** [comment]
Thank you, @martinwicke !

**Pull request merged**
