### PR TITLE
Register GPU RefExit kernel

### PR DESCRIPTION
**Pull request by drasmuss**
It looks like the code was all set up to support a GPU kernel for `RefExit` (as was done for similar kernels, e.g. `RefEnter`), but `RefExit` was never actually registered for the GPU.  I'm not sure if it was intentionally left out for some reason, or if this was just an oversight.  All I did was add the registration calls and it appears to work.

### CODE REVIEW

**Comment by drasmuss** [comment]
The more general motivation for this change is that currently all loop Variables are pinned to the CPU, because they are colocated with the CPU-only `RefExit`.  This means that the Variables need to be transferred on and off the GPU every loop iteration.  Adding a GPU kernel for `RefExit` allows the whole loop to run on the GPU, which significantly improves performance.

**Comment by drasmuss** [comment]
Any updates on the review?  Normally I wouldn't push, but it'd be really nice to get this into the 1.2 release if possible, since it's a pretty significant performance bottleneck.  @ebrevdo might be able to quickly comment, since he wrote the GPU RefExit code.

**Review by ebrevdo — DISMISSED** [review]
this *seems* fine; though i think we'll have to run some internal tests to confirm no breakages.

you'll probably want to also register a GPU_HOST_REF_KERNEL for the RefExit.

**Comment by drasmuss** [comment]
I believe the GPU_HOST_REF_KERNEL is already being registered [here](https://github.com/drasmuss/tensorflow/blob/51a7b7be792139f0f35877f464b88c50f11190c8/tensorflow/core/kernels/control_flow_ops.cc#L445)

**Comment by drasmuss** [comment]
Are there any other changes you'd suggest @ebrevdo?

**Comment by ebrevdo** [comment]
No, I'm away this week so will ask someone else to review.

On Jun 13, 2017 7:29 AM, "Daniel Rasmussen" <notifications@github.com>
wrote:

Are there any other changes you'd suggest @ebrevdo
<https://github.com/ebrevdo>?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/pull/10174#issuecomment-308134751>,
or mute the thread

**Comment by martinwicke** [comment]
@keveman can you take a look?

**Review by keveman — APPROVED** [review]

**Comment by keveman** [comment]
@tensorflow-jenkins test this please

**Comment by gunan** [comment]
I have just ran all internal tests, and looks like this change does not cause any breakages internally.
It is safe to merge this PR.

**Pull request merged**
