### PR TITLE
Refactor methods for path calculation

### PR DESCRIPTION
**Pull request by Androbin**
This allows other scripts to access this logic.
@gunan This is what I meant.

### CODE REVIEW

**Comment by Androbin** [comment]
@gunan If you don't mind, this would really benefit #15166 and others.

**Comment by gunan** [comment]
This is an API change. @wicke will need to take a look.

**Comment by Androbin** [comment]
> This is an API change.

This is supposed to preserve the behaviour of `load_resource` while additionally providing `resource_path` to access the path resolution directly.

**Comment by gunan** [comment]
I do not see the need to expand the API with this, but I will let @wicke comment on that.
What does this new function offer that `get_root_dir_with_all_resources` won't offer?
Again, any paths you access has to be under the runfiles dir, as our testinfra will soon turn on sandboxing everywhere. This means after the test binaries are built, they will run on a completely isolated environment by themselves, without the rest of TF code. Sometimes they wont even be on the same machine with the rest of the TF source code.

**Comment by KingRando95** [comment]
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Androbin** [comment]
@gunan Yes, I'm well aware of the sandboxing methodology. I think we had a little misunderstanding on what I said about `runfiles`. Tried to clarify with [this comment](https://github.com/tensorflow/tensorflow/pull/15166#issuecomment-351448537).

It's just that #15166 needs the path resolution logic of `load_resource` except it needs one directory level higher. You said that I should use `resource_loader` so as not to have to maintain this logic twice. So I extracted this logic into `resource_path` which should be fine, no?

**Comment by Androbin** [comment]
@martinwicke What you say?

**Comment by martinwicke** [comment]
Can you regenerate the API golden files so we can verify what this change does on the API? You need Linux/Py2 for this, do you have access to that?

(@gunan, did you check whether we can run this on MacOS?)

**Comment by Androbin** [comment]
I am running Linux with Python 2 and 3.
You're probably referring to `//tensorflow/tools/api/generator:create_python_api`
Trying to figure out how to use it.

**Comment by martinwicke** [comment]
You generate it using the test which complains about it (the error message has instructions). See tools/api/tests/README.txt

**Comment by Androbin** [comment]
I built and ran `//tensorflow/tools/api/tests:api_compatibility_test` but it skips 2/4 tests:
```
s.s.
----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK (skipped=2)
```

**Comment by martinwicke** [comment]
You have to run this on linux/py2. Do you have access to such a system?

**Comment by martinwicke** [comment]
(Good to go from API review, but we need the API golden updated)

**Comment by Androbin** [comment]
As I said, Linux (Ubuntu 16.04.2) and both Python 2 (default) and Python 3.
Let me check that I am running the target with the correct version.

**Comment by Androbin** [comment]
Seems like bazel compiled with Python 3. Upon forcing Python 2 I realized that I had compiled TensorFlow for Python 3 only. Give me some time to recompile for Python 2 and try again.

**Comment by Androbin** [comment]
```
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
ERROR:tensorflow:TensorFlow API backwards compatibility test
This test ensures all changes to the public API of TensorFlow are intended.

If this test fails, it means a change has been made to the public API. Backwards
incompatible changes are not allowed. You can run the test as follows to update
test goldens and package them with your change.

    $ bazel build tensorflow/tools/api/tests:api_compatibility_test
    $ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test \
          --update_goldens True

You will need an API approval to make changes to the public TensorFlow API. This
includes additions to the API.

ERROR:tensorflow:1 differences found between API and golden.
ERROR:tensorflow:Issue 1	: Change detected in python object: tensorflow.resource_loader.
WARNING:tensorflow:Golden file update requested!
All test failures have been skipped, see the logs for detected diffs.
This test is now going to write new golden files.
Make sure to package the updates together with your change.

You will need an explicit API approval. This may take longer than a normal
review.

..WARNING:tensorflow:Unexpected hidden op name: ScaleImageGrad
WARNING:tensorflow:Unexpected hidden op name: MutexAcquire
WARNING:tensorflow:Unexpected hidden op name: TensorArrayPackV2
WARNING:tensorflow:Unexpected hidden op name: ReaderWorkQueueLengthV2
WARNING:tensorflow:Unexpected hidden op name: SparseSelectLastK
WARNING:tensorflow:Unexpected hidden op name: Mutex
WARNING:tensorflow:Unexpected hidden op name: TensorArrayPackV3
WARNING:tensorflow:Unexpected hidden op name: TensorArrayUnpackV3
WARNING:tensorflow:Unexpected hidden op name: ReaderWorkQueueLength
WARNING:tensorflow:Unexpected hidden op name: TensorArrayUnpackV2
WARNING:tensorflow:Unexpected hidden op name: MutexRelease
..
----------------------------------------------------------------------
Ran 4 tests in 4.100s

OK
```

**Comment by Androbin** [comment]
The bazel target worked now (with Python 2).
It updated the golden file as expected and I committed it.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by Androbin** [comment]
I've just realized that `__file__` actually resolves to the python installation instead of the `runfiles` directory like it used to when resolving `__file__` from the test script itself.

**Comment by Androbin** [comment]
Sorry @gunan, I think I owe you an apology. I think I wanted `get_path_to_datafile` the whole time.

**Comment by martinwicke** [comment]
Androbin given you comment (deleted?) did you need this function, or is the existing one enough?

**Comment by Androbin** [comment]
I've realized that this one malfunctions and that I can probably use an existing one.
But there is one thing left: Tests in #15166 need paths relative to **the parent of** `tensorflow/` which I can get using `os.pardir` but I'm wondering: Why isn't this the default anyway?

**Comment by Androbin** [comment]
@martinwicke I think `get_path_to_datafile` doesn't do what it's supposed to do either.

The documentation reads
> The path is relative to `tensorflow/`

But it gives me a path relative to the directory my script is located in.

**Comment by Androbin** [comment]
Other functions give me paths relative to `/usr/local/lib/python2.7/dist-packages/` which should not be intended either.

**Comment by Androbin** [comment]
* It's strange that these functions don't seem to do what their documentation say they do
* I will modify this PR to introduce a function I think is better suited for the intended use

**Comment by gunan** [comment]
The functions in this library are built to run when you are running the scripts via:
`bazel run ...` or `bazel test`. It is possible they do not work as intended when running without bazel.

**Comment by Androbin** [comment]
> It is possible they do not work as intended when running without bazel.

What about compiling with bazel and then running that?

**Comment by gunan** [comment]
While I would not count on it to work properly, for `api_compatibility_test` we did not have many problems so far.

**Comment by Androbin** [comment]
For what matters, I will modify this PR to include a function which is fail-safe for the use cases I can come up with. But still, I would expect at least `get_root_dir_with_all_resources` to find the `runfiles` directory. Maybe I can figure out why this method fails for me and fix it instead.

**Comment by Androbin** [comment]
I've rewritten the function to be more flexible. It should work for `load_resource` as well as it does for the intended use in PR #15166. Golden files were re-generated accordingly.

**Comment by Androbin** [comment]
@martinwicke You okay with this change?
@gunan FYI. I verified that this works for the other PR.

**Comment by Androbin** [comment]
> While I would not count on it to work properly, for `api_compatibility_test` we did not have many problems so far.

@gunan I think, I know what's going on. Those functions use `sys._getframe` which is sensitive to its position in the callstack. While this seems to work fine for `api_compatibility_test`, it's so unflexible that it breaks on any opportunity.

@martinwicke While the new functions don't work out of the box either, the parameters can easily be adjusted to match the respective use case.

**Comment by Androbin** [comment]
@yifeif Could you rerun the CI tests, please?

**Comment by jart** [comment]
AFAICT one of these functions will be used #15166 for test code, which needs to wrap the API. Test coverage could have helped spot that xrange needs to come from six. I haven't seen precedent in other libraries for this sort of API. Since the TensorFlow team makes strong long-term commitments to APIs, these sorts of changes are oftentimes hard to get in. This one seems unlikely to gain the support that's required.

**Comment by Androbin** [comment]
@jart I get your point, but:
* I can change `xrange` to `range` to get rid of `six`
* These methods should be useful for other tests and build code as well
* @gunan requested to de-duplicate this logic with `resource_loader`
* I can rewrite this to further reduce the maintenance costs

**Comment by jart** [comment]
I have no doubt Gunhan gave good advice. Please note that API introductions typically require multiple inputs and it's oftentimes necessary to see the actual change and use cases before they can be considered.

Speaking only for myself, I would feel most comfortable if this API was introduced because it made something possible that was not possible to do before. I also want to understand why the code that needs this API can't be written in a different way where it's no longer required.

**Comment by Androbin** [comment]
> I would feel most comfortable if this API was introduced because it made something possible that was not possible to do before

Like [I said earlier](https://github.com/tensorflow/tensorflow/pull/15315#issuecomment-353598678), the existing methods would work in theory, but the hard-coded value for the `sys._getframe` argument and the like make them very unflexible and malfunction for no good reason.

Would you be satisfied if `get_data_files_path` had a defaulted parameter for the hard-coded value, so that the logic could be shared with `get_root_dir_with_all_resources` and `get_path_to_datafile`?
And would you be okay if we keep `get_abs_path` with `get_path_root` merged into it?

**Comment by jart** [comment]
At Google, our engineering best practices guides urge us to write test code that is as simple and unfancy as possible. If I was in your shoes, I'd be asking myself, "What can I do to make this change as boring as possible?" Because sometimes it's the boring stuff that excites us.

**Comment by jart** [comment]
Please note I'm referring to your CMake test infrastructure change. Also note my 'nay' vote here shouldn't be interpreted as a lack of gratitude for the challenging task you've been kind enough to take on for the project.

**Comment by Androbin** [comment]
I really appreciate your advice. I've rewritten this PR to be more "boring":
* `get_grandparent(path, degree)` -> a files grandparent of the given degree
* `get_abs_data_path(path, depth, frame=0)` -> absolute path relative to a file upwards the callstack
* `get_data_files_path(frame=0)` -> no change in behavior, but is now shared with other methods

They should be about boring enough to be useful and to be shared.
This should resolve the issues I had with using `get_data_files_path` by making it less brittle.
And I think `get_abs_data_path` is how `get_path_to_datafile` should really look like.
Further thoughts on this are appreciated.

**Pull request closed without merging**
