### PR TITLE
Support all fp types in GPU SparseTensorDenseMatMul

### PR DESCRIPTION
**Pull request by benbarsdell**
Adds Eigen::half for CPU, and Eigen::half, double, and complex for GPU.

cc @nluehr

### CODE REVIEW

**Comment by benbarsdell** [comment]
I'm investigating the test failures.

**Comment by benbarsdell** [comment]
I've fixed the complex type test failures (I just missed https://github.com/tensorflow/tensorflow/pull/47355) and added support for float32 accumulation for float16 input/output, along with tests for float16.

**Review by allenlavoie — APPROVED** [review]
Ah, the unit tests were soft-placing onto the CPU previously? Looks good.

**Comment by benbarsdell** [comment]
The tests were running on the GPU, it was just that https://github.com/tensorflow/tensorflow/pull/47355 changed (fixed) the handling of complex conjugates (on CPU), and my local branch didn't have that commit.

**Comment by allenlavoie** [comment]
When we build internally I see a bunch of references to quiet_NaN not being supported for complex<float> and complex<double>:

```
third_party/tensorflow/core/kernels/sparse_tensor_dense_matmul_op_gpu.cu.cc:104:9: note: in instantiation of function template specialization 'tensorflow::SparseTensorDenseMatMulKernel<std::complex<float>, std::complex<float>, int, false, false>' requested here
        SparseTensorDenseMatMulKernel<T, Tsum, Tindices, ADJ_A, ADJ_B>,
        ^
In file included from third_party/tensorflow/core/kernels/sparse_tensor_dense_matmul_op_gpu.cu.cc:20:
In file included from ./third_party/tensorflow/core/framework/bounds_check.h:21:
In file included from third_party/eigen3/Eigen/Core:155:
./third_party/eigen3/Eigen/src/Core/util/Meta.h:293:84: error: non-void function does not return a value [-Werror,-Wreturn-type]
  static T quiet_NaN() { assert(false && "quiet_NaN not supported for this type"); }
                                                                                   ^
./third_party/eigen3/Eigen/src/Core/NumTraits.h:208:39: note: in instantiation of member function 'Eigen::internal::device::numeric_limits<std::complex<double>>::quiet_NaN' requested here
    return numext::numeric_limits<T>::quiet_NaN();
                                      ^
third_party/tensorflow/core/kernels/sparse_tensor_dense_matmul_op_gpu.cu.cc:104:9: note: in instantiation of function template specialization 'tensorflow::SparseTensorDenseMatMulKernel<std::complex<double>, std::complex<double>, int, false, false>' requested here
        SparseTensorDenseMatMulKernel<T, Tsum, Tindices, ADJ_A, ADJ_B>,
        ^
In file included from third_party/tensorflow/core/kernels/sparse_tensor_dense_matmul_op_gpu.cu.cc:20:
In file included from ./third_party/tensorflow/core/framework/bounds_check.h:21:
In file included from third_party/eigen3/Eigen/Core:163:
```

I see the float and double specializations [there](https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/util/Meta.h), but nothing for complex types. Do you know where it's supposed to be coming from?

**Comment by benbarsdell** [comment]
I didn't realize there was no NumTraits implementation for complex (I guess compiler warning flags are more strict internally?).
I've pushed a fix for it.

**Review by allenlavoie — APPROVED** [review]

**Pull request merged**
