### PR TITLE
[DO NOT MERGE] Remove RTLD_GLOBAL when importing pywrap_tensorflow

### PR DESCRIPTION
**Pull request by allenlavoie**
Just making a pull request to run tests.

### CODE REVIEW

**Comment by allenlavoie** [comment]
Jenkins, test this please.

**Review by alextp — DISMISSED** [review]

**Comment by allenlavoie** [comment]
Thanks Alex. Can I test this myself, or do I need someone with write access to say the magic words?

Jenkins, test this please.

**Comment by allenlavoie** [comment]
Jenkins, test this please.

**Comment by allenlavoie** [comment]
Jenkins, test this please.

**Comment by jhseu** [comment]
Marking this as do not merge since it's testing only. Feel free to change the title if you intend to merge.

**Comment by allenlavoie** [comment]
Yes, do not merge is good for now. Thanks!

Jenkins, test this please.

**Comment by allenlavoie** [comment]
Jenkins, test this please.

**Comment by allenlavoie** [comment]
Jenkins, test this please.

**Comment by allenlavoie** [comment]
Jenkins, test this please.

**Comment by allenlavoie** [comment]
Jenkins, test this please.

**Comment by allenlavoie** [comment]
Jenkins, test this please.

**Comment by allenlavoie** [comment]
Jenkins, test this please.

**Comment by allenlavoie** [comment]
Hi Asim and Jonathan,

I'm adding you two as initial reviewers. I'm off next week, but will address comments when I get back. Once you're satisfied, I will add a few more people.

**Comment by jhseu** [comment]
As discussed, please move this to an internal change so there are fewer conflicts that the sync rotation has to resolve. Thanks!

**Pull request closed without merging**
