### PR TITLE
Make a TFLite test case run on big-endian machines

### PR DESCRIPTION
**Pull request by frreiss**
The test case `BasicInterpreter.ThreeStepAllocate` in `/tensorflow/lite/interpreter_test.cc` uses an array of little-endian binary data as one of its inputs. The little-endian data prevents this test from working properly on big-endian machines.

This pull request replaces the array of little-endian data with a struct, so that the embedded 32-bit fields will be in little-endian format on little-endian machines and in big-endian format on big-endian machines. After this change, the test case passes on both little-endian and big-endian machines.

### CODE REVIEW

**Comment by frreiss** [comment]
Found a second test case in `/tensorflow/lite/string_util_test.cc` with the same issue and pushed a second commit to this branch to fix that test case too.

**Comment by gbaned** [comment]
@frreiss Can you please resolve conflicts? Thanks!

**Comment by frreiss** [comment]
Conflicts resolved.

**Comment by gbaned** [comment]
@nutsiepully Can you please take a look on this PR? Thanks!

**Review by jdduke — APPROVED** [review]

**Pull request merged**
