### PR TITLE
update error checking on TensorFlow 2.0

### PR DESCRIPTION
**Pull request by foldl**
change ImportError to AttributeError.

### CODE REVIEW

**Comment by rthadur** [comment]
@foldl please sign CLA and could you elaborate description of PR about new change.Thank you.

**Comment by foldl** [comment]
@googlebot I signed it!

**Comment by foldl** [comment]
I have tried `--quantize` option on r2.1 (python 3.6.10). `AttributeError` is raised instead of `ImportError`.

**Review by gunan — APPROVED** [review]

**Comment by foldl** [comment]
What does this mean? Do I need to do something?

> import/copybara — An error happened while migrating the change

**Pull request merged**
