### PR TITLE
Added an argument to control the padding for flatten_atrous

### PR DESCRIPTION
**Pull request by yuzhang-deepmap**

### CODE REVIEW

**Comment by yuzhang-deepmap** [comment]
I signed the CLA

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@andrewharp  Can you take a look on this PR ?

**Comment by jhseu** [comment]
I don't really think I know enough to review this change. Maybe someone from TFLite/mobile?

**Comment by gbaned** [comment]
@petewarden, Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@petewarden, Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@rmlarsen Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@rmlarsen Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@rmlarsen Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@rmlarsen Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@rmlarsen Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@rmlarsen Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
Hi @rmlarsen Can you please review this PR ? Thank you!

**Comment by mihaimaruseac** [comment]
Closing stale PR

**Pull request closed without merging**
