### PR TITLE
[TFLite] Fix for minimum/maximum quantization problem

### PR DESCRIPTION
**Pull request by konstantinARM**
Fix for minimum/maximum quantization problem

Problem description:
MINIMUM and MAXIMUM operations were not quantized properly. Specifically, the problem was that only one of the inputs was quantized while another one was left in the original data type. Because of this reason, TFLite interpreter was failing to prepare since quantization params of ops did not match.

Problem cause:
MINIMUM and MAXIMUM operators were created in the way that they only had one input, not two. Hence when looping through inputs while quantizing them, only one of two inputs was quantized. 

Problem fix:
Change the definition of the aforementioned properties.

This patch contains fixes for the problem described above. 

1. Properties of MINIMUM and MAXIMUM operators were altered to have
two inputs rather than one. This is safe since both 1.* and 2.* branches
have only two inputs for these ops
2. Test suite for testing Minimum and Maximum ops quantization is added
3. Two small binaries have been added for testing purposes

### CODE REVIEW

**Comment by konstantinARM** [comment]
@googlebot I signed it!

**Comment by akarmi** [comment]
@suharshs, can you please review this PR?

**Comment by gbaned** [comment]
@konstantinARM Can you please resolve conflicts? Thanks!

**Comment by suharshs** [comment]
Hi sorry for the delay, this change actual requires a different solution similar to Concat. I have submitted the fix here: https://github.com/tensorflow/tensorflow/commit/481366eab297011fed94ccc599e27825c905a18c

**Comment by akarmi** [comment]
Hi @suharshs. Thanks for checking this PR. Can you please review the PR #34484 we raised to replace this one? - It extends your fix to cover for the case of inputs with different quantization parameters, and includes the C++ tests to cover both aspects of the problem.

**Comment by suharshs** [comment]
Sure will reply on that pr, thanks.

**Pull request closed without merging**
