### PR TITLE
Correcting Installation from Install

### PR DESCRIPTION
**Pull request by hrittikhere**
Hey, 
I have seen most of the documentation over the internet use the words installation guide so I thought this change would be something useful for the newbies.
Let me know if you have any queries!

### CODE REVIEW

**Comment by hrittikhere** [comment]
@googlebot I signed it!

**Review by KukretiShubham — APPROVED** [review]
LGTM

**Comment by gbaned** [comment]
We will not be encouraging one liner grammatical changes as this is expensive process, thank you for your interest.
CC @mihaimaruseac

**Comment by hrittikhere** [comment]
Hey, 
But I went through the PR's and found that you appreciate a PR with the same kind of issues. Now, I read through the docs and didn't find any similar kind of issues. So, now I could add few different stylings together but that would have been difficult to review or do this PR as the first contribution. 

Can you please throw some light on what should have been the correct path?  @mihaimaruseac @gbaned

**Pull request closed without merging**
