### PR TITLE
Remove deprecated function call in local.py

### LINKED ISSUE #48486: Deprecation Warning in LocallyConnected1D
Tensorflow version 2.4.1

https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/keras/layers/local.py#L39-L338

And also (perhaps more specifically)
https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/keras/layers/local.py#L780

In a LocallyConnected1D layer, if you use `implementation==2` you get a deprecation warning for using `math_ops.sparse_matmul`.

Possible solution:
Change that line to use `tf.linalg.matmul` as the deprecation warning recommends.

To reproduce:

```python
import tensorflow as tf

# Create a tensor to run the layer on.
# The specifics of the shape don't matter as long as it's at least 3 long so that the
# layer will process properly

tensor = tf.random.normal((1, 32, 5))

# Again, the specifics don't really matter as long as the input shape is compatible.
# The important part is the `implementation` parameter.
lc_layer = tf.keras.layers.LocallyConnected1D(10, 1, implementation=2)

print(lc_layer(tensor))
```
output:
```
WARNING:tensorflow:From c:\project_dir\venv\lib\site-packages\tensorflow\python\keras\layers\local.py:780: sparse_mat_mul (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.linalg.matmul` instead
```

### PR DESCRIPTION
**Pull request by AdityaKane2001**
Please refer #48486

### CODE REVIEW

**Review by bhack — APPROVED** [review]
Just for Kokoro tests

**Review by bhack — APPROVED** [review]
Kokoro

**Comment by AdityaKane2001** [comment]
@bhack 
Thanks for the prompt reply!

**Review by rthadur — APPROVED** [review]

**Comment by AdityaKane2001** [comment]
@rthadur 
Thanks for the review!

**Comment by swight-prc** [comment]
Thanks for the quick response!

**Pull request merged**
