### PR TITLE
Quantization support for LeakyRealu and Relu 6 in tools

### PR DESCRIPTION
**Pull request by amitsrivastava78**

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@achowdhery can you please review the PR and provide the feedback.

Regards 
Amit

**Comment by gbaned** [comment]
@achowdhery Can you please review this PR ? Thanks!

**Comment by amitsrivastava78** [comment]
@achowdhery , can you please spend some time on the PR and provide your feedback.

Regards
Amit

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@amitsrivastava78 Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
