### PR TITLE
Updating issue templates to add StackOverflow links

### PR DESCRIPTION
**Pull request by dksb**

### CODE REVIEW

**Review by martinwicke — CHANGES_REQUESTED** [review]
looks good except for some spaces.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment]
@martinwicke Can you please take a look at this PR? Thanks!

**Review by martinwicke — APPROVED** [review]

**Comment by rthadur** [comment]
closing this PR for now.

**Pull request closed without merging**
