### PR TITLE
Declare member functions on TensorShapeIter const.

### PR DESCRIPTION
**Pull request by davidstone**
This fixes a compiler error in C++20 mode caused by ambiguities between reversed and negated comparison candidates.

### CODE REVIEW

**Comment by gbaned** [comment]
@davidstone Thank you for your contribution. Can you please sign CLA? Thanks!

**Comment by davidstone** [comment]
Working through the process to get myself approved

**Comment by davidstone** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
@davidstone it still shows CLA is pending , can you please sign CLA. Thanks!

**Comment by davidstone** [comment]
> @davidstone it still shows CLA is pending , can you please sign CLA. Thanks!

I am seeing:

Corporate Agreements
You are covered by the following corporate agreements:
Agreement | Name | Date Signed
-- | -- | --
Google Corporate CLA | Uber Technologies | Mar 20, 2016 17:00 PDT

**Comment by gbaned** [comment]
@davidstone it still shows CLA is pending , can you use please make sure to use same GitHub username and email-id associated with it.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
