### PR TITLE
resolved issue #26280

### PR DESCRIPTION
**Pull request by arp95**
Please check.

### CODE REVIEW

**Comment by arp95** [comment]
@petewarden please review.

**Comment by arp95** [comment]
@rthadur can you please look into this? It has been over 10 days.

**Comment by arp95** [comment]
@tanzhenyu please review.

**Review by perfinion — CHANGES_REQUESTED** [review]
Your commit message needs to explain what this did and why.

Make it something like:

```
TFLite: Change Android example font dp to sp

Android fonts are supposed to use sp for sizes instead of dp
so that the fonts correctly scale with user preferences.

Closes: https://github.com/tensorflow/tensorflow/issues/26280
```

**Comment by arp95** [comment]
@perfinion updated. Please check.

**Comment by perfinion** [comment]
@arp95 Git needs there to be a blank line after the commit title before the body. I also like to have a blank line before the Closes: bit but that is up to you.

**Comment by arp95** [comment]
@perfinion anything more that needs to be done?

**Review by petewarden — APPROVED** [review]

**Comment by rthadur** [comment]
@arp95 can you please resolve conflicts

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
