### PR TITLE
Addressing #55510 and comments from PR:  https://github.com/keras-team/keras/pull/16417

### PR DESCRIPTION
**Pull request by abhilash1910**
As @fchollet  & @chenmoneygithub  mentioned, replacing deprecated tensorflow/python/keras dependency  with keras packaging works. 
Also there are dependencies on python/keras for other modules.
@gbaned I guess this change should be from the tf side? 
Previous PR: #55593

### CODE REVIEW

**Comment by chenmoneygithub** [comment]
@abhilash1910 Thanks for the PR! 

Keras code in Tensorflow repo is no longer maintained, so generally we just point users to the Keras repo.

**Comment by gbaned** [comment]
Hi @chenmoneygithub Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @abhilash1910,   As @chenmoneygithub mentioned, please submit it to the github.com/keras-team/keras repository instead. Thank you!

**Comment by chenmoneygithub** [comment]
Sorry I should have been more clear - this file is currently not being maintained, the right file is: https://github.com/keras-team/keras/blob/07e13740fd181fc3ddec7d9a594d8a08666645f6/keras/optimizers/optimizer_v2/optimizer_v2.py

**Comment by abhilash1910** [comment]
Hi @chenmoneygithub I agree that this is now deprecated and the in keras optimizers v2, it is mentioned in this [line](https://github.com/keras-team/keras/blob/07e13740fd181fc3ddec7d9a594d8a08666645f6/keras/optimizers/optimizer_v2/optimizer_v2.py#L242) . However in the older python module code, this import does not cause a conflict.  Since  Issue [#55510](https://github.com/tensorflow/tensorflow/issues/55510)  can by pass with this, do you think it is important to be added?

**Comment by gbaned** [comment]
Hi @chenmoneygithub Can you please assist on above comments from @abhilash1910. Thank you!

**Comment by gbaned** [comment]
Hi @abhilash1910 It looks like your PR relates to the Keras component. Please submit it to the github.com/keras-team/keras repository instead. Thankyou.
@fchollet, @qlzh727

**Comment by abhilash1910** [comment]
@chenmoneygithub  Does it make sense to add it in keras ? Since keras is already upstreamed to latest changes .

**Comment by chenmoneygithub** [comment]
@abhilash1910 Sorry for missing the earlier comment. We are actually working on removing legacy Keras code inside TF repo, apologize again for the inconvenience!

**Pull request closed without merging**
