### PR TITLE
Remove expired forward compatibility horizons

### PR DESCRIPTION
**Pull request by lgeiger**
This PR is a followup to #37801 and removes expired forward compatibility statements that always evaluate to `True`.

### CODE REVIEW

**Review by aaudiber — DISMISSED** [review]
LGTM, thanks for the cleanup.

**Comment by lgeiger** [comment]
@aaudiber thanks for the fast review. It looks like I left an unused import. I fixed it in e6f54e4f0780e0dccdafd41bad955ff961fe8afe so CI  should pass now.

**Comment by lgeiger** [comment]
@gbaned any updates on this? Would be good to get it reviewed and merged soon, before it accumulates merge conflicts

**Comment by gbaned** [comment]
@lgeiger Can you please resolve conflicts? Thanks!

**Comment by lgeiger** [comment]
> Can you please resolve conflicts? Thanks!

I rebased the conflicts.
@gbaned It was expected that this PR will accumulate merge conflicts due to the nature of the changes and since it has been open for a month now (see my last comment). Could this PR get reviewed soon in order to prevent more duplicate work on both sides?

**Review by aaudiber — APPROVED** [review]
LGTM, sorry for the delay in review

**Comment by lgeiger** [comment]
Thanks for the review :+1:

**Review by jaingaurav — APPROVED** [review]

**Pull request merged**
