### PR TITLE
Support for large number of classes when using tf.metrics.mean_per_class_accuracy()

### PR DESCRIPTION
**Pull request by clemens-schulz**
`tf.metrics.mean_per_class_accuracy()` uses a `num_classes x num_classes` matrix to keep track of accuracies for each class. This wastes a lot of memory and doesn't work well for large number of classes (e.g. matrix size for 500k classes is 500000^2*4 = 1 terabyte).

By switching to two 1-D variables of size `num_classes` instead, memory usage is reduced considerably. One variable keeps track of correct predictions for each class, while the other variable keeps track of the total number of predictions for each class.

### CODE REVIEW

**Review by alextp — APPROVED** [review]

**Comment by alextp** [comment]
Ouch. I wonder why the original code was unnecessarily quadratic.

**Comment by alextp** [comment]
I don't think this needs API review since metric variables are not persisted and the API for the metric function does not change.

**Comment by rmlarsen** [comment]
Thanks for the quick review, @alextp

**Comment by clemens-schulz** [comment]
Oops, I should've run the tests. I only tested it in my own project. At first glance I see two problems:
- The tests are using float instead of int as type for labels. This isn't supported based on the documentation. But I can cast the labels to int64 to match the old behavior.
- The tests require the update function to return the confusion matrix. I can fix the tests, but I'm not sure if anyone is using the matrix in their projects. Is changing this ok, since it's not really documented?

**Comment by clemens-schulz** [comment]
I added some changes in commit 5e86e3f.

**Comment by rmlarsen** [comment]
@alextp could you take a look at the latest changes?

**Review by rmlarsen — APPROVED** [review]

**Pull request merged**
