### PR TITLE
Branch 181499300

### PR DESCRIPTION
**Pull request by frankchn**

### CODE REVIEW

**Comment by frankchn** [comment]
@tensorflow-jenkins test this please.

**Comment by frankchn** [comment]
@tensorflow-jenkins test this please.

**Review by sb2nov — APPROVED** [review]

**Comment by av8ramit** [comment]
Why was this merged? This is breaking master:
http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/8012/console

**Comment by frankchn** [comment]
hey @av8ramit, sorry this is my fault -- should have checked more closely. when I last merged the `parallel_ops_interleave` test was timing out on Py3 so I thought this was the same problem.

**Comment by av8ramit** [comment]
ah no worries @frankchn I believe it is fixed now.

**Pull request merged**
