### PR TITLE
 [Intel MKL] Fix klockworks issue

### PR DESCRIPTION
**Pull request by guizili0**

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you! 
Just curious, what is klockworks?

**Comment by guizili0** [comment]
@penpornk thanks.
it's klocwork, a static code analysis tool.
https://www.roguewave.com/products-services/klocwork/static-code-analysis

**Comment by penpornk** [comment]
@guizili0 Got it. Thank you! :)

**Comment by penpornk** [comment]
@rthadur Could you please help merge this?

**Comment by rthadur** [comment]
> @rthadur Could you please help merge this?

sure pulling in this now again

**Comment by penpornk** [comment]
@rthadur Thank you! :)

**Pull request merged**
