### PR TITLE
[tf.data] support all combinations for MultiDeviceIteratorTest

### PR DESCRIPTION
**Pull request by kvignesh1420**
This PR extends the test combinations for multi-device iterator tests. Additionally, the `self.test_session` is replaced with `self.cached_session` as per deprecation info.

```TEST LOG
//tensorflow/python/data/kernel_tests:multi_device_iterator_test         PASSED in 7.4s
```
Also, this PR addresses one of the test with TODO(b/121264236) as support for emulating multiple devices in TF 2 now exists.  Reference: point 5 of https://github.com/tensorflow/tensorflow/pull/46761#issuecomment-770059963
cc: @jsimsa

### CODE REVIEW

**Review by jsimsa — COMMENTED** [review]
I actually have internal change that makes functional changes to this file and addressed the same issue as a side-effect. This PR will not be needed.

**Comment by kvignesh1420** [comment]
@jsimsa okay sure. Also, I was hoping we can discuss the graduation of few `tf.data.experimental` APIs to `tf.data` (as per our discussion) Let me know if you have an internal workflow before proceeding with such changes. Thanks!

**Comment by jsimsa** [comment]
@kvignesh1420 let me create a document that summarizes the status of each of the experimental endpoints and share it with you. The steps towards (and feasibility of) graduating experimental APIs will be different for different APIs.

**Comment by kvignesh1420** [comment]
@jsimsa That would be great. Thanks!

**Comment by jsimsa** [comment]
Could you let me know an email address that I can use to share the document with you? Thanks.

**Comment by kvignesh1420** [comment]
@jsimsa you can send the doc to k.vignesh1420@gmail.com

**Comment by kvignesh1420** [comment]
@jsimsa thanks for sharing the doc. I was thinking of assigning a few of the `ready to be migrated` API's to myself (i.e, put my name beside those items one by one) and work on them. This will prevent conflicts in our commits. WDYT?

**Comment by jsimsa** [comment]
sounds good, let's continue the discussion on the doc

**Pull request closed without merging**
