### PR TITLE
Revert "Revert: PR #48758: TFLM: Remove uint8 support for CMSIS-NN kernels"

### PR DESCRIPTION
**Pull request by advaitjain**
This reverts commit 6d8a184710164c7bcc41d3bd29fe4ef46836b6c9.

### CODE REVIEW

**Comment by advaitjain** [comment]
tagging @mansnils @freddan80

**Comment by mansnils** [comment]
@advaitjain this is hard to reproduce but I have seen a problem in another context, which I suspect is the same as this. If so then this should hopefully fix the issue.
Basically the fix is to use memcpy to interpret the bytes of an object as a value of a different type, as proposed here: https://en.cppreference.com/w/cpp/language/reinterpret_cast.
I have a patch but I am not able to push to this PR (is it even possible?). Besides the new repo will be taken into use tomorrow.. should we create a new PR?

**Comment by mansnils** [comment]
I will create a new PR in the new repo.

**Comment by advaitjain** [comment]
> I will create a new PR in the new repo.

thanks!

**Comment by advaitjain** [comment]
> @advaitjain this is hard to reproduce but I have seen a problem in another context, which I suspect is the same as this. If so then this should hopefully fix the issue.
> Basically the fix is to use memcpy to interpret the bytes of an object as a value of a different type, as proposed here: [en.cppreference.com/w/cpp/language/reinterpret_cast](https://en.cppreference.com/w/cpp/language/reinterpret_cast).
> I have a patch but I am not able to push to this PR (is it even possible?). Besides the new repo will be taken into use tomorrow.. should we create a new PR?

Good to know. Only maintainers can push to incoming PRs so you won't be able to push to a PR that I created. The purpose was to have a shared state to see the errors. Having you make a new PR would be great.

**Comment by advaitjain** [comment]
closing this PR in favor of the PR that @mansnils will create in https://github.com/tensorflow/tflite-micro/

**Pull request closed without merging**
