### PR TITLE
Disabling wrong regex test.

### PR DESCRIPTION
**Pull request by wenchenvincent**
The test failed for rocm in a weekly sync. Investigation under way but disabled it for rocm for now to keep community CI clean.
@cheshire @chsigg @deven-amd @stevenireeves

### CODE REVIEW

**Comment by stevenireeves** [comment]
@googlebot I consent.

**Review by cheshire — APPROVED** [review]
Why do we have a different error message for ROCm though?

**Comment by wenchenvincent** [comment]
> Why do we have a different error message for ROCm though?

It was indeed strange and still under investigation. Attached is the failing log.
[tridiagonal_matmul_op_test_gpu_test.log](https://github.com/tensorflow/tensorflow/files/7514763/tridiagonal_matmul_op_test_gpu_test.log)

**Comment by stevenireeves** [comment]
@cheshire Can we get a re-approval on this PR? We had to do a minor change for pylint.

**Review by cheshire — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
