### PR TITLE
[oneDNN] Adding support for QuantizedMaxpool3D

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR adds support for INT8 MaxPool3D through internal op _QuantizedMaxPool3D.

### CODE REVIEW

**Comment by gbaned** [comment]
@penpornk Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by vufg** [comment]
@mahmoud-abuzaina thanks for the PR! can you take a look at the failed checks?

**Comment by mahmoud-abuzaina** [comment]
@vufg looks like some logs are expired and I can't access them. Can you re-trigger the tests?

**Comment by vufg** [comment]
@mahmoud-abuzaina i think you need to rebase this PR to the head to trigger the tests

**Comment by mahmoud-abuzaina** [comment]
@vufg I think checks are passing now.

**Review by panzhufeng — APPROVED** [review]

**Pull request merged**
