### PR TITLE
Added StateSavingRnnEstimator in __init__ of contrib.learn

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by terrytangyuan** [comment]
@tensorflow-jenkins Test this please

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
@zheng-xq this can be merged. (not merging myself only because I don't want to mess with your sync if you're doing one -- conflicts etc.)

**Comment by martinwicke** [comment]
Unlikely to cause conflicts -- I'll merge.

**Pull request merged**
