### PR TITLE
Make source compilable in debug with -Og flag

### PR DESCRIPTION
**Pull request by sogartar**
Add missing definition for static constexpr member PjitFunctionCache::kDefaultCapacity.
In debug the value is not optimized out and you still need a definition to link.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @cheshire Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sogartar Can you please resolve conflicts? Thank you!

**Comment by sogartar** [comment]
> Hi @sogartar Can you please resolve conflicts? Thank you!

Done.

**Comment by reedwm** [comment]
@chsigg can you take a look? The `pjit.cc` change makes sense but I'm not familiar with the `crosstool_wrapper_driver_is_not_gcc.tpl` file.

**Comment by gbaned** [comment]
Hi @chsigg Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @chsigg Can you please review this PR ? Thank you!

**Review by chsigg — APPROVED** [review]

**Comment by jakevdp** [comment]
Hi - this is causing test failures in JAX's CI jobs: https://source.cloud.google.com/results/invocations/1286e06c-21ac-40e9-aafe-1f1b98fe5c0c/targets/jax%2Ftesting%2Fgpu%2Fpresubmit_github/log
```
Traceback (most recent call last):
  File "external/ubuntu20.04-gcc9_manylinux2014-cuda11.8-cudnn8.6-tensorrt8.4_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc", line 308, in <module>
    sys.exit(main())
  File "external/ubuntu20.04-gcc9_manylinux2014-cuda11.8-cudnn8.6-tensorrt8.4_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc", line 295, in main
    return InvokeNvcc(leftover, log=args.cuda_log)
  File "external/ubuntu20.04-gcc9_manylinux2014-cuda11.8-cudnn8.6-tensorrt8.4_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc", line 215, in InvokeNvcc
    (len(opt_option) > 0 and opt_option[0].isnumeric() and
```
Can we roll this back?

**Pull request merged**
