### PR TITLE
Add CombinedNMS FakeGPU op

### PR DESCRIPTION
**Pull request by samikama**
Move FakeGPU CombinedNonMaxSuppression op from #28745 to this PR

### CODE REVIEW

**Comment by samikama** [comment]
@aaroey Did this make into 1.14?

**Comment by aaroey** [comment]
@samikama unfortunately no, and TRT 5.1 is not in 1.14 yet. Given the situation, I'm not sure if this is the best approach and whether we want a real implementation of CombinedNMS, so I'll delay the review of this one until we figure out. Sorry about that.

**Comment by samikama** [comment]
@aaroey I understand. I don't like the solution either but due to discussion in #28051, I had a feeling that it is an acceptable practice.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
