### PR TITLE
Update tf.keras engine sequential.py: add predict_classes, predict_proba deprecation warnings

### PR DESCRIPTION
**Pull request by 8bitmp3**
`Model.predict_classes` and `Model.predict_proba` are deprecated and the warnings won't be seen by the users until they attempt to call the methods.

The messages should be in line with https://developers.google.com/devsite/reference/styles/notices#warning as discussed @lamberta @MarkDaoust

### CODE REVIEW

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
With the stitch to keras being implemented as a separate package that tensorflow depends on ... the sopurce files in tensorflow/python/keras are no longer used (!).

You's need to update the code in keras-team/keras:

https://github.com/keras-team/keras/blob/master/keras/engine/sequential.py

These methods don't exist on the base `Model` class?

**Comment by gbaned** [comment]
@8bitmp3  Please submit it to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. Thank you!

**Comment by 8bitmp3** [comment]
@gbaned @MarkDaoust The deprecated APIs were removed in `keras-team/keras` `sequential.py` https://github.com/keras-team/keras/commit/f4a382d66c12a7d20f9e7ad92be9a8e8bd4582bb#diff-3f56e791abb6fa7510fc1b987e6ad29cbc042b7e129af906d71be274bdb03e56 but `tensorflow/keras` `sequential.py` appears to still mention them https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/sequential.py

**Comment by MarkDaoust** [comment]
Yes, the team is still cleaning up those orphaned files in `tensorflow/python/keras`. In TensorFlow 2.6 (or tf-nightly) the source files are still there, but the public API is built from the source in `keras-team/keras`.

**Pull request closed without merging**
