### PR TITLE
update rpi build path

### PR DESCRIPTION
**Pull request by marine0131**
lite folder is no longer under contrib folder, I found these two scripts need update

### CODE REVIEW

**Comment by harshini-gadige** [comment]
@marine0131  Please sign CLA if you wish to contribute a PR. Thanks !

**Comment by marine0131** [comment]
I have signed CLA

**Comment by harshini-gadige** [comment]
@petewarden  Any update/comments ?

**Comment by andrehentz** [comment]
Looks like these changes have been independently made: https://github.com/tensorflow/tensorflow/commit/b4a7f51584d60e26024bb7401e3167704f94d298

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @miaout17: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @miaout17: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @miaout17: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @miaout17: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @miaout17: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by petewarden** [comment]
Sorry for the delay, and thanks for the fix! We had another similar change come in that has solved the issue, so closing this PR.

**Pull request closed without merging**
