### PR TITLE
MKL: Adding MKL-DNN graph pass implementation

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**

### CODE REVIEW

**Review by andydavis1 — APPROVED** [review]

**Comment by andydavis1** [comment]
@tensorflow-jenkins test this please.

**Comment by sb2nov** [comment]
@mahmoud-abuzaina can you take a quick look at the merge conflicts

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins, test this please.

**Pull request merged**
