### PR TITLE
Simplify python loops

### PR DESCRIPTION
**Pull request by lgeiger**
This PR replaces loops over `range(len(...))` with `enumerate()` or `zip()`. This makes the code (arguably) easier to read and in some cases even slightly faster.

### CODE REVIEW

**Review by caisq — DISMISSED** [review]
Thanks, @lgeiger

**Comment by lgeiger** [comment]
Sorry, I messed up the rebase from #25586 and included a change that messed up the bazel build. Fixed it in the latest commit 😇

**Comment by rthadur** [comment]
@caisq can you PTAL , thank you

**Review by jhseu — DISMISSED** [review]

**Comment by rthadur** [comment]
@lgeiger can you please resolve conflicts ?

**Comment by lgeiger** [comment]
> @lgeiger can you please resolve conflicts ?

@rthadur Rebase it :+1:

**Review by alextp — APPROVED** [review]
Thanks!

**Pull request merged**
