### PR TITLE
[WIP] Add boston.ipynb for better input_fn tutorial

### PR DESCRIPTION
**Pull request by mohan-chinnappan-n**
Here is ipython (jupyter) version, with these features:
- modularized 
- with plots to visualize  the model performance
- easy to tune the model

### CODE REVIEW

**Comment by martinwicke** [comment]
Is this in response to some issue?

**Comment by mohan-chinnappan-n** [comment]
No. It is an improvement and for re-usability.

**Comment by martinwicke** [comment]
It's a new file, do you anticipate it being referenced from a tutorial? It's in the tutorials directory, and the name suggests if should be explained in the input_fn tutorial, is that the plan?

**Comment by mohan-chinnappan-n** [comment]
Yes. That is the plan

**Comment by martinwicke** [comment]
Ok, in that case, I've marked this WIP, and we'll look at it together with the modifications to the actual tutorial. 

@wolffg @dr4b FYI. Who's working on the input_fn tutorial? Can't find Barry on GH.

**Comment by dr4b** [comment]
I'm not sure who's working on input_fn (it's not me as far as I know?), but Barry is @jugglerix if that helps.

**Comment by drpngx** [comment]
@jugglerix any luck with this?

**Comment by vrv** [comment]
Closing due to lack of response for 4 weeks, please re-open a new PR with the addressed changes if you can!  Thank you for your contribution.

**Pull request closed without merging**
