### PR TITLE
Use vector constructor to initialize Array3D.

### PR DESCRIPTION
**Pull request by conqerAtapple**
Current constructor of Array3D calls resize to initialize the inner vector of
Array3D and follows up with a Fill call. This can be replaced with a simple
call to vector constructor. Vector constructor might also be more efficient.

### CODE REVIEW

**Comment by conqer** [comment]
@hawkinsp Please review. Array2D has been covered in https://github.com/tensorflow/tensorflow/pull/8115.

**Review by hawkinsp — COMMENTED** [review]
This change is fine, but perhaps you should change Array4D as well at the same time? Thanks!

**Comment by conqer** [comment]
@hawkinsp Added Array4D changes.

**Review by hawkinsp — APPROVED** [review]

**Comment by dandelionmane** [comment]
@tensorflow-jenkins Test this please

**Comment by dandelionmane** [comment]
The XLA test looks like a flake - retriggering.
@tensorflow-jenkins Test this please

**Pull request merged**
