### PR TITLE
[Intel MKL] Adding support for MPI and Horovod to MKL containers

### PR DESCRIPTION
**Pull request by claynerobison**

### CODE REVIEW

**Comment by claynerobison** [comment]
@congxu-ml Here is the Horovod container

**Comment by congxu-ml** [comment]
Thanks, Clayne! I can answer any feedback related to this commit.

**Comment by congxu-ml** [comment]
@caisq Hi Shanqing, can you please review this PR? It is very important for us, lots of our customers need to use it. Thanks a lot!

**Comment by case540** [comment]
Adding angerson@ to take a look who is looking at refactoring our Docker files.

**Review by angerson — APPROVED** [review]
Thanks for working on this! This looks good, but (@congxu-ml) please also take a look at https://github.com/tensorflow/community/pull/8, which is a design doc that will improve our Dockerfile situation so that changes like these are easier for everyone to handle.

Once that design is integrated, we may ask you to add these changes in again to the new system.

**Comment by congxu-ml** [comment]
angerson@ Thanks for approving my commit! Sure, I will modify my files once the proposed Dockerfile assembler is merged.

**Pull request merged**
