### PR TITLE
Adding the CMAKE_GENERATOR  line to all external cmake files.

### PR DESCRIPTION
**Pull request by av8ramit**

### CODE REVIEW

**Review by mrry — APPROVED** [review]
Fingers crossed for this one!

**Comment by gunan** [comment]
The failure looks related. Could you take a  look?

**Comment by mrry** [comment]
I grepped the logs and there are some suspicious architecture-related warnings:

```
$ grep "library machine type" 5ea42dd3-build.log  | head
    41>zlib\install\lib\zlibstatic.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64' [T:\src\github\tensorflow\cmake_build\proto_text.vcxproj]
    41>gif\install\lib\giflib.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64' [T:\src\github\tensorflow\cmake_build\proto_text.vcxproj]
    41>png\install\lib\libpng12_static.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64' [T:\src\github\tensorflow\cmake_build\proto_text.vcxproj]
    41>jpeg\install\lib\libjpeg.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64' [T:\src\github\tensorflow\cmake_build\proto_text.vcxproj]
    41>lmdb\install\lib\lmdb.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64' [T:\src\github\tensorflow\cmake_build\proto_text.vcxproj]
    41>jsoncpp\src\jsoncpp\src\lib_json\Release\jsoncpp.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64' [T:\src\github\tensorflow\cmake_build\proto_text.vcxproj]
    41>farmhash\install\lib\farmhash.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64' [T:\src\github\tensorflow\cmake_build\proto_text.vcxproj]
    41>fft2d\\src\lib\fft2d.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64' [T:\src\github\tensorflow\cmake_build\proto_text.vcxproj]
    41>highwayhash\install\lib\highwayhash.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64' [T:\src\github\tensorflow\cmake_build\proto_text.vcxproj]
    41>nsync\install\lib\nsync.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64' [T:\src\github\tensorflow\cmake_build\proto_text.vcxproj]
```

...so for some reason it looks like the build is defaulting to making 32-bit builds for some of the external projects. I guess the spirit of the 90s is alive in CMake.

Notably `protobuf.cmake` doesn't display these errors, as it has an explicit directive to set the build platform to `${CMAKE_GENERATOR_PLATFORM}` in`protobuf.cmake`:

https://github.com/tensorflow/tensorflow/blob/926fc13f7378d14fa7980963c4fe774e5922e336/tensorflow/contrib/cmake/external/protobuf.cmake#L38-L49

...so perhaps what's needed is to replicate *that* structure (effectively setting the `-A`, `-G`, and `-T` flags to match the parent) in each of the externals. Perhaps setting one but not the others leads to it using bad defaults?

**Comment by martinwicke** [comment]
@av8ramit Are we really merging this into 1.5? Is this still current?

**Comment by av8ramit** [comment]
@gunan feel free to reopen if you plan on using this.

**Pull request closed without merging**
