### PR TITLE
change libcudnn7 version to 7.0.5.15

### PR DESCRIPTION
**Pull request by juanluisrosaramos**
Founded incompatibilities with my laptop GPU in ubuntu 18. "cuda_dnn.cc:360] Possibly insufficient driver version: 390.48.0". It was solved downgrading CuDNN

### CODE REVIEW

**Comment by juanluisrosaramos** [comment]
I signed it!

**Comment by aaroey** [comment]
Hi @juanluisrosaramos, can you upgrade your driver version instead? cuDNN 7.1+ is required for TensorRT 4, and we usually don't rollback cuDNN version.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Pull request closed without merging**
