### PR TITLE
Adding support for dynamic shapes to the Unpack converter.

### PR DESCRIPTION
**Pull request by drivanov**

### CODE REVIEW

**Comment by drivanov** [comment]
Some repetitive code used by 4 converters (**ConvertStridedSlice, ConvertSlice, ConvertSplit, ConvertUnpack**) has been moved to the newly implemented **ConvertStridedSliceHelper** function.

**Comment by gbaned** [comment]
Hi @drivanov Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @pjannaty Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @pjannaty Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @drivanov, @pjannaty I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you!

**Pull request closed without merging**
