### PR TITLE
[ROCM] Reland of PR #57102

### PR DESCRIPTION
**Pull request by draganmladjenovic**
Wire up TrsmBatched and Gesvd and add Trsv

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @draganmladjenovic Can you please sign CLA. Thank you!

**Comment by draganmladjenovic** [comment]
@gbaned rocm CI build dosn't seem to be related to this PR?

**Comment by gbaned** [comment]
Hi @cheshire Can you please assist on above comments from @draganmladjenovic. Thank you!

**Comment by i-chaochen** [comment]
Hi @akuegel wonder will you review this PR, please? Thanks in advance!

**Review by akuegel — APPROVED** [review]

**Pull request merged**
