### PR TITLE
Make tf_upgrade.py dependency free

### LINKED ISSUE #11217: tools.compatibility module is missing or not installed properly through pip
Running tf_upgrade.py gets ImportError:

```
$ python tf_upgrade.py 
Traceback (most recent call last):
  File "tf_upgrade.py", line 23, in <module>
    from tensorflow.tools.compatibility import ast_edits
ImportError: No module named compatibility

```
There's no subdir named compatibility under tools in python packages dir. Those were taken from:

```
>>> import site; site.getsitepackages()
['/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages'] 
```

### System information
Ubuntu 16.04
Tensorflow 1.2.1, upgraded 'natively' via pip from a pre 1.0 version:
$ sudo -H pip install --upgrade tensorflow-gpu
Python version 2.7.12

### PR DESCRIPTION
**Pull request by jart**
Nothing else references the ast_edits, so it will make tf_upgrade.py much
easier to use if it's just absorbed. This change fixes #11217 where a whole
bunch of folks encountered difficulties for this very reason.

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]
Funny, because I think I split this apart once, in anticipation of writing more of these upgrade scripts. We may still do that... but I guess the convenience outweighs that for now.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@jart, please take a look at this test failure:
https://ci.tensorflow.org/job/tensorflow-pull-requests-gpu/7887/consoleFull

> ERROR: missing input file '//tensorflow/tools/compatibility:ast_edits.py'.
> ERROR: /workspace/tensorflow/tools/compatibility/BUILD:20:1: //tensorflow/tools/compatibility:tf_upgrade_test: missing input file '//tensorflow/tools/compatibility:ast_edits.py'.
> INFO: Building complete.
> ERROR: /workspace/tensorflow/tools/compatibility/BUILD:20:1 1 input file(s) do not exist.

It looks like a BUILD rule needs to be updated.

**Comment by drpngx** [comment]
@jart is this still current?

**Comment by jart** [comment]
Yes. Build issue should be addressed. If tests pass please merge.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Looks like there's some error here

```
==================== Test output for //tensorflow/tools/compatibility:tf_upgrade_test:
Traceback (most recent call last):
  File "/tmp/botexec/bazel-out/k8-py3-opt/bin/tensorflow/tools/compatibility/tf_upgrade_test.runfiles/org_tensorflow/tensorflow/tools/compatibility/tf_upgrade_test.py", line 25, in <module>
    from tensorflow.tools.compatibility import ast_edits
ImportError: cannot import name 'ast_edits'
```

**Comment by jart** [comment]
Apologies for that one. I made sure to run that test locally before pushing again.

**Comment by drpngx** [comment]
Thanks!

**Pull request merged**
