### PR TITLE
Add aarch64 cross compile toolchain for TFLite

### PR DESCRIPTION
**Pull request by lgeiger**
This PR extends the current Arm toolchain by adding an `aarch64` bazel toolchain based on [Arm GCC 9.2](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads). This e.g. allows to cross compile TFLite with `bazel` for the Raspberry Pi 4 running on a 64-bit OS.

This has can be tested by compiling the TFLite benchmark binary on Linux by running:
```
bazelisk build -c opt tensorflow/lite/tools/benchmark:benchmark_model \
    --cpu=aarch64 --crosstool_top=@local_config_arm_compiler//:toolchain
```

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by rthadur — APPROVED** [review]

**Comment by terryheo** [comment]
Hi, @lgeiger 
Interestingly, I was making the same change for TFLite toolchain. In my experiment, GCC 9.2 requires glibc 2.30 which is not yet popular. Didn't you have difficult in running output binary?

**Comment by lgeiger** [comment]
We used an ARM gcc 8.3 based toolchain on a Rapberry Pi 4 before. When making the PR I upgraded to 9.2 and re-ran some test in QEMU sucessfully, speaking of glibc I am not 100% sure if I re-tested on an actual device though. I'll double check tomorrow and will get back to you.

**Comment by byronyi** [comment]
Any chance glibc-2.17 for manylinux2014 wheel spec be supported? The front end could be gcc-7/8/9 thanks to RH’s devtoolset.

**Comment by terryheo** [comment]
@lgeiger my RPI3 has libc-2.28.so even after running "apt-get update libc6". I'll wait for your test result. thanks!

@byronyi I'm not familiar with manylinux2014 and RH’s devtoolset. Do you want to have a toolchain which supports glibc-2.17?

**Comment by byronyi** [comment]
> @byronyi I'm not familiar with manylinux2014 and RH’s devtoolset. Do you want to have a toolchain which supports glibc-2.17?

devtoolset-X is a back port of gcc-X to older version of RHEL/CentOS (so also older versions of glibc, libstdcxx, etc.). 

For example, devtoolset-7 on CentOS 6 provides gcc-7.3 using glibc-2.12, and devtoolset-8 on CentOS 7 provides gcc-8.2 using glibc-2.17. Python packaging on Linux has followed these standards.

| OS version | glibc version | Python wheel standard |
|:---:|:---:|:---:|
| CentOS 5 | glibc-2.5 | [manylinux1](https://www.python.org/dev/peps/pep-0513/) |
| CentOS 6 | glibc-2.12 | [manyinux2010](https://www.python.org/dev/peps/pep-0571/) |
| CentOS 7 | glibc-2.17 | [manylinux2014](https://www.python.org/dev/peps/pep-0599/) |

TensorFlow Python package is built with [devtoolset-7](https://github.com/tensorflow/tensorflow/commit/2afcda57062b5ebb94c35a2bbd3581c9b8bc7393) and glibc-2.12 [starting from TF 1.15](https://www.tensorflow.org/install/source#cpu). 

However, manylinux2014 is the first packaging standard that considers multi-arch support. IBM has supplied their [ppc64le TF builds](https://github.com/tensorflow/build/blob/master/images/ppc64le/gpu/Dockerfile.manylinux_2014.cuda10_1) using the manylinux2014 standard. I am wondering if we could do the same for aarch64.

**Comment by lgeiger** [comment]
> Didn't you have difficult in running output binary?

I just double checked and I am able to build the model benchmark binary with this toolchaing and run it on the Raspberry Pi 4.
I forgot to mention earlier that although it has a 64-bit CPU the default Raspbian OS is a 32-bit OS, so I opted to use a custom 64-bit OS which apparently comes with a newer version of glibc. I'm currently using [Manjaro](https://manjaro.org/download/#raspberry-pi-4-xfce).

**Comment by terryheo** [comment]
@lgeiger thanks for the confirmation. So it's not a Rasbian release. Good to know about manjaro.

@byronyi  thanks for the information. We need a cross toolchain for aarch64 which relies on glibc-2.17 but I can't find it. I've checked older versions of Linaro toolchains but failed. https://releases.linaro.org/components/toolchain/binaries/
Which target OS are you using?  Can't you upgrade your target OS?

**Comment by byronyi** [comment]
> @lgeiger thanks for the confirmation. So it's not a Rasbian release. Good to know about manjaro.
> 
> @byronyi thanks for the information. We need a cross toolchain for aarch64 which relies on glibc-2.17 but I can't find it. I've checked older versions of Linaro toolchains but failed. https://releases.linaro.org/components/toolchain/binaries/
> Which target OS are you using? Can't you upgrade your target OS?

As I said, manylinux2014 is a Python packaging spec, and it roughly translates to CentOS 7. Being compatible to this spec means the binary could be installed/distributed using pip on PyPI.

cc @perfinion

**Comment by byronyi** [comment]
I took a look at devtoolset and it does have aarch64 support: http://mirror.aktkn.sg/centos-altarch/7/sclo/aarch64/rh/devtoolset-7/

**Pull request merged**
