### PR TITLE
[Language Fix] Change BlackBox to ClosedBox

### PR DESCRIPTION
**Pull request by AmanKishore**
Fixing a borderline-racist term in the Tensorflow repository.

### CODE REVIEW

**Comment by AmanKishore** [comment]
@googlebot I signed it!

**Comment by oopupdeep** [comment]
that's ridiculous

**Review by wangtz — APPROVED** [review]
Thanks for the change!

**Review by wangtz — APPROVED** [review]
I think I had approved this PR before. If you need to sync, try rebase instead of merge so that you don't need to wait for another approve (hopefully).

**Pull request merged**
