### PR TITLE
Removes unnecessary MKL contraction kernel flag from mkl_aarch64 build

### PR DESCRIPTION
**Pull request by nSircombe**

### CODE REVIEW

**Comment by nSircombe** [comment]
@penpornk - here's a PR to avoid the...

```
//tensorflow/core/kernels:no_mkldnn_contraction_kernel
Multiple matches are not allowed unless one is unambiguously more specialized.
```

...error when running `bazel test` on a build with `--config=mkl_aarch64`.

Is there any chance this could be cherry-picked for the next TF 2.9 RC?

**Comment by nSircombe** [comment]
@elfringham - I've tested this fix (which @penpornk suggested) to the .bazelrc and it appears to work fine.

**Review by penpornk — APPROVED** [review]
Thank you for the PR and sorry for the delay!

**Comment by nSircombe** [comment]
Thanks @penpornk

**Pull request merged**
