### PR TITLE
Remove hdfs as support has been moved to modular file systems.

### PR DESCRIPTION
**Pull request by yongtang**
This PR removes hdfs as support has been moved to modular file systems.

This PR will help reduce build time of tensorflow core.

/cc @kvignesh1420  @vnvo2409 @burgerkingeater FYI

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by kvignesh1420 — COMMENTED** [review]
@yongtang @mihaimaruseac I think we should mention this activity in the RELEASE.md.

**Comment by yongtang** [comment]
@kvignesh1420  Thanks for the reminder. PR #51036 has been created to update the RELEASE.md

**Review by gbaned — APPROVED** [review]

**Comment by gbaned** [comment]
@yongtang Can you please resolve conflicts? Thanks!

**Comment by yongtang** [comment]
@gbaned The PR has been rebased and updated. Please take a look.

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Seems I need to manually import this

**Comment by mihaimaruseac** [comment]
Merged by 86b9b15c4b8c3dd75ad766bb14d0c2143327b0ff

**Pull request closed without merging**
