### PR TITLE
Type inference using type annotations

### PR DESCRIPTION
**Pull request by rahul-kamat**
Performs type inference using type annotations. 
A dictionary with variable names mapped to a list of possible types is added to the AST nodes.

### Example
```python
def f(x: tf.Tensor, a: int):
  if y > 0:
    y = x + y
  return y
```
The AST will be annotated with:
`y = x + y`: 
```cs
___pyct_anno={SCOPE: Scope{r=(x, y,), w=(y,)}, 'type_anno_read': {x: {tf.Tensor}, y: {int}}, 'type_anno_write': {y: {tf.Tensor}}}
```

`return y`: 
```cs
___pyct_anno={SCOPE: Scope{r=(y,), w=()}, 'type_anno_read': {y: {tf.Tensor, int}}, 'type_anno_write': {}}
```

Note: This is experimental and does not infer types for variables assigned to a python object.

### CODE REVIEW

**Review by mdanatg — APPROVED** [review]

**Comment by rthadur** [comment]
@rahul-kamat can you please check ubuntu sanity build failures ?

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by mdanatg** [comment]
The PR is still valid, but we've been delayed on the integration.

**Comment by gbaned** [comment]
Hi @rahul-kamat, @mdanatg I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for your contribution!

**Pull request closed without merging**
