### PR TITLE
Extend test _loss_scaling

### PR DESCRIPTION
**Pull request by bhack**
Test if Optimizers with Slots could be used with SavedModel to train again with reproducible results.

### CODE REVIEW

**Comment by bhack** [comment]
I also still see this TODO in master on the `load` https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/saving/saved_model/load.py#L116

I don't know if it is still (partially) valid.

**Comment by reedwm** [comment]
I confirmed loading a model with `load_model` does not restore slot variables. This explains the failure both in this PR and your sample code in https://github.com/tensorflow/addons/pull/2126#issuecomment-683266384. Since slot variables are not restored and Adam (unlike SGD without momentum) has slot variables, saving and loading a model is not equivalent to simply keeping the same model.

I'm closing this PR since currently it's impossible to test this sort of thing, as slot variables are not restored. Let me know if you'd like to modify this PR and I can reopen.

**Comment by bhack** [comment]
Yes I suppose It was expected but we need to put this in the documentation cause It Is not a so edge case and this source code comment It Is on a not exposed API.

Also I think we need raise a warning somwhere? On load? On fit?

**Comment by reedwm** [comment]
@k-w-w can we mention that slot variables are not restored in the documentation of `tf.saved_model.load` and `tf.keras.models.load_model`? And perhaps the corresponding save functions as well.

I personally don't think we should warn since this won't negatively effect most users, and it would effectively warn every time a model is loaded.

**Comment by reedwm** [comment]
Actually it would make sense IMO if there is a warning when calling fit() on a model loaded from a SavedModel with a restored optimizer with slot variables . This would not warn for most SavedModels users, only those who would be affected by the fact slot variables are not restored.

**Comment by bhack** [comment]
Need we to add a setter to the model to detect this case?

**Comment by bhack** [comment]
Just a Draft for an entry point: https://github.com/tensorflow/tensorflow/pull/42846
Let me know there how we could go ahead..

**Comment by adriangb** [comment]
Are there any workarounds for this? Can one manually save the optimizer state (some combination of `get_weights`/`get_slots`)?

**Pull request closed without merging**
