### PR TITLE
[XLA] Remove dependency on having a GPU to run jit tests

### PR DESCRIPTION
**Pull request by DavidNorman**
We would like to be able to build the XLA backend without the GPU JIT compiled into it.  We put the xla_gpu_device behind a check for CUDA, and the update the 2 tests which explicitly target the GPU.

### CODE REVIEW

**Review by sanjoy — CHANGES_REQUESTED** [review]
Do you mind instead removing the dependency on the GPU JIT altogether and replacing XLA_GPU with 
XLA_CPU in the two tests?

**Comment by DavidNorman** [comment]
sure thing.

**Comment by DavidNorman** [comment]
sorry about taking my time over this.

**Comment by DavidNorman** [comment]
It turns out that some other GPU things were added to this test since we first put in this compilation fix, and so we don't actually run it any more.  So, I'm going to revert all of these changes in our repo, and abandon this change.

**Pull request closed without merging**
