### PR TITLE
Added support for half precision type in linear algebra operators

### LINKED ISSUE #22086: Lack of support for half precision type in linear algebra operators
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: v1.9.0-0-g25c197e023 1.9.0
- **Python version**: Python 3.6.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: Tesla V-100 16160MiB
- **Exact command to reproduce**:
Minimal example to reproduce the issue
```
import tensorflow as tf
from tensorflow.python.ops import gen_linalg_ops

a = tf.placeholder(tf.float16, shape=[2, 2])
gen_linalg_ops.qr(a)
```

### Problem
There seems to be no support for float16 type in [linalg_ops.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/linalg_ops.cc) at all. Is there any reason as to why that is the case? Or a way around it?

I have run into this issue when trying to use keras with float16 (by editing `.keras/keras.json`), sequential model with GRU cells. Code included for completeness:
```
import tensorflow.keras as keras

model = keras.Sequential()
model.add(keras.layers.GRU(128, recurrent_dropout=0.75, input_shape=(200, 4)))
```

### Log
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.6/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 1494, in qr
    "Qr", input=input, full_matrices=full_matrices, name=name)
  File ".../python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File ".../python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'input' has DataType float16 not in list of allowed values: float64, float32, complex64, complex128
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #22086 
Following changes were made:
- Added float16 support to relevant ops defined in [linalg_ops.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/linalg_ops.cc)
- Added unit tests in [linalg_ops_test.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/linalg_ops_test.cc) for validation of float16 support.

### CODE REVIEW

**Comment by alphastreak** [comment]
I am new to tensorflow development. So it would be nice if someone can review the code and suggest any edits if any.

**Comment by qlzh727** [comment]
Patrick, can u take a look? Thanks.

**Review by drpngx — APPROVED** [review]
Note that some of these operations may not be very stable numerically on float16.

**Comment by qlzh727** [comment]
The clang format check is failing, see https://source.cloud.google.com/results/invocations/70c2c0dc-d4b3-4074-a5c3-415c740c1c22/targets/%2F%2Ftensorflow%2Ftools%2Fci_build:gen_ci_clang_format_out/log

diff --git a/tensorflow/core/ops/linalg_ops_test.cc b/tensorflow/core/ops/linalg_ops_test.cc
index 8bcd271660..52d77991bd 100644
--- a/tensorflow/core/ops/linalg_ops_test.cc
+++ b/tensorflow/core/ops/linalg_ops_test.cc
@@ -84,7 +84,7 @@ TEST(LinalgOpsTest, SelfAdjointEigV2_ShapeFn) {
                      .Input({{"input", 0, DT_FLOAT}})
                      .Attr("compute_v", compute_v)
                      .Finalize(&op.node_def));
-    //test for float16
+    // test for float16
     TF_ASSERT_OK(NodeDefBuilder("test", "Pack")
                      .Input({{"input", 0, DT_HALF}})
                      .Attr("compute_v", compute_v)

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
