### PR TITLE
Fix TF 2.7 release notes

### PR DESCRIPTION
**Pull request by nouiz**
Fix https://github.com/tensorflow/tensorflow/pull/52670/. The changes is in TF2.7 and not 2.6.

@mihaimaruseac

### CODE REVIEW

**Comment by nouiz** [comment]
@googlebot I consent.

I already have the CLA signed. I'm not sure why this was asked.

**Comment by mihaimaruseac** [comment]
CLA bot is confused when doing cherrypicks.

There's a caveat here, we'll add a new commit on the branch after the release, but probably we can handle this the same as #52971

**Comment by nouiz** [comment]
> CLA bot is confused when doing cherrypicks.

I didn't cherry-pick anything here.

> There's a caveat here, we'll add a new commit on the branch after the release, but probably we can handle this the same as #52971

Can you confirm that, I need to do this commit on top of master and not on the release branch? I updated this PR to do this. I changed the RELEASE.md files instead of README.md.

**Comment by mihaimaruseac** [comment]
So we need one PR against the r2.7 branch and one against master. This way we ensure that the relnotes on the branch are always a subset of what's on master, each section matching.

After the r2.7 branch PR lands I will update the GitHub release notes to match.

**Comment by ratan** [comment]
Looks good

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
