### PR TITLE
Introducing WrappedFileSystem for transactions

### PR DESCRIPTION
**Pull request by samikama**
This is part of a large PR set of introducing Transactional FileSystems. The class will be updated when a follow up PR updates FileSystem class methods.

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
Hmm, this fails to build with errors such as

```
...
./tensorflow/core/platform/file_system.h:422:30: error: 'tensorflow::WrappedFileSystem::Stat' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  virtual tensorflow::Status Stat(
                             ^
./tensorflow/core/platform/file_system.h:163:30: note: hidden overloaded virtual function 'tensorflow::FileSystem::Stat' declared here: different number of parameters (2 vs 3)
  virtual tensorflow::Status Stat(const string& fname,
                             ^
./tensorflow/core/platform/file_system.h:428:30: error: 'tensorflow::WrappedFileSystem::DeleteFile' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  virtual tensorflow::Status DeleteFile(
                             ^
./tensorflow/core/platform/file_system.h:167:30: note: hidden overloaded virtual function 'tensorflow::FileSystem::DeleteFile' declared here: different number of parameters (1 vs 2)
  virtual tensorflow::Status DeleteFile(const string& fname) = 0;
                             ^
...
```

**Comment by samikama** [comment]
I guess this is because of the compiler flags `-Werror,-Woverloaded-virtual` . We want to hide the overloaded function here. Most of the time it is unintentional but we need to do that in order to be able split a big change set to smaller ones. It doesn't show up in public builds since this flag is not there. There are 2 ways I can think of to get around this compiler flag. First one is to comment arguments of the WrappedFileSystem and uncomment it when base class changes, which need to be applied to all other FileSystem derived classes as well. Or make a huge PR changing all at the same time. Which one do you prefer.

**Comment by mihaimaruseac** [comment]
You are right. Since we cannot change compile flags, let's try the first approach

**Comment by samikama** [comment]
@mihaimaruseac Done. I am going to modify other PRs and open new ones with changes in remaining filesystems however we will need to do a big change in the end to uncomment all overrides and commented arguments at once.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Agree that we will need a big change to change API at one point but that should be easily done/reviewed since it's mostly a string replace everywhere.

**Pull request merged**
