### PR TITLE
replace extend_with_weight_decay examples with extend_with_decoupled_weight_decay examples

### PR DESCRIPTION
**Pull request by miktoki**

### CODE REVIEW

**Comment by miktoki** [comment]
I signed it!

**Comment by alextp** [comment]
Please send this PR to tensorflow/addons instead; contrib is deprecated and stated to be removed so we're not making new changes to it.

**Comment by miktoki** [comment]
@alextp This is a response to https://github.com/tensorflow/tensorflow/pull/26433
which is inherently connected to the code in contrib.
There is no new code, only a correction to the existing misleading documentation. I cannot find the corresponding functions in tensorflow/addons https://github.com/tensorflow/addons/tree/master/tensorflow_addons/optimizers/python, could you redirect me to the appropriate place to add this PR?

**Comment by alextp** [comment]
I see two issues here:

 1. there's no mark-used-if-not-None and we seem to require it because of the checks in tf_should_use
 2. the assertion might not be executing even disregarding the tf_should_use mess.

Is this correct?

If so I think we should file two bugs to track these two things separately.

**Pull request closed without merging**
