### PR TITLE
[INTEL MKL] Changing import orders to fix bazel test failures with (--config=mkl) 

### PR DESCRIPTION
**Pull request by wei-v-wang**
Otherwise, there will be "libiomp5.so" No such file or directory failure.

### CODE REVIEW

**Review by caisq — CHANGES_REQUESTED** [review]
It's surprising that import order in Python can cause errors like you mentioned. 

Also, making changes like this will cause pylint errors. Is there another solution to this problem?

**Comment by wei-v-wang** [comment]
@caisq  Yes, for now there is another way to fix (while we work on figuring out a more elegant fix). 
We want to modify ./configure.py so that it appends the following line to the .tf_configure.bazel_rc 

write_to_bazelrc('test:mkl --action_env=LD_LIBRARY_PATH="%s"' % (os.getcwd()+"/bazel-out/k8-opt/bin/_solib_k8/_U\@mkl_Ulinux_S_S_Cmkl_Ulibs_Ulinux___Uexternal_Smkl_Ulinux_Slib")) 

We wanted to expose the LD_LIBRARY_PATH containing the libiomp5.so to bazel test command. 

If the above change is ok, I will create the PR for review.  Otherwise, we will try a third approach. Thanks!

**Comment by wei-v-wang** [comment]
The commit that introduced/affected the libiomp5 library loading issue was https://github.com/tensorflow/tensorflow/commit/98f22653431e67e77e5889198357c152a8a0fae7 
where pybind_extension was changed to tf_python_bind_extension.  Do you have any suggestions how to overcome the side-effect of library loading issue? This did not affect "bazel build --config=mkl", but only "bazel test --config=mkl".  
Currently our workarounds are to explicitly pass to bazel in one way or another an action_env that has LD_LIBRARY_PATH set to the libimop5.so file.  
Thanks for any suggestions in advance!

**Comment by caisq** [comment]
cc @av8ramit For thoughts. Please see @wei-v-wang 's comments above regarding the build issues the recent pybind11 changes has caused to the INTEL MKL build.

**Comment by caisq** [comment]
cc @penpornk

**Comment by wei-v-wang** [comment]
Thanks @caisq 
In the meantime, do you like the following fix better? 
We want to modify ./configure.py so that it appends the following line to the .tf_configure.bazel_rc

write_to_bazelrc('test:mkl --action_env=LD_LIBRARY_PATH="%s"' % (os.getcwd()+"/bazel-out/k8-opt/bin/_solib_k8/_U@mkl_Ulinux_S_S_Cmkl_Ulibs_Ulinux___Uexternal_Smkl_Ulinux_Slib"))

Thanks!

**Comment by penpornk** [comment]
I think fixing the linking options is better. 
@gunan, what do you think about the proposed solution in https://github.com/tensorflow/tensorflow/pull/33029#issuecomment-538155728?

**Comment by caisq** [comment]
Adding @penpornk to Rewiewer list, as she's working with the MKL group more closely.

I'm just providing drive-by comments to code relating to python/debug and core/debug. I don't have informed opinions about the build infrastructure.

**Review by penpornk — COMMENTED** [review]
@gunan Oops, sorry I linked to the wrong comment. https://github.com/tensorflow/tensorflow/pull/33029#issuecomment-538528459

**Comment by wei-v-wang** [comment]
Thanks everyone for your review. Our team figured out an elegant fix. Thanks @agramesh1 and @mahmoud-abuzaina ! 

https://github.com/tensorflow/tensorflow/pull/33058 deprecates this PR. Hence closing.

**Pull request closed without merging**
