### PR TITLE
Fixing LocallyConnected2D and LocallyConnected1D layer Save Model to tf issue

### LINKED ISSUE #47689: layers.LocallyConnected2D throws error when saving a model in tf, saving in .h5 works
Hi, tensorflow community

I'm playing around with LocallyConnected2D and found some weird error when I tried to save a model (model.save).

When I gave the layer implementation=1, the model was saved without any errors.
But, if I set implementation=2, it gave me this error.

Traceback (most recent call last):
  File "/home/tonglab/Documents/Project/PycharmProjects/LCN/LCN_Keras/LocalConn2d_Keras.py", line 84, in <module>
    model.save('keras1')
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2002, in save
    signatures, options, save_traces)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 157, in save_model
    signatures, options, save_traces)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 89, in save
    save_lib.save(model, filepath, signatures, options)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1033, in save
    obj, signatures, options, meta_graph_def)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1198, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1133, in _build_meta_graph_impl
    checkpoint_graph_view)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 151, in list_functions
    self._serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2613, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 3087, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 94, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 79, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 57, in _get_serialized_attributes_internal
    serialization_cache))
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 155, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 274, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 193, in wrap_layer_functions
    fn.get_concrete_function()
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 549, in get_concrete_function
    self.call_collection.add_trace(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 423, in add_trace
    fn.get_concrete_function(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 550, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 527, in wrapper
    ret = method(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 570, in call_and_return_conditional_losses
    call_output = layer_call(inputs, *args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/layers/local.py", line 615, in call
    self.compute_output_shape(inputs.shape))
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/layers/local.py", line 782, in local_conv_matmul
    [K.shape(output_flat)[0],] + output_shape.as_list()[1:])
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3020, in reshape
    return array_ops.reshape(x, shape)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 195, in reshape
    result = gen_array_ops.reshape(tensor, shape, name)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8378, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 540, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.

My tensorflow version is 2.4.1.

Any advice will be appreciated.
Thank you.

### LINKED ISSUE #48584: Models having locally connected layers with implementation = 2 or 3 cannot be saved in SavedModel format.
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Colab, so binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7

**Describe the current behavior**
This issue is a continuation of #47689 . Whenever the user opts for `implementation=2` or `implementation=3`, the model cannot be saved as a SavedModel format.  

**Describe the expected behavior**
One should be able to save it as SavedModel format.

**Standalone code to reproduce the issue**
Please see the gist [here](https://colab.research.google.com/gist/AdityaKane2001/c74692d463f14517d84ee9be9443941d/tfpr_maker.ipynb).

**Other info**
I have played around a bit with the source code in the colab environment. I have inserted many `logging_ops.print_v2(...)` statements to make it easier to debug. Also, I have cloned my fork (it's a clean fork, no personal commits) and ran the `local_test.py` file. I have added `model_2.save('model2')` line, too check for the issue.

**Some observations:**
1. The `local.py`  file has no errors (none that I found). But many function calls can be updated as they are deprecated.
2. The `K.reshape` or `array_ops.reshape` calls are the ones that are causing the issue. There's some bug in  `tensorflow/python/framework/op_def_library.py  : _apply_op_helper(op_type_name, name=None, **keywords)` function. 
3. Note that `local.py: 790` calls `reshape`, which calls `gen_array_ops.reshape`, which calls `op_def_library._apply_op_helper`. But the arguments that go to the latter **were not recorded in `**keywords` argument.**  I checked that by printing the keywords dict in the error message. 

Please take a look at the error log under local_test.py execution cell in the colab notebook.
Thanks.

### PR DESCRIPTION
**Pull request by ashutosh1919**
Fixes #48584 and #47689 .

### My understanding:
The model save is failing because at the time of saving, `call()` of LocallyConnected2D will be invoked which is not passed with any inputs (None). That is why `compute_output_shape` and `local_conv_matmul` fails and thus `save` fails.

### Solution that I propose:
We particularly don't require any input data at the time of saving. So, I am saving the input_shape at the time when LocallyConnected2D instance is `build()` and whenever the parameter `inputs` is `None` in `call()`, I am replacing `inputs` with the dummy tensor with shape `input_shape` which was saved in `build()`.

Any suggestions on optimisation of solution are welcomed.

cc @mihaimaruseac , @bhack , @ AdityaKane2001

### CODE REVIEW

**Comment by bhack** [comment]
Can you add a test to cover the mentioned tickets case?

**Comment by AdityaKane2001** [comment]
@ashutosh1919 
I ran your code in colab. I made a model with one LocallyConnected2D layer. I passed a random numpy array to the model. Then I tried to save the model, but the notebook crashed due to excessive RAM usage. Gist [here](https://colab.research.google.com/gist/AdityaKane2001/8fb5ba3fb81b4e37021817eb5a65d629/locallyconnectedpr.ipynb#scrollTo=JMg1oc5bl05h).

**Comment by ashutosh1919** [comment]
@AdityaKane2001 , how are you running code in my branch? I see direct import `import tensorflow as tf` in the gist you shared above.
Also, try reducing the size of the np array. I tried with (10,10,10,3) and works fine in your gist.

**Comment by AdityaKane2001** [comment]
@ashutosh1919 
It's sort of a small hack but it works for small changes. I replaced the changed files in local.py of the colab session with your code before importing tensorflow. It then uses the new code.
Actually, it's my fault, I forgot to add `implementation = 2` for LocallyConnected2D .

**Comment by AdityaKane2001** [comment]
Updated gist [here](https://colab.research.google.com/gist/AdityaKane2001/7816a20a2340aa5bfe13f1a2ea4aca97/locallyconnectedpr.ipynb). I have used your code as mentioned above. Still facing the same error.

**Comment by ashutosh1919** [comment]
@AdityaKane2001 , I have resolved the error and added test cases. And btw, I think you can't just change the code for `local.py` in collab. I think you need to `bazel build` again if you change the code. 

@bhack , I have added the test case to save all 3 implementation of models and the problem is there for `LocallyConnected1D` as well. So, I have fixed the code in that too. Bazel tests are passing in my local. Can you please approve the PR so that the external build tests can run?

### Solution (Attempt 2):
Actually at the time of `save()`, it is not that `No inputs are passed`, Inputs are passed but the shape of that is something like `(None, None, None, 2)` which is not the conventional shape (None, 4, 4, 2). So, the solution is, 
- To store the shape of input whenever the layer is built.
- Whenever call() is invoked, check whether any of the dimension shape other than first one is `None`. If yes, then replace `input_shape` with `stored_input_shape` otherwise proceed as it is.

Any other suggestions on this are welcome. Also I would suggest you to please review code and suggest changes because I have raised `ValueErrors` as well as `tf_logging.warn` and I am not sure about the messages that I am populating in that. It may need correction.

cc @mihaimaruseac @fchollet

**Comment by AdityaKane2001** [comment]
@ashutosh1919 
AFAIK, it works because we are altering the python code, which is in the very last layer of the API system. 

Anyways, apart from that, everything looks good. 👍

**Review by k-w-w — CHANGES_REQUESTED** [review]
Thanks for the fix! 

It looks like the LocallyConnected layer is failing as you noted, the input shapes have `None` in them. This is due to the input_spec being used as the inputs (for most Keras built-in layers using the input spec is fine, but not for LocallyConnected layers):

A simple fix would be overwriting this property to the LocallyConnected1D and LocallyConnected2D:
```
class LocallyConnected1D:
  ...
  @property
  def _use_input_spec_as_call_signature(self):
    return False
```

**Comment by ashutosh1919** [comment]
@k-w-w , Thanks for straight forward and easy solution. I got to learn something new here. 
I have made required changes. Please review.

**Review by k-w-w — APPROVED** [review]
Thanks !

**Pull request merged**
