### PR TITLE
Disable AWS S3 virtual addressing

### PR DESCRIPTION
**Pull request by yongtang**
The fix disables the virtual addressing of AWS S3, as was suggested in the comment https://github.com/tensorflow/tensorflow/issues/16397#issuecomment-360654674

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by drpngx** [comment]
Could we add a comment about that in the interface of the open call?

**Comment by rmlarsen** [comment]
@drpngx looks OK to you?

**Comment by drpngx** [comment]
@yongtang Actually, I was thinking about something in `s3_file_system.h`. A comment reflecting what the rules are about the bucket (e.g. how they are extracted from here):
https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/s3_file_system.cc#L96

Thanks!

**Comment by yongtang** [comment]
Thanks @drpngx. A section of comment has been added in `s3_file_system.h` to explain the behavior of S3 Client used. Please take a look and let me know if there are any issues.

**Review by drpngx — APPROVED** [review]

**Pull request merged**
