### PR TITLE
change tf.image.decode_image to tf.io.decode_image

### PR DESCRIPTION
**Pull request by Angus-Luo**
tf.image.decode_image to tf.io.decode_image for API migration and consistency which include decode_ jpeg, decode_gif, and decode_png.
Please see https://www.tensorflow.org/api_docs/python/tf/io/decode_image

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
Afaik, `tf.io.decode_image` is currently just an alias for `tf.image.decode_image`. But since the later might get removed in the future, it's ok to replace usage with the more consistent alias.

**Comment by Angus-Luo** [comment]
Oh...Sorry, I accidentally dismissed mihaimaruseac's review approval and added four more commits to this PR during the experiment with vscode pull request extension. Any way I can withdraw these four changes...

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
`git rebase` and then `git push -f`. But it seems copybara merged some of the PR, so closing this and let's create another one to fix

**Comment by Angus-Luo** [comment]
@mihaimaruseac Thank you. I will create another one later.

**Pull request closed without merging**
