### PR TITLE
Added additional information from Keras.io

### PR DESCRIPTION
**Pull request by elainecrutchley**

### CODE REVIEW

**Comment by gbaned** [comment]
@elainecrutchley please sign cla

**Comment by gbaned** [comment]
@elainecrutchley gentle ping to sign cla

**Comment by elainecrutchley** [comment]
i believe it's signed now, thanks

**Review by tanzhenyu — APPROVED** [review]

**Comment by gbaned** [comment]
@elainecrutchley can you please check build failures.

**Comment by gbaned** [comment]
@elainecrutchley Did you get a chance to check build failures? Please let us know on the update. Thanks!

**Comment by gbaned** [comment]
@elainecrutchley Could you please check build failures and resolve the conflicts? Thanks!

**Comment by gbaned** [comment]
@elainecrutchley gentle ping to check build failures and resolve the conflicts? Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
