### PR TITLE
Swift 3 wrapper around c interface. 

### PR DESCRIPTION
**Pull request by johndpope**
From comments here @rxwei
https://github.com/tensorflow/tensorflow/issues/19

It's apparent that the c wrapper is limited - and there's no feature parity matching python api. 
In order to progress swift - we need more of the python functionality to be ported to c interface.
Or a path forward using the services layer. 

I wonder if this c porting could be done automagically using some off the shelf library?
http://stackoverflow.com/questions/4650243/convert-python-program-to-c-c-code

### CODE REVIEW

**Comment by johndpope** [comment]
I signed it!

**Comment by johndpope** [comment]
@rxwei  - Hi Richard, can you sign the contributor license? 
https://cla.developers.google.com/

**Comment by rxwei** [comment]
Hey @johndpope, my previous commit was highly incomplete and not ready for merge. Would you have time implementing `Session`, `Tensor`, `Graph` to make it at least able to execute a graph on trained params?

**Comment by jhseu** [comment]
Thanks for the contribution! We'd prefer not to commit language bindings to the tensorflow repository that the core TensorFlow team won't yet maintain.

I'm happy to do code review on the Swift bindings and link to them on `tensorflow.org` when they're functional, though.

**Comment by jhseu** [comment]
Also, mind elaborating what you need that's in Python but not available in the C API yet?

The C API is intended to be complete for running inference tasks, such as on mobile phones.

**Comment by johndpope** [comment]
hi @jhseu,

apologies for late reply.
fyi @rxwei  - I have succesfully generated  grpc wrappers for all tensorflow services in swift.
https://github.com/nubbel/swift-tensorflow/
(there's a script to auto build in different target languages too / java /cpp)

@jhseu - When you asked previously about the api and what was missing - the answer would be everything that's in python and not in the c api. There is a growing interest, I imagine one day swift will supercede python for server side development. maybe swift v5.
https://github.com/tensorflow/tensorflow/issues/19

My idea when digging into this was one day to sit down and build graphs in swift instead of using python.  so having a library as deep as the python api is would be the best.
https://github.com/petewarden/tensorflow_makefile/blob/49c08e4d4ff3b6e7d99374dc2fbf8b358150ef9c/tensorflow/g3doc/api_docs/python/index.md

the grpc / from my reading is like how the c++ library currently works
 in that it's mostly for 'control the execution of a graph'
https://github.com/petewarden/tensorflow_makefile/blob/49c08e4d4ff3b6e7d99374dc2fbf8b358150ef9c/tensorflow/g3doc/api_docs/cc/index.md
in that effect / the corresponding swift tensorflow package could do that today (via grpc).

To move forward on original vision - I need to put all the bits of the puzzle together - but alas - it would never completely fulfill my intention of building the graph in swift. From reading into swig / this doesn't have support for swift. https://github.com/swig/swig/issues/981

there's an attempt to auto scaffold swift code from cpp 
https://github.com/sandym/swiftpp
but I'm reluctant to dive down that path as the cpp library I believe has parity with only the grpc services. 

I guess grpc could find a home with swift and end user if it was wired up to behave like sourcekitten / xcode in that as you type in editor it's executing the code and getting responses from the rpc calls.  

I'm enjoying learning about grpc / swift microservices in any case. 

A question to ponder - could you do everything in python today if you were using python via grpc (the old adage eating your own dog food comes to mind - but it describes what I need from google to flesh out my swift project)

I'm off to the pub.

**Comment by johndpope** [comment]
hi @jhseu,

fyi - you may consider linking to this swift port
 https://github.com/PerfectlySoft/Perfect-TensorFlow

**Comment by tirrorex** [comment]
@johndpope one might say that a swift port unusable on iOS is not a swift port.
More like server-side swift tensorflow

**Comment by johndpope** [comment]
@tirrorex  - there's been some developers pushing things forward. 
to do a vanillla swift + tensorflow app - I'm only aware of 
https://github.com/xmartlabs/Bender

there's more updates (swift server side libraries) here - 
https://github.com/tensorflow/tensorflow/issues/19

For my needs / Bender couldn't handle a neural net that was not specific to images. 
https://github.com/xmartlabs/Bender/issues/21

**Comment by tirrorex** [comment]
@johndpope yes i bumped into Bender yesterday after some research, doesn't seem to be anything else unfortunatly.

**Pull request closed without merging**
