### PR TITLE
Read full message in ReadBinaryProto().

### LINKED ISSUE #27375: ReadBinaryProto in tensorflow/core/platform/env.cc may report success on partial input
The code is calling proto->ParseFromCodedStream(&coded_stream), without also calling coded_stream.ConsumedEntireMessage(). This can result in ReadBinaryProto reporting success after reading just part of the input stream, returning a partially instantiated proto from data that didn't actually encode the desired proto in binary format.

### PR DESCRIPTION
**Pull request by hlsyounes**
Add call to coded_stream.ConsumedEntireMessage() in ReadBinaryProto() to
ensure that full message is read, and that ReadBinaryProto() does not
report success on a partial read.

Closes #27375.

### CODE REVIEW

**Comment by vrv** [comment]
I'm not super familiar with the message reading proto APIs, but this seems like a sensible change.  Is there a test one could write that would have highlighted the problem, or is it difficult to trigger the partial read?

**Comment by gunan** [comment]
I am not a good reviewer for this change. Please redirect.

**Comment by hlsyounes** [comment]
I encountered a problem in code that would first try to read a file as a binary proto, and would fall back on reading it as a text proto. It would sometimes accept a text proto as binary, which made it not fall back on reading it as a text proto and resulted in garbage. With this change, I don't have that problem. I suppose I could try to distill a minimal test case out of that scenario, if you think it is worth it. I don't know how easy it would be.

I would typically use MessageLite::ParseFromString() to parse from binary, which ends up calling this code:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/message_lite.cc#L164

ReadBinaryProto() ought to look the same as that. The documentation for MessageLite::ParseFromCodedStream() says a call to ConsumedEntireMessage() is expected to follow.

**Comment by vrv** [comment]
I guess it's fine to just use the API as specified and skip the test, given that there may not be an easy way to trigger this behavior in a test that we could write.

**Review by vrv — DISMISSED** [review]

**Comment by hlsyounes** [comment]
Added changes to MemmappedFileSystem. It seems like a bug in the implementation, which resulted in files having padded length. This made it look like the proto file had not been fully read, resulting in a read error with the added call to ConsumedEntireMessage() in ReadBinaryProto().

**Review by vrv — APPROVED** [review]
Approving based on approval given by original author of mmaped file system code.

**Pull request merged**
