### PR TITLE
Make this not UnboundLocalError if the actual TF_NewStatus failed.

### LINKED ISSUE #7356: Potential UnboundLocalError in error-handling context manager
I'm working on unrelated things while this came up, and it's possibly unlikely to happen in real development, but just to track it in case someone cares,

https://github.com/tensorflow/tensorflow/blob/5e5dc97dd3523509ce5f536d7be5122d016fc6b5/tensorflow/python/framework/errors_impl.py#L471

that is an `UnboundLocalError` if it was line 463 that raised there (i.e. if TF_NewStatus failed entirely).

Without any insider knowledge, possibly that line belongs outside the try block.

### PR DESCRIPTION
**Pull request by Julian**
Closes #7356.

Doesn't look like there are previous tests here, so unfortunately submitting this without any new tests, but if I've missed where they live let me know.

### CODE REVIEW

**Comment by Julian** [comment]
I signed it!

As usual, after having to spend 5 minutes reverse engineering how that CLA page handles switching between multiple signed-in Google accounts. Seems it's impervious to the `/u/1/` that GMail uses, and to the `&authuser=1` that other places use. Glad this is easy in 2017.

Sorry, it's early in the morning, snark is irresistable.

**Review by girving — APPROVED** [review]

**Comment by girving** [comment]
Thank you!  I'll merge once the tests complete.

**Comment by girving** [comment]
Jenkins, test this please.

**Comment by girving** [comment]
@Julian Thank you for the fix!

**Comment by Julian** [comment]
Thank you!

**Pull request merged**
