### PR TITLE
TfLite floor_mod.cc compilation warning fix

### PR DESCRIPTION
**Pull request by Dayananda-V**

### CODE REVIEW

**Review by karimnosseir — DISMISSED** [review]

**Comment by rthadur** [comment]
@Dayananda-V please resolve conflicts

**Comment by Dayananda-V** [comment]
@rthadur 

conflicts resolved now.

**Comment by rthadur** [comment]
@karimnosseir can you please review this PR

**Comment by Dayananda-V** [comment]
Corrupt PR is replaced with #27369

**Pull request closed without merging**
