### PR TITLE
fix link for installing page

### PR DESCRIPTION
**Pull request by superyyrrzz**

### CODE REVIEW

**Comment by benoitsteiner** [comment]
@superyyrrzz Can you sign the CLA please ?

**Comment by superyyrrzz** [comment]
I have signed it using superyyrrzz@gmail.com. It's my GitHub account's primary email.

**Review by benoitsteiner — APPROVED** [review]

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
