### PR TITLE
Fix crash in tf.eye when input is large

### LINKED ISSUE #57711: tf.keras.backend.eye crash (abort) with large input
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0-dev20220914

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Mobile device

_No response_

### Python version

3.7.6

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

N/A

### GPU model and memory

_No response_

### Current Behaviour?

`tf.keras.backend.eye` and `tf.eye` crash (abort) with large input

Also reproduced in this [gist](https://colab.research.google.com/drive/1UEeiUYXSKSU1cBqUs01d_M1RkXgSflEw?usp=sharing)

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.keras.backend.eye(size=2752212975)
```

```shell
import tensorflow as tf
tf.eye(2752212975)
```

### Relevant log output

```shell
2022-09-15 18:51:32.477313: F tensorflow/core/framework/tensor_shape.cc:572] Check failed: size >= 0 (0 vs. -1542754321)
Aborted (core dumped)
```
</details>

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to fix the issue raised in #57711 where tf.eye will crash when input is large.
This PR fixes #57711.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by cantonios — APPROVED** [review]

**Review by pak-laura — APPROVED** [review]

**Review by cantonios — CHANGES_REQUESTED** [review]
We're seeing failures:
```
[ RUN      ] EyeTest.testInvalidInput
F0930 11:46:41.503842    8433 shape_inference.h:888] Check failed: val >= 0 || val == InferenceContext::kUnknownDim Dimension must be non-negative or equal to InferenceContext::kUnknownDim but got -1542754321
```
Can you address this?

**Comment by yongtang** [comment]
Thanks @cantonios a lot for the help! I have made an attempt to fix the test failure shown. Can you give it a try and see if the internal tests will pass?

**Comment by gbaned** [comment]
Hi @yongtang Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @yongtang Can you please resolve conflicts? Thank you!

**Pull request closed without merging**
