### PR TITLE
Branch 192821482

### PR DESCRIPTION
**Pull request by qlzh727**
Fixing XLA test

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by qlzh727** [comment]
@yifeif the windows build seems broken, which might related to cl/192784701, can u take a look?

**Comment by yifeif** [comment]
`ERROR: 'remote' is an invalid value for spawn strategy`
@meteorcloudy is this related to the new remote_cache flag or bazel version upgrade?

**Comment by qlzh727** [comment]
Its already Friday midnight in Germany. Do u want to do a rollback for that change?

**Comment by qlzh727** [comment]
Also, seems that the OS presubmit test is bit different from the internal test, which did not catch the error.

**Review by annarev — APPROVED** [review]

**Comment by yifeif** [comment]
Let's revert. I'll send you a change.

**Comment by jhseu** [comment]
Closing because the other pull request has been merged.

**Pull request closed without merging**
