### PR TITLE
Update XNNPACK for support Windows

### PR DESCRIPTION
**Pull request by mattn**
This change add support Windows of XNNPACK delegate.

https://github.com/google/XNNPACK/pull/383

XNNPACK did not support Windows until yesterday. I sent pull-request to XNNPACK and pthreadpool and the pull-requests were merged. Now XNNPACK works on Windows. So this change update commit-id to enable Windows support of XNNPACK delegate.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
What does this change bring?

**Comment by mattn** [comment]
Sorry my too short description. XNNPACK did not support Windows until yesterday. I sent pull-request to XNNPACK and pthreadpool and the pull-requests were merged. Now XNNPACK works on Windows. So this change update commit-id to enable Windows support of XNNPACK delegate.

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
Thank you

**Comment by mihaimaruseac** [comment]
Can you fix builds please?

```
ERROR: /tmpfs/tmp/bazel/external/XNNPACK/BUILD.bazel:1854:1: @XNNPACK//:XNNPACK depends on @pthreadpool//:pthreadpool in repository @pthreadpool which failed to fetch. no such package '@pthreadpool//': java.io.IOException: Error extracting
```

(one of the errors from the sanity build)

**Comment by mattn** [comment]
Probably, mirror server is not ready?

https://github.com/tensorflow/tensorflow/pull/37225/files#diff-a9d9ac7fcfb09fe0b85976cdcad9ccbeR11

**Comment by mattn** [comment]
How to fix this?

image

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Mirror should be ready now

**Pull request merged**
