### PR TITLE
Fix bug in image_captioning_with_attention.ipynb

### LINKED ISSUE #23465: Bug in image_captioning_with_attention.ipynb
**System information:** ***Running the notebook on Colab.***

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): Colab ('1.12.0-rc2')
- Python version: Colab (3.6)
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: Colab
- GPU model and memory: Colab

**Describe the current behavior**

Error in Cell 27 (Training): 

`InvalidArgumentError: indices[37,0] = 5001 is not in [0, 5001) [Op:ResourceGather] name: rnn__decoder_1/embedding_1/embedding_lookup/`

**Describe the expected behavior**

If `tokenizer.word_index[tokenizer.oov_token] = top_k + 1` in Cell 10 is commented out, the notebook runs end-to-end on Colab. 

**Code to reproduce the issue**

The reason this happens could be because in Cells 9 and 10, Tokenizer is defined with `oov_token="<unk>"` in Cell 9, which assigns "\<unk\> : 1" in the token dictionary, and then `tokenizer.word_index[tokenizer.oov_token] = top_k + 1` in Cell 10 assigns "\<unk\>: top_k + 1" which makes the number \<unk\> was previously assigned to non-existent in the dictionary and causes trouble during lookup. 

The following demonstration explains why we can get an error when we refer to the dictionary later on. 

```
import tensorflow as tf
tf.enable_eager_execution()
import re
import numpy as np

sent = "<start> Alice in wonderland. <end>"
sent2 = "<start> When suddenly Alice saw a White Rabbit. <end>"
x_train = [sent, sent2]

top_k = 5
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=top_k, 
                                                  oov_token="<unk>", 
                                                  filters='!"#$%&()*+.,-/:;=?@[\]^_`{|}~ ')
tokenizer.fit_on_texts(x_train)
train_seqs = tokenizer.texts_to_sequences(x_train)
tokenizer.word_index = {key:value for key, value in tokenizer.word_index.items() if value <= top_k}
print(tokenizer.word_index)
idx = tokenizer.word_index['<unk>'] #saving the original index of '<unk>'
tokenizer.word_index[tokenizer.oov_token] = top_k + 1 # the problematic line
print(tokenizer.word_index)
index_word = {value:key for key, value in tokenizer.word_index.items()}
index_word[idx]
```

`Output:`
```
{'<unk>': 1, '<start>': 2, 'alice': 3, '<end>': 4, 'in': 5}
{'<unk>': 6, '<start>': 2, 'alice': 3, '<end>': 4, 'in': 5}
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-55bbbd305835> in <module>()
     11 print(tokenizer.word_index)
     12 index_word = {value:key for key, value in tokenizer.word_index.items()}
---> 13 index_word[idx]

KeyError: 1
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-58-03bc9960ded7> in <module>()
     19             for i in range(1, target.shape[1]):
     20                 # passing the features through the decoder
---> 21                 predictions, hidden, _ = decoder(dec_input, features, hidden)
     22 
     23                 loss += loss_function(target[:, i], predictions)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    755       if not in_deferred_mode:
    756         self._in_call = True
--> 757         outputs = self.call(inputs, *args, **kwargs)
    758         self._in_call = False
    759         if outputs is None:

<ipython-input-54-b844d20e3fc2> in call(self, x, features, hidden)
     16 
     17     # x shape after passing through embedding == (batch_size, 1, embedding_dim)
---> 18     x = self.embedding(x)
     19 
     20     # x shape after concatenation == (batch_size, 1, embedding_dim + hidden_size)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    755       if not in_deferred_mode:
    756         self._in_call = True
--> 757         outputs = self.call(inputs, *args, **kwargs)
    758         self._in_call = False
    759         if outputs is None:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/embeddings.py in call(self, inputs)
    175     if dtype != 'int32' and dtype != 'int64':
    176       inputs = math_ops.cast(inputs, 'int32')
--> 177     out = embedding_ops.embedding_lookup(self.embeddings, inputs)
    178     return out
    179 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/embedding_ops.py in embedding_lookup(params, ids, partition_strategy, name, validate_indices, max_norm)
    311       name=name,
    312       max_norm=max_norm,
--> 313       transform_fn=None)
    314 
    315 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/embedding_ops.py in _embedding_lookup_and_transform(params, ids, partition_strategy, name, max_norm, transform_fn)
    131     if np == 1 and (not transform_fn or ids.get_shape().ndims == 1):
    132       with ops.colocate_with(params[0]):
--> 133         result = _clip(array_ops.gather(params[0], ids, name=name),
    134                        ids, max_norm)
    135         if transform_fn:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py in gather(***failed resolving arguments***)
   2671     # TODO(apassos) find a less bad way of detecting resource variables without
   2672     # introducing a circular dependency.
-> 2673     return params.sparse_read(indices, name=name)
   2674   except AttributeError:
   2675     return gen_array_ops.gather_v2(params, indices, axis, name=name)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py in sparse_read(self, indices, name)
    756         tape.variable_accessed(self)
    757       value = gen_resource_variable_ops.resource_gather(
--> 758           self._handle, indices, dtype=self._dtype, name=name)
    759     return array_ops.identity(value)
    760 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_resource_variable_ops.py in resource_gather(resource, indices, dtype, validate_indices, name)
    611       else:
    612         message = e.message
--> 613       _six.raise_from(_core._status_to_exception(e.code, message), None)
    614 
    615 

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: indices[37,0] = 5001 is not in [0, 5001) [Op:ResourceGather] name: rnn__decoder_1/embedding_1/embedding_lookup/
```

### PR DESCRIPTION
**Pull request by joaak**
Fixes #23465 as discussed in the issue's comments.

### CODE REVIEW

**Comment by joaak** [comment]
Signed the CLA!

**Comment by yashk2810** [comment]
@MarkDaoust This notebook will be different than the one in docs after this PR has been merged :smile:

**Review by alextp — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by joaak** [comment]
@yashk2810 @aaroey @alextp hey guys, anything I can help with to close this PR?

**Comment by rmlarsen** [comment]
I'm pulling this PR manually now.

**Comment by rmlarsen** [comment]
This was merged.

**Comment by joaak** [comment]
Thank you!

**Pull request merged**
