### PR TITLE
[ROCm] Bazel build and continuous integration infrastructure

### PR DESCRIPTION
**Pull request by whchung**
This pull request is to start introduce support for ROCm platform to TensorFlow. In this initial pull request, 2 components are addressed:

- bazel build system
- continuous integration logic

Authors:
- Jack Chung: jack.chung@amd.com
- Jeffrey Poznanovic: Jeffrey.Poznanovic@amd.com
- Peng Sun: Peng.Sun@amd.com

### CODE REVIEW

**Comment by whchung** [comment]
CLA signed

**Comment by whchung** [comment]
signed CLA

**Comment by whchung** [comment]
signed CLA

**Comment by whchung** [comment]
signed CLA

**Comment by dagamayank** [comment]
CLA signed.

**Pull request closed without merging**
