### PR TITLE
Immediate execution mode with graph caching.

### PR DESCRIPTION
**Pull request by yaroslavvb**
Implementation of immediate mode execution in TensorFlow. The idea is to wrap original tensorflow API, but provide session/run management logic so that commands execute immediately, and graph caching to avoid modifying graph when same op is run repeatedly. Data is kept in TensorFlow runtime whenever possible using persistent tensors and transferred to Python runtime on demand when needed for printing/control flow.

```
import tensorflow as tf
from tensorflow.contrib import immediate

tfi = immediate.Env(tf).tf        # wraps "tf" namespace, saves it as "tfi"
val1 = tfi.ones((3,))             # creates tensor on GPU
val2 = val1 + val1                # runs into tf.add, keeps result on GPU
val3 = tfi.ones((2, 2, 2, 2))
val4 = tfi.nn.conv2d(val3, val3, [1, 1, 1, 1], "VALID")   # run CuDNN conv2d
if (tfi.reduce_sum(val3)>0.):     # runs reduce_sum on GPU, transfers bool to CPU
  print(val4)                     # transfers whole tensor to CPU for display

```

This is a single commit rebase of a previous pull request from https://github.com/tensorflow/tensorflow/pull/2346

@keveman @yuanbyu

### CODE REVIEW

**Comment by yaroslavvb** [comment]
Sorry, I'm opening new pull request since I don't know how to fix this
https://github.com/tensorflow/tensorflow/pull/2747

With my current work-flow, when I rebase, the pull request includes all the commits that I fast forward through while rebasing. Here's the sequence of commands I've been using for rebase so that people know not to do this:   
http://stackoverflow.com/questions/37707605/doing-rebase-adds-replays-master-branch-commits-into-my-pull-request

**Comment by vrv** [comment]
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by keveman** [comment]
I tried the following :

    import tensorflow as tf
    from tensorflow.contrib import immediate
    tfi = immediate.Env(tf).tf
    
    val1 = tfi.ones((3,))
    val2 = val1 + val1

and got :

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/tmp/imm_venv/local/lib/python2.7/site-packages/tensorflow/contrib/immediate/python/immediate/itensor.py", line 103, in __add__
        return self.env.tf.add(self, other)
      File "/tmp/imm_venv/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 70, in add
        result = _op_def_lib.apply_op("Add", x=x, y=y, name=name)
      File "/tmp/imm_venv/local/lib/python2.7/site-packages/tensorflow/contrib/immediate/python/immediate/op.py", line 158, in apply_op
        name=op_name)
    TypeError: get_session_tensor() takes at least 2 arguments (2 given)

Do you think you forgot to commit and push some changes?

**Comment by yaroslavvb** [comment]
It looks like https://github.com/tensorflow/tensorflow/commit/bf8084b71006123575c6416d69efdd00c13fe41c has changed the signature of `get_session_tensor`, let me update it with new sig

**Comment by yaroslavvb** [comment]
So I just sequence below which brought a bunch of extra commits. [hood-devel](https://github.com/yaroslavvb/tensorflow/tree/hood-devel) is my develoment branch which is one commit ahead of master, and hood is my pull request branch, and merging hood-devel into hood like below pulls new commits into pull request for some reason

```
git checkout hood-devel
git merge -s ours hood
git checkout hood
git merge hood-devel
git push

```

**Comment by girving** [comment]
Jenkins, test this please.

**Comment by yaroslavvb** [comment]
There's a failure in `//tensorflow/tools/test:check_futures_test` in `Linux CPU Tests (Python 3) — FAILURE `. I can run it locally with `bazel test //tensorflow/tools/test:check_futures_test` and it passes. Any suggestions how I can see the logs/reproduce the failure?

**Comment by yaroslavvb** [comment]
I think I fixed test_util issue, can someone trigger tests again? I believe failure it's caused by "bazel test" not being hermetic. If you build pip package and do `python setup.py develop`, then future `bazel test` will prefer try to grab python files from pip-package path, rather than dependencies specified for the test in `BUILD` file . Work-around is to make sure all Python files make it into pip package

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by yaroslavvb** [comment]
Tweaked/disabled some failing tests caused by Jenkins environment being different from mine. Didn't have any luck debugging 2to3 failure in Python3 compatibility test (bazel [issue #1393](https://github.com/bazelbuild/bazel/issues/1393)), but this is ready for another Jenkins run

**Comment by girving** [comment]
Jenkins, test this please.

**Comment by yaroslavvb** [comment]
On this [ci.tensorflow.org](http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/731/consoleFull) I see failure in `tensor_handle_test`, but it doesn't give any details, is there a way to see the log file linked `/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/workspace/bazel-out/local_linux-py3-opt/testlogs/tensorflow/contrib/immediate/tensor_handle_test/test.log` ?

**Comment by martinwicke** [comment]
This kind of error is usually because you don't have srcs_version = "PY2AND3" on some python target. I see a bunch of cases in your BUILD files, so maybe that's it?

**Comment by yaroslavvb** [comment]
@martinwicke maybe, although that particular test already had `PY2AND3` on its deps. I've added it on all targets anyway, could you trigger the tests again?

**Comment by girving** [comment]
Jenkins, test this please.

**Comment by yaroslavvb** [comment]
There was [internal commit](https://github.com/tensorflow/tensorflow/commit/a558c6e3b38846727873b5afbbc3ba309ae5dff5) yesterday that moved some libraries around and broke immediate, just updated it with the fix. PS: I'm going traveling at the end of next week, let me know if there's something I can do to help get this in before it bit rots.

**Comment by ebrevdo** [comment]
Jenkins, test this please.

**Comment by keveman** [comment]
@yaroslavvb Thanks for working on this and sending the PR. Imperative mode of execution is a really important feature that many users have asked for. While your implementation is impressive, it doesn't support a major feature that users ask for and we would like to get working, namely, automatic differentiation via `tf.gradients`. We believe the best way to implement the imperative mode that is efficient and would allow automatic differentiation to work out of the box would need some significant support in the backend. We are working on adding that support currently. I will keep you posted on its progress.

**Comment by yaroslavvb** [comment]
So is the gradient support an alternative to this implementation, or is it something that can be built on top?

**Comment by keveman** [comment]
It's an alternative implementation.

**Comment by yaroslavvb** [comment]
Closing this to spin it off into stand-alone library

**Pull request closed without merging**
