### PR TITLE
Fixed bug in Variable assign method

### PR DESCRIPTION
**Pull request by PiyushDatta**
@alextp , reference to #29178.

Please review changes. I think the best approach is to convert it to a TensorShape rather than giving an error. Also made a simple test to catch this error in the future.

Test results for testAssignMethod:

Ran 1 test in 0.099s
OK

### CODE REVIEW

**Comment by alanhdu** [comment]
@PiyushDatta I think the best solution would actually be to convert `self._shape` to a `tf.TensorShape` in the constructor and not during `assign`. `shape` is part of the public API of `tf.Variable`, and so having it be "type-stable" would be a plus for downstream libraries.

Specifically, I think changing:
https://github.com/tensorflow/tensorflow/blob/db88fe602f290ebd98127774b375d32f5eb44f19/tensorflow/python/ops/resource_variable_ops.py#L612

to something like:

```python
if shape is None:
  self._shape = shape if isinstance(shape, tf.TensorShape) else tf.TensorShape(shape)
else:
  self._shape = initial_value.shape
```

**Comment by PiyushDatta** [comment]
@alanhdu Ahh yes, that's a much better way. It would be a plus for the downstream libraries and other methods within the class.

I'll fix and test it later today after work. Thanks!

**Review by alextp — DISMISSED** [review]
Thanks!

**Comment by PiyushDatta** [comment]
@alextp Just fixing pylint errors, please see latest commit.

Previous errors:
FAIL: Found 2 non-whitelited pylint errors:
tensorflow/python/ops/resource_variable_ops.py:1146: [W0311(bad-indentation), ] Bad indentation. Found 10 spaces, expected 8
tensorflow/python/kernel_tests/resource_variable_ops_test.py:582: [C0301(line-too-long), ] Line too long (91/80)

**Review by alextp — APPROVED** [review]

**Comment by PiyushDatta** [comment]
Pretty sure these errors are not related to my changes, but if so, just let me know.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by rthadur** [comment]
@PiyushDatta please find the build errors here https://source.cloud.google.com/results/invocations/69263a9e-17e4-435d-865c-fb572c71cec8/log

**Comment by PiyushDatta** [comment]
@rthadur can you please review the builds again. It was an internal error, which got fixed. Builds should be okay now, only the internal CI ones are failing, which are not because of these changes.

Let me know if you need anything else!

**Comment by rthadur** [comment]
sure , let try to merge it internally , thank you

**Comment by PiyushDatta** [comment]
Hi @yifeif, 
I think there are still some internal build errors, can you please have a look? Thank you!
Mainly: "import/copybara — An error happened while migrating the change (Required)"

**Comment by alextp** [comment]
@PiyushDatta I see errors in the non-internal build as well. forwardprop_test seems to be failing on the GPU with this error

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test_gpu.runfiles/absl_py/absl/testing/parameterized.py", line 265, in bound_param_test
    test_method(self, *testcase_params)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test_gpu.runfiles/org_tensorflow/tensorflow/python/eager/forwardprop_test.py", line 326, in testKerasLayers
    order=2)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test_gpu.runfiles/org_tensorflow/tensorflow/python/eager/forwardprop_test.py", line 140, in _test_gradients
    testcase.assertAllClose(num_jac, sym_jac_back, rtol=rtol, atol=atol)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test_gpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1125, in decorated
    return f(*args, **kwds)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test_gpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 2466, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test_gpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 2413, in _assertAllCloseRecursive
    (path_str, path_str, msg))
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test_gpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 2368, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg="\n".join(msgs), equal_nan=True)
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/nose_tools/utils.py", line 1396, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.01, atol=0.0001
Mismatched value: a is different from b.
not close where = (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([ 0,  0,  1,  3,  3,  4,  6,  7, 11, 12, 12, 13, 14, 16, 17, 17, 18,
       19, 19, 20, 21, 23, 24, 25, 25, 26, 27, 27, 28, 28, 29, 31, 31]), array([3, 4, 4, 2, 5, 5, 5, 5, 0, 0, 1, 1, 0, 5, 3, 5, 4, 3, 5, 4, 5, 5,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 3]))
not close lhs = [-0.00023842 -0.00023842  0.00023842 -0.00023842  0.00023842  0.00023842
 -0.00023842 -0.00023842  0.00023842 -0.00023842 -0.00023842  0.00023842
  0.00023842 -0.00023842 -0.00023842 -0.00047684  0.00023842 -0.00023842
  0.00023842 -0.00023842 -0.00023842  0.00023842 -0.00023842  0.00023842
  0.00023842  0.00023842  0.00023842 -0.00023842 -0.00023842  0.00023842
  0.00023842 -0.00047684  0.00023842]
not close rhs = [ 3.7252903e-09  7.5364621e-09 -2.8786111e-09 -0.0000000e+00
 -6.5703709e-10  4.9943186e-08 -8.9793595e-09  1.1850787e-08
  2.2516321e-08 -1.8626451e-08 -1.1175871e-08  3.7252903e-09
  1.8626451e-08 -4.0597794e-08  3.7252903e-09 -4.1271591e-09
 -7.4720514e-09 -7.4505806e-09 -4.6350308e-08 -9.8335642e-09
 -2.6019722e-09 -2.3952033e-08  4.4531854e-09  1.6381053e-08
  4.4777888e-09  3.0752762e-08  3.2235008e-08  1.0935484e-09
  3.4924597e-10 -5.5879354e-09  1.4901161e-08  1.1175871e-08
  0.0000000e+00]
not close dif = [0.00023842 0.00023843 0.00023842 0.00023842 0.00023842 0.00023837
 0.00023841 0.00023843 0.0002384  0.0002384  0.00023841 0.00023841
 0.0002384  0.00023838 0.00023842 0.00047683 0.00023843 0.00023841
 0.00023846 0.00023841 0.00023842 0.00023844 0.00023842 0.0002384
 0.00023841 0.00023839 0.00023839 0.00023842 0.00023842 0.00023842
 0.0002384  0.00047685 0.00023842]
not close tol = [1.00000034e-04 1.00000070e-04 1.00000027e-04 9.99999975e-05
 1.00000005e-04 1.00000500e-04 1.00000085e-04 1.00000114e-04
 1.00000223e-04 1.00000187e-04 1.00000107e-04 1.00000034e-04
 1.00000187e-04 1.00000405e-04 1.00000034e-04 1.00000041e-04
 1.00000070e-04 1.00000070e-04 1.00000463e-04 1.00000099e-04
 1.00000027e-04 1.00000238e-04 1.00000041e-04 1.00000165e-04
 1.00000041e-04 1.00000303e-04 1.00000318e-04 1.00000012e-04
 9.99999975e-05 1.00000056e-04 1.00000143e-04 1.00000107e-04
 9.99999975e-05]
dtype = float32, shape = (1, 32, 6)
(mismatch 17.1875%)
 x: array([[[-9.996890e-01, -9.377002e-01,  0.000000e+00, -2.384186e-04,
         -2.384186e-04,  0.000000e+00],
        [-8.749961e-01, -8.125305e-01,  0.000000e+00,  0.000000e+00,...
 y: array([[[-1.000000e+00, -9.374999e-01, -1.117587e-08,  3.725290e-09,
          7.536462e-09,  1.286564e-08],
        [-8.750000e-01, -8.124999e-01, -2.607703e-08,  3.725290e-09,...
```

**Comment by rthadur** [comment]
@PiyushDatta can you please check latest comments ?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Comment by PiyushDatta** [comment]
@rthadur 
Hi, 
Sorry, currently busy with work and interviews. Will re-open and look at this again in early November. Thanks.

**Pull request closed without merging**
