### PR TITLE
make_one_shot_iterator API have changed

### PR DESCRIPTION
**Pull request by yuanxiaosc**
tf.compat.v1.data.make_one_shot_iterator(dataset)  to  tf.data.Dataset.make_one_shot_iterator(dataset)

### CODE REVIEW

**Comment by yuanxiaosc** [comment]
I signed it!

googlebot <notifications@github.com> 于2018年12月17日周一 下午3:13写道：

**Review by jsimsa — CHANGES_REQUESTED** [review]
`make_one_shot_iterator` is going away in V2 and so the proposed change is incorrect

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jsimsa: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Review by jsimsa — CHANGES_REQUESTED** [review]
the original version is correct, your change will not work when TF default switches to 2.0

**Comment by rthadur** [comment]
closing this PR based on latest comments.

**Pull request closed without merging**
