### PR TITLE
[android demo] add check to SpeechActivity.java for call requestPermissions only with API>=23

### PR DESCRIPTION
**Pull request by ArtsiomCh**
`requestPermissions` call possible only with API>=23
`minSdkVersion` set to 21 for the Project. 
Hence check required, otherwise, on devices with API 21 and 22 we'll get the error:
```
...
09-02 15:14:21.979 24890-24890/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.tensorflow.demo, PID: 24890
                                                                     java.lang.NoSuchMethodError: No virtual method requestPermissions([Ljava/lang/String;I)V in class Lorg/tensorflow/demo/SpeechActivity; or its super classes (declaration of 'org.tensorflow.demo.SpeechActivity' appears in /data/app/org.tensorflow.demo-1/split_lib_slice_7_apk.apk)
                                                                         at org.tensorflow.demo.SpeechActivity.requestMicrophonePermission(SpeechActivity.java:160)
...
```

### CODE REVIEW

**Comment by ArtsiomCh** [comment]
Sorry guys. Looks like I've messed up with this PR GitHub branch :( Trying just to add another small commit and rebased on the upstream branch...
Just cleaned up my local branch and push it as new remote branch here: https://github.com/ArtsiomCh/tensorflow/tree/SpeechActivity
Should I force push to this PR branch my cleaned local branch? Or Should I close that PR and reopen another one based on my clean branch? Or may be you know a better solution how to solve that?...
I'm sorry again, unfortunately, I'm not too proficient with Git...

**Comment by petewarden** [comment]
Thanks for this PR, it's a good catch!

> Should I force push to this PR branch my cleaned local branch?

I think this might be the easiest way. I'm not too proficient with git though either, so if this gets too sticky feel free to open a clean PR and link to it in a comment here, we can continue the review there.

**Comment by ArtsiomCh** [comment]
Just did force push. Looks like it solved the mess. :)
My second commit 84218e21424d64078c5dc2102443a1d66e4233b6 add call of `startRecording()` for the API<23. Originally it was called only at `onRequestPermissionsResult()` which is never executed when API<23, so Recording thread was never invoked.
Unfortunately, even after that fix, I can see through the debugger (and injecting some additional Log output into the code) that recognition works but do not animate label at `labelsListView` on the Activity screen. 
For me it looks like the problem is somewhere inside that piece of code:
```Java
...
                final View labelView = (View) labelsListView.getChildAt(labelIndex - 2);
                ValueAnimator colorAnimation =
                     ValueAnimator.ofArgb(0x00b3ccff, 0xffb3ccff, 0x00b3ccff);
                colorAnimation.setDuration(750);
                colorAnimation.addUpdateListener(
                    new ValueAnimator.AnimatorUpdateListener() {
                      @Override
                      public void onAnimationUpdate(ValueAnimator animator) {
                        labelView.setBackgroundColor((int) animator.getAnimatedValue());
                      }
                    });
                colorAnimation.start();
...
```

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by yifeif** [comment]
@petewarden are we ready to merge this PR? Thanks!

**Comment by drpngx** [comment]
@petewarden good to go?

**Comment by sb2nov** [comment]
@petewarden ping

**Review by andrewharp — APPROVED** [review]

**Comment by sb2nov** [comment]
Jenkins, test this please

**Pull request merged**
