### PR TITLE
Branch 169629054

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Review by frankchn — APPROVED** [review]

**Comment by msarett** [comment]
I believe this re-breaks https://github.com/tensorflow/tensorflow/issues/1924.

All of the jpeg symbols are now exported in `libtensorflow_framework.so`.

**Comment by drpngx** [comment]
@msarett can you find the commit that caused the issue?

**Comment by msarett** [comment]
Sorry I meant to indicate this one:
5c7f9e316d8c7735308a217310350d416d7498cc

**Comment by drpngx** [comment]
Thanks! Continuing discussion on the original bug.

**Pull request merged**
