### PR TITLE
[XLA-CPU] adding a check to handle large constant 

### PR DESCRIPTION
**Pull request by ashiqimranintel**
This PR will help to avoid unnecessary copies of large constants among multiple clusters. It improves performance, especially on GNN models with large constant stems from graph embeddings.

### CODE REVIEW

**Comment by keerthanakadiri** [comment]
Hi @MichaelHudgins, Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @MichaelHudgins, Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @MichaelHudgins, Can you please review this PR? Thank you !

**Review by chsigg — APPROVED** [review]

**Review by chsigg — APPROVED** [review]

**Comment by ashiqimranintel** [comment]
@chsigg , thanks for approving the PR, I was wondering why it's not merged yet.

**Comment by ashiqimranintel** [comment]
@chsigg , looks like, the PR got rollback, what could be the reason for it?

**Comment by ashiqimranintel** [comment]
@chsigg , @penpornk  any update on this PR?

**Pull request merged**
