### PR TITLE
contrib:get_variables_and_layers

### PR DESCRIPTION
**Pull request by shravankumar147**
Here are two function to extract layer names and respective variable values, also an example provided in jupyter-notebook.

### CODE REVIEW

**Review by frankchn — CHANGES_REQUESTED** [review]
Hmm, I am not sure this should be placed here. Perhaps somewhere under `tensorflow/examples/` is a better place?

**Comment by shravankumar147** [comment]
Moved the example notebook to tensorflow/examples, but still not sure about the  right place. Suggest if any changes still required.

**Review by shravankumar147 — COMMENTED** [review]
Moved

**Comment by machinelearning147** [comment]
Used different email address while committing changes. No objections in the contribution. please approve the cla and review the changes.

**Comment by machinelearning147** [comment]
I signed cla

**Comment by shravankumar147** [comment]
@frankchn I've updated as suggested.

**Comment by frankchn** [comment]
Yeah I am still not sure you should place an ipynb file in tensorflow/examples. Let me bring in @wolffg and @MarkDaoust, who might have a better idea of where to put this.

**Comment by shravankumar147** [comment]
@frankchn @wolffg @MarkDaoust 
However, the notebook is to just show how to use my two main contributions, i.e., `tensorflow/python/util/get_layer_names.py` and `tensorflow/python/util/get_variable_values.py`. These two are the main features, which automatically extracts Parameters of the model from a saved model.

**Comment by shravankumar147** [comment]
@googlebot cla-signed please update the label.

**Comment by machinelearning147** [comment]
> 😕 The bad news is that it appears that one or more commits were authored by someone other than the pull request submitter. We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that here in the pull request.

With respect to the above statement, I would like to confirm that I am okay with the contributions or comments. So, I request to please approve and proceed further.

**Pull request closed without merging**
