### PR TITLE
Einsum dynamic shape bug fix

### PR DESCRIPTION
**Pull request by eaplatanios**
I fixed a bug in einsum that did not allow for dynamic tensor shapes. I'm not sure if that's the only change necessary and I'm also not sure what conventions you follow to write tests for this, so since I have a paper deadline approaching I'll leave it at that for now. It seems to be working fine for me but I haven't tested any edge cases.

### CODE REVIEW

**Comment by eaplatanios** [comment]
I signed it!

**Comment by martinwicke** [comment]
Yeah, we should wait on this one until tests are added. Simply add a test that unsets the shape before calling `einsum` should test the new behavior.

**Comment by vrv** [comment]
Ping for @eaplatanios

**Comment by vrv** [comment]
Closing due to lack of activity and to clear out back log -- ping back or open a new PR if you still want to get this in!  We have an internal change also making huge changes to einsum it seems, so might be worth waiting for that too.

**Pull request closed without merging**
