### PR TITLE
Fix Conv3DTranspose in tf.keras

### PR DESCRIPTION
**Pull request by d02k01**

### CODE REVIEW

**Comment by mktozk** [comment]
I signed it!

**Review by fchollet — APPROVED** [review]

**Comment by mktozk** [comment]
Fix tf.layers.conv3d_transpose as stated in https://github.com/tensorflow/tensorflow/issues/15655#issuecomment-359504564

**Comment by rmlarsen** [comment]
@fchollet would you please take another look at the changes made after your approval?

**Comment by rmlarsen** [comment]
@mktozk thanks for the contribution!

**Pull request merged**
