### PR TITLE
Fix benchmark_model compilation for Windows

### PR DESCRIPTION
**Pull request by Jukyy**
Adding #ifdef block around unistd.h header.

### CODE REVIEW

**Comment by gbaned** [comment]
@Jukyy Can you please sign CLA. Thank you!

**Review by sirakiin — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Please sign CLA before this can be merged

**Comment by Jukyy** [comment]
> Please sign CLA before this can be merged

@mihaimaruseac don't worry I will, I am just waiting for an approval of higher ups.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Merging manually since Copybara/GitHub integration seems to consider this to be a conflict

**Pull request closed without merging**
