### PR TITLE
[ROCm] Fixes to enable triangular solve unit test for BEF thunk on ROCm.

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
Not sure if these changes are necessary, but...

/cc @chsigg @hanbinyoon

### CODE REVIEW

**Comment by chsigg** [comment]
This looks good and clean, but I'm missing where these constants are defined. Was there another PR that I missed?

**Comment by rsanthanam-amd** [comment]
> This looks good and clean, but I'm missing where these constants are defined. Was there another PR that I missed?

Sorry for the confusion, but the constants are defined in a separate commit as part of: https://github.com/tensorflow/tensorflow/pull/54926

**Comment by chsigg** [comment]
Hi Rohit, would you mind to rebase this change? Thanks!

**Comment by rsanthanam-amd** [comment]
> Hi Rohit, would you mind to rebase this change? Thanks!

Done.

**Comment by rsanthanam-amd** [comment]
I used git rebase instead of git merge - I hope that was the right thing to do.

**Comment by chsigg** [comment]
No, this PR now touches 200 files.

**Comment by rsanthanam-amd** [comment]
Closing this and creating a new PR.

**Pull request closed without merging**
