### PR TITLE
[ROCm] fixed rocm_solvers build

### PR DESCRIPTION
**Pull request by i-chaochen**
this has updated rocm_solvers due to XLA gpu executor changes.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @cheshire Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @cheshire Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @cheshire , Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @cheshire , Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @cheshire , Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @cheshire , Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @cheshire , Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @i-chaochen, Can you please resolve the conflicts? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @i-chaochen, Can you please resolve the conflicts? Thank you !

**Pull request closed without merging**
