### PR TITLE
Fix : Argument missing in TPUClusterResolver.connect

### PR DESCRIPTION
**Pull request by edwardyehuang**
FIX: `TPUClusterResolver.connect` missing argument

### CODE REVIEW

**Comment by keerthanakadiri** [comment]
Hi @fionalang, Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @fionalang, Can you please review this PR? Thank you !

**Comment by edwardyehuang** [comment]
> Hi @fionalang, Can you please review this PR? Thank you !

Has Google completely abandoned TensorFlow? If so, I will shift my development focus to Jax. @keerthanakadiri @gbaned

**Comment by keerthanakadiri** [comment]
> > Hi @fionalang, Can you please review this PR? Thank you !
> 
> Has Google completely abandoned TensorFlow? If so, I will shift my development focus to Jax. @keerthanakadiri @gbaned

Hi @edwardyehuang , Sorry for the delay in response.  This PR is in awaiting review status. Thank you for your patience and understanding.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
