### PR TITLE
Add Apache Arrow Support to TensorFlow Dataset

### LINKED ISSUE #23001: Add Support for Apache Arrow in TensorFlow Dataset
Apache Arrow is a standard format for in-memory columnar data. It provides a cross-language platform for systems to communicate and operate on data efficiently.

Adding Arrow support in TensorFlow Dataset will allow systems to interface with TensorFlow in a well defined way, without the need to develop custom converters, serialize data, or write to specialized files.

It would be straightforward to add a base layer of Arrow support that works on Arrow record batches (a common struct for Arrow IPC) and extend that layer to support different kinds of Arrow Ops:

* Python memory / Pandas DataFrames
* Arrow Feather files
* Parquet files
* Socket / Pipes

A slightly more involved Op could use Arrow Flight - Arrow-based messaging over gRPC.  Additionally, it would possible to define Ops to connect directly to other systems that can export Arrow data.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master branch
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.17.1
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.1
- **GPU model and memory**: Quadro M1000M 4G
- **Exact command to reproduce**: N/A

### PR DESCRIPTION
**Pull request by BryanCutler**
Apache Arrow is a standard format for in-memory columnar data. It provides a cross-language platform for systems to communicate and operate on data efficiently.

Adding Arrow support in TensorFlow Dataset will allow systems to interface with TensorFlow in a well defined way, without the need to develop custom converters, serialize data, or write to specialized files.

This PR defines an Arrow base layer that will create a TensorFlow Dataset with an iterator over Arrow record batches to produce Tensor values for each column. This base layer is then extended to implement three Dataset Ops that consume Arrow record batches: 1) from Python memory / Pandas DataFrames, 2) Reading Arrow Feather files, 3) Input stream with a socket client to connect to a server streaming Arrow record batches. These are implemented now because they are straightforward and can provide some good initial functionality, but the design here should allow for more Arrow Ops in the future.

fixes #23001

### CODE REVIEW

**Comment by BryanCutler** [comment]
This is currently a WIP, but wanted to open the PR to open discussion.  Still needed:

- [ ] Make sure all reasonable data types are supported
- [ ] Tests are currently very simple, need to expand them
- [ ] Socket impl is only enabled for posix
- [ ] Clean up some rough edges

**Comment by BryanCutler** [comment]
@yongtang I saw that you are adding a Parquet Dataset in #19461. There is a lot of overlap since the parquet-cpp reader is based on Arrow. I believe that the parquet-cpp reader can produce Arrow record batches that could then leverage the base classes here that iterate over the batches. It would be nice to have a common Arrow layer in TensorFlow Dataset that is easy to extend for specific Ops. Would you be interested in collaborating?

**Comment by BryanCutler** [comment]
cc @frreiss @feihugis

**Comment by yongtang** [comment]
@BryanCutler Yes it would be great to have a common layer for Arrow. PR #19461 has been approved, and is awaiting for bazel update (to 0.17.1) in #22449 to be merged. I think the arrow part could be consolidated once in.

**Comment by dmitrievanthony** [comment]
Hi @BryanCutler, PR looks very promising! I see you implemented only Posix sockets so far, let me suggest you to have a look at Apache Ignite Dataset (#22210). In this dataset I implemented Windows sockets as well as Posix, it might be helpful.

**Comment by BryanCutler** [comment]
> I see you implemented only Posix sockets so far, let me suggest you to have a look at Apache Ignite Dataset

Thanks @dmitrievanthony !  I would have liked to use boost asio, but I'm not sure if it's worth adding the dependency for that. If it's been done for Windows too in Apache Ignite Dataset, I'll take a look there and try to do the same.

**Comment by yongtang** [comment]
@BryanCutler The PR #19461 has boost dependency in place so it might be less of an issue for adding asio. Though boost dependency only works with bazel 0.17.1+ (that is also the reason merge of #19461 is blocked now).

**Comment by galv** [comment]
As a suggestion, you could consider making this a separate python package, which depends on both tensorflow and apache arrow to build. The tooling around these kinds of python packages with binary dependencies is still very new, but doable. Tensorflow *does* export its dataset header files. They are not under the API stability guarantees, but they have been fairly stable from what I observed (two method signatures changed trivially in 1.10, I believe). OF course, @mrry knows more, as the author.

I myself have made my own Dataset in an external project, using cmake. I don't have a ready-made example, but I know that arrow use cmake as well, so it is very easily doable to have this live separately from the tensorflow repo. You can follow up with me about that.

I mention this because tensorflow/contrib is going away.

Super cool work, by the way! I remember chatting with a Databricks engineer at the Spark Summit about how Arrow could be a great complement to Project Hydrogen.

**Comment by yongtang** [comment]
@BryanCutler See related discussion about `tensorflow/contrib` and dataset related`tensorflow/io`, that will likely happen in tensorflow 2.0: 

https://github.com/tensorflow/community/pull/18

FYI @dmitrievanthony @mrry @ewilderj @martinwicke

**Comment by BryanCutler** [comment]
Thanks for the info @galv and @yongtang, it sounds like a lot of things are in transition right now. Since `contrib` is going away, are no new additions being accepted there now?

**Comment by yongtang** [comment]
@BryanCutler When `tensorflow/contrib` is deprecated, Dataset related components could be moved to the planned `tensorflow/io` so it will not be a concern at that time. /cc @dmitrievanthony @mrry 

In the short term though, I guess it may depend on the length of the transition period. If 2.0 is imminent then PR may not be accepted. (the PR could be opened to `tensorflow/io` then).

Don't know the planned date of 2.0 yet. Maybe @martinwicke have some insight about the 2.0 schedule?

**Comment by martinwicke** [comment]
We announced we wouldn't accept new projects into contrib when we announced 2.0. 

I think this is an obvious candidate for sig-io. @ewilderj how far are we with sig-io? I think we're looking for a date, right?

Moving there will delay this for at least a few weeks as we have to set up the sig-io repo and integration. But if we were to accept this here, it would simply have to be moved to sig-io anyway, and I don't think there will be another TF release which could include this before sig-io is off the ground, so I think the extra work is not too useful.

**Comment by ewilderj** [comment]
I created the mailing list for SIG IO (announcement on developers@ list) and am recruiting for interest for that group. Once we've got a few folks signed up we can kick off the SIG with a conference call and get things moving.

**Comment by BryanCutler** [comment]
Thanks for the replies @ewilderj and @martinwicke. I signed up to the SIG and am looking forward to the discussions, thanks!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @mrry: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 24 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @mrry: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 39 days with no activity and the `awaiting review` label has been applied.

**Comment by mrry** [comment]
I removed myself as reviewer, since it looks like this is going to go through the SIG IO process instead.

**Comment by gunan** [comment]
I am not involved in sig-io
I think you are looking for @yongtang

**Comment by BryanCutler** [comment]
This PR has been moved to https://github.com/tensorflow/io/pull/36 and can be closed

**Pull request closed without merging**
