### PR TITLE
[PluggableDevice] Add range checks to TF_ExpectedOutputDataType in non-debug builds

### PR DESCRIPTION
**Pull request by PatriceVignola**
The header comments of `TF_ExpectedOutputDataType` mention that the program aborts when passing an out-of-bounds index, but in non-debug builds we get an AV instead since `OpKernelContext::expected_output_dtype` uses `DCHECK_GE` and `DCHECK_LT` instead of `CHECK_GE` and `CHECK_LT`.

### CODE REVIEW

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Review by penpornk — APPROVED** [review]
Thank you for the PR and I'm so sorry for the delay!

**Comment by PatriceVignola** [comment]
@penpornk How can I see the reason for the Code Check and Intel oneDNN failures?

**Comment by penpornk** [comment]
@PatriceVignola You can click on the `Details` links.

For [Code Check details page](https://storage.cloud.google.com/tensorflow-nightly/prod/tensorflow/github/docker/code_check_changed_files_presubmit/1636/20220315-074701/index.html), click the [ResultStore](https://source.cloud.google.com/results/invocations/bb9bb501-fd97-4d9b-93a6-3cf2b137fec1) link under the `Non-Googler Links` section. You will see a list of failed targets. Click on [pkg/code_check_changed_files](https://source.cloud.google.com/results/invocations/bb9bb501-fd97-4d9b-93a6-3cf2b137fec1/targets/pkg%2Fcode_check_changed_files) to see the error message. (Just C++ formatting errors.)

```
(in test file /usertools/code_check_changed_files.bats, line 36)
  `[[ ! -s $BATS_TEST_TMPDIR/needs_help.txt ]]' failed
clang-format is recommended. Here are the suggested changes:
=============================
diff --git a/tensorflow/c/kernels_test.cc b/-
index ac09d2f633d..00000000000 100644
--- a/tensorflow/c/kernels_test.cc
+++ b/-
@@ -28,7 +28,6 @@ limitations under the License.

 #include "absl/container/inlined_vector.h"
 #include "absl/strings/str_format.h"
-#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
 #include "tensorflow/c/c_api.h"
 #include "tensorflow/c/tf_datatype.h"
 #include "tensorflow/c/tf_status.h"
@@ -53,6 +52,7 @@ limitations under the License.
 #include "tensorflow/core/platform/status.h"
 #include "tensorflow/core/platform/test.h"
 #include "tensorflow/core/platform/types.h"
+#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"

 struct MyCustomKernel {
   bool created;
@@ -678,13 +678,11 @@ TEST(TestKernel, TestInputAndOutputCount) {

     EXPECT_EQ(TF_UINT8, TF_ExpectedOutputDataType(ctx, 0));

-    EXPECT_DEATH({
-      TF_ExpectedOutputDataType(ctx, 1);
-    }, "Check failed: i < cc_ctx->num_outputs");
+    EXPECT_DEATH({ TF_ExpectedOutputDataType(ctx, 1); },
+                 "Check failed: i < cc_ctx->num_outputs");

-    EXPECT_DEATH({
-      TF_ExpectedOutputDataType(ctx, -1);
-    }, "Check failed: i >= 0");
+    EXPECT_DEATH({ TF_ExpectedOutputDataType(ctx, -1); },
+                 "Check failed: i >= 0");

     TF_DeleteStatus(s);
     if (input != nullptr) {
You can use clang-format --style=Google -i <file> to apply changes to a file.
```

For [oneDNN details page](https://tensorflow-ci.intel.com/job/tensorflow-mkl-linux-cpu-pr/12675/), click on [oob_unittest.log](https://tensorflow-ci.intel.com/job/tensorflow-mkl-linux-cpu-pr/12675/artifact/oob_unittest.log) under the `Build Artifacts` section. The failures seem to be unrelated to this PR.
```
======================================================================
ERROR: testKerasInteropSequential (__main__.VariableTest)
VariableTest.testKerasInteropSequential
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/numpy_ops/np_interop_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/numpy_ops/np_interop_test.py", line 316, in testKerasInteropSequential
    model = tf.keras.Sequential(
  File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/numpy_ops/np_interop_test_cpu.runfiles/org_tensorflow/tensorflow/python/training/tracking/base.py", line 620, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 60, in error_handler
    return fn(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/keras/engine/sequential.py", line 109, in __init__
    super(functional.Functional, self).__init__(  # pylint: disable=bad-super-call
  File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/numpy_ops/np_interop_test_cpu.runfiles/org_tensorflow/tensorflow/python/training/tracking/base.py", line 620, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 60, in error_handler
    return fn(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/keras/engine/training.py", line 279, in __init__
    self._checkpoint = tf.train.Checkpoint(root=weakref.ref(self))
  File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/numpy_ops/np_interop_test_cpu.runfiles/org_tensorflow/tensorflow/python/training/tracking/util.py", line 2111, in __init__
    _assert_trackable(root, "root")
  File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/numpy_ops/np_interop_test_cpu.runfiles/org_tensorflow/tensorflow/python/training/tracking/util.py", line 1552, in _assert_trackable
    raise ValueError(
ValueError: `Checkpoint` was expecting root to be a trackable object (an object derived from `Trackable`), got <weakref at 0x7f1264db84a0; to 'Sequential' at 0x7f1264fdb9a0>. If you believe this object should be trackable (i.e. it is part of the TensorFlow Python API and manages state), please open an issue.
```

I don't think you need to do anything. I'll just pull this PR in manually and fix the formatting.

**Pull request merged**
