### PR TITLE
Tests for ParallelInterleaveDatasetOp

### PR DESCRIPTION
**Pull request by feihugis**
This PR adds 

- the comparison function to identify whether two tensor vectors have the same elements regarding/regardless of order.

- Tests for `ParallelInterleaveDatasetOp`.

cc: @jsimsa

### CODE REVIEW

**Review by jsimsa — APPROVED** [review]

**Comment by feihugis** [comment]
@jsimsa I will use this thread to communicate with you about the flaky issue in ParallelInterleaveDatasetOpTest, because I did not receive the notification when you pinged me under the commit(https://github.com/tensorflow/tensorflow/commit/32ff91cf4284861994b6bba2cfb8deeb2f840b7c).  

I'm wondering if you are able to see which test case causes the timeout? That will be helpful for me to debug as I could not reproduce it on my mac yet.

**Comment by jsimsa** [comment]
It is the test that I disabled. Here is a stack trace:

```
[ RUN      ] ParallelInterleaveDatasetOpTest/ParameterizedParallelInterleaveDatasetOpTest.Roundtrip/0
*** SIGTERM received by PID 8235 (TID 8235) from PID 1; stack trace: ***
PC: @     0x7fd078133ccd  (unknown)  prodkernel::api::base::InlinedSyscall6()
    @     0x7fd077f83e15       1376  FailureSignalHandler()
    @     0x7fd07786c9a0  (unknown)  (unknown)
    @     0x7fd078133c5a         64  prodkernel::api::base::Futex::WaitBitsetAbsoluteTimeout()
    @     0x7fd078133b78         48  prodkernel::api::base::Futex::WaitAbsoluteTimeout()
    @     0x7fd078133b9f         32  prodkernel::api::base::Futex::Wait()
    @     0x7fd0781339de         64  prodkernel::api::base::Futex::WaitUntil()
    @     0x7fd0781335c5        304  absl::synchronization_internal::Waiter::Wait()
    @     0x7fd077f7ed7f        320  AbslInternalPerThreadSemWait
    @     0x7fd07814602d         32  absl::synchronization_internal::PerThreadSem::Wait()
    @     0x7fd078145b74         64  absl::Mutex::DecrementSynchSem()
    @     0x7fd078142119        304  absl::CondVar::WaitCommon()
    @     0x7fd07814234a         64  absl::CondVar::Wait()
    @     0x5600a0440830         48  tensorflow::condition_variable::wait()
    @     0x5600a045775e        112  tensorflow::data::(anonymous namespace)::ParallelInterleaveDatasetOp::Dataset::ParallelInterleaveIterator::GetNextInternal()
    @     0x5600a0468518        224  tensorflow::data::DatasetBaseIterator::GetNext()
    @     0x7fd081319b03       1760  tensorflow::data::(anonymous namespace)::ParameterizedParallelInterleaveDatasetOpTest_Roundtrip_Test::TestBody()
    @     0x7fd0809c5784         96  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @     0x7fd0809b4af2        112  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x7fd0809a47c3         96  testing::Test::Run()
    @     0x7fd0809a4f4d        112  testing::TestInfo::Run()
    @     0x7fd0809a5508        112  testing::TestSuite::Run()
    @     0x7fd0809ae4f5        256  testing::internal::UnitTestImpl::RunAllTests()
    @     0x7fd0809c97f4         96  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @     0x7fd0809b6ee2        128  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x7fd0809ae0aa        112  testing::UnitTest::Run()
    @     0x7fd081092931         16  RUN_ALL_TESTS()
    @     0x7fd0810926bd         32  main
    @     0x7fd0776dabbd        208  __libc_start_main
    @     0x5600a04023e9  (unknown)  _start
```

**Comment by feihugis** [comment]
I changed `DISABLED_Roundtrip` --> `Roundtrip` to run the tests multiple times, but did not get any failures. The stack trace you posted here is helpful. Will take further look and keep you updated.

**Comment by feihugis** [comment]
I could reproduce the flaky issue now using the command ` bazel test -c opt //tensorflow/core/kernels/data:parallel_interleave_dataset_op_test --runs_per_test=20000`.

**Pull request merged**
