### PR TITLE
cherry-picks for 0.11.0rc1 

### PR DESCRIPTION
**Pull request by yifeif**

### CODE REVIEW

**Comment by yifeif** [comment]
Cherry-pick the bazel certificate issue fix as well. @tensorflow-jenkins test this please.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Comment by yifeif** [comment]
The failed GPU test has been flaky. May I get a LG?

**Comment by drpngx** [comment]
For the flakes, do you want to test these?
* fix the windows cmake: 136491988, 136504874, 136513790 
* gradients_test: 136498075

**Comment by gunan** [comment]
Windows cmake needs many more fixes in the release branch, so please ignore
that one. For gradients test lets cherrypick that as it will probably flake
in release tests too.

**Comment by yifeif** [comment]
Sounds good. Will cherrypick the fix for gradient test once #5054 is in.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Comment by gunan** [comment]
As we do not have windows support on this branch, we can call all tests passing.
Merging.

**Pull request merged**
