### PR TITLE
Remove calls to deprecated cusparse APIs

### PR DESCRIPTION
**Pull request by nluehr**
This PR replaces calls to cusparse calls that are deprecated in CUDA 10.2.

CC @pankajkgupta and @sanjoy

### CODE REVIEW

**Comment by rmlarsen** [comment]
@nluehr thanks a lot for this change. Are the changes to cusparse_10_1.inc all formatting?

**Review by rmlarsen — DISMISSED** [review]

**Comment by gbaned** [comment]
@nluehr Can you please fix build failures ? Thanks!

**Comment by nluehr** [comment]
Sorry about that. The original cusparse_10_1.inc exactly matched cusparse_10_2.inc which confused me. I updated 10_1.inc to match CUDA 10.1.105. However, it needs to match CUDA 10.1u2 (10.1.243), which happens to exactly match CUDA 10.2 as far as the cusparse API goes. So that explains why the inc files matched to begin with.
Should be fixed in latest commit.

**Review by rmlarsen — DISMISSED** [review]

**Comment by rmlarsen** [comment]
@nluehr thanks!

**Comment by pkanwar23** [comment]
@nluehr Can you please fix build failures ? Thanks.

**Review by pkanwar23 — APPROVED** [review]

**Review by rmlarsen — APPROVED** [review]

**Comment by gbaned** [comment]
@nluehr Can you please resolve conflicts? Thanks!

**Comment by deven-amd** [comment]
@penpornk 

Appreciate you looking into and fixing the ROCm build errors. Thank you.

However there seems to be some discrepancy between
* how G is testing for ROCm, and 
* how the ROCm CSB (Community Supported Build) is being run. 

ROCm CSB started failing last night as a consequence of this commit 
(see log here :  http://ml-ci.amd.com:21096/job/tensorflow-rocm-nightly/289/)

I will look into the cause of the failures and file a PR to fix them.

Can we also look into what is different between the ROCm CSB run (which uses this script : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/linux/rocm/run_csb_tests.sh ) and how G does ROCm testing? 

Thanks again.

deven

/cc @dagamayank

**Comment by penpornk** [comment]
@deven-amd Sorry about this! And thank you for looking into it. Please mention me in the PR and I can review it right away.

There was a discrepancy in our presubmit test and continuous test. Somehow the presubmit test didn't fail with [my commit](https://github.com/tensorflow/tensorflow/commit/557bd9e2457b36353cef5cff7f5eec137cd422ae) (but the other test failed after submitting). I actually had another fix ready since yesterday, but was waiting on someone from the build team to help look into this.

I'll pass your test script along to the build team. Thank you!

cc: @csigg -- FYI.

**Pull request merged**
