### PR TITLE
Enable tf.tanh() for SparseTensor

### PR DESCRIPTION
**Pull request by siddharth-agrawal**
Enabled `tf.tanh()` for `SparseTensor`. Added tests and verified locally. This partially addresses #1828.

### CODE REVIEW

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
Please rebase your repo to resolve the merge conflicts.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
Could you try to rebase your repo again to fix the test error?

**Comment by siddharth-agrawal** [comment]
@rmlarsen Done. Could you merge this in as soon as possible? I've already had to rebase twice.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by siddharth-agrawal** [comment]
@rmlarsen The tests don't seem to be running

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by siddharth-agrawal** [comment]
@rmlarsen While working on [this PR](https://github.com/tensorflow/tensorflow/pull/3122), I noticed that I missed adding tests for `tf.tanh()` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/cwise_ops_test.py#L219). I will send out a PR once the `tf.erf()` change is merged in (to avoid conflicts).

**Comment by rmlarsen** [comment]
@siddharth-agrawal Oops! should have caught that :-) Thanks for adding the tests.

**Pull request merged**
