### PR TITLE
[TFLite] Add int16x8 support for REDUCE_MIN and REDUCE_MAX operators

### PR DESCRIPTION
**Pull request by Tessil**
Hi,

This PR adds int16x8 support for the REDUCE_MIN  and REDUCE_MAX operators in TensorFlow Lite. 

It also updates the reduce operators in the BuiltinRefOpResolver to point to the reference registers. The base reduce registers uses the reference registers so it doesn't change anything functionally , it's mainly for clarity.

Thibaut

### CODE REVIEW

**Review by fredrec — APPROVED** [review]
Looks good to me, thanks for your contribution

**Comment by rthadur** [comment]
@Tessil can you please resolve conflicts

**Comment by Tessil** [comment]
@rthadur I resolved the conflicts, thanks.

**Review by rthadur — APPROVED** [review]

**Comment by gbaned** [comment]
Seems auto-merge is not happening but the changes are merged into master now, so we can close this. Thank you for the PR.

**Pull request closed without merging**
