### PR TITLE
ci_build: Upgrade the Python 'six' compatibility module

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by protoget — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by cclauss** [comment]
@pragyaak, @rthadur __six__ v1.12.0 was released during this review cycle so I created #25510

**Pull request merged**
