### PR TITLE
Tf32 fixes

### PR DESCRIPTION
**Pull request by nluehr**
Currently, enable_tensor_float_32_execution(False) does not fully disable TensorFloat32 evaluation in RNNs. This PR fixes this and also disabled TF32 execution for a few additional tests. 

Attn: @reedwm

### CODE REVIEW

**Review by reedwm — CHANGES_REQUESTED** [review]
Can you mention the fact RNN support for TF32 has been added in [RELEASE.md](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) under the "Bug Fixes and Other Changes" section

**Comment by nluehr** [comment]
Added release note. @reedwm, PTAL.

**Review by reedwm — APPROVED** [review]

**Comment by rthadur** [comment]
@nluehr can you please resolve sanity build failures ?

**Comment by nluehr** [comment]
@rthadur, Should be good to go now.

**Review by reedwm — APPROVED** [review]

**Review by rthadur — APPROVED** [review]

**Comment by gbaned** [comment]
@nluehr  Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
Seems auto-merge is not happening but the changes are merged into master now, so we can close this. Thank you for the PR.

**Pull request closed without merging**
