### PR TITLE
[Dockerfile] move stubs to the end of LD_LIBRARY_PATH

### LINKED ISSUE #36974: CUDA broken on docker image tensorflow/tensorflow:devel-gpu
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Docker Hub
- TensorFlow version: [tensorflow/tensorflow:latest-devel-gpu](https://hub.docker.com/layers/tensorflow/tensorflow/latest-devel-gpu/images/sha256-607098dc1fe31c990b2c54c37bd5c81099cad165232cb0489c35e51689de27c7?context=explore)
- Python version: python3
- Installed using virtualenv? pip? conda?: docker 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

CUDA is broken on [tensorflow/tensorflow:devel-gpu](https://hub.docker.com/layers/tensorflow/tensorflow/latest-devel-gpu/images/sha256-607098dc1fe31c990b2c54c37bd5c81099cad165232cb0489c35e51689de27c7?context=explore) image. TensorFlow could not recognize the GPUs.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

### Host Server (Debian GNU/Linux 9)

On the host server, CUDA is on 10.1. Tensorflow can detect 8 GPUs.

Run `nvidia-smi` and it shows 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
```

Verify that TensorFlow can see the 8 GPUs.
```
$ pip install tensorflow 
$ python -c 'import tensorflow as tf; print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices("GPU")))'

('Num GPUs Available: ', 8)
```

### Inside Container (tensorflow/tensorflow:devel-gpu)

Then, start the container.
```
$ docker run --gpus=all -it tensorflow/tensorflow:latest-devel-gpu-py3
```

In the container, run
```
root@5f3ceeb2248b:/# nvidia-smi
Sat Feb 22 02:06:17 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
```
Notice that the CUDA version was **ERR!**. It may indicate that the CUDA version is broken. 
Run 
```
$ pip install tensorflow 
$ python -c 'import tensorflow as tf; print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices("GPU")))'

2020-02-22 02:11:29.788170: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
2020-02-22 02:11:29.788245: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 418.87.1
Num GPUs Available:  0
```

TensorFlow could not see the GPUs.

**Any other info / logs**

### PR DESCRIPTION
**Pull request by nouiz**
Fix #36974 and maybe #38205 (not tested).
I hit #36974 again today.

See also https://github.com/tensorflow/tensorflow/issues/38205#issuecomment-637506594 and https://github.com/tensorflow/tensorflow/issues/38205#issuecomment-637505286

Maybe we could remove the stubs. But I'm not able to test if it would broke something. So I went with the safer fix.

@r4nt @angerson

### CODE REVIEW

**Comment by angerson** [comment]
Thanks! Can you follow the instructions in the dockerfiles/ directory README to update all the files, please?

**Comment by nouiz** [comment]
I amended the commit to include the change in the source file.

But I'm not able to regenerates the Dockerfiles automatically. I get errors if I try in my own shell or if I follow the instruction. Here is the error I have:
```> Error: _TAG_PREFIX is not a valid slice_set, and also isn't an arg provided on the command line. If it is an arg, please specify it with --arg. If not, check the slice_sets list.```

I do not plan to debug this error. I think my manual edit of the source and destination of the Dockerfile should be enough for this issue.

**Comment by angerson** [comment]
Ok, I'll have to do it myself if you're unable to -- but it will take more time. Thanks for your work!

**Comment by nouiz** [comment]
@angerson Is there a chance that this get finished this mount?

**Comment by cheshire** [comment]
@sanjoy

**Comment by sanjoy** [comment]
> But I'm not able to regenerates the Dockerfiles automatically. I get errors if I try in my own shell or if I follow the instruction. Here is the error I have:

Can you share full logs for this error?  In theory the regeneration tool should work fine in open source so I want to understand why it isn't working for you.

I'll separately check in an auto-generated version of this PR to unblock you as discussed in the sync today.

**Comment by sanjoy** [comment]
Created https://github.com/tensorflow/tensorflow/pull/46190.

**Comment by nouiz** [comment]
Read and tried again the instruction at: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/README.md#contributing

Those instruction aren't very clear. By the first read, I think I must execute most of those command inside the container started in the 2nd command `docker run --user $(id -u):$(id -g) -it -v $(pwd):/tf tf-tools bash`. After reading it completly, I suppose it isn't what is intended.

Here is the command to execute from the directory `tensorflow/tools/dockerfiles` to regenerates the Dockerfiles:

```
docker build -t tf-tools -f tools.Dockerfile .
alias asm_dockerfiles="docker run --rm -u $(id -u):$(id -g) -v $(pwd):/tf tf-tools python3 assembler.py "
asm_dockerfiles --release dockerfiles --construct_dockerfiles
```

Here is the error I have:

```
> Skipping release nightly
> Skipping release nightly
> Skipping release versioned
> Emptying Dockerfile dir "./dockerfiles"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1151, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1196, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1147, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 950, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 893, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1151, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1196, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1147, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 950, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 893, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/lib/python3.5/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python3.5/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "assembler.py", line 719, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "assembler.py", line 504, in main
    dock = docker.from_env()
  File "/usr/local/lib/python3.5/dist-packages/docker/client.py", line 101, in from_env
    **kwargs_from_env(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 222, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by sanjoy** [comment]
Thanks @nouiz!  @angerson any idea what's going on in the logs?

**Comment by angerson** [comment]
Thanks for the fix, Sanjoy! I'm not sure what's wrong with the logs. This looks bizarre.

Per https://github.com/tensorflow/tensorflow/issues/46062, ideally we'll deprecate this assembler system and avoid the problem entirely.

**Pull request closed without merging**
