### PR TITLE
minor eager notebook examples cleanup

### PR DESCRIPTION
**Pull request by amygdala**
Minor eager notebook examples cleanup.  See https://github.com/tensorflow/early-eager/pull/37/files

### CODE REVIEW

**Comment by amygdala** [comment]
@asimshankar has context on this.

**Comment by asimshankar** [comment]
Thanks for the PR. Looks good, but would you mind changing the remaining references to `tf.contrib.data` to `tf.data` as well?

Thanks!

**Comment by amygdala** [comment]
Sorry, I'd overlooked the comments.  I think we're set now.  PTAL.

**Review by asimshankar — APPROVED** [review]
Thanks!

**Comment by asimshankar** [comment]
Jenkins, test this please

**Pull request merged**
