### PR TITLE
Remove six.PY2

### PR DESCRIPTION
**Pull request by lithomas1**

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Can you do this for all files, please?

If it gets too large, then we can split per directory, maybe around 10 files per PR?

**Comment by lithomas1** [comment]
Hm. This is probably too large now and I might have to split it. 
Before I do that, can you please trigger CI on this PR? I cannot build from source, and just want to make sure everything works.

**Review by mdanatg — APPROVED** [review]
Nice!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
This looks good to me and not too large. So let's try first with just one PR.

**Review by mihaimaruseac — APPROVED** [review]

**Review by mdanatg — APPROVED** [review]

**Pull request merged**
