### PR TITLE
Add some information on testing to the contribution guidelines.

### PR DESCRIPTION
**Pull request by advaitjain**
Issue #42569

### CODE REVIEW

**Comment by freddan80** [comment]
@advaitjain Looks good so far, but some further info on what a contributor should test before submitting a PR would be great. Something like:

1) Run "./tensorflow/lite/micro/tools/ci_build/test_all.sh" in order to test xyz. Note: Add "-Wall -Werror" as build flags
2) Run e.g. "bazel run //tensorflow/lite/micro:micro_interpreter_test" if you have changed xyz. This test is will make sure that xyz.
3a) Run "make -f tensorflow/lite/micro/tools/make/Makefile TAGS=cmsis-nn  generate_kernel_<op_name>_test_mbed_project"
3b) cd tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/kernel_<op_name>_test/mbed
3c) mbed config root .
3d) mbed deploy
3e) mbed compile -m auto -t GCC_ARM -f --profile mbed-os/tools/profiles/release.json -D__ARM_FEATURE_DSP
      if you have make changes to the build system, since xyz.

etc. I think this may save a lot of time. 

Cheers!

**Review by njeffrie — DISMISSED** [review]
Looks like a good start. I agree with Fredrik's suggestions - perhaps they would make for a good follow-up change. In that follow-up, it may be valuable to explain common testing procedure for core platforms (perhaps make, mbed) and let others contribute instructions in their platform-specific README.

**Comment by advaitjain** [comment]
> @advaitjain Looks good so far, but some further info on what a contributor should test before submitting a PR would be great. Something like:
> 
> 1. Run "./tensorflow/lite/micro/tools/ci_build/test_all.sh" in order to test xyz. Note: Add "-Wall -Werror" as build flags
> 2. Run e.g. "bazel run //tensorflow/lite/micro:micro_interpreter_test" if you have changed xyz. This test is will make sure that xyz.
> 3. Mbed tests, if you have make changes to the build system, since xyz.
> 
> ```
> Run "make -f tensorflow/lite/micro/tools/make/Makefile TAGS=cmsis-nn  generate_kernel_<op_name>_test_mbed_project"
> cd tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/kernel_<op_name>_test/mbed
> mbed config root .
> mbed deploy
> mbed compile -m auto -t GCC_ARM -f --profile mbed-os/tools/profiles/release.json -D__ARM_FEATURE_DSP
> ```
> 
> etc.
> 
> I think this may save a lot of time.
> 
> Cheers!

Good suggestions. I have added a link to your comment from the issue. Will send a separate PR for that.

I am in the process of spending a bit more time myself as a PR author (instead of always writing code via the internal tools) and will update the guidelines as I get a chance to test them out.

**Comment by advaitjain** [comment]
@njeffrie: I had a merge conflict, so needs your review again. [Here](https://github.com/tensorflow/tensorflow/pull/42571/commits/303e22d09a175fdc1093d57fa09b44367851628b) is exactly what I had to change for the merge.

I'm keeping some notes as I figure out a workflow that works for me as a PR author and will update the guidelines once I have some more confidence in my workflow.

**Review by njeffrie — APPROVED** [review]

**Pull request merged**
