### PR TITLE
added CMake options to provide external zlib, GRPC, Eigen

### PR DESCRIPTION
**Pull request by Slonegg**
Here are changes necessary to build tensorflow with different version of GRPC, Protobuf, Eigen, zlib, etc. It is not possible to compile project using two different versions of protobuf for example. To deal with that I've chosen approach similar to one in GRPC library. Also for some reason I don't see changes from https://github.com/tensorflow/tensorflow/pull/13867 in master, thus changes from that branch are also here, @mrry might know something.

### CODE REVIEW

**Comment by mrry** [comment]
I suspect #14464 has the answer to the missing PR code... I'd suggest to wait until that is merged and then rebase.

**Comment by Slonegg** [comment]
thanks @mrry I'll ping you after then

**Comment by Slonegg** [comment]
@mrry rebased, I think it's ready for review now

**Comment by jhseu** [comment]
Please resolve conflicts. Thanks!

**Comment by Slonegg** [comment]
@jhseu rebased, there is some problem with protobuf, but doesn't seem that it is related to this PR.

**Review by mrry — APPROVED** [review]
Sorry for the long delay on this PR. Thanks for all the improvements... LGTM.

**Comment by mrry** [comment]
Arg, it looks like there's a conflict with `tensorflow/contrib/cmake/CMakeLists.txt`. Can you please resolve, and we'll run the tests? Thanks!

**Comment by Slonegg** [comment]
Here @mrry, should be ok now.

**Comment by mrry** [comment]
Thanks for resolving the conflicts!

@tensorflow-jenkins test this please.

**Comment by Slonegg** [comment]
@mrry I see that some changes in master are reverted, is that correct and I should rebase onto it or just wait a bit?

**Comment by mrry** [comment]
I think the merge should be resolved now (indeed, it looks like `include(double_conversion)` was reverted).

@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
@ whoever merges this, I think @googlebot is confused because I used the web tool to resolve the conflicts (and perhaps it doesn't have the right email address for my commit). AIUI we should still be fine to merge.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
@Slonegg could you take a look at the windows errors? Also, something went wrong on the CLA.

**Comment by Slonegg** [comment]
@drpngx windows error seems to be "Failed to checkout tag: 'b04e5cba356212e4e8c66c61bbe0c3a20537c5b9'". I usually just fork all the dependencies to avoid problems like this, library developers often change tags and commit hashes. I think we have CLA problem because @mrry made one commit.

**Comment by drpngx** [comment]
@Slonegg both commits appear to fail the CLA, according to our interface.
`ba17124ccd4e5f8bec3db824ba06d95b1b48a3ec` is also broken.

**Comment by Slonegg** [comment]
@drpngx probably something is wrong with the CLA system, mine is signed, just double-checked it right now

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
@Slonegg you have to reply to this thread: "I signed it!" and it might get it unstuck.

Jenkins, test this please.

**Comment by Slonegg** [comment]
I signed it!

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
@Slonegg we have you under the gmail address. Did you use that for the commit? Also, could you pull rebase and push again?

**Comment by Slonegg** [comment]
@drpngx I've created a copy of this PR https://github.com/tensorflow/tensorflow/pull/16210 since this one seems to be impossible to fix

**Comment by drpngx** [comment]
Thanks!

**Pull request closed without merging**
