### PR TITLE
TF Framework error_test missing test case add

### PR DESCRIPTION
**Pull request by Dayananda-V**
1-error_code_from_exception_type api test case

### CODE REVIEW

**Review by penpornk — COMMENTED** [review]
Thank you for the PR, but I don't think this is necessary. The check is redundant. `_make_specific_exception` already looks up the exception type from the error code.
https://github.com/tensorflow/tensorflow/blob/3b24c98659e87ff753f09ded2ae5b95c30610812/tensorflow/python/framework/errors_impl.py#L517-L523

And the function `error_code_from_exception_type` that you use just reads from `_EXCEPTION_CLASS_TO_CODE` which is built from `_CODE_TO_EXCEPTION_CLASS` anyway. (Both functions will always give consistent answers).
https://github.com/tensorflow/tensorflow/blob/3b24c98659e87ff753f09ded2ae5b95c30610812/tensorflow/python/framework/errors_impl.py#L503-L514

**Comment by Dayananda-V** [comment]
@penpornk 

Thanks for quick review. I added test case here to make sure both api is consistent and shouldn't be inconsistent. So additional changes is added with try catch block in error_code_from_exception_type similiar to _make_specific_exception api. 

Welcome for review comments and suggestion.

**Review by penpornk — CHANGES_REQUESTED** [review]
The test can't fail, by construction. But since it's not big, I think it's okay to have it. cc'ing @mrry for his information.

Please add a comment saying that this part checks that `error_code_from_exception_type` gives consistent answers with `exception_type_from_error_code` called in `_make_specific_exception`.

**Comment by Dayananda-V** [comment]
@penpornk 

Please review the updated changes, thanks.

**Review by penpornk — APPROVED** [review]
Thank you for the changes!

**Pull request merged**
