### PR TITLE
[INTEL MKL] re-submit rsqrt op bfloat16 support

### PR DESCRIPTION
**Pull request by cuixiaom**
the reverted PR is here: 
https://github.com/tensorflow/tensorflow/pull/43167

### CODE REVIEW

**Comment by cuixiaom** [comment]
the original PR was here:
https://github.com/tensorflow/tensorflow/pull/43167

**Review by reedwm — APPROVED** [review]

**Comment by cuixiaom** [comment]
> Unfortunately, this was rolled back since it broke an MLIR test. Will investigate.

@reedwm Do you have estimate when your test can be fixed? We need this op bf16 support is enabled, or we have to cast back and forth from fp32 to bf16 due to this op in our models when we run bf16 model. Thanks!

**Comment by reedwm** [comment]
I tried fixing and rolling forward but it was rolled back again for a different reason. Will take a look very soon and get back to you.

**Comment by reedwm** [comment]
This is failing an internal test, which I am trying to fix. I'm guessing this will be submitted early next week.

**Comment by cuixiaom** [comment]
@reedwm Thanks a lot for help!

**Comment by reedwm** [comment]
This is rolled forward now, and hasn't been rolled back again for 4 days now so I think it's in permanently :)

**Comment by cuixiaom** [comment]
@reedwm Great! Thanks a lot!

**Pull request merged**
