### PR TITLE
Add tensorflow io support in Docker container

### PR DESCRIPTION
**Pull request by dilverse**
Add tensorflow-io partial Dockerfile and updated the spec.yml file, to provide object storage support for tensorflow images out of the box as seen in [this](https://github.com/tensorflow/tensorflow/issues/58710) issue

### CODE REVIEW

**Comment by angerson** [comment]
While I appreciate the work you've done here, I prefer not to accept this change because:

- These are "officially supported" TensorFlow docker containers, and it's not our goal to include community / third-party support as well
- The complicated "partials" system is a nightmare to maintain, and we're discussing deprecation of these containers in favor of a different Docker recommendation (but no concrete plans yet).

**Comment by dilverse** [comment]
@angerson [tensorflow-io](https://github.com/tensorflow/io) is officially part of tensorflow repo, how can this be considered 3rd party and with the new `io` repo tensorflow docker images have broken support for object storage files systems that used to work before, this PR is trying to address that.

**Comment by mihaimaruseac** [comment]
`tensorflow-io` is a SIG IO project, not a Google project

**Comment by dvaldivia** [comment]
@mihaimaruseac well, `gcs` support is also part of `tensorflow-io` and it got a special separate wheel which is being added as a dependency to `tensorflow`, in this scenario, the `tensorflow-io-gcs-filesystem` is also a 3rd party isn't it? it sits on the `tensorflow-io` repo, per https://github.com/tensorflow/tensorflow/commit/7add88f2982331be6ba65ddc66f1c88053028fff it seems the split was for modularity and not to remove functionality from TF

Support for other filesystems was part of TensorFlow all the way up to `2.4`, by removing them from upstream the message we are getting is, don't use upstream for other cloud providers storage other than Google unless you really know what you are doing, which in my opinion is a very steep learning curve for anyone trying to use TF and for serious users they are not going to trust a 3rd party docker image all the time, users simply won't keep up with upstream TF since they have to built specialized docker images.

With this PR we are simply trying to return a functionality that was already present and all over the internet you can see the struggle of people trying to solve this problem over and over, the way I see the reason why there's only one tensorflow docker image for tensorflow, tensorboard and tensorflow-serve means, you prefer a one stop solution, so if the fix won't be coming to core, it should at least be in the main container image.

**Comment by mihaimaruseac** [comment]
The difference is that there is an equivalent of GCS filesystem built internally and both internal and external GCS support is tested nightly.

We need to strike a balance between what batteries are included within TF and what we ask the OSS team to support. It is unreasonable for a team of a handful of engineers to support all possible filesystems that exist out there.

**Comment by mihaimaruseac** [comment]
That would work, I think. but note that I'm no longer in TF, only doing drive by help (and should mostly focus on security stuff only). So I cannot do the decision here. Leaving to @angerson and the team

**Comment by raghav-vk** [comment]
@angerson Any suggestions as to when this PR will be merged, we have a need to leverage this change ASAP.

**Comment by angerson** [comment]
Sorry, I'm still against adding this to the official tensorflow docker containers. It would be expanding the implied support range for something that's already not very maintained to a wider scope, and ultimately wouldn't be a good precedent for us.

@learning-to-play @MichaelHudgins FYI

**Comment by learning-to-play** [comment]
Hi @raghav-vk, Having software that can be easily changed/updated is key to developer productivity. Additional support can make the code rigid and future upgrades/changes more difficult (due to incompatibilities, etc). A developer who would like to make a change in the software would also have to read and understand a broader scope. Taking into account the maintainability downsides, the proposed PR/change don't seem the best option to me.

**Comment by gbaned** [comment]
Hi @MichaelHudgins Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @dilverse Can you please resolve conflicts? Thank you!

**Comment by angerson** [comment]
These containers have been moved to https://github.com/tensorflow/build/tree/master/tensorflow_runtime_dockerfiles.

**Pull request closed without merging**
