### PR TITLE
Fix TODO avoiding serialization in gRPC/GPU path

### PR DESCRIPTION
**Pull request by byronyi**
See #10530 and #10531 for the rationale.

### CODE REVIEW

**Comment by byronyi** [comment]
Using a [modified version](https://gist.github.com/byronyi/cb4ba0f6c5815ce78924ebcdd56989b9) of local recv_tensor [benchmark script](https://gist.github.com/yaroslavvb/e196107b5e0afc834652bd3153030c42) (thanks to @yaroslavvb), the performance improvement over current master is shown below:

Current master:
```
Local rate:       23185.76 MB/s
Distributed rate: 196.11 MB/s
```

With this patch:
```
Local rate:       26588.30 MB/s
Distributed rate: 256.12 MB/s
```

**Comment by yaroslavvb** [comment]
why closed? Seems like an improvement

**Comment by byronyi** [comment]
Further investigation shows the l benchmark difference seems to come from different build options, e.g. AVX, SSE, etc. I suspect the difference is only visible after #6116 is fixed, so I'll revisit this PR then.

**Comment by byronyi** [comment]
This should be relevant now as we have the gRPC upgrade finished recently. With this change, it should do less work (mainly serialisation) in principle, but I have not checked.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Review by mrry — APPROVED** [review]
Change looks good to me. Thanks for the improvement!

**Comment by byronyi** [comment]
Thank you Derek @mrry :)

**Pull request merged**
