### PR TITLE
[ROCm] Enable unique op on the ROCm platform.

### PR DESCRIPTION
**Pull request by deven-amd**
porting the implementation by @ekuznetsov139 in the ROCm TF fork.

----------------------------------------

/cc @cheshire @chsigg

### CODE REVIEW

**Comment by deven-amd** [comment]
The failure in `Linux GPU` does not seem to be related to the changes in this PR

error from `Linux GPU` log 
```
tensorflow/core/kernels/cwise_op_mod.cc: In member function 'Eigen::TensorDevice<ExpressionType, DeviceType>& Eigen::TensorDevice<ExpressionType, DeviceType>::operator=(const OtherDerived&) [with OtherDerived = Eigen::TensorCwiseBinaryOp<Eigen::internal::safe_div_or_mod_op<long int, Eigen::internal::scalar_mod2_op<long int> >, const Eigen::TensorBroadcastingOp<const Eigen::array<long int, 4>, const Eigen::TensorMap<Eigen::Tensor<const long int, 4, 1, long int>, 16, Eigen::MakePointer> >, const Eigen::TensorBroadcastingOp<const Eigen::array<long int, 4>, const Eigen::TensorMap<Eigen::Tensor<const long int, 4, 1, long int>, 16, Eigen::MakePointer> > >; ExpressionType = Eigen::TensorMap<Eigen::Tensor<long int, 4, 1, long int>, 16, Eigen::MakePointer>; DeviceType = Eigen::ThreadPoolDevice]':
tensorflow/core/kernels/cwise_op_mod.cc:43:1: internal compiler error: Illegal instruction
 }  // namespace tensorflow
 ^
0xb019af crash_signal
	/dt7-src/gcc/toplev.c:340
0xb6c08a op_iter_init
	/dt7-src/gcc/ssa-iterators.h:601
0xb6c08a op_iter_init_tree
	/dt7-src/gcc/ssa-iterators.h:661
0xb6c08a mark_def_sites
	/dt7-src/gcc/tree-into-ssa.c:681
0xb6c08a mark_def_dom_walker::before_dom_children(basic_block_def*)
	/dt7-src/gcc/tree-into-ssa.c:2340
0x110a5aa dom_walker::walk(basic_block_def*)
	/dt7-src/gcc/domwalk.c:265
0xb7185d execute
	/dt7-src/gcc/tree-into-ssa.c:2452
```

**Comment by cheshire** [comment]
@deven-amd somehow we see those ICEs all the time now, usually it passes after a few runs. Not sure where are they coming from sadly.

**Review by cheshire — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by deven-amd** [comment]
@gbaned gentle ping. this PR seems to have gotten stuck in the merge pipeline

**Comment by deven-amd** [comment]
@gbaned ... this PR seems to have gotten merged and then rolled-back (without the typical "rolling back" comment that typically accompanies such rollbacks)....any idea what is happening here?

**Comment by cheshire** [comment]
It broke Windows.

Sorry we are really struggling maintaining the MSVC build. The error messages we get are usually really cryptic. This time we got:

```
.\tensorflow/core/kernels/unique_op_gpu.cu.h(463): fatal error C1070: mismatched #if/#endif pair in file 'T:\tmp\nsz6drem\execroot\org_tensorflow\tensorflow\core\kernels\unique_op_gpu.cu.h'

```

**Comment by deven-amd** [comment]
@cheshire :(

The line number in the error message is pointing to the end of the file, so that is not very helpful.

If we look at the changes in that file ( `.\tensorflow/core/kernels/unique_op_gpu.cu.h` ), 
* the [first one]( https://github.com/tensorflow/tensorflow/pull/50409/files#diff-1fafec84a77aafd71aae71878e5b751b9671c8bdf60632eb2c5a8cfd48a82846R19 ) has many similar instances throughout the TF codebase, so doubt that is triggering the error
* the other two ( [this one](https://github.com/tensorflow/tensorflow/pull/50409/files#diff-1fafec84a77aafd71aae71878e5b751b9671c8bdf60632eb2c5a8cfd48a82846R335-R339) , and [this one](https://github.com/tensorflow/tensorflow/pull/50409/files#diff-1fafec84a77aafd71aae71878e5b751b9671c8bdf60632eb2c5a8cfd48a82846R384-R390) ), both introduce "#if"s that are contained within a statement, and one or both of them are most likely causing the error.

Can I push out a commit  that essentially makes those two "#if"s contain full statements, and we can test out whether that change fixes the error? Would it be better to do that in this PR...or abandon this one and file a new one?

**Pull request merged**
