### PR TITLE
Fix issue 22298

### PR DESCRIPTION
**Pull request by DELTA37**
add storing variable created in variable scope in _VariableStore class

### CODE REVIEW

**Comment by drpngx** [comment]
@DELTA37 could you sign the CLA?

**Comment by DELTA37** [comment]
Ok, i will sign

**Comment by DELTA37** [comment]
I have signed

**Comment by DELTA37** [comment]
I have signed

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by alextp** [comment]
What is this change trying to fix? Can you add a unit test for it?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rthadur** [comment]
Closing this PR due to lack of activity .

**Pull request closed without merging**
