### PR TITLE
Lite: Util new test cases added to improve coverage

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
6 new test cases added

### CODE REVIEW

**Comment by ANSHUMAN87** [comment]
@achowdhery : Gentle Reminder!

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Review by petewarden — APPROVED** [review]
Thanks for these changes, and your patience with the long review time!

**Comment by rthadur** [comment]
Thank you @petewarden for your help in merging this PR. @ANSHUMAN87 sorry for the delay and thank you for patience.

**Pull request merged**
