### PR TITLE
[XLA] Separate out the dynamic slice wrapping tests

### PR DESCRIPTION
**Pull request by DavidNorman**
This is a set of changes to allow disabling of bfloat16 tests, for backends which don't support bfloat16.  Originally it was a change to the same set of tests to allow the wrapping behaviour tests to be disabled.  That change was made obsolete by some parallel work.

---
The original text was:

The XLA documentation says that the behaviour of dynamic slice and dynamic update slice is undefined when the indices wrap.

This separates out the tests which check for wrapping behaviour, so that they can be ignored for backends which don't exhibit the test's expected results.

### CODE REVIEW

**Comment by DavidNorman** [comment]
@broune
@alinas 

Hi - this is a small change to allow disabling of the bfloat16 tests.  I notice that my earlier change (separating out the wrapping behaviour into different tests) was already done separately.

**Review by broune — APPROVED** [review]
Looks good to me.

**Comment by DavidNorman** [comment]
thanks

**Comment by DavidNorman** [comment]
i think someone from google needs to tell the CI system to do a test run.

**Comment by hawkinsp** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
