### PR TITLE
fix sync update in distributed mnist demo

### PR DESCRIPTION
**Pull request by perhapszzy**

### CODE REVIEW

**Comment by perhapszzy** [comment]
I signed it!

**Comment by yifeif** [comment]
@caisq could you take a look?

**Comment by caisq** [comment]
Looking

**Comment by caisq** [comment]
Adding @jmchen-g

**Comment by perhapszzy** [comment]
https://github.com/tensorflow/tensorflow/issues/3457 provided more information

**Comment by danmane** [comment]
@caisq / @jmchen-g should we go ahead to merge this?

**Comment by jmchen-g** [comment]
This fix is not right. The chief queue runner can only run by the chief. This seems to expose a bug somewhere but we have not figured it yet. We are in the middle of changing the sync_rep_optimizer so will come back to this after that change.

**Comment by perhapszzy** [comment]
Any updates on the sync mode?

**Comment by rmlarsen** [comment]
@jmchen-g any updates on this?

**Comment by jmchen-g** [comment]
Most of the updates are implemented internally and after they are verified, we will push it outside. That will take some time though. We can close this PR for now as the fix is not a real fix but happens to get around some issues in the current implementation. The new implementation should be more robust and easier to debug.

**Comment by renato2099** [comment]
hi @jmchen-g any updates on this?

**Comment by jmchen-g** [comment]
@caisq, any update on this please?

**Pull request closed without merging**
