### PR TITLE
fix issue with nsync which copies the headers every build

### PR DESCRIPTION
**Pull request by kingofthebongo2008**
reworked nsync to be like png and zlib cmake files.
it copied the nsync headers on every build and this triggered rebuild of the whole tensorflow project on windows

### CODE REVIEW

**Comment by kingofthebongo2008** [comment]
I signed it!

**Comment by kingofthebongo2008** [comment]
I have signed it!

**Review by m3bm3b — COMMENTED** [review]
It looks good, but I'm confused.

When I created this file, I copied its structure 
from highwayhash.cmake.
So why aren't we having the same problem 
with that file?  
Or if we are having the problem with that file, 
shouldn't we fix that also?

**Comment by kingofthebongo2008** [comment]
From the cmake file i see that it needs the same,
Though it did not occured to be on windows 10.
nsync there forced rebuild every time.
but it did not occured to me.
I guess depends on the build systems. cmake that produces msbuild project
files work with dates to check dependencies. I am not familiar with bazel
and ninja though, if they check contents of the file, may be different.
anyway, i will investigate more for highwash, may be it was not compiled in
my build.

**Comment by kingofthebongo2008** [comment]
better to rework highwash, actually now only highwash follows different
pattern than the rest of the extern cmake files

**Comment by m3bm3b** [comment]
Do you plan to make the corresponding change to highwayhash.cmake in this PR?
I'm happy to review it if you do.

**Comment by kingofthebongo2008** [comment]
i am doing this right now, pull request will come shortly

**Comment by kingofthebongo2008** [comment]
Hello Mike,
I did a pull request 4 days ago for highwayhash and still nothing.
How these things are processed in tensorflow?
Usually coding takes half an hour and putting in git takes very long time

**Comment by m3bm3b** [comment]
I have no idea about how pull requests get assigned to reviewers.

I naively had expected you to add the highwayhash cmake 
change to this pull request, but perhaps that's 
not possible or inadvisable for some reason.

**Comment by kingofthebongo2008** [comment]
well, i create new branch for every fix as git best practices recommends
and after that i say create pull request

https://github.com/tensorflow/tensorflow/pull/20890

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by m3bm3b** [comment]
This got migrated to PR 21206, and it has all the necessary reviews and approvals.
I would expect it to appear in the next day or two, unless the final phase of testing
uncovers something unexpected.

**Pull request closed without merging**
