### PR TITLE
Added absolute path expansion of parent directory check in saver.py, …

### PR DESCRIPTION
**Pull request by PuchatekwSzortach**
…so as to correctly handle saving files in current directory

### CODE REVIEW

**Comment by PuchatekwSzortach** [comment]
Pull request in response to:
https://github.com/tensorflow/tensorflow/pull/3695#r94327053

**Comment by rohan100jain** [comment]
Is it possible to add a test for the corner case this is trying to fix?

**Comment by PuchatekwSzortach** [comment]
@rohan100jain Yes, but the test case passes on my OSX without the fix too... I assume it would fail on Windows and pass with the new check added, but don't have a Windows machine to really confirm that...
I can add the test case, but someone else would have to run it to see it really behaves as expected - especially that it fails with current code. If I add the test case here in comments, can someone run it to make sure it really fails on Windows? Or should I maybe first commit the test case alone without fix, make sure it fails when google bot runs tests and then add the fix and check that passes?

**Comment by gunan** [comment]
If you can create the test as a separate commit, I can help you get it tested both with and without your fix.

**Comment by PuchatekwSzortach** [comment]
@gunan 
Ok, this was a bit more complicated than I expected. First of all please ignore commits before 8a44d67, I made silly mistakes there.
Commit 8a44d67 adds a test that saves a graph to a file in current directory, using a path without "./" prepended.
I expect this to fail on Windows with parent not found error as per https://github.com/tensorflow/tensorflow/pull/6601#issuecomment-271063210. But what I didn't expect was that it would fail on OSX too - however not on saving the graph, but on restoring it. Adding a simple path expansion to body of Saver.restore(), commit b968f6, fixed that issue.

And commit 690b4ee (hopefully) fixes issue with not being able to save to current directory on Windows when no "./" is used in front of the path.

On a side note - it takes ~30min of rebuilding and re-running tests on my machine whenever I make a simple change to Tensorflow source code. Am I missing some caching settings, or is that a pain everyone here goes through? I could had solved the whole issue in 15 mins if not such slow rebuild + testing cycles...

**Comment by drpngx** [comment]
Is this fixed?

**Comment by gunan** [comment]
No, I still was not able to verify with the tests. Please assign to me and
block on me.
Sorry for the delay.

**Comment by drpngx** [comment]
Can this move forward? I wonder if it's related to the problems that we've seen with "./" @rohan100jain

**Comment by gunan** [comment]
OK, working on it right now.

**Comment by gunan** [comment]
I just confirmed that the test case added, without the changes in saver.py do fail in windows.
I am now testing if I can get the test passing with saver.py changes.
In the meantime,
Jenkins, test this please.

**Comment by gunan** [comment]
And with the fix the test passes.
Will proceed with the review.

**Comment by gunan** [comment]
The issues should be unrelated, and fixed.
Jenkins, test this please.

**Comment by gunan** [comment]
More flakes,
Jenkins, test this please.

**Review by gunan — APPROVED** [review]

**Comment by jhseu** [comment]
This change breaks saving checkpoints to any non-local filesystem. Let's revert?

**Comment by gunan** [comment]
Let's also discuss a plan for addressing the issue referenced by this PR.
Maybe we can add a method to wrap os.path.abspath, which checks if the path is local or remote and selectively converts the path?

**Comment by jhseu** [comment]
I think the following version is reasonable:
1. Modify Dirname() to handle non-absolute paths (i.e., return "." for the Dirname() for cwd paths)
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/path.h

The return type would probably have to change to a std::string.
2. Expose Dirname() in gfile:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/gfile.py
3. And call from save.

That should fix both save (#3) and restore (#1).

**Pull request merged**
