### PR TITLE
[INTEL oneDNN][Bug Fix]  Fix an AvgPoolGrad unit test failure caused by a newly added test

### PR DESCRIPTION
**Pull request by gzmkl**
Recent commit (merged around 2/16/2023)
https://github.com/tensorflow/tensorflow/commit/623a2f128b7e40ea990c82f56add4810244877d6

added error checking to AvgPoolGrad kernel (core/kernels/avgpooling_op.cc)
with a newly added test case in pooling_ops_test.py

This PR does the exact same for oneDNN AvgPoolGrad kernel, to address the unit test case failure which is triggered by the above commit (when oneDNN is enabled).

This PR also re-enables to following 2 unit tests for AARCH64:
    //tensorflow/python/kernel_tests/nn_ops:conv_ops_test \
    //tensorflow/python/kernel_tests/nn_ops:pooling_ops_test \

### CODE REVIEW

**Comment by elfringham** [comment]
Please see the comment https://github.com/tensorflow/tensorflow/issues/59773#issuecomment-1443459494 and adjust this PR so that it removes the line mentioned there. That will re-enable the running of the test in question on the AARCH64 github actions and allow confirmation that your fix addresses the issue.

**Comment by gzmkl** [comment]
Just made the code change to re-enable the unit case execution on AARCH64.
Please review!

**Comment by gzmkl** [comment]
I am not sure if my recent two commits (unblock 2 unit tests) caused the "ARM CI / build (3.10) (pull_request)" failure.

I could not find much useful info from "Details"

**Comment by elfringham** [comment]
@gzmkl The failure was due to an unrelated pre-existing issue that has since been addressed.

**Review by elfringham — CHANGES_REQUESTED** [review]
//tensorflow/python/kernel_tests/nn_ops:conv_ops_test still fails so please leave that test in the exclusion list.
```
FAIL: testConv2DGroupConvFwd (__main__.Conv2DTest)
Conv2DTest.testConv2DGroupConvFwd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/builder/.cache/bazel/_bazel_builder/945690c41481150b9aa58576637dd867/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/conv_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 2338, in decorated
    f(self, *args, **kwargs)
  File "/home/builder/.cache/bazel/_bazel_builder/945690c41481150b9aa58576637dd867/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/conv_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1501, in decorated
    f(self, *args, **kwargs)
  File "/home/builder/.cache/bazel/_bazel_builder/945690c41481150b9aa58576637dd867/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/conv_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/conv_ops_test.py", line 852, in testConv2DGroupConvFwd
    self._VerifyGroupConvFwd([10, 32, 32, 16], filter_dims,
  File "/home/builder/.cache/bazel/_bazel_builder/945690c41481150b9aa58576637dd867/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/conv_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/conv_ops_test.py", line 839, in _VerifyGroupConvFwd
    self.assertAllClose(
  File "/home/builder/.cache/bazel/_bazel_builder/945690c41481150b9aa58576637dd867/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/conv_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1542, in decorated
    return f(*args, **kwds)
  File "/home/builder/.cache/bazel/_bazel_builder/945690c41481150b9aa58576637dd867/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/conv_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 3173, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/home/builder/.cache/bazel/_bazel_builder/945690c41481150b9aa58576637dd867/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/conv_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 3129, in _assertAllCloseRecursive
    self._assertArrayLikeAllClose(
  File "/home/builder/.cache/bazel/_bazel_builder/945690c41481150b9aa58576637dd867/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/conv_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 3066, in _assertArrayLikeAllClose
    np.testing.assert_allclose(
  File "/home/builder/venv39/lib64/python3.9/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/builder/venv39/lib64/python3.9/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-05
Mismatched value: a is different from b. 
not close where = (array([0, 0, 0, ..., 9, 9, 9]), array([0, 0, 0, ..., 7, 7, 7]), array([ 0,  0,  0, ..., 31, 31, 31]), array([ 0,  1,  2, ..., 29, 30, 31]))
not close lhs = [1.0729360e+06 1.5484760e+06 1.6210520e+06 ... 3.9282451e+08 3.9286291e+08
 2.2004294e+08]
not close rhs = [7.2055200e+05 1.0859000e+06 1.1446520e+06 ... 5.3390678e+08 5.3395901e+08
 3.4552045e+08]
not close dif = [3.5238400e+05 4.6257600e+05 4.7640000e+05 ... 1.4108227e+08 1.4109610e+08
 1.2547750e+08]
not close tol = [   7.2055297   10.859009    11.446529  ... 5339.068     5339.59
 3455.2043   ]
dtype = float32, shape = (10, 8, 32, 32)
Mismatched elements: 81920 / 81920 (100%)
Max absolute difference: 1.410961e+08
Max relative difference: 0.4890473
 x: array([[[[1.072936e+06, 1.548476e+06, 1.621052e+06, ..., 3.580604e+06,
          3.653180e+06, 2.265128e+06],
         [2.758524e+06, 3.885114e+06, 3.966330e+06, ..., 6.159162e+06,...
 y: array([[[[7.205520e+05, 1.085900e+06, 1.144652e+06, ..., 2.730956e+06,
          2.789708e+06, 1.830760e+06],
         [2.017836e+06, 2.994042e+06, 3.075258e+06, ..., 5.268090e+06,...
```

**Comment by gzmkl** [comment]
@elfringham Thank you for the input. I will conv test into deny list and ask our team to address it in near future.

**Review by elfringham — COMMENTED** [review]
Thanks. OK by me.

**Comment by gzmkl** [comment]
@elfringham Regarding to conv_ops_test, I did follow-up and found that related failed test case (testConv2DGroupFwd) passed on all Intel CPUs in both GRAPH and EAGER modes. As we do not work on AARCH64, to fix the issue we can only provide support.  THANKS!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Review by penpornk — APPROVED** [review]
Thank you for the fix and sorry for the delay!

**Comment by gzmkl** [comment]
@penpornk  The new delta changes are in Eigen implementation already. We are just doing the same for oneDNN AvgPoolGrad op.

**Review by penpornk — APPROVED** [review]
Approved. Thank you!

**Pull request merged**
