### PR TITLE
Fix TensorFlow Windows build

### PR DESCRIPTION
**Pull request by meteorcloudy**
1. fix configure.py on Windows
2. Update nsync to make it work on Windows
3. disabled some failing tests.

@yifeif @gunan

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Jenkins, test this please

**Comment by yifeif** [comment]
+ @m3bm3b for nsync change. Mike updated the nsync binary to head from internal to make nsync work for cmake on macOS. Would that version also work for Windows @meteorcloudy?

**Comment by meteorcloudy** [comment]
@yifeif Just checked, yes it will work for Windows.

**Review by jhseu — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Jenkins, test this please

**Comment by snnn** [comment]
I'll re-enable these tests in #12680

**Pull request merged**
