### PR TITLE
Fix inappropriate argument names in c_api.cc

### PR DESCRIPTION
**Pull request by jungpilyu**
In Python3.7, a word **async** became a [**new reserved keyword**](https://docs.python.org/3.7/whatsnew/3.7.html).
Unfortunately, some functions in **c_api.cc** use the word **async** as argument names.
During tensorflow building, **c_api.cc** is converted to python wrapper by **swig** tool.
**Swig** uses the same name **async** in the wrapper functions.
This causes the syntax error in python 3.7.
The tensorflow building with python 3.7 thus ends up with failure without this fix.

### CODE REVIEW

**Comment by jungpilyu** [comment]
How can I commit suggestion codes for this issue? I encountered **an authentication error** during PUSH ORIGIN from GitHub Desktop. 
"Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository."

**Comment by rmlarsen** [comment]
@jungpilyu please resolve conflicts.

**Comment by case540** [comment]
This PR seems to change a lot more than what is described in the PR desc.

**Comment by jungpilyu** [comment]
I signed CLA. When will it be confirmed? In order to commit, I need to be given permission to access to repo. Whom do I have to ask?

**Comment by rmlarsen** [comment]
@jungpilyu I am not sure what you are asking. You need to create your own repo that is a for of TensorFlow, make the changes there and submit a pull request here to have the changes committed to the official repo.

**Comment by jungpilyu** [comment]
@rmlarsen Thank you for the guidance. I am newbie in contributing to open source. Now I become to know how to do that owing to you! Thank you again.

**Pull request closed without merging**
