### PR TITLE
Small fixes for Python 3 support

### PR DESCRIPTION
**Pull request by ogrisel**
Question: what is the procedure to run the Python tests? The [documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md) does not mention them.

### CODE REVIEW

**Comment by ogrisel** [comment]
Actually this is mostly a dupe of #568 and #569. Feel free to close this PR. I just added an entry in .gitignore for __pycache__ folders on top of the other 2 PRs.

**Comment by ogrisel** [comment]
BTW, is there no continuous integration for Python 3. This kind of regressions are prone to re-appear if the tensorflow core devs do not use Python 3 themselves.

**Comment by vrv** [comment]
Yeah we just merged #568 -- do you want to update change or just send a new PR for the .gitignore?

Yup, we're working on continuous integration tests with python 3 to prevent these regressions.

**Comment by vrv** [comment]
(re-open if you'd like)

**Comment by ogrisel** [comment]
Ok thanks, sorry for the slow reaction.

**Pull request closed without merging**
