### PR TITLE
#28014 [TF 2.0] the word2vec_basic.py example is not 2.0.0-alpha0.

### PR DESCRIPTION
**Pull request by Mr-Nineteen**

### CODE REVIEW

**Comment by Mr-Nineteen** [comment]
Already registered CLA

**Comment by xiejw** [comment]
Please find appropriate owner to review tutorial code. 

I read the code briefly, and not convinced the code style is consistent with others. But I might be wrong.

**Review by dynamicwebpaige — COMMENTED** [review]
@Mr-Nineteen, thanks for catching that this tutorial is not compatible with TF 2.0! Would you be willing to fully upgrade the [Word2Vec Example](https://github.com/tensorflow/tensorflow/blob/ad1eee02e3a912117c7dadc56b5fdcd790af86db/tensorflow/examples/tutorials/word2vec/word2vec_basic.py) into TensorFlow 2.0 style?

Information on migrating code from 1.x to 2.0 can be found [here](https://www.tensorflow.org/alpha/guide/migration_guide). Please reach out if you have any questions! 🙂

**Comment by Mr-Nineteen** [comment]
@dynamicwebpaige 
Ok, then I will open an issue again, thank you.

**Pull request closed without merging**
