### PR TITLE
README Updates

### PR DESCRIPTION
**Pull request by alelouis**
Clarification of code examples for fast copy-paste replication. (I did run the code myself and encountered those little missing elements)
- Estimator declaration placed after config declaration
- loss_fn() incoherent with previous loss variable declaration

### CODE REVIEW

**Comment by harshini-gadige** [comment]
@alelouis Hi, would you like to sign CLA ?

**Comment by alelouis** [comment]
That’s done :) Thank you.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yuefengz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Review by yuefengz — APPROVED** [review]
Thanks for updating it!

**Comment by harshini-gadige** [comment]
@yuefengz  - Hi, could you please look into the above kokoro failures ?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @harshini-gadige: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request merged**
