### PR TITLE
Build nighlty with GCS cache

### PR DESCRIPTION
**Pull request by bhack**
Test if we are able to compile (and monitor the required time) to build TF CPU on the GitHub Action free resources using the nightly GCS cache.

This a good proxy to verify the setup a contributor could use to prepare and test locally a PR.

This is a follow-up of https://github.com/tensorflow/build/pull/48 as the CI files was removed from that repository.

/cc @angerson  @perfinion @learning-to-play @mihaimaruseac @theadactyl

### CODE REVIEW

**Comment by bhack** [comment]
You can follow one execution at:
https://github.com/bhack/tensorflow/runs/8218571370?check_suite_focus=true

**Comment by bhack** [comment]
Eventually:

What we contribute in Docs to prepare PRs using Docker+GCS cache?:
- https://www.tensorflow.org/community/contribute/code
- https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md

**Comment by bhack** [comment]
It is going in timeout after ~6 hours of building. 
Are we not able to compile Tensorflow with the pre-filled GCS remote cache  in less then 6 hours on the Github CI 2 core (4 threads) runner?

**Comment by mihaimaruseac** [comment]
Yeah, TF does not compile on this type of VM in less than 6hrs, even if using a cache. 

On contrast, the [Linux kernel compiles on GH Actions in **slightly less over 2 hours without any cache**](https://github.com/whokilleddb/build-a-kernel-using-github-actions).

The build system of TF needs a lot of improvements, it should not be at least 3 times as complicated as the Linux kernel.

CC @learning-to-play

**Comment by bhack** [comment]
> Yeah, TF does not compile on this type of VM in less than 6hrs, even if using a cache.

I really want to be sure about this and it is why I am asking here to collaborate on the same "public page". 
As this GitHub action is extremely simple to be runned also [locally as is](https://github.com/nektos/act) I would like to clearly collaborate to away all doubts concerning a possible reproducibility of the cache/cache misses with this Action before going to investigate other longer term programs.

**Comment by bhack** [comment]
Nightly branch was broken again today by LLVM. 
The fix was too late: https://github.com/tensorflow/tensorflow/commit/5e55f7fe1d2ebc99961d1d4a51bd327661fce994

**Comment by bhack** [comment]
There is something not reproducible or some of you remote cache upload on nightly was failing to GCS.

I did this action locally on today nightly `6bd411ac57895e12ac7399947965912e863fec0c`:

Commit verified with you build and pushed nightly weels:  
- `python -c "import tensorflow as tf; print(tf.__git_version__, tf.__version__)"`: `g6bd411ac578`
-  `git rev-parse HEAD`:  `6bd411ac57895e12ac7399947965912e863fec0c`

I've manually interrupted the build at `2232 processes`:
- We already have only 1496/2232 remote cache hits

**Comment by bhack** [comment]
If you want to reproduce this on any system:

```bash
docker run --rm -it tensorflow/build:latest-python3.10 /bin/bash
git clone -b nightly --single-branch --depth 1  https://github.com/tensorflow/tensorflow.git && cd tensorflow

bazel --bazelrc=tensorflow/tools/tf_sig_build_dockerfiles/devel.usertools/cpu.bazelrc build  --config=sigbuild_remote_cache tensorflow/tools/pip_package:build_pip_package --build_event_text_file=/tmp/bep.txT
```

Interrupt the build with enough processed targets (I suggest to wait for >2500 targets built):

`grep "remote cache hit" /tmp/bep.txt`

**Comment by angerson** [comment]
Yeah, the cache isn't perfect; I don't know why. We get numbers like this internally: INFO: 18708 processes: 14156 remote cache hit, 4426 internal, 126 local.

That's a big improvement over zero. @perfinion IIRC the cache misses are usually because of that strange hash-or-timestamping thing that some source code files do, do you remember anything about it?

**Comment by bhack** [comment]
> Yeah, the cache isn't perfect; I don't know why. We get numbers like this internally: INFO: 18708 processes: 14156 remote cache hit, 4426 internal, 126 local.

The problem is not about reaching perfection but it is that with the cache we cannot build TF  in Github Action in 6/7/8 hours. 

I've shared 3 reproducible lines at https://github.com/tensorflow/tensorflow/pull/57630#issuecomment-1242711115

With today nightly 7cc008ea3d0f30345e083fa1e8687d6be74439d7

`18711 processes: 11170 remote cache hit, 4427 internal, 3114 local.`

But in these `7541` recompiled we have many targets that are very heavy under `tensorflow/core/` `tensorflow/lite` `tensorflow/compiler` tensorflow/cc`... etc....  missing the remote cache hit.

You can check number yourself with the pre-filled remote cache:
`INFO: Elapsed time: 2749.219s, Critical Path: 496.08s` on a GCP  **24 modern cores/64GB RAM**.

Really not a standard system that we could request to non enterprise contributors for PRs.

**Comment by bhack** [comment]
Please check https://github.com/tensorflow/tensorflow/issues/58310#issuecomment-1293031713

**Comment by bhack** [comment]
`pip install tf-nightly-cpu` 
`python3 -c "import tensorflow as tf; print(tf.__git_version__, tf.__version__)"`

`v1.12.1-83758-g5d6bfa6f978 2.12.0-dev20221027`

What commit is `5d6bfa6f978`?

https://github.com/tensorflow/tensorflow/blob/7265347c5bc9700ddc7424a9435f4fd6640cab32/tensorflow/tools/git/gen_git_source.py#L139-L148

**Comment by MichaelHudgins** [comment]
I think this is a good idea but I don't think the state of problems above with runtime have been addressed enough for a reliable run yet.  This is something i think would be worth reinvestigating after the possible clang migration and some other efforts to possibly address some of the cache invalidation.

**Comment by bhack** [comment]
@MichaelHudgins Let me know when you are ready so that I can reopen this old contribution. 
Currently the build time/required computing resources is one of the biggest bottleneck to the non enterprise OSS contribution in the repo.

**Comment by bhack** [comment]
@MichaelHudgins @learning-to-play https://github.com/openxla/iree/pull/13265#discussion_r1176755260

**Pull request closed without merging**
