### PR TITLE
Add the eager coverage for some dataset experimental kernels

### PR DESCRIPTION
**Pull request by feihugis**
This PR adds the eager coverage for `NumElementsTest`, `CounterTest`, `DenseToSparseBatchTest`, and `DirectedInterleaveDatasetTest`.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jaingaurav: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jaingaurav: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jaingaurav: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jaingaurav: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jaingaurav: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jaingaurav: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 89 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jaingaurav: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 104 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jaingaurav: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 119 days with no activity and the `awaiting review` label has been applied.

**Comment by jsimsa** [comment]
@feihugis is this PR still relevant? if so, could you please merge HEAD and resolve conflicts? thanks

**Comment by jsimsa** [comment]
@feihugis is this PR still relevant? if so, could you please merge HEAD and resolve conflicts? thanks

**Comment by feihugis** [comment]
@jsimsa Sorry for the late response! Double checked this PR. The current tests have covered both the graph and eager mode (cached_session() provides [`FakeEagerSession`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/test_util.py#L1896) for the eager mode). Please feel free to close this PR.

**Pull request closed without merging**
