### PR TITLE
Update get_started.md

### PR DESCRIPTION
**Pull request by alanyee**
Fix various errors in print out statements and unnecessary lines of code

### CODE REVIEW

**Review by frankchn — APPROVED** [review]

**Comment by frankchn** [comment]
Jenkins, test this please.

**Comment by frankchn** [comment]
Can you modify the pull request to merge into `master` rather than `r:1.2`?

**Comment by alanyee** [comment]
@frankchn I already made the changes to master. Am I not supposed update the 1.2 documentation?

**Comment by frankchn** [comment]
No, the v1.2 branch is already frozen and released and v1.3 is coming soon, so we’ll just fix forward at this point.

**Comment by alanyee** [comment]
Would I be allowed to push some changes into v1.3 branch?

**Comment by frankchn** [comment]
v1.3 will be cut from master when we decide to release it, so whatever that is in master when we create v1.3-rc0 will automatically be included.

**Comment by alanyee** [comment]
@frankchn does this look good, or do I need to do anything else?

**Comment by frankchn** [comment]
@alanyee We should be good.

Jenkins, test this please.

**Comment by frankchn** [comment]
Actually @alanyee looking at it now, can you rebase to master and push again? You have some random commits that are not relevant in this PR right now.

**Comment by alanyee** [comment]
@frankchn I think rebasing to master is what caused the random commits to become involved in this PR. Am I unsure how to do this besides open a new PR?

**Comment by frankchn** [comment]
I squashed the commits so I think this won't end up polluting `master`. Thanks!

**Pull request merged**
