### PR TITLE
fix: slot and primary can be different shape

### PR DESCRIPTION
**Pull request by candyzone**
See github issue #19457

### CODE REVIEW

**Comment by candyzone** [comment]
@martinwicke please review my PR or assign to someone else
thanks

**Comment by candyzone** [comment]
@protoget

**Comment by candyzone** [comment]
@martinwicke  Can you assign to someone else to review? @protoget didn't response on this.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment]
@allenlavoie you had commented on the issue, you're probably in a good position to properly review this.

**Review by allenlavoie — DISMISSED** [review]
Great! Thank you for looking into this.

**Comment by allenlavoie** [comment]
FYI this was just rolled back because (we think) of MetaGraph import issues with variable->constant conversion that it triggered. I have requested a snippet to reproduce the issue and will follow up when I have one with a plan to get this resubmitted.

**Pull request merged**
