### PR TITLE
Branch 137307610

### PR DESCRIPTION
**Pull request by drpngx**
Merge resolution:
- `tensorflow/core/framework/allocator.h`: (RequestedSize changed for windows (PR 5071)
- `tensorflow/tensorboard/backend/server.py`: use `io_wrapper` (136889282) and PR 5035 (path prefix check)

### CODE REVIEW

**Comment by caisq** [comment]
One of the commits (CLs) introduces the mac failure. I think we should fix the mac issue before pushing.

**Comment by caisq** [comment]
After some investigation, I've narrowed it down to: CL/137211288 (https://github.com/tensorflow/tensorflow/pull/5219/commits/fad20053a9d33f1427a7c48100a8b2aef7e7f675)

**Comment by drpngx** [comment]
Thanks for finding out! I have a fix for the windows stuff.

**Comment by drpngx** [comment]
Link to [log of the mac failure](https://ci.tensorflow.org/job/tensorflow-pull-requests-mac/2432/consoleFull).

**Pull request closed without merging**
