### PR TITLE
Fixes issue #34398, equation from BTRS paper

### PR DESCRIPTION
**Pull request by copperwiring**
Fixed a equation of the TF implementation of BTRS [paper](https://epub.wu.ac.at/1242/1/document.pdf). Equation is available on page 7 of the paper

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Can you also add a test case please?

**Comment by copperwiring** [comment]
@mihaimaruseac Thank you for the prompt response. Really appreciate it! Can you please direct me to the documentation for test case in tensorflow? I can't find them here: https://github.com/tensorflow/tensorflow

**Comment by lamberta** [comment]
Fixes https://github.com/tensorflow/tensorflow/issues/34398

**Review by mihaimaruseac — APPROVED** [review]
This seems harder to test than expected, so let's approve it.

Ideally, the test would go to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/random_binomial_op_test.cc but that file seems to be more of a benchmark than a test suite. TF uses GoogleTest for tests, for example https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/adjust_contrast_op_test.cc shows how a test suite would look

**Comment by copperwiring** [comment]
Thanks @mihaimaruseac . Hopefully, I'll get to work on some test cases for TF soon.

**Pull request merged**
