### PR TITLE
[XLA][StreamExecutor] add empty implementation for host stream, avoid…

### PR DESCRIPTION
**Pull request by qingyunqu**
… to log ERROR message when call SetPriority on host stream

### CODE REVIEW

**Review by cheshire — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @cheshire Import/copybara check is showing it didn't affect any internal files, can you please help with import these changes? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @cheshire Any update on this PR ? Please. Thank you!

**Comment by keerthanakadiri** [comment]
Hi @cheshire Any update on this PR ? Please. Thank you!

**Comment by cheshire** [comment]
hey, PRs touching XLA should be submitted to github.com/openxla/xla repository

**Comment by keerthanakadiri** [comment]
Hi @qingyunqu , Can you please create this PR in [github.com/openxla/xla ](https://github.com/openxla/xla)repository
Thank you

**Comment by qingyunqu** [comment]
> Hi @qingyunqu , Can you please create this PR in [github.com/openxla/xla ](https://github.com/openxla/xla)repository Thank you

Seems that xla has removed `stream_interface` in https://github.com/openxla/xla/commit/8c6e1ddd2598e7dadb95d89e612e0452a80068ba.  
It's no need to add this PR. I will close it.

**Pull request closed without merging**
