### PR TITLE
Branch 163490703

### PR DESCRIPTION
**Pull request by vrv**

### CODE REVIEW

**Review by alextp — APPROVED** [review]
rubber-stamp

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
@tensorflow-jenkins test this please, wakey wakey

**Comment by av8ramit** [comment]
Tensorflow Jenkins, test this please.

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Pull request merged**
