### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by mahdiaslanimk**

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]
Thank you for the PR. In the future, please try to fix typos across an entire file/directory, as we want to minimize hours of CI / letters changed :)

**Comment by gbaned** [comment]
Hi @mahdiaslanimk  It looks like your PR relates to the Keras component. Please submit it to the github.com/keras-team/keras repository instead. Thank you!
@mihaimaruseac, @fchollet, @qlzh727

**Comment by mihaimaruseac** [comment]
Right, I miss that part, sorry about it. Will remove approval

**Comment by gbaned** [comment]
Hi @mahdiaslanimk As mentioned above comments, please submit the PR to the github.com/keras-team/keras repository instead. Thank you!
Cc @fchollet, @qlzh727

Thank you @mihaimaruseac.

**Pull request closed without merging**
