### PR TITLE
Add missing tf_copts calls

### PR DESCRIPTION
**Pull request by snnn**
To eliminate warnings like:
libarithmetic_optimizer.a(arithmetic_optimizer.o) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported

This PR depends on #15439. Please merge that first.

### CODE REVIEW

**Comment by snnn** [comment]
Any problem?

**Comment by jhseu** [comment]
Can we separate out the XLA change and the tf_copts change? We probably only want to use tf_copts() at the top-level rules (cc_binary() rules) rather than at each cc_library().

**Comment by snnn** [comment]
Hi @jhseu
Do you mean:

1. Separate the changes in XLA into another commit?
2. Create a new macro named tf_cc_library in tensorflow.bzl, and use it everywhere?

Thanks.

**Comment by snnn** [comment]
Though LNK4049 is a linking issue, it need to be solved at compile time, by define the proper macros.

**Comment by snnn** [comment]
I'm splitting this pr.

**Comment by snnn** [comment]
I've spit this pr into 3 PRs.
#15439  #15441 #14531
Now this PR depends on #15439. Merge that first.

**Comment by snnn** [comment]
Recreated as #15466

**Pull request closed without merging**
