### PR TITLE
TFLu Apollo3 Maintenance

### PR DESCRIPTION
**Pull request by oclyke**
- Resolves benchmark performance for Apollo3 EVB
- Updates Apollo3 support to the 2.5.1 AmbiqSuite SDK
- Supports additional SFE Apollo3 boards for ```micro_speech```, ```magic_wand``` and ```person_detection``` examples

### CODE REVIEW

**Comment by gbaned** [comment]
@oclyke Can you please sign CLA. Thanks!

**Comment by oclyke** [comment]
@gbaned I seem to be having some issues with the CLA. I've previously signed the CLA with both my work and personal emails. I reviewed the commits and the only emails associated were:
* 65086349+rambiqmicro@users.noreply.github.com
* owen.lyke@sparkfun.com

AFAIK both those emails have signed CLAs at this point. Is there any additional information you could provide for me about this issue?

Thank you much!

**Comment by gbaned** [comment]
@oclyke Can you please resolve conflicts? Thanks!

**Comment by advaitjain** [comment]
@oclyke, we will not be able to accept this PR in its current for per our [updated contribution guidelines](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/CONTRIBUTING.md#new-target--platform--ide--examples).

The underlying issue in the case of this particular PR is that we want to control the amount of duplicated code involved in supporting examples across a range of very similar but slightly different target hardware and keep the scope of the pull requests to [doing one thing](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/CONTRIBUTING.md#general-pull-request-guidelines).

If you are up for a rethink and refactoring of the exisitng apollo3/sparkfun_edge support towards this end then I'd be happy to give you pointers on the direction that I would like this to go in.

If you have the time and interest in pursuing this, a next step would be to make a github issue describing the problem (and tag me) and I can guide the refactoring as a series of smaller PRs.

I'm going to close the current PR but would be happy to continue the conversation via a github issue to figure out a path forward.

**Pull request closed without merging**
