### PR TITLE
Update  tflite::gpu::Delegate  in delegate.cc

### PR DESCRIPTION
**Pull request by SunAriesCN**
Consider the nullptr input to tflite::gpu::Delegate constructor prevent crash.

### CODE REVIEW

**Review by terryheo — APPROVED** [review]
LGTM

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by terryheo** [comment]
Could you rebase the PR ?

**Comment by gbaned** [comment]
Hi @SunAriesCN Can you please check @terryheo's comments and keep us posted ? Thank you!

**Comment by terryheo** [comment]
The same change was already merged. Thanks for your contribution.

**Pull request closed without merging**
