### PR TITLE
copy reference kernels from lite to micro 

### PR DESCRIPTION
**Pull request by stephanboner**
PR3 in #45693

### CODE REVIEW

**Review by petewarden — APPROVED** [review]

**Comment by gbaned** [comment]
@stephanboner  Can you please resolve conflicts? Thanks!

**Comment by stephanboner** [comment]
Merged master. Reference kernel of `space_to_batch_nd.cc` not needed anymore since the micro version from #46681 was already merged into master

**Comment by gbaned** [comment]
@stephanboner Can you please resolve conflicts? Thanks!

**Comment by stephanboner** [comment]
Looks like all my changes are now already done in PR 4 and 5 so I'll close this one

**Pull request closed without merging**
