### PR TITLE
add documentation for Discrepancy between keras.layers.Reshape and tf.keras.layers.Reshape

### LINKED ISSUE #36428: Discrepancy between keras.layers.Reshape and tf.keras.layers.Reshape
```
tf-version 2.1.0
keras-version 2.2.4-tf
```

In Keras, according to [the documentation](https://keras.io/layers/core/), we expect:

```python
model.add(Reshape((-1, 2, 2)))
# now: model.output_shape == (None, 3, 2, 2)
```

But in tf.Keras [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Reshape):

```python
model.add(Reshape((-1, 2, 2)))
# now: model.output_shape == (None, None, 2, 2)
```

The second dimension is now `None` instead of the computed value.

This makes tf.Keras incompatible with Keras, and makes it harder to write code that is parameterized by of the output shape of an opaque model. Is there a way to get the true output shape?

### PR DESCRIPTION
**Pull request by rushabh-v**
resolves #36428

### CODE REVIEW

**Comment by rgov** [comment]
I think this change is needed, so thank you for adding the documentation.

Could you add a note that clarifies that the behavior deviates from Keras when using shape inference?

**Comment by rushabh-v** [comment]
I have added that

**Comment by rushabh-v** [comment]
Can you review this please @rthadur

**Review by pavithrasv — COMMENTED** [review]
Thank you for the PR. There is an RFC as per which tf.keras will be the new keras-team/keras. Because of this i am thinking we should not submit this doc change at this time.

**Pull request closed without merging**
