### PR TITLE
[XLA] Reduce maxval in random ops test.

### PR DESCRIPTION
**Pull request by georgepaw**
Reduced maxval in testRandomUniformIsNotConstant since the current value causes
an overflow when using a device which supports DT_HALF.

### CODE REVIEW

**Comment by georgepaw** [comment]
I see that the test has failed, perhaps I should change `maxvalue` to `np.finfo(dtype).max` or `np.finfo(dtype).max/2`?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 21 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 37 days with no activity and the `awaiting review` label has been applied.

**Comment by georgepaw** [comment]
could we look at this? - it is a very simple change.

**Comment by georgepaw** [comment]
@vrv Is it possible that this is assigned to a person who is no longer with the project? Would be nice to get some feedback on this.

**Review by vrv — APPROVED** [review]

**Pull request merged**
