### PR TITLE
Introduce tf.contrib.framework.Notification.

### PR DESCRIPTION
**Pull request by ebrevdo**
ConditionVariable may be used to delay computation, or to synchronize
computation between multiple tasks.

@mrry @m3bm3b i've had some free time here and there in the last couple weeks - and have been playing with improving synchronized training.  so i wrote up this ConditionVariable primitive.  though the Wait on the CV doesn't release a lock on a mutex or CriticalSection object (the way a condition_variable does in c++), it allows:

* Arbitrary-length sleep via wait(timeout_in_us)
* Synchronizing available workers using notifications.
* Support for cancellation.

### CODE REVIEW

**Comment by m3bm3b** [comment]
I haven't looked deeply at the code, but here are a few intial comments on the
change description and the interface.


---

You don't give any rationale or justification in the change description.   
Because it's so hard to remove things, I recommend not adding something new
until you can point to where you'd use it and explain why this is the mechanism 
that best fits the task.  Ideally, there would be more than one place 
where the new thing could be applied usefully.

---

Some of the comments say "critical section" where you probably mean the name of 
the new type.  Examples:
  tensorflow/contrib/framework/python/ops/condition_variable_ops.py, line 35 
  tensorflow/contrib/framework/python/ops/condition_variable_test.py, line 15 
I don't know whether there are others.

---

You say:

> the Wait on the CV doesn't release a lock on a mutex or CriticalSection 
> object (the way a condition_variable does does in c++)
   
In that case, I think ConditionVariable is a confusing name for this type.
Given what I suspect it does, I recommend something like "Notification".

Rationale:

The phrase "condition variable" is not just the name of a type in C++.  It's a
technical term, in use since the 1960s, and widely known by programmers.  
(They appear in the APIs for POSIX, Win32, Java, and C++.)  The term refers to a
particular mechanism that allows the client to wait for an arbitrary predicate
to become true, provided the predicate is a function of state modified only
with an associated critical section (implemented by a monitor or mutex).  They 
make no sense without that connection to a critical section.

"ConditionVariable" is particularly confusing in this context because you have
"CriticalSection", and yet this new mechanism doesn't seem to interact with it
in the expected way.

To get an idea for how confusing this feels, imagine
someone had created a SuffixTree that was merely a tree that contained
suffixes, or a SkipList that was merely a list that contained skip distances,
or a HashTable that was merely a vector of hash values.   You might be able to 
justify such names but they would still create confusion.

---

It seems odd to have a routine called "notify" that does not itself
notify anything, but instead returns something that does.
It's especially odd to have a spec that says:
   Notify all waiters on this ConditionVariable.
when the return value is specified as
   An `Operation` that, when executed, notifies all waiters.

Shouldn't the spec be, instead:
  Return an Operation that, when executed, notifies all waiters.

---

From the comments in
  tensorflow/contrib/framework/python/ops/condition_variable_ops.py
I can't tell what it means to "wait" on this resource, or to "notify" it.

For example: 
- Does the resource have (predicate-related) state (like a Notification in
  tensorflow/core/platform/default/notification.h) or not (like a traditional
  condition variable)?
- If there's state, can it be reset (like a binary sempaphore),
  or not (like a Notification)?
- If there's no (predicate-related) state, what substitutes for the atomicity
  guarantee of the wait operation of a traditional condition variable?  (That
  is the key part of the spec that allows a condition variable to work even  
  though it has no predicate-related state.)

If there's no state, I would make the spec of notify say:
   all current waiters
If there's state and it can be reset, I would say:
   all current and future waiters until the state is reset
If there's state and it cannot be reset, I would say:
   all current and future waiters

**Comment by ebrevdo** [comment]
@m3bm3b thank you for the comments!  i'll be addressing them, and at first I also wanted to call this a Notification but -- because it has no "state" (even a resettable one).  Though what you said does make me wonder if I should change the interface and replace the "Notify" op (which does an atomic notify and then resets the notification state) with two ops: "Notify" and "Reset".  I'll also update the documentation based on what you suggested.

In terms of usage examples, mine are experimental.  However, @benoitsteiner, @alextp, @saeta, @asimshankar, and @sguada may be interested in at least the cancellable timing functionality.

**Comment by ebrevdo** [comment]
To be more concise: I'll modify this to be a "Notification" object, and add the ability to set the "notified" state, and to reset it with a separate op.

**Comment by ebrevdo** [comment]
@m3bm3b i think i've addressed many of your code concerns; ptal.  @benoitsteiner @alextp @asimshankar @saeta @sguada ptal.

**Comment by m3bm3b** [comment]
You say that your usage examples are experimental.  Wouldn't it be
better to keep this change in an experimental fork until there's a
non-experimental need?  

You mention that others want cancellable timing.  If those are the only
confirmed requirements, then I recommend giving a few examples, and for the 
moment providing _just_ cancellable timing.  It's trivial to add to an
API later.  It's almost impossible to remove anything.  
Each addition of functionality is one more this we must 
maintain indefinitely.  That's proved crippling over the years in our other
APIs.

------

I'm quite surprised by the description of Notification.

You say first:
> The object is stateful.  Waiters will pause (or time out) until the
> Notification object is notified via the result of `notifier()`.  By default,
> notifying the object atomically releases all waiters, and resets the state.
> Any new `wait` operations executing after this will go into a waiting state.

This first says the object is _stateful_, but then goes on to describe a
wait/notification that is _stateless_.  It's stateless because the
Notification doesn't "remember" that it has been notified, which is why
subsequent attempts to wait will block until another notification event, rather
than waking immediately. 


Then you  describes stateful waits, where the fact that the object has been
notified is remembered by the object:

> Alternatively, executing `notifier(immediately_reset=False)` will also set the
> state of the Notification object.  Any `wait` operations executing after this
> will immediately continue and will not time out.


So the object seems provides both stateless and stateful synchronization.
Moreover, the stateful mode can be reset explicitly using resetter().

That's a lot different semantics.  Not only is it odd not to have a single usage
model that would dictate just one style of use, but to have an object that can 
be used in multiple different ways makes things harder for future readers to   
understand even if any given developer is trying to use it in only one way.
For example, suppose you're maintaining someone else's programme, and want to
know whether it's possible for the "notified" status of some Notification to be 
reset.  The only way to do that is to examine the entire programme (or the
entire scope where the Notification can be accessed, at least) to verify that no
one ever uses the "resetter()" operation.  So sometimes it's better to separate
different functionality into completely different types, so you can get this
sort of guarantee with just a glance.


I was expecting the object to be stateful, and not resettable.  I   
expected that because it's safer and easier to use, given the other aspects of
the design:

- Stateless waits are tricky to use correctly unless the synchronization object
  interacts in special ways with other sycnhronization primitives.  For
  example, a traditional condition variable is stateless, and the reason
  it's still easy to use is that it interacts in special ways with critical 
  sections (mutexes, monitors).  This interaction allows the "state" (the wakeup predicate)
  to be held as arbitrary state within the monitor, rather than within the condition variable.  
  But you don't describe any interaction analogous to this for your Notification, so
  I'm confused about how the default, stateless mode of your Notification can be used
  straightforwardly.

  Consider the example you give on lines 57-77 of notification_ops.py.  In that
  example, I think the workers wait on n, and the controller notifies n.  But
  if workers and controller run asychronously, I don't see what guarantees that
  the workers have all gone to sleep on n before the controller runs the
  notifier.  At least from a naive reading, if a worker performs its
  wait operation after the notification has happened, it would never be woken,
  and thus would deadlock.  Maybe I'm missing something about the setup
  that guarantees that can't happen, but if so if might be wise to
  point out why it works.  If instead this example had used
  "immediatelty_reset=False", it would be clearer, and I suspect that will
  be true of most examples.

- Explicitly resettable waits are hard to use correctly for similar reasons.  
  That's because it's not obvious in general when it's safe to reset the state.
  Synchronization is needed for that, which means you need extra sychronization
  objects to use your synchronization objects, which is usually sign that your synchronization
  objects aren't doing what you wanted.
  When you really need to reset the "woken" state, it's usually better to use a new, 
  non-resettable Notification object, as the machinery for doing that makes it clear 
  that you're waiting for something new.
That's why absl's Notification object is stateful and does not have
a reset operation.

------

You still have a reference to "critical section tests" at line 15 of  notification_test.py.
I suspect you mean "Motification tests".

**Comment by ebrevdo** [comment]
@m3bm3b I think this will require waiting until I return before we continue.  Workers are unlikely to deadlock here because the object exists across multiple session.run calls, so even if one worker is waiting while others are allowed to run -- it'll be allowed to run the next time the master notifies.  i.e., this approach allows stragglers to exist, and these stragglers will wait until a later notification.  For now I'll close this PR as I think there are some additional cleanups possible (notably: statefulness can rely on a scalar bool ResourceVariable which provides a notification mechanism).

**Pull request closed without merging**
