### PR TITLE
Temporary fix to failing test method in estimator_test

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by gunan** [comment]
CC @ispirmustafa 
We also need to cherrypick this into our release branch, release tests are failing with this.

**Comment by gunan** [comment]
hmm, looks like CPU failure is a very similar test.
`tensorflow/python/training/basic_session_run_hooks_test.py`

Could you also edit the test above?

**Comment by caisq** [comment]
@gunan, can you post the link to the basic_session_run_hooks_test failure?  If that test is failing, too, the issue might be related to the StopAfterNEvalsHook and/or MonitoredSession.

**Comment by caisq** [comment]
```
FAIL: test_save_secs_saves_periodically (__main__.CheckpointSaverHookTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pip_test/tests/basic_session_run_hooks_test.py", line 349, in test_save_secs_saves_periodically
    self.global_step.name))
AssertionError: 3 != 4

----------------------------------------------------------------------
Ran 47 tests in 30.707s

FAILED (failures=1)
```

Any thoughts on why the hook got called one extra time, @ispirmustafa ?

**Comment by gunan** [comment]
closing in favor of #6704

**Pull request closed without merging**
