### PR TITLE
Add a warning when fitting models loaded from SavedModels

### PR DESCRIPTION
**Pull request by bhack**
Add a warning when fitting models loaded from SaveModel having optimizers  with slots.
Ref: https://github.com/tensorflow/tensorflow/pull/42749#issuecomment-683964931

### CODE REVIEW

**Comment by bhack** [comment]
This is just an exploring proposal. If you have a better entry point let me know.

**Comment by gbaned** [comment]
@bhack @reedwm @k-w-w  This PR is in draft, any update on this? Please. Thanks!

**Comment by bhack** [comment]
@gbaned I have any private channel so the thread it is what you see here.

**Comment by reedwm** [comment]
Can you give context for this PR? I think adding a warning in fit() for loaded saved models with slot variables is sensible, but I don't see any warnings added in this PR.

**Comment by bhack** [comment]
@reedwm If you see is a draft as I have asked for comment on 1st September about the entry point I selected in the code to introduce" the condition but as of 2nd December I got any feedback. 
I have any other chat channel channel to discuss with devs as Gitter SIG Keras-io/Lobby in the current status is useless for discussion about PRs.

**Comment by reedwm** [comment]
Unfortunately I am not very familiar with the SavedModel code so I'm not sure if this is a good place to do it. Sorry for not responding until now.

@k-w-w, do you think it would be a good idea to add a warning if a SavedModel with slot variables is restored and Model.fit() is used? Currently slot variables are not restored in such a case, which could affect training and is why we should potentially add a warning. If this is a good idea, would the code modified in this PR be a good place to check for the use of slot variables?

**Comment by bhack** [comment]
@reedwm Thank you. Just to note that I've already asked to @k-w-w on 23th Oct at https://github.com/tensorflow/community/pull/281#issuecomment-715596624

**Comment by k-w-w** [comment]
I think directly sending the warning when loading would make sense (see the warning message for the HDF5 format: https://github.com/tensorflow/tensorflow/blob/a6b7e4b94ceb3471a268a57741fe1f32a1472119/tensorflow/python/keras/saving/hdf5_format.py#L211)

**Comment by bhack** [comment]
> The change looks good, although I think directly sending the warning when loading would make sense (see the warning message for the HDF5 format:
> 
> https://github.com/tensorflow/tensorflow/blob/a6b7e4b94ceb3471a268a57741fe1f32a1472119/tensorflow/python/keras/saving/hdf5_format.py#L211
> )

Do you like the same HDF5 warning message or something else?

**Comment by bhack** [comment]
Ok Windows is failing for unrelated MLIR issues and Macos CPU is failing probably for other unrelated stuff but has any visible details.
The other checks are passing.

**Review by k-w-w — APPROVED** [review]
Sorry for the delay, thank you!

**Comment by bhack** [comment]
@k-w-w The sanity is temp broken by https://github.com/tensorflow/tensorflow/pull/48294#issuecomment-849923841

**Comment by k-w-w** [comment]
> @k-w-w The sanity is temp broken by [#48294 (comment)](https://github.com/tensorflow/tensorflow/pull/48294#issuecomment-849923841)

Oh I see, good to know

**Comment by bhack** [comment]
Can you re-trigger the build? I think that the CI Sanity it is working again.

**Comment by bhack** [comment]
Do you need anything else here?

**Review by k-w-w — APPROVED** [review]
Hmm I'm not sure why this isn't being automatically pulled in. Let me try re-approving.

**Comment by bhack** [comment]
@k-w-w If you want you can add a reference somewhere to https://github.com/tensorflow/tensorflow/issues/44670

**Review by gbaned — APPROVED** [review]

**Pull request merged**
