### PR TITLE
check for platform prior to resusing sources for android

### PR DESCRIPTION
**Pull request by ashahba**

### CODE REVIEW

**Comment by gunan** [comment]
Looks like this is an android/lite target.
Could you redirect to a reviewer from that team?

**Comment by rthadur** [comment]
> Looks like this is an android/lite target.
> Could you redirect to a reviewer from that team?

sure @gunan

**Comment by agramesh1** [comment]
@jdduke @gunan Additional info -  
```
bazel test //tensorflow/core/...  
```
fails without this fix if Android build is not enabled. Runs into the following compilation error
```
//tensorflow/core:emscripten_proto_config_lite_runtime: missing input file '//tensorflow/core:android_proto_config.asciipb'
```

**Comment by ashahba** [comment]
Thanks @agramesh1 but seems like we no longer need this.

**Pull request closed without merging**
