### PR TITLE
Fix class_names in image_dataset_from_directory

### PR DESCRIPTION
**Pull request by bhack**
Initial fix of https://github.com/tensorflow/tensorflow/issues/44752

### CODE REVIEW

**Review by fchollet — COMMENTED** [review]
Thank you for the PR. Please add a unit test.

**Comment by bhack** [comment]
@fchollet Do you want that we handle directory/subdirectory walking strategy here? What behavior do you want?

Also do you want a separate PR for https://github.com/tensorflow/tensorflow/issues/44770? 

Cause if we want to think about a refactoring it could impact both tickets.

**Review by fchollet — APPROVED** [review]
Sorry for the delay -- I don't get GitHub notifications. In this case, let's just merge the change, since it's simple enough.

**Comment by bhack** [comment]
@fchollet Let me know what do you want to do with the original issue at https://github.com/tensorflow/tensorflow/issues/44752

**Pull request merged**
