### PR TITLE
resized temp outputs in MnistForwardModel

### PR DESCRIPTION
**Pull request by amturati**
@saxenasaurabh

potential fix to segfault in TestMNISTForward

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by saxenasaurabh** [comment]
This still segfaults internally due to another bug in the gradients infra so I had to disable the test.

@mihaimaruseac would you know why the tests for the original PR #41432 did not catch this?

@amturati Are you able to repro the segfault on your machine. If not, we should look into that.

**Comment by amturati** [comment]
@saxenasaurabh No, on my machine it compiles and runs succesfully

**Comment by mihaimaruseac** [comment]
@amturati what flags do you compile with? Which operating system? Trying to bisect

**Comment by amturati** [comment]
I don't run any additional flags; the command I run is `bazel test: XXX`. I've been working through Secure Shell on the Linux Beta offered on the pixelbooks.

**Pull request merged**
