### PR TITLE
Fixes #16314

### LINKED ISSUE #16314: Published libtensorflow_framework.so binaries ABI Problem
The distributed `libtensorflow_framework.so` included in the JAR files published to Maven are built using the C++ 11 ABI, in contrast to the main TF build. I think that affects all continuous integration builds of the shared objects. I believe the `-D_GLIBCXX_USE_CXX11_ABI=0` compiler flag should be used for the CI builds as is done for the main build. An example of its use is shown in commit 550df413158b32645ca5df4dcaabc67f1a48964d. This causes some trouble when using these shared objects and developing custom ops, as those are required to be built using that compiler flag. It would be great if the use of the flag was consistent and all binaries were built using the same ABI.

Thanks!

### PR DESCRIPTION
**Pull request by eaplatanios**
Fixes #16314.

### CODE REVIEW

**Review by gunan — APPROVED** [review]
We should use this flag during the build, but unfortunately it does not fix all the problems. The gcc flag seems to not always work.

**Comment by eaplatanios** [comment]
@gunan I have noticed that and have been trying to find a solution for a while. This keeps causing a problem with the pre-compiled binaries I distribute with my Scala API for TensorFlow. This change seems to fix the problems I've been having though. I will report if I bump into new issues and look for a solution then, but I need to be able to reproduce.

**Comment by gunan** [comment]
The bigger issue is for our pip packages. maybe the flag is not being propagated properly, but even with this flag we run into ABI incompatibility issues in our pip packages.
If this solves the problem for libtensorflow, that is great! we can solve the pip issue separately.

**Comment by eaplatanios** [comment]
@gunan Sounds good! Yeah I'm not using the pip packages at all so I can't really say anything about them. One minor thing to point out would be to maybe add a note on the "Compiling from Sources" section of the documentation, for people to use that flag when running the bazel build command. I think we could even just add the compiler option in the bazel build files themselves so developers don't have to worry about it.

**Pull request merged**
