### PR TITLE
Update api_def_Ceil.pbtxt

### PR DESCRIPTION
**Pull request by rohanreddych**
tensorflow/core/api_def/base_api/api_def_Ceil.pbtxt

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Similar to #37605 and #37604, we need to first decide if doctests should go into the global API files instead of in Python ones.

**Comment by rohanreddych** [comment]
@mihaimaruseac  can you once check issue #25802 and the pull requests associated with it, they are updating the pbtxt's.

**Comment by mihaimaruseac** [comment]
Thank you for the link to that issue. It seems that only a few of the PRs from there are still in code as of now, most got reverted. Which gives more sense to me asking to wait on this for a decision about whether to include Python tests on general language API defs.

I will come back to all these PRs in a few days once a decision is taken and will guide on how to progress.

**Comment by rohanreddych** [comment]
@mihaimaruseac off topic doubt,if some thing is there in nightly version but not in stable when does it get included in stable version? I mean does it get included in the next TF release like 2.2.x?

**Comment by mihaimaruseac** [comment]
For stable releases it needs to be on `master` when the branch for the release gets cut. So it will go to TF 2.3 now.

**Pull request closed without merging**
