### PR TITLE
Lite: Div Op Int8 support added

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
Ref: #21526

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by harsha070** [comment]
Please merge this PR.

**Comment by gbaned** [comment]
@ANSHUMAN87 Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by ANSHUMAN87** [comment]
I am working on it!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by ANSHUMAN87** [comment]
I will update on this next week. Thanks

**Comment by ANSHUMAN87** [comment]
Closing to reopen with latest changes.

**Pull request closed without merging**
