### PR TITLE
Documentation api reference badge added in Readme.md and added new header for contribution guidelines

### PR DESCRIPTION
**Pull request by rajendraarora16**
* There is no documentation link provided in Readme.md since added a nice badge with api reference link.
* Also I have added a nice header for contribution guidelines.

To see how it looks, please see here:
https://github.com/rajendraarora16/tensorflow

### CODE REVIEW

**Comment by rajendraarora16** [comment]
@rmlarsen please review :)

**Review by martinwicke — APPROVED** [review]
I like it. Thanks!

**Review by martinwicke — CHANGES_REQUESTED** [review]
Actually, can you check in the svg? I'd rather not depend on external assets.

**Comment by martinwicke** [comment]
@gunan reminds me, the icons are served from ci.tensorfllow.org.

**Comment by gunan** [comment]
Well, there are some partial alternatives, but I have no replacement for these yet.
For now, on Feb 28 these badges are going away together with ci.tensorflow.org

**Comment by rajendraarora16** [comment]
@martinwicke Thanks for reviewing :)

I have found some google repos like **https://github.com/google/go-github** are also using badges from shields.io.

Can we implement the same for tensorflow?

**Review by martinwicke — APPROVED** [review]
Yeah. It's fine.

**Comment by rajendraarora16** [comment]
Thank you @martinwicke :)

**Pull request merged**
