### PR TITLE
Move code shared between lite and micro to elementwise_portable.h

### PR DESCRIPTION
**Pull request by patriklaurell**
This PR refactors the elementwise kernel and moves code shared between Lite and Micro to elementwise_portable.h, as suggested by @advaitjain [here](https://github.com/tensorflow/tflite-micro/pull/204#pullrequestreview-692482804)

### CODE REVIEW

**Comment by wangtz** [comment]
Hi Patrick,

I think micro related issues should be raised in https://github.com/tensorflow/tflite-micro

Thanks,
Tiezhen

**Comment by advaitjain** [comment]
> Hi Patrick,
> 
> I think micro related issues should be raised in https://github.com/tensorflow/tflite-micro
> 
> Thanks,
> Tiezhen

This is a pull request that refactors the code in tflite to allow for more sharing when it is exported to tflite-micro. As such, the tensorflow repository is the correct location for this change.

**Comment by gbaned** [comment]
@advaitjain  Can you please review this PR ? Thanks!

**Comment by patriklaurell** [comment]
@advaitjain ready for review. I must have mistakenly pushed a commit last week. I apologize for any inconvenience caused.  953111e is the commit relevant for review.

**Comment by patriklaurell** [comment]
@advaitjain I needed to move `IsSqrtSupportedType` to back into elementwise.cc to get the micro kernel to compile. Since micro only has float32 support for RSQRT it uses `IsNumericSupportedType` and the compilation fails due to `IsRsqrtSupportedType` being defined but unused.

**Comment by gbaned** [comment]
@advaitjain Can you please assist on above comments from @patriklaurell. Thanks!

**Comment by patriklaurell** [comment]
@advaitjain @liufengdb ready for review

**Comment by advaitjain** [comment]
Apologies, I sent you down the wrong path with https://github.com/tensorflow/tflite-micro/pull/204#pullrequestreview-692482804. 

While the code looks like it can be shared, there are small differences which make it incompatible with TFLM.

This discrepancy is made more explicit by the recently added AllocateTempInputTensor API:
https://github.com/tensorflow/tflite-micro/blob/8a710d8ff01fd5d8797caaf349608b89ac2119ec/tensorflow/lite/micro/micro_context.h#L62-L67

I'm going to close this PR.

**Pull request closed without merging**
