### PR TITLE
tf.const now supports verification of a shape of values. 

### PR DESCRIPTION
**Pull request by b0noI**
If shape that is passed via the argument is not consistent with the value in the shape variable ValueError will be raised. Example:

"Expected Tensor's shape: (2, 1), got (1, 2)"

### CODE REVIEW

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@vrv this looks like a useful feature to me. Do you agree that we should extend the API of constant?

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by b0noI** [comment]
ERROR form the CI:
FAIL: Found 2 non-whitelited pylint errors:
tensorflow/python/framework/tensor_util.py:402: [W0311(bad-indentation), ] Bad indentation. Found 8 spaces, expected 6

tensorflow/python/framework/tensor_util.py:403: [W0311(bad-indentation), ] Bad indentation. Found 12 spaces, expected 8

looks like style checks error, will fix till EOD.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
