### PR TITLE
Add RecordInput documentation to tf.contrib.framework

### LINKED ISSUE #10622: RecordInput Documentation in API doc site
[RecordInput is in the tf 1.2 code](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/python/ops/data_flow_ops.py#L1602) but I don't see it in the [tf 1.2 API docs](https://www.tensorflow.org/versions/r1.2/api_docs/python/). Should it be present?

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #10622 where the RecordInput is not available in the documentation.

As was suggested in #10622, this fix exposes RecordInput to tf.contrib (tf.contrib.framework) so that docs could shown up.

After this change and run with:
```
bazel run tools/docs:generate --
           --src_dir="$(pwd)/docs_src/"
           --output_dir=/tmp/tfdocs/
```
The documentation correctly shown up in:
`/tmp/tfdocs/api_docs/python/tf/contrib/framework/RecordInput.md`

This fix fixes #10622.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment]
The PR has been rebased to resolve merge conflicts.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 36 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 51 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 66 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 81 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 111 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by annarev — DISMISSED** [review]
Approving based on @martinwicke comment in the linked Issue that it is ok to add this contrib endpoint.

**Review by annarev — APPROVED** [review]

**Pull request merged**
