### PR TITLE
Adding cuda_config.h to the pip package.

### PR DESCRIPTION
**Pull request by av8ramit**

### CODE REVIEW

**Comment by av8ramit** [comment]
http://ci.tensorflow.org/view/Release/job/test_cuda/4/
Pip package contains cuda_config.h

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by av8ramit** [comment]
http://ci.tensorflow.org/job/test_cuda/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/7/artifact/pip_test/whl/tensorflow_gpu-1.5.0rc0-cp27-cp27mu-manylinux1_x86_64.whl

**Comment by av8ramit** [comment]
Breakages are unrelated.

**Review by gunan — APPROVED** [review]

**Pull request merged**
