### PR TITLE
[PluggableDevice] Link `pywrap_tensorflow_internal` with `kernels_experimental`

### PR DESCRIPTION
**Pull request by PatriceVignola**
Because Windows python builds don't come with `tensorflow_framework.dll`, they don't currently expose any of the experimental kernel functions which are necessary to support resource operations in pluggable devices.

### CODE REVIEW

**Comment by wchao1115** [comment]
Reaching out to you @penpornk for help finding the right reviews going for @PatriceVignola. Pat is an engineer in my team actively working on TF2 pluggable device for DirectML. He has been proposing a few PRs to move us along with our plan to support TF2 on Windows through the pluggable device interface e.g. other than this PR there is also #53484 for example. @jstoecker

**Comment by wchao1115** [comment]
@penpornk Would you please help look into this PR or point us to someone who could help review and approve this change? It is currently blocking our plug-in development on Windows build. Thanks!

**Review by penpornk — APPROVED** [review]
@wchao1115 @PatriceVignola Sorry for the late reply! I've been on vacation. 

Thank you for the PR! The change looks good to me. Cc'ing @mihaimaruseac just in case.

**Review by mihaimaruseac — APPROVED** [review]

**Review by penpornk — CHANGES_REQUESTED** [review]
This PR seems to break our [Ubuntu CPU](https://source.cloud.google.com/results/invocations/652958ff-7e74-43d9-9be4-da7e296356a0), [Linux GPU](https://source.cloud.google.com/results/invocations/16a006fa-5359-4759-86b5-31180d378a01), and [MacOS CPU](https://source.cloud.google.com/results/invocations/e5976f9c-17bd-4c7e-83a4-9738d8e678cf) builds. Can we try adding the dependency just for Windows? Thank you!

**Comment by PatriceVignola** [comment]
> This PR seems to break our [Ubuntu CPU](https://source.cloud.google.com/results/invocations/652958ff-7e74-43d9-9be4-da7e296356a0), [Linux GPU](https://source.cloud.google.com/results/invocations/16a006fa-5359-4759-86b5-31180d378a01), and [MacOS CPU](https://source.cloud.google.com/results/invocations/e5976f9c-17bd-4c7e-83a4-9738d8e678cf) builds. Can we try adding the dependency just for Windows? Thank you!

Done!

**Review by penpornk — APPROVED** [review]
Thank you for the quick change!

**Comment by gbaned** [comment]
@PatriceVignola Can you please address Ubuntu Sanity errors? Thanks!

**Comment by PatriceVignola** [comment]
@gbaned I fixed the buildifier warnings.

**Review by penpornk — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
