### PR TITLE
When events are specified as root events by user, they should be treated as root events in trace view.

### PR DESCRIPTION
**Pull request by burgerkingeater**
When events are created with _r by users like this https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/keras/engine/training.py#L1098, [it indicates they are root events](https://github.com/tensorflow/tensorflow/blob/v2.4.0/tensorflow/core/profiler/utils/xplane_schema.cc#L168).
Thus those user-specified root events should be processed as root events in the first place. 

However according to current processing order, [they are the last group of events to be processed](https://github.com/tensorflow/tensorflow/blob/v2.4.0/tensorflow/core/profiler/utils/group_events.cc#L616). If any event fits into any of the preceding criteria of root events, they will be processed as root, [then the function will return](https://github.com/tensorflow/tensorflow/blob/v2.4.0/tensorflow/core/profiler/utils/group_events.cc#L603), skipping the subsequent user-specified root events processing, which is undesirable.

One consequence is when events like [these](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/engine/training.py#L1093) are not processed as root events, it breaks profiler's overview page as the profiler overview page relies on the root events and their step numbers to collect per-step time breakdown.

### CODE REVIEW

**Comment by burgerkingeater** [comment]
@jray319 @Terranlee would you mind taking a look?

**Comment by Terranlee** [comment]
_r is not only used by user defined root events, but also used by some legacy root events. See the IsLegacyRootEvent function in group_events.cc. Changing the order of root_events_ will affect existing users with legacy root events

**Comment by burgerkingeater** [comment]
@Terranlee when _r is specified, should it override other root events? If so, why is current logic putting processing `_r` events at the last?

**Comment by burgerkingeater** [comment]
@jray319 @Terranlee let me know if you have any feedback on this change.

**Comment by Terranlee** [comment]
Hi Cheng, Jiho and I are trying to understand your use case for event grouping.
You mentioned the user defined root events like [keras training loop](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/engine/training.py#L1093)

Does this mean your job has both keras level loop and TF level loop? Right now the overview page is focused on the TF level loop and that is the only thing it displays, do you want to see the result at keras level loop?

Can you share with us a profile so we can better understand your use case?

Thanks.

**Comment by burgerkingeater** [comment]
@Terranlee thanks for your reply. What do you mean TF level loop? Do you have some sample code for that?

I assume in order to make overview work, trace and root events need to be defined like what keras(https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/engine/training.py#L1093) does, and this is also what doc says: https://www.tensorflow.org/guide/profiler#profiling_custom_training_loops.

For keras, it's not needed since keras already did this in the code as shown above,
but for custom training loop(https://www.tensorflow.org/guide/profiler#profiling_custom_training_loops) , users need to define the root event and trace themselves.

**Comment by burgerkingeater** [comment]
@Terranlee @jray319 please let me know if you have any feedback for this.

**Comment by gbaned** [comment]
@burgerkingeater Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@burgerkingeater  Any update on this PR? Please. Thanks!

**Comment by burgerkingeater** [comment]
@gbaned will do, thanks!

**Comment by burgerkingeater** [comment]
@gbaned @Terranlee @jray319 updated the PR with latest master. Could you take a look when you have time? Thanks

**Comment by burgerkingeater** [comment]
any feedback on this PR?  @Terranlee @jray319

**Comment by burgerkingeater** [comment]
kindly ping again @Terranlee @jray319

**Comment by burgerkingeater** [comment]
@Terranlee @jray319 mind taking a look when you have a chance?

**Comment by burgerkingeater** [comment]
@gbaned If the assigned reviewers are not currently available, would you mind having others review this PR? Please let me know if there's anything needed from my side. Thanks.

**Comment by jpienaar** [comment]
I pinged the team that is responsible for this code and they'll follow up here.

**Comment by Terranlee** [comment]
Hi, sorry for the late reply to this issue.
I tried this PR in our code base and some of the existing event grouping tests failed.
The issue happens when tf_loop_root_events_ and root_events both are not empty, the code we have right now will treat tf_loop_root_events_ as a special root event and ignores other root events.
In https://github.com/tensorflow/tensorflow/pull/48922#issuecomment-840933781 you mentioned you are using customized training loop(https://www.tensorflow.org/guide/profiler#profiling_custom_training_loops), in that case do you find tf_loop_root_events_ to be not empty?

**Comment by burgerkingeater** [comment]
@Terranlee would you mind posting the details of the failed tests? 
If both `tf_loop_root_events_` and `root_events` are not empty, in this PR, the logic becomes process root_events firstly and ignore `tf_loop_root_events_` regardless it's empty or not.

**Comment by burgerkingeater** [comment]
@Terranlee can we schedule a virtual meeting on this PR? It has been while and I really would like to merge it soon.

**Comment by Terranlee** [comment]
I scheduled a meeting on Friday to talk about this PR.
Please change if the time does not work for you.
Thanks.

**Comment by burgerkingeater** [comment]
@Terranlee thanks, can you send me the invite? My email is rencheng311@gmail.com

**Comment by burgerkingeater** [comment]
@Terranlee thanks, saw the invite, the time LGTM. See you then!

**Comment by gbaned** [comment]
@Terranlee Can you please review this PR ? Thanks!

**Comment by Terranlee** [comment]
I talked with burgerkingeater last time and it is not easy to make this change because it will break some google internal code.
Can you send me an example of your profile (the XSpace file)? so I can look at why the events are not grouped as you expected?
Thanks.

**Comment by gbaned** [comment]
@burgerkingeater Can you please check above @Terranlee's comments and keep us posted ? Thanks!

**Pull request closed without merging**
