### PR TITLE
[documentation] Updated comment for tf.multnomial

### PR DESCRIPTION
**Pull request by gnedivad**
Self-explanatory.

### CODE REVIEW

**Comment by drpngx** [comment]
Could you sign the CLA? We need this.

**Comment by gnedivad** [comment]
Done.

**Comment by martinwicke** [comment]
I'm not sure this is an improvement.

@aselle what say you?

**Comment by gnedivad** [comment]
Up to you, though I think it's worth noting that "unnormalized log probabilities" makes it seem like the function accepts log probabilities (which it doesn't). It accepts log-odds!!!

The documentation of the underlying function that implements `tf.multinomial` is actually more precise; this is how I figured out that I needed to pass log-odds in the first place.

**Comment by martinwicke** [comment]
Apologies, you are correct. Thanks!

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Pull request merged**
