### PR TITLE
Adjust audio_provider for the sparkfun_edge for production boards.

### PR DESCRIPTION
**Pull request by suphoff**
Temporary gain emulation to deal with too-quiet audio on prototype boards
together with fluctuating 'zero' level offset causes oversaturation on
production boards.

cc: @petewarden

### CODE REVIEW

**Comment by suphoff** [comment]
Please add label comp:micro so it gets in the right queue

**Comment by gbaned** [comment]
ping @petewarden for review ?

**Comment by gbaned** [comment]
@suphoff  Can you please resolve conflicts? Thanks!

**Comment by suphoff** [comment]
Updated

**Comment by petewarden** [comment]
Thanks for your patience! We're not going to take this PR, since we're hoping the number of proto boards is pretty small now and newer generations are moving over to digital mics.

**Pull request closed without merging**
