### PR TITLE
Remove all_opensource_files

### LINKED ISSUE #15758: Getting rid of all_opensource_files
This ticket is for tracking the progress of removing the `all_opensource_files` bazel target.
See the discussion in #15368.

- [x] Turn `check_futures_test` into a sanity check #15671
- [x] De-Bazel `check_load_py_test` sanity check #15677
- [x] De-Bazel `pip_smoke_test` sanity check #15678
- [x] Rewrite `//tensorflow/contrib/makefile:build_all_linux`
- [x] Remove `all_opensource_files` bb582f1b6fad474bc446c78a6683247a8eb6048e

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #15758
@gunan /cc
@yifeif /cc

### CODE REVIEW

**Comment by Androbin** [comment]
Relying on https://github.com/tensorflow/tensorflow/pull/15368#issuecomment-354159959

**Comment by gunan** [comment]
I have found a few additional internal checks that depend on this, so we are not ready to merge this PR yet.
We need to discuss how we can move those checks to not use bazel.

**Comment by Androbin** [comment]
Either we get rid of the dependency or we remove the boilerplate with bazelbuild/bazel#4577.

**Comment by yifeif** [comment]
Looks like we will still need to export some of the files or change their visibility so other targets can access them. How should  we go about this? @gunan any suggestion?

**Comment by gunan** [comment]
I think we need some filegroup rules, and new data dependencies on these filegroup rules. Those fixes should be a part of this, as they will be "thinner" replacements to the all_files rules these tests are already depending on.
Could you go through the broken tests and triage the build failures?

**Comment by yifeif** [comment]
@Androbin do you mind adding this suggested fix:
`/tmpfs/src/github/tensorflow/tensorflow/core/ops/compat/BUILD:33:1: no such target '//tensorflow/core:ops/ops.pbtxt': target 'ops/ops.pbtxt' not declared in package 'tensorflow/core'; however, a source file of this name exists.  (Perhaps add 'exports_files(["ops/ops.pbtxt"])' to tensorflow/core/BUILD?) defined by /tmpfs/src/github/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/ops/compat:backwards_compatibility_test'`

**Comment by Androbin** [comment]
Good catch!

**Comment by Androbin** [comment]
Last build failed because of `master`. Rebased on last successful build and resolved merge conflicts.

**Comment by yifeif** [comment]
Looks like there are a few more:
`ERROR: /tmpfs/src/github/tensorflow/tensorflow/examples/image_retraining/BUILD:28:1: no such target '//tensorflow/examples/label_image:data/grace_hopper.jpg': target 'data/grace_hopper.jpg' not declared in package 'tensorflow/examples/label_image'; however, a source file of this name exists.  (Perhaps add 'exports_files(["data/grace_hopper.jpg"])' to tensorflow/examples/label_image/BUILD?) defined by /tmpfs/src/github/tensorflow/tensorflow/examples/label_image/BUILD and referenced by '//tensorflow/examples/image_retraining:retrain_test'`

**Comment by Androbin** [comment]
Okay, that made `bazel nobuild` pass locally.

**Comment by Androbin** [comment]
Last build succeeded. Had to resolve a minor merge conflict.

**Comment by yifeif** [comment]
Thanks @Androbin! Let's see how the builds go.

**Comment by Androbin** [comment]
Oops, `master` is failing hard and as of the rebase, this PR inherited its errors.
I can't tell in which commit these have been introduced.
@yifeif We should probably wait for stable `master` and then rebase.

**Comment by yifeif** [comment]
We had some infra issue earlier. It should be fine now.

**Comment by Androbin** [comment]
Last build successful (99f5d4e17d360b57ba3dea54d14b91ba730910e2)
Had to resolve minor merge conflict (f6bda409206dc642d7a6f02842e76b0be7234491)

**Comment by Androbin** [comment]
@yifeif Basically any addition to a `BUILD` file will "conflict" with the removal of an `all_files` target.
On the next successful build, it shouldn't take us 2 days to merge.

**Comment by yifeif** [comment]
Hi @Androbin sorry for the delay, I was thinking of bringing this PR in independently and was waiting for the sync to resolve merge conflicts. Let me give it another shot.

**Comment by yifeif** [comment]
@Androbin I managed to create a pending internal change with your PR, and unfortunately found another internal dependency on all_files. Will let you know once we figure out how we can remove it. Thanks.

**Comment by yifeif** [comment]
@Androbin quick update: the internal dependency issue has been fixed. I'm working on submitting this change internally following [this process](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#contributing-code).

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yifeif** [comment]
https://github.com/tensorflow/tensorflow/commit/bb582f1b6fad474bc446c78a6683247a8eb6048e has been submitted. I'm going to close this PR. Thanks @Androbin!

**Pull request closed without merging**
