### PR TITLE
Adding support for Linux s390x

### PR DESCRIPTION
**Pull request by kbhute-ibm**
As discussed in https://github.com/tensorflow/tensorflow/issues/26135 creating a PR to fix below test cases on s390x:

//tensorflow/python:nn_test
//tensorflow/contrib/distributions:independent_test
//tensorflow/contrib/layers:normalization_test

### CODE REVIEW

**Comment by rthadur** [comment]
@kbhute-ibm please sign CLA

**Comment by martinwicke** [comment]
Hmm... changing the dtype clearly does the trick, but it seems broken that we have to. big endian shouldn't be inherently less accurate, right? I'm just wondering whether this simply papers over a bug.

**Comment by kbhute-ibm** [comment]
I signed it!

**Comment by kbhute-ibm** [comment]
Hi @martinwicke,

Thanks for the comment. We already had a discussion with @gunan [here](https://github.com/tensorflow/tensorflow/issues/26135#issuecomment-467963074). Please let me know if you need any more details.

Thanks :)

**Comment by kbhute-ibm** [comment]
Hi @rthadur @martinwicke,
Any inputs please?

**Comment by martinwicke** [comment]
I looked at #26135, I still don't understand why big endian systems would require a different threshold (I didn't see a discussion of that in the other PR -- just a verification that it's not flaky). 

This doesn't have to block this -- but I'm a little concerned that we're hiding a problem instead of fixing it. Unless big endian architectures have inherently less numerical precision (which seems hard to believe), this change to the tests is hard to justify.

**Comment by kbhute-ibm** [comment]
Hi @martinwicke, 
I am confirming if this is related to [Numpy bug](https://github.com/tensorflow/tensorflow/pull/12963) and [Github issue](https://github.com/tensorflow/tensorflow/issues/11431). Please share your inputs on this if any.

Till I reach to some point, could you please guide me in knowing the impact of these test case failures on TensorFlow functionality?

**Comment by martinwicke** [comment]
Yes, that numpy bug could very well be the root cause. If your theory is correct, I'd love for this to be fixed in a workaround similar to https://github.com/tensorflow/tensorflow/pull/12963 (instead of fixing the tests). If you cannot find a root cause, we can merge this instead.

**Comment by kbhute-ibm** [comment]
Hi @martinwicke 
We debugged the code further for //tensorflow/python:nn_test. The test case fails with following values:
`mu = 1e3`, `sigma = 0.1` and `keep_dims = False`. When it hits `nparray = values.astype(dtype.as_numpy_dtype)` [here](https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/python/framework/tensor_util.py#L416) the array values changes for dtype=tf.float32. However if its dtype=tf.float64, the values remain constant on s390x.

```
(Pdb) p values
array([[ 1000.01846343,  1000.07748109,  1000.05901822, ...,
         1000.09638957,  1000.09352149,  1000.04648203],
       [ 1000.0527755 ,  1000.06733742,  1000.0641509 , ...,
         1000.04154237,  1000.09075805,  1000.03772178],
       [ 1000.03718904,  1000.03666347,  1000.09894839, ...,
         1000.00636682,  1000.09297756,  1000.00986914],
       ...,
       [ 1000.03859482,  1000.03546114,  1000.05678384, ...,
         1000.00672955,  1000.07011743,  1000.04866641],
       [ 1000.06618747,  1000.05226396,  1000.09398577, ...,
         1000.08058321,  1000.02070808,  1000.03280688],
       [ 1000.00648291,  1000.09405838,  1000.03243373, ...,
         1000.05311184,  1000.08248722,  1000.02524148]])
(Pdb) p dtype.as_numpy_dtype
<type 'numpy.float64'>
(Pdb) values.astype(dtype.as_numpy_dtype)
array([[ 1000.01846343,  1000.07748109,  1000.05901822, ...,
         1000.09638957,  1000.09352149,  1000.04648203],
       [ 1000.0527755 ,  1000.06733742,  1000.0641509 , ...,
         1000.04154237,  1000.09075805,  1000.03772178],
       [ 1000.03718904,  1000.03666347,  1000.09894839, ...,
         1000.00636682,  1000.09297756,  1000.00986914],
       ...,
       [ 1000.03859482,  1000.03546114,  1000.05678384, ...,
         1000.00672955,  1000.07011743,  1000.04866641],
       [ 1000.06618747,  1000.05226396,  1000.09398577, ...,
         1000.08058321,  1000.02070808,  1000.03280688],
       [ 1000.00648291,  1000.09405838,  1000.03243373, ...,
         1000.05311184,  1000.08248722,  1000.02524148]])

(Pdb) dtype1.as_numpy_dtype
<type 'numpy.float32'>
(Pdb) values.astype(dtype1.as_numpy_dtype)
array([[ 1000.01849365,  1000.07745361,  1000.059021  , ...,
         1000.09637451,  1000.09350586,  1000.04650879],
       [ 1000.05279541,  1000.06732178,  1000.06414795, ...,
         1000.04156494,  1000.09075928,  1000.03771973],
       [ 1000.03717041,  1000.03668213,  1000.09893799, ...,
         1000.00634766,  1000.09295654,  1000.0098877 ],
       ...,
       [ 1000.03857422,  1000.03546143,  1000.0567627 , ...,
         1000.00671387,  1000.07012939,  1000.04864502],
       [ 1000.06616211,  1000.05224609,  1000.09399414, ...,
         1000.08056641,  1000.02069092,  1000.03283691],
       [ 1000.00646973,  1000.09405518,  1000.03240967, ...,
         1000.05310059,  1000.0824585 ,  1000.02526855]], dtype=float32)
```

Debugging is still going on but please share your inputs on same if any as it would streamline our investigation.

Thanks,
Koumudini

**Comment by kbhute-ibm** [comment]
Hi @martinwicke 
Few more findings on the investigation:

On Intel:
```
(Pdb) input_shape = (3,3)
(Pdb) sigma = 0.1
(Pdb) mu = 1000.0
(Pdb) m = np.random.rand(*input_shape) * sigma + mu
(Pdb) m.astype(np.float32)
array([[1000.09625, 1000.0288 , 1000.06494],
       [1000.0495 , 1000.02466, 1000.0644 ],
       [1000.0143 , 1000.031  , 1000.09705]], dtype=float32)
(Pdb) m.astype(np.float64)
array([[1000.09628103, 1000.02878154, 1000.06495031],
       [1000.04949626, 1000.02468053, 1000.06442176],
       [1000.01426861, 1000.03101769, 1000.09702152]])
```

On Z:
```
(Pdb) input_shape = (3,3)
(Pdb) sigma = 0.1
(Pdb) mu = 1000.0
(Pdb) m = np.random.rand(*input_shape) * sigma + mu
(Pdb) m.astype(np.float32)
array([[ 1000.034729  ,  1000.06030273,  1000.09344482],
       [ 1000.07342529,  1000.01916504,  1000.06616211],
       [ 1000.08764648,  1000.09729004,  1000.07043457]], dtype=float32)
(Pdb) m.astype(np.float64)
array([[ 1000.03471172,  1000.06030737,  1000.09343678],
       [ 1000.07343308,  1000.01916033,  1000.06618081],
       [ 1000.08764095,  1000.09729445,  1000.07041618]])
```

I wonder in case of `m.astype(np.float32)` where does `dtype=float32` come from in output. Could you please give us some pointers on this? 

In case of [this](https://github.com/tensorflow/tensorflow/pull/12963) issue, ndarray is created with `np.ndarray(shape=(), buffer=np.array([input_shape.ndims], dtype=np.int32), dtype=np.int32)` command, whereas in this case, it get randomly created with `np.random.rand(*input_shape) * sigma + mu`. The issue looks similar but not sure where to exactly look into. Please suggest.

Thanks.

**Comment by kbhute-ibm** [comment]
Hi @martinwicke ,
As I mentioned in one of my earlier comments, original NumPy array with basetype float64 is cast into float32. As per comments from @mrry and @zffchen78 on [this issue](https://github.com/tensorflow/tensorflow/issues/14017#issuecomment-352573861) this behavior of casting can not be changed. 

In this test case, `nparray.tostring()` changes its byte ordering on BE. This is NumPy's native behavior. To fix this issue we have a workaround as below, please let us know your suggestion on same:

```diff
 import numpy as np
 import six
+import sys
 from tensorflow.core.framework import tensor_pb2
 from tensorflow.core.framework import tensor_shape_pb2
 from tensorflow.python.framework import ops
@@ -409,11 +409,16 @@ def make_tensor_proto(values, dtype=None, shape=None, verify_shape=False):
           dtypes.qint8, dtypes.quint8, dtypes.qint16, dtypes.quint16,
           dtypes.qint32
       ])
+  isbasetypesame = False
   # We first convert value to a numpy array or scalar.
   if isinstance(values, (np.ndarray, np.generic)):
     if dtype:
-      nparray = values.astype(dtype.as_numpy_dtype)
+      # Do not cast `values` to float32 on big endian
+      if sys.byteorder == 'big':
+        nparray = values
+      else:
+        nparray = values.astype(dtype.as_numpy_dtype)
+        isbasetypesame = dtype.base_dtype != numpy_dtype.base_dtype
@@ -471,8 +476,7 @@ def make_tensor_proto(values, dtype=None, shape=None, verify_shape=False):
   if is_quantized:
     numpy_dtype = dtype

-  if dtype is not None and (not hasattr(dtype, "base_dtype") or
-                            dtype.base_dtype != numpy_dtype.base_dtype):
+  if dtype is not None and (not hasattr(dtype, "base_dtype") or isbasetypesame):
     raise TypeError("Incompatible types: %s vs. %s. Value is %s" %
                     (dtype, nparray.dtype, values))

```

Adding @gunan to the discussion for more suggestions. Thanks.

**Comment by kbhute-ibm** [comment]
@martinwicke , please post your response.

**Comment by martinwicke** [comment]
Just to make sure I understand correctly, would the diff you showed fix the problems?

I don't think it's terribly problematic to change the casting behavior on BE only, given that a bug in numpy makes the behavior inconsistent on the platform. 

@mrry in case I'm getting this wrong.

**Comment by mrry** [comment]
Is there a small reproduction that shows the problem, without involving the details of these unit tests? I don't understand what's being proposed.

**Comment by kbhute-ibm** [comment]
Hi @martinwicke @mrry 
I had shifted to some other test case failures and will get back to this one soon.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by kbhute-ibm** [comment]
This PR is being discussed in one of the related open issues. We will close this if not valid.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
