### PR TITLE
Allow specifying dtype to keras dataset generator

### PR DESCRIPTION
**Pull request by Cyniikal**
This change would allow image_dataset_from_directory to load images with
arbitary dtypes, like 16 bit IR imagery.

### CODE REVIEW

**Comment by qlzh727** [comment]
Looks Good to me, since this update the API interface, adding @fchollet as the API owner for review.

**Review by fchollet — COMMENTED** [review]
Thanks for the PR. Looks good, please add a unit test.

**Comment by Cyniikal** [comment]
Not sure if it's okay for me to modify the internal methods in the testing code, but I didn't want to just copy//paste stuff from _get_images and _prepare_directory into my test.

**Review by fchollet — CHANGES_REQUESTED** [review]
> +36,982 −9,895

It looks like your PR needs to be rebased. It contains many unrelated changes.

**Comment by Cyniikal** [comment]
> > +36,982 −9,895
> 
> It looks like your PR needs to be rebased. It contains many unrelated changes.

Fixed, sorry about that.

**Review by fchollet — APPROVED** [review]

**Comment by rthadur** [comment]
@Cyniikal can you please check sanity build failures ?

**Comment by Cyniikal** [comment]
> @Cyniikal can you please check sanity build failures ?

Should be good now.

**Comment by fchollet** [comment]
This PR wasn't merged. Is this the desired outcome?

**Pull request closed without merging**
