### PR TITLE
Add tf.linalg.normalize

### PR DESCRIPTION
**Pull request by sleighsoft**
As discussed in #28741.

Note: Now calling tf.linalg.l2_normalize(x) is identical to tf.linalg.normalize(x, axis=None).
I did not peform any changes to l2_normalize to not break anything.

The only thing that would break here is the name scoping as that would result in l2_normalize>normalize>norm instead of just l2_normalize.

Regarding the test. This test is based on the the test provided for tf.norm. I can change nn_test.py to add individual tests for each case if required.

### CODE REVIEW

**Comment by sleighsoft** [comment]
@alextp Re-opened PR

**Review by alextp — DISMISSED** [review]

**Comment by sleighsoft** [comment]
I do not see the connection between the failing tests and what I change.

**Comment by gbaned** [comment]
@sleighsoft  Can you please check Ubuntu Sanity errors and keep us posted. Thanks!

**Comment by sleighsoft** [comment]
> 
> 
> @sleighsoft Can you please check Ubuntu Sanity errors and keep us posted. Thanks!

That one escaped me. Fixed the wrong indentations.

**Review by alextp — DISMISSED** [review]

**Comment by sleighsoft** [comment]
@alextp norm_op_test.py has the following additional tags in BUILD
```
    tags = [
        "no_windows_gpu",
        "nomsan",
    ],
```
Maybe I have to add them as well. Even though, again, I don't understand why.
`nosman` is not very descriptive and why `tf.norm` has `no_windows_gpu` is unclear as well.

**Review by alextp — APPROVED** [review]
no_windows_gpu: do not run this test on windows gpu builds
nomsan: do not run this test with https://clang.llvm.org/docs/MemorySanitizer.html

**Comment by sleighsoft** [comment]
Thank you for clarifying `nomsan`. Regarding the `no_windows_gpu`. I was wondering why it is there in the first place. Some test seem to fail again. I don't see my code being the reason in the logs.

**Comment by sleighsoft** [comment]
Any ideas why `Windows Bazel` and `MacOS Contrib` fail?

**Comment by sleighsoft** [comment]
Any status update here?

**Comment by alextp** [comment]
The windows failure looks like an unrelated flake, `ERROR: T:/src/github/tensorflow/tensorflow/python/tools/BUILD:140:1 C++ compilation of rule '//tensorflow/core/util/tensor_bundle:tensor_bundle' failed (Exit 2): cl.exe failed: error executing command`, so rerunning.

**Comment by alextp** [comment]
@gbaned why request another review? I have already approved the latest snapshot of this

**Comment by gbaned** [comment]
> @gbaned why request another review? I have already approved the latest snapshot of this

@alextp My apologies for that. Thank you.

**Pull request merged**
