### PR TITLE
fix a wrong example in slim README

### PR DESCRIPTION
**Pull request by v1incent**

### CODE REVIEW

**Comment by v1incent** [comment]
I signed it!

**Comment by v1incent** [comment]
test CLA

**Comment by v1incent** [comment]
test CLA

**Review by dynamicwebpaige — APPROVED** [review]
👍 LGTM - thanks for noticing the error, and for making a PR to fix it! Please note that beginning in TensorFlow 2.0, `tf.contrib.slim` will be **removed**, as well as all other endpoints in `tf.contrib`.

**Pull request merged**
