### PR TITLE
Fix tf.reduce_logsumexp to accept `-inf`

### LINKED ISSUE #11692: A bug of tf.reduce_logsumexp with `-inf`
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux CentOS 7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2.0
- **Python version**: 2.7.13
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 8.0/5.1.3
- **GPU model and memory**: Tesla K40m, 11439MiB
- **Exact command to reproduce**:  `python -c "import tensorflow as tf; print tf.Session().run(tf.reduce_logsumexp(float('-inf')))"`

### Describe the problem
The doc of tf.reduce_logsumexp says it

> Computes log(sum(exp(elements across dimensions of a tensor))).

However, it does not when the tensor is `-inf`.

### Source code / logs
```
python -c "import tensorflow as tf; print tf.Session().run(tf.reduce_logsumexp(float('-inf')))"
```
prints
```
nan
```
--------------------

```
python -c "import tensorflow as tf; print tf.Session().run(tf.log(tf.reduce_sum(tf.exp(float('-inf')))))"
```
prints
```
-inf
```

### PR DESCRIPTION
**Pull request by meijun**
Fix #11692

### CODE REVIEW

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
Known flakiness in the mac failure.  Looks good for review @aselle !

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
The test failure is unrelated. Merging.

**Pull request merged**
