### PR TITLE
doc: fix typo in api_guides/cc/guide.md

### PR DESCRIPTION
**Pull request by peacedog123**
When I was learning the cc api from official site, I found the calculation result  and the comment doesn't match, so I send this PR.

### CODE REVIEW

**Comment by peacedog123** [comment]
I signed it!

**Review by olicht — APPROVED** [review]
You are correct. (it needs to be 41 so that the MatMul output 0 would be 42)

**Review by wt-huang — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by peacedog123** [comment]
I have made the pr for the docs project, so this pr can be  closed.

**Comment by peacedog123** [comment]
closed

**Pull request closed without merging**
