### PR TITLE
[ROCm] Adding complex types to existing hipsparse functionality 

### PR DESCRIPTION
**Pull request by stevenireeves**
Added complex support for:
- csrgemm
- csrmm
- csr2coo
- coo2csr
- csrmm2

@cheshire for review.

### CODE REVIEW

**Review by cheshire — APPROVED** [review]

**Comment by gbaned** [comment]
@stevenireeves  Can you please address Ubuntu Sanity errors? Thanks!

**Comment by stevenireeves** [comment]
@gbaned 

The Ubuntu Sanity failure is from pylint. But it is referencing files that were not changed in this PR:
 
Found 2 non-allowlisted pylint errors:
tensorflow/compiler/tests/binary_ops_test.py:721: [E1130(invalid-unary-operand-type), BinaryOpsTest._testDivision] bad operand type for unary -: max
tensorflow/compiler/tests/binary_ops_test.py:753: [E1130(invalid-unary-operand-type), BinaryOpsTest._testRemainder] bad operand type for unary -: max

**Comment by stevenireeves** [comment]
@gbaned 

This seems to have been addressed in https://github.com/tensorflow/tensorflow/commit/061dec2ab7fd91f369598b2223ba388e5b10777d

**Comment by stevenireeves** [comment]
@gbaned Is that satisfactory?

**Comment by stevenireeves** [comment]
@gbaned I have merged the changes from 061dec2 to solve the pylint error in the Sanity Check.

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Comment by stevenireeves** [comment]
@cheshire @gbaned Is this PR moving forward?

**Comment by akuegel** [comment]
This was rolled back because the test dataset is too big and caused test failures for csr_sparse_matrix_ops_test.

**Comment by stevenireeves** [comment]
@akuegel, can you elaborate on what you mean? These changes should not have affected anything but on the ROCm side. What are the next steps so I can get these commits back in?

**Comment by stevenireeves** [comment]
@akuegel Thanks for the update, can you let me know if it is rolled forward again?

**Comment by cheshire** [comment]
I've rolled back the rollback.

**Pull request merged**
