### PR TITLE
Add additional argument to freeze_graph

### PR DESCRIPTION
**Pull request by tedhtchang**
This PR fixes the failed testFreezeGraphV1 test for PR https://github.com/tensorflow/tensorflow/pull/14341

### CODE REVIEW

**Review by vrv — APPROVED** [review]
Seems straightforward and backwards compatible from a code point of view, but I'm not an owner of the freeze graph API.  Adding two people who should also double check that this is something they'd support.

**Comment by drpngx** [comment]
There is the write version and the read version. I think we want to support the read version but not the write version for the time being. If you update this, then you'd probably also want to write a test.

**Comment by rmlarsen** [comment]
@drpngx Do you have a specific suggestion for the author in order to make progress on this?

**Comment by drpngx** [comment]
Sure,
1. Write a test
2. Do not implement the write path. Only the read path.

**Comment by rmlarsen** [comment]
@drpngx OK, my reading comprehension is not very impressive, I suppose :-)

**Comment by drpngx** [comment]
Yeah probably that wasn't very clear. Thanks for asking!

**Comment by tedhtchang** [comment]
Hi @drpngx 
Could you help me understand "read version" and "read path"? My understanding of  write_version is from the [Saver constructor](https://github.com/tensorflow/tensorflow/blob/a1b155b6f51c539974e1bf73d0e0d15b388b9219/tensorflow/python/training/saver.py#L1171)

**Comment by drpngx** [comment]
@tedhtchang I'd like to make it hard for people to create `v1` checkpoints. It's OK to be able to load them, but I'd rather we didn't provide an option to write `v1` checkpoints since they are deprecated. Does that make sense?

**Comment by tedhtchang** [comment]
Hi @drpngx I don't think the change will alter the write path (i.e. let people create a v1 checkpoint). The new argument, [checkpoint_version](https://github.com/tedhtchang/tensorflow/blob/4b04b1b89d8571ee36c5cae43079f5dc9e5367b0/tensorflow/python/tools/freeze_graph.py#L254), I introduce is to explicitly tell the [saver.restore](https://github.com/tedhtchang/tensorflow/blob/4b04b1b89d8571ee36c5cae43079f5dc9e5367b0/tensorflow/python/tools/freeze_graph.py#L131) to read the input_checkpoint as v1 format.
The only write path I see is the [output_graph_def](https://github.com/tedhtchang/tensorflow/blob/4b04b1b89d8571ee36c5cae43079f5dc9e5367b0/tensorflow/python/tools/freeze_graph.py#L160) but that doesn't create checkpoint.

**Comment by rmlarsen** [comment]
@drpngx is this OK to merge, given @tedhtchang's explanation?

**Comment by drpngx** [comment]
Oh OK, got it. You're right. Good to go!

**Comment by rmlarsen** [comment]
@drpngx @tedhtchang Thanks!

**Comment by elgehelge** [comment]
Now `main` will raise a
`NameError: name 'checkpoint_version' is not defined`
on line [254](https://github.com/tensorflow/tensorflow/blob/73cf824a24e46766a1674c7879d8c48bd0728083/tensorflow/python/tools/freeze_graph.py#L254). Or am I doing something wrong?
@drpngx @tedhtchang

**Pull request merged**
