### PR TITLE
[iOS/tflite] Add ability to build a specific arch

### PR DESCRIPTION
**Pull request by powderluv**
Add a flag to build only the arch you want. By default build all.
Also check number of CPUs when invoking the make commands -j

TEST=tensorflow/contrib/lite/build_ios_universal_lib.sh -a arm64

### CODE REVIEW

**Comment by powderluv** [comment]
@petewarden can you please review. Thx

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 105 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by qlzh727** [comment]
Hi @powderluv, it seems that there is a merge conflict for one file on this PR. Can u resolve it? Thanks.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer%(reviewers): You have been added as a reviewer to this pull request. Please add your review or reassign. It has been  29ays with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 89 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 104 days with no activity and the `awaiting review` label has been applied.

**Review by petewarden — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by qlzh727** [comment]
@powderluv, please rebase the PR to resolve the merge conflict, so that I can run the test for this PR again.

**Comment by harshini-gadige** [comment]
@powderluv  Please address the test failures. Thanks !

**Comment by hgadig** [comment]
@powderluv  Can you please run clang-format on your code.

**Comment by hgadig** [comment]
@powderluv  Please look into the merging conflicts.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by powderluv** [comment]
The code base has changed much since my original patch for tflite. I will rebase in the next few weeks.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Review by shahzadlone — APPROVED** [review]

**Comment by daquexian** [comment]
@shahzadlone @qlzh727 @hgadig You stuff use one and a half year to approve a trivial PR, however, the author has to receive a spam email from your robot every 14 days. So great.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Comment by powderluv** [comment]
Good to close. I had to wait a year for the PR approval by which time the code base evolved. I will re-open a new PR in the future when I have time to revisit the issue.

**Pull request closed without merging**
