### PR TITLE
Branch 130964761

### PR DESCRIPTION
**Pull request by rmlarsen**

### CODE REVIEW

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
The one test that failed in Python 3 "sequence_queueing_state_saver_test" looks like a flaky test. Let's merge the PR and we will deal with the flakiness later.

**Comment by caisq** [comment]
Also ignore the mac status. PR Mac jobs have been disabled temporarily due to resource crunch. This CL is ready to be merged @rmlarsen

**Comment by caisq** [comment]
The mac test will be run after merge (in master jobs).

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@caisq  Thanks. I'll merge.

**Pull request merged**
