### PR TITLE
fix integer overflow in range

### LINKED ISSUE #64081: slient overflow occurs in tf.range leading to incorrect result, here is a possible fix
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### OS platform and distribution

_No response_

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current behavior?

Following the documentation https://www.tensorflow.org/api_docs/python/tf/range, tf.range should have consistent result with np.arange. 
However, given the following inputs, tf.range outputs `tf.Tensor([1136033460], shape=(1,), dtype=int32)`, which is **incorrect**
The correct result is np.arange's output `[1136033460 -713794229]`.

I did some analysis and find the root cause lies in here:
https://github.com/tensorflow/tensorflow/blob/06e37b8d7f2ba0338efd0f588f068122414f0722/tensorflow/core/kernels/sequence_ops.cc#L100

When computing the `limit - start`, the actual value overflows.
To solve this problem, we can change the original code to a new one by applying the division first
origin:
```
Eigen::numext::ceil(Eigen::numext::abs((limit - start) / delta));
```

new:
```
Eigen::numext::ceil(Eigen::numext::abs(limit / delta - start / delta);
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
start = 1136033460
end = -2110457150
step = -1849827689
out = tf.range(start, end, step)
print(out)
out_np = np.arange(start, end, step)
print(out_np)
```
```


### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mattbahr**
Fixes #64081 

I modified the fix from the rolled back PR #76252 to check that the value of the unsigned size does not exceed the max value of the `int64_t` data type before casting it back to the signed type.

### CODE REVIEW

**Comment by mattbahr** [comment]
@mihaimaruseac Would you be ok with reviewing this since you were on the review for the original pull request?

**Review by mihaimaruseac — APPROVED** [review]
Thank you!

**Comment by mattbahr** [comment]
My initial approach testing for the failure case from the python ops was failing so I moved that test case over to the kernel tests. Tests are passing for me now.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mattbahr** [comment]
@mihaimaruseac @gbaned Is there anything holding up this PR internally? It looks like the change was imported successfully, but the feedback check hasn't run

**Comment by mihaimaruseac** [comment]
It was blocked on an internal presubmit check, but it should get merged soon

**Comment by mihaimaruseac** [comment]
This will get rolled back again. It still fails further down the line:

```
Details
tensorflow/core/kernels/ragged_range_op.cc: runtime error: signed integer overflow: -713794229 + -1849827689 cannot be represented in type 'int'
    #0 0x55aa58fee7ba in tensorflow::RaggedRangeOp<int, long>::Compute(tensorflow::OpKernelContext*)
    #1 0x55aa6e363e5c in tensorflow::ThreadPoolDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) 
...
```

It's a test compiled with ASAN.

**Comment by mattbahr** [comment]
Wow, ok if I have time this week, I'll see if I can get the tests compiling with ASAN on my system. Thanks for the info! And thanks for the review!

**Pull request merged**
