### PR TITLE
Additional testcases for embedding_lookup ops

### PR DESCRIPTION
**Pull request by joyalbin**

### CODE REVIEW

**Comment by joyalbin** [comment]
@miaout17 Could you please kindly review this PR..

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by jdduke** [comment]
Is this still desired? Is it worth rebasing?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
