### PR TITLE
update TensorShape::CheckDimsAtLeast

### PR DESCRIPTION
**Pull request by 372046933**
The declaration of `CheckDimsAtLeast` states that 
> REQUIRES: dims() >= NDIMS

### CODE REVIEW

**Comment by allenlavoie** [comment]
I'm no longer working on TensorFlow; adding Rohan to triage.

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
This would then cause all the callers of this to call `std::abort` as the condition gets flipped

**Comment by 372046933** [comment]
Yes, flipping the condition would make all callers `abort`. However, it seems that  the tensorflow codebase does not call this function, nor did it have a test case about `CheckDimsAtLeast`. Flipping the condition makes the function semantically correct.

**Comment by mihaimaruseac** [comment]
There is at least [one caller](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/framework/tensor_shape.cc;l=50;bpv=1;bpt=1?q=CheckDimsAtLeast&ss=tensorflow%2Ftensorflow:tensorflow%2F) with [one occurence](https://cs.opensource.google/search?q=AsEigenDSizesWithPadding&sq=&ss=tensorflow%2Ftensorflow:tensorflow%2F)

**Comment by 372046933** [comment]
Sorry, I missed one caller `AsEigenDSizesWithPadding`. The other is the implementation of `CheckDimsAtLeast`
```c++
template <int NDIMS, typename IndexType>
Eigen::DSizes<IndexType, NDIMS> TensorShape::AsEigenDSizesWithPadding() const {
  CheckDimsAtLeast(NDIMS);
  return AsEigenDSizesCopyAndPad<NDIMS, IndexType>();
}
````
`AsEigenDSizesWithPadding` requires that `NDIMS` greater than or equal to the tensor's `dims()`. Maybe `CheckDimsAtLeast` could be renamed to `CheckDimsAtMost`, or  the original comments 
```c++
 // REQUIRES: dims() >= NDIMS
  void CheckDimsAtLeast(int NDIMS) const;
```
could be revised to
```c++
 // REQUIRES: dims() <= NDIMS
  void CheckDimsAtLeast(int NDIMS) const;
```
according to the current `CheckDimsAtLeast` implementation. 
Which do you think is better? IMHO, function name should reflect its purpose.

**Comment by mihaimaruseac** [comment]
Let's change the name. I looked internally and there are no other users besides the ones in OSS.

**Comment by 372046933** [comment]
Just renamed `CheckDimsAtLeast`  to `CheckDimsAtMost` and local build passes.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
