### PR TITLE
Configure script code reduction (no merge please)

### PR DESCRIPTION
**Pull request by hotchkiss87**
Please don't merge yet.

The configure script has a lot of repetition. Adding functions can reduce the number of lines of code, help prevent errors, and make life easier.

I noticed it was kind of long when editing another part.

This adds two functions: build_with and get_path
```bash
function build_with {
  # don't change value if it is already set
  if [[ "$(eval echo \"\$$1\")" ]] ; then
    return
  fi
  local needed="$1"
  local build_ask="$2"
  # default is 'enabled' or 'disabled'
  local default="$3"

  if [[ "$4" ]] ; then
    local build_ans_yes="$4"
    local build_ans_no="$5"
  else
    local build_ans_yes="$build_ask support will be enabled for TensorFlow."
    local build_ans_no="No $build_ans_yes"
    local build_ask="Do you wish to build TensorFlow with $build_ask support?"
  fi

  if [[ "$default" == "enabled" ]] ; then
    local build_ask="$build_ask [Y/n] "
  else
    local build_ask="$build_ask [y/N] "
  fi

  while true; do
    read -p "$build_ask" user_input

    case "$user_input" in
      [Yy]* ) echo "$build_ans_yes"
        eval $needed=1
        break;;
      [Nn]* ) echo "$build_ans_no"
        eval $needed=0
        break;;
      "" ) if [[ "$default" == "enabled" ]] ; then
          echo "$build_ans_yes"
          eval $needed=1
        else
          echo "$build_ans_no"
          eval $needed=0
        fi
        break;;
      * ) echo "Invalid selection: $user_input";;
    esac
  done
}
```

```bash
function get_path {
  if [[ "$(eval echo \"\$$1\")" ]] ; then
    return
  fi
  local sys_path="$1"
  local path_for="$2"
  # looking for a path for a bin or lib
  local type_of_path="$3"
  # optional search for bin, array of paths for lib
  local generic_path="$4"
  local default_path=""

  if [[ "$type_of_path" == "bin" ]] ; then
    local default_path="$(which $path_for || true)"
    if [[ !"$default_path" ]] && [[ "$generic_path" ]] ; then
      local default_path="$(which $generic_path || true)"
    fi
    local ask_for_path="Please specify the location of $path_for. [Default is $default_path]:"
  else
    echo "Possible library path(s): "
    for x in "${generic_path[@]}" ; do
      if [[ "$x" ]] && [[ ! "$default_path" ]] ; then
        local default_path="$x"
      fi
      echo "    $x"
    done
    local ask_for_path="Please input the desired $path_for library path to use. [Default is $default_path]:"
  fi

  while true; do
    read -p "$ask_for_path " $sys_path

    if [[ ! "$(eval echo \$$sys_path)" ]] ; then
      if [[ -e "$default_path" ]] ; then
        eval $sys_path="$default_path"
      elif [[ -e "$generic_path" ]] && [[ "$type_of_path" == "bin" ]] ; then
        eval $sys_path="$default_path"
      else
        echo "ERROR! I cannot find a default path and one was not specified." 1>&2
      fi
    fi

    if [[ -e "$(eval echo \$$sys_path)" ]] ; then
      if [[ "$type_of_path" == "bin" ]] && [[ ! -x "$(eval echo \$$sys_path)" ]] ; then
        echo "ERROR! \$$sys_path is not executable." 1>&2
      else
        break
      fi
    else
      echo "ERROR! $(eval echo \$$sys_path) does not seem to be a valid path to $path_for." 1>&2
    fi
  done
}
```

Those functions alone kill ~150 or so lines of code. I was going to do more reducing MKL, but I believe I rebased those changes away due to the discussion in  #11212

If possible, I'd like to run tests on this to see if there's any issue with cross compatibility. (I'm not sure what permissions are, and if I can run the tests myself?) I killed another 50 or so from the CUDA area, but I want to try it on a machine with CUDA before running it.

The selection below is just to see what versions you're supporting. TensorFlow is pretty new, and you're already using some more recent options in the script. I just wanted to test it to be sure.
```bash
declare -A array_test=( [one]="position_one" [two]="position_two" [three]="position_three" )
array_ans=""
positional_test=( one two three )
positional_ans="position_oneposition_twoposition_three"

for x in "${positional_test[@]}" ; do
  array_ans+="$(eval echo \${array_test[$x]})"
done

if [[ ! "$array_ans" == "$positional_ans" ]] ; then
  echo "dec arrays not supported"
  exit 1
fi
```

If that is successful, I can remove another 100 or so lines. It'll (probably) be more readable too, for instance you can just add something like:
```bash
declare -A GCP=( [tf_needs]="TF_NEED_GCP" [name]="Google Cloud Platform" [default]="disabled" \
                                [write_opts]="write_gcp" [enabled]=0 )
```
And have it iterate over fields instead of having an entire section of the script that has the same install process as TF_NEED_HDFS.

### CODE REVIEW

**Comment by gunan** [comment]
This script is planned to be moved to python
@yifeif How close are we to that?

**Comment by hotchkiss87** [comment]
That makes a lot of sense.

If the Python script isn't far away, or even if the script is and this stuff will make it harder for you in the future, definitely close it. I did this because my build failed (locate not on system), and I just edited a few other things while I was looking at the file, and uploaded my changes. I figured I'd check to see if I should continue to do more on this file, or just leave it. If it's helpful, I can also fix it up a bit without spending too much time on additional things, but if not, feel free to kill it.

**Comment by caisq** [comment]
@yifeif, any thoughts? Should we review this PR or close it in favor of the upcoming Python version of it?

**Comment by yifeif** [comment]
Thanks for the PR @hotchkiss87. Sorry I haven't gotten around to do the python conversion yet. If I still don't get to this next week, I'll review your PR.

**Comment by hotchkiss87** [comment]
@yifeif I thought about it a bit, and it's probably a better use of our time if we worked on the python replacement instead. I have some work done (for other install scripts) via python, but it would unfortunately take a lot of work (a lot more work than a couple of quick changes to the current configure script) to implement for tesseract. The current configure scripts support a version of python that's much older than the scripts I run do.

If you're interested, I'd share any work done, but for me the most important part is what the earliest version of python you're targeting is.

### What I feel uncomfortable committing to
My 'knee-jerk' reaction is typically just to do it all myself, but I have work, family, and some work for some local non-profits that I've already committed to for the next month, and that are depending on me to deliver. I hate being bored and commit to enough work so that there's no chance that this will happen, but I am quite committed to delivering for the non-profits (and the people that they serve) for the next month or so.

I also hate inefficiency, and two people repeating the same work is painfully inefficient.

### Thanks for your work!
Thanks for the project! I ended up going with my own SVM classifier for a project, but I'm sure I'll utilize this in the future.

(oh no way I just checked git log and you work for Google? IDK if you'll want/need the partial python script(s) I have then... wow! tbh if you're really planning on just rewriting everything yourself, I can send you what I have. Worst case it's all useful and you... rewrite everything like you already planned to do, but hopefully you'll find something useful! I mostly just use a set of functions I've perfected over the years to handle this stuff for me. I'm younger than some of the old guys I have worked with, who did UNIX sysadmin work and the like in the 70s/80s, so I take a more modern approach, but some of the work I have may be useful! I'm more than happy to GPL/Apache it to you too. Should I email it in git or? I'd feel bad about posting non-mergeworthy code to github, but if you want a partial script, I can deliver.)

**Pull request closed without merging**
