### PR TITLE
Add missing link to the eager guide.

### PR DESCRIPTION
**Pull request by MarkDaoust**

### CODE REVIEW

**Review by ewilderj — APPROVED** [review]
lgtm

**Comment by ewilderj** [comment]
just noticed... s/tensorflow/TensorFlow

**Comment by meteorcloudy** [comment]
Please pull and rebase to fix build failure on Windows Bazel

**Comment by MarkDaoust** [comment]
Hi meteorcloudy@.

I'm not sure what is causing that "Windows Bazel" build to fail. But as far as I can tell this patch is based on the current tip of r1.7: 

```
git log --oneline --graph --decorate
```

```
* 8a2c8409c7 (HEAD -> MarkDaoust-patch-1, upstream/MarkDaoust-patch-1) Capitalization.
* cf65769bef Add missing link to the eager guide.
*   99322a92bf (upstream/r1.7, r1.7) Merge pull request #18137 from annarev/update_release_notes
|\  
| * 57de6ef5b1 Also adding a note about Cuda supported version
```
99322a92 is the current top commit of the r1.7 branch. 

The test logs seem to say that [bazel is not installed](https://source.cloud.google.com/results/invocations/98ea2497-d390-42af-a3a7-6dac17d82843/targets/%2F%2Ftensorflow%2Ftools%2Fci_build%2Fbuilds:gen_win_out/log).

**Comment by meteorcloudy** [comment]
The Bazel Presubmit is set up recently. It needs some fixes that's not
included in r1.7. I believe rebase from HEAD should fix the "Bazel is not
installed", because the build _tf_windowd.sh should set the correct PATH
value.

**Pull request merged**
