### PR TITLE
[tf.data] graduate experimental `take_while` API to tf.data.Dataset

### PR DESCRIPTION
**Pull request by kvignesh1420**
This PR graduates the `tf.data.experimental.take_while` API into `tf.data.Dataset.take_while` by making the following changes:

- [x] Adds the deprecation decorator for the experimental API.
- [x] Add the `take_while()` method to `DatasetV2` class.
- [x] Updates example in documentation with new API.
- [x] Regenerate golden API's.
- [x] Moved and updated the `take_while_test` target from experimental/kernel_tests to kernel_tests
- [x] Updated the RELEASE.md file

TEST LOG
```
INFO: Build completed successfully, 355 total actions
//tensorflow/python/data/kernel_tests:take_while_test                    PASSED in 3.9s
  Stats over 4 runs: max = 3.9s, min = 3.7s, avg = 3.8s, dev = 0.1s

```

cc: @jsimsa @aaudiber

### CODE REVIEW

**Review by aaudiber — APPROVED** [review]

**Comment by kvignesh1420** [comment]
@aaudiber any update on this?

**Comment by aaudiber** [comment]
@kvignesh1420 still working on getting it merged, should hopefully be in soon

**Comment by kvignesh1420** [comment]
sure, thanks!

**Comment by kvignesh1420** [comment]
cc: @gbaned @aaudiber the conflicts have been resolved.

**Comment by kvignesh1420** [comment]
closing the PR as the internal commit has been made.

**Pull request closed without merging**
