### PR TITLE
Preformance optimized Negate Ops

### PR DESCRIPTION
**Pull request by joyalbin**

### CODE REVIEW

**Review by karimnosseir — CHANGES_REQUESTED** [review]
Is there any measurable difference in performance ? Can you benchmark this change please.

Thanks

**Comment by joyalbin** [comment]
@karimnosseir I have seen generally this method will have performance benefits.
The `neg_test` testcase bench-marking values are fluctuating.
Still wrote a small program to prove this change will have benefits, results are:

> Split loop time in ms: 0.000208
> input:1234567892
> output:-1-2-3-4-5-6-7-8-9-2
> 
> non Split loop time in ms: 0.000365
> input:1234567892
> output:-1-2-3-4-5-6-7-8-9-2

Test code: [loop_split.zip](https://github.com/tensorflow/tensorflow/files/3006826/loop_split.zip)

**Comment by joyalbin** [comment]
@karimnosseir Could you please further review this PR?

**Comment by karimnosseir** [comment]
Sorry for late reply as i was  out of office.
To get a better understanding on the benefit please use the benchmark tool to get performance numbers
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark

Thanks

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
