### PR TITLE
add uint8 gpu kernel

### PR DESCRIPTION
**Pull request by fsx950223**
align with cpu kernel

### CODE REVIEW

**Comment by gbaned** [comment]
@rohan100jain Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rohan100jain Can you please review this PR ? Thank you!

**Review by cantonios — CHANGES_REQUESTED** [review]
Can you also enable tests in `tensorflow/python/kernel_tests/array_ops/one_hot_op_test.py` for `uint8`?

**Comment by gbaned** [comment]
Hi @fsx950223 Can you please check @cantonios's comments and resolve conflicts?. Thank you!

**Comment by gbaned** [comment]
Hi @fsx950223 Any update on this PR? Please. Thank you!

**Pull request closed without merging**
