### PR TITLE
Fix deprecation warnings in beam search decoder

### PR DESCRIPTION
**Pull request by georgesterpu**
This one is for the master branch

### CODE REVIEW

**Comment by rthadur** [comment]
Please send this PR to [tensorflow/addons](https://github.com/tensorflow/addons) instead; contrib is deprecated and stated to be removed so we're not making new changes to it.

**Comment by georgesterpu** [comment]
tf/contrib/seq2seq still looks active to me
https://github.com/tensorflow/tensorflow/commit/87d558f2a993f595ffe9b0c58b4a5672be26954c

There is an open PR to migrate seq2seq to addons, so I cannot send my PR there yet
https://github.com/tensorflow/addons/pull/72

**Comment by ebrevdo** [comment]
Let's fix this one too for tf1.14.

**Comment by rthadur** [comment]
@georgesterpu can you please resolve conflicts

**Comment by georgesterpu** [comment]
This PR has been made redundant in the meantime after https://github.com/tensorflow/tensorflow/commit/df3a3375941b9e920667acfe72fb4c33a8f45503, will close it. Apologies.

**Comment by georgesterpu** [comment]
But wait, there is one left :shipit: 
this [math_ops.div](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py#L1264) ---> math_ops.divide

**Pull request closed without merging**
