### PR TITLE
lite: enable (u)int8 quantization and int32 for ABS

### PR DESCRIPTION
**Pull request by zhenhuaw-me**
Remake of PR #31914 (the branch is recreated, leading to impossible to reopen). The change in this PR removes the *key reordering* of the last patch, nothing bit change.

Please have look into this @wangtz @jianlijianli @suharshs .

### CODE REVIEW

**Comment by jackwish** [comment]
@liyunlu0618 Would you like to take a look at this?

**Comment by ravikyram** [comment]
@jackwish 

Can you please resolve conflicts? Thanks!

**Comment by jackwish** [comment]
> @jackwish
> Can you please resolve conflicts? Thanks!

Resolved. Would you mind to push this PR to be merged? I have been getting tired of the conflict resolving process.

**Review by suharshs — APPROVED** [review]

**Comment by jackwish** [comment]
Would you mind to push the *internal safe review approval* a bit? I am afraid that conflicts may come as operators are changing frequently, which takes time from us all...

**Comment by suharshs** [comment]
Hmm, strange I have approved, but am not seeing the internal review request.

**Review by suharshs — APPROVED** [review]

**Comment by suharshs** [comment]
Trying re-approving

**Comment by jackwish** [comment]
Thanks for your kind effort @suharshs

**Comment by jackwish** [comment]
I have checked the failed list of ***Ubuntu CPU — Internal CI build failed***, seems not related to this patch set.

**Comment by ravikyram** [comment]
@jackwish Could you please check other failed build errors? Thanks!

**Comment by jackwish** [comment]
> @jackwish Could you please check other failed build errors? Thanks!

Tried locally, no failures found. Would you please re-trigger the test or build?

PS. We don't know how the patch is tested? Is it a *checkout and test* or *cherry pick and test*?

**Comment by rthadur** [comment]
@jackwish  can you please check below error : 
`ERROR: /tmpfs/src/github/tensorflow/tensorflow/lite/kernels/BUILD:414:1: Couldn't build file tensorflow/lite/kernels/_objs/builtin_op_kernels/abs.pic.o: C++ compilation of rule '//tensorflow/lite/kernels:builtin_op_kernels' failed (Exit 1)
[8,502 / 11,019] Compiling tensorflow/lite/kernels/reduce.cc; 17s remote ... (200 actions, 199 running)
[9,964 / 11,023] Compiling tensorflow/lite/toco/tflite/operator.cc; 27s remote ... (193 actions, 186 running)
[13,224 / 14,698] Compiling tensorflow/compiler/mlir/lite/flatbuffer_translate.cc; 24s remote ... (198 actions, 197 running)
tensorflow/lite/kernels/abs.cc:18:10: fatal error: tensorflow/lite/c/c_api_internal.h: No such file or directory
 #include "tensorflow/lite/c/c_api_internal.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

link for more detailed logs : https://source.cloud.google.com/results/invocations/f20488f8-b408-4b40-a556-246e08af48c4/log

**Comment by jackwish** [comment]
Too long merging progress.

**Pull request closed without merging**
