### PR TITLE
Make TensorFlow Lite library for Android target

### PR DESCRIPTION
**Pull request by yesmung**
You can compile Tensorflow Lite library using Makefile.
It is possible to compile both static and shared library
including benchmark tools.

For more details, see TensorFlow Lite Makefile section
of the README.md file.

Signed-off-by: MyungSung Kwak <yesmung@gmail.com>

### CODE REVIEW

**Comment by yesmung** [comment]
@martinwicke 
Hello, I have a question.
How long does it take verify check list approximately? There seems to be no progress.
Please reply if you can.

**Comment by martinwicke** [comment]
We're waiting for a review from @petewarden. He will get to it as soon as he can.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by yesmung** [comment]
Is there any update?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 15 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 30 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 45 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 60 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 75 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 92 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 108 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 124 days with no activity and the `awaiting review` label has been applied.

**Comment by martinwicke** [comment]
@petewarden any update?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

**Comment by achowdhery** [comment]
@yesmung have you tried the latest Android target of TensorFlow Lite? This issue is already resolved at head. Thanks

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @jdduke: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @jdduke: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by jdduke** [comment]
So, the primary reason for the Makefile's existence is to allow compilation on platforms that aren't natively (or well) supported by bazel.  As Android is wells-supported by bazel, is there any reason you cannot use that path? We're hoping to avoid yet another parallel build system.

**Comment by jdduke** [comment]
Closing as we have no plans to support Makefile builds for Android.

**Pull request closed without merging**
