### PR TITLE
Registering all real number types for resize operations.

### PR DESCRIPTION
**Pull request by panmari**
Simplifies code and only adds int16 and int64 as additional compatible
types, which might come in handy at some point.

### CODE REVIEW

**Comment by vrv** [comment]
Thanks @panmari!

There are a few changes that will be necessary to get this to work.

1) https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/image_ops.cc#L25  All of the ops that you added are currently only defined for those set of types.  So this file needs to be updated to additionally include the ones you are adding kernel registrations for.  My suggestion would be to change the attribute of T to be "realnumbertype".

2) After doing that, we should also write some tests to make sure these additional kernels are actually invoked properly.  Unfortunately, our current ops/image_ops_test.py does not really test many of the kernels.  Would you be willing to add the tests for these kernels?

The way to do this would be to change https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_test.py#L576 to iterate various numpy dtypes for each of the kernels that we support.  We convert numpy dtypes to the appropriate tensorflow datatype, and this should be sufficient to test each of the kernels.

If this doesn't make sense, or you'd rather us take a look at it, let us know, since this is a change we really should make.

**Comment by vrv** [comment]
Is it possible add at least add a test for one of these new types, to make sure it works?  Again, we can take this over if that's too much work for you.

**Comment by panmari** [comment]
No problem, I'm right now writing some tests. But I'm running in the same issues as mentioned in #472. Most python tests just fail with the following message:

```
+ /home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/gen_docs_test.runfiles/tensorflow/python/gen_docs_combined --out_dir /home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/tensorflow/_tmp/gen_docs_test_2
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "/home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/gen_docs_test.runfiles/tensorflow/python/framework/gen_docs_combined.py", line 23, in <module>
    import tensorflow.python.platform
  File "/home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/gen_docs_test.runfiles/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/gen_docs_test.runfiles/tensorflow/python/__init__.py", line 50, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/gen_docs_test.runfiles/tensorflow/python/framework/framework_lib.py", line 62, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/gen_docs_test.runfiles/tensorflow/python/framework/ops.py", line 40, in <module>
    from tensorflow.python.framework import versions
  File "/home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/gen_docs_test.runfiles/tensorflow/python/framework/versions.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/gen_docs_test.runfiles/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/gen_docs_test.runfiles/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: numpy.core.multiarray failed to import
```

**Comment by vrv** [comment]
There's probably some other installation of numpy that is interfering -- try searching for other installations, and if they are not needed, try removing them.  IIRC, this is saying that tensorflow was compiled with 1.10.1 (likely) but the runtime is loading 1.9.  Or maybe change the paths so that 1.10 is preferentially chosen over 1.9?  I'm not an expert here :(

**Comment by panmari** [comment]
Luckily, the tests relevant for this PR worked for me. I extended some of them to test through all supported types. This required to change some test cases since 128 can not be represented as int8. Is there a way to make a custom error message for `assertAllClose`? It would be nice to know in these test for which resize algorithm/type they failed.

**Comment by vrv** [comment]
Hmm, not that I know of.  We want to add 'parameterized test' support to the python unit tests to make this easy.  Alternatively, you could make the base class a test harness that takes in one type, and then instantiate one class for each type being tested, so that the name of the class tells you which type failed.

That being said, it's probably fine for now to leave it as is, since we do this type of test in a bunch of other files.  Thanks for making these changes!

I'll take a closer look tomorrow.

**Comment by panmari** [comment]
Yeah, parametrized tests would be a perfect fit here. Thanks for all your guidance.

**Comment by vrv** [comment]
test this please

**Comment by vrv** [comment]
@jendap, tests didn't kick off :(

(Running manually)

**Comment by panmari** [comment]
@vrv this was directed at a bot, not me?

**Comment by vrv** [comment]
Yes, it was directed at the bot.  We need to change our regex to somehow make that more clear.

**Pull request merged**
