### PR TITLE
Made rounding in convert_image_dtype for numbers close to zero

### LINKED ISSUE #48701: Function used in many augmentations (convert_image_dtype) has an issue
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab default
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Colab default
- TensorFlow version (use command below): v2.4.1-0-g85c8b2a817f 2.4.1
- Python version: 3
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the current behavior**
There is a function convert_image_dtype that used in many augmentation ops like tf.image.stateless_random_brightness and etc.
That function has a rounding issue here https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/ops/image_ops_impl.py#L2290
Maybe other cases also have this bug (not checked).

When we casting float to int, we should use rounding. In convert_image_dtype rounding implemented as shift by 0.5 which is correct for max value, but is not correct for 0.
See example by link below.

**Describe the expected behavior**
Every time convert_image_dtype changes value scale following casting to int, it should use rounding before casting.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1xZqyuAlZu_xkDZZHNsr7K8g6MyapcNPi?usp=sharing

### PR DESCRIPTION
**Pull request by pointhex**
Fixes #48701

### CODE REVIEW

**Comment by pointhex** [comment]
@googlebot I fixed it.

**Comment by pointhex** [comment]
@googlebot I fixed it.

**Review by kkimdev — APPROVED** [review]

**Comment by rthadur** [comment]
@pointhex can you please check build failures ?

**Comment by pointhex** [comment]
> @pointhex can you please check build failures ?

Hi, I will try to do it by the end of the next week. I have and will have a bit busy week. is it ok?

**Review by kkimdev — APPROVED** [review]

**Review by kkimdev — APPROVED** [review]

**Comment by pointhex** [comment]
Hi @kkimdev,
I see that tests, that I've broked, are fixed now. 
But for Linux GPU link is broken for me.
About Windows Bazel GPU, looks like some infrastructure error.
Could you check plz or tell me what I should do with that?

**Comment by gbaned** [comment]
Here are the internal errors, @pointhex can you please verify ? Thanks!

Traceback (most recent call last):
  File "/tensorflow/python/ops/image_ops_test.py", line 4648, in testConvertBetweenFloat32AndInt8SmallNumbers
    self.assertEqual(x0.numpy(), 0)
  File "/tensorflow/python/framework/ops.py", line 402, in __getattr__
    self.__getattribute__(name)
AttributeError: 'Tensor' object has no attribute 'numpy'

**Comment by pointhex** [comment]
> Here are the internal errors, @pointhex can you please verify ? Thanks!
> 
> Traceback (most recent call last):
> File "/tensorflow/python/ops/image_ops_test.py", line 4648, in testConvertBetweenFloat32AndInt8SmallNumbers
> self.assertEqual(x0.numpy(), 0)
> File "/tensorflow/python/framework/ops.py", line 402, in **getattr**
> self.**getattribute**(name)
> AttributeError: 'Tensor' object has no attribute 'numpy'

Hi @gbaned,
I did it another way. Hope it will help.

**Review by kkimdev — APPROVED** [review]

**Comment by gbaned** [comment]
Here are the internal errors, @pointhex can you please verify ? also can you please address  pylint errors ? Thanks!

Traceback (most recent call last):
  File "/tensorflow/python/ops/image_ops_test.py", line 918, in testHalfSaturation
    self.assertAllEqual(y_tf, y_np)
  File "/tensorflow/python/framework/test_util.py", line 1275, in decorated
    return f(*args, **kwds)
  File "/tensorflow/python/framework/test_util.py", line 2976, in assertAllEqual
    np.testing.assert_array_equal(a, b, err_msg="\n".join(msgs))
  File "/py/numpy/testing/_private/utils.py", line 931, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/py/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

not equal where = (array([0, 1]), array([1, 0]), array([1, 0]))
not equal lhs = array([180, 136], dtype=uint8)
not equal rhs = array([181, 135], dtype=uint8)
Mismatched elements: 2 / 12 (16.7%)
Max absolute difference: 255
Max relative difference: 1.40883978
 x: array([[[  7,   9,  13],
        [140, 180, 226]],
...
 y: array([[[  7,   9,  13],
        [140, 181, 226]],
...

**Comment by pointhex** [comment]
> Here are the internal errors, @pointhex can you please verify ? also can you please address pylint errors ? Thanks!
> 
> Traceback (most recent call last):
> File "/tensorflow/python/ops/image_ops_test.py", line 918, in testHalfSaturation
> self.assertAllEqual(y_tf, y_np)
> File "/tensorflow/python/framework/test_util.py", line 1275, in decorated
> return f(*args, **kwds)
> File "/tensorflow/python/framework/test_util.py", line 2976, in assertAllEqual
> np.testing.assert_array_equal(a, b, err_msg="\n".join(msgs))
> File "/py/numpy/testing/_private/utils.py", line 931, in assert_array_equal
> verbose=verbose, header='Arrays are not equal')
> File "/py/numpy/testing/_private/utils.py", line 840, in assert_array_compare
> raise AssertionError(msg)
> AssertionError:
> Arrays are not equal
> 
> not equal where = (array([0, 1]), array([1, 0]), array([1, 0]))
> not equal lhs = array([180, 136], dtype=uint8)
> not equal rhs = array([181, 135], dtype=uint8)
> Mismatched elements: 2 / 12 (16.7%)
> Max absolute difference: 255
> Max relative difference: 1.40883978
> x: array([[[ 7, 9, 13],
> [140, 180, 226]],
> ...
> y: array([[[ 7, 9, 13],
> [140, 181, 226]],
> ...

The main problem is that I changed that for CPU from 180 to 181 but for some reason on GPU it computes as 180. @gbaned Could you tell me if you have some ideas on how I can fix that?

**Comment by gbaned** [comment]
@kkimdev Can you please assist on above comments from @pointhex. Thanks!

**Comment by kkimdev** [comment]
I guess the test was affected by your `convert_image_dtype` change, could you try printing intermediate values in your changes using `tf.print` and compare CPU and GPU?

**Comment by pointhex** [comment]
> I guess the test was affected by your `convert_image_dtype` change, could you try printing intermediate values in your changes using `tf.print` and compare CPU and GPU?

I'm sure that it because of my change:) I will try to do it by print. But still, it strange a bit. Maybe, floating-point arithmetic shows some differences.

**Comment by gbaned** [comment]
@pointhex  Any update on this PR? Please. Thanks!

**Comment by pointhex** [comment]
> @pointhex Any update on this PR? Please. Thanks!

Unfortunately, I don't have. I tried to set up a build on my machine for GPU. But it still doesn't work. I will be on vacation for 2 weeks. So this time I will not have time for work on this commit( So if it hot and can't wait for me. So someone can finish it.
I still think that it is some CPU and GPU computing problem.

**Comment by gbaned** [comment]
@kkimdev Can you please assist on above comments from @pointhex. Thanks!

**Comment by pointhex** [comment]
> @kkimdev Can you please assist on above comments from @pointhex. Thanks!

I'm working on the problem. I managed to install cuda, but getting some errors during builds. Hope it will be solved. And I will check on my machine.

**Comment by pointhex** [comment]
Check with cuda. 
used two commands:
bazel test --config=cuda --repo_env=CC=clang-12  //tensorflow/python:image_ops_test
bazel test --repo_env=CC=clang-12  //tensorflow/python:image_ops_test
and now tests passes. 
Is it right way?

**Comment by pointhex** [comment]
Hi @kkimdev 
I see that some builds are broken again, it looks like an infrastructure problem.
Could you please restart or check it?
Thank you!

**Review by kkimdev — APPROVED** [review]

**Pull request merged**
