### PR TITLE
New features: tf.alphas and tf.alphas_like - Related to #16128

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
This PR is related to the issue: #16128

### A few interrogations before merging

1. Are the names I have chosen fine with everyone or you would like it to be changed to something else ?
2. Do my implementations seem fine ?
3. What kind of tests should I implement ? Where shall I put them ?
4. Is it a good idea to replace the function body of tf.ones/tf.zeros and tf.ones_like/tf.zeros_like by a function call to tf.alphas and tf.alphas_like ? Not doing it would lead to code duplication, however I would understand that you might be reluctant, these functions are at the core of the library.

### Why I created these functions ?

I oftenly need to create similar tensors with a non-zero/one value. A simple example would be cost functions in GANs with *label smoothing* applied. 

As stated by @facaiy in #16128, I could use : 
```python
b1 = tf.ones_like(a, dtype=tf.float32) * 0.9 # Tensor full of 0.9
b2 = tf.ones_like(a, dtype=tf.int32) * 2 # Tensor full of 2
b4 = tf.ones_like(a, dtype=tf.bool) # Tensor full of True
```
 However, as shown in my later comments in the issue, the method implemented in this PR is almost twice as fast.

In a wider view, I think that using a single function more *generic* is always a good thing whenever it is possible.

### How does the function API work ?

In a very similar manner than the existing ones: 

```python
import tensorflow as tf

a = tf.constant([
    [
        [4, 5, 6],
        [1, 2, 3]
    ],
    [
        [4, 5, 6],
        [1, 2, 3]
    ]
])

b1 = tf.alphas_like(a, 0.5431)
b2 = tf.alphas_like(a, 5)
b3 = tf.alphas_like(a, -5)
b4 = tf.alphas_like(a, True)

with tf.Session() as sess:
    _b1, _b2, _b3, _b4 = sess.run([b1, b2, b3, b4])
    
print("b1:", _b1)
print("b2:", _b2)
print("b3:", _b3)
print("b4:", _b4)

############### OUTPUTS ###############

>>> b1: [
  [
    [ 0.5431  0.5431  0.5431]
    [ 0.5431  0.5431  0.5431]
  ]
  [
    [ 0.5431  0.5431  0.5431]
    [ 0.5431  0.5431  0.5431]
  ]
]

>>> b2: [
  [
    [5 5 5]
    [5 5 5]
  ]
  [
    [5 5 5]
    [5 5 5]
  ]
]

>>> b3: [
  [
    [-5 -5 -5]
    [-5 -5 -5]
  ]
  [
    [-5 -5 -5]
    [-5 -5 -5]
  ]
]

>>> b4: [
  [
    [ True  True  True]
    [ True  True  True]
  ]
  [
    [ True  True  True]
    [ True  True  True]
  ]
]
```

---------------------------

I'm of course free for discussion over video-calls. It's the first time I try to make a change at the core of TF, and I'm quite afraid of breaking everything ;) Thanks for your help btw.

All the best,

Jonathan DEKHTIAR

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
Hi everyone, 

I have added a few corrections to this PR, I am implementing unittests in order to be sure that everything is executing fine.

### Compiled Library for test:

I have compiled the library for test only: https://drive.google.com/file/d/1THGNtLwptiv6T1zciZoSp_PAQtHrsk6Q/view?usp=sharing

* **OS**: Ubuntu 16.04
* **GPU Support**: No
* **Python**: Python 3.5
* **Architecture:** x86_64

### The PR can be tested with the following script:

```python
import tensorflow as tf
import numpy as np

ops_array = list()

target_np_array = np.ones([2,3])

for dtype in [np.int32, np.float32, np.bool, np.uint8]:
    for target_value in [0, 1, 0.7, -5.2]:
        
        op_val = np.array(target_value).astype(dtype)
        
        tmp_ops = tf.alphas_like(target_np_array, op_val)
        ops_array.append(tmp_ops)


with tf.Session() as sess:
    result_array = sess.run(ops_array)

for _, result in enumerate(result_array):
    if _:
        print("################")
    print(result)
```

### Outputs:

```shell
[[0 0 0]
 [0 0 0]]
################
[[1 1 1]
 [1 1 1]]
################
[[0 0 0]
 [0 0 0]]
################
[[-5 -5 -5]
 [-5 -5 -5]]
################
[[0. 0. 0.]
 [0. 0. 0.]]
################
[[1. 1. 1.]
 [1. 1. 1.]]
################
[[0.7 0.7 0.7]
 [0.7 0.7 0.7]]
################
[[-5.2 -5.2 -5.2]
 [-5.2 -5.2 -5.2]]
################
[[False False False]
 [False False False]]
################
[[ True  True  True]
 [ True  True  True]]
################
[[ True  True  True]
 [ True  True  True]]
################
[[ True  True  True]
 [ True  True  True]]
################
[[0 0 0]
 [0 0 0]]
################
[[1 1 1]
 [1 1 1]]
################
[[0 0 0]
 [0 0 0]]
################
[[251 251 251]
 [251 251 251]]
```

**Comment by DEKHTIARJonathan** [comment]
Hi everyone, 

I have added a few corrections to this PR, I am implementing unittests in order to be sure that everything is executing fine.

### Compiled Library for test (in whl format):

I have compiled the library for test only: https://drive.google.com/open?id=1qHtPZpOzgJGvuWnaOPSIU1caLIpoEA8m

* **OS**: Ubuntu 16.04
* **GPU Support**: No
* **Python**: Python 3.5
* **Architecture:** x86_64
* **Size:** 55MB

### The PR can be tested with the following script:

```python
import tensorflow as tf
import numpy as np

ops_array = list()

target_np_array = np.ones([2,3])

for dtype in [np.int32, np.float32, np.bool, np.uint8]:
    for target_value in [0, 1, 0.7, -5.2]:
        
        op_val = np.array(target_value).astype(dtype)
        
        tmp_ops = tf.alphas_like(target_np_array, op_val)
        ops_array.append(tmp_ops)


with tf.Session() as sess:
    result_array = sess.run(ops_array)

for _, result in enumerate(result_array):
    if _:
        print("################")
    print(result)
```

### Outputs:

```shell
[[0 0 0]
 [0 0 0]]
################
[[1 1 1]
 [1 1 1]]
################
[[0 0 0]
 [0 0 0]]
################
[[-5 -5 -5]
 [-5 -5 -5]]
################
[[0. 0. 0.]
 [0. 0. 0.]]
################
[[1. 1. 1.]
 [1. 1. 1.]]
################
[[0.7 0.7 0.7]
 [0.7 0.7 0.7]]
################
[[-5.2 -5.2 -5.2]
 [-5.2 -5.2 -5.2]]
################
[[False False False]
 [False False False]]
################
[[ True  True  True]
 [ True  True  True]]
################
[[ True  True  True]
 [ True  True  True]]
################
[[ True  True  True]
 [ True  True  True]]
################
[[0 0 0]
 [0 0 0]]
################
[[1 1 1]
 [1 1 1]]
################
[[0 0 0]
 [0 0 0]]
################
[[251 251 251]
 [251 251 251]]
```

**Comment by rmlarsen** [comment]
@DEKHTIARJonathan  I'm not sure it is necessary to add this API. Constant folding optimizations in TensorFlow will replace expressions 5 * ones_like(x) with a the same constant that alpha_as(x, 5) would have produced, if the shape of x can be deduced.

Maybe API reviewers can comment?

**Comment by rmlarsen** [comment]
@DEKHTIARJonathan Your proposed alphas API is essentially the same as tf.constant: https://www.tensorflow.org/versions/master/api_docs/python/tf/constant

**Comment by josh11b** [comment]
https://www.tensorflow.org/api_docs/python/tf/fill ?

**Comment by rmlarsen** [comment]
@josh11b Indeed, even closer.

**Pull request closed without merging**
