### PR TITLE
Added assertion error in reset_default_graph()

### PR DESCRIPTION
**Pull request by chaserileyroberts**
See #11121

### CODE REVIEW

**Comment by drpngx** [comment]
That might trigger an API change.

Jenkins, test this please.

**Comment by Thenerdstation** [comment]
Tests should pass now unless I did something very wrong on my end.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by drpngx — APPROVED** [review]

**Comment by caisq** [comment]
@Thenerdstation @drpngx  FYI, it seems that the PR is causing a test failure. The failure seems to be specific to Mac , for reasons I don't fully understand. See example log from Jenkins nightly Mac build:
http://ci.tensorflow.org/view/Tensorflow%20Jenkins%20Monitored%20builds/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=NO_PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=mac-slave/537/consoleFull

If you have thoughts, please let me know.

**Comment by drpngx** [comment]
That is very odd. It passed when I merged.

The `exporter_test` looks like a genuine error, except that it's Mac only, and the `session_test` points to some other part of the code where `self.stack` is used. The `generate_lib_test` is probably some other error :(

Checking the submit logs, it looks like `exporter_test` did not exist on Mac at the time, but `session_test` passed. `session_test` has been there for a while and it's not clear what changed.

Given the risk that the extra strict check would blow up when merging into google code, we might want to revert this CL and push it from the inside with more internal test coverage.

**Comment by Thenerdstation** [comment]
Yeah, I don't own a mac so I wasn't able to test for that, sorry.

**Pull request merged**
