### PR TITLE
Add calls to `reserve()` before populating vectors

### PR DESCRIPTION
**Pull request by SamuelMarks**
…and am at capacity

PS: WiP. Will finish going through you codebase adding capacity hints to all vectors with obvious opportunity for this optimisation.

### CODE REVIEW

**Comment by SamuelMarks** [comment]
Following the huge amount of interest from @sanjoy @kkimdev @sherhut @qqfish and @joker-eph—over the past 5 weeks—I merged in the latest master and reserved vector allocation to another 82 files in the TensorFlow codebase.

**Comment by joker-eph** [comment]
Nice! I had missed this pull-request originally.

It is likely that I read the title as some spam somehow though, can you title this explicitly: ```Add calls to `reserve()` before populating vectors``` or something like that.

**Comment by SamuelMarks** [comment]
> 123 CAN HAZ REZERVATIONS

Sure things @joker-eph ; and whilst I was at it I finished the cc files in the compiler dir

**Review by joker-eph — APPROVED** [review]

**Comment by gbaned** [comment]
@SamuelMarks Can you please fix build failures ? Thanks!

**Comment by SamuelMarks** [comment]
@gbaned Ahhh it wasn't erring on my end, ok going through the CI logs now

**Review by mihaimaruseac — APPROVED** [review]

**Review by bhack — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by joker-eph** [comment]
```
tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc: In function 'tensorflow::Status tensorflow::tensorrt::convert::ConvertAddN(tensorflow::tensorrt::convert::OpConverterParams*)':
tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:6570:31: error: no matching function for call to 'std::vector<tensorflow::tensorrt::ITensorProxyPtr>::reserve(const std::vector<tensorflow::tensorrt::convert::TRT_TensorOrWeights>&)'
   tensor_inputs.reserve(inputs);
                               ^
.....
  no known conversion for argument 1 from 'const std::vector<tensorflow::tensorrt::convert::TRT_TensorOrWeights>' to 'std::vector<tensorflow::tensorrt::ITensorProxyPtr>::size_type {aka long unsigned int}'
```

**Comment by joker-eph** [comment]
```
tensorflow/compiler/xla/tests/array_elementwise_ops_test.cc: In member function 'virtual void xla::{anonymous}::ArrayElementwiseOpTest_Atan2F32s_Test::TestBody()':
tensorflow/compiler/xla/tests/array_elementwise_ops_test.cc:2361:9: error: 'ys' does not name a type
   const ys = {+0.0f, -0.0f, inf, -inf, 5.0f, -3.0f, 2.0f, -8.0f, 1.0f};
         ^~
```

**Review by joker-eph — APPROVED** [review]

**Comment by gbaned** [comment]
@SamuelMarks Can you please resolve conflicts? Thanks!

**Review by joker-eph — APPROVED** [review]

**Review by akuegel — CHANGES_REQUESTED** [review]

**Comment by SamuelMarks** [comment]
Also started to look more at the size types, any .cc file I opened I was able to find a multitude of size inconsistencies (size type in `for` loop not matching size type being compared against). Maybe someone wants to work with me on a LibClang/LibTooling tool to automatically correct these errors across the entire codebase?

**Review by ccrusius — CHANGES_REQUESTED** [review]
Thanks for the change, only a couple of small changes requested in the comments for me.

**Review by joker-eph — APPROVED** [review]
(re-approval to put it back in the testing pipeline)

**Comment by SamuelMarks** [comment]
@joker-eph The tests didn't pass so I merged master and built it locally without error. Probably best to merge this quickly, before master deviates too far

**Review by bhack — APPROVED** [review]

**Comment by joker-eph** [comment]
Also this is not clearly unrelated:
```
[ RUN      ] DepthwiseConv2DTest.testDepthwiseConv2DInputGradCompare
INFO:tensorflow:Start test case: DepthwiseConv2DTest.testDepthwiseConv2DInputGradCompare
I1010 21:05:46.342214 139639331483776 xla_test.py:230] Start test case: DepthwiseConv2DTest.testDepthwiseConv2DInputGradCompare
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Fatal Python error: Aborted
```

**Comment by SamuelMarks** [comment]
Fixing now @joker-eph

**Review by joker-eph — APPROVED** [review]

**Comment by joker-eph** [comment]
You still have a lot of _test.cc changed, I'm not sure why is this a good thing though.

**Comment by SamuelMarks** [comment]
@joker-eph Tests may run faster with this optimisation.

Anyway the idea with all of this is to cover the entire TensorFlow codebase, using [`.reserve`](https://en.cppreference.com/w/cpp/container/vector/reserve) on [at least] the most obvious of cases. There's no need to skip any C++ file.

The relevant tests, are they passing now, or did I miss one [e.g., another typo]?

**Comment by joker-eph** [comment]
> @joker-eph Yes there is a maintenance cost, but IMHO reserving vector sizes is something everything should do all the time (when they know the size in advance). 

We'll have to disagree on this: I don't see the point in clobbering unit-tests.

> Similarly in C you should malloc the entire size of what you are going to be working on, rather than—realloc and—malloc continuously.

Luckily we don't write C and we use reasonable abstractions which take care of anything like this for us transparently :)


Anyway a lot of the wasted time was that many iteration of the code just didn't build in the first place. I triggered a CI run and we'll see if we're there yet.

**Comment by bhack** [comment]
I really think that some micro-optimizations could be bench-marked to weight their impact on the readability. 

From the famous [ISO CPP FAQ](https://isocpp.org/wiki/faq/containers):
> People sometimes worry about the cost of std::vector growing incrementally. Many C++ programmers used to worry about that and used reserve() to optimize the growth. After measuring their code and repeatedly having trouble finding the performance benefits of reserve() in real programs, they stopped using it except where it is needed to avoid iterator invalidation (a rare case in most code). Again: measure before you optimize.

**Comment by joker-eph** [comment]
> Hmm, could it be my use of leaf_count?

It is purely syntactic. Compiler says:
```
tensorflow/compiler/xla/shape_tree_test.cc:454:3: error: expected ';' before 'for'
   for (auto index_to_data : t) {
   ^~~
```

Indeed:

 ```
   v.reserve(t.leaf_count())
   for (auto index_to_data : t) {
```

The first line here does not have a `;`.

Then you have issues with how you get `size()`.

```
tensorflow/compiler/xla/shape_tree_test.cc:518:20: error: 'class tensorflow::gtl::iterator_range<xla::ShapeTreeLeafIterator<std::vector<xla::internal::ShapeTreeNode<int>, std::allocator<xla::internal::ShapeTreeNode<int> > >, __gnu_cxx::__normal_iterator<xla::internal::ShapeTreeNode<int>*, std::vector<xla::internal::ShapeTreeNode<int>, std::allocator<xla::internal::ShapeTreeNode<int> > > >, std::pair<xla::ShapeIndex, int> > >' has no member named 'size'
   v.reserve(leaves.size())
                    ^~~~
tensorflow/compiler/xla/shape_tree_test.cc: In member function 'virtual void xla::{anonymous}::ShapeTreeTest_ReverseIterateOrderLeaves_Test::TestBody()':
tensorflow/compiler/xla/shape_tree_test.cc:529:15: error: 'class xla::ShapeTree<int>' has no member named 'size'
   v.reserve(t.size());
               ^~~~
```


Now again this is test code and I feel we're just wasting everyone time here really.

**Comment by bhack** [comment]
> I'm sure it's just my n00bness on the bazel side (each build I do takes many many hours).

This is true just when it is your first time that you compile TF or when your last build was very old (e.g. sparse development) cause currently we don't have a [public read-only pre-filled bazel GCS cache to consume](https://github.com/tensorflow/build/issues/5).

But if your problem is about multiple commits->rebases-merges->builds on the same PR  you need to use `disk-cache` arg for a fast build:
https://docs.bazel.build/versions/main/remote-caching.html#disk-cache

>  And also I'm not testing on every platform your CI runs on. And the IDE integration with bazel I could get to work (TODO follow-up on my: [bazelbuild/intellij#2895](https://github.com/bazelbuild/intellij/issues/2895)). And I'm not filtering the log files from CI effectively. All in all, a whole bunch of excuses that are wholly unwarranted and an understandable annoyance to your team.

You can run the tests with command-line just for your host. We have example strings for running tests on a single target or single test so that you could only rerun the specific fix that was failing:

https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#running-unit-tests

**Review by joker-eph — APPROVED** [review]

**Review by akuegel — APPROVED** [review]

**Comment by SamuelMarks** [comment]
@bhack Thanks for the suggestions. I'll also see if my aforementioned IDE issue is now resolvable https://github.com/bazelbuild/intellij/issues/2895 so that I'll get nice errors/warnings before sending it off to your build server (and/or waiting a very long time for it to build locally)

**Comment by joker-eph** [comment]
Thanks for splitting, but I'm not sure where you got the idea that one PR-per-file is the right granularity?

I handled all of tensorflow/compiler/mlir/... changes though, let me know if I missed any.

**Comment by james-martens** [comment]
Hi,

I'm not sure why I was added to this thread. Perhaps someone typed the
wrong name?

James

**Comment by james-martens** [comment]
It was in Thea Lamkin's message from yesterday:

***@***.*** <https://github.com/james-martens> I recommend you follow
@akuegel <https://github.com/akuegel> and @joker-eph
<https://github.com/joker-eph>'s request to break this PR up, at least
by narrowing down to your working changes."

**Comment by bhack** [comment]
> Thanks @bhack, I wasn't aware of this file. There is another tool we have that auto-assign based on path (for example I get all reviews in tensorflow/compiler/mlir auto-assigned. Seems like we could use this CODEOWNERS files instead!

I think that could be useful to maintain a reference github account for every folder. If not in CODEOWNERS as we don't want to notify directly team members in another reference file. 

This could help up to write in the contribution guide how to segment a code contribution in multiple PR, like this one, for the single team review unit if and when this is possible.

**Comment by bhack** [comment]
Just to make an example:
```
git fetch origin pull/51739/head:reserve
git diff --dirstat=files,0 reserve
```

```
   0.3% tensorflow/c/eager/
   0.3% tensorflow/c/experimental/filesystem/plugins/gcs/
   1.9% tensorflow/c/
   0.7% tensorflow/cc/gradients/
   0.3% tensorflow/cc/ops/
   0.7% tensorflow/cc/saved_model/
   0.3% tensorflow/compiler/aot/
   2.2% tensorflow/compiler/jit/
   1.1% tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/
   0.3% tensorflow/compiler/mlir/hlo/lib/Analysis/
   0.3% tensorflow/compiler/mlir/hlo/
   0.3% tensorflow/compiler/mlir/lite/ir/
   0.3% tensorflow/compiler/mlir/lite/transforms/
   0.3% tensorflow/compiler/mlir/python/
   1.1% tensorflow/compiler/mlir/tensorflow/ir/
   2.2% tensorflow/compiler/mlir/tensorflow/tests/
  13.3% tensorflow/compiler/mlir/tensorflow/transforms/
   0.3% tensorflow/compiler/mlir/tensorflow/utils/
   0.3% tensorflow/compiler/mlir/tensorflow/
   0.3% tensorflow/compiler/mlir/tfr/examples/mnist/
   0.3% tensorflow/compiler/mlir/tfr/integration/
   0.3% tensorflow/compiler/mlir/tfrt/jit/
   0.3% tensorflow/compiler/mlir/tfrt/python_tests/regression_tests/
   0.3% tensorflow/compiler/mlir/tfrt/python_tests/
   0.3% tensorflow/compiler/mlir/tfrt/tests/tf_to_corert/
   0.7% tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data/
   0.3% tensorflow/compiler/mlir/tfrt/transforms/lmhlo_to_gpu/
   0.3% tensorflow/compiler/mlir/tfrt/
   1.5% tensorflow/compiler/mlir/tools/kernel_gen/transforms/
   0.3% tensorflow/compiler/mlir/tools/kernel_gen/
   0.3% tensorflow/compiler/mlir/xla/experimental/conv_emitter/
   0.3% tensorflow/compiler/mlir/xla/ir/
   0.3% tensorflow/compiler/mlir/xla/tests/
   0.7% tensorflow/compiler/mlir/xla/transforms/
   0.3% tensorflow/compiler/mlir/
   0.3% tensorflow/compiler/tests/
   1.1% tensorflow/compiler/tf2tensorrt/convert/
   0.3% tensorflow/compiler/tf2tensorrt/kernels/
   4.1% tensorflow/compiler/tf2xla/kernels/
   0.3% tensorflow/compiler/tf2xla/lib/
   2.2% tensorflow/compiler/tf2xla/
   2.2% tensorflow/compiler/xla/client/lib/
   1.5% tensorflow/compiler/xla/client/
   0.3% tensorflow/compiler/xla/pjrt/
   0.7% tensorflow/compiler/xla/python/tpu_driver/
   1.5% tensorflow/compiler/xla/python/xla_extension/
   1.5% tensorflow/compiler/xla/python/
   1.9% tensorflow/compiler/xla/service/cpu/
   0.7% tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/
   1.1% tensorflow/compiler/xla/service/gpu/tests/
   2.2% tensorflow/compiler/xla/service/gpu/
   0.3% tensorflow/compiler/xla/service/interpreter/
   1.9% tensorflow/compiler/xla/service/spmd/
  12.9% tensorflow/compiler/xla/service/
   4.1% tensorflow/compiler/xla/tests/
   1.9% tensorflow/compiler/xla/
   0.3% tensorflow/compiler/xrt/kernels/
   0.3% tensorflow/compiler/xrt/tests/
   0.3% tensorflow/core/common_runtime/eager/
   0.3% tensorflow/core/common_runtime/
   0.3% tensorflow/core/distributed_runtime/eager/
   0.3% tensorflow/core/framework/
   0.3% tensorflow/core/kernels/
   0.3% tensorflow/core/ops/
   0.7% tensorflow/core/profiler/utils/
   1.1% tensorflow/core/protobuf/
   0.3% tensorflow/core/public/
   1.1% tensorflow/core/runtime_fallback/kernel/
   0.3% tensorflow/core/runtime_fallback/runtime/
   0.3% tensorflow/core/runtime_fallback/
   0.3% tensorflow/go/op/
   0.3% tensorflow/lite/kernels/
   0.3% tensorflow/lite/toco/graph_transformations/
   0.3% tensorflow/python/autograph/impl/
   0.3% tensorflow/python/compat/
   0.3% tensorflow/python/data/ops/
   0.3% tensorflow/python/distribute/integration_test/
   1.1% tensorflow/python/distribute/
   1.5% tensorflow/python/eager/
   1.1% tensorflow/python/framework/
   0.7% tensorflow/python/keras/estimator/
   0.3% tensorflow/python/keras/
   0.3% tensorflow/python/training/
   0.3% tensorflow/python/types/
   0.7% tensorflow/tools/api/golden/v1/
   0.7% tensorflow/tools/api/golden/v2/
   0.3% tensorflow/tools/api/lib/
   0.7% tensorflow/tools/ci_build/
   0.7% tensorflow/
   0.3% third_party/llvm/
   0.3% third_party/tf_runtime/
```

So what kind of PR clustering on folders do you suggest?:

1. `tensorflow/c`
2. `tensorflow/cc`
3. `tensorflow/compiler/jit/`
4. `tensorflow/compiler/mlir`
5. tensorflow/compiler/xla`
5. ....ETC...

**Comment by SamuelMarks** [comment]
@mihaimaruseac So I made #52532 through:
```sh
git checkout master
git checkout -b 'tensorflow.compiler.xla'
git branch -a | grep -F ' tensorflow.compiler.xla' | xargs -n 1 git merge
git push --set-upstream offscale
gh pr create --title "$title" \
             --body '#51739#issuecomment-945027209 told me to merge into one PR per "large module/namespace"'
```

Is that correct? - If so, I'll do the same for the others.

PS: I purposefully didn't squash… do you want me to, or are you happy to just use the GitHub button shortcut?

**Comment by bhack** [comment]
Now it think that your changes are better aggregated.

**Comment by SamuelMarks** [comment]
So what do you want me to do?

**Comment by bhack** [comment]
> So what do you want me to do?

That you run tests for your PR locally as I've already commented in your new PR

**Comment by joker-eph** [comment]
I don't think there is an automated way to tell where to split: this is a semantic kind of thing, for example under `tensorflow/compiler/` every single directory could be a separate component, similar under `tensorflow/core`, but not under `tensorflow/c`.
In general with minimal judgement it isn't too hard to figure out a reasonable grouping.
It is also likely not the common case to have contributions from people who don't really understand the software's high-level components organization.

**Comment by mihaimaruseac** [comment]
I think CODEOWNERS is orthogonal. One is for automatic assignment to reviewers, the other is using judgement to split large PRs.

**Comment by bhack** [comment]
But also now we partially use the `CODEOWNERS` default github assigment/notification logic but in other cases we use a more complex triaging/notification/assigmnet logic as you have mentioned in https://github.com/tensorflow/tensorflow/pull/51739#issuecomment-944427142.

What I meant here is that as we don't have an unique traditional assignment file, it would be nice to have a file in the repository where we maintain the proxy ownership and segmentation of folders/components with a so large project like Tensorflow as this is also not documented in the official website so we don't have any source on this topic.

If you think that then the community will abuse  notification on these Github alias I think that  you could also omit them and just push, in that file, an overview of the folders components semantic.

**Comment by mihaimaruseac** [comment]
So most PRs have been merged. Can you go through the comments on the remaining ones and try to fix them? There are a few with no comments that are going through the pipeline right now but given we've had 100 PRs this resulted in somewhat of a denial of service on CI runners so it will take a while.

**Pull request closed without merging**
