### PR TITLE
Have `write_graph` return the output path of file

### PR DESCRIPTION
**Pull request by samjabrahams**
Since the function is performing `os.path.join()` for the user, it makes sense to return the location of the final file, or else the user will have to call `os.path.join()` again on their own.

### CODE REVIEW

**Comment by drpngx** [comment]
Could we modify the test to check for that?

**Comment by samjabrahams** [comment]
Done- I think I've added them in the right place.

**Comment by samjabrahams** [comment]
Should I also assert `os.path.exists` is True?

**Comment by drpngx** [comment]
Hopefully that'll work under windows. Yes, `os.path.exists` is probably a good idea. Once you push that, I'll trigger a test.

**Comment by samjabrahams** [comment]
How's this look? Added in the path existence test, and changed `"/".join()` to `os.path.join()` (both in existing code and newly added code) for Windows compatibility.

**Comment by drpngx** [comment]
Jenkins, test this please.

Looks good. It would be nice to specify if it's binary/text proto

**Comment by drpngx** [comment]
NM the comment about text/binary, it's in the arguments.

**Pull request merged**
