### PR TITLE
Add Linux and Android makefile

### PR DESCRIPTION
**Pull request by zh794390558**

### CODE REVIEW

**Comment by jdduke** [comment]
In general we only resort to Makefiles for architectures and platforms that are either unsupported by bazel, or for which bazel support is buggy/experimental. Android/Linux are both fairly well-supported by bazel, so I'm curious what the motivation is for this change? There's no description provided.

**Comment by zh794390558** [comment]
@jdduke We want to use lite without java api, and use subset of the lite ops for small size of lib.  Also we are not familiar with bazel.

**Comment by jdduke** [comment]
You don't have to use the full set of ops. If you build a static library (via bazel), you can provide a custom OpResolver with a smaller set of ops to trim the binary size. See also https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/apis.md.

We have a shared library target for the C API in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/c/BUILD#L20. We'll be introducing one for the C++ API, but for now you can tweak the version_script.lds to preserve the C++ symbols.

**Comment by zh794390558** [comment]
@jdduke Does have a guide for compile Android tflite .so or .a lib without Java API? or C api under Android?

**Comment by jdduke** [comment]
Sure, for Android, make sure your bazel Android environment is configured properly (see [this guide](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo)). You can build the C library with:

```
bazel build -c opt --cxxopt=--std=c++11 \
  --config=android_arm \
  //tensorflow/lite/experimental/c:libtensorflowlite_c.so
```

If you want to use the C++ API you'll need to tweak the [linker script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/c/BUILD#L20) to avoid stripping the C++ symbols.

**Comment by bhack** [comment]
@jdduke Is there an integration example with Linux c++? We have [only model inference in a mobile app](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/devguide.md#3-use-the-tensorflow-lite-model-for-inference-in-a-mobile-app). What it is suggested for a standalone app on a linux host? XLA AOT? Tensorflow standard with c++ api?

**Comment by jdduke** [comment]
Sure, you can look at our [minimal](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/minimal) and [label_image](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/label_image) samples for guidance, they should both run on a Linux host using the usual `bazel` build commands.

**Comment by jdduke** [comment]
I'm going to tentatively close this for now. We're going to add proper C/C++ shared library targets over the next month or so as we move the C API out of experimental.

**Pull request closed without merging**
