### PR TITLE
Added 8-bit Quantization Support for ELU.

### PR DESCRIPTION
**Pull request by amitsrivastava78**

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@talumbau , can you please review the PR and provide your feedback, this is kind of important PR for me and need your help to get it though.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@talumbau , i have covered all the scenario and tested even with model, kindly check as this is very important PR for me.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@talumbau , based on your comments on my previous PR (Quantization support for exp operator).
I have reworked the applicable comments here as well.
Kindly check and approve.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@talumbau , i have added TC and kernel version in operator.cc file as well.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@talumbau , i have resolved the merge conflicts, can you please review the code.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@talumbau , can you have a look at the PR and provide your comments, this PR is important for me.

Regards
Amit

**Comment by gbaned** [comment]
@amitsrivastava78 Could you please resolve the conflicts? Thanks!

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
