### PR TITLE
[ROCm] Rocm unit test fixes

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
/cc @chsigg @cheshire @jurahul

### CODE REVIEW

**Comment by jayfurmanek** [comment]
The fix in rocm_dnn.cc here fixes pooling on ROCm and fairly high priority
@chsigg  FYI

**Comment by rsanthanam-amd** [comment]
@chsigg gentle ping

**Comment by rsanthanam-amd** [comment]
@chsigg gentle ping

**Review by jurahul — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @rsanthanam-amd Can you please resolve conflicts? Thank you!

**Comment by rsanthanam-amd** [comment]
> Hi @rsanthanam-amd Can you please resolve conflicts? Thank you!

Done.

**Review by jurahul — APPROVED** [review]

**Pull request merged**
