### PR TITLE
[Windows] Add Windows instructions to the 0.12 docs.

### PR DESCRIPTION
**Pull request by mrry**
Added some instructions for installing/building TensorFlow on Windows, and made minor changes to other docs.

### CODE REVIEW

**Comment by mrry** [comment]
@gunan @yifeif I was guessing what the eventual paths would look like, based on the PIP packages we're generating and the convention for other platforms. Did I guess right?

**Comment by gunan** [comment]
Yeah, the links look right to me.
Is this commit also already in master?

**Review by gunan — APPROVED** [review]

**Comment by mrry** [comment]
@gunan This isn't in master yet - would you like me to send a backport PR?

**Comment by gunan** [comment]
Either is fine.
Once binaries are out, we will merge this back into master, so we can wait
for that too.

**Pull request merged**
