### PR TITLE
Update broken GitHub policy link in issue templates

### LINKED ISSUE #46592: ISSUES.md link broken
## URL(s) with the issue:

Most files under https://github.com/tensorflow/tensorflow/tree/f2d8cfe09234329e14c98798540f146bd94558e0/.github/ISSUE_TEMPLATE

## Description of issue (what needs changing):

The links to the [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md) are broken.

### Clear description

For example, why should someone use this method? How is it useful?

I don't know why there is a separate GitHub policy aside from the CONTRIBUTING.md, but it seems important and people are supposed to read it

### Correct links

Is the link to the source code correct? No

### Parameters defined

Are all parameters defined and formatted correctly? N/A

### Returns defined

Are return values defined? N/A

### Raises listed and defined

Are the errors defined? N/A

### Usage example

Is there a usage example? N/A

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content? N/A

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? No

### PR DESCRIPTION
**Pull request by amahendrakar**
The GitHub policy page has been moved from 

https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md

to 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/opensource_only/ISSUES.md

Updated the links in the issue templates. Fixes [#46592](https://github.com/tensorflow/tensorflow/issues/46592).

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Let's move it back instead.

That directory should not exist in OSS (we're removing it iternally)

**Comment by amahendrakar** [comment]
> Let's move it back instead.

@mihaimaruseac,
In this case, do we just close this PR so that the change is never merged?  

Could you please suggest the best course of action? Thanks!

**Comment by mihaimaruseac** [comment]
Yes, we should close this Pr and instead make sure the files are at the old location.

**Comment by amahendrakar** [comment]
@mihaimaruseac,
Thank you for the update. Closing this PR.

**Pull request closed without merging**
