### PR TITLE
Migrate TF for https://github.com/bazelbuild/bazel/issues/6942

### PR DESCRIPTION
**Pull request by hlopko**
Since Bazel 0.22 static_runtime_libs and dynamic_runtime_libs attributes
are not mandatory, and since 0.23 they are replaced by their singluar
siblings.

Details: https://github.com/bazelbuild/bazel/issues/6942

### CODE REVIEW

**Comment by hlopko** [comment]
CC @meteorcloudy

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
We need to bump the minimal Bazel version to 0.22.0

**Comment by meteorcloudy** [comment]
I'm upgrading TF Bazel version using on CI to 0.23.2, after that you can bump the minimal Bazel version here:
https://github.com/tensorflow/tensorflow/blob/5bc5a4b562170fd922b9e6cb56cd5e0b15429928/configure.py#L1624

**Comment by rthadur** [comment]
@hlopko can you please check failed tests

**Pull request merged**
