### PR TITLE
[TF mobile] change toolchain to clang

### PR DESCRIPTION
**Pull request by Neargye**
Change toolchain to clang, GCC Deprecated on Android ndk
https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: It has been 29 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: It has been 44 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 89 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 104 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 119 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 134 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 149 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 164 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 182 days with no activity and the `awaiting review` label has been applied.

**Comment by andrehentz** [comment]
Sorry I missed this! I'll approve the change but you might have to rebase.

**Review by andrehentz — DISMISSED** [review]

**Comment by Neargye** [comment]
@andrehentz rebase to new master head?

**Review by andrehentz — APPROVED** [review]

**Comment by Neargye** [comment]
@case540  Do I need to do something else?

**Pull request merged**
