### PR TITLE
Fix comment on update_op of streaming_concat()

### PR DESCRIPTION
**Pull request by raviqqe**
I'm not good at writing in English. Could someone improve it?

### CODE REVIEW

**Comment by yifeif** [comment]
@shoyer  could you take a look? Thanks.

**Comment by shoyer** [comment]
This does look like an accurate reflection of what the op currently does. But, to be honest, I did not think too carefully about what the return value of the `update_op` from `streaming_concat()` should be when I wrote this op originally.

An alternative fix would be to make `update_op` actually return the current value of the concatenated tensor. That would be a little more consistent with how other metrics ops work. I'm not entirely sure that makes sense, though, because it *might* have performance consequences to copy large tensors from `tf.Variable` objects into NumPy arrays. If so, then preserving the current behavior of returning the current size makes more sense. Can someone who understands TensorFlow internals better comment here?

Either way, we should add a unit test to verify the behavior (currently, the return value of `update_op` is untested).

@martinwicke any thoughts?

**Comment by drpngx** [comment]
Doesn't it return the value later?

**Comment by shoyer** [comment]
@drpngx

> Doesn't it return the value later?

Yes, `streaming_concat` returns `value` and `update` ops, like the other streaming metrics. But for most streaming metrics, the `update` op also evaluates to the same thing as `value`. If there are no performance implications, we should probably do the same here.

**Comment by drpngx** [comment]
Sorry for being dense, but let me repeat what I understand: the op _should_ return the length, but instead returns the value. This PR proposes to change the doc to say that it returns the length, but that's inaccurate.

**Comment by raviqqe** [comment]
@drpngx I just made the documentation reflect current behavior. I also +1 for returning concatenated tensors for symmetry with other ops. Moreover, we can get length easily with `tf.shape`.

**Comment by shoyer** [comment]
> Sorry for being dense, but let me repeat what I understand: the op should return the length, but instead returns the value. This PR proposes to change the doc to say that it returns the length, but that's inaccurate.

I think the current behavior is actually backwards: the op returns the length, but it is documented to return the value. Clearly this discrepancy is a bug, but we should figure out which behavior we want for the op.

**Comment by drpngx** [comment]
Oh, is that something that we can do this week? We'll have an API freeze soon and it'll be painful to change.

**Comment by vrv** [comment]
It's in contrib, so I don't think timing matters.  Let's do the right thing :)

**Comment by drpngx** [comment]
Oh, good point!

Any volunteer for changing the actual returned value?

**Comment by shoyer** [comment]
So I'm still a little concerned with possible performance implications of
returning the value tensor in the update op. Unlike the values returned by
other streaming metrics, this value could potentially be a very large
tensor. Is there any chance that copying a local variable like this into
numpy could require a memory copy?

**Comment by drpngx** [comment]
@raviqqe is that something you are able to measure?

**Comment by drpngx** [comment]
@shoyer in the code, you're fetching the whole thing, right? That's not quite fair -- we should compute the length in tensorflow and return only the length back.

**Comment by shoyer** [comment]
> @shoyer in the code, you're fetching the whole thing, right? That's not quite fair -- we should compute the length in tensorflow and return only the length back.

The current implementation indeed only returns the length back, so I think we should keep that and move forward with the doc fix suggested by this PR. Indeed, we don't want to fetch the whole thing every time `update` is run.

**Comment by raviqqe** [comment]
@drpngx @shoyer Sorry for being dumb for a while.
I run [a benchmark test](https://gist.github.com/raviqqe/b11f55393004b33b342ff3426957883a) which incorporates @drpngx's opinion. As a result, it seems to be reasonable to keep current behavior of the update op.

```ipython
In [1]: from strm_concat_op_bench import *
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /home/toyama.12056/.gvm/pkgsets/go1.7/global/overlay/l
ib:/home/toyama.12056/.gvm/pkgsets/go1.7/global/overlay/lib:
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3459] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally

... (omitted)

In [3]: %time exec_update()
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:948] Ignoring visible gpu device (device: 1, name: GeForce GT 610, pci bus id: 0000:0a:00.0) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.0.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 2, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:2) -> (device: 3, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0)
[6400]
CPU times: user 325 ms, sys: 97.6 ms, total: 423 ms
Wall time: 458 ms

In [4]: %time exec_update_and_calc_len()
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:948] Ignoring visible gpu device (device: 1, name: GeForce GT 610, pci bus id: 0000:0a:00.0) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.0.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 2, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:2) -> (device: 3, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0)
[6400, 6336]
CPU times: user 2.77 s, sys: 252 ms, total: 3.02 s
Wall time: 3.17 s
```

**Review by drpngx — APPROVED** [review]

**Comment by raviqqe** [comment]
@drpngx Sorry. My benchmark code was wrong. [This](https://gist.github.com/raviqqe/b3cd26119a9e108e03bed089903b0e79) is the fixed version and the following is the result.
There is no difference between returning length by the update op and calculating it from `tf.Tensor` in terms of computational cost. But, we may need to check their difference of memory usage.

```
ipython3 -i fixed_strm_concat_op_bench.py
Python 3.4.3 (default, Aug  9 2016, 15:36:17) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /home/toyama.12056/.gvm/pkgsets/go1.7/global/overlay/lib:/home/toyama.12056/.gvm/pkgsets/go1.7/global/overlay/lib:
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3459] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally

... (omitted)

In [2]: %time exec_update()
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:948] Ignoring visible gpu device (device: 1, name: GeForce GT 610, pci bus id: 0000:0a:00.0) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.0.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 2, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:2) -> (device: 3, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0)
6400
CPU times: user 397 ms, sys: 42 ms, total: 439 ms
Wall time: 396 ms

In [3]: %time exec_update_and_calc_len()
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:948] Ignoring visible gpu device (device: 1, name: GeForce GT 610, pci bus id: 0000:0a:00.0) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.0.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 2, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:2) -> (device: 3, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0)
[6400, 6336]
CPU times: user 353 ms, sys: 43 ms, total: 396 ms
Wall time: 361 ms
ITAN X, pci bus id: 0000:05:00.0)
[6400, 6336]
CPU times: user 353 ms, sys: 43 ms, total: 396 ms
Wall time: 361 ms
```

**Comment by drpngx** [comment]
OK. If you want to submit a PR then @martinwicke can do the API review.

**Pull request merged**
