### PR TITLE
Support constant value tensor shape for tf.constant

### LINKED ISSUE #21267: tf.constant should support dynamic shape
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOSX 10.13.5
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: pip binary
- **TensorFlow version (use command below)**: v1.9.0-0-g25c197e023 1.9.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: -
- **GPU model and memory**: -
- **Exact command to reproduce**: see below

### Source code / logs

Example code:

`tf.constant(3, shape=(3, 1, tf.constant(3) * 5))`

Will throw an error (very unrelated / confusing: `ValueError: setting an array element with a sequence.`).

Corresponding `tf.zeros` or `tf.ones` works, so it is a counter-intuitive that `tf.constant` does not.

(Workaround for me, but this seems a bit ugly: `tf.tile(tf.constant(value, shape=[1] * len(shape)), shape)`)

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #21267 where
it was not possible to provide a tensor to the shape argument
of tf.constant:
```
tf.constant(3, shape=(3, 1, tf.constant(3)))
```
will throw out ValueError.

This fix is an attempt to address the issue so that at least
the constant value tensor shape like `shape=(3, 1, tf.constant(3))`
or `shape=tf.constant([3, 1, 3])` is supported.
It may not be a complete fix but an improvement.

This fix fixes #21267.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by annarev** [comment]
Sorry for delay looking at this! According to @asimshankar comment for #21267, it is better to use `tf.fill` in this case.

Is there another usecase for this PR? Would it be ok to use `tf.fill` in all such cases?

**Comment by rthadur** [comment]
@yongtang gentle ping to check review comments

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
