### PR TITLE
Fixed performance degradation with RUY library on some platforms (e.g. A53)

### PR DESCRIPTION
**Pull request by robert-kalmar**
The RUY library changed the way to detect target processor to choose btw. kernel implementation optimized for in-order vs. out-of-order CPUs. Instead of micro-benchmark it uses `cpuinfo` library. 
Ruy started to provide its own `CMakeLists.txt`, where this change is reflected. This patch switches to use the RUY provided CMakeLists.txt, and ensures the RUY is built with CPUINFO library.

### CODE REVIEW

**Review by terryheo — APPROVED** [review]
Thanks for the fixing this.

**Comment by gbaned** [comment]
@robert-kalmar Can you please resolve conflicts? Thanks!

**Comment by robert-kalmar** [comment]
@kruglov-dmitry  this patch had conflict with your commit e891422915ff031da3eb2089161e34eff19e824f. 
RUY library is shipped with its own CMakeLists.txt. This patch removes the tensorflow/lite/cmake/ruy/CMakeLists.txt and uses the CMakeLists.txt from RUY project. 
Is this change OK with your patch?

**Comment by kruglov-dmitry** [comment]
@robert-kalmar yes!

I've copied changes from this [pr](https://github.com/tensorflow/tensorflow/pull/51455/files) into `tensorflow/lite/CMakeLists.txt` only 

Build was configured using those flags `-D TFLITE_ENABLE_METAL=ON -D TFLITE_ENABLE_GPU=ON` and successfully produced all metal related libraries for iOS!

**Comment by robert-kalmar** [comment]
@terryheo , @gbaned  The conflict is resolved. Also kruglov-dmitry has confirmed this PR does not break his earlier contribution. You can continue with the review, 
Thanks

**Review by terryheo — APPROVED** [review]
LGTM

**Review by gbaned — APPROVED** [review]

**Pull request merged**
