### PR TITLE
R0.12

### PR DESCRIPTION
**Pull request by gunan**
Update release version @asimshankar just to check if the new string complies with all our usecases.
Adding windows GPU build script to the branch.

### CODE REVIEW

**Comment by asimshankar** [comment]
You mean if the version string is semver compliant? 
Looking at semver.org, it seems that "0rc" is not a valid patch since it can't have leading zeros.
Also, the whl files are currently a bit funny - 0.12.0-0rc-0rc... (so 0rc twice).

I think what we might want to do is to set `TF_PATCH_VERSION` in `tensorflow/core/public/version.h` to `0-rc0` but remove the hyphen from the filenames of the `.whl`s

**Comment by gunan** [comment]
Thanks for the explanation.
I made a change to have the version string as '0.12.0-rc0', but make pip convert this to '0.12.0rc0'

**Review by asimshankar — COMMENTED** [review]
'TF_BINARY_URL' looks funny

**Comment by gunan** [comment]
You are right,
looks like we will need to handle version updates in a special way.

**Pull request merged**
