### PR TITLE
cross_validation is deprecated

### PR DESCRIPTION
**Pull request by hprovenza**
And should be replaced with model_selection.

### CODE REVIEW

**Comment by hprovenza** [comment]
I signed it!

**Comment by rmlarsen** [comment]
@martinwicke This would break the internal Google build, since our version of sklearn dores not have model_selection. What's your advice?

**Comment by martinwicke** [comment]
We should update sklearn then. @ilblackdragon, wdyt?

**Comment by hprovenza** [comment]
Just a note that pull request #7115 is an identical change in a different tutorial file; if you decide to make the internal changes necessary to merge this one I think it will be pretty trivial to take care of that one also.

**Comment by dandelionmane** [comment]
friendly ping @martinwicke

**Comment by martinwicke** [comment]
We have not updated sklearn internally so we cannot make this change yet.

**Comment by hprovenza** [comment]
The matching change on #7114 is passing tests now; if this one is tested I would expect it to pass also

**Review by jhseu — APPROVED** [review]

**Comment by jhseu** [comment]
Jenkins, test this please

**Pull request merged**
