### PR TITLE
Fix can't get a replica variable bug when use recompute_grad

### PR DESCRIPTION
**Pull request by fsx950223**
Fix can't get a replica variable bug when use recompute_grad in the graph mode which is reported in https://github.com/google/automl/issues/886.

### CODE REVIEW

**Review by allenlavoie — APPROVED** [review]

**Comment by guptapriya** [comment]
This is a TF1 only bug-fix? Since we have no more TF1 releases, how does this help?
cc @w-xinyi to help review as well from dist strat side.

**Comment by gbaned** [comment]
@fsx950223  Can you please resolve conflicts? Thanks!

**Comment by fsx950223** [comment]
Done

**Comment by gbaned** [comment]
@w-xinyi-zz  Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@w-xinyi-zz  Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@w-xinyi-zz Can you please review this PR ? Thanks!

**Review by rohan100jain — APPROVED** [review]

**Comment by allenlavoie** [comment]
Hi @fsx950223,

One thing that came up as Rohan and I were discussing: we're trying to keep tf.distribute layered cleanly on top of "core" tensorflow as much as possible. The change itself looked fine, but would you mind structuring the tests as (a) a unit test with a stand-in custom tf.Variable subclass (whatever's easy, just to trigger the .op issue) but not tf.distribute, and (b) an integration test using custom_gradient/recompute_grad (rather than the get_dependent_variables helper, i.e. public symbols) + tf.distribute which lives in tensorflow/python/distribute.

(b) is optional, but it's probably useful to have an integration test anyway.

**Comment by fsx950223** [comment]
> Hi @fsx950223,
> 
> One thing that came up as Rohan and I were discussing: we're trying to keep tf.distribute layered cleanly on top of "core" tensorflow as much as possible. The change itself looked fine, but would you mind structuring the tests as (a) a unit test with a stand-in custom tf.Variable subclass (whatever's easy, just to trigger the .op issue) but not tf.distribute, and (b) an integration test using custom_gradient/recompute_grad (rather than the get_dependent_variables helper, i.e. public symbols) + tf.distribute which lives in tensorflow/python/distribute.
> 
> (b) is optional, but it's probably useful to have an integration test anyway.

Do you know how to create such a custom variable?

**Comment by fsx950223** [comment]
> Hi @fsx950223,
> 
> One thing that came up as Rohan and I were discussing: we're trying to keep tf.distribute layered cleanly on top of "core" tensorflow as much as possible. The change itself looked fine, but would you mind structuring the tests as (a) a unit test with a stand-in custom tf.Variable subclass (whatever's easy, just to trigger the .op issue) but not tf.distribute, and (b) an integration test using custom_gradient/recompute_grad (rather than the get_dependent_variables helper, i.e. public symbols) + tf.distribute which lives in tensorflow/python/distribute.
> 
> (b) is optional, but it's probably useful to have an integration test anyway.

I have finished task a. I'm going to add an integration test, where should I put it.

**Comment by allenlavoie** [comment]
I'd put the integration test in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/distribute/mirrored_variable_test.py

And you can subclass ResourceVariable to e.g. override the `op` property to throw an error: https://github.com/tensorflow/tensorflow/blob/17f694077ee5228eb20a8e228e88cd3987e6b854/tensorflow/python/ops/resource_variable_ops.py#L1461

**Review by allenlavoie — APPROVED** [review]

**Comment by fsx950223** [comment]
> Looks like the newly added test is failing,
> 
> ```
> ERROR: testGetVariableByName (__main__.GetDependentVariablesTest)
> GetDependentVariablesTest.testGetVariableByName
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "[...]tensorflow/python/ops/gradients_test.py", line 1033, in testGetVariableByName
>     var2 = custom_gradient.get_variable_by_name("a")
>   File "[...]tensorflow/python/ops/custom_gradient.py", line 330, in get_variable_by_name
>     raise ValueError("Unsuccessful at finding variable {}.".format(var_name))
> ValueError: Unsuccessful at finding variable a.
> ```
> 
> It's [tagged not to run in the outside-Google presubmits](https://github.com/tensorflow/tensorflow/blob/371d215a7b40bc083f593e353f775ae71d73f2c4/tensorflow/python/BUILD#L2699) because it was flaky on GPU a few years ago... you may want to run it manually for now, or try removing the tag.

It passes the test again.

**Comment by allenlavoie** [comment]
Maybe decorate it with `@test_util.run_v2_only`. It was probably failing in 1.x mode with reference variables.

**Comment by fsx950223** [comment]
> Maybe decorate it with `@test_util.run_v2_only`. It was probably failing in 1.x mode with reference variables.

Done

**Review by allenlavoie — APPROVED** [review]

**Pull request merged**
