### PR TITLE
Removing the executor file and link jax to use tpu_api_dlsym_initializer

### PR DESCRIPTION
**Pull request by sshahrokhi**
Because tpu_profiler dependency already pulls in the full tpu_api_dlsym_initializer dependency, so there's no point maintaining this smaller executor dependency.

### CODE REVIEW

**Comment by sshahrokhi** [comment]
@skye could you please take a look at this PR(draft)? it is dependent on [this PR](https://github.com/tensorflow/tensorflow/pull/55413).

**Comment by skye** [comment]
LGTM, my only suggestion to mention that the tpu_profiler dependency already pulls in the full tpu_api_dlsym_initializer dependency, so there's no point maintaining this smaller executor dependency. I'll approve this for real once the previous change is in + this is rebased.

**Comment by sshahrokhi** [comment]
@michaelbanfield could you please review this PR? It is changing where JAX is loading the libtpu, and removing executor file which was the light weight version of tpu_api_dlsym_initializer.

**Review by michaelbanfield — APPROVED** [review]

**Comment by sshahrokhi** [comment]
> @sshahrokhi Can you please resolve conflicts? Thank you!

It is funny that there were commits exactly to the same files I was working on, between the few hours between my PR and your response. Anyhow I rebased it again and the conflict should have been resolved, thanks!

**Review by michaelbanfield — APPROVED** [review]

**Pull request merged**
