### PR TITLE
fixes #1522 close file object properly for read_data()

### LINKED ISSUE #1522: closing file object in read_data() function for word2vec tutorials
The `read_data()` function that appears in the following files:

- tensorflow/tensorflow/examples/tutorials/word2vec/word2vec_basic.py
- tensorflow/tensorflow/examples/udacity/5_word2vec.ipynb

Look like this: 

```
def read_data(filename):
  f = zipfile.ZipFile(filename)
  for name in f.namelist():
    return f.read(name).split()
  f.close()
```

```
def read_data(filename):
  f = zipfile.ZipFile(filename)
  for name in f.namelist():
    return tf.compat.as_str(f.read(name)).split()
  f.close()
```

There are two problems that these two versions of the function share: 

1. The for loop is redundant since the `return` statement exits the loop (and the function) with the first file in the loop. Also, there is only one file within the zip file anyway. 
2. Since the return statement exits the function early, it never executes the `f.close()` line. Therefore it doesn't get to close the file object properly. 

I propose something like this instead: 

```
def read_data(filename):
  """Extract the first file enclosed in a zip file as a list of words"""
  with zipfile.ZipFile(filename) as f:
    data = f.read(f.namelist()[0]).split()
  return data
```

```
def read_data(filename):
  """Extract the first file enclosed in a zip file as a list of words"""
  with zipfile.ZipFile(filename) as f:
    data = tf.compat.as_str(f.read(f.namelist()[0])).split()
  return data
```

I will submit a pull request with the proposed changes.

### PR DESCRIPTION
**Pull request by ronrest**
Fixes the issue raised here:  https://github.com/tensorflow/tensorflow/issues/1522

### CODE REVIEW

**Comment by mrry** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Jenkins, test this, PLEASE

**Comment by ronrest** [comment]
I don't understand the printouts when I click on "Details" for the checks that have failed. Is there something wrong with the code I contributed that caused those errors? Or does it fail because of some other reason? 

Also I am now getting a warning saying `This branch is out-of-date with the base branch` , should I click on the `Update Branch` button?

**Comment by mrry** [comment]
It looks like you branch might be taken from when the build was in a bad state. Can you please rebase to master and we'll rerun the tests? Thanks!

**Comment by vrv** [comment]
FYI, you have to tell us when you rebase, github doesn't tell us :/

@tensorflow-jenkins: test this please.

**Comment by ronrest** [comment]
Oh, sorry. Yes, I have clicked the `Update Branch` button on github now,  is that what you mean by rebasing? (apologies for my ignorance, it is my first time contributing code to someone elses project).

**Comment by ronrest** [comment]
I clicked it again after you sent the message. I realise now that i probably reset any tests you initiated with your comment. Sorry :( 

Can anyone call on jenkins to perform the tests? Or does it only respond to the admins?

**Comment by vrv** [comment]
It only responds to admins right now, sorry :(.  Let me kick it off one more time.  And no worries about any ignorance, we're honored to be your first code contribution!

@tensorflow-jenkins: test this please.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please (our tests are now passing so this will actually tell us something)

**Comment by ronrest** [comment]
Should I rebase again? it is saying the branch is out of date again.

**Comment by vrv** [comment]
every time we merge any other PR, this happens.  It is weird github behavior they recently introduced, because it means everyone would have to rebase after any merge, which is insane for projects that have 30 outstanding PRs.  

since i have admin powers, I can merge though :)

**Comment by ronrest** [comment]
cool :)

**Pull request merged**
