### PR TITLE
Make tf.clip_by_value not crash on empty tensors

### LINKED ISSUE #19337: tf.clip_by_value crashes for empty tensors on GPU
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.4 LTS
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: `b'v1.8.0-0-g93bc2e2' 1.8.0`
- **Python version**: `Python 3.6.1 :: Continuum Analytics, Inc.`
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 9.0, cuDNN 7.0.5
- **GPU model and memory**: Tesla K80, 12 GB
- **Exact command to reproduce**: `./bug.py`

### Describe the problem
`tf.clip_by_value` has four different kernel code paths for different shape inputs.  None of them check for empty inputs, which is necessary before calling into a cuda kernel since the infinite wisdom of cuda is that zero length loops should crash horribly.  One of the four places a check is necessary:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_clip.cc#L48

It ran across this in real code, but it's slightly delicate to reproduce this crash.  Therefore, I'm not sure that the check is technically necessary before all of the paths.  But it's necessary in at least one, as exhibited by the code below.  Also the code should probably be restructured: currently the same error code is repeated three times.  With that restructuring, there would also only need to be one emptiness check.

### Source code / logs

This code reproduces the bug for me.  Note that it runs fine on CPU, since zero length loops on CPUs do not crash horribly:

```
#!/usr/bin/env python3

import numpy as np
import tensorflow as tf

z = tf.placeholder(dtype=tf.float32, shape=None)
x = tf.clip_by_value(z, 1, z)
with tf.Session():
  print(x.eval(feed_dict={z: np.zeros((7,0))}).shape)
```

Resulting output:

```
root@azero-bug:~/tmp$ ./bug.py 
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-05-16 22:07:46.191147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 4761:00:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-05-16 22:07:46.191226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-05-16 22:07:46.514559: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-16 22:07:46.514640: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-05-16 22:07:46.514661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-05-16 22:07:46.514923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10755 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 4761:00:00.0, compute capability: 3.7)
2018-05-16 22:07:46.631461: F ./tensorflow/core/util/cuda_launch_config.h:127] Check failed: work_element_count > 0 (0 vs. 0)
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by girving**
Also rearrange the code to remove duplication.  No tests yet; I'll leave
refactoring the test cases for empty tensor coverage to someone else.

Fixes #19337.

### CODE REVIEW

**Comment by girving** [comment]
Whoever wants to go the rest of the way and write the tests is free to use this patch or not.

**Comment by yongtang** [comment]
@girving Thanks for the fix!

I tried with v1.8.0 and the most recent master branch (nightly). On 1.8.0 the crash happens. Interestingly, on nightly there is no crash. I haven't figure out the changes recently between master and v1.8.0 that prevent the crash. I added small test cases in PR #19396.

It is always better to change the empty tensor case early on, and this PR reduces the code duplication significantly 👍 , so this PR looks good to me.

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by girving** [comment]
Great!  Should we merge this one and then the test case PR separately, or do you want to combine them first?

**Comment by yongtang** [comment]
@girving The two PRs could be merged separately. Since this PR has been approved, I would think someone will merge fairly soon.

**Pull request merged**
