### PR TITLE
Remove sigmoid by calling sigmoid before split

### PR DESCRIPTION
**Pull request by eddiepierce**
Remove one sigmoid function, by calling sigmoid before split

### CODE REVIEW

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Comment by eddiepierce** [comment]
I signed it!

**Review by ebrevdo — APPROVED** [review]
LGTM, thanks!

**Review by ebrevdo — APPROVED** [review]
LGTM, thanks!

**Comment by jhseu** [comment]
Jenkins, test this please

**Pull request merged**
