### PR TITLE
disable ampere tf32 failures

### PR DESCRIPTION
**Pull request by kushanam**
Some tests use matmul op to compute the reference value. For TF32 those ops are less precise causing some tests to fail. This is PR is to address the issue.

### CODE REVIEW

**Review by sanjoy — CHANGES_REQUESTED** [review]
Can you please add a more descriptive description than `"This test fails in TF32"`?

This is also 11.4 specific right?  If yes, do you know why?  Does 11.4 include different algorithms?

**Comment by kushanam** [comment]
> > Some tests use matmul op to compute the reference value. For TF32 those ops are less precise causing some tests to fail.
> 
> In cases where matmul is only used to compute reference values, it is preferable to change the test to use [`test_util.matmul_without_tf32`](https://github.com/tensorflow/tensorflow/blob/9edd7b971aacc3545f7f08c628c39f4761036f01/tensorflow/python/framework/test_util.py#L2087), so that TF32 is not disabled for the op(s) being tested. But given we are trying to get the tests working with CUDA 11.4 as soon as possible, I'm also fine with sticking with `test_util.run_without_tensor_float_32` for now.
> 
> Agree with Sanjoy that, if we stick with `run_without_tensor_float_32`, there should be a more descriptive description.

I suspect as few tests still might fail which I had previously as "no status". I am confirming those.

> > Some tests use matmul op to compute the reference value. For TF32 those ops are less precise causing some tests to fail.
> 
> In cases where matmul is only used to compute reference values, it is preferable to change the test to use [`test_util.matmul_without_tf32`](https://github.com/tensorflow/tensorflow/blob/9edd7b971aacc3545f7f08c628c39f4761036f01/tensorflow/python/framework/test_util.py#L2087), so that TF32 is not disabled for the op(s) being tested. But given we are trying to get the tests working with CUDA 11.4 as soon as possible, I'm also fine with sticking with `test_util.run_without_tensor_float_32` for now.
> 
> Agree with Sanjoy that, if we stick with `run_without_tensor_float_32`, there should be a more descriptive description.

 I agree, added a better description. Also had to refactor some tests to be more clear and also resolve some issues in the original commit due to some tests that had "no status" and hence hadn't raised a flag.

**Comment by kushanam** [comment]
> Can you please add a more descriptive description than `"This test fails in TF32"`?
> 
> This is also 11.4 specific right? If yes, do you know why? Does 11.4 include different algorithms?

I think it is related to matmul's reduced precision in TF32 devices. I tested the some failures with 11.3 and the issues were present. It is possible that the number of failures have increased due to CUDA's extended TF32 coverage.

**Review by pkanwar23 — APPROVED** [review]

**Comment by pkanwar23** [comment]
Closing this, since the PR is no longer relevant. The CUDA upgrade has been pushed out.

**Pull request closed without merging**
