### PR TITLE
 [ROCm] Fix for the broken ROCm CSB. 

### PR DESCRIPTION
**Pull request by deven-amd**
This PR addresses to separate breaks in ROCm CSB

### 1

The following commit breaks the `--config=rocm` build

ab65243

The commit above introduces the test "test_opt_einsum_cached" in //tensorflow/python:special_math_ops_test_gpu

The order of execution of other tests within that file can dictate whether or not the newly added test will pass or fail.
The failure (caught byt he ROCm Nighty CSB run) does not seem specific to the ROCm platform.

The "fix" is to explicitly clear the lru_cache of the routine "special_math_ops._get_opt_einsum_contract_path" (before running the test) to gurantee that the test will pass, irrespective of the order in which it is run relative to the other tests.

-------

### 2

The following commit breaks the `--config=rocm` build

c8b0100

The commit above introduces the test "testFusedBatchNormGradsInference" in //tensorflow/python/eager:forwardprop_test_gpu

We are still working towards analysing the cause of the failure and potentially coming up with the fix. In meantime, the change in this commit is to skip the failing subtest on the ROCm platform. This is so that we can get he ROCm Nightly CSB build passing again.

--------

@whchung @chsigg

### CODE REVIEW

**Review by chsigg — DISMISSED** [review]
Thanks!

**Comment by deven-amd** [comment]
@chsigg , please re-approve. I pushed out a new commit to fix the py_lint error. thanks

**Comment by deven-amd** [comment]
@chsigg, gentle ping

**Review by chsigg — APPROVED** [review]

**Comment by deven-amd** [comment]
@gbaned gentle ping

**Pull request merged**
