### PR TITLE
Add behavioral note to VariableV2 and VarhandleOp

### LINKED ISSUE #37830: Replace VarHandleOp in Keras with VariableV2
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue: https://www.tensorflow.org/api_docs/python/tf/Variable

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Clear description

TF 1.13.1
I can't find anything detail about differences between VarHandlOp and VariableV2. 
As far as I know it seems that VarHandleOp implement in Keras and VariableV2 in TF 1.X. 
How can I convert VarHandleOp to VariableV2 in tf.keras?
I'm using some model processing tool that can only run under VariableV2 ops.

### Correct links

https://git.codingcafe.org/Mirrors/tensorflow/tensorflow/commit/e4a5c5356063d7f7b324a5771fe296bb199b532c
Somelink above is all I could find.

### Parameters defined

---

### Returns defined

---

### Raises listed and defined

---

### Usage example

Is this a usage example?
https://www.tensorflow.org/api_docs/python/tf/raw_ops/VariableV2?hl=pl
Is that a kind of example?

### Request visuals, if applicable

---

### Submit a pull request?
---

### PR DESCRIPTION
**Pull request by ashutosh1919**
Fixes #37830 .
@mihaimaruseac , Please review.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
We should not add Python doctests/examples to the base api_defs. Those files are shared across multiple languages.

**Comment by ashutosh1919** [comment]
@mihaimaruseac , removed doctest, please review.

**Review by mihaimaruseac — APPROVED** [review]
would be great to also get the doctests in a Python side, but let's approve this for now

**Comment by mihaimaruseac** [comment]
See 8582a583d45fdf6a895c0677c7f68b4bf3596ee9 for an example of how to add python-specific text to an OP. Let's try to do that

**Comment by gbaned** [comment]
@ashutosh1919 Can you please check reviewer comments and keep us posted. Thanks!

**Comment by ashutosh1919** [comment]
@gbaned , created new PR for the python_api of this #37925. And @mihaimaruseac is aware about it.This PR contains changes to base_api.

**Comment by mihaimaruseac** [comment]
Let's close this one in favor of #37925

**Comment by ashutosh1919** [comment]
@mihaimaruseac, note that this PR contains the changes in base_api where as #37925 contains changes in python_api. So, do you want me to include these changes in #37925? If yes, then please reply, if no, then please reopen this PR

**Comment by mihaimaruseac** [comment]
Yes, please, let's include everything in one single PR

**Review by mihaimaruseac — APPROVED** [review]

**Comment by ashutosh1919** [comment]
@gbaned, It has been 10 days since @mihaimaruseac approved this PR. It is not merged yet. Please, can you check internal status and update me if something is wrong?

**Comment by alextp** [comment]
I don't understand what this is trying to say, but VarHandleIOp doesn't get automatically read in any meaningful way.

**Pull request closed without merging**
