### PR TITLE
Add gradient for tf.extract_volume_patches

### PR DESCRIPTION
**Pull request by olesalscheider**
This implementation is based on tf.extract_image_patches.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by drpngx** [comment]
Sorry I didn't realize I was a reviewer here. Please find another reviewer for now.

**Review by alextp — APPROVED** [review]

**Pull request merged**
