### PR TITLE
Fix the GraphFloat32::outputs() problem in TFLite

### LINKED ISSUE #53781: [TFLite] An multi-headers model output problem on GPU Delegates.
Hi TFers,
I just found the problem that I was getting wrong data output from my model having multi-headers. For example, if the graph my model is like 0 -> 1 -> 2 -> 3 and the model inputs is [0] outputs is [2, 3], I will only get correct answer from 3 but 2 is not, because our GraphFloat32::outputs() only believe the value with no consumer, the 3 above, is an output value. However, our tflite::Interpreter still tell us the outputs is [2, 3] and it's right. So, I try to fix with this [PR](https://github.com/tensorflow/tensorflow/pull/53780), please take a check.

Following is my code snippet with [this model](https://github.com/tensorflow/tensorflow/files/7875588/small_test.zip) for test :
```
#define PRINT(format, ...)                              \
  do {                                                  \
    TFLITE_LOG(TFLITE_LOG_INFO, format, ##__VA_ARGS__); \
  } while (false);

bool SmallTest(Json::Value& config) {
  auto RunInterpreter =
      [](std::unique_ptr<tflite::Interpreter>* interpreter) -> bool {
    assert((*interpreter)->inputs().size() == 1);
    assert((*interpreter)->outputs().size() == 2);

    float* input_buffer = (*interpreter)->typed_input_tensor<float>(0);
    input_buffer[0] = 1.;
    auto input_index = (*interpreter)->inputs()[0];
    auto size_inputs = (*interpreter)->inputs().size();
    PRINT("(SmallTest) Input: [%f] to input tensors: [%d] with size %d.",
          input_buffer[0], input_index, size_inputs);

    bool is_ok = (*interpreter)->Invoke() == kTfLiteOk;
    if (!is_ok) {
      return false;
    }

    float* first_output = (*interpreter)->typed_output_tensor<float>(0);
    float* second_output = (*interpreter)->typed_output_tensor<float>(1);
    PRINT("(SmallTest) Output: [%f, %f] from output tensors: [%d, %d]",
          first_output[0], second_output[0], (*interpreter)->outputs()[0],
          (*interpreter)->outputs()[1]);

    return true;
  };

  {
    auto model = tflite::FlatBufferModel::BuildFromFile(
        config["model_path"].asCString());
    if (!model) return false;

    tflite::ops::builtin::BuiltinOpResolver op_resolver;
    std::unique_ptr<tflite::Interpreter> interpreter;
    tflite::InterpreterBuilder(*model, op_resolver)(&interpreter);
    interpreter->AllocateTensors();
    PRINT("(SmallTest) CPU:");
    RunInterpreter(&interpreter);
  }

  {
    auto model = tflite::FlatBufferModel::BuildFromFile(
        config["model_path"].asCString());
    if (!model) return false;
    tflite::ops::builtin::BuiltinOpResolver op_resolver;
    std::unique_ptr<tflite::Interpreter> interpreter;
    tflite::InterpreterBuilder(*model, op_resolver)(&interpreter);

    // NEW: Prepare GPU delegate.
    auto options = TfLiteGpuDelegateOptionsV2Default();
    auto* delegate = TfLiteGpuDelegateV2Create(&options);
    if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk)
      assert(false);

    interpreter->AllocateTensors();
    PRINT("(SmallTest) GPU:");
    RunInterpreter(&interpreter);

    // NEW: Clean up.
    TfLiteGpuDelegateV2Delete(delegate);
  }

  return true;
}
#undef PRINT
```

### PR DESCRIPTION
**Pull request by SunAriesCN**
Hi TFers,
I just found the problem that I was getting wrong data output from my model having multi-headers. For example, if the graph my model is like `0 -> 1 -> 2 -> 3` and the model inputs is `[0]` outputs is `[2, 3]`, I will only get correct answer from 3 but 2 is not, because our `GraphFloat32::outputs()` only believe the value with no consumer, the `3` above, is an output value. However, our tflite::Interpreter still tell us the outputs is `[2, 3]` and it's right. So, I try to fix with this PR, please take a check.

### CODE REVIEW

**Comment by SunAriesCN** [comment]
Hi all，any update？

**Comment by impjdi** [comment]
Sorry, I didn't realize I was assigned this.

Your fix may work (sorry, didn't check too closely) when the full graph is run on the GPU, but may not work when only a subgraph is delegated.  We are aware of this issue but it doesn't have an easy fix the way GraphFloat32 works with the rest of the system.  We have broken Google multiple times with various fixes (and I'm dealing with one right now).

Now having said that, I suggest that you insert a dummy x = ADD(x, 1e-6) at the second node and consume the output of that.

**Comment by SunAriesCN** [comment]
Well, thanks for your reply.

Sounds bad that I have to accept workaround insert ADD op now. By the way, would you mind share test cases about the subgraph problems you just mentioned? Maybe I have other idea to try. Otherwise, from your descriptions, I'm just think about the cases that nodes which the part of subgraph in GPU need shortcut to later nodes in other devices. Do they also output the wrong answers?

**Comment by gbaned** [comment]
@impjdi  Can you please assist on above comments from @SunAriesCN. Thank you!

**Comment by SunAriesCN** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/delegate.cc#L98 
Fixed!

**Pull request closed without merging**
