### PR TITLE
Remove the unused/orphaned code in python/package/default.

### PR DESCRIPTION
**Pull request by ericdnielsen**

### CODE REVIEW

**Comment by ericdnielsen** [comment]
@tensorflow-jenkins test this please

**Comment by ericdnielsen** [comment]
I signed it!

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@vrv @martinwicke PTAL.

**Comment by martinwicke** [comment]
@ericdnielsen looks like your commits aren't using your google email? Can you `--amend --author` the commit so CLAbot is happy?

**Comment by ericdnielsen** [comment]
Fixed.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
LGTM

**Pull request merged**
