### PR TITLE
Update Estimator dependency version in setup.py.

### PR DESCRIPTION
**Pull request by case540**

### CODE REVIEW

**Comment by case540** [comment]
For some reason copybara is migrating my internal change. So making new change directly on branch to get it in

**Review by martinwicke — DISMISSED** [review]

**Comment by wdirons** [comment]
This change is failing master builds for me:

error in tensorflow setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'< 1.14.0'",

I think a comma is needed like tensorboard in the line above. (or I might just need a new version of setuptools)

**Comment by case540** [comment]
Ah, thank you. Yup, pretty sure missing comma. WIll fix

**Comment by case540** [comment]
Updated

**Comment by aselle** [comment]
@case540, this needs the new commit added

**Comment by case540** [comment]
Done.

**Comment by aselle** [comment]
this was already merged 
https://github.com/tensorflow/tensorflow/pull/25268

**Pull request closed without merging**
