### PR TITLE
Undef OPAQUE marco conflicting with TensorFlow symbol.

### PR DESCRIPTION
**Pull request by bystepii**
See issue #25773.
@jlebar @rmlarsen.

### CODE REVIEW

**Comment by jlebar** [comment]
I think Eigen is managed as a separate repository and copy/pasted into TF (?), so the PR should be against https://bitbucket.org/eigen/eigen/ ?

But @rmlarsen I also notice that third_party/eigen3 hasn't been updated since Nov 6 2018.  Not sure if that means that adding this one-line fix is going to require a massive Eigen upgrade?

**Comment by rmlarsen** [comment]
third_party/eigen3 is synced with upstream roughly weekly. Feel free to
send a PR for Eigen to fix this issue.

**Comment by Stepiii** [comment]
@rmlarsen [third_party/eigen3/unsupported/Eigen/CXX11/Tensor](https://github.com/tensorflow/tensorflow/blob/master/third_party/eigen3/unsupported/Eigen/CXX11/Tensor) is not the same as [src/default/unsupported/Eigen/CXX11/Tensor](https://bitbucket.org/eigen/eigen/src/default/unsupported/Eigen/CXX11/Tensor).

There are also commits like [this](https://github.com/tensorflow/tensorflow/commit/d0d975f8c3330b5402263b2356b038bc8af919a2#diff-dd67b23046f83602c7172fd9457a44c8) affecting [third_party/eigen3/unsupported/Eigen/CXX11/Tensor](https://github.com/tensorflow/tensorflow/blob/master/third_party/eigen3/unsupported/Eigen/CXX11/Tensor) on TensorFlow repo. @jlebar So I do not think it is managed as a separate repository.

**Comment by jlebar** [comment]
Ah, my bad!

**Comment by Stepiii** [comment]
@rmlarsen Will this PR fix the issue?

**Comment by Stepiii** [comment]
Already fixed in 0621242.

**Pull request closed without merging**
