### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by samuelhychan**
Made a few changes to make the documentation clear.

### CODE REVIEW

**Comment by jhseu** [comment]
Please address the CLA. Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 120 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by annarev** [comment]
@samuelhychan can you please take a look at the CLA comment?

**Comment by tensorflowbutler** [comment]
It has been 20 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Review by MarkDaoust — APPROVED** [review]

**Comment by MarkDaoust** [comment]
Thanks @samuelhychan, 

The change looks good, but we can't merge it unless you answer the CLA bot.

**Comment by tensorflowbutler** [comment]
It has been 28 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
