### PR TITLE
[ROCm] eigen patch needed for HIP header changes

### PR DESCRIPTION
**Pull request by jeffdaily**
This patch is needed to fix the ROCm TensorFlow build for changes currently in HIP master.

### CODE REVIEW

**Review by chsigg — APPROVED** [review]

**Comment by rthadur** [comment]
@jeffdaily can you please check build failures ?

**Comment by jeffdaily** [comment]
@rthadur Eigen moved its repo from bitbucket to gitlab.  All references to fetching from bitbucket will likely need to be updated.

http://eigen.tuxfamily.org/index.php?title=News:Migration_to_GitLab.com_scheduled_on_the_December_4th

**Comment by rthadur** [comment]
@jeffdaily will this require a new PR ?

**Comment by jeffdaily** [comment]
@whchung could you restart CI for this PR?  I think the eigen fetch is now working correctly upstream.

**Pull request merged**
