### PR TITLE
Parallelize instantiation to speedup the build

### PR DESCRIPTION
**Pull request by georgthegreat**
Rationale is in #59503.
The actual slowdown is caused by [this bug in llvm-14](https://github.com/llvm/llvm-project/issues/56241).
However, this PR looks useful disregarding the fix.

What do you think?

(there are no changes in BUILD files as this is only an illustation of the approach)

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @georgthegreat Can you please resolve conflicts? Thank you!

**Comment by georgthegreat** [comment]
Well, I can, but I am not sure if this will be of any help.
This is not the first PR which gets stalled and remains unmerged for months.

**Comment by ishark** [comment]
Apologies @georgthegreat for delay in reviewing the pull requests!

Splitting the gather op sounds useful.
However, want to further understand the benefits. Could you please help understand the following points:

1. [LLVM issue](https://github.com/llvm/llvm-project/issues/56241)  for slowness has been marked fixed  with [pull request](https://github.com/llvm/llvm-project/commit/c7243f21d3f1b1544f6067f81b02c0af9f2ee8ab.) Is the slowness in compile still an issue for gather_ops?

2. Could you share what improvement do you see in the benchmark shared  in #59503?

Thank you! And sorry for the delay!

**Comment by gbaned** [comment]
Hi @georgthegreat Can you please resolve conflicts? Thank you!

**Comment by georgthegreat** [comment]
I have checked the numbers when compiling with clang-16.
They still do look considerable, despite the ~3 time improval.

```
[180922 ms] [CC] [yXk4ysnwCKvoEoFaPJXUUA]: $(SOURCE_ROOT)/contrib/libs/tf/tensorflow/core/kernels/argmax_op.cc [started: 1682333791653, finished: 1682333972575]
[150855 ms] [CC] [RDkjdww6QXNyXD86ALXdRA]: $(SOURCE_ROOT)/contrib/libs/tf/tensorflow/core/kernels/conv_grad_input_ops.cc [started: 1682333855672, finished: 1682334006527]
[149613 ms] [CC] [-xDYlYrxYMG97scgZXkZ8Q]: $(SOURCE_ROOT)/contrib/libs/tf/tensorflow/core/kernels/bias_op.cc [started: 1682333810548, finished: 1682333960161]
[148890 ms] [CC] [G7wCwmR0zR_8pmDQHJtI0g]: $(SOURCE_ROOT)/contrib/libs/tf/tensorflow/core/kernels/cwise_op_select.cc [started: 1682333831877, finished: 1682333980767]
```

**Comment by georgthegreat** [comment]
Let me proceed with closing this.

**Pull request closed without merging**
