### PR TITLE
A theano.clone() equivalent for Tensorflow

### PR DESCRIPTION
**Pull request by thjashin**
This an implementation of a `clone()` function for Tensorflow based on `meta_graph` utilities, inspired by discussion with @sherrym in #5477 .

Feature requests on this can be found in #1070  #5479 . Previous implementations of copying graphs #557 does copy naively and doesn't have `replace` feature as in [theano.clone()](http://deeplearning.net/software/theano/library/#theano.clone).

Though this implementation is almost good. It still has problems for now with control flow copies. To be specific, I'm not sure how to deal with collections of `cond_context` and `while_context`, because both of its `to_proto` functions only consider the case of stripping `export_scope`.

Not copying `cond_context` collection to new operations (to their `_control_flow_context`) will cause problems described in #5477 , also demonstrated in the last test (`testCloneBatchNorm`) in this pull request, which is failed for now. I'm opening this PR early before that test pass, wondering if someone can have advice on dealing with control flow collections when cloning subgraphs. Thanks.

### CODE REVIEW

**Comment by thjashin** [comment]
Anyone help with this PR? @sherrym , @keveman , @vrv , @ebrevdo , especially about the control flow context part.

**Comment by yaroslavvb** [comment]
@yuanbyu may know about control flow parts

**Comment by martinwicke** [comment]
Ping all! @sherrym, @yuanbyu can you look at this?

**Comment by thjashin** [comment]
@yaroslavvb @martinwicke Thanks for help. I'm always willing to keep working on this feature.

**Comment by ebrevdo** [comment]
How does this work related to the graph view and replace operations in contrib?  Can those tools be used to perform cloning?

**Comment by thjashin** [comment]
@ebrevdo Thanks for the question. **The short answer**:
They cannot do exactly the same thing due to bugs, but to fix bugs touches the design. While using meta_graph, from my view, is the most elegant way to implement and maintain this feature.

**Long answer**:
I used to rely on `tf.contrib.graph_editor`. It seems to have everything. But I have to say it's still buggy, and maintenance seems to have stopped for some time. The `graph_replace` function provided in `tf.contrib.graph_editor` tries to do similar things with this PR, however, there are big cases it fails, for example, when one node in the given replacements is a descendant of another, the copied subgraph won't cover the uprooting graph of the descendant node even there are target nodes between this two nodes. I tries to fix but it turns out things are not easy under that framework. This is not the only problem, you could see I had a PR ( #5451 ) merged on problems about control inputs. It's still an easy one to fix, but there exist much harder ones.

Though this owes much to lack of extensive tests in `tf.contrib` modules, I'm still wondering whether `tf.contrib.graph_editor` is the right way to achieve this clone() ability. Then I found the `_control_flow_context` problem, which I raised in #5477 . This is because copying operations in `tf.contrib.graph_editor` is by directly copying members of a python objects. In that issue @sherrym pointed out to me that I could use meta_graph utilities to achieve what I want. So I made this trial. Though I still don't succeed in copying control flow contexts, I find the codes more elegant in this way, compared to implementations in `tf.contrib.graph_editor`.

I believe this is at least a right direction to implement this theano equilvalent. And I also want to point out that **this function is of great value to people building higher level libraries based on Tensorflow, it helps on operation level reuse (which cannot be achieved either by using name scope or by experimental function utilities in TF)**.

**Comment by yaroslavvb** [comment]
@sherrym  ping. Can you comment if this is feasible to get merged?

@thjashin note that getting added to contrib means it's a candidate to be moved into core, which means that core TensorFlow team would have to take over support and maintenance. Hence, the code has to be easy enough to transfer over (ie, design docs can help sometimes)

**Comment by drpngx** [comment]
@thjashin could you merge and push again?

**Comment by thjashin** [comment]
@yaroslavvb Thanks. Any templates for design docs?

**Comment by thjashin** [comment]
@drpngx Sure, I'll do it tomorrow.

**Comment by yaroslavvb** [comment]
@thjashin I was thinking more of an informal thing that'll help someone understand for someone reading the code for the first time (ie, motivation, brief outline of how code is structured and why)

**Comment by thjashin** [comment]
@drpngx Done.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
We might have to move that to contrib first.

**Comment by thjashin** [comment]
@drpngx I think I've modified things in the framework, not just adding other functions...Can you give some advice on how to move them into contrib? btw, I guess if you can get some team member to review, can we directly merge? I guess I don't change the original behavior of other parts of code. Also if you need design docs. I'm very happy to write one. In fact it's just a DFS in the graph with some terminal conditions.

**Comment by drpngx** [comment]
@sheerym or @yuanbyu are the best to review this.

**Comment by drpngx** [comment]
@sherrym sorry, typo.

**Comment by dandelionmane** [comment]
@thjashin I'll try pinging sherrym and yuanbyu directly to review this. In the mean time, can you fix the merge conflict that's appeared?

**Comment by thjashin** [comment]
@dandelionmane Sure. I will do this tomorrow.

**Comment by yaroslavvb** [comment]
cc @purpledog

**Comment by thjashin** [comment]
@dandelionmane I've done the merge.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
@yuanbyu @sherrym Could you take a look? I'm not super familiar with this part of the code.

**Comment by yuanbyu** [comment]
I am not very familiar with this part of the codebase. For the control flow context, it seems to strip name scope when exporting and to add back the "current" name scope when importing. Why doesn't it work in your case?

**Comment by vrv** [comment]
I think for now, given that we don't really have any volunteer maintainers of this code internally, we're going to close this PR;  I think the current implementation of GraphDef and state in TensorFlow's python implementation is not very amenable to analysis and correctness, and while what you've done is very neat, it will probably make it very difficult or impossible to move the existing complex python code (control flow, state management) to better implementations (not a proof, but just a gut feeling).

I believe some of the work on improving functions and state management will make something equivalent to clone() possible and maintainable, and that's what we really need to make sure we do if we intend to make our users happy.

**Comment by ebrevdo** [comment]
+1 I think for now we need to reserve the right to make changes to this
part of the tf codebase without maintaining a .clone implementation,
especially given the lack of internal maintainers.

**Pull request closed without merging**
