### PR TITLE
changed predict to use self.batch_size by default in skflow

### PR DESCRIPTION
**Pull request by mheilman**
Also, this adds an example for skflow that uses sklearn's gridsearchcv.

This was a PR for skflow when it was a separate repo: https://github.com/tensorflow/skflow/pull/126.

### CODE REVIEW

**Comment by mheilman** [comment]
The CLA page seems to always redirect to the individual CLA at the moment, though I need to sign the corporate CLA.

**Comment by mrry** [comment]
Jenkins, test this please.

**Comment by vrv** [comment]
@mheilman : what did you sign as, so I can check the status of the corp CLA?

**Comment by mheilman** [comment]
@vrv, sorry, I haven't actually signed either because I need to sign the corporate CLA but the link for signing it redirects to the individual CLA (i.e., "Your Employer" on [this page](https://cla.developers.google.com/clas) links to [this page](https://cla.developers.google.com/clas/new?domain=DOMAIN_GOOGLE&kind=KIND_INDIVIDUAL)).

**Comment by vrv** [comment]
Try https://cla.developers.google.com/clas/new?domain=DOMAIN_GOOGLE&kind=KIND_CORPORATE ?

**Comment by mheilman** [comment]
Thanks.  I signed the corporate CLA.  It should be under Civis Analytics.

**Comment by ilblackdragon** [comment]
@mheilman Hey, just wanted to update - corp CLAs take few days to process and I still don't see Civis Analytics in the list. Will keep checking on Monday. And thanks for contribution, hope next time will be smoother!

**Comment by mheilman** [comment]
I just got an email saying that that the license agreement I signed was voided "for the following reason:", with no reason listed.  I just emailed cla-submissions@google.com to see what's up.

**Comment by mheilman** [comment]
OK, we re-signed the CLA.  It should be under Civis Analytics.

**Comment by ilblackdragon** [comment]
Jenkins, please test this!

CLA looks good.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

Our bot doesn't yet understand natural language ;)

**Pull request merged**
