### PR TITLE
Update protobuf to 3.4.1

### PR DESCRIPTION
**Pull request by vladmos**
This change is required for compatibility with the upcoming Bazel 0.7. There seem to be no issues in tensorflow itself but there are in the old version of the protobuf repository.

### CODE REVIEW

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
There seems to be small failures in one of the tests:
https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/7006/consoleFull
Could you take a look at the failure above and fix them?

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by vladmos** [comment]
The tests seem to be fixed, can it be merged please? I also need to fix compatibility for other Tensorflow-related repositories, such as Serving and Models, and currently they both fail because they depend on this main repository.

**Review by gunan — APPROVED** [review]

**Pull request merged**
