### PR TITLE
Add Init test hadoop

### PR DESCRIPTION
**Pull request by vnghia**
@mihaimaruseac 
This PR adds initialization for testing hadoop filesystem

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by vnvo2409** [comment]
@mihaimaruseac 
How can I test the integration of modular filesystem with Tensorflow to ensure that there isn't any ODR violation on Windows

**Comment by mihaimaruseac** [comment]
I would build the pip package and the plugins and then from Python I would use `tf.load_library` to load the plugin DLLs and then issue a few filesystem calls.

Or I would use the test suite and pass the plugins as arguments but I think the test suite is still not working on Windows.

**Comment by vnvo2409** [comment]
> I would build the pip package and the plugins and then from Python I would use tf.load_library to load the plugin DLLs and then issue a few filesystem calls.

I tried this method but the filesystem calls does not work. It keeps throw `Unimplemented`

> Or I would use the test suite and pass the plugins as arguments but I think the test suite is still not working on Windows.

I think the main cause of ODR is when we link against pip package ( `pywrap_tensorflow_internal` )  so this approach isn't what we need.

**Comment by mihaimaruseac** [comment]
Hmm, I would add prints to the filesystem registration routines and debug what happen during registration and during lookup. Something seems wrong.

**Comment by vnvo2409** [comment]
AFAIK, we have to issue a few filesystem calls using `modular_filesystem`, but `modular_filesystem` isn't included anywhere outside `//tensorflow/c/experimental`. Where should I add `modular_filesystem` as a dependency so I can get it work ?

**Comment by mihaimaruseac** [comment]
That shouldn't be the case. [These lines](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/c/experimental/filesystem/modular_filesystem_registration.cc;l=261-270;drc=e777af90e878cb3618e583bc1b8ec796903ccbdb) register the filesystem.

Maybe we need adding it as a dependency to https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/platform/BUILD;l=222-231;drc=dcbf62e6b2588c83c3b0fdfcb1fe101eb2afae47 ?

**Comment by vnvo2409** [comment]
When I use `tf.load_library("libgcs_filesystem.so")` in TF 2.3.0 on Linux, it throws 
`
tensorflow.python.framework.errors_impl.NotFoundError: /home/vovannghia56789/.cache/bazel/_bazel_vovannghia56789/203e9f31192603e9d3065c5e6101525c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/c/experimental/filesystem/plugins/hadoop/../../../../../../_solib_k8/libtensorflow_Sc_Slibtf_Ustatus.so: undefined symbol: _ZN10tensorflow7IOErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi
`

It cannot find the symbol of this function here.
https://github.com/tensorflow/tensorflow/blob/7e703f509409d00f99e9c87f69909c2808cc1142/tensorflow/c/tf_status.cc#L41

**Comment by mihaimaruseac** [comment]
Both look like C++ symbols somehow got used in the interface. I'll have to debug this but it's unlikely I'll be able to this week.

Did you compile both plugin and TF code with the same toolchain?

**Comment by vnvo2409** [comment]
I compiled both plugin and TF code on the same machine so I am quite sure it is the same toolchain

**Pull request merged**
