### PR TITLE
add op to tf_op_files.txt

### PR DESCRIPTION
**Pull request by formath**
1. add op to `tensorflow/contrib/makefile/tf_op_files.txt` to fix problem of op not registered
2. download `farmhash` and `highwayhash` to fix `*.h` and `*.cc` not found problem

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @akshaym: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment]
Sorry for the slow review response! We're beginning to deprecate the makefile build of TensorFlow in favor of TF Lite, but this looks like a reasonable change to include even so, thanks.

**Review by petewarden — DISMISSED** [review]

**Comment by formath** [comment]
@petewarden Have fixed conflict. Please approve it again.

**Review by petewarden — APPROVED** [review]

**Pull request merged**
