### PR TITLE
Replace PLATFORM_WINDOWS to _MSC_VER as it only applies to MSVC

### PR DESCRIPTION
**Pull request by rongjiecomputer**
Attempt to fix Bazel Windows build.

/cc @meteorcloudy

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Hi @rongjiecomputer , I have a fix internally for this issue.
That's by changing `PLATFORM_WINDOWS` to `COMPILER_MSVC` in this file.
`PLATFORM_WINDOWS` is only defined in `tf_copts`, `COMPILER_MSVC` is defined in CROSSTOOL, so it's guaranteed to exist.

**Comment by rongjiecomputer** [comment]
@meteorcloudy Can you change the internal fix to `_WIN32` and `_MSC_VER` where appropriate instead of relying on `COMPILER_MSVC` from `CROSSTOOL`?

I was thinking about asking Bazel to remove `-DCOMPILER_MSVC` from `CROSSTOOL` completely. IMO, build system should add as little compile/link flags as possible.

Many Google projects like Protobuf and Chromium do use `COMPILER_MSVC` macro, but they are defined in header file and IWYU rule is enforced. Only Tensorflow is not following the rule.

**Comment by rongjiecomputer** [comment]
I am not against using `PLATFORM_WINDOWS` and `COMPILER_MSVC` if they are defined in header files and IWYU rule is enforced (this is what Chromium does), but `-D` for platform/compiler configuration should be avoided (that is, `PLATFORM_WINDOWS` should not come from `tf_copts` and `COMPILER_MSVC` should not come from `CROSSTOOL`).

**Comment by meteorcloudy** [comment]
@rongjiecomputer I think you are right. Here we also need to distinguish MSVC and clang, as you are working on Clang support for TensorFlow IIRC.

So maybe change it to:
```
#if defined(_MSC_VER) && !defined(__clang__)
#include "third_party/tensorflow/core/platform/windows/cpu_info.h"
#endif
```
Then remove the check in `third_party/tensorflow/core/platform/windows/cpu_info.h` ?

**Comment by meteorcloudy** [comment]
BTW, I want to work on a CROSSTOOL for clang when I have more time, but recently I'm quite occupied.

**Comment by rongjiecomputer** [comment]
> So maybe change it to:
```
#if defined(_MSC_VER) && !defined(__clang__)
#include "tensorflow/core/platform/windows/cpu_info.h"
#endif
```
> Then remove the check in `tensorflow/core/platform/windows/cpu_info.h` ?

`tensorflow/core/platform/windows/cpu_info.h` will include `intrin.h` which Clang+MSVC also needs. I will change `PLATFORM_WINDOWS` to `_MSC_VER` in and still keep the `__clang__` check in `tensorflow/core/platform/windows/cpu_info.h`. Sounds good?

**Comment by meteorcloudy** [comment]
Yes, please do that!

**Comment by rongjiecomputer** [comment]
Done.

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Testing at http://ci.tensorflow.org/view/TF%20pull%20requests/job/tensorflow-pr-win-bazel/61/console

**Comment by rongjiecomputer** [comment]
Everything compiles successfully! (Tests still fail though, but that is not what this PR is for).

I envy the build speed of the CI server 😆 . A change in `tensorflow/core` header file normally will trigger a complete re-build and yet the CI job managed to finish < 30 minutes.

**Pull request merged**
