### PR TITLE
Branch 121719728

### PR DESCRIPTION
**Pull request by zheng-xq**
Merge internal changes

### CODE REVIEW

**Comment by zheng-xq** [comment]
@tensorflow-jenkins test this please

**Comment by zheng-xq** [comment]
@caisq, @vrv, @martinwicke, do we need the "cla/google" for this merge?

**Comment by caisq** [comment]
@zheng-xq My understanding is that cla is usually not in a good state for pushes PRs like this because not every internal author has registered on GH. @vrv and @martinwicke have the permissions to merge without cla being satisfied in this case.

**Comment by zheng-xq** [comment]
Adding @martinwicke to merge the pull request, given the cla issue.

**Pull request merged**
