### PR TITLE
Update outdated K.eval

### PR DESCRIPTION
**Pull request by OverLordGoldDragon**
`K.eval` for K per `import tensorflow.keras.backend as K` fails for a `tensorflow.python.framework.ops.Tensor` tensor for operations involving `tensorflow.python.ops.resource_variable_ops.ResourceVariable`. Minimal reproducible example for a custom optimizer below; replacing `K.eval` with `K_eval` fixes the problem. `eval_fn` code taken from [Keras' backend](https://github.com/keras-team/keras/blob/master/keras/backend/tensorflow_backend.py#L908)

(_Another_ problem does remain for `.save()`, but one down)

<hr>

**Proposed fix**:

```python
def K_eval(x):
    try:
        return K.get_value(K.to_dense(x))
    except:
        eval_fn = K.function([], [x])
        return eval_fn([])[0]
```
<hr>

**UPDATE**: problem is also reproducible in `tensorflow.keras` optimizers & layers, TensorFlow 2.0.0, when eager execution is disabled - overcoming the following error upon `K.eval`:

**Minimal reproducible example 2**:

```python
import tensorflow as tf
import tensorflow.keras.backend as K
tf.compat.v1.disable_eager_execution()

var = K.variable([2.], name='var')

try:
    print("K.get_value", K.get_value(var))
except:
    try:
        print("K.eval", K.eval(var))
    except:
        try:
            print("K.eager(K.get_value)", K.eager(K.get_value)(var))
        except:
            try:
                print("K.eager(K.eval)", K.eager(K.eval)(var))
            except:
                print("K_eval", K_eval(var))
```
```python
K_eval [2.]
```
<hr>

**Minimal reproducible example**:

```python
from tensorflow.python.keras.optimizers import Optimizer
from tensorflow.python.keras.layers import Input, Dense
from tensorflow.python.keras.models import Model
import tensorflow.keras.backend as K
import numpy as np

ipt   = Input(shape=(4,))
out   = Dense(1,  activation='sigmoid')(ipt)
model = Model(ipt, out)
model.compile(SGD(lr=1e-2), loss='binary_crossentropy')

X = np.random.randn(32,4)
Y = np.random.randint(0,3,(32,1))
model.train_on_batch(X,Y)

model.save("path.h5")
```

<hr>

**Custom optimizer**:

```python
class SGD(Optimizer):
    def __init__(self, lr=0.01, momentum=0., decay=0., nesterov=False,
                 total_iterations=100, eta_min=0, eta_max=1,
                 t_cur=0, init_verbose=True, **kwargs):
        eta_t = kwargs.pop('eta_t', 1.)
        super(SGD, self).__init__(**kwargs)
        with K.name_scope(self.__class__.__name__):
            self.iterations = K.variable(0, dtype='int64', name='iterations')
            self.lr = K.variable(lr, name='lr')
            self.momentum = K.variable(momentum, name='momentum')
            self.decay = K.variable(decay, name='decay')
            self.eta_min = K.constant(eta_min, name='eta_min')
            self.eta_max = K.constant(eta_max, name='eta_max')
            self.eta_t = K.variable(eta_t, dtype='float32', name='eta_t')
            self.t_cur = K.variable(t_cur, dtype='int64', name='t_cur')

        self.initial_decay = decay
        self.nesterov = nesterov
        self.total_iterations = total_iterations

    def get_updates(self, loss, params):
        grads = self.get_gradients(loss, params)
        self.updates = [state_ops.assign_add(self.iterations, 1)]
        self.updates.append(state_ops.assign_add(self.t_cur, 1))

        lr = self.lr

        # momentum
        shapes = [K.int_shape(p) for p in params]
        moments = [K.zeros(shape) for shape in shapes]
        self.weights = [self.iterations] + moments

        self.eta_t = _compute_eta_t(self)

        for p, g, m in zip(params, grads, moments):
            v = self.momentum * m - lr * g  # velocity
            self.updates.append(state_ops.assign(m, v))

            if self.nesterov:
                p_t = p + self.momentum * v - lr * g
            else:
                p_t = p + v

            new_p = p_t

            # Apply constraints.
            if getattr(p, 'constraint', None) is not None:
                new_p = p.constraint(new_p)

            self.updates.append(state_ops.assign(p, new_p))
        return self.updates

    def get_config(self):
        config = {
            'lr': float(K.get_value(self.lr)),
            'momentum': float(K.get_value(self.momentum)),
            'decay': float(K.get_value(self.decay)),
            'nesterov': self.nesterov,
            'total_iterations': int(self.total_iterations),
            'eta_t': int(K.eval(self.eta_t)),
            't_cur': int(K.get_value(self.t_cur)),
            'eta_min': int(K.get_value(self.eta_min)),
            'eta_max': int(K.get_value(self.eta_max)),
        }
        base_config = super(SGD, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

def _compute_eta_t(cls):
    PI = 3.141592653589793
    t_frac = K.cast(cls.t_cur / cls.total_iterations , 'float32')
    eta_t = cls.eta_min + 0.5 * (cls.eta_max - cls.eta_min) * \
        (1 + K.cos(PI * t_frac))
    return eta_t
```

<hr>

**Full error trace**:

```python

  File "<ipython-input-7-7b8a41253feb>", line 1, in <module>
    model.save("path.h5")

  File "D:\Anaconda\envs\tf2_env\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 975, in save
    signatures, options)

  File "D:\Anaconda\envs\tf2_env\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 112, in save_model
    model, filepath, overwrite, include_optimizer)

  File "D:\Anaconda\envs\tf2_env\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 99, in save_model_to_hdf5
    model_metadata = saving_utils.model_metadata(model, include_optimizer)

  File "D:\Anaconda\envs\tf2_env\lib\site-packages\tensorflow_core\python\keras\saving\saving_utils.py", line 202, in model_metadata
    'config': model.optimizer.get_config()}

  File "<ipython-input-3-5d1359d04ea5>", line 70, in get_config
    'eta_t': int(K.eval(self.eta_t)),

  File "D:\Anaconda\envs\tf2_env\lib\site-packages\tensorflow_core\python\keras\backend.py", line 1271, in eval
    return get_value(to_dense(x))

  File "D:\Anaconda\envs\tf2_env\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3267, in get_value
    return x.numpy()

AttributeError: 'Tensor' object has no attribute 'numpy'
```

### CODE REVIEW

**Comment by OverLordGoldDragon** [comment]
**UPDATE**: problem is also reproducible in `tensorflow.keras` optimizers & layers, TensorFlow 2.0.0 when eager execution is disabled - overcoming the following error upon `K.eval`:

```python
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
```

**Comment by gbaned** [comment]
@fchollet Can you please take a look on this PR? Thanks!

**Comment by qlzh727** [comment]
If you are trying to get the value of the variable, you should use K.get_value(), which should work for both eager and graph context.

In future, we will probably remove backend functions since TF is the only backend now. There isn't a level of abstraction needed here.

**Comment by OverLordGoldDragon** [comment]
@qlzh727 As shown in minimal reproducible example 2, `K.get_value()` fails. In fact, my fix isn't foolproof and fails for some Variables in `tf.keras` optimizers, with very ambiguous errors. Couldn't figure a way around it reasonably, so nothing to add to `K_eval` - but this one is at least more reliable than the current `K.eval` implementation.

In full agreement that development should just proceed with `tf.keras`; retaining backend neutrality is a pain, and rather unnecessary given usage statistics. Though I don't look forward to losing `keras` implementations, as they're significantly more readable than `tf.keras`.

**Comment by OverLordGoldDragon** [comment]
A new error this change addresses:

```python
ValueError: Operation 'lstm/while/add_27' has been marked as not fetchable.
```

Context: in [LSTMCell](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/layers/recurrent.py#L2027), add the following:

```python
# in __init__
self.step = K.constant(0, dtype='int64', name='step')

# in call
self.step = self.step.assign_add(1)
```
Then, trying `K.get_value` or `K.eval` on `lstm_layer.cell.step` will yield the error.

**Comment by qlzh727** [comment]
Sorry for the late reply.

I wasn't be able to repo the issue with Minimal reproducible example 2 and latest tf nightyly

```
import tensorflow as tf
import tensorflow.keras.backend as K
tf.compat.v1.disable_eager_execution()
print(tf.version.VERSION)

var = K.variable([2.], name='var')

try:
  print("K.get_value", K.get_value(var))
except:
  try:
    print("K.eval", K.eval(var))
  except:
    try:
      print("K.eager(K.get_value)", K.eager(K.get_value)(var))
    except:
      try:
        print("K.eager(K.eval)", K.eager(K.eval)(var))
      except:
        print("K_eval", K_eval(var))
```

2.2.0-dev20200227
K.get_value [2.]

**Comment by gbaned** [comment]
@OverLordGoldDragon Can you please check qlzh727's comments and keep us posted? Thanks!

**Comment by OverLordGoldDragon** [comment]
@gbaned Good to see one of my examples is addressed (thanks for sharing @qlzh727), I'll verify another one in the custom optimizer context sometime.

**Comment by OverLordGoldDragon** [comment]
I don't recall all the failure cases, but some were fixed; no time to dig further now, will just open an issue on recurrence, as I doubt something like a try-except will be merged anyway.

**Comment by OverLordGoldDragon** [comment]
@qlzh727 @gbaned Found the culprit; the minrep. example fails under `tf.python.distribute.distribution_strategy_context.in_replica_context() == True`, which is the case for `_resource_apply_dense` in `OptimizerV2`; a `K.variable` created within that context will error any `K.eval`-etc attempts. My `K_eval` worked for TF 2.1, but no longer in 2.2; at this point it seems the replica context just doesn't want its tensors evaluated like this, so I won't be hacking away further - this context-fest isn't very custom functionality-friendly.

**Pull request closed without merging**
