### PR TITLE
Only hoist after-all instruction if it allows another instruction to be hoisted

### PR DESCRIPTION
**Pull request by Sam-Hornby**
The after all instruction doesn't produce any code and is only used at compile
time, hence it can be put with the other instructions that are not hoisted
individually. The motivation is to reduce compile time of models by reducing
total number of instructions and in the case where this avoids having to clone
and replace the while loop and it's called computations.

### CODE REVIEW

**Review by bishalbaaniya123 — APPROVED** [review]

**Comment by gbaned** [comment]
@r4nt  Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @r4nt Can you please review this PR ? Thank you!

**Comment by joker-eph** [comment]
This is missing tests I think.

**Comment by gbaned** [comment]
Hi @Sam-Hornby Any update on this PR? Please. Thank you!

**Pull request closed without merging**
