### PR TITLE
Added info about how to run TensorBoard for the Deep CNN example.

### PR DESCRIPTION
**Pull request by bernardopires**
The CIFAR tutorial talks a bit about the TensorBoard and I think it'd be nice if the command to run it was mentioned explicitly in the tutorial. Otherwise you have to look the documentation for the TensorBoard and open `cifar10_train.py` to see where the log files are being saved.

### CODE REVIEW

**Comment by bernardopires** [comment]
Thanks for the fast review! I've changed the command to ``tensorboard`` as you suggested. :)

**Comment by vrv** [comment]
Sorry for the delay, can you update this to handle the conflicts?

**Comment by bernardopires** [comment]
Merged upstream and handled the conflicts.

**Comment by vrv** [comment]
Sorry -- can you merge (again) and make sure to squash the commits into one?

**Comment by vrv** [comment]
Closing since it looks like you've given up :(.  Feel free to ping this thread / rebase and we'll re-open and merge.

**Pull request closed without merging**
