### PR TITLE
Numpy ndarray should be serialized as Python list

### LINKED ISSUE #22062: Keras load_model crash for custom layer using tf.gather
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.11.0-dev20180823
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0/7
- **GPU model and memory**: Nvidia Quadro 4000
- **Exact command to reproduce**: N/A

### Describe the problem
When having a custom layer using tf.gather, the model could be built successfully and run without problem. I can save that model successfully; however, when loading the model, the error occurs. If no tf.gather custom layer used, there is no problem. Is this a bug or a mis-use?

My codes are:

	def test_lambda_layer():
	  data_input = keras.Input(shape=(1,4,5), dtype=float)
	  mask = [0,1,1,0,1]
	  valid_out_idx = np.nonzero(mask)[0]
	  x = Lambda(lambda t: tf.gather(t, valid_out_idx, axis=-1))(data_input)
	  x = Conv2D(5, 1, use_bias=False, kernel_initializer='ones', trainable=False)(x)
	  model = keras.Model(inputs=data_input, outputs=x)
	  model.summary()

	  data = np.ones((1,1,4,5), dtype=float)
	  print(model.predict(data))

	  model.save('test.h5')

	  new_model = keras.models.load_model('test.h5')
	  new_model.summary()

	  print(new_model.predict(data))

The error message is:

	Traceback (most recent call last):
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 527, in make_tensor_proto
		str_values = [compat.as_bytes(x) for x in proto_values]
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 527, in <listcomp>
		str_values = [compat.as_bytes(x) for x in proto_values]
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\util\compat.py", line 61, in as_bytes
		(bytes_or_text,))
	TypeError: Expected binary or unicode string, got {'type': 'ndarray', 'value': [1, 2, 4]}

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "test_keras.py", line 31, in <module>
		main()
	  File "test_keras.py", line 28, in main
		test_lambda_layer()
	  File "test_keras.py", line 16, in test_lambda_layer
		new_model = keras.models.load_model('test.h5')
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 230, in load_model
		model = model_from_config(model_config, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 310, in model_from_config
		return deserialize(config, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 64, in deserialize
		printable_module_name='layer')
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 173, in deserialize_keras_object
		list(custom_objects.items())))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1302, in from_config
		process_node(layer, node_data)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1260, in process_node
		layer(input_tensors[0], **kwargs)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 770, in __call__
		outputs = self.call(inputs, *args, **kwargs)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\core.py", line 716, in call
		return self.function(inputs, **arguments)
	  File "test_keras.py", line 5, in <lambda>
		x = Lambda(lambda t: tf.gather(t, valid_out_idx, axis=-1))(data_input)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2650, in gather
		return gen_array_ops.gather_v2(params, indices, axis, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3804, in gather_v2
		"GatherV2", params=params, indices=indices, axis=axis, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 513, in _apply_op_helper
		raise err
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
		preferred_dtype=default_dtype)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1127, in internal_convert_to_tensor
		ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 228, in _constant_tensor_conversion_function
		return constant(v, dtype=dtype, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 207, in constant
		value, dtype=dtype, shape=shape, verify_shape=verify_shape))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 531, in make_tensor_proto
		"supported type." % (type(values), values))
	TypeError: Failed to convert object of type <class 'dict'> to Tensor. Contents: {'type': 'ndarray', 'value': [1, 2, 4]}. Consider casting elements to a supported type.

### PR DESCRIPTION
**Pull request by yanboliang**
Pick the fix at https://github.com/keras-team/keras/pull/10727 to ```tf.keras```.
This PR can fix #22062 and https://github.com/keras-team/keras/issues/11023 as well.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by yanboliang** [comment]
It seems the failure is not relevant, or how to re-trigger the test?

**Comment by fchollet** [comment]
@yanboliang the tests seem to be consistently failing?

**Comment by yanboliang** [comment]
@fchollet I just found the failure caused by bad indentation, and has updated it, let's see the test result.

**Comment by yanboliang** [comment]
I have checked the ```MacOS Contrib``` and ```Windows Bazel GPU``` failures, it seems not relevant to this PR.
This is the ```MacOS Contrib``` failure:
```
tensorflow/contrib/lite/profiling/profiler_test.cc:34
The difference between expected_ms and duration_ms is 14.462999999999965, which exceeds eps_ms, where
expected_ms evaluates to 500,
duration_ms evaluates to 514.46299999999997, and
eps_ms evaluates to 10.
```
It looks like some tests timeout.
And this is ```Windows Bazel GPU``` failure:
```
ERROR: T:/src/github/tensorflow/tensorflow/core/BUILD:2911:1: C++ compilation of rule '//tensorflow/core:device_tracer' failed (Exit 2): msvc_wrapper_for_nvcc.bat failed: error executing command
```
Does anyone know whether or how to fix it? Thanks.

**Comment by yanboliang** [comment]
I don't update my code, but the error changed, I think it's still non-relevant.
```
ERROR: missing input file '@ngraph_tf//:license.txt'
ERROR: /tmpfs/src/github/tensorflow/tensorflow/python/BUILD:1761:1: Creating runfiles tree bazel-out/host/bin/tensorflow/python/gen_training_ops_py_wrappers_cc.runfiles [for host] failed: Process terminated by signal 15: Process terminated by signal 15
ERROR: /tmpfs/src/github/tensorflow/tensorflow/tools/pip_package/BUILD:210:1: //tensorflow/tools/pip_package:build_pip_package: missing input file '@ngraph_tf//:license.txt'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /tmpfs/src/github/tensorflow/tensorflow/tools/pip_package/BUILD:210:1 1 input file(s) do not exist
```

**Comment by yanboliang** [comment]
Gently ping @fchollet @caisq . Would mind to have a look at this? I found other bug (https://github.com/keras-team/keras/issues/11023) which can be fixed by this PR as well. Thanks.

**Comment by yanboliang** [comment]
@fchollet I checked ```Windows Bazel GPU``` and ```XLA``` build failures, they are non-relevant to this PR. What need I do to move forward? Thanks.

**Review by fchollet — DISMISSED** [review]
LGTM, thanks for the PR.

**Comment by yanboliang** [comment]
@caisq The failed test is irrelevant, this change has got approved by fchollet. I found several issues(https://github.com/tensorflow/tensorflow/issues/22062, https://github.com/keras-team/keras/issues/11023) are caused by this bug, can you move forward for this PR? Thanks.

**Comment by yanboliang** [comment]
The last commit is changing unit test from deprecated ```test_session``` to ```cache_session``` according https://github.com/tensorflow/tensorflow/commit/e32029541ae270a021b266fcc3929b2528f8dff1 , so it won't have effect on the PR.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by drpngx — APPROVED** [review]
LGTM latest patch.

**Pull request merged**
