### PR TITLE
Use fixed width types consistently

### PR DESCRIPTION
**Pull request by andrewxcav**
int32_t* functions were being called with int* arguments. This works on most compilers, but some implementations of stdint.h define int32_t as long since long is at least 32-bits, and _technically_ int is at least 16 bits.

This is a portability issue. I have fixed all of the cases that fail with a toolchain that uses long, but I have not exhaustively gone through the codebase for this consistency in order to keep this PR as atomic as possible.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
I should handle these by the weekend

**Comment by andrewxcav** [comment]
I am guessing the bot is having issues because of Github site-wide problems. 

Let me know if you think I need to take any action on the CLA front.

**Comment by mihaimaruseac** [comment]
You have commits under 2 different email addresses. Both need to sign the CLA

**Comment by mihaimaruseac** [comment]
Also, apologies for the delay in reviewing the PR, it has slipped through the cracks

**Review by mihaimaruseac — APPROVED** [review]

**Comment by andrewxcav** [comment]
@googlebot I fixed it.

**Comment by andrewxcav** [comment]
@googlebot I fixed it.

**Comment by andrewxcav** [comment]
@googlebot I fixed it.

**Comment by andrewxcav** [comment]
That was a treasure hunt. I enjoy seeing the daylight between 'git' and 'github' once in a while.

Not sure how my changes could have caused the two failing checks.

**Comment by andrewxcav** [comment]
Any chance we could re-try those Windows builds?

**Comment by mihaimaruseac** [comment]
Sure, retriggered them.

**Pull request merged**
