### PR TITLE
Fixed build failure with TF 2.5.0-rc0

### PR DESCRIPTION
**Pull request by npanpaliya**
On Linux x86_64, while building TF 2.5.0-rc0 for cuda 10.2, I encountered an error that says "no such package @local_cuda referenced by cub" (don't have an exact error). This PR proposes a fix for this.
But I'm surprised how this is working for everyone as the same code is also present on the master branch. And if it is working fine, then what is wrong with my environment.

### CODE REVIEW

**Comment by npanpaliya** [comment]
@goldiegadde - Could you please review this?

**Comment by freedomtan** [comment]
@npanpaliya  FYR. The `deps = ["@local_cuda//:cuda_headers"]` works for for CUDA 11.x because of https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda_configure.bzl#L1143-L1144.  I met this problem when building recent master branch on my Jetson board which doesn't have CUDA 11 yet. This problem was introduced in 7737446695d360efd8e87ca63a26518b8787481c.

tag @chsigg for 7737446

**Comment by npanpaliya** [comment]
> @npanpaliya FYR. The `deps = ["@local_cuda//:cuda_headers"]` works for for CUDA 11.x because of https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda_configure.bzl#L1143-L1144. I met this problem when building recent master branch on my Jetson board which doesn't have CUDA 11 yet. This problem was introduced in [7737446](https://github.com/tensorflow/tensorflow/commit/7737446695d360efd8e87ca63a26518b8787481c).
> 
> tag @chsigg for [7737446](https://github.com/tensorflow/tensorflow/commit/7737446695d360efd8e87ca63a26518b8787481c)

Thanks @freedomtan for the information. Yeah, I'd also found the commit that introduced this problem but was wondering how it has been working for all. Thank you for pointing the change in cuda_configure.bzl which makes it working with cuda 11.x. 
But this breaks TF builds with cuda 10.2. Does it mean that cuda 10.x (specifically 10.2) won't be supported any more?

**Comment by mihaimaruseac** [comment]
TF releases are always tied in with a specific CUDA version.

This PR should be first opened on master, merged, wait for inclusion in tf-nightly and only then cherrypicked on the branch.

**Comment by npanpaliya** [comment]
Closing this one and instead created a new one https://github.com/tensorflow/tensorflow/pull/48393 against master which shows clean changes.

**Pull request closed without merging**
