### PR TITLE
[Intel-MKL] Fold subdivmul based batchnorms onto convlution and biasadd

### PR DESCRIPTION
**Pull request by nammbash**
This PR folds BatchNorms that are of form Sub-RealDiv-Mul format into the Conv2d present before and BiasAdd node present after.

<pre>
Before:
--->Conv2D ---> Sub ---> RealDiv ---> Mul ---> BiasAdd --->
      ^          ^         ^           ^          ^
    Const      Const      Const      Const      Const

After:
--->Conv2D ---------------------------------> BiasAdd --->
      ^                                          ^
  Const(New)                                 Const(New)
</pre>
This optimization can be used in models such as Yolov2, Yolov3 where we see a  12 to 14% FP32 performance improvement while preserving the same mAP accuracy.

Note: The input bias for the convolution2D node is set to zero in our calculation of Const(New) to Conv2D.

### CODE REVIEW

**Comment by petewarden** [comment]
Can you add unit tests for this change, similar to the other graph transform examples? Thanks!

**Comment by nammbash** [comment]
@petewarden Done. Unit test added as requested.

**Review by petewarden — DISMISSED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nammbash** [comment]
@petewarden @wt-huang Can you Merge this PR please.

**Pull request closed without merging**
