### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gbaned** [comment]
@Pulkit0076  Can you please sign CLA. Thanks!

**Comment by Pulkit0076** [comment]
> @Pulkit0076 Can you please sign CLA. Thanks!

@gbaned already done :)
image

**Comment by mihaimaruseac** [comment]
Why did you delete the file?

**Comment by Pulkit0076** [comment]
> Why did you delete the file?
Actually it was having some errors, so I updated and deleted the file that was having a error

**Comment by mihaimaruseac** [comment]
There cannot be an error from a README file.

**Comment by Pulkit0076** [comment]
> There cannot be an error from a README file.

I meant to say in first file , I made a mistake so I updated it and deleted the error commit ( file )

**Comment by mihaimaruseac** [comment]
Your first commit is spam.

**Pull request closed without merging**
