### PR TITLE
[INTEL MKL] Graph pattern matcher for grappler.

### PR DESCRIPTION
**Pull request by mdfaijul**
This PR is to help finding large pattern (e.g. tf.nn.gelu) in a the data flow graph for grappler graph optimization. This has been motivated from pattern matching that exists in the graph_transforms tools (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md)

Intended use is for remapper optimizer. User can get an initial match for a pattern consisting of op types in the nodes with a simple grammar like 

```
leaf_pattern ::= `{` op_type `}`
pattern ::= leaf_pattern |
                  `{` op_type `,` `{` pattern `,` ... `,` pattern `}` `}`
```

Here a pattern syntax has a root and children (typically input ops feeding the root). Each child is a sub-pattern in a recursive manner. After an initial match has been found, additional constraint like device, shapes, constant values etc. will be used for determining a true match for a fusion.

### CODE REVIEW

**Review by ezhulenev — APPROVED** [review]

**Comment by mdfaijul** [comment]
@ezhulenev Thanks for approving this PR.
I have a side question. Is it fine to swap the order of arithmetic optimizer with the remapper in grappler? This would simplify specifying a pattern that can be viewed from TF api level. Otherwise, a subgraph generated from TF apis would be modified by the arithmetic optimizer and a user needs to look at the pattern after arithmetic optimizer.

**Comment by ezhulenev** [comment]
That might be problematic, I remember that we had few performance regressions when I moved arithmetic optimizer, but I don't remember the details. Maybe it was not arithmetic optimizer :) Let's try, if it will lead to perf regressions or test failures I'll get a notification.

**Comment by mdfaijul** [comment]
@ezhulenev I have created a test PR for moving remapper before arithmetic_optimizer.
https://github.com/tensorflow/tensorflow/pull/46097

**Comment by ezhulenev** [comment]
There are few build errors with this PR:

```
CppCompile action:
third_party/tensorflow/core/grappler/utils/pattern_utils_test.cc:23:10: error: module //third_party/tensorflow/core/grappler/utils:pattern_utils_test does not depend on a module exporting 'third_party/tensorflow/core/util/dump_graph.h'
see http://go/cpp-features#layering_check; to fix run:
build_cleaner //third_party/tensorflow/core/grappler/utils:pattern_utils_test
#include "third_party/tensorflow/core/util/dump_graph.h"
         ^
third_party/tensorflow/core/grappler/utils/pattern_utils_test.cc:172:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
  graph_view.SortTopologically(/*ignore_cycles=*/false, {});
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ~~~~~~~~~
third_party/tensorflow/core/grappler/utils/pattern_utils_test.cc:254:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
  graph_view.SortTopologically(/*ignore_cycles=*/false, {});
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ~~~~~~~~~
third_party/tensorflow/core/grappler/utils/pattern_utils_test.cc:340:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
  graph_view.SortTopologically(/*ignore_cycles=*/false, {});
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ~~~~~~~~~
third_party/tensorflow/core/grappler/utils/pattern_utils_test.cc:361:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
  graph_view.SortTopologically(/*ignore_cycles=*/false, {});
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ~~~~~~~~~
third_party/tensorflow/core/grappler/utils/pattern_utils_test.cc:397:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
  graph_view.SortTopologically(/*ignore_cycles=*/false, {});
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ~~~~~~~~~
third_party/tensorflow/core/grappler/utils/pattern_utils_test.cc:418:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
  graph_view.SortTopologically(/*ignore_cycles=*/false, {});
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ~~~~~~~~~
third_party/tensorflow/core/grappler/utils/pattern_utils_test.cc:448:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
  mutation->Apply();
  ^~~~~~~~~~~~~~~
third_party/tensorflow/core/grappler/utils/pattern_utils_test.cc:453:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
  mutation->Apply();
  ^~~~~~~~~~~~~~~
9 errors generated.
```

**Comment by mdfaijul** [comment]
@ezhulenev I have addressed the errors. Please check.

**Review by ezhulenev — APPROVED** [review]

**Comment by mdfaijul** [comment]
@ezhulenev Is there still error?

**Comment by ezhulenev** [comment]
It was approved internally just now, should be submitted soon.

**Pull request merged**
