### PR TITLE
Lite: Add Op Refatcored

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
1:> Optimized Macro usage to reduce code duplication.
2:> Unnecessary Template usage removed.
3:> Wrong error message corrected.

### CODE REVIEW

**Review by lu-wang-g — APPROVED** [review]

**Comment by gbaned** [comment]
@ANSHUMAN87 can you please check failed build errors

**Comment by ANSHUMAN87** [comment]
> @ANSHUMAN87 can you please check failed build errors

@gbaned : I have checked, the errors not related to my changes.

**Comment by ANSHUMAN87** [comment]
@rthadur : The errors are not related to my changes,, would you please help proceed with this PR, Thanks!

**Comment by rthadur** [comment]
@lu-wang-g can you please approve this PR internally

**Comment by lu-wang-g** [comment]
I took a second look at this PR, and found that the changes and benefit were not very obvious at this moment. The original version works well, and let's keep it for now.

**Comment by ANSHUMAN87** [comment]
> I took a second look at this PR, and found that the changes and benefit were not very obvious at this moment. The original version works well, and let's keep it for now.

@lu-wang-g : Thanks for your effort in reviewing, I am sorry i could only partially agree on your conclusion. I totally agree that this PR does not address any functionality issues. But as per benefit part 
i beg to differ from your conclusion by stating that, this kind of PR even though not necessary to have, but it is important to have, as it falls under one of the objectives of TFLite("Reduced binary size").
Please correct me if i am wrong, Thanks a lot!

**Comment by gbaned** [comment]
Considering reviewers comments, I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Comment by ANSHUMAN87** [comment]
@gbaned : I think @lu-wang-g  has not yet went through my reply to his conclusion earlier, also i strongly feel this PR is important to consider, so lets have conclusion from @lu-wang-g.

**Pull request closed without merging**
