### PR TITLE
[ROCm] Enable ROCm support for "sequence" ops / "reverse_sequence" op

### PR DESCRIPTION
**Pull request by deven-amd**
This PR enables ROCm support for the "range" / "linspace" / "reverse_sequence" ops.

PR #26722 is a pre-req for this PR, and hence this PR includes commits from that PR.
Only the last two commit in this PR should be reviewed here (as all others will be reviewed as part of PR #26722 )

----------------

@tatianashp , @whchung : just FYI

### CODE REVIEW

**Comment by deven-amd** [comment]
rebased to remove merge conflicts

**Comment by chsigg** [comment]
Will get back to this in a bit. I would like to have the choice of macro sorted out in PR #26753 first.

**Comment by deven-amd** [comment]
rebased PR to account for updates in PR #26722

**Comment by deven-amd** [comment]
rebased PR to resolve merge-conflicts post the merge for PR #26722 .

Note that now PR #28116 is a pre-requisite for this PR. This PR includes commits from PR #28116

**Comment by deven-amd** [comment]
rebased PR to the tip of master (since all the pre-reqs are now merged).

the changes in this PR are now trivial...please approve and merge.

thanks

deven

**Review by whchung — APPROVED** [review]

**Review by gunan — APPROVED** [review]

**Pull request merged**
