### PR TITLE
[XLA:GPU]: Re-47398 + AMD fix + missing commits.

### PR DESCRIPTION
**Pull request by nouiz**
This re-enable my commits https://github.com/tensorflow/tensorflow/pull/47398 + apply AMD fixed from https://github.com/tensorflow/tensorflow/pull/47730 and add the commits not merged from https://github.com/tensorflow/tensorflow/pull/47398.

@sanjoy

### CODE REVIEW

**Review by sanjoy — APPROVED** [review]

**Comment by gbaned** [comment]
@nouiz Can you please resolve conflicts? Thanks!

**Comment by nouiz** [comment]
I can't. My PR was reverted: 99b9d93780d68190ba0f7b8c3b97c665fc63077b
The only information I have is: `Breaks nigthly non pip tests`
So I can't try to fix it... Can someone fix it or help me get a error that tell me what is going on?

**Comment by deven-amd** [comment]
@googlebot I consent

**Comment by nouiz** [comment]
I reverted the revert, added the AMD fixes and added the missing commit. See the new description.
I still do not know if this will fix the internal error as I do not have access to it. But it fixes tests on AMD GPUs.

**Comment by sanjoy** [comment]
@gbaned do you know what's going on here?

**Comment by gbaned** [comment]
> @gbaned do you know what's going on here (why this isn't auto-merging)?

@sanjoy  It is waiting for the reviewer approval, can you please take a look? Thank you!

**Review by sanjoy — APPROVED** [review]

**Pull request merged**
