### PR TITLE
Sorting now runs in tensorboards image grid.

### PR DESCRIPTION
**Pull request by panmari**
Some other changes from previous commits were also added to compiled file through `gulp vulcanize`. 

To make `gulp vulcanize` work I had to do some other changes first, documented [here](https://github.com/panmari/tensorflow/commit/29045bc29fc94eadfa9cb3dc9f53ccb300752c37). Should I make another PR with these (and also add some documentation for `gulp vulcanize`)? Or would that break the internal build?

### CODE REVIEW

**Comment by vrv** [comment]
ping for @dsmilkov or @danmane

**Comment by panmari** [comment]
@dsmilkov @danmane any feedback on this? I'll rebase it if it's worth the effort.

**Comment by danmane** [comment]
Looks good to me :+1: Rebase please

**Comment by martinwicke** [comment]
I'll rebase and merge.

**Comment by martinwicke** [comment]
I take that back, someone more qualified please do the rebase.

**Comment by panmari** [comment]
Im on it. The documentation for generating the distribution file is kinda
lacking, i'll try to fix that in another PR.

**Comment by panmari** [comment]
@martinwicke rebased and ran `gulp vulcanize` again.

**Comment by martinwicke** [comment]
merged. Thanks!

**Pull request closed without merging**
