### PR TITLE
[Intel MKL] Fixing static scan issue in mkl_layout_pass.cc

### PR DESCRIPTION
**Pull request by nhasabni**

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Nice refactoring. Thank you!
Could you please elaborate more on the static scan issue? What was the problem?
Is it because the original code can get to the for loop even when `GetNodeAttr` is ok for `Tinput` and `Tfilter` but they aren't MKL layout dependent (but `T1`, `T2` are)?

**Comment by claynerobison** [comment]
In the original logic, if Tinput and TFilter are OK, then T1 and T2 are never initialized, but can then be subsquently passed to GetMklOpName()

Conversely, if Tinput and Tfilter are not OK, and T1 and T2 are OK, and the first call to IsMklLayoutDependentOp() returns false, then the 2nd call to IsMklLayoutDependentOp() will use uninitialized Tinput and Tfilter values.

**Comment by penpornk** [comment]
@claynerobison Thank you for the explanation!

**Comment by penpornk** [comment]
@gbaned The `Windows Bazel` and `Windows Bazel GPU` test failures seem unrelated to this PR. Could you please help pull the PR in? Thank you very much!

**Comment by gbaned** [comment]
> @gbaned The `Windows Bazel` and `Windows Bazel GPU` test failures seem unrelated to this PR. Could you please help pull the PR in? Thank you very much!

@penpornk  Sure. Thank you for the confirmation.

**Pull request merged**
