### PR TITLE
Fix GPU delegate flatbuffer target when built from external projects.

### PR DESCRIPTION
**Pull request by AdamHillier**
### Problem

Building the target `//tensorflow/lite/delegates/gpu/cl:serialization_cc_fbs_srcs` currently fails if doing so from an external project that has TensorFlow as a dependency.

Within the TF repo `bazel build //tensorflow/lite/delegates/gpu/cl:serialization_cc_fbs_srcs` works as expected. However, from an external project running `bazel build @org_tensorflow//tensorflow/lite/delegates/gpu/cl:serialization_cc_fbs_srcs` causes a build error:

```
error: unable to load include file: tensorflow/lite/delegates/gpu/common/task/serialization_base.fbs
```

<details>
<summary>Full error logs (building with `--verbose_failures`)</summary>
<br>

```
ERROR: /private/var/tmp/_bazel_adamwork/c7d230be9f03353c15a455e1a87ecf41/external/org_tensorflow/tensorflow/lite/delegates/gpu/cl/BUILD:488:22: Generating flatbuffer files for serialization_cc_fbs_srcs: @org_tensorflow//tensorflow/lite/delegates/gpu/cl:serialization_cc_fbs_srcs failed (Exit 1): bash failed: error executing command 
  (cd /private/var/tmp/_bazel_adamwork/c7d230be9f03353c15a455e1a87ecf41/execroot/larq_compute_engine && \
  exec env - \
    <PATH ENV VAR REDACTED>
    PYTHON_BIN_PATH=/usr/local/opt/python@3.8/bin/python3.8 \
    PYTHON_LIB_PATH=/usr/local/Cellar/python@3.8/3.8.9/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages \
    TF2_BEHAVIOR=1 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; for f in external/org_tensorflow/tensorflow/lite/delegates/gpu/cl/serialization.fbs; do bazel-out/host/bin/external/flatbuffers/flatc --scoped-enums -I ./  -c -o bazel-out/darwin-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/cl $f; done')
Execution platform: @local_execution_config_platform//:platform
error: external/org_tensorflow/tensorflow/lite/delegates/gpu/cl/serialization.fbs:15: 75: error: unable to load include file: tensorflow/lite/delegates/gpu/common/task/serialization_base.fbs
Target @org_tensorflow//tensorflow/lite/delegates/gpu/cl:serialization_cc_fbs_srcs failed to build
```
</details>

The issue comes from this line (recently introduced by cfd834264dbd82a2): https://github.com/tensorflow/tensorflow/blob/d98f22e0e769bfa6177f73799b19266bc7382398/tensorflow/lite/delegates/gpu/cl/BUILD#L521

This include argument passed to `flatc` hard-codes the (relative) workspace root as `./`, which is indeed true when building the target from within the TensorFlow repo. However, if building from an external project the TF workspace root is instead `external/org_tensorflow`; hence the `unable to load include file` build error.

### Proposed solution

This PR fixes the issue by defining a `workspace_root` variable inside `tensorflow.bzl` that will always resolve to the correct root. I am not wedded to this solution and welcome any alternate suggestions for how to fix the problem, but it does work and is (relatively) clean.

### Context

I ran into this issue because I work on [a project](https://github.com/larq/compute-engine) that has TensorFlow as an external dependency. I am in the process of updating our TF dependency from 2.4 to the recent 2.5 release candidates, which are the first to have the problem. Inside our project we build a target that depends on `@org_tensorflow//tensorflow/lite/tools/benchmark:benchmark_tflite_model_lib`, which in turn depends on this flatbuffer target.

### CODE REVIEW

**Comment by abattery** [comment]
@impjdi could you review this PR?

**Review by impjdi — APPROVED** [review]

**Comment by impjdi** [comment]
It currently fails at line

```
    workspace_root = Label("//:WORKSPACE").workspace_root or "./"
```

with the assertion:

```
AssertionError: Must use absolute label in constructor.
```

Unfortunately, I'm not familiar enough with Bazel to suggest a fix :(

**Comment by AdamHillier** [comment]
Hi @impjdi, thanks for looking into this :)

Do you know what command triggers this error (/and maybe what environment too)? For me, on this branch, running `bazel build //tensorflow/lite/delegates/gpu/cl:serialization_cc_fbs_srcs` works just fine. I'm on MacOS if that makes any difference.

**Comment by impjdi** [comment]
Yeah, it's not really your problem, but your PR not being compatible with Google's internal repository you don't have control over.  I'm checking with people how this fix of yours can be accomplished without breaking the internal repository.  I'll keep you posted.

**Comment by impjdi** [comment]
Just letting you know that I bumped up the review internally.

**Comment by angerson** [comment]
That assertion looks for a well-formed label, e.g. `"@repo//foo/bar:baz"`, so `./` is probably breaking it. I'm not certain of how it works myself. Will it work to put `workspace_root` in the `flatc_args` instead, like the way they were before? String interpolation should work there, right?

**Comment by AdamHillier** [comment]
> That assertion looks for a well-formed label, e.g. `"@repo//foo/bar:baz"`, so `./` is probably breaking it. I'm not certain of how it works myself. Will it work to put `workspace_root` in the `flatc_args` instead, like the way they were before? String interpolation should work there, right?

I'm not super familiar with Bazel/Starlark so I'm not sure what you mean by string interpolation - could you elaborate with the precise change you think might work?

**Comment by angerson** [comment]
`"-I " + workspace_root`, for instance. There are a few more examples of functions that build strings throughout the BUILD file.

**Comment by AdamHillier** [comment]
> `"-I " + workspace_root`, for instance. There are a few more examples of functions that build strings throughout the BUILD file.

Ah cool, I misunderstood. I had assumed that the internal issue was with the definition of `workspace_root` in `tensorflow.bzl`, so I thought you were suggesting some different way of defining `workspace_root` inside the `BUILD` file directly. Thanks, I've pushed that change now :)

**Review by angerson — APPROVED** [review]

**Comment by AdamHillier** [comment]
@angerson I guess `feedback/copybara - Google internal checks FAILED` means that solution didn't work?

**Comment by AdamHillier** [comment]
@angerson @impjdi sorry to ping you both, but this is blocking us updating [our project's](https://github.com/larq/compute-engine) TF dependency, so I'd really like to be able to get this in (and cherry-picked onto the `r2.5` branch) if at all possible before the 2.5 release.

Is there anything else I can try from my end to help with this?

**Comment by impjdi** [comment]
One proposal I had (and asked @angerson but haven't heard back yet) was
that your PR just sets `workspace_root = "."`, wait for it to get to the
Google repo, I follow up and swap it out with
`Label('//:WORKSPACE').workspace_root or "."` before it is sent back to TF
GitHub repo.

**Comment by AdamHillier** [comment]
> One proposal I had (and asked @angerson but haven't heard back yet) was that your PR just sets workspace_root = ".", we wait for it to get to the Google repo, I follow up and swap it out with Label('//:WORKSPACE').workspace_root or "." before it is sent back to TF GitHub repo.

Ah okay great, thanks :)

I've pushed that change, but of course can revert it if that's not the approach you end up deciding to take.

**Comment by AdamHillier** [comment]
I don't think the Windows build failure is related?

**Comment by impjdi** [comment]
I think it's unrelated too.  I'm not too familiar with github PRs.  Is
there a way to trigger the tests again to see whether it went away?

**Comment by AdamHillier** [comment]
For now I've just merged in the most recent `master` changes to re-trigger.

**Review by impjdi — APPROVED** [review]

**Comment by impjdi** [comment]
@gbaned Adam has been trying to submit this PR for ages, but things are failing for totally unrelated reasons.  Is there way to expedite this?

**Comment by impjdi** [comment]
Aite.  It's in; thank you for the patience!

Now I'm following up and doing the change from the inside.  I'll update this thread when that is submitted and goes live.

**Comment by AdamHillier** [comment]
Fantastic, thanks very much for your help @impjdi

**Comment by impjdi** [comment]
Okay.  This is now submitted and exported at commit: 59fa037eec3bf526bf8399aae900453e151a05f3

**Pull request merged**
