### PR TITLE
make RestoreV2() work for windows

### PR DESCRIPTION
**Pull request by guschmue**
RestoreV2() did not work because wildcard match had some issues.
Enabled RTTI for windows as well.

### CODE REVIEW

**Review by mrry — APPROVED** [review]
Thanks for the fix!

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by mrry** [comment]
@rmlarsen The Windows failure here is unrelated, and we have a fix for it in the works. This one should be good to merge at your convenience....

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Pull request merged**
