### PR TITLE
Update api_def_Div.pbtxt

### PR DESCRIPTION
**Pull request by rohanreddych**

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
I'm a little bit concerned with updating the API definitions for pbtxts used in multiple languages. Sure, they would work good in Python (doctest, everything), but will fail in all other languages.

@yashk2810 @lamberta do you have a recommendation for this?

Leaving for API owners to review, too.

**Comment by lamberta** [comment]
I think it was decided *not* to add python examples to `.pbtxt` files. cc: @MarkDaoust

**Comment by mihaimaruseac** [comment]
Yes, forgot to update the PR after the decision. Thanks for the ping

**Comment by MarkDaoust** [comment]
See 8582a583d45fdf6a895c0677c7f68b4bf3596ee9 for an example of how to add python-specific text to an OP.

**Comment by rohanreddych** [comment]
@mihaimaruseac should i close these PRs?

**Comment by mihaimaruseac** [comment]
We could update the PR and follow the new guideliness, or we could create new ones

**Comment by MarkDaoust** [comment]
The example is in 8582a58 is clear on how to do this.

@rohanreddych If you're still interested in fixing this follow that pattern please. Feel free to re-open this or make a new PR if you get back to it.

But let's not just leave this open.

**Pull request closed without merging**
