### PR TITLE
[ROCm] Update to use ROCm 3.9 (when building TF with --config=rocm)

### PR DESCRIPTION
**Pull request by deven-amd**
~~PR https://github.com/tensorflow/tensorflow/pull/43636 is a pre-requisite for this PR.~~

~~For the time being, this PR includes commits from it's pre-req as well.  Once the pre-req PR is merged, I will rebase this PR to remove those commits.~~

update : PR  https://github.com/tensorflow/tensorflow/pull/43636 has been merged, and I have rebased this PR to pull it in

--------------------------------------

/cc @cheshire @chsigg @nvining-work

### CODE REVIEW

**Review by cheshire — APPROVED** [review]

**Comment by gbaned** [comment]
@deven-amd  Can you please resolve conflicts? Thanks!

**Comment by deven-amd** [comment]
@gbaned done

**Comment by deven-amd** [comment]
I see the cause of the errors in `Linux GPU` and `Ubuntu CPU` ... will push out a fix soon

**Comment by akuegel** [comment]
I have actually already rebased the earlier version of your PR and fixed a few issues, hopefully it will be merged soon.

**Comment by deven-amd** [comment]
@akuegel 

This PR does seem to have gotten merged...thank you for rebasing it and seeing it through.  

The merged PR seems to have dropped one of the commits ( https://github.com/tensorflow/tensorflow/commit/fbfdb64c3375f79674a4f56433f944e1e4fd6b6e ) even though it is mentioned in PR message here (https://github.com/tensorflow/tensorflow/commit/312e6bacca8377d94ca4f62ca899683817728c67). 

Do you want me to close out this PR and file another one to pick up the missing change?

thanks

**Comment by akuegel** [comment]
Please create another one. I am not sure why this was not included, but in any case I was just happy that I could get this merged at all. It should be easier now to apply smaller fixes on top of that.

**Pull request closed without merging**
