### PR TITLE
[Features] Support gradients reduction in tf.gradients according to immediate_grads_reduction in CollectiveAllReduceStrategy and MirroredStrategy

### PR DESCRIPTION
**Pull request by wangsiyu**
Currently, gradients_reduction will be called in `apply_gradients` when using `DistributionStrategy`. It will block computation and communication overlapping with `clip_by_global_norm`. In this pull request, the `immediate_grads_reduction` has been add to `MirroredStrategy` and `CollectiveAllReduceStrategy`. When it is True, the gradients reduction will be called in `tf.gradients` so that the clipping operation will be executed after communication. Otherwise, it preserves the original cases. 

`immedeiate_grads_reduction` has been only enabled in graph mode. We will also add support in eager mode in the future.

This PR will change some API. Could you please take a look at this PR?  This performance feature has been widely used in Alibaba. Any comments are welcome.

@yuefengz

### CODE REVIEW

**Comment by yangjunpro** [comment]
Thank siyu for the nice work.

@yuefengz 

Could you please kindly take a look at this PR?

Regards

**Comment by isaprykin** [comment]
It sounds like Yuefeng's review is requested.

**Comment by rthadur** [comment]
@wangsiyu can you please resolve conflicts.

**Comment by wangsiyu** [comment]
> @wangsiyu can you please resolve conflicts.
OK. I will solve it and come back soon.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
