### PR TITLE
Branch 155393864

### PR DESCRIPTION
**Pull request by rmlarsen**

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by yifeif** [comment]
This one seems to be still running https://ci.tensorflow.org/job/tensorflow-pull-requests-multijob/4922/

**Comment by rmlarsen** [comment]
Yes, I kicked off another run.

**Comment by rmlarsen** [comment]
But yes, the MacOS buld seems to actually be making progress this time.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
