### PR TITLE
Improved support for OpenCL

### PR DESCRIPTION
**Pull request by benoitsteiner**

### CODE REVIEW

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
The failures in sanity checks are terminating all other tests.
https://ci.tensorflow.org/job/tensorflow-pull-requests-sanity/2184/console

**Comment by benoitsteiner** [comment]
I fixed the sanity check failure.

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
Looks like after this PR on MacOS, one shard of the cwise_ops_test is consistently failing with the following error:

```
FAIL: testBCast_15B (__main__.BinaryOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jenkins/47802726cfb6783f0513af299bd0e285/execroot/tensorflow-master-mac/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/cwise_ops_test.py", line 1031, in testBCast_15B
    self._testBCastB([10, 3, 1, 2], [3, 1, 2])
  File "/private/var/tmp/_bazel_jenkins/47802726cfb6783f0513af299bd0e285/execroot/tensorflow-master-mac/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/cwise_ops_test.py", line 829, in _testBCastB
    self._testBCastByFunc(funcs, xs, ys)
  File "/private/var/tmp/_bazel_jenkins/47802726cfb6783f0513af299bd0e285/execroot/tensorflow-master-mac/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/cwise_ops_test.py", line 814, in _testBCastByFunc
    self._compareBCast(ys, xs, dtype, np_func, tf_func)
  File "/private/var/tmp/_bazel_jenkins/47802726cfb6783f0513af299bd0e285/execroot/tensorflow-master-mac/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/cwise_ops_test.py", line 795, in _compareBCast
    self._compareGpu(x, y+ 0.1, np_func, tf_func)
  File "/private/var/tmp/_bazel_jenkins/47802726cfb6783f0513af299bd0e285/execroot/tensorflow-master-mac/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/cwise_ops_test.py", line 575, in _compareGpu
    self.assertAllClose(np_ans, tf_gpu)
  File "/private/var/tmp/_bazel_jenkins/47802726cfb6783f0513af299bd0e285/execroot/tensorflow-master-mac/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 449, in assertAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
  File "/Library/Python/2.7/site-packages/numpy-1.11.0-py2.7-macosx-10.11-intel.egg/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/Library/Python/2.7/site-packages/numpy-1.11.0-py2.7-macosx-10.11-intel.egg/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=1e-06

(mismatch 1.66666666667%)
 x: array([[[[   1.000000  +0.j      ,    1.474711  +0.703009j]],

        [[   2.064002  +1.518696j,    2.834290  +2.474841j]],...
 y: array([[[[   1.000000  +0.j      ,    1.474711  +0.703009j]],

        [[   2.064002  +1.518697j,    2.834289  +2.47484j ]],...

----------------------------------------------------------------------
Ran 3 tests in 13.699s

FAILED (failures=1)
```

@benoitsteiner @lukeiwanski I looked at the code, and I see that in _compareBCast in cwise_ops_test we add `0.1` to one of the args.
Is it by any chance a leftover?
I will send a PR to fix.

**Pull request merged**
