### PR TITLE
Lite: Space_to_batch Op N-dim support

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
Arbitrary dimension support added

### CODE REVIEW

**Comment by ANSHUMAN87** [comment]
Add ref: #21526

**Comment by jdduke** [comment]
Is there a specific model you're using which requires this?

**Comment by ANSHUMAN87** [comment]
> Is there a specific model you're using which requires this?

@jdduke : I am using 4-D space-to-batch, but i have generalized the kernel, as it states N-Dim.

**Comment by jdduke** [comment]
So, in general I'm sympathetic to these changes. The problem is that, every time we change the TFLite operator semantics, we have to bump the operator version and that has non-trivial downstream implications for our accelerator library (i.e., every single one has to be updated, and that can take a year+ for NNAPI). Unless you have a model which requires this (and this applies for other operators that you're generalize), I would rather wait to modify the semantics until there's a clear and immediate need. Thanks for your patience.

**Comment by ANSHUMAN87** [comment]
> So, in general I'm sympathetic to these changes. The problem is that, every time we change the TFLite operator semantics, we have to bump the operator version and that has non-trivial downstream implications for our accelerator library (i.e., every single one has to be updated, and that can take a year+ for NNAPI). Unless you have a model which requires this (and this applies for other operators that you're generalize), I would rather wait to modify the semantics until there's a clear and immediate need. Thanks for your patience.

@jdduke: Thanks a lot for enlightening(Will keep in mind for my Future PRs). For your reference i am posting the issue link #21266, which sought for such generalization, which triggered my PR. I had also added a reference link(#21526) where @suharshs : added this feature as TBD state.

**Comment by jdduke** [comment]
Ahh, that's very helpful! There does appear to be a compelling model which requires this, though we should check that model (issue #21266) to see if your change would resolve the problem. Can you check, with your change?

**Comment by ANSHUMAN87** [comment]
> Ahh, that's very helpful! There does appear to be a compelling model which requires this, though we should check that model (issue #21266) to see if your change would resolve the problem. Can you check, with your change?

@jdduke : Sure, i will update once i get the result, Thanks!

**Comment by jdduke** [comment]
Sounds good, thanks for checking! Once you confirm that updating to support ND unblocks the referenced models, we can proceed with this and https://github.com/tensorflow/tensorflow/pull/28179.

**Comment by ANSHUMAN87** [comment]
> Sounds good, thanks for checking! Once you confirm that updating to support ND unblocks the referenced models, we can proceed with this and #28179.

@jdduke : I have verified with both my PRs #27867 & #28179 , it solves the blocking model execution.
Note: i have used the model file attached in the issue(#22146), and the inference is successful.

**Comment by jdduke** [comment]
Thanks @ANSHUMAN87, I'm confirming internally about landing these changes, stay tuned.

**Comment by ANSHUMAN87** [comment]
@jdduke : Any update on this & #28179 ?

**Comment by jdduke** [comment]
Thanks again for your contribution. Per previous directions, we're still reviewing proposals which have downstream impact on operator semantics. Anything that requires a version bump for the operator has a non-trivial impact on our accelerator ecosystem, and has to be considered carefully. Please be patient.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by sorenchiron** [comment]
hoping to see the successful merge, I'm in great need of N-dim support of Conv1D operators for use in audio speech analysis applications.

**Comment by jdduke** [comment]
Would it simplify the implementation if we just supported the <=4D case?

**Comment by gbaned** [comment]
@ANSHUMAN87 Could you please check reviewer comments and keep us posted. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by ANSHUMAN87** [comment]
> Would it simplify the implementation if we just supported the <=4D case?

@jdduke : Sorry for late response! Earlier only 4D was supported. So i generalized it. As of now i can not think of otherwise. Welcome for any suggestion. Thanks!

**Comment by ANSHUMAN87** [comment]
> > Would it simplify the implementation if we just supported the <=4D case?
> 
> @jdduke : Sorry for late response! Earlier only 4D was supported. So i generalized it. As of now i can not think of otherwise. Welcome for any suggestion. Thanks!

If we want to support only <=4D, may be we can have different kernel implementation based on Number of Dimension. It will be mostly like switch case. But i feel that may not be a good one. Waiting for your feedback!

**Comment by jdduke** [comment]
My main concern right now is the introduction of temporary tensor usage, which wasn't needed before. If we implement the <= 4D case, would we be able to get rid of that? Hopefully we could at least reuse some of the logic between dimensional cases?

**Comment by gbaned** [comment]
@ANSHUMAN87 Can you please check reviewer comments and keep us posted. Thanks!

**Comment by ANSHUMAN87** [comment]
> My main concern right now is the introduction of temporary tensor usage, which wasn't needed before. If we implement the <= 4D case, would we be able to get rid of that? Hopefully we could at least reuse some of the logic between dimensional cases?

@jdduke : In that case the operator cant not be N-Dim. However if you think limiting the kernel only to 4-Dim is best, i will check and confirm whether the existing logic can be reused.

**Comment by jdduke** [comment]
> However if you think limiting the kernel only to 4-Dim is best, i will check and confirm whether the existing logic can be reused.

Worth checking, particularly if this will handle the Conv1D-related scenarios.

**Comment by ANSHUMAN87** [comment]
> > However if you think limiting the kernel only to 4-Dim is best, i will check and confirm whether the existing logic can be reused.
> 
> Worth checking, particularly if this will handle the Conv1D-related scenarios.

@jdduke : Sorry for late reply! I checked regarding the point you suggested. I think it is possible to reuse the existing code to support (dim < 4), but it can not support (dim > 4), also in order to reuse, we have to create intermediate tensors to store the upgraded block_data & padding_data.

Please let me know your valuable opinion in this case. TIA!

**Comment by jdduke** [comment]
Looping in @thaink who is helping us improve our kernel ecosystem to support 5D shapes more generally, particularly for operators currently restricted to 4D.

**Comment by thaink** [comment]
Thanks Jared. Let me take a look.

**Comment by thaink** [comment]
Hi @ANSHUMAN87,
Are you actively on this? we are having an internal user-case that need support 3D space_to_batch. So I think I'll add 3D support first, then let's discuss about N-D later.

**Comment by ANSHUMAN87** [comment]
> Hi @ANSHUMAN87,
> Are you actively on this? we are having an internal user-case that need support 3D space_to_batch. So I think I'll add 3D support first, then let's discuss about N-D later.

@thaink : Thanks for your feedback! Yes i am active on the PRs. I believe adding for specific cases may not be the right approach. However i have put my analysis in my previous comment. We can reuse the existing code to support both 3-D & 4-D. But it will lack N-D support. If you have not started working on it. May be we can use current PR and improvise it to the current requirements.  Just a thought! What do you feel? 
Having said that, still i would press for N-D kernels rather than specific kernels.

**Comment by thaink** [comment]
@: Implementation to support 3-D looks is simple enough to make it quick and it fills both your and our user-cases. So I prefer to support it first. Extending to ND is good but it will take sometime to review your PR.

**Comment by ANSHUMAN87** [comment]
> @ANSHUMAN87: Implementation to support 3-D looks is simple enough to make it quick and it fills both your and our user-cases. So I prefer to support it first. Extending to ND is good but it will take sometime to review your PR.

@thaink : Thanks! Will wait for your comments!

**Comment by thaink** [comment]
space_to_batch and batch_to_space now supports 3D. You can sync to head to try it with your model.

**Comment by gbaned** [comment]
@ANSHUMAN87 Can you please check thaink's comments and resolve conflicts. Thanks!

**Comment by ANSHUMAN87** [comment]
@gbaned : I will handle this PR possibly by Saturday. Thanks!

**Comment by ANSHUMAN87** [comment]
> space_to_batch and batch_to_space now supports 3D. You can sync to head to try it with your model.

@thaink : Thanks! I checked it works fine for 3D support.

**Comment by ANSHUMAN87** [comment]
@gbaned : Thanks! The conflicts are resolved now.

**Comment by jdduke** [comment]
See also the latest comment on PR #28179. We're working on an overhaul for >4D kernel support, so I think it's best if we table this PR for now (and 1 or 2 of the related PRs) as we work toward that end. Thanks for your patience in iterating on this and pushing for generalization, and apologies we couldn't land this more promptly.

**Pull request closed without merging**
