### PR TITLE
Definitions about @protobuf between the workspace.bzl and grpc

### PR DESCRIPTION
**Pull request by Shuolongbj**
grpc expects //external:protobuf_clib and //external:protobuf_compiler to point to the protobuf's compiler library.

Definitions about @protobuf between the workspace.bzl and grpc(https://github.com/grpc/grpc/blob/master/WORKSPACE)

### CODE REVIEW

**Comment by jhseu** [comment]
(Adding Justine because I don't understand our protobuf Bazel config). Some unrelated changes made it in, please revert.

**Comment by Shuolongbj** [comment]
@jhseu @jart thanks !
Definitions about @protobuf between the tensorflow.bzl and [grpc](https://github.com/grpc/grpc/blob/master/WORKSPACE)

**Comment by jart** [comment]
Mr. Jenkins: test this please

**Comment by jart** [comment]
I don't understand this change. Why change the name from `@protobuf` to `@com_google_protobuf`? The only difference between the two is the noinline patch we have.

**Comment by Shuolongbj** [comment]
@jart 
thanks! 
tensorflow binds @protubuf to the protobuf repository at workspace.bzl, while https://github.com/grpc/grpc/blob/master/WORKSPACE binds @protobuf to the build target (not the repo).  the build may fail due to name clash, the error message is something like external/protobuf does not have attribute testonly, which basically says Bazel is trying to use @protobuf as a target but in fact the name is pulled in as a repo by tensorflow, if you have a third repository and pulling in both tensorflow and grpc as external repositories.

**Comment by snnn** [comment]
Why not replace all @protobuf occurrences and remove @protobuf from WORKSPACE?
like this: https://github.com/snnn/tensorflow/commit/341bb1e207e299a942695a2db1bc823457549a29

**Comment by Shuolongbj** [comment]
thank you ! @jhseu @jart @snnn 
Upgrade gRPC (#11768)

**Pull request closed without merging**
