### PR TITLE
Exclude importing tensorflow.contrib.cloud on Windows

### PR DESCRIPTION
**Pull request by meteorcloudy**
This is a follow up to fix import error in tensorflow/contrib/__init__.py on Windows, which is caused by https://github.com/tensorflow/tensorflow/commit/654eb3dd779107eb919af1093e2a72f0ab6ba922

@gunan @case540

### CODE REVIEW

**Comment by yongtang** [comment]
The `Ubuntu Sanity` test failed in `do_bazel_nobuild`. Which is caused by
```
ERROR: Config value hdfs is not defined in any .rc file
136
137
FAIL: bazel build --nobuild --config=hdfs --config=gcp -- //tensorflow/... -//tensorflow/contrib/lite/java/demo/app/... -//tensorflow/contrib/lite/examples/android/... -//tensorflow/contrib/lite/schema/...
138
  This is due to invalid BUILD files. See lines above for details.
```

It also impact other PR's (e.g., #19534) Sanity checks as well.

Not very familiar with how CI setup so I haven't been able to find a fix yet.

**Comment by gunan** [comment]
Sanity failure is a known issue that will be fixed by the latest push soon.

**Comment by gunan** [comment]
We are also updating the google_cloud_cpp dependency. I sent a fix for their windows build and will see if the build is fixed internally later today.
Let's wait on that to see if the build is fixed with cloud component.

**Comment by gunan** [comment]
Actually it looks like we merged the build dependency change already, so merging this PR.

**Review by gunan — APPROVED** [review]

**Pull request merged**
