### PR TITLE
Create global C++/.h/.proto .clang-format

### PR DESCRIPTION
**Pull request by aaronhma**
This commit creates a .clang-format file for global C++/.h/.proto .clang-format. This code can be changed later on. This just makes the TensorFlow project simpler on the fact of code formatting.

### FORMAT OPTIONS
Style Guide: Google
The .clang-format file follows Google's style guide.

### CODE REVIEW

**Comment by gunan** [comment]
I think our problem before was, internally we have different versions of clang-tidy running. So when people ran clang-format, sometimes it may be incompatible with external clang-tidy.

@yifeif you explored this a while back. Do you know if this config captures the commonalities of internal and external clang-tidy?

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by aaronhma** [comment]
@yifeif @gunan What is the internal problem? I can fix my PR based on your suggestions.

**Comment by gunan** [comment]
The problem is while externally a "Google format" is available, we discovered that it never matches internally. So any clang-format we tried before has failed the internal checks.

**Comment by martinwicke** [comment]
We are now auto-formatting all code that is checked in. So for C++ code, whatever you do at home is fine, we'll auto-format anyway.

Using the Google style clang-format will work fine for that purpose, the differences are slight at best. 

I'd rather not check this into the repo though, because what will happen is that if you reformat code you didn't write, that'll cause larger than necessary diffs. 

For that reason, I'll close this PR. 

Thank you!

**Comment by aaronhma** [comment]
Ok, sure, no problem!

**Pull request closed without merging**
