### PR TITLE
fix a compile error of r2.1 caused by skylib address invalid.

### PR DESCRIPTION
**Pull request by rhdong**
fix a compile error of r2.1 caused by the invalid link of skylib.

### CODE REVIEW

**Comment by gbaned** [comment]
@rhdong Can you please sign CLA ? Thanks!

**Comment by mihaimaruseac** [comment]
Please sign CLA and open against master and then cherry-pick here.

If master already works, we should cherry-pick the commit fixing there.

Note that since this is against 2.1 branch we won't merge it until we need to do a patch release (for security reasons)

**Comment by rhdong** [comment]
@googlebot I fixed it.

**Comment by rhdong** [comment]
@googlebot I fixed it.

**Comment by rhdong** [comment]
@googlebot I fixed it.

**Comment by mihaimaruseac** [comment]
We can only merge this when we do a patch release on the 2.1 release

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
