### PR TITLE
Bug Fix for Relu1 graph transformation.

### PR DESCRIPTION
**Pull request by amitsrivastava78**
Fied the bug in the code and add a TC file.

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@miaout17 , i have resolved the merge conflicts and re-based the code, can you please review the PR.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@miaout17, can you please review the PR and provide your feedback.

Regards 
Amit

**Comment by amitsrivastava78** [comment]
@gbaned , i have resolved the merge conflicts @miaout17 , can you please check the PR.


Regards
Amit

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@amitsrivastava78 Could you please resolve the conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
