### PR TITLE
Track initializer in StaticVocabularyTable

### LINKED ISSUE #32770: Asset file not exported in the SavedModel when using tf.lookup.StaticVocabularyTable
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: 2.0.0rc2
- Python version: 3.6.6

**Describe the current behavior**

When using `tf.lookup.StaticVocabularyTable`, the asset file is not exported in the SavedModel assets directory. However, it is correctly saved when using `tf.lookup.StaticHashTable`.

**Describe the expected behavior**

The vocabulary file should be saved in the assets directory of the SavedModel.

**Code to reproduce the issue**

```python
import os
import shutil
import tensorflow as tf

class Model(tf.keras.layers.Layer):

    def __init__(self, vocabulary_path):
        super(Model, self).__init__()
        initializer = tf.lookup.TextFileInitializer(
            vocabulary_path,
            tf.string,
            tf.lookup.TextFileIndex.WHOLE_LINE,
            tf.int64,
            tf.lookup.TextFileIndex.LINE_NUMBER)
        self.table = tf.lookup.StaticVocabularyTable(initializer, num_oov_buckets=1)
        #self.table = tf.lookup.StaticHashTable(initializer, 0)

    def call(self, tokens):
        return self.table.lookup(tokens)

    @tf.function(input_signature=(tf.TensorSpec([None], dtype=tf.string),))
    def serve(self, tokens):
        return self(tokens)


vocabulary_path = "/tmp/vocab.txt"
with open(vocabulary_path, "w") as vocabulary_file:
    vocabulary_file.write("a\nb\nc\n")

model = Model(vocabulary_path)

export_dir = "/tmp/model"
if os.path.exists(export_dir):
    shutil.rmtree(export_dir)
tf.saved_model.save(model, export_dir, signatures=model.serve)
assets = os.listdir(os.path.join(export_dir, "assets"))
assert len(assets) == 1
```

**Other info / logs**

The code above raises an `AssertionError` as the assets directory is empty.

### PR DESCRIPTION
**Pull request by guillaumekln**
Fixes #32770.

### CODE REVIEW

**Review by alextp — CHANGES_REQUESTED** [review]
Can you add a test? It's not obvious from reading this code what bug it is fixing.

**Comment by guillaumekln** [comment]
@alextp I added a test. Thanks!

**Review by alextp — DISMISSED** [review]

**Review by alextp — APPROVED** [review]

**Comment by sandstrom** [comment]
@guillaumekln Seems like the tests got stuck, do you know how to restart? Perhaps by force-pushing nothing?

**Comment by guillaumekln** [comment]
It does not seem like the failures are related to this change.

**Comment by sandstrom** [comment]
@guillaumekln alright, either ping someone who can re-trigger the checks, or maybe force-push new commits to trigger a re-run of the checks

**Comment by guillaumekln** [comment]
Looks like other PRs marked with "ready to pull" have similar CI failures.

@gbaned Should we do something else to move forward?

**Comment by gbaned** [comment]
@guillaumekln Sorry for the slow response, it is waiting for internal approval. We will let you know if anything needed. Thank you.

**Pull request merged**
