### PR TITLE
[oneDNN] Optimize MIN_FIRST mode quantization with oneDNN

### PR DESCRIPTION
**Pull request by mdfaijul**
This PR is improves performance of MIN_FIRST mode quantization using oneDNN library.

### CODE REVIEW

**Comment by mdfaijul** [comment]
@penpornk Any update on this PR?

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Review by cantonios — APPROVED** [review]

**Review by penpornk — CHANGES_REQUESTED** [review]

**Comment by mdfaijul** [comment]
@penpornk I have addressed the comments. Thanks!

**Review by penpornk — APPROVED** [review]
Thank you!

**Review by penpornk — CHANGES_REQUESTED** [review]
The test was already failing on Windows (with just removing the `ENABLE_MKL` condition in `mkl_quantize_op_test.cc`.) Could you please help take a look?
The error message:
```
I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[       OK ] MklQuantizeV2OpTest.small_uint8 (22 ms)
[ RUN      ] MklQuantizeV2OpTest.small_int8
tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
  Actual: false (-1 not equal to -2)
Expected: true
i = 1
tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
  Actual: false (1 not equal to 3)
Expected: true
i = 2
tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
  Actual: false (-2 not equal to -4)
Expected: true
i = 3
tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
  Actual: false (-25 not equal to -49)
Expected: true
i = 4
tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
  Actual: false (-81 not equal to -128)
Expected: true
i = 6
tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
  Actual: false (-127 not equal to 0)
Expected: true
i = 0
[  FAILED  ] MklQuantizeV2OpTest.small_int8 (1 ms)
```

**Comment by mdfaijul** [comment]
> The test was already failing on Windows (with just removing the `ENABLE_MKL` condition in `mkl_quantize_op_test.cc`.) Could you please help take a look? The error message:
> 
> ```
> I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> [       OK ] MklQuantizeV2OpTest.small_uint8 (22 ms)
> [ RUN      ] MklQuantizeV2OpTest.small_int8
> tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
>   Actual: false (-1 not equal to -2)
> Expected: true
> i = 1
> tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
>   Actual: false (1 not equal to 3)
> Expected: true
> i = 2
> tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
>   Actual: false (-2 not equal to -4)
> Expected: true
> i = 3
> tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
>   Actual: false (-25 not equal to -49)
> Expected: true
> i = 4
> tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
>   Actual: false (-81 not equal to -128)
> Expected: true
> i = 6
> tensorflow/core/framework/tensor_testutil.cc(134): error: Value of: IsEqual(Tx[i], Ty[i], t)
>   Actual: false (-127 not equal to 0)
> Expected: true
> i = 0
> [  FAILED  ] MklQuantizeV2OpTest.small_int8 (1 ms)
> ```

Thanks for reporting this issue. Does it fail on windows without this PR if `ENABLE_MKL` is dropped?

**Comment by mdfaijul** [comment]
@penpornk We tried reproducing the issue on BDW/SKX/CLX with oneDNN V3.x, but we could not reproduce.

**Comment by penpornk** [comment]
> @penpornk Thanks for reporting this issue. Does it fail on windows without this PR if `ENABLE_MKL` is dropped? Also could you please mention CPU kind (Broadwell/Skylake/Cascadelake etc.) and oneDNN version.

Yes. It failed without this PR if `ENABLE_MKL` is dropped. Based on the log, the machine is a Broadwell.

@cantonios A quick fix is replace the `ENABLE_MKL` test guard with `defined(TF_PLATFORM_LINUX_X86_64)`. Would you be okay if we only run the test for Linux (and not Windows) for now?

**Comment by mdfaijul** [comment]
@cantonios I have disabled the test on Windows. Let me know if it is okay.

**Comment by cantonios** [comment]
I'd rather it be fixed on Windows.  This is an MKL-specific test.  If it fails on Windows and something is wrong, not only the test should be disabled, but also the original implementation.

**Review by penpornk — CHANGES_REQUESTED** [review]
@cantonios Sounds good.
@mdfaijul Let's disable this specific op rewrite on Windows?

**Comment by mdfaijul** [comment]
> @cantonios Sounds good. @mdfaijul Let's disable this specific op rewrite on Windows?

Thanks for the suggestions. We are evaluating the impact on Windows for disabling rewrite.

**Comment by mdfaijul** [comment]
> > @cantonios Sounds good. @mdfaijul Let's disable this specific op rewrite on Windows?
> 
> Thanks for the suggestions. We are evaluating the impact on Windows for disabling rewrite.

@penpornk We have evaluated disabling QuantizeV2 op rewrite on Windows client CPU. We observed up to 2X degradation in performance.

**Comment by cantonios** [comment]
> @penpornk We have evaluated disabling QuantizeV2 op rewrite on Windows client CPU. We observed up to 2X degradation in performance.

Thanks for investigating.  But if we can't trust the rewrite on Windows, then I'm not sure how we can justify putting it in.  We should probably disable it until we figure out why the tests are failing.

**Comment by mdfaijul** [comment]
@penpornk @cantonios I think I was able to find the issue. It looks like it is a compiler issue in Windows. A fix has been made (https://github.com/tensorflow/tensorflow/pull/56776/commits/77fc2fff3c8a2413d882fd766e7ff71fdf45a112). Please check.

I found that when `T = qint8`

- Windows: `std::is_signed<T>::value` is `false`
- Linux: `std::is_signed<T>::value` is `true`

**Comment by gbaned** [comment]
Hi @penpornk  Can you please review this PR ? Thank you!

**Comment by mihaimaruseac** [comment]
Closing stale PR

**Pull request closed without merging**
