### PR TITLE
Support string custom attributes

### PR DESCRIPTION
**Pull request by psunn**
[convert composite op to a TFLite custom operation](https://www.tensorflow.org/lite/models/convert/operation_fusion#composing_operations_in_tensorflow)
, custom attributes could be set for custom operations through `experimental_implements`:
```
def get_implements_signature():
  implements_signature = [
    # 'name' will be used as a name for the operation.
    'name: "my_custom_fused_op"',
    # attr "tfl_fusable_op" is required to be set with true value.
    'attr {key: "tfl_fusable_op" value { b: true } }',
    # Example attribute "example_option" that the op accepts.
    'attr {key: "example_option" value { i: %d } }' % 10
  ]
  return ' '.join(implements_signature)

@tf.function(experimental_implements=get_implements_signature())
def my_custom_fused_op(input_1, input_2):
```

With this pull request, we enable `string` as supported data type of custom attributes:
```
def get_implements_signature():
    implements_signature = [
        ...
        # Example string attibute "custom_attr" that the op accepts
        'attr {key: "custom_attr" value { s: "value 1.01" } }',
        ...
    ]
    return " ".join(implements_signature)

@tf.function(experimental_implements=get_implements_signature())
def my_custom_fused_op(input_1, input_2):
```

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @sagunb Can you please check @sirakiin's comments and keep us posted ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin / @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin / @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin / @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin / @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin / @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin / @zichuan-wei Can you please review this PR ? Thank you!

**Review by rascani — APPROVED** [review]

**Pull request merged**
