### PR TITLE
Fix Const op tensor_content on s390x during save/load

### PR DESCRIPTION
**Pull request by rposts**
This PR addresses swapping of  tensor_content data when Tensorflow models are saved across LE/BE systems.

Few [testcases](https://github.com/tensorflow/serving/blob/42666a18c050c47753449726f65cccc0937b75e0/tensorflow_serving/model_servers/tensorflow_model_server_test.py#L768) in Tensorflow Serving fail because they try to serve TF models that were saved on x86.  In particular, `tensor_content` field of `Const op` tensor has data stored in the native endiness format.  However, `tensor_content` field does not have a way to indicate endiness of the raw bytes that go in the `tensor_content` field.

Load and store mechanism of `saved_model` code has been modified to account for endiness when these operations are performed on LE/BE machines.  This is achieved by traversing through `meta_graph_def` proto and modifying the `tensor_content` of `Const op` tensor.

Specifically:

- In `tensorflow/python/saved_model/save.py` a function to swap `tensor_content`  is called on big-endian machine to store the bytes in little-endian format
- In `tensorflow/python/saved_model/load.py`, a reverse operation is performed to get `tensor_content` in big-endian format
- Similar changes are implemented in `tensorflow/cc/saved_model/reader.cc` to byte swap `tensor_content` 

This implementation is broadly based on the ideas from [this](https://github.com/tensorflow/tensorflow/pull/28490) PR.

### CODE REVIEW

**Review by ccrusius — CHANGES_REQUESTED** [review]
Looks good, thanks! Could we update the proto field documentation to make it explicit that we expect LE data there?

**Comment by rposts** [comment]
> 
> 
> Looks good, thanks! Could we update the proto field documenta

Thanks @ccrusius for the comments.

I assume you meant me to update description of [proto](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto) file?  One concern I have with updating it is that this field can potentially contain BE data for other use cases.  As noted [here](https://github.com/tensorflow/tensorflow/issues/41652#issuecomment-665916603) byte order of `tensor_content` is not defined and therefore documenting it explicitly to say it contains LE data may have broader ramifications.

**Review by rposts — COMMENTED** [review]
Thanks @ccrusius for the comments.

I assume you meant me to update description of [proto](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto) file?  One concern I have with updating it is that this field can potentially contain BE data for other use cases.  As noted [here](https://github.com/tensorflow/tensorflow/issues/41652#issuecomment-665916603) byte order of `tensor_content` is not defined and therefore documenting it explicitly to say it contains LE data may have broader ramifications. 

I could remove the comments from `load.py` if it is causing confusion.  Thanks.

**Comment by rposts** [comment]
@ccrusius - please let me know if further modifications are needed. Thx!

**Comment by gbaned** [comment]
@ccrusius  Any update on this PR? Please. Thanks!

**Review by ccrusius — APPROVED** [review]
Sorry for the delay - I think that's fine, we can leave the comments as is. Thanks!

**Comment by rthadur** [comment]
@rposts can you please check sanity build errors ?

**Review by rthadur — APPROVED** [review]

**Comment by rposts** [comment]
@rthadur - seems like this one has slipped through the cracks. Is there anything I need to do at my end? Tx.

**Comment by rthadur** [comment]
@rposts thanks for your patience , this PR is stuck internally , @ccrusius is working on it.

**Pull request merged**
