### PR TITLE
.numpy() was missing in code example: tf.add(1, 2).numpy()

### PR DESCRIPTION
**Pull request by stevelang789**

### CODE REVIEW

**Comment by stevelang789** [comment]
I have signed the CLA

**Comment by stevelang789** [comment]
Accidentally closed the pull request; reopening it.

**Comment by stevelang789** [comment]
Closing this PR and opening a new one as per @hgadig's suggestion.

**Comment by hgadig** [comment]
> Closing this PR and opening a new one as per @hgadig's suggestion.

Thank you. Please make sure you sign CLA

**Pull request closed without merging**
