### PR TITLE
Add test for nested batch accumulator 

### PR DESCRIPTION
**Pull request by abhichou4**

### CODE REVIEW

**Comment by allenlavoie** [comment]
What's the error / stack trace?

**Comment by abhichou4** [comment]
> What's the error / stack trace?

```
AssertionError: Tuples differ: (2,) != ()

First tuple contains 1 additional elements.
First extra element 0:
2

- (2,)
+ () : Shape mismatch: expected (2,), got () with contents -0.16209069.
```
The problem is with using `tape.gradient` afterwards. Results are as expected with `acc.jvp` (tf.Tensor([-0.0841471  -0.16829419], shape=(2,), dtype=float32)

**Comment by allenlavoie** [comment]
A scalar seems like the right shape to me, since it's a scalar (`primals`) passed as the second argument to `tape.gradient`. Note that `tape.gradient(y, x)` is equivalent to `tape.gradient(tf.reduce_sum(y), x)` (where the reduce_sum is implicitly watched on the tape). If you want a full Jacobian there's another method for that.

**Review by abhichou4 — COMMENTED** [review]
Is there a problem with using the power function here? It looks like there's a problem in tf.function definition but the error reported is incompatible shape. 
```
Traceback (most recent call last):
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/eager/forwardprop_test.py", line 1049, in testBatchNestedForward
    primal_out = primal ** 3.5
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/ops/math_ops.py", line 1139, in binary_op_wrapper
    raise e
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/ops/math_ops.py", line 1123, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/ops/math_ops.py", line 636, in pow
    return gen_math_ops._pow(x, y, name=name)
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 6656, in _pow
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/eager/forwardprop.py", line 213, in _jvp_dispatch
    return _jvp_exact_shapes(op_name, attr_tuple, inputs, outputs, tangents,
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/eager/function.py", line 2924, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/eager/function.py", line 3322, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/eager/function.py", line 3174, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/cheems/.cache/bazel/_bazel_cheems/35c71c768feb0f5b26e35cfa18cc26e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/forwardprop_test.runfiles/org_tensorflow/tensorflow/python/eager/forwardprop.py:171 _jvp_helper_wrapper  *
        raise ValueError("Tangent {} was expected to be of shape "

    ValueError: Tangent Tensor("tangents_1:0", shape=(), dtype=float32) was expected to be of shape (None,) but is instead of shape ()
```

**Comment by allenlavoie** [comment]
So the jvp function for the op runs, but something is passing a scalar? It could be related to the tf.function special casing for forwardprop. Maybe this placeholder? https://github.com/tensorflow/tensorflow/blob/247e9bd050e68fa4b055fe6c99144def3fde4e81/tensorflow/python/eager/function.py#L1005

To be clear the inner ForwardAccumulator is making a tf.function, and so the outer accumulator runs forwardprop on that function rather than op-by-op. But the test looks fine to me (until the assertions at least; is the whole thing linear in the tangent?).

**Review by allenlavoie — DISMISSED** [review]

**Comment by gbaned** [comment]
@abhichou4 Can you please address Ubuntu Sanity errors? Thanks!

**Review by allenlavoie — APPROVED** [review]

**Pull request merged**
