### PR TITLE
Dense layer that ingests both sparse and dense inputs

### PR DESCRIPTION
**Pull request by SharoneDayan**

### CODE REVIEW

**Comment by SharoneDayan** [comment]
Clear example on how I used this custom Layer in subclassing : https://medium.com/dailymotion/how-to-design-deep-learning-models-with-sparse-inputs-in-tensorflow-keras-fd5e754abec1

**Comment by rthadur** [comment]
@SharoneDayan thanks for your contribution , can you please add a test case ?

Also please add some description as why this change is needed.

**Comment by SharoneDayan** [comment]
Hello, thank you for your comment ! I create a test case file to test a model that supports this layer.
I also added a brief description. Thank you !

**Comment by qlzh727** [comment]
Adding Francois who is the api owner.

From API perspective, we don't want to have layers that is specially designed to handle certain inputs, otherwise the number of layer will be exploded.

Also, in the meantime, we are adding composite tensor support across keras, which will also handle sparse input.

**Comment by qlzh727** [comment]
Closing this PR based on the comment above. Feel free to reopen if there is any updates. Thanks.

**Comment by tanzhenyu** [comment]
The current Keras Dense layer already supports sparse tensor.

**Pull request closed without merging**
