### PR TITLE
Updating default version for building from master source.

### PR DESCRIPTION
**Pull request by av8ramit**
Making the default build from source version 1.4.0dev. The whl files that are built will be 1.3.0devDDMMYYYY.

### CODE REVIEW

**Review by drpngx — APPROVED** [review]
This seems a bit error-prone to change so many files.

**Comment by drpngx** [comment]
```
//tensorflow/python:framework_versions_test                              FAILED in 2.2s
```

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Pull request merged**
