### PR TITLE
updated installation instructions for Tensowflow-TensorRT integration

### PR DESCRIPTION
**Pull request by jjsjann123**
@aaroey @cliffwoolley @gunan

### CODE REVIEW

**Comment by tfboyd** [comment]
I will pick this up.  The markdown has a lot of HTML that should be removed.  I will prioritize getting to this in the next 48 hours and figuring out how to get it published after it is submitted.

**Comment by cliffwoolley** [comment]
Thanks @tfboyd.  There was already similar HTML moved into the MD of that page (well, except the br's), so we figured it was okay.  If you'd like to reformat to be a bit more pure on the MD, that's understandable.  Let us know if we can help.

**Review by tfboyd — APPROVED** [review]
LGTM
@cliffwoolley   Agreed, sorry for the delay a bunch of stuff came up and it is much harder to see how this will show up on tensorflow.org than it should be.  I was not looking closely enough at the original.  No idea why they did that but 100% you followed their lead and I am not super interested in trying to get to why they used so many tags. :-)  Thank you for following the format and above and beyond patience.  If this gets merged it will show up for 1.8 unless we to a cherry pick back to the 1.7 tag and ask for a rebuild of the site.  It will show up under master (as soon as they do a rebuilt and that is pretty easy) just not 1.7, which is the current default people see without selecting "version -> master".  Please do not harass me about how complicated that is.  :-)  I know first hand :-(

**Comment by jhseu** [comment]
Mind resolving the conflicts? (Should we merge this into the master branch instead?)

**Comment by tfboyd** [comment]
@jhseu  I changed to master and I think I fixed the merge conflict.  My github/git skills are not strong in this area.  There was not a conflict with the branch and I think I realize what they is kind of a mess.  Makes more sense to push it to master than to the branch if we really want that but 1.8 is very near.

**Comment by tfboyd** [comment]
Ubuntu CC seems stuck or was stuck on the last run.

**Pull request merged**
