### PR TITLE
Removed unnecessary copying of dict

### PR DESCRIPTION
**Pull request by msamogh**

### CODE REVIEW

**Comment by msamogh** [comment]
I signed it!

**Comment by caisq** [comment]
cc @ispirmustafa

**Comment by xiejw** [comment]
@ispirmustafa  the attached bug pointed you are the owner for that part. Please find the best reviewer if that's incorrect. 

I have read the code by myself and, if I read correctly, the mutating logic still exists. So, not feel safe to remove the copy here.

**Comment by msamogh** [comment]
@xiejw If I understand correctly, the concern here is that if the `features` dict is mutated somewhere, you don't want it to affect the `receiver_tensors`. Where are you saying it will be mutated?

**Comment by case540** [comment]
Please land this to master branch first and the cherry-pick it to r1.9.

**Pull request closed without merging**
