### PR TITLE
TFLM: To add Himax WE1 EVB examples

### PR DESCRIPTION
**Pull request by CKHSUinHimax**
This pull request adds support magic wand and micro speech examples on Himax WE1 EVB

### CODE REVIEW

**Comment by bigcat-himax** [comment]
@googlebot I consent.

**Review by petewarden — CHANGES_REQUESTED** [review]
Can you remove the animation GIF file? It's 1MB, which is too large for this repo. Hopefully you can host it on a different server and use that URL instead?

**Comment by bigcat-himax** [comment]
> Can you remove the animation GIF file? It's 1MB, which is too large for this repo. Hopefully you can host it on a different server and use that URL instead?

Thanks for the suggestion, GIF now use an external link.

**Comment by gbaned** [comment]
@CKHSUinHimax Can you please resolve conflicts? Thanks!

**Review by petewarden — APPROVED** [review]

**Pull request merged**
