### PR TITLE
Update to monitors and tutorial

### PR DESCRIPTION
**Pull request by alanyee**
-Removed tf.learn.SessionRunHook in favor of tf.train.SessionRunHook.
-Remove unnecessary slash in tutorial

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]
Thanks!

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (28/25 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:37799)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-e6d9-mazecreator=mazecreator.com@sgmail.github.com>)
	id 1ddIPr-00006l-LO
	for mazecreator@mazecreator.com; Thu, 03 Aug 2017 10:52:33 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=K/1KJk/gYUgph4QuocVrnYukE6U=; b=nRrzh42Qbi5V2onH
	/CcL/ntCUVHxAky7DQ0t5Cwbj393hQQRLVKmfWfHr3x18IgGVbIO6pG8xpXxaBcd
	FYuhTUxo8sQiiKTRlHGqcJVXrVKX3N6k00vQlQrQERbeD0k/IesxF+8E56sEXI6/
	A725T9yA/8ZkQA/jI6fszAeOH7o=
Received: by filter0997p1mdw1.sendgrid.net with SMTP id filter0997p1mdw1-19761-5983490A-AB
        2017-08-03 16:02:18.769481858 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id LeXJ5kGyTme6Hda6Hdkhvw
	for <mazecreator@mazecreator.com>; Thu, 03 Aug 2017 16:02:18.767 +0000 (UTC)
Date: Thu, 03 Aug 2017 16:02:21 +0000 (UTC)

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (29/25 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:31975)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-e6d9-mazecreator=mazecreator.com@sgmail.github.com>)
	id 1ddIQB-00008t-8Q
	for mazecreator@mazecreator.com; Thu, 03 Aug 2017 10:52:53 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=AknbOaAdHdM3hcb3muwLpI+jfaU=; b=EN6DGqTD2VETz2Qv
	hU1S/vfKo40JJK+klSuGiajTI1fJbLKLKFLHSdkQov7ZVOvKc79Y0C3NWrKIZV8h
	d9gSF4qXIkql5n12gfxnK1u/oE3+TNz4+UYKv2vEwnekjuypsTzqCjm4/VqyQ7DS
	e74RedupdxfjucYr+twyfVJEGoA=
Received: by filter0491p1mdw1.sendgrid.net with SMTP id filter0491p1mdw1-13711-598348DB-26
        2017-08-03 16:01:31.251338081 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id aO2qSTPeRaibpIF_aLlmEg
	for <mazecreator@mazecreator.com>; Thu, 03 Aug 2017 16:01:31.244 +0000 (UTC)
Date: Thu, 03 Aug 2017 16:02:58 +0000 (UTC)

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
