### PR TITLE
[oneDNN] Enable mkl_remapper_test for stock tf

### PR DESCRIPTION
**Pull request by gaurides**
This test was earlier enabled only when TF is built with --config=mkl and hence didn't execute for stock TF. Due to which some issues were missed.
For this test to run, one either had to build with config=mkl or remove the compile check "defined(ENABLE_MKL)" temporarily.
With the changes in this PR, the tests are enabled in stock TF and it will help to catch any issues sooner. 
This PR only affects MKL related tests and skip the tests when running without MKL, thus no impact otherwise.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @ezhulenev Can you please review this PR ? Thank you!

**Review by ezhulenev — APPROVED** [review]

**Review by penpornk — CHANGES_REQUESTED** [review]
Could you please take a look at [Ubuntu CPU failure](https://source.cloud.google.com/results/invocations/563b99ad-8e20-4832-827f-fe90ff11b96c/log)? Thank you!
```
[ RUN      ] MklRemapperConv2dBiasAddSwishTest.F32
tensorflow/core/grappler/optimizers/mkl_remapper_test.cc:1022: Failure
Expected equality of these values:
  node.name()
    Which is: "bias_add"
  "activation"
tensorflow/core/grappler/optimizers/mkl_remapper_test.cc:1023: Failure
Expected equality of these values:
  fused_ops.size()
    Which is: 1
  2
[  FAILED  ] MklRemapperConv2dBiasAddSwishTest.F32 (350 ms)
...
```

**Comment by gaurides** [comment]
@penpornk - i made changes "Py+CPP Test Suite - Ubuntu GPU, Python 3.9" public tests are passing now. But I can't see the failures in the "Internal CI build failed"

**Comment by penpornk** [comment]
@gaurides Thank you! PY+CPP Ubuntu CPU says it's still [failing](https://source.cloud.google.com/results/invocations/0f163039-400c-4ba0-b19d-546e136d1e22/log) though.

**Comment by gaurides** [comment]
@penpornk - i fixed the failing tests. Can you please take a look? Thanks!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gaurides** [comment]
@penpornk - can you please take a look at this PR too? I fixed the earlier issue. Thanks.

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gaurides** [comment]
@penpornk - please let me know if there's something I can do for this PR.

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gaurides** [comment]
@gbaned @penpornk - i resolved the merge conflicts. Can you please review this PR?

**Comment by gaurides** [comment]
@cantonios - Can you please review this PR? Thanks!

**Review by cantonios — APPROVED** [review]

**Comment by gaurides** [comment]
@cantonios - I checked the failing jobs results (except the internal), they don't look related to this change. Please let me know if i need to update/fix something.

**Comment by cantonios** [comment]
> @cantonios - I checked the failing jobs results (except the internal), they don't look related to this change. Please let me know if i need to update/fix something.

It is your change - the mlk_remapper_test is failing no Windows.  e.g.
```
[ RUN      ] FusedConvBiasAddAndHardSwishTest.Bfloat16Conv2DBiasHardSwish
tensorflow/core/grappler/optimizers/mkl_remapper_test.cc(1646): error: Expected equality of these values:
  "_FusedConv2D"
  node.op()
    Which is: "Mul"
tensorflow/core/grappler/optimizers/mkl_remapper_test.cc(1648): error: Expected equality of these values:
  "input"
  node.input(0)
    Which is: "mul_one_sixth"
tensorflow/core/grappler/optimizers/mkl_remapper_test.cc(1649): error: Expected equality of these values:
  "filter"
  node.input(1)
    Which is: "relu_6"
```

**Comment by gaurides** [comment]
I fixed the failing test. I hadn't merged master branch recently. Some additional tests got added that needed update.

**Review by cantonios — APPROVED** [review]

**Review by cantonios — APPROVED** [review]

**Comment by gaurides** [comment]
sorry, i had 1 fix from windows test, it didn't show here.

**Review by cantonios — APPROVED** [review]

**Comment by gbaned** [comment]
Seems auto-merge is not happening but the changes are merged into master branch now, so closing this PR. Thank you!

**Pull request closed without merging**
