### PR TITLE
Upgrade to protobuf 3.3.1

### PR DESCRIPTION
**Pull request by jhseu**
(Haven't tested, letting Jenkins try it out)

### CODE REVIEW

**Comment by jhseu** [comment]
Jenkins, test this please

**Review by jart — APPROVED** [review]

**Comment by martinwicke** [comment]
Does this have implications on our installation instructions, the pip package dependencies, or other documentation?

**Comment by jhseu** [comment]
It should be ok to update the build dependency without updating the pip) runtime dependency. They're used for two different purposes right now.

pip tests would also catch any issues.

**Comment by martinwicke** [comment]
different purposes? So using two different protobufs in different parts of the code isn't a problem?

**Comment by jhseu** [comment]
Yeah, the interaction points only test wire-compatibility, which is guaranteed by protobuf. The different versions only occur when serialization happens in the Python runtime (the pip version) and it's deserialized in TF core (bazel version in pywrap_tensorflow).

**Comment by jart** [comment]
Good catch @martinwicke. OOC is there any reason why we _wouldn't_ want to bump our setup.py protobuf dependency from 3.2.0 -> 3.3.1? Purely for the sake of consistency?

Our Python code probably depends on `@com_google_protobuf//:python_srcs` somehow, for things like `from google.protobuf import json_format`. There's been changes to their Python API since 3.2.0 and probably other subtleties we haven't considered.

**Comment by martinwicke** [comment]
Let's update the pip dependency as well. I think Jonathan is right and it
won't be a problem. But consistency is nice.

**Comment by jhseu** [comment]
Bumped all protobuf versions throughout. pypi doesn't have 3.3.1 yet, so depended on 3.3.0 instead.

**Comment by jart** [comment]
LGTM. Thanks @jhseu.

**Comment by jhseu** [comment]
Also had to downgrade some other spots to 3.3.0: only source is available for 3.3.1. The prebuilt protoc binary is not available.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Pull request merged**
