### PR TITLE
Hard-coded bash path

### PR DESCRIPTION
**Pull request by iblislin**
Changed '#!/bin/bash' to '#!/usr/bin/env bash'.
There do not exist bash in most Unix system, like bsd family.

### CODE REVIEW

**Comment by iblis17** [comment]
I signed it!

**Comment by jendap** [comment]
@tensorflow-jenkins test this please

**Comment by jendap** [comment]
The Linux CPU test has failed //tensorflow/tools/docs:gen_docs_test. @iblis17 can you fix it please?

**Comment by iblis17** [comment]
Hi @jendap 
Please test it again, tnx!

**Comment by jendap** [comment]
@tensorflow-jenkins test this please

**Comment by jendap** [comment]
LGTM, thank you @iblis17

**Pull request merged**
