### PR TITLE
Added a library to convert TensorFlow GraphDef to XLA SessionModule.

### PR DESCRIPTION
**Pull request by keveman**
I have only added the minimal code without lot of comments. I wanted to make sure this approach is acceptable. I have made the xlagen library public, so a python library can be built externally by using TensorFlow as a submodule. Please let me know if this is acceptable and I will spruce up the PR with more documentation, comments, and tests.

### CODE REVIEW

**Comment by keveman** [comment]
This approach may not be as tenable as I originally anticipated. Even with this in contrib, it is still hard to make use of it from another project that uses TensorFlow as a (git) submodule, and swig wrap it. This is mostly because of the build system, and swig wrapping this causes symbol collisions with tensorflow (can't import tensorflow and this library together). Please let me know what the best way forward for making it easy to extract XLA graphs from GraphDefs in Python.

**Comment by jmchen-g** [comment]
Adding myself :)

**Comment by tatatodd** [comment]
Hi Manjunath!

FYI you might be interested in the following code in contrib, which looks like it does what you want:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/xla_tf_graph/xla_tf_graph_util.h#L62

I don't think I understand the Python / swig-wrapping issues.  Perhaps you can open a bug to discuss that further, if the problem still exists with the existing contrib code?

**Comment by keveman** [comment]
Thanks @tatatodd for the response. I did notice that code before I embarked on this. However, we wanted to be able to call this from Python, so I needed going from GraphDef -> SessionModule. Actually, the better piece of code that I can reuse is a combination of `InitGraph` and `CompileGraph` in your https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/aot/compile.h. Also, the BUILD visibility of the various components is not suitable for making tensorflow a git submodule under a different project. Here is what would be ideal for our (Cerebras) use case:

    with tf.Graph().as_default() as g:
      a = tf.placeholder(tf.int32, shape=[2, 2])
      b = tf.placeholder(tf.int32, shape=[2])
      c = tf.add(a, b, name="c")
    # xla_graph would be a xla::SessionModule
    xla_graph = tf2xla.GraphDefToXla(g.as_graph_def(), ["c:0"])

Now, `tf2xla` can be something that we build on our own using the stock `tensorflow` repo as a git submodule, or if you think this is going to be more generally useful, this can be in `tf` module itself. The former would require changing the visibility of some of the libraries to `//visibility:public`. Either way, I am willing to do the necessary work. But please let me know what you think the best approach is.

**Comment by keveman** [comment]
Closing this, will make do with a fork for now.

**Pull request closed without merging**
