### PR TITLE
Rewrite matrix_set_diag GPU kernel.

### PR DESCRIPTION
**Pull request by gunan**
Base new implementation on matrix_diag_op.

### CODE REVIEW

**Comment by gunan** [comment]
Rasmus, I am now going to test this on windows. please feel free to throw this PR out if there should be a better way to implement this.

**Comment by gunan** [comment]
Running windows GPU tests here:
http://ci.tensorflow.org/view/Experimental/job/tf-win-gpu/3/

Hopefully, by tomorrow morning we will have a result.

**Comment by gunan** [comment]
Still fails on windows. Not sure what is missing.

**Comment by rmlarsen** [comment]
As discussed, this is not the right direction to go.

**Comment by rmlarsen** [comment]
Instead, I recommend using the recent rewrite of matrix_band_part as a template. Getting rid of the Eigen generator mechanism makes the code more readable and much faster.

**Pull request closed without merging**
