### PR TITLE
Add assert condition to clip_by_value

### LINKED ISSUE #57151: tf.clip_by_value allows clip_value_min greater than clip_value_max
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF2.4

### Custom Code

Yes

### OS Platform and Distribution

win11

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current Behaviour?

```shell
When clip_value_min is greater than clip_value_max, the snippet code works but behaves abnormally. I think it should throw exception or add an example in documentation to illustrate what will happen when clip_value_min > clip_value_max.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
results={}
try:
  arg_0 = tf.random.uniform([2, 3], maxval=10, dtype=tf.float32)
  print(arg_0)
  '''
  arg_0 = tf.Tensor(
[[4.7769785  0.57591677 4.4995    ]
 [0.93842626 4.697542   2.146771  ]], shape=(2, 3), dtype=float32)
  '''
  clip_value_min = 1
  clip_value_max = -1
  results["res"] = tf.clip_by_value(arg_0,clip_value_min=clip_value_min,clip_value_max=clip_value_max,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
'''
  results = {'res': <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>}
'''
```

### Relevant log output

_No response_</details>

### PR DESCRIPTION
**Pull request by sachinprasadhs**
Added assert condition to check the clip_value_max is greater or equal to the clip_value_min.
Fixes: https://github.com/tensorflow/tensorflow/issues/57151

### CODE REVIEW

**Comment by rohan100jain** [comment]
Unfortunately, assert ops are quite bad in distributed execution as they unnecessarily create performance barriers. There is a TODO in the code to use gen_math_ops.clip_by_value. Might be better to make this check in the kernel?

**Comment by cantonios** [comment]
We would also need to update the documentation to state that the op asserts.  Currently it only [says:](https://www.tensorflow.org/api_docs/python/tf/clip_by_value)

> Note: clip_value_min needs to be smaller or equal to clip_value_max for correct results.

**Comment by gbaned** [comment]
@sachinprasadhs Can you please check @rohan100jain's @cantonios's comments and keep us posted ? Thank you!

**Comment by gbaned** [comment]
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

**Review by cantonios — CHANGES_REQUESTED** [review]
See the other comment - remove the assert from python.  If we need to assert, we can do so from the kernel.  Otherwise, it's always better not to fail.

**Comment by gbaned** [comment]
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

**Pull request closed without merging**
