### PR TITLE
Fix for #12537

### PR DESCRIPTION
**Pull request by jzju**
I have built the fix on x86 linux no gpu and it's working.

There are some android specific code in logging that I ignored.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/logging.cc#L35-L75

### CODE REVIEW

**Comment by JohanJu** [comment]
I signed it!

**Comment by vrv** [comment]
I am going to defer to API review first, and possibly someone else who works on TF core team should be a real reviewer.

**Comment by vrv** [comment]
The concerns I have are; API bloat, and internally our logging infrastructure under the LOG macros do a lot of extra helpful things relevant to Google-infrastructure that std:cerr would lose.  I don't know how to rectify these things easily, even though I like the spirit of your change.

Perhaps this is a candidate for a custom op; it's not clear that we can make "Print" work generically for all environments in the world, and trying will just make Print more complicated than it needs to be.

**Comment by JohanJu** [comment]
Another solution would be to have an environment variable like TF_CPP_MIN_LOG_LEVEL that modifies the underlying fprintf https://github.com/tensorflow/tensorflow/blob/4ad12049d0c93155a8137b7d656136885335374b/tensorflow/core/platform/default/logging.cc#L88-L91

Also is it a bug or feature that TF_CPP_MIN_LOG_LEVEL also disables tf.Print?

**Comment by vrv** [comment]
@asimshankar and I chatted offline, there may be a simpler solution to this, but he'll have to pass it by the API review folks first.

It's a feature to allow users to completely disable all logging via LOG(INFO), and perhaps a bug that tf.Print uses LOG(INFO) in the OSS build.

**Comment by asimshankar** [comment]
@JohanJu : Thanks for the contribution. We feel that instead of adding a new API, it might be okay to just change the implementation of the `Print` kernel to always use `std::cerr` instead of `LOG(INFO)`.

Thoughts?

**Comment by JohanJu** [comment]
@asimshankar This is my first PR so I will just follow your lead, It won't be any problem the Google-infrastructure angel that @vrv talked about?

**Comment by asimshankar** [comment]
@JohanJu : I think it is fine, @vrv 's concerns are valid, but I believe we have a workaround to integrate better with our internal logging system.

For now I'd stick with `std::cerr`, since the current behavior with `LOG(INFO)` is to write to stderr as well (IIUC).

Thanks very much!

**Review by asimshankar — APPROVED** [review]
Thanks!

**Pull request merged**
