### PR TITLE
[tfgan] Add possibility to export GANEstimator saved model

### PR DESCRIPTION
**Pull request by lgeiger**
This allows GANEstimator's to be easily exported via [`GANEstimator::export_saved_model()`](https://www.tensorflow.org/api_docs/python/tf/contrib/gan/estimator/GANEstimator#export_savedmodel).

Currently when trying to when trying to export the model, `.export_saved_model()` raises:
```python-traceback
ValueError: export_outputs must be a dict and not<class 'NoneType'>
```

Fixes https://stackoverflow.com/questions/48448431/tensorflow-tfgan-ganestimator-export-model

### CODE REVIEW

**Comment by mr-ubik** [comment]
I have stumbled upon this limitation too.

**Comment by lgeiger** [comment]
@joel-shor Friendly ping 😉 

Are we able to get this reviewed before tf 1.9 is out, since this PR is somewhere in between a feature and a bug fix?

**Review by joel-shor — DISMISSED** [review]

**Comment by AndrewLeach** [comment]
The test fails because spec.expor_output.keys() also includes the default key "serving_default".

From estimator.export_savedmodel:

>     The exported `MetaGraphDef` will provide one `SignatureDef` for each
>     element of the export_outputs dict returned from the model_fn, named using
>     the same keys.  One of these keys is always
>     signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY, indicating which
>     signature will be served when a serving request does not specify one.
>     For each signature, the outputs are provided by the corresponding
>     `ExportOutput`s, and the inputs are always the input receivers provided by
>     the serving_input_receiver_fn.

Note that signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY is "serving_default".
[https://github.com/tensorflow/tensorflow/blob/57031c7565fe996270bafdd1940d50c37be35d04/tensorflow/python/saved_model/signature_constants.py](url)

Maybe this should be imported in the test and the constant included in the assertion?

**Comment by lgeiger** [comment]
@case540 @AndrewLeach Thanks for the help. I added the default serving key to the test.

Sorry for pushing a failing unit test. I still didn't found time to build tensorflow from source on my machine so I'm unable to run the test suite locally for now. Since this is only a small python fix I'm using   this as a patch on top of tf@1.8 installed via pip for my work.

> Also, in response to your previous comment, I think this will be too late to make it into TF 1.9 release

Sure no problem 👍

**Comment by AndrewLeach** [comment]
@lgeiger Thanks for adding the feature!
@joel-shor Looks like it should be good to go, would be awesome to get this merged soon :D

**Review by joel-shor — APPROVED** [review]

**Pull request merged**
