### PR TITLE
Off-by-one-error in shapes table doc

### PR DESCRIPTION
**Pull request by naveensundarg**
A rank n tensor's shapes should be [D0, D1, ..., Dn-1]

### CODE REVIEW

**Comment by josh11b** [comment]
(We are waiting for the CLA before proceeding.)

**Comment by naveensundarg** [comment]
I signed it!

**Comment by josh11b** [comment]
There are 2 diffs in that file, but I can't see what has changed in the second.  Is it a whitespace-only change?

**Comment by naveensundarg** [comment]
Yes. Did not change anything in (or around) the second diff.  Clicking on "rich diff" removes the second change. (Possible bug in the Github UI/Github Editor?)

https://github.com/tensorflow/tensorflow/pull/805/files?diff=split&short_path=6f0a487#diff-6f0a4870f1edfecc7868242cc8c4c426

**Comment by josh11b** [comment]
LGTM

**Comment by martinwicke** [comment]
merged.

**Pull request closed without merging**
