### PR TITLE
Adding approach to fix the issue with tf.tile call

### PR DESCRIPTION
**Pull request by saloni346**
this PR is trying to solve the issue listed here : https://github.com/tensorflow/tensorflow/issues/58002

### CODE REVIEW

**Comment by saloni346** [comment]
Hi @cantonios, this is not worthy of a complete PR. I have just added some bunch of comments describing the approach. I am new to this source code, so need your handholding for a while. Some questions:
1. Can you share some example code where we have changed the Shape from one dimension to another?
2. Which functions can help me prepend the entries to the multiples shape data structure?
3. Where do I have to write the tests for it?
4. Why the above cla/google and AMD ROCm is failing?
Please, help me out whenever free.

**Comment by gbaned** [comment]
@saloni346 Can you please sign CLA. Thank you!

**Comment by cantonios** [comment]
> 1. Can you share some example code where we have changed the Shape from one dimension to another?
> 2. Which functions can help me prepend the entries to the multiples shape data structure?

For the `multiples` data, we don't really expect it to be very big (the max size is governed by the max number of dimensions we support, which is usually around 6 or 7... looks like 7 for this op by scanning below in the [tile_ops.cc](https://github.com/tensorflow/tensorflow/blob/da55f2228f3279495dd689bd5514d8ec7a78da3b/tensorflow/core/kernels/tile_ops.cc#L534) file for gradients).  This gets passed around as an `ArraySlice` that is created [here](https://github.com/tensorflow/tensorflow/blob/da55f2228f3279495dd689bd5514d8ec7a78da3b/tensorflow/core/kernels/tile_ops.cc#L185).  If there is a size mismatch, we can probably just copy this to an `std::vector`, and prepend ones to that.

For the input tensor, you will need to use the Eigen tensor `.reshape( )` function.  That accepts an `std::array` (or `Eigen::DSizes` or similar) of new sizes.  Since we need to have a fixed known number of dimensions, you'll need to break it up into cases of output sizes 0 - 7.  There's an example in [`tile_ops_impl.h`](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/kernels/tile_ops_impl.h#L64) that uses `.reshape()`.

> 3. Where do I have to write the tests for it?

Most tests go through python testing.  Looks like we don't have great testing for `tf.tile` currently. The python tests are generally [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/array_ops/array_ops_test.py) for array ops, unless there are a sufficient number of tests for the op to warrant breaking it out into its own file.

> 4. Why the above cla/google and AMD ROCm is failing?

You should be able to click on the "Details" to find out, but it looks like an unrelated configuration error
> Package 'python-pip' has no installation candidate

ROCm probably updated their docker images and we haven't caught up.  It's not a blocking failure, so I wouldn't worry about it atm.

**Comment by cantonios** [comment]
> * can you tell me the steps or point me to the right documentation from where I can know how to compile my changes in my local system?

https://www.tensorflow.org/install/source

> * I have tried to update my signature on the CLA form but it still showing failed. please let me know where might be the issue?

https://github.com/tensorflow/tensorflow/pull/58422/checks?check_run_id=9261642567

**Comment by gbaned** [comment]
@saloni346 Can you please check @cantonios's comments and keep us posted ? Thank you!

**Comment by gbaned** [comment]
@saloni346 Any update on this PR? Please. Thank you!

**Comment by cantonios** [comment]
Let's close this for now.  It looks like there has been no progress, and the current change isn't yet meaningful.

Please re-open when you have something working.

**Pull request closed without merging**
