### PR TITLE
TensorFlow for .NET / C#

### PR DESCRIPTION
**Pull request by Oceania2018**
Provides a .NET Standard binding for TensorFlow. It aims to implement the complete Tensorflow API in C# which allows .NET developers to develop, train and deploy Machine Learning models with the cross-platform .NET Standard framework.

### CODE REVIEW

**Comment by 13653415686** [comment]
加油，支持大佬。

**Comment by 13653415686** [comment]
> Provides a .NET Standard binding for TensorFlow. It aims to implement the complete Tensorflow API in C# which allows .NET developers to develop, train and deploy Machine Learning models with the cross-platform .NET Standard framework.

yes，

**Comment by ElderJames** [comment]
Great!

**Comment by 13653415686** [comment]
yes，support

**Comment by Jiuyong** [comment]
TensorFlow has not forgotten that there are 6 million .NET developers in the world.

**Comment by pepure** [comment]
I am a machine vision developer in the industrial field. At present, it is very convenient to use tensorflow for development, but there are many difficulties in the production line deployment, mainly the compatibility between Python and the  existing .Net platform. Generally, the system environment of the industrial production site is difficult to change, so if there is tensorflow under the .Net platform（especially C#）, it's very convenient!

**Comment by MarkDaoust** [comment]
Hi @Oceania2018,

This doesn't really belong in the tensorflow/tensorflow repository: docs are in the [tensorflow/docs](https://github.comn/tensorflow/docs)

We have a link to this on the tensorflow.org/api_docs page, from here: https://github.com/tensorflow/docs/tree/master/site/en/api_docs

We'll see if we can do more than that, but can we continue this conversation over on tensorflow/docs?

**Comment by Oceania2018** [comment]
@MarkDaoust Appricate for you quick response. Maybe I could tell more specific reason why we need this kind of folder.
* .NET binding will complete most of the key functions act like python binding.
* .NET binding will add more custimized APIs in the `cswrap_tfe.h`, making changes in the seperate folder will reduce the main repo's risk.
* .NET binding will contains two parts, one is C++ exported functions in `tensorflow` repo, another one is C# code in `tensorflow.net` repo.

image

**Comment by MarkDaoust** [comment]
@Oceania2018

Thanks for the context, but I think I'm still missing some. 

This sounds like a big plan, are you discussing this plan with the TensorFlow team? Is there an RFC for this or something? Or is this PR the start of that conversation?

**Comment by Oceania2018** [comment]
@MarkDaoust Right, I consider this PR as an initial converstaion. Because I've no idea how to communicate with the TensorFlow team. No clue how to make this plan happen. Is there any docs related to add new language binding in the repo? I'm the key contributor for [TensorFlow.NET](https://github.com/SciSharp/TensorFlow.NET). Our goal is making tensorflow more friendly to .NET developers.

BTW, we really need mentor to guide how to collaborate with tensorflow team in terms of code standards and so on.

**Comment by MarkDaoust** [comment]
Then I think the place you want to start is with the [tensorflow/community](https://github.com/tensorflow/community/) repository.

For significant changes to core tensorflow we have the conversations as RFCs in that repository.
But you may want to look into creating a SIG also in [tensorflow/community](https://github.com/tensorflow/community/).

@joanafilipa @ewilderj: what would be the next step here?

**Comment by MarkDaoust** [comment]
Before diving in and writing a full proposal or anything big, maybe open an issue there describing your plans, and they may be able to advise.

**Comment by Oceania2018** [comment]
@MarkDaoust Do you think https://github.com/SciSharp/TensorFlow.NET/issues/529 is making sense?

**Comment by MarkDaoust** [comment]
If there's interest (there seems to be) I would look into making a SIG.

But I'm expecting it to be hard, or impossible to get anything significant into the core TensorFlow repo.
TensorFlow's been trying to split up into smaller parts wherever possible.

`java`, for example is in the process of moving out into a [repo owned by sig-jvm](https://github.com/tensorflow/java).

So I expect that route to meet less resistance.

**Comment by Oceania2018** [comment]
That would be great if there is a repo https://github.com/tensorflow/csharp

**Comment by halukmy** [comment]
@Oceania2018  he is one of best developer, one of best programming language, so make him help @google-admin

**Comment by GeorgeS2019** [comment]
@MarkDaoust => @Oceania2018  has demonstrated on his twitter site that using Csharp binding on Windows, tensorflow 2.2 is faster than the version running through python. 

We need tensorflow.dll both CPU and GPU for windows to stay commitment.

**Comment by GeorgeS2019** [comment]
Latest [tensorflow.dll ](https://github.com/tensorflow/tensorflow/issues/35405#issuecomment-653621878)for c# api

**Pull request closed without merging**
