### PR TITLE
Replace expunge with expunge_async in bazel clean

### PR DESCRIPTION
**Pull request by Randl**
https://github.com/tensorflow/tensorflow/issues/5357

### CODE REVIEW

**Comment by Randl** [comment]
Signed CLA

**Comment by drpngx** [comment]
@jart, related to #5253.

**Comment by damienmg** [comment]
This change might be problematic (generate some race conditions), and is not solving the underlying problem.

**Comment by vrv** [comment]
Thanks @damienmg. I'll close this and we should either follow up on the referenced bug, or at bazelbuild/bazel, since this is more about bazel?

**Pull request closed without merging**
