### PR TITLE
Disable the gradients test for python3 entirely. [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by av8ramit**

### CODE REVIEW

**Comment by gunan** [comment]
Could you retry running this test after pinning our protobuf version to what it would have been during 1.6 release?
I at least would like to isolate the issue we are seeing.

**Comment by rmlarsen** [comment]
This sounds scary. What is your plan for re-enabling the tests. We cannot just disable tests when convenient. They are there for a reason.

**Comment by av8ramit** [comment]
@rmlarsen I am not merging this PR yet. I was just trying to prove my point that Python3.4 might be to blame for this on the 1.6 branch. I've added a DO NOT MERGE tag to be safe.

**Comment by av8ramit** [comment]
Fixed it.

**Pull request closed without merging**
