### PR TITLE
Branch 154885009

### PR DESCRIPTION
**Pull request by vrv**

### CODE REVIEW

**Comment by vrv** [comment]
Everything passing except for Android Demo app, going to try again and see if it's consistent.  If android passes quickly, I'll merge.

@tensorflow-jenkins test this please

**Comment by vrv** [comment]
cc @caisq or @yifeif if they have any idea why the Android build is failing with

```
18:05:18 INFO: Loading package: tensorflow/c
18:05:18 ERROR: /workspace/tensorflow/core/BUILD:1363:1: in cmd attribute of genrule rule //tensorflow/core:version_info_gen: $(PYTHON_BIN_PATH) not defined. Since this rule was created by the macro 'tf_version_info_genrule', the error might have been caused by the macro implementation in /workspace/tensorflow/tensorflow.bzl:1188:7.
18:05:18 ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted.
18:05:18 INFO: Elapsed time: 2.669s
```

The only likely culprit is the .bazel.rc commit, but I can't see why that would cause this to fail.

**Comment by caisq** [comment]
Is it related to this PR? #9547

**Comment by vrv** [comment]
Maybe, but that PR passed before. @andrewharp thinks it is related to stand alone strategy

**Comment by vrv** [comment]
Going to try to revert 50aff7a2735ac595199abb67f4c96fa39193007c for now so we can make progress, and then let someone else figure out how to get around this sandboxing issue.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
