### PR TITLE
Usage example for tf.linalg.det()

### PR DESCRIPTION
**Pull request by abhayKashyap03**

### CODE REVIEW

**Comment by abhayKashyap03** [comment]
@googlebot I signed it!

**Comment by abhayKashyap03** [comment]
Hey, could anybody please review this?
This was a GCI task and I need to complete it and move on to the next task ASAP....

**Comment by yashk2810** [comment]
Can you delete the notebook and add the example to the docstring of that function?

See https://www.tensorflow.org/community/contribute/docs_ref for writing docstrings.

**Comment by abhayKashyap03** [comment]
I couldn't find the docstring for that function, would it be okay if I wrote the docstring again and submitted or could you tell me its location?

**Comment by yashk2810** [comment]
The location: https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/core/api_def/base_api/api_def_MatrixDeterminant.pbtxt

**Comment by abhayKashyap03** [comment]
Hey, I've created another PR, could you review that please?
https://github.com/tensorflow/tensorflow/pull/35457

**Comment by abhayKashyap03** [comment]
I deleted this repo and created a new one and made a PR from that one.

**Comment by abhayKashyap03** [comment]
@yashk2810

**Pull request closed without merging**
