### PR TITLE
Fix sourceforge links for TF external dependencies.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Comment by gunan** [comment]
tensorflow/tensorboard/backend:server_test  flaked.
Jenkins, test this please.

**Review by caisq — APPROVED** [review]

**Comment by snnn** [comment]
Why rollback this change? ufpr.dl.sourceforge.net is not reachable again.

**Comment by martinwicke** [comment]
Actually this change seems to have been clobbered by a bad merge. 

We have some redundancy now though, and we mirror the package and shouldn't need the sourceforge server at all. Do you see issues with it?

**Comment by snnn** [comment]
@martinwicke , Yes, it broke the cmake build.  Later on, it was fixed by 6446895aa6e35b88c0344ac1f976b06826617cbb

**Pull request merged**
