### PR TITLE
Document undocumented ops in check_ops.py

### PR DESCRIPTION
**Pull request by frreiss**
This PR adds API documentation for two public functions in `check_ops.py` that were previously undocumented.

I've generated and reviewed the Markdown files for the documentation after these changes.

### CODE REVIEW

**Review by MarkDaoust — DISMISSED** [review]

**Comment by frreiss** [comment]
Hmm, something appears to have gone wrong with the CI server. @MarkDaoust, would you mind triggering the CI builds again?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @wt-huang: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by hgadig** [comment]
@frreiss  Can you please run clang-format on your code.

**Comment by frreiss** [comment]
> @frreiss Can you please run clang-format on your code.

`clang-format` doesn't seem to have settings for Python. I tried running my modified copy of `check_ops.py` through `yapf`, but the formatter didn't change any of the lines that I modified in this PR. Can you provide more information about the formatting issue?

**Comment by hgadig** [comment]
@frreiss  please rebase the PR to resolve the merge conflict, so that I can run the test for this PR again.

**Comment by hgadig** [comment]
@MarkDaoust -  The merging conflicts have been resolved and could you please approve or suggest changes(if required).

**Review by MarkDaoust — APPROVED** [review]

**Pull request merged**
