### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by samikama**
This PR updates Readme file with instructions to help installation of external packages.

### CODE REVIEW

**Comment by samikama** [comment]
Tagging @gunan and @aaroey

**Comment by yifeif** [comment]
cc @MarkDaoust

**Comment by MarkDaoust** [comment]
@gunan - README.md files don't get pulled into tensorflow.org, it only has to render on github so there are no site-compatibility issues to worry about (LGTM).

**Review by gunan — APPROVED** [review]

**Review by aaroey — APPROVED** [review]

**Comment by aaroey** [comment]
Hi @gunan, who is going to merge this?

**Comment by yifeif** [comment]
I can bring everything back to master. I will wait for #17772 to get in.

**Comment by aaroey** [comment]
Thanks @yifeif !

**Pull request merged**
