### PR TITLE
Update math_ops.py

### PR DESCRIPTION
**Pull request by Cyberface**
Add a new exit clause to tf.cast as discussed in this issue https://github.com/tensorflow/tensorflow/issues/44844

If the input is not a Tensor then simply return tf.convert_to_tensor.

### CODE REVIEW

**Comment by Cyberface** [comment]
@googlebot I signed it!

**Review by bhack — CHANGES_REQUESTED** [review]
I think you need to add a test case that cover the original ISSUE of your ticket.
Also It seems that you need to cover also the original TODO part with a new test:
> but that
      # allows some conversions that cast() can't do, e.g. casting numbers to
      # strings.

**Comment by Cyberface** [comment]
I'm not sure how to add a test. Should I add something to here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/cast_op_test.py

For the TODO part. Do you have something in mind? Is there a preferred way to catch this 'casting numbers to string' error?

**Comment by bhack** [comment]
Yes you can add your test case in that file.

**Comment by Cyberface** [comment]
Sorry if I'm a little slow at getting this done. I've updated math_ops.py in this commit https://github.com/tensorflow/tensorflow/pull/44902/commits/df8fbc5d07e14f7c7130190f2a57c264dc89bfdf

In a first attempt to test the precision of tf.cast. I'm not sure if this is a good test or not so would appreciate any feedback thanks!

After that I can look into the casting of strings issue.

Cheers!

**Comment by Cyberface** [comment]
Hmm I thought the CI would run for this but I guess I'm wrong. Is it possible to run the CI on this?

**Comment by gbaned** [comment]
@Cyberface  Can you please fix build failures ? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by Cyberface** [comment]
I'm about to stop for the Winter break now so I'll leave it to you if you want to close this for now and I'll try and get back to it in the new year.

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by Cyberface** [comment]
Sorry I don't think I can work on this anymore.

**Pull request closed without merging**
