### PR TITLE
Fixing Issue 7214 about tf_update.py

### PR DESCRIPTION
**Pull request by machrisaa**
- first commit of tf_update2.py implemented by using RedBaron method
- fixed issue of #7214
- fixed issue of mixed code
- added support of tf.reverse and tf.image.resize_image

### CODE REVIEW

**Comment by rmlarsen** [comment]
@machrisaa can you sign the CLA?

**Comment by machrisaa** [comment]
Hi @rmlarsen , I have signed it just now.

**Comment by gunan** [comment]
@machrisaa you have to type "I signed it!" exactly, as there is a bot for checking CLA.

**Comment by machrisaa** [comment]
I signed it!

**Comment by gunan** [comment]
Another problem with CLA.
Looks like your commit email is is not recognized by github. Maybe you need to change the email of the commit to your email you use in github?

**Review by gunan — DISMISSED** [review]
it looks like this is a brand new file. Is this supposed to be modifying tf_upgrade.py?

**Comment by machrisaa** [comment]
Thanks @gunan. I created `tf_upgrade2.py` because it used completely different approach to implement the upgrading script. I have been communication with @aselle in [7214](https://github.com/tensorflow/tensorflow/issues/7214) to see if he would accept this approach or not. Also, this method has not fully completed the functions in `tf_update.py` (upgrading a folder tree and creating log file)

**Comment by aselle** [comment]
This is currently a demo implementation. See the issue #7214 for discussion.

**Pull request closed without merging**
