### PR TITLE
Avoid undefined behavior by union type punning in round_to_bfloat16

### PR DESCRIPTION
**Pull request by N-Dekker**
Use `std::memcpy` instead of union based type punning, to avoid undefined behavior.
See also C++ Core Guidelines: "Don't use a union for type punning"
https://github.com/isocpp/CppCoreGuidelines/blob/v0.8/CppCoreGuidelines.md#c183-dont-use-a-union-for-type-punning

### CODE REVIEW

**Comment by N-Dekker** [comment]
@googlebot I signed it!

**Review by Dynmi — DISMISSED** [review]
Delicate and nice change

**Review by jaingaurav — CHANGES_REQUESTED** [review]
Could you remove the FP32 union on line 180 as well?

Also adding @rmlarsen to the review.

**Review by jaingaurav — DISMISSED** [review]

**Comment by jaingaurav** [comment]
@N-Dekker: Could you also make this change in Eigen? The relevant file is https://bitbucket.org/eigen/eigen/src/default/Eigen/src/Core/arch/Default/Half.h.

**Comment by N-Dekker** [comment]
> @N-Dekker: Could you also make this change in Eigen? The relevant file is https://bitbucket.org/eigen/eigen/src/default/Eigen/src/Core/arch/Default/Half.h.

Thanks for the suggestion, @jaingaurav I never contributed to Eigen before, but I could give it a try. Specifically for their bfloat16 implementation, I think that would be this `union`: https://gitlab.com/libeigen/eigen/-/blob/386d809bde475c65b7940f290efe80e6a05878c4/Eigen/src/Core/arch/Default/BFloat16.h#L315  Right? Bfloat16 is my main interest for now, as I'm maintaining another implementation myself! https://github.com/biovault/biovault_bfloat16

Unfortunately, it appears that Eigen does not have a convenient `bit_cast` function template like `absl::bit_cast`. So I'd either have to propose `bit_cast` to Eigen as well, or fix their bfloat16 by memcpy-ing the bits from `float` to `unsigned int`, inside their `float_to_bfloat16_rtne`.

Anyway, it would certainly help if this pull request would make it into the master branch of TensorFlow  😃  I'll have another look tomorrow!

**Comment by jaingaurav** [comment]
@N-Dekker: Yeah I'd recommend updating both Half.h & BFloat16.h.

We're trying to merge your changes but there seem to be some BUILD file issues. I think you need to include the absl dependency else we are getting errors like: `'absl/base/casts.h': No such file or directory`

**Comment by N-Dekker** [comment]
> We're trying to merge your changes but there seem to be some BUILD file issues. I think you need to include the absl dependency else we are getting errors like: `'absl/base/casts.h': No such file or directory`

Thank you @jaingaurav, but I'm sorry, I'm not really familiar with the build system! Would it be sufficient to just add "@com_google_absl//absl/base" to  tensorflow/core/lib/bfloat16/BUILD ?  I guess somewhere here, right?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/bfloat16/BUILD#L18

**Comment by jaingaurav** [comment]
Yep I believe that should work

**Review by jaingaurav — DISMISSED** [review]

**Comment by jaingaurav** [comment]
@N-Dekker: I believe there is a ubuntu sanity check failure due to the ordering of the build deps. Could you please address that?

**Comment by N-Dekker** [comment]
>  I believe there is a ubuntu sanity check failure due to the ordering of the build deps. Could you please address that?

@jaingaurav: Thanks, I see now in https://source.cloud.google.com/results/invocations/c3882af9-15f4-4c40-b79a-37a233c1d006/targets/%2F%2Ftensorflow%2Ftools%2Fci_build:gen_ci_sanity_out/log

    FAIL: buildifier found errors and/or warnings in above BUILD files.
    buildifier suggested the following changes:
    tensorflow/core/lib/bfloat16/BUILD:
    18d17
    <         "@com_google_absl//absl/base",
    20a20
    >         "@com_google_absl//absl/base",
    exit status 1
Please fix manually or run buildifier <file> to auto-fix.

I guess that means that it suggests moving the line down, from 18 to 20, right? Do you have a clue why? I'm asking because other BUILD files do have "@com_google_absl//absl/base" in front of their "//tensorflow/core..." dependencies, for example: https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc0/tensorflow/compiler/aot/BUILD#L43

Anyway, I'll give it a try.

**Review by jaingaurav — DISMISSED** [review]

**Comment by N-Dekker** [comment]
@jaingaurav Still build failures, unfortunately! I guess because of the "absl/base" dependency as well. Would you suggest me to simply avoid using Abseil for this pull request? (Instead of `absl::bit_cast<uint32_t>(v)`, the member function could directly call `std::memcpy(&u, &v, sizeof(float))`, of course.)

I'm asking you, because I have another pull request in mind that may or may not use `bit_cast`

**Comment by jaingaurav** [comment]
@N-Dekker: Some of the failures seem unrelated. However, given that we're unlikely to use absl in Eigen an alternate fix without absl would be preferred.

**Review by jaingaurav — APPROVED** [review]

**Comment by jaingaurav** [comment]
Apologies @N-Dekker but we're actively reworking this code to use the Eigen implementation. As a result, we'll address this casting behavior when performing that work.

**Comment by N-Dekker** [comment]
>Apologies @N-Dekker but we're actively reworking this code to use the Eigen implementation. As a result, we'll address this casting behavior when performing that work.

No problem @jaingaurav, , thank you for the information! Would you still suggest me to make a merge request on this issue for https://gitlab.com/libeigen/eigen ? 

I'm asking also because I was about to prepare another possible improvement: I believe the performance of conversion from an integer type to bfloat could be improved significantly.

**Comment by jaingaurav** [comment]
@N-Dekker: I think I'd hold off just a bit until @rmlarsen completes the work. He said he might be able to fix this issue when doing that work.

If the performance improvement is isolated, maybe you can start proposing that in eigen right away?

**Comment by N-Dekker** [comment]
FYI I just submitted a bfloat32 merge request to Eigen, albeit on a different subject: "Allow implicit conversion from bfloat16 to float and double", https://gitlab.com/libeigen/eigen/-/merge_requests/163

**Comment by N-Dekker** [comment]
@jaingaurav FYI, The `eigen::bfloat16` merge request that corresponds to this `tensorflow::bfloat16` pull request has just been approved and merged onto the Eigen master branch by your Google colleague Rasmus Munk Larsen (@rmlarsen) 😃
  "Avoid undefined behavior by union type punning in float_to_bfloat16_rtne"
  https://gitlab.com/libeigen/eigen/-/merge_requests/164
  https://gitlab.com/libeigen/eigen/-/commit/b11f817bcff04276f3024d6780f56a137968b81a

**Comment by N-Dekker** [comment]
@jaingaurav 
> If the performance improvement is isolated, maybe you can start proposing that in eigen right away?

FYI, the `eigen::bfloat16` performance improvement merge request that I submitted currently being reviewed: "Faster conversion from integer types to bfloat16", https://gitlab.com/libeigen/eigen/-/merge_requests/166

**Pull request closed without merging**
