### PR TITLE
Fixing typo in comment.

### PR DESCRIPTION
**Pull request by cserpell**
Changed mathemetical to mathematical.

### CODE REVIEW

**Comment by cserpell** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
We will not be encouraging one liner grammatical changes as this is expensive process, thank you for your interest.
CC @mihaimaruseac

**Comment by cserpell** [comment]
I understand. Anyway, just FYI, this is an orthographic issue that goes directly into this live [API documentation](https://www.tensorflow.org/api_docs/python/tf/keras/Model#train_step).

**Comment by mihaimaruseac** [comment]
Can you try to fix all typos in that file/directory? If you fix more than just one/a handful we can get the PR accepted.

It's all a balance between amount of changes done and amount of CI that gets spent in merging the change.

**Comment by cserpell** [comment]
I just changed those three lines, I don't have enough time to go over all files in the directory. Don't worry, it can be fixed with some other changes in the future.

**Pull request closed without merging**
