### PR TITLE
[Intel MKL] Improve eager performance for small batch sizes

### PR DESCRIPTION
**Pull request by nammbash**
Improved eager performance  for small batch size by 2X (Intel MKL.)

Model Tested:
resnet 50 model

Modified File:
mkl_eager_op_rewrite.cc

Unit test:(PR Already Merged with Master)
https://github.com/tensorflow/tensorflow/pull/32935

### CODE REVIEW

**Review by penpornk — CHANGES_REQUESTED** [review]
Thank you for the PR! 
Why don't we just make `mkl_eager_ops_` an unordered map in the first place?

**Comment by nammbash** [comment]
> Thank you for the PR!
> Why don't we just make mkl_eager_ops_ an unordered map in the first place?

Yes, there is a todo for future further refactoring.

**Comment by penpornk** [comment]
> > Thank you for the PR!
> > Why don't we just make mkl_eager_ops_ an unordered map in the first place?
> 
> Yes, there is a todo for future further refactoring.

Why don't we do it now? It seems much simpler than keeping using std::vector and add another std::unordered_map for quick lookups on top of it.

To change `mkl_eager_ops_` to `unordered_map`, we only need to change these
https://github.com/tensorflow/tensorflow/blob/1b5c66bc3a2b05b47f0e4247a4e7bf872d608984/tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc#L79-L87
and these
https://github.com/tensorflow/tensorflow/blob/1b5c66bc3a2b05b47f0e4247a4e7bf872d608984/tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc#L172-L181

**Comment by nammbash** [comment]
> Thank you for the PR!
> Why don't we just make mkl_eager_ops_ an unordered map in the first place?
> 
> Yes, there is a todo for future further refactoring.
> 
> Why don't we do it now? It seems much simpler than keeping using std::vector and add another std::unordered_map for quick lookups on top of it.
> To change mkl_eager_ops_ to unordered_map, we only need to change these
> 
>   
>     
>       tensorflow/tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc
>     
>     
>         Lines 79 to 87
>       in
>       1b5c66b
>     
>     
>     
>     
> 
>         
>           
>            mkl_eager_ops_.push_back({"BatchMatMul", AlwaysRewrite, CreateGenericMklOp}); 
>         
> 
>         
>           
>            mkl_eager_ops_.push_back( 
>         
> 
>         
>           
>                {"BatchMatMulV2", AlwaysRewrite, CreateGenericMklOp}); 
>         
> 
>         
>           
>            mkl_eager_ops_.push_back({"Conv2D", RewriteConv2D, CreateMklConv2DOp}); 
>         
> 
>         
>           
>            mkl_eager_ops_.push_back( 
>         
> 
>         
>           
>                {"Conv2DBackpropInput", RewriteConv2D, CreateMklConv2DOp}); 
>         
> 
>         
>           
>            mkl_eager_ops_.push_back( 
>         
> 
>         
>           
>                {"Conv2DBackpropFilter", RewriteConv2D, CreateMklConv2DOp}); 
>         
> 
>         
>           
>            mkl_eager_ops_.push_back({"MatMul", AlwaysRewrite, CreateGenericMklOp}); 
>         
>     
>   
> 
> 
> and these
> 
>   
>     
>       tensorflow/tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc
>     
>     
>         Lines 172 to 181
>       in
>       1b5c66b
>     
>     
>     
>     
> 
>         
>           
>            *op_idx = -1; 
>         
> 
>         
>           
>            // Find and call the op's rewrite rule that determines whether we need to 
>         
> 
>         
>           
>            // rewrite this op or not. 
>         
> 
>         
>           
>            for (auto it = mkl_eager_ops_.begin(); it != mkl_eager_ops_.end(); ++it) { 
>         
> 
>         
>           
>              if (it->op_name.compare(op->Name()) == 0 && it->RewriteRule(op)) { 
>         
> 
>         
>           
>                *op_idx = it - mkl_eager_ops_.begin(); 
>         
> 
>         
>           
>                return true; 
>         
> 
>         
>           
>              } 
>         
> 
>         
>           
>            } 
>         
> 
>         
>           
>            return false;

Thank you for suggesting where exactly code needs to change.
The only thing is even if this code is going to change it is unrelated to this PR and has to be submitted as a new PR as the reason for both the hash maps are different and both will exist. I have created an internal ticket to track this.

**Review by penpornk — APPROVED** [review]
Got it. I saw the search in `mkl_eager_ops_` in `SlowCheckIfKernelRegistered` so I thought it was the part we are accelerating. It's actually `IsMklNameChangeOp` that we are trying to bypass. Sorry for the misunderstanding and thank you for filing the ticket!

**Comment by nammbash** [comment]
@penpornk you got it andThank you for the review. 
Also, talking internally , looks like the ask for refactoring has been requested twice. I am planning to refactor the vector to hashmap as a new PR soon and will keep you posted.

**Comment by penpornk** [comment]
@nammbash Thank you very much! :)

**Pull request merged**
