### PR TITLE
Go: add support for empty tags-set when loading saved model

### PR DESCRIPTION
**Pull request by kristofmaar**
There is a check in `saved_model.go` that does not allow empy tag set, however there are models without tags that work perfectly in the library without providing them (they are optional in the Python library too, for example).

Apparently the check was added in #36466, though instead of throwing an error on an empty set, a nil value can be passed in these cases and the C library will not complain. Otherwise, the pointer to the first element is passed as before.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @gharibian Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @gharibian Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @gharibian Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @gharibian Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @gharibian Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @gharibian Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @gharibian Can you please review this PR ? Thank you!

**Review by mihaimaruseac — COMMENTED** [review]
Let's still keep the test, converting it to test that the model loads successfully.

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
A test is failing, so we cannot merge this. Can you take a look please?

```
tensorflow/go/saved_model_test.go:100: LoadSavedModel() failed with an empty tags set: Could not find meta graph def matching supplied tags: {  }. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
```

**Comment by kristofmaar** [comment]
@mihaimaruseac I've added a version of half_plus_two with the tags removed. Can you please try to run the test again?
I cannot seem to run it on my ARM64 Mac.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
