### PR TITLE
Compilation warnings handled

### PR DESCRIPTION
**Pull request by ANSHUMAN87**

### CODE REVIEW

**Review by lu-wang-g — COMMENTED** [review]
What kind of compilation warning is it for?

**Comment by ANSHUMAN87** [comment]
> What kind of compilation warning is it for?

Below is the warning message i got:
>warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

**Comment by ANSHUMAN87** [comment]
@lu-wang-g : The code is updated now, please check and approve, Thanks!

**Review by lu-wang-g — COMMENTED** [review]
For simplicity, please use "size_t i = 0 "instead

**Comment by ANSHUMAN87** [comment]
> For simplicity, please use "size_t i = 0 "instead

@lu-wang-g : Updated as per your comment, please check and approve, Thanks!

**Comment by gbaned** [comment]
@lu-wang-g Could you PTAL and approve.

**Comment by gbaned** [comment]
@lu-wang-g Could you PTAL and approve.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @lu-wang-g, @lu-wang-g, @lu-wang-g, @miaout17: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @lu-wang-g, @lu-wang-g, @lu-wang-g, @miaout17: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 30 days with no activity and the `awaiting review` label has been applied.

**Review by talumbau — APPROVED** [review]

**Pull request merged**
