### PR TITLE
Code improvement to fasten execution process

### PR DESCRIPTION
**Pull request by john-2424**
Added couple of shabang lines to configure.py and configure.md

### CODE REVIEW

**Comment by gbaned** [comment]
@KrishnaRajule Can you please sign CLA. Thanks!

**Comment by KrishnaRajule** [comment]
@googlebot I signed it!

**Comment by KrishnaRajule** [comment]
@gbaned I have signed it!

**Comment by mihaimaruseac** [comment]
These files are intended to run without a shebang. Plus, the shebang you added is not general/invalid (you added a `bash` shebang on a file that is supposed to run on Windows and you added a shebang that requires users to have `python3` as a binary on the path, but there are systems where that is not the case -- they only come with Python 3.x by default).

**Comment by KrishnaRajule** [comment]
Okay, I understand. Thank You for your response! @mihaimaruseac

**Pull request closed without merging**
