### PR TITLE
[Windows] Fix build by avoiding use of non-standard 0-size array.

### LINKED ISSUE #4798: Error building on Windows
(Copied from @laudney's comment on #17)

> I've tried to follow your instructions. All seem to work flawlessly (for about 45min) until it failed with:
> 
> ```
> The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (186,61)" does not exist in the project, and will be ignored.
> Done Building Project "H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default targets) -- FAILED.
> 
> "H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
> "H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow.vcxproj" (default target) (3) ->
> "H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\tf_core_cpu.vcxproj" (default target) (4) ->
> "H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\tf_core_framework.vcxproj" (default target) (5) ->
> (CustomBuild target) ->
>   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [H:\PycharmProjects\t
> ensorflow\tensorflow\contrib\cmake\build\tf_core_framework.vcxproj]
> 
>     30 Warning(s)
>     1 Error(s)
> ```

### PR DESCRIPTION
**Pull request by mrry**
Fixes #4798.

### CODE REVIEW

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
@gunan: Is there a cunning way we could trigger the Windows Jenkins build on demand for a PR? (I tested it locally and it built, but it'd be nice to have a green tick to go with it :).

**Comment by gunan** [comment]
Now that we have 3 windows executors, I can set up windows build to run for every PR.
Would that work?

I can quickly get you a test we can link for this, but unfortunately I cannot get the green tick without adding it to all presubmits and getting all the PR tests to run again.

**Review by gunan — APPROVED** [review]

**Comment by mrry** [comment]
I'm happy to take a chance on merging this, since it builds for me locally!

But it'd be awesome to run Windows presubmits for every PR. Maybe an optional check at first though, in case it starts blocking people for no good reason?

**Pull request merged**
