### PR TITLE
Fix error in tf.linalg.triangular_solve docstring

### PR DESCRIPTION
**Pull request by st--**
The description for adjoint=True vs False was the wrong way around. I've also added a (perhaps more natural) explanation using matmul directly.

### CODE REVIEW

**Comment by st--** [comment]
@gbaned Hi, I am not able to sign the Google CLA because the form claims that my GitHub username is invalid!

**Comment by gbaned** [comment]
@st--  Can you please make sure to use same GitHub username and email-id associated with it.  Thank you.

**Comment by mihaimaruseac** [comment]
The problem might be because you use a github-noreply private email.

Until CLA is signed, we cannot review the PR

**Comment by st--** [comment]
Could you confirm that I understand correctly, it is ONLY possible to contribute to tensorflow (/ other Google projects) if I make my email address public in the git commit, and I cannot propose commits under my github-users-noreply address?

I've attached the error message I get when trying to sign the CLA.
image

**Comment by st--** [comment]
@mihaimaruseac let me know if you can figure out a way around my issues with getting the CLA signed. Alternatively, I am happy to make these changes public domain, if that helps. Or you could simply take inspiration from my changes and re-do them in your own way. I would just be keen for this obvious mistake in the official docs to be fixed!

**Comment by gbaned** [comment]
@st-- It still shows CLA is pending, can you please sign CLA. Thank you!

**Comment by st--** [comment]
I still can't add my github user name to the Google CLA form (see screenshot above). I don't want to make my personal gmail address public in the Git commit message - but I can't associate GitHub's `st--@users.noreply.github.com` address with my Google account because it's not an actual email service. Unless I've missed something somewhere, I don't see how I can resolve this any other way.

I hereby put the changes I proposed in commit https://github.com/tensorflow/tensorflow/pull/55697/commits/ad651b682ca3154e5877b9fdf6df5728a943d186 into the public domain and waive all my rights to it to the extent possible. I hope that should allow you to just fix the docstring yourself, if you can't get the system to work with me.

**Comment by gbaned** [comment]
@st-- It still shows CLA is pending, any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
> Hi @st-- Sorry for the delay, it still shows CLA is pending, any update on this PR? Please. Thank you!

**Comment by st--** [comment]
I've signed an Individual CLA, but your form does not let me fill in my GitHub user-name, so it seems to not associate it with my commit. I'm afraid I can't see what *I* can do about this. Please let me know once the

**Comment by gbaned** [comment]
Hi @st-- Sorry for the delay, it still shows CLA is pending, any update on this PR? Please. Thank you!

**Review by cantonios — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @st-- It still shows CLA is pending, please sign. Thank you!

**Comment by st--** [comment]
@gbaned I've signed it, but your form still does not let me enter my GitHub username and claims it is invalid, please fix it. Thank you!
image

**Comment by gbaned** [comment]
Hi @mihaimaruseac Still it is showing CLA pending for @st-- . Can you please assist on above [comments](https://github.com/tensorflow/tensorflow/pull/55697#issuecomment-1372435983) Thank you!

**Comment by gbaned** [comment]
Hi @mihaimaruseac Can you please assist on above [comments](https://github.com/tensorflow/tensorflow/pull/55697#issuecomment-1372435983) from @st--. Thank you!

**Comment by gbaned** [comment]
Hi @mihaimaruseac Can you please assist on above https://github.com/tensorflow/tensorflow/pull/55697#issuecomment-1372435983 from @st--. Thank you!

**Comment by gbaned** [comment]
Hi @mihaimaruseac Can you please assist on above https://github.com/tensorflow/tensorflow/pull/55697#issuecomment-1372435983 from @st--. Thank you!

**Comment by gbaned** [comment]
Hi @mihaimaruseac Can you please assist on above https://github.com/tensorflow/tensorflow/pull/55697#issuecomment-1372435983 from @st--. Thank you!

**Comment by gbaned** [comment]
Hi @mihaimaruseac Can you please assist on above https://github.com/tensorflow/tensorflow/pull/55697#issuecomment-1372435983 from @st--. Thank you!

**Comment by gbaned** [comment]
Hi @st-- It shows Need CLA. Can you please make sure to use same GitHub username and email-id associated with it. Thank you.

image

**Comment by gbaned** [comment]
Hi @st-- Any update on this PR? Please. Thank you!

**Comment by st--** [comment]
@gbaned I just tried again, but the Google CLA form still refuses to accept my current GitHub user name as valid. I'm afraid I'm not willing to change my username just because Google's CLA form doesn't know what makes a valid GitHub username.

**Comment by gbaned** [comment]
> @gbaned I just tried again, but the Google CLA form still refuses to accept my current GitHub user name as valid. I'm afraid I'm not willing to change my username just because Google's CLA form doesn't know what makes a valid GitHub username.

Hi @st-- We cannot review this PR without CLA singed. Shall we close this PR? Thank you!

**Comment by gbaned** [comment]
Hi @st-- I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please sign the CLA and feel free to reopen. Thank you for your contribution.

**Comment by st--** [comment]
@gbaned I'm sorry to see that you are unable to provide a form that actually _allows_ me to sign it. I am perfectly willing to sign the CLA, and I _tried_ signing the CLA multiple times, but unfortunately it always claims that my username were invalid (when it's not, as you can see in me being logged in and writing comments on GitHub).

**Comment by st--** [comment]
Actually, I just realized I _have_ signed the CLA - the issue is that the CLA tool doesn't let me enter my GitHub username to associate it with the CLA, so your CLA _checker_ does not realize that I did, in fact, sign the CLA.

**Pull request closed without merging**
