### PR TITLE
PIC flag for Makefile-built Android Static Library

### PR DESCRIPTION
**Pull request by resec**
Currently if we build a shared lib with ndk = r12b and android-api = 21, and the shared lib is linking Makefile-built tensorflow android static library, the android ndk hints that the tensorflow and nsync lib is not complied with -fPIC option, this PR fix the problem. It only impacts the android build.

### CODE REVIEW

**Comment by sb2nov** [comment]
@petewarden please review

**Review by petewarden — APPROVED** [review]
Sorry for the very slow response. This looks good, thanks for the fix!

**Comment by martinwicke** [comment]
Jenkins, test this please!

**Comment by martinwicke** [comment]
(CLA is fine, it's just me)

**Pull request merged**
