### PR TITLE
Fixed the statility issue of the autotuning process

### PR DESCRIPTION
**Pull request by kaixih**
(1) Add an environment variable TF_AUTOTUNE_EPSILON (default=0.03) to enforce a fussy time comparison to reduce the chances of the autotuning process flipping back and forth between close algorithms.

(2) Add a max *global* autotuning iteration count to completely avoid the case that the autotuner cannot stabilize after many iterations if the two algorithms are very close to each other.  

To problem (2), for example: 
Suppose the winner sequence is 0 1 0 1 0 1 0 1..., (meaning algorithm 0 and 1 are very close to each other, and they appear as the winner alternatively).
According to the current auto-tuning algorithm and if we have set the TF_AUTOTUNE_THRESHOLD = 2, meaning the target score=2, and max (local) count = 5x2x2=20. 

The auto tuner will do this: 
0 wins: create node 0 (1, 1) # the numbers in () mean the current score and local_iteration_count
1 wins: demote node 0 (0, 2) and delete node 0 # because the winner changes
0 wins: create node 0 (1, 1) 
1 wins: demote node 0 (0, 2) 
....
This means the auto-tuner will never end, since the score and the local iteration count can never reach 2 and 20.

FYI @nluehr

### CODE REVIEW

**Comment by houtoms** [comment]
Any updates on this PR?

**Comment by nluehr** [comment]
@jlebar Can you review this PR for us?

**Comment by jlebar** [comment]
> @jlebar Can you review this PR for us?

I work on XLA, and this is a TensorFlow change, so I can't.  @gunan is also not the right reviewer, that may be why you haven't gotten a response.  cc @tatianashp @chsigg.

(That said, as I understand it this PR says that if algorithm N is 2.9% slower than algorithm N+1, TF will always choose algorithm N.  If we were trying to make this change in XLA I'd have a lot of questions as far as whether this is the best and simplest way to accomplish the goal...)

**Comment by chsigg** [comment]
Kaixi, do you think just adding the max global iterations would be sufficient to prevent endless toggling? Then we wouldn't risk the issue that Justin is describing.

**Comment by houtoms** [comment]
Hi @chsigg , thanks for your comments. 

Yes. I have removed other parts and only keep the max global iteration now.

**Review by chsigg — APPROVED** [review]

**Pull request merged**
