### PR TITLE
Restore a working CMake build

### PR DESCRIPTION
**Pull request by mrry**
This includes changes from #2705, which fixed some of the breakage.

### CODE REVIEW

**Comment by mrry** [comment]
@martinwicke: This is the PR I mentioned on Friday. Do you know how to invoke @googlebot to tell it that the CLAs are valid?

**Comment by martinwicke** [comment]
This is the PR you're thinking about splitting again?

**Comment by mrry** [comment]
@martinwicke: Yep, I'm going to merge #2705 and rebase this on top of it so it contains just my changes.

**Comment by mrry** [comment]
@martinwicke: OK, this now contains my change only. Good to merge?

**Comment by martinwicke** [comment]
Merged. Note this doesn't actually restore the cmake build.

**Pull request merged**
