### PR TITLE
Fix bug in add_n's handling of IndexedSlices

### PR DESCRIPTION
**Pull request by frreiss**
The fix for #15943 (https://github.com/tensorflow/tensorflow/pull/21494) modified the Python `add_n` op to allow `IndexedSlices` in its arguments. This fix introduced a bug in how `add_n` handles an input consisting of a single `IndexedSlices` object. Specifically, `add_n` returns the `values` field of the `IndexedSlices` object, when it should return the tensor representation of the object.

This PR fixes the bug and adds a regression test.

### CODE REVIEW

**Review by rmlarsen — DISMISSED** [review]

**Comment by rmlarsen** [comment]
@frreiss Thanks for the fix!

**Comment by rmlarsen** [comment]
@frreiss Please fix the linter errors: https://source.cloud.google.com/results/invocations/2ec1249e-6c88-47f6-8ab2-1529b4abdb10/log

**Comment by frreiss** [comment]
@rmlarsen should be fixed now.

**Comment by frreiss** [comment]
@rmlarsen would you mind triggering another CI build on this branch? I believe that my last commit fixed all the linter errors.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rmlarsen** [comment]
I think you can ignore the errors.

**Pull request merged**
