### PR TITLE
Java/Android: Fix bug introduce in #12643

### PR DESCRIPTION
**Pull request by asimshankar**
The contents of the graphDef file weren't actually being read into the
byte array.

### CODE REVIEW

**Comment by asimshankar** [comment]
Jenkins, test this please

**Review by andrewharp — APPROVED** [review]

**Comment by drpngx** [comment]
`fft_ops_test` is known failure internally, not sure what happened to `nn_grad_test`. Trying again.

Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
I ended up pushing from internal. Thank you for the fix!

**Pull request closed without merging**
