### PR TITLE
Fix the issues in API compatibility test

### PR DESCRIPTION
**Pull request by feihugis**
When running `$ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test --update_goldens True`, the compatibility test failed due to some files in the estimator module as below. This PR tries to fix this issue. 
```
sisue 1	: Object tensorflow.estimator.Estimator expected but not found (removed).
Issue 2	: Object tensorflow.estimator.BaselineClassifier expected but not found (removed).
Issue 3	: Object tensorflow.estimator.export.ExportOutput expected but not found (removed).
Issue 4	: Object tensorflow.estimator.inputs expected but not found (removed).
Issue 5	: Object tensorflow.estimator.export.RegressionOutput.__metaclass__ expected but not found (removed).
Issue 6	: Object tensorflow.estimator.export.PredictOutput.__metaclass__ expected but not found (removed).
Issue 7	: Object tensorflow.estimator.EvalSpec expected but not found (removed).
Issue 8	: Object tensorflow.estimator.BaselineRegressor expected but not found (removed).
Issue 9	: Object tensorflow.estimator expected but not found (removed).
Issue 10	: Object tensorflow.estimator.FinalExporter expected but not found (removed).
Issue 11	: Object tensorflow.estimator.export.PredictOutput expected but not found (removed).
Issue 12	: Object tensorflow.estimator.WarmStartSettings expected but not found (removed).
Issue 13	: Object tensorflow.estimator.export.ClassificationOutput expected but not found (removed).
Issue 14	: Object tensorflow.estimator.experimental expected but not found (removed).
Issue 15	: Object tensorflow.estimator.export.RegressionOutput expected but not found (removed).
Issue 16	: Object tensorflow.estimator.BoostedTreesRegressor expected but not found (removed).
Issue 17	: Object tensorflow.estimator.export expected but not found (removed).
Issue 18	: Object tensorflow.estimator.LatestExporter expected but not found (removed).
Issue 19	: Object tensorflow.estimator.EstimatorSpec expected but not found (removed).
Issue 20	: Object tensorflow.estimator.export.ClassificationOutput.__metaclass__ expected but not found (removed).
Issue 21	: Object tensorflow.estimator.RunConfig expected but not found (removed).
Issue 22	: Object tensorflow.estimator.LinearClassifier expected but not found (removed).
Issue 23	: Object tensorflow.estimator.DNNLinearCombinedClassifier expected but not found (removed).
Issue 24	: Object tensorflow.estimator.BoostedTreesClassifier expected but not found (removed).
Issue 25	: Object tensorflow.estimator.DNNClassifier expected but not found (removed).
Issue 26	: Object tensorflow.estimator.export.ExportOutput.__metaclass__ expected but not found (removed).
Issue 27	: Object tensorflow.estimator.ModeKeys expected but not found (removed).
Issue 28	: Object tensorflow.estimator.BestExporter expected but not found (removed).
Issue 29	: Object tensorflow.estimator.Exporter expected but not found (removed).
Issue 30	: Object tensorflow.estimator.VocabInfo expected but not found (removed).
Issue 31	: Object tensorflow.estimator.DNNLinearCombinedRegressor expected but not found (removed).
Issue 32	: Object tensorflow.estimator.DNNRegressor expected but not found (removed).
Issue 33	: Object tensorflow.estimator.export.ServingInputReceiver expected but not found (removed).
```

### CODE REVIEW

**Comment by feihugis** [comment]
@case540 Could you have a look at this PR? It seems like there are big changes in the estimator module. Is my understanding right?

**Comment by case540** [comment]
Does...

bazel-bin/tensorflow/tools/api/tests/api_compatibility_test --update_goldens True --only_test_core_api True

...work? Should maybe make --only_test_core_api default to True I suppose. But yeah, estimator code is moving out of core TF into its own repo https://github.com/tensorflow/estimator

**Comment by feihugis** [comment]
@case540 Yes, this command works. Then, should we keep the estimator pbtxt files or just delete them?

**Comment by case540** [comment]
Keep them (for now at least). We run internal tests against them. Also, I think if you "pip install tensorflow_estimator" you will be able to run without the core_only flag yourself.

**Comment by feihugis** [comment]
@case540 Sounds good. We could close this PR?

**Comment by case540** [comment]
Closing! Thanks and if you see any potential issues with these tests due to the Estimator mode migration please let me know!

**Pull request closed without merging**
