### PR TITLE
MKL DNN: cleaning up MKL ML code in LRN kernel

### PR DESCRIPTION
**Pull request by ashraf-bhuiyan**
Cleaned up Intel MKL ML related code. The intention is to stop supporting MKL ML (closed source library) code and have the MKL DNN code (Open sourced library) to be the default code path.

### CODE REVIEW

**Comment by ashraf-bhuiyan** [comment]
If possible, can you please review this PR.

**Comment by ashraf-bhuiyan** [comment]
If possible, can you please review this PR

**Review by penpornk — APPROVED** [review]
Sorry for the delay and thank you for the PR!

**Comment by penpornk** [comment]
This PR is failing the `clang-format` check. Could you please help fix it? Pasting the error message here for convenience (see details in the link at the end of the PR)
```c++
--- a/tensorflow/core/kernels/mkl_lrn_op.cc
+++ b/tensorflow/core/kernels/mkl_lrn_op.cc
@@ -23,7 +23,6 @@ limitations under the License.
 #define EIGEN_USE_THREADS
 #include <vector>
 #include "mkldnn.hpp"
-#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
 #include "tensorflow/core/framework/op_kernel.h"
 #include "tensorflow/core/framework/register_types.h"
 #include "tensorflow/core/framework/tensor.h"
@@ -32,6 +31,7 @@ limitations under the License.
 #include "tensorflow/core/lib/core/errors.h"
 #include "tensorflow/core/util/mkl_util.h"
 #include "tensorflow/core/util/tensor_format.h"
+#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
 #if !defined(IS_MOBILE_PLATFORM)
 #include "tensorflow/core/util/work_sharder.h"
```

**Review by penpornk — CHANGES_REQUESTED** [review]
This PR is failing the `clang-format` check. Could you please help run `clang-format`/fix it? Pasting the error message here for convenience (see details in the link at the end of the PR)
```c++
--- a/tensorflow/core/kernels/mkl_lrn_op.cc
+++ b/tensorflow/core/kernels/mkl_lrn_op.cc
@@ -23,7 +23,6 @@ limitations under the License.
 #define EIGEN_USE_THREADS
 #include <vector>
 #include "mkldnn.hpp"
-#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
 #include "tensorflow/core/framework/op_kernel.h"
 #include "tensorflow/core/framework/register_types.h"
 #include "tensorflow/core/framework/tensor.h"
@@ -32,6 +31,7 @@ limitations under the License.
 #include "tensorflow/core/lib/core/errors.h"
 #include "tensorflow/core/util/mkl_util.h"
 #include "tensorflow/core/util/tensor_format.h"
+#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
 #if !defined(IS_MOBILE_PLATFORM)
 #include "tensorflow/core/util/work_sharder.h"
```

**Comment by ashraf-bhuiyan** [comment]
sorry for the delay. I have applied clang format check, and found some other format issues. Fixed all the issues.

**Review by penpornk — APPROVED** [review]
Thank you for the changes!

**Pull request merged**
