### PR TITLE
Fix nondeterminstic crash when initializing xnnpack tensors

### PR DESCRIPTION
**Pull request by richhx**

### CODE REVIEW

**Comment by richhx** [comment]
See https://github.com/tensorflow/tensorflow/issues/55331

**Comment by richhx** [comment]
Anything I need to do to make the build pass or get this reviewed? Not sure why it's failing since the link doesn't work for me.

**Comment by gbaned** [comment]
@nutsiepully Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
@nutsiepully Can you please review this PR ? Thank you!

**Comment by richhx** [comment]
Bump

**Comment by gbaned** [comment]
@nutsiepully Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
@nutsiepully Can you please review this PR ? Thank you!

**Review by yishuangP — APPROVED** [review]

**Comment by richhx** [comment]
Is there a reason the build fails for macOS CPU and Windows Bazel? Looking at the logs, I don't see anything quite informative. Are there more informative logs on Google's side?

**Comment by gbaned** [comment]
@richhx Can you please resolve conflicts? Thank you!

**Comment by richhx** [comment]
Should be fixed. Looks like someone else also found the issue and finally fixed it.

**Comment by gbaned** [comment]
Hi @yishuangP Can you please review this PR ? Thank you!

**Comment by yishuangP** [comment]
> Should be fixed. Looks like someone else also found the issue and finally fixed it.

Yes this is fixed in https://github.com/tensorflow/tensorflow/commit/b842657860e85490dfc074541a6ce83198476b33. Thanks for this PR anyway. I'm gonna close this one.

**Pull request closed without merging**
