### PR TITLE
Update retrain.py to be compatible with Python 3

### PR DESCRIPTION
**Pull request by dgolden1**
It's PROBABLY backwards compatible with Python 2 but I haven't fully tested it

Fixes https://github.com/tensorflow/tensorflow/issues/1274

### CODE REVIEW

**Comment by dgolden1** [comment]
I signed it! As Arterys, Inc.

**Comment by dgolden1** [comment]
Updated commit e-mail address to match my CLA e-mail address (Arterys, Inc.) and force pushed.

**Comment by martinwicke** [comment]
Can you go to https://cla.developers.google.com/clas and check that the corp CLA for Arterys shows up as "CLAs I am covered by"?

**Comment by dgolden1** [comment]
@martinwicke sorry for the confusion; *now* I see the CLA listed at https://cla.developers.google.com/clas.

**Comment by vrv** [comment]
Thanks, can you update to master?  Then we can test.

**Comment by dgolden1** [comment]
@vrv Rebased onto master

**Comment by vrv** [comment]
@tensorflow-jenkins: test this lease

**Comment by vrv** [comment]
*test this please

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please.

**Comment by vrv** [comment]
Our mac tests are broken, but this otherwise lookss good. merging.

**Pull request merged**
