### PR TITLE
Branch 126082003

### PR DESCRIPTION
**Pull request by rmlarsen**
Push of internal Google updates to TensorFlow.

### CODE REVIEW

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
@willnorris it looks like the cla checker bot isn't checking the commits for these types of PRs -- just an FYI.

**Comment by rmlarsen** [comment]
@googlebot I signed it as Google Inc.

**Comment by rmlarsen** [comment]
@vrv @martinwicke : this looks ready to be merged, apart from the (bogus?) cla check.

**Comment by willnorris** [comment]
@rmlarsen: This PR is in a state that our CLA checker can't handle.  For this, and ones like it, it's safe to ignore googlebot (see [go/cla#It's okay to accept](http://go/cla#It's okay to accept)).  Also, [b/28148245](http://b/28148245) for a relevant bug that should help PRs like this.

**Comment by rmlarsen** [comment]
@willnorris thanks for the clarification.

**Pull request merged**
