### PR TITLE
Rename models directory to examples

### PR DESCRIPTION
**Pull request by anirudh161**
Moving files under the models/ directory to live under the examples/ directory as part of the tab merge effort

### CODE REVIEW

**Comment by gbaned** [comment]
@anirudh161 Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@anirudh161 Can you please resolve conflicts? Thanks!

**Comment by anirudh161** [comment]
The changes in this PR have already been made on another CL. Closing this PR.

**Pull request closed without merging**
