### PR TITLE
Move training_op_helpers to framework

### PR DESCRIPTION
**Pull request by vcarpani**
This PR moves training_op_helpers from [`tensorflow/core/kernels`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/) to [`tensorflow/core/framework`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/), to support people writing new C++ optimizers. 

Solves issue: https://github.com/tensorflow/tensorflow/issues/27899

### CODE REVIEW

**Comment by jhseu** [comment]
Looks fine to me based on comments in that issue, adding @alextp as FYI.

**Review by jhseu — DISMISSED** [review]

**Review by alextp — DISMISSED** [review]
Thanks!

**Comment by jhseu** [comment]
This might get tricky to do, because the dependencies on framework -> core/kernels/{dense_update_functor,variable_ops} -> framework causes a circular dependency...

**Comment by vcarpani** [comment]
> This might get tricky to do, because the dependencies on framework -> core/kernels/{dense_update_functor,variable_ops} -> framework causes a circular dependency...

Could moving training_op_helpers to util be a viable solution?

**Comment by alextp** [comment]
Putting the helpers in their own separate library might work, yes. This doesn't really care whether they are in the framework directory or the util directory. I prefer the framework directory.

**Review by alextp — DISMISSED** [review]

**Comment by vcarpani** [comment]
The latest commit should finally remove the circular dependency.

**Review by alextp — DISMISSED** [review]

**Review by jhseu — CHANGES_REQUESTED** [review]
This just moves the files to framework, but it won't be included in libtensorflow_framework.so since it's not in the framework_internal_impl BUILD rule.

I think it'll work if you update the tensorflow/BUILD file to depend on training_op_helpers, though.

**Comment by vcarpani** [comment]
Thanks, I think I also fixed the problem with the AdroidDemoApp.

**Review by alextp — APPROVED** [review]

**Comment by rthadur** [comment]
@vcarpani can you please check build failures

**Comment by vcarpani** [comment]
> @vcarpani can you please check build failures

I will do it later this week ;)

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by Squadrick** [comment]
@vcarpani Why was this closed? Seems pretty useful, imo.

**Comment by vcarpani** [comment]
I closed it because because I did not have time for continuing it; I could pick it up in the near future, especially if someone is interested in helping

**Comment by Squadrick** [comment]
@vcarpani We need it for TensorFlow Addons. I'll check out your code and make the needed changes. Just wanted to know if there was any other reason for closing this PR. Thanks for the clarification.

**Comment by vcarpani** [comment]
@Squadrick ok, I'll reopen this PR and push back the changes to my fork, so we can use it as base for the changes ;)

**Comment by Squadrick** [comment]
@vcarpani Thanks so much.

**Comment by vcarpani** [comment]
Closing since it has been moved to:
https://github.com/tensorflow/tensorflow/pull/37873

**Pull request closed without merging**
