### PR TITLE
Use string_to_hash_bucket_fast in feature_column

### PR DESCRIPTION
**Pull request by ysuematsu**
Updated feature_column to use string_to_hash_bucket_fast instead of deprecated string_to_hash_bucket.

### CODE REVIEW

**Comment by ysuematsu** [comment]
I signed it!

**Comment by ysuematsu** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Failing test is a known flake with fix underway.

**Pull request merged**
