### PR TITLE
Improve shape function for CudnnRNNParamsSize

### PR DESCRIPTION
**Pull request by yongtang**
In cudnn_rnn_ops.cc, the CudnnRNNParamsSize does not have restrictions on num_layers, num_units, and input_size, though they all should be scalars.

This fix adds the shape check of num_layers, num_units, and input_size
for CudnnRNNParamsSize.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by annarev — DISMISSED** [review]

**Comment by annarev** [comment]
@yongtang can you check output of "Experimental clang-format Check" and update the formatting according to the errors reported?

**Comment by yongtang** [comment]
Thanks @annarev for the review. The PR has been updated with clang-format issue fixed. Please take a look.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request merged**
