### PR TITLE
Branch 139989725

### PR DESCRIPTION
**Pull request by caisq**
Manually resolved conflicts in:
tensorflow/contrib/training/BUILD
tensorflow/contrib/learn/python/learn/datasets/base.py
tensorflow/contrib/cmake/tf_tests.cmake
tensorflow/core/kernels/cwise_op_floor_div.cc

### CODE REVIEW

**Comment by caisq** [comment]
@mrry, any idea about this error in the windows cmake build?

```
07:51:24 stderr: error: unable to create file third_party/llvm/expand_cmake_vars.py": Invalid argument
```

**Comment by mrry** [comment]
@caisq It looks like there's a stray `"` character in the filename of this file:

https://github.com/caisq/tensorflow/blob/branch_139989725/third_party/llvm/expand_cmake_vars.py%22

Since this is an oss-only file, I'm guessing one of the scripts for generating the git version got bad input?

**Comment by caisq** [comment]
Thanks for looking into it, @mrry. Since all other tests passed, shall we merge this PR and push a fix later?

**Comment by mrry** [comment]
Whatever you think is easier... ISTR that changing a filename in the file-chooser script needs some manual intervention on the Git repo side, so it might be just as easy to remove manually it in this PR?

**Comment by caisq** [comment]
The fix should have been submitted internally. Let me push again. Closing this PR.

**Pull request closed without merging**
