### PR TITLE
Set re2 repository commit to the latest

### PR DESCRIPTION
**Pull request by meteorcloudy**
This makes re2 buildable on Windows with MSVC toolchain. @mrry @damienmg @dslomov

### CODE REVIEW

**Review by mrry — COMMENTED** [review]
Looks good, thanks!

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by meteorcloudy** [comment]
Hmm.. Is it my change that's causing the failure? Can we rerun it?

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
(Looks like a transient failure for one of the external repositories... but let's test again to be sure.)

**Comment by martinwicke** [comment]
Still failing. I'm sure it's unrelated to this CL, but that test is becoming is problem. Do you know what's wrong with it?

**Pull request merged**
