### PR TITLE
#23976 : Resolve ImportError: cannot import name cloud on s390x 

### PR DESCRIPTION
**Pull request by Nayana-ibm**
As per comments in #23976, adding check for s390x

### CODE REVIEW

**Review by gunan — APPROVED** [review]

**Review by meteorcloudy — APPROVED** [review]

**Comment by Nayana-ibm** [comment]
checked logs for failing CI builds. Could see error  `AttributeError: class Tokenizer has no attribute '__mro__'`
Not sure if its related to the code patch introduced in this PR

**Comment by harshini-gadige** [comment]
@Nayana-ibm  @gunan  Please address the test failures.

**Comment by Nayana-ibm** [comment]
@gunan @meteorcloudy Checked logs of failing CI builds - GPU Python3, MacOS Contrib etc.  Tests are failing with - `error code 134` or `ImportError: No module named keras_preprocessing`

Doesn't look like its related to the code patch introduced in this PR. Could you please guide me on this? Merging is blocked due to these failures.

**Comment by Nayana-ibm** [comment]
@gunan @meteorcloudy When this can be merged?

**Comment by meteorcloudy** [comment]
@Nayana-ibm sorry for the delay, I'm trying to re-submit this change internally.

**Comment by Nayana-ibm** [comment]
@meteorcloudy Thanks

**Pull request merged**
