### PR TITLE
Update nsync from 1.24.0 to 1.25.0.

### PR DESCRIPTION
**Pull request by plliao**
This PR upgrades nsync from 1.24.0 to 1.25.0 to include a fix from upstream.

Please see the following issue for more details. Thanks.
https://github.com/tensorflow/tensorflow/issues/56280

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by plliao** [comment]
Hello @pak-laura @gbaned,
Could you review the PR? Thanks!

**Comment by plliao** [comment]
Hello @pak-laura @gbaned 
Could you please help find someone review and merge the PR? 
It is a really simple dependency upgrade PR. The upgraded dependent library is also owned and maintained by Google.
Merging the PR will reduce our cost to maintain internal change in TensorFlow. Thank you so much.

**Review by rohan100jain — APPROVED** [review]

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
I think this already landed due to concurrent internal changes (JAX motivated)

**Comment by mihaimaruseac** [comment]
PR is empty, nothing left to merge

**Pull request closed without merging**
