### PR TITLE
Fixed Tensorboard minimap not being drawn on Safari (OS X, iOS)

### PR DESCRIPTION
**Pull request by qbx2**
Fixed Tensorboard minimap not being drawn on Safari (OS X, iOS)
Tested on Chrome (OS X), Safari (OS X, iOS)

### CODE REVIEW

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by qbx2** [comment]
This patch also makes "Download PNG" work on Safari.

**Comment by vrv** [comment]
@dsmilkov: look ok?  We'll merge if so.

**Comment by dsmilkov** [comment]
Thanks for the trying to fix this!

I tested it and the minimap doesn't work on Firefox now. Can you get a solution that works on Chrome/Firefox/MacOS? Thanks!

**Comment by dsmilkov** [comment]
@qbx2 I did some testing and having the old way as a fallback makes it work on Firefox/Safari/Chrome. Can you change your commit to:
```
image.src = 'data:image/svg+xml;charset=utf-8,' + svgXml.replace(/\n/g,'');
image.onerror = () => {
  let blob = new Blob([svgXml], {type: 'image/svg+xml;charset=utf-8'});
  image.src = URL.createObjectURL(blob);
};
```

**Comment by qbx2** [comment]
@dsmilkov I committed as you suggested. Test please.

**Comment by dsmilkov** [comment]
Thanks! One last question: any reason why in the new commit, you removed the "replace" as in svgXml.replace(/\n/g,''); Is that not needed? Thanks!

**Comment by qbx2** [comment]
I used "replace" for debugging because URL must not contain any new-line characters. After checking if it would work if i remove "replace", I removed it for clearer code because both worked well.

**Comment by dsmilkov** [comment]
Great - was just curious! @vrv Good to merge!

**Comment by qbx2** [comment]
Url-encoding svgXml data would be good

**Comment by vrv** [comment]
there are conflicts unfortunately -- can you rebase so we can test and merge?

**Comment by qbx2** [comment]
@vrv test please.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
