### PR TITLE
Fix reported snyk vulnerabilities with the recommended patch

### PR DESCRIPTION
**Pull request by sspintel**

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Can you list the vulnerabilities discovered?

**Comment by sspintel** [comment]
Here's the Snyk scan report for r2.2: [TF 2.2.2 Snyk Scan Report](https://snyktf22.tiiny.site/)

These seem to have been fixed in the recent TF 2.4.x. The following are the respective commits for these fixes.

https://github.com/tensorflow/tensorflow/commit/c1e1fc899ad5f8c725dcbb6470069890b5060bc7
https://github.com/tensorflow/tensorflow/commit/eccb7ec454e6617738554a255d77f08e60ee0808
https://github.com/tensorflow/tensorflow/pull/42143/commits/3ade2efec2e90c6237de32a19680caaa3ebc2845

Getting rid of these vulnerabilities would be beneficial for users who still don't want to upgrade to the latest TF r2.4

**Comment by mihaimaruseac** [comment]
Something is wrong though. c1e1fc8 is included in TF 2.2.2, see [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v2.2.2)

Will pick the other two when we make a new patch release on the branch.

**Comment by sspintel** [comment]
Thank you @mihaimaruseac Sorry for not noticing that c1e1fc8 was already a part of r2.2.

Does this also mean the PyPi packages of r2.2 will be updated when you apply the patch? And, any idea when we can expect the patched release to happen? This information will be helpful to make decisions on my current work as it needs r2.2 to be clear of vulnerabilities. Thanks in advance! 👍

**Comment by mihaimaruseac** [comment]
We don't release timelines for the patch releases, but most likely it will happen by end of month/early April.

2.2 will get patched once this lands.

**Pull request closed without merging**
