### PR TITLE
Makefile to build TensorFlow Lite C library from source

### PR DESCRIPTION
**Pull request by Jonarod**
After using `bazel` to build the library, I experienced performance hits compared to `make`.

Just to keep record and for someone to reproduce my original issue, I left the `bazel` build steps in my repo here: [https://github.com/Jonarod/tensorflow_lite_alpine/blob/master/builder/Dockerfile.bazel](https://github.com/Jonarod/tensorflow_lite_alpine/blob/master/builder/Dockerfile.bazel).

On the same repo, one can build `libtensorflowlite_c.so` using `make` (using [this Dockerfile](https://github.com/Jonarod/tensorflow_lite_alpine/blob/master/builder/Dockerfile)) and/or `bazel` (using [this Dockerfile](https://github.com/Jonarod/tensorflow_lite_alpine/blob/master/builder/Dockerfile.bazel)) then compare performance on inference. You should see the `make`-build performs better than the `bazel` one.

### CODE REVIEW

**Comment by Jonarod** [comment]
@googlebot I signed it!

**Comment by jdduke** [comment]
What is the exact `bazel build` command you used?

**Comment by Jonarod** [comment]
@jdduke [here](https://github.com/Jonarod/tensorflow_lite_alpine/blob/master/builder/Dockerfile.bazel#L73)

**Comment by jdduke** [comment]
> You should see the make-build performs better than the bazel one.

Can you say more about the observed performance differences? How did you benchmark? Thanks for any info, we'd like to fully repro your conditions before committing to the Makefile build support.

**Comment by Jonarod** [comment]
Sure !

I used [go-tflite](https://github.com/mattn/go-tflite) that consumes the library as a C API. I started copy-pasting the example found [here](https://github.com/mattn/go-tflite/tree/master/_example/label_image) to run inference. The project requires you to have Golang installed to run the `main.go` script. The project also requires you to place `libtensorflowlite_c.so` in your `$GOPATH/tensorflow/tensorflow/tensorflow/lite/experimental/c/` and linker should also require you to place a copy of the same library in `/usr/local/lib/`.

I just did exactly that, then I ran inference by switching between the bazel-based `libtensorflowlite_c.so` and the make-based `libtensorflowlite_c.so` (Trying 50 inferences with one and then 50 other inferences with the other version). I observed that bazel-based `libtensorflowlite_c.so` is consistently twice slower than the make-based one. For instance, on my CPU machine, the same inference script using the bazel-based library could classify the sample `peacock.png` image in 300ms (on average), meanwhile the make-based library would do the same in 120ms. I reproduced these metrics very consistently with any other sample image.

I understand it is quite demanding to setup everything if you do not already work with Golang, for this reason I pushed a reproduction scenario for you [here](https://github.com/Jonarod/tensorflow_lite_alpine/tree/master/example). In this repo you will find:
- `bazel_libtensorflowlite_c.so` bazel-based built using [this Dockerfile](https://github.com/Jonarod/tensorflow_lite_alpine/blob/master/builder/Dockerfile.bazel) (don't forget to trim off the `bazel_` before use)
- `make_libtensorflowlite_c.so` make-based built using [this Dockerfile](https://github.com/Jonarod/tensorflow_lite_alpine/blob/master/builder/Dockerfile) (don't forget to trim off the `make_` before use)
- the assets to run inference including the model used and its labels, as well as the sample image
- my revised version of `main.go` with timings used for benchmarks
- a `classify-gcc-t4` binary which is the same `main.go` using 4 threads but compiled using `gcc` (so you don't need to install golang to reproduce)
- a `classify-musl-t4` binary which is the same `main.go` using 4 threads but compiled using `musl` (so you don't need to install golang to reproduce)
- an example `Dockerfile` to see basic usage

Ping me if you need anything else.

**Comment by jdduke** [comment]
Thanks for the detailed repro steps? It's possible this is a simple function of how certain paths are switched on via default when using bazel (vs Makefile). Will try to repro on our end and get back to you, but a 2x performance difference is not expected (and hopefully we can get to performance parity with bazel).

**Comment by terryheo** [comment]
Jonarod, thanks for the patch.
You're using "-O3" for Makefile but bazel uses "-O2" for "-c opt".
To get the same performance with bazel,  you need to use "bazel build -c opt --copt=-O3 <target>". 
Could you verify this?

**Comment by terryheo** [comment]
A patch was just submitted to set -O3 for Linux build (including RPI3)

**Pull request closed without merging**
