### PR TITLE
Fixes to build and run TFLite evaluation ios app

### PR DESCRIPTION
**Pull request by martin-etchart**
Minimal changes to build and run the TFLite evaluation tool on iOS.

### CODE REVIEW

**Comment by danik292** [comment]
I think its ok

**Review by DanielFrantes — APPROVED** [review]
Its simple changes of location of the files. Its ok

**Review by DanielFrantes — APPROVED** [review]
Its ok

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Please make this again master branch

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Please make this again master branch

**Comment by mihaimaruseac** [comment]
Yeah, I would say, let's close this, open a new one on master and after that lands cherrypick to the last active release branches.

**Comment by martin-etchart** [comment]
> Yeah, I would say, let's close this, open a new one on master and after that lands cherrypick to the last active release branches.

Done, you can close this one now.

**Pull request closed without merging**
