### PR TITLE
[TFLite] Add options for benchmark_model and label_image to allow fp16 for fp32 models

### PR DESCRIPTION
**Pull request by freedomtan**
Add options for benchmark_model and label_image to allow running fp32 models with fp16. Useful when testing NNPAI accelerators with fp16 capability.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by gargn — DISMISSED** [review]

**Review by shashishekhar — APPROVED** [review]

**Comment by rthadur** [comment]
@freedomtan please rebase branch

**Comment by freedomtan** [comment]
@rthadur it seems the patch is merged into master already.

**Comment by rthadur** [comment]
> @rthadur it seems the patch is merged into master already, see [c28a24b](https://github.com/tensorflow/tensorflow/commit/c28a24b5f40a2ba887981e55b8f449633a71ccda)

yes , thank you closing this PR

**Pull request closed without merging**
