### PR TITLE
Allow tf.summary.merge_all() assign operation name

### PR DESCRIPTION
**Pull request by reeze**
One may need to assign name of the MergeSummary operation

### CODE REVIEW

**Comment by josh11b** [comment]
(From API-owners) We are fine with this, but are somewhat curious if there was a motivating example where this would be needed.

**Comment by reeze** [comment]
Hi @josh11b  we are trying to embed TF to our application. we are define graph with python, train the graph with a C++ application.  

Tensorboard is great tool to visualize the graph an metrics, since we are not train with python api we can't use summary file writer.  A solution would be define summary with python and fetch in C++, so I need a name to fetch summary output, then I found that the name  is not assignable, that is the reason behind this PR.

**Comment by josh11b** [comment]
Ok, gotcha

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by drpngx — DISMISSED** [review]

**Comment by drpngx** [comment]
Can you look at the errors and fix them?

**Comment by drpngx** [comment]
It seems to be broken on Windows. Could you check?

**Comment by reeze** [comment]
@drpngx  Can you help trigger the test again, I am not sure it is related to this PR. If it persist I will try to get a windows box to debug it. thanks

**Comment by reeze** [comment]
Windows related failure didn't show up this time. but instead anther internal failure ;(

**Comment by drpngx** [comment]
Testing again. We'll initiate a pull.

**Comment by drpngx** [comment]
`gen_collective_ops` seems to be the cause. It looks like the build is broken.

**Comment by drpngx** [comment]
@reeze could you pull rebase and push again? thanks.

**Comment by reeze** [comment]
@drpngx  DONE ;)

**Comment by drpngx** [comment]
Thanks! Running tests...

**Comment by drpngx** [comment]
OK, these are weird errors... build errors against LLVM.

**Pull request merged**
