### PR TITLE
Retrain tutorial with tensorboard

### PR DESCRIPTION
**Pull request by maxmelnick**
I created a script that allows running the [Inception retraining example](https://www.tensorflow.org/versions/master/how_tos/image_retraining/index.html) with TensorBoard visualizations and figured I'd submit it so others can learn from it. It's based on the [retrain.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py) and [mnist_with_summaries.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py) scripts.

New to submitting open source PRs so let me know if there's anything else you need from me. Thanks!

### CODE REVIEW

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Comment by danmane** [comment]
Thanks for this PR!

Instead of creating a separate script with summaries, could you replace the existing retrain.py with the one with summaries? This will be easier to review, and to maintain. If we have two copies of the script (one with summaries and one without) they will go out of sync, and become very confusing.

**Comment by maxmelnick** [comment]
Sure thing! I will make the changes and update my pull request accordingly.

**Comment by maxmelnick** [comment]
I updated the PR to replace the existing retrain.py with the one with summaries. Please let me know if you need anything else.

**Comment by petewarden** [comment]
Thanks @maxmelnick ! Would you mind adding a short paragraph to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/image_retraining/index.md explaining how to view the summaries on TensorBoard?

Jenkins, test this please.

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Comment by maxmelnick** [comment]
@petewarden Will do! I'll add the paragraph for using retrain.py with TensorBoard to the doc and then update my PR.

**Comment by maxmelnick** [comment]
@petewarden If I want to include screenshots in my update to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/image_retraining/index.md where would I commit them? I can't find where the existing images that are in the file are committed in the overall tensorflow repository.

If it's too complicated to include images, I can just include the text explanation.

**Comment by vrv** [comment]
We generally don't want images in the git repository (it makes fetching the repository take longer).  I'd suggest sticking with a text description for now -- we can externally host an image-based one later if it turns out to be super helpful.

**Comment by maxmelnick** [comment]
Sounds good! I finished adding a section to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/image_retraining/index.md explaining how to view the summaries on TensorBoard and updated the PR accordingly. Thanks!

**Comment by petewarden** [comment]
Thanks for the doc updates @maxmelnick! They all look good to me.

Jenkins, test this please.

**Comment by maxmelnick** [comment]
👍 Thanks @petewarden! Let me know if you need anything else from me.

**Comment by petewarden** [comment]
All good, thanks for this @maxmelnick !

**Comment by maxmelnick** [comment]
You're welcome! Happy to contribute 😄

**Comment by shaolinkhoa** [comment]
Hi @maxmel,
Thank you for your example code.

Would you mind adding the option input-image are both JPEG and PNG.
I tried to change the code but I don't get error on "DecodePng/contents:0"

thank you,
Khoa

**Comment by argavish** [comment]
Hey @maxmelnick and co.,
Is there an example containing also the embedding visualization?
Thanks!

**Comment by maxmelnick** [comment]
@argavish - I'm not aware of a version of this image retraining example that contains the embedding visualization. Maybe a good opportunity for a new pull request? 

Assuming you've seen this? _TensorBoard: Embedding Visualization_ https://www.tensorflow.org/get_started/embedding_viz

**Comment by argavish** [comment]
Thanks @maxmelnick !
Yep, seen this :) 
Working on it, I'll upload the script as soon as I crack it..

**Pull request merged**
