### PR TITLE
Update seq2seq.py: To avoid error thread.lock

### PR DESCRIPTION
**Pull request by mandar1010**
Issue: Can't pickle thread.lock object 
https://github.com/tensorflow/tensorflow/issues/11157

### CODE REVIEW

**Comment by mandar1010** [comment]
cla signed

**Comment by frankchn** [comment]
Jenkins, test this please.

**Review by ebrevdo — CHANGES_REQUESTED** [review]
Can you add a unit test that would break before this change?

**Comment by martinwicke** [comment]
@mandar1010 any update?

**Comment by martinwicke** [comment]
Closing as stalled. Please reopen with a test.

**Pull request closed without merging**
