### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tchugh**
Correct MobilenetV1 variable

### CODE REVIEW

**Comment by tchugh** [comment]
I signed it!

Best Regards

Tarang Chugh <http://tchugh.github.io>
PRIP Lab, MSU <http://biometrics.cse.msu.edu>
chughtar@msu.edu | +1-517-515-2575

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rmlarsen** [comment]
@aselle can you take a look?

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rmlarsen** [comment]
@aselle does this look OK?

**Review by rmlarsen — APPROVED** [review]

**Pull request merged**
