### PR TITLE
[INTEL MKL]: ADD Tensorflow MKL-DNN Singularity definition files

### PR DESCRIPTION
**Pull request by karthikvadla**
This PR adds Singularity definition files for intel-optimized tensorflow

### CODE REVIEW

**Comment by karthikvadla** [comment]
@penpornk @martinwicke here is a PR for adding singularity definition files.

**Comment by karthikvadla** [comment]
I closed that old PR to re-write singularity definition files from scratch instead of converting docker binaries to singularity. 
This is a new PR with all re-written files.

**Comment by karthikvadla** [comment]
@martinwicke please let me know what do you think.

**Comment by martinwicke** [comment]
I still see no reason to have these files in the TensorFlow repo. We cannot maintain them, and putting core TensorFlow developers into a modification loop seems like a bad idea. I would maintain these in a separate repo, I can see no downside to that.

**Pull request closed without merging**
