### PR TITLE
Fix invalid shape issue in random.uniform

### LINKED ISSUE #34363: random.uniform((),minval,maxval) returns array instead of scalar tensor when min or maxval is not a scalar tensor
```
>>> import tensorflow as tf
>>> scalar = tf.zeros(shape=())
>>> array = tf.zeros(shape=(1,))

>>> tf.random.uniform(shape=(),minval = scalar)
<tf.Tensor: id=25, shape=(), dtype=float32, numpy=0.021499991>

>>> tf.random.uniform(shape=(),minval = array)
<tf.Tensor: id=31, shape=(1,), dtype=float32, numpy=array([0.9388697], dtype=float32)>
```
Expected behavior is to either trow an error or treat single element tensor as scalar and return a scalar.

-win10, tf2, cuda

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to address the issue raised in #34363 where
invalid shape passed to minval/maxval (expected to be 0-D)
does not raise an error.

The issue was that in most of the scenarios the shape was
checked inside the C++ kernel ops.

However, in one condition math_ops.add was used which will
implicitly do broadcast when necessarily.
This results in maxval/minval's shape getting carried.

This PR adds the shape check before math_ops.add, to make
sure the shape is guaranteed.

This PR fixes #34363.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by alextp — DISMISSED** [review]

**Comment by gbaned** [comment]
@yongtang Could you please check failed build errors? Thanks!

**Comment by yongtang** [comment]
Thanks @alextp @gbaned for the review. The PR has been updated to fix the failed tests.

**Review by alextp — APPROVED** [review]

**Comment by gbaned** [comment]
@yongtang Here is the internal error we are getting , can you please check this.

> google3/third_party/py/six/__init__.py", line 737, in raise_from
    raise value
InvalidArgumentError: Function invoked by the following node is not compilable: name: "__forward_call_512" op: "__forward_call_512" input: "dummy_input" input: "dummy_input" input: "dummy_input" input: "dummy_input" input: "dummy_input" input: "dummy_input" input: "dummy_input" input: "dummy_input" input: "dummy_input" attr { key: "_XlaCompile" value { b: true } } attr { key: "config_proto" value { s: "\n\007\n\003CPU\020\001\n\016\n\nTPU_SYSTEM\020\001\n\007\n\003TPU\020\002\n\007\n\003GPU\020\0002\002J\0008\001" } } attr { key: "executor_type" value { s: "" } }.
Uncompilable nodes:

**Comment by yongtang** [comment]
Thanks @gbaned, the log is quite hard to interpret, I am wondering if there are any other information I could see? For example, can I get the code snippet that related to this error?

**Comment by sanjoy** [comment]
> Thanks @gbaned, the log is quite hard to interpret, I am wondering if there are any other information I could see? For example, can I get the code snippet that related to this error?

The test breaks because `EnsureShape` is not implemented for XLA, and with your change we generate `EnsureShape` in graphs where we wouldn't before.  Can you please add an XLA kernel for `EnsureShape` (preferably in a separate PR)?  Let me know if you need help.

**Comment by yongtang** [comment]
Thanks @sanjoy. I will take a look and add XLA EnsureShape kernel first.

**Comment by gbaned** [comment]
@yongtang Any update on this PR, please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 16 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by yongtang** [comment]
Sorry for the late reply. Was out of the office during the year end and was only back last week. I will update and work on XLA EnsureShape shortly.

**Comment by gbaned** [comment]
@yongtang Any update on this PR, please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@yongtang Any update on this PR and can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Comment by yongtang** [comment]
Sorry for the long wait. I have created #38544 to fix the ensure_shape issue. Once the #38544 is merged, this PR will be re-opened for a final fix.

**Pull request closed without merging**
