### PR TITLE
[INTEL MKL]: Enable quantization using MKL-DNN

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR removes the #ifdef INTEL_MKL_QUANTIZED to enable quantization in the default build.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR! Does this PR still depend on any other unmerged PRs, or is it ready to merge now?

**Comment by mahmoud-abuzaina** [comment]
@penpornk thank you for the quick review. This PR is ready to be merged. Other INT8 PRs are coming but this PR is not dependent on any of them.

**Comment by mahmoud-abuzaina** [comment]
Hi @pragyaak, is there anything blocking this from being merged?

**Comment by pragyaak** [comment]
@mahmoud-abuzaina yes, I am looking into it. Will update here.

**Comment by pragyaak** [comment]
@mahmoud-abuzaina this is now done. Thanks!

**Comment by mahmoud-abuzaina** [comment]
@pragyaak Thank you too!

**Pull request merged**
