### PR TITLE
Fix the unexpected behavior of RandomUniform in the eager mode

### LINKED ISSUE #23882: The same op seed gives different results in eager execution
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux openSUSE Leap 42.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: none
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6.4
- Bazel version (if compiling from source): none
- GCC/Compiler version (if compiling from source): none
- CUDA/cuDNN version: none
- GPU model and memory: none

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

```
import tensorflow as tf

tf.enable_eager_execution()

a = tf.random_uniform((3, ), seed=0)
b = tf.random_uniform((3, ), seed=0)
print(a)
print(b)
```

prints

```
tf.Tensor([0.10086262 0.9701668  0.8487642 ], shape=(3,), dtype=float32)
tf.Tensor([0.5689162  0.31256282 0.09009469], shape=(3,), dtype=float32)
```

When run in a graph, the output is the same.

**Describe the expected behavior**

I would have expected the output to be same in eager mode as well, just like in graph mode.

### PR DESCRIPTION
**Pull request by feihugis**
This PR fixes #23882. It may also be related to #23407. cc: @alextp  

In the eager mode, the kernels are cached to improve the performance, where the `cache_key` is generated based on the Op's attributes. That means, two Ops with the same attributes will use the same cached kernel. However, this will cause some unexpected behaviors for RandomUniform as described in #23882. 

This PR adds an `op_id` attribute to `RandomUniform` Op to enable users to decide whether to reuse the cached RandomUniform kernel or create a new RandomUniform kernel.

### CODE REVIEW

**Comment by alextp** [comment]
@josh11b @asimshankar we have a longer-term plan to improve the random state situation but this is an acceptable short-term fix (in principle; I haven't looked at the details carefully). What should we do?

**Comment by feihugis** [comment]
Thank you, @alextp! @josh11b @asimshankar Do you have any suggestion/comments on this PR?

**Comment by feihugis** [comment]
A kindly reminder that this PR has been a while. @alextp @josh11b Do you get a chance to review this PR?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alextp, @josh11b: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by alextp** [comment]
I'm closing this as we'd like to address these problems with the more comprehensive solution described in https://github.com/tensorflow/community/pull/38 . Can you comment on that RFC instead?

Thanks!

**Pull request closed without merging**
