### PR TITLE
Update callbacks.py corrected term names in doc

### PR DESCRIPTION
**Pull request by rasenganai**
In reference to the issue #34965 
Corrected the "accuracy" and "val_accuracy" terms as returned by the callback (history object) instead of the short documented versions acc/val_acc .

### CODE REVIEW

**Comment by Jaskaran170599** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
@Jaskaran170599 Can you please resolve conflicts? Thanks!

**Comment by Jaskaran170599** [comment]
@gbaned conflicts resolved , please review.

**Comment by fchollet** [comment]
Closing outdated PR, sorry that we weren't able to review it in time.

**Pull request closed without merging**
