### PR TITLE
Wrong Copyright/license info in core/lib/io files, originated in LevelDB

### PR DESCRIPTION
**Pull request by PetrProkopNXP**
Duplicite with issue #43015
--------------------------------

Hi TensorFlow authors,
My name is Petr Prokop, I serve in NXP as a Trusted Advisor – person in charge of SW licenses compliance.
NXP adapts TensorFlow for its i.MX processors. Such releases are subject of license-compliance check.

Unfortunately, our scanning tool (Black Duck Protex by Synopsis) has reported following license breach:
TensorFlow file https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/cache.cc is very similar to
LevelDB file https://github.com/google/leveldb/blob/master/util/cache.cc.

Likewise, files
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/cache.h
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/cache_test.cc
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/table.cc
are reported to be similar to
https://github.com/google/leveldb/blob/master/include/leveldb/cache.h
https://github.com/google/leveldb/blob/master/util/cache_test.cc
https://github.com/google/leveldb/blob/master/table/table.cc.

As many SW tools, Black Duck Protex has only limited efficiency, so I’ve found some further files in core/lib/io directory during my investigation manually.

My understanding is, that TensorFlow reuses LevelDB files, that is pretty fine according original LevelDB license (BSD-3-Clause). However, changing both copyright and license breaches claim #1 of BSD. I wouldn’t dare to advise you anything, but described state is an obstacle for using TF by NXP. Simultaneously, our internal policy prohibits to change 3rd party copyrights, even if they were wrong.

Can I ask you to allow update of *.h, *.cc and addition of Authors/License_LevelDB.txt files in your repository?

Feel free change exact wording of “Modification” clause and/or formatting.

Regards,
Petr

### CODE REVIEW

**Comment by gbaned** [comment]
@PetrProkopNXP Thank you for your contribution. Can you please sign CLA? Thanks!

**Comment by gbaned** [comment]
@PetrProkopNXP Any update on this PR? Please. Thanks!

**Comment by mihaimaruseac** [comment]
Based on #43015 I think this can be closed.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
