### PR TITLE
Fix Succesful to Successful.

### PR DESCRIPTION
**Pull request by Yulv-git**

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @bmzhao Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bmzhao Can you please review this PR ? Thank you!

**Comment by mihaimaruseac** [comment]
Please fix more than just one single letter typos.

**Comment by mihaimaruseac** [comment]
Brian does not work in TF for more than a year, removing assignment.

**Pull request closed without merging**
