### PR TITLE
add debian stretch Dockerfile (CPU)

### PR DESCRIPTION
**Pull request by reza-ebrahimi**

### CODE REVIEW

**Comment by angersson** [comment]
We use the Dockerfiles under `ci_build` mostly for internal release architecture. If you're submitting this for general use, you'll need to place it in `tools/docker`, where none of these helper scripts are available.

Also, we are currently reviewing https://github.com/tensorflow/community/pull/8, which would totally restructure how *those* Dockerfiles are maintained (because they are widespread and messy). Please take a look at that doc if you're interested in improving the Dockerfiles.

**Review by angerson — CHANGES_REQUESTED** [review]
(see my comment on this PR)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request closed without merging**
