### PR TITLE
support fixed64 in features parser .

### PR DESCRIPTION
**Pull request by zhaozheng09**
### Current:
1. Our model have 900+ features(will be expanded to 2000 features within one year).
2. We run tensorflow on A100 machine, and our model currently consumes TFRecord very fast, now 1700,000 TFRecords/s. PS:We replace TFRecord reader from disk to high-performance network and memory cache.
After the above change, we find deserialize varint64 is very hot, so we check how to decode varint64 in pb.

### Varint64 and Fixed64

**Varint64:** A variable-length storage format, the details:https://developers.google.com/protocol-buffers/docs/encoding
**Fixed64**: A fixed-length storage format, fixed use 64bit to save uint64_t
Decoding varint64 needs two loop.
1. Check whether the highest bit of each byte is 1
2. Iterate and decode each byte, and then compose each byte into uint64_t
Varint64 decodes very fast when the number is small, such as using 2-3 bytes numbers(1bytes special deal).

### Why we replace Varint64 to fixed64:

But unfortunately, because our confidential data, we have to save big hash values.The storage of the hash value usually uses 7-8 bytes, and varint64 is very unfriendly to decode the hash value.
so I want to replace from varint64 to fixed64, we have **a small test in _protobuf_**, through varint64 and fixed64 decoding the same hash data, we get fixed64 10 times faster than varint64.(The example is a bit complicated, but I can provide it if necessary)

**Do you think it is necessary for TF to add the fixed64 type? If necessary, I can contribute this part of the code.**

 ### Remarks some profiling result:
image
image
image

### CODE REVIEW

**Comment by zhaozheng09** [comment]
@gbaned I have not developed this feature at present, I would like to know if this feature is needed? and reviewer hasn't been online for a long time.

**Comment by zhaozheng09** [comment]
> @gbaned I have not developed this feature at present, I would like to know if this feature is needed? and reviewer hasn't been online for a long time.

Hi @gbaned

**Comment by gbaned** [comment]
@rohan100jain  Can you please assist on above comments from @zhaozheng09. Thanks!

**Comment by zhaozheng09** [comment]
> There is already a bytes field; what about just `tf.bitcast`ing to/from an array of bytes?

Maybe it's a good idea~ I will try it.

**Comment by zhaozheng09** [comment]
> > There is already a bytes field; what about just `tf.bitcast`ing to/from an array of bytes?
> 
> Maybe it's a good idea~ I will try it.

@allenlavoie 
I successfully write data with bytes type, then I find a question that decoder output tf.string, and tf.bitcast don't support tf.string.
decoder support type:
parse_example only support  ````tf.float32` (`FloatList`), `tf.int64` (`Int64List`), and `tf.string` (`BytesList`) are supported. ```
tf.bitcast tips:
```TypeError: Value passed to parameter 'input' has DataType string not in list of allowed values: bfloat16, float16, float32, float64, int64, int32, uint8, uint16, uint32, uint64, int8, int16, complex64, complex128, qint8, quint8, qint16, quint16, qint32```

**Comment by allenlavoie** [comment]
Sorry, misread your comment. You're saying it's coming out as a tf.string dtype and you want it as uint8/int8/etc. again so you can bitcast it back? For that I would suggest inserting `tf.io.decode_raw` on the string to get it back to a dense array of bytes.

**Comment by gbaned** [comment]
@zhaozheng09 Any update on this PR? Please. Thanks!

**Comment by zhaozheng09** [comment]
> Please try Allen's suggestion to see if that works. Other than that, would be okay adding this field to the proto but tf.Example is used a fair amount and we'll have to update all the places its parsed
> 
> https://cs.opensource.google/search?q=int64_list&sq=&ss=tensorflow
> 
> If we can do that, it'll be fine adding this.

get I will try .

**Comment by zhaozheng09** [comment]
> Sorry, misread your comment. You're saying it's coming out as a tf.string dtype and you want it as uint8/int8/etc. again so you can bitcast it back? For that I would suggest inserting `tf.io.decode_raw` on the string to get it back to a dense array of bytes.

get I will try it.

**Comment by zhaozheng09** [comment]
@allenlavoie  ```decode_raw``` looks okay.
 Do we still need this pr, if not, I will close this pr.
cc @rohan100jain

**Comment by rohan100jain** [comment]
If decode_raw works for you, then we can close the PR

**Comment by zhaozheng09** [comment]
> If decode_raw works for you, then we can close the PR

thx

**Pull request closed without merging**
