### PR TITLE
Fixes Github #47520 Step number of batch_steps_per_second 

### LINKED ISSUE #47520: TensorBoard callback: step is always 0 for batch_steps_per_second
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.2.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-51814-gb08c055e840 2.5.0-dev20210301
- Python version: 3.8.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
The current tf-nightly (for 2.5.0) has  a new parameter  `write_steps_per_second` to tf.keras.callbacks.TensorBoard.
If that is used with `update_freq` > 0, the resulting batch_steps_per_second all have `0` as step value, which makes the graph unreadable in tensorboard.

**Describe the expected behavior**
The step number is the corresponding training step

**Standalone code to reproduce the issue**
```
import shutil
import glob
import tensorflow as tf
from tensorflow.core.util import event_pb2

workdir = 'tmp_workdir/'
shutil.rmtree(workdir, ignore_errors=True)

x = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [0, 1, 1, 0]

inputs = tf.keras.Input(shape=(2,))
outputs = tf.keras.layers.Dense(units=1, activation='sigmoid')(inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

model.compile(optimizer=tf.keras.optimizers.Adam(), loss=tf.keras.losses.MeanSquaredError())

model.fit(x=x, y=y, batch_size=2, epochs=2, callbacks=[
    tf.keras.callbacks.TensorBoard(log_dir=workdir, write_steps_per_second=True, update_freq=1,
                            profile_batch=0)])

max_step = 0
for record in tf.data.TFRecordDataset(glob.glob(workdir + 'train/events.out*')[0]):
    event = event_pb2.Event.FromString(record.numpy())
    if event.HasField('summary') and event.summary.value[0].tag == 'batch_steps_per_second':
        max_step = max(max_step, event.step)

if max_step == 0:
    print("FAILURE")
else:
    print("OK")
```

**Other info / logs** 
The step number 0 comes from passing `step.value()` instead of `step` in _push_writer. There is a TODO saying `# TODO(b/151339474): Fix deadlock when not using .value() here.` above that line - I suppose the details are in some internal google bug database.

But as the `batch_steps_per_second` event is only written during training, this can easily be fixed by explicitly passing  self._train_step  as step when writing it.

I'll add a pull request.

### PR DESCRIPTION
**Pull request by brychcy**

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM

**Comment by gbaned** [comment]
@brychcy Can you please address Ubuntu Sanity errors? Thanks!

**Comment by brychcy** [comment]
> @brychcy Can you please address Ubuntu Sanity errors? Thanks!

I'll have a look.

Problem is:
```
Found 1 non-allowlisted pylint errors:
tensorflow/python/keras/callbacks.py:2448: [C0301(line-too-long), ] Line too long (97/80)`
```

**Comment by brychcy** [comment]
@gbaned, Fix is pushed. 
I guess I cannot retrigger those checks myself, right?

**Comment by brychcy** [comment]
@gbaned, my updated patch just added a linebreak to the patch already approved by @fchollet.
do you really think he needs to approve it again?

**Comment by gbaned** [comment]
> @gbaned, my updated patch just added a linebreak to the patch already approved by @fchollet.
> do you really think he needs to approve it again?

@brychcy  There are commits after approved by @fchollet. Hence it requires approval again. Thanks!

**Review by fchollet — APPROVED** [review]
LGTM

**Pull request merged**
