### PR TITLE
the prority of session config

### PR DESCRIPTION
**Pull request by zhaozheng09**
https://github.com/tensorflow/tensorflow/issues/52938

### CODE REVIEW

**Comment by jsimsa** [comment]
Re-assigning to @mhong for triage.

**Comment by gbaned** [comment]
@mhong Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@[bramandia](https://github.com/bramandia) Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@bramandia Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
@bramandia Can you please review this PR ? Thank you!

**Review by mihaimaruseac — COMMENTED** [review]
Wouldn't this duplicate existing config? As in `existing, argument, existing`?

**Comment by gbaned** [comment]
Hi @zhaozheng09 Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!

**Comment by zhaozheng09** [comment]
I'm really sorry, I don't have time to perfect this PR for now, let's talk about it next time we meet.

**Pull request closed without merging**
