### PR TITLE
Fix typo 'updaye' in audio_recognition.md

### PR DESCRIPTION
**Pull request by fdzzy**
Fix typo 'updaye' to 'update' in audio_recognition.md

### CODE REVIEW

**Comment by patrickzzy** [comment]
I signed it!

**Comment by drpngx** [comment]
I can't find your CLA in the database. Could you double check?

**Comment by patrickzzy** [comment]
I just checked my existing CLA data, there is one agreement. Is the email case sensitive? Or does the name in CLA need to match the one in the commit?

**Review by drpngx — APPROVED** [review]
OK, it seems that the bot got unstuck.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Pull request merged**
