### PR TITLE
Cherry-pick some fixes into r0.7 branch

### PR DESCRIPTION
**Pull request by vrv**
gfile changes are necessary for input_data.py

tensorboard requires polymer 1.2.4, so updating the workspace entry

### CODE REVIEW

**Comment by jendap** [comment]
The polymer should fix tensorboard! Nice!

Why is the gfile still failing? Should this fix the mac python3 build?

**Comment by vrv** [comment]
it's failing in python3 test only -- do you want me to cherry pick that fix too? :)

**Comment by vrv** [comment]
Eh, why not.  @tensorflow-jenkins: test this please.

**Comment by vrv** [comment]
Does this look good? I can merge if so.

**Comment by vrv** [comment]
Closing, going to do all of this on a separate branch until we get it working.

**Pull request closed without merging**
