### PR TITLE
[tflite] Metal GPU delegate: improve op scheduling

### PR DESCRIPTION
**Pull request by LK**
Improve how we schedule ops to the GPU. Rather than reverting all ops to the CPU once we encounter a CPU op in the linear execution plan, we now only move ops to the GPU if any of their inputs are not computable on the GPU. This allows two parallel branches to both be partially scheduled on the GPU.

This seems to work for my model, but not familiar with TFLite internals enough to determine if this is going to cause any unexpected downstream problems or thrashing.

### CODE REVIEW

**Review by impjdi — COMMENTED** [review]
Without proper testing of various network shapes, I would be very hesitant to approve this change.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by impjdi** [comment]
@mellanox-github 

Without full unit testing of various network scenarios, it's going to be hard to verify the validity of this.  "This seems to work for my model, but not familiar with TFLite internals enough to determine if this is going to cause any unexpected downstream problems or thrashing."  is not going to be good enough, and Google products use this too =/

**Comment by LK** [comment]
@impjdi of course — I’m hoping that somebody on the TF team with more context around this code path can shed some light on how things are moved to/from the GPU and any potential problems this change might cause there.

As for unit tests, I mentioned this in one of my other PRs, but I’m not sure how to run unit tests for the Metal kernel, since AFAIK they can’t run on the simulator. If you could point me in the right direction there, I can definitely go back and add tests here!

**Comment by rthadur** [comment]
@LK any updates ?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by LK** [comment]
@rthadur @impjdi is there any way for me to run the unit tests for the Metal GPU delegate? At least this way I could put together a test suite to test various network configurations.

**Comment by rthadur** [comment]
reassigning to @NikolayChirkov

**Comment by NikolayChirkov** [comment]
@LK We're working on xcode project for testing operations and models

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
