### PR TITLE
fix Windows build errors

### PR DESCRIPTION
**Pull request by jgehw**
fix some more build errors of the kind already addressed in #42676:

compiler doesn't get that LOG(FATAL) macro eventually calls std::abort() and complains with "method doesn't return a value", so call abort explicitely

### CODE REVIEW

**Comment by joker-eph** [comment]
This looks redundant to me: can we find a solution to make LOG(FATAL) work with MSVC? Either adding the abort more prominently there, or use an attribute or any annotation that would appease MSVC?

Alternatively: can a flag be added to the MSVC configuration to disable this warning/error?

**Comment by jgehw** [comment]
> This looks redundant to me: can we find a solution to make LOG(FATAL) work with MSVC? Either adding the abort more prominently there, or use an attribute or any annotation that would appease MSVC?

Due to the fact that the LOG macro expands to a subclass of std::ostringstream, I don't see a way to place abort() anywhere else than in the destructor and at the same time keep the semantics of the LOG macro.

> Alternatively: can a flag be added to the MSVC configuration to disable this warning/error?

It's an error (I wouldn't have submitted this PR just to silence a false warning ;-) ), or rather it's tons of error C4716, for example:
```
C:\tools\vcpkg\buildtrees\.bzl\_bazel_jgehweil\e7zqzfy3\execroot\org_tensorflow\tensorflow\compiler\xla\literal.cc(1391) : error C4716: 'xla::`anonymous namespace'::BitcastBetweenNativeTypes<short,signed char>': must return a value
```

**Comment by jgehw** [comment]
In the documentation of the MSVC compiler, I only found switches to handle warnings (suppress them or raise them like errors), but not errors. Nevertheless, I gave it a try to see if the suppress warning switch would also suppress an error, and added the according switch `/wd4716` to `./tensorflow/BUILD` like this:
```
tf_cc_shared_object(
    name = "tensorflow_cc",
    linkopts = select({
        "//tensorflow:macos": [
            "-Wl,-exported_symbols_list,$(location //tensorflow:tf_exported_symbols.lds)",
        ],
        "//tensorflow:windows": [],
        "//conditions:default": [
            "-z defs",
            "-Wl,--version-script,$(location //tensorflow:tf_version_script.lds)",
        ],
    }) + select({
        "//tensorflow:msvc_cl_debug": [
            "/DEBUG:FASTLINK",
            "/wd4716",
        ],
        "//conditions:default": [],
    }),
    per_os_targets = True,
```
But it kept failing with the C4716 error. So, in the end I don't see any better solution than mine.

**Comment by sanjoy** [comment]
The MSVC [doc](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4716?view=msvc-160) suggests using `#pragma`; WDYT about putting that in the header that defines the `LOG` macro?

**Review by sanjoy — CHANGES_REQUESTED** [review]
As per previous comment to try using `#pragma`.

**Comment by jgehw** [comment]
> As per previous comment to try using `#pragma`.

I tried to build it with the suggested `#pragma` solution, and it actually worked (through it just disables a warning and the compiler was reporting an error previously).

I updated the PR accordingly.

**Review by sanjoy — APPROVED** [review]

**Pull request merged**
