### PR TITLE
[Java] Ability to load from SavedModel

### LINKED ISSUE #7134: [Java] [Feature] Load from SavedModel
Make it possible for the Java library to load exported TF models in SavedModel format.   

Outline of the proposed design:
1. Define a new class `SavedModelBundle` to represent the loaded saved model.  Properties include the graph, session, and metagraphdef.
2. Define a static method on `SavedModelBundle` to load from disk, given an export path and some tags.

```
class SavedModelBundle implements AutoCloseable { 
  public Graph graph() { ... }
  public Session session() { ... }
  public byte[] metaGraphDef() { ... }
  public void close() { /* close the session and graph */ }
  public static SavedModelBundle loadSavedModel(String exportDir, Set<String> tags) { ... }
}
```

3. Write a JNI method to support loading, based on `TF_LoadSessionFromSavedModel` from the C API.

### PR DESCRIPTION
**Pull request by asimshankar**
This PR is exactly the same as #7688 with updates to the BUILD file to make tests pass so that we can merge the changes in.

Closes #7134 and #7688 

@EronWright : Not sure if you saw updates to #7688 asking for tweaks to the PR to make the tests pass. If you want to update that PR instead, I'm happy to abandon this one. Otherwise, will merge this one in and abandon the other.

### CODE REVIEW

**Comment by asimshankar** [comment]
Setting "cla:yes" since the commits authored by @EronWright are exactly the same as in PR #7688 which he proposed.

**Review by jhseu — APPROVED** [review]

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by EronWright** [comment]
Thanks @asimshankar for the tweaks and for driving this through.

**Comment by jhseu** [comment]
Ah, I probably shouldn't have squashed so we could preserve the correct `git blame` history.

**Comment by EronWright** [comment]
@jhseu yes that saddens me a little but don't worry about it

**Pull request merged**
