### PR TITLE
replaced builtin `all` by `np.all`

### PR DESCRIPTION
**Pull request by KristianHolsheimer**
For reasons that I cannot understand, the builtin function `all` is somehow overridden by `K.all`.

To make things even more complicated, it depends on the details of the computation graph. It doesn't happen for all configurations. I tried to create a minimal test case so that others might be able to reproduce it, but I can't... so here are my suggestions to reproduce (in version 1.14 and up):
```
$ git clone git@github.com:KristianHolsheimer/keras-gym.git
$ cd keras-gym/script/atari/
$ python3 ppo.py
```
This will throw the following error at the line that I edited in the commit:
> TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

To have a closer look at what the python interpreter sees, I added some lines just above the changes:
```python
try:
  bool(all(input_shape[1:]))
except:
  import inspect
  print(inspect.getsource(all)
  raise
```
Prints the following code snippet:
```python
@keras_export('keras.backend.all')
def all(x, axis=None, keepdims=False):
  """Bitwise reduction (logical AND).

  Arguments:
      x: Tensor or variable.
      axis: axis along which to perform the reduction.
      keepdims: whether the drop or broadcast the reduction axes.

  Returns:
      A uint8 tensor (0s and 1s).
  """
  x = math_ops.cast(x, dtypes_module.bool)
  return math_ops.reduce_all(x, axis, keepdims)
```

Very strange indeed. 

I feel like I've already lost a lot of time on this, so to solve my problem I propose to use the numpy version. It's a only a tiny change.

If you'd like to dig deeper into this very strange behavior, let me know.

Either way, I hope we can get this resolved quickly.

Thanks,
Kris

### CODE REVIEW

**Comment by KristianHolsheimer** [comment]
I forgot to mention something important.. this is happening in `tf.keras.models.clone_model()`.

**Comment by KristianHolsheimer** [comment]
@qlzh727 Would you be able to have a look at this? The changeset is tiny.

If you'd like to investigate the unexpected behavior of `tf.keras.models.clone_model()` I can open a new issue for that specifically.

**Comment by qlzh727** [comment]
Sorry for the very late reply.

I think we will need to understand the root cause, rather than workaround the issue like this. If this is related to save model, we could get more weird issue if the root cause is not fixed.

**Comment by qlzh727** [comment]
Adding Kathy since the issue is somehow related to save model.

**Comment by qlzh727** [comment]
@KristianHolsheimer, on a side note, it will be nice to have a bug tracking this, rather than in a PR.

**Comment by KristianHolsheimer** [comment]
Okay, in that case I'll see if I can create a minimal example to reproduce this and file an issue with that.

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@KristianHolsheimer Any update on this PR, please.

**Comment by KristianHolsheimer** [comment]
Sorry, I haven't had time to create a minimal example to reproduce. The steps to reproduce that I mentioned in my original post should still work.

I did write a little function that patches tensorflow with the minor change in this PR, because I wanted to move on.

So to reproduce, you could checkout the commit before this patch:
```
$ git clone git@github.com:KristianHolsheimer/keras-gym.git
$ python3 -m pip install -e ./keras-gym
```
Comment out [line 13 of `keras_gym/base/patches.py`](https://github.com/KristianHolsheimer/keras-gym/blob/master/keras_gym/base/patches.py#L13), the one that calls `_monkey_patch_tensorflow()`.

After that, you can run e.g. the atari/ppo script (which is how I stumbled upon this):
```
$ cd keras-gym/script/atari/
$ python3 ppo.py
```

**Review by k-w-w — APPROVED** [review]

**Comment by k-w-w** [comment]
Thanks!

**Pull request merged**
