### PR TITLE
Add synthetic datasets fix

### LINKED ISSUE #5314: Add more "synthetic" datasets in the `contrib.learn`
The feature request is as in the title -- having synthetic datasets for demo purposes, and to see how different algorithms behave would be beneficial. It is fairly straightforward to generate two-dimensional multi-class set for a lot of synthetic problems.

### PR DESCRIPTION
**Pull request by z-a-f**
This fixes #5314 and #5315  that was reverted by #6288 by re-introducing a fix by @comicchang in  #6283 . Fix #6283 was not merged as it was submitted after #6288 reverted it.  

The error was that `import tensorflow as tf` is not allowed (sorry didn't know that).
I think I checked everything, lgtm

@ilblackdragon @caisq @martinwicke

### CODE REVIEW

**Comment by zafartahirov** [comment]
@comicchang Could you sign the CLA? I didn't rewrite my commit to add your changes, I added your changes directly. As you are a contributor, you need to sign it :)

**Comment by zafartahirov** [comment]
My bad @comicchang, it doesn't need CLA, it says you need confirm here that you are OK with this PR

> 😕 The bad news is that it appears that one or more commits were authored by someone other than the pull request submitter. We need to confirm that they're okay with their commits being contributed to this project. Please have them confirm that here in the pull request.

**Comment by comicchang** [comment]
@zafartahirov I've already sighed the CLA
I'm ok with this PR

But...didn't my PR/commits already merged to the master?

**Comment by zafartahirov** [comment]
@comicchang No it didn't, it was revoked before the merge was complete

**Comment by comicchang** [comment]
@zafartahirov
I'm confused, but l'm sure the PR was already merged.

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/learn/python/learn/datasets

https://github.com/tensorflow/tensorflow/commit/81eae9ac713e02b6d36785de8b7f29258601592b

**Comment by zafartahirov** [comment]
That's odd, when I was reading the #6288 it was saying that it got cancelled -- my bad, will close it now

**Comment by zafartahirov** [comment]
I know what happened - You are right, I checked it now - I was reading an old thread from #6283 before you reverted the changes - disadvantage of keeping open tabs as my "todo-list", my bad :)

**Comment by comicchang** [comment]
That's ok.
Have a good day :)
Zafar Takhirov <notifications@github.com>于2016年12月21日 周三下午2:17写道：

**Pull request closed without merging**
