### PR TITLE
Added doc for all application models for decode_prediction() and preprocess_input()

### LINKED ISSUE #37021: There are no documentations related to decode_predictions() and preprocess_input() in any keras.applications
## URL(s) with the issue:
[https://www.tensorflow.org/api_docs/python/tf/keras/applications?version=nightly](https://www.tensorflow.org/api_docs/python/tf/keras/applications?version=nightly)

## Description of issue (what needs changing):
The doc corresponding to these two functions must be added in each application model doc.

Are you planning to also submit a pull request to fix the issue? 
Yes, Will mention these issue soon in those PRs.

### PR DESCRIPTION
**Pull request by ashutosh1919**
Fixes #37021.
Added doc for the two functions since there are Issues being created for it.

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
@ashutosh1919 can you please resolve conflicts? Thanks!

**Comment by ashutosh1919** [comment]
> @ashutosh1919 can you please resolve conflicts? Thanks!

@gbaned , I have resolved conflicts.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by ashutosh1919** [comment]
@gbaned , Please merge this one.

**Comment by mihaimaruseac** [comment]
It is going to be merged automatically once internal review and testing passes.

**Pull request merged**
