### PR TITLE
Update interpreter.cc

### PR DESCRIPTION
**Pull request by smitshilu**
Updated file to remove condition, reduce complexity and reduced lines.

### CODE REVIEW

**Comment by smitshilu** [comment]
@ekelsen Can you please check this changes?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by case540** [comment]
It seems like there are conflicts. Please fix merge conflicts and ill get someone to review this.

**Comment by case540** [comment]
Sorry, I should have taken a closer look at this before asking you do fix the conflicts. Since this PR just changes around one if statement, going to close.

**Pull request closed without merging**
