### PR TITLE
Adding support for Linux s390x in sparse_split_op

### PR DESCRIPTION
**Pull request by namrata-ibm**
Changing the data type of split_dim to resolve sparse_split_op_test failure on Big Endian System.

### CODE REVIEW

**Comment by namrata-ibm** [comment]
The split_dim in sparse_split_op.cc is int32 type which causes the column wise tests(where split_dim should be 1) to fail on Big Endian system as the "context->input(0).scalar<int>()();" returns 0 all the time.

Could you review the change please?

**Review by rohan100jain — APPROVED** [review]

**Comment by rohan100jain** [comment]
Jenkins, test this please

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Could we add a test for this?

**Comment by namrata-ibm** [comment]
The int64 data type change in this Op file is related to the `//tensorflow/python/kernel_tests:sparse_split_op_test`.  With above change test case is passing on big endian as well as little endian machine. @drpngx , Are you referring to any other test here?

**Comment by drpngx** [comment]
I guess I'm looking for something that would test that specifically, on little endian, if possible.

**Comment by drpngx** [comment]
Hmm, thinking about it, it's hard to create a test for this.

**Pull request merged**
