### PR TITLE
[SE] Include absl/memory/memory.h

### PR DESCRIPTION
**Pull request by veshij**
Similar to https://github.com/tensorflow/tensorflow/pull/42942

```
external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc:184:23: error: 'make_unique' is not a member of 'absl'
     auto lock = absl::make_unique<absl::MutexLock>(&mutex_);
                       ^~~~~~~~~~~
```

### CODE REVIEW

**Comment by veshij** [comment]
@googlebot I signed it!

**Comment by veshij** [comment]
@googlebot I fixed it.

**Comment by gbaned** [comment]
@veshij Thank you for your contribution. Can you please sign CLA? Thanks!

**Comment by veshij** [comment]
@googlebot I fixed it.

**Review by reedwm — APPROVED** [review]

**Pull request merged**
