### PR TITLE
[TF:TRT] Add additional conv2d test case

### PR DESCRIPTION
**Pull request by christopherbate**

### CODE REVIEW

**Comment by bixia1** [comment]
Would you please provide a description of the PR?

**Comment by gbaned** [comment]
@christopherbate Can you please check @bixia1's comments and keep us posted ? Thanks!

**Comment by gbaned** [comment]
@christopherbate  Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
@christopherbate This PR is in draft, any update on this? Please. Thank you!

**Pull request closed without merging**
