### PR TITLE
Make wide_n_deep_tutorial.py work on Python 2 and 3

### PR DESCRIPTION
**Pull request by jpangburn**
Use the six.moves module as suggested by @mrry to make this work with Python 2 and 3

### CODE REVIEW

**Comment by mrry** [comment]
Thanks for sending this in!

@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
@googlebot can you validate the CLA?

**Comment by mrry** [comment]
@jpangburn It looks like our bot for checking CLAs (contributor license agreements) has failed to respond to this PR. However, I've checked manually and it seems you've signed the CLA (thanks!) so I'm going to merge this now.

**Comment by jpangburn** [comment]
Yes, I did sign the CLA just today, not sure if that’s why it didn’t find it automatically.  Thanks!

**Pull request merged**
