### PR TITLE
[oneDNN] Enabled {Conv2D, DepthwiseConv2D}+BiasAdd+_FusedHardSwish fusion for INT8

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR adds support for _FusedHardSwish activation function as fused op in Conv2D/DWConv2D INT8 kernel.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @mahmoud-abuzaina Can you please confirm if this PR is still valid? Thank you!

**Comment by mahmoud-abuzaina** [comment]
This PR is no longer needed.

**Pull request closed without merging**
