### PR TITLE
cast to integer as required re issue #2420

### LINKED ISSUE #2420: TypeError: an integer is required executing skflow text classification examples
Using a nightly build I'm unable to execute the text classification examples in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/skflow (I have tried text_classification.py, text_classification_cnn.py and text_classification_builtin_rnn_model.py).

`$ sudo pip3 install --upgrade http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl 

$ python3 -c "import tensorflow; print(tensorflow.__version__)"
0.8.0

$ python3 rnn.py
Total words: 822383
Traceback (most recent call last):
  File "rnn.py", line 68, in <module>
    classifier.fit(X_train, y_train, logdir='/tmp/tf_examples/word_rnn')
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 270, in fit
    feed_params_fn=self._data_feeder.get_feed_params)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/trainer.py", line 49, in train
    feed_dict = feed_dict_fn()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/io/data_feeder.py", line 324, in _feed_dict_fn
    out.itemset((i, self.y[sample]), 1.0)
TypeError: an integer is required`

### PR DESCRIPTION
**Pull request by aroyer**
issue #2420 workaround fix

Fixes #2420

### CODE REVIEW

**Comment by aroyer** [comment]
I signed it as game-changing labs

**Comment by vrv** [comment]
Thanks, it may take a bit for the CLA to propagate.  will look at this again tomrorow

**Comment by girving** [comment]
Make sure to close #2420 once this is merged, since the commit message doesn't say "Fixes #2420".

**Comment by vrv** [comment]
I updated the commit message.  Corp CLA still hasn't propagated, will check again soon.

**Comment by aroyer** [comment]
signed individual CLA as well because still not seeing the Corp CLA.

**Comment by vrv** [comment]
I guess this doesn't have a test for it, but I'll test and merge anyway.

@ilblackdragon @martinwicke need moar test coverage

@tensorflow-jenkins test this please

**Pull request merged**
