### PR TITLE
minor spelling tweaks under mlir

### PR DESCRIPTION
**Pull request by kiszk**
This PR addresses minor spelling tweaks under `tensorflow/compiler/mlir` directory. This is complementary to #33091.

### CODE REVIEW

**Review by lukasfolle — DISMISSED** [review]
Look good to me.

**Comment by mihaimaruseac** [comment]
Should these changes be made on the MLIR repo and reflected back here? Or the other way round? With the code duplication between the two, it's harder to identify proper location of changes

**Comment by jpienaar** [comment]
> Should these changes be made on the MLIR repo and reflected back here? Or the other way round? With the code duplication between the two, it's harder to identify proper location of changes

These changes are only to files that are only in TF MLIR and not MLIR core repo.

**Review by jpienaar — DISMISSED** [review]
Thanks

**Comment by gbaned** [comment]
@kiszk Can you please resolve conflicts? Thanks!

**Comment by kiszk** [comment]
@gbaned Thank you for pinging me. Just resolved.

**Comment by gbaned** [comment]
@kiszk Still, conflicts are appearing. Can you please resolve? Thanks!

**Comment by kiszk** [comment]
@gbaned sure, just resolved.

**Comment by gbaned** [comment]
@kiszk  Can you please resolve conflicts? Thanks!

**Review by jpienaar — DISMISSED** [review]
Thanks!

**Comment by kiszk** [comment]
@gbaned @jpienaar Sorry for being late. I made a business trip. I have just fixed conflict.

**Comment by jpienaar** [comment]
Sorry missed your response. Let me approve again, if it conflicts I'll pull it manually and update.

**Review by jpienaar — APPROVED** [review]

**Pull request merged**
