### PR TITLE
rename var mu to learning_rate

### PR DESCRIPTION
**Pull request by amchercashin**
Trying to resolve some problems with commit...done

Rename variable `mu` to `learing_rate` for paper consistency. 

This is a second try, first try I have broke the file somehow (some waste lines leaked in it in merge commits). Now I have updated my local master branch from remote master, made a new branch for just this commit and made one commit ahead master. Hope it will be ok now.

### CODE REVIEW

**Comment by vrv** [comment]
Thanks, you can you try to squash the commits to get rid of all of those merge commits?

**Comment by amchercashin** [comment]
Still trying. Constantly got an merge error while squashing commits into one with `git rebase`

**Comment by amchercashin** [comment]
I could make a commit from github web-editor. But it adds a /newline character at the end of ipynb file. Maybe it's good to have one (usually) but I think it's not so good to have all this in one commit

**Comment by vrv** [comment]
The merge commits are distracting -- maybe clone a new copy of your local repo, rebase to head, and then apply your changes?

    git clone ... your fork
    git remote add upstream https://github.com/tensorflow/tensorflow.git
    git fetch upstream
    git rebase upstream/master
    git checkout -b new_branch
    ... make edits ...
    git push -u origin new_branch

**Comment by amchercashin** [comment]
@vrv  Ok, finally, thanks to your instructions, looks like it's done! Please double check if my happiness is too early.

**Comment by vrv** [comment]
Great, thanks!  @tensorflow-jenkins: test this please

**Pull request merged**
