### PR TITLE
[ROCm] Fix for //tensorflow/python/kernel_tests/signal:mel_ops_test

### PR DESCRIPTION
**Pull request by ekuznetsov139**
The test //tensorflow/python/kernel_tests/signal:mel_ops_test fails on ROCm in eager mode by slightly exceeding the error tolerance.
This patch replaces the calls to exp and log with more accurate expm1 and log1p (which is something that occurs automatically in graph mode but not in eager mode), bringing the error back below threshold.

### CODE REVIEW

**Review by chsigg — DISMISSED** [review]

**Comment by rthadur** [comment]
@ekuznetsov139 can you please fix sanity build errors ?

**Comment by deven-amd** [comment]
gentle ping

**Comment by deven-amd** [comment]
gentle ping

**Review by chsigg — DISMISSED** [review]

**Comment by gbaned** [comment]
@ekuznetsov139 Can you please address Ubuntu Sanity errors? Thanks!

**Review by rthadur — APPROVED** [review]

**Review by rthadur — APPROVED** [review]

**Pull request merged**
