### PR TITLE
generate_examples_lib updated with Round op

### PR DESCRIPTION
**Pull request by siju-samuel**

### CODE REVIEW

**Comment by gbaned** [comment]
@achowdhery Can you please review this PR? Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @achowdhery: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by terryheo** [comment]
Thanks for your contribution, Siju.
The test was added via https://github.com/tensorflow/tensorflow/pull/24918

**Pull request closed without merging**
