### PR TITLE
[TF Mobile] Adding codes to print Logcat log of statString for analizing the perf…

### PR DESCRIPTION
**Pull request by namyikim**
…ormance per layers

Adding codes to print Logcat log of statString for analizing the performance per layers

### CODE REVIEW

**Comment by namyikim** [comment]
I already signed it!

**Comment by namyikim** [comment]
I signed it!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 50 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 65 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 80 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 95 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 110 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rthadur** [comment]
> I signed it
can you please make sure to use same username and email id while signing CLA

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
