### PR TITLE
Fix all but one Python 3 test

### PR DESCRIPTION
**Pull request by girving**
`saver_test` is still broken.

### CODE REVIEW

**Comment by caisq** [comment]
This PR contains a lot edits in the same spots as https://github.com/tensorflow/tensorflow/pull/1034 We can look and decide which PR to merge.

**Comment by girving** [comment]
It's much better to open the file correctly as binary or not than to decode manually, so this PR seems better.

**Comment by caisq** [comment]
@girving I agree that this PR is better with one exception: In scatter_ops_test.py, use 
`from six.moves import xrange`

so that we can get both 2-3 compatibility and the performance of xrange.

**Comment by caisq** [comment]
I'm closing https://github.com/tensorflow/tensorflow/pull/1034 in favor of this one.

**Comment by girving** [comment]
The performance difference is negligible for small loops and this is just a test, so I went for simplicity.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
merged.

**Pull request closed without merging**
