### PR TITLE
[NVIDIA TF] Rollforward Dynamic Pywrap PR #55941

### LINKED ISSUE #58287: Issue created for Rollback of PR #55941: Dynamic Pywrap - Refactor pywrap_tensorflow_internal to load TF symbols from libtensorflow_cc.so
Merged PR #55941 is rolled back in 970c3b44ea8b0db78d92ada624f03aeacf2e4518.
    Please follow up with the reviewer and close this issue once its resolved.

### PR DESCRIPTION
**Pull request by trevor-m**
This reverts the rollback commit 970c3b44ea8b0db78d92ada624f03aeacf2e4518.

> This PR adds a new build configuration which is tentatively called dynamic_pywrap. When enabled, _pywrap_tensorflow_internal.so will no longer contain any implementation for TensorFlow and will instead dynamically depend on libtensorflow_cc.so to load those symbols. _pywrap_tensorflow_internal.so will now a lightweight binary only containing the python bindings and other code/APIs which depends on python.

Fixes #58287
cc https://github.com/horovod/horovod/pull/3755

### CODE REVIEW

**Review by learning-to-play — APPROVED** [review]

**Review by learning-to-play — APPROVED** [review]

**Comment by learning-to-play** [comment]
Hi @trevor-m, I see the following two warnings. Could you please fix?
- There is already a load from "//third_party/tensorflow/core/platform:build_config_root.bzl" on line 25. Please merge all loads from the same origin into a single one.
- Symbol "if_static" has already been loaded on line 27. Please remove it.

**Comment by trevor-m** [comment]
> Hi @trevor-m, I see the following two warnings. Could you please fix?
> 
> * There is already a load from "//third_party/tensorflow/core/platform:build_config_root.bzl" on line 25. Please merge all loads from the same origin into a single one.
> * Symbol "if_static" has already been loaded on line 27. Please remove it.

Thank you @learning-to-play! Just pushed the fixes.

**Review by learning-to-play — APPROVED** [review]

**Comment by learning-to-play** [comment]
Thank you @trevor-m. I see failing jobs with the following error message. Could you please sync your PR and make sure all jobs pass including "Code Check - Changed Files", "Windows Bazel", and "feedback/copybara"?

```
ERROR: /tf/tensorflow/tensorflow/BUILD:1214:21: no such target '//tensorflow/core/profiler/convert:hlo_to_tools_data_impl': target 'hlo_to_tools_data_impl' not declared in package 'tensorflow/core/profiler/convert' defined by /tf/tensorflow/tensorflow/core/profiler/convert/BUILD and referenced by '//tensorflow:libtensorflow_cc.so.2.12.0'
```

**Review by learning-to-play — APPROVED** [review]

**Comment by learning-to-play** [comment]
Hi @trevor-m, Google internal checks failed. I fixed it. Could you please sync? Sorry for the inconvenience.

**Comment by trevor-m** [comment]
> Hi @trevor-m, Google internal checks failed. I fixed it. Could you please sync? Sorry for the inconvenience.

Thanks @learning-to-play! I synced the PR but it looks like the internal checks are failing again. Let me know if I can help at all.

**Review by learning-to-play — APPROVED** [review]

**Pull request merged**
