### PR TITLE
Error handling for missing variable nodes

### PR DESCRIPTION
**Pull request by SaurabhDesai20**
Error Logging: Added better error logging for missing nodes or variable issues (LOG(ERROR)).
Memory Handling: Removed the need for a static variable (kVariableTypes) and replaced it with a local unordered_set.
API Adaptation: Fixed some outdated TensorFlow API calls and ensured compatibility with modern versions.

### CODE REVIEW

**Comment by keerthanakadiri** [comment]
Hi @SaurabhDesai20 , Can you please sign CLA , thank you !

**Comment by mihaimaruseac** [comment]
This should be reviewed by someone from SavedModel team

**Comment by keerthanakadiri** [comment]
Hi @SaurabhDesai20 , Can you please sign CLA , thank you !

**Comment by keerthanakadiri** [comment]
Hi @SaurabhDesai20 , Can you kindly sign CLA ? thank you !

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Please split PR into components that do one thing only. Here, you fix an error from a not found node, you change freezing saved models and you also remove comments and TODOs. Not to mention changing logic from `if (expr1) expr2; expr3` to `if (!expr1) expr3; expr2;` which is equivalent but different readability implications.

**Pull request closed without merging**
