### PR TITLE
Fix contrib.seq2seq.BeamSearchDecoder #9855

### PR DESCRIPTION
**Pull request by shuuki4**
Fixed Issue 9855 by shielding the `top_k` op's input with `min`.
Also fixed wrong `log_probs `shape at `_get_scores` method docstring.

### CODE REVIEW

**Comment by chenghuige** [comment]
scores_flat.shape[-1].value) might be None for dynamic batch size ?

**Comment by shuuki4** [comment]
@chenghuige That is true. It will be better to treat two values as tensor since top_k operation can handle `k` as tensor.
```
from tensorflow.python.ops import gen_math_ops

...

next_beam_size = gen_math_ops.minimum(
  ops.convert_to_tensor(
    beam_width, dtype=tf.int32, name="beam_width"),
  ops.convert_to_tensor(
    scores_flat.shape[-1], dtype=tf.int32, name="num_available"))
```
Will this code be OK?

**Comment by rmlarsen** [comment]
@shuuki4 

Yes, that should work, but use math_ops.minimum, not gen_math_ops.minimum.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@shuuki4 the unit test is failing, can you take a look?

**Comment by shuuki4** [comment]
@rmlarsen Error was due to the unknown shape after cond operation. Fixed the problem.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
Thanks for the contribution!

**Pull request merged**
