### PR TITLE
internal to github 2016/4/28

### PR DESCRIPTION
**Pull request by poxvoculi**

### CODE REVIEW

**Comment by poxvoculi** [comment]
@tensorflow-jenkins test this please

**Comment by poxvoculi** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
test this please

**Comment by vrv** [comment]
Wahh @caisq what happened

**Comment by vrv** [comment]
Oh @poxvoculi introduced a problem during the merge conflict, nevermind.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
