### PR TITLE
Remove the additional "." in profiler.cc to make the format the consistent. 

### PR DESCRIPTION
**Pull request by lionelfeng**
Remove the additional "." in profiler.cc to make the format the consistent.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Please don't use "add file"/"update file"/"fix file"/etc. commit messages. These are hard to reason about when looking at the history of the file/repository. Instead, please write explanatory git commit messages.

The commit message is also the title of the PR if the PR has only one commit. It is thus twice important to have commit messages that are relevant, as PRs would be easier to understand and easier to analyze in search results.

For how to write good quality git commit messages, please consult https://cbea.ms/git-commit/

**Comment by lionelfeng** [comment]
> Please don't use "add file"/"update file"/"fix file"/etc. commit messages. These are hard to reason about when looking at the history of the file/repository. Instead, please write explanatory git commit messages.
> 
> The commit message is also the title of the PR if the PR has only one commit. It is thus twice important to have commit messages that are relevant, as PRs would be easier to understand and easier to analyze in search results.
> 
> For how to write good quality git commit messages, please consult https://cbea.ms/git-commit/

Updated. PTAL.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by lionelfeng** [comment]
Thanks, @mihaimaruseac. could you pls guide me how to fix the `You’re not authorized to merge this pull request`?

**Comment by mihaimaruseac** [comment]
In general repos should not allow anyone to merge PRs even after they get reviewed. There are maintainer roles that can merge (humans or bots).

For TF we have a long process, please see https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md. TL;DR is that there is CI running on Github but also CI running internally and only after everything passes a copybara based bot will merge it.

**Pull request merged**
