### PR TITLE
fixed atrous_conv2d to work with unknown shape of the input tensor

### PR DESCRIPTION
**Pull request by ThomasWollmann**

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
I signed it!

**Comment by martinwicke** [comment]
This is great. Could you add a test to make sure it keeps working?

**Comment by ThomasWollmann** [comment]
The test should still work. I ran them and fixed some imports. Still they are failing, because the calculated padding is somehow wrong. Currently I have no time to investigate. Maybe someone sees the cause immediately.

**Comment by shampool** [comment]
The current atrous_conv2d seems requiring image size should be divisible by the rate.
```
InvalidArgumentError: Image height 232 and width 248should be divisible by block_size: 16
	 [[Node: atrous_conv2d_7/SpaceToBatch = SpaceToBatch[T=DT_FLOAT, block_size=16, _device="/job:localhost/replica:0/task:0/cpu:0"](transpose_21, atrous_conv2d_7/concat)]]
Caused by op u'atrous_conv2d_7/SpaceToBatch', defined at:
```

**Comment by ThomasWollmann** [comment]
Thanks @shampool! Works for me.

**Comment by vrv** [comment]
sorry, some conflicts have sprung up, can you rebase?

**Comment by ThomasWollmann** [comment]
Seems like somebody else applied a fix in the meanhwile: https://github.com/tensorflow/tensorflow/commit/3a744a417178646712e9cda0a85655d5d8968e19

**Pull request closed without merging**
