### PR TITLE
Fixing download_dependencies.sh bugs for generating TFLite iOS exmaples

### PR DESCRIPTION
**Pull request by miaout17**
This is the 2nd try for #14631

To verify this:
* `git clean -fdx` to clean all local files. 
* run `tensorflow/contrib/lite/download_dependencies.sh`
* Verify that you see "download_dependencies.sh completed successfully", so the script is completed. 
* Verify these files are downloaded to correct location. 
 * tensorflow/contrib/lite/examples/ios/camera/data/labels.txt
 * tensorflow/contrib/lite/examples/ios/camera/data/mobilenet_quant_v1_224.tflite
 * tensorflow/contrib/lite/examples/ios/simple/data/labels.txt
 * tensorflow/contrib/lite/examples/ios/simple/data/mobilenet_v1_1.0_224.tflite
* Run `tensorflow/contrib/lite/build_ios_universal_lib.sh` to verify the library can be built.

### CODE REVIEW

**Review by aikailin — APPROVED** [review]
LGTM

**Review by gargn — APPROVED** [review]
@miaout17 @sidneyyan tested the changes.

**Comment by llyyun** [comment]
download_dependencies.sh completed successfully, and examples are downloaded,  but run build_ios_universal_lib.sh failed: 
+ set -e
+ make -f tensorflow/contrib/lite/Makefile TARGET=IOS IOS_ARCH=x86_64 -j 8
make: tensorflow/contrib/lite/Makefile: No such file or directory
make: *** No rule to make target `tensorflow/contrib/lite/Makefile'.  Stop.

**Comment by miaout17** [comment]
@llyyun For now, you need to execute this script at the git root directory. 
We will improve these scripts and make it executable from anywhere.

**Pull request merged**
