### PR TITLE
Fix indentation in CRF

### PR DESCRIPTION
**Pull request by himkt**
- Fixed the wrong indentation.

### CODE REVIEW

**Review by mrry — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by himkt** [comment]
@mrry @case540 what is status of this PR?
Can I close it?

**Comment by case540** [comment]
Huh, the internal CL got reverted for some reason. No idea what happen. WIll start the copybara migration thing again.

**Pull request merged**
