### PR TITLE
Update CUB to 1.7.4

### PR DESCRIPTION
**Pull request by yongtang**
Was working on #13731 and noticed that the CUB version is 1.7.3.

This fix updates CUB to 1.7.4 which consists of bug fixes in radix sort.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Review by caisq — APPROVED** [review]

**Review by mrry — CHANGES_REQUESTED** [review]
Can you please apply the same change to [`cub.cmake`](https://github.com/tensorflow/tensorflow/blob/cffe603e93520318aaaf07c165cfaf1a3f13805a/tensorflow/contrib/cmake/external/cub.cmake#L17) so that Windows users get the benefits of the bug fix? Thanks!

**Comment by yongtang** [comment]
Thanks @mrry @caisq. I have updated the PR with the CMAKE file changes. I don't have a Windows dev machine readily available though I tested with CMAKE Linux build and it works.

Please take a look and let me know if there are any issues.

**Review by mrry — APPROVED** [review]
CMake changes LGTM, thanks!

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
