### PR TITLE
C++ gradient for Slice

### PR DESCRIPTION
**Pull request by kbsriram**
See https://github.com/tensorflow/tensorflow/issues/9645

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @suharshs: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Review by suharshs — DISMISSED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 22 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
@kbsriram, sorry for the delay.
Could you rebase the changes, looks like we can merge as soon as all conflict are resolved.

**Comment by kbsriram** [comment]
@gunan - no worries. I rebased (which also seems to have invalidated the lgtm; the changes should be identical however.)

**Comment by gunan** [comment]
@suharshs could you take a look.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by suharshs — APPROVED** [review]

**Comment by wumo** [comment]
I find `tensorflow v1.9.0-rc2 ` supports `SliceGrad` whereas `tensorflow v1.9.0` throws `No gradient defined for op: Slice`.

**Pull request merged**
