### PR TITLE
gpu support on windows

### PR DESCRIPTION
**Pull request by schmuell**
code changes to enable gpu support under windows. Tested on windows 10, cuda 8 sdk and cudnn 5.1.
CMake changes to build this come in a 2nd pull request.

### CODE REVIEW

**Comment by schmuell** [comment]
corperate cla: microsoft

**Comment by JimSEOW** [comment]
@schmuell  please provide a url link for the instruction to compile with GPU support. Thank you.

The link I used to compile for [CPU only is](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md)

**Comment by schmuell** [comment]
It is in
https://github.com/schmuell/tensorflow/blob/b11ef5128f7341cfc7018ac0771d8939b8535cfc/tensorflow/contrib/cmake/README.md

you need to instal the cuda 8.0 SDK + cudnn 5.1 and add 2 options to cmake
-Dtensorflow_ENABLE_GPU=ON  -DCUDNN_HOME=c:\local\cudnn

I normally do:
cd tensorflow\contrib\cmake\
mkdir build
cd build
cmake .. -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo
-DPYTHON_EXECUTABLE=C:\local\Anaconda2\envs\py3\python.exe
-DPYTHON_LIBRARIES=C:\local\Anaconda2\envs\py3\libs\python35.lib
-DSWIG_EXECUTABLE=c:\local\swigwin-3.0.10\swig.exe
-Dtensorflow_ENABLE_GPU=ON  -DCUDNN_HOME="C:\local\cudnn"
msbuild /p:Configuration=RelWithDebInfo tf_python_build_pip_package.vcxproj

**Comment by schmuell** [comment]
I close this pull request and did a new one under a different user to deal with the cla: https://github.com/tensorflow/tensorflow/pull/5071

**Pull request closed without merging**
