### PR TITLE
Contributing: Fix a typo

### PR DESCRIPTION
**Pull request by MaherJendoubi**
nput --> input

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Can you fix more than one typo in a file please? One letter change causes hours of CI to run and that warms the planet and melts the ice.

**Comment by MaherJendoubi** [comment]
@mihaimaruseac What is the minimum number of typos?

**Comment by mihaimaruseac** [comment]
There is no minimum number but we prefer fixing every typo in a file/directory instead of just one. See [`CONTRIBUTING.md`](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#general-guidelines-and-philosophy-for-contribution)

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mdanatg** [comment]
It would be nice if changes to comments alone did not trigger this lengthy CI process.

**Review by mdanatg — APPROVED** [review]

**Comment by MaherJendoubi** [comment]
@mihaimaruseac my mistake. It is always important to read the contributing guide before any PR.

**Review by generationzcode — APPROVED** [review]

**Pull request merged**
