### PR TITLE
Python API documentation fixes

### PR DESCRIPTION
**Pull request by BryanCutler**
This PR fixes some minor grammatical and typo errors in the Python tf.data APIs that I came across while working with the code.

I generated documentation markdown files and checked them for correctness.

### CODE REVIEW

**Review by tensorflow-copybara — APPROVED** [review]
Thank you @BryanCutler !

**Review by yifeif — APPROVED** [review]

**Comment by harshini-gadige** [comment]
@yifeif  A quick question. Looks like Kokoro checks are not done for this. Did we bypass this intentionally ?
Would you like me to proceed further without kokoro checks ? Please confirm.

**Comment by yifeif** [comment]
Hi @harshini-gadige you are correct, this change is relatively low risk, and we are already running these Kokoro builds internally, therefore I didn't trigger them here :). But in general, we do want to make sure PR passes Kokoro builds first.  You can proceed with the safe review approval. Thanks for checking!

**Comment by BryanCutler** [comment]
Thank you @yifeif !

**Pull request merged**
