### PR TITLE
Add workspace root to the list of include path for swig compilation

### PR DESCRIPTION
**Pull request by damienmg**

### CODE REVIEW

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
@caisq, this looks like a test failure (this is an error you can apparently fix by reinstalling protobuf, according to #487). Is there an old protobuf version in the container?

**Comment by martinwicke** [comment]
Merged.

**Comment by caisq** [comment]
@jendap @martinwicke Regarding the test failure, I've seen this a number of times in the past couple of weeks. It looks sporadic. Oftentimes it goes away if you run exactly the same build again. The error message suggest that it has to do with protobuf version (see below). We should figure out the cause and solution to it because it'll most likely show up again and slow us down during release builds. 

> Traceback (most recent call last):
>   File "/tensorflow/pip_test/tests/in_topk_op_test.py", line 21, in <module>
>     import tensorflow.python.platform
>   File "/root/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
>     from tensorflow.python import *
>   File "/root/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 37, in <module>
>     from tensorflow.core.framework.graph_pb2 import *
>   File "/root/.local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
>     from google.protobuf import descriptor_pb2
>   File "/root/.local/lib/python2.7/site-packages/google/protobuf/descriptor_pb2.py", line 1533, in <module>
>     __module__ = 'google.protobuf.descriptor_pb2'
>   File "/root/.local/lib/python2.7/site-packages/google/protobuf/reflection.py", line 123, in __new__
>     new_class = superclass.__new__(cls, name, bases, dictionary)
> TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
>

**Pull request closed without merging**
