### PR TITLE
Add SkipLine to BufferedInputStream

### PR DESCRIPTION
**Pull request by zhuzilin**
This PR adds a `SkipLine` method to `BufferedInputStream` which will help implement the `SkipInternal` method of `TextLineDataset`, like #41222 to `TFRecordDataset`

Thank you for yor time on reviewing this PR.

### CODE REVIEW

**Review by allenlavoie — APPROVED** [review]

**Comment by zhuzilin** [comment]
@allenlavoie Thank you for your reviewing. There was a typo in the test file which resulted in the build errors. Could you take another look? :)

**Review by allenlavoie — APPROVED** [review]

**Comment by zhuzilin** [comment]
The errors from TFLite are not induced by this PR. The relevant error log is:
```
INFO: Repository 'eigen_archive' used the following cache hits instead of downloading the corresponding file.
 * Hash 'd76992f1972e4ff270221c7ee8125610a8e02bb46708a7295ee646e99287083b' for https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/90ee821c563fa20db4d64d6991ddca256d5c52f2/eigen-90ee821c563fa20db4d64d6991ddca256d5c52f2.tar.gz
If the definition of 'eigen_archive' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'eigen_archive':
   Traceback (most recent call last):
	File "/workspace/third_party/repo.bzl", line 119, column 21, in _tf_http_archive
		ctx.template("BUILD.bazel", build_file, executable = False)
Error in template: Not a regular file: /workspace/third_party/eigen.BUILD
INFO: Repository clog instantiated at:
  /workspace/WORKSPACE:20:10: in <toplevel>
  /workspace/tensorflow/workspace.bzl:85:20: in workspace
  /workspace/tensorflow/workspace.bzl:79:27: in tf_repositories
  /workspace/tensorflow/workspace.bzl:13:9: in initialize_third_party
  /workspace/third_party/clog/workspace.bzl:6:29: in repo
Repository rule third_party_http_archive defined at:
  /workspace/third_party/repo.bzl:226:43: in <toplevel>
INFO: Repository remotejdk11_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:131:6: in <toplevel>
  /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository remote_java_tools_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:237:6: in <toplevel>
  /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /workspace/third_party/eigen3/BUILD:34:11: //third_party/eigen3:eigen3 depends on @eigen_archive//:eigen in repository @eigen_archive which failed to fetch. no such package '@eigen_archive//': Not a regular file: /workspace/third_party/eigen.BUILD
ERROR: Analysis of target '//tensorflow/lite/micro/kernels:fully_connected' failed; build aborted: Analysis failed
INFO: Elapsed time: 7.455s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (57 packages loaded, 1038 targets configured)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (57 packages loaded, 1038 targets configured)
```

**Comment by gbaned** [comment]
@allenlavoie  Can you please take a look on above comments from @zhuzilin. Thanks!

**Comment by gbaned** [comment]
@allenlavoie Any update on this PR? Please. Thanks!

**Review by allenlavoie — APPROVED** [review]

**Pull request merged**
