### PR TITLE
Add tests in TFLite micro for Relu/Relu6 Int8/Uint8/Float

### PR DESCRIPTION
**Pull request by giuseros**
Adding reference code and tests for Relu and Relu6 for  Int8/Uint8/Float

### CODE REVIEW

**Comment by gbaned** [comment]
@giuseros thank you for your contribution, please sign CLA

**Review by njeffrie — DISMISSED** [review]

**Comment by giuseros** [comment]
Can someone please re-run this tests? They should not be affected by this change.

**Comment by giuseros** [comment]
Ready to merge

**Comment by rthadur** [comment]
Here is the internal error,please take a look.
`ld.lld: error: undefined symbol: tflite::ops::micro::Register_RELU()
>>> referenced by all_ops_resolver.cc
>>>               blaze-out/k8-opt/bin/third_party/tensorflow/lite/experimental/micro/kernels/_objs/all_ops_resolver/all_ops_resolver.o:(tflite::ops::micro::AllOpsResolver::AllOpsResolver())

ld.lld: error: undefined symbol: tflite::ops::micro::Register_RELU6()
>>> referenced by all_ops_resolver.cc
>>>               blaze-out/k8-opt/bin/third_party/tensorflow/lite/experimental/micro/kernels/_objs/all_ops_resolver/all_ops_resolver.o:(tflite::ops::micro::AllOpsResolver::AllOpsResolver())
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by giuseros** [comment]
Hi @rthadur , 
It works when I compile (and run) with:
$ make -f tensorflow/lite/experimental/micro/tools/make/Makefile test

Was this a Bazel failure? I added the "activations.cc" file into tensorflow/lite/experimental/micro/kernels/BUILD, hoping that this was the issue. 

Alternatively, how can I reproduce this?

Thanks,
Giuseppe

**Review by njeffrie — APPROVED** [review]

**Comment by giuseros** [comment]
Ready to merge

**Pull request merged**
