### PR TITLE
[TF-TRT] - Bazel Test does not use allow_growth in TF2

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
CC: @bixia1 I recently saw numerous of OOM when running python bazel tests:

```bash
bazel test --verbose_failures --cache_test_results=no --runs_per_test=10 //tensorflow/python/compiler/tensorrt/...
```

This tends to generate OOM issues for the TF2 unittests. This PR fixes this. 

In TF1 the configuration is applied properly, in TF2 mode this is skipped: https://github.com/tensorflow/tensorflow/blob/e5648ef49daa9500ebdebca603f3b5cc42c76a99/tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py#L317-L320

### CODE REVIEW

**Comment by bixia1** [comment]
Do you know why the "TF1 way" doesn't work for TF2? Is it because of [this code](https://github.com/tensorflow/tensorflow/blob/eb8f61f5f41c56b4cb267c549a192e8301eb7d30/tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py#L782) for _MakeSavedModelV1 doesn't exist for _MakeSavedModelV2? Prefer to make it work the same way for TF1 and TF2.

**Review by bixia1 — COMMENTED** [review]
Sorry, I think I made a mistake in my previous comment. It is probably due to the difference between _RunGraphV1 and _RunGraphV2 in handling "config". The V2 version actually ignore "config".

**Comment by DEKHTIARJonathan** [comment]
That's correct. This PR should fix that

**Comment by bixia1** [comment]
Is there a way to fix it in _RunGraphV2 as _RunGraphV1 takes care of similar things, and RunTest is common  for V1 and V2.

**Comment by DEKHTIARJonathan** [comment]
Not really sure ... TF1 path uses sessions (that takes a session config), not TF2 path. So this approach sounds safer to me

**Comment by bixia1** [comment]
Would simplify moving the code to inside _RunGraphV2 be a good solution?

**Comment by DEKHTIARJonathan** [comment]
I'm not sure it could cover all paths. 
For example this one would not be covered: https://github.com/tensorflow/tensorflow/blob/e5648ef49daa9500ebdebca603f3b5cc42c76a99/tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py#L796-L798

**Comment by bixia1** [comment]
That code generates a saved model for V1. Your current fix doesn't cover it either. Right?

**Comment by DEKHTIARJonathan** [comment]
If I understand things correctly it does since the current fix is applied at the beginning of the test execution and is therefore valid for the whole test execution scope

**Comment by bixia1** [comment]
Each RunTest will call RunGraph twice. Are you concern that setting it twice at runtime through _RunGraphV2 is less efficient than setting it once in RunTest? I prefer to set it inside _RunGraphV2 to match the behavior of _RunGraphV1 and avoid special handling in RunTest. But if you insist, you may add it to RunTest with a comment to explain why this is only done for V2, to help readability.

**Comment by gbaned** [comment]
@DEKHTIARJonathan Can you please check @bixia1's comments and keep us posted. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@DEKHTIARJonathan Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@DEKHTIARJonathan Any update on this PR? Please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 28 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
