### PR TITLE
update

### PR DESCRIPTION
**Pull request by helloalll**

### CODE REVIEW

**Comment by shahzadlone** [comment]
It says there are no files that were changed.. maybe you just need to rebase rather than manually merge from tensorflow/tensor flow?

**Comment by rthadur** [comment]
> It says there are no files that were changed.. maybe you just need to rebase rather than manually merge from `tensorflow/tensorflow`?

@leekinpo gentle ping to rebase

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 26 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 45 days with no activity and the `awaiting review` label has been applied.

**Comment by mihaimaruseac** [comment]
I don't think this is a useful PR, there are no actual changes to TensorFlow code and the commits are just merges of old PRs. Thus, closing.

**Pull request closed without merging**
