### PR TITLE
Update LSTMBlockCell to use LSTMStateTuple as state

### LINKED ISSUE #6582: Incompatible state size between LSTMCell and LSTMBlockCell
Hello,

I heard that the implementation of LSTMBlockCell is faster than that of LSTMCell, so I am trying to convert my codes using LSTMCell to use LSTMBlockCell.
However, I found one weird point: the types of state_size of the two are not compatible.
Specifically, LSTMCell's state_size is of type LSTMStateTuple and LSTMBlockCell's state_size is of type tuple.
As far as I know, tuple and LSTMStateTuple are quite similar but the latter handles an internal memory state and a hidden state in a more abstract way.

I know the separated use of tuple and LSTMStateTuple is quite useful; for example when I have to detect whether a cell is MultiRNNCell (where state_size is of type tuple) or a cell is LSTMCell (where state_size is of type LSTMStateTuple).
Thus, I think the current behavior of LSTMBlockCell should be corrected to use LSTMStateTuple as a state type.
It can be easily modified if there is no backward compatibility issue, and I will send a pull request if nobody is working on this now.

### PR DESCRIPTION
**Pull request by jihunchoi**
Fixes #6582

### CODE REVIEW

**Comment by drpngx** [comment]
@ebrevdo any interest?

**Comment by jihunchoi** [comment]
Reading my codes written in dawn again, I found LSTMBlockFusedCell should not be fixed! I will revert it back.

**Comment by vrv** [comment]
@jihunchoi just to make sure, this PR is blocked on #7387 ?

**Comment by jihunchoi** [comment]
No, I mentioned this PR wrongly in #7387 but the message does not disappear after I deleted the mention...

**Comment by vrv** [comment]
It's okay, just wanted to understand the status -- so this is ready to review again?

**Comment by jihunchoi** [comment]
Yes, the mention can be safely ignored.

**Comment by ebrevdo** [comment]
Can you resolve merge conflicts?

**Comment by jihunchoi** [comment]
Was there a conflict? It was able to be automatically merged with tensorflow/master branch.
Anyway, I updated it to follow the latest master branch and it seems there exists no conflict.

**Review by ebrevdo — APPROVED** [review]
LGTM

**Comment by ebrevdo** [comment]
thanks!  please ensure all tests pass.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
