### PR TITLE
[docs] Fix formatting-related issues and address #2083

### PR DESCRIPTION
**Pull request by kirillbobyrev**
Improving tensorflow/g3doc/get_started/os_setup.md by enforcing 80-char width limit, which is widely used in docs, removing trailing whitespaces and adressing point 2 from #2083.

### CODE REVIEW

**Comment by omtcyfz** [comment]
By the way, is the first point from #2083

> In the "pip installation" and "virtualenv installation" section, should specify that the wheel package is specifically for Python 3.4. 
> As a side note, a wheel package for Python 3.5 would be greatly appreciated.

Still the case? IIUC TensorFlow now has Python 3.5 wheel package. Please correct me if I am wrong.

**Comment by omtcyfz** [comment]
@tensorflow-jenkins test this please.

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this please.

**Comment by omtcyfz** [comment]
@andrewharp Thank you very much!

**Pull request merged**
