### PR TITLE
Artifact links for ppc64le GPU builds.

### PR DESCRIPTION
**Pull request by wdirons**
whl files for tensorflow_gpu..._ppc6le are now hosted on the OSU
Jenkins build server. Nightly builds and Stable Release builds
are provided. I didn't include the version number so we won't need
to update the readme file for every new release

### CODE REVIEW

**Comment by wdirons** [comment]
Links can be tested by looking at the README.md file here: https://github.com/wdirons/tensorflow/blob/update_readme_pp64le_gpu_artifacts/README.md

**Review by gunan — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by gunan — APPROVED** [review]

**Comment by tedhtchang** [comment]
Hi @gunan Both Nightly build and release build artifacts have been generated. Could you merge?

**Comment by tedhtchang** [comment]
Thank you @gunan , we appreciate all the reviews you have been doing for the power specific changes.

**Pull request merged**
