### PR TITLE
Branch 187471483

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by caisq** [comment]
@rmlarsen I'll start a pull after this PR is merged.

**Comment by caisq** [comment]
Thanks for trying to resolve the conflicts, @benoitsteiner . can you take a look at the test failure after your resolution commit? https://source.cloud.google.com/results/invocations/f418fb3a-6960-4db9-8345-78d5576ee32c/targets/%2F%2Ftensorflow%2Fcore%2Fgrappler%2Foptimizers:loop_optimizer_test/tests

**Comment by benoitsteiner** [comment]
@caisq The good new is that the failure is not due to a merge commit, just the fact that the "Enter" nodes created for the LoopOptimizerTest.RemovePush_NoOp test are not annotated with a frame name. Is there any way to edit the test to fix it ?

**Comment by caisq** [comment]
@benoitsteiner the test was not failing before the merge commit. So I think it has something to do with the new PR that got merged (https://github.com/tensorflow/tensorflow/commit/84fe908258550e1ce27e8725de1e2af279479c9d) or the merge commit. Do you have time to take a look at that test? If so, it might be more efficient for you to do it rather than me given you are more familiar with that code. Either way let me know. Thanks.

**Comment by benoitsteiner** [comment]
@caisq The test was creating a technically invalid graph, but only started failing before https://github.com/tensorflow/tensorflow/commit/84fe908258550e1ce27e8725de1e2af279479c9d got merged because https://github.com/tensorflow/tensorflow/commit/84fe908258550e1ce27e8725de1e2af279479c9d calls the function that requires the "Enter" nodes to be correctly created (i.e. annotated with a frame name). @rmlarsen will fix the test to add the frame names.

**Comment by caisq** [comment]
@benoitsteiner Thanks for the explanation. @rmlarsen, should I disable the test for now?

**Comment by terrytangyuan** [comment]
@caisq I just had a glance of the commits but it looks like some commits are already in master?

**Comment by caisq** [comment]
@terrytangyuan I think something got messed up in the previous push(es). I just tried again and the old commits still show up. Let us merge this PR, which hopefully will straighten things out.

**Review by protoget — APPROVED** [review]

**Pull request merged**
