### PR TITLE
Add GPU implem of sparse segment reduction ops [resubmission]

### PR DESCRIPTION
**Pull request by benbarsdell**
This is a resubmission of https://github.com/tensorflow/tensorflow/pull/47974 that includes an additional commit to (attempt to) workaround errors in the Windows CI build.

cc @nluehr @sanjoy

### CODE REVIEW

**Comment by sanjoy** [comment]
I don't see the "details" link either, kicked off another Kokoro run.

**Comment by sanjoy** [comment]
Wow, looks like this is ICEing the compiler.

@cheshire you ran into this too right?  Did you have to do something specific to work around this?

**Comment by benbarsdell** [comment]
Is the ICE related to this PR? It's in XLA, which this doesn't touch. (Also I don't think it showed up on the previous Kokoro run).

Still no Details on the Windows Bazel GPU failure.
I think the other failures are unrelated.

**Comment by sanjoy** [comment]
> Is the ICE related to this PR? It's in XLA, which this doesn't touch. (Also I don't think it showed up on the previous Kokoro run).

Good point, I'll kick off a second run to see if we get lucky.

I was able to grab the Windows log though: https://gist.github.com/sanjoy/09105756945061ca4aa331948027f8fa, which is displaying an error I've never seen before "ERROR: command succeeded, but not all targets were analyzed"

**Comment by benbarsdell** [comment]
I assume it's these from the Windows log?
```
ERROR: T:/src/github/tensorflow/py_test_dir/tensorflow/python/saved_model/BUILD:625:18: in py_library rule //py_test_dir/tensorflow/python/saved_model:load_options: target '//tensorflow/python/util:tf_export' is not visible from target '//py_test_dir/tensorflow/python/saved_model:load_options'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: T:/src/github/tensorflow/py_test_dir/tensorflow/python/saved_model/BUILD:50:18: in py_library rule //py_test_dir/tensorflow/python/saved_model:signature_constants: target '//tensorflow/python/util:tf_export' is not visible from target '//py_test_dir/tensorflow/python/saved_model:signature_constants'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: T:/src/github/tensorflow/py_test_dir/tensorflow/python/saved_model/BUILD:512:18: in py_library rule //py_test_dir/tensorflow/python/saved_model:revived_types: target '//tensorflow/python/util:tf_export' is not visible from target '//py_test_dir/tensorflow/python/saved_model:revived_types'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

Also looks like the ICE is still there but in a different file.

**Comment by sanjoy** [comment]
Ben, can you please rebase?  Given the builds are green, I suspect whatever is causing the ICE in XLA has been resolved.

**Review by sanjoy — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by benbarsdell** [comment]
I'm a little unclear on the state of this, does it still need to be rebased?

**Review by sanjoy — APPROVED** [review]

**Comment by sanjoy** [comment]
Ben, the Linux GPU failures seem legitimate (segfault in //tensorflow/python/kernel_tests:segment_reduction_ops_test_gpu[k8-opt]), can you PTAL?

**Comment by benbarsdell** [comment]
I've rebased and added a fix for the new test failure.

**Comment by benbarsdell** [comment]
Is this still blocked on something internally?

**Comment by sanjoy** [comment]
> Is this still blocked on something internally?

No, but I need to check it in manually because of merge conflicts and a failing test.  Should be in tree soon.

**Comment by sanjoy** [comment]
Merged at f9c651943d442f98d4c7c36839bde70f27a9a135.

**Pull request closed without merging**
