### PR TITLE
Fix syntax error when executing setup.py using python 3.4

### PR DESCRIPTION
**Pull request by brchiu**
When I execute `python3 ./tensorflow/tools/pip_package/setup.py install` on raspberry pi 2, I encountered syntax error message at these two code snippets. This commit is for fixing such error.

### CODE REVIEW

**Comment by brchiu** [comment]
I also encountered this problem when executing `python3 ./tensorflow/tools/pip_package/setup.py install` on Lubuntu 15.10.

**Comment by brchiu** [comment]
I have signed the  Contributor License Agreement !

**Comment by vrv** [comment]
(looks like it hasn't registered -- did you verify that the commit email matches?)

**Comment by brchiu** [comment]
@vrv Looks like I have some trouble about different gmail and github account. I don't know how to resolve it. My usage scenario is : 

1) I use brchiu@ms35.hinet.net as my github account for my development purpose, commit this pull request to my fork then create this pull request. 
2) my google account is biruei.chiu@gmail.com. I signed CLA using it and designate my github account as brchiu@ms35.hinet.net in contact information.

Please advice how to resolve this ?
Thanks.

**Comment by vrv** [comment]
- You can sign the CLA using the email address that you use in your git commits
- You can git commit --amend your change to use the email address you already registered the CLA with and then repush / resend the pull request.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
```
==================== Test output for //tensorflow/models/rnn/ptb:reader_test:
.E.
======================================================================
ERROR: testPtbRawData (__main__.PtbReaderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/models/rnn/ptb/reader_test.runfiles/tensorflow/models/rnn/ptb/reader_test.py", line 49, in testPtbRawData
    output = reader.ptb_raw_data(tmpdir)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/models/rnn/ptb/reader_test.runfiles/tensorflow/models/rnn/ptb/reader.py", line 83, in ptb_raw_data
    word_to_id = _build_vocab(train_path)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/models/rnn/ptb/reader_test.runfiles/tensorflow/models/rnn/ptb/reader.py", line 47, in _build_vocab
    key=lambda word, count: (-count, word))
TypeError: <lambda>() takes exactly 2 arguments (1 given)
```

Looks like this doesn't work for python 2 ...

**Comment by ebrevdo** [comment]
Wrap word, count in parens.  It should work.

**Comment by vrv** [comment]
That's what we had before, so not sure why it's not python 3 compatible, would have to look into it.

**Comment by brchiu** [comment]
After some searching on internet, the problem of comes from 'PEP 3113 -- Removal of Tuple Parameter Unpacking', i.e. https://www.python.org/dev/peps/pep-3113/ . 
According to a post on StackOverflow, the author suggest a fix on this kind of problem, 'http://stackoverflow.com/questions/11328312/python-lambda-does-not-accept-tuple-argument' , but 

I don't know how to execute the unit test (i.e. reader_test.py) on my machine. 
Can anyone advice ?

**Comment by brchiu** [comment]
I tried a fix according to previous mentioned StackOverflow post. It seems work for executing `python3 ./tensorflow/tools/pip_package/setup.py install` and `python2 ./tensorflow/tools/pip_package/setup.py install` on my machine. 

Should I create a new pull request ? 
Or just commit my local fix to github then googlebot can automatically fetch new commit code and run new verification ?

**Comment by brchiu** [comment]
@tensorflow-jenkins: test this please

**Comment by brchiu** [comment]
@tensorflow-jenkins: test this please

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by brchiu** [comment]
I found that 'MacOS CPU Test' failed from 2016/1/10. 
Is there anyone looking into it ?

**Comment by vrv** [comment]
Yeah it's known and unrelated, let me disable that for now.

**Comment by vrv** [comment]
Thanks, can you squash your commits?  I'll merge once that's done.

**Comment by brchiu** [comment]
I have squashed my commits. Thanks.

**Comment by brchiu** [comment]
Jenkins, test this please.

**Comment by vrv** [comment]
@brchiu: only admins can kick off tests right now.  I'll test and merge tomorrow morning.

**Comment by brchiu** [comment]
@vrv Got it ! I just try to see whether 'Open Sesame!' work or not. :)

**Pull request closed without merging**
