### PR TITLE
[ROCm] Replacing csrMM with SpMM for ROCm 4.2+ 

### PR DESCRIPTION
**Pull request by stevenireeves**
Using the generalized SpMM function for Matrix Multiplication for ROCm>=4.2, aligning with the CUDA implementation.
In conjunction with https://github.com/tensorflow/tensorflow/pull/49305

### CODE REVIEW

**Comment by stevenireeves** [comment]
@cheshire for review

**Comment by cheshire** [comment]
@penpornk for sparse kernels, but otherwise LG

**Comment by stevenireeves** [comment]
@penpornk bumping this thread.

**Review by cheshire — APPROVED** [review]

**Comment by gbaned** [comment]
@stevenireeves  Can you please resolve conflicts? Thanks!

**Comment by stevenireeves** [comment]
@gbaned conflict should be resolved.

**Review by cheshire — APPROVED** [review]

**Pull request merged**
