### PR TITLE
MKL: Fix for a compilation error caused by a previous commit

### PR DESCRIPTION
**Pull request by agramesh1**

### CODE REVIEW

**Comment by agramesh1** [comment]
@andydavis1 Can you approve this?

**Review by yuefengz — APPROVED** [review]

**Comment by agramesh1** [comment]
@yuefengz Can you merge this PR? The build is broken for Intel MKL.

**Comment by agramesh1** [comment]
@zheng-xq can you approve?

**Comment by gunan** [comment]
Jenkins, test this please.

**Review by gunan — APPROVED** [review]

**Pull request merged**
