### PR TITLE
[tflite] support broadcasting in Metal Add kernel

### LINKED ISSUE #31526: TFLite Metal GPU delegate: Add operator does not support broadcasting
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOS 12.3.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone Xr
- TensorFlow installed from (source or binary): binary, but TFLite compiled from source
- TensorFlow version (use command below): b'v1.13.2-5-g04256c89d8' 1.13.2
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): clang-1001.0.46.4
- CUDA/cuDNN version: n/a
- GPU model and memory: iPhone Xr

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Running the single-operation model given below using the Metal GPU delegate gives a different output than when executing on CPU or with the full Tensorflow interpreter.

**Describe the expected behavior**
The Metal GPU delegate gives the same output as the CPU interpreter.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
[model-broken.tflite.zip](https://github.com/tensorflow/tensorflow/files/3490983/model-broken.tflite.zip)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### PR DESCRIPTION
**Pull request by LK**
Re-adds support for broadcasted addition in the `Add` kernel on Metal after it was removed in https://github.com/tensorflow/tensorflow/commit/b4f842384a7f63f513a62bbe3efa41bf1ff3f9ad#diff-54815b5e93d252c9f48c9036228a4fa1. Due to the same issue as the one described in #31468, it's necessary to implement this as an unlinkable kernel, to properly specify a threadgrouping.

closes #31526

### CODE REVIEW

**Comment by rthadur** [comment]
@LK can you please add test cases ?

**Comment by LK** [comment]
@rthadur see comment here: https://github.com/tensorflow/tensorflow/pull/31564#issuecomment-520618964

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@NikolayChirkov Can you please take a look on this PR? Thanks!

**Comment by gbaned** [comment]
@LK Can you please resolve conflicts? Thanks!

**Comment by rthadur** [comment]
@LK do you mind adding test cases ?

**Comment by LK** [comment]
This was implemented in https://github.com/tensorflow/tensorflow/commit/cb98da75f249cf7e4a0e8185b620cf0b3f19c020#diff-54815b5e93d252c9f48c9036228a4fa1.

**Pull request closed without merging**
