### PR TITLE
Improve performance of tokenization for seq2seq/translation 

### PR DESCRIPTION
**Pull request by mithrandir**
by reducing compilation time of regular expression

### CODE REVIEW

**Comment by danmane** [comment]
@mithrandir Please sign our CLA neither late, nor early, but precisely when you mean to.

**Comment by mithrandir** [comment]
Hi Daniel,

Actually I'm employee of Microsoft and I'm now checking if I'm ok with
signing that. It would be great to know if there was similar case before.

Thanks,
Jiin

**Comment by danmane** [comment]
I believe that Microsoft is already covered under a Google CLA. You may need to switch the commit author email in the git log to your microsoft.com email address.

**Comment by mithrandir** [comment]
After reviewing internal policy, I decided to use my personal email instead
of @microsoft.com address because I did this not for my work. I'll sign
this when I come back to home.

Thanks,
Jiin

**Comment by mithrandir** [comment]
Ok, I signed it with tisphie@gmail.com

Thanks,
Jiin

**Comment by danmane** [comment]
@lukaszkaiser PTAL

**Comment by lukaszkaiser** [comment]
Looks good to me, when tests pass let's get this in. Thanks!

**Comment by lukaszkaiser** [comment]
Sorry -- not meant to close. Adding vrv to merge.

**Comment by lukaszkaiser** [comment]
Please merge.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
