### PR TITLE
Fix Android Build

### PR DESCRIPTION
**Pull request by fdoumet**

### CODE REVIEW

**Comment by fdoumet** [comment]
I signed it!

**Comment by angersson** [comment]
I'm not sure of the context of this PR. Which android build have you fixed? Can you tell me how I can verify this?

**Comment by fdoumet** [comment]
As you can see, the nightly Android builds are failing. To verify it, you can follow the instructions in `/contrib/makefile` and `contrib/android`

**Comment by angersson** [comment]
@aselle @gunan can you look at this? I don't think I have the expertise to review appropriately.

**Comment by gunan** [comment]
Ugh, we have another cmakefile under contrib/android?
Adding @petewarden, as he is the owner of the android build.

In our CI, android builds are passing. ci.tensorflow.org is deprecated, and it has last ran the android build a month ago. So if you are referring to that one the results there are obsolete.
We are working to expose the new CIs results.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment]
@petewarden @aselle please review.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle, @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle, @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by algohali3008** [comment]
Thanks

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle, @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 16 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle, @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 30 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle, @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 45 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle, @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle, @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by petewarden** [comment]
Sorry for the slow review. We're no longer actively maintaining the cmake Android builds for mainline TensorFlow, we're deprecating that in favor of TF Lite, so closing for now.

**Pull request closed without merging**
