### PR TITLE
Tflite micro: Fix #36533 (segfault after failing to allocate tensors in MicroAllocator)

### LINKED ISSUE #36533: Tflite micro: segfault after failing to allocate tensors in MicroAllocator
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux, NixOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: nope
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): latest master
- Python version: C++
- Bazel version (if compiling from source): nope, Make
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: nope
- GPU model and memory: nope

**Describe the current behavior**

`tflite::MicroInterpreter` constructor segfaults

**Describe the expected behavior**

it shouldn't segfault

**Code to reproduce the issue**

grrr call MicroInterpreter constructor with a small arena_size

**Other info / logs**
Fix: https://github.com/tensorflow/tensorflow/blob/753ceb91fc8472a5d9f1293ba97814c04c3a4d4c/tensorflow/lite/micro/micro_allocator.cc#L345 this conditional should return an error code instead of continuing. PR coming up

### PR DESCRIPTION
**Pull request by exFalso**

### CODE REVIEW

**Comment by exFalso** [comment]
@googlebot I signed it!

**Review by wangtz — APPROVED** [review]
Good catch!

**Comment by wangtz** [comment]
Would be good to add a unit test to prevent regression. but doesn't has to be in this PR.

**Comment by gbaned** [comment]
@exFalso Can you please address reviewer comments and Ubuntu Sanity errors. Thanks!

**Pull request merged**
