### PR TITLE
register float16 for gpu kenel of scatter and scatter_nd functions

### LINKED ISSUE #20219: [FEATURE REQUEST] tf.scatter_nd doesn't support half types
I try to use tf.scatter_nd and tf.scatter_max for tf.float16 input, but it reports that it doesn't support half types. Can tf.scatter_nd  and tf.scatter_max add support for half types? Thanks.

@kosklain @dantkz

### PR DESCRIPTION
**Pull request by facaiy**
Fix #20219.

I compile the codes and run those related gpu test cases. All seems passed.

### CODE REVIEW

**Review by josh11b — APPROVED** [review]

**Comment by qlzh727** [comment]
The py3 test are failing. Can u fix the test?

**Comment by qlzh727** [comment]
Adding Alex for some help. @josh11b do you know who's the expert in this part?

**Comment by zheng-xq** [comment]
LGTM.

Overall the kernel might be slower because it does not operator in half2. But we can improve that later if necessary.

**Review by alextp — APPROVED** [review]

**Comment by qlzh727** [comment]
The GPU py3 tests are still failing. All reviewers, please take a closer look.

**Comment by facaiy** [comment]
Thank you, @qlzh727. 

@zheng-xq @alextp 
GPU python 3 tests failed. I checked the log file:

```python
2018-06-26 17:23:41.925524: E tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: AttrValue must not have reference type value of half_ref
	 for attr 'tensor_type'
	; NodeDef: Variable/_1 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2_Variable", tensor_type=DT_HALF_REF, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^ScatterAdd/indices, ^ScatterAdd/updates); Op<name=_Recv; signature= -> tensor:tensor_type; attr=tensor_type:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>
```

There seems something wrong with updating variable. I'm not familiar with low-level implementation of Variable, do you have any idea about the problem? Thanks.

**Comment by alextp** [comment]
I don't understand why we have a ref dtype argument to a send node. @facaiy can you try coercing the failing test to run on the CPU?

**Comment by facaiy** [comment]
@alextp I'm afraid not, because those tests failed are related to float16. Moreover, they are all passed in CPU and GPU(Python2)  environment.

I don't know why we bind `_Recv` node with a ref type `tensor_type=DT_HALF_REF`. Is it a bug when building graph?

**Comment by facaiy** [comment]
I don't know how to debug it. Could you give me some suggestion? Thanks.

**Comment by alextp** [comment]
@facaiy can you reproduce locally? I found that if I build with cuda and python3 and run the test I can see the error.

**Comment by facaiy** [comment]
@alextp Thank you for your help. I'm afraid this is beyond the scope of my knowledge. So I'd like close the PR and let others take over the issue.

**Pull request closed without merging**
