### PR TITLE
Add to_ordinal utility

### PR DESCRIPTION
**Pull request by awsaf49**
This PR will update the `RELEASE.md` for recently added feature `tf.keras.utils.to_ordinal` on Keras (keras-team/keras/pull/17419).

### CODE REVIEW

**Review by haifeng-jin — COMMENTED** [review]
Unfortunately, we are doing the branch cut right now for 2.12 release. And the previous PR got rolledback because of a breakage. I am rolling it forward now, but we will have to wait till 2.13 to release it.

So what will do with the PR is to hold it until there is a `Release 2.13.0` log being added to `RELEASE.md`. Please rebase the PR then to append it there.

**Comment by awsaf49** [comment]
@haifeng-jin  Thanks for letting me know. Any idea when `to_ordinal` will be added for `Release 2.13.0` ?

**Review by haifeng-jin — APPROVED** [review]
The to_ordinal just got rolled forward. It is in the keras codebase now. I will approve this PR to see if we can merge it.

**Comment by awsaf49** [comment]
@haifeng-jin my fork was out of sync, I fixed it just now. Can you please approve the workflow?

**Review by haifeng-jin — APPROVED** [review]
LGTM

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
