### PR TITLE
Added tf.strings.to_number() usage example

### PR DESCRIPTION
**Pull request by HotPotatoC**

### CODE REVIEW

**Review by martinwicke — DISMISSED** [review]
This is fine. If you want to make it extra fine, you could change "Usage Example" to just "Example"

**Comment by HotPotatoC** [comment]
Cool, I've changed it. Please take a look, and happy new years also :)

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Thank you and happy New year!

**Comment by HotPotatoC** [comment]
Happy to contribute! :)

**Comment by martinwicke** [comment]
Thank you!

**Pull request merged**
