### PR TITLE
MKL: Fixing a regression in slice op

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
Fixing a build/runtime issue in MKL Slice op caused by another PR.

### CODE REVIEW

**Review by andydavis1 — APPROVED** [review]

**Comment by mahmoud-abuzaina** [comment]
@gunan can you kick off the test here?

**Comment by gunan** [comment]
We have an ongoing breakage right now. As soon as the fix is verified and merged, I can.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
@gunan, is gpu6 the possibly broken worker? 

Trying again...

Jenkins, test this please.

**Comment by martinwicke** [comment]
Could the conv_op_test failure be related?

**Comment by mahmoud-abuzaina** [comment]
@martinwicke I don't think so since that test is passing on CPU.

**Comment by martinwicke** [comment]
Confirmed by re-running GPU tests.

**Pull request merged**
