### PR TITLE
Extended tf.print to support more options

### PR DESCRIPTION
**Pull request by zimmerrol**
Right now `tf.print` lacks the support of options like `end` or `sep` known from python's `print` function. Adding support for those options might make it easier for people to migrate existing code to TensorFlow (e.g. see [issue 26510](https://github.com/tensorflow/tensorflow/issues/26510)).  This pull request tries to solve this. 

Only small modifications had to be done to support the `end` and `sep` keyword. At the moment one unit test still fails; but it rather looks like a problem in the configuration of the test than a bug in the real code.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by FlashTek** [comment]
@petewarden Will you have the time to review this PR or should someone else take over?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by FlashTek** [comment]
@rthadur If @petewarden does not have time to review this PR can someone else take over?

**Review by tomerk — CHANGES_REQUESTED** [review]
Thank you for the submission, this is great!
Two qs:
1. Do the C++ logging ops tests still pass after this change? They may need to be updated if they rely on the newline appearing. If you want to be completely safe and not change any behavior for people who are using the C++ op not directly through the python API (e.g. already-saved models), it might make sense to add an optional "end" string attribute to the C++ PrintV2 op.
2. Can you make sure to also update `PrintToPythonStdout` in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/pywrap_tfe_src.cc
to make sure that this will work in Jupyter notebooks + colabs?

**Comment by FlashTek** [comment]
@tomerk 
> 1. Do the C++ logging ops tests still pass after this change?
Yes, I made sure of that. I have also added a new unit test to verify the behavior of the new options.

> It might make sense to add an optional "end" string attribute to the C++ PrintV2 op.
Okay. I will take care of that!

> 2. Can you make sure to also update `PrintToPythonStdout` in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/pywrap_tfe_src.cc
>    to make sure that this will work in Jupyter notebooks + colabs?
This should be solved by now, too.

**Comment by rthadur** [comment]
@FlashTek please resolve conflicts.

**Comment by FlashTek** [comment]
@rthadur I solved the conflicts

**Comment by rthadur** [comment]
> @rthadur I solved the conflicts

Thank you , we will wait for @tomerk review.

**Review by tomerk — APPROVED** [review]

**Comment by tomerk** [comment]
Fantastic, thank you!

**Pull request merged**
