### PR TITLE
Implement reference kernel for Softmax into TFLu - Int8

### PR DESCRIPTION
**Pull request by giorgio-arenarm**

### CODE REVIEW

**Review by petewarden — DISMISSED** [review]
Looks good, thanks!

**Comment by giorgio-arenarm** [comment]
Can someone please re-run these tests? They shouldn't be affected by this change

**Comment by giorgio-arenarm** [comment]
Ready to merge

**Comment by rthadur** [comment]
@giorgio-arenarm done.

**Comment by giorgio-arenarm** [comment]
Still not merged, no rebase issues expected

**Comment by rthadur** [comment]
> Still not merged, no rebase issues expected

will try again to merge this again , thanks for your patience.

**Comment by rthadur** [comment]
@giorgio-arenarm can you please check the build failures ?

**Comment by giorgio-arenarm** [comment]
I've had a look at the failures:
https://source.cloud.google.com/results/invocations/b7a114e2-a06d-4aea-8afe-98c75bc071e1/targets/%2F%2Ftensorflow%2Ftools%2Fci_build%2Fbuilds:gen_win_out/log
and
https://source.cloud.google.com/results/invocations/5ce7ad81-1317-4dc0-b366-bee85f0d0221/log

None of them seem to be related to my patch (The errors don't even seem to be related to TFLite). Plus I find weird that Windows Bazel is failing while Windows Bazel GPU isn't. Shall I try to rebase?

**Comment by giorgio-arenarm** [comment]
Hi, I can se that after a rebase only four tests have been launched (against the 9 from before if I recall correctly). Two of them passed and the other two are still "Waiting for status to be reported". Though I don't think "Ubuntu CC" has ever finished running even with past PRs. If there are any changes please keep me updated, thanks!

**Review by petewarden — DISMISSED** [review]

**Comment by rthadur** [comment]
@petewarden this is failing internal tests, can you please help merge this ?

**Comment by giorgio-arenarm** [comment]
Ready to merge

**Comment by rthadur** [comment]
gentle ping @petewarden for review ?

**Review by petewarden — APPROVED** [review]

**Comment by rthadur** [comment]
Changes are submitted internally ,closing this PR. Thank you

**Pull request closed without merging**
