### PR TITLE
Branch 200727545

### PR DESCRIPTION
**Pull request by akshaym**
Manual merge in 
```
tensorflow/tools/api/generator/create_python_api.py
tensorflow/tools/ci_build/install/install_pip_packages.sh
tensorflow/tools/ci_build/install/install_python3.5_pip_packages.sh
tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
tensorflow/tools/pip_package/BUILD
```

### CODE REVIEW

**Review by yifeif — DISMISSED** [review]

**Review by caisq — DISMISSED** [review]
Thanks!

**Comment by caisq** [comment]
@akshaym Can you take a look at the test failure in "Ubuntu Python2"? Looks like something related to the golden API files.

**Comment by akshaym** [comment]
Thanks @caisq. I believe it should be fixed now.

**Comment by caisq** [comment]
Great! Thanks, @akshaym

**Review by yifeif — APPROVED** [review]

**Pull request merged**
