### PR TITLE
Fix routing of quantized tensors

### PR DESCRIPTION
**Pull request by manipopopo**
The original tensor was not replaced with the quantized one when it had already been quantized.

### TODO

- [x] Handle delayed quantization

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
Sorry for the delay.

**Comment by drpngx** [comment]
@suharshs could you take a look?

**Comment by suharshs** [comment]
Hi, sorry for the delay. Can you describe in more detail what this change tries to fix? I don't fully understand the graph that this fails on before this change

**Comment by manipopopo** [comment]
When a kernel `Variable` is shared by two `Conv2D`s, after quantization there will be only one `Conv2D` getting the quantized kernel. 

For example, suppose there is a kernel `K` shared by `Conv2D` `c1` and `Conv2D` `c2`:

`K` > `c1`
`K` > `c2`

When quantizing `c1`, `Quantize` calls `_InsertQuantOp` to quantize the input kernel `K` and feeds the quantized `K` to `c1`:

`K` > `quantized_K` > `c1`

After that when quantizing `c2`,  `Quantize` calls `_InsertQuantOp` to quantize the input kernel `K` again but this time [`_InsertQuantOp` will return immediately](https://github.com/tensorflow/tensorflow/blob/2e7ae3406f0715de9e23d7657827048ed81e57cb/tensorflow/contrib/quantize/python/quantize.py#L543) since `K` has been quantized.

The quantized graph will be

`K` > `quantized_K` > `c1`
`K` > `c2`

This PR changes the quantized graph into

`K` > `quantized_K` > `c1`
`K` > `quantized_K` > `c2`

**Review by raghuraman-k — DISMISSED** [review]
Addresses issue of incorrect quantization when tensors are shared across multiple kernels (like shared weights).
Tested and approved. Thanks for making this useful change!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 19 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 34 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by raghuraman-k** [comment]
@drpngx : Can we get this change integrated? Who can  help with this?

**Comment by manipopopo** [comment]
@suharshs, @raghuraman-k 
I've rebased it onto the master branch.

**Review by raghuraman-k — COMMENTED** [review]
Approved, this change works as expected.

**Review by raghuraman-k — APPROVED** [review]

**Pull request merged**
