### PR TITLE
[LITE] uint8, int8, int16, datatype support for lite ops

### PR DESCRIPTION
**Pull request by siju-samuel**

### CODE REVIEW

**Comment by siju-samuel** [comment]
@alanchiao could you please help to review this changes. TIA

**Comment by siju-samuel** [comment]
@alanchiao could you please help to review this changes. TIA

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@siju-samuel Could you please resolve the conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
