### PR TITLE
[Intel MKL] Updating the MKL CI Infrastructure.

### PR DESCRIPTION
**Pull request by claynerobison**
Adding the following features:
- Dockerfile builds TensorFlow with parameterized bazel options
- gcc version detected inside the container environment in order to set the correct compiler flags
- Support for modern Intel platforms (and CPU instructions)
- Support for alternate base containers

### CODE REVIEW

**Comment by claynerobison** [comment]
@gunan This is our first step to moving out of the old `docker` folder. The CPU Dockerfiles in the new directory work just fine for building for MKL because the TensorFlow build doesn't happen in those Dockerfiles.

**Review by angerson — COMMENTED** [review]
I'm fairly ignorant of MKL in the context of TF's internal builds, so forgive me for asking: is this just for providing a build environment for MKL? I don't know how or if we use this in our internal CI. Is it possible that this would be more fitting in a "unique dockerfiles" subdirectory of dockerfiles/?

**Comment by claynerobison** [comment]
Ya, @gunan will have to answer that question. I considered putting it in the dockerfiles location, but the two scripts made more sense here, and none of the Dockerfiles build TF as part of Docker build. This is essentially a layer on top of other containers that does the actual TF build after detecting the context of the base container.

**Comment by gunan** [comment]
Just to check.
Is the docker container only used for CI, or do you want to publicize and use it for TF docker containers that have MKL enabled?

If 2nd is the case, we should find a way to have it as a part of the new dockerfiles.
Otherwise, the changes are LGTM for the CI.

**Comment by claynerobison** [comment]
Both. We'd like to use this Dockerfile for both CI and to publish our containers. @gunan Where do you recommend we put the files?

**Comment by gunan** [comment]
For the one to distribute, I recommend creating  a dockerfile here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/dockerfiles

But I think we can do that after this PR is merged.

**Review by gunan — DISMISSED** [review]

**Comment by claynerobison** [comment]
Sounds good. Where do you recommend that we put the python script that detects gcc version?

**Comment by angersson** [comment]
Right now it fits well in ci_build, but perhaps if we move them out, it may make sense to put it in a includes directory under `dockerfiles`.

**Comment by claynerobison** [comment]
OK LMK.

**Comment by gunan** [comment]
Ok, lets go ahead and merge this PR for now, and then we can figure out the
rest of the details.

**Comment by angersson** [comment]
Ping @gbaned for merge

**Comment by rthadur** [comment]
@claynerobison thank you for your contribution . can you please check Ubuntu Sanity build failures.

**Comment by claynerobison** [comment]
@gunan @angersson @gbaned This last commit looks frightening, but it's mostly pylint whitespace fixes. The more substantial commit is in tensorflow/tools/ci_build/linux/mkl/build-dev-container.sh.

**Review by gunan — DISMISSED** [review]

**Comment by claynerobison** [comment]
@rthadur @gbaned fixed remaining pylint errors. Ubuntu Sanity check is now passing.

**Review by gunan — DISMISSED** [review]

**Comment by claynerobison** [comment]
@gbaned Would you mind merging this?

**Comment by claynerobison** [comment]
@gbaned @gunan Our internal and external CI are waiting for this. Would you mind flipping the switch?

**Comment by angersson** [comment]
@claynerobison It looks like the PR quietly got stuck in internal CI because set-build-env.py is using Intel's license. Can you change the license to the same license used by other TF files, please?

**Comment by claynerobison** [comment]
@angersson Done.

**Comment by angersson** [comment]
@claynerobison I had to resolve a few straggling linter issues that only showed up on our end. Thanks for your patience!

**Pull request merged**
