### PR TITLE
To fix continuous build, install ca-certificates-java in docker images.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Comment by gunan** [comment]
DONOTMERGE yet.

**Comment by gunan** [comment]
Ready for review, running the 2nd test now.

**Review by drpngx — APPROVED** [review]

**Comment by gunan** [comment]
First tests mostly passed with only a flake
https://ci.tensorflow.org/job/tensorflow-pull-requests-multijob/2217/
Current tests also cleared up the hurdle we have been seeing.

patrick, would you like me to force merge this to clear all the other failures we are seeing?

**Comment by drpngx** [comment]
SG, thanks!

**Comment by drpngx** [comment]
As in, please force merge.

**Pull request merged**
