### PR TITLE
[tosa] Fix wrong intermediate datatype for genericReduceOps

### PR DESCRIPTION
**Pull request by Jerry-Ge**
A quick fix for the issue from here: #58714 

Signed-off-by: Jerry Ge <jerry.ge@arm.com>

### CODE REVIEW

**Review by jpienaar — CHANGES_REQUESTED** [review]
LG, the issue has a small repro that we can add as test here to ensure we don't regress here that would be good to add.

**Comment by Jerry-Ge** [comment]
> 

yea, that's an reasonable request. Should I add that test to `tf-tfl-to-tosa-pipeline.mlir` or add two separate tests to tf and tfl?

**Comment by jpienaar** [comment]
> yea, that's an reasonable request. Should I add that test to `tf-tfl-to-tosa-pipeline.mlir` or add two separate tests to tf and tfl?

The former suffices given the code is shared. But given the size and different users, lets add both as it should be easy to go from one to the other.

**Comment by Jerry-Ge** [comment]
the lit tests now have been pushed : )

**Review by jpienaar — APPROVED** [review]

**Pull request merged**
