### PR TITLE
Add TF_UpdateEdge C API.

### PR DESCRIPTION
**Pull request by Oceania2018**
In order to support more complicated conditional/loop statement flow. We have to expose `graph->graph.UpdateEdge` fucntion to [.NET binding](https://github.com/SciSharp/TensorFlow.NET). There still are several APIs needed to support [MNIST RNN/ LSTM](https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/ImageProcessing/DigitRecognitionRNN.cs) model training that I'll submit in other PR once this one is approved. Thanks.

### CODE REVIEW

**Comment by Oceania2018** [comment]
@saxenasaurabh Can you review this PR?

**Comment by saxenasaurabh** [comment]
Thanks for the PR, could we update the [UpdateEdge](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/c/python_api.cc;l=58;drc=9c75b7ffd22ead5842dcb47e7b037f3bea46b9a7) function in `tensorflow/c/python_api.cc` to call this? 

Also could you please add a unit test?

**Comment by Oceania2018** [comment]
@saxenasaurabh I'll update `tensorflow/c/python_api.cc` to call this API. Can you skip unit test for this? Because basically I just copy and paste the code.

**Comment by saxenasaurabh** [comment]
I think it would be nice to have a test since this is a public API. You should be able to adapt an [existing C++ test](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/graph/graph_test.cc;l=541;drc=000c8f09eae7b266ebda7afb53a83fd65b461db5).

**Comment by Oceania2018** [comment]
I went through this testing code, looks like it not fit for testing public API. It's just for internal graph testing. I think this [test](https://github.com/tensorflow/tensorflow/blob/686912c768fbd845eca78ad16fd6a2074acb4f97/tensorflow/c/c_api_test.cc#L459) is better for graph's public API. Please advise.

**Comment by saxenasaurabh** [comment]
Yes, you should add your test to `c_api_test`. What I meant was that you can add a C equivalent of the C++ test for `UpdateEdge`.

**Comment by Oceania2018** [comment]
@saxenasaurabh @gbaned Please help reivew the unit test of `UpdateEdge`.

**Review by saxenasaurabh — APPROVED** [review]

**Comment by gbaned** [comment]
Seems auto-merge is not happening but the changes are now committed, so we can close this. Thank you for the PR.

**Pull request closed without merging**
