### PR TITLE
Fix for parallel_map_dataset_op_test failure on big endian

### PR DESCRIPTION
**Pull request by anujajakhade**
For Tensorflow v2.0.0, `//tensorflow/core/kernels/data:parallel_map_dataset_op_test` module was failing on s390x  with error "**_Which is: Invalid argument: num_parallel_calls must be greater than zero._**"

The int32 results in a negative value of num_parallel_calls, hence the test case fails on s390x.
When the type is changed to int64, behavior is same for both s390x and Intel.  And all the test cases of parallel_map_dataset_op_test run successfully.
Even after changing int32 to int64, behavior on Intel is unaffected.

### CODE REVIEW

**Comment by jsimsa** [comment]
I believe the problem is with the test and not with the kernel. The op kernel expects a int32 for `num_parallel_calls` but the failing test is creating int64 tensor. Could you please see if changing the test to use int32 for the num_parallel_calls tensors fixes the problem?

**Comment by feihugis** [comment]
@anujajakhade Could you try to change `int64` to `int32` at Line [89](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L89), [111](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L111), [134](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L134), [156](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L156),
[179](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L179), [202](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L202), [226](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L226), [250](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L250), [270](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L270)?

**Comment by anujajakhade** [comment]
> @anujajakhade Could you try to change `int64` to `int32` at Line [89](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L89), [111](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L111), [134](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L134), [156](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L156),
> [179](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L179), [202](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L202), [226](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L226), [250](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L250), [270](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc#L270)?

The mentioned changes work on s390x. Should I do the changes in the same PR ?

**Comment by jsimsa** [comment]
Yes, I revert the change to the kernel.

**Comment by anujajakhade** [comment]
@jsimsa I have done the required changes. Can you please review?

**Review by jsimsa — APPROVED** [review]

**Pull request merged**
