### PR TITLE
[INTEL oneDNN] Code clean: unsupport blocked format for fused batchnorm op

### PR DESCRIPTION
**Pull request by gzmkl**
We will not support blocked format for oneDNN kernel operations.

This PR does related code cleanup of oneDNN FusedBatchNorm op and related tests.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @gzmkl Can you please review this PR ? Thank you!

**Comment by ashiqimranintel** [comment]
Any update on this PR?

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @gzmkl Can you please rebase your branch and resolve conflicts? Thank you!

**Pull request closed without merging**
