### PR TITLE
Removing /contrib/tensorboard and its references

### PR DESCRIPTION
**Pull request by k4r4koyun**
New pull request to master branch, as requested at https://github.com/tensorflow/tensorflow/pull/12768.

Cleaning up "/contrib/tensorboard" since Tensorboard have been moved and we don't need the "/contrib/tensorboard" additionally. (As mentioned before, it creates confusion)

### CODE REVIEW

**Comment by yifeif** [comment]
@goktay do you mind resolve the conflicts? Thanks!

**Comment by goktay** [comment]
I have pulled the current master branch, did the necessary changes, copied all the files to my local repo and pushed it to my github.

Only conflict I have is inside contrib/tensorboard which should be deleted, I don't know why it shows up as a conflict.

Git is not my cup of tea I guess.

**Comment by drpngx** [comment]
@goktay could you pull rebase and push again?

**Comment by sb2nov** [comment]
@goktay can you resolve the merge conflicts

**Comment by martinwicke** [comment]
@goktay, please resolve conflicts.
@jart, please review?

**Comment by jart** [comment]
I really appreciate that you took the time to send us this change @goktay. I've actually been doing some work in contrib/tensorboard recently so I'd like to have this folder stick around for the time being. Some of the things in here could go on the other hand. I'll try to take care of that as soon as I have the cycles.

**Pull request closed without merging**
