### PR TITLE
Combined update for contrib/go

### PR DESCRIPTION
**Pull request by damienstanton**
This PR merges 1700+ commits from `master` into `go`. 

Currently working [in this fork](https://github.com/damienstanton/tensorflow/tree/go).

Changes: 
- Minor syntax alterations to the public C api header. 
- Where merge conflicts occur, code from `master` used exclusively.

Tests:
- [X] `go test` in tensorflow/contrib/go passes.
- [X] Inception model image recognition ([from examples](https://github.com/tensorflow/tensorflow/blob/go/tensorflow/g3doc/tutorials/image_recognition/index.md#usage-with-the-go-api)) works as expected.
- [X] `pip3` build, installation, 'hello world' works as expected.

### CODE REVIEW

**Comment by damienstanton** [comment]
Re: the googlebot's comment on CLA, I am the sole author of this PR. 

I may have pushed some early commits from a new OS installation where my `git config` did not contain my email address.

**Comment by Mistobaan** [comment]
did you add anything go related to this PR? or is just a rebase ? 
if is just a rebase I think the committers can create a cleaner history by rebasing and force update?

**Comment by damienstanton** [comment]
@Mistobaan Mostly a rebase but there are a couple Go specific changes. The exported TF_DataType, and TF_Codes enums needed to be declared differently, also there was a type mismatch where Swig needed a `long long` instead of an `int64_t`.

I'd be happy to rebase/squash locally and resubmit for a cleaner PR.

**Comment by Mistobaan** [comment]
I think would be better to just rebase the current go branch into master and then do new PRs against that. @vrv (or any googlers) can you help on this ? see also #3258

**Comment by damienstanton** [comment]
>rebase the current go branch into master and then do new PRs against that

Okay 👍 I can do that. We can close this PR in that case. I presume we want contrib/go building properly in master, right? Unless there is a specific reason for keeping the Go branch separate

**Pull request closed without merging**
