### PR TITLE
Fixes #16976

### LINKED ISSUE #16976: df982b8de - Split gpu_id.h and GpuIdManager out from build target breaks build for verbs and GDR
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: TF not compiling. (master)
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.5.4
- **GCC/Compiler version (if compiling from source)**: 5.4
- **CUDA/cuDNN version**: 9.1
- **GPU model and memory**: Any
- **Exact command to reproduce**: 

1. ./configure ... with GDR (and/or verbs)
2. bazel build -c opt --config=cuda  //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
Commit df982b8de breaks the build for GDR and verbs. 
> ERROR: /home/eladw/google/tensorflow/tensorflow/contrib/gdr/BUILD:52:1: undeclared inclusion(s) in rule '//tensorflow/contrib/gdr:gdr_memory_manager':
this rule is missing dependency declarations for the following files included by 'tensorflow/contrib/gdr/gdr_memory_manager.cc':
  '/home/eladw/google/tensorflow/tensorflow/core/common_runtime/gpu/gpu_id.h'.

### PR DESCRIPTION
**Pull request by byronyi**

### CODE REVIEW

**Comment by byronyi** [comment]
Mind to check CLA again? @googlebot

**Comment by aaroey** [comment]
@byronyi I'm adding a more general fix, will let you know once it's pushed.

**Comment by aaroey** [comment]
@byronyi I tested that febed14f36eef0d3800d891b18717df36f786852 fixed the issue, would you help to double check? Thanks.

**Comment by byronyi** [comment]
Thanks!

**Pull request closed without merging**
