### PR TITLE
[NVIDIA TF] Update cudnn frontend to v0.8

### PR DESCRIPTION
**Pull request by kaixih**
This PR is to update the cudnn frontend version to v0.8. The release note is [here](https://github.com/NVIDIA/cudnn-frontend/releases/tag/v0.8).

cc. @pjannaty @nluehr

### CODE REVIEW

**Comment by pgpetrak** [comment]
v0.8 is not available at https://github.com/NVIDIA/cudnn-frontend. I cannot proceed until it has been updated.

**Comment by kaixih** [comment]
> v0.8 is not available at https://github.com/NVIDIA/cudnn-frontend at the main branch. I cannot proceed until it has been updated.

Thanks for the comment. Yes, we are working on releasing it soon. And this PR will be updated accordingly. Will ping you after that.

**Comment by pgpetrak** [comment]
There was an update ~1.5 days ago. Is that the final update to v0.8? Or are more changes expected?

**Comment by kaixih** [comment]
@pgpetrak Thanks for the checkup. I have pushed a new commit to use the official v0.8 release and updated the PR description to reflect this. PTAL.

**Review by pgpetrak — APPROVED** [review]
cuDNN Frontend v0.8 has been patched in.

**Comment by kaixih** [comment]
Basically, there are two changes of this PR: (1) update the download url and (2) update the patch file.

Then, I checked the above automatically created PR https://github.com/openxla/xla/pull/1589, and saw one test "XLA Linux GPU" fails.

It seems that the above PR only fetches the change (2) and I don't know how to make it to apply the change (1) (I guess it uses a different way to download the zip rather than `workspace2.bzl`.).

@reedwm Can you help or redirect?

**Comment by reedwm** [comment]
> Basically, there are two changes of this PR: (1) update the download url and (2) update the patch file.
> 
> Then, I checked the above automatically created PR [openxla/xla#1589](https://github.com/openxla/xla/pull/1589), and saw one test "XLA Linux GPU" fails.
> 
> It seems that the above PR only fetches the change (2) and I don't know how to make it to apply the change (1) as well (I guess it uses a different way to download the zip rather than `workspace2.bzl`.).
> 
> @reedwm Can you help or redirect?

@jakeharmon8 do you know how to fix this? I think this PR also needs to update the [`workspace2.bzl` in the openxla/xla repo](https://github.com/openxla/xla/blob/main/workspace2.bzl), in addition to the `workspace2.bzl` that it already updates in the TF repo. But a PR can only update one repo at once. When merging internally, should we update both `workspace2.bzl`s in the same CL?

**Review by mihaimaruseac — COMMENTED** [review]
LG in principle, but letting Jake approve given XLA dependency.

**Comment by AyanmoI** [comment]
Is there an ETA on the merge for this PR. https://github.com/tensorflow/tensorflow/pull/60002 build is dependent on this PR being merged.

**Comment by SandSnip3r** [comment]
@pgpetrak I guess you're still the reviewer for this? I'm going to remove myself as reviewer if you can take care of this.

**Pull request merged**
