### PR TITLE
Allow `keras.utils.Sequence` sub-classes to use sparse/ragged tensors

### LINKED ISSUE #41419: Output of tf.keras.utils.Sequence is automatically cast to Tensor even if it is a SparseTensor
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.5
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8

**Describe the current behavior**
All outputs produced by `tensorflow.keras.utils.Sequence` are automatically cast to `Tensor` when calling `model.fit()`, even if they are of class `SparseTensor`.
This makes it impossible to use sparse operations in a model if the model is trained with the Keras training loop. 

**Describe the expected behavior**
`model.fit()` should not automatically cast the inputs to `Tensor` if the inputs are supported by TensorFlow operations.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.utils import Sequence


class Dataset(Sequence):
    def __init__(self):
        pass

    def __len__(self):
        return 1

    def __getitem__(self, idx):
        return tf.SparseTensor([[0, 1], [1, 0]], [1, 1], (2, 2))


class Net(Model):
    def __init__(self):
        super().__init__()

    def call(self, x, **kwargs):
        return x.values


net = Net()
net.compile()
net.fit(Dataset())
```

Causes the following error:
```python
AttributeError: 'Tensor' object has no attribute 'values'
```

### PR DESCRIPTION
**Pull request by karlhigley**
This adjusts the way `GeneratorDataAdapter` supplies the shapes and types of tensors from the first (peeked) batch when converting from a generator to a `Dataset`, in order to allow sub-classes of `keras.utils.Sequence` to return `SparseTensors` or `RaggedTensors` in batches.

Resolves #41419.

### CODE REVIEW

**Comment by karlhigley** [comment]
@googlebot I signed it!

**Comment by karlhigley** [comment]
@nluehr Here's the PR for the change related to downstream issues in [NVTabular](https://github.com/NVIDIA/NVTabular). Thanks for your help!

**Comment by gbaned** [comment]
Please submit this PR to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. Thankyou.
@fchollet, @qlzh727, @tomerk

**Comment by gbaned** [comment]
Closing this PR since it is summited to keras-team/keras#15264.  Thank you!

**Pull request closed without merging**
