### PR TITLE
Update Custom Op instructions to use tf.sysconfg flags

### PR DESCRIPTION
**Pull request by alsrgv**

### CODE REVIEW

**Review by allenlavoie — APPROVED** [review]
Awesome, thanks!

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by alsrgv** [comment]
@jhseu, looks like a bunch of tests failed due to an internal error. Could you re-run?

**Comment by alsrgv** [comment]
@jhseu, good to go? :-)

**Pull request merged**
