### PR TITLE
Add "python 3 only" support for bazel build

### PR DESCRIPTION
**Pull request by yongtang**
When building tensorflow in a python3 system (i.e., only `/usr/bin/python3` and no `/usr/bin/python` in the system), even though `/usr/bin/python3` is specified during the configure the following failure still occur:
```
SUBCOMMAND: # //tensorflow/core:version_info_gen [action 'Executing genrule //tensorflow/core:version_info_gen [for host]']
(cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; tensorflow/tools/git/gen_git_source.py --generate external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref "bazel-out/host/genfiles/tensorflow/core/util/version_info.cc" --git_tag_override=${GIT_TAG_OVERRIDE:-}')
ERROR: /home/ubuntu/tensorflow/tensorflow/core/BUILD:2015:1: Executing genrule //tensorflow/core:version_info_gen failed (Exit 127)
/usr/bin/env: 'python': No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/ubuntu/tensorflow/tensorflow/tools/api/generator/BUILD:27:1 Executing genrule //tensorflow/core:version_info_gen failed (Exit 127)
INFO: Elapsed time: 391.217s, Critical Path: 46.74s
INFO: 656 processes, local.
FAILED: Build did NOT complete successfully
```

This fix adds the necessary `${PYTHON_BIN_PATH}` (configured already in `./configure`)
into related commands so that bazel build works even in python 3 only environment.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by gunan** [comment]
Unfortunately, bazel inserts the shebang line `#!/usr/bin/env python` to the python files in "builds". Therefore even with this change we are blocked by that bazel bug to be able to build on a python3 only environment.
You can see more information here:
https://github.com/tensorflow/tensorflow/issues/15618

The issue is escalated to bazel team, and we are waiting for a resolution from them.

**Comment by yongtang** [comment]
@gunan I updated the PR. Now in Windows the behavior remains the same while on Linux it will use `PYTHON_BIN_PATH`.

I tried a python 3 only of `Ubuntu 18.04` (only `/usr/bin/python3`, no `/usr/bin/python`). The following command builds successfully:
```
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

Please take a look and let me know if there are any issues.

**Review by gunan — COMMENTED** [review]
Let's wait until @meteorcloudy can take a look. We want to keep windows bazel build in a working condition, because we are very close to switching to bazel on windows.

**Review by meteorcloudy — APPROVED** [review]
All looks good to me and the Bazel Windows presubmit passes

**Review by gunan — APPROVED** [review]

**Comment by petewarden** [comment]
It looks like this is breaking the Raspberry Pi build. I'm still investigating exactly why, but it appears that the PYTHON_BIN_PATH is not set for some build steps. It could be because cross-compilation rules don't pick them up, or something related to this tools bug on bazel:
https://github.com/bazelbuild/bazel/issues/4008

It's not clear from my investigation, and some fixes I attempted didn't solve the issue, so I'm going to prepare a rollback of this PR for now, to make sure we get the Pi builds working for 1.9.

**Comment by yongtang** [comment]
Thanks@petewarden, and sorry for the trouble that may have caused.

**Comment by petewarden** [comment]
No worries at all @yongtang, I appreciate the work you put into this PR! Thanks for putting it together, I hope we'll be able to put it back in soon once we figure out the issues with other platforms.

**Comment by petewarden** [comment]
I have https://github.com/tensorflow/tensorflow/pull/19678 pending as a rollback

**Pull request merged**
