### PR TITLE
add int8 support for tf.tile

### PR DESCRIPTION
**Pull request by goexle**
add int8 support for tf.tile otherwise there is an error after int8 quantization

### CODE REVIEW

**Comment by abattery** [comment]
@goexle could you provide some contexts to understand why this op is needed?

**Comment by abattery** [comment]
Fyi @thaink @teijeong

**Comment by thaink** [comment]
@goexle We are having an internal commit for this as well.

@abattery our internal cl is in better state since it also add quantization support and increase the op version.

**Comment by goexle** [comment]
@thaink thanks for mentioning. Do you know when your internal commit will be pushed to master?

**Comment by thaink** [comment]
Not sure about that yet but It is not a complicated one so I hope it will be landed soon.
I'll let you know then.

**Comment by thaink** [comment]
@goexle Can you describe a bit about your use-case?
Ex: What model are you trying to run and why does it need int8?

**Comment by goexle** [comment]
Yes sure. I want to quantize a model which is using the tf.tile operation. And I want to quantize it to int8.

Am 17. August 2021 02:22:59 MESZ schrieb Thai Nguyen ***@***.***>:
***@***.*** Can you describe a bit about your use-case?

**Comment by gbaned** [comment]
@goexle  Any update on this PR? Please. Thanks!

**Comment by goexle** [comment]
@gbaned do you need further explanation about the use case or the model type beyond the mentioned use case?
The model is a modified version of TDNN for speech recognition.
If you need anything else, please let me know

**Comment by gbaned** [comment]
> @gbaned do you need further explanation about the use case or the model type beyond the mentioned use case? The model is a modified version of TDNN for speech recognition. If you need anything else, please let me know

@goexle Thank you for the update.

**Pull request closed without merging**
