### PR TITLE
[ROCm] skip randomized_tests_mlir_seeded

### PR DESCRIPTION
**Pull request by jayfurmanek**
Disable randomized_tests_mlir_seeded tests on ROCm

@cheshire @chsigg @deven-amd @reza-amd

### CODE REVIEW

**Comment by reza-amd** [comment]
@googlebot I consent.

**Comment by jayfurmanek** [comment]
@cheshire gentle nudge on this one. thx!

**Review by chsigg — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by deven-amd** [comment]
@gbaned this PR seems to have been stuck in the merge pipeline....let us know if we can do anything on our end to help 

thanks

**Review by gbaned — APPROVED** [review]

**Comment by chsigg** [comment]
I will pull it manually. Thanks.

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by jayfurmanek** [comment]
So this PR is comically hitting every branch while falling out of the copybara tree. Anything I can do to help it? Is it being rejected on import as too small of a change, or mistaken for a cosmetic change?

**Comment by gbaned** [comment]
@jayfurmanek Can you please address Ubuntu Sanity errors? Thanks!

**Comment by gbaned** [comment]
Seems auto-merge is not happening but the changes are merged into master now, so we can close this. Thank you for the PR.

**Pull request closed without merging**
