### PR TITLE
Add @org_tensorflow to targets in tensorflow.bzl for submodule usage

### LINKED ISSUE #8439: tf_kernel_library doesn't work from repo containing tensorflow as a submodule
`tf_kernel_library` and friends from `tensorflow.bzl` refer to deps like `//tensorflow/core:gpu_lib`.  These deps do not work if TensorFlow exists only under `@org_tensorflow`, which results in errors like

    bazel build ...
    WARNING: /usr/local/google/home/geoffreyi/.cache/bazel/_bazel_geoffreyi/f928d2088d4c5ef4e2f54ff2af6f8a71/external/org_tensorflow/tensorflow/workspace.bzl:72:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
    WARNING: /usr/local/google/home/geoffreyi/.cache/bazel/_bazel_geoffreyi/f928d2088d4c5ef4e2f54ff2af6f8a71/external/org_fold/WORKSPACE:1: Workspace name in /usr/local/google/home/geoffreyi/.cache/bazel/_bazel_geoffreyi/f928d2088d4c5ef4e2f54ff2af6f8a71/external/org_fold/WORKSPACE (@org_tensorflow_fold) does not match the name given in the repository's definition (@org_fold); this will cause a build error in future versions.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: Analysis of target '//deepmath/guidance:clause_ops' failed; build aborted.
    INFO: Elapsed time: 0.320s

### PR DESCRIPTION
**Pull request by girving**
tf_kernel_library and friends do not currently work if called from a
repo that contains tensorflow as submodule.

Fixes #8439.

### CODE REVIEW

**Comment by girving** [comment]
This is a version of https://github.com/tensorflow/tensorflow/pull/8606 with `str(Label(` replaced with `@org_tensorflow`.

**Comment by girving** [comment]
@gunan So clearly `@org_tensorflow//tensorflow` is not equivalent to `//tensorflow` if you build tensorflow not as a submodule.  This would seem to imply to me that the `str(Label(` is better, given that that approach works and this one doesn't.

**Comment by girving** [comment]
They both seem equivalent if tensorflow is used as a submodule.

**Comment by gunan** [comment]
I understand.
To unblock your usecase, let's go with your other PR.
Thank you very much for waiting for bazel upgrade and testing this out.

@damienmg FYI.

**Pull request closed without merging**
