### PR TITLE
LSTM input dropout bug

### PR DESCRIPTION
**Pull request by zacwellmer**
occurs when _could_use_gpu_kernel is True

### CODE REVIEW

**Comment by zacwellmer** [comment]
see [this issue](https://github.com/tensorflow/tensorflow/issues/40215) for details

**Comment by qlzh727** [comment]
Thanks for sending the PR, and sorry for dropping the ball on the Github issue. Let me comment on the https://github.com/tensorflow/tensorflow/issues/40215

**Comment by gbaned** [comment]
@qlzh727 Any update on this PR? Please. Thanks!

**Comment by qlzh727** [comment]
The related #40215 has been closed. Closing this PR since it is not needed any more.

**Pull request closed without merging**
