### PR TITLE
Improve windows bazel python test suite.

### PR DESCRIPTION
**Pull request by gunan**
- Create new tags, no_windows and no_windows_gpu
- Instead of a separate maintained list, use bazel tags to exclude tests.
- Tag all the python tests that are known to have issues in windows.

### CODE REVIEW

**Comment by gunan** [comment]
Running windows bazel presubmit here:
http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/18/

**Comment by yifeif** [comment]
new link http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/19/

**Comment by gunan** [comment]
@meteorcloudy There are some build errors.
http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/19/console

Could you help us debug these?

**Comment by gunan** [comment]
Here is another try
http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/20/

**Comment by meteorcloudy** [comment]
@gunan @yifeif Thank you for making this change! This is great!
From the latest run, it seems only `//py_test_dir/tensorflow/python/debug:examples_test` is failing. And it turns out to be a shell test!
So, adding `--test_lang_filters=py` as a test option should solve this problem.

**Review by meteorcloudy — DISMISSED** [review]
Please also add no_windows tag to `//tensorflow/python:session_test`, although it's commented out, it was in the failing list before.

**Comment by gunan** [comment]
Another try with all the changes requested:
http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/21/

**Review by yifeif — APPROVED** [review]

**Pull request merged**
