### PR TITLE
Fix of issue #10479

### PR DESCRIPTION
**Pull request by smksyj**
Fixes issue #10479

### CODE REVIEW

**Comment by smksyj** [comment]
I signed it

**Review by ebrevdo — CHANGES_REQUESTED** [review]
Can you update Orthogonal's docstring to explain what happens in the 1d case?  Also can you fix the scalar case, where shape=[] ?

**Comment by drpngx** [comment]
@smksyj any luck with this?

**Comment by ebrevdo** [comment]
@smksyj ping.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by rmlarsen** [comment]
@smksyj any chance you'll finish this up?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by ebrevdo** [comment]
Please reopen when you've had a chance to finish this PR.

**Pull request closed without merging**
