### PR TITLE
Revert "NADAM Optimizer (#8405)"

### PR DESCRIPTION
**Pull request by drpngx**
We need to put this in contrib instead.

This reverts commit 86d3891ba6612552347beaabe27edac11f5758d7.

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]

**Review by caisq — APPROVED** [review]

**Comment by cancan101** [comment]
Is there a new PR with this moved to contrib?

**Comment by drpngx** [comment]
No, we're considering a merge with https://github.com/tensorflow/tensorflow/pull/9175 for cleaner code.

**Pull request merged**
