### PR TITLE
[TFLite 16x8] Notebook for 16x8 post-training quantization.

### PR DESCRIPTION
**Pull request by wwwind**
This PR provides a notebook with tutorial on 16x8 post-training quantization. 
It uses a simple MNIST example to demonstrate how this mode should be used.

### CODE REVIEW

**Review by renjie-liu — COMMENTED** [review]
looks good in general!

Can you wait for Khanh's review as well?

thanks

**Comment by khanhlvg** [comment]
The notebook LGTM. Can you also update these pages?
* https://www.tensorflow.org/lite/performance/model_optimization
* https://www.tensorflow.org/lite/performance/post_training_quantization

**Comment by wwwind** [comment]
Hi @khanhlvg Thanks for the review! I have changes to update these pages, but I want to upstream them in a separate PR. Is it okay ?

**Comment by khanhlvg** [comment]
SGTM. Thanks @wwwind !

**Review by khanhlvg — DISMISSED** [review]

**Review by renjie-liu — COMMENTED** [review]
Hi Can you enable python3 for the colab and clear the outputs?

thanks a lot!

**Comment by gbaned** [comment]
@wwwind Can you please check @renjie-liu's comments and keep us posted ? Thanks!

**Comment by wwwind** [comment]
Hi @renjie-liu Sorry, but all output cells are empty in this notebook as far as I can see. 
Also, what do you mean by "enable python3 for the colab" ?
Thanks a lot for the review!

**Comment by gbaned** [comment]
@renjie-liu Can you please assist on above comments from @wwwind. Thanks!

**Comment by alanchiao** [comment]
A drive-by comment as @renjie-liu clarifies. Given that the feature is experimental, it'd be good to also mark it in the navigation side bar, like below.

Screen Shot 2020-08-14 at 11 28 40 AM

**Comment by gbaned** [comment]
@wwwind  Can you please check @alanchiao's comments and keep us posted ? Thanks!

**Comment by wwwind** [comment]
Hi @renjie-liu !
Could you please re-approve this PR?
- i think i enabled python3 correctly now in this notebook by setting 
`"kernelspec": {
"display_name": "Python 3",
"name": "python3"
}`
- i checked that all output cells are empty:
`"outputs": [],`
- added 'experimental' status as well

Thanks for the review!

**Comment by akarmi** [comment]
> 
> 
> A drive-by comment as @renjie-liu clarifies. Given that the feature is experimental, it'd be good to also mark it in the navigation side bar, like below.
> 
> Screen Shot 2020-08-14 at 11 28 40 AM

@alanchiao, how is that done, could you point at the source example please?

**Comment by gbaned** [comment]
@alanchiao Can you please take a look on above comments from @akarmi. Thanks!

**Comment by alanchiao** [comment]
@gbaned : Elena figured out how to add the "experimental" status, so Anton's comment is resolved. @renjie-liu to finalize this.

**Review by renjie-liu — DISMISSED** [review]

**Review by khanhlvg — CHANGES_REQUESTED** [review]
> Use the Colab's "private outputs" setting to clear oputputs for tensorflow notebooks: 
> `edit->notebook settings->omit cell output`
> Found no '"private_outputs": true' in file.

The internal lint system raised this error and it likely blocked the PR merge.
Could you sync this branch with master make the change and resend the PR?

**Comment by wwwind** [comment]
Hi @khanhlvg Thanks for the review! I updated the notebook as suggested. Could you please re-approve ?

**Review by khanhlvg — APPROVED** [review]

**Review by rthadur — APPROVED** [review]

**Pull request merged**
