### PR TITLE
CudaRoot() returns the configured CUDA toolkit path.

### PR DESCRIPTION
**Pull request by wujingyue**
Fixes the problem of XLA being unable to find libdevice files if not executed through bazel. For example,
http://stackoverflow.com/questions/41729019/notfounderror-running-tensorflow-xla-example-libdevice-compute-35-10-bc/41800414#41800414

### CODE REVIEW

**Comment by wujingyue** [comment]
The checks are still in the process of "Waiting for status to be reported". Any actions on my side to get them run and finish?

**Review by hawkinsp — APPROVED** [review]
Looks good to me.

**Comment by hawkinsp** [comment]
Jenkins, test this please.

**Comment by jlebar** [comment]
Are the tests stuck here?

**Comment by yaroslavvb** [comment]
@martinwicke, can @hawkinsp trigger tests? @caisq to trigger tests

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
It looks like this breaks the build. @wujingyue can you take another look?

**Comment by wujingyue** [comment]
Yes. I'm looking at those failures.

**Comment by hawkinsp** [comment]
@tensorflow-jenkins test this please

**Comment by wujingyue** [comment]
@tensorflow-jenkins test this please

**Comment by gunan** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@wujingyue it looks like the Android and Windows builds are still failing to find "cuda/cuda_config.h".

ERROR: /workspace/tensorflow/core/BUILD:798:1: C++ compilation of rule '//tensorflow/core:android_tensorflow_lib_lite' failed: process-wrapper failed: error executing command /var/lib/jenkins/workspace/tensorflow-pull-requests-android/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/_bin/process-wrapper -1 5 - - ... (remaining 71 argument(s) skipped).
tensorflow/core/platform/default/cuda_libdevice_path.cc:20:30: fatal error: cuda/cuda_config.h: No such file or directory
 #include "cuda/cuda_config.h"
                              ^
compilation terminated.

**Comment by wujingyue** [comment]
I re-spun this PR internally, because I can run tests more easily over there. 

It has now landed as https://github.com/tensorflow/tensorflow/commit/c1238db44e3344b661ae3e6aa17ff74898569b11. So closing this PR.

**Pull request closed without merging**
