### PR TITLE
MNIST downloader doesn't work as expected

### PR DESCRIPTION
**Pull request by MicaelCarvalho**
See: https://www.tensorflow.org/versions/r0.9/tutorials/mnist/pros/index.html

> For your convenience, we've included a script which automatically downloads and imports the MNIST dataset. It will create a directory 'MNIST_data' in which to store the data files.

Linked to this file: https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/examples/tutorials/mnist/input_data.py

Which currently doesn't create any folder.

### CODE REVIEW

**Comment by MicaelCarvalho** [comment]
Signed.

**Comment by vrv** [comment]
Assigning to tf learn people, since this seems like a bug they should fix instead?

**Comment by martinwicke** [comment]
@ilblackdragon this will likely break some tests. At the very least this change would need some changes to the examples? Maybe it's better to adjust the mnist tutorial text to change the reference to the input.

**Comment by ilblackdragon** [comment]
@tensorflow-jenkins test this please!

@martinwicke not sure if it will break tests, let's see. Indeed changing the tutorial text makes sense.

**Comment by martinwicke** [comment]
Jenkins, test this please? For real?

**Comment by vrv** [comment]
Indeed, some failures unfortunately.  For example:

FAIL: //tensorflow/examples/tutorials/mnist:fully_connected_feed_test (see /private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/tensorflow-pull-requests-mac/bazel-out/local_darwin-opt/testlogs/tensorflow/examples/tutorials/mnist/fully_connected_feed_test/test.log).
INFO: From Testing //tensorflow/examples/tutorials/mnist:fully_connected_feed_test:
==================== Test output for //tensorflow/examples/tutorials/mnist:fully_connected_feed_test:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/tensorflow-pull-requests-mac/bazel-out/local_darwin-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/tensorflow/examples/tutorials/mnist/fully_connected_feed.py", line 27, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/tensorflow-pull-requests-mac/bazel-out/local_darwin-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/tensorflow/examples/tutorials/mnist/input_data.py", line 30, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
ImportError: cannot import name input_data

**Comment by MicaelCarvalho** [comment]
The initial pull request was plain bad code (can't really describe it better -- shame on me). I fixed the problem with another commit, and I believe it should work now without crashing stuff.

However, I also believe this pull request should be refused, and the tutorial should be corrected instead, just to make clear that the user must run the code to download the dataset himself -- the same code that is already there. The difference in the text is that the said script won't download anything, but will help with it.

Here is why I think it should be refused: This script is used in 3 more files (fully_connected_feed.py, mnist_softmax.py and mnist_with_summaries.py). These files use flags to specify the directory in which the dataset should be saved. Saving the dataset in the current folder would be too strict, and the said scripts would still download it later on their own folders.

TL;DL: It will work for the tutorial, but it will download the dataset without using it. Two command lines are enough, and they are already in the tutorial. Just change the text so it won't say that the script downloads things. Refuse this pull request, please. :-)

**Comment by vrv** [comment]
Sounds good -- we'll close this request.  Feel free to send us a PR to correct our tutorials as you best see fit!

**Pull request closed without merging**
