### PR TITLE
[INTEL MKL] MKL DNN 0.x code cleanup - FusedBatchNorm op

### PR DESCRIPTION
**Pull request by gzmkl**
DNN 0.x cleanup of MKL FusedBatchNorm op:
 (1) Remove all DNN 0.x related code;

 (2) Replace all DNN 1.x macro usages

### CODE REVIEW

**Comment by gbaned** [comment]
@gzmkl Can you please resolve conflicts? Thanks!

**Comment by gzmkl** [comment]
@gbaned.  There was a recent commit (by my teammate at Intel) on the same source file. That commit had changes which
did not clean up DNN 0.x code block (also DNN 1.x macros are still used).  I will rebase and then re-do the clean-up.
Thanks!

**Comment by gzmkl** [comment]
@gbaned Also, the following PR has to go first as part of Tensorflow 2.4 release. 
https://github.com/tensorflow/tensorflow/pull/43504
The above PR does a lot of change in the same source file tensorflow/core/kernels/mkl/mkl_fused_batch_norm_op.cc. 

So I may need to wait a couple of weeks before I can rebase and do cleanup. I will notify you once it is ready.

**Comment by penpornk** [comment]
@gzmkl Thank you for the note! I just approved #43504. It should be merged in a day or two if there's no problem.

**Comment by gzmkl** [comment]
@penpornk Thank you for letting me know!

**Comment by penpornk** [comment]
@gzmkl  FYI, #43504 is merged.

**Comment by gbaned** [comment]
@gzmkl Can you please resolve conflicts? Thanks!

**Comment by gzmkl** [comment]
@gbaned  Because there are a lot of changes in a recent merged PR (related to MKL native format support) on the same source file mkl_fused_batch_norm_op.cc, I am in the process of getting approval of an INTERNAL PR. Once it is done, I will submit a new PR to replace this one.  Thanks!

**Comment by gzmkl** [comment]
@penpornk @gbaned  Hi, I have done any round of cleanup after rebase with PR #43504 changes. So this one shall be fine and there is no need to submit a new PR.  Thanks!

**Review by penpornk — APPROVED** [review]
Thank you for the clean-up! I'm so sorry for the delay!

**Pull request merged**
