### PR TITLE
word2vec: Create directories for saving summaries, if necessary.

### PR DESCRIPTION
**Pull request by darrengarvey**
Simple change to allow passing a directory that doesn't exist to `--save_path` in the word2vec examples.

### CODE REVIEW

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@darrengarvey Please fix indentation:

FAIL: Found 2 non-whitelited pylint errors:
tensorflow/models/embedding/word2vec_optimized.py:130: [W0311(bad-indentation), ] Bad indentation. Found 8 spaces, expected 6

tensorflow/models/embedding/word2vec.py:151: [W0311(bad-indentation), ] Bad indentation. Found 8 spaces, expected 6

**Comment by darrengarvey** [comment]
@rmlarsen - Fixed. Sorry about that.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@darrengarvey No worries. Thanks for the fix.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
