### PR TITLE
[MLIR][tosa] Fixed tf.StridedSlice lowering to tosa with new_axis_mask/shrink_axis_mask

### PR DESCRIPTION
**Pull request by AviadCo**
* When using tf.StridedSlice with new_axis_mask/shrink_axis_mask we must take into account the new/deleted dimentioned in begin_mask & end_mask.

### CODE REVIEW

**Comment by AviadCo** [comment]
Hi @rsuderman 
I would appreciate if you take a look at this fix, thanks.

**Comment by AviadCo** [comment]
kindly reminder

**Comment by gbaned** [comment]
> kindly reminder

Hello @AviadCo Sorry for the delay.

**Comment by gbaned** [comment]
Hi @AviadCo Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @AviadCo Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @AviadCo Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @AviadCo Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @AviadCo I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for you contribution!

**Pull request closed without merging**
