### PR TITLE
Changed TfLiteFusedActivation to TfLiteActivation

### PR DESCRIPTION
**Pull request by joyalbin**

### CODE REVIEW

**Review by karimnosseir — APPROVED** [review]

**Comment by joyalbin** [comment]
@rthadur Could you please kindly check this change for merge

**Comment by rthadur** [comment]
> @rthadur Could you please kindly check this change for merge

@jdduke can you please help merge this PR internally

**Comment by jdduke** [comment]
Thanks for your patience, but these kinds of minor refactorings have quite a bit of downstream impact in our internal code, so it's not a straightforward pull request.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by jdduke** [comment]
There was too much downstream impact, so let's just leave the name as-is. Apologies for the hassle.

**Pull request closed without merging**
