### PR TITLE
Cumsum reference op test

### PR DESCRIPTION
**Pull request by ddavis-2015**
This adds the test  for the CUMSUM reference op code.

This PR is in reference to issue #49913

### CODE REVIEW

**Comment by abattery** [comment]
Thanks for creating this PR. Instead of creating duplicated test case, could you merge these new test cases with the existing cumsum_test.cc?

For example, 

```

const auto kKernelMap = new std::map<string, TfLiteRegistration*>({
    {"Reference", ops::builtin::Register_TRANSPOSECONV_REF()},
    {"GenericOptimized", ops::builtin::Register_TRANSPOSECONV_GENERIC_OPT()},
});
...


INSTANTIATE_TEST_SUITE_P(
    TransposeConvOpTest, TransposeConvOpTest,
    ::testing::Combine(
        ::testing::ValuesIn(SingleOpTest::GetKernelTags(*kKernelMap)),
        ::testing::Values(TestType::kConst, TestType::kDynamic)));
```

See also https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/transpose_conv_test.cc#L129.

**Comment by ddavis-2015** [comment]
The suggested method for combining the tests will not work here.  The CUMSUM kernel only has a single registration and the Eval code for that kernel will only call the optimized operator code.

**Comment by abattery** [comment]
It would be better to have the reference op version in order to make the reference kernel version visible to users.

Could you make the changes in the cumsum.cc to have the reference op registration like we have the above transpose conv op?

**Comment by advaitjain** [comment]
With TFLM moving to its own GitHub repository, we are not going to be merging any TFLM specific pull requests in the TensorFlow repository starting today.

I am closing the current PR but please feel free to open a new PR in https://github.com/tensorflow/tflite-micro/.

https://groups.google.com/a/tensorflow.org/g/micro/c/W4DACgjPmOE

**Comment by ddavis-2015** [comment]
This PR is for TfLite, not for TFLM

**Comment by abattery** [comment]
Closing due to no activity on the suggestion.

**Pull request closed without merging**
