### PR TITLE
Revert changes in TrainingHelper that cause "no gradient" error

### PR DESCRIPTION
**Pull request by sleighsoft**
Change occured in https://github.com/tensorflow/tensorflow/commit/69c324591ba4dfeafb403ee59de56ffe063c1e94

Discussed in https://github.com/tensorflow/tensorflow/issues/15278

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by yifeif** [comment]
cc: @joel-shor

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by Androbin** [comment]
Was it intended to revert only one of the two instances?

**Comment by sleighsoft** [comment]
I have not tested the GreedyEmbeddingHelper so I did not apply that fix there.

**Comment by Androbin** [comment]
Does the other function also depend on gradient?

**Comment by sleighsoft** [comment]
If you use the sample_ids from GreedyEmbeddingHelper for any kind of loss calculation then yes, this would probably also throw an error right now.
I can open up a pull request for that one as well. But I will not have tested it in that case.

**Pull request merged**
