### PR TITLE
Fixing crosstool config file to build tensorflow on PowerPC architect…

### PR DESCRIPTION
**Pull request by npanpaliya**
…ures

### CODE REVIEW

**Comment by yifeif** [comment]
@keveman could you take a look?

**Comment by keveman** [comment]
@damienmg Damien, can you take a look? I am not 100% sure about the syntax and semantics of that file.

**Comment by damienmg** [comment]
LGTM

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by npanpaliya** [comment]
@yifeif - I wanted to know if this change would be part of Tensorflow 0.10.0 release. It actually missed 0.10.0rc0 by just one day or even less than that. Request to kindly include this change in the next RC(if any) or final release of 0.10.0.

**Pull request merged**
