### PR TITLE
Add a mutex in cuda_solvers GetrfImpl.

### PR DESCRIPTION
**Pull request by codrut3**
This should solve issue #13558. Because NVIDIA does not publish the code, it is not possible to prove
the bug is in the cuSolver function. However, I have removed / commented code from
matrix_inverse_op.cpp until essentially only the call to solver->Getrf remained, and from @yaroslavvb' 
project mostly everything except the regularized_inverse calls, and the segmentation fault still
occurred. It did not appear when there was a single thread calling regularized_inverse. The segmentation fault always occurs without my change, and never after introducing the
lock (although that in itself does not mean the bug is solved).

Note that GetrsImpl is already protected with a lock, so apparently this issue was known.

Finally, @yaroslavvb has a second stacktrace which does not involve the Getrf function.
I could not reproduce this error, but it may be a different bug.

### CODE REVIEW

**Comment by yaroslavvb** [comment]
Impressive investigation!

**Comment by codrut3** [comment]
Hi @rmlarsen,

Please, would you have some time to look at this PR?

**Comment by codrut3** [comment]
Only one test fails: //tensorflow/core:util_saved_tensor_slice_util_test. It does not seem related to my change (it doesn't even use CUDA). Also, I can't reproduce this error on my computer.

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@codrut3 I have sadly had to add similar mutexes due to races in cusolver. NVIDIA is aware of the problem and I believe the situation should be improved in Cuda9.
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by drpngx** [comment]
OK, we are moving to cuda9. could you update and test with the new version?

**Comment by codrut3** [comment]
Hi @drpngx ,

Someone else added in the meantime the mutex, so the change is no longer needed. However, my PR also fixes a typo, at least this could merged. Because it's just a comment change, I don't think it requires testing.

**Comment by drpngx** [comment]
We have to test everything. You never know when something is going to break.

Jenkins, test this please.

**Comment by drpngx** [comment]
/CC @gunan Ran out of disk space on the Jenkins build here too.

```
devmapper: Thin Pool has 968455 free data blocks which is less than minimum required 983040 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior
```
Jenkins, test this please.

**Pull request merged**
