### PR TITLE
Add DEVICE_DEFAULT registration for DataFormatDimMap and DataFormatVecPermute

### PR DESCRIPTION
**Pull request by PatriceVignola**
`DataFormatDimMap` and `DataFormatVecPermute` are necessary for pluggable devices with the `GPU` type that want to leverage existing grappler optimizations.

### CODE REVIEW

**Comment by gbaned** [comment]
@rohan100jain Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rohan100jain Can you please review this PR ? Thank you!

**Comment by PatriceVignola** [comment]
Bumping this to hopefully get some eyes on it. `DataFormatDimMap` and `DataFormatVecPermute` are necessary for pluggable devices with the `GPU` type that want to leverage existing grappler optimizations. Thanks!

**Review by penpornk — APPROVED** [review]
Thank you for the PR and sorry for the delay!

**Pull request merged**
