### PR TITLE
TF Lite toco/tflite warning fix

### PR DESCRIPTION
**Pull request by Dayananda-V**
toco/tflite module warning fix

### CODE REVIEW

**Comment by gbaned** [comment]
@achowdhery Can you please review this PR? Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @achowdhery: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Review by petewarden — APPROVED** [review]
Thanks for the fix, and for your patience with the long review time!

**Pull request merged**
