### PR TITLE
Swap dictionary and tensor for readability

### PR DESCRIPTION
**Pull request by raviqqe**

### CODE REVIEW

**Comment by raviqqe** [comment]
I signed it!!!

**Review by jhseu — APPROVED** [review]

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by caisq** [comment]
The Windows cmake build failure looks unrelated. @mrry and @gunan, can you take a look?

**Comment by mrry** [comment]
@caisq Yes, it looks unrelated.

**Comment by caisq** [comment]
PR merged. Thanks, @raviqqe !

**Pull request merged**
