### PR TITLE
Update doc and add tests about multi_hot labels with vocabulary

### PR DESCRIPTION
**Pull request by ravwojdyla**

### CODE REVIEW

**Comment by ravwojdyla** [comment]
CLA singed via Spotify, also signed my personal just now.

**Comment by ravwojdyla** [comment]
Right now when label vocabulary is set, the doc says that:

```
If `label_vocabulary` is given, a string `SparseTensor`. The `dense_shape`
must be `[D0, D1, ... DN, ?]` and the values within `label_vocabulary`.
```

but if you pass the label vocabulary and labels as multi hot it works fine too - see the test. I don't have a strong opinion about failing in that case - this PR fixes the doc and adds tests for that case, but I can also try to fail in such case if that is what we want to do. What's your opinion?

**Review by ispirmustafa — APPROVED** [review]

**Comment by ravwojdyla** [comment]
@qlzh727 @ispirmustafa thanks for the feedback. The error in the tests doesn't seem related?

**Comment by qlzh727** [comment]
Seems to be a flaky test, let me rerun it.

**Pull request merged**
