### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dauba-dauba**
Add more detail on required project changes to include TensorFlow support.

### CODE REVIEW

**Comment by andrewharp** [comment]
@tensorflow-jenkins test this please

**Comment by dauba-dauba** [comment]
//tensorflow/contrib/learn:export_test failed. I'm not sure how this commit could cause that. Is it a flaky test?

**Comment by terrytangyuan** [comment]
@dauba-dauba yeah it should be fixed now. @tensorflow-jenkins test this please

**Comment by vrv** [comment]
Pete can you take a look?

**Comment by petewarden** [comment]
These updates look good to me, thanks @dauba-dauba!

**Pull request merged**
