### PR TITLE
Relex restrictions on `tf.foldr` and `tf.foldl`

### LINKED ISSUE #12019: foldr is too restrictive:  dimension 0 in both shapes must be equal
Using TF 1.2.0-rc1 on Ubuntu 16.04.

There are cases where `tf.foldr` should work, but is unable to because of a restriction that the first shape dimensions be identical for all list elements.  Below is a self-contained example that demonstrates the problem:

```
import tensorflow as tf
sess = tf.InteractiveSession()

def concat2(A, B):
    return tf.concat([A, B], axis=0)

A = tf.constant([[10,10]])             # A.shape => (1,2)
B = tf.constant([[20, 20], [30, 30]])  # B.shape => (2,2)

print(concat2(A, B).eval())              # => [[10, 10], [20, 20], [30, 30]]
print(tf.foldr(concat2, [A, B]).eval())  # => ERROR!
```

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #12019 where `tf.foldr` and `tf.foldl` only accpet first shape dimensions be identical for all list elements.

The issue comes from the implementation of `tf.foldr` and `tf.foldl` where the input elems is converted to tensor, then converted to tensor array:
https://github.com/tensorflow/tensorflow/blob/1e1b3d90295f9396a25b9cfd4c571f7949716182/tensorflow/python/ops/functional_ops.py#L100-L106

It is possible to bypass the conversion to tensor, and go directly to tensor array, as long as the input elems is Iterable (and pass `infer_shape=False`)

This fix is an proposal to relex the restriction on `tf.foldr` and `tf.foldl` so that a list of elements with different shapes could be passed.

This fix fixes #12019.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
Not sure about the input value of `tf.foldr` and `tf.foldl` so this PR is more about a proposal.

**Comment by mrry** [comment]
@ebrevdo: Can you take a look at the `TensorArray` manipulation here and see if it looks alright?

I'm a little dubious about these functions, because they don't appear to accept `nest`-ed components, and that seems like an equally likely feature request that might conflict with this one in annoying ways....

**Comment by ebrevdo** [comment]
It would indeed be better to extent these functions to support nested inputs and outputs in the same way that map_fn does.

**Comment by facaiy** [comment]
I found that most of ops use `ops.convert_to_tensor` to convert its inputs, however the method is really strict (same dimension, same dtype etc), and brings some inconvenience, for example #12486. Is it possible to find a more general and solid solution? say, create some more loose helper method?

**Comment by yongtang** [comment]
@mrry @ebrevdo Thanks. I will update the PR with nested input.

**Comment by yongtang** [comment]
@facaiy I guess some of the restrictions might be related to proto definition. For example, the issue #12486 you referred is the op `ShapeN` which requires the same type `T` for input:
https://github.com/tensorflow/tensorflow/blob/de46da6f748d2ea8472154bb067a361e8238568d/tensorflow/core/ops/array_ops.cc#L2096-L2102

It might be possible to pass the proto such that same type is not required. Though that would require proto update I guess.

**Comment by yongtang** [comment]
@mrry @ebrevdo I looked into the way `map_fn` handles nested structures. However, it seems that `map_fn`-like method (and `scan`) expects the same (nested) structure for all elems along dimension 0. But this is not the case raised in #12019.

In #12019, the input was
```
def concat2(A, B):
    return tf.concat([A, B], axis=0)

A = tf.constant([[10,10]])             # A.shape => (1,2)
B = tf.constant([[20, 20], [30, 30]])  # B.shape => (2,2)

print(concat2(A, B).eval())              # => [[10, 10], [20, 20], [30, 30]]
print(tf.foldr(concat2, [A, B]).eval())  # => ERROR!
```

My understanding is that the above scenario will not be compatible with nested structure as `map_fn`.

For that I am thinking we might consider:
- Update the `tf.foldl` and `tf.foldr` to support `map_fn`-like operations that allows nested structure.
- Add method `foldl` and `foldr` to `TensorArray` so that tensors with different shapes could be supported.

Let me know if the above makes sense or not. If it does, then I can update this PR for nested structure support of `tf.foldl` and `tf.foldr`, and create another PR to address #12019 with `foldl` and `foldr` to `TensorArray`.

/cc @edgimar

**Comment by ebrevdo** [comment]
I'd prefer not making any more changes to the TensorArray API.  Can all the
logic be done in tf.foldl and tf.foldr?

**Comment by martinwicke** [comment]
@yongtang any update?

**Comment by martinwicke** [comment]
@yongtang and update on this? Or did you make another PR?

**Comment by yongtang** [comment]
Sorry for the late response. I have been thinking about addressing the issue of  #12019  while at the same time limit the changes to `foldr/foldl` (vs. TensorArray) but couldn't find an easy way to get around that. For now I think it probably make sense to close this PR. I will keep the issue #12019 in mind and if I could find some way to make it work then will reopen.

Thanks all for the help and sorry for the inconvenience.

**Pull request closed without merging**
