### PR TITLE
Enable crc32c acceleration for MSVC

### PR DESCRIPTION
**Pull request by rongjiecomputer**
Use `TestCPUFeature` instead of `__builtin_cpu_supports` to dynamically detect SSE4.2 support.
This will allow us to enable crc32c acceleration for MSVC and old Apple clang.

### CODE REVIEW

**Review by meteorcloudy — DISMISSED** [review]

**Comment by rongjiecomputer** [comment]
@martinwicke @meteorcloudy Can I get CI test for this PR, https://github.com/tensorflow/tensorflow/pull/20538, https://github.com/tensorflow/tensorflow/pull/20537 and https://github.com/tensorflow/tensorflow/pull/20541? They already get LGTM-ed.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by qlzh727** [comment]
@rongjiecomputer, please take a look for the test failure and update the PR.

**Comment by rongjiecomputer** [comment]
Currently a bit busy with other matters, I will revisit this PR when I have the free time again.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment]
np, let us know.

**Pull request closed without merging**
