### PR TITLE
Remove incorrect test in batch_to_space_nd.cc and space_to_batch_nd.cc

### PR DESCRIPTION
**Pull request by stephanboner**
@tensorflow/micro

Edit: Removes incorrect tests in the prepare function after discussion with @njeffrie.

### CODE REVIEW

**Review by njeffrie — CHANGES_REQUESTED** [review]
I think this check may be incorrect overall. I've run into an issue with both >= and <=, so removing it altogether seems reasonable to me. It's also not present in the TFLite version of the kernel (I was getting too "clever", it seems).

**Comment by stephanboner** [comment]
> I think this check may be incorrect overall. I've run into an issue with both >= and <=, so removing it altogether seems reasonable to me. It's also not present in the TFLite version of the kernel (I was getting too "clever", it seems).

Ok thanks, I have removed it now from batch_to_space_nd.cc and space_to_batch_nd.cc.

**Review by njeffrie — APPROVED** [review]
Thanks!

**Comment by njeffrie** [comment]
Looks like one of the batch_so_space and space_to_batch tests is failing since it was evaluating the check we are removing. Please remove that test and try to run `bazel run tensorflow/lite/micro/kernels:space_to_batch_nd_test` and `bazel run tensorflow/lite/micro/kernels:batch_to_space_nd_test`

Sorry for missing this in the first pass of reviews.

**Comment by stephanboner** [comment]
> Looks like one of the batch_so_space and space_to_batch tests is failing since it was evaluating the check we are removing. Please remove that test and try to run `bazel run tensorflow/lite/micro/kernels:space_to_batch_nd_test` and `bazel run tensorflow/lite/micro/kernels:batch_to_space_nd_test`
> 
> Sorry for missing this in the first pass of reviews.

Done! I also removed the `// TODO(b/158102673): workaround for not having fatal test assertions.`, was that correct?

**Comment by njeffrie** [comment]
Ahh, I meant more to remove the whole second test case, without removing the equality check in the validate method. Removing the test case starting with `TF_LITE_MICRO_TEST(BatchToSpaceInvalidOutputDimensionShouldFail) {` and the corresponding test case in SpaceToBatch. Apologies for the confusion.

**Comment by stephanboner** [comment]
Sorry that it needed so many iterations - now it should be fine 🙈

**Review by njeffrie — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
