### PR TITLE
Replace `template_rule` by Skylib `expand_template`

### PR DESCRIPTION
**Pull request by Vertexwahn**
Use `expand_template` from [Skylib](https://github.com/bazelbuild/bazel-skylib) instead of custom `template_rule` implementation (Skylib implementation is unit tested and is used already at some other places at TensorFlow - we need only one function to get the job done)

### CODE REVIEW

**Comment by Vertexwahn** [comment]
@penpornk Can you please review this PR?

**Comment by Vertexwahn** [comment]
@gbaned Any chance to get this in?

**Comment by gbaned** [comment]
Hi @Vertexwahn Can you please resolve conflicts? Thank you!

**Comment by Vertexwahn** [comment]
Will split it in smaller PRs. Start here -> https://github.com/tensorflow/tensorflow/pull/58879

**Comment by gbaned** [comment]
Hi @Vertexwahn Can you please resolve conflicts? Thank you!

**Comment by Vertexwahn** [comment]
@gbaned I resolved the conflicts

**Comment by Vertexwahn** [comment]
@penpornk Any chance to get a review for this?

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
