### PR TITLE
Branch 121636618

### PR DESCRIPTION
**Pull request by zheng-xq**
Merge internal changes.

### CODE REVIEW

**Comment by zheng-xq** [comment]
@tensorflow-jenkins, test this please.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by zheng-xq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@martinwicke @vrv : ready to merge!

**Comment by caisq** [comment]
Thanks for resolving the conflicts and fixing the tests, @zheng-xq

**Pull request merged**
