### PR TITLE
Make 'import tensorflow' go faster

### PR DESCRIPTION
**Pull request by jart**
@av8ramit I recommend this cherry pick of cl/163600869 which makes `import tensorflow` go much faster (2x faster on my machine.) I would also request that it be mentioned in the 1.3 release notes.

### CODE REVIEW

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by av8ramit** [comment]
Jenkins, test this please. Rerun due to failed cmake flake.

**Comment by av8ramit** [comment]
Jenkins, test this please. Cmake flake again. Restarted some problem agents.

**Comment by av8ramit** [comment]
@caisq we can ignore the GPU tests for 1.3 right since the tag was changed from "local" to "requires-gpu"?

**Comment by caisq** [comment]
@av8ramit yes, you can ignore the errors due to the tag change in the PR testing. If there are problems (unlikely), they will be caught in the release jobs.

**Review by av8ramit — APPROVED** [review]

**Pull request merged**
