### PR TITLE
[oneDNN] Fix the collective_test python failure with tensorflow:devel container

### PR DESCRIPTION
**Pull request by sachinmuradi**
This PR fixes collective_combine_all_reduce_test_cpu and collective_test_cpu python tests, which fail when run in tensorflow:devel docker container, due to the older version of numpy.
Numpy version used in container is 1.18.5, which shows above test failures. The tests are fixed by moving the dtype check after the result_dtensor is converted to numpy array from dtensor.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the quick change!

**Comment by penpornk** [comment]
Could you please help fix the [PyLint error](https://github.com/tensorflow/tensorflow/actions/runs/3949051506/jobs/6759788729)?
```
tensorflow/dtensor/python/tests/test_util.py:278:0: C0301: Line too long (81/80) (line-too-long)
```

**Comment by sachinmuradi** [comment]
> Could you please help fix the [PyLint error](https://github.com/tensorflow/tensorflow/actions/runs/3949051506/jobs/6759788729)?
> 
> ```
> tensorflow/dtensor/python/tests/test_util.py:278:0: C0301: Line too long (81/80) (line-too-long)
> ```

@penpornk Pushed the Fix for pylint error.

**Review by penpornk — APPROVED** [review]
Thank you for the fix!

**Pull request merged**
