### PR TITLE
online add worker to  Running a distributed training session

### PR DESCRIPTION
**Pull request by ghost**
When you use distributed tensorflow for training tasks, if you start your quest, it has been running for a long time. At this point you find that the number of workers to start too little, so can not be a good convergence.

At this point, you should increase the worker online to the distributed training tasks.

example:
# On ps0.example.com:
$ python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
     --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222 \
     --job_name = ps --task_index = 0
# On ps1.example.com:
$ python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
     --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222 \
     --job_name = ps --task_index = 1
# On worker0.example.com:
$ python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
     --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222 \
     --job_name = worker --task_index = 0
# On worker1.example.com:
$ python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
     --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222 \
     --job_name = worker --task_index = 1

When you start, then, you need to increase worker2.example.com:2222, should do so:

# Write a python script:,note must call all ps servers
import tensorflow as tf
def main (_):
    with tf.Session ('grpc: //ps0.example.com:2222') as sess:
        sess.add_onlineworker (2, 'worker2.example.com: 2222')

    with tf.Session ('grpc: //ps1.example.com:2222') as sess:
        sess.add_onlineworker (2, 'worker2.example.com: 2222')

if __name__ == "__main__":
    tf.app.run ()

Then  run  this  python script:,

# On worker2.example.com:
$ python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
    --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222, \
     --worker2.example.com:2222 --job_name = worker --task_index = 2

#Then you can see worrker has started training

#If ps  nodes in the cluster restart, remember to start with the worker2.

For example ps0 restart, you must start:
# On ps0.example.com:
$ python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
    --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222, \
     --worker2.example.com:2222 --job_name = ps --task_index = 0

if  ps1 restart, you must start:
# On ps1.example.com:
$ python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
    --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222, \
     --worker2.example.com:2222 --job_name = ps --task_index = 1

Can continue to train.

### CODE REVIEW

**Comment by guoying1030** [comment]
yes,you can verify this patch

**Comment by guoying1030** [comment]
@tensorflow-jenkins ,,yes,you can verify this patch

**Comment by guoying1030** [comment]
I signed the CLA (under my primary email guowl18702995996@gmail.com).

**Review by ghost — COMMENTED** [review]
ok

**Comment by guoying1030** [comment]
@tensorflow-jenkins   yes,    anyone  can  verify this patch

**Comment by guoying1030** [comment]
sorry

**Comment by guoying1030** [comment]
@tensorflow-jenkins      Well, of course.

**Comment by guoying1030** [comment]
@mrry    why  donnot  deal  this   pull  request?

**Comment by mrry** [comment]
@guoying1030, thanks for your contribution! This is an interesting feature, and something that we would like to support eventually.

However, as @vrv mentioned on #6352, for a change of this magnitude (modifying public APIs such as the C API, the `tensorflow::Session` API, and the `MasterService` RPC interface), we would typically have a design review before starting the implementation. Having looked through the changes in this PR, we can't accept them in their current form. I'm going to close this PR for now, but we would be glad to have an open design discussion on a new issue about this feature.

**Comment by guoying1030** [comment]
@mrry      So what should I do? You can accept my code？

**Comment by guoying1030** [comment]
@mrry ,,what is PR mean?

**Pull request closed without merging**
