### PR TITLE
DiagPart Operator

### PR DESCRIPTION
**Pull request by chemelnucfin**
Implemented the get diagonal GetDiag operator #824

I believe numpy is also trying to have two different operators, but they are using diagonal and diagflat for their names.  GetDiag sounds reasonable to me, but discussion welcome.

### CODE REVIEW

**Comment by girving** [comment]
Thank you for the contribution!  I added a bunch of comments.  Let me know when I should take another look.

**Comment by chemelnucfin** [comment]
wow, thanks a lot for the detailed comments.  I'll work on the fixes and resubmit.  Since it hasn't merged yet, is it ok if I do a force push to squash the commits or leave them separately?

**Comment by girving** [comment]
A force push is good.

**Comment by chemelnucfin** [comment]
Seems like a forced push erases your line comments, unfortunately.  I have addressed your concerns earlier.  Including indentation issues, removed unnecessary template parameter, documentation, and test matrices. 

One thing I realized from looking at numpy code, shouldn't diagonals be where all the indices are the same instead of how it is now?  I mostly reversed the diag operator for this commit though.

Thanks.

**Comment by girving** [comment]
Thanks, getting much closer!  I guess add commits for now if forcing removes old comments, and once everything is good we can squash into one.

**Comment by Mistobaan** [comment]
I was thinking if `get_diag` a good name for the operation ?  reading the doc and having `diag` and `get_diag` feels a bit confusing

**Comment by girving** [comment]
@Mistobaan: I don't much like it either, but I haven't thought of something good yet.  Do you have suggestions?

**Comment by girving** [comment]
Ah, got it!  `diag_part`.

**Comment by chemelnucfin** [comment]
Diagflat in numpy is actually the "diag" operation here, (which diagflat doesn't make sense to me either).  Having diag_part might be confusing to numpy users.  I thought of using ExtractDiag for this commit and CreateDiag for the existing "diag" operation, but not sure if you wanted names that long.

**Comment by girving** [comment]
diag_part is mathematically unambiguous and matches common usage ("the diagonal part of A").  It's unfortunately that numpy is different, but `get_diag` is just as bad there.

**Comment by chemelnucfin** [comment]
Ok, give me a few minutes to finish working on the rintop pull request and
I'll change the name in this one.

**Comment by chemelnucfin** [comment]
Thanks for the time spent reviewing the code!  Hopefully this is good for now.

Should I add offset in the future in both diag and diag_part?

**Comment by girving** [comment]
Looks good, thank you!  @vrv: How does one run tests and get this merged?

**Comment by girving** [comment]
Yep, an offset would be a reasonable addition for a future CL, but it has the unfortunate issue that it would ideally be an `input` rather than an `attr`, and adding new inputs is awkward to do in a backwards compatible way.

Also, before we merge (but perhaps after the tests?) we should squash this into one commit.  Thanks for keeping it separated for now to make it easier to incrementally review.

**Comment by chemelnucfin** [comment]
@girving I think you just say "jenkins, test this please" and it will trigger the tests.

So, should I work on offset for this first before we merge?  

Also, for both of these operations should there be a value to indicate the diagonal that is created and extracted?
For example:
dim=0 => A[i, i, i, i, i, i]
dim=1 => A[i, j, i, j, i, j]
dim=2 => A[i, j, k, i, j, k]
etc.

**Comment by vrv** [comment]
only admins can trigger it :)

@tensorflow-jenkins: test this please

**Comment by girving** [comment]
Let's leave generalizations to a separate CL.  The symmetry of your existing change is good, since it doesn't change the existing op and adds it's one sided inverse.

**Comment by chemelnucfin** [comment]
I just squashed the commits.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
Merged

**Pull request closed without merging**
