### PR TITLE
add identity_initializer

### PR DESCRIPTION
**Pull request by carpedm20**
Add identity initializer to initiate a variable with custom values.

### CODE REVIEW

**Comment by vrv** [comment]
A test for this might be nice.

**Comment by carpedm20** [comment]
@vrv I added a test case for `identity_initializer` but I think `identity_initializer` should not have additional shape variable but we should by pass https://github.com/carpedm20/tensorflow/blob/master/tensorflow/python/ops/variable_scope.py#L110. However, I think it is not possible to by pass this without adding an additional parameter because return value of `identity_initializer` is only a `_initializer` method. Is there any suggestion for this or do you think requesting `shape` is necessary for `identity_initializer`?

**Comment by vrv** [comment]
@mrry and @lukaszkaiser might have better answers for you here, though most of us are on vacation for the next few days / weeks.

**Comment by girving** [comment]
How would this be used?  If you already know the whole value including shape, I thought you could just pass the value directly.

**Comment by lukaszkaiser** [comment]
I'm planning to work on adding an option to just pass a value instead of an initializer in tf.get_variable. Maybe this initializer will not be needed then. Currently you can use "lamda x: x" as initializer, but we should have a better way soon.

**Comment by lukaszkaiser** [comment]
I've just made a CL that allows to use a Tensor as initializer in get_variable (should appear soon on git). I hope this closes this request, but feel free to re-open if needed.

**Comment by vrv** [comment]
@lukaszkaiser: let's only close issues once they are publicly available

**Pull request closed without merging**
