### PR TITLE
Introducing BatchedNMS and CombinedNMS GPU ops

### PR DESCRIPTION
**Pull request by samikama**
This PR adds BatchedNMS op, which uses significantly less memory than GPUNMSV[234] ops at the expense of some performance for very small batch sizes. A GPU implementation of CombinedNMS op using BatchedNMS kernels is also included. GPU CombinedNMS improve SSD images/s about 50% with respect to multi-class CPU NMS ops and about 4x vs CPU CombinedNMS implementation

### CODE REVIEW

**Comment by aaroey** [comment]
@sanjoy could you help to take a look? Thanks.

**Comment by samikama** [comment]
@pkanwar23 and @aaroey please ask your internal teams to give these ops a try.

**Comment by gbaned** [comment]
@sanjoy, @chsigg Can you please take a look at this PR? Thanks!

**Comment by gbaned** [comment]
@samikama Can you please check failed build errors? Thanks!

**Comment by samikama** [comment]
@gbaned build errors are unrelated with this PR. @sanjoy Will there be a review of this?

**Comment by samikama** [comment]
@gbaned I merged with current master to fix the compilation issues. Earlier issues were because master at the time of PR was not compiling.

**Comment by samikama** [comment]
@googlebot I fixed it.

**Comment by gbaned** [comment]
@samikama  please sign CLA. Thanks!

**Comment by gbaned** [comment]
@samikama Can you please sign CLA and resolve conflicts? Thanks!

**Comment by samikama** [comment]
@cliffwoolley CLAs from NVIDIA side are missing. Do you want me to close this?

**Comment by cliffwoolley** [comment]
I see this was auto-closed because of the CLA mismatches; FYI we are still looking into how to move forward with this one and will open a new PR to make the CLA bots happy if necessary as soon as we have a plan solidified.  /cc @reedwm @nluehr

**Pull request closed without merging**
