### PR TITLE
Add missing arguments.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
- For `docs.py`, add `name` for exception message generation.
- For `rnn_cell.py` and `rnn_test.py`, add `scope=None` for inheritance.

### CODE REVIEW

**Comment by josh11b** [comment]
Jenkins, test this please.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
@ebrevdo: I assume adding 'scope' is the right change to the API, can you confirm?

**Comment by ebrevdo** [comment]
Can you justify the need for passing scope to the __call__ interface?

**Comment by dongjoon-hyun** [comment]
I know that it's not required or used in those functions. I just tried to make the derived classes of `RNNCell` have the same format literally. If you think it's redundant, I will remove the changes related *call*.

**Comment by ebrevdo** [comment]
Ah sorry, I see now.  Changes LGTM.

**Comment by dongjoon-hyun** [comment]
Thank you for reviewing, @ebrevdo !

**Comment by bhack** [comment]
@vrv In the majority of the cases (like this one) seems that your are following (this merging process)[http://stackoverflow.com/questions/23015168/how-to-close-a-github-pull-request-with-a-commit-comment]. This alter the github pulse and other stats. Is there a way in your process to let this PRs result as merged?

**Comment by vrv** [comment]
Sometimes it appears as merged, sometimes closed.  I'm not sure what I have to do to tell github it's been merged.  Help would be appreciated

**Pull request closed without merging**
