### PR TITLE
Add \r and \n to DEFAULT_STRIP_REGEX

### PR DESCRIPTION
**Pull request by dewball345**
I worked with text vectorization and I thought that \r and \n needed to be cropped off.

### CODE REVIEW

**Comment by dewball345** [comment]
@googlebot I signed it!

**Comment by mattdangerw** [comment]
Can you explain more of what's going wrong for you here?

Whitespace should be removed during the token splitting step, which comes after the standardization step where this regex is applied. You can also always pass custom callables for `standardize` or `split` if you want custom behavior. But as a default, I do not think we the standardization step to strip whitespace.

**Review by deeb02 — COMMENTED** [review]
Thanks, Matt!

**Comment by dewball345** [comment]
> Can you explain more of what's going wrong for you here?
> 
> Whitespace should be removed during the token splitting step, which comes after the standardization step where this regex is applied. You can also always pass custom callables for `standardize` or `split` if you want custom behavior. But as a default, I do not think we the standardization step to strip whitespace.

A lot of the data that I had had \n and \r, and I think that it is probably a common occurrence in text data, which is why I thought it should be part of the default punctuation removal part. I kind of think it is redundant to have a callable that basically does the exact same thing as the default program with just these two characters, right?

**Comment by mattdangerw** [comment]
A minimal code example might help us get to the bottom of this!

To be clear `\n` and `\r` should already be stripped, along with spaces, tabs, and other whitespace, just during the "splitting" step, not the "standardization" step. You won't see them in a regex in this file, as we call into a standard tf utility for whitespace splitting. Removing whitespace in the standardization step would be unwanted, as it could actually end up fusing separate tokens across whitespace.

Here's an example of how things work today.

```
text_vectorization = TextVectorization(
    output_mode="int",
)
text_vectorization.adapt(["foo\r\nbar\nbaz   foo"])
text_vectorization.get_vocabulary()
> ['', '[UNK]', 'foo', 'baz', 'bar']
text_vectorization(["foo\r\nbar\nbaz   foo"])
> <tf.Tensor: shape=(1, 4), dtype=int64, numpy=array([[2, 4, 3, 2]])>
```

I believe with your change we could end up getting a vocabulary of "foobarbaz foo", which is not what we want in this case.

**Comment by dewball345** [comment]
Oh! ok, I see. 

> A minimal code example might help us get to the bottom of this!
> 
> To be clear `\n` and `\r` should already be stripped, along with spaces, tabs, and other whitespace, just during the "splitting" step, not the "standardization" step. You won't see them in a regex in this file, as we call into a standard tf utility for whitespace splitting. Removing whitespace in the standardization step would be unwanted, as it could actually end up fusing separate tokens across whitespace.
> 
> Here's an example of how things work today.
> 
> ```
> text_vectorization = TextVectorization()
> text_vectorization.adapt(["foo\r\nbar\nbaz   foo"])
> text_vectorization.get_vocabulary()
> > ['', '[UNK]', 'foo', 'baz', 'bar']
> text_vectorization(["foo\r\nbar\nbaz   foo"])
> > <tf.Tensor: shape=(1, 4), dtype=int64, numpy=array([[2, 4, 3, 2]])>
> ```
> 
> I believe with your change we could end up getting a vocabulary of "foobarbaz foo", which is not what we want in this case.

Ok, I see. That makes sense to split it then. I think I incorrectly assumed that it wouldn't happen just by looking at the regex. That all seems good, then!

**Pull request closed without merging**
