### PR TITLE
[ROCm] rocFFT integration logic in ROCm StreamExecutor

### PR DESCRIPTION
**Pull request by whchung**
Please focus on the content in commit https://github.com/tensorflow/tensorflow/pull/20712/commits/1a34db1da952351788da04a8a8161888647d8687

The pull request contains rocFFT integration logic for ROCm platform.

There are additional changes included in this pull request which are covered
in other pull requests for ROCm. In order to ensure each pull request is
self-contained and builds / runs on both CUDA & ROCm platform they are still
included here.

- #20277 : bazel changes and continuous integration logic
- #20675 : StreamExecutor interface change
- #20709 : barebone ROCm StreamExecutor implementation

Authors:

- Jack Chung: jack.chung@amd.com
- Johannes M Dieterich: Johannes.Dieterich@amd.com

### CODE REVIEW

**Comment by whchung** [comment]
@jlebar This is the subsequent PR after #20709 to cover integration logic for FFT on ROCm StreamExecutor implementation

**Comment by jlebar** [comment]
@chsigg volunteered to help with this.  Christian, you can see the full set of patches at https://github.com/tensorflow/tensorflow/pulls/whchung.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @jlebar, @chsigg: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
It has been 20 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by qlzh727** [comment]
@whchung, please rebase and resolve the merge conflict here if this PR is still alive.

**Comment by deven-amd** [comment]
@qlzh727

This PR is still active. As with the other ROCm related PRs, we are waiting for PR #20277 to get merged, since that is a per-requisite to getting this PR merged. Once that PR is merged, we expect to rebase and resolve the merge conflicts.

Thanks

**Comment by tensorflowbutler** [comment]
It has been 28 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
