### PR TITLE
Add licenses for neon2sse and OpenGL in TF Lite CMake build.

### LINKED ISSUE #55741: TF Lite (CMake): neon2sse missing license file location
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.0

### Custom Code

No

### OS Platform and Distribution

Linux

### Mobile device

_No response_

### Python version

3.8

### Bazel version

N/A

### GCC/Compiler version

N/A

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

```shell
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/cmake/modules/OverridableFetchContent.cmake tracks licenses for each dependency of an imported module of TensorFlow Lite. This allows projects using TF Lite to build an aggregate license file for redistribution (e.g https://github.com/google-research/falken/blob/e15aea40aec08e1e5858905e7dd6de7da2e4a1ec/sdk/cpp/CMakeLists.txt#L196 )

https://github.com/tensorflow/tensorflow/commit/1485091a6a64989a01cd2db76d53fe71653ae666 caused a regression in TF Lite's CMake dependencies by manually specifying a download URL where the license URL can no longer be inferred by `OverridableFetchContent.cmake`.

I'm happy to provide a fix that:
* Specifies the license URL and downloaded location.
* Enables license file checking in the TF Lite CMake project.
```

### Standalone code to reproduce the issue

```shell
Add `set(OVERRIDABLE_FETCH_CONTENT_LICENSE_CHECK ON)` near the top of `tensorflow/lite/CMakeLists.txt`, configure the project and wait for configuration to fail due to neon2sse missing a license.
```

### Relevant log output

```shell
$ cd tensorflow/lite
$ mkdir build
$ cd build
$ cmake ..
# lots of output
- Could NOT find CLANG_FORMAT: Found unsuitable version "0.0", but required is exact version "9" (found CLANG_FORMAT_EXECUTABLE-NOTFOUND)
--
-- Configured Eigen 3.4.90
--
-- Performing Test FARMHASH_HAS_BUILTIN_EXPECT
-- Performing Test FARMHASH_HAS_BUILTIN_EXPECT - Success
-- Looking for strtof_l
-- Looking for strtof_l - found
-- Looking for strtoull_l
-- Looking for strtoull_l - found
CMake Error at tools/cmake/modules/OverridableFetchContent.cmake:571 (message):
  Required license URL not found for neon2sse
Call Stack (most recent call first):
  tools/cmake/modules/neon2sse.cmake:37 (OverridableFetchContent_Populate)
  tools/cmake/modules/Findneon2sse.cmake:18 (include)
  CMakeLists.txt:148 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/stewart/src/tensorflow/tensorflow/lite/build/CMakeFiles/CMakeOutput.log".
See also "/home/stewart/src/tensorflow/tensorflow/lite/build/CMakeFiles/CMakeError.log".
```
</details>

### PR DESCRIPTION
**Pull request by stewartmiles**
Fixes #55741

### CODE REVIEW

**Comment by stewartmiles** [comment]
Hi, it has been a couple of weeks any progress on reviewing this?

**Comment by gbaned** [comment]
Hi @JunyoungLim Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @JunyoungLim Can you please review this PR ? Thank you!

**Comment by stewartmiles** [comment]
@JunyoungLim thanks for your help on https://github.com/tensorflow/tensorflow/pull/55746 could you do something similar for this patch?

**Comment by stewartmiles** [comment]
@gbaned and @JunyoungLim any chance you could review this / merge this patch into g3 to work around the AMD ROCm presubmit flake.

**Comment by gbaned** [comment]
Hi @JunyoungLim Can you please review this PR ? Thank you!

**Comment by stewartmiles** [comment]
Ping @gbaned and @JunyoungLim

**Comment by gbaned** [comment]
@stewartmiles Can you please resolve conflicts? Thank you!

**Comment by stewartmiles** [comment]
Hey @gbaned I've rebased and resolved conflicts.

**Comment by stewartmiles** [comment]
Ping again, is this a candidate for the longest open pull request? We're now coming up to 6 months.

**Comment by stewartmiles** [comment]
Oh I would like to remind folks that the AMD ROCm build is perpetually broken and nothing to do with this pull. i.e this is the error message:

```
E: Package 'python-pip' has no installation candidate

The command '/bin/sh -c apt-get update --allow-insecure-repositories && DEBIAN_FRONTEND=noninteractive apt-get install -y   build-essential   bsdmainutils   clang-6.0   clang-format-6.0   clang-tidy-6.0   cmake   cmake-qt-gui   ssh   curl   apt-utils   pkg-config   g++-multilib   git   kmod   libunwind-dev   libfftw3-dev   libelf-dev   libncurses5-dev   libpthread-stubs0-dev   vim   gfortran   libboost-program-options-dev   libssl-dev   libboost-dev   libboost-system-dev   libboost-filesystem-dev   rpm   libnuma-dev   pciutils   virtualenv   python-pip   libxml2   libxml2-dev   wget &&   apt-get clean &&   rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

ERROR: docker build failed. Dockerfile is at /home/jenkins/workspace/ROCm-Community-CI-Build_PR-55743/tensorflow/tools/ci_build/Dockerfile.rocm
```

**Comment by stewartmiles** [comment]
@gbaned @JunyoungLim hello again, I'm still waiting for the AMD ROCm build to be fixed - it isn't due to this change - and this commit to be merged. As I've mentioned before I don't mind you taking this commit and manually patching in g3 then I can just close this out when it is auto merged to this repo.

**Comment by stewartmiles** [comment]
@terryheo @gbaned @JunyoungLim I'm pinging this pull request again, any chance this could be merged before the end of the year?

**Review by mihaimaruseac — APPROVED** [review]

**Comment by stewartmiles** [comment]
Thanks @mihaimaruseac as I mentioned in this thread it looks like the AMD ROCm presubmit has been perpetually failing and not due to this pull, so unless someone forge merges this is going to be stuck. With my last pull for TF-Lite the folks just patched the change in g3/third_party and let that roll out. If that's the easiest way to merge, I'm fine with it.

**Comment by mihaimaruseac** [comment]
TF-life-of-PR


The above image displays the life of a PR. See also https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#how-to-become-a-contributor-and-submit-your-own-code for another view of the same process.

Basically, this PR has been blocked because there was no approving review to it. The AMD Rocm build is not required and will be ignored when merging the PR if all required external and internal checks pass.

**Review by terryheo — APPROVED** [review]

**Comment by stewartmiles** [comment]
Hi everyone, thanks for approving but it appears merge is still blocked. I can't see the copybara failure - of course - and the AMD ROCm build - which has been failing forever - is still broken.

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by stewartmiles** [comment]
image

😢

**Comment by stewartmiles** [comment]
Any chance someone could let me know what copybara is missing? Of course I can't see critique to know what is failing anymore 😄

**Comment by gbaned** [comment]
> Any chance someone could let me know what copybara is missing? Of course I can't see critique to know what is failing anymore 😄

Hi @stewartmiles This PR is giving internal checks failures. We will let you know if anything needed from your side. Thank you!

**Comment by terryheo** [comment]
I'm seeing the following build error.

```
[100%] Built target pthreadpool
-- Downloading FXdiv to /tmpfs/tensor_flow/tflite_build/FXdiv-source (define FXDIV_SOURCE_DIR to avoid it)
-- Configuring done
-- Generating done
-- Build files have been written to: /tmpfs/tensor_flow/tflite_build/FXdiv-download
Scanning dependencies of target fxdiv
[ 11%] Creating directories for 'fxdiv'
[ 22%] Performing download step (git clone) for 'fxdiv'
Cloning into 'FXdiv-source'...
Already on 'master'
Your branch is up to date with 'origin/master'.
[ 33%] No patch step for 'fxdiv'
[ 44%] Performing update step for 'fxdiv'
Current branch master is up to date.
[ 55%] No configure step for 'fxdiv'
[ 66%] No build step for 'fxdiv'
[ 77%] No install step for 'fxdiv'
[ 88%] No test step for 'fxdiv'
[100%] Completed 'fxdiv'
[100%] Built target fxdiv
CMake Error at [tools/cmake/modules/OverridableFetchContent.cmake:566](https://cs.corp.google.com/piper///depot/google3/tools/cmake/modules/OverridableFetchContent.cmake?l=566&cl=504577264) (message):
  Required license file not found for opengl_headers
Call Stack (most recent call first):
  [tools/cmake/modules/opengl_headers.cmake:35](https://cs.corp.google.com/piper///depot/google3/tools/cmake/modules/opengl_headers.cmake?l=35&cl=504577264) (OverridableFetchContent_Populate)
  [tools/cmake/modules/Findopengl_headers.cmake:16](https://cs.corp.google.com/piper///depot/google3/tools/cmake/modules/Findopengl_headers.cmake?l=16&cl=504577264) (include)
  CMakeLists.txt:262 (find_package)
```

**Comment by stewartmiles** [comment]
Hey @terryheo https://github.com/tensorflow/tensorflow/blob/f5f5be34449bbaa7210522e8e0e5f8e602f12bec/tensorflow/lite/tools/cmake/modules/opengl_headers.cmake#L22 needs to be updated with a reference to the license file relative to the downloaded archive / cloned repo or license URL. I cloned https://github.com/KhronosGroup/OpenGL-Registry and it looks like they don't have a license file embedded in there but the headers pulled in by opengl_headers.cmake adhere to MIT and Apache licenses:

```
$ find api/ -type f -name '*.h' | xargs grep 'License-Identifier:' | sed 's/.*://' | sort -u
 Apache-2.0
 MIT
```

So I think - probably best to check with the open source group - that pointing `LICENSE_URL` at https://www.apache.org/licenses/LICENSE-2.0.txt is probably reasonable since it's more restrictive than MIT. https://github.com/tensorflow/tensorflow/blob/f5f5be34449bbaa7210522e8e0e5f8e602f12bec/tensorflow/lite/tools/cmake/modules/fft2d.cmake#L29 is an example of using `LICENSE_URL`.

**Comment by stewartmiles** [comment]
I can update this commit with various license files / URLs if you want .. lmk

**Comment by stewartmiles** [comment]
Oh it looks like quite a few dependencies have been added, I'll take a pass now and update the license pointers.

**Comment by stewartmiles** [comment]
Ok I've added a license for OpenGL headers. Interesting the OpenCL repo contains a LICENSE file so it _just works_(tm).

**Review by terryheo — APPROVED** [review]
LGTM

**Comment by terryheo** [comment]
This PR still has an error.

```
CMake Error at [tools/cmake/modules/OverridableFetchContent.cmake:566](https://cs.corp.google.com/piper///depot/google3/tools/cmake/modules/OverridableFetchContent.cmake?l=566&cl=507511477) (message):
  Required license file not found for opengl_headers
Call Stack (most recent call first):
  [tools/cmake/modules/opengl_headers.cmake:36](https://cs.corp.google.com/piper///depot/google3/tools/cmake/modules/opengl_headers.cmake?l=36&cl=507511477) (OverridableFetchContent_Populate)
  [tools/cmake/modules/Findopengl_headers.cmake:16](https://cs.corp.google.com/piper///depot/google3/tools/cmake/modules/Findopengl_headers.cmake?l=16&cl=507511477) (include)
  CMakeLists.txt:262 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmpfs/tensor_flow/tflite_build/CMakeFiles/CMakeOutput.log".
See also "/tmpfs/tensor_flow/tflite_build/CMakeFiles/CMakeError.log".
+ finish
+ [[ -n 18992 ]]
+ echo 'Stopping portserver...'
Stopping portserver...
+ kill 18992
```

**Comment by stewartmiles** [comment]
@terryheo could you describe how you're reproducing the failure (platform etc.)? On my Linux box this works just fine:

```
$ cd ~/src/tensorflow/tensorflow/lite
$ git log --oneline | head
1873bc26ccd Add licenses for neon2sse and OpenGL in TF Lite CMake build.
90f612774e6 [XLA/GPU] Plug in a basic latency estimator for GPU - Assume latency is high between async-start/done pairs - Assume custom calls for cuBLAS, cuDNN and softmax are high cost, else medium cost. - Enable latency hiding for collective permute
48d134703cc Update TFRT dependency to use revision http://github.com/tensorflow/runtime/commit/6b7aa683a10b43f263565b7aa71702f101f50d3a.
902a004faff [XLA:CPU] Fix getLoopIteratorTypes for thlo.reverse
94abc100f53 Add copybara config tests.
47cd1a63936 [XLA:GPU] Disable padding for triton-based matmuls.
9da8616b2ea Implement functional<->regional transformation for CaseOp and CaseRegionOp
8a8807021fd #tf-data-service Distributed snapshot supports infinite choice dataset.
5d725681875 #tf-data-service Add more details to `rename` error message.
905aa5fbb0c Disable all sanitizers for distributed snapshot fault tolerance tests.
$ ( mkdir cmake_build && cd cmake_build && cmake .. && cmake --build . -j && echo success )
# Lots of output...
success
```

**Comment by gbaned** [comment]
Hi @terryheo Can you please assist on above [comments](https://github.com/tensorflow/tensorflow/pull/55743#issuecomment-1419663269) from @stewartmiles. Thank you!

**Comment by stewartmiles** [comment]
Thanks @terryheo of course I wasn't seeing the problem as GPU support is disabled by default. It looks like I forgot to add support for downloading a license from a URL if the file isn't in the cloned repository / archive. I'll post an update with the fix shortly.

**Comment by stewartmiles** [comment]
I configured and built using:
```bash
# cd into tensorflow source dir
# create build dir
mkdir build
cd build
# configure
cmake ../tensorflow/lite -DTFLITE_ENABLE_GPU=ON -DTFLITE_KERNEL_TEST=ON 2>&1 | \
    tee cmake_tflite_configure.log
# build
cmake --build . -j 2>&1 | tee cmake_tflite_build.log
```

The output is in:
* [cmake_tflite_configure.log](https://github.com/tensorflow/tensorflow/files/11227094/cmake_tflite_configure.log)
* 
[cmake_tflite_build.log](https://github.com/tensorflow/tensorflow/files/11227148/cmake_tflite_build.log)

Unrelated to this change the build fails due to a problem in `tensorflow/tensorflow/lite/kernels/test_util_test.cc`:

```
In file included from /home/stewart/src/tensorflow/build/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h:39,
                 from /home/stewart/src/tensorflow/build/googletest/googletest/include/gtest/gtest-death-test.h:41,
                 from /home/stewart/src/tensorflow/build/googletest/googletest/include/gtest/gtest.h:64,
                 from /home/stewart/src/tensorflow/build/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:47,
                 from /home/stewart/src/tensorflow/build/googletest/googlemock/include/gmock/gmock-actions.h:51,
                 from /home/stewart/src/tensorflow/build/googletest/googlemock/include/gmock/gmock.h:59,
                 from /home/stewart/src/tensorflow/tensorflow/lite/kernels/test_util.h:39,
                 from /home/stewart/src/tensorflow/tensorflow/lite/kernels/test_util_test.cc:15:
/home/stewart/src/tensorflow/build/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘bool testing::internal::AnyEq::operator()(const A&, const B&) const [with A = TfLiteIntArray*; B = tflite::DimsAreMatcher]’:
/home/stewart/src/tensorflow/build/googletest/googletest/include/gtest/gtest-matchers.h:549:18:   required from ‘bool testing::internal::ComparisonBase<D, Rhs, Op>::Impl<Lhs, <template-parameter-2-2> >::MatchAndExplain(Lhs, testing::MatchResultListener*) const [with Lhs = TfLiteIntArray* const&; <template-parameter-2-2> = tflite::DimsAreMatcher; D = testing::internal::EqMatcher<tflite::DimsAreMatcher>; Rhs = tflite::DimsAreMatcher; Op = testing::internal::AnyEq]’
/home/stewart/src/tensorflow/build/googletest/googletest/include/gtest/gtest-matchers.h:547:10:   required from here
/home/stewart/src/tensorflow/build/googletest/googletest/include/gtest/gtest-matchers.h:211:60: error: no match for ‘operator==’ (operand types are ‘TfLiteIntArray* const’ and ‘const tflite::DimsAreMatcher’)
  211 |   bool operator()(const A& a, const B& b) const { return a == b; }
      |                                                          ~~^~~~
In file included from /home/stewart/src/tensorflow/build/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:47,
                 from /home/stewart/src/tensorflow/build/googletest/googlemock/include/gmock/gmock-actions.h:51,
                 from /home/stewart/src/tensorflow/build/googletest/googlemock/include/gmock/gmock.h:59,
                 from /home/stewart/src/tensorflow/tensorflow/lite/kernels/test_util.h:39,
                 from /home/stewart/src/tensorflow/tensorflow/lite/kernels/test_util_test.cc:15:
/home/stewart/src/tensorflow/build/googletest/googletest/include/gtest/gtest.h:1518:13: note: candidate: ‘bool testing::internal::operator==(testing::internal::faketype, testing::internal::faketype)’
 1518 | inline bool operator==(faketype, faketype) { return true; }
... the errors go on ...
```

**Comment by stewartmiles** [comment]
@gbaned and @terryheo any chance someone could take another look?

**Review by terryheo — COMMENTED** [review]
I wonder if opencl_headers, vulkan_headers don't require the license.

**Comment by stewartmiles** [comment]
@terryheo they don't:

Per https://github.com/tensorflow/tensorflow/blob/60c0bb9d5332a806d18da043a77a3e99eb0e504e/tensorflow/lite/tools/cmake/modules/opencl_headers.cmake#L24

See this has https://github.com/KhronosGroup/OpenCL-Headers/blob/main/LICENSE which is picked up as the license.

And per https://github.com/tensorflow/tensorflow/blob/60c0bb9d5332a806d18da043a77a3e99eb0e504e/tensorflow/lite/tools/cmake/modules/vulkan_headers.cmake#L24

has https://github.com/KhronosGroup/Vulkan-Headers/blob/main/LICENSE.txt which is picked up as the license.

The auto-license file detection logic is:
https://github.com/tensorflow/tensorflow/blob/60c0bb9d5332a806d18da043a77a3e99eb0e504e/tensorflow/lite/tools/cmake/modules/OverridableFetchContent.cmake#L539-L545

**Review by terryheo — APPROVED** [review]
That's good to know. Thanks!

**Comment by stewartmiles** [comment]
Woo it's in! Thanks!

**Pull request merged**
