### PR TITLE
Branch 170584354

### PR DESCRIPTION
**Pull request by sb2nov**

### CODE REVIEW

**Review by frankchn — APPROVED** [review]

**Comment by sb2nov** [comment]
@gunan is there a way to trigger the CLA bot ?

**Comment by sb2nov** [comment]
I signed it!!

**Comment by frankchn** [comment]
@sb2nov I think there is probably some configuration issue with your account re: CLAs? I don't have that issue when I submit changes -- the CLA bot accepts immediately without me asking.

**Comment by sb2nov** [comment]
It was fine for other PRs so I don't think that is the issue. Also it didn't ever post the message about asking for CLA on this PR so might be something else.

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by sb2nov** [comment]
@martinwicke the CLA bot got stuck on this PR. Is it possible to merge this without that.

**Comment by gunan** [comment]
@sb2nov could you try commenting `I signed it!` with single exclamation mark.
What is curious is CLA bot never reported anything on this PR.

**Comment by sb2nov** [comment]
I signed it!

**Comment by gunan** [comment]
This is really curious. Let us wait for tomorrow, I can manually verify CLAs, and override CLAbot tomorrow morning if we cannot find a way to get it to work.

**Comment by sb2nov** [comment]
@gunan the CLA bot is timing out in the check which is causing this issue. I think we can manually merge this as all the commits are from Googlers.

A good future lesson to make merges smaller and resolving broken syncs faster.

**Comment by sb2nov** [comment]
Got manual approval on https://github.com/tensorflow/tensorflow/pull/13435 so closing this.

**Pull request closed without merging**
