### PR TITLE
Fixed assert_shapes broken code in documentation

### PR DESCRIPTION
**Pull request by sPredictorX1708**
Issue #33974

### CODE REVIEW

**Comment by dubesar** [comment]
@googlebot I signed it!

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
Cool, thanks I didn't know about this function.

If you're updating code samples please use `doctest` format, this is tested not to ensure examples aren't broken again:

https://docs.python.org/3/library/doctest.html

You'll need to add a few lines to create these tensors.

**Comment by dubesar** [comment]
@MarkDaoust Can I know what all additional changes have to be done?

**Comment by MarkDaoust** [comment]
Hi I did the reformatting to show you how for your next PR.

But what Email address did you sign the CLA with? 

Your commits are made with : "38752758+dubesar@users.noreply.github.com"

**Comment by dubesar** [comment]
@MarkDaoust  yes I have signed the cla with dubeysarvesh5525@gmail.com

**Comment by dubesar** [comment]
@MarkDaoust I have fixed the email problem as the '38752758+dubesar@users.noreply.github.com' was shown as I had kept the email address private.

**Comment by MarkDaoust** [comment]
Cool, for any future contributions be sure to configure your git/github so that that email address gets set as the author.

**Review by MarkDaoust — APPROVED** [review]

**Comment by dubesar** [comment]
@MarkDaoust Do I have to make more changes as some of the CL checks are failing?

**Comment by MarkDaoust** [comment]
I'm not sure, it looks like the buildre failed, not this code, all try pulling it.

**Comment by dubesar** [comment]
@MarkDaoust  Yes, I observed all the pull request is failing.

**Comment by mihaimaruseac** [comment]
Please make the PR against `master` branch, not `r2.0`.

**Pull request closed without merging**
