### PR TITLE
Pass required input_length to batch_sequences_with_states() in example

### PR DESCRIPTION
**Pull request by raviqqe**

### CODE REVIEW

**Comment by ebrevdo** [comment]
Thanks!  Can you make the example:

length = tf.shape(sequences['inputs'])[0]

Or something of the sort?

**Comment by raviqqe** [comment]
Like this?

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by ebrevdo** [comment]
Yes, thanks!  Lgtm.

**Review by vrv — APPROVED** [review]
Approval based on ebrevdo's approval

**Pull request merged**
