### PR TITLE
[INTEL MKL] Remove unnecessary MKL  build macros and bug fixes

### PR DESCRIPTION
**Pull request by gzmkl**
Remove the following MKL build options (and usage of related MACRO's):

1. ENABLE_INTEL_MKL_BFLOAT16  (treat as "TRUE" value)
2. INTEL_MKL_DNN_ONLY              (treat same as "INTEL_MKL")
3. ENABLE_MKLDNN_V1                 (DNN 0.x code cleanup; cleanup was overwritten by later PRs).

#3 fixes some bugs caused by the merge of final DNN 0.x code cleanup PR (https://github.com/tensorflow/tensorflow/pull/46370/), most MKL unit test failure.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
This looks so much cleaner. Thank you very much!

This PR will take a while to merge. I might try submitting a separate commit to fix `mkl_dequantize_op.cc` first so the CI can stop failing.

**Comment by penpornk** [comment]
The fix was in cbaadc39c48f282f09c3ab92146ccbe62e599a11, but the CI still have some other failures (about benchmarks). 
Could you please resync to master to resolve the merge conflict? Thank you!

**Comment by gzmkl** [comment]
> This looks so much cleaner. Thank you very much!
> 
> This PR will take a while to merge. I might try submitting a separate commit to fix `mkl_dequantize_op.cc` first so the CI can stop failing.

Thank you Penporn! I have just addressed the merge conflicts

**Comment by gzmkl** [comment]
For CI  failures (about benchmarks, there is another PR (submitted by my teammate).

**Review by penpornk — APPROVED** [review]
Thank you for the update! I'll look for that other fixing PR. :)

**Pull request merged**
