### PR TITLE
Fixes #34194 - tf.size() documentation

### LINKED ISSUE #34194: tf.size() has no documentation
https://www.tensorflow.org/api_docs/python/tf/size

Example: "Returns the number of elements in the tensor. It equals the length of the flattened tensor."

### PR DESCRIPTION
**Pull request by copperwiring**
Copied definition from v1 size API reference

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Please open PR against `master` branch. We don't update release branches (`r...`) after the final release of the corresponding TF version (i.e., we won't update `r2.1` after TF2.1 is released).

The only time release branches are updated is when we make a patch release to fix a security vulnerability. As that requires expediency, we only accept minimal changes even then.

**Comment by copperwiring** [comment]
Thanks @mihaimaruseac I will send a new PR in some time. Appreciate your detailed feedback!

**Comment by mihaimaruseac** [comment]
Please add me as reviewer to expedite process

**Comment by copperwiring** [comment]
@mihaimaruseac I have sent a PR for master branch here: https://github.com/tensorflow/tensorflow/pull/34389 but I am unable to see the option to add you as a reviewer. Could you help me here, please?

**Pull request closed without merging**
