### PR TITLE
Removed legacy rnn constructors

### PR DESCRIPTION
**Pull request by terrytangyuan**
These are deprecated. But someone still needs to check whether they are being used internally.

### CODE REVIEW

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by terrytangyuan** [comment]
@caisq FYI It's actually usually auto-triggered for me since I am in TF Github org. Thanks though!

**Review by martinwicke — CHANGES_REQUESTED** [review]
Also remove _get_dropout_and_num_units

**Comment by martinwicke** [comment]
Note: this can go in after 154336469.

**Comment by terrytangyuan** [comment]
Done! @martinwicke

**Review by martinwicke — APPROVED** [review]

**Pull request merged**
