### PR TITLE
Branch 140088698

### PR DESCRIPTION
**Pull request by caisq**
Manually resolved conflicts in:
tensorflow/contrib/learn/python/learn/datasets/base.py
tensorflow/contrib/training/BUILD
tensorflow/core/kernels/cwise_op_floor_div.cc
tensorflow/python/platform/test.py

### CODE REVIEW

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
The issue related to the extraneous file in third_party/llvm is now resolved. However, the windows cmake build shows another error:
```
18:58:53     import tensorflow as tf
18:58:53   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
18:58:53     from tensorflow.python import *
18:58:53   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 85, in <module>
18:58:53     from tensorflow.python import layers
18:58:53 ImportError: cannot import name 'layers'
```

Any thoughts?

**Comment by caisq** [comment]
@tensorflow-jenkins test this please.

**Comment by caisq** [comment]
@aselle, @lukeiwanski, there were some conflicts in tensorflow/core/kernels/cwise_op_floor_div.cc that I resolved as a part of this push.

Is it possible that CL/139922734 seems somehow interacted with PR https://github.com/tensorflow/tensorflow/commit/6a0263970dd05edfa080931cc0d2c202dfba1976 to cause the test failures seen at: 
https://ci.tensorflow.org/job/tensorflow-pull-requests-gpu/2740/consoleFull

Example error message:
```
InvalidArgumentError (see above for traceback): Multiple OpKernel registrations match NodeDef 'FloorDiv = FloorDiv[T=DT_INT64, _device="/device:CPU:0"](FloorDiv/x, FloorDiv/y)': 'op: "FloorDiv" device_type: "GPU" constraint { name: "T" allowed_values { list { type: DT_INT64 } } }' and 'op: "FloorDiv" device_type: "GPU" constraint { name: "T" allowed_values { list { type: DT_INT64 } } }'
	 [[Node: FloorDiv = FloorDiv[T=DT_INT64, _device="/device:CPU:0"](FloorDiv/x, FloorDiv/y)]]
```

**Comment by mrry** [comment]
@caisq It looks like this PR adds one or more new Python modules. The file [tf_python.cmake](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/tf_python.cmake) has a sequence of `add_python_module(…)` commands, one per module, and I guess we'll need a new one:

```
add_python_module("tensorflow/python/layers")
```

…and maybe others if there are submodules within that directory.

**Comment by lukeiwanski** [comment]
@caisq Upstream file ( https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_div.cc#L27 ) looks okay.. Seems like this ( https://github.com/caisq/tensorflow/commit/72e85c594000667dd1b3718da0f2bf7e2d003d74#diff-b6091d29f9b8efa4283ca6937ee6ceaaR35 ) merge went bad.

**Comment by gunan** [comment]
mac tests are flaking. but all the others seem to be legitimate failures.

**Comment by aselle** [comment]
As @lukeiwanski says, it looks like there are now two GPU entries for the integer version of floordiv. Delete the first one and it should help.

**Review by mrry — APPROVED** [review]
LGTM.

**Comment by gunan** [comment]
Windows failure is legit:
00:42:28.542         Start 170: C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/tensorboard/backend/handler_test.py
00:42:31.948 170/172 Test #170: C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/tensorboard/backend/handler_test.py .............................***Failed    3.41 sec
00:42:31.948 Traceback (most recent call last):
00:42:31.948   File "C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/tensorboard/backend/handler_test.py", line 28, in <module>
00:42:31.948     from tensorflow.tensorboard.backend import handler
00:42:31.948   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\tensorboard\backend\handler.py", line 43, in <module>
00:42:31.948     from tensorflow.tensorboard.plugins import REGISTERED_PLUGINS
00:42:31.948   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\tensorboard\plugins\__init__.py", line 20, in <module>
00:42:31.948     from tensorflow.tensorboard.plugins.projector.plugin import ProjectorPlugin
00:42:31.948   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\tensorboard\plugins\projector\plugin.py", line 27, in <module>
00:42:31.948     from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME
00:42:31.948   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 36, in <module>
00:42:31.948     from tensorflow.contrib import linalg
00:42:31.948 ImportError: cannot import name 'linalg'

tf.contrib.linalg seems to be a new package, and I bet they forgot to add it to the cmake files.

**Comment by gunan** [comment]
:|
```
ImportError: No module named 'tensorflow.contrib.linalg.python.ops'
```

**Comment by caisq** [comment]
All right. I pushed the following updates to fix the test failures
1) Removed the duplicate GPU kernel registration lines in cwise_op_floor_div.cc
2) Added new modules tensorflow/python/layers and tensorflow/contrib/linalg to tf_python.cmake
3) Disabled complex data types (complex64 and complex128) in cwise_ops_test.py _compareBCast() for now.

@aselle, I made a TODO item for you in cwise_ops_test.py to restore those data types once the question around the "+ 0.1" is resolved.

I'm merging this PR now.

**Comment by gunan** [comment]
I fixed the cwise op test on mac by removing +0.1
Looks like it used to not be there, and was added during a
mosunderstanding, it looks like.

**Comment by shenyuhit** [comment]
@caisq  T want to use cmake build the libtensorflow-core.a which enable gpu for c++ predict program。 But i saw the cmakelist can only work in windows that enable the gpu . What can i do?

**Comment by caisq** [comment]
@shenyuhit Maybe you can take a look at the makefile build that we have? See: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile

**Comment by shenyuhit** [comment]
@caisq  
I have tried to use makefile  and successfully acquired the  libtensorflow-core.a ,but it only supports  cpu, does not  support gpu!  In CPU to predict the time efficiency is not high enough ,so i want to predict in GPU!

**Comment by caisq** [comment]
@mrry: see the question from @shenyuhit. Is there a way to make the GPU cmake build work on noo-windows platforms?

**Comment by mrry** [comment]
@caisq There's some discussion of using CMake to build the GPU version on Ubuntu in #5465. However, it's not a configuration that we're planning to support, but we would accept contributions to make it work.

**Pull request merged**
