### PR TITLE
[WIP] [XLA:GPU] cuBLASLT integration in XLA

### PR DESCRIPTION
**Pull request by AyanmoI**

### CODE REVIEW

**Comment by gbaned** [comment]
@AyanmoI  This PR is in draft, any update on this? Please. Thanks!

**Comment by AyanmoI** [comment]
> @AyanmoI This PR is in draft, any update on this? Please. Thanks!

Not yet. Needs further testing and bug fixes.

**Comment by gbaned** [comment]
@AyanmoI This PR is in draft, any update on this? Please. Thanks!

**Comment by AyanmoI** [comment]
Closing this PR for now.

**Pull request closed without merging**
