### PR TITLE
avoid signed unsigned comparison warning

### PR DESCRIPTION
**Pull request by walyong**

### CODE REVIEW

**Comment by walyong** [comment]
I signed it!

**Review by shashishekhar — COMMENTED** [review]
The changes look incorrect: replace || with |
Also I will like to avoid casts, we can disable the warning on particular files.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by qlzh727** [comment]
Is this PR still alive? @walyong, please address the review comments, thanks.

**Comment by tensorflowbutler** [comment]
It has been 20 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by martinwicke** [comment]
I'll close this for inactivity. Reopen a new PR if you want to continue this.

**Pull request closed without merging**
