### PR TITLE
Fix tutorials failures.

### PR DESCRIPTION
**Pull request by gunan**
ptb_word_lm should work, but want to see how cifar10_train will look.

### CODE REVIEW

**Comment by caisq** [comment]
ptb_word_lm is fixed (great!) 

But looks like cifar10_train is still failing, maybe read_input.label needs to call set_shape() as well?

**Review by caisq — APPROVED** [review]

**Comment by caisq** [comment]
Thanks a lot for the fix, @gunan !

**Comment by jperczel** [comment]
Hi, with the new version of read.py I get the following error message:
TypeError: strided_slice() takes at least 4 arguments (3 given)

**Comment by gunan** [comment]
@physicsai are you using compatible versions of this file and the pip package?

If you have tensorflow 0.12.0rc0 installed, you need to use the version of the file in r0.12 branch of this repo. If you have built tensorflow from source, you can use this file.

Also, please reach out to us by either filing an issue, or through stackoverflow. Pull requests, after merging, cannot really address any questions anymore.

**Comment by physicsai** [comment]
@gunan  It was indeed an issue with tensorflow verions. It runs all fine when I clone the r0.11 files. Thanks for your help!

**Pull request merged**
