### PR TITLE
Correct minimum Python 3 version in install instruction

### PR DESCRIPTION
**Pull request by carlthome**
https://github.com/tensorflow/tensorflow/issues/12309

### CODE REVIEW

**Comment by caisq** [comment]
We do have python 3.3 wheels available on PyPI: https://pypi.python.org/pypi/tensorflow

If we make this change, we should remove the wheels from pypi in the next release.

**Comment by carlthome** [comment]
It's actually NumPy that made 3.4 the minimum, but I imagine that will cause some confusion for people that are careless with their `pip install` commands.

Another alternative would be to change `numpy>=1.11.0` to `numpy==1.11.0`

**Comment by gunan** [comment]
Actually we need to go higher than 1.12 in numpy due to our new autograd dependency.
So we wont be able to pin it to 1.11.

I am ok with this change and also having 3.3 wheel on pypi for a while.
We can use it as a transition period.

**Review by gunan — APPROVED** [review]

**Comment by hugovk** [comment]
This page https://www.tensorflow.org/install/install_linux still says "Python 3.3+". 

Please could you deploy these updates to avoid further confusion?

Thank you.

**Pull request merged**
