### PR TITLE
[ROCm] Updates to account for the removal of $ROCM_PATH/include/hiprand,rocrand dirs

### PR DESCRIPTION
**Pull request by deven-amd**
The following dirs (which are soft-links really) will removed in a (near) future ROCm release. This commit updates `rocm_configure.bzl` to account for that change by explicitly copying over the header files (for `local_config_rocm` repo) from the following directories instead
* $ROCM_PATH/hiprand/include
* $ROCM_PATH/rocrand/include

Unfortunately making the above change also breaks the build, if the directories that will be going away, are still present. This is because we end up with two `make_copy_dir_rule`s in `rocm_configure.bzl` that try to write to the same destination dirs

```
ERROR: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/local_config_rocm/rocm/BUILD", line 1588, column 8, in <toplevel>
		genrule(
Error in genrule: generated file 'rocm/include/hiprand/hiprand.h' in rule 'hiprand-include' conflicts with existing generated file from rule 'rocm-include', defined at /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/local_config_rocm/rocm/BUILD:175:8
```

In order to get around this error, this commit is also updating the `Dockerfile.rocm` to explicitly delete those two dirs from the `$ROCM_PATH/include` dir, immediately after installing ROCm

------------------------------------

@cheshire @chsigg

### CODE REVIEW

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Review by cheshire — APPROVED** [review]

**Comment by cheshire** [comment]
@deven-amd I have no idea what this code is doing, but since it's ROCM-only I trust your judgement on it.

**Comment by deven-amd** [comment]
@gbaned this PR seems to have gotten stuck in the merge pipeline...anything we can do on our end to get it merged?

**Review by chsigg — APPROVED** [review]

**Comment by deven-amd** [comment]
@gbaned gentle ping.  @chsigg already approved this PR

**Comment by gbaned** [comment]
> @gbaned gentle ping. @chsigg already approved this PR

@deven-amd There are commits after approval, hence re-requested @chsigg to review. Thanks!

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Review by chsigg — APPROVED** [review]

**Pull request merged**
