### PR TITLE
Fix few warnings that I see on macosx-clang compilation

### PR DESCRIPTION
**Pull request by Mistobaan**

### CODE REVIEW

**Comment by Mistobaan** [comment]
The only one that I am not 100% sure is the `this == nullptr`. I don't think this should ever be possible in C++ from within a method. Right ?

```
if (this == nullptr) {		
    return "{nullptr}";		
 }
```

**Comment by keveman** [comment]
@tensorflow-jenkins test this.

**Comment by keveman** [comment]
@Mistobaan can you please resolve the merge conflicts?
@martinwicke can you please kick off a jenkins test?

**Comment by martinwicke** [comment]
@keveman you can trigger that too, if not, that's a problem.

Jenkins, test this please!

**Comment by Mistobaan** [comment]
@keveman fixed

**Comment by keveman** [comment]
@martinwicke I did try uttering the magic words, but doesn't seem like the testing has happened.

**Comment by martinwicke** [comment]
Jenkins? Test this please?

**Comment by martinwicke** [comment]
Maybe I wasn't nice enough.

**Pull request merged**
