### PR TITLE
Updated find_cuda_config.py.gz.base64

### PR DESCRIPTION
**Pull request by cliffwoolley**
Now matches https://github.com/tensorflow/tensorflow/pull/56246

Signed-off-by: Cliff Woolley <jwoolley@nvidia.com>

### CODE REVIEW

**Comment by cliffwoolley** [comment]
@chsigg @nluehr @DEKHTIARJonathan

**Comment by DEKHTIARJonathan** [comment]
This PR finishes to address the problem and I'm now able to compile TF upstream. See https://github.com/tensorflow/tensorflow/pull/56246 for the original description of the problem

**Comment by cliffwoolley** [comment]
Note: the need for this seems to first appear in CUDA 11.7 Update 1, which is due out soon.

**Review by chsigg — APPROVED** [review]

**Comment by cliffwoolley** [comment]
@nluehr called to my attention that I should have used `python3 compress_find_cuda_config.py` for this.  Instead I did it via `pigz -z find_cuda_config.py; base64 --wrap=0 find_cuda_config.py.zz > find_cuda_config.py.gz.base64` .

Unfortunately compress_find_cuda_config.py is also slightly broken/outdated:

```
--- a/third_party/gpus/compress_find_cuda_config.py
+++ b/third_party/gpus/compress_find_cuda_config.py
@@ -12,7 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 # ==============================================================================
-"""Compresses the contents of 'find_cuda.py'.
+"""Compresses the contents of 'find_cuda_config.py'.

 The compressed file is what is actually being used. It works around remote
 config not being able to upload files yet.
@@ -22,13 +22,13 @@ import zlib


 def main():
-  with open('find_cuda.py', 'rb') as f:
+  with open('find_cuda_config.py', 'rb') as f:
     data = f.read()

   compressed = zlib.compress(data)
   b64encoded = base64.b64encode(compressed)

-  with open('find_cuda.py.gz.base64', 'wb') as f:
+  with open('find_cuda_config.py.gz.base64', 'wb') as f:
     f.write(b64encoded)


```
The two methods' outputs differ by only two header bytes:
```
@@ -1,6 +1,6 @@
 e
-F
-7
+J
+z
 d
 P
 G
 ```

I can resubmit with a fixed compress_find_cuda_config.py and the byte-exact output using that script if you'd prefer, @chsigg .

**Comment by chsigg** [comment]
I Cliff, that would be much appreciated, to prevent the next person to run into this again. Thanks a lot!

**Comment by cliffwoolley** [comment]
@chsigg -- Done.  This PR now includes the fixed `compress_find_cuda_config.py` as well as the direct output of that script.

**Review by chsigg — APPROVED** [review]

**Comment by chsigg** [comment]
Thanks a lot Cliff!

**Comment by cliffwoolley** [comment]
Anything else I need to do here?  A few CI tests failed, but the failures look unrelated as far as I can tell.

**Comment by DEKHTIARJonathan** [comment]
@chsigg any blocker ?

**Comment by gbaned** [comment]
> @chsigg any blocker ?

Hi @cliffwoolley, @DEKHTIARJonathan Nothing pending from your end at this point. It have internal errors, we are working on it.  Thank you!

**Review by rthadur — APPROVED** [review]

**Review by gcforster — COMMENTED** [review]
LGTM

**Review by gcforster — APPROVED** [review]

**Pull request merged**
