### PR TITLE
[oneDNN][BugFix] Prevent AMP exit on supported CPU platforms

### PR DESCRIPTION
**Pull request by akhilgoe**
This PR prevents the Auto Mixed Precision Optimizer to exit for float16 on supported Intel E-Cores.

### CODE REVIEW

**Comment by keerthanakadiri** [comment]
Hi @ezhulenev  , Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @ezhulenev , Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @ezhulenev , Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @ezhulenev , Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @ezhulenev , Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @ezhulenev , Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @ezhulenev , Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @ezhulenev , Can you please review this PR? Thank you !

**Review by penpornk — APPROVED** [review]
Thank you for the fix!

**Pull request merged**
