### PR TITLE
tf.function decorator converts ragged tensors to their dense equivalent #26505

### PR DESCRIPTION
**Pull request by shashvatshahi1998**
tf.function decorator converts ragged tensors to their dense equivalent #26505

### CODE REVIEW

**Comment by shashvatshahi1998** [comment]
This is just for basic review purpose , just to check that I am on right track or not. There are still some changes which I have to add further.

**Comment by allenlavoie** [comment]
@edloper would know better whether you're on the right track. I think he was also working on this.

Unit tests would be good so we know what we're fixing (but check with Edward to see what he's doing so you're not stepping on each other's toes).

**Comment by shashvatshahi1998** [comment]
@edloper can you please review it once and tell me my mistakes?

**Comment by shashvatshahi1998** [comment]
@edloper  can you please review it once.

**Comment by shashvatshahi1998** [comment]
please somebody review this PR

**Comment by shashvatshahi1998** [comment]
@alextp can you please review it and tell me, what can I do further?

**Comment by edloper** [comment]
Sorry for the delay in responding to this thread.  I have had to explore some of the implications of this change especially with respect to input_signature and TensorSpecs.  I submitted [a change](https://github.com/tensorflow/tensorflow/commit/40006c34f53e2a0b3fe72079dae64168cc2c0d1d) a few days ago that updates tf.function to accept composite tensors (including ragged tensor and sparse tensor), and will follow up with another change to add support for input_signatures.

**Comment by gbaned** [comment]
@shashvatshahi1998 could you please resolve the conflicts? Thanks!

**Comment by edloper** [comment]
The issue that this PR was meant to address fixed by commit 40006c3.

**Pull request closed without merging**
