### PR TITLE
Converter for Tile operation

### PR DESCRIPTION
**Pull request by andrei5055**
- ConvertTile operator is implemented so that both parameters (tensor and multiplier) can be passed as tensors and weights. A unit test with 6 tests and all combinations of passed parameters is provided.
- New macro #define CHECK_INPUT_SIZE (size, exp_size, node_def) unifies the testing of the number of parameters passed. It is used in 8 different places.
- The helper function template <typename T> void AdjustVectorByDims(...) makes writing tests much easier (especially tests with parameters that can be passed as tensors and weights). For example, today we can use some parameters like tensors with predefined dimensions, but with no real numbers. An attempt to pass the same parameters with the same values as weights leads to the crash. We see a similar crash when the vector providing the values assigned to the tensor is not empty, but its length does not match the number of values defined by the dimensions. AdjustVectorByDims fixes these two problems and is called by default in the situations described, but these calls can also be blocked when such failures are intentional.

### CODE REVIEW

**Comment by tfeher** [comment]
Thanks @andrei5055 for the PR! Tagging @bixia1 for review.

**Comment by bixia1** [comment]
Shall we close this PR as it is replaced by [PR53718](https://github.com/tensorflow/tensorflow/pull/53718)?

**Comment by drivanov** [comment]
Yes, this one should be closed, it was replaced by [PR53718](https://github.com/tensorflow/tensorflow/pull/53718)

**Comment by gbaned** [comment]
@andrei5055 Can you please resolve conflicts? Thanks!

**Comment by drivanov** [comment]
> @andrei5055 Any update on this PR? Please. Thanks!

@gbaned : This one was closed and replaced by [#53718](https://github.com/tensorflow/tensorflow/pull/53718) and [#54424
](https://github.com/tensorflow/tensorflow/pull/54424)which were also closed. Currently, only [#54427](https://github.com/tensorflow/tensorflow/pull/54427) should be considered.

**Comment by andrei5055** [comment]
Closing this one because the latest version is in [PR#54427](https://github.com/tensorflow/tensorflow/pull/54427)

**Pull request closed without merging**
