### PR TITLE
Update API Docs

### PR DESCRIPTION
**Pull request by wagonhelm**
Updated api dos for SampleDistortedBoundingBox v1 and v2 to update tf.image_summary to tf.summary.image

### CODE REVIEW

**Comment by yifeif** [comment]
Thanks @wagonhelm. These files are auto-generated from the code. Could you updated in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py as well?

**Comment by wagonhelm** [comment]
[Done](https://github.com/tensorflow/tensorflow/pull/15532/files), thanks!

**Comment by yifeif** [comment]
Thanks @wagonhelm, could you run tensorflow/core/api_def/update_api_def.sh and check what are the pbtxt files that should be updated?

**Comment by wagonhelm** [comment]
[Done](https://github.com/tensorflow/tensorflow/pull/15545) on a new branch, tests passed, will delete this pull request once new one is pushed.

Thanks for walking me through the process @yifeif

**Comment by yifeif** [comment]
I'm closing this one in favor of #15545. Thanks again!

**Pull request closed without merging**
