### PR TITLE
Classify Java ops in API definitions

### PR DESCRIPTION
**Pull request by karllessard**
This PR classifies the Java operators so that they do not all end up in the main (core) package, e.g. the `Sqrt` operator is now accessed from `ops.math.sqrt(...)` instead of `ops.sqrt(...)`.

The classification is following pretty the one used in Python V2 API. Here's the list of additional packages that are generated using it and a few exceptions to make it work in Java:
```
org.tensorflow.op.audio
org.tensorflow.op.bitwise
org.tensorflow.op.collective
org.tensorflow.op.core
org.tensorflow.op.data
org.tensorflow.op.dtypes
org.tensorflow.op.image
org.tensorflow.op.io
org.tensorflow.op.linalg
org.tensorflow.op.math
org.tensorflow.op.nn
org.tensorflow.op.quantization
org.tensorflow.op.random
org.tensorflow.op.signal
org.tensorflow.op.sparse
org.tensorflow.op.strings
org.tensorflow.op.summary
org.tensorflow.op.train
```
Exceptions for Java: 
* `Assert` is renamed to `AssertThat` to avoid conflict with `assert` keyword
* `Switch` is renamed to `SwitchCond` to avoid conflict with `switch` keyword

CC: @asimshankar , @annarev , @martinwicke

### CODE REVIEW

**Comment by asimshankar** [comment]
Thanks! 

@annarev : Does it make sense to collapse many of these endpoints into the "base" api_def so they are automatically shared across languages, instead of having to duplicate them between Python and Java?

**Review by asimshankar — APPROVED** [review]
(May make sense to collapse with the base_api definitions, will defer to @annarev on that. But otherwise looks good to me. Also, @annarev - if we don't collapse, then what's the best way to keep this and the Python one in sync as much as possible?)

**Review by asimshankar — APPROVED** [review]
(May make sense to collapse with the base_api definitions, will defer to @annarev on that. But otherwise looks good to me. Also, @annarev - if we don't collapse, then what's the best way to keep this and the Python one in sync as much as possible?)

**Review by asimshankar — CHANGES_REQUESTED** [review]
@karllessard : Could you take a look at the failing tests. It seems that the names of the generated classes don't always match the files. For example, I saw this in the build log (note the `3d` in the generated class name and the `3D` in the filename):

```
ERROR: /Volumes/BuildData/tmpfs/src/github/tensorflow/tensorflow/java/BUILD:20:1: Couldn't build file tensorflow/java/libtensorflow.jar: Building tensorflow/java/libtensorflow.jar (27 source files, 1 source jar) and running annotation processors (OperatorProcessor) failed (Exit 1): java failed: error executing command 
  (cd /Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/execroot/org_tensorflow && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/embedded_jdk/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--patch-module=java.compiler=external/bazel_tools/third_party/java/jdk/langtools/java_compiler.jar' '--patch-module=jdk.compiler=external/bazel_tools/third_party/java/jdk/langtools/jdk_compiler.jar' '--add-opens=java.base/java.nio=ALL-UNNAMED' -jar external/bazel_tools/tools/jdk/JavaBuilder_deploy.jar @bazel-out/darwin-opt/bin/tensorflow/java/libtensorflow.jar-2.params)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/install/912b630badc6cc8c4a621e7b44c0b313/_embedded_binaries/embedded_tools/tools/jdk/JavaBuilder_deploy.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
/src/main/java/org/tensorflow/op/nn/Conv3DBackpropFilter.java:35: error: class Conv3dBackpropFilter is public, should be declared in a file named Conv3dBackpropFilter.java
public final class Conv3dBackpropFilter<T extends Number> extends PrimitiveOp implements Operand<T> {
             ^
```

**Comment by karllessard** [comment]
@asimshankar : ok found the case, both classes are generated: `Conv3DBackpropFilter` and `Conv3dBackpropFilter` (the former is from `Conv3DBackpropFilter` op and the later is from `Conv3DBackpropFilterV2` op).

I don't know why this specific test it was failing since in both files the classes was named correctly but I'll rename them to avoid this conflict. I suggest to drop all ops that has a V2 version at this point, what do you think?

**Comment by karllessard** [comment]
all right, I pushed a new version using lowercase accronyms exclusively and renamed the conflicting op class to `Conv3dBackpropFilterV2`.

@asimshankar , if you think we should also get rid of any version that has been succeeded, just let me know (e.g. if there is `MyOp`, `MyOpV2` and `MyOpV3` available, we only generate a class for the last one that we rename `MyOp`).

**Comment by harshini-gadige** [comment]
> all right, I pushed a new version using lowercase accronyms exclusively and renamed the conflicting op class to `Conv3dBackpropFilterV2`.
> 
> @asimshankar , if you think we should also get rid of any version that has been succeeded, just let me know (e.g. if there is `MyOp`, `MyOpV2` and `MyOpV3` available, we only generate a class for the last one that we rename `MyOp`).

@asimshankar   Any update on the approval ? Please keep us posted.

**Comment by asimshankar** [comment]
@karllessard : Yeah, makes sense to only generate for the latest version and drop the older ones.

**Comment by karllessard** [comment]
> @karllessard : Yeah, makes sense to only generate for the latest version and drop the older ones.

@asimshankar I'm having some doubts now and would like to have your advice: if we delete previous versions, how will we handle the next ones? 

For example, if we are at `MyOpV2` right now, we'll delete `MyOp` and rename endpoint of V2 as `MyOp`... but when V3 appears, whose gonna be `MyOp`? V3? If so, for backward compatibility, I guess we'll have to keep `MyOpV2` but with its original name?

**Comment by asimshankar** [comment]
> > @karllessard : Yeah, makes sense to only generate for the latest version and drop the older ones.
> 
> @asimshankar I'm having some doubts now and would like to have your advice: if we delete previous versions, how will we handle the next ones?
> 
> For example, if we are at `MyOpV2` right now, we'll delete `MyOp` and rename endpoint of V2 as `MyOp`... but when V3 appears, who's gonna be `MyOp`? V3? If so, for backward compatibility, I guess we'll have to keep `MyOpV2` but with its original name?

We'll do exactly what we do in Python - where we keep the endpoint name the same but change the implementation so that it invokes the new operation. For example, consider this really old change where a `GatherV2` operation was added and we set things up so that the Python `tf.gather` function adds the `GatherV2` operation (see [change to `array_ops.py` in this commit](https://github.com/tensorflow/tensorflow/commit/b1f9e2c89eb007cb4b9483d08dcace1e45e84164#diff-68052049ee5dc7573829a5fdb7a57310R2405))

For the example you provided, yes, this amounts to the Java class `org.tensorflow.op.mypkg.MyOp` adding the `MyOpV3` operation to the graph instead of the `MyOpV2` operation. Does that make sense?

**Comment by karllessard** [comment]
In Java, the endpoints are automatically generated from the signature of their op, so it will work only if V3 has a signature backward compatible with V2. To support other cases, we’ll need to create a wrapper class that will “hide” the original ops. That shouldn’t be a problem though and will probably be exceptional.

Ok, I’ll clean up the ops tonight to keep only the last version available, thanks!

**Comment by karllessard** [comment]
@asimshankar done!

**Comment by karllessard** [comment]
@asimshankar is it too late to update this PR once again? I want to make visible those ops that are hidden by default from the `base_api` defs, since there is no wrapper in Java for them (~140 ops, ex: `WriteSummary`).

Otherwise I'll just create another PR for this, thanks

**Comment by asimshankar** [comment]
I wouldn't override the hidden ops. Ops are generally marked hidden because they typically require some additional outside-of-graph pre-processing before being useful, i.e., we'd want a hand-crafted Java class instead of having clients use the op directly. Similar to some Python API endpoints.

**Comment by karllessard** [comment]
Ok, sounds good.

**Comment by karllessard** [comment]
@harshini-gadige , @asimshankar : is there anything left to be done for this PR to get merged? I thought the review was completed

**Comment by harshini-gadige** [comment]
> @harshini-gadige , @asimshankar : is there anything left to be done for this PR to get merged? I thought the review was completed

@karllessard  If  the reviewer approves it, I can proceed further to help this get merged. Before that please make sure you made all changes as suggested by the reviewer(if any).

**Comment by karllessard** [comment]
I think I did, @asimshankar?

**Review by asimshankar — APPROVED** [review]

**Comment by karllessard** [comment]
@harshini-gadige sorry for bugging you again with this but can we target to merge this PR for 1.13 release? Thanks

**Comment by martinwicke** [comment]
Something got stuck in the tooling. I'm looking into it.

**Comment by annarev** [comment]
Really sorry for missing all the questions here earlier!

@asimshankar Yep, definitely makes sense to collapse into base api_defs if all languages use the same namespaces. Is it true for C++ and Go?

@karllessard: "For example, if we are at MyOpV2 right now, we'll delete MyOp and rename endpoint of V2 as MyOp... but when V3 appears, who's gonna be MyOp? V3? If so, for backward compatibility, I guess we'll have to keep MyOpV2 but with its original name (forcing the clients to update their code)?"

Are you asking about op name at C++ layer or at Java API layer? At C++ layer, we don't deprecate ops as far as I know, therefore MyOp in V3 would need to be named MyOpV3. At Java layer, we can break backwards compatibility at a major release. That is, when we release TF 3.0, we can name V3 version MyOp. Older versions could either be removed or renamed.

On Python side, we provide a `tf.compat.v1` module that keeps V1 names available in V2. For e.g. tf.compat.v1.foo would still point to 1.* version of `foo` even though `tf.foo` points to the 2.* version. May be something like this can be done on Java side too.

We also provide a script for Python API that renames endpoints for 2.0 upgrade. For e.g. that script could auto rename 'MyOp' to 'MyOpV2' if 'MyOpV2' is corresponding 2.* name.

**Review by annarev — APPROVED** [review]

**Comment by karllessard** [comment]
> At Java layer, we can break backwards compatibility at a major release.

Ok that make sense, thanks Anna

**Pull request merged**
