### PR TITLE
Remove left over code

### PR DESCRIPTION
**Pull request by nouiz**
Remove left over code since the removal of XLAFusionOptimizer in e833b6c98b53d7e06a619d0b5329d7ffb2135b64

@sanjoy

### CODE REVIEW

**Review by sanjoy — DISMISSED** [review]
lgtm

**Comment by nouiz** [comment]
I forgot to remove some other lines. So I amended the commit above to remove all leftover lines.

**Review by sanjoy — APPROVED** [review]
lgtm

**Comment by nouiz** [comment]
4 CI failed, but I do not think the error is related to my PR.
And the Ubuntu CC didn't run. Any idea what is going on?

**Review by sanjoy — APPROVED** [review]

**Pull request merged**
