### PR TITLE
Try to switch to h5py 3.1.0

### LINKED ISSUE #44467: h5py==3.0.0 causes issues with keras model loads in tensorflow 2.1.0
h5py released version 3.0.0 today and it causes this code to fail:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/saving/hdf5_format.py#L182
with error:

```
File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

It looks like in version 2.1.0 the `h5py` version is not pinned (it is pinned in master), which is causing the issue.

### PR DESCRIPTION
**Pull request by bhack**
This reverts commit d36db2955c460d2abe185ced9cc5bdfabc67b631.

Reopen https://github.com/tensorflow/tensorflow/pull/45380 that was merged when still under tests.

/cc @mihaimaruseac 

Fixes https://github.com/tensorflow/tensorflow/issues/44467

### CODE REVIEW

**Comment by bhack** [comment]
@mihaimaruseac Please we could work here after you have investigated on the Win/Macos machine. I  have allowed you edits directly in the PR

**Comment by bhack** [comment]
I put some blackbox (as I have no access to Win/Macos machine) workarounds for windows and Macos. 
Now we have only `OSError: Unable to open file (unable to open file)` on Windows  only for the `core` driver test case:

```
      # Test non-default options in h5
      with h5py.File('_', driver='core',
                     backing_store=False) as h5file:
```
And a MLIR error for Macos

**Comment by bhack** [comment]
Very strange on Windows GPU all tests are passing.

**Comment by silvasean** [comment]
> /cc @silvasean any hint about your MLiR test on MacOS?

Sorry, no specific hints. I ran into these kinds of random breakages and very painfully debugged them at a distance by re-running presubmits as I don't have a mac. My sympathies go out to you!

**Comment by bhack** [comment]
@silvasean Thanks but it is unrelated cause it is failing with the same MLIR test also in other PRs

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
