### PR TITLE
Fix tfcompile module label.

### PR DESCRIPTION
**Pull request by andykernahan**
Hi,

The tfcompile module label is incorrect in the docs; this PR fixes it.

Cheers,

Andy

### CODE REVIEW

**Comment by jhseu** [comment]
Ankur, FYI, this affects the merge back in

**Comment by ankurtaly** [comment]
Thanks for the fix!

This PR affects the pull from Public to Google Internal (as the /third_party/ prefix is essential for Google Internal). We will do the pull in the next day or so, and review this PR after that.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ankurtaly: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ankurtaly: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ankurtaly: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by jhseu — APPROVED** [review]

**Pull request merged**
