### PR TITLE
Changes to add bfloat16 support for image rotation

### PR DESCRIPTION
**Pull request by jojivk73**
This are changes to add bfloat16 to image rotation. When models are run in mixed bfloat16 precision, models that use image transformation would perform much better with image rotation in bfloat16.

### CODE REVIEW

**Review by cantonios — CHANGES_REQUESTED** [review]
Can you add a test for the new dtype?

**Comment by cantonios** [comment]
> @cantonios, Thanks for the review. I was not able to find a testcase in the framework, (that I could test and enable) for bfloat16. Do you want me to add a python testcase or C++ testcase for this?. If you can give me a reference testcase it will be great. I tried updating and running this testcase tensorflow/python/ops/image_ops_test.py (only forImageProjectiveTransformV2) . It fails for different versions of protobuf (latest : 4.23, and based on comments in failure: 3.19, 3.20).

Yes, modifying the existing `ImagProjectiveTransformV2` python test is fine.  I don't understand your comment about protobuf issues... the test is currently enabled, so should be passing.  It sounds like a configuration error on your end.

**Comment by gbaned** [comment]
Hi @jojivk73 Any update on this PR? Please. Thank you!

**Comment by jojivk73** [comment]
@gbaned , Additions under internal review. Will upstream soon. Thanks

**Pull request closed without merging**
