### PR TITLE
[Intel MKL] Adding a unit test for MKL eager rewrite

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**

### CODE REVIEW

**Review by jaingaurav — APPROVED** [review]

**Review by alextp — APPROVED** [review]

**Review by Ishaan28malik — APPROVED** [review]

**Comment by mahmoud-abuzaina** [comment]
It looks like this PR was rolled back. Do we know why?

**Comment by Ishaan28malik** [comment]
It was an automated rollback as it seems.
@mahmoud-abuzaina

**Comment by gbaned** [comment]
@jaingaurav Could you please help to @mahmoud-abuzaina on rolled back. Thanks!

**Comment by ashraf-bhuiyan** [comment]
@gbaned @jaingaurav is there anyway I can help so that the PR can be merged again.

**Comment by jaingaurav** [comment]
ashraf-bhuiyan@ It was some macos build failure, but the error seems unrelated. I'm trying to roll-forward the fix.

**Comment by jaingaurav** [comment]
Okay we had to disable the test on macos but the PR is merged again.

**Comment by ashraf-bhuiyan** [comment]
Thank you so much @jaingaurav

**Pull request merged**
