### PR TITLE
[PJRT][Fix] Add device check for NextPluggableDevice in GetPjRtExecuteOptions 

### PR DESCRIPTION
**Pull request by cboss6**
Description:
Add device check for NextPluggableDevice(NPD) in GetPjRtExecuteOptions as NPD also needs to set options.strict_shape_checking to false.

### CODE REVIEW

**Comment by cboss6** [comment]
Hi @jyingl3, could you help to review this PR? Thanks!

**Comment by jyingl3** [comment]
This change will set options.strict_shape_checking to false for all NextPluggableDevice. Can you apply this change only to your NPD? If not, I think it is ok to set options.strict_shape_checking to false for all NextPluggableDevice.

**Comment by keerthanakadiri** [comment]
Hi @jyingl3 , Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @cboss6 , Can you please resolve the conflicts? Thank you!

**Comment by cboss6** [comment]
I will fix it ASAP, thanks!

**Comment by cboss6** [comment]
@keerthanakadiri 
Done. Thx!

**Comment by cboss6** [comment]
@

**Pull request closed without merging**
