### PR TITLE
[INTEL MKL] Fix oneDNN Ubuntu partials and Dockerfiles and remove support for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by ashahba**
Signed-off-by: Abolfazl Shahbazi <abolfazl.shahbazi@intel.com>

### CODE REVIEW

**Comment by ashahba** [comment]
To build Ubuntu 18.04 and 20.04 containers from `Intel` try this:

```
pushd <PATH_TO_THE_SOURCE>/tensorflow/tools/dockerfiles

alias asm_dockerfiles="docker run ${DOCKER_RUN_ENVS} --rm -u $(id -u):$(id -g) -v $(pwd):/tf tf-tools python3 assembler.py "

asm_dockerfiles --release dockerfiles --construct_dockerfiles

alias asm_images="docker run ${DOCKER_RUN_ENVS} --rm -v $(pwd):/tf -v /var/run/docker.sock:/var/run/docker.sock tf-tools python3 assembler.py "
```
and then build Ubuntu 18.04 and 20.04 base and Jupyter images for example, this way:


```
# For UBUNTU images
declare -a OS_VERSIONS=( "ubuntu-18.04" "ubuntu-20.04" )
for OS_VERSION in ${OS_VERSIONS[@]}; do
  PY_MINOR_VER=8
  PYTHON=python3.${PY_MINOR_VER}
  PYTHON_TAG=py3${PY_MINOR_VER}
  TF_VERSION=2.8.0
  TF_PACKAGE=intel-tensorflow
  HOROVOD_VERSION=v0.24.2
  asm_images \
      ${PARTIALS_BUILD_ARGS} \
      --release onednn \
      --repository intel-optmized-tensorflow \
      --arg BAZEL_VERSION=4.2.1 \
      --arg TF_BRANCH=v${TF_VERSION} \
      --arg TF_PACKAGE=${TF_PACKAGE} \
      --arg HOROVOD_VERSION=${HOROVOD_VERSION} \
      --arg TF_PACKAGE_VERSION=${TF_VERSION} \
      --arg PYTHON=${PYTHON} \
      --arg _TAG_PREFIX=${PYTHON_TAG}-${TF_VERSION} \
      --build_images \
      --only_tags_matching ${PYTHON_TAG}-${TF_VERSION}-${OS_VERSION}'$'

  asm_images \
      ${PARTIALS_BUILD_ARGS} \
      --release onednn \
      --repository intel-optmized-tensorflow \
      --arg BAZEL_VERSION=4.2.1 \
      --arg TF_BRANCH=v${TF_VERSION} \
      --arg TF_PACKAGE=${TF_PACKAGE} \
      --arg HOROVOD_VERSION=${HOROVOD_VERSION} \
      --arg TF_PACKAGE_VERSION=${TF_VERSION} \
      --arg PYTHON=${PYTHON} \
      --arg _TAG_PREFIX=${PYTHON_TAG}-${TF_VERSION} \
      --build_images \
      --only_tags_matching ${PYTHON_TAG}-${TF_VERSION}-${OS_VERSION}-jupyter'$'
done
```

Once the build is done you have the following images ready for testing:

```
$ docker images --format "{{.Repository}}:{{.Tag}}" | grep py38 | sort
intel-optmized-tensorflow:py38-2.8.0-ubuntu-18.04
intel-optmized-tensorflow:py38-2.8.0-ubuntu-18.04-jupyter
intel-optmized-tensorflow:py38-2.8.0-ubuntu-20.04
intel-optmized-tensorflow:py38-2.8.0-ubuntu-20.04-jupyter
```

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thank you!

**Comment by ashahba** [comment]
Hi @penpornk 
any feedback on this PR?

Thanks.

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by ashahba** [comment]
@penpornk any feedback on this one?

**Comment by gbaned** [comment]
Hi @ashahba Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by mihaimaruseac** [comment]
The docker containers will be moved in a different direction. I think we should instead close this.

**Pull request closed without merging**
