### PR TITLE
Create build shell script to make installation and setup of TensorFlo…

### PR DESCRIPTION
**Pull request by aaronhma**
In this commit, II created a build.sh file which makes installing and setting up TensorFlow easier for beginners and pros. This file supports all computer platforms.

### CODE REVIEW

**Comment by gunan** [comment]
I am skeptic about this script, but I will read it more closely once I have more time.
For example, on windows running a "bash" script is a problem of its own. 

@angerson @yifeif to see if they have any comments.

**Comment by gunan** [comment]
Also @mihaimaruseac as I see "sudo" calls in the script.

**Comment by mihaimaruseac** [comment]
I think this is better as a tutorial / file outside of the repo, as it currently makes several assumption about the environment it is going to run in (i.e: what happens if someone wants to use TensorFlow on Fedora? ArchLinux? Gentoo? NixOS?; `apt` won't work on either of these and the script would just be one extra file in the directory).

**Comment by aaronhma** [comment]
Maybe I should change the script?

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by aaronhma** [comment]
Ok, thanks, everyone! That's a good suggestion. I found this: https://www.tensorflow.org/install/source much better than my script. Until next time!

**Pull request closed without merging**
