### PR TITLE
Fix numpy 1.20 deprecation warnings

### PR DESCRIPTION
**Pull request by NeilGirdhar**
Replaced
* np.bool with np.bool_,
* np.int with np.int64,
* np.float with np.float64,
* np.complex with np.complex128
* np.object with np.object_,
* np.str with np.str_, and
* np.unicode with np.str_.

Repaired 4 uses of np.complex that should have been np.complexfloating.

According to https://numpy.org/doc/stable/release/1.20.0-notes.html,
this will have no effect except to suppress deprecation warnings.

### CODE REVIEW

**Review by kkimdev — APPROVED** [review]

**Comment by zenogantner** [comment]
Thank you for this PR.

Wouldn't it be more elegant to replace `np.bool` with `bool`, `np.object` with `object`, and `np.string` and `np.unicode` with `str`?

The numpy release notes say:

> To give a clear guideline for the vast majority of cases, for the types bool, object, str (and unicode) using the plain version is shorter and clear, and generally a good replacement.

**Comment by NeilGirdhar** [comment]
> Wouldn't it be more elegant to replace…

Yes, it's definitely a reasonable solution to specify dtypes using the Python types or using dtypes.

One of my considerations is to try to remain consistent with the rest of TensorFlow.  Currently, roughly 13000 other places in the code use dtypes whereas about 1200 use Python types.

Another reason is that `np.int64` is explicit.  Someone may come along later and wonder whether `int` corresponds to `int64` or `int32` or `int128` (when it exists).  It's nice not having to guess.

Finally, this is the typical style in every numeric library I've looked at (NumPy itself, scipy, JAX, etc.)

I'm happy to do things the other way if you prefer.

**Comment by zenogantner** [comment]
I fully agree on the more explicit `int64` -- which is why I did not list it here.

The other ones are somewhat about aesthetics and a lot about how much the code will make the reader think, and what it will make them think:

 - Something that ends in an underscore would make me think -- "ah, looks we are using some internals or stuff we otherwise should not use".
 -  Using `np.unicode_` makes it look like it represents a datatype different from `str` when in reality it is the same datatype (in Python 3).
 - Using the `np.` prefix might make readers of the code think that these datatypes are different from Python's built-in ones, when in reality they are not.

Of course that needs to be weighed against the consistency with the rest of the code base. If the usage was almost 100% in one direction, the decision would be easy :-).

Anyway, just my opinion with some thoughts around it -- do whatever suits you with it.
I am happy if the deprecation warnings go away.

**Comment by NeilGirdhar** [comment]
> Something that ends in an underscore would make me think -- "ah, looks we are using some internals or stuff we otherwise should not use".

In Python, when the underscore precedes the word: `_something` it indicates a private variable.  An underscore following a word indicates a name chosen to avoid a collision, which is exactly what happened here.

> Using np.unicode_ makes it look like it represents a datatype different from str when in reality it is the same datatype (in Python 3).

True.  I could have converted those to `np.str_`.

> Using the np. prefix might make readers of the code think that these datatypes are different from Python's built-in ones, when in reality they are not.

Sorry, but you are mistaken.  They are different data types.  Whether you pass `bool` or `np.bool_` as your dtype argument, NumPy will convert it to the dtype `np.bool_` and the array it creates is based on its representation of Boolean values (maybe one byte per element)--and not Python's representation of Boolean values, which is a boxed object.  It is true that you can pass Python type names as synonyms, but the ultimate internal representation is NumPy dtypes.

**Review by bhack — APPROVED** [review]
For kokoro run

**Comment by gbaned** [comment]
@NeilGirdhar  Can you please check build failures. Thanks!

**Comment by NeilGirdhar** [comment]
@gbaned  Happy to.

The pylint error has nothing to do with this changelist, so I didn't think I should make that change in this changelog.  For some reason:
```python
      x = np.linspace(-np.e, np.e, num=1000, dtype=dtype)
```
doesn't like the `-np.e`.

The oneDNN CI fails some builds, which has nothing to do with this changelist since I only touched Python.  It also says that this test fails: "tensorflow/python/kernel_tests/linalg/sparse:conjugate_gradient_test".  I ran it on my machine and it works fine:

<details>
```
python tensorflow/python/kernel_tests/linalg/sparse/conjugate_gradient_test.py                                                                      ✔  4s  
Running tests under Python 3.9.5: /home/neil/.pyenv/versions/3.9.5/bin/python
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_10_staticshape_False
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_10_staticshape_False): 0.26s
I0706 14:58:00.242783 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_10_staticshape_False): 0.26s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_10_staticshape_False
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_10_staticshape_True
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_10_staticshape_True): 0.07s
I0706 14:58:00.313689 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_10_staticshape_True): 0.07s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_10_staticshape_True
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_1_staticshape_False
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_1_staticshape_False): 0.02s
I0706 14:58:00.329952 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_1_staticshape_False): 0.02s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_1_staticshape_False
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_1_staticshape_True
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_1_staticshape_True): 0.01s
I0706 14:58:00.344354 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_1_staticshape_True): 0.01s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_1_staticshape_True
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_4_staticshape_False
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_4_staticshape_False): 0.03s
I0706 14:58:00.375050 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_4_staticshape_False): 0.03s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_4_staticshape_False
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_4_staticshape_True
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_4_staticshape_True): 0.03s
I0706 14:58:00.406750 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_4_staticshape_True): 0.03s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat32_4_staticshape_True
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_10_staticshape_False
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_10_staticshape_False): 0.07s
I0706 14:58:00.474509 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_10_staticshape_False): 0.07s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_10_staticshape_False
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_10_staticshape_True
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_10_staticshape_True): 0.06s
I0706 14:58:00.538034 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_10_staticshape_True): 0.06s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_10_staticshape_True
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_1_staticshape_False
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_1_staticshape_False): 0.01s
I0706 14:58:00.552656 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_1_staticshape_False): 0.01s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_1_staticshape_False
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_1_staticshape_True
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_1_staticshape_True): 0.01s
I0706 14:58:00.566967 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_1_staticshape_True): 0.01s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_1_staticshape_True
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_4_staticshape_False
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_4_staticshape_False): 0.03s
I0706 14:58:00.599325 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_4_staticshape_False): 0.03s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_4_staticshape_False
[ RUN      ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_4_staticshape_True
INFO:tensorflow:time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_4_staticshape_True): 0.03s
I0706 14:58:00.629496 140491261256320 test_util.py:2102] time(__main__.ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_4_staticshape_True): 0.03s
[       OK ] ConjugateGradientTest.test_ConjugateGradient__test_conjugate_gradientfloat64_4_staticshape_True
[ RUN      ] ConjugateGradientTest.test_session
[  SKIPPED ] ConjugateGradientTest.test_session
----------------------------------------------------------------------
Ran 13 tests in 0.645s

OK (skipped=1)
```
</details>
The Internal CI is failing with
```
E   ModuleNotFoundError: No module named 'tensorflow.tools.api'
```
This is because you're missing an `__init__.py` file in that directory.  This should also be in a separate changelist.

**Comment by NeilGirdhar** [comment]
@gbaned Am I misinterpreting the errors?  What can I do to help this along?

**Comment by gbaned** [comment]
@kkimdev Can you please assist on above comments from @NeilGirdhar. Thanks!

**Comment by bhack** [comment]
@NeilGirdhar It is not so easy to reproduce exactly the Pylint CI environment locally. See my comment at https://github.com/tensorflow/tensorflow/pull/50133#issuecomment-856329703 about using the official TF devel docker image for the pylint github action.

**Comment by bhack** [comment]
@NeilGirdhar Can you try with `-np.reveal_type(np.e)` or `-float(np.e)`?

**Comment by bhack** [comment]
Also please check we had some API changes in random for `numpy.int64`:
https://source.cloud.google.com/results/invocations/9dec6c3d-bf74-4f8b-81d8-ffb6c1b4600a/targets/%2F%2Ftensorflow%2Ftools%2Fapi%2Ftests:api_compatibility_test/log

**Comment by NeilGirdhar** [comment]
@bhack sure I'll take a look now

**Comment by bhack** [comment]
Also please note that for the current Github linting action we don't set specific a specific numpy version so it is always running with the last stable available version (currently `numpy 1.21.0`):
https://github.com/tensorflow/tensorflow/blob/5ce6132701108cb6550d947927bf6fd373130c2f/.github/workflows/pylint-presubmit.yml#L44

**Comment by NeilGirdhar** [comment]
> Also please check we had some API changes in random for numpy.int64

Yes, that makes sense.  Can we update the default?  Should we just ignore the API change since NumPy will internally convert `int` to `np.int64` anyway.

**Comment by NeilGirdhar** [comment]
> @NeilGirdhar Can you try with -float(np.e)?

As soon I know how to test things locally, I'm happy.  It's weird that `-np.e` is failing, but `-np.euler_gamma` in the same file passes.  Also, that doesn't seem like a great solution.  It might be better to `# pylint: disable=` the problem until it's fixed by `NumPy` or `pylint`--not sure who's to blame.

**Comment by bhack** [comment]
> > @NeilGirdhar Can you try with -float(np.e)?
> 
> As soon I know how to test things locally, I'm happy to try that. It's weird that `-np.e` is failing, but `-np.euler_gamma` in the same file passes. Also, that doesn't seem like a great solution. It might be better to `# pylint: disable=` the problem until it's fixed by `NumPy` or `pylint`--not sure who's to blame.

Ok please add the inline ignore. 
As I told you we don't have a single to reproduce this locally as we are not running the pylint with the Docker image we distribute for developer or any officially distributed Docker image.

So please commit and we will run CI linting here on Github.

For the API change I think we need a quick check from @tensorflow/api-owners  /cc @mihaimaruseac

**Comment by NeilGirdhar** [comment]
> As I told you we don't have a single command to reproduce this locally as we are not running the pylint in the Docker image we distribute for developer or any other officially distributed Docker image.

Sorry, I didn't understand.  I don't have a lot of experience with Docker.

> Ok please add the inline ignore.

I will add the ignore and force push now.

**Review by bhack — APPROVED** [review]
Just for linting check

**Comment by bhack** [comment]
> Sorry, I didn't understand. I don't have a lot of experience with Docker.

In this context It is just a quick solution to have aligned environments (e.g. python , pylint, numpy versions etc..). 
If we run `pylint` here with the Github Action in the same Docker container that you can run on your machine we are on the same page and we could expect exactly the same results.

> I will add the ignore and force push now.

Ok please resolve also the conflict.

**Comment by NeilGirdhar** [comment]
(Done)

**Comment by bhack** [comment]
OK now pylint has green light. 
The problem is that we don't know what is fixed in 1.20 with this PR as the CI is not running with numpy 1.20.
See:
https://github.com/tensorflow/tensorflow/pull/48935
https://github.com/tensorflow/tensorflow/pull/48918

**Comment by NeilGirdhar** [comment]
@bhack Yes, I've been watching both of those PRs since they were submitted.  I'm not trying to make tensorflow compatible with 1.21 in this PR; I just want to resolve the warnings :smile:

**Comment by bhack** [comment]
What I meant is that the tests that are running now in the CI are just checking what is going wrong with numpy < 1.20.
They don't tell us anything about  you PR changes with numpy>=1.20 that is what your a solving locally on your env.

**Review by mihaimaruseac — COMMENTED** [review]
What is the earliest version of numpy that has these symbols?

What is the compatibility story? Will these get renamed again in a later numpy version?

**Comment by NeilGirdhar** [comment]
> What is the earliest version of numpy that has these symbols?

Looking at https://github.com/numpy/numpy/blob/main/numpy/core/numerictypes.py, these types have been in NumPy for at least 16 years.

> What is the compatibility story?

Good question.  This change will have no effect on people running older versions of NumPy that are compatible with TensorFlow.

> Will these get renamed again in a later numpy version?

I think that's _extremely_ unlikely to happen in the next decade.  But in the unlikely event that it does happen, there will be at least a few years of deprecation time, after which a similar search and replace would fix everything again.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Thank you. Just wanted to make sure.

**Pull request merged**
