### PR TITLE
fix backward compatible in delegate

### PR DESCRIPTION
**Pull request by arvinjhou**
Hi, 

This PR fix that not backward compatible after add new structure `TfLiteRegistrationExternal` in TfLiteRegistration once use delegate case

Please check the changes.

Regards
Arvin

### CODE REVIEW

**Review by Danailova — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @MeghnaNatraj Can you please review this PR ? Thank you!

**Comment by terryheo** [comment]
@arvinjhou thanks for your contribution. Could you share if this PR is still needed with ToT TFLite?
If yes, could you elaborate your issue?

**Comment by gbaned** [comment]
@arvinjhou Can you please check @terryheo's comments and resolve conflicts?. Thank you!

**Comment by gbaned** [comment]
Hi @arvinjhou Any update on this PR? and please resolve conflicts. Thank you!

**Comment by gbaned** [comment]
Hi @arvinjhou I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! thank you for your contribution.

**Comment by fergushenderson** [comment]
Just a brief comment on this issue: TF Lite has not promised binary backwards compatibility.
In particular for TFLiteRegistration, the structure was only documented as being "semi-ABI stable".
See the comment at the top of common.h:

```
// NOTE: The order of values in these structs are "semi-ABI stable". New values
// should be added only to the end of structs and never reordered.
```

So IMHO the proposed change in this issue should be considered as a feature request rather than a bug fix.

Also, I don't think the proposed patch would be sufficient to ensure binary backwards compatibility in all cases.
For example custom ops might not have version == 1.  Likewise for delegates not defined using SimpleDelegateInterface.
The patch also doesn't have any tests to ensure binary backwards compatibility would be preserved in the future.

**Pull request closed without merging**
