### PR TITLE
Branch 144490912

### PR DESCRIPTION
**Pull request by drpngx**
Includes:

144470919 (compiler opts)
144485165, and 144478254 (parallel concat / parallel stack)
144490912 i/o namespace in C++ API

### CODE REVIEW

**Comment by drpngx** [comment]
@petewarden `cc1plus: error: unrecognized argument in option '-march=native'` is that new?

**Comment by drpngx** [comment]
@petewarden NM, I think it's 144470919.

**Comment by gunan** [comment]
@martinwicke could you take a look?
@drpngx Would you like to fix internally first, or should we merge and then fix forward?

**Comment by drpngx** [comment]
I prefer to fix internally, but this adds latency maybe an hour or two of latency. I'm fine working late, up to you. Let's see if we have other failures while we are thinking of a fix.

**Comment by gunan** [comment]
however works best for you I can adjust, then let's close this, prepare a fix and prepare a new push?

**Comment by drpngx** [comment]
OK, closing. Not clear yet what the fix is.

**Pull request closed without merging**
