### PR TITLE
Add New Features and Enhance TensorFlow ConstOp Tests

### PR DESCRIPTION
**Pull request by sanowl**
## Overview
This pull request introduces several new features to the TensorFlow constant operation tests, enhancing the coverage and robustness of the tests. Key additions include tests for complex numbers, boolean values, large tensors, mixed data types, and range values.

### New Features
1. **Complex Numbers**: Added a test case to check the creation of tensors with complex numbers.
2. **Boolean Values**: Added a test case to verify the creation of tensors with boolean values.
3. **Large Tensor**: Added a test case to create and verify a large tensor.
4. **Mixed Data Types**: Added a test case to check behavior with mixed data types (should fail).
5. **Range Values**: Added a test case to create tensors from a range of values.

### Detailed Changes
- **Complex Numbers**: Ensured support for complex number tensors and verified with appropriate tests.
- **Boolean Values**: Verified the creation of boolean value tensors.
- **Large Tensor**: Tested the creation and validation of a large tensor to ensure performance and correctness.
- **Mixed Data Types**: Checked the behavior of tensors with mixed data types to ensure appropriate error handling.
- **Range Values**: Created tensors from a range of values to validate correct tensor generation.

### Impact
These enhancements improve the test coverage for TensorFlow's constant operations, ensuring more robust and comprehensive validation of tensor creation and handling.

## Testing
Tested the code with various constant definitions and inputs to ensure functionality remains intact. Verified that error handling works as expected for invalid inputs and mixed data types.

## Notes
- Ensure all dependencies are up-to-date to avoid compatibility issues.
- Review the added test cases to ensure they align with the intended usage and edge cases.

---

Please review the changes and let me know if there are any questions or further modifications needed.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @sanowl Can you please sign CLA? Thank you!

**Review by sagunb — APPROVED** [review]

**Comment by keerthanakadiri** [comment]
Hi @sanowl Can you please sign CLA? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @sanowl, Can you please sign CLA? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @sanowl, Can you please sign CLA? Thank you!

**Comment by gbaned** [comment]
Hi @sanowl I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen. Thank you for your contribution!

**Pull request closed without merging**
