### PR TITLE
added scope filtering to summaries.merge_all

### PR DESCRIPTION
**Pull request by m-smith**
I found a use for filtering the ops returned by `merge_all by scope`, so this request implements that change. You could also pass the collection to `merge`, but I thought this was a bit nicer.

### CODE REVIEW

**Comment by sb2nov** [comment]
Jenkins, test this please

**Comment by martinwicke** [comment]
You will have to rebuild the golden files, since this is an API change. See the failed logs for details.

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
ping @jart

**Comment by martinwicke** [comment]
I fixed the conflict so we can move this along (or not, depending on @jart's verdict).

**Review by jart — APPROVED** [review]
This seems to fit like a glove with the existing API so it's hard to say no. I would be curious to learn more about how this has been useful for you.

**Comment by martinwicke** [comment]
@m-smith, can you make sure all commits in this PR have the correct email attached (the same one that was used in the CLA)? I need that to be able to merge this.

**Comment by m-smith** [comment]
I think that all my commits already use the same email that I used for the CLA!

**Comment by drpngx** [comment]
@m-smith the first commit 30350cdc5785df745436d65175fb136676dd2a40 on Sep 26 appears to have failed the CLA. Could you check again?

**Comment by m-smith** [comment]
I'm pretty much 100% sure that I used the same email for all my commits! The one causing an issue has the wrong user name I think. But I'd have to rewrite the whole history in order to fix this...should I just redo the changes or is there a way to force the CLA?

**Comment by martinwicke** [comment]
Sorry, I did a merge for you. We can override the CLA, it's confused by this.

**Comment by drpngx** [comment]
@martinwicke @gunan Seems ready to merge. Please override the CLA.

**Comment by drpngx** [comment]
thanks!

**Pull request merged**
