### PR TITLE
WIP: BUG: fix inconsistent scope for `tensorflow.python.layers.base.Layer`

### LINKED ISSUE #13429: Name/variable scopes of tensorflow.python.layers.base.Layer
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem

This is a tiny code that creates layers and connects them in series.

```python
import tensorflow as tf
from tensorflow.python.layers.base import Layer


class A(Layer):
    def build(self, input_shape):
        self.v = self.add_variable('v', (), tf.float32)
        self.built = True
    
    def call(self, inputs):
        return self.v * inputs
    

# Case 1
with tf.Graph().as_default() as graph:
    x = tf.placeholder(tf.float32, (), 'x')
   
    out = x
    out = A()(out)
    out = A()(out)
    out = A()(out)
    
    tf.summary.FileWriter('/tmp/tensorboard/1', graph=graph).close()

# Case 2
with tf.Graph().as_default() as graph:
    x = tf.placeholder(tf.float32, (), 'x')
   
    out = x
    out = A(name='a')(out)
    out = A(name='a_1')(out)
    out = A(name='a_2')(out)
    
    tf.summary.FileWriter('/tmp/tensorboard/2', graph=graph).close()

# Case 3
with tf.Graph().as_default() as graph:
    x = tf.placeholder(tf.float32, (), 'x')
   
    out = x
    out = A(name='a_1')(out)
    out = A(name='a_2')(out)
    out = A(name='a_3')(out)
    
    tf.summary.FileWriter('/tmp/tensorboard/3', graph=graph).close()
```

#### Results

Other than case 3, an unexpected graph is generated.
Is this a bug?

- Case 1

result

- Case 2

result

- Case 3

result

### PR DESCRIPTION
**Pull request by facaiy**
It is proposed to fix #13429, however, I'm not sure whether it's the best solution. I'll finish the PR when I get back from holiday (next week).

### How to test

+ [ ] add test case.
+ [ ] pass all tests.

### CODE REVIEW

**Comment by frankchn** [comment]
Jenkins, test this please.

**Comment by frankchn** [comment]
@facaiy Can you rebase to master to resolve the conflict?

**Comment by lukaszkaiser** [comment]
Adding Eugene and Francois as they've been looking at Layers code more recently (I think I skipped some changes).

**Comment by facaiy** [comment]
Hi, @frankchn , it seems that master introduces a big change in `variable_scope.py`. I'll test nightly version. If bug still exists, I'll rebase master.

@lukaszkaiser The bug is reported on `tf.layer` at first, however, I find that it seems from a little mistake in `variable_scope`.

**Comment by lukaszkaiser** [comment]
Could you make a smaller PR that only changes `variable_scope` first? I'd much rather do it in a 2-step way, as these changes can break things in a subtle way and it can be hard to figure out what broke what.

**Comment by facaiy** [comment]
The case is more subtle than I expected, so let's close the PR now and go to #13429 for discuss. I'll reopen the PR until the best solution is found.

**Pull request closed without merging**
