### PR TITLE
Update beam_search_decoder.py

### PR DESCRIPTION
**Pull request by georgesterpu**
#22172 
probably not the neatest way to update my previous pull request...

### CODE REVIEW

**Comment by harshini-gadige** [comment]
@ebrevdo  Did you get a chance to look into this ?

**Comment by harshini-gadige** [comment]
@georgesterpu  Please sign the CLA in order to proceed looking into this PR.

**Review by ebrevdo — APPROVED** [review]
LGTM; thanks!

**Comment by harshini-gadige** [comment]
@ebrevdo  -  I think we need to wait until the user signs a CLA to proceed.

**Comment by ebrevdo** [comment]
Sure; I guess I thought George had written one.  Thanks!

**Comment by georgesterpu** [comment]
Hello,
I just signed the CLA with my university email, although gmail is listed as the primary one on GitHub, fingers crossed.

**Comment by georgesterpu** [comment]
Hi. Is the problem still on my side ?

**Comment by harshini-gadige** [comment]
> Hi. Is the problem still on my side ?

Thanks for signing CLA. We are looking into the PR.

**Pull request merged**
