### PR TITLE
[INTEL MKL] Fix Error Loading Package @io_bazel_rules_docker

### LINKED ISSUE #28824: Error Loading Package @io_bazel_rules_docker when building Tensorflow
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.12.2 / master branch
- Python version: Python 3.6.8 :: Anaconda, Inc.
- Installed using virtualenv? pip? conda?: Conda
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): gcc version 8.2.0 (Rev3, Built by MSYS2 project)
- CUDA/cuDNN version: Cuda v10.1 - cudnn-9.2-windows10-x64-v7.5.1.10
- GPU model and memory: NVidia 1060

**Describe the problem**
Build failing when running `bazel build --config=opt //tools/pip_package:build_pip_package`
with error:
```
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories'
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed the tutorial here: https://medium.com/@amsokol.com/how-to-build-and-install-tensorflow-gpu-cpu-for-windows-from-source-code-using-bazel-d047d9342b44

```
> python configure.py
Python Location (default): C:\Users\Arise\Miniconda3\envs\tensorflow-v1.10\python.exe
Python Libraries Path (default): C:\Users\Arise\Miniconda3\envs\tensorflow-v1.10\lib\site-packages
XLA JIT support: No
ROCm support: No
CUDA support: Yes
CUDA compute capabilities (default): 3.5,7.0
Optimization Flags Bazel (default): --config=opt
Override Eigen Strong Inline (default): Yes
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
(tensorflow-v1.10) C:\Users\Arise\tensorflow-build\tensorflow>bazel build
Starting local Bazel server and connecting to it...
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
INFO: An error occurred during the fetch of repository 'io_bazel_rules_docker'
INFO: Call stack for the definition of repository 'io_bazel_rules_docker':
 - C:/users/arise/_bazel_arise/ji3ak47x/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - C:/users/arise/tensorflow-build/tensorflow/WORKSPACE:29:1
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "C:/users/arise/_bazel_arise/ji3ak47x/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/arise/_bazel_arise/ji3ak47x/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd C:/users/arise/_bazel_arise/ji3ak47x/external
+ rm -rf C:/users/arise/_bazel_arise/ji3ak47x/external/io_bazel_rules_docker C:/users/arise/_bazel_arise/ji3ak47x/external/io_bazel_rules_docker
/usr/bin/bash: line 5: rm: command not found
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "C:/users/arise/_bazel_arise/ji3ak47x/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/arise/_bazel_arise/ji3ak47x/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd C:/users/arise/_bazel_arise/ji3ak47x/external
+ rm -rf C:/users/arise/_bazel_arise/ji3ak47x/external/io_bazel_rules_docker C:/users/arise/_bazel_arise/ji3ak47x/external/io_bazel_rules_docker
/usr/bin/bash: line 5: rm: command not found
INFO: Elapsed time: 2.642s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### PR DESCRIPTION
**Pull request by ashahba**
Upgrade to latest `bazel_rules v0.7.0` to Fix #28824

### CODE REVIEW

**Comment by angersson** [comment]
@pcloudy, Is this one of Bazel's normally-automatically-loaded packages? I'm not sure this should be locked in to this version, but I'm also uncertain why the linked Issue failed to build (does our CI not catch something?).

**Comment by xinan-jiang** [comment]
@angersson, I also met the same problem in docker. this package is just need in docker.

**Comment by angersson** [comment]
@xinan-jiang, can you provide more details, please, preferably on the original issue? I'd like to understand this issue better before accepting any patches. There's a useful text template you can use here: https://github.com/tensorflow/tensorflow/issues/new (but you don't need to create a new issue; it would be a duplicate of #28824 )

**Comment by gbaned** [comment]
@ashahba Did you get a chance to look on reviewer comments? Please let us know on the update. Thanks!

**Comment by ashahba** [comment]
@gbaned thanks for looking into this issue.
I'll find sometime in the next couple of days to get more details on this.

Stay tuned please 🙂

**Comment by ashahba** [comment]
@gbaned looks like I'm no longer able to reproduce this one.
So the PR doesn't seem to be needed anymore.

**Pull request closed without merging**
