### PR TITLE
Merge r0.12 back into master

### PR DESCRIPTION
**Pull request by gunan**
There were some documentation conflicts, but I reran gen_docs.sh to fix those.

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]

**Comment by gunan** [comment]
@mrry I also reverted b5e6d667d28f8dd1ea21ed428fa560b0d4720afa in master, it looks like we now moved set_ops into core?

**Comment by martinwicke** [comment]
We have, as part of the layers move.

**Comment by gunan** [comment]
Jenkins, test this please.
Macos tests timed out in this run:
https://ci.tensorflow.org/job/tensorflow-pull-requests-multijob/3061/

**Comment by gunan** [comment]
all tests pass!

CLA ok since it is a merge PR.

**Pull request merged**
