### PR TITLE
macOS doesn't have wget

### PR DESCRIPTION
**Pull request by dmaclach**
Make building easier on macOS by using curl instead of wget
because wget isn't part of macOS, and wget installed from
brew has trouble resolving certificates appropriately.

### CODE REVIEW

**Review by aselle — APPROVED** [review]

**Comment by yifeif** [comment]
Thanks @dmaclach! Do you mind also resolving the conflicts?

**Comment by drpngx** [comment]
@dmaclach any luck with pull rebase and push?

**Comment by caisq** [comment]
ping @dmaclach?

**Comment by gunan** [comment]
Looks like the issue was already fixed for contrib/lite/download_dependencies.
reverted changes to that file, and we can either move forward with this PR, or just copy the changes under contrib/lite to contrib makefile.

**Pull request merged**
