### PR TITLE
Feature requested by issues 18354: No gradient defined for operation DepthwiseConv2dNativeBackpropFilter

### PR DESCRIPTION
**Pull request by jony0917**
Feature requested by issues 18354: No gradient defined for operation DepthwiseConv2dNativeBackpropFilter

### CODE REVIEW

**Comment by reedwm** [comment]
Not super familiar with depthwise convolutions. @chsigg, can you review?

**Comment by jony0917** [comment]
Ok,thanks

**Comment by ppwwyyxx** [comment]
Is there a follow up of this PR?

**Comment by veqtor** [comment]
Also would really like 2nd order grads for these!

**Comment by reedwm** [comment]
It looks  functionality of this PR was merged in 6d96cc4d05fd09e5663853a795bcd9a5b01f1732.

**Comment by veqtor** [comment]
Right, but I'm still getting this error on 1.13.1, I fixed it by adding this code to __init__.py in a project where I needed second order gradients:

`@ops.RegisterGradient("DepthwiseConv2dNativeBackpropInput")
def _DepthwiseConv2DNativeBackpropInputGrad(op, grad):
  """The derivatives for depth-wise deconvolution.
  Args:
    op: the depth-wise deconvolution op.
    grad: the tensor representing the gradient w.r.t. the output
  Returns:
    the gradients w.r.t. the input and the filter
  """
  return [None,
          nn_ops.depthwise_conv2d_native_backprop_filter(
              grad,
              array_ops.shape(op.inputs[1]),
              op.inputs[2],
              op.get_attr("strides"),
              op.get_attr("padding"),
              data_format=op.get_attr("data_format")),
          nn_ops.depthwise_conv2d_native(
              grad,
              op.inputs[1],
              op.get_attr("strides"),
              op.get_attr("padding"),
              data_format=op.get_attr("data_format"))]`

I know this makes very little sense, but for some reason this PR, while merged, must have regressed recently, could op renaming for v2 be the culprit?

These ops really need tests for 2nd order grads so these regression do not happen so frequently.

**Comment by reedwm** [comment]
The commit didn't make it into 1.13.1, but will be in the next stable release. The commit was merged in 5da4b304fad211a4191a59f6cba64c5330329ff4, which was merged too late to be in 1.13.

**Pull request closed without merging**
