### PR TITLE
Added TF.Learn white paper links and citation

### PR DESCRIPTION
**Pull request by terrytangyuan**
cc: @martinwicke @ilblackdragon

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@tensorflow-jenkins Test this please

**Review by martinwicke — APPROVED** [review]

**Comment by terrytangyuan** [comment]
@martinwicke Thanks. Just for my curiosity - will the actual change on website come from automated internal commit?

**Comment by martinwicke** [comment]
Not automated, but the website is built (manually, but regularly) from github.

**Comment by terrytangyuan** [comment]
Got it. Thanks.

**Pull request merged**
