### PR TITLE
[INTEL oneDNN] Upgrade pip version 

### PR DESCRIPTION
**Pull request by justkw**
Upgrade pip version in mkl docker file

### CODE REVIEW

**Comment by shwetaoj** [comment]
@googlebot I consent

**Comment by gbaned** [comment]
@angerson, @penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@angerson, @penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@angerson, @penpornk Can you please review this PR ? Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by justkw** [comment]
no longer need.  Close.

**Comment by justkw** [comment]
no longer needed.

**Pull request closed without merging**
