### PR TITLE
Fixing typo in default_name argument for name_scope

### PR DESCRIPTION
**Pull request by raphael-sch**
Looks like a typo to me and I think this could lead to unexpected behavior.

### CODE REVIEW

**Comment by raphael-sch** [comment]
I signed it!

**Comment by drpngx** [comment]
@ebrevdo any opinion here?

**Comment by sb2nov** [comment]
@ebrevdo ping

**Review by ebrevdo — APPROVED** [review]

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Pull request merged**
