### PR TITLE
Move CMSIS downloads to a separate script.

### LINKED ISSUE #46020: Common location for portable bash helper functions / aliases
@tensorflow/micro

PR #46011 fixes the use of `md5sum` to be compatible with a Mac. We are already using `md5sum` in additional places too.

While we should get #46011 merged, it would be better to have a common location for these helper functions / aliases.

I can imagine collecting these into a common helper script (for example `micro/tools/bash_helpers.sh`) and have something like:

```bash

UNAME_S=`uname -s`

if [ UNAME_S == Linux]; then
  alias tflm_md5sum='md5sum'
else if [ UNAME_S == Darwin ]; then
  alias tflm_md5sum='md5 -r'
fi

```

We would then need to change the different download scripts to determine the directory in which the script lives, something like: https://github.com/tensorflow/tensorflow/blob/59f5abfbc8dc5559c361f80f4fa4a006db825e40/tensorflow/lite/micro/tools/ci_build/test_bluepill.sh#L21-L23

and then have
```bash
source tensorflow/lite/micro/tools/bash_helper.sh
```

### PR DESCRIPTION
**Pull request by advaitjain**
This is a first step towards adding back some of the CMSIS patching needed to fix the Arduino build (http://b/175435756).

Moving to a stand-alone download script is part of the cleanup described in http://b/143904317

Also, this change introduces a common location for helper functions and fixes #46020

### CODE REVIEW

**Review by mansnils — APPROVED** [review]
Looks good. Just curious about the broken Arduino build (didn't know it was broken)? I am not able to access the link (http://b/175435756).

**Review by mansnils — CHANGES_REQUESTED** [review]
On second thought, could you also update tensorflow/lite/micro/tools/make/ext_libs/ethosu.inc?

**Comment by advaitjain** [comment]
> Looks good. Just curious about the broken Arduino build (didn't know it was broken)? I am not able to access the link (http://b/175435756).

Turns out that that was something specific to Pete's setup: https://github.com/arduino/Arduino/issues/11141

I'll still plan on merging this change since we do want to decentralize the download logic.

**Comment by advaitjain** [comment]
> On second thought, could you also update tensorflow/lite/micro/tools/make/ext_libs/ethosu.inc?

done.

**Pull request merged**
