### PR TITLE
Update variables.py

### PR DESCRIPTION
**Pull request by alanyee**
Added deprecated message

### CODE REVIEW

**Comment by alanyee** [comment]
I have been looking at the core training framework. It seems that the other functions such as `get_global_step` are also deprecated. Should I add the deprecated comments for them too?

**Comment by rmlarsen** [comment]
@martinwicke should we add deprecation statements for all these function?

**Comment by martinwicke** [comment]
Yes. For every function for which a direct equivalent exists outside of contrib, we should deprecate the contrib version.

Please (also in this PR) set the date to `None`. Timelines confuse people, especially if they're in the past.

This may lead to spurious warnings, which we'll have to fight with the `with deprecation.silence` decorator, but we can do that in a follow-up.

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
