### PR TITLE
common global variable with constant.py

### PR DESCRIPTION
**Pull request by rajendraarora16**
Made a common `constant.py` for global commonly used variables.

### CODE REVIEW

**Comment by rajendraarora16** [comment]
Have deleted forked repo and again facing CLA issues. Help needed!

**Comment by rmlarsen** [comment]
@martinwicke @vrv can you help here?

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@gunan do you have any experience resolving these CLA issues? I'm not sure what's going on.

**Comment by gunan** [comment]
I think the issue is github cannot detect the original repository:
`tensorflow:master from unknown repository`
Thus CLA check is getting confused?

**Comment by rmlarsen** [comment]
@gunan oh, I see. @rajendraarora16 what repository are you pusing from?

**Comment by jhseu** [comment]
@rajendraarora16 mind remaking this pull request from a public repo? Closing for now.

**Pull request closed without merging**
