### PR TITLE
Adding missing close parenthesis in code listing.

### PR DESCRIPTION
**Pull request by sandersk**
Fixing code syntax error that is already corrected in 1.0 and master branches.

### CODE REVIEW

**Comment by maciekcc** [comment]
Closing, duplicate PR.

**Comment by sandersk** [comment]
@maciekcc, did you close because it's a duplicate of #7828? I made 2 separate PRs: one to merge this fix into the r0.11 branch (this one) and one to merge this fix into the r0.12 branch (#7828), so that the tutorial doc will be correct in both API versions on tf.org.

**Comment by maciekcc** [comment]
Oh, sorry, didn't notice :/

**Review by maciekcc — APPROVED** [review]

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
The test failures are due to some buildifier changes between r0.11 and now and are unrelated to the doc-only changes in this PR. Merging PR now.

**Pull request merged**
