### PR TITLE
[oneDNN] pooling fix

### PR DESCRIPTION
**Pull request by Srini511**
This PR fixes empty input/grad tensor for AvgpoolingGrad V1 (it is already fixed for v2), by providing an empty tensor allocation. We also align the o/p values with the eigen implementation.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Review by penpornk — APPROVED** [review]
Thank you for the fix and sorry for the delay!

**Comment by penpornk** [comment]
@Srini511 Could you please help resolve merge conflicts?

**Comment by penpornk** [comment]
@Srini511 Thank you for the quick reply! It seems the auto-importer malfunctioned. I'll try importing this PR manually.

**Pull request merged**
