### PR TITLE
[CMake] Fix support for custom kernels in `tf.contrib.metrics`.

### LINKED ISSUE #6115: [Windows] How can we call builtin ops function in Windows like _set_ops.dense_to_dense_set_operation?
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
http://stackoverflow.com/questions/40947669/attributeerror-nonetype-object-has-no-attribute-dense-to-dense-set-operation

Operating System: Windows

Installed version of CUDA and cuDNN: 
 ```
Directory of C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

12/02/2016  02:50 PM    <DIR>          .
12/02/2016  02:50 PM    <DIR>          ..
09/11/2016  10:26 AM            93,804 cublas.lib
09/11/2016  10:19 AM        62,239,924 cublas_device.lib
09/05/2016  02:51 PM            87,834 cuda.lib
09/05/2016  02:51 PM           681,064 cudadevrt.lib
09/05/2016  02:51 PM            64,550 cudart.lib
09/05/2016  02:51 PM         2,318,456 cudart_static.lib
07/26/2016  11:31 PM            37,452 cudnn.lib
09/05/2016  02:51 PM            17,042 cufft.lib
09/05/2016  02:51 PM            15,838 cufftw.lib
09/05/2016  02:51 PM             8,534 curand.lib
09/05/2016  02:51 PM           115,226 cusolver.lib
09/05/2016  02:51 PM           175,020 cusparse.lib
09/05/2016  02:51 PM             4,746 nppc.lib
09/05/2016  02:51 PM         1,312,172 nppi.lib
09/05/2016  02:51 PM           202,098 nppial.lib
09/05/2016  02:51 PM           102,322 nppicc.lib
09/05/2016  02:51 PM             9,324 nppicom.lib
09/05/2016  02:51 PM           176,272 nppidei.lib
09/05/2016  02:51 PM           244,310 nppif.lib
09/05/2016  02:51 PM            73,428 nppig.lib
09/05/2016  02:51 PM            25,078 nppim.lib
09/05/2016  02:51 PM           441,650 nppist.lib
09/05/2016  02:51 PM             8,416 nppisu.lib
09/05/2016  02:51 PM            55,026 nppitc.lib
09/05/2016  02:51 PM           214,486 npps.lib
09/05/2016  02:51 PM            11,250 nvblas.lib
09/05/2016  02:51 PM             6,814 nvcuvid.lib
09/05/2016  02:51 PM             8,720 nvgraph.lib
09/05/2016  02:51 PM            40,096 nvml.lib
09/05/2016  02:51 PM             3,954 nvrtc.lib
09/05/2016  02:51 PM            23,076 OpenCL.lib
              31 File(s)     68,817,982 bytes
               2 Dir(s)  206,249,398,272 bytes free
```

If installed from binary pip package, provide:

1. A link to the pip package you installed:
https://github.com/tensorflow/tensorflow.git

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
(tensorflow) C:\Users\e-budur>python -c "import tensorflow; print(tensorflow.__v
ersion__)"
I c:\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opene
d CUDA library cublas64_80.dll locally
I c:\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opene
d CUDA library cudnn64_5.dll locally
I c:\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opene
d CUDA library cufft64_80.dll locally
I c:\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opene
d CUDA library nvcuda.dll locally
I c:\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opene
d CUDA library curand64_80.dll locally
0.12.head
```

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
C:\tensorflow>git rev-parse HEAD
778539ce3cb4a0effabe46e7674c22602cb08dc0

2. The output of `bazel version`
I've used MSBuild.

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
`true_positives = set_ops.set_intersection(predictions_idx, labels)`

I've run udc_train.py by following the preliminary steps give in the repository page https://github.com/dennybritz/chatbot-retrieval.  As a result of the execution I got the following exception when the application calls the function tf.contrib.metrics.streaming_sparse_recall_at_k in udc_metrics.py

### What other attempted solutions have you tried?
I've rebuilded the source code by following the instruction in the following link hoping that the ops library will be compiled and embedded into the main excutable of tensorflow like '_pywrap_tensorflow.pyd' but no luck.  I kept receiving the same error after successful compilation and deployment of the latest source code (778539ce3cb4a0effabe46e7674c22602cb08dc0).
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md

I've posted the question on Stackoverflow but I got no answer.
http://stackoverflow.com/questions/40947669/attributeerror-nonetype-object-has-no-attribute-dense-to-dense-set-operation

### Logs or other output that would be helpful
I've downloaded the sample project Chatbot Retrieval from the following repository
https://github.com/dennybritz/chatbot-retrieval

I've run udc_train.py by following the preliminary steps give in the repository page above.  As a result of the execution I got the following exception when the application calls the function tf.contrib.metrics.streaming_sparse_recall_at_k

```
Traceback (most recent call last):
  File "C:/Users/e-budur/PycharmProjects/chatbot-retrieval/udc_train.py", line 72, in <module>
    tf.app.run()
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:/Users/e-budur/PycharmProjects/chatbot-retrieval/udc_train.py", line 68, in main
    estimator.fit(input_fn=input_fn_train, steps=None, monitors=[eval_monitor])
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 247, in new_func
    return func(*args, **kwargs)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 364, in fit
    max_steps=max_steps)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 741, in _train_model
    max_steps=max_steps)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\graph_actions.py", line 301, in _monitored_train
    None)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 473, in run
    run_metadata=run_metadata)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 628, in run
    run_metadata=run_metadata)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 595, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 737, in run
    run_metadata=run_metadata))
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\monitors.py", line 1210, in after_run
    induce_stop = m.step_end(self._last_step, result)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\monitors.py", line 409, in step_end
    return self.every_n_step_end(step, output)
  File "C:/Users/e-budur/PycharmProjects/chatbot-retrieval/udc_train.py", line 65, in every_n_step_end
    steps=None)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 247, in new_func
    return func(*args, **kwargs)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 436, in evaluate
    name=name)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 800, in _evaluate_model
    eval_ops = self._get_eval_ops(features, labels, metrics)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1111, in _get_eval_ops
    metrics, features, labels, model_fn_ops.predictions))
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 280, in _make_metrics_ops
    result[name] = metric(predictions, labels_tensor_or_dict)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\metrics\python\ops\metric_ops.py", line 1422, in streaming_sparse_recall_at_k
    weights=weights)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\metrics\python\ops\metric_ops.py", line 2102, in _streaming_sparse_true_positive_at_k
    weights=weights)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\metrics\python\ops\metric_ops.py", line 2054, in _sparse_true_positive_at_k
    tp = set_ops.set_size(set_ops.set_intersection(predictions_idx, labels))
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\metrics\python\ops\set_ops.py", line 138, in set_intersection
    return _set_operation(a, b, "intersection", validate_indices)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\metrics\python\ops\set_ops.py", line 113, in _set_operation
    indices, values, shape = _set_ops.dense_to_dense_set_operation(
AttributeError: 'NoneType' object has no attribute 'dense_to_dense_set_operation'
```

The main problem turns out to be loader.load_op_library fails to load .so files in NT system.

```
_set_ops = loader.load_op_library(resource_loader.get_path_to_datafile("_set_ops.so"))

indices, values, shape = _set_ops.dense_to_dense_set_operation(
        a, b, set_operation, validate_indices) #_set_ops turns out to be None
```

```
def load_op_library(path):
  """Loads a contrib op library from the given path.

  NOTE(mrry): On Windows, we currently assume that contrib op
  libraries are statically linked into the main TensorFlow Python
  extension DLL.

  Args:
    path: An absolute path to a shared object file.

  Returns:
    A Python module containing the Python wrappers for Ops defined in the
    plugin.
  """
  if os.name != 'nt':
    path = resource_loader.get_path_to_datafile(path)
    ret = load_library.load_op_library(path)
    assert ret, 'Could not load %s' % path
    return ret
  else:
    # NOTE(mrry):
    return None
```
The comments belongs to @mrry 

Hence the question is : How can we call builtin ops function in Windows like _set_ops.dense_to_dense_set_operation?

Thanks

### PR DESCRIPTION
**Pull request by mrry**
Fixes #6115.

### CODE REVIEW

**Comment by mrry** [comment]
Looks like a flake on the Linux GPU tests.

@yifeif I'm not sure if the window has closed for r0.12 cherry picks, but it'd be nice to get this bug fix in as well....

**Comment by gunan** [comment]
E tensorflow/stream_executor/cuda/cuda_blas.cc:372] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support

This one is all new. We can cherrypick, but I would feel safer rerunning the tests once more.
Jenkins, test this please.

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Oh for crying out loud, I wanted gpu tests to rerun and they failed to download dependencies.

**Comment by gunan** [comment]
Jenkins, test this please.

**Pull request merged**
