### PR TITLE
Add tf.print an an alias for tf.Print

### LINKED ISSUE #18053: Lowercase tf.print when print is a function?
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: n/a
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: n/a
- **TensorFlow installed from (source or binary)**: n/a
- **TensorFlow version (use command below)**: n/a
- **Python version**: n/a
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

### Describe the problem
Since TensorFlow must be compatible with Python 2.7, `tf.Print` is uppercase.  However, `tf.print` would work fine for Python 3 users and Python 2 users with `from __future__ import print_function`?  There's no difficulty adding this to the source, since all TensorFlow source files have `from __future__ import print_function`, and it wouldn't interfere with any other 2.7 users.

Objections to me adding?

### PR DESCRIPTION
**Pull request by girving**
Users with Python 3 or `from __future__ import print_function` can now
use lowercase `tf.print`.

Fixes #18053.

### CODE REVIEW

**Comment by girving** [comment]
Wow, have I really not signed the CLA before? :)

**Comment by girving** [comment]
I signed it!

**Comment by girving** [comment]
Note: I haven't added any tests for this, since I was unsure what the correct protocol is these days for tests about the toplevel `tensorflow` module.

**Comment by girving** [comment]
Huh, the `api_compatibility_test` is failing, and that's probably related to this:

    >>> tf.keras.datasets.boston_housing.print_function
    _Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 65536)

That file has some very strange lines.  Why would one need to `del print_function`? 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/datasets/boston_housing/__init__.py#L25

**Comment by girving** [comment]
The `api_compatibility_test` passes for me since I'm on Python 3, so updating the goldens has no effect.  I could try to do it on 2, but I'm leery of any situation where the goldens are generated differently with different versions of Python.

**Comment by girving** [comment]
The easy fix would to be make the `api_compatibility_test` simply ignore `print_function`, but it seems weird to have to do this.  And I already don't understand why `keras` has those del lines.

**Comment by fchollet** [comment]
For a long time, the following pattern has been standard in TF for files that were used for exporting API keywords:

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from blah import keywords

del absolute_import
del division
del print_function
```

This is no longer the case since API export now relies on decorators. @annarev, what should we do with existing files using the above pattern?

**Comment by asimshankar** [comment]
(Okay for API change)

**Comment by annarev** [comment]
create_python_api.py script generates __init__.py files that define TensorFlow API.
Currently, we don't have print_function included in these files because it is not a part of TensorFlow API.

What is the usecase for having print_function available in TensorFlow API? Can users of TensorFlow API just import it before tensorflow?

**Comment by girving** [comment]
I think I figured out what was happening with the API.  Commit updated.

**Comment by girving** [comment]
Jenkins, test this please.  (Curious if I still have permission to do that.)

**Comment by girving** [comment]
Oh, I see: the `api_compatibility_test` is just skipped in Python 3.  That would explain why it is passing for me, and why the goldens don't update.  Golden update coming up.

**Comment by girving** [comment]
Golden update done.

**Comment by girving** [comment]
The failing `Ubuntu CC` tests appear unrelated.

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@girving I can't see what's failing either :-(

**Comment by girving** [comment]
Ooh, all green!  Shall I merge?  Not sure I'm supposed to do that as a Xoogler.

**Comment by rmlarsen** [comment]
Merged. Thanks, Geoffrey.

**Pull request merged**
