### PR TITLE
Fix discrepancy between tf.io.gfile.mkdir and os.mkdir's created mode

### LINKED ISSUE #32963: tf.io.gfile.mkdir restricts directory mode/(permissions)
**System information**

-  Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: v1.14.0-rc1-22-gaf24dc9 1.14.0
- Python version: 3.6

**Describe the current behavior**
Directories created with `tf.io.gfile.mkdir()` on Linux does not have the w mode bit set for group and other even if allowed by the umask and ACL.

**Describe the expected behavior**
Directories created with `tf.io.gfile.mkdir` should have the maximum permissions allowed by the umask and ACL, which is the way `os.mkdir()` in Python works.
I think this behavior is caused by the fact that [TF always calls mkdir with mode 0755](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/core/platform/posix/posix_file_system.cc#L281) while  [Python calls mkdir with mode 511 (= 777 in octal)](https://github.com/python/cpython/blob/3.7/Modules/clinic/posixmodule.c.h#L1094) if no mode is given .

**Code to reproduce the issue**

```
import tensorflow as tf
import stat
import os

os.umask(0000)

tf_dir = "test1"
os_dir = "test2"

tf.io.gfile.mkdir(tf_dir)
tf_mode = os.stat(tf_dir).st_mode

os.mkdir(os_dir)
os_mode = os.stat(os_dir).st_mode

if (tf_mode != os_mode):
    print("File mode differs:")
    print("TF: {}, OS: {}".format(stat.filemode(tf_mode), stat.filemode(os_mode)))

```

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #32963 where the modes of the directory created between tf.io.gfile.mkdir and os.mkdir are different (one is 0777 and another is 0755).

This fix fixes the issue.

This fix fixes #32963.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
This test fails internally

```
Traceback (most recent call last):
  File ".../absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File ".../absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File ".../tensorflow/python/lib/io/file_io_test.py", line 634, in testCreateDirMode
    self.assertEqual(tf_mode, os_mode)
AssertionError: 17407 != 16895
```

**Comment by mihaimaruseac** [comment]
I will have a fix on the internal infrastructure and then revisit this and get it merged.

**Comment by yongtang** [comment]
Thanks @mihaimaruseac 👍 for the update , let me know if there is anything I could help.

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please.

**Comment by mihaimaruseac** [comment]
I think we need to wait for 2 other internal changes to land first but they keep getting delayed.

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by mihaimaruseac** [comment]
Unfortunately the differences between Google and external POSIX filesystem are harded than anticipated, so this will have to wait until after modular filesystems land :(

**Comment by gbaned** [comment]
@yongtang Can you please resolve conflicts? Thanks!

**Comment by mihaimaruseac** [comment]
Well, it's too early to fix conflicts as we cannot yet merge this due to large differences between internal and external file system :-/

**Comment by yongtang** [comment]
Thanks @mihaimaruseac @gbaned, let me when it is ready to move forward.

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by mihaimaruseac** [comment]
> Unfortunately the differences between Google and external POSIX filesystem are harded than anticipated, so this will have to wait until after modular filesystems land :(

This is still the case unfortunately.

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by mihaimaruseac** [comment]
Same as before unfortunately.

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR, please. Thank you!

**Comment by mihaimaruseac** [comment]
No longer working in TF.

**Comment by gbaned** [comment]
Hi @sagunb Can you please review this PR ? Thank you!

**Comment by sagunb** [comment]
Could you try syncing to head please, it looks like there are some conflicts.

**Comment by gbaned** [comment]
Hi @yongtang Can you please resolve conflicts? Thank you!

**Comment by mihaimaruseac** [comment]
Same as https://github.com/tensorflow/tensorflow/pull/42138#issuecomment-1351961713

**Comment by mihaimaruseac** [comment]
Closing stale PR. Should be reopened when modular filesystem is fully implemented.

**Pull request closed without merging**
