### PR TITLE
MKL: Adding MKL-DNN Identity op

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**

### CODE REVIEW

**Review by andydavis1 — APPROVED** [review]

**Comment by andydavis1** [comment]
@tensorflow-jenkins test this please.

**Comment by claynerobison** [comment]
What is the Ubuntu CC test that is preventing this PR from merging? It appears to be a Google Internal check. AFAICT none of these errors are related to the changes in this PR. Please merge.

**Comment by gunan** [comment]
Ubuntu CC runs the tests on our new test infra. I will need them to pass before I can make sure our releases wont be negatively affected.
I will try to watch these builds and get the change merged.

**Comment by claynerobison** [comment]
@gunan Anything we can do on our side to make your life easier with all these MKL PRs?

**Comment by gunan** [comment]
Not really, we had a few bugs in the CI stack that made tests fail for unrelated reasons.  This week they are under control, so the merge is much better than it was last week.

**Pull request merged**
