### PR TITLE
Make TensorFlow Lite library for Android target

### PR DESCRIPTION
**Pull request by yesmung**
You can compile Tensorflow Lite library using Makefile.
It is possible to compile both static and shared library
excluding benchmark tools.

For more details, see android.md in tensorflow/contrib/lite/g3doc/

Signed-off-by: MyungSung Kwak <yesmung@gmail.com>

### CODE REVIEW

**Comment by yesmung** [comment]
@martinwicke, petewarden

Hello, 

I want to contribute this request to master branch.
It is a bit different from the related my request #18631  
Please review & merge as process.

Thanks.

**Comment by yesmung** [comment]
@petewarden , @aselle 
Hello, 
I have resolved the conflict with the current master branch.
Please let me know the progress of review.

**Comment by yesmung** [comment]
Is there any update?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yesmung** [comment]
@pineking
Sorry for late response.
Sure, you can use this commit.
Would you explain PR work?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by achowdhery** [comment]
@yesmung have you tried the latest Android target of TensorFlow Lite? This issue is already resolved at head. Thanks

**Comment by petewarden** [comment]
Closing, since this is already resolved.

**Pull request closed without merging**
