### PR TITLE
Branch 198811639

### PR DESCRIPTION
**Pull request by case540**

### CODE REVIEW

**Comment by case540** [comment]
There were merge conflicts with this pull in...

tensorflow/tools/api/generator/create_python_api.py  
tensorflow/tools/api/generator/BUILD

I think I resolved them properly.

**Review by av8ramit — DISMISSED** [review]

**Comment by av8ramit** [comment]
Thanks @case540

**Comment by case540** [comment]
Really not sure about changes to the layout_optimizer_test.py. Trying to figure out what caused them now.

Here is potential test fix, but I just changed test to pass. Not sure what caused the difference to the Add op name.
https://github.com/tensorflow/tensorflow/pull/19680/commits/1acaca5c2b033f2d51f7d2e97da0511b04420f1d

**Comment by case540** [comment]
+ @zhangyaobit to confirm changes to layout_optimizer_test.py are sensible

**Review by yifeif — APPROVED** [review]

**Pull request merged**
