### PR TITLE
Add note to new op and source build doc (#6473)

### PR DESCRIPTION
**Pull request by MircoT**
As seen in #6473 issue topic I want to suggest this two little changes to the documentation.

### CODE REVIEW

**Comment by MircoT** [comment]
I signed it!

**Comment by rmlarsen** [comment]
@keveman does this look OK to you?

**Review by keveman — APPROVED** [review]

**Comment by vrv** [comment]
@MircoT unfortunately our docs are undergoing a reorganization -- can I ask you to wait until the new docs are available so you can make the same changes there?  Thanks!

Will mark this as stalled until then.

**Comment by MircoT** [comment]
@vrv no problem for me. I'll take this as a note to do the changes later. 

Sorry but do you mean with the new version of the library, or before that?

**Comment by vrv** [comment]
I think the docs are being moved around and such, so these edits would get lost in the translation (which got snapshotted last week), so I've been asked to tell people to hold off until the new files are checked in, and then you can make these changes in the new locations.

**Comment by MircoT** [comment]
@vrv thanks for the response. I'll do again the pull request adjusting it after the changes of the documentation.

**Comment by josh11b** [comment]
Could you please update your PR to reflect our move from g3doc/ to doc_src/?
https://github.com/tensorflow/tensorflow/commit/1c707ac780313f48a6733dc3beedf4b8a2b3df77

In particular, there are some new instructions here:
https://github.com/tensorflow/tensorflow/blob/1c707ac780313f48a6733dc3beedf4b8a2b3df77/tensorflow/g3doc/README.txt

Thanks!

**Review by josh11b — APPROVED** [review]

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
