### PR TITLE
Logsoftmax kernel

### PR DESCRIPTION
**Pull request by kashif**
for issue #443

### CODE REVIEW

**Comment by kashif** [comment]
@girving how do you run tests when you develop locally? Do you simply do:

```
bazel test  //tensorflow/core/kernels:matm...
```

etc.? Thanks

**Comment by girving** [comment]
@kashif: Yep, though the names of tests unfortunately don't correspond exactly to the directory structure.  Usually it's easiest to write op tests in Python, so I'd either put something `python/kernel_tests/softmax_op_test.py` or make `log_softmax_op_test.py`.  You can run these as

    blaze test python/softmax_op_test python/log_softmax_op_test

I.e., the `kernel_tests` part goes away.  You can also run all the tests by doing `blaze test ...`.

**Comment by kashif** [comment]
@girving thank you, can you kindly review now?

**Comment by girving** [comment]
Please squash this into one commit.  It's hard to see the differences from master as is, since you introduced a bunch of code in one commit and then removed it in another.

**Comment by kashif** [comment]
@girving squashed

**Comment by kashif** [comment]
cool thanks! I'll get that done and squash it back to a single commit

**Comment by jendap** [comment]
@tensorflow-jenkins test this please

**Comment by kashif** [comment]
@jendap the builds are failing due to some other tests not related to my changes... is there a way to fix that from my side?

**Comment by girving** [comment]
@kashif: Actually the backwards compatibility test is failing, which does require an update on your end.  Please do this:

    bazel run core/ops/compat/update_ops

It updates some files that keep track of the history of op changes to ensure that everything is backwards compatible.  In this case, `update_ops` will add a new entry for `LogSoftmax`.

**Comment by girving** [comment]
Note that you can reproduce this problem locally by running `bazel test ...`.  You should see the same failure.

**Comment by kashif** [comment]
@girving thanks! will do... wow I learned so much in the pull request thanks for that!!

**Comment by kashif** [comment]
@tensorflow-jenkins test this please

**Comment by girving** [comment]
Apologies for not responding to this for a few days.  What's the status?  It looks like the squash hasn't happened yet.

**Comment by kashif** [comment]
@girving no worries! squashed

**Comment by girving** [comment]
I still see two commits.  Did you squash?

**Comment by kashif** [comment]
opps missed 1 squashing...

**Comment by girving** [comment]
Looks good!  Jenkins: Test this please.

**Comment by girving** [comment]
Tests all look good.  Unfortunately Github recently changed the "Merge pull request" button to not work if you're out of date.  Can you rebase?  Apologies for the trouble; we haven't yet figured out to hack around this unfortunate behavior change.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by akuz** [comment]
Does this implementation use a safe way to compute LogSumExp, preventing the underflow, using the "log sum exp trick"? I could not see it in code. More info on preventing the underflow here: http://math.stackexchange.com/questions/648514/preventing-underflow-log-sum-exp-trick

**Comment by akuz** [comment]
It seems to me that this should have been applied at some point: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard1/tf.reduce_logsumexp.md

**Pull request merged**
