### PR TITLE
[ROCm] Rename GPU device array helpers from cuda_ to gpu_

### PR DESCRIPTION
**Pull request by whchung**
Common utility helpers between CUDA and ROCm are renamed:

- core/kernels/cuda_device_array.h -> core/kernels/gpu_device_array.h
- core/kernels/cuda_device_array_gpu.h -> core/kernels/gpu_device_array_gpu.h

In subsequent PRs, ROCm-specific terminology changes would be introduced.

### CODE REVIEW

**Comment by whchung** [comment]
@yifeif May I ask you to take a look at this PR? It's a precursor to upstream ROCm-specific logic for TensorFlow operators.

Failed CI targets are:
- MacOS Contrib
- MacOS Python2 and CC
- Windows Bazel
- Windows Bazel GPU

From the logs they seem to have nothing to do with this PR, but a configuration issue in CI test infrastructure. I'm wondering if it's possible to manually apply `ready-to-pull` label, after your review and approval?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yifeif: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yifeif: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yifeif: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by whchung** [comment]
ping?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yifeif: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by yifeif** [comment]
Sorry for the delay @whchung. This change looks pretty benign, and dont think the errors are related.

**Review by yifeif — DISMISSED** [review]

**Comment by ymodak** [comment]
@whchung Can you please resolve the merge conflicts? Thanks!

**Comment by whchung** [comment]
@ymodak sorry for being late. resolved all conflicts with tip.

**Comment by dagamayank** [comment]
@yifeif Can you please approve this PR again after the latest merge conflicts were resolved?

**Comment by yifeif** [comment]
For sure! Looks good other than one more instance needs to be renamed:
'./tensorflow/core/kernels/split_lib_gpu.h:27:59: fatal error: tensorflow/core/kernels/cuda_device_array_gpu.h: No such file or directory'

Mind making the change and we can import again? Thank you!

**Comment by whchung** [comment]
@yifeif sorry I made some mistakes in the rebase process. it should have been fixed by now.

**Comment by whchung** [comment]
@yifeif could you take another look now? there is only one failed target `Ubuntu contrib` and looking from the logs it shouldn't have anything to do with this PR

**Comment by yifeif** [comment]
Thanks @whchung! Re-importing now.

**Comment by whchung** [comment]
@yifeif thanks! #26678 is a subsequent PR after this. Wondering could you help also take a look at it?

**Comment by yifeif** [comment]
Ofc. Taking a look now!

**Pull request merged**
