### PR TITLE
Revert "Fix compile warnings."

### PR DESCRIPTION
**Pull request by teamdandelion**
Reverts tensorflow/tensorflow#8206

This PR unfortunately broke the XLA build (at least internally).

I understand @gunan is working on adding XLA presubmits to our Jenkins testing. I think they are maybe available now but not enabled by default? Please get gunan's help to resubmit.

### CODE REVIEW

**Review by caisq — APPROVED** [review]

**Comment by conqer** [comment]
@dandelionmane what was the error?

**Comment by gunan** [comment]
The XLA build is ready, but there was a problem with it broadcasting its results to github.
Now that should be fixed.
However continuous XLA build on github seems to be OK. Maybe we are having an issue with compiler versions?

**Comment by conqer** [comment]
@gunan do you want me to resubmit? On gcc 4.8, it compiles fines. Please let me know the error.

**Comment by gunan** [comment]
@hawkinsp is this failure addressed by #8276 ?
Should we merge this PR, or wait for yours?

**Comment by gunan** [comment]
@conqer I am exploring how we can reproduce the issue on jenkins. Looks like we had a few failures with macos, I am guessing that come from clang.

**Comment by conqer** [comment]
@gunan Thanks. Please let me know if I can help.

**Pull request merged**
