### PR TITLE
make xtensa downloader generic to support variants

### PR DESCRIPTION
**Pull request by kpraving**
Change the download script so that we can support multiple xtensa target variants. The functionality is identical to https://github.com/tensorflow/tensorflow/pull/44845 but the script is ready for additional download variants.

Tested the following commands:

1. Incorrect params to the download script
    ```
    $ tensorflow/lite/micro/tools/make/ext_libs/xtensa_download.sh /tmp blah
    ```
    Gave the expected error:
    ```
    Attempting to download an unsupported xtensa variant: blah
    ```

1. Correct invocation for hifi4 
    ```
    $ tensorflow/lite/micro/tools/make/ext_libs/xtensa_download.sh /tmp hifi4
    ```
    Downloaded the library to `/tmp/xa_nnlib_hifi4`.

1. Using the makefile
    ```
    rm -rf tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi4/
    make -f tensorflow/lite/micro/tools/make/Makefile -j8 TARGET=xtensa XTENSA_CORE=blah XTENSA_BASE=blah XTENSA_TOOLS_VERSION=blah TARGET_ARCH=hifi4 clean
    ```
    Downloaded the library and printed out the sources list.

1. Using the makefile after already downloading the library
    ```
    make -f tensorflow/lite/micro/tools/make/Makefile -j8 TARGET=xtensa XTENSA_CORE=blah XTENSA_BASE=blah XTENSA_TOOLS_VERSION=blah TARGET_ARCH=hifi4 clean
    ```
    Correctly determined that the downloaded file already exists (`tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi4 already exists, skipping the download.`) and prints out the sources list on the terminal.

### CODE REVIEW

**Comment by kpraving** [comment]
@googlebot I signed it!

Regards
pravin

**Comment by advaitjain** [comment]
Thanks @kpraving. I have pushed a commit that makes the following changes:

1. moves the URL, MD5 etc to the bash script from the Makefile so that we can run the download script more easily.
1. Reduced the number of parameters to the script at the cost of duplicating the downloaded folder name (`xa_nnlib_hifi4`) across the bash script and the makefile.
1. having the downloaded zip folder in /tmp be also named according to the variant being downloaded.

If you can review and comment here that the changes look good to you then we can get this merged.

Note that since I directly pushed to your branch, you should `git pull` before making any further changes locally.

**Comment by kpraving** [comment]
@advaitjain, We added TARGET_ARCH dependency in both files. We could just keep dependency in 'xtensa.inc' and keep 'xtensa_download.sh' generic. But this works as well. Changes look good to me. Thanks.

**Review by advaitjain — APPROVED** [review]

**Comment by advaitjain** [comment]
> @advaitjain, We added TARGET_ARCH dependency in both files. We could just keep dependency in 'xtensa.inc' and keep 'xtensa_download.sh' generic. But this works as well. Changes look good to me. Thanks.

Thanks. Let's go with this for now. I have a preference for being able to run the script easily independent of the makefile (even though it means more duplication).

**Review by gbaned — APPROVED** [review]

**Pull request merged**
