### PR TITLE
(re-re-submission) Improve Flatten to avoid using dynamic shapes when possible

### PR DESCRIPTION
**Pull request by pooyadavoodi**
- Fixes issues @ebrevdo pointed out with #30380
- Added unit test for the int32 overflow situation (skip test for windows due to failures).
- See [original PR](https://github.com/tensorflow/tensorflow/pull/30380) for explanation of overall changes.

Thanks to @trevor-m who did most of the implementation.

### CODE REVIEW

**Comment by ebrevdo** [comment]
sanity check failed:

```
FAIL: Found 1 non-whitelisted pylint errors:
tensorflow/python/layers/core_test.py:562: [E0001(syntax-error), ] invalid syntax
```

**Review by ebrevdo — CHANGES_REQUESTED** [review]
please fix sanity check.

**Comment by pooyadavoodi** [comment]
> sanity check failed:
> 
> ```
> FAIL: Found 1 non-whitelisted pylint errors:
> tensorflow/python/layers/core_test.py:562: [E0001(syntax-error), ] invalid syntax
> ```

oops, I fixed the syntax. Thanks.

**Comment by ebrevdo** [comment]
OK; the windows failure is not related.  Let's merge.

**Review by ebrevdo — APPROVED** [review]

**Pull request merged**
