### PR TITLE
Update AMP mkl lists

### PR DESCRIPTION
**Pull request by gaurides**
Improves performance for many models by ~15-20% 

Moving Mean from Deny to Infer list because the Mean functor does accumulation in FP32. 
Also, adding Rsqrt, SquaredDifference and Mean will help fusion the LayerNorm sub-graph.

Adding ResizeBilinear to Clear list as it helps reduce the incoming Casts and improve performance

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Review by penpornk — CHANGES_REQUESTED** [review]
Could you please help take a look at [Arm CI failure](https://github.com/tensorflow/tensorflow/actions/runs/3153362427/jobs/5129746558)?
```
//bazel_pip/tensorflow/python/grappler:remapper_test_cpu                 FAILED in 3 out of 3 in 5.0s
//bazel_pip/tensorflow/python/grappler:remapper_test_gpu                 FAILED in 3 out of 3 in 11.1s
```

Alternatively, please feel free to guard the changes with `#ifndef DNNL_AARCH64_USE_ACL` (or an x86 ifdef).

cc: @nSircombe @milpuz01

**Comment by gaurides** [comment]
Thanks @penpornk 
@nSircombe  @milpuz01 : can you please help me with which test fails in remapper_test_cpu?

**Review by mihaimaruseac — APPROVED** [review]

**Comment by penpornk** [comment]
@elfringham Thank you very much for checking! I'll pull this PR in then.

**Comment by gaurides** [comment]
Thanks @elfringham  and @penpornk for checking.

**Pull request merged**
