### PR TITLE
1.0.1 patch (update version)

### PR DESCRIPTION
**Pull request by av8ramit**
Running the update_version.sh script to update all version #s to 1.0.1.

### CODE REVIEW

**Comment by av8ramit** [comment]
@tensorflow-jenkins test this please

**Review by jhseu — APPROVED** [review]

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by av8ramit** [comment]
Jenkins, test this please

**Comment by av8ramit** [comment]
@tensorflow-jenkins test this please

**Comment by av8ramit** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Pull request merged**
