### PR TITLE
[TF-TRT] Adding a widget to inform the user that we are still processing `TrtGraphConverterV2.build()`

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
@bixia1 for review

This PR adds a waiting widget to inform the user that we are still processing `TrtGraphConverterV2.build()`.

Print message on the console during the duration of the build indicating: `Building TensorRT Engines. Please wait ...`

### CODE REVIEW

**Comment by gbaned** [comment]
@bixia1 Can you please review this PR ? Thanks!

**Comment by bixia1** [comment]
We discussed whether this is indeed needed at a meeting and hasn't reached a final solution yet.

**Comment by gbaned** [comment]
@DEKHTIARJonathan Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@DEKHTIARJonathan Can you please resolve conflicts? Thanks!

**Pull request closed without merging**
