### PR TITLE
integer overflow possibility fix

### PR DESCRIPTION
**Pull request by iurii-kvasniuk**
The current code can lead to integer overflow and weird results
Created issue: https://github.com/tensorflow/tensorflow/issues/32045

### CODE REVIEW

**Comment by iur-kvasniuk** [comment]
here with @googlebot I signed it!)

**Comment by gbaned** [comment]
@iur-kvasniuk thank you for your contribution, please sign CLA.

**Comment by iur-kvasniuk** [comment]
> @iur-kvasniuk thank you for your contribution, please sign CLA.

@gbaned, I have signed Google Individual CLA Aug 28, 2019 23:12 PDT

**Comment by iur-kvasniuk** [comment]
@googlebot I signed it!

**Comment by iurii-kvasniuk** [comment]
username was changed to avoid dublication

**Comment by iurii-kvasniuk** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
Closing this since it is a duplicate of PR#[32083](https://github.com/tensorflow/tensorflow/pull/32083).

**Pull request closed without merging**
