### PR TITLE
Update example_proto_fast_parsing.cc

### PR DESCRIPTION
**Pull request by yann-yy**
hash with a new seed when hash collision is found

### CODE REVIEW

**Comment by hgadig** [comment]
@drpngx  Could you PTAL and approve or suggest changes(if required).

**Review by drpngx — DISMISSED** [review]
Sorry I missed this. Thanks for the fix!

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Comment by yann-yy** [comment]
> I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

I'm confused this PR is ready to pull, but stalled for months. What I have missed or what I should do to continue this PR ?

**Comment by mihaimaruseac** [comment]
I think there were build failures that were not taken care of and then conflicts.

To continue, please reopen as a new PR, solve conflicts (if any). You can add me to reviewers and I'll try to get in as soon as it can land.

**Comment by rthadur** [comment]
@yann-yy thank you for your contribution , please reopen a new PR , thank you @mihaimaruseac

**Comment by yann-yy** [comment]
I have reopened a new PR (https://github.com/tensorflow/tensorflow/pull/29120). 
Thank you @mihaimaruseac @rthadur

**Pull request closed without merging**
