### PR TITLE
Support boolean type to variables' ops and assign-like ops.(#12046)

### PR DESCRIPTION
**Pull request by nolanliou**
Fix [#12046](https://github.com/tensorflow/tensorflow/issues/12046).

### CODE REVIEW

**Review by jhseu — APPROVED** [review]

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by nolanliou** [comment]
Have updated the code.

**Comment by jhseu** [comment]
Jenkins, test this please

**Pull request merged**
