### PR TITLE
Removed the deprecated API from contrib module

### PR DESCRIPTION
**Pull request by amitsrivastava78**

### CODE REVIEW

**Review by alextp — DISMISSED** [review]

**Comment by gbaned** [comment]
@amitsrivastava78 Could you please address the build failures? Thanks!

**Comment by amitsrivastava78** [comment]
@gbaned , i have solved the build errors.
@alextp , Sorry for the trouble there were some indentation related issues which i have fixed, can you please re-approve the PR.

Regards
Amit

**Review by alextp — DISMISSED** [review]

**Comment by amitsrivastava78** [comment]
@alextp  the rework is complete ,can you please approve the PR.

Regards
Amit

**Review by alextp — DISMISSED** [review]

**Comment by amitsrivastava78** [comment]
@gbaned , can you pls help to get this PR merged.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@alextp , there were some TC failures which i have fixed, can you please re-approve the PR.

Regards
Amit

**Review by alextp — APPROVED** [review]

**Comment by rthadur** [comment]
@amitsrivastava78 sorry for the delay , there were some test failures , can you please check the build failures and update your branch, thank you.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
