### PR TITLE
 Fix bug: divide by zero in embedding_lookup_sparse

### LINKED ISSUE #14851: Got NAN when calling embedding_lookup_sparse with weights and "mean" combiner
### System information
- **OS Platform and Distribution**: Win7 64bit
- **TensorFlow installed from**: anaconda binary
- **TensorFlow version**: 1.2.1
- **Python version**: 3.6

### Describe the problem
I always got nan when I call embedding_lookup_sparse with weights and "mean" combiner.
Code pieces are listed below:

### Source code / logs
from __future__ import absolute_import
from __future__ import print_function
import os
import numpy as np
import tensorflow as tf
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

a = np.arange(192).reshape(24, 8)
print(a)

a = tf.Variable(a, dtype=tf.float32)
ids = tf.SparseTensor(
    indices=[[1, 0], [2, 0], [2, 1], [2, 2], [3, 0], [9, 1]],
    values=[10, 1, 2, 3, 4, 5],
    dense_shape=[1, 1])
weights = tf.SparseTensor(
    indices=[[1, 0], [2, 0], [2, 1], [2, 2], [3, 0], [9, 1]],
    values=[1, 0.2, 0.4, 0.4, 1, 1],
    dense_shape=[1, 1])
b = tf.nn.embedding_lookup_sparse(
    a, ids, weights, partition_strategy='mod', combiner='sum')
c = tf.pad(b, [[0, 16 - tf.shape(b)[0]], [0, 0]], mode='CONSTANT')

sess = tf.Session()
sess.run(tf.global_variables_initializer())
[value] = sess.run([c])
print(value)

### PR DESCRIPTION
**Pull request by facaiy**
Fix #14851

### CODE REVIEW

**Comment by drpngx** [comment]
Let's wait until the GPU version is checked in.

@tatatodd do you see a perf issue here?

**Comment by facaiy** [comment]
Sure, many thanks.

**Comment by facaiy** [comment]
Hi, any update ?

**Comment by drpngx** [comment]
So, we should definitely change the doc. There is also `safe_embedding_lookup_sparse` in contrib, which obviously has a different implementation. Can you explain what the difference is?

**Comment by facaiy** [comment]
You're right. 

The API of ` tf.nn.embedding_lookup_sparse` requires:

> This op assumes that there is at least one id for each row in the dense tensor represented by sp_ids

Let's close it.

**Comment by facaiy** [comment]
@drpngx  Could you close #14851 as well ?

**Comment by wenmin-wu** [comment]
@facaiy Came across this problem in version 1.3, 1.4. 1.5 again. Seems your changes have been overridden by someone else?
https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/python/ops/embedding_ops.py
https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/ops/embedding_ops.py
https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/ops/embedding_ops.py
All the implementation in these versions is:
```
elif combiner == "mean":
        embeddings = math_ops.segment_sum(embeddings, segment_ids)
        weight_sum = math_ops.segment_sum(weights, segment_ids)
        embeddings = math_ops.div(embeddings, weight_sum, name=name)
```

**Pull request closed without merging**
