### PR TITLE
Remove no_oss tag for depthwise conv tests

### PR DESCRIPTION
**Pull request by duncanriach**
This PR is a follow-up to [this conversation](https://github.com/tensorflow/tensorflow/pull/55657#issuecomment-1105605034) with @reedwm in PR [55657](https://github.com/tensorflow/tensorflow/pull/55657).

### CODE REVIEW

**Review by reedwm — APPROVED** [review]

**Comment by reedwm** [comment]
The test is failing, so this can't be merged. This explains why the `no_oss` tag was there: The test fails, and since the timeout of the test is long, it doesn't run on the internal codebase either, so the depthwise convolution tests are not run at all by the CI.

The tests `testDepthwiseConv2DFilterGradCompare` and `testDepthwiseConv2DFilterGradExplicitCompare` are failing, both on the CPU and GPU builds. The former test fails with the error

```
======================================================================
ERROR: testDepthwiseConv2DFilterGradCompare (tensorflow.python.kernel_tests.nn_ops.depthwise_conv_op_base.DepthwiseConv2DBase)
tensorflow.python.kernel_tests.nn_ops.depthwise_conv_op_base.DepthwiseConv2DBase.testDepthwiseConv2DFilterGradCompare
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_base.py", line 1055, in testDepthwiseConv2DFilterGradCompare
    self._CompareBackpropFilter(input_size, filter_size, output_size, stride,
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_base.py", line 1043, in _CompareBackpropFilter
    gpu_value = _GetVal(use_gpu=True, data_format=data_format)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_base.py", line 1035, in _GetVal
    backprop = nn_ops.depthwise_conv2d_native_backprop_filter(
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
    return fn(*args, **kwargs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/util/dispatch.py", line 1170, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/nn_ops.py", line 3150, in depthwise_conv2d_native_backprop_filter
    return gen_nn_ops.depthwise_conv2d_native_backprop_filter(
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/gen_nn_ops.py", line 2540, in depthwise_conv2d_native_backprop_filter
    _ops.raise_from_not_ok_status(e, name)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 7203, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__DepthwiseConv2dNativeBackpropFilter_device_/job:[localhost/replica:0](https://cs.corp.google.com/piper///depot/google3/localhost/replica?cl=446264337)/task:0/device:GPU:0}} DepthwiseConv2DBackpropFilter: input and filter must have the same in_depth [Op:DepthwiseConv2dNativeBackpropFilter]
```

The latter test fails with

```
======================================================================
ERROR: testDepthwiseConv2DFilterGradExplicitCompare (tensorflow.python.kernel_tests.nn_ops.depthwise_conv_op_base.DepthwiseConv2DBase)
tensorflow.python.kernel_tests.nn_ops.depthwise_conv_op_base.DepthwiseConv2DBase.testDepthwiseConv2DFilterGradExplicitCompare
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_base.py", line 1073, in testDepthwiseConv2DFilterGradExplicitCompare
    self._CompareBackpropFilter(input_size, filter_size, output_size, stride,
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_base.py", line 1043, in _CompareBackpropFilter
    gpu_value = _GetVal(use_gpu=True, data_format=data_format)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_base.py", line 1035, in _GetVal
    backprop = nn_ops.depthwise_conv2d_native_backprop_filter(
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
    return fn(*args, **kwargs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/util/dispatch.py", line 1170, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/nn_ops.py", line 3150, in depthwise_conv2d_native_backprop_filter
    return gen_nn_ops.depthwise_conv2d_native_backprop_filter(
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/gen_nn_ops.py", line 2540, in depthwise_conv2d_native_backprop_filter
    _ops.raise_from_not_ok_status(e, name)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_gpu.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 7203, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__DepthwiseConv2dNativeBackpropFilter_device_/job:[localhost/replica:0](https://cs.corp.google.com/piper///depot/google3/localhost/replica?cl=446264337)/task:0/device:GPU:0}} Nonzero explicit padding in the batch or depth dimensions is not supported [Op:DepthwiseConv2dNativeBackpropFilter]
```

This needs to get fixed, as we are not testing depthwise convolutions currently. @duncanriach, do you want to fix this? A quick fix would be to add `@unittest.skip("Test currently fails")` for the two failing test methods.

**Comment by duncanriach** [comment]
> This needs to get fixed, as we are not testing depthwise convolutions currently. @duncanriach, do you want to fix this? A quick fix would be to add `@unittest.skip("Test currently fails")` for the two failing test methods.

Yes, I'll work on this. It's weird that these tests are failing because I thought I ran them successfully for PR [55657](https://github.com/tensorflow/tensorflow/pull/55657).

**Comment by duncanriach** [comment]
> > This needs to get fixed, as we are not testing depthwise convolutions currently. @duncanriach, do you want to fix this? A quick fix would be to add `@unittest.skip("Test currently fails")` for the two failing test methods.
> 
> Yes, I'll work on this. It's weird that these tests are failing because I thought I ran them successfully for PR [55657](https://github.com/tensorflow/tensorflow/pull/55657).

@reedwm, the errors on these two tests are caused by incomplete changes in PR [55751](https://github.com/tensorflow/tensorflow/pull/55751) from @kaixih, merged 2022-05-04 (yesterday). This would not have been caught be the OSS CI because of the `no_oss` tag. The tests were then disabled using the `notap` tag (what does "notap" mean?), because they were failing, a few hours ago by [this commit](https://github.com/tensorflow/tensorflow/commit/226627be53a581543378249766940a6a3c71427f). So these tests were being run somewhere. I think I can see what needs to be done to make these tests pass and I intend to push a commit later today.

**Comment by reedwm** [comment]
I see, so I was incorrect in saying these were not run by CI. Once you push a commit to fix this, you can remove the `no_oss` and `no_tap` tags.

**Review by reedwm — APPROVED** [review]

**Comment by reedwm** [comment]
The CPU-only builds are failing with the error

```
======================================================================
ERROR: testDepthwiseConv2DFilterGradExplicitCompare (tensorflow.python.kernel_tests.nn_ops.depthwise_conv_op_base.DepthwiseConv2DBase)
tensorflow.python.kernel_tests.nn_ops.depthwise_conv_op_base.DepthwiseConv2DBase.testDepthwiseConv2DFilterGradExplicitCompare
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_cpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_base.py", line 1078, in testDepthwiseConv2DFilterGradExplicitCompare
    self._CompareBackpropFilter(input_size, filter_size, output_size, stride,
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_cpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_base.py", line 1048, in _CompareBackpropFilter
    gpu_value = _GetVal(use_gpu=True, data_format=data_format)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_cpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_base.py", line 1035, in _GetVal
    backprop = nn_ops.depthwise_conv2d_native_backprop_filter(
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_cpu.runfiles/org_tensorflow/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
    return fn(*args, **kwargs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_cpu.runfiles/org_tensorflow/tensorflow/python/util/dispatch.py", line 1176, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/nn_ops.py", line 3150, in depthwise_conv2d_native_backprop_filter
    return gen_nn_ops.depthwise_conv2d_native_backprop_filter(
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/gen_nn_ops.py", line 2540, in depthwise_conv2d_native_backprop_filter
    _ops.raise_from_not_ok_status(e, name)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/depthwise_conv_op_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 7203, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.UnimplementedError: {{function_node __wrapped__DepthwiseConv2dNativeBackpropFilter_device_/job:localhost/replica:0/task:0/device:CPU:0}} Depthwise convolution on CPU is only supported for NHWC format [Op:DepthwiseConv2dNativeBackpropFilter]
```

Looks like NCHW shouldn't be tested if `test.is_gpu_available()` returns False.

**Comment by duncanriach** [comment]
The four tests that compared the gradients between the CPU and GPU were being run even when there was no GPU available, which would have compared the CPU gradients with themselves, always passing. The tests were being run under both `depthwise_conv_op_test.py` and `depthwise_conv_op_d9m_test.py`, so the most recent commit removes eight tests when there is no GPU available.

**Review by reedwm — APPROVED** [review]

**Pull request merged**
