### PR TITLE
Removes line from README

### PR DESCRIPTION
**Pull request by ChrisAntaki**
As @terrytangyuan pointed out in #23647, the line being removed makes a suggestion that can't be followed

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Comment by harshini-gadige** [comment]
@terrytangyuan  A CL has been created and can you please LGTM it ?

**Comment by terrytangyuan** [comment]
@harshini-gadige Could you elaborate on what I need to do? I've already approved this PR.

**Comment by harshini-gadige** [comment]
> @harshini-gadige Could you elaborate on what I need to do? I've already approved this PR.

Can you please approve and LGTM the CL in the below link.
https://critique.corp.google.com/#review/224036595

**Comment by ChrisAntaki** [comment]
Hey @harshini-gadige - looks like shlens@ is the CL reviewer. Terry is an external contributor. Thanks!

**Comment by harshini-gadige** [comment]
> Hey @harshini-gadige - looks like shlens@ is the CL reviewer. Terry is an external contributor. Thanks!

Thanks for correcting @ChrisAntaki. I'll get in touch with shlens@

**Comment by harshini-gadige** [comment]
@shlens  Could you PTAL ?

**Review by shlens — COMMENTED** [review]
LGTM

**Pull request merged**
