### PR TITLE
Integration of CMSIS-NN API to TFLu

### PR DESCRIPTION
**Pull request by freddan80**
This is a first step towards integrating CMSIS-NN optimized kernel implementations into TFLu.

### CODE REVIEW

**Comment by freddan80** [comment]
I signed it!

**Comment by freddan80** [comment]
I added my work email.

**Review by petewarden — COMMENTED** [review]
Thanks for this, and sorry it took me a few days to get to it, I missed it in my other PRs! This is an important one, so I'll try to put together some notes, and maybe see if we can set up a call at a convenient time once I've done that.

**Comment by freddan80** [comment]
Sounds good!

**Comment by rthadur** [comment]
@freddan80 please resolve conflicts

**Comment by freddan80** [comment]
I will fix it

**Comment by freddan80** [comment]
Reverted back to original change. No need to review this

**Comment by freddan80** [comment]
Ready for review

**Review by petewarden — APPROVED** [review]
Thanks for this Fredrik! Looks great, approving.

**Pull request merged**
