### PR TITLE
Basic setup steps for contributing

### PR DESCRIPTION
**Pull request by Dorian**
There was no instructions on how to get set up and running tests.

(e.g. I found a bug in tensorflow and just want to fix it)

---

**Edit**: TODO:

- [ ] Setup instructions for non-MacOS users? (e.g. not necessary if setup script is OS-agnostic)
- [ ] System tests for setup instructions?
- [ ] `bin/setup`?
- [ ] `bin/test`? Would test all targets by default?

### CODE REVIEW

**Comment by drpngx** [comment]
@wolffg feel free to chime in.

That'll work for Mac, but we have other instructions for other OS. Maybe it's best to point to the general source building instructions.

**Comment by martinwicke** [comment]
@wolffg ping?

**Comment by Dorian** [comment]
I started working on a draft https://github.com/Dorian/doma/blob/master/_drafts/2017-04-16-contributing-to-tensorflow.md

But ultimately a `bin/setup` and `bin/test` would be my goal (even if not integrated in the main repo)

**Comment by Dorian** [comment]
I'm going to setup an automated process with a MacOS virtual image to test my instruction steps, might take a bit more time than I thought but it's all good :)

**Comment by vrv** [comment]
Hi Dorian, it turns out as part of a huge documentation day on Friday, a change is in the works to provide a full contributions list, which apparently includes this as well.  So I'm going to close this for now, and perhaps you can add to that one when it gets pushed (hopefully tomorrow?)

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/pull/9604/commits/a8cf54a732d2385fa7b97495c73a91e4515e8d60 is the pending file.

**Comment by Dorian** [comment]
@vrv Nice! Thanks!

I also found a hacky way to get things working quickly:

```bash
> docker run -it tensorflow/magenta
> cd /tensorflow/tensorflow
> python examples/learn/iris.py
> bazel test python
```

**Pull request closed without merging**
