### PR TITLE
changed EarlyStopping so best weights are also loaded at the end of training

### PR DESCRIPTION
**Pull request by jmhessel**
Hi,

I love using tf.keras.callbacks.EarlyStopping. But I also want the best weights to be loaded automatically at the end of the training, in addition to during training if `restore_best_weights=True`. Checking out the semantics from the documentation:

restore_best_weights | Whether to restore model weights from the epoch with the best value of the monitored quantity. If False, the model weights obtained at the last step of training are used.
-- | --

I think this PR more closely aligns with expected behavior vs. the current version. It's easy enough to make a version of EarlyStopping with this behavior, but I was pretty surprised that this wasn't the default so figured I'd make a PR.

### CODE REVIEW

**Comment by jmhessel** [comment]
@googlebot I signed it!

**Comment by jmhessel** [comment]
FWIW --- a summary of the current behavior is:

if you early stop during training causing the model to exit early, you will load your best weights.

I think it should be

if you stop early during training causing the model to exit early, you will load your best weights. And, if your training continues to completion without early stopping, at the end of training, you still load your best weights.

**Review by omalleyt12 — APPROVED** [review]
@jmhessel Thanks for the PR! LGTM, I agree with your reasoning

**Comment by jmhessel** [comment]
@omalleyt12 BTW --- I saw some check is not successful; anything I can do to fix it? I can't see the details because it looks to be some google-internal check.

**Pull request merged**
