### PR TITLE
Tutorial updates for r0.10 release

### PR DESCRIPTION
**Pull request by sandersk**
Hi TF team,

Would it be possible to fold these tutorial doc updates from master into the r0.10 release branch?

Thanks,
Sanders

### CODE REVIEW

**Comment by danmane** [comment]
Hi Sanders,

Please sign the CLA and then we can move forward with the review process.

Thanks!

**Comment by vrv** [comment]
alternatively, change the git commit email to your google address

**Comment by benoitsteiner** [comment]
@sandersk, can you sign the cla?

**Comment by sandersk** [comment]
@benoitsteiner I signed it. Let me know if there's still any issues.

**Pull request merged**
