### PR TITLE
Added an example to tf.keras.backend.categorical_crossentropy

### PR DESCRIPTION
**Pull request by eito-fis**

### CODE REVIEW

**Comment by rthadur** [comment]
Closing this PR as this not against `master`, please open a new PR against `master` 
CC @mihaimaruseac

**Comment by eito-fis** [comment]
@rthadur Is it ok to merge to master even though it's written for the 2.0 docs? 
Sorry, new to contributing and not sure what to do.

**Comment by rthadur** [comment]
please submit docs changes to [here](https://github.com/tensorflow/docs)

**Comment by mihaimaruseac** [comment]
@eito-fis Yes, anything that touches code should go on master. The 2.0 branch is going to be forwarded several times until the first RC. Before the first RC, due to forwarding, any commits on the branch will get lost at every forward. After the RC, all the commits to the branch are cherry-picks from master.

**Comment by eito-fis** [comment]
Thanks! Remade the PR [here](https://github.com/tensorflow/tensorflow/pull/29563).

**Pull request closed without merging**
