### PR TITLE
[2.0 Cherrypick] Bug fixes for Keras SavedModel

### PR DESCRIPTION
**Pull request by k-w-w**

### CODE REVIEW

**Review by alextp — DISMISSED** [review]
I don't understand why the deletion of gbdt_batch was in the commit but I think it's harmless.

**Comment by k-w-w** [comment]
Whoops, thanks for catching that. I meant to delete only the change that was added to the file. Updating the commit

**Comment by k-w-w** [comment]
`gbdt_batch.py` has been undeleted.

**Review by alextp — APPROVED** [review]

**Review by goldiegadde — APPROVED** [review]

**Comment by luzm123** [comment]
2022-01-08 12:47:32.812069: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/openvino_2021/data_processing/dl_streamer/lib:/opt/intel/openvino_2021/data_processing/gstreamer/lib:/opt/intel/openvino_2021/opencv/lib:/opt/intel/openvino_2021/deployment_tools/ngraph/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib::/opt/intel/openvino_2021/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/omp/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-01-08 12:47:32.812092: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-08 12:47:32.812107: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2022-01-08 12:47:32.812367: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:absl:Please consider providing the trackable_obj argument in the from_concrete_functions. Providing without the trackable_obj argument is deprecated and it will use the deprecated conversion path.
2022-01-08 12:47:34.806218: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-01-08 12:47:34.806383: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-01-08 12:47:34.860258: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1164] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.008ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.

2022-01-08 12:47:37.790651: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:357] Ignored output_format.
2022-01-08 12:47:37.790685: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:360] Ignored drop_control_dependency.
2022-01-08 12:47:38.104138: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1892] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexStridedSlice, FlexTranspose
Details:
	tf.StridedSlice(tensor<1x120x160x3x1x32xf32>, tensor<6xi32>, tensor<6xi32>, tensor<6xi32>) -> (tensor<1x120x160x1x32xf32>) : {begin_mask = 55 : i64, device = "", ellipsis_mask = 0 : i64, end_mask = 55 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 8 : i64}
	tf.Transpose(tensor<1x30x4x40x4x1x4xf32>, tensor<7xi32>) -> (tensor<1x30x40x1x4x4x4xf32>) : {device = ""}
See instructions: https://www.tensorflow.org/lite/guide/ops_select
2022-01-08 12:47:38.104385: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1963] Estimated count of arithmetic ops: 53.877 G  ops, equivalently 26.938 G  MACs

Estimated count of arithmetic ops: 53.877 G  ops, equivalently 26.938 G  MACs
WARNING:absl:Buffer deduplication procedure will be skipped when flatbuffer library is not properly loaded

**Comment by qadafie96** [comment]
gh pr checkout 26682

**Comment by luzm123** [comment]
???/

**Pull request merged**
