### PR TITLE
xla cpu backend enhancements

### PR DESCRIPTION
**Pull request by snadampal**
This PR implements 
1. batch dot emitter with eigen runtime
2. ACL (Arm Compute Library) runtime for dot and conv emitters

### CODE REVIEW

**Comment by gbaned** [comment]
@snadampal Can you please resolve conflicts? Thank you!

**Comment by snadampal** [comment]
Hi @gbaned , thanks for the review! As you know, the conflict in the xla.proto file is for the enum definitions, It will be a one line change to use the last available value for the new definitions. Since this file is being changed in lot of other PRs as well, depending on which PR gets merged first, all other need to update theirs. I'm thinking it may be good to address it at the end, close to when the PR is ready for merge.  If you think this is required to proceed with CI tests, I will update it right away.

**Comment by snadampal** [comment]
Hi @gbaned , I have rebased to the latest and resolved the merge conflict. Happy to address if any other feedback on the commits. Thank you!

**Comment by snadampal** [comment]
Hi @gbaned, I'm not able to view the CI Build failure. Please let me know how I can get access to them? Thank you!

**Comment by gbaned** [comment]
> Hi @gbaned, I'm not able to view the CI Build failure. Please let me know how I can get access to them? Thank you!

@snadampal  Sorry for the delay, I ran the builds, please check now. Thank you!

**Comment by snadampal** [comment]
Hi @gbaned , thanks! I'm able to access the CI build now. I have updated the commits to address the CI failure. Will wait for the next CI run.

**Comment by snadampal** [comment]
Hi @gbaned, CI builds are passing now, however the other checks (code check and Py+CPP Test suite) are in waiting state for quite sometime. Could you please check if they need force run again. Also please let me know if there is any feedback on the commits. Thank you!

**Comment by gbaned** [comment]
@snadampal Sorry for the delay. Can you please resolve conflicts? Thank you!

**Comment by snadampal** [comment]
Hi @gbaned, I have resolved the merge conflicts.

**Review by d0k — APPROVED** [review]

**Comment by snadampal** [comment]
The Intel community CI build failure seems to be due to merge conflict, I will resolve it. But i'm not able to get the logs for Code Check and Android Demo App Internal CI build failure. I believe they are again due to the merge conflict.... otherwise, can someone point me to the failures?

> 11:55:46  Auto-merging tensorflow/compiler/xla/xla.proto
> 11:55:46  CONFLICT (content): Merge conflict in tensorflow/compiler/xla/xla.proto
> 11:55:46  Automatic merge failed; fix conflicts and then commit the result.

**Comment by d0k** [comment]
The merge conflict is in xla.proto, when another flag is added, I added another one yesterday, but it has been rolled back for now.

I don't seem to have access to the other CI builds either, it's just 404. Is there a way to retrigger them?

**Comment by snadampal** [comment]
Hi @d0k , I have resolved the merge conflicts.

**Review by d0k — APPROVED** [review]

**Comment by d0k** [comment]
Working on the merge, should land tomorrow or Monday. There's still a bunch of failing tests when there's more than one batch dimension and lowering to the batch matmul libcall. I'll put in a check to disable emitting the library call in that case but would be nice if you could take a look.

**Comment by snadampal** [comment]
Thank you so much Benjamin! If I can get the test setup for more than one batch dimension test failure, I can definitely try to debug them. Please let me know where I can get the test setup details. Thank you!

**Comment by snadampal** [comment]
> You should be able to see wrong results on `bazel test -c opt //tensorflow/compiler/xla/tests:dot_operation_test_cpu` https://source.cloud.google.com/results/invocations/e217cb81-ca26-408d-ac6f-b4f8da0e081c/log

thank you. I've got the setup now.

**Comment by snadampal** [comment]
Hi @d0k, the failure is with the eigen batch matmul which shouldn't have been picked up in the first place. I didn't see ACL runtime being used because this particular flag is not visible to the bazel system. I'm looking into it.

third_party/compute_library/BUILD

```
load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
config_setting(
    name = "build_with_acl",
    define_values = {
        "build_with_acl": "true",
    },
    visibility = ["//visibility:public"],
)
```

**Comment by d0k** [comment]
> Hi @d0k, I ran the below bazel test and able to reproduce data mismatch failure for `Einsum/EinsumTest.SimpleEinsumTest` and `DotOperationTextTest.DotReorderedDotDims` in every shard and I'm looking into them. `bazel test --config=mkl_aarch64 -c opt //tensorflow/compiler/xla/tests:dot_operation_test_cpu`

Thanks. I don't have a ACL setup so I was testing with Eigen only. I think the problem is that it only passes one dimension to the runtime even if there are multiple batch dims.

Still working on getting this merged. Should happen soon.

**Comment by snadampal** [comment]
Thanks! btw, do you want me to resolve the merge conflicts? As you might have probably noticed, the conflict is only an enum definition in xla.proto, the change required is just to increment the value to the Next id. Please let me know If I need to resolve and rebase the commits.

**Comment by d0k** [comment]
> Thanks! btw, do you want me to resolve the merge conflicts? As you might have probably noticed, the conflict is only an enum definition in xla.proto, the change required is just to increment the value to the Next id. Please let me know If I need to resolve and rebase the commits.

No need, I can handle that merge.

**Comment by snadampal** [comment]
Hi @d0k , thanks for merging the PR!!
I see you added this TODO for the multi dimensional batch scenario. I will look into it.
```
  // TODO(kramerb): Remove this limitation.
  if (num_batch_dims > 1) return false;
```

**Comment by snadampal** [comment]
Hi @d0k , I see compilation failure for '--config=mkl_aarch64' with the PR merge commit,  but when I apply the PR patches manually to the latest commit, everything is compiling and working fine. 

I'm checking the PR merge commit to see what is different from the original patches, could you also please check at your end? 
Please let me know if you want me to push the rebased PR including your change to exclude the multi dimension batch.

>   // TODO(kramerb): Remove this limitation.
>   if (num_batch_dims > 1) return false;

```
commit c1f394e95289ff8a35c1d6e27c7ed5d4d27704f9 (HEAD -> master)
Author: Sunita Nadampalli <nadampal@amazon.com>
Date:   Thu Jun 30 02:46:13 2022 +0000

    support grouped convolutions in acl conv2d runtime

commit 2690e9afc8d535b91a4d2fd9987958d8045864bf
Author: Sunita Nadampalli <nadampal@amazon.com>
Date:   Thu Jun 30 02:45:09 2022 +0000

    Implement acl conv2d runtime for convolution ir emitter
    
    Note: This work is derived from OneDNN code which was published
    with the following copyright statements:
    Copyright 2021 Arm Ltd. and affiliates.

commit 3d99f9b73aa9c33aaf8615bcfcf99cb84e43e208
Author: Sunita Nadampalli <nadampal@amazon.com>
Date:   Thu Jun 30 02:42:02 2022 +0000

    Implement acl runtime for batch dot emitter
    
    Note: This work is derived from OneDNN code which was published
    with the following copyright statements:
    Copyright 2021 Arm Ltd. and affiliates.

commit 2687f467c8d3dd8eda80d7f1b75633df0c259583
Author: Sunita Nadampalli <nadampal@amazon.com>
Date:   Thu Jun 30 02:41:14 2022 +0000

    Implement batch dot emit directly with Eigen runtime

commit 548022435c4b58d4835a715cbb26c24aa44e6b7d
Author: Sunita Nadampalli <nadampal@amazon.com>
Date:   Thu Jun 30 02:39:25 2022 +0000

    implement acl gemm runtime for xla dot emitter
    
    Note: This work is derived from OneDNN code which was published
    with the following copyright statements:
    Copyright 2021 Arm Ltd. and affiliates.

commit 3621e227b68aee3f327679d09489ff41f23b87e2
Author: Sunita Nadampalli <nadampal@amazon.com>
Date:   Thu Jun 30 02:32:06 2022 +0000

    Add Arm Compute Library (ACL) build option to bazel config
    
    Add ACL standalone build option to enable direct linking to TF libraries

commit ff0d5677c9c4f74da8e086429377cdca544c2d78 (origin/master, origin/HEAD)
Author: Mihai Maruseac <mihaimaruseac@google.com>
Date:   Wed Jun 29 19:31:43 2022 -0700

    Fix TF broken by LLVM integrate
    
    Reverts the patch for https://github.com/llvm/llvm-project/commit/6901607822ccb2bcd0f373adfa9e91c3f7da7929 as it is now included in the new integrate
    
    PiperOrigin-RevId: 458117843
```

**Comment by d0k** [comment]
Does it work when you checkout d74695c directly? I didn't make any other conscious changes to your PR except for that TODO, but the copybara process does a bunch of automated modifications to BUILD files and I hope I didn't mess anything up there.

Sadly, your PR was automatically reverted after CI found a failing build that runs with threads disabled 9e815926c4d6a7324e141ee98622aefcc476055e. The thread pool is `nullptr` in that case, crashing inside of the batch matmul runtime function. I'm trying to reland it with a simple fix, checking `ShouldUseMultiThreadedEigen(hlo_module_config)` before emitting a call to Eigen batch matmul.

**Comment by snadampal** [comment]
I'm testing on aarch64 system, with https://github.com/tensorflow/tensorflow/commit/d74695c1097b181e4fe6b68e47b620053ce4a073 checked out, the default config builds fine, but not the '--config=mkl_aarch64'. would you be able to make sure mkl_aarch64 build is also tested before merging the PR.  Recently we've setup aarch64 ci/cd for tensorflow
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.cpu.arm64
Is there something I can help with?

**Comment by d0k** [comment]
I don't have a setup to debug that build configuration and I'm still busy resolving breakages from your batch matmul change. What is broken for mkl_aarch64?

**Comment by snadampal** [comment]
Here is the build failure with 'mkl_aarch64' config. I'm not able to reproduce the error if I manually apply the PR. That's why I'm wondering what was so different in the merge commit. At first look nothing obvious I can make out, there have been more BUILD file changes, but they all look like for rearranging the includes in alphabetical order, and remove the unused includes.

> ERROR: /home/ubuntu/workplace/tensorflow/tensorflow/compiler/xla/service/cpu/BUILD:861:11: Compiling tensorflow/compiler/xla/service/cpu/runtime_matmul_acl.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 107 arguments skipped)
> tensorflow/compiler/xla/service/cpu/runtime_matmul_acl.cc: In function 'int32_t {anonymous}::MatMulF32(const void*, float*, float*, float*, int64_t, int64_t, int64_t, int64_t, int32_t, int32_t)':
> tensorflow/compiler/xla/service/cpu/runtime_matmul_acl.cc:123:4: error: no matching function for call to 'call_once(std::once_flag&, {anonymous}::MatMulF32(const void*, float*, float*, float*, int64_t, int64_t, int64_t, int64_t, int32_t, int32_t)::<lambda()>)'
>   123 |   });
>       |    ^
> In file included from tensorflow/compiler/xla/service/cpu/runtime_matmul_acl.cc:19:
> external/com_google_absl/absl/base/call_once.h:206:6: note: candidate: 'template<class Callable, class ... Args> void absl::lts_20211102::call_once(absl::lts_20211102::once_flag&, Callable&&, Args&& ...)'
>   206 | void call_once(absl::once_flag& flag, Callable&& fn, Args&&... args) {
>       |      ^~~~~~~~~
> external/com_google_absl/absl/base/call_once.h:206:6: note:   template argument deduction/substitution failed:
> tensorflow/compiler/xla/service/cpu/runtime_matmul_acl.cc:121:19: note:   cannot convert 'flag_once' (type 'std::once_flag') to type 'absl::lts_20211102::once_flag&'
>   121 |   absl::call_once(flag_once, [&]() {
>       |                   ^~~~~~~~~
> Target //tensorflow/compiler/xla/tests:dot_operation_test_cpu failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 60.098s, Critical Path: 5.43s
> INFO: 441 processes: 69 internal, 372 local.
> FAILED: Build did NOT complete successfully
> //tensorflow/compiler/xla/tests:dot_operation_test_cpu          FAILED TO BUILD
> 
> FAILED: Build did NOT complete successfully

**Comment by snadampal** [comment]
great relief! thanks!! 
coming back to my original request, is there a way I can test the final changes on aarch64 before merging them? your feature branch or something like that??

**Comment by d0k** [comment]
I'm afraid there is no option of sharing the changes, they're not living in a git branch. I just managed to re-land the PR c7bfba1d8a8700168c24d18f869886466ce0d54a. This includes the fix for multithreading I described above and also doesn't have the issue with call_once. Let me know if there are any issues left.

**Comment by snadampal** [comment]
Hi @d0k , I have verified the commit c7bfba1d8a8700168c24d18f869886466ce0d54a on aarch64 and everything is working as expected! Appreciate your efforts in merging it along with handling the null thread pool scenario !!

**Comment by snadampal** [comment]
Hi @elfringham , are you compiling the tests with the updated 'mkl_aarch64' bazel config? Please note that this PR adds "build:mkl_aarch64 --define=build_with_acl=true".

build_with_acl is used in xla to enable ACL runtime,  and '__xla_cpu_runtime_ACLMatMulF32' is part of  that.

I was able to build xla unit tests with 'mkl_aarch64' without any errors. Which unit tests are you running?

**Comment by elfringham** [comment]
@snadampal The Jenkins job Linaro runs every night does a checkout of git HEAD and builds it in a fresh docker container, so yes it has the updated bazel config and it is a clean build. You can see the flags and tests that we use in the linked log. Basically we run as much as we can, which is over 3000 tests currently.
https://ci.linaro.org/job/ldcg-python-manylinux-tensorflow-onednn-nightly/108/consoleText

**Comment by snadampal** [comment]
raised this [PR](https://github.com/tensorflow/tensorflow/pull/56715) to address the unit tests.

**Comment by elfringham** [comment]
@snadampal You need to address the buildifier failure on your PR. You have an added line that is not in alphabetical order in the list. This is why the required presubmit test "Code Check - Changed Files" is failing. See #56673 for the details on that.

**Pull request merged**
