### PR TITLE
[NVIDIA TF] Enable BF16 BiasAdd

### PR DESCRIPTION
**Pull request by trevor-m**
Adds GPU BF16 kernel and tests for BiasAdd op.

Uses @kaixih's `GpuAtomicAdd` from https://github.com/tensorflow/tensorflow/pull/57674

### CODE REVIEW

**Review by reedwm — APPROVED** [review]
Not sure if this can be merged as-is since https://github.com/tensorflow/tensorflow/pull/57674 and this CL both modified the same `gpu_device_functions.h` file in the same way. Let's find out.

**Comment by trevor-m** [comment]
> Not sure if this can be merged as-is since #57674 and this CL both modified the same `gpu_device_functions.h` file in the same way. Let's find out.

Thanks, let me know if I need to rebase.

**Comment by reedwm** [comment]
No need to rebase. But this is failing with the environment variable `TF2_BEHAVIOR=1` (you can run with `--test_env=TF2_BEHAVIOR=1` to reproduce the failure). The issue is `bias_op_base.py` calls l2_loss, which doesn't yet support BF16. Probably the easiest way to fix is to cast the input of l2_loss to fp32 when bf16 is used.

**Comment by trevor-m** [comment]
> No need to rebase. But this is failing with the environment variable `TF2_BEHAVIOR=1` (you can run with `--test_env=TF2_BEHAVIOR=1` to reproduce the failure). The issue is `bias_op_base.py` calls l2_loss, which doesn't yet support BF16. Probably the easiest way to fix is to cast the input of l2_loss to fp32 when bf16 is used.

Got it, I was planning on adding L2Loss anyway so I opened a PR for that https://github.com/tensorflow/tensorflow/pull/58608
We can try this one again once L2Loss is merged.

**Comment by reedwm** [comment]
BF16 L2Loss is only supported on the GPU, but the BiasAdd BF16 tests in this PR run with both CPU and GPU. So it's still failing.

I would either use cast the L2 Loss input to FP32 or only run these tests with BF16 if there is a GPU.

**Review by reedwm — APPROVED** [review]

**Pull request merged**
