### PR TITLE
Optimize all reduce v2

### PR DESCRIPTION
**Pull request by chengmengli06**
the original dense all reduce is not efficient, update to a more efficient one.

### CODE REVIEW

**Comment by chengmengli06** [comment]
@googlebot I consent.

**Comment by mihaimaruseac** [comment]
We never patch the nightly branch. Please open/rebase against `master`

**Comment by gbaned** [comment]
@chengmengli06  Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Comment by mihaimaruseac** [comment]
Closing since this is against nightly branch which we don't update

**Pull request closed without merging**
