### PR TITLE
Compute F1 score multilabel classifier #27171 #27446

### PR DESCRIPTION
**Pull request by shashvatshahi1998**
Compute F1 score multilabel classifier #27171

### CODE REVIEW

**Comment by shashvatshahi1998** [comment]
@alextp I know you closed same PR for not affecting the code base but I literally want to work on this issue s can you please tell me the files where I can add these changes so that it can affect the files.

**Comment by alextp** [comment]
@shashvatshahi1998 This is a one-file change which only affects private symbols in TF. It also has no tests and no documentation.

So I don't understand how this tries to fix the issue.

**Comment by gbaned** [comment]
@shashvatshahi1998  Did you get a chance to look on reviewer comments? Please let us know on the update. Thanks!

**Comment by gbaned** [comment]
@shashvatshahi1998 gentle ping to check reviewer comments and let us know on the update. Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
