### PR TITLE
Update layers_test.py

### PR DESCRIPTION
**Pull request by shreyneil**
Hello!
I have merged the two pull requests i have made earlier (https://github.com/tensorflow/tensorflow/pull/13829 and https://github.com/tensorflow/tensorflow/pull/13864) with reference to the issue https://github.com/tensorflow/tensorflow/issues/11673 .
Please suggest if any more changes are required.

### CODE REVIEW

**Comment by vrv** [comment]
Okay we'll look at that other PR that has both the test change and the feature change in one PR, thanks

**Comment by shreyneil** [comment]
sir this that PR which has both the merged pull requests.

**Comment by vrv** [comment]
I only see one file in this commit, see: https://github.com/tensorflow/tensorflow/pull/13877/files

**Review by shreyneil — COMMENTED** [review]
The other change had been inculcated prior to this and merged with my master branch.

**Comment by vrv** [comment]
Can you just use the branch in https://github.com/tensorflow/tensorflow/pull/13829 and fix everything up there?  Thanks

**Pull request closed without merging**
