### PR TITLE
Fix a bug in tf.multiply documentation

### PR DESCRIPTION
**Pull request by ssinad**
In this commit, a bug that caused "NOTE: `tf.multiplytiply` supports broadcasting." to appear on tf.multiply documentation page was fixed.
See https://www.tensorflow.org/api_docs/python/tf/multiply

### CODE REVIEW

**Comment by ssd352** [comment]
I signed it!

**Review by MarkDaoust — APPROVED** [review]

**Comment by ssd352** [comment]
I'm not really sure about the second commit Mark has made. If you take a look at the following file, you'll see the word `Mul` not `Multiply`.
https://github.com/tensorflow/tensorflow/blob/4e69e02241067129379f73dd4fefe57f0a12bdc9/tensorflow/core/api_def/base_api/api_def_Mul.pbtxt

**Comment by MarkDaoust** [comment]
> You'll see the word Mul not Multiply.

Yes. But at the point when this replacement is run, it's already been switched to `Multiply`, or there wouldn't be the trailing "tiply". Also, look at the [c api doc for the op](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/multiply)

same for [`Sub`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_Sub.pbtxt), and it's [generated docs](https://www.tensorflow.org/api_docs/python/tf/subtract), the only reason it didn't fail the same way is that it had the back-quotes in the replace string.

So I think this is correct.

**Comment by ekelsen** [comment]
Looks like you have some lint problems.

**Comment by protoget** [comment]
Re @ssd352 please fix the lint problem then we can merge.

**Comment by ssd352** [comment]
I am sorry but I don't know what the lint problem is. I just changed a few characters, that's all.

**Comment by MarkDaoust** [comment]
It takes some clicking to find the failed test report.
It turns out the problem was "line too long" on both.

Fixed, as suggested by `g4 fix`

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jhseu** [comment]
Looks like an equivalent fix was merged. Thanks for your pull request!

**Pull request closed without merging**
