### PR TITLE
Lr workaround for wrapped  optimizers

### PR DESCRIPTION
**Pull request by bhack**
Investigate side effects in CI tests with a Workaround for mixed precision hyper access with wrapped optimizers.

See:
https://github.com/tensorflow/addons/pull/2404

### CODE REVIEW

**Comment by reedwm** [comment]
It looks like this passes tests and will fix tensorflow/addons#2404, but I have two concerns:

1. We assume an optimizer is an optimzier wrapper if and only if it has an `_optimizer` attribute. But an optimizer wrapper could store the inner optimizer in a different attribute (say `_inner_optimizer`) and it's possible for a non-wrapper to have an attribute called `_optimizer`.
2. This approach doesn't work with triply nested optimizers. E.g. if LossScaleOptimizer wrapps Lookahead which wraps SWA which wraps Adam.

I think we either need a stable overridable method which gets the hypereparameters, or have an `OptimizerWrapper` class which all optimizers use and handles this case. I prefer the former, and will try to come up with more solutions.

**Comment by reedwm** [comment]
Another potential solution would be to require (by convention) that all optimizer wrappers expose an `_optimizer` wrapper, which takes care of (1). For (2), we keep accessing the `_optimizer` attribute in a loop until we get the inner-most optimizer.

/CC @omalleyt12

**Comment by bhack** [comment]
> Another potential solution would be to require (by convention) that all optimizer wrappers expose an _optimizer wrapper, which takes care of (1)

Yes sorry I supposed that `_optimizer` was already a quite  "de-facto" standard.

**Comment by reedwm** [comment]
Closing as tensorflow/addons#2403 has been fixed.

**Comment by bhack** [comment]
Just as reference fixed in Tensorflow for `learning_rate` hyper with commit: https://github.com/tensorflow/tensorflow/commit/31d58c65625592453cb9456e9cf663d891de599e

**Pull request closed without merging**
