### PR TITLE
Fix quantizing graph with control flows

### PR DESCRIPTION
**Pull request by wodesuck**
Related to #7162

### CODE REVIEW

**Comment by drpngx** [comment]
@petewarden any thoughts?

**Review by petewarden — DISMISSED** [review]
Looks good, thanks!

**Comment by lissyx** [comment]
@petewarden Working on RNN as part of DeepSpeech and trying to get things up and running, I have been relying on that patch for a while already. You may want to be aware that a slight variation is actually required otherwise there's a very big performance impact. I have not been the only one observing this, as you can see at https://github.com/tensorflow/tensorflow/issues/7162#issuecomment-307994191

**Comment by vrv** [comment]
@lissyx are you suggesting that this PR as written needs to be fixed?  if so would you like to comment on what needs to be changed?

**Comment by lissyx** [comment]
@vrv Well, it is not really that I am stating this PR is wrong, I'm not really in position to judge, and it does indeed fix the issue. However, this will add the node input for any case, not just the broken control flow ones. And experience proved that to come with a non neglicitble perf regression, not only documented by me but others on https://github.com/tensorflow/tensorflow/issues/7162#issuecomment-307994191.

Now, maybe it is wrong to add the input only on /some nodes/ and the correct fix is indeed the one in this PR, or maybe we just need the PR to be more specific to those nodes. I tried to do something nicer than what was suggested by the very same author of the PR: https://github.com/tensorflow/tensorflow/issues/7162#issuecomment-307994191 but I could not find quickly a nicer way to change the `float_node.name().find("/while/") != string::npos` to something more robust.

**Comment by lissyx** [comment]
@wodesuck Maybe you can elaborate, after all you are the one who confirmed me the perf regression and how you circumvented that :)

**Comment by vrv** [comment]
@petewarden I'm going to hold off on merging until you can re-approve to make sure you're okay with this.

**Comment by wodesuck** [comment]
@petewarden Are there any way to identify whether a node is in a control loop or not, so that I could only add control inputs on those nodes. Otherwise maybe I should add `float_node.name().find("/while/") != string::npos` in this PR, which is a dirty solution but good enough for quantizing `dynamic_rnn`.

**Comment by rmlarsen** [comment]
@wodesuck can you sign the CLA?
@petewarden could you have another look, please?

**Comment by pks** [comment]
For me the exception changes from this

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'model.0_1/decoder/attention/while/attention_1/mul_eightbit/model.0_1/decoder/attention/while/attention_1/mul/Enter/reshape' has inputs from different frames. The input 'model.0_1/decoder/attention/while/attention_1/mul/Enter' is in frame 'model.0_1/decoder/attention/while/model.0_1/decoder/attention/while/'. The input 'encoder_1/layer-0/fw/lstm_block_wrapper/mul_eightbit/encoder_1/layer-0/fw/lstm_block_wrapper/BlockLSTM__port__6/reshape_dims' is in frame ''.
```

 ... to this

```
ValueError: graph_def is invalid at node 'encoder_1/layer-0/bw/lstm_block_wrapper/mul_eightbit/encoder_1/layer-0/bw/lstm_block_wrapper/BlockLSTM__port__6/reshape_dims': Control input '^encoder_1/layer-0/bw/lstm_block_wrapper/BlockLSTM:6' not found in graph_def..
```

... after applying the proposed fix.

I'm trying to apply quantize_weights + quantize_nodes to a series of RNNs. ```quantize_weights``` works fine, but ```quantize_nodes``` fails with any available tool.

**Comment by wodesuck** [comment]
@pks Seem cause by `:6` in the name `^encoder_1/layer-0/bw/lstm_block_wrapper/BlockLSTM:6`, making it an invalid control input name, maybe you could try striping it to `^encoder_1/layer-0/bw/lstm_block_wrapper/BlockLSTM` and see if your model work or not. I would modify this pr once you confirm it.

**Comment by drpngx** [comment]
@pks @lissyx please chime in so we can merge this PR.

**Comment by lissyx** [comment]
@drpngx Sorry, I'm not sure what you need from me.

**Comment by sb2nov** [comment]
@petewarden ping for review

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
@petewarden said LGTM, so I'll assume he means it.

**Review by martinwicke — APPROVED** [review]

**Comment by snownus** [comment]
now, when I use quantize_nodes, it will appear tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'map/while/ToAbsoluteCoordinates/Scale/mul_eightbit/map/while/ToAbsoluteCoordinates/Scale/split/reshape' has inputs from different frames. The input 'map/while/ToAbsoluteCoordinates/Scale/split' is in frame 'map/while/map/while/'. The input 'SecondStagePostprocessor/Reshape_2_eightbit/SecondStagePostprocessor/Tile/reshape_dims' is in frame ''

Is there any solutions for this? When applied only quantize_weights, it is ok.

**Comment by snownus** [comment]
I have addressed the problem, but in faster rcnn, when I used quantize nodes, it appears ValueError: graph_def is invalid at node u'Decode/get_center_coordinates_and_sizes/add_1_eightbit/Decode/get_center_coordinates_and_sizes/unstack__port__1/reshape_dims': Control input '^Decode/get_center_coordinates_and_sizes/unstack:1' not found in graph_def..

**Comment by snownus** [comment]
It doesn't have running time error now. Thanks very much for your help! I
have tried fix this problem several days. And it seems the error comes from
control flow.

May i know why NodeNameFromInput works but not input_name? Is it current
node will find another dependency node from this function?

Thanks again for your contribution.

Warm regards,
Xue

**Comment by snownus** [comment]
@wodesuck  It doesn't have running time error now. Thanks very much for your help! I
have tried fix this problem several days. And it seems the error comes from
control flow.

May i know why NodeNameFromInput works but not input_name? Is it current
node will find another dependency node from this function?

Thanks again for your contribution!

**Comment by snownus** [comment]
@wodesuck It appears another error:
 [[Node: SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_1/Area/mul_eightbit/SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_1/Area/sub_1/quantize = QuantizeV2[T=DT_QUINT8, mode="MIN_FIRST", round_mode="HALF_AWAY_FROM_ZERO", _device="/job:localhost/replica:0/task:0/device:CPU:0"](SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_1/Area/sub_1/_1125, SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_1/Area/mul_eightbit/SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_1/Area/sub_1/min/_1127, SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_1/Area/mul_eightbit/SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_1/Area/sub_1/max/_1129)]]

**Comment by snownus** [comment]
@wodesuck 

InvalidArgumentError (see above for traceback): input_max_range must be larger than input_min_range.
	 [[Node: SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_2/Area/mul_eightbit/SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_2/Area/sub_1/quantize = QuantizeV2[T=DT_QUINT8, mode="MIN_FIRST", round_mode="HALF_AWAY_FROM_ZERO", _device="/job:localhost/replica:0/task:0/device:CPU:0"](SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_2/Area/sub_1/_1355, SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_2/Area/mul_eightbit/SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_2/Area/sub_1/min/_1357, SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_2/Area/mul_eightbit/SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow_2/Area/sub_1/max/_1359)]]
	 [[Node: SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ChangeCoordinateFrame/Scale/mul_1/_1255 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_5246_SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ChangeCoordinateFrame/Scale/mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by wodesuck** [comment]
@snownus `NodeNameFromInput` just simply strip `:1` at the end of input name, so that the control input would have a correct name. (tf doesn't allow `:x` in control input name)

For you second question, I have saw it once, cause by an empty tensor. `Quantize` need `min < max`, and for an empty tensor `x`, `min(x) = inf` and `max(x) = -inf`, which will break the constraint. I solve it by modify the tf kernel. I am not 100% sure that your problem cause by the same reason as mine, but hope those information helps you.

**Comment by snownus** [comment]
@wodesuck Thanks for your explanation...  And one more question about the kernel modification, can you show more details? And it's weird that the error often occurs after several running.

**Comment by wodesuck** [comment]
In `tensorflow/core/kernels/quantize_op.cc`, add few lines as below:

```
  void Compute(OpKernelContext* ctx) override {
    const Tensor& input = ctx->input(0);
    const float input_min_range = ctx->input(1).flat<float>()(0);
    const float input_max_range = ctx->input(2).flat<float>()(0);

    if (input.NumElements() == 0) {
      Tensor* output = nullptr;
      OP_REQUIRES_OK(ctx, ctx->allocate_output(0, input.shape(), &output));

      Tensor* output_min_tensor = nullptr;
      OP_REQUIRES_OK(ctx, ctx->allocate_output(1, {}, &output_min_tensor));
      output_min_tensor->flat<float>()(0) = 0.0;

      Tensor* output_max_tensor = nullptr;
      OP_REQUIRES_OK(ctx, ctx->allocate_output(2, {}, &output_max_tensor));
      output_max_tensor->flat<float>()(0) = 1.0;

      return;
    }

    float min_range;
    float max_range;
    OP_REQUIRES(ctx, !(input_max_range < input_min_range),
                errors::InvalidArgument(
                    "input_max_range must be larger than input_min_range."));
```

It just detect whether input is empty or not, if yes, just set `min = 0.0, max = 1.0`. (for it's empty, the value of minmax may not matter, I think)

**Comment by snownus** [comment]
@wodesuck , thanks for your help!

**Comment by snownus** [comment]
@wodesuck , I run the program and found similar errors in requested_output_min_float and requested_output_max_float (requantize.cc) and update the code following your provided but, the final performance is quite lower.  Do u have any suggestions?

**Comment by wodesuck** [comment]
@snownus 

The simplest thing you could do is try only add control input to nodes in a `tf.while_loop`. (as disscusions in https://github.com/tensorflow/tensorflow/issues/7162#issuecomment-307994191).

Then, you could do some benchmark with [benchmark_model](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark) and [timeline](https://towardsdatascience.com/howto-profile-tensorflow-1a49fb18073d), to find the bottleneck of your model.

The last suggestion, I have found that `QuantizedMatMul` could speed up if `transpose_b=True`, so a general trick is pre-transposing all the weight matrices.

**Comment by dreamibor** [comment]
Great, this solved my problem, Thank you!

**Comment by dreamibor** [comment]
@wodesuck @snownus Hi, Thank you for your great talk, I am also trying to figure out this problem. So basically, if I use NodeNameFromInput(input_name), the quantized model will say errors like: "
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_2/lstm_cell/LSTMBlockCell' has inputs from different frames. The input 'model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_2/lstm_cell/LSTMBlockCell/Enter_1' is in frame 'model/inference/decoder/while/while_context'. The input 'model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_1/lstm_cell/zeros' is in frame ''.
"
but if I use the input_name directly, because the tensorflow system does not allow node_name followed by :x, so I got the error:"
ValueError: graph_def is invalid at node 'model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/MatMul_eightbit/model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_2/lstm_cell/LSTMBlockCell__port__6/reduction_dims': Control input '^model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_2/lstm_cell/LSTMBlockCell:6' not found in graph_def..
"
Any intelligent advice? Thank you!

**Comment by rzou15** [comment]
> @wodesuck @snownus Hi, Thank you for your great talk, I am also trying to figure out this problem. So basically, if I use NodeNameFromInput(input_name), the quantized model will say errors like:
> "
> tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_2/lstm_cell/LSTMBlockCell' has inputs from different frames. The input 'model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_2/lstm_cell/LSTMBlockCell/Enter_1' is in frame 'model/inference/decoder/while/while_context'. The input 'model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_1/lstm_cell/zeros' is in frame ''.
> "
> but if I use the input_name directly, because the tensorflow system does not allow node_name followed by :x, so I got the error:
> "
> ValueError: graph_def is invalid at node 'model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/MatMul_eightbit/model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_2/lstm_cell/LSTMBlockCell__port__6/reduction_dims': Control input '^model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_2/lstm_cell/LSTMBlockCell:6' not found in graph_def..
> "
> Any intelligent thoughts? Thank you!

I met the same problem when quantizing Transformer model graph nodes. Have you solved it? Mnay thx!

**Pull request merged**
