### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jsrimr**
previous link shows only .gitignore which doesn't provide any information

### CODE REVIEW

**Comment by gbaned** [comment]
@jsrimr  Can you please sign CLA. Thanks!

**Comment by jsrimr** [comment]
> @googlebot I signed it

**Comment by jsrimr** [comment]
> @jsrimr Can you please sign CLA. Thanks!

I forgot to reply to the bot. Now I signed!

**Comment by jdduke** [comment]
Over to Khanh for review.

**Review by khanhlvg — APPROVED** [review]

**Pull request merged**
