### PR TITLE
[INTEL MKL] Fix for failure in conv_ops_test

### PR DESCRIPTION
**Pull request by agramesh1**
Don't fuse conv ops when dtype is not DT_FLOAT.

### CODE REVIEW

**Comment by agramesh1** [comment]
Pinging @tatianashp for review.

**Review by tatianashp — APPROVED** [review]
Thanks for fixing the test.

**Comment by agramesh1** [comment]
@caisq can you merge this PR? Thanks

**Comment by caisq** [comment]
@agramesh1 Thanks for the reminder. I'll kick off the tests and if they pass, merge the PR.

**Comment by rthadur** [comment]
Closing this PR as the changes were pushed part of #24617

**Pull request closed without merging**
