### PR TITLE
Added a hyperparameter beta in swish activation function.

### PR DESCRIPTION
**Pull request by MrinalTyagi**
As described in (https://arxiv.org/abs/1710.05941) swish consists of a beta hyperparamter that is inputted in the sigmoid activation function. Implemented to paramter beta with default value of 1.0 in order to replicate the same behavior as current if no value is provided.

### CODE REVIEW

**Comment by MrinalTyagi** [comment]
@googlebot I signed it!

**Comment by MrinalTyagi** [comment]
@sanjoy @yongtang Hello guys. I am new in committing to open source. Can anyone guide me on how to proceed further in this pull request?

**Comment by MrinalTyagi** [comment]
@sanjoy Could you please have a look at the pr and update me with the required changes if there are any?

**Comment by MrinalTyagi** [comment]
I have updated the gradient calculation formulae.

**Comment by MrinalTyagi** [comment]
@rohan100jain Sir could you please review the PR. Thank you for your time.

**Comment by gbaned** [comment]
@rohan100jain Can you please review this PR ? Thanks!

**Review by rohan100jain — CHANGES_REQUESTED** [review]

**Review by rohan100jain — APPROVED** [review]
Thanks for doing this!

**Review by rohan100jain — APPROVED** [review]

**Review by rohan100jain — APPROVED** [review]

**Comment by MrinalTyagi** [comment]
Still same issue :(

**Comment by rohan100jain** [comment]
I'm working with the internal failures to push this change through. Apologies for the rollback.

**Comment by MrinalTyagi** [comment]
> I'm working with the internal failures to push this change through. Apologies for the rollback.

Let me know if I can help in any way. Thanks for the cooperation. :)

**Comment by MrinalTyagi** [comment]
@rohan100jain any update on the issue?

**Comment by rohan100jain** [comment]
Working on it. I am to push the change through by tomorrow at the latest.

**Comment by MrinalTyagi** [comment]
> Working on it. I am to push the change through by tomorrow at the latest.

Thank you for the update :)

**Pull request merged**
