### PR TITLE
Additional  FreeBSD compatibility 

### PR DESCRIPTION
**Pull request by xeonvs**
In this commit some additional changes to increase compatibility with FreeBSD.
Also i have some little patches for gcs & ignite, but I do not know if they should be included in the master branch.

### CODE REVIEW

**Comment by xeonvs** [comment]
I've signed the CLA.

**Comment by aaroey** [comment]
@rthadur I'm not familiar with the changed files, please help to find other appropriate reviews.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @gunan: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Review by gunan — DISMISSED** [review]

**Review by gunan — DISMISSED** [review]

**Review by gunan — APPROVED** [review]

**Comment by arrowd** [comment]
For some reason GitHub doesn't let me to add comments inline, so I'll ask here.

What's the reason for the change in `tensorflow/lite/toco/BUILD`?

**Comment by xeonvs** [comment]
> What's the reason for the change in `tensorflow/lite/toco/BUILD`?
Build failed when package neon is installed in system. I think this is version\patches conflict. This is dependency solves build error independent of system packages.

**Comment by arrowd** [comment]
Are you talking about `www/neon`?

If so, the change seems right, but it shouldn't be constained to FreeBSD only, as any Linux can have `neon` installed from system package manager. Any TensorFlow dev to comment on that?

**Comment by xeonvs** [comment]
> Are you talking about `www/neon`?
Yes, but now i read description this package and this should not influence. I think it's FreeBSD specific dependency resolve error, on Linux building are ok without this changes.

**Comment by arrowd** [comment]
For me, `bazel build //tensorflow:libtensorflow.so` succeceeds wihtout that change, and `//tensorflow/python:python` fails with unrelated error.

What error do you get without this change?

**Comment by xeonvs** [comment]
> What error do you get without this change?

ERROR: /usr/home/xeon/tensorflow/tensorflow/lite/toco/BUILD:425:1: Linking of rule '//tensorflow/lite/toco:toco' failed (Exit 1)
ld: error: undefined symbol: tflite::tensor_utils::NeonSymmetricQuantizeFloats(float const*, int, signed char*, float*, float*, float*)
>>> referenced by tensor_utils.cc
>>>               tensor_utils.o:(tflite::tensor_utils::SymmetricQuantizeFloats(float const*, int, signed char*, float*, float*, float*)) in archive bazel-out/host/bin/tensorflow/lite/kernels/internal/libtensor_utils.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by arrowd** [comment]
The `//tensorflow/lite/toco:toco` built fine for me. Maybe you need to rebase your changes onto recent HEAD?

Or try out my branch with other FreeBSD fixes added: https://github.com/tensorflow/tensorflow/pull/28689

**Comment by xeonvs** [comment]
> The `//tensorflow/lite/toco:toco` built fine for me. Maybe you need to rebase your changes onto recent HEAD?
> 
> Or try out my branch with other FreeBSD fixes added: #28689
your changes same :)
` tensorflow/lite/kernels/internal/BUILD 
 ":freebsd": [
            ":neon_tensor_utils",
        ],`

this affects to the whole tf-lite module, and not to the specific problematic toco-module

**Comment by gunan** [comment]
Closing in favor of #28689

**Pull request closed without merging**
