### PR TITLE
Updated doc for all symbols in tf.keras.activations

### LINKED ISSUE #25828: [TF 2.0 API Docs] tf.keras.activations.serialize
**System information**
- TensorFlow version: 2.0
- Doc Link: https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/keras/activations/serialize
* **Correct Links** https://github.com/tensorflow/tensorflow/blob/master/python/keras/activations.py is incorrect. The correct link should be https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/activations.py.
* **Clear Description**
  The description is not opinionated about when to use this symbol, or what happens when arguments are passed to the symbol.
* **Usage Example**
  No usage example is provided.
* **Parameters Defined**
  Parameters are poorly defined, and not formatted appropriately.
* **Returns Defined**
  Returns are not defined.
* **Raises Listed and Defined**
  Errors are not defined.

### PR DESCRIPTION
**Pull request by asmitapoddar**
Updated Descriptions, Examples, Arguments, Returns and Raises lists.

Fixes #25828

### CODE REVIEW

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
Thanks,

Mostly this looks good.

At a few places you've deleted blank lines, and those can be important. The linters will complain if there isn't a blank line after the first-line summary. It's best to keep a blank line above a codeblock.

The examples look helpful. It is worth noting that we've enabled [doctest](https://docs.python.org/3/library/doctest.html) for TensorFlow, and are in the process of converting the docstrings. So it would be cool if you could make these examples tested by switching them to use the doctest format `>>>` instead of the code fences ```.

**Comment by asmitapoddar** [comment]
> Thanks,
> 
> Mostly this looks good.
> 
> At a few places you've deleted blank lines, and those can be important. The linters will complain if there isn't a blank line after the first-line summary. It's best to keep a blank line above a codeblock.
> 
> The examples look helpful. It is worth noting that we've enabled [doctest](https://docs.python.org/3/library/doctest.html) for TensorFlow, and are in the process of converting the docstrings. So it would be cool if you could make these examples tested by switching them to use the doctest format `>>>` instead of the code fences ```.

Thank you for the suggestions. I have added the blank lines wherever required, and have converted the examples to the doctest format.

**Review by MarkDaoust — DISMISSED** [review]

**Comment by gbaned** [comment]
@asmitapoddar Could you please check failed build errors? Thanks!

**Comment by asmitapoddar** [comment]
I fixed some issues with the file to resolve the failed build errors. Does it look fine now?

**Comment by asmitapoddar** [comment]
Though the commit had passed the `import/copybara` check, I'm not sure why it shows `import/copybara — An error happened while migrating the change` now.

**Comment by MarkDaoust** [comment]
I think everything's okay on your side.

I'm fixing this internally. This should be merged soon.

**Pull request merged**
