### PR TITLE
1.12-1 cherry-pick request: Fix TfLiteTensor invalidation issue when using the Java API

### PR DESCRIPTION
**Pull request by jdduke**
Fix an issue where the Java Tensor class would hold a reference
to an invalidated TfLiteTensor instance. This issue was manifest
in certain models that add temporary tensors during execution.

PiperOrigin-RevId: 215582842

This CL is critical for 1.12 as there are several clients who were
impacted by the regression in 1.11 and are blocked on a stable fix.

### CODE REVIEW

**Comment by annarev** [comment]
Jared, can you take a look at the  clang-format error:
--- a/tensorflow/contrib/lite/java/src/main/java/org/tensorflow/lite/NativeInterpreterWrapper.java
+++ b/tensorflow/contrib/lite/java/src/main/java/org/tensorflow/lite/NativeInterpreterWrapper.java
@@ -269,9 +269,8 @@ final class NativeInterpreterWrapper implements AutoCloseable {
     }
     Tensor inputTensor = inputTensors[index];
     if (inputTensor == null) {
-      inputTensor =
-          inputTensors[index] =
-              Tensor.fromIndex(interpreterHandle, getInputTensorIndex(interpreterHandle, index));
+      inputTensor = inputTensors[index] =
+          Tensor.fromIndex(interpreterHandle, getInputTensorIndex(interpreterHandle, index));
     }
     return inputTensor;
   }
@@ -292,9 +291,8 @@ final class NativeInterpreterWrapper implements AutoCloseable {
     }
     Tensor outputTensor = outputTensors[index];
     if (outputTensor == null) {
-      outputTensor =
-          outputTensors[index] =
-              Tensor.fromIndex(interpreterHandle, getOutputTensorIndex(interpreterHandle, index));
+      outputTensor = outputTensors[index] =
+          Tensor.fromIndex(interpreterHandle, getOutputTensorIndex(interpreterHandle, index));
     }
     return outputTensor;
   }

**Review by goldiegadde — APPROVED** [review]
Also might need gunhan's approval , can you please add him as well

**Review by gunan — APPROVED** [review]
Looks like a bugfix. Approved.

**Comment by jdduke** [comment]
Hmm, this is a straight cherry-pick and matches code already in master? Do we have to fix the clang failures to land?

I can clean it up in master, but would prefer not to fix the (existing) style issue with the cherry-pick.

**Pull request merged**
