### PR TITLE
Adding exception handling code to TensorShape methods

### PR DESCRIPTION
**Pull request by SSaishruthi**
Hi,

This PR adds exception handling code to the following TensorShape methods:

1. merge_with
2. concatenate
3. assert_same_rank

Thanks.

### CODE REVIEW

**Comment by SSaishruthi** [comment]
@gunan FYI
I have similar PR for Dimension methods
https://github.com/tensorflow/tensorflow/pull/27962

**Comment by SSaishruthi** [comment]
@gbaned This PR is yet to be assigned to a reviewer.
Thanks

**Comment by gbaned** [comment]
@MarkDaoust Could you PTAL and approve.

**Comment by SSaishruthi** [comment]
@MarkDaoust Made some minor updates to the code.

**Comment by gbaned** [comment]
@MarkDaoust can you please review this PR ?

**Comment by SSaishruthi** [comment]
Output after changes:

```
>>> import tensorflow as tf
>>> a = tf.TensorShape(['30'])
>>> a.merge_with('30')
(<class 'TypeError'>, '::', TypeError('A string has ambiguous TensorShape, please wrap in a list or convert to an int: 30'))
```

Before changes:
```
>>> import tensorflow as tf
>>> a = tf.TensorShape(['30'])
>>> a.merge_with('30')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saishruthi.tn@ibm.com/anaconda3/envs/cp/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 841, in merge_with
    other = as_shape(other)
  File "/Users/saishruthi.tn@ibm.com/anaconda3/envs/cp/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1125, in as_shape
    return TensorShape(shape)
  File "/Users/saishruthi.tn@ibm.com/anaconda3/envs/cp/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 670, in __init__
    "list or convert to an int: %s" % dims)
TypeError: A string has ambiguous TensorShape, please wrap in a list or convert to an int: 30
```
Basically, handling raised exception and displaying only the needed information as the message is clear

**Pull request closed without merging**
