### PR TITLE
[INTEL oneDNN] Refactoring: remove MKL ML API calls

### PR DESCRIPTION
**Pull request by gzmkl**
The PR removes obsolete MKL ML API calls, including all related functional calls and unit tests.

This PR will replace
 this old public PR ( I will close)

https://github.com/tensorflow/tensorflow/pull/60292

Removed functionality in runtime_matmul_mkl.cc/h will be included in a follow-up PR
     https://github.com/tensorflow/tensorflow/pull/61237
which depends on the merge of this one.

### CODE REVIEW

**Review by DocKustom — CHANGES_REQUESTED** [review]
runtime_matmul_mkl

**Comment by gzmkl** [comment]
> runtime_matmul_mkl

I removed it from BUILD. THANKS

**Comment by penpornk** [comment]
https://github.com/tensorflow/tensorflow/pull/61237 was brought back with commit https://github.com/tensorflow/tensorflow/commit/765314dd0b5e3fae242c9b7441ce1bda3daa8070. Does this PR need to be updated again?

**Comment by gzmkl** [comment]
> #61237 was brought back with commit [765314d](https://github.com/tensorflow/tensorflow/commit/765314dd0b5e3fae242c9b7441ce1bda3daa8070). Does this PR need to be updated again?

YES, I will patch back the changes in my 2nd commit today

**Comment by gzmkl** [comment]
@penpornk  I updated this PR. Please help to review

**Review by penpornk — APPROVED** [review]
Thank you for the update!

**Pull request merged**
