### PR TITLE
[ROCm] Adding no_rocm tag to tests that started failing after the 200129 weekly sync

### PR DESCRIPTION
**Pull request by deven-amd**
/cc @whchung @chsigg

### CODE REVIEW

**Review by chsigg — DISMISSED** [review]

**Comment by gbaned** [comment]
@deven-amd Can you please resolve conflicts? Thanks!

**Comment by deven-amd** [comment]
@gbaned , I have rebased the PR to resolve the merge conflict.

**Comment by deven-amd** [comment]
@gbaned, gentle ping

**Comment by deven-amd** [comment]
gentle ping

**Comment by deven-amd** [comment]
gentle ping

**Review by cheshire — APPROVED** [review]

**Pull request merged**
