### PR TITLE
[INTEL MKL] MKL DNN 0.x code clean -- pooling ops

### PR DESCRIPTION
**Pull request by gzmkl**
DNN 0.x cleanup of MKL Avg/Max pooling ops and related base classes/utilities:

(1) Remove all DNN 0.x related code;

(2) Replace all DNN 1.x macro usages

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR and I'm so sorry for the delay!

**Comment by gbaned** [comment]
@gzmkl  Can you please resolve conflicts? Thanks!

**Comment by gzmkl** [comment]
@gbaned merge conflicts should have been addressed. thanks

**Review by penpornk — APPROVED** [review]
Thank you again for the PR!

**Pull request merged**
