### PR TITLE
Suppress all warnings that appear >100 times in windows cmake build.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Review by mrry — APPROVED** [review]
Looks good to me! How much does it reduce the log size?

**Comment by drpngx** [comment]
Nice, thanks!

**Comment by gunan** [comment]
We will see right now, after the above tests run :)

**Comment by drpngx** [comment]
Roughly: 
* build 134 (which includes other commits), 33MB, 107k lines
* build 139, 3.7MB, 21k lines

**Comment by mrry** [comment]
That's a nice improvement :). It looks like there's a lot of other chaff arising from an unknown compiler option - looking at the vcxproj files it seems as if two of the flags are being concatted together... I'll see what I can do in another PR.

**Comment by gunan** [comment]
ah, I need to resolve conflicts now.
Will do that

**Pull request merged**
