### PR TITLE
[INTEL MKL] Remove unnecessary oneDNN dependency.

### PR DESCRIPTION
**Pull request by agramesh1**
Removes the redundant inclusion of oneDNN in libtensorflow_framework.so.2.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the clean-up! :)

**Comment by rthadur** [comment]
@agramesh1 can you please check for sanity build failures ?

**Comment by agramesh1** [comment]
> @agramesh1 can you please check for sanity build failures ?

@gbaned pushed an update to fix the issue. Thanks.

**Review by penpornk — APPROVED** [review]
Thank you for the fix!

**Review by gbaned — APPROVED** [review]

**Pull request merged**
