### PR TITLE
boringssl sha256 checksum mismatched

### PR DESCRIPTION
**Pull request by facaiy**
issue #12986 .

### How to test 

+ [ ] confirmed by #12752 @louiehelm @gunan

### CODE REVIEW

**Comment by drpngx** [comment]
How can the SHA be off?

**Comment by gunan** [comment]
This also happened for gemmlowp.
Someone mentioned github regenerated all their compressed archive files which can explain all these failures.

Since we also have a mirror, this is not as simple. I would like to triage this internally and push out the change.

**Comment by facaiy** [comment]
So the best way is to stop check SHA for Github, right?

**Comment by gunan** [comment]
No, we will try to find a stable source for our dependencies. We will always enforce sha checks whenever we depend on other repositories.

**Pull request closed without merging**
