### PR TITLE
remove warnings when compiling this as a c header.

### PR DESCRIPTION
**Pull request by kingofthebongo2008**
There are some compile errors with visual studio 2017.
These consts are not c compatible

### CODE REVIEW

**Comment by skye** [comment]
We can't commit this change because it breaks the semantics of TF_WhileParams (e.g. changing `TF_Graph* const` to `const TF_Graph*` means you can no longer edit the graph, but can change the pointer value). I'm surprised the compiler is complaining, what errors are you seeing?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request closed without merging**
