### PR TITLE
extract common function for start abort rendezvous

### PR DESCRIPTION
**Pull request by horance-liu**

### CODE REVIEW

**Review by mrry — APPROVED** [review]

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Looks like this breaks the tests. Mind taking a look?

**Comment by horance-liu** [comment]
@jhseu I'm sorry, I have fixed it.

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Pull request merged**
