### PR TITLE
Update estimator.py

### PR DESCRIPTION
**Pull request by alanyee**
Replace contrib metrics with core metrics

### CODE REVIEW

**Review by ispirmustafa — APPROVED** [review]
Thanks Alan!

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by alanyee** [comment]
@martinwicke I believe my commit was passing all the tests a couple of days ago, but now they are failing four.

**Comment by martinwicke** [comment]
This looks like infra failure.

**Comment by martinwicke** [comment]
@sb2nov FYI, ready to merge.

**Pull request merged**
