### PR TITLE
Added linker options to armv7 in iOS makefile

### PR DESCRIPTION
**Pull request by petewarden4prs**

### CODE REVIEW

**Comment by petewarden** [comment]
Jenkins, test this please.

**Comment by petewarden** [comment]
I signed it.

**Comment by petewarden** [comment]
@martinwicke Can you figure out why the CLA bot thinks I'm not authorized? I've checked the commit and it seems to have my correct google.com address attached.

**Comment by martinwicke** [comment]
Hmm. Jenkins ignored you too.

**Comment by martinwicke** [comment]
The creator of the PR shows as @petewarden4prs, not @petewarden, maybe that's why? Have you successfully created PRs from that special account before?

**Pull request closed without merging**
