### PR TITLE
Mkl filter optimization

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This pull request optimizes the MKL convolution backpropagation by avoiding extra filter data conversion.

### CODE REVIEW

**Comment by nhasabni** [comment]
Hi,

I have signed Google CLA (from Intel) for this contribution already, and have made several contributions to Tensorflow so far. Not sure why it is showing me that I don't have signed CLA.

**Comment by martinwicke** [comment]
Most of the time it's because the email on your commits doesn't match the email on file (or the one on github). Sadly the github UI makes it really hard to see that email.

I'll override CLA bot.

**Comment by nhasabni** [comment]
thanks @martinwicke!

**Comment by tfboyd** [comment]
Ping @rmlarsen @andydavis1

**Review by andydavis1 — APPROVED** [review]

**Comment by vivek-rane** [comment]
@tfboyd @andydavis1 @rmlarsen Please merge this one first (before 12661)

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Pull request merged**
