### PR TITLE
Fixed bug in estimator.py where [estimator]._distribution was called …

### PR DESCRIPTION
**Pull request by asaquib**
…instead of [estimator]._train_distribution causing an AttributeError.

### CODE REVIEW

**Comment by asaquib** [comment]
I signed it!

**Comment by qlzh727** [comment]
Could u please also update the unit test?

**Comment by asaquib** [comment]
Could you point me to where the previous unit test for this is, if it exists? Looked like there was a TODO for @yuefengz  to write the initial one.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yuefengz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by qlzh727** [comment]
Ping @yuefengz for review.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @yuefengz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by yuefengz** [comment]
I think we've merged two similar PRs a while ago. Could you update your repository please?

**Comment by asaquib** [comment]
Looks like on master the estimator code no longer exists here, however the bug is still present in the new location: https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/estimator.py#L1336

**Comment by yuefengz** [comment]
The new estimator has code `self._train_distribution.unwrap(per_device_hook)[0]`. Am I looking at the right file?

**Comment by asaquib** [comment]
No, that looks correct - I must have been looking at a different version and thinking it was the current master. Which Tensorflow version is/will be the first to use this estimator class?

**Comment by yuefengz** [comment]
@karmel , could you comment on TensorFlow version to use the Estimator repo?

**Comment by qlzh727** [comment]
@asaquib , can u resolve the merge conflict? Thanks.

**Comment by karmel** [comment]
@case540 -- should PRs go through tensorflow/estimator? Or here?

**Comment by case540** [comment]
tensorflow/estimator. If this change is rebased, you will see obvious errors/issues. These files now live in https://github.com/tensorflow/estimator so please create a new PR there

**Pull request closed without merging**
