### PR TITLE
Add external delegate support to the cmake build of benchmark app

### PR DESCRIPTION
**Pull request by NAgarwalla**

### CODE REVIEW

**Comment by NAgarwalla** [comment]
@terryheo, this is the separated pull request from #52866

**Comment by gbaned** [comment]
@terryheo  Can you please review this PR ? Thanks!

**Review by terryheo — APPROVED** [review]
LGTM

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by NAgarwalla** [comment]
Hi Everyone, what else is required to get this merged into master?

**Comment by terryheo** [comment]
NAgarwalla, did you sign the CLA(Contributor License Agreement)? https://www.tensorflow.org/community/contribute/code

**Comment by BrownGenius** [comment]
> NAgarwalla, did you sign the CLA(Contributor License Agreement)? https://www.tensorflow.org/community/contribute/code

Yes, the cla check passed, too. I already had another change pulled a few weeks ago.  I think someone else with privileges needs to initiate the actual pull request.

**Pull request merged**
