### PR TITLE
Fix types for tflite micro builds

### PR DESCRIPTION
**Pull request by dimtass**
When using `-Wall` then some warnings regarding types make the build fail. An example of these warnings is the next one:

`tensorflow/lite/experimental/micro/micro_interpreter.cc: In member function 'TfLiteStatus tflite::MicroInterpreter::Invoke()':
tensorflow/lite/experimental/micro/micro_interpreter.cc:104:21: warning: comparison of integer expressions of different signedness: 'int' and 'flatbuffers::uoffset_t' {aka 'long unsigned int'} [-Wsign-compare]
   for (int i = 0; i < operators_->size(); ++i) {`

With this PR I was able to build without errors using CMAKE on the stm32f746 and the listed flags:

`set (CMAKE_CXX_FLAGS "-g -mthumb -fno-builtin -mcpu=cortex-m7 -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -Wall -std=c++11 -ffunction-sections -fdata-sections -fomit-frame-pointer -mabi=aapcs -fno-unroll-loops -ffast-math -ftree-vectorize" CACHE INTERNAL "cxx compiler flags")
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lm -lc -lnosys --specs=nosys.specs")`

### CODE REVIEW

**Comment by dimtass** [comment]
Hi people. I don't know why this PR is blocked. I followed all the suggested guidelines, but I'm getting the above bot errors.

Thanks!

**Review by petewarden — DISMISSED** [review]

**Comment by gbaned** [comment]
@dimtass Could you please resolve the conflicts? Thanks!

**Comment by dimtass** [comment]
@gbaned I'm currently on holidays, therefore it may take me some time to be able to do this...

**Comment by dimtass** [comment]
Hi @gbaned, I'm on holidays so I don't have access to my stuff, but I've used the online tool to resolve this. That means that I wasn't able to build my self. I'll be able to do this in a few weeks, though.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@dimtass wondering if you still need this PR, if yes can you please resolve conflicts. Thanks!

**Comment by dimtass** [comment]
@gbaned, yes I do. If you don't mind, I'll update the PR in a couple of
weeks when I'm back, because currently I don't have access to any computer
to build and test.

gbaned <notifications@github.com> schrieb am Do., 26. Sep. 2019, 14:36:

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
gentle ping @petewarden for review ? Thanks!

**Comment by gbaned** [comment]
@dimtass Could you please resolve the conflicts? Thanks!

**Comment by dimtass** [comment]
Hi @gbaned since I'm not using TF-Lite anymore, I don't have what is needed installed on my workstation to build and check if everything is ok.
Therefore, I'll close this ticket and in the future maybe someone else that has the same problem can re-open this.
Regards.

**Pull request closed without merging**
