### PR TITLE
[issue#9328]fix invalid pointer when free()

### PR DESCRIPTION
**Pull request by DjangoPeng**
Fix the [issue#9328](https://github.com/tensorflow/tensorflow/issues/9328) of TensorFlow v1.0 images.

### CODE REVIEW

**Comment by DjangoPeng** [comment]
@caisq @girving Please check.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
Linux XLA didn't exist at r1.0, so I'm assuming this is probably good.  Merging.

**Review by vrv — APPROVED** [review]

**Comment by nealwu** [comment]
@vrv Looks like this was only merged into r1.0 and is not currently in master or any of the later releases. Should we merge this into those branches as well?

**Comment by vrv** [comment]
I don't know, maybe see the original bug for context?

**Comment by nealwu** [comment]
I see, looks like it was planned in that issue to merge into r1.0 specifically. No worries then.

**Pull request merged**
