### PR TITLE
[r1.15 CherryPick]: [INTEL MKL] Fixing spurious omp thread spawning

### PR DESCRIPTION
**Pull request by penpornk**
This PR fixes the core over-utilization issue when Eigen and OpenMP threadings crash (in eager mode). (Cherry-picked to r2.0 in PR #32514.)

Original PR #32485:
In some models that use eager/imperative code where we don’t rewrite a few operators to MKL, a lot (intra_op_threads*OMP_NUM_THREADS) of threads are spawned by Eigen matmul code. This is because -fopenmp flag is passed to Eigen as part of the build configuration. This PR fixes the configuration to not pass -fopenmp to Eigen under --config=mkl.

### CODE REVIEW

**Comment by penpornk** [comment]
Manually setting CLA to yes because all the co-authored commits are from PR #32485 that is already merged in master.

**Comment by Srini511** [comment]
Hi @penpornk , @gunan and @goldiegadde , quick ping to check if we are okay to make the 1.15 cutoff for this PR.

**Comment by penpornk** [comment]
@Srini511 The PR wasn't merged yesterday because many tests failed in `Linux GPU`, `MacOS Python2 and CC`, and `Ubuntu CPU`. I believe they are unrelated to the PR, but I don't know what's going to happen to this PR either. Will have to wait to hear from @goldiegadde and @gunan.

**Comment by Srini511** [comment]
Thanks @penpornk for the update.

**Pull request merged**
