### PR TITLE
Cross-import KMeans and GMM in tf.learn.estimators

### PR DESCRIPTION
**Pull request by terrytangyuan**
- Cross-import KMeans and GMM in tf.learn.estimators

### CODE REVIEW

**Comment by martinwicke** [comment]
@agarwal-ashish do you prefer to keep this separate? We may just want to cross-import the estimator. That way it's clearer who the best contact for the code.

**Comment by terrytangyuan** [comment]
Yeah we probably need some agreement going forward. I just saw HMM got merged in as well, which is a similar case. In my opinion, it's just easier to generate the docs and they will be in the same place for users to see.

**Comment by martinwicke** [comment]
There's more of these coming. I'm leery of moving them around. However, we should cross-import them. Do you want to change the PR to do that? 

Regarding the documentation, we will reorganize the documentation more thoroughly, and hopefully that will address the issue of scattered docs. 

FYI @xmbrst @dr4b

**Comment by terrytangyuan** [comment]
Sounds good. I'll see if I have some time this weekend. Thanks for clarification.

**Comment by terrytangyuan** [comment]
@martinwicke I updated the PR to simply cross-import the others. This Linux GPU PIP test does not seem to finish, as seen in other PRs as well. Do you know why?

**Comment by terrytangyuan** [comment]
@martinwicke Seems fixed now :-)

**Comment by martinwicke** [comment]
@ilblackdragon: this is the right thing to do for users, but it is weird because there will be an expectation of API stability for the externally provided libraries. @terrytangyuan, I will hold off on merging this while we figure out policy and team responsibility questions.

**Comment by terrytangyuan** [comment]
Sure that makes sense.

**Comment by rmlarsen** [comment]
@martinwicke any resolution on this yet?

**Comment by martinwicke** [comment]
Let's not do this for now. Things will move out of contrib at their on pace, and I'd like to avoid more interdependencies.

**Comment by martinwicke** [comment]
Sorry about the runaround -- I'll close this.

**Comment by terrytangyuan** [comment]
Sure no problem. That makes sense.

**Pull request closed without merging**
