### PR TITLE
Fixed #27598

### LINKED ISSUE #27598: RaggedTensor casting bug
version 2.0.0-alpha.
Nested RaggedTensor are cast to int64 without apparent reason:

with regular tensors (ok):
```
>>> tf.constant([[1]], dtype=tf.int8)
<tf.Tensor: id=98, shape=(1, 1), dtype=int8, numpy=array([[1]], dtype=int8)>
```
with nested RaggedTensor (not ok):
```
>>> tf.ragged.constant([[1]], dtype=tf.int8)
tf.RaggedTensor(values=tf.Tensor([1], shape=(1,), dtype=int8), row_splits=tf.Tensor([0 1], shape=(2,), dtype=int64))
```

Also they can not be used to create generators even with dtype=int64. The following code leads to:

> The expected type was int64, but the yielded element was <tf.RaggedTensor [[6]]>.

```

class LineGenerator(object):
  def get_next_line(self):
    while True:
      out = [[6]]
      yield tf.ragged.constant(out, dtype=tf.int64)

class Dataset(object):
  def __init__(self, generator=LineGenerator()):
    self.next_element = self.build_iterator(generator)

  def build_iterator(self, gen: LineGenerator):
    dataset = tf.data.Dataset.from_generator(gen.get_next_line,output_types = tf.int64)
    #some other code...
```

### PR DESCRIPTION
**Pull request by captain-pool**
Converting the Ragged Tensor to General Tensor is the fastest way to fix the Bug.

### CODE REVIEW

**Comment by mrry** [comment]
This doesn't seem quite right to me... `Dataset.from_generator()` is meant for wrapping code that generates Python values such as NumPy arrays, and convering a RaggedTensor to a Tensor seems like it might lead to a surprising increase in memory use.

@jsimsa is reviewing some RaggedTensor support in other parts of `tf.data`, and might have a better idea of how to handle this.

**Comment by captain-pool** [comment]
> This doesn't seem quite right to me... `Dataset.from_generator()` is meant for wrapping code that generates Python values such as NumPy arrays, and convering a RaggedTensor to a Tensor seems like it might lead to a surprising increase in memory use.
> 
> @jsimsa is reviewing some RaggedTensor support in other parts of `tf.data`, and might have a better idea of how to handle this.

@mrry , I know that this might cause memory problem. But this a temporary fix, as long as there's no support for RaggedTensor in `tf.data` this is the only way to deal with this.
Apart from that, Can you give me some pointers or Documentation Links, how to get started with building support for Special Tensor Types? @jsimsa is working on Supporting RaggedTensor, so I was thinking if I could add Support to SparseTensors.

**Comment by mrry** [comment]
The current PR couldn't be a temporary change though... `Dataset.from_generator()` is in the public API, so applying this PR would prevent us from making the proper fix, because users might come to depend on the temporary behavior in the meantime.

**Comment by captain-pool** [comment]
> The current PR couldn't be a temporary change though... `Dataset.from_generator()` is in the public API, so applying this PR would prevent us from making the proper fix, because users might come to depend on the temporary behavior in the meantime.

Okay. Thanks @mrry for Clearing out. Can you Point me some resources from which I can teach myself adding C++ Kernels for Ops? I went through the codes already available Ops, but that doesn't really help.
This Error also occurs for SparseTensors, So, I can start working for supporting Sparse Tensors in `tf.data`.

**Comment by jsimsa** [comment]
Hi @captain-pool, here is a tutorial that demonstrates how to add new ops and kernels to TensorFlow: https://www.tensorflow.org/guide/extend/op.

As for `tf.SparseTensor`, tf.data already supports that type for most transformations. `tf.data.Dataset.from_generator` is an exception. Because of its implementation details only numpy values and (dense) tensors are supports and there are no plans to add support for other types.

Can you describe the high-level use case you have for using `tf.SparseTensor` or `tf.RaggedTensor`?

Last but not least, I agree with @mrry that this PR should not be submitted.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
