### PR TITLE
[WIP] Add tf_copts to XLA libraries

### PR DESCRIPTION
**Pull request by snnn**
Split from #14531 
Required by #15213
Depends on #15466

To fix a build error in //tensorflow/compiler/xla:util
There is a name conflict in  xla_data.pb.h
```
enum PrimitiveType {
  PRIMITIVE_TYPE_INVALID = 0,
  PRED = 1,
  S8 = 2,
  S16 = 3,
  S32 = 4,
  S64 = 5,
  U8 = 6,
  U16 = 7,
  U32 = 8,
  U64 = 9,
  F16 = 10,
  F32 = 11,
  BF16 = 16,
  F64 = 12,
  C64 = 15,
  TUPLE = 13,
  OPAQUE = 14,
  PrimitiveType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PrimitiveType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
```
However, **OPAQUE** is already defined in wingdi.h as:
```
#define OPAQUE              2
```
So, "/DNOGDI“ compiler flag  is a must for who includes this file.

@rongjiecomputer 
@jhseu

### CODE REVIEW

**Comment by jhseu** [comment]
This might be a brittle fix. If a new rule is added that forgets to add tf_copts, then it'll break again. @gunan not sure who owns this build rule. Should we do this more generally by adding a new library rule?

@snnn I'm not sure from your description why this doesn't build. The enum should be under a separate namespace. See xla_data.proto.

**Comment by gunan** [comment]
I am also not fond of this solution. I think us redefining the cc_library rule will  be better, if we have to add tf_copts to these rules.
That is unless @mhlopko has a better recommendation for us.

**Comment by snnn** [comment]
Though we can create a new macro like tf_cc_library, it doesn't mean I could change fewer lines. 
As this change is huge, you may want to do it internally.

**Comment by snnn** [comment]
Hi @jhseu

Yes,  The enum is under a separate namespace. But, OPAQUE in Windows.h is a macro. macro comes first. It's like:
```c
#define NOGDI 1
enum something{
  a,
  b,
  NOGDI,  //here, you will get an error, no matter which namespace the enum lives
};
```

**Comment by jhseu** [comment]
Another alternative is to #undef OPAQUE where Windows.h is included. That seems preferable.

**Comment by rongjiecomputer** [comment]
@jhseu `windows.h` is included in a lot of places, trying to track down all these files an `#undef OPAQUE` right after `windows.h` can be difficult. If a new file includes `windows.h` and forgot to undef macros again, it will break again.

`windows.h` is known as one of the most namespace/macro polluting header file for a reason.

**Comment by snnn** [comment]
Hi @jhseu,

Then you just solved one of these problems.  Please take a look at #15302

Instead of adding
```
#include "tensorflow/core/platform/cpu_info.h"
```
I could do 
```
#if defined(PLATFORM_WINDOWS)
#include "tensorflow/core/platform/windows/cpu_info.h"
#endif
```

Then __BYTE_ORDER__  will remain undefined if PLATFORM_WINDOWS is not defined (because of lacking tf_copts)
However, we have code like
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/numeric_types.h#L55
```
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
    value = p[0];
#else
    value = p[1];
#endif
```

Who includes this file will get a silent error.

**Comment by snnn** [comment]
The problem is even more tricky for cc_tests. 
Every cc_test is binary exe on Windows, it may either link to tf framework libraries statically or dynamically.
For link statically, you should define TF_COMPILE_LIBRARY, otherwise, you must be care of not defining it. 
For every cc file under tensorflow/core, we need to **define** TF_COMPILE_LIBRARY while compiling.
For every cc file under tensorflow/contrib, we need to **undefine** TF_COMPILE_LIBRARY while compiling.
To accomplish that,  we have to add tf_copts everywhere.

**Comment by snnn** [comment]
@melodyguan 
Any suggestion?

**Comment by snnn** [comment]
@meteorcloudy, any suggestion?

**Comment by jhseu** [comment]
Yeah, perhaps let's just create a tf_cc_library and add the copts there, and modify all of these to use tf_cc_library.

**Comment by snnn** [comment]
Got it. I will do it

**Comment by snnn** [comment]
Hi @jhseu

How about this #15466 ?

**Pull request closed without merging**
