### PR TITLE
tensorflow-stablehlo_reduce_window-compileFixed

### PR DESCRIPTION
**Pull request by GuoHuanyu**
bazel or cmake build tensorflow/lite issues brought by "tensorflow/lite/kernels/stablehlo_reduce_window.cc"
It can be fixed by reversing the order of the StridedReduce and ReduceWindowImpl functions. #64376

### CODE REVIEW

**Comment by GuoHuanyu** [comment]
I think i have a CLM with github name : GuoHuanyu

**Comment by gbaned** [comment]
Hi @GuoHuanyu Can you please sign CLA. Thank you!

**Comment by GuoHuanyu** [comment]
> Hi @GuoHuanyu Can you please sign CLA. Thank you!
I have a cla as blow,  i have no idea about how to edit  it to make check pass
Screenshot_2024-04-05-12-35-40-27_40deb401b9ffe8e1df2f1cc5ba480b12

The following contributors were found for this pull request:

✅  PR Opener: @GuoHuanyu
❌ Author: <Hua*****uo> it should be Huanyu Guo，and i have checked with git log.

**Comment by GuoHuanyu** [comment]
> Hi @GuoHuanyu Can you please make sure to use same GitHub username and email-id associated with it.

I tried your suggestion, but I'm still facing issues. Could you help me revert this pull request? Thank you for your assistance.

**Comment by GuoHuanyu** [comment]
I tried your suggestion, but I'm still facing issues. Could you help me revert this pull request? Thank you for your assistance.

**Comment by GuoHuanyu** [comment]
> Hi @GuoHuanyu Can you please make sure to use same GitHub username and email-id associated with it.

I tried your suggestion, but I'm still facing issues. Could you help me revert this pull request? Thank you for your assistance.

**Comment by gbaned** [comment]
> > Hi @GuoHuanyu Can you please make sure to use same GitHub username and email-id associated with it.
> 
> I tried your suggestion, but I'm still facing issues. Could you help me revert this pull request? Thank you for your assistance.

Hi @GuoHuanyu Sorry for the delay, please close this PR and create new one.  Thank you!

**Pull request closed without merging**
