### PR TITLE
Fix tensorboard import path

### PR DESCRIPTION
**Pull request by Vesnica**

### CODE REVIEW

**Comment by Vesnica** [comment]
I signed it!

**Comment by vrv** [comment]
@danmane: is this correct? 

https://github.com/tensorflow/tensorflow/commit/880011919c7b113802eb23c54ed5b8e2218e4416 specifically changed this a few days ago.

**Comment by vrv** [comment]
Hm, with the reorganization of tensorboard, I think this is right.  Currently  tensorboard install is broken at HEAD, and I think this fixes it.

**Comment by vrv** [comment]
(Merged a few days ago)

**Pull request closed without merging**
