### PR TITLE
Reintroduce TF to TF lowering patterns to legalize_tf pass for TFLite 

### PR DESCRIPTION
**Pull request by ahmedsabie**
The TF lowering patterns are useful across multiple different backends. This PR adds the lowering patterns from TF to TFLite so that TFLite specific code can focus on lowerings unique to it. We can also automatically benefit from any TF lowerings that get added without having to manually sync it with TFLite if TFLite didn't use the lowering patterns of TF directly.

The PR was originally reverted for an unrelated issue which was fixed in https://github.com/tensorflow/tensorflow/pull/44097. It can be reintroduced now.

### CODE REVIEW

**Review by smit-hinsu — APPROVED** [review]

**Review by smit-hinsu — APPROVED** [review]

**Comment by byronyi** [comment]
This seems to block nightly builds again. See following error message in CI:

```
INFO: From Testing //tensorflow/compiler/tests:stateless_random_ops_test_cpu_mlir_bridge_test:
==================== Test output for //tensorflow/compiler/tests:stateless_random_ops_test_cpu_mlir_bridge_test:
Running tests under Python 3.6.12: /usr/local/bin/python3.6
WARNING:tensorflow:From /buildfarm/default/operations/4d2cb36e-fb6e-43ce-a05c-32e283615e12/bazel-out/k8-opt/bin/tensorflow/compiler/tests/stateless_random_ops_test_cpu_mlir_bridge_test.runfiles/org_tensorflow/tensorflow/compiler/tests/xla_test.py:87: Context.enable_xla_devices (from tensorflow.python.eager.context) is deprecated and will be removed in a future version.
Instructions for updating:
XLA:CPU and XLA:GPU devices are deprecated
W1026 18:11:56.800348 139974732013696 deprecation.py:339] From /buildfarm/default/operations/4d2cb36e-fb6e-43ce-a05c-32e283615e12/bazel-out/k8-opt/bin/tensorflow/compiler/tests/stateless_random_ops_test_cpu_mlir_bridge_test.runfiles/org_tensorflow/tensorflow/compiler/tests/xla_test.py:87: Context.enable_xla_devices (from tensorflow.python.eager.context) is deprecated and will be removed in a future version.
Instructions for updating:
XLA:CPU and XLA:GPU devices are deprecated
[ RUN      ] StatelessRandomOpsTest.testDeterminism
INFO:tensorflow:Start test case: StatelessRandomOpsTest.testDeterminism
I1026 18:11:56.802196 139974732013696 xla_test.py:199] Start test case: StatelessRandomOpsTest.testDeterminism
2020-10-26 18:11:56.817781: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-26 18:11:56.846378: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2400000000 Hz
2020-10-26 18:11:56.851322: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55eb4f6412a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-26 18:11:56.851354: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-26 18:11:56.862759: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2020-10-26 18:11:56.874682: I tensorflow/compiler/jit/xla_device.cc:399] XLA_GPU and XLA_CPU devices are deprecated and will be removed in subsequent releases. Instead, use either @tf.function(experimental_compile=True) for must-compile semantics, or run with TF_XLA_FLAGS=--tf_xla_auto_jit=2 for auto-clustering best-effort compilation.
2020-10-26 18:11:56.880781: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xla_compile_on_demand_op.cc:171 : Internal: MLIR TF to XLA legalization failed<unknown>:0: error: The following operations cannot be legalized: tf.StatelessRandomGetKeyCounterAlg (count: 1). These legalization failure(s) may be due to missing TF to HLO lowerings and/or unsupported attributes, etc.
<unknown>:0: error: loc("stateless_random_uniform/StatelessRandomGetKeyCounterAlg"): 'tf.StatelessRandomGetKeyCounterAlg' op is not legalizable
<unknown>:0: note: loc("stateless_random_uniform/StatelessRandomGetKeyCounterAlg"): see current operation: %0:3 = "tf.StatelessRandomGetKeyCounterAlg"(%arg0) {Tseed = i32, _XlaHasReferenceVars = false, device = "/job:localhost/replica:0/task:0/device:XLA_CPU:0"} : (tensor<2xi32>) -> (tensor<1xui64>, tensor<2xui64>, tensor<i32>)
<unknown>:0: error: A failure has been detected while processing the MLIR module, a reproducer has been generated in '/buildfarm/default/operations/4d2cb36e-fb6e-43ce-a05c-32e283615e12/bazel-out/k8-opt/testlogs/tensorflow/compiler/tests/stateless_random_ops_test_cpu_mlir_bridge_test/test.outputs/mlir_reproducer_n148-102-199-5a7642e6-83266-5b29029067726.mlir'
<unknown>:0: note: see current operation: "module"() ( {
  "func"() ( {
  ^bb0(%arg0: tensor<2xi32>):  // no predecessors
    %0:3 = "tf.StatelessRandomGetKeyCounterAlg"(%arg0) {Tseed = i32, _XlaHasReferenceVars = false, device = "/job:localhost/replica:0/task:0/device:XLA_CPU:0"} : (tensor<2xi32>) -> (tensor<1xui64>, tensor<2xui64>, tensor<i32>)
    "std.return"(%0#0, %0#1, %0#2) : (tensor<1xui64>, tensor<2xui64>, tensor<i32>) -> ()
  }) {sym_name = "main", tf.entry_function = {control_outputs = "", inputs = "_arg0", outputs = "_retval0,_retval1,_retval2"}, type = (tensor<2xi32>) -> (tensor<1xui64>, tensor<2xui64>, tensor<i32>)} : () -> ()
  "module_terminator"() : () -> ()
}) {tf.versions = {bad_consumers = [], min_consumer = 0 : i32, producer = 565 : i32}} : () -> ()

INFO:tensorflow:time(__main__.StatelessRandomOpsTest.testDeterminism): 0.09s
I1026 18:11:56.888627 139974732013696 test_util.py:2076] time(__main__.StatelessRandomOpsTest.testDeterminism): 0.09s
INFO:tensorflow:End test case: testDeterminism
I1026 18:11:56.888831 139974732013696 xla_test.py:206] End test case: testDeterminism
[  FAILED  ] StatelessRandomOpsTest.testDeterminism
[ RUN      ] StatelessRandomOpsTest.testDistributionOfStatelessRandomNormal
INFO:tensorflow:Start test case: StatelessRandomOpsTest.testDistributionOfStatelessRandomNormal
I1026 18:11:56.891267 139974732013696 xla_test.py:199] Start test case: StatelessRandomOpsTest.testDistributionOfStatelessRandomNormal
2020-10-26 18:11:56.905228: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xla_compile_on_demand_op.cc:171 : Internal: MLIR TF to XLA legalization failed<unknown>:0: error: The following operations cannot be legalized: tf.StatelessRandomGetKeyCounterAlg (count: 1). These legalization failure(s) may be due to missing TF to HLO lowerings and/or unsupported attributes, etc.
<unknown>:0: error: loc("stateless_random_normal/StatelessRandomGetKeyCounterAlg"): 'tf.StatelessRandomGetKeyCounterAlg' op is not legalizable
<unknown>:0: note: loc("stateless_random_normal/StatelessRandomGetKeyCounterAlg"): see current operation: %0:3 = "tf.StatelessRandomGetKeyCounterAlg"(%arg0) {Tseed = i32, _XlaHasReferenceVars = false, device = "/job:localhost/replica:0/task:0/device:XLA_CPU:0"} : (tensor<2xi32>) -> (tensor<1xui64>, tensor<2xui64>, tensor<i32>)
<unknown>:0: error: A failure has been detected while processing the MLIR module, a reproducer has been generated in '/buildfarm/default/operations/4d2cb36e-fb6e-43ce-a05c-32e283615e12/bazel-out/k8-opt/testlogs/tensorflow/compiler/tests/stateless_random_ops_test_cpu_mlir_bridge_test/test.outputs/mlir_reproducer_n148-102-199-5a7642e6-83266-5b2902906d80a.mlir'
<unknown>:0: note: see current operation: "module"() ( {
  "func"() ( {
  ^bb0(%arg0: tensor<2xi32>):  // no predecessors
    %0:3 = "tf.StatelessRandomGetKeyCounterAlg"(%arg0) {Tseed = i32, _XlaHasReferenceVars = false, device = "/job:localhost/replica:0/task:0/device:XLA_CPU:0"} : (tensor<2xi32>) -> (tensor<1xui64>, tensor<2xui64>, tensor<i32>)
    "std.return"(%0#0, %0#1, %0#2) : (tensor<1xui64>, tensor<2xui64>, tensor<i32>) -> ()
  }) {sym_name = "main", tf.entry_function = {control_outputs = "", inputs = "_arg0", outputs = "_retval0,_retval1,_retval2"}, type = (tensor<2xi32>) -> (tensor<1xui64>, tensor<2xui64>, tensor<i32>)} : () -> ()
  "module_terminator"() : () -> ()
}) {tf.versions = {bad_consumers = [], min_consumer = 0 : i32, producer = 565 : i32}} : () -> ()

```

**Comment by smit-hinsu** [comment]
Thanks for reporting this. Let me look into this.

**Comment by smit-hinsu** [comment]
It seems to have broken by the following commit. Let me fix it. https://github.com/tensorflow/tensorflow/commit/9745e24f30cc54b35af85936eab277c1dc62643f

**Comment by byronyi** [comment]
You are correct. Simply reverting this PR doesn't fix the issue. Compatibility horizon seems to bite again..

**Comment by byronyi** [comment]
cc @wangpengmit for 6d605dde

**Comment by wangpengmit** [comment]
Ah, the newly added V2 stateless ops kicked in when compatibility horizon expired. There is a lowering in the old tf2xla bridge: https://github.com/tensorflow/tensorflow/blob/547bd9c88b1a86f0543fff3460e2d4d1c8009cb4/tensorflow/compiler/tf2xla/kernels/stateless_random_ops_v2.cc#L482 . Can you do a similar thing in the MLIR bridge?

**Comment by smit-hinsu** [comment]
This should have got fixed with https://github.com/tensorflow/tensorflow/commit/337d20c7f07139d8e00e67a58b4f5d771e1f313a.

**Comment by byronyi** [comment]
Thanks!

**Comment by byronyi** [comment]
cc @ahmedsabie it seems to be reverted again in da6eb9c93d023de5e9613efeb42c7d8e723f26e5.

**Pull request merged**
