### PR TITLE
Update .bazelrc to allow building for ios_arm64e

### PR DESCRIPTION
**Pull request by adis300**
Update .bazelrc to allow building for ios_arm64e by using `bazel -config=ios_arm64e ......`

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by rthadur — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Please sign CLA. We shouldn't have reviewed before that

**Comment by adis300** [comment]
> Please sign CLA. We shouldn't have reviewed before that
I signed the CLA a few months ago. Clicked "update check" and google showed me 404 error.

I tried again today, and still 404. You can help me on rechecking the commit as a Googler?

**Comment by mihaimaruseac** [comment]
> > Please sign CLA. We shouldn't have reviewed before that
> > I signed the CLA a few months ago. Clicked "update check" and google showed me 404 error.
> 
> I tried again today, and still 404. You can help me on rechecking the commit as a Googler?

 If you are not currently covered under a CLA, please visit https://cla.developers.google.com/. Once you've signed, follow the "New Contributors" link at the bottom of this page to update this check.

**Comment by adis300** [comment]
> 
I have signed the CLA multiple times. I am pretty sure the recheck feature doesn't work for me. It show's me 
"400. That’s an error.
That’s all we know." with a Google logo.

I noticed as a Googler you could help me to rescan this pull request from the page.
"Googlers: Go [here](https://goto.google.com/prinfo/github.com%2Ftensorflow%2Ftensorflow%2Fpull%2F56647) to view more details and manage scans for this pull request."

**Comment by mihaimaruseac** [comment]
Can you try this link? https://cla.developers.google.com/github/rescan?pr=tensorflow%2Ftensorflow%2Fpull%2F56647&key=%01%B5g%86%81%A0G%24%E6%94w%2Bi%D4%E5m6e%08%06%2C&expiry=2022-08-15

**Comment by mihaimaruseac** [comment]
No CLA signed

**Comment by gbaned** [comment]
Hi @adis300 Can you please sign CLA. Thank you!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
It seems CLA is now signed and accepted

**Comment by adis300** [comment]
> It seems CLA is now signed and accepted

Finally. Thanks. I tried multiple times. I'm quite sure it's google CLA system's bug.

**Pull request merged**
