### PR TITLE
Moved pad reference and optimized ops into its own.

### PR DESCRIPTION
**Pull request by amitsrivastava78**
To Remove the dependency moving pad to it own file.

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@aselle , I have committed padding support for tflite macro as well with the 2nd commit, Would love to see your comments on the same.

Regards
Amit

**Comment by gbaned** [comment]
@amitsrivastava78 could you please resolve the conflicts?  Thanks!

**Comment by amitsrivastava78** [comment]
@gbaned , thanks for pointing this out, i have resolved the merge conflicts.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@aselle , i have re-based the code again , kindly have a look and provide your feedback.

Regards
Amit

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by gbaned** [comment]
@amitsrivastava78 Could you please resolve the conflicts? Thanks!

**Comment by amitsrivastava78** [comment]
> @amitsrivastava78 Could you please resolve the conflicts? Thanks!

@gbaned , conflict resolved.

Regards
Amit

**Comment by gbaned** [comment]
@amitsrivastava78 Could you please resolve the conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
