### PR TITLE
added Install instructions for OS X GPU

### PR DESCRIPTION
**Pull request by kashif**
for issue #2522

### CODE REVIEW

**Comment by vrv** [comment]
Thanks, this is helpful! Will assign to @martinwicke since I think he's setting up the Mac OS X GPU test machine and this should be useful to validate the instructions :)

**Comment by Mistobaan** [comment]
I have also a pretty good list of steps to do to install on macosx: https://gist.github.com/Mistobaan/dd32287eeb6859c6668d that could be integrated.

**Comment by kashif** [comment]
@Mistobaan yes there is a newer cuda toolkit that fixes the xcode issue. I am just about to make a cask pull-request to update cuda, after which there will be no need to downgrade xcode etc.

**Comment by kashif** [comment]
@Mistobaan ok i spoke too soon, seems like some kind soul has already done that... so no need to downgrade xcode 🎉

**Comment by yaroslavvb** [comment]
BTW, I just tried these instructions after upgrading MacOS and TensorFlow to today's head and they don't seem to work. Something about libcudart not being loaded because I'm running a "restricted program". Sudo doesn't help

```
bash-3.2$ echo $DYLD_LIBRARY_PATH
/usr/local/cuda/lib

bash-3.2$ find /usr/local/cuda -name libcudart.7.5.dylib
/usr/local/cuda/lib/libcudart.7.5.dylib

bash-3.2$ bazel-bin/tensorflow/python/session_ops_test

dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin/_U_S_Sthird_Uparty_Sgpus_Scuda_Ccudart___Uthird_Uparty_Sgpus_Scuda_Slib in /Users/yaroslavvb/tfimmediate_fresh.gpu/tensorflow/_python_build/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH third_party/gpus/cuda/lib in /Users/yaroslavvb/tfimmediate_fresh.gpu/tensorflow/_python_build/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH third_party/gpus/cuda/extras/CUPTI/lib in /Users/yaroslavvb/tfimmediate_fresh.gpu/tensorflow/_python_build/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/yaroslavvb/tfimmediate_fresh.gpu/tensorflow/_python_build/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/yaroslavvb/tfimmediate_fresh.gpu/tensorflow/_python_build/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/yaroslavvb/tfimmediate_fresh.gpu/tensorflow/_python_build/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/yaroslavvb/tfimmediate_fresh.gpu/tensorflow/_python_build/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/Users/yaroslavvb/tfimmediate_fresh.gpu/tensorflow/_python_build/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib
  Referenced from: /Users/yaroslavvb/tfimmediate_fresh.gpu/tensorflow/_python_build/tensorflow/python/_pywrap_tensorflow.so

```

**Comment by kashif** [comment]
@yaroslavvb can you try `xcode-select --install` and then try again?

**Comment by yaroslavvb** [comment]
Yes, tried that, restarted, same issue.

**Comment by yaroslavvb** [comment]
Seems like it's possibly coming from this line in ImageLoader. Somehow
"context.processIsRestricted" is set when I'm running with config=cuda
http://opensource.apple.com//source/dyld/dyld-210.2.3/src/ImageLoaderMachO.cpp

if ( context.processIsRestricted  && (context.mainExecutable == this) ) {
						dyld::warn("LC_RPATH %s in %s being ignored in restricted
program because of @loader_path\n", path, this->getPath());
						break;
					}

**Comment by kashif** [comment]
@yaroslavvb yes seems like its part of OS X's System Integrity Protection (SIP) feature... wondering why it works for me...

**Comment by kashif** [comment]
@yaroslavvb how did you install the cuda toolkit?

**Comment by yaroslavvb** [comment]
Using brew. I'll try disabling this SIP feature and update in few hours

**Comment by kashif** [comment]
@yaroslavvb i installed via the nvidia installed and my 

```bash
$ csrutil status
System Integrity Protection status: enabled.
```

**Comment by yaroslavvb** [comment]
Hm, after disabling SIP I'm seeing this [segfault](http://pastebin.com/bbzsTMPq) in dylib, looks something's broken in trying to load those libs from relative path

**Comment by yaroslavvb** [comment]
@kashif btw, how old is your TensorFlow version where you got this to work? (I've only tested this on version from this morning)

**Comment by kashif** [comment]
@yaroslavvb my tensorflow is about 4 days old... i can merge in master and try to compile again...

**Comment by yaroslavvb** [comment]
@kashif 4 days old is pretty recent, seems likely problem is somewhere else

**Comment by dansbecker** [comment]
I also tried to follow these instructions and got an error
`
(py35)Dans-iMac:tensorflow dan$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
ERROR: /Users/dan/tensorflow/tensorflow/core/BUILD:87:1: //tensorflow/core:protos_all_py: no such attribute 'imports' in 'py_library' rule.
ERROR: /Users/dan/tensorflow/tensorflow/tools/pip_package/BUILD:23:1: Target '//tensorflow/core:framework_headers' contains an error and its package is in error and referenced by '//tensorflow/tools/pip_package:build_pip_package'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.199s
`

I'd successfully been running the prebuilt binary, which I removed before starting these instructions.

**Comment by yaroslavvb** [comment]
Update, I installed CUDA from official website, ran ./configure again, rebuilt and now it works.

**Comment by yaroslavvb** [comment]
OK, I believe this is an issue of environment variables, probably the `DYLD_LIBRARY_PATH`. I was testing things by running "bazel test" which spawns it's own environment and probably doesn't set that path correctly

so this fails
`bazel test -c opt --config=cuda tensorflow/python:depthwise_conv_op_test
`
but then this passes
`bazel-bin/tensorflow/python/depthwise_conv_op_test
`

**Comment by martinwicke** [comment]
We've had problems with environment variables in bazel test before. :/

It'll take me a while to actually get to installing the GPU test machine. I'll probably have an update then. For now, this looks good. Clarifications to the instructions are always welcome.

**Comment by yaroslavvb** [comment]
OK, I just did SMC reset, which somehow reset my SIP and this stopped working with same ` being ignored in restricted program because it is a relative path` message, and then after disabling SIP, it started working again. So disabling SIP seems to be a requirement for MacOS 10.11.5 (15F34)

**Pull request merged**
