### PR TITLE
Update parameterized_docker_build.sh

### PR DESCRIPTION
**Pull request by fxfabre**
typo : Dockerilfe > Dockerfile

### CODE REVIEW

**Comment by fxfabre** [comment]
I signed it!

**Review by benoitsteiner — APPROVED** [review]

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (27/25 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:55315 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1ddNok-0006k4-2c
	for mazecreator@mazecreator.com; Thu, 03 Aug 2017 16:38:36 -0500
Date: Thu, 03 Aug 2017 14:48:49 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1501796929;
	bh=PYfZZ6XQbKPrrt9qwGh/6g85uMoCPPc1Ofw+zne71Uk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=AFfQJ2S4iDjHCE9OiOySZbqvx1oCUfMy76I2Vz7zPgCfnbEYVuf2QY4V8z4cf4mRE
	 Pi3tnxhLkV7TDtfMUE2KVG3QU2pVgsrVWu00+3ma5CbSgpM2D/YmBolN0G2d5JyzGU
	 tUSo9hLxUQrEbbBPPtY7i6MnddLN+87X9PqheGTo=

**Pull request merged**
