### PR TITLE
[TF-TRT] ResourceGather converter

### PR DESCRIPTION
**Pull request by Nyrio**
This is another step towards the full support of non-frozen models in TF-TRT.
This PR contains all the changes of #55337, #55608, and #56050, so I'm marking it as a draft for now.

### CODE REVIEW

**Comment by gbaned** [comment]
@Nyrio This PR is in draft, any update on this? Please. Thank you!

**Comment by Nyrio** [comment]
@gbaned The other PRs in the series need to be reviewed first (cf description)

**Comment by gbaned** [comment]
@Nyrio This PR is in draft, any update on this? Please. Thank you!

**Comment by gbaned** [comment]
@Nyrio This PR is in draft, any update on this? Please. Thank you!

**Comment by gbaned** [comment]
@Nyrio This PR is in draft, any update on this? Please. Thank you!

**Comment by gbaned** [comment]
@Nyrio This PR is in draft, any update on this? Please. Thank you!

**Comment by gbaned** [comment]
Hi @Nyrio I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for the contribution.

**Pull request closed without merging**
