### PR TITLE
Revert "[MLIR][XLA] Buffer Assignment"

### PR DESCRIPTION
**Pull request by joker-eph**
Reverts tensorflow/tensorflow#37212

This lacks test coverage, it was merged incorrectly without addressing comments.

### CODE REVIEW

**Review by pifon2a — CHANGES_REQUESTED** [review]
Let's not roll it back it, since the tests are being prepared right now by @dfki-ehna . It is too much work, rolling it back and forth.

**Comment by joker-eph** [comment]
Can you clarify what is the extra work exactly?
(My main issue will be that it will be harder to assess the coverage of the tests without a revert)

**Comment by pifon2a** [comment]
@joker-eph Waiting for rollback to be approved, submitted, then approved in gerrit, then approved again. Then doing the same for the next PR with added tests. I think it is a waste of time.

**Comment by joker-eph** [comment]
How are you gonna check the test coverage?

**Comment by pifon2a** [comment]
@joker-eph Do we need to? I think it is pretty clear what tests have to be added.

**Comment by gbaned** [comment]
@joker-eph Can you please resolve conflicts? Thanks!

**Comment by sherhut** [comment]
This revert is no longer needed.

**Pull request closed without merging**
