### PR TITLE
[TFLM] Added handling of tensors used as outputs for ops but then never used

### PR DESCRIPTION
**Pull request by yair-ehrenwald**
Discussed in https://github.com/tensorflow/tensorflow/issues/43380

A long term fix would probably eliminate the need for this, but at least in my tests it solves the issue for now.

### CODE REVIEW

**Comment by yair-ehrenwald** [comment]
This failed some of my tests now, converting to draft, needs some work.

**Comment by gbaned** [comment]
@yair-ehrenwald This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@yair-ehrenwald This PR is in draft, any update on this? Please. Thanks!

**Comment by gbaned** [comment]
@yair-ehrenwald This PR is in draft, any update on this? Please. Thanks!

**Comment by yair-ehrenwald** [comment]
Closing this, going with @advaitjain 's suggestion in https://github.com/tensorflow/tensorflow/issues/43380

**Pull request closed without merging**
