### PR TITLE
[tf.data] support ~/ alias for home dir in tf.data.Dataset.list_files

### PR DESCRIPTION
**Pull request by kvignesh1420**
This PR addresses the issue: https://github.com/tensorflow/tensorflow/issues/44264 by:
- Adding support to handle `~/` alias for home dir in file paths while using `tf.data.Dataset.list_files` API.
- Adding a test case to validate the functionality.

### CODE REVIEW

**Comment by kvignesh1420** [comment]
cc: @aaudiber

**Review by aaudiber — CHANGES_REQUESTED** [review]
Typically Python APIs don't expand `~`, e.g. `open('~/file')` will not expand the `~`. To get the behavior of starting a path with `~`, users should call `os.path.expanduser("~")` themselves. It is possible for a filename to start with the character '~', so this change would technically break backwards compatibility.

**Comment by kvignesh1420** [comment]
@aaudiber If that's the case, then let me close this PR. Shall I update https://github.com/tensorflow/tensorflow/issues/44264 with the reference to your comment and close it?

**Comment by aaudiber** [comment]
@kvignesh1420 Ah sorry, should have replied on #44264 earlier. I prefer not reporting a special error for `~/` to keep the implementation simpler.

**Comment by kvignesh1420** [comment]
@aaudiber no problem. Thanks anyways.

**Pull request closed without merging**
