### PR TITLE
export CombinerPreprocessingLayer and Combiner

### PR DESCRIPTION
**Pull request by haifeng-jin**
We will need to implement some custom preprocessing layers which should override the CombinerPreprocessingLayer.
I export these two classes to override.
Or any other suggestions for reusing the code in these two classes?

### CODE REVIEW

**Comment by haifeng-jin** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
@haifeng-jin Can you please resolve conflicts? Thanks!

**Comment by haifeng-jin** [comment]
@gbaned Conflicts resolved. Thanks

**Comment by tanzhenyu** [comment]
This will likely not pass tests since it requires proto definition. If you need, can you email me and Francois so we can do this for you?

**Comment by haifeng-jin** [comment]
@tanzhenyu I need these mainly for implementing a preprocessing layer that encodes the categorical features into numerical features for structured data.
However, I noticed there are some such preprocessing layers on the way in TF 2.2. If so, I don't need these classes now.

I may need it in the future, we can discuss whether to do it with the team during my internship : )

Thank you!

**Comment by tanzhenyu** [comment]
Haifeng, can you take a look at this?
https://github.com/tensorflow/community/pull/188

It was reviewed and implemented, I haven't merged this into master yet.

**Comment by gbaned** [comment]
@haifeng-jin Could you please check the reviewer comments and keep us posted? Thanks!

**Comment by haifeng-jin** [comment]
@gbaned As I discussed with @tanzhenyu, we will wait until the feature in tensorflow/community#188 is confirmed to see if we really my PR or not. 

If we still need it, I will fix the tests.
This PR currently is not likely to pass the tests.

Thank you.

**Comment by tanzhenyu** [comment]
Closing this PR per above discussion.

**Pull request closed without merging**
