### PR TITLE
Fixed line formatting

### PR DESCRIPTION
**Pull request by settle**

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
@settle thank you for your contribution, please sign CLA.

**Comment by ashutosh1919** [comment]
@settle , If you are signing CLA [(here)](https://cla.developers.google.com/) then please sign CLA for all the email IDs which you are already logged in in your browser. I faced the same problem once but I got solution after posting the question to stackoverflow [here](https://stackoverflow.com/questions/57214178/how-should-i-troubleshoot-my-google-contributor-licence-agreement-issue-on-my-pu/57228116#57228116).

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
@settle without signing CLA we cannot merge in your change

**Comment by settle** [comment]
> @settle without signing CLA we cannot merge in your change

Sorry, but I can't sign the CLA at this time.  I guess someone else will have to fix this missing newline character in the docs.

**Comment by mihaimaruseac** [comment]
In that case, closing the PR. Sorry for this.

**Comment by ashutosh1919** [comment]
@settle, Your approval is necessary on #36479.

**Pull request closed without merging**
