### PR TITLE
Add Support for TensorRT 8.2

### PR DESCRIPTION
**Pull request by ghost**
1. Add stub files for TensorRT 8.2
2. Fix accuracy regression with MobilenetV2 i.e. set dynamic range for (-6, 6)
3. Limit GPU memory utilization for TFTRT Integration tests
4. Fix incorrect usage of TRT version to string API
5. TensorRT model_tests update
- Add separate perf tolerance for FP32, FP16, and INT8
- Add separate accuracy tolerance for FP32, FP16, and INT8
- Add functionality to dump histograms for better accuracy validation 

CC: @DEKHTIARJonathan, @tfeher , and @bixia1

### CODE REVIEW

**Comment by christopherbate** [comment]
I am taking over the TensorRT 8.2-relevant work for @jhalakp-nvidia . Please see the new PR here https://github.com/tensorflow/tensorflow/pull/52932. @jhalakp-nvidia includes  some other features here that either are already covered by separate PRs or can go into a separate PR.

**Comment by gbaned** [comment]
@jhalakp-nvidia Any update on this PR? Please. Thanks!

**Comment by amehrish** [comment]
Hi, Has this PR been rejected? If yes! does this mean that there is no support for TensorRT 8.x?

**Comment by amehrish** [comment]
If there is no support for TensorRT 8.x, please can you recommend the right version of tensorRT to be used with Tensorflow 2.7.0 on UBuntu 20.04?

**Comment by devvaibhav455** [comment]
Same question as amehrish's. Can we have a compatibility matrix for tensorflow and tensorrt. Please correct me if its already there (couldn't find it) and share the link.

**Pull request closed without merging**
