### PR TITLE
Make necessary validations in the file image_ops_impl.py and array_ops.py

### LINKED ISSUE #54115: tf.image.adjust_hue miss input check
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
image = [[[1, 2, 3], [4, 5, 6]],
         [[7, 8, 9], [10, 11, 12]],
         [[13, 14, 15], [16, 17, 18]]]
image = tf.constant(image)
tf.image.adjust_hue(image, -2)
tf.image.adjust_hue(image, 2)

```

**Expected output**
According to the document [tf.image.adjust_hue](https://www.tensorflow.org/api_docs/python/tf/image/adjust_hue?hl=en), the delta should be in range `[-1, 1]`. Valid input check is missing here.

### PR DESCRIPTION
**Pull request by Cheril311**
Fixes https://github.com/tensorflow/tensorflow/issues/54115 and https://github.com/tensorflow/tensorflow/issues/54116 and https://github.com/tensorflow/tensorflow/issues/54848

<br> 
<b>What does this PR do? </b><br><br>
1) As per the documentation for   `tf.image.adjust_brightness` (https://www.tensorflow.org/api_docs/python/tf/image/adjust_brightness) and `tf.image.ajust_hue` (https://www.tensorflow.org/api_docs/python/tf/image/adjust_hue?hl=en) the parameter delta in both the functions needs to be in the range [-1,1], this PR adds necessary validations in image_ops_impl.py to ensure that
<br><br>
2) As per the documentation of 'tf.linalg.tensor_diag_part' the input matrix should be of the rank 2k, however there are no validations for this, I have added those validations,

### CODE REVIEW

**Comment by SeeForTwo** [comment]
Thank you for your pull request. I have some comments from an initial triage tell you in advance about what potentially might have to be defended, changed or otherwise addressed. This was NOT a review and NOT a final decision. While you are welcome to address any or all of these now if it is convenient, you can also wait for comments from a review.

* A potential performance concern is the computation of min and max in `adjust_brightness`.

* A potential concern is that this Python-only change will not add error checking for graph mode.

* Instead of adding error checking, should documentation be changed to say like that `delta` has an expected range and "safe but unspecified behavior occurs if it is out of range"?

Thank you for your patience as this is reviewed.

**Comment by Cheril311** [comment]
> Thank you for your pull request. I have some comments from an initial triage tell you in advance about what potentially might have to be defended, changed or otherwise addressed. This was NOT a review and NOT a final decision. While you are welcome to address any or all of these now if it is convenient, you can also wait for comments from a review.
> 
> * A potential performance concern is the computation of min and max in `adjust_brightness`.
> * A potential concern is that this Python-only change will not add error checking for graph mode.
> * Instead of adding error checking, should documentation be changed to say like that `delta` has an expected range and "safe but unspecified behavior occurs if it is out of range"?
> 
> Thank you for your patience as this is reviewed.

@SeeForTwo thanks for your time! I will surely look into this. Actually I was told that using tf - api functions in python is graph-mode friendly, thus had used reduce_min and reduce_max. But your point on performance seems valid

**Comment by mihaimaruseac** [comment]
Please don't use `update <file>` as title. It makes it harder later to understand what the commit does when looking at the change history

**Comment by Cheril311** [comment]
> Please don't use `update <file>` as title. It makes it harder later to understand what the commit does when looking at the change history

@mihaimaruseac can I please know some set of rules to keep a pr name, asking this as I am new to this

**Comment by mihaimaruseac** [comment]
Hi, please for example have a look at https://reflectoring.io/meaningful-commit-messages/

If you have just one commit in the PR, the title will be based on that. If you have more commits, pick a title that tells a story about all commits (and maybe also add more text in the first comment)

**Comment by Cheril311** [comment]
> Hi, please for example have a look at https://reflectoring.io/meaningful-commit-messages/
> 
> If you have just one commit in the PR, the title will be based on that. If you have more commits, pick a title that tells a story about all commits (and maybe also add more text in the first comment)

Thanks a lot @mihaimaruseac

**Comment by yongtang** [comment]
The issue is actually in PyObject conversion side I believe. It should have been fixed in: https://github.com/tensorflow/tensorflow/pull/54441

**Comment by Cheril311** [comment]
> The issue is actually in PyObject conversion side I believe. It should have been fixed in: #54441

@yongtang did not know about it, thanks for mentioning, however I believe the necessary validations for image_ops_impl.py still are necessary, will remove the changes I made in math_ops.py

**Comment by mihaimaruseac** [comment]
Can you make sure the required builds are all passing, please?

**Comment by Cheril184** [comment]
@mihaimaruseac for the py+cpp test suite I am getting a build error because the array in the test case does not have a rank of 2k, so my modified code is throwing a value error as written in the code, and in the issue and documentation of TF, it says the rank should 2k itself, so can you see if this an error in writing tests or the issue and docs are wrong?

**Comment by Cheril311** [comment]
Anyone in the community can help me understand a few tests?

**Comment by sachinprasadhs** [comment]
@Cheril184 , Can you fix the below error and submit changes again.
```
tensorflow/python/ops/array_ops.py:2813:0: W0311: Bad indentation. Found 8 spaces, expected 4 (bad-indentation)
************* Module image_ops_impl
tensorflow/python/ops/image_ops_impl.py:2222:0: W03[11](https://github.com/tensorflow/tensorflow/runs/6084856954?check_suite_focus=true#step:7:11): Bad indentation. Found 5 spaces, expected 6 (bad-indentation)
tensorflow/python/ops/image_ops_impl.py:2224:0: W0311: Bad indentation. Found 5 spaces, expected 6 (bad-indentation)
tensorflow/python/ops/image_ops_impl.py:2226:0: W0311: Bad indentation. Found 5 spaces, expected 6 (bad-indentation)
tensorflow/python/ops/image_ops_impl.py:2228:0: W0311: Bad indentation. Found 5 spaces, expected 6 (bad-indentation)
tensorflow/python/ops/image_ops_impl.py:2230:0: W0311: Bad indentation. Found 5 spaces, expected 6 (bad-indentation)
```

**Comment by gbaned** [comment]
@Cheril311 Can you please check @sachinprasadhs's comments and keep us posted ? Thank you!

**Comment by Cheril311** [comment]
@gbaned I need help in understanding the linux cpu error, can anyone help me? Sorry for a late response have my end-term exams going on

**Comment by sachinprasadhs** [comment]
> @gbaned I need help in understanding the linux cpu error, can anyone help me? Sorry for a late response have my end-term exams going on

You need to fix the indentation problem appearing in PyLint first and then you can work on other errors.

**Comment by gbaned** [comment]
Hi @Cheril311 Ling Any update on this PR? Please. Thank you!

**Pull request closed without merging**
