### PR TITLE
Update README.md for graph transform

### PR DESCRIPTION
**Pull request by raingo**
Do not recommend to use`remove_nodes(op=Identity, op=CheckNumerics)` in the README. It breaks the control flow based operations.

### CODE REVIEW

**Comment by yifeif** [comment]
Thanks for sending the PR @raingo. @petewarden mind taking a look? Thanks!

**Comment by petewarden** [comment]
Thanks for the PR! Can you give some more background on the specific issues you're hitting? Control flow is generally only needed for Variable assignment, which generally doesn't happen during inference, so it would be good to know more about what's going wrong in your case.

**Comment by raingo** [comment]
@petewarden For example, for object detection, there is a `tf.image.non_max_suppression` step per each object class. I used `tf.map_fn`to iterate through each class. This iteration is necessary in the deploy time.

**Comment by drpngx** [comment]
@petewarden any modifications we would need here?

**Comment by petewarden** [comment]
Sorry for the slow response on this. Can we address this by leaving the code example but adding documentation along the lines of "this may cause problems if you have a model with control-flow based operations"? I'd hate people to miss out on the optimizations in other cases.

I think the real solution would be to warn or otherwise avoid removing ops that are significant for control flows, but I'm not sure how to do that yet.

**Comment by vrv** [comment]
ping for @raingo !

**Comment by raingo** [comment]
@petewarden PTAL. Just added a note about the control flow ops.

**Review by petewarden — APPROVED** [review]
That looks good, thanks!

**Pull request merged**
