### PR TITLE
[tflite] Tests for the operator PACK quantization

### PR DESCRIPTION
**Pull request by wwwind**
There is a bug in the current implementation of the operator PACK.
The multiple inputs should be requantized.
The current PR fixes this bug and adds a test for the quantization of the PACK operator.

### CODE REVIEW

**Comment by suharshs** [comment]
Hi, I believe the aribitrary_inputs and rescrict_same_input_output_scale params are sufficient, the tests are welcome additions though! Thanks!

**Comment by wwwind** [comment]
Hi Suharsh,

Yes, it makes sense. We kept this variable to be consistent with our solution to the maximum/minimum bug [PR](https://github.com/tensorflow/tensorflow/pull/32582).
I edited PR and left only C++ test.

Could you please review it ?
Thanks!

**Review by suharshs — DISMISSED** [review]

**Comment by wwwind** [comment]
Hi @suharshs, could you please take a look again ? The same problem with this PR - small complaint from the buildifier, that I have fixed.
Thanks!

**Review by suharshs — DISMISSED** [review]

**Comment by wwwind** [comment]
@suharshs Could you please review again ? I resolved merge conflicts and this dismissed PR approval. Thanks

**Review by suharshs — APPROVED** [review]

**Pull request merged**
