### PR TITLE
Fixes to build and run TFLite evaluation ios app

### PR DESCRIPTION
**Pull request by martin-etchart**
Minimal changes to build and run the TFLite evaluation tool on iOS.

### CODE REVIEW

**Comment by martin-etchart** [comment]
As discussed with @mihaimaruseac at https://github.com/tensorflow/tensorflow/pull/60019, this PR cherry-picks the single commit starting from the latest point in master branch.

**Review by terryheo — APPROVED** [review]
LGTM

**Review by mihaimaruseac — APPROVED** [review]

**Review by Neilblaze — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
This need manual changes internally to the copybara config due to the renamed file.

**Comment by martin-etchart** [comment]
> This need manual changes internally to the copybara config due to the renamed file.

Is there anything I can do to advance this?

**Comment by mihaimaruseac** [comment]
@terryheo can you shepherd this please? Looks like the renamed file requires copybara changes, so this needs to be manually imported

**Pull request merged**
