### PR TITLE
tflite label_image: add -llog and update doc

### PR DESCRIPTION
**Pull request by freedomtan**
1. -llog needed for Android after 2c623eaa
2. update label_image.md
   a. reflect changes
   b. where to get test model and data
   c. describe --cxxopt=-DTFLITE_PROFILING_ENABLED

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by freedomtan** [comment]
close this because lite is not longer in contrib/. Will send another one later

**Pull request closed without merging**
