### PR TITLE
DOC: Fix typos in readme.

### PR DESCRIPTION
**Pull request by csukuangfj**

### CODE REVIEW

**Comment by rthadur** [comment]
@csukuangfj please sign CLA

**Comment by csukuangfj** [comment]
I signed it!

**Comment by rthadur** [comment]
@csukuangfj thank you but our system still shows there is no CLA signed , make sure you give all necessary information , ex: email

**Comment by csukuangfj** [comment]
Please check again. I really signed it.

**Review by ymodak — APPROVED** [review]

**Pull request merged**
