### PR TITLE
Fixing python3 issues

### PR DESCRIPTION
**Pull request by martinwicke**

### CODE REVIEW

**Comment by jendap** [comment]
Nice, it seems to fix a few. But not all - 4 done, 6 to go :)

**Comment by martinwicke** [comment]
That last commit should fix a couple more, but at least two left, I think. Off to bed. Goodnight.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
3 left: 

saver_test (Any has no attribute Pack)
tensorboard:server_test ('very_large_attr' has type <class 'str'>, but expected one of: (<class 'bytes'>,))
scda_ops_test: abort (trying to register op twice?)

@sherrym, @danmane, can you take a look at the saver and tensorboard issues, respectively?

see details at
http://ci.tensorflow.org/job/tensorflow-pull-requests-mac-python3/93/consoleFull

**Comment by martinwicke** [comment]
I'll merge this now for the other fixes.

**Comment by martinwicke** [comment]
merged.

**Pull request closed without merging**
