### PR TITLE
MutableDenseHashTable should check empty keys before Rebucket when Insert

### PR DESCRIPTION
**Pull request by evanrang**
MutableDenseHashTable Insert operation should check empty keys before Rebucket, otherwise too much empty keys may cause the table too large

### CODE REVIEW

**Comment by rangjiaheng** [comment]
@allenlavoie hi, could you help review this patch ? we got huge memory used since unchecked keys, thanks

**Comment by rangjiaheng** [comment]
😳

**Comment by gbaned** [comment]
@rohan100jain Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@rohan100jain Can you please review this PR ? Thanks!

**Pull request closed without merging**
