### PR TITLE
Adding support for Linux s390x 

### PR DESCRIPTION
**Pull request by namrata-ibm**
Adding support for Linux s390x. Could someone please review?

### CODE REVIEW

**Comment by Nayana-ibm** [comment]
@vrv 
We have re-created this PR after closing #4508 

We have incorporated @aselle's  suggestion about cpu_info.h. 
Could you please have a look?

**Comment by gunan** [comment]
Jenkins, test this please.
Leaving the review to @aselle

**Comment by gunan** [comment]
Windows failures are definitely caused by changes here. GPU failures are also suspicious, but I will rerun the tests to make sure.
@namrata-ibm Could you take a look at windows failures here:
https://ci.tensorflow.org/job/tensorflow-pr-win-cmake-py/286/

For GPU tests,
Jenkins, test this please.

**Comment by namrata-ibm** [comment]
Windows failures are occurring because of following error:
`c:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\tensorflow\core\platform\cpu_info.h(23): error C2065: '__ORDER_LITTLE_ENDIAN__': undeclared identifier (compiling source file C:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\tensorflow\core\platform\file_system.cc)`

This change was added as per aselle's  [review comment](https://github.com/tensorflow/tensorflow/pull/4508/files#r81671579) in our earlier PR.

@aselle , any inputs on how to make it work on Windows?

**Comment by guschmue** [comment]
__BYTE_ORDER__ is defined by gcc and windows compiles with msvc which does not define it.
There is no platform specific platform.h and looking over the source I see lots of places that include cpu_info.h directly. Maybe a decent compromise between clean and safe would be to create a new include platform/windows/msvc_compat.h and include this in cpu_info.h under #ifdef COMPILE_MSVC.
@mrry what do you think?

**Comment by mrry** [comment]
@guschmue I think the standard workaround for this would be to create `tensorflow/core/platform/windows/cpu_info.h`, `tensorflow/core/platform/posix/cpu_info.h`, etc. and have `tensorflow/core/platform/cpu_info.h` include the appropriate header based on what `PLATFORM_*` macro was defined. Is there a subtlety I'm missing here?

**Comment by guschmue** [comment]
sure that will work. @namrata-ibm , I can help with the change if you want me to.

**Comment by namrata-ibm** [comment]
@guschmue , Thank you for your inputs. Would be great if you could help with above change suggested by mrry.

**Comment by guschmue** [comment]
ok, should be getting to it today.

**Comment by namrata-ibm** [comment]
have added fix for another test here.
@guschmue , thanks and let us know if anything needs to be done from our side.

**Comment by guschmue** [comment]
sorry, some else came up. should be getting to it tomorrow.

**Comment by namrata-ibm** [comment]
@aselle, we have added a fix for decode_raw_op_test in the PR.

According to the [readme](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard3/tf.decode_raw.md) the tf.decode_raw has an attribute little_endian whose default value is set to true in parsing_ops.cc (flag ignored for uint8). 
If we set the value of the flag to False for big endian, the assert for endianness check doesn't fail on either systems (little endian or big endian) and the following data copying works on both systems.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by guschmue** [comment]
@namrata-ibm - windows should compile now with your change but you need to merge platform\cpu_info.h from master,

**Comment by namrata-ibm** [comment]
@guschmue, Thank you for the PR for Windows support.
@gunan , Could you please run a build in your CI now?

**Comment by gunan** [comment]
@Nayana-ibm  Could you Check the CLA?
If you read and signed the CLA, please add a comment that says "I signed it!"

Jenkins, test this please.

**Comment by Nayana-ibm** [comment]
I signed it! 
(covered as part of IBM Google Corporate CLA)

**Comment by vrv** [comment]
Your commit email on git is shown as
From: namrata-ibm <bhavenamrata@gmail.com>

I'm guessing that's not the email you used to sign up to your internal google groups associated with the IBM account.  You might want to commit --amend with the email you've registered with your company.

**Comment by gunan** [comment]
There are quite a few pylint failures, mostly inconsistencies with google style:
```
FAIL: Found 34 non-whitelited pylint errors:
tensorflow/python/kernel_tests/decode_raw_op_test.py:32: [W0311(bad-indentation), ] Bad indentation. Found 9 spaces, expected 8

tensorflow/python/kernel_tests/decode_raw_op_test.py:34: [W0311(bad-indentation), ] Bad indentation. Found 9 spaces, expected 8

tensorflow/python/kernel_tests/decode_raw_op_test.py:53: [W0311(bad-indentation), ] Bad indentation. Found 9 spaces, expected 8

tensorflow/python/kernel_tests/decode_raw_op_test.py:55: [W0311(bad-indentation), ] Bad indentation. Found 9 spaces, expected 8

tensorflow/python/kernel_tests/decode_raw_op_test.py:60: [W0311(bad-indentation), ] Bad indentation. Found 9 spaces, expected 8

tensorflow/python/kernel_tests/decode_raw_op_test.py:63: [W0311(bad-indentation), ] Bad indentation. Found 9 spaces, expected 8

tensorflow/python/kernel_tests/decode_raw_op_test.py:75: [W0311(bad-indentation), ] Bad indentation. Found 9 spaces, expected 8

tensorflow/python/kernel_tests/decode_raw_op_test.py:77: [W0311(bad-indentation), ] Bad indentation. Found 9 spaces, expected 8

tensorflow/python/framework/tensor_util_test.py:48: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:54: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:66: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:72: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:84: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:90: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:103: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:109: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:121: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:127: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:139: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:145: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:168: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:174: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:254: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:260: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:320: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:326: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:338: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:344: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:359: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:365: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:396: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:402: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:413: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6

tensorflow/python/framework/tensor_util_test.py:419: [W0311(bad-indentation), ] Bad indentation. Found 5 spaces, expected 6
```
Could you fix those, the I can rerun all the tests.
(also the email issue Vijay mentioned)

**Comment by Nayana-ibm** [comment]
I have CLA signed for gmail id : nayana.thorat@gmail.com
I could see corporate CLA entry here : https://cla.developers.google.com/clas

**Comment by namrata-ibm** [comment]
I could see CLA for my id as well: bhavenamrata@gmail.com
Also our commit IDs and author IDs are the same. 
Could you please confirm if we are missing something here?

**Comment by gunan** [comment]
One possible solution to the CLA issue is to squash all the commits in this PR to a single commit, and then retry creating the PR.
Would that be OK?

Also, you will need further edits to fix the test failures reported by jenkins.

**Comment by namrata-ibm** [comment]
@gunan, ok, we will work on recreating PR with the edits and by pulling latest changes to resolve conflicts shown above.

**Comment by namrata-ibm** [comment]
@mrry, @guschmue, @vrv , While debugging sparse_split_op_test on big endian system, I could observe that tests involving column wise splitting are failing.
 This seems to happen because `context->input(0).scalar<int>()();`  returns 0 instead of 1  in OpKernel for sparse_split test ( from [file](https://github.com/tensorflow/tensorflow/blob/v0.10.0/tensorflow/core/kernels/sparse_split_op.cc ) - pasted code snippet below : ) 
```
void Compute(OpKernelContext* context) override { 
     const int32 split_dim = context->input(0).scalar<int>()();  
     const Tensor& input_indices = context->input(1); 
```
looks like the **scalar\<int\>()()** is not converting the data correctly. While stepping through the scalar function, came across below code snippets:
From [file
](https://github.com/tensorflow/tensorflow/blob/v0.10.0/tensorflow/core/framework/tensor.h#L621)

```
  template <typename T>
  T* base() const {
    return reinterpret_cast<T*>(data());
  }
};

template <typename T>
T* Tensor::base() const {
  return buf_ == nullptr ? nullptr : buf_->base<T>();
}
```
data() picks value[ from](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.cc#L92):

` void* data() const override { return data_; }`
Here printing *data_ gives 1! However this does not propagate to split_dim which remains 0.

 I am unable to catch the exact point where the manipulation is happening. Could you please have a look?

**Comment by aselle** [comment]
@namrata-ibm: The decode_raw option for little endian is not whether the system is little endian, it is whether the data is little endian. So in particular, if you copy data that is little endian to a big endian machine you should be able to call decode_raw with false on those sequence of bytes and work.  What you said you did doesn't sound right in that regard.

**Comment by namrata-ibm** [comment]
@aselle , ok, so I tried running the test without setting decode_raw option for little endian, This caused the test to fail with error `"UnimplementedError: Unimplemented support for little_endian=true"`. 
Next, I removed below assert to verify if the further code for copying the data works. This resulted in test case to pass on Big Endian as it copies data  byte-by-byte.

```
     DCHECK_EQ(flat_in.size(), out.dimensions()[0]);
-    OP_REQUIRES(
-        context,
-        little_endian_ == ::tensorflow::port::kLittleEndian || sizeof(T) == 1,
-        errors::Unimplemented("Unimplemented support for little_endian=",
-                              little_endian_ ? "true" : "false"));
     // Endianness matches, so just copy each string byte-for-byte.
     T* out_data = out.data();
     for (int64 i = 0; i < flat_in.size(); ++i) {
	   const T* in_data = reinterpret_cast<const T*>(flat_in(i).data());
       memcpy(out_data, in_data, str_size);
       out_data += added_dim;
     }

```
The only change in [test case ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/decode_raw_op_test.py)for Int16 for Big Endian was  
```
     if sys.byteorder == "big": 
        self.assertAllEqual([[ord("A") * 256 + ord("a"), 
                                ord("B") * 256 + ord("C")]], result) 
     else: 
        self.assertAllEqual([[ord("A") + ord("a") * 256, 
                                ord("B") + ord("C") * 256]], result) 

```

**Comment by namrata-ibm** [comment]
@gunan , We have re-created PR for resolving CLA issue with single commit. 
Also, we have fixed the test failures reported by jenkins.

Link to new [PR ](https://github.com/tensorflow/tensorflow/pull/6681)

Closing this PR.

**Pull request closed without merging**
