### PR TITLE
refactor learning rate related code for the optimizers

### PR DESCRIPTION
**Pull request by raingo**
This is one step forward to solve #313. It's overshot to use multiple optimizers just for different learning rate.

Control the learning rate on the root class of the optimizers.

### CODE REVIEW

**Comment by raingo** [comment]
I signed it!

**Comment by martinwicke** [comment]
I'm conflicted -- the optimizer interface is too narrow as it is, and learning rate is not necessarily universal (although arguably it is for the optimizers we actually support). @rmlarsen, an opinion?

**Comment by rmlarsen** [comment]
We might want  to implement other optimizers where the concept of "learning rate" does not make sense (such as second order methods), so I find moving it to the base class is not the right design.

**Comment by raingo** [comment]
Gotta.

**Pull request closed without merging**
