### PR TITLE
Bijector mapping  deep tuple fix

### PR DESCRIPTION
**Pull request by hartikainen**
Right now, Bijector _Mapping's _deep_tuple doesn't allow nested dicts. This problem causes some of the conditioning not to work. See:  #21543. This PR is a possible way to fix the issue.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 33 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 48 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ebrevdo** [comment]
@jvdillon ptal.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by hartikainen** [comment]
@ebrevdo @jvdillon Does this PR make sense? If it does, would it make sense for me to move it under tfp?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request closed without merging**
