### PR TITLE
Fix compilation error caused by cuda and cusparse stub files

### PR DESCRIPTION
**Pull request by xcnick**
This pr fix compilation error caused by cuda and cusparse stub files, tested in cuda 10.1.

### CODE REVIEW

**Comment by xcnick** [comment]
@googlebot I signed it!

**Comment by sanjoy** [comment]
As written, I'm not sure if this PR is correct.  Can you please share some more details on what the root cause was and how you fixed it?

**Comment by xcnick** [comment]
Of course.
When compiling `//tensorflow/stream_executor/cuda:cudart_stub` in cuda 9.0/10.0/10.1/11.2, In function `cudaChannelFormatDesc cudaCreateChannelDesc(int, int, int, int, cudaChannelFormatKind)`, the return value type of `GetSymbolNotFoundError()` is `cudaError_t`, and it does not match the return value type expected by `cudaCreateChannelDesc`. These changes refer to `cuda_runtime_11_0.inc`. The changes in file `cusparese_x_x.inc` are similar.

**Comment by gbaned** [comment]
@sanjoy Can you please assist on above comments from @xcnick. Thanks!

**Comment by xcnick** [comment]
Close this pr since it has been fixed.

**Pull request closed without merging**
