### PR TITLE
tf.Print converts Variable to mutable Tensor

### LINKED ISSUE #14788: tf.print makes a variable a constant?
```
In [1]: import tensorflow as tf

In [2]: # using print

In [3]: entcoeff =  tf.Variable([0], dtype=tf.float32, trainable=False)
   ...: entcoeff = tf.Print(entcoeff,[entcoeff,"printing"])

In [4]: tf.assign(entcoeff, [-1.])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-dd57efca5923> in <module>()
----> 1 tf.assign(entcoeff, [-1.])

/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py in assign(ref, value, validate_shape, use_locking, name)
    270         ref, value, use_locking=use_locking, name=name,
    271         validate_shape=validate_shape)
--> 272   return ref.assign(value)

AttributeError: 'Tensor' object has no attribute 'assign'

In [5]: # not using print

In [6]: entcoeff =  tf.Variable([0], dtype=tf.float32, trainable=False)

In [7]: tf.assign(entcoeff, [-1.])
Out[7]: <tf.Tensor 'Assign:0' shape=(1,) dtype=float32_ref>

```

### PR DESCRIPTION
**Pull request by facaiy**
The PR is proposed to resolve #14788.

tf.Print converts Variable to mutable Tensor, instead of constant.

```python
v = tf.Variable([99])
# <tf.Variable 'Variable:0' shape=(1,) dtype=int32_ref>

p = tf.Print(v, [v])
# Tensor("PrintRef:0", shape=(1,), dtype=int32_ref)
```

### How to test

+ [x] add test case
+ [ ] pass all tests

### CODE REVIEW

**Comment by mrry** [comment]
Handing this off to @alextp as variables czar. I think this approach won't play at all well with `ResourceVariable`, so it might need some more work....

**Comment by alextp** [comment]
Can't you achieve the same result by doing the following in the definition of Print:

```
 if v.dtype._is_ref:
  with ops.control_dependencies([Print(constant_op.constant(1), data)]):
    return gen_array_ops._ref_identity(v._ref)
```
?

**Comment by alextp** [comment]
Though I do discourage you from writing such code. Why do you want this? Forwarding mutable references to variables is weird and not quite future-proof with resource variables.

**Comment by facaiy** [comment]
Thanks for feedback, @mrry , @alextp . 
Yes, I also think it weird to convert variable to mutable tensor. @alextp 's solution is better and straight.

**Pull request closed without merging**
