### PR TITLE
Updating install_golang.sh - bumping to 1.8.3

### PR DESCRIPTION
**Pull request by ctava**

### CODE REVIEW

**Comment by frankchn** [comment]
Jenkins, test this please.

**Review by asimshankar — APPROVED** [review]
Thanks for the update!

**Comment by asimshankar** [comment]
FYI @av8ramit @gunan

**Comment by asimshankar** [comment]
Jenkins, test this please.

The CI failures seem like infrastructure failures.
Trying again

**Comment by ctava** [comment]
Jenkins, test this please.

**Comment by frankchn** [comment]
Jenkins, test this please.

**Pull request merged**
