### PR TITLE
[oneDNN] Remove StopGradient op seen in some LayerNorm patterns

### PR DESCRIPTION
**Pull request by kanvi-nervana**
Following pattern is seen in 3 models. It looks similar to InstanceNorm pattern but it is actually LayerNorm based on the reduction axis. Under right conditions, this pattern will be fused as LayerNorm to improve performance.

layernorm-pattern

StopGradient is removed as part of optimize_for_inference since it is not required and is a training op.
"When used in a graph, it outputs the input as is" https://www.tensorflow.org/api_docs/python/tf/stop_gradient

### CODE REVIEW

**Comment by BrianWieder** [comment]
@gbaned Could you find another reviewer, I don't think that I am the correct person to review this.

**Comment by gbaned** [comment]
> @gbaned Could you find another reviewer, I don't think that I am the correct person to review this.

Hi @BrianWieder Sorry for the late reply. Sure thing, Thank you for the update.

**Comment by gbaned** [comment]
Hi @penpornk, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk, Can you please review this PR ? Thank you!

**Comment by cantonios** [comment]
@kanvi-nervana can you fix the image link?

**Review by cantonios — CHANGES_REQUESTED** [review]
Update PR description with working image link

**Comment by gbaned** [comment]
Hi @kanvi-nervana Can you please check @cantonios's comments and keep us posted ? Thank you!

**Comment by kanvi-nervana** [comment]
> Update PR description with working image link

Uploaded the image again, please let me know if you still have any issue. Thanks!

**Review by cantonios — APPROVED** [review]

**Pull request merged**
