### PR TITLE
1.9-rc0 cherry-pick request: Keras symbol visibility, and `Dataset` evaluation fixes.

### PR DESCRIPTION
**Pull request by MarkDaoust**
The first two commits fix visibility for various Keras symbols.
The last one fixes Dataset-evaluation in eager mode (was only running 1 step regardless of steps-argument).

cl/199161696
cl/199198086
cl/199645638

### CODE REVIEW

**Review by case540 — APPROVED** [review]
These seem small/important enough to cherrypick. Thanks!

**Comment by drpngx** [comment]
This is not in master, better @yifeif handle this.

**Comment by MarkDaoust** [comment]
> This is not in master, better @yifeif handle this.

I made this with the cherry-picker tool, will that let you cherry-pick something that isn't in master?

All three of the source commits are in master now:

cl/199161696 -->  https://github.com/tensorflow/tensorflow/commit/5f315a292a65bd898a736cd305152f348846718a

cl/199198086 -->
https://github.com/tensorflow/tensorflow/commit/6b2a088fb263af2428ca672a62088646a7f54219

cl/199645638 --> 
https://github.com/tensorflow/tensorflow/commit/086d96aea3d6b3272b2746359e13f4156072ff8b

**Comment by case540** [comment]
No, the cherrypicker.py util script should only be able to cherrypick commits from github master.

**Comment by MarkDaoust** [comment]
Thanks Mike.

**Pull request merged**
