### PR TITLE
Fix typos in strings and docs in CUDA module

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by zheng-xq** [comment]
@dongjoon-hyun, Thank you for your contribution. Unfortunately, TensorFlow doesn't really own stream-executor. And this has to be fixed there first. I will pass on your changes to the stream-executor team to incorporate them upstream. Then TensorFlow will benefit from it automatically.

**Comment by dongjoon-hyun** [comment]
Oh, I see. Thank you for informing me that, @zheng-xq .

By the way, could you give me some URLs for contributing stream-executor code? Github or googlesource? I hope to contribute there directly next time if it is possible.

**Comment by zheng-xq** [comment]
Unfortunately, the stream-executor team is still working on their own open-sourcing. That's why TensorFlow currently carries a copy. When they are ready for their own open-sourcing, we will drop our copy, and refer to the public one. But for now, you are doing the right thing. Although we cannot accept the pull request, we will pass them to the stream-executor to make the change upstream.

**Comment by dongjoon-hyun** [comment]
I see. Now I understand the situation. Okay, no problem.
Thank you for taking the passing jobs. :)

**Comment by vrv** [comment]
Closing for now, I assume this is on the roadmap, @zheng-xq and @leary-google ?

**Pull request closed without merging**
