### PR TITLE
Avoid installing newest pip and wheel versions

### PR DESCRIPTION
**Pull request by mpenagar**
https://bootstrap.pypa.io/get-pip.py  was updated (pip-18.0, setuptools-40.0.0 and wheel-0.31.1) on 22-Jul-2018

### CODE REVIEW

**Comment by mpenagar** [comment]
I signed it!

**Comment by gunan** [comment]
Is there a bug that requires us to avoid installing the latest version?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
Closing, because there are changes coming to the dockerfiles, and was not able to verify if this is still an issue.

**Pull request closed without merging**
