### PR TITLE
fix numpy 1.20

### PR DESCRIPTION
**Pull request by fsx950223**
Related #48918

### CODE REVIEW

**Comment by bhack** [comment]
I think that `>=` probably It will be a little bit "out of control" for the TF team. But I could be wrong. /cc @mihaimaruseac

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
This got rolled back

**Comment by bhack** [comment]
> This got rolled back

Do you know why?

**Comment by mihaimaruseac** [comment]
A TFX test broke, but didn't look into why yet.

**Pull request merged**
