### PR TITLE
Support dense tensors in _SequenceNumericColumn

### PR DESCRIPTION
**Pull request by jperl**
Resolves https://github.com/tensorflow/tensorflow/issues/20478

To Do:

- [ ] Add unit tests

### CODE REVIEW

**Review by ispirmustafa — CHANGES_REQUESTED** [review]
thank you!
could you please add a unit test? otherwise lgtm

**Comment by jperl** [comment]
Will do :+1:

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by jperl** [comment]
Closing. We switched away from feature columns.

**Pull request closed without merging**
