### PR TITLE
Numpy and dataframe converter

### PR DESCRIPTION
**Pull request by rd16395p**
Addresses issue #43487, coded with @nelsonlin2708968 and @vulkomilev. Previous change from PR https://github.com/tensorflow/tensorflow/pull/45066. 

Numpy feature is located within https://www.tensorflow.org/api_docs/python/tf/make_ndarray/ .

### CODE REVIEW

**Comment by rd16395p** [comment]
@vulkomilev can you check if you signed the CLA please?

**Comment by gbaned** [comment]
@rd16395p Can you please sign CLA. Thanks!

**Comment by rd16395p** [comment]
@gbaned I have signed the cla. Are we missing someone else? 

@googlebot I fixed it.

**Comment by vulkomilev** [comment]
I can't login for some reason

На ср, 19.05.2021 г. в 14:34 ч. Becca ***@***.***> написа:

**Comment by rd16395p** [comment]
@googlebot I fixed it.

**Comment by rd16395p** [comment]
@gbaned It seems that the cla bot is not recognizing @vulkomilev 's agreement, maybe you can check if it exists please?

**Comment by vulkomilev** [comment]
Yeah this shows up when I try to sing it again
[image: Screenshot from 2021-05-21 15-38-55.png]


На пт, 21.05.2021 г. в 14:59 ч. Becca ***@***.***> написа:

**Comment by rd16395p** [comment]
Looks like it passed 👍

**Comment by vulkomilev** [comment]
Okay so now we just wait to be approved and merged?

На сб, 22.05.2021 г. в 20:24 ч. Becca ***@***.***> написа:

**Comment by rd16395p** [comment]
Looks like it!

**Comment by gbaned** [comment]
@aaudiber Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@aaudiber Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@aaudiber Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@aaudiber Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@aaudiber Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@aaudiber Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
@aaudiber Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @aaudiber Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @aaudiber Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @aaudiber Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @aaudiber Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rd16395p Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @rd16395p Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @rd16395p Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @rd16395p Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @rd16395p Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @rd16395p Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @rd16395p I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for your contribution!

**Pull request closed without merging**
