### PR TITLE
Register missing gradient for tf.nn.max_pool_with_argmax

### PR DESCRIPTION
**Pull request by fabianschilling**
Registering the gradient should fix issue #1793. 

The corresponding test is already present in [pooling_ops_test.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/pooling_ops_test.py) (correct me if I'm wrong).

### CODE REVIEW

**Comment by rmlarsen** [comment]
Please add corresponding unit tests.

**Comment by rmlarsen** [comment]
sorry, you are correct, the tests are already there.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
(if the tests were already there, why wasn't the test failing because of a lack of a gradient?)

**Comment by rmlarsen** [comment]
@fabianschilling could you please investigate why the tests were not failing before. Modify the unit tests or add a new one that would fail and demonstrates the need for the registration.

**Comment by fabianschilling** [comment]
I will look into it!

Btw, the CPU tests were failing because of an assertion error in `file_io_test.py`:

```
============== BEGINS failure log content ==============
....................F.....
======================================================================
FAIL: testStat (__main__.FileIoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pip_test/tests/file_io_test.py", line 279, in testStat
    self.assertEqual(33188, file_statistics.mode)
AssertionError: 33188 != 33206

----------------------------------------------------------------------
Ran 26 tests in 0.257s

FAILED (failures=1)
============== ENDS failure log content ==============
```

**Comment by rmlarsen** [comment]
@fabianschilling don't worry about the file_io test. It is flaky.

**Comment by danmane** [comment]
@fabianschilling Please also rebase, since the branch now has conflicts.

**Comment by martinwicke** [comment]
@fabianschilling please rebase, then I can run a final test and possibly merge.

**Comment by martinwicke** [comment]
Talked with @fabianschilling, will close this PR, he'll make a new one.

**Comment by tomrunia** [comment]
What is the status on this? Is there any work around for using `tf.nn.max_pool_with_argmax` at the current `master`?

**Pull request closed without merging**
