### PR TITLE
Edit train.exponential_decay sample code

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by vladzzag** [comment]
I signed it!

**Comment by vrv** [comment]
Thanks, you'll also need to make the same modification to https://github.com/tensorflow/tensorflow/blob/f2bd0fc399606d14b55f3f7d732d013f32b33dd5/tensorflow/python/training/learning_rate_decay.py#L53 -- our MD files are generated from the original source documentation.

**Comment by vrv** [comment]
Thanks, can you address any merge conflicts and squash the changes?  (Sorry, github doesn't notify me when you push changes without commenting on this thread).

**Comment by vladzzag** [comment]
@vrv, commits are squashed and the branch is up-to-date.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
Merged

**Pull request closed without merging**
