### PR TITLE
Update Dockerfiles to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by angerson**
This seemed to mostly work locally, so I'm making this change to see if
our automation will pick it up and succeed. This also updates the
container Python version to one newer than 3.6 and the CUDA version to
11.2.

One notable new requirement is that users must run ldconfig after the
image starts to pick up libraries that are mounted by nvidia-docker. If
the automation is successful, then I'll look into updating the Docker
Hub page.

Working with this system is getting to be quite the hassle, so I'm glad
to be able to drop it in the future.

### CODE REVIEW

**Comment by angerson** [comment]
FYI @bhack

**Review by mihaimaruseac — APPROVED** [review]

**Comment by bhack** [comment]
I had some extra commit at the old https://github.com/tensorflow/tensorflow/pull/48371 but I suppose that are for the next devel generation. 
If the "next-gen" will be too far in the future I suggest to recover at least `clang-format` and `pylint` availability in the devel images.

**Comment by bhack** [comment]
P.s. also in my PR there was a diff in https://github.com/bhack/tensorflow/blob/master/tensorflow/tools/dockerfiles/spec.yml.

Why we don't see any diffs on this file here?

**Review by bhack — COMMENTED** [review]
Before merging this check my two comments if you can.

**Comment by angerson** [comment]
> I had some extra commit at the old #48371 but I suppose that they are for the next tensorflow:devel generation.
If the "next-gen" will be too far in the future I suggest to recover at least clang-format and pylint availability in the devel images.

Good idea, I added clang-format but not pylint since it can be installed quickly to match the GitHub Action.

> P.s. also in my PR there was a diff in https://github.com/bhack/tensorflow/blob/master/tensorflow/tools/dockerfiles/spec.yml. Why we don't see any diffs on this file here?

I didn't include the precommit stuff from your PR (which is one reason why I split this into a new one), which is one part of the `spec.yml` changes, and I changed the `UBUNTU_VERSION` variable in-place, which covers both of the changes to `spec.yml`.

**Comment by bhack** [comment]
> but not pylint since it can be installed quickly to match the GitHub Action.

I think that this is an expectation with a very low probability. I don't think that contributors will care to install the right `pylint` version that match the Github Action. Who is going by default to check the Github Action log details or source code?
It is why some month ago [I've requested to run the linting action with exactly the same `tesnorflow:devel` image](https://github.com/tensorflow/tensorflow/pull/50133#issuecomment-856329703) so that we was exactly on the same page, locally and GithubAction, with a very little effort.

>  I changed the UBUNTU_VERSION variable in-place, which covers both of the changes to spec.yml

But do you have still used the scripts to generate this PR/diff or with the in-place change you have manually edited all the Dockerfiles?

**Comment by bhack** [comment]
Thanks

**Pull request merged**
