### PR TITLE
update word2vec_basic.py:	Fix TSNE invocation in Udacity word2vec assignment

### PR DESCRIPTION
**Pull request by Shuolongbj**
Update 5_word2vec.ipnb-

Fix TSNE invocation in Udacity word2vec assignment

#add method='exact' .fix ValueError

num_points = 400
tsne = TSNE(perplexity=30, n_components=2, init='pca',n_iter=5000,**method='exact'**)
two_d_embeddings = tsne.fit_transform(final_embeddings[1:num_points+1, :])

### CODE REVIEW

**Comment by frankchn** [comment]
Jenkins, test this please.

**Review by vincentvanhoucke — CHANGES_REQUESTED** [review]
Can you provide a minimal diff of the .ipynb file?
Also, please explain why you are making that change, your description is not very informative right now, I have no idea what method='exact' means. Thanks!

**Comment by Shuolongbj** [comment]
@vincentvanhoucke thank you.pls check here again.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/5_word2vec.ipynb



num_points = 400

tsne = TSNE(perplexity=30, n_components=2, init='pca', n_iter=5000)
two_d_embeddings = tsne.fit_transform(final_embeddings[1:num_points+1, :])


#add method='exact' .you should add the method that can run correctly
num_points = 400
tsne = TSNE(perplexity=30, n_components=2, init='pca',n_iter=5000,method='exact')
two_d_embeddings = tsne.fit_transform(final_embeddings[1:num_points+1, :])

**Comment by vincentvanhoucke** [comment]
Sorry, I meant to just have the one line change in the pull request code. Right now your diff is very large and unreadable as a result. Does the colab no longer work with the default method? I see that it now defaults to ‘barnes_hut’. Thanks!

**Comment by Shuolongbj** [comment]
5-word2vec

**Comment by Shuolongbj** [comment]
@vincentvanhoucke @frankchn ,i send a new PR(here) for fix the word2vec_basic.py
(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/word2vec/word2vec_basic.py)
fix the tsne class work with  method='barnes_hut' or 'method=’exact’ .please check & update it with the above PR.thank you all

**Comment by vincentvanhoucke** [comment]
Thanks for this! Again, the diff in the .ipynb file is 900 lines long at this point. I can't accept a large change like that. Ideally, it would be a 1 line diff, with just the addition of `,method='exact'` on the right line. Then we can commit it.

**Comment by Shuolongbj** [comment]
5_word2vec

this PR include two update(the same issue.)
1、 https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/5_word2vec.ipynb
2、
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/word2vec/word2vec_basic.py

@vincentvanhoucke Need i close the current pr and re-PR again? Thank you

**Comment by vincentvanhoucke** [comment]
That was unnecessary. I've created a PR with the minimal fix (#11482) which makes the change easy to revies. Thanks for pointing out the issue!

**Comment by vincentvanhoucke** [comment]
@Shuolongbj  Maybe you can repoen this PR with just the change the word2vec_basic.py change and retitle it. I'd be happy to approve that. Thanks!

**Comment by Shuolongbj** [comment]
@vincentvanhoucke thank you.i resend here #11483

**Pull request closed without merging**
