### PR TITLE
Add data format into MKL maxpool cache key.

### LINKED ISSUE #61482: Incorrect tf.nn.max_pool2d outputs for NCHW and NHWC in the same thread.
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.13

### Custom code

No

### OS platform and distribution

Ubuntu 22.04

### Mobile device

_No response_

### Python version

3.10

### Bazel version

_No response_

### GCC/compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current behavior?

There is an incorrect output of tf.nn.max_pool2d when calling with the input of the same batch size, height, width and depth first in NCHW, then in NHWC format with MKL support.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1Vuo7txDPDq-YXAuCFQcPNowHgOwbT7Oi?usp=sharing
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by API92**
Resolves tensorflow/tensorflow#61482

### CODE REVIEW

**Comment by agramesh1** [comment]
@gzmkl please review.

**Comment by gzmkl** [comment]
@penpornk  I have reviewed the code change which is fine. Thanks!  --GZ

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Pull request closed without merging**
