### PR TITLE
Fix compile warnings.

### PR DESCRIPTION
**Pull request by conqerAtapple**
Fixes instances of comparisons between 'signed' and 'unsigned'.

### CODE REVIEW

**Comment by conqer** [comment]
@cwhipkey please review. More compiler warning fixes. Maybe we should have a check for compiler warnings before commit?

**Review by cwhipkey — APPROVED** [review]

**Comment by dandelionmane** [comment]
@tensorflow-jenkins Test this please

**Comment by dandelionmane** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
