### PR TITLE
[TFLite] Add int16x8 support for comparison operators

### PR DESCRIPTION
**Pull request by johan-gras**
Hello,

This PR adds int16x8 support for comparison operators.
Comparison operators: LESS, GREATER, GREATER_EQUAL, LESS_EQUAL, EQUAL, NOT_EQUAL.

Furthermore, this PR transforms the absolute scaling of each input by a relative scaling (based on the highest scaling of the two inputs). This allows for greater precision when dealing with very small scales.

Thanks,
Johan.

### CODE REVIEW

**Comment by gbaned** [comment]
@miaout17 Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@miaout17 Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@johan-gras Can you please sign CLA. Thank you!

**Comment by gbaned** [comment]
Hi @johan-gras Can you please sign CLA. Thank you!

**Comment by johan-gras** [comment]
@gbaned signed.

**Comment by gbaned** [comment]
Hi @johan-gras Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @johan-gras Can you please resolve conflicts? Thank you!

**Comment by Tessil** [comment]
@gbaned Thanks, I resolved the conflicts.

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @johan-gras Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @johan-gras Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @johan-gras Any update on this PR? Please. Thank you!

**Comment by Tessil** [comment]
@gbaned Thanks, we fixed the conflicts.

**Comment by gbaned** [comment]
Hi @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @zichuan-wei Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @johan-gras Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @johan-gras Can you please resolve conflicts? Thank you!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Closing this as it has been stale since 2021. Please open again (a new one is better) if still relevant

**Pull request closed without merging**
