### PR TITLE
Add CUDA compute cap support of 3.0 for gpu.devel

### PR DESCRIPTION
**Pull request by chenliu0831**
See discussion in [#4048](https://github.com/tensorflow/tensorflow/issues/4048)

### CODE REVIEW

**Comment by martinwicke** [comment]
@caisq can you review? I'll merge without tests since no tests are affected by this change.

**Comment by caisq** [comment]
OK. Will take a look.

**Comment by caisq** [comment]
LGTM. Thanks.

@tensorflow-jenkins test this please.

**Comment by caisq** [comment]
Test failure appears to be unrelated.

@chenliu0831, can you please sign the CLA?

**Comment by chenliu0831** [comment]
@caisq Just signed. Thanks!

**Comment by caisq** [comment]
@tensorflow-jenkins test this please.

**Comment by caisq** [comment]
merged. thanks!

**Pull request merged**
