### PR TITLE
[oneDNN] Use original Threadpool scheduling approach if use_caller_thread is enabled

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR fixes a performance regression observed when user enables TF_ONEDNN_THREADPOOL_USE_CALLER_THREAD that allows one task to run on the main thread. This feature is off by default. Recent PR https://github.com/tensorflow/tensorflow/pull/60346 has made changes to threads scheduling which caused user_caller_thread feature (if enabled) to run slower than before (about 12% in Resnet50). This PR reverts to original scheduling in case user_caller_thread option is enabled.

### CODE REVIEW

**Review by penpornk — COMMENTED** [review]
Thank you for the PR!

@milpuz01 @nSircombe @cfRod Could you please help check if this affects your performance?

**Comment by gbaned** [comment]
Hi @milpuz01 @nSircombe @cfRod  Any update on this PR? Please. Thank you!

**Comment by davsva01** [comment]
> Hi @milpuz01 @nSircombe @cfRod Any update on this PR? Please. Thank you!

Hi @gbaned I have tested with this patch and there's no performance impact on our end. Thanks!

**Review by penpornk — APPROVED** [review]
@davsva01 Thank you for checking!
@mahmoud-abuzaina Thank you again for the PR!

**Pull request merged**
