### PR TITLE
Edit CosineSimilarity documentation on metrics.py

### PR DESCRIPTION
**Pull request by kwonmha**
Match dimensions of input and output of `l2_norm()`.
Applied same work done on #48633 to `metrics.py`.
It would have been better if I'm informed to avoid opening similar pr.

By the way, I would like to suggest to edit comments on `cosine_similarity()` and `CosineSimilarity()` on `losses.py`.
It confuses readers because the output of "cosine similarity" is mutiplied with -1.
It should be mentioned or the comments might be misunderstood.

Phrases to be modified are:
At line 1925
`Computes the cosine similarity between labels and predictions.`   <= negative cosine similarity
At line 1951 ~ 1952
```
Returns:
    Cosine similarity tensor.                                <= negative cosine similarity
```
At line 1961
`Computes the cosine similarity between labels and predictions.`   <= negative cosine similarity

### CODE REVIEW

**Review by deeb02 — APPROVED** [review]
The docstrings are confusing. Still are. But this change is an improvement.
Thank you for your change!

**Comment by kwonmha** [comment]
Good to see your agreed.
But I haven't made any modification on the docstrings about -1 multiplication.
Wanted to pick others' brain.

I'll comment here after pushing commit

**Comment by kwonmha** [comment]
It's done.
Please look into it.

**Comment by deeb02** [comment]
Actually, although I agreed that the first commit was a strict improvement. I'm not sure I feel comfortable with this change. It is strictly correct that this is the opposite of the standard cosine similarity, but it is very weird to have a method called cosine_similarity and have the docstring say it is negative cosine similarity. I'll take this one to the team's triage.

**Comment by deeb02** [comment]
Ideally the method should be renamed, but that would break backward compatibility if not done carefully. But all things considered, I liked the old docstring better. I don't like calling it negative cosine similarity

**Comment by kwonmha** [comment]
I got your point and agree with you.
Maybe I misunderstood that you would like to accept my suggestions.
I'll look forward to this to be arranged.

I pushed reverting commit.

TY.

**Review by deeb02 — APPROVED** [review]
Looks good to me. Thank you again.

**Pull request merged**
