### PR TITLE
[PluggableDevice] Make the dimensions constant in the C API's Allocate functions

### PR DESCRIPTION
**Pull request by PatriceVignola**
The allocate functions don't modify the dimensions, so there's no reason they can't be passed as constants. This makes it easier to call the API deep in a codebase when using arrays that are already constant and that we're not allowed to modify.

### CODE REVIEW

**Comment by gbaned** [comment]
@saxenasaurabh  Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@saxenasaurabh Can you please review this PR ? Thanks!

**Review by saxenasaurabh — APPROVED** [review]

**Comment by gbaned** [comment]
@PatriceVignola  Can you please resolve conflicts? Thanks!

**Comment by PatriceVignola** [comment]
@gbaned Done!

**Review by saxenasaurabh — APPROVED** [review]

**Pull request merged**
