### PR TITLE
something wrong with the path

### PR DESCRIPTION
**Pull request by Echofy**

### CODE REVIEW

**Comment by Echofy** [comment]
i signed it

**Comment by gunan** [comment]
I do not think this change will work. This is how `os.path.join` works:
```
>>> import os
>>> os.path.join('a', 'b')
'a/b'
>>> os.path.join('a', '/b')
'/b'
```
So the first part of the path, `TEST_TMPDIR` is ignored with your change. I am closing this PR.

**Comment by Echofy** [comment]
I just try the code both in linux and windows.The result is :linux users do not need to change anything,but if you use windows , you need to modify what i have been mentioned:

in linux:
`os.path.join(os.getenv('TEST_TMPDIR', '/tmp'),'/tensorflow/mnist/logs/fully_connected_feed')
'/tensorflow/mnist/logs/fully_connected_feed'
>>> os.path.join(os.getenv('TEST_TMPDIR', '/tmp'),'tensorflow/mnist/logs/fully_connected_feed')
'/tmp/tensorflow/mnist/logs/fully_connected_feed'
` 
in windows:
`>>> os.path.join(os.getenv('TEST_TMPDIR', '/tmp'),'/tensorflow/mnist/logs/fully_
connected_feed')
'/tensorflow/mnist/logs/fully_connected_feed'
>>> os.path.join(os.getenv('TEST_TMPDIR', '/tmp'),'tensorflow/mnist/logs/fully_c
onnected_feed')
'/tmp\\tensorflow/mnist/logs/fully_connected_feed'`

**Comment by Echofy** [comment]
I just try the code both in linux and windows.The result is :linux users do not need to change anything,but if you use windows , you need to modify what i have been mentioned:

in linux:
`os.path.join(os.getenv('TEST_TMPDIR', '/tmp'),'/tensorflow/mnist/logs/fully_connected_feed')
'/tensorflow/mnist/logs/fully_connected_feed'
>>> os.path.join(os.getenv('TEST_TMPDIR', '/tmp'),'tensorflow/mnist/logs/fully_connected_feed')
'/tmp/tensorflow/mnist/logs/fully_connected_feed'
`

in windows:
`>>> os.path.join(os.getenv('TEST_TMPDIR', '/tmp'),'/tensorflow/mnist/logs/fully_
connected_feed')
'/tensorflow/mnist/logs/fully_connected_feed'
>>> os.path.join(os.getenv('TEST_TMPDIR', '/tmp'),'tensorflow/mnist/logs/fully_c
onnected_feed')
'/tmp\\tensorflow/mnist/logs/fully_connected_feed'`

**Comment by gunan** [comment]
I still do not see why we may need your edit.
On windows, we clearlly should avoid using `/tmp`.
But your change makes all the statement a noop both on windows and linux, and it always returns `/tmp/tensorflow/mnist/logs/fully_connected_feed`. This is definitely something we do not want.

**Pull request closed without merging**
