### PR TITLE
Add property to get cell wrapped by DropoutWrapper 

### PR DESCRIPTION
**Pull request by michaelkhan3**
Adding wrapped cell property as discussed in #15810.

### CODE REVIEW

**Review by ebrevdo — APPROVED** [review]
i think this has to go through API approval.  if there's a failing test it'll give instructions on how to update the public API.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by sherrym** [comment]
Approved for tf-api-owners.

**Review by asimshankar — APPROVED** [review]

**Comment by drpngx** [comment]
@michaelkhan3 please update the goldens:

```
    $ bazel build tensorflow/tools/api/tests:api_compatibility_test
    $ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test \
          --update_goldens True
```

Note that you need to run that under python2.

**Comment by rmlarsen** [comment]
@michaelkhan3 Please update the golden files as described in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/api/tests/README.txt

**Comment by michaelkhan3** [comment]
Is that right?

**Comment by rmlarsen** [comment]
@michaelkhan3 thanks for the contribution!

**Pull request merged**
