### PR TITLE
Restore output shapes when loading V1 SavedModels.

### PR DESCRIPTION
**Pull request by frreiss**
The new `tf.saved_model.load_v2()` API currently ignores any shape information stored in the `SignatureDef`s of the SavedModel. For example, the following code snippet loads an object detection model from the [TensorFlow detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md):
```python
model_dir = "./ssd_mobilenet_v1_coco_2018_01_28/saved_model"
trackable = tf.saved_model.load_v2(model_dir)
print(trackable.signatures["serving_default"].outputs)
```
This code currently produces the following output:
```
[<tf.Tensor 'detection_boxes:0' shape=<unknown> dtype=float32>,
<tf.Tensor 'detection_classes:0' shape=<unknown> dtype=float32>,
<tf.Tensor 'detection_scores:0' shape=<unknown> dtype=float32>,
<tf.Tensor 'num_detections:0' shape=<unknown> dtype=float32>]
```
Note the `shape=<unknown>` for each output.

This PR modifies the behavior of `tensorflow.python.saved_model.load_v1_in_v2.load()` such that the output shapes in the returned `ConcreteFunction` match the output shapes in the original SavedModel. After these changes, the code snippet above produces the following output:
```
[<tf.Tensor 'detection_boxes:0' shape=(?, 100, 4) dtype=float32>,
 <tf.Tensor 'detection_classes:0' shape=(?, 100) dtype=float32>,
 <tf.Tensor 'detection_scores:0' shape=(?, 100) dtype=float32>,
 <tf.Tensor 'num_detections:0' shape=(?,) dtype=float32>]
```
Note the additional shape information that wasn't there before.

Most of the code modifications are in `WrappedFunction.prune()`, which I have extended to accept `TensorInfo` objects for fetches in addition to `Tensor` and `Operation` objects. I've included an automated regression test for the new functionality. I also added some documentation to `WrappedFunction.prune()`.

### CODE REVIEW

**Review by allenlavoie — DISMISSED** [review]
This is great!

And thank you for finally adding a prune() docstring.

**Comment by gbaned** [comment]
@frreiss can you please check build failures and resolve the conflict. Thanks!

**Comment by frreiss** [comment]
Conflicts resolved, starting a test build now.

**Comment by gbaned** [comment]
@frreiss could you please resolve the conflicts? Thanks!

**Comment by frreiss** [comment]
Conflicts resolved, rerunning regression tests now.

**Review by allenlavoie — DISMISSED** [review]

**Comment by gbaned** [comment]
@frreiss could you please resolve the conflicts? Thanks!

**Review by allenlavoie — APPROVED** [review]

**Comment by allenlavoie** [comment]
Running the submit with some minor tweaks to resolve yet another merge conflict; you shouldn't need to do anything else. Sorry about all of those.

**Comment by frreiss** [comment]
Thanks, @allenlavoie ! For what it's worth, my own test build of the branch after my manual merge just completed without errors.

**Pull request merged**
