### PR TITLE
[TFLite] Add int8 and int16x8 support for the ROUND operator

### PR DESCRIPTION
**Pull request by georgeedward2000**
Hi,

This PR adds int16x8 support for the ROUND operator in TensorFlow Lite.

There is a restriction on the inputs: they need to have the quantization scale <= 1.0f. This is necessary, along with the output quantization scale = 1.0f and zero-point = 0. These requirements support rounding of a value, converting it directly from a quantization mode to another.

Eddie

### CODE REVIEW

**Comment by gbaned** [comment]
@georgeedward2000  Can you please resolve conflicts? Thanks!

**Comment by georgeedward2000** [comment]
@gbaned I solved the conflicts. Thanks!

**Comment by gbaned** [comment]
@georgeedward2000  Can you please approve this PR by click on Approve and run button.  Thank you.

**Comment by teijeong** [comment]
Hi @georgeedward2000 ,

Thanks for PR and really sorry for delayed review. Adding @renjie-liu for more wisdom.

Can you explain what use cases are you trying to enable with this? To check the input scale during the quantization, I think there should be fixes in the quantizers (both legacy and the new MLIR one). The quantized kernel has limited use case, and not sure if we can allow the quantizer to quantize the round op by default.

If others agree, here are additional changes I suggest:

1. Add ` FixedOutputRangeInterface` and corresponding extra class declaration to `TFL_RoundOp` accordingly, and remove `NoQuantizableResult` trait. This has a downside that the range would be fixed to certain zero point. (e.g. -127~128, or 0~255).
2. You'd also need to come up with a logic that checks input's scale < 1.0f for round ops. Bad news is that the 16x8 quantization still relies on old quantizer, while int8 quantization works with the new quantizer by default, so you'd need to modify both.

**Comment by Tessil** [comment]
Hi @teijeong 

Even though a floating-point rounding operator isn't too costly in itself, it's problematic on hardware that doesn't have a a floating-point unit. Without quantized support for the rounding we have to either emulate the floating-point operations (dequantize, round, quantize) or transfer the data to a unit that natively supports floating-point. Having a quantized rounding would allow us to avoid the dequantize/quantize nodes and have a fully integer model for the ones that have a rounding operation.

Looking a bit more though, we could support input scales > 1.0 by setting the output scale to `output_scale = ceil(input_scale)` and keep the output zero-point to the same value as the input zero-point. We would lose some precision though for input scales > 1.0 (it should be a really rare occurrence for int16 inputs).

I checked the MLIR quantizer but there doesn't seem to be an easy way to do that currently. I will need to check a bit more how we could implement that but any insight is welcome. Note that we could start by only adding 8-bit supports and add 16-bit once the MLIR quantizer supports 16-bit.

**Comment by gbaned** [comment]
@teijeong Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@georgeedward2000 Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@georgeedward2000 Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
@georgeedward2000 Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
@georgeedward2000 Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
@georgeedward2000 Can you please resolve conflicts? Thank you!

**Comment by Tessil** [comment]
@gbaned Thanks, I resolved the conflicts

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @georgeedward2000 Can you please resolve conflicts? Thank you!

**Comment by psunn** [comment]
@gbaned thanks, I merged current HEAD of master into this branch.

**Comment by gbaned** [comment]
Hi @rascani Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rascani Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rascani Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rascani Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rascani Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rascani Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @rascani Can you please review this PR ? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @georgeedward2000 , Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @georgeedward2000 , Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @georgeedward2000 , Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @georgeedward2000 , Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @georgeedward2000 , Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @georgeedward2000 , Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @georgeedward2000 , Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @georgeedward2000 , Can you please resolve the conflicts? Thank you!

**Pull request closed without merging**
