### PR TITLE
MKL: Adding MKL-DNN pooling ops

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**

### CODE REVIEW

**Comment by yifeif** [comment]
Thanks for the PRs @mahmoud-abuzaina!
@andydavis1 I just assigned a bunch of the MKL PRs to you for review as it looks like you have been reviewing them :) Feel free to re-assign if needed. Thank you!

**Review by andydavis1 — APPROVED** [review]

**Comment by andydavis1** [comment]
@tensorflow-jenkins test this please.

**Comment by claynerobison** [comment]
What is the Ubuntu CC test that is preventing this PR from merging? It appears to be a Google Internal check. AFAICT none of these errors are related to the changes in this PR. Please merge.

**Comment by gunan** [comment]
Jenkins, test this please.

**Pull request merged**
