### PR TITLE
Fix to TensorFlow-Slim README

### PR DESCRIPTION
**Pull request by mbbrodie**
Same TF Slim README fix as earlier today. 
This is a resubmit with my email added to git config to pass your CLA check.

### CODE REVIEW

**Comment by mbbrodie** [comment]
I'm not sure why @googlebot can't verify my CLA (I am both the commit author and sender of the pull request). I set user.email in my git config before resubmitting this pull request. 
Please let me know if I need to update a config elsewhere.

**Comment by drpngx** [comment]
I think you have to say something like "I signed it!". It's somewhere in the instructions.

**Comment by mbbrodie** [comment]
Thanks @drpngx , I'll try that and see if it resolves the issue.

**Comment by mbbrodie** [comment]
I signed it!

**Comment by drpngx** [comment]
OK, I'm able to see the CLA with your gmail address. Not clear why the bot is confused.

**Review by drpngx — APPROVED** [review]

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Ignoring unrelated failure.

```
==================== Test output for //bazel_pip/tensorflow/python/kernel_tests:sparse_reshape_op_test:
2017-06-28 18:29:35.102138: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-28 18:29:35.102177: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-28 18:29:35.102184: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-28 18:29:35.102187: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-28 18:29:35.102190: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
F..................
======================================================================
FAIL: testFeedDenseReshapeSemantics (__main__.SparseReshapeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/bazel_pip/tensorflow/python/kernel_tests/sparse_reshape_op_test.runfiles/org_tensorflow/bazel_pip/tensorflow/python/kernel_tests/sparse_reshape_op_test.py", line 277, in testFeedDenseReshapeSemantics
    self.assertAllEqual(output_val.indices, new_indices)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/framework/test_util.py", line 725, in assertAllEqual
    np.testing.assert_array_equal(a, b)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/numpy/testing/utils.py", line 854, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 66.95152019231006%)
 x: array([[  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],...
 y: array([[  0,   0,   0,   2],
       [  0,   0,   0,   3],
       [  0,   0,   0,   9],...

----------------------------------------------------------------------
Ran 19 tests in 0.774s

FAILED (failures=1)
not equal where =  (array([     0,      1,      2, ..., 405178, 405178, 405178]), array([3, 3, 3, ..., 1, 2, 3]))
not equal lhs =  [  0   0   0 ...,   7  47 413]
not equal rhs =  [  2   3   9 ...,   9  59 448]
================================================================================
```

**Pull request merged**
