### PR TITLE
Added invocation and memory allocation checks

### PR DESCRIPTION
**Pull request by lamarrr**
Added checks for the Invoke and AllocateTensors. 
Also, consider using macros and more descriptive error logs. As in the TfLite C++ example for Desktop.

### CODE REVIEW

**Review by njeffrie — COMMENTED** [review]
Prefer using TF_LITE_MICRO_EXPECT_EQ(kTfLiteOk, interpreter.Invoke()) for test methods.  That way the test will fail quickly exactly where the issue is instead of just logging it.

Good catch and thanks for the PR improving our error checking.

**Comment by lamarrr** [comment]
> Prefer using TF_LITE_MICRO_EXPECT_EQ(kTfLiteOk, interpreter.Invoke()) for test methods. That way the test will fail quickly exactly where the issue is instead of just logging it.
> 
> Good catch and thanks for the PR improving our error checking.

Done
Thanks for the notes
https://github.com/tensorflow/tensorflow/pull/32917/files

**Review by njeffrie — APPROVED** [review]

**Comment by lamarrr** [comment]
Still yet to be merged, is there anyway I could help out resolving the build errors?

**Comment by rthadur** [comment]
@lamarrr let me try to pull this again, thanks for your patience.

**Comment by lamarrr** [comment]
> @lamarrr let me try to pull this again, thanks for your patience.

My pleasure actually.

**Pull request merged**
