### PR TITLE
Disable building the MatrixDiag and OneHot kernels for GPU on Windows.

### PR DESCRIPTION
**Pull request by mrry**
This is a temporary workaround for issue #6509, while the root cause of the runtime errors is under investigation.

### CODE REVIEW

**Comment by mrry** [comment]
@gunan I didn't manage to get the GPU PR build started... here's the error: http://ci.tensorflow.org/job/tf-pr-win-cmake-gpu/5/console

```
21:59:28 c:\tf_jenkins\home\workspace\tf-pr-win-cmake-gpu>call tensorflow/tools/ci_build/windows/gpu/cmake/run_py.bat 
21:59:28 'tensorflow' is not recognized as an internal or external command,
21:59:28 operable program or batch file.
21:59:28 
21:59:28 c:\tf_jenkins\home\workspace\tf-pr-win-cmake-gpu>exit 1 
```

Any ideas? I'll test it on my workstation tomorrow if not....

**Comment by gunan** [comment]
Got it to run now,
http://ci.tensorflow.org/job/tf-pr-win-cmake-gpu/7/
Apparently we need to provide PR number slightly differently.

**Comment by mrry** [comment]
Thanks for looking into that! Trying a new run, which should fix the failure: http://ci.tensorflow.org/job/tf-pr-win-cmake-gpu/8/

**Comment by mrry** [comment]
Once more without a silly typo this time: http://ci.tensorflow.org/job/tf-pr-win-cmake-gpu/9/

**Comment by mrry** [comment]
Well the build timed out before reaching the `one_hot_op_test.py`. :(

@gunan Any ideas for how to make it run longer? I also made a similar change to the MatrixDiag ops and `diag_op_test.py` has failed, but when I look in the workspace at the testing log, I don't see any errors.... Is it maybe failing because it's not using the GPU (e.g. because of some smarts put in to ensure that we're actually testing GPU implementations)?

**Comment by gunan** [comment]
ah, I have upped the timeout to 5 hours and restarted the build here:
http://ci.tensorflow.org/job/tf-pr-win-cmake-gpu/10/

**Comment by mrry** [comment]
Five hours ought to be enough for **any** test run! :P

**Comment by mrry** [comment]
@gunan Looks like `one_hot_op_test.py` and `trace_op_test.py` succeeded, but `diag_op_test.py` failed for mysterious reasons. 2 out of 3 isn't bad:

http://ci.tensorflow.org/job/tf-pr-win-cmake-gpu/10/console

Shall we merge this, since it should at least prevent ugly crashes?

**Comment by gunan** [comment]
Sure, sgtm.
The remaining issues are known to me so the tests are all OK.

**Pull request merged**
