### PR TITLE
Add missing line feed after totals in stat_summarizer

### PR DESCRIPTION
**Pull request by gar1t**

### CODE REVIEW

**Comment by gar1t** [comment]
I signed the contributors agreement as gar1t on GitHub.

**Comment by andrewharp** [comment]
@tensorflow-jenkins Test this please.

**Comment by gar1t** [comment]
Please advise as to how you'd like me to test this change. The test at tensorflow/contrib/stat_summarizer/python/stat_summarizer_test.py does not test line endings.

You are of course free to reject this PR for lack of explicit tests, but it's a trivial fix of an obvious bug.

**Comment by andrewharp** [comment]
@gar1t This seems fine, and the test failures are unrelated. Thanks for the PR!

**Pull request merged**
