### PR TITLE
Branch 192193752

### PR DESCRIPTION
**Pull request by qlzh727**
Manually merged following files, PTAL

	tensorflow/BUILD
	tensorflow/compiler/tests/BUILD
	tensorflow/compiler/xla/service/hlo_evaluator.cc
	tensorflow/contrib/autograph/operators/control_flow.py
	tensorflow/contrib/autograph/pyct/inspect_utils_test.py
	tensorflow/core/grappler/costs/op_level_cost_estimator.cc
	tensorflow/core/grappler/costs/op_level_cost_estimator.h
	tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
	tensorflow/core/kernels/cudnn_rnn_ops.cc
	tensorflow/python/keras/_impl/keras/applications/resnet50.py
	tensorflow/stream_executor/cuda/cuda_dnn.cc

### CODE REVIEW

**Review by yifeif — APPROVED** [review]

**Comment by qlzh727** [comment]
I think the py3 builds are already failing and broken by internal changes

**Comment by qlzh727** [comment]
Somehow the cla is not replying

**Comment by yifeif** [comment]
hmm I see, let's wait for a fix before we push then? We don't want to break the github master. clabot seems to do that when there are too many commits in a PR.

**Comment by qlzh727** [comment]
Understood. The build corp has pushed a change to disabled the test

**Comment by qlzh727** [comment]
created https://github.com/tensorflow/tensorflow/pull/18366, which includes few more changes. After doing several merge, I am doing efficiently :)

**Pull request closed without merging**
