### PR TITLE
[tosa] Fix Rescale shift attr data type

### PR DESCRIPTION
**Pull request by Tai78641**
Fixes required by Rescale shift attr data type changing to DenseI8ArrayAttr (from DenseI32ArrayAttr)

this needs to be coordinated with https://reviews.llvm.org/D157439 which changes tosa dialect's shift attribute types

Change-Id: I6f27d32b60847a296994687d8b6807065958f218

### CODE REVIEW

**Review by jpienaar — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @Tai78641 Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @Tai78641 Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar / @rsuderman Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar / @rsuderman Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar / @rsuderman Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar / @rsuderman Can you please review this PR ? Thank you!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by Tai78641** [comment]
FYI, the corresponding llvm PR, https://github.com/llvm/llvm-project/pull/71084, has been merged.

**Comment by gbaned** [comment]
Hi @Tai78641 Can you please resolve conflicts? Thank you!

**Comment by Tai78641** [comment]
resolved conflicts, and turned out the code changes have been merged with a slight casting diff.
force pushed, and PR is automatically closed because there is no code diff anymore in the PR

**Pull request closed without merging**
