### PR TITLE
Move bazel.rc to workspace root to support bazel-0.18.0

### PR DESCRIPTION
**Pull request by perfinion**
Bazel 0.17.0 will contain a change for which rc files it accepts.
https://github.com/bazelbuild/bazel/commit/ec83598cb6ee4136166bb562a24dc5dfa58921db
https://github.com/bazelbuild/bazel/issues/4502

Old bazel used to read %workspace%/tools/bazel.rc. New bazel will not
read that and instead will only read %workspace%/.bazelrc.

Signed-off-by: Jason Zaman <jason@perfinion.com>

Also updates bazel rules_closure to the latest and changes ./configure to echo a workspace relative path instead of full path in case the .bazelrc accidentally gets committed.

### CODE REVIEW

**Comment by perfinion** [comment]
There is a fatal error if the .bazelrc imports a .tf_configure.bazelrc that does not exist. I will open a bazel issue to make it nonfatal.

Changing the import to workspace-relative should make things a little better, but care will still need to be taken to ensure that the import is not accidentally committed to the file anyway.

```
$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
[bazel INFO src/main/cpp/option_processor.cc:203] Looked for a system bazelrc at path '/etc/bazel.bazelrc', but none was found.
[bazel INFO src/main/cpp/option_processor.cc:259] Looking for master bazelrcs in the following three paths: /home/jason/code/venv/tf/tensorflow/tools/bazel.rc, , 
[bazel INFO src/main/cpp/rc_file.cc:53] Parsing the RcFile /home/jason/code/venv/tf/tensorflow/.bazelrc
[bazel INFO src/main/cpp/rc_file.cc:53] Parsing the RcFile /home/jason/code/venv/tf/tensorflow/.tf_configure.bazelrc
[bazel FATAL src/main/cpp/blaze.cc:1271] Unexpected error reading .blazerc file '/home/jason/code/venv/tf/tensorflow/.tf_configure.bazelrc'
```

**Comment by perfinion** [comment]
Filed: https://github.com/bazelbuild/bazel/issues/5765

**Comment by case540** [comment]
Thanks for the PR! One question.

Why do we have to update io_bazel_rules_closure in WORKSPACE file for this change?

**Comment by perfinion** [comment]
@case540 oh, i guess we dont. I just saw it was out of date and updated it. Do you want me to remove that commit and make a separate PR for that?

**Comment by case540** [comment]
Yeah, please remove that change from this PR. Only create a separate PR if there is a very specific reason you need to update the dependency. Thanks again

**Comment by case540** [comment]
Sounds good to me.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by perfinion** [comment]
Rebased to quiet the bot. The rc file change was rolled back for bazel-0.17 and will be in 0.18 instead so gotta wait a little more so we get the new syntax right.

**Comment by meteorcloudy** [comment]
Any progress on this? We also need this change to fix TensorFlow failure with Bazel@HEAD on our CI.
Please see https://github.com/bazelbuild/bazel/issues/5945

**Comment by perfinion** [comment]
@meteorcloudy when will try-import hit a released version of Bazel? Once I update ./configure to use try-import it'll also need to have the minimum required version set higher too so I was thinking to do this only once bazel is released? Having people use bazel from git is a bunch more complicated.

**Comment by perfinion** [comment]
Or should I just do this change first using import then we change to try-import a bit later? (but not too long)

**Comment by meteorcloudy** [comment]
Hi @perfinion , thanks for working on this.
`try-import` should be available from `0.18.0`, since `0.17.0` is still not out yet, we might have to wait a few more weeks.
I think we can do this change first if you think it's ok.

**Comment by perfinion** [comment]
@meteorcloudy my main concern is if people accidentally commit anything weird in the /.bazelrc file. Everyone will just have to be careful to make sure the import line does not get committed to the file until we switch to try-import.

@martinwicke @yifeif Can we make one of the test bots double check the .bazelrc line to confirm no PR accidentally commits the "import %workspace%/.bazelrc" line? Or if the sanity stuff is in the tree somewhere i'll add a commit to update that together.

**Comment by perfinion** [comment]
@meteorcloudy I dont think so, //tensorflow/compiler/xla/tests:exhaustive_f32_elementwise_op_test_cpu has been failing a lot the last couple weeks. The MacOS and android failures I dont recall seeing last time I ran the tests maybe something broke in the mean time.

**Review by meteorcloudy — DISMISSED** [review]
Thanks!

**Comment by perfinion** [comment]
@case540 @meteorcloudy looks like the auto-import failed, you'll have to do it manually i think

**Comment by meteorcloudy** [comment]
@case540 Can you help importing this change?

**Comment by case540** [comment]
huh, no idea why import/copybara isnt running properly. Yeah, I can handle importing this.

**Comment by case540** [comment]
Didnt forget about this. Will hopefully have this PR pulled internally over the weekend. Just needs some internal update due to the way our migration scripts work (this PR removes an opensource-only file).

**Comment by perfinion** [comment]
@case540 thanks for the help! is there also something you can add (to the sanity bot maybe?) to flag if a PR accidentally commits the "import %workspace%/.bazelrc" line until we get the try-import stuff?
Otherwise it shouldn't be too long before 0.18.0 is out so we can just keep an eye on it carefully.

**Comment by perfinion** [comment]
@case540 Do you want me to rebase and fix the conflicts? or is it already in the queue?

**Comment by case540** [comment]
Yes, could you fix the conflicts please. I tried to merge this in this morning and hit a bunch of random errors.

**Comment by perfinion** [comment]
@case540 done :)

**Pull request merged**
