### PR TITLE
MKL: Fixes for concat and elementwise ops

### PR DESCRIPTION
**Pull request by agramesh1**
Fixes concat for Svd test cases and disable 4 elementwise ops to get SSG/VGG-16 model to work with MKL DNN. Disabled tanh due to differences between Tensorflow and DNN primitives.

### CODE REVIEW

**Comment by yifeif** [comment]
Thanks @agramesh1. Could you fix your cla?

**Review by andydavis1 — APPROVED** [review]

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by drpngx** [comment]
@agramesh1 Could you sign the CLA?

**Comment by agramesh1** [comment]
@drpngx I have CLA completed, but one of the other committer did not have one at the time of submission.  He obtained one since then, can you check again if @gzmkl has CLA?

**Comment by drpngx** [comment]
We don't have records for @gzmkl -- could you also sign the CLA?

**Comment by agramesh1** [comment]
@drpngx thanks. I have already signed CLA (Corporate level). I just checked the website https://cla.developers.google.com/clas it shows CLA.

**Comment by agramesh1** [comment]
I signed it!

**Comment by agramesh1** [comment]
@drpngx  It looks like the CLAs are fine now. Thanks.

**Comment by drpngx** [comment]
Thanks!

**Pull request merged**
