### PR TITLE
Use movi NEON instruction to zero out registers

### PR DESCRIPTION
**Pull request by lgeiger**
Currently `dup` is used to zero our NEON registers in the packing and AArch64 kernel code. According to the [Cortex A72 optimization guide](https://developer.arm.com/documentation/uan0016/a/) which is used in the Raspberry PI 4, `dup` has an execution latency of 8 cycles and a throughput of 1 when copying from a general purpose register to a NEON register.

This PR changes the code to use `movi` which has a latency of 3 cycles and a throughput of 2. This is also used in [LLVM for zeroing out registers](https://github.com/llvm/llvm-project/blob/master/llvm/test/CodeGen/AArch64/arm64-zero-cycle-zeroing.ll), but please let me know if I am missing something here.

### CODE REVIEW

**Comment by terryheo** [comment]
@abattery it looks fine to me. What do you think?

**Comment by abattery** [comment]
Thank you for your contribution. 

According to the optimization guide, the dup instruction has the same latency and throughput with the movi instruction.

It would be better to keep the current code as is.

Please see the page 30 of the guide pdf file .


| Instruction Group        | AArch64 Instructions | Exec latency | Execution Throughput | Utilized Pipelines | Notes |
|--------------------------|----------------------|--------------|----------------------|--------------------|-------|
| ASIMD duplicate, element | DUP                  | 3            | 2                    | F0/F1              |       |

**Comment by lgeiger** [comment]
Thanks a lot for the fast response.

> According to the optimization guide, the dup instruction has the same latency and throughput with the movi instruction.

I think this is only true for the case when both source registers are already NEON vector registers.
Since `wzr` is a general purpose register I think the numbers on the bottom of page 29 need to be used:

Instruction Group | AArch64 Instructions | Exec latency | Execution Throughput | Utilized Pipelines
-- | -- | -- | -- | --
ASIMD duplicate, gen reg | DUP | 8 | 1 | L, F0/F1

But please let me know if I am missing something.

**Comment by abattery** [comment]
Thanks @lgeiger for correcting me on this. LLVM community also have a similar optimization like this one in https://reviews.llvm.org/D41515

**Review by abattery — APPROVED** [review]

**Comment by lgeiger** [comment]
> LLVM community also has a similar optimization like this one in https://reviews.llvm.org/D41515

Great find!

Thanks for the fast review.

**Pull request merged**
