### PR TITLE
Improve NumPy to Dataset performance with vectorized shuffling.

### PR DESCRIPTION
**Pull request by goldiegadde**
PiperOrigin-RevId: 263611727

### CODE REVIEW

**Comment by omalleyt12** [comment]
There’s a follow up fix to this bc this was causing a recursion error in some cases, should we wait for that? Or submit this and then follow up?

**Comment by qlzh727** [comment]
yea, Please cherrypick the followup as well

**Comment by goldiegadde** [comment]
> yea, Please cherrypick the followup as well

Done.

**Review by omalleyt12 — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
