### PR TITLE
Branch 142140440

### PR DESCRIPTION
**Pull request by martinwicke**

### CODE REVIEW

**Comment by martinwicke** [comment]
Small number of conflicts in the merge.

**Comment by martinwicke** [comment]
Jenkins, test this please?

**Comment by martinwicke** [comment]
aborted? please don't abort...

**Review by jart — APPROVED** [review]
I'm Justine Tunney and I approve of this pull request.

**Comment by martinwicke** [comment]
@mrry, can I get your help on the cmake failure? I suspect it's mostly about a new legacy_seq2seq module that's not properly included. But the conv test failure is different.

**Comment by mrry** [comment]
Looks like a missing Python module in tf.contrib :(. Adding the following lines [here](https://github.com/martinwicke/tensorflow/blob/0daa5a0a2ce3c695b94a7008b191780343010bdc/tensorflow/contrib/cmake/tf_python.cmake#L313) should get you there:

```
add_python_module("tensorflow/contrib/legacy_seq2seq/python")
add_python_module("tensorflow/contrib/legacy_seq2seq/python/ops")
```

**Comment by martinwicke** [comment]
GPU failure looks like a flake.

**Pull request merged**
