### PR TITLE
[Windows/CMake] Add tensorflow.models.* to the PIP package.

### LINKED ISSUE #5953: Windows 'models' directory
I'm following through the tutorial and it seems that the 'tensorflow/models/' directory is missing from the TensorFlow 0.12.0 RC0 build for Windows - at least when downloaded using pip.

I installed TensorFlow using `pip3 install --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-0.12.0rc0-cp35-cp35m-win_amd64.whl`. The initial test of TensorFlow ran fine.

Additionally running `python3 -m tensorflow.models.image.mnist.convolutional` produces the follwing error:

	I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll locally
	I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll locally
	I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll locally
	I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll locally
	I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll locally
	C:\Program Files\Python35\python3.exe: Error while finding spec for 'tensorflow.models.image.mnist.convolutional' (ImportError: No module named 'tensorflow.models')

I'm new to TensorFlow so please correct me if the Models module is not supposed to be packaged with the pip download.

### LINKED ISSUE #6024: where is Tensorflow directory on Windows ?
I have installed and verified Tensorflow installation on Windows, that's great. But how I am supposed to to stuff like `pyhthon3 cifar10_train.py`? ran that command got error no such file or directory. Also run the whole code in cifar10.py and got error there is no module named tensorflow.modles.

`ImportError was unhandled by user code
Message: No module named 'tensorflow.models'`

### PR DESCRIPTION
**Pull request by mrry**
Also runs the few tests in there, and builds the word2vec kernels.

Fixes #6024. Fixes #5953.

### CODE REVIEW

**Comment by mrry** [comment]
It looks like a few users are having difficulty running our tutorials on Windows without these files - and I don't think they'd work standalone - so I propose we add them to r0.12. We'll remove them again when they move to the models repo (cc @nealwu), so we probably shouldn't backport this to master. Does that sound alright?

**Comment by nealwu** [comment]
Sounds good.

**Comment by gunan** [comment]
sure, but not with a failing test :)
```
180/182 Test #180: C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/models/embedding/word2vec_test.py ...............................***Failed
```

Looks like the root cause is:
`tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'Skipgram'`

**Comment by nealwu** [comment]
I've seen that op before. I believe it's related to word2vec.

**Comment by mrry** [comment]
That'll teach me not to run all the tests before pushing :).

**Review by gunan — APPROVED** [review]
:) It is easier to have jenkins run the tests for you, so I understand.

**Pull request merged**
