### PR TITLE
Added batch as formatting parameter during ModelCheckpoint callback

### LINKED ISSUE #38668: In ModelCheckpoint, filepath is not accepting batch as formatting parameter.
In `ModelCheckpoint` callback, there is a parameter given named `save_freq` to save model. If `save_freq` is set to `epoch`, it will save model at the end of every epoch. (This works perfectly fine). But when `save_freq` is set to an integer let's say `N`, then the callback should save the model after `N` batches in every epoch. But the problem here is the callback doesn't accept the filepath as `file.batch{batch:02d}epoch{epoch:02d}.h5` and raises error as `batch` is invalid key.  
The problem in the code that I have noticed is that the `_save_model` function has access to `epoch` but it doesn't have access to `batch`. And that's why `_get_file_path()` has access to `epoch` but not `batch`.  The functionality should be changed little bit. I am raising PR to add access to `batch` param in both `_save_model` and `_get_file_path` variable.
I noticed this error in tf code during the work on my PR [#1702](https://github.com/tensorflow/addons/pull/1702) in tensorflow/addons.  

cc @gabrieldemarmiesse.

### PR DESCRIPTION
**Pull request by ashutosh1919**
Fixes #38668 . It is to complete the work done in two of my previous stale PRs #38669 and [#1702](https://github.com/tensorflow/addons/pull/1702).

cc @mihaimaruseac , please review.

### CODE REVIEW

**Comment by ashutosh1919** [comment]
cc @gbaned , @mihaimaruseac , @rchao, Any updates on this PR?

**Review by mihaimaruseac — APPROVED** [review]

**Comment by ashutosh1919** [comment]
@mihaimaruseac , @gbaned - Why is it failing internally? Previously also the PR for same issue I closed because of this. There was no bazel error but it failed internally. 

Can you please paste the stack trace or error if available?

**Comment by gbaned** [comment]
Here are the internal errors, @ashutosh1919 can you please verify ?  Thanks!

Traceback (most recent call last):
  File "/py/absl/testing/parameterized.py", line 316, in bound_param_test
    return test_method(self, *testcase_params)
  File "/tensorflow/python/keras/keras_parameterized.py", line 285, in decorated
    _test_functional_model_type(f, self, *args, **kwargs)
  File "/tensorflow/python/keras/keras_parameterized.py", line 299, in _test_functional_model_type
    f(test_or_class, *args, **kwargs)
  File "/tensorflow/python/keras/callbacks_test.py", line 720, in test_ModelCheckpoint
    verbose=1)
  File "/tensorflow/python/keras/engine/training_v1.py", line 814, in fit
    use_multiprocessing=use_multiprocessing)
  File "/tensorflow/python/keras/engine/training_arrays_v1.py", line 661, in fit
    steps_name='steps_per_epoch')
  File "/tensorflow/python/keras/engine/training_arrays_v1.py", line 391, in model_iteration
    callbacks._call_batch_hook(mode, 'end', batch_index, batch_logs)
  File "/tensorflow/python/keras/callbacks.py", line 316, in _call_batch_hook
    self._call_batch_end_hook(mode, batch, logs)
  File "/tensorflow/python/keras/callbacks.py", line 336, in _call_batch_end_hook
    self._call_batch_hook_helper(hook_name, batch, logs)
  File "/tensorflow/python/keras/callbacks.py", line 374, in _call_batch_hook_helper
    hook(batch, logs)
  File "/tensorflow/python/keras/callbacks.py", line 1383, in on_train_batch_end
    self._save_model(epoch=self._current_epoch, batch=batch, logs=logs)
  File "/tensorflow/python/keras/callbacks.py", line 1427, in _save_model
    filepath = self._get_file_path(epoch, batch, logs)
  File "/tensorflow/python/keras/callbacks.py", line 1485, in _get_file_path
    epoch=epoch + 1, batch=batch + 1, **logs)
TypeError: format() got multiple values for keyword argument 'batch'

**Comment by ashutosh1919** [comment]
@mihaimaruseac , Can you please review the fix? I resolved the error.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
@qlzh727 should we move this to Keras?

**Comment by qlzh727** [comment]
The PR is merged to keras-team/keras as https://github.com/keras-team/keras/commit/c567184255468a1d0ca0b6b284e20cdeb7561574. Closing this now.

**Pull request closed without merging**
