### PR TITLE
[OpenCL] Fixes core_rnn_cell_tests

### PR DESCRIPTION
**Pull request by lukeiwanski**
SYCL uses the same implementation as the CPU one for BiasAdd

### CODE REVIEW

**Comment by rmlarsen** [comment]
@tensorflow-jenkins

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Review by rmlarsen — APPROVED** [review]

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (25/25 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:58752 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1demv0-0005fw-1m
	for mazecreator@mazecreator.com; Mon, 07 Aug 2017 13:38:52 -0500
Date: Mon, 07 Aug 2017 11:49:15 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1502131755;
	bh=P/h8w7tbR/8xwMQxV3PmreV0jc3cU8w7K0WqUjoKlSc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=kaPWFBj6xoS9neuDkKe90PE+lv6WRtDjBkXm4di+aKN/ivZJiOWIzaF4/hcCxOzps
	 MNrm6aB+d7ItmAeeFFcLmclrvpQBkfZeBbq6XC0CEOvZpvSGsoDzXMPQrquseLjsgR
	 q10YGjvMEGKFtKVCAVyRuGIjj962mcGK2fvZ1UZg=

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (26/25 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:4115)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-e6d9-mazecreator=mazecreator.com@sgmail.github.com>)
	id 1demv6-0005gJ-NO
	for mazecreator@mazecreator.com; Mon, 07 Aug 2017 13:38:58 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=VDGbuoU2FrZAPnRZNFZlApIA8nM=; b=Nwg24bEWzAUJGGHf
	T3eTFneGfGwHOtn3thOI9bSs7s3gNGBS6Sd6JawhYneVxm9nSb83DDLCiIG8Bj47
	6VyU5GrZU0kNVdcgdn4dljPD4uvUYVBimyjRm35/T3orxhpfiSEmOMKguga1NMom
	1eCTcwtIkzPPTPMHe7hNrKwbMlU=
Received: by filter0470p1mdw1.sendgrid.net with SMTP id filter0470p1mdw1-31435-5988B630-7C
        2017-08-07 18:49:20.806939127 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id 9aYVFB0gQ1KlKBhANoMEBg
	for <mazecreator@mazecreator.com>; Mon, 07 Aug 2017 18:49:20.795 +0000 (UTC)
Date: Mon, 07 Aug 2017 18:49:21 +0000 (UTC)

**Comment by rmlarsen** [comment]
@lukeiwanski FYI: I approved this prematurely. We don't need to add the DeviceName template function. the proper way to get the device name is through the context->device_type() method. I'll revert that part.

**Comment by rmlarsen** [comment]
@lukeiwanski I should say context->device_type().type_string() or context->device()->attributes().name()  :-)

**Comment by lukeiwanski** [comment]
@rmlarsen Would you like me to create PR for that fix ?

**Pull request merged**
