### PR TITLE
Add Multi-Dimentional LSTM

### PR DESCRIPTION
**Pull request by johnsmithm**
implementation of Multi-Dimentional LSTM described in https://www.cs.toronto.edu/~graves/nips_2008.pdf

### CODE REVIEW

**Comment by johnsmithm** [comment]
I signed it!

**Comment by ebrevdo** [comment]
Hi, what's the difference between this and ndlstm?

https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/contrib/ndlstm/python/__init__.py

**Comment by johnsmithm** [comment]
It splits images in blocks(rectangles). Lstm cell get states from both neighbors at once.  ndlstm just run bidirectional rnn on lines and columns.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by johnsmithm** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
This failed the sanity test, please try to build on your end.

```
ERROR: /workspace/tensorflow/contrib/mdlstm/BUILD:12:1: no such target '//tensorflow/contrib:rnn_py': target 'rnn_py' not declared in package 'tensorflow/contrib' defined by /workspace/tensorflow/contrib/BUILD and referenced by '//tensorflow/contrib/mdlstm:mdlstm'.
ERROR: /workspace/tensorflow/contrib/mdlstm/BUILD:12:1: no such package 'tensorflow/python/framework': BUILD file not found on package path and referenced by '//tensorflow/contrib/mdlstm:mdlstm'.
ERROR: Analysis of target '//tensorflow/contrib/mdlstm:mdlstm' failed; build aborted.
INFO: Elapsed time: 7.597s
```

**Comment by johnsmithm** [comment]
can someone help me with including dependencies in the BUILD file?

**Comment by drpngx** [comment]
It's `//tensorflow/contrib/rnn:rnn_py` and `//tensorflow/python/core:framework` respectively.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by johnsmithm** [comment]
what does it mean?
`[Set GitHub commit status (universal)] PENDING on repos [] (sha:905bfc7) with context:tensorflow-pull-requests-cpu
Unable to get pull request builder trigger!!
Setting status of 954d61d3002774b373b2f698c93c27bf8d4d5ab4 to FAILURE with url https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/5532/ and message: 'FAILURE`

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
The sanity check fails because of formatting errors in BUILD files and Python code:

==== Summary of sanity check results ====
1. do_pylint PYTHON2: Python 2 pylint
  FAIL
2. do_pylint PYTHON3: Python 3 pylint
  FAIL
3. do_buildifier: buildifier check
  FAIL

https://ci.tensorflow.org/job/tensorflow-pull-requests-sanity/5358/consoleFull

**Comment by johnsmithm** [comment]
thanks for information, i will fix the build as sugested and the pylint errors!

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@johnsmithm It looks like there are a few more errors to resolve. 

https://ci.tensorflow.org/job/tensorflow-pull-requests-multijob/6413/

**Comment by johnsmithm** [comment]
i do not know how to add dependencies to pip_packages:
Missing dependency: //tensorflow/contrib/mdlstm:mdlstm 
also buildifier failed, and i do not know what to change.
is there a documentation how to write BUILD file?

**Comment by rmlarsen** [comment]
@johnsmithm You should be able to add a dependence on //tensorflow/contrib/mdlstm:mdlstm to what ever target needs it in your new code.

You can format the BUILD file with the buildifier tool. There is a script to install it here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_buildifier.sh

It might also add the missing dependency for you, but make sure it doesn't make unintended changes to other targets.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@drpngx @ebrevdo can you help @johnsmithm fixing the missing pip dependency? Thanks.

https://ci.tensorflow.org/job/tensorflow-pull-requests-sanity/5855/console

**Comment by drpngx** [comment]
I would try to add the dependency here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/BUILD#L155
Does this build under windows? If so, try this too:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/BUILD#L88

**Comment by drpngx** [comment]
@johnsmithm Any luck with this?

**Comment by sb2nov** [comment]
@johnsmithm ping

**Comment by johnsmithm** [comment]
i still don't know how to sort the dependencies, what is the correct order.

**Comment by terrytangyuan** [comment]
You can use buildifier to automatically format your BUILD file. https://github.com/bazelbuild/buildtools#buildifier

**Review by ebrevdo — CHANGES_REQUESTED** [review]
Can you rewrite as a single core Layer object, and implement build and call instead of __call__?  Also hide the non Layer implementation (multi_dimensional_rnn) and add unit tests with unknown batch size (feed inputs via feed_dict).

To ensure the tf team can maintain this code, we need it to be as close to the final goal of wrapping complex behaviors in layers as possible.

**Comment by martinwicke** [comment]
I'll close this PR due to inactivity. If you continue working on it, I'm happy to reopen it, or you can just start a new one.

**Pull request closed without merging**
