### PR TITLE
[Grappler] Fix comparison between node name and input in UpdateConsumers

### PR DESCRIPTION
**Pull request by xinan-jiang**
This is a PR from JIZHI, the AI platform in Tencent.

The input name is always "node:port", it could not compare to the node name directly.  @ezhulenev

### CODE REVIEW

**Comment by smilingday** [comment]
@ezhulenev Could you help take a look? Thanks!

**Review by ezhulenev — APPROVED** [review]
Sorry for the wait, missed email from github.

**Comment by gbaned** [comment]
@xinan-jiang Could you please address Ubuntu Sanity errors? Thanks!

**Comment by xinan-jiang** [comment]
I can not see the log@gbaned
I think this PR will not break sanity case@ezhulenev

**Pull request merged**
