### PR TITLE
Simplify shape inference in Keras resize_images

### LINKED ISSUE #25086: tf.keras.layers.UpSampling2D - static shapes for ResizeNearestNeighbor are NOT inferred in GraphDef (with `add_shapes=True`)
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **n/a**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **1.12**
- Python version: **3.6**
- Bazel version (if compiling from source): **n/a**
- GCC/Compiler version (if compiling from source): **n/a**
- CUDA/cuDNN version: **CUDA 9 / cuDNN 7**
- GPU model and memory:  **n/a**

### Premise:
Assume we're given a `GraphDef` that was serialized as `graph.as_graph_def()`. To infer static shapes of every node in this graph and store them as `_output_shapes` attr, TensorFlow [provides](https://www.tensorflow.org/api_docs/python/tf/Graph#as_graph_def) the option`add_shapes=True`.

### Issue:
Let's consider the two APIs that internally use `ResizeNearestNeighbor` kernel:
- `tf.image.resize_nearest_neighbor`
- `tf.keras.layers.UpSampling2D`

The static shape attr (`_output_shapes`) for `ResizeNearestNeighbor` node is correctly inferred when created with `tf.image.resize_nearest_neighbor` API. Yet using `tf.keras.layers.UpSampling2D` results in incomplete shape information for height and width dims.

### Minimal examples:

**Using `tf.image.resize_nearest_neighbor` static shapes are inferred correctly:**
```python3
import tensorflow as tf

# Prepare `GraphDef`
tf.reset_default_graph()
input = tf.placeholder(tf.float32, shape=[None, 26, 128, 256])
output = tf.image.resize_nearest_neighbor(input, (52, 256))
graph_def = tf.get_default_graph().as_graph_def()

# Import `GraphDef` and restore static shapes
tf.reset_default_graph()
with tf.Session(graph=tf.Graph()) as sess:
    tf.import_graph_def(graph_def, name='')
    output_graph_def = tf.get_default_graph().as_graph_def(add_shapes=True)

# Check shapes
for node in output_graph_def.node:
    if node.op == 'ResizeNearestNeighbor':
        print(node.attr["_output_shapes"])
```
**Output**
```
list {
  shape {
    dim {
      size: -1
    }
    dim {
      size: 52
    }
    dim {
      size: 256
    }
    dim {
      size: 256
    }
  }
}
```

**Using `tf.keras.layers.UpSampling2D` static shapes are NOT inferred for H, W:**
```python3
import tensorflow as tf

# Prepare `GraphDef`
tf.reset_default_graph()
input = tf.placeholder(tf.float32, shape=[None, 26, 128, 256])
output = tf.keras.layers.UpSampling2D((2, 2))(input)
graph_def = tf.get_default_graph().as_graph_def()

# Import `GraphDef` and restore static shapes
tf.reset_default_graph()
with tf.Session(graph=tf.Graph()) as sess:
    tf.import_graph_def(graph_def, name='')
    output_graph_def = tf.get_default_graph().as_graph_def(add_shapes=True)

# Check shapes
for node in output_graph_def.node:
    if node.op == 'ResizeNearestNeighbor':
        print(node.attr["_output_shapes"])
```
**Output**
```
list {
  shape {
    dim {
      size: -1
    }
    dim {
      size: -1
    }
    dim {
      size: -1
    }
    dim {
      size: 256
    }
  }
}
```

### PR DESCRIPTION
**Pull request by lgeiger**
This PR simplifies shape inference of `keras.backend.resize_images`, since the shape of the output tensor is already correctly set in `image_ops.resize_images_v2`:
https://github.com/tensorflow/tensorflow/blob/0921a80d56107e19c5c1cebf9500a683d7d41b10/tensorflow/python/ops/image_ops_impl.py#L1390

This also removes the need for the `tf.shape` op in cases where the spatial shape of the input tensor is fully defined which fixes #25086.

### CODE REVIEW

**Comment by mattdangerw** [comment]
Please add a unit test!

**Comment by lgeiger** [comment]
@mattdangerw the correct output shape computations should already be covered in the following test cases
https://github.com/tensorflow/tensorflow/blob/c4d6c698022f1527fc786ad498f5b1866694ca33/tensorflow/python/keras/backend_test.py#L599-L615

But let me know if there is still a case I am missing.

**Comment by mattdangerw** [comment]
Look like we are missing a case for a partially defined shape to me. Something that exercises the else block in your change.

**Comment by lgeiger** [comment]
@mattdangerw Sorry about that, I added a test case for dynamic input shapes.

**Review by mattdangerw — APPROVED** [review]
Thanks! lgtm

**Pull request merged**
