### PR TITLE
order quantized table by value for ease of reading

### PR DESCRIPTION
**Pull request by Atlas7**

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by petewarden — APPROVED** [review]
Looks good, thanks for this clarification!

**Comment by martinwicke** [comment]
@Atlas7 we are not taking PRs against release branches -- can you reopen this PR against master?

**Pull request closed without merging**
