### PR TITLE
Fix two linter warnings

### PR DESCRIPTION
**Pull request by frreiss**
I've been seeing the following linter warnings in my test builds for a few days now:
```
FAIL: Found 2 non-whitelited pylint errors:
tensorflow/python/platform/googletest.py:28: [W0622(redefined-builtin), ] Redefining built-in 'xrange'

tensorflow/examples/saved_model/integration_tests/integration_scripts.py:64: [E1111(assignment-from-no-return), MaybeRunScriptInstead] Assigning to function call which doesn't return
```

This PR fixes the two issues that cause these warnings.

### CODE REVIEW

**Comment by annarev** [comment]
I wonder if `sys.exit` in `integration_scripts.py` is still needed (may be with a constant exit code).
@andresusanopinto Andre, can you take a look?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by frreiss** [comment]
Replaced the fix for the second warning with a hopefully less-controversial version.

By the way, these linter errors are still showing up on the master branch. To replicate the problem, run:
```
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
tensorflow/tools/ci_build/ci_build.sh CPU tensorflow/tools/ci_build/ci_sanity.sh
```
You'll see the following output:
```
[...]
=== Sanity check step 2 of 14: do_pylint PYTHON2 (Python 2 pylint) ===
[...]
FAIL: Found 2 non-whitelited pylint errors:
tensorflow/examples/saved_model/integration_tests/integration_scripts.py:64: [E1111(assignment-from-no-return), MaybeRunScriptInstead] Assigning to function call which doesn't return

tensorflow/python/platform/googletest.py:28: [W0622(redefined-builtin), ] Redefining built-in 'xrange'
```

**Review by annarev — APPROVED** [review]
Thank you for the fixes and sorry for delay.

**Comment by frreiss** [comment]
Any idea what is causing those two failed checks (Windows Bazel GPU and import/copybara)? I don't have any visibility into the build results.

**Pull request merged**
