### PR TITLE
Use typedef struct

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
This misses the declaration specs from `TFL_CAPI_EXPORT`. Also, why should we switch to `typedef`?

**Comment by mattn** [comment]
struct is not symbol. it should be tagged for functions or global variables. `__declspec(dllexport)` can be used for C++ classes. But this is plain struct. This header file is used from C. So `struct Foo` must not be written without `struct`. typedef is always required for struct, enum for C.

**Comment by mihaimaruseac** [comment]
I thought it got used as `struct Foo` everywhere else in the code, but seems not, so :+1: for the PR.

Though, can you please make it `typedef struct Foo {...} Foo;` instead of `typedef struct { ...} Foo;`?

**Comment by mattn** [comment]
c_api_types.h defines `typedef struct {} Foo` already.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
