### PR TITLE
Fixing bug in Adadelta implementation

### PR DESCRIPTION
**Pull request by luheng**
The updated accum vector should be computed as:
\rho * accum + (1.0 - \rho) * grad^2,
according to Algorithm1 in Zeiler 2012 (https://arxiv.org/pdf/1212.5701v1.pdf).

### CODE REVIEW

**Comment by luheng** [comment]
I signed it!

**Comment by vrv** [comment]
Thanks!  I suspect you'll have to update the tests in adadelta_test.py, but I'll kick off the test anyway.

@tensorflow-jenkins test this please

**Comment by luheng** [comment]
Thanks! Weirdly the updates in adadelta_test.py are implemented correctly. Do I still need to update the tests?

**Comment by vrv** [comment]
Do you know why the tests were passing before and after?  Should we come up with a better test that would have failed before and passes with your change?

**Comment by luheng** [comment]
I updated the precision in adadelta_test.py so it will be able to test the difference.

**Comment by vrv** [comment]
That's great!  Gives us more confidence it's doing the right thing now.

@tensorflow-jenkins test this please

**Review by vrv — APPROVED** [review]

**Comment by caisq** [comment]
PR merged. Thanks, @luheng

**Pull request merged**
