### PR TITLE
added shortcuts to access tensorshape dims and ndims

### PR DESCRIPTION
**Pull request by chemelnucfin**
for less typing.  
**len** seems to cause problems though, will look into it.

### CODE REVIEW

**Comment by girving** [comment]
@mrry: Was there some plan to change `get_shape()` to be less verbose as well?

**Comment by mrry** [comment]
Yes, but it depends on fixing all of the legacy code that uses the vestigial `Tensor.shape` property internally. Assuming this eventually happens, I'd be inclined to add `Tensor.shape` as an alias for `Tensor.get_shape()`, instead of accepting this PR.

**Comment by girving** [comment]
@mrry: What does the vestigial thing do?  I can't find it in the code.

**Comment by chemelnucfin** [comment]
@mrry Are there any reasons to have convenience accessors on C++ but not python?

**Comment by girving** [comment]
It does seem like once we rename `get_shape()` to `shape`, these aliases fit naturally into the picture.

**Comment by vrv** [comment]
Ok, looks like we have some internal work to do instead.  Thanks!

**Comment by vrv** [comment]
(We can revive this later when it becomes possible to get to our end goal)

**Pull request closed without merging**
