### PR TITLE
[ROCM] enable self_adjoint_eig op (#1511)

### PR DESCRIPTION
**Pull request by micmelesse**
This pr enables self_adjoint_eig_v2_op on rocm.

### CODE REVIEW

**Comment by stevenireeves** [comment]
@gbaned can you rescan the CLA? I made sure my amd email was associated with the CLA.

**Comment by gbaned** [comment]
> @gbaned can you rescan the CLA? I made sure my amd email was associated with the CLA.

@stevenireeves  I can see you have signed CLA. Thank you.

**Comment by gbaned** [comment]
@micmelesse Can you please sign CLA. Thanks!

**Comment by micmelesse** [comment]
@gbaned It says that I have signed it. I added my amd email just in case. Can you rescan it?

**Comment by stevenireeves** [comment]
@gbaned The CLA still appears to be failing on my email, although I updated the CLA to have both my personal and my work email. Is there a way fix this issue?

**Review by akuegel — APPROVED** [review]

**Comment by gbaned** [comment]
@micmelesse I have checked, still it shows you have not signed CLA.  Thank you!

**Comment by micmelesse** [comment]
@gbaned I updated my username from a link to github to just the username. Can you try to rerun the cla again?

**Comment by stevenireeves** [comment]
@gbaned  both @micmelesse  and I have double checked our CLA and made sure that everything is as needed. On the details it shows that Michael's CLA is correct, but mine is not. I added my work email to the CLA associated with my github account. I think the CLA just needs to be rerun. Thanks!

**Comment by gbaned** [comment]
> @gbaned both @micmelesse and I have double checked our CLA and made sure that everything is as needed. On the details it shows that Michael's CLA is correct, but mine is not. I added my work email to the CLA associated with my github account. I think the CLA just needs to be rerun. Thanks!

@stevenireeves  Now, CLA looks good for both of you. Thank you.

**Comment by stevenireeves** [comment]
@gbaned thanks!

**Comment by akuegel** [comment]
> > @gbaned both @micmelesse and I have double checked our CLA and made sure that everything is as needed. On the details it shows that Michael's CLA is correct, but mine is not. I added my work email to the CLA associated with my github account. I think the CLA just needs to be rerun. Thanks!
> 
> @stevenireeves Now, CLA looks good for both of you. Thank you.

If the question comes up again how to trigger rerunning the CLA check, I did it by clicking the Details link on the right of the cla/google line, and on that page there was a button Re-run all checks.

**Comment by akuegel** [comment]
Seems there is an issue with the AMD ROCm Community CI Build, can you please take a look?

**Comment by stevenireeves** [comment]
@akuegel The Community CI build uses rocm4.3.1, the features included in this PR were introduced in rocm4.5. @micmelesse will provide a solution to this.

**Comment by micmelesse** [comment]
The changes in this pr will be part of an upcoming pr from @stevenireeves that integrates hipsolver.

**Pull request closed without merging**
