### PR TITLE
Change `int` to `uint` or `size_t` where applicable

### PR DESCRIPTION
**Pull request by olicht**
Change `int` to `uint` or `size_t` where applicable. 
Based on compiler warnings & common sense. 

Note: there is **a lot** more to be done on this subject.

### CODE REVIEW

**Comment by olicht** [comment]
@skye, any news?

**Comment by skye** [comment]
Hi sorry missed this somehow, thanks for the ping. I'm running tests to make sure this doesn't cause any errors with our prechecks.

**Review by skye — APPROVED** [review]
I can't tell if the tests ran, but otherwise LGTM pending tests (I just wanna make sure e.g. we have uint defined on all platforms).

**Comment by rmlarsen** [comment]
@olicht please take a look at the build errors.

**Comment by hgadig** [comment]
@olicht  Please rebase to resolve the branch conflicts.

**Comment by rthadur** [comment]
closing this PR due to lack of activity.

**Pull request closed without merging**
