### PR TITLE
Support GPU fusion of matmal+bias+(activation)

### PR DESCRIPTION
**Pull request by kaixih**
This PR enables the remapping optimization for fusion patterns of matmal+bias and matmul+bias+relu on GPUs.

This optimization needs to be turned on by `TF_USE_CUBLASLT`.

cc. @nluehr

### CODE REVIEW

**Review by ezhulenev — APPROVED** [review]

**Comment by akuegel** [comment]
Can you please compile with warnings enabled, and fix those? This is blocking the merge of this PR.

Sample warnings:

[tensorflow/core/kernels/matmul_op_fused.cc:318](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/core/kernels/matmul_op_fused.cc?l=318&ws=tap-prod-presubmit/182490833&snapshot=2):10: error: unused variable 'allow_tf32' [-Werror,-Wunused-variable]
    bool allow_tf32 = tensor_float_32_execution_enabled();

[tensorflow/core/kernels/matmul_op_fused.cc:330](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/core/kernels/matmul_op_fused.cc?l=330&ws=tap-prod-presubmit/182490833&snapshot=2):77: error: non-constant-expression cannot be narrowed from type 'tensorflow::uint64' (aka 'unsigned long') to 'int64_t' (aka 'long') in initializer list [-Wc++11-narrowing]
    se::blas::MatrixDescriptor lhs_matrix = {b_ptr, trans[trans_b ? 1 : 0], n,

(there are more)

**Comment by kaixih** [comment]
@akuegel  Can you advise how to enable the warning message? I've tried to add a `copt` to the related `tf_kernel_library()` call for "matmul_op" but I didn't see the warnings. Or if we could have the access to the log that you mentioned. Thanks.

**Comment by kaixih** [comment]
I think I figured out how to print out all the warning messages. Pushed new commits to fix the warnings. PTAL. @akuegel

**Review by akuegel — APPROVED** [review]

**Comment by rahulbatra85** [comment]
@kaixih Can you please explain why you removed a bunch of  TENSORFLOW_USE_ROCM #defines?

**Comment by kaixih** [comment]
IIRC, the `AMD ROCm -- Community CI Build` will fail if those TENSORFLOW_USE_ROCM is there. It usually was some dependence issue but I didn't dive deep into the issue. @rahulbatra85

**Comment by rahulbatra85** [comment]
@kaixih ok, thanks!

**Pull request merged**
