### PR TITLE
Issue3963

### PR DESCRIPTION
**Pull request by kbrems**
Added threadpool.h to the BUILD script so it can be installed in the public #include directory with a binary pip install. Fixes issue https://github.com/tensorflow/tensorflow/issues/3963

### CODE REVIEW

**Comment by kbrems** [comment]
I should be part of the CLA for Hewlett Packard Enterprise.

**Comment by vrv** [comment]
From our page about Corp CLAs: "The Corporate CLA is only signed once per corporation. As part of signing the CLA, they designate a Google Group that identifies who at their company is authorized to contribute to Google projects." -- do you know whether you've been added to the appropriate google group, and is the email used on your commits the one that is in that group?

**Comment by kbrems** [comment]
I went through the legal review process to be allowed to contribute to tensorflow, so I thought all was set, but let me check on the Google Group.

**Comment by danmane** [comment]
@kbrems Friendly ping so this PR doesn't get forgotten :)

**Comment by kbrems** [comment]
Sigh. The contribution has been approved by our legal dept. but they have to add me to the google group on the CLA and that is taking forever...

**Comment by kbrems** [comment]
My email address should now be on the google group list for the CLA for Hewlett Packard Enterprise.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

(woohoo!!!)

**Pull request merged**
