### PR TITLE
[Go] Add RunOptions as an argument for Tensorflow Session Run

### PR DESCRIPTION
**Pull request by yutkin**
Add RunOptions as an argument for Tensorflow Session Run. Another option is adding a method for `Session` struct like `SetRunOptions()`. It will keep the current API the same, however, such method will be not thread-safe.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @rohan100jain, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rohan100jain, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rohan100jain, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rohan100jain, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @rohan100jain, Can you please review this PR ? Thank you!

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Is there any justification for this?

**Comment by yutkin** [comment]
The PR probably needs to be updated because it has been quite a while since its proposal. But anyway, having `RunOptions` for session runs is crucial because it allows specifying a timeout for calls. We used it actively in our project.

**Comment by gbaned** [comment]
Hi @mihaimaruseac , Can you please review this PR ? Thank you!

**Comment by mihaimaruseac** [comment]
I'll review once it gets updated, if it will

**Comment by gbaned** [comment]
Hi @yutkin Any update on this PR? Please. Thank you!

**Pull request closed without merging**
