### PR TITLE
 add `tf.div_no_nan` op for division by zero

### LINKED ISSUE #15706: Feature request: unsafe_div op
As discussed with @drpngx in #14667 , we found that several PRs are related to division by zero problem, for example, #15443, #14865. 

#### 1. why do we need the op

In `metrics`, `loss` and `math_ops` modules, all create a `_safe_div` or `_safe_scalar_div` method with help of `array_ops.where` to resolve the problem. However, we think those implementations have three disadvantages:
1. Lack of generality: most are designed for only scalar.
2. Not efficient.
3. Since `where` ops propagates NaNs in gradients (#2540), we have to use nested `where` trick which is a little counter-intuitive.

#### 2. what behavior do we expect it

Above all, we propose to create new c++ op: `safe_div`:
+ When denominator is zero, return 0 or numerator. The behavior can be selected by user themselves.
+ Optional: Treat negative as zero, which is sometime useful for loss calculation.
+ Create its own gradient op to avoid NaN problem for `where`.

I think for metric, loss and gradient calculation, they could benefit from the op and get rid of NaN.
And I'd like to contribute the op in **contrib** at first if the proposition is approved by tensorflowers.

#### 3. how to implement it

By the way, since  the name`safe_div` has been used in cwise_ops.h, whose behavior is opposite: raise an exception for integer when divide by zero. 
https://github.com/tensorflow/tensorflow/blob/3629fc4e98254c37e614ac3f77fa250b75c70f8d/tensorflow/core/kernels/cwise_ops.h#L703
So perhaps we need to either rename it or create a new name for our op. Does anyone has a good idea?

### PR DESCRIPTION
**Pull request by facaiy**
Fix #15706, #17350, #20091. 
Ref #19105.

This is a summary of discussion in #15706:

+ op name: div_no_nan
+ op behavior: return 0 when denominator is zero
+ designed for float value only: float32, float 64
+ op kernel: CPU for now  (GPU kernel will be add later).

### CODE REVIEW

**Comment by facaiy** [comment]
As suggested by @yifeif, create a follow up PR for #19105.
cc @drpngx @martinwicke @asimshankar

**Review by martinwicke — DISMISSED** [review]

**Comment by yifeif** [comment]
Thanks @facaiy. Could you take a look at the api_compatibility_test failure?

**Comment by facaiy** [comment]
Hi, @yifeif. The UnsafeDiv op #19105 was merged prematurely before we finished the discussion about its API design in  #15706. I think it's an expected failure, because UnsafeDiv op is being renamed DivNoNan here. But the PR, actually, do not break backwards_compatibility of released version, I think we can ignore the failure.

**Comment by martinwicke** [comment]
That matches my understanding. However, do we need to update goldens here?

**Comment by facaiy** [comment]
Thanks for reminding me. I didn't recognize that there are two versions for golden file: v1 and v2. Those files are updated. Is there anything else that has to be done?

**Comment by martinwicke** [comment]
The two versions are new in preparation of 2.0. Thanks for updating. Running tests.

**Comment by facaiy** [comment]
Thanks for your explanation. Except of backwards_compatibility_test, other failures seems unrelated?

**Comment by martinwicke** [comment]
@yifeif I merged this PR (using a clone), but for some reason the PR isn't closed? Is that some asynchronous process? Did I mess something up?

**Comment by yifeif** [comment]
This is expected. The tool only automatically merges the PR if the last commit in the PR matches the imported version. Looks like the internal change only officially imported up to hash c69459 (not including the latest commit in this PR). But I saw @martinwicke you made the same V1 golden fix internally as the last commit made by @facaiy, so we should be good here. I'll close this PR.

**Comment by facaiy** [comment]
Thank you everyone!

**Comment by facaiy** [comment]
@yifeif feifei, could you close issue #15706, #17350 ? I think both are resolved.

**Pull request closed without merging**
