### PR TITLE
Don't load libcupti.so from regular path on Android

### PR DESCRIPTION
**Pull request by andrewharp**
Open to alternatives, but as other methods in this file work similarly this doesn't seem too bad.

### CODE REVIEW

**Comment by rmlarsen** [comment]
Looks OK to me, but @petewarden better take a look.

**Review by petewarden — APPROVED** [review]

**Comment by rmlarsen** [comment]
@yifei @gunan why does the CLA check not pass for this, despite CLA being added by the bot earlier?!?

**Comment by gunan** [comment]
Not sure why it is failing. The pull request and commit authors are the same, and he is a googler.
@willnorris any ideas?

**Comment by rmlarsen** [comment]
I am going to set the CLAlabel manually and merge this.

**Comment by rmlarsen** [comment]
@willnorris @gunan that doesn't seem to help?!? How to merge this?

**Comment by andrewharp** [comment]
Could it be related to this? Duplicate random PR from "unknown repository" with a missing CLA: https://github.com/tensorflow/tensorflow/pull/16367

**Comment by andrewharp** [comment]
Weird, I added the CLA to that one and it fixed this one... :P

**Comment by willnorris** [comment]
The only thing from @googlebot that I see here is setting "cla:yes" four days ago.  What is/was the problem?

**Comment by andrewharp** [comment]
@willnorris there's no current issue, the problem resolved itself after I manually set the CLA:yes tag on #16367. It seems they somehow created a phantom PR that masked the flags on this one. GitHub bug possibly?

**Comment by willnorris** [comment]
Setting the cla status on one PR has no effect on other PRs.  I think the timing of you manually setting that is just coincidental.

**Comment by andrewharp** [comment]
Possibly, but it cleared up instantly when I flipped the tag after being blocked for over a day. Something is strange with that PR because it says it's from an "unknown repository" despite being a clone of this one.

**Pull request merged**
