### PR TITLE
[INTEL MKL] Fix Tensorflow MKL 'set-build-env.py' script syntax error

### PR DESCRIPTION
**Pull request by ashahba**
Thanks for catching this @kkasravi

### CODE REVIEW

**Comment by ashahba** [comment]
@kkasravi would you please provide your consent here like this:

@googlebot I consent

Thanks.

**Comment by gbaned** [comment]
@ashahba Thank you for your contribution. Can you please sign CLA? Thanks!

**Comment by ashahba** [comment]
@gbaned me and @kkasravi both have CLA's and I'm waiting for him to provide consent.
If I don't hear from him by EOD tomorrow, I'll go ahead and do another identical minor PR 🙂

**Comment by kkasravi** [comment]
@googlebot I consent

**Comment by ashahba** [comment]
Thanks @kkasravi 
@gbaned The `CLA` issue is resolved now.

**Comment by ashahba** [comment]
@mihaimaruseac this one is ready to go.

**Review by penpornk — APPROVED** [review]
Thank you for the fix!

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
