### PR TITLE
remove duplicated code

### PR DESCRIPTION
**Pull request by horance-liu**
I'm remove duplicated code, and to avoid missing when adding new error code.

### CODE REVIEW

**Comment by jhseu** [comment]
Seems like it was intentionally done this way, but adding @skye to chime in.

**Comment by skye** [comment]
@josh11b actually wrote this, but I agree we should keep it as-is. It's actually less error-prone in the long run, as it doesn't depend on TF_Code and the proto being in sync (and will fail if we add a new code to the proto without adding it to TF_Code).

**Comment by horance-liu** [comment]
@skye @jhseu It has delayed for a long time. the modification will be less error-prone in future, and remove duplicated code implementation.

**Comment by jhseu** [comment]
Closing as per Skye's comments.

**Pull request closed without merging**
