### PR TITLE
Safely terminate server RPC loops

### PR DESCRIPTION
**Pull request by andrewor14**
**Issue:** Clean server shutdown is currently not supported. This is because the RPC loops in `GrpcWorkerService` and `GrpcMasterService` do not actually exit even after `Shutdown()` is called.

**Fix:** This commit adds the mechanism to break out of the RPC loops in both of these classes, modeled after how `GrpcEagerServiceImpl` does it.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tensorflow/28935)

### CODE REVIEW

**Comment by andrewor14** [comment]
I signed it!

**Review by mrry — CHANGES_REQUESTED** [review]
Thank you for taking on this problem. As you can probably tell, the logic for shutting down an asynchronous gRPC server is quite subtle. Can you please add some tests that cover the shutdown case?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
@andrewor14 gentle ping to add test cases.

**Comment by tensorflowbutler** [comment]
It has been 28 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
