### PR TITLE
WIP - Remove left over swift rules

### PR DESCRIPTION
**Pull request by ashahba**
Looks like `swift` rules were accidentally deleted and now I'm getting the error:
```
[0m[91mERROR: error loading package '': Encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swift': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external/bazel_tools/tools/build_defs/repo/git.bzl", line 166
		_clone_or_update(ctx)
	File "/root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external/bazel_tools/tools/build_defs/repo/git.bzl", line 72, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning build_bazel_rules_swift:
+ cd /root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external
+ rm -rf /root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external/build_bazel_rules_swift /root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external/build_bazel_rules_swift
+ git clone --depth=1 https://github.com/bazelbuild/rules_swift.git /root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external/build_bazel_rules_swift
Cloning into '/root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external/build_bazel_rules_swift'...
fatal: unable to access 'https://github.com/bazelbuild/rules_swift.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
+ git clone https://github.com/bazelbuild/rules_swift.git /root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external/build_bazel_rules_swift
Cloning into '/root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external/build_bazel_rules_swift'...
fatal: unable to access 'https://github.com/bazelbuild/rules_swift.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
[0m[91mERROR: error loading package '': Encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swift': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external/bazel_tools/tools/build_defs/repo/git.bzl", line 166
		_clone_or_update(ctx)
	File "/root/.cache/bazel/_bazel_root/c04143c934ba98544255b77f5f229b2f/external/bazel_tools/tools/build_defs/repo/git.bzl", line 72, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning build_bazel_rules_swift:
```

### CODE REVIEW

**Comment by gunan** [comment]
@temrich has been working on this, not sure about the status.

**Comment by temrich** [comment]
They were removed intentionally since they are pulled in via the Apple bazel rules: https://github.com/bazelbuild/rules_apple/blob/master/apple/repositories.bzl#L115

Same for skylib:
https://github.com/bazelbuild/rules_apple/blob/master/apple/repositories.bzl#L99

**Comment by temrich** [comment]
Can you share the BUILD file / targets you are trying to build that triggers the error you are seeing?

**Comment by ashahba** [comment]
Actually it turns out that we attempted to remove `swift` but we didn't completely cleanup 🙂 
So hence removing the leftover junk.

**Comment by ashahba** [comment]
Once this one is merged I'll update this one as well:
https://github.com/tensorflow/tensorflow/pull/25736

**Comment by temrich** [comment]
What's the reasoning for removing swift_rules_dependencies() in the WORKSPACE file? Can you provide some more details on how you are getting a build error and which platform you are building on?

**Comment by ashahba** [comment]
The details are the actual `rules` have been removed but we are still attempting to load them in lines `57` and `58` that we are removing in this PR, otherwise loading them would give the above error.

**Comment by temrich** [comment]
Can you sync your branch to master? The TensorFlow Lite Swift library depends on the Swift bazel deps when building on Apple platforms: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/swift/BUILD.apple#L10

**Comment by ashahba** [comment]
@temrich I synced my branch with master.

**Comment by temrich** [comment]
Sounds good, thank you! Assuming you are still seeing an error because of `swift_rules_dependencies()` in the WORKSPACE? If so, can you provide info for the following:

1) Which version of Bazel are you using?
2) Are you building on Mac or Linux (or some other platform)?
3) Which command(s) are you running that triggers this error?

I would like to try to repro this on my end. Thank you!

**Comment by ashahba** [comment]
@temrich I don't have access to a machine to reproduce again but possibly tomorrow I can post my config here.
Thanks.

**Comment by ashahba** [comment]
@temrich I was able to spend some time on this and we may not need PR after all, since I was able to build the images manually. It's possible that this is specific to our `CI` system.
I'm going to mark this PR and `WIP` for now and if that turns out to be the case, I'll close this one and I'll come back with a new PR specific to `MKL` area.

**Comment by temrich** [comment]
Hey Abolfazl, thank you for continuing to look into this. Please let me know if you run into anymore issues.

**Comment by ashahba** [comment]
Ok, looks like this is no longer needed and the issue was in our `CI` scripts.
Closing the PR.

**Pull request closed without merging**
