### PR TITLE
Tf lite cross compilation

### PR DESCRIPTION
**Pull request by vinceab**
This pull request add the support of cross compiling variables.
It allow to cross compile TFLite library and python module for platforms other than aarch64, Rpi and iOS.
It has been successfully tested with Yocto Openembedded environment to build TensorFlow Lite for the new STM32MP1 Microprocessor target from STMicroelectronics.

BR
Vincent Abriou

### CODE REVIEW

**Comment by vinceab** [comment]
Hello,

Have you any update concerning this pull request?

Thanks
BR
Vincent

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by terryheo** [comment]
Thanks Vincent for the contribution.
It seems that your PR is bit outdated to apply. Could you check if you still need a patch for your Yocto Openembedded environment with the recent TFLite release?

**Comment by vinceab** [comment]
Terry, I see that my patches could not be applied on the last version.
I will update my patches according to the last TensorFlow version to check what is still missing.
If any missing stuff, I will push a new pull request.

BR
Vincent

**Comment by terryheo** [comment]
Got it. Then let's close this PR until it's needed again.

**Pull request closed without merging**
