### PR TITLE
Fix spelling error: adverserial -> adversarial

### PR DESCRIPTION
**Pull request by DanCard**

### CODE REVIEW

**Review by alextp — APPROVED** [review]

**Comment by alextp** [comment]
Thanks!

**Comment by rthadur** [comment]
@alextp  could you please look at the failing checks

**Comment by alextp** [comment]
@rthadur it just says "page not found"

**Comment by rthadur** [comment]
@alextp  thank you , @DanCard please create your PR in "tensorflow:master "

**Comment by rthadur** [comment]
> @alextp thank you , @DanCard please create your PR in "tensorflow:master "

@DanCard  gentle ping

**Comment by DanCard** [comment]
Master has the fix.  Sorry for the noise.

**Pull request closed without merging**
