### PR TITLE
Fix issue with collective_nccl_test.

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
This issue was caught by our internal CI.

/cc @cheshire @jpienaar

### CODE REVIEW

**Comment by cheshire** [comment]
I'm a bit confused as to how we were able to check in the code which does not build.

**Comment by jpienaar** [comment]
@cheshire same

**Review by jpienaar — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by rthadur** [comment]
@rsanthanam-amd can you please update your branch

**Comment by rsanthanam-amd** [comment]
@rthadur I have updated my branch.

**Comment by jpienaar** [comment]
The change is empty, I think this has been merged already.

**Comment by rsanthanam-amd** [comment]
@cheshire @jpienaar Confirmed that the fix has already been made in this commit: https://github.com/tensorflow/tensorflow/commit/8557ca660aa7b1d5853d3a1f2fe19cae5be4b589

**Pull request closed without merging**
