### PR TITLE
Update learning.py

### PR DESCRIPTION
**Pull request by yogiadi**
Changed description in learning.py .

### CODE REVIEW

**Comment by karmel** [comment]
Fixes #19043

**Review by caisq — APPROVED** [review]

**Comment by yogiadi** [comment]
@caisq  Hi , changes are approved but still I am getting a required check for Ubuntu CC. Not sure what does it mean ?

**Comment by caisq** [comment]
@yogiadi PR merged. Thanks.

**Comment by yogiadi** [comment]
@caisq  thx :-)

**Pull request merged**
