### PR TITLE
OptimizationPass::POST_REWRITE_FOR_EXEC after Grappler optimization

### PR DESCRIPTION
**Pull request by nutti**
I found there is graph optimization ordering difference between PartitionedCallOp and GraphExecutionState.
I think OptimizationPass::POST_REWRITE_FOR_EXEC should be applied after Grappler optimization because we can not add the graph conversion between Grappler optimization and graph partitioning.

This PR matches the graph optimization ordering.

### CODE REVIEW

**Review by akshaym — DISMISSED** [review]
Thanks for the fix!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nutti** [comment]
@akshaym @aaroey 

Thanks for the reviewing and testing.
The only I did is moving the original code, but I noticed that there is a clang-format check error on CI.
Should I fix these error?

**Comment by aaroey** [comment]
@nutti Yes please help to fix the broken tests, then we can try to merge again. Thanks.

**Comment by nutti** [comment]
@aaroey @akshaym 

Thanks for your advice.
Now, I fixed the format error issued by CI.
Could you review and test this patch again, please?

**Pull request merged**
