### PR TITLE
Move cache_rpc_response from GrpcWorkerServiceOptions to ConfigProto.…

### PR DESCRIPTION
**Pull request by jiakai0419**
for this  
```  
    // TODO(jingdong): it would be cleaner to move this option to GrpcWorker
    // since the cache is maintained by GrpcWorker now.
    if (options.cache_rpc_response) {
      worker->EnableResponseCache();
    }
```

### CODE REVIEW

**Comment by jiakai0419** [comment]
@gbaned Would you mind adding another reviewer?

**Comment by mrry** [comment]
@jing-dong Merging this PR (which looks reasonable to me) will require some changes to the internal code that uses `GrpcWorkerServiceOptions` today. Can you please review and kick off the merge process? Thanks!

**Comment by jiakai0419** [comment]
@mrry @gbaned It's been 14 days. @jing-dong may be busy and have no time to deal with it.

**Review by jing-dong — APPROVED** [review]

**Comment by jing-dong** [comment]
This change has been pushed to the master in the following commit:

https://github.com/tensorflow/tensorflow/commit/29c522fd3e966b6a918d744b45318b59fc5d969a

**Pull request closed without merging**
