### PR TITLE
Make Transactional API methods pure virtual

### PR DESCRIPTION
**Pull request by samikama**
This PR makes Transactional API methods pure virtual to match previous behavior and move new Filesystems to transactional API.

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
Needs manual change of internal filesystems, I think I'll manage the manual import later today/early tomorrow

**Comment by gbaned** [comment]
@mihaimaruseac, Any update on this PR? Please. Thanks!

**Comment by mihaimaruseac** [comment]
Still need to change several internal filesystems. Unfortunately, this period is busy with a lot of other things, so unfortunately this will be delayed until mid next week

**Comment by gbaned** [comment]
@mihaimaruseac, Any update on this PR? Please. Thanks!

**Comment by mihaimaruseac** [comment]
As team got halved with people leaving, modular work has been downprioritized. Will still happen but there are other issues taking my time at the moment so I didn't have time to manually import.

**Comment by gbaned** [comment]
@mihaimaruseac, Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac, Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac, Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by mihaimaruseac** [comment]
All modular TF work is currently stalled. If PR does not pass tests we don't have cycles to import at the moment

**Comment by gbaned** [comment]
@samikama Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Comment by mihaimaruseac** [comment]
> @mihaimaruseac Any update on this PR? Please. Thanks!

The dismissal above the comment states the status. Cannot do any update until things change

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by mihaimaruseac** [comment]
https://github.com/tensorflow/tensorflow/pull/42138#issuecomment-955553325 is still true

**Comment by gbaned** [comment]
@samikama Can you please resolve conflicts? Thank you!

**Comment by mihaimaruseac** [comment]
Until modular TF is brought back, these updates are just treading water. We cannot take the PR in until modular TF work is being done and until then there will be conflicts and staleness.

It might be better to close it and revisit later, given there is no way to mark this work as paused. Or, maybe add a "paused" label?

**Comment by mihaimaruseac** [comment]
Closing stale PR. Should be reopened when modular filesystem is fully implemented.

**Pull request closed without merging**
