### PR TITLE
Fix an exception on using tf.keras.utils.Sequence with tf.distribute.MirroredStrategy under multi-GPU environment

### PR DESCRIPTION
**Pull request by debuggerD**
There is an exception issue on using data provider which is subclass of tf.keras.utils.Sequence with tf.distribute.MirroredStrategy in multi-GPU environment.

There can be get() function calls from other GPUs' training context after an epoch ending have been occured in a GPU's context.
The existing implementation of OrderedEnqueuer class(in tensorflow/python/keras/utils/data_utils.py) access directly inner data of Python's queue object, thus there can be data race issues.

In OrderedEnqueuer.get() function, 
`self.queue.task_done()`
cause 'task_done() called too many times' exception, when it called after another context's OrderedEnqueuer.stop call during waiting for
`inputs = self.queue.get(block=True).get()`.

To prevent this exception, we can check OrderedEnqueuer.is_running() before call self.queue.task_done().

Also, after fix the exception issue, infinity waiting can occured in 
`self.queue.get(block=True)`
after some GPUs' context wait for it after another thread's end of data.
It can be walk arounded by introducing timeout for the queue waiting.

### CODE REVIEW

**Comment by debuggerD** [comment]
@googlebot I signed it!

**Comment by debuggerD** [comment]
@googlebot I fixed it.

**Comment by victech-kimys** [comment]
@googlebot I consent.

**Comment by qlzh727** [comment]
Could u add a test case for that to showcase the failure in the multi-gpu's case?

**Comment by debuggerD** [comment]
This is a test code for the issue what I mentioned:
[tf_test_multi_gpu.py.txt](https://github.com/tensorflow/tensorflow/files/4699458/tf_test_multi_gpu.py.txt)
(Changed extention to .txt due to limitation of attachable file types for GitHub's comment.)

I wrote the code as compatible with existing unit tests, but I didn't commit it as an unit test of TF code because the function consumes a lot of resources which can cause spurious test fail due to OOM.


The problem is occured under both heavy data loading and heavy training situation, so I added fake slow data loader Sequence object and used big model to fit.
My test environment was 16-cores Ubuntu 18.04 machine has 2 NVIDIA TITAN RTX GPUs connected with NVLink.

It's behavior is vary for values of _sequence_length_ and _queue_size_:

1.
The setting that I attached(seq.len=7, queue.len=10) usually caused the exception that I mentioned.
Stack trace was :
```
2020-05-29 11:34:35.128820: W tensorflow/core/framework/op_kernel.cc:1741] Invalid argument: ValueError: task_done() called too many times
Traceback (most recent call last):

  File "/home/dev/.local/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/home/dev/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/home/dev/.local/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 785, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/dev/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 801, in wrapped_generator
    for data in generator_fn():

  File "/home/dev/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/data_utils.py", line 880, in get
    six.reraise(*sys.exc_info())

  File "/home/dev/.local/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value

  File "/home/dev/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/data_utils.py", line 875, in get
    self.queue.task_done()

  File "/usr/lib/python3.7/queue.py", line 74, in task_done
    raise ValueError('task_done() called too many times')

ValueError: task_done() called too many times
```


2.
The setting (seq.len=7, queue.len=4) occasionally caused the infinity waiting I fixed.

3.
When I found the issue with our real code, the length(# of minibatches) of my data sequence was about 58, but I cannot find exact problematic setting for simple test code with same sequence length right now.


I check those problems are not occuring after fix the code as I commited.
I also checked the test code in my desktop which has only one NVIDIA GeForce RTX 2080 Ti GPU, those issues had never seen in the single GPU environment.

**Review by qlzh727 — APPROVED** [review]
Thanks. Let's kick off the existing unit test.

**Comment by quassy** [comment]
Being merged, does this mean this will this be included in TF 2.3.0?

**Pull request merged**
