### PR TITLE
support SparseToDenseOp on GPU

### PR DESCRIPTION
**Pull request by evanrang**
Support SparseToDense operator on GPU, testing shows great performance improvement than on CPU.
#8321

### CODE REVIEW

**Comment by rangjiaheng** [comment]
@concretevitamin Could you help to review this patch ?

**Comment by gbaned** [comment]
@rangjiaheng Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@rangjiaheng Any update on this PR? Please. Thanks!

**Comment by penpornk** [comment]
@rangjiaheng I'm incredibly sorry I dropped the ball on this PR. :'(
It seems a SparseToDenseOp GPU kernel has been added recently in #47234. Are there additional changes you would like to make with this PR?

**Comment by gbaned** [comment]
@rangjiaheng  Can you please check @penpornk's comments and keep us posted ? Thanks!

**Comment by gbaned** [comment]
@rangjiaheng Any update on this PR? Please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 19 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
