### PR TITLE
[INTEL MKL] Fix for 'Horovod>0.19.5' installation

### PR DESCRIPTION
**Pull request by ashahba**
`Horovod` install was recently broken on main branch and `make/cmake` are now required to install the package.
Otherwise the following error happens during install:

```
Step 22/24 : RUN ${PYTHON} -m pip install --no-cache-dir horovod${HOROVOD_VERSION:+==${HOROVOD_VERSION}}
 ---> Running in 33b945e5cbb9
Collecting horovod==0.21.0
  Downloading horovod-0.21.0.tar.gz (3.2 MB)
Collecting cloudpickle
  Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting dataclasses
  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting psutil
  Downloading psutil-5.7.3.tar.gz (465 kB)
Collecting pyyaml
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Building wheels for collected packages: horovod, psutil, pyyaml
  Building wheel for horovod (setup.py): started
  Building wheel for horovod (setup.py): finished with status 'error'
  Running setup.py clean for horovod
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m3fizszw/horovod_5339227cd66141c2a05dc6b44fc7dd16/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m3fizszw/horovod_5339227cd66141c2a05dc6b44fc7dd16/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-va5ikcqf
       cwd: /tmp/pip-install-m3fizszw/horovod_5339227cd66141c2a05dc6b44fc7dd16/
  Complete output (211 lines):
  WARNING: Skipping page https://download.pytorch.org/whl/torch_stable.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html
  WARNING: Skipping page https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html
  WARNING: Skipping page https://download.pytorch.org/whl/torch_stable.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html
  WARNING: Skipping page https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html
  WARNING: Skipping page https://download.pytorch.org/whl/torch_stable.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html
  WARNING: Skipping page https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html
  WARNING: Skipping page https://download.pytorch.org/whl/torch_stable.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html
  WARNING: Skipping page https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/horovod
  copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
  creating build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/compression.py -> build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/optimizer.py -> build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/functions.py -> build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/sync_batch_norm.py -> build/lib.linux-x86_64-3.6/horovod/torch
  creating build/lib.linux-x86_64-3.6/horovod/spark
  copying horovod/spark/conf.py -> build/lib.linux-x86_64-3.6/horovod/spark
  copying horovod/spark/gloo_run.py -> build/lib.linux-x86_64-3.6/horovod/spark
  copying horovod/spark/mpi_run.py -> build/lib.linux-x86_64-3.6/horovod/spark
  copying horovod/spark/runner.py -> build/lib.linux-x86_64-3.6/horovod/spark
  copying horovod/spark/__init__.py -> build/lib.linux-x86_64-3.6/horovod/spark
  creating build/lib.linux-x86_64-3.6/horovod/ray
  copying horovod/ray/elastic.py -> build/lib.linux-x86_64-3.6/horovod/ray
  copying horovod/ray/driver_service.py -> build/lib.linux-x86_64-3.6/horovod/ray
  copying horovod/ray/runner.py -> build/lib.linux-x86_64-3.6/horovod/ray
  copying horovod/ray/__init__.py -> build/lib.linux-x86_64-3.6/horovod/ray
  creating build/lib.linux-x86_64-3.6/horovod/keras
  copying horovod/keras/elastic.py -> build/lib.linux-x86_64-3.6/horovod/keras
  copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
  copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
  creating build/lib.linux-x86_64-3.6/horovod/common
  copying horovod/common/elastic.py -> build/lib.linux-x86_64-3.6/horovod/common
  copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
  copying horovod/common/basics.py -> build/lib.linux-x86_64-3.6/horovod/common
  copying horovod/common/exceptions.py -> build/lib.linux-x86_64-3.6/horovod/common
  copying horovod/common/util.py -> build/lib.linux-x86_64-3.6/horovod/common
  creating build/lib.linux-x86_64-3.6/horovod/mxnet
  copying horovod/mxnet/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/mxnet
  copying horovod/mxnet/__init__.py -> build/lib.linux-x86_64-3.6/horovod/mxnet
  copying horovod/mxnet/functions.py -> build/lib.linux-x86_64-3.6/horovod/mxnet
  creating build/lib.linux-x86_64-3.6/horovod/runner
  copying horovod/runner/js_run.py -> build/lib.linux-x86_64-3.6/horovod/runner
  copying horovod/runner/run_task.py -> build/lib.linux-x86_64-3.6/horovod/runner
  copying horovod/runner/gloo_run.py -> build/lib.linux-x86_64-3.6/horovod/runner
  copying horovod/runner/mpi_run.py -> build/lib.linux-x86_64-3.6/horovod/runner
  copying horovod/runner/__init__.py -> build/lib.linux-x86_64-3.6/horovod/runner
  copying horovod/runner/launch.py -> build/lib.linux-x86_64-3.6/horovod/runner
  copying horovod/runner/task_fn.py -> build/lib.linux-x86_64-3.6/horovod/runner
  creating build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/compression.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/elastic.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/gradient_aggregation.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/gradient_aggregation_eager.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/functions.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/sync_batch_norm.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/util.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  creating build/lib.linux-x86_64-3.6/horovod/_keras
  copying horovod/_keras/elastic.py -> build/lib.linux-x86_64-3.6/horovod/_keras
  copying horovod/_keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/_keras
  copying horovod/_keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/_keras
  creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
  copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
  creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
  copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
  creating build/lib.linux-x86_64-3.6/horovod/torch/elastic
  copying horovod/torch/elastic/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/elastic
  copying horovod/torch/elastic/state.py -> build/lib.linux-x86_64-3.6/horovod/torch/elastic
  copying horovod/torch/elastic/sampler.py -> build/lib.linux-x86_64-3.6/horovod/torch/elastic
  creating build/lib.linux-x86_64-3.6/horovod/spark/torch
  copying horovod/spark/torch/estimator.py -> build/lib.linux-x86_64-3.6/horovod/spark/torch
  copying horovod/spark/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/spark/torch
  copying horovod/spark/torch/remote.py -> build/lib.linux-x86_64-3.6/horovod/spark/torch
  copying horovod/spark/torch/util.py -> build/lib.linux-x86_64-3.6/horovod/spark/torch
  creating build/lib.linux-x86_64-3.6/horovod/spark/task
  copying horovod/spark/task/gloo_exec_fn.py -> build/lib.linux-x86_64-3.6/horovod/spark/task
  copying horovod/spark/task/mpirun_exec_fn.py -> build/lib.linux-x86_64-3.6/horovod/spark/task
  copying horovod/spark/task/task_service.py -> build/lib.linux-x86_64-3.6/horovod/spark/task
  copying horovod/spark/task/__init__.py -> build/lib.linux-x86_64-3.6/horovod/spark/task
  copying horovod/spark/task/task_info.py -> build/lib.linux-x86_64-3.6/horovod/spark/task
  creating build/lib.linux-x86_64-3.6/horovod/spark/keras
  copying horovod/spark/keras/estimator.py -> build/lib.linux-x86_64-3.6/horovod/spark/keras
  copying horovod/spark/keras/optimizer.py -> build/lib.linux-x86_64-3.6/horovod/spark/keras
  copying horovod/spark/keras/bare.py -> build/lib.linux-x86_64-3.6/horovod/spark/keras
  copying horovod/spark/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/spark/keras
  copying horovod/spark/keras/tensorflow.py -> build/lib.linux-x86_64-3.6/horovod/spark/keras
  copying horovod/spark/keras/remote.py -> build/lib.linux-x86_64-3.6/horovod/spark/keras
  copying horovod/spark/keras/util.py -> build/lib.linux-x86_64-3.6/horovod/spark/keras
  creating build/lib.linux-x86_64-3.6/horovod/spark/common
  copying horovod/spark/common/_namedtuple_fix.py -> build/lib.linux-x86_64-3.6/horovod/spark/common
  copying horovod/spark/common/estimator.py -> build/lib.linux-x86_64-3.6/horovod/spark/common
  copying horovod/spark/common/store.py -> build/lib.linux-x86_64-3.6/horovod/spark/common
  copying horovod/spark/common/params.py -> build/lib.linux-x86_64-3.6/horovod/spark/common
  copying horovod/spark/common/backend.py -> build/lib.linux-x86_64-3.6/horovod/spark/common
  copying horovod/spark/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/spark/common
  copying horovod/spark/common/constants.py -> build/lib.linux-x86_64-3.6/horovod/spark/common
  copying horovod/spark/common/cache.py -> build/lib.linux-x86_64-3.6/horovod/spark/common
  copying horovod/spark/common/serialization.py -> build/lib.linux-x86_64-3.6/horovod/spark/common
  copying horovod/spark/common/util.py -> build/lib.linux-x86_64-3.6/horovod/spark/common
  creating build/lib.linux-x86_64-3.6/horovod/spark/driver
  copying horovod/spark/driver/host_discovery.py -> build/lib.linux-x86_64-3.6/horovod/spark/driver
  copying horovod/spark/driver/driver_service.py -> build/lib.linux-x86_64-3.6/horovod/spark/driver
  copying horovod/spark/driver/rsh.py -> build/lib.linux-x86_64-3.6/horovod/spark/driver
  copying horovod/spark/driver/job_id.py -> build/lib.linux-x86_64-3.6/horovod/spark/driver
  copying horovod/spark/driver/mpirun_rsh.py -> build/lib.linux-x86_64-3.6/horovod/spark/driver
  copying horovod/spark/driver/__init__.py -> build/lib.linux-x86_64-3.6/horovod/spark/driver
  copying horovod/spark/driver/rendezvous.py -> build/lib.linux-x86_64-3.6/horovod/spark/driver
  creating build/lib.linux-x86_64-3.6/horovod/runner/task
  copying horovod/runner/task/task_service.py -> build/lib.linux-x86_64-3.6/horovod/runner/task
  copying horovod/runner/task/__init__.py -> build/lib.linux-x86_64-3.6/horovod/runner/task
  creating build/lib.linux-x86_64-3.6/horovod/runner/http
  copying horovod/runner/http/__init__.py -> build/lib.linux-x86_64-3.6/horovod/runner/http
  copying horovod/runner/http/http_server.py -> build/lib.linux-x86_64-3.6/horovod/runner/http
  copying horovod/runner/http/http_client.py -> build/lib.linux-x86_64-3.6/horovod/runner/http
  creating build/lib.linux-x86_64-3.6/horovod/runner/util
  copying horovod/runner/util/__init__.py -> build/lib.linux-x86_64-3.6/horovod/runner/util
  copying horovod/runner/util/threads.py -> build/lib.linux-x86_64-3.6/horovod/runner/util
  copying horovod/runner/util/network.py -> build/lib.linux-x86_64-3.6/horovod/runner/util
  copying horovod/runner/util/cache.py -> build/lib.linux-x86_64-3.6/horovod/runner/util
  copying horovod/runner/util/remote.py -> build/lib.linux-x86_64-3.6/horovod/runner/util
  copying horovod/runner/util/lsf.py -> build/lib.linux-x86_64-3.6/horovod/runner/util
  creating build/lib.linux-x86_64-3.6/horovod/runner/common
  copying horovod/runner/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/runner/common
  creating build/lib.linux-x86_64-3.6/horovod/runner/driver
  copying horovod/runner/driver/driver_service.py -> build/lib.linux-x86_64-3.6/horovod/runner/driver
  copying horovod/runner/driver/__init__.py -> build/lib.linux-x86_64-3.6/horovod/runner/driver
  creating build/lib.linux-x86_64-3.6/horovod/runner/elastic
  copying horovod/runner/elastic/settings.py -> build/lib.linux-x86_64-3.6/horovod/runner/elastic
  copying horovod/runner/elastic/driver.py -> build/lib.linux-x86_64-3.6/horovod/runner/elastic
  copying horovod/runner/elastic/discovery.py -> build/lib.linux-x86_64-3.6/horovod/runner/elastic
  copying horovod/runner/elastic/worker.py -> build/lib.linux-x86_64-3.6/horovod/runner/elastic
  copying horovod/runner/elastic/__init__.py -> build/lib.linux-x86_64-3.6/horovod/runner/elastic
  copying horovod/runner/elastic/rendezvous.py -> build/lib.linux-x86_64-3.6/horovod/runner/elastic
  copying horovod/runner/elastic/constants.py -> build/lib.linux-x86_64-3.6/horovod/runner/elastic
  copying horovod/runner/elastic/registration.py -> build/lib.linux-x86_64-3.6/horovod/runner/elastic
  creating build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/settings.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/host_hash.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/codec.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/timeout.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/safe_shell_exec.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/tiny_shell_exec.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/hosts.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/__init__.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/network.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/env.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/secret.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  copying horovod/runner/common/util/config_parser.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/util
  creating build/lib.linux-x86_64-3.6/horovod/runner/common/service
  copying horovod/runner/common/service/driver_service.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/service
  copying horovod/runner/common/service/task_service.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/service
  copying horovod/runner/common/service/__init__.py -> build/lib.linux-x86_64-3.6/horovod/runner/common/service
  creating build/lib.linux-x86_64-3.6/horovod/tensorflow/keras
  copying horovod/tensorflow/keras/elastic.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow/keras
  copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow/keras
  copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow/keras
  running build_ext
  Traceback (most recent call last):
    File "/tmp/pip-install-m3fizszw/horovod_5339227cd66141c2a05dc6b44fc7dd16/setup.py", line 89, in build_extensions
      cwd=self.build_temp)
    File "/usr/lib64/python3.6/subprocess.py", line 306, in check_call
      retcode = call(*popenargs, **kwargs)
    File "/usr/lib64/python3.6/subprocess.py", line 287, in call
      with Popen(*popenargs, **kwargs) as p:
    File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
      restore_signals, start_new_session)
    File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-m3fizszw/horovod_5339227cd66141c2a05dc6b44fc7dd16/setup.py", line 193, in <module>
      'horovodrun = horovod.runner.launch:run_commandline'
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-install-m3fizszw/horovod_5339227cd66141c2a05dc6b44fc7dd16/setup.py", line 93, in build_extensions
      raise RuntimeError('CMake failed: {}'.format(str(e)))
  RuntimeError: CMake failed: [Errno 2] No such file or directory: 'cmake': 'cmake'
  ----------------------------------------
  ERROR: Failed building wheel for horovod
```

### CODE REVIEW

**Comment by ashahba** [comment]
@angerson we also need some parts of this hotfix on [r2.4](https://github.com/tensorflow/tensorflow/tree/r2.4) as well.
So I created a cherry-pick here: #45806

**Comment by ashahba** [comment]
`PowerTools` repo name is also subject to licensing issue, so that's fixed in this PR as well.

**Review by penpornk — APPROVED** [review]
Thank you for the fixes and I'm so sorry for the delay!

**Pull request merged**
