### PR TITLE
BUG: fix, layer_test doesn't accept layer_cls key

### PR DESCRIPTION
**Pull request by facaiy**
The bug is reported on https://github.com/tensorflow/addons/pull/92

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fchollet, @pavithrasv: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @fchollet, @pavithrasv: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Review by fchollet — CHANGES_REQUESTED** [review]
Thank you for the PR. Please add a unit test to check correctness.

**Comment by facaiy** [comment]
@rthadur Hi, is there something wrong with CI?

**Comment by facaiy** [comment]
@fchollet Thank you, I think unit test has been added, could you take a look again?

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@facaiy Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
