### PR TITLE
[INTEL MKL]Fixing spurious omp thread spawning

### PR DESCRIPTION
**Pull request by Srini511**
In some models that use eager/imperative code where we don’t rewrite a few operators to MKL, a lot (intra_op_threads*OMP_NUM_THREADS) of threads are spawned by Eigen matmul code. This is because -fopenmp flag is passed to Eigen as part of the build configuration. This PR fixes the configuration to not pass -fopenmp to Eigen under --config=mkl.

### CODE REVIEW

**Review by penpornk — CHANGES_REQUESTED** [review]
Thank you for your PR! I have a question and a minor formatting change request.

**Review by penpornk — APPROVED** [review]
Thank you for the fixes!

**Comment by Srini511** [comment]
Hi @penpornk , is everything okay with the PR?

**Comment by penpornk** [comment]
@Srini511 Let's talk through email. :)

**Pull request merged**
