### PR TITLE
Error in variable_scope initialization, via estimator api, due to a panda.DataFrame without column headers

### PR DESCRIPTION
**Pull request by sagarrjadhav**
The variable_scope initialization generates an error when a panda.DataFrame object without any column headers is passed via the estimator api.

To replicate this issue, please execute the below-specified code - 

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import pandas as pd


def main(argv):
    # Fetch the data
    (train_x, train_y), (test_x, test_y) = load_data()

    # Feature columns describe how to use the input.
    my_feature_columns = []
    for key in train_x.keys():
        my_feature_columns.append(tf.feature_column.numeric_column(key=key))

    # Build 2 hidden layer DNN with 10, 10 units respectively.
    classifier = tf.estimator.DNNClassifier(
        feature_columns=my_feature_columns,
        # Two hidden layers of 10 nodes each.
        hidden_units=[10, 10],
        # The model must choose between 3 classes.
        n_classes=3)

    # Train the Model.
    classifier.train(
        input_fn=lambda: train_input_fn(train_x, train_y,
                                        100),
        steps=1000)

    # Evaluate the model.
    eval_result = classifier.evaluate(
        input_fn=lambda: eval_input_fn(test_x, test_y,
                                       10))

    print('\nTest set accuracy: {accuracy:0.3f}\n'.format(**eval_result))


def load_data():

    # Note that there are no column names specified during the
    # DataFrame initialization
    train_x = pd.DataFrame([[6.4, 2.8, 5.6, 2.2],
                            [5,	2.3, 3.3, 1],
                            [4.9, 2.5, 4.5, 1.7],
                            [4.9, 3.1, 1.5, 0.1]], dtype=float)
    train_y = pd.DataFrame([[2], [1], [2], [0]], dtype=float)

    test_x = pd.DataFrame([[4.4, 3.2, 1.3, 0.2]], dtype=float)
    test_y = pd.DataFrame([[2]], dtype=float)

    print(train_x)

    return (train_x, train_y), (test_x, test_y)


def train_input_fn(features, labels, batch_size):
    """An input function for training"""
    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))

    # Shuffle, repeat, and batch the examples.
    dataset = dataset.shuffle(1000).repeat().batch(batch_size)

    # Return the dataset.
    return dataset


def eval_input_fn(features, labels, batch_size):
    """An input function for evaluation or prediction"""
    features = dict(features)
    if labels is None:
        # No labels, use only features.
        inputs = features
    else:
        inputs = (features, labels)

    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices(inputs)

    # Batch the examples
    assert batch_size is not None, "batch_size must not be None"
    dataset = dataset.batch(batch_size)

    # Return the dataset.
    return dataset


if __name__ == '__main__':
    tf.logging.set_verbosity(tf.logging.INFO)
    tf.app.run(main)

```

Output, printing the 'train_x' dataframe, before the error - 

```python
     0    1    2    3
0  6.4  2.8  5.6  2.2
1  5.0  2.3  3.3  1.0
2  4.9  2.5  4.5  1.7
3  4.9  3.1  1.5  0.1
```
Note that there are no column headers provided, the respective index appears as the column header for the data frame which is of type integer.

Traceback - 
```python
Traceback (most recent call last):
  File "tf_bug.py", line 90, in <module>
    tf.app.run(main)
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "tf_bug.py", line 30, in main
    steps=1000)
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\estimator\estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\estimator\estimator.py", line 743, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\estimator\estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\estimator\canned\dnn.py", line 324, in _model_fn
    config=config)
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\estimator\canned\dnn.py", line 176, in _dnn_model_fn
    logits = logit_fn(features=features, mode=mode)
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\estimator\canned\dnn.py", line 90, in dnn_logit_fn
    features=features, feature_columns=feature_columns)
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 280, in input_layer
    trainable, cols_to_vars)
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 193, in _internal_input_layer
    None, default_name=column._var_scope_name):  # pylint: disable=protected-access
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1929, in __enter__
    unique_default_name = _get_unique_variable_scope(self._default_name)
  File "C:\Users\Sagar_Jadhav03\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1656, in _get_unique_variable_scope
    name = current_scope.name + "/" + prefix if current_scope.name else prefix
TypeError: must be str, not int
```

### CODE REVIEW

**Comment by xiejw** [comment]
Thanks for reporting and debugging this! 

If I understand correctly, the issue is that the default pandas DataFrame has int as type for column headers.

Given the Estimator requires the input_fn returning a dict with string name as key (i.e., str type) [1], I think a better way to fix this is the pandas_input_fn, i.e., Line 118 of [2]. Most of the tooling around Estimator is written based on the fact that the dict has string key name. 

wdyt?

[1] https://github.com/tensorflow/tensorflow/blob/7c324811f10eaf049735ace7b6a228ccc931d8ff/tensorflow/python/estimator/estimator.py
[2] https://github.com/tensorflow/tensorflow/blob/bc69c4ceed6544c109be5693eb40ddcf3a4eb95d/tensorflow/python/estimator/inputs/pandas_io.py

**Comment by Stryker0301** [comment]
Adding a comment to resolve the issue with the CLA.

**Comment by Stryker0301** [comment]
adding comment to resolve the issue with the CLA.

**Comment by Stryker0301** [comment]
Sorry for being late on responding to this and thanks for your inputs.

I did try and check if we can insert the fix at the [place](https://github.com/tensorflow/tensorflow/blob/bc69c4ceed6544c109be5693eb40ddcf3a4eb95d/tensorflow/python/estimator/inputs/pandas_io.py#L118) suggested by you, but it appears that the said line is not invoked for the example given by me.

Also, I'm not completely aware of how pandas input_fn is used. If you can point to any relevant documentation explaining the usage, that would be helpful.

Coming back to the main topic, the other alternatives that I can think of for this problem are - 
1. Keep the fix at the same place which I had proposed earlier, which would localize its effect and avoid the error.
2. Given that the name of the feature column is used as the partial name for constructing the name of the variable scope, cast the return value of the method - ['_var_scope_name'](https://github.com/tensorflow/tensorflow/blob/7c324811f10eaf049735ace7b6a228ccc931d8ff/tensorflow/python/feature_column/feature_column.py#L1595) to 'str'.
3. Or else override the method specified in [2] in the class - ['_NumericColumn'](https://github.com/tensorflow/tensorflow/blob/7c324811f10eaf049735ace7b6a228ccc931d8ff/tensorflow/python/feature_column/feature_column.py#L2030) to return an 'str' value. This would localize its effect to numeric feature columns only.

Let me know your thoughts on this.

**Comment by Stryker0301** [comment]
Could you please check and let me know if you agree to the proposed solution.

**Comment by xiejw** [comment]
Sorry the confusion. When I see the "panda", I am thinking pandas_input_fn [1].

I re-read your code and figured out you were creating the input_fn by yourself. I have tested your scripted locally and found the following issues:
1) scope name should not be int. It should be str. Of course, this is not user facing part as your repro example is using the number_column.
2) tf.feature_column.numeric_column takes a string as key name [2]. Your repro example is passing int, which is not allowed. 

I do not think it is reasonable to hack all the framework code in order to support the unsupported "int" type here as most of APIs explicitly documented the argument should be string. Added @ispirmustafa 
for his insights.

I think there are two ways to fix this
1) In your code, cast all the keys to string types. It should work. I have not tested by myself. You can either give explicit string column name to DataFrame or cast in the input_fn.

2) You can also use the tf.estimator.inputs.pandas_input_fn. It needed a fix I mentioned in previous comment (converting the column name from int to str) -- which I can fix for you. See [3] for a working example. 

I think item 1) by adding string column name is easiest for you. See [4]


[1]  https://www.tensorflow.org/api_docs/python/tf/estimator/inputs/pandas_input_fn

[2] https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column

[3] https://gist.github.com/xiejw/7b4c351beec41817c62f587ad90970ad

[4] https://gist.github.com/xiejw/329502f3726f139e6af85829bdad2720

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @xiejw: It has been 23 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by xiejw** [comment]
Close due to inactivity.

**Pull request closed without merging**
