### PR TITLE
[INTEL MKL] Change order for remapper

### PR DESCRIPTION
**Pull request by mdfaijul**
This PR is to test if there will be any regression if the order of remapper in grappler meta_optimizer is moved before arithmetic_optimizer.

### CODE REVIEW

**Comment by mdfaijul** [comment]
@ezhulenev could you please if this PR would have any regression or not?

**Review by ezhulenev — APPROVED** [review]
Run internal tests, seems to be ok.

**Comment by ezhulenev** [comment]
Though I did not test for perf regressions, they still could show up after the change will be submitted.

**Comment by mdfaijul** [comment]
@ezhulenev I see this has been reverted. Could you please explain me the reason?

**Comment by ezhulenev** [comment]
I caused ~8% perf regression in multi-gpu (and I think single GPU as well) Resnet benchmark on V100. Still don't know the root cause.

**Comment by mdfaijul** [comment]
@ezhulenev Thanks for your quick reply. If this PR is not the root cause, may I request to bring this PR back.
I have work for couple of fusions (with DNNL aka INTEL_MKL) based on this PR, i.e., an assumption that remapper runs before arithmetic_optimizer.

**Comment by ezhulenev** [comment]
The problem is unfortunately in this PR, I'm just not sure what exactly happens, my guess is that some fusion prevents an important arithmetic rewrite from happening. I have 2 perf profiles, will try to find the clue there. Unfortunately it takes an order of hours to reproduce the benchmark in multi-gpu setup...

What are the current problems with remapper running after arithmetic?

**Comment by mdfaijul** [comment]
@ezhulenev Thanks again for your kind reply.
I have been preparing a PR for a fusion (MatMul + BiasAdd + Gelu) through remapper optimizer, using pattern matcher that we have contributed earlier. Subgraph for gelu is generated from the api `tf.nn.gelu(feature, approximate=True)`. This optimization is very useful for BERT_LARGE model inference on Intel CPU. It gives us 20% performance improvement. Below are sample subgraphs: (left) generated from python api (middle) input graph to remapper when arithmetic_optimizer runs before remapper and (right) input graph to remapper when arithmetic_optimizer does not run before remapper. So arithmetic_optimzer changes the graph that is not obvious from python APIs. Although I can provide middle graph as an input to the pattern matcher, for future complex fusion it becomes unpredictable pattern for a potential fusion.

Gelu-Fusion

Adding @agramesh1  in the discussion.

**Pull request merged**
