### PR TITLE
Java does not need operations like'& 0xff'in the process of strong rotation. Reducing this operation can reduce many calculations and improve performance.

### PR DESCRIPTION
**Pull request by yuxitong**
Java does not need operations like'& 0xff'in the process of strong rotation. Reducing this operation can reduce many calculations and improve performance.

Before that, every pixel in the picture had to be operated on three times, which would reduce the speed relatively. Because Java has the feature of high-to-low and discards high-to-low directly, high-to-low does not require manual'& 0xff'to be strong.

### CODE REVIEW

**Comment by yuxitong** [comment]
I signed it!

**Comment by yuxitong** [comment]
I signed it!

**Comment by harshini-gadige** [comment]
@petewarden  Any update ?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by petewarden** [comment]
Sorry for the delay in reviewing. The TensorFlow mobile examples are deprecated and no longer being actively maintained, so closing this one.

**Pull request closed without merging**
