### PR TITLE
Enable denormal test in open source

### PR DESCRIPTION
**Pull request by girving**
They seem to work fine; not sure what changed since ages ago.  The test works fine on my linux desktop and my OS X laptop; we'll see how it fares on the rest of the Jenkins machines.

### CODE REVIEW

**Comment by girving** [comment]
Internal bug link so that I can get to it from here: b/28906384.

**Comment by girving** [comment]
@mrry Suggestions for how to fix the Windows part?  I'm a bit surprised that it doesn't work, since the denormal flag code only depends on SSE3 (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/denormal.cc#L27).  Maybe SSE3 isn't on for the Windows build?

**Comment by girving** [comment]
2 tests in the Python 3 run seem to fail for unrelated reasons, so Windows is the only issue.

**Comment by drpngx** [comment]
```
10:14:10 FAIL: testFlushDenormalsCPU (__main__.DenormalTest)
10:14:10 ----------------------------------------------------------------------
10:14:10 Traceback (most recent call last):
10:14:10   File "C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/python/kernel_tests/denormal_test.py", line 50, in testFlushDenormalsCPU
10:14:10     self._flushDenormalsTest(use_gpu=False, dtypes=(np.float32, np.float64))
10:14:10   File "C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/python/kernel_tests/denormal_test.py", line 44, in _flushDenormalsTest
10:14:10     self.assertAllEqual(flush.eval(), np.zeros(shape))
10:14:10   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\test_util.py", line 535, in assertAllEqual
10:14:10     np.testing.assert_array_equal(a, b)
10:14:10   File "C:\Program Files\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 871, in assert_array_equal
10:14:10     verbose=verbose, header='Arrays are not equal')
10:14:10   File "C:\Program Files\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 796, in assert_array_compare
10:14:10     raise AssertionError(msg)
10:14:10 AssertionError: 
10:14:10 Arrays are not equal
10:14:10 
10:14:10 (mismatch 100.0%)
10:14:10  x: array(1.1754946310819804e-39, dtype=float32)
10:14:10  y: array(0.0)
10:14:10 
10:14:10 ======================================================================
10:14:10 FAIL: testFlushDenormalsGPU (__main__.DenormalTest)
10:14:10 ----------------------------------------------------------------------
10:14:10 Traceback (most recent call last):
10:14:10   File "C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/python/kernel_tests/denormal_test.py", line 54, in testFlushDenormalsGPU
10:14:10     self._flushDenormalsTest(use_gpu=True, dtypes=(np.float32,))
10:14:10   File "C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/python/kernel_tests/denormal_test.py", line 44, in _flushDenormalsTest
10:14:10     self.assertAllEqual(flush.eval(), np.zeros(shape))
10:14:10   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\test_util.py", line 535, in assertAllEqual
10:14:10     np.testing.assert_array_equal(a, b)
10:14:10   File "C:\Program Files\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 871, in assert_array_equal
10:14:10     verbose=verbose, header='Arrays are not equal')
10:14:10   File "C:\Program Files\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 796, in assert_array_compare
10:14:10     raise AssertionError(msg)
10:14:10 AssertionError: 
10:14:10 Arrays are not equal
10:14:10 
10:14:10 (mismatch 100.0%)
10:14:10  x: array(1.1754946310819804e-39, dtype=float32)
10:14:10  y: array(0.0)
```

I suppose we could use `assertAllClose` instead of `assertAllEqual` unless it should be exactly zero.

**Comment by girving** [comment]
Given that we're checking whether denormals are flushed to zero, I'd prefer to stay with `assertAllEqual`.

**Comment by mrry** [comment]
@girving From this [similar-sounding bug in Eigen](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=136), it looks like MSVC does build with SSE3 instructions, but does doesn't define `__SSE3__`. Since Eigen seems to have the necessary conditionals for sending whether SSE3 is available, perhaps we could use`#ifdef EIGEN_VECTORIZE_SSE3` instead?

**Comment by girving** [comment]
@mrry Excellent idea.  I've confirmed that `__SSE3__ -> EIGEN_VECTORIZE_SSE3` doesn't break my desktop or laptop, so hopefully Jenkins will be greener after the last commit.

**Comment by girving** [comment]
@mrry Alas, looks like that didn't do it.

**Comment by mrry** [comment]
Hmm, looking at the present-day Eigen code, perhaps this is never defined:

https://bitbucket.org/eigen/eigen/src/737f257bb23da9175bcef9102b702b4ab0671a2b/Eigen/Core?at=default&fileviewer=file-view-default#Core-121

If we assume that all Windows machines that we care about have SSE3 (I think that's reasonable, right?), maybe adding an explicit `-DEIGEN_VECTORIZE_SSE3` to CMakeLists.txt for the Windows build [here](https://github.com/tensorflow/tensorflow/blob/859d8e30070fec468fa9f8f052eae5b7c086d72b/tensorflow/contrib/cmake/CMakeLists.txt#L62) would be the way to go.

**Comment by girving** [comment]
@mrry I'm okay with an explicit define if you are.  It's a bit sad, but the web isn't showing me any alternatives either.  I'll give it a try.

**Comment by girving** [comment]
Woot.  @mrry: I think it's ready for review.

**Review by mrry — APPROVED** [review]
LGTM!

**Comment by gunan** [comment]
This test seems to have failed in windows-cpu cmake build.
http://ci.tensorflow.org/job/tf-master-win-gpu-cmake/223/console
testFlushDenormalsGPU fails with:
01:46:34.321 (mismatch 100.0%)
01:46:34.321  x: array(1.1754946310819804e-39, dtype=float32)
01:46:34.321  y: array(0.0)

Any ideas?

**Comment by drpngx** [comment]
I merged when it was all green. We had that error before and @girving / @mrry fixed it on the thread above. It sounded it like fix was deterministic.

**Comment by girving** [comment]
@gunan Yep, the fix should have been deterministic, but let me know if these failures continue.

**Comment by gunan** [comment]
Windows GPU tests take hours, so we do not run them during presubmits.
I will keep an eye on the build and touch back if we still have issues
after a few runs.

**Comment by girving** [comment]
@gunan Ah, the GPU Windows build probably will break.  To fix it I need to add a flag to cmake's use of nvcc.  Since I can't test it myself, should I prepare a PR and ask you to test?

**Comment by gunan** [comment]
Sure, I can quickly start a presubmit run for windows cmake gpu on any pull
requests you need.

**Comment by gunan** [comment]
Is it possible this was passing, because we were building everything with sse4.1?
My change to disable sse4.1 seems to break this test:
https://github.com/tensorflow/tensorflow/pull/7349
https://ci.tensorflow.org/job/tensorflow-pull-requests-gpu/3588/consoleFull

**Comment by girving** [comment]
@gunan Yes, we need at least SSE3 for this test to pass.  Is the plan to not have SSE3 going forwards?

**Pull request merged**
