### PR TITLE
update protobuf to 3.0.0b2.post2

### PR DESCRIPTION
**Pull request by jendap**

### CODE REVIEW

**Comment by martinwicke** [comment]
tests don't look good. Is that a bazel 0.2 issue?

**Comment by jendap** [comment]
It is! But I was looking at it puzzled before reading your comment. It would be really good to have https://github.com/bazelbuild/bazel/issues/1014.

**Comment by jendap** [comment]
@tensorflow-jenkins test this please.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by vrv** [comment]
(Can you remind me what we need to upgrade this for?)

**Comment by vrv** [comment]
I suspect this is going to be updated for ios support in a separate PR.

**Pull request closed without merging**
