### PR TITLE
Refine permuation const device placement for LayoutOptimizer.

### PR DESCRIPTION
**Pull request by lowintelligence**
In layout optimizer of Grappler, two permutation const nodes would be
added into the graph by default. The nodes should be placed to a default
device assigned by a Virtual Placer, which was constructed from the
cluster infomation. However, the Virtual Placer could not distinguish
remote devices from local ones in distributed runtime, which causes that
a remote device might be the default device. Thus unnecessary dependency
between workers would be implicitly built, unexpected crashed would
occur in asynchronous distributed graph running.

This fix only refines the behaviour of LayoutOptimizer. Permutation
const nodes would be lazy created when necessary and would be colocated
with the connected nodes if the device was already done. Each device
would keep one pair and at most one pair of permutation consts, so that
these consts would not bring cross-device send-recv in ideal cases.

### CODE REVIEW

**Comment by lowintelligence** [comment]
Here is a real case found in our production jobs.

Workers are running the asynchronous training independently. But after worker 3 successfully finished, other worker reported errors for failed receiving operation and exited because of the permutation const was placed on worker 3 by layout optimizer. That's why we try to fix this issue in this PR.
image

**Review by rmlarsen — DISMISSED** [review]

**Comment by rmlarsen** [comment]
Looks good. Let's get this merged.

**Comment by lowintelligence** [comment]
> Looks good. Let's get this merged.

Thanks for approving the commit. I saw some UTs was broken in CI build, some of them were caused by invalid node name. I'll check and fix it.

**Comment by lowintelligence** [comment]
@rmlarsen I've fixed a bug caused by empty device name in the code and also stripped the first '_' char for the perm const node. Could you take a check again? Thx.

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@lowintelligence thanks!

**Pull request merged**
