### PR TITLE
Clean up unused variables in a example

### PR DESCRIPTION
**Pull request by izeye**
This PR removes unused variables in `mnist_with_summaries.py` and makes its document align with it.

### CODE REVIEW

**Comment by vrv** [comment]
I think for illustration purposes, the current code might be useful to show that these functions do return objects that *could* be used, even though at the moment the side effects are that they add to the graph. What do you think?

**Comment by izeye** [comment]
@vrv If they have been added intentionally, this PR could be closed. Thanks for the feedback!

**Comment by vrv** [comment]
@danmane: what do you think?  Originally they were given names (which led to unused_var lint errors).   Do you still think it's worth capturing the return values?

**Comment by martinwicke** [comment]
The summary ops are magic in that the canonical summary use depends on the collection. They are ops just like all the others, but their return values are very rarely used (I guess you could depend on them, but typically you're really happy that they don't run, and what are you going to do with the serialized proto anyway except for write it to disk?). I would omit the return types in the example code, I don't think it's all that enlightening.

**Comment by vrv** [comment]
Ok, merged

**Pull request closed without merging**
