### PR TITLE
Add layer scope to tf.contrib.layers.spatial_softmax

### PR DESCRIPTION
**Pull request by lospooky**
`tensorflow.contrib.layers.spatial_softmax` is lacking a layer-level scope

| before | after |
|---|---|
|before|after|

### CODE REVIEW

**Comment by martinwicke** [comment]
This may break checkpoints by changing variable names (unless I misunderstand). You could use a name_scope instead, that is harmless.

**Comment by lospooky** [comment]
On one hand, yes, that would break checkpoints. On the other, wouldn't it be a bit against the general behavior of the `layers` api to create variables not in their own scope but in the global one?

No problem though if you'd prefer a `name_scope` however.

**Comment by martinwicke** [comment]
That is true, variable_scope would have been the right thing to do. I am wary of breaking people though, so I'd rather stick with the safer fix. 

@sguada, do you agree with name_scope here? Or should we try for variable_scope.

**Comment by sguada** [comment]
Since it creates a variable it should have a variable_scope.

**Comment by martinwicke** [comment]
Are you ok with breaking checkpoints using this? That's what a variable_scope would do. If you're ok with it, I am too.

**Review by sguada — APPROVED** [review]
I'm ok with this change.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Pull request merged**
