### PR TITLE
Unstack int64 tensors on GPU

### PR DESCRIPTION
**Pull request by dantkz**
Registered unstack GPU kernel op for int64 tensors.
Extended tests to check unstack op on different types of tensors for CPU and GPU.

### CODE REVIEW

**Comment by frankchn** [comment]
Jenkins, test this please.

**Comment by dantkz** [comment]
It's been 3 weeks now.

**Review by jart — APPROVED** [review]
Thank you so much for the patience. We really appreciate it when people take the time to send us contributions like this.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
