### PR TITLE
fix iOS example README

### PR DESCRIPTION
**Pull request by buffxz**
fix iOS example README

The iOS example got moved to a different directory. This PR fixes that.

Test plan:

- [x] test it by following the readme to set up the new project for iOS.

### CODE REVIEW

**Comment by buffxz** [comment]
I signed it!

**Comment by buffxz** [comment]
ping

**Comment by buffxz** [comment]
ping

**Comment by martinwicke** [comment]
@mhyttsten, does that look right to you?

**Review by mhyttsten — COMMENTED** [review]
Thank you for noting this! This should have been fixed already by another commit that was scheduled but which apparently did not go through. That CL also had other fixes (in addition to this one) to the README, so I will pursue making sure it passes (to avoid any conflicts by also committing you PR).  Please keep additional pull requests coming if you find more problems, it is much appreciated. Thanks!

**Pull request closed without merging**
