### PR TITLE
[ROCm] Adding no_rocm tag to CSB tests currently failing on the ROCm platform

### PR DESCRIPTION
**Pull request by deven-amd**
/cc @whchung  @cheshire @chsigg @nvining-work

### CODE REVIEW

**Review by cheshire — APPROVED** [review]

**Review by alextp — APPROVED** [review]

**Comment by deven-amd** [comment]
@gbaned gentle ping

**Comment by deven-amd** [comment]
@gbaned gentle ping

**Review by jaingaurav — APPROVED** [review]

**Comment by deven-amd** [comment]
@gbaned gentle ping

Merging this PR will get the ROCm CSB passing again...let me know if there is anything we can do to expedite this

**Comment by jaingaurav** [comment]
@deven-amd: Apologies, the PR was missing one approval internally. It should be landing shortly now.

**Pull request merged**
