### PR TITLE
Overview sanilty check fails on pylint upgrade

### LINKED ISSUE #43038: Pylint incorrectly identifies tensorflow public API functions in tensorflow 2.2+
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Apart from the example below, no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04/OSX 10.15.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: :x:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2+
- Python version: 3.7.4
- Bazel version (if compiling from source): :x:
- GCC/Compiler version (if compiling from source): :x:
- CUDA/cuDNN version: :x:
- GPU model and memory: :x:

**Describe the current behavior**
When using pylint, a lot of functions from the public API are misidentified.
For example, the public api function `tf.split`, which is publicly defined as `tensorflow/python/ops/array_ops.split` is misidentified (I think as `tensorflow/python/ops/gen_array_ops.split`).

Other examples include `tf.random.uniform`, `tf.concat` and the list goes on.

Let's take the code snipped below:

`example.py`:
```python
import tensorflow as tf

tensor = tf.random.uniform((2, 4), minval=0, maxval=256)
tf.split(tensor, num_or_size_splits=2, axis=-1)
```

This is perfectly fine code, it runs as expected.

However, when running pylint both functions are misidentified and lots of linting errors are raised.
Running pylint on the module (`pylint -E example.py`) gives:
```
example.py:3:9: E1123: Unexpected keyword argument 'minval' in function call (unexpected-keyword-arg)
example.py:3:9: E1123: Unexpected keyword argument 'maxval' in function call (unexpected-keyword-arg)
example.py:3:9: E1120: No value for argument 'dtype' in function call (no-value-for-parameter)
example.py:4:0: E1123: Unexpected keyword argument 'num_or_size_splits' in function call (unexpected-keyword-arg)
example.py:4:0: E1124: Argument 'axis' passed by position and keyword in function call (redundant-keyword-arg)
example.py:4:0: E1120: No value for argument 'value' in function call (no-value-for-parameter)
example.py:4:0: E1120: No value for argument 'num_split' in function call (no-value-for-parameter)
```

**Describe the expected behavior**
Running `pylint -E example.py` should not give any errors.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

tensor = tf.random.uniform((2, 4), minval=0, maxval=256)
tf.split(tensor, num_or_size_splits=2, axis=-1)
```

**Other info / logs**
This occurs with `tensorflow>=2.2.0`.
Previous versions of tensorflow `2.X` (e.g. tensorflow `2.1.X` and tensorflow `2.0.X`) do not have these problems.

I have used `pylint==2.6.0` for the example, but previous versions have the same behaviour.

One of the things that might have caused this (just a guess) is the upgrade to a new version of `gast` that occurred in tensorflow `2.2`, where they went from `gast==0.2.2` to `gast==0.3.3`.

Now, I know that this issue is not a code breaking issue, but it is a workflow breaking issue when using tensorflow in a professional setting. For example, one of the requirements for passing all steps in the CI may be running pylint, which now fails. Pylint allow disabling errors for specific third-party packages, so really the only solution is to add a `pylint: disable=...` comment every time you use a tensorflow function which is misidentified or to disable pylint for the project all together. Both options aren't desirable.

This issue was also raised in the `pylint` repo (https://github.com/PyCQA/pylint/issues/3613) and probably also related to https://github.com/PyCQA/pylint/issues/3596. But I don't think these issues belong in the `pylint` repo` (or `astroid` for that matter), but here in the tensorflow repo as it's probably caused by the import structure of tensorflow.

One lead might be that a wildstar import overwrites functions. An examples might be the wildstar import in https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/ops/array_ops.py#L40 which overwrites `tensorflow/python/ops/array_ops.split` with the starred import `tensorflow/python/ops/gen_array_ops.split`. I'm not sure, but not performing wildstar imports might solve this linter problem.

### PR DESCRIPTION
**Pull request by bhack**
This is just to have an overview of the sanity checks that will fail with a `pytlint` upgrade:

Theoretically fix: https://github.com/tensorflow/tensorflow/issues/43038

### CODE REVIEW

**Comment by bhack** [comment]
To shortcut triage routing /cc @mihaimaruseac

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by gbaned** [comment]
@bhack  This PR is in draft, any update on this? Please. Thanks!

**Comment by bhack** [comment]
@gbaned Check https://github.com/tensorflow/tensorflow/issues/43038#issuecomment-688817162

**Comment by bhack** [comment]
Also in the meantime pylint was just partially updated but with another version by https://github.com/tensorflow/tensorflow/pull/42938 approved by @angerson

**Comment by gbaned** [comment]
@bhack  Can you please resolve conflicts? Thanks!

**Comment by mihaimaruseac** [comment]
Hmm, sanity is still failing :(

**Comment by bhack** [comment]
@mihaimaruseac Yes this was opened to have an overview of what it is failing with an updated version of pylint.

**Comment by bhack** [comment]
Let me know what is the plan. Do we want to change pylint configuration? Do we want to fix something else? Etc..

**Comment by mihaimaruseac** [comment]
I don't think there is any plan at the moment. We have the issue that we have to make sure any changes to pylint don't go against internal lint rules, but otherwise I think we can attempt an upgrade

**Comment by gbaned** [comment]
@bhack  Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Comment by angerson** [comment]
@mihaimaruseac We already fixed this internally, right? Is this PR still necessary?

**Comment by mihaimaruseac** [comment]
I am unsure. Our pylint version is still old and needs to be upraded (config too). There's at least a discrepancy between formatting and linting code around Python type annotations.

**Comment by gbaned** [comment]
@angerson Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@angerson  Any update on this PR? Please. Thanks!

**Comment by bhack** [comment]
@mihaimaruseac Why it was ready to pull and merged? What is the plan?

**Comment by mihaimaruseac** [comment]
It looked like it was passing all external CI when I approved. It is failing internal sanity with 

```
FAIL: Found 6088 non-allowlisted pylint errors:
tensorflow/lite/python/convert.py:112: [E0307(invalid-str-returned), OpsSet.__str__] __str__ does not return str
...
```

Will probably revert and try fixing from inside now.

**Comment by bhack** [comment]
> It looked like it was passing all external CI when I approved. It is failing internal sanity with 
> 
> ```
> FAIL: Found 6088 non-allowlisted pylint errors:
> tensorflow/lite/python/convert.py:112: [E0307(invalid-str-returned), OpsSet.__str__] __str__ does not return str
> ...
> ```
> 
> Will probably revert and try fixing from inside now.

Ok thanks

**Comment by bhack** [comment]
We had a rolback of this with https://github.com/tensorflow/tensorflow/commit/420ce899d013b7ac60482a66edacb458cc6a6bf1

**Pull request merged**
