### PR TITLE
Misc improvements to Dockerfile.devel-gpu

### PR DESCRIPTION
**Pull request by cancan101**

### CODE REVIEW

**Comment by martinwicke** [comment]
Can you please sign the CLA? I had to revert this one, my bad for not looking.

**Comment by cancan101** [comment]
I signed it! /CC @martinwicke

**Comment by martinwicke** [comment]
Thanks!

**Comment by martinwicke** [comment]
I'll revert the revert.

**Comment by aselle** [comment]
Seems like this is resolved. Closing for now.

**Pull request merged**
