### PR TITLE
[PluggableDevice] Add the option to force memory growth

### PR DESCRIPTION
**Pull request by PatriceVignola**
It's currently possible to force memory growth either from the session or the `TF_FORCE_GPU_ALLOW_GROWTH` environment variable, but some pluggable devices may need even more control than that. On some architectures and devices, allocating the memory all at once in a single is simply not an option so the pluggable devices should have the tools to prevent that from being overridden by the user.

### CODE REVIEW

**Comment by gbaned** [comment]
@saxenasaurabh Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@PatriceVignola  Can you please resolve conflicts? Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
