### PR TITLE
Update deploy docs to use Minio distributed mode as well

### PR DESCRIPTION
**Pull request by nitisht**
Based on discussion here (https://github.com/minio/minio/issues/5797#issuecomment-38089813),
distributed erasure code deployment works fine with Tensorflow.

### CODE REVIEW

**Comment by nitisht** [comment]
I signed it!

**Comment by nitisht** [comment]
cc @elsonrodriguez

**Comment by elsonrodriguez** [comment]
Yeah, it looks good. Sorry I forgot to go back and remove this note. The Minio team has long since fixed this bug.

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
