### PR TITLE
Support weight_column for time series regressor

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by allenlavoie** [comment]
Right now the Estimators operate on a single series. What is getting weighted here? Parts of the series?

**Comment by terrytangyuan** [comment]
I guess I should've spent some more time on the input pipeline. I was
assuming those estimators support multiple series (for example multivariate
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/timeseries/examples/multivariate.py)
so I could use part of the series (one of the columns in the data)  as
weights. Please correct me if I misunderstood something here.

**Comment by allenlavoie** [comment]
Ah, so the idea is that each feature of the series can have its own weight? I suppose that could be useful. Could you add a unit test or two?

**Comment by terrytangyuan** [comment]
I am basically trying to complete feature parity against the heads used by
non-ts estimators, e.g.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/canned/head.py#L786

Right now it's using the shared _weights() function in canned/head.py to
extract the weight column from the list of columns from input.

**Comment by terrytangyuan** [comment]
Got distracted by my projects recently. I am going to close this one for now until I found more time.

**Pull request closed without merging**
