### PR TITLE
gpu floor mod .

### PR DESCRIPTION
**Pull request by zhaozheng09**

### CODE REVIEW

**Comment by cheshire** [comment]
What is the CL description?

**Comment by reedwm** [comment]
@sanjoy, IIRC we generate MLIR-based GPU kernels for component wise ops. Is MLIR used for FloorMod? I would prefer to generate a GPU kernel instead of adding more hand-written ones.

**Comment by zhaozheng09** [comment]
The optimal solution is to call the implementation of the open source library, but when the open source library is not available, do we need to write the operator by hand for this function?

**Comment by zhaozheng09** [comment]
1. Can mlir cover all scenes? Are there scenes that mlir cannot cover?
2. The optimal solution is to call the implementation of the open source library, but when the open source library is not available, do we need to hand-write the operator for this function?

**Comment by gbaned** [comment]
@zhaozheng09 Can you please resolve conflicts? Thanks!

**Comment by sherhut** [comment]
So the motivation here is to add support for floor mod on GPU? Can you provide some background what motivates this?

**Comment by zhaozheng09** [comment]
> * Can mlir cover all scenes? Are there scenes that mlir cannot cover?
> * The optimal solution is to call the implementation of the open source library, but when the open source library is not available, do we need to hand-write the operator for this function?



> So the motivation here is to add support for floor mod on GPU? Can you provide some background what motivates this?
> 
> For context: We are about to add this operation as a jitted operation, which means it will be compiled on first invocation. Does that address your need?

motivation: TF don't have GPU floormod.
jitted operation: 
1. Are there scenes that jit op cannot satisfy?
2. If jit op can satisfy all scenarios, can all tf op be deleted like **+, -, *, /** ?
3. Is there anyone who has to close jit due to the negative effects of JIT (for example: dynamic shape), and thus must use the GPU version of the floor mod?

**Comment by akuegel** [comment]
We have now enabled the FloorMod MLIR generated JIT kernel by default. See e688b1e5dc87c67860bae7d477ae555ff5c9d0c9

I will try to answer your questions:
1. It works for all data types that the op is registered for on CPU, except int32 (but for int32 it still uses the special GPU kernel that is registered in cwise_op_floor_mod.cc which uses host memory).

2. For most ops we don't have jitted kernels, but kernels which are compiled ahead of time. FloorMod would work with AOT compilation as well, but we try to avoid increasing the binary size. But yes, quite a few Eigen based GPU kernels could potentially be deleted by now.

3. Our generated code supports dynamic rank and dynamic sizes (with the same limitations as the Eigen based kernels, so broadcasting works up to rank 5 after the shapes have been simplified to smaller ranks when possible - this is a bit complicated to explain). So it needs to compile only once per data type.

I hope the new MLIR generated kernel fits your needs :)

**Comment by zhaozheng09** [comment]
thank you for your answer, and your answer is professional and comprehensive. I will close this pr.
By the way, how did you make XLA or MILR support dynamic shapes? Are there any related articles? I want to learn， thanks:)

**Comment by zhaozheng09** [comment]
Thank you for your professional and comprehensive answer, and I will close this pr.
By the way, how did you make XLA or MILR support dynamic shapes? Are there any related articles? I want to learn， thanks:)

**Comment by zhaozheng09** [comment]
> We have now enabled the FloorMod MLIR generated JIT kernel by default. See [e688b1e](https://github.com/tensorflow/tensorflow/commit/e688b1e5dc87c67860bae7d477ae555ff5c9d0c9)
> 
> I will try to answer your questions:
> 
> 1. It works for all data types that the op is registered for on CPU, except int32 (but for int32 it still uses the special GPU kernel that is registered in cwise_op_floor_mod.cc which uses host memory).
> 2. For most ops we don't have jitted kernels, but kernels which are compiled ahead of time. FloorMod would work with AOT compilation as well, but we try to avoid increasing the binary size. But yes, quite a few Eigen based GPU kernels could potentially be deleted by now.
> 3. Our generated code supports dynamic rank and dynamic sizes (with the same limitations as the Eigen based kernels, so broadcasting works up to rank 5 after the shapes have been simplified to smaller ranks when possible - this is a bit complicated to explain). So it needs to compile only once per data type.
> 
> I hope the new MLIR generated kernel fits your needs :)

Thank you for your professional and comprehensive answer, and I will close this pr.
By the way, how did you make XLA or MILR support dynamic shapes? Are there any related articles? I want to learn， thanks:)

**Comment by akuegel** [comment]
So first, a small disappointment: I had to revert my change because it caused problems on Windows (still need to figure out why, and how to fix them).

> Thank you for your professional and comprehensive answer, and I will close this pr. By the way, how did you make XLA or MILR support dynamic shapes? Are there any related articles? I want to learn， thanks:)

I don't think we have articles about this. But the basic idea for elementwise ops is that for unary ops we reshape it to 1D, then we just need code that works on a dynamic 1D tensor. For binary ops it is harder, because it needs to support broadcasting. Here we do shape specialization. We generate code for ranks between 0 and 5, and the runtime decides which one is picked. To make it possibly work for bigger ranks as well, as a first step, we reshape to shapes with minimum rank such that the broadcasting result would still be the same. We can merge dimensions if there is no change in what is broadcasted. E.g. (1, 1, 5, 5) tensor on left hand side with (3, 3, 5, 5) tensor on right hand side can be simplified to (1, 25) lhs and (9, 25) rhs. In fact we also get rid of leading 1 dimensions, so lhs shape becomes (25).

**Comment by zhaozheng09** [comment]
> So first, a small disappointment: I had to revert my change because it caused problems on Windows (still need to figure out why, and how to fix them).
> 
> > Thank you for your professional and comprehensive answer, and I will close this pr. By the way, how did you make XLA or MILR support dynamic shapes? Are there any related articles? I want to learn， thanks:)
> 
> I don't think we have articles about this. But the basic idea for elementwise ops is that for unary ops we reshape it to 1D, then we just need code that works on a dynamic 1D tensor. For binary ops it is harder, because it needs to support broadcasting. Here we do shape specialization. We generate code for ranks between 0 and 5, and the runtime decides which one is picked. To make it possibly work for bigger ranks as well, as a first step, we reshape to shapes with minimum rank such that the broadcasting result would still be the same. We can merge dimensions if there is no change in what is broadcasted. E.g. (1, 1, 5, 5) tensor on left hand side with (3, 3, 5, 5) tensor on right hand side can be simplified to (1, 25) lhs and (9, 25) rhs. In fact we also get rid of leading 1 dimensions, so lhs shape becomes (25).

thx~

**Comment by akuegel** [comment]
So by now I have tested the MLIR generated FloorMod kernel with ahead of time compilation on windows, and that worked. So the problem is not with the kernel itself, but with the JIT mode (we haven't triggered the problems yet with the other JIT kernels because they are with data types that are probably almost not used). I will keep you updated.

**Pull request closed without merging**
