### PR TITLE
Register ZerosLikeOp for all number types and bool

### LINKED ISSUE #952: Error in //tensorflow/core:ops_array_grad_test
On a machine with a GPU, under the GPU configuration, I ran the command: bazel test -c opt --config=cuda //tensorflow/core:ops_array_grad_test

and I got the following error (see highlight in bold font)

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so.6.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcurand.so.7.0. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_rng.cc:333] Unable to load cuRAND DSO.
Running main() from test_main.cc
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from ArrayGradTest
[ RUN      ] ArrayGradTest.PackGrad
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:909] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 980
major: 5 minor: 2 memoryClockRate (GHz) 1.2785
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.91GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:680] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 2.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 4.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 8.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 16.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 32.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 64.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 128.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 256.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 512.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 2.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 4.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 8.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 16.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 32.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 64.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 128.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 256.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 512.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 2.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 4.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:73] Allocating 3.62GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:83] GPU 0 memory begins at 0x704a80000 extends to 0x7ec261000
[       OK ] ArrayGradTest.PackGrad (481 ms)
[ RUN      ] ArrayGradTest.UnpackGrad
I tensorflow/core/common_runtime/gpu/gpu_device.cc:680] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:01:00.0)
[       OK ] ArrayGradTest.UnpackGrad (2 ms)
[ RUN      ] ArrayGradTest.ConcatGrad
I tensorflow/core/common_runtime/gpu/gpu_device.cc:680] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:01:00.0)
**E tensorflow/core/common_runtime/executor.cc:273] Executor failed to create kernel. Not found: No registered 'ZerosLike' OpKernel for GPU devices compatible with node n8 = ZerosLike[T=DT_INT32](n0)**
         [[Node: n8 = ZerosLike[T=DT_INT32](n0)]]
**W tensorflow/core/common_runtime/executor.cc:1096] 0x7f70d3c21f10 Compute status: Not found: **No registered 'ZerosLike' OpKernel for GPU devices compatible with node n8 = ZerosLike[T=DT_INT32](n0)**
         [[Node: n8 = ZerosLike[T=DT_INT32](n0)]]
         [[Node: dx = SymbolicGradient[Tin=[DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_INT32, DT_FLOAT, DT_FLOAT], f=Concat[N=2, T=DT_FLOAT], _device="/job:localhost/replica:0/task:0/gpu:0"](_recv_dim_0/_1, _recv_x0_0/_3, _recv_x1_0/_5, _recv_dy_0/_7)]]
**W tensorflow/core/common_runtime/executor.cc:1096] 0x7f70d3c224b0 Compute status: Not found: No registered 'ZerosLike' OpKernel for GPU devices compatible with node n8 = ZerosLike[T=DT_INT32](n0)**
         [[Node: n8 = ZerosLike[T=DT_INT32](n0)]]
         [[Node: dx = SymbolicGradient[Tin=[DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_INT32, DT_FLOAT, DT_FLOAT], f=Concat[N=2, T=DT_FLOAT], _device="/job:localhost/replica:0/task:0/gpu:0"](_recv_dim_0/_1, _recv_x0_0/_3, _recv_x1_0/_5, _recv_dy_0/_7)]]
         [[Node: dx/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_18_dx", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
**W tensorflow/core/common_runtime/executor.cc:1096] 0x7f70d3c224b0 Compute status: Not found: No registered 'ZerosLike' OpKernel for GPU devices compatible with node n8 = ZerosLike[T=DT_INT32](n0)
**         [[Node: n8 = ZerosLike[T=DT_INT32](n0)]]
         [[Node: dx = SymbolicGradient[Tin=[DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_INT32, DT_FLOAT, DT_FLOAT], f=Concat[N=2, T=DT_FLOAT], _device="/job:localhost/replica:0/task:0/gpu:0"](_recv_dim_0/_1, _recv_x0_0/_3, _recv_x1_0/_5, _recv_dy_0/_7)]]
         [[Node: dx/_11 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_20_dx", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
**W tensorflow/core/common_runtime/executor.cc:1096] 0x7f70d3c224b0 Compute status: Not found: No registered 'ZerosLike' OpKernel for GPU devices compatible with node n8 = ZerosLike[T=DT_INT32](n0)**
         [[Node: n8 = ZerosLike[T=DT_INT32](n0)]]
         [[Node: dx = SymbolicGradient[Tin=[DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_INT32, DT_FLOAT, DT_FLOAT], f=Concat[N=2, T=DT_FLOAT], _device="/job:localhost/replica:0/task:0/gpu:0"](_recv_dim_0/_1, _recv_x0_0/_3, _recv_x1_0/_5, _recv_dy_0/_7)]]
         [[Node: dx/_13 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22_dx", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
**F tensorflow/core/ops/array_grad_test.cc:126] Check failed: ::tensorflow::Status::OK() == (sess->Run( {{"dim", test::AsScalar(dim)}, {"x0:0", x0}, {"x1:0", x1}, {"dy:0", dy}}, {"dx:0", "dx:1", "dx:2"}, {}, &out)) (OK vs. Not found: No registered 'ZerosLike' OpKernel for GPU devices compatible with node n8 = ZerosLike[T=DT_INT32](n0)**
         [[Node: n8 = ZerosLike[T=DT_INT32](n0)]]
         [[Node: dx = SymbolicGradient[Tin=[DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_INT32, DT_FLOAT, DT_FLOAT], f=Concat[N=2, T=DT_FLOAT], _device="/job:localhost/replica:0/task:0/gpu:0"](_recv_dim_0/_1, _recv_x0_0/_3, _recv_x1_0/_5, _recv_dy_0/_7)]]
         [[Node: dx/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_18_dx", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]])
external/bazel_tools/tools/test/test-setup.sh: line 51:  9618 Aborted                 (core dumped)

### PR DESCRIPTION
**Pull request by martinwicke**
Fixes #952

### CODE REVIEW

**Comment by martinwicke** [comment]
This wasn't ready. It is breaking the GPU build.

**Comment by vrv** [comment]
I'll send a rollback

**Comment by martinwicke** [comment]
I know it looked ready. :/ sorry.

**Comment by vrv** [comment]
Reverted

**Pull request merged**
