### PR TITLE
shard segment reduction op to multi threads

### PR DESCRIPTION
**Pull request by shengofsun**
shards the segment reduction op to multi threads when computing with CPU, so as to speed up the op.

In my test, the time may reduce to about half of original version.

Some other codes are modified automatically when I do the code format with: 
```
clang-format-3.9 -i segment_reduction_ops.cc --style=google
```
So I'm wondering if there's  something wrong with my clang-format.

## Env

* CPU: 8 cores
* Mem: 14G

the benchmark program: https://gist.github.com/shengofsun/cf9b203cb722a290667360770923c55f

### CODE REVIEW

**Comment by shengofsun** [comment]
@caisq could you please take a look at this patch?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by harshini-gadige** [comment]
@caisq PTAL

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 89 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 104 days with no activity and the `awaiting review` label has been applied.

**Comment by jlebar** [comment]
@gbaned I work on XLA and sometimes StreamExecutor, but not TensorFlow.  I get asked to do a lot of TensorFlow reviews and I have to say "no" every time.  Is there something I can do to fix this?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by gbaned** [comment]
@shengofsun could you please resolve the conflicts? Thanks!

**Comment by gbaned** [comment]
@shengofsun gentle ping to resolve the conflicts. Thanks!

**Comment by gbaned** [comment]
@shengofsun Did you get a chance to look on conflicts? Please let us know on the update. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
