### PR TITLE
Fixed param ordering of RESIZE_BILINEAR for NNAPI

### PR DESCRIPTION
**Pull request by silfverstrom**
This commit swaps the ordering of the parameters sent to RESIZE_BILINEAR.
Currently width is sent as height. For reference see the documentation of RESIZE_BILINEAR.
https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a42bd92518e273b6716ecd56b571fcd3e

### CODE REVIEW

**Comment by srjoglekar246** [comment]
This is not a bug, there was an inconsistency between the documentation & the NNAPI driver pre-Android Q. So this should work as intended. Are you seeing an accuracy drop for any model with NNAPI?

**Comment by silfverstrom** [comment]
@srjoglekar246 That is odd. We're running a model on a Xiaomi MI9 as well as a Samsung S10, both with the snapdragon 855. When we disable RESIZE_BILINEAR in the delegate the model is executed correctly, as well as when we run the model without the NNAPI. 

However when delegating to RESIZE_BILINEAR the model returns different/invalid data. Aligning the parameters according to the NNAPI-documentation fixes our problem and gives us consistent results when using the delegate. I assumed this was a bug. Could the parameter-implementation vary between different drivers?

**Comment by miaowang14** [comment]
Unfortunately, there seems discrepancy in NNAPI's CPU reference implementation and the driver implementation for devices running Android P. In Q, NNAPI fixed the documentation and advised QCOM to fix the driver implementation.

I think we should probably make sure width == height before delegating to devices running Android P.

**Comment by silfverstrom** [comment]
@miaowang14 Yes that seems to be the case. I agree that validating width == height makes sense to avoid incorrect behaviour. I could update this pull request with that validation if that is acceptable @srjoglekar246 ?

**Comment by srjoglekar246** [comment]
Will defer to Miao for that :-)

**Comment by miaowang14** [comment]
@silfverstrom , sounds good to me.

**Comment by silfverstrom** [comment]
@miaowang14 I've updated this PR, it now disables bilinear when width != height for nnapi < 1.2.

**Review by miaowang14 — DISMISSED** [review]
thanks for fixing this

**Comment by silfverstrom** [comment]
@miaowang14 @srjoglekar246 Is it possible to merge this pr?

**Comment by srjoglekar246** [comment]
Could you rebase this PR? It shows some errors while merging internally

**Comment by silfverstrom** [comment]
@srjoglekar246 Sure, I've rebased the branch.

**Comment by gbaned** [comment]
@silfverstrom Could you please resolve the conflicts? Thanks!

**Comment by silfverstrom** [comment]
> @silfverstrom Could you please resolve the conflicts? Thanks!

Sure, i've resolved the conflicts.

**Comment by rthadur** [comment]
Changes have been pushed earlier, auto merge did not happen ,so closing this PR.

**Pull request closed without merging**
