### PR TITLE
Convert layer weights even within nested Functional models.

### LINKED ISSUE #49214: RNN weight conversion not applied within nested Functional models
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **no**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **any**, tested on MacOS 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): **binary** (independent)
- TensorFlow version (use command below): since **v2.3.0-rc0**, present in latest
  - since refactoring https://github.com/tensorflow/tensorflow/commit/bb15c97379f197a6a46ec1446d8fb0b292b860ba
- Python version: **any**, 3.7 (independent)
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: **any** (independent)
- GPU model and memory: -

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

The function `convert_nested_model()` nested within `keras.saving.load_model_from_hdf5()` converts layers only nested within `Model` or `Sequential` submodels, but not yet `Functional`.

For a model where GRU is within Functional nested model, trained with CuDNN, conversion when loading without CuDNN is not applied.

The result is that loading fails when setting weight values of incompatible shape.

**Describe the expected behavior**

The conversion is applied to GRU weights even when the layer is nested within a Functional submodel.

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

Yes. I contributed the original code of some of those conversions.

https://github.com/keras-team/keras/pull/10081

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

I will provide a minimal example for reproduction.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
# in K.batch_set_value() for the GRU bias (CuDNN-compatible, ie .reset_after=True)
assign_op = x.assign(assign_placeholder)

self:
<tf.Variable 'gru_18/gru_cell_30/bias:0' shape=(2, 384) dtype=float32>
value:
<tf.Tensor 'Placeholder_173:0' shape=(?,) dtype=float32>
```

The bias value array is 768 and placeholder shape is `(?,)` (1D). It's missin conversion to proper shape: `(2, 384)` (as the variable has).

## Proposed solution

I tried adding the `'Functional'` to the list of nested class names to be be converted.

```
- elif layer.__class__.__name__ in ['Model', 'Sequential']:
+ elif layer.__class__.__name__ in ['Model', 'Sequential', 'Functional']:
```

And the whole model loaded correctly.

+ make unit tests

### PR DESCRIPTION
**Pull request by bzamecnik**
Closes #49214

### CODE REVIEW

**Review by bhack — APPROVED** [review]
Just to run Kokoro

**Comment by bzamecnik** [comment]
@googlebot I signed it!

**Comment by bhack** [comment]
I think the missing CLA is for `Bohumir Zamecnik` user commiter.

**Comment by bhack** [comment]
Check that the your committer email is the same as the CLA

**Comment by bzamecnik** [comment]
@bhack Yeah, thanks. I recommitted it with my personal email.

**Review by bhack — APPROVED** [review]
For Kokoro run

**Review by qlzh727 — APPROVED** [review]
Thanks for the fix. LGTM.

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Pull request merged**
