### PR TITLE
Fix broken image link in TensorFlow Lite's docs

### PR DESCRIPTION
**Pull request by akimach**
I fixed the link of image in the same way as other documents in [tensorflow/tensorflow/docs_src/](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src).

### CODE REVIEW

**Comment by dr4b** [comment]
Yeah, that's fine.  I wrote it for tf.org style links when I first put it in, but I guess this change will make it compatible with viewing on Github as well. However, it looks like I'm not approved to review this?

**Review by dr4b — APPROVED** [review]
Tested this on the tf.org server internally and it works

**Comment by yifeif** [comment]
Thanks @dr4b!

**Comment by akimach** [comment]
Thanks @dr4b !

**Pull request merged**
