### PR TITLE
[XLA:GPU] Add back the profiling information

### PR DESCRIPTION
**Pull request by nouiz**
This commit removed the profiling information for some thunks including fused thunks with reduction:
```
commit 9ac28f43e180e0db65bf7872fcd828680e3d2e92
Author: George Karpenkov <cheshire@google.com>
Date:   Wed Oct 26 06:05:31 2022 -0700
```

Instead of converting many call of ThunkInfo(op) to GetThunkInfo(op), I changed the API to be simpler. So less chance of breaking this in the future.

This has the side effect that initializer now have profiling information. I consider this a good thing.

@cheshire

### CODE REVIEW

**Comment by cheshire** [comment]
Thanks a lot ! Looks like I broke it during refactoring.

**Review by cheshire — APPROVED** [review]

**Comment by nouiz** [comment]
I updated the PR to something more complete. I didn't fixed all the issues. Now I think I did it.
I updated the description with the new fix.

**Review by cheshire — APPROVED** [review]
Thanks ! We should really add tests for this in the future, but I'm not really sure how (E.g. somehow using cupti?)

**Comment by nouiz** [comment]
I quick grep found some cupti related tests. So it should be possible to add some tests.

**Pull request merged**
