### PR TITLE
More numerically stable gradients for division.

### PR DESCRIPTION
**Pull request by tillahoffmann**
This PR improves the numerical stability of gradients for the division operator. 

Let `f = x / y` such that `df/dy = - x / y ** 2`. But if `y` is of small magnitude, `y ** 2` can underflow, and if `y` is of large magnitude, `y ** 2` can overflow. It is thus better to compute the derivative as `df/dy - (x / y) / y`. The changes are illustrated in the figure below using 32-bit floating point representations.

divgrad

The coverage of the new implementation is strictly greater than the coverage of the old implementation, where coverage is the domain in which the gradient is defined.

### CODE REVIEW

**Comment by tillahoffmann** [comment]
Here is a [notebook](https://gist.github.com/tillahoffmann/e2e639335f89f2e5e270bb18edd11ded) to reproduce the figure above.

**Review by drpngx — APPROVED** [review]
`-x / (y*y)` as `(-x / y) / y` should be more stable.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Ignoring unrelated errors.

**Pull request merged**
