### PR TITLE
[INTEL MKL] Enable back MKL auto_mixed_precision

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR fixes an issue in the auto_mixed_precision_test and enables back MKL auto_mixed_precision in the single binary build.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the fix!

**Review by penpornk — CHANGES_REQUESTED** [review]
Could you please help fix the [MacOS CPU Python3](https://source.cloud.google.com/results/invocations/e7b85bf4-a73c-4456-af3f-677f62360540/log) failures? Thank you!
```
ImportError: Traceback (most recent call last):
  File "/Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/lite/python/convert_test.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/lite/python/convert_test.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: __ZN10tensorflow12IsMKLEnabledEv
  Referenced from: /Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/python/../libtensorflow_framework.2.dylib
  Expected in: flat namespace
 in /Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/python/../libtensorflow_framework.2.dylib
```

**Review by penpornk — APPROVED** [review]
Thank you for the quick fix!

**Review by ezhulenev — APPROVED** [review]

**Comment by mahmoud-abuzaina** [comment]
Thank you both for reviewing/approving the PR. This time the `MacOS CPU Python3` error seems to be unrelated to the changes. Please let me know if I need to take a look.

**Pull request merged**
