### PR TITLE
Adding HDFS connection cache on tensorflow side can improve performance by 20+ times #43187

### PR DESCRIPTION
**Pull request by yuanbopeng**
This is a PR from TaiJi AI platform in Tencent.

Adding HDFS connection cache on tensorflow side can improve performance by 20+ times #43187.

### CODE REVIEW

**Comment by byronyi** [comment]
Any chance that your particular HDFS distribution does not cache the connection internally, or it is a general issue for most distributions out there?

Just curious, not a blocker for this PR. Thanks for your contribution!

**Comment by yuanbopeng** [comment]
> Any chance that your particular HDFS distribution does not cache the connection internally, or it is a general issue for most distributions out there?

@byronyi 
Thank you for your reminder. I found that this issue is based on hadoop 2.7 and hadoop 2.8. I will later test whether the latest version of hadoop 3.3 has this issue.

**Comment by jhseu** [comment]
Can you verify whether this is still an issue in recent versions of Hadoop before we merge? If it still is an issue, I don't mind merging this.

**Comment by yuanbopeng** [comment]
> Can you verify whether this is still an issue in recent versions of Hadoop before we merge? If it still is an issue, I don't mind merging this.

@jhseu 
Thank you for your comment. I did the same test in Hadoop 3.3.0 and the performance problem still exists. If there is no cache, [HadoopFileSystem::Connect](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L160) will take more than 10ms. If the cache is added, the time consuming of [HadoopFileSystem::Connect](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L160) can be ignored. For details, please refer to the following content.

image

**test code**
```
#include <sys/time.h>
#include <iostream>

int64_t getCurrentTime() {
  struct timeval tv;
  gettimeofday(&tv, NULL);
  return tv.tv_sec * 1000000 + tv.tv_usec;
}

Status HadoopFileSystem::Connect(StringPiece fname, hdfsFS* fs) {
  int64_t start = getCurrentTime();
  TF_RETURN_IF_ERROR(libhdfs()->status());
  StringPiece scheme, namenode, path;
  .......................
  if (*fs == nullptr) {
    return errors::NotFound(strerror(errno));
  }
  int64_t end = getCurrentTime();
  std::cout << "HadoopFileSystem::Connect use time " << (end - start) << " µs" << std::endl;
  return Status::OK();
}
```
[HadoopFileSystem::Connect](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L160) without connection cache
image

[HadoopFileSystem::Connect](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L160) with connection cache
image

**Comment by yuanbopeng** [comment]
@jhseu  
I think we can temporarily suspend the merging of this patch until I further update this issue.

Out of my curiosity, I want to further look for the cause of the problem.
Added debug code to [hdfsBuilderConnect](https://github.com/apache/hadoop/blob/release-3.3.0-RC0/hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/hdfs.c#L687) on the HDFS side, and found that hdfsBuilderConnect mainly takes time in org/apache/hadoop/fs/FileSystem.get.

**Comment by yuanbopeng** [comment]
> Added debug code to [hdfsBuilderConnect](https://github.com/apache/hadoop/blob/release-3.3.0-RC0/hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/hdfs.c#L687) on the HDFS side, and found that hdfsBuilderConnect mainly takes time in `org.apache.hadoop.fs.FileSystem.get()`.
>
> For further analysis, I will add later.

Furthermore, by adding debug logs to [FileSystem.java getInternal](https://github.com/apache/hadoop/blob/release-3.3.0-RC0/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L3479) and [jni_helper.c invokeMethod](https://github.com/apache/hadoop/blob/release-3.3.0-RC0/hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/jni_helper.c#L126), I found that it takes more than 10ms to call `org.apache.hadoop.fs.FileSystem.get()` through CallStaticObjectMethodV, but the time consumption of `org.apache.hadoop.fs.FileSystem.get()` on the JVM side is negligible. JNI is the root cause of performance problems , Even if FileSystem's cache is effective. In order to overcome the shortcomings brought by JNI, I think it is very necessary to reduce the call to [hdfsBuilderConnect](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L192) by adding the connection cache on the tensorflow side.

@jhseu  Do you agree with my analysis?

**Comment by byronyi** [comment]
So the cache this PR proposes is primarily to reduce the number of JNI calls, is that correct?

**Comment by yuanbopeng** [comment]
> So caching in this PR is primarily to reduce the number of JNI calls, is that correct?
@byronyi  
Yes, it is very costly to obtain HDFS connection through JNI for every HDFS operation.

**Review by jhseu — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Can you make these changes to the modular filesystem implementation, too, @yuanbopeng ? Otherwise, when we switch to them there will be a new regression.

**Comment by yuanbopeng** [comment]
> Can you make these changes to the modular filesystem implementation, too, @yuanbopeng ? Otherwise, when we switch to them there will be a new regression.
cc @mihaimaruseac @vnvo2409 https://github.com/tensorflow/tensorflow/pull/43525

**Comment by byronyi** [comment]
This has caused an issue of reading HDFS, using the official model garden ResNet50:

```
2020-09-30 16:49:16.731277: W tensorflow/core/nccl/nccl_manager.cc:859] NcclManager already aborted, ignoring subsequent StartAbort with Not found: Success
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[while/body/_1/while/IteratorGetNext]]
Traceback (most recent call last):
  File "/home/byronyi/models/official/benchmark/models/resnet_imagenet_main.py", line 304, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/byronyi/official/benchmark/models/resnet_imagenet_main.py", line 297, in main
    stats = run(flags.FLAGS)
  File "/home/byronyi/models/official/benchmark/models/resnet_imagenet_main.py", line 260, in run
    verbose=2)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1076, in fit
    tmp_logs = self.train_function(iterator)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 789, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 849, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 2946, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 1927, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 561, in call
    ctx=ctx)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found:  Success
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[while/body/_1/while/IteratorGetNext]]
	 [[cluster_1_1/merge_oidx_10/_50]]
  (1) Not found:  Success
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[while/body/_1/while/IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_29790]

Function call stack:
train_function -> train_function
```

**Comment by yuanbopeng** [comment]
@byronyi 
Can you provide error information about operating hdfs?

**Comment by byronyi** [comment]
It might come from thread-safety issue. Simply calling `tf.io.gfile` APIs on HDFS path seems fine.

**Comment by yuanbopeng** [comment]
@byronyi 
How do you confirm that it is related to HDFS? Have you compared the situation of removing the cache HDFS? 

In addition, you can try to merge https://github.com/tensorflow/tensorflow/pull/43647 into it

**Comment by yuanbopeng** [comment]
> Simply calling `tf.io.gfile` APIs on an HDFS path is fine.

[https://github.com/apache/hadoop/blob/release-3.3.0-RC0/hadoop-hdfs-project/hadoop-hdfs/src/site/markdown/LibHdfs.md]

**Comment by byronyi** [comment]
The connection cache itself might need to be thread-safe as well.

**Comment by yuanbopeng** [comment]
> The connection cache itself might need to be thread-safe as well.

Do you mean to add thread synchronization here?
```
  if (connectionCache_.find(cacheKey) == connectionCache_.end()) {
    hdfsFS cacheFs = libhdfs()->hdfsBuilderConnect(builder);
    if (cacheFs == nullptr) {
      return errors::NotFound(strerror(errno));
    }
    connectionCache_[cacheKey] = cacheFs;
  }
```
In theory, multiple threads may acquire the same HDFS connection handle, I am not sure if synchronization is required in this case.

**Comment by byronyi** [comment]
@yuanbopeng You need to add a mutex to guard the `connectionCache_`.

`std::map` is not thread safe and cannot be accessed from multiple threads without synchronization.

**Comment by yuanbopeng** [comment]
@byronyi Thanks for your suggestion, I will fix it now.

**Comment by vnvo2409** [comment]
@yuanbopeng 
Please leave the modular filesystem part for me. There is some other work to be done as well so I will make a PR to address this issue and those changes.

**Comment by yuanbopeng** [comment]
@vnvo2409 ok

**Pull request merged**
