### PR TITLE
remove unused test flags for arm builds

### PR DESCRIPTION
**Pull request by mseth10**
Removing `-nopip,-no_pip` flags as they are added by the pip_new.sh script https://github.com/tensorflow/tensorflow/blob/5e7c4a9fc98caee07b41d758d9648a72080f811b/tensorflow/tools/ci_build/builds/pip_new.sh#L185

### CODE REVIEW

**Comment by mseth10** [comment]
@nitins17  I originally created this PR to enable non pip tests. By apparently even after removing the `-nopip,-no_pip` flags, those tests are still skipped as these flags are added by the pip_new.sh script. I have a couple of questions: Does it make sense to run non pip tests for these pipelines? If yes, how can we enable them?

**Comment by nitins17** [comment]
The non-pip tests needs a separate Bazel invocation and would need to be run from the TensorFlow root directory. Here's the [script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/rel/ubuntu/cpu_py37_nonpip.sh) we used to use for running the non-pip tests. You can remove the `-no_oss_py3*` from the build script as [we don't use it anymore](https://github.com/tensorflow/build/blob/master/tf_sig_build_dockerfiles/devel.usertools/cpu.bazelrc#L53-L55).

**Comment by mseth10** [comment]
> The non-pip tests needs a separate Bazel invocation and would need to be run from the TensorFlow root directory. Here's the [script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/rel/ubuntu/cpu_py37_nonpip.sh) we used to use for running the non-pip tests. You can remove the `-no_oss_py3*` from the build script as [we don't use it anymore](https://github.com/tensorflow/build/blob/master/tf_sig_build_dockerfiles/devel.usertools/cpu.bazelrc#L53-L55).

I see. What's the difference between pip tests and non-pip tests? If our pipelines are meant to publish pip wheels, do we need to run non pip tests?

**Comment by nitins17** [comment]
For the pip tests, we need to build the wheel first and then the tests are run on the built wheel. Non-pip tests test the source code directly. I would recommend that both pip and non-pip are running because:
1.  They both are part of our complete test suite and would provide more evidence that everything is working as intended. 
2.  We run 1363 pip tests and 1975 nonpip tests and as part of our release approval pipeline, we make sure that both of them are green before releasing the wheels.

**Review by nitins17 — APPROVED** [review]

**Pull request merged**
