### PR TITLE
Fix typo in estimator with distribution strategy using hooks

### PR DESCRIPTION
**Pull request by nvcastet**
Fix typo while extracting estimator training hooks using distribution strategy.
CC @yuefengz

### CODE REVIEW

**Review by yuefengz — APPROVED** [review]

**Comment by nvcastet** [comment]
I signed it!

**Comment by byronyi** [comment]
Maybe this PR should be submitted against master, and then cherry-picked to r1.12?

**Comment by tatatodd** [comment]
@byronyi is right.  All PRs should be merged into master, rather than directly into the r1.12 branch.

@nvcastet please create a new PR for master.

**Comment by byronyi** [comment]
It got moved, but the code is still in the main repo master branch. I believe it will only be removed after the 2.0 release. 

But you might also need to submit a PR in tf_estimator repo.

**Comment by nvcastet** [comment]
@byronyi This code is not in repo anymore. Yes I will submit something for tensorflow_estimator repo too. But we would appreciate if this PR make it to 1.12.

**Comment by byronyi** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/estimator.py

**Comment by nvcastet** [comment]
@byronyi ok file came back 20h ok with rollback: https://github.com/tensorflow/tensorflow/commit/20f03388ac28fdf5ad33adb87d95346209ef0052#diff-17d893fed7bb36da99ce6c80d933d00b

**Pull request closed without merging**
