### PR TITLE
Implement L2Loss gradient.

### PR DESCRIPTION
**Pull request by bpiel**
This branch implements L2LossGrad, the gradient for L2Loss.
It is a port of the python implementation:
https://github.com/tensorflow/tensorflow/blob/c0198fd8d491a83576b75d1bc9becaa5910a19fe/tensorflow/python/ops/nn_grad.py#L752

This is my first PR to TensorFlow. When giving feedback, please assume that I barely know what I'm doing.

Side question: I plan to do a few more gradients. Is it ok if I batch a few simple ones (like this one) into a single PR?

### CODE REVIEW

**Comment by bpiel** [comment]
@suharshs Do you want to be pinged on PRs like this? (I don't have rights to assign)

**Review by suharshs — APPROVED** [review]
Thanks!

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
@gunan @yifeif for some reason, tests aren't triggering for this pull request (even after 3 attempts). It only runs the sanity checks.

**Comment by yifeif** [comment]
Looks like it just started https://ci.tensorflow.org/job/tensorflow-pull-requests-multijob/6594/. Jenkins is having a long queue now.

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by bpiel** [comment]
I merged master and now tests are passing again.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by bpiel** [comment]
The WIndows Cmake Tests aborted. Unrelated to the code changes?

https://ci.tensorflow.org/job/tensorflow-pr-win-cmake-py/4079/console
```
18:00:45 289/290 Test #205: C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/python/kernel_tests/tensordot_op_test.py .....................................   Passed  326.71 sec
19:25:20 Build was aborted
19:25:20 Aborted by unknown
19:25:20 [Set GitHub commit status (universal)] PENDING on repos [] (sha:4d472fa) with context:tensorflow-pr-win-cmake-py
19:25:20 Unable to get pull request builder trigger!!
19:25:20 Setting status of e5ac94c2c4f5002679f3cd1734ac1cdaebf2d090 to FAILURE with url https://ci.tensorflow.org/job/tensorflow-pr-win-cmake-py/4079/ and message: 'FAILURE
19:25:20  '
19:25:20 Using context: Windows Cmake Tests
19:25:21 Finished: ABORTED
```

**Comment by gunan** [comment]
The windows tests timed out after 30 minutes. We have been seeing this occasionally. Let's try again:
Jenkins, test this please.

**Comment by bpiel** [comment]
I wonder what happens if I type:
Jenkins, test this please

**Comment by bpiel** [comment]
Hmmmm.... doesn't trigger *ALL* the tests, I guess

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by bpiel** [comment]
I don't know what these failures mean.
https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/6532/console
```
Started by upstream project "tensorflow-pull-requests-multijob" build number 6653
originally caused by:
 GitHub pull request #12391 of commit 02a593886e5e1ac815bb887ac61417736cbd8564, no merge conflicts.
Setting status of 02a593886e5e1ac815bb887ac61417736cbd8564 to PENDING with url https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/6532/ and message: 'BUILDING'
Using context: Linux CPU Tests
[EnvInject] - Loading node environment variables.
Building remotely on cpu42-slave (slave cpu-slave) in workspace /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/tensorflow/tensorflow.git # timeout=10
Fetching upstream changes from https://github.com/tensorflow/tensorflow.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/tensorflow/tensorflow.git +refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/tensorflow/tensorflow.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:812)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1079)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1110)
	at hudson.scm.SCM.checkout(SCM.java:496)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1281)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/tensorflow/tensorflow.git +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1903)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1622)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:348)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:748)
	at ......remote call to JNLP4-connect connection from 118.56.196.104.bc.googleusercontent.com/104.196.56.118:47590(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
	at sun.reflect.GeneratedMethodAccessor380.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
	at com.sun.proxy.$Proxy83.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
	... 11 more
ERROR: Error fetching remote repo 'origin'
ERROR: [GitHub Commit Status Setter] - Cannot retrieve Git metadata for the build, setting build result to FAILURE
Unable to get pull request builder trigger!!
Setting status of 02a593886e5e1ac815bb887ac61417736cbd8564 to FAILURE with url https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/6532/ and message: 'FAILURE
 '
Using context: Linux CPU Tests
Finished: FAILURE
```

**Comment by gunan** [comment]
That is an infrastructure issue where our executors could not properly fetch information from github. We should retry.
Jenkins, test this please.

**Comment by bpiel** [comment]
try *again*?

**Comment by gunan** [comment]
Something is causing our builds on windows to get stuck. But as far as I can tell, this change is not causing an issue. OK to merge. We will investigate windows issues separately.

**Comment by bpiel** [comment]
@gunan Works for me, thanks!

**Pull request merged**
