### PR TITLE
Don't use __has_builtin with version of apple clang that doesn't supp…

### PR DESCRIPTION
**Pull request by DavidNorman**
This is a small fix to allow the clang compiler in OS/X El Capitan "Apple LLVM version 7.3.0 (clang-703.0.31)"  to compile the CRC acceleration code.

It is a fix for issue: https://github.com/tensorflow/tensorflow/issues/7223

### CODE REVIEW

**Comment by DavidNorman** [comment]
ok - maybe this isn't the correct fix.  doesn't work on apple clang 8.0.0 either.  there is obviously some sort of library that is meant to be linked in (clang compiler-rt or something)

**Comment by rmlarsen** [comment]
@DavidNorman do you want to close this one out while you investigate, or are you going to re-use this PR?

**Comment by DavidNorman** [comment]
no - i'm done now.  as far as I can tell, the problem exists on all apple compilers.  the fix assumes that the problem will have gone away by the next major compiler release.

**Comment by DavidNorman** [comment]
@rmlarson hi. I definitely want to have this patch pulled as is. Thanks.

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Review by vrv — APPROVED** [review]

**Pull request merged**
