### PR TITLE
TF Android Example first launch abnormal fix

### PR DESCRIPTION
**Pull request by Dayananda-V**
Demo application start after installation on android phone, permission screen request appears and activity close on background problem resolved with proper management of permission request.

### CODE REVIEW

**Comment by Dayananda-V** [comment]
@andrewharp 

Welcome for review and thanks.....

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrewharp: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrewharp: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrewharp: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrewharp: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrewharp: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 76 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrewharp: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 91 days with no activity and the `awaiting review` label has been applied.

**Comment by angersson** [comment]
@gbaned I'm afraid I don't know anything about the demo app, and @andrewharp is no longer on the team, IIRC. Can you find a more appropriate reviewer, please?

**Comment by gbaned** [comment]
@Dayananda-V could you please resolve the conflicts?

**Comment by Dayananda-V** [comment]
[Remove lite/examples/android example](https://github.com/tensorflow/tensorflow/commit/195678bf9930b878a008d72df573c44a4ca14f5e#diff-adb147fd1cd4e6bd657bcffbafbab670) as per this change, lite example move to [tensorflow-examples](https://github.com/tensorflow/examples). So closing this PR.

**Pull request closed without merging**
