### PR TITLE
Fix typo in image_ops_impl.py

### PR DESCRIPTION
**Pull request by sadiqj**
radomize -> randomize

### CODE REVIEW

**Comment by sadiqj** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
We will not be encouraging one liner grammatical changes as this is expensive process, thank you for your interest.
CC @mihaimaruseac

**Comment by sadiqj** [comment]
> We will not be encouraging one liner grammatical changes as this is expensive process, thank you for your interest.

Understood. Is there a simpler/cheaper process to suggest documentation fixes through?

**Comment by mihaimaruseac** [comment]
Please fix all typos in file/directory instead of one by one.

**Pull request closed without merging**
