### PR TITLE
Normalizing checkpoint path for Windows File System in Saver.py

### PR DESCRIPTION
**Pull request by Ather23**
https://github.com/keras-team/keras-tuner/issues/198

The hardcoded forward slash value for _SHARDED_SUFFIX broke on windows since the windows file system does not except forward slashes.

Solution:
Using os.path.normpath is going to normalize path relative to the OS

### CODE REVIEW

**Comment by Ather23** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
@Ather23  Can you please resolve conflicts? Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Will review again once conflict is solved

**Comment by Ather23** [comment]
Thank you for the feedback. I will resolve conflicts shortly.

**Comment by Ather23** [comment]
@mihaimaruseac @gbaned I have resolved the conflicts. Please review.
Thank you.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by Ather23** [comment]
A note on failing builds on Windows.

Based on my overview of the failing builds, the test function builds a path with a hard-coded train folder like so.
` @test_util.run_deprecated_v1
  def testNameCollision(self):
    # Make sure we have a clean directory to work in.
    with self.tempDir() as tempdir:
      # Jump to that directory until this test is done.
      with self.tempWorkingDir(tempdir):
        # Save training snapshots to a relative path.
        traindir = "train/"
        os.mkdir(traindir)`

image


Which results in the following dir path
` train/checkpoint_temp\part-00000-of-00001.data-00000-of-00001.tempstate11227093142142859221`
This is not going to work on Windows.

Notice that the checkpoint_temp has a \ in the end correctly which is within the scope of this fix.

The test functions also need to have a normalized path in order for them to be successful based on the OS.

Regardless of the failing build, I think this fix is going to run windows when the correct initial path is supplied.

**Comment by mihaimaruseac** [comment]
Let's remove the `/` at the end of `traindir` definition. All of the subsequent calls should be able to insert the proper path separator.

**Comment by Ather23** [comment]
@mihaimaruseac The `/` has been removed from traindir.

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Pull request merged**
