### PR TITLE
Added preprocessing and corrected example of RGB images before feeding rgb_to_yub

### LINKED ISSUE #37591: Example given in tf.image.rgb_to_yub is contadicting with the description.
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/image/rgb_to_yuv?version=nightly

## Description of issue (what needs changing):
(1) The example image `x` has pixel values which are not in the range of [0,1]. So, it can't be fed to `rgb_to_yuv` directly without scaling it.
(2) Users of the API need example which is close to practical scenario. In this case, nobody wants to see the values changed by the function but they want correct implementation and pre-processing example.

### Submit a pull request? 
Yes

### PR DESCRIPTION
**Pull request by ashutosh1919**
Fixes #37591 .
@mihaimaruseac - Please review.

### CODE REVIEW

**Review by mihaimaruseac — COMMENTED** [review]
The previous example is testable. I would keep it.

Thie new example combines multiple TF operations, probably needs explanation on what it does.

**Comment by mihaimaruseac** [comment]
Saw the issue. Let's try replacing the numbers in the existing example with numbers that match the preconditions and then let's also include the larger example you provided

**Comment by ashutosh1919** [comment]
@mihaimaruseac , Then please suggest what is best to do?

**Comment by ashutosh1919** [comment]
Ok let me try

**Comment by ashutosh1919** [comment]
@mihaimaruseac , I have changed back again. Is it okay now?

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
