### PR TITLE
variable name change and documentation clarification

### PR DESCRIPTION
**Pull request by jalammar**
Addressing #9927

### CODE REVIEW

**Review by ebrevdo — APPROVED** [review]
thanks!

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by drpngx** [comment]
Could you take a look at the `layers_test` failure?

```
======================================================================
ERROR: testSparsePartialFlatten (__main__.PartialFlattenTest)
Test `_inner_flatten` on `SparseTensor`s.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/bazel_pip/tensorflow/contrib/layers/layers_test.runfiles/org_tensorflow/bazel_pip/tensorflow/contrib/layers/python/layers/layers_test.py", line 1434, in testSparsePartialFlatten
    expected_indices, expected_values, _ = _sparsify(reshaped_random_)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/bazel_pip/tensorflow/contrib/layers/layers_test.runfiles/org_tensorflow/bazel_pip/tensorflow/contrib/layers/python/layers/layers_test.py", line 1399, in _sparsify
    values = array[non_zero]
IndexError: index 3 is out of bounds for axis 1 with size 3
```

**Comment by jalammar** [comment]
@drpngx I did. It's unrelated to the patch. It also occurred in a completely separate PR (https://github.com/tensorflow/tensorflow/pull/11012).

That error occurs occasionally depending on what random values were generated in the setup of ```testSparsePartialFlatten```. Specifically the ```random_ = np.random.rand(*shape)``` command
```
  def testSparsePartialFlatten(self):
    """Test `_inner_flatten` on `SparseTensor`s."""
    shape = [4, 3, 11, 6, 1, 3]
    np.random.seed(10301)
    random_ = np.random.rand(*shape)
    indices, values, _ = _sparsify(random_)
    ...
```


I isolated the test (https://gist.github.com/jalammar/e560aea1557ea12fec943762f32ab6eb) and ran it a few times. It fails about 40% of the time.

Running the test again would likely pass. But that test needs to be addressed as well.

**Comment by drpngx** [comment]
/CC: @yifeif if you know about the layers test.

**Comment by drpngx** [comment]
Thanks @jalammar !! Are you saying this needs a seed?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
OK, it looks like the layers test is a flake.

**Comment by jalammar** [comment]
@drpngx Thanks! 

Actually, upon further investigation, the culprit seems not to be the random value generation in testSparsePartialFlatten. It seems to be inconsistent behavior from numpy.where().

**Comment by drpngx** [comment]
Are you able to formulate a fix?

**Comment by jalammar** [comment]
@drpngx I reported the underlying issue to the numpy team. This second PR (https://github.com/tensorflow/tensorflow/pull/11069) is my attempt at fixing the test.

**Pull request merged**
