### PR TITLE
use `std::make_tuple` instead of non-empty braced-init-lists

### PR DESCRIPTION
**Pull request by njzjz**
Non-empty braced-init-lists cause some errors when I build from source. I don't know the exact reason. It may be related to my build tools, but the safest way is not to use non-empty braced-init-lists.
The error is:
```
external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc: In function ‘void stream_executor::LogPtxasTooOld(const string&, int, int)’:
external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:190:62: error: converting to ‘absl::lts_2020_02_25::container_internal::raw_hash_set<absl::lts_2020_02_25::container_internal::FlatHashSetPolicy<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int> >, absl::lts_2020_02_25::hash_internal::Hash<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int> >, std::equal_to<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int> >, std::allocator<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int> > >::init_type {aka std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int>}’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&, int&}; <template-parameter-2-2> = void; _Elements = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int}]’
   if (already_logged->insert({ptxas_path, cc_major, cc_minor}).second) {
```
https://github.com/google/jax/issues/6046#issuecomment-809613061 reported a same error.
Using `std::make_tuple` instead makes the error disappear.

### CODE REVIEW

**Comment by yisitu** [comment]
Out of curiosity, what was the error for cupti_tracer.cc?

Using `std::make_tuple` makes sense. FWIW I think another pair of curly braces will fix the compiler's confusion:
```diff
-  if (already_logged->insert({ptxas_path, cc_major, cc_minor}).second) {
+  if (already_logged->insert({{ptxas_path, cc_major, cc_minor}}).second) {
```

**Comment by njzjz** [comment]
It's a similar error in `cupti_tracer.cc` (sorry I didn't record the log). These lines work fine in v2.4.1 using `make_tuple`:
https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/core/profiler/internal/gpu/cupti_tracer.cc#L156-L232

And 60b9283c9e5308bae6fe19d2db531a6c230baffd breaks it. So I just reverted them.

**Comment by yisitu** [comment]
I think the changes from asm_compiler.cc (curly braces confuses a flat_hash_map of tuple) makes sense so +1 to the changes there. I think that is the same error as the JAX issue over at  https://github.com/google/jax/issues/6046#issuecomment-800439215.

However, regarding cupti_tracer.cc (curly braces for initializing tuple directly, no hash maps), it is not clear to me whether the changes fixes anything. Could we either revert cupti_tracer.cc here and isolate it into a separate PR? This way the asm_compiler.cc fix can go in first.

**Comment by yisitu** [comment]
By the way, thanks for the investigation + fix, @njzjz!

**Comment by njzjz** [comment]
Ok, I've reverted changes to `cupti_tracer.cc`. You are welcome!

**Review by yisitu — APPROVED** [review]

**Pull request merged**
