### PR TITLE
Fix a bug in ResolveConstantConcat

### PR DESCRIPTION
**Pull request by mohamedadaly**
Changes to fix a bug in ResolveConstantConcat whereby shared tensors are removed without checking if they are used in other operators in the graph.

### CODE REVIEW

**Comment by mohamedadaly** [comment]
I signed it!

**Comment by mohamedadaly** [comment]
now?

**Review by petewarden — APPROVED** [review]
Looks good, thanks Mohamed!

**Comment by mohamedadaly** [comment]
added irobot email to my account.

**Comment by rmlarsen** [comment]
@mohamedadaly Please resolve conflicts.

**Comment by mohamedadaly** [comment]
Conflicts resolved.

**Comment by rmlarsen** [comment]
@mohamedadaly I'm afraid a recent push introduced new conflict, please resolve again.

**Comment by mohamedadaly** [comment]
@rmlarsen Resolved again.

**Comment by rmlarsen** [comment]
@mohamedadaly Thanks!

**Comment by rmlarsen** [comment]
@mohamedadaly Thanks for the contribution!

**Comment by mohamedadaly** [comment]
Sure, you are welcome!

**Pull request merged**
