### PR TITLE
[LITE]concat_embeddings to concatenate_embeddings, todo change updated

### PR DESCRIPTION
**Pull request by siju-samuel**
A TODO updated, Rename CONCAT_EMBEDDINGS to CONCATENATE_EMBEDDINGS

`  // TODO(aselle): Consider rename to CONCATENATE_EMBEDDINGS	
`

### CODE REVIEW

**Review by zhenhuaw-me — COMMENTED** [review]
This may result failure to apps which built on top of TFLite and relying on op string. I suggest we pending this change.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@siju-samuel Could you please resolve the conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
