### PR TITLE
Add 6 layers of Octave Convolutions to tensorflow keras layers (issue author's implementation)

### PR DESCRIPTION
**Pull request by amascia**
Hi,
This pull request is an implementation of issue #37576 I'm the author of.
I implemented 7 classes of Octave Convolutions: 1 abstract OctaveConv layer, 5 octave convolution layers (OctaveConv1D, OctaveConv2D, OctaveConv3D, OctaveConv2DTranspose, OctaveConv3DTranspose) and 1 OctaveConvAdd class to add the octave convolution layers.
The reference paper and description of these features are given in the issue (#37576 ) so I invite you to look at it.
I also attached a python file to give you an example usage of OctaveConv2D, OctaveConv2DTranspose and OctaveConvAdd on the MNIST dataset.

PS. Pull request #38052 was opened a few days ago by another developer to fix the issue but it is incomplete (only 2 layers of octave convolutions) and has some bugs (for instance, setting the trainable attribute of the octave convolution layers won't freeze the weights) so I invite you to look at this pull request instead.

[AchilleMascia_mnist_octconv2D_2DTranspose.zip](https://github.com/tensorflow/tensorflow/files/4419653/AchilleMascia_mnist_octconv2D_2DTranspose.zip)

### CODE REVIEW

**Comment by AchilleMascia** [comment]
@googlebot I fixed it, I'm the only author of thir pull request

**Comment by gbaned** [comment]
@AchilleMascia Thank you for your contribution. Can you please sign CLA? Thanks!

**Comment by AchilleMascia** [comment]
It should be ok, isn't it?

AchilleMascia_CLA_signature

**Comment by AchilleMascia** [comment]
@googlebot I fixed it, it is signed. Waiting for the corporate CLA to be processed.

**Comment by qlzh727** [comment]
Thanks for the contribution.

Before we dive into details, I would like to have @fchollet as API owner to see if this is a good fit for the core Keras API. You might also want to check with tf-addons repository and it might be a better fit for this new extension.

**Comment by AchilleMascia** [comment]
Thank you for your feedback, I'll go along with whatever you think is the most appropriate for this feature.

**Comment by gabrieldemarmiesse** [comment]
I believe it's better for it to go in Addons first. If we see a very wide adoption, we can migrate it to core. I suggest closing this pull request and follow up at https://github.com/tensorflow/addons/pull/1782

**Comment by qlzh727** [comment]
Thanks Gabriel. Closing this PR for now and will follow up in addons.

**Pull request closed without merging**
