### PR TITLE
fixing documentation for tf.batch_to_space

### PR DESCRIPTION
**Pull request by vishalsubbiah**
issue #33354

fixing documentation so it is easier to read on the website. 
each step is not separated correctly : https://www.tensorflow.org/api_docs/python/tf/batch_to_space

### CODE REVIEW

**Comment by rthadur** [comment]
We will not be encouraging one liner grammatical changes as this is expensive process, thank you for your interest.
CC @mihaimaruseac

**Comment by mihaimaruseac** [comment]
Let's take this one as it improves website documentation

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
However, please make sure the Pr is against master, not 2.0

**Comment by vishalsubbiah** [comment]
@mihaimaruseac created a new pr at #33481 to be against master

**Pull request closed without merging**
