### PR TITLE
[tensorflow/compiler/jit/test_util.cc] Add calls to `reserve()` before populating vector

### PR DESCRIPTION
**Pull request by SamuelMarks**
https://github.com/tensorflow/tensorflow/pull/51739#issuecomment-940389562 told me to split the larger PR into one PR per file; thus this (thanks `bash`, `git` and `gh`!)

### CODE REVIEW

**Comment by SamuelMarks** [comment]
@gbaned @jpienaar Any issue with this PR?

**Comment by gbaned** [comment]
@jpienaar Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@jpienaar Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@jpienaar Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@jpienaar Can you please review this PR ? Thank you!

**Review by jpienaar — APPROVED** [review]
No objection inside jit/test_util, but I'm not owner of this code.

**Review by gbaned — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Closing stale PR. Please reopen if still needed and wanting to work on it.

**Comment by SamuelMarks** [comment]
@mihaimaruseac It's not stale, looking at master your latest commit to that file still is missing [`std::vector<T,Allocator>::reserve`](https://en.cppreference.com/w/cpp/container/vector/reserve): https://github.com/tensorflow/tensorflow/blob/92fc332/tensorflow/compiler/jit/test_util.cc#L30

**Pull request closed without merging**
