### PR TITLE
Fix typo in docstring

### PR DESCRIPTION
**Pull request by stmugisha**
`Input`s should be `Inputs` in the add_loss() docstring at tensorflow/python/keras/engine/base_layer.py

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
I don't think this is required. The class is called `Input`, not `Inputs`

**Comment by steph-en-m** [comment]
> I don't think this is required. The class is called `Input`, not `Inputs`

So it's just a redundant ```s``` in the docstring that should be removed right?

**Comment by mihaimaruseac** [comment]
There are multiple instances of class `Input`, so they get called "`Input`s"

**Comment by steph-en-m** [comment]
Okay i get it now.

**Pull request closed without merging**
