### PR TITLE
Dynamic Pywrap - Refactor pywrap_tensorflow_internal to load TF symbols from libtensorflow_cc.so

### PR DESCRIPTION
**Pull request by trevor-m**
This PR adds a new build configuration which is tentatively called `dynamic_pywrap`. When enabled, `_pywrap_tensorflow_internal.so` will no longer contain any implementation for TensorFlow and will instead dynamically depend on `libtensorflow_cc.so` to load those symbols. `_pywrap_tensorflow_internal.so` will now a lightweight binary only containing the python bindings and other code/APIs which depends on python.

## Goals of this PR

* Reduce binary size when building both python and C++ libraries. Currently, both libraries contain about ~800mb of the same code, which can now be shared using the approach in this PR.
* Improve parity between C++ and Python library. Many APIs, kernels, operators, grappler passes, etc. were not consistent between C++ and Python libraries since each library is a separate bazel target.
* Improve modularity by separating python bindings from TensorFlow core library implementation. This will have to be enforced going forward, otherwise duplication errors will occur.
* By separating the lightweight python bindings from the large TF implementation, it enables us to potentially build the python bindings for multiple python versions at once in order to build a non-version specific pip wheel.

## Implementation details

Dependencies of `pywrap_tensorflow_internal` were updated to only depend on **headers** from TensorFlow, to avoid duplicating the implementation which is already in `libtensorflow_cc.so`. There was a lot of TensorFlow implementation which was not yet in `libtensorflow_cc.so`, so those will now be moved to `libtensorflow_cc.so` by way of `//tensorflow/python:tensorflow_impl`.

Requires https://github.com/tensorflow/tensorflow/pull/55943 to fix a bug when building libtensorflow_cc.so

### CODE REVIEW

**Comment by trevor-m** [comment]
> Thank you for sending the PR! This is great work! What do you think about moving //tensorflow/python:tensorflow_impl from tensorflow/python/BUILD to tensorflow/BUILD?

Thanks for reviewing the PR! I agree with your suggestion.

**Comment by mihaimaruseac** [comment]
I would keep targets that only touch `tensorflow/python/...` files in `tensorflow/python/BUILD`, to ease layering and similar build tools

**Comment by gbaned** [comment]
@trevor-m Can you please resolve conflicts? Thank you!

**Review by learning-to-play — APPROVED** [review]

**Review by learning-to-play — APPROVED** [review]

**Review by learning-to-play — APPROVED** [review]

**Review by learning-to-play — APPROVED** [review]

**Review by learning-to-play — APPROVED** [review]

**Review by learning-to-play — APPROVED** [review]

**Review by learning-to-play — APPROVED** [review]

**Review by learning-to-play — APPROVED** [review]

**Review by learning-to-play — APPROVED** [review]

**Comment by joker-eph** [comment]
It seems that this configuration will quickly get obsolete by the migration to cc_shared_library (as far as I understand), is this correct?

If so: 
- Is this PR gonna help the migration in any way?
- Otherwise, I'm concerned about the added complexity and how it'll get in the way of the current migration (by having more select/if and an extra config to maintain).
-

**Comment by trevor-m** [comment]
> It seems that this configuration will quickly get obsolete by the migration to cc_shared_library (as far as I understand), is this correct?
> 
> If so:
> 
> * Is this PR gonna help the migration in any way?
> * Otherwise, I'm concerned about the added complexity and how it'll get in the way of the current migration (by having more select/if and an extra config to maintain).

Hi @joker-eph thanks for the comments.

The general idea of this configuration (having a light `pywrap_tensorflow_internal.so` which loads all TF symbols from `libtensorflow_cc.so`) is orthogonal to the migration to `cc_shared_library ` and has tangible benefits which we can benefit from now. The configuration would not go away after the migration.

On the other hand, you are correct that once `cc_shared_library ` is functioning properly, most of the changes in the PR would be unnecessary since all of the changes to use TF headers instead of implementation would be handled automatically. I can certainly understand this perspective to reduce complexity. I'm willing to refactor to use `cc_shared_library ` to greatly reduce the number of code changes, whether it comes after this PR is merged or before it I will leave up to you guys.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by joker-eph** [comment]
So what will remain after the migration to cc_shared_library? The fact that we're moving more code to libtensorflow_framework.so? 
cc_shared_library migration is intended to eliminate all of the code duplication between the .so, so I assume there shouldn't be a change in binary size right?

The last bullet of the intro about "potentially build the python bindings for multiple python versions at once" seems interesting though, but then will this be a different build configuration? Why wouldn't we make this the default instead of being behind a flag?

**Comment by trevor-m** [comment]
> So what will remain after the migration to cc_shared_library? The fact that we're moving more code to libtensorflow_framework.so? cc_shared_library migration is intended to eliminate all of the code duplication between the .so, so I assume there shouldn't be a change in binary size right?
> 
> The last bullet of the intro about "potentially build the python bindings for multiple python versions at once" seems interesting though, but then will this be a different build configuration? Why wouldn't we make this the default instead of being behind a flag?

`libtensorflow_framework.so` isn't changing from this PR. We are adding `libtensorflow_cc.so` into the python wheel and eliminating the redundancies between it and `pywrap_tensorflow_internal.so`. 

Currently, the dependencies for the python wheel look like:
````
other python bindings <- pybind11 modules
  | depends on
 V
pywrap_tensorflow_internal.so  <- all op/kernel definitions which are registered with libtf_framework, TF APIs + implementation, some pybind11 modules
  | depends on
 V
libtensorflow_framework.so
```

And the dependencies for the C++ shared library are a completely separate tree. The C++ library currently is only built if you explicitly build it 
````
libtensorflow_cc.so  <- all op/kernel definitions which are registered with libtf_framework, TF APIs + implementation
  |
 V
libtensorflow_framework.so
```

As you might notice, libtensorflow_cc and pywrap_tensorflow_internal are pretty much the same, except pywrap_tensorflow_internal has additional stuff for the python bindings.

The PR will fundamentally change these relationships, so that there is only one dependency tree. The C++ shared library will now always be built and used as part of the python library, and the redundancy between the C++ library and the python library is eliminated. The C++ library because a subset of the Python library. This is extremely valuable for those who are using both the C++ and python libraries because they are around 1GB each, so we are saving 1GB of disk space.

````
other python bindings --------------------------------|
 |                                                    |
 V                                                    |
pywrap_tensorflow_internal.so                         |
 |                                                    |-- TF Python Library
 V                                                    |
libtensorflow_cc.so -------------|                    |
 |                               |--- TF C++ library  |
 V                               |                    |
libtensorflow_framework.so ------|--------------------|
```

**Comment by joker-eph** [comment]
> The C++ shared library will now always be built and used as part of the python library, and the redundancy between the C++ library and the python library is eliminated. 

OK that sounds great to me! 
I have one more question that you missed I think: Why wouldn't we make this the default instead of being behind a flag? Is the flag only a temporary thing during the roll-out of this change?

**Comment by trevor-m** [comment]
> > The C++ shared library will now always be built and used as part of the python library, and the redundancy between the C++ library and the python library is eliminated.
> 
> OK that sounds great to me! I didn't entirely get this until you're last message, thanks for elaborating :)
> 
> I have one more question that you missed I think: Why wouldn't we make this the default instead of being behind a flag? Is the flag only a temporary thing during the roll-out of this change?

You are welcome! :)

You are right, I guess the flag is more of a temporary thing during the roll-out. I was mainly wary of the "monolithic build" so added the flag so that this change wouldn't affect the monolithic build - which appears to be used only for windows?

**Comment by gbaned** [comment]
@joker-eph Can you please assist on above comments from @trevor-m. Thank you!

**Comment by joker-eph** [comment]
I don't have anything more here, I think it's on @learning-to-play to see how to move forward I think?

**Comment by learning-to-play** [comment]
As I shared with @trevor-m, multiple presubmits are failing including Windows GPU, Windows Bazel GPU, and so on as you can see in the table above. You need to pass all the presubmits. Furthermore, because the change touches many different directories, multiple owners have to approve the code. Feel free to sync and make sure all the presubmits pass. I can check if all the internal tests pass and also help add all the reviewers here (currently some of the comments are only visible internally).

**Comment by trevor-m** [comment]
Hi @learning-to-play @joker-eph @mihaimaruseac 

I've just refactored the PR to use `cc_shared_library`. I've preserved the original approach here: https://github.com/trevor-m/tensorflow/tree/tmorris-dynamic-pywrap-original
The PR now depends on @learning-to-play's change to use `cc_shared_Library` in `pywrap_tensorflow_internal`. I will rebase once that is merged.

In the original approach, developers would need to carefully make sure every target in `pywrap_tensorflow_internal` did not depend on any TF implementation, otherwise it would be duplicated in both `libtensorflow_cc` and `pywrap_tensorflow_internal`. The targets must instead depend on headers from TF only.

In the new approach, as long as the target is listed in the `roots` attribute of `libtensorflow_cc`, bazel will automatically obtain that target for `pywrap_tensorflow_internal` through dynamic linking instead of duplicating it.

The new approach has much less changes so it should be easier to follow and review and will also have better maintainability. The list of exported targets in `roots` is currently very large since bazel does not consider transitive dependencies of targets in `roots`. Perhaps this example can serve as an argument to change `roots` to include transitive dependencies.

**Review by learning-to-play — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @trevor-m  Can you please resolve conflicts? Thank you!

**Comment by learning-to-play** [comment]
@gbaned Thank you for your follow up. Landing this PR is dependent on Bazel
5.3.0 release which is scheduled for Aug.

**Comment by gbaned** [comment]
Hi @trevor-m Can you please resolve conflicts? Thank you!

**Comment by trevor-m** [comment]
@learning-to-play I see that the prerequisite changes (https://github.com/tensorflow/tensorflow/commit/cc96e4ef758b23bb8b60ae7a1bd07f95674d0a7f) have now been merged.

I just rebased this PR; please let me know if there are any other changes I can make or issues that come up. Thanks!

**Comment by gbaned** [comment]
Hi @trevor-m Can you please resolve conflicts? Thank you!

**Comment by learning-to-play** [comment]
@angerson MacOS presubmits failed, but the "Details" link to see the logs is missing. Can you help fix this issue?

**Comment by nitins17** [comment]
> @angerson @nitins17 MacOS presubmits failed, but the "Details" link to see the logs is missing. Can you help fix this issue?

Sorry about this. I'm currently looking into this. In the meantime, here is the link to the [missing log](https://source.cloud.google.com/results/invocations/5344535e-2ce6-4b1f-b929-1ba72a25d56c/targets).

**Comment by nitins17** [comment]
> > @angerson @nitins17 MacOS presubmits failed, but the "Details" link to see the logs is missing. Can you help fix this issue?
> 
> Sorry about this. I'm currently looking into this. In the meantime, here is the link to the [missing log](https://source.cloud.google.com/results/invocations/5344535e-2ce6-4b1f-b929-1ba72a25d56c/targets).

This should be fixed now.

**Comment by trevor-m** [comment]
Thanks for sharing the log and fixing the missing link issue @nitins17!

@learning-to-play I have fixed the MacOS error which was specific to this PR (duplicate registration of master.proto), however it looks like there are still MacOS errors which are unrelated to this PR - I can see the same errors on other PRs.

**Comment by learning-to-play** [comment]
@trevor-m MacOS issue is resolved. Could you please resync your change?

**Comment by gbaned** [comment]
Hi @trevor-m Can you please resolve conflicts? Thank you!

**Comment by learning-to-play** [comment]
Hi @trevor-m, It seems the macOS build is still failing.

**Comment by trevor-m** [comment]
> Hi @trevor-m, It seems the macOS build is still failing.

Hi @learning-to-play, thanks for checking in. I'm currently working on fixing the Mac tests. I'll let you know when they are working again.

**Comment by trevor-m** [comment]
Hi @learning-to-play, the mac issues are fixed now :smile:.

**Comment by reedwm** [comment]
Unfortunately this was rolled back in 970c3b44ea8b0db78d92ada624f03aeacf2e4518 because it broke the TF serving build. @learning-to-play, can you debug this or triage?

**Comment by learning-to-play** [comment]
@reedwm Will be happy to debug or triage. Could you please provide some context for why this was rolled back, how to reproduce, and create some tests?

**Comment by reedwm** [comment]
Unfortunately I don't know much here other than that the internal CL is cl/483456888.

**Comment by karllessard** [comment]
@trevor-m , what is the status of this, looks like it has been only partially rolled back? Can we expect it to be back for 2.12 release?

At SIG JVM (who is maintaining [TensorFlow Java](https://github.com/tensorflow/java)), we would be VERY interested by this since our client relies on `libtensorflow_cc` and we have to build it ourselves as it is not being distributed independently from the `_pywrap_tensorflow_internal.so` in the PIP package.

Building `libtensorflow_cc` ourselves is a nightmare at each TF upgrade. For instance, we are blocked in our TF2.10.1 upgrade right now as the Windows build of that library seems broken. Just being able to retrieve and use the library from the Python wheels would be a charm.

(FYI, we don't use the `libtensorflow` (C API) anymore since it's lacking some features we need and its development does not seem to be a priority lately)

CC\ @craigacp

**Comment by trevor-m** [comment]
> @trevor-m , what is the status of this, looks like it has been only partially rolled back? Can we expect it to be back for 2.12 release?
> 
> At SIG JVM (who is maintaining [TensorFlow Java](https://github.com/tensorflow/java)), we would be VERY interested by this since our client relies on `libtensorflow_cc` and we have to build it ourselves as it is not being distributed independently from the `_pywrap_tensorflow_internal.so` in the PIP package.
> 
> Building `libtensorflow_cc` ourselves is a nightmare at each TF upgrade. For instance, we are blocked in our TF2.10.1 upgrade right now as the Windows build of that library seems broken. Just being able to retrieve and use the library from the Python wheels would be a charm.
> 
> (FYI, we don't use the `libtensorflow` (C API) anymore since it's lacking some features we need and its development does not seem to be a priority lately)
> 
> CC\ @Craigacp

Hi @karllessard , I'm really glad to hear of your interest. This PR is now fully merged via https://github.com/tensorflow/tensorflow/pull/58734. It should be available in the master branch of TF or the nightly builds. I expect it will be in the 2.12 release.

**Comment by learning-to-play** [comment]
@meteorcloudy @mihaimaruseac I think we should be able to use a similar shared library structure in Windows, too. Do you see any challenges? What was the reason for using monolithic build for Windows?

**Comment by joker-eph** [comment]
Windows shared libraries have a limited number of exported symbols I believe (64k?).

**Comment by karllessard** [comment]
Do we support custom op registration in Windows now or is this still not supported? I recall having a monolithic build was preventing this in the past but if something has been done to publish a `tensorflow_framework.dll` somehow then maybe we can do the same with `tensorflow_cc.dll`, the missing piece here? Can't we strip the unnecessary symbols?

**Pull request merged**
