### PR TITLE
Added drop_first feature to to_categorical

### PR DESCRIPTION
**Pull request by jaketae**
Pandas offers a `drop_first` argument as part of its [`get_dummies`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html) function, which is comparable to TensorFlow's `to_categorical`. `drop_first` allows users to drop the first column of their one-hot vectorized binary matrix, since the first dimension can be considered a form of extraneous information. Added this feature into the current version of `to_categorical`, alongside an example in the docstring.

### CODE REVIEW

**Review by mihaimaruseac — COMMENTED** [review]
This LGTM but will need API approval.

**Comment by alextp** [comment]
Why will the first dimension be considered extraneous information? I think this needs to be clarified in the docstring.

Isn't this better done by slicing the output tensor?

**Comment by jaketae** [comment]
@alextp Any one of the generated columns is extraneous because its values can automatically be inferred from the rest of the columns, *i.e.* a dummy is bound to be a linear combination of other columns. Therefore, dropping a column incurs zero loss of information. Links to relevant SO posts [here](https://datascience.stackexchange.com/questions/27957/why-do-we-need-to-discard-one-dummy-variable/27993#27993) and [here](https://datascience.stackexchange.com/questions/28353/always-drop-the-first-column-after-performing-one-hot-encoding).

It doesn't have to be the first column; it just so happens that other frameworks like Pandas offer this functionality by default, so I thought it would be a useful addition to the TF API. I can improve the docs if you think that would be necessary! Thanks for the input.

**Comment by guptapriya** [comment]
(for @tensorflow/api-owners )
We would like to keep the API surface small and since this can be achieved with a combination of existing APIs. We would like to keep things like this outside core TF in external libraries.

**Pull request closed without merging**
