### PR TITLE
[Intel MKL] Upgrading oneDNN to v2.1

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR upgrades oneDNN version to 2.1 and makes few required API changes. It also makes native format the default execution mode.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Comment by mahmoud-abuzaina** [comment]
@penpornk looks like the build is failing. We are not able to reproduce in our environment so far. We will continue trying on that. If you have any input, please let us know.

**Review by penpornk — CHANGES_REQUESTED** [review]
Could you please resolve the conflicts? Thank you!

**Comment by mahmoud-abuzaina** [comment]
I have resolved the conflicts. Thank you!

**Comment by mahmoud-abuzaina** [comment]
I also made the change to make both MKL and vanilla TF use the same oneDNN build.

**Comment by penpornk** [comment]
> I also made the change to make both MKL and vanilla TF use the same oneDNN build.

This one is risky of being rolled back. Let's make it a separate PR. 
You don't need to revert the new commit. I just won't reapprove the PR. :)

**Comment by penpornk** [comment]
@mahmoud-abuzaina Please open a new PR and mention me. I'll close this PR now since it is merged. :)

**Comment by penpornk** [comment]
This PR is rolled back in a253da7ebe03a34840020a2e526fca4819005115 because it broke the docker build. To reproduce:

- Run the TensorFlow CPU docker image. [Instructions here](https://www.tensorflow.org/install/source#cpu-only)
- Inside the container, go to the tensorflow source folder that have this v2.1 changes. Build with
```
yes "" | python3 configure.py
bazel build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=opt --config=v2 @mkl_dnn_v1//:dnnl_single_threaded
```
The error message:
```
ERROR: /root/.cache/bazel/_bazel_root/dd986257047f8a12e681831016f9a417/external/mkl_dnn_v1/BUILD.bazel:124:11: C++ compilation of rule '@mkl_dnn_v1//:dnnl_single_threaded' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 78 argument(s) skipped)
external/mkl_dnn_v1/src/cpu/x64/gemm/f32/jit_avx2_f32_copy_an_kern_autogen.cpp: In member function 'virtual void dnnl::impl::cpu::x64::jit_avx2_f32_copy_an_kern::generate()':
external/mkl_dnn_v1/src/cpu/x64/gemm/f32/jit_avx2_f32_copy_an_kern_autogen.cpp:29:6: internal compiler error: in equal_mem_array_ref_p, at tree-ssa-scopedtables.c:429
 void jit_avx2_f32_copy_an_kern::generate() {
      ^~~~~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target @mkl_dnn_v1//:dnnl_single_threaded failed to build
```

Once the problem is fixed, please create a new PR to bring this back. Thank you very much! :)

**Pull request closed without merging**
