### PR TITLE
Handle multiple channel audio files

### PR DESCRIPTION
**Pull request by astropeak**
Addresses [#22838](https://github.com/tensorflow/tensorflow/issues/22838).

The old code only works for single channel audio files. For a multiple channel audio file, there will be problems described in the issue.

This PR add handling for multiple channel audio files. Now the code works for both single and multiple channel audio files. But there is an open question in the implementation that need to be discussed: for a multiple channel audio file, it only export the first channel as a png file. I don't know if this is the behavior we want. Do we want to export each channel as a png file, or export all channel data as a single png file. Thanks!

### CODE REVIEW

**Comment by gbaned** [comment]
@petewarden  Hi, Can you please review this PR ?

**Comment by petewarden** [comment]
Can you add a test that fails before this PR is added, and is fixed by it, in tensorflow/core/kernels/spectrogram_test.cc? That would help document this functionality.

I'm happy to have just the first channel be written out to the PNG, since that's only for debugging purposes.

**Review by petewarden — CHANGES_REQUESTED** [review]
Can you add a test that fails before this PR is added, and is fixed by it, in tensorflow/core/kernels/spectrogram_test.cc? That would help document this functionality.

I'm happy to have just the first channel be written out to the PNG, since that's only for debugging purposes.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@petewarden Can you please take a look on this PR? Thanks!

**Comment by astropeak** [comment]
@petewarden Thanks for the comments, I will add a test case soon

**Comment by astropeak** [comment]
@petewarden can you help to create the expected output file for the attached wav file? The wav file has two channels, and is about 1s of music audio.

To add a new test case, I need to add a new wav file whose channel is 2.

In the README(tensorflow/core/kernels/spectrogram_test_data/README), it says:
The CSV spectrogram files in this directory are generated from the
matlab code in ./matlab/GenerateTestData.m
To save space in the repo, you'll then need to convert them into a binary packed
format using the convert_test_data.cc command line tool.

So I think I can't do it myself.

[short_test_segment_2.wav.zip](https://github.com/tensorflow/tensorflow/files/3587535/short_test_segment_2.wav.zip)

**Comment by MarkDaoust** [comment]
> Format using the convert_test_data.cc command line tool.  So I think I can't do it myself.

The tool code is here: 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/spectrogram_convert_test_data.cc

This build rule creating it:

https://github.com/tensorflow/tensorflow/blob/7829641a2a3083b091782e306c476de7cbf7bc25/tensorflow/core/kernels/BUILD#L5811

So if you're setup to build tensorflow from source this command might do it:

```
bazel run //tensorflow/core/kernels:spectrogram_convert_test_data -- <args>
```

There's also this file group you probably need to add it too:

https://github.com/tensorflow/tensorflow/blob/7829641a2a3083b091782e306c476de7cbf7bc25/tensorflow/core/kernels/BUILD#L5773

**Comment by astropeak** [comment]
> The CSV spectrogram files in this directory are generated from the
> matlab code in ./matlab/GenerateTestData.m

The problem is that I don't have the matlab tool that converts a wav file to a csv file, which is then fed to the 'convert_test_data.cc' tool.

**Comment by mihaimaruseac** [comment]
This is still missing tests

**Comment by gbaned** [comment]
@astropeak Can you please check mihaimaruseac's comments and keep us posted. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by astropeak** [comment]
I won't be able to work on this PR anymore. As said before, to add the test case, a matlab tool is required to generate the reference file. But that matlab tool seems an internal tool and is unavailable.
But anyhow I don't have time to work on this. Anyone interested in could continue working on this. If no one will work on this, maybe closing the PR will be an option.

**Pull request closed without merging**
