### PR TITLE
[INTEL MKL] MKL DNN v0.x cleanup - Reset MKL build config and remove DNN v0.x related macros

### PR DESCRIPTION
**Pull request by gzmkl**
This is the first PR for MKL DNN v0.x clean - for Tensorflow 2.4, only MKL DNN v1.x will be supported
   (1) Reset MKL DNN related build config (mostly in third_part/mkl or mkl_dnn folder)
   (2) Remove MKL DNN v0.x related macros in core/util/mkl_types.c
   (3) Minor code style fix in one MKL kernel op. 

There will be a sequence of PR's which will clean up all related MKL kernels ops.

### CODE REVIEW

**Review by penpornk — DISMISSED** [review]
I'm so sorry for the delay, and thank you very much for the cleanup!

**Comment by gzmkl** [comment]
Thank you!  
I will create a series of PR's to clean up all MKL kernel ops. For each op, remove 5-10% DNN 0.x code and replace MACRO's with actual DNN 1.x API's.

**Comment by penpornk** [comment]
Sounds good to me. Thank you for the heads up! :)

**Comment by gbaned** [comment]
@gzmkl  Can you please address Ubuntu Sanity errors? Thanks!

**Comment by gzmkl** [comment]
@gbaned. Hi, we just found that we (Intel) do not support "ngraph" (third_party/ngraph) any more. We will soon support a new PR to clean away ngraph related configuration setttings. Once that PR is merged. This one will pass sanity check. 

THANKS!  -GZ

**Comment by gzmkl** [comment]
@gbaned  I pushed a commit to fix ngraph build issue for this PR.  We will continue to submit a new PR to remove ngraph bridge. But this PR will not pend on it.   Thanks!

**Review by penpornk — APPROVED** [review]
Thank you for the fix!

**Pull request merged**
