### PR TITLE
update the py/py3 toolchain config

### PR DESCRIPTION
**Pull request by erain**
- The python3 are installed in `/opt/python3.6` in the base toolchain
container:
https://console.cloud.google.com/launcher/details/google/rbe-ubuntu16-04

- Also updated the corresponding python2 `numpy` library locations. 

- Both py2 and py3 config tested.

### CODE REVIEW

**Comment by erain** [comment]
+ @nlopezgi on reviewing python config changes.

**Review by nlopezgi — COMMENTED** [review]
Yu, can you double check that all TF builds are currently already switched to the latest container that has python available in the new location.

**Comment by erain** [comment]
@nlopezgi I've fond some internal builds are still using the old containers. I am sending CL internally to update them to use the latest container.

**Comment by yifeif** [comment]
@erain let us know when we are ready to proceed with this change. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by erain** [comment]
So sorry to miss this PR. With several CLs we submitted internally, I believe now this PR is ready to submit.

**Comment by nlopezgi** [comment]
@yifeif this PR can now be merged if possible. Thanks!

**Review by yifeif — APPROVED** [review]

**Pull request merged**
