### PR TITLE
Backport https://github.com/tensorflow/addons/pull/306 into master

### PR DESCRIPTION
**Pull request by sjmielke**
This is fixing the conditional in `tf.contrib.seq2seq.beam_search_decoder`'s `_check_static_batch_beam_maybe`, as reported in https://github.com/tensorflow/addons/issues/289 .

### CODE REVIEW

**Comment by ebrevdo** [comment]
If you want this in tf1.15, consider also submitting this patch to the r1.15 branch.

**Review by ebrevdo — DISMISSED** [review]

**Comment by sjmielke** [comment]
I suppose it's probably best to do that PR from upstream master (to upstream r1.15) instead of from my fork -- so that it really only needs to be reviewed this one time? :)

**Comment by mihaimaruseac** [comment]
Yes, let's get them in master first and then on r1.15.

Note: the `r1.15` cherry-pick windows closes soon.

**Comment by ebrevdo** [comment]
Looks like we missed the window; since contrib is no longer in master.  I suggest just pushing this to the tf 1.15 branch manually.  You'll still only need to have one PR, it just won't be to master...

**Comment by mihaimaruseac** [comment]
The window for 1.15 cherry-picks has also closed, unfortunately.

**Comment by ebrevdo** [comment]
Even for bugfixes?

**Comment by mihaimaruseac** [comment]
Unless we do a patch release for security vulnerabilities, no more changes are accepted into the branch as the release jobs for final are almost triggered.

**Pull request closed without merging**
