### PR TITLE
Branch 169299199

### PR DESCRIPTION
**Pull request by av8ramit**
I needed a file from master asap, so I thought I'd push.

### CODE REVIEW

**Review by caisq — APPROVED** [review]

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by caisq** [comment]
Looks like a flaky test failure of //tensorflow/core/distributed_runtime/rpc:grpc_session_test_gpu on mac:
https://ci.tensorflow.org/job/tensorflow-pull-requests-mac/6424/consoleFull

Testing again.

@tensorflow-jenkins test this please

**Comment by caisq** [comment]
It failed again. So this does look like a reproducible failure on mac now...

@mrry for insight. I'll also investigate which CL might be the culprit later.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
