### PR TITLE
add support for gcc byteoder defines to windows platform

### PR DESCRIPTION
**Pull request by guschmue**
needed to unblock https://github.com/tensorflow/tensorflow/pull/5450

### CODE REVIEW

**Review by mrry — APPROVED** [review]
LGTM, thanks!

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by gunan** [comment]
CPU failures known issues.

**Pull request merged**
