### PR TITLE
TensorFlow now builds with Bazel 1.0

### LINKED ISSUE #32835: TF doesn't build anymore with Bazel's --incompatible_remove_legacy_whole_archive
Some time ago we migrated Tensorflow to build with this flag flipped, but it regressed again (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1207#d1e5940d-bde3-46cd-8734-1b6f2fddabf5).

The incompatible flag: https://github.com/bazelbuild/bazel/issues/7362

I'm looking into it. This is a tracking issue for this effort :)

### PR DESCRIPTION
**Pull request by laszlocsomor**
Fix cc_library targets by adding 'alwayslink = 1'
so targets depending on them build with
--incompatible_remove_legacy_whole_archive, which
is enabled by default in Bazel 1.0.

Inspired by c3619ceb0200bc1eb9db7565e78bbf645e1f6cb0

Fixes https://github.com/tensorflow/tensorflow/issues/32835

### CODE REVIEW

**Comment by laszlocsomor** [comment]
ping

**Comment by mihaimaruseac** [comment]
I don't think `alwayslink = 1` is the right solution here. @meteorcloudy is working on enabling TF to build with Bazel 1.0.

**Comment by laszlocsomor** [comment]
> I don't think `alwayslink = 1` is the right solution here.

Can you explain why?

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
In this case approving. I was thinking that `alwayslink = 1` will result in more bloat in the binaries, but happy to be proven wrong and learn that it is useful. Thanks.

**Comment by meteorcloudy** [comment]
@laszlocsomor , I did a rerun with TF@HEAD, but the build failure doesn't seem to be fixed. 
https://buildkite.com/bazel/tensorflow/builds/3755

Are we missing anything?

**Comment by laszlocsomor** [comment]
Well this is embarrassing, but it seems I was actually using 0.26.1 because of the `.bazelversion` and because I used Bazelisk.

Looking into failures with the real Bazel 1.1.0 now, then again with Bazel 1.0.0. I'll keep this thread updated.

**Comment by laszlocsomor** [comment]
Fortunately, @scentini has also been working on this same issue and made far more progress than I did.

**Comment by timokau** [comment]
> Fortunately, @scentini has also been working on this same issue and made far more progress than I did.

Is that progress publicly available?

**Comment by flokli** [comment]
Also would be very interested in trying this out :-)

**Comment by scentini** [comment]
The commit in question is 52167ad. TF at HEAD currently builds with Bazel 1.0: https://buildkite.com/bazel/tensorflow/

There are still a couple of tests that are failing with Bazel 1.0, and I'm working on fixing them. Then, I will set --incompatible_remove_legacy_whole_archive to True in [.bazelrc](https://github.com/tensorflow/tensorflow/blob/master/.bazelrc), to prevent regression.

**Comment by timokau** [comment]
Is there some kind of hotfix one can apply to compile the current releases (1.15.0 and 2.0.0) with bazel 1.0?

**Comment by laszlocsomor** [comment]
@timokau : Can you patch https://github.com/tensorflow/tensorflow/pull/33415/commits/b4e690154f96a1242b4d5562cb8e59b1dcffe58b and https://github.com/tensorflow/tensorflow/commit/52167ad65887b4d5f433b719d9c3654e02daafd5 onto your source tree? I think that should do it.

**Comment by timokau** [comment]
@laszlocsomor unfortunately neither of those apply on the 1.15.0 or 2.0.0 trees. Is there any other option?

**Comment by laszlocsomor** [comment]
@timokau : Sorry, I'm not aware of any. Can you try resolving the merge conflicts? I just tried cherry-picking the commits onto r1.15: some conflicting targets don't yet exist (I deleted those), some files don't exist (deleted those too). There are some genuine conflicts too that I now cannot inspect closer, but the goal of these two cherry-picked commits was to add `alwayslink = 1` to `cc_library` rules that contain source files that define methods that the linker would strip without the `alwayslink`. So if you try building TensorFlow and the linker complains about missing functions, find the .cc files where they are defined, find the cc_library where those .cc files are in the srcs, and add `alwayslink = 1`. Hope that helps -- if you're still stuck, I can help again on Monday next week.

**Comment by timokau** [comment]
Yeah, unfortunately I'm still stuck. I've gotten this far with cherry-picks: https://github.com/timokau/tensorflow/commit/cec52a85a9de50c03840175458e8d05cc455e17f

But the build still fails with

```
bazel-out/host/bin/tensorflow/contrib/ignite/gen_gen_igfs_ops_py_wrappers_cc: symbol lookup error: /build/output/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/contrib/ignite/../../../_solib_k8/_U_S_Stensorflow_Scontrib_Signite_Cgen_Ugen_Uigfs_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined symbol: scc_info_DoubleValue_google_2fprotobuf_2fwrappers_2eproto
```

and I don't know where this symbol is coming from. Any help would be much appreciated from me and maybe also other distro maintainers.

**Comment by laszlocsomor** [comment]
@scentini: does this error look familiar?

**Comment by kgizdov** [comment]
@scentini @laszlocsomor  any idea which package causes this:
```
ERROR: /build/tensorflow/src/tensorflow-2.0.0/tensorflow/python/BUILD:2158:1: Executing genrule //tensorflow/python:parsing_ops_pygenrule failed (Exit 127)
bazel-out/host/bin/tensorflow/python/gen_parsing_ops_py_wrappers_cc: symbol lookup error: /build/.cache/bazel/_bazel_builduser/539918b59a0d8a3726d6fc114e247083/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/../../_solib_k8/_U_S_Stensorflow_Spython_Cgen_Uparsing_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined symbol: scc_info_DoubleValue_google_2fprotobuf_2fwrappers_2eproto
```
? from the log it points to something in `tensorflow/python` but not sure what.

**Comment by scentini** [comment]
Can you try patching [2d2d6cf](https://github.com/tensorflow/tensorflow/commit/2d2d6cffbda0fce31672beabffabb2dfacf76cd5) ?
The missing symbol is a protobuf one.
I'll share a list of all the changes we made regarding `--incompatible_remove_legacy_whole_archive` later today. Note that we are still encountering issues though.

**Comment by scentini** [comment]
Here it is:
[c3619ce](https://github.com/tensorflow/tensorflow/commit/c3619ceb0200bc1eb9db7565e78bbf645e1f6cb0)
[afb7639](https://github.com/tensorflow/tensorflow/commit/afb76393811a7e46ffab256c29116492bfd08e31)
[9760bc2](https://github.com/tensorflow/tensorflow/commit/9760bc2f6a657ca58019116062b96ac6c60f1b43)
[b4e6901](https://github.com/tensorflow/tensorflow/commit/b4e690154f96a1242b4d5562cb8e59b1dcffe58b)
[52167ad](https://github.com/tensorflow/tensorflow/commit/52167ad65887b4d5f433b719d9c3654e02daafd5)
[2d2d6cf](https://github.com/tensorflow/tensorflow/commit/2d2d6cffbda0fce31672beabffabb2dfacf76cd5)

Also, see https://github.com/tensorflow/tensorflow/pull/34044, not yet merged.

**Comment by timokau** [comment]
Thank you! Unfortunately with all those patches cherry-picked (to the best of my conflict-resolution ability), the build still fails:

```
ERROR: /build/source/tensorflow/compiler/tf2xla/ops/BUILD:25:1: Executing genrule //tensorflow/compiler/tf2xla/ops:gen_xla_ops_pygenrule failed (Exit 127)
[2,139 / 2,289] 3 actions running
    Compiling external/pcre/pcre_exec.c [for host]; 2s local
    Compiling external/pcre/pcre_compile.c [for host]; 0s local
    Compiling external/swig/Source/Modules/python.cxx [for host]; 0s local
bazel-out/host/bin/tensorflow/compiler/tf2xla/ops/gen_gen_xla_ops_py_wrappers_cc: symbol lookup error: /build/output/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/compiler/tf2xla/ops/../../../../_solib_k8/_U_S_Stensorflow_Scompiler_Stf2xla_Sops_Cgen_Ugen_Uxla_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined symbol: _ZN10tensorflow16ProtoDebugStringB5cxx11ERKNS_16DeviceAttributesE
[2,139 / 2,289] 3 actions running
```

Should I give up on trying to get 1.15 to build?

**Comment by kgizdov** [comment]
@scentini thanks. I managed to port the patches you listed. On `v2.0.0` it still fails with the following error:
```
ERROR: /build/tensorflow/src/tensorflow-2.0.0/tensorflow/python/BUILD:2212:1: Executing genrule //tensorflow/python:state_ops_pygenrule failed (Exit 127)
bazel-out/host/bin/tensorflow/python/gen_state_ops_py_wrappers_cc: symbol lookup error: /build/.cache/bazel/_bazel_builduser/539918b59a0d8a3726d6fc114e247083/execroot/org_tens
orflow/bazel-out/host/bin/tensorflow/python/../../_solib_k8/_U_S_Stensorflow_Spython_Cgen_Ustate_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined s
ymbol: _ZN10tensorflow16ProtoDebugStringB5cxx11ERKNS_16DeviceAttributesE
```
Is there an easy way of identifying which `cc_library` is the culprit, so that I can put `alwayslink = 1` accordingly? Cheers

**Comment by scentini** [comment]
Sometimes you can just search where the method is defined, and then find the cc_library that contains it. This case was tricky though, we managed to track it to [this](https://github.com/tensorflow/tensorflow/blob/aaa42634af9bdd316f65de64759ff31f42d97345/tensorflow/tensorflow.bzl#L2328) library. I sent out a PR internally to add `alwayslink=1`.

**Comment by timokau** [comment]
In case anybody else is interested in this, with [this patch](https://github.com/timokau/nixpkgs/blob/8e382a7ca71fdbb35efe037f1bb26e021408981d/pkgs/development/python-modules/tensorflow/tf-1.15-bazel-1.0.patch) I got the 1.15.0 build to work with bazel 1.1. Thanks @scentini!

**Pull request merged**
