### PR TITLE
[WIP] [tf.learn] API restructure

### PR DESCRIPTION
**Pull request by ilblackdragon**
API restructure to unify pieces and support a wider variety of models (such as multi head, unsupervised, etc)

Done:
- Estimator now uses `(features, targets, mode) -> (prediction, loss, train_op)`. Moved `optimize_loss` into `TensorFlowEstimator` (it's now a "simple" Estimator).
- Removed `classification` flag from Estimator.

Todo:
- Integrate BaseEstimator and Estimator.
- Add Classifier and Regressor subclasses.
- Make sure TensorFlowEstimator supports multi-feature.
- Integrate TensorFlowDNN/Linear with DNN/Linear Classifiers and Regressors.

CC @terrytangyuan @ispirmustafa @martinwicke

### CODE REVIEW

**Comment by martinwicke** [comment]
Pulling in.

**Comment by martinwicke** [comment]
See 123527855.

**Comment by terrytangyuan** [comment]
Awesome! So this will be included as part of internal branch merge later instead, right? @martinwicke

**Comment by martinwicke** [comment]
Yes. I will close this PR then. The skflow examples have to be adapted to
use the new DNNClassifier and DNNRegressor. If someone wants to do that on
top of this PR it will continue working when the internal code is merged
(hopefully later today). That's one of the major impediments to removing
the TensorFlowDNNEstimator,Regressor classes. As far as I can see at least,
Illia may know more.

**Pull request closed without merging**
