### PR TITLE
[tosa] Slice the input of kernel based ops to the actual used size

### PR DESCRIPTION
**Pull request by Tessil**
Hi,

This PR adds, if needed, a `tosa.slice` operator before kernel-based operators to ensure only the actual used size is passed as input to these operators so that the pre-condition on OH/OW is respected (example in [tosa.conv2d](https://www.mlplatform.org/tosa/tosa_spec.html#_conv2d)).

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @Tessil Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @Tessil Can you please resolve conflicts? Thank you!

**Comment by Tessil** [comment]
@jpienaar Would it be possible to reopen the PR? Thanks!

**Comment by jpienaar** [comment]
@Tessil could you update merge conflicts?

**Comment by Tessil** [comment]
@jpienaar Thanks, I merged the latest changes from upstream.

**Comment by Tessil** [comment]
Hi @jpienaar could you check if the PR looks good? We would ideally like it to be merged before the 2.14 branch cut if possible.

**Comment by gbaned** [comment]
Hi @Tessil Can you please resolve conflicts? Thank you!

**Comment by Tessil** [comment]
Thanks, I fixed the conflicts and added better support for dynamic shapes.

@rsuderman Could you have a look when you have some time? Thanks!

**Comment by gbaned** [comment]
Hi @rsuderman Can you please review this PR ? Thank you!

**Comment by yijie-yang** [comment]
Hi @jpienaar, could you help review this PR?

**Comment by gbaned** [comment]
Hi @jpienaar, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar, Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @Tessil Can you please resolve conflicts? Thank you!

**Pull request closed without merging**
