### PR TITLE
Raspberry PI example label image patch

### PR DESCRIPTION
**Pull request by metalalive**
In the Makefile, there were missing options that lead to compile / linking error :
* `absl` , according to [issue 22240](https://github.com/tensorflow/tensorflow/issues/22240)
* `nsync`, according to [issue12810](https://github.com/tensorflow/tensorflow/issues/12810)

Also in label_image.cc , there was an compile error as described in [issue 5200](https://github.com/tensorflow/tensorflow/issues/5200), the error can be solved if the included header `<stdio.h>` is moved before `<jpeglib.h>`.

The modified Makefile and label_image.cc is tested in my Raspbian Stretch 9 and GCC 6.3.0, it works well .

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @caisq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Review by petewarden — APPROVED** [review]

**Pull request merged**
