### PR TITLE
Add 3D operations for layers: conv3d, avg_pool3d, max_pool3d and conv3d_transpose.

### PR DESCRIPTION
**Pull request by Kongsea**
1.Fix a TODO(jbms):
change rate parameter to dilation_rate for consistency with underlying op.

2.Add 3D operations for layers:

- conv3d
- avg_pool3d
- max_pool3d
- conv3d_transpose

### CODE REVIEW

**Comment by ebrevdo** [comment]
This should be reviewed by someone with more experience with convolutional
operators.  Perhaps Sergio?

**Comment by martinwicke** [comment]
Conv3dTranspose exists in convolution.py now, can you rebase to use it?

**Comment by fchollet** [comment]
@Kongsea note that `Conv3DTranpose` has been introduced in `tf.layers` already: https://github.com/tensorflow/tensorflow/pull/8461#event-1004929500

So this CL does not have to modify `tf.layers` at all.

**Comment by Kongsea** [comment]
@martinwicke @fchollet I have seen it. However, you can ignore the commit [80a44db](https://github.com/tensorflow/tensorflow/pull/9404/commits/80a44db415fb74eab146c57dd6bf7d155720262a) now since this is similar with [#8461](https://github.com/tensorflow/tensorflow/pull/8461) and it has no influence with the other commits, so we don't need to do any modifications about them.

**Comment by fchollet** [comment]
@Kongsea please do rebase in any case.

**Comment by Kongsea** [comment]
@fchollet Please check if I have rebased it? I don't know how to rebase and I do it following the instructions of [this](https://anavarre.net/how-to-rebase-a-github-pull-request/).

**Comment by karandesai-96** [comment]
@Kongsea I checked your recent two commits, they have similar work to #8461. If you look at **layers/convolution.py**, you shall see two definitions of `Conv3DTranspose` class, because you rebased on latest master (after my PR was merged). There were no merge conflicts as they were simply additions.

To avoid duplicate definitions, you may run `git rebase -i master` by staying on your branch. It may open a text editor in the terminal and you'll see a list of these four commits. You can remove the recent two commits from that file and save it, your first two commits shall be retained while the ones with `Conv3DTranspose` code should be gone by now.

Alternatively, if you rebased just an hour ago and the master hasn't changed yet, you can run `git reset --hard HEAD~2` to remove your recent two commits and force push on this branch. But be cautious, do this step only if you haven't made a new commit locally after the rebase.

**Comment by Kongsea** [comment]
I am very sorry. I closed this pull request accidentally when I using git reset @karandesai-96 mentioned. I have to reopen a [new pull request](https://github.com/tensorflow/tensorflow/pull/9477). So please go there to discuss this features I added.

**Comment by Kongsea** [comment]
@fchollet @martinwicke @karandesai-96 Very sorry for my accident.

**Comment by martinwicke** [comment]
No problem at all. We'll continue on the new PR.

**Comment by karandesai-96** [comment]
Happened to me around a year ago, it usually happens when the base reference goes away. You get cautious stuff like this only after you face it for the first time :smile:

**Pull request closed without merging**
