### PR TITLE
[ROCm] Adding ROCm support for resource_variable_ops

### PR DESCRIPTION
**Pull request by deven-amd**
This PR adds ROCm support for resource_variable_ops

The changes in this PR are trivial, please review and merge...thanks.

-------------------------------------------------------

@tatianashp @whchung @chsigg

### CODE REVIEW

**Review by whchung — DISMISSED** [review]

**Review by chsigg — DISMISSED** [review]

**Comment by rthadur** [comment]
@deven-amd could you please resolve conflicts ?

**Comment by deven-amd** [comment]
@rthadur done.

**Review by whchung — APPROVED** [review]

**Review by chsigg — APPROVED** [review]

**Comment by deven-amd** [comment]
@rthadur 

this is the 1st of 4 PRs that seem to be stuck in the merge pipeline. 
Please let me know if there is anything that needs to be done on my end.
thanks

deven

**Comment by rthadur** [comment]
@deven-amd copybara could not pull in this changes , trying again now.

**Pull request merged**
