### PR TITLE
[ROCm] fix CSB build

### PR DESCRIPTION
**Pull request by jeffdaily**
Co-authored with @deven-amd.  This PR fixes recent failures in the Linux AMD ROCm GPU Nightly CSB build.  This PR does not depend on https://github.com/tensorflow/tensorflow/pull/32296, however that PR is also required before CSB build is successful again.

### CODE REVIEW

**Review by chsigg — DISMISSED** [review]

**Comment by jeffdaily** [comment]
@chsigg thank you for your earlier review approval.  Ubuntu Sanity test caught an error in our last commit, now fixed.  I hope you can review again soon.  Thanks.

**Comment by deven-amd** [comment]
@smit-hinsu can we get more information on why this PR was rolled-back? 

We need the changes in this PR to make ROCm CSBs pass. How do we go about getting this changes back in?

Thanks

deven

**Comment by smit-hinsu** [comment]
Sorry about the rollback without any details.

This was causing some integration test to fail internally. I don't understand the test so I have asked @chsigg to follow-up with you to help roll-forward the PR.

**Comment by deven-amd** [comment]
@chsigg, let me know how we can help out on our end. We would like to get this PR rolled back soon :)

@smit-hinsu, Is there any insight/detail you can provide on the nature of the failure. We now have 2 PRs (this one + PR #32296 )that are needed to get ROCm CSBs back to working status, and both of them are running into internal failures...would love to help resolve them in an expedient manner.

thanks

deven

**Comment by jerryyin** [comment]
Gentle ping @chsigg @smit-hinsu

**Comment by chsigg** [comment]
I will work on getting this rolled forward.

**Comment by chsigg** [comment]
The PR got rolled forward, but I had to disable the nccl_manager_test on ROCm completely (because the tag would have triggered on multi_gpu as well, and the test currently fails on CUDA). I hope this does unblock you though.

**Comment by jeffdaily** [comment]
Thank you @chsigg.  We're now unblocked to move on to the next community supported build failure.

Concerning the nccl_manager_test failing for CUDA, we did test #32296 on CUDA before creating the PR to make sure it would work for both ROCm and CUDA paths.  Please let me know how I can help unblock the nccl_manager_test.

**Pull request merged**
