### PR TITLE
Add .shape property to Variable object

### PR DESCRIPTION
**Pull request by yaroslavvb**
also adjust docstrings for consistency with Tensor.shape/Tensor.get_shape

### CODE REVIEW

**Comment by vrv** [comment]
If this acceptable, I'd suggest adding a test of the new property, at the very least.

**Comment by yaroslavvb** [comment]
I'll add tests if the API change goes through. The motivation for this is that Variables/Tensors are largely exchangeable and we had users confused to why "a.shape" fails for some a

**Review by yifeif — APPROVED** [review]
I dont know what's the formal procedures for PR API change review, but the change itself LGTM.

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Pull request merged**
