### PR TITLE
doc: update the conv1 shape.

### PR DESCRIPTION
**Pull request by lazyparser**
Update the conv1 shape from [5, 5, 32, 32] to [5, 5, 1, 32]. (`1` means gray image.)

Although this is irrelevant with the key content in the chapter, one might be confused when looking at this detail.

### CODE REVIEW

**Comment by drpngx** [comment]
@MarkDaoust WDYT?

**Comment by MarkDaoust** [comment]
It's reasonable for the example model to start with a 1 channel image.

But this `variable_scope.md` doc was just merged into `variables.md`, so accepting this now would just set us up for a merge conflict when the sync happens.

If you want to update `variables.md` after the sync, that's fine with me.

**Comment by lazyparser** [comment]
Got it. Thank you. I'll update this PR after sync.

**Comment by lazyparser** [comment]
rebased.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by drpngx — APPROVED** [review]
As per Mark's comment.

**Pull request merged**
