### PR TITLE
Integrating cuBLASLt into XLA

### PR DESCRIPTION
**Pull request by philipphack**
Adds support for the cuBLASLt library for GEMM operations to XLA. The library can be activated by setting the XLA flag `xla_gpu_enable_cublaslt=true`.

Attn: @SandSnip3r

### CODE REVIEW

**Review by SandSnip3r — APPROVED** [review]

**Comment by SandSnip3r** [comment]
@philipphack It was again confirmed that this change caused drastically increased memory usage (out-of-memory errors). We are investigating.

**Comment by SandSnip3r** [comment]
@philipphack As found by someone else, the suspicion is that the code seems to be restructured so that memory assignments in `gemm_algorithm_picker.cc` are done even if there is a cache hit in `DoGemmAutotune`. Looking at the code, previously, we used to check the cache before allocating this lhs_buffer, rhs_buffer, etc. Now, we always allocate them, then check the cache afterwards. Whatever usecase was triggering this out-of-memory error was seeing an accumulated allocation from this part of the code with no matching frees.

**Comment by philipphack** [comment]
@SandSnip3r I changed `DoGemmAutotune` and opened PR 55518. Can you take a look?

**Comment by SandSnip3r** [comment]
> @SandSnip3r I changed `DoGemmAutotune` and opened PR 55518. Can you take a look?

Yeah, I see it. I'll check it out. Thanks.

**Pull request merged**
