### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by apeltop**
I hope it helps.

### CODE REVIEW

**Review by bhack — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Can you try to fix multiple typos in the same file/directory please? As you see, the CI time is significant (and this is ~1/3rd of the total CI if we take into account the internal CI too). We're trying to minimize the hours_of_ci/delta_of_change metric

**Comment by apeltop** [comment]
Thank you for telling me. I'll try to find it.

**Comment by apeltop** [comment]
I'll look for a little more

**Review by mihaimaruseac — APPROVED** [review]
Thank you very much!

**Comment by apeltop** [comment]
I found a little more, so please stop CI

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
