### PR TITLE
Updated image_ops_impl.py

### PR DESCRIPTION
**Pull request by tiruk007**
Fix for #58703 and please find the gist [here](https://colab.research.google.com/gist/tiruk007/06aae2e97f70571eebde88d8b0703bbe/58703.ipynb) for  reference.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @cantonios Can you please review this PR ? Thank you!

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
I don't think we need to document this. This is likely a bug in XLA if support is missing.

**Comment by cantonios** [comment]
@wangpengmit do you have any more context here?  I seem to remember seeing such errors/descriptions elsewhere in the codebase.

**Comment by gbaned** [comment]
Hi @wangpengmit Can you please check @cantonios's [comments](https://github.com/tensorflow/tensorflow/pull/58725#issuecomment-1370000094) and keep us posted ? Thank you!

**Comment by gbaned** [comment]
Hi @wangpengmit Any update on this PR? Please. Thank you!

**Review by wangpengmit — APPROVED** [review]

**Comment by wangpengmit** [comment]
I checked today and found that int64 seeds are still unsupported by the TF2XLA bridge. If you use int64 seeds, the higher 32bit will just be ignored because of https://github.com/tensorflow/tensorflow/blob/754b3df1dd4d928063e9399a86a3e6209d79e9ff/tensorflow/compiler/tf2xla/kernels/stateless_random_ops_v2.cc#L563
But @mihaimaruseac said we shouldn't document this missing TF2XLA coverage. I don't have a strong opinion on this documentation question.

**Pull request merged**
