### PR TITLE
Make CMake on TensorFlow Incrementally Compile on Windows (#14194)

### PR DESCRIPTION
**Pull request by brunomorishita**

### CODE REVIEW

**Comment by brunomorishita** [comment]
I signed it!

**Comment by brunomorishita** [comment]
@headupinclouds I would like to use your commit on my pull request. Is that ok to you?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 50 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 65 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 80 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 95 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yifeif** [comment]
@brunomorishita, @headupinclouds is this PR still WIP?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rthadur** [comment]
@brunomorishita  wondering if you still need this PR , if yes can you please resolve conflicts

**Comment by brunomorishita** [comment]
> @brunomorishita wondering if you still need this PR , if yes can you please resolve conflicts

Hi @yifeif,
I don't need this PR anymore

**Pull request closed without merging**
