### PR TITLE
fix TFOpLambda name for KerasOpDisparcher

### LINKED ISSUE #43840: regression in layer names for tf-operation layers in current tf-nightly (2.4)
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0-dev20201006
- Python version: 3.7

**Describe the current behavior**
In the last tf-nightly release, when attributing a name to a layer created by a tf operation, this naming does not seem anymore to be effective anymore. 

**Describe the expected behavior**
the naming of the layer shall work as expected, as for tf 2.3

**Standalone code to reproduce the issue**
```
import tensorflow as tf
print(tf.__version__)

test = tf.keras.Input((1,), name='input1')
test2 = tf.identity(test, name='abcd')
print(test.name)
print(test2.name)
```

**Other info / logs** 
```
2.4.0-dev20201005
input1
tf.identity/Identity:0
```

### PR DESCRIPTION
**Pull request by bhack**
Try to fix https://github.com/tensorflow/tensorflow/issues/43840

### CODE REVIEW

**Comment by bhack** [comment]
@scd75 The test are failing. I see that they name was specifically removed with this claim https://github.com/tensorflow/tensorflow/blob/f718b7fd197836e335a69844dfec4e2c2ef2a615/tensorflow/python/keras/layers/core.py#L1340-L1344 /cc @tomerk

**Comment by scd75** [comment]
Well I guess that is a big change triggering many issues. Does that mean that the "name" parameter in all tf-op layers constructors become useless??
I guess the solution to the original issue would rather be to fix the way tf-ops are automatically named (to make sure they are uniquely identified), rather than totally getting rid of the "name" attribute which is very useful in many cases (and which I guess is widely used)

**Comment by bhack** [comment]
I am trying to compile this locally to run tests. But as always it is a quite heavy a long process without a [fresh cache](https://github.com/tensorflow/build/issues/5)

**Comment by tomerk** [comment]
I've replied on issue #43840 and you can find more info about the functional API refactoring in the release notes:
https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

The names of individual ops in the graph generated by a Keras model should not be considered load-bearing, and we have never made guarantees about them. If we did it would prevent us from making any change to Keras layers that alters the actual ops in the TF graph that we generate. That would prevent us from making all sorts of performance improvements, bug fixes, or code cleanups.

*If* your use case is that you need to identify the generated TFOpLambda layer by its name and the auto-incrementing names aren't sufficient for you then we can explore alternative ways of allowing users to explicitly override the name of the auto-generated layer. But we'd need to understand why you treat the op names generated by tf op layers in a load-bearing way to see what changes/features would even make sense.

**Comment by bhack** [comment]
@tomerk What what it will be the role of of `name` param in the ticket?
`tf.identity(test, name='abcd')`

**Comment by tomerk** [comment]
In the linked issue, because `test` is a keras input (which mimics a tensor) rather than actual tf.Tensor, it will create an op layer in the functional model that calls `tf.identity`.

Generally when called on standard tensors, `tf.identity` uses the name argument to set the names of any ops in the graphs it creates.
But, when we create op layers we have to drop the name argument because if the op layer is reused *and* it passes the same `name` arg to `tf.identity` each time it tends to create multiple ops in the same graph that have the exact same name. This is unsupported and causes an error to be raised.

So, in the specific `tf.identity(test, name='abcd')` call from the ticket `name` will remain completely unused.

The more important question here is *why* is name being set to `abcd`, and what is the user (in this case @scd75 ) hoping to get by having the `name` arg reflected in the ops generated by the Keras model? E.g. is it a slightly more interpretable tensorboard graph? Is there code that is trying to directly manipulating nodes in the graph that ends up treating names as load-bearing? etc.

**Comment by tomerk** [comment]
E.g, there are things we could to that set `name` as the name of the layer we generate (even though we would still drop `name` before calling the actual tf.identity when running the layer). This would help if the user just cares about identifying the layer w/o using the auto-incremented names, but it wouldn't help if the user is looking to maintain exact compatibility for pre-existing code that treats graph node names in a load-bearing way.

**Comment by bhack** [comment]
@tomerk I understand the logic but by an API usability point of view it is not so good to have a parameter that it is more or less silently ignored or at least we could raise a Warning.  
I don't think that the proposed `abcd/Identity:0` it is more consistent but could give a role to the name param.

**Comment by scd75** [comment]
Thanks for the reply and detailed explanation on #43840 @tomerk .
To clarify my use case: I treat some input features differently in my model. Each of those (named) features in the input dataset in mapped to a different keras Input layer whose is named after the feature name.
I then perform several preprocessing operations on those input layers (which differ depending on the feature), and I end up naming the resulting tensor through the use of a tf.identity layer, which I name "preprocessed_{feature_name".

in the rest of the model, I am then able to apply different subsequent operations for each preprocessed feature, depending on their name, by relying on the "name" attribute of the preprocessed input tensors.
But maybe there is a better way to do it.. I just found it easy and quite clean to carry over the feature name all along the process, from the very first Input layer, to the entry of the rest of the model.

**Comment by gbaned** [comment]
@tomerk Can you please take a look on above comments from @bhack, @scd75. Thanks!

**Comment by tomerk** [comment]
Thanks all for your thoughts! Response to the comments above:

> by an API usability point of view it is not so good to have a parameter that it is more or less silently ignored or at least we could raise a Warning.
Yeah, I definitely agree with this in principle.
But, the key point here is the `tf.Identity` api on actual tensor values *already does* behave that way (hence why it has the `name` argument), while Keras's op layer conversion is a *best effort* attempt to emulate the behavior of the tf apis it traces (but w/o making any guarantees about naming because the simple act of packaging things into layers will change the name scoping / alter the tensor naming semantics).

When we ran various experiments across all of our internal google users of Keras to see what would pose the lowest risk to users, we found that it was safer to blanket-disable the `name` argument than to always leave the `name` argument in.
The few cases where the name change broke code were generally just unit tests that checked for an exact output name to make sure a layer was used, which could easily be fixed to expect a different name or to check the model layers directly.

On the other hand there were a number of cases that started running into breakages if we left `name` in because some tf apis directly pass a name to an op that eventually gets converted to a layer, which then breaks as soon as you used that api multiple times in one model. (One example is some of the various tensor binary operators if I recall correctly)

-------------
I will say that it's possible we could identify which exact apis it's safe to leave `name` for and which it's not, and then it could behave slightly more like before. We don't have the bandwidth to safely do this analysis though, it would add complexity to the code, and because things get auto-wrapped in layers it might not even match your naming expectations anyway (and naming isn't part of the Keras op layer api spec so it's prone to change anyway)

---------------
@scd75 it sounds like you fall into the case of needing to know what layers were applied? The way we handled this in the internal cases I mentioned above is by building a temporary model w/ the tensor you're checking as your model output, and then checking `model.layers` for the presence of of specific layers (by type or by name).

**Pull request closed without merging**
