### PR TITLE
Fix tf32 for real.

### PR DESCRIPTION
**Pull request by reedwm**
I thought I fixed this in https://github.com/tensorflow/tensorflow/pull/40957, but when I fixed the build error on Windows, I inadvertently caused tf32 to stop working again.

### CODE REVIEW

**Comment by reedwm** [comment]
Ugh I still fail Linux CPU and MacOS CPU. I tested Windows CPU and Linux GPU and assumed that would be enough.

I will take a look tomorrow.

**Comment by av8ramit** [comment]
Are the failures related? Might be broken at HEAD. I'll force a rerun.

**Comment by av8ramit** [comment]
So just to clarify, you're moving the dependency to if_static, but what if the user accesses the API from open source? What is the expected behavior?

**Comment by reedwm** [comment]
The expected behavior is the API is always accessible and there is one copy of the global variable. In the static case, it will directly be linked in. In the dynamic case, it will be linked in libtensorflow_framework but not any pywrap_tensorflow_internal or any other shared libraries.

I think I fixed the issue, but we will see :)

**Review by av8ramit — APPROVED** [review]

**Pull request merged**
