### PR TITLE
[tosa] legalize tfl.fully_connected to tosa.conv2d

### PR DESCRIPTION
**Pull request by Tai78641**
This patch changes legalization of tfl.fully_connected to tosa.conv2d instead of tosa.fully_connected

### CODE REVIEW

**Comment by rsuderman** [comment]
> This patch changes legalization of tfl.fully_connected to tosa.conv2d instead of tosa.fully_connected

Can you explain why this is preferred over matmul? From a computational standpoint a matmul and bias add seem more correct.

**Comment by Tai78641** [comment]
> > This patch changes legalization of tfl.fully_connected to tosa.conv2d instead of tosa.fully_connected
> 
> Can you explain why this is preferred over matmul? From a computational standpoint a matmul and bias add seem more correct.

Matmul + add would have following shortcomings:
- To use MATMUL we would need to transpose the second matrix
- MATMUL does not support asymmetric types (like int16 x int8) allowed by FULLY_CONNECTED
- Bias addition for 48 bit accumulator (eg 16x8 operation) would require a 48-bit ADD which would be a new operation

**Comment by gbaned** [comment]
Hi @rdzhabarov Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @Tai78641 Can you please resolve conflicts? Thank you!

**Comment by Tai78641** [comment]
> This PR is stale because it has been open for 14 days with no activity. It will be closed if no further activity occurs. Thank you.

resolved conflicts

**Comment by Tai78641** [comment]
@NatashaKnk would you help review this?

**Comment by NatashaKnk** [comment]
The code itself looks good, but I'm a bit concerned about this approach. From a clarity standpoint this seems confusing -- The first point of conversion between tfl and tosa should probably be as close of a 1:1 mapping we can get. Happy to review it as a later-on pass though.

**Comment by Tai78641** [comment]
the motivation for this PR is that we want to deprecate tosa.fully_connected operator.
before we can do that, we wanted to remove its use in tf/tfl loweing to tosa, so that we wont break tf/tfl
when we removed tosa.fully_connected as an op. Therefore this PR.

**Comment by NatashaKnk** [comment]
I think if fully_connected is being depricated, it's reasonable to expect that matmul would be able to pick up everything it was able to do before deprecation. It can later be converted into conv2d for optimization purposes, but mapping ftl directly to conv2d seems a bit hacky and confusing to me.

**Comment by Tai78641** [comment]
The reasons we did not lower to Matmul (followed by an Add), are:

- To use MATMUL we would need to transpose the second matrix
- MATMUL does not support asymmetric types (like int16 x int8) allowed by FULLY_CONNECTED
- Bias addition for 48 bit accumulator (eg 16x8 operation) would require a 48-bit ADD which would be a new TOSA operation

thats why we chose the implementation in this PR

**Comment by NatashaKnk** [comment]
I understand why this is the best approach with the existing set-up, I'm just not sure that looking at this PR in isolation is the best way to go about this. If there is no way to support existing fully_connected behavior through an op that is a reasonable default mapping of that op (which I don't consider Conv2D to be), the reasons for/approach to deprecation should be looked at.

**Comment by gbaned** [comment]
Hi @Tai78641 Can you please resolve conflicts? Thank you!

**Comment by Tai78641** [comment]
> Hi @Tai78641 Can you please resolve conflicts? Thank you!

done

**Comment by sjarus** [comment]
> I understand why this is the best approach with the existing set-up, I'm just not sure that looking at this PR in isolation is the best way to go about this. If there is no way to support existing fully_connected behavior through an op that is a reasonable default mapping of that op (which I don't consider Conv2D to be), the reasons for/approach to deprecation should be looked at.

One of the reasons that tosa.conv2d is preferable is that fully_connected may include a bias addition. In the integer domain this potentially requires a tosa.add with a 48-bit operand, which is unsupported. 

The conv2d op conveniently lets us encode bias addition as an operand. Matmul typically does not have a bias addition construct. Since fully_connected is a degenerate form of conv2d within this view, it makes sense to deprecate it and replace it with a tosa.conv2d. 

In other circumstances fully_connected could indeed map to tosa.matmul (we're adding a new parameter to tosa.matmul to define accumulator width), but right now tosa.fully_connected is intended to be expressed as a conv2d instead. It's possible to implement a tosa-tosa transform beneath it that decomposes the conv2d to a matmul.

**Review by jpienaar — APPROVED** [review]

**Pull request merged**
