### PR TITLE
Fix int64 failure on GPU for TensorArray

### LINKED ISSUE #22054: map_fn gives colocation errors with integer typed input tensors
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
CentOS Linux release 7.4.1708
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:
binary (pip3 install tensorflow-gpu==1.9.0)
- **TensorFlow version (use command below)**:
v1.9.0-0-g25c197e023 1.9.0
- **Python version**:
3.6.4
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
9.0.176
- **GPU model and memory**:
 GeForce GTX-1080 - 8GB memory
- **Exact command to reproduce**:
`python3 map_fn_GPU_error.py`

### Describe the problem
The `tf.map_fn` function raises the following error if I provide two tensors of input one of which is `tf.float32` and the other `tf.int64`. This error doesn't appear if both of them are `tf.float32`.

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'map/TensorArray_1': Could not satisfy explicit device specification '' because the node was colocated with a group of nodes that required incompatible device '/device:GPU:0'
Colocation Debug Info:                                                                                                     
Colocation group had the following types and devices:
TensorArrayReadV3: CPU                                                                                                    
Enter: GPU CPU                                                                        
TensorArrayV3: CPU                         
TensorArrayScatterV3: CPU                                                                                                                                      
Placeholder: GPU CPU                                                                                   
                                                           
Colocation members and user-requested devices:                   
  RaggedLengths (Placeholder) /device:GPU:0
  map/TensorArray_1 (TensorArrayV3)                                                                                                                            
  map/TensorArrayUnstack_1/TensorArrayScatter/TensorArrayScatterV3 (TensorArrayScatterV3) /device:GPU:0
  map/while/TensorArrayReadV3_1/Enter (Enter) /device:GPU:0
  map/while/TensorArrayReadV3_1 (TensorArrayReadV3) /device:GPU:0
                                                  
         [[Node: map/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_INT64, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name=""](map/strided_slice)]]
                                                                                                                            
Caused by op 'map/TensorArray_1', defined at:
  File "map_fn_GPU_error.py", line 33, in <module>                                                                              
    dtype=tf.float32)                                      
  File "/my/python/package/path/tensorflow/python/ops/functional_ops.py", line 420, in map_fn    
    for elem in elems_flat]                    
  File "/my/python/package/path/tensorflow/python/ops/functional_ops.py", line 420, in <listcomp>                               
    for elem in elems_flat]                      
  File "/my/python/package/path/tensorflow/python/ops/tensor_array_ops.py", line 754, in __init__
    name=name)                                                           
  File "/my/python/package/path/tensorflow/python/ops/tensor_array_ops.py", line 160, in __init__         
    self._handle, self._flow = create()            
  File "/my/python/package/path/tensorflow/python/ops/tensor_array_ops.py", line 157, in create                                 
    name=scope)   
  File "/my/python/package/path/tensorflow/python/ops/gen_data_flow_ops.py", line 7157, in tensor_array_v3
    tensor_array_name=tensor_array_name, name=name)                  
  File "/my/python/package/path/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)                                                                    
  File "/my/python/package/path/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)                                                                                                                                             
  File "/my/python/package/path/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access    

```
This is triggered by the line
`sess.run(tf.global_variables_initializer())` in the code below. This code works perfectly on CPU however, I cannot seem to force placement on the GPU.

### Source code / logs

This is a minimal example to reproduce the above error. (This is the file named `map_fn_GPU_error.py` used in the command above)

```python
import tensorflow as tf
import numpy as np

with_gpu = True
if with_gpu:
    device_name = '/device:GPU:0'
else:
    device_name = '/device:CPU:*'

batch_size = 32
max_ragged_dim = 10
embedding_dim = 20


def ragged_function(ragged_input, length_of_input):
    # length_of_input is not used here but is in the actual function
    # The error is caused whether or not it is used
    return tf.reduce_sum(ragged_input, axis=0)


def final_loss_function(ragged_function_outputs):
    weights = tf.get_variable('LossWeights', dtype=tf.float32,
                              shape=(ragged_function_outputs.shape[1], 1))
    return tf.reduce_sum(tf.matmul(ragged_function_outputs, weights))


with tf.device(device_name):
    input_ragged_mat = tf.placeholder(name='RaggedMatrix', dtype=tf.float32,
                                      shape=(None, max_ragged_dim, embedding_dim))
    input_ragged_lengths = tf.placeholder(name='RaggedLengths', dtype=tf.int64,
                                          shape=(None,))

    ragged_function_outputs = tf.map_fn(lambda x: ragged_function(*x),
                                        [input_ragged_mat, input_ragged_lengths], 
                                        # Note that input_ragged_lengths is of type int64
                                        # This leads to an error on GPU placement
                                        dtype=tf.float32)
    final_loss = final_loss_function(ragged_function_outputs)

    optimizer = tf.train.AdamOptimizer(learning_rate=1e-3)
    train_op = optimizer.minimize(final_loss)

# Create input ragged_matrices, with zeros beyond the actual length
ragged_input_mat = np.random.random(size=(batch_size, max_ragged_dim, embedding_dim))
ragged_input_length_mat = np.random.randint(max_ragged_dim, size=(batch_size,)) + 1
for i, rlen in enumerate(ragged_input_length_mat):
    ragged_input_mat[i, rlen:max_ragged_dim] = 0

with tf.Session() as sess:
    feed_dict = {input_ragged_mat: ragged_input_mat,
                 input_ragged_lengths: ragged_input_length_mat}

    sess.run(tf.global_variables_initializer())

    print("Calculating Final Loss")
    sess.run([final_loss],
             feed_dict=feed_dict)
    print("Running Train operation")
    sess.run([train_op],
             feed_dict=feed_dict)
```

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #22054 where int64 on GPU results in colocation errors. This fix enables int64 on GPU with TensorArray.

This fix fixes #22054.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by ebrevdo** [comment]
Can you add a unit test that only runs if GPU is available?

**Comment by ebrevdo** [comment]
(to make sure we don't regress on this in the future)

**Review by ebrevdo — DISMISSED** [review]

**Comment by ebrevdo** [comment]
Errors look unrelated.  I think this is safe to merge but running kokoro one more time.

**Comment by yongtang** [comment]
Thanks @ebrevdo. The failure in `Ubuntu Sanity` was pylint:
```
FAIL: Found 1 non-whitelited pylint errors:
69
tensorflow/python/kernel_tests/tensor_array_ops_test.py:1509: [W0311(bad-indentation), ] Bad indentation. Found 7 spaces, expected 6
```

I have fixed the pylint error and pushed. Thanks for the help!

**Pull request merged**
