### PR TITLE
Include absl headers in pip package

### PR DESCRIPTION
**Pull request by av8ramit**
PiperOrigin-RevId: 212067303

Cherrypick Austin's change into r1.11

### CODE REVIEW

**Comment by gunan** [comment]
Any idea about the XLA failure?

**Comment by av8ramit** [comment]
I didn't see it, hopefully a rerun helps.

**Comment by perfinion** [comment]
What about using https://github.com/tensorflow/tensorflow/pull/22061 to gather all the headers then copy those into the pip package?

**Comment by gunan** [comment]
This is an issue with setup.py copying the files, more than the bazel dependencies.
Even with your change, we have to have the changes in setup.py to make sure the new files are included in the pip package., otherwise setup.py will ignore the new headers.

**Review by angerson — APPROVED** [review]

**Comment by angersson** [comment]
The XLA build failures seem to be fixed by https://github.com/tensorflow/tensorflow/pull/22196, but not the test failure.

**Pull request merged**
