### PR TITLE
TypeError on line 88 should have a condition

### PR DESCRIPTION
**Pull request by aniketmaurya**
while exporting the model in Tensorflow Object detection API we get *TypeError('Expected Operation, Variable, or Tensor, got ' + str(x))*
Please refer this https://github.com/tensorflow/models/issues/8881#issuecomment-665486156

### CODE REVIEW

**Review by fchollet — COMMENTED** [review]
Thanks for the PR. What is the goal here? No behavior appears to change. Perhaps you could just use string formatting to print the error message?

**Comment by aniketmaurya** [comment]
> Thanks for the PR. What is the goal here? No behavior appears to change. Perhaps you could just use string formatting to print the error message?

Sorry! I didn't realize that there is no behavior change with this. I made the PR because many people were using this for TF OD API to work.

**Review by fchollet — COMMENTED** [review]
There is nothing wrong with the code here as far as I can tell. The thing is, `x` is absolutely not supposed to be a `str`, and if it is, it is appropriate to raise an error (the error you are seeing).

So it seems like the bug that should be fixed is the bug that leads to `x` having been a `str` in the first place.

**Comment by gbaned** [comment]
@aniketmaurya  Can you please check @fchollet's comments and keep us posted ? Thanks!

**Comment by aniketmaurya** [comment]
> @aniketmaurya  Can you please check @fchollet's comments and keep us posted ? Thanks!

Sure

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@aniketmaurya Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
