### PR TITLE
Try to upgrade gast to 0.4.0

### PR DESCRIPTION
**Pull request by bhack**

### CODE REVIEW

**Review by kkimdev — APPROVED** [review]

**Review by mdanatg — COMMENTED** [review]
Thank you for the change. Unfortunately, there are a few internal dependencies that need to be updated in the same PR, and those can only be touched by an internal change. We have everything set up and just need one last approval before pushing it, so this should be resolved soon. It's an unfortunate shortcoming that internal pending changes are not visible externally to avoid this kind of confusion. I'll make a note of the PR in the internal one so that you can get credit for the work.

**Comment by bhack** [comment]
> It's an unfortunate shortcoming that internal pending changes are not visible externally to avoid this kind of confusion

@mdanatg Yes you are totally right but I've tried to open a discussion about this big topic since 2016 and we are still here after 4 years with the same problem :disappointed: . You can see the original 2016 thread at  https://github.com/tensorflow/tensorflow/issues/162#issuecomment-171573488

**Comment by bhack** [comment]
@mdanatg I am closing this and stop to push other local commits on this upgrade. But how can solve this more in general? Could you start to use ticket with a special label? Where can we track this discussion?

**Comment by mdanatg** [comment]
@bhack We can use #44485 to continue the discussion, since it's been mentioned there, or alternatively we can open a separate issue to track the 0.4 upgrade alone. In hindsight, we probably should have done that from the beginning.

**Comment by bhack** [comment]
@mdanatg I meant more about where we could discuss the general topic since 2016 so the produce some regular public info about in progress internal activities as internal teams commits don't pass through PR/Draft PR pipelines.

**Comment by mdanatg** [comment]
Ah, let's file a new issue for that part, because it's an important topic and I don't know if one exists.

**Comment by bhack** [comment]
> Ah, let's file a new issue for that part, because it's an important topic and I don't know if one exists.

As we don't have a special place to discuss this kind of topics I've recycled my community ticket at https://github.com/tensorflow/community/issues/29. @mdanatg  as @martinwicke is probably no more involved please mention someone else in the team that can discuss/handle this topic.

Thanks

**Comment by mdanatg** [comment]
SG thanks! It might be worth creating a dedicated ticket as well, to that readers don't mistakenly think this is just about email notifications.

**Comment by bhack** [comment]
@mdanatg I am on hold in first ticket since 2016 and on that one since 2018 so as you know better the internal dynamic so please help me to push this forward.

**Comment by mdanatg** [comment]
Hmm, since the tickets are so old it's possible they slipped through the cracks; re-filing might help with that. @ewilderj any advice on how to best proceed?

**Pull request closed without merging**
