### PR TITLE
[ROCm] Adding #defines for ROCm / MIOpen / HIP Runtime version numbers 

### PR DESCRIPTION
**Pull request by deven-amd**
This PR/commit introduces the following #defines in the `rocm/rocm_config.h` file

```
#define TF_ROCM_VERSION <Version Number of ROCm install>
#define TF_MIOPEN_VERSION <Verion Number of MIOpen in ROCm install>
#define TF_HIPRUNTIME_VERSION <Version Number of HIP Runtinme in ROCm install>
```

These #defines should be used within TF code to add ROCm/MIOpen/HIp Runtime version specific code.

A new script `find_rocm_config.py` is being added by this commit. This script does all the work of determining the version number information and it is pretty easy to extend it to query more information about the ROCM install.

The information collected by the script is available to `rocm_configure.bzl` and hence can be used to add version specific code in `rocm_configure.bzl` as well.

----------------------------------------------------------

/cc @cheshire @chsigg @nvining-work

### CODE REVIEW

**Comment by deven-amd** [comment]
@cheshire @chsigg gentle ping

**Review by cheshire — APPROVED** [review]

**Comment by deven-amd** [comment]
@gbaned let me know if there is anything that needs to be done on my end to get this PR merged

**Comment by gbaned** [comment]
@deven-amd  It is processing internally, we will let you know if anything required from you.  Thank you!

**Comment by deven-amd** [comment]
@gbaned any update on this one? 
getting this PR merged is a pre-req to enable me to file the next PR (which will update TF builds to use ROCm 3.9). 
thanks.

**Comment by akuegel** [comment]
It seems this runs again into the error that you cannot execute a python script checked into the repository in the configure step during a remote build execution. You can take a look at the workaround used in cuda_configure.bzl (function _check_cuda_libs) for a workaround how to do this.

**Comment by gbaned** [comment]
@deven-amd  Can you please check @akuegel's comments and keep us posted ? Thanks!

**Comment by deven-amd** [comment]
@akuegel @gbaned 

I have updated the manner in which `find_rocm_config.py` is invoked, to mimic the manner in which `find_cuda_config.py` is invoked. I am hoping that this is enough to make the script execute properly in rbe, but I have no way to check/confirm it. Please trigger the RBE on your end, and let me know if the changes are good. 

thanks

deven

**Review by akuegel — APPROVED** [review]

**Comment by akuegel** [comment]
> @akuegel @gbaned
> 
> I have updated the manner in which `find_rocm_config.py` is invoked, to mimic the manner in which `find_cuda_config.py` is invoked. I am hoping that this is enough to make the script execute properly in rbe, but I have no way to check/confirm it. Please trigger the RBE on your end, and let me know if the changes are good.
> 
> thanks
> 
> deven

Thanks for fixing it, it looks like it now runs successfully with RBE. It might still take until tomorrow until we merge this PR, because we still need an internal approval by an OWNER of this code area.

**Comment by akuegel** [comment]
I ran into some additional issues, it seems the find_rocm_config.py script didn't find some configs. So in the end I just commented out all _find_*_config lines which are currently unused (and regenerated the compressed file), and then it worked.

**Pull request merged**
