### PR TITLE
Add dynamic_pad to shuffle_batch

### PR DESCRIPTION
**Pull request by SriramRamesh**
Add 'dynamic_pad' flag to `shuffle_batch` as implemented in `batch`
Added the c++ implementation of padding_random_shuffle_queue 
#5147

### CODE REVIEW

**Comment by ebrevdo** [comment]
Derek, do we want the added complexity of a padded shuffle queue?  PTAL.

**Comment by mrry** [comment]
According to #5147, it's a contribution we'd welcome. I assume there's a use case?

(I'm not thrilled by adding another queue implementation, but it's compatible with the current way things are implemented. It looks like there's a lot of repeated logic in the new shuffle queue... perhaps the padding and shuffling could be implemented orthogonally so there isn't as much repetitive code?)

**Comment by ebrevdo** [comment]
+1 Sriram, is there a way to refactor the two queues in question (shuffle + paddingshuffle) to use one common base set of functions for shuffling?

**Comment by SriramRamesh** [comment]
RandomShuffleQueue can take dynamic_pad as a default argument and then implement padding if it is true

**Comment by ebrevdo** [comment]
@mrry are you ok merging the logic for dynamic_padding and w/o into a single kernel impl?  if so, we could do the same for PaddingFIFOQueue and regular FIFOQueue.

**Comment by mrry** [comment]
@ebrevdo: I don't think we want a single kernel (at the very least, we need separate kernels for backwards compatibility, but I would also prefer it aesthetically)... but the aim is to cut down on repeated code: so we might want to refactor the queue implementation so that (e.g.) the padding (output preparation) logic is separate from the coordination and the element selection code.

**Comment by ebrevdo** [comment]
Sriram, want to try to factor the c++ implementations of the two ops to
share a common codebase for everything but the padded copies?

**Comment by SriramRamesh** [comment]
Sorry,I didn't get you @ebrevdo 
Should i create a common base for PaddingRandomShuffleQueue and PaddingFIFOQueue?

**Comment by ebrevdo** [comment]
This seems reasonable, yes.

**Comment by danmane** [comment]
@SriramRamesh Please also rebase when you make the changes ebrevdo suggested.

**Comment by martinwicke** [comment]
Friendly ping. Can you rebase?

**Pull request closed without merging**
