### PR TITLE
Branch 160731226

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by drpngx — APPROVED** [review]

**Comment by drpngx** [comment]
Not sure what that is:

```
ERROR: /var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/external/local_config_cuda/cuda/BUILD:1305:1: declared output 'external/local_config_cuda/cuda/lib/libcublas.so.8.0' is a dangling symbolic link.
```

**Comment by caisq** [comment]
@gunan @annarev Any idea where the libcublas-related error quoted by @drpngx above comes from?

**Comment by gunan** [comment]
Not sure what it is, but looks bad.
Internal and external builds are both healthy, so I am not sure what is happening with this one.

**Comment by drpngx** [comment]
Maybe some cache corruption?

Jenkins, test this please.

**Comment by caisq** [comment]
@drpngx I was thinking of the same thing. I wiped the cache of the "tensorflow-pull-requests-gpu" build on all Jenkins GPU instances. Let's see how the new builds go.

**Comment by caisq** [comment]
Looks like wiping the cache gets rid of the previous error. But it appears that the cache of "tensorflow-pull-requests-xla" also needs to be wiped. Doing that right now.

**Comment by drpngx** [comment]
/CC: @jart @davidzchen @rmlarsen in case they know something.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please
hopefully this time all tests will pass

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
Both the GPU and XLA builds passed after clearing the caches. So it does look like a cache problem related to libcublas. @davidzchen @meteorcloudy , if you have thoughts, please let us know. 

I'm merging this PR now.

**Comment by gunan** [comment]
Looks like another bazel bug related to caching of external build rules?
@damienmg fyi

**Comment by damienmg** [comment]
That's because we do not track the binary to which we point the symlink too, so if you change the install of cuda, this will fail and needs a reconfigure. We are discussing how to do it correctly in the future already. FTR the same fix that the previous case is feasible (force a reconfiguration of the repo).

**Comment by gunan** [comment]
Thank you very much for the clarification Damien!

**Pull request merged**
