### PR TITLE
Added several 'see also' references in Python API documentation

### PR DESCRIPTION
**Pull request by tomasvr**
In relation to issue #36786 and PR #37121 I have added some additional 'see also' references between functions in the Python API docs. 

These references make it easier for newcomers to learn about existing alternatives to functions that might better fit their use case and also reminds intermediate users about different options. This style of referencing is similar to what is seen in PyTorch and Arduino documentation. Any feedback is welcome. 

For your convenience, these are roughly the functions which I have referred to each other 

- `tf.slice` and `tf.strided_slice`
- `tf.rank` and `tf.shape`
- `tf.scan` and `tf.map_fn`
- `tf.unqiue` and `tf.unique_with_counts`
- `tf.fill`, `tf.ones`, `tf.zeros`, `tf.eye`, `tf.one_hot` 

For the last group, I left out certain references if they seemed unnecessary (e.g. `tf.one_hot` and `tf.zeros`).

### CODE REVIEW

**Comment by tomasvr** [comment]
@googlebot I signed it!

**Review by alextp — APPROVED** [review]

**Comment by tomasvr** [comment]
I see that the **import/copybara** check has failed. I couldn't find any information regarding this check, could @alextp  or someone please explain what this means and how I can fix it? Thanks in advance.

**Comment by alextp** [comment]
@gbaned can you see the status of this test? I can't click the link..

**Review by gbaned — APPROVED** [review]

**Comment by gbaned** [comment]
> @gbaned can you see the status of this test? I can't click the link..

@alextp Yes. I can see the status of this test now. Thank you.

**Pull request merged**
