### PR TITLE
Branch 202673820

### PR DESCRIPTION
**Pull request by case540**

### CODE REVIEW

**Comment by case540** [comment]
Very very confusing merge. GRPC build targets got duplicated because of internal change,  protobuf pip version was accidently downgraded internally, and many conflicts caused by internal formatting tool

**Comment by case540** [comment]
Might have messed some of the merge up. Double checking

**Review by yifeif — DISMISSED** [review]

**Review by yifeif — DISMISSED** [review]

**Comment by yifeif** [comment]
looks like windows bazel build is broken by cl/202664219

**Review by yifeif — APPROVED** [review]
Thanks @case540!

**Comment by jayfurmanek** [comment]
@case540 Can you explain a bit more what this is? A 150 commit PR this close to 1.9 being tagged is wild. I'm not arguing about the need, it's just these large PRs often break the ppc64le build and we have to sift through a lot of code to find out why. A bit more transparency would be great!

**Comment by case540** [comment]
@jayfurmanek I dont think this is in 1.9 branch so it being committed close to 1.9 being tagged shouldn't matter. This is just part of the process of pushing internally made commits to public tensorflow.

**Comment by jayfurmanek** [comment]
Ah, right. I was looking at so many 1.9 commits lately, I see this is to master now. (sorry!)
If this must come in one big PR, having a description of what it is would be nice.

**Comment by yifeif** [comment]
@jayfurmanek thanks for your note. This PR was part of our old process to push internal changes out to github daily. We have recently moved to a new workflow where each internal change gets pushed to GitHub right away, and hopefully it is more clear than big PR like this one!

**Comment by jayfurmanek** [comment]
Oh ok, that's great to hear! These big PRs can be painful to sift through, so the new method is most welcome. Thanks!

**Pull request merged**
