### PR TITLE
R0.11

### PR DESCRIPTION
**Pull request by TheUSER123**

### CODE REVIEW

**Comment by TheUSER123** [comment]
yes16.12.2016, 19:03, "Tensorflow Jenkins" <notifications@github.com>:Can one of the admins verify this patch?

**Comment by philipperemy** [comment]
Really you make a PR just for that?

**Comment by martinwicke** [comment]
This is a cherry-pick from inside TF, so I'll ignore CLAbot.

**Review by martinwicke — COMMENTED** [review]
great.

**Review by martinwicke — APPROVED** [review]

**Pull request merged**
