### PR TITLE
Fix the Docker GPU build (adds a symlink + library path)

### PR DESCRIPTION
**Pull request by allenlavoie**
I was running a slightly modified build script the last time this passed, so you may want to test it again.

### CODE REVIEW

**Review by gunan — APPROVED** [review]

**Comment by flx42** [comment]
Hello,

I don't understand what this PR is solving. You shouldn't add the stubs to your `LD_LIBRARY_PATH`, you don't want to use them at runtime, just at build time.

**Comment by gunan** [comment]
We were able to work around a bazel bug with this PR.
@allenlavoie has more context.

**Comment by allenlavoie** [comment]
Some recent changes mean that we're linking in GPU code when generating op wrappers (while building).

The tools for Bazel genrules depend on libtensorflow_framework.so, and that depends on CUDA libraries when building with CUDA. It's likely avoidable by not linking libtensorflow_framework.so for these genrules, and instead relying on the cc_library rules directly.

So we need a stub to satisfy that (trivial/incidental) dependency while building. But you're right that we should avoid putting stubs in LD_LIBRARY_PATH in the final image. I'll fix it in another PR.

**Comment by flx42** [comment]
Ok. I would suggest adding the fixups around the code that require them, e.g. something like that:
```
RUN export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$LD_LIBRARY_PATH && \
        ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 && \
        bazel [...] && \
        rm /usr/local/cuda/lib64/stubs/libcuda.so.1
```
Thanks!

**Pull request merged**
