### PR TITLE
Added switch support to tflite.

### PR DESCRIPTION
**Pull request by amitsrivastava78**
This is one of the Issue #27241.

### CODE REVIEW

**Comment by jdduke** [comment]
Hi @amitsrivastava78, I'll let @miaout17 respond with more details, but in short, we are actively working on more general control flow support which will obiate the need for this kind of change.

Let's discuss this more offline, in particular, whenever you plan on landing new features/operators/etc..., it would be better to let us know in advance before you start working on said feature/operator. That is, design/detailed discussion should happen before the pull request.

**Comment by amitsrivastava78** [comment]
@jdduke thanks for the comments, i will wait for @miaout17 to respond, Yes i think it would be great if we can discuss in advance the new operator/features detail design, do you have any suggestions as to where we can discuss this ? 

Regards
Amit

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by jdduke** [comment]
See https://github.com/tensorflow/tensorflow/issues/28485 for the generalized control flow proposal. Feedback welcome.

**Pull request closed without merging**
