### PR TITLE
Add feature to enable INT ops on GPU conditionally by environment

### PR DESCRIPTION
**Pull request by samikama**
Tensorflow contains certain Fake-GPU ops i.e. ops that are marked as GPU ops but has inputs and outputs on the host and run host kernels. This pr adds a bazel configuration option to enable code path to register real GPU versions of Fake-GPU ops using an environment variable. 

If "--define using_gpu_int_ops=true" added to bazel flags during building phase it will be possible to register GPU versions of Fake-GPU ops by setting an environment variable "TF_USE_INT_TYPES_ON_GPU=1"

### CODE REVIEW

**Comment by samikama** [comment]
tagging @azaks2, @aaroey  and @tfboyd

**Comment by ebrevdo** [comment]
@rmlarsen  @alextp I think we shouldn't do it this way, and eventually just fix the PinToHost rewriter and move registration of all these ops on device.

**Comment by tfboyd** [comment]
@tatianashp will be ready next time.

**Comment by gbaned** [comment]
@samikama could you please resolve the conflicts? Thanks !

**Comment by gbaned** [comment]
@samikama  gentle ping to resolve the conflicts. Thanks!

**Comment by samikama** [comment]
@tatianashp @tfboyd Should I fix the conflicts for merging or are we going to discuss it further. I believe, since this touches many files it will have conflicts again if it is not going to be merged in near future and fixing these will be pointless.

**Comment by alextp** [comment]
I'd also strongly prefer first fixing the PinToHostOptimizer and then always enabling int ops on GPUs.

**Comment by ebrevdo** [comment]
Let's put this PR on hold until we can get PinToHost optimizer to a point
where it's always enabled; then we can enable non-host int kernels on GPUs
by default.

**Comment by samikama** [comment]
@tatianashp @tfboyd, as discussed in the meeting, compiling in the extra kernels increase the pip wheel size approximately 7 megabytes. filesize of the _pywrap_tensorflow_internal.so for gpu build with ci_build.sh increased from 530MB to 563MB.

**Comment by tfboyd** [comment]
Thanks Sami.  I will try to figure out if 7MB (in the pip) is ok.  It seems ok to me but I am no the owner.  If not we can go back to the build flag and still move forward with trying to get this moving forward.

**Comment by tfboyd** [comment]
@tatianashp   Please state the next direction.  Our last decision 22-MAY was to add this as optional so we can play with the feature.

**Comment by gbaned** [comment]
@samikama could you please resolve the conflicts? Thanks!

**Comment by tfboyd** [comment]
@tatianashp  to get answer at next meeting.  Rasmus has been out and is vital to the review process.

**Pull request closed without merging**
