### PR TITLE
fix a crash on Android Lollipop and lower versions

### PR DESCRIPTION
**Pull request by zhenyuni**
The allocated memory address is not aligned by 16, which causes
BUS_ADRALN crash on Android platform of low versions.

### CODE REVIEW

**Comment by zhenyuni** [comment]
I signed it! @googlebot

**Comment by zhenyuni** [comment]
I signed it!

**Comment by zhenyuni** [comment]
I signed it!

**Comment by zhenyuni** [comment]
@petewarden Could you please review this commit?

**Review by petewarden — APPROVED** [review]
Looks good, thanks!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: It has been 44 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by gunan** [comment]
@zhenyuni sorry for the delay.
Could you rebase and resolve all conflicts? Looks like we can merge as soon as all the conflicts are resolved.

**Comment by zhenyuni** [comment]
@gunan I think the recent patch (commit 88103d000add4ea7f8d1a34ee3c898fc79d9e3c7) on master branch has also solved this problem so that my pull request can be closed. Thanks!

**Pull request closed without merging**
