### PR TITLE
Resolve Programmatic mistake.

### PR DESCRIPTION
**Pull request by bhosalems**
SPECIES should have been either imported here or it should have referenced from iris_data. The corresponding code is correct but the conflict in the documentation.

### CODE REVIEW

**Comment by MaheshBhosale** [comment]
I signed it.

**Comment by jhseu** [comment]
The CLA hasn't yet resolved. Mind taking another look?

**Comment by jhseu** [comment]
Nevermind, looks like CLA bot is having issues. I verified that you've signed the CLA.

**Review by jhseu — APPROVED** [review]

**Comment by jhseu** [comment]
I've verified the CLA manually. Merging.

**Pull request merged**
