### PR TITLE
Fixed a bug where inception layers had 2 3x3 conv kernels instead of …

### PR DESCRIPTION
**Pull request by manjunaths**
…one 3x3 and 5x5 kernel. This is a fix for the issue #7130 .

### CODE REVIEW

**Comment by sguada** [comment]
The problem of changing the network definition, is that the checkpoint would stop working. So it would need to be re-trained.

**Comment by vrv** [comment]
@sguada so how should we go about fixing this?  Do you want to own fixing the bug and regenerating the checkpoint?

**Comment by vrv** [comment]
closing since the author hasn't signed the CLA, but I suspect this ought to be fixed somehow.

**Comment by manjunaths** [comment]
Sorry, this took longer than expected. I had to go through an internal company approval process to find out about the CLA signing. Seems we have a corporate CLA and I signed the individual CLA too.

I signed it!

Is that it ?

**Comment by dandelionmane** [comment]
@manjunaths can you go to https://cla.developers.google.com/clas and see if the email you used for these commits is associated with a CLA?

**Comment by manjunaths** [comment]
Hello, Yes there is one E-mail address associated in the github.com account and the CLA page shows the same E-mail address.

**Comment by manjunaths** [comment]
Can you check now please ? I pushed to my fork with a corrected e-mail address.

**Comment by aselle** [comment]
Don't know why cla is not being re-evaluated... checking

**Comment by aselle** [comment]
I think it is not showing cla:yes, because you have 3 commits on your branch. commit 3dd13a52df07d60d06099b26fe368b73f98b2ff1 is authored by manjunaths+github@gmial.com, the other two are authored by manjunaths@gmail.com. You need to make sure they are all authored by an email address associated with your git account.

**Comment by manjunaths** [comment]
https://github.com/tensorflow/tensorflow/pull/8295

I created a new pull request with everything fixed. Is it possible to merge this ?

Sorry for all the confusion I am new to all this.

**Pull request closed without merging**
