### PR TITLE
make tf_upgrade.py more useful

### PR DESCRIPTION
**Pull request by primetang**
When we upgrade tf code to version 1.0.0 in a directory tree, some times we also want to copy all the other files from `--intree` to the `--outtree`，this makes it easier to upgrade an entire project.

So I add an option named `--copyotherfiles` in `tf_upgrade.py`. Hopefully useful!

```
# just upgrade the .py files
tf_upgrade.py --intree coolcode --outtree coolcode-upgraded
# after upgrade the .py files, then copy all the other files to the outtree
tf_upgrade.py --intree coolcode --outtree coolcode-upgraded --copyotherfiles True
```

### CODE REVIEW

**Comment by caisq** [comment]
gentle ping @aselle

**Review by aselle — APPROVED** [review]

**Comment by aselle** [comment]
Thanks for the patch @primetang, LGTM

**Comment by dandelionmane** [comment]
@tensorflow-jenkins Test this please.

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Pull request merged**
