### PR TITLE
Refactor Lite reference op CAST from reference_ops.h into cast.h

### PR DESCRIPTION
**Pull request by rsun-bdti**
Issue #45608 PR2: Refactor reference implementation from lite/kernels/internal/reference/reference_ops.h into its own header cast.h without making any changes

### CODE REVIEW

**Review by petewarden — APPROVED** [review]

**Comment by advaitjain** [comment]
the internal checks are failing because of a missing license in cast.h.

PR https://github.com/tensorflow/tensorflow/pull/46182 will make the error visible externally as well so that it will be caught much earlier in the review process.

**Review by advaitjain — APPROVED** [review]

**Comment by gbaned** [comment]
@rsun-bdti  Can you please resolve conflicts? Thanks!

**Comment by rsun-bdti** [comment]
Merging is not working. I am digging into this.

**Comment by gbaned** [comment]
Seems auto-merge is not happening but the changes are merged into master now, so we can close this. Thank you for the PR.

**Pull request closed without merging**
