### PR TITLE
support IndexedSlices in `add_n`

### LINKED ISSUE #15943: add_n: issue with IndexedSlices
inside function add_n, line 2117, shouldn't
"if not all(isinstance(x, ops.Tensor) for x in inputs):" check also whether x is IndexedSlices instead of merely Tensor? i.e. replace the statement with:

if not ( (all(isinstance(x, ops.Tensor) for x in inputs)) | (all(isinstance(x, ops.IndexedSlices) for x in inputs)) ):

Thanks!

### PR DESCRIPTION
**Pull request by npow**
Fixes #15943

### CODE REVIEW

**Review by drpngx — DISMISSED** [review]

**Comment by drpngx** [comment]
```
ound a whitelisted error:
  tensorflow/contrib/eager/python/evaluator.py:209: [E0202(method-hidden), Evaluator.call] An attribute defined in evaluator line 61 hides this method
Found a whitelisted error:
  tensorflow/contrib/eager/python/evaluator.py:361: [E0202(method-hidden), SparseSoftmaxEvaluator.call] An attribute defined in evaluator line 61 hides this method
Found a whitelisted error:
  tensorflow/contrib/eager/python/metrics_impl.py:179: [E0202(method-hidden), Metric.build] An attribute defined in metrics_impl line 121 hides this method
Found a whitelisted error:
  tensorflow/contrib/eager/python/metrics_impl.py:192: [E0202(method-hidden), Metric.call] An attribute defined in metrics_impl line 131 hides this method
Found a whitelisted error:
  tensorflow/contrib/eager/python/metrics_impl.py:301: [E0202(method-hidden), Mean.build] An attribute defined in metrics_impl line 121 hides this method
Found a whitelisted error:
  tensorflow/contrib/eager/python/metrics_impl.py:312: [E0202(method-hidden), Mean.call] An attribute defined in metrics_impl line 131 hides this method
Found a whitelisted error:
  tensorflow/contrib/eager/python/metrics_impl.py:356: [E0202(method-hidden), Accuracy.call] An attribute defined in metrics_impl line 131 hides this method
Found a whitelisted error:
  tensorflow/contrib/eager/python/metrics_impl.py:401: [E0202(method-hidden), CategoricalAccuracy.call] An attribute defined in metrics_impl line 131 hides this method
Found a whitelisted error:
  tensorflow/contrib/eager/python/metrics_impl.py:454: [E0202(method-hidden), BinaryAccuracy.call] An attribute defined in metrics_impl line 131 hides this method
Found a whitelisted error:
  tensorflow/contrib/eager/python/metrics_impl.py:498: [E0202(method-hidden), SparseAccuracy.call] An attribute defined in metrics_impl line 131 hides this method
Found a whitelisted error:
  tensorflow/python/kernel_tests/constant_op_eager_test.py:250: [E0303(invalid-length-returned), ConstantTest.testInvalidLength.BadList.__len__] __len__ does not return non-negative integer
Found a whitelisted error:
  tensorflow/python/feature_column/feature_column_test.py:3125: [E0110(abstract-class-instantiated), MakeParseExampleSpecTest.test_invalid_type] Abstract class '_TestFeatureColumn' with abstract methods instantiated
Found a whitelisted error:
  tensorflow/python/feature_column/feature_column_test.py:3132: [E0110(abstract-class-instantiated), MakeParseExampleSpecTest.test_one_feature_column] Abstract class '_TestFeatureColumn' with abstract methods instantiated
Found a whitelisted error:
  tensorflow/python/feature_column/feature_column_test.py:3142: [E0110(abstract-class-instantiated), MakeParseExampleSpecTest.test_two_feature_columns] Abstract class '_TestFeatureColumn' with abstract methods instantiated
Found a whitelisted error:
  tensorflow/python/feature_column/feature_column_test.py:3143: [E0110(abstract-class-instantiated), MakeParseExampleSpecTest.test_two_feature_columns] Abstract class '_TestFeatureColumn' with abstract methods instantiated
Found a whitelisted error:
  tensorflow/python/feature_column/feature_column_test.py:3155: [E0110(abstract-class-instantiated), MakeParseExampleSpecTest.test_equal_keys_different_parse_spec] Abstract class '_TestFeatureColumn' with abstract methods instantiated
Found a whitelisted error:
  tensorflow/python/feature_column/feature_column_test.py:3156: [E0110(abstract-class-instantiated), MakeParseExampleSpecTest.test_equal_keys_different_parse_spec] Abstract class '_TestFeatureColumn' with abstract methods instantiated
Found a whitelisted error:
  tensorflow/python/feature_column/feature_column_test.py:3163: [E0110(abstract-class-instantiated), MakeParseExampleSpecTest.test_equal_keys_equal_parse_spec] Abstract class '_TestFeatureColumn' with abstract methods instantiated
Found a whitelisted error:
  tensorflow/python/feature_column/feature_column_test.py:3164: [E0110(abstract-class-instantiated), MakeParseExampleSpecTest.test_equal_keys_equal_parse_spec] Abstract class '_TestFeatureColumn' with abstract methods instantiated
Found a whitelisted error:
  tensorflow/python/feature_column/feature_column_test.py:3177: [E0110(abstract-class-instantiated), MakeParseExampleSpecTest.test_multiple_features_dict] Abstract class '_TestFeatureColumn' with abstract methods instantiated
Found a whitelisted error:
  tensorflow/python/feature_column/feature_column_test.py:3178: [E0110(abstract-class-instantiated), MakeParseExampleSpecTest.test_multiple_features_dict] Abstract class '_TestFeatureColumn' with abstract methods instantiated
FAIL: Found 2 non-whitelited pylint errors:
tensorflow/python/ops/math_ops.py:2120: [C0301(line-too-long), ] Line too long (81/80)
tensorflow/python/ops/math_ops.py:2124: [C0301(line-too-long), ] Line too long (81/80)
```

**Comment by ebrevdo** [comment]
The relevant lines:

FAIL: Found 2 non-whitelited pylint errors:
tensorflow/python/ops/math_ops.py:2120: [C0301(line-too-long), ] Line
too long (81/80)
tensorflow/python/ops/math_ops.py:2124: [C0301(line-too-long), ] Line
too long (81/80)

**Review by drpngx — APPROVED** [review]

**Comment by npow** [comment]
Hi @drpngx, just curious what release this will make it into? I saw version 1.10.1 was released 5 days ago but this commit isn't in there.

**Comment by av8ramit** [comment]
1.10.1 was a patch release and by definition will not necessarily contain all latest commits. @drpngx is correct it will be in 1.11 which will be cut tomorrow at 5pm.

**Pull request merged**
