### PR TITLE
[XLA] Add a check to the HLO verifier for badly formatted Broadcasts.

### PR DESCRIPTION
**Pull request by DavidNorman**
This adds a check to the HloVerifier which ensures that the Hlo Broadcast instructions are formatted correctly.  Since they are different from the UserComputation broadcast instructions (and therefore the XLA docs), examples of invalid instructions were appearing in the repo.

Also fix up the two cases where the code was creating invalid broadcasts.

### CODE REVIEW

**Review by meheffernan — APPROVED** [review]
Thanks for the fix!

**Comment by jpienaar** [comment]
Jenkins, test this please

**Comment by DavidNorman** [comment]
@jpienaar hi - seems like the code review thing has not run.  is that an automated thing?

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by DavidNorman** [comment]
Ah - this Linux XLA error seems to be a memory/disk space issue with the docker builder.

**Comment by jpienaar** [comment]
Jenkins, test this please

**Comment by DavidNorman** [comment]
Hmm.  I'm not really sure I understand the problem here.  it appears to be another build system error, but two in a row seems suspicious.

is this happening to other CI builds too, or just this one?

should I be merging in the head of master?

**Comment by DavidNorman** [comment]
The 'Linux CPU Tests (Python 3)' failure is definitely not this PR - it contains only XLA changes, and the failure is something about a gRPC server.

the XLA one is harder to judge - is it a git merge problem?  or just an infrastructure problem?

**Comment by jpienaar** [comment]
It is weird, I've tried prodding it too. And I do see passing cases post this. I've set off another round of building. And will ask around more if that doesn't work.

**Comment by jpienaar** [comment]
Jenkins, test this please.

**Review by jpienaar — APPROVED** [review]
Don't know why it says awaiting a review as Mark already did, but re-approving.

**Comment by martinwicke** [comment]
@gunan, can we change "TF Code Review" to "TF Test Suite" to avoid confusion?

Jenkins, test this please.

**Comment by gunan** [comment]
Renaming of the build complete.

**Pull request merged**
