### PR TITLE
Optimized fashion-mnist dataset download sourses for developers in China

### PR DESCRIPTION
**Pull request by Dynmi**
make the fashion-mnist dataset accessable for those developer who can't visit storage.googleapis.com

### CODE REVIEW

**Comment by Dynmi** [comment]
@googlebot I signed it!

**Comment by Dynmi** [comment]
mimi43435@gmail.com

**Comment by Dynmi** [comment]
@googlebot I signed it!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Pull request closed without merging**
