### PR TITLE
Daily Pull Request (July 10th 2017)

### PR DESCRIPTION
**Pull request by frankchn**

### CODE REVIEW

**Comment by frankchn** [comment]
@tensorflow-jenkins test this please.

**Comment by frankchn** [comment]
@jhseu PTAL

**Comment by drpngx** [comment]
Barrier ops test is b/35468214.

Jenkins, test this please.

**Comment by jhseu** [comment]
Nits:
- 5d1b38d is the merge commit, but the commit message indicates something else (probably what was needed in conflict resolution?).
- (Style) Please leave the original pull request title that's set when you create the pull request since it includes the CL#.

**Review by jhseu — APPROVED** [review]
(Approving anyway, can just do those for the next push).

**Comment by frankchn** [comment]
Due to some internal delays, I am going to recreate and land this in a bit.

**Pull request closed without merging**
