### PR TITLE
[XLA] Register the input arguments with the XlaAllocator

### PR DESCRIPTION
**Pull request by DavidNorman**
If an op returns one if its inputs as an output, then the XlaAllocator needs to be able to notice the buffer and find the original tensor.

This adds a method to the XlaAllocator to allow this action, and calls it with all of the inputs and variables (but not the runtime context).

### CODE REVIEW

**Comment by DavidNorman** [comment]
This is related to the comments in https://groups.google.com/forum/#!topic/xla-dev/pFiI1sO8ZhE

**Review by hawkinsp — APPROVED** [review]

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by DavidNorman** [comment]
@sb2nov @hawkinsp 

Cheers guys.  judging by the error 'cannot remove some set of files or another', I think that the Linux CPU tests Makefile is not related to this change.

**Comment by sb2nov** [comment]
@DavidNorman I don't think the Makefile trigger ran anything.

Jenkins, test this please.

**Comment by sb2nov** [comment]
@gunan any ideas about the Makefile test?

**Comment by DavidNorman** [comment]
@sb2nov 

hmm.  the failures are now something to do with git, and something to do with some tests that are nothing to do with XLA.  again, i suspect nothing to do with my changes.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Pull request merged**
