### PR TITLE
Branch 198743117

### PR DESCRIPTION
**Pull request by case540**

### CODE REVIEW

**Comment by case540** [comment]
Any idea why all the presubmit tests arent being triggered?

**Comment by yifeif** [comment]
The xla build link shows that the build passed.
For pip3, not sure why it is complaining "TypeError: a bytes-like object is required, not 'str'". The file_content was read in under binary mode already?

**Comment by av8ramit** [comment]
@case540 do you or @yifeif mind making a new push as this has failed Python3 Pip? Thanks!

**Comment by case540** [comment]
Is there a fix internally that creating a new push would solve? Otherwise, I'm keeping on trying things to fix this. Also, not sure if there is an easy way to run the pip3 tests locally. Do you know a way @av8ramit

**Comment by yifeif** [comment]
I dont think we run this build internally. Quick way to reproduce this locally is probably use virtualenv.

**Comment by case540** [comment]
Ok, closing PR, creating new one to get latest internal CLs. Will add fix.

**Pull request closed without merging**
