### PR TITLE
Fix for compilation error in cmsis-nn/pooling.cc

### PR DESCRIPTION
**Pull request by freddan80**
There was a couple of compilation errors that needed to be fixed. One of the issues is that arm_avgpool_s8() returned void. I had to fix that in the CMSIS repo. Hence I had to step up the downloaded CMSIS commit id. On top of that I added two .c file that are utilized in CMSIS for MVE optimizations.

### CODE REVIEW

**Comment by freddan80** [comment]
@petewarden @advaitjain, gentle ping for review

**Comment by gbaned** [comment]
@freddan80  Can you please resolve conflicts? Thanks!

**Comment by njeffrie** [comment]
You will have to pull and resolve conflicts.  We recently moved micro out of the experimental directory, so your changes need to reflect the correct paths for tip-of-tree.

**Review by njeffrie — DISMISSED** [review]
Approved pending conflict resolution.

**Review by njeffrie — APPROVED** [review]

**Comment by njeffrie** [comment]
I've landed an exact replica of this change internally to get around copybara errors.

**Pull request closed without merging**
