### PR TITLE
Synced the implementation of QuantizationParams.

### PR DESCRIPTION
**Pull request by amitsrivastava78**
This is one of the TODO in the file.

### CODE REVIEW

**Review by suharshs — COMMENTED** [review]
I think the intention of this CL was not to copy the code from that function, but to somehow use the same function. The issue may be that the other functions is in "internal" that may cause dependency issues.

**Comment by amitsrivastava78** [comment]
@suharshs , thanks for the review, I agree with you but the problem is that both the function differ internally and to even sync them might trigger another level of big changes and testing, so i thought of syncing the function itself, kindly check and let me know if i can do any other better way.

Regards
Amit

**Review by suharshs — APPROVED** [review]

**Comment by gbaned** [comment]
@amitsrivastava78 can you please check failed build errors

**Comment by amitsrivastava78** [comment]
@gbaned , thanks for the update, i checked all the errors but none of them are related to tflite module, where my changes are there. On top of it i again ran all the sanity checks and it passed without any issue.
Can you please let me know if you are talking about anything specific.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@gbaned , can you please help to get this PR merged, this is already approved.

**Pull request merged**
