### PR TITLE
[ROCm] Switch r2.1 to use ROCm 3.7

### PR DESCRIPTION
**Pull request by deven-amd**
This PR updates Dockerfile.rocm and the ROCm CI scripts to use ROCm 3.7. 

In addition to that there are also other commits to enable/disable some unit-tests (or subtests within unit tests) on the ROCm platform. See individual commit messages for details.

These changes are required for the ROCm CI scripts to successfully run on the ROCm platform with ROCm 3.7.

Thanks

------------------------------

/cc @mihaimaruseac @sunway513

### CODE REVIEW

**Review by alextp — COMMENTED** [review]
Is this intended to be a cherry-pick to 2.1? I thought we only cherry-picked security fixes.

**Comment by deven-amd** [comment]
> Is this intended to be a cherry-pick to 2.1?

Yes, the intent is to cherry-pick these changes into 2.1.

**Comment by mihaimaruseac** [comment]
It will have to wait until we do another patch release for 2.1 (until we find the need to fix another security issue)

**Comment by deven-amd** [comment]
> It will have to wait until we do another patch release for 2.1 (until we find the need to fix another security issue)

@mihaimaruseac , that is okay. thank you.

**Comment by mihaimaruseac** [comment]
Should we be making these changes on `master` instead? And then backporting them once fully done?

This becomes quite large and risky to incorporate in a patch release.

**Comment by deven-amd** [comment]
@mihaimaruseac we can take that approach too.

Some of the changes are already on master...I will be filing a PR for the rest soon (before end of week). The goal is to ensure that the `r2.1` and `master` branches do not regress when we switch to ROCm 3.5 (or higher). I do not know how long it will be to the next patch release, and hence am using this PR to collect  all the changes we need to make it into r2.1.  

If you think that the next patch release is imminent, then let me know and I can trim the ROCm 3.5 specific commits from this PR and file a new PR for them once the patch release goes out. 
Else I would like continue to use this PR for the ROCm 3.5 specific commits as well.

Also note that most if not all of the changes are ROCm specific, so it should not have any impact on non-ROCm TF builds.

thanks

**Comment by mihaimaruseac** [comment]
There is no plan yet for a new patch release. We can keep using this PR then, but we need to ensure the changes are mirrored in master too.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
