### PR TITLE
Fixed the indentation convention problem

### PR DESCRIPTION
**Pull request by amitsrivastava78**
Fixed indentation convention problem in two places

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@aselle can you pls review the PR and let me know your comments

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 30 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 45 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 60 days with no activity and the `awaiting review` label has been applied.

**Review by impjdi — COMMENTED** [review]
I ran our internal py formatter, and the existing indentation is fine.  In fact, your changes will be reverted by our internal py formatter.

https://github.com/google/styleguide/blob/gh-pages/pyguide.md

L.209 is fine as is because rule says 4 space indent.  If you really want, the only change you can do on that line is:

    for filename in [
        toco_filename, input_filename, model_filename, output_filename
    ]:

L.398 is fine as is because, well, if you want to do it your way, you would have to indent L.400 in the same way, and that's clearly wrong.

**Comment by amitsrivastava78** [comment]
@impjdi, thanks for the review, i am closing this PR

**Pull request closed without merging**
