### PR TITLE
Branch 155393864

### PR DESCRIPTION
**Pull request by benoitsteiner**

### CODE REVIEW

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
The "Linux CPU Test" failed due to the following reason:
```
ERROR: /workspace/bazel_pip/tensorflow/contrib/util/BUILD:65:1: Target '//tensorflow/python:framework' is not visible from target '//bazel_pip/tensorflow/contrib/util:util_py'. Check the visibility declaration of the former target if you think the dependency is legitimate.
ERROR: /workspace/bazel_pip/tensorflow/contrib/util/BUILD:65:1: Target '//tensorflow/python:platform' is not visible from target '//bazel_pip/tensorflow/contrib/util:util_py'. Check the visibility declaration of the former target if you think the dependency is legitimate.
ERROR: /workspace/bazel_pip/tensorflow/contrib/util/BUILD:65:1: Target '//tensorflow/python:util' is not visible from target '//bazel_pip/tensorflow/contrib/util:util_py'. Check the visibility declaration of the former target if you think the dependency is legitimate.
```

Is this related to this commit, @ringw ? https://github.com/tensorflow/tensorflow/pull/9874/commits/733bff53926717bb9583d4833ba062c58f27960futil

**Comment by ringw** [comment]
Yes that must be the culprit--weird that our open source presubmits passed. Rolling back.

**Pull request closed without merging**
