### PR TITLE
Changed inconsistent conv1d to use 'filter' param instead of 'filters'

### PR DESCRIPTION
**Pull request by JulienSiems**
Updated the docs and all occurrences of 'filters' when used as input to conv1d. Partial fix for #6379.

### CODE REVIEW

**Comment by dandelionmane** [comment]
@martinwicke This is technically a backwards-incompatible API change (b.c. ppl may use keyword params) and therefore inadmissible, yes?

**Comment by martinwicke** [comment]
Indeed, that is sad. We can accept a second parameter called filter, which
takes filters' spot, and we can deprecate filters, which would move to the
end. That would be backward compatible. This change we cannot make because
it may well break current users.

**Comment by JulienSiems** [comment]
I can change it to be a second parameter. Should there be a deprecation message when using filters?
Why was is it ok to do this in #7883 ?  Didn't that break the API as well?

**Comment by terrytangyuan** [comment]
@JulienSiems The PR you referred was only documentation change. The first argument name change is not as big as this one. A longer warning period before removal would be more appropriate, e.g. remove when it gets to next major release.

**Comment by JulienSiems** [comment]
Should I close this pull request? If it's better solved for the next major release?

**Comment by dandelionmane** [comment]
You could close the PR, or make the change in a backwards-compatible way as martin suggested.

**Comment by JulienSiems** [comment]
I used the deprecated_args decorator to deprecate filters. Is that the way you want to be done?

**Pull request closed without merging**
