### PR TITLE
Add int32/string k/v support for tf.contrib.lookup.HashTable

### LINKED ISSUE #20869: tf.contrib.lookup.HasTable
== cat /etc/issue ===============================================
Linux george-OMEN-by-HP-Laptop 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="18.3 (Sylvia)"
VERSION_ID="18.3"
VERSION_CODENAME=sylvia

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux george-OMEN-by-HP-Laptop 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                              1.14.0        
numpydoc                           0.7.0         
protobuf                           3.5.2.post1   
tensorflow-gpu                     1.8.0         

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.8.0
tf.GIT_VERSION = v1.8.0-0-g93bc2e2072
tf.COMPILER_VERSION = v1.8.0-0-g93bc2e2072
Sanity check: array([1], dtype=int32)
/home/george/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-9.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-9.1/lib64:/usr/local/cuda/extras/CUPTI/lib64/:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Tue Jul 17 09:00:20 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   56C    P0    N/A /  N/A |    709MiB /  4038MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1439      G   /usr/lib/xorg/Xorg                           286MiB |
|    0      2503      G   cinnamon                                     160MiB |
|    0      2630      G   ...-token=2E210DC1F44A55A6DDE70E07757D319C    63MiB |
|    0      2865      G   /usr/lib/firefox/firefox                       3MiB |
|    0      2995      G   ...-token=E5432E224C69AA6F39ED672CDE9108B3    79MiB |
|    0      3500      G   /usr/lib/firefox/firefox                       1MiB |
|    0      3574      G   /usr/lib/firefox/firefox                       1MiB |
|    0      3632      G   /usr/lib/firefox/firefox                       1MiB |
|    0      7199      C   /home/george/anaconda3/bin/python             97MiB |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudart.so.9.1.85
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-9.1/lib64/libcudart.so.9.1.85
/usr/local/cuda-9.1/lib64/libcudart_static.a
/usr/local/cuda-9.1/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.1/doc/man/man7/libcudart.7
/usr/local/cuda-9.0/lib64/libcudart.so.9.0.176
/usr/local/cuda-9.0/lib64/libcudart_static.a
/usr/local/cuda-9.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.0/doc/man/man7/libcudart.7

Tensorflow 1.9

Please provide an oportunity to use tf.contrib.lookup.HashTables  
with key_dtype=tf.int32 and value_dtype=tf.string
Synthetic code:
table = tf.contrib.lookup.HashTable(tf.contrib.lookup.KeyValueTensorInitializer(
    tf.constant([1, 2, 3], dtype=tf.int32), tf.constant(['a', 'b', 'c'], dtype=tf.string)
), '')
table.init.run() raises with error 
InvalidArgumentError: No OpKernel was registered to support Op 'HashTableV2' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='CPU'; key_dtype in [DT_INT32]; value_dtype in [DT_INT32]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_BOOL]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_STRING]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_FLOAT]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_INT64]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_STRING]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_INT64]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_INT32]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_FLOAT]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_DOUBLE]

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #20869 where there were no int32/string k/v support for tf.contrib.lookup.HashTable. This fix adds the int32/string for the kernel.

This fix fixes #20869.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by rmlarsen — APPROVED** [review]

**Comment by yongtang** [comment]
/cc @gunan @yifeif @martinwicke This PR seems to have been imported separately by tensorflower-gardener in da12c366bd55cd797e433f78034d3848736ebe6f and showed up in master branch.

But it is not merged or committed so this PR is still open. Just wondering if there are some additional steps to fully merge and close this PR?

**Comment by rmlarsen** [comment]
@yongtang This is due to a new workflow where we use the internal google repository as the single source of truth and commit every PR there first.

**Comment by rmlarsen** [comment]
@yifeif should this PR not be closed automatically after being pushed?

**Comment by yifeif** [comment]
Looking into why this PR is not marked as merged now. Apologies for the inconvenience @yongtang.

**Comment by yongtang** [comment]
Thanks @rmlarsen @yifeif. It looks like da12c36 already captured all changes in this PR. So it might be safe to close this PR, though let me know if there are anything else that needs to be done.

**Comment by yifeif** [comment]
@yongtang we found the issue in our tool and this shouldn't happen again once the fix is in. Sorry for the trouble. Is it okay with you if we close this PR?

**Comment by yongtang** [comment]
Sure. Let me close the PR.

**Comment by yifeif** [comment]
Thank you @yongtang!

**Pull request closed without merging**
