### PR TITLE
Modify code in docs to conform to Python syntax

### PR DESCRIPTION
**Pull request by rinarakaki**
Corrected a very few code in the docs to let it work only by copy-and-paste.

### CODE REVIEW

**Review by av8ramit — DISMISSED** [review]

**Comment by av8ramit** [comment]
Thanks for the fix @rnarkk

**Comment by rnarkk** [comment]
I just resolved the conflict to catch up with the master branch and the differences remain superficial.

**Review by asimshankar — DISMISSED** [review]

**Comment by rnarkk** [comment]
Seems the same a little conflict has happened so I will resolve it and request someone's review again?

**Comment by asimshankar** [comment]
Closing this since it was merged in https://github.com/tensorflow/tensorflow/commit/73177c09d6ef3716aa449c1f0d7afd992c91dcd7

**Pull request closed without merging**
