### PR TITLE
Added native architecture option to Linux makefile to fix test breakage

### PR DESCRIPTION
**Pull request by petewarden**

### CODE REVIEW

**Comment by petewarden** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Awesome, thanks!

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Oh well. :(

**Comment by petewarden** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Makefile passed, not waiting for the rest. Thanks!

**Pull request merged**
