### PR TITLE
Fixes added to remove CorrectTensorEndianness in AllocateTensors

### PR DESCRIPTION
**Pull request by skribm9**
This PR request is raised with respect to bug #45858 .
A previous discussion was done on a PR #45790 where it was suggested to raise a separate PR with only this fix.

Changes done:
Calling of CorrectTensorEndianness function is removed as the FlatBufferVectorToTfLiteTypeArray already converts flatbuffer tensor data from little endian to big endian during StartModelAllocation function call within AllocateTensors function.

### CODE REVIEW

**Comment by skribm9** [comment]
@nkreeger Can you please review these changes when you some time?

**Review by njeffrie — CHANGES_REQUESTED** [review]
Unless I'm missing something, it looks like you should be able to remove the CorrectTensorEndianness and CorrectTensorDataEndianness methods in the MicroInterpreter class as well, since those methods are only used from the code you are removing.

**Comment by skribm9** [comment]
@njeffrie Thanks for looking into this. Yes, I can remove it but left it in code in case it is being used in other TF Projects.

**Comment by njeffrie** [comment]
That would be great. I did a quick double check and these methods are only used from within MicroInterpreter, so they should be safe to remove.

Removing this code makes me happy, since is has previously been the source of substantial confusion.

**Comment by skribm9** [comment]
@njeffrie That's great then! I have removed these methods and pushed the commit.

**Review by njeffrie — APPROVED** [review]
Looks good, thanks!

**Review by gbaned — APPROVED** [review]

**Pull request merged**
