### PR TITLE
[S3] Fix error due to clashing names of temporary files created by the S3 file system

### PR DESCRIPTION
**Pull request by rahul003**
- Previously the name of the temp file was controlled by the AWS SDK. But the SDK uses timestamp to create temporary files. We've run into cases where the temp files are created with the same name for two different files, and data gets corrupted.
- Adds a static counter and a lock to generate a unique suffix for each temp file to resolve this.

### CODE REVIEW

**Comment by rahul003** [comment]
@googlebot I fixed it.

**Comment by ravikyram** [comment]
@rahul003 thank you for your contribution, please sign CLA.

**Comment by rahul003** [comment]
@ravikyram Yes, my coauthor is on it

**Comment by rahul003** [comment]
Closing this, as the upgrade of AWS SDK fixes this issue. https://github.com/tensorflow/tensorflow/pull/36478

**Pull request closed without merging**
