### PR TITLE
expose sparse_column_with_vocabulary_file method

### PR DESCRIPTION
**Pull request by facaiy**
The bug is explained in #12568 . 

I am not familiar with build tool, however, I observe that the method is missing in `__init__.py`.

### CODE REVIEW

**Review by ispirmustafa — APPROVED** [review]
Thank you Yan

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by facaiy** [comment]
Could I get `queue_runner_test/test.log` ? Thanks.

**Comment by drpngx** [comment]
This is the full log:

```
FAIL: //bazel_pip/tensorflow/python:queue_runner_test (see /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/testlogs/bazel_pip/tensorflow/python/queue_runner_test/test.log).
INFO: From Testing //bazel_pip/tensorflow/python:queue_runner_test:
==================== Test output for //bazel_pip/tensorflow/python:queue_runner_test:
2017-09-08 00:08:17.468320: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
.ERROR:tensorflow:Exception in QueueRunner: Fetch argument 'i fail' cannot be interpreted as a Tensor. ("The name 'i fail' refers to an Operation not in the graph.")
ERROR:tensorflow:Exception in QueueRunner: Fetch argument 'so fail' cannot be interpreted as a Tensor. ("The name 'so fail' refers to an Operation not in the graph.")
Exception in thread QueueRunnerThread-fifo_queue-so fail:
Traceback (most recent call last):
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 271, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3156, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3216, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'so fail' refers to an Operation not in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/training/queue_runner_impl.py", line 233, in _run
    enqueue_callable = sess.make_callable(enqueue_op)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1184, in make_callable
    fetch_handler = _FetchHandler(self._graph, fetches, {})
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 414, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 234, in for_fetch
    return _ListFetchMapper(fetch)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 341, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 341, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 242, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 281, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument 'so fail' cannot be interpreted as a Tensor. ("The name 'so fail' refers to an Operation not in the graph.")

Exception in thread QueueRunnerThread-fifo_queue-i fail:
Traceback (most recent call last):
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 271, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3156, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3216, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'i fail' refers to an Operation not in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/training/queue_runner_impl.py", line 233, in _run
    enqueue_callable = sess.make_callable(enqueue_op)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1184, in make_callable
    fetch_handler = _FetchHandler(self._graph, fetches, {})
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 414, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 234, in for_fetch
    return _ListFetchMapper(fetch)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 341, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 341, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 242, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 281, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument 'i fail' cannot be interpreted as a Tensor. ("The name 'i fail' refers to an Operation not in the graph.")

.............ERROR:tensorflow:Exception in QueueRunner: Fetch argument 'bad_op' cannot be interpreted as a Tensor. ("The name 'bad_op' refers to an Operation not in the graph.")
Exception in thread QueueRunnerThread-fifo_queue-bad_op:
Traceback (most recent call last):
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 271, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3156, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3216, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'bad_op' refers to an Operation not in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/training/queue_runner_impl.py", line 233, in _run
    enqueue_callable = sess.make_callable(enqueue_op)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1184, in make_callable
    fetch_handler = _FetchHandler(self._graph, fetches, {})
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 414, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 234, in for_fetch
    return _ListFetchMapper(fetch)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 341, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 341, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 242, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 281, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument 'bad_op' cannot be interpreted as a Tensor. ("The name 'bad_op' refers to an Operation not in the graph.")

ERROR:tensorflow:Exception in QueueRunner: Fetch argument 'bad_op' cannot be interpreted as a Tensor. ("The name 'bad_op' refers to an Operation not in the graph.")
Exception in thread QueueRunnerThread-fifo_queue-bad_op:
Traceback (most recent call last):
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 271, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3156, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3216, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'bad_op' refers to an Operation not in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/training/queue_runner_impl.py", line 233, in _run
    enqueue_callable = sess.make_callable(enqueue_op)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1184, in make_callable
    fetch_handler = _FetchHandler(self._graph, fetches, {})
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 414, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 234, in for_fetch
    return _ListFetchMapper(fetch)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 341, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 341, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 242, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/workspace/pip_test/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 281, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument 'bad_op' cannot be interpreted as a Tensor. ("The name 'bad_op' refers to an Operation not in the graph.")

...
----------------------------------------------------------------------
Ran 17 tests in 0.958s

OK
```

**Comment by facaiy** [comment]
Thank you very much, @drpngx. 
The stack trace is really odd for me. Could you please take a retest? I'll prepare a python3 environment for test later.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Jenkins, test this please.

(failing test should be fixed.)

**Comment by drpngx** [comment]
That doesn't seem to be related, can you check?

```
18:06:37  63/295 Test  #38: C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/python/kernel_tests/batch_matmul_op_test.py ..................................***Failed   27.18 sec
18:06:37 C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/python/kernel_tests/batch_matmul_op_test.py:181: ComplexWarning: Casting complex values to real discards the imaginary part
18:06:37   b * n * k).astype(dtype).reshape([b, n, k])
18:06:37 C:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/tensorflow/python/kernel_tests/batch_matmul_op_test.py:185: ComplexWarning: Casting complex values to real discards the imaginary part
18:06:37   b * k * m).astype(dtype).reshape([b, k, m])
```

**Comment by facaiy** [comment]
@drpngx We have tested the PR for three times, however,  different test case is broken in each time:

1.
2. //tensorflow/tools/api/tests:api_compatibility_test  
3. //tensorflow/python/kernel_tests:fft_ops_test 

It seems totally random? I try to create a py3 environment to reproduce it.

**Comment by drpngx** [comment]
Yes, the `fft_ops_test` seems to be a recent timeout. The queue runner test was fixed earlier today, and same for the `api_compatibility_test`. How about the `batch_matmul_op`, does that ring a bell?

**Comment by facaiy** [comment]
Thanks for your help, @drpngx . I am confused why the PR will break unit tests? Do you mean all failures are brought by its own test case, not the PR, right?

How about rebasing the PR on the latest master branch? Will it resolve all failures?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Ignoring `fft_ops_test` failure, fixed internally.

**Comment by drpngx** [comment]
Ignoring `fft_ops_test` which was fixed internally.

**Pull request merged**
