### PR TITLE
Remove references to the Bazel flag `--distinct_host_configuration`.

### PR DESCRIPTION
**Pull request by katre**
Part of https://github.com/bazelbuild/bazel/issues/17731.

### CODE REVIEW

**Comment by katre** [comment]
If you are not yet on Bazel 6.0 you can close this and I won't migrate you, but do note the the delta between Bazel 5 and the next release is growing.

**Comment by katre** [comment]
Also, the internal LSC may also send CLs that you'll need to tell me to revert.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by katre** [comment]
Thanks! What needs to be done to merge this?

**Comment by mihaimaruseac** [comment]
It will be imported by copybara, run more CI internally and then automatically merged.

**Pull request merged**
