### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by dheerajmpai**
Adding our Organizations. We extensively use tensorflow for all our AI applications.

(I am also confused why this page is empty)

### CODE REVIEW

**Comment by gbaned** [comment]
@dheerajpai  Can you please sign CLA. Thanks!

**Comment by gbaned** [comment]
@dheerajpai  Any update on this PR? Please. Thanks!

**Comment by dheerajmpai** [comment]
@googlebot I signed it!

**Comment by dheerajmpai** [comment]
@gbaned  Thanks so much for following up. I am quite surprised the adopter list is empty.

**Review by theadactyl — APPROVED** [review]
LGTM

**Comment by martinwicke** [comment]
Can we just delete this file? It's clearly not representative of actual adoption, and it's unclear what it could be used for.

**Comment by theadactyl** [comment]
Think that's probably wise. @dheerajmpai I don't believe this file gets a lot of traffic (as you may have noticed!). This might be better served on a tensorflow.org page. Can you let us know how you'd benefit from being listed, and we can point you in a better direction?

**Comment by gbaned** [comment]
@dheerajmpai  Can you please check @theadactyl's comments and keep us posted ? Thanks!

**Comment by dheerajmpai** [comment]
Sure @theadactyl makes sense to delete this file. By publishing our use cases of Tensorflow we would get a better outreach. Not much of a benefit otherwise.

**Comment by rthadur** [comment]
Thank you all , created a pull request [here](https://github.com/tensorflow/tensorflow/pull/42868) to delete the file.

**Pull request closed without merging**
