### PR TITLE
fix op does not dominate this use after mhlo-fusion pass

### PR DESCRIPTION
**Pull request by lipracer**
test: tests/mhlo-fusion.mlir: fused_unfused_mix

### CODE REVIEW

**Review by joker-eph — APPROVED** [review]
Thanks!
(it'll get in the queue for merging, no further action required from you right now)

**Comment by lipracer** [comment]
@joker-eph Sorry, What do I need to do? Why is the check display always pending?

**Comment by joker-eph** [comment]
You don't need to do anything, it is in the queue for merging, it has to go through our internal integration testing (this is "mostly automated", but not a super fast process): I expect it'll get merged today.

**Comment by lipracer** [comment]
> You don't need to do anything, it is in the queue for merging, it has to go through our internal integration testing (this is "mostly automated", but not a super fast process): I expect it'll get merged today.

Thank you for your answer, Programmer Daniel.

**Pull request merged**
