### PR TITLE
Extracting out tf.bin_values_fixed_width from tf.histogram_fixed_width.

### PR DESCRIPTION
**Pull request by nathansilberman**

### CODE REVIEW

**Comment by nathansilberman** [comment]
I signed it!

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by nathansilberman** [comment]
How can I visualize the jenkins logs remotely? All the tests pass locally (with both Python 3 and 2.7) so I need get access to the logs to determine why its failing via Jenkins.

**Comment by sb2nov** [comment]
https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/6999/console is an example of the link to the logs. I seem them in the review section below the comments on the PR.

```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/metrics/histogram_ops_test.runfiles/org_tensorflow/tensorflow/contrib/metrics/python/kernel_tests/histogram_ops_test.py", line 117, in test_large_class_imbalance_still_ok
    num_updates=1000)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/metrics/histogram_ops_test.runfiles/org_tensorflow/tensorflow/contrib/metrics/python/kernel_tests/histogram_ops_test.py", line 162, in _check_auc
    labels, scores, score_range, nbins=nbins)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/metrics/histogram_ops_test.runfiles/org_tensorflow/tensorflow/contrib/metrics/python/ops/histogram_ops.py", line 88, in auc_using_histogram
    score_range, nbins)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/metrics/histogram_ops_test.runfiles/org_tensorflow/tensorflow/contrib/metrics/python/ops/histogram_ops.py", line 138, in _make_auc_histograms
    name='hist_true')
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/metrics/histogram_ops_test.runfiles/org_tensorflow/tensorflow/python/ops/histogram_ops.py", line 138, in histogram_fixed_width
    indices = bin_values_fixed_width(values, value_range, nbins, dtype, scope)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/metrics/histogram_ops_test.runfiles/org_tensorflow/tensorflow/python/ops/histogram_ops.py", line 96, in bin_values_fixed_width
    return array_ops.reshape(indices, shape)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/metrics/histogram_ops_test.runfiles/org_tensorflow/tensorflow/python/ops/gen_array_ops.py", line 3920, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/metrics/histogram_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'shape' to a tensor and failed. Error: Cannot convert a partially known TensorShape to a Tensor: (?,)
```

**Review by jhseu — COMMENTED** [review]
Seems reasonable to me, but please fix the tests. It will need to go through API review, though.

I'm not fully sure what the best name is here. @aselle any opinions?

**Comment by nathansilberman** [comment]
Jenkins, test this please.

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by nathansilberman** [comment]
The only test that appears to be failing is the goldens tensorflow/tools/api/tests:api_compatibility_test which passes locally. As per the jenkins stdout, I ran:

```
    $ bazel build tensorflow/tools/api/tests:api_compatibility_test
    $ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test \
          --update_goldens True
```

but this did not appear to alter any files.

**Comment by nathansilberman** [comment]
Any thoughts on how to get the compatibility tests to pass?

**Comment by jhseu** [comment]
The golden files should be updated as part of this pull request. The --update_goldens flag should update the goldens. @gunan might have some thoughts as to why it's not working.

**Comment by gunan** [comment]
You need to use python2 to update goldens.
Sorry, I meant to document this for a long time now, but keep forgetting.

**Comment by nathansilberman** [comment]
Ran it locally using Python 2.7, no other files changed.

**Comment by gunan** [comment]
That is weird. Could you share the stdout when you run the following:
```
bazel-bin/tensorflow/tools/api/tests/api_compatibility_test --update_goldens True
```
Then you should check what `git status` outputs.

**Comment by nathansilberman** [comment]
```
(tf) Nathans-MacBook-Pro:tensorflow nathansilberman$ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test           --update_goldens True
s.
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK (skipped=1)
(tf) Nathans-MacBook-Pro:tensorflow nathansilberman$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   tensorflow/python/ops/histogram_ops_test.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.cache/
	tf/

no changes added to commit (use "git add" and/or "git commit -a")
(tf) Nathans-MacBook-Pro:tensorflow nathansilberman$ python --version
Python 2.7.10
(tf) Nathans-MacBook-Pro:tensorflow nathansilberman$
```

Note that the tf directory contains my virtual env and the histogram_ops_test.py change is a minor formatting change.

**Comment by gunan** [comment]
Is it possible in your local repository you have a commit not pushed to your remote branch?
Sorry for exploring possible issues on your end, I am also looking into why the test might be doing this.

**Comment by josh11b** [comment]
From api-review: I think I prefer the name "tf.histogram_fixed_width_bins" more than "tf.bin_values_fixed_width", and it would clearly indicate the connection to "tf.histogram_fixed_width".

**Comment by josh11b** [comment]
(otherwise fine for API review.)

**Comment by nathansilberman** [comment]
Updated the files, still seeing no differences when running the api_compatibility_test with --update_goldens=True. I'm not sure how to proceed here.

**Review by jhseu — APPROVED** [review]

**Comment by josh11b** [comment]
I think the API test requires Python 2.

**Comment by nathansilberman** [comment]
@josh11b I ran the tests using Python2:

```
(tf2) Nathans-MacBook-Pro:tf nathansilberman$ python --version
Python 2.7.10
(tf2) Nathans-MacBook-Pro:tf nathansilberman$ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test           --update_goldens True
s.
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK (skipped=1)
```

**Comment by gunan** [comment]
There is our problem:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/api/tests/api_compatibility_test.py#L194

Only runs on linux. I will check if we can enable this on other OSs.

**Comment by nathansilberman** [comment]
Any update on this?

**Comment by gunan** [comment]
I did not have time to see if on macos we can run the api compatibility checks without any changes.
could you run and update the api goldens under an ubuntu docker image?
You should be able to use our devel docker images to make the update.

Once that is ready, we can get another final nod for api review and merge the change.

**Comment by martinwicke** [comment]
@gunan, can we run compatibility in MacOS? If still unknown, is finding out as simple as running them to see whether there are differences in file handling (I thought you already fixed those anyway)?

**Comment by gunan** [comment]
It should be as simple as that. Never quite found the time to look into it though.

**Comment by drpngx** [comment]
@nathansilberman sorry the code has since changed, could you please pull rebase and push again?

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
@nathansilberman this is ready to be merge, only pull rebase and push again. Thanks.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Just double-checking @jhseu that the API change is fine.

**Comment by jhseu** [comment]
Yeah, this already went through API review. Good to merge.

**Comment by drpngx** [comment]
Thanks! @nathansilberman please update the goldens:

```
    $ bazel build tensorflow/tools/api/tests:api_compatibility_test
    $ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test \
          --update_goldens True
```

**Comment by nathansilberman** [comment]
Ran the goldens but it still doesn't seem to update anything on osx...

**Comment by jhseu** [comment]
@drpngx this has been sitting for a while for the same reason. Mind merging and then just submitting a golden fix as a followup?

**Comment by jhseu** [comment]
@benoitsteiner

**Comment by drpngx** [comment]
For some reason I can't merge.

@nathansilberman could you try to modify the goldens by hand?
https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/api/golden/tensorflow.pbtxt#L1160

**Comment by nathansilberman** [comment]
I see failures in MacOS Python2 but cannot replicate. I ran with:

```
bazel test -c opt --test_output=all --force_python=py2 tensorflow/tools/api/tests:api_compatibility_test
```
as well as the default args and everything passes...

**Comment by nathansilberman** [comment]
Apparently, I needed to re-run the goldens from python 2.7.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Woohoo!

**Comment by nathansilberman** [comment]
Phew, thanks for all your help guys!

**Pull request merged**
