### PR TITLE
[INTEL MKL] Install latest future module as part of pip installs

### PR DESCRIPTION
**Pull request by ashahba**
We need the latest `future` version otherwise we get:
```
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
Loading: 0 packages loaded
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (1 packages loaded, 0 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (3 packages loaded, 0 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (73 packages loaded, 30 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (295 packages loaded, 6382 targets configured)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins
ERROR: /tensorflow/tensorflow/core/BUILD:2778:1: no such package '@local_config_git//': Traceback (most recent call last):
	File "/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

 and referenced by '//tensorflow/core:version_info_gen'
ERROR: /tensorflow/tensorflow/core/BUILD:2778:1: no such package '@local_config_git//': Traceback (most recent call last):
	File "/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

 and referenced by '//tensorflow/core:version_info_gen'
ERROR: /tensorflow/tensorflow/core/BUILD:2778:1: no such package '@local_config_git//': Traceback (most recent call last):
	File "/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

 and referenced by '//tensorflow/core:version_info_gen'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@local_config_git//': Traceback (most recent call last):
	File "/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins
```

### CODE REVIEW

**Comment by ashahba** [comment]
This should also be cherry picked to `r1.14` branch.

**Comment by ashahba** [comment]
@agramesh1

**Comment by ashahba** [comment]
Hi @penpornk 
Any feedback on this would be highly appreciated.
We certainly want the change in `tensorflow/tools/ci_build/linux/mkl/Dockerfile.devel-mkl` file, the changes in the other file is just for keeping things consistent.

This issue is causing our `Python2.7` builds to fail so prioritizing it is highly appreciated.

**Review by penpornk — COMMENTED** [review]
The changes look fine to me, but I need to make sure that this won't negatively affect other things that depend on `future`. @gunan is a better reviewer for this.

@gunan Could you please take a quick look at this? Is it okay to up the version requirement of the `future` module?

Also tagging @bananabowl for more info on r1.14 release.

**Comment by gunan** [comment]
Looks like @av8ramit debugged a similar issue before.

**Comment by ashahba** [comment]
Looks like we are failing during `test_async_copy_reraise` here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training_utils_test.py#L406

**Comment by av8ramit** [comment]
Yes, installing latest future will resolve this

**Review by av8ramit — APPROVED** [review]

**Comment by bananabowl** [comment]
Thanks - please send me a PR for the r1.14 branch once this is merged

**Comment by ashahba** [comment]
@bananabowl it was submitted here for `r1.14`: #29233

**Pull request merged**
