### PR TITLE
[Tosa] Update Sin/Cos operators legalization

### PR DESCRIPTION
**Pull request by Jerry-Ge**
- with the introduction of tosa.sin and tosa.cos ops
- update the legalization to do direct mapping

### CODE REVIEW

**Comment by Jerry-Ge** [comment]
cc @jpienaar

**Comment by Jerry-Ge** [comment]
Hi @rdzhabarov or @jpienaar , could you help take a look at this PR? Thanks

**Comment by Jerry-Ge** [comment]
Hi @NatashaKnk, would you be able to do a review on this patch? thanks : )

**Comment by gbaned** [comment]
Hi @Jerry-Ge Can you please resolve conflicts? Thank you!

**Pull request closed without merging**
