### PR TITLE
[XLA] BufferComparator: add int8 support

### PR DESCRIPTION
**Pull request by yongfeng-nv**
As part of int8 convolution using CuDNN work, this is a necessary enhancement.  Previously this change is reviewed under https://github.com/tensorflow/tensorflow/pull/30783.

### CODE REVIEW

**Review by cheshire — CHANGES_REQUESTED** [review]
Tests?

Also, last argument (`__xla_int8_comparison`) refers to the PTX kernel name, yet no new kernel was added.

**Comment by cheshire** [comment]
Could we change it even more to prevent the possibility of such collisions in the future?
Eg __xla_buffer_comparator_canonicalize?

**Review by cheshire — APPROVED** [review]

**Review by cheshire — CHANGES_REQUESTED** [review]
Please change tabs to spaces

**Comment by cheshire** [comment]
@yongfeng-nv Sorry I had to revert this. The PTX version got bumped in the commit, is it possible to re-generate PTX with the version which was originally specified?

**Comment by yongfeng-nv** [comment]
@cheshire Sure.  I will be back to work on this next week.

**Pull request merged**
