### PR TITLE
Fallback to legacy camera API for problematic devices in android demo app

### LINKED ISSUE #8550: Android "TF Stylize" demo crash with "input_max_range must be larger than input_min_range"
I have compiled and installed the demo app according to the instruction in the [README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md).  The "TF Detect" and "TF Classify" apps are working as expected.  However, starting the "TF Stylize" app, it always crashes in about 3 seconds.  The prebuilt apk crashes in the same way.  Here is the android logcat recorded:

> $ adb -s b80360c7 logcat  | grep Tensor
I/TensorFlowInferenceInterface( 6801): Checking to see if TensorFlow native methods are already loaded
I/TensorFlowInferenceInterface( 6801): TensorFlow native methods not found, attempting to load via tensorflow_inference
I/TensorFlowInferenceInterface( 6801): Successfully loaded TensorFlow native methods (RunStats error may be ignored)
I/TensorFlowInferenceInterface( 6801): Model load took 540ms, TensorFlow version: 1.0.1
I/TensorFlowInferenceInterface( 6801): Successfully loaded model from 'file:///android_asset/stylize_quantized.pb'
E/TensorFlowInferenceInterface( 6801): Failed to run TensorFlow inference with inputs:[input, style_num], outputs:[transformer/expand/conv3/conv/Sigmoid]
E/TensorFlowInferenceInterface( 6801): Inference exception: java.lang.IllegalArgumentException: input_max_range must be larger than input_min_range.
E/TensorFlowInferenceInterface( 6801):   [[Node: transformer/contract/conv1/Relu_eightbit_quantize_transformer/contract/conv1/InstanceNorm/batchnorm/add_1 = QuantizeV2[T=DT_QUINT8, mode="MIN_FIRST", _device="/job:localhost/replica:0/task:0/cpu:0"](transformer/contract/conv1/InstanceNorm/batchnorm/add_1, transformer/contract/conv1/Relu_eightbit_min_transformer/contract/conv1/InstanceNorm/batchnorm/add_1, transformer/contract/conv1/Relu_eightbit_max_transformer/contract/conv1/InstanceNorm/batchnorm/add_1)]]
E/AndroidRuntime( 6801):        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.getTensor(TensorFlowInferenceInterface.java:486)
E/AndroidRuntime( 6801):        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.readNodeIntoFloatBuffer(TensorFlowInferenceInterface.java:332)
E/AndroidRuntime( 6801):        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.readNodeFloat(TensorFlowInferenceInterface.java:287)

As can be inferred from the logcat, the problem happens in `tensorflow/core/kernels/quantize_op.cc` line 71.  The app is using a quantized model.  I found that `input_min_range` is set to be `inf`, and `input_max_range` is `-inf`, which is obviously wrong.

What should be done to fix it?

The crash appears on Samsung Galaxy S4, but does not appears on emulator with Intel CPU.

[Edit]
With more experiment I found that sometimes the apps works without crashing, about 1 out of 10 trials.

### PR DESCRIPTION
**Pull request by BrianOn99**
Fix #8550 
The camera 2 API is problematic in some devices.  Similar problem is also dicussed in #7464 .  One of the problem is shown here on a LG G4c device:
screenshot_2017-03-27-00-47-09

A space inversion is taken (left-right mirrored), and color turns green (which is reported also here https://code.google.com/p/android/issues/detail?id=81984).  It effectively makes all 3 demo app not working or crashes.

This PR attempts to take legacy camera API as fallback, in case `INFO_SUPPORTED_HARDWARE_LEVEL` is lower than FULL.  It is mostly a copy of the implementation [here](https://github.com/hamidb/tensorflow/blob/api20/tensorflow/examples/android/src/org/tensorflow/demo/CameraConnectionFragment.java).  Here is the working demo if fallback is taken:
screenshot_2017-03-27-00-48-19

I would like to mention that I have no previous experience with the API, so the implementation may not be optimal.  Also please check if the demo still works on Android6+ devices because I only have 2 android5 for testing.  Please also notice that the "TF Detect" demo does not show red box on preview image, for which I cannot find out the cause.

screenshot_2017-03-27-00-35-07

### CODE REVIEW

**Comment by BrianOn99** [comment]
I signed it!

**Comment by yifeif** [comment]
@andrewharp could you take a look? Thanks!

**Review by andrewharp — COMMENTED** [review]
Thank you for doing this!

A couple of high-level comments before a full review:

1) CameraActivity.java should probably handle any references to android.hardware.Camera or android.hardware.camera2, and the CameraActivity class implementations should just implement a method that takes a byte[] for each plane. This will keep the actual demo classes from all having parallel implementations of the adapter code.

2) I've added functionality for choosing hard-coded preferred preview sizes internally available to help address #7464, and that should be getting pushed soon, so this this will PR will have to account for that on the android.hardware.Camera side as well.

**Comment by BrianOn99** [comment]
I agree that I have made the demo a bit more complicated and that should be avoided.

**Comment by BrianOn99** [comment]
Please also notice that I have hard-coded rotation to be 90 in the legacy camera API, and I don't know how to set it properly.

**Comment by drpngx** [comment]
@BrianOn99 Could you pull rebase and push again?
@andrewharp is there any better way to set the rotation in the legacy camera API?

**Comment by andrewharp** [comment]
@drpngx @BrianOn99 The demo currently assumes a 90 degree rotation, so I don't see an issue with this, unless I'm misunderstanding something. It should be something we can leave a TODO for and fix for both implementations at a later time.

**Comment by BrianOn99** [comment]
@drpngx So do I need to `git push --force`?

**Comment by drpngx** [comment]
Did you rebase from upstream/master? I think it's usually fine to push force in that case. But do save the SHA1s in case you need to go back to them.

**Comment by BrianOn99** [comment]
During rebase I get this error:

```
~/A/t/tensorflow ❯❯❯ bazel build --jobs=2 -c opt //tensorflow/examples/android:tensorflow_demo                                           ⏎ master ✱ ◼
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/DataType.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/Graph.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/NativeLibrary.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/Operation.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/OperationBuilder.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/Output.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/SavedModelBundle.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/Session.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/Shape.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/Tensor.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/TensorFlow.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/TensorFlowException.java' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:58:12: in srcs attribute of android_library rule //tensorflow/contrib/android:android_tensorflow_inference_java: please do not import '//tensorflow/java:src/main/java/org/tensorflow/package-info.java' directly. You should either move the file to this package or depend on an appropriate rule there.
ERROR: /home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/contrib/android/BUILD:72:1: error loading package 'tensorflow/core': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Traceback (most recent call last):
	File "/home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/workspace.bzl", line 98
		_apply_patch(repo_ctx, repo_ctx.attr.patch_file)
	File "/home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/workspace.bzl", line 87, in _apply_patch
		_execute_and_check_ret_code(repo_ctx, ["patch", "-p1", "-d", r...), <2 more arguments>])
	File "/home/o/AndroidStudioProjects/ttens/tensorflow/tensorflow/workspace.bzl", line 79, in _execute_and_check_ret_code
		fail("Non-zero return code({1}) when ..., <2 more arguments>))
Non-zero return code(256) when executing 'patch -p1 -d /home/o/.cache/bazel/_bazel_o/18da53e8d12eeb6697178b6abb9cee58/external/protobuf -i /home/o/AndroidStudioProjects/ttens/tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout: 
Stderr: java.io.IOException: Cannot run program "patch" (in directory "/home/o/.cache/bazel/_bazel_o/18da53e8d12eeb6697178b6abb9cee58/external/protobuf"): error=2, No such file or directory and referenced by '//tensorflow/contrib/android:libtensorflow_inference.so'.
ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted.
```

I cannot find such a build issue from the internet.  Even a fresh clone and build from master give this issue, while building from my old branch still works.  Any one has idea?

**Comment by BrianOn99** [comment]
I am building in this environment:
bazel 0.4.5
arch linux
tensorflow commit 34c738cc6d3badcb22e3f72482536ada29bd0e65

**Comment by BrianOn99** [comment]
git bisect tells me the offending commit is 8d393ea2fab0ea88ecd11e36d89f186cbc884dbe.  Looks like due to the changes in `tensorflow/workspace.bzl`?

**Comment by drpngx** [comment]
@jart any idea what might be happening here?

@BrianOn99 please rebase and push again when you get a chance.

**Comment by jart** [comment]
Is the program `patch` installed from the Arch package manager?

**Comment by BrianOn99** [comment]
@jart yes

**Comment by BrianOn99** [comment]
@jart It is installed from the package manager as far as I can remember.  I will verify it tonight.

**Comment by BrianOn99** [comment]
You are right patch is not installed :-P.  Never thought of this stupid mistake.  Now it has been rebased.  Again, I have not tested it on Android6+ devices.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
It does not appear to build

```
ERROR: in target '//external:android/crosstool': no such package '@androidndk//': /home/o/Android/android-ndk-r12b (No such file or directory).
```

**Comment by BrianOn99** [comment]
Pushed again and should be OK now.

**Comment by andrewharp** [comment]
We probably don't want any references to android.hardware.Camera or android.hardware.Camera2 in the Activity classes, apart from CameraActivity. Right now there are 3 methods in each activity for handling incoming frames -- I think we can reduce that to 1 if possible and let CameraActivity itself handle supporting the different camera hardwares.

**Comment by vrv** [comment]
ping for @BrianOn99 for next steps!

**Comment by BrianOn99** [comment]
@andrewharp @vrv The main reason for this quite messy implementation is:
1. Some clean-up code is required for Camera ( specifically `camera.addCallbackBuffer(bytes);`), but nor for Camera2.
2. In `DetectorActivity`, the luminance plane is required.  There is different code for the Camera and Camera2 API to extract the luminace plane from a YUV420 format.  If we hide the difference between the API by giving just an RBGA buffer, it makes the luminance plane difficult to extract.  In fact I don't really understand how `DetectorActivity` works so I hope someone else can help.

**Comment by andrewharp** [comment]
@BrianOn99 I suppose you could modify the method prototype to also take in an optional luminance plane. I think that would be better than having Camera references and duplicate processing code creeping into the actual Activity implementations.

Regarding camera.addCallbackBuffer(bytes) perhaps just have two buffers and return the old one when you get the new one.

**Comment by vrv** [comment]
ping for @BrianOn99 !

**Comment by rmlarsen** [comment]
@BrianOn99 any update on this?

**Comment by BrianOn99** [comment]
@rmlarsen I don’t yet have time to improve the code.  You are welcome to fix it.

**Comment by osdamv** [comment]
Hello, I am working refactoring the android demo to work with the camera api1 but I am having troubles with the tracker detector(DetectorActivity.java around line 250) 
```
 final Plane[] planes = image.getPlanes();
      fillBytes(planes, yuvBytes);

      tracker.onFrame(
          previewWidth,
          previewHeight,
          planes[0].getRowStride(),
          sensorOrientation,
          yuvBytes[0],
          timestamp);
trackingOverlay.postInvalidate();
```
that object requires a rowStride wich is provided by the camera api 2 Image object, but  the camera api1 just provides a simple byte[] `public void onPreviewFrame(final byte[] bytes, final Camera camera) `
Any ideas how can I code that section fore the camera api1?

**Comment by andrewharp** [comment]
@osdamv You should be able to assume that width == stride when using the camera 1 api. This is always the case afaik.

**Comment by drpngx** [comment]
@osdamv any luck with this?

**Comment by osdamv** [comment]
@drpngx I can't make work the detector demo with the legacy api, however the another examples work fine .
The class MultiBoxTracker(its job is draw the boxes, the detection works fine) pretty much assumes everything would have the api2, IMHO  the detector demo requieres a lot of more of refactoring and sadly is a part I don't need for my project, if you wish I can upload my changes

**Comment by andrewharp** [comment]
@osdamv The object detector demo is able to work without tracking support (it does this when it can't find the native libraries), so if you want, just disable tracking when in fallback mode and I can fix that functionality later.

**Comment by osdamv** [comment]
Is there any format needed for the commit message?

**Comment by andrewharp** [comment]
@osdamv For individual commits? Not really, just a blurb about what code changed. The overall PR description is what gets mentioned in the changelog.

**Comment by BrianOn99** [comment]
Please see #8736 for a this PR improved by @osdamv .

**Comment by jubjamie** [comment]
@osdamv has done some great work with that pull request but the detector demo is still problematic. Not sure whether this issue is fully resolved. Although @andrewharp said he would try and find some time to fix the misbehaving code. I guess the detector issue could be continued on #10348 perhaps?

**Pull request closed without merging**
