### PR TITLE
Just want to confirm if this failure is intended

### PR DESCRIPTION
**Pull request by scottcjt**
I have a model acts like the test case attached. If tested with tf-v1.8 (which I previously worked on), incorrect dims will be output. If tested with *master*, a recently added assertion in `tensorflow/lite/simple_memory_arena.cc:100` will be triggered.

To reproduce the error, posting test case is simpler. So even if this PR is more like an issue report, please kindly allow me to post here and ask if model like this is a misuse? Or it is not supported by TFLite? Thanks.

### CODE REVIEW

**Comment by scottcjt** [comment]
I signed it!

**Comment by jdduke** [comment]
Is there any chance you can attach your model as well? There can be subtle differences between a loaded model and trying to manually construct it in a test.

**Comment by scottcjt** [comment]
Sure. I just realized there is Python front-end for TFLite now :) So it is possible to reproduce it in single Python script:

OS: Ubuntu Linux 18.04 LTS
Python & TF version:

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow                                                                                                                                                                                   

In [2]: tensorflow.__version__                                                                                                                                                                              
Out[2]: '1.13.1'
```

Reproduce steps:

```python
import numpy as np
import tensorflow as tf


i = tf.placeholder(dtype=tf.float32, shape=[2, 2, 1, 1])
p = tf.placeholder(dtype=tf.int32, shape=[4, 2])
a = tf.placeholder(dtype=tf.float32, shape=[1])

n = tf.negative(a)
o = tf.add(tf.pad(i, p), n)

test_input = np.array([[[[0]], [[0]]],[[[0]], [[0]]]], dtype=np.float32)
test_pad = np.array([[2,2],[2,2],[0,0],[0,0]], dtype=np.int32)
test_pad_2 = np.array([[4,4],[4,4],[0,0],[0,0]], dtype=np.int32)
test_a = np.array([1], dtype=np.float32)


def test_tf():
    with tf.Session() as sess:
        out = sess.run(o, {i: test_input, p: test_pad, a: test_a})
        assert out.shape == (6, 6, 1, 1)

        out = sess.run(o, {i: test_input, p: test_pad_2, a: test_a})
        assert out.shape == (10, 10, 1, 1)

test_tf()


# convert
with tf.Session() as sess:
    conv = tf.lite.TFLiteConverter.from_session(sess, [i, p, a], [o])
    lite_model_bytes = conv.convert()


def test_tflite():
    interp = tf.lite.Interpreter(model_content=lite_model_bytes)

    #### I just hard-coded them:
    # print(interp.get_input_details())
    # print(interp.get_output_details())

    interp.allocate_tensors()
    interp.set_tensor(3, test_input)
    interp.set_tensor(4, test_pad)
    interp.set_tensor(5, test_a)

    interp.invoke()
    assert interp.get_tensor(0).shape == (6, 6, 1, 1)

    interp.set_tensor(4, test_pad_2)

    interp.invoke()
    assert interp.get_tensor(0).shape == (10, 10, 1, 1)

test_tflite()
```

**Comment by jdduke** [comment]
Awesome, thanks for the minimal repro! Just to confirm, is [this the line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/simple_memory_arena.cc#L100) that is failing in your local repro?

If this graph works properly in TF, then it should also behave properly in TFLite, so it's most likely a bug or an issue with conversion. Feel free to file a bug in parallel while we investigate.

**Comment by scottcjt** [comment]
> Awesome, thanks for the minimal repro! Just to confirm, is [this the line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/simple_memory_arena.cc#L100) that is failing in your local repro?

Yes. I got following console output:

```
RuntimeError: tensorflow/lite/simple_memory_arena.cc:100 erased_allocs_count != 1 (0 != 1)
```

If changing input and paddings to other reasonable values, we can get similar error like this one:

```
RuntimeError: tensorflow/lite/simple_memory_arena.cc:93 it->size != alloc.size (36 != 4)
```

> If this graph works properly in TF, then it should also behave properly in TFLite, so it's most likely a bug or an issue with conversion. Feel free to file a bug in parallel while we investigate.

IMHO arena is not properly reset in some cases. If we force arena to re-compute before every invocation, this issue won't happen. But it is kind ugly...

**Comment by jdduke** [comment]
So, I'm not able to repro the error from your Python test case, but I do see it with the native unit test case. Looking into it now.

**Comment by jdduke** [comment]
I'm going to close the PR, but we're tracking this internally. If you want to file a separate issue that would be helpful, as it very likely could be a legit bug.

**Comment by scottcjt** [comment]
Ops have to be in specific order to trigger this, so we probably still need the model file to figure out. I posted the issue and model file here: #26549.

**Pull request closed without merging**
