### PR TITLE
Implementation of 8-bit quantized mean in TFLu

### PR DESCRIPTION
**Pull request by patriklaurell**

### CODE REVIEW

**Review by njeffrie — DISMISSED** [review]

**Comment by rthadur** [comment]
Here is the internal error please check 

`In file included from third_party/tensorflow/lite/micro/kernels/reduce.cc:16:
./third_party/tensorflow/lite/kernels/internal/reference/reduce.h:360:17: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
    if (current > (std::numeric_limits<U>::max() / num_elements_in_axis)) {
        ~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/tensorflow/lite/micro/kernels/reduce.cc:115:26: note: in instantiation of function template specialization 'tflite::reference_ops::QuantizedMeanOrSum<signed char, int>' requested here
          reference_ops::QuantizedMeanOrSum(
                         ^
In file included from third_party/tensorflow/lite/micro/kernels/reduce.cc:16:
./third_party/tensorflow/lite/kernels/internal/reference/reduce.h:360:17: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
    if (current > (std::numeric_limits<U>::max() / num_elements_in_axis)) {
        ~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/tensorflow/lite/micro/kernels/reduce.cc:124:22: note: in instantiation of function template specialization 'tflite::reference_ops::QuantizedMeanOrSum<unsigned char, int>' requested here
      reference_ops::QuantizedMeanOrSum(`

**Comment by gbaned** [comment]
@patriklaurell Can you please check @rthadur's comments and keep us posted. Thanks!

**Comment by patriklaurell** [comment]
On hold. We found an issue with this that needs to be fixed.

**Comment by patriklaurell** [comment]
accidentally rebased. will create new PR with appropriate changes. my apologies

**Pull request closed without merging**
