### PR TITLE
[tf.data] Increase default buffer size to 256 MB

### PR DESCRIPTION
**Pull request by byronyi**
A larger buffer size brings better throughput at the cost of buffer bloat.

### CODE REVIEW

**Comment by byronyi** [comment]
Ping @frankchn @mrry to review

**Review by jsimsa — CHANGES_REQUESTED** [review]
This change should not happen. The TODO is stale and should be removed.

**Review by jsimsa — APPROVED** [review]

**Comment by byronyi** [comment]
@jsimsa Any rationale behind the introduction and removal of this particular TODO? We'd like to fix it the first time as we observed small buffer size might not be optimal for certain storage options, e.g. HDFS.

**Comment by jsimsa** [comment]
The reason why the TODO is removed is that there is no one right buffer size that makes sense for all possible storage systems and changing this value to be 1000x bigger would affect memory usage of existing uses that would not necessarily benefit from it.

This TODO was introduced by someone when integration between TensorFlow and GCS was being worked on but for the same reason as stated above, it was not a good idea and instead, the storage system specific buffering was performance in the storage system client.

**Pull request merged**
