### PR TITLE
Adding processing to FinddBatchNormV2 and FinddBatchNormV3 in the opt…

### PR DESCRIPTION
**Pull request by SmokerX**
…imize method

### CODE REVIEW

**Comment by gbaned** [comment]
@jhseu Can you please take a look on this PR? Thanks!

**Comment by gbaned** [comment]
@SmokerX Can you please resolve conflicts? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 16 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
