### PR TITLE
tf.sparse.SparseTensor and tf.repeat doc

### PR DESCRIPTION
**Pull request by Angus-Luo**
- Afaik, tf.SparseTensor is currently just an alias for tf.sparse.SparseTensor. But since the later might get removed in the future, suggest replacing usage with the more consistent alias.

- Change "repeat" to "tf.repeat" for consistency in this doc and easier to copy and experiment with the code.

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
@Angus-Luo Can you please address Ubuntu Sanity errors? Thanks!

**Comment by gbaned** [comment]
@Angus-Luo Still,  Ubuntu Sanity errors appearing. Can you please check? Thanks!

**Comment by mihaimaruseac** [comment]
pylint fails. Please donwload the sanity log and locate the pylint error.

**Comment by Angus-Luo** [comment]
> pylint fails. Please donwload the sanity log and locate the pylint error.

Thank you, I will try it soon.

**Pull request closed without merging**
