### PR TITLE
[TFLM] Added a platform specific micro_time.cc for CEVA-DSP BX1 and SP500

### PR DESCRIPTION
**Pull request by yair-ehrenwald**
Added code calling into CEVA's clock so the micro profiler can be used

### CODE REVIEW

**Review by advaitjain — CHANGES_REQUESTED** [review]
You might prefer using system_setup.cc to avoid having state in the micro_time functions. See sparkfun_edge and arduino as examples.

You'll have to still keep empty micro_time.cc and/ or debug_log.cc depending on what all needs to be specialized for your target.

**Comment by yair-ehrenwald** [comment]
> You might prefer using system_setup.cc to avoid having state in the micro_time functions. See sparkfun_edge and arduino as examples.
> 
> You'll have to still keep empty micro_time.cc and/ or debug_log.cc depending on what all needs to be specialized for your target.

Done.
The micro_time.cc isn't empty as the clock() function we use isn't the standard one.

**Review by advaitjain — APPROVED** [review]

**Comment by advaitjain** [comment]
> > You might prefer using system_setup.cc to avoid having state in the micro_time functions. See sparkfun_edge and arduino as examples.
> > You'll have to still keep empty micro_time.cc and/ or debug_log.cc depending on what all needs to be specialized for your target.
> 
> Done.
> The micro_time.cc isn't empty as the clock() function we use isn't the standard one.

If you prefer to have all the functions in system_setp.cc then you can keep micro_time.cc empty. There is no requirement that micro_time.h be implemented in micro_time.cc

I prefer that since it gives me a single file with all the code (time, debug_log and init). But whatever you prefer. I have approved this PR and we can merge it as-is.

**Comment by yair-ehrenwald** [comment]
> > > You might prefer using system_setup.cc to avoid having state in the micro_time functions. See sparkfun_edge and arduino as examples.
> > > You'll have to still keep empty micro_time.cc and/ or debug_log.cc depending on what all needs to be specialized for your target.
> > 
> > 
> > Done.
> > The micro_time.cc isn't empty as the clock() function we use isn't the standard one.
> 
> If you prefer to have all the functions in system_setp.cc then you can keep micro_time.cc empty. There is no requirement that micro_time.h be implemented in micro_time.cc
> 
> I prefer that since it gives me a single file with all the code (time, debug_log and init). But whatever you prefer. I have approved this PR and we can merge it as-is.

NP, moved everything into system_setup.cc

**Comment by advaitjain** [comment]
> > > > You might prefer using system_setup.cc to avoid having state in the micro_time functions. See sparkfun_edge and arduino as examples.
> > > > You'll have to still keep empty micro_time.cc and/ or debug_log.cc depending on what all needs to be specialized for your target.
> > > 
> > > 
> > > Done.
> > > The micro_time.cc isn't empty as the clock() function we use isn't the standard one.
> > 
> > 
> > If you prefer to have all the functions in system_setp.cc then you can keep micro_time.cc empty. There is no requirement that micro_time.h be implemented in micro_time.cc
> > I prefer that since it gives me a single file with all the code (time, debug_log and init). But whatever you prefer. I have approved this PR and we can merge it as-is.
> 
> NP, moved everything into system_setup.cc

Apologies, this PR was already in the merge queue at the time of your latest update.

https://github.com/tensorflow/tensorflow/commit/871c66bd6fb833358aca6c51f5a4af1f147855b7 has all the changes (except for the consolidation in system_setup.cc).

I'll close this PR. If you could make a new PR for the consolidation in system_setup.cc, that would be great.

**Pull request closed without merging**
