### PR TITLE
fixed mkl sgemm call

### PR DESCRIPTION
**Pull request by mslacken**
gemm called used *float instead of Float
see: https://intel.github.io/mkl-dnn/group__dnnl__api__blas.html

### CODE REVIEW

**Review by alextp — APPROVED** [review]

**Comment by gbaned** [comment]
@mslacken Could you please check failed build errors? Thanks!

**Comment by mslacken** [comment]
@gbaned Is it possible that the Ubuntu CPU tests has the proprietary Intel Math Kernel library installed. There the calls for dnnl_sgemm may differ.

**Comment by gbaned** [comment]
@alextp Can you please assist with the above query from @mslacken? Thanks!

**Comment by alextp** [comment]
@penpornk do you know the answer?

**Comment by penpornk** [comment]
DNNL (MKL-DNN v1.x) is only used with TF-MKL build (--config=mkl). Stock TensorFlow is still using MKL-DNN v0.x, whose sgemm interface is incompatible with v1.x. There is nothing to fix here. (I'll fix them when we update stock TF to v1.x later after the 2.2 branch cut.)

**Comment by penpornk** [comment]
More details:

- Stock TensorFlow (`@mkl_dnn`) currently uses MKL-DNN [v0.21.3](https://github.com/tensorflow/tensorflow/blob/dd662a9228b0f94ed2527f4117f2bef62e0aad00/tensorflow/workspace.bzl#L171).
- [eigen_contraction_kernel](https://github.com/tensorflow/tensorflow/blob/dd662a9228b0f94ed2527f4117f2bef62e0aad00/tensorflow/core/kernels/BUILD#L824) depends on `@mkl_dnn`.
- [conv_grad_input_ops](https://github.com/tensorflow/tensorflow/blob/dd662a9228b0f94ed2527f4117f2bef62e0aad00/tensorflow/core/kernels/BUILD#L4516) depends on `eigen_contraction_kernel`.
- [Here](https://github.com/intel/mkl-dnn/blob/4f5d024fc84cff5995b440eeaee3fda6385dd970/include/mkldnn.h#L1797-L1801) is the sgemm interface in v0.21.3 (`const float* alpha` and `const float* beta`). 

So the existing `sgemm` calls are correct and shouldn't be fixed.

**Comment by mslacken** [comment]
@penpornk Thanks for you clarification. I encountered this issue as I am using the system mkl-dnn which is at version 1.1.3.
One good news is that this calls seem the only incompatibility so far.

**Comment by penpornk** [comment]
@mslacken Got it. Thank you for the explanation! Stock TensorFlow only uses two routines from MKL-DNN: [mkldnn_sgemm](https://github.com/tensorflow/tensorflow/blob/a898220ce412b3ede459b7ed6c0bd0660aacb97a/tensorflow/core/kernels/eigen_contraction_kernel.h#L166-L168) and [mkldnn_s8u8s32](https://github.com/tensorflow/tensorflow/blob/a898220ce412b3ede459b7ed6c0bd0660aacb97a/tensorflow/core/kernels/eigen_contraction_kernel.h#L231-L238). So there can't be many incompatibilities to begin with.

We plan to also switch to MKL-DNN v1.2 for stock TF in the near future. If you'd like to use v1.x before that, please feel free to apply the fix locally in the meanwhile. Note that another difference between v0.x and v1.x is that v0.x assumes matrices are in column major order and v1.x assumes row-major. Please account for that too if you do make the changes. 

However, I'd suggest staying with v0.21.3 to save your time, because v1.2 doesn't have any noticeable performance improvements from v0.21.3 for `sgemm`. I'll ping this thread once stock TF also switches to v1.2.

**Comment by muziker** [comment]
Hi, i'm compiling this but with --config=cuda. I was under the impression --config=mkl would use this, but if --config=cuda would not.

**Comment by penpornk** [comment]
@muziker Yes, only --config=mkl would use MKL-DNN v1.x. Vanilla TF and --config=cuda (and all other configurations that runs on non-mobile devices) are still using MKL-DNN v0.21.3.

**Pull request closed without merging**
