### PR TITLE
Make non-standard cudnn paths work again

### PR DESCRIPTION
**Pull request by sjperkins**
This corrects #9634 for me.

### CODE REVIEW

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Review by rmlarsen — DISMISSED** [review]

**Comment by rmlarsen** [comment]
Hmm this doesn't appear to be the right fix. It breaks the test builds with:

 tensorflow/stream_executor/cuda/cuda_dnn.cc:43:24: fatal error: cuda/cudnn.h: No such file or directory
 #include "cuda/cudnn.h"

**Comment by rmlarsen** [comment]
@sjperkins Can you take another look?

**Comment by sjperkins** [comment]
Hey @rmlarsen. I had a quick look, but no luck. Apologies, I don't have more to spend on this at present :-(

**Comment by jthestness** [comment]
I was able to fix this a different way without changing the relative include path in `tensorflow/stream_executor/cuda/cuda_dnn.cc`:
```diff --git a/third_party/gpus/cuda_configure.bzl b/third_party/gpus/cuda_configure.bzl
index 6994db0..dad0d83 100644
--- a/third_party/gpus/cuda_configure.bzl
+++ b/third_party/gpus/cuda_configure.bzl
@@ -875,8 +875,8 @@ def _create_cuda_repository(repository_ctx):
   included_files = _read_dir(repository_ctx, cuda_include_path).replace(
       cuda_include_path, '').splitlines()
   if '/cudnn.h' not in included_files:
-    genrules.append(_symlink_genrule_for_dir(repository_ctx, None, "",
-        "cudnn-include", [cudnn_header_dir + "/cudnn.h"], ["include/cudnn.h"]))
+    genrules.append(_symlink_genrule_for_dir(repository_ctx, cudnn_header_dir,
+        "include", "cudnn-include"))
   else:
     genrules.append(
             'filegroup(\n' +
```

Will continue testing to whether to open an alternative PR

**Comment by rmlarsen** [comment]
@jthestness yeah, that looks better. Feel free to submit an alternative PR.

**Comment by sjperkins** [comment]
Closing in favour of alternative solutions. I'm not going to have time to look at this soon.

**Pull request closed without merging**
