### PR TITLE
Fix file exists error

### PR DESCRIPTION
**Pull request by yilinjuang**
In function `tf.train.write_graph`, first check if `logdir` exists, then write file in "w" or "wb" mode depends on `as_text`

### CODE REVIEW

**Comment by frankyjuang** [comment]
I signed it!

**Comment by vrv** [comment]
(squash the commits once this is done and i'll run a quick test before merging)

**Comment by frankyjuang** [comment]
@vrv, done, thanks

**Comment by vrv** [comment]
@tensorflow-jenkins, test this please.

**Comment by vrv** [comment]
(ugh, give us some time to fix our CI testing, sorry)

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by vrv** [comment]
@martinwicke: why is one check stuck?

**Comment by martinwicke** [comment]
We're working on it. Looking good though, I think we can merge (I'll take the beating if I'm wrong).

**Pull request merged**
