### PR TITLE
Added Keras Import for Linting

### PR DESCRIPTION
**Pull request by pky00**
Added Keras Import to when Type Checking so linting and highlighting works for the dynamically imported keras library

### CODE REVIEW

**Review by mihaimaruseac — COMMENTED** [review]
What issue is this PR resolving? It looks very strange and I'm inclined to reject it if there's no proof it solves a real issue.

**Comment by pky00** [comment]
When using the keras imported from tensorflow `tensorflow.keras` , keras doesnt get linted because keras is dynamically imported, making developing much harder. Adding the keras module statically only when type checking enables linting making development easier.

**Comment by mihaimaruseac** [comment]
But now keras will no longer be lazily imported, I think?

Can you open an issue on tf-keras repo and have some discussion there first, please?

**Comment by keerthanakadiri** [comment]
Hi @pky00, Can you please sign CLA , thank you !

**Comment by pky00** [comment]
@keerthanakadiri Done !

@mihaimaruseac Can u provide a link to that repo ?

**Comment by mihaimaruseac** [comment]
https://github.com/keras-team/tf-keras/

**Pull request closed without merging**
