### PR TITLE
fix gdr compiling error

### PR DESCRIPTION
**Pull request by byronyi**

### CODE REVIEW

**Review by jhseu — APPROVED** [review]

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by byronyi** [comment]
CMake build aborts again, seems to be unrelated.

**Comment by byronyi** [comment]
@jhseu Jonathan, could you merge this when you have time? Thanks!

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by byronyi** [comment]
CI server seems to fail on fetching Git.

**Comment by byronyi** [comment]
@jhseu Can we just merge this? The CI seems to be constantly broken, and the fix is straight forward.

**Pull request merged**
