### PR TITLE
Tidy up tf_tests.cmake and reenable tests that are not failing anymore.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Review by mrry — APPROVED** [review]
Thanks for cleaning this up!

**Comment by mrry** [comment]
Looks like tensorflow/python/training/coordinator_test.py failed :(. I think this is the same issue you fixed in `saver_test.py` (in ee50560b5fd2b1112e82377d7d094a0e6918f935) where `time.sleep()` doesn't sleep for long enough on Windows, and can lead to flakiness. Would it be easy to port the same solution?

**Comment by mrry** [comment]
(Disabling the test in this PR is also a reasonable approach, though :).)

**Comment by gunan** [comment]
I will follow this test internally.
I am really surprised it has not been more flaky.

**Pull request merged**
