### PR TITLE
[Linaro:ARM_CI] Limit the version of h5py that is allowed to prevent ftb

### PR DESCRIPTION
**Pull request by elfringham**

### CODE REVIEW

**Comment by elfringham** [comment]
@penpornk This should fix ARM_CI pipeline

**Review by penpornk — APPROVED** [review]
Thank you for the fix!

**Review by penpornk — COMMENTED** [review]
@nitins17  Is there a way to limit the constraint to just aarch64? Or are you okay with applying the limit on all platforms?

**Comment by elfringham** [comment]
@penpornk @nitins17 I am working on an alternative fix that will not add a constraint to h5py but will instead allow h5py to be built by the ARM_CI docker container. ie it will fix the hdf5 dependency. This will take maybe a couple of hours to confirm working though.

**Review by nitins17 — APPROVED** [review]

**Comment by nitins17** [comment]
LGTM, thanks Andrew!

There seem to be tests that fail with `ImportError: cannot import name 'estimator_export' from 'tensorflow.python.util.tf_export'` due to https://github.com/tensorflow/tensorflow/commit/3837d0f28cb1812878dd8b21aecf283b06f5617c. Rebuilding the Dockerfile to get the latest version of tf-estimator-nightly should fix it.

**Pull request merged**
