### PR TITLE
Avoid unnecessary `for` cycle overhead for `tf.gfile.Glob`

### PR DESCRIPTION
**Pull request by firejq**
Avoid unnecessary `for` cycle overhead to speed up `tf.gfile.Glob` in v1.15.x.

Thanks for your review.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Do we want this only against 1.15?

**Comment by firejq** [comment]
@mihaimaruseac Thanks for your reply! It is indeed a general improvement but for [v2.x](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/file_system_helper.cc#L135), I have found that there is no this unnecessary `for` cycle anymore. As v1.15 is the latest (& last?) version for v1.x, I put this pr only against 1.15.

Of course, this may just be my immature idea. May you have any better suggestions?

**Comment by mihaimaruseac** [comment]
We no longer update TF 1.x code, unless for security patches. It is better to reopen against master and then cherrypick if needed.

**Comment by firejq** [comment]
@mihaimaruseac Thanks for your relpy!  I have make some optimizion against master #44269 and I will close this pr.

**Pull request closed without merging**
