### PR TITLE
Upgrade gRPC

### PR DESCRIPTION
**Pull request by jhseu**
Just Jenkins testing for now.

### CODE REVIEW

**Comment by jhseu** [comment]
This is ready for review. The only test failures are the same failures that are in https://github.com/tensorflow/tensorflow/pull/11789.

Reasons for some changes:
- protobuf -> protobuf_archive because //external:protobuf is now depended on in grpc. That needs to be a bind rule, unfortunately.
- grpc.patch and the grpc cmake files are only needed until these pull requests are submitted:
https://github.com/grpc/grpc/pull/11944
https://github.com/grpc/grpc/pull/11933

Once those are submitted, then we can switch to the BUILD and cmake files that are in the grpc repo.
- A bunch of classes were renamed. See b/62910646

**Comment by jhseu** [comment]
The cmake file is a direct copy of the grpc one with a single line deletion (patching isn't so easy in vanilla cmake).

**Comment by jhseu** [comment]
Also thanks to @llhe for his work on the older version of this change that we couldn't merge because of Windows issues.

**Comment by jhseu** [comment]
Forgot to mention:
- bazel clean is needed in the CI scripts due to the protobuf -> protobuf_archive rename. We should probably leave them in for a week or so and then remove them.

**Review by vrv — APPROVED** [review]
Looks fairly mechanical, so approving.  Nice work!

See https://github.com/tensorflow/tensorflow/pull/9376/commits/24d8d498b30f458486393674fb58be6c11006796 for a related PR where I manually added protobuf_headers -- depending on which gets merged first, we'll have to update this one or the other one.

**Comment by vrv** [comment]
Let me know if you feel confident merging this now.

**Comment by nlopezgi** [comment]
This CL broke sandboxed builds due to missing dependencies.
Sample error message:
#include <grpc++/impl/codegen/proto_utils.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR: .../github/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:225:1: Couldn't build file tensorflow/core/distributed_runtime/rpc/_objs/grpc_master_service_impl/tensorflow/core/distributed_runtime/rpc/grpc_master_service_impl.pic.o: C++ compilation of rule '//tensorflow/core/distributed_runtime/rpc:grpc_master_service_impl' failed (Exit 1)

**Pull request merged**
