### PR TITLE
[ROCm] Hipsparse version of Sparse Add Operation

### PR DESCRIPTION
**Pull request by stevenireeves**
Bringing hipsparseXcsrgeam to Tensorflow for sparse add operations on ROCm enabled devices. 

Builds on https://github.com/tensorflow/tensorflow/pull/49108 to flesh out Hipsparse functionality for Tensorflow.

### CODE REVIEW

**Comment by stevenireeves** [comment]
@cheshire this is now ready for review.

**Comment by gbaned** [comment]
@stevenireeves  Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@stevenireeves  Can you please resolve conflicts? Thanks!

**Comment by stevenireeves** [comment]
@gbaned, some of the functions needed from https://github.com/tensorflow/tensorflow/pull/49108 were reverted. These need to be addressed before this can move forward.

**Comment by stevenireeves** [comment]
@gbaned looks like the cancellation of the rollback removed the conflict. It should be ready to proceed.

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Pull request merged**
