### PR TITLE
Add gradient op for MaxPoolWithArgmax

### LINKED ISSUE #1793: Missing gradient for tf.nn.max_pool_with_argmax
I swapped out the first max_pool operation in [convolutional.py](https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/models/image/mnist/convolutional.py) tutorial for a max_pool_with_argmax operation and there doesn't seem to exist a gradient for that op:

`(virtenv)$ python convolutional.py`
`Extracting data/train-images-idx3-ubyte.gz`
`Extracting data/train-labels-idx1-ubyte.gz`
`Extracting data/t10k-images-idx3-ubyte.gz`
`Extracting data/t10k-labels-idx1-ubyte.gz`
`Traceback (most recent call last):`
`File "convolutional.py", line 316, in <module>`
`tf.app.run()`
`File "/home/name/virtenv/local/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run`
`sys.exit(main(sys.argv))`
`File "convolutional.py", line 244, in main`
`global_step=batch)`
`File "/home/name/virtenv/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 190, in minimize`
`colocate_gradients_with_ops=colocate_gradients_with_ops)`
`File "/home/name/virtenv/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 241, in compute_gradients`
`colocate_gradients_with_ops=colocate_gradients_with_ops)`
`File "/home/name/virtenv/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 453, in gradients`
`(op.name, op.type))`
`LookupError: No gradient defined for operation 'MaxPoolWithArgmax' (op type: MaxPoolWithArgmax)`
### Environment info

Operating System: Ubuntu 14.04.1 LTS

If installed from binary pip package, provide:

(virtenv)$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
(virtenv)$ python -c "import tensorflow; print(tensorflow.**version**)"
0.7.1
### Steps to reproduce
1. Change line 192-5 of [convolutional.py](https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/models/image/mnist/convolutional.py) from:
   
   `pool = tf.nn.max_pool(relu, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')`
   
   to:
   
   `pool, pos = tf.nn.max_pool_with_argmax(relu, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')`
2. Run:
   
   `(virtenv)$ python convolutional.py`
### What have you tried?

1.
### Logs or other output that would be helpful

(If logs are large, please upload as attachment).

### PR DESCRIPTION
**Pull request by Enet4**
This is a reattempt of #4014, which fixes #1793.

### CODE REVIEW

**Comment by drpngx** [comment]
Jenkins, test this please.

@keveman what do you think?

**Review by keveman — APPROVED** [review]

**Comment by Enet4** [comment]
Hopefully yes, although I've only tested it on the GPU myself. That was IIRC the same error message I had before this fix.

**Comment by Datadude88** [comment]
Awesome to hear! I'm pretty new to this; how would I go about updating to the latest version that's on here? Been looking to use this. Thanks again!

**Comment by Enet4** [comment]
Until the next release, you may have to install from the master branch. See [Installing TensorFlow from Sources](https://www.tensorflow.org/install/install_sources).

**Comment by zhenbangchen** [comment]
Still seems not to be working on CPUs. Thanks guys!
`tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxPoolWithArgmax' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>`

**Comment by tfboyd** [comment]
reopened,  the PR I referenced as verified that it does not work on CPU by @zhenbangchen above.  Thank you for checking.

**Comment by Enet4** [comment]
Is there a clue on what should be done here to achieve CPU support?

**Pull request merged**
