### PR TITLE
Improvements to ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by nealwu**
Removed the asterisks from the "must complete" section and the shell tag because when users see this template, they will see the unformatted markdown, not the formatted version.

Fixed the last sentence as well.

See also https://github.com/tensorflow/models/pull/1340. Will submit an update to that issue template as well.

### CODE REVIEW

**Comment by aselle** [comment]
The point of the asterisks is to make it easier for the triager to see if they have added answers to the questions.

**Comment by nealwu** [comment]
I see, makes sense. Added them back.

**Review by aselle — APPROVED** [review]

**Comment by nealwu** [comment]
I'm very confused about this pull request. Did it not make it in properly? I don't see the changes in https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md nor in [the history](https://github.com/tensorflow/tensorflow/commits/master/ISSUE_TEMPLATE.md).

**Comment by drpngx** [comment]
So you can look at
```
git log --graph --oneline --decorate --all
```
I traced a survivor `fdbeae662` and its lineage dies in `a5b1fb8e5` (aka #9289), which was a forward push.
@caisq did you see any merge errors?

**Comment by caisq** [comment]
@nealwu @drpngx it is possible that I took only internal and ignored external when resolve the merge conflicts. Sorry if that's the case. In any case, I sent out another PR to fix it: https://github.com/tensorflow/tensorflow/pull/9385

**Comment by drpngx** [comment]
Thank you @caisq! As long as it's not a script issue, we're good.

**Pull request merged**
