### PR TITLE
[Intel MKL] Adding Quantized Convolution (Int8) - Part 2

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR is part 2 of four PRs that add quantized version of convolution using MKL-DNN. This part enables MKL quantized convolution kernel in the graph pass.

Please note that the below PRs replace this old one #19425 
Part 1: #21483 
Part 2: #21456 
Part 3: #21465 
Part 4: #21466

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @tatianashp, @raghuraman-k: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 20 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @tatianashp, @raghuraman-k: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 35 days with no activity and the `awaiting review` label has been applied.

**Review by raghuraman-k — DISMISSED** [review]

**Comment by drpngx** [comment]
@mahmoud-abuzaina could you look into the failures?

**Comment by mdfaijul** [comment]
@drpngx ran clang-format.

**Comment by drpngx** [comment]
@raghuraman-k good to go?

**Comment by mdfaijul** [comment]
@drpngx Any update on this PR?

**Review by tatianashp — APPROVED** [review]

**Comment by mdfaijul** [comment]
@drpngx @tatianashp I don't think failures related to our contribution. Could you please let us know.

**Comment by agramesh1** [comment]
@drpngx We can't access the details for the feedback/copybara. Can you provide us more info on the failure?

**Comment by drpngx** [comment]
Waiting for check & approval from @tatianashp

**Comment by tatianashp** [comment]
I reviewed and approved. All checks pass. Let me know if you need anything else.

**Pull request merged**
