### PR TITLE
Added tests for tensors, inputs, outputs, opcodes

### PR DESCRIPTION
**Pull request by amitsrivastava78**
This was one of the TODO, just complete the same

### CODE REVIEW

**Comment by gbaned** [comment]
@alanchiao Could you PTAL and approve.

**Comment by gbaned** [comment]
@alanchiao can you please review this PR ?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alanchiao: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alanchiao: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 30 days with no activity and the `awaiting review` label has been applied.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gunan** [comment]
Closing as a duplicate of https://github.com/tensorflow/tensorflow/pull/25809

**Pull request closed without merging**
