### PR TITLE
Modernize TF_CPP_VMODULE handling using absl

### PR DESCRIPTION
**Pull request by sanjoy**
This gets rid of the custom StringData struct since flat_hash_map
supports heterogenous lookups.

### CODE REVIEW

**Review by kkimdev — APPROVED** [review]

**Comment by gbaned** [comment]
@sanjoy  Can you please address Ubuntu Sanity errors? Thanks!

**Comment by gbaned** [comment]
@sanjoy Any update on this PR? Please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@sanjoy Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@sanjoy Any update on this PR? Please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 19 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 59 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
