### PR TITLE
Rename CONCAT_EMBEDDINGS to CONCATENATE_EMBEDDINGS"

### PR DESCRIPTION
**Pull request by siju-samuel**
TODO item done, Rename CONCAT_EMBEDDINGS to CONCATENATE_EMBEDDINGS

### CODE REVIEW

**Review by karimnosseir — DISMISSED** [review]

**Comment by siju-samuel** [comment]
@rthadur gentle ping to merge this PR. TIA

**Comment by siju-samuel** [comment]
@rthadur gentle ping to merge this PR. TIA

**Comment by rthadur** [comment]
@siju-samuel sorry for the delay , can you please resolve conflicts.

**Comment by siju-samuel** [comment]
@karimnosseir please approve again. needed to rebased due to the movement of nnapi file change.

**Comment by siju-samuel** [comment]
@karimnosseir Gentle ping to check and approve again. This PR is rebased due to recent changes.

**Comment by rthadur** [comment]
@siju-samuel thanks for your contribution,we don't think this changes is necessary, so closing this PR.

**Pull request closed without merging**
