### PR TITLE
Fixed minor typos

### PR DESCRIPTION
**Pull request by kyscg**
Mega typo fix PR, review pleasee @rthadur @dynamicwebpaige ?????

### CODE REVIEW

**Comment by rthadur** [comment]
@kyscg please rebase your branch

**Comment by kyscg** [comment]
Where should I rebase it to? I'm new to this, sorry if I'm holding up stuff

**Comment by rthadur** [comment]
> Where should I rebase it to? I'm new to this, sorry if I'm holding up stuff

rebase to master , i mean resolve conflicts.

**Review by chsigg — DISMISSED** [review]
Thanks for fixing the typos. I will resolve and merge the change.

**Review by chsigg — APPROVED** [review]

**Comment by kyscg** [comment]
Hi, why isn't this being merged, should I make anything better? @rthadur @chsigg

**Comment by kyscg** [comment]
@rthadur Gentle ping to pull, all changes have been approved

**Comment by chsigg** [comment]
It's not being merged because tests fail (the exception check is case sensitive). I will fix it and submit.

**Pull request merged**
