### PR TITLE
issue #4252

### PR DESCRIPTION
**Pull request by aaalgo**
tensorflow/contrib/makefile/tf_pb_text_files.txt missing a couple of items.
[Issue #4252](https://github.com/tensorflow/tensorflow/issues/4252)

### CODE REVIEW

**Comment by aaalgo** [comment]
I signed it!

**Comment by danmane** [comment]
@mrry / @keveman  / @martinwicke would any of you be suited to review this?

**Comment by mrry** [comment]
Makefile issues are usually @petewarden's speciality, so I'm deferring to his wisdom :).

**Comment by martinwicke** [comment]
Yeah don't be fooled by the bot! :) I think the ifdef in core is something
to look at though. I don't know what the IS_SLIM_BUILD is, but I expect it
to be mobile related.

**Comment by petewarden** [comment]
Thanks! I've actually been trying to keep the zlib-related stuff out of the mobile builds entirely at the source file level, so on my local build I've actually got `$(wildcard tensorflow/core/lib/io/zlib*) \` added to the `CORE_CC_EXCLUDE_SRCS` definition in the Makefile. Unfortunately it's part of a larger change that I haven't been able to check in yet, but if that's enough information to reproduce would you be able to try that approach?

Thanks for your help maintaining this, I do appreciate it!

**Comment by martinwicke** [comment]
@petewarden is this redundant with your other PR?

**Comment by petewarden** [comment]
Yes, I believe #4287 fixed this issue, so I'm closing this.

**Pull request closed without merging**
