### PR TITLE
Fix error caused by incorrect rank assumption in tf.image.flip_left_right

### LINKED ISSUE #40580: tf.image.flip_left_right and tf.image.flip_up_down incorrectly assumes rank-3 image and flips along the wrong axis
## System information
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, see below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.0
- Python version: 3.7

You can also obtain the TensorFlow version with:
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
`unknown 2.0.0`

## Describe the current behavior

**Setup:** Under some circumstances (in my case, when a `tf.Tensor` is inside a `tf.data.Dataset` and it is being conditionally transformed inside a `tf.data.Dataset.map()` call), the shape of a `Tensor` becomes unknown (this may be expected behavior still).

**Behavior**: When `tf.image.flip_left_right` is applied to this `tf.Tensor`, the function incorrectly assumes a rank-3 shape and flips the image along the wrong axis.

## Describe the expected behavior

When `tf.image.flip_left_right` is applied to the `tf.Tensor`, the function does not assume a rank-3 shape and flips the image along the correct axis.

## Standalone code to reproduce the issue

```py
import tensorflow as tf

def correct_image_flip_left_right(image):
    return tf.reverse(image, axis=[-2])

PATCH_TF = False  # Change this to True to fix the bug
if PATCH_TF:
    tf.image.flip_left_right = correct_image_flip_left_right

image_input = tf.convert_to_tensor([
    # batch: 0
    [
        # y: 0
        [[0, 1, 2], [3, 4, 5]],  # x=0,1 channels=0,1,2
        # y: 1
        [[6, 7, 8], [9, 10, 11]],  # x=0,1 channels=0,1,2
    ],
])

image_flipped_directly = tf.image.flip_left_right(image_input)

expected_output = tf.convert_to_tensor([
    # batch: 0
    [
        # y: 0
        [[3, 4, 5], [0, 1, 2]],  # x=0,1 channels=0,1,2
        # y: 1
        [[9, 10, 11], [6, 7, 8]],  # x=0,1 channels=0,1,2
    ],
])

tf.assert_equal(image_flipped_directly, expected_output)
print("Directly calling tf.image.flip_left_right works as exected.")

def generator():  yield image_input

dataset = tf.data.Dataset.from_generator(generator, output_types=tf.int32)

def flip_it(image, do_flip: bool):
    if do_flip:
        return tf.image.flip_left_right(image)
    else:
        return image

dataset = dataset.map(lambda image: flip_it(image, tf.constant(True)))

image_flipped_via_dataset_map = next(iter(dataset))

print("image_flipped_via_dataset_map:")
print(image_flipped_via_dataset_map)
print("expected_output:")
print(expected_output)

tf.assert_equal(image_flipped_via_dataset_map, expected_output)
# This assertion fails even though it shouldn't unless PATCH_TF is True

print("If you can see this message, image_flipped_via_dataset_map == expected_output")
```

Output:
```
> python .\tf_image_flip.py
2020-06-18 17:10:08.875275: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Directly calling tf.image.flip_left_right works as exected.
image_flipped_via_dataset_map:
tf.Tensor(
[[[[ 6  7  8]
   [ 9 10 11]]

  [[ 0  1  2]
   [ 3  4  5]]]], shape=(1, 2, 2, 3), dtype=int32)
expected_output:
tf.Tensor(
[[[[ 3  4  5]
   [ 0  1  2]]

  [[ 9 10 11]
   [ 6  7  8]]]], shape=(1, 2, 2, 3), dtype=int32)
Traceback (most recent call last):
  File ".\tf_image_flip.py", line 54, in <module>
    tf.assert_equal(image_flipped_via_dataset_map, expected_output)
  File "C:\Users\uib58003\AppData\Local\Continuum\miniconda3\lib\site-packages\tensorflow_core\python\ops\check_ops.py", line 456, in assert_equal_v2
    return assert_equal(x=x, y=y, summarize=summarize, message=message, name=name)
  File "C:\Users\uib58003\AppData\Local\Continuum\miniconda3\lib\site-packages\tensorflow_core\python\ops\check_ops.py", line 546, in assert_equal
    (message or '', index_and_values_str, summary_msg)))
tensorflow.python.framework.errors_impl.InvalidArgumentError:
Condition x == y did not hold.
Indices of first 3 different values:
[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 2]]
Corresponding x values:
[6 7 8]
Corresponding y values:
[3 4 5]
First 3 elements of x:
[6 7 8]
First 3 elements of y:
[3 4 5]
```

## Other info / logs

The bug is in `tensorflow_core.ops.image_ops_impl._flip`, called by `image_ops_impl.flip_left_right`:
https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/ops/image_ops_impl.py#L537-L546

Tensorflow should not assume based on `shape.ndims is None` that the image is 3-dimensional and it should not call `fix_image_flip_shape` which further builds on this incorrect assumption:
https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/ops/image_ops_impl.py#L315-L320

This causes the flipping to happen along the wrong axis.

The `flip_left_right` function should be implemented by `array_ops.reverse(image, axis=[-2])` which always flips along the correct axis for any number of ranks as long as the dimensions end in `..., HEIGHT, WIDTH, CHANNELS]`.

The same bug probably appears in `tf.image.flip_up_down` for the same reason based on looking at the source code, but I haven't tested this. That function should always apply `tf.reverse(image, axis=[-3])` for the same reason as before.

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to address the issue raised in #40580 where an error
was thrown out when tf.image.flip_left_right process a tensor of unknown
rank.

The reason was that tf.image.flip_left_right assumes rank == 3 in case
of unknown rank.

This PR adjust to use array_ops.rank(image) to obtain the true rank
when unknown rank is present.

This PR fixes #40580.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by yongtang** [comment]
Thanks @mihaimaruseac for the review. The PR has been updated and ` next(iter(dataset))` has been converted to `get_single_element(dataset.take(1))`. This should resolve the graph mode failure I think. Please take a look and let me know if the issue still exists.

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
Tests are still failing :(

This is `tensorflow/python:image_ops_test:FlipTransposeRotateTest.testFlipImageUnknownShape`
```
Traceback (most recent call last):
  File ".../tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File ".../tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File ".../tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
google3.third_party.tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int32, but the yielded element was Tensor("Const:0", shape=(1, 2, 2, 3), dtype=int32).
Traceback (most recent call last):

  File ".../tensorflow/python/data/ops/dataset_ops.py", line 843, in generator_py_func
    ret, dtype=dtype.as_numpy_dtype))

  File ".../tensorflow/python/ops/script_ops.py", line 205, in _convert
    result = np.asarray(value, dtype=dtype, order="C")

  File ".../numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)

TypeError: __array__() takes 1 positional argument but 2 were given
```

**Comment by yongtang** [comment]
Thanks @mihaimaruseac for the help. The failure very much looks like related to shape is not passed in generator. I have added additional parameter to `from_generator`. Think this might solve the internal test issue. 

I have updated the PR. Please take a look and see if the issue still exist.

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
Hmm, I am seeing the same error

**Comment by mihaimaruseac** [comment]
Let's try to resync copybara import to make sure all changes are in.

**Comment by mihaimaruseac** [comment]
Yes, same error with the latest commit included :(

**Comment by gbaned** [comment]
@yongtang, @mihaimaruseac Any update on this PR? Please. Thanks!

**Comment by yongtang** [comment]
@gbaned I will take a look, sorry for the late reply.

**Comment by gbaned** [comment]
@yongtang  Any update on this PR? Please. Thanks!

**Comment by yongtang** [comment]
@mihaimaruseac The PR has been updated by switch from usage of tf.constant to np.array inside the generator. This will avoid calling extra layer conversion between tf and numpy. I think this might resolve the issue. Can you give it a try? Sorry for the extra inconvenience.

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
