### PR TITLE
accelerate crf_log_norm

### PR DESCRIPTION
**Pull request by wanguanglu**
the base `crf_log_norm` function looks very cool, but it runs very slow.
I run the experiment on cpu
```
model name  : Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
```

I use the configure
```python
batch_size=128
max_seq_len=200
```
it runs `0.5s` per batch

when I optimize the realization way
it  runs `0.25s` per batch

### CODE REVIEW

**Comment by wanguanglu** [comment]
i have signed google cla use email mail@wanguanglu.com and GitHub Account Name wanguanglu

**Comment by vrv** [comment]
Can you git commit --amend with the correct git email config set to mail@wanguanglu.com ?

https://patch-diff.githubusercontent.com/raw/tensorflow/tensorflow/pull/6203.patch shows you probably don't have the right commit email set in your git config.

**Comment by wanguanglu** [comment]
OK, I try again

**Comment by wanguanglu** [comment]
i tried again by change the `.gitconfig`. it's OK now, thank you.

**Pull request closed without merging**
