### PR TITLE
Branch 178260923

### PR DESCRIPTION
**Pull request by ankurtaly**

### CODE REVIEW

**Comment by ankurtaly** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Review by caisq — APPROVED** [review]

**Comment by caisq** [comment]
Can you change `no_mac` to `nomac`, @ankurtaly ? Yes, it is a little inconsistent with other tags.

**Comment by caisq** [comment]
Actually, I'll merge this now since it's just a single test failing. I'll send a PR to fix the tag.

**Pull request merged**
