### PR TITLE
Fix seg fault in micro_speech_test on ppc64le.

### LINKED ISSUE #24148: [ppc64le] //tensorflow/lite/experimental/micro unit test fail.
You can assign this issue to me, as I'm about ready to submit a PR to fix this.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux ppc64le Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): commit 92854f2426c2b91f2b09831696ffebb5b793933d from Dec 4th, 2018
- Python version: 2.7
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu/IBM 5.4.0-6ubuntu1~16.04.10)
- CUDA/cuDNN version: N/A 
- GPU model and memory: N/A

**Describe the current behavior**
All tensorflow/lite/experimental/micro unit test fail
See: https://powerci.osuosl.org/job/TensorFlow_PPC64LE_CPU_Build_and_Test/31/testReport/

**Describe the expected behavior**
All unit test pass

**Code to reproduce the issue**
Unit test invoked by Jenkins:
`./tensorflow/tools/ci_build/ci_build.sh cpu --dockerfile tensorflow/tools/ci_build/Dockerfile.cpu.ppc64le ./tensorflow/tools/ci_build/linux/ppc64le/cpu/run_py2.sh`

`./tensorflow/tools/ci_build/linux/ppc64le/cpu/run_py2.sh` can be modified to just run `//tensorflow/lite/experimental/micro/...`

Also the getting started section here recreates two of the issues:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro

**Other info / logs**
Running the getting started example: make -f tensorflow/lite/experimental/micro/tools/make/Makefile test_micro_speech

This warning below is flagged and run the test runs it seg faults. As I understand the warning is because your not allowed to pass a string constant in this case. (It works however on x86)

```
g++ -O3 -DNDEBUG --std=c++11 -g -DTF_LITE_STATIC_MEMORY -I. -Itensorflow/lite/experimental/micro/tools/make/../../../../../ -Itensorflow/lite/experimental/micro/tools/make/../../../../../../ -Itensorflow/lite/experimental/micro/tools/make/downloads/ -Itensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/experimental/micro/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/experimental/micro/examples/micro_speech/micro_speech_test.cc -o tensorflow/lite/experimental/micro/tools/make/gen/linux_ppc64le/obj/tensorflow/lite/experimental/micro/examples/micro_speech/micro_speech_test.o

In file included from tensorflow/lite/experimental/micro/examples/micro_speech/micro_speech_test.cc:22:0:
tensorflow/lite/experimental/micro/examples/micro_speech/micro_speech_test.cc: In function 'int main(int, char**)':
./tensorflow/lite/experimental/micro/testing/micro_test.h:95:51: warning: ISO C++ forbids converting a string constant to 'va_list {aka char*}' [-Wwrite-strings]
   micro_test::reporter->Report("Testing %s", #name);                       \
                                                   ^
tensorflow/lite/experimental/micro/examples/micro_speech/micro_speech_test.cc:28:1: note: in expansion of macro 'TF_LITE_MICRO_TEST'
 TF_LITE_MICRO_TEST(TestInvoke) {
 ^~~~~~~~~~~~~~~~~~
```

Fixing it and running the example: make -f tensorflow/lite/experimental/micro/tools/make/Makefile test identifies the same problem in another place:

```
g++ -O3 -DNDEBUG --std=c++11 -g -DTF_LITE_STATIC_MEMORY -I. -Itensorflow/lite/experimental/micro/tools/make/../../../../../ -Itensorflow/lite/experimental/micro/tools/make/../../../../../../ -Itensorflow/lite/experimental/micro/tools/make/downloads/ -Itensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/experimental/micro/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/experimental/micro/micro_error_reporter_test.cc -o tensorflow/lite/experimental/micro/tools/make/gen/linux_ppc64le/obj/tensorflow/lite/experimental/micro/micro_error_reporter_test.o
tensorflow/lite/experimental/micro/micro_error_reporter_test.cc: In function 'int main(int, char**)':
tensorflow/lite/experimental/micro/micro_error_reporter_test.cc:24:56: warning: ISO C++ forbids converting a string constant to 'va_list {aka char*}' [-Wwrite-strings]
   error_reporter->Report("~~~%s~~~", "ALL TESTS PASSED");
                                                        ^
```

Fixing that allows the make test to complete, but when running inside of bazel some test still fail because they fail to compile:

```
ERROR: ^[[0m/workspace/tensorflow/lite/experimental/micro/examples/micro_speech/BUILD:185:1: Couldn't build file tensorflow/lite/experimental/micro/examples/micro_speech/feature_provider_test_binary: Linking of rule '//tensorflow/lite/experimental/micro/examples/micro_speech:feature_provider_test_binary' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /mnt/pai/home/wdirons/tmp/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-9.2 \
    CUDNN_INSTALL_PATH=/usr/local/cuda-9.2 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    OMP_NUM_THREADS=1 \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python2 \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=3.7 \
    TF_CUDA_VERSION=9.2 \
    TF_CUDNN_VERSION=7 \
    TF_NCCL_VERSION='' \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/ppc-opt/bin/tensorflow/lite/experimental/micro/examples/micro_speech/feature_provider_test_binary -Wl,-no-as-needed -pie -Wl,-z,relro,-z,now '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -no-canonical-prefixes -fno-canonical-system-headers -B/usr/bin -Wl,--gc-sections -Wl,@bazel-out/ppc-opt/bin/tensorflow/lite/experimental/micro/examples/micro_speech/feature_provider_test_binary-2.params)
/usr/bin/ld: bazel-out/ppc-opt/bin/tensorflow/lite/experimental/micro/examples/micro_speech/libpreprocessor_reference.a(preprocessor.o): undefined reference to symbol 'cos@@GLIBC_2.17'
//lib/powerpc64le-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line

```
Passing the link option "-lm" resolves this error. The makefile already does this.

### PR DESCRIPTION
**Pull request by wdirons**
Building micro_speech_test with the same compiler options as on x86, leads to the warnings:
... /micro/testing/micro_test.h:95:51: warning: ISO C++ forbids converting a string constant to 'va_list {aka char*}'
... /micro/micro_error_reporter_test.cc:24:56: warning: ISO C++ forbids converting a string constant to 'va_list {aka char*}'

And running the test program leads to a seg fault, for what I understand the standard for c++11
doesn't allow for a constant string to be used with %s substitution.

Another fix was to add the "-lm" link option when compiling on ppc64le, this avoided compile errors like:
undefined reference to symbol 'cos@@GLIBC_2.17'

This fixes several failing unit testcases on ppc64le, and causes no regression
errors on x86.

Fixes #24148

### CODE REVIEW

**Comment by wdirons** [comment]
@petewarden , Can you please review these changes?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by wdirons** [comment]
@petewarden , Could you please review or select someone else to review?

@ymodak - Can I enlisted your help nagging someone to review this ?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @achowdhery: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @petewarden, @achowdhery: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Review by petewarden — DISMISSED** [review]
Sorry for the delay on reviewing! This looks good, thanks.

**Comment by ymodak** [comment]
@wdirons Can you please take a look at the failed test builds? Thanks!

**Comment by wdirons** [comment]
I have no idea how to view the internal CI build failures. I can try again with the latest code on x86 ubuntu and make sure the test still pass.

**Comment by wdirons** [comment]
@ymodak , I verified the fix works fine with the latest code on x86 ubuntu python 2.  I have no idea how to view google's internal ci build failures, can you retry the test and if they fail, provide some details on why?

**Comment by ymodak** [comment]
@wdirons Thanks for the update. Re triggered the tests now.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by rthadur** [comment]
@wdirons  can you please fix build errors ?

**Comment by wdirons** [comment]
I tried to rebase the pull request with the latest changes. That didn't work. I'm just going to close the PR and open another if I need to.

**Pull request closed without merging**
