### PR TITLE
Adding an install sources line for 1.5.0-rc0. Earlier we only updated…

### PR DESCRIPTION
**Pull request by av8ramit**
… this for official.

### CODE REVIEW

**Review by gunan — CHANGES_REQUESTED** [review]
Why not windows?

**Comment by av8ramit** [comment]
@gunan for Windows we list the cmake version as that is what is technically supported.

**Comment by gunan** [comment]
But we should still add all the compiler, cmake and CUDA/cuDNN versions we use to build TF on windows.

**Comment by av8ramit** [comment]
Ah my mistake.

**Review by gunan — APPROVED** [review]

**Review by angerson — APPROVED** [review]

**Pull request merged**
