### PR TITLE
Test ramfs walk on win

### LINKED ISSUE #48086: tf.io.gfile.walk broken on Windows
It seems that the path isn't split correctly. Filenames come with an extra `\` prefix. Minimal reproducible example:

```python3
import os
import tensorflow as tf


tf.io.gfile.makedirs("ram://folder")
with tf.io.gfile.GFile("ram://folder/file.txt", mode="w") as f:
    f.write("data")

for root, _, filenames in tf.io.gfile.walk("ram://folder"):
    for filename in filenames:
        assert tf.io.gfile.exists(os.path.join(root, filename))
```

This passes on *nix but not on Windows. Here is a quick CI run in GitHub actions showing this: https://github.com/adriangb/tensorflow-test/actions/runs/688190284

ccing @mihaimaruseac @bhack

### PR DESCRIPTION
**Pull request by bhack**
Explore fixes https://github.com/tensorflow/tensorflow/issues/48086

### CODE REVIEW

**Comment by bhack** [comment]
@mihaimaruseac @frankchn  This is almost working. If we want to go ahead with `ram://` + native sep we need to just see what we want to do for `DeleteRecurively` cause `JoinPath` is not virtual and the parent `JoinPathImpl` has the `/` separator hardcoded.

**Comment by frankchn** [comment]
@bhack Thanks for doing this. I think we can just `#define` the implementation of `FileSystem::Separator()` like what we are doing here, then get `FileSystem::JoinPathImpl` to use `FileSystem::Separator`.

**Comment by bhack** [comment]
@frankchn Bazel cache was invalidated again.  So It will need hours of compile time as usual to test it locally again.

I've added a black box commit in the case you can test there with RBE or any with any other faster resource.

**Review by frankchn — APPROVED** [review]

**Comment by bhack** [comment]
@frankchn Do you have a Windows host to test this? It is very slow to iterate over Windows CI passes

**Comment by frankchn** [comment]
I don't unfortunately :(

**Comment by bhack** [comment]
Can you mention anyone in the team who can review it on window host?

**Comment by frankchn** [comment]
@bhack Yeah that looks unrelated.

@gbaned Can you check?

**Comment by adriangb** [comment]
@frankchn @bhack if I understand correctly, this is formally defining that the `ram://` filesystem will now support Windows path separators. Is that the intention?

**Comment by bhack** [comment]
Any idea?

**Comment by bhack** [comment]
@mihaimaruseac What do you think?

**Review by frankchn — APPROVED** [review]

**Comment by adriangb** [comment]
> @frankchn @bhack if I understand correctly, this is formally defining that the `ram://` filesystem will now support Windows path separators. Is that the intention?

Hi, sorry to bump this, I never got a response. Thanks.

**Comment by frankchn** [comment]
Yeah, on Windows this will use Windows style `\` separators

**Comment by adriangb** [comment]
> Yeah, on Windows this will use Windows style \ separators

As far as I can tell, supporting `\` isn't strictly necessary (although it also doesn't really hurt anything). And isn't that technically adding new features that would then need to be maintained?

**Comment by frankchn** [comment]
Yeah this isn't adding anything new, so support load shouldn't be too high.

**Comment by adriangb** [comment]
Currently, support for `\` on Windows is "undefined". I'd think that by adding this you are now establishing it as "defined". But in any case, this came from #39609 failing. Which is caused by `os.path.join` introducing `\`s in Windows. I just want to postulate that an alternative to implementing support for `\` is to keep TF itself from producing `\` on Win by replacing `os.path.join` with something that is aware the of the multiple TF filesystems. It can then collect other scattered workarounds like this one. But if you want to implement and support `\` regardless, that's totally okay, it won't hurt anything. I just want to make it clear that it is not the only way to resolve the original issue.

**Comment by frankchn** [comment]
@adriangb Yeah, that's fair, but I think in general people expect `os.path` stuff to work with file system accesses rather than using TF specific functions so I think in general perhaps we should have the principle of least surprise here and support this use case for the RAM file system?

**Comment by bhack** [comment]
> @adriangb Yeah, that's fair, but I think in general people expect `os.path` stuff to work with file system accesses rather than using TF specific functions so I think in general perhaps we should have the principle of least surprise here and support this use case for the RAM file system?

I still prefer to enforce portable "/" only for host like cases

**Comment by adriangb** [comment]
I wouldn't be so sure. GCS is clearly a URL, I wouldn't expect `os.path.join` to work for URLs, nor do I expect GCS to support `\`. I don't see how `ram://` is any different. 

And users are also already going to be using Tensorflow specific implementations of `listdir`, `walk`, etc

So I would almost lean towards explicitly not supporting `\`, for consistency.

**Comment by frankchn** [comment]
@mihaimaruseac Any thoughts on whether we should support `\` as a directory separator in file systems generally or should we provide a `join_path` or similar thing and not support `\` at all?

**Comment by bhack** [comment]
GCS Is an URL so your  https://github.com/tensorflow/tensorflow/pull/48125 It will useful for GCS and other host/URL like cases.
I think ramfs Is still in the OS perimeter so It Is ok to have native os sep. 
Also many of these fs APIs are not wrapped in python so It Is better to be in Sync with python os when possibile..

**Comment by mihaimaruseac** [comment]
I think we should support `\` only for local Windows filesystem and everywhere else mandate `/`.

**Comment by bhack** [comment]
> I think we should support `\` only for local Windows filesystem and everywhere else mandate `/`.

What do you mean with local? Do you mean on a local physical disk storage?

Cause I think that RAM is local :)

**Comment by mihaimaruseac** [comment]
I mean the `C:\\path\\to\\file` / `path\\to\\file` filesystem, without an URI. Also the `file://C:\\path\\to\file`, maybe, as it shares the same code, but ideally any filesystem that has a non-empty URI scheme should be interpreted as a valid URL and use `/`.

Though I'm not completely sold on this, if there are arguments to allow `\` anywhere on Windows OS, then we can go that way, at the risk of complicating some implementations.

**Comment by adriangb** [comment]
Just echoing back to make sure I understood:

```python
gfile.GFile("path\file.csv")  # okay, relative path that is backed by Windows native disk FS
gfile.GFile("C:\\path\file.csv")  # okay, absolute path that is backed by Windows native disk FS
gfile.GFile("C:\\path/file.csv")  # okay with TF, but / is disallowed by Windows native disk FS, failure happens outside of TF
gfile.GFile("file://path\file.csv")  # up for debate?
gfile.GFile("file://path/file.csv")  # okay
gfile.GFile("ram://path\file.csv")  # not okay: \ is not allowed in `ram`. Should this fail or just make a file called "path\file.csv"?
gfile.GFile("gc://path\file.csv")  # not okay: \ is not allowed in `gc`. Should this fail or just make a file called "path\file.csv"?
gfile.GFile("ram://path/file.csv")  # okay on all platforms, including Windows
```

**Comment by mihaimaruseac** [comment]
> Just echoing back to make sure I understood:
> 
> ```python
> gfile.GFile("path\file.csv")  # okay, relative path that is backed by Windows native disk FS
> gfile.GFile("C:\\path\file.csv")  # okay, absolute path that is backed by Windows native disk FS
> gfile.GFile("C:\\path/file.csv")  # okay with TF, but / is disallowed by Windows native disk FS, failure happens outside of TF
> gfile.GFile("ram://path\file.csv")  # not okay: \ is not allowed in `ram`. Should this fail or just make a file called "path\file.csv"?
> gfile.GFile("gc://path\file.csv")  # not okay: \ is not allowed in `gc`. Should this fail or just make a file called "path\file.csv"?
> gfile.GFile("ram://path/file.csv")  # okay on all platforms, including Windows
> ```

Yes, those two not okay paths should be disallowed.

Alternatively, we could make a change in `TranslateName` (or somewhere similar) to canonicalize paths on Windows to replace all `\\` with `/` as this won't require extensive changes in the rest of the code. However, it would harm cornercases of paths that contain these separators in the file name itself.

**Comment by adriangb** [comment]
> Yes, those two not okay paths should be disallowed

For what it's worth, I think this is probably the way to go. Even though I am not very familiar with your codebase, I think that generally it is easier to have only one way to do things (which in this case would be `/`) and either explicitly (likely more work and fragility, but better user experience because the errors are clear) or implicitly (just don't test for or hint at supporting) disallowing other cases. This is doubly true with a case like this where you end up with a lot of rough edges, like the question above of "should `folder\file.txt` be an error or a file called `folder\file.txt`".

**Comment by bhack** [comment]
@mihaimaruseac  Please close this when you have a

**Pull request closed without merging**
