### PR TITLE
Fixed description of num_threads in `tf.lite.interpreter` doc

### PR DESCRIPTION
**Pull request by LakshmiKalaKadali**
Hi
As per the code  [tensorflow/tensorflow/lite/python/interpreter.py](https://github.com/tensorflow/tensorflow/blob/b297295711589c2d71880a046333e6ec095c6d7d/tensorflow/lite/python/interpreter.py#L460-L464)

Lines 460 to 464 in [b297295](https://github.com/tensorflow/tensorflow/commit/b297295711589c2d71880a046333e6ec095c6d7d) , code num_threads is greater than equal to 1 but in description it was given as `-1`. This PR fixes description of num_threads in `tf.lite.interpreter` doc.

This PR fixes: TFLite issue [#68862](https://github.com/tensorflow/tensorflow/issues/68862)

Thank You

### CODE REVIEW

**Comment by keerthanakadiri** [comment]
Hi @junjiang-lab , Can you please review this PR? Thank you .

**Review by junjiang-lab — CHANGES_REQUESTED** [review]
Thanks Lakshmi  for the fix. Shall we remove below comments as well?

"Setting num_threads to 0 has the effect to disable multithreading ... implementation-defined and platform-dependent."

**Comment by LakshmiKalaKadali** [comment]
Hi @junjiang-lab,

Thank You for the suggestion. If num_threads >=1, no need to mention about 0 and -1 cases. So removed those lines.
Thank You

**Review by junjiang-lab — APPROVED** [review]
Thanks Lakshmi!

**Pull request merged**
