### PR TITLE
Check in generated protobufs for Go

### PR DESCRIPTION
**Pull request by jhseu**
To make it more idiomatic and easier to install. See #35133 

Gunhan, any objections to doing this? It adds 1.3 MB of generated files to the repo.

### CODE REVIEW

**Review by frankchn — APPROVED** [review]

**Comment by gunan** [comment]
Did we not do this internally?
I am confused?

**Comment by gbaned** [comment]
@jhseu, @frankchn Any update on this PR? Please. Thanks!

**Comment by JacobSMoller** [comment]
Any update on when this will be merged?

**Comment by umbrellary** [comment]
Why Merging is blocked?

**Comment by philpearl** [comment]
please please please merge this PR. Every other Go package we use we can just "go get". I really don't want to have to have special case code in our build for tensorflow.

**Comment by gbaned** [comment]
@jhseu, @frankchn Any update on this PR? Please. Thanks!

**Comment by frankchn** [comment]
There is some issue merging this in where the CL doesn't seem to be able to be merged properly internally. @jhseu might know more

**Comment by philpearl** [comment]
## How to build tensorflow
1. Get a job at Google
2. ...
3. ...
4. 💰

**Comment by jhseu** [comment]
We had a discussion with the Go team who discouraged checking this in because other projects had faced issues with conflicts between generated protobufs and the protobuf files generated by bazel. Closing for now.

Users should run go generate as mentioned in the [README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md).

**Comment by philpearl** [comment]
please please please merge this PR. Every other Go package we use we can just "go get". I really don't want to have to have special case code in our build for tensorflow.

No other package I've ever seen does this.

**Pull request closed without merging**
