### PR TITLE
Adding missing close parenthesis in code listing.

### PR DESCRIPTION
**Pull request by sandersk**
Fixing code syntax error that is already corrected in 1.0 and master branches.

### CODE REVIEW

**Review by maciekcc — APPROVED** [review]

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Comment by caisq** [comment]
The test failures are due to some buildifier changes between r0.12 and now and are unrelated to the doc-only changes in this PR. Merging PR now.

**Pull request merged**
