### PR TITLE
[XLA:GPU][ROCm] Refactor redzone_allocator and ptxas_utils

### PR DESCRIPTION
**Pull request by jerryyin**
This is a follow-up PR to #30884. This PR bring `Cuda` specific interface including 

- `RedzoneAllocator` 
- `ptxas_util` ---renamed to----> `gpu_asm_opts`

to parallel with `ROCm`. It take advantage of scoped macros, and removed all compile time dispatches. The scoped macro is in `ptxas_util` component only. We will implement `ROCm` corresponding ptx utilities once hip compile time utilities become available to us.

With this PR, the dependent #30884 will be able to compile without compile time dispatch.

Note to the reviewer: a decent number of changes are trivial and related to `RedzoneAllocator` and `ptxas_utils`. Please review those two first.

@cheshire @timshen91

### CODE REVIEW

**Review by cheshire — DISMISSED** [review]
LGTM, thanks!

**Comment by rthadur** [comment]
@jerryyin can you please check build failures ?

**Review by cheshire — DISMISSED** [review]

**Review by cheshire — DISMISSED** [review]

**Review by cheshire — DISMISSED** [review]

**Review by cheshire — DISMISSED** [review]

**Comment by jerryyin** [comment]
FYI, Re-based again to pick changes from `buffer_comparator.cc`.

**Review by cheshire — APPROVED** [review]

**Comment by cheshire** [comment]
Sorry for the difficulties, I keep approving it, but apparently merge issues keep piling up. Hopefully it will go through this time.

**Comment by jerryyin** [comment]
Thanks for your effort in updating it! When this is done, I will create a new PR for the remainder of #30884, and ping you there.

**Comment by cheshire** [comment]
This CL does not build, I'll try to fix the issues today.

**Comment by jerryyin** [comment]
@cheshire I don't have access to result of feedback/copybara, but let me know if there's anything I can do to help.

**Comment by cheshire** [comment]
I understand, so for now I'm looking at it. In general, smaller commits help. The problem I'm facing now is that XLA tests previously could run with GOOGLE_CUDA variable injected, and we should try to preserve this behavior. I'm trying to reverse the guard: give the ROCM version if TENSORFLOW_USE_ROCM is defined, and use CUDA instead.

**Comment by cheshire** [comment]
I had to do a few renames as well: `gpu_asm_opts` became `gpu/asm_compiler`, and `redzone_allocator` became `gpu/redzone_allocator`, since both are specific to GPUs.

**Comment by jerryyin** [comment]
@cheshire I walked through you changes and there are several thing I like: 

- Moving shared files under stream_executor/gpu
- Setting the `visibility` field to scope the binary under certain targets. I assume this together with `if_gpu_is_configured` helped address linker issues, if any

I'm not too sure about the macro injection part of the story. As long as switch from `GOOGLE_CUDA` to `TENSORFLOW_USE_ROCM` help you address the issue.

**Comment by cheshire** [comment]
Could you clarify what is "macro injection part of story"? Have I missed injecting macros setting ROCM?

**Comment by jerryyin** [comment]
> The problem I'm facing now is that XLA tests previously could run with GOOGLE_CUDA variable injected, and we should try to preserve this behavior. I'm trying to reverse the guard: give the ROCM version if TENSORFLOW_USE_ROCM is defined, and use CUDA instead.

Ahh, it is related to your comments referred above. I saw the description but didn't see relevant code changes, so was suspecting this is related to your internal code base?

**Comment by cheshire** [comment]
Yes, internally XLA has to keep working with CUDA if no variables are injected.
So for now I suggest to guard ROCM changes on special variables, and use CUDA otherwise.

**Comment by jerryyin** [comment]
Sounds good

**Pull request merged**
