### PR TITLE
Support GCS URL by tf.estimator.LatestExporter

### PR DESCRIPTION
**Pull request by nagachika**
I have found that the parameter `exports_to_keep` of `tf.estimator.LatestExporter()` is ignored if export_path is GCS URL (like `gs://bucket/object/`). All exported SavedModel directories are never removed.

The root cause is that the `tf.gfile.ListDirectory` returns basenames with file separator '/' at the end if the path was GCS URL.  The `_export_version_parser` function rejects a path with trailing '/'.

I don't think the behavior of `tf.gfile.ListDirectory` is wrong because the semantics of "path" in GCS is different from usual filesystems. For example, you can place two different objects in the GCS bucket like `gs://bucket/obj` and `gs://bucket/obj/`. So I think `tf.gfile.ListDirectory` should return basename with '/'.

I try to fix the issue by eliminating trailing separator at `tf.estimator.gc._getpaths()`.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @isaprykin: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: It has been 59 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: It has been 74 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by nagachika** [comment]
Hi @isaprykin, 
Is there any chance to merge this PR before branching for 1.10?

Thanks.

**Comment by ispirmustafa** [comment]
Hi nagachika, is it possible to create a test which shows all flow for this case. 
I mean, have paths, deleted right ones at the end.
you can mock listdirectories

**Comment by nagachika** [comment]
Hi @ispirmustafa , thank you for your advice.
I have add a test in case `gfile.ListDirectory` returns subdirectory with delimiter `/` at https://github.com/tensorflow/tensorflow/pull/17239/commits/3c44a0c54ad09eed8855d017b18ffbb51b4e68e3.
Is that OK? Using GCS for temporary export directory is ideal, but I don't know how to handle credentials for that.

**Review by ispirmustafa — APPROVED** [review]
Thank you!

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: It has been 16 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @isaprykin: It has been 31 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by nagachika** [comment]
Hi
Is there any chance to merge this pull req before creating branch `r1.10`?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ispirmustafa: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request merged**
