### PR TITLE
Update CODE_OF_CONDUCT.md with additional protected characteristic

### PR DESCRIPTION
**Pull request by germanmarky**
Government/Military/Veteran affiliation (government catch-all) protected characteristic added to opening paragraph.

### CODE REVIEW

**Comment by germanmarky** [comment]
CLA signed

**Comment by vrv** [comment]
@martinwicke is out this week so maybe he can speak more to this when he gets back.  Since I'm trying to help and I have no context, I believe this code of conduct was taken from http://contributor-covenant.org/ -- perhaps it makes sense to make this request there first so we don't deviate?

**Comment by germanmarky** [comment]
@vrv PR on Contributor Covenant completed. As the CoC used here has content from multiple sources, a minor change with an addition of a protected characteristic should not conflict with the source originals.

I welcome comments from @martinwicke when he returns.

**Comment by vrv** [comment]
Thanks, will probably wait for https://github.com/ContributorCovenant/contributor_covenant/pull/432 to be merged.

**Comment by rmlarsen** [comment]
@martinwicke can you please comment on this.

**Comment by jhseu** [comment]
@germanmarky Closing this out since there's no update on that pull request and  we don't want to deviate from contributor covenant. Feel free to reopen or resend when the change gets merged there (we'll also likely update it on our own when that happens).

**Pull request closed without merging**
