### PR TITLE
[tosa] Align with the custom assembly format change.

### PR DESCRIPTION
**Pull request by tatwaichong**
Synchronize to the change in mlir.

link to the PR https://reviews.llvm.org/D155231.

### CODE REVIEW

**Comment by tatwaichong** [comment]
Kindly remind that https://reviews.llvm.org/D155231 has been merged, free feel to adopt this PR to match.

**Comment by burmako** [comment]
@tatwaichong Thank you for the patch! This week, I'm on a Google-internal rotation that bumps LLVM versions, and this will help big time. I'll land this change internally, and it'll bubble up to tensorflow/tensorflow soon.

**Comment by tatwaichong** [comment]
Thanks your help. I've just rebased this PR and resolved the conflicts.

**Comment by tatwaichong** [comment]
Close this PR as the change has been merged in a LLVM integration.

**Pull request closed without merging**
