### PR TITLE
[OpenCL] Cleans reduction ops

### PR DESCRIPTION
**Pull request by lukeiwanski**

### CODE REVIEW

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins, test this please.

**Pull request merged**
