### PR TITLE
Update is_windows() to allow mingw shells

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by angerson — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 42 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Pull request merged**
