### PR TITLE
Feature requested by issue 18354: No gradient defined for operation DepthwiseConv2dNativeBackpropFilter 

### PR DESCRIPTION
**Pull request by jony0917**
Feature requested by issue 18354: No gradient defined for operation DepthwiseConv2dNativeBackpropFilter

### CODE REVIEW

**Comment by lgeiger** [comment]
Thanks for adding the gradients!

It looks like the lint is failing due to 4 space indentation and some other style issues. Checkout [this section](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#python-coding-style) on how to run `pylint` locally so this PR can be reviewed and merged.

**Comment by qlzh727** [comment]
Ping @chsigg for review again.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg, @azaks2: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg, @azaks2: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg, @azaks2: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg, @azaks2: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Review by chsigg — APPROVED** [review]

**Comment by qlzh727** [comment]
This PR is failed for internal test since it was using placeholder in tests, which is not eager mode compatible. @chsigg, can u please take a look again? Thanks.

**Comment by qlzh727** [comment]
Ping @chsigg again for internal merge.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg, @azaks2: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Pull request merged**
