### PR TITLE
Revert "Add synthetic datasets (#5315)"

### PR DESCRIPTION
**Pull request by caisq**
This reverts commit ca29fa3cc16663a8dddf5968b5600c60e2dc71a8.

Reason for rollback: Broke builds due to errors such as:

File
"/workspace/pip_test/venv/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py",
line 29, in <module>
    from tensorflow.contrib.learn.python.learn.datasets import synthetic
    ImportError: cannot import name synthetic

### CODE REVIEW

**Comment by caisq** [comment]
CC @martinwicke @zafartahirov @gunan. Please roll forward after fixing. Thanks.

**Review by ericdnielsen — APPROVED** [review]

**Comment by zafartahirov** [comment]
Hey @caisq can you please share which builds fail? I cannot seem to replicate the error

**Comment by caisq** [comment]
@zafartahirov zafartahirov 

To give a few examples:
http://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/228/console
http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/323/console
http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=NO_PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/323/consoleFull

@comicchang has opened a PR to fix it. This this rollback PR got merged first so we didn't get a chance to test that fixing PR. https://github.com/tensorflow/tensorflow/pull/6283

**Comment by zafartahirov** [comment]
OK, thanks! If ca29fa3 + #6283 don't fix the issue, I will take a look at it tomorrow evening.

**Pull request merged**
