### PR TITLE
TfLite one_hot int8 and unit8 feature support

### PR DESCRIPTION
**Pull request by Dayananda-V**
1- int8 and uint8 data type support change
2- supported data type test coverage added

### CODE REVIEW

**Review by shahzadlone — APPROVED** [review]

**Comment by jdduke** [comment]
Have you verified that this works in a real quantized model? The on/off value semantics may work differently for quantized models.

**Comment by jdduke** [comment]
@suharshs how should we treat these ops for quantization?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @suharshs: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by gbaned** [comment]
@suharshs can you please review this? Thanks!

**Comment by suharshs** [comment]
Sorry for the delay, am discussing the general approach for operations like this. Will update when we have concensus.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@suharshs  Any update on this PR, please.

**Review by suharshs — APPROVED** [review]
This changes are approved as we do not need to consider the scale or zero_point for uint8 or int8 values.

**Comment by suharshs** [comment]
Since one-hot just using int for the backing values anyways.

**Pull request merged**
