### PR TITLE
Add default value in complex function 

### PR DESCRIPTION
**Pull request by thisisiron**

### CODE REVIEW

**Comment by rthadur** [comment]
@thisisiron thanks for your contribution , can you please sign CLA.

**Comment by thisisiron** [comment]
I signed it!

**Review by ymodak — APPROVED** [review]

**Review by dynamicwebpaige — APPROVED** [review]
Thanks for adding the clarification. 😊

**Comment by rthadur** [comment]
Closing this PR as this not against `master`, please open a new PR against `master` 
CC @mihaimaruseac

**Pull request closed without merging**
