### PR TITLE
DOC: formats momentum calculation for web

### PR DESCRIPTION
**Pull request by stsievert**

### CODE REVIEW

**Review by benoitsteiner — APPROVED** [review]

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by yifeif** [comment]
Is this change intended for 1.1 branch? We don't usually accept changes to released branches. Could you make the change in master branch instead?

**Comment by stsievert** [comment]
Changed.

**Comment by stsievert** [comment]
Yes, I'm okay with this PR being merged into master regardless of any other commits authored by others.

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Pull request merged**
