### PR TITLE
Delete the parameter allow_soft_placement in function AssignDevice

### PR DESCRIPTION
**Pull request by leike666666**
The parameter allow_soft_placement is useless in function AssignDevice

### CODE REVIEW

**Comment by rthadur** [comment]
@leike666666 thanks for your contribution , can you please add some more description why  'allow_soft_placement' is not necessary ?

**Comment by leike666666** [comment]
> @leike666666 thanks for your contribution , can you please add some more description why 'allow_soft_placement' is not necessary ?

This parameter 'allow_soft_placement' is not used in function 'AssignDevice' implementation.

**Comment by sanjoy** [comment]
I'm sorry but I'm not the right reviewer for this.  Try @mrry ?

**Review by mrry — APPROVED** [review]
Thanks for the cleanup!

**Pull request merged**
