### PR TITLE
Fix link errors in build tests

### PR DESCRIPTION
**Pull request by elfringham**
Some build tests were failing due to unresolved symbols so add in their dependencies

### CODE REVIEW

**Comment by elfringham** [comment]
This appears to only be a problem with gcc/ld builds. When using clang/lld the build succeeds.

**Comment by gbaned** [comment]
Hi @cheshire Can you please review this PR ? Thank you!

**Comment by cheshire** [comment]
TF has a canonical build configuration, and OSS CI is passing, why should this change be required?

**Comment by cheshire** [comment]
Then there should be a GCC CI?

**Comment by elfringham** [comment]
@cheshire Please see the [SIG BUILD notes](http://bit.ly/tf-sig-build-notes) from 2nd May 2023, with the comment about "we'll accept PRs to fix gcc!"

**Comment by angerson** [comment]
@cheshire Indeed, this is a special case. Although TF's official builds now use and are gated by clang, we (the TF DevInfra team) decided to keep accepting changes that help make TF able to build with GCC, since a large portion of TF's community builders still use gcc for their platforms. We currently leave verification up to them.

**Review by angerson — APPROVED** [review]

**Comment by perfinion** [comment]
This sounds like a difference with `-Was-needed`, not actually due to clang/gcc. I wouldnt be surprised if you added as-needed on clang it'd fail as well. Maybe `:stream_executor_pimpl` needs to have `alwayslink=True` set?

**Comment by gbaned** [comment]
Hi @elfringham Can you please resolve conflicts? Thank you!

**Comment by elfringham** [comment]
Due to the delays in getting this merged, it is now too late as the code has been moved to a different repo.

**Pull request closed without merging**
