### PR TITLE
Use the latest release version instead of master

### PR DESCRIPTION
**Pull request by slevental**
Master branch is subject to change, so to make build predictable it's better to lock dependencies on the particular version

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 50 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @andrehentz: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 65 days with no activity and the `awaiting review` label has been applied.

**Comment by rmlarsen** [comment]
@slevental Please rebase to resolve conflicts.

**Pull request closed without merging**
