### PR TITLE
Remove TF_NEED_KAFKA from configure.py as it is not needed anymore.

### PR DESCRIPTION
**Pull request by yongtang**
With the new update in kafka dataset support, it looks like TF_NEED_KAFKA is not needed any more as we are loading .so dynamically. For that I think it makes sense to remove TF_NEED_KAFKA option from configure.py.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by gunan** [comment]
It looks like we may need the ability to remove dependency on Kafka conditionally.
Kafka depends on boringSSL, and boringSSL does not work on big endian systems, such as IBM s390x.

**Comment by yongtang** [comment]
Thanks @gunan. I updated the PR so that now kafka build will be skipped if `with_kafka_support=False` or if in Windows. Please take a look and let me know if there are any issues.

**Comment by gunan** [comment]
I also would like to see how much of extra build the test infra has to do with kafka support default on.
This is pretty important as we are at the scale of 10s of thousands of CPUs. What is the extra sources we have to build with kafka default on? If it adds aa lot, I wold still go for turning it off and letting people enable it conditionally.

@martinwicke how do you feel about having the apache kafka support on by default?

**Comment by martinwicke** [comment]
I don't mind this if the added load isn't excessive. I would want to make sure that all ops which depend on Kafka exit gracefully and with a clear error if the required library is not found. 

In generally, less questions in configure are better.

**Comment by Nayana-ibm** [comment]
@gunan Could you please help in merging this? Will this commit available in Tensorflow v1.7.0? Once merged, we will give a try to build on s390x to see if we still face the issue mentioned in https://github.com/tensorflow/tensorflow/issues/17587

**Review by gunan — APPROVED** [review]

**Pull request merged**
