### PR TITLE
Print `tags` instead of `tag` since `tag` doesn't exist in funtion `Run`.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
Otherwise, in order to print exception info for each tag,
we also are able to declare local variable `tag`, and
set it with the value of `t` in for statement.

### CODE REVIEW

**Comment by danmane** [comment]
LGTM, please rebase :+1:

**Comment by dongjoon-hyun** [comment]
Thank you, @vrv, @danmane and @martinwicke . I'll rebase it.

**Comment by danmane** [comment]
Thank you too! :)

**Comment by danmane** [comment]
Actually, I've taken it upon myself to re-write this script today so it will work a bit more cleanly, and serialize some new endpoints we're adding to the backend. Since this is such a small change, do you mind if I just add this directly into the new version of the script? Lower friction than going through the pull request.

**Comment by dongjoon-hyun** [comment]
Sure, @danmane . After doing that, please just close this one. :-)
Thank you.

**Comment by martinwicke** [comment]
Thanks @dongjoon-hyun. Closing.

**Comment by dongjoon-hyun** [comment]
Hi, @martinwicke . 
I cannot find @danmane 's new code until now.
Is it still internal? I thought you guys close my PR after merging yours.
Anyway, I'm looking forward to seeing the rewritten code soon. :-)

**Comment by martinwicke** [comment]
I'm sorry, I got all excited and went on a issue/pr closing spree. It should get here soon.

**Comment by dongjoon-hyun** [comment]
Oh, never mind. I'm just a happy user. :)

**Pull request closed without merging**
