### PR TITLE
Fixed a typo. It should be x (not b).

### PR DESCRIPTION
**Pull request by hunkim**
I think it's should be x, not b.

``` python
# 'perm' is more useful for n-dimensional tensors, for n > 2
# 'x' is   [[[1  2  3]
#            [4  5  6]]
#           [[7  8  9]
#            [10 11 12]]]
# Take the transpose of the matrices in dimension-0
tf.transpose(b, perm=[0, 2, 1]) ==> [[[1  4]
...
tf.transpose(x, perm=[0, 2, 1]) ==> [[[1  4]
```

### CODE REVIEW

**Comment by mrry** [comment]
This documentation is auto-generated from [this line in `array_ops.py`](https://github.com/tensorflow/tensorflow/blob/fe9dafd1583da5ccc205eab776f86afcb00411d2/tensorflow/python/ops/array_ops.py#L564). Can you please make the change there instead? Thanks!

**Comment by hunkim** [comment]
Thanks, @mrry. Done!

**Comment by mrry** [comment]
@tensorflow-jenkins, test this please.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by hunkim** [comment]
@martinwicke I just changed one line in the comment. I am not sure why it causes two failures: 
 ci.tensorflow.org — FAILURE
 Linux CPU Tests — FAILURE

Did I miss something?

**Comment by martinwicke** [comment]
That looks like a tool failure. I'm pretty sure those timeouts are not your fault.

**Pull request merged**
