### PR TITLE
EIGEN_DEVICE_FUNC annotation cleanup

### PR DESCRIPTION
**Pull request by nluehr**
Fix some compiler warnings, and reduce chance of future bugs being introduced where device functions call host-only functions.

### CODE REVIEW

**Comment by gbaned** [comment]
@nluehr Can you please resolve conflicts? Thank you!

**Comment by cantonios** [comment]
Can you give more context here?  What warnings?

If these are in fact used on GPU, this will break those cases.  NVCC will often complain about adding `__device__` to a default constructor saying it's not necessary and is ignored, but in practice it isn't actually ignored and code breaks without it.

**Comment by nluehr** [comment]
The warnings are something like the following.
```
warning: calling a __host__ function(...) from a __host__ __device__ function(...) is not allowed.
```

Eigen has a habit if decorating almost all functions for device. Some functions, however, include calls to host-only functions, and compiling these for the device doesn't make sense. Would the functions ever be called on the device, it would result in a crash.

I pushed a similar PR to cleanup similar issues in Eigen itself in https://gitlab.com/libeigen/eigen/-/merge_requests/477

**Comment by cantonios** [comment]
`scalar_left`/`scalar_right` don't call host functions - they are default constructors.  And given that those are in the top `cwise_ops.h` header, it may be expected that they work on device.

Digging through call graphs, it looks like `SpatialConvolution` might actually be called from [here](https://github.com/tensorflow/tensorflow/blob/97d0b6a8ecbe651aede8bb678f78f01b4741cf54/tensorflow/core/kernels/conv_ops.cc#L354).

Because Eigen passes a lot of complex class types through template parameters, it could be that for only certain template parameters the function would end up calling a host-only function (and hence generate the warning), but in other cases it's actually required.  If we ever did actually call a host-only function, that would generate an error.  Many of the existing decorators in Eigen were added because of this viral nature in order to reduce compile warnings.

Anyways, I'm happy to test this, but was just wondering more about the specifics for why this is required.

**Review by cantonios — APPROVED** [review]

**Pull request merged**
