### PR TITLE
Updated PR for "Fold BN after depthwise conv"(#21023)

### PR DESCRIPTION
**Pull request by zhaoyongke**
[Original PR is here](https://github.com/tensorflow/tensorflow/pull/21023)

### CODE REVIEW

**Comment by drpngx** [comment]
Could you pull rebase and push again?

**Comment by drpngx** [comment]
@smillius if you could take a quick look, that would be great. Thanks!

**Review by smillius — COMMENTED** [review]
Looks good to me.

**Comment by drpngx** [comment]
@zhaoyongke could you run clang-format-3.6.0 on this?

**Comment by zhaoyongke** [comment]
@drpngx can u provide full command lines for clang-format-3.6.0?

**Comment by harshini-gadige** [comment]
> @drpngx can u provide full command lines for clang-format-3.6.0?

@drpngx  Any update please ?

**Comment by drpngx** [comment]
You need to download the tool and run it.

**Comment by harshini-gadige** [comment]
> @zhaoyongke could you run clang-format-3.6.0 on this?

@zhaoyongke   Any update please ?

**Comment by zhaoyongke** [comment]
I tried to run clang-format-3.6 on modified files in this PR, nothing meaningful found, only generated the almost same code again with some indent changed.@drpngx @harshini-gadige

**Comment by harshini-gadige** [comment]
> I tried to run clang-format-3.6 on modified files in this PR, nothing meaningful found, only generated the almost same code again with some indent changed.@drpngx @harshini-gadige

@drpngx  Can  you please suggest the user on this.

**Comment by drpngx** [comment]
Please push the files. Clang format will have nothing meaningful, just
spaces.

**Comment by HuiyangFei** [comment]
Hi @drpngx @mingxingtan @smillius, 
The only thing left is the code review,  can you guys approve it?  The old PR has been reviewed once already.

**Comment by drpngx** [comment]
Sounds good. Started the test & pull to internal.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @mingxingtan: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @mingxingtan: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @mingxingtan: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Review by mingxingtan — CHANGES_REQUESTED** [review]
The CL looks good to me.  After drpngx@ verify all tests pass, we can merge it.

**Review by mingxingtan — APPROVED** [review]

**Pull request merged**
