### PR TITLE
Transpose Elimination for TF Dialect

### PR DESCRIPTION
**Pull request by ksugama**
Pull out distributed transposes from binary operators in canonicalization pass

### CODE REVIEW

**Comment by gbaned** [comment]
@ksugama  Can you please resolve conflicts? Thanks!

**Comment by ksugama** [comment]
@gbaned Hi! Yes I just resolved the conflicts. Waiting for any build errors from Jenkins to show up, if any.

**Review by sanjoy — CHANGES_REQUESTED** [review]
Something is wrong with how this PR is setup -- github says 1,513 files were changed.  Can you please fix?

**Comment by gbaned** [comment]
@ksugama Can you please resolve conflicts? Thanks!

**Pull request closed without merging**
