### PR TITLE
Update iris.py

### PR DESCRIPTION
**Pull request by hprovenza**
sklearn cross_validation is deprecated and should be replaced with model_selection

### CODE REVIEW

**Comment by rmlarsen** [comment]
Notice that this need to wait until the version of sklearn at Google has been updated.

**Review by ilblackdragon — APPROVED** [review]

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by dandelionmane** [comment]
@tensorflow-jenkins Test this please

**Review by teamdandelion — APPROVED** [review]
Carrying over lilblackdragon's lgtm

**Pull request merged**
