### PR TITLE
Updated the broken link in customized_task_api.md

### PR DESCRIPTION
**Pull request by tiruk007**
Fix broken link for `BertQuestionAnswerer` in line 43  and in line 106

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @sirakiin Can you please review this PR ? Thank you!

**Review by sirakiin — APPROVED** [review]

**Pull request merged**
