### PR TITLE
[Intel MKL] Fix shape inference for Quantized{Conv2D/DepthwiseConv2D}-like operations

### PR DESCRIPTION
**Pull request by CuiYifeng**

### CODE REVIEW

**Comment by gbaned** [comment]
@CuiYifeng  Can you please resolve conflicts? Thanks!

**Comment by CuiYifeng** [comment]
@gbaned Sorry for the slow reponse. The change is in the internal test.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by CuiYifeng** [comment]
@tensorflowbutler This PR is still in internal test.

**Comment by CuiYifeng** [comment]
@gbaned @penpornk Changes done. Please continue to review, thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thank you!

**Comment by CuiYifeng** [comment]
Close this PR due to similar fixes in https://github.com/tensorflow/tensorflow/pull/56139.

**Pull request closed without merging**
