### PR TITLE
[TFLite] Fix of issue 58050. Give user the option to silence the logging of TfLite completely

### LINKED ISSUE #58050: How to disable logging to the standard output in C++?
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Ubuntu 22.04LTS

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/Compiler version

gcc 11.2.0

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current Behaviour?

How to disable logging to the standard output in C++? E.g. the message "INFO: Created TensorFlow Lite XNNPACK delegate for CPU." There are a plethora of questions about this. Most of them concern Python, and some C/C++. All of them boil down to setting an environment variable as:
`TF_CPP_MIN_LOG_LEVEL=3`
Sometimes together with:
`TF_CPP_MAX_VLOG_LEVEL=0`

I set these environment variables with setenv() or putenv(). I checked with getenv() at the start of main() whether they were set correctly, and they are. See code provied with this issue.

I also tried:
`export TF_CPP_MIN_LOG_LEVEL=3`
`export TF_CPP_MAX_VLOG_LEVEL=0`
`./my_executable`

And tried:
`TF_CPP_MIN_LOG_LEVEL=3 ./my_executable`

Yet I keep seeing "INFO: Created TensorFlow Lite XNNPACK delegate for CPU." on the standard output. This is driving me crazy. A solution is therefore warmly welcomed.

### Standalone code to reproduce the issue

```shell
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include <iostream>

using namespace tflite;
using namespace std;

int main() {
	//setenv("TF_CPP_MIN_LOG_LEVEL", "3", 1);

	char env[] = "TF_CPP_MIN_LOG_LEVEL=3";
	putenv(env);

	char* check_env;
	check_env = getenv ("TF_CPP_MIN_LOG_LEVEL");
	if (check_env == NULL)
		cout << "TF_CPP_MIN_LOG_LEVEL not set\n";
	else
		cout << "TF_CPP_MIN_LOG_LEVEL = " << check_env << "\n";

	std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile("my_network.tflite");
	tflite::ops::builtin::BuiltinOpResolver resolver;

	std::unique_ptr<tflite::Interpreter> interpreter;
	tflite::InterpreterBuilder(*model, resolver)(&interpreter);
	interpreter->SetNumThreads(1);

	interpreter->AllocateTensors();

	return EXIT_SUCCESS;
}
```

### Relevant log output

_No response_</details>

### PR DESCRIPTION
**Pull request by misterBart**
`tflite::LoggerOptions::SetMinimumLogSeverity(tflite::TFLITE_LOG_ERROR)` will not silence error event.
I added enum case `tflite::TFLITE_LOG_SILENT` for `tflite::LoggerOptions::SetMinimumLogSeverity()` to give the user the option to silence TfLite's logging completely.
Why? Our software (using TfLite) is part of a bigger customer system. The customer controls what is printed on the terminal, our software is therefore not allowed to print to the terminal.
This fixes https://github.com/tensorflow/tensorflow/issues/58050

### CODE REVIEW

**Review by yishuangP — APPROVED** [review]

**Comment by misterBart** [comment]
I see an automatic comment with "Some check were not successful" and "Merging is blocked" I checked the Details of the failed checks, but I cannot pinpoint them to my added code. Do I still need to do something or should I simply wait? This is my first contribution to Tensorflow code, hence my question.

**Comment by gbaned** [comment]
> I see an automatic comment with "Some check were not successful" and "Merging is blocked". I checked the Details of the failed checks, but I cannot pinpoint them to my added code. Do I still need to do something or should I simply wait? This is my first contribution to Tensorflow code, hence my question.

Hi @misterBart Sorry for the delay. Nothing pending from end now. We are processing this PR. Thank you!

**Comment by misterBart** [comment]
First, thanks for your notification.
Second, today I pushed an update to my branch (affected files: lite/minimal_logging_default.cc, lite/minimal_logging_android.cc, lite/minimal_logging_ios.cc). Hopefully still on time to be taken into account by you guys.

**Comment by gbaned** [comment]
Hi @yishuangP Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @yishuangP, @alankelly Can you please review this PR ? Thank you!

**Comment by misterBart** [comment]
Thanks gbaned. Because I started to wonder whether my PR had been forgotten. My PR is very small and not difficult to comprehend, so it should not take much time to review.

**Review by alankelly — APPROVED** [review]

**Comment by yishuangP** [comment]
This cl is submitted with some modification. May take sometime to merge.

**Pull request closed without merging**
