### PR TITLE
Add optional CheckpointSaverListener to MonitoredSession

### PR DESCRIPTION
**Pull request by magnusja**

### CODE REVIEW

**Comment by magnusja** [comment]
I signed it!

**Review by ispirmustafa — CHANGES_REQUESTED** [review]
Thank you Magnus.
Please add unit test. 
also mention in documentation that this argument will be used if (save_checkpoint_secs and save_checkpoint_secs > 0)

**Comment by asimshankar** [comment]
Could you elaborate on the motivation here? 

IIUC, this provides a hook to the checkpoint hook :). Is there an alternative possible here where you provide your own MyCheckpointHook that composes CheckpointSaverHook with your custom code?

**Comment by magnusja** [comment]
@asimshankar Yes that's right ;)
I have not thought about that, but that would be an option as well. Would you prefer an CheckpointSaverHook as an optional argument which is used when not None instead of creating one?

**Comment by asimshankar** [comment]
@martinwicke @ispirmustafa : Could you guys take a look? It seems this is very similar to a change that was proposed to `tf.Estimator` that was also adding such a hook.

**Comment by ispirmustafa** [comment]
We're adding listener argument to `tf.estimator.Estimator.train` since there are edge cases related to creation of `CheckpointSaverHook`.  User can create his/her own `CheckpointSaverHook` before calling `MonitoredTrainingSession`. It's also not a common thing. So I recommend not to change `MonitoredTrainingSession`.

**Comment by martinwicke** [comment]
Closing in response to Mustafa's comment.

**Pull request closed without merging**
