### PR TITLE
Hopefully can solve issue #33811

### PR DESCRIPTION
**Pull request by gekowa**
Hopefully can solve issue #33811

### CODE REVIEW

**Comment by gekowa** [comment]
@googlebot I fixed it.

**Comment by gekowa** [comment]
@googlebot I fixed it.

**Comment by rthadur** [comment]
@gekowa please sign CLA ?

**Comment by omalleyt12** [comment]
@qlzh727 Can you please take a look at this? We expect that Sequence and Generator data adapters should not overlap no?

**Comment by qlzh727** [comment]
Yea, Sequence and Generator data adapter shouldn't overlap. From the name of ImageDataGenerator, it will return a generator?

**Comment by gekowa** [comment]
Signed CLA, but still got the error. Can't get any clue...

[image: image.png]

Rajeshwar Reddy T <notifications@github.com> 于2019年11月2日周六 上午3:48写道：

**Comment by gekowa** [comment]
@googlebot I fixed it.

**Comment by gekowa** [comment]
@omalleyt12 @qlzh727 What should I do next? Several pending checks pending for days...

**Comment by qlzh727** [comment]
Thanks for sending this PR. We wasn't expecting the overlapping the usage of data adapter in the first place, but now if this doesn't holds any more, we want to be thoughtful when there are multiple adapter can be used, and also which one should take priority. 

This PR so far only mitigate the immediate error, but we probably want to put more updates into this issue. I will take the issue from here and fix it. Thanks for the contribution anyway.

**Pull request closed without merging**
