### PR TITLE
Using pd.Series instead of pd.Dataframe

### PR DESCRIPTION
**Pull request by yufengg**
Small change to use Series for x and y values for clarity and simplicity. Code executes equivalently afaict.

### CODE REVIEW

**Comment by yufengg** [comment]
as a matter of side-interest, I had made some changes to update my code compat with Estimators, but when I when to [merge it](https://github.com/tensorflow/tensorflow/pull/11220), it had already been updated lol.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by nealwu** [comment]
Sorry @drpngx I'm not too familiar with this code or with `pandas`. Maybe @roumposg would know? He made the last big change to the internal version of this.

**Comment by roumposg** [comment]
I am not familiar with Pandas in particular, but I did write this code and tested that it works.

I cannot see what benefit this cl brings in. Yufeng, can you clarify?

**Comment by caisq** [comment]
@yufengg any thoughts? Should I close this PR or leave it open for you to work it further?

**Comment by nealwu** [comment]
Looks like we can close this, since it doesn't have a clear benefit and we haven't heard from @yufengg.

**Comment by yufengg** [comment]
Oops sorry missed this -- There's a small perf benefit (since you're not constructing a DataSet and then making a Series out of it), but the main reason is for clarity, since it removes the mental step of "Okay we make a Dataset, then select the index column 1 from it, which implicitly makes a Series".

Instead, we just make a Series explicitly. This makes the code more readable and consistent.

**Comment by roumposg** [comment]
LGTM, thanks for the explanation. But I don't think I have the power to approve your change. Perhaps the others can help.

**Comment by nealwu** [comment]
@roumposg were you able to run this code and verify that it still works as intended?

**Comment by roumposg** [comment]
Yes, I ran it and verified it works as intended.

**Comment by nealwu** [comment]
OK, great! Will approve. I checked out the two failing tests and they appear to be unrelated.

**Review by nealwu — APPROVED** [review]

**Comment by nealwu** [comment]
@benoitsteiner could you help us merge?

**Pull request merged**
