### PR TITLE
Added Support for different data types.

### PR DESCRIPTION
**Pull request by amitsrivastava78**
Added different data types along with test cases.

### CODE REVIEW

**Comment by gbaned** [comment]
@miaout17 Could you PTAL and approve.

**Comment by gbaned** [comment]
@miaout17 could you please review and approve this ?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @miaout17, @jianlijianli: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @miaout17, @jianlijianli: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gunan** [comment]
Closing as a duplicate of https://github.com/tensorflow/tensorflow/pull/26934

**Pull request closed without merging**
