### PR TITLE
tf.tuple usage exaple 

### PR DESCRIPTION
**Pull request by CREVIOS**
Its will reviewed  google code in mentors

### CODE REVIEW

**Comment by gbaned** [comment]
@CREVIOS thank you, it is failing doctest can you please check here for [logs](https://source.cloud.google.com/results/invocations/339219ac-fcf9-421b-bdc9-ae203c2c72c1/targets/%2F%2Ftensorflow%2Ftools%2Fdocs:tf_doctest/tests).

Please run the doctest locally as mentioned here in the [contributor guidelines](https://www.tensorflow.org/community/contribute/docs_ref).

**Comment by gbaned** [comment]
@CREVIOS Any update on this PR, please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
