### PR TITLE
Minor changes in README.md

### PR DESCRIPTION
**Pull request by sSinha28**

### CODE REVIEW

**Review by gbaned — APPROVED** [review]

**Review by rthadur — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Please sing CLA, please change title to something not "update <file>", please revert trivial incorrect changes.

See https://cbea.ms/git-commit/ for how to better title the PR and the commits.

**Comment by gbaned** [comment]
@sSinha28 Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!

**Review by mihaimaruseac — APPROVED** [review]
Changes seem to minimal but let's take this.

**Comment by rthadur** [comment]
Can you please rebase your branch to head, Thank you.

**Comment by gbaned** [comment]
@sSinha28 Can you please check @rthadur's comments and keep us posted ? Thank you!

**Comment by mihaimaruseac** [comment]
We can also drop the PR, the changes are minor and if the process to merge it take too long we would be better spending this time somewhere else.

**Pull request closed without merging**
