### PR TITLE
Reinstate solution #26682.

### PR DESCRIPTION
**Pull request by MrRaevenswood**
It is my understanding that this solution was originally failed a test, but, as of now we do not know why. So I am trying to recreate the pull request so as to see what failed so that we can fix it.

### CODE REVIEW

**Comment by MrRaevenswood** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
@gharibian  Can you please review this PR ? Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
```
tensorflow/go/session.go:21:11: fatal error: 'tensorflow/c/c_api_experimental.h' file not found
 #include "tensorflow/c/c_api_experimental.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

You need to edit the BUILD file to add the proper dependency for the new header.

When done, you should be able to test by

```
bazel test //tensorflow/go:op_test
```

**Comment by gbaned** [comment]
@MrRaevenswood  Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Comment by MrRaevenswood** [comment]
Apologies for not getting to this right away. I just came back from my vacation I will now look to fixing the issue to get this solution merged successfully.

**Comment by MrRaevenswood** [comment]
@mihaimaruseac I got this far in adding the new dependency and testing it with bazel. I have the following error at the moment. 

image

Where is the remote_execution.bzl file?

**Comment by mihaimaruseac** [comment]
Sorry, was OOO. What flags are you using for compiling?

**Comment by gbaned** [comment]
@MrRaevenswood  Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Comment by gbaned** [comment]
@MrRaevenswood Any update on this PR? Please. Thanks!

**Pull request closed without merging**
