### PR TITLE
[tf.keras.layers.ReLU] Layer returns 0 if threshold is negative and max_value is set #28230

### PR DESCRIPTION
**Pull request by shashvatshahi1998**
Tried to solve #28230

### CODE REVIEW

**Comment by shashvatshahi1998** [comment]
@rthadur please somebody review it?

**Comment by shashvatshahi1998** [comment]
Please @mihaimaruseac  can you review it?

**Comment by mihaimaruseac** [comment]
Would be good to also have a test

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Please provide a test

**Comment by mihaimaruseac** [comment]
Closing as there is no more activity

**Pull request closed without merging**
