### PR TITLE
[ROCm] Add ROCm macro for Google upstream avgpooling op

### PR DESCRIPTION
**Pull request by jerryyin**
This PR added the ROCm macro for avgpooling_op

This PR depends on #26722 and #26774

### CODE REVIEW

**Comment by jerryyin** [comment]
Oops, looks like I can't do merge from an on-going PR request

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @chsigg: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Review by chsigg — APPROVED** [review]

**Pull request merged**
