### PR TITLE
Added pre-commit to make pylint checks automated.

### PR DESCRIPTION
**Pull request by LukasMoll**
This will automatically run pylint and others when you try to commit your changes.

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
We already have github actions and presubmits that run this. Can you merge this them, if needed?

**Comment by gbaned** [comment]
Hi @LukasMoll Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!

**Comment by gbaned** [comment]
Hi @LukasMoll Any update on this PR? Please. Thank you!

**Comment by LukasMoll** [comment]
Hi, sorry for the late reply. I think it might be redundant because of existing CI.

**Pull request closed without merging**
