### PR TITLE
Documentation updates for r0.10(non-rc) release.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Comment by gunan** [comment]
Not sure about the change I made for TF_Buffer.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/g3doc/api_docs/cc/StructTF_Buffer.md  you'd have to cherrypick the change that removed the generated docs too :/

**Comment by gunan** [comment]
Will do right away.
However, I see that TF_Buffer is still here:
https://github.com/tensorflow/tensorflow/blob/f9ae4fe749c5d7dbf1851cffc94730086e588c35/tensorflow/c/c_api.h#L146

Is removing it (and what I am doing in this cl the right approach?

**Comment by vrv** [comment]
I don't have the context for what you are doing exactly

**Comment by martinwicke** [comment]
He's just rebuilding the docs -- TF_Buffer doesn't show up any more.

**Comment by vrv** [comment]
LGTM.

**Comment by gunan** [comment]
I confirmed with Manjunath that c_api file is still not compatible with doxygen. That is the reason for TF_Buffer to be missing. removing it from docs for now is the correct course of action.

**Pull request merged**
