### PR TITLE
update pin of bazel-toolchain repo for bazel 0.15.0 config release

### PR DESCRIPTION
**Pull request by erain**
bazel-toolchain repo updated for the bazel 0.15.0 config release

https://releases.bazel.build/bazel-toolchains.html

### CODE REVIEW

**Comment by erain** [comment]
@nlopezgi @xingao267 could you help review this?

**Review by nlopezgi — APPROVED** [review]

**Review by xingao267 — APPROVED** [review]

**Comment by nlopezgi** [comment]
@gunan @yifeif could you please review this pr? Thanks!

**Comment by gunan** [comment]
Could you re-send this internally? It is much faster to propagate the change everywhere that way.

**Comment by gunan** [comment]
Also, on github we are not merging any changes to migrate to single source of truth.

**Comment by nlopezgi** [comment]
thanks, sent internally. @erain can you close this PR please?

**Pull request closed without merging**
