### PR TITLE
Removed duplicated line in bazel.rc

### PR DESCRIPTION
**Pull request by hermanzdosilovic**

### CODE REVIEW

**Comment by hermanzdosilovic** [comment]
I signed it!

**Review by case540 — DISMISSED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yifeif** [comment]
@hermanzdosilovic could you fix the conflicts? Thanks!

**Comment by yifeif** [comment]
Thanks @hermanzdosilovic! line `build:win-cuda --define=using_cuda=true --define=using_cuda_nvcc=true` should still be deleted?

**Pull request merged**
