### PR TITLE
[ROCM] enable some multigpu tests

### PR DESCRIPTION
**Pull request by micmelesse**
This PR enables some of the multi-gpu tests that were disabled in a previous pr https://github.com/tensorflow/tensorflow/pull/50331

### CODE REVIEW

**Comment by rthadur** [comment]
@micmelesse thank you for the PR, please let us know when it is ready for review , also add some description for PR.

**Comment by micmelesse** [comment]
@rthadur This pr is ready for review. Sorry about that.

**Review by cheshire — APPROVED** [review]

**Review by cheshire — APPROVED** [review]

**Review by cheshire — APPROVED** [review]

**Review by cheshire — APPROVED** [review]

**Comment by micmelesse** [comment]
@gbaned @cheshire Is there something that I should to address the "feedback/copybara" failure  or is it a ci issue? I cannot access the details of the test

**Review by cheshire — APPROVED** [review]

**Comment by micmelesse** [comment]
@gbaned @cheshire  All the tests pass is it possible to merge this now

**Review by cheshire — APPROVED** [review]

**Comment by gbaned** [comment]
@micmelesse Can you please resolve conflicts? Thanks!

**Review by cheshire — APPROVED** [review]

**Comment by micmelesse** [comment]
@gbaned sorry for the delayed response. Conflicts are resolved.

**Comment by gbaned** [comment]
@cheshire Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@cheshire Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@micmelesse Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@micmelesse Any update on this PR? Please. Thanks!

**Review by cheshire — APPROVED** [review]

**Comment by micmelesse** [comment]
@gbaned Apologies I have resolved the conflicts.

**Comment by micmelesse** [comment]
@gbaned @cheshire I am not sure the failures have anything to do with the changes in this pr. It just enables tests on rocm. The ROCM ci passes.

**Pull request merged**
