### PR TITLE
[INTEL MKL] Fix debug_grappler unit test failure

### PR DESCRIPTION
**Pull request by gzmkl**
Fix a bug with debug_grappler, which is related to MklAddN.

### CODE REVIEW

**Review by caisq — APPROVED** [review]
Thanks, @gzmkl

**Comment by gzmkl** [comment]
Hi, 
This PR has been approved for a while but not merged.
Please let me know if I need to do anything.  Because this PR will reduce one MKL test failure, I would like it to be included in TF 2.1.  
Thanks,
GZ

**Comment by caisq** [comment]
@rthadur Can you please take a look why this PR still hasn't been pulled internally?

**Comment by rthadur** [comment]
@caisq sure trying again to pull this in, @gzmkl thanks for waiting.

**Comment by gzmkl** [comment]
Thanks!

**Pull request merged**
