### PR TITLE
[PluggableDevice] register default devices for functional ops

### PR DESCRIPTION
**Pull request by quintinwang5**
Register default devices for functional ops. This is for PluggableDevice.

### CODE REVIEW

**Comment by gbaned** [comment]
@saxenasaurabh Can you please review this PR ? Thanks!

**Review by mdanatg — APPROVED** [review]

**Comment by gbaned** [comment]
@mdanatg  Any update on this PR? Please. Thanks!

**Review by mdanatg — APPROVED** [review]

**Comment by mdanatg** [comment]
Let's try the tests again now that the parent is merged.

**Comment by quintinwang5** [comment]
@mdanatg Sorry for the delay. I modify the UT(`WhileOpTest, WhileOpCPUBuildWithPluggableDevice`) in this PR. Let me explain that. The UT was also added by me because `While` op will crash when `TF CPU build + PluggableDevice`. In this UT, I register a device called `FAKE`, so `While`/`LessEqual`/`Mul` will use `DEVICE_DEFAULT` with `DT_FLOAT`(due to the limitation of `While` op's implementation, `DT_INT32`/`DT_INT64` will not run into the `PluggableDevice` path). But `LessEqual`/`Mul` with `DT_FLOAT` must not have `DEVICE_DEFAULT`(just `DT_INT32` available). So I add two `FunctionDef` to cast `DT_FLOAT` into `DT_INT32` before compute for them, convert them back to `DT_FLOAT` then. 
Before I register `While` to `DEVICE_DEFAULT`, this UT was not actually ran. If this PR was merged before [50916](https://github.com/tensorflow/tensorflow/pull/50916), I would have a chance to fix this in 50916.

**Comment by mdanatg** [comment]
Sounds good, but note that in the long term we don't want DType holes in kernel registrations, especially for such generic kernels as control flow. To capture these points in the code, please add the notes in code comments (in the test function would be fine), along with a TODO to support cast-free operation (and add the corresponding DEVICE_DEFAULTs).

**Review by mdanatg — APPROVED** [review]

**Pull request merged**
