### PR TITLE
Fixed bug with fall-through switch statement

### PR DESCRIPTION
**Pull request by wlsc**

### CODE REVIEW

**Comment by dsmilkov** [comment]
Nice catch. Looks good to me. Can you merge the latest changes from master into this branch. Branch is out-of-date.

**Comment by wlsc** [comment]
Sure, it's updated now

**Comment by vrv** [comment]
@dsmilkov: does this need to be cherry-picked into r0.7 too?

**Comment by dsmilkov** [comment]
No need to cherry-pick. No visual impact by this change.

@wlsc I'm curious how did you notice this case? Did you see something visually different in the graph, or just by looking at code?

**Comment by wlsc** [comment]
@dsmilkov I was curious about architecture and spotted this bug accidentally by browsing the python code

**Comment by vrv** [comment]
Merged

**Pull request closed without merging**
