### PR TITLE
[ROCm] Fixing RNNFowardV2 autotuning loop and unit tests

### PR DESCRIPTION
**Pull request by jerryyin**
The first commit is cherry-picked from #34532, and has been approved in #31849 (authored by @whchung ). Without the first commit, r1.15 branch will not build for the latest ROCm release.

The second commit is cherry picked from [#710](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/710). Fixed the RNN V2 kernels by enabled the auto-tuning loop in `ROCm` path. It should also fix the warning "No RNN Algorithm Found." `cudnn_recurrent_test` used to have 68 failures on value difference, now is all passing

### CODE REVIEW

**Comment by jerryyin** [comment]
I accidentally deleted the branch, causing the pull request to close. Reopening the pull request again.

**Review by chsigg — APPROVED** [review]

**Comment by deven-amd** [comment]
@jerryyin , please resolve the `Ubuntu Sanity` failures, and check whether the other failures are related to this PR

**Comment by mihaimaruseac** [comment]
Note that the currently running presubmits might still fail. https://github.com/tensorflow/tensorflow/pull/34532#issuecomment-574814561

**Comment by jerryyin** [comment]
Thanks for helping out @mihaimaruseac

**Pull request merged**
