### PR TITLE
Fix formatting of ops_version.md

### PR DESCRIPTION
**Pull request by ashutosh1919**
This is alternative of PR #36145 which was closed because of CLA issues. @mihaimaruseac, You approved that PR, please approve this one so that it can be merged.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
As it is identical to that one, we might need @settle to also approve of the 100% identical change.

**Comment by ashutosh1919** [comment]
> As it is identical to that one, we might need @settle to also approve of the 100% identical change.

Agree with you @mihaimaruseac . @settle, Please approve this PR if you think that the changes are identical to your previous PR #36145.

**Review by terryheo — COMMENTED** [review]
Could you update description as
"Fix formatting of ops_version.md" ?

**Comment by terryheo** [comment]
@ashutosh1919 Could you update description of the commit to "Fix formatting of ops_version.md" ?

**Review by terryheo — COMMENTED** [review]
I should be more specific.

Could you update the description of this commit?
https://github.com/tensorflow/tensorflow/pull/36479/commits/6a77480ec23b1014247eca3a7a7d3d158db85eb0

**Review by terryheo — APPROVED** [review]

**Review by terryheo — COMMENTED** [review]
I guess you shouldn't include this merge commit.
https://github.com/tensorflow/tensorflow/pull/36479/commits/5e11aa9aadc38650670fb57c3b6961182e66f9c6

**Comment by ashutosh1919** [comment]
> I guess you shouldn't include this merge commit.
> [5e11aa9](https://github.com/tensorflow/tensorflow/commit/5e11aa9aadc38650670fb57c3b6961182e66f9c6)

I have just synchronized it with the current master tf. How can it produce any kind of error?

**Pull request merged**
