### PR TITLE
[INTEL MKL] - Adding 'oneDNN' partials and Dockerfiles for 'RedHat 8'

### PR DESCRIPTION
**Pull request by ashahba**
This PR introduces:

- Partials and Dockerfiles for oneDNN based on `RedHat 8` 
- Misc updates for existing oneDNN partials

Like before this is how you generate the new Docker files and build the images:

```bash
$ export DOCKER_BUILD_ARGS=<extra docker build args specific to your environment, like proxies>
$ alias db="docker build ${DOCKER_BUILD_ARGS}"
$ export DOCKER_RUN_ENVS="extra docker run environment variables specific to your environment, like proxies"
$ alias dr="docker run --disable-content-trust ${DOCKER_RUN_ENVS}"
```

Finally start building containers:

```bash
$ cd tensorflow/tools/dockerfiles
$ db -t tf-tools -f tools.Dockerfile .

$ alias asm_dockerfiles="dr --rm -u $(id -u):$(id -g) -v $(pwd):/tf tf-tools python3 assembler.py "
$ alias asm_images="dr --rm -v $(pwd):/tf -v /var/run/docker.sock:/var/run/docker.sock tf-tools python3 assembler.py "
$ asm_dockerfiles --release dockerfiles --construct_dockerfiles

$ TF_VERSION=2.4.0 HOROVOD_VERSION=v0.21.1 && \
    asm_images ${PARTIALS_BUILD_ARGS} \
    --release onednn \
    --repository intel/intel-optimized-tensorflow \
    --arg BAZEL_VERSION=3.1.0 \
    --arg TF_BRANCH=v${TF_VERSION} \
    --arg TF_PACKAGE_VERSION=${TF_VERSION} \
    --arg _TAG_PREFIX=${TF_VERSION} \
    --arg REDHAT_VERSION=latest \
    --arg --network=host \
    --only_tags_matching '.*redhat-8' \
    -build_images
```

and this will produce the following images:
```bash
intel/intel-optimized-tensorflow:2.4.0-redhat-8
intel/intel-optimized-tensorflow:2.4.0-redhat-8-devel
intel/intel-optimized-tensorflow:2.4.0-redhat-8-devel-jupyter
intel/intel-optimized-tensorflow:2.4.0-redhat-8-devel-mpich-horovod
intel/intel-optimized-tensorflow:2.4.0-redhat-8-devel-mpich-horovod-jupyter
intel/intel-optimized-tensorflow:2.4.0-redhat-8-devel-mpi-horovod
intel/intel-optimized-tensorflow:2.4.0-redhat-8-devel-mpi-horovod-jupyter
intel/intel-optimized-tensorflow:2.4.0-redhat-8-jupyter
intel/intel-optimized-tensorflow:2.4.0-redhat-8-mpich-horovod
intel/intel-optimized-tensorflow:2.4.0-redhat-8-mpich-horovod-jupyter
intel/intel-optimized-tensorflow:2.4.0-redhat-8-mpi-horovod
intel/intel-optimized-tensorflow:2.4.0-redhat-8-mpi-horovod-jupyter
```

### CODE REVIEW

**Comment by claynerobison** [comment]
@sub-mod Can you take a look at this?

**Comment by ashahba** [comment]
@angerson would you also review and provide us with feedback?

Thanks.

**Comment by sub-mod** [comment]
> @sub-mod Can you take a look at this?

taking a look

**Comment by ashahba** [comment]
Hi @sub-mod were you able to review this? Any feedback for me?

Thanks.

**Comment by gbaned** [comment]
@angerson/@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@angerson /@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@angerson /@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@angerson /@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@angerson /@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@angerson /@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@angerson /@penpornk Can you please review this PR ? Thank you!

**Comment by ashahba** [comment]
The PR works as expected when run like this:

```
TF_VERSION=2.8.0 HOROVOD_VERSION=v0.24.3 && \
  asm_images ${PARTIALS_BUILD_ARGS} \
  --release onednn \
  --repository intel/intel-optimized-tensorflow \
  --arg BAZEL_VERSION=3.1.0 \
  --arg TF_BRANCH=v${TF_VERSION} \
  --arg TF_PACKAGE_VERSION=${TF_VERSION} \
  --arg _TAG_PREFIX=${TF_VERSION} \
  --arg REDHAT_VERSION=latest \
  --arg HOROVOD_VERSION=${HOROVOD_VERSION} \
  --arg --network=host \
  --arg SUBSCRIPTION_ORG=${SUBSCRIPTION_ORG} \
  --arg SUBSCRIPTION_KEY=${SUBSCRIPTION_KEY} \
  --only_tags_matching '.*redhat-8-mpich-horovod$' \
  -build_images
```

**Comment by ashahba** [comment]
@penpornk and @angerson any chance we can get this merged?

Thanks.

**Comment by ashahba** [comment]
I also cleaned up the PR so that it only brings `Red Hat 8` related files.

**Comment by bhack** [comment]
I think this was merged with https://github.com/tensorflow/tensorflow/commit/299cb76dd913e7bb0349a13c1165459dac4ea81e but the PR is not closed and put in a merged status.

We have collected this case in https://github.com/tensorflow/community/issues/413

**Comment by ashahba** [comment]
Thanks @bhack but I'm still seeing some diff in the change set.
It might be wise for me to just close this and bring a new PR if any changes didn't make it in.
What do you think? i'm open to ideas.

**Comment by gbaned** [comment]
@angerson /@penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
@angerson /@penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
@angerson /@penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @angerson /@penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @angerson /@penpornk Can you please review this PR ? Thank you!

**Comment by mihaimaruseac** [comment]
The docker containers will be moved in a different direction. I think we should instead close this.

**Comment by ashahba** [comment]
Holding off on this PR for now.

**Comment by ashahba** [comment]
This PR and #55418 will be revisited in the future.

**Pull request closed without merging**
