### PR TITLE
added `__restrict__` tag to all `__global__`kernels

### PR DESCRIPTION
**Pull request by ThisIsIsaac**
@chsigg 

I have added `__restrict__` tag to all `__global__` kernels.

However, I have left `GpuDeviceArrayStruct<T*>` alone, such as:

```cpp
__global__ void SplitVOpKernel_fixed(const T* __restrict__ input, int32 prefix_dim_size,
                                     int32 suffix_dim_size,
                                     GpuDeviceArrayStruct<T*> output_ptr_data) {
```

### CODE REVIEW

**Comment by ThisIsIsaac** [comment]
I have also prepared a PR for adding `__restrict__` to `__device__` kernels. I will send it once we are done with this one.

**Comment by ThisIsIsaac** [comment]
> I have also prepared a PR for adding __restrict__ to __device__ kernels. I will send it once we are done with this one.

Never mind this comment. I committed changed to both `__device__` and `__global__`.

**Comment by rmothukuru** [comment]
#31052

**Review by chsigg — COMMENTED** [review]
Thanks a lot Isaac! Could you run some benchmarks to check whether this has any impact.

**Comment by ThisIsIsaac** [comment]
@chsigg 

Since there are so many kernels, I think it would be better to profile them by calling the high-level python API instead of timing the kernels directly like we have been doing previously.

I am going to:
1. turn eager mode: `tf.enable_eager_execution()`
2. and call functions that call the CUDA kernels that have been modified using `%timeit`

Does this sound alright? I am not sure if there exists any additional overhead by turning on eager execution. Also, calling Python API would have overhead, but it seems negligible according to [this](https://gist.github.com/colesbury/41fc51225f25e72d7dd0049ec3966e04) conversation I had with a Pytorch dev.

**Comment by chsigg** [comment]
I think you know more than me ;-)
And yes, your plan sounds good.
You also don't need to benchmark every last kernel. A sampling should be sufficient.

**Comment by minty99** [comment]
@googlebot I fixed it.

**Comment by minty99** [comment]
@googlebot I consent.

**Comment by gbaned** [comment]
@ThisIsIsaac Could you please resolve the conflicts? Thanks!

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by ThisIsIsaac** [comment]
@gbaned planning on doing so as soon as I profile some meaningful results :)

**Comment by gbaned** [comment]
@ThisIsIsaac, Still, conflicts are appearing. Can you please resolve? Thanks!

**Comment by ThisIsIsaac** [comment]
@gbaned are you planning on merging once I resolve the conflict? I was going to resolve the conflict after I get approval so that there aren't more conflicts created while waiting for approval. If you are, then I will resolve the conflict ASAP.

**Review by chsigg — APPROVED** [review]

**Comment by chsigg** [comment]
I will resolve the conflict during merge.

**Comment by chsigg** [comment]
Oops, sorry. That doesn't work (tool limitation). Would you please fix the conflicts, then I will perform the merge. Thanks!

**Comment by ThisIsIsaac** [comment]
@chsigg @gbaned conflict resolved.

**Review by chsigg — APPROVED** [review]

**Comment by samikama** [comment]
@chsigg @ThisIsIsaac @gbaned  Are you sure that this blanket __restrict is a good idea? For example for some kernels, specifically non_max_suppression_op.cu.cc, it is pointless since compiler can see whether aliasing is possible or not, or in some cases aliasing might not be guaranteed. I believe __restrict__ keyword should be added case by case when its benefit is obvious, otherwise it is just complicating code. I did some tests for the some of the kernels modified by this PR, and compiler generated exactly the same assembly for both cases. Also these changes may introduce heisen-bugs that are data dependent and notoriously hard to debug.

**Comment by samikama** [comment]
In my tests for NMS op, I see a small slowdown due to this change. @ThisIsIsaac do you have some table from your profiling these changes are actually beneficial?

**Comment by ThisIsIsaac** [comment]
> Also these changes may introduce heisen-bugs that are data dependent and notoriously hard to debug.

I am not aware of any bugs that `__restrict__` can introduce, unless there are aliases to the pointers within the kernel.

---

> In my tests for NMS op, I see a small slowdown due to this change.

Could you share details of how and what versions you profiled against? I don't think `__restrict__` can slow down the speed, but please let me know if I am mistaken,.

When I profiled with below configuration:
**TF version**: 1.14
**GPU:** GTX1660 & V100
**code:**
```python
import tensorflow as tf
from IPython import get_ipython
ipython = get_ipython()
tf.enable_eager_execution()
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config)
t = tf.Variable(tf.random.uniform([50, 50, 50, 50]))
f = tf.Variable(tf.random.uniform([50, 50, 50, 50]))
ipython.magic('timeit out = tf.nn.conv2d(t, filter=f, padding="SAME")')
```

I saw **10% slowdown** but it turned out to be due to some other code that changed, not because of adding `__restrict__`. 

So I pulled from the commit right before I created my branch, copy-and-pasted the CUDA kernels instead of using the Python API.

After having profiled 3~4 kernels, there was about 3~5% increase in speed due to adding `__restrict__` using `float` type since it is the most popular one among `float`, `half`, `int` and `int8`. 


```cpp
template <typename T>
__global__ void UnaryClipCustomKernel(const int size_in, const T* __restrict__ in0,
                                      const T* __restrict__ in1, const T* __restrict__ in2, T* __restrict__ out) {
  for(int i = blockIdx.x * blockDim.x + threadIdx.x; i <= size_in; i += gridDim.x * blockDim.x) {
    T value = in2[0] < in0[i] ? in2[0] : in0[i];
    out[i] = value < in1[0] ? in1[0] : value;
  }
}
```

For example, `UnaryClioCustomKernel` seemed to have benefited from `__restrict__` because the global read bandwidth is only fully utilized if `sizeof(T) >= 4`. So for `half` and `int8` types, there is wasted bandwidth.

**Comment by chsigg** [comment]
I'm having some second thoughts as well that this might be on the risky side. I do like getting speedups almost for free, and I know that __restrict__ does help. Let's do some benchmarks and then decide. For example, remove the restricts where it doesn't help and look at the code more closely where it does.

**Comment by pooyadavoodi** [comment]
From CUDA programming guide about using `__restrict__` (confirming what @samikama said about performance):

> The effects here are a reduced number of memory accesses and reduced number of computations. This is balanced by an increase in register pressure due to "cached" loads and common sub-expressions.
> Since register pressure is a critical issue in many CUDA codes, use of restricted pointers can have negative performance impact on CUDA code, due to reduced occupancy.

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#restrict

**Comment by samikama** [comment]
@chsigg I was just pointing to the doc but @pooyadavoodi beat me to it. Our feelings on getting speedups almost for free is mutual, but I believe there are very few silver bullets left if any. __restrict will help in some cases but not necessarily all and even might worsen the performance as described in the manual. So I believe best would be doing it case-by-case basis, possibly by investigating investigating individual kernels by [nsight-compute](https://developer.nvidia.com/nsight-compute-2019_4) and by profiling them.

**Comment by samikama** [comment]
@ThisIsIsaac 

> I am not aware of any bugs that __restrict__ can introduce, unless there are aliases to the pointers 
> within the kernel.

Did you verify that pointer aliasing is never a possibility in the cases you modified? If pointer aliasing can happen, there will be hard to trace bugs in the results.

> Could you share details of how and what versions you profiled against? I don't think __restrict__
> can slow down the speed, but please let me know if I am mistaken.

Please see comment above.
Also, correct me if I am wrong but in your example above, having in and out to point the same array is perfectly fine right? It would be in-place clipping. However you are promising the compiler that they are never going to be same or alias each other. 
As I mentioned above, I suggest using nsight-compute to verify your changes actually improve the the results, if possible significantly.

**Comment by ThisIsIsaac** [comment]
@chsigg @samikama 

After having read the doc, I also think it is best to profile per-kernel instead of applying a sweeping change to all kernels. 

I will work with @minty99 and break this PR into smaller PRs per kernel.

Thanks again for your insights :)

**Pull request merged**
