### PR TITLE
Update BUILD

### PR DESCRIPTION
**Pull request by Anil9703**
I think that their might be a punctual error in using comma in line19

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @Anil9703 Can you please sign CLA. Thank you!

**Comment by Anil9703** [comment]
> Hi @Anil9703 Can you please sign CLA. Thank you!
Yeah, can you please provide the link to sign CLA?
Thank you

**Comment by Anil9703** [comment]
> Contributor
I have signed CLA just now

**Comment by gbaned** [comment]
Hi @Anil9703, Please submit multiple typo fixes in a single PR as the CPU/GPU hours are wasted on CI. 
Hence, we do not encourage one liner grammatical changes as it is an expensive process. Thank you for your contribution!

**Comment by mihaimaruseac** [comment]
Actually, this PR is invalid and spam. Bazel BUILD files end all lines with a comma.

**Pull request closed without merging**
