### PR TITLE
Remove third_party/ prefixes

### PR DESCRIPTION
**Pull request by Androbin**

### CODE REVIEW

**Comment by drpngx** [comment]
Not sure if we want to do this internally. Thanks for pointing out.

**Comment by Androbin** [comment]
@drpngx What you mean? The community guidelines should not have the prefix. Not a single `BUILD` file in this repository does.

**Comment by drpngx** [comment]
Sorry, I meant I'm not sure if we want to push this internally first. This is tied to our exporting scripts. I feel that it should be easier to fix it internally and push forward instead of merging this in. @yifeif would know.

**Comment by yifeif** [comment]
Thanks @Androbin! I'm going to fix this internally for the reason @drpngx mentioned.

**Pull request closed without merging**
