### PR TITLE
Point directly to guide without alpha

### PR DESCRIPTION
**Pull request by lc0**

### CODE REVIEW

**Review by lamberta — APPROVED** [review]
Thanks! This is correct. I'm working on a larger PR that will update tensorflow/tensorflow

(Though redirects will forward this along)

**Comment by lc0** [comment]
> Thanks! This is correct. I'm working on a larger PR that will update tensorflow/tensorflow
> 
> (Though redirects will forward this along)

yeah, it works fine, it's just that i was re-reading docs and decided to submit this small change in place.

**Comment by rthadur** [comment]
similar changes are pushed by ` db6be9c ` , so closing this PR, thank you

**Comment by lc0** [comment]
> db6be9c

@rthadur I think your reference is wrong, since mentioned commit is not addressing it - https://github.com/tensorflow/tensorflow/commit/db6be9c

**Comment by lamberta** [comment]
Looks like the fix landed in https://github.com/tensorflow/tensorflow/commit/4f1336086675aaf747703ad26b4a01743f8ed85c
Thanks

**Pull request closed without merging**
