### PR TITLE
add type to T for FusedResizeAndPadConv2D and FusedPadConv2D

### PR DESCRIPTION
**Pull request by chaosink**
Issue: https://github.com/tensorflow/tensorflow/issues/19228

### CODE REVIEW

**Comment by chaosink** [comment]
I signed it!

**Review by rmlarsen — CHANGES_REQUESTED** [review]
Please update the unit tests to test with the added types.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/conv_ops_test.cc#L89

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
