### PR TITLE
Fix incompatibility in ’tensorflow/core/kernels:cwise_op_gpu’ with Clang

### PR DESCRIPTION
**Pull request by kazuki0824**
It is reported that Clang cannot handle "cwise_ops_gpu_common.cu.h." in #27253 and #26159.  This PR is a patch to avoid the issue.

### CODE REVIEW

**Comment by kazuki0824** [comment]
I signed it!

**Comment by ezhulenev** [comment]
The right fix is to add missing functions to Eigen `Eigen/src/Core/arch/GPU/PacketMath.h`. /cc @rmlarsen

**Comment by kazuki0824** [comment]
For reviewers @ezhulenev : Clang has a bug that -O2 and -D_FORTIFY_SOURCE cannot coexist when running "clang -x cuda" , so you might have to modify 'bazel-tensorflow/external/local_config_download_clang/extra_tools/lib/clang/8.0.0/include/__clang_cuda_runtime_wrapper.h' like below before you begin building. Thank you.

```diff
-#include <string.h>
+#if defined(__fortify_function)
+#define __tmp_value __fortify_function
+#undef __fortify_function
+#include <string.h>
+#define __fortify_function __tmp_value
+#undef __tmp_value
+#else
+#include <string.h>
+#endif
```

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
