### PR TITLE
[TFLite] Add support for Particle MCUs to TensorFlow Lite Micro

### PR DESCRIPTION
**Pull request by bsatrom**
This is a WIP PR for adding support for Particle MCUs to TFLite Micro. It includes the following:

- [x] `debug_log` implementation for Particle
- [x] `hello_world` example source
- [x] Particle additions to `Makefile` and `helper_functions.inc`
- [x] `test_particle.sh`
- [x] Generate and merge zips in a similar fashion to Arduino builds
- [x] Modifications to `transform_source.py`
- [x] Add `magic_wand` source
- [x] Add `micro_speech` source

Still to complete:

- [ ] Remove `fprintf` calls from `kissfft` for Particle projects
- [ ] Transform example projects for standard Particle project formats (`project.properties` and `src` directory)

### CODE REVIEW

**Comment by bsatrom** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
@bsatrom This PR is in draft, any update on this? Please. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by bsatrom** [comment]
No longer valid

**Pull request closed without merging**
