### PR TITLE
Doc example update

### PR DESCRIPTION
**Pull request by grofte**
Wrong variable called in example, query_input -> value_input

### CODE REVIEW

**Comment by grofte** [comment]
@googlebot I signed it!

**Comment by mihaimaruseac** [comment]
Please open against master.

**Review by qlzh727 — APPROVED** [review]
Thanks for the fix.

**Review by qlzh727 — CHANGES_REQUESTED** [review]
Please open the PR against the master branch.

**Comment by gbaned** [comment]
@grofte closing this PR. As mentioned by @mihaimaruseac, @qlzh727, please open the PR against the master branch. Thanks!

**Pull request closed without merging**
