### PR TITLE
Fix tensorflow lite label_image cmake build error.

### LINKED ISSUE #70659: TensorFlow Lite label_image fails to build with cmake
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v2.17.0-rc0

### Custom code

No

### OS platform and distribution

Linux (Raspberry Pi OS)

### Mobile device

Raspberry Pi 4

### Python version

3.11.2

### Bazel version

_No response_

### GCC/compiler version

12.2.0

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current behavior?

I get the error 
> tensorflow/lite/profiling/proto/profiling_info.pb.h: No such file or directory.

### Standalone code to reproduce the issue

```shell
$ git clone -b v2.17.0-rc0 https://github.com/tensorflow/tensorflow
$ mkdir tflite_build && tflite_build
$ cmake ../tensorflow/tensorflow/lite/
$ cmake --build . -j3
$ cmake --build . -t label_image
In file included from /home/pi/tensorflow/tensorflow/lite/profiling/profile_summarizer.h:28,
                 from /home/pi/tensorflow/tensorflow/lite/profiling/profile_summarizer.cc:16:
/home/pi/tensorflow/tensorflow/lite/profiling/profile_summary_formatter.h:31:10: fatal error: tensorflow/lite/profiling/proto/profiling_info.pb.h: No such file or directory
   31 | #include "tensorflow/lite/profiling/proto/profiling_info.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```
```


### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by NobuoTsukamoto**
Fix #70659

### CODE REVIEW

**Comment by keerthanakadiri** [comment]
Hi @mattsoulanille Can you please review this PR? Thank you .

**Comment by keerthanakadiri** [comment]
Hi @mattsoulanille Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @mattsoulanille, Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @mattsoulanille, Can you please review this PR? Thank you !

**Review by mattsoulanille — APPROVED** [review]

**Pull request merged**
