### PR TITLE
Python style, added spaces between arguments

### PR DESCRIPTION
**Pull request by h0pbeat**

### CODE REVIEW

**Comment by h0pbeat** [comment]
I'm a Googler.

**Comment by danmane** [comment]
What's your LDAP?

**Comment by danmane** [comment]
Found it.

**Comment by danmane** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
Can you use your google email on the commit instead?

**Comment by agarwal-ashish** [comment]
Is this tested on tensorflow-jenkins ?

**Comment by vrv** [comment]
(Closing, re-open if you can amend your commits with the right email)

**Pull request closed without merging**
