### PR TITLE
Added 8-bit Quantization support for one_hot op.

### PR DESCRIPTION
**Pull request by amitsrivastava78**
This was also a TODO item in the code.

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@alanchiao ,can you pls review the PR.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alanchiao: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alanchiao: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alanchiao: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 46 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alanchiao: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alanchiao: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by alanchiao** [comment]
Looks like you've created https://github.com/tensorflow/tensorflow/pull/28279. Should we close this Pull Request then?

**Comment by amitsrivastava78** [comment]
@alanchiao , thanks for pointing this out, i am closing this PR and will update the changes in #28279

Regards
Amit

**Pull request closed without merging**
