### PR TITLE
remove validation_data from docstring of Callback class

### LINKED ISSUE #36375: AttributeError: 'Callback' object has no attribute 'validation_data'
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/Callback

## Description of issue (what needs changing):

Currently, the page https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/Callback says `validation_data: Deprecated. Do not use.`, but if I attempt to access the attribute `validation_data` inside the callback I get the error `AttributeError: 'MyCustomCallbackClass' object has no attribute 'validation_data'.`. You should change the documentation to remove the attribute `validation_data`, which apparently was removed.

### PR DESCRIPTION
**Pull request by rushabh-v**
resolves #36375

### CODE REVIEW

**Comment by rushabh-v** [comment]
@rchao Can you please review this PR?

**Comment by rushabh-v** [comment]
Can somebody take a look here, please?

**Review by rchao — COMMENTED** [review]
Thanks for the PR! Given that the cost of keeping this attr in the docstring is low, I think it is fine that we have it there until the next time we can have a breaking change.

**Comment by gbaned** [comment]
@rchao Any update on this PR? Please. Thanks!

**Review by rchao — COMMENTED** [review]
Thanks for the PR. This change was made in https://github.com/tensorflow/tensorflow/commit/1286b957c21eea2e956a51fcd758653ed7e7cb36.

**Comment by rushabh-v** [comment]
okay

**Pull request closed without merging**
