### PR TITLE
Add missing grpc dependency to include the proto_util.h header

### PR DESCRIPTION
**Pull request by jhseu**

### CODE REVIEW

**Comment by jhseu** [comment]
@nlopezgi

**Comment by vrv** [comment]
windows cmake test looks a bit concerning, seems related to protobuf change, but is that related?

**Comment by jhseu** [comment]
Doesn't seem like it could be related since it's a different build system.

Clicking the Rebuild button in Jenkins to try again.

**Review by vrv — APPROVED** [review]

**Comment by jhseu** [comment]
Looks like Windows passes now. Merging this to fix the issue.

**Pull request merged**
