### PR TITLE
Enable tf.sqrt() for SparseTensor

### PR DESCRIPTION
**Pull request by siddharth-agrawal**
Enabled `tf.sqrt()` for `SparseTensor`. Added tests and verified locally. This partially addresses #1828.

### CODE REVIEW

**Comment by maciekcc** [comment]
Thanks!

Can you please change this a little and make sure that we use the higher tolerance threshold (1e-3) only for testing sqrt? If the other tests pass with the default value of: 1e-6 let us leave it this way.

**Comment by siddharth-agrawal** [comment]
@maciekcc Updated the PR. Let me know if this is okay.

**Comment by maciekcc** [comment]
Thanks for the update!

Sorry for nit-picking :). Can you please pass the tolerance explicitly in the test body, say:

`self._compareBothSparse(z, np.sqrt, tf.sqrt, tolerance=1e-3)`

pass it down to _check and use `None` as default value. This way you can rely on the defaults defined in the super class. You do not need to keep them synced in two places, and overload only when you want to. Maybe something like this will do:

'
def _check(self, result_tensor, result_np, input_sp_t, tolerance=None):
  ..
  if tolerance is None:
    self.assertAllClose(result_np, result_tensor.values.eval())
  else:
    self.assertAllClose(result_np, result_tensor.values.eval(), rtol=tolerance, atol=tolerance)

`

**Comment by siddharth-agrawal** [comment]
@maciekcc Updated.

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Pull request merged**
