### PR TITLE
Speedup the TFLu Renode tests

### PR DESCRIPTION
**Pull request by JakubJatczak**
This is a proposed way to reduce the execution time of TFLu Renode tests by generating all tests cases in Robot.
**The changes are applied only to the Bluepill target related files and are not yet integrated with `make test`.**
Main changes:
* `test_bluepill_binary.sh` now takes directory containing test binaries as argument,
* `.robot` runs test on all files found in given directory,
* console output was changed to suit the new approach.

Running the `tensorflow/lite/micro/testing/test_bluepill_binary.sh  tensorflow/lite/micro/tools/make/gen/bluepill_cortex-m3/bin/` will ouput:
* In case of PASS:
```
Preparing suites
Started Renode instance on port 9999; pid 62470
Starting suites
Running /home/jakub/Dokumenty/renode-tensorflow/tensorflow/lite/micro/testing/bluepill.robot
+++++ Starting test 'bluepill.Should Run All Bluepill Tests'
	detection_responder_test - PASSED
	detection_responder_test_int8 - PASSED
	greedy_memory_planner_test - PASSED
	hello_world_test - PASSED
        [...]
	simple_memory_allocator_test - PASSED
	testing_helpers_test - PASSED
+++++ Finished test 'bluepill.Should Run All Bluepill Tests' in 34.06 seconds with status OK
Cleaning up suites
Closing Renode pid 62470
Aggregating all robot results
Output:  /tmp/test_bluepill_binary/robot_output.xml
Log:     /tmp/test_bluepill_binary/log.html
Report:  /tmp/test_bluepill_binary/report.html
Tests finished successfully :)
PASS
```
* In case of FAIL:
```
Preparing suites
Started Renode instance on port 9999; pid 83495
Starting suites
Running /home/jakub/Dokumenty/renode-tensorflow/tensorflow/lite/micro/testing/bluepill.robot
+++++ Starting test 'bluepill.Should Run All Bluepill Tests'
	detection_responder_test - PASSED
	detection_responder_test_int8 - PASSED
	greedy_memory_planner_test - PASSED
	hello_world_test - PASSED
        [...]
	kernel_elementwise_test - PASSED
+++++ Finished test 'bluepill.Should Run All Bluepill Tests' in 9.14 seconds with status failed
      ╔═
      ║ kernel_floor_test - FAILED
      ╚═
Cleaning up suites
Closing Renode pid 83495
Aggregating all robot results
Output:  /tmp/test_bluepill_binary/robot_output.xml
Log:     /tmp/test_bluepill_binary/log.html
Report:  /tmp/test_bluepill_binary/report.html
Some tests failed :( See logs for details!
UART LOGS:
[...]
~~~SOME TESTS FAILED~~~
```

### CODE REVIEW

**Comment by freddan80** [comment]
tagging @mansnils

**Comment by advaitjain** [comment]
Thanks @JakubJatczak. I think we're headed in the right direction.

Couple of high level feedback:
 * This doesn't have to be part of this pull request but prior to turning this on as part of CI, we will need to be able to selectively turn off running certain tests, if needed.
 * In your sample output, I don't see the logs from the failed test. Was this intentional? We will want to see the logs for all the failed tests.
 * If more than one test fails, will we run through all of them regardless? That would be preferred so that we can see all the failing tests in one go.
 * The format of the .robot file is pretty opaque to me (though I haven't really looked at the Renode docs either). A description of what this test suite is doing and some pointers into the renode docs from [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/docs/renode.md) would be very useful in making this easier to maintain in the future.

**Comment by advaitjain** [comment]
> * This doesn't have to be part of this pull request but prior to turning this on as part of CI, we will need to be able to selectively turn off running certain tests, if needed.

On second thought, I take this back. With the current makefile system we can exclude a test from being built for a particular target. That is sufficient for now.

**Comment by JakubJatczak** [comment]
> In your sample output, I don't see the logs from the failed test. Was this intentional? We will want to see the logs for all the failed tests.

I omitted UART logs to reduce length of the example.  Please see the full fail (forced by manually changing golden values) output example below:
``` 
$> tensorflow/lite/micro/testing/test_bluepill_binary.sh tensorflow/lite/micro/tools/make/gen/bluepill_cortex-m3/bin '~~~ALL TESTS PASSED~~~'

Preparing suites
Started Renode instance on port 9999; pid 53718
Starting suites
Running /home/jakub/Dokumenty/renode-tensorflow/tensorflow/lite/micro/testing/bluepill.robot
+++++ Starting test 'bluepill.Should Run All Bluepill Tests'
	detection_responder_test - PASSED
	detection_responder_test_int8 - PASSED
	greedy_memory_planner_test - PASSED
	hello_world_test - PASSED
	image_provider_test - PASSED
	image_provider_test_int8 - PASSED
	kernel_activations_test - PASSED
+++++ Finished test 'bluepill.Should Run All Bluepill Tests' in 10.63 seconds with status failed
      ╔═
      ║ kernel_add_test - FAILED
      ╚═
Cleaning up suites
Closing Renode pid 53718
Aggregating all robot results
Output:  /tmp/test_bluepill_binary/robot_output.xml
Log:     /tmp/test_bluepill_binary/log.html
Report:  /tmp/test_bluepill_binary/report.html
Some tests failed :( See logs for details!
UART LOGS:
Testing FloatAddNoActivation
golden[i] (-1.0999994*2^2) near output[i] (-1.8999992*2^0) failed at tensorflow/lite/micro/kernels/add_test.cc:87
golden[i] (1.0999994*2^2) near output[i] (1.5999993*2^-2) failed at tensorflow/lite/micro/kernels/add_test.cc:87
golden[i] (1.0999994*2^2) near output[i] (1.0*2^0) failed at tensorflow/lite/micro/kernels/add_test.cc:87
golden[i] (1.0999994*2^2) near output[i] (1.2999993*2^0) failed at tensorflow/lite/micro/kernels/add_test.cc:87
Testing FloatAddActivationRelu1
Testing FloatAddVariousInputShapes
Testing FloatAddWithScalarBroadcast
Testing QuantizedAddNoActivationUint8
Testing QuantizedAddNoActivationInt8
Testing QuantizedAddActivationRelu1Uint8
Testing QuantizedAddActivationRelu1Int8
Testing QuantizedAddVariousInputShapesUint8
Testing QuantizedAddVariousInputShapesInt8
Testing QuantizedAddWithScalarBroadcastUint8
Testing QuantizedAddWithScalarBroadcastFloat
Testing QuantizedAddWithScalarBroadcastInt8
Testing QuantizedAddWithMixedBroadcastUint8
Testing QuantizedAddWithMixedBroadcastInt8
14/15 tests passed
~~~SOME TESTS FAILED~~~
```
> If more than one test fails, will we run through all of them regardless? That would be preferred so that we can see all the failing tests in one go.

It will not - just like in the current approach, the tests will stop after first failure. It is possible to achieve what you ask for, but this will require significant changes to the approach. 

> The format of the .robot file is pretty opaque to me (though I haven't really looked at the Renode docs either). A description of what this test suite is doing and some pointers into the renode docs from here would be very useful in making this easier to maintain in the future.

I added `Documentation` section to custom `Keywords` to make it a little bit cleaner, but I understand that it doesn't solve the problem. Do you think that adding single link to the [testing section of the docs](https://renode.readthedocs.io/en/latest/introduction/testing.html) will be enough or should we add something about the test suite flow?

**Review by advaitjain — APPROVED** [review]
Approved, let's merge this pull request with the understanding that we are in prototyping mode.

I am adding some notes and changes as I learn a bit more about the Robot Framework and will send a follow-up PR with some of these improvements.

**Pull request merged**
