### PR TITLE
contrib: minor spelling tweaks

### PR DESCRIPTION
**Pull request by brettkoonce**

### CODE REVIEW

**Review by protoget — DISMISSED** [review]
Thank you! Looks great.

**Comment by brettkoonce** [comment]
@protoget rebased to master, thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 33 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 48 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 63 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 78 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 93 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by brettkoonce** [comment]
dropped conflicting part of commit, hope this helps!

**Review by m3bm3b — APPROVED** [review]
Looks good.  Thanks.

**Pull request merged**
