### PR TITLE
Add "AddV2" to tensorflow v1 flops calculation

### PR DESCRIPTION
**Pull request by tigert1998**

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Why? It's strange to add a V2 operation to a V1 collection

**Comment by tigert1998** [comment]
Because addv2 is not involved in flops profile. IDK if there is a v2 collection or not. But if there is, I did not find it.

**Comment by mihaimaruseac** [comment]
Is there a usecase where this is needed? What are you trying to do? I'm trying to understand why this needs to be done, and it seems we have an [XY problem](http://xyproblem.info/) here

**Comment by tigert1998** [comment]
# A problem I encountered:

When a serialized protobuf neural network (frozen pb, saved model) contains "AddV2" instead of "Add" operator, the flops of this operator ("AddV2") obtained from using `tf.profiler.ProfileOptionBuilder.float_operation` shows 0.

# What I want:

I want the flops from "AddV2" operator being counted when using `tf.profiler`.

# What I found:

"AddV2" is not registered in flops calculation.

# What I did:

Register "AddV2" to flops calculation.

**Review by mihaimaruseac — APPROVED** [review]
Makes sense now. LGTM to me but let's see what the internal review might add.

**Comment by mihaimaruseac** [comment]
This breaks internal tests and has been automatically rolled back.

**Comment by tigert1998** [comment]
Are there any methods to check which test is broken?

**Pull request merged**
