### PR TITLE
make applications using TFLite work on ARM64 Linux (non-Android) platforms

### PR DESCRIPTION
**Pull request by freedomtan**
When build TF Lite related stuff such as lable_image for tflite on ARMv64 non-Android environment (I am running Debian on an internal development board). I saw something like:

 ```
 /home/freedom/work/tensorflow/tensorflow/contrib/lite/kernels/internal/BUILD:264:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels/internal:neon_tensor_utils' failed (Exit 1)
  gcc: error: unrecognized command line option '-mfpu=neon'
  gcc: error: unrecognized command line option '-mfloat-abi=softfp'
```

It seems ARM64 falls into the ":arm" category. After removing it, I can build my tflite-based command line programs without problems.

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by freedomtan** [comment]
rebased to resolve a conflict

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 81 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 96 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by Davidnet** [comment]
I had this issue with the jetson tx2. Thanks for the PR

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @aselle: It has been 29 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewers @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Review by andrehentz — DISMISSED** [review]

**Comment by raziel** [comment]
Hi. This is my understanding of the issue:

NEON is mandatory (always present) for aarch64 (arm64), so -mfpu and -mfloat are not only not needed but invalid as the aarch64 and arm backends are completely separate in gcc.
They're needed for the arm 32 archs like armeabi-v7a, and armv7a though.
Having said that, the -O3 option is still needed on both, so it's good it's the default here.

I also can see how if you're compiling, the arm64-v8a would map to the arm target. But I also see how on a 32 bit arm it would also do the same (I haven't tried myself).

So, can you try adding a more specific target:

    ":arm64-v8a": [
        "-O3",
    ],

Otherwise, by removing the arm target, there could be 32 bit cases that would not get the flags needed.

**Comment by psyhtest** [comment]
@freedomtan Unfortunately, building with your patch on the TX1 failed as follows (see platform details in https://github.com/tensorflow/tensorflow/issues/21332):
```
ERROR: /home/anton/CK_TOOLS/lib-tensorflow-src-cpu-1.9-compiler.python-2.7.12-linux-64/src/tensorflow/contrib/lite/kernels/BUILD:128:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels:builtin_ops' failed (Exit 1)
In file included from ./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8.h:21:0,
                 from tensorflow/contrib/lite/kernels/depthwise_conv.cc:26:
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:80:43: error: expected primary-expression before ',' token
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==
                                           ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:80:45: error: 'input_depth' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==
                                             ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:80:56: error: 'offsetof' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==
                                                        ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:82:43: error: expected primary-expression before ',' token
 static_assert(offsetof(DepthwiseConvParams, input_row_size) ==
                                           ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:82:45: error: 'input_row_size' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, input_row_size) ==
                                             ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:82:59: error: 'offsetof' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, input_row_size) ==
                                                           ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:84:43: error: expected primary-expression before ',' token
 static_assert(offsetof(DepthwiseConvParams, output_depth) ==
                                           ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:84:45: error: 'output_depth' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, output_depth) ==
                                             ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:84:57: error: 'offsetof' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, output_depth) ==
                                                         ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:86:43: error: expected primary-expression before ',' token
 static_assert(offsetof(DepthwiseConvParams, output_row_size) ==
                                           ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:86:45: error: 'output_row_size' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, output_row_size) ==
                                             ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:86:60: error: 'offsetof' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, output_row_size) ==
                                                            ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:88:43: error: expected primary-expression before ',' token
 static_assert(offsetof(DepthwiseConvParams, input_offset) ==
                                           ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:88:45: error: 'input_offset' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, input_offset) ==
                                             ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:88:57: error: 'offsetof' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, input_offset) ==
                                                         ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:90:43: error: expected primary-expression before ',' token
 static_assert(offsetof(DepthwiseConvParams, output_offset) ==
                                           ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:90:45: error: 'output_offset' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, output_offset) ==
                                             ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:90:58: error: 'offsetof' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, output_offset) ==
                                                          ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:92:43: error: expected primary-expression before ',' token
 static_assert(offsetof(DepthwiseConvParams, filter_offset) ==
                                           ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:92:45: error: 'filter_offset' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, filter_offset) ==
                                             ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:92:58: error: 'offsetof' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, filter_offset) ==
                                                          ^
...
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 21412.854s, Critical Path: 162.92s
INFO: 3111 processes: 3111 local.
```

**Comment by freedomtan** [comment]
@psyhtest Don't know why that happened. I ran Debian on an internal board and also chroot() debian rootfs on various rooted Android devices. Tested with both gcc-6 and gcc-7.

**Comment by psyhtest** [comment]
@freedomtan I will try on a couple of other boards. This failure might be due to gcc-5 not being to reach some headers. But this suggests a proper fix is needed (although it's useful to know about the workaround).

**Comment by psyhtest** [comment]
Same result on HiKey960:
```
ERROR: /home/anton/CK_TOOLS/lib-tensorflow-src-cpu-1.9-compiler.python-2.7.13-linux-64/src/tensorflow/contrib/lite/kernels/BUILD:128:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels:builtin_ops' failed (Exit 1)
In file included from ./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8.h:21:0,                                                                          
                 from tensorflow/contrib/lite/kernels/depthwise_conv.cc:26:                                                                                          
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:80:43: error: expected primary-expression before ',' token      
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==      
                                           ^                     
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:80:45: error: 'input_depth' was not declared in this scope 
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==                                                                    
                                             ^~~~~~~~~~~                                                                                                                                                                          
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:80:56: error: 'offsetof' was not declared in this scope                                                                 
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==          
                                                        ^   
...
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 16652.070s, Critical Path: 857.48s
INFO: 4664 processes, local.
FAILED: Build did NOT complete successfully
```

**Comment by psyhtest** [comment]
@freedomtan Apologies, I've only just noticed that you opened this PR on 17 January 2018, i.e. between TF 1.4 (2 November 2017) and TF 1.5 (26 January 2018), while I didn't have any problem building on aarch64 platforms until 1.8 (19 April 2018). So your fix has helped me to make progress on building TF 1.9, but the actual failure is different. Thanks.

**Comment by freedomtan** [comment]
@psyhtest I usually build master branch. Yes, I sent this PR in Jan, 2018 when I was trying to build TF Lite at that time. I use TensorFlow master on the board and build pip package from time to time since then.

Regarding the offsetof(), which is supposed to be defined in `stddef.h`, problem, I don't know why NVIDIA's Linux doesn't define it. Maybe Denver 2 of TX2 is weird. However, I think something like
```
#define offsetof(type, member) ((size_t)* ((type *) 0)->member)
```
should work most of the time. And for HiKey 960, which Linux distro your uses?

**Comment by psyhtest** [comment]
@freedomtan This problem might have appeared between the 1.4 and 1.5 releases. Unless you know the exact revision, we might never find out. (Not that I want to become a TF archaeologist. :)

Anyway, it is back with a vengeance. Still, I managed to build it on HiKey960 (Debian 9) by commenting out all asserts in `depthwiseconv_uint8_3x3_filter.h` as follows:
```
anton@hikey962:~/CK_REPOS/ck-tensorflow$ cat package/lib-tensorflow-1.9.0-src-cpu/patch.linux/offsetof-off.patch
diff --git a/tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h b/tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
index 8cd72239e9..a7c4cf8f76 100644
--- a/tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
+++ b/tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
@@ -76,7 +76,7 @@ struct DepthwiseConvParams {
 #define OFFSET_INPUT_HEIGHT 64
 #define OFFSET_OUTPUT_WIDTH 68
 #define OFFSET_OUTPUT_HEIGHT 72
-
+#if 0
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==
                   OFFSET_INPUT_DEPTH, "");
 static_assert(offsetof(DepthwiseConvParams, input_row_size) ==
@@ -107,7 +107,7 @@ static_assert(offsetof(DepthwiseConvParams, output_width) ==
                   OFFSET_OUTPUT_WIDTH, "");
 static_assert(offsetof(DepthwiseConvParams, output_height) ==
                   OFFSET_OUTPUT_HEIGHT, "");
-
+#endif
```

**Comment by freedomtan** [comment]
@psyhtest I've been using Debian unstable (which is supposed to be Debian 10 under development at this time) to build TensorFlow master branch on my board and chroot() Android devices more than one year, which includes 1.4 to 1.9, without running into `offsetof()` problem. 

So, if your environment has `offsetoff()` problem, I think probably the "right" solution is to add something like, 
```
#ifdef MY_DEBIAN_WHATEVER_WITHOUT_OFFSETOF
#define offsetof(type, member) ......
#endif
````

**Comment by tensorflowbutler** [comment]
Nagging Assignees @achowdhery, @benoitsteiner: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by freedomtan** [comment]
it turns out why aarch64/arm64 falls into `arm:` is bazel's problem, after https://github.com/bazelbuild/bazel/commit/886d01c89fca32e46f5841081eb3288e5b4f313b, in bazel 0.16.0 or later, arm64 will be recognized as `aarch64`. So I'll revert this and add `aarch64` related settings.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by freedomtan** [comment]
The one I used to build and test this patch last time was 0.16.1

**Comment by tensorflowbutler** [comment]
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @achowdhery: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by freedomtan** [comment]
rebased because TFLite moved from tensorflow/contrib to tensorflow/

**Review by andrehentz — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by depthwise** [comment]
Related PR: #24876

**Pull request merged**
