### PR TITLE
Add evaluation tools to cmake build

### PR DESCRIPTION
**Pull request by robert-kalmar**
The pull request extends the CMake with option to build the tools for accuracy and correctness evaluation of the delegates (https://www.tensorflow.org/lite/performance/delegates#accuracy_correctness). Supports both native and cross-compilation scenario.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @robert-kalmar Can you please sign CLA. Thank you!

**Comment by robert-kalmar** [comment]
Hi @gbaned, can you help to identify what is wrong with the CLA? Based on the report Irina's CLA is ok, and my is missing. 
image
What is strange, as I have the same corporate CLA, and it got verified fine e.g. here [ verified e.g. on PR here](https://github.com/tensorflow/tensorflow/pull/62933)

**Comment by gbaned** [comment]
Hi @robert-kalmar Sorry for the delay on response. Can you please make sure to use same GitHub username and email-id associated with it. Thank you!

**Comment by gbaned** [comment]
Hi @robert-kalmar I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for your contribution!

**Pull request closed without merging**
