### PR TITLE
Move stateless ops out of contrib

### PR DESCRIPTION
**Pull request by girving**
Phase two!

### CODE REVIEW

**Comment by girving** [comment]
`//tensorflow/tools/api/tests:api_compatibility_test` still passes for me (on Mac with Python 3), and `--update_goldens` does nothing.  Someone else will have to run it for me.

**Comment by hsgkim** [comment]
`//tensorflow/tools/api/tests:api_compatibility_test` should be run with Python 2 only. The test is set to just be skipped when it's invoked with Python 3.

**Comment by girving** [comment]
@martinwicke said it should work with Python 3 now, but indeed it's still skipped in that case.  Should that be fixed?

**Comment by martinwicke** [comment]
I guess I was wrong. @annarev will know for certain. It's possible that the py2/py3 differences in the system libraries are too large to make it feasible to maintain this in the same files. We may have to hard-switch at some point.

**Review by alextp — DISMISSED** [review]

**Comment by drpngx** [comment]
@girving you need to run the `api_compatibility_test` with py2 or update the goldens manually:
 ```
Issue 1	: 'path: "tensorflow.random"\ntf_module {\n  member_method {\n    name: "gamma"\n  [truncated]... != 'path: "tensorflow.random"\ntf_module {\n  member_method {\n    name: "gamma"\n  [truncated]...
  path: "tensorflow.random"
  tf_module {
    member_method {
      name: "gamma"
      argspec: "args=[\'shape\', \'alpha\', \'beta\', \'dtype\', \'seed\', \'name\'], varargs=None, keywords=None, defaults=[\'None\', \"<dtype: \'float32\'>\", \'None\', \'None\'], "
    }
    member_method {
      name: "get_seed"
      argspec: "args=[\'op_seed\'], varargs=None, keywords=None, defaults=None"
    }
    member_method {
      name: "log_uniform_candidate_sampler"
      argspec: "args=[\'true_classes\', \'num_true\', \'num_sampled\', \'unique\', \'range_max\', \'seed\', \'name\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
    }
    member_method {
      name: "multinomial"
      argspec: "args=[\'logits\', \'num_samples\', \'seed\', \'name\', \'output_dtype\'], varargs=None, keywords=None, defaults=[\'None\', \'None\', \'None\'], "
    }
    member_method {
      name: "normal"
      argspec: "args=[\'shape\', \'mean\', \'stddev\', \'dtype\', \'seed\', \'name\'], varargs=None, keywords=None, defaults=[\'0.0\', \'1.0\', \"<dtype: \'float32\'>\", \'None\', \'None\'], "
    }
    member_method {
      name: "poisson"
      argspec: "args=[\'lam\', \'shape\', \'dtype\', \'seed\', \'name\'], varargs=None, keywords=None, defaults=[\"<dtype: \'float32\'>\", \'None\', \'None\'], "
    }
    member_method {
      name: "set_random_seed"
      argspec: "args=[\'seed\'], varargs=None, keywords=None, defaults=None"
    }
    member_method {
      name: "shuffle"
      argspec: "args=[\'value\', \'seed\', \'name\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
    }
    member_method {
+     name: "stateless_multinomial"
+     argspec: "args=[\'logits\', \'num_samples\', \'seed\', \'output_dtype\', \'name\'], varargs=None, keywords=None, defaults=[\"<dtype: \'int64\'>\", \'None\'], "
+   }
+   member_method {
+     name: "stateless_normal"
+     argspec: "args=[\'shape\', \'seed\', \'mean\', \'stddev\', \'dtype\', \'name\'], varargs=None, keywords=None, defaults=[\'0.0\', \'1.0\', \"<dtype: \'float32\'>\", \'None\'], "
+   }
+   member_method {
+     name: "stateless_truncated_normal"
+     argspec: "args=[\'shape\', \'seed\', \'mean\', \'stddev\', \'dtype\', \'name\'], varargs=None, keywords=None, defaults=[\'0.0\', \'1.0\', \"<dtype: \'float32\'>\", \'None\'], "
+   }
+   member_method {
+     name: "stateless_uniform"
+     argspec: "args=[\'shape\', \'seed\', \'minval\', \'maxval\', \'dtype\', \'name\'], varargs=None, keywords=None, defaults=[\'0\', \'None\', \"<dtype: \'float32\'>\", \'None\'], "
+   }
+   member_method {
      name: "truncated_normal"
      argspec: "args=[\'shape\', \'mean\', \'stddev\', \'dtype\', \'seed\', \'name\'], varargs=None, keywords=None, defaults=[\'0.0\', \'1.0\', \"<dtype: \'float32\'>\", \'None\', \'None\'], "
    }
    member_method {
      name: "uniform"
      argspec: "args=[\'shape\', \'minval\', \'maxval\', \'dtype\', \'seed\', \'name\'], varargs=None, keywords=None, defaults=[\'0\', \'None\', \"<dtype: \'float32\'>\", \'None\', \'None\'], "
    }
    member_method {
      name: "uniform_candidate_sampler"
      argspec: "args=[\'true_classes\', \'num_true\', \'num_sampled\', \'unique\', \'range_max\', \'seed\', \'name\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
    }
  }
```

**Comment by girving** [comment]
@drpngx I applied your patch to what are hopefully the correct files:

```
 tensorflow/tools/api/golden/v1/tensorflow.random.pbtxt          |  16 +++
 tensorflow/tools/api/golden/v2/tensorflow.random.pbtxt          |  16 +++
```

**Comment by annarev** [comment]
@girving and @martinwicke api_compatibility_test still doesn't work with Python 3. I tried to run it with Python 3. It has a lot of differences and I didn't get a chance to go through all of them yet. sorry about the trouble!

**Comment by girving** [comment]
Thanks all!  That was substantially smoother than last time.

@hawkinsp I don't think I'll have time to do the related TPU changes, so I'll leave that part to someone else.  Specifically that means (1) turn on and test `bfloat16` and (2) implement the integer case of `tf.random.stateless_uniform`.

**Pull request merged**
