### PR TITLE
fixed link to tutorial and some typos

### PR DESCRIPTION
**Pull request by kashif**

### CODE REVIEW

**Comment by mnemonicflow** [comment]
Please note that according to the [README](https://github.com/tensorflow/tensorflow#tensorflow):
```
Note: Currently we do **not** accept pull requests on github -- see CONTRIBUTING.md for information on how to contribute code changes to TensorFlow through tensorflow.googlesource.com

We use github issues for tracking requests and bugs, but please see Community for general questions and discussion.```

**Comment by kashif** [comment]
@mnemonicflow ok cool done, closing this pull request.

**Comment by kashif** [comment]
@mnemonicflow can you kindly have a look at:

https://tensorflow-review.googlesource.com/#/c/1081/

thanks!

**Comment by kashif** [comment]
@vrv can you kindly have a look at:

https://tensorflow-review.googlesource.com/#/c/1081/

thanks!

**Pull request closed without merging**
