### PR TITLE
TFTRT: Prevent segments with partially defined inputs for static mode

### PR DESCRIPTION
**Pull request by trevor-m**
In static mode, If an input to a segment does not have a fully defined shape (exlcuding batch dim), we should prevent that segment from converting and fall back to native TF. TensorRT requires shapes to be defined in static mode. In some cases we would've caught the undefined shape by checks in certain ops but it was not reliable and the undefined shapes manifested in weird error messages.

### CODE REVIEW

**Comment by trevor-m** [comment]
I'm still not entirely sure about this. Do we expect partially defined input shapes to work in static mode?

**Review by smit-hinsu — APPROVED** [review]
Thanks, Trevor!

**Comment by smit-hinsu** [comment]
> I'm still not entirely sure about this. Do we expect partially defined input shapes to work in static mode?

I am not sure about that as well. Adding Lambda for that. I could not figure that out by quick read of the code.

I remember a discussion about the bucketing logic but not sure if that is already done and if that is part of TRTStatic orTRTDynamic.

**Comment by pooyadavoodi** [comment]
I don't think unknown shapes can work with static mode because the static mode requires building the TRT engine which includes all the optimizations that depend on shapes. But this requirement is for the inputs of the TRT engine, and not necessarily for the inputs of the whole graph; in other words, it's possible that there are unknown shapes in the graph inputs but not in the TRT engine inputs. I think Trevor's change checks the shape of TRT engine inputs which is the right thing.

**Pull request merged**
