### PR TITLE
Lite: Add Op Refatcored

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
1:> Optimized Macro usage to reduce code duplication.
2:> Unnecessary Template usage removed.
3:> Wrong error message corrected.

### CODE REVIEW

**Comment by karimnosseir** [comment]
Added Jared to have a look. My only comment is that the old version is more consistent with other kernels. Any specific reason to change it

Thanks

**Comment by jdduke** [comment]
Yeah, this code is actually slightly less readable IMO. The EvalAddQuantized changes look fine though.

**Comment by ANSHUMAN87** [comment]
@jdduke , @karimnosseir : Thanks for your valuable opinions. The reason being for this change is to reduce the duplicate codes, which i feel is acceptable, as the readability is not drastically reduced, Thanks!

Waiting for your PoV!

**Comment by ANSHUMAN87** [comment]
@jdduke : Improved the readability, please check, Thanks!

**Comment by jdduke** [comment]
Hmm, now the float path is inconsistent with the quantized path. I think for now it's best for us to just sit on this change, we may be doing a broader refactoring of kernels and we're trying to minimize churn.

**Pull request closed without merging**
