### PR TITLE
Added GPU implementation for resize nearest neighbor grad.

### PR DESCRIPTION
**Pull request by panmari**
And also adapted/added appropriate tests.

### CODE REVIEW

**Comment by panmari** [comment]
I needed to adapt the test so they use `np.float` instead of `np.float32`, e. g. [here](https://github.com/tensorflow/tensorflow/pull/1393/files#diff-bb1fdb8f5be7a85b4505589762579bf7R31). Isn't that a bit concerning? Shouldn't these types be equivalent? Or at least the op fall back to CPU if it's not supported on the GPU?

**Comment by martinwicke** [comment]
np.float is an alias for float64, not float32. Surprised me too. http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html

**Comment by panmari** [comment]
Oh, that's bad news. That means the tests are not using the new written kernel, but are falling back to the CPU version. I'll have to look into that and add a [WIP] for the time being.

**Comment by panmari** [comment]
@martinwicke I fixed the PR and tests. Could you take another look at this? I also added the kernel for `SetZero` from `maxpooling_op_gpu.cu.cc` to `tensorflow/core/util/cuda_kernel_helper.h` and consequently removed some duplicated code there after including `cuda_kernel_helper.h`.

**Comment by martinwicke** [comment]
Thanks for moving SetZero, that's good. Can you add a blank line after it? Otherwise looks good to me. You can amend your last commit with that, then I'll merge.

**Comment by panmari** [comment]
Done.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
Jenkins, test this please

**Pull request merged**
