### PR TITLE
get data ranges for missing types

### PR DESCRIPTION
**Pull request by chenfeiyue-cfy**
Hi,I 'm learning how to generate random data in tflite benchmark.However,I met this confusing code , and it doesn't seem to include datatype of int32 or uint32 and so on , I guess maybe the code should be like this ？If not, could you complete the range setting for Int32  and Uint32? It 's really important to me, thanks!

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @alankelly Can you please review this PR ? Thank you!

**Review by alankelly — APPROVED** [review]

**Comment by alankelly** [comment]
Thanks for spotting this, this is definitely a bug. Since this is only used for benchmarking, it doesn't impact correctness but should nevertheless be fixed

**Pull request merged**
