### PR TITLE
TF device_test additional test cases covers

### PR DESCRIPTION
**Pull request by Dayananda-V**
1- merge_device api test case

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for adding the test cases!

**Comment by penpornk** [comment]
@Dayananda-V This failed a test in eager mode. Could you please help take a look? Thank you!
Test name:  //tensorflow/python:framework_device_test
Error log:
```
Traceback (most recent call last):
  File "tensorflow/python/framework/device_test.py", line 121, in testMerge
    with ops.device(device.merge_device("/device:GPU:0")):
  File "tensorflow/python/framework/ops.py", line 5074, in device
    "tf.device does not support functions when eager execution "
RuntimeError: tf.device does not support functions when eager execution is enabled.
```

**Review by penpornk — CHANGES_REQUESTED** [review]
@Dayananda-V This failed a test in eager mode. Could you please help take a look? Thank you!
Test name:  //tensorflow/python:framework_device_test
Error log:
```
Traceback (most recent call last):
  File "tensorflow/python/framework/device_test.py", line 121, in testMerge
    with ops.device(device.merge_device("/device:GPU:0")):
  File "tensorflow/python/framework/ops.py", line 5074, in device
    "tf.device does not support functions when eager execution "
RuntimeError: tf.device does not support functions when eager execution is enabled.
```

**Comment by Dayananda-V** [comment]
@penpornk 

Eager mode execution test check added to validate merge_device test case. Thanks

**Review by penpornk — APPROVED** [review]
Thank you!

**Pull request merged**
