### PR TITLE
del wav_to_features.py

### PR DESCRIPTION
**Pull request by fix27**
delete wav_to_features.py

### CODE REVIEW

**Review by penpornk — COMMENTED** [review]
Could you please explain why the file should be deleted?

**Comment by hgadig** [comment]
> Could you please explain why the file should be deleted?

@fix27  Could you please give an explanation.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by fix27** [comment]
Hello you wrote the Ecologist - Engineer the information processing system Surgu Pozdnyakov Konstantin Nikolayevich. Help the solution of ecological problems with the help of tensorflow. 
For example, teach tensorflow to find and report negative impacts of human activities on the environment. Thanks.

**Review by penpornk — COMMENTED** [review]
I don't understand your response and  I think you are a bot (or at least your message is generated). :)
Since the response doesn't answer my original question, I'm going to reapply the label `stalled`.

**Comment by tensorflowbutler** [comment]
It has been 28 days that this pull-request has stalled. Please create a new pull-request with the requested changes.

**Pull request closed without merging**
