### PR TITLE
Improve the tf.repeat implementation

### LINKED ISSUE #50712: tf.repeat memory consumption and performance
Windows 10
TF 2.5.0
Python 3.8
CUDA 11.2
RTX 3060 6 GB

tf.repeat consumes much more memory with axis=0 in comparison if I create the same array with tf.gather.

```
D = 4000
a = tf.ones((D, 20))
Ns = tf.repeat([1000], D)
b = tf.repeat(a, Ns, axis=0)
tf.config.experimental.get_memory_info('GPU:0')
# {'current': 320337920, 'peak': 676338176}
```

```
D = 4000
a = tf.ones((D, 20))
Ns = tf.repeat([1000], D)
Ns_r = tf.range(0, D, dtype=tf.int64)
Ns_r = tf.repeat(Ns_r, Ns)
c = tf.gather(a, Ns_r, axis=0)
tf.config.experimental.get_memory_info('GPU:0')
# {'current': 352337920, 'peak': 352337920}
```

Also my code ( I might share it, but is quite huge) runs 58 sec when I use tf.gather on each iteration and 73 sec when I use repeat, that is a bit strange (as tf.repeat is just a particular case of gather in this case). 
When I add creration of Ns_r on each it too, the time is same, but I do not consider tf.gather as optimal - the elements are ordered and just repeated, while gather does not use this assumption

### PR DESCRIPTION
**Pull request by benbarsdell**
- Replaces the old implementation with a simpler algorithm that is significantly more memory and compute efficient.
- Fixes https://github.com/tensorflow/tensorflow/issues/50712
- **Requires https://github.com/tensorflow/tensorflow/pull/52543 to be merged first to avoid performance regression.**

cc @nluehr

### CODE REVIEW

**Comment by benbarsdell** [comment]
I've added benchmarks and also fixed another performance issue I discovered (removed a forced cast to int32; it took me a few goes to keep all the tests passing).

These are the benchmark results I get on a Titan V GPU (this is including PR 52543):
```
                                                   Old Time  New Time  Speedup factor
RepeatBenchmark.benchmark_repeat_few_1d	           0.007645  0.000686  11.1
RepeatBenchmark.benchmark_repeat_few_2d_axis0      0.000606  0.000277   2.2
RepeatBenchmark.benchmark_repeat_few_2d_axis1      0.007869  0.000434  18.2
RepeatBenchmark.benchmark_repeat_many_1d           0.005879  0.000599   9.8
RepeatBenchmark.benchmark_repeat_many_2d_axis0     0.000329  0.000282   1.2
RepeatBenchmark.benchmark_repeat_many_2d_axis0_big 0.001637  0.000439   3.7
RepeatBenchmark.benchmark_repeat_many_2d_axis1     0.005514  0.000462  11.9
```

**Comment by benbarsdell** [comment]
https://github.com/tensorflow/tensorflow/pull/52543 is merged now (after a roll-back and roll-forward), so this PR is good to go.

**Review by sanjoy — APPROVED** [review]

**Comment by bgdax** [comment]
We're looking into a performance regression in the benchmarks for the 1D case on CPU.

**Comment by bgdax** [comment]
Hi Ben,

Thank you for the contribution, this will help fix a number of issues around tf.repeat.

I was able to observe similar improvements in performance as what you reported for GPU.
However, I ran into a couple of performance regressions on CPU (via building without CUDA support) for the 1D case.

|  | Old time | New time |
|----------------------------|----------|-----------|
| benchmark_repeat_few_1d | 0.029 | 0.211|
|benchmark_repeat_many_1d | 0.019 | 0.086 |

Profiling shows that most of the time is spent in the `upper_bound` that is invoked in `searchsorted`.

Can you please take a look into this when you get a chance?
Thank you!

**Comment by benbarsdell** [comment]
I've added a commit to add multithreading to the searchsorted CPU kernels, but I'll probably have to revisit this in the new year.

**Comment by gbaned** [comment]
@bgdax Can you please review this PR ? Thanks!

**Comment by bgdax** [comment]
The PR is in internal review. We're also investigating the remaining internal tests that are broken.

**Pull request merged**
