### PR TITLE
Add cuda 11.2 driver and runtime inc files

### PR DESCRIPTION
**Pull request by nluehr**
CC @sanjoy

### CODE REVIEW

**Review by sanjoy — APPROVED** [review]

**Comment by nluehr** [comment]
The test failure looks unrelated to the changed made in the PR.

**Comment by byronyi** [comment]
TF/xla with CUDA 11.2 gives the following warning:

``warning: Linking two modules of different target triples: '/usr/local/cuda-11.2/nvvm/libdevice/libdevice.10.bc' is 'nvptx64-nvidia-gpulibs' whereas '' is 'nvptx64-nvidia-cuda'``

cc @jpienaar @timshen91

**Comment by sanjoy** [comment]
@byronyi We have not yet fully tested TF with 11.2 so some failures are expected.  Having said that, that particular issue is probably a false positive, we should not print this warning.  We can either remove the diagnostic printer while linking (it is created and added [here](https://github.com/tensorflow/tensorflow/blob/b444969f2a8101a7add09c71f917196714bf1629/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc#L806)), or change the printer to filter out just the [linker diagnostics](https://github.com/llvm/llvm-project/blob/d75b3719828f3e0c9736476e50a08e5083f90c0b/llvm/include/llvm/IR/DiagnosticInfo.h#L59).

**Comment by byronyi** [comment]
@sanjoy Except this particular warning, the CUDA 11.2 build seems pretty fine for the model garden RN50.

**Pull request merged**
