### PR TITLE
Add globs from Lambda before building it

### PR DESCRIPTION
**Pull request by Dref360**
The globals required to build the Lambda weren't loaded correctly. This leads to many problems when cloning a Model.

I'm not sure how to handle collisions. 

This PR allows us to avoid using lambda with an inner import.

Small note: the latter one is more efficient and does the same thing.
```python
globs = dict(list(globs.items()) + list(custom_objects.items()))
globs.update(custom_objects)
```

### CODE REVIEW

**Comment by Dref360** [comment]
@fchollet this is a PR for what I talked to you about.

**Review by fchollet — DISMISSED** [review]
Thanks for the PR. LGTM

**Review by fchollet — DISMISSED** [review]
LGTM

**Review by fchollet — APPROVED** [review]
LGTM

**Comment by fchollet** [comment]
@ekelsen please merge after the checks have run. Thanks!

**Pull request merged**
