### PR TITLE
Include any windows

### PR DESCRIPTION
**Pull request by turgut-baba**
As the commit message mentions, when trying to build tensorflow lite with `-DTFLITE_ENABLE_GPU=ON` on windows to get the dll/lib files the `cmake --build . -j ` causes the following error: 'any_cast is not a member of std' on r2.14 branch. After making sure my c++ version is indeed above 17, I figured that `operation_selector.cc` and `conv_pointwise.cc` does not include `#include <any>` to use those functions. So I just added them next to other includes.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @turgut-baba Can you please sign CLA. Thank you!

**Comment by gbaned** [comment]
@turgut-baba Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
@turgut-baba Can you please resolve conflicts? Thank you!

**Comment by mihaimaruseac** [comment]
You definitely need to rebase this, it has too many commits

**Comment by mihaimaruseac** [comment]
I think you only want [ded506a](https://github.com/tensorflow/tensorflow/pull/61718/commits/ded506a043abab7a5c37c8cf1636eab2eb25d517), but you started this on the `r2.14` branch while targeting master. You need to start from `master` branch

**Comment by gbaned** [comment]
Hi @turgut-baba Any update of this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @turgut-baba Any update of this PR? Please. Thank you!

**Comment by mihaimaruseac** [comment]
We should close this PR and reopen only with the commit that is needed

**Comment by mihaimaruseac** [comment]
In this case, closing the PR.

Please open it again with the conflicts resolved if you want to contribute the changes upstream.

**Pull request closed without merging**
