### PR TITLE
Fixes issue #26276 - Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by F20170604**
Fixes issue #26276

### CODE REVIEW

**Comment by Ayush517** [comment]
@dynamicwebpaige Can you please review this 🙂

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @dynamicwebpaige: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 16 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @dynamicwebpaige: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @dynamicwebpaige: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @dynamicwebpaige, @yifeif: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Review by yifeif — APPROVED** [review]

**Pull request merged**
