### PR TITLE
Add return_index_map argument in ssim()

### LINKED ISSUE #53115: SSIM index maps
**System information**
- TensorFlow version (you are using): 2.7
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently tf.image.ssim() returns a global ssim value but it would be useful to have it return a non globally averaged value as per 
e.g. https://uk.mathworks.com/help/images/ref/ssim.html that would allow the making of ssim index maps

**Will this change the current api? How?**
-

**Who will benefit with this feature?**
anyone doing computer vision

**Any Other info.**

### PR DESCRIPTION
**Pull request by CohenAriel**
Closes #53115

### CODE REVIEW

**Review by SeeForTwo — APPROVED** [review]

**Comment by gbaned** [comment]
Here are the internal errors, @CohenAriel can you please verify ?  Thank you!

Traceback (most recent call last):
  File "/tensorflow/python/ops/image_ops_test.py", line 5801, in testWithIndexMap
    self.assertAllEqual(ssim_global, math_ops.reduce_mean(ssim_locals, axes))
  File "/tensorflow/python/framework/test_util.py", line 1571, in decorated
    return f(*args, **kwds)
  File "/tensorflow/python/framework/test_util.py", line 3292, in assertAllEqual
    np.testing.assert_array_equal(a, b, err_msg="\n".join(msgs))
  File "/py/numpy/testing/_private/utils.py", line 934, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/py/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

not equal where = (array([0]),)
not equal lhs = array([0.06525472], dtype=float32)
not equal rhs = array([0.06525473], dtype=float32)
Mismatched elements: 1 / 1 (100%)
Max absolute difference: 7.450581e-09
Max relative difference: 1.1417688e-07
 x: array([0.065255], dtype=float32)
 y: array([0.065255], dtype=float32)

**Comment by CohenAriel** [comment]
Weird. Am I running the wrong command?
```
bazel test -k tensorflow/python:image_ops_test --test_filter=*SSIMTest.testWithIndexMap*
```
resulted in
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=191
INFO: Reading rc options for 'test' from /home/ariel/Projects/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'test' from /home/ariel/Projects/tensorflow/.bazelrc:
  Inherited 'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /home/ariel/Projects/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/ariel/Projects/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/ariel/Projects/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/ariel/Projects/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 test targets...
INFO: Elapsed time: 8.992s, Critical Path: 1.66s
INFO: 33 processes: 1 internal, 32 local.
INFO: Build completed successfully, 33 total actions
//tensorflow/python:image_ops_test_cpu                                   PASSED in 1.7s
  Stats over 16 runs: max = 1.7s, min = 1.2s, avg = 1.5s, dev = 0.1s
//tensorflow/python:image_ops_test_gpu                                   PASSED in 1.7s
  Stats over 16 runs: max = 1.7s, min = 1.3s, avg = 1.5s, dev = 0.1s

Executed 2 out of 2 tests: 2 tests pass.
INFO: Build completed successfully, 33 total actions
```

**Comment by gbaned** [comment]
Hi @SeeForTwo Can you please assist on above comments from @CohenAriel. Thank you!

**Comment by SeeForTwo** [comment]
When @gbaned ran the test, there appeared to be a trivial floating point rounding difference:

> not equal lhs = array([0.06525472], dtype=float32)
> not equal rhs = array([0.06525473], dtype=float32)
> sMax absolute difference: 7.450581e-09
> Max relative difference: 1.1417688e-07

If you agree that this is just a rounding issue (how rounding occurs on different computers), I would suggest changing the test to use `self.assertAllClose(ssim_global, math_ops.reduce_mean(ssim_locals, axes))` instead of `self.assertAllEqual(ssim_global, math_ops.reduce_mean(ssim_locals, axes))`. The default tolerances for "close" are 1e-6. (In general, I favor using assertAllClose over assertAllEqual when comparing floats.)

**Comment by CohenAriel** [comment]
Makes sense. I'll try that.

**Review by SeeForTwo — APPROVED** [review]

**Comment by rohan100jain** [comment]
@tensorflow/api-owners

**Comment by SeeForTwo** [comment]
@CohenAriel, because adding this optional argument changes the public API, "the goldens" need to be updated.

Can you please try running:

```
bazel run tensorflow/tools/api/tests:api_compatibility_test  -- --update_goldens True
```

See "Py+XPP Test Suite - Ubuntu CPU, Python 3.9.." [Details](https://storage.cloud.google.com/tensorflow-nightly/prod/tensorflow/rel/docker/github_presubmit/pycpp_cpu_py39/1211/20220804-103104/index.html) --> [Details](https://storage.cloud.google.com/tensorflow-nightly/prod/tensorflow/rel/docker/github_presubmit/pycpp_cpu_py39/1211/20220804-103104/index.html) and search for "If this test fails, it means a change has been made to the public API" in the log.

**Comment by SeeForTwo** [comment]
After running that command, commit the changes that it (hopefully) creates.

**Review by SeeForTwo — APPROVED** [review]

**Review by rohan100jain — APPROVED** [review]

**Comment by SeeForTwo** [comment]
For `feedback/copybara — Google internal checks FAILED` (i.e. since this is a public API change) could you please add a short summary of this change to [RELEASE.md](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md). My suggestion is in `# Bug Fixes and Other Changes` to add something like the following:

```
*   `tf.image`
    *   Added an optional parameter `return_index_map` to `tf.image.ssim` which
        causes the returned value to be the local SSIM map instead of the
        global mean.
```

Thank you for your patience!

**Comment by CohenAriel** [comment]
No problem. I hope it's fine now.

**Review by SeeForTwo — APPROVED** [review]

**Pull request closed without merging**
