### PR TITLE
[Bazel/MSVC] Enable jpeg SIMD for MSVC

### PR DESCRIPTION
**Pull request by rongjiecomputer**

### CODE REVIEW

**Review by meteorcloudy — DISMISSED** [review]
Great, thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by meteorcloudy — DISMISSED** [review]

**Comment by gunan** [comment]
I cannot tell how, but the failures look legit.
This is what we see on windows:
```
ERROR: T:/tmp/bigvaudl/external/nasm/BUILD.bazel:8:1: undeclared inclusion(s) in rule '@nasm//:nasm':
this rule is missing dependency declarations for the following files included by 'external/nasm/stdlib/strlcpy.c':
  'external/nasm/config/msvc.h'
```
@rongjiecomputer could you conditionally add msvc.h  to this list, maybe what will fix it?
https://github.com/tensorflow/tensorflow/blob/master/third_party/nasm.BUILD#L45
I think with the new headers, somehow different code paths are activated in nasm by some macros.

**Comment by rongjiecomputer** [comment]
@gunan https://github.com/tensorflow/tensorflow/pull/20537/commits/f22edf35083dff5f54636fab2ecac3672a3d2d7d should fix the build error for nasm. Please trigger CI build again.

**Comment by rongjiecomputer** [comment]
#21993 is going to break this PR again. Can we get this or that PR merged soon?

**Comment by perfinion** [comment]
@rongjiecomputer the update to 2.0.0 needs to go in quickly cuz it fixes some CVEs in the current version. That version passes all the tests but I don't really know how to do the SIMD stuff on windows. It looks like 2.0.0 adds quite a bit of support tho so ideally could you rebase this on top of the 2.0.0 one to enable the windows SIMD stuff?

**Comment by rongjiecomputer** [comment]
@perfinion I will rebase and update this PR when your PR is merged. It is just that all my Windows PRs tend to drag very long before it gets imported for some reason. Having to keep updating PR due to newer changes breaking my PR is pretty frustrating.

**Comment by perfinion** [comment]
@rongjiecomputer yep I hear you. Ping me when it's rebased and I'll help push it through. Thanks for the patience :-)

**Comment by rongjiecomputer** [comment]
Can I get a CI test? Thanks!

**Comment by perfinion** [comment]
@rongjiecomputer Looks like some windows test failures. can you take a look?
Also can you squash those commits together when you update it? `git rebase -i origin/master` then change the pick to squash. The early commits are just confusing with the new 2.0 stuff so better have it all in one so there are no issues when merging in later.

**Comment by rongjiecomputer** [comment]
@perfinion Windows builds failed because symbols from `simd/x86_64/jsimd.c` was missing. Added them back.

I have squashed the commits as requested. I did not do it initially as I thought it will make it difficult for reviewer to see what I have changed since last review.

**Review by perfinion — APPROVED** [review]

**Review by gunan — APPROVED** [review]

**Pull request merged**
