### PR TITLE
Fix VarianceScaling initializer for warmstart

### PR DESCRIPTION
**Pull request by yunjiangster**
To replace https://github.com/tensorflow/tensorflow/pull/31648 which was incorrectly submitted for r1.14.

### CODE REVIEW

**Comment by yunjiangster** [comment]
How do I fix the cla/google check?

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by mihaimaruseac** [comment]
For old releases we are only accepting patches for security vulnerabilities, as they are the only ones that cause new (patch) releases to be made. As such, we cannot accept PRs which are not against master (and cherry-pick PRs against the main development branch for a new release).

Closing this PR accordingly.

**Comment by yunjiangster** [comment]
> For old releases we are only accepting patches for security vulnerabilities, as they are the only ones that cause new (patch) releases to be made. As such, we cannot accept PRs which are not against master (and cherry-pick PRs against the main development branch for a new release).
> 
> Closing this PR accordingly.

Same problem exists in r1.14. Care to make a similar patch?

**Comment by mihaimaruseac** [comment]
Unfortunately, since this PR is not a security vulnerability, it cannot go into r1.14 either.

Instead, this fix should be made against master, so it can be picked up on the future releases. As there is a branch cut for r2.0 (and soon r1.15), you might then decide to cherry-pick the PR against master to each of those two branches and the release owners can decide if they want the patch or not.

**Pull request closed without merging**
