### PR TITLE
fix typo inside and outside

### PR DESCRIPTION
**Pull request by mingting**

### CODE REVIEW

**Comment by gbaned** [comment]
@mingting  thank you for your contribution, please sign CLA.

**Comment by mingting** [comment]
@googlebot I signed it!

**Comment by mingting** [comment]
> ou for your contribution, please sign CLA.

thanks for your reply,  CLA done just now.

**Comment by cheshire** [comment]
Are you sure it's a typo? I think the text is intentional: xla.compile wants to have as much of the computation inside itself as possible, including the gradient computation.

**Comment by mingting** [comment]
> Are you sure it's a typo? I think the text is intentional: xla.compile wants to have as much of the computation inside itself as possible, including the gradient computation.
@cheshire  
from the context, gradient computation in xla.compile is prohibited. so I think to avoid performance drop,  suggest develop to move gradient computation outside of xla.compile, not inside.


Note: Gradient computation of graph in xla.compile() is prohibited because it can cause performance degradation. To avoid this issue, move gradient computation insideoutside xla.compile().

**Comment by cheshire** [comment]
I don't think it's a typo.

**Pull request closed without merging**
