### PR TITLE
Fix Ignite Dataset (V2 API)

### PR DESCRIPTION
**Pull request by dmitrievanthony**
Hi, @mrry, @yongtang.

During the update on Dataset V2 API `Ignite Dataset` has been broken (I guess nobody runs manual tests). The errors looks like that:

```
Traceback (most recent call last):
  File "ignite_dataset_test.py", line 47, in test_ignite_dataset_with_plain_client
    ds = IgniteDataset(cache_name="SQL_PUBLIC_TEST_CACHE", port=42300)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 318, in new_func
    return func(*args, **kwargs)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/ignite/python/ops/ignite_dataset_ops.py", line 738, in __init__
    super(IgniteDataset, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'variant_tensor'
```

The problem is that `DatasetSource` now requires `varient_tensor` to be passed into constructor. I guess fixed this problem.

PS: @yongtang, I found that Kafka currently has the same issue, so I fixed it too. Please have a look.

### CODE REVIEW

**Comment by yongtang** [comment]
The fix looks good to me. Thanks! I also created a PR #24903 for kinesis fix. In addition, we will need to carry the fix to tensorflow/io  (tensorflow/io#54) once we move from tensorflow 1.12 to tensorflow 1.13 (to be released soon).

**Review by yongtang — DISMISSED** [review]
LGTM

**Comment by dmitrievanthony** [comment]
@yongtang, as far as I understand 1.13 branch is about to be cut off. Let me mention that it's important to include this fix into the release.

**Comment by byronyi** [comment]
@dmitrievanthony It's cut off a month ago. @ewilderj Who should we speak to if we'd like to cherry-pick this to r1.13?

**Comment by dmitrievanthony** [comment]
Folks, it's not clear when this PR will be merged? I see that #24903 has already been merged, but not this one. Do we have some issues with it?

**Comment by ewilderj** [comment]
cc @aselle

**Comment by dmitrievanthony** [comment]
Guys, what about this PR? I guess it has to be merged and than cherry-picked into 1.13, but it looks like the process is stuck.

**Comment by jsimsa** [comment]
@ymodak what do you need me to do? the changes in this PR seems to be already a approved

**Comment by jsimsa** [comment]
This PR is failing internal presubmits with the following error:

```
HOURGLASS IMPORT DETECTED

'import tensorflow' statements are no longer allowed in the internal
TensorFlow codebase, with the exception of /examples/ and /g3doc/
directories. This is because they prevent Blaze and TAP from caching
anything.

Please import modules directly. Also please make sure your Python
BUILD rules depend on all the labels whose sources they import.
```

**Comment by dmitrievanthony** [comment]
Hi, @jsimsa. It's a bit strange restriction for tests, but okay, I've removed import of `tensorflow`. Please have a look.

**Review by jsimsa — APPROVED** [review]

**Comment by dmitrievanthony** [comment]
Thanks, @jsimsa, @aselle please don't forget to cherry-pick these changes into 1.13.

**Comment by dmitrievanthony** [comment]
Folks, @jsimsa, @aselle let me remind that it's important to push this fix into `1.13`. Do you have plans to do that soon?

**Comment by ewilderj** [comment]
I also sent an internal ping for this cherry pick.

**Comment by aselle** [comment]
This has been merged into r1.13 #25290

**Comment by dmitrievanthony** [comment]
Hi, @aselle, @ewilderj. I'm a bit embarrassed, but it looks like I have to ask to revert cherry pick. 

The reason for this fix is commit https://github.com/tensorflow/tensorflow/commit/9a63f5b8432f0057d5099e2aea0c8f57467c65db, but I realized that it wasn't included into 1.13. It's not included and so that the correspondent fix should not be included too. Unfortunately, for now we have broken 1.13.0rc1.

Is it possible to revert the cherry pick?

**Comment by ewilderj** [comment]
I've tagged this internally too, will await @aselle confirmation.

**Comment by dmitrievanthony** [comment]
Hi, @aselle. Any update?

**Comment by aselle** [comment]
This will not make RC2 but I will try to get it into final.
-A

**Comment by dmitrievanthony** [comment]
Him @aselle. It looks like RC2 still has this issue, have you tried to revert this cherry-pick in it? Anyway, I hope this will be node in final release.

**Pull request merged**
