### PR TITLE
Broadcast doc for ops in math_ops.cc

### PR DESCRIPTION
**Pull request by siddharth-agrawal**
Document broadcasting behavior for each binary elementwise operation, as discussed in #508.

### CODE REVIEW

**Comment by martinwicke** [comment]
I think there's a bunch of backticks missing, can you look at https://www.tensorflow.org/versions/r0.9/how_tos/documentation/index.html? Most of it is not relevant here, but the formatting for functions names should be consistent.

**Comment by siddharth-agrawal** [comment]
@martinwicke Are you referring to op names? I'm following the documentation [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/math_ops.cc#L470).

**Comment by xmbrst** [comment]
Yep, @martinwicke is referring to op names. BatchMatMul in [math_ops.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/math_ops.cc#L129) illustrates the right style: op names, class names, etc should be in backticks. It's true the style isn't applied completely consistently at the moment, but we should try to be consistent going forward.

**Comment by siddharth-agrawal** [comment]
Updated the PR.

**Comment by xmbrst** [comment]
Admins, this PR looks good to me.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Pull request merged**
