### PR TITLE
update dataset_ops.py

### PR DESCRIPTION
**Pull request by NeerajBhadani**
Code consistency

### CODE REVIEW

**Review by aaudiber — DISMISSED** [review]

**Comment by gbaned** [comment]
@NeerajBhadani Can you please check build failures. Thanks!

**Comment by aaudiber** [comment]
@NeerajBhadani It appears that the line is now too long, can you shorten the example or wrap the line?

>FAIL: Found 1 non-whitelisted pylint errors:
tensorflow/python/data/ops/dataset_ops.py:1659: [C0301(line-too-long), ] Line too long (87/80)

**Comment by NeerajBhadani** [comment]
> @NeerajBhadani It appears that the line is now too long, can you shorten the example or wrap the line?
> 
> > FAIL: Found 1 non-whitelisted pylint errors:
> > tensorflow/python/data/ops/dataset_ops.py:1659: [C0301(line-too-long), ] Line too long (87/80)

Thanks @aaudiber I have made the necessary changes. Let me know if anything else is required from my side.

Regards,
Neeraj

**Review by aaudiber — DISMISSED** [review]

**Comment by NeerajBhadani** [comment]
@aaudiber I have added the paratheses in order to avoid the syntax error. However, I have checked the code locally and it was working without parentheses as well.

**Review by aaudiber — DISMISSED** [review]

**Comment by NeerajBhadani** [comment]
@aaudiber I have checked the code locally and it seems to be working fine but here some of the test cases are failing with multiline code. Could you please help here.

**Comment by aaudiber** [comment]
@NeerajBhadani sorry I didn't notice this at first - multi-line doctest statements require "..." on the continuation line, see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py#L612-L614 for example

**Review by aaudiber — APPROVED** [review]

**Pull request merged**
