### PR TITLE
[oneDNN] QuantizeV2 with bfloat16 Input

### PR DESCRIPTION
**Pull request by mdfaijul**
Depends on #56776
This PR extends QuantizeV2 op for converting bfloat16 tensor to quantized tensor. It helps quantizing a model with bfloat16 and 8-bit integer mixed precisions, for example using Intel Neural Compressor (INC) tool (https://github.com/intel/neural-compressor).

### CODE REVIEW

**Comment by mdfaijul** [comment]
@jpienaar Any update on this PR?

**Comment by jpienaar** [comment]
> @jpienaar Any update on this PR?

I'm not actively looking at this one/outside my area. @penpornk is the best positioned.

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @mdfaijul Can you please rebase your branch and resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by mihaimaruseac** [comment]
Closing stale PR

**Pull request closed without merging**
