### PR TITLE
Fix hip-clang build

### PR DESCRIPTION
**Pull request by darkbuck**
- Add clang 11.0 support.

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
@whchung @sunway513

**Comment by whchung** [comment]
@darkbuck thanks for submitting this. please sign individual CLA.

**Review by whchung — APPROVED** [review]
LGTM

**Comment by darkbuck** [comment]
@googlebot I signed it!

**Comment by whchung** [comment]
@chsigg may I ask for your help to expedite the merge of this PR? we are testing new toolchain with tip of TensorFlow + LLVM + Clang and this is breaking our CI.

**Review by chsigg — APPROVED** [review]

**Pull request merged**
