### PR TITLE
Adding meta_graph_be.pb testdata for big endian for framework_meta_graph_test

### PR DESCRIPTION
**Pull request by namrata-ibm**

### CODE REVIEW

**Comment by namrata-ibm** [comment]
@drpngx, Could you please help with this?

**Comment by drpngx** [comment]
How big is the metagraph? Is there a doc on how to generate it?

**Comment by namrata-ibm** [comment]
@drpngx, I have created the `metrics_export_meta_graph_be.pb` from the original [metrics_export_meta_graph.pb](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/testdata/metrics_export_meta_graph.pb) itself. There is only 1 change in [tensor_content](https://github.com/linux-on-ibm-z/tensorflow/blob/67bc8fc36f74ea57e0477e84e99ec024c716fce4/tensorflow/python/framework/testdata/metrics_export_meta_graph_be.pb#L1161) where data is swapped as below for int32 dtype(with size 2):
```
original: tensor_content: "\000\000\000\000\001\000\000\000"
BE:       tensor_content: "\000\000\000\000\000\000\000\001"
```
With this change, the test `//tensorflow/python:framework_meta_graph_test` passes on big endian, which earlier was failing with error: 
`ValueError: Invalid reduction dimension 16777216 for input with 2 dimensions. for 'mean/Sum' (op: 'Sum') with input shapes: [1,2], [2] and with computed input tensors: input[1] = <0 16777216>.
`

Since the original file contains 1559 lines, added a new file for big endian and referenced it in test. Is there some other way to handle this failure?

**Comment by drpngx** [comment]
I see. I think the "right" way is to standardize the metagraph to be small endian and do the conversion on load. We have the dtypes for that. Do you want to submit a PR for that?

**Comment by namrata-ibm** [comment]
@drpngx, Thank you for your feedback. I will have a look at how to carry out conversion on load. It would be helpful if you could give me some pointers about the location where the endian conversion might be needed to achieve uniformity while reading test data.

**Comment by drpngx** [comment]
You can trace the load through [here](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.cc#L220), probably.

**Comment by rmlarsen** [comment]
Indeed, the stored format should be platform independent.

**Comment by rmlarsen** [comment]
I think we should close this PR and open an issue for standardizing the saved format and/or converting to big-endian on read when needed.

**Pull request closed without merging**
