### PR TITLE
Copy the Keras config file handling from master into the 1.1 release

### PR DESCRIPTION
**Pull request by jhseu**
Fix for Cloud ML to use 1.1

### CODE REVIEW

**Comment by jhseu** [comment]
Current code only handles EEXIST, and doesn't handle unwritable directories.

**Review by fchollet — APPROVED** [review]

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by av8ramit** [comment]
Flake android build.

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Review by av8ramit — APPROVED** [review]

**Pull request merged**
