### PR TITLE
[Intel MKL] Enable Mac build on MKL

### PR DESCRIPTION
**Pull request by claynerobison**

### CODE REVIEW

**Comment by opencici2006** [comment]
duplicated PR with https://github.com/tensorflow/tensorflow/pull/18726
so closed this PR.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
I was able to verify that MKL build now works on macos. Should we close this PR?

**Comment by claynerobison** [comment]
@opencici2006 Closing per Gunhan's suggestion.

**Pull request closed without merging**
