### PR TITLE
Add gitpod config

### PR DESCRIPTION
**Pull request by DZERK17**
this commit adds support for Gitpod.io, a free automated
dev environment that makes contributing and generally working on GitHub
projects much easier. It allows anyone to start a ready-to-code dev
environment for any branch, issue and pull request with a single click.

### CODE REVIEW

**Comment by gbaned** [comment]
@DZERK17 Can you please check build failures. Thanks!

**Comment by gbaned** [comment]
@DZERK17 Can you please sign CLA? Thanks!

**Comment by bhack** [comment]
I don't know it will be so much useful cause the `bazel` cache it is not available in the container [since 2016](https://github.com/tensorflow/tensorflow/commit/8a724211a9d4871338afe874276abf1d358f799b)
All the bazel cache for the Docker image builds currently are "internal" and remote. 
So in the current status will be hard to have a quite ready dev container for quickly online editing and run change. 
The build require many hours without an available cache.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
