### PR TITLE
cherrypicks for test and builds fixes for TF 2.0 alpha0

### PR DESCRIPTION
**Pull request by goldiegadde**

### CODE REVIEW

**Comment by martinwicke** [comment]
Just the backwards compatible test. Is the new file in?

**Comment by goldiegadde** [comment]
> Just the backwards compatible test. Is the new file in?

yes that is in the list of cherrypicks

**Comment by martinwicke** [comment]
Ubuntu CC is still failing with the old "file not found": https://source.cloud.google.com/results/invocations/2a2317c2-2a38-4851-b9ec-fa695e0b5f9f/targets/%2F%2Ftensorflow%2Fcore%2Fops%2Fcompat:backwards_compatibility_test/tests

**Comment by goldiegadde** [comment]
> Ubuntu CC is still failing with the old "file not found": https://source.cloud.google.com/results/invocations/2a2317c2-2a38-4851-b9ec-fa695e0b5f9f/targets/%2F%2Ftensorflow%2Fcore%2Fops%2Fcompat:backwards_compatibility_test/tests

added the build file dependancy

**Pull request closed without merging**
