### PR TITLE
replace xrange with range for python3 compatibility

### PR DESCRIPTION
**Pull request by yjmade**

### CODE REVIEW

**Comment by girving** [comment]
Thanks!  Jenkins, test this please.

**Comment by girving** [comment]
The failure looks like a flaky test on our end.  Investigation.

**Comment by girving** [comment]
Jenkins, test this please.

**Comment by girving** [comment]
@keveman: Do you know might be causing this protobuf pip test failure?

**Comment by girving** [comment]
@vrv apparently knows the issue.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please  (PLEASE)

**Pull request merged**
