### PR TITLE
Branch 199809082

### PR DESCRIPTION
**Pull request by drpngx**

### CODE REVIEW

**Review by yifeif — DISMISSED** [review]

**Comment by drpngx** [comment]
Fails:
```
//tensorflow/compiler/xla/tests:convolution_test_gpu
//tensorflow/compiler/xla/tests:convolution_test_gpu_alternative_layout_gpu
```
And
`//tensorflow/contrib/data/python/kernel_tests:optimize_dataset_op_test` (timeout - flakey)

**Comment by yifeif** [comment]
Looks like the XLA failure was fixed in cl/199814523.

**Comment by drpngx** [comment]
All passed.

**Comment by drpngx** [comment]
Could I get another approval?

**Comment by akshayka** [comment]
Re: py_func_test.py:testCleanup, I believe the LHS of the diff (i.e,. the implementation that calls gc.collect()) is more recent than the RHS --- it was added in https://github.com/tensorflow/tensorflow/pull/19085. We probably shouldn't revert it --- does that test no longer pass?

Besides that function, LGTM.

**Comment by drpngx** [comment]
oh, ok, I got confused in the merge. Thanks!

**Comment by caisq** [comment]
Closing stale push PR.

**Pull request closed without merging**
