### PR TITLE
Fix for Issue 9103, serialization issue with tf.Placeholder

### PR DESCRIPTION
**Pull request by figmentc**
Removed restriction on Placeholder to have fully defined dimensions. Partially defined dimensions now accepted. Allows Placeholders to now be fully serialized under Protobuf.

### CODE REVIEW

**Comment by karpkarp** [comment]
I signed it

**Comment by drpngx** [comment]
@cwhipkey does that look right?

@karpkarp could you make sure you are pushing with the same email as the one you used for CLA?

**Comment by asimshankar** [comment]
@vrv is working on a more comprehensive fix (that also enables distinguishing between truly unknown and scalar shapes), so I'd be tempted to hold off on this at least until @vrv chimes in.

**Comment by vrv** [comment]
I already submitted a fix internally that should fix the problem -- hopefully with the next push it'll all just work?

**Comment by drpngx** [comment]
Pushed commits which include: https://github.com/tensorflow/tensorflow/pull/9143/commits/6461dd322be3a74f0c20b62a8136bc0d8d8c1bb8 and https://github.com/tensorflow/tensorflow/pull/9143/commits/24a95ae389e1c76e771ac33d66e0ec40a236260f

Please pull and check if that worked for you.

**Comment by drpngx** [comment]
Assuming this has been resolved. Feel free to reopen.

**Pull request closed without merging**
