### PR TITLE
Provides example for tf.argsort and tf.sort

### PR DESCRIPTION
**Pull request by F20170604**
Fixes issue #26533

### CODE REVIEW

**Review by mandroid6 — CHANGES_REQUESTED** [review]
Stick to 'Usage:', remove 'For example:'.

**Review by mandroid6 — CHANGES_REQUESTED** [review]
Works now

**Review by mandroid6 — APPROVED** [review]

**Comment by Ayush517** [comment]
So, any more changes or it's good now?

**Review by kyscg — APPROVED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

**Review by alextp — APPROVED** [review]
Thank you very much!

(optional) Can you also add these examples as unit tests in tensorflow/python/ops/sort_ops_test.py ?

**Pull request merged**
