### PR TITLE
Add BestSplits op to common windows installation problems.

### LINKED ISSUE #9273: [Docs] Update wheels URLs to match latest TensorFlow release (1.1.0)
The wheels available on the website are from the previous release (1.0.1) which still contain OpKernels errors that are solved at head (as well as on 1.1.0) and can be ignored but are confusing users prompting repeated reports of this issue.

### PR DESCRIPTION
**Pull request by yifeif**
Fix #9273

### CODE REVIEW

**Review by mrry — COMMENTED** [review]
This will cease to be a problem in r1.1 though, right?

**Comment by yifeif** [comment]
yea, only for 1.0.1 and its RCs.

**Comment by mrry** [comment]
Here's a link to the other FAQ (about SSE instructions): http://stackoverflow.com/q/43134753

**Comment by yifeif** [comment]
Added to the table as well!

**Review by mrry — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
