### PR TITLE
Disable ppc64le custom gemm_pack_rhs to use the convolution specialization

### PR DESCRIPTION
**Pull request by maxiwell**
Eigen ppc64le has a gemm_pack_rhs specialization for AltiVec architecture. TF Convolution also specializes this packing routine, improving the Tensor code and avoiding a lot of index computation. Based on eigen_benchmark_cpu_test, we found a good scenario for ppc64le, where gemm_pack_rhs from TF headers together with VSX/MMA from ppc64le speeds up the performance of convolution.

This patch fixes the column computation for convolution in case of ppc64le and disables the Eigen ppc64le gemm_pack_rhs using the define EIGEN_ALTIVEC_USE_CUSTOM_PACK=0.

### CODE REVIEW

**Comment by maxiwell** [comment]
Hi, the PR #47768 fixed the issue #44626, but slowed down the convolution performance (based on eigen_benchmark_cpu_test).  This PR fixes this performance issue using the ability to disable ppc64le gemm_pack_rhs in Eigen (https://gitlab.com/libeigen/eigen/-/commit/91e99ec1e02100d07e35a7abb1b5c76707237219)

@Flamefire @ezhulenev @ChipKerchner

**Review by ezhulenev — APPROVED** [review]

**Comment by jayfurmanek** [comment]
This is great! Thanks @maxiwell !

**Comment by Flamefire** [comment]
Just double-checking: The mechanism in Eigen is very recent. Did you update Eigen already so this is actually used?

**Comment by maxiwell** [comment]
@Flamefire Yes, I have waited for Eigen update here to start the PR

**Comment by jayfurmanek** [comment]
Ah, right, so this likely won't back-port to 2.5 cleanly then. Beyond the updated Eigen, are there are other dependent changes in main beyond the 2.5 tag?

**Comment by maxiwell** [comment]
@jayfurmanek AFAIK, you just need to use both commits in this PR and change the `third_party/eigen3/workspace.bzl` to update Eigen

**Comment by jayfurmanek** [comment]
Gotcha. That's good.
Do you have the minimum commit of Eigen that's needed? If not, I can look it up.
thanks.

**Comment by maxiwell** [comment]
This commit https://github.com/tensorflow/tensorflow/commit/b513d76287a1067ee2a161dfac2ecfb6741417dc updates Eigen with a good commit id for that (another file is also updated in this commit, but only the workspace.bzl is necessary here)

**Pull request merged**
