### PR TITLE
Adding Swift Language Bindings.

### PR DESCRIPTION
**Pull request by RockfordWei**
https://github.com/PerfectlySoft/Perfect-TensorFlow
Supports Swift 3.1/4.0 on both macOS / Ubuntu Linux, with full documentation and example.

### CODE REVIEW

**Comment by RockfordWei** [comment]
Just signed the CLA, please check it out, Thank you!

**Comment by drpngx** [comment]
@RockfordWei I can't see the CLA in our database. It's associated with email. Could you check again?

Thanks.

**Comment by RockfordWei** [comment]
@drpngx Yes, I did sign the document and the email address is 100% matched with my google developer account. The CLA is terrible - not editable, actually, so I had to sign both documents for individual and on behalf my employer and I can review them in any moment online. Do you need my envelope id?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Review by drpngx — APPROVED** [review]

**Pull request merged**
