### PR TITLE
[Go] add bazel rules

### PR DESCRIPTION
**Pull request by wamuir**
PR adds Bazel rules to build and test tensorflow/go. Uses [rules_go](https://github.com/bazelbuild/rules_go).

### CODE REVIEW

**Comment by gbaned** [comment]
@gharibian  Can you please review this PR ? Thanks!

**Comment by rjpower** [comment]
Adding Austin since this seems mostly like it will impact devinfra.

**Comment by angerson** [comment]
I think this is beyond my level to accept... is it an accurate statement to say that this change adds a golang requirement into the full TF build? That seems like quite a large change that would need internal planning / support. Is there any other context you can point us to?

**Comment by angerson** [comment]
FYI @mihaimaruseac

**Comment by wamuir** [comment]
@angerson and @mihaimaruseac, thanks for looking.  Admittedly, I'm unable to assess internal implications (I am sensitive to these but lack insight) and don't have an understanding of acceptance level or criteria. @angerson, I completely agree that I left context out of this PR; let me take an initial stab at describing the problem.  Can fill in more blanks, if needed.

As it stands now:

1. Go bindings cannot be built via Go's preferred tooling (Go Modules / `go get` fails). See #44655.

2. Go bindings cannot be built via TensorFlow's preferred tooling (Bazel). This PR, but also see #18100.

This PR is not my preferred solution.  I'd strongly prefer that the Go bindings exist in their own repo (I wonder why the bindings are here, anyway?) and have recently proposed as much to community, including establishing a SIG Go (/cc @theadactyl).  Of course, there are other potential solutions including use of a third-party's fork/bindings, using/creating
some additional tooling to build/install, and so forth. As a very less-than-ideal solution, there is an [install guide](https://github.com/tensorflow/build/tree/master/golang_install_guide) in SIG Build's repo that amounts to making a local development copy of the TF repo, applying any patches, generating code, shuffling some directories around, generating more code, and then, for any/all dependent packages using a `replace` directive to point at the local copy instead of this repo (whew!).

Again, thanks so much.  I appreciate any thoughts that you have.

**Comment by mihaimaruseac** [comment]
I am unsure if we have anyone left at Google that works on the go bindings.

It might be possible to actually move these bindings to a separate repository.

**Comment by gbaned** [comment]
@wamuir Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Comment by theadactyl** [comment]
I think this could use an RFC:
https://github.com/tensorflow/community/blob/master/governance/TF-RFCs.md
@mihaimaruseac do you have an idea of who might sponsor?

**Comment by mihaimaruseac** [comment]
I can sponsor

**Comment by wamuir** [comment]
Good news, I'll draft and submit to community.  I have time this week.

**Comment by wamuir** [comment]
https://github.com/tensorflow/community/pull/407

**Comment by gbaned** [comment]
@wamuir Can you please resolve conflicts? Thanks!

**Comment by wamuir** [comment]
> @wamuir Can you please resolve conflicts? Thanks!

Sure thing, done

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
@wamuir Can you please address Ubuntu Sanity errors? Thank you!

**Comment by wamuir** [comment]
> @wamuir Can you please address Ubuntu Sanity errors? Thank you!

@gbaned done, can you please trigger the tests to rerun?

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
For this one, I needed to first create stub files as Copybara expects them. When that change lands (after it gets approved, etc.), please rebase this PR and hopefully it should go in afterwards.

**Comment by mihaimaruseac** [comment]
Ok, this should now be doable after fixing the merge conflicts

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
It generates proper copybara imports :tada: 

However, still fails

```
# DEBUG: /tf/tensorflow/third_party/repo.bzl:132:14:
# Warning: skipping import of repository 'io_bazel_rules_go' because it already exists.
# ERROR: Traceback (most recent call last):
# 	File "/tf/tensorflow/WORKSPACE", line 23, column 14, in <toplevel>
# 		tf_workspace0()
# 	File "/tf/tensorflow/tensorflow/workspace0.bzl", line 134, column 20, in workspace
# 		grpc_extra_deps()
# 	File "/root/.cache/bazel/_bazel_root/fbac33eb30dbfb6b11b15a7ff5ac830d/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl", line 36, column 27, in grpc_extra_deps
# 		go_register_toolchains(version = "1.18.4")
# 	File "/root/.cache/bazel/_bazel_root/fbac33eb30dbfb6b11b15a7ff5ac830d/external/io_bazel_rules_go/go/private/sdk.bzl", line 458, column 13, in go_register_toolchains
# 		fail("go_register_toolchains: version set after go sdk rule declared ({})".format(", ".join([r["name"] for r in sdk_rules])))
# Error in fail: go_register_toolchains: version set after go sdk rule declared (go_sdk)
```

PTAL

**Comment by wamuir** [comment]
@mihaimaruseac very cool, thanks.  I'll work on this.

**Comment by wamuir** [comment]
@mihaimaruseac I've updated:  `io_bazel_rules_go` is now pulled into the bazel workspace via `@com_github_grpc_grpc` (call to `grpc_extra_deps`)... this is why go_register_toolchains errored.  Additionally, I've updated for protos that moved into into tsl.  Commits have been squashed.

This will need two more stub files:
- tensorflow/go/tsl/profiler/protobuf/BUILD
- tensorflow/go/tsl/protobuf/BUILD

Can you create these stubs?  I'd write a separate PR but I assume it will hit the same issue with copybara.

**Comment by mihaimaruseac** [comment]
Should be handled now

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @wamuir Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @wamuir Can you please resolve conflicts? Thank you!

**Comment by wamuir** [comment]
@gbaned Yes, I'll take a look at this.

**Comment by gbaned** [comment]
> @gbaned Yes, I'll take a look at this.

Hi @wamuir Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @wamuir I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for your contribution!

**Pull request closed without merging**
