### PR TITLE
Ensure all ValueErrors are raised

### PR DESCRIPTION
**Pull request by ConcurrencyPractitioner**
Some ValueErrors are currently not thrown (or raised) when they are detected. We want to avoid this and raise all ValueErrors given the chance.

### CODE REVIEW

**Comment by ConcurrencyPractitioner** [comment]
I signed it.

**Comment by ConcurrencyPractitioner** [comment]
Hi @anj-s  Are you going to review?

**Review by anj-s — DISMISSED** [review]

**Comment by ConcurrencyPractitioner** [comment]
@anj-s Hi, I just want to confirm something. Would this change require tests? Or should I do something else?

**Comment by martinwicke** [comment]
There are some failures that are newly uncovered from this. Can you fix the new errors? I've retriggered the tests. There is a failure in contrib/quantize:fold_batch_norms_test

**Comment by tedyu** [comment]
When I look at:

https://source.cloud.google.com/results/invocations/66bfcd5b-c469-4f4e-8794-0a0de124bc41/targets/%2F%2Ftensorflow%2Fcontrib%2Fquantize:fold_batch_norms_test/tests

I don't see link for the console output for the test.
How can I access the console output ?

thanks

**Comment by ConcurrencyPractitioner** [comment]
@martinwicke Outside of this test error, should anything else be done?

**Comment by ConcurrencyPractitioner** [comment]
@martinwicke @anj-s Should the test be retriggered? Usually, QA should not take this long.

**Comment by tedyu** [comment]
@anj-s 
Can you take another look at the PR ?

Thanks

**Review by anj-s — APPROVED** [review]

**Comment by martinwicke** [comment]
Unless this hits unexpected flakes in testing, this should submit soon.

**Pull request merged**
