### PR TITLE
Fixes NaNs in weighted_moments with all-zeros weights.

### LINKED ISSUE #51792: weighted_moments produces NaNs when weights are all zeros
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): git
- Python version: 3.9
- Bazel version (if compiling from source): 4.2
- GCC/Compiler version (if compiling from source): gcc-10
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
`tf.nn.weighted_moments` produces NaNs when all weights are zeros.
**Describe the expected behavior**
Correct result in this case should be zeros.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):
Do not divide by 0 unless you are Chuck Norris.

**Standalone code to reproduce the issue**
```python
x = tf.random.uniform((5, 3))
w = tf.zeros((5, 1))

tf.nn.weighted_moments(x, axes=0, frequency_weights=w)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([nan, nan, nan], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([nan, nan, nan], dtype=float32)>)


```

### PR DESCRIPTION
**Pull request by eli-osherovich**
Fixes #51792

### CODE REVIEW

**Comment by eli-osherovich** [comment]
@mihaimaruseac 
Friendly ping.

**Comment by eli-osherovich** [comment]
ANY reply?

**Comment by eli-osherovich** [comment]
@gbaned ?

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Sorry, was OOO

**Comment by eli-osherovich** [comment]
Thanks @mihaimaruseac 
It seems there were several tests that failed due to unrelated issues...
Should these be re-run?

**Comment by mihaimaruseac** [comment]
Hi.

The failing tests are optional for merging the PR (as they're flaky, we have an internal version of them that behaves better and roadmap work to make external tests be similar).

This is now waiting on internal review and after that passes it should automerge.

Thank you for the PR

**Review by gbaned — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
This is being rolled back due to tests failing. Can you provide a test that fails without this PR and this Pr fixes and then I can take it internally and discuss with other folks to see which scenario is more important / come up with a fix that handles both scenarios?

Unfortunately, cannot share internal test.

**Comment by mihaimaruseac** [comment]
Reciprocal is not a linear operation.

**Comment by eli-osherovich** [comment]
Of course, reciprocal is not linear. We are not fixing it...
Weighted sum is linear though. I think most people would expect a zero when all weights are zeros, not a NaN.

**Pull request merged**
