### PR TITLE
Simplify tensorflow/core/BUILD

### LINKED ISSUE #11985: windows bazel build failed: undeclared inclusion
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
2ab9cb209babf905091dcff2f7cdce38da616cfe
- **Python version**: 
3.5.3
- **Bazel version (if compiling from source)**:
0.5.3
- **CUDA/cuDNN version**:
None
- **GPU model and memory**:
None
- **Exact command to reproduce**:
bazel --output_base C:\t  build  //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
ERROR: C:/os/tensorflow/tensorflow/core/BUILD:1271:1: undeclared inclusion(s) in rule '//tensorflow/core:lib_internal':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/framework/variant_tensor_data.cc':
  'C:/os/tensorflow/tensorflow/core/framework/tensor.h'
  'C:/os/tensorflow/tensorflow/core/framework/allocator.h'
  'C:/os/tensorflow/tensorflow/core/framework/numeric_types.h'
  'C:/os/tensorflow/tensorflow/core/framework/type_traits.h'
  'C:/os/tensorflow/tensorflow/core/framework/variant.h'
  'C:/os/tensorflow/tensorflow/core/framework/type_index.h'
  'C:/os/tensorflow/tensorflow/core/framework/tensor_shape.h'
  'C:/os/tensorflow/tensorflow/core/framework/tensor_types.h'
  'C:/os/tensorflow/tensorflow/core/framework/types.h'
  'C:/os/tensorflow/tensorflow/core/framework/bfloat16.h'

### Source code / logs

### PR DESCRIPTION
**Pull request by snnn**
Fix #11985

### CODE REVIEW

**Comment by meteorcloudy** [comment]
I also think we can remove LIB_INTERNAL_WINDOWS_DEPS , but this change also removed 
```
"framework/variant_tensor_data.h",        
"framework/variant_tensor_data.cc",
```
@gunan Where is do you think is the right place to put them?

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Review by rmlarsen — APPROVED** [review]

**Review by rmlarsen — CHANGES_REQUESTED** [review]
Please wait for Gunhan to comment.

**Comment by gunan** [comment]
Jenkins, test this please.
As long as the build passes, I am OK with the change.
My later tests showed that the addition of the files were not fully needed, but forgot to remove the lines when I was rolling my change forward.

**Review by gunan — APPROVED** [review]

**Review by rmlarsen — APPROVED** [review]

**Pull request merged**
