### PR TITLE
Use `tf.compat.v1.summary.FileWriter` under TF v1

### PR DESCRIPTION
**Pull request by ayushmankumar7**
@mihaimaruseac Here is the new Pull Request. 

Issue: #37113

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Ok, now what's left is to write a test that would fail before this change and passes afterwards.

**Comment by ayushmankumar7** [comment]
What should i do ? 
All the other parts of the code is compatible with tensorflow 2.x

**Comment by mihaimaruseac** [comment]
So this PR is not needed on master (where 2.x behavior and API is used)?

**Comment by ayushmankumar7** [comment]
"module_test.py" failed initially. Converting  "tf.summary.FileWriter" to  "tf.compat.v1.summary.FileWriter" , solves the problem.
Hence, i think this should be on the master.

This is the Screenshot, before i made the changes.
Screenshot from 2020-03-02 22-58-37


Here is the Screenshot to the Final Result after the changes
Screenshot from 2020-03-02 22-56-34

**Comment by gbaned** [comment]
@mihaimaruseac Can you please take a look on the above comment from @ayushmankumar7. Thank you!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by ayushmankumar7** [comment]
@mihaimaruseac Thanks for the approval. :+1:

**Pull request merged**
