### PR TITLE
Add back bazel clean into configure script.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Review by av8ramit — APPROVED** [review]

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Look like there is an issue we missed due to missing bazel clean.
I am looking into root causing this, and solving the problem

**Comment by Androbin** [comment]
Could you please explain briefly, what kind of issue this is?
I would like to know under which circumstances cleaning is actually necessary to recompiling successfully.
This would be good to know because this comes undeniably with some speed penalty.

> Bazel's design is such that these problems are fixable; we consider such bugs a high priority, and will do our best fix them. If you ever find an incorrect incremental build, please file a bug report. We encourage developers to get out of the habit of using `clean` and into that of reporting bugs in the tools.

**Comment by gunan** [comment]
https://github.com/bazelbuild/bazel/issues/2759

**Comment by Androbin** [comment]
@gunan from what the referenced issue says, this should only be an issue on macOS?

**Comment by gunan** [comment]
We first observed this on macos, but then reproduced the same problem on
different platforms as well.

**Comment by Androbin** [comment]
As far as I know, the according fix was already available and now introduced in the recent release of bazel.

**Pull request merged**
