### PR TITLE
Fix a minor tuple plus operation

### PR DESCRIPTION
**Pull request by imsheridan**
This PR is to fix a minor bracket format for tuple plus operation.

As we can see [_conv definition](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L2167), the input arg "filter_size" is an int tuple.
>   #Now the computation.
>   kernel = vs.get_variable(
>       "kernel", filter_size + (total_arg_size_depth, num_features), dtype=dtype)

Thus this PR is to fix above "[]" with "()" since plus operation should be on same data type tuple instead of list.

### CODE REVIEW

**Review by benoitsteiner — APPROVED** [review]

**Comment by benoitsteiner** [comment]
@imsheridan This change results in the following error in test //tensorflow/contrib/rnn:rnn_cell_test: TypeError: can only concatenate list (not "tuple") to list. Can you fix the code ?

**Comment by imsheridan** [comment]
Thanks @benoitsteiner , subbmited another iteration to fix the error you pointed out. Could you please kindly help how to run tests and check tests results myself locally?

**Comment by imsheridan** [comment]
@jhseu Fixed the failed test case, could u pls help re-run the gates?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by imsheridan** [comment]
I'll looked into the failure today.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 19 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
@imsheridan any luck with this? It's almost ready to merge!

**Comment by imsheridan** [comment]
Oh busy on other stuff recent days, will reopen this PR when I got time to fix the failure tests.

**Pull request closed without merging**
