### PR TITLE
Change collection.Sequence to collection.abc.Sequence in keras recurrent.py 2

### PR DESCRIPTION
**Pull request by ulf1**
see https://github.com/tensorflow/tensorflow/issues/35892

### CODE REVIEW

**Comment by qlzh727** [comment]
Thanks for reporting the issue, since py2 is end of life as of 2020/1/1, we probably can change to use py3 symbol. I will need to check with TF build team and see if they have already drop the py2 test, otherwise this will cause build failure in py2.7.

@gunan, is it safe to migrate to py3 only symbol?

**Comment by gunan** [comment]
Unfortunately, we have not deprecated/migrated all the internal workflows yet.
So we cannot accept any changes that would break python2 yet.

**Comment by qlzh727** [comment]
Thanks for the reply. Closing this PR and related issue now.

**Comment by ulf1** [comment]
@gunan
the python 3.9 release is scheduled for October 2020. 
https://www.python.org/dev/peps/pep-0596/

**Comment by gunan** [comment]
I understand, but for a while, we still have to have changes that are compatible with python 2.7.
Maybe we can have the line switch between collections.abc or collections based on python version?

**Pull request closed without merging**
