### PR TITLE
DO NOT SUBMIT: Temporarily disable go:test

### PR DESCRIPTION
**Pull request by caisq**
context: b/70154286

### CODE REVIEW

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
cc @jhseu @asimshankar

**Review by gunan — APPROVED** [review]
Could you file an internal bug for us to reenable this test after debugging it?

**Comment by asimshankar** [comment]
Let's try https://github.com/tensorflow/tensorflow/pull/15170 instead of disabling the test?

**Pull request closed without merging**
