### PR TITLE
TFLu: remove -fno-builtin compiler flag

### PR DESCRIPTION
**Pull request by mansnils**

### CODE REVIEW

**Comment by mshawcroft** [comment]
What is the motivation for this patch?  Would be good if there was a description in the commit log!

**Comment by mansnils** [comment]
Good point, I will add a description. The motivation is that it disables optimization of standard C library functions, which may cause problems.

**Comment by petewarden** [comment]
Thanks for looking into this Mans! The background to this flag being present is that it helps us avoid code that introduces function calls like exit() that are not present on bare metal platforms without an OS. We normally link with --no-stdlib on those platforms, but because builtins are inserted inline during compilation, it's easy to accidentally use them and either end up with invisible code bloat or obscure linker errors caused by libc functions the builtins themselves call.

Could you add a bit more about the binary size or other optimization problems you see with this flag enabled? Maybe we can turn it on in particular circumstances.

**Comment by mansnils** [comment]
I didn't know that was the background of the flag.

For many binaries, the file size is about 7% (~6% with cmsis-nn tag) percent bigger with the flag enabled.

There is also this issue reported with some significant performance improvement for cmsis-nn without the flag:
https://github.com/tensorflow/tensorflow/issues/37361
CMSIS-NN use optimized builtins for memset and memcpy frequently.

**Comment by mansnils** [comment]
Gentle ping for review

**Review by petewarden — APPROVED** [review]

**Pull request merged**
