### PR TITLE
Apply final cherry-picks for 1.5.0 release.

### PR DESCRIPTION
**Pull request by angerson**

### CODE REVIEW

**Review by av8ramit — DISMISSED** [review]

**Comment by angersson** [comment]
I have cherry-picked a prerequisite of 973167c whose absence was causing the tests to fail. Thanks to @panyx0718 for investigating.

**Comment by angersson** [comment]
I have cherry-picked yet another prerequisite.

**Comment by angersson** [comment]
I've applied a subset of earlier changes to test_util that may allow the test to run, without bringing in other odd dependencies.

**Comment by av8ramit** [comment]
@angersson are we closing this one until bfloat16 is cherrypicked into 1.5 properly?

**Comment by angersson** [comment]
@av8ramit Yep.

**Pull request closed without merging**
