### PR TITLE
converting alpha to float before use

### PR DESCRIPTION
**Pull request by tusharsnx**
issue fixed if user enters aplha = 1 instead of alpha = 1.0, causing error during loading weights due to model_name getting wrong and downloading fails. Also typo at the line 152 to add consistency for the user.

### CODE REVIEW

**Comment by tusharvickey1999** [comment]
@googlebot I signed it !

**Comment by mihaimaruseac** [comment]
Is there a real issue that this fixes?

**Comment by tusharvickey1999** [comment]
@mihaimaruseac #49904 this issue was related to this bug. Mobilenetv2 could not download imgnet weights even after all value validations done, url gets wrong when alpha is 1 instead of 1.0

**Review by tusharsnx — COMMENTED** [review]
This is to ensure user is guided to enter 1.0 and not 1, even though internally it will be managed accordingly

**Comment by mihaimaruseac** [comment]
https://github.com/tensorflow/tensorflow/commit/8a4bd5f159815ff5f31ec2601d4d8a9284c6d3bb is the proper fix (as it silently converts `1` to `1.0` when serializing to string to form the URL). `1` is a perfectly valid floating point number and there should be no behavior difference between `1` and `1.0`.

Since above commit landed, there is no need for this PR anymore.

Thank you for the PR and sorry that another PR landed first

**Pull request closed without merging**
