### PR TITLE
[TF-TRT] Refactoring Final Step - Preparing for transition to C++ Conversion API

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
**Objective of this PR:**

- *Lazy Loading:* Fix & Replace https://github.com/tensorflow/tensorflow/pull/56334 (Lazy loading was blocking the generation of golden APIs)

- Improving overall code structure:
  - Separate `v1` and `v2` Converter APIs in one
  - Separate public facing APIs & utility functions in different files:
    - `constants.py`: Hard Coded Objects for TF-TRT
    - `graph_utils.py`: Graphdef manipulation objects & funcs
    - `lazy_utils.py`: Lazy loading utilities to prevent the loading of `_pywrap_py_utils` if not required.
    - `trt_utils.py`: General purpose utility functions
    - `types.py`: Utility classes to help TF-TRT development

This PR changes the internal of the Python TF-TRT codebase and does not modify the public facing APIs.
We do not expect any non-backward compatible changes or any impact on user code (if they used public APIs).

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
@bixia1 for review.
Sorry for the large PR, I really don't have a way to split this in small incremental changes

**Comment by gbaned** [comment]
@DEKHTIARJonathan Can you please resolve conflicts? Thank you!

**Comment by DEKHTIARJonathan** [comment]
@bixia1 please review

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @DEKHTIARJonathan Can you please resolve conflicts? Thank you!

**Pull request closed without merging**
