### PR TITLE
[XLA] Include sort in ReplaceComputations check

### PR DESCRIPTION
**Pull request by DavidNorman**
Sort has a subcomputation, and therefore should be included in this check.  The check is in ReplaceComputations, and is checking all operations which have a subcomputation.

### CODE REVIEW

**Review by jlebar — COMMENTED** [review]
Ugh, this looks like a bad bug.  Should we write a unit test?

**Comment by DavidNorman** [comment]
sure - i will add one.

this code path is never exercised because i believe that no backends other than the GC one use the subcomputation unifier, and that is the only thing that uses replace computation.

**Comment by DavidNorman** [comment]
hi- i am definitely looking at this - it isn't too high priority at our end so it might take me a little time to get around to it.

**Comment by DavidNorman** [comment]
@jlebar test added.

**Review by jlebar — APPROVED** [review]

**Pull request merged**
