### PR TITLE
Fix markdown syntax of skflow README.md

### PR DESCRIPTION
**Pull request by nsuke**
I find it very inconvenient since links are not clickable and code blocks are not highlighted.

### CODE REVIEW

**Comment by nsuke** [comment]
You may also want to remove license and pypi badges.
I moved them from the bottom because I couldn't decide whether you still need them.

**Comment by terrytangyuan** [comment]
Great! Simply removing them should be fine.

**Comment by nsuke** [comment]
OK, removed them.

**Comment by ilblackdragon** [comment]
@tensorflow-jenkins please test this!

**Comment by ilblackdragon** [comment]
@tensorflow-jenkins test this please.

**Pull request merged**
