### PR TITLE
Added 8-bit Quantization Support for ELU.

### PR DESCRIPTION
**Pull request by amitsrivastava78**

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@achowdhery, this is kind of important PR for me, would be great to see your feedback on the PR

Regards 
Amit

**Comment by amitsrivastava78** [comment]
@achowdhery , i have optimized the implementation, kindly have a look.

Regards
Amit

**Comment by amitsrivastava78** [comment]
Added support for uint8 and int8 as well for ELU


Regards
Amit

**Comment by amitsrivastava78** [comment]
Added Support in Toco as well.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@achowdhery , i have updated the PR with all the scenarios and tested with model as well, kindly check, this is very important PR for me.

Regards
Amit

**Comment by gbaned** [comment]
@amitsrivastava78 Could you please resolve the conflicts? Thanks!

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
