### PR TITLE
Fix issue in tf.image.extract_glimpse

### LINKED ISSUE #2134: tf.image.extract_glimpse does not work as expected
tf.image.extract_glimpse function does not work as expected. In some cases, the extracted glimpses are the same regardless of offset parameters. Please see the below code to reproduce.
### Environment info

Operating System: Ubuntu 14.04 

Installed version of CUDA and cuDNN: CUDA 7.5, cuDNN R4

If installed from sources, provide the commit hash: cf1659d
### Steps to reproduce

Try to run the code

```
import tensorflow as tf
import numpy as np

input_img = np.arange(25).reshape((1,5,5,1))

first_glimpse = tf.image.extract_glimpse(input_img, [3,3], [[1,1]],
                                    centered=False, normalized=False)
second_glimpse = tf.image.extract_glimpse(input_img, [3,3], [[2,1]],
                                    centered=False, normalized=False)

sess = tf.Session()

print first_glimpse.eval(session=sess)[0,:,:,0]
print second_glimpse.eval(session=sess)[0,:,:,0]
```

Results are

```
first_glimpse = [[  0.   1.   2.]
                 [  5.   6.   7.]
                 [ 10.  11.  12.]]
second_glimpse = [[  0.   1.   2.]
                  [  5.   6.   7.]
                  [ 10.  11.  12.]]
```

Is this a bug? Or am I missing something?

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to fix the issue raised in #2134 where `tf.image.extract_glimpse` does not work as expected when `centered=False` and `normalized=False`

This fix fixes #2134.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by drpngx** [comment]
Jenkins, test this please.

@benoitsteiner what do you think?

**Review by benoitsteiner — APPROVED** [review]

**Comment by patriciacs1994** [comment]
Hello, I am using tf.image.extract_glimpse. And I realised that the bug has not been in fixed in the code. How can I use this solution @yongtang ?

**Comment by yongtang** [comment]
@patriciacs1994 I think the PR has been merged long time ago. If the issue still persists, can you open a new issue with the extract version of TF you are using, and the minimal code snippet to reproduce the issue?

**Comment by patriciacs1994** [comment]
Thank you, I will

**Pull request merged**
