### PR TITLE
Remove deprecated .where in math_grad.py

### PR DESCRIPTION
**Pull request by vcarpani**
This PR substitutes array_ops.where with array_ops.whare_v2 in math_grad.py, removing the deprecated message.

### CODE REVIEW

**Review by alextp — DISMISSED** [review]

**Comment by gbaned** [comment]
@vcarpani Could you please address the build failures? Thanks!

**Comment by gbaned** [comment]
@vcarpani Could you please resolve the conflicts? Thanks!

**Comment by vcarpani** [comment]
> @vcarpani Could you please resolve the conflicts? Thanks!

Yes, I will, had no spare time in the last weeks, as soon as i can I will get back on this ;)

**Comment by vcarpani** [comment]
`bazel test //tensorflow/python`(which was failing before) is now passing

**Review by alextp — DISMISSED** [review]

**Comment by rthadur** [comment]
@vcarpani can you please check build failures ?

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Review by alextp — APPROVED** [review]

**Pull request merged**
