### PR TITLE
golang: ~2x speedup for encodeTensor()

### PR DESCRIPTION
**Pull request by anight**
This is duplicate of https://github.com/tensorflow/tensorflow/pull/14368, but now it can be merged safely because https://github.com/tensorflow/tensorflow/pull/14331 is merged.

CC: https://github.com/tensorflow/tensorflow/pull/14408

before:

$ go test -bench=.
goos: linux
goarch: amd64
pkg: github.com/tensorflow/tensorflow/tensorflow/go
BenchmarkNewTensor/[150528]-8                200           6792809 ns/op
PASS
ok      github.com/tensorflow/tensorflow/tensorflow/go  2.116s

after:

$ go test -bench=.
goos: linux
goarch: amd64
pkg: github.com/tensorflow/tensorflow/tensorflow/go
BenchmarkNewTensor/[150528]-8                500           3269740 ns/op
PASS
ok      github.com/tensorflow/tensorflow/tensorflow/go  2.021s

### CODE REVIEW

**Review by asimshankar — APPROVED** [review]
(Do you also want to consider a similar optimization on the decode side in a follow up?)

**Comment by asimshankar** [comment]
Jenkins, test this please

**Comment by anight** [comment]
@asimshankar Yeah, this is great idea. I'll open a new pr for this one.

**Comment by asimshankar** [comment]
Jenkins, test this please

**Comment by asimshankar** [comment]
That test failure seems un-related. Haven't dug in, but it seems that the continuous builds are passing beyond that point, so perhaps something fixed at head.

**Comment by asimshankar** [comment]
Jenkins, test this please

**Comment by asimshankar** [comment]
Jenkins, test this please.

**Pull request merged**
