### PR TITLE
Update layers pull request

### PR DESCRIPTION
**Pull request by shreyneil**
I have created a new pull request by updating the unit test cases with reference to my previous pull request
https://github.com/tensorflow/tensorflow/pull/13829 .
I have already updated layers.py initially by checking for beta in the if condition.
The initial pull request was raised in accordance with the issue 
https://github.com/tensorflow/tensorflow/issues/11673 .

Please verify and get back.

### CODE REVIEW

**Comment by shreyneil** [comment]
Please verify and get back.

**Comment by vrv** [comment]
@tensorflow-jenkins  test this please

**Review by vrv — APPROVED** [review]

**Comment by shreyneil** [comment]
it would be great if you could merge this PR.

**Comment by yifeif** [comment]
@shreyneil do you mind fixing the test? 
`NameError: global name 'dtype' is not defined`

**Comment by shreyneil** [comment]
Made the necessary changes, please verify.

**Comment by yifeif** [comment]
Thanks @shreyneil! @tensorflow-jenkins test this please.

**Comment by shreyneil** [comment]
It would be great if you could merge this PR.

**Pull request merged**
