### PR TITLE
Branch 140903864

### PR DESCRIPTION
**Pull request by benoitsteiner**

### CODE REVIEW

**Comment by gunan** [comment]
Windows failure looks legit.
@mrry It looks like some cuda stuff is leaking into non-cuda build?

**Comment by mrry** [comment]
Apparently yes. I don't recognize the symbols `CudaRoot` and `LibdeviceRoot`… perhaps they're new and whatever CL added them will make it clear what's wrong. (I'm not sure why this wouldn't fail to link on Linux CMake CPU as well, but maybe MSVC is more strict about unused symbols?)

**Comment by mrry** [comment]
Maybe this one?

https://github.com/benoitsteiner/tensorflow/commit/e1f44d854e9e6db6ce1f7c70b81d0fef03e4a932

**Comment by mrry** [comment]
It'd probably be possible to fix this up by moving this file https://github.com/benoitsteiner/tensorflow/blob/e1f44d854e9e6db6ce1f7c70b81d0fef03e4a932/tensorflow/core/platform/posix/cuda_libdevice_path.cc to `../default` (and modifying the necessary paths in the build config).

**Comment by benoitsteiner** [comment]
I've fixed the CudaRoot and LibdeviceRoot compilation errors on windows.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
@martinwicke I see experiment_test failures here.
Maybe this PR does not contain the rollback?

**Comment by martinwicke** [comment]
Not included. Was waiting for LGTMs -- it's being submitted now.

**Comment by benoitsteiner** [comment]
Andrew will push the changes

**Pull request closed without merging**
