### PR TITLE
fixed: issue #36332

### PR DESCRIPTION
**Pull request by OmerLiberman**

### CODE REVIEW

**Comment by gbaned** [comment]
@OmerLiberman thank you for your contribution, please sign CLA.

**Comment by OmerLiberman** [comment]
@gbaned 
signed.

**Review by ashutosh1919 — COMMENTED** [review]
Fixes #36332 . Mentioned it so that no other will work on this.

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
When does `is_start` turn `False`? This should have been documented on the PR's first message.

**Comment by gbaned** [comment]
@OmerLiberman Can you please check mihaimaruseac's comments and keep us posted. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
