### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Mandar-Shinde**
Final UI

### CODE REVIEW

**Comment by martinwicke** [comment]
Yes, please point the logo to https://www.tensorflow.org/images/tf_logo.png or https://www.tensorflow.org/images/tf_logo_transp.png

**Comment by martinwicke** [comment]
Pretty though. Can the build status images be centered? Or is that too much to ask from Markdown?

**Comment by Mandar-Shinde** [comment]
@martinwicke Thanks :blush:

Sorry we can't move build status table to center (as per current version of Markdown).

# **Version: 1 (Pure Markdown)**
big left icon version


# **Version: 2 (Markdown+ html)**
big center icon version

**Comment by martinwicke** [comment]
I'd have to see the md to see which one is better. Some HTML annotations in MD are ok, but not all. Can I see how you did Version 2?

**Comment by Mandar-Shinde** [comment]
Updated to version:2

**Comment by martinwicke** [comment]
Did you as a centering div to the build status icons as well to make the image you sent? Actually, I would center the whole table (maybe just put it into the same div as the logo), and also center the build icon as you (I think) did when you made image version 2. 

Then it's good, and I'll merge it.

**Comment by Mandar-Shinde** [comment]
@martinwicke Yes, :smile:  I have tried same but it seems that table formatting is overridden by Markdown


# **Expected UI (Image)**
Expected UI


# **Expected UI (Markup)**
> **As per HTML code it should be centered but the table will be left aligned in markdown**

<div align="center">
    <br><br>
  <table>
  <tr>
    <th>Linux CPU</th>
    <th>Linux GPU PIP</th>
    <th>Mac OS CPU</th>
    <th>Android </th>
  </tr>
  <tr>
    <td><a href='http://ci.tensorflow.org/job/tensorflow-master/'></a></td>
    <td><a href='http://ci.tensorflow.org/job/tensorflow-master-gpu_pip/'></a></td>
    <td><a href='http://ci.tensorflow.org/job/tensorflow-master-mac/'></a></td>
    <td><a href='http://ci.tensorflow.org/job/tensorflow-master-android/'></a></td>
  </tr>
</table>

</div>
-----------------

**TensorFlow** is an open source software library for numerical computation using
data flow graphs.  Nodes in the graph represent mathematical operations, while
the graph edges represent the multidimensional data arrays (tensors) that flow
between them.  This flexible architecture lets you deploy computation to one
or more CPUs or GPUs in a desktop, server, or mobile device without rewriting
code.  TensorFlow was originally developed by researchers and engineers
working on the Google Brain team within Google's Machine Intelligence research
organization for the purposes of conducting machine learning and deep neural
networks research.  The system is general enough to be applicable in a wide
variety of other domains, as well.

**If you'd like to contribute to tensorflow, be sure to review the [contribution
guidelines](CONTRIBUTING.md).**

**We use [github issues](https://github.com/tensorflow/tensorflow/issues) for
tracking requests and bugs, but please see
[Community](tensorflow/g3doc/resources/index.md#community) for general questions
and discussion.**

## Installation
*See [Download and Setup](tensorflow/g3doc/get_started/os_setup.md).*

#### *Try your first TensorFlow program*
```python
$ python

>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> sess.run(hello)
Hello, TensorFlow!
>>> a = tf.constant(10)
>>> b = tf.constant(32)
>>> sess.run(a+b)
42
>>>
```

##For more information
* [TensorFlow website](http://tensorflow.org)
* [TensorFlow whitepaper](http://download.tensorflow.org/paper/whitepaper2015.pdf)
* [Tensorflow MOOC on Udacity] (https://www.udacity.com/course/deep-learning--ud730)

**Comment by martinwicke** [comment]
Have you tried putting the align="center", or even a style attr on the td itself? It's quite possible that github's CSS sets the table to left-aligned. If that doesn't work, don't worry too much, I like the image and the centered table.

**Comment by Mandar-Shinde** [comment]
@martinwicke alignment is not working with styles too, so by default the table will be aligned left as in image Version: 2 (Markdown+ html)

**Comment by martinwicke** [comment]
merged, thank you!

**Pull request closed without merging**
