### PR TITLE
Spatial pyramid pooling layer implementation.

### PR DESCRIPTION
**Pull request by yardstick17**
PR Inspired from the work of @luizgh and @RikHeijdens.
References:
1. He, Kaiming et al (2015): Spatial Pyramid Pooling in Deep Convolutional Networks for Visual Recognition. http://arxiv.org/pdf/1406.4729.pdf.
2. [Implement SpatialPyramidPooling](https://github.com/Lasagne/Lasagne/pull/799)

### CODE REVIEW

**Comment by yardstick17** [comment]
@yifeif  please review the PR.

**Comment by yardstick17** [comment]
@jart Can you please review the PR. It's been here for a while and not yet reviewed.

**Comment by dnnavn** [comment]
Hi @yardstick17 , Is this feature available in tf-nightly? I looked for it in tf.layers and tf.contrib.layers so far. I'm pretty new to TF. Can you please tell me where to find it? 
Thanks!

**Comment by sfikas** [comment]
@dnnavn It looks like this layer isn't available yet. There is a related open pull request, https://github.com/tensorflow/tensorflow/pull/13259 .

**Comment by dnnavn** [comment]
@sfikas  Thank you. Will follow that thread.

**Pull request closed without merging**
