### PR TITLE
Allow variable sized tensor for RDMA transport

### LINKED ISSUE #10699: RDMA transport should support variable sized tensor
RDMA transport disabled variable size tensor https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L738 and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L759.

However, in the embedding lookup model, the tensor has variable size. It's a common model parallelism case.

### PR DESCRIPTION
**Pull request by llhe**
This PR fixes https://github.com/tensorflow/tensorflow/issues/10699.

Q: Should we make aggressive buffer extension?

### CODE REVIEW

**Comment by junshi15** [comment]
The code is fine. The question is whether we should allow buffers to grow infinitely. Ideally, a buffer should shrink if the current size is unnecessarily large. But I could not think a case where the tensor size is temporary, i.e.  one will likely see the tensor of the same size in the future training steps.

**Comment by drpngx** [comment]
@michaelisard what do you think?

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
@poxvoculi if you have suggestions.

**Comment by poxvoculi** [comment]
We have seen models where there is a very large number of different tensor sizes that don't necessarily repeat.  If there's only one buffer and it is allocated from CPU RAM, it probably doesn't matter.

**Comment by junshi15** [comment]
There is one buffer per tensor, allocated in CPU memory. 

The original assumption was that tensor sizes (except string tensors) did not change over the course of training. It was valid for the early models, e.g. InceptionV3, VGG16, etc. As new models appear, the assumption is not valid anymore. I think we should let buffer sizes vary. 

We could have some kind of policy to reclaim the memory if the tensor sizes have been smaller than the buffer size for some period of time. Note the buffers are pinned and registered for RDMA. Frequent allocation and registration can slow down things. The patch is good for now due to its simplicity.

**Comment by poxvoculi** [comment]
Use of verbs/rdma is optional.  If the model won't run with this constraint, user can just drop back to gRPC.  I'm ok with this.  @drpngx do you want me to review, or wait for Michael?

**Comment by drpngx** [comment]
@poxvoculi I'm not sure how much @michaelisard knows about this, maybe you have the most context on this one.

**Review by poxvoculi — APPROVED** [review]

**Comment by drpngx** [comment]
Thanks!

**Pull request merged**
