### PR TITLE
[TFTRT - Dynamic Shape Phase 3] Add Dynamic Shape Testing for ConvertClipByValue

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
@bixia1 @tfeher for review

Feature Tracker: https://github.com/tensorflow/tensorflow/issues/45481

Please merge this PR after: https://github.com/tensorflow/tensorflow/pull/45587

### CODE REVIEW

**Review by bixia1 — COMMENTED** [review]
Looks good to me. We will come back to this after the parent PR is merged.

**Comment by DEKHTIARJonathan** [comment]
@bixia1 rebased on master (with the new `OpConverterTest` name).
Good for review / merge

**Review by bixia1 — APPROVED** [review]

**Comment by bixia1** [comment]
The test doesn't even compiled and here is just one example of the error message:
third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc:6637:5: error: no matching member function for call to 'AddTestTensor'
    AddTestTensor("t", {1, 2, 3}, trt_type_);
    ^~~~~~~~~~~~~
third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc:1811:8: note: candidate template ignored: could not match 'vector<type-parameter-0-0>' against 'nvinfer1::DataType'
  void AddTestTensor(const string& name, const std::vector<int32>& dims,
       ^

**Comment by DEKHTIARJonathan** [comment]
The bug is fixed and we are good.

```bash
INFO: 318 processes: 318 local.
INFO: Build completed successfully, 325 total actions
//tensorflow/compiler/tf2tensorrt:convert_graph_test                     PASSED in 16.7s
//tensorflow/compiler/tf2tensorrt:convert_graph_test_gpu                 PASSED in 14.9s
//tensorflow/compiler/tf2tensorrt:convert_nodes_test                     PASSED in 96.0s
//tensorflow/compiler/tf2tensorrt:convert_nodes_test_gpu                 PASSED in 86.8s
//tensorflow/compiler/tf2tensorrt:segment_test                           PASSED in 0.2s
//tensorflow/compiler/tf2tensorrt:segment_test_gpu                       PASSED in 0.1s
//tensorflow/compiler/tf2tensorrt:tensorrt_test_cc                       PASSED in 16.7s
//tensorflow/compiler/tf2tensorrt:tensorrt_test_cc_gpu                   PASSED in 15.9s
//tensorflow/compiler/tf2tensorrt:trt_allocator_test                     PASSED in 0.1s
//tensorflow/compiler/tf2tensorrt:trt_engine_op_test                     PASSED in 13.0s
//tensorflow/compiler/tf2tensorrt:trt_engine_op_test_gpu                 PASSED in 12.4s
//tensorflow/compiler/tf2tensorrt:trt_engine_resource_ops_test           PASSED in 13.1s
//tensorflow/compiler/tf2tensorrt:trt_engine_resource_ops_test_gpu       PASSED in 12.4s
//tensorflow/compiler/tf2tensorrt:trt_lru_cache_test                     PASSED in 0.1s
//tensorflow/compiler/tf2tensorrt:trt_shape_optimization_profiles_test   PASSED in 15.9s
//tensorflow/compiler/tf2tensorrt:trt_shape_optimization_profiles_test_gpu PASSED in 12.1s

Executed 16 out of 16 tests: 16 tests pass.
INFO: Build completed successfully, 325 total actions
```

**Review by bixia1 — APPROVED** [review]

**Comment by bixia1** [comment]
I am still seeing this error when using TRT7:
third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc:6687:44: error: type 'float' cannot be narrowed to 'int' in initializer list [-Wc++11-narrowing]
    AddTestWeights("clip_value_min", {1}, {p.clip_value_min}, tf_type_);
                                           ^~~~~~~~~~~~~~~~
third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc:6687:44: note: insert an explicit cast to silence this issue
    AddTestWeights("clip_value_min", {1}, {p.clip_value_min}, tf_type_);
                                           ^~~~~~~~~~~~~~~~
                                           static_cast<int>( )

**Comment by DEKHTIARJonathan** [comment]
Hum... I'm not exactly sure why it fails on your side. It works perfectly on my end...

I changed the dtype of `clip_value_min` and `clip_value_max` to int. That should fix the error message you saw: https://github.com/tensorflow/tensorflow/pull/45589/files#diff-b9ae60f058d9ae72ddc0625fa93ff1b8441e57db5695e8444d18becdb3abea2dR6655-R6656

```bash
INFO: Build completed successfully, 21 total actions
//tensorflow/compiler/tf2tensorrt:convert_graph_test                     PASSED in 14.7s
//tensorflow/compiler/tf2tensorrt:convert_graph_test_gpu                 PASSED in 14.6s
//tensorflow/compiler/tf2tensorrt:convert_nodes_test                     PASSED in 91.2s
//tensorflow/compiler/tf2tensorrt:convert_nodes_test_gpu                 PASSED in 91.8s
//tensorflow/compiler/tf2tensorrt:segment_test                           PASSED in 0.3s
//tensorflow/compiler/tf2tensorrt:segment_test_gpu                       PASSED in 0.1s
//tensorflow/compiler/tf2tensorrt:tensorrt_test_cc                       PASSED in 13.2s
//tensorflow/compiler/tf2tensorrt:tensorrt_test_cc_gpu                   PASSED in 13.1s
//tensorflow/compiler/tf2tensorrt:trt_allocator_test                     PASSED in 0.1s
//tensorflow/compiler/tf2tensorrt:trt_engine_op_test                     PASSED in 12.6s
//tensorflow/compiler/tf2tensorrt:trt_engine_op_test_gpu                 PASSED in 12.7s
//tensorflow/compiler/tf2tensorrt:trt_engine_resource_ops_test           PASSED in 12.4s
//tensorflow/compiler/tf2tensorrt:trt_engine_resource_ops_test_gpu       PASSED in 12.2s
//tensorflow/compiler/tf2tensorrt:trt_lru_cache_test                     PASSED in 0.1s
//tensorflow/compiler/tf2tensorrt:trt_shape_optimization_profiles_test   PASSED in 12.1s
//tensorflow/compiler/tf2tensorrt:trt_shape_optimization_profiles_test_gpu PASSED in 12.0s

Executed 16 out of 16 tests: 16 tests pass.
INFO: Build completed successfully, 21 total actions
```

**Review by bixia1 — APPROVED** [review]

**Pull request merged**
