### PR TITLE
Moved pooling reference ops into its own file

### PR DESCRIPTION
**Pull request by jenselofsson**
Moving the reference pooling ops into its own file to remove dependencies.

### CODE REVIEW

**Review by multiverse-tf — COMMENTED** [review]
Thanks for the change! Could you kindly share the motivation behind this change?

**Comment by jenselo** [comment]
> Thanks for the change! Could you kindly share the motivation behind this change?

I'm working on porting the MaxPooling part of the Pooling kernel to Tensorflow Lite Micro, and then the dependency on gemmlowp needs to be removed in order to build for the bluepill target in Tensorflow Lite Micro.

**Comment by multiverse-tf** [comment]
> > Thanks for the change! Could you kindly share the motivation behind this change?
> 
> I'm working on porting the MaxPooling part of the Pooling kernel to Tensorflow Lite Micro, and then the dependency on gemmlowp needs to be removed in order to build for the bluepill target in Tensorflow Lite Micro.

Cool! Could update the description to reflect this? Like "Moved pooling reference ops into its own file to remove the gemmlowp dependency and enable bluepill target build in TFL Micro"?

**Comment by multiverse-tf** [comment]
Btw, I think such a change should be added to tensorflow/lite/experimental/micro. Added  @petewarden for further comment.

**Review by petewarden — APPROVED** [review]
This looks great, thanks!

**Pull request merged**
