### PR TITLE
verbs: Configure IB/RoCE QPs MTU according to the port MTU

### PR DESCRIPTION
**Pull request by shamoya**
For the verbs RDMA code to work on standard Ethernet networks,
where ports are configured with MTU 1500, need to set the path
MTU to 1K, as the previous 4K value is typical for IB networks.

@junshi15  @llhe @jhseu

### CODE REVIEW

**Comment by poxvoculi** [comment]
Can you make this a compile time or load time option, instead of hard-coding the MTU value?  I would guess there's no one value that's going to be optimal for everyone.

**Comment by jhseu** [comment]
Up to @poxvoculi, but I'd favor defaulting to a lower MTU for better compatibility and proving that a higher MTU matters for performance before offering a configuration option. @shamoya did some basic tests and it didn't seem to matter.

**Comment by poxvoculi** [comment]
A colleague has a better suggestion: Why not just use the library ibv_port_attr.active_mtu value at runtime, instead of compiling in a fixed value?

**Comment by shamoya** [comment]
Thanks @poxvoculi @jhseu,
You are right of course and it's better to query the port (ibv_qeury_port) attributes for the MTU.
The attention was to create a (very) temporary fix just to get things working in Roce for the time being, as 
I am working on a patch that adds rdmacm connection management support to the verbs code.

This is the best to go, and removes all the manual connection configurations the code is doing today.
It will also save the need to get all configurations from the user in Server creation (device, port, gid index, roce version, mtu, etc..) since all the connection configuration will be set automatically accordingly to the grpc network provided by the cluster spec (user controls the verbs network according the GRPC network interfaces). It means they are binded (grpc and verbs on the same hw interface ) but this is the way to go according the grpc+verbs protocol @junshi15 created.
What do you think ?

Anyway, I will change for selecting the MTU from the port query.

**Comment by junshi15** [comment]
Yes, I think this is a temporary fix for the RoCE folks to be able to use Infiniband.

@shamoya is working on a better version with rdmacm, which is smart enough to set the network parameters automatically and properly. I assume that end users, especially those unfamiliar with hardware, would rather not tweak the network parameters, unless the goal is benchmarking.

**Comment by shamoya** [comment]
@poxvoculi - Changed to take active_mtu from port attribures

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by vrv** [comment]
(A spurious failure)

**Review by poxvoculi — APPROVED** [review]

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by bkovalev** [comment]
What the PR a status?

**Comment by bkovalev** [comment]
Why it still not merged?

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@bkovalev It seems that the tests failed on the last try. Let's give it another try.

**Comment by bkovalev** [comment]
Thanks

**Comment by bkovalev** [comment]
Hi,
ROCE is working, but with poor performance. In inception v3 arround 1/8 from Ethernet speed.

**Comment by junshi15** [comment]
@bkovalev did you by any chance checked IB as well? It should not affect IB performance. Verbs supports RoCE, not sure why the performance penalty.

**Pull request merged**
