### PR TITLE
Update TF Lite Android example

### PR DESCRIPTION
**Pull request by Neargye**
update to work in actual Android Studio

### CODE REVIEW

**Comment by achowdhery** [comment]
Thanks for PR. What Android devices has this been tested on?

**Comment by Neargye** [comment]
@achowdhery Samsung S8

**Comment by zaichang** [comment]
FWIW I just had to do the same changes for the TFLite Android example to compile. Tested on macOS 10.13.6 and Android Studio 3.0

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @shashishekhar: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @shashishekhar: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Review by shashishekhar — APPROVED** [review]

**Pull request merged**
