### PR TITLE
Fix some typos.

### PR DESCRIPTION
**Pull request by Yulv-git**

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Please revert changes to `tensorflow/compiler/mlir/g3doc/_includes/tf_passes.md`. It is autogenerated

**Comment by Yulv-git** [comment]
> 

Thanks for pointing out the error, it has now been fixed.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by Yulv-git** [comment]
> This seems to have trouble landing. Can you split it into multiple PRs, one per top-level directory, please?

I don't know how to split this PR into multiple PRs.
Perhaps, I can create multiple branches based on the current official latest master branch to create multiple new PRs.

**Comment by MarkDaoust** [comment]
> I can create multiple branches based on the current official latest master branch to create multiple new PRs.

That sounds right.

**Comment by Yulv-git** [comment]
> This seems to have trouble landing. Can you split it into multiple PRs, one per top-level directory, please?

I have created multiple new PRs based on multiple branches to fix typos.

**Pull request closed without merging**
