### PR TITLE
Fix for a regression in graph rewrite pass  (MKL)

### PR DESCRIPTION
**Pull request by agramesh1**
Changed CPU device string from "cpu" to "CPU" to re enable MKL graph rewrite pass that was disabled by a prior commit.

### CODE REVIEW

**Comment by mahmoud-abuzaina** [comment]
@rmlarsen Did you get a chance to look at this?

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by rmlarsen** [comment]
@gunan @caisq  what does it take to get a successful ubuntu CC test? All the other tests passed yesterday, so that is the only blocker to merge this.

**Comment by caisq** [comment]
I think adding the "kokoro:run" tag is the magic word :) Just added it. The test is running now.

cc @yifeif

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by mahmoud-abuzaina** [comment]
@rmlarsen and @gunan, this fix is critical for Intel MKL functionality. Although this seems to be merged soon into master, we see that r1.4 has been released without this fix, that means r1.4 won't be able to to use MKL. Is there anyway to add this to r1.4?

**Comment by rmlarsen** [comment]
Merged. Thanks for the fix. We had some internal test infrastructure overload that delayed testing. Thanks you for your patience.

**Comment by rmlarsen** [comment]
@wicke @rajatmonga It seems critical that we cherrypick this into R1.4.

**Comment by gunan** [comment]
@av8ramit @case540 Please cherrypick this PR into the release, then we can prepare rc1.

**Comment by rmlarsen** [comment]
@av8ramit could you take a look, please?

**Comment by rmlarsen** [comment]
@gunan didn't see your comment. Thanks!

**Comment by av8ramit** [comment]
We will cherry-pick this into 1.4. Thanks everyone!

**Pull request merged**
