### PR TITLE
update cpuinfo

### PR DESCRIPTION
**Pull request by cocoa-xu**
Update cpuinfo so that TensorFlow builds for riscv64 again, as PR https://github.com/pytorch/cpuinfo/pull/204 broke it for including the `<sys/hwprobe.h>` header, which only exists in the RISC-V Android NDK. It was fixed in https://github.com/pytorch/cpuinfo/pull/215.

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by cocoa-xu** [comment]
Hi, I'm sorry for the ping here, but I was wondering if there're any estimated date for this to be merged? I understand that the risc-v architecture is not in the top tier of support, but as this should be a fairly small PR and would help others to build Tensorflow Lite for risc-v devices. :)

**Comment by cocoa-xu** [comment]
Also I'll happy to bump this to the latest commit ([3c8b153](https://github.com/pytorch/cpuinfo/tree/3c8b1533ac03dd6531ab6e7b9245d488f13a82a5)) of `pytorch/cpuinfo` if you'd like me to do so. 😃

**Comment by gbaned** [comment]
> Hi, I'm sorry for the ping here, but I was wondering if there're any estimated date for this to be merged? I understand that the risc-v architecture is not in the top tier of support, but as this should be a fairly small PR and would help others to build Tensorflow Lite for risc-v devices. :)

Hi @cocoa-xu Sorry for the delay, we are working on this PR internally. Thank you for your contribution!

**Comment by cocoa-xu** [comment]
> > Hi, I'm sorry for the ping here, but I was wondering if there're any estimated date for this to be merged? I understand that the risc-v architecture is not in the top tier of support, but as this should be a fairly small PR and would help others to build Tensorflow Lite for risc-v devices. :)
> 
> Hi @cocoa-xu Sorry for the delay, we are working on this PR internally. Thank you for your contribution!

Got it! Thanks for your kind reply 😃

**Comment by gbaned** [comment]
Hi @vamsimanchala / @mihaimaruseac Import/copybara check is not appearing in the list of checks.  Can you please help to import the changes in this PR?  Thank you!

**Comment by keerthanakadiri** [comment]
Hi @vamsimanchala / @mihaimaruseac  Any update on this PR ? Please. Thank you!

**Comment by mihaimaruseac** [comment]
Needs a rebase, there's a conflict for copybara

**Comment by cocoa-xu** [comment]
Hi @mihaimaruseac, I synced this branch with the origin/master but couldn't see any conflicts here. Could you please let me know which lines are causing conflicts and I'll resolve them as soon as possible. :)

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
