### PR TITLE
Remove never used arg `sample_weight_mode` in tf.keras.Model:compile

### PR DESCRIPTION
**Pull request by howl-anderson**
Argument `sample_weight_mode` of tf.keras.Model:compile never used in code. 

Remove `sample_weight_mode` from arguments and docs.

### CODE REVIEW

**Review by omalleyt12 — COMMENTED** [review]
@howl-anderson Thanks for the PR!

It's true that `sample_weight_mode` is no longer needed here. However, we have backwards compatibility guarantees so unfortunately I don't think we can delete this argument

**Comment by howl-anderson** [comment]
@omalleyt12 I will make another PR to add a comment about this in the code, in case someone tries to remove it too.

**Comment by omalleyt12** [comment]
> @omalleyt12 I will make another PR to add a comment about this in the code, in case someone tries to remove it too.

Sounds good, thanks!

**Comment by howl-anderson** [comment]
the commit [Remove sample_weight_mode arg from compile and cleanup docs](https://github.com/tensorflow/tensorflow/commit/c7aa3e8d1711f49add2c6dc76fc8c000ce1edee8) have merged into the master branch by @pavithrasv, that commit has fixed this issue.

**Pull request closed without merging**
