### PR TITLE
Avoid doing reset when position is still in buffer in BufferedInputStream.

### PR DESCRIPTION
**Pull request by burgerkingeater**
See https://github.com/tensorflow/tensorflow/issues/34510.

This is a duplicated PR of https://github.com/tensorflow/tensorflow/pull/34515, but it cannot be reopened, thus creating a new one.

### CODE REVIEW

**Comment by burgerkingeater** [comment]
@rohan100jain can you help review? thanks.

**Comment by burgerkingeater** [comment]
i drew a diagram for better illustration:
https://www.dropbox.com/s/0z4fv7u7atroixh/Photo%20Oct%2012%2C%203%2025%2056%20PM.jpg?dl=0

**Comment by rohan100jain** [comment]
Could you add a test for buffered_inputstream_test.cc that demonstrates the failure? I believe you can test it via 

bazel test -c opt tensorflow/core:__tensorflow_core_lib_io_legacy_lib_io_all_tests

**Comment by gbaned** [comment]
@burgerkingeater  Can you please check @rohan100jain's comments and keep us posted ? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 19 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by burgerkingeater** [comment]
this is still being worked on.

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by burgerkingeater** [comment]
This is still being worked on, thanks.

**Comment by burgerkingeater** [comment]
@rohan100jain Unit test added. Please take a look and let me know if anything else is needed. Thanks.

**Comment by burgerkingeater** [comment]
@rohan100jain kindly ping

**Comment by burgerkingeater** [comment]
@rohan100jain pinging again..

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Can you look at the failure, please?

`//tensorflow/python/lib/io:file_io_test` is failing and the failure looks related to the PR

```
[       OK ] FileIoTest.test_session
======================================================================
ERROR: testFileSeekableWithZip (__main__.FileIoTest)
testFileSeekableWithZip (__main__.FileIoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/lib/io/file_io_test.runfiles/org_tensorflow/tensorflow/python/lib/io/file_io_test.py", line 674, in testFileSeekableWithZip
    _ = [i for i in info.items()]
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 249, in items
    return [(f, self[f]) for f in self.files]
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 249, in <listcomp>
    return [(f, self[f]) for f in self.files]
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 228, in __getitem__
    bytes = self.zip.open(key)
  File "/usr/lib/python3.6/zipfile.py", line 1419, in open
    % (zinfo.orig_filename, fname))
zipfile.BadZipFile: File name in directory 'arr_0.npy' and header b'\xbcx\xf3`\xb0\x93\x82P\x0f' differ.

======================================================================
FAIL: testSeek (__main__.FileIoTest)
testSeek (__main__.FileIoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/lib/io/file_io_test.runfiles/org_tensorflow/tensorflow/python/lib/io/file_io_test.py", line 462, in testSeek
    self.assertEqual(18, f.tell())
AssertionError: 18 != 27

======================================================================
FAIL: testSeekFromWhat (__main__.FileIoTest)
testSeekFromWhat (__main__.FileIoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/lib/io/file_io_test.runfiles/org_tensorflow/tensorflow/python/lib/io/file_io_test.py", line 496, in testSeekFromWhat
    self.assertEqual(18, f.tell())
AssertionError: 18 != 27

----------------------------------------------------------------------
Ran 65 tests in 0.947s

FAILED (failures=2, errors=1)
================================================================================
```

**Comment by burgerkingeater** [comment]
@mihaimaruseac fixed, thanks.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by burgerkingeater** [comment]
@mihaimaruseac thanks for the review. All check passed, can this PR be merged?

**Comment by mihaimaruseac** [comment]
It should get merged automatically once internal review and internal CI pass.

**Comment by burgerkingeater** [comment]
@mihaimaruseac how is it going with the internal review and CI? It's been 3 days.

**Comment by mihaimaruseac** [comment]
Waiting for owner approval, it gets delayed as people are returning from holidays. Apologies for the delay

**Comment by burgerkingeater** [comment]
@mihaimaruseac just curious about the process. Does every PR need to go through the internal review/CICD process?

**Comment by mihaimaruseac** [comment]
@burgerkingeater yes, every PR is first approved on GitHub, there is a CI run that only tests the open source part of TF and there is a process (Copybara) to integrate the change into the internal version of TF. The result of this integration needs to be reviewed again and tested on CI again (both internally and re-exported to open source). If all is green, the change is merged internally and copybara then merges the PR.

For some PRs there is an additional review round: if APIs are changed, API owners need to approve too. This happens twice a week, all the API-owners tagged PRs and issues and internal changelists are reviewed during these meetings. Once approved, the process from above continues

**Comment by burgerkingeater** [comment]
Thanks for the explanation! @mihaimaruseac

**Pull request merged**
