### PR TITLE
Deprecated contrib.learn.ops.batch_normalize

### PR DESCRIPTION
**Pull request by terrytangyuan**
cc: @ilblackdragon @martinwicke I'll probably do similar thing for some other ops (different PRs) if you think this approach is ok.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@tensorflow-jenkins Test this please

**Comment by terrytangyuan** [comment]
@benoitsteiner Error seems unrelated. Seems to have some flaky tests?

**Comment by terrytangyuan** [comment]
@tensorflow-jenkins Test this please

**Comment by martinwicke** [comment]
We've been mulling a decorator. It takes a message and adds a logging.warning("This function (%s, %s:%d) is deprecated. %s", name, file, line, message) when the function/method is called. It can also add a warning to the beginning of the docstring. 

We could have another one for classes. 

We will use them a fair bit I feel. 

I sent this via email, but it seems it didn't make it.

**Comment by terrytangyuan** [comment]
@martinwicke Thanks. Then I'll make changes later when that decorator is available. This PR should be ok, right? Some tests failed in other unrelated place.

**Comment by martinwicke** [comment]
I think it's ok.

**Comment by terrytangyuan** [comment]
Ping @benoitsteiner required tests passed

**Comment by benoitsteiner** [comment]
The one test failure is due to a known preexisting problem with the png decoder. I'll merge this PR.

**Pull request merged**
