### PR TITLE
Branch 180856860

### PR DESCRIPTION
**Pull request by raghuraman-k**

### CODE REVIEW

**Comment by raghuraman-k** [comment]
@tensorflow-jenkins  "test this please".

**Review by frankchn — APPROVED** [review]

**Comment by jhseu** [comment]
Please address the test failures.

**Comment by raghuraman-k** [comment]
The only failure is a timeout error in the Ubuntu Contrib test:
https://source.cloud.google.com/results/invocations/ebd79e77-af5b-42d6-9b38-c069aa86c1ef/targets
Is it ok to submit this change with this timeout error?

**Review by caisq — APPROVED** [review]
Woohoo! Thanks, @raghuraman-k !

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
There are a few test failures:
http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/7922/consoleFull

These should be relative straightforward to address. We can merge the PR tomorrow morning. Shortly after, I can send PRs to fix them.

**Comment by raghuraman-k** [comment]
Hi Shanquing,
Sure, will take a look first thing tomorrow. Thanks for your help.
Raghu

On Jan 4, 2018 8:38 PM, "Shanqing Cai" <notifications@github.com> wrote:

There are a few test failures:
http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-
python3/7922/consoleFull

These should be relative straightforward to address. We can merge the PR
tomorrow morning. Shortly after, I can send PRs to fix them.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/pull/15867#issuecomment-355470997>,
or mute the thread

**Pull request merged**
