### PR TITLE
Additional change to pull request #6014

### PR DESCRIPTION
**Pull request by zuoxingdong**
Additional change to pull request #6014

### CODE REVIEW

**Comment by martinwicke** [comment]
Please add the changes from #6014 here. Thanks!

**Comment by zuoxingdong** [comment]
@martinwicke Done, 2 files together.

**Review by alextp — APPROVED** [review]

**Comment by alextp** [comment]
Jenkins, test this please.

**Comment by alextp** [comment]
Thanks for the fix!

**Pull request merged**
