### PR TITLE
Add int 8 and 16 support for TensorArray on GPU.

### PR DESCRIPTION
**Pull request by vcarpani**
This PR adds GPU support for int8, int16 and int32 for TensorArray split, referenced in this Issue https://github.com/tensorflow/tensorflow/issues/28458

### CODE REVIEW

**Comment by vcarpani** [comment]
Bump :)

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Review by ebrevdo — APPROVED** [review]

**Review by ebrevdo — CHANGES_REQUESTED** [review]
Some failing tests.

**Comment by vcarpani** [comment]
I currently have some problem while building Tensorflow related to nccl, will solve as soon as I succeed in building

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by gbaned** [comment]
@vcarpani  Wondering if you still need this PR, if yes can you please check reviewer comments and keep us posted. Thanks!

**Comment by gbaned** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
