### PR TITLE
Handle DT_VARIANT in DataTypeToPrimitiveType.

### PR DESCRIPTION
**Pull request by jakeh-gc**

### CODE REVIEW

**Comment by sanjoy** [comment]
Hi @jakeh-gc,

Can you please state why you need this?

Thanks!

CC @jpienaar @yunxing

**Comment by jpienaar** [comment]
DT_VARIANT types should be handled instead by passes like tensorlist decomposition rather than a blanket mapping to void* IMO. This seems convenient but lossy and creates an ordering dependency.

**Review by sanjoy — CHANGES_REQUESTED** [review]
As per the comment I left on the conversation pane.

**Comment by jakeh-gc** [comment]
Since creating this PR I've created a workaround for this. So I don't think it's needed.

**Pull request closed without merging**
