### PR TITLE
Branch 161478803

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Review by frankchn — APPROVED** [review]

**Comment by caisq** [comment]
@frankchn There are duplicate op definitions in tensorflow/go. I pushed a new commit to try to fix it. Hopefully all tests will pass this time (except the flaky barrier_ops_test on Mac)

**Comment by frankchn** [comment]
Jenkins, test this please.

**Comment by frankchn** [comment]
Thanks @caisq for handling this!

**Comment by caisq** [comment]
This looks new... https://ci.tensorflow.org/job/tensorflow-pull-requests-gpu/5701/console

ERROR: /workspace/tensorflow/stream_executor/BUILD:39:1: undeclared inclusion(s) in rule '//tensorflow/stream_executor:cuda_platform':
this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/cuda/cuda_timer.cc':

Let's try again to see if it is reproducible. @tensorflow-jenkins test this please

**Comment by caisq** [comment]
Looks like the aforementioned error is not 100% reproducible. Could be specific to gpu5-slave. Merging PR.

**Pull request merged**
