### PR TITLE
Improve the shape function of Bincount

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to improve the shape function of Bincount.

In the existing implementation there was not a lot of restriction in shape function of Bincount, and the output shape was unknown. But it is actually possible to get a better shape output if `size` input is known.

This fix adds enhancement to the shape function of Bincount.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by josh11b — CHANGES_REQUESTED** [review]
How about adding a test that verifies this new code is working?

**Comment by yongtang** [comment]
Thanks @josh11b for the review. The PR has been updated with additional test cases added. Please take a look.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 19 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 34 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by martinwicke — APPROVED** [review]

**Pull request merged**
