### PR TITLE
Fix the iOS makefile on tensorflow lite.

### PR DESCRIPTION
**Pull request by croath**
Just make it right.
Ref: https://github.com/tensorflow/tensorflow/issues/15074

### CODE REVIEW

**Review by andrehentz — APPROVED** [review]

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by croath** [comment]
Hi, it seems that it's not this pull request failing the tests. Anything I could do to fix the errors?

**Comment by zzcgumn** [comment]
It build successfully after I downloaded Eigen from https://bitbucket.org/eigen/eigen/get/b6e6d0cf6a77.zip. Hope this helps.

**Comment by croath** [comment]
Closed. Similar pull request that has been merged: https://github.com/tensorflow/tensorflow/pull/15191

**Pull request closed without merging**
