### PR TITLE
test without long test_timeout

### PR DESCRIPTION
**Pull request by jendap**
We should remove --test_timeout=3600.

### CODE REVIEW

**Comment by jendap** [comment]
@martinwicke @vrv do not merge yet, I will remove the bazel clean hack. It will make sure the tests are not cached. I should have used --cache_test_results=no probably. Anyway, we will remove that hack.

**Comment by jendap** [comment]
It has build just fine without insanely long test timeouts. We can merge this. But expect to find some flaky tests in next few builds.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by martinwicke** [comment]
cwise_ops_test is just on the boundary it seems -- runs 295-305s -- should we make that test bigger?

**Comment by jendap** [comment]
How about just increase the sharding - https://github.com/tensorflow/tensorflow/pull/1536/commits/ef3409d0eb76e9f3ec0c181616ab91330f4805b1?

That sharding is actually very cool feature! Bazel is pretty smart :)

**Pull request merged**
