### PR TITLE
[INTEL oneDNN] Enable BF16 support for Round

### PR DESCRIPTION
**Pull request by othakkar**
Added BF16 support for the Round op.

A special if-clause for the round op has been added in the test because the subsequent code computes the gradient of the op, which is zero for the round op (returns None in TF) (https://github.com/tensorflow/tensorflow/issues/5888). Therefore, returning early.

### CODE REVIEW

**Comment by gbaned** [comment]
@penpornk  Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @penpornk Can you please review this PR ? Thank you!

**Comment by othakkar** [comment]
BF16 support for Round op is already included in TF2.10 (https://github.com/tensorflow/tensorflow/commit/057e83dc3e2fd69565067f0dd23a05e45d7131fd). 
Closing this PR to avoid duplication!

**Comment by othakkar** [comment]
Closing this PR as BF16 support was added for Round Op a few days ago (https://github.com/tensorflow/tensorflow/commit/057e83dc3e2fd69565067f0dd23a05e45d7131fd) and opening a new PR having the corresponding python test.

**Pull request closed without merging**
