### PR TITLE
Update to README.md to add more learning material 

### PR DESCRIPTION
**Pull request by abeadam**
Adding additional learning material. Currently the list includes competitors of LinkedIn so in the interest of fairness and providing more options to reader, adding a link to the courses provided by LinkedIn.

### CODE REVIEW

**Comment by saikota** [comment]
Sweet. Shipit.

**Comment by mihaimaruseac** [comment]
3 commits for a single line change? Can you please merge the commits in just one?

In general, we don't want to insert all and every links to the README. There are too many and some don't have the same quality as others. It takes too much time to evaluate the materials, so it is better to only include links that Google has vetted. As such, I don't think this PR is worthwhile.

**Comment by gbaned** [comment]
Hi @mihaimaruseac Can you please review this PR ? Thank you!

**Comment by mihaimaruseac** [comment]
I already reviewed it:

> In general, we don't want to insert all and every links to the README. There are too many and some don't have the same quality as others. It takes too much time to evaluate the materials, so it is better to only include links that Google has vetted. As such, I don't think this PR is worthwhile.

**Comment by gbaned** [comment]
Hi @abeadam Any update on this PR? Please. Thank you!

**Comment by abeadam** [comment]
Thank you for reviewing, it's fine to close the pull request. My hope was to make it slightly fair by including links to a missing Learning provider.

**Pull request closed without merging**
