### PR TITLE
Add the code to request the runtime permission for the camera.

### PR DESCRIPTION
**Pull request by thagikura**
Note that this change requires the bazel to be able to import v13 support
library. Until this issue (https://github.com/bazelbuild/bazel/issues/827) is
fixed, thisc change doesn't build.
(I tested by changing my local bazel setting)

PR for https://github.com/tensorflow/tensorflow/issues/925

### CODE REVIEW

**Comment by jendap** [comment]
The Android build fails. See the links in github status checks. Or wait for an email you will get in 20 minutes ;-)

**Comment by thagikura** [comment]
Added another commit to replace FragmentComapt (which requires v13 support library) by inlined methods.

This should work without depending on v13 support library.

Is it possible to trigger the build again?

**Comment by jendap** [comment]
It is currently building pull requests of all people in google organization automatically. We will disable that soon though.

The android build still failed.

**Comment by thagikura** [comment]
Looks like android-support-v4.jar is missing in the build server.
Is it possible to install the android-support-v4.jar in the server?

If not, I can inline the ContextCompat (which requires android-support-v4.jar) like the way I did for v13 support library.

**Comment by jendap** [comment]
IT would be better if you can avoid that dependency by just a few lines of code. Otherwise we would have to change setup instructions and everybody would have to go go through manual process of launching sdk manager and installing something. Or is it in some public maven repo? If so you can just add it as external dependency in BUILD file.

**Comment by thagikura** [comment]
v4 support library is pretty common for Android developers, but it requires the SDK manager to install.
Ok, I'll inline the code to avoid v4 support library dependency.

**Comment by jendap** [comment]
It is, imho, better to inline it if it is a few lines of code. If it is bigger we can add the dependency.

(if it was in maven central I would have different threshold)

**Comment by thagikura** [comment]
Added another commit to remove the v4 support library dependency.
I think the build in the CI server should be now fixed.

**Comment by jendap** [comment]
LGTM

Thank you!

**Comment by jendap** [comment]
@vrv can we merge this?

**Comment by martinwicke** [comment]
@thagikura can you squash your commits?

**Comment by thagikura** [comment]
Squashed the commits.

**Comment by martinwicke** [comment]
merged.

**Comment by andrewharp** [comment]
Glad to see this go in. FYI there's also "adb install -r -g tensorflow_demo.apk" which will automatically grant permissions upon install (so you don't need to grant manually on every install). Unfortunately there's no way to do this currently directly through bazel, but they are working on it.

**Pull request closed without merging**
