### PR TITLE
Try to make _global_policy thread local

### PR DESCRIPTION
**Pull request by bhack**
As in the source code `TODO` list.
Also we don't want to use not exposed methods in this class from mixed precision tests in https://github.com/tensorflow/addons/pull/1924

### CODE REVIEW

**Comment by reedwm** [comment]
The main issue with making this thread local is that `MirroredStrategy` spawns multiple threads. If the policy is thread local and the policy is updated, the new threads won't see the new values of the policy. If you run the test `//tensorflow/python/keras/mixed_precision/experimental:keras_test`, it should fail due to this issue.

TensorFlow has lots of thread local variables. Normally to get around this, [this class](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/python/distribute/mirrored_run.py;l=242;drc=0f3562ba77d62abef6c55c7c7649f836398dbc6e) copies over the values of the thread local variables from the old thread to the new thread. Unfortunately, we cannot have it copy the value of the Keras policy, since we cannot introduce a new dependency from TensorFlow to Keras.

@guptapriya, @yuefengz, can we introduce an API to allow new thread-local variables to be copied by distribution strategy? Alternatively, perhaps the policy should be kept as a global variable instead of a thread local variable.

**Comment by bhack** [comment]
As an alternative is exporting `policy_scope` safe?

**Comment by reedwm** [comment]
Until the policy is thread-local, `policy_scope` is not thread safe, as it will still be setting a global, non-thread local variable. So I don't think exposing `policy_scope` will solve this issue.

For #1924, since unit tests run sequentially, you don't need to make policy thread-local. The recommend way of setting policies in unit tests is to set the policy back to float32 in the tearDown function, like [here](https://cs.opensource.google/tensorflow/models/+/master:official/nlp/modeling/networks/encoder_scaffold_test.py;l=57;drc=8c408bbeb9142979600fa671e454d001628d1cb7). Then within unit tests, you can set the policy however you wish and it will be set back to float32 before running a new unit test.

**Comment by bhack** [comment]
@reedwm So why [this is working](https://github.com/tensorflow/addons/pull/1924/files#diff-fa100414eab669c5277ea22483702affR132) and instead using exposed API `set_policy` and back was not working?

**Comment by bhack** [comment]
P.s. In the CI we are using `pytest -n` so we are not executing tests on a single process.

**Comment by reedwm** [comment]
It shouldn't make a difference. You can see the source code of [policy_scope](https://github.com/tensorflow/tensorflow/blob/f55ffa1ab219d5b521f9aaea0378463d81ceb778/tensorflow/python/keras/mixed_precision/experimental/policy.py#L568) is simply to set the policy at the start of the scope and set it back at the end. The try-finally is only to make sure it sets it back if an exception is thrown.

I think `pytest -n` runs in separate processes, so each process should have its own value of the global policy. So having this be a global varaible shouldn't matter.

If you give me instructions to reproduce the test I can try running your PR locally to see why `set_policy` does not work and `policy_scope` does work.

**Comment by bhack** [comment]
Yes I also think it is a multiprocess but this flavour was not working https://github.com/tensorflow/addons/blob/fba902866131ea4333c976118cb9f2bc324763e9/tensorflow_addons/optimizers/tests/lookahead_test.py#L131

**Comment by bhack** [comment]
This Is the line for running test https://github.com/tensorflow/addons/blob/master/tools/testing/build_and_run_tests.sh#L38

**Comment by reedwm** [comment]
To fix, replace the line

```
tf.keras.mixed_precision.experimental.global_policy()
```

with

```
tf.keras.mixed_precision.experimental.set_policy("float32")
```

The issue is `global_policy` only returns the global policy without changing it. Setting the global policy back to its default of "float32" fixes the issue.

You should also use a try-finally to ensure the policy is set back to float32:

```python
    try:
        tf.keras.mixed_precision.experimental.set_policy("mixed_float16")
        model = tf.keras.models.Sequential()
        model.add(tf.keras.layers.Dense(input_shape=(3,), units=1))
        model.compile(Lookahead("sgd"), loss="mse")
    finally:
        tf.keras.mixed_precision.experimental.set_policy("float32")
```

This means even if a line in the try-block throws an exception, the policy will still be set back to float32. This logic emulates what the `policy_scope` does.

**Comment by bhack** [comment]
@reedwm Ok that seem to work I remeber that I had `float32` locally and that failed in the CI but probably was something else. 

Waiting here on what we want to do for the multi-thread case.

As a side node do you think that `set_policy()` without argument is handled correctly?

**Comment by reedwm** [comment]
> As a side note do you think that set_policy() without argument is handled correctly?

Can you clarify? `set_policy` requires an argument.

**Comment by bhack** [comment]
Yes sorry  I meant  `None` is not going to set it to global_policy() right?

**Comment by yuefengz** [comment]
> The main issue with making this thread local is that `MirroredStrategy` spawns multiple threads. If the policy is thread local and the policy is updated, the new threads won't see the new values of the policy. If you run the test `//tensorflow/python/keras/mixed_precision/experimental:keras_test`, it should fail due to this issue.
> 
> TensorFlow has lots of thread local variables. Normally to get around this, [this class](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/python/distribute/mirrored_run.py;l=242;drc=0f3562ba77d62abef6c55c7c7649f836398dbc6e) copies over the values of the thread local variables from the old thread to the new thread. Unfortunately, we cannot have it copy the value of the Keras policy, since we cannot introduce a new dependency from TensorFlow to Keras.
> 
> @guptapriya, @yuefengz, can we introduce an API to allow new thread-local variables to be copied by distribution strategy? Alternatively, perhaps the policy should be kept as a global variable instead of a thread local variable.

What API are thinking of? If this would be user-visible change anyway, is it acceptable to set the thread_local object in a `replica_fn`?

**Comment by reedwm** [comment]
Setting the policy instead of `None` instead of `"float32"` means the policy will default to floatx. However, floatx is almost always float32 anyway so in tests, I just set back to "float32" for simplicity. `None` works equally as well.

> What API are you thinking of? If this would be user-visible change anyway, is it acceptable to set the thread_local object in a replica_fn?

I don't think the policy should ever be set in a replica_fn (we should probably raise an error if this is done). But it will definitely be set outsdie a replica_fn and retrieved in a replica_fn.

I'm thinking we should have a `tf.distribute.register_thread_local(thread_local) that takes in a `threading.local` object. Then when MirroredStrategy spawns threads, it would copy over the attributes of the thread local object to the new thread.

**Comment by yuefengz** [comment]
`tf.distribute.register_thread_local(thread_local)` would introduce some global states to `tf.distribute`, which might be fine given mixed precision is global as well.

What is the problem with setting thread local in a `replica_fn`? Could adding an argument to `run` as an option?

**Comment by reedwm** [comment]
I think introducing global state is necessary if we want the policy to be thread-local.

> What is the problem with setting thread local in a replica_fn? Could adding an argument to run as an option?

If a thread in a replica_fn sets a thread local variable, does it remain set outside the replica_fn? If so, what happens if different threads set it to different values? If not, it may cause confusion if the thread local variable is changed but then is unchanged outside the replica_fn.

As a solution, we could allow it to be set in a replica_fn, but require it to be set to it's original value by the time the replica_fn ends. This allows scopes like `policy_scope` to be used in a replica_fn (if we expose `policy_scope`)

**Comment by bhack** [comment]
I am thinking about to try to not expose new user interfaces but I don't know deeply the complete flow of these internals. 
Is there a way to identify that we are inside a `MirroredStrategy` thread?

**Comment by bhack** [comment]
> f the policy is thread local and the policy is updated, the new threads won't see the new values of the policy. If you run the test //tensorflow/python/keras/mixed_precision/experimental:keras_test, it should fail due to this issue.

@reedwm I ran `bazel test //tensorflow/python/keras/mixed_precision/experimental:keras_test` on this branch but the test is passing. What I need to do to let it fail?

**Comment by reedwm** [comment]
I was mistaken, `keras_test` does not run into this issue. To reproduce, a layer needs to be created inside a function passed to `MirroredStrategy.run`, which `keras_test` does not do. A natural way to reproduce the issue is by creating another layer in `build()`, which will be called in  `MirroredStrategy.run`. For example:

```python
from absl import app
import tensorflow as tf

# Represents two sequential dense layers.
class DoubleDense(tf.keras.layers.Layer):

  def build(self, _):
    self.dense1 = tf.keras.layers.Dense(10)
    self.dense2 = tf.keras.layers.Dense(10)

  def call(self, inputs):
    y = self.dense1(inputs)
    return self.dense2(y)


def main(_):

  # Create two logical CPUs so that we can use a multi-device mirrored strategy
  (cpu,) = tf.config.list_physical_devices('CPU')
  tf.config.set_logical_device_configuration(
      cpu, [tf.config.LogicalDeviceConfiguration(),
            tf.config.LogicalDeviceConfiguration()])

  # Run the model
  tf.keras.mixed_precision.experimental.set_policy('mixed_float16')
  with tf.distribute.MirroredStrategy(['/cpu:0', '/cpu:1']).scope() as strategy:
    layer = DoubleDense()
    def run_fn():
      x = tf.ones((10, 10))
      y = layer(x)
      assert y.dtype == tf.float16, 'y has dtype: %s' % (y.dtype.name,)
      return y
    strategy.run(run_fn)


if __name__ == '__main__':
  app.run(main)
```

In this example, if policy is thread-local, the two `Dense` layers will not see the fact the policy is updated to `'mixed_float16'`. 

With this PR, the example gives the error `AttributeError: '_thread._local' object has no attribute '_global_policy'`, since `thread_local._global_policy` is only set on the main thread. This is typically solved by a hasattr check, as in done [here](https://github.com/tensorflow/tensorflow/blob/821d1b087be221aa3c58be8e077d4553d6851ef2/tensorflow/python/distribute/cross_device_utils.py#L280), but that will not solve the main issue in that the `Dense` layers do not see that the policy is updated to `'mixed_float16'`.

**Comment by yuefengz** [comment]
> I am thinking about to try to not expose new user interfaces but I don't know deeply the complete flow of these internals.
> Is there a way to identify that we are inside a `MirroredStrategy` thread?

If `tf.distribute.get_replica_context()` is None, then we are inside a `MirroredStrategy` thread.

**Comment by bhack** [comment]
> If `tf.distribute.get_replica_context()` is None, then we are inside a `MirroredStrategy` thread.

@yuefengz Also the coordinator is in a new thread how can I check that I am inside a coordinator?

**Comment by bhack** [comment]
I've done a small hack but I am not sure if it could cover "distributed" spawned threads.

**Comment by reedwm** [comment]
The hack helps, but there are still cases where it won't work properly, such as if a user spawns their own threads or if a user sets the policy inside a `MirroredStrategy` thread.

I think for now, we should keep the policy as a global variable. I do not see a strong use case for making this thread local yet. The primary use case would be to set the policy in a `MirroredStrategy` thread, but I'm not sure why a user would do that (we should probably raise an error if they try). If we do find a use case for making it thread local, we can add a `tf.distribute.register_thread_local` function in order to make the policy thread-local.

I'm closing this PR for now. @bhack, sorry for the misleading TODO. If you want, you can create a PR to raise an error if the `set_policy` is called in a `MirroredStrategy` thread. Otherwise I can implement this.

**Comment by bhack** [comment]
@reedwm What about two python threads launching two models one with mixed_precision policy and the other one without it?
What is the behavior in this case?

**Pull request closed without merging**
