### PR TITLE
[determinism] Add v2.8 release notes

### PR DESCRIPTION
**Pull request by duncanriach**
Add op-determinism changes to the version 2.8 release notes in the master branch (prior to the r2.8 branch cut).

@reedwm, please will you review. This is not much different than the notes for version 2.7. I'm wondering if there any additional enhancements in version 2.8 that I'm not yet aware of.

### CODE REVIEW

**Comment by reedwm** [comment]
Yesterday I added a brief section in the release notes, in d5b368107de08b6b55b6685b4eec72dab1b8e677, but it doesn't list the 2.7 changes. I don't think it is worth listing the 2.7 changes for TF 2.8 despite having not listing them in the TF 2.7 release, since there are no known ops that are nondeterministic and do not raise an error. So users don't need to be aware of which ops are nondeterministic by reading the release notes, because they all should be deterministic. Granted, there are almost certainly bugs that still will cause nondeterminism, but hopefully such bugs will be rare.

I have a small XLA change that makes XLA aware of the TF global determinism variable, which will allow determinism to work correctly when `tf.function(jit_compile=True)` is used. I'm hoping it will be submitted within an hour of now, by the branch cut, and I'll let you know when it is submitted. I also added exceptions to some FakeQuant ops in ae1581faa8d7f24d7974c4021394bc559ed6110b. Unfortunately, my changes to make tf.data faster with determinism haven't landed yet.

Anyway, I'm happy to use your wording of the release notes, or keep my wording, but I don't think we should list 2.7 changes. It does make sense to mention the 2.8 changes though, so feel free to add those in, whether we go with my wording or yours.

**Comment by reedwm** [comment]
> I'm hoping it will be submitted within an hour of now, by the branch cut, and I'll let you know when it is submitted.

Actually looks like the change already landed 5 minutes ago, in 4dc6d4d59008b4558040afa1a5a5993f583bb48e.

**Comment by duncanriach** [comment]
@reedwm, I'm sorry I missed your addition to the release notes.

I have merged your change with mine in this PR. I have also added notes about the two changes you listed above. Thank you for sharing. I put it in the "Major Features and Improvements" section because it's a new, official API feature.

When possible, I would like to document the incremental changes for this functionality in the release notes. For example, some users are likely going to care, going forward, when an exception is replaced with an implementation. Also, if it makes sense to include the changes that are 2.8-specific then why not include the changes that were not reported for the 2.7 release? I tend to err on the side of being detail-oriented about tracking and reporting these changes because I'm trying to make this functionality as explicit and thoroughly documented as possible (for those who care), to minimize potential confusion.

**Comment by reedwm** [comment]
Agreed we should document incremental changes. I was a bit reluctant to include 2.7 changes in the 2.8 release notes, but you're right that this makes sense since we didn't report them in 2.7.

I pushed a commit to this PR that keeps the `enable_op_determinism` function in the "Major Features" section but moves the individual op changes to the "Bug Fixes and Other Changes" section. Since determinism was previously inaccessible through a public API, the entirety of the determinism work can be considered a major new feature, so it's not worth listing the individual determinism changes in that section IMO.

**Review by reedwm — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
We cut the branch for TF 2.8 now. Can you rebase this on r2.8 branch?

Apologies for the conflict, but if we keep this against master then the changes will be missed after the release when we merge the release notes from the branch back into master.

**Comment by reedwm** [comment]
I think the PR author may be offline until January, and I'm not sure if it's possible for me to rebase a PR that I didn't author (although I can create commits). Can I create a cherrypick into 2.8 instead?

If necessary, I can create a new PR as well.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Yes, let's land in master and then do a cherrypick. Sorry it needs extra work, I should have checked these a few days ago

**Comment by duncanriach** [comment]
Thank you, @reedwm. Nice improvements. Also, thanks for making that cherry-pick happen. Note that some of the indentation got lost somewhere, which PR [53720](https://github.com/tensorflow/tensorflow/pull/53720) addresses.

**Pull request merged**
