### PR TITLE
 Adding GANAuxiliaryLoss

### PR DESCRIPTION
**Pull request by isaacnoble**
Add a new namedtuple to contain the auxiliary loss settings.
Add a named argument to GANEstimator constructor,
so that GANEstimator can make use of auxiliary losses.

### CODE REVIEW

**Comment by isaacnoble** [comment]
Use work e-mail on one of the commit, re-signed cla from work account.

**Comment by joel-shor** [comment]
The ability to use special TF-GAN behavior with GANEstimator will be added when tensorflow_gan is released as its own repo. I'm just waiting for internal approval. @martinwicke

**Comment by isaacnoble** [comment]
Any estimate on a time frame? I was also going to make a pull request to better control what is returned from GANEstimator.predict, should I hold off on that as well?

**Comment by joel-shor** [comment]
The code has been ready to be pushed for over a month, but we're waiting on an internal process. Sorry I can't be more specific on timeframe. @martinwicke for more detail.

Perhaps in the meantime you could make local code changes for whatever you're working on, and you can switch to the new version when it becomes available (it's a bit cleaner, too). Once that's available, I *would* really appreciate a PR giving finer control over the generator output. Sound reasonable?

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by MarkDaoust** [comment]
The `tf.contrib` submodule will not be part of tensorflow after the `2.0` release.

It looks like the [tensorflow_gan repo is up](https://github.com/tensorflow/gan).

So please remake this PR on that repo. 


Thanks.

**Pull request closed without merging**
