### PR TITLE
Enable contrib/opt/external_optimizer in eager mode

### PR DESCRIPTION
**Pull request by yupbank**
Add a new interface that is eager compatible.  

Which requires both loss and equalities/inequalities passed in as a function

Addresses https://github.com/tensorflow/tensorflow/issues/23973

### CODE REVIEW

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @alextp, @strategist333: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Review by alextp — CHANGES_REQUESTED** [review]
Can we modify the existing external optimizer instead of adding a new one?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

**Comment by rthadur** [comment]
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

**Pull request closed without merging**
