### PR TITLE
[TF-TRT] Add parameter to the rewriter config to disable the optimization of the function library.

### PR DESCRIPTION
**Pull request by Nyrio**
This is a simpler replacement for #53114. What we want for now is to avoid running optimizations on the segments after segmentation by TF-TRT. This is equivalent to disabling optimization of the function library.

There is a setting for that in `GrapplerItem::OptimizationOptions`: `optimize_function_library`, but I'm not sure if there's any proper way to control that from the Python configuration, so I create an option in the rewriter config to override it. If there's a better way of doing that, please let me know and I'll be happy to change this PR.

### CODE REVIEW

**Comment by gbaned** [comment]
@bixia1 Can you please review this PR ? Thank you!

**Comment by Nyrio** [comment]
Indeed, I was wrongly assuming that all functions were inlined prior to running Grappler with this flag, but it is possible to mark some functions so that they won't be inlined and mark them as needing to be processed by the TF-TRT optimization pass. [tf_function_test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/compiler/tensorrt/test/tf_function_test.py) should fail with this change.

@tfeher @bixia1 Should we abandon the idea of disabling optimization of the segments for now or fix this parameter to be more TF-TRT specific e.g skip the functions only if their name indicates they correspond to TRT segments?

**Comment by gbaned** [comment]
@tfeher @bixia1 Can you please assist on above comments from @Nyrio. Thank you!

**Comment by bixia1** [comment]
If we indeed need to disable opts for functions associated with TRTEngineOp, we have to limit this to such functions in order to continue support conversion of user requested functions.

**Comment by Nyrio** [comment]
We decided that we don't need this functionality at the moment, so let's close this PR instead of reworking it using the function names.

**Pull request closed without merging**
