### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by GoodDaisy**

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @GoodDaisy Can you please sign CLA. Thank you!

**Comment by GoodDaisy** [comment]
@gbaned I found that my github's email was not the same as google email...Is there any way to resolve it?

**Comment by mihaimaruseac** [comment]
You'll have to sign the CLA with the noreply email too.

**Comment by GoodDaisy** [comment]
> You'll have to sign the CLA with the noreply email too.

Could you tell me how to sign the CLA with the github noreply email? Thank you very much.

**Comment by mihaimaruseac** [comment]
> > You'll have to sign the CLA with the noreply email too.
> 
> Could you tell me how to sign the CLA with the github noreply email? Thank you very much.

See https://cla.developers.google.com/about for full details

Reading it, I think this applies (but please read the full page to make sure):

> Your contribution (commit) must be associated with at least one of:
>
> * The primary email on your Google Account associated with the signed CLA.
> * An Alternate email on your Google Account associated with the signed CLA. See and modify your aternate emails at https://myaccount.google.com/alternateemail.
> * The GitHub username associated with the signed CLA.

**Comment by GoodDaisy** [comment]
When I added, it failed and showed that xxxx@users.noreply.github.com was not a valid email address...

**Review by kartiksain — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
I think in this case, you'll have to use your real email :( (a fake one created just for this and attached to your github profile should also work).

**Comment by gbaned** [comment]
Hi @GoodDaisy  Any update on this PR? Please. Thank you!

**Comment by GoodDaisy** [comment]
I am sorry that I have to close it since I can't solve the CLA. Thank you for your all helps.

**Pull request closed without merging**
