### PR TITLE
Eigen BiasAdd and BiasAddGrad Fix for NCHW Format.

### PR DESCRIPTION
**Pull request by mdfaijul**

### CODE REVIEW

**Comment by sb2nov** [comment]
@benoitsteiner please review

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by mdfaijul** [comment]
@sb2nov: Any update on  pull request. Looks like some permission issues. For example:

rm: cannot remove '/workspace/tensorflow/contrib/makefile/gen/obj/tensorflow/core/framework/op_def.pb_text.o': Permission denied
........................

Let me know if anything from my side need to be done.

**Comment by sb2nov** [comment]
Ah that is just a flake so kicking off the tests again

Jenkins, test this please.

**Comment by vivek-rane** [comment]
@mdfaijul @sb2nov Looks like the same issue again on "Linux CPU tests makefile" (permission denied). Could it be an issue with the environment or docker image?

**Comment by sb2nov** [comment]
I think that is known issue with the testing environment. @gunan helped with it a while back.

Going to try to re-run once more. 

Jenkins, test this please.

**Comment by vivek-rane** [comment]
@sb2nov @benoitsteiner The unit tests have passed - do let me or @mdfaijul know if there's any review changes blocking the merge.

**Review by benoitsteiner — APPROVED** [review]

**Pull request merged**
