### PR TITLE
Clean coding.cc

### PR DESCRIPTION
**Pull request by kingofthebongo2008**
Fix of a compile time issue

### CODE REVIEW

**Comment by yifeif** [comment]
@kingofthebongo2008 are the changes in the cmake files supposed to be part of this PR?

**Comment by kingofthebongo2008** [comment]
Hey,

No actually.

I just created several pull requests and created local branches after
finishing every task, this is why probably they appear one after the other.
I am relatively new to git so i may have created the branches wrong.

**Comment by yifeif** [comment]
@kingofthebongo2008 thanks for contributing to TF :). Do you mind double checking your PRs to make sure the commits only contain the changes that are relevant to each PR?

**Comment by kingofthebongo2008** [comment]
what should i do in general,
There are a couple of pr in groups, split them somehow?
which git commands should i use

**Comment by yifeif** [comment]
@kingofthebongo2008 you might want to create separate branches with [`git checkout`](https://git-scm.com/docs/git-checkout) for each PR, and [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick) the commits you want to each of the branches.
Do you mind closing the existing stacked PRs and sending us the new ones?

**Comment by yifeif** [comment]
@kingofthebongo2008 I'm closing this and a bunch of stacked PRs for now. Feel free to send us new ones when you have them ready. Thank you!

**Pull request closed without merging**
