### PR TITLE
[tf.data] graduate experimental `group_by_window` API to tf.data.Dataset

### PR DESCRIPTION
**Pull request by kvignesh1420**
UPDATED: This PR graduates the `tf.data.experimental.group_by_window` API into `tf.data.Dataset.group_by_window` by making the following changes:

 - [x] Adds the deprecation decorator for the experimental API.
 - [x] Adds the necessary `group_by_window` method to `DatasetV2` class.
 - [x] Updates example in documentation with new API.
 - [x] Regenerate golden API's.
 - [x] Moved and updated the `group_by_window` test target from experimental/kernel_tests to kernel_tests
 - [x] Updated the RELEASE.md file

TEST LOG
```
INFO: Build completed successfully, 346 total actions
//tensorflow/python/data/kernel_tests:group_by_window_test               PASSED in 4.8s
  Stats over 4 runs: max = 4.8s, min = 3.0s, avg = 4.2s, dev = 0.7s
```

This is a pre-requisite for https://github.com/tensorflow/tensorflow/pull/48110.
cc: @jsimsa

### CODE REVIEW

**Review by jsimsa — APPROVED** [review]

**Review by jsimsa — APPROVED** [review]

**Comment by kvignesh1420** [comment]
@jsimsa seems like the internal builds were failing due to an API call mismatch from `grouping.group_by_window` to `Dataset.group_by_window`. This commit addresses the issue.

**Review by jsimsa — APPROVED** [review]

**Comment by kvignesh1420** [comment]
All the tests are passing now!

**Comment by jsimsa** [comment]
Similarly to the `get_single_element` API, could we move the tests for `group_by_window` out of the experimental directory and update it to use the non-experimental API? Thanks.

**Comment by kvignesh1420** [comment]
@jsimsa done! Updated the PR description as well.

**Review by jsimsa — APPROVED** [review]

**Comment by jsimsa** [comment]
Similar to my `get_single_element` comment, please update https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md adding the following item there: "promoting `tf.data.experimental.group_by_window` API to `tf.data.Dataset.group_by_window` and deprecating the experimental endpoint"

**Comment by gbaned** [comment]
@kvignesh1420 Can you please check @jsimsa's comments and keep us posted ? Thanks!

**Comment by kvignesh1420** [comment]
@gbaned as per the discussion in https://github.com/tensorflow/tensorflow/pull/48048, this PR will update the `RELEASE.md` file and conflict with https://github.com/tensorflow/tensorflow/pull/48048, thus I was waiting for https://github.com/tensorflow/tensorflow/pull/48048 to be merged first.

**Comment by kvignesh1420** [comment]
@jsimsa the conflicts have been resolved and the RELEASE.md file has been updated as well!

**Review by jsimsa — APPROVED** [review]

**Comment by kvignesh1420** [comment]
@jsimsa seems like there are internal failures, please let me know if anything needs to be fixed!

**Comment by jsimsa** [comment]
yes, working on resolving these manually myself but today is a busy day

**Comment by kvignesh1420** [comment]
@jsimsa  Sure, np!
Also, I understand that the checks are internal to google but can you please let me know (whenever you find some time) where the failures occurred (if allowed by google's BCG)? This will help in future PRs for graduating other APIs. Thanks again.

**Comment by jsimsa** [comment]
doctests are failing with:

```
FAIL: group_by_window (google3.third_party.tensorflow.python.data.ops.dataset_ops.DatasetV2)
Doctest: google3.third_party.tensorflow.python.data.ops.dataset_ops.DatasetV2.group_by_window
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<embedded stdlib>/doctest.py", line 2199, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for google3.third_party.tensorflow.python.data.ops.dataset_ops.DatasetV2.group_by_window
  File "/build/work/56bb78db693a83f9c5641e125d68a438167d/google3/runfiles/google3/third_party/tensorflow/python/data/ops/dataset_ops.py", line 2524, in group_by_window

----------------------------------------------------------------------
File "/build/work/56bb78db693a83f9c5641e125d68a438167d/google3/runfiles/google3/third_party/tensorflow/python/data/ops/dataset_ops.py", line 2539, in google3.third_party.tensorflow.python.data.ops.dataset_ops.DatasetV2.group_by_window
Failed example:
    reduce_func = reduce_func=lambda key, dataset:
Exception raised:
    Traceback (most recent call last):
      File "<embedded stdlib>/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest google3.third_party.tensorflow.python.data.ops.dataset_ops.DatasetV2.group_by_window[3]>", line 1
        reduce_func = reduce_func=lambda key, dataset:
                                                     ^
    SyntaxError: invalid syntax
----------------------------------------------------------------------
File "/build/work/56bb78db693a83f9c5641e125d68a438167d/google3/runfiles/google3/third_party/tensorflow/python/data/ops/dataset_ops.py", line 2541, in google3.third_party.tensorflow.python.data.ops.dataset_ops.DatasetV2.group_by_window
Failed example:
    dataset = dataset.group_by_window(
              key_func=key_func,
              reduce_func=reduce_func,
              window_size=window_size)
Exception raised:
    Traceback (most recent call last):
      File "<embedded stdlib>/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest google3.third_party.tensorflow.python.data.ops.dataset_ops.DatasetV2.group_by_window[4]>", line 3, in <module>
        reduce_func=reduce_func,
    NameError: name 'reduce_func' is not defined
----------------------------------------------------------------------
File "/build/work/56bb78db693a83f9c5641e125d68a438167d/google3/runfiles/google3/third_party/tensorflow/python/data/ops/dataset_ops.py", line 2545, in google3.third_party.tensorflow.python.data.ops.dataset_ops.DatasetV2.group_by_window
Failed example:
    for elem in dataset.as_numpy_iterator():
      print(elem)
Expected:
    [0 2 4 6 8]
    [1 3 5 7 9]
Got:
    0
    1
    2
    3
    4
    5
    6
    7
    8
    9
```

**Comment by kvignesh1420** [comment]
@jsimsa fixed the docstring issue and resolved conflicts.

**Review by jsimsa — APPROVED** [review]

**Comment by rthadur** [comment]
Seems auto-merge is not happening but the changes are now committed so we can close this. Thank you for the PR.

**Pull request closed without merging**
