### PR TITLE
Dynload

### PR DESCRIPTION
**Pull request by pkit**
Unify `tensorflow` and `tensorflow_gpu` into single package
See #22562 and #16184
As a person who started all that (original patch [here](https://gist.github.com/pkit/e06c2d23046a265a4f0fea302a5ce539)) I will take it to the finish line, hopefully.

### CODE REVIEW

**Comment by rthadur** [comment]
@pkit can you please sign CLA

**Comment by pkit** [comment]
@rthadur already signed, you cannot submit PR if not signed...
"The bad news is that it appears that one or more commits were authored or co-authored by someone other than the pull request submitter"
I.e. the bot is not smart enough to understand that @superbobry is another author of a connected PR.

**Comment by superbobry** [comment]
@pkit thanks for doing this! Have you looked into the remaining cudart dependencies? I am still not sure if these can be safely removed.

**Comment by pkit** [comment]
@superbobry yep, looked into it, doing it right now.
We have some cublas and cusolver leftovers in kernel solvers. Treating these first.
Most of the cudart references are a red herring, essentially there are only 3 major places where it's used and mostly for memory management. I will isolate all the cudart MM into a wrapper object (similar to cupti wrapper) and point all the core/platform stuff there.
There seems to be some contrib stuff doing direct cuda MM, but these are easily treated once core wrapper is set up.

**Comment by pkit** [comment]
Oh, yeah!
```
$ nm -C -u ./tensorflow-1.12.0.data/purelib/tensorflow/python/_pywrap_tensorflow_internal.so | grep '@@libcu' 
$
```

**Comment by gunan** [comment]
@yifeif please take a look at this PR.
@yifeif has a few changes in flight internally, there may be some conflicts in the next few days.

**Comment by yifeif** [comment]
Thanks @pkit and @gunan. I have a pending change that does something similar to this PR, but also handles a few things so that it would work internally as well. Will drop a note once that is submitted.

**Comment by pkit** [comment]
@yifeif 6 days passed, should I continue and rebase, or you will handle it?
I will close the PR then.

**Comment by yifeif** [comment]
hi @pkit, the latest change that got pushed should remove cuda driver dynamic linking. I'm working on removing cuda runtime.

**Comment by pkit** [comment]
@yifeif I can read the code, thanks :)
If you're going to remove `libcudart`, `libcusolver` and last bits of `libcublas` from everywhere then probably this PR has no meaning. And needs to be closed.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @Artem-B, @yifeif, @timshen91: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by Artem-B** [comment]
Is this patch still relevant?

**Comment by gunan** [comment]
@yifeif Do we still need this patch, or should we close the PR?

**Comment by yifeif** [comment]
All the explicit dependency of cuda has been removed from core. @pkit I'll close this PR. If you are looking into removing the rest, let's open discuss in a new thread/PR. @gunan is also looking into dynamically load the kernels, so we might not need to wrap kernel's cuda usage.

**Comment by pkit** [comment]
@yifeif originally I needed only the `libcuda` out. Any additional things were just "nice to have", to make the deploy easier. So I'm good for now.

**Pull request closed without merging**
