### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by melvinljy96**
Add new links and descriptions about Tensorflow. The reasons is to make it more user-friendly and provide more informations to all the users so that they can get the informations quickly and learn more faster. I hope this would help all the communities and users.

### CODE REVIEW

**Comment by melvinljy96** [comment]
Thank you for your useful information. I signed it.

**Comment by melvinljy96** [comment]
Good day sir, may I know when will it be merged?
Your kind consideration is highly appreciated.
Thank you for your attention.

**Review by ctrlaltvikas — CHANGES_REQUESTED** [review]
Could you please arrange them alphabetically? will be good to have that way.

**Comment by melvinljy96** [comment]
I'm sorry for the late reply sir. I have arranged all the links alphabetically. Thank you for your attention.

**Review by av8ramit — APPROVED** [review]

**Pull request merged**
