### PR TITLE
Apply 1.4.2 patch update

### PR DESCRIPTION
**Pull request by angerson**
This PR applies the patches requested for the 1.4.2 patch release, and updates the version strings accordingly.

### CODE REVIEW

**Review by gunan — APPROVED** [review]

**Review by av8ramit — APPROVED** [review]

**Comment by angersson** [comment]
The internal CIs are failing with messages like this:

```
ERROR: /tmpfs/src/github/tensorflow/WORKSPACE:15:1: Traceback (most recent call last):
	File "/tmpfs/src/github/tensorflow/WORKSPACE", line 15
		closure_repositories()
	File "/tmpfs/tmp/bazel/external/io_bazel_rules_closure/closure/repositories.bzl", line 69, in closure_repositories
		_check_bazel_version("Closure Rules", "0.4.5")
	File "/tmpfs/tmp/bazel/external/io_bazel_rules_closure/closure/repositories.bzl", line 172, in _check_bazel_version
		fail(("%s requires Bazel >=%s but was...)))
Closure Rules requires Bazel >=0.4.5 but was 0.10.0
ERROR: Error evaluating WORKSPACE file
```

10 is larger than 4 (usually). Is there a cherry-pick we're missing?

**Comment by gunan** [comment]
I think the root cause is most of the Internal CI machines are upgraded, this branch was using older configs and jenkins. I think we will need to manually trigger tests on this PR using jenkins, I will look into that.

**Comment by angersson** [comment]
@gunan Ping; what can I do to help push this through?

**Comment by gunan** [comment]
1.5.1 is our. we can proceed with this as soon as 1.7 is complete.

**Pull request merged**
