### PR TITLE
Gradient and unit test for MatrixTriangularSolve and BatchMatrixTriangularSolve ops

### PR DESCRIPTION
**Pull request by alexggmatthews**
See issue #1875 for some discussion with @girving .

### CODE REVIEW

**Comment by gunan** [comment]
Can one of the admins verify this patch?

**Comment by alexggmatthews** [comment]
@rmlarsen What do you think of this one? Would you like me to update it? I notice the linalg_grad unit test has had some work recently.

**Comment by rmlarsen** [comment]
Hi,

Thanks for submitting the PR. I just submitted similar code with gradients
for {batch_}matrix_solve, {batch_}triangular_solve, and
batch_matrix_determinant. So this is probably not necessary anymore.

Cheers,
  Rasmus

**Comment by alexggmatthews** [comment]
Hi Rasmus, Great. Thanks for letting me know. I hope the code helped. Alex

**Comment by rmlarsen** [comment]
I actually didn't see your PR until after I submitted, but as you know "all great minds think alike", or the math only has one solution... or something... ;-)

**Pull request closed without merging**
