### PR TITLE
Remove local_run in Experiment

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by rmlarsen** [comment]
@martinwicke this changes the API by removing "local_eval_frequency", can you review, please?

**Comment by terrytangyuan** [comment]
This has been deprecated for months so I think it would be safe to remove it. It would be better if there's internal deprecation tracking for removal dates and the person who's responsible for removal on time.

**Comment by martinwicke** [comment]
Yes, the dates were a mistake.

**Comment by rmlarsen** [comment]
@martinwicke does this mean you approve of this change or not :-)

**Comment by martinwicke** [comment]
Taking the train. Will ​update when I've arrived.

**Comment by terrytangyuan** [comment]
@tensorflow-jenkins Test this please

**Comment by terrytangyuan** [comment]
Ping! Could this be merged?

**Comment by martinwicke** [comment]
This will break a bunch of things internally. We're planning some reorganization of this anyway, so let's leave it as is. Removing things is fiendishly hard. Better not to try without access to the internal tests. :(

**Pull request closed without merging**
