### PR TITLE
Branch 125511710

### PR DESCRIPTION
**Pull request by maciekcc**

### CODE REVIEW

**Comment by vrv** [comment]
ignore the bad cla check, it seems to fail sometimes on large lists of commits

@willnorris

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Comment by maciekcc** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
Jenkins is overloaded, and it was running 2 builds for this PR. I cancelled one of those, but the latest started one is still running.
The one run I cancelled had these two tests failing:
http://ci.tensorflow.org/job/tensorflow-pull-requests-mac/991/console
http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/818/console

**Pull request closed without merging**
