### PR TITLE
Branch 193411332

### PR DESCRIPTION
**Pull request by yifeif**

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]

**Comment by yifeif** [comment]
cc: @jlebar

**Comment by martinwicke** [comment]
What should we do here? @jlebar should we disable the test or can it be fixed easily?

**Comment by jlebar** [comment]
> What should we do here? @jlebar should we disable the test or can it be fixed easily?

I am actively looking at it.  So far it's been half a day since I've been notified that there is a test failure here.

My current status is tracked in b/78290751.

**Comment by jlebar** [comment]
This is a BUILD file problem.  I have a fix and am currently running it through our presubmits.

**Comment by martinwicke** [comment]
Thank you for investigating and fixing this. This PR is replaced by a newer merge.

**Pull request closed without merging**
