### PR TITLE
Issue 1702

### PR DESCRIPTION
**Pull request by guotong1988**
Sorry I make a mistake. I should create a branch in my repo in order to contribute.
would you please close https://github.com/tensorflow/tensorflow/pull/4873

### CODE REVIEW

**Review by keveman — COMMENTED** [review]
There are bunch of code formatting issues, and some commented out code. Is this PR ready for review? Can you please follow the coding guidelines at https://google.github.io/styleguide/cppguide.html to format your code?

**Comment by guotong1988** [comment]
OK , I will read it and edit the format.

**Comment by guotong1988** [comment]
@keveman Do you have a python code format doc? Thank you .

**Comment by drpngx** [comment]
@guotong1988 moved this to #5026.

**Pull request closed without merging**
