### PR TITLE
Enable graph-level multiple streams execution.

### PR DESCRIPTION
**Pull request by buptzyb**
This works as the basic implementation of the whole multi-stream feature, which is proposed in this [PR](https://github.com/tensorflow/tensorflow/pull/59843).

Multi-stream greatly speed up the execution of the model in high concurrency scenarios by putting different queries on different stream groups. The total number of stream groups to create can be set via the environment variable `TF_GPU_STREAM_GROUP_COUNT=N`, where `N` is a positive integer.

### CODE REVIEW

**Comment by pjannaty** [comment]
See some related documentation here: https://docs.google.com/document/d/1yL3lWk_iFKqLTyekkuaiKXZ78I0lPmD5kM1fghHRs4Y/edit

**Comment by eyalhir74** [comment]
@pjannaty @buptzyb 
Whats the status of this effort? was it merged? is there some other built-in TF solution for this?

**Comment by buptzyb** [comment]
@eyalhir74 This PR is closed. We plan to use a series of PRs to merge it. Two open PRs are #68497 and #68500 now. @changhuilin 
to comment.

**Comment by eyalhir74** [comment]
@buptzyb @changhuilin  thanks a lot! any ETA?

**Comment by eyalhir74** [comment]
@buptzyb ok so another question.. How do I actually test this locally on my side? do I need both PRs or 68500 is just for management (not needed).. anyway, maybe I don't fully understand the code - but how exactly do I cause the code to use multiple stream groups using the code in those two PRs?

thanks!

**Comment by buptzyb** [comment]
@eyalhir74 Please see this [branch](https://github.com/buptzyb/tensorflow_multistream/tree/v2.13.1%2Bmultistream-r24.08) (This is a private repo, you should have received the invitation). We have the full multistream feature maintained in this branch based on TF 2.13.1. Examples and README are in [examples/multistream/](https://github.com/buptzyb/tensorflow_multistream/tree/v2.13.1%2Bmultistream-r24.08/tensorflow/examples/multistream). Contact me (robinz@nvidia.com) if you have more questions.

**Comment by eyalhir74** [comment]
Thanks a lot @buptzyb , sent you an email via my work mail at Taboola.

**Comment by unwrittenspectacle** [comment]
This change is closing an architecturally fundamental hole in the TF GPU executor. What seems to be stopping this and related PRs from merging? @buptzyb , is the private repo you have the only way? Do we have customers running your private fork at internet scale in production?

**Comment by buptzyb** [comment]
Yes, referring to our private repo is the recommended way. Merging it to TF seems to be going slow.

**Pull request closed without merging**
