### PR TITLE
Use FindOpenMP instead of custom code

### PR DESCRIPTION
**Pull request by bstriner**
As suggested by @fo40225 , this switches from custom code to FindOpenMP. Seems to have been in CMake since at least 3.0. FindOpenMP would be preferred to anything custom. However, this might break the build for anyone still on CMake 2. Is that a supported configuration or something to not worry about?

@gunan This also adds a flag to enable or disable OpenMP. Default is ON but it will warn and disable if not found. This maintains current functionality for existing builds that expect OpenMP but gives the option of disabling.

@fo40225 , I saw you had a couple other ideas about changes to CMake. Were you going to put together a PR with your other changes?

### CODE REVIEW

**Comment by fo40225** [comment]
@bstriner

https://github.com/bstriner/tensorflow/blob/2fa2407ca68e24f3a9aed885ae420de932640264/tensorflow/contrib/cmake/CMakeLists.txt#L2

tensorflow require CMake at least 3.5, no worry about CMake 2.

I'd like to create PR for my refactoring, but it needs more testing. Building tensorflow once take too long.

**Comment by bstriner** [comment]
@fo40225 BTW, did you try clcache? Could make the builds a little faster, especially if you're rebuilding. Might need to make the cache huge to get full benefit though.

https://github.com/tensorflow/tensorflow/pull/19099

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 50 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 65 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 80 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 95 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by case540** [comment]
Thanks for the PR.

Closing PR since our cmake build is now deprecated. Please switch to building with Bazel if possible. Thanks!

**Pull request closed without merging**
