### PR TITLE
fix broken links, add links check to sanity

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please.

**Review by yifeif — APPROVED** [review]
Thanks @zasdfgbnm!

**Comment by zasdfgbnm** [comment]
some unrelated fails

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by zasdfgbnm** [comment]
There seems to be a newly introduced broken link in `export.md` and it is fixed now. Could any of the admin let Jenkins rerun the test?

**Comment by jhseu** [comment]
Jenkins, test this please

**Pull request merged**
