### PR TITLE
added flatc to third_party

### PR DESCRIPTION
**Pull request by Namburger**
this is to help assists people who are having problem running visualize.py

### CODE REVIEW

**Comment by Namburger** [comment]
@googlebot I signed it!

**Comment by mihaimaruseac** [comment]
This seems too large. Unassinging myself and assigning @gunan

**Comment by Namburger** [comment]
> This seems too large. Unassinging myself and assigning @gunan

Hi, sorry guys, I just built flatc and included it in third_party so that `tensorflow/tensorflow/lite/tools/visualize.py` can run smoothly. 
It's my first pull request, not too sure if this is against tf standard practices.
Thanks for considering.

**Comment by mihaimaruseac** [comment]
Afaik, you only need `BUILD` (and an optional `workspace.bzl`) and then add add the corresponding `tf_http_archive`, for example https://github.com/tensorflow/tensorflow/blob/235e88b123cbf742d7db91e37dd836e30bd6766d/tensorflow/workspace.bzl#L709-L718

**Comment by gunan** [comment]
As @mihaimaruseac expressed, you should just create a workspace.bzl entry.
We cannot copy the whole flatbuffers codebase into our own.

**Pull request closed without merging**
