### PR TITLE
Added code for preprocessing of YUV images before feeding yuv_to_rgb

### LINKED ISSUE #37067: Usage Documentation Needed for tf.image.yuv_to_rgb
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/image/yuv_to_rgb

## Description of issue (what needs changing):

The tf.image.yuv_to_rgb method specifies a YUV input of shape (H,W,3) and an RGB output of the same shape. It also notes:

> The output is only well defined if the Y value in images are in [0,1], U and V value are in [-0.5,0.5].

However YUV is natively encoded in HxWx1.5 Bytes, with values ranging from 0-255. Considering that multiple YUV-RGB conversion standards exist, it is unclear what pre-processing steps need to be done by a user who wants to pass YUV inputs to his network (https://en.wikipedia.org/wiki/YCbCr#JPEG_conversion).

### Usage example

More documentation on the proper usage of this method would be highly helpful. Specifically:

- An example showing how to pre-process a raw YUV image of size HxWx1.5B to the expected shape of (H,W,3) with normalized values Y: [0,1], UV: [-0.5,0.5].
- An example of how one might append this method to an RGB-trained model to enable it to accept YUV inputs during inference. A likely scenario might be exporting a frozen model to an Android device that natively captures in YUV.

### PR DESCRIPTION
**Pull request by ashutosh1919**
Fixes [#37067](https://github.com/tensorflow/tensorflow/issues/37067).
@lamberta , @mihaimaruseac - Please review this PR.

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Though it would be great if we can also make the example code be a doctest

**Comment by mihaimaruseac** [comment]
Replaced yub with yuv everywhere and trying to merge from internal to external

**Comment by yaoshiang-masterfulai** [comment]
I believe that both the implementation and documentation for the YUV conversions are incorrect.

1. The YUV specification comes from https://en.wikipedia.org/wiki/Rec._601 and sets a range of:

y: [0,1]
u: -0.436 to + 0.436
v: -0.615 to + 0.615

The kernels in the TF source allow the U value to go beyond the specified range:

y: [0,1]
u: -0.43601035 to + 0.43601035
v: -0.61497538 to + 0.61497538

2. The documentation has confused people on stack exchange by saying U and V need to be in the range [-0.5, 0.5]. I don't believe this documentation is accurate. 

3. The YUV/RGB conversion listed is for a linear RGB. Almost any image a TF developer would deal with will have sRGB gamma correction. The comparable standard for gamma corrected sRGB is YCbCr. That standard appears to be designed to support 24 bit color (8 bits per channel [0,255]). 

A reasonable approach might be to deprecate the YUV conversions in favor of YCbCr.

https://web.archive.org/web/20180423091842/http://www.equasys.de/colorconversion.html

**Comment by lamberta** [comment]
Thanks, @yaoshiang-masterfulai 
Can you please file a separate issue since your comment touches on the docs and the implementation?

**Comment by yaoshiang-masterfulai** [comment]
Could you point me to documentation on how to file issues and contribute?

**Comment by mihaimaruseac** [comment]
Probably this is a good starting point https://help.github.com/en/github/collaborating-with-issues-and-pull-requests Since this is not something specific to TF, google can provide more links

**Comment by lamberta** [comment]
@yaoshiang-masterfulai The TF contributor guide is here: https://www.tensorflow.org/community/contribute
And the docs live in the [tensorflow/docs](https://github.com/tensorflow/docs) repo. Thanks

**Pull request merged**
