### PR TITLE
Initial Haiku support

### PR DESCRIPTION
**Pull request by extrowerk**

### CODE REVIEW

**Comment by miqlas** [comment]
I signed it!

**Comment by gunan** [comment]
@martinwicke WDYT?

**Comment by martinwicke** [comment]
Instead of making PIC depend on Haiku directly, can you add a generic option to turn off PIC, and make haiku use that option? 

Since this is limited to PIC and some error codes (for which we already have FreeBSD exceptions) I'm fine with this change otherwise.

**Comment by miqlas** [comment]
@martinwicke : Sadly currently i have no idea how to create a variable what can propagate through the cmake files, but i'll look into it. Have you got an example maybe?

**Comment by martinwicke** [comment]
I think you can just do `option()`.

**Comment by miqlas** [comment]
thanks! Will try at weekend!

**Comment by miqlas** [comment]
@martinwicke : Tried to do it as good as possible,but i have not too much experiences with cmake.Can you look into it please?

Thanks!

**Comment by gunan** [comment]
There seems to be a merge conflict. could you rebase your change on top of master?

**Comment by miqlas** [comment]
@gunan : conflict solved.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by miqlas** [comment]
Checks looks ok 👍

**Comment by miqlas** [comment]
Any news here?

**Review by gunan — APPROVED** [review]

**Comment by nehaljwani** [comment]
Hi @extrowerk !

Could you please share the reason as to why you disabled PIC for Haiku builds? Just curious!

**Comment by extrowerk** [comment]
@nehaljwani i disabled PIE, not PIC.
I cannot explain you correctly, i don't know much about technologies behind the curtain in Haiku, but it is required, without it it results just linking problems.

**Pull request merged**
