### PR TITLE
Cherrypicks for r0.11rc release

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Cherry-pick, ignoring CLA.

**Comment by mrry** [comment]
@googlebot I authored the commit, and am okay with it being contributed.

**Comment by gunan** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Can you also pull in https://github.com/tensorflow/tensorflow/commit/1d9ca7bbea8f41d38f5dc57fd3fe4ee15c4aab04 and https://github.com/tensorflow/tensorflow/commit/ff2bea2684ccce59547eb9acd02462cc0d2ba1e1? They're needed to fix the makefile build.

**Comment by gunan** [comment]
tensorflow/python/kernel_tests:io_ops_test is still flaky.
Jonathan, did we have a fix for that?

**Comment by jhseu** [comment]
Yeah, https://github.com/tensorflow/tensorflow/commit/a112b988d0976493adab04b9cb2af771882a4904

**Comment by gunan** [comment]
All changes are cherrypicked from master.
therefore ignoring CLA, assuming CLA is all taken care of in master branch.

**Pull request merged**
