### PR TITLE
Cleanup for more consistent use of c_api_macros.h, throughout tensorflow C APIs.

### PR DESCRIPTION
**Pull request by wxinix**
Scattering in different tensorflow C API headers, there is really no need for including the following macro definitions, given there is already a dedicated header c_api_macros.h

Therefore the following lines are removed, while c_api_macros.h is added accordingly to the front of each relevant header file.

// Macro to control visibility of exported symbols in the shared library (.so,
// .dylib, .dll).
// This duplicates the TF_EXPORT macro definition in
// tensorflow/core/platform/macros.h in order to keep this .h file independent
// of any other includes.
#ifdef SWIG
#define TF_CAPI_EXPORT
#else
#if defined(_WIN32)
#ifdef TF_COMPILE_LIBRARY
#define TF_CAPI_EXPORT __declspec(dllexport)
#else
#define TF_CAPI_EXPORT __declspec(dllimport)
#endif  // TF_COMPILE_LIBRARY
#else
#define TF_CAPI_EXPORT __attribute__((visibility("default")))
#endif  // _WIN32
#endif  // SWIG

### CODE REVIEW

**Comment by wxinix** [comment]
Scattering in different tensorflow C API headers,  there is no need for the duplicate macro definitions, given there is already a dedicated header c_api_macros.h

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Can you ensure that Ubuntu CPU build passes? Currently it fails as the header is not found:

```
[2,195 / 5,685] [Sched] Compiling tensorflow/c/tf_status.cc ... (197 actions, 1 running)
In file included from ./tensorflow/c/tf_status_helper.h:19:0,
                 from tensorflow/c/tf_status_helper.cc:16:
./tensorflow/c/tf_status.h:19:10: fatal error: tensorflow/c/c_api_macros.h: No such file or directory
 #include "tensorflow/c/c_api_macros.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ERROR: /tmpfs/src/github/tensorflow/tensorflow/c/BUILD:483:16: Couldn't build file tensorflow/c/_objs/tf_status_helper/tf_status_helper.pic.o: C++ compilation of rule '//tensorflow/c:tf_status_helper' failed (Exit 1): gcc failed: error executing command
...
```

https://source.cloud.google.com/results/invocations/bec0a226-e398-4869-9672-d88a304e2c36/targets/%2F%2Ftensorflow%2Fc:tf_status_helper_test/log

Most likely you need changes to the `BUILD` file

**Comment by gbaned** [comment]
@wxinix  Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

**Comment by wxinix** [comment]
Apology - I am not very familiar with the Build system, and how to update it for Ubuntu.

**Comment by gbaned** [comment]
@mihaimaruseac Can you please assist on above comments from @wxinix. Thanks!

**Comment by gbaned** [comment]
@wxinix  Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@mihaimaruseac Can you please review this PR ? Thank you!

**Comment by mihaimaruseac** [comment]
https://github.com/tensorflow/tensorflow/pull/48084#pullrequestreview-679861204 is still not addressed. Reviewing it now means giving the exact same comment and just wasting time.

**Comment by gbaned** [comment]
@wxinix Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!

**Comment by gbaned** [comment]
@wxinix Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
@wxinix Any update on this PR? Please. Thank you!

**Pull request closed without merging**
