### PR TITLE
Fix exception handling of tf.histogram_fixed_width_bins

### LINKED ISSUE #29661: Bug in exception handling of tf.histogram_fixed_width_bins
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.0.0-beta0
- Python version: python3 from colab
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
when value range for  `tf.histogram_fixed_width_bins ` is `[0.0, 0.0], it outputs an index outside `nbins`. See the code below.

```
nbins = 5
value_range = [.0, .0]
new_values = [-1.0, 0.0, 1.5, 2.0, 5.0, 15]
indices = tf.histogram_fixed_width_bins(new_values, value_range, nbins=5)
print(indices)

```
Output is 
```
tf.Tensor([          0 -2147483648           4           4           4           4], shape=(6,), dtype=int32)
```

**Describe the expected behavior**
It should show indices as [0,0,4,4,4,4] and throw a warning saying that the range needs to be updated

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
See above

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to address the issue in #29661 where
tf.histogram_fixed_width_bins does not throw out an exception
when (value_range[0] < value_range[1]) is not satified.
This is dfferent from the documentation specified in the docstring.

This is different from a similiar API `tf.histogram_fixed_width`
where exception is thrown out correctly. The reason is that
`tf.histogram_fixed_width_bins` is handled in python while
`tf.histogram_fixed_width` has a C++ kernel.

This PR uses tf.Assert to make sure `(value_range[0] < value_range[1])`
satisty.

This PR fixes #29661.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by alextp — CHANGES_REQUESTED** [review]
The change as it is now is very expensive, as it'll always run the assertion at runtime.

Maybe it's worth only checking at graph build time? Or instead specifying the behavior for when this condition is not true in the documentation and allowing users to know what happens?

**Comment by gbaned** [comment]
@yongtang Can you please check reviewer comments and keep us posted. Thanks!

**Review by alextp — DISMISSED** [review]

**Comment by yongtang** [comment]
Thanks @alextp for the review. I have updated the PR. Now `tensor_util.constant_value` is used to resolve value if possible, and throws out a ValueError incase there is overlap of `value_range`. This is in graph compilation time and avoids runtime check. Let me know if this makes sense.

**Comment by yongtang** [comment]
Ah see the approve, that was quick. Thanks! 👍

**Comment by gbaned** [comment]
@yongtang Can you please address Ubuntu Sanity errors? Thanks!

**Comment by yongtang** [comment]
Thanks @alextp @gbaned The pylint has been fixed, sorry to update the PR again.

**Review by alextp — APPROVED** [review]

**Pull request merged**
