### PR TITLE
change learn.metric_spec.MetricSpec to learn.MetricSpec due to API change  in version 1.0

### PR DESCRIPTION
**Pull request by wangg12**
As mentioned in #7569.

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
LGTM. You just need to get the CLA signed.

**Comment by wangg12** [comment]
@terrytangyuan Sorry, maybe I used another usename and email to do this PR. I don't know how to add a CLA for it.  Maybe I should create another PR with the username which I had a CLA?

**Comment by terrytangyuan** [comment]
Sure

**Comment by wangg12** [comment]
@terrytangyuan I pushed with another username, it should be OK now.

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Comment by terrytangyuan** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
Android test failure is unrelated. Merging PR.

**Pull request merged**
