### PR TITLE
[Windows/CMake] Add optimization flags

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Comment by gunan** [comment]
Jenkins, test this please.

**Review by yifeif — APPROVED** [review]

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by mrry** [comment]
I am okay with this.

**Comment by mrry** [comment]
@googlebot I am okay with this.

**Comment by gunan** [comment]
@mrry it turns out when cherrypicking changes googlebot will never be happy (known issue in cla bot)
As long as we manually verify CLAs, we are OK.

**Comment by mrry** [comment]
@googlebot I just wanted to make you happy :(.

**Pull request merged**
