### PR TITLE
[INTEL MKL] Refactor mkl_relu_ops files, and add accuracy and performace UT.

### PR DESCRIPTION
**Pull request by gyshi**
This PR contains two modifications:  

- Refactor tensorflow/core/kernels/mkl/mkl_relu_op files.
- Add benchmark  and accuracy files for MKL eltwise kernels UT.

### CODE REVIEW

**Comment by gbaned** [comment]
@gyshi  Can you please resolve conflicts? Thanks!

**Comment by gyshi** [comment]
@gbaned  thanks, I have resolved conflict

**Comment by gyshi** [comment]
@gbaned , please review this MR, thanks very much, becaues some bug fix depend on this MR.

**Comment by gyshi** [comment]
@gbaned , i have resolved conflict. thanks for reviewing

**Comment by gyshi** [comment]
@gbaned , Please review

**Comment by gbaned** [comment]
@gyshi Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@gyshi  Any update on this PR? Please. Thanks!

**Comment by gyshi** [comment]
hi, @gbaned   I remove  tensorflow/core/kernels/mkl/mkl_relu_op_test.cc this file, I do not know why it raises Conflicting. now, i have no update for this MR. thanks

**Comment by gbaned** [comment]
@gyshi Can you please resolve conflicts? then this PR will go for review. Thanks!

**Comment by gyshi** [comment]
hi, @gbaned  i have rebased this MR

**Comment by gyshi** [comment]
hi, @gbaned  please review this mr

**Comment by gyshi** [comment]
@gbaned @penpornk hi, please review this mr, some bug fix depend on this MR.  thanks very much

**Comment by gyshi** [comment]
@gbaned @penpornk hi, please review this mr, some bug fix depend on this MR. thanks very much

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gyshi** [comment]
@penpornk please review this MR。 thanks very much, i think Gelu and other bug fix will depend on this mr

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Pull request closed without merging**
