### PR TITLE
Branch 134070499

### PR DESCRIPTION
**Pull request by martinwicke**

### CODE REVIEW

**Review by mrry — APPROVED** [review]
Fix LGTM.

**Comment by martinwicke** [comment]
cmake failure:

**Comment by martinwicke** [comment]
[ 23%] No install step for 'grpc'
[ 23%] Completed 'grpc'
[ 23%] Built target grpc

**Comment by mrry** [comment]
I'm tempted to say ignore the CMake failure and I'll fix it. Sound good?

**Comment by martinwicke** [comment]
Hard to resist.

**Comment by mrry** [comment]
I have a fix in the works... the Bazel simplification also moved some of the header paths for our external dependencies, so we need a corresponding change in the CMake build.

**Pull request merged**
