### PR TITLE
Use correct casts to get right dimensions on s390x

### PR DESCRIPTION
**Pull request by shahidhs-ibm**
The `testConcatAxisType` test in `concat_op_test` is failing on an assertion for s390x (Ref. Issue#[28114](https://github.com/tensorflow/tensorflow/issues/28114)):
```
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/87c06bad5aec2f21ec96b7253de551e8/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/python/kernel_tests/concat_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/concat_op_test.py", line 621, in testConcatAxisType
    self.assertEqual([2, 6], c.get_shape().as_list())
AssertionError: Lists differ: [2, 6] != [4, 3]
```
It turned out that the cast operation was not correct for big-endian architecture and not able to draw right dimension value when the Axis is of int64 type. Updating the cast resolved the issue.

### CODE REVIEW

**Comment by shahidhs-ibm** [comment]
@jaingaurav Kindly review the PR when you get chance.
@gbaned I wish to merge these code changes in `r1.15` branch too. Is there any way available to achieve this or I have to raise another PR?

**Review by jaingaurav — CHANGES_REQUESTED** [review]
Change looks good, however could you please fix the indentation? Seems like you are using 4 spaces vs the rest of the file which uses 2 spaces.

And yes you'll have to request a PR into 1.15.

**Review by jaingaurav — APPROVED** [review]

**Comment by shahidhs-ibm** [comment]
@jaingaurav Thanks for reviewing the code changes. I have incorporated your review comments. As you have suggested, will create a separate PR for `1.15` branch.

**Comment by shahidhs-ibm** [comment]
Created PR#[33417](https://github.com/tensorflow/tensorflow/pull/33417) for merging the code changes on 1.15 branch.

**Pull request merged**
