### PR TITLE
 Use abs() rather than sqrt() for mfcc mel filter to prepare the spectrum

### PR DESCRIPTION
**Pull request by zYeoman**
It's more sensible to use power spectrum than amplitude spectrum.

And we can use "magnitude_squared=False" for amplitude spectrum.

### CODE REVIEW

**Comment by martinwicke** [comment]
We cannot change the behavior of this unless this is a straightforward bug. What does the documentation say about this?

**Comment by zYeoman** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Mel-frequency_cepstrum), 

> MFCCs are commonly derived as follows:
> 1. Take the Fourier transform of (a windowed excerpt of) a signal.
> 2. Map the powers of the spectrum obtained above onto the mel scale, using triangular overlapping windows.
> 3. Take the logs of the powers at each of the mel frequencies.
> 4. Take the discrete cosine transform of the list of mel log powers, as if it were a signal.
> 5. The MFCCs are the amplitudes of the resulting spectrum.

But the [standardised MFCC algorithm](https://www.etsi.org/deliver/etsi_es/201100_201199/201108/01.01.03_60/es_201108v010103p.pdf)  defined by ETSI seems to use amplitude spectrum.

I did more research online, and found out that some paper use power spectrum[1][2][3] while the other use amplitude spectrum[4][5]. Some ppts from classes in university show that professors prefer power spectrum.

For me, it's weird to square the "magnitude_squared=True" spectrum to get MFCCs from power spectrum. And if I want to use some different spectrum (diff(FFT(x)) for example), I'll have to square the spectrum before MFCCs feature extract.


[1]: A. Dev, “Robust Features for Noisy Speech Recognition using MFCC Computation from Magnitude Spectrum of Higher Order Autocorrelation Coefficients,” Int. J. Comput. Appl., vol. 10, no. 8, pp. 36–38, 2010.
[2]: A. Mohammed et al., “Techniques for Feature Extraction In Speech Recognition System: A Comparative Study,” Int. J. Comput. Appl. Eng. Technol. Sci., vol. 2, no. 1, pp. 1–9, 2013. Time-frequency representations Speech Processing Tom Bäckström Aalto University October 2015
[3]: S. G. Koolagudi, D. Rastogi, and K. S. Rao, “Identification of language using mel-frequency cepstral coefficients (MFCC),” in Procedia Engineering, 2012, vol. 38, pp. 3391–3398.
[4]: B. Logan, “Mel Frequency Cepstral Coefficients for Music Modeling,” Int. Symp. Music Inf. Retr., vol. 28, p. 11p., 2000.
[5]: S. K. Kopparapu and M. Laxminarayana, “Choice of Mel filter bank in computing MFCC of a resampled speech,” in 10th International Conference on Information Sciences, Signal Processing and their Applications, ISSPA 2010, 2010, pp. 121–124.

**Comment by rryan** [comment]
It's my understanding that the choice is task dependent. I would suggest that people who want MFCCs use [`tf.contrib.signal.mfccs_from_log_mel_spectrograms`](https://www.tensorflow.org/api_docs/python/tf/contrib/signal/mfccs_from_log_mel_spectrograms), which gives you the choice of whether to use amplitude or power (or power in decibels, as librosa does). 

This also gets you GPU and TPU support, which this C++ op doesn't :).

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment]
We cannot change the behavior of the stable API. I think we should consider deprecating this function and instead find a good place for contrib/signal, so users can get it from there.

**Pull request closed without merging**
