### PR TITLE
ci_build updates

### PR DESCRIPTION
**Pull request by jendap**
- fix domain in pip metadata
- ci_build: add user inside docker to sudo group
- ci_build: detect python path within container

### CODE REVIEW

**Comment by caisq** [comment]
@jendap The files involved in this PR overlap with my PR https://github.com/tensorflow/tensorflow/pull/1051 and is smaller. I can include your changes in my PR to avoid potential conflict and make it easier to merge everything to r0.7. How does that sound to you?

**Comment by martinwicke** [comment]
Are all changes in this PR included in #1051? Because I don't see the sudo change in #1051.

**Comment by caisq** [comment]
@martinwicke I didn't include it in 1051 because I didn't hear back. Please merge this to master and cherry-pick it to r0.7 separately.

**Comment by martinwicke** [comment]
There are conflicts. I'll wait for jan to resolve.

**Comment by jendap** [comment]
Conflict resolved.

**Comment by caisq** [comment]
I manually pulled them to my fork of the release branch and tests of them on Jenkins has been okay so far. We can just merge them into r0.7 and then master when the release is done.

**Comment by martinwicke** [comment]
The coordinator test failure is unrelated?

**Comment by caisq** [comment]
@martinwicke That's unrelated. I forgot to add the TF_BUILD_SERIAL_TESTS=1 to the build configuration, which is required for GPU tests because concurrent running of the GPU tests is known to cause OOM errors. We can consider adding TF_BUILD_SERIAL_TESTS=1 as an automatic default for GPU to ci_parameterized_build.sh.

**Comment by martinwicke** [comment]
Included in #1096. Closing.

**Pull request closed without merging**
