### PR TITLE
Fix buffer overrun in MicroAllocator

### PR DESCRIPTION
**Pull request by frreiss**
The quantization code in the method `MicroAllocator::InitializeRuntimeTensor` writes past the end of the `params.zero_point` field in `TfLiteTensor` structs, clobbering the `allocation_type` field. This pull request fixes the overrun. I have also extended the test coverage for `MicroAllocator` to cover the lines of code where the overrun was occurring.

**Edit:** After subsequent changes, the code in question now copies the first four bytes of a 64-bit integer value into the first four bytes of a 32-bit integer value. This behavior is subtly incorrect on little-endian machines (doesn't maintain sign bits properly) and very incorrect on big-endian machines.

### CODE REVIEW

**Comment by gbaned** [comment]
@frreiss Could you please resolve the conflicts? Thanks!

**Comment by frreiss** [comment]
@gbaned the conflicts seem to have resolved themselves.

**Comment by gbaned** [comment]
@petewarden, @advaitjain Can you please take a look at this PR? Thanks!

**Comment by gbaned** [comment]
@frreiss Can you please resolve the conflicts? Thanks!

**Comment by frreiss** [comment]
Conflicts resolved. It looks like someone has attempted to patch the buffer overrun, but the change in the patch is incorrect. The changes in this PR are still needed, particularly on big-endian machines.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by njeffrie** [comment]
Thanks for this change and for catching this subtle issue.  For future reference, The micro teams is likely to get to the PR faster if you add comp:micro to the tags (at least that's how I filter for micro-related PRs/bugs).

**Comment by mordieross** [comment]
@frreiss @mihaimaruseac - Thanks for this! - Is this in a patched release yet? Or would I need to build from source using master branch?

**Comment by mihaimaruseac** [comment]
2.2-rc0 has the commit. See attached image

**Pull request merged**
