### PR TITLE
[NVIDIA TF] Add bfloat16 to TF_CALL_GPU_NUMBER_TYPES macro

### PR DESCRIPTION
**Pull request by trevor-m**
This PR adds `bfloat16` registration to the `TF_CALL_GPU_NUMBER_TYPES` and `TF_CALL_GPU_ALL_TYPES` macros and removes the explicit bfloat16 registration for all ops using those.

All ops which use these macros already have bfloat16 support and unit tests from previous PRs, so this PR has no functional changes. 

cc @reedwm @cantonios Thanks again for all of your efforts reviewing the bfloat16 PRs!

### CODE REVIEW

**Comment by cantonios** [comment]
Eek, that's a lot of changes.  Just double-checking: do we have a sense of whether these all work with rocm as well?

**Comment by trevor-m** [comment]
> Eek, that's a lot of changes. Just double-checking: do we have a sense of whether these all work with rocm as well?

Hi @cantonios, there is no actual change happening in this PR. This is just moving the call to `TF_CALL_bfloat16` from each individual op to the `TF_CALL_GPU_NUMBER_TYPES` macro.

If there was no problems with rocm before there should be no effect.

**Comment by reedwm** [comment]
> Eek, that's a lot of changes. Just double-checking: do we have a sense of whether these all work with rocm as well?

I think it should work with rocm, although i'm not sure if AMD GPUs natively support bfloat16. If not, it will use the slow bfloat16 emulation, as is done with bfloat16 on older NVIDIA GPUs.

Merging this PR might be slightly tricky due to the potential of people modifying one of the hundreds of modified files during the merge process, but it should be doable if we merge late at night or over a weekend.

**Comment by cantonios** [comment]
> > Eek, that's a lot of changes. Just double-checking: do we have a sense of whether these all work with rocm as well?
> 
> Hi @cantonios, there is no actual change happening in this PR. This is just moving the call to `TF_CALL_bfloat16` from each individual op to the `TF_CALL_GPU_NUMBER_TYPES` macro.
> 
> If there was no problems with rocm before there should be no effect.

I believe our CI only does a rocm _build_, so was mainly wondering if anyone has actually tested it.  But yeah, glanced through and looks okay.

**Review by cantonios — APPROVED** [review]

**Comment by cantonios** [comment]
Thanks @trevor-m, it's nice to finally have proper bfloat16 support on GPU.  Now we just need to add it properly to Eigen ;).

**Pull request merged**
