### PR TITLE
TF-Lite Micro: port Silicon Labs STK3701A to Micro Speech example

### PR DESCRIPTION
**Pull request by sldriedler**
This ports the  Micro Speech example to the Silicon Labs STK3701A development board.

### CODE REVIEW

**Comment by sldriedler** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
@sldriedler Thank you for your contribution. Can you please sign CLA? Thanks!

**Comment by sldriedler** [comment]
@gbaned My company, Silicon Labs signed an agreement. My email is in the group: @silabs-nn-contributors.googlegroups.com

**Comment by gbaned** [comment]
@sldriedler Can you use please make sure to use same GitHub username and email-id associated with it. Thanks!

**Comment by gbaned** [comment]
@sldriedler  Any update on this PR? Please. Thanks!

**Comment by sldriedler** [comment]
Hi, there was an issue with the CLA. This issue should now be resolved. My email: dan.riedler@silabs.com is associated to the silabs-ot-dev Google group.

**Comment by sldriedler** [comment]
@gbaned Are you able to provide any insight as to why the PR is being blocked?

My github user email is: dan.riedler@silabs.com
The committer email of this PR is the same.
My email is associated with silabs-ot-dev Google group
And that google group has a signed CLA.

Is there anything I'm missing? Any help is very much appreciated. Thanks!

**Comment by rthadur** [comment]
@sldriedler your username and email are not associated , we see a CLA with email dan.riedler@silabs.com from feb 2019, but not the username, can you please make sure both are linked.

**Comment by sldriedler** [comment]
@rthadur Thank you for your response, however, I am still not sure what I need to do. My Github username (sldriedler) has a primary email of dan.riedler@silabs.com. I have just made this email 'public' in the Github account settings. What else do I need to do to associate my username and email?

Thank you for your help

**Comment by rthadur** [comment]
@sldriedler i am not sure why it still shows no CLA , is it possible to sign the CLA again with all the information ?

cc @mihaimaruseac

**Comment by sldriedler** [comment]
@rthadur rthadur I closed this and opened another PR: https://github.com/tensorflow/tensorflow/pull/41568
The CLA looks good to go. Thank you for your help.

**Pull request closed without merging**
