### PR TITLE
Canned estimators use 'careful_interpolation' rule to compute PR-AUCs

### PR DESCRIPTION
**Pull request by hhzrz**
Fix https://github.com/tensorflow/tensorflow/issues/19080

### CODE REVIEW

**Comment by hhzrz** [comment]
I signed it!

**Comment by hhzrz** [comment]
@protoget From the CI build result we can tell, all failed checks are related to the calculation of `AUC_PR` as we used a new way(`careful_interpolation`) to do the calculation. But i'm not able to confirm this result is correct, as this new way of calculating `AUC_PR` is out of my cognition. This change happend by [this commit](https://github.com/tensorflow/tensorflow/commit/1f5324ca69bc1017972eef8e418691cff9a86dd7).

So i don't know how should i continue with this **failed CI build**?

**Comment by aselle** [comment]
@roumposg could you take a look?

**Comment by roumposg** [comment]
Thank you for your contribution. We have discussed changing the default behavior of AUC metric to careful_interpolation. Unfortunately, changing the default will be backwards incompatible. E.g. if a user pipeline relies on the AUC metric to make some decisions, such as push the model to serving or not, this change may break their pipeline.

What about the following: Add a `auc_pr_careful_interpolation` metric in addition to the existing ones. You can do the same to MultiLabelHead in tensorflow/contrib/estimator/python/estimator/head.py Thanks.

**Comment by hhzrz** [comment]
@roumposg Thanks for your reply. You're right, this change will result in backwards incompatibility. And also i've thought about your proposal for a time. As the requirement to this careful_interpolation way to do AUC calculation seems not a very urgent need to most of people(at least we can tell from the activity of this pull request.), maybe we'd better to wait for this change can be taken into consideration in next big version(hopefully 2.0), and i'll do my work with some workarounds.

**Comment by roumposg** [comment]
As you wish, thanks. BTW, you can add metrics to an estimator using `tf.contrib.estimator.add_metrics`.

**Comment by ed-alertedh** [comment]
Just ran into this - using batches of 256 I'm finding the trapezoidal AUC is way off. I know it's only ever going to be an estimate but careful_interpolation seems to at least be in the right ballpark. In case it saves someone else a few minutes, here is how to implement @roumposg's suggestion:

    def my_auc(labels, predictions):
        return {'auc_pr_careful_interpolation': tf.metrics.auc(labels, predictions['logistic'], curve='PR',
                                                                summation_method='careful_interpolation')}

    self._estimator = tf.contrib.estimator.add_metrics(estimator, my_auc)

**Pull request closed without merging**
