### PR TITLE
Branch 122541517

### PR DESCRIPTION
**Pull request by nsthorat**
To sync @nsthorat

test this please

### CODE REVIEW

**Comment by nsthorat** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by mrry** [comment]
The most likely culprit for the failure is https://github.com/tensorflow/tensorflow/pull/2408/commits/d0fa481d59228e39ee4e76d5191633cc7e9d1c29 (since the other changes seem to be Python only, and the failing test itself is unmodified). There were 3 days' lag between the Jenkins presubmit test for that change and its submission, so that could explain the breakage. Might be worth trying to roll it back?

**Comment by mrry** [comment]
Looks like https://github.com/tensorflow/tensorflow/pull/2408/commits/d0fa481d59228e39ee4e76d5191633cc7e9d1c29 works in isolation, so there goes that theory. Let's run the tests again, in case it was a flake.

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by caisq** [comment]
@vrv, should be ready to merge. The cmake build failure is pre-existing.

**Comment by mrry** [comment]
OK, looks like the test failure was a flake :). I'll go ahead and merge this one, thanks!

**Comment by mrry** [comment]
Merged in https://github.com/tensorflow/tensorflow/commit/b54b59e0e65861a624ff5273308565487c8ac25e.

**Pull request closed without merging**
