### PR TITLE
_linear scope bug: use the scope if provided

### PR DESCRIPTION
**Pull request by Bihaqo**

### CODE REVIEW

**Comment by Bihaqo** [comment]
I signed the CLA (under my primary email sasha.v.novikov@gmail.com).

**Comment by ebrevdo** [comment]
Please remove the scope argument instead.  This function is not meant for public use and the scope argument is a bug.

**Comment by Bihaqo** [comment]
Done.

**Comment by ebrevdo** [comment]
Lukasz, can you do the final approval?  ooo.

**Review by lukaszkaiser — APPROVED** [review]
Thanks, looks good!

**Comment by lukaszkaiser** [comment]
@tensorflow-jenkins test this please

**Comment by jhseu** [comment]
Mind fixing the lint errors? (The _scope arg is used in several places in that file)

**Comment by Bihaqo** [comment]
My bad, fixed

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by jhseu** [comment]
Trying again...
Jenkins, test this please

**Pull request merged**
