### PR TITLE
Fix typos in tensorboard/components

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by dsmilkov** [comment]
LGTM. Thanks @dongjoon-hyun!

**Comment by dongjoon-hyun** [comment]
Thank you, @dsmilkov ! :)

**Comment by dsmilkov** [comment]
@vrv You can go ahead and merge.

**Comment by vrv** [comment]
Merged into master.

**Comment by dongjoon-hyun** [comment]
Thank you, @vrv .

**Pull request closed without merging**
