### PR TITLE
Use Bazel's builtin patch support.

### PR DESCRIPTION
**Pull request by benjaminp**
This removes a dependency on the system having a patch executable.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
We had issues in the past where patching wouldn't work on Windows/Linux. We have tried `git patch`, `git apply` and `patch`.

Adding gunan@ to verify if this is likely to solve all issues form above and if the diffs are also ok, as I was not expecting them to be generated given PR title/description

**Comment by benjaminp** [comment]
I had to regenerate some of the patch files because the builtin patch is stricter than `patch(1)`. (Basically, I just did `patch -p1 old.patch` and `diff -ru`.)

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by gunan** [comment]
As long as presubmits pass, I think we can accept this change.

**Comment by benjaminp** [comment]
Only "Windows Bazel GPU " appears to have failed, but it also is broken on master.

**Review by gunan — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Will import this manually, something breaks

**Pull request merged**
