### PR TITLE
GOOGLE CODE IN 2019 : TASK "Add a usage example to TensorFlow 2.0 API documentation. "

### PR DESCRIPTION
**Pull request by CREVIOS**

### CODE REVIEW

**Comment by HotPotatoC** [comment]
Hello, good work. Apparently, this example uses Tensorflow 1.0, not 2.0. It's nice to see another code-in participant, good luck on this task btw!

JuanC

**Comment by CREVIOS** [comment]
Thanks for your appreciation, I love to contribute here. Let's see what can be done next. The mentors are very helpful by giving us many suggestions.

**Comment by CREVIOS** [comment]
https://colab.research.google.com/drive/1a8B3_w_u70c1WyI4vO4gWN1hBtQpKyKL
in Tf 2.0

**Comment by boronhub** [comment]
Hi! Unfortunately you can't add Google Colab notebooks as usage examples, you need to make it a doctest as seen [here ](https://www.tensorflow.org/community/contribute/docs_ref#testable_docstrings). Also please make sure to make the changes in the correct file.

**Comment by CREVIOS** [comment]
Hi , i have added the doctest

**Comment by HotPotatoC** [comment]
Sorry, this is not how the doctests should be. You can take a look at @msteknoadam's examples here #35388

**Pull request closed without merging**
