### PR TITLE
Minor optimization of conv_ops.

### PR DESCRIPTION
**Pull request by codrut3**
If data_format is NCHW, and the computation is done on the GPU, the temporary tensor `transformed_output` is not needed. One can use directly the `output` tensor. This
leaves more memory for the cudnn scratch allocator, possibly improving performance
of the convolution algorithm.

I also fixed several style issues in `conv_ops.cc` reported by clang-format.

I did not add any tests because the change is covered by `python/kernel_tests/conv_ops_test.py`.

### CODE REVIEW

**Comment by martinwicke** [comment]
@zheng-xq you're far more familiar with these kernels, can you take a look?

**Comment by rmlarsen** [comment]
@zheng-xq ping XQ.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: It has been 16 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: It has been 123 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: It has been 138 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: It has been 153 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: It has been 168 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 183 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 198 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 213 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 228 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @zheng-xq: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 243 days with no activity and the `awaiting review` label has been applied.

**Comment by codrut3** [comment]
Hi @vrv,

Yes, if you are interested, I want to get it committed. This change followed my investigation into a bug, where I discovered that memory usage is not optimal for data format NCHW. From what I see, this optimization still applies to the current conv_ops.cc.

Anyway, in the meantime I changed countries, and I lost the GPU that I used for dev. So I need a few days to find a GPU card and set up a new dev environment.

**Comment by codrut3** [comment]
Hi @vrv,
I resolved the conflicts, but the checks are not being run. Please, what should I do?

**Comment by vrv** [comment]
I made a small syntax / comment edit, but LG.  Running tests (again).  We have to trigger the tests, unfortunately.

**Comment by codrut3** [comment]
Hi @vrv, @wt-huang,

I think the tests passed. Is there anything else I should do?

**Comment by vrv** [comment]
I clicked some other buttons that apparently were necessary but I'm awaiting next steps too...

**Pull request merged**
