### PR TITLE
Update load.py

### PR DESCRIPTION
**Pull request by blackyang**
Simple fix for keras model load for raggedTensor. Otherwise there is `AttributeError` about `raggedTensorSpec` not having `name`

### CODE REVIEW

**Comment by blackyang** [comment]
@googlebot I signed it!

**Comment by pedro-r-marques** [comment]
@blackyang It would probably make sense to add a unit test that reproduces the issue you did run into.

I've been poking around trying to understand how signatures that refer to RaggedTensors are saved. As far as I understand it, function tracing and model saving take a RaggedTensor argument and do ```nest.flatten(arg, expand_composites=True)``` which results in the arguments being the underlying shape of the RaggedTensor values and row_splits elements.

It is possible that this has to be taking into consideration when evaluating a loaded model.

**Review by omalleyt12 — APPROVED** [review]
Thanks for the PR! LGTM

**Comment by blackyang** [comment]
@omalleyt12 Thanks you! I found 1 failed check about `import/copybara`, do you know how to see the detailed error message?

**Review by gbaned — APPROVED** [review]

**Pull request merged**
