### PR TITLE
Remaining cherry-picks for 1.4.0rc1

### PR DESCRIPTION
**Pull request by case540**
Java doc fixes. Fixes for S3 file system and making S3 file system a default build option when
running configure.

### CODE REVIEW

**Comment by case540** [comment]
Will also potentially cherry-pick this change if it lands on master.
https://github.com/tensorflow/tensorflow/pull/13699

**Comment by case540** [comment]
Missed cherry-picking "Add documentation to sloppy_interleave function"

Added this to the PR

**Comment by av8ramit** [comment]
You're missing 251a1e70dc04b10fb25e8013d1ad1f27d5eda30b

**Comment by av8ramit** [comment]
Throw in 2f3812501d3ac10165acfcae228e52f6f3358f7e as well.

**Review by av8ramit — COMMENTED** [review]
Missing some cherrypicks.

**Comment by case540** [comment]
251a1e7 already appears to be in r1.4 branch. But added 2f38125

**Review by av8ramit — APPROVED** [review]

**Pull request merged**
