### PR TITLE
Immediate Mode execution in tensorflow

### PR DESCRIPTION
**Pull request by yaroslavvb**
Implementation of immediate mode execution in TensorFlow. The idea is to wrap original tensorflow API, but provide session/run management logic so that commands execute immediately, and graph caching to avoid modifying graph when same op is run repeatedly. Data is kept in TensorFlow runtime whenever possible using persistent tensors and transferred to Python runtime on demand when needed for printing/control flow.

```
import tensorflow as tf
from tensorflow.contrib import immediate

tfi = immediate.Env(tf).tf        # wraps "tf" namespace, saves it as "tfi"
val1 = tfi.ones((3,))             # creates tensor on GPU
val2 = val1 + val1                # runs into tf.add, keeps result on GPU
val3 = tfi.ones((2, 2, 2, 2))
val4 = tfi.nn.conv2d(val3, val3, [1, 1, 1, 1], "VALID")   # run CuDNN conv2d
if (tfi.reduce_sum(val3)>0.):     # runs reduce_sum on GPU, transfers bool to CPU
  print(val4)                     # transfers whole tensor to CPU for display

```

This is a single commit rebase of a previous pull request from https://github.com/tensorflow/tensorflow/pull/2346

@keveman

### CODE REVIEW

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by yaroslavvb** [comment]
The failures are due to https://github.com/tensorflow/tensorflow/issues/2586, @yuanbyu  are you able to reproduce?

**Comment by yaroslavvb** [comment]
Hm, I may need to move this to a new pull request, every time I do rebase, it includes all the changes fast-forwarded by the rebase into the pull request

**Comment by yaroslavvb** [comment]
Sorry, I'm opening new request since I don't know how to fix this:

https://github.com/tensorflow/tensorflow/pull/2747

In my current work-flow, when I rebase, every commit that's included during fast forwarding goes into the pull request. Here's the sequence of commands I've been using so that people know not to do this: http://stackoverflow.com/questions/37707605/doing-rebase-adds-replays-master-branch-commits-into-my-pull-request

**Pull request closed without merging**
