### PR TITLE
modified the documentation of tf.math.add and tf.math.acos operations

### PR DESCRIPTION
**Pull request by Sudeepam97**
A Pull Request for issues #25802   and #25846 . I have tried to improve the documentation of `tf.math.acos` and `tf.math.add` with this patch. I did this by editing the files `api_def_Acos.pbtxt` and `api_def_Add.pbtxt` and by modelling them after the `api_def_Angle.pbtxt` file within the `tensorflow/tensorflow/core/api_def/base_api` directory. The changes I made were reflected in the generated file `python/ops/gen_math_ops.py`. The `gen_math_ops.py` file was generated by following [these](https://www.tensorflow.org/community/documentation#api_documentation) instructions. 

This is my first time editing a piece of documentation which is created from a generated file, and so it may not be perfect. Please feel free to point out any errors that I may have made, and I'll be happy to work on them.

### CODE REVIEW

**Comment by Sudeepam97** [comment]
@dynamicwebpaige, you might want to take a look.

**Comment by dynamicwebpaige** [comment]
@Sudeepam97 - Thank you for wanting to help improve the TF 2.0 API documentation! We appreciate it. :slightly_smiling_face: 

The `.pbtxt` files are generated for the `tf.math.*` operations; in order to make modifications to the descriptions of these endpoints in TensorFlow's documentation, you need to modify the equivalent `.Doc`s in [`math_ops.cc`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/math_ops.cc).

An example would be description [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/math_ops.cc#L531).

Does that make sense?

**Comment by Sudeepam97** [comment]
> @Sudeepam97 - Thank you for wanting to help improve the TF 2.0 API documentation! We appreciate it, and I am happy to work with you to get the changes added. slightly_smiling_face
> 
> The `.pbtxt` files are generated for `tf.math.*` operations; in order to make modifications to the descriptions of these endpoints in TensorFlow's documentation, you need to modify the equivalent `.Doc`s in [`math_ops.cc`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/math_ops.cc).
>
Ohh. I thought that the `.pbtxt` files were independent files since they were available in the code base beforehand, without any compilation or so. I realize that you mentioned this in the issues thread as well. I feel a little silly now. :sweat_smile: 
 
> An example would be description [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/math_ops.cc#L531).
> 
> Does that make sense?

Yes it does. I'll fix these changes right away.

**Review by dynamicwebpaige — COMMENTED** [review]
Thank you for including the usage examples for these two operations! Could you please add Python after the backticks that initiate code samples? (e.g., ```python).

**Comment by Sudeepam97** [comment]
Do we want **python** to be displayed in the markdown render or we just want it to be there in the doc comment without it being rendered? I am asking because when I write python immediately after the backticks without a line break (like so: **```python**), it is not rendered. (checking with a GitHub preview)

**Comment by Sudeepam97** [comment]
@dynamicwebpaige, for now, I have specified *python* after the backticks, just as you have stated in your example, would be glad to work if any changes are required.

Also, I have a few questions regarding the modification of other API docs, and a few questions related to the mentoring of GSoC projects for TensorFlow, which I believe can be best answered by you. If you can find the time, then what would be a good place (email / twitter etc.) to ask?

**Comment by rthadur** [comment]
similar changes are pushed by different PR ,so closing this

**Pull request closed without merging**
