### PR TITLE
:memo: Adding quick guide in Keras documentation

### PR DESCRIPTION
**Pull request by vaibhavarora102**
I had tried to add a quick guide to make the DNN model using  Keras API, which code be very beneficial for beginners and new to TensorFlow or Keras.
I had tried to add short comments to give insights for the code. Being my first contribution there is the scope of error in depicting or any other mean if so, kindly guide me, I would definitely try to stand on community needs and be part of this community.

### CODE REVIEW

**Comment by vaibhavarora102** [comment]
@googlebot I signed it!

**Comment by vaibhavarora102** [comment]
@qlzh727 
Sir, I am new to Open source, Kindly review and tell the scope of improvement and give a quick start to my open source journey.
thanks

**Review by qlzh727 — CHANGES_REQUESTED** [review]
We try to consolidate all the keras related doc in keras.io. You can send the PR there if you feel the added example is useful.

**Comment by qlzh727** [comment]
Closing this PR since I don't think we will move forward on TF side. Feel free to reopen if you feel otherwise.

**Pull request closed without merging**
