### PR TITLE
Remove redundant word "the"

### PR DESCRIPTION
**Pull request by johnlinp**

### CODE REVIEW

**Review by MarkDaoust — DISMISSED** [review]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by MarkDaoust** [comment]
Thanks @johnlinp

Can you resolve that conflict in: "tensorflow/contrib/lite/python/op_hint.py"

**Comment by johnlinp** [comment]
Hi @MarkDaoust, the conflict is resolved. Thanks.

**Comment by angersson** [comment]
Thanks for the fix!

**Pull request merged**
