### PR TITLE
Adding tensorflow as a default custom_object in keras.models.load_model

### LINKED ISSUE #27364: Include TF in keras.models.load_model for custom functions
**System information**
- TensorFlow version (you are using): Latest
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

```
from keras import models, layers
import tensorflow as tf
in_tensor = layers.Input((50, 1), name='InSpeech')
def sum_tensor(x):
  return tf.reduce_sum(x, 1)
sum_out = layers.Lambda(sum_tensor, name='SumTensor')(in_tensor)
k_model = models.Model(inputs=[in_tensor],
            outputs=[sum_out])
k_model.save('sum_model.h5')
```

Loading the model

```
models.load_model('sum_model.h5')
```

or 

```
tf.lite.TFLiteConverter.from_keras_model_file('sum_model.h5')
```

Results in the error message:
```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py in sum_tensor(x)
      3 in_tensor = layers.Input((50, 1), name='InSpeech')
      4 def sum_tensor(x):
----> 5   return tf.reduce_sum(x, 1)
      6 sum_out = layers.Lambda(sum_tensor, name='SumTensor')(in_tensor)
      7 k_model = models.Model(inputs=[in_tensor],

NameError: name 'tf' is not defined
```

While running `models.load_model('sum_model.h5', custom_objects={'tf': tf})` works fine. Unfortunately with the tflite wrapper function to convert models you cannot specify custom objects.

**Will this change the current api? How?**

No, it would just make the default custom objects include tensorflow.

**Who will benefit with this feature?**

Anyone using simple tensorflow-derived lambda functions inside of the HDF5 models in Keras. In particular people hoping to convert the models to tflite.

### PR DESCRIPTION
**Pull request by kmader**
Adding tensorflow and tf as default custom objects. The commit makes it easier to include simple tensorflow operations as part of keras models (like `tf.reduce_sum` for example) and then reload the model without issues.
- Closes https://github.com/tensorflow/tensorflow/issues/27364

### CODE REVIEW

**Comment by kmader** [comment]
Just as a note, I realize that in this specific case, running `K.sum(x, 1)` instead of `tf.reduce_sum(x, 1)` will work, but there are a number of tensorflow Ops that are not available in `keras.backend`

**Comment by tensorflowbutler** [comment]
Nagging Reviewers @k-w-w, @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by fchollet** [comment]
Thanks for the PR. The issue above is readily resolved by using `tf.reduce_sum` without wrapping it in a Lambda layer. This will result in a serializable TensorFlowOp layer.

**Comment by kmader** [comment]
@fchollet but using the unwrapped ```tf.reduce_sum``` means you cannot use the incredibly convenient hdf5 model saving feature of keras (you have to save it with tf tools)

**Pull request closed without merging**
