### PR TITLE
add checking for input values in GANHead constructor

### PR DESCRIPTION
**Pull request by alexpantyukhin**

### CODE REVIEW

**Comment by alexpantyukhin** [comment]
@martinwicke Hello, what status of this PR?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @joel-shor: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Review by joel-shor — CHANGES_REQUESTED** [review]
If you add the optimizer, you should add it to the build rule as well. however, checking that it is an optimizer might be too restrictive, so I'm in favor of dropping the new import and dropping the optimizer check. Up to you

**Comment by alexpantyukhin** [comment]
Hi @joel-shor . Thank you very much for your review. Yes, I'm agree with you comment. Now it's fixed.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment]
@joel-shor can you take a look and see whether you have any more comments?

**Review by joel-shor — APPROVED** [review]

**Comment by martinwicke** [comment]
The build failure is unrelated (and also on master, probably infra)

**Pull request merged**
