### PR TITLE
[XLA] Add override of Permute to fix compile errors

### PR DESCRIPTION
**Pull request by tatatodd**
This is an attempted fix for older compilers that can't deduce the template args.

### CODE REVIEW

**Comment by yifeif** [comment]
@tatatodd is this one ready to be merged?

**Comment by tatatodd** [comment]
@yifeif No, this isn't ready to be merged; it's an attempted fix for #10843, which we're still working out.

Thanks for checking though!  I'll ping when it is eventually ready.

**Comment by yifeif** [comment]
Got it, sounds good. Thanks @tatatodd!

**Comment by tatatodd** [comment]
Jenkins, please test this.

**Comment by tatatodd** [comment]
@asimshankar For context, this is the fix for the variadic template issue you helped me look at.

**Review by asimshankar — APPROVED** [review]

**Pull request merged**
