### PR TITLE
BUG: log_cosh alias missing results in round-trip serialization failure

### PR DESCRIPTION
**Pull request by adriangb**
See https://colab.research.google.com/drive/1AfOBJTHOYngsPEn3Fo4rkeD4kUJG3eil#scrollTo=_pyJctK__Btb

```python3
from tensorflow.keras.metrics import deserialize, serialize

deserialize("mse")  # returns tensorflow.python.keras.losses.mean_squared_error
# so let's try deserialize("mean_squared_error")
deserialize("mean_squared_error") # returns tensorflow.python.keras.losses.mean_squared_error

deserialize("logcosh")  # returns tensorflow.python.keras.losses.log_cosh
# so let's try deserialize("log_cosh")
deserialize("log_cosh") # ValueError: Unknown metric function: log_cosh

deserialize(serialize(deserialize("mse")))  # roundtrip works

deserialize(serialize(deserialize("logcosh")))  # roundtrip breaks
```

### CODE REVIEW

**Comment by adriangb** [comment]
And more generally, is there any way to convert from the shorthand to the "official" names for metric/loss functions, or is the best way for me to make a function like:

```python3
def get_loss_metric_full_name(name: str) -> str:
    mapping = {
        "acc": "accuracy",
        "bce": "binary_crossentropy",
        "mse": "mean_square_error",
        "mean_squared_error": "mean_square_error",
        "mae": "mean_absolute_error",
        "mape": "mean_absolute_percentage_error",
        "msle": "mean_squared_logarithmic_error",
        "cosine_similarity": "cosine_proximity",
        "kld": "kl_divergence",
        "kullback_leibler_divergence": "kl_divergence",
        "logcosh": "log_cosh",
        "huber_loss": "huber",
    }
    if name.lower() in mapping.keys():
        return mapping[name.lower()]
    if name.lower() in mapping.values():
        return name.lower()
    if name == "loss":
        return name
    raise ValueError(f"Unknonw loss/metric '{name}'")
```

Where I'm just copy/pasting the names and hoping they don't change.

**Review by pavithrasv — APPROVED** [review]
Thank you for the PR!

**Comment by adriangb** [comment]
@pavithrasv do you think you could help answer the question in my above comment? Thanks!

**Comment by adriangb** [comment]
@pavithrasv testing with the latest `tf-nightly` it seems that neither `log_cosh` nor `logcosh` are in `tensorflow.keras.metrics.__init__.py`. Apparently that is an auto-generated file. Do we need to add these two to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/api/golden/v2/tensorflow.keras.metrics.pbtxt or something? What am I missing here? Happy to try to help fix anything. Thanks!

**Comment by pavithrasv** [comment]
Yes. We currently have `'keras.losses.log_cosh', 'keras.losses.logcosh'` exports for the logcosh function. Can you add `'keras.metrics.log_cosh', 'keras.metrics.logcosh'` to this list?

**Pull request merged**
