### PR TITLE
[Intel MKL] Fix docker ffmpeg issue

### PR DESCRIPTION
**Pull request by wei-v-wang**
Comment in the "apt-get install" broke the command stream: https://github.com/NervanaSystems/private-tensorflow/blob/master/tensorflow/tools/ci_build/install/install_deb_packages.sh#L47 

Restart the apt-get install ffmpeg after comment. 

@yifeif  FYI.

### CODE REVIEW

**Comment by wei-v-wang** [comment]
Fixes Public CI failure: https://tensorflow-ci.intel.com/job/tensorflow-mkl-linux-cpu/3003/console 
[bdw] [91m/install/install_deb_packages.sh: line 49: ffmpeg: command not found
[bdw] [0mThe command '/bin/sh -c /install/install_deb_packages.sh' returned a non-zero code: 127

**Comment by tensorflow-copybara** [comment]
Sorry about this and thanks for sending a fix @wei-v-wang! I actually just about to submit the same fix internally. I will close this PR once it propagates to GitHub if you don't mind. Thanks again!

**Comment by yifeif** [comment]
Sorry about this and thanks for sending a fix @wei-v-wang! I actually just about to submit the same fix internally. I will close this PR once it propagates to GitHub if you don't mind. Thanks again!

**Comment by wei-v-wang** [comment]
Ok, great. Thanks for the update!

**Pull request closed without merging**
