### PR TITLE
Clarify that negative values are valid for adjust_brightness.

### LINKED ISSUE #42704: Clarify that tf.image.adjust_brightness accepts negative values
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/image/adjust_brightness

## Description of issue (what needs changing):

The documentation states that delta should be in the range [0, 1). However, the delta is added to the image so negative values in the range (-1, 0] are also valid, and useful if the image should be made darker.

### Clear description

It is useful to be able to darken images, and the documentation should make it clear how to do so.

### PR DESCRIPTION
**Pull request by hwaxxer**
Fixes #42704.

### CODE REVIEW

**Comment by gbaned** [comment]
@hwaxxer Can you please sign CLA. Thanks!

**Comment by hwaxxer** [comment]
@googlebot I signed it!

**Review by alextp — DISMISSED** [review]

**Comment by gbaned** [comment]
@hwaxxer  Can you please address Ubuntu Sanity errors? Thanks!

**Comment by gbaned** [comment]
@hwaxxer  Any update on this PR? Please. Thanks!

**Comment by hwaxxer** [comment]
@gbaned Should be fixed now!

**Review by rthadur — APPROVED** [review]

**Pull request merged**
