### PR TITLE
WIP: ENH: only master is allowed to export model

### LINKED ISSUE #13849: Feature request: only master is allowed to export for `tf.contrib.learn.Experiment`
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac 10.11.6
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4.0-nightly, 1.3.0
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem

When using `tf.contrib.learn.Experiment` for distributed training, it seems that all workers, ps, and master try to export model when finished. However, this will cause write conflict when `model_dir` is on hdfs, because all write the same file to the same location.

Hence, I propose that only master is allowed to export model.
I can work on it if tensorflowers're agreed.

### Source code / logs

```python
INFO:tensorflow:Saving dict for global step 30: accuracy = 0.339453, global_step = 30, loss = 70112.8
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    tf.app.run()
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 56, in main
    sess.run()
  File "/Users/facai/Workshop/sina/Prometheus/prometheus/python/session.py", line 172, in run
    ex.train_and_evaluate()
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 641, in train_and_evaluate
    export_results = self._maybe_export(eval_result)
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 744, in _maybe_export
    eval_result=eval_result))
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/export_strategy.py", line 87, in export
    return self.export_fn(estimator, export_path, **kwargs)
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/utils/saved_model_export_utils.py", line 454, in export_fn
    checkpoint_path=checkpoint_path)
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1307, in export_savedmodel
    builder = saved_model_builder.SavedModelBuilder(temp_export_dir)
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/python/saved_model/builder_impl.py", line 88, in __init__
    "directory: %s" % export_dir)
AssertionError: Export directory already exists. Please specify a different export directory: file:///tmp/facai/prome/model/new/export/Servo/temp-1508482645
```

### PR DESCRIPTION
**Pull request by facaiy**
Fix #13849 

If the proposition is accepted, I'll add the corresponding test case later.

### How to test

+ [ ] add unit test
+ [ ] pass all tests

### CODE REVIEW

**Comment by facaiy** [comment]
Thank you, @xiejw . I'll post the information required next Monday.

**Comment by facaiy** [comment]
@xiejw This is the TF_CONFIG:
```bash
INFO:tensorflow:TF_CONFIG:
{"environment": "cloud", 
  "cluster": {
    "ps": ["77-112-184-hadoop:2955"], 
    "worker": ["77-112-168-hadoop:7181", "77-112-174-hadoop:5564", "77-16-119-hadoop:6089", "77-112-184-hadoop:5587"],
    "master": ["77-113-54-hadoop:5290"]},
  "task": {"index": 0, "type": "worker"}}
```

**Comment by xiejw** [comment]
This is one TF_CONFIG for the first worker (as the index is 0). Is this the worker in question (which triggers the export)?

By default, the tf.contrib.learn.learn_runner will call Experiment.train for you (as this is worker), which does not trigger export by default. Did you modify the default behavior (by passing a different schedule)?

**Comment by facaiy** [comment]
Thank you. 

We use `contrib.learn.estimator`, instead of `tf.estimator`. Will it be a problem? Code is pasted here.

```python
        estimator = config.get_estimator()

        logging.info("generate export config...")
        columns = config._get_columns(only_used=True)
        serving_input_fn = _get_serving_input_fn(columns)
        export_strategies = make_export_strategy(
            serving_input_fn=serving_input_fn)

        logging.info("generate experiment...")
        ex = Experiment(estimator,
                        train_input_fn=train_input_fn,
                        eval_input_fn=test_input_fn,
                        train_steps=self.fit_steps,
                        eval_steps=self.evaluate_steps,
                        export_strategies=export_strategies)

        logging.info("train and evaluate....")
        ex.train_and_evaluate()

```


this is all the logs:
```bash
##### master0

INFO:tensorflow:TF_CONFIG:
{"environment": "cloud", "cluster": {"ps": ["77-112-184-hadoop:2955"], "worker": ["77-112-168-hadoop:7181", "77-112-174-hadoop:5564", "77-16-119-hadoop:6089", "77-112-184-hadoop:5587"], "master": ["77-113-54-hadoop:5290"]}, "task": {"index": 0, "type": "master"}}

INFO:tensorflow:SavedModel written to: hdfs://77-16-121-hadoop:9000/user/zhongwei5/prometheus/output/export/Servo/1508406233/saved_model.pb


##### worker0
INFO:tensorflow:TF_CONFIG:
{"environment": "cloud", "cluster": {"ps": ["77-112-184-hadoop:2955"], "worker": ["77-112-168-hadoop:7181", "77-112-174-hadoop:5564", "77-16-119-hadoop:6089", "77-112-184-hadoop:5587"], "master": ["77-113-54-hadoop:5290"]}, "task": {"index": 0, "type": "worker"}}

Traceback (most recent call last):
AssertionError: Export directory already exists. Please specify a different export directory: hdfs://77-16-121-hadoop:9000/user/zhongwei5/prometheus/output/export/Servo/1508406233


##### worker1
INFO:tensorflow:TF_CONFIG:
{"environment": "cloud", "cluster": {"ps": ["77-112-184-hadoop:2955"], "worker": ["77-112-168-hadoop:7181", "77-112-174-hadoop:5564", "77-16-119-hadoop:6089", "77-112-184-hadoop:5587"], "master": ["77-113-54-hadoop:5290"]}, "task": {"index": 1, "type": "worker"}}

AssertionError: Export directory already exists. Please specify a different export directory: hdfs://77-16-121-hadoop:9000/user/zhongwei5/prometheus/output/export/Servo/1508406233

##### worker2
INFO:tensorflow:TF_CONFIG:
{"environment": "cloud", "cluster": {"ps": ["77-112-184-hadoop:2955"], "worker": ["77-112-168-hadoop:7181", "77-112-174-hadoop:5564", "77-16-119-hadoop:6089", "77-112-184-hadoop:5587"], "master": ["77-113-54-hadoop:5290"]}, "task": {"index": 2, "type": "worker"}}

INFO:tensorflow:SavedModel written to: hdfs://77-16-121-hadoop:9000/user/zhongwei5/prometheus/output/export/Servo/1508406234/saved_model.pb

##### worker3
INFO:tensorflow:TF_CONFIG:
{"environment": "cloud", "cluster": {"ps": ["77-112-184-hadoop:2955"], "worker": ["77-112-168-hadoop:7181", "77-112-174-hadoop:5564", "77-16-119-hadoop:6089", "77-112-184-hadoop:5587"], "master": ["77-113-54-hadoop:5290"]}, "task": {"index": 3, "type": "worker"}}

AssertionError: Export directory already exists. Please specify a different export directory: hdfs://77-16-121-hadoop:9000/user/zhongwei5/prometheus/output/export/Servo/1508406234


##### ps0
INFO:tensorflow:TF_CONFIG:
{"environment": "cloud", "cluster": {"ps": ["77-112-184-hadoop:2955"], "worker": ["77-112-168-hadoop:7181", "77-112-174-hadoop:5564", "77-16-119-hadoop:6089", "77-112-184-hadoop:5587"], "master": ["77-113-54-hadoop:5290"]}, "task": {"index": 0, "type": "ps"}}

AssertionError: Export directory already exists. Please specify a different export directory: hdfs://77-16-121-hadoop:9000/user/zhongwei5/prometheus/output/export/Servo/1508406233

```

**Comment by xiejw** [comment]
All TF_CONFIGs look good to me. 

I think the issue is you are calling the Experiment improperly. 

Your code runs on all jobs (master, worker and ps). The same code should behave differently. The code runs on master handling the eval and export in addtion to training. The code on worrk only trains the model. ps handles the data sharing. 

In order to achieve that, Experiment class has multiple methods (called schedule). The "schedule" specifies the code to run. 

For master, the schedule should be train_and_evaluate. For worker, the schedule should be train.  User does not need to set the schedule. tf.contrib.learn.learn_runner handles that for your automatically. 

See you see the example in the docstring [1]. The schedule argument should be absent for most cases, as the default is good enough. So, the simplest way is

    def _create_my_experiment(run_config, hparams):
        # You can change a subset of the run_config properties as
        #   run_config = run_config.replace(save_checkpoints_steps=500)
        return tf.contrib.learn.Experiment(
          estimator=my_estimator(config=run_config, hparams=hparams),
          train_input_fn=my_train_input,
          eval_input_fn=my_eval_input)

    learn_runner.run(
          experiment_fn=_create_my_experiment,
          run_config=run_config_lib.RunConfig(model_dir="some/output/dir"))

[1] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/learn_runner.py#L119

**Comment by vrv** [comment]
It looks like a change to the estimator is not needed to get this to work, so I'm going to close the PR for now; perhaps one could move this discussion to stackoverflow / github issue until it is clear a PR is needed.  Thanks!

**Pull request closed without merging**
