### PR TITLE
Extend #3020 to decode animated GIF

### PR DESCRIPTION
**Pull request by raingo**
#3020 has been squashed into a single commit, with proper authorship acknowledgment. I'll squash my commits after code review.

This PR extends #3020 by loading all frames. The underlying library  `giflib` is too low level to handle the GIF optimizations properly, so an error will be raised if the source GIF is optimized.

For the test, a synthetic file is used to test the actual decoded content.

Please review @buaaliyi @martinwicke

### CODE REVIEW

**Comment by caisq** [comment]
@tensorflow-jenkins test this please. (Preliminary testing prior to detailed review).

**Comment by caisq** [comment]
There are test failures. Please take a look: http://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/1261/consoleFull

**Comment by raingo** [comment]
Hi @caisq ,

I checked the logs, and the errors are that the testdata can't be found. Is it a mistake in the testing framework? because the tests have passed on my local machine before I submitted here, and the same tests have passed in the other buckets. 

```
NotFoundError: tensorflow/core/lib/gif/testdata/optimized.gif
NotFoundError: tensorflow/core/lib/gif/testdata/scan.gif
```

Thanks!

**Comment by martinwicke** [comment]
I'll merge #3020 so CLAbot will be happy. The test failure is a test on installation failure. Test data for those tests needs to be copied manually (by the testing framework). Add the relevant lines here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/builds/test_installation.sh#L243

**Comment by raingo** [comment]
@martinwicke Added the lines to copy test data over

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by martinwicke** [comment]
Assuming this passes, could you squash this PR into two commits: one containing @buaaliyi's changes and one containing yours? Then I can merge without squashing and we'll preserve authorship and have a nice tree.

**Comment by raingo** [comment]
There is a conflict with HEAD, so I have to merge and resolve. I don't know how to get rid of the merge commit message.

**Comment by martinwicke** [comment]
Yeah, so three commits, that's fine.

**Comment by buaaliyi** [comment]
@googlebot  I'm okey.

**Comment by martinwicke** [comment]
Jenkins, test this please

CLAbot is broken I guess.

**Comment by martinwicke** [comment]
Hooray! Thank you!

**Comment by buaaliyi** [comment]
Greate!

**Comment by raingo** [comment]
Great! Thanks!

**Pull request merged**
