### PR TITLE
Intel MKL : Fixed variable initialization, pass Clockworks and fixed Clang format

### PR DESCRIPTION
**Pull request by ashraf-bhuiyan**
Minor edits.
Fixed variable initialization issue, thus now passed the Clockworks test. 
Also fixed Clang format.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for your PR!

**Comment by penpornk** [comment]
@rthadur Could you please help merge this?

**Comment by rthadur** [comment]
> @rthadur Could you please help merge this?

sure

**Comment by penpornk** [comment]
@rthadur Thank you!

**Pull request merged**
