### PR TITLE
Remove boston_input_fn_with_queue

### PR DESCRIPTION
**Pull request by zhaojunz**
since it is not used.

### CODE REVIEW

**Comment by drpngx** [comment]
@fwiffo what do you think?

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Comment by caisq** [comment]
@tensorflow-jenkins test this please

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
Test failure seems unrelated.

**Comment by caisq** [comment]
Right. The test failure in //tensorflow/contrib/xla_tf_graph:xla_tf_graph_util_test is unrelated. (But we need to look into that separately.) Merging PR.

**Pull request merged**
