### PR TITLE
 Fix duplicated return in the fullconnect

### PR DESCRIPTION
**Pull request by yzhou51**
Remove the duplicated return statement in the 'CreateFullyConnected'.

### CODE REVIEW

**Comment by yzhou51** [comment]
Hi, 
How to re-run the CI check? It seems caused by the CI system.

**Comment by keerthanakadiri** [comment]
Hi @vamsimanchala, Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @vamsimanchala, Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @vamsimanchala, Can you please review this PR? Thank you !

**Review by mihaimaruseac — APPROVED** [review]

**Comment by yzhou51** [comment]
How to fix the "AMD ROCm" CI building failure? It seems not caused by this Pull request.

**Comment by mihaimaruseac** [comment]
It's pending on internal review, that AMD ROCm job failure is in every PR and should be removed from here.

See https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#how-to-become-a-contributor-and-submit-your-own-code

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Unsure why this stalled for so long. I'm OOO now but will have to check again when I'm back

**Comment by mihaimaruseac** [comment]
Oh, this actually landed, just Copybara did not close the PR.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/common/tasks/fully_connected.cc

Likely, https://github.com/tensorflow/tensorflow/commit/98e7b330a13e15c41ed78465d58397c57c4f84a4 is because Copybara integration was broken and then the fix requires squashing a bunch of changes into a single commit.

Thank you for the contribution.

**Pull request closed without merging**
