### PR TITLE
Syntactic Sugar: Utilizing dict comprehension

### PR DESCRIPTION
**Pull request by Horstage**

### CODE REVIEW

**Comment by Horstage** [comment]
I signed it!

**Review by yifeif — DISMISSED** [review]
Thanks for the PR @Horstage

**Comment by yifeif** [comment]
hi @Horstage, do you mind fixing the pylint error in the sanity build?

**Comment by yifeif** [comment]
Thank you @Horstage!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
@Horstage could you pull rebase and push again? Thanks.

**Pull request merged**
