### PR TITLE
Disable keras data_utils_test as it's flaky.

### PR DESCRIPTION
**Pull request by av8ramit**

### CODE REVIEW

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by gunan** [comment]
If you also need to disable it in cmake builds, you will need to add it to the test blacklist in `tensorflow/contrib/cmake/tf_tests.cmake`

**Comment by rmlarsen** [comment]
@av8ramit is this still relevant?

**Comment by av8ramit** [comment]
@m3bm3b I was having issues with this test as buildcop. If this is still occurring please feel free to merge. If not I can revert this.

**Comment by gunan** [comment]
The flakiness is on windows, which is not addressed by this PR.
I will close this for now, and we can disable it in cmake build if we see the flake again.

**Pull request closed without merging**
