### PR TITLE
Addition of TanhExp activation function - issue #45929

### PR DESCRIPTION
**Pull request by sangireddysiva**
Addition of TanhExp activation function based on issue #45929 that leads changes to tensorflow/python/keras/activations.py and tensorflow/python/ops/nn_impl.py

### CODE REVIEW

**Comment by sangireddysiva** [comment]
> @googlebot I signed it!

**Comment by ematejska** [comment]
The API owners are moving to a rotation based system instead of the meetings and assigning several owners to follow along and review.  Adding @fchollet, @manivaradarajan

**Comment by mihaimaruseac** [comment]
This should be opened against master, not a release branch

**Comment by sangireddysiva** [comment]
> This should be opened against master, not a release branch

A new pull request has been created for the master branch - https://github.com/tensorflow/tensorflow/pull/47566

**Pull request closed without merging**
