### PR TITLE
issue-4737

### PR DESCRIPTION
**Pull request by guotong1988**
Issue description: https://github.com/tensorflow/tensorflow/issues/4737
I test it by: 

```
x = tf.constant(-1,tf.float32)
y = tf.nn.elu(x)
dy = tf.gradients(y,x)
ddy = tf.gradients(dy,x)
dddy = tf.gradients(ddy,x)

elu2 = lambda x: tf.select(x < 0., tf.exp(x) - 1., x)
dy2 = tf.gradients(elu2(x), x)
ddy2 = tf.gradients(dy2,x)

with tf.Session() as sess:
    print sess.run(dy2)
    print sess.run(ddy2)
    print sess.run(dy)
    print sess.run(ddy)
    print sess.run(dddy)
```

### CODE REVIEW

**Comment by benoitsteiner** [comment]
Thanks for the contribution. Can you extend the tests in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/relu_op_test.py to also cover the second order derivatives for Elu ? Thanks.

**Comment by guotong1988** [comment]
OK

**Comment by drpngx** [comment]
@guotong1988 , to be clear, did you address Benoit's request?

**Comment by guotong1988** [comment]
I already commit the unit test.

**Review by benoitsteiner — APPROVED** [review]

**Comment by drpngx** [comment]
Jenkins, test this please.

**Pull request merged**
