### PR TITLE
[tflite] [gpu] Add DHWC4 no-copy support

### PR DESCRIPTION
**Pull request by natario1**
See discussion in #44336 . The GPU delegate [README](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/gpu#tips-and-tricks) currently promotes the possibility to send input in DHWC4 format to avoid an useless buffer copy. In practice, this does not work, at least for SSBOs, and that is, because:

- The `DefaultTensorTie` in `api2.cc` does not register the external SSBO to the object manager, so that the runtime in `runtime.cc` is not able to find the tensor object.
- The `Runtime` in `runtime.cc` retrieves the buffers and creates binding functions for them at initialization time. This means that this op is done during `InferenceBuilder::Builld`, which is **before** we can attempt to provide the real object through `InferenceRunner::SetInputObject`, for example.

This PR introduces two changes to address these issues:
- The `Runtime` now acknowledges the fact that external objects are not immutable (which is clear looking at the fact that InferenceRunner has setters for them). So, **only for external objects**, they are now retrieved and validated at binding time, not initialization time. This way inference invocations can pick up the latest buffer available.
- The `DefaultTensorTie`, which is the component that pipes the external user-defined `TensorObject` to the internal one, recognizes the case where we want to have a DHWC4 no-copy piping, and correctly registers the buffer to the ObjectManager. The tie also registers a placeholder object at initialization time, for the runtime to initialize properly.

Using DHWC4 input gave me a 25% performance boost in my tests on a super simple model (take image, output the mean).

### CODE REVIEW

**Comment by gbaned** [comment]
@natario1  Can you please resolve conflicts? Thanks!

**Comment by natario1** [comment]
@gbaned could you please give some high-level opinion first? I haven't looked at conflicts in depth, but recent commits are actually doing something very similar: 

https://github.com/tensorflow/tensorflow/commit/bcd5dd0148ebdbbd93875049598b02b73bae8e30#diff-1ad703f1ca05896beb3921399d6486250abdad7e5ca027cd62568052ff5a177f

Seems to be what I have suggested in #44336 (which got no answer) and tried to implement here. So if the team is already working on this, we're in good hands and we can close the PR. Thanks!

**Comment by ekaterinaignasheva** [comment]
Thank you, @natario1 for bringing this issue to our attention. The [internal fix](https://github.com/tensorflow/tensorflow/commit/bcd5dd0148ebdbbd93875049598b02b73bae8e30), which you already mentioned, was ready by the time you sent your PR and it just took some time to submit. We appreciate your proactive interest to solving this problem. On our end we verified no-copy DHWC4 inputs work correctly now, hope things got fixed on your end too. Please, keep sending us bugs in the future, if you spot one, your finding was very helpful!

**Comment by natario1** [comment]
@ekaterinaignasheva I'll test when it's released, thanks. One issue that I'm seeing with my implementation (which is very similar to yours) is that no-copy DHWC4 actually slows execution down when OpenCL is available. Compare third and fourth plots in #46486 for example... I wonder if the CL delegate has some issues similar to the GL issues that we fixed here.

**Comment by gbaned** [comment]
@natario1 Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
As per confirmation from @ekaterinaignasheva, closing this PR since problem was solved.

**Pull request closed without merging**
