### PR TITLE
Adding documentation about contrib.losses

### PR DESCRIPTION
**Pull request by alanyee**
-Add information for update from tf.contrib.losses.hinge_loss to tf.losses.hinge_loss
-Add more notes of deprecation
-Other minor corrections and updates

### CODE REVIEW

**Comment by alextp** [comment]
Jenkins, test this please.

**Review by alextp — APPROVED** [review]

**Comment by jhseu** [comment]
Jenkins, test this please

**Comment by alanyee** [comment]
Ah I misread which word was the noun.

**Comment by jhseu** [comment]
Jenkins, test this please

**Pull request merged**
