### PR TITLE
Add deprecated_args decoration to array_ops/ sparse_ops

### PR DESCRIPTION
**Pull request by imsheridan**
This PR is to add deprecated_args decoration to several ops in array_ops/ sparse_ops as below:
- [tf.reverse_sequence](https://www.tensorflow.org/api_docs/python/tf/reverse_sequence)
- [tf.sparse_concat](https://www.tensorflow.org/api_docs/python/tf/sparse_concat)
- [sparse_split](https://www.tensorflow.org/api_docs/python/tf/sparse_split)

### CODE REVIEW

**Comment by asimshankar** [comment]
(OK for API change)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Review by martinwicke — APPROVED** [review]

**Comment by yongtang** [comment]
There are some sanity build issues introduced by this PR:
```
53 FAIL: Found 4 non-whitelited pylint errors:
54 tensorflow/python/ops/sparse_ops.py:87: [C0301(line-too-long), ] Line too long (94/80)
55
56 tensorflow/python/ops/sparse_ops.py:594: [C0301(line-too-long), ] Line too long (92/80)
57
58 tensorflow/python/ops/array_ops.py:2622: [C0301(line-too-long), ] Line too long (92/80)
59
60 tensorflow/python/ops/array_ops.py:2623: [C0301(line-too-long), ] Line too long (98/80)
```

Created a PR #19327 for the pylint fix.

**Comment by martinwicke** [comment]
@yifeif was this Kokoro swallowing results without telling us? I only saw the summary view all green and merged, but it only shows GPU and Ubuntu CC -- I believe those shouldn't even run if sanity breaks, no?

Thank you @yongtang for the fix!

**Comment by yifeif** [comment]
This was due to the Kokoro flag. It should be fixed with the rollback. We are no long blocking other builds with sanity. But we can add all builds to merge requirements(currently only cc build is).

**Pull request merged**
