### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by nouiz**
A few small changes:
- Rename a variable.
- Better error message.
- More complete help message.
- Small doc fix.

@sanjoy  @thomasjoerg

### CODE REVIEW

**Review by sanjoy — CHANGES_REQUESTED** [review]
We disable the signed vs. unsigned comparison warning in google since it is too noisy.  Can you do the same in OSS instead of changing adding explicit casts to unsigned integers?  Otherwise it is only a matter of time before these kinds of expressions creep back in.

**Comment by nouiz** [comment]
> We disable the signed vs. unsigned comparison warning in google since it is too noisy. Can you do the same in OSS instead of changing adding explicit casts to unsigned integers? Otherwise it is only a matter of time before these kinds of expressions creep back in.

I only fixed a few. It is true that I saw tons of those warnings that I didn't fix.

I didn't had the line 'build:opt --copt=-Wno-sign-compare' in my .tf_configure.bazelrc file. It is added by default by the configure script. So the problem was in my config. I'll make sure it stay fixed.

If you think of something else to change to this PR, tell me.

**Comment by sanjoy** [comment]
> If you think of something else to change to this PR, tell me.

Can you please revert the signed int -> unsigned changes in this PR?

**Comment by nouiz** [comment]
I removed the commit from the history.

**Comment by nouiz** [comment]
There was a conflict. I rebased and force-pushed to fix it. This needed small change in the last commit.

**Review by sanjoy — DISMISSED** [review]

**Comment by nouiz** [comment]
The CI was failing. The rebase broked stuff that I didn't catched up before. Now it should be fine to start the CI again.

**Comment by nouiz** [comment]
The Mac CI failed, but I can't see why. I would be surprised that this is related to my PR. What should I do?

**Comment by sanjoy** [comment]
> The Mac CI failed, but I can't see why. I would be surprised that this is related to my PR. What should I do?

I'll manually merge this.

**Pull request merged**
