### PR TITLE
replace is_real with is_floating, remove is_real

### PR DESCRIPTION
**Pull request by yaroslavvb**
@martinwicke 

Haven't tested (because of https://github.com/tensorflow/tensorflow/issues/6911 testing time goes 1 min -> 20 mins every time you switch branch)

### CODE REVIEW

**Comment by martinwicke** [comment]
Jenkins, test this please!

**Comment by martinwicke** [comment]
Thank you!

**Comment by martinwicke** [comment]
@caisq, this will fix the API modification in the pull.

**Comment by caisq** [comment]
Thanks, @yaroslavvb

**Review by caisq — APPROVED** [review]

**Pull request merged**
