### PR TITLE
Set workspace name

### LINKED ISSUE #2040: building pip package issue
```
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
2016年 04月 21日 星期四 07:34:12 CST : === Using tmpdir: /tmp/tmp.cMsLMGw3bz
cp: cannot stat ‘bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/tensorflow’: No such file or directory
cp: cannot stat ‘bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/external’: No such file or directory
```

### PR DESCRIPTION
**Pull request by kchodorow**
Adds the workspace name to runfiles paths, removes a hack introduced in
https://github.com/tensorflow/tensorflow/commit/8cda66e19c0bdc6d8fc373fdcefcc644ab5ecfa3,
and fixes #2040.

### CODE REVIEW

**Comment by vrv** [comment]
Does this require a specific version of bazel to be installed, btw?

**Comment by kchodorow** [comment]
Yes, this will only work with 0.2.3+ (see https://groups.google.com/d/msg/bazel-discuss/_Xo14sf7fHw/g7wdatTGBgAJ for more info about the change).  For this to work with older versions, I can make it check both paths and use whichever exists.

**Comment by vrv** [comment]
Given that 0.2.3 isn't officially released yet, I think we'd prefer to try to make it work with both versions, at least for a little transition period.

**Comment by kchodorow** [comment]
Okay, finally updated this, at least according to the test suite this should now work with old and new versions of Bazel.

**Comment by vrv** [comment]
@tensorflow-jenkins test this please

**Comment by kchodorow** [comment]
Whoops, I didn't realize your CI was still on 0.2.1, should be fixed it for that version (and previous versions), too.

**Comment by vrv** [comment]
We should probably upgrade our CI to use a newer version of bazel, but supporting older is good too, particularly since check_version requires 0.2.1 right now

@tensorflow-jenkins test this please

**Pull request merged**
