### PR TITLE
Fix the issue#4138

### PR DESCRIPTION
**Pull request by DjangoPeng**
Fix the issue #4138 
Redefine the `w` and `w_t` for improving the efficiency in case of handling sparse `IndexedSlices` objects

### CODE REVIEW

**Comment by danmane** [comment]
@lukaszkaiser Please take a look.

**Comment by lukaszkaiser** [comment]
Looks good to me, thanks! Does it really give a speedup? (We should merge it anyway, I think, just curious).

**Comment by DjangoPeng** [comment]
@lukaszkaiser The issue shows it gives a speedup and set a `contribution welcome ` tag. So, I think it maybe help to do this. At least, it can'b be worse.

**Comment by lukaszkaiser** [comment]
Let's merge this! Is anything blocking it?

**Comment by DjangoPeng** [comment]
@lukaszkaiser I don't know, what happened when you merge?  My branch is still has the commit

**Comment by danmane** [comment]
@tensorflow-jenkins test this please

**Comment by danmane** [comment]
@lukaszkaiser, based on your comments I think you might have meant to merge this and closed the PR instead? I'm re-opening it and testing it :)

**Comment by DjangoPeng** [comment]
@danmane ooh..I got your point! 👍

**Comment by DjangoPeng** [comment]
@lukaszkaiser Could you merge it? :)

**Comment by lukaszkaiser** [comment]
I'm not authorized to merge. vrv -- could you merge?

**Comment by lukaszkaiser** [comment]
Please merge.

**Pull request merged**
