### PR TITLE
[r1.15Cherrypick]: Cherry-pick #30893 to r1.15

### LINKED ISSUE #32401: GPU NMS kernel in TF 1.15rc0 was not fixed
This commit:
https://github.com/tensorflow/tensorflow/commit/9480262cbbfc2430b0c53424f0fc133418d7ae3f
was included in TF 1.15rc0.

However, this commit has a bug as pointed out in https://github.com/tensorflow/tensorflow/pull/28745#issuecomment-512949342.

The bug is fixed in https://github.com/tensorflow/tensorflow/commit/5d6158e0d4a736a8ad2fc98b717fed519e4080f0, which is not included in TF 1.15rc0.

I expect TF 1.15rc0 to include the bugfix for the GPU version of NMS kernel.

### PR DESCRIPTION
**Pull request by ppwwyyxx**
fix #32401 

@mihaimaruseac

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by samikama** [comment]
@mihaimaruseac I would have preferred if the original commits have been kept from #30893. After all you already had them in the master and cherry-picking would be better than creating a new commit with a different author.

**Comment by mihaimaruseac** [comment]
Sorry for this. I always use the GitHub interface when creating cherry-picks.

The rest is just dependent on how you created the PR/cherry-pick.

**Comment by samikama** [comment]
@mihaimaruseac I didn't create the cherry-pick, @ppwwyyxx did, I expected you would verify it is a cherry-pick before merging.

**Comment by mihaimaruseac** [comment]
Yes, we verify if commit content shows up but we don't verify author as authors of cherry-picks could be different than authors of original commit for all kinds of valid reasons.

Sorry this caused issues, I could have handled this better.

**Comment by ppwwyyxx** [comment]
IIRC I did a `git cherry-pick` and had to deal with some merge conflicts:
```
╰─$git cherry-pick -m 1 5d6158e0d4a736a8ad2fc98b717fed519e4080f0
error: could not apply 5d6158e0d4... Merge pull request #30893 from samikama:GPUNMSFixes
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
```
after resolving them I did a `git commit` following the instruction which probably created the commit with me being the author. Sorry for the mistake.

**Pull request merged**
