### PR TITLE
doc: fix possible copy&paste error in cumprod docs

### PR DESCRIPTION
**Pull request by temporaer**

### CODE REVIEW

**Comment by drpngx** [comment]
@rmlarsen Could you take a look?

**Review by benoitsteiner — APPROVED** [review]

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
`graph_io_test` seems to be failing again...

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Pull request merged**
