### PR TITLE
Add support for int8 for SplitV and OneHot

### LINKED ISSUE #56785: Support INT8 for tf.split and tf.one_hot
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 10 Enterprise 20H2

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current Behaviour?

```shell
Tensorflow will not work with int8 tensors when using one_hot or splitv.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

int8_tensor = tf.constant([[1, 2],
                           [3, 4],
                           [5, 6]], dtype=tf.int8)
try:
    tf.one_hot(int8_tensor, 3)
except Exception as e:
    print(e)
```

### Relevant log output

```shell
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'Tlen' of int8 is not in the list of allowed values: int32, int64
	; NodeDef: {{node SplitV}}; Op<name=SplitV; signature=value:T, size_splits:Tlen, split_dim:int32 -> output:num_split*T; attr=num_split:int,min=1; attr=T:type; attr=Tlen:type,default=DT_INT64,allowed=[DT_INT32, DT_INT64]> [Op:SplitV] name: split

tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'TI' of int8 is not in the list of allowed values: uint8, int32, int64
	; NodeDef: {{node OneHot}}; Op<name=OneHot; signature=indices:TI, depth:int32, on_value:T, off_value:T -> output:T; attr=axis:int,default=-1; attr=T:type; attr=TI:type,default=DT_INT64,allowed=[DT_UINT8, DT_INT32, DT_INT64]> [Op:OneHot]
```
</details>

### PR DESCRIPTION
**Pull request by olipinski**
Adds support for int8 for SplitV and OneHot ops to allow for lower memory consumption.

Closes #56785.

### CODE REVIEW

**Comment by cantonios** [comment]
Can you add a test for split too?

**Comment by olipinski** [comment]
@cantonios I have added the split test, however it does not seem to pass, even on the release branch on my local install.

**Comment by cantonios** [comment]
@olipinski which test is failing in your local install?

For your PR, gradients are only supported for floating-point types, so you'll need to modify the `testGradientsAll` test to something like:
```
  def testGradientsAll(self):
    for dtype in _TEST_DTYPES:
      # Gradients not supported for integer types.
      if not dtype.is_integer:
        self._testGradientsSimple(dtype)
        self._testGradientsSimpleVariable(dtype)
```

**Comment by olipinski** [comment]
@cantonios whatever part was failing yesterday, it is fine now. I have also fixed the `testGradientsAll`, and now all `array_ops` test pass for me locally.

**Review by cantonios — APPROVED** [review]

**Comment by cantonios** [comment]
@olipinski sorry for the delay here.

Looks like you're missing a registration of `SplitVOpGPULaunch`.  Register it in `split_lib_gpu.cu.cc`, and add a corresponding `extern template struct` declaration in `split_lib_gpu.h`.

**Comment by olipinski** [comment]
@cantonios thanks for looking at the issue here! I have fixed it, hopefully, in the last commit.

**Review by cantonios — APPROVED** [review]
Thanks! *fingers crossed*

**Comment by olipinski** [comment]
Seems like almost all tests succeeded except for one, but I am not sure what to make of this. I don't know if this PR is what breaks this?

```
tensorflow/c/eager/c_api_test.cc:681: Failure
Expected equality of these values:
  orig_ptr
    Which is: 0x55ab336cfc00
  TF_TensorData(t)
    Which is: 0x7f5d90089f40
```

**Comment by rthadur** [comment]
@olipinski could you please rebase the branch to head , thank you!

**Comment by olipinski** [comment]
> @olipinski could you please rebase the branch to head , thank you!

Done!

**Review by cantonios — APPROVED** [review]

**Pull request merged**
