### PR TITLE
Ppc build fix

### PR DESCRIPTION
**Pull request by npanpaliya**

### CODE REVIEW

**Comment by npanpaliya** [comment]
Thankfully the check for ROCm build has passed now. Now, the PR is ready for review/merge.

**Comment by npanpaliya** [comment]
I don't see option to re-trigger the checks. Could someone please do it for me?

**Comment by npanpaliya** [comment]
Hello @gbaned and @sherhut , 
Request you to please review this PR.

**Comment by gbaned** [comment]
@npanpaliya Can you please resolve conflicts? Thanks!

**Comment by npanpaliya** [comment]
@gbaned My branch is up-to-date as well as has passed all the checks. I wish if my PR can be reviewed and merged before another LLVM update to master.

**Review by akuegel — COMMENTED** [review]
I am not familiar with this area, but I wonder whether the llvm patch is needed? Is it not possible to change it in the LLVM project, directly?
Ideally this PR should only change third_party/cpuinfo/cpuinfo.BUILD, and the other change should go to LLVM. Tensorflow updates to new LLVM revisions about once per day, so you shouldn't have to wait too long until you can depend on your change there.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by npanpaliya** [comment]
@akuegel - Yes, LLVM fix can go directly into llvm-project too. But adding ppc64le support in LLVM will need more work and verification. 
For TF to compile, only this change is needed in llvm and hence I added a patch in TF itself (TF follows this approach anyway).
I'm working on llvm-project too but it will take time. Hence raised this PR to TF to fix the builds.

**Comment by akuegel** [comment]
> @akuegel - Yes, LLVM fix can go directly into llvm-project too. But adding ppc64le support in LLVM will need more work and verification. For TF to compile, only this change is needed in llvm and hence I added a patch in TF itself (TF follows this approach anyway). I'm working on llvm-project too but it will take time. Hence raised this PR to TF to fix the builds.

Ok, good to know that you are planning to change this in LLVM, too :)
This patching mechanism is meant to be used only short term (as far as I know), e.g. if the LLVM revision we want to use has some issues with GCC which will be fixed with a later LLVM revision, or if the Bazel build was broken at that revision. We have a bug filed to remove this macos patch file that we currently have there.

**Comment by gbaned** [comment]
@npanpaliya Can you please resolve conflicts? Thanks!

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
