### PR TITLE
Implement the bilinear initializer op

### PR DESCRIPTION
**Pull request by bowang**
Bilinear interpolation is commonly used to initialize upsampling layers like `conv2d_transpose`. This PR implements a CPU op to initialize the filters.

Similar feature request: https://github.com/tensorflow/tensorflow/issues/5790

### CODE REVIEW

**Comment by martinwicke** [comment]
Fine for API review.

**Comment by bowang** [comment]
Hi @protoget , thanks for offering to review this issue! Please feel free to let me know of any suggestions.

**Comment by srikalyan** [comment]
Whats ETA on this? We really need this feature.

**Comment by bowang** [comment]
@srikalyan The implementation is ready and tested.
@martinwicke @protoget Would you mind taking a look at this PR? It's a quite simple one. Most of the code are just boilerplate templates.

**Comment by martinwicke** [comment]
Could you add documentation that explains what exactly this does? I can tell from the code, but it's not clear from the docs alone.

Also, the quadruple loop appears to be inefficient. Since you only assign a value for `k==l`, three loops should suffice. For bonus points, can you express this loop in eigen operations? That will give it both GPU support and significant optimizations. 

I am wondering whether a C++ op is even necessary for this. Can you build this initializer from existing op kernels (e.g. ResizeBilinear for appropriate inputs?). That would be easier to maintain.

**Comment by bowang** [comment]
@martinwicke Thanks for the comments.

I added more docs/comments on the code to make it easier to understand. 

I fixed the quadruple loop into a triple loop. Thank you for the suggestion!
Using eigen will make it more concise and gain the benefit of GPU support. But it will also make it harder to understand and maintain. As an initializer, it only runs once at the beginning. Thus the performance impact is relatively limited.

It's not very straightforward to implement it using ResizeBilinear, because ResizeBilinear directly performs the upsampling on the data while BilinearInitializer generates a kernel with which the convolution conducts the upsampling.

**Comment by bowang** [comment]
@martinwicke Do you have some time to take a look at this PR?
I've heard from several people who wanted to use this feature in their fully convolutional networks (FCN).
Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by bowang** [comment]
Can someone take a look at this PR? It has been waiting for a while. Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: It has been 29 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 45 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 89 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 104 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 119 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 134 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 149 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 164 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 182 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 197 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 89 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 104 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 119 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 134 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 149 days with no activity and the `awaiting review` label has been applied.

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @ebrevdo, @sherrym: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 164 days with no activity and the `awaiting review` label has been applied.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by gbaned** [comment]
@bowang Could you please resolve the conflicts? Thanks!

**Comment by bowang** [comment]
I am happy to fix the conflicts if any maintainer agrees to review this PR... otherwise it's just work in vain.

**Comment by mihaimaruseac** [comment]
I'll take a look

**Comment by gbaned** [comment]
@bowang Could you please check reviewer comments and keep us posted. Thanks!

**Comment by gbaned** [comment]
@bowang Could you please check reviewer comments and resolve conflicts?. Thanks!

**Comment by mihaimaruseac** [comment]
I said I'll take a look but it's going to be wasted time to look at it before conflicts are fixed.

**Comment by mihaimaruseac** [comment]
Actually, contrib is removed so closing this PR. Please reopen against TF Addons.

**Pull request closed without merging**
