### PR TITLE
Improvement of the regular expression

### PR DESCRIPTION
**Pull request by eukub**
The improvement of the regular expression

### CODE REVIEW

**Comment by eukub** [comment]
I've sent Google CLA

**Comment by gbaned** [comment]
Hi @kanglant Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @kanglant Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @kanglant Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @kanglant Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @kanglant Can you please review this PR ? Thank you!

**Review by kanglant — APPROVED** [review]

**Pull request merged**
