### PR TITLE
fix mem leaks for dynamic rnn

### PR DESCRIPTION
**Pull request by awni**
Fix mem leaks in tensor array and stack.

Tests `tensorflow/python/kernel_tests/rnn_*.py` pass.

### CODE REVIEW

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please (I'm assuming this is correct ahead of time).

@ebrevdo: is it worth adding C++ tests that would catch this memory leak?  (It's interesting that the python one doesn't expose it).

**Comment by ebrevdo** [comment]
Can you do a favor and run the tests with blaze test -c dbg ?  This should check that you don't unref once too many times.

**Comment by awni** [comment]
Sure, this is what I ran
`bazel test -c dbg //tensorflow/python:rnn_test`
And this was the output
```
...
//tensorflow/python:rnn_test                                             PASSED in 58.9s

Executed 1 out of 1 tests: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.```

**Comment by ebrevdo** [comment]
Great!  Can you rebase on HEAD so we can merge?

**Comment by awni** [comment]
Yup, done!

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by bhack** [comment]
@vrv Can this be detected with a special -fsanitize=leak in the CI build matrix running tests?

**Comment by ebrevdo** [comment]
Thanks!!

**Pull request merged**
