### PR TITLE
Fix: also include dirent.h in cuda_diagnostics for compilation on mac.

### PR DESCRIPTION
**Pull request by gunan**

### CODE REVIEW

**Comment by gunan** [comment]
http://ci.tensorflow.org/job/tensorflow-pull-requests-mac-gpu/1
running test for mac-gpu, where the issue showed up.

**Comment by gunan** [comment]
the gpu mac build shows the main issue being fixed, however it reveals another problem :|

**Comment by mrry** [comment]
First of all, thanks for fixing the compilation error! I'm not sure what could be causing the error... could it be a driver or CUDA version issue on the Mac?

There are a few warnings in the stream_executor code, but no smoking gun that I can see....

**Comment by gunan** [comment]
Nope, the test failure is we are trying to run multiple tests on a single
GPU. That one is my bad.

**Comment by mrry** [comment]
Ah cool. I'm happy to approve this, anyway! Are the Mac GPU tests passing again?

**Review by mrry — APPROVED** [review]

**Comment by gunan** [comment]
I will work on those next, as I was not able to test my changes.

**Comment by gunan** [comment]
Nope, just completed setting up the new macs, I will look into the failures
now.

**Pull request merged**
