### PR TITLE
Branch 181174976

### PR DESCRIPTION
**Pull request by frankchn**

### CODE REVIEW

**Comment by frankchn** [comment]
@tensorflow-jenkins, test this please.

**Review by sb2nov — APPROVED** [review]

**Comment by frankchn** [comment]
The 5 tests that failed passes on both Python 2 and Python 3 when I `bazel test`ed them from my own branch, so chalking it up to spurious test failures:

```$ bazel test //tensorflow/python/debug:analyzer_cli_test //tensorflow/python/debug:curses_ui_test //tensorflow/python/debug:tensor_format_test //tensorflow/python/eager:tensor_test //tensorflow/python:special_math_ops_test
...
//tensorflow/python:special_math_ops_test                                PASSED in 2.5s
//tensorflow/python/debug:analyzer_cli_test                              PASSED in 2.4s
//tensorflow/python/debug:curses_ui_test                                 PASSED in 1.0s
//tensorflow/python/debug:tensor_format_test                             PASSED in 0.8s
//tensorflow/python/eager:tensor_test                                    PASSED in 1.0s```

**Comment by frankchn** [comment]
@tensorflow-jenkins, test this please.

**Comment by frankchn** [comment]
The failing tests are disabled via internal commit 181212111. This will get propagated externally with the next daily push.

**Pull request merged**
