### PR TITLE
Fix two typos in API docs for ExponentialMovingAverage.

### PR DESCRIPTION
**Pull request by lukaszbk**

### CODE REVIEW

**Comment by lukaszbk** [comment]
I signed it!

**Comment by vrv** [comment]
(we can't look at this until the CLA comes back as signed, can you double check)

**Comment by gunan** [comment]
Can one of the admins verify this patch?

**Comment by lukaszbk** [comment]
I think I know what is wrong with the CLA. I use lukaszbk+github@gmail.com as my GitHub login, while I signed the CLA as lukaszbk@gmail.com.

Is there a way to sign the CLA as lukaszbk+github@gmail.com? Unfortunately, I cannot use lukaszbk+github@gmail.com as an alternate Gmail address in my Google Account settings.

**Comment by vrv** [comment]
Not sure, you can give it a try!  I think you can add multiple emails to your github account (as non-primary) as well, if you felt comfortable doing that.  Basically:

- email of commit must match CLA email
- CLA email must be associated with your github account (somehow)

**Comment by lukaszbk** [comment]
OK. I verified that lukaszbk@ which I signed the CLA with is added to my GitHub account.

**Comment by vrv** [comment]
google cla bot doesn't seem to have picked it up, sadly.  what's the commit email you used on the commit?  (why github makes this very hard to find is beyond me)

**Comment by lukaszbk** [comment]
I am guessing that the email used for commit was lukaszbk@users.noreply.github.com, since I created the commit in the web UI I had "keep my email private" setting checked. I think I'll close this pull request and try another one with a different email.

**Pull request closed without merging**
