### PR TITLE
[ROCm] Update TF to call HipSolver for most LA functions in ROCm 4.5+

### PR DESCRIPTION
**Pull request by stevenireeves**

### CODE REVIEW

**Comment by stevenireeves** [comment]
The AMD ROCm community CI Build failure is not related to this PR. The fix is in https://github.com/tensorflow/tensorflow/pull/54093

**Comment by stevenireeves** [comment]
@chsigg Ping on this PR.

**Review by chsigg — APPROVED** [review]

**Comment by stevenireeves** [comment]
@gbaned  any updates on this PR?

**Comment by akuegel** [comment]
The problem why it wasn't merged is that there is an unused variable. This requires either commenting about it on this PR, so you can fix it, or fixing it ourselves. In the future, if you want speedier merges, please compile with -Wunused-variable
I am now fixing the unused variable issue and hopefully then this PR can be merged.

**Pull request merged**
