### PR TITLE
Branch 173060283

### PR DESCRIPTION
**Pull request by vrv**

### CODE REVIEW

**Comment by vrv** [comment]
@gunan @benoitsteiner Something in this PR is causing all non-kokoro infrastructure to fail, but I can't figure out why.  I'll leave this push out so you can look at logs to debug.

**Comment by yifeif** [comment]
Maybe add `apt-key adv --keyserver keyserver.ubuntu.com  --recv 084ECFC5828AB726` to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_deb_packages.sh#L30?

**Comment by vrv** [comment]
Tried that and let's see what happens.

**Comment by vrv** [comment]
@annarev can you take a look for this possible failure?

```
22:42:50 In file included from /workspace/tensorflow/contrib/makefile/gen/proto_text/tensorflow/core/framework/node_def.pb_text-impl.h:5:0,
22:42:50                  from /workspace/tensorflow/contrib/makefile/gen/proto_text/tensorflow/core/framework/node_def.pb_text.cc:2:
22:42:50 /workspace/tensorflow/contrib/makefile/gen/proto/tensorflow/core/framework/attr_value.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
22:42:50  #include <google/protobuf/stubs/common.h>
22:42:50                                           ^
22:42:50 compilation terminated.
22:42:50 In file included from /workspace/tensorflow/contrib/makefile/gen/proto_text/tensorflow/core/framework/api_def.pb_text-impl.h:5:0,
22:42:50                  from /workspace/tensorflow/contrib/makefile/gen/proto_text/tensorflow/core/framework/api_def.pb_text.cc:2:
22:42:50 /workspace/tensorflow/contrib/makefile/gen/proto/tensorflow/core/framework/api_def.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
22:42:50  #include <google/protobuf/stubs/common.h>
22:42:50                                           ^
```

**Pull request closed without merging**
