### PR TITLE
[Intel MKL] Updating mkl_layout_test to test for native format mode (Part 1)

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR (Part 1)  updates mkl_layout_test to test for native format mode. Also since the file is getting very big, it splits the file into two based on type of test case, fusion vs non-fusion cases.

### CODE REVIEW

**Comment by mahmoud-abuzaina** [comment]
@gbaned I have resolved the conflicts. Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by gbaned** [comment]
@penpornk Can you please review this PR ? Thanks!

**Comment by mahmoud-abuzaina** [comment]
@gbaned We are planning to create a simpler version of this PR. Closing this for now.

**Pull request closed without merging**
