### PR TITLE
Update the link for MKL optimized wheels

### PR DESCRIPTION
**Pull request by ashahba**
Please remove the `WIP` and merge only after we at `Intel` post the `MKL optimized` wheels. `v1.13`.
Thanks.
I'll post here when that's done.

### CODE REVIEW

**Comment by rthadur** [comment]
@ashahba thank you for the PR , please submit your PR to Tensorflow:master

**Comment by ashahba** [comment]
@rthadur the PR for master is here: #25407

**Comment by tensorflowbutler** [comment]
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

**Comment by ashahba** [comment]
Hi @drpngx this is ready to be merged and packages for v1.13.1 have been uploaded.

**Pull request closed without merging**
