### PR TITLE
Updating MKL to the latest release.

### PR DESCRIPTION
**Pull request by bhavani-subramanian**

### CODE REVIEW

**Comment by bhavani-subramanian** [comment]
@jart Can you mirror the new MKL URL?

**Comment by gunan** [comment]
Mirror is now available.

**Comment by yifeif** [comment]
Thanks @gunan!

**Comment by yifeif** [comment]
@tensorflow-jenkins test this please

**Review by gunan — APPROVED** [review]

**Comment by yifeif** [comment]
windows cmake rerun at http://ci.tensorflow.org/job/tensorflow-pr-win-cmake-py/5902/

**Pull request merged**
