### PR TITLE
Fix split_v docs

### PR DESCRIPTION
**Pull request by danielgordon10**
Fixes some inconsistencies and copy/paste typos in split_v's code.

### CODE REVIEW

**Comment by danielgordon10** [comment]
I signed it

**Comment by danielgordon10** [comment]
This is really just some typo fixes. I don't think it should take that long to approve.

**Comment by danielgordon10** [comment]
I signed it with my other email as well now.

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by AnishShah** [comment]
I think, this has been fixed internally. This is same as my PR #6208. :)

**Comment by martinwicke** [comment]
ok great. I'll close this then.

**Comment by danielgordon10** [comment]
Has the batch norm comment in split_v benchmark also been updated?

**Comment by ekelsen** [comment]
yes

**Pull request closed without merging**
