### PR TITLE
Support Identity in tensor_util.constant_value.

### PR DESCRIPTION
**Pull request by charmasaur**
This looks just the same as StopGradient, since for the purposes of
forward-propagated values the two are identical.

Note that confusion_matrix_test needed to be updated because the
condition can now be evaluated statically (i.e. by constant_value), which
causes the error message to be printed across multiple lines.

### CODE REVIEW

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
This PR creats build failures. Please see them by clicking Details on the right of the failed builds and please fix.

**Comment by charmasaur** [comment]
It looks as though the format of the logged exception has changed, which is causing some tests to fail (they're searching for a regex of the form "foo.*bar", but now "foo" and "bar" are on separate lines). I'll look into it.

**Comment by charmasaur** [comment]
OK, found the issue: now that `constant_value` supports the `Identity` op, the relevant check can be performed statically (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/check_ops.py#L369), which formats the exception message a different way.

I'm pretty dubious about this pattern of running assertions on exception messages, but since it seems widespread I guess I'll leave it be, and just update the regex.

Will re-request review once I've made the changes and verified them.

**Comment by charmasaur** [comment]
I've updated the test and verified that it passes locally.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Can you please resync on master?

**Comment by charmasaur** [comment]
Done (and thanks for the review!)

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Apologies it took so long, it slipped out of my radar for a while

**Comment by mihaimaruseac** [comment]
This causes multiple failures internally, so we will rollback for a while and then roll forward when we are ready for it. Apologies.

**Comment by charmasaur** [comment]
Oh no, sorry for the pain :(

FWIW I actually don't need this any more (I just figured it was a sensible change to push through regardless), so if it's causing too many problems maybe it should just be dropped.

**Comment by mihaimaruseac** [comment]
It is a sensible change, so we might still pick it up in the future, depending on how easy is to fix the broken test. If that happens, we will still credit the PR.

**Pull request merged**
