### PR TITLE
Update documentation of micro_speech example

### PR DESCRIPTION
**Pull request by biagiom**
Hello Tensorflowers,
as this is my first contribution, first I would like to say a big thank to all the TensorFlow contributors that every day take care about improving it and fixing issues.

This pull request updates the documentation related to `micro_speech` example. Further info is also provided in the commit messages.

Best regards,
Biagio.

### CODE REVIEW

**Comment by biagiom** [comment]
@googlebot I signed it!

**Comment by gbaned** [comment]
@biagiom Can you please resolve conflicts? Thanks!

**Comment by biagiom** [comment]
Done. I also updated the alignment of the table in the **Trained Models** section ([micro_speech/train/README.md](https://github.com/tensorflow/tensorflow/pull/38753/commits/d0c4a0489c8669e4a9c652e839694b074b5a900a#diff-371c67872e41288cb2aefe6faf6f4688))

**Comment by gbaned** [comment]
@biagiom Still, conflicts are appearing. Can you please resolve those? Thanks!

**Comment by biagiom** [comment]
Hi @gbaned, conflicts solved. Thanks and sorry for the delay !

**Review by njeffrie — APPROVED** [review]
Thanks for your contribution. We usually accept PRs for correctness issues or major documentation fixes.  Let's land this since it does seem to improve things a bit, but for future changes keep in mind that the pull request process has a fairly high overhead.

**Pull request merged**
