### PR TITLE
[Intel MKL] Upgrading to oneDNN 2.1

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR upgrades oneDNN version to 2.1. It also includes a patch to fix 2 build errors with certain gcc versions. So [this ](https://github.com/tensorflow/tensorflow/commit/ce7ad9e58aabea67595afa0d601f7277d93ba7e9#diff-501d1399b467b9f36e528126219bea5c3c9d6b2156248f6fe44e5c33eae5f0f5) patch is also included in this PR.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Review by penpornk — CHANGES_REQUESTED** [review]
@mahmoud-abuzaina Could you please fix the `Ubuntu CPU` failures? Thank you!
```
external/mkl_dnn_v1/src/common/type_helpers.hpp:23:10: fatal error: oneapi/dnnl/dnnl.h: No such file or directory
 #include "oneapi/dnnl/dnnl.h"
          ^~~~~~~~~~~~~~~~~~~~
```

**Comment by mahmoud-abuzaina** [comment]
@penpornk yes, this error was also there last time and we could not reproduce it. Can you share the compiler version used for that build?

**Comment by penpornk** [comment]
@mahmoud-abuzaina It's gcc 7. It uses the same `--crosstool_top=//third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010:toolchain` bazel option. I'll see if the dockerfile can reproduce this.

**Comment by penpornk** [comment]
@mahmoud-abuzaina Are the oneDNN unit test failures related to this PR?

**Comment by mahmoud-abuzaina** [comment]
No, we expect that unit test to fail. There other pending PR to fix it. That PR got deprioritized.
For the build error, we tried with several compiler versions including gcc7 so far but for some reason we could not reproduce the issue.

**Review by penpornk — APPROVED** [review]
Got it. I can't get docker to reproduce this either. The error seems trivial. I'll pull this in and fix internally. :)

**Comment by penpornk** [comment]
This PR is being reverted because of a nightly build failure. I'm finding a way to reproduce this in docker. Will post commands to reproduce later.
```
ERROR: .../mkl_dnn_v1/BUILD.bazel:124:11: C++ compilation of rule '@mkl_dnn_v1//:dnnl_single_threaded' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.1/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 87 argument(s) skipped)
mkl_dnn_v1/src/cpu/x64/gemm/f32/jit_avx512_core_f32_copy_at_kern_autogen.cpp: In member function 'virtual void dnnl::impl::cpu::x64::jit_avx512_core_f32_copy_at_kern::generate()':
mkl_dnn_v1/src/cpu/x64/gemm/f32/jit_avx512_core_f32_copy_at_kern_autogen.cpp:29:6: internal compiler error: in equal_mem_array_ref_p, at tree-ssa-scopedtables.c:429
 void jit_avx512_core_f32_copy_at_kern::generate() {
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0xcf338f equal_mem_array_ref_p
	/dt7-src/gcc/tree-ssa-scopedtables.c:429
0xcf338f hashable_expr_equal_p
	/dt7-src/gcc/tree-ssa-scopedtables.c:466
0xcf338f expr_elt_hasher::equal(expr_hash_elt* const&, expr_hash_elt* const&)
	/dt7-src/gcc/tree-ssa-scopedtables.c:916
0xcf44b0 hash_table<expr_elt_hasher, xcallocator>::find_slot_with_hash(expr_hash_elt* const&, unsigned int, insert_option)
	/dt7-src/gcc/hash-table.h:889
0xcf3d61 hash_table<expr_elt_hasher, xcallocator>::find_slot(expr_hash_elt* const&, insert_option)
	/dt7-src/gcc/hash-table.h:414
0xcf3d61 avail_exprs_stack::lookup_avail_expr(gimple*, bool, bool)
	/dt7-src/gcc/tree-ssa-scopedtables.c:156
0xc6a046 optimize_stmt
	/dt7-src/gcc/tree-ssa-dom.c:1691
0xc6a046 dom_opt_dom_walker::before_dom_children(basic_block_def*)
	/dt7-src/gcc/tree-ssa-dom.c:1184
0x1159872 dom_walker::walk(basic_block_def*)
	/dt7-src/gcc/domwalk.c:265
0xc6a96d execute
	/dt7-src/gcc/tree-ssa-dom.c:459
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```

**Comment by mahmoud-abuzaina** [comment]
We are trying to reproduce the failure. Is the Linux version ubuntu 16.04?

**Comment by penpornk** [comment]
@mahmoud-abuzaina Thank you! Yes, it's Ubuntu 16.04.

**Pull request merged**
