### PR TITLE
[oneDNN] Optimize CNMS implementation

### PR DESCRIPTION
**Pull request by yimeisun123**
Eliminate unnecessary data copying in per class NMS computation, this reduces memory usage and improves performance.

### CODE REVIEW

**Comment by yimeisun123** [comment]
CNMS benchmark test result
- Comparison of real time in ns between baseline vs with this PR change.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/yimeisun/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/yimeisun/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



name | Before real_time | After real_time | Ratio
-- | -- | -- | --
BM_CombinedNMS_cpu_1_500_25_1 | 334189 | 322264 | 1.037004
BM_CombinedNMS_cpu_28_500_25_1 | 4.41E+06 | 4.10E+06 | 1.0754
BM_CombinedNMS_cpu_32_500_25_1 | 4.48E+06 | 4.31E+06 | 1.039714
BM_CombinedNMS_cpu_64_500_25_1 | 7.60E+06 | 7.22E+06 | 1.052113
BM_CombinedNMS_cpu_1_1000_25_1 | 349802 | 332937 | 1.050655
BM_CombinedNMS_cpu_28_1000_25_1 | 4.43E+06 | 4.30E+06 | 1.028769
BM_CombinedNMS_cpu_32_1000_25_1 | 4.81E+06 | 4.53E+06 | 1.059926
BM_CombinedNMS_cpu_64_1000_25_1 | 8.59E+06 | 7.66E+06 | 1.121244
BM_CombinedNMS_cpu_1_1917_25_1 | 387730 | 350081 | 1.107544
BM_CombinedNMS_cpu_28_1917_25_1 | 5.22E+06 | 4.50E+06 | 1.159611
BM_CombinedNMS_cpu_32_1917_25_1 | 5.50E+06 | 5.04E+06 | 1.092065
BM_CombinedNMS_cpu_64_1917_25_1 | 1.01E+07 | 8.52E+06 | 1.188657
BM_CombinedNMS_cpu_1_2500_25_1 | 400145 | 360238 | 1.11078
BM_CombinedNMS_cpu_28_2500_25_1 | 5.68E+06 | 4.87E+06 | 1.166302
BM_CombinedNMS_cpu_32_2500_25_1 | 5.95E+06 | 5.47E+06 | 1.086979
BM_CombinedNMS_cpu_64_2500_25_1 | 1.10E+07 | 9.38E+06 | 1.168934
BM_CombinedNMS_cpu_1_500_25_25 | 338261 | 321794 | 1.051172
BM_CombinedNMS_cpu_28_500_25_25 | 4.33E+06 | 3.97E+06 | 1.090368
BM_CombinedNMS_cpu_32_500_25_25 | 4.50E+06 | 4.19E+06 | 1.071899
BM_CombinedNMS_cpu_64_500_25_25 | 7.92E+06 | 7.24E+06 | 1.093034
BM_CombinedNMS_cpu_1_1000_25_25 | 351871 | 334681 | 1.051362
BM_CombinedNMS_cpu_28_1000_25_25 | 4.80E+06 | 4.41E+06 | 1.087341
BM_CombinedNMS_cpu_32_1000_25_25 | 4.80E+06 | 4.66E+06 | 1.029737
BM_CombinedNMS_cpu_64_1000_25_25 | 9.16E+06 | 8.25E+06 | 1.110321
BM_CombinedNMS_cpu_1_1917_25_25 | 395715 | 356851 | 1.108908
BM_CombinedNMS_cpu_28_1917_25_25 | 5.45E+06 | 4.89E+06 | 1.114186
BM_CombinedNMS_cpu_32_1917_25_25 | 5.87E+06 | 5.25E+06 | 1.117478
BM_CombinedNMS_cpu_64_1917_25_25 | 1.11E+07 | 9.67E+06 | 1.14452
BM_CombinedNMS_cpu_1_2500_25_25 | 413935 | 361808 | 1.144074
BM_CombinedNMS_cpu_28_2500_25_25 | 6.32E+06 | 5.14E+06 | 1.229518
BM_CombinedNMS_cpu_32_2500_25_25 | 6.68E+06 | 5.65E+06 | 1.182296
BM_CombinedNMS_cpu_64_2500_25_25 | 1.28E+07 | 1.06E+07 | 1.210632
BM_CombinedNMS_cpu_1_500_90_1 | 1.07E+06 | 1.00E+06 | 1.072312
BM_CombinedNMS_cpu_28_500_90_1 | 1.58E+07 | 1.40E+07 | 1.124338
BM_CombinedNMS_cpu_32_500_90_1 | 1.58E+07 | 1.49E+07 | 1.062751
BM_CombinedNMS_cpu_64_500_90_1 | 2.78E+07 | 2.58E+07 | 1.079076
BM_CombinedNMS_cpu_1_1000_90_1 | 1.12E+06 | 1.04E+06 | 1.080739
BM_CombinedNMS_cpu_28_1000_90_1 | 1.70E+07 | 1.58E+07 | 1.079352
BM_CombinedNMS_cpu_32_1000_90_1 | 1.76E+07 | 1.63E+07 | 1.074538
BM_CombinedNMS_cpu_64_1000_90_1 | 3.10E+07 | 2.89E+07 | 1.069872
BM_CombinedNMS_cpu_1_1917_90_1 | 1.20E+06 | 1.08E+06 | 1.107895
BM_CombinedNMS_cpu_28_1917_90_1 | 1.95E+07 | 1.77E+07 | 1.10383
BM_CombinedNMS_cpu_32_1917_90_1 | 2.04E+07 | 1.90E+07 | 1.074876
BM_CombinedNMS_cpu_64_1917_90_1 | 3.78E+07 | 3.36E+07 | 1.12239
BM_CombinedNMS_cpu_1_2500_90_1 | 1.27E+06 | 1.15E+06 | 1.109065
BM_CombinedNMS_cpu_28_2500_90_1 | 2.16E+07 | 1.88E+07 | 1.145242
BM_CombinedNMS_cpu_32_2500_90_1 | 2.30E+07 | 2.02E+07 | 1.138123
BM_CombinedNMS_cpu_64_2500_90_1 | 4.28E+07 | 3.67E+07 | 1.165077
BM_CombinedNMS_cpu_1_500_90_90 | 1.07E+06 | 1.02E+06 | 1.055089
BM_CombinedNMS_cpu_28_500_90_90 | 1.52E+07 | 1.51E+07 | 1.00377
BM_CombinedNMS_cpu_32_500_90_90 | 1.63E+07 | 1.61E+07 | 1.016836
BM_CombinedNMS_cpu_64_500_90_90 | 2.84E+07 | 2.72E+07 | 1.04343
BM_CombinedNMS_cpu_1_1000_90_90 | 1.13E+06 | 1.06E+06 | 1.064577
BM_CombinedNMS_cpu_28_1000_90_90 | 1.66E+07 | 1.58E+07 | 1.054762
BM_CombinedNMS_cpu_32_1000_90_90 | 1.79E+07 | 1.76E+07 | 1.019121
BM_CombinedNMS_cpu_64_1000_90_90 | 3.20E+07 | 3.02E+07 | 1.058378
BM_CombinedNMS_cpu_1_1917_90_90 | 1.23E+06 | 1.13E+06 | 1.088672
BM_CombinedNMS_cpu_28_1917_90_90 | 1.98E+07 | 1.91E+07 | 1.036563
BM_CombinedNMS_cpu_32_1917_90_90 | 2.17E+07 | 2.08E+07 | 1.047132
BM_CombinedNMS_cpu_64_1917_90_90 | 3.83E+07 | 3.67E+07 | 1.042737
BM_CombinedNMS_cpu_1_2500_90_90 | 1.29E+06 | 1.17E+06 | 1.099015
BM_CombinedNMS_cpu_28_2500_90_90 | 2.14E+07 | 2.04E+07 | 1.047537
BM_CombinedNMS_cpu_32_2500_90_90 | 2.44E+07 | 2.27E+07 | 1.074722
BM_CombinedNMS_cpu_64_2500_90_90 | 4.29E+07 | 3.94E+07 | 1.088768
BM_CombinedNMS_cpu_1_500_200_1 | 2.40E+06 | 2.33E+06 | 1.029554
BM_CombinedNMS_cpu_28_500_200_1 | 2.65E+07 | 2.52E+07 | 1.052669
BM_CombinedNMS_cpu_32_500_200_1 | 2.86E+07 | 2.70E+07 | 1.059056
BM_CombinedNMS_cpu_64_500_200_1 | 5.28E+07 | 4.87E+07 | 1.083045
BM_CombinedNMS_cpu_1_1000_200_1 | 2.51E+06 | 2.41E+06 | 1.041351
BM_CombinedNMS_cpu_28_1000_200_1 | 2.92E+07 | 2.63E+07 | 1.110325
BM_CombinedNMS_cpu_32_1000_200_1 | 3.28E+07 | 2.87E+07 | 1.145261
BM_CombinedNMS_cpu_64_1000_200_1 | 5.99E+07 | 5.26E+07 | 1.13853
BM_CombinedNMS_cpu_1_1917_200_1 | 2.71E+06 | 2.54E+06 | 1.067206
BM_CombinedNMS_cpu_28_1917_200_1 | 3.53E+07 | 3.05E+07 | 1.159143
BM_CombinedNMS_cpu_32_1917_200_1 | 3.99E+07 | 3.29E+07 | 1.212441
BM_CombinedNMS_cpu_64_1917_200_1 | 7.44E+07 | 6.23E+07 | 1.194299
BM_CombinedNMS_cpu_1_2500_200_1 | 2.78E+06 | 2.58E+06 | 1.078483
BM_CombinedNMS_cpu_28_2500_200_1 | 3.95E+07 | 3.35E+07 | 1.178008
BM_CombinedNMS_cpu_32_2500_200_1 | 4.29E+07 | 3.64E+07 | 1.178887
BM_CombinedNMS_cpu_64_2500_200_1 | 8.34E+07 | 6.93E+07 | 1.203188
BM_CombinedNMS_cpu_1_500_200_200 | 2.40E+06 | 2.37E+06 | 1.015784
BM_CombinedNMS_cpu_28_500_200_200 | 2.64E+07 | 2.56E+07 | 1.031587
BM_CombinedNMS_cpu_32_500_200_200 | 2.92E+07 | 2.82E+07 | 1.034441
BM_CombinedNMS_cpu_64_500_200_200 | 5.31E+07 | 5.26E+07 | 1.009757
BM_CombinedNMS_cpu_1_1000_200_200 | 2.51E+06 | 2.49E+06 | 1.008234
BM_CombinedNMS_cpu_28_1000_200_200 | 3.02E+07 | 2.92E+07 | 1.033287
BM_CombinedNMS_cpu_32_1000_200_200 | 3.31E+07 | 3.27E+07 | 1.013632
BM_CombinedNMS_cpu_64_1000_200_200 | 6.11E+07 | 5.85E+07 | 1.043018
BM_CombinedNMS_cpu_1_1917_200_200 | 2.72E+06 | 2.62E+06 | 1.037425
BM_CombinedNMS_cpu_28_1917_200_200 | 3.74E+07 | 3.35E+07 | 1.117488
BM_CombinedNMS_cpu_32_1917_200_200 | 4.07E+07 | 3.69E+07 | 1.102791
BM_CombinedNMS_cpu_64_1917_200_200 | 7.71E+07 | 6.92E+07 | 1.113246
BM_CombinedNMS_cpu_1_2500_200_200 | 2.85E+06 | 2.70E+06 | 1.056102
BM_CombinedNMS_cpu_28_2500_200_200 | 4.13E+07 | 3.71E+07 | 1.114582
BM_CombinedNMS_cpu_32_2500_200_200 | 4.57E+07 | 4.00E+07 | 1.1443
BM_CombinedNMS_cpu_64_2500_200_200 | 8.58E+07 | 7.55E+07 | 1.137008



</body>

</html>

**Comment by yimeisun123** [comment]
@rohan100jain - please let me know when you may be able to review this PR. Thanks

**Review by mihaimaruseac — APPROVED** [review]

**Comment by yimeisun123** [comment]
I checked the log for "Ubuntu CPU - Internal CI build failed", the failures are not related to this PR change.

**Comment by mihaimaruseac** [comment]
Yes, probably broken by c6531b8bcb83d1314acc96360156b549afecb377 LLVM/MLIR

**Comment by yimeisun123** [comment]
If this PR is approved, can it be merged now? Thanks

**Pull request merged**
