### PR TITLE
Also accept non-k8 CPU types in build pip package.

### LINKED ISSUE #12735: Magic name directories prevent to embed the mkl library
For some reasons the build_pip_package script sues the magic directory `solib_k8`. 
That directory does not exists if you compile mkl on a vm machine, where the libraries are added under `_solib_local`. 

```
fabriziomilo@instance-2:~/ml-models/tensorflow$ ag solib_k8
tensorflow/tools/pip_package/build_pip_package.sh
94:      mkdir "${TMPDIR}/_solib_k8"
96:                     bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uthird_Uparty_Smkl \
97:        "${TMPDIR}/_solib_k8"
110:      if [ -d bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uthird_Uparty_Smkl ]; then
111:        mkdir "${TMPDIR}/_solib_k8"
113:          bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uthird_Uparty_Smkl \
114:          "${TMPDIR}/_solib_k8"
127:      if [ -d bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uthird_Uparty_Smkl ]; then
128:        mkdir "${TMPDIR}/_solib_k8"
130:                            bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uthird_Uparty_Smkl \
131:          "${TMPDIR}/_solib_k8"

tensorflow/tools/pip_package/setup.py
159:matches += ['../' + x for x in find_files('*', '_solib_k8') if '.py' not in x]
fabriziomilo@instance-2:~/ml-models/tensorflow$ find ./bazel-bin/ -iname \*mkl\*.so
./bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/org_tensorflow/_solib_local/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uthird_Uparty_Smkl/libmklml_intel.so
./bazel-bin/tensorflow/tools/pip_package/simple_console.runfiles/org_tensorflow/_solib_local/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uthird_Uparty_Smkl/libmklml_intel.so
./bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/_solib_local/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uthird_Uparty_Smkl/libmklml_intel.so
./bazel-bin/_solib_local/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uthird_Uparty_Smkl/libmklml_intel.so```

### PR DESCRIPTION
**Pull request by gunan**
Fixes #12735

### CODE REVIEW

**Review by drpngx — APPROVED** [review]

**Comment by drpngx** [comment]
There is a silent python3 error AFAICT.

**Comment by gunan** [comment]
Actually building pip package failed on python3.
I will see what is going on.

**Review by yifeif — APPROVED** [review]

**Comment by drpngx** [comment]
Failure seems to be unrelated, and happens in another pending merge.

**Comment by gunan** [comment]
Also seen internally, root caused to an anomaly in gemmlowp repository.
Have a change waiting to submit to fix the issue.

**Comment by drpngx** [comment]
Thank you @gunan !

**Pull request merged**
