### PR TITLE
[INTEL MKL] Added missed  bfloat16 CPU support for op math.rsqrt

### PR DESCRIPTION
**Pull request by cuixiaom**

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Comment by cuixiaom** [comment]
This PR has been merged, and I can see the merge information in the log, but the files doesn't have the changes in this PR, was there a merge issue? please check the file in the master:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_rsqrt.cc
which doesn't have the changes from this PR, but in the history of this file, I can see there is merge record.

**Comment by penpornk** [comment]
@cuixiaom It got rolled back because it broke some of our internal tests that cannot be easily fixed. I'll try to bring it back but it might take some time. Sorry about that!

**Comment by cuixiaom** [comment]
@penpornk  thanks for your response! Please let me know if need my help.

**Pull request merged**
