### PR TITLE
session_clusterspec_prop_test and common_runtime_direct_session_with_tracking_alloc_test fixed for GPU

### PR DESCRIPTION
**Pull request by sandipmgiri**
As I discussed here - https://github.com/tensorflow/tensorflow/issues/14515 and https://github.com/tensorflow/tensorflow/issues/14576 , I made the changes in code to pass session_clusterspec_prop_test and common_runtime_direct_session_with_tracking_alloc_test tests for GPU.

Thanks!

### CODE REVIEW

**Comment by sandipmgiri** [comment]
@saeta @jhseu

**Comment by sandipmgiri** [comment]
Hi @saeta , can you please have a look ?

**Review by saeta — APPROVED** [review]

**Comment by saeta** [comment]
Sorry for the delay @sandipmgiri ; LGTM.

**Comment by sandipmgiri** [comment]
Thanks @saeta. Please merge this.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
/CC @gunan: Sanity checks [failed](https://ci.tensorflow.org/job/tensorflow-pull-requests-sanity/12918/console) for some reason,

Jenkins, test this please.

**Pull request merged**
