### PR TITLE
Add compression support to RecordInput

### LINKED ISSUE #12344: Feature request: RecordInput to support gzipped tfrecord files.
Currently [RecordInput](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/record-input) doesn't support gzipped tfrecord files, would be great to have this supported.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to fix the request raised in #12344 so that it is possible to process RecordInput with compressions.

An attr of `compression_type` has been added.

Additional tests have been created to cover the changes.

This fix fixes #12344.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by drpngx — COMMENTED** [review]
Nice, thanks!

Am I correct to understand that this compresses the entire file, not just the payload? Any thoughts on how to make that compress only the payload and leave the headers alone?

**Comment by yongtang** [comment]
Thanks @drpngx for the review. The current PR utilizes the existing implementation of `io::RecordReader`which allows a compression type as the flag.

To add compression to the payload but expose the header might be possible. It may require additional implementations on `io::RecordReader`.

Let me play with it and see if I could create another PR for that.

**Comment by drpngx** [comment]
OK, I think that's the same as other behavior in TF, but I'm curious to see what you'll find.

/CC @skye

**Comment by martinwicke** [comment]
@yongtang any update? What should we do with this PR?

**Comment by yongtang** [comment]
@martinwicke Given that the original issue #12344 was to support gzipped tfrecord files, I think it probably make sense to limit the scope of this PR and merge if there is no outstanding issues.

In the review @drpngx raised an interesting point of having payload compressed while exposing the header. I haven't spend much time on that though I think it is worth at least exploring.

Maybe we could move forward to merge with this PR (assuming no other outstanding issue) so that the original issue #12344 could be closed? I could open a separate issue to track the alternative approach. You can assign the new issue to me and I will spend time on it.

**Comment by yongtang** [comment]
Added a new issue #14342 to cover the payload only compression.

**Review by drpngx — APPROVED** [review]
Still need API review for the new option.

**Comment by martinwicke** [comment]
I see no API change in this PR which is surprising. Are you sure it does what it's intended to? Or do you just need to update the golden files for the API test?

**Comment by drpngx** [comment]
Strange, there should be a `compression_type`. Maybe there's some indirection of some kind.

**Comment by drpngx** [comment]
It looks like the op is only available through [here](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/data_flow_ops.py#L2267), @yongtang can you check?

**Comment by yongtang** [comment]
@martinwicke @drpngx The C++ kernel ops update is through:

https://github.com/tensorflow/tensorflow/pull/12369/files#diff-9dd26225c3129302e6f60e2b119f48d2R2478

and for python, it is through the `__init__()` method of the class `RecordInput` and `TFRecordInput`:

https://github.com/tensorflow/tensorflow/pull/12369/files#diff-156604dc2cdee8c1c0cd03edb1e8a7fdR2155

https://github.com/tensorflow/tensorflow/pull/12369/files#diff-156604dc2cdee8c1c0cd03edb1e8a7fdR2178

As it is through class constructor, it is not a python ops like `decode_raw`.

Maybe that is the reason there is no api compatibility issue?

**Comment by yongtang** [comment]
Not able to see the build error. Maybe it is an infrastructure failure?

**Comment by drpngx** [comment]
Ah, there is an API change detected, good.

```
2017-12-15 18:38:23.754138: I tensorflow/core/api_def/api_test.cc:233] Skipping GenerateBigQueryReaderPartitions
tensorflow/core/api_def/api_test.cc:298: Failure
      Expected: golden_api_defs_str
      Which is: "op {\n  graph_op_name: \"RecordInput\"\n  out_arg {\n    name: \"records\"\n    description: <<END\nA tensor of shape [batch_size].\nEND\n  }\n  attr {\n    name: \"file_pattern\"\n    description: <<END\nGlob pattern for the data files.\nEND\n  }\n  attr {\n    name: \"file_random_seed\"\n    description: <<END\nRandom seeds used to produce randomized records.\nEND\n  }\n  attr {\n    name: \"file_shuffle_shift_ratio\"\n    description: <<END\nShifts the list of files after the list is randomly\nshuffled.\nEND\n  }\n  attr {\n    name: \"file_buffer_size\"\n    description: <<END\nThe randomization shuffling buffer.\nEND\n  }\n  attr {\n    name: \"file_parallelism\"\n    description: <<END\nHow many sstables are opened and concurrently iterated over.\nEND\n  }\n  attr {\n    name: \"batch_size\"\n    description: <<END\nThe batch size.\nEND\n  }\n  summary: \"Emits randomized records.\"\n}\n"
To be equal to: new_api_defs_str
      Which is: "op {\n  graph_op_name: \"RecordInput\"\n  out_arg {\n    name: \"records\"\n    description: <<END\nA tensor of shape [batch_size].\nEND\n  }\n  attr {\n    name: \"file_pattern\"\n    description: <<END\nGlob pattern for the data files.\nEND\n  }\n  attr {\n    name: \"file_random_seed\"\n    description: <<END\nRandom seeds used to produce randomized records.\nEND\n  }\n  attr {\n    name: \"file_shuffle_shift_ratio\"\n    description: <<END\nShifts the list of files after the list is randomly\nshuffled.\nEND\n  }\n  attr {\n    name: \"file_buffer_size\"\n    description: <<END\nThe randomization shuffling buffer.\nEND\n  }\n  attr {\n    name: \"file_parallelism\"\n    description: <<END\nHow many sstables are opened and concurrently iterated over.\nEND\n  }\n  attr {\n    name: \"batch_size\"\n    description: <<END\nThe batch size.\nEND\n  }\n  attr {\n    name: \"compression_type\"\n    description: <<END\nThe type of compression for the file. Currently ZLIB and\nGZIP are supported. Defaults to none.\nEND\n  }\n  summary: \"Emits randomized records.\"\n}\n"
With diff:
@@ +42,11 @@
     description: <<END
 The batch size.
+END
+  }
+  attr {
+    name: \"compression_type\"
+    description: <<END
+The type of compression for the file. Currently ZLIB and
+GZIP are supported. Defaults to none.
 END
   }

To update golden API files, run tensorflow/core/api_def/update_api_def.sh.
```

**Comment by yongtang** [comment]
Thanks @drpngx. The PR has been updated and pushed with changes from `tensorflow/core/api_def/update_api_def.sh`.

Most of the tests passed except `Linux CPU Tests (Python 3)`, which seems to be an infrastructure issue:
```
FATAL: command execution failed
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
```

Please take a look.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
Double-checking with @martinwicke for API if it's OK to merge.

**Comment by martinwicke** [comment]
Yes, these classes are not part of the public API at all, so this is good to go.

**Pull request merged**
