### PR TITLE
Cherry-pick python3 and libcuda.so fixes from master into r0.7 branch

### PR DESCRIPTION
**Pull request by vrv**
I think it would be nice to get these changes into the patch release too, at least the python3 bug fix one.  Thoughts?

### CODE REVIEW

**Comment by vrv** [comment]
@danijar: I assume this is okay since you contributed this already to master.

(This is a weird edge case @willnorris)

**Comment by willnorris** [comment]
yeah I've seen another case like this, where commits that were already reviewed and merge into one branch are simply being cherry-picked over to a different branch.  In these cases, you are much more likely to get into a "need author consent" state.  At the time, someone had suggested checking to see if the commit was already in the repo in a different branch, which might be possible.  I've cc'ed you on the internal bug.

**Comment by vrv** [comment]
Would it be safe to ignore the label, or should I still wait for consent?

**Comment by willnorris** [comment]
see [go/cla#github-consent](http://go/cla#github-consent).  This label will never change to "cla: yes", so yes it's safe to ignore in this case.

**Comment by vrv** [comment]
Ok, great, thanks :)

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

added a whl package change as well.

**Comment by vrv** [comment]
@tensorflow-jenkins: test this please

**Comment by vrv** [comment]
Merged

**Pull request closed without merging**
