### PR TITLE
Fix wrong includes for tensorflow-lite for ios

### PR DESCRIPTION
**Pull request by lukasfolle**
I was trying to build the ios examples for tensorflow lite, however several include statements seemed to be wrong. This PR is fixing this. 
Feel free to suggest any improvements.

### CODE REVIEW

**Comment by lufol** [comment]
Also I found this issue #26924. This should fix it as well.

**Comment by lamberta** [comment]
I'm not sure of the status of these examples. Maybe they should move into the `/lite` section of the [tensorflow/examples](https://github.com/tensorflow/examples) repo? @MarkDaoust @wolffg

**Comment by miaout17** [comment]
Thanks for fixing these. It seems accidentally broken a while ago. 

@lamberta Yes we plan to move most of the examples into tensorflow/examples, but it's not done yet. Meanwhile these changes look right. I'm going to approve this.

**Review by miaout17 — APPROVED** [review]

**Comment by lufol** [comment]
@dansitu @jdduke Can this be merged?

**Pull request merged**
