### PR TITLE
Add the tests for some tf.data kernels

### PR DESCRIPTION
**Pull request by feihugis**
This PR develops the tests for tf.data kernel implementations in C++. It designs a test base class and adds the tests for RangeDataset and MapDataset.

cc @jsimsa

### CODE REVIEW

**Comment by jsimsa** [comment]
```

Running do_buildifier on 412 files
tensorflow/core/kernels/data/BUILD # reformat listsort unsafesort sort:tf_cc_test.deps
buildifier took 0 s
FAIL: buildifier found errors and/or warnings in above BUILD files.
buildifier suggested the following changes:
212,213d211
<         ":map_dataset_op",
<         ":range_dataset_op",
216,217c214,215
<         "//tensorflow/core:testlib",
<         "//tensorflow/core:test_main",
---
>         ":map_dataset_op",
>         ":range_dataset_op",
222c220,221
<         "//tensorflow/core/kernels:function_ops",
---
>         "//tensorflow/core:test_main",
>         "//tensorflow/core:testlib",
223a223
>         "//tensorflow/core/kernels:function_ops",
399d398
<         ":range_dataset_op",
401c400
<         "//tensorflow/core:testlib",
---
>         ":range_dataset_op",
403c402
<
---
>         "//tensorflow/core:testlib",
Please fix manually or run buildifier <file> to auto-fix.
```

**Comment by jsimsa** [comment]
The other test failuers seems to be unreleated AFAICT.

**Comment by feihugis** [comment]
@jsimsa Thanks for running the tests. I fix the style issue in BUILD file (using this command `buildifier tensorflow/tensorflow/core/kernels/data/BUILD`). Could you run the test again?

**Comment by feihugis** [comment]
@jsimsa The test failures seem to be unrelated. After checking the logs, the failures are caused by TensorFlow lite, such as `ERROR: /tmpfs/src/github/tensorflow/tensorflow/lite/python/testdata/BUILD:10:1: Executing genrule //tensorflow/lite/python/testdata:permute_float failed (Exit 1)`

**Review by jsimsa — DISMISSED** [review]

**Comment by rthadur** [comment]
@feihugis can you please check the failed tests.

**Comment by feihugis** [comment]
@rthadur I can only access the failure logs of `MacOS Contrib` test. It is unrelated and caused by TensorFlow lite toco. This [PR](https://github.com/tensorflow/tensorflow/pull/25345) is pending for fixing this issue.

I don't know why I could not access other logs. Could you re-trigger the tests again?

**Comment by feihugis** [comment]
@rthadur Thanks for running the tests. These test failures are unrelated to this PR: 

- the test failures in`MacOS Contrib` and `MacOS Python2 and CC` are caused by TensorFlow lite; 

- the test failures in `Windows Bazel` are caused by `tensorflow/python/kernel_tests:lookup_ops_test`

**Comment by feihugis** [comment]
@jsimsa Does the log mean that some dependencies are missing in the BUILD file for the newly added tests? To fix the issues, the log suggests to run `build_cleaner //third_party/tensorflow/core/kernels/data:range_dataset_op_test`. But I did not find a way to install `build_cleaner`. Do you know how to install `build_cleaner`?

**Comment by jsimsa** [comment]
Yes, that's what it means. Build cleaner is an internal tool. You will need to make sure that for the listed header files, you add dependencies that provide them.

**Pull request merged**
