### PR TITLE
refine server.py

### PR DESCRIPTION
**Pull request by frankfqchen**
delete .keys()
no need to get keys()
just use 'in' instead

### CODE REVIEW

**Review by jart — APPROVED** [review]

**Comment by jart** [comment]
LGTM. Thank you for your contribution.

Mr. Jenkins: test this please

**Comment by hestendelin** [comment]
when this can be merges?

**Comment by hestendelin** [comment]
when this pull can be merged?

**Comment by guotong1988** [comment]
I think the code will make it more unreadable.

**Comment by terrytangyuan** [comment]
@frankfqchen Could you combine your other PRs for such small and similar  change?

**Comment by jart** [comment]
Good catch @terrytangyuan. Seven one-line code health commits is not something we want in the commit history. @frankfqchen could you please merge this pull request (along with the others) into #4951 since that's the only one with an actionable comment?

**Pull request closed without merging**
