### PR TITLE
Branch 141580230

### PR DESCRIPTION
**Pull request by andrewharp**
Pushing internal changes

### CODE REVIEW

**Comment by gunan** [comment]
The half_plus_two rules are referenced also from:
tensorflow/cc/saved_model/BUILD  loader_test rule
tensorflow/python/saved_model/BUILD  saved_model_test
tensorflow/contrib/session_bundle/BUILD  bundle_shim_py_test session_bundle_test session_bundle_py_test rules.

**Comment by gunan** [comment]
@andrewharp the current test failures can be seen in your branch.
`extract` function is defined twice in `tensorflow/contrib/learn/python/learn/estimators/estimator_test.py`
maybe a merge conflist resolution issue?

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
Once the tests pass, good to go

**Comment by caisq** [comment]
The build "Linux CPU Tests" failed because several tutorials in tensorflow/models have been removed. This is not a big deal - we can fix it easily by removing them from test_tutorials.sh.

The "Linux GPU" build failed due to two timeouts:
//tensorflow/python/kernel_tests:fft_ops_test
//tensorflow/python/kernel_tests:shape_ops_test

The first one looks like an existing flaky timeout. The second one may be related to this push? In any case, I think we should move ahead and merge this pushing PR. @gunan @andrewharp

**Comment by andrewharp** [comment]
If I had to guess, the Windows cmake failure is also due to half_plus_two_data being missing: https://github.com/tensorflow/tensorflow/pull/6223/files#diff-79d31bc9f4560bd3b40a78be48d3a228

**Pull request merged**
