### PR TITLE
Fix go proto handling

### LINKED ISSUE #35133: Installing tensorflow go failed
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac os 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): n/a
- TensorFlow version: n/a
- Python version: n/a
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**
Followed https://www.tensorflow.org/install/lang_go
but got this:
go get github.com/tensorflow/tensorflow/tensorflow/go
package github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core" in any of:

go get -d github.com/tensorflow/tensorflow/tensorflow/go
yielded the same result.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### PR DESCRIPTION
**Pull request by jhseu**
Fixes #35133 and #34580

### CODE REVIEW

**Review by frankchn — APPROVED** [review]

**Comment by JWMHayhurst** [comment]
Tested out the solution. This seems to now cause an import cycle.

**Comment by frankchn** [comment]
@JWMHayhurst can you file a bug with what you are running and the error message?

**Comment by jhseu** [comment]
I have a change out to fix the import cycle. Will submit today.

**Comment by jhseu** [comment]
Fixed in https://github.com/tensorflow/tensorflow/commit/4221d1aa4d20ada495771528bb13ca786d0bdbe0

**Pull request merged**
