### PR TITLE
Add ability to use default values via environment variables

### PR DESCRIPTION
**Pull request by ghost**
Extend get_from_env_or_user_or_default() to look for an environment
variable named 'USE_DEFAULT_' + var_name, which if set to 1, causes the
default value to be used and not prompt the user for input.

Similar to how setting USE_DEFAULT_PYTHON_LIB_PATH to 1 causes the
default Python path to be used, this allows the default values for other
config vars to be used (e.g. CUDA_TOOLKIT_PATH, CUDNN_INSTALL_PATH,
GCC_HOST_COMPILER_PATH, and CC_OPT_FLAGS).

### CODE REVIEW

**Comment by gunan** [comment]
I am not sure I see the benefit of this change.
Why cant we just override the environment variables when running configure, like follows:
```
CC_OPT_FLAGS="" CUDA_TOOLKIT_PATH="" ./configure
```

**Comment by dtrebbien** [comment]
Right now, setting the environment variable to an empty string still causes the configure script to prompt for user input.

get_from_env_or_user_or_default() could be alternatively changed as follows:
 * If the environment variable is set, then don't prompt for user input.
 * Also, if the environment variable is set to "", then assume the user wants to use the default value.

This would accomplish basically the same thing of allowing default values for configure variables to be used through setting environment variables, and thus to allow a small shell script to be written which configures and builds TensorFlow without requiring user input. However, I personally think that `USE_DEFAULT_*=1` communicates the intention of using a default value a bit better than `*=""`. Moreover, in the case of CC_OPT_FLAGS, what if someone actually wants to use no extra compiler flags in the opt build configuration. They might use something like `CC_OPT_FLAGS=" "`, but this is one character away from `CC_OPT_FLAGS=""`. It's not clear unless one is familiar with the implementation of the configure script that this would mean something quite different from `CC_OPT_FLAGS=" "`.

**Comment by gunan** [comment]
How about:
```
yes "" | ./configure
```
After setting the non-default environment variables?

**Comment by dtrebbien** [comment]
The problem with this is that if a new configuration option is added, then I won't know about it because the default will automatically be selected.

**Comment by gunan** [comment]
In the availability of defaults case, you will be broken until you set the variable. This is usually undesirable for upstream projects, but in your case you specifically are looking for being broken when there is a change in configure?

Nevertheless, I still do not see a benefit that outweighs the added complexity in configuration script.
Also, our future plans involve deprecating configure script, and routing everything through `--config` flags in bazel. So I am inclined to reject this PR.

**Comment by dtrebbien** [comment]
> In the availability of defaults case, you will be broken until you set the variable. This is usually undesirable for upstream projects, but in your case you specifically are looking for being broken when there is a change in configure?

Yes.  This is not for an upstream project, but for my personal use in building TensorFlow at HEAD.  Whenever I pull from TensorFlow's repository, I need to reconfigure and rebuild.  The small shell script that I have written helps me with that so I don't make a configuration mistake.  If there is a new configuration option added, I would like to know about it.

> Nevertheless, I still do not see a benefit that outweighs the added complexity in configuration script. Also, our future plans involve deprecating configure script, and routing everything through `--config` flags in bazel. So I am inclined to reject this PR.

What is the issue number for this?  I would like to subscribe to that ticket.

**Comment by gunan** [comment]
There is an internal bug, but there is no external issue we have for deprecating configure script.
@mikecase how far are you into the work for removing configuration script?

**Comment by case540** [comment]
configure.py is still used for some things that dont have good replacements within Bazel. Working on it, but I would expect configure.py to still exist for several months.

Now that configure.py is a python script, one thing I was thinking we could do short-term is just have python arguments to set these options instead of environment variables. That way its clear how your project is being configured by the single-line configure.py invocation. Also, could add proper --help option.

Im pretty against support further ENV variables for the configure script.

**Pull request closed without merging**
