### PR TITLE
[Intel MKL] Restructuring layout pass tests for bfloat16 - part 4

### PR DESCRIPTION
**Pull request by nhasabni**

### CODE REVIEW

**Comment by gbaned** [comment]
@nhasabni Thank you for your contribution. Can you please sign CLA? Thanks!

**Comment by nhasabni** [comment]
@gbaned I've singed the CLA already. Not sure what's the issue now. https://cla.developers.google.com/clas shows Googe Corporate CLA.

**Comment by nhasabni** [comment]
@googlebot I signed it!

**Review by penpornk — APPROVED** [review]
Thank you for the PR and I'm sorry for the delay!

**Pull request merged**
