### PR TITLE
Some XLA utility functions

### PR DESCRIPTION
**Pull request by nouiz**
Add to XLA those utility functions:
- `ShapeUtil::EqualIgnoringElementType`

Also fill a TODO in comment to generalize some fusion optimization by reusing `ShapeUtil::EqualIgnoringElementType`. This will allow MOF fusion when the outputs have different element type, not just different float precision.

@sanjoy @d0k

### CODE REVIEW

**Comment by cheshire** [comment]
Could these be split into multiple commits? Also are all these strictly additive non-functional changes? I saw a TODO removed and some logic changed. Is there a PR which uses those utilities?

**Comment by nouiz** [comment]
This is part of a bigger PR that I'm working on. It depends on 2 PR, this one and https://github.com/tensorflow/tensorflow/pull/31929

To help the review I split part of the bigger PR to come that was independent.
I could make in the next few days the bigger PR that would include those 2 PRs.

How do you want me to split this PR? I can make 3:
The changes to window_utils, the changes to hlo_creation_utils and those that fill the TODO that I implemented?

**Comment by cheshire** [comment]
> The changes to window_utils, the changes to hlo_creation_utils and those that fill the TODO that I implemented?

Yes, that sounds great.

**Comment by nouiz** [comment]
The split is done. This PR only keep the TODO being filled.
The 2 others PR: https://github.com/tensorflow/tensorflow/pull/32263 and https://github.com/tensorflow/tensorflow/pull/32264

I also updated the description of this PR.

**Review by cheshire — APPROVED** [review]

**Pull request merged**
