### PR TITLE
Fix ClusterSpec.as_dict with only chief and ps

### PR DESCRIPTION
**Pull request by DeliangFan**
If the worker num is zero, continue the loop.

### CODE REVIEW

**Review by mrry — CHANGES_REQUESTED** [review]
Can you please add a test for this new code? Thanks!

**Comment by DeliangFan** [comment]
reply @mrry  All right, I would add a unittest later.

**Comment by DeliangFan** [comment]
@mrry Hi, mrry, would you please take a review, thanks very much.

**Review by mrry — APPROVED** [review]

**Comment by DeliangFan** [comment]
@harshini-gadige Hi, harshini, the Windows Bazel checks get failed, but there is no any details. Would you please tell me how to deal with it.  Thank you very much!

**Comment by harshini-gadige** [comment]
> @harshini-gadige Hi, harshini, the Windows Bazel checks get failed, but there is no any details. Would you please tell me how to deal with it. Thank you very much!

I've bypassed those 2 failures and proceeding to get this merged.

**Pull request merged**
