### PR TITLE
Update api_def_StringLower.pbtxt

### PR DESCRIPTION
**Pull request by rohanreddych**
#35652 Pull request in relation to the mentioned issue.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Please follow documentation guide at https://www.tensorflow.org/community/contribute/docs_ref and make them testable docstrings.

Note also the merging comment in #35659

**Comment by pbaranay** [comment]
Rohan, do you want to additionally combine this as additional commits in #35647, or at least base your branch off of that commit? As-is, the summary fields you're adding conflict with the ones I'm proposing.

Thanks for elaborating further on the missing docs!

**Comment by rohanreddych** [comment]
Should I close this pull request and make another one?

**Comment by mihaimaruseac** [comment]
Close this and move work onto #35659 or close that one and move work onto this. Either is fine.

**Comment by rohanreddych** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_Sin.pbtxt 
I followed the syntax of this file in making the pull request, can I know what are the changes I should be making?

**Comment by mihaimaruseac** [comment]
There is a conflict that needs to be solved

**Comment by rohanreddych** [comment]
I just tried to resolve the conflicts, I edited the file and commited it, It was taking a long time so I reloaded the page now I cant see the `Resolve Conflicts` link (button).

**Comment by mihaimaruseac** [comment]
Did you delete the fork?

**Comment by rohanreddych** [comment]
Yep, so should I close this and open another one?

**Comment by mihaimaruseac** [comment]
Yes please

**Pull request closed without merging**
