### PR TITLE
Fixed link error on MSVC(2019).

### PR DESCRIPTION
**Pull request by rabbitfoot530**
This commits a solve link error when build tflite on Windows with MSVC(2019).

MSVC does not need a link for m.lib. Because MSVC dose not have it.

The _m_ link cause of linker error on MSVC.

We can check the error (not found m.lib) by following command on Windows PowerShell.

```
cd tensorflow/tensorflow/lite/examples/minimal
mkdir b
cd b
cmake -G "Visual Studio 16 2019" .
cmake --build . -j
```

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @rabbitfoot530  Can you please review this PR ? Thank you!

**Review by terryheo — APPROVED** [review]
LGTM

**Comment by gbaned** [comment]
@rabbitfoot530 Can you please resolve conflicts? Thank you!

**Comment by rabbitfoot530** [comment]
@gbaned I fixed the conflict. Could you check the result?

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
