### PR TITLE
INTEL-MKL:  Enhance Mkl conv2d backward (filter and input) ops with primitive reuse

### PR DESCRIPTION
**Pull request by gzmkl**
1. Enable MKL primitive reuse for backward conv2d (filter & input) to improve performance of
   (1) model training and
  (2) inference of small batch size

### CODE REVIEW

**Comment by gzmkl** [comment]
Hi Rasmus, please let me know when you start to review this.
I have budgeted my time to take actions on your suggestions for code change.
Best,
GZ

**Comment by gzmkl** [comment]
For conv2d forward related refactoring work, I will create a new PR. 
Once the new PR is reviewed and merged, I will reopen this one.

**Comment by gzmkl** [comment]
Reopen since PR #19754 has been approved

**Review by tatianashp — APPROVED** [review]
Looks fine.

**Comment by tatianashp** [comment]
cc: @yifeif

**Pull request merged**
