### PR TITLE
Comment out dynamic slice tests that rely on wrapping

### PR DESCRIPTION
**Pull request by Timmmm**
The wrapping behaviour has not yet been specified so it can't be tested. See https://groups.google.com/forum/#!topic/xla-dev/XQ7LbZOg9Nc

### CODE REVIEW

**Comment by Timmmm** [comment]
> The bad news is that it appears that one or more commits were authored by someone other than the pull request submitter.

I am me. That is to say, the git commit contains my work email but I'm submitting using my non-work github account (since I don't have a work github account). Both emails are in our work CLA group.

**Comment by gunan** [comment]
Once we have the approval, I can push the change through as you the email has CLA and you have expressed your consent for merging the PR.

**Comment by martinwicke** [comment]
If you add your work email to your GitHub account that would also resolve the CLA issue.

**Comment by Timmmm** [comment]
Ah cool I have done that now, thanks.

**Comment by martinwicke** [comment]
@hawkinsp could you take a look?

**Review by hawkinsp — APPROVED** [review]
Sorry, I never noticed this PR in my inbox. The change is fine (not sure if it still applies),

Thanks for the PR!

**Comment by martinwicke** [comment]
@Timmmm can you resolve the conflicts? I don't know what would be correct here.

**Comment by drpngx** [comment]
@Timmmm could you pull rebase and push again? Otherwise it looks like it should be good to go, assuming the tests pass.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
Closing for now. Please reopen if you have an update.

**Pull request closed without merging**
