### PR TITLE
Udacity example 1: import urllib for download

### PR DESCRIPTION
**Pull request by ah-**
Really minor, import urllib so the dataset download below just works the first time.

### CODE REVIEW

**Comment by ah-** [comment]
Signed it!

**Comment by vrv** [comment]
I think this may be superceded by a change @vincentvanhoucke recently made ...

**Comment by ah-** [comment]
Do you mean this one? https://github.com/tensorflow/tensorflow/commit/6e5a7d9af85d67ec1dd499b472472b68a56d51a2

How recently? I cloned around half an hour ago.

**Comment by ah-** [comment]
Oh, I see. Updated to use urlretrieve from six as intended.

**Comment by vrv** [comment]
@vincentvanhoucke already fixed this internally (we'll be pushing it out soon).

**Pull request closed without merging**
