### PR TITLE
Add parameter to specify inner activations for rnn cells

### PR DESCRIPTION
**Pull request by danijar**
Allow to specify activation function of inner states for GRU, BasicLSTM and LSTM cells. The paramter defaults to `tanh` so that existing code does not need to be changed. This is equivalent to the `activation` parameter for GRU and the `inner_activation` parameter for LSTM in Keras and the `activation` parameter for LSTM and GRU in Theanets.

### CODE REVIEW

**Comment by petewarden** [comment]
Test this please, Jenkins.

**Comment by ebrevdo** [comment]
We have some changes incoming to the signature of the various RNN Cells.  This change has a few lines conflicting with it, so will hold off till Wednesday or so to review.

**Comment by danijar** [comment]
@ebrevdo Any update on this?

**Comment by ebrevdo** [comment]
Yes - please rebase, resolve any conflicts, and ping when ready.

**Comment by danijar** [comment]
Ping

**Comment by ebrevdo** [comment]
Jenkins, test this please.

**Comment by ebrevdo** [comment]
Jenkins, test this please.

**Comment by ebrevdo** [comment]
Thanks!

**Pull request merged**
