### PR TITLE
[TF-TRT] Replace TRT FullyConnected (deprecated) with Matmul Layer

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
This PR removes the deprecated FullyConnected TRT layer in favor of TRT Matmult.
Change only applies for TRT >= 8.0.0.

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
CC: @tfeher 
Review: @bixia1

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @bixia1 Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @pjannaty Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @pjannaty Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @pjannaty Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @pjannaty Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @DEKHTIARJonathan, @pjannaty  I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for your contribution!

**Pull request closed without merging**
