### PR TITLE
Add CUDA and cuDNN Configuration to TensorFlow WORKSPACE

### PR DESCRIPTION
**Pull request by nehalmr**
## Description:
This pull request adds configurations to TensorFlow’s WORKSPACE file to properly include CUDA and cuDNN support, addressing the issue where TensorFlow fails to find the CUDA compiler.

## Files Changed:
tensorflow/WORKSPACE
tensorflow/tools/ci_build/gpu_build.sh (new script)

## Changes Made:
Added CUDA and cuDNN repository configurations to the WORKSPACE file.
Added a script to verify CUDA and nvcc installation.

## Instructions to Test:
Update the WORKSPACE File: Apply the changes to include CUDA and cuDNN.
Run the Verification Script: Use gpu_build.sh to ensure CUDA and nvcc are correctly set up.
Build TensorFlow: Follow the standard build instructions to confirm that CUDA support is correctly integrated.

### CODE REVIEW

**Comment by nehalmr** [comment]
## Title: Add CUDA and cuDNN Configuration to TensorFlow WORKSPACE

Description:
This pull request addresses issue [#72879](https://github.com/tensorflow/tensorflow/issues/72879), where TensorFlow fails to find the CUDA compiler with the error Could not find compiler for platform CUDA: NOT_FOUND. The updates ensure TensorFlow's build configuration correctly includes CUDA and cuDNN support and provides a script to verify the CUDA setup.

Files Changed:

tensorflow/WORKSPACE
tensorflow/tools/ci_build/gpu_build.sh (new script)
Changes Made:

Updated WORKSPACE file: Added repository configurations for CUDA and cuDNN to ensure they are included in the TensorFlow build system.
Added gpu_build.sh script: This script sets the necessary environment variables and verifies the CUDA installation and nvcc compiler.
Example Code Changes:

tensorflow/WORKSPACE:

python
Copy code
# Define CUDA path
new_local_repository(
    name = "cuda",
    path = "/usr/local/cuda-12.2",
    build_file_content = """
cc_library(
    name = "cuda",
    includes = ["include"],
    linkopts = ["-Llib64"],
    deps = [],
)
"""
)

# Define cuDNN path
new_local_repository(
    name = "cudnn",
    path = "/usr/local/cuda-12.2-cudnn",
    build_file_content = """
cc_library(
    name = "cudnn",
    includes = ["include"],
    linkopts = ["-Llib64"],
    deps = [],
)
"""
)
Create gpu_build.sh:

bash
Copy code
#!/bin/bash

# Set CUDA and cuDNN paths
export CUDA_HOME=/usr/local/cuda-12.2
export CUDNN_INCLUDE_DIR=/usr/local/cuda-12.2-cudnn/include
export CUDNN_LIB_DIR=/usr/local/cuda-12.2-cudnn/lib64

# Ensure CUDA compiler is in PATH
export PATH=$CUDA_HOME/bin:$PATH

# Verify CUDA compiler
if ! command -v nvcc &> /dev/null; then
    echo "nvcc not found. Please ensure CUDA is installed and nvcc is in your PATH."
    exit 1
fi

# Check CUDA version
nvcc --version
Instructions to Test:

Update the WORKSPACE File: Apply the changes to include CUDA and cuDNN configurations.
Run the Verification Script: Execute gpu_build.sh to confirm that CUDA and nvcc are correctly set up.
Build TensorFlow: Follow the standard build instructions to ensure CUDA support is integrated properly.
Additional Notes:

This pull request aims to resolve the compilation issue reported in [#72879](https://github.com/tensorflow/tensorflow/issues/72879) by ensuring TensorFlow can correctly locate and use the CUDA compiler.
Ensure that the CUDA version specified (12.2) matches your installation.

**Comment by nehalmr** [comment]
## Title: Add CUDA and cuDNN Configuration to TensorFlow WORKSPACE

**Description:**
This pull request addresses issue [#72879](https://github.com/tensorflow/tensorflow/issues/72879), where TensorFlow fails to find the CUDA compiler with the error Could not find compiler for platform CUDA: NOT_FOUND. The updates ensure TensorFlow's build configuration correctly includes CUDA and cuDNN support and provides a script to verify the CUDA setup.

**Files Changed:**

tensorflow/WORKSPACE
tensorflow/tools/ci_build/gpu_build.sh (new script)
**Changes Made**:

Updated WORKSPACE file: Added repository configurations for CUDA and cuDNN to ensure they are included in the TensorFlow build system.
Added gpu_build.sh script: This script sets the necessary environment variables and verifies the CUDA installation and nvcc compiler.

**Instructions to Test:**

Update the WORKSPACE File: Apply the changes to include CUDA and cuDNN configurations.
Run the Verification Script: Execute gpu_build.sh to confirm that CUDA and nvcc are correctly set up.
Build TensorFlow: Follow the standard build instructions to ensure CUDA support is integrated properly.
Additional Notes:

This pull request aims to resolve the compilation issue reported in [#72879](https://github.com/tensorflow/tensorflow/issues/72879) by ensuring TensorFlow can correctly locate and use the CUDA compiler.
Ensure that the CUDA version specified (12.2) matches your installation.

**Comment by eyalhir74** [comment]
@nehalmr Thanks for your assistance!
I've applied the changes you've suggested but I'm still getting the same error (execuse me for not being a Bazel expert)..
Your script's output gives me this:
root@spd-toy-gpu:/tensorflow-serving# ./test.sh
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

There's also no /usr/local/cuda-12.2-cudnn/ folder created on my env

**Comment by nehalmr** [comment]
# 1. Install cuDNN
You can download and install cuDNN from the NVIDIA website. Make sure to select the version that matches your CUDA version (12.2 in this case).

```bash

# Assuming you have downloaded the cuDNN tar file
tar -xzvf cudnn-linux-x86_64-8.x.x.x_cuda12-archive.tar.xz
sudo cp cuda/include/cudnn*.h /usr/local/cuda-12.2/include
sudo cp -P cuda/lib64/libcudnn* /usr/local/cuda-12.2/lib64
sudo chmod a+r /usr/local/cuda-12.2/include/cudnn*.h /usr/local/cuda-12.2/lib64/libcudnn*
```

# 2. Verify Environment Variables
Ensure the environment variables are correctly pointing to the CUDA and cuDNN directories.

```bash

export CUDA_HOME=/usr/local/cuda-12.2
export CUDNN_INCLUDE_DIR=/usr/local/cuda-12.2/include
export CUDNN_LIB_DIR=/usr/local/cuda-12.2/lib64

export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$CUDNN_LIB_DIR:$LD_LIBRARY_PATH
```

Steps to Test
1) Install cuDNN:
Follow the steps to install cuDNN and ensure it is in the correct directory.

2) Set Environment Variables:
Make sure the environment variables point to the correct locations for CUDA and cuDNN.

3) Update WORKSPACE File:
Ensure the paths in the WORKSPACE file are correct.

4) Run the Verification Script:
Execute gpu_build.sh to verify that both CUDA and cuDNN are properly set up.

5) Build TensorFlow:
Follow the standard TensorFlow build instructions.

**Comment by keerthanakadiri** [comment]
Hi @MichaelHudgins , Can you please review this PR? Thank you !

**Comment by keerthanakadiri** [comment]
Hi @nehalmr, Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @nehalmr, Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @nehalmr, Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @nehalmr, Can you please resolve the conflicts? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @nehalmr, Can you please resolve the conflicts? Thank you!

**Comment by nehalmr** [comment]
I apologize; I am actually starting over due to a glitchy environment.

**Pull request closed without merging**
