### PR TITLE
Support session config in tf.contrib.predictor

### PR DESCRIPTION
**Pull request by lgeiger**
This PR allows users to supply a custom session config uses by `tf.contrib.predictor`.

This can be essential for some GPU setups in order to play nicely with other processes running on the same GPU.

### CODE REVIEW

**Comment by case540** [comment]
Thanks for the PR! This looks good to me, but can you add a test using the session config. thanks

**Comment by lgeiger** [comment]
Sure, I'll add a unittest.

Is there a good way to check that the session config is really used other than accessing the private `sess._config` value?

**Comment by lgeiger** [comment]
@case540 Thanks for the review.

I added unittests for the factory methods testing the config option.

**Comment by lgeiger** [comment]
I added unittests, could someone trigger CI so we can verify that everything works correctly?

**Review by case540 — APPROVED** [review]
Not really familiar with this code, but this all looks good to me. Thanks for the PR

**Pull request merged**
