### PR TITLE
Update train.py

### PR DESCRIPTION
**Pull request by gautam1858**
This fixes several warnings in tf.contrib.gan by switching to addsummaries in tfgan_losses

### CODE REVIEW

**Comment by martinwicke** [comment]
@joel-shor is `addsummaries` really the preferred name? That seems to run counter to the style guide for naming.

**Comment by joel-shor** [comment]
I don't understand this proposed change.

1) There are no arguments called `addsummaries` anywhere in TFGAN, so I suspect this PR will cause tensorflow/models tests to fail.

2) @gautam185 What warnings are you trying to avoid with this?

**Comment by gautam1858** [comment]
@joel-shor this WARNING:tensorflow:update_ops in create_train_op does not contain all the  update_ops

**Comment by joel-shor** [comment]
Your change will cause errors, and won't fix the problem. The issue should be fixed if you use the nightly build instead of the default one, and will be fixed by default when the next TensorFlow release is made.

**Pull request closed without merging**
