### PR TITLE
Add customerized kernel implementation for clip_by_value

### PR DESCRIPTION
**Pull request by yongtang**
This fix is a follow up on #13998 as it was reverted in https://github.com/tensorflow/tensorflow/commit/943201bf1a959acf6a08b88a488b3db55404835c

This fix adds the customerized kernel implementation for `tf.clip_by_value`.

This fix is related to #13998, also see #15427

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by drpngx** [comment]
@benoitsteiner WDYT?

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment]
The PR has been rebased to address merge conflict.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment]
Rebased to address the merge conflict.

**Review by benoitsteiner — APPROVED** [review]

**Pull request merged**
