### PR TITLE
Add float64 support for conv1d and conv2d

### LINKED ISSUE #12941: float64 support for conv1d and conv2d
This is a feature request for `float64` support with `nn.conv1d`, `nn.conv2d`, and `nn.convolution`. Also, `conv1d` does not correctly document which types it supports. See below for details.

`conv1d` (which seems to be a wrapper for `conv2d`) and `conv2d` throw a TypeError when passed `float64` tensors. (I have only tested using a CPU; I don't have GPU access.) This occurs despite the fact that the documentation for `conv1d` claims support for `float64`. It is also worth mentioning that (at least on my CPU), `conv1d` seems to support `float16` even though this isn't mentioned in the documentation.

`conv3d` does however seem to support `float64`. Fortunately, this can at least be used as a temporary workaround to obtain `float64` support for 1d and 2d convolutions.

| Command | float16 | float32 | float64 |
| --- | --- | --- | --- |
| conv1d | works, but undocumented | works | TypeError, despite documentation |
| conv2d | works | works | TypeError |
| conv3d | TypeError | works | works |

The above table summarizes the (rather inconsistent) current state of tensorflow's support for various types according to my tests on a CPU using the code below. `convolution` appears to be a wrapper for `conv1d`, `conv2d`, and `conv3d`, and thus fails on the same types for each dimension.

```python
import tensorflow as tf
# t = tf.float16
# t = tf.float32
t = tf.float64
b, fw1, fw2, fw3, ic, oc, iw1, iw2, iw3 = range(2,11)
tf.nn.conv1d(tf.zeros([b, iw1, ic], t), tf.zeros([fw1, ic, oc], t), 1, "VALID")
tf.nn.conv2d(tf.zeros([b, iw1, iw2, ic], t), tf.zeros([fw1, fw2, ic, oc], t), [1]*4, "VALID")
tf.nn.conv3d(tf.zeros([b, iw1, iw2, iw3, ic], t), tf.zeros([fw1, fw2, fw3, ic, oc], t), [1]*5, "VALID")
tf.nn.convolution(tf.zeros([b, iw1, ic], t), tf.zeros([fw1, ic, oc], t), "VALID")
tf.nn.convolution(tf.zeros([b, iw1, iw2, ic], t), tf.zeros([fw1, fw2, ic, oc], t), "VALID")
tf.nn.convolution(tf.zeros([b, iw1, iw2, iw3, ic], t), tf.zeros([fw1, fw2, fw3, ic, oc], t), "VALID")
```

### System information
- **Have I written custom code**: No
- **OS Platform and Distribution**: Arch Linux (up to date)
- **TensorFlow installed from**: source
- **TensorFlow version**: 1.3.0
- **Python version**: 3.6.2
- **Bazel version**: 0.5.4

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in  #12941 where `float64` for conv1d and conv2d is incomplete.

This fix adds:
- float64 support for conv1d
- float64 support for conv2d
- float16 support for conv3d
- updated docs for float16 support of conv1d (already supported).

This fix fixes #12941.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by drpngx — CHANGES_REQUESTED** [review]
We'll need tests for that. Could you update the unit test?

**Comment by yongtang** [comment]
@drpngx Thanks for the review. The unit tests has been updated. Please take a look.

**Comment by drpngx** [comment]
Jenkins, test this please.

**Comment by yongtang** [comment]
@drpngx The Jenkins failure was caused by pylint sanity check. I have updated the PR with pylint issue fixed. Please take a look.

**Comment by drpngx** [comment]
Jenkins, test this please

On Sep 11, 2017 1:40 PM, "Yong Tang" <notifications@github.com> wrote:

@drpngx <https://github.com/drpngx> The Jenkins failure was caused by
pylint sanity check. I have updated the PR with pylint issue fixed. Please
take a look.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/pull/12943#issuecomment-328650961>,
or mute the thread

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Review by drpngx — APPROVED** [review]

**Comment by sb2nov** [comment]
@yongtong there is a compilation error in some of the tests. Can you take a look.

**Comment by yongtang** [comment]
Thanks @sb2nov. The PR has been rebased and pushed. I tested locally and it passes. Please take a look.

**Comment by sb2nov** [comment]
Jenkins, test this please.

**Comment by drpngx** [comment]
This doesn't appear to build:

```
tensorflow/core/kernels/conv_grad_filter_ops.cc:945:1:   required from here
./tensorflow/core/kernels/eigen_spatial_convolutions.h:730:34: error: no matching function for call to 'ptranspose(Eigen::internal::PacketBlock<__vector(2) double, 4>&)'
```

**Comment by yongtang** [comment]
@drpngx @sb2nov The Jenkins failure is for real, though I am not able to reproduce with my local dev machine from the command line `bazel test -s --config=opt --verbose_failures //tensorflow/core/kernels:all` yet.

I will take a look at the Jenkins setup and see if I could reproduce with:
```sh
export USER=jenkins
export TF_BUILD_CONTAINER_TYPE=CPU
export TF_BUILD_PYTHON_VERSION=PYTHON2
export TF_BUILD_IS_OPT=OPT
export TF_BUILD_IS_PIP=NO_PIP
export TF_BUILD_APPEND_CI_DOCKER_EXTRA_PARAMS=-e TF_BUILD_FILTER_INSTALL_TESTS_BY_TAG=-manual
tensorflow/tools/ci_build/ci_parameterized_build.sh
```

**Comment by yongtang** [comment]
I am able to reproduce the error with docker/ci script though I am still not able to reproduce with standalone command line:
```
bazel test -s --config=opt --verbose_failures //tensorflow/python/kernel_tests:conv1d_test
```

One difference between docker/CI script and the above standalone command line seems to be `--distinct_host_configuration=false`.

Will need to investigate further to see what is exactly the difference.

**Comment by gunan** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
@yongtang can you resolve the conflicts?

**Comment by yongtang** [comment]
@martinwicke This PR probably is not easy to fix.

On my dev machine if running bazel directly without docker (and gcc 5.4.0+ubuntu 16.04) everything is fine.

However, when running inside docker (similar to what is invoked in Jenkins CI with `tensorflow/tools/ci_build/ci_parameterized_build.sh`) then build will fail.

I have been investigating this issue for some time. I would guess the reason is that, certain flags are passed by bazel inside/outside container differently. And I tend to guess that `ptranspose` in Eigen might have been hidden by certain flags. However, I am still relatively new to bazel's build system and haven't been able to figure out what exactly is the issue here.

Currently there are several pending issues in TF (#12941 and #13097) and Keras (fchollet/keras#7176) that is related to this PR. But I am afraid this may not be resolved soon.

I think maybe this issue could be labeled as `stalled` or we could closed it for now. I will try to revisit this issue after I have a better understanding of the bazel's flags.

Sorry about the inconvenience.

**Comment by drpngx** [comment]
@yongtang Yes, that's right, we run the build under `ci_parameterized_build.sh`. Just to be clear, you want to know how blaze is run, or what commands blaze runs?

**Comment by martinwicke** [comment]
Thanks. I will mark it stalled for now. If you need help with bazel, we can help.

**Comment by martinwicke** [comment]
I'll close this for now -- please reopen a new one (or ping me to reopen it).

**Comment by redouanelg** [comment]
Hi @yongtang, any news about float64 support for conv2d? thanks

**Comment by yongtang** [comment]
@redouanelg The last time I worked on this issue is in #16273. The problem has been reduced to the configurations/flags in Eigen library. Though I haven't been able to find out the solution yet. Will looking into it again if possible.

**Pull request closed without merging**
