### PR TITLE
Prelu graph Bug fix and added TODO

### PR DESCRIPTION
**Pull request by amitsrivastava78**
Bug fix along with the TC.

### CODE REVIEW

**Comment by amitsrivastava78** [comment]
@karimnosseir , this is kind of important PR for me, can you please review the PR.

Regards
Amit

**Review by karimnosseir — COMMENTED** [review]
Can you please expand the description.
What is the bug/bug fix and todo for what 

Thanks

**Comment by amitsrivastava78** [comment]
@karimnosseir thanks for spending time on the PR, i also felt this is getting more complex, so i have removed the TODO part and for now i have only given the BUG fix and TC added to verify the bug fix. Once you review , approve and hopefully this gets merged , will upstream the TODO part as well.

Regards
Amit

**Comment by gbaned** [comment]
@karimnosseir can you please review this PR ?

**Comment by gbaned** [comment]
@amitsrivastava78 could you please resolve the conflicts? Thanks!

**Comment by amitsrivastava78** [comment]
Closing the PR since another one is already existing

**Pull request closed without merging**
