### PR TITLE
1.8.0-rc1 cherry-pick request: some fixes for boosted_trees

### PR DESCRIPTION
**Pull request by yk5**
After the fixes:
 * Stopping training at the right moment, without extra layers.
 * BoostedTreesClassifier and BoostedTreesRegressors work well with batched Dataset now.
 * Dependency between resource serialization and prediction is set properly.

@annarev This is the list of cherrypicks that I wish to merge. Please let me know if I need to do anything else. Thanks!

### CODE REVIEW

**Comment by yifeif** [comment]
Thanks @yk5! Could you take a look at the build failure?

**Comment by yifeif** [comment]
Looks like the build failure is irrelevant.

**Comment by yk5** [comment]
Hmm. Let me look at it. What's the timeline for Cherrypicks for RC1?

**Comment by yifeif** [comment]
By EOD Tuesday 04/17. I will start building the binaries on Wednesday.

**Review by yifeif — APPROVED** [review]

**Comment by yk5** [comment]
Thanks!

**Pull request merged**
