### PR TITLE
Find NCCL2 debians in Tensorflow configure

### PR DESCRIPTION
**Pull request by jayfurmanek**
Continuation of https://github.com/tensorflow/tensorflow/pull/20155

The Tensorlfow configure doesn't work with NCCL2 when it is installed via the debians.
This PR adds code that will handle the following scenarios:

    NCCL2 installed via unpacked .tar file and not listed in ldconfig
    NCCL2 installed via unpacked .tar file and listed properly in ldconfig
    NCCL2 installed via debian file and not listed in ldconfig
    NCCL2 installed via debian file and listed properly in ldconfig

The debian places the lib and header in the system paths (`/usr/lib/*-linux-gnu` and `/usr/include`). A new environment variable `NCCL_HDR_PATH` was created to deal with the divergence in the lib and header paths in this scenario. The `third_party/nccl/nccl_configure.bzl` file was changed to look up the new environment variable for the header location.

### CODE REVIEW

**Comment by tfboyd** [comment]
NCCL 2 is open source which should allow us to make this easier.  Not to side track the effort. :-)

**Comment by jayfurmanek** [comment]
Yup, just posted:
https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/rel_2.3.5.html
https://github.com/NVIDIA/nccl

I think this PR is still valid for folks that have installed .debs manually on their system or perfer to use the .debs for package management.

**Comment by tfboyd** [comment]
agree

**Review by chsigg — APPROVED** [review]
Thank you very much for taking care of my TODO item. The code looks good to me.

We are working on allowing to build NCCL from source, but it won't be ready for the 1.12 release, so this is a very welcome contribution.

**Comment by smit-hinsu** [comment]
Marking as "ready to pull" to start pull process while tests are running so that this PR can make it to TF 1.12.

**Pull request merged**
