### PR TITLE
[XLA] Add required header

### PR DESCRIPTION
**Pull request by DavidNorman**
For me, the master branch fails to build with this header not explicitly included in the source file.  I'm not sure where the transitive inclusion occurs for the main CI system.  Perhaps it is better to avoid relying on transitive inclusions anyway.

### CODE REVIEW

**Comment by jlebar** [comment]
@gbaned I'm leaving the project at the end of July, so we need to stop tagging me as the point of contact for all XLA PRs/bugs.  Ideally we'd have an "XLA CPU/GPU group" in github, I dunno if that's something you could help us set up.  Otherwise I've updated go/tf-who-do-i-notify with the new point of contact.

**Review by jlebar — COMMENTED** [review]
Thanks for the PR.  Sorry to send this one back for a second round, but there's a particular way that `#includes` are formatted.  Normally formatting in PRs doesn't really matter, because we run everything through clang-format when we import it.  But I am not sure clang-format will DTRT given the empty line between the two sets of includes.

Can you remove that empty line?

**Comment by DavidNorman** [comment]
sure thing.  not a problem

**Comment by DavidNorman** [comment]
done

**Review by jlebar — APPROVED** [review]

**Comment by DavidNorman** [comment]
thanks.  as you can probably guess, i'm trying to get our repo more in line with the public one, so we can transition more easily to making it actually public.

**Comment by gbaned** [comment]
> @gbaned I'm leaving the project at the end of July, so we need to stop tagging me as the point of contact for all XLA PRs/bugs. Ideally we'd have an "XLA CPU/GPU group" in github, I dunno if that's something you could help us set up. Otherwise I've updated go/tf-who-do-i-notify with the new point of contact.

@jlebar Thank you for the update. Sure, we will assign XLA PRs/bugs to new point of contact as per go/tf-who-do-i-notify

**Comment by DavidNorman** [comment]
H @gbaned I do not think that the MacOS contrib could be failing due to this change.

**Comment by jlebar** [comment]
Don't worry, we are not holding this because of that.  Our system for
accepting these changes is just...designed to be as slow and opaque as
possible.

**Comment by jlebar** [comment]
This is submitted internally, it just looks like our to-github updater is stuck, no updates since 3 days ago.

**Pull request merged**
